### PR TITLE
sql: enum introspection improvements

### PR DESCRIPTION
**Pull request by arulajmani**
See individual commit messages for details.

### CODE REVIEW

**Review by otan — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57197)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/sql/pg_catalog.go, line 1303 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57197#-MNKVLbQD7qi-g-6kK1q:-MNKVLbQD7qi-g-6kK1r:b-2pxdv0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4c707802aea92071eb532f926cd18e0cf64f5f9/pkg/sql/pg_catalog.go#L1303)):*
> ```Go
> 		return forEachTypeDesc(ctx, p, dbContext, func(_ *dbdesc.Immutable, _ string, typDesc *typedesc.Immutable) error {
> 			// We only want to iterate over ENUM types and multi-region enums.
> 			if typDesc.Kind != descpb.TypeDescriptor_ENUM &&
> ```

nit: nicer as a switch statement:

```
switch typDesc.Kind {
    case ENUM,
             MULTIREGION_ENUM:
          return nil
}
```
___
*[pkg/sql/delegate/show_enums.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57197#-MNKV17JB_f5l0zMeL6a:-MNKV17JB_f5l0zMeL6b:b-qespmd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dc582a6a7927671312fef7e4c07eaa0c23317f1/pkg/sql/delegate/show_enums.go#L63)):*
> ```Go
> WHERE types.typtype = 'e' %[2]s
> ORDER BY (nsp.nspname, types.typname)
> `, &name.CatalogName, schemaClause)
> ```

should this be lex.EscapeSQLString(name.CatalogName) ?

**Review by arulajmani — COMMENTED** [review]
RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57197#-:-MNOxHk29-llk049wl-Q:bb72pd0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/pg_catalog.go, line 1303 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57197#-MNKVLbQD7qi-g-6kK1q:-MNOxBVIBSlGUJQEwE60:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4c707802aea92071eb532f926cd18e0cf64f5f9/pkg/sql/pg_catalog.go#L1303)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: nicer as a switch statement:

```
switch typDesc.Kind {
    case ENUM,
             MULTIREGION_ENUM:
          return nil
}
```
</blockquote></details>

Done
___
*[pkg/sql/delegate/show_enums.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57197#-MNKV17JB_f5l0zMeL6a:-MNOjUtl1VhaC_fkJCLb:b7ylvfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dc582a6a7927671312fef7e4c07eaa0c23317f1/pkg/sql/delegate/show_enums.go#L63)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

should this be lex.EscapeSQLString(name.CatalogName) ?
</blockquote></details>

Naa. We're using this to construct a FQN of the pg_enum table, which won't work if we put quotes around the db name.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57197)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/delegate/show_enums.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57197#-MNKV17JB_f5l0zMeL6a:-MNOy3Yc4_SdiyRV4Cff:bkssbba) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dc582a6a7927671312fef7e4c07eaa0c23317f1/pkg/sql/delegate/show_enums.go#L63)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Naa. We're using this to construct a FQN of the pg_enum table, which won't work if we put quotes around the db name. 
</blockquote></details>

Try this out:

```
CREATE DATABASE "I am tricksy";
SHOW ENUMS FROM "I am tricksy";
```

**Comment by otan** [comment]
___
*[pkg/sql/delegate/show_enums.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57197#-MNKV17JB_f5l0zMeL6a:-MNPmvvlBqhFof72BYuA:b-bj99m1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dc582a6a7927671312fef7e4c07eaa0c23317f1/pkg/sql/delegate/show_enums.go#L63)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Try this out:

```
CREATE DATABASE "I am tricksy";
SHOW ENUMS FROM "I am tricksy";
```
</blockquote></details>

yeah and use `EncodeRestrictedSQLIdent` in that case.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57197)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/delegate/show_enums.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57197#-MNKV17JB_f5l0zMeL6a:-MNQ2LeI-BSMtuixk4DD:b-iw0meu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dc582a6a7927671312fef7e4c07eaa0c23317f1/pkg/sql/delegate/show_enums.go#L63)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

yeah and use `EncodeRestrictedSQLIdent` in that case.
</blockquote></details>

Talked w @otan offline -- the case above works because the `x.Name.String()` escapes correctly, so we don't need anything special here.

**Review by otan — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57197)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

**Comment by arulajmani** [comment]
TFTR! 

bors r=otan

**Comment by arulajmani** [comment]
bors r=otan

**Pull request merged**
