### PR TITLE
sql: temporarily removing multinode parallel test

### LINKED ISSUE #8089: sql: failure in TestParallel (time out, but not on shutdown)
https://circleci.com/gh/tschottdorf/cockroach/2643

cc @RaduBerinde 

```
goroutine 31196 [semacquire]:
sync.runtime_Semacquire(0xc82022fb1c)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc82022fb18)
	/usr/local/go/src/sync/mutex.go:83 +0x1c4
github.com/cockroachdb/cockroach/storage.(*Store).ReplicaCount(0xc82022f900, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2058 +0x3d
github.com/cockroachdb/cockroach/storage.(*Store).Descriptor(0xc82022f900, 0xd75b35, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2046 +0xa2
github.com/cockroachdb/cockroach/storage.(*Store).ComputeMetrics(0xc82022f900, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2838 +0x45
github.com/cockroachdb/cockroach/testutils/testcluster.(*TestCluster).WaitForFullReplication.func1(0xc82022f900, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/testutils/testcluster/testcluster.go:436 +0x3a
github.com/cockroachdb/cockroach/storage.(*Stores).VisitStores(0xc8204f2040, 0xc822ea5608, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/stores.go:121 +0x102
github.com/cockroachdb/cockroach/testutils/testcluster.(*TestCluster).WaitForFullReplication(0xc820114900, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/testutils/testcluster/testcluster.go:435 +0x1f8
github.com/cockroachdb/cockroach/sql_test.(*parallelTest).setup(0xc820114540, 0xc820114660)
	/go/src/github.com/cockroachdb/cockroach/sql/parallel_test.go:212 +0xa97
github.com/cockroachdb/cockroach/sql_test.(*parallelTest).run(0xc820114540, 0xc8203d8060, 0x24)
	/go/src/github.com/cockroachdb/cockroach/sql/parallel_test.go:138 +0x4d4
github.com/cockroachdb/cockroach/sql_test.TestParallel(0xc820a99b00)
	/go/src/github.com/cockroachdb/cockroach/sql/parallel_test.go:232 +0x43e
testing.tRunner(0xc820a99b00, 0x2747058)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

```

### PR DESCRIPTION
**Pull request by RaduBerinde**
Even though the workload of this test was already disabled, there are occasional
timeouts during the setup of the test. Removing it altogether for now as it
looks it will take a while to figure out all the issues.

Fixes #8089.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8144)

### CODE REVIEW

**Comment by tamird** [comment]
MIght be nicer to move these tests into a different directory so that inspect of the source still reveals their existence. LGTM.

**Comment by RaduBerinde** [comment]
TFTR! Anything under `partestdata/` will be attempted to be run in the test, so I would have to put them in some other place which would be confusing. They should be resurrected soon, we are working on it under #8057.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8144#-:-KNw_61-0PX_5fhO_W9J:-732294592)*

**Comment by tamird** [comment]
You could update the test to exclude files with some special suffix? Just
spitballing.

**Comment by petermattis** [comment]
LGTM

I'm fine with deleting the files temporarily as long as there is active work to fix this test (which it sounds like there is).

**Pull request merged**
