### PR TITLE
sql,descs: add & adopt descriptor_validation session var

### PR DESCRIPTION
**Pull request by postamar**
This commit removes the `sql.catalog.descs.validate_on_write.enabled` cluster setting and replaces it with the `descriptor_validation` session variable. The default value is 'on' which indicates that catalog descriptors are to be validated when both read from- and written to the system.descriptor table. Other possible values are 'off' which disables validation entirely and 'read_only' which disables it for writes.

Informs #50651.

Release note (sql change): added a new 'descriptor_validation' session variable which can be set to 'read_only' or 'off' to disable descriptor validation, which may be useful when mitigating or recovering from catalog corruption.

### CODE REVIEW

**Comment by postamar** [comment]
@ajwerner this is ready for review. This commit only covers part of the work required for https://github.com/cockroachdb/cockroach/issues/50651 but I'd like to merge it ahead of the rest because it has enough merit of its own and offers a strict improvement over the use of a cluster setting for controlling descriptor validation behaviour. 

For the actual DROP story I'm not quite sure what to do yet and I'll want to explore. Contrary to initial impressions perhaps the declarative schema changer will prove more robust after all. This would involve making `scdecomp` robust in the face of descriptor corruption. If this turns out to be possible, then I have a feeling this is going to be preferable, because the output of `EXPLAIN (DDL) DROP ...` might then be enough for a power user/support specialist to determine whether it's safe to go ahead or not.

**Review by ajwerner — APPROVED** [review]
:lgtm: this is a good change. Just the nit on narrowing the interface scope for sessiondata. I could see building a little adapter which has the methods you really need. It's a bit of ceremony. Maybe like:


```go
package descs

type SessionData interface {
    TemporarySchemaProvider
    ValidationMode() sessiondatapb.ValidationMode
}
```

```go
package catsessiondata

type SessionData sessiondata.Stack

func MakeSessionData(sds *sessiondata.Stack) *SesssionData {   return (*SessionData)(sds) }

func (sd *SessionData) toStack() *sessiondata.Stack { return (*sessiondata.Stack)(sd) }

func (sd *SessionData) ValidationMode() sessiondatapb.ValidationMode { 
    return sd.toStack().Top().ValidationMode()
}
```

> Reviewed 35 of 45 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90488#-:-NFOS8KlD4JVIdSLQcD2:b-5qn449)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)

___
*[`pkg/sql/catalog/descs/collection.go` line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90488#-NFORWu_-bu-RYK-Gn6f:-NFORWu_-bu-RYK-Gn6g:bhii8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/a15b49225f491480045800a99d4c6c67e3577a74/pkg/sql/catalog/descs/collection.go#L51)):*
> ```Go
> 	systemDatabase *catkv.SystemDatabaseCache,
> 	virtualSchemas catalog.VirtualSchemas,
> 	sds *sessiondata.Stack,
> ```

nit: how would you feel about narrowing the scope of the interface you need here to just the relevant parts of the sessiondata.Stack? Time has shown that narrowing the dependencies prevents sprawl and increases clarity.

**Comment by postamar** [comment]
Thanks for the suggestion. I hesitated to do that, worrying it might be overkill. I might have to implement that interface both on SessionData and on Stack, because AFAIK the stack has a different lifecycle than the collection: the collection gets reset every txn but the stack may change within the txn. That doesn't bother me, though.

**Comment by postamar** [comment]
Assuming that CI is happy, this is ready for another look. I think your suggested changes were worth it.

**Review by ajwerner — APPROVED** [review]
:lgtm_strong: 

> Reviewed 42 of 48 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90488#-:-NFVN9f3981uL7s9G_Ka:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by postamar** [comment]
Thanks for the reviews!

bors r+

**Pull request merged**
