### PR TITLE
cmd/roachtest: add engine/switch/encrypted test

### LINKED ISSUE #48154: roachtest: add engine/switch variant which uses encryption-at-rest
We should add an `engine/switch` variant which uses encryption at rest, verifying that the RocksDB and Pebble implementations of encryption at rest are compatible.

See `cmd/roachtest/kv.go` for an example of a roachtest which specifies both unencrypted and encrypted variants. We'll have to pass an `--encrypt=%t` start arg. I believe `roachprod` takes care of the heavy lifting of translating that into the correct flags for `cockroach start`.

### PR DESCRIPTION
**Pull request by jbowens**
Add an encrypted variant to the engine/switch test to ensure
compatability of the encrypted FS implementations.

Fix #48154.

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

Did you try running this manually a few times?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48175#-:-M66SNab8tdAxPUC2m4b:bu40xpg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, and @petermattis)

___
*[pkg/cmd/roachtest/engine_switch.go, line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48175#-M66SDNl66ZF6zDXQMOG:-M66SDNl66ZF6zDXQMOH:b-k90q2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f8a29b0731858b2a71374b149ba94a471569a71/pkg/cmd/roachtest/engine_switch.go#L144)):*
> ```Go
> 	})
> 	r.Add(testSpec{
> 		Name:       fmt.Sprintf("engine/switch/encrypted,nodes=%d", n),
> ```

Nit: the naming idiom seems to be separate "path" components for each parameter. So I think this should be `engine/switch/encrypted/nodes=%d`.

**Comment by jbowens** [comment]
> Did you try running this manually a few times?

Yeah, a few times locally and a couple on gcp.

TFTR!

**Pull request merged**
