### PR TITLE
ui: show a hint when a RPC result encounters HTTP 403

### LINKED ISSUE #44600: ui:provide a user-friendly message when non-admin user accesses privileged web page
This is related to [tech advisory](https://forum.cockroachlabs.com/t/cockroachdb-technical-alert-01-22-2020/3433). Today, in Cockroach 19.2.2 and 19.1.6, if non-admin user navigates to a priveledged page on the UI, they will be greeted with `Internal Server Error`, see image below.

internal-server-error

I recommend to change the default message to something less dramatic and aesthetically pleasing. 
Instead of throwing that error, it should say something like `the current user does not have rights to access this page.` and point to mitigation steps, i.e. add user to `admin` role.

### LINKED ISSUE #45073: Statements sections is returning an Internal Server Error after upgrading to v19.2.4
After upgrading from v19.2.3 to v19.2.4, the Statements section in the admin console stopped working. We are running on CentOS 7. This happens on both our dev and production DB.

The browser console shows repeated errors:
GET ***.com/_status/statements 500 (Internal Server Error).

Screenshot 2020-02-13 at 11 03 11.

Is anybody else experiencing the issue?

### PR DESCRIPTION
**Pull request by knz**
Fixes #44600.
Fixes #45073.

A user hint is now displayed in the UI when
error 403 is encountered.

image

Release note (admin ui change): The web UI now reports a clearer
message when a non-admin user uses an admin-only feature.

### CODE REVIEW

**Comment by knz** [comment]
cc @piyush-singh

**Comment by knz** [comment]
Intending to backport this to relieve support burden after security fixes in 19.2.2 and 19.1.6

**Comment by kenliu** [comment]
This is a good idea, thanks for fixing this

**Comment by dhartunian** [comment]
@knz and I discussed this in person and I will be pushing a unit test to this PR before it's merged that exercises the solution.

**Comment by knz** [comment]
We'll want this in the next patch revisions for 19.1 and 19.2. Please take the release schedule into account in your prioritization. Thanks

**Comment by piyush-singh** [comment]
Since this is still open, would it be possible to modify this message to include a link to documentation about the permissions issue? @taroface do we have a link in the docs that would provide the relevant info?

**Comment by knz** [comment]
good idea! But I don't actually know how to do this :sweat_smile: 
I hope david can chime in

**Comment by taroface** [comment]
> Since this is still open, would it be possible to modify this message to include a link to documentation about the permissions issue? @taroface do we have a link in the docs that would provide the relevant info?

@piyush-singh It's still being reviewed in a PR, but once merged this link should be best: https://www.cockroachlabs.com/docs/stable/admin-ui-overview.html#admin-ui-access

**Comment by taroface** [comment]
> @piyush-singh It's still being reviewed in a PR, but once merged this link should be best: https://www.cockroachlabs.com/docs/stable/admin-ui-overview.html#admin-ui-access

FYI this link is now live

**Comment by dhartunian** [comment]
@taroface what do you think of this?

Screen Shot 2020-03-03 at 11 45 37 PM

The link is using an internal UI function that automatically sets the correct db version in the URL. Is there a reason I should pin it to `stable` in the URL?

**Comment by dhartunian** [comment]
Note to self: make warning yellow.

**Comment by dhartunian** [comment]
@Annebirzin @piyush-singh the design of that box aggregates multiple possible error messages, should I just always make it yellow? It's not 100% straightforward to make yellow just on that one message.

**Comment by dhartunian** [comment]
Leaving color as-is for now. Fixed copy to have link separate and add period.

Screen Shot 2020-03-09 at 6 32 38 PM

**Review by dhartunian — APPROVED** [review]

**Pull request merged**
