### PR TITLE
logictest: audit logic tests to enable default configs

### LINKED ISSUE #46237: colexec: audit logic test configurations
We need to make sure that as many logic tests as possible run with the default configurations.

### PR DESCRIPTION
**Pull request by yuzefovich**
Release justification: non-production code changes.

This commit extends the number of configurations on some of the logic
tests (mostly by removing explicit configs so that all default ones are
used). It also uncomments few things, renames a few files, and moves the
contents of `exec_window` into `window`.

It also adds a new `5node-dist-vec-disk` config that about 10 files or
so are now run with.

Additionally, it removes `5node-local` config (which was used in two
files), removes `dist-` part from all 5 node config names, and adds
a special alias `5node-default-configs` which includes all 5 node
configs.

Fixes: #46237.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46270)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/logictest/testdata/logic_test/column_families, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46270#-M2kFwo19L8_zKcBtZ2o:-M2kFwo19L8_zKcBtZ2p:b-zva6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/82164eae503af3af49206e488e97369fe8f68aca/pkg/sql/logictest/testdata/logic_test/column_families#L4)):*
> ```
> 
> # TODO(rohany): enable all of the configs below.
> # LogicTest: local local-vec-off local-vec fakedist fakedist-vec-off fakedist-vec fakedist-metadata
> ```

@rohany do you know why the trace query at the bottom of this file returns slightly different output with some configurations?
```
        --- FAIL: TestLogic/local-vec-off/column_families (1.04s)
            logic.go:1826: 
                 
                testdata/logic_test/column_families:66: SELECT message FROM [SHOW KV TRACE FOR SESSION] WHERE
                message LIKE 'fetched: /t/primary/%'
                ORDER BY message
                expected:
                    fetched: /t/primary/1/2.00/x -> /1.00
                    fetched: /t/primary/1/2/y -> /2.00
                    fetched: /t/primary/1/2/z -> /1
                but found (query options: "") :
                    fetched: /t/primary/1/2/x -> /1.00
                    fetched: /t/primary/1/2/y -> /2.00
                    fetched: /t/primary/1/2/z -> /1
```

**Comment by rohany** [comment]
Hmm, it seems to be some sort of small variation between how the fetcher and the cfetcher work. I'd be fine moving this tracing failure case into the `execbuilder` tests to have it only run under local config (i looked at this for some time with no real success).

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46270)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/logictest/testdata/logic_test/column_families, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46270#-M2kFwo19L8_zKcBtZ2o:-M2kSUK-1mJ69vKeRHp9:b-w6mfaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/82164eae503af3af49206e488e97369fe8f68aca/pkg/sql/logictest/testdata/logic_test/column_families#L4)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

@rohany do you know why the trace query at the bottom of this file returns slightly different output with some configurations?
```
        --- FAIL: TestLogic/local-vec-off/column_families (1.04s)
            logic.go:1826: 
                 
                testdata/logic_test/column_families:66: SELECT message FROM [SHOW KV TRACE FOR SESSION] WHERE
                message LIKE 'fetched: /t/primary/%'
                ORDER BY message
                expected:
                    fetched: /t/primary/1/2.00/x -> /1.00
                    fetched: /t/primary/1/2/y -> /2.00
                    fetched: /t/primary/1/2/z -> /1
                but found (query options: "") :
                    fetched: /t/primary/1/2/x -> /1.00
                    fetched: /t/primary/1/2/y -> /2.00
                    fetched: /t/primary/1/2/z -> /1
```

</blockquote></details>

Ok, I removed the TODO and will leave up to you to decide whether this test should be moved.

**Review by asubiotto — CHANGES_REQUESTED** [review]
Great to see this!

> Reviewed 31 of 34 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46270#-:-M2s6AFSE7nCMKhV2XSK:b-699yfr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/distsql_agg, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46270#-M2s6JF11hpJqhmV5x4W:-M2s6JF24YvHqzFOWCFF:brwvtbu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7619e81c17e7185394f8408405a1e45c43bdbde3/pkg/sql/logictest/testdata/logic_test/distsql_agg#L1)):*
> ```
> # LogicTest: 5node-dist 5node-dist-vec 5node-dist-metadata 5node-dist-disk
> ```

Maybe we should have an equivalent of default configs but for `5node` configs. This would also include a `5node-dist-vec-disk`.
___
*[pkg/sql/logictest/testdata/logic_test/distsql_union, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46270#-M2s6nYf21q4yGRBs8sg:-M2s6nYgAGMHN3CCNQtP:bhaaini) ([raw file](https://github.com/cockroachdb/cockroach/blob/7619e81c17e7185394f8408405a1e45c43bdbde3/pkg/sql/logictest/testdata/logic_test/distsql_union#L1)):*
> ```
> # LogicTest: 5node-dist 5node-dist-vec 5node-dist-metadata 5node-dist-disk
> ```

Could you stress this test `make stress PKG=./pkg/sql/logictest TESTS=TestLogic//distsql_union`. I know we've had interesting concurrency issues in the past with `union` so might be good to see what the result here is now with `5node-dist-vec`
___
*[pkg/sql/logictest/testdata/logic_test/exec_merge_join, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46270#-M2s7Tty4XeBIQCJJoIp:-M2s7TtzARRmhkmQS9Fd:b-72zb8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec8ee4f2bf8b35de82b32b2aec6b85a5ada33295/pkg/sql/logictest/testdata/logic_test/exec_merge_join#L61)):*
> ```
> 
> query T
> SELECT url FROM [EXPLAIN ANALYZE SELECT t1.k FROM t AS t1, t AS t2 WHERE t1.k = t2.k]
> ```

Can we put this test in another file? I know we have some specific `explain_analyze` tests somewhere
___
*[pkg/sql/logictest/testdata/logic_test/exec_merge_join_dist, line 46 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46270#-M2s7ajj7pUXmwVbsuiW:-M2s7ajj7pUXmwVbsuiX:bwd36po) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec8ee4f2bf8b35de82b32b2aec6b85a5ada33295/pkg/sql/logictest/testdata/logic_test/exec_merge_join_dist#L46)):*
> ```
> 
> query T
> SELECT url FROM [EXPLAIN (DISTSQL) SELECT * FROM l LEFT OUTER JOIN r USING(a) WHERE a = 2]
> ```

Same with this?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46270)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/logictest/testdata/logic_test/distsql_agg, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46270#-M2s6JF11hpJqhmV5x4W:-M38OPeo0whgcla55QXU:b-ts42p4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7619e81c17e7185394f8408405a1e45c43bdbde3/pkg/sql/logictest/testdata/logic_test/distsql_agg#L1)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Maybe we should have an equivalent of default configs but for `5node` configs. This would also include a `5node-dist-vec-disk`.
</blockquote></details>

Why not, added.
___
*[pkg/sql/logictest/testdata/logic_test/distsql_union, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46270#-M2s6nYf21q4yGRBs8sg:-M38Qjqp1mtOxCgdGx5Z:bfyxpty) ([raw file](https://github.com/cockroachdb/cockroach/blob/7619e81c17e7185394f8408405a1e45c43bdbde3/pkg/sql/logictest/testdata/logic_test/distsql_union#L1)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Could you stress this test `make stress PKG=./pkg/sql/logictest TESTS=TestLogic//distsql_union`. I know we've had interesting concurrency issues in the past with `union` so might be good to see what the result here is now with `5node-dist-vec`
</blockquote></details>

Stressed it for 5 minutes with no failures locally and will kick off another run on gceworker.
___
*[pkg/sql/logictest/testdata/logic_test/exec_merge_join, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46270#-M2s7Tty4XeBIQCJJoIp:-M38PS_C24GcPVgAXupj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec8ee4f2bf8b35de82b32b2aec6b85a5ada33295/pkg/sql/logictest/testdata/logic_test/exec_merge_join#L61)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Can we put this test in another file? I know we have some specific `explain_analyze` tests somewhere
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/exec_merge_join_dist, line 46 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46270#-M2s7ajj7pUXmwVbsuiW:-M38PpLz1F224OGceq6O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec8ee4f2bf8b35de82b32b2aec6b85a5ada33295/pkg/sql/logictest/testdata/logic_test/exec_merge_join_dist#L46)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Same with this?
</blockquote></details>

Done.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46270)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/logictest/testdata/logic_test/distsql_union, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46270#-M2s6nYf21q4yGRBs8sg:-M38d6DT5eYSg1-h1GYj:b-ngnnev) ([raw file](https://github.com/cockroachdb/cockroach/blob/7619e81c17e7185394f8408405a1e45c43bdbde3/pkg/sql/logictest/testdata/logic_test/distsql_union#L1)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Stressed it for 5 minutes with no failures locally and will kick off another run on gceworker.
</blockquote></details>

```
4296 runs so far, 0 failures, over 53m15s
^C4296 runs completed, 0 failures, over 53m16s
```
on gceworker, so I think we're good for now :)

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 34 files at r1, 15 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46270#-:-M3AtO2073lr1ZmfCBem:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/distsql_agg, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46270#-M2s6JF11hpJqhmV5x4W:-M3ArAq-4qJR_OXyHQ2j:b-yo680l) ([raw file](https://github.com/cockroachdb/cockroach/blob/7619e81c17e7185394f8408405a1e45c43bdbde3/pkg/sql/logictest/testdata/logic_test/distsql_agg#L1)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Why not, added.
</blockquote></details>

Is there a way to do `# LogicTest: 5node-default-configs` which would be parsed and cause the file to be run with all of these `5node` configs?

**Review by yuzefovich — COMMENTED** [review]
I did some more refactoring and added another commit. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46270#-:-M3Co-3w192rP2GlEfd2:bvrwj2s)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[Makefile, line 127 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/46270#-M3CnfhkAnpF2VxHqiZ8:-M3CnfhkAnpF2VxHqiZ9:bur1w4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/b50d00ce4612b5921a9758c246eaf49573474cb3/Makefile#L127)):*
> ```Makefile
> 
> ## Test timeout to use for regular tests.
> TESTTIMEOUT := 30m
> ```

I wonder whether we should separate out timeout for logic tests.
___
*[pkg/sql/logictest/testdata/logic_test/distsql_agg, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46270#-M2s6JF11hpJqhmV5x4W:-M3CgB9SC23O_u8M-9J2:bcus9ab) ([raw file](https://github.com/cockroachdb/cockroach/blob/7619e81c17e7185394f8408405a1e45c43bdbde3/pkg/sql/logictest/testdata/logic_test/distsql_agg#L1)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is there a way to do `# LogicTest: 5node-default-configs` which would be parsed and cause the file to be run with all of these `5node` configs?
</blockquote></details>

Nice idea, done.

**Comment by yuzefovich** [comment]
Removed the second commit to extract into a separate PR, but still I'd appreciate another look.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 39 of 39 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46270#-:-M3G50j15Zp7f8gh9qf4:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
