### PR TITLE
 *: remove the remaining uses of ReplicaDescriptors.Unwrap

### LINKED ISSUE #37916: *: audit and migrate uses of roachpb.ReplicaDescriptors.Unwrap
Each of these needs to be migrated to `All`, `Voters`, `Learners` (or one of the more specific methods on `ReplicaDescriptors`).

- [x] Should learners be allowed to serve follower reads? No for now. A learner is a temporary state on the way to a full voting replica. One can certainly imagine the benefits to a replica that can be read from in the past but doesn't affect quorum, but this is considered out of scope for the current project, which is to get rid of the technical debt of preemptive snapshots. This means learners also don't need closed timestamps.

- [x] Should learners be included in replica metrics? Definitely not counted as a live replica. Probably shouldn't be included in calcBehindCount. These are about the health of the voters.
https://github.com/cockroachdb/cockroach/blob/39f934d30b565b6c8271dd2c96040b073309451a/pkg/storage/replica_metrics.go#L204

- [ ] Should we add metrics specifically for learners?

- [x] Quota pool? Doesn't delay until it has the snapshot, then it does. https://github.com/cockroachdb/cockroach/pull/35787#issuecomment-490004991
https://github.com/cockroachdb/cockroach/blob/39f934d30b565b6c8271dd2c96040b073309451a/pkg/storage/replica_proposal_quota.go#L132
https://github.com/cockroachdb/cockroach/blob/39f934d30b565b6c8271dd2c96040b073309451a/pkg/storage/replica_raft_quiesce.go#L83

- [x] Log truncation? Treat as a normal follower https://github.com/cockroachdb/cockroach/pull/35787#issuecomment-490005442

- [X] Should learners block quiescence? Yes

- [x] Allocator. Definitely we want to include learners when deciding when to add a replica, otherwise we could race and add too many. Probably should consider them for removal as well. Rebalance? I think yes for consistency with the other two.

- [x] Store QPS balancing: We don't want to use learners as candidates, since they can't be leaseholders. Do we use them when figuring out per-store qps/diversity? Probably also no

- [x] Should learners be included in consistency check? Doesn't seem particularly interesting to include them but I also don't see the harm
https://github.com/cockroachdb/cockroach/blob/39f934d30b565b6c8271dd2c96040b073309451a/pkg/storage/replica_consistency.go#L307

- [x] Do learner replicas block decommissioning? On one hand, it seems like we should be waiting for every replica to be removed before the node can be turned down, but on the other hand, it can't be affecting quorum, so how disruptive is it to shut off a node with only learners left?
https://github.com/cockroachdb/cockroach/blob/39f934d30b565b6c8271dd2c96040b073309451a/pkg/server/admin.go#L1426

- [x] How should we treat learner replicas in the admin ui (node fullness, num replicas etc)?
https://github.com/cockroachdb/cockroach/blob/39f934d30b565b6c8271dd2c96040b073309451a/pkg/server/admin.go#L1426

- [x] Should learner replicas get passed to queues? Initial guess is it depends on the queue and this should be an option in `queueConfig` like `needsLease`.

- [x] The merge queue needs all replicas for the two ranges to be co-located. Should we just drop learners from both sides?

- [x] What happens if a range with a learner splits?

- [x] `(Replica).changeReplicas` and `(Store).AdminRelocateRange` both are dealing with a specific set of recomputed replicas and so want all replicas.

- [x] `(Replica).adminScatter` has a RandomizeLeases option, which only wants voters since learners can't be leaseholders
https://github.com/cockroachdb/cockroach/blob/39f934d30b565b6c8271dd2c96040b073309451a/pkg/storage/replica_command.go#L1425

- [x] We implemented the `(ReplicaDescriptors).QuorumSize` to use voters, which is correct but looking more closely at the places where we use quorum size, it seems like we might want to include learners in some of them. Otherwise, we're basically making a decision on information that is very shortly going to be outdata. Maybe this is okay? Worth thinking about more closely

  Example: In `processOneChange`, not making changes while we don't have quorum https://github.com/cockroachdb/cockroach/blob/39f934d30b565b6c8271dd2c96040b073309451a/pkg/storage/replicate_queue.go#L296-L306

- [ ] `(Store).Capacity` and `updateReplicationGauges` update a set of counts. What downstream uses these counts? What if they have different preferences for whether it includes learners?

- [x] How should learner snapshots behave? There are a bunch of places preemptive snapshots get special cased (they can be rejected etc), are learner snaps the same?

- [x] A couple of tests also rely on the "snapshot intersects existing range" error to detect when we can't upreplicate over some old replica that needs to be gc'd but hasn't yet. I guess learner snapshots need the same behavior? My initial impression of this is that it seems a little bit of an abstraction breakage for a snapshot to be the detection mechanism for this, but you do need knowledge of the actual state of things on some remote node and it's not clear that anything else is better

### PR DESCRIPTION
**Pull request by danhhz**
Closes #37916

Release note: None

### CODE REVIEW

**Comment by danhhz** [comment]
First commit is #39151. No hurry on this review!

**Review by tbg — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 22 of 22 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39157)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz)

___
*[pkg/storage/allocator_test.go, line 4774 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39157#-Ll0Z9pcC7YBzXWWTUwq:-Ll0Z9pcC7YBzXWWTUwr:b-2xz82y) ([raw file](https://github.com/cockroachdb/cockroach/blob/04d31373f8f216bb93b435b8206dffd6765f3a18/pkg/storage/allocator_test.go#L4774)):*
> ```Go
> }
> 
> func TestAllocatorRemoveLearner(t *testing.T) {
> ```

Where'd this go?
___
*[pkg/storage/replica_raft_quiesce.go, line 79 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39157#-Ll0ZMH30Ho5TBDvtBNg:-Ll0ZMH30Ho5TBDvtBNh:bfm3ph7) ([raw file](https://github.com/cockroachdb/cockroach/blob/14c4f1c2d102379b7743fea726db2f1aa8349c9d/pkg/storage/replica_raft_quiesce.go#L79)):*
> ```Go
> 		// NB: we know there's a non-nil RaftStatus because internalRaftGroup isn't nil.
> 		r.mu.lastUpdateTimes.updateOnUnquiesce(
> 			// WIP this All is a guess
> ```

It's correct, when the group unquiesces we want to treat all replicas as active for the moment (since they may not have contacted us recently, and we don't want to assume they're all dead).
___
*[pkg/storage/replicate_queue.go, line 197 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39157#-Ll0Za-TCi6pa4WtWr5_:-Ll0Za-UClvonn576DZN:b-m32398) ([raw file](https://github.com/cockroachdb/cockroach/blob/14c4f1c2d102379b7743fea726db2f1aa8349c9d/pkg/storage/replicate_queue.go#L197)):*
> ```Go
> }
> 
> func (rq *replicateQueue) computeAction(
> ```

Why did you hoist the learner stuff out of the allocator? Not saying this is necessarily bad, but leave a comment somewhere.
___
*[pkg/storage/replicate_queue.go, line 275 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39157#-Ll0Zzti6qHDXhqIa3nH:-Ll0Zztj2DoOKk4tmgjU:b-3gbfdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/14c4f1c2d102379b7743fea726db2f1aa8349c9d/pkg/storage/replicate_queue.go#L275)):*
> ```Go
> 		if rq.canTransferLease() &&
> 			rq.allocator.ShouldTransferLease(
> 				ctx, zone, rangeInfo.Replicas, lease.Replica.StoreID, desc.RangeID, repl.leaseholderStats) {
> ```

Is this right? Add a comment.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39157)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz and @tbg)

___
*[pkg/storage/replicate_queue.go, line 197 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39157#-Ll0Za-TCi6pa4WtWr5_:-Ll3DBQwD6OnX_-M0OmO:bg0o5p8) ([raw file](https://github.com/cockroachdb/cockroach/blob/14c4f1c2d102379b7743fea726db2f1aa8349c9d/pkg/storage/replicate_queue.go#L197)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Why did you hoist the learner stuff out of the allocator? Not saying this is necessarily bad, but leave a comment somewhere.
</blockquote></details>

I was trying to make it obvious within the allocator code that it was only dealing with voters, without littering it with `.Replicas().All()` or `.Replicas().Voters()` calls, each accompanied by a comment. I don't super-love this refactor, so I'll poke at this again. It's tough because I think this code wants a bit larger of a refactor, but I also don't think it's the right timing for me to do that right now
___
*[pkg/storage/replicate_queue.go, line 275 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39157#-Ll0Zzti6qHDXhqIa3nH:-Ll3DgoRBBDllq_30qVp:bd6h6nq) ([raw file](https://github.com/cockroachdb/cockroach/blob/14c4f1c2d102379b7743fea726db2f1aa8349c9d/pkg/storage/replicate_queue.go#L275)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Is this right? Add a comment.
</blockquote></details>

This is pretty good evidence that I failed in my goals above. I was hoping to make `rangeInfo.Replicas` the go to place for replicas in all allocator/replicateQ code, and to have it produced in one place that did the learners check. But you having to ask this question tips me off that it's not as obvious as I was looking for

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39157)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/storage/allocator_test.go, line 4774 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39157#-Ll0Z9pcC7YBzXWWTUwq:-Ll8vRnR29i7F6d_gSd9:bu7oxxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/04d31373f8f216bb93b435b8206dffd6765f3a18/pkg/storage/allocator_test.go#L4774)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Where'd this go?
</blockquote></details>

It's back! : - D
___
*[pkg/storage/replica_raft_quiesce.go, line 79 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39157#-Ll0ZMH30Ho5TBDvtBNg:-Ll8vUj53dH8d9OM3rmb:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/14c4f1c2d102379b7743fea726db2f1aa8349c9d/pkg/storage/replica_raft_quiesce.go#L79)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

It's correct, when the group unquiesces we want to treat all replicas as active for the moment (since they may not have contacted us recently, and we don't want to assume they're all dead).
</blockquote></details>

:thumbsup: 
___
*[pkg/storage/replicate_queue.go, line 197 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39157#-Ll0Za-TCi6pa4WtWr5_:-Ll8vYGJ7ajdKmCdaLyY:b-9cv3nq) ([raw file](https://github.com/cockroachdb/cockroach/blob/14c4f1c2d102379b7743fea726db2f1aa8349c9d/pkg/storage/replicate_queue.go#L197)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I was trying to make it obvious within the allocator code that it was only dealing with voters, without littering it with `.Replicas().All()` or `.Replicas().Voters()` calls, each accompanied by a comment. I don't super-love this refactor, so I'll poke at this again. It's tough because I think this code wants a bit larger of a refactor, but I also don't think it's the right timing for me to do that right now
</blockquote></details>

Thanks for pushing back on this. I think this new version is better
___
*[pkg/storage/replicate_queue.go, line 320 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39157#-Ll8vEqT7x4mcpr0hi04:-Ll8vEqU-p7vKGxuBvf9:bwz3udu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4928e811aa052757fc7440bf3ce052e5da6d22cd/pkg/storage/replicate_queue.go#L320)):*
> ```Go
> 	voterReplicas := desc.Replicas().Voters()
> 
> 	// WIP there's all sorts of `return true, nil` below, which is what it was
> ```

It feels like some of these should be `false, nil` (noop, rangeunavailable) and some should get comments on why we're retrying ("range of replica %s was identified as having dead replicas, but no dead replicas were found")

**Review by tbg — APPROVED** [review]
> Reviewed 11 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39157)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz)

___
*[pkg/storage/replicate_queue.go, line 320 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39157#-Ll8vEqT7x4mcpr0hi04:-LlAzTeMAZZeOq5cfEYP:byotg3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/4928e811aa052757fc7440bf3ce052e5da6d22cd/pkg/storage/replicate_queue.go#L320)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

It feels like some of these should be `false, nil` (noop, rangeunavailable) and some should get comments on why we're retrying ("range of replica %s was identified as having dead replicas, but no dead replicas were found")
</blockquote></details>

You're talking about Noop and RangeUnavailable below, right? Agreed, either in this PR or a separate one.

**Comment by danhhz** [comment]
TFTR! I starting cleaning the allocator reason stuff up some more, but decided it was better left for a separate PR

bors r=tbg

**Pull request merged**
