### PR TITLE
sql: reuse test infrastructure in logic tests

### PR DESCRIPTION
**Pull request by jordanlewis**
This commit changes the behavior of `LogicTest` to not have to spin up and down a test server for every single subtest. Now, it spins up a single test server and cleans up created resources in between each subtest.

This is currently blocked on the resolution of #11701.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/11719)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/sql/logic_test.go, line 375 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11719#-KXqJoVVgaUEwbowBDxK:-KXqJoVVgaUEwbowBDxL:b-4wfu1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c308025ed5b091097c672ecf9ae04b74dda8cbd/pkg/sql/logic_test.go#L375)):*
> ```Go
> 	cleanup := t.setUser(security.RootUser)
> 	// drop all databases created in the test
> 	toDrop := make([]string, 0)
> ```

weird syntax

---

*[pkg/sql/logic_test.go, line 394 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11719#-KXqJtLRo4l2n8QbPCMB:-KXqJtLRo4l2n8QbPCMC:bixym2w) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c308025ed5b091097c672ecf9ae04b74dda8cbd/pkg/sql/logic_test.go#L394)):*
> ```Go
> 	}()
> 	for _, dbName := range toDrop {
> 		fmt.Printf("Dropping database %s...\n", dbName)
> ```

dont usually capitalize logs

---

*[pkg/sql/logic_test.go, line 395 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11719#-KXqK05es_0-x0r2BgMl:-KXqK05es_0-x0r2BgMm:bekkl7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c308025ed5b091097c672ecf9ae04b74dda8cbd/pkg/sql/logic_test.go#L395)):*
> ```Go
> 	for _, dbName := range toDrop {
> 		fmt.Printf("Dropping database %s...\n", dbName)
> 		if _, err := t.db.Exec(fmt.Sprintf("DROP DATABASE %s;", dbName)); err != nil {
> ```

no need for the semicolons

---

*[pkg/sql/logic_test.go, line 400 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11719#-KXqJwziUhWlV-GmukU5:-KXqJwziUhWlV-GmukU6:bbh4eeu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c308025ed5b091097c672ecf9ae04b74dda8cbd/pkg/sql/logic_test.go#L400)):*
> ```Go
> 	}
> 	if _, err := t.db.Exec(
> 		fmt.Sprintf("DELETE FROM system.users WHERE username='%s';", server.TestUser)); err != nil {
> ```

use a placeholder

---

*[pkg/sql/logic_test.go, line 1139 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11719#-KXqKEW3lLQY6L51oJJG:-KXqKEW3lLQY6L51oJJH:b2byeqv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c308025ed5b091097c672ecf9ae04b74dda8cbd/pkg/sql/logic_test.go#L1139)):*
> ```Go
> 
> 			if *printErrorSummary {
> 				defer l.printErrorSummary()
> ```

remove this defer

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11719#-:-KXqKLbb5c7a3MGdQYZW:bnfp4nl)*

**Comment by asubiotto** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/sql/logic_test.go, line 400 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11719#-KXqeA4pbCHw49wrH2fx:-KXqeA4pbCHw49wrH2fy:b-d7uytq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c308025ed5b091097c672ecf9ae04b74dda8cbd/pkg/sql/logic_test.go#L400)):*
> ```Go
> 	}
> 	if _, err := t.db.Exec(
> 		fmt.Sprintf("DELETE FROM system.users WHERE username='%s';", server.TestUser)); err != nil {
> ```

Some tests create more users than just `server.TestUser` (`pkg/sql/testdata/user` is an example).

---

*[pkg/sql/logic_test.go, line 479 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11719#-KXqg7jM2zkbLAPadLbm:-KXqfnQ_gY-gfauFpfha:b-wj8tvn) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c308025ed5b091097c672ecf9ae04b74dda8cbd/pkg/sql/logic_test.go#L479)):*
> ```Go
> 	}
> 
> 	if _, err := t.db.Exec(fmt.Sprintf("CREATE USER %s;", server.TestUser)); err != nil {
> ```

Small optimization could be to create this user when the server is started and not delete it when cleaning up after each test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11719)*

**Comment by jordanlewis** [comment]
This is also blocked on #10830, FWIW.

**Comment by RaduBerinde** [comment]
The logic tests seems to have slowed down a lot very recently (it was ~20 seconds, now it's more like 50). Is it known what caused it?

**Comment by jordanlewis** [comment]
I'm not sure what caused the slowdown, no. Could it be related to #11212?

**Comment by jordanlewis** [comment]
So this works after the addition of #12036, but it's actually slower than `TestLogic` on master. So I guess I'll close this unless someone has an idea of how to improve it.

**Comment by tamird** [comment]
Slower because dropping tables is slow? That's a real bummer.

**Comment by tamird** [comment]
Maybe @a-robinson wants to dig into why that's so slow!

**Comment by jordanlewis** [comment]
I pushed a WIP commit that demonstrates further progress on making this work in case someone is interested. It's blocked on fixing some tests that depend on OIDs getting generated the same every time, which won't work if more tables and databases have been created and deleted updating the unique descriptor ids. Also the eventlog tests are broken because they expect an empty eventlog to start as well as some other conditions.

**Comment by a-robinson** [comment]
@tamird - sorry, but I can't tell if you're being serious. Do you want me to investigate why it's slow? I'm certainly not opposed to checking it out.

**Comment by tamird** [comment]
Yeah, I was being serious given all the other sleuthing you've done recently

**Comment by petermattis** [comment]
I'm not surprised this is slower. Creating a single-node test server is fairly fast. 

Another avenue to speeding up the logic tests is to reuse the test server between files and add a new directive to reset it when needed by the test. Lots of tests could run perfectly fine in a randomly named database. The few that don't get special treatment.

**Comment by vivekmenezes** [comment]
I don't know what you want to do with this jordan. I'd like to see us add checking the reference counts on table leases at the end of each test.

**Comment by jordanlewis** [comment]
Okay going to close this as stale and wontfix.

**Pull request closed without merging**
