### PR TITLE
opt: Add correlated subquery execution tests and fix bugs

### PR DESCRIPTION
**Pull request by andy-kimball**
- Add a new suite of tests designed to test correlated subquery
execution.

- Fix two issues that I found during testing.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm: Very nice!

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/logictest/testdata/logic_test/subquery_correlated, line 4 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26284#-LDqsBCACZSk84f7GpWv:-LDqsBCACZSk84f7GpWw:b-kfb2hq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8d3a1783b44a4dccbec3c12179adbb075733014/pkg/sql/logictest/testdata/logic_test/subquery_correlated#L4)):*
> ```
> 
> statement ok
> CREATE TABLE c (c_id INT PRIMARY KEY, bill TEXT);
> ```

[nit] a comment with a high-level explanation of the tables would help (given that the table and column names are not very hepful)

---

*[pkg/sql/logictest/testdata/logic_test/subquery_correlated, line 267 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26284#-LDqt7P54yp0zjg5j0RP:-LDqt7P54yp0zjg5j0RQ:b-rqlaa1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8d3a1783b44a4dccbec3c12179adbb075733014/pkg/sql/logictest/testdata/logic_test/subquery_correlated#L267)):*
> ```
> 4  TX
> 
> # MaxRows prevents decorrelation.
> ```

Max1Row?

---

*[pkg/sql/opt/norm/check_expr.go, line 36 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26284#-LDqtsJ_CJUkyQSZRAmJ:-LDqtsJ_CJUkyQSZRAmK:b-ola1e5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f4bf509e1acf3d0fb24b4c20fb8eb2f83128df0/pkg/sql/opt/norm/check_expr.go#L36)):*
> ```Go
> 		}
> 		if relational.OuterCols.Intersects(relational.OutputCols) {
> 			panic(fmt.Sprintf("outer cols %s intersect output cols %s",
> ```

Looks like we are hitting this in some tests

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26284#-:-LDqtest3-Cze3b7wCVd:b-kerl87)*

**Comment by rytaft** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/norm/decorrelate.go, line 481 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26284#-LDsGOnNCZR43Gg6AJW4:-LDsGOnNCZR43Gg6AJW5:b-g8vquo) ([raw file](https://github.com/cockroachdb/cockroach/blob/64af06a31c7ad957e61ef2fd18e2bbcee6a48e92/pkg/sql/opt/norm/decorrelate.go#L481)):*
> ```Go
> // into the GroupBy, and null values produced by the join will flow into the
> // EXISTS_AGG. It's defined to ignore those nulls so that its result will be
> // unaffected.
> ```

Update this comment to remove reference to EXISTS_AGG and explain the new functionality

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26284#-:-LDs_Pp130kqUzgeT0FM:bnfp4nl)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/logictest/testdata/logic_test/subquery_correlated, line 4 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26284#-LDqsBCACZSk84f7GpWv:-LDtUzgX8VbtKaTCEn6Y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8d3a1783b44a4dccbec3c12179adbb075733014/pkg/sql/logictest/testdata/logic_test/subquery_correlated#L4)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] a comment with a high-level explanation of the tables would help (given that the table and column names are not very hepful)
</blockquote></details>

Done.

---

*[pkg/sql/logictest/testdata/logic_test/subquery_correlated, line 267 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26284#-LDqt7P54yp0zjg5j0RP:-LDtV3XD730C3AZ29ihe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8d3a1783b44a4dccbec3c12179adbb075733014/pkg/sql/logictest/testdata/logic_test/subquery_correlated#L267)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Max1Row?
</blockquote></details>

Done.

---

*[pkg/sql/opt/norm/check_expr.go, line 36 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26284#-LDqtsJ_CJUkyQSZRAmJ:-LDtV4rm1ET6aq2tGqtO:bi5w1vl) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f4bf509e1acf3d0fb24b4c20fb8eb2f83128df0/pkg/sql/opt/norm/check_expr.go#L36)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Looks like we are hitting this in some tests
</blockquote></details>

Yeah, this should be fixed by Rebecca's PR that she put out today (it's due to unwrapped outer cols that are projected).

---

*[pkg/sql/opt/norm/decorrelate.go, line 481 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26284#-LDsGOnNCZR43Gg6AJW4:-LDtXRZS7CXHFi3HORKy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64af06a31c7ad957e61ef2fd18e2bbcee6a48e92/pkg/sql/opt/norm/decorrelate.go#L481)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Update this comment to remove reference to EXISTS_AGG and explain the new functionality
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26284)*

**Pull request merged**
