### PR TITLE
opt: Add correlated subquery Hibernate tests

### PR DESCRIPTION
**Pull request by andy-kimball**
Add several exemplar correlated subquery tests from the Hibernate
test suite, in order to ensure that we monitor their query plans going
forward. While several of the queries cannot be fully decorrelated,
upcoming enhancements will take care of that.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
LGTM

What's the problem with allowing CREATE to overwrite the previous table? Note that some of the existing tests are relying on that so they'll need updating.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27236#-:-LGyjtzrBz0GFOCzHKxQ:bodnxlv)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27236#-:-LGzUMGe1MHrPC0H0tjz:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by andy-kimball — COMMENTED** [review]
I think there are a couple problems with allowing overwrite:

1. It makes the behavior of our test version of CREATE TABLE different from how the real statement works, which is surprising.
2. It masks bugs, since it's easy to reuse a table name without realizing it, and then get confused about which is which. I know when I'm looking over a test file I don't expect the schema of simple tables to change mid-file. I think it's best practice not to do that, and the new error will ensure that we don't do it by accident. And if we have good reason to do it (like with these hibernate test cases), we still have a way to do it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27236#-:-LH3kcKGAlB1sZlHzwMs:b-utdu3s)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27236#-:-LH3m6-32HvCLDXji5Jb:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Pull request merged**
