### PR TITLE
 sql: exponentially grow Datum alloc chunks

### PR DESCRIPTION
**Pull request by nvb**
`DatumAlloc` used to allocate fixed chunks of 16 `Datums` at a time. This
was an improvement over allocating a single `Datum` at a time, but meant
that `Datum` decoding still required an allocation count that grew
linearly with respect to the number of rows in a scan.

This commit changes `DatumAlloc` so that it grows the chunk allocation
size exponentially as more `Datums` are needed. This means that `Datum`
decoding now only requires an allocation count that grows logarithmically
with respect to the number of rows in a scan. It uses a maximum allocation
size so we avoid allocating slices that are too big.

```
name                                     old time/op    new time/op    delta
Scan/Cockroach/count=100000/limit=0-16      156ms ± 4%     156ms ± 3%     ~     (p=1.000 n=23+23)

name                                     old alloc/op   new alloc/op   delta
Scan/Cockroach/count=100000/limit=0-16     48.1MB ± 1%    47.5MB ± 0%     ~     (p=0.433 n=25+24)

name                                     old allocs/op  new allocs/op  delta
Scan/Cockroach/count=100000/limit=0-16       258k ±17%      208k ± 0%  -19.33%  (p=0.000 n=25+24)
```

### CODE REVIEW

**Comment by petermattis** [comment]
Are any other benchmarks affected? (No need to run them all, but perhaps sample a few). The reduction in allocations is nice, but it would be nicer if there is a performance improvement. Also, https://github.com/cockroachdb/cockroach/issues/6248 might be more fruitful.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/sqlbase/table.go, line 956 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18912#-KvDqRNlq5nkvX3QTmnB:-KvDqRNlq5nkvX3QTmnC:b958840) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7cb72e1ad9ab0a637a1878ac0d951372368e7d/pkg/sql/sqlbase/table.go#L956)):*
> ```Go
> 	if l == 0 {
> 		l = a.allocLen(cap(*buf))
> 		*buf = make([]parser.DInt, l, l)
> ```

The 3rd parameter isn't necessary here and below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18912#-:-KvDqYR0nXLOW02VKZAE:b-1m2scy)*

**Comment by knz** [comment]
@nvanbenschoten mind sharing the rationale to close this? (is there any lesson to learn?)

**Comment by nvanbenschoten** [comment]
Mainly because I thought this was https://github.com/cockroachdb/cockroach/pull/19050 without looking too closely. I'm going to re-open and try this out again at some point though because it seems like a pretty clear (if minor) win.

**Comment by petermattis** [comment]
@nvanbenschoten Are you planning to do anything about this?

**Comment by nvanbenschoten** [comment]
No, closing.

**Pull request closed without merging**
