### PR TITLE
roachtest/large-schema-benchmark: add support for invoking console REST APIs

### PR DESCRIPTION
**Pull request by fqazi**
This patch adds support for invoking the console REST APIs as a part of the tpcc/large-schema-benchmark variant. To add this functionality this PR does the following

1. Extend multidbtpcc to support authenticating and invoking arbitrary end points from a file, and add logic to gather histogram information for these invocations.
2. Update the large-schema-benchmark roachtest to use the new options to invoke the REST API.

### CODE REVIEW

**Review by spilchen — COMMENTED** [review]
Looks good. I just had a few comments/questions.

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127429#-:-O2BARF85ZrrJ8ahAh5p:b-itu0yl)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @fqazi, and @renatolabs)

___
*[`pkg/workload/tpcc/tpcc_multi_db.go` line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127429#-O2B8pTv9y1uOahIkKWU:-O2B8pTv9y1uOahIkKWV:bojnvhc) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf8320bb514710a1f07728b95606ded390acbc7d/pkg/workload/tpcc/tpcc_multi_db.go#L78)):*
> ```Go
> 		g.tpcc.workloadName = "tpccmultidb"
> 		g.flags.Meta["txn-preamble-file"] = workload.FlagMeta{RuntimeOnly: true}
> 		g.flags.Meta["admin-urls"] = workload.FlagMeta{RuntimeOnly: true}
> ```

This new option should be used with `--console-api-file`. Do we have any way to ensure they are both set or both not set?
___
*[`pkg/workload/tpcc/tpcc_multi_db.go` line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127429#-O2B0d3Z6nEydnzQBzc4:-O2B0d3Z6nEydnzQBzc5:b-c0xlie) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf8320bb514710a1f07728b95606ded390acbc7d/pkg/workload/tpcc/tpcc_multi_db.go#L120)):*
> ```Go
> 		values := url.Values{
> 			"username": {"roachadmin"},
> 			"password": {"roacher"},
> ```

There is a connection between the user/password used here and the ones used to create the user in `large_schema_benchmark.go`. At a minimum, we should add a comment to link these two places. But I wonder if we add options for this and have large_schema_benchmark.go pass the credentials down.
___
*[`pkg/workload/tpcc/tpcc_multi_db.go` line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127429#-O2B4ANGCaYGWNnpIVH4:-O2B4ANGCaYGWNnpIVH5:b-afozis) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf8320bb514710a1f07728b95606ded390acbc7d/pkg/workload/tpcc/tpcc_multi_db.go#L226)):*
> ```Go
> 	}
> 	// Record the time that the invocation took.
> 	t.consoleAPITime.Record(timeutil.Since(startTime))
> ```

The time may include retry attempts if there is an API error. Should we track the number of API retries we do too? Otherwise, it may inflate the numbers without having much insight. Also, we will capture the API time if all of the APIs complete. If one of them fails, then no time is recorded. I am wondering if we should record each time we call the API and have a record of the time spent calling APIs that failed?
___
*[`pkg/workload/tpcc/tpcc_multi_db.go` line 263 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127429#-O2B8PA16qeRDVWUl3g7:-O2B8PA16qeRDVWUl3g8:b-hi7wql) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf8320bb514710a1f07728b95606ded390acbc7d/pkg/workload/tpcc/tpcc_multi_db.go#L263)):*
> ```Go
> 		return workload.QueryLoad{}, err
> 	}
> 	if t.consoleAPITime == nil {
> ```

Should this be checking if we are capturing console API times?



_Suggestion:_
```Go
	if len(t.adminUrls) > 0 {
```

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127429)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @renatolabs, and @spilchen)

___
*[`pkg/workload/tpcc/tpcc_multi_db.go` line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127429#-O2B8pTv9y1uOahIkKWU:-O2UelCq1vHTqy9DptSs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf8320bb514710a1f07728b95606ded390acbc7d/pkg/workload/tpcc/tpcc_multi_db.go#L78)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

This new option should be used with `--console-api-file`. Do we have any way to ensure they are both set or both not set?
</blockquote></details>

Done.
___
*[`pkg/workload/tpcc/tpcc_multi_db.go` line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127429#-O2B0d3Z6nEydnzQBzc4:-O2Uem1y0EGy0K6Mn7ix:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf8320bb514710a1f07728b95606ded390acbc7d/pkg/workload/tpcc/tpcc_multi_db.go#L120)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

There is a connection between the user/password used here and the ones used to create the user in `large_schema_benchmark.go`. At a minimum, we should add a comment to link these two places. But I wonder if we add options for this and have large_schema_benchmark.go pass the credentials down.
</blockquote></details>

Done.
___
*[`pkg/workload/tpcc/tpcc_multi_db.go` line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127429#-O2B4ANGCaYGWNnpIVH4:-O2UemXN0Vq_k0O-A4nr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf8320bb514710a1f07728b95606ded390acbc7d/pkg/workload/tpcc/tpcc_multi_db.go#L226)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

The time may include retry attempts if there is an API error. Should we track the number of API retries we do too? Otherwise, it may inflate the numbers without having much insight. Also, we will capture the API time if all of the APIs complete. If one of them fails, then no time is recorded. I am wondering if we should record each time we call the API and have a record of the time spent calling APIs that failed?
</blockquote></details>

Done.
___
*[`pkg/workload/tpcc/tpcc_multi_db.go` line 263 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127429#-O2B8PA16qeRDVWUl3g7:-O2UeoQ93ldsvEBs_uj5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf8320bb514710a1f07728b95606ded390acbc7d/pkg/workload/tpcc/tpcc_multi_db.go#L263)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Should this be checking if we are capturing console API times?
</blockquote></details>

Done.

**Review by spilchen — APPROVED** [review]
:lgtm: Just had a minor nit for one of your error messages.

> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127429#-:-O2WKIBgBrf4xcUkU1dE:b-yj3jq)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @fqazi, and @renatolabs)

___
*[`pkg/workload/tpcc/tpcc_multi_db.go` line 350 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127429#-O2WIfHABe_7_ifiO516:-O2WIfHABe_7_ifiO517:b-3wdinl) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dcf8f8bcc3e34db1fdf9f7841d68e23b101952f/pkg/workload/tpcc/tpcc_multi_db.go#L350)):*
> ```Go
> 		if (len(t.adminUrlStr) == 0) !=
> 			(len(t.consoleAPICommandFile) == 0) {
> 			err = errors.Newf("console-api-command must be specified with admin-rls must be speicifed together")
> ```

nit: small correction in the parm names



_Suggestion:_
```Go
console-api-file must be specified with admin-urls must be specified together
```

**Pull request merged**
