### PR TITLE
storage: avoid "lost read" after lease change

### PR DESCRIPTION
**Pull request by tbg**
When acquiring a new lease, we were updating the in-memory state too early. In
particular, this could lead to serving writes before having updated the
timestamp cache low water mark from the previous lease. The consequence was
a loss of consistency.

This fix is for 1.0.3 and avoids the refactor (which I attempted, but then
realized was not easily contained). Similarly, reproducing #16610 has so far
eluded me. Both should be addressed for 1.1.

See #16610.

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica_proposal.go, line 680 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16722#-KndgJTCacKL6B2sh1-D:-KndgJTCacKL6B2sh1-E:bbhg8x8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7ce8795a34ba5efa9ae7e32b72c85a1edfa84e7/pkg/storage/replica_proposal.go#L680)):*
> ```Go
> 			}
> 		}
> 		r.store.tsCacheMu.Unlock()
> ```

This code is now duplicated in `leasePostApply`. Did you intend to remove the code there? If not, why are both versions necessary?

---

*[pkg/storage/store.go, line 1843 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16722#-KndfiStWCwDxg03hH9k:-KndfiStWCwDxg03hH9l:b-6gqfk8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6394546363d6341537e77c89c2da0f43694bb3ac/pkg/storage/store.go#L1843)):*
> ```Go
> 
> 	r.mu.Lock()
> 	rightRng.mu.Lock()
> ```

I thought lock ordering requirements mandated that we lock the left range before the right range. Seems like this is now reversed and could lead to deadlock. Was the change here motivated by something? If not, I'd revert and add a comment about the necessary lock order acquisition.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16722)*

**Comment by tschottdorf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/replica_proposal.go, line 680 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16722#-KndgJTCacKL6B2sh1-D:-Kne2KMrNG4IsEbIZF5w:bzalsgp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7ce8795a34ba5efa9ae7e32b72c85a1edfa84e7/pkg/storage/replica_proposal.go#L680)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This code is now duplicated in `leasePostApply`. Did you intend to remove the code there? If not, why are both versions necessary?
</blockquote></details>

See the commit message - this is for cherry-picking into 1.0.3. Tried to get a proper fix right away, but there are some threads to pull.

---

*[pkg/storage/store.go, line 1843 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16722#-KndfiStWCwDxg03hH9k:-Kne2aNyTug24R9UD0Il:bsc8lmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6394546363d6341537e77c89c2da0f43694bb3ac/pkg/storage/store.go#L1843)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I thought lock ordering requirements mandated that we lock the left range before the right range. Seems like this is now reversed and could lead to deadlock. Was the change here motivated by something? If not, I'd revert and add a comment about the necessary lock order acquisition.
</blockquote></details>

No, I'll back this out. Didn't find anything on the locking order here, does your memory serve?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16722)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica_proposal.go, line 680 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16722#-KndgJTCacKL6B2sh1-D:-KneEAWJTKeRidlKzr5s:b-a6mfuc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7ce8795a34ba5efa9ae7e32b72c85a1edfa84e7/pkg/storage/replica_proposal.go#L680)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

See the commit message - this is for cherry-picking into 1.0.3. Tried to get a proper fix right away, but there are some threads to pull.
</blockquote></details>

Yeah, I saw the commit message, but I'm not clear on why you need to do this work in both places. Removing this code from `leasePostApply` doesn't work? At the very least, add a comment noting that this work is duplicated and that doing so is a short term fix.

Also, is this even the right thing to do? The similar code in `leasePostApply` is protected by `leaseChangingHands && iAmTheLeaseHolder`. The code here is always setting the low water mark for the timestamp cache which seems wrong when the lease isn't changing hands.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16722)*

**Comment by tschottdorf** [comment]
@petermattis you're right, this is too sloppy. Back to the drawing board.

**Pull request closed without merging**
