### PR TITLE
core: check version compatibility on RPC handshake

### LINKED ISSUE #18058: rpc: fail at handshake time when node versions are incompatible
see https://github.com/cockroachdb/cockroach/issues/17659.

We can do this in our `rpc` connection cache: before a connection becomes healthy, we require that both peers run with compatible binaries, and perhaps even compare their cluster IDs.

Should be a decent starter project. cc @cuongdo.

### PR DESCRIPTION
**Pull request by solongordon**
The RPC heartbeat now checks for version compatibility between the two
nodes. This prevents a node from establishing a gRPC connection if its
binary version is lower than the cluster version on the other end.

Fixes #18058.

Release note (bug fix): Prevent RPC connections between nodes with
incompatible versions.

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 33 of 33 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/rpc/heartbeat.go, line 65 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20587#-L01mP6SXvFO_8ihPKN1:-L01mP6SXvFO_8ihPKN2:bey83he) ([raw file](https://github.com/cockroachdb/cockroach/blob/d48b748df98405afce38b8515113dbcad7e6b25d/pkg/rpc/heartbeat.go#L65)):*
> ```Go
> 
> func checkVersion(
> 	clusterVersion *cluster.ExposedClusterVersion, serverVersion roachpb.Version,
> ```

s/server/peer/

---

*[pkg/rpc/heartbeat_test.go, line 226 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20587#-L01rmZHDPLT5e6OUqya:-L01rmZHDPLT5e6OUqyb:b-pjs82c) ([raw file](https://github.com/cockroachdb/cockroach/blob/d48b748df98405afce38b8515113dbcad7e6b25d/pkg/rpc/heartbeat_test.go#L226)):*
> ```Go
> }
> 
> func TestVersionCheck(t *testing.T) {
> ```

What's the difference between this test and the similar one in context_test.go? (comments would be nice)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20587#-:-L01rtA2h1JNUqnmapbX:bnfp4nl)*

**Comment by a-robinson** [comment]
:lgtm:

---

Reviewed 33 of 33 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/rpc/context.go, line 585 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20587#-L05N5azMMGLQAWhWvI2:-L05N5azMMGLQAWhWvI3:b-nkdjaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d48b748df98405afce38b8515113dbcad7e6b25d/pkg/rpc/context.go#L585)):*
> ```Go
> 
> 		if err == nil {
> 			err = checkVersion(ctx.version, response.ServerVersion)
> ```

The wording of the "but peer has version" error message is ambiguous depending on where it's returned from. If it's evaluated on the server and returned by `heartbeatClient.Ping` it means that the client is too old. If it's evaluated here it means the server is too old. In both cases we stick the error into the same place without distinguishing which case it was.

Could you disambiguate the situation in some way so that we don't get stuck wondering which server was at the bad version in a debugging scenario where we only have the logs to go by?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20587#-:-L05O14sT58vXk1hEKys:bnfp4nl)*

**Comment by solongordon** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/rpc/context.go, line 585 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20587#-L05N5azMMGLQAWhWvI2:-L0ANmwMKXhixfF7vHBU:bqr5tzw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d48b748df98405afce38b8515113dbcad7e6b25d/pkg/rpc/context.go#L585)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

The wording of the "but peer has version" error message is ambiguous depending on where it's returned from. If it's evaluated on the server and returned by `heartbeatClient.Ping` it means that the client is too old. If it's evaluated here it means the server is too old. In both cases we stick the error into the same place without distinguishing which case it was.

Could you disambiguate the situation in some way so that we don't get stuck wondering which server was at the bad version in a debugging scenario where we only have the logs to go by?
</blockquote></details>

Good point. I wrapped the error to indicate if it's on the request or response side. Hopefully that's sufficient.

---

*[pkg/rpc/heartbeat.go, line 65 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20587#-L01mP6SXvFO_8ihPKN1:-L0AKnP4btAcytUQnTSu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d48b748df98405afce38b8515113dbcad7e6b25d/pkg/rpc/heartbeat.go#L65)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

s/server/peer/
</blockquote></details>

Done.

---

*[pkg/rpc/heartbeat_test.go, line 226 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20587#-L01rmZHDPLT5e6OUqya:-L0GwJ3q7NtiUfwOC47J:b-wbpow0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d48b748df98405afce38b8515113dbcad7e6b25d/pkg/rpc/heartbeat_test.go#L226)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

What's the difference between this test and the similar one in context_test.go? (comments would be nice)
</blockquote></details>

Yup, added comments. They test similar logic but at different levels. Basically this one tests the handler side of the heartbeat and the other tests the request side. I would have only added this test except that I needed to verify that the check was bidirectional. Hopefully the new comments make this clearer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20587)*

**Comment by a-robinson** [comment]
👍

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20587#-:-L0H1GELOa4hc5MNs8Ro:b44tpx)*

**Comment by solongordon** [comment]
Update to fix acceptance tests: I added a `rpc.GRPCDialRaw` function for when we want a gRPC connection without running validation. This was useful for the failing test which needed to create a client connection to an older binary. I have a feeling it will come in handy in other situations too.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20587#-:-L0H0wUa_56Qvs9cbSka:b-si1t0k)*

**Pull request merged**
