### PR TITLE
Ensure that failures in sql -e are reported to the user on stderr.

### LINKED ISSUE #4285: Error details not printed with sql -e
Used to work, broken with #4212. Not detected by test suite since we don't have expected failures yet.

### PR DESCRIPTION
**Pull request by knz**
Fixes #4285.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4286)

### CODE REVIEW

**Comment by tamird** [comment]
Can you avoid commit messages like "fixes #xxx"? Your commit message should at a minimum include a description of the work being done.

**Comment by tamird** [comment]
Can you add a test?

**Comment by knz** [comment]
No I cannot add a test, because the test framework does not support expected failures in the sql client.

**Comment by tamird** [comment]
I see.

**Pull request merged**
