### PR TITLE
licenses: updating licenses for 22.1

### PR DESCRIPTION
**Pull request by celiala**
This PR updates license files for the 22.1 release, which will be backported to release-22.1.0 and release.22.1.x.

This PR updates the license files in the `license/` directory to the following:

- For BSD licenses: the name of the copyright holder appears in the text of the license itself, so we've copied their BSD license into the `license/` folder
- For all other licenses: we are using the generic license text
  - Note that we currently have a few separate files for OFL and MIT, which were cargo-culted from the BSD pattern. For 22.2 onwards, we will determine if these should be merged into a single generic version of the license (separate commit, if applicable). For 22.1, these will be kept as-is.

Notes:
- The update to the BSL license, which will not be backported to 22.1, will happen in a separate commit.
- Older BSD licenses:
  - BSD-biogo.txt has been renamed BSD3-biogo.store.llrb.txt, as the https://github.com/google/go-licenses tool found an exact equivalent.
  - All other pre-existing BSD licenses remain as-is for now. We can clean up in 22.2 if not needed (separate commit, if applicable).

Partial work for https://github.com/cockroachdb/cockroach/issues/80555

Release note: None

### CODE REVIEW

**Review by jlinder — COMMENTED** [review]
Looks great overall. Though it looks like the `licenses/BSD-golang.txt` was renamed to `licenses/BSD3-aws.txt` instead of `BSD3-golang.org.x.txt`.

**Comment by celiala** [comment]
This - this is RFAL!

> Though it looks like the licenses/BSD-golang.txt was renamed to licenses/BSD3-aws.txt instead of BSD3-golang.org.x.txt.

I tried forcing this rename a few different ways (git mv, 2 separate commits then a squash), but git was still mapping BSD-golang.txt to BSD3-aws.txt.

Keeping `BSD-golang.txt` as-is, as this continues to be correct, and the most clear.

**Review by jlinder — APPROVED** [review]
LGTM

**Comment by celiala** [comment]
TFTR!

bors r=jlinder

**Comment by celiala** [comment]
TFTR!

bors r=jlinder

**Pull request merged**
