### PR TITLE
sql/catalog: split desc.Collection name resolution into mutable and immutable methods, adopt database name resolution methods

### PR DESCRIPTION
**Pull request by thoszhang**
See individual commits for details.

### CODE REVIEW

**Comment by lucy-zhang** [comment]
This isn't quite ready yet. 293d585 has a nil interface value bug that I need to track down.

**Comment by lucy-zhang** [comment]
Alright, this should be more correct now. I'm still not sure I understand what's going on with the nil values. We compare a descriptor to nil here:

https://github.com/cockroachdb/cockroach/blob/cd62a02833eeb02d14944668d09ee54806927a2b/pkg/sql/resolver.go#L216

It's not clear to me what causes an interface-wrapped value to be returned from `GetObjectDesc`.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 5 of 5 files at r2, 17 of 17 files at r3, 7 of 7 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58226#-:-MPG0Bfk9zGvs_Z246fI:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/sql/catalog/accessor.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58226#-MPG-G_lErpy2ocfGVUk:-MPG-G_m-lSTm2fG4xjV:b14kqtn) ([raw file](https://github.com/cockroachdb/cockroach/blob/fedd8fa21b96d9d49dc3d571447d4e1dd0d15e15/pkg/sql/catalog/accessor.go#L30)):*
> ```Go
> 	// an error is returned; otherwise a nil reference is returned.
> 	//
> 	// Warning: This method uses no "logical" schema information and only exists
> ```

What does logical mean in this context?
___
*[pkg/sql/catalog/descs/collection.go, line 752 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/58226#-MPG065Q3TyrmFcNef_d:-MPG065Q3TyrmFcNef_e:b-7iimq0) ([raw file](https://github.com/cockroachdb/cockroach/blob/53220144e10f5b61e6f21e42d4823af7a19c2611/pkg/sql/catalog/descs/collection.go#L752)):*
> ```Go
> 	flags tree.SchemaLookupFlags,
> 	mutable bool,
> ) (bool, catalog.ResolvedSchema, error) {
> ```

I would *love* to kill the `ResolvedSchema` concept.

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58226)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

___
*[pkg/sql/catalog/accessor.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58226#-MPG-G_lErpy2ocfGVUk:-MPGhIId2Hh0RKFBOUP6:bsz6t3m) ([raw file](https://github.com/cockroachdb/cockroach/blob/fedd8fa21b96d9d49dc3d571447d4e1dd0d15e15/pkg/sql/catalog/accessor.go#L30)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

What does logical mean in this context?
</blockquote></details>

I guess it doesn't mean anything at the interface level. I rewrote this to be a bit more explicit.
___
*[pkg/sql/catalog/descs/collection.go, line 752 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/58226#-MPG065Q3TyrmFcNef_d:-MPGeT2LEhl5pX7RwbiM:b-m3ltop) ([raw file](https://github.com/cockroachdb/cockroach/blob/53220144e10f5b61e6f21e42d4823af7a19c2611/pkg/sql/catalog/descs/collection.go#L752)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I would *love* to kill the `ResolvedSchema` concept. 
</blockquote></details>

Me too. I wrote some thoughts in https://github.com/cockroachdb/cockroach/issues/57538.

**Comment by lucy-zhang** [comment]
TFTR!

bors r+

**Pull request merged**
