### PR TITLE
scheduledlogging: various fixes to index stat collection

### LINKED ISSUE #87771: schedulinglogging: some cluster setting values cause CPU usage to increase to 100%
**Describe the problem**

If I set the following cluster settings:

```
set cluster setting "sql.telemetry.capture_index_usage_stats.interval" = '0s';
set cluster setting "sql.telemetry.capture_index_usage_stats.check_enabled_interval" = '0s';
set cluster setting "sql.telemetry.capture_index_usage_stats.logging_delay" = '0s';
```

Then the task `"capture-index-usage-stats"` starts to busy-loop with a zero timer.

**Expected behavior**

There should be a minimum delay between iterations to avoid a busy loop.

Jira issue: CRDB-19524

### PR DESCRIPTION
**Pull request by knz**
As I was reviewing #87525, I noticed that the actual test cases were missing.
Then, as I tried to fix that, I discovered a couple of other shortcomings. This PR fixes them.

Fixes #87771.
Informs #87772.

### CODE REVIEW

**Comment by knz** [comment]
Please also indicate if this needs to be backported to 22.1

**Review by xinhaoz — APPROVED** [review]
Additional test cases :lgtm: 

> Reviewed 1 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87773#-:-NBm0j399FvTJ2yQ94v2:bg2lry5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @THardy98)

**Comment by knz** [comment]
So what do you think about backports?

**Comment by knz** [comment]
bors r=xinhaoz

**Comment by THardy98** [comment]
With https://github.com/cockroachdb/cockroach/pull/88999 backported to 22.1, we can probably backport this to 22.1 as well (also, super sorry for not seeing this earlier).

**Pull request merged**
