### PR TITLE
sql: deflake TestSchemaChangeReverseMutations

### LINKED ISSUE #31462: sql: TestSchemaChangeReverseMutations failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/a0b7cd4ebddf5ebc8f8c2119b119e57688f072f9

Parameters:
```
TAGS=
GOFLAGS=-race
```

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stressrace instead of stress and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
make stress TESTS=TestSchemaChangeReverseMutations PKG=github.com/cockroachdb/cockroach/pkg/sql TESTTIMEOUT=5m STRESSFLAGS='-stderr=false -maxtime 20m -timeout 10m'
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=969388&tab=buildLog

```
I181016 12:36:53.454181 108165 sql/lease.go:315  publish (1 leases): desc=[{test 53 16}]
I181016 12:36:53.865056 108165 sql/lease.go:345  [n1,scExec] publish: descID=53 (test) version=18 mtime=2018-10-16 12:36:53.863309659 +0000 UTC
I181016 12:36:53.955236 108165 sql/lease.go:315  publish (1 leases): desc=[{test 53 17}]
I181016 12:36:53.976904 108750 sql/lease.go:877  new lease: 53("test") ver=18:1539693670.672605501,0, refcount=0
I181016 12:36:54.019884 108165 sql/lease.go:315  publish (1 leases): desc=[{test 53 17}]
I181016 12:36:54.098961 108165 sql/backfill.go:132  [n1,scExec] Running backfill for "test", v=18, m=5
I181016 12:36:54.303246 108133 storage/replica_proposal.go:212  [n1,s1,r5/1:/System/ts{d-e}] new range lease repl=(n1,s1):1 seq=3 start=1539693403.397612557,0 epo=1 pro=1539693414.297802820,0 following repl=(n1,s1):1 seq=2 start=1539693403.397612557,0 exp=1539693412.447715340,0 pro=1539693403.447847978,0
I181016 12:36:54.348601 108165 sql/lease.go:345  [n1,scExec] publish: descID=53 (test) version=19 mtime=2018-10-16 12:36:54.346664967 +0000 UTC
I181016 12:36:54.478938 108165 sql/event_log.go:126  [n1,scExec] Event: "finish_schema_change", target: 53, info: {MutationID:5}
I181016 12:36:54.537191 107868 sql/schema_changer_test.go:1767  SucceedsSoon: 1 mutations remaining
I181016 12:36:54.576519 108165 sql/lease.go:315  publish (1 leases): desc=[{test 53 18}]
I181016 12:36:54.583863 108793 sql/lease.go:877  new lease: 53("test") ver=19:1539693663.173692229,0, refcount=0
I181016 12:36:54.629890 108165 sql/lease.go:315  publish (1 leases): desc=[{test 53 18}]
I181016 12:36:54.879956 108165 sql/lease.go:345  [n1,scExec] publish: descID=53 (test) version=20 mtime=2018-10-16 12:36:54.87841889 +0000 UTC
I181016 12:36:54.923463 108165 sql/lease.go:315  publish (1 leases): desc=[{test 53 19}]
I181016 12:36:54.924935 108797 sql/lease.go:877  new lease: 53("test") ver=20:1539693711.125095242,0, refcount=0
I181016 12:36:54.968340 108165 sql/backfill.go:132  [n1,scExec] Running backfill for "test", v=20, m=6
I181016 12:36:55.192760 108165 sql/lease.go:345  [n1,scExec] publish: descID=53 (test) version=21 mtime=2018-10-16 12:36:55.190844125 +0000 UTC
I181016 12:36:55.311468 108165 sql/event_log.go:126  [n1,scExec] Event: "finish_schema_change", target: 53, info: {MutationID:6}
I181016 12:36:55.368868 108948 sql/lease.go:877  new lease: 53("test") ver=21:1539693665.963444366,0, refcount=0
I181016 12:36:55.387733 108165 sql/lease.go:315  publish (1 leases): desc=[{test 53 20}]
I181016 12:36:55.544648 107868 sql/schema_changer_test.go:1767  SucceedsSoon: 1 gc mutations remaining
I181016 12:36:55.609463 108165 sql/lease.go:345  [n1,scExec] publish: descID=53 (test) version=22 mtime=2018-10-16 12:36:55.607695096 +0000 UTC
I181016 12:36:55.744490 108998 sql/lease.go:877  new lease: 53("test") ver=22:1539693732.945594691,0, refcount=0
I181016 12:36:55.753812 108165 sql/lease.go:315  publish (1 leases): desc=[{test 53 21}]
I181016 12:36:55.803934 108165 sql/lease.go:315  publish (1 leases): desc=[{test 53 21}]
I181016 12:36:56.612276 107868 util/stop/stopper.go:537  quiescing; tasks left:
1      [async] transport racer
1      [async] storage.consistencyChecker: processing replica
1      [async] storage.Replica: checking consistency
1      [async] closedts-rangefeed-subscriber
I181016 12:36:56.614533 107868 util/stop/stopper.go:537  quiescing; tasks left:
1      [async] transport racer
1      [async] storage.consistencyChecker: processing replica
1      [async] closedts-rangefeed-subscriber
I181016 12:36:56.615382 107868 util/stop/stopper.go:537  quiescing; tasks left:
1      [async] transport racer
1      [async] closedts-rangefeed-subscriber
I181016 12:36:56.617555 108110 kv/transport_race.go:113  transport race promotion: ran 62 iterations on up to 4084 requests
I181016 12:36:56.620412 107868 util/stop/stopper.go:537  quiescing; tasks left:
1      [async] closedts-rangefeed-subscriber
--- FAIL: TestSchemaChangeReverseMutations (13.48s)
	schema_changer_test.go:1782: pq: batch timestamp 1539693416.550241344,0 must be after GC threshold 1539693416.551361159,0

```

### PR DESCRIPTION
**Pull request by eriktrinh**
Fixes #31462.

Release note: None

### CODE REVIEW

**Review by vivekmenezes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31515)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/schema_changer_test.go, line 1779 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31515#-LOyKpdo3OKuAsrqXs5u:-LOyKpdo3OKuAsrqXs5v:bsaitot) ([raw file](https://github.com/cockroachdb/cockroach/blob/6864c14c5cb9b460da4735789a4f06cfdf6571a4/pkg/sql/schema_changer_test.go#L1779)):*
> ```Go
> 	if _, err := addDefaultZoneConfig(sqlDB, tableDesc.ID); err != nil {
> 		t.Fatal(err)
> 	}
> ```

Any particular reason to need to reset it?

**Review by eriktrinh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31515)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/schema_changer_test.go, line 1779 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31515#-LOyKpdo3OKuAsrqXs5u:-LOyLVLM9QXjNM6B6c7o:b-m19k07) ([raw file](https://github.com/cockroachdb/cockroach/blob/6864c14c5cb9b460da4735789a4f06cfdf6571a4/pkg/sql/schema_changer_test.go#L1779)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Any particular reason to need to reset it?
</blockquote></details>

The error is the same as #31177 and probably happens because the GC TTL is set to 0 so there is a race between the gc running and when the subsequent reads of this test occur. Resetting the GC TTL should prevent that.

**Review by eriktrinh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31515)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/schema_changer_test.go, line 1779 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31515#-LOyKpdo3OKuAsrqXs5u:-LOyb7g5DJ872qjMh2W_:bwvuw92) ([raw file](https://github.com/cockroachdb/cockroach/blob/6864c14c5cb9b460da4735789a4f06cfdf6571a4/pkg/sql/schema_changer_test.go#L1779)):*
<details><summary><i>Previously, eriktrinh (Erik Trinh) wrote…</i></summary><blockquote>

The error is the same as #31177 and probably happens because the GC TTL is set to 0 so there is a race between the gc running and when the subsequent reads of this test occur. Resetting the GC TTL should prevent that.
</blockquote></details>

Restructured as discussed.

**Review by vivekmenezes — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31515)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/schema_changer_test.go, line 1771 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31515#-LOyd4SeDgNY7VCSD2ya:-LOyd4Sf7toSORAh4k7W:b-tt53p4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8be9fa56c9edb2e4132564cde457b33ee4902077/pkg/sql/schema_changer_test.go#L1771)):*
> ```Go
> 
> 	// Wait until all the mutations have been processed.
> 	var rows *gosql.Rows
> ```

Do we need this to be defined?

**Review by eriktrinh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31515)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/schema_changer_test.go, line 1771 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31515#-LOyd4SeDgNY7VCSD2ya:-LOyeB7dBsoaRarjRKem:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8be9fa56c9edb2e4132564cde457b33ee4902077/pkg/sql/schema_changer_test.go#L1771)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Do we need this to be defined?
</blockquote></details>

Done.

**Pull request merged**
