### PR TITLE
cli: deflake TestZipRetries

### LINKED ISSUE #124650: cli: TestZipRetries failed
cli.TestZipRetries [failed](https://tanzanite.cluster.engflow.com/invocations/default/b6e469ac-146e-41cd-aeaf-59619a9f5902?testReportRun=6&testReportShard=8&testReportAttempt=1#targets-Ly9wa2cvY2xpOmNsaV90ZXN0) on master @ [c7f16c96d4db6ef97085f972f094c7e4e7c1518f](https://github.com/cockroachdb/cockroach/commits/c7f16c96d4db6ef97085f972f094c7e4e7c1518f):

```
=== RUN   TestZipRetries
    test_log_scope.go:170: test logs captured to: outputs.zip/logTestZipRetries2072478922
    test_log_scope.go:81: use -show-logs to present logs inline
    test_server_shim.go:157: automatically injected a shared process virtual cluster under test; see comment at top of test_server_shim.go for details.
[test] retrieving SQL data for generate_series(1,15000) as t(x)...
[test] retrieving SQL data for generate_series(1,15000) as t(x): writing output: test/generate_series(1,15000) as t(x).json...
(error encountered after some results were delivered)
[test] retrieving SQL data for generate_series(1,15000) as t(x): last request failed: ERROR: query execution canceled due to statement timeout (SQLSTATE 57014)
[test] retrieving SQL data for generate_series(1,15000) as t(x): creating error output: test/generate_series(1,15000) as t(x).json.err.txt...
[test] retrieving SQL data for generate_series(1,15000) as t(x): done
    zip_test.go:829: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/cli/zip_test.go:829
        	Error:      	Not equal: 
        	            	expected: "test/generate_series(1,15000) as t(x).json\ntest/generate_series(1,15000) as t(x).json.err.txt\ntest/generate_series(1,15000) as t(x).1.json\ntest/generate_series(1,15000) as t(x).1.json.err.txt\ntest/generate_series(1,15000) as t(x).2.json\ntest/generate_series(1,15000) as t(x).2.json.err.txt\ntest/generate_series(1,15000) as t(x).3.json\ntest/generate_series(1,15000) as t(x).3.json.err.txt\ntest/generate_series(1,15000) as t(x).4.json\ntest/generate_series(1,15000) as t(x).4.json.err.txt\n"
        	            	actual  : "test/generate_series(1,15000) as t(x).json\ntest/generate_series(1,15000) as t(x).json.err.txt\n"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -2,10 +2,2 @@
        	            	 test/generate_series(1,15000) as t(x).json.err.txt
        	            	-test/generate_series(1,15000) as t(x).1.json
        	            	-test/generate_series(1,15000) as t(x).1.json.err.txt
        	            	-test/generate_series(1,15000) as t(x).2.json
        	            	-test/generate_series(1,15000) as t(x).2.json.err.txt
        	            	-test/generate_series(1,15000) as t(x).3.json
        	            	-test/generate_series(1,15000) as t(x).3.json.err.txt
        	            	-test/generate_series(1,15000) as t(x).4.json
        	            	-test/generate_series(1,15000) as t(x).4.json.err.txt
        	            	 
        	Test:       	TestZipRetries
    zip_test.go:830: -- test log scope end --
test logs left over in: outputs.zip/logTestZipRetries2072478922
--- FAIL: TestZipRetries (4.20s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=6</code>
 - <code>shard=8</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/obs-prs @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestZipRetries.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-38986

### PR DESCRIPTION
**Pull request by rafiss**
This avoids a race when setting a cluster setting, and instead sets the parameter directly in the connection string.

fixes https://github.com/cockroachdb/cockroach/issues/124650
Release note: None

### CODE REVIEW

**Review by dhartunian — APPROVED** [review]

**Comment by rafiss** [comment]
tftr!

bors r+

**Comment by dhartunian** [comment]
I'm a little confused: the cluster setting is synchronous in this case?

**Comment by rafiss** [comment]
I believe the race is under multitenant configs, since propagating the setting to tenants is not synchronous.

**Comment by dhartunian** [comment]
> I believe the race is under multitenant configs, since propagating the setting to tenants is not synchronous.

😑 I keep forgetting that's a thing. thanks!

**Pull request merged**
