### PR TITLE
storage/cloud: replace WriteFile(Reader) with Writer

### PR DESCRIPTION
**Pull request by dt**
This changes the ExternalStorage API's writing method from WriteFile which takes an io.Reader
and writes its content to the requested destination or returns an error encountered while doing
so to instead have Writer() which returns an io.Writer pointing to the destination that can be
written to later and then closed to finish the upload (or CloseWithError'ed to cancel it).

All existing callers use the shim and are unaffected, but can later choose to change to a
push-based model and use the Writer directly. This is left to a follow-up change.

(note: first commit is just adding a shim for existing callers and switching them)

Release note: none.

### CODE REVIEW

**Comment by dt** [comment]
This will need a rebase over #65033 but I wanted to start letting CI chew on it.

**Review by miretskiy — CHANGES_REQUESTED** [review]
> Reviewed 15 of 17 files at r1, 10 of 15 files at r2, 7 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65057)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

___
*[pkg/storage/cloud/cloud_io.go, line 256 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65057#-M_W-64x3YgvtuD30yiv:-M_W-64x3YgvtuD30yiw:bhlzw7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/b30ec19e9d6e4ded066cd3b1d06e55fc952c421c/pkg/storage/cloud/cloud_io.go#L256)):*
> ```Go
> }
> 
> func BackgroundPipe(ctx context.Context, fn func(ctx context.Context, pr io.Reader) error) WriteCloserWithError {
> ```

nit: comment needed for exported function (and all aexported methods).
___
*[pkg/storage/cloud/cloud_io.go, line 300 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65057#-M_WxsCK-fSvo9vYCfee:-M_WxsCK-fSvo9vYCfef:b-aw9fd3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f6625d67079647bb2f5f77705713f31c3ec3808/pkg/storage/cloud/cloud_io.go#L300)):*
> ```Go
> // WriteFile is a helper for writing the content of a Reader to the given path
> // of an ExternalStorage.
> func WriteFile(ctx context.Context, basename string, src io.Reader, dest ExternalStorage) error {
> ```

should the signature be changed (ctx, src, dest, basename) to be more of a "src -> dest" pattern?
___
*[pkg/storage/cloud/cloud_io.go, line 307 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65057#-M_WyWIcAL_wWqQ5wmg-:-M_WyWIcAL_wWqQ5wmg0:bjxxb0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f6625d67079647bb2f5f77705713f31c3ec3808/pkg/storage/cloud/cloud_io.go#L307)):*
> ```Go
> 	if _, err := io.Copy(w, src); err != nil {
> 		_ = w.CloseWithError(err)
> 		return err
> ```

you could keep both errors if you so choose: `return errors.CombineErrors(err, w.CloseWithError(err))`
___
*[pkg/storage/cloud/amazon/s3_storage.go, line 293 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65057#-M_W1EZQ-FYIQqvfSmcp:-M_W1EZQ-FYIQqvfSmcq:b-fjvdbk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b30ec19e9d6e4ded066cd3b1d06e55fc952c421c/pkg/storage/cloud/amazon/s3_storage.go#L293)):*
> ```Go
> 		return nil, err
> 	}
> 	uploader := s3manager.NewUploader(sess)
> ```

not saying that this is bad... but we're changing implementation to use upload vs put object.
We should probably add this in the pr descriptor.
s3 manager seems to have settings around concurrency (default upload == 5).  What does that mean for us
(if anything)?  Should that be configurable?  Perhaps a TODO is in order to evaluate this.
___
*[pkg/storage/cloud/azure/azure_storage.go, line 135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65057#-M_W2FDz0qgvdBpKnVXh:-M_W2FDz0qgvdBpKnVXi:bnd5gsi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b30ec19e9d6e4ded066cd3b1d06e55fc952c421c/pkg/storage/cloud/azure/azure_storage.go#L135)):*
> ```Go
> 		_, err := azblob.UploadStreamToBlockBlob(
> 			ctx, r, blob, azblob.UploadStreamToBlockBlobOptions{
> 				BufferSize: 4 << 20,
> ```

This seems rather arbitrary?  
I'm also curious/worried about the implication of this call, particularly in the face of slowness/unavailabilty of azure.  You could imagine having bunch of these uploads  starting ,all buffering 4 MB? 
___
*[pkg/storage/cloud/gcp/gcs_storage.go, line 162 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65057#-M_W4s9VBMt0GoljFPBM:-M_W4s9VBMt0GoljFPBN:b-rru6mp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5bf73870b8b95a09767b71fd7a604ebcb4acb0e/pkg/storage/cloud/gcp/gcs_storage.go#L162)):*
> ```Go
> func (g *gcsStorage) WriteFile(ctx context.Context, basename string, content io.ReadSeeker) error {
> 	const maxAttempts = 3
> 	err := retry.WithMaxAttempts(ctx, base.DefaultRetryOptions(), maxAttempts, func() error {
> ```

Do we know if gcs retries? Is it safe to drop this?
___
*[pkg/storage/cloud/httpsink/http_storage.go, line 179 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65057#-M_X-HQJBE9PyGrp_K2I:-M_X-HQJBE9PyGrp_K2J:bdrjtn2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5bf73870b8b95a09767b71fd7a604ebcb4acb0e/pkg/storage/cloud/httpsink/http_storage.go#L179)):*
> ```Go
> 
> func (h *httpStorage) WriteFile(ctx context.Context, basename string, content io.ReadSeeker) error {
> 	return contextutil.RunWithTimeout(ctx, fmt.Sprintf("PUT %s", basename),
> ```

I assume we're dropping this because, presumably the caller could set deadlines themselves...
Do we know if anything is effected by this?  Is this a safe change to make?
___
*[pkg/storage/cloud/userfile/file_table_storage.go, line 269 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65057#-M_X-RgGCFmTD5UY4_kV:-M_X-RgGCFmTD5UY4_kW:btu4gg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5bf73870b8b95a09767b71fd7a604ebcb4acb0e/pkg/storage/cloud/userfile/file_table_storage.go#L269)):*
> ```Go
> 	// retry we are not able to seek to the start of `content` and try again,
> 	// resulting in bytes being missed across txn retry attempts.
> 	// See chunkWriter.WriteFile for more information about writing semantics.
> ```

Can you explain why it's safe to remove this?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65057)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @miretskiy)

___
*[pkg/storage/cloud/cloud_io.go, line 256 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65057#-M_W-64x3YgvtuD30yiv:-M_XIXG92jvRUwp2vGaI:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b30ec19e9d6e4ded066cd3b1d06e55fc952c421c/pkg/storage/cloud/cloud_io.go#L256)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

nit: comment needed for exported function (and all aexported methods).
</blockquote></details>

Done. 
___
*[pkg/storage/cloud/cloud_io.go, line 300 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65057#-M_WxsCK-fSvo9vYCfee:-M_XI9UK3U1-ntJszHU7:b-ewn7wj) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f6625d67079647bb2f5f77705713f31c3ec3808/pkg/storage/cloud/cloud_io.go#L300)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

should the signature be changed (ctx, src, dest, basename) to be more of a "src -> dest" pattern?
</blockquote></details>

Heh, I thought of this after I'd already changed all the calls, but decided I didn't quite care enough about a temporary shim to go change them all again.
___
*[pkg/storage/cloud/cloud_io.go, line 307 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65057#-M_WyWIcAL_wWqQ5wmg-:-M_XYIyzCTZqpAB1epkn:b-n0qlb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f6625d67079647bb2f5f77705713f31c3ec3808/pkg/storage/cloud/cloud_io.go#L307)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

you could keep both errors if you so choose: `return errors.CombineErrors(err, w.CloseWithError(err))`
</blockquote></details>

nifty.
___
*[pkg/storage/cloud/amazon/s3_storage.go, line 293 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65057#-M_W1EZQ-FYIQqvfSmcp:-M_XHnYHBoo6wnS-I7r9:b8b7iad) ([raw file](https://github.com/cockroachdb/cockroach/blob/b30ec19e9d6e4ded066cd3b1d06e55fc952c421c/pkg/storage/cloud/amazon/s3_storage.go#L293)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

not saying that this is bad... but we're changing implementation to use upload vs put object.
We should probably add this in the pr descriptor.
s3 manager seems to have settings around concurrency (default upload == 5).  What does that mean for us
(if anything)?  Should that be configurable?  Perhaps a TODO is in order to evaluate this.
</blockquote></details>

Oh, yeah, there's a huge implicit TODO around this whole change that we will need to test and tune each cloud afterwards, as well as revisit the callers to make them make use of a streaming write pattern. 

I just wanted to get a commit out as soon as I got the initial sweeping interface change compiling / passing tests, then do targeted changes for those.
___
*[pkg/storage/cloud/azure/azure_storage.go, line 135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65057#-M_W2FDz0qgvdBpKnVXh:-M_XGMZPAMf-Mro1xZ_4:bwivofc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b30ec19e9d6e4ded066cd3b1d06e55fc952c421c/pkg/storage/cloud/azure/azure_storage.go#L135)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

This seems rather arbitrary?  
I'm also curious/worried about the implication of this call, particularly in the face of slowness/unavailabilty of azure.  You could imagine having bunch of these uploads  starting ,all buffering 4 MB? 
</blockquote></details>

We'll need to account for the "a bunch of uploads starting" _anyway_ and reserve off a monitor for them. Indeed, we already needed to do this before, but for the whole file size, vs some fixed buffer like 4mb.

 The other SDKs have similar chunk buffers, and AWS has a _minimum_ of 5MB, so there is little point in going much smaller if we're going to have to pick at least that as the "cloud upload overhead" reservation size to grab off a monitor. Indeed, we may want to go higher, since each chunk is an API req and these clouds charge per request as well as per GB, so a too-small chunk size could cause some $$ request counts.
___
*[pkg/storage/cloud/gcp/gcs_storage.go, line 162 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65057#-M_W4s9VBMt0GoljFPBM:-M_XG5BL66kos2OBkCSB:bqg9jmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5bf73870b8b95a09767b71fd7a604ebcb4acb0e/pkg/storage/cloud/gcp/gcs_storage.go#L162)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Do we know if gcs retries? Is it safe to drop this?
</blockquote></details>

I'm not really sure -- we need to experiment with it. I guess I could leave some retries here, but they'd now just be around _creating_ the Writer, not actually doing the writes -- that'd be up to the caller, in how it uses that Writer. I'm assuming it _does_ do internal retries, because if it doesn't we'll want to do our own chunking, retry chunks, then stitch them after, but I have to imagine that's what the SDK is already doing and we'll just want to configure it.
___
*[pkg/storage/cloud/httpsink/http_storage.go, line 179 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65057#-M_X-HQJBE9PyGrp_K2I:-M_XFKOMAyiuk-kRQFAx:bcbi7yu) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5bf73870b8b95a09767b71fd7a604ebcb4acb0e/pkg/storage/cloud/httpsink/http_storage.go#L179)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I assume we're dropping this because, presumably the caller could set deadlines themselves...
Do we know if anything is effected by this?  Is this a safe change to make?
</blockquote></details>

Right, we now just return a writer, and the caller can decide when to write to it, how long to wait for that write, etc or e.g. put a timeout like this around an `io.Copy` call, but this thing here should just provide a writer which the caller decides how to use. 

The http client itself has an internal timeout.
___
*[pkg/storage/cloud/userfile/file_table_storage.go, line 269 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65057#-M_X-RgGCFmTD5UY4_kV:-M_XEehK2pFWU8R9d-Yv:b-29pod9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5bf73870b8b95a09767b71fd7a604ebcb4acb0e/pkg/storage/cloud/userfile/file_table_storage.go#L269)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Can you explain why it's safe to remove this?
</blockquote></details>

Hilariously, it is apparently doing nothing.

The internal executor isn't stateful, so the `BEGIN` begins a transaction... which then implicitly just ends. The `COMMIT` one above errors ("no transaction in progress" but we were throwing away the error. I only realized this when I started doing `COMMIT` (or `ROLLBACK`) in `Close()` (and `CloseWithError` respectively).

I think if we want the semantics it says it has, we'll need to thread a `kvclient.Txn` around, but that can be its own change.

**Review by miretskiy — APPROVED** [review]
All of the "scary" changes aside, I think this PR is great. So, :lgtm_strong: , and we'll shake whatever problems may arise  pretty soon... 

> Reviewed 1 of 8 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65057#-:-M_Xwj13CRo-iME1kCpq:b-rsi8bh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @miretskiy)

___
*[pkg/storage/cloud/gcp/gcs_storage.go, line 162 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65057#-M_W4s9VBMt0GoljFPBM:-M_XwSgO2ob5sf7Cz-BB:b-qeyk55) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5bf73870b8b95a09767b71fd7a604ebcb4acb0e/pkg/storage/cloud/gcp/gcs_storage.go#L162)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I'm not really sure -- we need to experiment with it. I guess I could leave some retries here, but they'd now just be around _creating_ the Writer, not actually doing the writes -- that'd be up to the caller, in how it uses that Writer. I'm assuming it _does_ do internal retries, because if it doesn't we'll want to do our own chunking, retry chunks, then stitch them after, but I have to imagine that's what the SDK is already doing and we'll just want to configure it.
</blockquote></details>

I'm fine with a TODO.  I really like the direction of this PR.

**Comment by dt** [comment]
I wonder if we should keep the WriteFile API side-by-side with Writer, so that smaller files can be put in a single API call (the uploader APIs often involve open call, 1 or more add block calls and then a finish call, so maybe 2 extra calls per file compared for small files?

**Comment by dt** [comment]
OTOH, making all put use the Writer API actually tests the writer API.

Also, at least in the google case, there's just no difference: we were _already_ using the `Writer` API and just running `io.Copy` to completion inside the put call. Maybe it should be up to an individual implementation of ExternalStorage.Writer to decide if it wants to buffer and to use a different API to put vs stream. Hmm.

**Review by adityamaru — COMMENTED** [review]
> Reviewed 22 of 22 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65057)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[pkg/storage/cloud/cloud_io.go, line 276 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/65057#-M_ZvG9I1OFmpbpQFNME:-M_ZvG9J7FlfUl_ugxH9:b173zx2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f20fb9d8050e24cf9f6ce047b635cd8cc62c44d1/pkg/storage/cloud/cloud_io.go#L276)):*
> ```Go
> }
> 
> type backroundPipe struct {
> ```

nit: backgroundPipe

**Comment by miretskiy** [comment]
Personally, I'm not a fan of too many utility functions like WriteFile.  I
think writer is totally fine.

**Comment by dt** [comment]
To be clear, I was suggesting not a utility function, but rather that `ExternalStorage` API would have *two* methods for writing files: one which puts a file in its entirety (`WriteFile`, which was here before) and then one which opens a file for incremental writing  (aka `Writer`, added here). I was musing that this might allow callers who are writing a small file / are already holding the whole thing in memory to use the put method, which could do the operation in a single API call for some clouds, vs opening for writing which is almost always 2+n (1 to open, one to finish and n to move the chunks of payload), so 3 for these where n is small. If we were writing hundreds of thousands of small files, 3 calls each vs 1 call each could be a big deal for request-count billing. (separately we should avoid making 100k small files, but that's another issue).

But I think I've  convinced myself that maybe the `Writer` implementation should just deal with this internally -- if this is an issue for a given cloud, we could service the initial `Write` calls by writing to a buffer, and only once it exceeds a certain size do we open the underlying cloud writer, drain it and then send subsequent writes straight to it while if closed before it fills, we instead put it via the other cloud API. I guess there's a slight downside in that it forces us to buffer a second copy of these small puts. Anyway, I think I might be getting lost in premature optimization here.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65057)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @miretskiy)

___
*[pkg/storage/cloud/cloud_io.go, line 300 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65057#-M_WxsCK-fSvo9vYCfee:-M__wEt5--HHqxcm3YHr:b9wzwwm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f6625d67079647bb2f5f77705713f31c3ec3808/pkg/storage/cloud/cloud_io.go#L300)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Heh, I thought of this after I'd already changed all the calls, but decided I didn't quite care enough about a temporary shim to go change them all again.
</blockquote></details>

turned out I did care enough

**Review by miretskiy — COMMENTED** [review]
> Reviewed 1 of 8 files at r3, 1 of 22 files at r5, 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65057)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @miretskiy)

**Comment by dt** [comment]
TFTRs!

bors r+

**Pull request merged**
