### PR TITLE
changefeedccl: Function resolution and cdc_prev handling

### LINKED ISSUE #92962: cdc: perform type resolution before function resolution and validation
Currently cdceval doesn't know what type a clause in an expression is going to be while it's resolving functions and validating the expression. That means we don't know which overload a function or operator is, and what is being cast to what, which is problematic mainly because they can have different volatility and require different session information to be serialized. We should perform these operations in the same order as the normal query planner so that these issues don't occur. Also, once we're allowing schema changes we should redo it all every time the schema changes.

Jira issue: CRDB-22070

Epic CRDB-17161

### LINKED ISSUE #92963: cdc: handle stable functions that query system tables
Some stable functions run a SQL query as part of their execution. When we allow stable functions in changefeed expressions, we should probably disallow those functions, or at least warn about them and ensure they get accounted for properly (resources, request units, metrics).

Jira issue: CRDB-22071

Epic CRDB-17161

### PR DESCRIPTION
**Pull request by miretskiy**
*changefeedcc: Rework cdc_prev handling*

Changeefed expressions may access the previous state of the row.
Prior to this change, this access was provided by adding
a subselect to the changefeed expression to return expanded
tuple containing the old state of the row:

```
 SELECT ... FROM tbl, (SELECT ((crdb_internal.cdc_prev_row()).*)) AS cdc_prev
```

This approach worked okay.  However, it had few problems.
CDC had to analyze all names in the expressions, and fully qualify
them prior to adding above subselect (this was required since otherwise,
names would collide).  Then, cdc had to understand
by analyzing expression, if access to the previous state of the row
was needed -- again, by analyzing expressions to see if anything
accessed "cdc_prev".  Then, there is the cost of invoking
additional function for each row.  And finally, this approach
would not work well if at some point changefeed expressions support
multiple target tables.

This PR moves majority of the complexity -- most importantly
name resolution and star expansion -- to the optimizer.
This is accomplished by letting the caller specify "extra"
columns that are added synthetically to the target table.
Since as far as the optimizer concerned these extra columns
are just like regular columns, all of the name resolution rules
apply -- and CDC gets those for free.

CDC arranges for a special `cdc_prev` column to be provided to the
optimizer.  This *hidden* column is a tuple typed column.

To access the previous state of the row the callers must
access `cdc_prev` explicitly:
```
CREATE CHANGEFEED ... AS
SELECT *, cdc_prev FROM tbl
```

If the caller wants to access previous state of a column,
then this is available as a named field in the cdc_prev tuple:

```
CREATE CHANGEFEED ... AS
SELECT *, cdc_prev FROM tbl
WHERE (cdc_prev).value = 'old'
```

Note: since cdc_prev is a tuple, accessing tuple fields requires
`()` around tuple name to disambiguate tuple field access from
table column access.

Epic: [CRDB-17161](https://cockroachlabs.atlassian.net/browse/CRDB-17161)

Release note (enterprise change): changefeed expressions have access
to cdc_prev tuple which contains the previous state of the row.

Release note (backward-incompatible change): changefeeds using
"preview" expressions (released in 22.2.0) and that access the
previous state of the row using old `cdc_prev()` function
will no longer work and will need to be recreated with new syntax.

----
Rework and clarify function resolution logic in CDC expressions.
Update doc.go to clarify handling of stable functions in CDC
expressions.  Add additional functions to the supported list
of expressions.

Add support for user defined functions in CDC expressions:
```
CREATE FUNCTION yesterday(mvcc DECIMAL)
RETURNS DECIMAL IMMUTABLE LEAKPROOF LANGUAGE SQL AS $$
  SELECT mvcc - 24 * 3600 * 1e9
$$;

CREATE CHANGEFEED ... AS
SELECT *, yesterday(crdb_internal_mvcc_timestamp) FROM tbl

```

Fixes https://github.com/cockroachdb/cockroach/issues/92962
Fixes https://github.com/cockroachdb/cockroach/issues/92963
Epic [CRDB-17161](https://cockroachlabs.atlassian.net/browse/CRDB-17161)

Release note (enterprise change): CDC expressions now support
non-volatile user defined functions.

### CODE REVIEW

**Comment by miretskiy** [comment]
@HonoreDB @mgartner the top 2 changes in this PR being reviewed https://github.com/cockroachdb/cockroach/pull/93979

**Comment by miretskiy** [comment]
@HonoreDB, @jayshrivastava  ping?

**Comment by jayshrivastava** [comment]
@miretskiy halfway through at the moment

**Review by jayshrivastava — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94429)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @mgartner, and @miretskiy)

___
*[`pkg/ccl/changefeedccl/cdceval/cdc_prev.go` line 42 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/94429#-NL1SGmi66ccME0pOzNC:-NL1SGmi66ccME0pOzND:b-be0mjn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11adcaa19c6e33e545b9635441f3bef2569f174/pkg/ccl/changefeedccl/cdceval/cdc_prev.go#L42)):*
> ```Go
> 	}
> 
> 	if colName == "" {
> ```

nit: It's a bit confusing to return this error here. From what I understand, `desc` not having `"cdc_prev", "crdb_internal_cdc_prev"` in `desc` is a side effect of the underlying table having `"cdc_prev", "crdb_internal_cdc_prev"` columns. It would be better to check this when we generate the descriptor.
___
*[`pkg/ccl/changefeedccl/cdceval/validation.go` line 39 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/94429#-NL1VVn6Dp3mwl5RXSUN:-NL1VVn6Dp3mwl5RXSUO:b-iaybc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11adcaa19c6e33e545b9635441f3bef2569f174/pkg/ccl/changefeedccl/cdceval/validation.go#L39)):*
> ```Go
> 
> // SelectStatementForFamily returns tree.Select representing this object.
> func (n *NormalizedSelectClause) SelectStatementForFamily() *tree.Select {
> ```

This is confusing. Firstly, where does `n.desc.FamilyID` come from? It doesn't come from the cf expression `create changefeed as select ...` right?
___
*[`pkg/sql/execinfrapb/processors_changefeeds.proto` line 63 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/94429#-NL1Ol4l4xbfXaVvVm1m:-NL1Ol4l4xbfXaVvVm1n:b-r7xujx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11adcaa19c6e33e545b9635441f3bef2569f174/pkg/sql/execinfrapb/processors_changefeeds.proto#L63)):*
> ```protobuf
>   // select is the "select clause" for predicate changefeed.
>   optional Expression select = 6 [(gogoproto.nullable) = false];
>   optional sessiondatapb.SessionData session_data = 7 [(gogoproto.nullable) = false];
> ```

Shouldn't `select` and `session_data` of these already exist in the `ChangefeedDetails`? I'm not sure if there's a good reason for them to be separate.



_Code quote:_
```protobuf
ChangefeedDetails
```
___
*[`pkg/sql/sem/tree/select.go` line 314 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/94429#-NL1UaNjD31t0uIYdewB:-NL1UaNjD31t0uIYdewC:b-tfrwb8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11adcaa19c6e33e545b9635441f3bef2569f174/pkg/sql/sem/tree/select.go#L314)):*
> ```Go
> // IndexFlags represents "@<index_name|index_id>" or "@{param[,param]}" where
> // param is one of:
> //   - FORCE_INDEX=<index_name|index_id>
> ```

This comment needs to be updated.

**Review by HonoreDB — COMMENTED** [review]
> Reviewed 2 of 15 files at r1, 36 of 36 files at r6, 16 of 16 files at r7, 22 of 22 files at r8, 21 of 21 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94429)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @miretskiy)

___
*[`pkg/ccl/changefeedccl/cdceval/functions.go` line 42 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/94429#-NL2-CbX4mw-MI0lT98B:-NL2-CbX4mw-MI0lT98C:b-2tutpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11adcaa19c6e33e545b9635441f3bef2569f174/pkg/ccl/changefeedccl/cdceval/functions.go#L42)):*
> ```Go
> 	"array_to_json":            useDefaultBuiltin,
> 	"array_to_string":          useDefaultBuiltin,
> 	"crdb_internal.cluster_id": useDefaultBuiltin,
> ```

This one's iffy because of the cluster to cluster streaming of job records thing.
___
*[`pkg/ccl/changefeedccl/cdceval/functions.go` line 245 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/94429#-NL2-ln0531bC3IWUcxb:-NL2-ln0531bC3IWUcxc:b-fbssji) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11adcaa19c6e33e545b9635441f3bef2569f174/pkg/ccl/changefeedccl/cdceval/functions.go#L245)):*
> ```Go
> 				// Same argument applies to overload.Class -- seeing heterogeneous
> 				// class would be surprising.
> 				functionBlacklist[fnDef.Name] = struct{}{}
> ```

nit: blacklist/whitelist is deprecated in crdb style, use denylist/allowlist.

**Review by miretskiy — COMMENTED** [review]
@jayshrivastava @honoredb  -- thanks for the reviews; comments addressed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94429#-:-NL22TtkDCtcb1eRp-2q:b-qiq1rq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @jayshrivastava, and @mgartner)

___
*[`pkg/ccl/changefeedccl/cdceval/cdc_prev.go` line 42 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/94429#-NL1SGmi66ccME0pOzNC:-NL1ugLY7FJ2WtkEcacP:bjydx4w) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11adcaa19c6e33e545b9635441f3bef2569f174/pkg/ccl/changefeedccl/cdceval/cdc_prev.go#L42)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

nit: It's a bit confusing to return this error here. From what I understand, `desc` not having `"cdc_prev", "crdb_internal_cdc_prev"` in `desc` is a side effect of the underlying table having `"cdc_prev", "crdb_internal_cdc_prev"` columns. It would be better to check this when we generate the descriptor.
</blockquote></details>

I guess I was trying to be too cleaver here.  I'm looking for a name to use for "cdc_prev" -- that name depends
on whether or not table has columns named cdc_prev or crdb_internal_cdc_prev... I want to use the
first name that's *not* in the table (notice err != nil check above -- err is nil if the column exists, and non-nil if
it doesn't.

Anyhow... Too clever. Redone.
___
*[`pkg/ccl/changefeedccl/cdceval/functions.go` line 42 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/94429#-NL2-CbX4mw-MI0lT98B:-NL20mKvDy0053pj1JCL:b-i8nl1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11adcaa19c6e33e545b9635441f3bef2569f174/pkg/ccl/changefeedccl/cdceval/functions.go#L42)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

This one's iffy because of the cluster to cluster streaming of job records thing.
</blockquote></details>

what does that have to do with cdc potentially wanting to include cluster_id in a message?
I guess, you're worried about this job being restored on the other cluster.
I'm not worried about that because ... changefeeds would break way before that -- i.e. spans
include tenant id, which needs to change on the other cluster.
Currently, the best way to migrate those feeds is to cancel/recreate them anyway.

If you feel like we should drop it, let me know.
___
*[`pkg/ccl/changefeedccl/cdceval/functions.go` line 245 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/94429#-NL2-ln0531bC3IWUcxb:-NL20seJ5_efd_m2ZCsv:bv8sta3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11adcaa19c6e33e545b9635441f3bef2569f174/pkg/ccl/changefeedccl/cdceval/functions.go#L245)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

nit: blacklist/whitelist is deprecated in crdb style, use denylist/allowlist.
</blockquote></details>

ahhh... lint didn't complain... but okay.
___
*[`pkg/ccl/changefeedccl/cdceval/validation.go` line 39 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/94429#-NL1VVn6Dp3mwl5RXSUN:-NL1wN7Z7iHYOgQcUmbC:b-xkg04v) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11adcaa19c6e33e545b9635441f3bef2569f174/pkg/ccl/changefeedccl/cdceval/validation.go#L39)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

This is confusing. Firstly, where does `n.desc.FamilyID` come from? It doesn't come from the cf expression `create changefeed as select ...` right?
</blockquote></details>

this object is created with the underlying  *cdcevent.EventDescriptor which always has column family ID set (and the family ID comes from the underlying KVs -- when we decode them, we know which family it belongs to because family ID is part of the key).

This used to be called SelectStatement, but I wanted to be explicit that I will leverage column family ID in this statement... But if you have better suggestions for naming -- please let me know.
___
*[`pkg/sql/execinfrapb/processors_changefeeds.proto` line 63 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/94429#-NL1Ol4l4xbfXaVvVm1m:-NL1zxbjDxaSlOcWqF3N:b-wyxp0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11adcaa19c6e33e545b9635441f3bef2569f174/pkg/sql/execinfrapb/processors_changefeeds.proto#L63)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

Shouldn't `select` and `session_data` of these already exist in the `ChangefeedDetails`? I'm not sure if there's a good reason for them to be separate.
</blockquote></details>

Hmm... That's a good point.
I'm not going to drop Expression though -- that'd be annoying backward incompatible 
mechanism.  I remember though why I added it: rest of execinfra uses Expression protocol message
to represent expressions; it felt more "correct" to use that.  Also, I included it because it is possible
that the expression we send to the aggregators may be different from the one in the changefeed record, and I believe it was at some point, because of all of the normalization/validation steps.  Anyway, keeping expression, but going to drop addition of session data.
___
*[`pkg/sql/sem/tree/select.go` line 314 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/94429#-NL1UaNjD31t0uIYdewB:-NL1xe874B4dJg0wU1gV:b-q3nax5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11adcaa19c6e33e545b9635441f3bef2569f174/pkg/sql/sem/tree/select.go#L314)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

This comment needs to be updated.
</blockquote></details>

I think this file is part of another PR being reviewed; I'll update there.

**Review by mgartner — APPROVED** [review]
:LGTM: for the optimizer-related things.

> Reviewed 17 of 17 files at r13, 5 of 11 files at r15.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94429#-:-NL6fjPG5nI0VeoSwaB9:b-sxgtcp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @HonoreDB, @jayshrivastava, and @miretskiy)

___
*[`pkg/ccl/changefeedccl/cdceval/cdc_prev.go` line 44 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/94429#-NL6dtm105K6Q-15aob_:-NL6dtm105K6Q-15aoba:buzimcd) ([raw file](https://github.com/cockroachdb/cockroach/blob/60ac67d7452eda2bf113347926ed46230781ff88/pkg/ccl/changefeedccl/cdceval/cdc_prev.go#L44)):*
It might be best to lock down a well-defined behavior here. Do changefeeds have unique names that a user could use to qualify the `cdc_prev` column? If so, we could make this match the behavior of UDFs when an argument name collides with a column name of a table that's in scope of a statement inside the UDF. From https://www.postgresql.org/docs/current/xfunc-sql.html:

> To use a name, declare the function argument as having a name, and then just write that name in the function body. If the argument name is the same as any column name in the current SQL command within the function, the column name will take precedence. To override this, qualify the argument name with the name of the function itself, that is function_name.argument_name. (If this would conflict with a qualified column name, again the column name wins. You can avoid the ambiguity by choosing a different alias for the table within the SQL command.)

So, if I created a changefeed called `myfeed` and I had a table `tab` with a `cdc_prev` column, a plain `cdc_prev` column would be resolved to `tab.cdc_prev`, and I could use `myfeed.cdc_prev` to access the previous row.

This shouldn't be too hard to make work with the optimizer's column resolution, but it's dependent on having a sensible name to qualify the synthesized `cdc_prev` column.

Can you leave a TODO/ticket?
___
*[`pkg/ccl/changefeedccl/cdceval/doc.go` line 92 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/94429#-NL6gLB_-mic92pjXwvZ:-NL6gLB_-mic92pjXwv_:bklalan) ([raw file](https://github.com/cockroachdb/cockroach/blob/21fc471b0cdfe17b4f3354689193260863504627/pkg/ccl/changefeedccl/cdceval/doc.go#L92)):*
> ```Go
>   * Is the stable function actually volatile in CDC context?
>     Example functions include crdb_internal.node_id, current_setting, gateway_region, etc.
>     These functions are stable, but if the changefeed restarts, all of these
> ```

Can you explain how changefeed restarts behave? Stable functions are defined as functions that return the same result when given the same input within a single statement. If the mental model of these changefeed expressions is "for every change, apply the filters and projections in this expression", then it seems valid to allow stable functions. Do you have an example of what would break if we allowed a stable function?
___
*[`pkg/ccl/changefeedccl/cdceval/func_resolver.go` line 28 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/94429#-NL6hJRi0MOgNvJ_Rl-P:-NL6hJRi0MOgNvJ_Rl-Q:b-obymot) ([raw file](https://github.com/cockroachdb/cockroach/blob/21fc471b0cdfe17b4f3354689193260863504627/pkg/ccl/changefeedccl/cdceval/func_resolver.go#L28)):*
> ```Go
> }
> 
> func newCDCFunctionResolver(wrapped tree.FunctionReferenceResolver) tree.FunctionReferenceResolver {
> ```

This is fine for now, but in the long term I don't think we should be using custom function resolution logic for this purpose. Function resolution is complex and we currently do it incorrectly (see #75101). It'll be painful to maintain two implementations. Instead, I think we should define builtins that can be resolved in any context - the CDC-specific ones can error if used outside of a CDC expression. Feel free to make a ticket and/or leave a TODO for this.
___
*[`pkg/sql/distsql_plan_changefeed.go` line 528 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/94429#-NL6dIGaDY2TfraimaoC:-NL6dIGbEbAISoy7i28G:bwxjl7t) ([raw file](https://github.com/cockroachdb/cockroach/blob/60ac67d7452eda2bf113347926ed46230781ff88/pkg/sql/distsql_plan_changefeed.go#L528)):*
> ```Go
> }
> 
> func (d *familyTableDescriptor) filterColumns(cols []catalog.Column) []catalog.Column {
> ```

nit: This is a bit confusingly named because now it's doing more than filtering - it's also adding extraCols.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94429)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @HonoreDB, @jayshrivastava, and @mgartner)

___
*[`pkg/ccl/changefeedccl/cdceval/cdc_prev.go` line 44 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/94429#-NL6dtm105K6Q-15aob_:-NLLigNA4eTQMKqxT2NJ:bwcacbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/60ac67d7452eda2bf113347926ed46230781ff88/pkg/ccl/changefeedccl/cdceval/cdc_prev.go#L44)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It might be best to lock down a well-defined behavior here. Do changefeeds have unique names that a user could use to qualify the `cdc_prev` column? If so, we could make this match the behavior of UDFs when an argument name collides with a column name of a table that's in scope of a statement inside the UDF. From https://www.postgresql.org/docs/current/xfunc-sql.html:

> To use a name, declare the function argument as having a name, and then just write that name in the function body. If the argument name is the same as any column name in the current SQL command within the function, the column name will take precedence. To override this, qualify the argument name with the name of the function itself, that is function_name.argument_name. (If this would conflict with a qualified column name, again the column name wins. You can avoid the ambiguity by choosing a different alias for the table within the SQL command.)

So, if I created a changefeed called `myfeed` and I had a table `tab` with a `cdc_prev` column, a plain `cdc_prev` column would be resolved to `tab.cdc_prev`, and I could use `myfeed.cdc_prev` to access the previous row.

This shouldn't be too hard to make work with the optimizer's column resolution, but it's dependent on having a sensible name to qualify the synthesized `cdc_prev` column.

Can you leave a TODO/ticket?
</blockquote></details>

This is an excellent suggestion; Alas, changefeeds don't have a name -- at least not right now.
I copied your comment as a TODO.
___
*[`pkg/ccl/changefeedccl/cdceval/doc.go` line 92 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/94429#-NL6gLB_-mic92pjXwvZ:-NLLioc9E9eJsdnYTNa4:b6xzndc) ([raw file](https://github.com/cockroachdb/cockroach/blob/21fc471b0cdfe17b4f3354689193260863504627/pkg/ccl/changefeedccl/cdceval/doc.go#L92)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you explain how changefeed restarts behave? Stable functions are defined as functions that return the same result when given the same input within a single statement. If the mental model of these changefeed expressions is "for every change, apply the filters and projections in this expression", then it seems valid to allow stable functions. Do you have an example of what would break if we allowed a stable function?
</blockquote></details>

We had a discussion offline.  We want to make sure that even if changefeed restarts on a different node, 
different time, etc, that the same event (i.e. same key@ts) would produce the same results.
___
*[`pkg/ccl/changefeedccl/cdceval/func_resolver.go` line 28 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/94429#-NL6hJRi0MOgNvJ_Rl-P:-NLLj_SP2i9T6ppZXWwq:b-mskow5) ([raw file](https://github.com/cockroachdb/cockroach/blob/21fc471b0cdfe17b4f3354689193260863504627/pkg/ccl/changefeedccl/cdceval/func_resolver.go#L28)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This is fine for now, but in the long term I don't think we should be using custom function resolution logic for this purpose. Function resolution is complex and we currently do it incorrectly (see #75101). It'll be painful to maintain two implementations. Instead, I think we should define builtins that can be resolved in any context - the CDC-specific ones can error if used outside of a CDC expression. Feel free to make a ticket and/or leave a TODO for this.
</blockquote></details>

TODO added; though, I think situation as of this PR improved a lot since the actual resolution
gets delegated to the real resolver, and the only thing added are sanity checks to make sure the
resolved overload is okay to use in CDC context.  Of course, even that part may be incorrect, but I feel
more confident w/ the current code.
___
*[`pkg/sql/distsql_plan_changefeed.go` line 528 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/94429#-NL6dIGaDY2TfraimaoC:-NLLkhH635igPScOMU2v:brreqs9) ([raw file](https://github.com/cockroachdb/cockroach/blob/60ac67d7452eda2bf113347926ed46230781ff88/pkg/sql/distsql_plan_changefeed.go#L528)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: This is a bit confusingly named because now it's doing more than filtering - it's also adding extraCols.
</blockquote></details>

This change was done as part of https://github.com/cockroachdb/cockroach/pull/93979 -- so, going to fix comment/naming there.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94429)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @HonoreDB, @jayshrivastava, and @mgartner)

___
*[`pkg/sql/distsql_plan_changefeed.go` line 528 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/94429#-NL6dIGaDY2TfraimaoC:-NLLks9R-0jJye1mUCM5:b-jwwzw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/60ac67d7452eda2bf113347926ed46230781ff88/pkg/sql/distsql_plan_changefeed.go#L528)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

This change was done as part of https://github.com/cockroachdb/cockroach/pull/93979 -- so, going to fix comment/naming there.
</blockquote></details>

Ooops... sorry, I"m wrong; going to fix it here.

**Review by jayshrivastava — APPROVED** [review]
LGTM 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94429#-:-NLLnWClEKBzoiTYw4uf:b-85i649)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @HonoreDB and @mgartner)

**Review by mgartner — APPROVED** [review]
:lgtm_strong: 

> Reviewed 31 of 31 files at r16, 21 of 21 files at r17, 16 of 16 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94429#-:-NLRaasKDYge6OGbv6kz:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @HonoreDB and @jayshrivastava)

**Pull request merged**
