### PR TITLE
roachprod: add mutex for roachprod log writers

### PR DESCRIPTION
**Pull request by herkolategan**
The roachprod logger relies on the standard log output's internal synchronization, but there are a few cases where the writers (Stdout, Stderr) are used directly. This adds a safe writer wrapper around these outputs to prevent log overlaps.

Epic: None
Release note: None

### CODE REVIEW

**Review by DarrylWong — COMMENTED** [review]
I think I understand the issue this PR is trying to solve, but if we create multiple Loggers through `NewLogger`, won't we still have concurrent access to `stdout`/`stderr` as the mutexes aren't shared?

**Comment by herkolategan** [comment]
> I think I understand the issue this PR is trying to solve, but if we create multiple Loggers through NewLogger, won't we still have concurrent access to stdout/stderr as the mutexes aren't shared?

Good observation, but afaik roachtest only passes os.Stdout / os.Stderr if "tee" is enabled (a single test is run & no parallelism). The other thing to consider is that there will be only one logger per file, but that logger might be shared in a goroutine (parallel run etc.), which this PR will protect against. And there is only one "tee" logger that outputs to os.Stdout / os.Stderr, but might also be shared amongst goroutines.

That said, I remember seeing overlap somewhere, and I noted it down on a todo list. So maybe it's not such a big issue, doesn't regularly happen.

**Comment by DarrylWong** [comment]
>Good observation, but afaik roachtest only passes os.Stdout / os.Stderr if "tee" is enabled

Ah gotcha, that's what I was trying (and failing) to figure out. If so this change LGTM. 

Perhaps it might be good to add some of that explanation inside of `NewLogger` though. It's a bit annoying to track down all the usages of logger when trying to understand what's going on, having some context would be nice.

**Review by DarrylWong — APPROVED** [review]

**Comment by herkolategan** [comment]
TFTR!

bors r=DarrylWong

**Pull request merged**
