### PR TITLE
[DNM] kv: prototype async Raft log writes

### PR DESCRIPTION
**Pull request by nvb**
See #17500.

This commit polishes and flushes a prototype I've had lying around that demonstrates the async Raft log appends component of #17500. I'm not actively planning to productionize this, but it sounds like we may work on this project in v23.1, so this prototype might help. It also demonstrates the kind of performance wins we can expect to see on write-heavy workloads. To this point, we had only [demonstrated the potential speedup](https://github.com/cockroachdb/cockroach/issues/17500#issuecomment-757344603) in a simulated environment with [rafttoy](https://github.com/nvanbenschoten/rafttoy).

Half of the change here is to `etcd/raft` itself, which needs to be adapted to support asynchronous log writes. These changes are presented in https://github.com/nvanbenschoten/etcd/commit/1d1fa32ec22715f6e21a6d6486f865356c3eb4fc.

The other half of the change is extracting a Raft log writer component that handles the process of asynchronously appending to a collection of Raft logs and notifying individual replicas about the eventual durability of these writes. This component is pretty basic and should probably be entirely rewritten, but it gets the job done for the prototype.

The Raft log writer reveals an interesting dynamic where concurrency at this level actually hurts performance because it leads to concurrent calls to sync Pebble's WAL, which is less performant than having a single caller due to the fact that Pebble only exposes a synchronous Sync API and coalesces all Sync requests on to a single thread. An async Pebble Sync API would be valuable here. See the comment in NewWriter for more details.

### Benchmarks

```
name                          old ops/s    new ops/s    delta
kv0/enc=false/nodes=3/cpu=32   36.4k ± 5%   46.5k ± 5%  +27.64%  (p=0.000 n=10+10)

name                          old avg(ms)  new avg(ms)  delta
kv0/enc=false/nodes=3/cpu=32    5.26 ± 3%    4.14 ± 6%  -21.33%  (p=0.000 n=8+10)

name                          old p99(ms)  new p99(ms)  delta
kv0/enc=false/nodes=3/cpu=32    10.9 ± 8%     9.1 ±10%  -15.94%  (p=0.000 n=10+10)
```

These are compelling results. I haven't pushed on this enough to know whether there's actually a throughput win here, or whether the fixed concurrency and reduced average latency is just making it look like there is. `kv0bench` should help answer that question.

cc. @erikgrinaker

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87050)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sumeerbhola)

___
*[`pkg/kv/kvserver/raftlog/writer.go` line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87050#-NCg-fyaA3axDQ6FJ1Fb:-NCg-fyaA3axDQ6FJ1Fc:bv11mve) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c132e6bc812c9ec24aaf69edada535a6f9b4a0/pkg/kv/kvserver/raftlog/writer.go#L73)):*
> ```Go
> 	// some goroutine wait on a sync to be notified of durability. An asynchronous
> 	// variant of Pebble's API (similar to Pebble's own syncQueue) that is hooked
> 	// directly into Pebble's LogWriter.flushLoop would help.
> ```

I reread our slack thread from May 19, which touched on this.
Our current synchronous scheme incurs a mean of 1.5x the latency of a single LogWriter flush+sync since the LogWriter is working on something and must finish it before flushing again. And we ignore the latency incurred in waiting for a `raftScheduler.worker` because we assume that there are enough workers that someone will be free. This assumption partly relies on the fact that there is no deterministic assignment of replicas=>workers, so we don't have to worry about getting a hotspot because of a poor assignment. If we mirror that approach in these writers, i.e., no deterministic assignment, and enough writers, we can continue to assume zero latency in waiting for the writer to be free. Not having a deterministic assignment is also generally good to smear out the load. So I don't think we need an async API in Pebble.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87050)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/raftlog/writer.go` line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87050#-NCg-fyaA3axDQ6FJ1Fb:-ND-4mdECLNMXhT4KxZS:b1e2lzn) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c132e6bc812c9ec24aaf69edada535a6f9b4a0/pkg/kv/kvserver/raftlog/writer.go#L73)):*
[Sumeer and I discussed this over lunch]

> This assumption partly relies on the fact that there is no deterministic assignment of replicas=>workers, so we don't have to worry about getting a hotspot because of a poor assignment. If we mirror that approach in these writers, i.e., no deterministic assignment, and enough writers, we can continue to assume zero latency in waiting for the writer to be free.

While this is true across ranges, we do still need to pay for ordering within a range because we need log writes for a given range to be performed in increasing index order without the possibility of gaps. This is where the desire for an async API comes from. Without an async API, a log write for a given range needs to wait for the sequencing (seq num assignment) _and the sync_ of previous writes for that range. Ideally, it would only need to wait for the sequencing of previous writes and could then independently wait for the sync.

Assuming multiple ranges and a full replication pipeline within each range, the sync Pebble API incurs an average-case 1.5x latency multiplier to order log writes within a range and then another average-case 1.5x latency multiplier when syncing log writes while waiting for syncs from other ranges due to the single LogWriter flush+sync loop you mentioned. Combined, that means that the average-case latency multiplier to get through this `Write.Append` call is 2.25x.

`shards = 1` helps because it avoids the second multiplier, but only because no one else is syncing in the system and as a result, the LogWriter flush+sync loop idles when not being synced by this writer. I think one way to get around the absence of an async API is to stop sync-ing individual WriteBatch writes and to lift our own flushing loop up here that calls `Pebble.SyncWAL` in a loop. That would allow us to build our own async API. But I'd like to avoid that. That also only helps if no one else in the system is ever driving the Pebble `LogWriter` sync loop.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87050)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sumeerbhola)

___
*[`pkg/kv/kvserver/raftlog/writer.go` line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87050#-NCg-fyaA3axDQ6FJ1Fb:-ND4hvFOCeuJlPo4uyvY:b-xge32z) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c132e6bc812c9ec24aaf69edada535a6f9b4a0/pkg/kv/kvserver/raftlog/writer.go#L73)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

[Sumeer and I discussed this over lunch]

> This assumption partly relies on the fact that there is no deterministic assignment of replicas=>workers, so we don't have to worry about getting a hotspot because of a poor assignment. If we mirror that approach in these writers, i.e., no deterministic assignment, and enough writers, we can continue to assume zero latency in waiting for the writer to be free.

While this is true across ranges, we do still need to pay for ordering within a range because we need log writes for a given range to be performed in increasing index order without the possibility of gaps. This is where the desire for an async API comes from. Without an async API, a log write for a given range needs to wait for the sequencing (seq num assignment) _and the sync_ of previous writes for that range. Ideally, it would only need to wait for the sequencing of previous writes and could then independently wait for the sync.

Assuming multiple ranges and a full replication pipeline within each range, the sync Pebble API incurs an average-case 1.5x latency multiplier to order log writes within a range and then another average-case 1.5x latency multiplier when syncing log writes while waiting for syncs from other ranges due to the single LogWriter flush+sync loop you mentioned. Combined, that means that the average-case latency multiplier to get through this `Write.Append` call is 2.25x.

`shards = 1` helps because it avoids the second multiplier, but only because no one else is syncing in the system and as a result, the LogWriter flush+sync loop idles when not being synced by this writer. I think one way to get around the absence of an async API is to stop sync-ing individual WriteBatch writes and to lift our own flushing loop up here that calls `Pebble.SyncWAL` in a loop. That would allow us to build our own async API. But I'd like to avoid that. That also only helps if no one else in the system is ever driving the Pebble `LogWriter` sync loop.
</blockquote></details>

I agree that CockroachDB should not need to call something like `Pebble.SyncWAL` in a loop since it becomes complicated to coordinate what got synced.
I'll get you to explain the 2.25x calculation in front of a whiteboard. I get the same answer but by: 1.5x fsync for doing a fsync'd write to Pebble + 1.5x/2 for waiting for this worker thread that is doing the write to free up = 2.25x. What you are asking for would make this 1x latency, and perhaps more importantly would remove the 1.5x fsync of wait for IO time from the worker thread, which allows for higher throughput on the range (which may allow us to make the ranges fatter), and makes the throughput (assuming an open loop workload), insensitive to variations in fsync latency.

Making the Pebble change should be easy -- do you want it now for this prototype, or later when we are writing the production code?

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87050)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola and @tbg)

___
*[`pkg/kv/kvserver/raftlog/writer.go` line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87050#-NCg-fyaA3axDQ6FJ1Fb:-ND7ZUFj9a_vN1PsuiIO:b-6wpyse) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c132e6bc812c9ec24aaf69edada535a6f9b4a0/pkg/kv/kvserver/raftlog/writer.go#L73)):*
> I'll get you to explain the 2.25x calculation in front of a whiteboard

:+1: I was also not able to really confirm this one. Also, depending on how you model it, I think the actual wait might be longer. When the inflight shard finishes, and ours starts, it has no chance to catch a 50% done pebble sync. It'll either be the one starting the sync or it has to latch onto a sync that just started. The average is 0.5, but only if you assume both cases are equally likely. In a system where many ranges are seeing write, the average is closer to 1.

Anyway, it seems clear that a an API that asynchronously confirms inflight fsyncs is the right solution.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87050)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola and @tbg)

___
*[`pkg/kv/kvserver/raftlog/writer.go` line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87050#-NCg-fyaA3axDQ6FJ1Fb:-ND95qF_2RQQksAKpXPa:b14e3n5) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c132e6bc812c9ec24aaf69edada535a6f9b4a0/pkg/kv/kvserver/raftlog/writer.go#L73)):*
> The average is 0.5, but only if you assume both cases are equally likely. In a system where many ranges are seeing write, the average is closer to 1.

For the case where all writer shards are writing+syncing in a tight loop, I think you are correct that each individual shard ends up participating in every second sync. This leads to an expected wait time of 1 sync, so using multiple shards doubles the latency of any individual shard's call to sync. That's directly in line with my prototype results.

> Making the Pebble change should be easy -- do you want it now for this prototype, or later when we are writing the production code?

If you think the changes should be easy and are willing to make them then I'd be happy to integrate them into this PR. I've been working on the process of productionizing the changes to etcd/raft, which should be in a good enough state to rebase this PR on shortly.

**Comment by nvanbenschoten** [comment]
Replaced by https://github.com/cockroachdb/cockroach/pull/94165.

**Pull request closed without merging**
