### PR TITLE
sql: Add support for nested arrays to ColumnType (patch 5/)

### PR DESCRIPTION
**Pull request by knz**
Split from #36598 cc @andy-kimball 

Previously, ColumnType did not support nested arrays. This commit lifts that
restriction by changing the type of the ArrayContents field from *SemanticType
to *ColumnType (the old field is renamed and deprecated). The marshal and
unmarshal code maps to and from the old representation in order to preserve
backwards-compatibility.

In addition, a nil ArrayDimensions field now means the array has a single
unbounded dimension. This will eventually allow for simple Array declarations:

  types.T{SemanticType: ARRAY, ArrayContents: types.Int}

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
This commit really contains two separate changes. 

- you have extended the list of advertised supported OIDs (via `types.OidToType`), to include `_int2vector` (arrays of INT2VECTOR), `_regproc` etc. I think this doesn't hurt *although CockroachDB does not yet support storing those things in tables* so it's not really required IMHO. If you decide to keep this change, **please add a release note to the commit message** to advertise the new entries.

- you are doing things about nested array types. Regarding this aspect, I think the commit is currently a bit confused. I want to separate two separate points.

  - regarding the type change for ArrayContent in the protobuf definitions from SemanticType to ColumnType - yes OK why not, I have no objections. This makes the code easier to understand.
  - regarding whether to actually *support* this combination in the rest of the code. I think here you're crossing a line which this PR / patch set should not cross.

Let me be clear: **I think that any nested array types should be rejected with unimplemented errors** throughout the code base. Both when attempting to construct one, and when attempting to read one from a table descriptor.

There are three things that "don't work" for me:

- assigning nested arrays the OID value zero. This is going to bite us later. You have determined that PostgreSQL does not have pre-defined OIDs for nested arrays, so the problem was seemingly harder to solve. But that does not make zero a good choice. PostgreSQL has a method to generate OIDs beyond the predefined set. This should be explored. Until this is explored, there should be no bogus / random / zero OID values returned to clients. 

   Our previous understanding was that the only way to avoid wondering which OID value to use in those cases was to refuse constructing a nested array type. What I wrote above.

- you write "The marshal and unmarshal code maps to and from the old representation" except, that's not true. A nested array type with your new representation does not map to/from accurately with the old representation. Instead of doing something random/broken that's going to create hard-to-interpret situations in the future [1], it's much better to refuse to create nested array types in the new situation. What I wrote above.

- "a nil ArrayDimensions field now means the array has a single unbounded dimension." - not a good choice. The number of dimensions (the number of entries in the dimension arrays) has semantic value. Zero dimensions means that the value is a scalar (i.e. not an array). 

  This in turn reminds me of something I had wanted to discuss with you **before** you embarked into this refactoring. IMHO, the ArrayDimensions field *alone* should determine that a column has an array type. The ArrayContents field is *not necessary*. 


Regarding "hard to interpret situations" we have the following scenario to contend with:

1. 19.2 node creates a table T with an "advanced" type
2. 19.1 node runs ALTER TABLE on that table, and rewrites the descriptor
3. 19.2 node reads the modified descriptor

You need to find a way that all types valid in 19.2 are also valid in 19.1, OR to prevent the use of any new types in 19.2 until the cluster version is bumped (i.e. you know there are no 19.1 nodes active any more).

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36702#-:-Lc5ibre3ImlJ72fB3qi:biwuk7r)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/testutils/testcat/test_catalog.go, line 743 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36702#-Lc5hvvWDxjcfoFg3YOg:-Lc5hvvWDxjcfoFg3YOh:beqevjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e96cdc82d2b6c8e1424a3e8d9f0d00b24b2aa92/pkg/sql/opt/testutils/testcat/test_catalog.go#L743)):*
> ```Go
> // ColTypePrecision is part of the cat.Column interface.
> func (tc *Column) ColTypePrecision() int {
> 	// TODO(andyk): This only handles one level of nesting.
> ```

Maybe it's worth adding an error check and raise an unimplemented error here.
___
*[pkg/sql/sqlbase/structured.go, line 2798 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36702#-Lc5iSKH1lCL-PfGbvlo:-Lc5iSKI7Io-BkAwG3Cz:b-x9crv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e96cdc82d2b6c8e1424a3e8d9f0d00b24b2aa92/pkg/sql/sqlbase/structured.go#L2798)):*
> ```Go
> // ColTypePrecision is part of the cat.Column interface.
> func (desc *ColumnDescriptor) ColTypePrecision() int {
> 	// TODO(andyk): This only handles one level of nesting.
> ```

ditto error checking and unimplemented error

**Comment by knz** [comment]
Also once you get a green build on the previous commit (#36701) let's look at the CI tests on this one.

**Review by andy-kimball — COMMENTED** [review]
Remember that just because we're adding support for nested arrays in `ColumnType` *does not* mean we support nested arrays as a column type. In fact, we absolutely do not support nested arrays as a column type. If you try to create a table with that type, it will fail just like it always have.

However, we still must support marshaling datums using DistSQL. My understanding is that array datums can have nested array types, and so we must support them for that reason. Is that not correct? Certainly the old `types.TArray` did allow these types to be constructed, so I assumed they could also be marshaled in some cases.

I have no wish to add support for anything that we don't actually need. But just because we support nested arrays in our type struct does not mean we need to support them everywhere else.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36702#-:-Lc8jPkh6jBIwP5t0dDA:b6f1c55)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball)

**Comment by andy-kimball** [comment]
Maybe we can sync up about these issues tomorrow morning, since I'm unclear on what we do/do not need to support. Also, I'm not quite understanding an ArrayContents field is not necessary (or are you saying it's not necessary unless/until we fully support nested arrays?).

**Comment by knz** [comment]
Did you mess up a rebase / add an intermediate commit? One of your latest pushes broke the PR sequencing -- there are merge conflicts now.

**Comment by knz** [comment]
Until you rebase this against the proper root (and re-push) Reviewable is broken, so I'll refrain from reviewing this patch further.

However coming back to my comment above: my concern is with code like this:

```go
// ColTypePrecision is part of the cat.Column interface.
func (tc *Column) ColTypePrecision() int {
	// TODO(andyk): This only handles one level of nesting.
	if tc.ColType.SemanticType == types.ARRAY {
		return int(tc.ColType.ArrayContents.Precision)
	}
	return int(tc.ColType.Precision)
}
```

I think that this code should read instead:

```go
// ColTypePrecision is part of the cat.Column interface.
func (tc *Column) ColTypePrecision() (int, error) {
	// TODO(andyk): This only handles one level of nesting.
	if tc.ColType.SemanticType == types.ARRAY {
        if tc.ColType.ArrayContents.SemanticType == types.ARRAY {
           return 0, pgerror.UnimplementedWithIssue(....)
        }
		return int(tc.ColType.ArrayContents.Precision), nil
	}
	return int(tc.ColType.Precision), nil
}
```

and similarly for the other places.

In particular you should not allow the OID value zero to be reported for "unsupported" cases and instead produce errors in those cases.

**Review by andy-kimball — COMMENTED** [review]
Re: the intermediate commit stuff, I've only force pushed commits before this one. I haven't attempted to rebase this one on top of those yet, so the merge conflicts will continue to stack up. I'm just adding comments to later patches in response to your request that I read your comments in case they impact older commits. These array issues are going to block me from rebasing this until I know better what I need to do.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36702#-:-LcA-Kh6DdlqOFOPKo0P:b-httstb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball)

**Comment by andy-kimball** [comment]
- I added a release note referencing the changes to `pg_catalog.pg_type`. I did that in this commit because I wanted all OIDs that might be returned by ARRAY types to be advertised.
- As long as we want to retain compatibility with the old `types.T`, as well as `DArray`, I think we need to have `ArrayContents` be a nested type, so I've left that part of the change in-place.
- I removed code to marshal/unmarshal nested arrays, since it sounds like that's never possible today. Instead, I return an assertion error if it's attempted.
- I updated the ARRAY oid code to never return 0, even in the case where arrays are nested in intermediate evaluation steps.
- I deprecated `ArrayDimensions` entirely, since they didn't appear to be used anywhere. The previous commit message was in error about mapping to nil -- that was based on an older version of this commit.
- Note that there's one special case: there's no T__unknown OID, because it's not possible to create an array of unknown in PG (I think). However, CRDB does allow that, and in past versions it returned 0 for this case (see `unknownArrayOid`, which was renamed from `noArrayType` in this commit).

**Review by knz — COMMENTED** [review]
:lgtm: modulo fixing the linter error. Thank you!

> Reviewed 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36702#-:-LcFyuJ98e_zTM_-OQcK:bt1lhih)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball)

**Pull request closed without merging**
