### PR TITLE
sql: remove 'experimental_always' as an option for vectorize cluster setting

### PR DESCRIPTION
**Pull request by yuzefovich**
If we allow such thing, then it is quite painful to reset the
cluster setting. It is also quite tricky to allow the corresponding
query to go around the vectorized engine when the vectorize cluster
setting is 'experimental_vectorize` even if the session variable is
'off' because the internal executor uses the cluster setting.

Release note: None

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
What about just removing the "experimental_always" setting from the cluster setting?

**Comment by yuzefovich** [comment]
I didn't even realize it was an option! Thanks, it's a lot cleaner this way.

Also, is there a way to "advertise" `experimental_always` as a session variable since it's no longer included in the generated `settings.html`?

**Review by jordanlewis — APPROVED** [review]
LGTM - I'm not sure if there's a particular way to "advertise" the setting besides normal documentation.

**Comment by yuzefovich** [comment]
I guess if someone really wants to use `experimental_always`, they will know about this option.

TFTR!

bors r+

**Pull request merged**
