### PR TITLE
kvserver,server: add more load stats to hot ranges v2 api

### LINKED ISSUE #95383: server: add hot ranges v1 load statistics to hot ranges v2 api
Currently, the hot ranges v2 API only supports gathering and using the QPS per range.

This issue is to include the additional statistics available on the hot ranges v1 API:

https://github.com/cockroachdb/cockroach/blob/0f6333cbd6c78264a59dc435324c0c33d75ea148/pkg/server/serverpb/status.proto#L1324-L1338

Into the hot ranges v2 response:

https://github.com/cockroachdb/cockroach/blob/0f6333cbd6c78264a59dc435324c0c33d75ea148/pkg/server/serverpb/status.proto#L1402-L1405

Jira issue: CRDB-23495

### LINKED ISSUE #95384: kvserver,server: surface cpu in hot ranges API (v1) and range status
The hot ranges v1 API currently includes qps and read/write bytes/keys for the top qps ranges. This issue is to include CPU in the hot ranges v1 API alongside these metrics.

Hot Ranges V1:

https://github.com/cockroachdb/cockroach/blob/0f6333cbd6c78264a59dc435324c0c33d75ea148/pkg/server/serverpb/status.proto#L1324-L1338

Range Statistics:

https://github.com/cockroachdb/cockroach/blob/0f6333cbd6c78264a59dc435324c0c33d75ea148/pkg/server/serverpb/status.proto#L416-L399

Jira issue: CRDB-23496

### PR DESCRIPTION
**Pull request by kvoli**
This PR adds CPU as a hotranges v1 and range statistic field. Then the stats that are included in the v1 hot ranges (including cpu) but not v2 are added to the hot ranges v2 api.

```
WritesPerSecond
ReadsPerSecond
WriteBytesPerSecond
ReadBytesPerSecond
CPUTimePerSecond
```

See the associated comments in `status.proto` for a description of each
load statistic.

These may be used to determine the hottest ranges. Note however that
these are sorted by default by QPS. The ordering of ranges w.r.t the new
load statistics has no guarantees. Likewise, ranges may be omitted which
have high relative values for the new load statistics but relatively low
QPS. In practice however, there usually exists a strong correlation that
ensures that such ranges would not be omitted entirely.

resolves: https://github.com/cockroachdb/cockroach/issues/95383
resolves: https://github.com/cockroachdb/cockroach/issues/95384

Release note: None

### CODE REVIEW

**Review by koorosh — COMMENTED** [review]
LGTM  with only one minor suggestion.

> Reviewed 2 of 4 files at r1, 9 of 9 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95388#-:-NMZyN--7OEMmXMUxQr7:b5v251u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/server/serverpb/status.proto` line 1415 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95388#-NMZx4Ta8NuvyPJZPJ8a:-NMZx4Ta8NuvyPJZPJ8b:b-kef9pm) ([raw file](https://github.com/cockroachdb/cockroach/blob/718c70aea11834e560ae63a86001a424d417e37d/pkg/server/serverpb/status.proto#L1415)):*
> ```protobuf
>       (gogoproto.customname) = "QPS"
>     ];
>     // writes_per_second is the recent number of keys written per second on
> ```

nit. 11 is the next vacant field number available to use and suggesting to put fields in order.

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95388)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh)

___
*[`pkg/server/serverpb/status.proto` line 1415 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95388#-NMZx4Ta8NuvyPJZPJ8a:-NM_RDPACfRJaoHstWFl:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/718c70aea11834e560ae63a86001a424d417e37d/pkg/server/serverpb/status.proto#L1415)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

nit. 11 is the next vacant field number available to use and suggesting to put fields in order.
</blockquote></details>

Updated.

**Review by koorosh — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95388#-:-NMc7wEL7-9s1WMFM6UX:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

**Comment by kvoli** [comment]
TYFTR - merging in https://github.com/cockroachdb/cockroach/pull/95190

**Pull request closed without merging**
