### PR TITLE
Fix a tiny spelling mistake in proto/errors.proto

### PR DESCRIPTION
**Pull request by kkaneda**
s/represesentation/representation/

### CODE REVIEW

**Comment by spencerkimball** [comment]
LGTM

**Comment by tschottdorf** [comment]
you've got to `go generate ./...`, @kkaneda.

**Comment by kkaneda** [comment]
Ah, I see.. Updated.

**Comment by tschottdorf** [comment]
test failure is unrelated to your change. @MBerhault is currently taking a look. We'll ping you once it's done, and then you probably want to rebase.

**Comment by kkaneda** [comment]
Sure. Thanks, @tschottdorf !

**Comment by tschottdorf** [comment]
@kkaneda fire at will.

**Comment by kkaneda** [comment]
Thanks! Merging.

**Pull request merged**
