### PR TITLE
opt,sql: add sql.defaults.reorder_joins_limit

### PR DESCRIPTION
**Pull request by justinj**
A session variable is not really a great recourse to disable join
reordering if there's problems, since you'd need to make sure it got set
for every connection. This adds a cluster setting to disable it.

Release note (sql change): Added the sql.defaults.reorder_joins_limit
cluster setting which defines the default value of the
reorder_joins_limit session variable.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36268#-:-Lb3mlzj2sGTP9rOYCbq:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/exec_util.go, line 141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36268#-Lb3ltfn3pzECw8QnJSD:-Lb3ltfn3pzECw8QnJSE:bbie73k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae3203be93fe8754122f20ed937936bd3c67e521/pkg/sql/exec_util.go#L141)):*
> ```Go
> 	// NOTE: If this is changed, the value in the opt-tester must also be
> 	// changed.
> 	4,
> ```

[nit] maybe we can make this a constant in the `opt` package. It could be used for explain(opt,env) as well (my only concern there is overly advertising the variable by including it every time in the output).

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36268#-:-Lb3uokO0_nn7DDylfPW:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @justinj)

**Review by justinj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36268)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rytaft)

___
*[pkg/sql/exec_util.go, line 141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36268#-Lb3ltfn3pzECw8QnJSD:-Lb8ydGD5-PYsh6gZGmT:bhormoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae3203be93fe8754122f20ed937936bd3c67e521/pkg/sql/exec_util.go#L141)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] maybe we can make this a constant in the `opt` package. It could be used for explain(opt,env) as well (my only concern there is overly advertising the variable by including it every time in the output).
</blockquote></details>

Done, good idea. I added a `constants.go` which seems a bit special-case but I couldn't think of a better place to put it.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm: Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36268#-:-Lb93xB5BotTQ2ISg9_4:b-g2a5fb)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36268#-:-Lb98IYM9Q_6RfzKzESD:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj)

___
*[pkg/sql/opt/constants.go, line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36268#-Lb97ZTY6yHEHjAVTDff:-Lb97ZTY6yHEHjAVTDfg:bbd089z) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2ceb072fcee698d0470fe0c00e73aac5f8e0088/pkg/sql/opt/constants.go#L18)):*
> ```Go
> 
> // DefaultJoinOrderLimit denotes the default number of tables being joined to
> // reorder.
> ```

[nit] this comment is a bit awkward. Maybe "denotes the default limit on the number of joins to reorder"?

**Review by justinj — COMMENTED** [review]
thanks!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36268#-:-LbO8lfM4LYrTJU46ETb:b-hqrd7s)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/constants.go, line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36268#-Lb97ZTY6yHEHjAVTDff:-LbO8kx5Eq23BkVQewOZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2ceb072fcee698d0470fe0c00e73aac5f8e0088/pkg/sql/opt/constants.go#L18)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] this comment is a bit awkward. Maybe "denotes the default limit on the number of joins to reorder"?
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36268)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Pull request merged**
