### PR TITLE
kv: clarify the Sender contract and pre-allocate commit batches

### PR DESCRIPTION
**Pull request by andreimatei**
See individual commits.

Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
Tobi, putting this up on the flag pole to see if the cat licks it up.

cc @nvanbenschoten

**Review by tbg — COMMENTED** [review]
I'm with you in spirit, and I'm glad the time has come where such reuse is actually important for performance, but I'm afraid that turning it off and going wild-west on the whole thing is going to cost us dearly in obscure bugs. Let's figure out what the contracts should be (to make the optimizations most powerful) and then let's think about the best way to enforce them (I hope that in the process we can get rid of this transport, which is quite expensive and slows down race a bunch).

The race transport doesn't only exist because we might be manipulating data on the server (in the local case). It also exists because grpc might be reading the data even after the call came back (or so we assume). In the spirit of [there are no benign data races](https://software.intel.com/en-us/blogs/2013/01/06/benign-data-races-what-could-possibly-go-wrong), it follows that unless you can prove that what you gave to gRPC is no longer going to be accessed by it, you don't want to mutate it. I haven't looked at what grpc does with the passed-in message exactly. Ideally it would encode it before it does anything async and then we're home free and can forget about the race transport for that purpose.

Then what's left is finding better ways to enforce the guarantees we want in our code.

For example,

> Server side code is currently not allowed to mutate objects referenced by a Batch.

Can (mostly) be caught by hashing the batch on the way in and on the way out and comparing at the `(Node).Batch` endpoint (unless the requests gets passed elsewhere out-of-band, but that doesn't happen often and we can audit it). But I agree that we're probably fairly good here, though that too may change as we move objects between the heap and the stack (and so what was a shallow copy cedes to be one).

Ideally I think we get to a place where the incoming request (incl. the Txn proto) is treated immutable at the node (i.e. below DistSender) and where we feel comfortable that it's not passed around across goroutine boundaries anywhere in DistSender or above (and so can be pooled and reused aggressively).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30485#-:-LMvgRcmDgpCy9xxscP8:bh7n6p7)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
I looked into grpc... At first it looked pretty convincing that there no funny business and once the thing returns from an `Invoke()` call, there's no referencing a request in the background or anything. But then I realized that I was looking at an older version. In the current version it's a bit harder to assert anything; it's not the most traceable code. But I didn't see any clues that there might be monkey business, and thinking about it I'm confident enough that it's all fine - like, it order for it to not be fine, the code would really have to try explicitly to screw you.

I've added better comments as per our convo to the Sender iface. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30485#-:-LMxcSijEYfEJHbtUtOq:b-8lowh7)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by bdarnell — COMMENTED** [review]
I think it's reasonable to assume that grpc won't touch the input proto once the client method has returned. But I'm not sure about making that same assumption about DistSender. Couldn't tasks started by `sendPartialBatchAsync` still be running when `DistSender.Send` returns? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30485#-:-LNBZcpYDU6bVaK8VySf:b-w5iqij)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by bdarnell** [comment]
Errors from `combine` are rare to non-existent in practice, so it ought to be possible to eliminate that early return. I think this is probably a good direction to pursue, but the guarantees involved are pretty subtle. I'm worried that we could miss something here or re-introduce problems later.

**Comment by andreimatei** [comment]
I got rid of those combine errors.
I'd like to move forward with this change and the general push for batch reuse, but I won't backport.

**Review by nvb — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30485)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/internal/client/txn.go, line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30485#-LNFQp6j-c57X3Ub5gcf:-LNFQp6j-c57X3Ub5gcg:b-v7e2mu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5b3b2e87c24af40ec4202a13964b8ffa38bfe26/pkg/internal/client/txn.go#L41)):*
> ```Go
> 	typ TxnType
> 
> 	// alloc holds pre-allocated fields that can be used to avoid heap allocations
> ```

Nice! The only thing I'll point out is that this kind of optimization is even more impactful when we start pooling the `Txn` object itself. Let's leave a TODO to do that, along with the TxnCoordSender. They're both huge objects that would benefit a lot from being pooled. Pooling them would also force us to clean up their lifetimes, which is a good idea on its own.
___
*[pkg/internal/client/txn.go, line 44 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30485#-LNFQgL5BC7gUvJG8Bs2:-LNFQgL5BC7gUvJG8Bs3:b5ftwwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5b3b2e87c24af40ec4202a13964b8ffa38bfe26/pkg/internal/client/txn.go#L44)):*
> ```Go
> 	// for batches with lifetimes tied to a Txn.
> 	alloc struct {
> 		requests [4]roachpb.RequestUnion
> ```

We're only ever using a single element out of this, so let's give this a length of 1.
___
*[pkg/roachpb/api.go, line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30485#-LNFQL7P5jEtZxYoI0Xk:-LNFQL7P5jEtZxYoI0Xl:bu5czx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c567cadb0276329103afe4ec0a663b9925b4b0d/pkg/roachpb/api.go#L246)):*
> ```Go
> 	}
> 	if rh.ResumeSpan != nil {
> 		log.Fatalf(ctx, "combining %+v with %+v", rh.ResumeSpan, otherRH.ResumeSpan)
> ```

I don't know about this. We shouldn't fatal if we get something we don't like back from a different node in the cluster. Why don't we just change the defer in `divideAndSendBatchToRange` to treat the error like any other error? It can return it later without immediately breaking from the loop.

**Review by bdarnell — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30485)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/roachpb/api.go, line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30485#-LNFQL7P5jEtZxYoI0Xk:-LNGimcv7gQ5cUV4LSuW:bs6mq8f) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c567cadb0276329103afe4ec0a663b9925b4b0d/pkg/roachpb/api.go#L246)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I don't know about this. We shouldn't fatal if we get something we don't like back from a different node in the cluster. Why don't we just change the defer in `divideAndSendBatchToRange` to treat the error like any other error? It can return it later without immediately breaking from the loop.
</blockquote></details>

I agree. Changing a panic to a fatal here doesn't hurt anything, but it's moving in the wrong direction to force us to fatal instead of returning an error. It would be better to keep the error return from `combine()` and just delay the return until everything is done.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30485)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/roachpb/api.go, line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30485#-LNFQL7P5jEtZxYoI0Xk:-LNGp9LfAHMVdkXPWeRX:bkhhsai) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c567cadb0276329103afe4ec0a663b9925b4b0d/pkg/roachpb/api.go#L246)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I agree. Changing a panic to a fatal here doesn't hurt anything, but it's moving in the wrong direction to force us to fatal instead of returning an error. It would be better to keep the error return from `combine()` and just delay the return until everything is done.
</blockquote></details>

Before I change everything back, I'd like to litigate this more.
Ben, the position you've expressed when we were talking before seems inconsistent to me: you said you're fine with assertions about the behavior of a single process, but not so much about what is received from a different node. And you said that this policy preference is not necessarily related to different node version mismatches. But generally it seems to me like the only sane thing to do is have the same policy across nodes that we have within a single process. Like, we make a million assumptions about what another node will return; we can't accept any arbitrary data and trying to tolerate programming errors on another node that we don't tolerate locally... I don't see why we'd do that. If a remote node says this is the data at this key, we take it at face value. We don't assert that it returned data from the key we requested, and such.
What gives?

**Comment by bdarnell** [comment]
I'm just coming from the general principle that any crash that can be triggered by data received over the network is a bug (not necessarily a high-priority bug, but a bug nonetheless). If the existing code didn't have an `error` return I wouldn't be advocating for adding one at this point, but since it's there removing it seems like a step in the wrong direction. 

I think it's worth a little extra effort to keep the error return from `combine()` and modify the loop to wait for all results regardless of error. But it's not worth a *lot* of extra effort. I was also mainly reacting to Nathan's comment without looking too closely at the particular panic here. If combining ResumeSpans and Errors are the only way `combine` can fail, then I'm not too worried about the panics.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30485)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/roachpb/api.go, line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30485#-LNFQL7P5jEtZxYoI0Xk:-LNHDkl6EkGpP9C22HHt:b-x3yg1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c567cadb0276329103afe4ec0a663b9925b4b0d/pkg/roachpb/api.go#L246)):*
Pasting Ben's response here:
> I'm just coming from the general principle that any crash that can be triggered by data received over the network is a bug (not necessarily a high-priority bug, but a bug nonetheless). If the existing code didn't have an error return I wouldn't be advocating for adding one at this point, but since it's there removing it seems like a step in the wrong direction.
>
> I think it's worth a little extra effort to keep the error return from combine() and modify the loop to wait for all results regardless of error. But it's not worth a lot of extra effort. I was also mainly reacting to Nathan's comment without looking too closely at the particular panic here. If combining ResumeSpans and Errors are the only way combine can fail, then I'm not too worried about the panics.

Thanks. I'd still be inclined to debate what exactly you're thinking when you say "crash that can be triggered by data received over the network is a bug" - like, if we try to read the value of a sequence and we get back a string, would it be a "bug" if we crashed? Or an inconsistent lease? I don't think you want to argue that, so you probably want to refine your statement to only refer to some response "metadata". But even then, do you think that a more precise description of what you want to express can be phrased, and still be general enough that I can tattoo it on my chest?

We don't need to have a general discussion if you don't want to; we can discuss this specific.
- combining  something with a `ResumeSpan` was a panic; now it's a fatal. I think this indicates a situation where the gateway split a batch that it shouldn't have.
- combining a response that had an error was an error. Now it's a Fatal. This indicates a bug in the DistSender's logic that's supposed to strip these errors before combining anything.
- combining two "non-combinable" was an error. The patch makes it a fatal. "Non-combinable" means we were trying to combine a, say, `ScanResponse` with a `PutResponse`. Even before the patch, trying to combine a `ScanResponse` with a `DelRangeResponse` (where they're both "combinable") would be crash. This indicates a bug in how the gateway calculates the positions of the responses it combines or, I guess, a server-side bug where we rearrange the responses to individual constituents of a batch.

So, given these specific changes, do you object to the two new fatals introduced?

**Comment by bdarnell** [comment]
> if we try to read the value of a sequence and we get back a string, would it be a "bug" if we crashed? Or an inconsistent lease? I don't think you want to argue that, so you probably want to refine your statement to only refer to some response "metadata".

I do want to argue that. We should strive to return an error instead of panicking for things like this. Data-dependent crashes are nearly always bugs (sometimes, like at startup, it really doesn't make sense to continue if we can't read what's on the disk, but ideally even that would be handled by returning an error up the stack). 

> So, given these specific changes, do you object to the two new fatals introduced?

Not enough to keep arguing about it.

**Comment by nvanbenschoten** [comment]
+1 to @bdarnell's stance here. My general rule of thumb is that errors that can be scoped to a single request should be.

**Review by andreimatei — COMMENTED** [review]
I've reintroduced the combine errors (and converted the panic we had to an error too).
PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30485#-:-LNLcQdE46lHZ9BGSkVc:b-vb9joz)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/internal/client/txn.go, line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30485#-LNFQp6j-c57X3Ub5gcf:-LNLc8GlBwdlb9qG4UsF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5b3b2e87c24af40ec4202a13964b8ffa38bfe26/pkg/internal/client/txn.go#L41)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Nice! The only thing I'll point out is that this kind of optimization is even more impactful when we start pooling the `Txn` object itself. Let's leave a TODO to do that, along with the TxnCoordSender. They're both huge objects that would benefit a lot from being pooled. Pooling them would also force us to clean up their lifetimes, which is a good idea on its own.
</blockquote></details>

Done.
___
*[pkg/internal/client/txn.go, line 44 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30485#-LNFQgL5BC7gUvJG8Bs2:-LNLbcZK5Qz-xLvoiRE5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5b3b2e87c24af40ec4202a13964b8ffa38bfe26/pkg/internal/client/txn.go#L44)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We're only ever using a single element out of this, so let's give this a length of 1.
</blockquote></details>

Done.
___
*[pkg/roachpb/api.go, line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30485#-LNFQL7P5jEtZxYoI0Xk:-LNLcLvHCbidgCGmOXRy:byjchat) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c567cadb0276329103afe4ec0a663b9925b4b0d/pkg/roachpb/api.go#L246)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Pasting Ben's response here:
> I'm just coming from the general principle that any crash that can be triggered by data received over the network is a bug (not necessarily a high-priority bug, but a bug nonetheless). If the existing code didn't have an error return I wouldn't be advocating for adding one at this point, but since it's there removing it seems like a step in the wrong direction.
>
> I think it's worth a little extra effort to keep the error return from combine() and modify the loop to wait for all results regardless of error. But it's not worth a lot of extra effort. I was also mainly reacting to Nathan's comment without looking too closely at the particular panic here. If combining ResumeSpans and Errors are the only way combine can fail, then I'm not too worried about the panics.

Thanks. I'd still be inclined to debate what exactly you're thinking when you say "crash that can be triggered by data received over the network is a bug" - like, if we try to read the value of a sequence and we get back a string, would it be a "bug" if we crashed? Or an inconsistent lease? I don't think you want to argue that, so you probably want to refine your statement to only refer to some response "metadata". But even then, do you think that a more precise description of what you want to express can be phrased, and still be general enough that I can tattoo it on my chest?

We don't need to have a general discussion if you don't want to; we can discuss this specific.
- combining  something with a `ResumeSpan` was a panic; now it's a fatal. I think this indicates a situation where the gateway split a batch that it shouldn't have.
- combining a response that had an error was an error. Now it's a Fatal. This indicates a bug in the DistSender's logic that's supposed to strip these errors before combining anything.
- combining two "non-combinable" was an error. The patch makes it a fatal. "Non-combinable" means we were trying to combine a, say, `ScanResponse` with a `PutResponse`. Even before the patch, trying to combine a `ScanResponse` with a `DelRangeResponse` (where they're both "combinable") would be crash. This indicates a bug in how the gateway calculates the positions of the responses it combines or, I guess, a server-side bug where we rearrange the responses to individual constituents of a batch.

So, given these specific changes, do you object to the two new fatals introduced?
</blockquote></details>

This conversation had moved to the top level PR comments.

**Review by bdarnell — APPROVED** [review]
> Reviewed 2 of 8 files at r4, 3 of 3 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30485)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by nvb — APPROVED** [review]
:lgtm_strong: 

> Reviewed 8 of 8 files at r4, 2 of 3 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30485#-:-LNO2yh96TkzaAZJLxqQ:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
TFTRs

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30485#-:-LNRi3KD6ObP-dAqvyeM:b-6rbzir)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
