### PR TITLE
release-23.2: telemetry: log transaction exec events to TELEMETRY

### PR DESCRIPTION
**Pull request by xinhaoz**
Backport:
  * 1/1 commits from "util/log: allow bool fields to be emitted as false in json format" (#113757)
  * 1/1 commits from "log: add protobuf messages for telemetry txn events" (#113952)
  * 2/2 commits from "sql/telemetry: give more descriptive names for statement logging and use atomic counter types where appropriate" (#114099)
  * 1/1 commits from "telemetry: track telemetry transactions through conn executor" (#115733)
  * 4/4 commits from "telemetry: log transaction exec events to TELEMETRY" (#115722)

Please see individual PRs for details.

/cc @cockroachdb/release

Release justification: high priority need for this change

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
nice work! lgtm overall, but i had some comments. none of them are show-stoppers, so maybe the best thing to do is merge this, then address my comments on the master branch, and backport that as well?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118432#-:-NqDiq_K68WYlpL835ZE:b96ppl8)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @maryliag, and @xinhaoz)

___
*[`-- commits` line 150 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/118432#-NqDg5Yy8Q2hYjrg4XcI):*
should logging changes be a "sql" release note. would `general change` or `ops change` make more sense? https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/186548364/Release+notes#Categories
___
*[`pkg/sql/conn_executor.go` line 2027 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/118432#-NqDd7ibE7GmP6IKLb_n:-NqDd7ic1T6F5SKg2Ru0:b2ey84d) ([raw file](https://github.com/cockroachdb/cockroach/blob/c26ca44f0ad6b1ae19d19daf9660c866ab5f1d25/pkg/sql/conn_executor.go#L2027)):*
> ```Go
> 		ex.state.mu.stmtCount = 0
> 		tracingEnabled := ex.planner.ExtendedEvalContext().Tracing.Enabled()
> 		ex.extraTxnState.shouldLogToTelemetry =
> ```

nit: updating the shouldLogToTelemetry field would make sense to do inside of `onTxnRestart`

but also, i'm not sure if it makes sense to change the value of shouldLogToTelemetry during a txn restart. wouldn't it be confusing to see that a transaction failed, when in fact, it succeeded after a transaction restart? similarly, wouldn't it be confusing to only see the retry, but not know how much time was spent executing before the retry?
___
*[`pkg/sql/conn_executor_exec.go` line 3165 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/118432#-NqDe-spAEvPzcjWwJtk:-NqDe-sq4zSrw79JpuyL:boiu8ab) ([raw file](https://github.com/cockroachdb/cockroach/blob/c26ca44f0ad6b1ae19d19daf9660c866ab5f1d25/pkg/sql/conn_executor_exec.go#L3165)):*
> ```Go
> 
> 	tracingEnabled := ex.planner.ExtendedEvalContext().Tracing.Enabled()
> 	ex.extraTxnState.shouldLogToTelemetry =
> ```

super nit: might be easier to read if this was done lower done, closer to the other code that updates fields in extraTxnState
___
*[`pkg/sql/exec_log.go` line 117 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/118432#-NqDe7XS-1ZjSQH-ApMp:-NqDe7XS-1ZjSQH-ApMq:b-aegyih) ([raw file](https://github.com/cockroachdb/cockroach/blob/c26ca44f0ad6b1ae19d19daf9660c866ab5f1d25/pkg/sql/exec_log.go#L117)):*
> ```Go
> func shouldForceLogStatement(ast tree.Statement) bool {
> 	switch ast.StatementTag() {
> 	case "BEGIN", "COMMIT":
> ```

nit: you don't need to look at the statement tag, since BEGIN and COMMIT have type `TypeTCL` (transaction control language).

also, i think ROLLBACK should be logged as well (it's also of type TCL, but the way the code is written now, makes it seem like we don't care about ROLLBACK for some reason).

so it's probably better to just simplify the whole function to `return ast.StatementType() != tree.TypeDML`
___
*[`pkg/sql/exec_log.go` line 300 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/118432#-NqDfBUb0hAsMX72YWip:-NqDfBUb0hAsMX72YWiq:b-d47vb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c26ca44f0ad6b1ae19d19daf9660c866ab5f1d25/pkg/sql/exec_log.go#L300)):*
> ```Go
> 
> 		// Always sample if one of the scenarios is true:
> 		// - statement is not of type DML and is not BEGIN or COMMIT
> ```

nit: as per the last comment, this could just say "statement is not of type DML"
___
*[`pkg/util/log/eventpb/eventpbgen/gen.go` line 499 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/118432#-NqDgc-QEGf9rX1I6rMT:-NqDgc-QEGf9rX1I6rMU:b-5sti7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/e62bc46733ca0553b4b265863c53417761e9e219/pkg/util/log/eventpb/eventpbgen/gen.go#L499)):*
> ```Go
> var reservedDefRe = regexp.MustCompile(`\s*(reserved ([1-9][0-9]*);)`)
> 
> var notNullableRe = regexp.MustCompile(`\s*\(\s*gogoproto\.nullable\s*\)\s*=\s*false`)
> ```

i think it would be more intuitive if the attribute name was also `notnullable`. otherwise, we have slightly confusing behavior where `nullable` defaults to true, which is not the norm for boolean values.

similarly, i think we should make the field in `fieldInfo` be named `NotNullable`. (btw, this is also what we do in SQL land, for marking not-nullable columns)
___
*[`pkg/sql/telemetry_datadriven_test.go` line 56 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/118432#-NqDfnTE2EodxQLUrQD2:-NqDfnTE2EodxQLUrQD3:bqr2hr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c26ca44f0ad6b1ae19d19daf9660c866ab5f1d25/pkg/sql/telemetry_datadriven_test.go#L56)):*
> ```Go
>  * reset-last-sampled: resets the last sampled time.
>  */
> func TestTelemetryLoggingDataDriven(t *testing.T) {
> ```

this is a great testing framework, nice work!

**Comment by xinhaoz** [comment]
@rafiss Ack. re; connexec changes! I think it makes sense to go through with the process you mentioned on making the changes via master first and backporting that.

**Comment by xinhaoz** [comment]
*[`pkg/sql/exec_log.go` line 117 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/118432#-NqDe7XS-1ZjSQH-ApMp:-NqEOB0Y94L1LndfG2qg:b1y9ub) ([raw file](https://github.com/cockroachdb/cockroach/blob/c26ca44f0ad6b1ae19d19daf9660c866ab5f1d25/pkg/sql/exec_log.go#L117)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: you don't need to look at the statement tag, since BEGIN and COMMIT have type `TypeTCL` (transaction control language).

also, i think ROLLBACK should be logged as well (it's also of type TCL, but the way the code is written now, makes it seem like we don't care about ROLLBACK for some reason).

so it's probably better to just simplify the whole function to `return ast.StatementType() != tree.TypeDML`
</blockquote></details>

Are you saying we do want to always log all BEGIN and COMMIT statements? Currently we're excluding them from being force logged to reduce noise, but I can remove this exclusion if it makes sense to always log BEGIN/COMMIT even if DML statements are being sampled. ROLLBACK is indeed being force logged right now.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118432)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @maryliag, and @xinhaoz)

___
*[`pkg/sql/exec_log.go` line 117 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/118432#-NqDe7XS-1ZjSQH-ApMp:-NqEREdp8H5wuF5G1vIT:b-jpuime) ([raw file](https://github.com/cockroachdb/cockroach/blob/c26ca44f0ad6b1ae19d19daf9660c866ab5f1d25/pkg/sql/exec_log.go#L117)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Are you saying we do want to always log all BEGIN and COMMIT statements? Currently we're excluding them from being force logged to reduce noise, but I can remove this exclusion if it makes sense to always log BEGIN/COMMIT even if DML statements are being sampled. ROLLBACK is indeed being force logged right now.
</blockquote></details>

oh my bad, i thought this returned `true` for BEGIN/COMMIT

this is fine then, assuming the UX makes it clear that the DML is from a transaction, so there's no need to show begin/commit.

though to be more idiomatic with other code, i would change this to:
```
switch ast.(type) {  
case *tree.BeginTransaction, *tree.CommitTransaction:
  // ...
default:
  // ...
}
```

**Review by dhartunian — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118432#-:-NqTgWEUEGk-WpVtq-EF:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rafiss and @xinhaoz)

**Pull request merged**
