### PR TITLE
cli: added --locality

### PR DESCRIPTION
**Pull request by d4l3k**
Builds on #8627

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8676)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm: (looked at the third commit only)

---

Review status: 0 of 38 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[roachpb/metadata.go, line 233 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8676#-KPUsSl03Lm1p6cRculO:-KPUsSl1zqesS5wkBaoc:bm7z7c9) ([raw file](https://github.com/cockroachdb/cockroach/blob/037d5a0ee1230a7d1f35098aa86286a021b0fdc0/roachpb/metadata.go#L233)):*
> ```Go
> // Type returns the underlying type in string form. This is part of pflag's
> // value interface.
> func (l Locality) Type() string {
> ```

_ Locality

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8676#-:-KPUsgu68_T2h6YOWQlm:b-5gpwjk)*

**Comment by d4l3k** [comment]
Review status: 0 of 38 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[roachpb/metadata.go, line 233 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8676#-KPUsSl03Lm1p6cRculO:-KPnvUEIidGDJUW4N10s:b-fgtxqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/037d5a0ee1230a7d1f35098aa86286a021b0fdc0/roachpb/metadata.go#L233)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> _ Locality
</details>
golint
```
roachpb/metadata.go:233:1: receiver name should not be an underscore
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8676)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 38 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[roachpb/metadata.go, line 233 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8676#-KPUsSl03Lm1p6cRculO:-KPnvs4YL9zyMkV6nh2M:bahesr5) ([raw file](https://github.com/cockroachdb/cockroach/blob/037d5a0ee1230a7d1f35098aa86286a021b0fdc0/roachpb/metadata.go#L233)):*
<details><summary><i>Previously, d4l3k (Tristan Rice) wrote…</i></summary>
> golint
> ```
> roachpb/metadata.go:233:1: receiver name should not be an underscore
> ```
</details>
Ah, my bad

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8676)*

**Comment by tamird** [comment]
Review status: 0 of 38 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[roachpb/metadata.go, line 233 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8676#-KPUsSl03Lm1p6cRculO:-KPo8t_IsTpPe7rTvXPI:b-lb27ys) ([raw file](https://github.com/cockroachdb/cockroach/blob/037d5a0ee1230a7d1f35098aa86286a021b0fdc0/roachpb/metadata.go#L233)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Ah, my bad
</details>
It can be `func (Locality) Type() String`, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8676)*

**Comment by d4l3k** [comment]
Review status: 0 of 38 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[roachpb/metadata.go, line 233 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8676#-KPUsSl03Lm1p6cRculO:-KPoBW3RFYTkVN_R9BY-:b4vrnvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/037d5a0ee1230a7d1f35098aa86286a021b0fdc0/roachpb/metadata.go#L233)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> It can be `func (Locality) Type() String`, though.
</details>
Didn't realize that. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8676)*

**Comment by d4l3k** [comment]
@RaduBerinde @bdarnell Thoughts on whether I should wait to merge this until the allocator actually takes locality into account?

**Comment by bdarnell** [comment]
:lgtm:

It's fine to merge this before it is actually used.

---

Review status: 0 of 40 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cli/cliflags/flags.go, line 56 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8676#-KQ8KHQ26gOczE06xmZ4:-KQ8KHQ26gOczE06xmZ5:bjf5chv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac5effac4a4734c8b76888b325a06d8b25287ee1/cli/cliflags/flags.go#L56)):*
> ```Go
> 		Name: "locality",
> 		Description: `
> An ordered, comma-separated list of key-value pairs that describe the topography
> ```

This help text should say that this is not yet fully implemented.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8676#-:-KQ8KtQGUFBs9fyYxp_z:b9i4xt7)*

**Comment by d4l3k** [comment]
Review status: 0 of 40 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[cli/cliflags/flags.go, line 56 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8676#-KQ8KHQ26gOczE06xmZ4:-KQMHfYxFmO2R7YW1_om:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac5effac4a4734c8b76888b325a06d8b25287ee1/cli/cliflags/flags.go#L56)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> This help text should say that this is not yet fully implemented.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8676)*

**Comment by knz** [comment]
Seems ok to merge right?

**Comment by d4l3k** [comment]
It's being blocked on @BramGruneir's comments on #8786.

**Comment by BramGruneir** [comment]
Which comments are you waiting on?  I just did another pass of it.

**Comment by d4l3k** [comment]
```
Bram Gruneir
Please add a number of other examples!

Tristan Rice
This info will be folded into the https://www.cockroachlabs.com/docs/configure-replication-zones.html docs. As far as I can tell, none of the other cliflags have redundant examples.

Bram Gruneir
store has a large number of examples, but we should ask @jseldess what he thinks.
```

**Comment by BramGruneir** [comment]
Ah, I say just merge it for now.  We can always add more examples.

**Comment by d4l3k** [comment]
Just added some extra examples and added a link to the tracking issue.

**Comment by BramGruneir** [comment]
That part of this change LGTM.  Manitoba FTW.

---

Review status: 0 of 18 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8676#-:-KQRkw-8zeR2-7UfeJd2:bnjphb4)*

**Pull request merged**
