### PR TITLE
sql: Add more efficient implementation of min, max, sum, avg aggregates when used as window functions.

### PR DESCRIPTION
**Pull request by yuzefovich**
Adds linear-time implementations of min, max, sum, and avg
(using sliding window approach) instead of naive quadratic
version.

Addresses: #26464.

Bonus: min and max is order of magnitude faster that PG
(when window frame doesn't include the whole partition).

Release note (performance improvement): min, max, sum, avg
now take linear time when used for aggregation as window
functions.

### CODE REVIEW

**Comment by yuzefovich** [comment]
@solongordon take a look if you're interested in what I've been working on :)

**Comment by nvanbenschoten** [comment]
Reviewed 2 of 4 files at r1.
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/window.go, line 772 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LGO853n9dWmicQpr3nc:-LGO853n9dWmicQpr3nd:b-pks9lh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2c99f2f0a581f5237ff8a4850784899e4832042/pkg/sql/window.go#L772)):*
> ```Go
> 			frameRun.RowIdx = 0
> 
> 			if frameRun.Frame != nil {
> ```

Per my comment below, I think we should explore whether this entire block can be removed.

---

*[pkg/sql/sem/builtins/window_frame_builtins.go, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LGO3dUZ6H3X1GC2Ohax:-LGO3dUZ6H3X1GC2Ohay:bqx2uua) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2c99f2f0a581f5237ff8a4850784899e4832042/pkg/sql/sem/builtins/window_frame_builtins.go#L18)):*
> ```Go
> 
> import (
> 	"context"
> ```

The spacing on these imports got a little messed up.

---

*[pkg/sql/sem/builtins/window_frame_builtins.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LGO3seK4nrhpqFxP7eu:-LGO3seK4nrhpqFxP7ev:bz9b1q6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2c99f2f0a581f5237ff8a4850784899e4832042/pkg/sql/sem/builtins/window_frame_builtins.go#L33)):*
> ```Go
> 	windowFunc tree.WindowFunc, evalCtx *tree.EvalContext, wfr *tree.WindowFrameRun,
> ) tree.WindowFunc {
> 	if framableAgg, ok := windowFunc.(*framableAggregateWindowFunc); ok {
> ```

Is there a reason to ever not replace the `framableAggregateWindowFunc` with the faster version? If not, why not do that statically and always give these optimized window functions `slidingWindowFunc` implementations in the `tree.Overload` itself?

On that note, I've gotten a little confused by `AddAggregateConstructorToFramableAggregate` upon re-reading it. Why don't we give the aggregate constructor to the `framableAggregateWindowFunc` when we build the `tree.Overload` in `makeAggOverloadWithReturnType`? It seems like all of this could be done statically.

---

*[pkg/sql/sem/builtins/window_frame_builtins.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LGO6xAk9DH7GWiU3MSd:-LGO6xAk9DH7GWiU3MSe:b-tyh7vg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2c99f2f0a581f5237ff8a4850784899e4832042/pkg/sql/sem/builtins/window_frame_builtins.go#L39)):*
> ```Go
> 			min := &slidingWindowFunc{}
> 			min.sw = &slidingWindow{
> 				values: make([]indexedValue, 0, wfr.PartitionSize()),
> ```

It would be nice if we only had to use `O(max window size)`  instead of `O(partition size)` space. Should be doable by turning the window into a dynamically sized ring buffer. I'd still make sure to keep it as a contiguous chunk of memory though.

---

*[pkg/sql/sem/builtins/window_frame_builtins.go, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LGO7UQW9ElzL0xyM0rp:-LGO7UQX7aRVsZCAhHa6:b-lq2kgv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2c99f2f0a581f5237ff8a4850784899e4832042/pkg/sql/sem/builtins/window_frame_builtins.go#L115)):*
> ```Go
> 
> func (sw *slidingWindow) string() string {
> 	var buf bytes.Buffer
> ```

Use a `strings.Builder`. Will save an extra alloc.

---

*[pkg/sql/sem/builtins/window_frame_builtins_test.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LGO8-C82dmspCWEdytE:-LGO8-CADBrSpI6pLKjY:b-obwm8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2c99f2f0a581f5237ff8a4850784899e4832042/pkg/sql/sem/builtins/window_frame_builtins_test.go#L35)):*
> ```Go
> const maxOffset = 100
> 
> func testSlidingWindow(t *testing.T, count int) {
> ```

Nice testing!

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26988)*

**Comment by yuzefovich** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/window.go, line 772 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LGO853n9dWmicQpr3nc:-LGVzwtU3SsHC6zG1zei:b-pjwtyj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2c99f2f0a581f5237ff8a4850784899e4832042/pkg/sql/window.go#L772)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Per my comment below, I think we should explore whether this entire block can be removed.
</blockquote></details>

I added a field which indicated whether resetting behavior is required. Without it, `framableAggregateWindowFunc` would always reset the aggregate, even when it is not necessary which would result in quadratic performance for aggregates (that don't have a sliding window implementation) when default frame is being used. Please let me know if you see a better way.

---

*[pkg/sql/sem/builtins/window_frame_builtins.go, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LGO3dUZ6H3X1GC2Ohax:-LGQ2I8U-Uep1FjHS_yQ:b-m16fak) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2c99f2f0a581f5237ff8a4850784899e4832042/pkg/sql/sem/builtins/window_frame_builtins.go#L18)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The spacing on these imports got a little messed up.
</blockquote></details>

Nice catch, thanks.

---

*[pkg/sql/sem/builtins/window_frame_builtins.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LGO3seK4nrhpqFxP7eu:-LGW-X4j5xE2dTA119-i:b2bz0sj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2c99f2f0a581f5237ff8a4850784899e4832042/pkg/sql/sem/builtins/window_frame_builtins.go#L33)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is there a reason to ever not replace the `framableAggregateWindowFunc` with the faster version? If not, why not do that statically and always give these optimized window functions `slidingWindowFunc` implementations in the `tree.Overload` itself?

On that note, I've gotten a little confused by `AddAggregateConstructorToFramableAggregate` upon re-reading it. Why don't we give the aggregate constructor to the `framableAggregateWindowFunc` when we build the `tree.Overload` in `makeAggOverloadWithReturnType`? It seems like all of this could be done statically.
</blockquote></details>

I think these were great suggestions, and thanks for the clarifications.

---

*[pkg/sql/sem/builtins/window_frame_builtins.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LGO6xAk9DH7GWiU3MSd:-LGW-hjVDHIFTrgOU6Cu:b-uiwv5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2c99f2f0a581f5237ff8a4850784899e4832042/pkg/sql/sem/builtins/window_frame_builtins.go#L39)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

That will also allow you to remove `WindowFrameRun` from this function, which further indicates to me that all of this can be done statically.
</blockquote></details>

Another great idea, thanks! Not sure what the appropriate initial buffer size should be.

---

*[pkg/sql/sem/builtins/window_frame_builtins.go, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LGO7UQW9ElzL0xyM0rp:-LGQ0lzA3d_56XW5yXiq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2c99f2f0a581f5237ff8a4850784899e4832042/pkg/sql/sem/builtins/window_frame_builtins.go#L115)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Use a `strings.Builder`. Will save an extra alloc.
</blockquote></details>

Done.

---

*[pkg/sql/sem/builtins/window_frame_builtins_test.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LGO8-C82dmspCWEdytE:-LGVKnEgCjCPmmfJEh4d:bvtk9y9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2c99f2f0a581f5237ff8a4850784899e4832042/pkg/sql/sem/builtins/window_frame_builtins_test.go#L35)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Nice testing!
</blockquote></details>

Thanks :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26988)*

**Review by nvb — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26988)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/window.go, line 772 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LGO853n9dWmicQpr3nc:-LH-GXAUA2MmBHtH13_v:b-biq2w9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2c99f2f0a581f5237ff8a4850784899e4832042/pkg/sql/window.go#L772)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I added a field which indicated whether resetting behavior is required. Without it, `framableAggregateWindowFunc` would always reset the aggregate, even when it is not necessary which would result in quadratic performance for aggregates (that don't have a sliding window implementation) when default frame is being used. Please let me know if you see a better way.
</blockquote></details>

This is much better. I'd just make it clear in this comment that not resetting is an optimization.
___
*[pkg/sql/sem/builtins/window_frame_builtins.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LH-FDht0NdI_NlF48uZ:-LH-FDht0NdI_NlF48u_:b-5upgvv) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0ef4d61e4a1300e705b3c5395bc72dfc2e2e534/pkg/sql/sem/builtins/window_frame_builtins.go#L35)):*
> ```Go
> 
> // ringBuffer is a deque of indexedValue's maintained over a ring buffer.
> type ringBuffer struct {
> ```

It's probably worth adding some tests for this type itself.
___
*[pkg/sql/sem/builtins/window_frame_builtins.go, line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LH-DjCX01G8KRVcYBCU:-LH-DjCX01G8KRVcYBCV:b-s5wugj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0ef4d61e4a1300e705b3c5395bc72dfc2e2e534/pkg/sql/sem/builtins/window_frame_builtins.go#L40)):*
> ```Go
> 	tail   int // the index of the first position right after the end of the deque.
> 
> 	empty bool // indicates whether the deque is empty, necessary to distinguish
> ```

Make this a useful empty value by
1. inverting this flag
2. handling `cap(r.values) == 0` in `ringBuffer.add` and having some minimum allocation size. `8` sounds good.

Useful empty values are a general idiom in Go that end up making code a lot nicer. You then don't need to initialize this at all in `makeSlidingWindow`.
___
*[pkg/sql/sem/builtins/window_frame_builtins.go, line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LH-DSX66hP_wqmMTqug:-LH-DSX66hP_wqmMTquh:bw58115) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0ef4d61e4a1300e705b3c5395bc72dfc2e2e534/pkg/sql/sem/builtins/window_frame_builtins.go#L63)):*
> ```Go
> 	if r.len() == cap(r.values) {
> 		newValues := make([]*indexedValue, 2*cap(r.values))
> 		for pos := 0; pos < cap(r.values); pos++ {
> ```

Can we use two calls to `copy` here? That would be faster because it could use a memcpy directly.
___
*[pkg/sql/sem/builtins/window_frame_builtins.go, line 144 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LH-HKnd97QNMRb0EtKK:-LH-HKnd97QNMRb0EtKL:b-bpjbgw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0ef4d61e4a1300e705b3c5395bc72dfc2e2e534/pkg/sql/sem/builtins/window_frame_builtins.go#L144)):*
> ```Go
> func (sw *slidingWindow) add(iv *indexedValue) {
> 	var newEndIdx int
> 	for newEndIdx = sw.values.len() - 1; newEndIdx >= 0; newEndIdx-- {
> ```

nit: Delete `newEndIdx` and replace it with `i`, which is scoped only to this loop.

`for i := sw.values.len() - 1; ...`
___
*[pkg/sql/sem/builtins/window_frame_builtins.go, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LH-HaQc3AfBYIVWJAh-:-LH-HaQc3AfBYIVWJAh0:bk3mh7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0ef4d61e4a1300e705b3c5395bc72dfc2e2e534/pkg/sql/sem/builtins/window_frame_builtins.go#L158)):*
> ```Go
> func (sw *slidingWindow) removeAllBefore(idx int) {
> 	var newStartIdx int
> 	for newStartIdx = 0; newStartIdx < sw.values.len() && newStartIdx < idx; newStartIdx++ {
> ```

Same thing here. No need for `newStartIdx` to be scoped outside of this loop. Once it's a loop index variable, might as well call it `i` to avoid noise.
___
*[pkg/sql/sem/builtins/window_frame_builtins.go, line 194 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LH-FOeg2FC7V0kbe2td:-LH-FOeg2FC7V0kbe2te:b-20ev7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0ef4d61e4a1300e705b3c5395bc72dfc2e2e534/pkg/sql/sem/builtins/window_frame_builtins.go#L194)):*
> ```Go
> 	w.prevEnd = end
> 
> 	if w.sw.values.empty {
> ```

`.len() == 0`. Don't break the abstraction you fought so hard for!
___
*[pkg/sql/sem/builtins/window_frame_builtins.go, line 239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LH-HACR8A5ml4Y5bPiD:-LH-HACR8A5ml4Y5bPiE:b-cjxoni) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0ef4d61e4a1300e705b3c5395bc72dfc2e2e534/pkg/sql/sem/builtins/window_frame_builtins.go#L239)):*
> ```Go
> 			return w.agg.Add(ctx, tree.NewDFloat(-*v))
> 		case *tree.DInterval:
> 			return w.agg.Add(ctx, &tree.DInterval{Duration: duration.Duration{}.Sub(v.Duration)})
> ```

`-v.Duration` doesn't work?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26988)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/window.go, line 772 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LGO853n9dWmicQpr3nc:-LH-kPDCDiK3KTczWfeP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2c99f2f0a581f5237ff8a4850784899e4832042/pkg/sql/window.go#L772)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is much better. I'd just make it clear in this comment that not resetting is an optimization.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/window_frame_builtins.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LH-FDht0NdI_NlF48uZ:-LH0VMyFATHV2mAYAAB7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0ef4d61e4a1300e705b3c5395bc72dfc2e2e534/pkg/sql/sem/builtins/window_frame_builtins.go#L35)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's probably worth adding some tests for this type itself.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/window_frame_builtins.go, line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LH-DjCX01G8KRVcYBCU:-LH-uS_O64nhlqSeNJNk:bqwb4ka) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0ef4d61e4a1300e705b3c5395bc72dfc2e2e534/pkg/sql/sem/builtins/window_frame_builtins.go#L40)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Make this a useful empty value by
1. inverting this flag
2. handling `cap(r.values) == 0` in `ringBuffer.add` and having some minimum allocation size. `8` sounds good.

Useful empty values are a general idiom in Go that end up making code a lot nicer. You then don't need to initialize this at all in `makeSlidingWindow`.
</blockquote></details>

I agree, this way the code looks nicer.
___
*[pkg/sql/sem/builtins/window_frame_builtins.go, line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LH-DSX66hP_wqmMTqug:-LH-uNom0JjjwR8ndPXU:blg302i) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0ef4d61e4a1300e705b3c5395bc72dfc2e2e534/pkg/sql/sem/builtins/window_frame_builtins.go#L63)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we use two calls to `copy` here? That would be faster because it could use a memcpy directly.
</blockquote></details>

Yes, we can.
___
*[pkg/sql/sem/builtins/window_frame_builtins.go, line 144 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LH-HKnd97QNMRb0EtKK:-LH-ugyY1jfMurysdVTw:bau46xc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0ef4d61e4a1300e705b3c5395bc72dfc2e2e534/pkg/sql/sem/builtins/window_frame_builtins.go#L144)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: Delete `newEndIdx` and replace it with `i`, which is scoped only to this loop.

`for i := sw.values.len() - 1; ...`
</blockquote></details>

Done. At some point I was using it outside of the loop, but then changed the code and forgot the restrict the scope.
___
*[pkg/sql/sem/builtins/window_frame_builtins.go, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LH-HaQc3AfBYIVWJAh-:-LH-v5T_6e6BymHkLybD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0ef4d61e4a1300e705b3c5395bc72dfc2e2e534/pkg/sql/sem/builtins/window_frame_builtins.go#L158)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Same thing here. No need for `newStartIdx` to be scoped outside of this loop. Once it's a loop index variable, might as well call it `i` to avoid noise.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/window_frame_builtins.go, line 194 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LH-FOeg2FC7V0kbe2td:-LH-sy3q1b7BM37Rbusa:b-m16fak) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0ef4d61e4a1300e705b3c5395bc72dfc2e2e534/pkg/sql/sem/builtins/window_frame_builtins.go#L194)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`.len() == 0`. Don't break the abstraction you fought so hard for!
</blockquote></details>

Nice catch, thanks.
___
*[pkg/sql/sem/builtins/window_frame_builtins.go, line 239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LH-HACR8A5ml4Y5bPiD:-LH-vXRY5kF_Puhayiu4:b-fvm3yj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0ef4d61e4a1300e705b3c5395bc72dfc2e2e534/pkg/sql/sem/builtins/window_frame_builtins.go#L239)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`-v.Duration` doesn't work?
</blockquote></details>

As far as options I tried, it doesn't.

However, I'm not sure whether I should include changes related to `Interval` type since supporting this type requires more work - for instance, offsets can currently be only integers, but it could also be something like `'10 days' PRECEDING`. I plan to get back to it after finishing up window functions in distsql.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-:-LHZ-5T-2E987w-fJ9UY:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sem/builtins/window_frame_builtins.go, line 239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LH-HACR8A5ml4Y5bPiD:-LHYzhOk8WIiJplicjKd:b-dnz58g) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0ef4d61e4a1300e705b3c5395bc72dfc2e2e534/pkg/sql/sem/builtins/window_frame_builtins.go#L239)):*
> As far as options I tried, it doesn't.

Oh, this is a `duration.Duration`, not a `time.Duration`. That makes sense.

> However, I'm not sure whether I should include changes related to Interval type since supporting this type requires more work - for instance, offsets can currently be only integers, but it could also be something like '10 days' PRECEDING. I plan to get back to it after finishing up window functions in distsql.

Ok, please leave a TODO comment then.
___
*[pkg/sql/sem/builtins/window_frame_builtins.go, line 137 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LHYz_u_7Z0Wq6VpQfhv:-LHYz_ua7-IipJq5b0u0:b-4wv9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/77ce2b7558e833619ac62ce79ec064e4377d2026/pkg/sql/sem/builtins/window_frame_builtins.go#L137)):*
> ```Go
> ) *slidingWindow {
> 	return &slidingWindow{
> 		values:  ringBuffer{},
> ```

No need for this line.

**Review by yuzefovich — COMMENTED** [review]
Thanks for your reviews!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-:-LHZCwEbCgTXoTDvuwD2:b7absbu)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/sem/builtins/window_frame_builtins.go, line 239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LH-HACR8A5ml4Y5bPiD:-LHZD-bS1cA5eJgxDWJf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0ef4d61e4a1300e705b3c5395bc72dfc2e2e534/pkg/sql/sem/builtins/window_frame_builtins.go#L239)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> As far as options I tried, it doesn't.

Oh, this is a `duration.Duration`, not a `time.Duration`. That makes sense.

> However, I'm not sure whether I should include changes related to Interval type since supporting this type requires more work - for instance, offsets can currently be only integers, but it could also be something like '10 days' PRECEDING. I plan to get back to it after finishing up window functions in distsql.

Ok, please leave a TODO comment then.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/window_frame_builtins.go, line 137 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26988#-LHYz_u_7Z0Wq6VpQfhv:-LHZCzStCikYJxw3f44v:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/77ce2b7558e833619ac62ce79ec064e4377d2026/pkg/sql/sem/builtins/window_frame_builtins.go#L137)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

No need for this line.
</blockquote></details>

Done.

**Pull request merged**
