### PR TITLE
gossip: avoid racing client removal against ID discovery

### LINKED ISSUE #8937: stress: failed test in cockroach/gossip/gossip.test: TestGossipOrphanedStallDetection
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/7a59042b04a56c69dc7956b97f5dbce6b8312f13

Stress build found a failed test:

```
=== RUN   TestGossipOrphanedStallDetection
W160830 05:17:02.852395 gossip/gossip.go:1037  no resolvers found; use --join to specify a connected node
W160830 05:17:02.853916 gossip/gossip.go:1037  no resolvers found; use --join to specify a connected node
I160830 05:17:02.856401 gossip/client.go:111  node 2: started gossip client to 127.0.0.1:34454
I160830 05:17:02.857389 stopper.go:408  quiesceing; tasks left:
2      gossip/infostore.go:290
I160830 05:17:02.857458 stopper.go:408  quiesceing; tasks left:
1      gossip/infostore.go:290
I160830 05:17:02.857541 http2_server.go:276  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:34454->127.0.0.1:39848: use of closed network connection
I160830 05:17:02.857562 http2_client.go:1029  transport: http2Client.notifyError got notified that the client transport was broken EOF.
I160830 05:17:02.857811 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:34454: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:34454" <nil>}
I160830 05:17:02.861849 gossip/gossip.go:1053  node has connected to cluster via gossip
I160830 05:17:03.857936 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:34454: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:34454" <nil>}
I160830 05:17:05.290911 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:34454: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:34454" <nil>}
I160830 05:17:07.982285 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:34454: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:34454" <nil>}
I160830 05:17:11.466891 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:34454: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:34454" <nil>}
I160830 05:17:17.447406 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:34454: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:34454" <nil>}
I160830 05:17:27.557251 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:34454: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:34454" <nil>}
I160830 05:17:43.897937 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:34454: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:34454" <nil>}
I160830 05:17:47.944167 /go/src/google.golang.org/grpc/clientconn.go:767  grpc: addrConn.transportMonitor exits due to: context canceled
--- FAIL: TestGossipOrphanedStallDetection (45.09s)
	testing.go:117: gossip/gossip_test.go:308, condition failed to evaluate within 45s: 2 still connected
```

Run Details:

```
32 runs so far, 0 failures, over 5s
66 runs so far, 0 failures, over 10s
109 runs so far, 0 failures, over 15s
149 runs so far, 0 failures, over 20s
187 runs so far, 0 failures, over 25s
225 runs so far, 0 failures, over 30s
265 runs so far, 0 failures, over 35s
299 runs so far, 0 failures, over 40s
333 runs so far, 0 failures, over 45s
367 runs so far, 0 failures, over 50s
395 runs so far, 0 failures, over 55s
426 runs so far, 0 failures, over 1m0s
452 runs completed, 1 failures, over 1m4s
FAIL
```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by tamird**
Fixes #8937.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8945)

### CODE REVIEW

**Comment by petermattis** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[gossip/client.go, line 290 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8945#-KQR-hbz9lDO9WhlS4NN:-KQR-hbz9lDO9WhlS4NO:b-5iutq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5196018739fb35390e93172d57f454247797f078/gossip/client.go#L290)):*
> ```Go
> 			}
> 		}()
> 		wg.Done()
> ```

There are other ways to return from `client.gossip()`, don't we want all of them to signal the wait group? Seems safer to do `defer wg.Done()` in `client.gossip()` (immediately after the `wg.Add(1)`). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8945)*

**Comment by tamird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[gossip/client.go, line 290 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8945#-KQR-hbz9lDO9WhlS4NN:-KQR0DB5AmrCZwR4_but:b-ipjin2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5196018739fb35390e93172d57f454247797f078/gossip/client.go#L290)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> There are other ways to return from `client.gossip()`, don't we want all of them to signal the wait group? Seems safer to do `defer wg.Done()` in `client.gossip()` (immediately after the `wg.Add(1)`). 
</details>
Note that this isn't returning from `gossip` - this is the end of the worker. `defer wg.Done()` in `client.gossip()` is exactly the wrong thing (otherwise we'd just wait until the method returned).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8945)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[gossip/client.go, line 290 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8945#-KQR-hbz9lDO9WhlS4NN:-KQR3EuHkE4T6IQkZblt:b-3dfu6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/5196018739fb35390e93172d57f454247797f078/gossip/client.go#L290)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Note that this isn't returning from `gossip` - this is the end of the worker. `defer wg.Done()` in `client.gossip()` is exactly the wrong thing (otherwise we'd just wait until the method returned).
</details>
Ah, this deserves a comment: `Signal the wait group that we are done receiving gossip messages.`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8945#-:-KQR3RgbZq1FJl7hyiED:bnfp4nl)*

**Comment by tamird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[gossip/client.go, line 290 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8945#-KQR-hbz9lDO9WhlS4NN:-KQR4AF1Ct1IP4MWPF5M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5196018739fb35390e93172d57f454247797f078/gossip/client.go#L290)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Ah, this deserves a comment: `Signal the wait group that we are done receiving gossip messages.`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8945)*

**Pull request merged**
