### PR TITLE
roachtest: update ruby-pg and activerecord tests

### LINKED ISSUE #108848: roachtest: npgsql failed
roachtest.npgsql [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11339541?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11339541?buildTab=artifacts#/npgsql) on master @ [e0de1f12d4f496fc7e4050a33e96f8c635c7a27c](https://github.com/cockroachdb/cockroach/commits/e0de1f12d4f496fc7e4050a33e96f8c635c7a27c):

```
(orm_helpers.go:212).summarizeFailed: 
Tests run on Cockroach v23.2.0-alpha.00000000-dev-e0de1f12d4f496fc7e4050a33e96f8c635c7a27c
Tests run against npgsql v7.0.2
3292 Total Tests Run
2560 tests passed
732 tests failed
248 tests skipped
49 tests ignored
0 tests passed unexpectedly
2 tests failed unexpectedly
0 tests expected failed but skipped
0 tests expected failed but not run
---
--- FAIL: Npgsql.Tests.NotificationTests.Wait_with_timeout -  (unexpected)
--- FAIL: Npgsql.Tests.CommandTests(Multiplexing).Use_across_connection_change(NotPrepared) -  (unexpected)
For a full summary look at the npgsql artifacts 
An updated blocklist (npgsqlBlocklist) is available in the artifacts' npgsql log
test artifacts and logs in: /artifacts/npgsql/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/p/roachfana/teamcity-11339541-1692164772-17-n1cpu4/1692201005708/1692201259502)

</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*npgsql.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-30665

### LINKED ISSUE #109357: roachtest: ruby-pg failed
roachtest.ruby-pg [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11449045?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11449045?buildTab=artifacts#/ruby-pg) on master @ [0bbf845a525d02661b853a4dd1190d8b9831a3d4](https://github.com/cockroachdb/cockroach/commits/0bbf845a525d02661b853a4dd1190d8b9831a3d4):

```
(orm_helpers.go:212).summarizeFailed: 
Tests run on Cockroach v23.2.0-alpha.00000000-dev-0bbf845a525d02661b853a4dd1190d8b9831a3d4
Tests run against ruby-pg v1.3.5
834 Total Tests Run
648 tests passed
186 tests failed
0 tests skipped
0 tests ignored
2 tests passed unexpectedly
0 tests failed unexpectedly
0 tests expected failed but skipped
2 tests expected failed but not run
---
For a full summary look at the ruby-pg artifacts 
An updated blocklist (rubyPGBlocklist) is available in the artifacts' ruby-pg log
test artifacts and logs in: /artifacts/ruby-pg/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/p/roachfana/teamcity-11449045-1692769663-63-n1cpu4/1692814487685/1692815052160)

</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*ruby-pg.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-30888

### LINKED ISSUE #109552: roachtest: activerecord failed
roachtest.activerecord [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11499593?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11499593?buildTab=artifacts#/activerecord) on release-23.1.9-rc @ [49148609ccafb4dd3bc547ef3aaa10c95b4f8dbf](https://github.com/cockroachdb/cockroach/commits/49148609ccafb4dd3bc547ef3aaa10c95b4f8dbf):

```
(orm_helpers.go:212).summarizeFailed: 
Tests run on Cockroach v23.1.9-dev-49148609ccafb4dd3bc547ef3aaa10c95b4f8dbf
Tests run against activerecord 7.0.3
6537 Total Tests Run
6537 tests passed
0 tests failed
25 tests skipped
395 tests ignored
0 tests passed unexpectedly
0 tests failed unexpectedly
0 tests expected failed but skipped
8 tests expected failed but not run
---
--- PASS: SerializedAttributeTest#test_unexpected_serialized_type (expected)
For a full summary look at the activerecord artifacts
An updated blocklist (activeRecordBlocklist) is available in the artifacts' activerecord log
test artifacts and logs in: /artifacts/activerecord/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/p/roachfana/teamcity-11499593-1693028586-17-n1cpu4/1693032086187/1693040698912)

</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*activerecord.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-30982

### LINKED ISSUE #109554: roachtest: npgsql failed
roachtest.npgsql [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11499593?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11499593?buildTab=artifacts#/npgsql) on release-23.1.9-rc @ [49148609ccafb4dd3bc547ef3aaa10c95b4f8dbf](https://github.com/cockroachdb/cockroach/commits/49148609ccafb4dd3bc547ef3aaa10c95b4f8dbf):

```
(orm_helpers.go:212).summarizeFailed: 
Tests run on Cockroach v23.1.9-dev-49148609ccafb4dd3bc547ef3aaa10c95b4f8dbf
Tests run against npgsql v7.0.2
3293 Total Tests Run
2555 tests passed
738 tests failed
248 tests skipped
48 tests ignored
0 tests passed unexpectedly
2 tests failed unexpectedly
0 tests expected failed but skipped
0 tests expected failed but not run
---
--- FAIL: Npgsql.Tests.TaskTimeoutAndCancellationTest.DelayedFaultedTaskCancellation("CancelOnly") -  (unexpected)
--- FAIL: Npgsql.Tests.TaskTimeoutAndCancellationTest.DelayedFaultedTaskCancellation("TimeoutOnly") -  (unexpected)
For a full summary look at the npgsql artifacts
An updated blocklist (npgsqlBlocklist) is available in the artifacts' npgsql log
test artifacts and logs in: /artifacts/npgsql/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/p/roachfana/teamcity-11499593-1693028586-30-n1cpu4/1693057313643/1693057571552)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #108848 roachtest: npgsql failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-master release-blocker]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*npgsql.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-30984

### LINKED ISSUE #109563: roachtest: activerecord failed
roachtest.activerecord [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11508355?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11508355?buildTab=artifacts#/activerecord) on release-23.1 @ [e9a99ca5edea2d3f838467323355be76d9d3ec92](https://github.com/cockroachdb/cockroach/commits/e9a99ca5edea2d3f838467323355be76d9d3ec92):

```
(orm_helpers.go:212).summarizeFailed: 
Tests run on Cockroach v23.1.9-dev-e9a99ca5edea2d3f838467323355be76d9d3ec92
Tests run against activerecord 7.0.3
3090 Total Tests Run
3090 tests passed
0 tests failed
18 tests skipped
809 tests ignored
0 tests passed unexpectedly
0 tests failed unexpectedly
0 tests expected failed but skipped
8 tests expected failed but not run
---
For a full summary look at the activerecord artifacts
An updated blocklist (activeRecordBlocklist) is available in the artifacts' activerecord log
test artifacts and logs in: /artifacts/activerecord/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/p/roachfana/teamcity-11508355-1693115043-17-n1cpu4/1693115811998/1693120808220)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #109552 roachtest: activerecord failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-release-23.1.9-rc release-blocker]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*activerecord.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-30990

### PR DESCRIPTION
**Pull request by rafiss**
### roachtest: update ruby-pg with new passing tests

---

### roachtest: remove activerecord expected failures

Since we are waiting for upstream fixes, we should make the blocklist
empty. Otherwise, the roachtest will fail if these activerecord tests
DON'T fail, which can happen if the tests don't get run.

---

###  roachtest: mark npgsql tests as flaky

---

fixes https://github.com/cockroachdb/cockroach/issues/108848
fixes https://github.com/cockroachdb/cockroach/issues/109554
fixes https://github.com/cockroachdb/cockroach/issues/109552
fixes https://github.com/cockroachdb/cockroach/issues/109563
fixes https://github.com/cockroachdb/cockroach/issues/109357

Release note: None

### CODE REVIEW

**Review by annrpom — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109701#-:-Nd27Z2p2hZKIiYc3qto:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andyyang890, @smg260, and @srosenberg)

**Comment by annrpom** [comment]
should this also be backported to 23.1.9-rc?

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109701)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/activerecord_blocklist.go` line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109701#-Nd28FDO0aAYTYZjsl5i:-Nd28FDO0aAYTYZjsl5j:bul6hcj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f6fbc036cad72a52bf3406570cf5d96753ecfd6/pkg/cmd/roachtest/tests/activerecord_blocklist.go#L25)):*
> ```Go
> // in the test log.
> var activeRecordBlocklist = blocklist{
> 	"ActiveRecord::CockroachDB::Migration::PGChangeSchemaTest#test_change_string_to_date":                                               "49329",
> ```

Do you think it might be better to comment these out instead of deleting them so we don't lose our record of which tests we expect to fail once the upstream changes are merged? Or are we just going to regenerate this list from future failures?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109701)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andyyang890, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/activerecord_blocklist.go` line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109701#-Nd28FDO0aAYTYZjsl5i:-Nd2AV7tC-vKkv6xgtq7:b-v0c2g6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f6fbc036cad72a52bf3406570cf5d96753ecfd6/pkg/cmd/roachtest/tests/activerecord_blocklist.go#L25)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Do you think it might be better to comment these out instead of deleting them so we don't lose our record of which tests we expect to fail once the upstream changes are merged? Or are we just going to regenerate this list from future failures?
</blockquote></details>

i think we should regenerate this once the tests are fixed. Ideally, we'd end up with all the tests passing anyway.

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
