### PR TITLE
sql: support tuple EQ/NE in splitFilter

### LINKED ISSUE #21243: sql: problem with filter propagation through joins
```
root@:26257/test> CREATE TABLE abcdef (
               ->     a INT NOT NULL,
               ->     b INT NOT NULL,
               ->     c INT NOT NULL,
               ->     d INT NOT NULL,
               ->     e INT NULL,
               ->     f INT NULL,
               ->     CONSTRAINT "primary" PRIMARY KEY (a ASC, b ASC, c DESC, d ASC),
               ->     FAMILY "primary" (a, b, c, d, e, f)
               -> );
CREATE TABLE

Time: 35.578305ms

root@:26257/test> 
root@:26257/test> CREATE TABLE abcdef__static (                        
               ->     a INT NOT NULL,                                  
               ->     b INT NOT NULL,                                  
               ->     g INT NULL,                                      
               ->     CONSTRAINT "primary" PRIMARY KEY (a ASC, b ASC), 
               ->     FAMILY "primary" (a, b, g)                       
               -> );
CREATE TABLE

Time: 55.690702ms

root@:26257/test> 
root@:26257/test> explain select * from abcdef as A join (select * from abcdef__static) as B using (a,b) where ((a,b)>(1,2) or ((a,b)=(1,2) and c < 6) or ((a,b,c)=(1,2,6) and d > 8));
+----------------+----------------+-----------------------------------+
|      Tree      |     Field      |            Description            |
+----------------+----------------+-----------------------------------+
| render         |                |                                   |
|  └── join      |                |                                   |
|       │        | type           | inner                             |
|       │        | equality       | (a, b) = (a, b)                   |
|       │        | mergeJoinOrder | +"(a=a)",+"(b=b)"                 |
|       ├── scan |                |                                   |
|       │        | table          | abcdef@primary                    |
|       │        | spans          | /1/2/6/9-/1/2/5 /1/2/5-/1/3 /1/3- |
|       └── scan |                |                                   |
|                | table          | abcdef__static@primary            |
|                | spans          | ALL                               |
+----------------+----------------+-----------------------------------+
(11 rows)
```

This should have propagated the (a, b) >= (1, 2) condition to the right side, like this:

```
root@:26257/test> explain select * from abcdef as A join (select * from abcdef__static) as B using (a,b) where ((a,b)>(1,2) or ((a,b)=(1,2) and c < 6) or ((a,b,c)=(1,2,6) and d > 8)) AND (a,b) >= (1,2);
+----------------+----------------+-----------------------------------+
|      Tree      |     Field      |            Description            |
+----------------+----------------+-----------------------------------+
| render         |                |                                   |
|  └── join      |                |                                   |
|       │        | type           | inner                             |
|       │        | equality       | (a, b) = (a, b)                   |
|       │        | mergeJoinOrder | +"(a=a)",+"(b=b)"                 |
|       ├── scan |                |                                   |
|       │        | table          | abcdef@primary                    |
|       │        | spans          | /1/2/6/9-/1/2/5 /1/2/5-/1/3 /1/3- |
|       └── scan |                |                                   |
|                | table          | abcdef__static@primary            |
|                | spans          | /1/2-                             |
+----------------+----------------+-----------------------------------+
(11 rows)
```

`splitFilter` should be able to start from `((a,b)>(1,2) or ((a,b)=(1,2) and c < 6) or (a,b,c)=(1,2,6) and d > 8))` and derive `(a,b) > (1,2) or (a,b) = (1,2) or (a,b) = (1,2)`.

### PR DESCRIPTION
**Pull request by RaduBerinde**
We currently support truncating inequalities in splitFilter, but we
don't break up tuple equality (and we don't normalize
`(a, b, c) = (1, 2, 3)` to `a = 1 AND b = 2 AND c = 3`).

This change adds special handling for tuple equalities. We also break
up `(a, b, c) != (1, 2, 3)` if it is inside a NOT.

Fixing a bug noticed in `tryTruncateTupleComparison` where we only
handled prefixes up to 2.

Fixes #21243.

Release note (performance improvement): more efficient scans with
joins and certain complex WHERE clauses containing tuple equality.

### CODE REVIEW

**Comment by knz** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/expr_filter.go, line 250 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21288#-L2BEI1mx5D9UdCRdc5l:-L2BEI1mx5D9UdCRdc5m:b-f0znxi) ([raw file](https://github.com/cockroachdb/cockroach/blob/151eddd02bb584addebdead3e99a88dd9557138d/pkg/sql/expr_filter.go#L250)):*
> ```Go
> // If the given expression is a tuple EQ or NE, extract a comparison that
> // contains only variables known to the conversion function. See
> // truTruncateTupleComparison for information on "weaker".
> ```

tru -> try

---

*[pkg/sql/expr_filter.go, line 266 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21288#-L2BEphg76IYVqSImlzo:-L2BEphg76IYVqSImlzp:bqh68g6) ([raw file](https://github.com/cockroachdb/cockroach/blob/151eddd02bb584addebdead3e99a88dd9557138d/pkg/sql/expr_filter.go#L266)):*
> ```Go
> 	left, leftOk := t.Left.(*tree.Tuple)
> 	right, rightOk := t.Right.(*tree.DTuple)
> 	// TODO(radu): we should also support Tuple on both sides.
> ```

Incidental question (not directly related to this PR): Why do we have a `DTuple` datum type at all? Why is it not sufficient to have the `Tuple`  `Expr` type?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21288#-:-L2BFKI0gTdP50dEnGYr:bnfp4nl)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/expr_filter.go, line 266 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21288#-L2BEphg76IYVqSImlzo:-L2GKNPH4x0cdAZxTtfM:b-s0gqqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/151eddd02bb584addebdead3e99a88dd9557138d/pkg/sql/expr_filter.go#L266)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Incidental question (not directly related to this PR): Why do we have a `DTuple` datum type at all? Why is it not sufficient to have the `Tuple`  `Expr` type?
</blockquote></details>

`DTuple` implements `Datum`, without it planNodes wouldn't be able to output tuples.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21288)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/expr_filter.go, line 266 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21288#-L2BEphg76IYVqSImlzo:-L2GPG_2CzPYzQhP8DPA:bpwz8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/151eddd02bb584addebdead3e99a88dd9557138d/pkg/sql/expr_filter.go#L266)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`DTuple` implements `Datum`, without it planNodes wouldn't be able to output tuples.
</blockquote></details>

Sorry I wasn't clear -- why do we have a distinction between the two types? Could we not have a single type that implements the Datum interface and also serves tuple expression purposes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21288)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/expr_filter.go, line 266 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21288#-L2BEphg76IYVqSImlzo:-L2GQ8_xBqh6wO8wKgPg:by3wonw) ([raw file](https://github.com/cockroachdb/cockroach/blob/151eddd02bb584addebdead3e99a88dd9557138d/pkg/sql/expr_filter.go#L266)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Sorry I wasn't clear -- why do we have a distinction between the two types? Could we not have a single type that implements the Datum interface and also serves tuple expression purposes?
</blockquote></details>

Maybe, not sure. AFAICT it would be the first type that implements Datum while not always being a datum. Would the Datum methods Panic if the Tuple doesn't have only `Datum`s as sub-expressions?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21288)*

**Comment by RaduBerinde** [comment]
TFTR!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21288#-:-L2GRjXn9qL7qZggLhUo:b-814g8k)*

**Comment by knz** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/expr_filter.go, line 266 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21288#-L2BEphg76IYVqSImlzo:-L2GS1EffoJj722HM_zI:b-vi7lvv) ([raw file](https://github.com/cockroachdb/cockroach/blob/151eddd02bb584addebdead3e99a88dd9557138d/pkg/sql/expr_filter.go#L266)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Maybe, not sure. AFAICT it would be the first type that implements Datum while not always being a datum. Would the Datum methods Panic if the Tuple doesn't have only `Datum`s as sub-expressions?
</blockquote></details>

Well they do currently but I don't see a reason why they should :)

Anyway I was just curious.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21288)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/sem/tree/expr.go, line 757 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21288#-L2GqAuNcFFBYyJuZNeT:-L2GqAuNcFFBYyJuZNeU:b3w9w2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae7f42e399dc27c04973a4c982d60029893eed7c/pkg/sql/sem/tree/expr.go#L757)):*
> ```Go
> 		types: make(types.TTuple, 0, set.Len()),
> 	}
> 	for i, ok := set.Next(0); ok; i, ok = set.Next(i + 1) {
> ```

Interesting iteration pattern, though that's a lot of `ok`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21288#-:-L2GqJ6erRDCxkXNxvtm:bnfp4nl)*

**Pull request merged**
