### PR TITLE
sql: Populate pg_cast

### LINKED ISSUE #47498: sql: Populate pg_cast table
See the documentation on this catalog table here: https://www.postgresql.org/docs/12/catalog-pg-cast.html

This is currently used by ActiveRecord, though we are exploring if there is a workaround.

ActiveRecord is running this query:

```
              SELECT exists(
                SELECT * FROM pg_proc
                WHERE proname = 'lower'
                  AND proargtypes = ARRAY[#{quote column.sql_type}::regtype]::oidvector
              ) OR exists(
                SELECT * FROM pg_proc
                INNER JOIN pg_cast
                  ON ARRAY[casttarget]::oidvector = proargtypes
                WHERE proname = 'lower'
                  AND castsource = #{quote column.sql_type}::regtype
              )
```

Jira issue: CRDB-4404

### PR DESCRIPTION
**Pull request by e-mbrown**
Resolves #47498

Release note (sql change): The pg_cast table was populated in order
to match PostgreSQL behavior.

### CODE REVIEW

**Review by otan — COMMENTED** [review]
this needs a test as a `pg_catalog` logic test.

**Review by mgartner — APPROVED** [review]
:lgtm: Very nice!

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79537#-:-N07T5789wcUaNlftVAz:b-kerl87)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @e-mbrown, @otan, and @rafiss)

___
*[pkg/sql/pg_catalog.go, line 493 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79537#-N07S7r2A68RdtfnRkxM:-N07S7r2A68RdtfnRkxN:bg5gjgl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a205088862a51ce614563f5ee34f1823d9b8a5aa/pkg/sql/pg_catalog.go#L493)):*
> ```Go
> 				case tree.CastContextImplicit:
> 					castCtx = "i"
> 				}
> ```

nit: you could move this switch statement to a helper called something like `PGString()`, which would be similar to `CastContext.String()`: https://github.com/cockroachdb/cockroach/blob/4c5f7326ee9db6ac25f431a4cf0b9c9df7ca6ec2/pkg/sql/sem/tree/cast.go#L69-L81
___
*[pkg/sql/sem/tree/cast.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79537#-N07Sh2HE0CUsy1EPNPY:-N07Sh2HE0CUsy1EPNPZ:b-xiaedx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a205088862a51ce614563f5ee34f1823d9b8a5aa/pkg/sql/sem/tree/cast.go#L105)):*
> ```Go
> 	// [1] https://www.postgresql.org/docs/13/catalog-pg-cast.html#CATALOG-PG-CAST
> 	// [2] https://www.postgresql.org/docs/13/sql-createcast.html#SQL-CREATECAST-NOTES
> 	contextOriginAutomaticIOConversion
> ```

nit: I think it's a bit odd to export only one of these ContextOrigin constants. I see no harm in exporting all of them, even if they aren't used.

**Comment by mgartner** [comment]
*[pkg/sql/pg_catalog.go, line 4492 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79537#-N0ChrhB2JwA-ooUUt0V:-N0ChrhB2JwA-ooUUt0W:b-lefyu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c62198c0a61040fcaebb5ebf4892600a6ae5f442/pkg/sql/pg_catalog.go#L4492)):*
> ```Go
> 
> // PGString returns the representation of CastContext as a string.
> func PGString(castCtx tree.CastContext) string {
> ```

I think this would be better as a method of `tree.CastContext` that lives in `pkg/sql/sem/tree/cast.go`, like `func (cc CastContext) PGString() string { ... }`. You can put it right under the CastContext's `String()` method that I linked to previously

**Review by mgartner — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79537)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan and @rafiss)

**Review by otan — APPROVED** [review]

**Comment by e-mbrown** [comment]
Tftr 
bors r+

**Pull request merged**
