### PR TITLE
sqlstats, sql: add latency info to statement statistics

### PR DESCRIPTION
**Pull request by maryliag**
This commits adds latency info in seconds to the statement
statistics on `crdb_internal.statement_statistics`,
`system.statement_statistics` and
`crdb_internal.cluster_statement_statistics`,
with information about: min, max, p50, p90 and p99.

It also adds to `crdb_internal.node_statement_statistics`
the columns: `latency_seconds_min`, `latency_seconds_max`, `latency_seconds_p50`,
` latency_seconds_p90` and `latency_seconds_p99`.

Part Of #72954

This initial version is leveraging the latency summary that
already existed on Insights. Since we were already collecting
that information for all statements that executed for at least
`AnomalyDetectionLatencyThreshold`, this commit makes that
mapping available so SQLStats can use it to retrieve the values.
This value is an estimate, since we're missing the executions
that took less than the 50ms (default).
We were also collecting just for p50, p90 and p99, so the
function that returns the values adds that limitation, in case
someone else was trying to use that function to retrieve other
percentiles.

A following task will focus on making this information more complete.

Example of statistics column on a `SELECT pg_sleep(x)` with various values of x between 0.1 and 3:
```
{
	"execution_statistics": {
                 ...
	},
	"index_recommendations": [],
	"statistics": {
                 ...
		"latencyInfo": {
			"max": 3.050540917,
			"min": 0.101273666,
			"p50": 0.600609374,
			"p90": 1.000914625,
			"p99": 3.001826416
		},
	}
}
```

Example of new columns on node table:
```
...
latency_seconds_min           | 0.201089583
latency_seconds_max           | 3.200554126
latency_seconds_p50           | 0.700803875
latency_seconds_p90           | 1.501616292
latency_seconds_p99           | 3.200554126
```

Release note (sql change): Add latency info (min, max, p50, p90, p99)
to crdb_internal.statement_statistics, system.statement_statistics and
crdb_internal.cluster_statement_statistics. Also adds `latency_seconds_min`,
`latency_seconds_max`, `latency_seconds_p50`, `latency_seconds_p90` and `latency_seconds_p99` to
crdb_internal.node_statement_statistics.

### CODE REVIEW

**Review by ericharmeling — COMMENTED** [review]
Nice! Just a couple nits and a question.

> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96396#-:-NNcY1Ot1eP7XNRX1t_2:b-yd95h4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/sql/appstatspb/app_stats.proto` line 347 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96396#-NNcW4Y643QcHN5D3T9Y:-NNcW4Y643QcHN5D3T9Z:bb7lc5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/936f985eb9f89d8a7559c4bc5cf29dfc03a1c4c4/pkg/sql/appstatspb/app_stats.proto#L347)):*
> ```protobuf
> // LatencyInfo contains more details about the latency.
> message LatencyInfo {
>   // Min is the minimum time in seconds spent by the fingerprint.
> ```

nit:



_Suggestion:_
```protobuf
// Min is the minimum time in seconds spent executing the fingerprint.
```
___
*[`pkg/sql/appstatspb/app_stats.proto` line 350 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96396#-NNcW8PJ1Wjm6h2iEQUr:-NNcW8PJ1Wjm6h2iEQUs:bb7lc5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/936f985eb9f89d8a7559c4bc5cf29dfc03a1c4c4/pkg/sql/appstatspb/app_stats.proto#L350)):*
> ```protobuf
>   optional double min = 1 [(gogoproto.nullable) = false];
> 
>   // Max is the maximum time in seconds spent by the fingerprint.
> ```

nit:



_Suggestion:_
```protobuf
// Max is the maximum time in seconds spent executing the fingerprint.
```
___
*[`pkg/sql/sqlstats/insights/detector.go` line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96396#-NNcXbiE0Tbe0HfAjdks:-NNcXbiE0Tbe0HfAjdkt:b-ul1vi1) ([raw file](https://github.com/cockroachdb/cockroach/blob/936f985eb9f89d8a7559c4bc5cf29dfc03a1c4c4/pkg/sql/sqlstats/insights/detector.go#L147)):*
> ```Go
> 
> func newAnomalyDetector(settings *cluster.Settings, metrics Metrics) *anomalyDetector {
> 	anomaly := &anomalyDetector{
> ```

Does this function not need to lock/unlock?



_Code quote:_
```Go
func newAnomalyDetector(settings *cluster.Settings, metrics Metrics) *anomalyDetector {
	anomaly := &anomalyDetector{
		settings: settings,
		metrics:  metrics,
		store:    list.New(),

	}
	anomaly.mu.index = make(map[appstatspb.StmtFingerprintID]*list.Element)

	return anomaly
```

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96396)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[`pkg/sql/appstatspb/app_stats.proto` line 347 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96396#-NNcW4Y643QcHN5D3T9Y:-NNcmBuE90tE-pgkDr-V:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/936f985eb9f89d8a7559c4bc5cf29dfc03a1c4c4/pkg/sql/appstatspb/app_stats.proto#L347)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

nit:
</blockquote></details>

Done
___
*[`pkg/sql/appstatspb/app_stats.proto` line 350 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96396#-NNcW8PJ1Wjm6h2iEQUr:-NNcmCsS4Btknru06W3u:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/936f985eb9f89d8a7559c4bc5cf29dfc03a1c4c4/pkg/sql/appstatspb/app_stats.proto#L350)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

nit:
</blockquote></details>

Done
___
*[`pkg/sql/sqlstats/insights/detector.go` line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96396#-NNcXbiE0Tbe0HfAjdks:-NNcmEY69w06s0OaiCm6:b-3icfkn) ([raw file](https://github.com/cockroachdb/cockroach/blob/936f985eb9f89d8a7559c4bc5cf29dfc03a1c4c4/pkg/sql/sqlstats/insights/detector.go#L147)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

Does this function not need to lock/unlock?
</blockquote></details>

It doesn't. At this point we're creating the detector/cache/etc.

**Review by ericharmeling — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96396)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/sql/sqlstats/insights/detector.go` line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96396#-NNcXbiE0Tbe0HfAjdks:-NNcnv4a32lsO71GfpAs:b-nbp88c) ([raw file](https://github.com/cockroachdb/cockroach/blob/936f985eb9f89d8a7559c4bc5cf29dfc03a1c4c4/pkg/sql/sqlstats/insights/detector.go#L147)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

It doesn't. At this point we're creating the detector/cache/etc. 
</blockquote></details>

Ah okay that makes sense. Thanks!

**Comment by j82w** [comment]
*[`-- commits` line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96396#-NNg9BhAEeZNzIbYMB95):*
What is the reason for adding it to insights instead of just add it to where the existing ServiceLat stat is being collected?

**Comment by j82w** [comment]
*[`-- commits` line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96396#-NNg9BhAEeZNzIbYMB95):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

What is the reason for adding it to insights instead of just add it to where the existing ServiceLat stat is being collected?
</blockquote></details>

More specifically I was thinking about ExecStats. Can't we just add a histogram to that and then remove the the need to compute it from insights? : https://github.com/cockroachdb/cockroach/blob/cc99062a810b5d9687e0c2b08cf73ce83fcd73cd/pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go#L445

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96396)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`-- commits` line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96396#-NNg9BhAEeZNzIbYMB95):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

More specifically I was thinking about ExecStats. Can't we just add a histogram to that and then remove the the need to compute it from insights? : https://github.com/cockroachdb/cockroach/blob/cc99062a810b5d9687e0c2b08cf73ce83fcd73cd/pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go#L445
</blockquote></details>

This PR didn't added to the Insights, it was already there because Insights was using to determine the anomaly detector (latency > p99 & > 2*p50). So for this PR I'm just using existing code (the changes on insights was to make that cache visible outside of insights). This will follow by another PR where I move this cache/collection out of insights, and then make improvements on it so it collects more info and not just when hitting an insight.

I create this version so we have some info to show (in this case sampled), in case I can't make the more complex change.

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96396)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`-- commits` line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96396#-NNg9BhAEeZNzIbYMB95):*
> More specifically I was thinking about ExecStats. Can't we just add a histogram to that and then remove the the need to compute it from insights? :

That is indeed my goal! Just not yet part of this PR

**Review by j82w — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96396#-:-NNgIX8V7fsrOi5AJ50m:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/sql/crdb_internal.go` line 1379 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96396#-NNgHyT84PbYXBZ-EcGE:-NNgHyT84PbYXBZ-EcGF:b7ffeiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/57cc6c4dd6a6b13af5486a8c6af1e02741fc9f89/pkg/sql/crdb_internal.go#L1379)):*
> ```Go
>   txn_fingerprint_id  STRING,
>   index_recommendations STRING[] NOT NULL,
>   latency_min FLOAT,
> ```

Can we add the unit to avoid confusion? 
___
*[`pkg/sql/crdb_internal.go` line 1380 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96396#-NNgHvqU7pDj8rfc4nhA:-NNgHvqU7pDj8rfc4nhB:b-tmkhzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/57cc6c4dd6a6b13af5486a8c6af1e02741fc9f89/pkg/sql/crdb_internal.go#L1380)):*
> ```Go
>   index_recommendations STRING[] NOT NULL,
>   latency_min FLOAT,
> 	latency_max FLOAT,
> ```

nit: spacing

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96396)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ericharmeling and @j82w)

___
*[`pkg/sql/crdb_internal.go` line 1379 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96396#-NNgHyT84PbYXBZ-EcGE:-NNgP85W-igWSMRJrlAf:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/57cc6c4dd6a6b13af5486a8c6af1e02741fc9f89/pkg/sql/crdb_internal.go#L1379)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Can we add the unit to avoid confusion? 
</blockquote></details>

Done
___
*[`pkg/sql/crdb_internal.go` line 1380 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96396#-NNgHvqU7pDj8rfc4nhA:-NNgP8n15KnlmLZLyyUh:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/57cc6c4dd6a6b13af5486a8c6af1e02741fc9f89/pkg/sql/crdb_internal.go#L1380)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

nit: spacing
</blockquote></details>

Done

**Comment by maryliag** [comment]
TFTR!
bors r+

**Pull request merged**
