### PR TITLE
sql: Implement ALTER DATABASE ... SURVIVE REGION/ZONE FAILURE

### PR DESCRIPTION
**Pull request by ajstorm**
This change implements ALTER DATABASE ... SURVIVE REGION/ZONE FAILURE
which allows the user to change the survival goal for an existing
database.

Release note (sql change): Implement ALTER DATABASE ... SURVIVE
REGION/ZONE FAILURE

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58937)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/alter_database.go, line 470 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58937#-MQx8fBBADoOg36Fp5uf:-MQx8fBC0n0kccUk9QdP:b-lm0vzm) ([raw file](https://github.com/cockroachdb/cockroach/blob/2157dafcca14848c053936fbe0cf4cf088540a24/pkg/sql/alter_database.go#L470)):*
> ```Go
> 			),
> 			"you must first add regions to the database using "+
> 				"ALTER DATABASE %s ADD REGION <region_name>",
> ```

Should this prompt the user to add a primary region?
___
*[pkg/sql/region_util.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58937#-MQx9CFa1Fpfe5ENidN3:-MQx9CFa1Fpfe5ENidN4:bhrd7cz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2157dafcca14848c053936fbe0cf4cf088540a24/pkg/sql/region_util.go#L29)):*
> ```Go
> )
> 
> const minNumRegionsForSurviveRegionGoal = 3
> ```

Isn't this subject to change depending on the replication factor?

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58937)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

___
*[pkg/sql/alter_database.go, line 470 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58937#-MQx8fBBADoOg36Fp5uf:-MQxEbIy3PjVgOG5Sm24:boq0s6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/2157dafcca14848c053936fbe0cf4cf088540a24/pkg/sql/alter_database.go#L470)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should this prompt the user to add a primary region?
</blockquote></details>

At this point we're already a multi-region database (see the test above for this if branch), so the only way out of this is to add additional regions.
___
*[pkg/sql/region_util.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58937#-MQx9CFa1Fpfe5ENidN3:-MQxEiZ-Dk15uUsjCS61:b-5byaah) ([raw file](https://github.com/cockroachdb/cockroach/blob/2157dafcca14848c053936fbe0cf4cf088540a24/pkg/sql/region_util.go#L29)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Isn't this subject to change depending on the replication factor?
</blockquote></details>

I don't think so.  I think even if you have a large number of nodes and a higher replication factor, you'd still only need a minimum of 3 regions to survive a region failure.  The bottom line is that you need at least 3 regions to place the replicas in such a way that if one of the regions goes down, you can still make quorum with the surviving too.  Then again, it's possible that I'm the one missing something here...

**Review by arulajmani — APPROVED** [review]
LGTM modulo the one clarification question

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58937#-:-MQxKVoo7HK5frtkNdYC:b-g1w7w2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/alter_database.go, line 470 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58937#-MQx8fBBADoOg36Fp5uf:-MQxIz7uEsp1PBXHGZm4:bvhasa8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2157dafcca14848c053936fbe0cf4cf088540a24/pkg/sql/alter_database.go#L470)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

At this point we're already a multi-region database (see the test above for this if branch), so the only way out of this is to add additional regions.
</blockquote></details>

Isn't this when the database is not a multi-region database, or am I missing something?
___
*[pkg/sql/region_util.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58937#-MQx9CFa1Fpfe5ENidN3:-MQxJRA-0SWfvQecv9OB:b-2mi6v6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2157dafcca14848c053936fbe0cf4cf088540a24/pkg/sql/region_util.go#L29)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

I don't think so.  I think even if you have a large number of nodes and a higher replication factor, you'd still only need a minimum of 3 regions to survive a region failure.  The bottom line is that you need at least 3 regions to place the replicas in such a way that if one of the regions goes down, you can still make quorum with the surviving too.  Then again, it's possible that I'm the one missing something here...
</blockquote></details>

Oh yeah, you're right. My bad!

**Review by otan — COMMENTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58937)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @arulajmani)

___
*[pkg/sql/alter_database.go, line 470 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58937#-MQx8fBBADoOg36Fp5uf:-MQxK-MiBE9qUGzhxoLl:b-pqkiuj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2157dafcca14848c053936fbe0cf4cf088540a24/pkg/sql/alter_database.go#L470)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Isn't this when the database is not a multi-region database, or am I missing something?
</blockquote></details>

not sure you you mean there, I think @arulajmani is right, we need to set a primary region first in this hint.
___
*[pkg/sql/alter_database.go, line 510 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58937#-MQxKsKp2YMwUVRg8mHH:-MQxKsKp2YMwUVRg8mHI:b-zfo8vi) ([raw file](https://github.com/cockroachdb/cockroach/blob/2157dafcca14848c053936fbe0cf4cf088540a24/pkg/sql/alter_database.go#L510)):*
> ```Go
> 
> 	// Update the database's zone configuration.
> 	if err := params.p.applyZoneConfigFromDatabaseRegionConfig(
> ```

i think we need to update table configurations as well, e.g. REGIONAL BY TABLE IN <non primary region> probably needs updating based on survivability goals.

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58937)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/alter_database.go, line 470 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58937#-MQx8fBBADoOg36Fp5uf:-MQxbGxx5VHeasqOQ4Wo:bo0o7xz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2157dafcca14848c053936fbe0cf4cf088540a24/pkg/sql/alter_database.go#L470)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

not sure you you mean there, I think @arulajmani is right, we need to set a primary region first in this hint.
</blockquote></details>

Ah, right.  My bad.  Added the correct hint.
___
*[pkg/sql/alter_database.go, line 510 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58937#-MQxKsKp2YMwUVRg8mHH:-MQxcC7C6XhNTHV0uftw:b-v3lrb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2157dafcca14848c053936fbe0cf4cf088540a24/pkg/sql/alter_database.go#L510)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i think we need to update table configurations as well, e.g. REGIONAL BY TABLE IN <non primary region> probably needs updating based on survivability goals.
</blockquote></details>

Good catch.  Will work on that now...

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58937)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/alter_database.go, line 510 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58937#-MQxKsKp2YMwUVRg8mHH:-MQygoQ_CgIba8PEICTq:b-4670xl) ([raw file](https://github.com/cockroachdb/cockroach/blob/2157dafcca14848c053936fbe0cf4cf088540a24/pkg/sql/alter_database.go#L510)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Good catch.  Will work on that now...
</blockquote></details>

Done.  @otan PTAL.  Thx!

**Review by otan — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58937)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/region_util.go, line 312 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58937#-MR1blB738kVvsPuEDh_:-MR1blB738kVvsPuEDha:b-s9zavs) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bd3fc0ab9595f5b48d0b0da1cb1a2f878fefd72/pkg/sql/region_util.go#L312)):*
> ```Go
> 
> 			switch l := tbDesc.LocalityConfig.Locality.(type) {
> 			case *descpb.TableDescriptor_LocalityConfig_RegionalByTable_:
> ```

global tables also need to include the new region, don't they?
otherwise, they can run rampant on any region.

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58937)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/region_util.go, line 312 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58937#-MR1blB738kVvsPuEDh_:-MR1sd7c9_nPcq1VswM-:b6l1256) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bd3fc0ab9595f5b48d0b0da1cb1a2f878fefd72/pkg/sql/region_util.go#L312)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

global tables also need to include the new region, don't they?
otherwise, they can run rampant on any region.
</blockquote></details>

Global tables should be inheriting the region constraints from the database zone configuration (which will have the region added at `ADD REGION` time).  The only field set in a global table's zone config should be `non_blocking_transactions`, which shouldn't need to be updated here.

@aayushshah15 to confirm.

**Review by otan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58937)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajstorm, and @arulajmani)

___
*[pkg/sql/region_util.go, line 272 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58937#-MR1xwFW2YgbbtDNg_4O:-MR1xwFW2YgbbtDNg_4P:b-oovjqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bd3fc0ab9595f5b48d0b0da1cb1a2f878fefd72/pkg/sql/region_util.go#L272)):*
> ```Go
> // NOTE: this function uses cached table and schema descriptors. As a result, it may
> // not be safe to run within a schema change.
> func (p *planner) updateZoneConfigsForLocalityRegionalByTable(
> ```

as a nit, i'd rather have this handle be `refreshZoneConfigs`, which handles all cases and ignores non-regional by table. that way if we need to update anything else it should be done in the one place.
___
*[pkg/sql/region_util.go, line 312 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58937#-MR1blB738kVvsPuEDh_:-MR1cAiA2J-8JxQ20E_d:bxc1tma) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bd3fc0ab9595f5b48d0b0da1cb1a2f878fefd72/pkg/sql/region_util.go#L312)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Global tables should be inheriting the region constraints from the database zone configuration (which will have the region added at `ADD REGION` time).  The only field set in a global table's zone config should be `non_blocking_transactions`, which shouldn't need to be updated here.

@aayushshah15 to confirm.
</blockquote></details>

ah, i see. it's not clear without the full story.

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58937)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/region_util.go, line 272 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58937#-MR1xwFW2YgbbtDNg_4O:-MR24RUQ1A7rCeEkmcmc:bxzgg6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bd3fc0ab9595f5b48d0b0da1cb1a2f878fefd72/pkg/sql/region_util.go#L272)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

as a nit, i'd rather have this handle be `refreshZoneConfigs`, which handles all cases and ignores non-regional by table. that way if we need to update anything else it should be done in the one place.
</blockquote></details>

I went with `updateZoneConfigsForAllTables()`, but it's the spirit of what you wanted.  Resonable?
___
*[pkg/sql/region_util.go, line 312 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58937#-MR1blB738kVvsPuEDh_:-MR262jJ5aOXHZc-RtUb:b-luprn7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bd3fc0ab9595f5b48d0b0da1cb1a2f878fefd72/pkg/sql/region_util.go#L312)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

ah, i see. it's not clear without the full story. 
</blockquote></details>

With the new change you proposed, it matters a lot less.  Code's cleaner now too.  Win-win.

**Comment by otan** [comment]
Lgtm! Ship it.

**Comment by ajstorm** [comment]
Awesome.  TFTR!

bors r=otan

**Comment by ajstorm** [comment]
another attempt

bors r=otan

**Pull request merged**
