### PR TITLE
storage: separate `services Stores` into per-RPC services

### PR DESCRIPTION
**Pull request by tamird**
This avoids the warty `panic("unimplemented")` methods.

This can wait until post-yellow.

cc @eisenstatdavid for context on a comment I left in #9159.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9246)

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/api.proto, line 67 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9246#-KTArnmXce4TiJkVA3jx:-KTArnmY8W3qEbwc2tH4:b-nhvc62) ([raw file](https://github.com/cockroachdb/cockroach/blob/d61a2ca24d1add65c7a13356a2d9a794faa44ffb/storage/api.proto#L67)):*
> ```protobuf
> }
> 
> service Freezes {
> ```

I think this is a good opportunity to get rid of the pluralizations, unless you think those are a good idea for some reason.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9246#-:-KTArzUu_W1_zBJKbBv9:bnfp4nl)*

**Comment by tschottdorf** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9246)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/api.proto, line 67 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9246#-KTArnmXce4TiJkVA3jx:-KTAsbyuOZ8b609MBrTC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d61a2ca24d1add65c7a13356a2d9a794faa44ffb/storage/api.proto#L67)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> I think this is a good opportunity to get rid of the pluralizations, unless you think those are a good idea for some reason.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9246)*

**Comment by tschottdorf** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/stores_server.go, line 30 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9246#-KTAujV_shV8DL5K4lUF:-KTAujV_shV8DL5K4lUG:b8k4vzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8084b7c55ea5cdbd72b5a90c1a7b85ebbcd29ce/storage/stores_server.go#L30)):*
> ```Go
> 
> // StoresServer handles store-addressed RPCs.
> type StoresServer interface {
> ```

Singularize? (In which case `git mv stores_server.go store_server.go`). I don't feel strongly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9246)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/stores_server.go, line 30 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9246#-KTAujV_shV8DL5K4lUF:-KTAvC1aIoIt51_GHiBg:bvwd333) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8084b7c55ea5cdbd72b5a90c1a7b85ebbcd29ce/storage/stores_server.go#L30)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Singularize? (In which case `git mv stores_server.go store_server.go`). I don't feel strongly.
</details>
Seems right to leave this pluralized since this thing dispatches to multiple stores.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9246)*

**Pull request merged**
