### PR TITLE
importccl: Preserve '\r\n' during CSV import

### PR DESCRIPTION
**Pull request by neeral**
See #25344.

### CODE REVIEW

**Review by neeral — COMMENTED** [review]
some of the lint rules are failing because of imported code. e.g. you don't need to check for errors on `Write` or `Flush` because you call `Error` immediately afterwards. This is the semantics of how the csv writer is designed. How can ask the linter to ignore these?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28181#-:-LIs1b6ZDEikj9Z_2hC-:b-n2k8vv)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by benesch** [comment]
Can you post the output of the failed lint rule? I'm not seeing it in the failed TeamCity job.

**Review by neeral — COMMENTED** [review]
@benesh this is the link to TC lint job: 
https://teamcity.cockroachdb.com/viewLog.html?buildTypeId=Cockroach_UnitTests_Check&buildId=810996&branch_Cockroach_UnitTests_Check=28181

```
[/TestUnused] lint_test.go:879: /go/src/github.com/cockroachdb/cockroach/pkg/util/encoding/csv/reader.go:85:2: var ErrTrailingComma is unused (U1000)
lint_test.go:879: /go/src/github.com/cockroachdb/cockroach/pkg/util/encoding/csv/reader.go:134:2: field TrailingComma is unused (U1000)

[23:49:08][TestLint] /TestErrCheck
[23:49:08]

[/TestErrCheck] lint_test.go:1145: pkg/util/encoding/csv/example_test.go:121:12:	w.WriteAll(records) // calls Flush internally <- unchecked error
lint_test.go:1145: pkg/util/encoding/csv/writer.go:103:11:	w.w.Flush() <- unchecked error
lint_test.go:1145: pkg/util/encoding/csv/writer_test.go:69:9:	f.Write([]string{"abc"}) <- unchecked error
lint_test.go:1145: pkg/util/encoding/csv/writer_test.go:78:9:	f.Write([]string{"abc"}) <- unchecked error

[/TestForbiddenImports] lint_test.go:1031: 
	github.com/cockroachdb/cockroach/pkg/util/encoding/csv: log <- please use "util/log" instead of "log"
```

The Unused variables is easy to remove.
The ErrCheck rule conflicts with the semantics of write/flush.
Use of `log` package means adding contexts. 

I don't want to change this stdlib code more than I have to, as it will make it hard to maintain. I'm open to suggestions on how you normally handle this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28181#-:-LIt-DqFAcpqy2_rpVeh:b-4o0h7t)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by neeral — COMMENTED** [review]
The job ran on revision1 of this PR - in case the line numbers don't align with the current version. I tried to fix some of these but did a bad job.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28181#-:-LIt0KGc0oblNZImOqfS:by7zaiy)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by neeral — COMMENTED** [review]
I've added test case for this in `pkg/ccl/importccl/import_stmt_test.go`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28181#-:-LIvkIB22Gs9SKbapxoJ:bdycd8n)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by benesch** [comment]
To suppress the errcheck warnings, I'd be OK with you adding `-ignorepkg pkg/util/encoding/csv` to the errcheck invocation here: https://github.com/cockroachdb/cockroach/blob/2e4952db490337eb7b769eda6ecee5b23a98fb05/pkg/testutils/lint/lint_test.go#L1133

**Comment by dt** [comment]
I too would be fine with exempting from linters to minimize diff from stdlib, but also LGTM as-is. Thanks!

**Review by dt — APPROVED** [review]

**Review by benesch — CHANGES_REQUESTED** [review]
I’d rather not list `(*bufio.Writer).Flush` in errcheck_excludes. It’s not in general safe to ignore its error. It’s only safe here because encoding/csv knows that it can find that error later by calling `w.Write(nil)`. Which actually seems like an undocumented implementation detail to rely on; but whatever, parity with the stdlib definitely wins here.

**Review by neeral — COMMENTED** [review]
`-ignorepkg` doesn't do what we thought. `-ignorepkg ./pkg/util/encoding/csv` doesn't work - need to do `-ignorepkg bufio` which defeats the purpose of what we want to do.

https://github.com/kisielk/errcheck
> The -ignorepkg flag takes a comma-separated list of package import paths to ignore

It's not which packages to ignore when running the checks.

If you are both happy with this, could @benesh or @dt give an LGTM and trigger bors?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28181#-:-LIwRrjc2eZFXVObfC0q:bcbv67a)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/importccl/import_stmt_test.go, line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28181#-LIvkV052MyZmKnjJwWd:-LIvkV052MyZmKnjJwWe:b8p64sn) ([raw file](https://github.com/cockroachdb/cockroach/blob/67ffc7e7143aa23972783fe13e82c6be12e637f5/pkg/ccl/importccl/import_stmt_test.go#L179)):*
> ```Go
> 			create: `t text`,
> 			typ:    "CSV",
> 			data:   "\"hello\r\nworld\"\n\"friend\nfoe\"\n\"mr\rmrs\"",
> ```

Is this the correct way to handle this?

**Comment by benesch** [comment]
D’oh, sorry to lead you astray. Your approach is definitely the lesser poison. Leaving to @dt to answer your other question and merge.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28181)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/importccl/import_stmt_test.go, line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28181#-LIvkV052MyZmKnjJwWd:-LIwUeW01cA8kw6GRDbL:bu45ptb) ([raw file](https://github.com/cockroachdb/cockroach/blob/67ffc7e7143aa23972783fe13e82c6be12e637f5/pkg/ccl/importccl/import_stmt_test.go#L179)):*
<details><summary><i>Previously, neeral (Neeral Dodhia) wrote…</i></summary><blockquote>

Is this the correct way to handle this?
</blockquote></details>

Yeah, looks right to me! It might be a little easier to read using backticks rather than escaping all the quotes, but not enough to justify another CI cycle.

**Review by neeral — COMMENTED** [review]
@dt could you give an LGTM, bors is complaining no one has approved this PR

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28181#-:-LIwYo9GAqkZdl4ytjIU:b-j9vl3m)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by benesch — APPROVED** [review]

**Comment by benesch** [comment]
Sorry, my review was in the way.

bors r+

**Comment by benesch** [comment]
Thanks for the fix, @neeral!

**Pull request merged**
