### PR TITLE
storage, ui: add a problem range state of raft log size too large

### PR DESCRIPTION
**Pull request by taku-k**
When a raft log grows too large, it can cause numerous problems.
It would be good to notify users of a problem replica which has
too large log through admin UI.

See #27709

Release note (admin ui change): show the number of replicas which have
too large log in the problem ranges report

### CODE REVIEW

**Review by couchand — CHANGES_REQUESTED** [review]
Thanks for the contribution, this looks helpful.  I mostly looked at the UI parts, but it seems good generally.  It's likely @BramGruneir will have useful feedback.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28034#-:-LIg5fPID8IjZeKBH5mG:bpp6gcy)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/server/serverpb/status.proto, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28034#-LIg4WVZ9R5OWuHkWqXw:-LIg4WVZ9R5OWuHkWqXx:bdvrko2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d2c7c3359249401ef0d1284d17bd9f470c127f8/pkg/server/serverpb/status.proto#L147)):*
> ```protobuf
>   bool quiescent_equals_ticking = 6;
> 
>   bool log_too_large = 7;
> ```

It would probably be helpful to add a little comment here describing this problem.
___
*[pkg/storage/replica.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28034#-LIg4er37ZZwJqO149M-:-LIg4er37ZZwJqO149M0:bykzy8g) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d2c7c3359249401ef0d1284d17bd9f470c127f8/pkg/storage/replica.go#L98)):*
> ```Go
> 	defaultReplicaRaftMuWarnThreshold = 500 * time.Millisecond
> 
> 	raftLogTooLargeSize = 1 << 20
> ```

I suspect we will want to make this threshold configurable, I'll leave suggesting the exact mechanism to use to one of the core devs.
___
*[pkg/storage/replica_test.go, line 8791 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28034#-LIg5-Rs8IRE-GrKDe31:-LIg5-Rs8IRE-GrKDe32:b-17213t) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d2c7c3359249401ef0d1284d17bd9f470c127f8/pkg/storage/replica_test.go#L8791)):*
> ```Go
> 		expected    ReplicaMetrics
> 	}{
> 		// The leader of a 1-replica range is up and log size is too large.
> ```

It would probably be cleaner to give this it's own test case in this list rather than adding it to this entry.
___
*[pkg/ui/src/views/reports/containers/problemRanges/connectionsTable.tsx, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28034#-LIg5EKN7EuBW-v9T5UZ:-LIg5EKN7EuBW-v9T5U_:bxb8qir) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d2c7c3359249401ef0d1284d17bd9f470c127f8/pkg/ui/src/views/reports/containers/problemRanges/connectionsTable.tsx#L46)):*
> ```XML
>   },
>   {
>     title: "Raft log too large size",
> ```

Suggest just "Raft log too large"

**Review by BramGruneir — CHANGES_REQUESTED** [review]
Thanks for doing this!

Let some comments and there also needs to be work done in `pkg/ui/src/views/reports/containers/range/rangeTable.tsx`.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28034#-:-LIgL5m7Cv2jgxHLBQRO:b-6ui97y)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/server/serverpb/status.proto, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28034#-LIg4WVZ9R5OWuHkWqXw:-LIgJtbc57T28IoZxzsv:b80jed6) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d2c7c3359249401ef0d1284d17bd9f470c127f8/pkg/server/serverpb/status.proto#L147)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

It would probably be helpful to add a little comment here describing this problem.
</blockquote></details>

Also, rename this to raft_log_too_large, just to be explicit.
___
*[pkg/server/serverpb/status.proto, line 529 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28034#-LIgK0pY2r68pnz6BzdJ:-LIgK0pY2r68pnz6BzdK:bn930ru) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d2c7c3359249401ef0d1284d17bd9f470c127f8/pkg/server/serverpb/status.proto#L529)):*
> ```protobuf
>           "github.com/cockroachdb/cockroach/pkg/roachpb.RangeID"
>     ];
>     repeated int64 log_size_too_large_range_ids = 8 [
> ```

please rename to `raft_log_too_large_range_ids`
___
*[pkg/storage/replica.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28034#-LIg4er37ZZwJqO149M-:-LIgKnCQ-GhKqx5-jYo6:b-u1af0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d2c7c3359249401ef0d1284d17bd9f470c127f8/pkg/storage/replica.go#L98)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

I suspect we will want to make this threshold configurable, I'll leave suggesting the exact mechanism to use to one of the core devs.
</blockquote></details>

Please use 4x the `raftLogMaxSize` from `raft_log_queue.go`.

**Review by taku-k — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28034)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/server/serverpb/status.proto, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28034#-LIg4WVZ9R5OWuHkWqXw:-LIpV-gt9QLuF4TLMWTy:b-bnegue) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d2c7c3359249401ef0d1284d17bd9f470c127f8/pkg/server/serverpb/status.proto#L147)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Also, rename this to raft_log_too_large, just to be explicit.
</blockquote></details>

Renamed to `raft_log_too_large` and added the comment
___
*[pkg/server/serverpb/status.proto, line 529 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28034#-LIgK0pY2r68pnz6BzdJ:-LIpVKVi-upmC80jcmCp:b-huk6lu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d2c7c3359249401ef0d1284d17bd9f470c127f8/pkg/server/serverpb/status.proto#L529)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

please rename to `raft_log_too_large_range_ids`
</blockquote></details>

Renamed to `raft_log_too_large_range_ids`
___
*[pkg/storage/replica.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28034#-LIg4er37ZZwJqO149M-:-LIpVNYzBthODzXMMRL-:bqdkyjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d2c7c3359249401ef0d1284d17bd9f470c127f8/pkg/storage/replica.go#L98)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Please use 4x the `raftLogMaxSize` from `raft_log_queue.go`. 
</blockquote></details>

Used 4x the `raftLogMaxSize`
___
*[pkg/storage/replica_test.go, line 8791 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28034#-LIg5-Rs8IRE-GrKDe31:-LIpVSny4M5cXvNnoXAC:b-9wbi1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d2c7c3359249401ef0d1284d17bd9f470c127f8/pkg/storage/replica_test.go#L8791)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

It would probably be cleaner to give this it's own test case in this list rather than adding it to this entry.
</blockquote></details>

Added own test caes
___
*[pkg/ui/src/views/reports/containers/problemRanges/connectionsTable.tsx, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28034#-LIg5EKN7EuBW-v9T5UZ:-LIpVYBzEuuZIAzuVEho:buy3vgk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d2c7c3359249401ef0d1284d17bd9f470c127f8/pkg/ui/src/views/reports/containers/problemRanges/connectionsTable.tsx#L46)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

Suggest just "Raft log too large"
</blockquote></details>

Changed to "Raft log too large"

**Review by BramGruneir — APPROVED** [review]
:lgtm: There was a little code that I think was from some other work on abort spans that should be removed and a suggestion for a comment.

> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28034#-:-LIso2J19GGw_rwlq23s:b-mcjism)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/server/serverpb/status.proto, line 149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28034#-LIsmp6i9dSniq-nxwQk:-LIsmp6i9dSniq-nxwQl:b-b5msc0) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf18a27134504eda1431bca23ee56c303c2e26d9/pkg/server/serverpb/status.proto#L149)):*
> ```protobuf
>   bool quiescent_equals_ticking = 6;
> 
>   // When raft has too large log, it can cause numerous problems.
> ```

Small grammar error here.  Perhaps reword as:
When the raft log it too large, it can be a symptom of other issues.
___
*[pkg/storage/replica.go, line 5990 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28034#-LIsnVHG57fgMZKE2ky8:-LIsnVHG57fgMZKE2ky9:b-jaa523) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d2c7c3359249401ef0d1284d17bd9f470c127f8/pkg/storage/replica.go#L5990)):*
> ```Go
> 		// this check in that case.
> 		if ba.IsTransactionWrite() || ba.Txn.Writing {
> 			// If the request is asking to abort the transaction, then don't check the
> ```

These changes about the abort span seem unrelated.   Please remove them and issue another PR for them.

**Review by couchand — APPROVED** [review]
> Reviewed 6 of 8 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28034)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by taku-k** [comment]
@BramGruneir, @couchand Thank you for your reviews. Could you merge this pr?

**Comment by BramGruneir** [comment]
one minor grammar issue that was my fault, please update it and I'll merge.  Thanks for much for this PR!

**Comment by BramGruneir** [comment]
___
*[pkg/server/serverpb/status.proto, line 149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28034#-LIsmp6i9dSniq-nxwQk:-LJJzAGw19Qb8J0mvSRa:b-2bt5t9) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf18a27134504eda1431bca23ee56c303c2e26d9/pkg/server/serverpb/status.proto#L149)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Small grammar error here.  Perhaps reword as:
When the raft log it too large, it can be a symptom of other issues.
</blockquote></details>

Ah, my fault, should have been is not it.  Please update to:
When the raft log is too large, it can be a symptom of other issues.

**Review by BramGruneir — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28034)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by taku-k** [comment]
@BramGruneir ah, I didn't notice it. I fixed it. Thanks.

**Review by BramGruneir — APPROVED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28034)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
