### PR TITLE
github: update CODEOWNERS for product-security team

### PR DESCRIPTION
**Pull request by pritesh-lahoti**
This PR updates code ownership for the `product-security` team. This team is responsible for all the customer-facing security features (AuthN, AuthZ, Network Security, etc.).

Release note: None

### CODE REVIEW

**Review by souravcrl — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128447#-:-O3ggzdFBCy2ksDmxqYg:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @BabuSrithar and @pritesh-lahoti)

___
*[`.github/CODEOWNERS` line 381 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128447#-O3gg-Nm574TT0SRuv_U:-O3gg-NnE2nArdGzsp-6:blgqigm) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f4ea65431d69e6d33d98fcb57a92504e75718f9/.github/CODEOWNERS#L381)):*
> ```CODEOWNERS
> /pkg/ccl/cmdccl/clusterrepl/ @cockroachdb/disaster-recovery
> /pkg/ccl/gqpccl/             @cockroachdb/sql-queries-prs
> #!/pkg/ccl/gssapiccl/        @cockroachdb/unowned
> ```

we should own this.

**Review by pritesh-lahoti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128447)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @BabuSrithar and @souravcrl)

___
*[`.github/CODEOWNERS` line 381 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128447#-O3gg-Nm574TT0SRuv_U:-O3gqFuLDzyY7sO6TB7g:b-qjpp0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f4ea65431d69e6d33d98fcb57a92504e75718f9/.github/CODEOWNERS#L381)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

we should own this.
</blockquote></details>

Absolutely! Thank you for catching.

**Review by souravcrl — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128447)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @BabuSrithar and @pritesh-lahoti)

___
*[`.github/CODEOWNERS` line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128447#-O3kd4sG3zH6yy7-7azw:-O3kd4sG3zH6yy7-7azx:bdn695b) ([raw file](https://github.com/cockroachdb/cockroach/blob/07a91bd9c7b88ed7949d2e2e1865e26cd0dfc560/.github/CODEOWNERS#L91)):*
> ```CODEOWNERS
> /pkg/sql/pg_catalog.go       @cockroachdb/sql-foundations
> /pkg/sql/pgwire/             @cockroachdb/sql-foundations @cockroachdb/server-prs
> /pkg/sql/pgwire/auth.go      @cockroachdb/sql-foundations @cockroachdb/server-prs @cockroachdb/prodsec @cockroachdb/prodsec-eng
> ```

Some more to consider will be `pkg/sql/pgwire/auth_behaviors.go` `pkg/sql/pgwire/auth_methods.go` `pkg/sql/pgwire/auth_test.go` `pkg/sql/pgwire/authenticator.go`  `pkg/sql/pgwire/authpipe_test.go`  `pkg/sql/pgwire/hba_conf.go`  `pkg/sql/pgwire/ident_map_conf.go` `pkg/sql/pgwire/role_mapper.go`. Would it be better to have partial ownership for pwgire?

**Review by pritesh-lahoti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128447)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @BabuSrithar and @souravcrl)

___
*[`.github/CODEOWNERS` line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128447#-O3kd4sG3zH6yy7-7azw:-O3koy-X61aVCTdbLfhX:b-awes68) ([raw file](https://github.com/cockroachdb/cockroach/blob/07a91bd9c7b88ed7949d2e2e1865e26cd0dfc560/.github/CODEOWNERS#L91)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

Some more to consider will be `pkg/sql/pgwire/auth_behaviors.go` `pkg/sql/pgwire/auth_methods.go` `pkg/sql/pgwire/auth_test.go` `pkg/sql/pgwire/authenticator.go`  `pkg/sql/pgwire/authpipe_test.go`  `pkg/sql/pgwire/hba_conf.go`  `pkg/sql/pgwire/ident_map_conf.go` `pkg/sql/pgwire/role_mapper.go`. Would it be better to have partial ownership for pwgire?
</blockquote></details>

Right, makes sense to add ownership at the pgwire level. Thank you for the suggestions!

**Comment by pritesh-lahoti** [comment]
TFTR!
bors r=souravcrl

**Pull request merged**
