### PR TITLE
roachprod: ability to manage ssh keys from command line

### LINKED ISSUE #90104: roachprod: SSH Key Management in GCP
Currently, `roachprod` in GCP is used in conjunction with project metadata to store [1], distribute SSH public keys, as well as provision and deprovision corresponding user accounts [2]. The project metadata contains a key, `ssh-keys` (not to be confused with `sshKeys` which was deprecated circa 2019) whose value, encoded as JSON dictionary, is a set of tuples of the form `{user}:{public_key}`. (Optionally, each tuple can also contain `expireOn` to denote key's TTL.) The (encoded) size of `ssh-keys` cannot exceed 256KB [3].

Recently, we have reached the aforementioned limit for `ssh-keys` in the default GCP project used by `roachprod`,
```
Value for 'metadata.items[2] is too large: maximum size 262144 character(s); actual size 262281.
```

The following are the top-3 users by the number of the corresponding ssh keys,
```
182 roach
126 root
66 agent
```

This finding prompted an investigation into SSH key management by `roachprod` and uncovered several areas of improvement,

- temporary SSH keys created while running in CI, namely `roach` and `agent` must be GCed
- SSH keys for `root` must be wiped (for security reasons, `root` login is forbidden)
- `ConfigSSH` [4] can result in a corrupted `~/.ssh.config` when multiple instances of `roachprod` are executing concurrently

[1] https://cloud.google.com/compute/docs/connect/add-ssh-keys#metadata
[2] https://github.com/GoogleCloudPlatform/guest-agent#account-management
[3] https://cloud.google.com/compute/docs/metadata/setting-custom-metadata#limitations
[4] https://github.com/cockroachdb/cockroach/blob/master/pkg/roachprod/vm/gce/gcloud.go#L375

Jira issue: CRDB-20584
Epic: CRDB-10428

### PR DESCRIPTION
**Pull request by renatolabs**
This PR adds a few commands to `roachprod` to make it easier to inspect the current set of keys added to clusters managed by roachprod; and to add and remove keys from that set. Previously, this task required either memorizing cryptic `gcloud` commands or using the Console UI. Neither option was convenient.

The PR introduces the `roachprod ssh-keys` command, along with the following subcommands: `list`, `add`, and `remove`. See documentation for each command for more information.

These commands should allow us to change the location where these keys are stored in the future (if desired) without us having to make any user-visible API change -- we'd just need to change the implementation behind these commands.

Closes: #90104

### CODE REVIEW

**Comment by renatolabs** [comment]
I ran `roachprod ssh-keys remove agent` and `roachprod ssh-keys remove roach` to reduce the number of SSH keys in the project metadata from 446 to 67 (thanks to the changes in #119106).

Once we merge this branch, we can close the longstanding #90104 issue. I also plan to announce this change more broadly for awareness so that hopefully people are able to fix their access independently.

**Comment by renatolabs** [comment]
```console
% roachprod ssh-keys list
[...]

TOTAL: 39257 bytes (usage: 14%)
```

We're now at 14% of the available project metadata storage space.

**Review by srosenberg — APPROVED** [review]
Very nice, thanks for adding these! `roachprod ssh-keys list` is already my favorite command; it's so much faster (and more convenient) than having to go through the console :)

**Comment by renatolabs** [comment]
TFTR!

bors r=srosenberg

**Pull request merged**
