### PR TITLE
sql: decrease cardinality of `__moreN__`

### LINKED ISSUE #86320: improve limitation for unique fingerprints collected with different IN sizes
We have users creating 1M rows on statement_statistics very quickly (e.g.a day) and part of this is because we're creating different fingerprints for selects that only have the amount of parameters inside a `IN()` as their difference. 
We should consider these type of statement as the same, to improve the cardinality.

Jira issue: CRDB-18696

### PR DESCRIPTION
**Pull request by maryliag**
When removing literals from statements we are
replacing with `__moreN__`.
With P as number of parameters, previously
N would be log10 of P * the most significant digit,
e.g.
p = 1 -> n = 1
p = 9 -> n = 9
p = 11 -> n = 10
p = 234 -> n = 200

Now we're reducing the bucket sizes, so now we have
0 < p <= 10    -> n = 1_10
10 < p <= 100  -> n = 10_100
100 < p <= 1000 -> follow the same rules as previously,
                   so p = 120 -> n = 100
                      p = 586 -> n = 500
p >= 1000       -> n = 1000_plus

Fixes #86320

Release justification: high impact change to improve cardinality
of fingerprint
Release note (sql change): Decreasing the cardinality of
the number on `__moreN__` when replacing literals.

### CODE REVIEW

**Review by knz — CHANGES_REQUESTED** [review]
Instead of removing the logic altogether, have you considered reducing the number of buckets instead?

The origin of the arity indicator is an actual use case: when an app issues e.g. INSERT statements with various VALUES clause sizes, it's useful to use different fingerprints for the different sizes.

That's because the execution time (and thus the stats) are averaged across all statements with the same fingerprint.

It's meaningless to compute the average of an INSERT of 1 value and an INSERT of 10000 values. The resulting performance metric is bogus!

My preference would be to modify the `arityString()` function to reduce the number of buckets. Currently it's  using
- 1 separate bucket for each counts below 10
- then, 1 bucket per log10 of the count. (but separate buckets for, say, 20 and 30 buckets).

I think you could get a lot of mileage by:

1) using just 1 bucket for all counts below 10
2) using just 1 bucket for all counts between 10 and 100
3) all counts between 100 and 1000
4) then just 1 bucket for all counts above 1000

(you can add some buckets between 3 and 4 -- the point is to not go all the way to 15 buckets for MaxInt64)

What do you think?

**Comment by maryliag** [comment]
@knz I made the changes to create the buckets and added the names to signify that. 
Hopefully that is enough level of details to see the case you want, but also doesn't cause problems with the high cardinality some users are having! :) 

(Just need to update tests now)

**Review by knz — COMMENTED** [review]
Try to make the generated string a valid lowercase identifier, so that the pretty-printing doesn't need to use double quotes.

**Comment by maryliag** [comment]
Done!

**Review by knz — APPROVED** [review]
thanks!

**Comment by maryliag** [comment]
TFTR!
bors r+

**Pull request merged**
