### PR TITLE
engine: iterate in-mem SSTs without copying

### PR DESCRIPTION
**Pull request by dt**
Release note (performance change): reduce memory usage during bulk ingestion of data (during IMPORT, RESTORE, and index creation).

### CODE REVIEW

**Review by danhhz — COMMENTED** [review]
:lgtm: nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36394#-:-LbPZGrU-X2adO44P7DR:b-7yytuz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz, @dt, @jordanlewis, and @lucy-zhang)

___
*[pkg/storage/engine/sst_iterator.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36394#-LbPXtWHAsWSR9lAB9Tf:-LbPXtWHAsWSR9lAB9Tg:bb4nozs) ([raw file](https://github.com/cockroachdb/cockroach/blob/717320deb692f72452e6be6b2b416a05359f2dd3/pkg/storage/engine/sst_iterator.go#L76)):*
> ```Go
> }
> 
> func (_ memFileInfo) IsDir() bool {
> ```

I usually see this as `(memFileInfo)`

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36394)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @lucy-zhang)

___
*[pkg/storage/engine/sst_iterator.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36394#-LbPXtWHAsWSR9lAB9Tf:-LbQ7QTxDLCmCniK34ff:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/717320deb692f72452e6be6b2b416a05359f2dd3/pkg/storage/engine/sst_iterator.go#L76)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I usually see this as `(memFileInfo)`
</blockquote></details>

Done

**Review by dt — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36394#-:-LbQ7WNv9WhCGfJY6LEt:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @lucy-zhang)

**Pull request merged**
