### PR TITLE
plpgsql: coerce types for PLpgSQL expressions

### LINKED ISSUE #112809: plpgsql: add correct type-checking + coercion
PLpgSQL expressions in postgres are coerced to the desired type, whether that be the variable type for an assignment, or the function return type for a RETURN statement. The process (described [here](https://www.postgresql.org/docs/current/plpgsql-statements.html#PLPGSQL-STATEMENTS-ASSIGNMENT)) is as follows:
1. If an assignment cast exists, simply cast to the desired type.
2. Otherwise, convert the expression to text, and then attempt to convert the result to the desired type.

This issues tracks adding correct type-coercion for PLpgSQL expressions. We also need to be able to infer the concrete return type for a RECORD-returning function; right now, that case results in an internal error:
```
(XX000) internal error: unexpected error from the vectorized engine: error decoding 11 bytes: couldn't decode type ANYELEMENT
statement ok
CREATE FUNCTION f() RETURNS RECORD AS $$
  BEGIN
    RETURN (1, 'foo', true);
  END
$$ LANGUAGE PLpgSQL;
```

Jira issue: CRDB-32607

### PR DESCRIPTION
**Pull request by DrewKimball**
#### plpgsql: correctly type the dummy expression for EOF

Previously, the end-of-function error logic attempted to project a
typed NULL to ensure consistent typing for PLpgSQL routines that have
non-terminating branches. However, I forgot to to add this projection
as a body statement of the EOF error continuation routine. This patch
fixes that oversight, and adds tests to verify correct typing.

Informs #112809

Release note: None

#### plpgsql: coerce PLpgSQL expressions to the expected type

This patch adds type-coercion for PLpgSQL expressions. If an assignment
cast exists for the required conversion, the expression is casted directly
to the required type. Otherwise, the expression is casted to a string,
which is parsed as the required type. It is possible for this to fail,
since there is no guarantee that the string format of an expression can
be parsed as a given type.

Informs #112809

Release note: None

#### plpgsql: correctly handle RECORD-returning PLpgSQL routines

This patch fixes type-checking and inference for RECORD-returning
PLpgSQL routines. Previously, the actual return type of a routine call
was not updated when the call was built, which could lead to internal
errors because the `AnyTuple` data type is only valid during planning.
The concrete return type for a RECORD-returning PLpgSQL routine is now
inferred by examining the `RETURN` statements, and correctly set when
building the callsite. Note that unlike postgres, we require that the
return statements are all either NULL, or otherwise have identical
types.

Fixes #112809

Release note: None

### CODE REVIEW

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112816)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/logictest/testdata/logic_test/plpgsql_record` line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112816#-NhXO9yZ2e_3dcNwOf60:-NhXO9yZ2e_3dcNwOf61:b-dp0159) ([raw file](https://github.com/cockroachdb/cockroach/blob/4edf1cd23a467a9b2b97bc69f66bc38fa59746c6/pkg/sql/logictest/testdata/logic_test/plpgsql_record#L1)):*
> ```
> # LogicTest: !local-mixed-23.1
> ```

Could use the following test coverage:
* return multiple elements in the RECORD tuple
* Tests like `SELECT * FROM f()` (I think this should just work, but it would be good to verify).
* The failure cases, i.e., RETURN statement types don't match in the function, RETURN statement type not a tuple

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112816)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/logictest/testdata/logic_test/plpgsql_record` line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112816#-NhXO9yZ2e_3dcNwOf60:-NhkH7a30mFUY6o4HCL2:ba110s8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4edf1cd23a467a9b2b97bc69f66bc38fa59746c6/pkg/sql/logictest/testdata/logic_test/plpgsql_record#L1)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Could use the following test coverage:
* return multiple elements in the RECORD tuple
* Tests like `SELECT * FROM f()` (I think this should just work, but it would be good to verify).
* The failure cases, i.e., RETURN statement types don't match in the function, RETURN statement type not a tuple
</blockquote></details>

Good ideas. I found a bug while adding these: https://github.com/cockroachdb/cockroach/issues/113186
They also caught a bug that prevented catching invalid non-tuple return types for the first RETURN statement.

**Comment by DrewKimball** [comment]
@mgartner @rharding6373 friendly ping. The issue(s) this fixes should probably be a ga-blocker.

**Comment by DrewKimball** [comment]
TODO: check which of the pg_regress issues related to PLpgSQL are fixed by this.

**Review by mgartner — CHANGES_REQUESTED** [review]
Great job tracking down and matching some interesting behavior!

> Reviewed 15 of 15 files at r4, 3 of 3 files at r5, 15 of 15 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112816#-:-NkMpzPqEgp4AGuSt0xf:bqo6sxx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @rharding6373)

___
*[`-- commits` line 22 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/112816#-NkMkYOT8Jd0AWJpRh0x):*
It's weird that in Postgres the behavior for PLpgSQL functions here differs from SQL functions which must have a valid assignment cast and do not allow this string-format casting. From [the docs](https://www.postgresql.org/docs/current/xfunc-sql.html#XFUNC-SQL-BASE-FUNCTIONS):

> If the final `SELECT` or `RETURNING` clause in an SQL function does not return exactly the function's declared result type, PostgreSQL will automatically cast the value to the required type, if that is possible with an implicit or assignment cast. Otherwise, you must write an explicit cast.

```
marcus=# CREATE FUNCTION f() RETURNS INT LANGUAGE SQL AS $$ SELECT '1'::CHAR $$;
ERROR:  42P13: return type mismatch in function declared to return integer
DETAIL:  Actual return type is character.
CONTEXT:  SQL function "f"
LOCATION:  check_sql_fn_retval, functions.c:1756
```

:shrug: 

Is the behavior for PLpgSQL described in the docs anywhere? All I could find was [this sentence](https://www.postgresql.org/docs/current/plpgsql-control-structures.html#PLPGSQL-STATEMENTS-RETURNING) which fails to mention anything but the normal assignment cast behavior:

> In a function that returns a scalar type, the expression's result will automatically be cast into the function's return type as described for assignments.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 1278 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/112816#-NkMlhSS4jp0r2oHyz_M:-NkMlhSS4jp0r2oHyz_N:b5sqnqu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dc4808ff096e85a2e1d9f4a44895a65f8eee8b6/pkg/sql/opt/optbuilder/plpgsql.go#L1278)):*
> ```Go
> 			scalar = b.ob.factory.ConstructCast(scalar, types.String)
> 		}
> 		scalar = b.ob.factory.ConstructCast(scalar, typ)
> ```

We should explain why we use `ConstructCast` and not `ConstructAssignmentCast` here. The behavior of the two are different.

Cast `TEXT` to `CHAR`:

```
defaultdb> SELECT 'foo'::TEXT::CHAR;
  bpchar
----------
  f
```

Assignment cast `TEXT` to `CHAR`:

```
defaultdb> CREATE TABLE t (c CHAR);
CREATE TABLE

defaultdb> INSERT INTO t VALUES ('foo'::TEXT);
ERROR: value too long for type CHAR
SQLSTATE: 22001
```

I presume that you need the behavior of the explicit cast to match Postgres's behavior for cases below like:

```
DROP FUNCTION f();
CREATE OR REPLACE FUNCTION f() RETURNS CHAR AS $$
  BEGIN
    RETURN 'abcd'::TEXT;
  END
$$ LANGUAGE PLpgSQL;

query T
SELECT f();
----
a
``
```

___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 2507 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/112816#-NkMive7EhKb9_Gzh-zm:-NkMive83gyr4-HWAQrj:b-kgidmn) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dc4808ff096e85a2e1d9f4a44895a65f8eee8b6/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L2507)):*
> ```
> a
> 
> # TODO(drewk): postgres doesn't truncate the values.
> ```

This is odd behavior for Postgres. I would expect an error, like it does when performing a similar assignment cast for an insert:

```
marcus=# CREATE TABLE t (c CHAR);
CREATE TABLE

marcus=# INSERT INTO t VALUES ('foo'::TEXT);
ERROR:  22001: value too long for type character(1)
LOCATION:  bpchar, varchar.c:311
```

:shrug:

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112816)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`-- commits` line 22 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/112816#-NkMkYOT8Jd0AWJpRh0x):*
[Here's](https://www.postgresql.org/docs/current/plpgsql-statements.html#PLPGSQL-STATEMENTS-ASSIGNMENT) a snippet for variable assignment:
>If the expression's result data type doesn't match the variable's data type, the value will be coerced as though by an assignment cast (see [Section 10.4](https://www.postgresql.org/docs/current/typeconv-query.html "10.4. Value Storage")). If no assignment cast is known for the pair of data types involved, the PL/pgSQL interpreter will attempt to convert the result value textually, that is by applying the result type's output function followed by the variable type's input function. Note that this could result in run-time errors generated by the input function, if the string form of the result value is not acceptable to the input function.

Some tests (and IIRC, some code reading) seem to confirm that this applies to expressions returned from PLpgSQL as well:
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 1278 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/112816#-NkMlhSS4jp0r2oHyz_M:-NkN9J4eAcICjwL4WxFc:b-rvq2a4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dc4808ff096e85a2e1d9f4a44895a65f8eee8b6/pkg/sql/opt/optbuilder/plpgsql.go#L1278)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

We should explain why we use `ConstructCast` and not `ConstructAssignmentCast` here. The behavior of the two are different.

Cast `TEXT` to `CHAR`:

```
defaultdb> SELECT 'foo'::TEXT::CHAR;
  bpchar
----------
  f
```

Assignment cast `TEXT` to `CHAR`:

```
defaultdb> CREATE TABLE t (c CHAR);
CREATE TABLE

defaultdb> INSERT INTO t VALUES ('foo'::TEXT);
ERROR: value too long for type CHAR
SQLSTATE: 22001
```

I presume that you need the behavior of the explicit cast to match Postgres's behavior for cases below like:

```
DROP FUNCTION f();
CREATE OR REPLACE FUNCTION f() RETURNS CHAR AS $$
  BEGIN
    RETURN 'abcd'::TEXT;
  END
$$ LANGUAGE PLpgSQL;

query T
SELECT f();
----
a
``
```

</blockquote></details>

I'm thinking now that we should use assignment casts after all, and error out for these "too long" cases even though postgres doesn't. It's not clear how to exactly match postgres even if we don't error, since they don't truncate for some reason:
```
CREATE OR REPLACE FUNCTION f() RETURNS CHAR AS $$
  BEGIN
    RETURN 'abcd'::TEXT;
  END
$$ LANGUAGE PLpgSQL;
DROP FUNCTION
CREATE FUNCTION
postgres=# SELECT f();
  f
------
 abcd
(1 row)
```
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 2507 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/112816#-NkMive7EhKb9_Gzh-zm:-NkN7SRYDV8XfYvb8WQp:b-3skqmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dc4808ff096e85a2e1d9f4a44895a65f8eee8b6/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L2507)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This is odd behavior for Postgres. I would expect an error, like it does when performing a similar assignment cast for an insert:

```
marcus=# CREATE TABLE t (c CHAR);
CREATE TABLE

marcus=# INSERT INTO t VALUES ('foo'::TEXT);
ERROR:  22001: value too long for type character(1)
LOCATION:  bpchar, varchar.c:311
```

:shrug:
</blockquote></details>

Maybe it would be best if we did throw an error for this sort of thing, since it does seem likely to be a bug in Postgres... It's definitely odd behavior.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112816)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`-- commits` line 22 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/112816#-NkMkYOT8Jd0AWJpRh0x):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[Here's](https://www.postgresql.org/docs/current/plpgsql-statements.html#PLPGSQL-STATEMENTS-ASSIGNMENT) a snippet for variable assignment:
>If the expression's result data type doesn't match the variable's data type, the value will be coerced as though by an assignment cast (see [Section 10.4](https://www.postgresql.org/docs/current/typeconv-query.html "10.4. Value Storage")). If no assignment cast is known for the pair of data types involved, the PL/pgSQL interpreter will attempt to convert the result value textually, that is by applying the result type's output function followed by the variable type's input function. Note that this could result in run-time errors generated by the input function, if the string form of the result value is not acceptable to the input function.

Some tests (and IIRC, some code reading) seem to confirm that this applies to expressions returned from PLpgSQL as well:
</blockquote></details>

Here's a code comment talking about it a bit (and a function call you can follow): https://github.com/postgres/postgres/blob/e722846daf4a37797ee39bc8ca3e78a4ef437f51/src/pl/plpgsql/src/pl_exec.c#L7856-L7870
```
		 * Apply coercion.  We use the special coercion context
		 * COERCION_PLPGSQL to match plpgsql's historical behavior, namely
		 * that any cast not available at ASSIGNMENT level will be implemented
		 * as an I/O coercion.  (It's somewhat dubious that we prefer I/O
		 * coercion over cast pathways that exist at EXPLICIT level.  Changing
		 * that would cause assorted minor behavioral differences though, and
		 * a user who wants the explicit-cast behavior can always write an
		 * explicit cast.)
```

**Review by rharding6373 — COMMENTED** [review]
Sorry for letting this sit for so long :-/

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112816#-:-NkXWvu49-psmtvV8WBW:b-8aa27d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/logictest/testdata/logic_test/plpgsql_record` line 339 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/112816#-NkXKWwp7WVMVA3QkbmH:-NkXKWwp7WVMVA3QkbmI:bqwpte4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f85dc63e08ede5fe79ea0de2743d3151e2387c56/pkg/sql/logictest/testdata/logic_test/plpgsql_record#L339)):*
> ```
> $$ LANGUAGE PLpgSQL;
> 
> statement error pgcode 42804 pq: unable to infer type for RECORD-returning routine
> ```

This function and the next succeed in postgres (as do calling them). This is the case even if the branches return records with different number of values. It seems like fixing this behavior would be difficult given the exec engine needs to have a precise type and we don't know what type it will be until execution time, but maybe we should have an unsupported error code instead in the meantime?
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 2507 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/112816#-NkMive7EhKb9_Gzh-zm:-NkXNQnG3b_kDuPtUiUz:b-6rsj9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dc4808ff096e85a2e1d9f4a44895a65f8eee8b6/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L2507)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Maybe it would be best if we did throw an error for this sort of thing, since it does seem likely to be a bug in Postgres... It's definitely odd behavior.
</blockquote></details>

But `SELECT ('foo'::TEXT)::CHAR;` succeeds in postgres (though it truncates to `f`).

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112816)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 2507 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/112816#-NkMive7EhKb9_Gzh-zm:-NkX_H_QB42ik1YahUDb:bp3uyel) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dc4808ff096e85a2e1d9f4a44895a65f8eee8b6/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L2507)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

But `SELECT ('foo'::TEXT)::CHAR;` succeeds in postgres (though it truncates to `f`).
</blockquote></details>

That's an explicit cast, we should have the same behavior for that (success + truncation). The weird behavior happens with coercing the type of a PLpgSQL expression specifically.

**Comment by DrewKimball** [comment]
I've opened an issue to track the difference in truncation behavior for values that are too wide: https://github.com/cockroachdb/cockroach/issues/115385

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112816)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 1278 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/112816#-NkMlhSS4jp0r2oHyz_M:-NkYDsiu91RvesDvH7cI:b-sepim1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dc4808ff096e85a2e1d9f4a44895a65f8eee8b6/pkg/sql/opt/optbuilder/plpgsql.go#L1278)):*
>We should explain why we use `ConstructCast` and not `ConstructAssignmentCast` here. The behavior of the two are different.

I added a comment explaining this.
___
*[`pkg/sql/logictest/testdata/logic_test/plpgsql_record` line 339 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/112816#-NkXKWwp7WVMVA3QkbmH:-NkYBe4f3TAvTDZgGyQC:b-34uxia) ([raw file](https://github.com/cockroachdb/cockroach/blob/f85dc63e08ede5fe79ea0de2743d3151e2387c56/pkg/sql/logictest/testdata/logic_test/plpgsql_record#L339)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

This function and the next succeed in postgres (as do calling them). This is the case even if the branches return records with different number of values. It seems like fixing this behavior would be difficult given the exec engine needs to have a precise type and we don't know what type it will be until execution time, but maybe we should have an unsupported error code instead in the meantime?
</blockquote></details>

Sure, I opened #115384 to track it.

**Review by mgartner — APPROVED** [review]
:lgtm: Nice work!

> Reviewed 17 of 17 files at r7, 3 of 3 files at r8, 15 of 15 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112816#-:-NkqFRi1DrNfnkyh48Jl:bcmw7ss)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @rharding6373)

___
*[`-- commits` line 22 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/112816#-NkMkYOT8Jd0AWJpRh0x):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Here's a code comment talking about it a bit (and a function call you can follow): https://github.com/postgres/postgres/blob/e722846daf4a37797ee39bc8ca3e78a4ef437f51/src/pl/plpgsql/src/pl_exec.c#L7856-L7870
```
		 * Apply coercion.  We use the special coercion context
		 * COERCION_PLPGSQL to match plpgsql's historical behavior, namely
		 * that any cast not available at ASSIGNMENT level will be implemented
		 * as an I/O coercion.  (It's somewhat dubious that we prefer I/O
		 * coercion over cast pathways that exist at EXPLICIT level.  Changing
		 * that would cause assorted minor behavioral differences though, and
		 * a user who wants the explicit-cast behavior can always write an
		 * explicit cast.)
```
</blockquote></details>

Thanks. Linking to these things in the commit message or a comment would be useful for future code archaeologists.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 1278 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/112816#-NkMlhSS4jp0r2oHyz_M:-NkqEPI59Hlq4_Ohq-uW:b-rjd6oy) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dc4808ff096e85a2e1d9f4a44895a65f8eee8b6/pkg/sql/opt/optbuilder/plpgsql.go#L1278)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

>We should explain why we use `ConstructCast` and not `ConstructAssignmentCast` here. The behavior of the two are different.

I added a comment explaining this.
</blockquote></details>

I'm hoping it comes up infrequently, so this looks good as-is.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 1281 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/112816#-NkqF-D89koGG3QVazBk:-NkqF-D89koGG3QVazBl:b-5b2lh0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7be9b1b4e877f010eedff3b54cc7cc762c06fd53/pkg/sql/opt/optbuilder/plpgsql.go#L1281)):*
> ```Go
> 		// coercion, but instead performs the cast without truncation. Using an
> 		// explicit cast, we also allow narrowing type coercion, but with
> 		// truncation. This difference is tracked in #115384.
> ```

nit: Did you mean  #115385 here?

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112816)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`-- commits` line 22 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/112816#-NkMkYOT8Jd0AWJpRh0x):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Thanks. Linking to these things in the commit message or a comment would be useful for future code archaeologists.
</blockquote></details>

Good idea, I added them to the commit message.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 1281 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/112816#-NkqF-D89koGG3QVazBk:-NkqJxWa78Hh6hbBq8Bk:bulzyxe) ([raw file](https://github.com/cockroachdb/cockroach/blob/7be9b1b4e877f010eedff3b54cc7cc762c06fd53/pkg/sql/opt/optbuilder/plpgsql.go#L1281)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Did you mean  #115385 here?
</blockquote></details>

Yes, thanks for catching that. Done.

**Review by rharding6373 — APPROVED** [review]
:lgtm: Great!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112816#-:-NkqRhnt7FvipQ_T1QqF:bioon7n)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 17 of 17 files at r10, 2 of 3 files at r11, 16 of 16 files at r13, 15 of 15 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112816#-:-NkrKLIL6UnJtuOkA2yz:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

**Comment by DrewKimball** [comment]
TFTRs!

**Comment by DrewKimball** [comment]
The bors failure looks the same as the one from #109033.

bors retry

**Pull request merged**
