### PR TITLE
rangefeed: remove non-muxrangefeed code

### LINKED ISSUE #125666: rangefeed: remove non-mux rangefeed code entirely
**Describe the problem**

In 24.1, to simplify the implementation of https://github.com/cockroachdb/cockroach/issues/110432, we removed any cluster
setting for enabling non-mux rangefeeds, making them always enabled. But we
retained the non-mux rangefeed code there for test coverage in mixed-version
clusters. Given that we are going to 24.2, we are now more comfortable with 
removing the tests and deprecating non-mux rangefeed code entirely. 

Jira issue: CRDB-39543

### PR DESCRIPTION
**Pull request by wenyihu6**
In 22.2, mux rangefeeds were introduced to reduce the number of rpc streams from
one per replica to one per client for all rangefeeds on a node.

In 24.1, to simplify the implementation of https://github.com/cockroachdb/cockroach/issues/110432, we removed any cluster
setting for enabling non-mux rangefeeds, making them always enabled. But we
retained the non-mux rangefeed code there for test coverage in mixed-version
clusters. Given that we are going to 24.2, we are now more comfortable with removing
the tests. This patch completely removes client and server code for non-mux
rangefeed.

Resolves: #125666
Release note: none

### CODE REVIEW

**Comment by wenyihu6** [comment]
The first three commits are from https://github.com/cockroachdb/cockroach/pull/125665.

**Comment by wenyihu6** [comment]
We shouldn't need to worry about mixed version tests here since they were covered during the removal process in v24.1 https://github.com/cockroachdb/cockroach/blob/d8073b58467ddb4c5b2ebe4a485fc42fb98f7200/pkg/cmd/roachtest/tests/mixed_version_cdc.go#L422-L431.

**Comment by wenyihu6** [comment]
@nvanbenschoten Tagging for visibility since this one was out of order in the list of PRs I made. This is the final PR that will close the issue.

**Comment by wenyihu6** [comment]
@nvanbenschoten (Didn't mean to rush the review) Tagging here to ensure this PR isn’t overlooked since it was out of order from the list of PRs I made.

**Comment by wenyihu6** [comment]
Friendly ping here : ) Lmk if we prefer to bake for a while before merging this pr.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125610#-:-O-ft7ZX2-lV8f3fi53v:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt)

**Comment by wenyihu6** [comment]
TFTR! 

bors r=nvanbenschoten

**Pull request merged**
