### PR TITLE
sql: add escape_string_warning session variable for compatibility

### PR DESCRIPTION
**Pull request by johnseekins**
Relates to #22937 

This makes it possible for Zabbix to successfully connect to CockroachDB.
See https://www.postgresql.org/docs/10/runtime-config-compatible.html#GUC-ESCAPE-STRING-WARNING

Release note (sql change): The `escape_string_warning` session variable from
PostgreSQL was added with compatibility-only support. It defaults to `on`
and cannot be changed.

### CODE REVIEW

**Comment by knz** [comment]
cc @rafiss for triage 

During the review please ensure:

- there is a proper commit title (there isn't one currently)
- the code follows the pattern from other session variables, instead of using an ad-hoc mechanism
- there's a URL in a comment to the pg doc that explains the setting

Also I'd recommend double-checking what this does in pg, and verify that ignoring the session var is not creating an incorrect signal to clients (i.e. if the session var exists to prevent certain problems, let's not ignore the session var and paper over the problem when it occurs)

**Comment by johnseekins** [comment]
Can anyone give me some suggestions on how to rename this ticket?

I can say that I:
1. definitely added comments pointing to PostgreSQL docs about the variable change.
2. used the pattern from another variable config to set this one, so the code shouldn't be adhoc in any way.

**Comment by rafiss** [comment]
@johnseekins Sorry, this fell of my todo list. I will give this a review now and give more details on the comments above.

**Review by rafiss — CHANGES_REQUESTED** [review]
thanks for your contribution!

can you make the commit *title*: `sql: add escape_string_warning session variable for compatibility`

and the message something more like this (note the line breaks):
```
Relates to #22937 

This makes it possible for Zabbix to successfully connect to CockroachDB.
See https://www.postgresql.org/docs/10/runtime-config-compatible.html#GUC-ESCAPE-STRING-WARNING

Release note (sql change): The `escape_string_warning` session variable from
PostgreSQL was added with compatibility-only support. It defaults to off
and cannot be changed.
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58870#-:-MS0-RUD8ODP6zMGIjaX:b-duycs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @johnseekins)

___
*[pkg/sql/vars.go, line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58870#-MS-zG5dAxblkOSLUzY0:-MS-zG5dAxblkOSLUzY1:b-oiet4u) ([raw file](https://github.com/cockroachdb/cockroach/blob/acaf5ab4b06e3f9adc3bd81b764e406718c96cfb/pkg/sql/vars.go#L138)):*
> ```Go
> 	},
> 
> 	// See https://www.postgresql.org/docs/10/runtime-config-compatible.html#GUC-ESCAPE-STRING-WARNING
> ```

can you add a comment saying "Supported for PG compatibility only."
___
*[pkg/sql/vars.go, line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58870#-MS-ybGPAK4BT_Eohbf_:-MS-ybGPAK4BT_Eohbfa:bnlxjcp) ([raw file](https://github.com/cockroachdb/cockroach/blob/acaf5ab4b06e3f9adc3bd81b764e406718c96cfb/pkg/sql/vars.go#L139)):*
> ```Go
> 
> 	// See https://www.postgresql.org/docs/10/runtime-config-compatible.html#GUC-ESCAPE-STRING-WARNING
> 	`escape_string_warning`: {
> ```

Currently, this always causes the value to be returned as "ON". i don't think that's what we want here, since this patch doesn't actually change any behavior. seems like it should be "off".

we have a special way that we implement "compatibility only" session variables. for example, take a look at "standard_conforming_strings"

for this patch, we'd want:
```
	`escape_string_warning`: makeCompatBoolVar(`standard_conforming_strings`, false, false /* anyAllowed */),
```

according to the PG docs, it seems like this setting only has any effect if `standard_conforming_strings` is set to `off`, and right now we only allow `standard_conforming_strings` to be `on`. so i guess it doesn't matter that much what we do with `escape_string_warning`. however, in the future, if we ever do decide to add full support for `standard_conforming_strings`, then it would be safer to make `escape_string_warning` remain `off` until we add full support for it too.

unless it is actually important for zabbix to be able to set this to both on and off?
___
*[pkg/sql/vars.go, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58870#-MS01t0MCWAWWRFu4Y5m:-MS01t0MCWAWWRFu4Y5n:bnyuhw1) ([raw file](https://github.com/cockroachdb/cockroach/blob/acaf5ab4b06e3f9adc3bd81b764e406718c96cfb/pkg/sql/vars.go#L151)):*
> ```Go
> 		Get:           func(evalCtx *extendedEvalContext) string { return "ON" },
> 		GlobalDefault: func(_ *settings.Values) string { return "ON" },
> 	},
> ```

you need to comment `"escape_string_warning"` in unsupported_vars.go now that it's supported here.

**Review by rafiss — COMMENTED** [review]
also, please rebase your branch on the latest `master` -- this PR should not have a merge commit in it

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58870#-:-MS03ZKH75KoiwegrhF8:b9g32nw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @johnseekins)

**Comment by johnseekins** [comment]
According to PostgreSQL docs, the setting actually defaults to `on`, which is what Zabbix expects to set it to.

**Comment by johnseekins** [comment]
I did comment out `escape_string_warning` in unsupported_vars.go, so that should be sorted.

**Comment by johnseekins** [comment]
I merged with master and did a rebase...but it seems to have added _all_ the commits between my initial commit and upstream master into my merge request?! I am...not good at git. I think the best plan here is to revoke this PR and re-submit...

**Comment by knz** [comment]
you should never "merge with master" on your feature branch in a repo that uses a rebase strategy.

If you choose to rebase, then that is the way to catch up with master. You do a rebase and that is sufficient.

**Pull request closed without merging**
