### PR TITLE
release-21.1: sql: use correct encoding type when creating unique index in ALTER PRIMARY KEY

### LINKED ISSUE #71552: sql: unique secondary index that used to be primary incorrectly uses PrimaryIndexEncoding in the descriptor on 21.1 and before
On 21.1 and prior version if we do this sequence of steps:
```
CREATE TABLE t (a INT PRIMARY KEY, b INT NOT NULL);
ALTER TABLE t ALTER PRIMARY KEY USING COLUMNS (b);
ALTER TABLE t ALTER PRIMARY KEY USING COLUMNS (a);
```
we will have 3 indexes total (a primary as well as two unique secondary indexes). If we examine the descriptor of `t_b_key` unique secondary index we will see that it's incorrectly thinking that it is using the PrimaryIndexEncoding
```
      {
          "columnDirections": [
              "ASC"
          ],
          "columnIds": [
              2
          ],
          "columnNames": [
              "b"
          ],
...
          "encodingType": 1,
          "extraColumnIds": [
              1
          ],
...
          "id": 5,
...
          "name": "t_b_key",
...
      }
```
Versions 21.2 and newer don't have this problem

### PR DESCRIPTION
**Pull request by postamar**
In versions 21.1 and earlier, the unique index sometimes created as
a side-effect of ALTER PRIMARY KEY could have the wrong encoding type
set. It could be set to the encoding type used for primary indexes,
instead of the one for secondary indexes such as these.

This commit fixes this bug at creation time, but does nothing for
any unique indexes that have already been created.

Partly fixes #71552.

Release justification: fix correctness bug

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
LGTM, but I don't know much about the versions and validations, so I'll defer to Andrew for approval.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72570#-:-Mo4OnrA5gkcH_VbWfic:b-9uh7jt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by postamar** [comment]
Thanks for taking a look @yuzefovich. Should I close https://github.com/cockroachdb/cockroach/issues/71552 once this merges? I don't see us taking any further action at this point.

**Comment by yuzefovich** [comment]
> Should I close #71552 once this merges? I don't see us taking any further action at this point.

IIUC the old descriptors with the incorrect encoding will exist forever (until the index is dropped), right? It sounds a bit wrong to me, but in any case I think it's up to the Schema team to decide.

**Comment by postamar** [comment]
Yes, they'll exist forever, unless perhaps someone adds a migration in 22.1 or a subsequent version which effectively forces the user to re-create the offending indexes, much like we recently did with interleaves. Right now I don't see a better alternative but I'll be happy to be proven wrong. It seems like a lot of trouble for something which in the end is quite benign.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72570#-:-MpI4AQk5mkTxNaTGqY0:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)

**Pull request merged**
