### PR TITLE
changefeedccl: Support enum columns in avro encoding

### PR DESCRIPTION
**Pull request by HonoreDB**
In the JSON encoder, enums are rendered as strings,
and if a type is altered, this is reflected in future messages
but doesn't backfill. Because a backfill would be nontrivial,
we're doing the same thing in the avro encoder rather than use
the Avro enum type.

Note that enums are not a built-in type and therefore not
hit in avro_test.go. I'm hoping to figure out how to fix that
before merging this commit, or as a followup.

Release note (bug fix): Enum columns can be encoded in avro changefeeds

### CODE REVIEW

**Review by miretskiy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65474)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @stevendanna)

___
*[pkg/ccl/changefeedccl/encoder.go, line 379 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65474#-Ma5aVaL2xTZ870AClUB:-Ma5aVaMAMlWRh-CYnQR:b-8hybzo) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ddb74d79eb5e43d353a6cc25af846ebda9142bf/pkg/ccl/changefeedccl/encoder.go#L379)):*
> ```Go
> 
> 	if ok {
> 		registered.schema.refreshTypeMetadata(row.tableDesc)
> ```

is there a way to avoid refreshing type metadata on every call?
___
*[pkg/ccl/changefeedccl/encoder.go, line 435 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65474#-Ma5b02G6_ajJShcn0Ra:-Ma5b02G6_ajJShcn0Rb:bcr48bf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ddb74d79eb5e43d353a6cc25af846ebda9142bf/pkg/ccl/changefeedccl/encoder.go#L435)):*
> ```Go
> 		e.valueCache[cacheKey] = registered
> 	}
> 	if ok {
> ```

same: do we have to refresh on every call?
___
*[pkg/ccl/changefeedccl/encoder_test.go, line 375 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65474#-Ma5avfR5lNuHdBIjy4t:-Ma5avfR5lNuHdBIjy4u:b-orh2ik) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ddb74d79eb5e43d353a6cc25af846ebda9142bf/pkg/ccl/changefeedccl/encoder_test.go#L375)):*
> ```Go
> }
> 
> func TestAvroEnum(t *testing.T) {
> ```

do we want to bench enum encoding performance?
___
*[pkg/ccl/changefeedccl/encoder_test.go, line 437 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65474#-Ma5aq9J6FnnaMydjuqT:-Ma5aq9J6FnnaMydjuqU:biuaex8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ddb74d79eb5e43d353a6cc25af846ebda9142bf/pkg/ccl/changefeedccl/encoder_test.go#L437)):*
> ```Go
> 
> 	t.Run(`sinkless`, sinklessTest(testFn))
> 	t.Run(`enterprise`, enterpriseTest(testFn))
> ```

you can after kafka test after rebase.

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65474)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @miretskiy)

___
*[pkg/ccl/changefeedccl/avro.go, line 837 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65474#-MaDXYdP1LuFDorc3BF0:-MaDXYdQByCZjfadY3jp:b-fv5f0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ddb74d79eb5e43d353a6cc25af846ebda9142bf/pkg/ccl/changefeedccl/avro.go#L837)):*
> ```Go
> }
> 
> // Refresh the metadata for user-defined types on a cached schema
> ```

Do we want to call out enum's in the comment here explicitly? That is, IIUC the only current reason we need to do this refresh is to pick up enum renames (since the "logical representation" is in the type returned by GetType()).
___
*[pkg/ccl/changefeedccl/encoder.go, line 379 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65474#-Ma5aVaL2xTZ870AClUB:-MaD_J9zEdveunl9eHQX:b-tvn4p5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ddb74d79eb5e43d353a6cc25af846ebda9142bf/pkg/ccl/changefeedccl/encoder.go#L379)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

is there a way to avoid refreshing type metadata on every call?
</blockquote></details>

Perhaps we could do something with the version on the TableDescriptor?

**Review by HonoreDB — COMMENTED** [review]
Was procrastinating on the "adding to avro_test" bit, but it didn't end up being _that_ awkward as there's already support for injecting a test semantic context. With that done it was easy to add benchmarks, which are fine: up to 5 allocs/op.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65474#-:-MaoYoHvEoGqN5oWm1kt:b-y54ebh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, and @stevendanna)

___
*[pkg/ccl/changefeedccl/avro.go, line 837 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65474#-MaDXYdP1LuFDorc3BF0:-MaoZDhUDIlkbDCDmer6:b-ld369a) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ddb74d79eb5e43d353a6cc25af846ebda9142bf/pkg/ccl/changefeedccl/avro.go#L837)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Do we want to call out enum's in the comment here explicitly? That is, IIUC the only current reason we need to do this refresh is to pick up enum renames (since the "logical representation" is in the type returned by GetType()).
</blockquote></details>

We also need it to pick up new enum values. Enums are actually the only user-defined type right now (since collated string types are just regenerated idempotently every time they're referenced); the intent in the code seems to be that any new user-defined type will also use the TypeMetadata field. Added a comment here to call this out and to make it clear this does nothing for most types.
___
*[pkg/ccl/changefeedccl/encoder.go, line 379 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65474#-Ma5aVaL2xTZ870AClUB:-Mao_mwe72_NKynx1VSJ:bqedk89) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ddb74d79eb5e43d353a6cc25af846ebda9142bf/pkg/ccl/changefeedccl/encoder.go#L379)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Perhaps we could do something with the version on the TableDescriptor?
</blockquote></details>

So, yeah. If we wanted to avoid calling refreshTypeMetadata, we have two options. We can use the version ids in the type object on the table descriptor to create a new cache key (not the table version itself, which doesn't change, which is why we're hitting cache at all). Or we could use the schema feed, which is where we're finding out about the enum changes in the first place, to trigger a refresh, but we'd still need to store multiple versions since we might get rows from before the change. The thing is I'm pretty sure both of those options have more per-row overhead than just doing the refresh every time! The refresh just iterates over a cached array of the enum columns on the table descriptor and sets a pointer for each one. To determine whether we need to do a refresh, we'd also be doing O(number of enum columns in this table) amount of work. So while it's possible there's a clever way to do this that I'm missing, it doesn't seem worth it performance-wise.

The argument I do see for doing one of those two things is that it would tell us when to update the avro schema version, which could be a way to signal to the client that even though our generated schema would be identical, a dependent type has changed elsewhere in the database. But I haven't heard anything to suggest that would be desirable.
___
*[pkg/ccl/changefeedccl/encoder_test.go, line 375 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65474#-Ma5avfR5lNuHdBIjy4t:-MaodL377ph7bwZ2_Fig:b-xj04r5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ddb74d79eb5e43d353a6cc25af846ebda9142bf/pkg/ccl/changefeedccl/encoder_test.go#L375)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

do we want to bench enum encoding performance?
</blockquote></details>

Done. 1613616	       773.7 ns/op	      81 B/op	       5 allocs/op
___
*[pkg/ccl/changefeedccl/encoder_test.go, line 437 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65474#-Ma5aq9J6FnnaMydjuqT:-MaodxwHEcx2ulU3gZRx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ddb74d79eb5e43d353a6cc25af846ebda9142bf/pkg/ccl/changefeedccl/encoder_test.go#L437)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

you can after kafka test after rebase.
</blockquote></details>

Done.

**Review by miretskiy — APPROVED** [review]
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65474)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, and @stevendanna)

___
*[pkg/ccl/changefeedccl/encoder.go, line 379 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65474#-Ma5aVaL2xTZ870AClUB:-Map3WgV79n5Y7o1uk-d:b7brox8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ddb74d79eb5e43d353a6cc25af846ebda9142bf/pkg/ccl/changefeedccl/encoder.go#L379)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

So, yeah. If we wanted to avoid calling refreshTypeMetadata, we have two options. We can use the version ids in the type object on the table descriptor to create a new cache key (not the table version itself, which doesn't change, which is why we're hitting cache at all). Or we could use the schema feed, which is where we're finding out about the enum changes in the first place, to trigger a refresh, but we'd still need to store multiple versions since we might get rows from before the change. The thing is I'm pretty sure both of those options have more per-row overhead than just doing the refresh every time! The refresh just iterates over a cached array of the enum columns on the table descriptor and sets a pointer for each one. To determine whether we need to do a refresh, we'd also be doing O(number of enum columns in this table) amount of work. So while it's possible there's a clever way to do this that I'm missing, it doesn't seem worth it performance-wise.

The argument I do see for doing one of those two things is that it would tell us when to update the avro schema version, which could be a way to signal to the client that even though our generated schema would be identical, a dependent type has changed elsewhere in the database. But I haven't heard anything to suggest that would be desirable.

</blockquote></details>

Let's go with what we have, unless proven otherwise.
___
*[pkg/ccl/changefeedccl/encoder_test.go, line 595 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65474#-Map3Al_8nHBLfWqpnON:-Map3Al_8nHBLfWqpnOO:bjcma13) ([raw file](https://github.com/cockroachdb/cockroach/blob/66b2e1d404d0672d0b09b98d702ba699d13895b8/pkg/ccl/changefeedccl/encoder_test.go#L595)):*
> ```Go
> 	t.Run(`sinkless`, sinklessTest(testFn))
> 	t.Run(`enterprise`, enterpriseTest(testFn))
> 	t.Run(`kafka`, enterpriseTest(testFn))
> ```

should it be `kafkaTest`?

**Comment by HonoreDB** [comment]
bors r=[miretskiy]

**Pull request merged**
