### PR TITLE
cli: Add "debug range-data" command

### PR DESCRIPTION
**Pull request by bdarnell**
"debug range-data" prints the contents of a range using `ReplicaDataIterator` (which is exported and cleaned up as a part of this PR), so it sees the same things that the consistency checker sees.

Improved coverage of the pretty-printer.

This PR was used in my last message on #7224.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7321)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 7 of 7 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: 7 of 11 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[cli/debug.go, line 163 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321#-KKfdbVvP8RO7onQdjme:-KKfdbVxHCiIiH-KQ5u1:1178093940) ([raw file](https://github.com/cockroachdb/cockroach/blob/92df26972305de544c164cdf39cd4caa6ebccd3b/cli/debug.go#L163)):*
> ```Go
> 	defer stopper.Stop()
> 
> 	if len(args) != 2 {
> ```

nit: this error will be difficult to parse in case of too many arguments

---

*[cli/debug.go, line 195 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321#-KKfcoCsBQjnj4EG9V4V:-KKfcoCta74oy61-sn59:790311940) ([raw file](https://github.com/cockroachdb/cockroach/blob/92df26972305de544c164cdf39cd4caa6ebccd3b/cli/debug.go#L195)):*
> ```Go
> 	}
> 
> 	return nil
> ```

not just `return iter.Error()`?

---

*[cli/debug.go, line 307 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321#-KKfeOmE7tG59x7Bktu2:-KKfeOmE7tG59x7Bktu3:2082968072) ([raw file](https://github.com/cockroachdb/cockroach/blob/92df26972305de544c164cdf39cd4caa6ebccd3b/cli/debug.go#L307)):*
> ```Go
> 		}
> 		if err := checkRangeDescriptorKey(kv.Key); err != nil {
> 			return false, nil
> ```

is this intentionally not returning `err`? could do with a comment

---

*[cli/debug.go, line 324 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321#-KKfd7Ebd9PAAStYiW8K:-KKfd7Ebd9PAAStYiW8L:866885926) ([raw file](https://github.com/cockroachdb/cockroach/blob/92df26972305de544c164cdf39cd4caa6ebccd3b/cli/debug.go#L324)):*
> ```Go
> 		return desc, nil
> 	}
> 	return roachpb.RangeDescriptor{}, fmt.Errorf("range descriptor not found")
> ```

nit: include rangeID in message

---

*[cli/debug.go, line 271 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321#-KKfeeYdHQK1Lf8KgXzi:-KKfeeYdHQK1Lf8KgXzj:-882810747) ([raw file](https://github.com/cockroachdb/cockroach/blob/11a7cfab64922be24dae69c9c91a0fc9bfca34c5/cli/debug.go#L271)):*
> ```Go
> func tryRangeIDKey(kv engine.MVCCKeyValue) (string, error) {
> 	if kv.Key.Timestamp != hlc.ZeroTimestamp {
> 		return "", fmt.Errorf("range ID keys shouldn't have timestamps")
> ```

should this log the key?

---

*[storage/replica_data_iter.go, line 154 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321#-KKfcHUPAfcSMvnqmc52:-KKfcHUPAfcSMvnqmc53:-1276165612) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f89a6391ba6c9e43ab57b1d4bea6f88f8095f45/storage/replica_data_iter.go#L154)):*
> ```Go
> // AllocIterKeyValue returns ri.Key() and ri.Value() with the underlying
> // storage allocated from the passed ByteAllocator.
> func (ri *replicaDataIterator) AllocIterKeyValue(
> ```

how come this bit was needed? it's only called from this package, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321#-:-KKff-OlFtH7m8sEXF-R:1417088721)*

**Comment by bdarnell** [comment]
Review status: 5 of 11 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[cli/debug.go, line 163 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321#-KKfdbVvP8RO7onQdjme:-KKhLl4PdNj70TaCZAyK:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/92df26972305de544c164cdf39cd4caa6ebccd3b/cli/debug.go#L163)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: this error will be difficult to parse in case of too many arguments
</details>
Done.

---

*[cli/debug.go, line 195 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321#-KKfcoCsBQjnj4EG9V4V:-KKhLoKsYX2XudUO2ghc:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/92df26972305de544c164cdf39cd4caa6ebccd3b/cli/debug.go#L195)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> not just `return iter.Error()`?
</details>
Done.

---

*[cli/debug.go, line 307 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321#-KKfeOmE7tG59x7Bktu2:-KKhM4lSXOYKf4iazHX2:-697028300) ([raw file](https://github.com/cockroachdb/cockroach/blob/92df26972305de544c164cdf39cd4caa6ebccd3b/cli/debug.go#L307)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> is this intentionally not returning `err`? could do with a comment
</details>
Added comment.

---

*[cli/debug.go, line 324 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321#-KKfd7Ebd9PAAStYiW8K:-KKhM8Rp3sZ3WOrRZqiD:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/92df26972305de544c164cdf39cd4caa6ebccd3b/cli/debug.go#L324)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: include rangeID in message
</details>
Done.

---

*[cli/debug.go, line 271 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321#-KKfeeYdHQK1Lf8KgXzi:-KKhLukz6wJv-gIbc69D:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/11a7cfab64922be24dae69c9c91a0fc9bfca34c5/cli/debug.go#L271)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> should this log the key?
</details>
Done.

---

*[storage/replica_data_iter.go, line 154 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321#-KKfcHUPAfcSMvnqmc52:-KKhMB8S4jEIlHEFwtNb:187763431) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f89a6391ba6c9e43ab57b1d4bea6f88f8095f45/storage/replica_data_iter.go#L154)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> how come this bit was needed? it's only called from this package, right?
</details>
Unexported. The caller could have reached in to `ri.iterator` but I'd rather hide that behind a method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 2 of 2 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321)*

**Comment by petermattis** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 7 of 7 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, 1 of 1 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[cli/debug.go, line 316 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321#-KKi6VJKY7t1mWyai7GH:-KKi6VJKY7t1mWyai7GI:593549012) ([raw file](https://github.com/cockroachdb/cockroach/blob/92df26972305de544c164cdf39cd4caa6ebccd3b/cli/debug.go#L316)):*
> ```Go
> 
> 	start := engine.MakeMVCCMetadataKey(keys.LocalRangePrefix)
> 	end := engine.MakeMVCCMetadataKey(keys.LocalRangeMax)
> ```

This could use a comment explaining that range descriptors are indexed by their start key but we're trying to find a range descriptor given a range ID. 

---

*[keys/printer.go, line 135 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321#-KKi6rJOdj7FQGygh2Dm:-KKi6rJPvFAIChqy8bzL:1733760467) ([raw file](https://github.com/cockroachdb/cockroach/blob/85bd1661199250472d6126bca9e558ec0c87f7b6/keys/printer.go#L135)):*
> ```Go
> 		{name: "RaftHardState", suffix: localRaftHardStateSuffix},
> 		{name: "RaftAppliedIndex", suffix: LocalRaftAppliedIndexSuffix},
> 		{name: "LeaseAppliedIndex", suffix: LocalLeaseAppliedIndexSuffix},
> ```

Add a test case to `printer_test.go`. 

---

*[storage/replica_data_iter.go, line 101 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321#-KKi5hWd5qKydQSYCyoo:-KKi5hWeBrsXQxldODmz:812320889) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f89a6391ba6c9e43ab57b1d4bea6f88f8095f45/storage/replica_data_iter.go#L101)):*
> ```Go
> 
> // Seek seeks to the specified key.
> func (ri *replicaDataIterator) Seek(key engine.MVCCKey) {
> ```

`Seek`is part of the `engine.Iterator` interface. Seems fine to remove, but now the comment about `replicaDataIterator` implementing the `engine.Iterator` interface is inaccurate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321#-:-KKi7E8TidARROVtrkPJ:1417088721)*

**Comment by bdarnell** [comment]
Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[cli/debug.go, line 316 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321#-KKi6VJKY7t1mWyai7GH:-KKiAgsb-BiDpH73c4jf:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/92df26972305de544c164cdf39cd4caa6ebccd3b/cli/debug.go#L316)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> This could use a comment explaining that range descriptors are indexed by their start key but we're trying to find a range descriptor given a range ID. 
</details>
Done.

---

*[keys/printer.go, line 135 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321#-KKi6rJOdj7FQGygh2Dm:-KKiArcVWar6K3uJZcgU:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/85bd1661199250472d6126bca9e558ec0c87f7b6/keys/printer.go#L135)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Add a test case to `printer_test.go`. 
</details>
Done.

---

*[storage/replica_data_iter.go, line 101 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321#-KKi5hWd5qKydQSYCyoo:-KKiAunyNE7-TmIRjptH:-1023496709) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f89a6391ba6c9e43ab57b1d4bea6f88f8095f45/storage/replica_data_iter.go#L101)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `Seek`is part of the `engine.Iterator` interface. Seems fine to remove, but now the comment about `replicaDataIterator` implementing the `engine.Iterator` interface is inaccurate.
</details>
The comment now claims to implement a subset of the interface. This implementation of `Seek` never really worked correctly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321)*

**Comment by petermattis** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/replica_data_iter.go, line 101 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321#-KKi5hWd5qKydQSYCyoo:-KKiCCf4fafI8pnZ4UQ4:1916368910) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f89a6391ba6c9e43ab57b1d4bea6f88f8095f45/storage/replica_data_iter.go#L101)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> The comment now claims to implement a subset of the interface. This implementation of `Seek` never really worked correctly.
</details>
Oops, misread the direction of the comment change. Carry on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321)*

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 7 of 7 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 2 of 2 files at r9, 11 of 11 files at r10, 1 of 1 files at r11, 7 of 7 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, 3 of 3 files at r15, 2 of 2 files at r16, 1 of 1 files at r17, 2 of 2 files at r18.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[cli/debug.go, line 301 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321#-KKiGLb8SFQSCf5_PJVP:-KKiGLb8SFQSCf5_PJVQ:588463347) ([raw file](https://github.com/cockroachdb/cockroach/blob/92df26972305de544c164cdf39cd4caa6ebccd3b/cli/debug.go#L301)):*
> ```Go
> ) (roachpb.RangeDescriptor, error) {
> 	var desc roachpb.RangeDescriptor
> 	handleKV := func(kv engine.MVCCKeyValue) (bool, error) {
> ```

Doesn't look like this will correctly handle a RangeDescriptor with an intent on it?

---

*[cli/debug.go, line 153 \[r13\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321#-KKiHGYrXUXQfIWfUKVC:-KKiHGYrXUXQfIWfUKVD:2064753971) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab3eefffd61c4f241ab877ec8e2857f51c3ea64f/cli/debug.go#L153)):*
> ```Go
> 	Short: "dump all the data in a range",
> 	Long: `
> Pretty-prints all keys and values in a range. This includes all data convered
> ```

s/con/cov/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321#-:-KKiHqfJO7GZxmlDrQGN:1417088721)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[cli/debug.go, line 301 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321#-KKiGLb8SFQSCf5_PJVP:-KKiI2qXuvE3f7-lszPM:1503873872) ([raw file](https://github.com/cockroachdb/cockroach/blob/92df26972305de544c164cdf39cd4caa6ebccd3b/cli/debug.go#L301)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Doesn't look like this will correctly handle a RangeDescriptor with an intent on it?
</details>
It'll return the last committed value. Since transactions that manipulate range descriptors are always local to that range descriptor we should never see an intent on a descriptor for a committed transaction. That's a questionable "should" in light of the current issues, but I'm not sure what we could do better. We only really need this to find the range boundaries. 

---

*[cli/debug.go, line 153 \[r13\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321#-KKiHGYrXUXQfIWfUKVC:-KKiIt0WgCtYfWo21fM0:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab3eefffd61c4f241ab877ec8e2857f51c3ea64f/cli/debug.go#L153)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> s/con/cov/
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7321)*

**Comment by jseldess** [comment]
`debug` command is not in client-facing docs, but I've added `docs-todo` for future reference.

**Pull request merged**
