### PR TITLE
sql: add query level stats to EXPLAIN ANALYZE

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change adds top-level query stats to the EXPLAIN ANALYZE output.

Release note (sql change): EXPLAIN ANALYZE now shows more top-level
query statistics.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
I am unsure of the max-memory and network usage stats. Do we think these are currently robust enough to be useful? I could hide them behind the `VERBOSE` flag if not.

**Comment by awoods187** [comment]
Could you post some examples for the issue?

> I am unsure of the max-memory and network usage stats. Do we think these are currently robust enough to be useful?
I'd vote in favor of adding them to Explain Analyze.

**Comment by RaduBerinde** [comment]
Example:
```
demo@127.0.0.1:26257/movr> EXPLAIN ANALYZE SELECT * FROM rides JOIN vehicles ON rides.vehicle_id
= vehicles.id; 
                    info
--------------------------------------------
  planning time: 530µs
  execution time: 5ms
  distribution: full
  vectorized: true
  rows read from KV: 515 (89 KiB)
  cumulative time spent in KV: 3ms
  maximum memory usage: 566 KiB
  network usage: 0 B (0 messages)

  • hash join
  │ actual row count: 500
  │ equality: (vehicle_id) = (id)
  │
  ├── • scan
  │     actual row count: 500
  │     KV rows read: 500
  │     KV bytes read: 86 KiB
  │     missing stats
  │     table: rides@primary
  │     spans: FULL SCAN
  │
  └── • scan
        actual row count: 15
        KV rows read: 15
        KV bytes read: 2.3 KiB
        missing stats
        table: vehicles@primary
        spans: FULL SCAN

  WARNING: this statement is experimental!
(30 rows)

Time: 6ms total (execution 5ms / network 0ms)
```

> I'd vote in favor of adding them to Explain Analyze.

Any thoughts on whether any of it should be VERBOSE-only?

**Comment by awoods187** [comment]
I love it! I'd vote to keep them in EXPLAIN ANALYZE and not in a verbose only mode.

**Review by asubiotto — CHANGES_REQUESTED** [review]
I'm in agreement with Andy. It might not be useful in some cases but I think it's better to show more than less information (users might not even know there is a verbose mode) and iterate from there if we get negative feedback.

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60641#-:-MTjmvqQCb8t0XZbdStM:bds2343)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/explain_plan.go, line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60641#-MTjnhJx6q27GwivwPpH:-MTjnhJx6q27GwivwPpI:b-nkateg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4ea2ec5f5d7149b09ae20ade78066dde8336242/pkg/sql/explain_plan.go#L174)):*
> ```Go
> 
> 	if explainPlan == nil {
> 		return errors.New("no plan")
> ```

Is there enough context to understand this error?
___
*[pkg/sql/instrumentation.go, line 262 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60641#-MTjo3HjBNXNR7yUaOq2:-MTjo3HjBNXNR7yUaOq3:b-sjmz5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4ea2ec5f5d7149b09ae20ade78066dde8336242/pkg/sql/instrumentation.go#L262)):*
> ```Go
> 			stmtStats.mu.Unlock()
> 		}
> 		txnStats.Accumulate(queryLevelStats)
> ```

I'm not sure we want to call `Accumulate` outside the block. Might lead to cases where stats don't add up in the DB console (i.e. one statement in a txn has nil stmt stats but what was collected is reflected in the txn stats).
___
*[pkg/sql/logictest/testdata/logic_test/explain_analyze, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60641#-MTjoZ4r0eOULS3CeGE5:-MTjoZ4r0eOULS3CeGE6:b-ke9sa) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4ea2ec5f5d7149b09ae20ade78066dde8336242/pkg/sql/logictest/testdata/logic_test/explain_analyze#L39)):*
> ```
> distribution: <hidden>
> vectorized: <hidden>
> rows read from KV: 3 (24 B)
> ```

Are the bytes values deterministic?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60641)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/explain_plan.go, line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60641#-MTjnhJx6q27GwivwPpH:-MTlWpFq6tyW1CmqC0LT:b-afhsq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4ea2ec5f5d7149b09ae20ade78066dde8336242/pkg/sql/explain_plan.go#L174)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is there enough context to understand this error?
</blockquote></details>

We are checking at a higher level, this is a "just in case" check (I ran into a NPE while working on this change). In general, no plan means that there was an error during planning. Changed to an `AssertionFailedf`.
___
*[pkg/sql/instrumentation.go, line 262 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60641#-MTjo3HjBNXNR7yUaOq2:-MTlXEjL0xBYqo2TV8WQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4ea2ec5f5d7149b09ae20ade78066dde8336242/pkg/sql/instrumentation.go#L262)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm not sure we want to call `Accumulate` outside the block. Might lead to cases where stats don't add up in the DB console (i.e. one statement in a txn has nil stmt stats but what was collected is reflected in the txn stats).
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/explain_analyze, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60641#-MTjoZ4r0eOULS3CeGE5:-MTlXFLcEGqJ4gtLLjHO:b-ru7asd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4ea2ec5f5d7149b09ae20ade78066dde8336242/pkg/sql/logictest/testdata/logic_test/explain_analyze#L39)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Are the bytes values deterministic?
</blockquote></details>

Yeah, 8 per row

**Review by RaduBerinde — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60641#-:-MTqHhFOBjmyh7KReWnO:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

**Pull request merged**
