### PR TITLE
sql: add CONTROLCHANGEFEED role option

### PR DESCRIPTION
**Pull request by solongordon**
Fixes #52869

Release note (sql change): Introduced a new CONTROLCHANGEFEED role
option. This grants non-admin roles the ability to create new
changefeeds, as long as they have SELECT privileges on the target table.
It can be conferred via `ALTER ROLE <role> CONTROLCHANGEFEED` and
revoked via `ALTER ROLE <role> NOCONTROLCHANGEFEED`.

### CODE REVIEW

**Review by RichardJCai — CHANGES_REQUESTED** [review]
ALTER ROLE <role> NOCONTROLCHANGEFEED to revoke instead of ALTER ROLE <role> CONTROLCHANGEFEED in the commit message

> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52869#-:-MEyqQK6-nkDjFGbUOQ1:b-14ag3s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea, @RichardJCai, and @solongordon)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 2002 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52869#-MEypW7S6nyHrP1G-jyZ:-MEypW7S6nyHrP1G-jy_:b2e78zl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7de5270105e6654a7ba7d8e311205da7cb8cea7/pkg/ccl/changefeedccl/changefeed_test.go#L2002)):*
> ```Go
> 			stmt = `CREATE CHANGEFEED FOR d.foo`
> 		}
> 		privErr := `user testuser does not have CONTROLCHANGEFEED privilege`
> ```

Does it make sense to turn this function into a logic test?
___
*[pkg/sql/authorization.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52869#-MEyp_3EB-2_HkkgM3kE:-MEyp_3EB-2_HkkgM3kF:brk77uk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7de5270105e6654a7ba7d8e311205da7cb8cea7/pkg/sql/authorization.go#L70)):*
> ```Go
> 	// HasRoleOption converts the roleoption to its SQL column name and checks if
> 	// the user belongs to a role where the roleprivilege has value true. Only
> 	// works on checking the "positive version" of the privilege. Requires a valid
> ```

I updated this in my PR but "positive version" doesn't actually make sense. I changed the function header to
// HasRoleOption converts the roleoption to it's SQL column name and
// checks if the user belongs to a role where the roleprivilege has value true.
// Requires a valid transaction to be open.
// This check should be done on the version of the privilege that is stored in
// the role options table.
// Example: CREATEROLE instead of NOCREATEROLE. NOLOGIN instead of LOGIN.

but didn't add it to the AuthorizationAccessor interface so I think it'll have to be updated here as well.
___
*[pkg/sql/parser/sql.y, line 6252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52869#-MEyptfH2UFfuxDdo0E6:-MEyptfH2UFfuxDdo0E7:b-5v1lty) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7de5270105e6654a7ba7d8e311205da7cb8cea7/pkg/sql/parser/sql.y#L6252)):*
> ```Yacc
> | NOCONTROLCHANGEFEED
> 	{
> 		$$.val = tree.KVOption{Key: tree.Name($1), Value: nil}
> ```

tabs here, I also just noticed NOCREATEROLE, LOGIN and NOLOGIN are tab spaced as well.

I need to change my goland to convert tabs to spaces for the .y file format as well

**Review by solongordon — COMMENTED** [review]
Oops, fixed the release note.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52869#-:-MF0nPCz3s-mtkrCf0W4:b-n6chv8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea and @RichardJCai)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 2002 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52869#-MEypW7S6nyHrP1G-jyZ:-MF0r7r8BrVfMQ_zv2o4:b2xgkm1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7de5270105e6654a7ba7d8e311205da7cb8cea7/pkg/ccl/changefeedccl/changefeed_test.go#L2002)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Does it make sense to turn this function into a logic test?
</blockquote></details>

That seems like a reasonable improvement. Done.
___
*[pkg/sql/authorization.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52869#-MEyp_3EB-2_HkkgM3kE:-MF0nsM19FezH5_P1eL8:bdow6an) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7de5270105e6654a7ba7d8e311205da7cb8cea7/pkg/sql/authorization.go#L70)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I updated this in my PR but "positive version" doesn't actually make sense. I changed the function header to
// HasRoleOption converts the roleoption to it's SQL column name and
// checks if the user belongs to a role where the roleprivilege has value true.
// Requires a valid transaction to be open.
// This check should be done on the version of the privilege that is stored in
// the role options table.
// Example: CREATEROLE instead of NOCREATEROLE. NOLOGIN instead of LOGIN.

but didn't add it to the AuthorizationAccessor interface so I think it'll have to be updated here as well.
</blockquote></details>

Yeah, I'll fix this once I rebase on your CONTROLJOB PR.
___
*[pkg/sql/parser/sql.y, line 6252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52869#-MEyptfH2UFfuxDdo0E6:-MF0oP0M9yilR5hG7GfP:bjye2xj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7de5270105e6654a7ba7d8e311205da7cb8cea7/pkg/sql/parser/sql.y#L6252)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

tabs here, I also just noticed NOCREATEROLE, LOGIN and NOLOGIN are tab spaced as well.

I need to change my goland to convert tabs to spaces for the .y file format as well 
</blockquote></details>

Ack, you infected me! I'll do a find/replace on this whole part of the file.

**Review by RichardJCai — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52869#-:-MFBdHXaDQQAhaB7Gxs4:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea and @RichardJCai)

**Pull request merged**
