### PR TITLE
opt: add rule to decorrelate union operators

### PR DESCRIPTION
**Pull request by DrewKimball**
#### opt: improve EnsureKey custom function

This commit makes a small improvement to the `EnsureKey` custom function
(used in decorrelation rules), so that it can add passthrough columns to
a `Project` operator in an effort to find a key. This can prevent rules
from adding unnecessary `Ordinality` operators to the query plan.

Epic: None

Release note: None

#### opt: improve exists subquery hoisting

This commit makes a small improvement to the subquery-hoisting rules so
that hoisting an `EXISTS` subquery can often avoid projecting a new
column to check for NULL values. This can allow other optimization rules
to match later on.

Epic: None

Release note: None

#### opt: add rule to decorrelate unions in EXISTS subqueries

This commit adds a new rule `TryDecorrelateUnion`, which matches on a
`Union` or `UnionAll` operator in the input of a `ScalarGroupBy`. The
`ScalarGroupBy` must have "any-not-null" semantics, meaning it produces
an arbitrary non-null value from each input column.

If these conditions are satisfied, the `Union` operator is replaced by an
`InnerJoin` between two `ScalarGroupBy` operators. A `Project` coalesces
columns from each side of the join to produce the final aggregated values.

This transformation does not itself decorrelate the `Union` operators, but
it does make it easier for other rules to do so.

Release note: None

Epic: None

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: Very nice!!!

> Reviewed 6 of 6 files at r1, 10 of 10 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131141#-:-O8CtErn3CZZqPlK5Tz6:b-9nehqv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/opt/norm/rules/decorrelate.opt` line 410 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131141#-O8CrzHv-HBSFeuhA3to:-O8CrzHv-HBSFeuhA3tp:b-1ty5si) ([raw file](https://github.com/cockroachdb/cockroach/blob/2653bec36b4ac2fe807c2d975648b7d559621d32/pkg/sql/opt/norm/rules/decorrelate.opt#L410)):*
> ```
> 
> # TryDecorrelateUnion replaces a Union/UnionAll beneath a ScalarGroupBy with an
> # InnerJoin between two ScalarGroupBy operators. A Project operator coalesces
> ```

It's really a cross-join isn't it? A diagram of the transformation in this comment, either in an abbreviated opt plan format or SQL, might be helpful in explaining the rule, but up to you.
___
*[`pkg/sql/opt/norm/testdata/rules/decorrelate` line 7595 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131141#-O8CsfD3EviyxNtP-zBe:-O8CsfD3EviyxNtP-zBf:b8370wt) ([raw file](https://github.com/cockroachdb/cockroach/blob/2653bec36b4ac2fe807c2d975648b7d559621d32/pkg/sql/opt/norm/testdata/rules/decorrelate#L7595)):*
> ```
>  │              └── j
>  └── projections
>       └── CASE WHEN COALESCE("?column?", "?column?") IS NOT NULL THEN 1 ELSE 0 END
> ```

nit: I realize it'll blow up the size of these plans, but a more verbose output might be nice, e.g., to see that the correct columns are coalesced here.

**Review by DrewKimball — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131141#-:-O8E7PEnCUEW0gxfZrPB:b-814g8k)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/opt/norm/rules/decorrelate.opt` line 410 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131141#-O8CrzHv-HBSFeuhA3to:-O8DhFjJ0kkZhwtodc1N:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2653bec36b4ac2fe807c2d975648b7d559621d32/pkg/sql/opt/norm/rules/decorrelate.opt#L410)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It's really a cross-join isn't it? A diagram of the transformation in this comment, either in an abbreviated opt plan format or SQL, might be helpful in explaining the rule, but up to you.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/norm/testdata/rules/decorrelate` line 7595 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131141#-O8CsfD3EviyxNtP-zBe:-O8E7DUK4T-MsEbRXQnP:b-6ioljs) ([raw file](https://github.com/cockroachdb/cockroach/blob/2653bec36b4ac2fe807c2d975648b7d559621d32/pkg/sql/opt/norm/testdata/rules/decorrelate#L7595)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: I realize it'll blow up the size of these plans, but a more verbose output might be nice, e.g., to see that the correct columns are coalesced here.
</blockquote></details>

Done. Turns out there's a `show-columns` directive.

**Comment by mgartner** [comment]
*[`pkg/sql/opt/norm/testdata/rules/decorrelate` line 7801 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/131141#-O8OD-pz42X9gLLvusJK:-O8OD-pz42X9gLLvusJL:b-xcrger) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ec356814b4ee6f87a0b4676a46a2435af30be78/pkg/sql/opt/norm/testdata/rules/decorrelate#L7801)):*
> ```
> # No-op because there's an Intersect instead of a Union.
> norm expect-not=TryDecorrelateUnion format=(hide-all,show-columns)
> SELECT *, CASE WHEN EXISTS (SELECT 1 FROM xy WHERE x = k INTERSECT SELECT 1 FROM uv WHERE v = k) THEN 1 ELSE 0 END FROM a;
> ```

Post-merge thought: all these tests have a single column projected in the subquery. Should we have some tests with multiple columns, expressions on those columns, and column references instead of constants? E.g.:

```
... EXISTS (SELECT 1, 2 ... UNION ...)

... EXISTS (SELECT x ... UNION ...)

... EXISTS (SELECT x + y ... UNION ...)

... EXISTS (SELECT x, y ... UNION ...
```

**Pull request merged**
