### PR TITLE
*: delete old version gates

### LINKED ISSUE #96761: disaster recovery: remove V22_2 gates and related logic/migrations/etc
Now that we've bumped minBinary to 22.2[1], we should now remove all V22_2* version gates and related gated logic/migrations/etc as applicable.

V22_2 gates for Disaster Recovery[2]:

- V22_2SupportAssumeRoleAuth
- V22_2NoNonMVCCAddSSTable
- V22_2SystemExternalConnectionsTable
- V22_2FixUserfileRelatedDescriptorCorruption

[1] https://github.com/cockroachdb/cockroach/issues/95530
[2] Using git blame from https://github.com/cockroachdb/cockroach/blame/984c24b05bfe3c04ffd7bec5784d475796504522/pkg/clusterversion/cockroach_versions.go

Jira issue: CRDB-24316

### LINKED ISSUE #96762: cdc: remove V22_2 gates and related logic/migrations/etc
Now that we've bumped minBinary to 22.2[1], we should now remove all V22_2* version gates and related gated logic/migrations/etc as applicable.

V22_2 gates for CDC[2]:

- V22_2EnablePredicateProjectionChangefeed
- V22_2RangefeedUseOneStreamPerNode

[1] https://github.com/cockroachdb/cockroach/issues/95530
[2] Using git blame from https://github.com/cockroachdb/cockroach/blame/984c24b05bfe3c04ffd7bec5784d475796504522/pkg/clusterversion/cockroach_versions.go

Jira issue: CRDB-24317

Epic CRDB-25043

### LINKED ISSUE #96765: kv: remove V22_2 gates and related logic/migrations/etc
Now that we've bumped minBinary to 22.2[1], we should now remove all V22_2* version gates and related gated logic/migrations/etc as applicable.

V22_2 gates for Transactions & Distribution(KV)[2]:

- [ ] V22_2LocalTimestamps
- [ ] V22_2PrioritizeSnapshots
- [ ] V22_2EnableLeaseUpgrade
- [x] V22_2SampledStmtDiagReqs. make sure to unskip `TestSampledStmtDiagReqsMigration`

[1] https://github.com/cockroachdb/cockroach/issues/95530
[2] Using git blame from https://github.com/cockroachdb/cockroach/blame/984c24b05bfe3c04ffd7bec5784d475796504522/pkg/clusterversion/cockroach_versions.go

### PR DESCRIPTION
**Pull request by healthy-pod**
Release note: None
Epic: none

Fixes #96762
Fixes #96761 
Fixes #96765

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111396#-:-NfOT5WN7vfr47A-faA1:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @healthy-pod, @lidorcarmel, and @miretskiy)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go` line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111396#-NfOSIW946OWlrcY0P_x:-NfOSIW946OWlrcY0P_y:bl4hzzo) ([raw file](https://github.com/cockroachdb/cockroach/blob/543814693d2b8c0641f05715c7ff9827c82ccc10/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L206)):*
> ```Go
> }
> 
> var isV221Active = func(_ tree.NodeFormatter, _ sessiondatapb.NewSchemaChangerMode, activeVersion clusterversion.ClusterVersion) bool {
> ```

nit: I think we can remove `isV221Active` altogether - it's ok for `checks` to be `nil`.

**Review by knz — APPROVED** [review]
> Reviewed 27 of 28 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111396)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @healthy-pod, @lidorcarmel, and @miretskiy)

___
*[`pkg/clusterversion/cockroach_versions.go` line 219 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111396#-NfQpRqh9QZfavEB1jXL:-NfQpRqh9QZfavEB1jXM:bu8e0q6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f085187c2c9570cbcc70127d188549d5ff9171dc/pkg/clusterversion/cockroach_versions.go#L219)):*
> ```Go
> 	// TODODelete_V22_2SetSystemUsersUserIDColumnNotNull sets the user_id column in system.users to not null.
> 	TODODelete_V22_2SetSystemUsersUserIDColumnNotNull
> 	// Permanent_V22_2SQLSchemaTelemetryScheduledJobs adds an automatic schedule for SQL schema
> ```

Maybe keep the full comment for this one.

**Comment by RaduBerinde** [comment]
There are some open issues around this, listed under 4 here: https://github.com/cockroachdb/cockroach/issues/95530

Can you mark this PR as fixing them?

**Review by RaduBerinde — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111396#-:-NfQyxNp72q1oOfeY4L1:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @healthy-pod, @lidorcarmel, and @miretskiy)

___
*[`pkg/clusterversion/cockroach_versions.go` line 180 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111396#-NfQxZLq9QtaAiuadT-C:-NfQxZLq9QtaAiuadT-D:b-scuefd) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b4db22febd5c54220faab81cf7024d8c89fe2f4/pkg/clusterversion/cockroach_versions.go#L180)):*
> ```Go
> 	//
> 	// This is a permanent migration which should exist forever.
> 	Permanent_V22_2SQLSchemaTelemetryScheduledJobs
> ```

Maybe we want to move this to a "Primordial" version? (feels like this is what they are for, but I'm not exactly sure)
___
*[`pkg/sql/schemachanger/screl/scalars.go` line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111396#-NfQycxM9l_qrMr1aWKz:-NfQycxM9l_qrMr1aWL-:bbst1r3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b4db22febd5c54220faab81cf7024d8c89fe2f4/pkg/sql/schemachanger/screl/scalars.go#L106)):*
> ```Go
> 
> // VersionSupportsElementUse checks if an element may be used at a given version.
> func VersionSupportsElementUse(el scpb.Element, version clusterversion.ClusterVersion) bool {
> ```

Nice refactoring!
___
*[`pkg/sql/schemachanger/screl/scalars.go` line 124 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111396#-NfQyjEx3XTYSkyYgrpG:-NfQyjEx3XTYSkyYgrpH:b-nal0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b4db22febd5c54220faab81cf7024d8c89fe2f4/pkg/sql/schemachanger/screl/scalars.go#L124)):*
> ```Go
> 		// These elements need v22.1 so they can be used without checking any version gates.
> 		return true
> 	case *scpb.CompositeType, *scpb.CompositeTypeAttrType, *scpb.CompositeTypeAttrName:
> ```

[nit] these cases can be consolidated and sorted by version

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111396)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @healthy-pod, @lidorcarmel, and @miretskiy)

___
*[`pkg/clusterversion/cockroach_versions.go` line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111396#-NfR0cdLA27qes_tr2rB:-NfR0cdLA27qes_tr2rC:b-v1ca3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b4db22febd5c54220faab81cf7024d8c89fe2f4/pkg/clusterversion/cockroach_versions.go#L171)):*
> ```Go
> 	VPrimordial5
> 	VPrimordial6
> 	// NOTE(andrei): Do not introduce new upgrades corresponding to VPrimordial
> ```

@knz do you understand this comment? My current guess is that it says to not introduce upgrades tied to an *existing* `VPrimordialX` version, and that we should instead add a new version?

It feels that all permanent upgrades would use one of these versions? Otherwise what is the point of "tying" a permanent upgrade to a dev version, if it is going to run no matter what?

Unfortunately Andrei and Andrew had the most context here I think :/
___
*[`pkg/upgrade/upgrades/upgrades.go` line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111396#-NfR-xLuDkMDsCrDv3gz:-NfR-xLuDkMDsCrDv3h-:bb5v4ld) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b4db22febd5c54220faab81cf7024d8c89fe2f4/pkg/upgrade/upgrades/upgrades.go#L89)):*
> ```Go
> 	),
> 	// Introduced in v2.1.
> 	// TODO(knz): bake this migration into v19.1.
> ```

I think we can remove this comment

**Comment by RaduBerinde** [comment]
*[`pkg/clusterversion/cockroach_versions.go` line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111396#-NfR0cdLA27qes_tr2rB:-NfR31AbEkRL1HPqNBO6:b5en35h) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b4db22febd5c54220faab81cf7024d8c89fe2f4/pkg/clusterversion/cockroach_versions.go#L171)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

@knz do you understand this comment? My current guess is that it says to not introduce upgrades tied to an *existing* `VPrimordialX` version, and that we should instead add a new version?

It feels that all permanent upgrades would use one of these versions? Otherwise what is the point of "tying" a permanent upgrade to a dev version, if it is going to run no matter what?

Unfortunately Andrei and Andrew had the most context here I think :/
</blockquote></details>

I will reach out to Andrei and see if we can get some more clarity and improve these comments.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111396)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @healthy-pod, @lidorcarmel, @miretskiy, and @RaduBerinde)

___
*[`pkg/clusterversion/cockroach_versions.go` line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111396#-NfR0cdLA27qes_tr2rB:-NfRExtY6T-OoQoMCj-z:b-5ylazf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b4db22febd5c54220faab81cf7024d8c89fe2f4/pkg/clusterversion/cockroach_versions.go#L171)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I will reach out to Andrei and see if we can get some more clarity and improve these comments.
</blockquote></details>

Without reversing this code, i don't feel comfortable reusing the VPrimordial versions for anything. We also didn't do it in the last release cycle.

**Comment by RaduBerinde** [comment]
*[`pkg/clusterversion/cockroach_versions.go` line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111396#-NfR0cdLA27qes_tr2rB:-NfRJwsp-RuqQ_cszA6E:bq2axc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b4db22febd5c54220faab81cf7024d8c89fe2f4/pkg/clusterversion/cockroach_versions.go#L171)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Without reversing this code, i don't feel comfortable reusing the VPrimordial versions for anything. We also didn't do it in the last release cycle.
</blockquote></details>

I spoke with Andrei for a bit and he agrees. I think the approach taken here is correct. I'll work on a separate PR to add to the comments.

**Review by celiala — APPROVED** [review]
:lgtm: 

> There are some open issues around this, listed under 4 here: [#95530](https://github.com/cockroachdb/cockroach/issues/95530)
> Can you mark this PR as fixing them?

Specifically:
- Fixes: #96762, #96761, #96765 

Thank you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111396#-:-NfRgbzh74qyXW6FOtA_:b74o46z)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 1 stale) (waiting on @healthy-pod, @knz, @lidorcarmel, @miretskiy, and @RaduBerinde)

___
*[`pkg/clusterversion/cockroach_versions.go` line 180 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111396#-NfQxZLq9QtaAiuadT-C:-NfRhJ_b3gaqtYH_G8To:b5q27hr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b4db22febd5c54220faab81cf7024d8c89fe2f4/pkg/clusterversion/cockroach_versions.go#L180)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Maybe we want to move this to a "Primordial" version? (feels like this is what they are for, but I'm not exactly sure)
</blockquote></details>

I'm not 100% sure how Primordial versions are used either tbh (compared to normal version gates).

At the very least, we should leave version value (order in which the system migrates though each gate). So perhaps we leave Permanent versions as-is (in the same order), unless others have more context/guidance here.

**Review by fqazi — APPROVED** [review]
SQL Foundations related files look good

**Review by rail — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111396)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 1 stale) (waiting on @healthy-pod, @knz, @lidorcarmel, @miretskiy, and @RaduBerinde)

**Comment by healthy-pod** [comment]
TFTRs!

bors r+

**Pull request merged**
