### PR TITLE
distsql: add router stats collection

### LINKED ISSUE #26647: distsql: add hashRouter stats to query stats
We need to add stats to the `hashRouter`. Specifically:
- The total number of rows processed and/or breakdown of number of rows sent to each output
- How much memory and/or disk (once we fall back to disk) was used per output

The `hashRouter` needs to create its own span and output its stats there. On the display side, the flow diagram code will need a way to map a `hashRouter` span to the box on the diagram. When displaying these stats, we need to be able to easily identify which data corresponds to which stream. Annotating outputs in the `hashRouter` with processor ids might be enough.

### PR DESCRIPTION
**Pull request by solongordon**
When stats collection is enabled, router outputs now report the number
of rows routed, memory usage, and disk usage. Like the existing network
stats, this data is keyed by stream ID, and in the flow diagram it
appears in the edge tooltip. (Due to the density of router edges, we
should probably find a better display strategy at some point.)

Fixes #26647

Release note: None

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
Make sure to also add some sort of test

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27657#-:-LHiXii5CrqmsSzU7Ivc:bmr6zec)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/flow.go, line 273 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27657#-LHiMNAp-gAGDRmtHcaP:-LHiMNAp-gAGDRmtHcaQ:bu9mxnz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b6c1056f4af66dd360f9d012bd9a8969257e921/pkg/sql/distsqlrun/flow.go#L273)):*
> ```Go
> 		streamIDs[i] = spec.Streams[i].StreamID
> 	}
> 	return makeRouter(spec, streams, streamIDs)
> ```

I would not get the `streamID`s here and instead pass in `spec` to `routerBase.setupStreams` (you can remove the `DisableBuffering` argument as well and have `routerBase` look at `spec` for the `streamID`s and anything else it needs.
___
*[pkg/sql/distsqlrun/flow_diagram.go, line 677 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27657#-LHiNHVEADDXWucL54l4:-LHiNHVF6F4RSQy46u9f:bw0v5ep) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b6c1056f4af66dd360f9d012bd9a8969257e921/pkg/sql/distsqlrun/flow_diagram.go#L677)):*
> ```Go
> 			}
> 			if s, ok := stats[i]; ok {
> 				stats[i] = append(s, dss.StatsForQueryPlan()...)
> ```

I think you can just do `stats[i] = append(stats[i] ...` in either case.
___
*[pkg/sql/distsqlrun/routers.go, line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27657#-LHiQqF43czWNlu0PrVE:-LHiQqF5-8o4H_SPimlD:b-q2gflv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b6c1056f4af66dd360f9d012bd9a8969257e921/pkg/sql/distsqlrun/routers.go#L236)):*
> ```Go
> func (rb *routerBase) init(ctx context.Context, flowCtx *FlowCtx, types []sqlbase.ColumnType) {
> 	// Check if we're recording stats.
> 	s := opentracing.SpanFromContext(ctx)
> ```

Might as well make this part of the if statement if it's not being used outside of it.
___
*[pkg/sql/distsqlrun/routers.go, line 237 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27657#-LHiPUQoEcpBzEjLcCX-:-LHiPUQpC-3QIPEvwamj:b-cocka7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b6c1056f4af66dd360f9d012bd9a8969257e921/pkg/sql/distsqlrun/routers.go#L237)):*
> ```Go
> 	// Check if we're recording stats.
> 	s := opentracing.SpanFromContext(ctx)
> 	if s != nil && !tracing.IsBlackHoleSpan(s) && tracing.IsRecording(s) {
> ```

I think just calling `IsRecording` is sufficient. Both `IsBlackHoleSpan` and `IsRecording`  have checks for `noopSpan` and `isRecording` with the difference that `IsBlackHoleSpan` returns true only if there is no shadow trace (zipkin/lightstep) and net trace (I'm not quite sure what that is) which shouldn't matter for stat collection.
___
*[pkg/sql/distsqlrun/routers.go, line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27657#-LHiQvMl7IWk4owPEOtd:-LHiQvMl7IWk4owPEOte:b1bk8bm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b6c1056f4af66dd360f9d012bd9a8969257e921/pkg/sql/distsqlrun/routers.go#L249)):*
> ```Go
> 		if rb.statsCollectionEnabled {
> 			// Start private memory monitor for stats collection.
> 			m := mon.MakeMonitorInheritWithLimit("router-stat-mem", 0 /* limit */, memoryMonitor)
> ```

You can use the `newMonitor` helper function here. I would also make each monitor name more descriptive by adding the stream id to the name maybe?
___
*[pkg/sql/distsqlrun/routers.go, line 260 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27657#-LHiUUvT9Ryh8JnnYaug:-LHiUUvT9Ryh8JnnYauh:bndaqq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b6c1056f4af66dd360f9d012bd9a8969257e921/pkg/sql/distsqlrun/routers.go#L260)):*
> ```Go
> 			flowCtx.TempStorage,
> 			memoryMonitor,
> 			flowCtx.diskMonitor,
> ```

We also need a private disk monitor here.
___
*[pkg/sql/distsqlrun/routers.go, line 323 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27657#-LHiRWab9DCdjc-OFRqL:-LHiRWab9DCdjc-OFRqM:b-klao32) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b6c1056f4af66dd360f9d012bd9a8969257e921/pkg/sql/distsqlrun/routers.go#L323)):*
> ```Go
> 						for _, row := range rows {
> 							if rb.statsCollectionEnabled {
> 								ro.stats.NumRows++
> ```

You could also increment this by `len(rows)` outside the loop I think
___
*[pkg/sql/distsqlrun/routers.go, line 687 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27657#-LHiX77c0ddVyMNCGIkB:-LHiX77c0ddVyMNCGIkC:bdu9ig8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b6c1056f4af66dd360f9d012bd9a8969257e921/pkg/sql/distsqlrun/routers.go#L687)):*
> ```Go
> func (ros *RouterOutputStats) Stats() map[string]string {
> 	statsMap := make(map[string]string)
> 	statsMap[routerOutputTagPrefix+"rows"] = string(ros.NumRows)
> ```

nit: I would make this `rows_routed` to mirror below
___
*[pkg/sql/distsqlrun/routers.go, line 697 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27657#-LHiX1uF8gruEXLigQKu:-LHiX1uF8gruEXLigQKv:b-d0scda) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b6c1056f4af66dd360f9d012bd9a8969257e921/pkg/sql/distsqlrun/routers.go#L697)):*
> ```Go
> 	return []string{
> 		fmt.Sprintf("rows routed: %d", ros.NumRows),
> 		fmt.Sprintf("%s: %d", maxDiskQueryPlanSuffix, ros.MaxAllocatedDisk),
> ```

Nit: we've been putting memory stats before disk stats
___
*[pkg/sql/distsqlrun/row_container.go, line 313 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27657#-LHiUgAVEl8jYq2a7hde:-LHiUgAVEl8jYq2a7hdf:b-f0gmy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b6c1056f4af66dd360f9d012bd9a8969257e921/pkg/sql/distsqlrun/row_container.go#L313)):*
> ```Go
> 
> 	// memoryMonitor is mrc's bytes monitor, exposed to enable stats collection.
> 	memoryMonitor *mon.BytesMonitor
> ```

I don't like that we're adding this field especially since we're thinking of putting row containers into their own package at some point. I think it would be better add `{disk,memory}Monitor` fields to keep track of these on the router output struct, sort of what we do in processors.

**Review by solongordon — COMMENTED** [review]
Addressed comments, though I still need to figure out an appropriate test.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27657#-:-LHj7v4q9D5BqU98gPN8:b-84h6tx)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/flow.go, line 273 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27657#-LHiMNAp-gAGDRmtHcaP:-LHipXY90Ok6zEn89Ozy:bdkz5h9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b6c1056f4af66dd360f9d012bd9a8969257e921/pkg/sql/distsqlrun/flow.go#L273)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I would not get the `streamID`s here and instead pass in `spec` to `routerBase.setupStreams` (you can remove the `DisableBuffering` argument as well and have `routerBase` look at `spec` for the `streamID`s and anything else it needs.
</blockquote></details>

Done. This introduces the slightly weird requirement that `streams` be in the same order as `spec.Streams` but I don't think that's a big deal.
___
*[pkg/sql/distsqlrun/flow_diagram.go, line 677 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27657#-LHiNHVEADDXWucL54l4:-LHiqOdG9rHtBJ9vpJWo:b-c9vg2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b6c1056f4af66dd360f9d012bd9a8969257e921/pkg/sql/distsqlrun/flow_diagram.go#L677)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think you can just do `stats[i] = append(stats[i] ...` in either case.
</blockquote></details>

Done, right you are.
___
*[pkg/sql/distsqlrun/routers.go, line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27657#-LHiQqF43czWNlu0PrVE:-LHiqlqR5t-pz1ED7itG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b6c1056f4af66dd360f9d012bd9a8969257e921/pkg/sql/distsqlrun/routers.go#L236)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Might as well make this part of the if statement if it's not being used outside of it.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/routers.go, line 237 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27657#-LHiPUQoEcpBzEjLcCX-:-LHiqr3FApu5nyrrtZhh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b6c1056f4af66dd360f9d012bd9a8969257e921/pkg/sql/distsqlrun/routers.go#L237)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think just calling `IsRecording` is sufficient. Both `IsBlackHoleSpan` and `IsRecording`  have checks for `noopSpan` and `isRecording` with the difference that `IsBlackHoleSpan` returns true only if there is no shadow trace (zipkin/lightstep) and net trace (I'm not quite sure what that is) which shouldn't matter for stat collection.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/routers.go, line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27657#-LHiQvMl7IWk4owPEOtd:-LHiu3Ia9K7gOyvy4fTw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b6c1056f4af66dd360f9d012bd9a8969257e921/pkg/sql/distsqlrun/routers.go#L249)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

You can use the `newMonitor` helper function here. I would also make each monitor name more descriptive by adding the stream id to the name maybe?
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/routers.go, line 260 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27657#-LHiUUvT9Ryh8JnnYaug:-LHiuhCmAkmKirxlW-Xq:b-qu6n94) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b6c1056f4af66dd360f9d012bd9a8969257e921/pkg/sql/distsqlrun/routers.go#L260)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

We also need a private disk monitor here.
</blockquote></details>

Good point. Done.
___
*[pkg/sql/distsqlrun/routers.go, line 323 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27657#-LHiRWab9DCdjc-OFRqL:-LHiv91e0NTRdeffrp2S:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b6c1056f4af66dd360f9d012bd9a8969257e921/pkg/sql/distsqlrun/routers.go#L323)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

You could also increment this by `len(rows)` outside the loop I think
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/row_container.go, line 313 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27657#-LHiUgAVEl8jYq2a7hde:-LHj0XYV6q976IRLN45S:bctpdcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b6c1056f4af66dd360f9d012bd9a8969257e921/pkg/sql/distsqlrun/row_container.go#L313)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't like that we're adding this field especially since we're thinking of putting row containers into their own package at some point. I think it would be better add `{disk,memory}Monitor` fields to keep track of these on the router output struct, sort of what we do in processors.
</blockquote></details>

Makes sense. Done.

**Review by asubiotto — APPROVED** [review]
:lgtm: minus the test

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27657#-:-LHnJKa2DZNfhMz-bb6c:b-wszghs)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
