### PR TITLE
Add a benchmark for MVCCPut.

### PR DESCRIPTION
**Pull request by petermattis**
BenchmarkMVCCPut10     200000   9489 ns/op    1.05 MB/s
BenchmarkMVCCPut100    200000  10975 ns/op    9.11 MB/s
BenchmarkMVCCPut1000   200000  19402 ns/op   51.54 MB/s
BenchmarkMVCCPut10000   30000  78242 ns/op  127.81 MB/s

While the MB/s does not look good at smaller sizes, we are performing
100k writes per second.

Tweak the MVCCMerge benchmark so that it only performs one merge for
each iteration. This matches up with the expectations of the go
benchmark framework.

### CODE REVIEW

**Comment by spencerkimball** [comment]
Why are these using in memory engines instead of rocksdb engines?

**Comment by bdarnell** [comment]
LGTM

**Comment by petermattis** [comment]
@spencerkimball InMem is now a small wrapper around RocksDB.

**Comment by spencerkimball** [comment]
LGTM

**Comment by spencerkimball** [comment]
Oh cool. Missed that change. That's great! So our ={integer bytes} engine specification now does the right thing?

**Comment by petermattis** [comment]
What's the `={integer bytes}` specification?

**Comment by spencerkimball** [comment]
That's how you can specify that a store should use memory instead of a file path for on disk storage.

**Comment by petermattis** [comment]
No, we don't support the `mem={integer bytes}` specification. Let me think about what can be done there. Problematic part is that the rocksdb in-mem stuff is hard to limit to a particular size. Works well for testing, but I'm not sure about production.

**Pull request merged**
