### PR TITLE
cluster-ui: delete unused vars

### PR DESCRIPTION
**Pull request by xinhaoz**
Delete unused vars in cluster-ui. A following commit will turn unused vars to errors via the eslint config.

Epic: None

Release note: None

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
Really nice cleanup!

> Reviewed 32 of 33 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107798#-:-NaSB89J4zV-YgsNOKpH:b-ce84og)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/columnsSelector/columnsSelector.tsx` line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107798#-NaSA8Ju1e7_tgf11Pb1:-NaSA8Ju1e7_tgf11Pb2:b-g4jijo) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bbf620c9ad337cedf6c07e94c95d2b27cfcbf4c/pkg/ui/workspaces/cluster-ui/src/columnsSelector/columnsSelector.tsx#L85)):*
> ```XML
>     boxShadow: "none",
>   }),
>   menuList: (provided: any) => ({
> ```

this is required, is setting the values on the customStyles, which is called on the code below

**Comment by xinhaoz** [comment]
*[`pkg/ui/workspaces/cluster-ui/src/columnsSelector/columnsSelector.tsx` line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107798#-NaSA8Ju1e7_tgf11Pb1:-NaSBI5Z9Q9LiaZ1HI4m:b-amvnb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bbf620c9ad337cedf6c07e94c95d2b27cfcbf4c/pkg/ui/workspaces/cluster-ui/src/columnsSelector/columnsSelector.tsx#L85)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

this is required, is setting the values on the customStyles, which is called on the code below
</blockquote></details>

Ah, gotcha + nice catch! This shouldn't affect the eslint rule anyways since it's a property. I'll put it back :thumbsup:

**Comment by xinhaoz** [comment]
*[`pkg/ui/workspaces/cluster-ui/src/columnsSelector/columnsSelector.tsx` line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107798#-NaSA8Ju1e7_tgf11Pb1:-NaSBuTLBJxoOaeosjWo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bbf620c9ad337cedf6c07e94c95d2b27cfcbf4c/pkg/ui/workspaces/cluster-ui/src/columnsSelector/columnsSelector.tsx#L85)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Ah, gotcha + nice catch! This shouldn't affect the eslint rule anyways since it's a property. I'll put it back :thumbsup: 
</blockquote></details>

Done.

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107798)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/databaseDetailsApi.ts` line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107798#-NaSE1UF8kE3RJSTasdn:-NaSE1UF8kE3RJSTasdo:b9x4qwa) ([raw file](https://github.com/cockroachdb/cockroach/blob/4874425ed333c202453efd22c35c43cdea5b6825/pkg/ui/workspaces/cluster-ui/src/api/databaseDetailsApi.ts#L96)):*
> ```XML
>     }
>   },
>   handleMaxSizeError: () => {
> ```

I'm surprise this is not giving errors after you removed the values. On the `DatabaseDetailsQuery` type this function is defined as receiving these 3 parameters, but you removed from almost all implementations. Can you confirm this is really handling correctly the max size error?

**Comment by xinhaoz** [comment]
*[`pkg/ui/workspaces/cluster-ui/src/api/databaseDetailsApi.ts` line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107798#-NaSE1UF8kE3RJSTasdn:-NaSRenu1K2pnvyRPwQO:budincp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4874425ed333c202453efd22c35c43cdea5b6825/pkg/ui/workspaces/cluster-ui/src/api/databaseDetailsApi.ts#L96)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I'm surprise this is not giving errors after you removed the values. On the `DatabaseDetailsQuery` type this function is defined as receiving these 3 parameters, but you removed from almost all implementations. Can you confirm this is really handling correctly the max size error? 
</blockquote></details>

I think it's because in JS/TS when a function is called with more arguments than there are params, theyre just ignored. One query that has `handleMaxSizeError` functions does use those params which is why theyre still included there. For consistency, instead of creating a union type to include functions without params, I've just appended the unused params with `_` so we can continue to use the single type without confusion.

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107798#-:-NaSV_Lw0OnJnWhXxzkm:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/databaseDetailsApi.ts` line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107798#-NaSE1UF8kE3RJSTasdn:-NaSVQYn6QkfO65jSt7s:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4874425ed333c202453efd22c35c43cdea5b6825/pkg/ui/workspaces/cluster-ui/src/api/databaseDetailsApi.ts#L96)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

I think it's because in JS/TS when a function is called with more arguments than there are params, theyre just ignored. One query that has `handleMaxSizeError` functions does use those params which is why theyre still included there. For consistency, instead of creating a union type to include functions without params, I've just appended the unused params with `_` so we can continue to use the single type without confusion.
</blockquote></details>

Thanks!

**Comment by xinhaoz** [comment]
TFTR! 
bors r+

**Pull request merged**
