### PR TITLE
workload: add details of loaded table to output

### PR DESCRIPTION
**Pull request by dt**
Release note: none.

### CODE REVIEW

**Comment by benesch** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[pkg/ccl/workloadccl/fixture.go, line 412 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23988#-L7oViQK8mNkKkTc_dA8:-L7oViQK8mNkKkTc_dA9:b1jnnxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7b6f2088f968bcbc175c39917984656428c6a0a/pkg/ccl/workloadccl/fixture.go#L412)):*
> ```Go
> 			if err := sqlDB.QueryRow(importStmt, table.BackupURI, database).Scan(
> 				&discard, &discard, &discard, &rows, &index, &discard, &bytes,
> 			); err != nil {
> ```

Very optional: `SELECT rows, index, bytes FROM [RESTORE...]`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23988#-:-L7oW6EWCto8fu1B-q9Z:bnfp4nl)*

**Comment by petermattis** [comment]
:lgtm:

Btw, I was wondering if we should store the rows and index entry counts in the jobs table when the job completes. 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23988#-:-L7oZWRj8Yi9F0zrdtYM:b-xcfqfh)*

**Comment by benesch** [comment]
Yeah, we've talked about that for a while. https://github.com/cockroachdb/cockroach/issues/18622

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23988#-:-L7o_cG108LRioO29wgB:b-3lahxa)*

**Comment by dt** [comment]
:thumbsup: yep, it's even already a proto since I figured we'd want to embed it like that.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[pkg/ccl/workloadccl/fixture.go, line 412 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23988#-L7oViQK8mNkKkTc_dA8:-L7oZk6X8WY-vQwKzsIX:b-kstzn8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7b6f2088f968bcbc175c39917984656428c6a0a/pkg/ccl/workloadccl/fixture.go#L412)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Very optional: `SELECT rows, index, bytes FROM [RESTORE...]`
</blockquote></details>

Thought about that but decided addition of subquery could (slightly) complicate any tracing/debugging.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23988#-:-L7o_86U8wfaabC9ROeu:b-hzw3ls)*

**Pull request merged**
