### PR TITLE
sql: More nuanced blocking of zone config DISCARD (as well as assorted testing)

### PR DESCRIPTION
**Pull request by ajstorm**
See individual commits for details.

### CODE REVIEW

**Comment by ajstorm** [comment]
@otan I forgot to include you on this review initially.  Can you PTAL?

**Review by otan — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63941)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/sql/region_util.go, line 1055 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63941#-MYqQr6W7js1-sZ9U4UL:-MYqQr6W7js1-sZ9U4UM:b-z9o58v) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ec95f75ef2fb92e7a9119b7daec5d141462532a/pkg/sql/region_util.go#L1055)):*
> ```Go
> 		// REGIONAL BY ROW tables.
> 		if tblDesc.IsLocalityRegionalByRow() {
> 			needToError = true
> ```

nit: can we just return `true, nil` here and below to avoid continuing on in the function if we might not.

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63941)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/region_util.go, line 1055 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63941#-MYqQr6W7js1-sZ9U4UL:-MYtS1LF6Ww0vu0aLbLH:b5eqek2) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ec95f75ef2fb92e7a9119b7daec5d141462532a/pkg/sql/region_util.go#L1055)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: can we just return `true, nil` here and below to avoid continuing on in the function if we might not.
</blockquote></details>

totes - all done

**Comment by ajstorm** [comment]
TFTR!

bors r=otan

**Comment by ajstorm** [comment]
Flake.  Rerunning...

bors r=otan

**Pull request merged**
