### PR TITLE
bazel,dev: allow generating `assets.tar.gz` for UI components

### LINKED ISSUE #105352: bazel: add a command to generate UI code consumed by Go build
This should generate the `assets.tar.gz` file in the following dirs: `pkg/ui/distccl`, `pkg/ui/distoss`. To my knowledge this is all we need to get the UI build "working" as far as `go build` is concerned. Also, expose a new command like `dev gen ui` to generate this stuff. Consider adding a new command to generate "everything" needed for the entire `cockroach` build which includes both `dev gen go` and `dev gen ui`?

Jira issue: CRDB-28998

### PR DESCRIPTION
**Pull request by rickystewart**
With this change, you can run `dev generate ui` (or equivalently, `bazel run pkg/gen:ui`) to build and hoist the `assets.tar.gz` files in `distoss` and `distccl`. We also expose `dev gen go_full`, which generates all `go` code, `cgo` stubs, as well as these UI tarballs. The idea is that generating `go_full` is enough to build `cockroach` in any configuration using `go build`.

Closes #105352.

Epic: none
Release note: None

### CODE REVIEW

**Review by mari-crl — COMMENTED** [review]
Lookin real good!! 
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105369#-:-NYcsvF-D3PoVaadrsa7:br0tpmg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart)

**Comment by rickystewart** [comment]
TFTR!

bors r=mari-crl

**Comment by rickystewart** [comment]
bors r=mari-crl

**Review by mari-crl — APPROVED** [review]
Trying again to get the approval though...

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105369#-:-NYcuCNp6BJImmRURLl1:b-yx50kg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart)

**Comment by rickystewart** [comment]
bors r=mari-crl

**Comment by rickystewart** [comment]
bors r=mari-crl

**Pull request merged**
