### PR TITLE
[WIP] *: optionally return Scan response data in RocksDB batch repr format

### PR DESCRIPTION
**Pull request by petermattis**
This reduces the size of a Scan response containing 10k "kv" keys from
410 KiB to 322 KiB. If we omit sending the timestamp this can further
reduce the size to 234 KiB. This can be seen as a primitive version of
 #13193. The response size savings are compelling and we'd likely see
even more space savings if we switched to an encoded datum format.

Unfortunately, this change doesn't seem to have an effect on performance
even when forcing the RPC to go over the network. The test I performed
was to load 1m rows using `kv` and then run `select count(*) test.kv`,
flipping `ReturnBatchRepr` on and off.

There are bits here that deserve to be merged regardless. Specifically,
the changes to RocksDBBatchReader and the usage of roachpb.KeyValue
instead of client.KeyValue in sql. I'll split these pieces out into
separate PRs.

### CODE REVIEW

**Comment by petermattis** [comment]
Cc @RaduBerinde, @bdarnell, @tschottdorf, @spencerkimball

**Comment by bdarnell** [comment]
> Unfortunately, this change doesn't seem to have an effect on performance
> even when forcing the RPC to go over the network.

What configurations did you test? I'd expect a bigger difference for a multi-DC cluster like `indigo` than a single-DC one. 

---

Review status: 0 of 21 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18913#-:-KvEM2TKAmH8xtZ9tYyI:b-3ehfz4)*

**Comment by petermattis** [comment]
> What configurations did you test? I'd expect a bigger difference for a multi-DC cluster like indigo than a single-DC one.

I only tested locally with the "localServer" optimization disabled. I agree this will make a bigger difference on wide area networks. Seems worth exploring further.

---

Review status: 0 of 21 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18913#-:-KvENU0ZFwtccSZCtooB:b-xuddfc)*

**Comment by nvanbenschoten** [comment]
I just ran this against TPCC and I'm not really seeing any movement in the metrics. It's giving at most a **1%** improvement in `ns/op`, but that doesn't look statistically significant.

**Comment by petermattis** [comment]
That's strange. I wonder why your PR showed improvement and mine didn't. Both should reduce allocations, while this one will also reduce the size of responses.

**Comment by petermattis** [comment]
With #21395 merged, the low-level `MVCCScan` op now generates RocksDB batch repr format. I plan to take another look at this PR to see if it moves the needle. I'm also planning to look at how this affects performance on a geo-distributed cluster.

**Comment by petermattis** [comment]
#26553 has replaced this PR.

**Pull request closed without merging**
