### PR TITLE
lint: check existence of release note

### PR DESCRIPTION
**Pull request by tbg**
Targeted alternative (or perhaps short-term stand-in) for [1].
I think it's worth linting this sooner rather than later.

Release notes: none.

[1]: https://github.com/cockroachdb/cockroach/pull/18782

### CODE REVIEW

**Comment by jordanlewis** [comment]
It would be great if this could come with a post-commit hook too.

**Comment by tschottdorf** [comment]
Yeah, that would be ideal, but that's the kind of work already done in #18782 (except in the context of a general commit linter, which I'm not really on board with). You can't just run a lint as a post-commit hook because it's way too slow. Perhaps @benesch can reduce #18782 to the uncontroversial part (linting release notes) and land it?

Either way, I'm pretty confident that linting these today rather than next week makes sense.

**Review by jordanlewis — APPROVED** [review]
I just meant a little git post-commit hook that checks for the existence of the
Release notes line and prints a warning if it's missing. I don't want to have
to build or run any Go test program to just grep my commit message.

I suppose we can do this offline since you can't add git hooks via a repository
commit anyway.

**Comment by benesch** [comment]
Hmm? make build will install any hook in the githooks directory. It’s kind
of a hack but it works well.

Building a Go program is also not so bad when it happens automatically
during make build. You don’t even notice it, really; if you commit before
it gets built Git will simply proceed as normal.

On the subject of the commit message linter, I’m about out of bandwidth for
defending/maintaining it.

@tschottdorf, I’m a bit nervous about a linter whose output changes
depending upon which branch you run it on. Would prefer a combination of a
precommit githook and something in github pull request make. But don’t let
that stop you from merging this PR in the meantime. Something is much
better than nothing.

**Comment by tschottdorf** [comment]
Heard @jordanlewis is cooking something up that has better ergonomics, closing this one!

**Pull request closed without merging**
