### PR TITLE
authors: add <Jack Wu> to authors

### PR DESCRIPTION
**Pull request by jackcwu**
Release note: None

### CODE REVIEW

**Comment by jlinder** [comment]
Hi @jackcwu, Can you amend your commit to include the `Release justification: non-production change` line?

This can be done like so:

- amend the commit with `git commit --amend`
- push the new branch head to your remote with `git push --force-with-lease FORK_NAME jackwu_authors`

**Comment by jackcwu** [comment]
@jlinder My apologies for not seeing this, it got buried under some emails. I just made the change

**Review by jlinder — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69889#-:-MjAGajABattHU8GHbBI:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jackcwu)

**Pull request merged**
