### PR TITLE
sql: add support for expression-based indexes with CREATE INDEX

### PR DESCRIPTION
**Pull request by mgartner**
#### sql: add experimental_enable_expression_based_indexes session setting

This commit adds a session setting that will eventually enable users to
create expression-based indexes. The setting will be removed when
expression-based indexes are fully supported.

Release note: None

#### sql: add support for expression-based indexes with CREATE INDEX

This commit adds basic support for creating expression-based indexes
with a `CREATE INDEX` statement. An expression-based index is syntactic
sugar for an index on a virtual computed column. Creating an
expression-based index will automatically created a hidden virtual
column with the given expression. If a virtual column with the given
expression already exists, that column is used rather than creating a
new one.

Future work includes supporting expression-based indexes in
`CREATE TABLE` and making error messages related to these indexes more
user-friendly.

There is no release note because expression-based indexes are not
enabled by default. They require the
`experimental_enable_expression_based_indexes` session setting until
they are fully supported.

Release note: None

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
Awesome work! Exciting that you've already made so much progress on this. The test cases are great.

As we talked about offline, I think it would be good to consider making the virtual columns just regular hidden columns, similar to how we handle the `crdb_region` column in `REGIONAL BY ROW` tables. This would allow you to avoid creating this new "inaccessible" column type. Not sure it's necessarily better, but worth considering anyway.

> Reviewed 12 of 12 files at r1, 11 of 11 files at r2, 11 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-:-Ma17dGWB6M2xFIv7dKg:b-hcnhen)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/create_index.go, line 322 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-Ma-8gnz8XXs_WJJ0GO1:-Ma-8gnz8XXs_WJJ0GO2:b-hdutbt) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9df5e3e7c7dfce7dc6af698edf4927b04aa6ce/pkg/sql/create_index.go#L322)):*
> ```Go
> // setupShardedIndex creates a shard column for the given index descriptor. It
> // returns the shard column, the new column list for the index, and a boolean
> // indicating which is true if the shard column was newly created. If the shard
> ```

nit: indicating which is true -> indicating (or which is true)
___
*[pkg/sql/create_index.go, line 323 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-Ma-9KOY5yhWXEt7Piuh:-Ma-9KOY5yhWXEt7Piui:b-z4rbe8) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9df5e3e7c7dfce7dc6af698edf4927b04aa6ce/pkg/sql/create_index.go#L323)):*
> ```Go
> // returns the shard column, the new column list for the index, and a boolean
> // indicating which is true if the shard column was newly created. If the shard
> // column is new, it is added to tableDesc. The column list returned must be
> ```

nit: "must be used" implies that there is some required action by the caller of this function
___
*[pkg/sql/create_index.go, line 324 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-Ma-8qfZ1mpBzfjuHi6x:-Ma-8qfZ1mpBzfjuHi6y:b-mrhhrv) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9df5e3e7c7dfce7dc6af698edf4927b04aa6ce/pkg/sql/create_index.go#L324)):*
> ```Go
> // indicating which is true if the shard column was newly created. If the shard
> // column is new, it is added to tableDesc. The column list returned must be
> // used in the index descriptor regardless whether or not the shard column was
> ```

nit: regardless of
___
*[pkg/sql/exec_util.go, line 362 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-Ma-AB_ACapHeWkALRUy:-Ma-AB_ACapHeWkALRUz:bljvz7e) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9df5e3e7c7dfce7dc6af698edf4927b04aa6ce/pkg/sql/exec_util.go#L362)):*
> ```Go
> ).WithPublic()
> 
> var experimentalMultiColumnInvertedIndexesMode = settings.RegisterBoolSetting(
> ```

this variable name doesn't match the setting
___
*[pkg/sql/catalog/descpb/structured.proto, line 143 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-Ma-AuwQDEQJkPnGAOmF:-Ma-AuwQDEQJkPnGAOmG:b-xbhv9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/86522486aeb21b9d696534d3cb8e1eef7b5ed35b/pkg/sql/catalog/descpb/structured.proto#L143)):*
> ```protobuf
>   // can create a hidden column with the NOT VISIBLE qualifier.
>   optional bool hidden = 6 [(gogoproto.nullable) = false];
>   // Inaccessible columns not not visible to queries by name, not part of star
> ```

nit: columns not not -> columns are not
___
*[pkg/sql/catalog/schemaexpr/expr.go, line 47 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-Ma15rrCCIJTwiverl86:-Ma15rrDCF6J1mgIfISe:bh2gv8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2435ada0487ddbd2f5c44181d8d77a3d6421db5/pkg/sql/catalog/schemaexpr/expr.go#L47)):*
> ```Go
> 
> 	// Strip database and table names from qualified column names.
> 	expr, err := dequalifyColumnRefs(ctx, sourceInfo, expr)
> ```

What if a user attempts to make an expression-based index using a column from a different table? Won't this either succeed silently (if a column with the same name exists in the current table) or cause a confusing error?
___
*[pkg/sql/catalog/tabledesc/validate.go, line 704 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-Ma-CtIzAAXioLJNnOCN:-Ma-CtJ-5Lq7v5P4be98:b988go1) ([raw file](https://github.com/cockroachdb/cockroach/blob/86522486aeb21b9d696534d3cb8e1eef7b5ed35b/pkg/sql/catalog/tabledesc/validate.go#L704)):*
> ```Go
> 
> 		if column.IsHidden() && column.IsInaccessible() {
> 			return errors.AssertionFailedf("column %q cannot be hidden an inaccessible", column.GetName())
> ```

nit: an -> and
___
*[pkg/sql/sessiondata/session_data.go, line 233 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-Ma-APBv8g-d1kJINaYx:-Ma-APBw0RgBLu1HAkX0:b-45tdy) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9df5e3e7c7dfce7dc6af698edf4927b04aa6ce/pkg/sql/sessiondata/session_data.go#L233)):*
> ```Go
> 	EnableSeqScan bool
> 
> 	// EnableExpressionBasedIndexes indicated whether creating expression-based
> ```

nit: indicated -> indicates

**Review by postamar — COMMENTED** [review]
This is pretty cool!

I'll second @rytaft's suggestion to not introduce an `inaccessible` column qualifier boolean and use `hidden` instead. My initial motivation for this comment is that these column qualifiers are complicated enough as it is; adding to that complexity would have to be really worth it. For a start, the interplay between qualifiers can be quite subtle; for instance can an inaccessible column be considered as readable? should being inaccessible but not hidden trigger a validation failure? if not, should the column be considered to be deletable? It's a nightmare that never ends. 

Looking beyond implementation considerations (we can deal with that if need be) what's the motivation to go beyond `hidden` here? This is not obvious to me and I feel this would need to be justified. 

I checked out your branch and fiddled with it so I could build it and try a few things:
```
demo@127.0.0.1:26257/defaultdb> CREATE TABLE foo (a INT PRIMARY KEY);
CREATE TABLE

Time: 3ms total (execution 3ms / network 0ms)
demo@127.0.0.1:26257/defaultdb> CREATE INDEX bar ON foo (a + 1);
invalid syntax: statement ignored: at or near "+": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
CREATE INDEX bar ON foo (a + 1)
                           ^
HINT: try \h CREATE INDEX
demo@127.0.0.1:26257/defaultdb> CREATE INDEX bar ON foo ((a + 1));
CREATE INDEX

Time: 59ms total (execution 5ms / network 55ms)

demo@127.0.0.1:26257/defaultdb> SHOW INDEXES FROM foo;
  table_name | index_name | non_unique | seq_in_index |  column_name  | direction | storing | implicit
-------------+------------+------------+--------------+---------------+-----------+---------+-----------
  foo        | bar        |    true    |            1 | crdb_idx_expr | ASC       |  false  |  false
  foo        | bar        |    true    |            2 | a             | ASC       |  false  |   true
  foo        | primary    |   false    |            1 | a             | ASC       |  false  |  false
(3 rows)

Time: 4ms total (execution 3ms / network 0ms)
```
Why does the parser want double brackets for the expression? I see no ambiguity here. Anyway the SHOW INDEXES is to illustrate that the auto-generated column is going to end up being user-visible anyway one way or another in some unexpected way, it's not worth fighting IMHO.

**Comment by mgartner** [comment]
> I'll second @rytaft's suggestion to not introduce an inaccessible column qualifier boolean and use hidden instead. 

Agreed. These column qualifiers are indeed already complex. I'll rework this PR to remove the "Inaccessible" qualifier. Thanks for the feedback!

> Why does the parser want double brackets for the expression?

This matches Postgres's behavior, which makes since because this part of our yacc file was lifted directly from PG in [this commit](https://github.com/cockroachdb/cockroach/commit/06e13874b9153cdcbf44bf0e0605db44039b0afa#diff-1b96bbb004afa8a7019c08f9be0482ac534ba91bd856d287ca03c7ed36ef991fR1028). Interestingly, parens are not required when the expression is a function call, so `CREATE INDEX i ON t (lower(s))` is allowed. I'll explore the possibility of removing the additional parens for non-function expressions.

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Nice to see this work underway!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-:-Ma55L4tCX494OPMo-yw:b8mbkwv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/clusterversion/cockroach_versions.go, line 566 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-Ma53JsI1-7Pc30OZSoq:-Ma53JsI1-7Pc30OZSor:bvd57jt) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9df5e3e7c7dfce7dc6af698edf4927b04aa6ce/pkg/clusterversion/cockroach_versions.go#L566)):*
> ```Go
> 	{
> 		Key:     ExpressionBasedIndexes,
> 		Version: roachpb.Version{Major: 21, Minor: 1, Internal: 10},
> ```

Should this be 21.2?
___
*[pkg/sql/logictest/testdata/logic_test/expression_index, line 2 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-Ma54WM92J7WKs3709dO:-Ma54WM92J7WKs3709dP:b-t4dsbh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2435ada0487ddbd2f5c44181d8d77a3d6421db5/pkg/sql/logictest/testdata/logic_test/expression_index#L2)):*
> ```
> statement ok
> SET experimental_enable_expression_based_indexes=true
> ```

[nit] add a test with the variable = false to test that it errors out

**Review by mgartner — COMMENTED** [review]
I've removed the `Inaccessible` column commit and address all the comments. RFAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-:-Ma5JmSA2OX8yAbUysGd:b-uu7hok)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/clusterversion/cockroach_versions.go, line 566 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-Ma53JsI1-7Pc30OZSoq:-Ma5IqjU5L0bzwA-4RmI:b6t9ebm) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9df5e3e7c7dfce7dc6af698edf4927b04aa6ce/pkg/clusterversion/cockroach_versions.go#L566)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Should this be 21.2?
</blockquote></details>

I don't think so. Notice the `Start21_2` entry a few lines up. From the comment higher up:

```
// It typically trails the current version by
// one release. For example, if the current branch is a `21.1.x` release, you
// will have a BinaryMinSupportedVersion of `21.0`, meaning that the versions
// 20.2.0-1, 20.2.0-2, etc are always going to be active on any peer and thus
// can be "baked in"; similarly all migrations attached to any of these versions
// can be assumed to have run (or not having been necessary due to the cluster
// having been initialized at a higher version in the first place).
```

I don't fully understand why these versions trail the current version, but I think I'm setting this correctly. I could be wrong...
___
*[pkg/sql/create_index.go, line 322 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-Ma-8gnz8XXs_WJJ0GO1:-Ma4kvC54v-c64Nqyik2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9df5e3e7c7dfce7dc6af698edf4927b04aa6ce/pkg/sql/create_index.go#L322)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: indicating which is true -> indicating (or which is true)
</blockquote></details>

Done.
___
*[pkg/sql/create_index.go, line 323 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-Ma-9KOY5yhWXEt7Piuh:-Ma4lFpwB7t9cY6C_tqy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9df5e3e7c7dfce7dc6af698edf4927b04aa6ce/pkg/sql/create_index.go#L323)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: "must be used" implies that there is some required action by the caller of this function
</blockquote></details>

Done.
___
*[pkg/sql/create_index.go, line 324 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-Ma-8qfZ1mpBzfjuHi6x:-Ma4lPF3ANJGS8zp-2ia:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9df5e3e7c7dfce7dc6af698edf4927b04aa6ce/pkg/sql/create_index.go#L324)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: regardless of
</blockquote></details>

Done.
___
*[pkg/sql/exec_util.go, line 362 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-Ma-AB_ACapHeWkALRUy:-Ma5DzYu8SLU3seILtq5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9df5e3e7c7dfce7dc6af698edf4927b04aa6ce/pkg/sql/exec_util.go#L362)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

this variable name doesn't match the setting
</blockquote></details>

Done.
___
*[pkg/sql/catalog/schemaexpr/expr.go, line 47 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-Ma15rrCCIJTwiverl86:-Ma5G_jhDmBIvJRJoF3X:bc072is) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2435ada0487ddbd2f5c44181d8d77a3d6421db5/pkg/sql/catalog/schemaexpr/expr.go#L47)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

What if a user attempts to make an expression-based index using a column from a different table? Won't this either succeed silently (if a column with the same name exists in the current table) or cause a confusing error?
</blockquote></details>

`dequalifyColumnRefs` only strips database and table names from columns if they match the database and table in `sourceInfo`. It will return an error if it encounters a database/table not in `sourceInfo`. This comment is confusing. Anywho, I've removed this function in favor of `DequalifyAndValidateExpr` now that I need the serialized expression to compare with existing virtual column expressions.

I've also added a test for this.
___
*[pkg/sql/logictest/testdata/logic_test/expression_index, line 2 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-Ma54WM92J7WKs3709dO:-Ma5HshcDrSP0KHTAlsA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2435ada0487ddbd2f5c44181d8d77a3d6421db5/pkg/sql/logictest/testdata/logic_test/expression_index#L2)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] add a test with the variable = false to test that it errors out
</blockquote></details>

Done.
___
*[pkg/sql/sessiondata/session_data.go, line 233 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-Ma-APBv8g-d1kJINaYx:-Ma5I36s4UMEZkDLUK0o:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9df5e3e7c7dfce7dc6af698edf4927b04aa6ce/pkg/sql/sessiondata/session_data.go#L233)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: indicated -> indicates
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm: Awesome!

> Reviewed 25 of 25 files at r4, 27 of 27 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-:-Ma5SgXc1GapjIUp-kG9:bswp6el)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/catalog/schemaexpr/expr.go, line 47 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-Ma15rrCCIJTwiverl86:-Ma5RYob8VSc96qGfXCW:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2435ada0487ddbd2f5c44181d8d77a3d6421db5/pkg/sql/catalog/schemaexpr/expr.go#L47)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

`dequalifyColumnRefs` only strips database and table names from columns if they match the database and table in `sourceInfo`. It will return an error if it encounters a database/table not in `sourceInfo`. This comment is confusing. Anywho, I've removed this function in favor of `DequalifyAndValidateExpr` now that I need the serialized expression to compare with existing virtual column expressions.

I've also added a test for this.
</blockquote></details>

:thumbsup: 
___
*[pkg/sql/catalog/schemaexpr/expr.go, line 46 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-Ma5RgIy8Ng3Mcm6zRVX:-Ma5RgIy8Ng3Mcm6zRVY:beq7ghc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6c9b62bca7cdf4098246c27d1d158cbd35bbbc8/pkg/sql/catalog/schemaexpr/expr.go#L46)):*
> ```Go
> 	maxVolatility tree.Volatility,
> 	tn *tree.TableName,
> ) (string, *types.T, catalog.TableColSet, error) {
> ```

nit: update function comment to mention this new return param
___
*[pkg/sql/catalog/tabledesc/table_desc.go, line 417 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-Ma5RyCd2MyF2WJLxNsE:-Ma5RyCd2MyF2WJLxNsF:b-3gls5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6c9b62bca7cdf4098246c27d1d158cbd35bbbc8/pkg/sql/catalog/tabledesc/table_desc.go#L417)):*
> ```Go
> 
> // FindVirtualColumnWithExpr returns the first virtual computed column whose
> // expression matches the provided target expression, in the canonical order. If
> ```

what's the canonical order?
___
*[pkg/sql/catalog/tabledesc/table_desc.go, line 418 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-Ma5S-c-8Oavyvngak1e:-Ma5S-c0EHtfzUIXDKlM:b-5ck6l2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6c9b62bca7cdf4098246c27d1d158cbd35bbbc8/pkg/sql/catalog/tabledesc/table_desc.go#L418)):*
> ```Go
> // FindVirtualColumnWithExpr returns the first virtual computed column whose
> // expression matches the provided target expression, in the canonical order. If
> // no column is found then ok=false is return.
> ```

nit: is return -> is returned
___
*[pkg/sql/opt/exec/execbuilder/testdata/expression_index, line 25 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-Ma5T2HVCIKKIkwSxEKG:-Ma5T2HVCIKKIkwSxEKH:blp6fh1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6c9b62bca7cdf4098246c27d1d158cbd35bbbc8/pkg/sql/opt/exec/execbuilder/testdata/expression_index#L25)):*
> ```
> EXPLAIN SELECT * FROM t@t_a_plus_b_idx WHERE a + b = 110
> ----
> distribution: local
> ```

you're getting test failures for some configurations that set this to distribution: full or vectorized: false. You could either restrict the test configs or use the pattern used elsewhere of `SELECT * FROM [EXPLAIN ...] OFFSET 2`

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65375)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/catalog/schemaexpr/expr.go, line 46 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-Ma5RgIy8Ng3Mcm6zRVX:-MaANUL89f6fh9_VgChQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6c9b62bca7cdf4098246c27d1d158cbd35bbbc8/pkg/sql/catalog/schemaexpr/expr.go#L46)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: update function comment to mention this new return param
</blockquote></details>

Done.
___
*[pkg/sql/catalog/tabledesc/table_desc.go, line 417 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-Ma5RyCd2MyF2WJLxNsE:-MaANfP16hdsyAa0Xz53:b-fpzx0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6c9b62bca7cdf4098246c27d1d158cbd35bbbc8/pkg/sql/catalog/tabledesc/table_desc.go#L417)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

what's the canonical order?
</blockquote></details>

I copied this from the similar functions above. The comment for `AllColumns` explains:

```
// AllColumns returns a slice of Column interfaces containing the
// table's public columns and column mutations, in the canonical order:
// - all public columns in the same order as in the underlying
//   desc.TableDesc().Columns slice;
// - all column mutations in the same order as in the underlying
//   desc.TableDesc().Mutations slice.
// - all system columns defined in colinfo.AllSystemColumnDescs.
```
___
*[pkg/sql/catalog/tabledesc/table_desc.go, line 418 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-Ma5S-c-8Oavyvngak1e:-MaAO0w20hNgi6ItQeaw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6c9b62bca7cdf4098246c27d1d158cbd35bbbc8/pkg/sql/catalog/tabledesc/table_desc.go#L418)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: is return -> is returned
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/testdata/expression_index, line 25 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-Ma5T2HVCIKKIkwSxEKG:-MaAOo088NuzjjTpSZRX:b-a6taqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6c9b62bca7cdf4098246c27d1d158cbd35bbbc8/pkg/sql/opt/exec/execbuilder/testdata/expression_index#L25)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

you're getting test failures for some configurations that set this to distribution: full or vectorized: false. You could either restrict the test configs or use the pattern used elsewhere of `SELECT * FROM [EXPLAIN ...] OFFSET 2`
</blockquote></details>

Thanks! Fixed.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 22 of 22 files at r6, 16 of 16 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65375#-:-MaAd0M6AncbVxkjaT67:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
