### PR TITLE
kv/kvnemesis: include support for reverse scan operations

### LINKED ISSUE #64818: kvnemesis: add ReverseScan
We should extend kvnemesis to issue ReverseScan requests.

### PR DESCRIPTION
**Pull request by AlexTalks**
Closes #64818

Adds ReverseScan and ReverseScanForUpdate operations to the potential
operations performed by kvnemesis.  This enhances additional validation
of a KV operation that was not previously tested by the tool.

Release note: None

/cc. @cockroachdb/kv

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
Very nice job! I just have a few minor comments.

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66750#-:-Md2otF5AFj2ayRABx4l:b-oj72vl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks)

___
*[pkg/kv/kvnemesis/operations.proto, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66750#-Md2mxA73WO6LMyLbjSi:-Md2mxA73WO6LMyLbjSj:b9mdoi) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ced45f5912d683329152a94ca967917f1d7586b/pkg/kv/kvnemesis/operations.proto#L52)):*
> ```protobuf
>   bool for_update = 3;
>   Result result = 4 [(gogoproto.nullable) = false];
>   bool reverse = 5;
> ```

nit: these protobufs are never serialized anywhere, so they don't have any compatibility requirements. So it would be fine and probably appropriate to move this field up above `result` and switch their numbers.
___
*[pkg/kv/kvnemesis/validator.go, line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66750#-Md2nhRs4wsIt5jH8ds7:-Md2nhRs4wsIt5jH8ds8:b8pu0c8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ced45f5912d683329152a94ca967917f1d7586b/pkg/kv/kvnemesis/validator.go#L191)):*
> ```Go
> 	KVs     []roachpb.KeyValue
> 	Valid   multiKeyTimeSpan
> 	Reverse bool
> ```

nit: move this up below `Span` so that the inputs and outputs remain in order. Same thing when constructing the `&observedScan` down below.
___
*[pkg/kv/kvnemesis/validator.go, line 533 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66750#-Md2nvAV12x43v2OCT0N:-Md2nvAV12x43v2OCT0O:bjo3zo) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ced45f5912d683329152a94ca967917f1d7586b/pkg/kv/kvnemesis/validator.go#L533)):*
> ```Go
> 			}
> 			// All kvs should be in order.
> 			if !o.Reverse {
> ```

I think we can avoid some of the code duplication with `sort.Reverse`. Perhaps something like:
```go
orderedKVs := sort.Interface(roachpb.KeyValueByKey(o.KVs))
if o.Reverse {
    orderedKVs = sort.Reverse(orderedKVs)
}
if !sort.IsSorted(orderedKVs) {
    ...
}
```
___
*[pkg/kv/kvnemesis/validator.go, line 804 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66750#-Md2o__j4TsYejiCLuoM:-Md2o__k6poUp_hs1Yam:bwga7mv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ced45f5912d683329152a94ca967917f1d7586b/pkg/kv/kvnemesis/validator.go#L804)):*
> ```Go
> 				kvs.WriteString(mustGetStringValue(kv.Value.RawBytes))
> 			}
> 			opCode := "s"
> ```

nit: move this up above `var kvs strings.Builder`.

**Comment by AlexTalks** [comment]
___
*[pkg/kv/kvnemesis/validator.go, line 533 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66750#-Md2nvAV12x43v2OCT0N:-Md3COwdCoYKz8IVTApT:b5dyv0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ced45f5912d683329152a94ca967917f1d7586b/pkg/kv/kvnemesis/validator.go#L533)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think we can avoid some of the code duplication with `sort.Reverse`. Perhaps something like:
```go
orderedKVs := sort.Interface(roachpb.KeyValueByKey(o.KVs))
if o.Reverse {
    orderedKVs = sort.Reverse(orderedKVs)
}
if !sort.IsSorted(orderedKVs) {
    ...
}
```
</blockquote></details>

Wouldn't the `sort.IsSorted` still usr the `roachpb.KeyValueByKey` comparator though, which implements an increasing order?  https://github.com/cockroachdb/cockroach/blob/2eda7d0d6c1bdb277cb72eecc21ba8c382b1deab/pkg/roachpb/data.go#L2406

I could implement a `KeyValueByReverseKey` interface that implements the reverse order comparator if that seems better here though.  It didn't seem like there were any reverse order comparators in `roachpb` but I can put in this file itself of course.

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66750)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks and @nvanbenschoten)

___
*[pkg/kv/kvnemesis/validator.go, line 533 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66750#-Md2nvAV12x43v2OCT0N:-Md3Gaf1ED7GzXFxbAmN:bx2zbh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ced45f5912d683329152a94ca967917f1d7586b/pkg/kv/kvnemesis/validator.go#L533)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

Wouldn't the `sort.IsSorted` still usr the `roachpb.KeyValueByKey` comparator though, which implements an increasing order?  https://github.com/cockroachdb/cockroach/blob/2eda7d0d6c1bdb277cb72eecc21ba8c382b1deab/pkg/roachpb/data.go#L2406

I could implement a `KeyValueByReverseKey` interface that implements the reverse order comparator if that seems better here though.  It didn't seem like there were any reverse order comparators in `roachpb` but I can put in this file itself of course.
</blockquote></details>

`sort.Reverse` will wrap the `roachpb.KeyValueByKey` comparator in a function that inverts the result: https://golang.org/src/sort/sort.go?s=6980:7018#L254. So this should allow us to avoid implementing a `KeyValueByReverseKey` wrapper.

**Review by AlexTalks — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66750)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvnemesis/validator.go, line 533 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66750#-Md2nvAV12x43v2OCT0N:-Md3O3Cr0InQjlDvQdrG:b-drqpgh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ced45f5912d683329152a94ca967917f1d7586b/pkg/kv/kvnemesis/validator.go#L533)):*
> Reverse
ahhh cool.  That does work better :smile: posting fix now.

**Review by AlexTalks — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66750)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvnemesis/validator.go, line 533 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66750#-Md2nvAV12x43v2OCT0N:-Md3OY5v2FdRqsLNolQn:b-l91hrr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ced45f5912d683329152a94ca967917f1d7586b/pkg/kv/kvnemesis/validator.go#L533)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

> Reverse
ahhh cool.  That does work better :smile: posting fix now.
</blockquote></details>

for some reason I thought it worked like Python's `reversed(..)` and just reversed the iterator, makes a lot more sense that as a part of the `sort` pkg it actually reverses the comparator, heh.

**Review by nvb — APPROVED** [review]
:lgtm_strong: 

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66750#-:-Md3fPMi5DtV6ZQ1E1Ka:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @AlexTalks)

**Comment by AlexTalks** [comment]
bors merge

**Pull request merged**
