### PR TITLE
storage: replace queueLog with EventLog in context

### PR DESCRIPTION
**Pull request by RaduBerinde**
Replacing the queueLog with new infrastructure that allows us to embed an
EventLog in the context and use regular logs and events.

@tamird @tschottdorf @andreimatei

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8846)

### CODE REVIEW

**Comment by tamird** [comment]
:dog2: :lgtm:

I'm not sold on the idea of embedding an event log in a context, but seems like that ship has sailed.

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8846#-:-KQ6AOST0Kdfs3u5xDlp:b6kmmg0)*

**Comment by RaduBerinde** [comment]
Why? It's conceptually very close to embedding a tracing Span. One is for short-lived stuff, one is for long-lived stuff, but other than I don't see why we should treat them differently.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8846#-:-KQ6Hj1EqRl0GEKVHJna:b6q944q)*

**Comment by tamird** [comment]
Well, because there's usually no need to pass an event log around - it's
typically a member on some structure.

**Comment by RaduBerinde** [comment]
I don't think our typical usage is ideal. We should be able to set up an EventLog to capture everything that happens inside (and below) a given layer. An example - we currently have spans that stay open for the entire duration of a pg connection. We may want to switch those to be EventLogs instead. Switching between the two is trival with this model.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8846#-:-KQ6IYw9NmX3GnoeolrI:b-2vxpm8)*

**Pull request merged**
