### PR TITLE
Add # of ranges in table to TableDetails API and UI

### LINKED ISSUE #4931: server: add more stats to TableDetails admin API
From @petermattis:

We should also return stats here [in `TableDetailsResponse`] such as number of ranges and number of bytes.

### PR DESCRIPTION
**Pull request by cuongdo**
The biggest changes are to `DistSender` and `InternalExecutor`.

Resolves #4931

cc @mrtracy @tschottdorf

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5361)

### CODE REVIEW

**Comment by cuongdo** [comment]
screenshot 2016-03-17 17 47 58

**Comment by cuongdo** [comment]
The design is ugly but functional. We'll need to make it nicer looking.

**Comment by mrtracy** [comment]
LGTM, but we probably want somebody to double check that the `CountRanges()` method uses a sound technique (I think it's fine).

---

Reviewed 10 of 10 files at r2.
Review status: 10 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[kv/dist_sender.go, line 356 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361#-KD5hEmicUSL3865hNqT:-KD5hEmicUSL3865hNqU:992908528) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4f973ad715539fe17b7de492b7f86fb7955adda/kv/dist_sender.go#L356)):*
Out of hand I would have said this was a bad way to approach the problem (querying one descriptor at a time), but thanks to the cache that's not at all the case.

I imagine this can be optimized further, but given the frequency of usage I don't think it will be a problem.

---

*[ui/styl/partials/layout.styl, line 488 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361#-KD5jKKlorhH_UPyz3Ci:-KD5jKKlorhH_UPyz3Cj:-1760579787) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e8af34440fa13f2fa34d1a8a6112661d3e1501/ui/styl/partials/layout.styl#L488)):*
Whitespace bug at EOF.

---

*[ui/ts/pages/databases.ts, line 226 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361#-KD5jVbRtpjNx1RSA4V_:-KD5jVbRtpjNx1RSA4Va:1436298493) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e8af34440fa13f2fa34d1a8a6112661d3e1501/ui/ts/pages/databases.ts#L226)):*
At this point, I don't think you can assume that ctrl.data() returns non-null.  This should likely be something like `ctrl.data() && ctrl.data().range_count || "Unknown"`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361#-:-KD5k42tcOKSaD3dF4ad:328902315)*

**Comment by petermattis** [comment]
The `InternalExecutor` change :lgtm:. So does the dist_sender change, though I haven't looked at that code in a while. @tschottdorf might want to weigh in.

---

Review status: 10 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/internal.go, line 46 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361#-KD6EjQK6R-Tm93VT0zZ:-KD6EjQK6R-Tm93VT0z_:736662218) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e8af34440fa13f2fa34d1a8a6112661d3e1501/sql/internal.go#L46)):*
I wonder if this method should be `GetTableID` and then add a `roachpb.MakeTableSpan` method.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361#-:-KD6F-c_qRQ0dxZc9mYJ:-1012543858)*

**Comment by cuongdo** [comment]
*[sql/internal.go, line 46 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361#-KD6EjQK6R-Tm93VT0zZ:-KD90fxoHQLIH6DZZuon:590218059) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e8af34440fa13f2fa34d1a8a6112661d3e1501/sql/internal.go#L46)):*
I agree with breaking up this method. However, is `roachpb` the right place for a new `MakeTableSpan` method? It seems like `roachpb` is at a lower level of the stack than the SQL layer. Maybe I'll add `MakeTableSpan` somewhere in the `sql` package?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361)*

**Comment by petermattis** [comment]
Review status: 10 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[sql/internal.go, line 46 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361#-KD6EjQK6R-Tm93VT0zZ:-KD91CwMNKwH3qtYKKhW:924406086) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e8af34440fa13f2fa34d1a8a6112661d3e1501/sql/internal.go#L46)):*
`roachpb` already contains `MakeTableID` (necessary because even non-SQL portions of the system need to know about table IDs). I think it is fine to add `MakeTableSpan` there.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361)*

**Comment by cuongdo** [comment]
*[sql/internal.go, line 46 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361#-KD6EjQK6R-Tm93VT0zZ:-KD92uwybo_ylP_PTuiW:1241100679) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e8af34440fa13f2fa34d1a8a6112661d3e1501/sql/internal.go#L46)):*
I need `keys.MakeTablePrefix()` to make the table span. If I tried calling that from `roachpb`, that'd introduce a circular dependency, because `keys/keys.go` imports `roachpb`. Also, I can't find the method `MakeTableID` anywhere. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361)*

**Comment by cuongdo** [comment]
*[sql/internal.go, line 46 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361#-KD6EjQK6R-Tm93VT0zZ:-KD93W4hhTdxwYGyhHuC:320111943) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e8af34440fa13f2fa34d1a8a6112661d3e1501/sql/internal.go#L46)):*
Maybe add `MakeTableSpan` to `keys/keys.go`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361)*

**Comment by cuongdo** [comment]
*[sql/internal.go, line 46 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361#-KD6EjQK6R-Tm93VT0zZ:-KD94SJ0XpZPMLh3rSax:1763887126) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e8af34440fa13f2fa34d1a8a6112661d3e1501/sql/internal.go#L46)):*
Actually, that won't work either, because `sql` also relies on `keys`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361)*

**Comment by petermattis** [comment]
Review status: 10 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[sql/internal.go, line 46 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361#-KD6EjQK6R-Tm93VT0zZ:-KD96iVrd6wfSQw7wa0A:-981327059) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e8af34440fa13f2fa34d1a8a6112661d3e1501/sql/internal.go#L46)):*
Err, I completely misspoke above in several ways. `MakeTableSpan` should go in `keys` since that is where `MakeTablePrefix` also lives. Apologies for the confusion.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361)*

**Comment by cuongdo** [comment]
Addressed comments so far and rebased. Awaiting feedback from @tschottdorf

---

Review status: 0 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/internal.go, line 46 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361#-KD6EjQK6R-Tm93VT0zZ:-KD99p9VJCwCc9kiuc42:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e8af34440fa13f2fa34d1a8a6112661d3e1501/sql/internal.go#L46)):*
Done.

---

*[ui/styl/partials/layout.styl, line 488 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361#-KD5jKKlorhH_UPyz3Ci:-KD9-AppTjsFIs4vuxV2:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e8af34440fa13f2fa34d1a8a6112661d3e1501/ui/styl/partials/layout.styl#L488)):*
Done.

---

*[ui/ts/pages/databases.ts, line 226 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361#-KD5jVbRtpjNx1RSA4V_:-KD99qE3mviFJC8SgQsV:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e8af34440fa13f2fa34d1a8a6112661d3e1501/ui/ts/pages/databases.ts#L226)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361#-:-KD99rCN2o_YvqYvn8le:2124168835)*

**Comment by petermattis** [comment]
Review status: 0 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/internal.go, line 65 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361#-KD9GQTOlfSZDWD-mKdu:-KD9GQTOlfSZDWD-mKdv:-35888973) ([raw file](https://github.com/cockroachdb/cockroach/blob/df465be3c2457d47d85f862780b95a4e53b3a728/sql/internal.go#L65)):*
This method exists in `keys` now. Did you forget to remove it from here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361)*

**Comment by cuongdo** [comment]
Review status: 0 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/internal.go, line 65 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361#-KD9GQTOlfSZDWD-mKdu:-KD9HNnu_WnBOdhQlZsL:702598329) ([raw file](https://github.com/cockroachdb/cockroach/blob/df465be3c2457d47d85f862780b95a4e53b3a728/sql/internal.go#L65)):*
Yes, thanks for the reminder. Removed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361)*

**Comment by bdarnell** [comment]
Review status: 0 of 13 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[kv/dist_sender.go, line 356 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361#-KD5hEmicUSL3865hNqT:-KDFCQZj1u-k5V7WbI_F:2043735740) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4f973ad715539fe17b7de492b7f86fb7955adda/kv/dist_sender.go#L356)):*
Note that this uses prefetching in the event of a cache miss, so even in the worst case it won't go one at a time (it currently fetches 8 at a time).

This will tend to under-count the number of ranges for tables that are currently growing: the cache is not updated after a split until we try to send an rpc to the range and get an error.  We have to decide whether we want a fast answer that may be stale by an unknown amount of time, or one that is slower (at compared to a cache hit) but gives a more accurate answer. I suspect that the unbounded staleness of the cache will severely reduce the usefulness of this data (a growing table is exactly when this value is interesting), so it's probably better to opt for accuracy (if you're OK with the stale data anyway, then this LGTM)

The best way to get an accurate count is probably to add support for an `EndKey` to `RangeLookup` and then issue a consistent `RangeLookup` RPC with a high `MaxRanges` value (you could also use a `Scan` of the appropriate `Meta2` range). Ideally this would be plumbed through the `DistSender` so that it can populate the cache (since you're doing the work anyway), but that's not necessary for now. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361)*

**Comment by cuongdo** [comment]
Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[kv/dist_sender.go, line 356 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361#-KD5hEmicUSL3865hNqT:-KDOQXf1uCBkK_W54-1T:888338894) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4f973ad715539fe17b7de492b7f86fb7955adda/kv/dist_sender.go#L356)):*
Staleness should be fine for now especially with the other beta UI issues that still need to be fixed. Ideally, we'd have the size stat as # of bytes/KB/MB/GB. Also, we'll need to think of something better for database size (currently unimplemented), which is a little more challenging to implement in a way that's acceptable for UI latency. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5361)*

**Pull request merged**
