### PR TITLE
roachtest: add more logging to drop test

### PR DESCRIPTION
**Pull request by m-schneider**
Before if the drop test fails because the disk hasn't been cleared, it
only logs the reason for failure.

Now if the drop test fails because of uncleared disk, it will log the
amount of storage still being used.

Release note: None

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm: with minor nits.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pkg/cmd/roachtest/drop.go, line 124 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24867#-LAJ4mDhCzGak8kRy1PZ:-LAJ4mDhCzGak8kRy1P_:bx6ci4) ([raw file](https://github.com/cockroachdb/cockroach/blob/02cb6023d338476a6996979bb5c18eb72345571f/pkg/cmd/roachtest/drop.go#L124)):*
> ```Go
> 
> 			var allNodesSpaceCleared bool
> 			var sizeReport bytes.Buffer
> ```

You don't need a buffer for this.

---

*[pkg/cmd/roachtest/drop.go, line 127 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24867#-LAJ4SMnEIM89xU4nQ8f:-LAJ4SMnEIM89xU4nQ8g:b-iw2ls8) ([raw file](https://github.com/cockroachdb/cockroach/blob/02cb6023d338476a6996979bb5c18eb72345571f/pkg/cmd/roachtest/drop.go#L127)):*
> ```Go
> 			// We're waiting a maximum of 10 minutes to makes sure that the drop operations clear the disk.
> 			for i := 0; i < 10; i++ {
> 				sizeReport.Reset()
> ```

`var sizeReport string`

---

*[pkg/cmd/roachtest/drop.go, line 140 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24867#-LAJ4Wbl7JJxqP-DdDzE:-LAJ4Wbl7JJxqP-DdDzF:b-wpdsyj) ([raw file](https://github.com/cockroachdb/cockroach/blob/02cb6023d338476a6996979bb5c18eb72345571f/pkg/cmd/roachtest/drop.go#L140)):*
> ```Go
> 					// Return if the size of the directory is less than 100mb
> 					if size > 1E8 {
> 						allNodesSpaceCleared = allNodesSpaceCleared && false
> ```

This is just `allNodesSpaceCleared = false`

---

*[pkg/cmd/roachtest/drop.go, line 141 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24867#-LAJ4Z980LguvOLxBnwK:-LAJ4Z980LguvOLxBnwL:bv8axg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/02cb6023d338476a6996979bb5c18eb72345571f/pkg/cmd/roachtest/drop.go#L141)):*
> ```Go
> 					if size > 1E8 {
> 						allNodesSpaceCleared = allNodesSpaceCleared && false
> 						sizeReport.WriteString(nodeSpaceUsed)
> ```

sizeReport += nodeSpaceUsed

---

*[pkg/cmd/roachtest/drop.go, line 152 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24867#-LAJ4dGf54YWHKCXq1jC:-LAJ4dGf54YWHKCXq1jD:b-fk5931) ([raw file](https://github.com/cockroachdb/cockroach/blob/02cb6023d338476a6996979bb5c18eb72345571f/pkg/cmd/roachtest/drop.go#L152)):*
> ```Go
> 
> 			if !allNodesSpaceCleared {
> 				sizeReport.WriteString("Disk space has not been freed within 10 minutes of deletion.")
> ```

```
sizeReport += "Disk space ..."
t.Fatal(sizeReport)
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24867#-:-LAJ5-iA5G_808Htc5tV:b-8y1vs2)*

**Comment by m-schneider** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/cmd/roachtest/drop.go, line 124 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24867#-LAJ4mDhCzGak8kRy1PZ:-LAJT3lhCD6c67dlmz5C:b-4hvi0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/02cb6023d338476a6996979bb5c18eb72345571f/pkg/cmd/roachtest/drop.go#L124)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

You don't need a buffer for this.
</blockquote></details>

Got it!

---

*[pkg/cmd/roachtest/drop.go, line 127 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24867#-LAJ4SMnEIM89xU4nQ8f:-LAJT5aY77BT3gfyPCrM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/02cb6023d338476a6996979bb5c18eb72345571f/pkg/cmd/roachtest/drop.go#L127)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

`var sizeReport string`
</blockquote></details>

Done.

---

*[pkg/cmd/roachtest/drop.go, line 140 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24867#-LAJ4Wbl7JJxqP-DdDzE:-LAJT8MO-t_4IU_P1bvs:b-jeslk) ([raw file](https://github.com/cockroachdb/cockroach/blob/02cb6023d338476a6996979bb5c18eb72345571f/pkg/cmd/roachtest/drop.go#L140)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

This is just `allNodesSpaceCleared = false`
</blockquote></details>

That's true.

---

*[pkg/cmd/roachtest/drop.go, line 141 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24867#-LAJ4Z980LguvOLxBnwK:-LAJTN66DnFCAeODwoxY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/02cb6023d338476a6996979bb5c18eb72345571f/pkg/cmd/roachtest/drop.go#L141)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

sizeReport += nodeSpaceUsed
</blockquote></details>

Done.

---

*[pkg/cmd/roachtest/drop.go, line 152 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24867#-LAJ4dGf54YWHKCXq1jC:-LAJTPGjBKYz31DXwZ_s:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/02cb6023d338476a6996979bb5c18eb72345571f/pkg/cmd/roachtest/drop.go#L152)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

```
sizeReport += "Disk space ..."
t.Fatal(sizeReport)
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24867)*

**Comment by tschottdorf** [comment]
Take or leave the remaining nits. Please merge this when you get a chance!

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pkg/cmd/roachtest/drop.go, line 139 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24867#-LAOvYL98YSJeFM88P9f:-LAOvYL98YSJeFM88P9g:b6kupfu) ([raw file](https://github.com/cockroachdb/cockroach/blob/112d3a7445cb1376ab7c213c5d389f0c756ae27d/pkg/cmd/roachtest/drop.go#L139)):*
> ```Go
> 					// Return if the size of the directory is less than 100mb
> 					if size > 1.048E8 {
> 						c.l.printf(fmt.Sprintf("size 1 %s size actual %s\n", humanizeutil.IBytes(int64(size)), humanizeutil.IBytes(int64(1.024E8))))
> ```

This block looks confused, do you want something like

```
if maxSizeBytes := 100 * 1024 * 1024 /* 100mb */; size > maxSizeBytes {
  allNodesSpaceCleared = false
  sizeReport += nodeSpaceUsed
}
```

I'm not sure what printing the message gives you as it's already printed above.

---

*[pkg/cmd/roachtest/drop.go, line 152 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24867#-LAOwXde9lPhlAHYPpi4:-LAOwXde9lPhlAHYPpi5:bgc0aqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/112d3a7445cb1376ab7c213c5d389f0c756ae27d/pkg/cmd/roachtest/drop.go#L152)):*
> ```Go
> 
> 			if !allNodesSpaceCleared {
> 				sizeReport += "Disk space has not been freed within 10 minutes of deletion."
> ```

`+= fmt.Sprintf("disk space usage has not dropped below %s on all nodes.", humanizeutil.IBytes(int64(size)))`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24867#-:-LAOx4Xw4XZiXhxP60il:b-pmc92g)*

**Comment by m-schneider** [comment]
bors r+

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24867#-:-LAU4jqI1XChkY_yxpLb:b-ydi9ay)*

**Pull request merged**
