### PR TITLE
pgwire: only show TZ minutes offset if non-zero

### PR DESCRIPTION
**Pull request by rafiss**
Similar to #57265, this commit matches the PG behavior to
only show the minutes offset if it is non-zero.

Release note (bug fix): Minute timezone offsets are only displayed in
the wire protocol if they are non-zero for TimestampTZ and TimeTZ values.
Previously, they would always display.

Release note (bug fix): Binary TimeTZ values were not being decoded
correctly when being sent as a parameter in the wire protocol. This
is now fixed.

Release note (cli change): The SQL shell now formats times with time
zones so that the minutes and seconds offsets are only shown if they are
non-zero. Also, infinite floating point values are formatted as
`Infinity` rather than `Inf` now.

### CODE REVIEW

**Comment by rafiss** [comment]
Next question -- should we also update the timestamptz->string and timetz->string casts so that they only show the minutes offset if non-zero? That is the Postgres behavior and also that's how we treat the seconds offset already. Downside is that maybe it's too backwards-incompatible. @otan curious on your thoughts

**Review by otan — COMMENTED** [review]
yeah backwards compatibility is hard - you could do this with a cluster setting, off by default in v21.1 -> v21.2 but on by default for new v21.2 clusters. 

the change would have to be made here: https://github.com/cockroachdb/cockroach/blob/695a2d662834da78a9bf5054992dd108273250dd/pkg/sql/sem/tree/datum.go#L2569

does this work correctly on the CLI side? I think you also need to do something with lib/pq a la #62310

**Review by otan — APPROVED** [review]
change as is LGTM

**Comment by rafiss** [comment]
> yeah backwards compatibility is hard - you could do this with a cluster setting, off by default in v21.1 -> v21.2 but on by default for new v21.2 clusters.
> the change would have to be made here: 

yeah i already had the change ready to go, but just wasn't sure about compatibility. i'll look into the cluster setting idea in a different PR -- is there already a thing we do to control default values for upgrades versus new clusters?

> does this work correctly on the CLI side? I think you also need to do something with lib/pq a la #62310

it doesn't show correctly in CLI, i was wondering about that. thanks for the pointer, i will add that to this PR

**Comment by otan** [comment]
> yeah i already had the change ready to go, but just wasn't sure about compatibility. i'll look into the cluster setting idea in a different PR -- is there already a thing we do to control default values for upgrades versus new clusters?

i don't know unfortunately. it's tricky to fix, and i think why i avoided it.

**Comment by rafiss** [comment]
RFAL on the cli change. i made it also account for https://github.com/cockroachdb/cockroach/pull/64760

**Review by otan — APPROVED** [review]

**Comment by rafiss** [comment]
tftr!

bors r=otan

**Comment by rafiss** [comment]
bors r=otan

**Pull request merged**
