### PR TITLE
opt: adjust cost of lookup join on non-key columns

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: add cols-are-key flag in the lookup join private

We currently determine if the lookup columns of a join form a key in
the execbuilder. This change moves this logic in the code that creates
lookup joins, which will allow costing to take this flag into account.

Release note: None

#### opt: allow lax key for lookup join cols-are-key

If the lookup join columns form a lax key, we can consider that a key
because NULLs don't equal anything and are just discarded.

Release note: None

#### opt: adjust cost of lookup join on non-key columns

In 19.2, there was a change in lookup join execution: unless we know
that each lookup returns at most one row (i.e. the lookup columns are
a key), we now limit the number of results in each batch to avoid OOM
conditions. This disables parallelization of spans going to different
ranges, resulting in slower performance. I ran some experiments on a 4
node cluster which showed a ~5x degradation when the lookups are
random; repro details [here](https://gist.github.com/RaduBerinde/9228dd1feea6d39ce5c80ee6a6485079).

This change attempts to adjust the optimizer costing to account for
this degradation, by multiplying the cost of each lookup by 5 in this
case.

Four TPCH queries change. I ran them before and after and these are
the results (median time after a couple of runs on a 4 node cluster):
```
       before  after
  Q2   1.52s   2.16s
  Q8   40.42s  37.79s
  Q9   777s    461s
  Q18  9.16    11.80
```
The improvement on Q9 (by far the slowest query) is significant. I
experimented with smaller factors to see if I could get only Q8 and Q9
to change but that wasn't possible.

Release note (performance improvement): Adjusted the optimizer's cost
of lookup join when the lookup columns aren't a key in the table. This
will cause some queries to switch to using a hash or merge join
instead of a lookup join, improving performance in most cases.

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
This is great! How come the non-Q9 queries get slower? Do they switch plans, I guess?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43003#-:-LvMkiZdC4D2mVr6zWB5:boz2ql3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @jordanlewis, @justinj, and @rytaft)

**Comment by RaduBerinde** [comment]
The four queries are the queries that switch plans. For two of them, the change isn't beneficial. `*= 5` is not what I'd call an exact science :)

**Comment by RaduBerinde** [comment]
I'm hoping that in the future we will have a better interface with KV and it will make this costing less magic.

**Comment by jordanlewis** [comment]
https://five.js.org/

**Review by rytaft — APPROVED** [review]
:lgtm: nice improvement in Q9!

> Reviewed 37 of 37 files at r1, 2 of 2 files at r2, 14 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43003#-:-LvMrNzM3gCM9IpEhBib:b-n1hl6s)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, and @RaduBerinde)

___
*[pkg/sql/opt/memo/testdata/stats/lookup-join, line 303 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43003#-LvMp-QlDPRPachPMas9:-LvMp-QlDPRPachPMasA:b-4rnprs) ([raw file](https://github.com/cockroachdb/cockroach/blob/2302fbc9fbaaec71d3d548ef7d7d94da0c05bf0b/pkg/sql/opt/memo/testdata/stats/lookup-join#L303)):*
> ```
>     "columns": ["x"],
>     "created_at": "2018-01-01 1:00:00.00000+00:00",
>     "row_count": 1000,
> ```

Why this change? Maybe change the stats for "y" too so it's less confusing

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43003)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, and @rytaft)

___
*[pkg/sql/opt/memo/testdata/stats/lookup-join, line 303 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43003#-LvMp-QlDPRPachPMas9:-LvMzYQj5CXH39CVPBr6:b-ic6ez8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2302fbc9fbaaec71d3d548ef7d7d94da0c05bf0b/pkg/sql/opt/memo/testdata/stats/lookup-join#L303)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Why this change? Maybe change the stats for "y" too so it's less confusing
</blockquote></details>

Good catch, updated the `y` stat too. This was necessary to make the lookup join more enticing (or the plan below would change).

**Comment by awoods187** [comment]
Do we have any sense of the relative frequencies these type of queries occur in the wild? If one of the now slower queries occurs much more frequently we may not want to make the change

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43003)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @justinj)

**Comment by RaduBerinde** [comment]
Not really, but from what I have seen the common case is lookup on a key and those plans aren't affected.

**Pull request merged**
