### PR TITLE
changefeedccl: add an initial Changefeed benchmark 

### PR DESCRIPTION
**Pull request by danhhz**
To do this, add some benchmarking infrastructure. I initially tried
benchmarking via the sql `CREATE CHANGEFEED` but it was too noisy, even
when only benchmarking the initial scan phase (and the next step of
trying to incrementally INSERT data for it to pick up during the
benchmark would be even worse.) So, instead, a helper function sets up a
changefeed with a manually controlled clock, which is only used to
select the timestamps used for the ExportRequest polling. Then we can
set up the data ahead of time, noting its timestamps and using them with
the manual clock to make a stable, isolated benchmark. Just look at the
± on these!

    name          time/op
    Changefeed-8    10.9ms ± 3%
    name          speed
    Changefeed-8  9.25MB/s ± 3%
    name          alloc/op
    Changefeed-8    4.19MB ± 0%
    name          allocs/op
    Changefeed-8     56.2k ± 0%

There's some pretty obvious low-hanging performance fruit once this
merges.

Release note: None

### CODE REVIEW

**Comment by danhhz** [comment]
Ping! Any thoughts on this? : - )

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 2 of 4 files at r4.
Review status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/ccl/changefeedccl/helpers_test.go, line 42 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26549#-LEoLiBAApsoPvEjgBDg:-LEoLiBAApsoPvEjgBDh:b-6s387d) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e9b7ec359a3f0e7c6b9ede27f341d0a3c09a304/pkg/ccl/changefeedccl/helpers_test.go#L42)):*
> ```Go
> 	ctx context.Context,
> 	s serverutils.TestServerInterface,
> 	clockFn func() int64,
> ```

nit: I'd just pass a `*hlc.Clock` here.

---

*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 120 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26549#-LEoK66u7f6gCdlU2k65:-LEoK66v3c-VQDuiCO-n:bw0nqfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/49ad01bf9fd5f185a22adaa91078b843fa95e273/pkg/ccl/changefeedccl/changefeed_stmt.go#L120)):*
> ```Go
> 		// Make a channel for runChangefeedFlow to signal once everything has
> 		// been setup okay. This intentionally abuses what would normally be
> 		// hooked up to resultsCh to avoid a bunch of extra plumbing.
> ```

Are you planning to remove this abuse later, or just leave it?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26549#-:-LEoM2W2EaypzxcByVfF:bnfp4nl)*

**Comment by danhhz** [comment]
TFTRs!

> the benchmark mostly benchmarks ExportRequest, right?

With a bunch of polls that each find a single row change, ExportRequest doesn't really dominate in the way you'd expect. Allocations are mostly json generation and cpu time seems to be spent in `(*testKafkaProducer).SendMessages` (??? I'm assuming the channel, dunno still looking into it)

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

---

*[pkg/ccl/changefeedccl/bench_test.go, line 75 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26549#-LEnWH2H786onG-1yU61:-LEoQn-5BHRCm-2rCsYe:b-ngx8e2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e9b7ec359a3f0e7c6b9ede27f341d0a3c09a304/pkg/ccl/changefeedccl/bench_test.go#L75)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

What's this for?
</blockquote></details>

Habit (to make sure defers aren't counted) but it's not needed here. Removed

---

*[pkg/ccl/changefeedccl/helpers_test.go, line 42 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26549#-LEoLiBAApsoPvEjgBDg:-LEoRQx2-qdzc76i2RVi:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e9b7ec359a3f0e7c6b9ede27f341d0a3c09a304/pkg/ccl/changefeedccl/helpers_test.go#L42)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: I'd just pass a `*hlc.Clock` here.
</blockquote></details>

Done

---

*[pkg/ccl/changefeedccl/helpers_test.go, line 84 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26549#-LEnX0Vp2iMFzupMdcGW:-LEoTr3P0kWzuyAB6jZZ:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e9b7ec359a3f0e7c6b9ede27f341d0a3c09a304/pkg/ccl/changefeedccl/helpers_test.go#L84)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

A sanity check for this method wouldn't be bad (perhaps just at the end of the method, check the number of rows inserted)?
</blockquote></details>

Done

---

*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 120 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26549#-LEoK66u7f6gCdlU2k65:-LEoQtL81qsdhsg9PSwq:b-4gt2nb) ([raw file](https://github.com/cockroachdb/cockroach/blob/49ad01bf9fd5f185a22adaa91078b843fa95e273/pkg/ccl/changefeedccl/changefeed_stmt.go#L120)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Are you planning to remove this abuse later, or just leave it?
</blockquote></details>

Planning to leave it for now. Doesn't seem worth it until/if we get a second thing that needs it

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26549#-:-LEoUHuIBcFxFLzSq15K:b-pz3th0)*

**Comment by danhhz** [comment]
bors r=nvanbenschoten,tschottdorf

**Pull request merged**
