### PR TITLE
server: ensure correct authorization for debug pages

### PR DESCRIPTION
**Pull request by BramGruneir**
Up until now, they have been wide open regardless of the cluster settings.

### CODE REVIEW

**Comment by tamird** [comment]
I think you can do this without all the duplication if you use a middleware pattern: write a function that returns a `http.HandlerFunc` which wraps a passed-in `http.HandlerFunc` with this authentication logic. Then do all the wrapping in server/server.go where you register all the handlers.

**Comment by petermattis** [comment]
These need to be tested. See `acceptance/debug_remote_test.go`.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16341#-:-KluqgSPIHK3Z57N5ZXg:bnv98lp)*

**Comment by BramGruneir** [comment]
@tamird Good call.  Done.
@petermattis.  Done.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16341#-:-KlvpgLqnJ736rJr5s0b:b-oevigz)*

**Comment by BramGruneir** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/server/server.go, line 849 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16341#-KlvrUtPZ0ZA1s2cQtFb:-KlvrUtPZ0ZA1s2cQtFc:b688vxl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b5850a0a5258ceffca5ee1396b22b720fdf09f5/pkg/server/server.go#L849)):*
> ```Go
> 	s.mux.Handle(statusPrefix, gwMux)
> 	s.mux.Handle("/health", gwMux)
> 	s.mux.Handle(statusVars, authorizedHandler(http.HandlerFunc(s.status.handleVars)))
> ```

Should statusVars be protected as well?  Seems like it should be.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16341)*

**Comment by mberhault** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/server/server.go, line 849 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16341#-KlvrUtPZ0ZA1s2cQtFb:-KlxSWQY6jgXttUobSr8:b-7ygx0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b5850a0a5258ceffca5ee1396b22b720fdf09f5/pkg/server/server.go#L849)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Should statusVars be protected as well?  Seems like it should be.
</blockquote></details>

Probably not, we still want monitoring to work and shouldn't be exporting metrics with sensitive information.
Even if we do protect it, does that mean we want to disable metrics reporting when we add push-type metrics (eg: graphite)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16341)*

**Comment by petermattis** [comment]
:lgtm: modulo not doing auth for the status vars.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/server/server.go, line 854 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16341#-Klxg1AMsdIKbbjSiiR5:-Klxg1AMsdIKbbjSiiR6:b-sg3or2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b5850a0a5258ceffca5ee1396b22b720fdf09f5/pkg/server/server.go#L854)):*
> ```Go
> 	s.mux.Handle(certificatesDebugEndpoint, authorizedHandler(http.HandlerFunc(s.status.handleDebugCertificates)))
> 	s.mux.Handle(networkDebugEndpoint, authorizedHandler(http.HandlerFunc(s.status.handleDebugNetwork)))
> 	s.mux.Handle(nodesDebugEndpoint, authorizedHandler(http.HandlerFunc(s.status.handleDebugNodes)))
> ```

It might be the case that these could have been added to `debugServeMux` instead of `s.mux`. Maybe. Probably not worth changing now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16341#-:-KlxgAhZ38ECU4ZmZ9Fw:b-7b4alb)*

**Comment by BramGruneir** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/server/server.go, line 849 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16341#-KlvrUtPZ0ZA1s2cQtFb:-KlxqAq1euzbt4gdcuit:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b5850a0a5258ceffca5ee1396b22b720fdf09f5/pkg/server/server.go#L849)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

Probably not, we still want monitoring to work and shouldn't be exporting metrics with sensitive information.
Even if we do protect it, does that mean we want to disable metrics reporting when we add push-type metrics (eg: graphite)?
</blockquote></details>

Done.

---

*[pkg/server/server.go, line 854 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16341#-Klxg1AMsdIKbbjSiiR5:-Klxplwzg5QcwSShhhYV:bklytqv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b5850a0a5258ceffca5ee1396b22b720fdf09f5/pkg/server/server.go#L854)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

It might be the case that these could have been added to `debugServeMux` instead of `s.mux`. Maybe. Probably not worth changing now.
</blockquote></details>

noted.  Since I'm going to be moving a lot of these to `/_status/` with the move to the admin ui, it might be moot.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16341)*

**Pull request merged**
