### PR TITLE
acceptance: remove nodectl, move test fixture data to azure

### PR DESCRIPTION
**Pull request by benesch**

### CODE REVIEW

**Comment by tamird** [comment]
Thanks for picking this up. Feel free to squash my commit away, and looks like there are a few instances of `at.StoreURL` that need to be replaced with `FixtureURL(at.storeFixture)`.

---

Reviewed 4 of 6 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[docs/cloud-resources.md, line 1 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17749#-KroTqR5d05SBnUtUPy8:-KroTqR5d05SBnUtUPy9:b-2wh17i) ([raw file](https://github.com/cockroachdb/cockroach/blob/694269dc7be296e2fec9941200e8b91d49247e70/docs/cloud-resources.md#L1)):*
> ```Markdown
> # Cloud Resources
> ```

This is nice. Hope people read it - might be worth a PSA.

---

*[pkg/acceptance/util.go, line 111 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17749#-KroSdiGfKqLjKeNr37g:-KroSdiGfKqLjKeNr37h:b-bukssl) ([raw file](https://github.com/cockroachdb/cockroach/blob/694269dc7be296e2fec9941200e8b91d49247e70/pkg/acceptance/util.go#L111)):*
> ```Go
> )
> var flagTFLocation = flag.String("location", "eastus",
> 	"the cloud provider location or region in which to create resources",
> ```

I think you can be more specific that this is an azure region; that is already hardcoded in FixtureURL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17749#-:-KroT-NzKc94PIhmcz4W:b-n4v3au)*

**Comment by cuongdo** [comment]
Thanks for taking this on. This looks much cleaner now. Where is the change that adds `FixtureURL`? I see it in `acceptance/util.go`, but it doesn't show up as a change in this PR.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17749#-:-KrpXMV2cbRdPmj30MmO:b-mk74h1)*

**Comment by benesch** [comment]
@cuongdo previously `FixtureURL` was used in allocator_test.go but not backup_test.go; now it's used in both.

@tamird done.

---

Review status: 4 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/acceptance/util.go, line 111 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17749#-KroSdiGfKqLjKeNr37g:-KrveCMVpcfkBSnHwnsK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/694269dc7be296e2fec9941200e8b91d49247e70/pkg/acceptance/util.go#L111)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I think you can be more specific that this is an azure region; that is already hardcoded in FixtureURL.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17749#-:-KrveEo_W2iFhiUSf8Za:b-3cp3l6)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17749#-:-KrveseI5fMGNsgm3jof:bnfp4nl)*

**Comment by benesch** [comment]
TC run of 1 to 3 10GB on this branch: https://teamcity.cockroachdb.com/viewLog.html?buildId=328741&buildTypeId=Cockroach_AllocatorTest1to310g&tab=buildLog

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17749#-:-KrvgM-ATt0mfuXsj9Zp:b-b7ft2a)*

**Comment by benesch** [comment]
Since 1 to 3 10GB was happy, I'm going to merge in time for tonight's nightly run to exercise this further.

**Pull request merged**
