### PR TITLE
kv: Don't evict from leaseholder cache on context cancellations

### LINKED ISSUE #23543: perf: excessive not lease holder errors running tpcc
When starting up `tpcc` we see a spike in not lease holder errors that eventually settles down to a steady stream that never completely goes away. This was noticed on a cluster running tpcc-10k. I'm not sure if it happens on smaller tpcc datasets. There might be a simple explanation for this (e.g. the cluster has 54k ranges). My simple attempts to ensure that the leaseholder cache is fully populated on each node in the cluster were unable to completely eliminate the errors.

screen shot 2018-03-07 at 1 06 06 pm

### PR DESCRIPTION
**Pull request by a-robinson**
This was a major contributor to the hundreds of NotLeaseHolderErrors per
second that we see whenever we run tpc-c at scale. A non-essential batch
request like a QueryTxn would get cancelled, causing the range to be
evicted from the leaseholder cache and the next request to that range to
have to guess at the leaseholder.

This is effectively an extension of https://github.com/cockroachdb/cockroach/pull/26764 that we should have thought to inspect more closely at the time.

Actually fixes https://github.com/cockroachdb/cockroach/issues/23543, which was not fully fixed before. Although I still haven't seen the errors drop all the way to 0, so I'm letting tpc-c 10k continue to run for a while longer to verify that they do. They are continuing to decrease about 15 minutes in. I don't think getting to 0 will be possible because there are still occasional splits and lease transfers), but it looks like it should be able to get down to single digit errors per second from the hundreds it was at before this change.

Also, avoid doing unnecessary sorting by latency of replicas in the dist_sender in the common case when we know who the leaseholder is and plan on sending our request there.

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm: nice catch! I've also run into significant numbers of NotLeaseHolderErrors on larger clusters, so I'm very happy we tracked this down.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30163#-:-LMFzNg33cQxWqgkMIlQ:b-1lkhbn)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/kv/dist_sender.go, line 1338 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30163#-LMFzCvT586g3wSdVHzv:-LMFzCvT586g3wSdVHzw:b-hes9fg) ([raw file](https://github.com/cockroachdb/cockroach/blob/5437d1c56ddc830ae31fb31530c719ceb44d4240/pkg/kv/dist_sender.go#L1338)):*
> ```Go
> 			// account that the local node can't be down) it won't take long until we
> 			// talk to a replica that tells us who the leaseholder is.
> 			if ctx.Err() == nil {
> ```

nit: is this preferable to `if err != context.Canceled && err != context.DeadlineExceeded {`?

**Comment by nvanbenschoten** [comment]
Looks like this was actually somewhat new #23885.

**Review by a-robinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30163)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/kv/dist_sender.go, line 1338 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30163#-LMFzCvT586g3wSdVHzv:-LMIyl2P4aOhFn3blEHY:bqw3n35) ([raw file](https://github.com/cockroachdb/cockroach/blob/5437d1c56ddc830ae31fb31530c719ceb44d4240/pkg/kv/dist_sender.go#L1338)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: is this preferable to `if err != context.Canceled && err != context.DeadlineExceeded {`?
</blockquote></details>

An argument could be made either way. I like this way because with all the wrapping of errors that we do throughout our code base I don't necessarily trust `SendNext` to have returned the context's error directly. Also this matches the check that we do for `ctx.Err()` below to determine whether to mark the error as a `SendError`.

If you prefer the other way for similarly compelling reasons, I can change it.

**Review by nvb — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30163)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/kv/dist_sender.go, line 1338 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30163#-LMFzCvT586g3wSdVHzv:-LMJ-c4I3PuDOPiC3E1G:borrl9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/5437d1c56ddc830ae31fb31530c719ceb44d4240/pkg/kv/dist_sender.go#L1338)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

An argument could be made either way. I like this way because with all the wrapping of errors that we do throughout our code base I don't necessarily trust `SendNext` to have returned the context's error directly. Also this matches the check that we do for `ctx.Err()` below to determine whether to mark the error as a `SendError`.

If you prefer the other way for similarly compelling reasons, I can change it.
</blockquote></details>

The wrapping argument is valid. Let's keep this as is.

**Pull request merged**
