### PR TITLE
sql: fix SQL:2008 FETCH FIRST syntax to allow parameters

### PR DESCRIPTION
**Pull request by nvb**
This is mostly a port of https://github.com/postgres/postgres/commit/1da162e1f5a783bd0ce26e6a07c0138dc8a47d44.

`OFFSET <x> ROWS FETCH FIRST <y> ROWS ONLY` syntax is supposed to accept \<simple value specification\>, which includes parameters as well as literals. When this syntax was added all those years ago, it was done inconsistently, with \<x\> and \<y\> being different subsets of the standard syntax.

Rectify that by making \<x\> and \<y\> accept the same thing, and allowing either a (signed) numeric literal or a c_expr there, which allows for parameters, variables, and parenthesized arbitrary expressions.

I noticed this while trying to run YCSB workload E, which recently switched to use the FETCH FIRST n ROWS ONLY syntax in https://github.com/brianfrankcooper/YCSB/commit/25724e8f2c5dcf2841da9dfa23cb7e45c48a8eb0. I'm curious how people feel about backporting this to v19.2.

Release notes (sql change): The SQL:2008 syntax OFFSET \<x\> ROWS and FETCH FIRST \<y\> ROWS ONLY now accept parameter values.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
1) can you add some tests making the expression correlated. Does the planning code either support, or properly block, such a case without crashing or yielding weird behavior? (e.g. `select (select * ... fetch first t.x from u) from t`)

2) be mindful that the `<...>` in the commit message is not properly rendered when interpreted as markdown in github. You may want to edit that PR desc manually.

3) 

>  I'm curious how people feel about backporting this to v19.2.

I'd be ok considering this to be a bug fix.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45112#-:-M03BXuk9_ncqsiIEQZH:b-o0fe5l)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/parser/sql.y, line 6477 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45112#-M03BwvBAdPWPwjeiRw8:-M03BwvC-6Y65pcRD_oj:b-rh7yp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/04ad100629fa94c4b4efa29e17af13fd220fd412/pkg/sql/parser/sql.y#L6477)):*
> ```Yacc
> // c_expr covers almost all the spec-required cases (and more), but it doesn't
> // cover signed numeric literals, which are allowed by the spec. So we include
> // those here explicitly.
> ```

:100: clever!

**Review by nvb — COMMENTED** [review]
> can you add some tests making the expression correlated. Does the planning code either support, or properly block, such a case without crashing or yielding weird behavior? (e.g. select (select * ... fetch first t.x from u) from t)

Nice intuition! It doesn't work properly. I filed https://github.com/cockroachdb/cockroach/issues/45152 to track this.

>  be mindful that the <...> in the commit message is not properly rendered when interpreted as markdown in github. You may want to edit that PR desc manually.

Hm, I actually had already escaped the arrows in the PR description. Is it not rendering properly for you? It seems to work for me.

> I'd be ok considering this to be a bug fix.

Ack. Thanks for the confirmation.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45112#-:-M0KesEA5Fu5KF9LJABP:b-mj7tcf)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by knz — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45112)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
TFTR!

bors r+

**Pull request merged**
