### PR TITLE
sql: fix statement bundle creation when memo isn't detached 

### LINKED ISSUE #92920: sql: some statement bundles have empty opt.* and schema.sql files
If a statement executes and doesn't commit we call [SetIndexRecommendations](https://github.com/cockroachdb/cockroach/blob/0937c6c2f6d727fe27d708bddec14daaa1ccfe94/pkg/sql/conn_executor_exec.go#L1213) which resets the memo.   This means that when a statement bundle is requested we don't get things derived from the mem (schema and opt plans).  This bug also only occurs when the optimizer context factories memo is left in tact, ie its the same memo in curPlan.mem.  This only happens when we decide NOT to cache the memo (ie we don't call DetachMemo).  This happens when the query has placeholders, is prepared or has stable folds.   This also occurs when DisableMemoReuse is on which mostly affects DDL and "SHOW" queries.

If the transaction commits as part of statement execution we skip the index recommendations and everything is fine but this would be a rare 1PC optimized statement (ie insert fastpath).

Jira issue: CRDB-22053

### PR DESCRIPTION
**Pull request by cucaroach**
When a memo is deemed not resuable we don't detach it from the factory
and this causes problems later when we execute SetIndexRecommendations
which resets the optimizer context which will reset the memo.  This
causes the schema.sql and opt*.txt files to be empty.

Fixes: #92920

Release note: None

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
Great find!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92952#-:-NIXluqy2WAXZ-QCQ6I6:b-arcnu8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach)

___
*[`pkg/sql/plan_opt.go` line 510 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92952#-NIXl-kh-yPKjFyowe7s:-NIXl-ki5s_eHAig9XIv:b-gizg20) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0ec642d122852caadfcab6e89a74ac284cc07f/pkg/sql/plan_opt.go#L510)):*
> ```Go
> //
> // The returned memo is only safe to use in one thread, during execution of the
> // current statement.
> ```

Do we need this warning anymore? (not that it did much good before...)
___
*[`pkg/sql/opt/norm/factory.go` line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92952#-NIXlcZo25TvspFl7D1W:-NIXlcZo25TvspFl7D1X:btw8w5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0ec642d122852caadfcab6e89a74ac284cc07f/pkg/sql/opt/norm/factory.go#L179)):*
> ```Go
> 	m := f.mem
> 	f.mem = nil
> 	f.Init(f.ctx, f.evalCtx, nil /* catalog */)
> ```

Do we need to call `Init` here? Would it be enough to just return `m` and set `f.mem` to nil?

**Review by mgartner — APPROVED** [review]
Nice!

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92952#-:-NIXrALA5-n21VVDMTvN:b-83sjoh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @rytaft)

___
*[`pkg/sql/opt/norm/factory.go` line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92952#-NIXlcZo25TvspFl7D1W:-NIXppKcCgJxn3_EQvhp:b-3uot6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0ec642d122852caadfcab6e89a74ac284cc07f/pkg/sql/opt/norm/factory.go#L179)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Do we need to call `Init` here? Would it be enough to just return `m` and set `f.mem` to nil?
</blockquote></details>

Seems like `Init` shouldn't be necessary. Looks like `opc.reset()` is called whenever an optimizer factory is reused, which calls the factory's `Init` via the optimizer's `Init`. Even in `DetachMemo` above, `f.Init` looks redundant - maybe it was just for additional safety?
___
*[`pkg/sql/explain_bundle_test.go` line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92952#-NIXqgFJ4RxwYWdDdKZw:-NIXqgFJ4RxwYWdDdKZx:b-871exy) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0ec642d122852caadfcab6e89a74ac284cc07f/pkg/sql/explain_bundle_test.go#L109)):*
> ```Go
> 		checkBundle(t, fmt.Sprint(rows), "", func(name, contents string) error {
> 			if name == "opt.txt" {
> 				if contents == "no plan" {
> ```

nit: can you create a constant for this string that's used in both `pkg/sql/explain_bundle.go` and this test? That provides a little bit more safety to prevent this test from becoming a test that always passes if someone changes the "no plan" text in `pkg/sql/explain_bundle.go` without updating this test.

**Review by cucaroach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92952)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/plan_opt.go` line 510 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92952#-NIXl-kh-yPKjFyowe7s:-NIYpKNtCxGx2uu72saO:b-mnewyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0ec642d122852caadfcab6e89a74ac284cc07f/pkg/sql/plan_opt.go#L510)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Do we need this warning anymore? (not that it did much good before...)
</blockquote></details>

I'm not sure.
___
*[`pkg/sql/opt/norm/factory.go` line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92952#-NIXlcZo25TvspFl7D1W:-NIYsdtcEq3KF-rchVoo:b-8fx2ut) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0ec642d122852caadfcab6e89a74ac284cc07f/pkg/sql/opt/norm/factory.go#L179)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Seems like `Init` shouldn't be necessary. Looks like `opc.reset()` is called whenever an optimizer factory is reused, which calls the factory's `Init` via the optimizer's `Init`. Even in `DetachMemo` above, `f.Init` looks redundant - maybe it was just for additional safety?
</blockquote></details>

:+1:
___
*[`pkg/sql/explain_bundle_test.go` line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92952#-NIXqgFJ4RxwYWdDdKZw:-NIYsfYX5vOmDq0dGB6H:b-ul8jrf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0ec642d122852caadfcab6e89a74ac284cc07f/pkg/sql/explain_bundle_test.go#L109)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: can you create a constant for this string that's used in both `pkg/sql/explain_bundle.go` and this test? That provides a little bit more safety to prevent this test from becoming a test that always passes if someone changes the "no plan" text in `pkg/sql/explain_bundle.go` without updating this test.
</blockquote></details>

Good idea

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92952#-:-NIZ0oslCyP_0_anef5h:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @mgartner)

___
*[`pkg/sql/plan_opt.go` line 510 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92952#-NIXl-kh-yPKjFyowe7s:-NIZ0s2p0frlQSRnjN3_:biawm1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0ec642d122852caadfcab6e89a74ac284cc07f/pkg/sql/plan_opt.go#L510)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

I'm not sure.
</blockquote></details>

Ok, no harm in leaving it I guess...
___
*[`pkg/sql/opt/norm/factory.go` line 175 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92952#-NIZ0g833FTXoq1T8N_k:-NIZ0g833FTXoq1T8N_l:b-iagzr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c91cda39e86b73f0e7d950c2c1500395df09443/pkg/sql/opt/norm/factory.go#L175)):*
> ```Go
> // ReleaseMemo is just like DetachMemo but it doesn't call Detach on the memo
> // preserving any statistics information for explain purposes (distinct, null
> // count etc).
> ```

nit: update comment since now it also doesn't call Init anymore

**Review by mgartner — APPROVED** [review]
LGTM

> Reviewed 1 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92952#-:-NIcbfaVD9EWs4i6bjWo:bb6ywmx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach)

**Pull request merged**
