### PR TITLE
 engine: move a couple decoding helpers to enginepb

### PR DESCRIPTION
**Pull request by dt**
Working on #30001.

This moves a couple key decoding helpers from engine, where they share a package with lots of c-deps, to enginepb.
This leaves the old function signatures in place, but calling through to their moved implementations.

This allows sqlbase to call these helpers without pulling in engine and its cdeps dependencies.

Release note: none.

Smaller alternative to #30043.

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm: but could you open an issue discussing the refactoring we talked about in #30043 (feel free to assign to me) and link to it from `enginepb/decode.go`?

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30082#-:-LMAiMDcE3EsxXBNrPmQ:b-3f0uiy)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/engine/batch.go, line 317 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30082#-LMAho3ZEJ3ca2kKZZ6n:-LMAho3ZEJ3ca2kKZZ6o:bwbr6qa) ([raw file](https://github.com/cockroachdb/cockroach/blob/cde09f7acecb1dfd3cdef3284a859a72ae95b41e/pkg/storage/engine/batch.go#L317)):*
> ```Go
> }
> 
> // SplitMVCCKey returns the key and timestamp components of an encoded MVCC key. This
> ```

Can we get rid of these functions entirely? I think that's a better approach than adding an extra function call into performance critical code.
___
*[pkg/storage/engine/enginepb/decode.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30082#-LMAiEqF6LnvfoyEBH11:-LMAiEqGEHnWfeMm4ErP:b-wcvthv) ([raw file](https://github.com/cockroachdb/cockroach/blob/cde09f7acecb1dfd3cdef3284a859a72ae95b41e/pkg/storage/engine/enginepb/decode.go#L81)):*
> ```Go
> 	valSize := v & ((1 << 32) - 1)
> 	if (keySize + valSize) > uint64(len(repr)) {
> 		return key, ts, nil, nil, fmt.Errorf("expected %d bytes, but only %d remaining",
> ```

nit: `errors.Errorf`. That will get rid of the `fmt` import.

**Review by benesch — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1, 6 of 6 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30082#-:-LMDq_Uy5LQRMFQCvC-6:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/ccl/storageccl/engineccl/sst_iterator.go, line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30082#-LMDqFRmAETNUiEWZU_I:-LMDqFRmAETNUiEWZU_J:bfdv0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ceab5d0f2a9a0d09a9bdaf162787d5698aa621f/pkg/ccl/storageccl/engineccl/sst_iterator.go#L136)):*
> ```Go
> 	key := rocksdbInternalKey[:len(rocksdbInternalKey)-8]
> 
> 	if k, ts, err := enginepb.DecodeKey(key); err == nil {
> ```

This seems like it wants `engine.DecodeMVCCKey`, unless I'm missing something.
___
*[pkg/storage/engine/batch.go, line 317 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30082#-LMAho3ZEJ3ca2kKZZ6n:-LMDpkxu6VoPfhVe3Jmm:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/cde09f7acecb1dfd3cdef3284a859a72ae95b41e/pkg/storage/engine/batch.go#L317)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we get rid of these functions entirely? I think that's a better approach than adding an extra function call into performance critical code.
</blockquote></details>

+1
___
*[pkg/storage/engine/enginepb/decode.go, line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30082#-LMDqQvI-EF2oD5C-VC-:-LMDqQvI-EF2oD5C-VC0:b56xpkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ceab5d0f2a9a0d09a9bdaf162787d5698aa621f/pkg/storage/engine/enginepb/decode.go#L25)):*
> ```Go
> )
> 
> // Helpers here a split out of storage/engine since that package also contains
> ```

`s/ a / are /`

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30082)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/ccl/storageccl/engineccl/sst_iterator.go, line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30082#-LMDqFRmAETNUiEWZU_I:-LMDxVEa9RcxhEv01JVV:b-u5odnl) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ceab5d0f2a9a0d09a9bdaf162787d5698aa621f/pkg/ccl/storageccl/engineccl/sst_iterator.go#L136)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This seems like it wants `engine.DecodeMVCCKey`, unless I'm missing something.
</blockquote></details>

Based on comment above, I was avoiding the extra layer of function call.
___
*[pkg/storage/engine/batch.go, line 317 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30082#-LMAho3ZEJ3ca2kKZZ6n:-LMCpUhRBaR4fUHZpuT9:b-k86ihv) ([raw file](https://github.com/cockroachdb/cockroach/blob/cde09f7acecb1dfd3cdef3284a859a72ae95b41e/pkg/storage/engine/batch.go#L317)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

+1
</blockquote></details>

SplitMVCCKey is trivial. Done.

I switched the only internal DecodeKey call. It has couple external callers, mostly in debugging cli that don't care about perf, so I'll leave it around for them. I gave it a slightly more specific name while I was at it.
___
*[pkg/storage/engine/enginepb/decode.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30082#-LMAiEqF6LnvfoyEBH11:-LMCrugfDDpxVF_e2-wy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cde09f7acecb1dfd3cdef3284a859a72ae95b41e/pkg/storage/engine/enginepb/decode.go#L81)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: `errors.Errorf`. That will get rid of the `fmt` import.
</blockquote></details>

Done.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30082)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/storage/engine/enginepb/decode.go, line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30082#-LMDqQvI-EF2oD5C-VC-:-LME0LEH9oBtEtA3ip9n:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ceab5d0f2a9a0d09a9bdaf162787d5698aa621f/pkg/storage/engine/enginepb/decode.go#L25)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

`s/ a / are /`
</blockquote></details>

Done.

**Review by benesch — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30082)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/ccl/storageccl/engineccl/sst_iterator.go, line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30082#-LMDqFRmAETNUiEWZU_I:-LME0cou0FgoTToHVFqd:b-4eol2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ceab5d0f2a9a0d09a9bdaf162787d5698aa621f/pkg/ccl/storageccl/engineccl/sst_iterator.go#L136)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Based on comment above, I was avoiding the extra layer of function call.
</blockquote></details>

Oh, I see. I wouldn't be surprised if the compiler inlined all that away. But don't waste any time checking! You've spent long enough on this as it is and we're hopefully going to push through a more complete refactor eventually.

**Comment by dt** [comment]
bors r=nvanbenschoten r=benesch

**Pull request merged**
