### PR TITLE
Use roachpb value accessors.

### LINKED ISSUE #2839: roachpb.Value initialized inconsistently
We currently use a mix of direct field access to [`(roachpb.Value).Bytes`](https://gist.github.com/tamird/dcdb09f4b92b55e4d2fa) and [getters and setters](https://gist.github.com/tamird/bcc0609775cb30e8d1cd), which results in some error spew (of the form "... value type is not ...") in [tests](https://circle-artifacts.com/gh/cockroachdb/cockroach/8446/artifacts/0/tmp/circle-artifacts.mFXPMZz/test.log).

We should standardize on the use of accessor methods or change `roachpb.Value` to contain a oneof (why isn't it a oneof already?).

### PR DESCRIPTION
**Pull request by thschroeter**
Please take a look.

The first commit replaces direct access to `(roachpb.Value).Bytes` by access through getters and setters. Helpers are added to create `Value`s in tests.

The second commit renames `(roachpb.Value).Bytes` to `BytesUnchecked` to discourage direct use of the field. I've tried to generate a non-exported field `bytes` using `gogoproto.customname`. There seems to be a bug. The name of the field is still `Bytes` (capital first letter) while some generated methods try to access a non existing `bytes` field. I will investigate more and maybe file a bug upstream. Note that `GetBytesUnchecked` is called more often than the checked `GetBytes`. I'm not sure if this change is the right thing to do.

I'm happy to try a different approach or go-rename the new helper methods.

Fixes #2839.

### CODE REVIEW

**Comment by tamird** [comment]
First commit LGTM, but then it's almost all mechanical. For the second commit, I have a slight preference for `RawBytes` rather than `BytesUnchecked`, what do you think?

Either way, we should definitely see what's going on with gogoproto in this regard.

**Comment by tamird** [comment]
Hm, I think the latest changes to gogoproto actually just fixed this issue. I'm going to submit a PR updating our dependencies.

**Comment by thschroeter** [comment]
Great, thanks for your review. Seems like we can go with an un-exported `bytes` field without a new name. Will hold off until our dependencies are updated.

**Comment by tamird** [comment]
@thschroeter updated; want to try now?

**Comment by thschroeter** [comment]
@tamird, having and unexported `bytes` field works, thanks. Looks like I have to set `gogoproto_getters = false` as well, otherwise a `Getbytes` method is generated. I'll send you an update tomorrow for review.

**Comment by tamird** [comment]
Nice! Thanks again.

**Comment by thschroeter** [comment]
Having unexported the `bytes` field, I encounter a panic when running the tests. Somebody is accessing the unexported field through reflection and `reflect.Value.Interface` panics as [documented](https://golang.org/pkg/reflect/#Value.Interface). The test output looks like this
```
--- FAIL: TestAddInfoSameKeyDifferentHops (0.00s)
panic: reflect.Value.Interface: cannot return value obtained from unexported field or method [recovered]
```

Instead of searching a way to avoid this, I'd like to just rename the field to `BytesRaw` as you suggested. What do you think?

**Comment by tamird** [comment]
Can you push your work? I'd like to take a look.

**Comment by petermattis** [comment]
Does the panic come from the `proto.Equal` call?

**Comment by thschroeter** [comment]
@tamird the change is in this [branch](https://github.com/thschroeter/cockroach/tree/unexport-bytes).

@petermattis yes, I think so. See stack trace below.
```
goroutine 112 [running]:
testing.tRunner.func1(0xc820016240)
	/usr/local/go/src/testing/testing.go:450 +0x171
github.com/cockroachdb/cockroach/util/leaktest.AfterTest(0x4da4a78, 0xc820016240)
	/Users/ths/gocode/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:109 +0xcf
reflect.valueInterface(0x43f4300, 0xc82010a1e0, 0xf7, 0xc820380301, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:912 +0xe7
reflect.Value.Interface(0x43f4300, 0xc82010a1e0, 0xf7, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:901 +0x48
github.com/gogo/protobuf/proto.equalAny(0x43f4300, 0xc82010a1e0, 0xf7, 0x43f4300, 0xc82010a1e0, 0xf7, 0xf7)
	/Users/ths/gocode/src/github.com/gogo/protobuf/proto/equal.go:191 +0xcdf
github.com/gogo/protobuf/proto.equalStruct(0x44f9840, 0xc82010a1e0, 0xd9, 0x44f9840, 0xc82010a1e0, 0xd9, 0x4da6d08)
	/Users/ths/gocode/src/github.com/gogo/protobuf/proto/equal.go:117 +0x673
github.com/gogo/protobuf/proto.equalAny(0x44f9840, 0xc82010a1e0, 0xd9, 0x44f9840, 0xc82010a1e0, 0xd9, 0xd9)
	/Users/ths/gocode/src/github.com/gogo/protobuf/proto/equal.go:206 +0x119a
github.com/gogo/protobuf/proto.equalStruct(0x44f95c0, 0xc82010a1e0, 0xd9, 0x44f95c0, 0xc82010a1e0, 0xd9, 0x4406d20)
	/Users/ths/gocode/src/github.com/gogo/protobuf/proto/equal.go:117 +0x673
github.com/gogo/protobuf/proto.equalAny(0x44f95c0, 0xc82010a1e0, 0xd9, 0x44f95c0, 0xc82010a1e0, 0xd9, 0xd9)
	/Users/ths/gocode/src/github.com/gogo/protobuf/proto/equal.go:206 +0x119a
github.com/gogo/protobuf/proto.equalStruct(0x44e06c0, 0xc82010a1e0, 0xd9, 0x44e06c0, 0xc82010a1e0, 0xd9, 0x440c520)
	/Users/ths/gocode/src/github.com/gogo/protobuf/proto/equal.go:117 +0x673
github.com/gogo/protobuf/proto.Equal(0x4da8a58, 0xc82010a1e0, 0x4da8a58, 0xc82010a1e0, 0x4da0028)
	/Users/ths/gocode/src/github.com/gogo/protobuf/proto/equal.go:87 +0x3c6
github.com/cockroachdb/cockroach/gossip.TestAddInfoSameKeyDifferentHops(0xc820016240)
	/Users/ths/gocode/src/github.com/cockroachdb/cockroach/gossip/infostore_test.go:149 +0x57a
testing.tRunner(0xc820016240, 0x47d1ea0)
	/usr/local/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:561 +0x86d
```

**Comment by tamird** [comment]
@thschroeter you can use the gogoproto option `equal` to generate a non-reflective `Equal` method, and then replace proto.Equal(l, r) with l.Equal(r). What do you think?

**Comment by thschroeter** [comment]
@tamird will give it a try.

**Comment by bdarnell** [comment]
I'd rather just use an exported name that is unlikely to be used accidentally instead of dealing with panics any time we hit one of the uses of reflection in the protobuf library. Trying to keep this name unexported is just going to lead to more headaches whenever we update dependencies, etc.

**Comment by tamird** [comment]
> Trying to keep this name unexported is just going to lead to more headaches whenever we update dependencies, etc.

Why is that the case? There's no indication that we're going outside the normal use of gogo/protobuf. I think we can submit a patch upstream to change `Equal` to prefer an `Equal` method if one exists (like Marshal and Unmarshal), but that's strictly ergonomics.

**Comment by thschroeter** [comment]
@tamird I agree with @bdarnell that it's simpler to use a name like `RawBytes` instead of using many additional gogoproto features just to give the field an unexported name.

**Comment by bdarnell** [comment]
The original `protobuf` package is mainly reflection-based. Gogoproto adds the options to generate non-reflective code to replace the reflection-based implementations for performance, but it does not guarantee that *all* reflection will be replaced, even if you enable all the generated methods.

**Comment by tamird** [comment]
Well, I looked into it more; the sad truth is that the `equal` option is a broken mess. Carry on with RawBytes

**Comment by thschroeter** [comment]
Will do, thank for looking into it, @tamird.

**Comment by thschroeter** [comment]
PTAL, thanks. Mostly mechanical except for the helpers `MakeValueFrom...`.

**Comment by tamird** [comment]
LGTM, though we still need a lint to make sure we don't regress here.

**Comment by thschroeter** [comment]
@tamird, how would you add a lint?

**Comment by tamird** [comment]
I'm not really sure yet; something to think about.

**Pull request merged**
