### PR TITLE
exec: consolidate all Append{...} methods into one

### PR DESCRIPTION
**Pull request by asubiotto**
This makes the code much easier to work with.

```
name                    old time/op    new time/op    delta
Append/SimpleAppend-8      199ns ± 4%     190ns ± 1%   -4.51%  (p=0.000 n=9+9)
Append/AppendWithSel-8    2.45µs ± 1%    2.13µs ± 2%  -13.04%  (p=0.000 n=9+9)

name                    old speed      new speed      delta
Append/SimpleAppend-8   41.0GB/s ± 4%  42.9GB/s ± 2%   +4.64%  (p=0.000 n=9+9)
Append/AppendWithSel-8  3.34GB/s ± 1%  3.84GB/s ± 2%  +14.99%  (p=0.000 n=9+9)
```

I'm not sure why this is faster in the SimpleAppend case (it's possible
it's just noise given the variance), but the AppendWithSel case benefits
from less index arithmetic and bounds checks.

Release note: None

### CODE REVIEW

**Review by solongordon — APPROVED** [review]
Nice improvement! I think this will simplify the batch allocator work too. Could we do something similar for the Copy* methods?

I had a few thoughts but all optional.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38364#-:-Li8jA1IBkLqr_YOGK95:br33wi0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @solongordon)

___
*[pkg/sql/exec/coalescer.go, line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38364#-Li8hhlx4q_wb-t3CQHm:-Li8hhlx4q_wb-t3CQHn:bdlbx0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/08a0bb4e09882fab9fb3791e46de26c1ff0f9661/pkg/sql/exec/coalescer.go#L74)):*
> ```Go
> 				appendSel := sel
> 				if sel != nil {
> 					appendSel = sel[:batchSize]
> ```

The `sel` slicing business is kind of confusing to me. I think it would be clearer to pass in `sel` as-is and specify `SrcStartIdx` and `SrcEndIdx`.
___
*[pkg/sql/exec/coldata/vec_tmpl.go, line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38364#-Li8qCSL60Dd2L3I8jBs:-Li8qCSL60Dd2L3I8jBt:b-1ix94d) ([raw file](https://github.com/cockroachdb/cockroach/blob/08a0bb4e09882fab9fb3791e46de26c1ff0f9661/pkg/sql/exec/coldata/vec_tmpl.go#L60)):*
> ```Go
> 			numToAppend := uint16(len(args.Sel))
> 			toCol = append(toCol[:args.DestIdx], make([]_GOTYPE, numToAppend)...)
> 			toColSliced := toCol[args.DestIdx:]
> ```

Nit: Perhaps clearer to build `toColSliced` first and then append it to `toCol`? Unless that's less efficient for some reason.
___
*[pkg/sql/exec/coldata/vec_tmpl.go, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38364#-Li8q04mD6m4FZNJGA4y:-Li8q04mD6m4FZNJGA4z:b8n1luw) ([raw file](https://github.com/cockroachdb/cockroach/blob/08a0bb4e09882fab9fb3791e46de26c1ff0f9661/pkg/sql/exec/coldata/vec_tmpl.go#L70)):*
> ```Go
> 			// away. Or maybe I'm wrong and we should be using srcStartIdx and
> 			// srcEndIdx to index into sel.
> 			m.nulls.ExtendWithSel(args.Src.Nulls(), args.DestIdx, 0 /* srcStartIdx */, numToAppend, args.Sel)
> ```

Maybe for consistency we should also change the `Extend*` signatures to use `SrcEndIdx` rather than `toAppend`.

**Review by jordanlewis — APPROVED** [review]
Agreed w/ Solon this is a great improvement. The code readability of all callers to `Append` just went way up thanks to not having to understand the order of the positional arguments. Very cool! And bonus speed improvement is :thumbsup:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38364#-:-Li8uEsl-pklRewbu3nc:bf3d31c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/exec/coldata/vec.go, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38364#-Li8nn43D7WTpAwD2UN7:-Li8nn43D7WTpAwD2UN8:b-qsrtlk) ([raw file](https://github.com/cockroachdb/cockroach/blob/08a0bb4e09882fab9fb3791e46de26c1ff0f9661/pkg/sql/exec/coldata/vec.go#L82)):*
> ```Go
> 	// Do not call this from normal code - it'll always panic.
> 	_TemplateType() []interface{}
> ```

Please comment. I think this might be vague enough that we could add some examples here?

**Review by asubiotto — COMMENTED** [review]
Yep! Currently working on the Copy methods, although we can probably merge this independently.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38364#-:-Li8vQCY2pUEUhJ7Hvew:bmnnrtc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

___
*[pkg/sql/exec/coalescer.go, line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38364#-Li8hhlx4q_wb-t3CQHm:-Li8vUIg0NcCjXorQnKG:b-4nqthh) ([raw file](https://github.com/cockroachdb/cockroach/blob/08a0bb4e09882fab9fb3791e46de26c1ff0f9661/pkg/sql/exec/coalescer.go#L74)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

The `sel` slicing business is kind of confusing to me. I think it would be clearer to pass in `sel` as-is and specify `SrcStartIdx` and `SrcEndIdx`.
</blockquote></details>

Done. Much clearer now, thanks.
___
*[pkg/sql/exec/coldata/vec.go, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38364#-Li8nn43D7WTpAwD2UN7:-Li9WtdpA80KbR_xd8gh:b-rwc6vk) ([raw file](https://github.com/cockroachdb/cockroach/blob/08a0bb4e09882fab9fb3791e46de26c1ff0f9661/pkg/sql/exec/coldata/vec.go#L82)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Please comment. I think this might be vague enough that we could add some examples here?
</blockquote></details>

Done. Added a pointer to `TestAppend` which should serve that purpose.
___
*[pkg/sql/exec/coldata/vec_tmpl.go, line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38364#-Li8qCSL60Dd2L3I8jBs:-Li8vaamCl3BOTKWIxC4:b-qu6n94) ([raw file](https://github.com/cockroachdb/cockroach/blob/08a0bb4e09882fab9fb3791e46de26c1ff0f9661/pkg/sql/exec/coldata/vec_tmpl.go#L60)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Nit: Perhaps clearer to build `toColSliced` first and then append it to `toCol`? Unless that's less efficient for some reason.
</blockquote></details>

Good point. Done.
___
*[pkg/sql/exec/coldata/vec_tmpl.go, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38364#-Li8q04mD6m4FZNJGA4y:-Li9AqUT9vux-Ux2m1sS:b-i8mx6s) ([raw file](https://github.com/cockroachdb/cockroach/blob/08a0bb4e09882fab9fb3791e46de26c1ff0f9661/pkg/sql/exec/coldata/vec_tmpl.go#L70)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Maybe for consistency we should also change the `Extend*` signatures to use `SrcEndIdx` rather than `toAppend`.
</blockquote></details>

Good idea. I'm going to stay away from touching `Extend*` in this PR but added a TODO.

**Review by solongordon — CHANGES_REQUESTED** [review]
Agreed

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38364#-:-Li9b1ro5bxSbWSJ9Lc4:bqog80t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/exec/coldata/vec.go, line 38 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38364#-Li9aj-NAm7jmSGOXMB1:-Li9aj-NAm7jmSGOXMB2:b-f7lds1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0b39526d94edee274ef7632f2119f297895ca3e/pkg/sql/exec/coldata/vec.go#L38)):*
> ```Go
> 	DestIdx uint64
> 	// SrcStartIdx is the index of the first element in Src that Append will
> 	// append. Ignored if Sel is set.
> ```

Comment out of date
___
*[pkg/sql/exec/coldata/vec_tmpl.go, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38364#-Li8q04mD6m4FZNJGA4y:-Li9a8gt1ebRPFMBOSF4:b-zgebuj) ([raw file](https://github.com/cockroachdb/cockroach/blob/08a0bb4e09882fab9fb3791e46de26c1ff0f9661/pkg/sql/exec/coldata/vec_tmpl.go#L70)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Good idea. I'm going to stay away from touching `Extend*` in this PR but added a TODO.
</blockquote></details>

Perfect, thanks

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38364)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

___
*[pkg/sql/exec/coldata/vec.go, line 38 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38364#-Li9aj-NAm7jmSGOXMB1:-Li9cCFK0UDe2Dam_U-3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0b39526d94edee274ef7632f2119f297895ca3e/pkg/sql/exec/coldata/vec.go#L38)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Comment out of date
</blockquote></details>

Done.

**Review by solongordon — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38364#-:-Li9hcmc9S5bnwQ4JL2h:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

**Comment by asubiotto** [comment]
Removed the behavior that `DestIdx` defaults to the end of the destination slice given that some operators explicitly pass in `0` 🤷‍♂ . I think it's probably safest and least surprising to keep it this way. Maybe we want to do the same with `SrcEndIdx`? It's explicitly specified in every callsite anyway.

**Comment by solongordon** [comment]
I wondered about that. Yeah, I would lean towards making `SrcEndIdx` required as well for least surprise.

**Comment by asubiotto** [comment]
Done.

**Comment by asubiotto** [comment]
bors r=solongordon,jordanlewis

**Pull request merged**
