### PR TITLE
kv: replan rangefeeds with chronic closed ts lag

### LINKED ISSUE #136214: kvserver: mitigate chronic lagging rangefeeds due to rac2 send queues
Now that entries can be arbitrarily delayed by RACv2 pacing, it is also now more likely that a rangefeed planned on a chronically behind store may also have corresponding chronic rangefeed lag.

This issue is to mitigate chronic rangefeed lag that results from RACv2 pacing entries at a quorum speed.

Jira issue: CRDB-44928

### PR DESCRIPTION
**Pull request by kvoli**
When a rangefeed's closed timestamp lags behind the current time, any writes that have occurred in-between will not be emitted. This is problematic in cases where the lag is significant and chronic, as consumers (changefeeds, logical data replication, physical cluster replication) are likewise delayed in their processing. Observing a rangefeed with a chronic lagging closed timestamp will become relatively more likely with quorum replication flow control, as entries are deliberately queued, instead of being sent, to stores which do not have sufficient send tokens.

This commit (re)introduces the concept of cancelling lagging rangefeeds, so that they may be replanned and retried on another replica. The other replica may also have this issue, however there should be at least a quorum of voting replicas with a similar closed timestamp that would be suitable.

The replanning on a different replica is handled already by existing machinery. This commit introduces an observer which generates a signal indicating that the rangefeed should be cancelled. The signal also encapsulates the existing logic to nudge a rangefeed as well.

The criteria for cancelling a rangefeed is influenced by two thresholds, defined as cluster settings:

```
kv.rangefeed.lagging_closed_timestamp_cancel_multiple
(default = 20 x closed ts target duration = 60s)
```

```
kv.rangefeed.lagging_closed_timestamp_cancel_min_lagging_duration
(default = 60s)
```

When a replica's closed timestamp has sustained lag greater than:

```
kv.rangefeed.lagging_closed_timestamp_cancel_multiple * kv.closed_timestamp.target_duration
```

For at least:

```
`kv.rangefeed.lagging_closed_timestamp_cancel_min_lagging_duration`
```

duration, the rangefeed will be cancelled and then re-planned on the client. This can be visualized in the following diagram, where there is an initial spike over the lag threshold, which is recovered from so the rangefeed wouldn't be cancelled. The second drop below the lag threshold is sustained for greater than the duration threshold, so the rangefeed is then cancelled for replanning:

```
lag=0          ─────────────────────────────────────────────────────

observed lag   ─────────┐
                        │
                        │
                        │     ┌───────┐
lag threshold  ─────────┼─────┼───────┼──────────────────────────────
                        │     │       └───┐
                        │     │           └─────┐
                        └─────┘                 └──────┐
                                                       └────────────
                                      ◄────────────────────────────►
                                         exceeds duration threshold
```

Note we could also prevent accepting a rangefeed registration if the lag were sufficient, however the behavior change here applies only to lag which as been observed to be sustained over time, without historical data, we cannot apply identical decision logic on registration.

---

kvserver: add metric for rangefeed cancellations due to lag

Add a new counter metric,
`kv.rangefeed.closed_timestamp.slow_ranges.cancelled`, which is
incremented each time a rangefeed is cancelled server-side due to a
chronically lagging closed timestamp (see https://github.com/cockroachdb/cockroach/pull/137531).

Fixes: #136214
Release note: None

### CODE REVIEW

**Comment by kvoli** [comment]
Extended CI will hit https://github.com/cockroachdb/cockroach/issues/137396. Ignoring for now.

**Review by arulajmani — COMMENTED** [review]
> Reviewed 1 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137531)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli, @stevendanna, @sumeerbhola, and @wenyihu6)

___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 919 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137531#-OEOte1e8XzPkZSUVkyZ:-OEOte1e8XzPkZSUVky_:bjzlgin) ([raw file](https://github.com/cockroachdb/cockroach/blob/650c4e79e4e470289c0c3d24b3b64c293d9e17cb/pkg/kv/kvserver/replica_rangefeed.go#L919)):*
> ```Go
> 					// fail open, thrashing the rangefeed around the cluster.
> 					//
> 					// Note that we use the REASON_RANGEFEED_CLOSED, as adding a new
> ```

We've previously looked at these reasons in customer escalations. If adding a new reason is really out of the question (do we really need mixed version compatibility?), consider adding a server side metric for when we're disconnecting the rangefeed because we've exceeded the threshold.

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137531)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @stevendanna, @sumeerbhola, and @wenyihu6)

___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 919 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137531#-OEOte1e8XzPkZSUVkyZ:-OEPAsCO3tqKJ79mZT6_:bg0l849) ([raw file](https://github.com/cockroachdb/cockroach/blob/650c4e79e4e470289c0c3d24b3b64c293d9e17cb/pkg/kv/kvserver/replica_rangefeed.go#L919)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

We've previously looked at these reasons in customer escalations. If adding a new reason is really out of the question (do we really need mixed version compatibility?), consider adding a server side metric for when we're disconnecting the rangefeed because we've exceeded the threshold.
</blockquote></details>

My assumption is that we cannot afford to enable RACv2 `apply_to_all` and not also have this cancellation behavior. 

If that assumption is true, then I think this depends on whether we could have an earlier kvclient version running on a SQL pod -- I'm not too sure where that discussion ended up, but it appeared to me that we could have <v25.1 SQL pods while the host cluster isn't at that version. 

I'll dig a bit more. If what I mention above isn't true, then I'd much prefer to use a new cluster version and return something like:

https://github.com/kvoli/cockroach/blob/5ae4d3a4366a36efe4dfb82e88bc66d1c526259a/pkg/kv/kvpb/errors.proto#L657-L659

Agree on adding a server side metric, I'll push that change on-top of this.

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137531)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @stevendanna, @sumeerbhola, and @wenyihu6)

___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 919 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137531#-OEOte1e8XzPkZSUVkyZ:-OEPNRkr5nzV4mQpWHuT:bfkjw1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/650c4e79e4e470289c0c3d24b3b64c293d9e17cb/pkg/kv/kvserver/replica_rangefeed.go#L919)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

My assumption is that we cannot afford to enable RACv2 `apply_to_all` and not also have this cancellation behavior. 

If that assumption is true, then I think this depends on whether we could have an earlier kvclient version running on a SQL pod -- I'm not too sure where that discussion ended up, but it appeared to me that we could have <v25.1 SQL pods while the host cluster isn't at that version. 

I'll dig a bit more. If what I mention above isn't true, then I'd much prefer to use a new cluster version and return something like:

https://github.com/kvoli/cockroach/blob/5ae4d3a4366a36efe4dfb82e88bc66d1c526259a/pkg/kv/kvpb/errors.proto#L657-L659

Agree on adding a server side metric, I'll push that change on-top of this.
</blockquote></details>

Stacked another commit w/ the metric change.

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 3 of 9 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137531)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @kvoli, @stevendanna, and @wenyihu6)

___
*[`-- commits` line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137531#-OEPc6Nj42TQK6FYtPMX:-OEPc6Nj42TQK6FYtPMY:b-51ffkj):*
nit: which has been ...
nit: the rest of the sentence reads a bit odd. May be worth breaking into two sentences.
___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 862 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137531#-OEPeC9F7kjonsYrwgEt:-OEPeC9F7kjonsYrwgEu:b-kubxi6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5899f1774ff895ac0ed6321c22a715990cbafe8/pkg/kv/kvserver/replica_rangefeed.go#L862)):*
> ```Go
> func (r *Replica) handleClosedTimestampUpdateRaftMuLocked(
> 	ctx context.Context, closedTS hlc.Timestamp,
> ) (exceedsSlowLagThresh bool) {
> ```

How frequently is this method called if the closed timestamps is not being updated at all?
And is this periodic call being done from `startRangefeedUpdater` which has some logic related to a `refresh` interval which seems to use `kv.closed_timestamp.side_transport_interval` of 200ms.

When this is called, and we are using leader leases, the lease verification for the nudge will succeed but there is a TODO buried there:
```
// TODO(nvanbenschoten): evaluate whether this is too expensive to compute for  
// every lease status request. We may need to cache this result. If, at that  
// time, we determine that it is sufficiently cheap, we should either compute  
// it unconditionally, regardless of the lease type or let leases.Status  
// decide when to compute it. See #125255.  
if in.Lease.Type() == roachpb.LeaseLeader {  
  in.RaftStatus = r.raftLeadSupportStatusRLocked()  
}
```
@arulajmani should we be worried about the cost of this? I am guessing not, since doesn't every proposal evaluation need to check the lease, which will be far higher frequency?

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137531)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @kvoli, @sumeerbhola, and @wenyihu6)

___
*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/137531#-OEPVN6u8c-8mIfc2AGf:-OEPVN6u8c-8mIfc2AGg:bdqjrpv) (no related file):*
Overall this looks pretty good to me!
___
*[`pkg/kv/kvserver/replica_rangefeed_lag_observer.go` line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137531#-OEPUM_ABEM1VpaajRc5:-OEPUM_ABEM1VpaajRc6:b1m46he) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5899f1774ff895ac0ed6321c22a715990cbafe8/pkg/kv/kvserver/replica_rangefeed_lag_observer.go#L86)):*
> ```Go
> 		"`kv.closed_timestamp.target_duration` behind the current time,"+
> 		"for at least this duration, cancel the rangefeed",
> 	time.Minute,
> ```

I wonder if we could be less aggressive here. Namely, I could see this still being pretty useful even if this was 5 minutes. No strong opinion though.
___
*[`pkg/kv/kvserver/replica.go` line 345 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137531#-OEPSwQw4h5X9JcFesj5:-OEPSwQx5t9PyZ6Apq9g:b-3feq8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5899f1774ff895ac0ed6321c22a715990cbafe8/pkg/kv/kvserver/replica.go#L345)):*
> ```Go
> 		replicaStateScratchForFlowControl map[roachpb.ReplicaID]rac2.ReplicaStateInfo
> 
> 		// rangeFeedCTLagObserver is used to observe the closed timestamp lag of
> ```

s/rangeFeed/rangefeed/

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137531)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @kvoli, and @wenyihu6)

___
*[`pkg/kv/kvserver/replica_rangefeed_lag_observer.go` line 102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137531#-OEPkUqmDb7k3nBle9O7:-OEPkUqmDb7k3nBle9O8:bjre7c4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5899f1774ff895ac0ed6321c22a715990cbafe8/pkg/kv/kvserver/replica_rangefeed_lag_observer.go#L102)):*
> ```Go
> 	signal := rangeFeedCTLagSignal{targetLag: closedts.TargetDuration.Get(sv)}
> 	nudgeLagThreshold := signal.targetLag * laggingRangeFeedCTNudgeMultiple
> 	cancelLagThreshold := signal.targetLag * time.Duration(RangeFeedLaggingCTCancelMultiple.Get(sv))
> ```

if cancelation is disabled, will this evaluate to 0? If yes, this is a bit confusing and could use a code comment here.
___
*[`pkg/kv/kvserver/replica_rangefeed_lag_observer.go` line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137531#-OEPlHKVDXEQuZanbFmy:-OEPlHKVDXEQuZanbFmz:bdpgy9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5899f1774ff895ac0ed6321c22a715990cbafe8/pkg/kv/kvserver/replica_rangefeed_lag_observer.go#L106)):*
> ```Go
> 
> 	signal.lag = now.Sub(closedTS)
> 	if signal.lag <= cancelLagThreshold {
> ```

This is a nit, so feel free to ignore: by setting `cancelLagThreshold` to `time.Duration(math.MaxInt64)` when cancelation is disabled, I think the code is easier to follow.
___
*[`pkg/kv/kvserver/replica_rangefeed_lag_observer.go` line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137531#-OEPlmPb5F87IiPD0jaa:-OEPlmPb5F87IiPD0jab:b-y7jt0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5899f1774ff895ac0ed6321c22a715990cbafe8/pkg/kv/kvserver/replica_rangefeed_lag_observer.go#L113)):*
> ```Go
> 	} else if r.exceedsCancelLagStartTime.IsZero() {
> 		r.exceedsCancelLagStartTime = now
> 	}
> ```

an else here would allow simplifying:
```
signal.exceedsCancelLagThreshold = now.Sub(r.exceedsCancelLagStartTime) > cancelLagMinDuration
```
___
*[`pkg/kv/kvserver/replica_rangefeed_lag_observer.go` line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137531#-OEPm7oT8XVX3PuCFTso:-OEPm7oT8XVX3PuCFTsp:bd40qom) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5899f1774ff895ac0ed6321c22a715990cbafe8/pkg/kv/kvserver/replica_rangefeed_lag_observer.go#L117)):*
> ```Go
> 	signal.exceedsCancelLagThreshold = !r.exceedsCancelLagStartTime.IsZero() &&
> 		now.Sub(r.exceedsCancelLagStartTime) > cancelLagMinDuration
> 	return signal
> ```

another nit:
```
return signal{
...
}
```
is easier for the reader to be sure that all fields have been initialized, instead of piecemeal initialization. This function is small enough, that it is still ok-ish for the reader.

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137531)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @stevendanna, @sumeerbhola, and @wenyihu6)

___
*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/137531#-OEPVN6u8c-8mIfc2AGf:-OEPy4OG33tTkhMjOyDT:bx5ol6w) (no related file):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Overall this looks pretty good to me!
</blockquote></details>

TYFTRs!
___
*[`-- commits` line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137531#-OEPc6Nj42TQK6FYtPMX:-OEPyi-w607Jqrxt7Vch:b-bw8e14):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: which has been ...
nit: the rest of the sentence reads a bit odd. May be worth breaking into two sentences.
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/replica.go` line 345 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137531#-OEPSwQw4h5X9JcFesj5:-OEPypVw4N7c_xUqCxt7:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5899f1774ff895ac0ed6321c22a715990cbafe8/pkg/kv/kvserver/replica.go#L345)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

s/rangeFeed/rangefeed/
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 862 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137531#-OEPeC9F7kjonsYrwgEt:-OEQEnLh0oVMCscrqx5a:b9rk40j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5899f1774ff895ac0ed6321c22a715990cbafe8/pkg/kv/kvserver/replica_rangefeed.go#L862)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

How frequently is this method called if the closed timestamps is not being updated at all?
And is this periodic call being done from `startRangefeedUpdater` which has some logic related to a `refresh` interval which seems to use `kv.closed_timestamp.side_transport_interval` of 200ms.

When this is called, and we are using leader leases, the lease verification for the nudge will succeed but there is a TODO buried there:
```
// TODO(nvanbenschoten): evaluate whether this is too expensive to compute for  
// every lease status request. We may need to cache this result. If, at that  
// time, we determine that it is sufficiently cheap, we should either compute  
// it unconditionally, regardless of the lease type or let leases.Status  
// decide when to compute it. See #125255.  
if in.Lease.Type() == roachpb.LeaseLeader {  
  in.RaftStatus = r.raftLeadSupportStatusRLocked()  
}
```
@arulajmani should we be worried about the cost of this? I am guessing not, since doesn't every proposal evaluation need to check the lease, which will be far higher frequency?
</blockquote></details>

Checking this now, the side transport interval callout matches what I recall seeing.
___
*[`pkg/kv/kvserver/replica_rangefeed_lag_observer.go` line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137531#-OEPUM_ABEM1VpaajRc5:-OEQ4zt05Jas04oT02-i:b-zfuvew) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5899f1774ff895ac0ed6321c22a715990cbafe8/pkg/kv/kvserver/replica_rangefeed_lag_observer.go#L86)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I wonder if we could be less aggressive here. Namely, I could see this still being pretty useful even if this was 5 minutes. No strong opinion though.
</blockquote></details>

Replied on slack. I generally agree and the current data we have supports that, but we don't have great data for when RACv2 is enabled -- so I'll defer till later to make a change, if necessary.
___
*[`pkg/kv/kvserver/replica_rangefeed_lag_observer.go` line 102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137531#-OEPkUqmDb7k3nBle9O7:-OEQ6lGp1J8n6rbIbVHO:b-y0c4aw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5899f1774ff895ac0ed6321c22a715990cbafe8/pkg/kv/kvserver/replica_rangefeed_lag_observer.go#L102)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

if cancelation is disabled, will this evaluate to 0? If yes, this is a bit confusing and could use a code comment here.
</blockquote></details>

It will evaluate to zero, updated and added a test case to verify the disabled behavior is correct.
___
*[`pkg/kv/kvserver/replica_rangefeed_lag_observer.go` line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137531#-OEPlHKVDXEQuZanbFmy:-OEQ6yFd4P564MaEAkVW:bm5feck) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5899f1774ff895ac0ed6321c22a715990cbafe8/pkg/kv/kvserver/replica_rangefeed_lag_observer.go#L106)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This is a nit, so feel free to ignore: by setting `cancelLagThreshold` to `time.Duration(math.MaxInt64)` when cancelation is disabled, I think the code is easier to follow.
</blockquote></details>

That seems much cleaner, updated to set to the max int64 unless enabled.
___
*[`pkg/kv/kvserver/replica_rangefeed_lag_observer.go` line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137531#-OEPlmPb5F87IiPD0jaa:-OEQ75564fRFnVZUjQ_Q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5899f1774ff895ac0ed6321c22a715990cbafe8/pkg/kv/kvserver/replica_rangefeed_lag_observer.go#L113)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

an else here would allow simplifying:
```
signal.exceedsCancelLagThreshold = now.Sub(r.exceedsCancelLagStartTime) > cancelLagMinDuration
```
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/replica_rangefeed_lag_observer.go` line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137531#-OEPm7oT8XVX3PuCFTso:-OEQ8W6G2q3MpLucvKF1:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5899f1774ff895ac0ed6321c22a715990cbafe8/pkg/kv/kvserver/replica_rangefeed_lag_observer.go#L117)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

another nit:
```
return signal{
...
}
```
is easier for the reader to be sure that all fields have been initialized, instead of piecemeal initialization. This function is small enough, that it is still ok-ish for the reader.
</blockquote></details>

Good idea, done.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137531#-:-OEQJaw--8nGQF3NrIO7:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani, @stevendanna, and @wenyihu6)

**Comment by wenyihu6** [comment]
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

TYFTRs!
</blockquote></details>

:lgtm: I’ll defer the final stamp to Steven tho as he has been discussing the heuristics with you all and has a clearer understanding. I recall discussing whether `evict = true` is necessary. After more reading, I agree with you that `evict = true` shouldn’t be required. The `NextInternalClient` will handle incrementing `nextReplicaIdx` and finding the next replica after rangefeed restarts, so we should keep the transport (https://github.com/cockroachdb/cockroach/blob/027a191662e02ddf6281885b808b000fb60d42ce/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L295 and https://github.com/cockroachdb/cockroach/blob/c83c57d354741ac36740894f7387c014eb6c09fe/pkg/kv/kvclient/kvcoord/transport.go#L250-L263).

**Review by wenyihu6 — APPROVED** [review]

**Comment by kvoli** [comment]
Rebased.

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137531)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @arulajmani, @stevendanna, and @sumeerbhola)

___
*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/137531#-OEPVN6u8c-8mIfc2AGf:-OEQ_uesAQfQL7V1PAb-:bx4a6g1) (no related file):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

:lgtm: I’ll defer the final stamp to Steven tho as he has been discussing the heuristics with you all and has a clearer understanding. I recall discussing whether `evict = true` is necessary. After more reading, I agree with you that `evict = true` shouldn’t be required. The `NextInternalClient` will handle incrementing `nextReplicaIdx` and finding the next replica after rangefeed restarts, so we should keep the transport (https://github.com/cockroachdb/cockroach/blob/027a191662e02ddf6281885b808b000fb60d42ce/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L295 and https://github.com/cockroachdb/cockroach/blob/c83c57d354741ac36740894f7387c014eb6c09fe/pkg/kv/kvclient/kvcoord/transport.go#L250-L263).
</blockquote></details>

TYFTRs!

Will merge once CI goes green. We have a bit before the cut, so should be able to address anything glaring that falls out of testing before then. 

Agree on not using evict here, since we expect the descriptor to be usable and the next replica retried. 
___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 862 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137531#-OEPeC9F7kjonsYrwgEt:-OEQZP9C3FOPJmd_Q2hm:bbu85tb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5899f1774ff895ac0ed6321c22a715990cbafe8/pkg/kv/kvserver/replica_rangefeed.go#L862)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Checking this now, the side transport interval callout matches what I recall seeing.
</blockquote></details>

This matches up, its coming from the closed ts transport interval, default 200ms:
https://github.com/kvoli/cockroach/blob/b458f9fea88759dd3c20d7a47fb91d6bac612d31/pkg/kv/kvserver/closedts/setting.go#L29-L35

I'll defer to @arulajmani  for the other question.

**Comment by kvoli** [comment]
I'm going to eagerly bors, as the extended CI was green before merging.

TYFTRs!

bors r=sumeerbhola,wenyihu6

**Pull request merged**
