### PR TITLE
cli: actually fetch per-node tables from nodes

### PR DESCRIPTION
**Pull request by tbg**
Ignore the first commit, it's #36155.

----

The previous code used the sql connection to the first node to fetch all
data. Unfortunately, we have to guess the SQL connection string for the
other nodes (and may not get it right), but I've verified that this doesn't
fail out the whole `debug zip` process. In the process of verifying that
(running with one node down) I also fixed a few buglets related to that,
including creating files multiple times and generally confused-looking
output.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
@bdarnell Dan is out today, so maybe you can give this a look. Not super urgent.

**Review by bdarnell — APPROVED** [review]
LGTM as a quick fix, but we should really have a guesswork-free way of doing this. Either internal forwarding from one server to another (which is how debug zips get most of their per-node data) or explicitly get the set of sql endpoints. 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36167#-:-Lb-lWB-54AmL-aXw8yj:byz1uv7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz)

**Comment by tbg** [comment]
> Either internal forwarding from one server to another

What were you thinking here? An endpoint that takes a SQL query and passes it to the destination server?

> explicitly get the set of sql endpoints.

Seems difficult, when you're in some docker deployment the networking probably won't make this any better than this PR. I'd guess forwarding is a lot less trouble (or we force the user to pass all sql urls to debug zip, but that's crappy UX).

**Comment by tbg** [comment]
The tempting thing about that SQL endpoint is that it's also a powerful debugging tool. Someone gives us UI access, and we get to run queries as root. That's also not at all what folks think the UI lets you do, so it's scary. Perhaps the endpoint needs to be specifically to collect hard-coded debug info via SQL, so we wouldn't list them in `cli/debug` any more but in the endpoint. WDYT?

**Comment by bdarnell** [comment]
> What were you thinking here? An endpoint that takes a SQL query and passes it to the destination server?

No, I mean extending the virtual table mechanism with something that will make the RPCs for you, so you can query everything from a single sql connection. For each `crdb_internal.node_*` table, have an `all_nodes_*` counterpart that adds a `node_id` column and includes data from all nodes.

**Comment by tbg** [comment]
I see. Hmm, that's a bigger project. I won't pull on that now.

bors r=bdarnell

**Pull request merged**
