### PR TITLE
colexec: plan disk-spilling enabled operators when vectorize=auto

### LINKED ISSUE #45172: colexec: spill to disk when vectorize="auto"
This requires us changing the current "auto" setting to something that can be reverted back to, e.g. "192auto", and adding a new "auto" setting that is the default, that runs vectorized queries that have operators that can spill to disk.

### PR DESCRIPTION
**Pull request by asubiotto**
Each commit turns on one of the HashRouter, Sorter, and HashJoiner and includes the relevant test changes (all plan changes).

The only thing of note is that explain analyze plans include both row and column stats for wrapped operators. It seems like this is expected though (according to `vectorize_local`) and changing this naively results in other failures (`unexpectedly not collecting stats`), so will leave this up to discussion of whether we want to change this. Regardless, I think it is out of scope for this PR.

Closes #45172

### CODE REVIEW

**Comment by asubiotto** [comment]
Note that no tests are yet run with `fakedist-vec-disk`, since it is best to wait until #45505 is fixed.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 16 of 16 files at r2, 12 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45582#-:-M1RFm112g3CEPL2vB5O:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colflow/vectorized_flow.go, line 948 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45582#-M1RF7Up6f7o7JUe2MN7:-M1RF7Up6f7o7JUe2MN8:bb3rd29) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5fb62e0c676896928c30de6e63430f607cf4e9a/pkg/sql/colflow/vectorized_flow.go#L948)):*
> ```Go
> 			// buffer an unlimited number of tuples, even though it falls back to
> 			// disk. vectorize=auto does support this.
> 			return nil, errors.Errorf("hash router encountered when vectorize=auto")
> ```

nit: `s/auto/192auto/g`.

**Comment by asubiotto** [comment]
bors r=yuzefovich

**Comment by andreimatei** [comment]
Can this be responsible for this failure?
```
testdata/logic_test/postgresjoin:1577: SELECT 'x' AS "xxx", * FROM J1_TBL t1 (a, b, c) JOIN J2_TBL t2 (a, d) USING (a) ORDER BY a, d
                expected success, but found
                (XX000) internal error: unexpected error from the vectorized runtime: file does not exist
                error.go:70: in func1()
```
https://teamcity.cockroachdb.com/viewLog.html?buildId=1779463&buildTypeId=Cockroach_UnitTests

**Pull request merged**
