### PR TITLE
sql: declarative schema changer does not always clean up descriptors

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the declarative schema changer was missing logic
for cleaning up dropped descriptors for databases, schemas,
and types. This was inadequate because the descriptors
tables would have stale entries left. Additionally, when
dropping a schema we never cleaned up the database level
list. To address this, this patch add support for properly
deleting these descriptors via the schema change job or
GC. As well as cleaning up the database level schema list,
and correcting the default RESTRICT behaviour for DROP
DATABASE.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
Do we create gc jobs for indexes?

> Reviewed 22 of 37 files at r1, 19 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73356#-:-MqFpqTVEcjSlqnESi19:b-oqx6o2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @postamar)

___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_schema.go, line 44 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73356#-MqFjs_0Ds180K2AOaS8:-MqFjs_0Ds180K2AOaS9:brh8vib) ([raw file](https://github.com/cockroachdb/cockroach/blob/31d233c11dd9b74b15621f64b972da86af22d64c/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_schema.go#L44)):*
> ```Go
> 	behavior tree.DropBehavior,
> ) (nodeAdded bool, dropIDs catalog.DescriptorIDSet) {
> 	//
> ```

stray comment
___
*[pkg/sql/schemachanger/scdeps/sctestdeps/test_deps.go, line 657 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73356#-MqFpdZqBfVSJskmkJOO:-MqFpdZqBfVSJskmkJOP:b-vsej2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/31d233c11dd9b74b15621f64b972da86af22d64c/pkg/sql/schemachanger/scdeps/sctestdeps/test_deps.go#L657)):*
> ```Go
> 	}
> 	for _, deletedID := range b.descriptorsToDelete.Ordered() {
> 		b.s.LogSideEffectf("deleted descriptor #%d\n", deletedID)
> ```

I don't think the `\n` should be here
___
*[pkg/sql/schemachanger/scexec/executor.go, line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73356#-MqFkPOHEBf5jgyP25-u:-MqFkPOHEBf5jgyP25-v:b-qy5v2f) ([raw file](https://github.com/cockroachdb/cockroach/blob/31d233c11dd9b74b15621f64b972da86af22d64c/pkg/sql/schemachanger/scexec/executor.go#L48)):*
> ```Go
> // UpdateDescriptorJobIDs updates the job ID for the schema change on the
> // specified set of table descriptors.
> func UpdateDescriptorJobIDs(
> ```

one of us is going to hit rebase trouble with this. It's interesting. We'll need to order the operations differently. I can take that sooner rather than later. 
___
*[pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go, line 331 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73356#-MqFl_dqDNMUdw-w4TAF:-MqFl_dqDNMUdw-w4TAG:b-qmjvx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/31d233c11dd9b74b15621f64b972da86af22d64c/pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go#L331)):*
> ```Go
> }
> 
> func (m *visitor) CreateGcJobForTable(ctx context.Context, op scop.CreateGcJobForTable) error {
> ```

today when we drop a database, my understanding is that we create a single GC job. What do we do in the new schema changer? 
___
*[pkg/sql/schemachanger/testdata/drop, line 260 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73356#-MqFplnF81BV6nNttGbQ:-MqFplnF81BV6nNttGbR:b-7egkq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/31d233c11dd9b74b15621f64b972da86af22d64c/pkg/sql/schemachanger/testdata/drop#L260)):*
> ```
> ----
> ```
what's up with the new line here?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73356)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_schema.go, line 44 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73356#-MqFjs_0Ds180K2AOaS8:-MqGIHD97dCy9rwTFTIG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/31d233c11dd9b74b15621f64b972da86af22d64c/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_schema.go#L44)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

stray comment
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scdeps/sctestdeps/test_deps.go, line 657 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73356#-MqFpdZqBfVSJskmkJOO:-MqGIHoa1xTGpplP39KL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/31d233c11dd9b74b15621f64b972da86af22d64c/pkg/sql/schemachanger/scdeps/sctestdeps/test_deps.go#L657)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't think the `\n` should be here
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scexec/executor.go, line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73356#-MqFkPOHEBf5jgyP25-u:-MqGIIfSDmSIDf8p8VMh:b-kdkn2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/31d233c11dd9b74b15621f64b972da86af22d64c/pkg/sql/schemachanger/scexec/executor.go#L48)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

one of us is going to hit rebase trouble with this. It's interesting. We'll need to order the operations differently. I can take that sooner rather than later. 
</blockquote></details>

I'll sort it out on the rebase. Should be trivial on my side to deal with I think.
___
*[pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go, line 331 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73356#-MqFl_dqDNMUdw-w4TAF:-MqGINzkCE-d2CfKlVtb:b-mq82j7) ([raw file](https://github.com/cockroachdb/cockroach/blob/31d233c11dd9b74b15621f64b972da86af22d64c/pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go#L331)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

today when we drop a database, my understanding is that we create a single GC job. What do we do in the new schema changer? 
</blockquote></details>

We generate a single job across all the tables in a database in the current implementation. Let me clarify that the interface should accumulate all the state for that operation.

**Review by fqazi — COMMENTED** [review]
> Do we create gc jobs for indexes?
Yes we create them for indexes

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73356#-:-MqGKVW8CPG5r7yo_ZAv:b11ltzy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

**Review by fqazi — COMMENTED** [review]
Yes we make them for drop indexes

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73356#-:-MqGKbexEpHzpLevPlGN:b-5fiac4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73356#-:-MqGTLWK0JwR22znd6d3:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)

**Pull request merged**
