### PR TITLE
colexec: refactor allocator to reduce the number of function calls

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: refactor allocator to reduce the number of function calls**

Previously, allocator had methods to Append or Copy a single
coldata.Vec. Those methods created an anonymous function on every call.
However, calls to these methods often occur in a loop over many columns,
so they become relatively expensive. Now this code has been refactored
to Append or Copy all columns at once. Allocator.Append and
Allocator.Copy have been removed and Allocator.PerformOperation has been
exposed as a single method to use.

Release note: None

**colexec: minor refactor of memory accounting**

We extract out PerformOperation call outside of the loop in Case operator
(which should give minor performance improvement in case of multiple When
arms) and do a tweak to rowstovec template. Also, a bug with memory
accounting in any_not_null template is fixed.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
As a sanity check, I ran benchmarks on merge joiner, and here is the output:
```
name                                       old speed      new speed      delta
MergeJoiner/rows=1024-16                   1.98GB/s ± 0%  1.89GB/s ± 0%   ~     (p=0.333 n=2+2)
MergeJoiner/rows=4096-16                   2.21GB/s ± 0%  2.08GB/s ± 0%   ~     (p=0.333 n=2+2)
MergeJoiner/rows=16384-16                  2.32GB/s ± 0%  2.14GB/s ± 0%   ~     (p=0.333 n=2+2)
MergeJoiner/rows=1048576-16                2.37GB/s ± 0%  2.20GB/s ± 0%   ~     (p=0.333 n=2+2)
MergeJoiner/oneSideRepeat-rows=1024-16     2.01GB/s ± 0%  1.89GB/s ± 0%   ~     (p=0.333 n=2+2)
MergeJoiner/oneSideRepeat-rows=4096-16     2.20GB/s ± 0%  2.08GB/s ± 0%   ~     (p=0.333 n=2+2)
MergeJoiner/oneSideRepeat-rows=16384-16    2.31GB/s ± 0%  2.15GB/s ± 0%   ~     (p=0.333 n=2+2)
MergeJoiner/oneSideRepeat-rows=1048576-16  2.35GB/s ± 1%  2.20GB/s ± 0%   ~     (p=0.333 n=2+2)
MergeJoiner/bothSidesRepeat-rows=1024-16   1.95GB/s ± 0%  1.84GB/s ± 0%   ~     (p=0.333 n=2+2)
MergeJoiner/bothSidesRepeat-rows=4096-16    388MB/s ± 2%   763MB/s ± 1%   ~     (p=0.333 n=2+2)
MergeJoiner/bothSidesRepeat-rows=16384-16   364MB/s ± 3%   623MB/s ± 0%   ~     (p=0.333 n=2+2)
MergeJoiner/bothSidesRepeat-rows=32768-16   321MB/s ± 0%   499MB/s ± 0%   ~     (p=0.333 n=2+2)
```
Note that the change to merge joiner's code is in `buildRightGroups` and it affects only `bothSidesRepeat` cases. So, in some cases, this PR shows good improvement.

**Review by asubiotto — COMMENTED** [review]
> Reviewed 22 of 22 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43822)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/any_not_null_agg_tmpl.go, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43822#-LyVN8zX68zxlfPr9oFP:-LyVN8zX68zxlfPr9oFQ:b-xnwgje) ([raw file](https://github.com/cockroachdb/cockroach/blob/0efde95873f0fc4fa44ee967016dd4ff388ea19a/pkg/sql/colexec/any_not_null_agg_tmpl.go#L124)):*
> ```Go
> 	col, nulls := vec._TemplateType(), vec.Nulls()
> 
> 	a.allocator.PerformOperation(
> ```

What operation was this accounting for?

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43822)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/any_not_null_agg_tmpl.go, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43822#-LyVN8zX68zxlfPr9oFP:-LyVPSsh3en2Nj56uJMc:b7o3pls) ([raw file](https://github.com/cockroachdb/cockroach/blob/0efde95873f0fc4fa44ee967016dd4ff388ea19a/pkg/sql/colexec/any_not_null_agg_tmpl.go#L124)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What operation was this accounting for?
</blockquote></details>

I'm still slightly confused as to how this was double accounting. Would you mind explaining it?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43822)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/any_not_null_agg_tmpl.go, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43822#-LyVN8zX68zxlfPr9oFP:-LyVQGw91W6sTZc-zXRg:blqoohu) ([raw file](https://github.com/cockroachdb/cockroach/blob/0efde95873f0fc4fa44ee967016dd4ff388ea19a/pkg/sql/colexec/any_not_null_agg_tmpl.go#L124)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm still slightly confused as to how this was double accounting. Would you mind explaining it?
</blockquote></details>

Within `_FIND_ANY_NOT_NULL`, there is this `// {{ .Global.Set "a.vec" "a.curIdx" "v" }}` which sets a single value, so we wanted to account for that.

I think "double accounting" here is somewhat misleading phrase. Usually it means that we include something twice (i.e. we use 10 bytes, "double accounting" would say that we used 20 bytes). This was not the case here; instead, we perform the accounting part twice (i.e. we do it within the any not null aggregate, on every `Set`, so the allocator has the correct memory account, and then we also do the accounting in the `orderedAggregator`, on the whole batch that is shared among all of the aggregate functions). Essentially, we end up doing the same work twice (and the first time we do it, we do it very slowly, accounting on every `Set`). This change removes the "first" slow accounting entirely because the second is sufficient.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43822)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/any_not_null_agg_tmpl.go, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43822#-LyVN8zX68zxlfPr9oFP:-LyVZ7_xBW_IfsWsDiQd:b8v4tk4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0efde95873f0fc4fa44ee967016dd4ff388ea19a/pkg/sql/colexec/any_not_null_agg_tmpl.go#L124)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Within `_FIND_ANY_NOT_NULL`, there is this `// {{ .Global.Set "a.vec" "a.curIdx" "v" }}` which sets a single value, so we wanted to account for that.

I think "double accounting" here is somewhat misleading phrase. Usually it means that we include something twice (i.e. we use 10 bytes, "double accounting" would say that we used 20 bytes). This was not the case here; instead, we perform the accounting part twice (i.e. we do it within the any not null aggregate, on every `Set`, so the allocator has the correct memory account, and then we also do the accounting in the `orderedAggregator`, on the whole batch that is shared among all of the aggregate functions). Essentially, we end up doing the same work twice (and the first time we do it, we do it very slowly, accounting on every `Set`). This change removes the "first" slow accounting entirely because the second is sufficient.
</blockquote></details>

My understanding of this is that the accounting only happens once per batch in this case, not once per `Set`, right? The memory accounted for here that should be accounted for is the scratch output vector, but I fail to see where that is accounted for in the aggregator. Also, isn't this accounting wrong? We're passing in `vec` which is the input, I think we should be passing in `a.vec` to `PerformOperation`, right?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43822)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/any_not_null_agg_tmpl.go, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43822#-LyVN8zX68zxlfPr9oFP:-LyVay2dEdEhO3ZsNzJo:b-4eant6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0efde95873f0fc4fa44ee967016dd4ff388ea19a/pkg/sql/colexec/any_not_null_agg_tmpl.go#L124)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

My understanding of this is that the accounting only happens once per batch in this case, not once per `Set`, right? The memory accounted for here that should be accounted for is the scratch output vector, but I fail to see where that is accounted for in the aggregator. Also, isn't this accounting wrong? We're passing in `vec` which is the input, I think we should be passing in `a.vec` to `PerformOperation`, right?
</blockquote></details>

You're right on all three accounts:
- accounting happens once per the whole vector, not on every `Set`
- this memory is not accounted for in the `aggregator` (not sure why I thought so, probably because of several `PerformOperation` calls in there)
- there was a bug in any_not_null

All fixed.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43822#-:-LyVh7g8BB2guGxzB8DX:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
