### PR TITLE
storage/engine: rename Iterator.{Seek,SeekReverse} to {SeekGE,SeekLT}

### PR DESCRIPTION
**Pull request by nvb**
This addresses a comment from #42210.

The commit also adjusts the reverse seek (now SeekLT) to be exclusive instead of
inclusive. This matches the API exposed by Pebble and eliminates the need for
the bug fix in 79b4c775862f184d2b6dc6f5ba89cdff04d0c052.

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm: thanks for doing this.

The change mostly looks rote. Besides the `spanset.Iterator` note, was there anything worth special attention here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42390#-:-LtSSU7TEIL8fcKNI-2a:b5wb55)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @petermattis)

**Comment by nvanbenschoten** [comment]
> Besides the spanset.Iterator note, was there anything worth special attention here.

The only other parts to pay attention to are:
1. the implementation of `rocksDBIterator.SeekLT`, which can no longer use `r.reseek`.
2. `StateLoader.LoadLastIndex`, which should still be fine because we're never going to get to Raft log index `MaxUint64` (and if we did, we'd have bigger problems) so we can consider it exclusive instead of inclusive.

bors r=petermattis

**Comment by petermattis** [comment]
> StateLoader.LoadLastIndex, which should still be fine because we're never going to get to Raft log index MaxUint64 (and if we did, we'd have bigger problems) so we can consider it exclusive instead of inclusive.

This is the sole use of `SeekLT` in the code base currently. Your `pebbleMVCCScanner` refactor will add another one. I'm wondering if we should try to remove `SeekLT` from the `Iterator` interface.

**Comment by nvanbenschoten** [comment]
> This is the sole use of SeekLT in the code base currently. Your pebbleMVCCScanner refactor will add another one. I'm wondering if we should try to remove SeekLT from the Iterator interface.

I don't have strong feelings about this. It's nice to have access to `SeekLT` and it doesn't weigh down the interface too much, especially because we already have `SimpleIterator`. I'll defer to your judgment.

**Pull request merged**
