### PR TITLE
server: deflake TestUpgradeHappensAfterMigrations

### LINKED ISSUE #100276: server: TestUpgradeHappensAfterMigrations failed
server.TestUpgradeHappensAfterMigrations [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9356621?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9356621?buildTab=artifacts#/) on master @ [0b9f1a613e0caad135d9eee7964a0c26f37c563e](https://github.com/cockroachdb/cockroach/commits/0b9f1a613e0caad135d9eee7964a0c26f37c563e):

```
=== RUN   TestUpgradeHappensAfterMigrations
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/5b2c9b3a394428c7572d34050aad8975/logTestUpgradeHappensAfterMigrations3100504256
    test_log_scope.go:79: use -show-logs to present logs inline
    sql_runner.go:103: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/testutils/sqlutils/sql_runner.go:116
        	            				github.com/cockroachdb/cockroach/pkg/testutils/sqlutils/sql_runner.go:311
        	            				github.com/cockroachdb/cockroach/pkg/server/migration_test.go:279
        	Error:      	Received unexpected error:
        	            	query '
        	            	(1) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/testutils/sqlutils.(*SQLRunner).CheckQueryResultsRetry.func1
        	            	  | 	github.com/cockroachdb/cockroach/pkg/testutils/sqlutils/sql_runner.go:314
        	            	  | github.com/cockroachdb/cockroach/pkg/testutils.SucceedsWithinError.func1
        	            	  | 	github.com/cockroachdb/cockroach/pkg/testutils/soon.go:71
        	            	  | github.com/cockroachdb/cockroach/pkg/util/retry.ForDuration
        	            	  | 	github.com/cockroachdb/cockroach/pkg/util/retry/retry.go:213
        	            	  | github.com/cockroachdb/cockroach/pkg/testutils.SucceedsWithinError
        	            	  | 	github.com/cockroachdb/cockroach/pkg/testutils/soon.go:77
        	            	  | github.com/cockroachdb/cockroach/pkg/testutils/sqlutils.(*SQLRunner).succeedsWithin
        	            	  | 	github.com/cockroachdb/cockroach/pkg/testutils/sqlutils/sql_runner.go:116
        	            	  | github.com/cockroachdb/cockroach/pkg/testutils/sqlutils.(*SQLRunner).CheckQueryResultsRetry
        	            	  | 	github.com/cockroachdb/cockroach/pkg/testutils/sqlutils/sql_runner.go:311
        	            	  | github.com/cockroachdb/cockroach/pkg/server.TestUpgradeHappensAfterMigrations
        	            	  | 	github.com/cockroachdb/cockroach/pkg/server/migration_test.go:279
        	            	  | testing.tRunner
        	            	  | 	GOROOT/src/testing/testing.go:1446
        	            	  | runtime.goexit
        	            	  | 	GOROOT/src/runtime/asm_amd64.s:1594
        	            	Wraps: (2) query '
        	            	  | SELECT version = crdb_internal.node_executable_version()
        	            	  |   FROM [SHOW CLUSTER SETTING version]': expected:
        	            	  | true
        	            	  | got:
        	            	  | false
        	            	Error types: (1) *withstack.withStack (2) *errutil.leafError
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/5b2c9b3a394428c7572d34050aad8975/logTestUpgradeHappensAfterMigrations3100504256
I230331 09:55:06.221677 82920440 sql/backfill.go:264  [T1,n1,job=SCHEMA CHANGE id=852577830984318977,scExec,id=42,mutation=5] 1  running backfill for "statement_statistics", v=21
I230331 09:55:06.221807 82920440 sql/backfill.go:2410  [T1,n1,job=SCHEMA CHANGE id=852577830984318977,scExec,id=42,mutation=5] 2  clearing and backfilling columns
--- FAIL: TestUpgradeHappensAfterMigrations (47.88s)
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestUpgradeHappensAfterMigrations.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-26338

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/100276
Release note: None

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100490)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by rafiss** [comment]
tftr!

bors r+

**Comment by rafiss** [comment]
this was included in https://github.com/cockroachdb/cockroach/pull/100483

bors r-

**Comment by rafiss** [comment]
blathers backport 23.1

**Pull request closed without merging**
