### PR TITLE
roachtest: fix network/authentication test to learn port

### PR DESCRIPTION
**Pull request by DarrylWong**
Previously the tests hardcoded port 26257 to drop traffic. This did not lead to an error but lead to the test effectively not doing anything.

This change switches the test to learn the port through pgport env variable.

Release note: None
Epic: None

### CODE REVIEW

**Comment by DarrylWong** [comment]
I ran the network/authentication tests and confirmed it passes, but it was passing before so I don't think that proves anything. I don't see anything that different before and after the change either.

@rafiss would you know how can I check that packets are actually getting dropped?

**Comment by srosenberg** [comment]
> @rafiss would you know how can I check that packets are actually getting dropped?

```
iptables -vL
```

shows counters for every configured rule.

**Comment by rafiss** [comment]
Using `iptables -vL` sounds like a good approach. Another way could be to look at a table like `crdb_internal.kv_node_liveness`. The KV team would probably know the best way to verify that one node is inaccessible from the others.

**Comment by DarrylWong** [comment]
I'll go ahead and try `iptables -vL` out of my own curiosity but closing in favor of: #117884

**Comment by rafiss** [comment]
I think we should still make that change to make the test verify that the node became unreachable, otherwise the test could break again without us knowing.

**Comment by DarrylWong** [comment]
iptables -vL worked great, thanks Stan. Put out a new PR w/ the check here: https://github.com/cockroachdb/cockroach/pull/118112

**Pull request closed without merging**
