### PR TITLE
raft: stop heartbeats

### LINKED ISSUE #131749: raft: stop heartbeats
Leader leases doesn't require raft heartbeats because the liveness is recorded by store-to-store heartbeats.

We need to stop Raft heartbeats (once it's safe to do so) when using leader leases

Jira issue: CRDB-42682

### PR DESCRIPTION
**Pull request by iskettaneh**
Since all known heartbeat dependencies has been removed if store liveness is enabled, it should be now possible to stop Raft heartbeats.                                                                                                                                                                                                                                                                          

Fixes: #131749
                                                                                                                                                                                                                                                           
Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, 3 of 3 files at r3, 16 of 16 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131976)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @iskettaneh)

___
*[`-- commits` line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131976#-O8TQgsD7inSzc-sKC9x):*
"support follower support"
___
*[`pkg/raft/testdata/async_storage_writes_append_aba_race.txt` line 411 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/131976#-O8TS3UJ67CkPXmwtXPc:-O8TS3UK3xv073GOPQnt:b-vb6i29) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aec0079b6a099ca9c4e4780df1a262986cf62db/pkg/raft/testdata/async_storage_writes_append_aba_race.txt#L411)):*
> ```help
> Ready MustSync=false:
> Messages:
> 4->1 MsgHeartbeat Term:3 Log:0/0
> ```

Given how different some of these `TestInteraction` tests now look, what do you think about adding mixed-version variants of the ones that meaningfully differ?
___
*[`pkg/raft/testdata/msg_app_commit_index.txt` line 150 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/131976#-O8TUT4r4w_QlaHYN7uT:-O8TUT4sDbJKztLUWQ5H:b-ppcag1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aec0079b6a099ca9c4e4780df1a262986cf62db/pkg/raft/testdata/msg_app_commit_index.txt#L150)):*
> ```help
>   1/13 EntryNormal "data2"
>   Messages:
>   3->1 MsgHeartbeatResp Term:1 Log:0/0
> ```

All this red is quite satisfying to review.
___
*[`pkg/raft/testdata/snapshot_succeed_via_app_resp.txt` line 89 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131976#-O8TRbV5E3PumEH_g993:-O8TRbV5E3PumEH_g994:bcgz4aq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aec0079b6a099ca9c4e4780df1a262986cf62db/pkg/raft/testdata/snapshot_succeed_via_app_resp.txt#L89)):*
> ```help
> 
> # The leader in turn will realize that n3 needs a snapshot, which it initiates.
> stabilize 1
> ```

Was `stabilize` no longer equivalent to`deliver-msgs` plus `process-ready`?

EDIT: maybe this is something we can put back once the TODO from the next commit is addressed.

**Review by iskettaneh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131976)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/raft/testdata/async_storage_writes_append_aba_race.txt` line 411 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/131976#-O8TS3UJ67CkPXmwtXPc:-O8b7fCE3j4LRlWuaSRe:b-yplf2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aec0079b6a099ca9c4e4780df1a262986cf62db/pkg/raft/testdata/async_storage_writes_append_aba_race.txt#L411)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Given how different some of these `TestInteraction` tests now look, what do you think about adding mixed-version variants of the ones that meaningfully differ?
</blockquote></details>

Yeah I was thinking the same. We already have msg_app_commit_index_leader_old_version, I am thinking of adding old versions for:

1) lagging_commit
2) heartbeat_timeout_recovers_from_probing
3) snapshot_succeed_via_app_resp

What do you think?
___
*[`pkg/raft/testdata/msg_app_commit_index.txt` line 150 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/131976#-O8TUT4r4w_QlaHYN7uT:-O8b7j-Z2cUxita2Sxid:bb77uf3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aec0079b6a099ca9c4e4780df1a262986cf62db/pkg/raft/testdata/msg_app_commit_index.txt#L150)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

All this red is quite satisfying to review.
</blockquote></details>

Yes!
___
*[`pkg/raft/testdata/snapshot_succeed_via_app_resp.txt` line 89 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131976#-O8TRbV5E3PumEH_g993:-O8b8KNjBWWXnEu0VrOp:b-inpl8g) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aec0079b6a099ca9c4e4780df1a262986cf62db/pkg/raft/testdata/snapshot_succeed_via_app_resp.txt#L89)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Was `stabilize` no longer equivalent to`deliver-msgs` plus `process-ready`?

EDIT: maybe this is something we can put back once the TODO from the next commit is addressed.
</blockquote></details>

Yes, once we address the TODO, the code should return to how it was

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 15 of 16 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131976#-:-O8c8Yzo4IiD5zNkQi3_:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @iskettaneh)

___
*[`pkg/raft/testdata/async_storage_writes_append_aba_race.txt` line 411 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/131976#-O8TS3UJ67CkPXmwtXPc:-O8c9iHp2iOY8tcuHwnJ:b6ea1jh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aec0079b6a099ca9c4e4780df1a262986cf62db/pkg/raft/testdata/async_storage_writes_append_aba_race.txt#L411)):*
<details><summary><i>Previously, iskettaneh wrote…</i></summary><blockquote>

Yeah I was thinking the same. We already have msg_app_commit_index_leader_old_version, I am thinking of adding old versions for:

1) lagging_commit
2) heartbeat_timeout_recovers_from_probing
3) snapshot_succeed_via_app_resp

What do you think?
</blockquote></details>

How about `checkquorum`, `forget_leader`, and `forget_leader_prevote_checkquorum`?

**Review by iskettaneh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131976)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/raft/testdata/async_storage_writes_append_aba_race.txt` line 411 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/131976#-O8TS3UJ67CkPXmwtXPc:-O8cXH9KBQd-pe7nkxoE:b-ebd6d5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aec0079b6a099ca9c4e4780df1a262986cf62db/pkg/raft/testdata/async_storage_writes_append_aba_race.txt#L411)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

How about `checkquorum`, `forget_leader`, and `forget_leader_prevote_checkquorum`?
</blockquote></details>

I added them as well. I also created a subdirectory for these types of tests to avoid the clutter

**Review by nvb — APPROVED** [review]
:lgtm: as long as you have confirmed that the tests in the subdirectory are getting run.

> Reviewed 1 of 24 files at r9, 16 of 21 files at r11, 13 of 13 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131976#-:-O8cYnRJ79Dex8pqiFA-:bh5zx64)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Review by iskettaneh — COMMENTED** [review]
Yes, they all get run

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131976#-:-O8cZuOh-VP0L6WGTBwk:b9n4928)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by iskettaneh** [comment]
TFTR!

bors r+

**Pull request merged**
