### PR TITLE
storage: queue replicas for raft log truncation after write ops

### LINKED ISSUE #6012: storage: `raft_log_queue` should be more aggressive
Currently, `raft_log_queue` will never truncate log entries that are older than the replica that is the farthest behind. This leads to pathological cases in which a replica that is having trouble can result in unbounded log growth, as in these logs from #5970:

```
node4.log:W160406 14:17:15.637214 storage/raft_log_queue.go:116  storage/raft_log_queue.go:101: raft log's oldest index (0) is less than the first index (243127) for range 17
node4.log:W160406 14:17:35.639891 storage/raft_log_queue.go:116  storage/raft_log_queue.go:101: raft log's oldest index (0) is less than the first index (56364) for range 76
node4.log:W160406 14:23:50.864039 storage/raft_log_queue.go:116  storage/raft_log_queue.go:101: raft log's oldest index (0) is less than the first index (108869) for range 42
node4.log:W160406 14:23:55.867391 storage/raft_log_queue.go:116  storage/raft_log_queue.go:101: raft log's oldest index (0) is less than the first index (64298) for range 112
```

We should be willing to truncate applied log entries even if a lagging replica still needs them to prevent the log from getting too big. The raft protocol handles this gracefully and will fall back to sending a snapshot to help the lagging replica recover. We should still prefer to keep log entries around until all replicas are caught up because that's the most efficient path, but truncating the log is better than letting it grow without bound.

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #6012.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7125)

### CODE REVIEW

**Comment by petermattis** [comment]
@bdarnell I wanted to get feedback on this approach before I push it any further. In manual testing it seems to work as expected, keeping the raft log proactively truncated. Before merging I would want to add some specific testing of this functionality.

**Comment by BramGruneir** [comment]
My only concern would be that under heavy load, we might be checking the raft log state too often.  Specifically, calling `getTruncatableIndexes()`, which locks both the store and then the replica.  Is there perhaps a way to only add after a specific number of writes, perhaps after `RaftLogQueueStaleThreshold` writes, instead of after each one?

**Comment by petermattis** [comment]
@BramGrunier `getTruncatableIndexes` only locks the store due to issues with `TestGetTruncatableIndexes`. Once you fix #7056 we'll only be locking the replica. And there is plenty of replica locking/unlocking already going on. I doubt this additional locking will be significant.

That said, only checking for whether the replica should be queued after every Nth write would be very easy to add.

**Comment by petermattis** [comment]
@BramGrunier I tweaked `maybeAddToRaftLogQueue` to only try adding the replica on every 20th write operation. Manual testing indicates this works well. I still need to add unit tests for this change.

**Comment by tamird** [comment]
Reviewed 1 of 6 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[storage/client_metrics_test.go, line 152 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-KJr83Fz-sbzI4Xwga45:-KJr83Fz-sbzI4Xwga46:1055100275) ([raw file](https://github.com/cockroachdb/cockroach/blob/986b2c5ca1b552bca4d55db23f1e1de0036240da/storage/client_metrics_test.go#L152)):*
> ```Go
> 		t.Fatal(err)
> 	}
> 	mtc.stores[0].DisableRaftLogQueue(true)
> ```

does this want to be a loop? does it need a helpful comment?

---

*[storage/queue.go, line 262 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-KJr8CrL9_NwCd5JfG4Z:-KJr8CrL9_NwCd5JfG4_:233292318) ([raw file](https://github.com/cockroachdb/cockroach/blob/986b2c5ca1b552bca4d55db23f1e1de0036240da/storage/queue.go#L262)):*
> ```Go
> func (bq *baseQueue) MaybeAdd(repl *Replica, now roachpb.Timestamp) {
> 	if bq.gossip == nil {
> 		// The queue is disabled due to being part of the bootstrap store.
> ```

can this move up the stack to avoid creating the queue?

---

*[storage/replica_test.go, line 866 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-KJr8cCd97_7TgByYQ42:-KJr8cCd97_7TgByYQ43:20548809) ([raw file](https://github.com/cockroachdb/cockroach/blob/986b2c5ca1b552bca4d55db23f1e1de0036240da/storage/replica_test.go#L866)):*
> ```Go
> 	defer tc.Stop()
> 	tc.clock.SetMaxOffset(maxClockOffset)
> 	tc.store.DisableRaftLogQueue(true)
> ```

does this need a comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125)*

**Comment by petermattis** [comment]
Review status: 3 of 6 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/client_metrics_test.go, line 152 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-KJr83Fz-sbzI4Xwga45:-KJrppmBh8dq7ycIwOkd:-202221693) ([raw file](https://github.com/cockroachdb/cockroach/blob/986b2c5ca1b552bca4d55db23f1e1de0036240da/storage/client_metrics_test.go#L152)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> does this want to be a loop? does it need a helpful comment?
</details>
Switched to a loop and added a comment. Short summary is raft log truncation confuses this test.

---

*[storage/queue.go, line 262 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-KJr8CrL9_NwCd5JfG4Z:-KJrq-WKM8mVbeFv16M_:54682963) ([raw file](https://github.com/cockroachdb/cockroach/blob/986b2c5ca1b552bca4d55db23f1e1de0036240da/storage/queue.go#L262)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can this move up the stack to avoid creating the queue?
</details>
I actually investigated that but ran into a number of headaches. I think doing so is the right long term approach. I'll file an issue as it is separate from this PR.

---

*[storage/replica_test.go, line 866 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-KJr8cCd97_7TgByYQ42:-KJrqEdeI_UU3Q0CeWVF:1030362923) ([raw file](https://github.com/cockroachdb/cockroach/blob/986b2c5ca1b552bca4d55db23f1e1de0036240da/storage/replica_test.go#L866)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> does this need a comment?
</details>
Yes. Similar to my other response, raft log truncation confuses this test. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125)*

**Comment by petermattis** [comment]
Review status: 3 of 6 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 2354 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-KJulg1GWX4yi35LTo1H:-KJulg1GWX4yi35LTo1I:1271648603) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cba101b14f34420455b59ab22c98e6703dde858/storage/replica.go#L2354)):*
> ```Go
> 	if appliedIndex%raftLogCheckFrequency == 0 {
> 		r.store.raftLogQueue.MaybeAdd(r, r.store.Clock().Now())
> 	}
> ```

I'm not seeing an easy way to test this. If I disable the `raftLogQueue` then this code doesn't have any effect. If I enable the `raftLogQueue` then there is a race between the scanner and this code and I'm not sure which one won. I could jump through hoops and stop the replica scanner loop. Thoughts?

Curious how we're testing the `maybeAddToSplitQueue` code. I couldn't find the test which exercises that code path, but it is very possible I'm just missing it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/queue.go, line 262 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-KJr8CrL9_NwCd5JfG4Z:-KJunCRLKt-sjM3KGDmj:939747587) ([raw file](https://github.com/cockroachdb/cockroach/blob/986b2c5ca1b552bca4d55db23f1e1de0036240da/storage/queue.go#L262)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I actually investigated that but ran into a number of headaches. I think doing so is the right long term approach. I'll file an issue as it is separate from this PR.
</details>
Cool. I think a TODO here with the issue number would be helpful.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/queue.go, line 262 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-KJr8CrL9_NwCd5JfG4Z:-KJusdFfANnW4GM4gwGK:-858450432) ([raw file](https://github.com/cockroachdb/cockroach/blob/986b2c5ca1b552bca4d55db23f1e1de0036240da/storage/queue.go#L262)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Cool. I think a TODO here with the issue number would be helpful.
</details>
I just didn't push through the headaches enough. Looks like it was actually quite straightforward in the end: https://github.com/cockroachdb/cockroach/pull/7157

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125)*

**Comment by bdarnell** [comment]
LGTM modulo tests.

<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> @BramGrunier I tweaked `maybeAddToRaftLogQueue` to only try adding the replica on every 20th write operation. Manual testing indicates this works well. I still need to add unit tests for this change.
</details>


---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 2354 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-KJulg1GWX4yi35LTo1H:-KK0T-km4i91-r7fN7qP:1869856842) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cba101b14f34420455b59ab22c98e6703dde858/storage/replica.go#L2354)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I'm not seeing an easy way to test this. If I disable the `raftLogQueue` then this code doesn't have any effect. If I enable the `raftLogQueue` then there is a race between the scanner and this code and I'm not sure which one won. I could jump through hoops and stop the replica scanner loop. Thoughts?
> 
> Curious how we're testing the `maybeAddToSplitQueue` code. I couldn't find the test which exercises that code path, but it is very possible I'm just missing it.
</details>
We probably aren't testing `maybeAddToSplitQueue`. I think that bit of code predates our infrastructure for effectively testing splits. 

Most tests set the ScanInterval to 10 minutes, which is enough to make this race unlikely. You could set the interval even higher if you want to make sure (or add a Disable method to the scanner and not just the individual queues).

---

*[storage/replica.go, line 2408 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-KK0UWqWJEjtBRmyH7y_:-KK0UWqXdgSCAZa6Redg:-993924623) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c79418953a245b657e037e26d69d8bafec07e84/storage/replica.go#L2408)):*
> ```Go
> // truncation. If yes, the range is added to the raft log queue.
> func (r *Replica) maybeAddToRaftLogQueue(appliedIndex uint64) {
> 	const raftLogCheckFrequency = RaftLogQueueStaleThreshold / 5
> ```

`/ 4` (or `>> 2`)  may be a little faster. 

If RaftLogQueueStaleThreshold is too low, this rounds down to zero. We should make a note that if this becomes configurable, we need to either enforce that it falls in an appropriate range or that we round up to 1 here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-:-KK0WyWgw2ZziNakZY-D:-1307537680)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125)*

**Comment by petermattis** [comment]
I added the ability to disable a `replicaScanner` and a new test which verifies that proactive raft log truncation is being performed. PTAL.

**Comment by petermattis** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/replica.go, line 2354 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-KJulg1GWX4yi35LTo1H:-KKDy9otArxz0xoHmO8e:-1063252485) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cba101b14f34420455b59ab22c98e6703dde858/storage/replica.go#L2354)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> We probably aren't testing `maybeAddToSplitQueue`. I think that bit of code predates our infrastructure for effectively testing splits. 
> 
> Most tests set the ScanInterval to 10 minutes, which is enough to make this race unlikely. You could set the interval even higher if you want to make sure (or add a Disable method to the scanner and not just the individual queues).
</details>
I've added `replicaScanner.SetDisabled` so that processing of replicas can be disabled in tests. 

---

*[storage/replica.go, line 2408 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-KK0UWqWJEjtBRmyH7y_:-KKDxyr_oE4OL5L5jdQ0:294237868) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c79418953a245b657e037e26d69d8bafec07e84/storage/replica.go#L2408)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> `/ 4` (or `>> 2`)  may be a little faster. 
> 
> If RaftLogQueueStaleThreshold is too low, this rounds down to zero. We should make a note that if this becomes configurable, we need to either enforce that it falls in an appropriate range or that we round up to 1 here. 
> 
</details>
Can't imagine the speed matters here, but I've changed this to `/ 4`. I've added a comment about `RaftLogQueueStaleThreshold` becoming too low. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[storage/raft_log_queue_test.go, line 180 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-KKESjupY3wg-l8q1uxU:-KKESjupY3wg-l8q1uxV:287116015) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bf860049a561882ad30b1900e0cc545954b955/storage/raft_log_queue_test.go#L180)):*
> ```Go
> 	r, err := store.GetReplica(1)
> 	if err != nil {
> 		t.Error(err)
> ```

should be Fatal

---

*[storage/raft_log_queue_test.go, line 187 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-KKESkpWDHcF7exITGiN:-KKESkpWDHcF7exITGiO:287116015) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bf860049a561882ad30b1900e0cc545954b955/storage/raft_log_queue_test.go#L187)):*
> ```Go
> 	r.mu.Unlock()
> 	if err != nil {
> 		t.Error(err)
> ```

should be Fatal

---

*[storage/replica.go, line 2597 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-KKESSDqjB_-YZ82nv_3:-KKESSDrToiccS7bcdco:1692626538) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bf860049a561882ad30b1900e0cc545954b955/storage/replica.go#L2597)):*
> ```Go
> // truncation. If yes, the range is added to the raft log queue.
> func (r *Replica) maybeAddToRaftLogQueue(appliedIndex uint64) {
> 	// If RaftLogQueueStaleThreshold is too small, raftLogCheckFrequency may be 0
> ```

any reason not to `const raftLogCheckFrequency = RaftLogQueueStaleThreshold / 4 + 1`?

---

*[storage/scanner.go, line 121 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-KKESdzyWNG4sk2xhzuN:-KKESdzyWNG4sk2xhzuO:1921886081) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bf860049a561882ad30b1900e0cc545954b955/storage/scanner.go#L121)):*
> ```Go
> // SetDisabled turns replica scanning off or on as directed. Note that while
> // disabled, removals are still processed
> func (rs *replicaScanner) SetDisabled(disabled bool) {
> ```

this function should be in the file `helpers_test.go`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-:-KKETOb3e1WLX5PrffZf:1417088721)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[storage/raft_log_queue_test.go, line 180 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-KKESjupY3wg-l8q1uxU:-KKEfm5avhoJphFu5GaZ:-502697825) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bf860049a561882ad30b1900e0cc545954b955/storage/raft_log_queue_test.go#L180)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> should be Fatal
</details>
Copy&paste from above. I've fixed both tests.

---

*[storage/raft_log_queue_test.go, line 187 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-KKESkpWDHcF7exITGiN:-KKEfoLI6LW3Dv04AoG1:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bf860049a561882ad30b1900e0cc545954b955/storage/raft_log_queue_test.go#L187)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> should be Fatal
</details>
Done.

---

*[storage/replica.go, line 2597 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-KKESSDqjB_-YZ82nv_3:-KKEg3AWvulvFhCfKQa2:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bf860049a561882ad30b1900e0cc545954b955/storage/replica.go#L2597)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> any reason not to `const raftLogCheckFrequency = RaftLogQueueStaleThreshold / 4 + 1`?
</details>
Done.

---

*[storage/scanner.go, line 121 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-KKESdzyWNG4sk2xhzuN:-KKEfv6EncjcrIozF_QD:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bf860049a561882ad30b1900e0cc545954b955/storage/scanner.go#L121)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this function should be in the file `helpers_test.go`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125)*

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r8.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[storage/helpers_test.go, line 122 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-KKEh6iNZhNCc3erhdp3:-KKEh6iNZhNCc3erhdp4:746685952) ([raw file](https://github.com/cockroachdb/cockroach/blob/d390791390da59c9f3caed44ba4976d2ac6b4533/storage/helpers_test.go#L122)):*
> ```Go
> 
> // SetDisabled turns replica scanning off or on as directed. Note that while
> // disabled, removals are still processed
> ```

missing period

---

*[storage/raft_log_queue_test.go, line 79 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-KKEhD-EUiIr6GQpT54H:-KKEhD-EUiIr6GQpT54I:-518364009) ([raw file](https://github.com/cockroachdb/cockroach/blob/d390791390da59c9f3caed44ba4976d2ac6b4533/storage/raft_log_queue_test.go#L79)):*
> ```Go
> 	store, _, stopper := createTestStore(t)
> 	defer stopper.Stop()
> 	if _, err := store.GetReplica(0); err == nil {
> ```

this is pretty weird - why is it even here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/raft_log_queue_test.go, line 201 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-KKFEHNNMBakB2hsFE1Z:-KKFEHNNMBakB2hsFE1_:-1915364096) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4b7a466c57999f769d39992927f8d707e62f4ae/storage/raft_log_queue_test.go#L201)):*
> ```Go
> 
> 	// Wait for tasks to finish, in case the processLoop grabbed the event
> 	// before ForceRaftLogScanAndProcess but is still working on it.
> ```

Comment looks stale (or else it's not clear where ForceRaftLogScanAndProcess is getting called)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-:-KKFEMPZdRtTzU1QSfAz:1417088721)*

**Comment by petermattis** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/raft_log_queue_test.go, line 201 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125#-KKFEHNNMBakB2hsFE1Z:-KKFEtbvE23IXeZtDd4w:148351356) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4b7a466c57999f769d39992927f8d707e62f4ae/storage/raft_log_queue_test.go#L201)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Comment looks stale (or else it's not clear where ForceRaftLogScanAndProcess is getting called)
</details>
Doh, already merged. Sending a follow-on PR to fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7125)*

**Pull request merged**
