### PR TITLE
build: fix musl compilation

### PR DESCRIPTION
**Pull request by tamird**

### CODE REVIEW

**Comment by benesch** [comment]
RocksDB patch is unfortunate, but whatever. Glad it plugs the hole in the patch series, I guess.

Maybe I'm just dense, but don't you need to add the musl build to build-static-binaries.sh too?

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15209#-:-KiB637DnVTA9jGKavGW:b-hmsvk7)*

**Comment by tamird** [comment]
Nope, you're right! Nice catch.

**Comment by benesch** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15209#-:-KiB6lk3Hx6I4dTmuk4B:bnfp4nl)*

**Comment by benesch** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15209)*

**Pull request merged**
