### PR TITLE
[CRDB-5534] ui: hot ranges table page

### PR DESCRIPTION
**Pull request by Santamaura**
This PR adds the hot ranges page in a sortable table format. Values in the `range id`, `nodes`, and `database` columns link to their respective pages within crdb for more info.

Resolves: [CC-5804](https://cockroachlabs.atlassian.net/jira/software/c/projects/CRDB/boards/155?modal=detail&selectedIssue=CC-5804) (duplicate)

Notes:
- Tooltip text still needs to be finalized
- This branch was rebased off of [Andrii's endpoint pr](https://github.com/cockroachdb/cockroach/pull/74377) and thus includes his changes to the backend and debug page which can be ignored when reviewing.

Screen Shot 2022-01-19 at 2 03 11 PM

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
I know this is marked as `do-not-merge` but just a heads up that this should not have a `CC` link in the title, that's for CC PRs only. All Jira tickets for CRDB should have a corresponding Github issue that you can reference in the PR/commit description like "Resolves #xxxxx".

Additionally, I strongly suggest working on this as a single commit with amended revisions. Maybe squash once you take the `do-not-merge` tag off and it's ready for review.

Also, make sure this contains a release note once it's revised.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-:-MtsGDAu2ejW_xoqmmuh:b-twncv9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh and @zachlite)

**Review by koorosh — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, 5 of 5 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, 5 of 5 files at r5, 5 of 5 files at r6, 8 of 8 files at r7, 1 of 8 files at r8, 1 of 6 files at r12, 1 of 3 files at r14, 1 of 5 files at r15, 2 of 4 files at r16.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75073)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Santamaura and @zachlite)

___
*[pkg/ui/workspaces/db-console/src/redux/hotRanges/hotRangesReducer.ts, line 32 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-MtxWOka4qxsDrCsyCof:-MtxWOka4qxsDrCsyCog:b-pevv1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/62d85e3fa7467fc89b2c03774f8ba7b26233f0fc/pkg/ui/workspaces/db-console/src/redux/hotRanges/hotRangesReducer.ts#L32)):*
> ```XML
> };
> 
> export default function(state = INITIAL_STATE, action: any): HotRangesState {
> ```

In CRDB, there's `CachedDataReducer` (`pkg/ui/workspaces/db-console/src/redux/cachedDataReducer.ts`) to manage data that can be fetched periodically. This infrastructure establishes generic way to handle errors/loading in flight states, etc, but it is less flexible to manage. It is also a question to CRUX team (cc @nathanstilwell ) to agree if we should use `CachedDataReducer` for new features or redux-toolkit or as default reducer as in current implementation?
___
*[pkg/ui/workspaces/db-console/src/redux/hotRanges/hotRangesReducer.ts, line 42 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-MtxY4Gg9hLedVDLy11s:-MtxY4Gg9hLedVDLy11t:bqyqbb0) ([raw file](https://github.com/cockroachdb/cockroach/blob/62d85e3fa7467fc89b2c03774f8ba7b26233f0fc/pkg/ui/workspaces/db-console/src/redux/hotRanges/hotRangesReducer.ts#L42)):*
> ```XML
>       return {
>         loading: false,
>         lastUpdate: getCurrentDateTime(),
> ```

Reducer should produce new state by exclusively depending on received payload and previous state. Calling `getCurrentDateTime()` inside reducer should be avoided. Instead, you need to call `getCurrentDateTime()` in some saga that dispatches an action with payload that contains current date.

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75073)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @nathanstilwell, and @zachlite)

___
*[pkg/ui/workspaces/db-console/src/redux/hotRanges/hotRangesReducer.ts, line 32 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-MtxWOka4qxsDrCsyCof:-Mty1x-N7sxXgqS5-8Hy:bvfst0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/62d85e3fa7467fc89b2c03774f8ba7b26233f0fc/pkg/ui/workspaces/db-console/src/redux/hotRanges/hotRangesReducer.ts#L32)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

In CRDB, there's `CachedDataReducer` (`pkg/ui/workspaces/db-console/src/redux/cachedDataReducer.ts`) to manage data that can be fetched periodically. This infrastructure establishes generic way to handle errors/loading in flight states, etc, but it is less flexible to manage. It is also a question to CRUX team (cc @nathanstilwell ) to agree if we should use `CachedDataReducer` for new features or redux-toolkit or as default reducer as in current implementation?
</blockquote></details>

I am not sure either could use some other opinion on this..
___
*[pkg/ui/workspaces/db-console/src/redux/hotRanges/hotRangesReducer.ts, line 42 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-MtxY4Gg9hLedVDLy11s:-Mty28uf6uOkSwG8aoPa:budhejx) ([raw file](https://github.com/cockroachdb/cockroach/blob/62d85e3fa7467fc89b2c03774f8ba7b26233f0fc/pkg/ui/workspaces/db-console/src/redux/hotRanges/hotRangesReducer.ts#L42)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Reducer should produce new state by exclusively depending on received payload and previous state. Calling `getCurrentDateTime()` inside reducer should be avoided. Instead, you need to call `getCurrentDateTime()` in some saga that dispatches an action with payload that contains current date.
</blockquote></details>

Done, it's moved to the saga.

**Review by koorosh — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r18.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75073)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @nathanstilwell, @Santamaura, and @zachlite)

___
*[pkg/ui/workspaces/db-console/src/redux/hotRanges/hotRangesReducer.ts, line 32 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-MtxWOka4qxsDrCsyCof:-MuAGXZm3iEDNsw3Aebl:b-qqz6u9) ([raw file](https://github.com/cockroachdb/cockroach/blob/62d85e3fa7467fc89b2c03774f8ba7b26233f0fc/pkg/ui/workspaces/db-console/src/redux/hotRanges/hotRangesReducer.ts#L32)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

I am not sure either could use some other opinion on this..
</blockquote></details>

I thought about this a bit more and would stick with old reducers implementation (with `CachedDataReducer`) because:
- current implementation doesn't allow to reuse it in CC Console and follows different pattern than other reducers;
- current implementation doesn't handle continuous page refresh and state invalidation (that's already implemented in `CachedDataReducer`);
- it allows to avoid additional saga implementations per page.
___
*[pkg/ui/workspaces/db-console/src/redux/hotRanges/hotRangesReducer.ts, line 24 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-MuAF1XG9_crev-hynnr:-MuAF1XG9_crev-hynns:b-6de5xk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0a7686fb6aaeb8214114fea3db23925eca7eb16/pkg/ui/workspaces/db-console/src/redux/hotRanges/hotRangesReducer.ts#L24)):*
> ```XML
> };
> 
> export default function(state = INITIAL_STATE, action: any): HotRangesState {
> ```

Avoid using `any` type for action argument. It is possible to use union of actions types (defined in `hotRangesActions.ts`).
___
*[pkg/ui/workspaces/db-console/src/redux/hotRanges/hotRangesSagas.ts, line 45 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-MuAGB2nBf2HI4-s9fuA:-MuAGB2nBf2HI4-s9fuB:b-ie676d) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0a7686fb6aaeb8214114fea3db23925eca7eb16/pkg/ui/workspaces/db-console/src/redux/hotRanges/hotRangesSagas.ts#L45)):*
> ```XML
> 
> export function* hotRangesSaga() {
>   yield all([takeEvery(GET_HOT_RANGES, getHotRangesSaga)]);
> ```

It might be more convenient to use `takeLatest` instead of `takeEvery` as far as we're interested in most recent request.

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75073)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @nathanstilwell, and @zachlite)

___
*[pkg/ui/workspaces/db-console/src/redux/hotRanges/hotRangesReducer.ts, line 32 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-MtxWOka4qxsDrCsyCof:-MuBvqJi-tQEMHtYU7GX:btwolv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/62d85e3fa7467fc89b2c03774f8ba7b26233f0fc/pkg/ui/workspaces/db-console/src/redux/hotRanges/hotRangesReducer.ts#L32)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

I thought about this a bit more and would stick with old reducers implementation (with `CachedDataReducer`) because:
- current implementation doesn't allow to reuse it in CC Console and follows different pattern than other reducers;
- current implementation doesn't handle continuous page refresh and state invalidation (that's already implemented in `CachedDataReducer`);
- it allows to avoid additional saga implementations per page.
</blockquote></details>

Agreed. I have changed to using `CachedDateReducer` and it has simplified the redux flow and it will now poll to update the data.
___
*[pkg/ui/workspaces/db-console/src/redux/hotRanges/hotRangesReducer.ts, line 24 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-MuAF1XG9_crev-hynnr:-MuC2bns1U6ixSDRG0ut:b-i11auu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0a7686fb6aaeb8214114fea3db23925eca7eb16/pkg/ui/workspaces/db-console/src/redux/hotRanges/hotRangesReducer.ts#L24)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Avoid using `any` type for action argument. It is possible to use union of actions types (defined in `hotRangesActions.ts`).
</blockquote></details>

:thumbsup: file has been removed as it is not needed when using `CachedDataReducer`
___
*[pkg/ui/workspaces/db-console/src/redux/hotRanges/hotRangesSagas.ts, line 45 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-MuAGB2nBf2HI4-s9fuA:-MuC2ijH8LgmCQc4ETlB:b-7aepth) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0a7686fb6aaeb8214114fea3db23925eca7eb16/pkg/ui/workspaces/db-console/src/redux/hotRanges/hotRangesSagas.ts#L45)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

It might be more convenient to use `takeLatest` instead of `takeEvery` as far as we're interested in most recent request.
</blockquote></details>

:thumbsup: file has been removed.

**Review by koorosh — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r19.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75073)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @nathanstilwell, @Santamaura, and @zachlite)

___
*[pkg/ui/workspaces/db-console/src/views/hotRanges/hotRangesTable.tsx, line 31 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-MuCptJ9AYpHUSYHxhH4:-MuCptJ9AYpHUSYHxhH5:b-m58p7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/21dcaf9a3eb8e33efaa20b2c90ba97c80d2558cf/pkg/ui/workspaces/db-console/src/views/hotRanges/hotRangesTable.tsx#L31)):*
> ```XML
>   const [sortSetting, setSortSetting] = useState({
>     ascending: true,
>     columnTitle: null,
> ```

By default, it has to be sorted by QPS column in descending order?



_Code quote:_
```XML
    ascending: true,
    columnTitle: null,
```
___
*[pkg/ui/workspaces/db-console/src/views/hotRanges/hotRangesTable.tsx, line 68 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-MuCsSC33mZ6K5Tmu1H7:-MuCsSC33mZ6K5Tmu1H8:b-ihm8kb) ([raw file](https://github.com/cockroachdb/cockroach/blob/21dcaf9a3eb8e33efaa20b2c90ba97c80d2558cf/pkg/ui/workspaces/db-console/src/views/hotRanges/hotRangesTable.tsx#L68)):*
> ```XML
>       ),
>       cell: (val: HotRange) => (
>         <Link to={`/node/${val.replica_node_ids[0]}`}>
> ```

Can you map over replica ids and create multiple links for every replica? I don't think we should navigate to first replica only.
___
*[pkg/ui/workspaces/db-console/src/views/hotRanges/hotRangesTable.tsx, line 102 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-MuCthM15uKw7w_7pg3o:-MuCthM15uKw7w_7pg3p:b-ahazan) ([raw file](https://github.com/cockroachdb/cockroach/blob/21dcaf9a3eb8e33efaa20b2c90ba97c80d2558cf/pkg/ui/workspaces/db-console/src/views/hotRanges/hotRangesTable.tsx#L102)):*
> ```XML
>       ),
>       cell: (val: HotRange) => (
>         <Link to={`/database/${val.database_name}/table/${val.table_name}`}>
> ```

Some ranges can contain empty strings for database, and table names. Can we somehow validate such cases to avoid malformed links?
Also, as discussed in figma (https://www.figma.com/file/vgQDWxqSFzjCJdMBV4Po3u?node-id=2729:9311#137465754) table name should represent fully qualified name (schema name with table name) ie. `system.ranges` where system is a schema name that is also provided within response. Note, that it's possible that schema can be empty and non empty table name.
___
*[pkg/ui/workspaces/db-console/src/views/hotRanges/index.tsx, line 48 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-MuCythSD3JgsdVzcsZC:-MuCythSD3JgsdVzcsZD:botb1wh) ([raw file](https://github.com/cockroachdb/cockroach/blob/21dcaf9a3eb8e33efaa20b2c90ba97c80d2558cf/pkg/ui/workspaces/db-console/src/views/hotRanges/index.tsx#L48)):*
> ```XML
>       <Helmet title="Hot Ranges" />
>       <h1 className="base-heading">Hot ranges</h1>
>       <Text className={cx("hotranges-description")}>The hot ranges table shows ranges receiving a high number of reads or writes. By default the table is sorted by <br /> ranges with the highest QPS (Queries Per Second). Use this information to... <a href="" target="_blank">Learn more</a></Text>
> ```

- Can you add TODO or/and file another issue to add proper links on documentation so we don't forget about it later?
- Prefer to use `<Anchor>` component (`pkg/ui/workspaces/cluster-ui/src/anchor/anchor.tsx`) instead of `<a>` to use proper styles.

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75073)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @nathanstilwell, and @zachlite)

___
*[pkg/ui/workspaces/db-console/src/views/hotRanges/hotRangesTable.tsx, line 31 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-MuCptJ9AYpHUSYHxhH4:-MuGxhnd99j4KKZaidkB:b97akdv) ([raw file](https://github.com/cockroachdb/cockroach/blob/21dcaf9a3eb8e33efaa20b2c90ba97c80d2558cf/pkg/ui/workspaces/db-console/src/views/hotRanges/hotRangesTable.tsx#L31)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

By default, it has to be sorted by QPS column in descending order?
</blockquote></details>

Correct, done.
___
*[pkg/ui/workspaces/db-console/src/views/hotRanges/hotRangesTable.tsx, line 68 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-MuCsSC33mZ6K5Tmu1H7:-MuGxm2X8fJRnX6qPEEj:b-r2kt26) ([raw file](https://github.com/cockroachdb/cockroach/blob/21dcaf9a3eb8e33efaa20b2c90ba97c80d2558cf/pkg/ui/workspaces/db-console/src/views/hotRanges/hotRangesTable.tsx#L68)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Can you map over replica ids and create multiple links for every replica? I don't think we should navigate to first replica only.
</blockquote></details>

Good catch thanks.
___
*[pkg/ui/workspaces/db-console/src/views/hotRanges/hotRangesTable.tsx, line 102 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-MuCthM15uKw7w_7pg3o:-MuGxpe_5Z3DmeN_sNBO:b-rc95xv) ([raw file](https://github.com/cockroachdb/cockroach/blob/21dcaf9a3eb8e33efaa20b2c90ba97c80d2558cf/pkg/ui/workspaces/db-console/src/views/hotRanges/hotRangesTable.tsx#L102)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Some ranges can contain empty strings for database, and table names. Can we somehow validate such cases to avoid malformed links?
Also, as discussed in figma (https://www.figma.com/file/vgQDWxqSFzjCJdMBV4Po3u?node-id=2729:9311#137465754) table name should represent fully qualified name (schema name with table name) ie. `system.ranges` where system is a schema name that is also provided within response. Note, that it's possible that schema can be empty and non empty table name.
</blockquote></details>

Good catch on the malformed links. I didn't see that discussion in figma, thanks for pointing it out. Both have been done.
___
*[pkg/ui/workspaces/db-console/src/views/hotRanges/index.tsx, line 48 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-MuCythSD3JgsdVzcsZC:-MuGy4BC4OlogVbxUhW5:b-njdlmi) ([raw file](https://github.com/cockroachdb/cockroach/blob/21dcaf9a3eb8e33efaa20b2c90ba97c80d2558cf/pkg/ui/workspaces/db-console/src/views/hotRanges/index.tsx#L48)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

- Can you add TODO or/and file another issue to add proper links on documentation so we don't forget about it later?
- Prefer to use `<Anchor>` component (`pkg/ui/workspaces/cluster-ui/src/anchor/anchor.tsx`) instead of `<a>` to use proper styles.
</blockquote></details>

Added a TODO and switched to using `<Anchor>`

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75073)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @nathanstilwell, and @zachlite)

___
*[pkg/ui/workspaces/db-console/src/views/hotRanges/index.tsx, line 48 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-MuCythSD3JgsdVzcsZC:-MuGz9urEen-PEyX-iGW:b1aokql) ([raw file](https://github.com/cockroachdb/cockroach/blob/21dcaf9a3eb8e33efaa20b2c90ba97c80d2558cf/pkg/ui/workspaces/db-console/src/views/hotRanges/index.tsx#L48)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

Added a TODO and switched to using `<Anchor>`
</blockquote></details>

Github issue: https://github.com/cockroachdb/cockroach/issues/75502

**Review by koorosh — COMMENTED** [review]
LGTM! I think it is ready to be merged as soon as https://github.com/cockroachdb/cockroach/pull/74377 PR is merged

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-:-MuMkO4N-FhLQTG5sNpR:bwo2z4e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @nathanstilwell, and @zachlite)

**Review by Santamaura — COMMENTED** [review]
Won't some changes need to be made to switch to using server side pagination?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-:-MuMlQQ-30TIj65XY_mE:b-tr92hd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @nathanstilwell, and @zachlite)

**Review by koorosh — COMMENTED** [review]
Definitely, you're right!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-:-MuQVy91D1Y_TxJE-tfr:bpvt5as)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @nathanstilwell, and @zachlite)

**Review by dhartunian — COMMENTED** [review]
> Reviewed 1 of 5 files at r2, 1 of 3 files at r3, 3 of 5 files at r6, 6 of 8 files at r7, 1 of 8 files at r8, 1 of 3 files at r14, 1 of 5 files at r18, 2 of 9 files at r19, 2 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75073)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @nathanstilwell, @Santamaura, and @zachlite)

___
*[pkg/ui/workspaces/db-console/src/views/reports/containers/debug/index.tsx, line 421 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-Mukklf60NYkSalIoHhO:-Mukklf60NYkSalIoHhP:bw1d3in) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a3da9dd02d6128290b0d7bba2a76e0ba170d0ec/pkg/ui/workspaces/db-console/src/views/reports/containers/debug/index.tsx#L421)):*
> ```XML
>             name="All Nodes"
>             url="#/debug/hotranges"
>             note="#/debug/hotranges"
> ```

Some folks might still rely on the older hotrange pages. Are we keeping them around? If so, might be nice to keep the old links as "Hot Ranges (legacy)" perhaps.
___
*[pkg/ui/workspaces/db-console/src/views/reports/containers/hotranges/index.tsx, line 36 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-MukkyBv7g_gDbMzvvp2:-MukkyBv7g_gDbMzvvp3:b6vfgmf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a3da9dd02d6128290b0d7bba2a76e0ba170d0ec/pkg/ui/workspaces/db-console/src/views/reports/containers/hotranges/index.tsx#L36)):*
> ```XML
>     });
>   }, [nodeId]);
>   // eslint-disable-next-line react-hooks/exhaustive-deps
> ```

nit: can you add a comment explaining why this is necessary?
___
*[pkg/ui/workspaces/db-console/src/views/hotRanges/index.tsx, line 43 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-MukkI_I8Gt3HgnpXH1h:-MukkI_J2MbkEIvpeOPm:b-ahlk3g) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a3da9dd02d6128290b0d7bba2a76e0ba170d0ec/pkg/ui/workspaces/db-console/src/views/hotRanges/index.tsx#L43)):*
> ```XML
>     );
>   };
>   // TODO: Alex S add url to anchor once it's available
> ```

nit: please use `// TODO(santamaura)` format for TODOs (you can use your github or slack username in there but just something that clearly identifies. Unfortunately, we have multiple Alex S devs already).
___
*[pkg/ui/workspaces/db-console/src/views/hotRanges/index.tsx, line 50 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-MukkayB8Ouiv0x9glVq:-MukkayB8Ouiv0x9glVr:b-434eb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a3da9dd02d6128290b0d7bba2a76e0ba170d0ec/pkg/ui/workspaces/db-console/src/views/hotRanges/index.tsx#L50)):*
> ```XML
>       <Text className={cx("hotranges-description")}>
>         The hot ranges table shows ranges receiving a high number of reads or writes. By default the table is sorted by 
>         <br /> 
> ```

nit: I see trailing spaces here. Does eslint not take care of this?

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75073)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @koorosh, @nathanstilwell, and @zachlite)

___
*[pkg/ui/workspaces/db-console/src/views/reports/containers/debug/index.tsx, line 421 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-Mukklf60NYkSalIoHhO:-MulWTPG0t6_ClCeOhy8:b31jq9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a3da9dd02d6128290b0d7bba2a76e0ba170d0ec/pkg/ui/workspaces/db-console/src/views/reports/containers/debug/index.tsx#L421)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Some folks might still rely on the older hotrange pages. Are we keeping them around? If so, might be nice to keep the old links as "Hot Ranges (legacy)" perhaps.
</blockquote></details>

Sorry David, these changes are a part of https://github.com/cockroachdb/cockroach/pull/74377 which this PR is rebased on. cc @koorosh 
___
*[pkg/ui/workspaces/db-console/src/views/reports/containers/hotranges/index.tsx, line 36 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-MukkyBv7g_gDbMzvvp2:-MulWcuU1hnKTG0sXGqU:b-9vk6bk) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a3da9dd02d6128290b0d7bba2a76e0ba170d0ec/pkg/ui/workspaces/db-console/src/views/reports/containers/hotranges/index.tsx#L36)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: can you add a comment explaining why this is necessary?
</blockquote></details>

Same as above comment cc @koorosh 
___
*[pkg/ui/workspaces/db-console/src/views/hotRanges/index.tsx, line 43 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-MukkI_I8Gt3HgnpXH1h:-MulWFhk97b-l1POoQlH:b-g1hs46) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a3da9dd02d6128290b0d7bba2a76e0ba170d0ec/pkg/ui/workspaces/db-console/src/views/hotRanges/index.tsx#L43)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: please use `// TODO(santamaura)` format for TODOs (you can use your github or slack username in there but just something that clearly identifies. Unfortunately, we have multiple Alex S devs already).
</blockquote></details>

Makes sense, done.
___
*[pkg/ui/workspaces/db-console/src/views/hotRanges/index.tsx, line 50 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-MukkayB8Ouiv0x9glVq:-MulWJ575_HT27p_Lsqr:b-o1zqoa) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a3da9dd02d6128290b0d7bba2a76e0ba170d0ec/pkg/ui/workspaces/db-console/src/views/hotRanges/index.tsx#L50)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: I see trailing spaces here. Does eslint not take care of this?
</blockquote></details>

Ah odd eslint wasn't on when I committed this, should be ok now.

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75073)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @koorosh, @nathanstilwell, @Santamaura, and @zachlite)

___
*[pkg/ui/workspaces/db-console/src/views/reports/containers/debug/index.tsx, line 421 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-Mukklf60NYkSalIoHhO:-MupAxPZBQMB7-4qDQVn:bxa0m85) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a3da9dd02d6128290b0d7bba2a76e0ba170d0ec/pkg/ui/workspaces/db-console/src/views/reports/containers/debug/index.tsx#L421)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

Sorry David, these changes are a part of https://github.com/cockroachdb/cockroach/pull/74377 which this PR is rebased on. cc @koorosh 
</blockquote></details>

Agree, we can keep both pages for now. Will update in original PR.
___
*[pkg/ui/workspaces/db-console/src/views/reports/containers/hotranges/index.tsx, line 36 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/75073#-MukkyBv7g_gDbMzvvp2:-MupSQm291aeISxmPrBt:b-brg4c4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a3da9dd02d6128290b0d7bba2a76e0ba170d0ec/pkg/ui/workspaces/db-console/src/views/reports/containers/hotranges/index.tsx#L36)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

Same as above comment cc @koorosh 
</blockquote></details>

Ack! Will update in original PR.

**Comment by koorosh** [comment]
This PR can be closed in favor of https://github.com/cockroachdb/cockroach/pull/77330

**Pull request closed without merging**
