### PR TITLE
asim: add state exchange for stores

### PR DESCRIPTION
**Pull request by kvoli**
This patch adds state exchange for the allocation simulator. State
exchange controls the dissemination of a store's state, to every other
store in a simulation.

The first implementation is simple fixed delay state exchange. It groups
puts at an interval, selecting the last put for each descriptor within
an interval. Updates propagate uniformly, such that a get at time
t, will retrieve the largest tick t' <= t - delay * interval.

Release note: None

### CODE REVIEW

**Review by lidorcarmel — CHANGES_REQUESTED** [review]
another good step, thank you Austen!

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81710#-:-N2wBCdJ5DNHAzZvcuVt:bqg00h7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/asim/asim.go` line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81710#-N2vtDSh791plbdcOPTW:-N2vtDSh791plbdcOPTX:bfhwbww) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ece3c32470eb5e40a2f060464da54e7f7006bb8/pkg/kv/kvserver/asim/asim.go#L244)):*
> ```Go
> 
> func (s *State) storeDescriptors() []roachpb.StoreDescriptor {
> 	storeDescriptors := []roachpb.StoreDescriptor{}
> ```

golang style question - is it better/nicer to use `make` here? maybe with a higher capacity. this is just me wondering..
___
*[`pkg/kv/kvserver/asim/asim.go` line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81710#-N2vtBcS6YSehXIN0HvE:-N2vtBcS6YSehXIN0HvF:b-hfpv1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ece3c32470eb5e40a2f060464da54e7f7006bb8/pkg/kv/kvserver/asim/asim.go#L253)):*
> ```Go
> 				Capacity: store.Capacity(),
> 			}
> 			store.Capacity()
> ```

remove?
___
*[`pkg/kv/kvserver/asim/state_exchange.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81710#-N2vx-cP0nkPIJOp6Tx8:-N2vx-cP0nkPIJOp6Tx9:b7f3uhl) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ece3c32470eb5e40a2f060464da54e7f7006bb8/pkg/kv/kvserver/asim/state_exchange.go#L32)):*
> ```Go
> 
> 	// Get retrieves store view of the state exchange at tick t.
> 	Get(tick time.Time, StoreID roachpb.StoreID) map[roachpb.StoreID]*storepool.StoreDetail
> ```

can we drop the `StoreID` parameter here?
___
*[`pkg/kv/kvserver/asim/state_exchange.go` line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81710#-N2wAEYvE9zbPj3C-JGU:-N2wAEYvE9zbPj3C-JGV:b-7rj2k5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ece3c32470eb5e40a2f060464da54e7f7006bb8/pkg/kv/kvserver/asim/state_exchange.go#L87)):*
> ```Go
> 
> 	for _, desc := range descs {
> 		// Create store new store detail.
> ```

drop?



_Code quote:_
```Go
store
```
___
*[`pkg/kv/kvserver/asim/state_exchange_test.go` line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81710#-N2w98AT2QU9xDAElf4X:-N2w98AT2QU9xDAElf4Y:b-ciw72r) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ece3c32470eb5e40a2f060464da54e7f7006bb8/pkg/kv/kvserver/asim/state_exchange_test.go#L97)):*
> ```Go
> 	}
> 
> 	makePuts := func(tick int64, stores []int32) []roachpb.StoreDescriptor {
> ```

nit: this one doesn't really make puts, right? maybe makeStores? makeStoreDescriptors?



_Code quote:_
```Go
makePuts
```

**Review by kvoli — COMMENTED** [review]
Thanks, updated with feedback.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81710#-:-N2xA5fjAyL33gl9I1yX:b-k8rlre)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lidorcarmel)

___
*[`pkg/kv/kvserver/asim/asim.go` line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81710#-N2vtDSh791plbdcOPTW:-N2x8YD3EMjpzZEw3An8:b-gziz96) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ece3c32470eb5e40a2f060464da54e7f7006bb8/pkg/kv/kvserver/asim/asim.go#L244)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

golang style question - is it better/nicer to use `make` here? maybe with a higher capacity. this is just me wondering..
</blockquote></details>

Updated. We don't really know how many stores there are without looping at the moment (well we do because   len(nodes) is the num stores but that will change when we support multi store).
___
*[`pkg/kv/kvserver/asim/asim.go` line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81710#-N2vtBcS6YSehXIN0HvE:-N2x8sFC1rmnt4lA2gNX:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ece3c32470eb5e40a2f060464da54e7f7006bb8/pkg/kv/kvserver/asim/asim.go#L253)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

remove?
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/asim/state_exchange.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81710#-N2vx-cP0nkPIJOp6Tx8:-N2x8y6K2vFq4dGjVUs7:b-g25pua) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ece3c32470eb5e40a2f060464da54e7f7006bb8/pkg/kv/kvserver/asim/state_exchange.go#L32)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

can we drop the `StoreID` parameter here?
</blockquote></details>

We can't. The current impl has a fixed delay that is equal for every store. In the future, we will want to have some distribution for what different stores see and when.
___
*[`pkg/kv/kvserver/asim/state_exchange.go` line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81710#-N2wAEYvE9zbPj3C-JGU:-N2x9MC83CLq4mcQImkU:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ece3c32470eb5e40a2f060464da54e7f7006bb8/pkg/kv/kvserver/asim/state_exchange.go#L87)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

drop?
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/asim/state_exchange_test.go` line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81710#-N2w98AT2QU9xDAElf4X:-N2x9dCaA__xN4TTE3pR:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ece3c32470eb5e40a2f060464da54e7f7006bb8/pkg/kv/kvserver/asim/state_exchange_test.go#L97)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

nit: this one doesn't really make puts, right? maybe makeStores? makeStoreDescriptors?
</blockquote></details>

Updated.

**Review by lidorcarmel — APPROVED** [review]
thank you! lgtm.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81710#-:-N2xdmZ0AKJb9UDlad6G:bsrcvjr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/asim/asim.go` line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81710#-N2vtDSh791plbdcOPTW:-N2xbjEa1R-OGckRaRtS:bmjstm0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ece3c32470eb5e40a2f060464da54e7f7006bb8/pkg/kv/kvserver/asim/asim.go#L244)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Updated. We don't really know how many stores there are without looping at the moment (well we do because   len(nodes) is the num stores but that will change when we support multi store).
</blockquote></details>

thanks. I was thinking about len(nodes) as you said, it's fine to be less efficient with multi store. but anyway my question here was mostly on style.
___
*[`pkg/kv/kvserver/asim/state_exchange.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81710#-N2vx-cP0nkPIJOp6Tx8:-N2xc4L79LNvr0CTfm2C:b-m7kvxv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ece3c32470eb5e40a2f060464da54e7f7006bb8/pkg/kv/kvserver/asim/state_exchange.go#L32)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

We can't. The current impl has a fixed delay that is equal for every store. In the future, we will want to have some distribution for what different stores see and when.
</blockquote></details>

got it. maybe worth a comment? say someone sees this code 6 months from now they may think "this is not used, let's drop".

another way to see this would be yagni - you aren't gonna need it - so don't add until you really need it. but it's ok to keep it now.. just saying that sometimes it's easy to not add vs add and explain why it was added. (or maybe I completely missed something and it is used already here??)
___
*[`pkg/kv/kvserver/asim/state_exchange.go` line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81710#-N2wAEYvE9zbPj3C-JGU:-N2xdOjDDqQFEMmV4DB8:b-do7ft7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ece3c32470eb5e40a2f060464da54e7f7006bb8/pkg/kv/kvserver/asim/state_exchange.go#L87)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Updated.
</blockquote></details>

oh sorry, I meant just to drop the word "store" that was there twice.. I should have been more clear, the quoted response can be missed sometimes I guess. or maybe you understood and removed it because it's obvious.. that would make sense also.

**Review by kvoli — COMMENTED** [review]
TYFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81710#-:-N3-Y5Pw7uS8_FxiXXkk:bzftgo7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lidorcarmel)

___
*[`pkg/kv/kvserver/asim/asim.go` line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81710#-N2vtDSh791plbdcOPTW:-N3-XuWk2sUgAR3VbIwj:bmlbbn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ece3c32470eb5e40a2f060464da54e7f7006bb8/pkg/kv/kvserver/asim/asim.go#L244)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

thanks. I was thinking about len(nodes) as you said, it's fine to be less efficient with multi store. but anyway my question here was mostly on style.
</blockquote></details>

I'll add an issue to do a full sweep for multi-store support. Shouldn't be major, will leave as is atm.
___
*[`pkg/kv/kvserver/asim/state_exchange.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81710#-N2vx-cP0nkPIJOp6Tx8:-N3-XHq-BdNUJLHnV-_X:bdxdxme) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ece3c32470eb5e40a2f060464da54e7f7006bb8/pkg/kv/kvserver/asim/state_exchange.go#L32)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

got it. maybe worth a comment? say someone sees this code 6 months from now they may think "this is not used, let's drop".

another way to see this would be yagni - you aren't gonna need it - so don't add until you really need it. but it's ok to keep it now.. just saying that sometimes it's easy to not add vs add and explain why it was added. (or maybe I completely missed something and it is used already here??)
</blockquote></details>

Added a comment here and explanation on fixed delay.  The main reason I left it general was because it really made little difference to the interface but I do foresee simulating partitions, a distribution of delay per store etc (although this is less important given our findings on gossip).
___
*[`pkg/kv/kvserver/asim/state_exchange.go` line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81710#-N2wAEYvE9zbPj3C-JGU:-N3-XizZApI9RIPu1ua4:b-5ezp41) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ece3c32470eb5e40a2f060464da54e7f7006bb8/pkg/kv/kvserver/asim/state_exchange.go#L87)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

oh sorry, I meant just to drop the word "store" that was there twice.. I should have been more clear, the quoted response can be missed sometimes I guess. or maybe you understood and removed it because it's obvious.. that would make sense also.
</blockquote></details>

It seemed obvious, removed since it didn't add  anything to "why", just explaining code.

**Review by lidorcarmel — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81710)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/asim/asim.go` line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81710#-N2vtDSh791plbdcOPTW:-N301uz4DYeJRq1FIzwA:bhb6e83) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ece3c32470eb5e40a2f060464da54e7f7006bb8/pkg/kv/kvserver/asim/asim.go#L244)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

I'll add an issue to do a full sweep for multi-store support. Shouldn't be major, will leave as is atm.
</blockquote></details>

sg, thanks. I agree there is no need to worry about multi store now.
___
*[`pkg/kv/kvserver/asim/state_exchange.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81710#-N2vx-cP0nkPIJOp6Tx8:-N302LuqAqa-2EZxxPhD:b-7jh2w4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ece3c32470eb5e40a2f060464da54e7f7006bb8/pkg/kv/kvserver/asim/state_exchange.go#L32)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Added a comment here and explanation on fixed delay.  The main reason I left it general was because it really made little difference to the interface but I do foresee simulating partitions, a distribution of delay per store etc (although this is less important given our findings on gossip).
</blockquote></details>

sgtm.
___
*[`pkg/kv/kvserver/asim/state_exchange.go` line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81710#-N302bO42xEnaoRpg9Sw:-N302bO51xls653tuA7T:bb7phvt) ([raw file](https://github.com/cockroachdb/cockroach/blob/680b464d339492ef58a6fafe772f4efe4aacd51b/pkg/kv/kvserver/asim/state_exchange.go#L98)):*
> ```Go
> 
> // Get retrieves a store's view of the state exchange at tick t. In this
> // simplie implementation of state exchange, all stores have an symmetrical
> ```

typo



_Code quote:_
```Go
simplie
```
___
*[`pkg/kv/kvserver/asim/state_exchange.go` line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81710#-N302fIK5zbiCuYIJ5Lb:-N302fIK5zbiCuYIJ5Lc:b3ksc) ([raw file](https://github.com/cockroachdb/cockroach/blob/680b464d339492ef58a6fafe772f4efe4aacd51b/pkg/kv/kvserver/asim/state_exchange.go#L98)):*
> ```Go
> 
> // Get retrieves a store's view of the state exchange at tick t. In this
> // simplie implementation of state exchange, all stores have an symmetrical
> ```

a



_Code quote:_
```Go
an
```

**Review by lidorcarmel — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81710)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

**Pull request merged**
