### PR TITLE
Change runBenchmarkUpdate to always use a single statement.

### PR DESCRIPTION
**Pull request by petermattis**
This makes BenchmarkUpdate similar to BenchmarkDelete and allows
comparison between the speed of the two benchmarks. Previously,
BenchmarkUpdate was performing a separate statement for every updated
row. Not shown below is that the time for updating 1/10/100 rows is now
in line with deleting 1/10/100 rows. The numbers highlight the benefit
of batching operations as much as possible.

```
name                   old time/op    new time/op    delta
Update1_Cockroach-8       468µs ± 1%     473µs ± 1%   +1.04%   (p=0.000 n=10+9)
Update10_Cockroach-8     3.74ms ± 1%    1.10ms ± 1%  -70.66%   (p=0.000 n=10+9)
Update100_Cockroach-8    32.9ms ± 0%     6.3ms ± 2%  -80.77%  (p=0.000 n=10+10)

name                   old allocs/op  new allocs/op  delta
Update1_Cockroach-8         479 ± 0%       496 ± 0%   +3.59%  (p=0.000 n=10+10)
Update10_Cockroach-8      4.38k ± 0%     1.17k ± 0%  -73.22%   (p=0.000 n=6+10)
Update100_Cockroach-8     41.7k ± 0%      7.5k ± 0%  -81.95%  (p=0.000 n=10+10)
```

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4399)

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM

**Comment by bdarnell** [comment]
LGTM. It might be worthwhile to keep both versions around so that we can compare the performance when we implement #4403.

Now that `Update100` is a single statement, does it have the same performance anomaly as `Delete100` in #4386?

**Comment by RaduBerinde** [comment]
LGTM

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4399#-:-KAfFUIU-zyD5q91C6gA:676834233)*

**Comment by petermattis** [comment]
@bdarnell Rather than keeping around the previous `Update` benchmarks, I'll file an issue to benchmark multi-statement transaction performance.

**Pull request merged**
