### PR TITLE
changefeedccl: Move running count under metric label.

### LINKED ISSUE #75681: changefeedccl: include changefeed_running metric in metrics labels
See: https://cockroachlabs.atlassian.net/wiki/spaces/CDC/pages/2398552506/22.1+Metrics+Labels+Acceptance+Testing for reproducibility

The changefeed_running metric is not counted separately for different changefeed metrics labels, we should include this metric as it makes it clear when a new changefeed is added to a metrics label.

### PR DESCRIPTION
**Pull request by miretskiy**
Move running count metric to work under metric labels.

Fixes #75681

Release Notes: None

### CODE REVIEW

**Comment by miretskiy** [comment]
@HonoreDB friendly ping

**Review by sherman-grewal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76067)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @miretskiy)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 932 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76067#-Mvt2GWk7SG4LumljHa_:-Mvt2GWk7SG4LumljHaa:b-z2xtsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0c533d351b4e0268e642ad43483cb49cf2cc6b6/pkg/ccl/changefeedccl/changefeed_processors.go#L932)):*
> ```Go
> 	// metrics are monitoring counters shared between all changefeeds.
> 	metrics    *Metrics
> 	sliMetrics *sliMetrics
> ```

This looks good! I was wondering if it were possible to add a unit test to make sure that the running count is measured as expected. I will let @honoredb give it a look though

**Review by HonoreDB — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76067)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

**Pull request merged**
