### PR TITLE
sql/sqlbase: add a hard coded list of interesting datums to RandDatum

### PR DESCRIPTION
**Pull request by madelynnblue**
This should improve randomized test coverage by producing more interesting
datums more often.

Release note: None

### CODE REVIEW

**Comment by mjibson** [comment]
First two commits from another PR, ignore them. Just needed for the constants from the new date package.

**Comment by andy-kimball** [comment]
Matt, I made significant changes to the random type/datum generation routines in the type system refactor PR. I'm getting ready to merge that. Can you rebase this on top of that?

**Comment by mjibson** [comment]
Yes, will do.

**Comment by mjibson** [comment]
RFAL.

**Review by jordanlewis — COMMENTED** [review]
:lgtm: nice idea!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36964#-:-LdysS-N16fq6NjVDbcx:b-kjv2kq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @justinj)

**Comment by mjibson** [comment]
Added some commits to address failures caught by these improved tests! PTAL.

**Comment by mjibson** [comment]
ping @jordanlewis

**Comment by jordanlewis** [comment]
@mjibson it looks like there might still be some CI issues?

**Review by jordanlewis — COMMENTED** [review]
:lgtm: though

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36964#-:-LeTVS56ASvl5QWssHw6:b-v6pkie)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj and @mjibson)

___
*[pkg/sql/distsqlplan/aggregator_funcs_test.go, line 382 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36964#-LeTUVOu-m-XIKCCPMLF:-LeTUVOu-m-XIKCCPMLG:bu272rw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8685de4a26d3ff2622e4065d4d6baa5be90a6dc7/pkg/sql/distsqlplan/aggregator_funcs_test.go#L382)):*
> ```Go
> 
> // https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/
> func almostEqualRelative(a, b float64) bool {
> ```

minor nit: I would consider moving some of the documentation above to this function's godoc.

**Comment by mjibson** [comment]
@danhhz Can you review the changefeed commit?

**Review by danhhz — COMMENTED** [review]
changefeedccl :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36964#-:-LeqmTNjD-tFISVgNJYE:bfg778z)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj and @mjibson)

___
*[pkg/ccl/changefeedccl/avro_test.go, line 185 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/36964#-LeqlyE65_D0S8T7HHLZ:-LeqlyE72YSOynwHfoPJ:bfhtcnf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d7fc91c911fc2f1d22e0d7cec3970a835891791/pkg/ccl/changefeedccl/avro_test.go#L185)):*
> ```Go
> 			// timestamps that don't fit in an int32, so
> 			// restrict input to fit.
> 			t := time.Unix(rng.Int63n(2e6)-1e6, rng.Int63n(1e9)).Truncate(time.Millisecond)
> ```

can you comment where all these constants come from? i actually don't know offhand

also nit: instead of `rng.Int63n(2e6)-1e6`, throw a small `randInt(rng *rand.Rand, min, max int) int` method in this file and use it

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36964)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @danhhz, @justinj, and @mjibson)

___
*[pkg/ccl/changefeedccl/avro_test.go, line 185 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/36964#-LeqlyE65_D0S8T7HHLZ:-LernnIE4oBlGlTehcdw:b-cpblhc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d7fc91c911fc2f1d22e0d7cec3970a835891791/pkg/ccl/changefeedccl/avro_test.go#L185)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

can you comment where all these constants come from? i actually don't know offhand

also nit: instead of `rng.Int63n(2e6)-1e6`, throw a small `randInt(rng *rand.Rand, min, max int) int` method in this file and use it
</blockquote></details>

I rejiggered this and may have found the actual goavro bug, which is that time.Times you send to goavro must have a nanosecond representation that fits in an int64. The current code makes this clear.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36964)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @justinj and @mjibson)

___
*[pkg/ccl/changefeedccl/avro_test.go, line 185 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/36964#-LeqlyE65_D0S8T7HHLZ:-Lerssee8tjZgnLcWf5B:b-bap41s) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d7fc91c911fc2f1d22e0d7cec3970a835891791/pkg/ccl/changefeedccl/avro_test.go#L185)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I rejiggered this and may have found the actual goavro bug, which is that time.Times you send to goavro must have a nanosecond representation that fits in an int64. The current code makes this clear.
</blockquote></details>

This looks great, thanks!

**Pull request merged**
