### PR TITLE
roachpb: pretty-print range descriptors

### PR DESCRIPTION
**Pull request by andreimatei**
Printing the protobuf with %s, %v or %+v used to give:
range_id:3 start_key:"\274\211\212" end_key:"\274\211\213" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2

now:
<RangeID:1 keys:/Min-/Max replicas:[{1 1 1}] nrid:2>

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/roachpb/metadata.go, line 102 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14951#-KhjX26Ho3qb01Oky8ib:-KhjX26Ho3qb01Oky8ic:b-f7xngf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c1ac7f3b16bc20221c0f7f3c57a49f76338a9b5/pkg/roachpb/metadata.go#L102)):*
> ```Go
> 
> func (r RangeDescriptor) String() string {
> 	return fmt.Sprintf("<RangeID:%d keys:%s-%s replicas:%v nrid:%d>",
> ```

how about "r%d [%s-%s) replicas:%v nrid:%d"? cc @petermattis 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14951)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/roachpb/metadata.go, line 102 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14951#-KhjX26Ho3qb01Oky8ib:-KhtzGFyxGOJ4hKqJz25:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c1ac7f3b16bc20221c0f7f3c57a49f76338a9b5/pkg/roachpb/metadata.go#L102)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

how about "r%d [%s-%s) replicas:%v nrid:%d"? cc @petermattis 
</blockquote></details>

:thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14951#-:-KhtzHruQamTt93-YeSN:bnfp4nl)*

**Comment by tamird** [comment]
Also I believe @spencerkimball just added this method in another PR.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14951#-:-KhvXRLwEYbOMu3Wz5-V:b9hklxu)*

**Comment by andreimatei** [comment]
closing this for Spencer's

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14951#-:-KhxM5s4D20CkOaeu8t9:b-os6ddf)*

**Pull request closed without merging**
