### PR TITLE
execgen: some small improvements

### PR DESCRIPTION
**Pull request by jordanlewis**
- Use `imports` to avoid having to precisely specify template imports
- Use `strings.Replacer` to streamline some code

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
Nice! :lgtm:

> Reviewed 22 of 22 files at r1, 24 of 24 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49727#-:-M8Y0pvw0AiR-I87hrY8:be8rotp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/col/coldata/vec_tmpl.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49727#-M8Xz-VLCC1OO5HK5s8G:-M8Xz-VLCC1OO5HK5s8H:b-axhu4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b7502933254e34b4b4a4caac637d168a827f9f2/pkg/col/coldata/vec_tmpl.go#L38)):*
> ```Go
> 
> // Dummy import to pull in "typeconv" package.
> var _ = typeconv.DatumVecCanonicalTypeFamily
> ```

This can also be removed I think (and in a few other templates where we have this line).
___
*[pkg/sql/colexec/execgen/cmd/execgen/distinct_gen.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49727#-M8Y00Ie-lMYavRfYms7:-M8Y00Ie-lMYavRfYms8:bbenm6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ffdfe6a6b8f94ce40935f08c9c369edd419c0af/pkg/sql/colexec/execgen/cmd/execgen/distinct_gen.go#L32)):*
> ```Go
> 	r := strings.NewReplacer(
> 		"_CANONICAL_TYPE_FAMILY", "{{.CanonicalTypeFamilyStr}}",
> 		"_CANONICAL_TYPE_FAMILYY", "{{.CanonicalTypeFamilyStr}}",
> ```

An artifact.
___
*[pkg/sql/colexec/execgen/cmd/execgen/vec_comparators_gen.go, line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49727#-M8Y0eqh9KW2g9Ut8zEV:-M8Y0eqh9KW2g9Ut8zEW:b-3kyvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ffdfe6a6b8f94ce40935f08c9c369edd419c0af/pkg/sql/colexec/execgen/cmd/execgen/vec_comparators_gen.go#L31)):*
> ```Go
> 	r := strings.NewReplacer(
> 		"_CANONICAL_TYPE_FAMILY", "{{.CanonicalTypeFamilyStr}}",
> 		"_TYPE_WIDTH", "{{.Width}}{{if eq .Width -1}}: default{{end}}",
> ```

nit: this could be `"_TYPE_WIDTH", typeWidthReplacement,`.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49727)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[pkg/col/coldata/vec_tmpl.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49727#-M8Xz-VLCC1OO5HK5s8G:-M8YRDL6EFWMD8vHI1Fy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b7502933254e34b4b4a4caac637d168a827f9f2/pkg/col/coldata/vec_tmpl.go#L38)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

This can also be removed I think (and in a few other templates where we have this line).
</blockquote></details>

Done.
___
*[pkg/sql/colexec/execgen/cmd/execgen/distinct_gen.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49727#-M8Y00Ie-lMYavRfYms7:-M8YRCjJAxxCeJ8Y_NFc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ffdfe6a6b8f94ce40935f08c9c369edd419c0af/pkg/sql/colexec/execgen/cmd/execgen/distinct_gen.go#L32)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

An artifact.
</blockquote></details>

Done.

**Pull request merged**
