### PR TITLE
kvserver: use crtime.NowMono in logstore and spanlatch

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### go.mod: bump crlib to latest

Epic: none
Release note: None

#### kvserver: replace nowNanos() with crtime.NowMono()

This is cleaner and more efficient (we only read the monotonic timer,
not the wall clock).

Informs: #133315
Release note: None

#### kvserver: use crtime.NowMono for raft ready stats

Informs: #133315
Release note: None

#### kvserver: use crtime.NowMono in logstore and spanlatch

Informs: #133315
Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133700#-:-OAORuSLE_s0e8U5ym-O:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @tbg)

___
*[`pkg/kv/kvserver/spanlatch/manager.go` line 574 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/133700#-OAORnEM2aslAc1Ru1JR:-OAORnEM2aslAc1Ru1JS:bvvwor) ([raw file](https://github.com/cockroachdb/cockroach/blob/29d1ffe418e02c766712e56c741119b583dca01a/pkg/kv/kvserver/spanlatch/manager.go#L574)):*
> ```Go
> 	wait, held *latch,
> ) error {
> 	tBegin := timeutil.Now()
> ```

Can we use `crtime.MonoTime` here as well?

**Comment by RaduBerinde** [comment]
*[`pkg/kv/kvserver/spanlatch/manager.go` line 574 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/133700#-OAORnEM2aslAc1Ru1JR:-OAOT0chA-tlOrtiDjcf:b-o3b9sa) ([raw file](https://github.com/cockroachdb/cockroach/blob/29d1ffe418e02c766712e56c741119b583dca01a/pkg/kv/kvserver/spanlatch/manager.go#L574)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we use `crtime.MonoTime` here as well?
</blockquote></details>

Ah, yes, thanks.

Is there a semi-decent chance the channel will already be signaled when we get here? We could do a non-blocking select as a fast path, before we even get the current time

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133700#-:-OAOXqL0-J9qw-JtLbaJ:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @tbg)

___
*[`pkg/kv/kvserver/spanlatch/manager.go` line 574 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/133700#-OAORnEM2aslAc1Ru1JR:-OAOXh3PBQ4zlz8c4apd:bmyjuvt) ([raw file](https://github.com/cockroachdb/cockroach/blob/29d1ffe418e02c766712e56c741119b583dca01a/pkg/kv/kvserver/spanlatch/manager.go#L574)):*
> Is there a semi-decent chance the channel will already be signaled when we get here? We could do a non-blocking select as a fast path, before we even get the current time

This is essentially what's already happening in `iterAndWait` with the call to `held.g.done.signaled()`.

**Comment by RaduBerinde** [comment]
*[`pkg/kv/kvserver/spanlatch/manager.go` line 574 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/133700#-OAORnEM2aslAc1Ru1JR:-OAOZ83b8PL94OjFRdm8:b-1ngpxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/29d1ffe418e02c766712e56c741119b583dca01a/pkg/kv/kvserver/spanlatch/manager.go#L574)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> Is there a semi-decent chance the channel will already be signaled when we get here? We could do a non-blocking select as a fast path, before we even get the current time

This is essentially what's already happening in `iterAndWait` with the call to `held.g.done.signaled()`.
</blockquote></details>

Ah, got it, thanks.

**Review by tbg — APPROVED** [review]

**Comment by RaduBerinde** [comment]
TFTRs!

bors r+

**Pull request merged**
