### PR TITLE
kv: bump ReplicaChecksumVersion, disable cross v23.2/v24.1 consistency checks

### LINKED ISSUE #117302: kv: replica inconsistency false positive in mixed-version cluster with global table
In https://github.com/cockroachdb/cockroach/pull/105523 (v23.2), we removed the logic to decode the synthetic timestamp bit from mvcc keys. Keys with synthetic timestamps set would be decoded as if their synthetic timestamp bit was not set. Under normal operation, this was safe, as this field is no longer consulted and is being phased out (#101938).

The idea was that this would not cause issues with mixed-version clusters (v23.1 + v23.2) because replica consistency checks operated at the encoded `EngineKey` level, so previously present synthetic timestamps would be included in replica consistency checksum even from v23.2 nodes.

However, in the process of completing the migration and adding more mixed-version testing (https://github.com/cockroachdb/cockroach/pull/117294), I am finding that this assumption is false. Replica consistency checks operate at the `MVCCKey` level, meaning that they decode each encoded pebble key into an MVCC key and then hash the timestamp component separately:
https://github.com/cockroachdb/cockroach/blob/797e65847747a2ed32b149de3dfa56496fdcb79a/pkg/kv/kvserver/replica_consistency.go#L559-L565

This is a problem. If a v23.2 node does not decode the synthetic timestamp bit and a v23.1 node does, then it will hash the timestamp component differently than a v23.1 node will, and the replica consistency check will fail. I can reproduce this with the following script:
```bash
roachprod create local -n3
roachprod stage local:1,2 release v23.1.11
roachprod stage local:3 release v23.2.0-rc.1
roachprod start local

roachprod sql local:1 -- -e "SET CLUSTER SETTING server.consistency_check.interval = '0'"
roachprod run local:1 -- cockroach workload init kv --splits=9
roachprod sql local:1 -- -e "ALTER TABLE kv.kv SCATTER"

# consistency check succeeds before table marked as global.
roachprod sql local:1 -- -e "SELECT * FROM crdb_internal.check_consistency(false, '', '') WHERE status NOT IN ('RANGE_CONSISTENT', 'RANGE_CONSISTENT_STATS_ESTIMATED')"

# consistency check fails after table marked as global and data written to table.
roachprod sql local:1 -- -e "ALTER TABLE kv.kv CONFIGURE ZONE USING global_reads = true"
roachprod run local:1 -- cockroach workload run kv --duration=10s
roachprod sql local:1 -- -e "SELECT * FROM crdb_internal.check_consistency(false, '', '') WHERE status NOT IN ('RANGE_CONSISTENT', 'RANGE_CONSISTENT_STATS_ESTIMATED')"
```

### Option 1

One mitigation is to revert most or all of https://github.com/cockroachdb/cockroach/pull/105523. We need to keep decoding synthetic timestamps in MVCC keys until the consistency checks stop consulting them.

To complete the migration, we'll then need to phase out synthetic timestamps in replica consistency checks more slowly. We'll add a version gate flag that gets plumbed down to `CalcReplicaDigest` and is used to selectively ignore synthetic timestamps.

### Option 2

Another mitigation is to bump the `ReplicaChecksumVersion` in v23.2, so that v23.1 and v23.2 nodes don't mix when performing consistency checks. This would be the safest fix and would also make the migration easy, but it would disable replica consistency checks between v23.1 and v23.2 nodes when in a mixed-version, which might be too much of a loss of coverage to justify.

Jira issue: CRDB-35111

### PR DESCRIPTION
**Pull request by nvb**
Informs #101938.
Fixes #117302.

This commit bumps the ReplicaChecksumVersion to disable replica consistency checks between v23.2 and v24.1 nodes when in a mixed-version cluster. This avoids the backwards incompatibility discussed in #117302.

While here and permitted to change the replica consistency check logic, we unset the Synthetic flag from RangeAppliedState.RaftClosedTimestamp during stats-only consistency checks. This form of consistency check is rarely used, but this prevents it from causing trouble with #101938.

While here and allowed to change the consistency check hash computation, we also switch from using the LegacyTimestamp encoding to the Timestamp encoding for the hash contribution of MVCCKeys.

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
@erikgrinaker @pav-kv I'd like to get your input on this option for resolving https://github.com/cockroachdb/cockroach/issues/117302. The benefit is that it's simple and it doesn't require a revert of https://github.com/cockroachdb/cockroach/pull/105523 [^1]. The downside is that it uses the `ReplicaChecksumVersion` mechanism to disallow cross v23.1/v23.2 consistency checks, so we'll lose some consistency check coverage in mixed-version clusters that are running multiple binary versions. I'm leaning towards this being the right approach because clusters aren't meant to hang around in this state for a long time (just during the rolling restart), so the simplicity argument would win out. Curious to get your thoughts.

In the meantime, I'll run this with https://github.com/cockroachdb/cockroach/pull/117294 for a few dozen iterations overnight to confirm that it resolves the inconsistency.

[^1]: this would push back https://github.com/cockroachdb/cockroach/issues/101938 by a major releases and make the eventual migration more involved. If we never wanted to bump `ReplicaChecksumVersion` then we'd need to add a targeted version gate to consistency check requests to determine whether v24.1 nodes should ignore the synthetic bit in mvcc keys or not. Only in v24.2 could we then remove the field from the proto.

**Comment by erikgrinaker** [comment]
This seems fine to me. It's why `ReplicaChecksumVersion` exists in the first place.

You've verified that we don't have any further dependencies on `Synthetic` here?

**Comment by pav-kv** [comment]
SGTM

**Comment by pav-kv** [comment]
Since we're bumping the version, do we want to do any drive-by changes/refactorings to the hash computation? For example, #117302 mentions we're using `ToLegacyTimestamp`. Can we untangle from something named "legacy"?

**Comment by nvanbenschoten** [comment]
@erikgrinaker and @pav-kv, I've updated this PR with your suggestions. Now that https://github.com/cockroachdb/cockroach/pull/117324 has landed and all of the synthetic timestamp migration will land in v24.1, https://github.com/cockroachdb/cockroach/issues/117302 is no longer an issue for v23.1/v23.2 mixed-version clusters, but it will still be an issue for the eventual v23.2/v24.1 state. This PR will avoid that, so I'm planning to land it just on master.

PTAL when you get a chance.

**Review by erikgrinaker — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117304#-:-NncaCIoEBsAUqPlI45k:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv)

**Pull request merged**
