### PR TITLE
flowinfra: fix a couple of rare bugs with flow cleanup

### LINKED ISSUE #94113: sql: investigate possible race condition on super overloaded node
I'm currently playing around with running `tpch_concurrency` on nodes with `GOMEMLIMIT` set. Occasionally, I see that there appears to be a stall in the test where a few flows on the gateway are stuck forever. In particular, the main goroutine of the local flow:
Screen Shot 2022-12-21 at 3 31 34 PM
is blocked waiting for the wait group to be done (after having canceled the pending inbound streams):
Screen Shot 2022-12-21 at 3 31 51 PM
I don't see any other execution goroutines, so my current hypothesis is that there is an issue around decrementing the wait group when the inbound streams time out when the node is extremely overloaded (or something like that).

Further investigation is needed, but it doesn't seem important enough at the moment.

Jira issue: CRDB-22698

### PR DESCRIPTION
**Pull request by yuzefovich**
**sql: minor cleanup around flow's wait group**

This commit makes minor adjustments so that `WaitGroup.Done` is called
closer (visibly) to where `Add` is. This aids when understanding
whether the wait group is cleaned up properly.

Release note: None

**flowinfra: fix a couple of rare bugs with flow cleanup**

This commit fixes a couple of rare bugs around the flow cleanup that
were encountered when running `tpch_concurrency` roachtest at the
concurrency of 1000 or so (i.e. for the bugs to reproduce we needed
extremely overloaded nodes).

The setup for the bugs is as follows:
- we have some number of inbound streams on the node. The inbound
streams in this context are the server side of the `FlowStream` RPCs
(i.e. the inbox side)
- each inbound stream needs a separate goroutine (created by the gRPC
framework), and these goroutines are tracked against the wait group of
the flow
- the main goroutine of the flow registers the flow with the
`FlowRegistry` and gives it a timeout (10 seconds by default) to let the
inbound streams to arrive
- we have synchronization in place to block the inbound streams until
the flow is registered
- once the inbound stream finds its flow in the registry, it sends
a handshake RPC to the producer (i.e. to the outbox).

The first bug is about not decrementing the wait group of the flow in
some cases. In particular, if the inbound stream timeout occurs _while_
the inbound stream is performing the "handshake" RPC _and_ that RPC
results in an error, then the wait group wouldn't be decremented. This
was the case because
1. the "timeout" goroutine would observe that the stream is "connected",
so it would treat the timeout cancellation as a no-op
2. the inbound stream goroutine would get an error on the handshake, so
it would bubble the error up but would never call
`InboundStreamInfo.onFinish`.

This bug is now fixed by only marking the stream as "connected" once the
handshake succeeds. This bug was introduced about a year ago in https://github.com/cockroachdb/cockroach/commit/62ea0c622c22810b590616b38300dd39de708221
when we refactored the locking around the flow registry.

The second bug is related. Previously, if `ConnectInboundStream`
resulted in an error, this could leave one of the inbox goroutines
blocked forever in `Inbox.Init`. In particular, the inbox waits until
of the following occurs:
- the stream arrives and successfully performs the handshake
- the inbound stream timeout occurs
- the flow context is canceled
- the inbox context is canceled.

In the scenario from the first bug, the first point wasn't true because
the handshake resulted in an error. The second point wasn't true because
the stream was marked as "connected" so it was skipped when
`flowEntry.streamTimer` fired (meaning that
`InboundStreamHandler.Timeout` wasn't called). The contexts weren't
explicitly canceled either (the incorrect assumption was that the flow
context would be canceled by the outboxes on the node, but we might have
plans where the gateway flow doesn't have any outboxes).

This second bug is now fixed by explicitly cancelling the flow whenever
inbound stream connection results in an error. The additional
nice-to-have improvement was made to the outboxes to cancel the flow
context on their nodes whenever the `FlowStream` RPC fails - the query
is doomed, so we might as well cancel the flow sooner.

I decided to not include a release note here since I believe the
prerequisite for these bugs to occur is that the inbound streams time out
exactly while performing the handshake RPC. 10 seconds default value for
the timeout makes it extremely unlikely to happen, and the only way we
ran into this was by severely overloading the nodes (and the user would
have bigger problems at that point than these deadlocks).

Fixes: #94113.

Release note: None

**roachtest: increase bounds for tpch_concurrency**

This commit adjusts the bounds for `tpch_concurrency` roachtest. Given
that we now set GOMEMLIMIT by default, we can sustain much higher
concurrency without falling over. I ran the test manually with
`[128, 1024)` range and got 972.938 on average (I had 20 runs of which
4 timed out). To prevent the timeouts this commit uses a small interval
(less than 64 in length) so that we make 6 iterations in the binary
search. As a result, the new search range is [970, 1030).

Additionally, it was observed that Q15 (which performs two schema
changes) can take non-trivial amount of time, so it is skipped from
this test. This commit also makes a minor improvement to fail the test
if all iterations resulted in a node crash.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I know that @cucaroach and @msirek you don't have that much experience with this part of the codebase, but I doubt we have anyone who has.

@nvanbenschoten I wonder whether you'd be up for reviewing the second commit given that it fixes a bug that was introduced in #72998 (for which you were the main reviewer). No worries if not.

**Comment by msirek** [comment]
> I know that @cucaroach and @msirek you don't have that much experience with this part of the codebase, but I doubt we have anyone who has.

Thanks, I don't mind learning new parts of the code. I may not get to reviewing this until tomorrow afternoon, so hopefully this isn't a critical fix.

**Comment by yuzefovich** [comment]
Sounds good, thanks!

**Comment by cucaroach** [comment]
That tpch_concurrency test is so good at finding bugs I wonder if we should distill it into a go unit test so it can easily be run with race/stress so this code gets more sunshine.

**Review by cucaroach — APPROVED** [review]
:lgtm: 

I still don't completely grok all the inbox/outbox grpc layering here but its getting more familiar.  I still feel like a bug that manifests only in roachtest could be viewed as a containment breach and we should think about how to do similar testing in a unit test.   Maybe like your test fixture that adds blocking we should think about ways to inject sleeps into this subsystem under crdb_test control to simulate slow nodes.

> Reviewed 4 of 4 files at r1, 3 of 4 files at r2, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98428#-:-NQXmHOl43vuGKqmScWF:b9ixc7z)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek and @yuzefovich)

___
*[`pkg/sql/colexec/parallel_unordered_synchronizer.go` line 220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98428#-NQZt9Zg-zblLtdT-O4U:-NQZt9Zg-zblLtdT-O4V:b-2n8gid) ([raw file](https://github.com/cockroachdb/cockroach/blob/afc46e4362c7163387ce496a8227aadb128f6318/pkg/sql/colexec/parallel_unordered_synchronizer.go#L220)):*
> ```Go
> 		// goroutines just sitting around waiting for cancellation. I wonder if we
> 		// could reuse those goroutines to push batches to batchCh directly.
> 		go func(input colexecargs.OpWithMetaInfo, inputIdx int) {
> ```

Is this an example of where we should be using stopper instead of raw go?   Just curious.
___
*[`pkg/sql/colexec/parallel_unordered_synchronizer.go` line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98428#-NQZtcgt0vnJSQPeUI5l:-NQZtcgt0vnJSQPeUI5m:b5xy8lk) ([raw file](https://github.com/cockroachdb/cockroach/blob/afc46e4362c7163387ce496a8227aadb128f6318/pkg/sql/colexec/parallel_unordered_synchronizer.go#L224)):*
> ```Go
> 			defer func() {
> 				defer s.externalWaitGroup.Done()
> 				defer s.internalWaitGroup.Done()
> ```

The nested defer seems like overkill, are any of these defer's except the first one really necessary?

**Review by yuzefovich — COMMENTED** [review]
> That tpch_concurrency test is so good at finding bugs I wonder if we should distill it into a go unit test so it can easily be run with race/stress so this code gets more sunshine.

I think it will be quite annoying to try to do it as a unit test. The main difficulty is that `tpch_concurrency` pushes the nodes so hard, CPUs are maxed out many times over. If we were to do it as a unit test, it would need to be run separately from all other unit tests in order to not affect others. Instead, I think a better investment would be to make `tpch_concurrency` smarter - currently, if a node dies, we don't examine the cause. If it died due to OOM, this is (somewhat) expected and probably not worth looking into, but if it crashed for other reason, it'd be interesting to fail the test and collect the debug.zip. The deadlocks are surfaced as timeouts, so this is the only failure mode that we're getting the signal about, and that's how the deadlocks fixed in this PR were exposed.

> Maybe like your test fixture that adds blocking we should think about ways to inject sleeps into this subsystem under crdb_test control to simulate slow nodes.

This idea sounds interesting. `crdb_test` might be too coarse for this since we'll get too many "expected failures" that we would need to teach the unit tests about. Perhaps we could reuse the roachtest framework (or implement a new one) where each roachtest run is duplicated (maybe on the weekly basis) to have a "shadow" run that uses the binary with these injected sleeps, and we'd collect deadlocks / failures to analyze.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98428#-:-NQaqGjH0nzotpHDdIkG:btj0wn5)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @msirek)

___
*[`pkg/sql/colexec/parallel_unordered_synchronizer.go` line 220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98428#-NQZt9Zg-zblLtdT-O4U:-NQatFmi0HwnF5JCgl1_:bmw02m5) ([raw file](https://github.com/cockroachdb/cockroach/blob/afc46e4362c7163387ce496a8227aadb128f6318/pkg/sql/colexec/parallel_unordered_synchronizer.go#L220)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Is this an example of where we should be using stopper instead of raw go?   Just curious.
</blockquote></details>

Yes, it's one of those.
___
*[`pkg/sql/colexec/parallel_unordered_synchronizer.go` line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98428#-NQZtcgt0vnJSQPeUI5l:-NQau6GM6l--OOhTEG2P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/afc46e4362c7163387ce496a8227aadb128f6318/pkg/sql/colexec/parallel_unordered_synchronizer.go#L224)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

The nested defer seems like overkill, are any of these defer's except the first one really necessary?
</blockquote></details>

Done.

**Review by msirek — APPROVED** [review]
Looks good. Just a couple minor comments.

> Reviewed 1 of 6 files at r6, 4 of 4 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98428#-:-NQb513m0nM0DWejvKgs:bm0lr6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @yuzefovich)

___
*[`pkg/sql/flowinfra/flow_registry.go` line 619 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/98428#-NQb05ke5M-dnXIZehsl:-NQb05ke5M-dnXIZehsm:b77vgwb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b561a1175615c3ed355a45b4d2f048c984cb65b1/pkg/sql/flowinfra/flow_registry.go#L619)):*
> ```Go
> 		return nil, nil, nil, handshakeErr
> 	}
> 	s.mu.connected = true
> ```

Should this code have been moved here, so we error out if `connected` is already set?
```
	if s.mu.connected {
		return errors.Errorf("flow %s: inbound stream %d already connected", flowID, streamID)
	}

```



_Code quote:_
```Go
	if s.mu.connected {
		return errors.Errorf("flow %s: inbound stream %d already connected", flowID, streamID)
	}
```
___
*[`pkg/sql/flowinfra/outbox.go` line 265 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/98428#-NQb1_kn2N9Fht-sAK1e:-NQb1_kn2N9Fht-sAK1f:b-10f46e) ([raw file](https://github.com/cockroachdb/cockroach/blob/b561a1175615c3ed355a45b4d2f048c984cb65b1/pkg/sql/flowinfra/outbox.go#L265)):*
> ```Go
> 	}(); err != nil {
> 		// An error during stream setup - the whole query will fail, so we might
> 		// as well proactively cancel the flow on this node.
> ```

Is there a reason to limit this to stream setup failures? Couldn't any error case benefit from early cancellation of the context (maybe add a defer function to check `retErr`).
___
*[`pkg/sql/flowinfra/outbox.go` line 416 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/98428#-NQb2CkiEic49lKWUJfG:-NQb2CkiEic49lKWUJfH:b45h) ([raw file](https://github.com/cockroachdb/cockroach/blob/b561a1175615c3ed355a45b4d2f048c984cb65b1/pkg/sql/flowinfra/outbox.go#L416)):*
> ```Go
> 		close(ch)
> 	}); err != nil {
> 		wg.Done()
> ```

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98428)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @msirek)

___
*[`pkg/sql/flowinfra/flow_registry.go` line 619 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/98428#-NQb05ke5M-dnXIZehsl:-NQb7PusCUniDXmLMNGN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b561a1175615c3ed355a45b4d2f048c984cb65b1/pkg/sql/flowinfra/flow_registry.go#L619)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Should this code have been moved here, so we error out if `connected` is already set?
```
	if s.mu.connected {
		return errors.Errorf("flow %s: inbound stream %d already connected", flowID, streamID)
	}

```
</blockquote></details>

Done.
___
*[`pkg/sql/flowinfra/outbox.go` line 265 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/98428#-NQb1_kn2N9Fht-sAK1e:-NQb7i-rAK-M6DEhKajd:b-8ta7jn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b561a1175615c3ed355a45b4d2f048c984cb65b1/pkg/sql/flowinfra/outbox.go#L265)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Is there a reason to limit this to stream setup failures? Couldn't any error case benefit from early cancellation of the context (maybe add a defer function to check `retErr`).
</blockquote></details>

We already have the logic to examine the error and cancel the flow context for some types of errors (when we know that the distributed query will fail). This is done in `HandleStreamErr`.

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98428)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @yuzefovich)

___
*[`pkg/sql/flowinfra/outbox.go` line 265 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/98428#-NQb1_kn2N9Fht-sAK1e:-NQb8ts4-2U1h_TzqkzE:b-hfk55u) ([raw file](https://github.com/cockroachdb/cockroach/blob/b561a1175615c3ed355a45b4d2f048c984cb65b1/pkg/sql/flowinfra/outbox.go#L265)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

We already have the logic to examine the error and cancel the flow context for some types of errors (when we know that the distributed query will fail). This is done in `HandleStreamErr`.
</blockquote></details>

OK, thanks

**Comment by yuzefovich** [comment]
I got 20 runs of `tpch_concurrency` with no timeouts (the longest took less than 15 hours), and the average supported concurrency was `1014.9`.

TFTRs!

bors r+

**Comment by yuzefovich** [comment]
I'm confused - the run that you linked don't seem to have timed out AFAICT: `tpch_concurrency/run_1` run in 6:00-19:57 and `tpch_concurrency/no_streamer/run_1` in 6:00-16:01. It should be unlikely for this test to take longer than 15 hours, so it shouldn't be an issue with 21 hour timeout enforced by the CI.

If it does happen, is the whole nightly run is marked as failed? I.e. I'm wondering whether the time out of a single roachtest is worse than a failure of that same roachtest.

To answer your questions more directly: for now I'd really like to run this on a nightly basis, but eventually we might move it to weekly.

**Comment by renatolabs** [comment]
> It should be unlikely for this test to take longer than 15 hours

The issue is not only that _this test_ may timeout (although that's an issue too if the test kicks off in the 8th hour of the run for example), but also that it may delay the start of other tests, not giving them a chance to run. The build I linked above timed out (the build itself, not a particular test).

> If it does happen, is the whole nightly run marked as failed?

Yes, the run is marked as failed. Tests that did get a chance to run and failed are reported as usual; the main drawback of many long-running tests such as this one is that some tests may not get to run, and we get less coverage/value from them.

**Comment by yuzefovich** [comment]
> The issue is not only that _this_ test may timeout (although that's an issue too if the test kicks off in the 8th hour of the run for example), but also that it may delay the start of other tests, not giving them a chance to run. The build I linked above timed out (the build itself, not a particular test).

Can you expand on this? Are we limiting the number of concurrent roachtests or something?

**Comment by renatolabs** [comment]
Yes, there is a limit on the number of concurrent roachtests dictated by the `cpuQuota` [1] allocated to the run.

[1] https://github.com/cockroachdb/cockroach/blob/679d8e75022c7a53c96243981a10e8a79e4f145d/pkg/cmd/roachtest/test_runner.go#L157-L161

**Comment by yuzefovich** [comment]
Ok, thanks. I'm a bit surprised that this particular roachtest would suddenly become the bottleneck - it uses four 4vCPU machines with two test types, so it'll use 32 CPUs total. Up until this PR was merged, the test used the same hardware and would take on the order of 8 hours (instead of current up to 15 hours). So this PR did increase cpu-hour usage of the test, but still I'm surprised that it has noticeable impact on the overall nightly roachtest run. For now, I'll remove one of the two variants of this roachtest effectively reverting to the previous cpu-hour usage.

**Comment by renatolabs** [comment]
I was looking at other nightly failures, and there are at least two other tests that _didn't_ specify a `Timeout` in their spec (defaulting to 10h) that hung. That would also waste CPU usage and could lead to this.

I would actually suggest doing nothing at the moment; I'll keep an eye on the other issues to make sure a tighter timeout is specified and if we stop seeing these issues, we can leave this test alone (otherwise I'll comment on this thread again) 👍

**Pull request merged**
