### PR TITLE
caller: modernize Lookup

### PR DESCRIPTION
**Pull request by tbg**
When we use verbose tracing, we spend lots of time in `log.Event{,f}`
and optimizing `caller.Lookup` can matter. The old code was also ripe
for some cleanup.

```
$ benchstat old.txt new.txt 
name            old time/op    new time/op    delta
SimpleCaller-8     764ns ± 3%     504ns ± 4%   -33.98%  (p=0.008 n=5+5)

name            old alloc/op   new alloc/op   delta
SimpleCaller-8      216B ± 0%        0B       -100.00%  (p=0.008 n=5+5)

name            old allocs/op  new allocs/op  delta
SimpleCaller-8      2.00 ± 0%      0.00       -100.00%  (p=0.008 n=5+5)
```

Extracted from #71610.

Release note: None

### CODE REVIEW

**Review by stevendanna — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71693)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @stevendanna and @tbg)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71693#-MmMxZefCNz1rkZWdReu:-MmMxZefCNz1rkZWdRev:b-8mhwdm) (no related file):*
:lgtm: Cool.

---
___
*[pkg/util/caller/resolver.go, line 217 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71693#-MmMtJpH-mXooglePH3i:-MmMtJpH-mXooglePH3j:b-8nwztr) ([raw file](https://github.com/cockroachdb/cockroach/blob/716d2f24b53ffb145b62b4dcf9b276bacbb87081/pkg/util/caller/resolver.go#L217)):*
> ```Go
> // requested depth.
> func (cr *CallResolver) Lookup(depth int) (_file string, _line int, _fun string) {
> 	sl := uintptrSlPool.Get().([]uintptr)
> ```

Not recommending a change, but curiosity got the better of me about whether pooling this is worth it. Removing the pool on go1.16.5 locally seems to be a minor win, but my guess is that would reverse if the `[]uintptr` started to escape to the heap.  Anyway, just thought I would share:

```
name             old time/op    new time/op    delta
SimpleCaller-16     593ns ± 9%     533ns ±12%  -10.19%  (p=0.000 n=24+24)

name             old alloc/op   new alloc/op   delta
SimpleCaller-16      104B ± 0%       80B ± 0%  -23.08%  (p=0.000 n=25+25)

name             old allocs/op  new allocs/op  delta
SimpleCaller-16      3.00 ± 0%      2.00 ± 0%  -33.33%  (p=0.000 n=25+25)
```

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71693)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @stevendanna and @tbg)

___
*[pkg/util/caller/resolver.go, line 217 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71693#-MmMtJpH-mXooglePH3i:-MmMyKpu22ZOxCgqx2vx:b-5fkaa1) ([raw file](https://github.com/cockroachdb/cockroach/blob/716d2f24b53ffb145b62b4dcf9b276bacbb87081/pkg/util/caller/resolver.go#L217)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Not a change, but curiosity got the better of me about whether this pooling this is worth it. Removing the pool on go1.16.5 locally seems to be a minor win, but my guess is that would reverse if the `[]uintptr` started to escape escape to the heap.  Anyway, just thought I would share:

```
name             old time/op    new time/op    delta
SimpleCaller-16     593ns ± 9%     533ns ±12%  -10.19%  (p=0.000 n=24+24)

name             old alloc/op   new alloc/op   delta
SimpleCaller-16      104B ± 0%       80B ± 0%  -23.08%  (p=0.000 n=25+25)

name             old allocs/op  new allocs/op  delta
SimpleCaller-16      3.00 ± 0%      2.00 ± 0%  -33.33%  (p=0.000 n=25+25)
```
</blockquote></details>

:D I wish reviewable reflected my typo-fix edits. But alas, it does not.

**Review by stevendanna — COMMENTED** [review]
Aha! Completely missed that. Indeed now the pool is a little faster for me:

```
> benchstat old.txt new.txt 
name             old time/op    new time/op    delta
SimpleCaller-16     401ns ±31%     446ns ±23%  +11.40%  (p=0.011 n=24+24)

name             old alloc/op   new alloc/op   delta
SimpleCaller-16     0.00B          0.00B          ~     (all equal)

name             old allocs/op  new allocs/op  delta
SimpleCaller-16      0.00           0.00          ~     (all equal)
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71693#-:-MmNBkXw2uDkfZJcsyDc:b-t7vr4l)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @stevendanna and @tbg)

**Review by stevendanna — COMMENTED** [review]
(new there is removing the pool)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71693#-:-MmNCH_75h1AhMjZdxC3:b-p4zusq)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @stevendanna and @tbg)

**Comment by tbg** [comment]
flake in sql pkg

bors r=stevendanna

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71693)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis, @stevendanna, and @tbg)

___
*[pkg/util/caller/resolver.go, line 228 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71693#-MmNX2xf-K1C3FGXDBWY:-MmNX2xf-K1C3FGXDBWZ:b-q6dn6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e50ef7f31047559cb9e7f727e8e3f737697aed8/pkg/util/caller/resolver.go#L228)):*
> ```Go
> 	}
> 
> 	cr.mu.Lock()
> ```

Would it make sense to change `CallResolver.mu` to be a `RWLock` and then do the fast-path lookup only holding a read lock? I think we expect most lookups to be cached, but right now they serialize on the lock.

**Pull request merged**
