### PR TITLE
sql: add doctor check for parent schema in parent db

### LINKED ISSUE #55716: doctor: ensure that parentSchemaID is in parentID
**Is your feature request related to a problem? Please describe.**

This is a handy check for the doctor to perform. See https://github.com/cockroachdb/cockroach/issues/55710#issuecomment-712448905.

### PR DESCRIPTION
**Pull request by postamar**
With this patch, doctor now also checks that the parent id of an object
matches the parent id of the parent schema of the object.

Fixes #55716.

Release note: None

### CODE REVIEW

**Comment by postamar** [comment]
For good measure I checked out the commit prior to the merge commit https://github.com/cockroachdb/cockroach/pull/55723, cherry-picked this commit, successfully reproduced the problem in the issue and checked that `doctor` ran the new check correctly:
```
Examining 36 descriptors and 40 namespace entries...
   Table  55: ParentID  52, ParentSchemaID 54, Name 'bar': invalid parent schema parent id 50
Examining 0 running jobs...
ERROR: validation failed
Failed running "debug doctor cluster"
```

**Comment by postamar** [comment]
CI failed on what appears to be a flaky test, which already has an issue open: https://github.com/cockroachdb/cockroach/issues/58624 . I don't believe the failure is related to my changes.

**Review by ajwerner — COMMENTED** [review]
Thanks for picking this up 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58875#-:-MR0Xqmy0MQhW4s_Lvv4:b-lfqqfp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[pkg/sql/doctor/doctor.go, line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58875#-MR0XY_c5-LS8RyTamyk:-MR0XY_c5-LS8RyTamyl:bafa2k9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bbd2a3aa32ca15f6d0e67f7cec7c9893cba4593/pkg/sql/doctor/doctor.go#L177)):*
> ```Go
> 			} else if !invalidParentID && parentSchema.GetParentID() != desc.GetParentID() {
> 				problemsFound = true
> 				fmt.Fprint(stdout, reportMsg(desc, "invalid parent schema parent id %d", parentSchema.GetParentID()))
> ```

I think this message can be clearer and can have a test. Namely, it'd be interesting to know both parent id values.

**Review by postamar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58875)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/doctor/doctor.go, line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58875#-MR0XY_c5-LS8RyTamyk:-MR0cLM_DsV2kEy1Cngs:b-jppdsm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bbd2a3aa32ca15f6d0e67f7cec7c9893cba4593/pkg/sql/doctor/doctor.go#L177)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think this message can be clearer and can have a test. Namely, it'd be interesting to know both parent id values. 
</blockquote></details>

Perhaps I'm misunderstanding but it is tested and the other parent id values already get reported in the prefix of the error message. See the test case I added for an example of this.

**Review by postamar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58875)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/doctor/doctor.go, line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58875#-MR0XY_c5-LS8RyTamyk:-MR0j87m7MVtI87sCPgV:bjdup47) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bbd2a3aa32ca15f6d0e67f7cec7c9893cba4593/pkg/sql/doctor/doctor.go#L177)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Perhaps I'm misunderstanding but it is tested and the other parent id values already get reported in the prefix of the error message. See the test case I added for an example of this.
</blockquote></details>

I changed the message to something that should be less confusing.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58875)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/doctor/doctor.go, line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58875#-MR0pPa69sBTcR4yhcce:-MR0pPa69sBTcR4yhccf:b-c74zs3) ([raw file](https://github.com/cockroachdb/cockroach/blob/af9d6fb8621f0222e22de5aaafc4014d545633cb/pkg/sql/doctor/doctor.go#L174)):*
> ```Go
> 			if !parentSchemaExists {
> 				problemsFound = true
> 				fmt.Fprint(stdout, reportMsg(desc, "invalid parent schema id %d", desc.GetParentSchemaID()))
> ```

err, then this case is not tested then, right?

**Review by postamar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58875)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/doctor/doctor.go, line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58875#-MR0pPa69sBTcR4yhcce:-MR0qEef0PvRO1Kolkw0:b-t3k9bl) ([raw file](https://github.com/cockroachdb/cockroach/blob/af9d6fb8621f0222e22de5aaafc4014d545633cb/pkg/sql/doctor/doctor.go#L174)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

err, then this case is not tested then, right?
</blockquote></details>

This case was already there and only shows up in the diff because I broke down the `if` clause into an if-else statement, so I didn't check if it was covered. I'll add a test for good measure.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58875#-:-MR0qsUG5z4DfRx0ZGZC:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)

___
*[pkg/sql/doctor/doctor.go, line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58875#-MR0pPa69sBTcR4yhcce:-MR0qqOi-5lrfLiBg7DV:b-kdqcoi) ([raw file](https://github.com/cockroachdb/cockroach/blob/af9d6fb8621f0222e22de5aaafc4014d545633cb/pkg/sql/doctor/doctor.go#L174)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

This case was already there and only shows up in the diff because I broke down the `if` clause into an if-else statement, so I didn't check if it was covered. I'll add a test for good measure.
</blockquote></details>

gotcha, thanks

**Comment by postamar** [comment]
bors r+

Flaky test fix has been merged, trying again.

**Pull request merged**
