### PR TITLE
storage: add replica log tag to queue context

### PR DESCRIPTION
**Pull request by petermattis**
Add the replica log tag to the context passed to queue.process. Fixed up
a bunch of log messages in the process to removing the resulting
redundant information.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9223)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/queue.go, line 480 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9223#-KRAa55y_jp-H21XwPmS:-KRAa55y_jp-H21XwPmT:b-wo5kvz) ([raw file](https://github.com/cockroachdb/cockroach/blob/49c404efa4714cfd196fe297c75cc629123bb224/storage/queue.go#L480)):*
> ```Go
> 	sp := repl.store.Tracer().StartSpan(bq.name)
> 	ctx := opentracing.ContextWithSpan(context.Background(), sp)
> 	ctx = repl.withLogTag(ctx)
> ```

should we name the method to `logContext` for consistency with the method on `Store`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9223#-:-KRAd2_9_myf9vvSh8dh:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/replica.go, line 534 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9223#-KRAl1abesUGd4Dd6YBc:-KRAl1abesUGd4Dd6YBd:bn000i2) ([raw file](https://github.com/cockroachdb/cockroach/blob/49c404efa4714cfd196fe297c75cc629123bb224/storage/replica.go#L534)):*
> ```Go
> 
> func (r *Replica) withLogTag(ctx context.Context) context.Context {
> 	return log.WithLogTag(ctx, "r", &r.rangeDesc)
> ```

Do we expect `ctx` to already have node, store tags? If not, we should use `log.WithLogTagsFromCtx(ctx, r.ctx)` to automatically copy the log tags that this particular layer doesn't manage.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9223)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/replica.go, line 534 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9223#-KRAl1abesUGd4Dd6YBc:-KRAlpkkaWrHUvFZhLDN:bj61kk6) ([raw file](https://github.com/cockroachdb/cockroach/blob/49c404efa4714cfd196fe297c75cc629123bb224/storage/replica.go#L534)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Do we expect `ctx` to already have node, store tags? If not, we should use `log.WithLogTagsFromCtx(ctx, r.ctx)` to automatically copy the log tags that this particular layer doesn't manage.
</details>
Ah, the use we are adding is based off of Background, so we should definitely do that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9223)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/replica.go, line 534 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9223#-KRAl1abesUGd4Dd6YBc:-KRAm-YTWPg5KSFQQtex:b-nw96c3) ([raw file](https://github.com/cockroachdb/cockroach/blob/49c404efa4714cfd196fe297c75cc629123bb224/storage/replica.go#L534)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Ah, the use we are adding is based off of Background, so we should definitely do that.
</details>
We should probably not be calling that directly - instead, each layer could call the relevant methods for the layer above. In this case, we'd want something like

```
return log.WithLogTag(r.store.logContext(ctx), "r", &r.rangeDesc))
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9223)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/replica.go, line 534 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9223#-KRAl1abesUGd4Dd6YBc:-KRAmSfUPlIUYJrbxw5a:b-exj3ha) ([raw file](https://github.com/cockroachdb/cockroach/blob/49c404efa4714cfd196fe297c75cc629123bb224/storage/replica.go#L534)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> We should probably not be calling that directly - instead, each layer could call the relevant methods for the layer above. In this case, we'd want something like
> 
> ```
> return log.WithLogTag(r.store.logContext(ctx), "r", &r.rangeDesc))
> ```
</details>
No. That is a bad design IMO. The method was designed specifically for this. It's not normal for lower layers to have to have direct references to higher layers. E.g. in tests, we may not have a server, just a store. Or the server itself might be getting tags from a higher level (e.g. I could imagine adding a "test cluster id" tag in some cases). The whole point is for each layer to be passed the context of whatever higher layers are above it, no matter how many there are.

If you have a problem with the way I designed the log tags infrastructure, we can discuss it, and I have no problem changing the implementation if you have better ideas. But I wish you would stop the one-off "we should probably do this one particular thing some other way (without explanation as to why that is better, or consideration on how it fits the whole picture)" bike shedding that has been happening lately around this stuff.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9223)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/replica.go, line 534 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9223#-KRAl1abesUGd4Dd6YBc:-KRArKHsIzgtjzr7yZ3w:b317s1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/49c404efa4714cfd196fe297c75cc629123bb224/storage/replica.go#L534)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> No. That is a bad design IMO. The method was designed specifically for this. It's not normal for lower layers to have to have direct references to higher layers. E.g. in tests, we may not have a server, just a store. Or the server itself might be getting tags from a higher level (e.g. I could imagine adding a "test cluster id" tag in some cases). The whole point is for each layer to be passed the context of whatever higher layers are above it, no matter how many there are.
> 
> If you have a problem with the way I designed the log tags infrastructure, we can discuss it, and I have no problem changing the implementation if you have better ideas. But I wish you would stop the one-off "we should probably do this one particular thing some other way (without explanation as to why that is better, or consideration on how it fits the whole picture)" bike shedding that has been happening lately around this stuff.
</details>
I misread your suggestion. If the range's context already includes the store's tags, then we're in agreement.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9223)*

**Comment by petermattis** [comment]
Changed so that `Replica.logContext` mirrors `Store.logContext`. Reviewable is currently broken (for me) so I can't respond there. PTAL.

**Comment by RaduBerinde** [comment]
Looks great, thanks!

**Pull request merged**
