### PR TITLE
jobs: remove very old logic around detecting orphaned schemachange jobs

### PR DESCRIPTION
**Pull request by ajwerner**
This code was to deal with the very old world when there was no job for
schema changes. This is all part of an effort to hide the catalogkv
interface.

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
@dt I'm tagging you here because you're one of the few around who remembers why this code was here in the first place.

**Review by dt — APPROVED** [review]

**Comment by ajwerner** [comment]
TFTR!

bors r=dt

**Comment by yuzefovich** [comment]
I think there is a merge skew with bazel dependencies with this PR. Needs a rebase.

bors r-

**Pull request merged**
