### PR TITLE
opt: add support for EXPLAIN (DISTSQL)

### PR DESCRIPTION
**Pull request by RaduBerinde**
Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/sql/opt/optbuilder/explain.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26135#-LDbvaNO5aVQj65lK8x_:-LDbvaNP9nEQBIH_rZWm:busnvkp) ([raw file](https://github.com/cockroachdb/cockroach/blob/88f53e8e065a095d17a94dca3558adc14d6d6a7e/pkg/sql/opt/optbuilder/explain.go#L50)):*
> ```Go
> 
> 	default:
> 		panic(errorf("unsupported EXPLAIN mode"))
> ```

Can you print out the unsupported mode that was requested?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26135#-:-LDbvvLm5Nh0qLhu8gSv:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/opt/optbuilder/explain.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26135#-LDbvaNO5aVQj65lK8x_:-LDc2kTJETlhADLaSFo1:b-8gki8f) ([raw file](https://github.com/cockroachdb/cockroach/blob/88f53e8e065a095d17a94dca3558adc14d6d6a7e/pkg/sql/opt/optbuilder/explain.go#L50)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Can you print out the unsupported mode that was requested?
</blockquote></details>

There is no stringification function for the mode, I don't know how useful printing a cryptic number is. The mode should be obvious from the query.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26135)*

**Comment by rytaft** [comment]
*[pkg/sql/opt/optbuilder/explain.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26135#-LDbvaNO5aVQj65lK8x_:-LDcILkEA31ULxbwQPlE:b2ni9b4) ([raw file](https://github.com/cockroachdb/cockroach/blob/88f53e8e065a095d17a94dca3558adc14d6d6a7e/pkg/sql/opt/optbuilder/explain.go#L50)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

There is no stringification function for the mode, I don't know how useful printing a cryptic number is. The mode should be obvious from the query.
</blockquote></details>

ok!

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26135)*

**Pull request merged**
