### PR TITLE
changefeedccl: Fix a deadlock when closing blocking buffer.

### LINKED ISSUE #71364: changefeedccl: potential deadlock in `blockingBuffer`
`blockingBuffer` triggers the deadlock detector in the tests `TestBlockingBuffer` and `TestBlockingBufferNotifiesConsumerWhenOutOfMemory`. Seems legit.

With #71346, remove the `skip.UnderDeadlock` calls from the tests and run:

```
$ make testdeadlock PKG=./pkg/ccl/changefeedccl/kvevent TESTS='^TestBlockingBuffer$'
=== RUN   TestBlockingBuffer
    test_log_scope.go:79: test logs captured to: /tmp/logTestBlockingBuffer985122245
    test_log_scope.go:80: use -show-logs to present logs inline
POTENTIAL DEADLOCK: Inconsistent locking. saw this ordering in one goroutine:
happened before
../../../util/quotapool/quotapool.go:319 quotapool.(*AbstractPool).acquireFastPath { qp.mu.Lock() } <<<<<
../../../util/quotapool/quotapool.go:214 quotapool.(*AbstractPool).Acquire { fulfilled, n, tryAgainAfter, err := qp.acquireFastPath(ctx, r) }
blocking_buffer.go:198 kvevent.(*blockingBuffer).Add { if err := b.qp.Acquire(ctx, be); err != nil { }
blocking_buffer_test.go:96 kvevent_test.TestBlockingBuffer.func4 { err := buf.Add(ctx, kvevent.MakeKVEvent(makeKV(t, rnd), roachpb.Value{}, hlc.Timestamp{})) }
../../../util/ctxgroup/ctxgroup.go:166 ctxgroup.Group.GoCtx.func1 { return f(g.ctx) }
../../../../vendor/golang.org/x/sync/errgroup/errgroup.go:57 errgroup.(*Group).Go.func1 { if err := f(); err != nil { }

happened after
blocking_buffer.go:107 kvevent.(*blockingBuffer).notifyOutOfQuota { b.mu.Lock() } <<<<<
blocking_buffer.go:339 kvevent.(*bufferEntry).Acquire { quota.notifyOutOfQuota() }
../../../util/quotapool/quotapool.go:325 quotapool.(*AbstractPool).acquireFastPath { if fulfilled, tryAgainAfter = r.Acquire(ctx, qp.mu.quota); fulfilled { }
../../../util/quotapool/quotapool.go:214 quotapool.(*AbstractPool).Acquire { fulfilled, n, tryAgainAfter, err := qp.acquireFastPath(ctx, r) }
blocking_buffer.go:198 kvevent.(*blockingBuffer).Add { if err := b.qp.Acquire(ctx, be); err != nil { }
blocking_buffer_test.go:96 kvevent_test.TestBlockingBuffer.func4 { err := buf.Add(ctx, kvevent.MakeKVEvent(makeKV(t, rnd), roachpb.Value{}, hlc.Timestamp{})) }
../../../util/ctxgroup/ctxgroup.go:166 ctxgroup.Group.GoCtx.func1 { return f(g.ctx) }
../../../../vendor/golang.org/x/sync/errgroup/errgroup.go:57 errgroup.(*Group).Go.func1 { if err := f(); err != nil { }

in another goroutine: happened before
blocking_buffer.go:235 kvevent.(*blockingBuffer).Close { b.mu.Lock() } <<<<<
blocking_buffer_test.go:83 kvevent_test.TestBlockingBuffer.func2 { require.NoError(t, buf.Close(context.Background())) }
blocking_buffer_test.go:113 kvevent_test.TestBlockingBuffer { } }

happend after
../../../util/quotapool/quotapool.go:149 quotapool.(*AbstractPool).Close { qp.mu.Lock() } <<<<<
blocking_buffer.go:248 kvevent.(*blockingBuffer).Close { b.qp.Close("blocking buffer closing") }
blocking_buffer_test.go:83 kvevent_test.TestBlockingBuffer.func2 { require.NoError(t, buf.Close(context.Background())) }
blocking_buffer_test.go:113 kvevent_test.TestBlockingBuffer { } }


Other goroutines holding locks:
goroutine 8488 lock 0xc000a4af88
blocking_buffer.go:235 kvevent.(*blockingBuffer).Close { b.mu.Lock() } <<<<<
blocking_buffer_test.go:83 kvevent_test.TestBlockingBuffer.func2 { require.NoError(t, buf.Close(context.Background())) }
blocking_buffer_test.go:113 kvevent_test.TestBlockingBuffer { } }
```

cc @cockroachdb/cdc

### PR DESCRIPTION
**Pull request by miretskiy**
A deadlock can occur during shutdown when we attempt
to release buffered events.  In such situation, we could
wind up notifying blocking buffer of an out of quota situation,
and that lead to a deadlock.

In addition to not needing to release event resources, this change
also identified and fixed a bug where buffered events were not released
to the buffer pool.

Fixes #71364

Release Justification: low danger logic/correctness bug fix (category 4).
Release Notes: None

### CODE REVIEW

**Comment by erikgrinaker** [comment]
Drive-by: please test and unskip `TestChangefeedFlushesSinkToReleaseMemory` as well.

**Review by erikgrinaker — APPROVED** [review]
:lgtm: Nice, thanks!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71374#-:-MleGpAr0I2VOmw2tlcZ:bhuisuw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @stevendanna)

**Review by stevendanna — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71374)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ajwerner and @miretskiy)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71374#-Mlfplzy4SBD5opyHoql:-Mlfplzy4SBD5opyHoqm:bfd61qr) (no related file):*
Nice! :lgtm: 

---

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71374#-:-Mlz14Wc0z2DcHnMRJoZ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @miretskiy)

**Comment by miretskiy** [comment]
tftr
bors r+

**Pull request merged**
