### PR TITLE
sql/schemachanger: add eventlog for comment on schema

### LINKED ISSUE #80576: add event logging for `COMMENT ON SCHEMA` statements
For some reason we have event logging for every `COMMENT ON` statement but `COMMENT ON SCHEMA`. we should add it.

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
Fixes #80576

Previously the event logging was missing for some reason. This pr adds
eventlog for it in declarative schema changer.

Release note: None.

### CODE REVIEW

**Review by fqazi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81386)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81386#-N2I7Kgi30qPdUSdYL0_):*
*in the
___
*[`pkg/util/log/eventpb/ddl_events.proto` line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81386#-N2I85Iu86naQiZbJckJ:-N2I85Iu86naQiZbJckK:b-bdpfdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a79bd228a5f6d44d285cd168214408efc79e1a13/pkg/util/log/eventpb/ddl_events.proto#L239)):*
> ```protobuf
> }
> 
> message CommentOnSchema {
> ```

Tempted to say we should have some type of coverage like a logic test to confirm the entries. I know the existing testing for this stuff is loose.

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81386)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81386#-N2I7Kgi30qPdUSdYL0_):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

*in the
</blockquote></details>

done.
___
*[`pkg/util/log/eventpb/ddl_events.proto` line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81386#-N2I85Iu86naQiZbJckJ:-N2IkSGiB0FauJtsnXe2:b-tm2tka) ([raw file](https://github.com/cockroachdb/cockroach/blob/a79bd228a5f6d44d285cd168214408efc79e1a13/pkg/util/log/eventpb/ddl_events.proto#L239)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Tempted to say we should have some type of coverage like a logic test to confirm the entries. I know the existing testing for this stuff is loose.
</blockquote></details>

good call, I added the event logging for the old schema changer as well, and add a logic test there. this would cover the new schema changer when we turn the fully supported flags on. I could add it to the `new_schema_changer` test file too though, but I didn't want to have duplicated coverage (which won't hurt for sure...)

**Review by fqazi — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81386)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

**Comment by chengxiong-ruan** [comment]
TFTR! @fqazi 
bors r+

**Comment by otan** [comment]
bors r-

looks like a test failed on the aforementioned bors run and is related to this PR

**Comment by chengxiong-ruan** [comment]
🙏 
bors r+

**Pull request merged**
