### PR TITLE
workload: add sqlstats workload

### LINKED ISSUE #119311: workload: create workload that replicates pressure on sql stats
We should create a workload generator that gets us into a state that puts heavy pressure on the persisted sql stats recording system. Ideally, the workload should:
* Generate a high volume high-cardinality statement fingerprints
* Optionally initialize with 1M rows in `system.statement_statistics` and `system.transaction_statistics`

Note that the `insights` workload has a `--scaleStats` option that generates high cardinality sql stats using different app names -- this is sufficienet for some cases but we'd also like to be able to generate cardinality using other stmt fingerprint dimensions.

Jira issue: CRDB-36142

### PR DESCRIPTION
**Pull request by dhartunian**
This new workload generates a high rate of insert queries that fill up the sql stats pipeline by generating a high number of fingerprints.

This happens because the order of the 10 columns is shuffled in each request and our fingerprint algorithm treates these as unique for now.

This workload isn't a perfect solution to stressing the stats system but gets us started. Running it for 10 minutes on a local cluster will easily generate very high request times for sql stats queries on the SQL Activity page when large timescales are selected, which bypass the sql_activity tables.

Fixes: #119311
Epic: None

Release note: None

### CODE REVIEW

**Review by abarganier — APPROVED** [review]
Awesome

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121590#-:-NuZTkmK40G5xqhi5M6S:b-hxjyw2)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @dhartunian, @renatolabs, and @xinhaoz)

___
*[`pkg/workload/sqlstats/sqlstats.go` line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121590#-NuZSNhP3Ms4TDOAAVGM:-NuZSNhP3Ms4TDOAAVGN:b4ovtkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf0d6e1e94f7fa9ac36c25b2c59057141cbfe7e5/pkg/workload/sqlstats/sqlstats.go#L63)):*
> ```Go
> var sqlStatsMeta = workload.Meta{
> 	Name:          "sqlstats",
> 	Description:   `Make SQL Activity cry`,
> ```

lol 😈😈😈



_Code quote:_
```Go
	Description:   `Make SQL Activity cry`,
```
___
*[`pkg/workload/sqlstats/sqlstats.go` line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121590#-NuZSpw3ASaPuEbLNTgr:-NuZSpw3ASaPuEbLNTgs:b52gkwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf0d6e1e94f7fa9ac36c25b2c59057141cbfe7e5/pkg/workload/sqlstats/sqlstats.go#L108)):*
> ```Go
> 
> func (g *gen) Next() string {
> 	g.Shuffle()
> ```

nit: can we collapse `Shuffle`'s lock usage into the one below? Maybe turn it into `shuffleLocked()`? Unless I'm missing something, I don't see why we need to acquire & release the lock twice. 



_Code quote:_
```Go
	g.Shuffle()
```
___
*[`pkg/workload/sqlstats/sqlstats.go` line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121590#-NuZT9ql6hV3VTOCucin:-NuZT9qmB6q1bcxv_8tl:b68fk6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf0d6e1e94f7fa9ac36c25b2c59057141cbfe7e5/pkg/workload/sqlstats/sqlstats.go#L123)):*
> ```Go
> 	defer g.Unlock()
> 
> 	g.rng.Shuffle(10, func(i, j int) {
> ```

nit: can we make this `len(g.in)` instead of `10`? 



_Code quote:_
```Go
10
```

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121590)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @DarrylWong, @renatolabs, and @xinhaoz)

___
*[`pkg/workload/sqlstats/sqlstats.go` line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121590#-NuZSNhP3Ms4TDOAAVGM:-Nu_XXDb2HippXEe7KG1:bxz4s37) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf0d6e1e94f7fa9ac36c25b2c59057141cbfe7e5/pkg/workload/sqlstats/sqlstats.go#L63)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

lol 😈😈😈
</blockquote></details>

lol I will change this
___
*[`pkg/workload/sqlstats/sqlstats.go` line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121590#-NuZSpw3ASaPuEbLNTgr:-Nu_XscCB4O6dW933R4t:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf0d6e1e94f7fa9ac36c25b2c59057141cbfe7e5/pkg/workload/sqlstats/sqlstats.go#L108)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: can we collapse `Shuffle`'s lock usage into the one below? Maybe turn it into `shuffleLocked()`? Unless I'm missing something, I don't see why we need to acquire & release the lock twice.
</blockquote></details>

done
___
*[`pkg/workload/sqlstats/sqlstats.go` line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121590#-NuZT9ql6hV3VTOCucin:-Nu_XvaX-Yy5g3Fn-AZ4:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf0d6e1e94f7fa9ac36c25b2c59057141cbfe7e5/pkg/workload/sqlstats/sqlstats.go#L123)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: can we make this `len(g.in)` instead of `10`?
</blockquote></details>

done.

**Review by abarganier — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121590#-:-NueLNoG3A-I4NNjaClF:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @dhartunian, @renatolabs, and @xinhaoz)

___
*[`pkg/workload/sqlstats/sqlstats.go` line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121590#-NuZSNhP3Ms4TDOAAVGM:-NueLJy7BhN7gz-VpDeS:b6p2nla) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf0d6e1e94f7fa9ac36c25b2c59057141cbfe7e5/pkg/workload/sqlstats/sqlstats.go#L63)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

lol I will change this
</blockquote></details>

Haha I liked the original!

**Comment by dhartunian** [comment]
bors r=abarganier

**Pull request merged**
