### PR TITLE
Week -1: follow-up emails

### PR DESCRIPTION
**Pull request by celiala**
This PR adds follow-up emails for:

- the day before `PrepDate` (to be sent if only there are still blockers)
- the day of `PrepDate` (to be sent if only there are still blockers)
- the day after `PrepDate` (to be sent if only there are still blockers)

The `post-blockers` command should be used for all emails before and up to `PrepDate`:
```
# where `DAYS_BEFORE_PREP` is one of: many-days | day-before | day-of

SMTP_PASSWORD=$MY_SMTP_PWD SMTP_USER=$MY_SMTP_USER GITHUB_TOKEN=$MY_GITHUB_TOKEN \
$(bazel info bazel-bin)/pkg/cmd/release/release_/release post-blockers \
  --release-series 21.1 \
  --smtp-user $MY_SMTP_USER --smtp-host smtp.gmail.com --smtp-port 587 \
  --to $MY_TO_EMAIL \
  --template-dir ./pkg/cmd/release/templates \
  --prep-date "Apr 1, 2022" --publish-date "May 1, 2022" \
  --days-before-prep-date $DAYS_BEFORE_PREP
```

The `cancel-release-date` should be used for the day after `PrepDate` email:
```
SMTP_PASSWORD=$MY_SMTP_PWD SMTP_USER=$MY_SMTP_USER GITHUB_TOKEN=$MY_GITHUB_TOKEN \
$(bazel info bazel-bin)/pkg/cmd/release/release_/release cancel-release-date \
  --release-series 21.1 \
  --smtp-user $MY_SMTP_USER --smtp-host smtp.gmail.com --smtp-port 587 \
  --to $MY_TO_EMAIL \
  --template-dir ./pkg/cmd/release/templates \
  --publish-date "May 1, 2022" --next-publish-date "Jun 1, 2022"
```

### TeamCity changes

This will be paired with the following TeamCity jobs:
*  [Send release blockers - 78595](https://teamcity.cockroachdb.com/buildConfiguration/Internal_Cockroach_Release_Process_SendReleaseBlockers_78595?branch=78595&buildTypeTab=overview&mode=builds#all-projects) 
* [Cancel release date - 78595](https://teamcity.cockroachdb.com/buildConfiguration/Internal_Cockroach_Release_Process_CancelReleaseDate_78595?branch=78595&mode=builds#all-projects)

image

### CODE REVIEW

**Comment by celiala** [comment]
Hi @rail - I thought I could get these emails up in time for us to run today's "Monday emails" step, but the new parameters don't seem to be wired up correctly 🤔 . See failed attempts:

https://teamcity.cockroachdb.com/buildConfiguration/Internal_Cockroach_Release_Process_SendReleaseBlockers_78595?branch=78595&mode=builds#all-projects

Maybe we can chat about this further in today's weekly release meeting.

**Comment by celiala** [comment]
Hi @rail - I just squashed -- this is RFAL whenever you have a moment, thank you!

**Review by rail — APPROVED** [review]
> Reviewed 42 of 42 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78595)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @celiala)

**Comment by celiala** [comment]
TFTR!

bors r=rail

**Pull request merged**
