### PR TITLE
roachprod-microbench: prefix microbenchmark names with its package path

### LINKED ISSUE #98298: roachprod-microbench: prefix microbenchmark names with its package path
Given that the results of microbenchmarks are merged on the first depth of the package tree for spreadsheets and most likely other reports and information, it would be better to prefix the microbenchmark names with its full package path. 

The tooling could also possibly confuse microbenchmarks with the same name and from the same tree as iterations rather than individual benchmarks and combine the metrics.

Epic [CRDB-20903](https://cockroachlabs.atlassian.net/browse/CRDB-20903)

Jira issue: CRDB-25177

### PR DESCRIPTION
**Pull request by herkolategan**
This change adds the package path as a prefix to the microbenchmark names during spreadsheet generation. This prevents any possible collisions between names when calculations are done. It will also make finding a microbenchmark in the codebase easier if referenced from one of the reports.

Resolves: #98298
Epic: CRDB-20903

### CODE REVIEW

**Review by smg260 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98382)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @srosenberg)

___
*[`pkg/cmd/roachprod-microbench/testdata/reports/set-b/pkg_server-report.log` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98382#-NQBSXt99vUIAz9vAks5:-NQBSXt99vUIAz9vAks6:b8h1afq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec1814a3d76d01bbcf429bee6cd75a261be2f24f/pkg/cmd/roachprod-microbench/testdata/reports/set-b/pkg_server-report.log#L13)):*
> ```
> BenchmarkSetupSpanForIncomingRPC/traceInfo-8 19126 61399 ns/op 62037 B/op 21 allocs/op
> BenchmarkSetupSpanForIncomingRPC/grpcMeta-8 19110 62679 ns/op 62580 B/op 27 allocs/op
> BenchmarkSetupSpanForIncomingRPC/no_parent-8 19574 62141 ns/op 62036 B/op 21 allocs/op
> ```

where is `no_parent` coming from?

**Review by herkolategan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98382)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @smg260 and @srosenberg)

___
*[`pkg/cmd/roachprod-microbench/testdata/reports/set-b/pkg_server-report.log` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98382#-NQBSXt99vUIAz9vAks5:-NQBTUOt7HffKYJg8w99:b-edezhl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec1814a3d76d01bbcf429bee6cd75a261be2f24f/pkg/cmd/roachprod-microbench/testdata/reports/set-b/pkg_server-report.log#L13)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

where is `no_parent` coming from?
</blockquote></details>

This is just some data I scrubbed from real microbenchmarks in cockroach, for the data driven tests, to serve as a baseline for future changes. But more specific to the question it is probably a permutation on that microbenchmark. I can make the data driven test more specific if required? The other case `name-conflict` was engineered to simulate a situation where we have name conflicts.

**Review by smg260 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98382)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @srosenberg)

___
*[`pkg/cmd/roachprod-microbench/testdata/reports/set-b/pkg_server-report.log` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98382#-NQBSXt99vUIAz9vAks5:-NQBmKOP3WPFPSdJJflZ:b-uw3eir) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec1814a3d76d01bbcf429bee6cd75a261be2f24f/pkg/cmd/roachprod-microbench/testdata/reports/set-b/pkg_server-report.log#L13)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

This is just some data I scrubbed from real microbenchmarks in cockroach, for the data driven tests, to serve as a baseline for future changes. But more specific to the question it is probably a permutation on that microbenchmark. I can make the data driven test more specific if required? The other case `name-conflict` was engineered to simulate a situation where we have name conflicts.
</blockquote></details>

Ah ok - thought it might have been a constant that's used to actually indicate something without a parent.

**Review by herkolategan — COMMENTED** [review]
Just became aware of the non-determinism in the data-driven test. The ordering of the output from `Tables` shifts around, I'll push an update to that soon.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98382#-:-NQCB1rO30sxSbzbABOH:b-tfekow)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @srosenberg)

**Review by herkolategan — COMMENTED** [review]
Should be deterministic now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98382#-:-NQCu1y303XsOPyKzqFR:b-i7u6qt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @srosenberg)

**Review by renatolabs — COMMENTED** [review]
Have you considered passing package data in the `NameLabels` of a `benchfmt.Result`? It seems to have a purpose somewhat similar to what we're doing here, although I believe the output wouldn't quite be exactly the same. This LGTM, just wondering if there's a more official API.

Seems like the tests still need some fixing though.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98382#-:-NQVlar08XsNJv-tJ_3U:b-cgj28j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @srosenberg)

___
*[`pkg/cmd/roachprod-microbench/compare.go` line 103 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98382#-NQVlVI70zscY99Q8MQs:-NQVlVI70zscY99Q8MQt:b-qqowqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/eefaceaa68a7359b2c0a3ba196b53b571cd8dd2d/pkg/cmd/roachprod-microbench/compare.go#L103)):*
> ```Go
> // name with the package name, as this would break the parsing of the benchmark
> // name by benchstat further down the line.
> func postfixResultWithPackage(pkg string, result *benchfmt.Result) *benchfmt.Result {
> ```

We could make this separator explicit in a package var referenced by the two functions here.
___
*[`pkg/cmd/roachprod-microbench/benchmark_test.go` line 30 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98382#-NQVgffOBtcfFe8UTGtY:-NQVgffOBtcfFe8UTGtZ:b84fl9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/eefaceaa68a7359b2c0a3ba196b53b571cd8dd2d/pkg/cmd/roachprod-microbench/benchmark_test.go#L30)):*
> ```Go
> 			return output
> 		}
> 		return ""
> ```

I know you didn't change this, but remind me why we don't fail the test in this case?

**Review by herkolategan — COMMENTED** [review]
Benchstat unfortunately only uses the `Content` field on that struct (ignores the rest), and it specifically looks for the a "Benchmark" prefix; hard return if one is not found. It also only uses that to name the metric. The only way to rename is then to alter the names post processing. This makes this solution rather a hacky way to get around it, and one I wasn't particularly keen on. There is a new version out for some of these tools. I plan to look into it at some point to see if it alleviates these issues.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98382#-:-NQZNi5A58BGfL-i6AM_:bi30cpb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs and @srosenberg)

___
*[`pkg/cmd/roachprod-microbench/compare.go` line 103 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98382#-NQVlVI70zscY99Q8MQs:-NQZOHV32oS0m4un5z80:b-p9zz5q) ([raw file](https://github.com/cockroachdb/cockroach/blob/eefaceaa68a7359b2c0a3ba196b53b571cd8dd2d/pkg/cmd/roachprod-microbench/compare.go#L103)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

We could make this separator explicit in a package var referenced by the two functions here.
</blockquote></details>

Good idea, I'll add a const.
___
*[`pkg/cmd/roachprod-microbench/benchmark_test.go` line 30 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98382#-NQVgffOBtcfFe8UTGtY:-NQZNxfHEMGbS3l6YURl:b-nsgmfa) ([raw file](https://github.com/cockroachdb/cockroach/blob/eefaceaa68a7359b2c0a3ba196b53b571cd8dd2d/pkg/cmd/roachprod-microbench/benchmark_test.go#L30)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

I know you didn't change this, but remind me why we don't fail the test in this case?
</blockquote></details>

Actually might be a good addition to only allow `benchmark` commands in the data-driven test file. I'll change this to a failure prompting that an unknown command was encountered.

**Review by renatolabs — APPROVED** [review]
:lgtm:

Formatting needs to be fixed, but otherwise, :ship: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98382#-:-NQafikK5VNcaERjQMqv:bo3zjg6)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @srosenberg)

**Comment by herkolategan** [comment]
TFTR!
bors r=renatolabs

**Pull request merged**
