### PR TITLE
build: enable nightly bigtest with distsql

### PR DESCRIPTION
**Pull request by asubiotto**
bigtest enables us to run a large suite of tests against distsql for
correctness testing.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14515)

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
LGTM, although perhaps you should add a separate makefile target and separate nightly test to see the results separately?

**Comment by RaduBerinde** [comment]
LGTM

**Comment by andreimatei** [comment]
LGTM

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14515#-:-Kg_XZ2X2NEBrVPXOFL5:bb6ywmx)*

**Comment by asubiotto** [comment]
Thanks for the suggestion @jordanlewis. Added a separate target. Results are saved in `artifacts/bigtest.log` for default bigtest logic tests and `artifacts/bigtest-distsql.log` when distsql is enabled. PTAL.

**Comment by jordanlewis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14515#-:-KgoXu_b8Gailr3IxFM5:bnfp4nl)*

**Pull request merged**
