### PR TITLE
opt: add cost penalty for scans with large cardinality

### LINKED ISSUE #64570: opt: avoid choosing index with unreliable stats
A customer ran into a case where they were doing a single row UPSERT. Instead of choosing the primary index (which would scan at most 1 row), the optimizer is choosing a secondary index. The index is chosen because according to the histogram, the relevant value would have no rows. But the stats are stale and the query actually reads through 100k+ rows from the index.

We have discussed augmenting the cost value with an "uncertainty range", which would address this problem (primary index has <=1 row with 100% certainty, the secondary index has expected 0 rows but with no upper bound). This would be a big change; but I believe we can also consider a more targeted fix, e.g. we could give a heavy cost "discount" to scan operators which have a known cardinality bound (or a penalty to scans with no cardinality bound).

Below is an illustration. The t_y_v_idx index could in principle return any number of rows.
```sql
> SET CLUSTER SETTING sql.stats.automatic_collection.enabled = false;
> create table t (x int, y int, v int, index (y, v), primary key (x,y));
> insert into t values (1, 1, 1), (2, 2, 2), (3, 3, 3);
> create statistics foo from t;
> explain upsert into t values (10, 10, 10);
                                             info
----------------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • upsert
  │ into: t(x, y, v)
  │ auto commit
  │ arbiter indexes: primary
  │
  └── • cross join (left outer)
      │ estimated row count: 1
      │
      ├── • values
      │     size: 3 columns, 1 row
      │
      └── • filter
          │ estimated row count: 1
          │ filter: x = 10
          │
          └── • scan
                estimated row count: 0 (<0.01% of the table; stats collected 32 seconds ago)
                table: t@t_y_v_idx
                spans: [/10 - /10]
```

The correct plan would be:
```
demo@127.0.0.1:26257/defaultdb> explain upsert into t values (1, 1, 1);
                                         info
---------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • upsert
  │ into: t(x, y, v)
  │ auto commit
  │ arbiter indexes: primary
  │
  └── • cross join (left outer)
      │ estimated row count: 1
      │
      ├── • values
      │     size: 3 columns, 1 row
      │
      └── • scan
            estimated row count: 1 (31% of the table; stats collected 15 seconds ago)
            table: t@primary
            spans: [/1/1 - /1/1]
            locking strength: for update
```

gz#9150

Jira issue: CRDB-7134

Jira issue: CRDB-13889

gz#16142

gz#18109

### PR DESCRIPTION
**Pull request by rytaft**
**opt: ensure we prefer a reverse scan to sorting a forward scan**

This commit fixes an issue where in some edge cases the optimizer would
prefer sorting the output of a forward scan over performing a reverse scan
(when there is no need to sort the output of the reverse scan).

Release note (performance improvement): The optimizer now prefers
performing a reverse scan over a forward scan + sort if the reverse
scan eliminates the need for a sort and the plans are otherwise
equivalent. This was the case before in most cases, but some edge
cases with a small number of rows have been fixed.

**opt: add cost penalty for scans with large cardinality**

This commit adds a new cost function, `largeCardinalityRowCountPenalty`,
which calculates a penalty that should be added to the row count of scans.
It is non-zero for expressions with unbounded maximum cardinality or with
maximum cardinality exceeding the row count estimate. Adding a few rows
worth of cost helps prevent surprising plans for very small tables or for
when stats are stale.

Fixes #64570

Release note (performance improvement): When choosing between index
scans that are estimated to have the same number of rows, the optimizer
now prefers indexes for which it has higher certainty about the maximum
number of rows over indexes for which there is more uncertainty in the
estimated row count. This helps to avoid choosing suboptimal plans for
small tables or if the statistics are stale.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

Thanks for this! Surprising (in a good way) that none of the "xform/external" plans are affected!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66979#-:-MdIeDvxErLqvDUYyo7p:blm8xnl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @rytaft)

___
*[pkg/sql/opt/xform/coster.go, line 146 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66979#-MdIeNu6-tx6mqrX6NSB:-MdIeNu6-tx6mqrX6NSC:b6w5tdb) ([raw file](https://github.com/cockroachdb/cockroach/blob/4beaeeea1213522be586ad6fea0c05c926ef8d1b/pkg/sql/opt/xform/coster.go#L146)):*
> ```Go
> 	// unbounded maximum cardinality. This helps prevent surprising plans for very
> 	// small tables or for when stats are stale.
> 	unboundedMaxCardinalityScanRowCountPenalty = fullScanRowCountPenalty
> ```

For full table scans, this is added on top of the `fullScanRowPenalty`? That should be clarified here.
___
*[pkg/sql/opt/xform/testdata/coster/scan, line 300 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66979#-MdIdO14-J_LKDh4sKLp:-MdIdO14-J_LKDh4sKLq:b89w4ci) ([raw file](https://github.com/cockroachdb/cockroach/blob/4beaeeea1213522be586ad6fea0c05c926ef8d1b/pkg/sql/opt/xform/testdata/coster/scan#L300)):*
> ```
> ----
> 
> exec-ddl
> ```

[nit] add a comment explaining what these stats are trying to achieve. We're trying to make the `(y,v)` index more appetizing for finding (10,10,10), yes? Surprised why the histogram on `x` doesn't contain 10, doesn't this make the index on `(x,y)` just as good (in that we expect 0 rows)? (maybe the multi-col stats override that? though the test would be less effective if we improved stats to consider the histogram on `x` too)
___
*[pkg/sql/opt/xform/testdata/coster/scan, line 423 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66979#-MdIe-tMDUPtxciwTIdC:-MdIe-tMDUPtxciwTIdD:bhzozj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4beaeeea1213522be586ad6fea0c05c926ef8d1b/pkg/sql/opt/xform/testdata/coster/scan#L423)):*
> ```
> 
> opt
> UPSERT INTO t64570 VALUES (10, 10, 10)
> ```

[nit] add a comment explaining what we're looking for - a scan of the PK with cardinality 1.

**Review by cucaroach — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, 12 of 41 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66979)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @rytaft)

**Review by cucaroach — APPROVED** [review]
> Reviewed 29 of 41 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66979)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

**Review by rytaft — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66979#-:-MdJ8u6z70tuC4q0Oynb:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @RaduBerinde)

___
*[pkg/sql/opt/xform/coster.go, line 146 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66979#-MdIeNu6-tx6mqrX6NSB:-MdJ4TSWBGGvAdUciSlw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4beaeeea1213522be586ad6fea0c05c926ef8d1b/pkg/sql/opt/xform/coster.go#L146)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

For full table scans, this is added on top of the `fullScanRowPenalty`? That should be clarified here.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/coster/scan, line 300 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66979#-MdIdO14-J_LKDh4sKLp:-MdIzJ6j-0n26z9x6Ot2:bm7yiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/4beaeeea1213522be586ad6fea0c05c926ef8d1b/pkg/sql/opt/xform/testdata/coster/scan#L300)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] add a comment explaining what these stats are trying to achieve. We're trying to make the `(y,v)` index more appetizing for finding (10,10,10), yes? Surprised why the histogram on `x` doesn't contain 10, doesn't this make the index on `(x,y)` just as good (in that we expect 0 rows)? (maybe the multi-col stats override that? though the test would be less effective if we improved stats to consider the histogram on `x` too)
</blockquote></details>

These were the stats created from the example in the issue. The multi-column stats aren't important here, so I've removed them. The reason this test case works is that we don't use histograms when the cardinality is less than 100, so we estimate 1 row for the primary index scan based on the distinct count and cardinality. But we *do* use the histograms when the cardinality is unbounded, so we estimate 0 rows for the secondary index scan. Here's the comment from `statistics_builder.go` (I completely forgot that we did this...):
```
	// This is the minimum cardinality an expression should have in order to make
	// it worth adding the overhead of using a histogram.
	minCardinalityForHistogram = 100
```
___
*[pkg/sql/opt/xform/testdata/coster/scan, line 423 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66979#-MdIe-tMDUPtxciwTIdC:-MdIzFMfEJDUb01apg9m:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4beaeeea1213522be586ad6fea0c05c926ef8d1b/pkg/sql/opt/xform/testdata/coster/scan#L423)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] add a comment explaining what we're looking for - a scan of the PK with cardinality 1.
</blockquote></details>

Done.

**Review by RaduBerinde — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 39 of 41 files at r2, 3 of 3 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66979)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

**Comment by rytaft** [comment]
I'll let this bake for a week-or-so and then backport

bors r+

**Comment by rytaft** [comment]
The backport to 20.2 is not clean, so I think I will only backport this to 21.1.

**Pull request merged**
