### PR TITLE
sql, jobs: use one mutation ID for all mutations in the same transaction

### PR DESCRIPTION
**Pull request by eriktrinh**
Increment the next mutation ID at most once per transaction using the
value present in the cluster version of the table descriptor. At most
one schema change job is ever created transaction, which relates to the
added mutations. The schema change job's description is also multi-lined
with the related statements which created the mutations.

Rollbacks of a mutation will now also rollback the other mutations
created in the same transaction.

Release note: None

### CODE REVIEW

**Review by vivekmenezes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32309)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/schema_change_in_txn, line 522 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRJGEkx2nfqQW0-dZx_:-LRJGEky6VkCAu7K0ctW:b78jvmy) ([raw file](https://github.com/cockroachdb/cockroach/blob/bef4d0b39386b4ea97ac415d95cc31fcd210bb34/pkg/sql/logictest/testdata/logic_test/schema_change_in_txn#L522)):*
> ```
> query T
> SELECT * FROM customers LIMIT 0
> ----
> ```

What is this testing? I think what you want to check here is that column "i" was not added to the table. I'm pretty sure before this change column "i" would get added to the table.
___
*[pkg/sql/sqlbase/structured.go, line 2081 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRJHNTO6juyVIBWTPaf:-LRJHNTP8oC_0PFrmmQm:bvczmy2) ([raw file](https://github.com/cockroachdb/cockroach/blob/bef4d0b39386b4ea97ac415d95cc31fcd210bb34/pkg/sql/sqlbase/structured.go#L2081)):*
> ```Go
> 	}
> 	m.MutationID = desc.ClusterVersion.NextMutationID
> 	desc.NextMutationID = desc.ClusterVersion.NextMutationID + 1
> ```

ordinarily this works fine. Whenever a table is created in the same transaction the mutation id will be set to the invalid value of 0.  I think it would be better to say explicitly that this logic only runs when ClusterVersion is non empty, and in the create table in transaction case the MutationID is set to 1.

if desc.ClusterVersion.IsEmpty() {
        m.MutationID = 1
} else {
    	m.MutationID = desc.ClusterVersion.NextMutationID
	desc.NextMutationID = desc.ClusterVersion.NextMutationID + 1
}
___
*[pkg/sql/sqlbase/structured.proto, line 779 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRK3Fvm9SWXRnCBWmtP:-LRK3Fvm9SWXRnCBWmtQ:b-9rophh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ef85f07381e83246503d1c14cdef7e4a5899e9b/pkg/sql/sqlbase/structured.proto#L779)):*
> ```protobuf
>     // The job id for a mutation job is the id in the system.jobs table of the
>     // schema change job executing the mutation referenced by mutation_id.
>     optional int64 job_id = 2 [(gogoproto.nullable) = false,
> ```

By changing the protobuf this change is going to become a lot more complex because you have to be concerned with this data present during an upgrade and what it means to loose the protobuf data completely.

Is it possible to make the job_id field here repeatable and move forward with this change without worrying about migrations?

**Review by eriktrinh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32309)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/schema_change_in_txn, line 522 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRJGEkx2nfqQW0-dZx_:-LRKYZO8BtPgpruaE90i:b-nskg12) ([raw file](https://github.com/cockroachdb/cockroach/blob/bef4d0b39386b4ea97ac415d95cc31fcd210bb34/pkg/sql/logictest/testdata/logic_test/schema_change_in_txn#L522)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

What is this testing? I think what you want to check here is that column "i" was not added to the table. I'm pretty sure before this change column "i" would get added to the table.
</blockquote></details>

Yes, this is testing that column "i" does not get added to the table, made this more explicit by adding the colnames option.
___
*[pkg/sql/sqlbase/structured.go, line 2081 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRJHNTO6juyVIBWTPaf:-LRND8QPEklSd3H-vxZ2:bu19qpg) ([raw file](https://github.com/cockroachdb/cockroach/blob/bef4d0b39386b4ea97ac415d95cc31fcd210bb34/pkg/sql/sqlbase/structured.go#L2081)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

ordinarily this works fine. Whenever a table is created in the same transaction the mutation id will be set to the invalid value of 0.  I think it would be better to say explicitly that this logic only runs when ClusterVersion is non empty, and in the create table in transaction case the MutationID is set to 1.

if desc.ClusterVersion.IsEmpty() {
        m.MutationID = 1
} else {
    	m.MutationID = desc.ClusterVersion.NextMutationID
	desc.NextMutationID = desc.ClusterVersion.NextMutationID + 1
}
</blockquote></details>

The jobs for mutations created in the same transaction of the CREATE TABLE has always been broken (`runSchemaChangesInTxn` never starts and completes any of the jobs). We should have a separate change which fixes these issues.
___
*[pkg/sql/sqlbase/structured.proto, line 779 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRK3Fvm9SWXRnCBWmtP:-LRKgLkL0TCYgfliTP37:b-55wajz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ef85f07381e83246503d1c14cdef7e4a5899e9b/pkg/sql/sqlbase/structured.proto#L779)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

By changing the protobuf this change is going to become a lot more complex because you have to be concerned with this data present during an upgrade and what it means to loose the protobuf data completely.

Is it possible to make the job_id field here repeatable and move forward with this change without worrying about migrations?
</blockquote></details>

Yes this is a concern, I've made it repeatable but it requires some special casing to handle old data present during an upgrade with multiple mutations with the same ID. PTAL, thanks!

**Review by vivekmenezes — CHANGES_REQUESTED** [review]
The more I look at this change the more my head spins.  I think the right approach here is to accept that a job can represent more than one command. So what we could do is add many ";" separated commands to the same job . I think that should get rid of all the complexity in this change. It will also stress the fact that the commands are grouped together and if one fails, all of them fail together. Also the rollback job will rollback all the commands and show them together as having rolled back.

Once you go into the realm of having the same mutation id have many job ids, each job is acting as a checkpoint repository for parts of the mutation id. That adds a lot of complexity to this change.

Thanks for taking this change so far, but the more I looked at it the more I was worried about it correctness and how difficult it would be to maintain

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-:-LRSHKQn57YB9YK4IrYx:bibss9y)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/structured.proto, line 779 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRK3Fvm9SWXRnCBWmtP:-LRSCfgn4svqAynwE8xl:bmb1ics) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ef85f07381e83246503d1c14cdef7e4a5899e9b/pkg/sql/sqlbase/structured.proto#L779)):*
<details><summary><i>Previously, eriktrinh (Erik Trinh) wrote…</i></summary><blockquote>

Yes this is a concern, I've made it repeatable but it requires some special casing to handle old data present during an upgrade with multiple mutations with the same ID. PTAL, thanks!
</blockquote></details>

I think we should add the jobID to the MutationDescriptor in this change so that later on after everyone has upgraded to 2.2 we can get rid of the whole MutationJobs mess. Add a TODO to remove it for release 2.3
___
*[pkg/sql/sqlbase/structured.proto, line 780 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRS8dO2EoFQkFQ_Jiq8:-LRS8dO2EoFQkFQ_Jiq9:b-sc8nav) ([raw file](https://github.com/cockroachdb/cockroach/blob/835fc114bd9558190056fb9219c6bee816820882/pkg/sql/sqlbase/structured.proto#L780)):*
> ```protobuf
>     // the mutation referenced by mutation_id. The length of this is equal
>     // to the number of mutations with the same mutation ID. The ordering
>     // remains synchronized with the mutations list.
> ```

Add a comment: There is a one to one relationship here between a jobid and a mutation in the mutation list.

**Review by vivekmenezes — COMMENTED** [review]
The other thing I'd do is add the job id to the DescriptorMutation as a write only field so that future versions of the software can consider getting rid of MutationJobs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-:-LRSPTQC8Lk90Qzbr0Pl:bvm0c4e)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by vivekmenezes — COMMENTED** [review]
Please save this branch somewhere before you take that approach

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-:-LRSRzrR57XfPNS4Fe1d:b7v32i7)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by eriktrinh — COMMENTED** [review]
> The more I look at this change the more my head spins.  I think the right approach here is to accept that a job can represent more than one command. So what we could do is add many ";" separated commands to the same job . I think that should get rid of all the complexity in this change. It will also stress the fact that the commands are grouped together and if one fails, all of them fail together. Also the rollback job will rollback all the commands and show them together as having rolled back.

This is a much better idea, updated the PR. Also added another commit which fixes issues in the column backfill caused by grouping column mutations with the same mutation ID.

> The other thing I'd do is add the job id to the DescriptorMutation as a write only field so that future versions of the software can consider getting rid of MutationJobs!

As long as mutation IDs are mapped to single jobs I am fine with having the MutationJobs in the tables.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-:-LRTWjJS5c6YXpyzPqIC:b-vq03d5)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/structured.proto, line 779 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRK3Fvm9SWXRnCBWmtP:-LRTXvKm64svpYHTkFZe:b-by9q0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ef85f07381e83246503d1c14cdef7e4a5899e9b/pkg/sql/sqlbase/structured.proto#L779)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I think we should add the jobID to the MutationDescriptor in this change so that later on after everyone has upgraded to 2.2 we can get rid of the whole MutationJobs mess. Add a TODO to remove it for release 2.3
</blockquote></details>

See other comment.
___
*[pkg/sql/sqlbase/structured.proto, line 780 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRS8dO2EoFQkFQ_Jiq8:-LRTXZ3x6GMPDNdZJenX:b-il00n3) ([raw file](https://github.com/cockroachdb/cockroach/blob/835fc114bd9558190056fb9219c6bee816820882/pkg/sql/sqlbase/structured.proto#L780)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Add a comment: There is a one to one relationship here between a jobid and a mutation in the mutation list.
</blockquote></details>

Reverted to the previous comment which should be adequate.

**Review by vivekmenezes — CHANGES_REQUESTED** [review]
Great change!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-:-LRgfJ2h2k1qUEtOmAG2:b-cbr3fr)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/jobs/jobs.go, line 183 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRgatA27oJfMSXdFMHa:-LRgatA27oJfMSXdFMHb:b89k6yz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce71ddab70dd001627989af3b7d2359333eb5f0b/pkg/jobs/jobs.go#L183)):*
> ```Go
> 			if err != nil {
> 				return false, err
> 			}
> ```

rewrite to:

desc, err := updateFn(ctx, prev)
			if err != nil {
				return false, err
			}
payload.Description = desc
return prev != desc, nil
___
*[pkg/sql/schema_changer_test.go, line 2171 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRgbo8p4GqyIn_XT3gp:-LRgbo8p4GqyIn_XT3gq:b-xfud9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce71ddab70dd001627989af3b7d2359333eb5f0b/pkg/sql/schema_changer_test.go#L2171)):*
> ```Go
> 	// TODO(erik): Ignore errors or individually drop indexes in
> 	// DELETE_AND_WRITE_ONLY which failed during the creation backfill
> 	// as a rollback from a drop.
> ```

Don't follow the TODO here? Do we need to fix this issue? 
___
*[pkg/sql/schema_changer_test.go, line 2383 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRgbu9QC43Tf8GqO25G:-LRgbu9QC43Tf8GqO25H:b-7m74ox) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce71ddab70dd001627989af3b7d2359333eb5f0b/pkg/sql/schema_changer_test.go#L2383)):*
> ```Go
> 		{`select-create`, `SELECT * FROM t.kv`, `CREATE INDEX bar ON t.kv (v)`, ``},
> 		{`index-on-add-col`, `ALTER TABLE t.kv ADD i INT`,
> 			`CREATE INDEX foobar ON t.kv (i)`, ``},
> ```

nice!
___
*[pkg/sql/backfill/backfill.go, line 236 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRgeINFAYc_8jgZHw6A:-LRgeINFAYc_8jgZHw6B:b-b411y5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce71ddab70dd001627989af3b7d2359333eb5f0b/pkg/sql/backfill/backfill.go#L236)):*
> ```Go
> 			}
> 			if j < len(cb.added) {
> 				iv.CurSourceRow = append(iv.CurSourceRow, val)
> ```

Add a comment?
___
*[pkg/sql/logictest/testdata/logic_test/schema_change_in_txn, line 550 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRgeZnt4oT05W-0j5LU:-LRgeZnt4oT05W-0j5LV:b7ncptd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce71ddab70dd001627989af3b7d2359333eb5f0b/pkg/sql/logictest/testdata/logic_test/schema_change_in_txn#L550)):*
> ```
> ----
> succeeded                                                             ALTER TABLE test.public.customers ADD COLUMN i INT DEFAULT 5;
> ALTER TABLE test.public.customers ADD COLUMN j INT AS (i - 1) STORED
> ```

Can you add a transaction that drops an existing column and adds an index to the column in the same transaction. It will fail.

Also worth adding 5 columns and 5 indexes on the columns to showcase how they all get processed and what that means for the job description.

And while you're at it might as well also add 5 columns and 5 indexes where the 4 index fails. That way we check that a larger rollback works.

Thanks!
___
*[pkg/sql/sqlbase/structured.go, line 2081 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRJHNTO6juyVIBWTPaf:-LRgcxUB2rjSs4UcnSqL:b8eelqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/bef4d0b39386b4ea97ac415d95cc31fcd210bb34/pkg/sql/sqlbase/structured.go#L2081)):*
<details><summary><i>Previously, eriktrinh (Erik Trinh) wrote…</i></summary><blockquote>

The jobs for mutations created in the same transaction of the CREATE TABLE has always been broken (`runSchemaChangesInTxn` never starts and completes any of the jobs). We should have a separate change which fixes these issues.
</blockquote></details>

I'm fine leaving it the way it is. You can add a comment that the mutation id picked on a table created in the same transaction is InvalidMutationID, and that it's fine because it gets processed within the same transaction.
___
*[pkg/sql/sqlbase/structured.go, line 123 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRgceCxDRCrTX1VG4XN:-LRgceCxDRCrTX1VG4XO:bfdgjbm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce71ddab70dd001627989af3b7d2359333eb5f0b/pkg/sql/sqlbase/structured.go#L123)):*
> ```Go
> 	// MutationJobID is the ID of the created job for all of the finalized mutations
> 	// from the current transaction.
> 	MutationJobID int64
> ```

It's really hard to understand why you need any of these three. The MutableTableDescriptor contains the cluster version and the current version. What's missing in these two that warrants more information?

**Review by eriktrinh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32309)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/jobs/jobs.go, line 183 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRgatA27oJfMSXdFMHa:-LRgiDmU3V7A3Cx3VHpx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce71ddab70dd001627989af3b7d2359333eb5f0b/pkg/jobs/jobs.go#L183)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

rewrite to:

desc, err := updateFn(ctx, prev)
			if err != nil {
				return false, err
			}
payload.Description = desc
return prev != desc, nil
</blockquote></details>

Done.
___
*[pkg/sql/schema_changer_test.go, line 2171 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRgbo8p4GqyIn_XT3gp:-LRglD7X8UwG_JtXHASW:b-az6z60) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce71ddab70dd001627989af3b7d2359333eb5f0b/pkg/sql/schema_changer_test.go#L2171)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Don't follow the TODO here? Do we need to fix this issue? 
</blockquote></details>

Yes, if the drop of the unique index somehow fails, or (any of the mutations with the same ID fails) then the rollback creating the index can fail. This leaves the mutation in the mutations list for async processing and will always fail until the unique constraint can be satisfied, blocking any of the later queued mutations.
___
*[pkg/sql/backfill/backfill.go, line 236 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRgeINFAYc_8jgZHw6A:-LRgl2RnA0drrWBD-XE6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce71ddab70dd001627989af3b7d2359333eb5f0b/pkg/sql/backfill/backfill.go#L236)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Add a comment?
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/schema_change_in_txn, line 550 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRgeZnt4oT05W-0j5LU:-LRgtBI1D3wEZP2SGtJk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce71ddab70dd001627989af3b7d2359333eb5f0b/pkg/sql/logictest/testdata/logic_test/schema_change_in_txn#L550)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Can you add a transaction that drops an existing column and adds an index to the column in the same transaction. It will fail.

Also worth adding 5 columns and 5 indexes on the columns to showcase how they all get processed and what that means for the job description.

And while you're at it might as well also add 5 columns and 5 indexes where the 4 index fails. That way we check that a larger rollback works.

Thanks!
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.go, line 2081 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRJHNTO6juyVIBWTPaf:-LRgkJLR7odOKtJO0J9s:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bef4d0b39386b4ea97ac415d95cc31fcd210bb34/pkg/sql/sqlbase/structured.go#L2081)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I'm fine leaving it the way it is. You can add a comment that the mutation id picked on a table created in the same transaction is InvalidMutationID, and that it's fine because it gets processed within the same transaction.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.go, line 123 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRgceCxDRCrTX1VG4XN:-LRgqIZi3Exvqb-uiPl0:bkl8rdg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce71ddab70dd001627989af3b7d2359333eb5f0b/pkg/sql/sqlbase/structured.go#L123)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

It's really hard to understand why you need any of these three. The MutableTableDescriptor contains the cluster version and the current version. What's missing in these two that warrants more information?
</blockquote></details>

I've removed two of them, leaving `NumFinalizedMutations` to know how many resume spans to add to the job details (really there should only be one resume span representing every column mutation for the job, and one for all index mutations). This info is not available when just comparing the cluster version and the current version because the info required is the number of added mutations added in between calls to `createOrUpdateSchemaChangeJob`, not between transactions.

**Review by vivekmenezes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32309)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/schema_changer_test.go, line 2171 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRgbo8p4GqyIn_XT3gp:-LRhSsba5RKhTIAC0hG_:bxjiyqw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce71ddab70dd001627989af3b7d2359333eb5f0b/pkg/sql/schema_changer_test.go#L2171)):*
<details><summary><i>Previously, eriktrinh (Erik Trinh) wrote…</i></summary><blockquote>

Yes, if the drop of the unique index somehow fails, or (any of the mutations with the same ID fails) then the rollback creating the index can fail. This leaves the mutation in the mutations list for async processing and will always fail until the unique constraint can be satisfied, blocking any of the later queued mutations.
</blockquote></details>

Yeah create an issue once this PR has been merged for this future work.
___
*[pkg/sql/table.go, line 686 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRh_GIY9_7LmQ3e_zSm:-LRh_GIY9_7LmQ3e_zSn:b8tx6j1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce8b604390b21fad6517737999ed47a32231a30f/pkg/sql/table.go#L686)):*
> ```Go
> 
> 	span := tableDesc.PrimaryIndexSpan()
> 	for i := tableDesc.NumFinalizedMutations; i < len(tableDesc.Mutations); i++ {
> ```

We do not need NumFinalizedMutations, you can use:

i := len(tableDesc.ClusterVersion.Mutations) + len(spanList)
___
*[pkg/sql/table.go, line 718 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRh_fdj-Y1wr1DENAqr:-LRh_fdj-Y1wr1DENAqs:b-add4g2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce8b604390b21fad6517737999ed47a32231a30f/pkg/sql/table.go#L718)):*
> ```Go
> 			ctx,
> 			func(ctx context.Context, description string) (string, error) {
> 				return strings.Join([]string{description, stmt}, ";\n"), nil
> ```

I'm not convinced a newline is valuable here. How about "; "?
___
*[pkg/sql/logictest/testdata/logic_test/computed, line 678 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRhcfhv6003sSXoCPNM:-LRhcfhv6003sSXoCPNN:b-ukmnm3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fcbe2b73489b0b6626c0ab6ba55c9dfc8b53bd6/pkg/sql/logictest/testdata/logic_test/computed#L678)):*
> ```
> # Verify error if a default and computed column are added at the same time.
> statement error column "d" does not exist
> ALTER TABLE x ADD COLUMN d INT DEFAULT 15, ADD COLUMN e INT AS (d + a) STORED
> ```

I think it's okay to remove this failing command, but we should still test it somewhere
___
*[pkg/sql/sqlbase/computed_exprs.go, line 176 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRhdXeO-HY1aRyPIKvo:-LRhdXeO-HY1aRyPIKvp:b-4051fn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce8b604390b21fad6517737999ed47a32231a30f/pkg/sql/sqlbase/computed_exprs.go#L176)):*
> ```Go
> 
> 	maybeAddColumnInfo := func(col ColumnDescriptor) {
> 		if addingCols {
> ```

push this check to the callees and make this function addColumnInfo()
___
*[pkg/sql/sqlbase/structured.go, line 115 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRhdf4R3ONtS5HqIuJK:-LRhdf4R3ONtS5HqIuJL:b-8114lx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce8b604390b21fad6517737999ed47a32231a30f/pkg/sql/sqlbase/structured.go#L115)):*
> ```Go
> 
> 	// NumFinalizedMutations is the count of mutations associated with a job.
> 	NumFinalizedMutations int
> ```

I'm pretty sure you can delete this

**Review by vivekmenezes — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-:-LRhfUbcDcYIYOk-HWFi:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by vivekmenezes — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-:-LRhf_LW-q_OZskrBGRg:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by eriktrinh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32309)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/schema_changer_test.go, line 2171 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRgbo8p4GqyIn_XT3gp:-LRhkX6l7K2gljwSmv65:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce71ddab70dd001627989af3b7d2359333eb5f0b/pkg/sql/schema_changer_test.go#L2171)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Yeah create an issue once this PR has been merged for this future work.
</blockquote></details>

Ack.
___
*[pkg/sql/table.go, line 686 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRh_GIY9_7LmQ3e_zSm:-LRhl4GH1hnCbRCMkuGZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce8b604390b21fad6517737999ed47a32231a30f/pkg/sql/table.go#L686)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

We do not need NumFinalizedMutations, you can use:

i := len(tableDesc.ClusterVersion.Mutations) + len(spanList)
</blockquote></details>

Done.
___
*[pkg/sql/table.go, line 718 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRh_fdj-Y1wr1DENAqr:-LRhlHzX79liQF0exW8E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce8b604390b21fad6517737999ed47a32231a30f/pkg/sql/table.go#L718)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I'm not convinced a newline is valuable here. How about "; "?
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/computed, line 678 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRhcfhv6003sSXoCPNM:-LRhryv73Fc7BzdM1DxJ:b-ygd8ry) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fcbe2b73489b0b6626c0ab6ba55c9dfc8b53bd6/pkg/sql/logictest/testdata/logic_test/computed#L678)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I think it's okay to remove this failing command, but we should still test it somewhere
</blockquote></details>

Done, moved to `schema_change_in_txn`.
___
*[pkg/sql/sqlbase/computed_exprs.go, line 176 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRhdXeO-HY1aRyPIKvo:-LRhmT846piJ7fLt6t9L:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce8b604390b21fad6517737999ed47a32231a30f/pkg/sql/sqlbase/computed_exprs.go#L176)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

push this check to the callees and make this function addColumnInfo()
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.go, line 115 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRhdf4R3ONtS5HqIuJK:-LRhmUG0DPB4HbQ0uaTA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce8b604390b21fad6517737999ed47a32231a30f/pkg/sql/sqlbase/structured.go#L115)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I'm pretty sure you can delete this
</blockquote></details>

Done.

**Review by eriktrinh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32309)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/schema_changer_test.go, line 2171 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32309#-LRgbo8p4GqyIn_XT3gp:-LRhwb6m7GDH0lkBN7Pc:bbnccqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce71ddab70dd001627989af3b7d2359333eb5f0b/pkg/sql/schema_changer_test.go#L2171)):*
<details><summary><i>Previously, eriktrinh (Erik Trinh) wrote…</i></summary><blockquote>

Ack.
</blockquote></details>

#32486

**Pull request merged**
