### PR TITLE
cmd/benchmark: run without timeout

### PR DESCRIPTION
**Pull request by tamird**

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/cmd/benchmark/main.go, line 59 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16529#-Kmd7kJqFMC9dCDhcYhU:-Kmd7kJqFMC9dCDhcYhV:bzi5s8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcee525093ad8fdedff9c519ad846dcd6f121bd9/pkg/cmd/benchmark/main.go#L59)):*
> ```Go
> 
> func (tw *taggedWriter) Write(b []byte) (int, error) {
> 	return tw.Writer.Write(append(append([]byte(tw.tag), []byte(": ")...), b...))
> ```

Can't you make multiple calls to `tw.Writer.Write`? I think that would be simpler, cleaner and faster (if it works).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16529)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16529#-:-Kmd8DlY9-WdeuI_XVLC:bnfp4nl)*

**Comment by tamird** [comment]
It probably won't be faster in the case of that writer being os.Stderr,
which has synchronization on every write.

**Comment by petermattis** [comment]
> It probably won't be faster in the case of that writer being os.Stderr, which has synchronization on every write.

`os.Stderr` doesn't synchronize on every write. It does do a syscall, though, so you might be correct up multiple writes not being faster. My comment about speed was less important than the simplicity aspect, though. All of those appends are ugly.

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/cmd/benchmark/main.go, line 59 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16529#-Kmd7kJqFMC9dCDhcYhU:-Kmh_0jMJ_8owA1fbG7h:bb71pro) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcee525093ad8fdedff9c519ad846dcd6f121bd9/pkg/cmd/benchmark/main.go#L59)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can't you make multiple calls to `tw.Writer.Write`? I think that would be simpler, cleaner and faster (if it works).
</blockquote></details>

PTAL

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16529)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/cmd/benchmark/main.go, line 59 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16529#-Kmd7kJqFMC9dCDhcYhU:-Kmh_FDUPHYPasKj3shl:b-la2183) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcee525093ad8fdedff9c519ad846dcd6f121bd9/pkg/cmd/benchmark/main.go#L59)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

PTAL
</blockquote></details>

Much clearer! :thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16529)*

**Pull request merged**
