### PR TITLE
testutils/buildutil: properly canonicalize import paths

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8400)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm: just one comment

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[testutils/buildutil/build.go, line 40 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8400#-KOhZsRHZ4HaBOhrZwYc:-KOhZsRI2cQjOaljUoi8:b-uq71s6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3826005a3d3c26805a738185624f2076e4470a53/testutils/buildutil/build.go#L40)):*
> ```Go
> 		}
> 
> 		for _, importPath := range pkg.Imports {
> ```

We now have `importpath` and `importPath` accessible from the same context, can we rename one of them? Or we could make `addImports` a separate standalone function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8400#-:-KOh_-DVhpvbeTgXgFL6:b1j0qu8)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[testutils/buildutil/build.go, line 40 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8400#-KOhZsRHZ4HaBOhrZwYc:-KOiozYS3b66zk32UBfq:bs8quiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3826005a3d3c26805a738185624f2076e4470a53/testutils/buildutil/build.go#L40)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> We now have `importpath` and `importPath` accessible from the same context, can we rename one of them? Or we could make `addImports` a separate standalone function.
</details>
can't make it a separate function because of the need for it to 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8400)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[testutils/buildutil/build.go, line 40 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8400#-KOhZsRHZ4HaBOhrZwYc:-KOjUZtYEJVMa7Tzon2V:b3kre) ([raw file](https://github.com/cockroachdb/cockroach/blob/3826005a3d3c26805a738185624f2076e4470a53/testutils/buildutil/build.go#L40)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can't make it a separate function because of the need for it to 
</details>
?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8400#-:-KOjUs2IIpzhce6tNLJr:bnfp4nl)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[acceptance/monotonic_insert_test.go, line 99 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8400#-KOjVy9Hjr2yeeOEPNeu:-KOjVy9Hjr2yeeOEPNev:b-8ns8oo) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6c6ce807c9ca4c414c1e54a044c067d038084f9/acceptance/monotonic_insert_test.go#L99)):*
> ```Go
> 		logPrefix := fmt.Sprintf("%03d.%03d: ", atomic.AddUint64(&idGen, 1), client.ID)
> 		l := func(msg string, args ...interface{}) {
> 			t.Logf(logPrefix+msg, args...)
> ```

Is there a benefit to doing this?

---

*[testutils/buildutil/build.go, line 27 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8400#-KOjW_XSJvbPO8ga7KBS:-KOjW_XTOMSQPCGGp3ym:bipbm5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/c619c440de9ac4b9230393489c85153d4296126a/testutils/buildutil/build.go#L27)):*
> ```Go
> // TransitiveImports returns a set containing all of importpath's
> // transitive dependencies.
> func TransitiveImports(importpath string, cgo bool) (map[string]struct{}, error) {
> ```

`s/importpath/importPath/g`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8400#-:-KOjWj-CsHuE86dK1tC-:bnfp4nl)*

**Comment by tamird** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[acceptance/monotonic_insert_test.go, line 99 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8400#-KOjVy9Hjr2yeeOEPNeu:-KOjaj8imtvooQhzNdTW:b-8u5daz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6c6ce807c9ca4c414c1e54a044c067d038084f9/acceptance/monotonic_insert_test.go#L99)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Is there a benefit to doing this?
</details>
Doesn't really matter, just cleaner.

---

*[testutils/buildutil/build.go, line 40 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8400#-KOhZsRHZ4HaBOhrZwYc:-KOjYDm6nYxp2McRcyL1:b-p0t8n4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3826005a3d3c26805a738185624f2076e4470a53/testutils/buildutil/build.go#L40)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> ?
</details>
heh - sorry. separate function is awkward because it'd need a bunch more arguments.

---

*[testutils/buildutil/build.go, line 27 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8400#-KOjW_XSJvbPO8ga7KBS:-KOjamwSDN9T3J5icFrY:b-quv9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c619c440de9ac4b9230393489c85153d4296126a/testutils/buildutil/build.go#L27)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `s/importpath/importPath/g`
</details>
Done in a separate commit since it was `importpath` following the revert.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8400)*

**Comment by petermattis** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[acceptance/monotonic_insert_test.go, line 99 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8400#-KOjVy9Hjr2yeeOEPNeu:-KOjbrrrfjE6tzQTjE9d:b-i3h8hg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6c6ce807c9ca4c414c1e54a044c067d038084f9/acceptance/monotonic_insert_test.go#L99)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Doesn't really matter, just cleaner.
</details>
I don't have a problem with it, just want to understand why it is cleaner. Can you expand on why?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8400)*

**Comment by tamird** [comment]
Avoids an import, doesn't introduce random orphan `context.Context`s.

**Pull request merged**
