### PR TITLE
pkg/metrics: use experimental native histograms.

### PR DESCRIPTION
**Pull request by jmcarp**
Optionally enable prometheus native histograms. This feature is still
marked as experimental in prometheus, so flag using an environment
variable, and use additional environment variables to tune precision and
max bucket count. Prometheus native histograms currently only support
exponentially spaced buckets, so we also limit their use to metrics with
an exponential distribution. Note that native histograms currently use
the protobuf exposition format, so we add content negotiation to the
prometheus exporter.

Epic: https://cockroachlabs.atlassian.net/browse/CC-9716

Release note: None

### CODE REVIEW

**Review by abarganier — COMMENTED** [review]
Hey Josh! Can you provide us more information about this experiment? Some information about the problem this aims to solve, the impact of moving away from pre-defined buckets, and what we hope to learn from these experiments would be helpful to review this PR. We've gotten ourselves into some trouble recently regarding bucket counts and boundaries for histogram metrics, so the obs-infra considers this code sensitive and we want to make sure we use caution when making changes. That's not to say we're completely opposed, but we want to make sure we fully understand what's happening. Happy to talk through this more!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104302#-:-NXQyItd2aNYrDVcTDDs:beiklw4)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by jmcarp** [comment]
Rebased on master after @ericharmeling's [metrics refactor](https://github.com/cockroachdb/cockroach/pull/107388) was merged, so now we can enable native histograms only if the environment flag is set and if the given metric uses an exponential distribution. I have actually never written a PR against this repo before and am probably missing things, but I'm calling this ready for review—ping @abarganier @ericharmeling.

**Comment by jmcarp** [comment]
Some additional context:

* We found that switching from conventional to native histograms dropped overall prometheus memory use by 30-50%. This didn't involve any loss of precision, since the default bucket exponential factor of 1.1 is more precise than any of the current sets of buckets in pkg/util/metric. We can also tune the precision of native histograms by changing the bucket factor via environment variable if necessary.
* Under this patch, if native histograms are enabled by environment flag, prometheus can be configured to scrape conventional histograms, native histograms, or both. In other words, switching between histogram implementations doesn't even require reconfiguring or restarting the database.
* The promql for working with conventional vs native histograms is almost identical. For example, the `histogram_quantile` function works in the same way for conventional and native histograms. We just remove the `_bucket` suffix from the metric name to query native histograms.

**Review by dhartunian — COMMENTED** [review]
@jmcarp this all sounds good. I like the configuration knobs.

Can you update the PR with a detailed commit message that explains the new functionality, how it's configured, and how we and the customer scan take advantage (w/ release notes since our self-hosted customers will want to use this too). I think that and some native histogram test cases are the biggest things missing here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104302#-:-NbpR5q47hgvSddd-Mh6:b7cawb8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @jmcarp, @renatolabs, and @smg260)

___
*[`go.mod` line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104302#-NbpOnQc4C74D7fL9Kcg:-NbpOnQc4C74D7fL9Kch:b-u66xl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad223089ca2ccc03734c90dafdd3da03d8aba68/go.mod#L33)):*
> ```XML
> 	google.golang.org/genproto v0.0.0-20230227214838-9b19f0bdc514
> 	google.golang.org/grpc v1.53.0
> 	google.golang.org/protobuf v1.30.0
> ```

I think usually bumping the protobuf version is sensitive. Can we avoid in this PR?
___
*[`pkg/util/metric/metric.go` line 213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104302#-NbpP5ms0S5KD-E1Ej9E:-NbpP5ms0S5KD-E1Ej9F:b-4kmqb6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad223089ca2ccc03734c90dafdd3da03d8aba68/pkg/util/metric/metric.go#L213)):*
> ```Go
> // rather than a collection of per-bucket counter series. If enabled, both
> // conventional and native histograms are exported.
> const useNativeHistogramsEnvVar = "COCKROACH_ENABLE_NATIVE_HISTOGRAMS"
> ```

should the env var clarify that these are `PROMETHEUS_NATIVE_HISTOGRAMS`? (same with 2 below)
___
*[`pkg/util/metric/prometheus_exporter_test.go` line 22 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104302#-NbpRV25-y66XZs3julI:-NbpRV25-y66XZs3julJ:blmrgoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad223089ca2ccc03734c90dafdd3da03d8aba68/pkg/util/metric/prometheus_exporter_test.go#L22)):*
> ```Go
> )
> 
> func TestPrometheusExporter(t *testing.T) {
> ```

Add test case for native histogram

**Comment by jmcarp** [comment]
Wrote a better commit message.

**Comment by jmcarp** [comment]
*[`go.mod` line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104302#-NbpOnQc4C74D7fL9Kcg:-Nbu7xPV1EgvLSKsx6Vp:b-qf9auf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad223089ca2ccc03734c90dafdd3da03d8aba68/go.mod#L33)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I think usually bumping the protobuf version is sensitive. Can we avoid in this PR?
</blockquote></details>

Done. I see that prometheus/client_golang bumped this automatically recently in https://github.com/prometheus/client_golang/pull/1243, but I believe it's fine to pin to an older version.

**Comment by jmcarp** [comment]
*[`pkg/util/metric/metric.go` line 213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104302#-NbpP5ms0S5KD-E1Ej9E:-Nbu8pxN1tw91EZwofr6:b-40ctdv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad223089ca2ccc03734c90dafdd3da03d8aba68/pkg/util/metric/metric.go#L213)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

should the env var clarify that these are `PROMETHEUS_NATIVE_HISTOGRAMS`? (same with 2 below)
</blockquote></details>

Sounds good, I renamed the envvars.

**Comment by jmcarp** [comment]
*[`pkg/util/metric/prometheus_exporter_test.go` line 22 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104302#-NbpRV25-y66XZs3julI:-Nbu8vEKD4mgwodKk2qW:bqmjwcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad223089ca2ccc03734c90dafdd3da03d8aba68/pkg/util/metric/prometheus_exporter_test.go#L22)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Add test case for native histogram
</blockquote></details>

Added.

**Review by dhartunian — APPROVED** [review]
> Reviewed 4 of 27 files at r2, 8 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104302)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @renatolabs, and @smg260)

**Comment by jmcarp** [comment]
blathers backport 23.1

**Pull request merged**
