### PR TITLE
opt: update coster logic for sort and revscan

### PR DESCRIPTION
**Pull request by rytaft**
There are some queries where a sort was chosen previously by the
optimizer when it should have chosen a reverse scan. This commit
adjusts the cost calculation for each operator to improve this
choice.

In addition, this commit adds a small cost for all operators to break
ties and prefer plans with fewer operators.

Release note: None

### CODE REVIEW

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27979)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/xform/coster.go, line 135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27979#-LIOhGc0-HYL81x4ccMV:-LIOhGc0-HYL81x4ccMW:b-qcw8wp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c79174ae7ba3ab1e9e9d79ea3d2428e2a769fbb/pkg/sql/opt/xform/coster.go#L135)):*
> ```Go
> 	perRowCost := c.rowSortCost(len(physical.Ordering.Columns))
> 	cost := memo.Cost(rowCount) * perRowCost
> 	if rowCount > 2 {
> ```

Why `rowCount > 2`?
___
*[pkg/sql/opt/xform/coster.go, line 155 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27979#-LIOhhSN8r8KN6G3_GVd:-LIOhhSN8r8KN6G3_GVe:bs057vb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c79174ae7ba3ab1e9e9d79ea3d2428e2a769fbb/pkg/sql/opt/xform/coster.go#L155)):*
> ```Go
> 		if rowCount > 2 {
> 			// Need to do binary search to seek to the previous row.
> 			perRowCost *= memo.Cost(math.Log2(rowCount))
> ```

There's still an inconsistency between `Scan` and `Sort` that will make us prefer `Sort` in some cases that we probably shouldn't: we're including all columns in the `Scan` case, but only the ordering cols in the `Sort` case. Whatever costing we choose, I think we want to prefer `Scan/RevScan` over `Sort` in every case.
___
*[pkg/sql/opt/xform/testdata/rules/scan, line 124 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27979#-LIOgxec8TKjUo8_cNI3:-LIOgxec8TKjUo8_cNI4:b3t8py0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c79174ae7ba3ab1e9e9d79ea3d2428e2a769fbb/pkg/sql/opt/xform/testdata/rules/scan#L124)):*
> ```
> SELECT s FROM a ORDER BY k DESC
> ----
> sort
> ```

How come we're sorting in this case? Seems like the previous plan is better.
___
*[pkg/sql/opt/xform/testdata/rules/scan, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27979#-LIOh69Z89pxiro98bwd:-LIOh69Z89pxiro98bwe:b-7esevx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c79174ae7ba3ab1e9e9d79ea3d2428e2a769fbb/pkg/sql/opt/xform/testdata/rules/scan#L145)):*
> ```
> SELECT k FROM a ORDER BY k DESC
> ----
> sort
> ```

Ditto here.
___
*[pkg/sql/opt/xform/testdata/rules/scan, line 195 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27979#-LIOh7JV2dPK6KL3LRBy:-LIOh7JV2dPK6KL3LRBz:b-1kzc9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c79174ae7ba3ab1e9e9d79ea3d2428e2a769fbb/pkg/sql/opt/xform/testdata/rules/scan#L195)):*
> ```
> SELECT s,i,k,j FROM a ORDER BY s ASC, i ASC, k DESC
> ----
> sort
> ```

And here.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27979)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/xform/coster.go, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27979#-LIQsNOB4D3lS2Ni2Y78:-LIQsNOC26zkv_ZUdHet:budzf5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/0dc3c3b3d704a3fd9cea9ac1b3dc7d12144181cb/pkg/sql/opt/xform/coster.go#L127)):*
> ```Go
> 
> 	// Add a tiny cost per operator to break ties.
> 	return cost + cpuCostFactor/100000
> ```

Why is it useful to add a delta to all the costs? To prefer plans with fewer operators?

**Review by rytaft — COMMENTED** [review]
I've fixed the formulas so we always prefer revscan over sort. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27979#-:-LIfiPsy1iDLiXCK5Xg-:b-sbp1xi)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/xform/coster.go, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27979#-LIQsNOB4D3lS2Ni2Y78:-LIfi8kX-Yfq-jNKjeMP:bfconha) ([raw file](https://github.com/cockroachdb/cockroach/blob/0dc3c3b3d704a3fd9cea9ac1b3dc7d12144181cb/pkg/sql/opt/xform/coster.go#L127)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Why is it useful to add a delta to all the costs? To prefer plans with fewer operators?
</blockquote></details>

Exactly - I added a comment. This is necessary to ensure Limit is always pushed into Scan, and revscan is always preferred over Scan+Sort
___
*[pkg/sql/opt/xform/coster.go, line 135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27979#-LIOhGc0-HYL81x4ccMV:-LIfhRaG2CKgRQkJaj2y:bgx5v9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c79174ae7ba3ab1e9e9d79ea3d2428e2a769fbb/pkg/sql/opt/xform/coster.go#L135)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Why `rowCount > 2`?
</blockquote></details>

I added the check that `rowCount` is > 2 so `math.Log2(rowCount)` is always > 1, and therefore `cost` is always at least `memo.Cost(rowCount) * perRowCost`.

But now I've changed this logic to add rather than multiply the perRowCost, so it's not relevant anymore.
___
*[pkg/sql/opt/xform/coster.go, line 155 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27979#-LIOhhSN8r8KN6G3_GVd:-LIfi4Ew8pd6yKebwOQU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c79174ae7ba3ab1e9e9d79ea3d2428e2a769fbb/pkg/sql/opt/xform/coster.go#L155)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

There's still an inconsistency between `Scan` and `Sort` that will make us prefer `Sort` in some cases that we probably shouldn't: we're including all columns in the `Scan` case, but only the ordering cols in the `Sort` case. Whatever costing we choose, I think we want to prefer `Scan/RevScan` over `Sort` in every case.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/rules/scan, line 124 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27979#-LIOgxec8TKjUo8_cNI3:-LIfiL6lDG6ZaHEnjjTL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c79174ae7ba3ab1e9e9d79ea3d2428e2a769fbb/pkg/sql/opt/xform/testdata/rules/scan#L124)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

How come we're sorting in this case? Seems like the previous plan is better.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/rules/scan, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27979#-LIOh69Z89pxiro98bwd:-LIfiKEhBATuE95wh025:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c79174ae7ba3ab1e9e9d79ea3d2428e2a769fbb/pkg/sql/opt/xform/testdata/rules/scan#L145)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Ditto here.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/rules/scan, line 195 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27979#-LIOh7JV2dPK6KL3LRBy:-LIfiM2s4KSH_V30vK_s:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c79174ae7ba3ab1e9e9d79ea3d2428e2a769fbb/pkg/sql/opt/xform/testdata/rules/scan#L195)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

And here.
</blockquote></details>

Done.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27979)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/xform/coster.go, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27979#-LIQsNOB4D3lS2Ni2Y78:-LIfyl6s20rcXISxpZw5:b-17ncgv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0dc3c3b3d704a3fd9cea9ac1b3dc7d12144181cb/pkg/sql/opt/xform/coster.go#L127)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Exactly - I added a comment. This is necessary to ensure Limit is always pushed into Scan, and revscan is always preferred over Scan+Sort
</blockquote></details>

It feels like adding this dummy value is a workaround for our failure to define a cost function for each operator, and we should just do that instead. For example, the `Limit` operator has to iterate over N rows, where N=its limit value.
___
*[pkg/sql/opt/xform/coster.go, line 171 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27979#-LIg1Dcn75rC7Uh-mBR8:-LIg1Dcn75rC7Uh-mBR9:b-gyswhk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7a9a2b54af977ad7dd051575b75ce1441157c7c/pkg/sql/opt/xform/coster.go#L171)):*
> ```Go
> }
> 
> // rowSortCost is the CPU cost to sort one row, which depends on the number of
> ```

Isn't this meant to be the cost of computing the sort key for one row? Or is it the cost of comparing sort keys during the sort? Should this be part of the `NlogN` cost in `computeScanCost`? Your comment makes it sound like it should, but it isn't included there.
___
*[pkg/sql/opt/xform/testdata/external/tpcc, line 747 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27979#-LIg2EDg3aGcz29jw8ZR:-LIg2EDg3aGcz29jw8ZS:bdi4suf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7a9a2b54af977ad7dd051575b75ce1441157c7c/pkg/sql/opt/xform/testdata/external/tpcc#L747)):*
> ```
>  ├── fd: ()-->(1,5,6)
>  ├── prune: (1,5,6)
>  └── index-join order
> ```

Very nice plan.

**Review by rytaft — COMMENTED** [review]
Updated based on our offline discussions to remove the dummy cost value per operator and add coster functions for the missing operators. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27979#-:-LIh1fq79cp_kWmdSlXE:b5bn4e4)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/xform/coster.go, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27979#-LIQsNOB4D3lS2Ni2Y78:-LIgyQwG7Z7RlV3VOKOV:b-4rne0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/0dc3c3b3d704a3fd9cea9ac1b3dc7d12144181cb/pkg/sql/opt/xform/coster.go#L127)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

It feels like adding this dummy value is a workaround for our failure to define a cost function for each operator, and we should just do that instead. For example, the `Limit` operator has to iterate over N rows, where N=its limit value.
</blockquote></details>

I removed the dummy value and added cost functions for each operator.
___
*[pkg/sql/opt/xform/coster.go, line 171 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27979#-LIg1Dcn75rC7Uh-mBR8:-LIgyZmt0kxNqpMqOQFL:bffdzx4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7a9a2b54af977ad7dd051575b75ce1441157c7c/pkg/sql/opt/xform/coster.go#L171)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Isn't this meant to be the cost of computing the sort key for one row? Or is it the cost of comparing sort keys during the sort? Should this be part of the `NlogN` cost in `computeScanCost`? Your comment makes it sound like it should, but it isn't included there.
</blockquote></details>

It's included now.

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27979#-:-LIhDxN4DqnbzNwEgFh4:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by rytaft — COMMENTED** [review]
Thanks!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27979#-:-LIhImGR14xIGPSppMez:b-voiyyw)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27979#-:-LIi7XvgA0_FzUVrzL5c:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Pull request merged**
