### PR TITLE
indexrec: add support for inverted index recommendations (JSON/array)

### LINKED ISSUE #73990: indexrec: add inverted index recommendations (JSON/array columns)
We do not currently recommend indexes on JSON columns and array columns, as these require inverted indexes. Given a query like this, where j is a JSON column...

```sql
SELECT * FROM t WHERE j->'a' = '1'
```

...we should recommend an inverted index on j.

### PR DESCRIPTION
**Pull request by nehageorge**
**indexrec: add support for inverted index recommendations (JSON/array)**

This commit adds support for inverted index recommendations. Previously, we were
unable to recommend indexes on JSON and array columns, which was inadequate
because we can index these columns with an inverted index. Note that spatial
index recommendations are not added in this commit.

Release note: None

**opttester: return error for index candidates/recommendations**

Previously, errors were ignored for index candidate and
index recommendation tests, which is not desired. We now
return any errors to the function caller.

Release note: None

### CODE REVIEW

**Comment by nehageorge** [comment]
@rytaft @mgartner There is an interesting issue with this. It is unable to be tested because of the extra "inverted column" that needs to be added to the table. There is a bounds checking issue with the test catalog as it is unable to `OptimizeWithTables` because of an `index out of range` error on the table columns. However, when testing manually and running `EXPLAIN` in the CLI, it works as expected.

There are two ways I think we can remedy this, let me know your thoughts:

1. Do not create a new inverted column on the table and set the inverted column ordinal to 0 always (or to the inverted source column ordinal), meaning that that the optimizer will not be able to see the actual `InvertedColumn`. When I did this, I was able to get inverted index recommendations. However, I don't know if it is important for the optimizer to be able to see the actual inverted bytes column, instead of an arbitrary column, when it reads the `InvertedColumn`. 
2. Modify the test catalog to be able to support this. This would require some new functions to modify existing test tables, and it seems like quite an involved change.

**Comment by mgartner** [comment]
> Do not create a new inverted column on the table and set the inverted column ordinal to 0 always

I wouldn't advise this because I don't think you'll get logically correct plans. Even if they are logically correct, they might not be the same plans that you'd get if the inverted index actually existed.

> Modify the test catalog to be able to support this. This would require some new functions to modify existing test tables, and it seems like quite an involved change.

The test catalog already adds these inverted columns [here](https://github.com/cockroachdb/cockroach/blob/08435c31bc071e950bff96706a6e951284879fb2/pkg/sql/opt/testutils/testcat/create_table.go#L1021-L1039). In the real catalog it happens [here](https://github.com/cockroachdb/cockroach/blob/7e3a3e25dd70d9a12afdd441969ef303a207ca32/pkg/sql/opt_catalog.go#L807-L827). Unless I'm confused, I think you'd have to add a column to the hypothetical tables for each hypothetical inverted index. I don't think you'd need to change the test catalog.

**Comment by nehageorge** [comment]
This is now ready for review, with support for JSON/array column inverted indexes, but not spatial indexes.

**Review by rytaft — COMMENTED** [review]
Nice!

> Reviewed 28 of 28 files at r1, 7 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-:-Mr7z8sV2BxbnZl77sYM:b-83sjoh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @nehageorge)

___
*[pkg/sql/opt/indexrec/hypothetical_index.go, line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-Mr7twBlEcxraUFRcaSo:-Mr7twBmA0e_7Jp3rl9m:b-gjtuhi) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f558291f0ceba78a077258f27a804942a7b1101/pkg/sql/opt/indexrec/hypothetical_index.go#L141)):*
> ```Go
> // NonInvertedPrefixColumnCount is part of the cat.Index interface.
> func (hi *hypotheticalIndex) NonInvertedPrefixColumnCount() int {
> 	return len(hi.cols) - 1
> ```

should this assert that the index is inverted?
___
*[pkg/sql/opt/indexrec/testdata/index-candidates-recommendations, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-Mr7yZSV4XQLOrjmFxYs:-Mr7yZSW0AB4FOzxABu4:b-bju9dq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c4128a96afc7dea6756b0e33893cd49f91b4055/pkg/sql/opt/indexrec/testdata/index-candidates-recommendations#L18)):*
> ```
> 
> # Ensure that columns that require inverted indexes do not have candidates. This
> # is temporary until we support inverted index recommendations.
> ```

Can you add a test that we don't recommend spatial indexes?
___
*[pkg/sql/opt/indexrec/testdata/index-candidates-recommendations, line 1367 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-Mr7zNO0C65ja0UzD813:-Mr7zNO0C65ja0UzD814:b-fu2g0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/46867389392aa7dded37fa0f7eea6dc093b3576e/pkg/sql/opt/indexrec/testdata/index-candidates-recommendations#L1367)):*
> ```
>  ├── cost: 10.7379279
>  ├── fd: ()-->(1)
>  └── inner-join (zigzag t4@_hyp_1 t4@_hyp_2)
> ```

you could add another test for inverted zig zag, with a predicate like `j <@ '{"foo": "1", "bar": "2"}'`
___
*[pkg/sql/opt/indexrec/testdata/index-candidates-recommendations, line 1471 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-Mr7zfNG7E5tGOi_2_5a:-Mr7zfNG7E5tGOi_2_5b:b-ioeb7) ([raw file](https://github.com/cockroachdb/cockroach/blob/46867389392aa7dded37fa0f7eea6dc093b3576e/pkg/sql/opt/indexrec/testdata/index-candidates-recommendations#L1471)):*
> ```
>       └── filters
>            └── a:5 @> ARRAY[1] [outer=(5), immutable, constraints=(/5: (/NULL - ])]
> ```

would be good to add some other tests with other types of predicates, e.g., `j IS NULL` or `a = ARRAY[1]`

**Review by nehageorge — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73794)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/indexrec/hypothetical_index.go, line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-Mr7twBlEcxraUFRcaSo:-Mr8E90NC08NXejPw5bk:bfbq995) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f558291f0ceba78a077258f27a804942a7b1101/pkg/sql/opt/indexrec/hypothetical_index.go#L141)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

should this assert that the index is inverted?
</blockquote></details>

Good point, done!
___
*[pkg/sql/opt/indexrec/testdata/index-candidates-recommendations, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-Mr7yZSV4XQLOrjmFxYs:-Mr8ECB5CAdb6KUxsQww:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c4128a96afc7dea6756b0e33893cd49f91b4055/pkg/sql/opt/indexrec/testdata/index-candidates-recommendations#L18)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Can you add a test that we don't recommend spatial indexes?
</blockquote></details>

Done.
___
*[pkg/sql/opt/indexrec/testdata/index-candidates-recommendations, line 1367 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-Mr7zNO0C65ja0UzD813:-Mr8EE4l7F0gQUthGYXM:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/46867389392aa7dded37fa0f7eea6dc093b3576e/pkg/sql/opt/indexrec/testdata/index-candidates-recommendations#L1367)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

you could add another test for inverted zig zag, with a predicate like `j <@ '{"foo": "1", "bar": "2"}'`
</blockquote></details>

Good idea, done.
___
*[pkg/sql/opt/indexrec/testdata/index-candidates-recommendations, line 1471 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-Mr7zfNG7E5tGOi_2_5a:-Mr8EGLh3nDIRPm30LMe:bgxf81v) ([raw file](https://github.com/cockroachdb/cockroach/blob/46867389392aa7dded37fa0f7eea6dc093b3576e/pkg/sql/opt/indexrec/testdata/index-candidates-recommendations#L1471)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

would be good to add some other tests with other types of predicates, e.g., `j IS NULL` or `a = ARRAY[1]`
</blockquote></details>

Added some more tests, including those mentioned. These ones don't have index recommendations (only index candidates) but it is still nice to see for completeness.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r4, 7 of 7 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-:-Mr8FO1j8Y0MM6_LqXYe:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @nehageorge)

___
*[pkg/sql/opt/indexrec/testdata/index-candidates-recommendations, line 1522 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-Mr8Elp95p0YdQ6zbS5u:-Mr8EhRr8pVolKljq5Br:bjh6l6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c2f76f07ee792f3288266906ab4c24bda157880/pkg/sql/opt/indexrec/testdata/index-candidates-recommendations#L1522)):*
> ```
>       └── filters
>            └── a:5 = ARRAY[1] [outer=(5), constraints=(/5: [/ARRAY[1] - /ARRAY[1]]; tight), fd=()-->(5)]
> ```

Would be good to check that you don't suggest replacing an existing inverted index (both full and partial)

**Review by nehageorge — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73794)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/indexrec/testdata/index-candidates-recommendations, line 1522 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-Mr8Elp95p0YdQ6zbS5u:-Mr8M53bBARmSYt1kjg1:b-a2aspk) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c2f76f07ee792f3288266906ab4c24bda157880/pkg/sql/opt/indexrec/testdata/index-candidates-recommendations#L1522)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Would be good to check that you don't suggest replacing an existing inverted index (both full and partial)
</blockquote></details>

Good point. That test already exists for full inverted indexes on line 1596, but added that test for partial inverted indexes and partial unique indexes.

**Review by mgartner — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r5, 27 of 27 files at r7, 26 of 26 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73794)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nehageorge and @rytaft)

___
*[pkg/sql/opt/metadata.go, line 593 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-Mr8NYOb0RXcCL8oLoUo:-Mr8NYOb0RXcCL8oLoUp:b-ov5aod) ([raw file](https://github.com/cockroachdb/cockroach/blob/4030242272fcde90d220122587c22a612721446a/pkg/sql/opt/metadata.go#L593)):*
> ```Go
> 	for i := range md.tables {
> 		if tab, ok := tables[md.tables[i].Table.ID()]; ok {
> 			// Add any new inverted columns to the metadata.
> ```

nit: This confused me so maybe it's worthy of an explanation that any columns that were added to the end of a hypothetical table are inverted columns.
___
*[pkg/sql/opt/indexrec/hypothetical_index.go, line 153 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-Mr8GeI4AE4b72ZVwuEX:-Mr8GeI513bcJpPO9a0O:bzci4y6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c2f76f07ee792f3288266906ab4c24bda157880/pkg/sql/opt/indexrec/hypothetical_index.go#L153)):*
> ```Go
> 	if hi.IsInverted() && i == (len(hi.cols)-1) {
> 		return hi.InvertedColumn()
> 	}
> ```

Is this change necessary? I think this is the same as `return hi.cols[i]` which is done at the bottom of the function.
___
*[pkg/sql/opt/indexrec/hypothetical_table.go, line 44 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-Mr8HsUP2gs67q7XdRT3:-Mr8HsUP2gs67q7XdRT4:b-fbyn7b) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c2f76f07ee792f3288266906ab4c24bda157880/pkg/sql/opt/indexrec/hypothetical_table.go#L44)):*
> ```Go
> 		for _, index := range indexes {
> 			indexOrd := hypTable.Table.IndexCount() + len(hypIndexes)
> 			lastKeyCol := index[len(index)-1]
> ```

nit: `len(index)` is a bit confusing. Maybe `index` is better named `indexCols`?
___
*[pkg/sql/opt/indexrec/testdata/index-candidates-recommendations, line 1387 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-Mr8M8gM9d0U9v-3lnVx:-Mr8M8gN9uYoxH5y6RMU:bhb7jad) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c2f76f07ee792f3288266906ab4c24bda157880/pkg/sql/opt/indexrec/testdata/index-candidates-recommendations#L1387)):*
> ```
>  (k)
>  (k, i)
>  (k, i, j)
> ```

I'm not sure they'd ever lead to better plans, but I expected to see `(i, j)` and `(k, j)` here too. Any ideas why they don't appear in the candidates?
___
*[pkg/sql/opt/indexrec/testdata/index-candidates-recommendations, line 1404 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-Mr8LmM18j3jZGA1nrlZ:-Mr8LmM18j3jZGA1nrl_:b-e784e) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c2f76f07ee792f3288266906ab4c24bda157880/pkg/sql/opt/indexrec/testdata/index-candidates-recommendations#L1404)):*
> ```
>  ├── cost: 10.7379279
>  ├── fd: ()-->(1)
>  └── inner-join (zigzag t4@_hyp_1 t4@_hyp_2)
> ```

I'm a bit surprised that this zig-zag join is chosen over an inverted scan on an index with `(k, i, j)`, but I supposed it is dependent on the statistics of the table. If the table were large and `j <@ '{"foo": "1"}'` was very selective, then an inverted scan would probably be selected.
___
*[pkg/sql/opt/indexrec/testdata/index-candidates-recommendations, line 1670 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-Mr8Ml6D-Q9rtptKhHhd:-Mr8Ml6D-Q9rtptKhHhe:b-wpjiox) ([raw file](https://github.com/cockroachdb/cockroach/blob/05dee36b6d9628c57110c11fbd93a1b03f56b7df/pkg/sql/opt/indexrec/testdata/index-candidates-recommendations#L1670)):*
> ```
> 
> index-recommendations
> SELECT j FROM t4 WHERE j->'a' = '1' AND i > 1
> ```

An inverted index on `(i, j)` wouldn't be used here because `i` is not held constant. I think you'll want to change the inverted index to something like `CREATE INVERTED INDEX partial_inverted_idx ON t4 (j) WHERE i = 1` and the query to `SELECT j FROM t4 WHERE j->'a' = '1' AND i = 1`.

**Review by nehageorge — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73794)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/metadata.go, line 593 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-Mr8NYOb0RXcCL8oLoUo:-Mr8dY_-1_6hnKAkC9ER:b-s18o2k) ([raw file](https://github.com/cockroachdb/cockroach/blob/4030242272fcde90d220122587c22a612721446a/pkg/sql/opt/metadata.go#L593)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: This confused me so maybe it's worthy of an explanation that any columns that were added to the end of a hypothetical table are inverted columns.
</blockquote></details>

Added a more verbose explanation, done.
___
*[pkg/sql/opt/indexrec/hypothetical_index.go, line 153 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-Mr8GeI4AE4b72ZVwuEX:-Mr8d_xs57f5dRsk5ZER:b-yhgk6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c2f76f07ee792f3288266906ab4c24bda157880/pkg/sql/opt/indexrec/hypothetical_index.go#L153)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Is this change necessary? I think this is the same as `return hi.cols[i]` which is done at the bottom of the function.
</blockquote></details>

Good point, I missed this, fixed.
___
*[pkg/sql/opt/indexrec/hypothetical_table.go, line 44 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-Mr8HsUP2gs67q7XdRT3:-Mr8deV55hnvu6jeUvbK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c2f76f07ee792f3288266906ab4c24bda157880/pkg/sql/opt/indexrec/hypothetical_table.go#L44)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: `len(index)` is a bit confusing. Maybe `index` is better named `indexCols`?
</blockquote></details>

Done.
___
*[pkg/sql/opt/indexrec/testdata/index-candidates-recommendations, line 1387 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-Mr8M8gM9d0U9v-3lnVx:-Mr8dfwCDqpm_unLQnhn:b-d1vlqy) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c2f76f07ee792f3288266906ab4c24bda157880/pkg/sql/opt/indexrec/testdata/index-candidates-recommendations#L1387)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I'm not sure they'd ever lead to better plans, but I expected to see `(i, j)` and `(k, j)` here too. Any ideas why they don't appear in the candidates?
</blockquote></details>

I wouldn't have expected these candidates because we only create one multi-column inverted index per inverted column, which is a multi-column index on `(all equality columns) + (inverted column)`. However, I modified the code to add these candidates since I don't see the harm in having them (by also adding candidates for `(single equality column) + (inverted column)`).  Although it is not useful here, there could potentially be a plan where this is useful. 
___
*[pkg/sql/opt/indexrec/testdata/index-candidates-recommendations, line 1404 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-Mr8LmM18j3jZGA1nrlZ:-Mr8egbo0w0P7jiGrKZS:bdsjkoe) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c2f76f07ee792f3288266906ab4c24bda157880/pkg/sql/opt/indexrec/testdata/index-candidates-recommendations#L1404)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I'm a bit surprised that this zig-zag join is chosen over an inverted scan on an index with `(k, i, j)`, but I supposed it is dependent on the statistics of the table. If the table were large and `j <@ '{"foo": "1"}'` was very selective, then an inverted scan would probably be selected.
</blockquote></details>

Interesting. I can't see JSON/array columns in any of the `TPCC` tables to test this out. Any idea of a good way to verify this? 
___
*[pkg/sql/opt/indexrec/testdata/index-candidates-recommendations, line 1670 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-Mr8Ml6D-Q9rtptKhHhd:-Mr8eu9R4uTfcQl3bHTG:b-1bx59h) ([raw file](https://github.com/cockroachdb/cockroach/blob/05dee36b6d9628c57110c11fbd93a1b03f56b7df/pkg/sql/opt/indexrec/testdata/index-candidates-recommendations#L1670)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

An inverted index on `(i, j)` wouldn't be used here because `i` is not held constant. I think you'll want to change the inverted index to something like `CREATE INVERTED INDEX partial_inverted_idx ON t4 (j) WHERE i = 1` and the query to `SELECT j FROM t4 WHERE j->'a' = '1' AND i = 1`.
</blockquote></details>

True, but an inverted index on `(j)` could still be used. The point here was to test that this inverted index is not recommended and that we scan our partial index, which was conveyed to my knowledge. However, I made the change you suggested to make it even more clear.

**Review by rytaft — APPROVED** [review]
> Reviewed 6 of 6 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73794)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Review by mgartner — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-:-Mr9R0514s3m5-4l3Jsk:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @nehageorge)

___
*[pkg/sql/opt/indexrec/testdata/index-candidates-recommendations, line 1387 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-Mr8M8gM9d0U9v-3lnVx:-Mr9MajtC_nPtmMS1-1H:b-89q77x) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c2f76f07ee792f3288266906ab4c24bda157880/pkg/sql/opt/indexrec/testdata/index-candidates-recommendations#L1387)):*
<details><summary><i>Previously, nehageorge wrote…</i></summary><blockquote>

I wouldn't have expected these candidates because we only create one multi-column inverted index per inverted column, which is a multi-column index on `(all equality columns) + (inverted column)`. However, I modified the code to add these candidates since I don't see the harm in having them (by also adding candidates for `(single equality column) + (inverted column)`).  Although it is not useful here, there could potentially be a plan where this is useful. 
</blockquote></details>

Cool!
___
*[pkg/sql/opt/indexrec/testdata/index-candidates-recommendations, line 1404 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-Mr8LmM18j3jZGA1nrlZ:-Mr9Op9U-5lKFSMUIPSL:bxx5fsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c2f76f07ee792f3288266906ab4c24bda157880/pkg/sql/opt/indexrec/testdata/index-candidates-recommendations#L1404)):*
<details><summary><i>Previously, nehageorge wrote…</i></summary><blockquote>

Interesting. I can't see JSON/array columns in any of the `TPCC` tables to test this out. Any idea of a good way to verify this? 
</blockquote></details>

I was able to get the optimizer to prefer an inverted scan by changing the query filter a bit and making the `k = 1 AND i = 2` condition have low selectivity. But I couldn't manage to get the optimizer to prefer the inverted scan with the `j <@ '{"foo": 1}'` filter:

```
demo@127.0.0.1:26257/defaultdb> CREATE TABLE t (k INT, i INT, f FLOAT, j JSON);
CREATE TABLE

demo@127.0.0.1:26257/defaultdb> CREATE INDEX ON t (k) STORING (i, f, j);
CREATE INDEX

demo@127.0.0.1:26257/defaultdb> CREATE INDEX ON t (i) STORING (k, f, j);
CCREATE INDEX

demo@127.0.0.1:26257/defaultdb> CREATE INVERTED INDEX ON t (k, i, j);
CREATE INDEX

demo@127.0.0.1:26257/defaultdb> INSERT INTO t SELECT (random()*10)::INT, (random()*10)::INT, random(), '{"bar": 2}' FROM generate_series(1, 100000);
INSERT 100000

demo@127.0.0.1:26257/defaultdb> INSERT INTO t VALUES (1, 2, 0.5, '{"foo": 1}');
INSERT 1

demo@127.0.0.1:26257/defaultdb> ANALYZE t;
ANALYZE

demo@127.0.0.1:26257/defaultdb> EXPLAIN SELECT k, f FROM t WHERE k = 1 AND i = 2 AND
 j->'foo' = '1';
                                        info
------------------------------------------------------------------------------------
-
  distribution: local
  vectorized: true

  • index join
  │ estimated row count: 107
  │ table: t@primary
  │
  └── • scan
        estimated row count: 0 (<0.01% of the table; stats collected 3 seconds ago)
        table: t@t_k_i_j_idx
        spans: 1 span
(11 rows)

demo@127.0.0.1:26257/defaultdb> EXPLAIN SELECT k, f FROM t WHERE k = 1 AND i = 2 AND j <@ '{"foo": 1}';

                          info
---------------------------------------------------------
  distribution: full
  vectorized: true

  • zigzag join
    estimated row count: 0
    pred: ((k = 1) AND (i = 2)) AND (j <@ '{"foo": 1}')
    left table: t@t_k_idx
    left columns: (k, i, f, j)
    left fixed values: 1 column
    right table: t@t_i_idx
    right columns: ()
    right fixed values: 1 column
(12 rows)
```

In any case, there's nothing you need to change. This is outside the realm of index recommendations and more dependent on the optimization of the query.
___
*[pkg/sql/opt/indexrec/testdata/index-candidates-recommendations, line 1670 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-Mr8Ml6D-Q9rtptKhHhd:-Mr9Q1eY-CMOD5eutEbR:b-k6f79) ([raw file](https://github.com/cockroachdb/cockroach/blob/05dee36b6d9628c57110c11fbd93a1b03f56b7df/pkg/sql/opt/indexrec/testdata/index-candidates-recommendations#L1670)):*
<details><summary><i>Previously, nehageorge wrote…</i></summary><blockquote>

True, but an inverted index on `(j)` could still be used. The point here was to test that this inverted index is not recommended and that we scan our partial index, which was conveyed to my knowledge. However, I made the change you suggested to make it even more clear. 
</blockquote></details>

I see. But an inverted index on `(j) WHERE i > 1` will likely perform much better than an inverted index on `(j)`, so the latter would likely not be picked. By change the query condition and partial index predicate to `i = 1`, the index on `(j) WHERE i > 1` is now compared to an index on `(i, j)` which is a more fair.

**Review by nehageorge — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73794)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @nehageorge)

___
*[pkg/sql/opt/indexrec/testdata/index-candidates-recommendations, line 1404 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-Mr8LmM18j3jZGA1nrlZ:-MrNC-5d0xnx4PiZ29yy:brqw03y) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c2f76f07ee792f3288266906ab4c24bda157880/pkg/sql/opt/indexrec/testdata/index-candidates-recommendations#L1404)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I was able to get the optimizer to prefer an inverted scan by changing the query filter a bit and making the `k = 1 AND i = 2` condition have low selectivity. But I couldn't manage to get the optimizer to prefer the inverted scan with the `j <@ '{"foo": 1}'` filter:

```
demo@127.0.0.1:26257/defaultdb> CREATE TABLE t (k INT, i INT, f FLOAT, j JSON);
CREATE TABLE

demo@127.0.0.1:26257/defaultdb> CREATE INDEX ON t (k) STORING (i, f, j);
CREATE INDEX

demo@127.0.0.1:26257/defaultdb> CREATE INDEX ON t (i) STORING (k, f, j);
CCREATE INDEX

demo@127.0.0.1:26257/defaultdb> CREATE INVERTED INDEX ON t (k, i, j);
CREATE INDEX

demo@127.0.0.1:26257/defaultdb> INSERT INTO t SELECT (random()*10)::INT, (random()*10)::INT, random(), '{"bar": 2}' FROM generate_series(1, 100000);
INSERT 100000

demo@127.0.0.1:26257/defaultdb> INSERT INTO t VALUES (1, 2, 0.5, '{"foo": 1}');
INSERT 1

demo@127.0.0.1:26257/defaultdb> ANALYZE t;
ANALYZE

demo@127.0.0.1:26257/defaultdb> EXPLAIN SELECT k, f FROM t WHERE k = 1 AND i = 2 AND
 j->'foo' = '1';
                                        info
------------------------------------------------------------------------------------
-
  distribution: local
  vectorized: true

  • index join
  │ estimated row count: 107
  │ table: t@primary
  │
  └── • scan
        estimated row count: 0 (<0.01% of the table; stats collected 3 seconds ago)
        table: t@t_k_i_j_idx
        spans: 1 span
(11 rows)

demo@127.0.0.1:26257/defaultdb> EXPLAIN SELECT k, f FROM t WHERE k = 1 AND i = 2 AND j <@ '{"foo": 1}';

                          info
---------------------------------------------------------
  distribution: full
  vectorized: true

  • zigzag join
    estimated row count: 0
    pred: ((k = 1) AND (i = 2)) AND (j <@ '{"foo": 1}')
    left table: t@t_k_idx
    left columns: (k, i, f, j)
    left fixed values: 1 column
    right table: t@t_i_idx
    right columns: ()
    right fixed values: 1 column
(12 rows)
```

In any case, there's nothing you need to change. This is outside the realm of index recommendations and more dependent on the optimization of the query.
</blockquote></details>

Cool!!
___
*[pkg/sql/opt/indexrec/testdata/index-candidates-recommendations, line 1670 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/73794#-Mr8Ml6D-Q9rtptKhHhd:-MrNC1LV3wDnO5vW0SoZ:b-dxcbts) ([raw file](https://github.com/cockroachdb/cockroach/blob/05dee36b6d9628c57110c11fbd93a1b03f56b7df/pkg/sql/opt/indexrec/testdata/index-candidates-recommendations#L1670)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I see. But an inverted index on `(j) WHERE i > 1` will likely perform much better than an inverted index on `(j)`, so the latter would likely not be picked. By change the query condition and partial index predicate to `i = 1`, the index on `(j) WHERE i > 1` is now compared to an index on `(i, j)` which is a more fair.
</blockquote></details>

Makes sense.

**Comment by nehageorge** [comment]
TFTRs!

bors r+

**Pull request merged**
