### PR TITLE
design: update linearizability section

### PR DESCRIPTION
**Pull request by tbg**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9644)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm: but wait for el hefe 

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9644#-:-KSwRBfZWTmWvy0VjB_C:b-u39qgx)*

**Comment by a-robinson** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[docs/design.md, line 478 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9644#-KSwWZfrrKAsjXSkeRvm:-KSwWZfrrKAsjXSkeRvn:bnwg0s8) ([raw file](https://github.com/cockroachdb/cockroach/blob/18e6ce9308383c2c7ab26d7537531dcd6652bea1/docs/design.md#L478)):*
> ```Markdown
> Roughly speaking, the gap between linearizability and CockroachDB's default
> isolation level (which gives serializable transactions) is that with
> linearizable transactions, a phenomenon called <i>temporal reverse</i> is
> ```

Is "temporal reverse" a real term?

If you Google ["temporal reverse" linearizability], there are only 5 results, only one of which isn't derived from this document.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9644#-:-KSwXESoA-6f6qGs3fPL:bnfp4nl)*

**Comment by tschottdorf** [comment]
Reworded a bit. PTAL and then I'll merge.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/design.md, line 478 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9644#-KSwWZfrrKAsjXSkeRvm:-KSwshbiwoiLc8XPRcf2:b-cfa5q2) ([raw file](https://github.com/cockroachdb/cockroach/blob/18e6ce9308383c2c7ab26d7537531dcd6652bea1/docs/design.md#L478)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> Is "temporal reverse" a real term?
> 
> If you Google ["temporal reverse" linearizability], there are only 5 results, only one of which isn't derived from this document.
</details>
Good point, avoiding the term.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9644#-:-KSwsq-1xG3QVhPLRWcP:b-3q6w1e)*

**Comment by a-robinson** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9644#-:-KSx3tmS7ybiw2yNTzDw:bnfp4nl)*

**Pull request merged**
