### PR TITLE
ui: change the error case from "no lease" to "invalid lease"

### PR DESCRIPTION
**Pull request by BramGruneir**
The first commit does the rename which addresses #18055.

While I was in there, it seemed appropriate to also fix-up the problem ranges page which clearly needed some love.  There's now a loading spinner and errors are displayed and handled better.
The second commit does this.

### CODE REVIEW

**Comment by BramGruneir** [comment]
Bah, just realized 'error case' was a poor name in the commit and pr title.  It should be range problem type.  I'm going to leave it unless there's an objection.

**Comment by couchand** [comment]
:lgtm: modulo the loading conditions

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/ui/src/views/reports/containers/problemRanges/connectionsTable.tsx, line 57 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23920#-L7f8KryUpTKOFhc23ib:-L7f8KryUpTKOFhc23ic:b-oun42j) ([raw file](https://github.com/cockroachdb/cockroach/blob/244bd333da46a7edcc2104ccf7fd20844a244b4b/pkg/ui/src/views/reports/containers/problemRanges/connectionsTable.tsx#L57)):*
> ```XML
>   const { problemRanges } = props;
>   // lastError is already handled by ProblemRanges component.
>   if (_.isNil(problemRanges) ||
> ```

i'm pretty sure the initial state is an object so this isn't strictly necessary

---

*[pkg/ui/src/views/reports/containers/problemRanges/connectionsTable.tsx, line 58 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23920#-L7f8cAvTPBvZY1QCu9K:-L7f8cAvTPBvZY1QCu9L:bfyabuh) ([raw file](https://github.com/cockroachdb/cockroach/blob/244bd333da46a7edcc2104ccf7fd20844a244b4b/pkg/ui/src/views/reports/containers/problemRanges/connectionsTable.tsx#L58)):*
> ```XML
>   // lastError is already handled by ProblemRanges component.
>   if (_.isNil(problemRanges) ||
>     problemRanges.inFlight ||
> ```

our current thinking is to ignore `inFlight`/`valid` to avoid flicker

---

*[pkg/ui/src/views/reports/containers/problemRanges/index.tsx, line 175 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23920#-L7fAzvp8NTOqwQ2Jykx:-L7fAzvp8NTOqwQ2Jyky:bel9i32) ([raw file](https://github.com/cockroachdb/cockroach/blob/244bd333da46a7edcc2104ccf7fd20844a244b4b/pkg/ui/src/views/reports/containers/problemRanges/index.tsx#L175)):*
> ```XML
>         <h1>Problem Ranges Report</h1>
>         <Loading
>           loading={!this.props.problemRanges || this.props.problemRanges.inFlight}
> ```

likewise with the loading condition

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23920#-:-L7fB2lsm_qI9nbAtFFi:b7nmkg6)*

**Comment by BramGruneir** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/ui/src/views/reports/containers/problemRanges/connectionsTable.tsx, line 57 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23920#-L7f8KryUpTKOFhc23ib:-L7gS9giAhhIJPgPrUc1:b8jhoe7) ([raw file](https://github.com/cockroachdb/cockroach/blob/244bd333da46a7edcc2104ccf7fd20844a244b4b/pkg/ui/src/views/reports/containers/problemRanges/connectionsTable.tsx#L57)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

i'm pretty sure the initial state is an object so this isn't strictly necessary
</blockquote></details>

Ah, you're right.  It is a hold over from when this was already using `.data`.  I can remove it.

---

*[pkg/ui/src/views/reports/containers/problemRanges/connectionsTable.tsx, line 58 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23920#-L7f8cAvTPBvZY1QCu9K:-L7gSG7jKdQsmAWKUcZA:b57vvzg) ([raw file](https://github.com/cockroachdb/cockroach/blob/244bd333da46a7edcc2104ccf7fd20844a244b4b/pkg/ui/src/views/reports/containers/problemRanges/connectionsTable.tsx#L58)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

our current thinking is to ignore `inFlight`/`valid` to avoid flicker
</blockquote></details>

`valid` I just avoid.
But there is no chance of flicker here since this is only called once per page load and a lot of the other debug pages use it as well.  I'd rather stick to match the other debug pages and fix them all at once if this is an issue.

---

*[pkg/ui/src/views/reports/containers/problemRanges/index.tsx, line 175 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23920#-L7fAzvp8NTOqwQ2Jykx:-L7gSxi_H6Q_pvTV5ire:b-s1mqin) ([raw file](https://github.com/cockroachdb/cockroach/blob/244bd333da46a7edcc2104ccf7fd20844a244b4b/pkg/ui/src/views/reports/containers/problemRanges/index.tsx#L175)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

likewise with the loading condition
</blockquote></details>

see my other comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23920)*

**Comment by couchand** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23920)*

**Comment by BramGruneir** [comment]
Removed the inFlight and cleaned up the loading conditions.  

We should move the selection and key functions for all keyed cached data reducers into the keyedCacheDataReducer itself.  This would stop us from having to export the key function and ensure we always have an object.

---

Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/ui/src/views/reports/containers/problemRanges/connectionsTable.tsx, line 57 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23920#-L7f8KryUpTKOFhc23ib:-L82ZaMPdufoaZtCcTv7:bfuajjk) ([raw file](https://github.com/cockroachdb/cockroach/blob/244bd333da46a7edcc2104ccf7fd20844a244b4b/pkg/ui/src/views/reports/containers/problemRanges/connectionsTable.tsx#L57)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Ah, you're right.  It is a hold over from when this was already using `.data`.  I can remove it.
</blockquote></details>

Actually, this can still be nil. 

This CachedDataReducerState is pulled from an array.  It is possible for it to not exist at all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23920#-:-L83Id-kJvFu1LbLzMnX:b-xhrvpm)*

**Comment by couchand** [comment]
:lgtm: thanks!

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23920#-:-L83PSWB7rRa0HSZj1NY:brfqlux)*

**Pull request merged**
