### PR TITLE
asim: simulate recovery actions

### LINKED ISSUE #90141: asim: add allocator repair actions
The `asim` pkg currently mocks [the replicate queue ](https://github.com/cockroachdb/cockroach/blob/e74dd712305c5ed514bcb3edb8e3746efc3f1fe6/pkg/kv/kvserver/asim/queue/replicate_queue.go#L1-L1) and supports `AllocatorConsiderRebalance` action only. It also misses several crucial components of the replicate queue code. This issue is to add support for every allocator action, via the replicate queue in the simulator.

```
AllocatorNoop
AllocatorRemoveVoter
AllocatorRemoveNonVoter
AllocatorAddVoter
AllocatorAddNonVoter
AllocatorReplaceDeadVoter
AllocatorReplaceDeadNonVoter
AllocatorRemoveDeadVoter
AllocatorRemoveDeadNonVoter
AllocatorReplaceDecommissioningVoter
AllocatorReplaceDecommissioningNonVoter
AllocatorRemoveDecommissioningVoter
AllocatorRemoveDecommissioningNonVoter
AllocatorRemoveLearner
+ AllocatorConsiderRebalance
AllocatorRangeUnavailable
AllocatorFinalizeAtomicReplicationChange
```

The solution can be broken into two parts.

1. Separate the decision for the replicate queue change (change replicas, transfer lease) and the application of that decision.
2. Hook the simulator replicate queue into the decision of the real replicate queue, then call the asim application of that decision.

Jira issue: CRDB-20611

### PR DESCRIPTION
**Pull request by kvoli**
Previously, it was not possible to simulate recovery actions such as
replacing a dead or decommissioning (non-)voter, as the simulator
replicate queue previously had limited support to only rebalancing. With
the changes introduced in https://github.com/cockroachdb/cockroach/pull/99247, it is now possible to simulate all
actions returned from the Allocator's `ComputeChange`.

This commit updates the simulator replicate queue to call
`ShouldPlanChange` and `PlanOneChange`, in the same manner that the
actual replicate queue does.

Note the output of  `example_rebalancing` has changed, this is expected
as the replicate queue now returns lease transfer changes, previously it
did not.

Resolves: https://github.com/cockroachdb/cockroach/issues/90141

Release note: None

### CODE REVIEW

**Comment by kvoli** [comment]
Hey @sumeerbhola, would you be interested in reviewing these simulator changes? The dependency refactor PR merged a couple days ago - so this should be good to take a look at.

lmk if you want to walk though synchronously beforehand.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 6 of 6 files at r3, 6 of 6 files at r4, 5 of 5 files at r5, 14 of 14 files at r6, 7 of 7 files at r7, 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-:-NVGOcfqAhqQHc--jT0y:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`-- commits` line 17 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVFRQCO9vyjTz3pa2ez):*
rubber-stamping this commit
___
*[`pkg/kv/kvserver/asim/queue/allocator_replica.go` line 110 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVGNlff3cyh7rKnoi5e:-NVGNlfg6YOnPtHAuKOe:b-z4pkx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/536ea5cf9b936b28408006fbd03957a2b5b2dc2f/pkg/kv/kvserver/asim/queue/allocator_replica.go#L110)):*
> ```Go
> 	// We return a hack here, using the next replica ID from the descriptor and
> 	// the current time. This is used when removing a replica to provide a grace
> 	// period for new replicas. The corresponding code in plan.findRemoveVoter
> ```

so it will always have a grace period because of `timeutil.Now()`. In reality if the grace period expired, would this replica become a candidate for rebalancing away -- I am reading the following comment in replica.go
```
		// Used to determine whether a replica is new enough that we shouldn't
		// penalize it for being slightly behind. These field gets cleared out once
		// we know that the replica has caught up.
```
___
*[`pkg/kv/kvserver/asim/queue/allocator_replica.go` line 142 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVGODja3JBY_weun5LK:-NVGODja3JBY_weun5LL:b1zumco) ([raw file](https://github.com/cockroachdb/cockroach/blob/536ea5cf9b936b28408006fbd03957a2b5b2dc2f/pkg/kv/kvserver/asim/queue/allocator_replica.go#L142)):*
> ```Go
> func (sr *SimulatorReplica) GetFirstIndex() kvpb.RaftIndex {
> 	// TODO(kvoli): We always return 2 here as RaftStatus is unimplemented.
> 	// When it is implmeneted, this may become variable.
> ```

nit: implemented
___
*[`pkg/kv/kvserver/asim/state/change.go` line 169 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVFr8hb4-4XX3q4eBfT:-NVFr8hb4-4XX3q4eBfU:b-ep585a) ([raw file](https://github.com/cockroachdb/cockroach/blob/43cf0a8115900df18a6f96e8713291a39e121234/pkg/kv/kvserver/asim/state/change.go#L169)):*
> ```Go
> 	}
> 	if addOk, revertAdd := addReplica(s, rangeID, storeID, next); !addOk {
> 		rollback = append(rollback, revertAdd)
> ```

How are these rollbacks used?

`removeReplica` and `addReplica` are populating the rollback funcs when returning true, while here we seem to be assuming that they will populate when the return value is false.
___
*[`pkg/kv/kvserver/asim/state/change.go` line 230 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVG-j405JSH6AIh8dNU:-NVG-j405JSH6AIh8dNV:btirzk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/43cf0a8115900df18a6f96e8713291a39e121234/pkg/kv/kvserver/asim/state/change.go#L230)):*
> ```Go
> 	if lhBeingRemoved {
> 		if len(targets.NonVoterPromotions) > 0 {
> 			candidateLH := StoreID(targets.NonVoterPromotions[0].StoreID)
> ```

why not write this as `nextLH = StoreID(targets.NonVoterPromotions[0].StoreID)`?
Same question below.
___
*[`pkg/kv/kvserver/asim/state/change.go` line 237 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVG-uPH2H_DZvs9miKO:-NVG-uPH2H_DZvs9miKP:bqltx9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/43cf0a8115900df18a6f96e8713291a39e121234/pkg/kv/kvserver/asim/state/change.go#L237)):*
> ```Go
> 			nextLH = candidateLH
> 		}
> 		// Couldn't find a leaseholder target, abort the change.
> ```

What about existing voters? They could become the leaseholder too, but we don't seem to consider them.
___
*[`pkg/kv/kvserver/asim/state/change.go` line 250 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVG0926AixO9PY6jPdg:-NVG0926AixO9PY6jPdh:b-nmcmn) ([raw file](https://github.com/cockroachdb/cockroach/blob/43cf0a8115900df18a6f96e8713291a39e121234/pkg/kv/kvserver/asim/state/change.go#L250)):*
> ```Go
> 	var storeNeedingSnapshot StoreID
> 	if len(targets.NonVoterAdditions) > 0 {
> 		storeNeedingSnapshot = StoreID(targets.NonVoterAdditions[0].StoreID)
> ```

what about `targets.NonVoterAdditions[1]` etc.
Oh, I see below there is an invariant on at most 1 total addition.
Can you add a code comment here.
___
*[`pkg/kv/kvserver/asim/state/change.go` line 253 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVG0EYuDs7Hwv4P3OZ5:-NVG0EYuDs7Hwv4P3OZ6:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/43cf0a8115900df18a6f96e8713291a39e121234/pkg/kv/kvserver/asim/state/change.go#L253)):*
> ```Go
> 	}
> 	if len(targets.VoterAdditions) > 0 {
> 		storeNeedingSnapshot = StoreID(targets.VoterAdditions[0].StoreID)
> ```

ditto
___
*[`pkg/kv/kvserver/asim/state/change.go` line 272 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVG0MueCYhRAe1PrOz9:-NVG0MueCYhRAe1PrOzA:bxrt4m4) ([raw file](https://github.com/cockroachdb/cockroach/blob/43cf0a8115900df18a6f96e8713291a39e121234/pkg/kv/kvserver/asim/state/change.go#L272)):*
> ```Go
> 	// +-------+--------------------------------+---------------------+
> 	// The ordering is changed slightly, so that all the final voters are added
> 	// or promoted first before removing any previous voters. This is doen so
> ```

nit: done
___
*[`pkg/kv/kvserver/asim/state/change.go` line 350 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVG17OWCoATgN-17IVm:-NVG17OWCoATgN-17IVn:b-l8472i) ([raw file](https://github.com/cockroachdb/cockroach/blob/43cf0a8115900df18a6f96e8713291a39e121234/pkg/kv/kvserver/asim/state/change.go#L350)):*
> ```Go
> 	nonVoterAdditions := targets.NonVoterAdditions
> 	if len(voterAdditions) > 1 || len(nonVoterAdditions) > 1 ||
> 		(len(voterAdditions) >= 1 && len(nonVoterAdditions) >= 1) {
> ```

is this the same as `len(voterAdditions) + len(nonVoterAdditions) >= 2`?
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 556 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVFlwOR5cFPUb-dVZ9j:-NVFlwOR5cFPUb-dVZ9k:bq7w70n) ([raw file](https://github.com/cockroachdb/cockroach/blob/2946791463fcdec107655ccfe0ff7184aaa5b3ce/pkg/kv/kvserver/asim/state/impl.go#L556)):*
> ```Go
> }
> 
> // SetSpanConfig set the span config for the Range with ID RangeID.
> ```

Comment seems stale.
... for all the ranges represented by span, splitting if necessary.
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 564 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVFmDPj1E154iQpeehK:-NVFmDPj1E154iQpeehL:bi0qt5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/2946791463fcdec107655ccfe0ff7184aaa5b3ce/pkg/kv/kvserver/asim/state/impl.go#L564)):*
> ```Go
> 	// range boundary. Split if necessary. Then apply the span config to all the
> 	// ranges contained within the span. e.g.
> 	//   ranges r1: [a, c) r2: [c, z)
> ```

are there gaps in the range spans seen by the simulator?
e.g. could the simulator only know about [a, c) and [e,z) and then when this is called with [b, f), there is no effect on [c, e) since the simulator does not know about it?
___
*[`pkg/kv/kvserver/asim/state/new_state.go` line 57 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVG41Q95L-9N6i-KSf6:-NVG41Q95L-9N6i-KSf7:bau6cbq) ([raw file](https://github.com/cockroachdb/cockroach/blob/43cf0a8115900df18a6f96e8713291a39e121234/pkg/kv/kvserver/asim/state/new_state.go#L57)):*
> ```Go
> 	total := 0
> 	for _, count := range counts {
> 		total += count
> ```

where is `total` used?
___
*[`pkg/kv/kvserver/asim/state/new_state.go` line 238 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVG3Cbr3bW1Ym71XlLP:-NVG3Cbr3bW1Ym71XlLQ:biuy6nv) ([raw file](https://github.com/cockroachdb/cockroach/blob/43cf0a8115900df18a6f96e8713291a39e121234/pkg/kv/kvserver/asim/state/new_state.go#L238)):*
> ```Go
> 	stores int, ranges int, keyspace int, replicationFactor int, rangeSize int64,
> ) RangesInfo {
> 	distribution := evenDistribution(stores)
> ```

I may be reading incorrectly, but it looks to me that this method and `RangesInfoWithReplicaCounts` are producing different kinds of floats in `distribution`. Here the value is the fraction of replicas at each store, since `evenDistribution` divides 1 by the number of stores. While the latter seems to produce the fraction of ranges at each store. e.g. if `RangesInfoWithReplicaCounts` is called with `replCounts = [5, 5, 5]` (3 stores) and `replicationFactor = 3`, then there are 5 `ranges` and `exactDistribution` will produce `distribution = [1, 1, 1]`.

Does this not matter because these are just interpreted as proportions? In which case why bother with calling `exactDistribution` since we are already given the counts, and hence the proportion.

**Review by kvoli — COMMENTED** [review]
TYFTR

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-:-NV_mfHP2Z0QPfFQzxoU:b-80sls6)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/asim/queue/allocator_replica.go` line 110 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVGNlff3cyh7rKnoi5e:-NV_GvF846ogDGovm4ld:bvubxuh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e05abf1d72eb77975a34e124c2378a05d8b5e7db/pkg/kv/kvserver/asim/queue/allocator_replica.go#L110)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

so it will always have a grace period because of `timeutil.Now()`. In reality if the grace period expired, would this replica become a candidate for rebalancing away -- I am reading the following comment in replica.go
```
		// Used to determine whether a replica is new enough that we shouldn't
		// penalize it for being slightly behind. These field gets cleared out once
		// we know that the replica has caught up.
```
</blockquote></details>

Yes, if the period expired then the last replica added to the range would be a candidate for rebalancing away/removing. Currently, it will never be a candidate in this setup.

I've added a TODO to remove the hack. 
___
*[`pkg/kv/kvserver/asim/queue/allocator_replica.go` line 142 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVGODja3JBY_weun5LK:-NV_HoVR67hXJxwb30q2:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e05abf1d72eb77975a34e124c2378a05d8b5e7db/pkg/kv/kvserver/asim/queue/allocator_replica.go#L142)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: implemented
</blockquote></details>

Fixed.
___
*[`pkg/kv/kvserver/asim/state/change.go` line 169 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVFr8hb4-4XX3q4eBfT:-NV_JAFZ7JApqcGlbwKP:b-du6c6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7c424a591d9f13edec2352d8c2909ffcbde4949/pkg/kv/kvserver/asim/state/change.go#L169)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

How are these rollbacks used?

`removeReplica` and `addReplica` are populating the rollback funcs when returning true, while here we seem to be assuming that they will populate when the return value is false.

</blockquote></details>

Good catch - these should be populated even in the success case so that if a subsequent action fails we roll everything back. I've update the usages.

The rollbacks are used to return the state to what it was prior to beginning any changes, if any operation fails in the change.

I've also included a wipe of the rollbacks once the function knows everything has completed without issue, to avoid applying the changes in the defer.
___
*[`pkg/kv/kvserver/asim/state/change.go` line 230 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVG-j405JSH6AIh8dNU:-NV_JreJ28Or7Jn1W6CR:bt3e0ke) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7c424a591d9f13edec2352d8c2909ffcbde4949/pkg/kv/kvserver/asim/state/change.go#L230)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why not write this as `nextLH = StoreID(targets.NonVoterPromotions[0].StoreID)`?
Same question below.
</blockquote></details>

Updated to `nextLH`, there was no reason.
___
*[`pkg/kv/kvserver/asim/state/change.go` line 237 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVG-uPH2H_DZvs9miKO:-NV_K1X_AHcN5Y7jpWuH:b-qp8lkv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7c424a591d9f13edec2352d8c2909ffcbde4949/pkg/kv/kvserver/asim/state/change.go#L237)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

What about existing voters? They could become the leaseholder too, but we don't seem to consider them.
</blockquote></details>

If the LH is being removed in `ChangeReplicas` then an incoming voter must take the lease. If the incoming voter can't take the lease, the lease needs to be transferred away first in a separate change, then the former leaseholder replica removed/demoted.

This is mocking the change replicas logic in a simplified form.
___
*[`pkg/kv/kvserver/asim/state/change.go` line 250 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVG0926AixO9PY6jPdg:-NV_KcW35W44AZqi2gnt:bqmjwcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7c424a591d9f13edec2352d8c2909ffcbde4949/pkg/kv/kvserver/asim/state/change.go#L250)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

what about `targets.NonVoterAdditions[1]` etc.
Oh, I see below there is an invariant on at most 1 total addition.
Can you add a code comment here.
</blockquote></details>

Added.
___
*[`pkg/kv/kvserver/asim/state/change.go` line 253 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVG0EYuDs7Hwv4P3OZ5:-NV_Kobp1voLTCujdS-2:bqmjwcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7c424a591d9f13edec2352d8c2909ffcbde4949/pkg/kv/kvserver/asim/state/change.go#L253)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Added.
___
*[`pkg/kv/kvserver/asim/state/change.go` line 272 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVG0MueCYhRAe1PrOz9:-NV_Kqn_DbF66GCjMbbD:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7c424a591d9f13edec2352d8c2909ffcbde4949/pkg/kv/kvserver/asim/state/change.go#L272)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: done
</blockquote></details>

Fixed.
___
*[`pkg/kv/kvserver/asim/state/change.go` line 350 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVG17OWCoATgN-17IVm:-NV_L2n13VNncuuhMTwz:b-gm3bbs) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7c424a591d9f13edec2352d8c2909ffcbde4949/pkg/kv/kvserver/asim/state/change.go#L350)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is this the same as `len(voterAdditions) + len(nonVoterAdditions) >= 2`?
</blockquote></details>

It is, simplified.
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 556 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVFlwOR5cFPUb-dVZ9j:-NV_M0Qj5nAQljOBhDU7:bq5wuc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad409066d0b62a8d840e47b6d68a678864105a92/pkg/kv/kvserver/asim/state/impl.go#L556)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Comment seems stale.
... for all the ranges represented by span, splitting if necessary.
</blockquote></details>

Updated comment.
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 564 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVFmDPj1E154iQpeehK:-NV_M5TO0eNGLGJo-DoE:b8i04du) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad409066d0b62a8d840e47b6d68a678864105a92/pkg/kv/kvserver/asim/state/impl.go#L564)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

are there gaps in the range spans seen by the simulator?
e.g. could the simulator only know about [a, c) and [e,z) and then when this is called with [b, f), there is no effect on [c, e) since the simulator does not know about it?
</blockquote></details>

There are no gaps in range spans, the state is initialized with the full keyspace as the first range, where any range thereafter is split off from the first range and contained by it.
___
*[`pkg/kv/kvserver/asim/state/new_state.go` line 57 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVG41Q95L-9N6i-KSf6:-NV_NKGXCQ8av-2pZtLc:bvw7wx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7c424a591d9f13edec2352d8c2909ffcbde4949/pkg/kv/kvserver/asim/state/new_state.go#L57)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

where is `total` used?
</blockquote></details>

It should be used to calculate the proportion so it sum(distribution) approx adds to 1. 
___
*[`pkg/kv/kvserver/asim/state/new_state.go` line 238 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVG3Cbr3bW1Ym71XlLP:-NV_NRbA4uRnn5amKxC2:b-61h8mr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7c424a591d9f13edec2352d8c2909ffcbde4949/pkg/kv/kvserver/asim/state/new_state.go#L238)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I may be reading incorrectly, but it looks to me that this method and `RangesInfoWithReplicaCounts` are producing different kinds of floats in `distribution`. Here the value is the fraction of replicas at each store, since `evenDistribution` divides 1 by the number of stores. While the latter seems to produce the fraction of ranges at each store. e.g. if `RangesInfoWithReplicaCounts` is called with `replCounts = [5, 5, 5]` (3 stores) and `replicationFactor = 3`, then there are 5 `ranges` and `exactDistribution` will produce `distribution = [1, 1, 1]`.

Does this not matter because these are just interpreted as proportions? In which case why bother with calling `exactDistribution` since we are already given the counts, and hence the proportion.
</blockquote></details>

I intended for it to matter, they are used to calculate the required number of ranges/leases per store. I think however it doesn't end up mattering since we add replicas greedily to stores in `RangeInfoWithDistribution`, adding to the store with the highest remaining required replicas (going negative in this case where the proportions >= 1).


I've updated the above to use total.

**Comment by kvoli** [comment]
bors r=sumeerbhola

**Comment by kvoli** [comment]
flake https://github.com/cockroachdb/cockroach/issues/99261

bors r-

**Comment by kvoli** [comment]
bors r=sumeerbhola

**Comment by kvoli** [comment]
rebased, will try again once CI goes green.

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 2 of 14 files at r14.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101745)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli)

___
*[`pkg/kv/kvserver/asim/state/change.go` line 171 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVeDHRf0BrUx0Ao7bv0:-NVeDHRf0BrUx0Ao7bv1:b-v9jgly) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1e51a5e19a65f9b4a0de2e62c195d935140516b/pkg/kv/kvserver/asim/state/change.go#L171)):*
> ```Go
> 	addOk, revertAdd := addReplica(s, rangeID, storeID, next)
> 	rollback = append(rollback, revertAdd)
> 	if !addOk {
> ```

nit: is this simply `return addOk`?
For the future, if we are in this code, I'd prefer if we remove the empty returns. It is confusing not to see what is being returned.

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101745)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/asim/state/change.go` line 171 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/101745#-NVeDHRf0BrUx0Ao7bv0:-NVeY-K9-ozaV0F-7S7e:b-pw33ar) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1e51a5e19a65f9b4a0de2e62c195d935140516b/pkg/kv/kvserver/asim/state/change.go#L171)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: is this simply `return addOk`?
For the future, if we are in this code, I'd prefer if we remove the empty returns. It is confusing not to see what is being returned.
</blockquote></details>

It is. I'll go through and update the following PR to remove empty returns - I have a preference for them for short fns with useful return value names but I'm happy to remove.

**Pull request merged**
