### PR TITLE
kvstreamer: fix a bug with incorrect processing of empty scan responses

### LINKED ISSUE #75708: sql/logictest: logic tests occasionally are timing out because of the streamer
sql/logictest.TestLogic/local-vec-off/fk/notice_on_fk_ref_col_type_mismatch [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4249825&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4249825&tab=artifacts#/) on master @ [323988fdbb0e7d3a3f90607811a9f657fb922f93](https://github.com/cockroachdb/cockroach/commits/323988fdbb0e7d3a3f90607811a9f657fb922f93):

```
Slow failing tests:
TestLogic/local-vec-off/fk/notice_on_fk_ref_col_type_mismatch - 1578.66s

Slow passing tests:
TestTenantLogic - 1383.60s
TestCCLLogic - 510.10s
TestRemoveDeadReplicas - 351.98s
TestTwoArgumentRegressionAggregateFunctions - 294.74s
TestPebbleEquivalence - 258.89s
TestFullClusterBackup - 214.74s
TestPublicSchemaMigration500Tables - 198.42s
TestRestoreMidSchemaChange - 179.41s
TestChangefeedSchemaChangeNoBackfill - 161.01s
TestAlterTableLocalityRegionalByRowError - 149.01s
TestUnsplitRanges - 132.77s
TestWebhookSink - 132.63s
TestExecBuild - 127.81s
TestRegionChangeRacingRegionalByRowChange - 124.00s
TestClusterRestoreFailCleanup - 116.46s
TestBenchmarkExpectation - 115.50s
TestBenchmarkExpectation - 114.25s
TestLearnerSnapshotFailsRollback - 92.43s
TestImportData - 91.49s
TestMultiRegionDataDriven - 90.98s
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- GOFLAGS=-json
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLogic/local-vec-off/fk/notice_on_fk_ref_col_type_mismatch.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by yuzefovich**
**kvstreamer: fix a bug with incorrect processing of empty scan responses**

Previously, the `Streamer` could get stuck indefinitely when a response
for a Scan request came back empty - namely the response neither had no
bytes inside nor ResumeSpan set (this is the case when there is no data
in the key span to scan). This would lead to `GetResults` call being
stuck thinking there are more responses to come back, and none would
show up.

This is now fixed by creating a Result with an empty Scan response
inside of it. This approach makes it easier to support Scans that span
multiple ranges and the last range has no data in it - we want to be
able to set Complete field on such an empty Result.

Since this was the only known bug with the `Streamer` implementation,
the streamer is now used by default again.

Fixes: #75708.

Release note: None

**kvstreamer: minor cleanup**

This commit replaces the last buffered channel we had in the `Streamer`
code in favor of a condition variable which simplifies the control flow
a bit.

Additionally, this commit refactors the code so that empty Get responses
are not returned which allows us to clean up `TxnKVStreamer` a bit. Care
has to be taken so that we still signal the client's goroutine waiting
for results when an empty Get response comes back (similar to the bug
fixed by the previous commit).

Also, the tracking of the "number of outstanding requests" in
`TxnKVStreamer` has been removed since it provided little value (and
probably was broken anyway).

Release note: None

### CODE REVIEW

**Review by rharding6373 — CHANGES_REQUESTED** [review]
Good fix. I have some initial comments, but still need to review most of the second commit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75888#-:-Mv9urqeEDz_i1ySxO1S:b-wv0qcc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[pkg/sql/row/kv_batch_streamer.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75888#-Mv9rw-Z707Iu9Y6NIri:-Mv9rw-Z707Iu9Y6NIrj:b-8f4rjm) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc330daf0d412402c26ccb8cd186a6a9a338943c/pkg/sql/row/kv_batch_streamer.go#L41)):*
> ```Go
> 		"Enabling this will increase the speed of lookup/index joins "+
> 		"while adhering to memory limits.",
> 	true,
> ```

Did you mean to turn this on by default in this bug fix? If so, this should be called out in the commit message at least.

Also, when it is enabled by default, it would be good to keep some test coverage where it is disabled to make sure the other code path is still operational -- unless you think that the operations that don't support the streamer yet provide sufficient coverage.
___
*[pkg/kv/kvclient/kvstreamer/streamer_test.go, line 461 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75888#-Mv9sqHwEobvoW3EjqgP:-Mv9sqHwEobvoW3EjqgQ:b8ncdpq) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc330daf0d412402c26ccb8cd186a6a9a338943c/pkg/kv/kvclient/kvstreamer/streamer_test.go#L461)):*
> ```Go
> 		var union roachpb.RequestUnion_Scan
> 		makeKey := func(pk int) []byte {
> 			return []byte{190, 137, byte(136 + pk)}
> ```

Out of curiosity...what are these magic numbers?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75888)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373 and @rytaft)

___
*[pkg/sql/row/kv_batch_streamer.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75888#-Mv9rw-Z707Iu9Y6NIri:-MvAgKEW8EAaxFlracsO:bhadqdb) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc330daf0d412402c26ccb8cd186a6a9a338943c/pkg/sql/row/kv_batch_streamer.go#L41)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Did you mean to turn this on by default in this bug fix? If so, this should be called out in the commit message at least.

Also, when it is enabled by default, it would be good to keep some test coverage where it is disabled to make sure the other code path is still operational -- unless you think that the operations that don't support the streamer yet provide sufficient coverage.
</blockquote></details>

Yes, I did mean to turn it on by default since the first commit fixes the only known issue. Updated the commit message to include this note.

I'm not really concerned about the test coverage of the "streamer off" case because that code path is essentially everything that goes through the SQL layer and touches KV whereas the streamer code path is specific to only index joins in some cases.
___
*[pkg/kv/kvclient/kvstreamer/streamer_test.go, line 461 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75888#-Mv9sqHwEobvoW3EjqgP:-MvAfyjj-1PlUH2uxLJK:bv3ogr) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc330daf0d412402c26ccb8cd186a6a9a338943c/pkg/kv/kvclient/kvstreamer/streamer_test.go#L461)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Out of curiosity...what are these magic numbers?
</blockquote></details>

These make up a `/t/primary/pk` key, added a comment.

**Review by rharding6373 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75888#-:-MvQ_uCB6usz128rL4VA:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rharding6373 and @rytaft)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
