### PR TITLE
clusterversion: start 24.2 versions

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### clusterversion: start 24.2 versions

Add 24.2 versions and set current version to `v24.2.0-alpha.00000000`.

Epic: REL-712
Epic: REL-696

#### upgrademanger: TestPostJobInfoTableQueryDuplicateJobInfo fix

We change this test to create the tenant before upgrading the system.
Otherwise the tenant starts up at the upgraded version.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
This guidance no longer seems accurate:
```
// SystemDatabaseSchemaBootstrapVersion is the system database schema version
// that should be used during bootstrap. It should be bumped up alongside any
// upgrade that creates or modifies the schema of a system table.
// NB: Don't set this to clusterversion.Latest; use a specific version instead.
var SystemDatabaseSchemaBootstrapVersion = clusterversion.V24_1_AddSpanCounts.Version()
```

I'm not sure we really need this anymore, since it can be programmatically determined?

**Comment by RaduBerinde** [comment]
*[`pkg/clusterversion/README.md` line 184 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123650#-NxPwZ-EDKbJKOpre7Ge:-NxPwZ-EDKbJKOpre7Gf:b-lcdfey) ([raw file](https://github.com/cockroachdb/cockroach/blob/1748bb43ed9cda4175adc36cb200c0986458c621/pkg/clusterversion/README.md#L184)):*
> ```Markdown
> - [ ] Add mixed version logictest config for the replaced version (`local-mixed-24.1`)
> 
> - [ ] Update the scplan rules in `pkg/sql/schemachanger/internal/rules`:
> ```

@rafiss I added some steps here for the scplan stuff if you want to take a look

**Review by celiala — APPROVED** [review]
thank you !! :lgtm: 

had a (non-blocking) question (inline) how whether we could potentially do this task with an earlier pre-release.

> Reviewed 30 of 32 files at r1, 36 of 36 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123650#-:-NxTA_qw6YacSjYuD0fc:b-uqtulh)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @RaduBerinde, @rafiss, @rail, and @renatolabs)

___
*[`-- commits` line 7 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/123650#-NxSzbIu6iXhV5Bgnm2S):*
I'm okay to just reference this single REL-696 ticket to make the linter happy[1], since these have to be done at the same time.

[1] Linter error message:
> When multiple epics are referenced in the PR body, each commit of the PR should reference the epic(s) that commit is part of and all epics listed in the commit messages should be listed in the PR body.
___
*[`pkg/clusterversion/README.md` line 170 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/123650#-NxT4fBjDVQh290cWsND:-NxT4fBk4iMdzy9-RQzM:bmp9wkx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a60e0155e2eb68964b0418be1b2e48ba557fc3/pkg/clusterversion/README.md#L170)):*
> ```Markdown
> ### M.2: Bump current version
> 
> **What**: This change advances the current release series version.
> ```

thank you for creating and keeping this runbook up-to-date! :100: :heart_decoration: 
___
*[`pkg/clusterversion/README.md` line 194 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/123650#-NxT2yiNBOmXtdWquRNK:-NxT2yiNBOmXtdWquRNL:bpc7lsh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a60e0155e2eb68964b0418be1b2e48ba557fc3/pkg/clusterversion/README.md#L194)):*
> ```Markdown
> - [ ] Create new roachtest fixtures for the previous version (see
>   `pkg/cmd/roachtest/fixtures/README.md`). Note that the version used must have
>   the final version minted (typically the `rc.1` version or later).
> ```

:thinking: the example in [pkg/cmd/roachtest/fixtures/README.md](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/fixtures/README.md) uses a beta:

```
export FIXTURE_VERSION=v23.2.0-beta.1
```

which makes me wonder whether or not we can use an earlier pre-release to generate fixtures? (or if the fixtures need a minted pre-release)?

also cc @renatolabs or @DarrylWong in case y'all have additional guidance/context here.

**Review by rail — APPROVED** [review]
:lgtm:

> Reviewed 32 of 32 files at r1, 28 of 28 files at r2, 5 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123650#-:-NxTGNPpD89-oncAJPCt:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @celiala, @DarrylWong, @RaduBerinde, @rafiss, and @renatolabs)

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123650)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @celiala, @DarrylWong, @RaduBerinde, and @renatolabs)

___
*[`pkg/sql/catalog/systemschema/system.go` line 1210 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/123650#-NxTItih5DAFEAYTpc04:-NxTItih5DAFEAYTpc05:b-qq5huv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a60e0155e2eb68964b0418be1b2e48ba557fc3/pkg/sql/catalog/systemschema/system.go#L1210)):*
> ```Go
> // SystemDatabaseSchemaBootstrapVersion is the system database schema version
> // that should be used during bootstrap. It should be bumped up alongside any
> // upgrade.
> ```

super nit: technically it would be more accurate to say "It should be bumped alongside any upgrade that has an associated migration."

but the wording you have also seems clear enough

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123650)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @celiala, @DarrylWong, and @renatolabs)

___
*[`pkg/clusterversion/README.md` line 194 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/123650#-NxT2yiNBOmXtdWquRNK:-NxTL6st1UY0JDPP16c1:b-tpk6w1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a60e0155e2eb68964b0418be1b2e48ba557fc3/pkg/clusterversion/README.md#L194)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

:thinking: the example in [pkg/cmd/roachtest/fixtures/README.md](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/fixtures/README.md) uses a beta:

```
export FIXTURE_VERSION=v23.2.0-beta.1
```

which makes me wonder whether or not we can use an earlier pre-release to generate fixtures? (or if the fixtures need a minted pre-release)?

also cc @renatolabs or @DarrylWong in case y'all have additional guidance/context here.
</blockquote></details>

I tried that before rc was available; it didn't work. They do need a minted release. The upgrade tests were waiting for 24.1 cluster version which never came - in the beta, the latest version was 23.2-something.

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123650#-:-NxTMAwO9nbDKoeiSiTC:bz5mair)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @celiala, @DarrylWong, @rafiss, and @renatolabs)

___
*[`-- commits` line 7 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/123650#-NxSzbIu6iXhV5Bgnm2S):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

I'm okay to just reference this single REL-696 ticket to make the linter happy[1], since these have to be done at the same time.

[1] Linter error message:
> When multiple epics are referenced in the PR body, each commit of the PR should reference the epic(s) that commit is part of and all epics listed in the commit messages should be listed in the PR body.
</blockquote></details>

Thanks, I'll keep it as is since it's not a required check.
___
*[`pkg/sql/catalog/systemschema/system.go` line 1210 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/123650#-NxTItih5DAFEAYTpc04:-NxTM5KV0Nv7aoCLokBA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a60e0155e2eb68964b0418be1b2e48ba557fc3/pkg/sql/catalog/systemschema/system.go#L1210)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

super nit: technically it would be more accurate to say "It should be bumped alongside any upgrade that has an associated migration."

but the wording you have also seems clear enough
</blockquote></details>

Done.

**Review by renatolabs — APPROVED** [review]
:lgtm:

Nice, thank you for this!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123650#-:-NxTNKoI8RPs1szDwZmL:bprx41f)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @celiala, @DarrylWong, @RaduBerinde, @rafiss, and @rail)

___
*[`pkg/clusterversion/README.md` line 194 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/123650#-NxT2yiNBOmXtdWquRNK:-NxTMlhj4QUe8-Ef4sjL:b-ehe843) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a60e0155e2eb68964b0418be1b2e48ba557fc3/pkg/clusterversion/README.md#L194)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I tried that before rc was available; it didn't work. They do need a minted release. The upgrade tests were waiting for 24.1 cluster version which never came - in the beta, the latest version was 23.2-something.
</blockquote></details>

Don't betas come after rcs? In any case -- that's correct, the fixtures need to be generated after the release is minted. End-to-end test upgrade tests should reflect "real" upgrades as much as possible.

**Comment by RaduBerinde** [comment]
*[`pkg/clusterversion/README.md` line 194 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/123650#-NxT2yiNBOmXtdWquRNK:-NxTOSQG68jHYDUNQHsy:bwstz8u) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a60e0155e2eb68964b0418be1b2e48ba557fc3/pkg/clusterversion/README.md#L194)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Don't betas come after rcs? In any case -- that's correct, the fixtures need to be generated after the release is minted. End-to-end test upgrade tests should reflect "real" upgrades as much as possible.
</blockquote></details>

No, rc = release candidate, it's the last designation before the actual release. Note that they are also alphabetical (alpha < beta < rc).

**Review by celiala — APPROVED** [review]
:lgtm: 

appreciate the context around fixtures - makes sense now, thank you!

> Reviewed 35 of 35 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123650#-:-NxTR6_C1IYGEi7Vjltj:b7jst8k)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (and 1 stale) (waiting on @DarrylWong, @RaduBerinde, and @rafiss)

**Comment by RaduBerinde** [comment]
TFTRs!

bors r+

**Pull request merged**
