### PR TITLE
storage/metamorphic: update clearRangeOp to not conflict with in-flight writes

### LINKED ISSUE #72476: storage/metamorphic: TestPebbleEquivalence failed
storage/metamorphic.TestPebbleEquivalence [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3688252&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3688252&tab=artifacts#/) on master @ [ed35bbe8f6e5947db6e3f2423d1aa9dde1d15804](https://github.com/cockroachdb/cockroach/commits/ed35bbe8f6e5947db6e3f2423d1aa9dde1d15804):

```
=== RUN   TestPebbleEquivalence
    test_log_scope.go:79: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestPebbleEquivalence503536829
    test_log_scope.go:80: use -show-logs to present logs inline
first run output file: /go/src/github.com/cockroachdb/cockroach/artifacts/TestPebbleEquivalence879817464/output.meta
=== CONT  TestPebbleEquivalence
    meta_test.go:205: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestPebbleEquivalence503536829
--- FAIL: TestPebbleEquivalence (525.51s)
=== RUN   TestPebbleEquivalence/engine/standard=7
check file = /go/src/github.com/cockroachdb/cockroach/artifacts/TestPebbleEquivalence879817464/output.meta
output file = /go/src/github.com/cockroachdb/cockroach/artifacts/TestPebbleEquivalence_engine_standard=7214466125/output.meta
store path = /go/src/github.com/cockroachdb/cockroach/artifacts/TestPebbleEquivalence_engine_standard=7112879432/store
    generator.go:415: mismatching output at line 42290, operation index 42190: expected truncated range to delete = "hhkmxpkvenw" - "xjtrclkeqjmndk", deleted keys = "hkuvyjjaatd", "hqxhppwu", "iusewhth", "ivxigflfcqfnbrp", "jehggympkat", "jguxpsbhh", "jjgqpnccsb", "jkgltwsfiro", "wfchcsqfgmv", "wpheiqgnudi", "wsmrtqsrbflwdwu", "wvqhpvxbfhji", "wyjxdcxcjxvova", "xdjfkdinhacx", "xhmkoowsauf"
        , got error: WriteTooOldError: write at timestamp 0.000003821,0 too old; wrote at 0.000003821,1
    --- FAIL: TestPebbleEquivalence/engine/standard=7 (30.93s)
```
<details><summary>Help</summary>
<p>
See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)Parameters in this failure:

- GOFLAGS=-parallel=4
</p>
</details>
/cc @cockroachdb/storage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestPebbleEquivalence.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by itsbilal**
This change updates clearRangeOp to only run on key spans
    that do not have any transactional writes in-progress. This more
    closely matches behaviour in KV and avoids cases where we'd trample on
    intents and other in-flight keys.

 Fixes #72476. Speculatively. Reproduction was nearly impossible.

 Release note: None.

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
Could you elaborate on what went wrong in the failing test, and what has changed to make this a problem now?
We've previously viewed the MVCC metamorphic test as something that validates some notion of low-level correctness (without being explicit about what that is) and not particularly cared about whether it preserves transactional correctness.
 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74317#-:-Ms_Btgb07yiq_rln6Nz:b-37gnmn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens)

**Comment by itsbilal** [comment]
@sumeerbhola Nothing really changed to make it a problem now. It's just a really rare occurrence of a failure - so rare I wasn't able to reproduce it, even with hundreds of tries on the same sequence of operations, same pebble config, and the same seed.

But the best theory that I could come up with, given the sequence of operations (which I've linked
[here](https://github.com/cockroachdb/cockroach/files/7808617/output-6.meta.txt) , failure is at the very bottom) is that the `delete_range` made us lose `txnDidNotUpdateMeta` tracking for one of the previous `mvcc_put`s that called `Next` on the meta timestamp and rewrote it. The failure is `error: WriteTooOldError: write at timestamp 0.000003135,0 too old; wrote at 0.000003135,1` vs the usually-successful ClearTimeRange output. The latter timestamp `0.000003135,1` must be generated by mvccPutInternal, as we don't generate timestamps with nonzero logical values in the metamorphic tests. And we could get non-deterministic behaviour of the kind that'd fail the metamorphic test if we do a set-set-singledel or so.

But now that I think about it more, the ClearRange should have sat in between any possible bad combination of sets and single deletes, making the above unlikely. I'll try thinking about this more, but even my repro attempts from today were unsuccessful, so the best bit of evidence we have is that operations file.

I could also just fix this operation to only do a `ClearRange` on key ranges that do not have any in-flight transactional writes (something we track already). That would mimic actual behaviour more closely, and would probably prevent us from investigating more spurious failures. Failing any other decisive evidence / findings, I'll probably go ahead and do that.

**Review by sumeerbhola — COMMENTED** [review]
A successful `ClearMVCCRangeAndIntents(start, end roachpb.Key)` that is called by
`delete_range("cajscynxjskw"/130, "hxijsnrrclpueev"/1286) -> ok`
should have cleared everything at all versions, as you pointed out.

I assume the failure is 
`mvcc_delete_range(engine, t1568, "ansbelemqdiao"/3136, "rpnafxcq"/3136) -> error: WriteTooOldError: write at timestamp 0.000003135,0 too old; wrote at 0.000003135,1
`
Presumably we can have such errors in the metamorphic test if a transaction that wrote to a higher timestamp (0.000003135,0) has already committed. How do we know that the error is unexpected -- I didn't see any diff in the test output across different runs? We don't even know if the key corresponding to the `WriteTooOldError` is within the bounds of the `delete_range` 
-- it would have been nice to have the key and also the timestamp assigned to each txn at the time of `txn_commit` (not sure how easy it is to plumb these through to the metamorphic test).

I am wondering if we should limit the changes now to adding some more diagnostic messages, so that we have more information when such rare failures happen.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74317#-:-MsjyLpAAT323U_22yQu:bbs7bjx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens)

**Comment by itsbilal** [comment]
Made the change to only clearRange keys not being updated. PTAL!

**Comment by itsbilal** [comment]
@sumeerbhola Sorry I only pasted the output from the failing run. In the successful run, we saw the very last line to be a successful `mvcc_clear_time_range`. The failure message shows the diff: https://github.com/cockroachdb/cockroach/issues/72476#issuecomment-1002626428

The successful output for that line was:
```
truncated range to delete = "ansbelemqdiao" - "rpnafxcq", deleted keys = "aygfkgtvew", "bfikvmhno", "bjulaqilwg", "brmaqmpnckcyts", "bstkksnpfusjg", "buccjuwesmxgd", "burmwfklkoqe", "bvqyhmtc", "bysfouaphiwh", "igpenuxowhwqtb", "jdtufxsry", "jhorvifrqcyg", "jldxpdhecnqiw", "jqsplqmrt", "jursvdaufqg", "kfnpfbpxxbv", "kykypcdtxsfblg", "llhstwgyvwka", "lvtwvdgikee", "mpjfhhvgoqu", "mwiqjleyv", "nfarsghatmc", "nmvsotbty", "nxfteiebmuk", "oadvnsupy", "oelfojdh", "ogdwxerwx", "osssqtviaece", "qbojjvjrlvp", "qhtrlctoahm", "qtnwdbxmcpsc"
```

You can see the timestamps by looking at the `txn_open` corresponding to that txn - the open transaction at that time has a timestamp of (3135,0) so (3135,1) could have only been generated by an mvccPutInternal that Next()'d it, and also updated the meta.

I do agree the WriteIntentError output should also print out the corresponding key. Making that change now.

**Comment by sumeerbhola** [comment]
Thanks for the details -- unfortunately I can't spot the artifacts here https://teamcity.cockroachdb.com/viewLog.html?buildId=4007671&tab=artifacts&showAll=true#%2F;%2F.teamcity%2Flogs;%2F.teamcity%2Fproperties;%2F.teamcity%2Fsettings

Also, where do you see the timestamp in txn_open. I only noticed
```
txn_open(3135, t1568) -> t1568
```

> You can see the timestamps by looking at the txn_open corresponding to that txn - the open transaction at that time has a timestamp of (3135,0) so (3135,1) could have only been generated by an mvccPutInternal that Next()'d it, and also updated the meta.

The (3135,1) maybe coming from the Next() call here https://github.com/cockroachdb/cockroach/blob/bd09cb7124a70ca0dde1b5aa271bcfdf691146da/pkg/storage/pebble_mvcc_scanner.go#L341 in the `MVCCScan` done by `MVCCDeleteRange`.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74317)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @jbowens)

___
*[pkg/storage/metamorphic/operations.go, line 894 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74317#-Mt3lxyaBOAlS31RLmCm:-Mt3lxyaBOAlS31RLmCn:b9k51p) ([raw file](https://github.com/cockroachdb/cockroach/blob/8270e3586c8c04daa65dc3a54d97639cc0611dc7/pkg/storage/metamorphic/operations.go#L894)):*
> ```Go
> 			// truncate the span to that range.
> 			m.txnGenerator.forEachConflict(writer, txn, key, endKey, func(conflict roachpb.Span) bool {
> 				if conflict.ContainsKey(key) {
> ```

`ForEachConflict` is finding `writtenKeySpans` that overlap, yes? So if the delete span start key is contained we need to truncate the front of this delete span and continue looking for conflicts. Else we just truncate the rear and don't worry about the fact that there could be other later spans that could be non-conflicting since the contract is that we need to delete one span, yes?
A code comment would be helpful.

What if the delete span is completely contained in a written span -- we would now have an empty span, but we are returning true. I don't quite see how continuing leads to everything being correct eventually, including the `endKey.Compare(key) < 0` code below which seems to turn an empty span into a non-empty span.
___
*[pkg/storage/metamorphic/operations.go, line 1349 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74317#-Mt3nkg-DETe508G8323:-Mt3nkg-DETe508G8324:b-avbxfm) ([raw file](https://github.com/cockroachdb/cockroach/blob/8270e3586c8c04daa65dc3a54d97639cc0611dc7/pkg/storage/metamorphic/operations.go#L1349)):*
> ```Go
> 			}
> 
> 			// forEachConflict is guaranteed to iterate over conflicts in key order,
> ```

if this is the same code can it be abstracted out?
___
*[pkg/storage/metamorphic/options.go, line 20 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74317#-Mt3k6hY31npHCFoRoHm:-Mt3k6hY31npHCFoRoHn:bqebhii) ([raw file](https://github.com/cockroachdb/cockroach/blob/8270e3586c8c04daa65dc3a54d97639cc0611dc7/pkg/storage/metamorphic/options.go#L20)):*
> ```Go
> 
> const numStandardOptions = 18
> const numRandomOptions = 5
> ```

why this change?

**Review by itsbilal — COMMENTED** [review]
Yep, the artifacts disappear after some time. But the error message is logged in the issue (as a comment, #72476) and it shows the diff. 

The first argument to `txn_open` is the txn timestamp's WallTime. We only use 0 for Logical time in the mvcc meta tests, so that txn_open is basically setting the timestamp to `(3135,0)`.

And yep, good catch. I updated #74572 to also propagate `key` for `MVCCScan` WriteTooOld errors.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74317#-:-Mt3v9oJAOANiU_M6XuO:b-f8iqg8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @sumeerbhola)

___
*[pkg/storage/metamorphic/operations.go, line 894 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74317#-Mt3lxyaBOAlS31RLmCm:-Mt3v_Ze4K0cN9KQwaE9:ba672zy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8270e3586c8c04daa65dc3a54d97639cc0611dc7/pkg/storage/metamorphic/operations.go#L894)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

`ForEachConflict` is finding `writtenKeySpans` that overlap, yes? So if the delete span start key is contained we need to truncate the front of this delete span and continue looking for conflicts. Else we just truncate the rear and don't worry about the fact that there could be other later spans that could be non-conflicting since the contract is that we need to delete one span, yes?
A code comment would be helpful.

What if the delete span is completely contained in a written span -- we would now have an empty span, but we are returning true. I don't quite see how continuing leads to everything being correct eventually, including the `endKey.Compare(key) < 0` code below which seems to turn an empty span into a non-empty span.
</blockquote></details>

Added a comment. But yes the contract is just that we need one range that doesn't conflict. I was actually not handling the "no non-conflicting span" case well; for some reason I expected `forEachConflict` to coalesce perfectly-adjacent spans but I realized that won't happen. Now I made operations that only operate on a conflicting span a noop. In practice this seems very rare.
___
*[pkg/storage/metamorphic/operations.go, line 1349 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74317#-Mt3nkg-DETe508G8323:-Mt4XimNAfvSAbMwRZvM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8270e3586c8c04daa65dc3a54d97639cc0611dc7/pkg/storage/metamorphic/operations.go#L1349)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

if this is the same code can it be abstracted out?
</blockquote></details>

Done.
___
*[pkg/storage/metamorphic/options.go, line 20 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74317#-Mt3k6hY31npHCFoRoHm:-Mt3vlxs-unnJxVa9LDz:b-kuzj9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/8270e3586c8c04daa65dc3a54d97639cc0611dc7/pkg/storage/metamorphic/options.go#L20)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why this change?
</blockquote></details>

Reverted. Not necessary anymore to fit within the timeout now that clearRangeOp is back.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74317#-:-Mt8sgPBAVzLClSHIOEU:b593w57)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens and @sumeerbhola)

**Comment by itsbilal** [comment]
TFTR!

bors r=sumeerbhola

**Pull request merged**
