### PR TITLE
gossip: remove race on client peer id

### LINKED ISSUE #122435: kv/kvclient/kvcoord: TestPartialPartition failed
kv/kvclient/kvcoord.TestPartialPartition [failed](https://tanzanite.cluster.engflow.com/invocations/default/90c300eb-5feb-4780-a80e-db8df2e8a570?testReportRun=3&testReportShard=12&testReportAttempt=1#targets-Ly9wa2cva3Yva3ZjbGllbnQva3Zjb29yZDprdmNvb3JkX3Rlc3Q=) on release-24.1 @ [a4896de30a39c020e15e9e7e308cc4398051a810](https://github.com/cockroachdb/cockroach/commits/a4896de30a39c020e15e9e7e308cc4398051a810):

```
=== RUN   TestPartialPartition/true-5
    test_server_shim.go:144: cluster virtualization disabled in global scope due to issue: #76378 (expected label: C-bug)
=== RUN   TestPartialPartition/false-5
    test_server_shim.go:144: cluster virtualization disabled in global scope due to issue: #76378 (expected label: C-bug)
==================
WARNING: DATA RACE
Write at 0x00c01518f708 by goroutine 168480:
  github.com/cockroachdb/cockroach/pkg/gossip.(*client).handleResponse()
      github.com/cockroachdb/cockroach/pkg/gossip/pkg/gossip/client.go:248 +0x6e4
  github.com/cockroachdb/cockroach/pkg/gossip.(*client).gossip.func2.1()
      github.com/cockroachdb/cockroach/pkg/gossip/pkg/gossip/client.go:326 +0xa4
  github.com/cockroachdb/cockroach/pkg/gossip.(*client).gossip.func2()
      github.com/cockroachdb/cockroach/pkg/gossip/pkg/gossip/client.go:336 +0x115
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:485 +0x262

Previous read at 0x00c01518f708 by goroutine 168351:
  github.com/cockroachdb/cockroach/pkg/gossip.(*client).startLocked.func1()
      github.com/cockroachdb/cockroach/pkg/gossip/pkg/gossip/client.go:132 +0x52b
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:485 +0x262

Goroutine 168480 (running) created at:
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:476 +0x69c
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:347 +0x3b0
  github.com/cockroachdb/cockroach/pkg/gossip.(*client).gossip()
      github.com/cockroachdb/cockroach/pkg/gossip/pkg/gossip/client.go:314 +0x14a
  github.com/cockroachdb/cockroach/pkg/gossip.(*client).startLocked.func1()
      github.com/cockroachdb/cockroach/pkg/gossip/pkg/gossip/client.go:125 +0x4d5
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:485 +0x262

Goroutine 168351 (running) created at:
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:476 +0x69c
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:347 +0x2fb
  github.com/cockroachdb/cockroach/pkg/gossip.(*client).startLocked()
      github.com/cockroachdb/cockroach/pkg/gossip/pkg/gossip/client.go:81 +0xdd
  github.com/cockroachdb/cockroach/pkg/gossip.(*Gossip).startClientLocked()
      github.com/cockroachdb/cockroach/pkg/gossip/pkg/gossip/gossip.go:1417 +0x537
  github.com/cockroachdb/cockroach/pkg/gossip.(*Gossip).bootstrap.func1.1()
      github.com/cockroachdb/cockroach/pkg/gossip/pkg/gossip/gossip.go:1182 +0x438
  github.com/cockroachdb/cockroach/pkg/gossip.(*Gossip).bootstrap.func1()
      github.com/cockroachdb/cockroach/pkg/gossip/pkg/gossip/gossip.go:1194 +0x14f
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:485 +0x262
==================
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=3</code>
 - <code>shard=12</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestPartialPartition.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-37888

### PR DESCRIPTION
**Pull request by kvoli**
The gossip client `peerID` was accessed outside of the gossip mutex,
leading to concurrent access. Serialize access by acquiring the gossip
mutex.

Fixes: https://github.com/cockroachdb/cockroach/issues/122435
Release note: None

### CODE REVIEW

**Comment by andrewbaptist** [comment]
Nice catch! 

Interestingly enough we introduced by an attempt to address incorrect unlocking: #108064. 
To note, the file was added to the list of files we don't lint on here: #107577. In nogo_config.json is still marked as
```
            "pkg/gossip/client.go": "flagged by linter, should be evaluated",
```

I don't think this lint would have helped here though although I'm not positivev. In gossip we are acquiring the `g.mu` lock but then accessing `c.peerIdD`, and I don't know if it is possible to know programmatically which lock needed to be held.

**Comment by andrewbaptist** [comment]
Looking at this a little more, there is at least one more usage of `c.peerID` outside of the lock in the `RunAsyncTask` goroutine. That is also not safe, but I don't know the exact situation to hit it. Maybe we can lift that log line to before the `RunAsyncTask` call (although it might always be 0 before `requestGossip` is called.

There are also uses of `c.addr`, but that doesn't appear to change after construction.

Can you also add a comment on `client.peerID` to note that it can only be accessed while holding the `gossip.mu` lock.

I think there is also a bug in `gossip` client.go:333 where it sets this outside of a lock.

**Review by arulajmani — APPROVED** [review]
:lgtm: modulo comment

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122440#-:-NvcIj7uDB10YrlKLkHs:b-9gfqjg)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/gossip/client.go` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122440#-NvcFrcHCCq7T-WQa8iN:-NvcFrcHCCq7T-WQa8iO:bqigome) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfbd9f654fcaa348adf76a5181772c1de41eb91d/pkg/gossip/client.go#L36)):*
> ```Go
> 	createdAt time.Time
> 	// peerID is the node ID of the peer we're connected to. This is set when we
> 	// receive a response from the peer. The gossip mu should be held when
> ```

I found it a bit surprising that we're using gossip mu here, but then I came across this comment:

https://github.com/cockroachdb/cockroach/blob/25232a68fd77bb6f517b39864a8605205864ee99/pkg/gossip/gossip.go#L228-L229

Is this the "surprise" it's talking about? 
___
*[`pkg/gossip/client.go` line 335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122440#-NvcIW1p-PbnFUD5jKYB:-NvcIW1p-PbnFUD5jKYC:b-gxkucf) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfbd9f654fcaa348adf76a5181772c1de41eb91d/pkg/gossip/client.go#L335)):*
> ```Go
> 					initCh <- struct{}{}
> 				}
> 				if peerID == 0 {
> ```

We don't seem to be doing anything meaningful with this. Should we just get rid of `peerID` entirely?

**Review by kvoli — COMMENTED** [review]
TYFTR

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122440#-:-Nvcjdr1EjvnMQhaKAIz:b-80sls6)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani)

___
*[`pkg/gossip/client.go` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122440#-NvcFrcHCCq7T-WQa8iN:-NvcjB0J5EOfHPK_bblW:bo6apac) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfbd9f654fcaa348adf76a5181772c1de41eb91d/pkg/gossip/client.go#L36)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I found it a bit surprising that we're using gossip mu here, but then I came across this comment:

https://github.com/cockroachdb/cockroach/blob/25232a68fd77bb6f517b39864a8605205864ee99/pkg/gossip/gossip.go#L228-L229

Is this the "surprise" it's talking about?
</blockquote></details>

Indeed.
___
*[`pkg/gossip/client.go` line 335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122440#-NvcIW1p-PbnFUD5jKYB:-NvcjBs87uJGBkD_CQIq:b-45yhr7) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfbd9f654fcaa348adf76a5181772c1de41eb91d/pkg/gossip/client.go#L335)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

We don't seem to be doing anything meaningful with this. Should we just get rid of `peerID` entirely?
</blockquote></details>

Nice, I didn't notice -- removed.

**Comment by kvoli** [comment]
bors r=arulajmani

**Pull request merged**
