### PR TITLE
execinfra: extract out some packages to break dependencies

### PR DESCRIPTION
**Pull request by yuzefovich**
**execinfra: shrink the package down a bit**

This commit refactors `execinfra` package by extracting some things in
order to break the dependency of `colexecop` on it. Two main pieces had
to be refactored:
- `stats.go` file is now moved into `execstats` since it seems to be
a much more suitable place. This required inlining `GetTraceData`
function helper and breaking a dependency of `ShouldCollectStats` helper
on `execinfra.FlowCtx`.
- `operator.go` which defines `OpNode` interface (implemented by both
columnar operators and row-by-row processors) has been moved (and
renamed to `op_node.go`) to a new package `execopnode`.

Release note: None

**execinfra: extract Releasable interface into a separate package**

This commit extracts `execinfra.Releasable` interface into a new
`execreleasable` package in order to break the dependency of several
packages of the vectorized engine on `execinfra`. This will allow those
packages (e.g. `colexecproj`) to start being built sooner which will
shorten the build time.

Addresses: #79357.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
This PR makes it so that the vectorized engine packages are no longer on the [critical path](https://github.com/cockroachdb/cockroach/issues/79357#issuecomment-1098681752).

**Review by msirek — APPROVED** [review]
Keep these build time improvement PRs coming!
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79938#-:-N-aH_m2B-Jy50RBS5_q:b-s29yl9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Review by maryliag — COMMENTED** [review]
> Reviewed 8 of 73 files at r1, 3 of 41 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79938)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[pkg/sql/colexec/builtin_funcs.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79938#-N-cFV1631rh6RN0Cf-d:-N-cFV1631rh6RN0Cf-e:b-z2dtds) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3b7e8816fc6a0f67ae774067c7975c5310b88a/pkg/sql/colexec/builtin_funcs.go#L42)):*
> ```Go
> 
> var _ colexecop.Operator = &defaultBuiltinFuncOperator{}
> var _ execreleasable.Releasable = &defaultBuiltinFuncOperator{}
> ```

nit: is there any other name that would also make sense to change it to? Just thinking of something that would not have this usage of `releasable.Releasable`

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79938)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag and @michae2)

___
*[pkg/sql/colexec/builtin_funcs.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79938#-N-cFV1631rh6RN0Cf-d:-N-cnt8-11saE1UOF-fM:b-h457sg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3b7e8816fc6a0f67ae774067c7975c5310b88a/pkg/sql/colexec/builtin_funcs.go#L42)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: is there any other name that would also make sense to change it to? Just thinking of something that would not have this usage of `releasable.Releasable`
</blockquote></details>

Yeah, I'm not fond of it either but couldn't come up with anything better. My only other ideas were `execinfrabase` of `execbase`, but IMO those are even worse. Any other ideas?

**Review by maryliag — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79938#-:-N-xEGqICFfWCywi9cB1:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[pkg/sql/colexec/builtin_funcs.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79938#-N-cFV1631rh6RN0Cf-d:-N-xE1Pk4cxdXzTgvWuD:buvunim) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3b7e8816fc6a0f67ae774067c7975c5310b88a/pkg/sql/colexec/builtin_funcs.go#L42)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Yeah, I'm not fond of it either but couldn't come up with anything better. My only other ideas were `execinfrabase` of `execbase`, but IMO those are even worse. Any other ideas?
</blockquote></details>

I can't think of anything either, so let's keep this way. We can always revisit later :)

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
