### PR TITLE
asim: ensure consistent sequencing of changes applied to ranges

### PR DESCRIPTION
**Pull request by wenyihu6**
**asim: ensure consistent sequencing of changes applied to a range**

Upon investigating, we identified the non-deterministic behavior was due to the
sequence of changes applied on the ranges within one tick. Changes within a tick
are applied in one go. But the changes are stored in a map, and map iteration
order is non-deterministic. Thus, the sequence of events applied and published
via gossip could vary and could result in different event states. This patch
resolves the issue by changing the storage of changes to be applied from a map
to an array, ensuring consistent iteration and sequence of events. Note the
shift to an array doesn't pose any issues since all changes need to be applied
anyway.

With this fix, the test `TestAsimDeterministic` fails only under race. This is
less concerning since the simulator should run on a single goroutine without
concurrency. Although the cause of the test failure in race conditions in
unclear, fixing this is not a priority.

Part Of: https://github.com/cockroachdb/cockroach/issues/105904
Release Note: None

----

**asim: add tests for constraints validation, asim determinism**

This patch adds an asim datadriven test case which sets up zone constraints and
ensures its proper application and validation of these constraints.

Part Of: https://github.com/cockroachdb/cockroach/issues/105904
Release Note: None

----

**asim: sort map by key when iterating**

While investigating #105904, we found that the bug's cause is due to the
simulator's iteration over an unordered map, leading to non-determinism. There
are other occurrences in the simulator's code where unordered map iteration
takes place. To make the code less error-prone, this patch checks the
simulator's code and sorts unordered maps by key when iterating. While it's
uncertain whether this change will solve any underlying non-determinism or
pinpoint exactly where in the code non-determinism might occur, there is no harm
in making the system less error-prone.

Part Of:https://github.com/cockroachdb/cockroach/issues/105904
Release Note: None

----

Each test were stressed with [runs](https://github.com/cockroachdb/cockroach/blob/cb4f59df66852e24546067d4904a4c981b0cc92e/pkg/kv/kvserver/asim/asim_test.go#L49) set to 10 and with --count = 100.

TestAsimDeterministic (with --count = 5 due to test wait time):
Screenshot 2023-07-27 at 8 09 50 AM

TestAsimDeterministicZoneConf:
Screenshot 2023-07-27 at 8 08 48 AM

TestAsimDeterministicDiskFull:
Screenshot 2023-07-27 at 8 08 19 AM

example_zone_config:
Screenshot 2023-07-27 at 8 13 19 AM

example_fulldisk:
Screenshot 2023-07-27 at 8 18 36 AM

### CODE REVIEW

**Comment by wenyihu6** [comment]
Let me know your thoughts on the added non-determinism tests since they just reproduce the data-driven tests but with more runs to check for determinism. Happy to remove if this is just extending CI time.

**Comment by wenyihu6** [comment]
hm looks like `TestAsimDeterministic` and `TestAsimDeterministicDiskFull` are still failing under stress (Extended CI). I'm going to take a shot in the dark with some pieces of code that I suspect may have issues while investigating and hand off if I can't figure out within an hour.

**Review by kvoli — COMMENTED** [review]
Do you think we are getting anything out of having both these tests for non-determinism? Would it be possible to augment the existing determinsm test?

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107696#-:-NaMd-lP0oCHnYrmTvTH:bvt4tuo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`-- commits` line 22 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107696#-NaMc8f4AxpCD7GP4YvB):*
nit: this is a bit confusing to read.



_Code quote:_
```
2, 3.
```
___
*[`pkg/kv/kvserver/asim/tests/testdata/example_zone_config` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107696#-NaMcKVD45O2klc9ZeEr:-NaMcKVD45O2klc9ZeEs:bds3i29) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fdc77d24b31a090ba8a23141d837d5f47a5064b/pkg/kv/kvserver/asim/tests/testdata/example_zone_config#L1)):*
> ```
> # This test applies a configuration that prioritizes zone constraints, favoring
> ```

Nice test!
___
*[`pkg/kv/kvserver/asim/asim_test.go` line 181 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107696#-NaMcRIN5GrT_iZaXaan:-NaMcRIN5GrT_iZaXaao:b-kopbea) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fdc77d24b31a090ba8a23141d837d5f47a5064b/pkg/kv/kvserver/asim/asim_test.go#L181)):*
> ```Go
> 	})
> 
> 	num := 10
> ```

Is there a reason for 10 runs here instead of 3? I

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/asim/asim_test.go` line 181 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107696#-NaMcRIN5GrT_iZaXaan:-Naif_W_9VjocAr6agrz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c180002e9e5287820b721a0f9c676617463e5d46/pkg/kv/kvserver/asim/asim_test.go#L181)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Is there a reason for 10 runs here instead of 3? I
</blockquote></details>

Done.

**Comment by wenyihu6** [comment]
I'm removing these two tests that were added to catch non-deterministic failures. Initially, I added them as they were more effective than TestAsimDeterministic in reproducing certain failures. After overloading  TestAsimDeterministic with more stores and replicas in the setup, they now only fail when TestAsimDeterministic fails, making them unnecessary.

**Review by kvoli — APPROVED** [review]
:lgtm: Should be good to merge after addressing the storepool locking nit.

> Reviewed 3 of 3 files at r3, 8 of 8 files at r6, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107696#-:-Nal9k1l8Eh7pqa6O3qa:b-ymj3fv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`pkg/kv/kvserver/asim/state/impl.go` line 1031 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/107696#-Nal974yAMFUsPsKtYjo:-Nal974yAMFUsPsKtYjp:boqhoqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c3d7e3d206e2800993a2a3218a17fd95d1362b1/pkg/kv/kvserver/asim/state/impl.go#L1031)):*
> ```Go
> 	storeID StoreID, storeDescriptors map[roachpb.StoreID]*storepool.StoreDetail,
> ) {
> 	s.stores[storeID].storepool.DetailsMu.Lock()
> ```

nit: I would avoid locking in the simulator unless we understand why it is necessary.  This doesn't appear necessary, since we still think there shouldn't be any concurrency.

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/asim/state/impl.go` line 1031 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/107696#-Nal974yAMFUsPsKtYjo:-NalRjed8Kly0IygSxyt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c3d7e3d206e2800993a2a3218a17fd95d1362b1/pkg/kv/kvserver/asim/state/impl.go#L1031)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: I would avoid locking in the simulator unless we understand why it is necessary.  This doesn't appear necessary, since we still think there shouldn't be any concurrency.
</blockquote></details>

Done.

**Pull request merged**
