### PR TITLE
plpgsql: correctly handle parsing errors

### LINKED ISSUE #109342: sql: v23.1.8-custom: parentheses is badly nested in ParseAndCollectTelemetryForPLpgSQLFunc
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4415320627/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4415320627/?referrer=webhooks_plugin)

Panic Message:

```
lexer.go:316: parentheses is badly nested
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/plpgsql/parser.(*lexer).ReadSqlConstruct
  | 	github.com/cockroachdb/cockroach/pkg/sql/plpgsql/parser/lexer.go:316
  | github.com/cockroachdb/cockroach/pkg/sql/plpgsql/parser.(*lexer).ReadSqlExpressionStr
  | 	github.com/cockroachdb/cockroach/pkg/sql/plpgsql/parser/lexer.go:277
  | github.com/cockroachdb/cockroach/pkg/sql/plpgsql/parser.(*plpgsqlParserImpl).Parse
  | 	plpgsql-gen.y:1150
  | github.com/cockroachdb/cockroach/pkg/sql/plpgsql/parser.(*Parser).parse
  | 	github.com/cockroachdb/cockroach/pkg/sql/plpgsql/parser/parse.go:98
  | github.com/cockroachdb/cockroach/pkg/sql/plpgsql/parser.(*Parser).parseWithDepth
  | 	github.com/cockroachdb/cockroach/pkg/sql/plpgsql/parser/parse.go:82
  | github.com/cockroachdb/cockroach/pkg/sql/plpgsql/parser.Parse
  | 	github.com/cockroachdb/cockroach/pkg/sql/plpgsql/parser/parse.go:132
  | github.com/cockroachdb/cockroach/pkg/sql/sem/plpgsqltree/utils.CountPLpgSQLStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/plpgsqltree/utils/plpg_visitor.go:90
  | github.com/cockroachdb/cockroach/pkg/sql/sem/plpgsqltree/utils.ParseAndCollectTelemetryForPLpgSQLFunc
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/plpgsqltree/utils/plpg_visitor.go:112
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildCreateFunction
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/create_function.go:111
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:359
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:272
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:246
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:576
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:240
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1978
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1484
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:964
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:142
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2986
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:141
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2181
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2186
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2103
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:900
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:310
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (3) parentheses is badly nested
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: parentheses is badly nested
lexer.go:316: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/pgwire/conn.go#L309-L311](https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/pgwire/conn.go#L309-L311)
[https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/conn_executor.go#L899-L901](https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/conn_executor.go#L899-L901)
[https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/conn_executor.go#L2102-L2104](https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/conn_executor.go#L2102-L2104)
[https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/conn_executor.go#L2185-L2187](https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/conn_executor.go#L2185-L2187)
[https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/conn_executor.go#L2180-L2182](https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/conn_executor.go#L2180-L2182)
[https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/conn_executor_exec.go#L140-L142](https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/conn_executor_exec.go#L140-L142)
[https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/conn_executor_exec.go#L2985-L2987](https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/conn_executor_exec.go#L2985-L2987)
[https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/conn_executor_exec.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/conn_executor_exec.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/conn_executor_exec.go#L963-L965](https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/conn_executor_exec.go#L963-L965)
[https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/conn_executor_exec.go#L1483-L1485](https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/conn_executor_exec.go#L1483-L1485)
[https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/conn_executor_exec.go#L1977-L1979](https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/conn_executor_exec.go#L1977-L1979)
[https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/plan_opt.go#L239-L241](https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/plan_opt.go#L239-L241)
[https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/plan_opt.go#L575-L577](https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/plan_opt.go#L575-L577)
[https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/opt/optbuilder/builder.go#L245-L247](https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/opt/optbuilder/builder.go#L245-L247)
[https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/opt/optbuilder/builder.go#L271-L273](https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/opt/optbuilder/builder.go#L271-L273)
[https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/opt/optbuilder/builder.go#L358-L360](https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/opt/optbuilder/builder.go#L358-L360)
[https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/opt/optbuilder/create_function.go#L110-L112](https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/opt/optbuilder/create_function.go#L110-L112)
[https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/sem/plpgsqltree/utils/plpg_visitor.go#L111-L113](https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/sem/plpgsqltree/utils/plpg_visitor.go#L111-L113)
[https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/sem/plpgsqltree/utils/plpg_visitor.go#L89-L91](https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/sem/plpgsqltree/utils/plpg_visitor.go#L89-L91)
[https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/plpgsql/parser/parse.go#L131-L133](https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/plpgsql/parser/parse.go#L131-L133)
[https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/plpgsql/parser/parse.go#L81-L83](https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/plpgsql/parser/parse.go#L81-L83)
[https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/plpgsql/parser/parse.go#L97-L99](https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/plpgsql/parser/parse.go#L97-L99)
[plpgsql-gen.y#L1149-L1151](plpgsql-gen.y#L1149-L1151)
[https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/plpgsql/parser/lexer.go#L276-L278](https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/plpgsql/parser/lexer.go#L276-L278)
[https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/plpgsql/parser/lexer.go#L315-L317](https://github.com/cockroachdb/cockroach/blob/c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8/pkg/sql/plpgsql/parser/lexer.go#L315-L317)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 310
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 900
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2103
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2186
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 2181
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 141
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 2986
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 142
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 964
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1484
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).makeExecPlan at line 1978
pkg/sql/plan_opt.go in pkg/sql.(*planner).makeOptimizerPlan at line 240
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).buildExecMemo at line 576
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).Build at line 246
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot at line 272
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmt at line 359
pkg/sql/opt/optbuilder/create_function.go in pkg/sql/opt/optbuilder.(*Builder).buildCreateFunction at line 111
pkg/sql/sem/plpgsqltree/utils/plpg_visitor.go in pkg/sql/sem/plpgsqltree/utils.ParseAndCollectTelemetryForPLpgSQLFunc at line 112
pkg/sql/sem/plpgsqltree/utils/plpg_visitor.go in pkg/sql/sem/plpgsqltree/utils.CountPLpgSQLStmt at line 90
pkg/sql/plpgsql/parser/parse.go in pkg/sql/plpgsql/parser.Parse at line 132
pkg/sql/plpgsql/parser/parse.go in pkg/sql/plpgsql/parser.(*Parser).parseWithDepth at line 82
pkg/sql/plpgsql/parser/parse.go in pkg/sql/plpgsql/parser.(*Parser).parse at line 98
plpgsql-gen.y in pkg/sql/plpgsql/parser.(*plpgsqlParserImpl).Parse at line 1150
pkg/sql/plpgsql/parser/lexer.go in pkg/sql/plpgsql/parser.(*lexer).ReadSqlExpressionStr at line 277
pkg/sql/plpgsql/parser/lexer.go in pkg/sql/plpgsql/parser.(*lexer).ReadSqlConstruct at line 316
```

### Tags

| Tag | Value |
| --- | --- |
| Command | mt start-sql |
| Environment | v23.1.8 |
| Go Version | go1.19.10 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.8-2-gc2fa404f72 |
| Cockroach SHA | c2fa404f72599c2d6fd5ec8a894021b13bcfe5a8 |
| # of CPUs | 32 |
| # of Goroutines | 330 |

Jira issue: CRDB-30884

### PR DESCRIPTION
**Pull request by DrewKimball**
#### plpgsql: correctly handle parsing errors

This patch ensures that PLpgSQL parsing errors are correctly propagated
in all cases. Previously, there were a few cases (like variable declaration
type parsing) where an error didn't halt parsing. The contract for
`GetTypeFromValidSQLSyntax` is also clarified, since it is ok to call with
an invalid type name as long as the error is properly handled.

Informs #105254

Release note: None

#### plpgsql: handle multiple expressions when one expression is expected

Previously, the PLpgSQL parser could panic when the user supplied more
than one expression in a location where only one was expected, for example,
in a return statement. This was because the PLpgSQL parser delegated to
the SQL parser's `ParseExpr` function, which expects exactly one input
expression. This commit returns a syntax error instead of the panic by
switching to use `ParseExprs`, which can handle multiple input expressions.

Informs #109342

Release note: None

#### plpgsql: return correct error for invalid parantheses and missing expression

This patch fixes error messages in the PLpgSQL parser for the case when
the parenthesis nesting is invalid, and for the case when no expression
(or statement) is supplied. Previously, invalid parentheses would cause
a panic without an error code, and a missing expression had the incorrect
message, since it wasn't checked until the SQL parser attempted to read
an empty string. Now, both cases are checked immediately by the PLpgSQL
parser and the correct error is propagated.

Fixes #109342

Release note: None

### CODE REVIEW

**Review by rharding6373 — APPROVED** [review]
:lgtm: Nice work! Only one very minor test suggestion.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112200#-:-Nga6d5wAgl3KZK6rRUo:b-csgvix)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/plpgsql/parser/testdata/stmt_assign` line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112200#-Nga6Qo39ANVZnRuP-Ru:-Nga6Qo4BH-63ZgbtHCq:bv1h5x2) ([raw file](https://github.com/cockroachdb/cockroach/blob/00ffa21e89a046af995b04793f793b8db60c73d9/pkg/sql/plpgsql/parser/testdata/stmt_assign#L68)):*
> ```
> DECLARE
> BEGIN
>   a := 1, (2, 3, 4, 5);
> ```

nit: have one of these tests return 3+ columns.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112200)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/plpgsql/parser/testdata/stmt_assign` line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112200#-Nga6Qo39ANVZnRuP-Ru:-NgebLrv7caszl245D87:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00ffa21e89a046af995b04793f793b8db60c73d9/pkg/sql/plpgsql/parser/testdata/stmt_assign#L68)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

nit: have one of these tests return 3+ columns.
</blockquote></details>

Done.

**Comment by DrewKimball** [comment]
TFTR!

**Review by mgartner — APPROVED** [review]
:lgtm: Nice finds!

> Reviewed 2 of 3 files at r1, 7 of 7 files at r4, 2 of 2 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112200#-:-NgtJRIg0VCkqFr1AUuw:bsf1ghn)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

**Pull request merged**
