### PR TITLE
kv: tolerate write skew under weak isolation levels

### LINKED ISSUE #100131: kv: tolerate write skew under weak isolation levels
With the (re-)introduction of weak isolation levels, transaction client and server logic will need to change to tolerate write skew (`ReadTimestamp != WriteTimestamp`) for transactions run at weak isolation levels.

https://github.com/cockroachdb/cockroach/blob/f9ac2166fd716ebd678287ba780c532d4dc7f28e/pkg/kv/kvserver/concurrency/isolation/levels.proto#L88-L91

Jira issue: CRDB-26575

Epic CRDB-26539

### PR DESCRIPTION
**Pull request by nvb**
_or "support kv-level snapshot isolation"._

Fixes #100131.

This commit adds support for weak transaction isolation levels (Snapshot and Read Committed) to commit even when their read and write timestamps are skewed. Thanks to prior cleanup and refactoring, this change is limited to an update to the transaction commit condition and a clarification of the one-phase commit requirements, along with a collection of updates to tests.

Release note: None

### CODE REVIEW

**Comment by arulajmani** [comment]
I'll treat this as a nudge to look at https://github.com/cockroachdb/cockroach/pull/102808 like I've been promising to. I'll try to carve some time out for later today, but if not, definitely tomorrow.

**Review by arulajmani — COMMENTED** [review]
It's exciting to see how seamless this was given your prior cleanups/refactors! 

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103246#-:-NVeFGBu0cDfakRzq_ys:bze3yc3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @nvanbenschoten)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103246#-NVeFEhW7naXk0plO9gN):*
:rocket: 
___
*[`pkg/kv/kvserver/replica_write.go` line 781 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103246#-NVeAQg64toZPEwQ4leQ:-NVeAQg64toZPEwQ4leR:b1ca7dd) ([raw file](https://github.com/cockroachdb/cockroach/blob/deb984d88a0d460f039d8036b08e86b6a4c28ff1/pkg/kv/kvserver/replica_write.go#L781)):*
> ```Go
> // transaction and ends with an EndTxn. One phase commits are disallowed if any
> // of the following conditions are true:
> //  1. the transaction has already been flagged with a write too old error.
> ```

Do we still need to check this, now that we've gotten rid of the WTO deferral mechanism? 
___
*[`pkg/kv/kvserver/replica_write.go` line 800 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103246#-NVe6PpL7CfMZ77Lf8OL:-NVe6PpMBaD2HhecnWga:b-jhdoev) ([raw file](https://github.com/cockroachdb/cockroach/blob/deb984d88a0d460f039d8036b08e86b6a4c28ff1/pkg/kv/kvserver/replica_write.go#L800)):*
> ```Go
> 		// for write-only batches, the non-transactional path would be unable to
> 		// detect write-write version conflicts between the transaction's read and
> 		// write timestamps.
> ```

I don't fully follow this -- for my edification, could you explain?



_Code quote:_
```Go
		// know how to evaluate with reads and writes at different timestamps. Even
		// for write-only batches, the non-transactional path would be unable to
		// detect write-write version conflicts between the transaction's read and
		// write timestamps.
```
___
*[`pkg/kv/kvserver/replica_write.go` line 810 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103246#-NVe91Iy5Y9gMSssXRHF:-NVe91Iy5Y9gMSssXRHG:b-30id3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/deb984d88a0d460f039d8036b08e86b6a4c28ff1/pkg/kv/kvserver/replica_write.go#L810)):*
> ```Go
> 	arg, _ := ba.GetArg(kvpb.EndTxn)
> 	etArg := arg.(*kvpb.EndTxnRequest)
> 	if retry, _, _ := batcheval.IsEndTxnTriggeringRetryError(ba.Txn, etArg.Deadline); retry {
> ```

If we no longer need to check the WTO flag, should we just replace this with `IsEndTxnExceedingDeadline` given we added the `ba.Txn.ReadTimestamp != ba.Txn.WriteTimestamp` above?
___
*[`pkg/kv/kvserver/batcheval/cmd_end_transaction.go` line 500 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103246#-NVeCQCT7b92KFcszo4p:-NVeCQCT7b92KFcszo4q:b-y5k0ry) ([raw file](https://github.com/cockroachdb/cockroach/blob/deb984d88a0d460f039d8036b08e86b6a4c28ff1/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L500)):*
> ```Go
> 	txn *roachpb.Transaction, deadline hlc.Timestamp,
> ) (retry bool, reason kvpb.TransactionRetryReason, extraMsg redact.RedactableString) {
> 	if txn.WriteTooOld {
> ```

Not related to your patch, but is it still possible to hit this? Even in the mixed version setting, if a 22.2 node defers a WTO, we would expect the client to immediately refresh it, right? So technically this branch should never be hit on a 23.1 node?

**Review by nvb — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103246#-:-NVjubP21Fnzxbka7D1u:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @jbowens)

___
*[`pkg/kv/kvserver/replica_write.go` line 781 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103246#-NVeAQg64toZPEwQ4leQ:-NVjrfybCEf7Vir6N6DO:b-92fkms) ([raw file](https://github.com/cockroachdb/cockroach/blob/deb984d88a0d460f039d8036b08e86b6a4c28ff1/pkg/kv/kvserver/replica_write.go#L781)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Do we still need to check this, now that we've gotten rid of the WTO deferral mechanism? 
</blockquote></details>

Good question. Let's discuss below.
___
*[`pkg/kv/kvserver/replica_write.go` line 800 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103246#-NVe6PpL7CfMZ77Lf8OL:-NVjrtX3CIO7PEe6dcaJ:bufqhly) ([raw file](https://github.com/cockroachdb/cockroach/blob/deb984d88a0d460f039d8036b08e86b6a4c28ff1/pkg/kv/kvserver/replica_write.go#L800)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I don't fully follow this -- for my edification, could you explain?
</blockquote></details>

The one-phase commit path runs using a non-transactional batch. This batch only has a single timestamp for reads and writes. That means that when a transaction's read and write timestamp are skewed, we need to choose either the txn's read timestamp or write timestamp to assign to the batch. The txn's read timestamp would not be correct, because we need to perform writes at or above its current write timestamp. However, assigning the write timestamp to the batch would also not be correct, because the batch would not consider conflicting write-write versions between the txn's read and write timestamp to be conflicts (no WriteTooOld error would be thrown). This could lead to lost updates.
___
*[`pkg/kv/kvserver/replica_write.go` line 810 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103246#-NVe91Iy5Y9gMSssXRHF:-NVjstTP8RtYrWgO83cO:bqn9tpf) ([raw file](https://github.com/cockroachdb/cockroach/blob/deb984d88a0d460f039d8036b08e86b6a4c28ff1/pkg/kv/kvserver/replica_write.go#L810)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

If we no longer need to check the WTO flag, should we just replace this with `IsEndTxnExceedingDeadline` given we added the `ba.Txn.ReadTimestamp != ba.Txn.WriteTimestamp` above?
</blockquote></details>

See the comment about retaining the flag for now. But even once we do remove it, I still don't think we should make that change. This caller shouldn't have to understand all of the possible reasons why a txn might need to retry, just that it needs to call this function which encapsulates those conditions to check. We might add a new condition in the future. Or remove one. The fact that there's some redundancy between a structural condition for 1PC and a txn retry condition is incidental, so at long as it's not harmful, it feels fine.
___
*[`pkg/kv/kvserver/batcheval/cmd_end_transaction.go` line 500 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103246#-NVeCQCT7b92KFcszo4p:-NVju5Qv-f-vAROvnHbp:b-amyswc) ([raw file](https://github.com/cockroachdb/cockroach/blob/deb984d88a0d460f039d8036b08e86b6a4c28ff1/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L500)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Not related to your patch, but is it still possible to hit this? Even in the mixed version setting, if a 22.2 node defers a WTO, we would expect the client to immediately refresh it, right? So technically this branch should never be hit on a 23.1 node?
</blockquote></details>

That's an interesting question. I think you're probably right that we can't hit this anymore, now that it will never come from a 23.1 or 23.2 client and also will never be set by the server. I'm ok keeping the logic here until we're fully ready to remove the flag though, given that it's well-tested. If nothing else, it at least lets us test client logic against a server that still behaves roughly like v23.1.

**Review by arulajmani — APPROVED** [review]
:lgtm: 

Consider improving the comment on `isOnePhaseCommit` before merging. 

> Dismissed @nvanbenschoten from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103246#-:-NVkHYN27DZEfHEEkr_t:b6wmwlq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens and @nvanbenschoten)

___
*[`pkg/kv/kvserver/replica_write.go` line 800 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103246#-NVe6PpL7CfMZ77Lf8OL:-NVkEZE77vTD2WxX6QRa:bypbvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/53cad8fa2f8753b26143b88e5bf5293b48309df5/pkg/kv/kvserver/replica_write.go#L800)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The one-phase commit path runs using a non-transactional batch. This batch only has a single timestamp for reads and writes. That means that when a transaction's read and write timestamp are skewed, we need to choose either the txn's read timestamp or write timestamp to assign to the batch. The txn's read timestamp would not be correct, because we need to perform writes at or above its current write timestamp. However, assigning the write timestamp to the batch would also not be correct, because the batch would not consider conflicting write-write versions between the txn's read and write timestamp to be conflicts (no WriteTooOld error would be thrown). This could lead to lost updates.
</blockquote></details>

Makes sense, thanks! 
___
*[`pkg/kv/kvserver/replica_write.go` line 810 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103246#-NVe91Iy5Y9gMSssXRHF:-NVkC-Gb1K7744Xex5hG:b92xxb8) ([raw file](https://github.com/cockroachdb/cockroach/blob/53cad8fa2f8753b26143b88e5bf5293b48309df5/pkg/kv/kvserver/replica_write.go#L810)):*
> This caller shouldn't have to understand all of the possible reasons why a txn might need to retry, just that it needs to call this function which encapsulates those conditions to check.

I agree, but I think what throws me off is the comment on top of this function, which lists out 3 conditions (without talking about them in the context of retries) -- I'm left scratching my head for a second wondering where we're checking this stuff, until I realize that's what `IsEndTxnTrigerringRetryError` is doing.

Maybe what I really want is for the top level comment to talk about retries, instead of talking about WTO/Txn deadline being exceeded?  
___
*[`pkg/kv/kvserver/batcheval/cmd_end_transaction.go` line 500 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103246#-NVeCQCT7b92KFcszo4p:-NVkEy7m-4li9iKVlo0H:b-a20kic) ([raw file](https://github.com/cockroachdb/cockroach/blob/53cad8fa2f8753b26143b88e5bf5293b48309df5/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L500)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

That's an interesting question. I think you're probably right that we can't hit this anymore, now that it will never come from a 23.1 or 23.2 client and also will never be set by the server. I'm ok keeping the logic here until we're fully ready to remove the flag though, given that it's well-tested. If nothing else, it at least lets us test client logic against a server that still behaves roughly like v23.1.
</blockquote></details>

Ack, that makes sense. 

Also noting that my current/prev versions up there were out of date.

**Review by nvb — COMMENTED** [review]
> Consider improving the comment on `isOnePhaseCommit` before merging.

Done.

bors r=arulajmani

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103246#-:-NVkRynQ0Yl3wPBWbu6_:b-beg2sl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani and @jbowens)

___
*[`pkg/kv/kvserver/replica_write.go` line 810 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103246#-NVe91Iy5Y9gMSssXRHF:-NVkS1pQ22ejjpnjaFi2:b5jemk6) ([raw file](https://github.com/cockroachdb/cockroach/blob/53cad8fa2f8753b26143b88e5bf5293b48309df5/pkg/kv/kvserver/replica_write.go#L810)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

> This caller shouldn't have to understand all of the possible reasons why a txn might need to retry, just that it needs to call this function which encapsulates those conditions to check.

I agree, but I think what throws me off is the comment on top of this function, which lists out 3 conditions (without talking about them in the context of retries) -- I'm left scratching my head for a second wondering where we're checking this stuff, until I realize that's what `IsEndTxnTrigerringRetryError` is doing.

Maybe what I really want is for the top level comment to talk about retries, instead of talking about WTO/Txn deadline being exceeded?  
</blockquote></details>

That's a great point. The comment is overly specific. I've adjusted it to discuss commit conditions instead, as you suggest.

**Comment by nvanbenschoten** [comment]
bors r=arulajmani

**Pull request merged**
