### PR TITLE
roachtest: add another error to jepsen allowlist

### PR DESCRIPTION
**Pull request by tbg**
Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50333)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/cmd/roachtest/jepsen.go, line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50333#-MA1ZC530uZNEZC3Hb16:-MA1ZC54AhopnjeEOocE:b5k9z90) ([raw file](https://github.com/cockroachdb/cockroach/blob/076e9200a72a05ff83f8284502cbfcc80ab42525/pkg/cmd/roachtest/jepsen.go#L253)):*
> ```Go
> 				// lock=true stat=PENDING rts=1592384065.123218152 ,0 wto=false
> 				// max=1592384065.128230720,0
> 				`-e "TransactionRetryWithProtoRefreshError"`,
> ```

mmm for this one it might be worth asking ben if it's easy to put a retry to whatever schema change causes it

**Comment by tbg** [comment]
cc @bdarnell

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50333)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/cmd/roachtest/jepsen.go, line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50333#-MA1ZC530uZNEZC3Hb16:-MA2E3Xn0VEEnepkJUmm:bx7f4uq) ([raw file](https://github.com/cockroachdb/cockroach/blob/076e9200a72a05ff83f8284502cbfcc80ab42525/pkg/cmd/roachtest/jepsen.go#L253)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

mmm for this one it might be worth asking ben if it's easy to put a retry to whatever schema change causes it
</blockquote></details>

It's really important that simple schema changes like the ones jepsen does not be subject to random retry errors like this. We've put a lot of work into this in the past. Have we had a regression in this area? (`ABORT_REASON_NEW_LEASE_PREVENTS_TXN` is new to me)

**Comment by andreimatei** [comment]
I was complaining about some apparent regression in the area in https://github.com/cockroachdb/cockroach/issues/37751#issuecomment-495391682
Don't know if it's exactly what we're seeing here or not... Maybe not.
The question here is why didn't automatic retries kick in, if Jepsen only does simple things.

The underlying reasons for `ABORT_REASON_NEW_LEASE_PREVENTS_TXN` we've always had. The reason code is new because I've carved out the case where the timestamp cache reset was caused by a new lease, as opposed to other reasons.

**Comment by bdarnell** [comment]
> The question here is why didn't automatic retries kick in, if Jepsen only does simple things.

Yeah. Specifically, I'm pretty sure jepsen only does its schema changes in implicit transactions (or maybe as the first and only statement in an explicit transaction) so it should be retried on the server side. 

Assuming this was discovered in #49360, [multiregister's DDL statements are trivial](https://github.com/cockroachdb/jepsen/blob/ad0402c124703a6b591c5199bdb9706e1a6e8fc4/cockroachdb/src/jepsen/cockroach/multiregister.clj#L59-L64)

**Comment by tbg** [comment]
Yes, it was discovered there. Not frequently - a few times over >400 runs.

**Comment by tbg** [comment]
Do we even know that this was a schema change? Could the error have come from a regular txn operation in jepsen or would they not surface to that level?

**Comment by bdarnell** [comment]
During normal operation jepsen catches nearly all errors. Most of the time when an error bubbles up to this level, it's from a schema change. But the jepsen logs should tell us exactly where it's coming from. Do you have a pointer to a log showing this problem?

**Pull request closed without merging**
