### PR TITLE
cdc: update sarama from 1.35.0 to 1.38.1

### LINKED ISSUE #96419: roachtest: cdc/sink-chaos failed
roachtest.cdc/sink-chaos [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8550951?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8550951?buildTab=artifacts#/cdc/sink-chaos) on master @ [22244a780dcfaca48162dde8e0f90b5ba9b6bb9c](https://github.com/cockroachdb/cockroach/commits/22244a780dcfaca48162dde8e0f90b5ba9b6bb9c):

```
test artifacts and logs in: /artifacts/cdc/sink-chaos/run_1
(cluster.go:1937).Run: output in run_101232.441206973_n4_workload-run-tpcc-wa: ./workload run tpcc --warehouses=100 --duration=30m  {pgurl:1-3}  returned: COMMAND_PROBLEM: ssh verbose log retained in ssh_101233.189661854_n4_workload-run-tpcc-wa.log: exit status 1
(cdc.go:283).Close: error shutting down prometheus/grafana: context canceled
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=16</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/sink-chaos.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-24114

Epic CRDB-11732

### PR DESCRIPTION
**Pull request by jayshrivastava**
A previous update (https://github.com/cockroachdb/cockroach/pull/95544) which updated sarama to 1.35.0 introduced a bug which resulted in nodes crashing. These failures are shown by https://github.com/cockroachdb/cockroach/issues/96419. The bug in described in detail in https://github.com/Shopify/sarama/issues/2322 and fixed by https://github.com/Shopify/sarama/commit/237925756e46ac948e583fceb81e8738c9f1e04b, which is included in version 1.38.1.

Fixes: https://github.com/cockroachdb/cockroach/issues/96419
Release note: None
Epic: None

### CODE REVIEW

**Comment by jayshrivastava** [comment]
We have exactly 14 updates. I liked the diffs below.

go: upgraded github.com/Shopify/sarama v1.35.0 => v1.38.1 https://github.com/Shopify/sarama/compare/v1.35.0...v1.38.1
go: upgraded github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21 => v0.0.0-20230111030713-bf00bc1b83b6 https://github.com/eapache/go-xerial-snappy/compare/776d5712da21...bf00bc1b83b6
go: upgraded github.com/hashicorp/errwrap v1.0.0 => v1.1.0 https://github.com/hashicorp/errwrap/compare/v1.0.0...v1.1.0
go: upgraded github.com/jcmturner/gofork v1.0.0 => v1.7.6 https://github.com/jcmturner/gofork/compare/v1.0.0...v1.7.6
go: upgraded github.com/jcmturner/gokrb5/v8 v8.4.2 => v8.4.3 https://github.com/jcmturner/gokrb5/compare/v8.4.2...v8.4.3
go: upgraded github.com/pierrec/lz4/v4 v4.1.15 => v4.1.17 https://github.com/pierrec/lz4/compare/v4.1.15...v4.1.17
go: upgraded github.com/xdg-go/scram v1.1.1 => v1.1.2 github.com/xdg-go/scram/compare/v1.1.1...v1.1.2
go: upgraded github.com/xdg-go/stringprep v1.0.3 => v1.0.4 github.com/xdg-go/stringprep/compare/v1.0.3...v1.0.4
go: upgraded golang.org/x/crypto v0.0.0-20220817201139-bc19a97f63c8 => v0.6.0 https://github.com/golang/crypto/compare/bc19a97f63c8...v0.6.0
go: upgraded golang.org/x/net v0.0.0-20220722155237-a158d28d115b => v0.7.0 https://github.com/golang/net/compare/a158d28d115b...v0.7.0
go: upgraded golang.org/x/sync v0.0.0-20220722155255-886fb9371eb4 => v0.1.0 https://github.com/golang/sync/compare/886fb9371eb4...v0.1.0
go: upgraded golang.org/x/sys v0.3.0 => v0.5.0 https://github.com/golang/sys/compare/v0.3.0...v0.5.0
go: upgraded golang.org/x/term v0.0.0-20210927222741-03fcf44c2211 => v0.5.0 https://github.com/golang/term/compare/03fcf44c2211...v0.5.0
go: upgraded golang.org/x/text v0.4.0 => v0.7.0 https://github.com/golang/text/compare/v0.4.0...v0.7.0

**Comment by jayshrivastava** [comment]
Notably, some of these are very large
- sarama: 6,955 additions and 1,106 deletions
- crypto: 853 additions and 569 deletions
- net 4,186 additions and 12,732 deletions
- sys 4,048 additions and 1,293 deletions

**Comment by miretskiy** [comment]
@jayshrivastava are you waiting on somebody to merge this in? Either we merge this change, or we revert the previous update.

**Comment by jayshrivastava** [comment]
@miretskiy Just published this draft. I'm looking to have this reviewed and merged. Because I updated some dependencies, tech leads must review their changes before merging. I'm going to add @knz too.

**Review by miretskiy — APPROVED** [review]

**Comment by jayshrivastava** [comment]
bors r=miretskiy

**Pull request merged**
