### PR TITLE
sql: Split SqlLite tests from main TestLogic tests

### PR DESCRIPTION
**Pull request by andy-kimball**
During our nightly runs, we pass the -bigtest flag to the main
LogicTest. This causes it to run a completely different set of
tests, pulled from a fork of:

  https://github.com/cockroachdb/sqllogictest

This commit segregates those tests into a new top level go test,
called TestSqlLiteLogic. The -bigtest flag is still required in
order to run the test, since it takes too long to run by default.

This commit prepares the way for separating out other aspects of
the monolithic TestLogic test, such as variations that are intended
to test the 2.0 heuristic planner. Eventually, we will get to a
point where TestLogic only tests the correctness of relational
output, rather than the specifics of how that output was derived.
This will allow the 2.0 heuristic planner and the 2.1 cost-based
optimizer to share these tests.

Other aspects of our testing that cannot be easily shared can go
into other top-level tests.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25722#-:-LCtb8OK5h6TCW8mrAOI:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/logictest/logic_test.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25722#-LCtdSv55jbTdOCRw36w:-LCtdSv55jbTdOCRw36x:bg1kwhf) ([raw file](https://github.com/cockroachdb/cockroach/blob/06a4201eae66a20b6ac8b5769bf0a876396bc1cd/pkg/sql/logictest/logic_test.go#L71)):*
> ```Go
> 		return
> 	}
> 	globs := []string{
> ```

Is it still possible to run just one specific bigtest file? (it's very important when debugging a failure).  I'm asking because the names of the files inside each directory are the same, e.g. `slt_good_0.test` and I believe that would be the name of the subtest, so that won't be helpful.

Maybe each path here should be run separately in a different subtest (e.g. "TestSqlLiteLogic/index/between")

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25722)*

**Comment by andy-kimball** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/logictest/logic_test.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25722#-LCtdSv55jbTdOCRw36w:-LCu0h-Q4UlNtV72bE_p:b-bpcftf) ([raw file](https://github.com/cockroachdb/cockroach/blob/06a4201eae66a20b6ac8b5769bf0a876396bc1cd/pkg/sql/logictest/logic_test.go#L71)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Is it still possible to run just one specific bigtest file? (it's very important when debugging a failure).  I'm asking because the names of the files inside each directory are the same, e.g. `slt_good_0.test` and I believe that would be the name of the subtest, so that won't be helpful.

Maybe each path here should be run separately in a different subtest (e.g. "TestSqlLiteLogic/index/between")
</blockquote></details>

I left the `-d` option in place. Everything should work as it always has.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25722)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/logictest/logic_test.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25722#-LCtdSv55jbTdOCRw36w:-LCu3R2U8Ukqn4X2RMpb:bpinvwl) ([raw file](https://github.com/cockroachdb/cockroach/blob/06a4201eae66a20b6ac8b5769bf0a876396bc1cd/pkg/sql/logictest/logic_test.go#L71)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I left the `-d` option in place. Everything should work as it always has.
</blockquote></details>

The `-d` option sets `logictestdata` which isn't used in this test..  I guess you could use `-d` with `TestLogic` but that's confusing (given that you're debugging a `TestSqlteLogic` failure)

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25722)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/logictest/logic_test.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25722#-LCtdSv55jbTdOCRw36w:-LCuXW12Cu9lwrxvwBKD:bc3sci0) ([raw file](https://github.com/cockroachdb/cockroach/blob/06a4201eae66a20b6ac8b5769bf0a876396bc1cd/pkg/sql/logictest/logic_test.go#L71)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The `-d` option sets `logictestdata` which isn't used in this test..  I guess you could use `-d` with `TestLogic` but that's confusing (given that you're debugging a `TestSqlteLogic` failure)
</blockquote></details>

Sorry, I misread, it will get handled inside `RunLogicTest`, so the `-d` flag should still work. This is fine with me.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25722#-:-LCuXcat4qSkaDU4U0k-:bnfp4nl)*

**Review by jordanlewis — APPROVED** [review]
LGTM

**Review by knz — APPROVED** [review]
Thanks for thinking this forward.

**Pull request merged**
