### PR TITLE
kvserver: improve logging of draining lease transfer failures 

### PR DESCRIPTION
**Pull request by andreimatei**
The respective log message now tells you more about why the transfer
failed; in particular it tells you when no transfer targets were found.

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Looks good, just a few nits.

> Reviewed 2 of 2 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55829#-:-MKKo8BrC1_9r_dFlUfb:bjc4kor)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvserver/replicate_queue.go, line 933 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55829#-MKKngGP1dke9D_gBL9g:-MKKngGP1dke9D_gBL9h:biqh8jq) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa0ada12fa5112494e227b4a78c857c142343a67/pkg/kv/kvserver/replicate_queue.go#L933)):*
> ```Go
> 			checkCandidateFullness:   true,
> 			dryRun:                   dryRun,
> 		},
> ```

you should check `err` in every case before the `switch`.
___
*[pkg/kv/kvserver/replicate_queue.go, line 944 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55829#-MKKnkZ39BSxWBBlqopt:-MKKnkZ4950xTU7sj3t4:b-uuwo2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa0ada12fa5112494e227b4a78c857c142343a67/pkg/kv/kvserver/replicate_queue.go#L944)):*
> ```Go
> 		return false, nil
> 	default:
> 		panic("unreachable")
> ```

`AssertionFailedf`
___
*[pkg/kv/kvserver/store.go, line 1178 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55829#-MKKo-P211Qwbcjfhzdf:-MKKo-P211Qwbcjfhzdg:b22x439) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa0ada12fa5112494e227b4a78c857c142343a67/pkg/kv/kvserver/store.go#L1178)):*
> ```Go
> 								ctx, 1,
> 								"failed to transfer lease %s for range %s when draining: %s",
> 								drainingLease, desc, msg)
> ```

remove the conditional above
then here
`log.XXX("... when draining: %s (%v)", ..., transferStatus, err)`

**Review by andreimatei — COMMENTED** [review]
TFTR

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55829#-:-MNeNqg907i-CpUCy0EW:bb73zsl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/kv/kvserver/replicate_queue.go, line 933 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55829#-MKKngGP1dke9D_gBL9g:-MNeLNJ-CTiHsUALo0P3:b-voxrpm) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa0ada12fa5112494e227b4a78c857c142343a67/pkg/kv/kvserver/replicate_queue.go#L933)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

you should check `err` in every case before the `switch`.
</blockquote></details>

err is only coupled with `transferErr`, but anyway this code is gone now
___
*[pkg/kv/kvserver/replicate_queue.go, line 944 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55829#-MKKnkZ39BSxWBBlqopt:-MNeLT8AA6BQsjdRn36M:b-j7al7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa0ada12fa5112494e227b4a78c857c142343a67/pkg/kv/kvserver/replicate_queue.go#L944)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`AssertionFailedf`
</blockquote></details>

luckily we were able to avoid this fight; see now
___
*[pkg/kv/kvserver/store.go, line 1178 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55829#-MKKo-P211Qwbcjfhzdf:-MNeMk5t7OyvsLsX1rCw:b-g61yde) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa0ada12fa5112494e227b4a78c857c142343a67/pkg/kv/kvserver/store.go#L1178)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

remove the conditional above
then here
`log.XXX("... when draining: %s (%v)", ..., transferStatus, err)`

</blockquote></details>

Well I don't want to print a `<nil>` for no reason. But see now.

**Review by knz — APPROVED** [review]
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55829)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55829#-:-MNic6dyA0opzUGovyN3:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
