### PR TITLE
parser: combine TestParseErrors with TestParseDatadriven

### LINKED ISSUE #62106: sql: unify TestParseErrors with TestParseDataDriven
See @RaduBerinde's comment here: https://github.com/cockroachdb/cockroach/pull/60676#pullrequestreview-593678914

This will improve the ergonomics of testing error cases for parsing.

### PR DESCRIPTION
**Pull request by mgartner**
#### parser: combine TestParseErrors with TestParseDatadriven

Data-driven parser tests now allow the `error` command. Errors in
`pkg/sql/parser/testdata/errors` have been moved to corresponding
statement-specific test files. If there was not an obvious place to move
the error tests within the statement-specific files, the error tests
were places at the bottom.

This was improvement was suggestion in a comment in #60676.

Fixes #62106

Release note: None

#### parser: remove parse subdirectory in testdata

The `testdata/parse` subdirectory has been removed because it is the
only `testdata` subdirectory, so it is not necessary.

Release note: None

### CODE REVIEW

**Comment by rafiss** [comment]
awesome! this fixes https://github.com/cockroachdb/cockroach/issues/62106 too -- thanks for picking it up!

**Review by RaduBerinde — APPROVED** [review]
Nice!! :lgtm_strong: 

> Reviewed 1 of 21 files at r1, 59 of 59 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65704#-:-MadtT772ygpzdZzFEiA:b3cs2cs)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Review by rafiss — APPROVED** [review]
ty!

**Comment by mgartner** [comment]
Thanks for the reviews!

bors r+

**Comment by otan** [comment]
hehe, sorry.

**Pull request merged**
