### PR TITLE
Add myself to AUTHORS

### PR DESCRIPTION
**Pull request by apantel**
This is part of onboarding

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
LGTM!

In case you haven't seen the onboarding/PR instructions, the next step is for you to write a new comment on this github PR that has the following line:

bors r+
(actually you could also use `bors r=rafiss`)

bors is the name of a tool that automatically merges PRs for us and runs tests https://bors.tech/

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42545#-:-Lu-3JHK2UWz51kG21v8:beaq9xe)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by apantel** [comment]
bors r=rafiss

**Comment by apantel** [comment]
bors r=rafiss

**Comment by apantel** [comment]
bors r=rafiss

**Pull request merged**
