### PR TITLE
opt: remove CanHaveSideEffects

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: use volatility for SimplifyZeroCardinalityGroup

Switch to using volatility instead of `CanHaveSideEffects` for this rule.

Release note: None

#### opt: use volatility for CanInlineWith

Switch to using volatility instead of `CanHaveSideEffects` for this rule.

Release note: None

#### opt: use volatility for Project FDs

Switch to using volatility instead of `CanHaveSideEffects` for Project FDs.

Release note: None

#### opt: use volatility for hoisting from CASE

Switch to using volatility instead of `CanHaveSideEffects` for hoisting
expressions out of CASE and similar. We can only allow "leak proof" operators to
be hoisted.

Release note: None

#### opt: use volatility for deduplicating columns in optbuilder

Switch to using volatility instead of `CanHaveSideEffects` when deciding whether
we can reuse a projected column.

Release note: None

#### opt: remove CanHaveSideEffects

All uses of `CanHaveSideEffects` have been replaced with uses of VolatilitySet.
Remove this property.

Release note: None

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 3 of 3 files at r3, 2 of 2 files at r4, 3 of 3 files at r5, 4 of 4 files at r6, 54 of 54 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50581#-:-MAbGleE7QCT2TstawSe:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @RaduBerinde)

___
*[pkg/sql/opt/memo/expr.go, line 640 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50581#-MAbGckr8ix1ddzS9JK0:-MAbGckr8ix1ddzS9JK1:bvaumsy) ([raw file](https://github.com/cockroachdb/cockroach/blob/c164803a833a235477d50194280f1c85dfa40654/pkg/sql/opt/memo/expr.go#L640)):*
> ```Go
> 		}
> 
> 		if !item.scalar.VolatilitySet.HasVolatile() {
> ```

Were the `fd` changes in some of the tests solely because of this change?

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/memo/expr.go, line 640 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50581#-MAbGckr8ix1ddzS9JK0:-MAbaRrg3Mnhtn0a1qBR:b48c480) ([raw file](https://github.com/cockroachdb/cockroach/blob/c164803a833a235477d50194280f1c85dfa40654/pkg/sql/opt/memo/expr.go#L640)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Were the `fd` changes in some of the tests solely because of this change?
</blockquote></details>

Yeah, exactly. It also inspired my recent FD fix because some were getting worse even though we were strictly adding information.  Note that each change is its own commit with its test changes.

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, 3 of 3 files at r3, 2 of 2 files at r4, 3 of 3 files at r5, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50581#-:-MAdTRBc02Me3dHZ2tfT:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/props/volatility.go, line 31 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50581#-MAdO7me54Hue45lGqsj:-MAdO7mfCEnn3GFcoMde:bzhziql) ([raw file](https://github.com/cockroachdb/cockroach/blob/c164803a833a235477d50194280f1c85dfa40654/pkg/sql/opt/props/volatility.go#L31)):*
> ```Go
> //
> //   1. CASE/IF branches are only evaluated if the branch condition is true or
> //      if all operators are LeakProof.  Therefore, the following is guaranteed
> ```

Ultra Nit: Single space after period.

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50581#-:-MAg-QtoDMw01RTFXu2u:bz5mair)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andy-kimball and @mgartner)

___
*[pkg/sql/opt/props/volatility.go, line 31 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50581#-MAdO7me54Hue45lGqsj:-MAg-PUW5Dtayz8g2Hit:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c164803a833a235477d50194280f1c85dfa40654/pkg/sql/opt/props/volatility.go#L31)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Ultra Nit: Single space after period.
</blockquote></details>

Done.

**Pull request merged**
