### PR TITLE
streamingest: wait for all goroutines on streamIngestProcessor shutdown 

### PR DESCRIPTION
**Pull request by andreimatei**
This processor was failing to stop and wait for some of the goroutines it
spawned, which is not nice (in particular, it's likely that those
goroutines were using a tracing span after it was finished).

Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
I pulled this out of the bigger PR cause I had gotten it wrong.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72650#-:-MoF3QTDDuHHpabMqLJD:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru and @andreimatei)

___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go, line 313 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72650#-MoF3gxG-1JiN8tpG4Gs:-MoF3gxG-1JiN8tpG4Gt:boxx9hq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f02ba5e38166627a31e5956ea5a7cb0bfe22cdf/pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go#L313)):*
> ```Go
> 	sip.pollingWaitGroup.Wait()
> 	// Wait for the merge goroutine.
> 	sip.cancelMergeAndWait()
> ```

In an error case it's possible that `cancelMergeAndWait` is never set (i.e. we short-circuit `Start` method before `merge` is called), so it might be worth either checking here for `nil` or set this function to a non-nil noop in the constructor.

**Review by andreimatei — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72650#-:-MoFHTRX30kac6Jq8uDG:bodgj64)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru and @yuzefovich)

___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go, line 313 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72650#-MoF3gxG-1JiN8tpG4Gs:-MoFEosL9-kTHX4qSXme:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f02ba5e38166627a31e5956ea5a7cb0bfe22cdf/pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go#L313)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

In an error case it's possible that `cancelMergeAndWait` is never set (i.e. we short-circuit `Start` method before `merge` is called), so it might be worth either checking here for `nil` or set this function to a non-nil noop in the constructor.
</blockquote></details>

done

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72650#-:-MoFWXveAZgpNBvKREgj:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru and @yuzefovich)

**Pull request merged**
