### PR TITLE
ui: Automate formatting standards

### PR DESCRIPTION
**Pull request by vladlos**
Added `eslint` and `prettier`, import  config for `eslint` from @cockroachlabs/eslint-config.
Added additional rules into `.eslintrc` for avoiding some mistakes.

Release note (ui): none

### CODE REVIEW

**Review by dhartunian — CHANGES_REQUESTED** [review]
@elkmaster can you add more details in the PR about what commands were run to generate the diff. I'd like to make sure the actions taken to change this much code are fully documented.

**Comment by dhartunian** [comment]
@elkmaster also maybe in a separate PR can we adjust the Makefile task to run the linting we need? Not sure if it will do what we need by default https://github.com/cockroachdb/cockroach/blob/3a7db66e4e2930b745e22141755a13dad2385047/Makefile#L1372-L1379

**Comment by elkmaster** [comment]
only `"eslint:fix": "tsc --noEmit && eslint '*/**/*.{ts,tsx}' --quiet --fix --debug"` it mostly formatting changes. I disabled some of the rules so there was only around 10 very minor items were changed by hand.

**Comment by dhartunian** [comment]
Closing this old PR since I'll be submitting a new one.

**Pull request closed without merging**
