### PR TITLE
sql: add ability set, edit, read tenant capabilities

### LINKED ISSUE #87851: sql: add ability set, edit, read tenant capabilities
See the RFC here: #85954.

We would like to have a new overload to `crdb_internal.create_tenant()` and a new built-in function `crdb_internal.set_tenant_capabilities` (maybe also with a getter) to edit tenant capabilities.

This issue should also cover:

- [ ]  Cache invalidation of capabilities on edit.
- [ ] SHOW TENANT CAPABILITIES statement
- [ ] Syntax to create both privileged tenants and unprivileged ones

Epic: CRDB-19504

Jira issue: CRDB-19569

### PR DESCRIPTION
**Pull request by ecwall**
Fixes #87851

Add new SQL syntax for
1) Setting tenant capabilities:
`ALTER TENANT t GRANT CAPABILITY capabilitiy_name=capability_value;`
2) Resetting tenant capabilities:
`ALTER TENANT t REVOKE CAPABILITIY capability_name;`
3) Reading tenant capabilities:
`SHOW TENANT t WITH CAPABILITIES;`

Release note: None

### CODE REVIEW

**Comment by ecwall** [comment]
This should be rebased and updated to use `tenant_spec` after https://github.com/cockroachdb/cockroach/pull/94932 is merged.

**Comment by dikshant** [comment]
Is 3) supposed to be:
```
SHOW TENANT t WITH CAPABILITY capability_name;
```
?

**Review by knz — COMMENTED** [review]
General direction OK.
Regarding our convo yesterday: I like the idea to have the base statement be `SHOW TENANT`, and `WITH` _modify_ its behavior to add more columns. See my later comments about that.

Further than that:

1) you forgot to add/update sql/tree/walk.go to properly walk the exprs in AlterTenantSetCapabilities

2) As to dikshant's question, if the thing lists all capabilities it should be `WITH CAPABILITIES` (plural), perhaps with the singular as a non-documented convenience alias.

3) GRANT/REVOKE, not SET/RESET

4) we want the ability to grant/revoke multiple capabilities at once, with a comma-separated list.

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95013#-:-NLfLOX5-Y3j0_fzC-cP:bh71pbl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @dikshant, @ecwall, and @rafiss)

___
*[`pkg/sql/parser/sql.y` line 5557 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95013#-NLfLlfDBdpUIK5SLO3t:-NLfLlfE0wIELI4MT-5G:b6eur0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa8bf6e7dbaf6ccb89f727566dff7d606593db2c/pkg/sql/parser/sql.y#L5557)):*
> ```Yacc
>    }
>   }
> | SHOW TENANT d_expr WITH CAPABILITY
> ```

I would combine them with a show_tenant_with_clause, accepting a list of modifiers (like SHOW RANGES does)
Then the execution code would _add_ columns as specified by the modifiers, instead of changing the result schema entirely.
___
*[`pkg/sql/sem/tree/stmt.go` line 452 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95013#-NLfM98l3gCqoeUgia9S:-NLfM98m4nzn6s-m6phU:b-k06aa5) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa8bf6e7dbaf6ccb89f727566dff7d606593db2c/pkg/sql/sem/tree/stmt.go#L452)):*
> ```Go
> func (*AlterTenantCapability) StatementTag() string { return "ALTER TENANT CAPABILITY" }
> 
> func (*AlterTenantCapability) cclOnlyStatement() {}
> ```

Probably not.

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95013)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @dikshant, @knz, and @rafiss)

___
*[`pkg/sql/sem/tree/stmt.go` line 452 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95013#-NLfM98l3gCqoeUgia9S:-NMEeTrz1SubgSY_b2Ck:baoocwr) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa8bf6e7dbaf6ccb89f727566dff7d606593db2c/pkg/sql/sem/tree/stmt.go#L452)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Probably not.
</blockquote></details>

Good catch I just copied these methods.

**Review by ecwall — COMMENTED** [review]
1) Added
2) Changed to `WITH CAPABILITIES` for now. I don't know if we should have an alias for this but not the other `ALTER TENANT` statements for plural/singular.
3) Changed
4) Added

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95013#-:-NMF0NvN3S8S6DNMN-D0:bv84jgt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @dikshant, @knz, and @rafiss)

___
*[`pkg/sql/parser/sql.y` line 5557 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95013#-NLfLlfDBdpUIK5SLO3t:-NMFqlsg30OfDUHgzJvd:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa8bf6e7dbaf6ccb89f727566dff7d606593db2c/pkg/sql/parser/sql.y#L5557)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I would combine them with a show_tenant_with_clause, accepting a list of modifiers (like SHOW RANGES does)
Then the execution code would _add_ columns as specified by the modifiers, instead of changing the result schema entirely.
</blockquote></details>

Updated.

**Review by knz — COMMENTED** [review]
> Reviewed 5 of 16 files at r2, 20 of 20 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95013)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @dikshant, @ecwall, and @rafiss)

___
*[`pkg/sql/parser/sql.y` line 5592 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95013#-NMTa3Gw3HQ-XAsse3iX:-NMTa3Gw3HQ-XAsse3iY:bckm018) ([raw file](https://github.com/cockroachdb/cockroach/blob/f16bc095e8a503d1a47f6a4afb3591c6a0276ece/pkg/sql/parser/sql.y#L5592)):*
> ```Yacc
> // %Category: Experimental
> // %Text:
> // SHOW { TENANT { <tenant_spec> | ALL } | TENANTS ] [WITH {REPLICATION STATUS|CAPABILITY}]
> ```

nit: also mention `SHOW TENANTS` on a separate line.
___
*[`pkg/sql/parser/sql.y` line 5624 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95013#-NMTa8xHAkSAWYZlKVEN:-NMTa8xHAkSAWYZlKVEO:b-fvs7d0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f16bc095e8a503d1a47f6a4afb3591c6a0276ece/pkg/sql/parser/sql.y#L5624)):*
> ```Yacc
>   { $$.val = $2.showTenantOpts() }
> 
> show_tenant_options:
> ```

nit:
```
show_tenant_options:
   show_tenant_option
| show_tenant_options ',' show_tenant_option { $$.val = append($1.showTenantOpts(), $3.showTenantOpt()) }

show_tenant_option:
   REPLICATION STATUS
| CAPABILITIES
```
___
*[`pkg/sql/parser/sql.y` line 6342 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95013#-NMTaOs3-jteZ796CQ7b:-NMTaOs3-jteZ796CQ7c:b8hjt2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/f16bc095e8a503d1a47f6a4afb3591c6a0276ece/pkg/sql/parser/sql.y#L6342)):*
> ```Yacc
>       TenantSpec: $3.tenantSpec(),
>       Capabilities: $6.tenantCapabilities(),
> 			IsReset: true,
> ```

nit: spaces not tabs
___
*[`pkg/sql/parser/sql.y` line 6347 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95013#-NMTaffpDTd2PqpFprcn:-NMTaffpDTd2PqpFprco:b-kb2w2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f16bc095e8a503d1a47f6a4afb3591c6a0276ece/pkg/sql/parser/sql.y#L6347)):*
> ```Yacc
> 
> grant_tenant_capability:
>   var_name to_or_eq var_value
> ```

The `= <value>` part is optional. Some capabilities are just an identifier without a value.
___
*[`pkg/sql/parser/sql.y` line 6355 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95013#-NMTaV79C9spop5FNmNt:-NMTaV7A17jBMjcwXenA:bwnzrvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f16bc095e8a503d1a47f6a4afb3591c6a0276ece/pkg/sql/parser/sql.y#L6355)):*
> ```Yacc
>   }
> 
> grant_tenant_capability_list:
> ```

1. make a single non-terminal `tenant_capability_list` for both grant and revoke in the grammar (both accept `= var_value`)
2. during planning, produce an error in REVOKE if there are assignments.

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95013)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @dikshant, @knz, and @rafiss)

___
*[`pkg/sql/parser/sql.y` line 5592 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95013#-NMTa3Gw3HQ-XAsse3iX:-NMVQm2F-bUkrOSOfgqp:b-fqvqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/f16bc095e8a503d1a47f6a4afb3591c6a0276ece/pkg/sql/parser/sql.y#L5592)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: also mention `SHOW TENANTS` on a separate line.
</blockquote></details>

You mean this?

```
SHOW TENANT { <tenant_spec> | ALL } [ WITH { REPLICATION STATUS|CAPABILITY } ]
SHOW TENANTS [ WITH { REPLICATION STATUS|CAPABILITY } ]
```
___
*[`pkg/sql/parser/sql.y` line 5624 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95013#-NMTa8xHAkSAWYZlKVEN:-NMVSVjC6TtCLELa7sUP:b-9r6qyv) ([raw file](https://github.com/cockroachdb/cockroach/blob/f16bc095e8a503d1a47f6a4afb3591c6a0276ece/pkg/sql/parser/sql.y#L5624)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit:
```
show_tenant_options:
   show_tenant_option
| show_tenant_options ',' show_tenant_option { $$.val = append($1.showTenantOpts(), $3.showTenantOpt()) }

show_tenant_option:
   REPLICATION STATUS
| CAPABILITIES
```
</blockquote></details>

I modeled this after `show_ranges_options`. It looks like it is this way in order to handle either being put first? 

They aren't actually a slice of options, they modify the same "options" struct.
___
*[`pkg/sql/parser/sql.y` line 6342 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95013#-NMTaOs3-jteZ796CQ7b:-NMVTEtRByc6H05yzIVS:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f16bc095e8a503d1a47f6a4afb3591c6a0276ece/pkg/sql/parser/sql.y#L6342)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: spaces not tabs
</blockquote></details>

Fixed.



_Code quote:_
```Yacc
IsReset: true,
```
___
*[`pkg/sql/parser/sql.y` line 6347 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95013#-NMTaffpDTd2PqpFprcn:-NMVTGXTAI1W9i0uh0F_:b-kgk3uo) ([raw file](https://github.com/cockroachdb/cockroach/blob/f16bc095e8a503d1a47f6a4afb3591c6a0276ece/pkg/sql/parser/sql.y#L6347)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

The `= <value>` part is optional. Some capabilities are just an identifier without a value.
</blockquote></details>

Boolean cluster settings get set to `true` instead of just being set with no value.

Why handle boolean capabilities differently?

**Review by knz — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95013)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @dikshant, @ecwall, and @rafiss)

___
*[`pkg/sql/parser/sql.y` line 5592 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95013#-NMTa3Gw3HQ-XAsse3iX:-NMd32WR9ijVDw3DOCFV:bo9ntir) ([raw file](https://github.com/cockroachdb/cockroach/blob/f16bc095e8a503d1a47f6a4afb3591c6a0276ece/pkg/sql/parser/sql.y#L5592)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

You mean this?

```
SHOW TENANT { <tenant_spec> | ALL } [ WITH { REPLICATION STATUS|CAPABILITY } ]
SHOW TENANTS [ WITH { REPLICATION STATUS|CAPABILITY } ]
```
</blockquote></details>

yes. You can also do this:
```
// SHOW TENANT { <tenant_spec> | ALL }  [ WITH <options> ]
// SHOW TENANTS                         [ WITH <options> ]
//
// Options:
//     REPLICATION STATUS
//     CAPABILITIES
```

(nb: CAPABILITIES, not CAPABILITY)
___
*[`pkg/sql/parser/sql.y` line 5624 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95013#-NMTa8xHAkSAWYZlKVEN:-NMd3Q9f3hPJoBFJJ5w6:b14ni5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/f16bc095e8a503d1a47f6a4afb3591c6a0276ece/pkg/sql/parser/sql.y#L5624)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

I modeled this after `show_ranges_options`. It looks like it is this way in order to handle either being put first? 

They aren't actually a slice of options, they modify the same "options" struct.
</blockquote></details>

Oh, that's right. Then what you did is ok.
___
*[`pkg/sql/parser/sql.y` line 6347 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95013#-NMTaffpDTd2PqpFprcn:-NMd3WFBAjOK55aFORxR:b-ghrsix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f16bc095e8a503d1a47f6a4afb3591c6a0276ece/pkg/sql/parser/sql.y#L6347)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

Boolean cluster settings get set to `true` instead of just being set with no value.

Why handle boolean capabilities differently?
</blockquote></details>

We have used this pattern elsewhere already. For example, `BACKUP ... WITH detached` is implicit for `WITH detached = true`.

The advantage of supporting this is that you can then use a single grammar rule for both GRANT and REVOKE.

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95013)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @dikshant, @knz, and @rafiss)

___
*[`pkg/sql/parser/sql.y` line 5592 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95013#-NMTa3Gw3HQ-XAsse3iX:-NMdrmUu2kHlz_pkghze:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/f16bc095e8a503d1a47f6a4afb3591c6a0276ece/pkg/sql/parser/sql.y#L5592)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

yes. You can also do this:
```
// SHOW TENANT { <tenant_spec> | ALL }  [ WITH <options> ]
// SHOW TENANTS                         [ WITH <options> ]
//
// Options:
//     REPLICATION STATUS
//     CAPABILITIES
```

(nb: CAPABILITIES, not CAPABILITY)
</blockquote></details>

Updated.
___
*[`pkg/sql/parser/sql.y` line 6347 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95013#-NMTaffpDTd2PqpFprcn:-NMe8_nBBGj79jr2KrGA:b-b8fcxk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f16bc095e8a503d1a47f6a4afb3591c6a0276ece/pkg/sql/parser/sql.y#L6347)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

We have used this pattern elsewhere already. For example, `BACKUP ... WITH detached` is implicit for `WITH detached = true`.

The advantage of supporting this is that you can then use a single grammar rule for both GRANT and REVOKE.
</blockquote></details>

Ok, updated.
___
*[`pkg/sql/parser/sql.y` line 6355 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95013#-NMTaV79C9spop5FNmNt:-NMe8hdK5gRKd4IuKSQ8:btb7dp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f16bc095e8a503d1a47f6a4afb3591c6a0276ece/pkg/sql/parser/sql.y#L6355)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

1. make a single non-terminal `tenant_capability_list` for both grant and revoke in the grammar (both accept `= var_value`)
2. during planning, produce an error in REVOKE if there are assignments.
</blockquote></details>

Updated based on comment above.

**Review by knz — APPROVED** [review]
:lgtm: with nit

> Reviewed 17 of 18 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95013#-:-NMeb--96OVtoC1VU7R9:b-xv64lu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani, @dikshant, @ecwall, and @rafiss)

___
*[`pkg/sql/tenant_capability.go` line 64 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/95013#-NMeabAS1CmAutpPNG3w:-NMeabATBvdOcdWjbI9H:bhhcjq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1627a63800d767993a1dcb8f1abd3523f49555d9/pkg/sql/tenant_capability.go#L64)):*
> ```Go
> 			capabilities.CanAdminSplit, err = capability.GetBoolValue(isRevoke)
> 		default:
> 			err = errors.Newf("invalid capability")
> ```

`"invalid capability: %q", capabilityName`

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95013)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @dikshant, @knz, and @rafiss)

___
*[`pkg/sql/tenant_capability.go` line 64 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/95013#-NMeabAS1CmAutpPNG3w:-NMegZfkAGIsqsHVMcp1:bnuoceo) ([raw file](https://github.com/cockroachdb/cockroach/blob/1627a63800d767993a1dcb8f1abd3523f49555d9/pkg/sql/tenant_capability.go#L64)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

`"invalid capability: %q", capabilityName`
</blockquote></details>

I handled adding the `capabilityName` for this error and the errors from `GetBoolValue` (and future `Get*Value` methods) below:
```		
		if err != nil {
			return pgerror.Wrapf(
				err,
				pgcode.InvalidParameterValue,
				"error parsing capability %s",  // I will change this to %q though based on your feedback
				capabilityName,
			)
		}
```
so they would have a more consistent format:
```
statement error error parsing capability not_a_capability: invalid capability
ALTER TENANT [5] GRANT CAPABILITY not_a_capability=true

statement error error parsing capability can_admin_split: value must be bool
ALTER TENANT [5] GRANT CAPABILITY can_admin_split=1

statement error error parsing capability not_a_capability: invalid capability
ALTER TENANT [5] REVOKE CAPABILITY not_a_capability

statement error error parsing capability can_admin_split: revoke must not specify value
ALTER TENANT [5] REVOKE CAPABILITY can_admin_split=false
```

**Comment by ecwall** [comment]
bors r=knz

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95013)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @dikshant, @ecwall, and @rafiss)

___
*[`pkg/sql/tenant_capability.go` line 64 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/95013#-NMeabAS1CmAutpPNG3w:-NMf4aXc2NV4Z16JFiTu:b-r2d4w4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1627a63800d767993a1dcb8f1abd3523f49555d9/pkg/sql/tenant_capability.go#L64)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

I handled adding the `capabilityName` for this error and the errors from `GetBoolValue` (and future `Get*Value` methods) below:
```		
		if err != nil {
			return pgerror.Wrapf(
				err,
				pgcode.InvalidParameterValue,
				"error parsing capability %s",  // I will change this to %q though based on your feedback
				capabilityName,
			)
		}
```
so they would have a more consistent format:
```
statement error error parsing capability not_a_capability: invalid capability
ALTER TENANT [5] GRANT CAPABILITY not_a_capability=true

statement error error parsing capability can_admin_split: value must be bool
ALTER TENANT [5] GRANT CAPABILITY can_admin_split=1

statement error error parsing capability not_a_capability: invalid capability
ALTER TENANT [5] REVOKE CAPABILITY not_a_capability

statement error error parsing capability can_admin_split: revoke must not specify value
ALTER TENANT [5] REVOKE CAPABILITY can_admin_split=false
```

</blockquote></details>

You did not include the capability name in the error generated *if the capability name is not recognized* -- e.g. `alter tenant .. revoke capability THIS_CAPABILITY_DOES_NOT_EXIST`. We need to provide more detail in that error too.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95013)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @dikshant, @ecwall, and @rafiss)

___
*[`pkg/sql/tenant_capability.go` line 64 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/95013#-NMeabAS1CmAutpPNG3w:-NMf4jqp8I75Y_Qitm50:b-pgsvnc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1627a63800d767993a1dcb8f1abd3523f49555d9/pkg/sql/tenant_capability.go#L64)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

You did not include the capability name in the error generated *if the capability name is not recognized* -- e.g. `alter tenant .. revoke capability THIS_CAPABILITY_DOES_NOT_EXIST`. We need to provide more detail in that error too.
</blockquote></details>

oh and that case deserves a test as well.

**Pull request merged**
