### PR TITLE
backupccl: fix double close of backup mem account

### PR DESCRIPTION
**Pull request by adityamaru**
Release note: None

### CODE REVIEW

**Comment by adityamaru** [comment]
I'm unsure how to test this, and none of our roachtests have picked this up either. Qualification on v21.2.5 however has thrown up a sentry report that logs a [crash](https://sentry.io/organizations/cockroach-labs/issues/2951739716/?project=164528&query=is%3Aunresolved+release%3Av21.2.4-171-g5afb632f77&statsPeriod=14d). Looking around at other processors, and comments on InternalClose this seemed the most appropriate fix.

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76190#-:-MvLYpJs1L8rPWPrO0S0:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

___
*[pkg/ccl/backupccl/backup_processor.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76190#-MvLYadREFidqWqhtjLJ:-MvLYadS79x0Db3N04az:byfv9us) ([raw file](https://github.com/cockroachdb/cockroach/blob/4623d758bdbe2cc66320353f8ce03117a5bb35c1/pkg/ccl/backupccl/backup_processor.go#L218)):*
> ```Go
> 	bp.cancelAndWaitForWorker()
> 	// While it is safe to call `cancelAndWaitForWorker` more than once, all other
> 	// cleanup operations should only be called once. The condition below prevents
> ```

you say this, but then go ahead and call one of the "other cleanup operations". I'd scatch this comment completely.

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76190)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @dt)

___
*[pkg/ccl/backupccl/backup_processor.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76190#-MvLYadREFidqWqhtjLJ:-MvOgIZq9MjPz2Q8gi78:be8ws5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/4623d758bdbe2cc66320353f8ce03117a5bb35c1/pkg/ccl/backupccl/backup_processor.go#L218)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

you say this, but then go ahead and call one of the "other cleanup operations". I'd scatch this comment completely.
</blockquote></details>

heh, fair enough, deleted

**Comment by adityamaru** [comment]
Bazel failure is unrelated `TestLogic/local-declarative-schema/crdb_internal/max_retry_counter`.

TFTR!

bors r=andreimatei

**Pull request merged**
