### PR TITLE
sql: allow mixed-type IN expressions

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, the `IN` operator required that the LHS and every element in
the RHS tuple was of the same type. This is overly restrictive, because
an `IN` expression is equivalent to one `=` expression between the LHS
and every element of the RHS, and we already support mixed-type
comparisons between some types (e.g. numeric types).

Now, an `IN` expression will type-check successfully as long as every
element of the RHS is comparable to the LHS.

Found while investigating #12035.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
:lgtm: but we should note (probably in a test with an explanation) that this approach of resolving each comparison independently does limit our ability to perform constant type coercion across all expressions. For instance, since we're typing the left-hand expression blindly, I don't believe the following expression will type check successfully any longer: `'2010-09-28' IN ('2010-09-28'::DATE)`. Even if we were to take into account the first comparison when resolving the left-hand side, something like `'2010-09-28' IN ('2010-09-27', '2010-09-28'::DATE)` would still now fail. I'm pretty sure there are cases along these lines where #14674 now prevents successful typing as well.

That said, both are still pretty clear wins!

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/parser/type_check.go, line 930 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14810#-KhTPkdBjsN2p8NVcJ6e:-KhTPkdBjsN2p8NVcJ6f:b-tpgnv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/187f4e548a7066100f4fba17e8eabcda65f1324a/pkg/sql/parser/type_check.go#L930)):*
> ```Go
> 		rightTuple.types = make(TTuple, len(rightTuple.Exprs))
> 		var firstNonNullType Type
> 		for i, elt := range rightTuple.Exprs {
> ```

`elt`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14810#-:-KhTQ933pfFGfChOFOeB:bf0tlbk)*

**Comment by jordanlewis** [comment]
Great point and TFTR. I've added a TODO test that illustrates this issue. I did think about this issue while writing the code - it obviously is not great that the LHS is being typed blindly. I went down the route of collecting all of the LHS type outputs of each comparison typecheck, but it wasn't immediately clear how to unify those so I gave up in favor of this simpler practical solution.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/parser/type_check.go, line 930 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14810#-KhTPkdBjsN2p8NVcJ6e:-KhTWsyOMAIIdbisuPiI:bju6l0) ([raw file](https://github.com/cockroachdb/cockroach/blob/187f4e548a7066100f4fba17e8eabcda65f1324a/pkg/sql/parser/type_check.go#L930)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`elt`?
</blockquote></details>

shorthand for element, but I've picked a more descriptive variable name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14810#-:-KhTWz7DdbU7EwFaPzMZ:b-9mvdh0)*

**Comment by jordanlewis** [comment]
Hmm, maybe I'll need to deal with that sooner rather than later. This patch now causes tuples that have mutually incomparable elements to panic when being used as the RHS of an `IN`, because we try to sort them.

It would be great if we could determine the comparability of types in an easier way than searching pairwise via `typeCheckComparisonOp`. Maybe types should have a method similar to `Equivalent` that return true if the input type is comparable to the receiver.

**Comment by knz** [comment]
Ok on principle but two general questions:
1) what about making the LHS type desired but not required on the tuple; this will ensure a moderate amount of coercion
2) regarding the tuple sorting, is there an option to re-introduce the boolean "isSorted" that was there earlier, and simply unset it if the types are not mutually comparable?

---

Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14810#-:-KhWpxJc604shm7gj1YQ:bnw4hkl)*

**Comment by nvanbenschoten** [comment]
@knz `DTuple` still has a field `Sorted`. We could change `DTuple.sort` to only sort if the types are all mutually comparable.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14810#-:-KhYSJWyQhs1ppERkOE-:b-f5wzcr)*

**Comment by jordanlewis** [comment]
Determining whether all types are mutually comparable is currently burdensome because of the relatively high cost of running `typeCheckComparisonOp` (which contains a call to `typeCheckOverloadedExprs`).

I think it would be nice if types had a method `ComparableTo(typ Type)` that returns true if they're comparable to `typ`. That would make me less unhappy about checking all unique pairs of the tuple for comparability.

The other option I was mulling over was reverting `IN` type checking to use `typeCheckSameTypedExprs`, but augmenting that function (or a helper thereof) with an option that permits types in the input to be comparable and not exactly `Equivalent`. Thought on this?

**Comment by knz** [comment]
I'm sorry I didn't react on this earlier. Yes, extending `typeCheckSameTypedExprs` with a flag which decides between "same types" and "equivalent types" would be a good idea.

**Pull request closed without merging**
