### PR TITLE
ui: remove some functions generated by protobufjs

### PR DESCRIPTION
**Pull request by sjbarag**
Previously, a pretty wide range of methods was generated for each JS
class produced by protobufjs. Some of these were unused, or were only
used in tests (and were thus easy to replace). Luckily, the pbjs CLI
offers flags to not emit some of these! Specifically: 

* --no-create removes the static .create() method. It's nearly
  equivalent to the constructor that's already generated. Foo.create()
  accepts a pure JS object, but new Foo() requires nested types to be
  constructed with new Bar(). Its few uses are easily replaced.
* --no-verify removes the .verify() method. It was never used.
* --no-convert removes the .toJSON() and .fromJSON() methods, which
  were only used in a few tests (most uses were stub definitions).
* --no-delimited removes the .encodeDelimited and .encodeDelimited
  methods, which were never used.

With these flags added to the pbjs invocation, we can reduce emitted
file sizes pretty drastically (all values in kilobytes, measured with
`du -k`):

    protos.d.ts*                        5840 ->  2788 (- 3052)
    protos.js                          17464 ->  7300 (-10164)
    cluster-ui/dist/main.js            14148 -> 11136 (- 3012)
    db-console-ccl/assets/bundle.js    32732 -> 23684 (- 9048)

    *This has no impact on user-facing build sizes or load times, but
    does make the typescript compiler have to less work at build time.

At runtime, a reduced bundle.js reduces roughly one second off the
"first contentful paint" metric reported by Lighthouse.

Part of: #88876
Release note: None

-----

Impact on Lighthouse scores:

### Before
Screenshot 2023-04-12 at 2 44 29 PM

### After
Screenshot 2023-04-12 at 2 44 12 PM

### Summary
This shaves ~1s off of page load times for DB Console when run with `cockroach start-single-node --insecure` on a remote machine (24-core Xeon), with SSH port-forwarding local `8080` to that machine's `8080`.

### CODE REVIEW

**Comment by sjbarag** [comment]
Currently a draft to let CI take the wheel

**Comment by sjbarag** [comment]
No idea if this'll backport cleanly (probably not), but it's worth a shot.

**Review by koorosh — APPROVED** [review]
:lgtm_strong: 

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101340#-:-NTxkOcDAAjp0ygqhCGj:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag and @nathanstilwell)

**Comment by sjbarag** [comment]
bors r=koorosh

**Comment by sjbarag** [comment]
good call, craig. label removed.

bors r+

**Review by nathanstilwell — COMMENTED** [review]
Really nice work @sjbarag. 👏🏼

**Pull request merged**
