### PR TITLE
storage: handle MVCC range keys in `pebbleMVCCScanner`

### LINKED ISSUE #88908: storage: integrate `pointSynthesizingIter` into `pebbleMVCCScanner`
Currently, MVCC scans across spans with MVCC range tombstones will use a `pointSynthesizingIter` to synthesize point tombstones for range tombstones. This allowed the `pebbleMVCCScanner` logic to remain unchanged, and only concern itself with point tombstones. However, this likely has a performance penalty -- certainly because of the additional dynamic dispatch, but probably also because the `pebbleMVCCScanner` logic could process the range tombstones more efficiently without the synthesis.

We should consider integrating MVCC range tombstone logic directly into `pebbleMVCCScanner` if the performance benefit is found to be large enough. This will likely result in a significant complexity increase.

Jira issue: CRDB-20031

Epic CRDB-20465

### PR DESCRIPTION
**Pull request by erikgrinaker**
**storage: add some `TestMVCCHistories` range key cases for `MVCCGet`**

Release note: None

**storage: simplify some `pebbleMVCCScanner` iteration code**

This also yields a nice performance boost for reverse scans, by removing unnecessary peeking which incurs key copies.

```
name                                                                         old time/op    new time/op    delta
MVCCReverseScan_Pebble/rows=1/versions=1/valueSize=8/numRangeKeys=0-24         5.65µs ± 2%    5.62µs ± 1%    ~     (p=0.897 n=5+5)
MVCCReverseScan_Pebble/rows=1/versions=10/valueSize=8/numRangeKeys=0-24        22.7µs ± 0%    22.9µs ± 1%  +0.94%  (p=0.032 n=5+5)
MVCCReverseScan_Pebble/rows=100/versions=1/valueSize=8/numRangeKeys=0-24       43.0µs ± 1%    40.3µs ± 1%  -6.18%  (p=0.008 n=5+5)
MVCCReverseScan_Pebble/rows=100/versions=10/valueSize=8/numRangeKeys=0-24       352µs ± 1%     340µs ± 2%  -3.57%  (p=0.008 n=5+5)
MVCCReverseScan_Pebble/rows=10000/versions=1/valueSize=8/numRangeKeys=0-24     3.41ms ± 1%    3.21ms ± 1%  -5.68%  (p=0.008 n=5+5)
MVCCReverseScan_Pebble/rows=10000/versions=10/valueSize=8/numRangeKeys=0-24    32.5ms ± 2%    31.1ms ± 6%    ~     (p=0.095 n=5+5)
```

Release note: None

**storage: handle MVCC range keys in `pebbleMVCCScanner`**

This patch removes `PointSynthesizingIter`, and instead implements MVCC range key handling in `pebbleMVCCScanner` directly. `PointSynthesizingIter` was a mistake. It was intended to reduce the complexity of integrating MVCC range key processing into `pebbleMVCCScanner`, but ended up introducing even more complexity at a significant performance cost.

`MVCCScan` point synthesis has changed slightly: while point keys were previously synthesized at the start bound of an MVCC range key, they are now only synthesized above existing point keys. This was mostly an artifact of having to do conflict checks based on synthesized points (to ensure bare range keys were handled), but this is no longer necessary since `pebbleMVCCScanner` can inspect the range keys directly.

`MVCCGet` point synthesis remains unchanged: we always synthesize point keys regardless of whether there is an existing point key below it. This is necessary for e.g. conflict checks on top of `MVCCGet`, such as transaction read refreshes.

`MVCCScan` shows a significant performance gain with range keys, and negligible overhead without them. We still see a hefty performance penalty when range keys are present though, compared to the `numRangeKeys=0` case, which likely needs optimization in Pebble.

```
name                                                                    old time/op    new time/op     delta
MVCCScan_Pebble/rows=1/versions=1/valueSize=8/numRangeKeys=0-24           5.31µs ± 1%     5.39µs ± 2%     ~     (p=0.095 n=5+5)
MVCCScan_Pebble/rows=1/versions=1/valueSize=8/numRangeKeys=1-24           10.7µs ± 1%     10.2µs ± 3%   -4.39%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=1/versions=1/valueSize=8/numRangeKeys=100-24          144µs ± 1%       94µs ± 2%  -34.54%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=1/versions=10/valueSize=8/numRangeKeys=0-24          20.4µs ± 2%     20.6µs ± 3%     ~     (p=0.421 n=5+5)
MVCCScan_Pebble/rows=1/versions=10/valueSize=8/numRangeKeys=1-24          28.0µs ± 2%     26.7µs ± 2%   -4.41%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=1/versions=10/valueSize=8/numRangeKeys=100-24         120µs ± 1%       82µs ± 1%  -31.89%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=100/versions=1/valueSize=8/numRangeKeys=0-24         33.0µs ± 1%     33.3µs ± 1%     ~     (p=0.056 n=5+5)
MVCCScan_Pebble/rows=100/versions=1/valueSize=8/numRangeKeys=1-24         55.0µs ± 1%     46.1µs ± 1%  -16.15%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=100/versions=1/valueSize=8/numRangeKeys=100-24        158µs ± 1%      142µs ± 1%  -10.15%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=100/versions=10/valueSize=8/numRangeKeys=0-24         137µs ± 1%      139µs ± 3%   +1.72%  (p=0.032 n=5+5)
MVCCScan_Pebble/rows=100/versions=10/valueSize=8/numRangeKeys=1-24         223µs ± 2%      187µs ± 0%  -15.79%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=100/versions=10/valueSize=8/numRangeKeys=100-24       322µs ± 1%      264µs ± 1%  -17.95%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=10000/versions=1/valueSize=8/numRangeKeys=0-24       2.41ms ± 1%     2.41ms ± 0%     ~     (p=0.690 n=5+5)
MVCCScan_Pebble/rows=10000/versions=1/valueSize=8/numRangeKeys=1-24       3.99ms ± 1%     3.19ms ± 0%  -20.08%  (p=0.016 n=5+4)
MVCCScan_Pebble/rows=10000/versions=1/valueSize=8/numRangeKeys=100-24     4.74ms ± 1%     3.77ms ± 1%  -20.53%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=10000/versions=10/valueSize=8/numRangeKeys=0-24      10.7ms ± 3%     10.7ms ± 3%     ~     (p=0.421 n=5+5)
MVCCScan_Pebble/rows=10000/versions=10/valueSize=8/numRangeKeys=1-24      18.1ms ± 1%     15.0ms ± 0%  -17.33%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=10000/versions=10/valueSize=8/numRangeKeys=100-24    23.1ms ± 4%     16.4ms ± 6%  -28.90%  (p=0.008 n=5+5)
```

`MVCCScan` in reverse shows a moderate improvement, primarily due to the additional checks needed to detect bare range keys in reverse since it can land on them without `RangeKeyChanged` firing.

```
name                                                                           old time/op    new time/op    delta
MVCCReverseScan_Pebble/rows=1/versions=1/valueSize=8/numRangeKeys=0-24           5.69µs ± 2%    5.68µs ± 1%     ~     (p=0.841 n=5+5)
MVCCReverseScan_Pebble/rows=1/versions=1/valueSize=8/numRangeKeys=1-24           11.0µs ± 2%    10.8µs ± 1%   -2.01%  (p=0.016 n=5+5)
MVCCReverseScan_Pebble/rows=1/versions=1/valueSize=8/numRangeKeys=100-24          100µs ± 1%      95µs ± 1%   -5.67%  (p=0.008 n=5+5)
MVCCReverseScan_Pebble/rows=1/versions=10/valueSize=8/numRangeKeys=0-24          23.1µs ± 1%    23.4µs ± 1%     ~     (p=0.056 n=5+5)
MVCCReverseScan_Pebble/rows=1/versions=10/valueSize=8/numRangeKeys=1-24          31.5µs ± 1%    31.4µs ± 1%     ~     (p=0.421 n=5+5)
MVCCReverseScan_Pebble/rows=1/versions=10/valueSize=8/numRangeKeys=100-24        87.5µs ± 1%    91.7µs ± 1%   +4.88%  (p=0.008 n=5+5)
MVCCReverseScan_Pebble/rows=100/versions=1/valueSize=8/numRangeKeys=0-24         40.6µs ± 1%    41.3µs ± 1%   +1.60%  (p=0.008 n=5+5)
MVCCReverseScan_Pebble/rows=100/versions=1/valueSize=8/numRangeKeys=1-24         60.8µs ± 1%    55.8µs ± 1%   -8.18%  (p=0.008 n=5+5)
MVCCReverseScan_Pebble/rows=100/versions=1/valueSize=8/numRangeKeys=100-24        159µs ± 1%     145µs ± 0%   -8.49%  (p=0.008 n=5+5)
MVCCReverseScan_Pebble/rows=100/versions=10/valueSize=8/numRangeKeys=0-24         342µs ± 1%     344µs ± 3%     ~     (p=1.000 n=5+5)
MVCCReverseScan_Pebble/rows=100/versions=10/valueSize=8/numRangeKeys=1-24         486µs ± 1%     457µs ± 1%   -6.05%  (p=0.008 n=5+5)
MVCCReverseScan_Pebble/rows=100/versions=10/valueSize=8/numRangeKeys=100-24       701µs ± 3%     663µs ± 2%   -5.44%  (p=0.008 n=5+5)
MVCCReverseScan_Pebble/rows=10000/versions=1/valueSize=8/numRangeKeys=0-24       3.12ms ± 1%    3.17ms ± 0%   +1.36%  (p=0.008 n=5+5)
MVCCReverseScan_Pebble/rows=10000/versions=1/valueSize=8/numRangeKeys=1-24       4.51ms ± 2%    4.09ms ± 1%   -9.36%  (p=0.008 n=5+5)
MVCCReverseScan_Pebble/rows=10000/versions=1/valueSize=8/numRangeKeys=100-24     5.36ms ± 0%    4.66ms ± 1%  -13.21%  (p=0.008 n=5+5)
MVCCReverseScan_Pebble/rows=10000/versions=10/valueSize=8/numRangeKeys=0-24      32.5ms ± 8%    31.6ms ± 6%     ~     (p=0.310 n=5+5)
MVCCReverseScan_Pebble/rows=10000/versions=10/valueSize=8/numRangeKeys=1-24      45.7ms ± 6%    40.2ms ±10%  -12.14%  (p=0.016 n=5+5)
MVCCReverseScan_Pebble/rows=10000/versions=10/valueSize=8/numRangeKeys=100-24    64.5ms ± 6%    59.0ms ±11%   -8.50%  (p=0.032 n=5+5)
```

Scans across garbage show even better performance gains:

```
name                                                                                old time/op  new time/op  delta
MVCCScanGarbage_Pebble/rows=1/versions=1/numRangeKeys=0/tombstones=false-24         4.99µs ± 2%  4.81µs ± 1%   -3.64%  (p=0.008 n=5+5)
MVCCScanGarbage_Pebble/rows=1/versions=1/numRangeKeys=0/tombstones=true-24          5.10µs ± 1%  5.03µs ± 1%   -1.33%  (p=0.032 n=5+5)
MVCCScanGarbage_Pebble/rows=1/versions=1/numRangeKeys=1/tombstones=false-24         9.25µs ± 3%  8.47µs ± 2%   -8.41%  (p=0.008 n=5+5)
MVCCScanGarbage_Pebble/rows=1/versions=1/numRangeKeys=1/tombstones=true-24          9.44µs ± 1%  8.94µs ± 3%   -5.33%  (p=0.008 n=5+5)
MVCCScanGarbage_Pebble/rows=1/versions=1/numRangeKeys=100/tombstones=false-24        150µs ± 1%    96µs ± 1%  -36.27%  (p=0.008 n=5+5)
MVCCScanGarbage_Pebble/rows=1/versions=1/numRangeKeys=100/tombstones=true-24        96.7µs ± 0%  95.4µs ± 1%   -1.33%  (p=0.008 n=5+5)
MVCCScanGarbage_Pebble/rows=1/versions=10/numRangeKeys=0/tombstones=false-24        9.10µs ± 3%  9.24µs ± 2%     ~     (p=0.151 n=5+5)
MVCCScanGarbage_Pebble/rows=1/versions=10/numRangeKeys=0/tombstones=true-24         9.43µs ± 2%  9.41µs ± 2%     ~     (p=0.841 n=5+5)
MVCCScanGarbage_Pebble/rows=1/versions=10/numRangeKeys=1/tombstones=false-24        13.2µs ± 3%  12.6µs ± 2%   -4.73%  (p=0.008 n=5+5)
MVCCScanGarbage_Pebble/rows=1/versions=10/numRangeKeys=1/tombstones=true-24         14.5µs ± 1%  13.8µs ± 2%   -4.60%  (p=0.008 n=5+5)
MVCCScanGarbage_Pebble/rows=1/versions=10/numRangeKeys=100/tombstones=false-24       160µs ± 1%   105µs ± 1%  -34.67%  (p=0.008 n=5+5)
MVCCScanGarbage_Pebble/rows=1/versions=10/numRangeKeys=100/tombstones=true-24        106µs ± 1%   105µs ± 1%     ~     (p=0.548 n=5+5)
MVCCScanGarbage_Pebble/rows=100/versions=1/numRangeKeys=0/tombstones=false-24       22.2µs ± 1%  22.6µs ± 1%   +2.21%  (p=0.008 n=5+5)
MVCCScanGarbage_Pebble/rows=100/versions=1/numRangeKeys=0/tombstones=true-24        32.0µs ± 0%  32.2µs ± 1%   +0.80%  (p=0.016 n=5+5)
MVCCScanGarbage_Pebble/rows=100/versions=1/numRangeKeys=1/tombstones=false-24       18.9µs ± 1%  18.2µs ± 1%   -3.64%  (p=0.008 n=5+5)
MVCCScanGarbage_Pebble/rows=100/versions=1/numRangeKeys=1/tombstones=true-24        55.6µs ± 0%  45.4µs ± 1%  -18.27%  (p=0.008 n=5+5)
MVCCScanGarbage_Pebble/rows=100/versions=1/numRangeKeys=100/tombstones=false-24      215µs ± 1%   120µs ± 2%  -44.45%  (p=0.008 n=5+5)
MVCCScanGarbage_Pebble/rows=100/versions=1/numRangeKeys=100/tombstones=true-24       277µs ± 1%   148µs ± 1%  -46.36%  (p=0.008 n=5+5)
MVCCScanGarbage_Pebble/rows=100/versions=10/numRangeKeys=0/tombstones=false-24       108µs ± 1%   109µs ± 3%     ~     (p=1.000 n=5+5)
MVCCScanGarbage_Pebble/rows=100/versions=10/numRangeKeys=0/tombstones=true-24        122µs ± 0%   122µs ± 2%     ~     (p=0.421 n=5+5)
MVCCScanGarbage_Pebble/rows=100/versions=10/numRangeKeys=1/tombstones=false-24      67.6µs ± 1%  67.0µs ± 1%     ~     (p=0.095 n=5+5)
MVCCScanGarbage_Pebble/rows=100/versions=10/numRangeKeys=1/tombstones=true-24        200µs ± 0%   168µs ± 1%  -16.04%  (p=0.008 n=5+5)
MVCCScanGarbage_Pebble/rows=100/versions=10/numRangeKeys=100/tombstones=false-24     324µs ± 1%   178µs ± 1%  -45.17%  (p=0.008 n=5+5)
MVCCScanGarbage_Pebble/rows=100/versions=10/numRangeKeys=100/tombstones=true-24      306µs ± 1%   274µs ± 1%  -10.33%  (p=0.008 n=5+5)
MVCCScanGarbage_Pebble/rows=10000/versions=1/numRangeKeys=0/tombstones=false-24     1.61ms ± 0%  1.65ms ± 2%   +2.27%  (p=0.008 n=5+5)
MVCCScanGarbage_Pebble/rows=10000/versions=1/numRangeKeys=0/tombstones=true-24      2.33ms ± 2%  2.35ms ± 1%     ~     (p=0.151 n=5+5)
MVCCScanGarbage_Pebble/rows=10000/versions=1/numRangeKeys=1/tombstones=false-24      141µs ± 0%   140µs ± 1%     ~     (p=0.310 n=5+5)
MVCCScanGarbage_Pebble/rows=10000/versions=1/numRangeKeys=1/tombstones=true-24      4.31ms ± 1%  3.25ms ± 0%  -24.59%  (p=0.008 n=5+5)
MVCCScanGarbage_Pebble/rows=10000/versions=1/numRangeKeys=100/tombstones=false-24   6.64ms ± 8%  1.35ms ± 1%  -79.67%  (p=0.008 n=5+5)
MVCCScanGarbage_Pebble/rows=10000/versions=1/numRangeKeys=100/tombstones=true-24    16.4ms ± 2%   4.0ms ± 1%  -75.65%  (p=0.008 n=5+5)
MVCCScanGarbage_Pebble/rows=10000/versions=10/numRangeKeys=0/tombstones=false-24    9.33ms ± 1%  9.24ms ± 0%     ~     (p=0.310 n=5+5)
MVCCScanGarbage_Pebble/rows=10000/versions=10/numRangeKeys=0/tombstones=true-24     10.3ms ± 1%  10.1ms ± 1%   -1.48%  (p=0.008 n=5+5)
MVCCScanGarbage_Pebble/rows=10000/versions=10/numRangeKeys=1/tombstones=false-24     213µs ± 2%   213µs ± 1%     ~     (p=0.841 n=5+5)
MVCCScanGarbage_Pebble/rows=10000/versions=10/numRangeKeys=1/tombstones=true-24     17.7ms ± 1%  14.4ms ± 3%  -18.61%  (p=0.008 n=5+5)
MVCCScanGarbage_Pebble/rows=10000/versions=10/numRangeKeys=100/tombstones=false-24  11.1ms ± 4%   2.9ms ± 4%  -73.89%  (p=0.008 n=5+5)
MVCCScanGarbage_Pebble/rows=10000/versions=10/numRangeKeys=100/tombstones=true-24   18.2ms ± 1%  15.2ms ± 4%  -16.45%  (p=0.008 n=5+5)
```

And `MVCCGet` performance remains largely unchanged, as expected given that the cost is dominated by the seek.

```
name                                                                     old time/op    new time/op    delta
MVCCGet_Pebble/batch=false/versions=1/valueSize=8/numRangeKeys=0-24        5.20µs ± 1%    5.23µs ± 2%    ~     (p=0.841 n=5+5)
MVCCGet_Pebble/batch=false/versions=1/valueSize=8/numRangeKeys=1-24        9.52µs ± 1%    9.23µs ± 1%  -3.07%  (p=0.008 n=5+5)
MVCCGet_Pebble/batch=false/versions=1/valueSize=8/numRangeKeys=100-24      92.4µs ± 1%    91.6µs ± 1%  -0.93%  (p=0.032 n=5+5)
MVCCGet_Pebble/batch=false/versions=10/valueSize=8/numRangeKeys=0-24       20.2µs ± 2%    20.2µs ± 3%    ~     (p=0.651 n=5+5)
MVCCGet_Pebble/batch=false/versions=10/valueSize=8/numRangeKeys=1-24       25.9µs ± 2%    25.5µs ± 1%    ~     (p=0.056 n=5+5)
MVCCGet_Pebble/batch=false/versions=10/valueSize=8/numRangeKeys=100-24     79.8µs ± 1%    80.1µs ± 2%    ~     (p=1.000 n=5+5)
MVCCGet_Pebble/batch=false/versions=100/valueSize=8/numRangeKeys=0-24      82.9µs ± 2%    83.3µs ± 1%    ~     (p=0.310 n=5+5)
MVCCGet_Pebble/batch=false/versions=100/valueSize=8/numRangeKeys=1-24      92.2µs ± 3%    90.2µs ± 1%    ~     (p=0.095 n=5+5)
MVCCGet_Pebble/batch=false/versions=100/valueSize=8/numRangeKeys=100-24     151µs ± 2%     149µs ± 3%    ~     (p=0.690 n=5+5)
MVCCGet_Pebble/batch=true/versions=1/valueSize=8/numRangeKeys=0-24         3.02µs ± 1%    3.04µs ± 1%    ~     (p=0.310 n=5+5)
MVCCGet_Pebble/batch=true/versions=1/valueSize=8/numRangeKeys=1-24         5.44µs ± 2%    5.29µs ± 3%    ~     (p=0.056 n=5+5)
MVCCGet_Pebble/batch=true/versions=1/valueSize=8/numRangeKeys=100-24       53.0µs ± 1%    52.7µs ± 1%    ~     (p=0.095 n=5+5)
MVCCGet_Pebble/batch=true/versions=10/valueSize=8/numRangeKeys=0-24        17.0µs ± 1%    17.1µs ± 2%    ~     (p=1.000 n=5+5)
MVCCGet_Pebble/batch=true/versions=10/valueSize=8/numRangeKeys=1-24        21.4µs ± 5%    20.9µs ± 3%    ~     (p=0.151 n=5+5)
MVCCGet_Pebble/batch=true/versions=10/valueSize=8/numRangeKeys=100-24      73.1µs ± 2%    72.7µs ± 1%    ~     (p=0.841 n=5+5)
MVCCGet_Pebble/batch=true/versions=100/valueSize=8/numRangeKeys=0-24       83.9µs ± 1%    84.3µs ± 1%    ~     (p=0.310 n=5+5)
MVCCGet_Pebble/batch=true/versions=100/valueSize=8/numRangeKeys=1-24       90.8µs ± 2%    90.5µs ± 1%    ~     (p=1.000 n=5+5)
MVCCGet_Pebble/batch=true/versions=100/valueSize=8/numRangeKeys=100-24      146µs ± 1%     146µs ± 0%    ~     (p=0.556 n=5+4)
```

Resolves #88908.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — DISMISSED** [review]
some comments about code comments on the second commit

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93753#-:-NJf9SvbESEgyT4nXe5P:b2osh5w)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @jbowens)

___
*[`pkg/storage/pebble_mvcc_scanner.go` line 1020 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93753#-NJf6Tn28y4Yy0pZtja1:-NJf6Tn28y4Yy0pZtja2:b1do4ar) ([raw file](https://github.com/cockroachdb/cockroach/blob/09e338c73dd9522d21501d859d5bb5ba4a74ec83/pkg/storage/pebble_mvcc_scanner.go#L1020)):*
> ```Go
> func (p *pebbleMVCCScanner) prevKey(key []byte) bool {
> 	for i := 0; i < p.itersBeforeSeek; i++ {
> 		peekedKey, ok := p.iterPeekPrev()
> ```

Nice catch! This use of `iterPeekPrev` was totally unnecessary.
It should improve performance when there is more than one version of `key` or the iter is 1 record after `key`, since there are multiple copies being made.
When there is only 1 version, it may not change much, since the peeking here will be replaced by the peeking copy happening in `backwardLatestVersion`.
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 1428 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93753#-NJf8o_VBM1uD100oy_Q:-NJf8o_VBM1uD100oy_R:b-t102g2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8f73092ab1467c161bfeef723640dd47a218ac5/pkg/storage/pebble_mvcc_scanner.go#L1428)):*
> ```Go
> 	if p.reverse && p.peeked {
> 		// If we have peeked at the previous entry, we need to advance the iterator
> 		// twice.
> ```

The advancing twice happens because of the shared `p.parent.Next` at the end of this function, so this comment is a bit confusing. How about rephrasing to something like:
// If we have peeked at the previous entry, we need to advance the iterator to get back to the current entry.
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 1432 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93753#-NJf925I644Df5plJzCu:-NJf925I644Df5plJzCv:b-lnugy7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8f73092ab1467c161bfeef723640dd47a218ac5/pkg/storage/pebble_mvcc_scanner.go#L1432)):*
> ```Go
> 		if !p.iterValid() {
> 			// We were peeked off the beginning of iteration. Seek to the first
> 			// entry, and then advance one step.
> ```

And then change the second sentence in this comment to:
Seek to the first entry, since that is the current entry.
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 1441 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93753#-NJf9NvB5o8zaxEX-0Uy:-NJf9NvB5o8zaxEX-0Uz:brwojtg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8f73092ab1467c161bfeef723640dd47a218ac5/pkg/storage/pebble_mvcc_scanner.go#L1441)):*
> ```Go
> 		}
> 	}
> 	p.parent.Next()
> ```

// Step forward from the current entry.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @sumeerbhola)

___
*[`pkg/storage/pebble_mvcc_scanner.go` line 1020 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93753#-NJf6Tn28y4Yy0pZtja1:-NJfL_MH2wY6Gd7Ism8H:bsu8z2p) ([raw file](https://github.com/cockroachdb/cockroach/blob/09e338c73dd9522d21501d859d5bb5ba4a74ec83/pkg/storage/pebble_mvcc_scanner.go#L1020)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Nice catch! This use of `iterPeekPrev` was totally unnecessary.
It should improve performance when there is more than one version of `key` or the iter is 1 record after `key`, since there are multiple copies being made.
When there is only 1 version, it may not change much, since the peeking here will be replaced by the peeking copy happening in `backwardLatestVersion`.
</blockquote></details>

We get non-trivial savings in single-version benchmarks too (~5%). Took me a second to see why, but here's what happens:

1. Assume we're positioned on `c@1` when calling `prevKey()`, with keys `a@1`, `b@1`, `c@1`.
2. In `prevKey()`, `iterPeekPrev()` returns `b@1`, calls `backwardLatestVersion(b@1)`.
3. In `backwardLatestVersion`, `iterPeekPrev()` again returns `b@1`, because we haven't stepped the iterator yet (this is the crucial point).
4. In `backwardLatestVersion`, `bytes.Equal(b@1, b@1)` is true, so we fall through to `iterPrev()` and then on the next cycle we peek `a@1` and return at `b@1`.

So for each key, we ended up calling `iterPeekPrev()` twice on the same position, which incurs additional `iterValid()` and `UnsafeKey()` calls, and an additional key comparison that was always equal.
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 1428 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93753#-NJf8o_VBM1uD100oy_Q:-NJfXHxREYwO-DiqyOnD:bjxsc8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8f73092ab1467c161bfeef723640dd47a218ac5/pkg/storage/pebble_mvcc_scanner.go#L1428)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The advancing twice happens because of the shared `p.parent.Next` at the end of this function, so this comment is a bit confusing. How about rephrasing to something like:
// If we have peeked at the previous entry, we need to advance the iterator to get back to the current entry.
</blockquote></details>

Yep. done.
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 1432 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93753#-NJf925I644Df5plJzCu:-NJfXPfb3NYxqqaKjd18:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8f73092ab1467c161bfeef723640dd47a218ac5/pkg/storage/pebble_mvcc_scanner.go#L1432)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

And then change the second sentence in this comment to:
Seek to the first entry, since that is the current entry.
</blockquote></details>

Done.
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 1441 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93753#-NJf9NvB5o8zaxEX-0Uy:-NJfXVhM2k52Qgh539YT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8f73092ab1467c161bfeef723640dd47a218ac5/pkg/storage/pebble_mvcc_scanner.go#L1441)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

// Step forward from the current entry.
</blockquote></details>

Done.

**Comment by erikgrinaker** [comment]
Going to hold this until #93988 merges.

**Review by jbowens — APPROVED** [review]
Looks great! Thanks for tackling this!

:lgtm:

> Reviewed 7 of 13 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93753#-:-NKKJ9ZD5IqTmZlIAmJT:b-8tg4r7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker and @sumeerbhola)

___
*[`pkg/storage/pebble_mvcc_scanner.go` line 677 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/93753#-NKK8niCDsRbRHZ7Npjb:-NKK8niCDsRbRHZ7Npjc:b-s6qycv) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f330f55b8e4eb1f404e7ed2a482c74e071aa03a/pkg/storage/pebble_mvcc_scanner.go#L677)):*
> ```Go
> func (p *pebbleMVCCScanner) getOne(ctx context.Context) (ok, added bool) {
> 	if !p.curUnsafeKey.Timestamp.IsEmpty() {
> 		// Range key where read ts > range key ts > point key ts. Synthesize a point
> ```

should this be `read ts >= range key ts`? 
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 1355 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/93753#-NKK408J1AGGmnK0omy9:-NKK408J1AGGmnK0omyA:b7blv56) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f330f55b8e4eb1f404e7ed2a482c74e071aa03a/pkg/storage/pebble_mvcc_scanner.go#L1355)):*
> ```Go
> 	for seeked || reverse || p.parent.RangeKeyChanged() {
> 		hasPoint, hasRange := p.parent.HasPointAndRange()
> ```

wonder if we should have an early exit here for `!hasRange` so that we can outdent the `hasRange` code block down below, and in the common no-range key case we don't call `RangeKeyChanged` or `pebbleIterator.RangeKeys`.
```
if !hasRange {
    p.curRangeKeys = MVCCRangeKeyStack{}
    return true
}
```

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93753)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @erikgrinaker, @jbowens, and @sumeerbhola)

___
*[`pkg/storage/pebble_mvcc_scanner.go` line 677 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/93753#-NKK8niCDsRbRHZ7Npjb:-NKNnXxxDNfRl7GPdHn9:b-1ash47) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f330f55b8e4eb1f404e7ed2a482c74e071aa03a/pkg/storage/pebble_mvcc_scanner.go#L677)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

should this be `read ts >= range key ts`? 
</blockquote></details>

Yes, and >= point key ts, updated.
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 1355 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/93753#-NKK408J1AGGmnK0omy9:-NKNnb4lElRcZtxOvA3f:b-n8d2d3) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f330f55b8e4eb1f404e7ed2a482c74e071aa03a/pkg/storage/pebble_mvcc_scanner.go#L1355)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

wonder if we should have an early exit here for `!hasRange` so that we can outdent the `hasRange` code block down below, and in the common no-range key case we don't call `RangeKeyChanged` or `pebbleIterator.RangeKeys`.
```
if !hasRange {
    p.curRangeKeys = MVCCRangeKeyStack{}
    return true
}
```
</blockquote></details>

Thanks for the nudge, I was able to simplify this code even further, at no performance cost.

**Pull request merged**
