### PR TITLE
builtins: implement the ST_MakeLine aggregate

### LINKED ISSUE #48979: geo/geomfn: implement ST_MakeLine({geometry})
Implement `ST_MakeLine` on arguments {geometry}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_MakeLine.html).

_Observers: Please react to this issue if you need this functionality._

For Geometry builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geomfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geomfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
  * When using GEOS, you can reference the [C API](https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in) for which functions are available. Unfortunately, Windows is not currently supported when using GEOS.
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end (your exhaustive unit tests go the above mentioned packages!).
* Ensure the documentation is regenerated by calling `make buildshort`. You can also play with it by calling `./cockroach demo --empty` afterwards.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48552 for an example PR.

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-06-30T05:29:57Z. Changes to titles, body and labels may be overwritten.</sub>

### PR DESCRIPTION
**Pull request by otan**
Resolves #48979
Release note (sql change): Implement the ST_MakeLine aggregate builtin.

### CODE REVIEW

**Comment by otan** [comment]
___
*[pkg/sql/logictest/testdata/logic_test/geospatial, line 3767 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52631#-MET6HOH-Q1N8rOXfEgB:-MET6HOH-Q1N8rOXfEgC:bpjbpc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/06ad69961fb15ef2e73170dd7549c35f21727d54/pkg/sql/logictest/testdata/logic_test/geospatial#L3767)):*
> ```
> SRID=4326;POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0))                                   false  false
> 
> subtest translate_test
> ```

(this subtest melds with the previous "geometry_test" subtest, so deleting it)

**Comment by otan** [comment]
___
*[pkg/sql/logictest/testdata/logic_test/geospatial, line 3787 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52631#-MET6MeQ12r5A_F8Kv16:-MET6MeQ12r5A_F8Kv17:bdlrgki) ([raw file](https://github.com/cockroachdb/cockroach/blob/049f55176293d0adfcab5c7aee8ebe2391092c60/pkg/sql/logictest/testdata/logic_test/geospatial#L3787)):*
> ```
> POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0))                    POLYGON ((1 1, 2 1, 2 2, 1 2, 1 1))
> 
> query TTTT
> ```

(this is a move)

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52631)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[docs/generated/sql/aggregates.md, line 188 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52631#-MEYIPBT1x9pzOq6Jfys:-MEYIPBUBbwp7gpO5RMy:bqxhyrh) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e12b8d4a95be9404c8f2b42c9e55cf6f02d9f29/docs/generated/sql/aggregates.md#L188)):*
> ```Markdown
> <tr><td><a name="sqrdiff"></a><code>sqrdiff(arg1: <a href="int.html">int</a>) &rarr; <a href="decimal.html">decimal</a></code></td><td><span class="funcdesc"><p>Calculates the sum of squared differences from the mean of the selected values.</p>
> </span></td></tr>
> <tr><td><a name="st_makeline"></a><code>st_makeline(arg1: geometry) &rarr; geometry</code></td><td><span class="funcdesc"><p>Forms a LineString from Point, MultiPoint or LineStrings. Other shapes will be ignored.</p>
> ```

PostGIS https://postgis.net/docs/ST_MakeLine.html claims that other shapes will cause an error.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 617 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52631#-MEYJIFd4h3QUqKF6Eyw:-MEYJIFd4h3QUqKF6Eyx:b8xbyf4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e12b8d4a95be9404c8f2b42c9e55cf6f02d9f29/pkg/sql/sem/builtins/aggregate_builtins.go#L617)):*
> ```Go
> // Reset implements the AggregateFunc interface.
> func (agg *stMakeLineAgg) Reset(context.Context) {
> 	agg.flatCoords = nil
> ```

is the reuse for performance? If so, should this do `agg.flatCoords = agg.flatCoord[:0]`?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52631)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[docs/generated/sql/aggregates.md, line 188 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52631#-MEYIPBT1x9pzOq6Jfys:-MEYLGeg2T5OZ8trsnNw:baaaqa0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e12b8d4a95be9404c8f2b42c9e55cf6f02d9f29/docs/generated/sql/aggregates.md#L188)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

PostGIS https://postgis.net/docs/ST_MakeLine.html claims that other shapes will cause an error.
</blockquote></details>

I tried and it does not.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 617 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52631#-MEYJIFd4h3QUqKF6Eyw:-MEYL_dh02yEf7cTGYMJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e12b8d4a95be9404c8f2b42c9e55cf6f02d9f29/pkg/sql/sem/builtins/aggregate_builtins.go#L617)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is the reuse for performance? If so, should this do `agg.flatCoords = agg.flatCoord[:0]`?
</blockquote></details>

Done.

**Review by mgartner — APPROVED** [review]
`opt` changes LGTM

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52631#-:-MEZ9an98edZnBFUShKW:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by otan** [comment]
bors r=sumeerbhola

**Pull request merged**
