### PR TITLE
testServer: misc cleanup

### PR DESCRIPTION
**Pull request by tamird**

### CODE REVIEW

**Comment by BramGruneir** [comment]
LGTM

**Comment by mrtracy** [comment]
What's the issue with fatal as part of setup?  It cuts down on boilerplate.

**Comment by tamird** [comment]
It's probably fine as part of setup, I was being overzealous here with the thinking that t.Fatal outside of TestFoo functions makes it hard to locate failures.

**Comment by petermattis** [comment]
Passing a `t *testing.T` to test initialization routines is a pattern we've used elsewhere. It simplifies the tests for code that is expected to never fail. I'd drop this change.

**Pull request merged**
