### PR TITLE
vendor: bump Pebble to e567fec84c6e

### PR DESCRIPTION
**Pull request by jbowens**
This commit includes non-trivial changes to account for the change
in the `vfs.WithDiskHealthChecks` function signature change.
Additionally, this PR uncovered #81413 and necessitated some changes to
work around it.

```
e567fec8 db: ensure Open closes opened directories on error
b8c9a560 internal/metamorphic: overwrite unused bounds buffers
7c5f0cbb db: copy user-provided bounds and optimize unchanged bounds
f8897076 *: Add IterOption to optionally read L6 filter blocks.
d79f9617 vfs: extend disk-health checking to filesystem metadata operations
5ae21746 db: remove newRangeKeyIter closure
6d975489 db: add BenchmarkIteratorScan
782d102e sstable: fix invariant check for sstable size estimation
738a7f0b db: fix NewIter regression resulting in extra memtable levels
37558663 *: Use keyspan.LevelIter for rangedels in compactions
e6c60c71 db: use sublevel level iters for all compactions out of L0
d8f63bef db: extend documentation on ingested file overlap; improve test cases
b9e970a8 internal/keyspan: correct and document MergingIter key stability
498177bb internal/keyspan: collapse fragmentBoundIterator into MergingIter
```

Release note (bug fix): Fix a gap in disk-stall detection. Previously,
disk stalls during filesystem metadata operations could go undetected,
inducing deadlocks.  Now stalls during these types of operations will
correctly fatal the process.

### CODE REVIEW

**Review by nicktrav — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81389#-:-N2I9SDL0IVfTdZmGJY1:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Review by jbowens — COMMENTED** [review]
Still wrangling with two issues:
1. `kv/kvserver.TestStoreMetrics` is showing reduced bloom filter lookups.
2. `sql/colexec.TestExternalDistinct` has a goroutine leak from the disk-health checking. It appears to be file-level goroutines (not the new filesystem-wide goroutine) that are leaking, but it's a new leak with this commit. Still digging.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81389#-:-N2IoqCmEl_Td0WJvDPz:b-9pjqij)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Review by nicktrav — APPROVED** [review]
> Reviewed 4 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81389)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens)

**Review by nicktrav — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81389)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens)

**Comment by yuzefovich** [comment]
Thanks for filing #81413 - I think I have a fix in #81419, do you mind rebasing and checking whether it addresses the issue?

**Comment by jbowens** [comment]
> Thanks for filing https://github.com/cockroachdb/cockroach/issues/81413 - I think I have a fix in https://github.com/cockroachdb/cockroach/pull/81419, do you mind rebasing and checking whether it addresses the issue?

That fixes it, thanks for the quick turnaround!

**Comment by jbowens** [comment]
`TestLogic` is pointing to another open file leak.

```
[TestLogic] gotest://github.com/cockroachdb/cockroach/pkg/sql/logictest#TestLogic
[12:51:58]
[TestLogic] [Test Output]
=== RUN   TestLogic
    test_log_scope.go:79: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestLogic1197699296
    test_log_scope.go:80: use -show-logs to present logs inline
=== CONT  TestLogic
    logic.go:4414: -- test log scope end --
    logic_test.go:33: Leaked goroutine: goroutine 11937409 [select]:
        github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1()
        	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/vfs/disk_health.go:72 +0xe8
        created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker
        	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/vfs/disk_health.go:67 +0x65
        Leaked goroutine: goroutine 11937584 [select]:
        github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1()
        	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/vfs/disk_health.go:72 +0xe8
        created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker
        	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/vfs/disk_health.go:67 +0x65
--- FAIL: TestLogic (1937.22s)
```

**Review by nicktrav — APPROVED** [review]
Thanks for persevering with this yak shave! :lgtm: 

> Reviewed 9 of 13 files at r7, 10 of 10 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81389#-:-N2Nwq__2nc1AlDPfyau:btiobyy)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Comment by yuzefovich** [comment]
I think I found the other problem - #81490 and will open a fix shortly.

**Review by nicktrav — COMMENTED** [review]
> Reviewed 9 of 9 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81389)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens)

**Comment by jbowens** [comment]
Hrm, recent pushes aren't tickling CI

**Comment by nicktrav** [comment]
Isn't the `lint` commit already on master?

**Review by jbowens — COMMENTED** [review]
We're green, so I'll merge this afternoon.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81389#-:-N2XDPdv2IQPjtyVe64s:bto2fio)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nicktrav and @stevendanna)

**Comment by jbowens** [comment]
TFTR!

bors r+

**Pull request merged**
