### PR TITLE
Fix flaky test TestReplicaCancelRaft

### PR DESCRIPTION
**Pull request by tbg**
De-flake `make stress PKG=./storage TESTS=CancelRaft`.
The original test had some amount of randomness owing to the fact that when
selecting on two ready channels, either of those can be chosen.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4903)

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM

**Comment by tschottdorf** [comment]
PTAL, @bdarnell. It was still flaky.

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/replica_test.go, line 4028 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4903#-KCBgjq6-tzl78TIioey:-KCBgjq6-tzl78TIioez:459185084) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6793e1c8155dab88317a0948130d2eb64ed76c1/storage/replica_test.go#L4028)):*
looks like there's no cleanup now?

---

*[storage/replica_test.go, line 4031 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4903#-KCBghsdF8ICuMtytFxs:-KCBghsdF8ICuMtytFxt:485074348) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6793e1c8155dab88317a0948130d2eb64ed76c1/storage/replica_test.go#L4031)):*
why'd this move?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4903)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[storage/replica_test.go, line 505 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4903#-KCBhBFEXOzFl4jogSuN:-KCBhBFFq0v9MZUHV95s:1759366558) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d89a4b23627c6b4f865b335ee848a6c64ba4d2e/storage/replica_test.go#L505)):*
what's the point of this extra scope?

---

*[storage/replica_test.go, line 3557 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4903#-KCBh7BAjJddZZgHv5cg:-KCBh7BAjJddZZgHv5ch:1759366558) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d89a4b23627c6b4f865b335ee848a6c64ba4d2e/storage/replica_test.go#L3557)):*
what's the point of this extra scope?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4903)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[storage/replica_test.go, line 505 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4903#-KCBhBFEXOzFl4jogSuN:-KCBiZoc4OAJp5QJ1nKA:-1318284420) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d89a4b23627c6b4f865b335ee848a6c64ba4d2e/storage/replica_test.go#L505)):*
Thought it highlighted the locking. Apparently it's just confusing. Removing.

---

*[storage/replica_test.go, line 4028 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4903#-KCBgjq6-tzl78TIioey:-KCBiN0j4awKOmyzI3BE:-806576217) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6793e1c8155dab88317a0948130d2eb64ed76c1/storage/replica_test.go#L4028)):*
Can't wait for that to be plumbed through the Context. Fixed.

---

*[storage/replica_test.go, line 4031 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4903#-KCBghsdF8ICuMtytFxs:-KCBiUaA7Q_rDDvMsblp:-1987319483) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6793e1c8155dab88317a0948130d2eb64ed76c1/storage/replica_test.go#L4031)):*
Too many code changes inbetween. Moved back.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4903)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4903)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4903#-:-KCBxNnwX3qZQ_QQHxGr:676834233)*

**Pull request merged**
