### PR TITLE
server: Expose endpoint that serves up the entire range log

### PR DESCRIPTION
**Pull request by a-robinson**
The existing endpoint only serves up one range's events at a time.

Consider this a proposal. I expect that it'll be nice to be able to look at all range events at once when debugging cluster-wide allocator problems, but I may be overlooking a reason not to expose this.

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

I can't think of a reason not to allow retrieving logs for more than 1 range.

---

Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/server/admin.go, line 765 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17756#-KrryfnyQqeMDQN-kcPs:-KrryfnztauJID7kW7Rw:buxngdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8458fb25a1bc4c2567226bbd84507c445e6d9f26/pkg/server/admin.go#L765)):*
> ```Go
> 	}
> 	q.Append("ORDER BY timestamp DESC ")
> 	if limit > 0 {
> ```

When is a limit not specified?

I'm wonder how retrieving the range log entries for a specific range will perform when we have a million ranges. Note that we don't index on `rangeID` or `otherRangeID`. This concern is independent of this change.

---

*[pkg/server/serverpb/admin.proto, line 627 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17756#-KrrzQvBLbd1yxVuzPur:-KrrzQvBLbd1yxVuzPus:bqxz5ny) ([raw file](https://github.com/cockroachdb/cockroach/blob/8458fb25a1bc4c2567226bbd84507c445e6d9f26/pkg/server/serverpb/admin.proto#L627)):*
> ```protobuf
>   // URL: /_admin/v1/rangelog
>   // URL: /_admin/v1/rangelog?limit=100
>   rpc FullRangeLog(FullRangeLogRequest) returns (RangeLogResponse) {
> ```

Rather than a new endpoint, we could make `range_id == 0` retrieve all ranges. `0` is never a valid range ID.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17756#-:-Krs--_kdcaWxYXfQyy_:bpli82f)*

**Comment by BramGruneir** [comment]
So the rational for not exposing this is because there's nothing in the admin ui that uses it and you can already get the rangelog via SQL.  

The need for the single range version was so the debug range page could display its history.

If you do merge this, could you please add this updated endpoint to the debug page's list of endpoints in `/ui/src/views/reports/containers/debug/index.tsx`.

Also, I like Peter's suggestion to add the indexes, but that's not in the scope of these changes. Would probably have to be a migration.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/server/serverpb/admin.proto, line 627 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17756#-KrrzQvBLbd1yxVuzPur:-KrvBKNrn4Xyi665IS8k:b-1jebqr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8458fb25a1bc4c2567226bbd84507c445e6d9f26/pkg/server/serverpb/admin.proto#L627)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Rather than a new endpoint, we could make `range_id == 0` retrieve all ranges. `0` is never a valid range ID.
</blockquote></details>

Combining the endpoints would be cleaner.  Just have both use the same function (if that's possible).
I do like how `/_admin/v1/rangelog` will give you the full log and `/rangelog/{rangeID}` will give a specific one. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17756#-:-KrvC2B0o_4jn7vu3pfg:b-ym4d6u)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17756#-:-KrwOYhs3oxhrUcZuEtN:bnfp4nl)*

**Comment by a-robinson** [comment]
> So the rational for not exposing this is because there's nothing in the admin ui that uses it and you can already get the rangelog via SQL.

Yeah, I understand that it wasn't built because it wasn't needed for an existing page. It's just something I found myself wanting now.

> If you do merge this, could you please add this updated endpoint to the debug page's list of endpoints in `/ui/src/views/reports/containers/debug/index.tsx`.

Good call, thanks. Done.

screen shot 2017-08-21 at 11 29 19 am

And agreed on an index being a good idea. I've opened https://github.com/cockroachdb/cockroach/issues/17781 to track this for the next release.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/server/admin.go, line 765 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17756#-KrryfnyQqeMDQN-kcPs:-Ks4P7ZZ2JPEM7wExmLP:b3mhdt4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8458fb25a1bc4c2567226bbd84507c445e6d9f26/pkg/server/admin.go#L765)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

When is a limit not specified?

I'm wonder how retrieving the range log entries for a specific range will perform when we have a million ranges. Note that we don't index on `rangeID` or `otherRangeID`. This concern is independent of this change.
</blockquote></details>

If someone explicitly specifies a limit less than zero, we won't change it to our default. I think that's reasonable, given that we do have a default limit in place.

---

*[pkg/server/serverpb/admin.proto, line 627 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17756#-KrrzQvBLbd1yxVuzPur:-Ks4KsVmpMNx_gntjzJa:btyb7py) ([raw file](https://github.com/cockroachdb/cockroach/blob/8458fb25a1bc4c2567226bbd84507c445e6d9f26/pkg/server/serverpb/admin.proto#L627)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Combining the endpoints would be cleaner.  Just have both use the same function (if that's possible).
I do like how `/_admin/v1/rangelog` will give you the full log and `/rangelog/{rangeID}` will give a specific one. 
</blockquote></details>

Yeah, it's a little bit column A, little bit of column B. This approach is better REST design, but not adding a new grpc endpoint would be nice too.

I did a bit of digging in the grpc docs and found a way to specify multiple HTTP paths, though, so now we can effectively have both.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17756#-:-Ks4KRmabp3m82wGgtis:br9zzu6)*

**Comment by BramGruneir** [comment]
Could you add the other use cases as well, at least for a specific range please?
Or else the only way to know how the endpoint works is to look it up in the proto service definition.
`Specific Range Log  - /_admin/v1/rangelog/[range_id]`

Up to you if you think we advertise the limits, as well. (I think you can leave out the < 0 limit)
```
Range Log with limit - /_admin/v1/rangelog?limit=100
Specific Range Log with limit/_admin/v1/rangelog/[range_id]?limit=100
```

---

Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17756#-:-Ks4RIMrKdnmq-EYZhzY:btd6ggy)*

**Comment by a-robinson** [comment]
Showing the limit option makes sense, but what's the point of showing how to get to the range log for a specific ID given that it's just a subset of what already gets shown on the range debug page?

---

Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17756#-:-Ks4Sc1EgJwAtcy63lqS:b9khmis)*

**Comment by BramGruneir** [comment]
This endpoint section is more for helping others send us the info we need.
We can tell them via an email/im/phone, but it's a lot easier for them to just click on the link and change the range id.  (even better would be to add a form where they can put the range id in it.

**Comment by a-robinson** [comment]
Right, but I don't understand why anyone would ever prefer to look at `/_admin/v1/rangelog/12345` than at `/#/reports/range/12345`, given that the latter has the same info in a more nicely formatted table (and other useful info).

**Comment by BramGruneir** [comment]
It's a lot easier to tell someone to just grab the json and send it our way instead of having them take the debug page and save the html to file.

But if you feel strongly about not adding it, it's really not a big deal.  I just like to have all the endpoints (and how to use them) in one place.

**Comment by petermattis** [comment]
Review status: 3 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/server/serverpb/admin.proto, line 627 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17756#-KrrzQvBLbd1yxVuzPur:-Ks4ew2z4LsjlNO4A1aU:b-83sjo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8458fb25a1bc4c2567226bbd84507c445e6d9f26/pkg/server/serverpb/admin.proto#L627)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Yeah, it's a little bit column A, little bit of column B. This approach is better REST design, but not adding a new grpc endpoint would be nice too.

I did a bit of digging in the grpc docs and found a way to specify multiple HTTP paths, though, so now we can effectively have both.
</blockquote></details>

Nice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17756)*

**Comment by a-robinson** [comment]
I went and added the extra link, since I needed to rebuild things anyway.

I don't think it's correct to say that we have all the endpoints in one place, though, since none of the other admin endpoint URLs are listed there.

**Comment by BramGruneir** [comment]
That was just an oversight.  I'll add the missing ones.

**Comment by BramGruneir** [comment]
*[pkg/ui/src/views/reports/containers/debug/index.tsx, line 188 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17756#-Ks4qR04xY1J2HXwfYNB:-Ks4qR04xY1J2HXwfYNC:b-i7qkkk) ([raw file](https://github.com/cockroachdb/cockroach/blob/36fc51b21b5c79ed21033425ad656f7cbd4eab8e/pkg/ui/src/views/reports/containers/debug/index.tsx#L188)):*
> ```XML
>           />
>           <DebugTableLink name="Range Log" url="/_admin/v1/rangelog?limit=100" />
>           <DebugTableLink name="Range Log for Specific Range" url="/_admin/v1/rangelog/[range_id]limit=100" />
> ```

Can you make the url resolve?  And use the note to show how it is formed:

```
<DebugTableLink 
    name="Range Log"
    url="/_admin/v1/rangelog?limit=100"
    note="/_admin/v1/rangelog?[limit=100]" 
  />
  <DebugTableLink 
    name="Range Log for Specific Range"
    url="/_admin/v1/rangelog/1?limit=100"
    note="/_admin/v1/rangelog/[range_id]?[limit=100]" 
  />

```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17756)*

**Comment by a-robinson** [comment]
Yup, my bad.

**Comment by BramGruneir** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17756#-:-Ks5F-mekZkMhEOvte6u:bnfp4nl)*

**Pull request merged**
