### PR TITLE
sql, import: add metrics for max_row_size guardrails

### PR DESCRIPTION
**Pull request by michae2**
**sql: rename max_row_size guardrails to match transaction row limits**

Addresses: https://github.com/cockroachdb/cockroach/issues/67400

Rename sql.mutations.max_row_size.{log|err} to
sql.guardrails.max_row_size_{log|err} for consistency with
transaction_rows_{read|written}_{log|err} and upcoming metrics.

Release justification: Low-risk update to new functionality.

Release note (ops change): New variables
sql.mutations.max_row_size.{log|err} were renamed to
sql.guardrails.max_row_size_{log|err} for consistency with other
variables and metrics.

**sql/row: remove dependency on sql/execinfra**

The next commit needs to make sql/row a dependency of sql/execinfra, so
remove two small references to sql/execinfra.

(I will squash this into the next commit before merging.)

Release justification: Low-risk update to new functionality.

Release note: None

**sql, import: plumb RowMetrics from ExecutorConfig to row.Helper**

Addresses: https://github.com/cockroachdb/cockroach/issues/67400

Add metrics for sql/row and pass them down from ExecutorConfig and
FlowCtx all the way to row.Helper. Like sql.Metrics, there are two
copies, one for user queries and one for internal queries. (These were
originally part of sql.Metrics, but there are several users of sql/row
that do not operate under a sql.Server or connExecutor so we are forced
to add these to the ExecutorConfig and FlowCtx instead.)

I ran into difficulty passing these through import, as FlowCtx itself
is not plumbed through.

There are only two metrics at first, corresponding to
sql.guardrails.max_row_size_{log|err}.

Release justification: Low-risk update to new functionality.

Release note (ops): Added four new metrics,
sql.guardrails.max_row_size_{log|err}.count{.internal} which are
incremented whenever a large row violates
sql.guardrails.max_row_size_{log|err}.

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
Nice! 

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 24 of 24 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69457#-:-Mi6mk2S0JdEXMFxflEH:bwuv9up)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[pkg/sql/exec_util.go, line 2975 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69457#-Mi6laM3EoXfWVoCaluX:-Mi6laM41W72OeJbMLRg:b4mqzgm) ([raw file](https://github.com/cockroachdb/cockroach/blob/37dc124e93a0cffc557b0b73bd652dac48a3b5bf/pkg/sql/exec_util.go#L2975)):*
> ```Go
> }
> 
> func NewRowMetrics(internal bool) row.RowMetrics {
> ```

I'd put this in a different package other than sql.
___
*[pkg/sql/row/fetcher.go, line 343 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69457#-Mi6kQph45hJV3W57izg:-Mi6kQph45hJV3W57izh:b-f31nc0) ([raw file](https://github.com/cockroachdb/cockroach/blob/99b739cc9016b7ce347c4c704cb45f2b753f9e4b/pkg/sql/row/fetcher.go#L343)):*
> ```Go
> 
> 	if memMonitor != nil {
> 		rf.mon = mon.NewMonitorInheritWithLimit("fetcher-mem", 0 /* limit */, memMonitor)
> ```

why are you using a limit of 0 here?

**Review by michae2 — COMMENTED** [review]
Thank you for looking! :slightly_smiling_face:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69457#-:-Mi7Ihk86oRfFRozMto6:b1ccmgv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @rytaft, and @yuzefovich)

___
*[pkg/sql/exec_util.go, line 2975 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69457#-Mi6laM3EoXfWVoCaluX:-Mi7GzE8-aMy3mBjcGCy:b4i859g) ([raw file](https://github.com/cockroachdb/cockroach/blob/37dc124e93a0cffc557b0b73bd652dac48a3b5bf/pkg/sql/exec_util.go#L2975)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I'd put this in a different package other than sql.
</blockquote></details>

Unfortunately it has to be in sql to use `getMetricMeta` without creating a circular dependency.
___
*[pkg/sql/row/fetcher.go, line 343 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69457#-Mi6kQph45hJV3W57izg:-Mi7HBetDYxnnECDbDLt:btukzlg) ([raw file](https://github.com/cockroachdb/cockroach/blob/99b739cc9016b7ce347c4c704cb45f2b753f9e4b/pkg/sql/row/fetcher.go#L343)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

why are you using a limit of 0 here?
</blockquote></details>

This is a paste of the body of `execinfra.NewMonitor` from `processorbase.go` which uses 0 internally. I think the de facto limit comes from the parent monitor (or an ancestor of the parent), in this case `memMonitor`.

**Review by rytaft — APPROVED** [review]
:lgtm: although it would be good to get approval from at least one other person who knows this code better than I do.

> Reviewed 2 of 27 files at r4, 1 of 2 files at r5, 24 of 24 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69457#-:-Mi8BH0c5Rvcz9bAbdxD:b-hqgypk)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru and @yuzefovich)

___
*[pkg/sql/exec_util.go, line 2975 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69457#-Mi6laM3EoXfWVoCaluX:-Mi8AA_Q-khTGdg__KjA:bmfwehr) ([raw file](https://github.com/cockroachdb/cockroach/blob/37dc124e93a0cffc557b0b73bd652dac48a3b5bf/pkg/sql/exec_util.go#L2975)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Unfortunately it has to be in sql to use `getMetricMeta` without creating a circular dependency.
</blockquote></details>

Ah ok, makes sense.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 2 of 27 files at r4, 1 of 2 files at r5, 24 of 24 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69457#-:-Mi8Ih-xEVdJgn66_bRY:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @adityamaru and @michae2)

___
*[pkg/sql/execinfra/server_config.go, line 293 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69457#-Mi8Hg7xEBVLVSAYWH4H:-Mi8Hg7xEBVLVSAYWH4I:bo9un5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7f7ce383a68e03e7d8ab860d8dae8d22c388a0b/pkg/sql/execinfra/server_config.go#L293)):*
> ```Go
> // GetRowMetrics returns the proper RowMetrics for either internal or user
> // queries.
> func (flowCtx *FlowCtx) GetRowMetrics(internal bool) *row.Metrics {
> ```

nit: I think`FlowCtx` has `EvalContext` inside, so maybe we could peek into the session data and remove the need for an argument here?
___
*[pkg/sql/row/fetcher.go, line 343 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69457#-Mi6kQph45hJV3W57izg:-Mi8Hx43EVdXKOIXrZa-:b-gu2ph0) ([raw file](https://github.com/cockroachdb/cockroach/blob/99b739cc9016b7ce347c4c704cb45f2b753f9e4b/pkg/sql/row/fetcher.go#L343)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

This is a paste of the body of `execinfra.NewMonitor` from `processorbase.go` which uses 0 internally. I think the de facto limit comes from the parent monitor (or an ancestor of the parent), in this case `memMonitor`.
</blockquote></details>

Yep. Just to expand on Michael's comment: passing `0` as the limit we're only making the new monitor "locally unlimited" - any reservations still need to be approved by the parent (which might also not have a local limit and will ask its parent, etc, eventually the ask will be against `rootSQLMemoryMonitor`).
___
*[pkg/sql/row/metrics.go, line 16 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69457#-Mi8ITdz1-2kvZd7lG3B:-Mi8ITdz1-2kvZd7lG3C:bgxdl6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7f7ce383a68e03e7d8ab860d8dae8d22c388a0b/pkg/sql/row/metrics.go#L16)):*
> ```Go
> 
> var (
> 	// Metadata for sql.guardrails.max_row_size_log.count{.internal}
> ```

nit: missing period.

**Review by michae2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69457)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @adityamaru, @rytaft, and @yuzefovich)

___
*[pkg/sql/execinfra/server_config.go, line 293 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69457#-Mi8Hg7xEBVLVSAYWH4H:-Mi8O-6W-9eM37MO4Aad:btpk1a4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7f7ce383a68e03e7d8ab860d8dae8d22c388a0b/pkg/sql/execinfra/server_config.go#L293)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I think`FlowCtx` has `EvalContext` inside, so maybe we could peek into the session data and remove the need for an argument here?
</blockquote></details>

Oh! Good point! Done!

(It looks like the `EvalContext` inside `FlowCtx` is often copied by operators using `NewEvalCtx` but that's fine, we can still use `FlowCtx.EvalContext` because `SessionData().Internal` will always be the same in both copies.)
___
*[pkg/sql/row/metrics.go, line 16 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69457#-Mi8ITdz1-2kvZd7lG3B:-Mi8OutXDo5YLWHPJ4al:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7f7ce383a68e03e7d8ab860d8dae8d22c388a0b/pkg/sql/row/metrics.go#L16)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: missing period.
</blockquote></details>

Done.

**Comment by michae2** [comment]
TFTRs! Failure looks like an unrelated flake. I'd like to merge this before the 21.2 branch is cut (and before I go on vacation 😎) so I think I'll give it a shot.

bors r=rytaft,yuzefovich

**Comment by michae2** [comment]
Looks like bors got stuck.

bors r-

**Comment by michae2** [comment]
Let's try this again! 🎲

bors r=rytaft,yuzefovich

**Comment by michae2** [comment]
bors r-

Hmm.

**Comment by maryliag** [comment]
@michae2 there were some tests failing that we fixed and got merged this morning. I suggest rebase your branch and trying again, maybe it helps :)

**Comment by michae2** [comment]
Third time's the charm!

bors r=rytaft,yuzefovich

**Pull request merged**
