### PR TITLE
sql: change multi-region enum name and save primary region information on the descriptor

### PR DESCRIPTION
**Pull request by arulajmani**
See individual commits for details.

### CODE REVIEW

**Review by otan — COMMENTED** [review]
now that i see the code, i propose `crdb_internal_region` as opposed to `crdb_internal_regions`, as having a type be plural and having something like `CREATE TABLE a (pk crdb_internal_regions)` does not feel as convincing as the singular form.

> Reviewed 3 of 3 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57381#-:-MNZqyNA6NIdCsfZHw2C:b7cnjzr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @arulajmani)

___
*[pkg/sql/catalog/descpb/structured.proto, line 1211 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57381#-MNZrnCy9z7h2AzYhmP3:-MNZrnCy9z7h2AzYhmP4:br14mq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/788cab75be68f7685c4b6c4cd92a08c2b1a40465/pkg/sql/catalog/descpb/structured.proto#L1211)):*
> ```protobuf
> 
>   // PrimaryRegion represents the PrimaryRegion for a multi-region enum.
>     optional string primary_region = 16 [(gogoproto.nullable) = false, (gogoproto.casttype)="Region"];
> ```

nit: extra spacing
also consider encoding all multi-region specific parameters into their own struct, in case we add more, i.e.

```
message MultiRegionConfig {
       optional string primary_region = 1 [(gogoproto.nullable) = false, (gogoproto.casttype)="Region"];

optional MultiRegionConfig config = 16;
```

**Review by ajstorm — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57381)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/sql/catalog/descpb/structured.proto, line 1179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57381#-MN_B3vJ44euCLg8b_T6:-MN_B3vJ44euCLg8b_T7:b-l81s6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/788cab75be68f7685c4b6c4cd92a08c2b1a40465/pkg/sql/catalog/descpb/structured.proto#L1179)):*
> ```protobuf
>     [(gogoproto.casttype) = "ID", (gogoproto.customname) = "ReferencingDescriptorIDs"];
> 
>   // The fields below are used only when this type is an ENUM type or a
> ```

Nit: Could probably simplify to "  // The fields below are used only when this type is an ENUM or a MULTIREGION_ENUM"
___
*[pkg/sql/catalog/descpb/structured.proto, line 1208 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57381#-MN_BErj2cVKRrbRTTy2:-MN_BErj2cVKRrbRTTy3:bmamvnd) ([raw file](https://github.com/cockroachdb/cockroach/blob/788cab75be68f7685c4b6c4cd92a08c2b1a40465/pkg/sql/catalog/descpb/structured.proto#L1208)):*
> ```protobuf
> 
> 
>   // The fields below are used only when this type is a MULTIREGION_ENUM type.
> ```

Nit: same here, can remove the last "type"
___
*[pkg/sql/catalog/typedesc/type_desc.go, line 442 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57381#-MN_Bmt2BpcHpjmfPW_B:-MN_Bmt2BpcHpjmfPW_C:b-gwgtbr) ([raw file](https://github.com/cockroachdb/cockroach/blob/788cab75be68f7685c4b6c4cd92a08c2b1a40465/pkg/sql/catalog/typedesc/type_desc.go#L442)):*
> ```Go
> 	switch desc.Kind {
> 	case descpb.TypeDescriptor_MULTIREGION_ENUM:
> 		if desc.PrimaryRegion == "" {
> ```

Is this the only validation we have to do here?  What about validating that the regions are all present in the database descriptor?  That there are no duplicated regions?  
___
*[pkg/sql/catalog/typedesc/type_desc.go, line 466 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57381#-MN_cyj90mPs4a9KbQXk:-MN_cyjA61PjSZ5_N1Jy:biqgdhk) ([raw file](https://github.com/cockroachdb/cockroach/blob/788cab75be68f7685c4b6c4cd92a08c2b1a40465/pkg/sql/catalog/typedesc/type_desc.go#L466)):*
> ```Go
> 	})
> 
> 	switch desc.Kind {
> ```

noob question: why the two switch statements?  Can we not combine these into one?  Also, would it make sense to wrap all of this MR-specific validation logic in a separate function?
___
*[pkg/sql/catalog/typedesc/type_desc_test.go, line 663 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57381#-MN_fYOaE1WizHaTNjxx:-MN_fYOaE1WizHaTNjxy:b-wm86oh) ([raw file](https://github.com/cockroachdb/cockroach/blob/788cab75be68f7685c4b6c4cd92a08c2b1a40465/pkg/sql/catalog/typedesc/type_desc_test.go#L663)):*
> ```Go
> 				EnumMembers: []descpb.TypeDescriptor_EnumMember{
> 					{
> 						LogicalRepresentation:  "foo",
> ```

I'm probably missing something, but isn't this also an unexpected primary region case?

**Review by arulajmani — COMMENTED** [review]
Addressed comments and changed the type name to be of singular form. RFAL. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57381#-:-MNdsWtI5EBFC1NZxY5J:b-4hqu44)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/catalog/descpb/structured.proto, line 1211 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57381#-MNZrnCy9z7h2AzYhmP3:-MNdfVPdBy5UNGDgGvlp:bg6ey0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/788cab75be68f7685c4b6c4cd92a08c2b1a40465/pkg/sql/catalog/descpb/structured.proto#L1211)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: extra spacing
also consider encoding all multi-region specific parameters into their own struct, in case we add more, i.e.

```
message MultiRegionConfig {
       optional string primary_region = 1 [(gogoproto.nullable) = false, (gogoproto.casttype)="Region"];

optional MultiRegionConfig config = 16;
```
</blockquote></details>

Calling it `RegionConfig` to keep it in line with the database descriptor -- no strong opinions on the name here, as long as they're uniform -- lemme know if you prefer the other one and i can switch it. 
___
*[pkg/sql/catalog/typedesc/type_desc.go, line 442 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57381#-MN_Bmt2BpcHpjmfPW_B:-MNdaOI05LACzDm3iPCy:b-5dmkp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/788cab75be68f7685c4b6c4cd92a08c2b1a40465/pkg/sql/catalog/typedesc/type_desc.go#L442)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Is this the only validation we have to do here?  What about validating that the regions are all present in the database descriptor?  That there are no duplicated regions?  
</blockquote></details>

No, there's other validation that happens as well. The cross validation against the database descriptor happens below and we get no duplicated regions for free as enums (multi-region or otherwise)  can't have duplicate logical/physical representations. 
___
*[pkg/sql/catalog/typedesc/type_desc.go, line 466 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57381#-MN_cyj90mPs4a9KbQXk:-MNdapch1vEF7Xy3x1zR:b-x6kait) ([raw file](https://github.com/cockroachdb/cockroach/blob/788cab75be68f7685c4b6c4cd92a08c2b1a40465/pkg/sql/catalog/typedesc/type_desc.go#L466)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

noob question: why the two switch statements?  Can we not combine these into one?  Also, would it make sense to wrap all of this MR-specific validation logic in a separate function?
</blockquote></details>

I just followed the general pattern (although this isn't split out in different functions in the case of type descriptors) where we split out descriptor validation and cross-reference validation. 

I'm slightly hesitant to do the splitting, as there is some overlap between multi-region validation and regular enum validation. 
___
*[pkg/sql/catalog/typedesc/type_desc_test.go, line 663 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57381#-MN_fYOaE1WizHaTNjxx:-MNddN1hBJRyVPKjdM7L:b-ejajxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/788cab75be68f7685c4b6c4cd92a08c2b1a40465/pkg/sql/catalog/typedesc/type_desc_test.go#L663)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

I'm probably missing something, but isn't this also an unexpected primary region case?
</blockquote></details>

The kind of this enum is `TypeDescriptor_ENUM` (i.e it isn't a multi-region enum to begin with), so it fails with the error above as "regular" enums aren't expected to have a primary region on them,

**Review by ajstorm — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57381)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/catalog/typedesc/type_desc.go, line 466 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57381#-MN_cyj90mPs4a9KbQXk:-MNeP-0-Dl--JD3l5dSZ:b-9u74qp) ([raw file](https://github.com/cockroachdb/cockroach/blob/788cab75be68f7685c4b6c4cd92a08c2b1a40465/pkg/sql/catalog/typedesc/type_desc.go#L466)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I just followed the general pattern (although this isn't split out in different functions in the case of type descriptors) where we split out descriptor validation and cross-reference validation. 

I'm slightly hesitant to do the splitting, as there is some overlap between multi-region validation and regular enum validation. 
</blockquote></details>

Ahh, I didn't expand all the way up to the top and bottom of this function.  Not the easiest function to read, and probably could be refactored a number of ways, but I can understand why you wouldn't want to do that now.  

Incidentally, which team owns this function?  Do we know if this construction was deliberate?  Or if its length and structure are just an artifact of us adding new validation over time?

**Review by otan — APPROVED** [review]
> Reviewed 10 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57381)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

**Review by arulajmani — COMMENTED** [review]
TFTRs! 

bors r=ajstorm, otan

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57381#-:-MNf1_jW8vRMVJZhdbGj:b1sixuu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/catalog/typedesc/type_desc.go, line 466 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57381#-MN_cyj90mPs4a9KbQXk:-MNf0sHB1cEPPprTIRQy:b-eof08d) ([raw file](https://github.com/cockroachdb/cockroach/blob/788cab75be68f7685c4b6c4cd92a08c2b1a40465/pkg/sql/catalog/typedesc/type_desc.go#L466)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Ahh, I didn't expand all the way up to the top and bottom of this function.  Not the easiest function to read, and probably could be refactored a number of ways, but I can understand why you wouldn't want to do that now.  

Incidentally, which team owns this function?  Do we know if this construction was deliberate?  Or if its length and structure are just an artifact of us adding new validation over time?
</blockquote></details>

I don't think the construction is deliberate, but I do think this has reached a point where cross-reference validation should be in a different function, the way we do it for table descriptors. I'll try and clean it up in a followup. 

As for which team owns it, it's either us or schema.

**Pull request merged**
