### PR TITLE
build: Set --concurrency in jepsen tests

### LINKED ISSUE #15734: jepsen: the Register test is improperly configured
From https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=243251#_focus=3362

(Detected using new scripts from #15717 )

```
ERROR [2017-05-06 01:46:36,330] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
java.util.concurrent.ExecutionException: java.lang.AssertionError: Assert failed: This jepsen.independent/concurrent-generator has 5 threads to work with, but can only use 0 of those threads to run 0 concurrent keys with 10 threads apiece. Consider raising or lowering the test's :concurrency to a multiple of 10.
(= thread-count (* group-size group-count))
```

The error occurs for any combination of nemeses.

### LINKED ISSUE #15737: jepsen: the Sequential test is probably incorrect
Found e.g. in https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=243251#_focus=5334

(Using the new scripts from #15717 )

Failure immediately after test initialization:

```
ERROR [2017-05-06 02:48:58,677] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_121]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_121]
        at clojure.core$deref_future.invokeStatic(core.clj:2208) ~[clojure-1.8.0.jar:na]
        at clojure.core$future_call$reify__6962.deref(core.clj:6688) ~[clojure-1.8.0.jar:na]
        at clojure.core$deref.invokeStatic(core.clj:2228) ~[clojure-1.8.0.jar:na]
        at clojure.core$deref.invoke(core.clj:2214) ~[clojure-1.8.0.jar:na]
        at clojure.core$map$fn__4785.invoke(core.clj:2644) ~[clojure-1.8.0.jar:na]
        at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[clojure-1.8.0.jar:na]
        at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[clojure-1.8.0.jar:na]
        at clojure.lang.RT.seq(RT.java:521) ~[clojure-1.8.0.jar:na]
        at clojure.core$seq__4357.invokeStatic(core.clj:137) ~[clojure-1.8.0.jar:na]
        at clojure.core$dorun.invokeStatic(core.clj:3024) ~[clojure-1.8.0.jar:na]
        at clojure.core$dorun.invoke(core.clj:3024) ~[clojure-1.8.0.jar:na]
        at jepsen.core$run_case_BANG_$fn__1251.invoke(core.clj:305) ~[classes/:na]
        at jepsen.core$run_case_BANG_.invokeStatic(core.clj:286) ~[classes/:na]
        at jepsen.core$run_case_BANG_.invoke(core.clj:275) ~[classes/:na]
        at jepsen.core$run_BANG_$fn__1272$fn__1273.invoke(core.clj:414) ~[classes/:na]
        at jepsen.core$run_BANG_$fn__1272.invoke(core.clj:397) ~[classes/:na]
        at jepsen.core$run_BANG_.invokeStatic(core.clj:380) ~[classes/:na]
        at jepsen.core$run_BANG_.invoke(core.clj:329) ~[classes/:na]
        at jepsen.cockroach.runner$test_cmd$fn__3942.invoke(runner.clj:132) ~[classes/:na]
        at jepsen.cli$run_BANG_.invokeStatic(cli.clj:266) [classes/:na]
        at jepsen.cli$run_BANG_.invoke(cli.clj:196) [classes/:na]
        at jepsen.cockroach.runner$_main.invokeStatic(runner.clj:143) [classes/:na]
        at jepsen.cockroach.runner$_main.doInvoke(runner.clj:141) [classes/:na]
        at clojure.lang.RestFn.invoke(RestFn.java:3204) [clojure-1.8.0.jar:na]
        at clojure.lang.Var.invoke(Var.java:624) [clojure-1.8.0.jar:na]
        at user$eval5.invokeStatic(form-init2337330063800746046.clj:1) [na:na]
        at user$eval5.invoke(form-init2337330063800746046.clj:1) [na:na]
        at clojure.lang.Compiler.eval(Compiler.java:6927) [clojure-1.8.0.jar:na]
        at clojure.lang.Compiler.eval(Compiler.java:6917) [clojure-1.8.0.jar:na]
        at clojure.lang.Compiler.load(Compiler.java:7379) [clojure-1.8.0.jar:na]
        at clojure.lang.Compiler.loadFile(Compiler.java:7317) [clojure-1.8.0.jar:na]
        at clojure.main$load_script.invokeStatic(main.clj:275) [clojure-1.8.0.jar:na]
        at clojure.main$init_opt.invokeStatic(main.clj:277) [clojure-1.8.0.jar:na]
        at clojure.main$init_opt.invoke(main.clj:277) [clojure-1.8.0.jar:na]
        at clojure.main$initialize.invokeStatic(main.clj:308) [clojure-1.8.0.jar:na]
        at clojure.main$null_opt.invokeStatic(main.clj:342) [clojure-1.8.0.jar:na]
        at clojure.main$null_opt.invoke(main.clj:339) [clojure-1.8.0.jar:na]
        at clojure.main$main.invokeStatic(main.clj:421) [clojure-1.8.0.jar:na]
        at clojure.main$main.doInvoke(main.clj:384) [clojure-1.8.0.jar:na]
        at clojure.lang.RestFn.invoke(RestFn.java:421) [clojure-1.8.0.jar:na]
```

### PR DESCRIPTION
**Pull request by bdarnell**
Fixes #15734
Fixes #15737

Along with jepsen-io/jepsen#178, this gets most of the tests passing. Remaining flakes are due to #16450.

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM

**Review by knz — APPROVED** [review]

**Comment by knz** [comment]
Is the new 2nd commit belonging to this PR?

**Comment by bdarnell** [comment]
I'm trying to debug jepsen-io/jepsen#182, which started after I updated to the latest jepsen upstream. I'm reusing this branch out of laziness and the fact that I couldn't merge it on the first pass due to teamcity issues.

**Comment by knz** [comment]
ack

**Pull request merged**
