### PR TITLE
sql: allow creation of partial UNIQUE WITHOUT INDEX constraints

### PR DESCRIPTION
**Pull request by mgartner**
This commit allows creation of partial `UNIQUE WITHOUT INDEX`
constraints. These partial unique constraints have a predicate to
enforce uniqueness on the subset of rows in which the predicate
evaluates to true, similar to a unique partial index.

An example of a partial `UNIQUE WITHOUT INDEX` constraint:

    CREATE TABLE t (
      a INT,
      UNIQUE WITHOUT INDEX (a) WHERE a > 0
    )

**NOTE**: these constraints are not yet correctly enforcing uniqueness
on a subset of rows in the table. This requires optimizer changes that
will come in a follow-up commit. Specifically, this commit adds support
for:

  - Creating these constraints in `CREATE TABLE` and `ALTER TABLE`.
  - Storing the predicates in table descriptor constraints.
  - Validating the predicates both during creation and during descriptor
    validation.
  - Displaying the predicates in `SHOW CREATE` and `SHOW CONSTRAINTS`
    output, and in the pg_catalog.pg_constraint table.
  - Accessing the predicates via the opt catalog.

The primary motivation for this change is to simplify testing for
implicitly partitioned partial unique indexes. An experimental session
setting is required to use `UNIQUE WITHOUT INDEX` there are no current
plans to make these constraints available to users by default.

Informs #59195

There is no release note because these constraints are gated behind the
experimental_enable_unique_without_index_constraints session variable.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60289#-:-MTCpnUF-1mutvo1raIt:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @otan, and @rytaft)

___
*[pkg/sql/catalog/tabledesc/structured.go, line 2229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60289#-MTCpFwB0nSG15fCsIHo:-MTCpFwB0nSG15fCsIHp:b-lrlnfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1189979f4da67c0bafd97c4e2aff731a75bb27/pkg/sql/catalog/tabledesc/structured.go#L2229)):*
> ```Go
> 				return err
> 			}
> 			valid, err := schemaexpr.HasValidColumnReferences(desc, expr)
> ```

Why not use `ValidateUniqueWithoutIndexPredicate` here?

**Review by otan — APPROVED** [review]

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60289)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/catalog/tabledesc/structured.go, line 2229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60289#-MTCpFwB0nSG15fCsIHo:-MTDa2-g5XXAmj0OQGCw:bjdthfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1189979f4da67c0bafd97c4e2aff731a75bb27/pkg/sql/catalog/tabledesc/structured.go#L2229)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Why not use `ValidateUniqueWithoutIndexPredicate` here?
</blockquote></details>

That function requires a `*tree.SemaContext` which is not readily available here. I think I attempted to plumb one in here to better validate partial index predicates, but I ran into some issues. There was some discussion on this here: https://github.com/cockroachdb/cockroach/pull/51650#discussion_r463344916

**Review by rytaft — APPROVED** [review]
:lgtm: 

[nit] the syntax in commit/PR message is incorrect "UNIQUE WITHOUT CONSTRAINT" should be "UNIQUE WITHOUT INDEX".

Also would be good to note that this PR informs https://github.com/cockroachdb/cockroach/issues/59195

> Reviewed 23 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60289#-:-MTDN2Ua05uK_XEClvnm:b1vuuco)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/alter_table.go, line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60289#-MTDP5iq-A7mjPXEm43g:-MTDP5iq-A7mjPXEm43h:b-ci03a1) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1189979f4da67c0bafd97c4e2aff731a75bb27/pkg/sql/alter_table.go#L197)):*
> ```Go
> 							return err
> 						}
> 					}
> ```

[nit] maybe worth encapsulating this validation inside `addUniqueWithoutIndexTableDef`? Then you could remove it from here and `create_table.go`
___
*[pkg/sql/opt_catalog.go, line 786 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60289#-MTDY4hTDqj87568O47P:-MTDY4hTDqj87568O47Q:ba2wotj) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1189979f4da67c0bafd97c4e2aff731a75bb27/pkg/sql/opt_catalog.go#L786)):*
> ```Go
> 				table:        ot.ID(),
> 				columns:      idxDesc.ColumnIDs[idxDesc.Partitioning.NumImplicitColumns:],
> 				withoutIndex: true,
> ```

need to add the predicate here too (this will just be the index predicate)
___
*[pkg/sql/catalog/descpb/constraint.go, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60289#-MTDYVhz3vr5sNHkfsEf:-MTDYVhz3vr5sNHkfsEg:b63jb4o) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1189979f4da67c0bafd97c4e2aff731a75bb27/pkg/sql/catalog/descpb/constraint.go#L124)):*
> ```Go
> }
> 
> // IsPartial returns true if the index is a partial index.
> ```

[nit] index -> constraint
___
*[pkg/sql/catalog/descpb/constraint.go, line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60289#-MTDYnzu8qbRIwo1bJmM:-MTDYnzu8qbRIwo1bJmN:b-msl3tp) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1189979f4da67c0bafd97c4e2aff731a75bb27/pkg/sql/catalog/descpb/constraint.go#L125)):*
> ```Go
> 
> // IsPartial returns true if the index is a partial index.
> func (uc *UniqueWithoutIndexConstraint) IsPartial() bool {
> ```

Seems like this belongs elsewhere - there are some methods on `UniqueWithoutIndexConstraint` in `descpb/structured.go`. Might also be worth adding this method to the `UniqueConstraint` interface
___
*[pkg/sql/logictest/testdata/logic_test/create_table, line 408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60289#-MTD__KG5xDqlXZk4ELS:-MTD__KG5xDqlXZk4ELT:b6z2gq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1189979f4da67c0bafd97c4e2aff731a75bb27/pkg/sql/logictest/testdata/logic_test/create_table#L408)):*
> ```
> statement ok
> CREATE TABLE unique_without_index_partial (a INT, b INT, UNIQUE WITHOUT INDEX (a) WHERE b > 5)
> ```

maybe add a test here too to check that the predicate is validated (similar to the test in alter_table)?
___
*[pkg/sql/opt/cat/table.go, line 272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60289#-MTDar3G7__-4VgkIqg6:-MTDar3G7__-4VgkIqg7:b-89r8js) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1189979f4da67c0bafd97c4e2aff731a75bb27/pkg/sql/opt/cat/table.go#L272)):*
> ```Go
> 
> 	// Predicate returns the partial index predicate expression and true if the
> 	// index is a partial index. If it is not a partial index, the empty string
> ```

[nit] partial index -> partial constraint

**Review by mgartner — COMMENTED** [review]
Fixed the comment message and added "Informs...".

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60289#-:-MTIte9vE_kZX7HquLzU:b-w0csgh)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/alter_table.go, line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60289#-MTDP5iq-A7mjPXEm43g:-MTIuY19AXtNuLVnM0-h:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1189979f4da67c0bafd97c4e2aff731a75bb27/pkg/sql/alter_table.go#L197)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] maybe worth encapsulating this validation inside `addUniqueWithoutIndexTableDef`? Then you could remove it from here and `create_table.go`
</blockquote></details>

Done.
___
*[pkg/sql/opt_catalog.go, line 786 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60289#-MTDY4hTDqj87568O47P:-MTIvms-76Dqk8Qcq6Xj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1189979f4da67c0bafd97c4e2aff731a75bb27/pkg/sql/opt_catalog.go#L786)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

need to add the predicate here too (this will just be the index predicate)
</blockquote></details>

Done.
___
*[pkg/sql/catalog/descpb/constraint.go, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60289#-MTDYVhz3vr5sNHkfsEf:-MTIw7bZ9qbNjzMLliwQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1189979f4da67c0bafd97c4e2aff731a75bb27/pkg/sql/catalog/descpb/constraint.go#L124)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] index -> constraint
</blockquote></details>

Done.
___
*[pkg/sql/catalog/descpb/constraint.go, line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60289#-MTDYnzu8qbRIwo1bJmM:-MTIwE0VBOsg8D4UGsf7:bujtcl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1189979f4da67c0bafd97c4e2aff731a75bb27/pkg/sql/catalog/descpb/constraint.go#L125)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Seems like this belongs elsewhere - there are some methods on `UniqueWithoutIndexConstraint` in `descpb/structured.go`. Might also be worth adding this method to the `UniqueConstraint` interface
</blockquote></details>

Done. `UniqueConstraint.Predicate` already provides a boolean the indications if the unique constraint is partial.
___
*[pkg/sql/logictest/testdata/logic_test/create_table, line 408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60289#-MTD__KG5xDqlXZk4ELS:-MTIxFTs85LX4GLW3iIZ:b291dxe) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1189979f4da67c0bafd97c4e2aff731a75bb27/pkg/sql/logictest/testdata/logic_test/create_table#L408)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

maybe add a test here too to check that the predicate is validated (similar to the test in alter_table)?
</blockquote></details>

Done. Also added a TODO that there could be more tests if we ever decide to make UNIQUE WITHOUT INDEX available by default.
___
*[pkg/sql/opt/cat/table.go, line 272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60289#-MTDar3G7__-4VgkIqg6:-MTIyHW39W2wo8vS44zP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1189979f4da67c0bafd97c4e2aff731a75bb27/pkg/sql/opt/cat/table.go#L272)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] partial index -> partial constraint
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm: (although looks like you need to rebase)

> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60289#-:-MTJ0FpG4BZhq4fvpg1Y:b49mhpp)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/catalog/descpb/structured.go, line 341 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60289#-MTJ-xV47LZuZDwzb6bV:-MTJ-xV47LZuZDwzb6bW:b-51x7ym) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea4652bb2aabdb739cd97ec4a7f62e728ac623c2/pkg/sql/catalog/descpb/structured.go#L341)):*
> ```Go
> // both UNIQUE indexes and UNIQUE WITHOUT INDEX constraints to serve as
> // the referenced side of a foreign key constraint.
> type UniqueConstraint interface {
> ```

I meant you could add `IsPartial` to this interface -- not sure if it's needed, but could be useful at some point
___
*[pkg/sql/catalog/descpb/structured.go, line 367 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60289#-MTJ-RYEDI0FfbdGi1jW:-MTJ-RYEDI0FfbdGi1jX:b-eebzmn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea4652bb2aabdb739cd97ec4a7f62e728ac623c2/pkg/sql/catalog/descpb/structured.go#L367)):*
> ```Go
> 
> // IsPartial returns true if the constraint is a partial unique constraint.
> func (uc *UniqueWithoutIndexConstraint) IsPartial() bool {
> ```

[nit] the receiver has a different name than the other methods

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60289)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/catalog/descpb/structured.go, line 341 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60289#-MTJ-xV47LZuZDwzb6bV:-MTJ8HpZAHgiJ2Bg_Ih-:b-vsaflm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea4652bb2aabdb739cd97ec4a7f62e728ac623c2/pkg/sql/catalog/descpb/structured.go#L341)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I meant you could add `IsPartial` to this interface -- not sure if it's needed, but could be useful at some point
</blockquote></details>

Oof. Looks like we use this interfto allow for FK references to a unique index and unique constraints. We'll probably have to prevent partial unique constraints from being on the reference side of a FK. It might be needed for that, but I'll leave for a future PR.
___
*[pkg/sql/catalog/descpb/structured.go, line 367 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60289#-MTJ-RYEDI0FfbdGi1jW:-MTJ8qr6C7WcpWUHjq0E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea4652bb2aabdb739cd97ec4a7f62e728ac623c2/pkg/sql/catalog/descpb/structured.go#L367)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] the receiver has a different name than the other methods
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60289)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @RaduBerinde)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
