### PR TITLE
cleanup: replaces context.TODO() in places where a context.Context already exists

### PR DESCRIPTION
**Pull request by d4l3k**
Related to https://github.com/cockroachdb/cockroach/issues/1779

Was found using a modification to golint. https://github.com/golang/lint/pull/227

@tamird

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8194)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm_strong:  but wait for @petermattis' #8166. Gonna have some conflicts :(

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8194#-:-KO6lj0Jjm_IbwK0UpuT:-1633193091)*

**Comment by petermattis** [comment]
:lgtm: though ditto what @tamird said.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8194#-:-KO6zz5f0cGusBGjvlYM:415718320)*

**Comment by d4l3k** [comment]
Updated after Peter's commit

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8194#-:-KOBM6FbfxjuubacB0Bd:1417088721)*

**Comment by d4l3k** [comment]
Figured out why the tests were failing and added a comment about why. Also fixed several other `context.TODO()`s that were added in the meantime.

**Comment by tamird** [comment]
Another easy one is to blindly replace all context.TODO() in tests with context.Background().

:lgtm:

---

Reviewed 1 of 17 files at r1, 11 of 11 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[kv/txn_coord_sender.go, line 566 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8194#-KOH1-tmIvTmFzeJX5Ya:-KOH1-tmIvTmFzeJX5Yb:1922536084) ([raw file](https://github.com/cockroachdb/cockroach/blob/64b949994fb2ed7a0c7eba93e93f593fa4ca6ca6/kv/txn_coord_sender.go#L566)):*
> ```Go
> // that we pass the same one in every request, but it's brittle to rely on this
> // forever.
> // TODO(wiz): Update (*DBServer).Batch to not use context.TODO().
> ```

What will it use instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8194#-:-KOH3hmXNR3YYA78nPGQ:-593242048)*

**Comment by d4l3k** [comment]
*[kv/txn_coord_sender.go, line 566 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8194#-KOH1-tmIvTmFzeJX5Ya:-KOH6fuCApVOimiSRQPv:488725892) ([raw file](https://github.com/cockroachdb/cockroach/blob/64b949994fb2ed7a0c7eba93e93f593fa4ca6ca6/kv/txn_coord_sender.go#L566)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> What will it use instead?
</details>
It would use the RPC context since the context no longer needs to last longer than the connection.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8194)*

**Pull request merged**
