### PR TITLE
storage: don't initialize queues without gossip

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7157)

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM

**Comment by tamird** [comment]
:lgtm:

<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> LGTM
</details>


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/store.go, line 817 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7157#-KJut_t9DvqLy_Zambho:-KJut_t9DvqLy_Zambhp:-293513812) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fadaa5d97cd210ca881e212d10d6a35ffd46171/storage/store.go#L817)):*
> ```Go
> 	s.stopper = stopper
> 
> 	if s.ctx.Gossip != nil {
> ```

nit: i'd condition this on the existence of the queues:
```
for _, queue := range []stop.Closer{s.gcQueue,s.splitQueue, ...} {
  if queue != nil {
    s.stopper.AddCloser(queue)
  }
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7157#-:-KJutsudwgsN3Sghm8s5:1417088721)*

**Comment by tamird** [comment]
Fixes #7150.

**Comment by bdarnell** [comment]
Should we add an `IsBootstrap` field to StoreContext instead of using `Gossip == nil`? I could imagine us either creating a dummy `Gossip` object during bootstrapping  (which would allow us to remove the two `s.ctx.Gossip != nil` checks that we currently have but would break this change), or making the queues work without gossip, which would make it look like this check could be removed. (the only reason `baseQueue` needs gossip is to see whether the range needs to be split; the queues that accept unsplit ranges could run with no gossip)

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Fixes #7150.
</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7157#-:-KK0Rt8c6mR_wxzVMdxF:1186364058)*

**Comment by petermattis** [comment]
`baseQueue` also needs gossip in order to pass the `SystemConfig` object  to`queueImpl.{shouldQueue,process}`. Plumbing through a `StoreContext.IsBootstrap` field sounds reasonable, but I'm not seeing any immediate benefits. I'm going to leave this as-is for now. 

<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Should we add an `IsBootstrap` field to StoreContext instead of using `Gossip == nil`? I could imagine us either creating a dummy `Gossip` object during bootstrapping  (which would allow us to remove the two `s.ctx.Gossip != nil` checks that we currently have but would break this change), or making the queues work without gossip, which would make it look like this check could be removed. (the only reason `baseQueue` needs gossip is to see whether the range needs to be split; the queues that accept unsplit ranges could run with no gossip)
</details>


---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/store.go, line 817 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7157#-KJut_t9DvqLy_Zambho:-KKAD6e2kkKFIalYRUz0:687170166) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fadaa5d97cd210ca881e212d10d6a35ffd46171/storage/store.go#L817)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: i'd condition this on the existence of the queues:
> ```
> for _, queue := range []stop.Closer{s.gcQueue,s.splitQueue, ...} {
>   if queue != nil {
>     s.stopper.AddCloser(queue)
>   }
> }
> ```
</details>
Heh, that doesn't work as `queue` is never equal to `nil`. Comparing an interface type to `nil` is fraught. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7157#-:-KK9xdYH_jbJAagqP5mW:466207127)*

**Comment by tamird** [comment]
:lgtm:

<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `baseQueue` also needs gossip in order to pass the `SystemConfig` object  to`queueImpl.{shouldQueue,process}`. Plumbing through a `StoreContext.IsBootstrap` field sounds reasonable, but I'm not seeing any immediate benefits. I'm going to leave this as-is for now. 
</details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7157#-:-KKAGyRm7_e4ZRE4_uTl:1417088721)*

**Pull request merged**
