### PR TITLE
sql/server/ui: add end interval time to statements and transaction pages

### LINKED ISSUE #70236: Add interval end time to statement and transaction pages in the console UX
For the V1 console UX of persisted statistics, we surface the execution **start time** interval. We should surface the end time interval as well to provide clarity on the actual aggregated interval per row/fingerprint.

This can be derived by using  the aggregated_ts and agg_interval column in the system.*statistics table where the column will need to be added to the virtual table (including a protobuf change). 

UX: https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/21.2_SQL-obsrv_query-performance?node-id=2929%3A124036

### PR DESCRIPTION
**Pull request by xinhaoz**
### First Commit
sql: add aggregation_interval col to virtual stmt/txn stats tables
This commit adds the column `aggregation_interval` to
crdb_internal.statement_statistics and crdb_internal.transaction_statistics
virtual tables, representing the aggregation interval duration for the entry.
The column value is pulled directly from the `agg_interval` column
in the corresponding system tables for persisted stats. In the case of
in-memory stats, we populate the field by retrieving the current cluster
setting for the aggregation interval.

Release note (sql change): `aggregation_interval` column has been added
to crdb_internal.{statement,transaction}_statistics tables, representing
the aggregation duration.

### Second Commit
server: add aggregationInterval to CombinedStatementStats response 
Part of cockroachdb#70236

This commit adds the aggregation interval to the CombinedStatementStats
API response, under `CollectedTransactionStatistics` and
`CollectedStatementStatistics.Key` fields.

Release note (api change): `aggregationInterval` field has been
added to combined statements response.

### Third Commit
ui/cluster-ui: add interval end time to statements/txns pages 

Resolves #70236

This commit adds the interval end time to the statements and
transaction pages. The column `Interval Start Time` has been
updatd to `Aggregation Interval` to include both the start
and end interval times. Similarly, the statements details page
now includes the full interval. As a result, statement grouping
has been updated to group statments based on the both the
interval start and end time.

Release note (ui change): `Interval Start Time (UTC)` column
in statements and transactions pages has been renamed `Aggregation
Interval (UTC)` and is the interval of aggregation. The statement
details page will also display the interval for which the user
is viewing statement details.

-----------------------------------
Statements page
image

Transactions page
image

Statement details
image

### CODE REVIEW

**Review by Azhng — COMMENTED** [review]
> Reviewed 6 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71538)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @xinhaoz)

___
*[-- commits, line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71538#-MmEoTIA9kMSRiizKA9w):*
Hmm this is making me a bit sad. We should really move to unify the proto in `pkg/server` and the proto in `pkg/roahcpb`. 

How do you feel about adding those fields into `pkg/roachpb` proto and just make `pkg/server` directly import those? 
___
*[pkg/sql/crdb_internal.go, line 5276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71538#-MmElWI19bOEAa3u3QX9:-MmElWI19bOEAa3u3QXA:bygiv0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8563fd55c5fe22179fccab04712cd1296ea8c45/pkg/sql/crdb_internal.go#L5276)):*
> ```Go
>     metadata       				JSONB NOT NULL,
>     statistics     				JSONB NOT NULL,
>     aggregation_interval  INTERVAL NOT NULL
> ```

nit: seems like the white space here are not aligned
___
*[pkg/sql/sqlstats/persistedsqlstats/mem_iterator.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71538#-MmElv9U9-5buqVTM08Y:-MmElv9U9-5buqVTM08Z:b-mtj8rk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8563fd55c5fe22179fccab04712cd1296ea8c45/pkg/sql/sqlstats/persistedsqlstats/mem_iterator.go#L55)):*
> ```Go
> 
> // memTxnStatsIterator wraps a sslocal.TxnStatsIterator. Since in-memory
> // transaction statistics does not have aggregated_ts field populated,
> ```

nit: lets also update the comment here too 
___
*[pkg/ui/workspaces/db-console/src/util/appStats.ts, line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71538#-MmF0oo68XUFWRUGyWwl:-MmF0oo68XUFWRUGyWwm:b-cr3ate) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b4569f2433389528fb326546dc5f6278d2a44c6/pkg/ui/workspaces/db-console/src/util/appStats.ts#L19)):*
> ```XML
> import { FixLong } from "src/util/fixLong";
> import { uniqueLong } from "src/util/arrays";
> import { TimestampToNumber, DurationToNumber } from "src/util/convert";
> ```

Hmm, can we just directly import from `cluster-ui` and avoid the import here?

**Review by maryliag — COMMENTED** [review]
> Reviewed 7 of 8 files at r1, 4 of 4 files at r2, 15 of 18 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71538)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts, line 252 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71538#-MmIrN_90JiAl7vmp_qN:-MmIrN_90JiAl7vmp_qO:b-j51id7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b4569f2433389528fb326546dc5f6278d2a44c6/pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts#L252)):*
> ```XML
> // This function returns a key based on all parameters
> // that should be used to group statements.
> // Parameters being used: query, implicit_txn, database, and aggregated_ts.
> ```

nit: comment needs to be updated
___
*[pkg/ui/workspaces/db-console/src/util/appStats.ts, line 231 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71538#-MmIrvPD7imuweyvtWjH:-MmIrvPD7imuweyvtWjI:b-w5fg7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b4569f2433389528fb326546dc5f6278d2a44c6/pkg/ui/workspaces/db-console/src/util/appStats.ts#L231)):*
> ```XML
> // This function returns a key based on all parameters
> // that should be used to group statements.
> // Parameters being used: query, implicit_txn, database, and aggregated_ts.
> ```

nit: updste comment

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71538)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @xinhaoz)

___
*[-- commits, line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71538#-MmEoTIA9kMSRiizKA9w):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Just want to verify, are you suggesting addressing https://github.com/cockroachdb/cockroach/issues/69326 in this PR?
</blockquote></details>

Ah forgot that we had an issue for this already. This PR is already getting large, let's do it in a different PR :D

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71538)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @xinhaoz)

___
*[pkg/ui/workspaces/db-console/src/util/appStats.ts, line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71538#-MmF0oo68XUFWRUGyWwl:-MmJiSIC0VnXRKsU5g4e:b294w5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b4569f2433389528fb326546dc5f6278d2a44c6/pkg/ui/workspaces/db-console/src/util/appStats.ts#L19)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

We aren't exporting anything in /utils/ folder to the cluster-ui package AFAIK. Not sure if there is a good reason for this, as doing so will avoid the need to duplicate convert / appStats in both packages. What do you think of merging these files in the future? cc @maryliag 
</blockquote></details>

cluster-ui is exporting the utils here https://github.com/cockroachdb/cockroach/blob/a1e309a93d3bacab4d639e35a478353af7fa8a52/pkg/ui/workspaces/cluster-ui/src/index.ts#L41
which includes the convert file that has your new function, so you can use functions from there. I don't know the reasoning from creating duplicate files for those util functions, maybe worth asking on cluster-ui channel to make sure there isn't something we're not considering. 
To use your function you can import with
`import DurationToNumber from "@cockroachlabs/cluster-ui";`

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71538)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @xinhaoz)

___
*[pkg/sql/crdb_internal.go, line 5276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71538#-MmElWI19bOEAa3u3QX9:-MmK76Z6CwCEyx6cURF0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8563fd55c5fe22179fccab04712cd1296ea8c45/pkg/sql/crdb_internal.go#L5276)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: seems like the white space here are not aligned
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/mem_iterator.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71538#-MmElv9U9-5buqVTM08Y:-MmK77wG5dTgMegqBn3G:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8563fd55c5fe22179fccab04712cd1296ea8c45/pkg/sql/sqlstats/persistedsqlstats/mem_iterator.go#L55)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: lets also update the comment here too 
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts, line 252 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71538#-MmIrN_90JiAl7vmp_qN:-MmK79CPDRHTgXk8F2mv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b4569f2433389528fb326546dc5f6278d2a44c6/pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts#L252)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: comment needs to be updated
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/db-console/src/util/appStats.ts, line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71538#-MmF0oo68XUFWRUGyWwl:-MmK7Ave26DaoD8d7Kwd:b-j3ckav) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b4569f2433389528fb326546dc5f6278d2a44c6/pkg/ui/workspaces/db-console/src/util/appStats.ts#L19)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

cluster-ui is exporting the utils here https://github.com/cockroachdb/cockroach/blob/a1e309a93d3bacab4d639e35a478353af7fa8a52/pkg/ui/workspaces/cluster-ui/src/index.ts#L41
which includes the convert file that has your new function, so you can use functions from there. I don't know the reasoning from creating duplicate files for those util functions, maybe worth asking on cluster-ui channel to make sure there isn't something we're not considering. 
To use your function you can import with
`import DurationToNumber from "@cockroachlabs/cluster-ui";`
</blockquote></details>

Done. As discussed offline, we might want to consider removing the util files / other duplicated files from db-console package in favour of importing from cluster-ui. If we want to do that, I can file a ticket for it.
___
*[pkg/ui/workspaces/db-console/src/util/appStats.ts, line 231 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71538#-MmIrvPD7imuweyvtWjH:-MmK718U8frNPRotl7sX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b4569f2433389528fb326546dc5f6278d2a44c6/pkg/ui/workspaces/db-console/src/util/appStats.ts#L231)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: updste comment
</blockquote></details>

Done.

**Review by maryliag — APPROVED** [review]
one nit from me, and :lgtm:  ( as long tests are passing)

> Reviewed 2 of 24 files at r4, 4 of 4 files at r5, 17 of 18 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71538#-:-MmKLCVdD54-qcBIoiW7:b5ypyrm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @xinhaoz)

___
*[pkg/ui/workspaces/db-console/src/util/convert.ts, line 91 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71538#-MmKKokkEM17xV8xB2iw:-MmKKokkEM17xV8xB2ix:b4p9phg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4ddfede817d8ab10b336833c3c819f7692e7406/pkg/ui/workspaces/db-console/src/util/convert.ts#L91)):*
> ```XML
> 
> /**
>  * DurationToNumber converts a Duration object, as seen in wire.proto, to
> ```

function no longer used and can be removed

**Comment by xinhaoz** [comment]
bors r=maryliag

**Pull request merged**
