### PR TITLE
server: remove duplicated/redundant file 

### PR DESCRIPTION
**Pull request by VirrageS**
`pkg/server/pagination.go.orig` file is never used and is unnecessary
copy of `pkg/server/pagination.go`. This file was probably created
during some git modifications or refactoring.

### CODE REVIEW

**Comment by knz** [comment]
@VirrageS please edit your commit message as per our guidelines https://wiki.crdb.io/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages

then this will be good to go

thank you

**Comment by VirrageS** [comment]
@knz I've updated the commit message. Let me know if there is anything more I need to do.

**Comment by knz** [comment]
Thank you, the commit message looks good.
Ideally you'd have:
- updated the PR title and description from the commit message (I just did this for you)
- added a release note at the end the commit message, or in your case the text `Release note: None` since it's not a user-facing change.

Once you do this, this will be good to go. Thanks

**Comment by VirrageS** [comment]
@knz I've just pushed the updated commit. I wasn't sure about the "release note" part.

**Review by knz — APPROVED** [review]
perfect, this is brilliant.
Thanks for the extra steps!

bors r+

**Pull request merged**
