### PR TITLE
kv/kvnemesis: make deletes distinct from other writes in errors

### PR DESCRIPTION
**Pull request by AlexTalks**
Previously when kvnemesis performed validation, in error messaging,
delete operations were only distinguishable from other writes by the
value written.  With this change, they will be identified as follows:

```
committed txn missing write: [w]"a":missing->v1
committed txn missing write: [d]"a":missing-><nil>
```
This will also allow us to distinguish between point and ranged deletes,
once they are introduced.

Release justification: Non-production code change.
Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69488)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks)

___
*[pkg/kv/kvnemesis/validator.go, line 1000 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69488#-MiRjAj05BM9Uej7NlTM:-MiRjAj05BM9Uej7NlTN:b2wxl07) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c9f2aae871870be318116338a68f55ab0ba8aab/pkg/kv/kvnemesis/validator.go#L1000)):*
> ```Go
> 			}
> 			fmt.Fprintf(&buf, "[%s]%s:%s->%s",
> 				opCode, o.Key, ts, mustGetStringValue(o.Value.RawBytes))
> ```

If `o.isDelete()`, do we still want to print the value?

**Review by AlexTalks — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69488)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvnemesis/validator.go, line 1000 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69488#-MiRjAj05BM9Uej7NlTM:-Mjokm5q2cGnQ1BaIbBW:bmv9of1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c9f2aae871870be318116338a68f55ab0ba8aab/pkg/kv/kvnemesis/validator.go#L1000)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

If `o.isDelete()`, do we still want to print the value?
</blockquote></details>

I've found it useful to see the `<nil>` in the output personally, as it makes it explicit what should be seen in storage.

**Review by nvb — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69488#-:-Mjq98PA2bms5W1tJiPI:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @AlexTalks)

**Pull request merged**
