### PR TITLE
ui: Replace "Admin UI" with "DB Console" on login

### PR DESCRIPTION
**Pull request by nathanstilwell**
Changed a few remaining instances of "Admin UI" to "DB Console" that
were spotted on the login page.

Release note (ui change): Change copy that referred to the app as "Admin
UI" to "DB Console" instead

### CODE REVIEW

**Review by koorosh — APPROVED** [review]
LGTM

**Comment by nathanstilwell** [comment]
bors retry

**Comment by nathanstilwell** [comment]
bors retry

**Comment by knz** [comment]
@nathanstilwell @thtruo is this a candidate for a backport to 21.1?

**Comment by thtruo** [comment]
I assumed this was going to make it to 21.1 - if that's not the case, then yeah this is a backport candidate

**Pull request merged**
