### PR TITLE
roachtest: avoid flake in post-test assertions after decommission

### PR DESCRIPTION
**Pull request by AlexTalks**
Previously we have seen flakes in the `decommission/mixed-version` roachtest due to failures in the post-test assertions; after investigation it was found that the reason for these flakes is that in the case a node is decommissioning itself (`target == from`), the drain step is skipped to avoid RPC failures on finalization. In this case, the post-test assertions would race with the change in the value of the `/health?ready=1` endpoint and fail if they begin before the decommissioned node's liveness expires. This change fixes the test to consider a node decommissioned only once the health check endpoint returns a value other than `200 OK`.

Part of: #107855

Release note: None

### CODE REVIEW

**Comment by AlexTalks** [comment]
Alternatively we could check liveness (now called vitality) from the `/health?ready=1` endpoint and return `503 service unavailable` when a node is decommissioning.

I see this is done in `systemAdminServer.checkReadinessForHealthCheck(..)` but not `adminServer. checkReadinessForHealthCheck(..)`, and there's a comment stating that we we avoid checking liveness in the less-permissioned latter version but I'm not sure why.  @knz could you shed some light on the reasoning here?

**Comment by knz** [comment]
The latter is the code run on SQL pods which don't (currently) have access to kv liveness.

This may need to be improved, but I'm not sure it's relevant to the failure at hand? Is this failure observed while a secondary tenant is active?

**Comment by AlexTalks** [comment]
Maybe I'm missing something about how the `/health?ready=1` endpoint works, but it seems like it invokes `adminServer. checkReadinessForHealthCheck(..)`, at least on a decommissioned node.  Since it's possible for a node to be marked `decommissioned` before it is actually drained (if a node is decommissioning itself), there is a brief period in which `/health?ready=1` can return `200 OK` on a decommissioned node before the drain has completed.  This seems a bit incorrect, hence why I asked about why we aren't checking liveness in that function - which happens to cause a flake in this test because the post-test health check is sometimes returning `200 OK` before the drain finishes.  This is not a multitenant test, so it is happening even with a singular system tenant.

**Comment by knz** [comment]
> Maybe I'm missing something about how the /health?ready=1 endpoint works, but it seems like it invokes `adminServer. checkReadinessForHealthCheck(..)`

Are you sure about your use case?
Is your use case not by any chance hitting `(*systemAdminServer).Health()`, which then calls `(*systemAdminServer).checkReadinessForHealthCheck()`, which in turns _does_ check liveness?

**Comment by AlexTalks** [comment]
> Are you sure about your use case?

My apologies, I was wrong here.  We _are_ hitting `systemAdminServer.Health(..)` which - on 23.1 and prior - evaluates liveness based on the expiration of the liveness record, and doesn't consider decommissioning.  This has already been changed on master, so I'm not sure backporting changes to liveness behavior like this makes sense - likely it is more preferable in a mixed version test like this to simply wait for the expected value of the health check externally in the test (I.e. wait for the drain to complete).

Sorry about that!  Let me know if this test change looks ok, and we can merge it and backport it to 23.1.  If necessary I can add a `TODO` stating that this check should be removed after 24.1.0 as well.

**Comment by knz** [comment]
Just for my education, can you shed some light on the following:

> in the case a node is decommissioning itself (target == from), the drain step is skipped 
> change the test to only consider a node decommissioned after it is fully drained.

So you write "self-decommission -> no drain step"
and then also "test waits for drain to complete"

Is that going to result in a deadlock? If the drain step is skipped, what will prevent the test from waiting forever on a drain that does not happen?

**Comment by AlexTalks** [comment]
@knz you are right, the comments and the description of the PR were not correct.

What we are really ensuring here is that when a node is self-decommissioning, the test shouldn't end until the health check returns non-`200 OK`.  That happens when the liveness expires in versions prior to 23.2.  I've updated the comments and the commit/PR message.

**Review by knz — APPROVED** [review]
Thank you

**Comment by AlexTalks** [comment]
TFTR!

bors r+

**Pull request merged**
