### PR TITLE
opt: rework lookup join rules

### PR DESCRIPTION
**Pull request by RaduBerinde**
The PushJoinThroughIndexJoin rules result in too many combinations
being considered. For example, if we are joining two tables with three
indexes each, we will consider joining all possible pairs of indexes,
followed by index joins as needed. The main purpose of these rules is
to generate lookup joins (via a subsequent application of a
GenerateLookupJoin rule). Note that this won't work at all anymore if
we stop generating index joins with non-constrained scans.

This change reworks the lookup join exploration rules to run off of
the "canonical" Scan operator and identify indexes for lookup joins
(as opposed to relying on the memo having Scan/IndexJoin expressions
for all indexes).

This actually simplifies the high-level rules because some of the
cases are handled internally by the exploration function.

The new rules construct lookup join groups so we need to implement
logical properties and stats for them.

Release note: None

### CODE REVIEW

**Review by rytaft — CHANGES_REQUESTED** [review]
:lgtm_strong: 

> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-:-LKYfLVt46BAZ3g1p_Ub:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/metadata_column.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKYT_xC7PpGAwQH4v1Y:-LKYT_xC7PpGAwQH4v1Z:b-lu8dk3) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/metadata_column.go#L37)):*
> ```Go
> // FindInColList searches for a column in the list and returns its index in the
> // list (if successful).
> func FindInColList(cl ColList, col ColumnID) (idx int, ok bool) {
> ```

[nit] I feel like this should go somewhere else... this file seems to be just high-level definitions, not helper functions
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 593 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKYUw1S4CbrF5JqqHic:-LKYUw1T4WnX3uBT7uYH:b449jjc) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/memo/logical_props_builder.go#L593)):*
> ```Go
> 	// Lookup join output columns are the union between the input columns and the
> 	// retrieved columns.
> 	logical.Relational.OutputCols = inputProps.OutputCols.Union(def.LookupCols)
> ```

[nit] logical.Relational -> relational
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 597 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKYUUdV38k7cZfCwL9l:-LKYUUdWAyOuPm-G8MBw:b5bg0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/memo/logical_props_builder.go#L597)):*
> ```Go
> 	// Not Null Columns
> 	// ----------------
> 	notNullCols := b.tableNotNullCols(md, def.Table)
> ```

I think you can move all this down to the else block below
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 614 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKYUneb38MsC0GJk8Dh:-LKYUneb38MsC0GJk8Di:b-sylvlh) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/memo/logical_props_builder.go#L614)):*
> ```Go
> 	// are outer columns for the lookup join expression, in addition to any outer
> 	// columns inherited from the input.
> 	inputCols := inputProps.OutputCols.Union(def.LookupCols)
> ```

isn't this the same as `relational.OutputCols`?
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 623 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKYVJ0o2wv1s_u9bmHw:-LKYVJ0pEqcXP25xrPIJ:by0au47) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/memo/logical_props_builder.go#L623)):*
> ```Go
> 	// -----------------------
> 	// Start with FDs from left side, and modify based on join type.
> 	// See the general code for join for more details.
> ```

what do you mean by "general code"?
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 643 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKYWnir7Xw9PHtZz8LA:-LKYWnir7Xw9PHtZz8LB:bkzd16d) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/memo/logical_props_builder.go#L643)):*
> ```Go
> 	// Cardinality
> 	// -----------
> 	relational.Cardinality = props.AnyCardinality
> ```

I think you should copy this from `makeJoinCardinaltiy` (or maybe make another helper function):

```
	// Other join types can return up to cross product of rows.
	card = left.Product(right)

	// Apply filter to cardinality.
	filter := ev.Child(2)
	if filter.Operator() != opt.TrueOp {
		contradiction := filter.Operator() == opt.FalseOp ||
			filter.Logical().Scalar.Constraints == constraint.Contradiction
		if contradiction {
			card = props.ZeroCardinality
		} else {
			card = card.AsLowAs(0)
		}
	}
```
___
*[pkg/sql/opt/memo/testdata/logprops/lookup-join, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKYa9hX2yUDbcWaopTR:-LKYa9hY2CAsdqcCdn0k:bgpc77z) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/memo/testdata/logprops/lookup-join#L2)):*
> ```
> exec-ddl
> CREATE TABLE abcd (a INT, b INT, c INT, INDEX (a,b))
> ```

doesn't seem necessary to duplicate these tests here since you already have them in the stats tests.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28924)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/metadata_column.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKYT_xC7PpGAwQH4v1Y:-LKc1u1AEbU9ZpJ_L4V7:b-og30ej) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/metadata_column.go#L37)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] I feel like this should go somewhere else... this file seems to be just high-level definitions, not helper functions
</blockquote></details>

I think `Find` should be a method on `ColList` instead of using a function. I think we should change the type to be `type ColList []ColumnID`. If so, I think it's fine to have this method defined in this file.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 580 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKc9YCR4hemtMmpN0PJ:-LKc8_BJ2SD8c7f9i0OU:bbxyn43) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/memo/logical_props_builder.go#L580)):*
> ```Go
> }
> 
> func (b *logicalPropsBuilder) buildLookupJoinProps(ev ExprView) props.Logical {
> ```

My overall comment is that we need to share more between this and `buildJoinProps`, especially since we plan to support other lookup join types in the future. I'm happy to help with that. It was challenging to get the logic for joins correct, and I only want that code to live in one place.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 607 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKc8T5a6h5xY6sdTl_Y:-LKc8T5a6h5xY6sdTl_Z:b-4dd180) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/memo/logical_props_builder.go#L607)):*
> ```Go
> 		// from the table.
> 		relational.NotNullCols = notNullCols
> 	}
> ```

I think we need to factor out a `makeJoinNotNullCols` function rather than copy-paste.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 618 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKc9P2QAPVE5LEwjqlH:-LKc9P2QAPVE5LEwjqlI:b-bcfbru) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/memo/logical_props_builder.go#L618)):*
> ```Go
> 		relational.OuterCols = onProps.OuterCols.Difference(inputCols)
> 	}
> 	relational.OuterCols.UnionWith(inputProps.OuterCols)
> ```

Ditto here on factoring out helper funcs.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 622 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKc6q03-50QBVqkVJAa:-LKc6q03-50QBVqkVJAb:b-v16hme) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/memo/logical_props_builder.go#L622)):*
> ```Go
> 	// Functional Dependencies
> 	// -----------------------
> 	// Start with FDs from left side, and modify based on join type.
> ```

And factor out here as well.

I believe you'd need `leftFD, rightFD, onFD *props.FuncDepSet, inputNullCols opt.ColSet, outputProps *props.Relational`
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 643 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKYWnir7Xw9PHtZz8LA:-LKc4SxS1ZABRZUSpA4X:bpxa903) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/memo/logical_props_builder.go#L643)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think you should copy this from `makeJoinCardinaltiy` (or maybe make another helper function):

```
	// Other join types can return up to cross product of rows.
	card = left.Product(right)

	// Apply filter to cardinality.
	filter := ev.Child(2)
	if filter.Operator() != opt.TrueOp {
		contradiction := filter.Operator() == opt.FalseOp ||
			filter.Logical().Scalar.Constraints == constraint.Contradiction
		if contradiction {
			card = props.ZeroCardinality
		} else {
			card = card.AsLowAs(0)
		}
	}
```
</blockquote></details>

Isn't it possible to modify `makeJoinCardinality` like this:
```
func (b *logicalPropsBuilder) makeJoinCardinality(
	op opt.Operator, left, right props.Cardinality, on ExprView,
) props.Cardinality {
```
Then you can pass in `inputProps.Cardinality` for left, and `props.AnyCardinality` for right. This would pick up the filter code in `makeJoinCardinality`, and make it easier to support `Semi` and `Anti` joins in the future. Though looking at the existing code, I don't know why semi join is excluded from the filter logic.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 896 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKcCsUo0hE7xHDsb1jt:-LKcCsUo0hE7xHDsb1ju:b-tmhh43) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/memo/statistics_builder.go#L896)):*
> ```Go
> }
> 
> func (sb *statisticsBuilder) colStatLookupJoin(
> ```

Seeing all this near-duplication of complex code, I had an idea. Could we create add a `props.Relational` field to `LookupJoinDef` and fill it in as if it were the "right" side of a join? It wouldn't need to be part of the private interning, since it would be functionally determined by other lookup join fields. If we had that, could we then collapse down all this logic to operate over `joinOp, leftProps, rightProps, onProps`?
___
*[pkg/sql/opt/xform/custom_funcs.go, line 623 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKcE1lR--gJHTbroYXU:-LKcE1lR--gJHTbroYXV:b-bpbwi) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/xform/custom_funcs.go#L623)):*
> ```Go
> 	var pkCols opt.ColList
> 
> 	for i := 0; i < tab.IndexCount(); i++ {
> ```

When you rebase, you'll have access to `scanIndexIter`.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 651 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKcFTsp6-JB9ToYT5oS:-LKcFTsp6-JB9ToYT5oT:b-29hczw) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/xform/custom_funcs.go#L651)):*
> ```Go
> 		lookupJoinOn := on
> 
> 		indexCols := md.IndexColumns(scanDef.Table, i)
> ```

`scanIndexIter` has an `isCovering` method for this.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 670 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKcG7Rf-5uxSxja0518:-LKcG7Rf-5uxSxja0519:b-ax6ly6) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/xform/custom_funcs.go#L670)):*
> ```Go
> 		}
> 
> 		// The index is not covering. We have to generate an index join above the
> ```

I think you should lift this comment to be part of an expanded `GenerateLookupJoins` comment (see `GenerateConstrainedScans` comment for comparison). The current `GenerateLookupJoins` is skimpy, and I think it's a better place for this stuff to go than inline in the code.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 701 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKcGrqh7vNxrUxkFi8v:-LKcEh7kCqwyPZHr3aPH:b-38fpcd) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/xform/custom_funcs.go#L701)):*
> ```Go
> 		}
> 
> 		if pkCols == nil {
> ```

Can you factor out a function to do this pkCols logic? `indexScanBuilder` has a `primaryKeyCols` method that has the same logic in it.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/memo/statistics_builder.go, line 896 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKcCsUo0hE7xHDsb1jt:-LKgoGwY4yel3epCDOZH:b-vbqnh0) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/memo/statistics_builder.go#L896)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Seeing all this near-duplication of complex code, I had an idea. Could we create add a `props.Relational` field to `LookupJoinDef` and fill it in as if it were the "right" side of a join? It wouldn't need to be part of the private interning, since it would be functionally determined by other lookup join fields. If we had that, could we then collapse down all this logic to operate over `joinOp, leftProps, rightProps, onProps`?
</blockquote></details>

Interesting thought. It seems that we would need to call (or reuse some code from) buildScan to populate it (unless we implement something to derive props for an index scan from the props of the primary scan?). We could calculate the field lazily. I'll play with it and see how it goes.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/memo/testdata/logprops/lookup-join, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKYa9hX2yUDbcWaopTR:-LKvfi0R3Sm0mUG8fRDf:b-p2ljtv) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/memo/testdata/logprops/lookup-join#L2)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

doesn't seem necessary to duplicate these tests here since you already have them in the stats tests.
</blockquote></details>

True, but the tests have different purposes.. I wonder, should we hide the stats in the `logprops` tests since they aren't testing that?

**Review by rytaft — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28924)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/testdata/logprops/lookup-join, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKYa9hX2yUDbcWaopTR:-LKwlXMvEJRf8HJLoMTJ:b6rezoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/memo/testdata/logprops/lookup-join#L2)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

True, but the tests have different purposes.. I wonder, should we hide the stats in the `logprops` tests since they aren't testing that?
</blockquote></details>

Sure that sounds good.

**Review by RaduBerinde — COMMENTED** [review]
I managed to consolidate all paths for logical props and statistics. I used a helper struct that keeps track of various properties for the right side and for the filter. I used separate fields and didn't use props.Relational because not all fields would be filled so it would be error-prone.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-:-LKx-TfoET-W-qyZhMCL:b3b6kf3)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/metadata_column.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKYT_xC7PpGAwQH4v1Y:-LKx-1rE4UA03BfvPBof:b-fbnz94) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/metadata_column.go#L37)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I think `Find` should be a method on `ColList` instead of using a function. I think we should change the type to be `type ColList []ColumnID`. If so, I think it's fine to have this method defined in this file.
</blockquote></details>

Will change this to a method when #29120 merges.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 580 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKc9YCR4hemtMmpN0PJ:-LKwwb1bD_TIA8vOMlTe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/memo/logical_props_builder.go#L580)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

My overall comment is that we need to share more between this and `buildJoinProps`, especially since we plan to support other lookup join types in the future. I'm happy to help with that. It was challenging to get the logic for joins correct, and I only want that code to live in one place.
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 593 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKYUw1S4CbrF5JqqHic:-LKwwm435CG_fbO2BIlx:b350gjr) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/memo/logical_props_builder.go#L593)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] logical.Relational -> relational
</blockquote></details>

Code is gone.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 597 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKYUUdV38k7cZfCwL9l:-LKwwjkN310vpPBOfTIx:b350gjr) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/memo/logical_props_builder.go#L597)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think you can move all this down to the else block below
</blockquote></details>

Code is gone.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 607 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKc8T5a6h5xY6sdTl_Y:-LKwwij78mOEx_JxAtj7:b350gjr) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/memo/logical_props_builder.go#L607)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I think we need to factor out a `makeJoinNotNullCols` function rather than copy-paste.
</blockquote></details>

Code is gone.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 614 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKYUneb38MsC0GJk8Dh:-LKwwn334dtoSNC0miix:b350gjr) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/memo/logical_props_builder.go#L614)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

isn't this the same as `relational.OutputCols`?
</blockquote></details>

Code is gone.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 618 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKc9P2QAPVE5LEwjqlH:-LKwwnTEBhBnsxAjAej-:b350gjr) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/memo/logical_props_builder.go#L618)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Ditto here on factoring out helper funcs.
</blockquote></details>

Code is gone.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 622 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKc6q03-50QBVqkVJAa:-LKwwo8F5TZ66Hmjo_-u:b350gjr) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/memo/logical_props_builder.go#L622)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

And factor out here as well.

I believe you'd need `leftFD, rightFD, onFD *props.FuncDepSet, inputNullCols opt.ColSet, outputProps *props.Relational`
</blockquote></details>

Code is gone.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 623 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKYVJ0o2wv1s_u9bmHw:-LKwwqMz2DVlbtzNqphc:b350gjr) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/memo/logical_props_builder.go#L623)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

what do you mean by "general code"?
</blockquote></details>

Code is gone.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 643 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKYWnir7Xw9PHtZz8LA:-LKwwx43DNRthNPgRgCB:b350gjr) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/memo/logical_props_builder.go#L643)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Isn't it possible to modify `makeJoinCardinality` like this:
```
func (b *logicalPropsBuilder) makeJoinCardinality(
	op opt.Operator, left, right props.Cardinality, on ExprView,
) props.Cardinality {
```
Then you can pass in `inputProps.Cardinality` for left, and `props.AnyCardinality` for right. This would pick up the filter code in `makeJoinCardinality`, and make it easier to support `Semi` and `Anti` joins in the future. Though looking at the existing code, I don't know why semi join is excluded from the filter logic.
</blockquote></details>

Code is gone.
___
*[pkg/sql/opt/memo/testdata/logprops/lookup-join, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKYa9hX2yUDbcWaopTR:-LKwzuc47Nf7oE_zaxUh:b-hbphir) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/memo/testdata/logprops/lookup-join#L2)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Sure that sounds good.
</blockquote></details>

Opened another PR, will rebase when that merges.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 623 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKcE1lR--gJHTbroYXU:-LKwru-20v8IcxY4kuu3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/xform/custom_funcs.go#L623)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

When you rebase, you'll have access to `scanIndexIter`.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 651 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKcFTsp6-JB9ToYT5oS:-LKwrtD14z5Nxtq8owtI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/xform/custom_funcs.go#L651)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

`scanIndexIter` has an `isCovering` method for this.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 670 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKcG7Rf-5uxSxja0518:-LKwrv9h-yOx9cC6e_oI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/xform/custom_funcs.go#L670)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I think you should lift this comment to be part of an expanded `GenerateLookupJoins` comment (see `GenerateConstrainedScans` comment for comparison). The current `GenerateLookupJoins` is skimpy, and I think it's a better place for this stuff to go than inline in the code.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 701 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKcGrqh7vNxrUxkFi8v:-LKwtyw_6WnT6jV-dLVk:b-3pvysw) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/xform/custom_funcs.go#L701)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Can you factor out a function to do this pkCols logic? `indexScanBuilder` has a `primaryKeyCols` method that has the same logic in it.
</blockquote></details>

It's not quite the same, I need a ColList not a ColSet.

**Review by rytaft — APPROVED** [review]
:lgtm: Nicely done!

> Reviewed 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-:-LKxEBD51qtHNUZGn3_1:b-msncp4)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/xform/custom_funcs.go, line 672 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKxCmP36Eoee6a0pSJf:-LKxCmP36Eoee6a0pSJg:bh0c55a) ([raw file](https://github.com/cockroachdb/cockroach/blob/356c952f2a1207c9073187df19818901e06d70d8/pkg/sql/opt/xform/custom_funcs.go#L672)):*
> ```Go
> //     lookup join. Note that this index join is also implemented as a
> //     LookupJoin, because an IndexJoin can only output columns from one table,
> //     whereas we also need to output columns from Left.
> ```

[nit] Left -> Input

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28924)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/xform/custom_funcs.go, line 672 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKxCmP36Eoee6a0pSJf:-LKxEZh-3apUYmhPt77Z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/356c952f2a1207c9073187df19818901e06d70d8/pkg/sql/opt/xform/custom_funcs.go#L672)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] Left -> Input
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28924)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/xform/custom_funcs.go, line 672 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKxCmP36Eoee6a0pSJf:-LKxEqqt79fFH98elwVt:b-lvt2ti) ([raw file](https://github.com/cockroachdb/cockroach/blob/356c952f2a1207c9073187df19818901e06d70d8/pkg/sql/opt/xform/custom_funcs.go#L672)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't think you pushed...

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28924)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/xform/custom_funcs.go, line 672 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKxCmP36Eoee6a0pSJf:-LKxFkksBrQqmopsaUgc:bo5fsqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/356c952f2a1207c9073187df19818901e06d70d8/pkg/sql/opt/xform/custom_funcs.go#L672)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I don't think you pushed...
</blockquote></details>

Reviewable sometimes takes a while to notice

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28924)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/xform/custom_funcs.go, line 672 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKxCmP36Eoee6a0pSJf:-LKxHiiP3VsoBBYGMTHI:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/356c952f2a1207c9073187df19818901e06d70d8/pkg/sql/opt/xform/custom_funcs.go#L672)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Reviewable sometimes takes a while to notice
</blockquote></details>

:thumbsup:

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28924)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/metadata_column.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-LKYT_xC7PpGAwQH4v1Y:-LKxdNUE5gNfdcqNsD8C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a9a77209a225c66ef636adb97f148946d5feb7/pkg/sql/opt/metadata_column.go#L37)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Will change this to a method when #29120 merges.
</blockquote></details>

Done.

**Review by andy-kimball — APPROVED** [review]
:lgtm:, a very tough piece of work to complete, congrats on getting it over the finish line.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28924#-:-LL0fGae4xucCnc0UG0F:b-sy7uj2)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Comment by RaduBerinde** [comment]
Thanks for the reviews!

bors r+

**Pull request merged**
