### PR TITLE
c-deps: upgrade rocksdb to 6.2.1

### LINKED ISSUE #37602: storage: upgrade RocksDB to 6.0.2
We should upgrade RocksDB to 6.0.2 early in the 19.2 release cycle. That release contains lots of improvements to the range tombstone implementation. Those improvements replace the custom patches we have on crl-release-5.17.2. Fewer customer patches (I think we'll need zero) is a good thing.

It is possible that we should upgrade to 5.18.3 instead. It isn't clear to me how baked 6.0.2 is vs 5.18.3.

### PR DESCRIPTION
**Pull request by ajkr**
Release branch: https://github.com/cockroachdb/rocksdb/tree/crl-release-6.2.1

See checklist: https://github.com/cockroachdb/rocksdb/issues/37

Fixes #37602

Release note: None

### CODE REVIEW

**Comment by ajkr** [comment]
Current error:

```
[21:09:34]
[Compile C dependencies] In file included from /go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/util/jemalloc_nodump_allocator.cc:6:
[21:09:34]
[Compile C dependencies] In file included from /go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/util/jemalloc_nodump_allocator.h:14:
[21:09:34]
[Compile C dependencies] In file included from /go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/util/core_local.h:15:
[21:09:34]
[Compile C dependencies] In file included from /go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/util/random.h:11:
[21:09:34]
[Compile C dependencies] In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/random:50:
[21:09:34]
[Compile C dependencies] In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/x86_64-linux-gnu/c++/5.4.0/bits/opt_random.h:33:
[21:09:34]
[Compile C dependencies] In file included from /usr/lib/llvm-3.8/bin/../lib/clang/3.8.0/include/x86intrin.h:29:
[21:09:34]
[Compile C dependencies] In file included from /usr/lib/llvm-3.8/bin/../lib/clang/3.8.0/include/immintrin.h:29:
[21:09:34]
[Compile C dependencies] In file included from /usr/lib/llvm-3.8/bin/../lib/clang/3.8.0/include/xmmintrin.h:36:
[21:09:34]
[Compile C dependencies] /usr/lib/llvm-3.8/bin/../lib/clang/3.8.0/include/mm_malloc.h:39:16: error: 'posix_memalign' is missing exception specification 'throw()'
[21:09:34]
[Compile C dependencies] extern "C" int posix_memalign(void **__memptr, size_t __alignment, size_t __size);
[21:09:34]
[Compile C dependencies]                ^
[21:09:34]
[Compile C dependencies] /go/native/x86_64-pc-linux-gnu/jemalloc/include/jemalloc/jemalloc.h:327:26: note: expanded from macro 'posix_memalign'
[21:09:34]
[Compile C dependencies] #  define posix_memalign je_posix_memalign
[21:09:34]
[Compile C dependencies]                          ^
[21:09:34]
[Compile C dependencies] /go/native/x86_64-pc-linux-gnu/jemalloc/include/jemalloc/jemalloc.h:63:29: note: expanded from macro 'je_posix_memalign'
[21:09:34]
[Compile C dependencies] #  define je_posix_memalign posix_memalign
[21:09:34]
[Compile C dependencies]                             ^
[21:09:34]
[Compile C dependencies] /go/native/x86_64-pc-linux-gnu/jemalloc/include/jemalloc/jemalloc.h:202:38: note: previous declaration is here
[21:09:34]
[Compile C dependencies] JEMALLOC_EXPORT int JEMALLOC_NOTHROW    je_posix_memalign(void **memptr,
[21:09:34]
[Compile C dependencies]                                         ^
[21:09:34]
[Compile C dependencies] /go/native/x86_64-pc-linux-gnu/jemalloc/include/jemalloc/jemalloc.h:63:29: note: expanded from macro 'je_posix_memalign'
[21:09:34]
[Compile C dependencies] #  define je_posix_memalign posix_memalign
[21:09:34]
[Compile C dependencies]                             ^
[21:09:34]
[Compile C dependencies] 1 error generated.
[21:09:34]
[Compile C dependencies] make[4]: *** [CMakeFiles/rocksdb.dir/util/jemalloc_nodump_allocator.cc.o] Error 1
```

**Comment by petermattis** [comment]
@ajkr Is this on Linux? Your PR builds fine on OS X, and all of the tests pass.

**Comment by petermattis** [comment]
I see the same failure as @ajkr when running `build/builder.sh make build`.

**Comment by petermattis** [comment]
The problem is coming from compilation of `jemalloc_nodump_allocator.cc` which was added between 5.17.2 and 6.1.2. Not sure why the failure is only happening on Linux. It is occurring deep within system/compiler headers.

**Comment by petermattis** [comment]
This patch fixes the problem, but it subtle that the ordering of the headers has an effect:

```diff
diff --git a/util/jemalloc_nodump_allocator.h b/util/jemalloc_nodump_allocator.h
index e93c12237..b7924495e 100644
--- a/util/jemalloc_nodump_allocator.h
+++ b/util/jemalloc_nodump_allocator.h
@@ -8,11 +8,11 @@
 #include <atomic>
 #include <vector>

-#include "port/jemalloc_helper.h"
 #include "port/port.h"
 #include "rocksdb/memory_allocator.h"
 #include "util/core_local.h"
 #include "util/thread_local.h"
+#include "port/jemalloc_helper.h"

 #if defined(ROCKSDB_JEMALLOC) && defined(ROCKSDB_PLATFORM_POSIX)
```

**Comment by ajkr** [comment]
Nice finding.

So looking at the preprocessed compilation files, this order of declarations does not work:

```
// /usr/include/stdlib.h
extern int posix_memalign (void **__memptr, size_t __alignment, size_t __size)
     throw () __attribute__ ((__nonnull__ (1))) ;

// /go/native/x86_64-pc-linux-gnu/jemalloc/include/jemalloc/jemalloc.h
__attribute__((visibility("default"))) int __attribute__((nothrow)) posix_memalign(void **memptr,
    size_t alignment, size_t size) throw() __attribute__((nonnull(1)));

// /usr/lib/llvm-3.8/bin/../lib/clang/3.8.0/include/mm_malloc.h
extern "C" int posix_memalign(void **__memptr, size_t __alignment, size_t __size);
```

While this order of declarations works:
```
// /usr/include/stdlib.h
extern int posix_memalign (void **__memptr, size_t __alignment, size_t __size)
     throw () __attribute__ ((__nonnull__ (1))) ;

// /usr/lib/llvm-3.8/bin/../lib/clang/3.8.0/include/mm_malloc.h
extern "C" int posix_memalign(void **__memptr, size_t __alignment, size_t __size);

// /go/native/x86_64-pc-linux-gnu/jemalloc/include/jemalloc/jemalloc.h
__attribute__((visibility("default"))) int __attribute__((nothrow)) posix_memalign(void **memptr,
    size_t alignment, size_t size) throw() __attribute__((nonnull(1)));
```

**Comment by ajkr** [comment]
Building jemalloc without `JEMALLOC_USE_CXX_THROW` and then building RocksDB w/ clang against that jemalloc also works. So I guess this is another consequence of https://github.com/jemalloc/jemalloc/issues/778.

**Comment by ajkr** [comment]
RFAL.

**Review by petermattis — APPROVED** [review]
LGTM. Builds on both Mac OS X and Linux. Tests pass on Mac OS X.

**Pull request merged**
