### PR TITLE
opt: improve partial index implication performance

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: cache atom constraints during partial index predicate implication

One of the most time consuming parts of proving that a query filter
implies a partial index predicate is building constraints for each atom.
The same atom and may be examined multiple times when determining
filter/predicate implication, causing the optimizer to build a
constraint set for the same atom multiple times.

This commit adds a cache for atom constraints. By caching the
constraint, we ensure that the constraint only has to be built once for
each atom.

The speed-up when caching atom constraints within
`FiltersImplyPredicate` is significant:

    name                                                         old time/op  new time/op  delta
    PredicateImplication/single-exact-match-16                   57.3ns ± 3%  53.8ns ± 1%   -6.04%  (p=0.008 n=5+5)
    PredicateImplication/single-inexact-match-16                 1.16µs ± 0%  1.46µs ± 1%  +25.77%  (p=0.008 n=5+5)
    PredicateImplication/range-inexact-match-16                  3.45µs ± 1%  3.40µs ± 1%     ~     (p=0.056 n=5+5)
    PredicateImplication/single-exact-match-extra-filters-16      307ns ± 2%   302ns ± 1%     ~     (p=0.286 n=5+5)
    PredicateImplication/single-inexact-match-extra-filters-16   5.16µs ± 1%  5.11µs ± 3%     ~     (p=0.151 n=5+5)
    PredicateImplication/multi-column-and-exact-match-16          699ns ± 1%   956ns ± 1%  +36.78%  (p=0.008 n=5+5)
    PredicateImplication/multi-column-and-inexact-match-16       3.46µs ± 0%  3.16µs ± 2%   -8.54%  (p=0.008 n=5+5)
    PredicateImplication/multi-column-or-exact-match-16          53.9ns ± 1%  53.3ns ± 0%   -0.97%  (p=0.016 n=5+5)
    PredicateImplication/multi-column-or-exact-match-reverse-16  2.60µs ± 1%  2.27µs ± 0%  -12.72%  (p=0.008 n=5+5)
    PredicateImplication/multi-column-or-inexact-match-16        4.81µs ± 1%  3.46µs ± 0%  -28.05%  (p=0.008 n=5+5)
    PredicateImplication/and-filters-do-not-imply-pred-16        5.74µs ± 0%  5.12µs ± 1%  -10.91%  (p=0.008 n=5+5)
    PredicateImplication/or-filters-do-not-imply-pred-16         2.35µs ± 2%  1.65µs ± 1%  -29.77%  (p=0.008 n=5+5)
    PredicateImplication/many-columns-exact-match10-16           18.0µs ± 4%   7.7µs ± 1%  -57.30%  (p=0.008 n=5+5)
    PredicateImplication/many-columns-inexact-match10-16         29.7µs ± 2%  18.1µs ± 0%  -39.31%  (p=0.008 n=5+5)
    PredicateImplication/many-columns-exact-match100-16          1.72ms ± 0%  0.39ms ± 0%  -77.19%  (p=0.008 n=5+5)
    PredicateImplication/many-columns-inexact-match100-16        2.09ms ± 1%  0.48ms ± 2%  -76.94%  (p=0.008 n=5+5)

Release note: None

#### opt: populate partialidx implicator constraint cache with FilterItem atoms

This commit populates the `partialidx.implicator` cache with constraints
that have already been generated for `FiltersItem`s that are atoms. This
prevents the implicator from having to re-build constraints for these
atoms.

    name                                                         old time/op  new time/op  delta
    PredicateImplication/single-exact-match-16                   53.8ns ± 1%  54.8ns ± 1%   +1.78%  (p=0.008 n=5+5)
    PredicateImplication/single-inexact-match-16                 1.46µs ± 1%  1.29µs ± 0%  -11.33%  (p=0.008 n=5+5)
    PredicateImplication/range-inexact-match-16                  3.40µs ± 1%  3.46µs ± 0%   +1.59%  (p=0.016 n=5+5)
    PredicateImplication/single-exact-match-extra-filters-16      302ns ± 1%   308ns ± 1%   +1.72%  (p=0.008 n=5+5)
    PredicateImplication/single-inexact-match-extra-filters-16   5.11µs ± 3%  4.63µs ± 1%   -9.42%  (p=0.008 n=5+5)
    PredicateImplication/multi-column-and-exact-match-16          956ns ± 1%   638ns ± 1%  -33.29%  (p=0.008 n=5+5)
    PredicateImplication/multi-column-and-inexact-match-16       3.16µs ± 2%  2.87µs ± 1%   -9.30%  (p=0.008 n=5+5)
    PredicateImplication/multi-column-or-exact-match-16          53.3ns ± 0%  54.7ns ± 0%   +2.62%  (p=0.008 n=5+5)
    PredicateImplication/multi-column-or-exact-match-reverse-16  2.27µs ± 0%  2.33µs ± 1%   +2.85%  (p=0.008 n=5+5)
    PredicateImplication/multi-column-or-inexact-match-16        3.46µs ± 0%  3.56µs ± 0%   +2.69%  (p=0.008 n=5+5)
    PredicateImplication/and-filters-do-not-imply-pred-16        5.12µs ± 1%  4.16µs ± 1%  -18.77%  (p=0.008 n=5+5)
    PredicateImplication/or-filters-do-not-imply-pred-16         1.65µs ± 1%  1.68µs ± 0%   +2.12%  (p=0.008 n=5+5)
    PredicateImplication/many-columns-exact-match10-16           7.70µs ± 1%  6.16µs ± 1%  -20.08%  (p=0.008 n=5+5)
    PredicateImplication/many-columns-inexact-match10-16         18.1µs ± 0%  16.0µs ± 4%  -11.41%  (p=0.008 n=5+5)
    PredicateImplication/many-columns-exact-match100-16           393µs ± 0%   371µs ± 1%   -5.62%  (p=0.008 n=5+5)
    PredicateImplication/many-columns-inexact-match100-16         481µs ± 2%   434µs ± 1%   -9.73%  (p=0.008 n=5+5)

Release note: None

#### opt: make partialidx.Implicator a reuseable struct

This commit makes the private `implicator` struct public, allowing the
struct and its atom constraint cache to be reused for multiple calls to
`FiltersImplyPredicate`.

This commit also addes the `Implicator` as a field in the
`xform.CustomFuncs` struct. This allows any exploration rules that need
to prove query-filter/partial-index-predicate implication to use the
struct, and reuse the atom constraint cache within.

Reusing the cached constraints in successive calls to
`FiltersImplyPredicate` reduces the runtime of the function. The
benchmark has been updated to make 10 successive calls to
`FiltersImplyPredicate` before resetting the cache.

    name                                                         old time/op  new time/op  delta
    PredicateImplication/single-exact-match-16                   54.8ns ± 1%  60.3ns ± 1%  +10.04%  (p=0.008 n=5+5)
    PredicateImplication/single-inexact-match-16                 1.29µs ± 0%  0.88µs ± 1%  -31.87%  (p=0.008 n=5+5)
    PredicateImplication/range-inexact-match-16                  3.46µs ± 0%  2.33µs ± 0%  -32.58%  (p=0.008 n=5+5)
    PredicateImplication/single-exact-match-extra-filters-16      308ns ± 1%   313ns ± 2%   +1.63%  (p=0.048 n=5+5)
    PredicateImplication/single-inexact-match-extra-filters-16   4.63µs ± 1%  4.12µs ± 0%  -11.10%  (p=0.008 n=5+5)
    PredicateImplication/multi-column-and-exact-match-16          638ns ± 1%   472ns ± 0%  -26.02%  (p=0.016 n=5+4)
    PredicateImplication/multi-column-and-inexact-match-16       2.87µs ± 1%  1.96µs ± 0%  -31.58%  (p=0.008 n=5+5)
    PredicateImplication/multi-column-or-exact-match-16          54.7ns ± 0%  59.7ns ± 0%   +9.10%  (p=0.008 n=5+5)
    PredicateImplication/multi-column-or-exact-match-reverse-16  2.33µs ± 1%  1.73µs ± 2%  -25.85%  (p=0.008 n=5+5)
    PredicateImplication/multi-column-or-inexact-match-16        3.56µs ± 0%  2.18µs ± 0%  -38.65%  (p=0.008 n=5+5)
    PredicateImplication/and-filters-do-not-imply-pred-16        4.16µs ± 1%  3.68µs ± 1%  -11.58%  (p=0.008 n=5+5)
    PredicateImplication/or-filters-do-not-imply-pred-16         1.68µs ± 0%  0.77µs ± 0%  -54.24%  (p=0.008 n=5+5)
    PredicateImplication/many-columns-exact-match10-16           6.16µs ± 1%  5.08µs ± 2%  -17.51%  (p=0.008 n=5+5)
    PredicateImplication/many-columns-inexact-match10-16         16.0µs ± 4%  11.4µs ± 1%  -28.71%  (p=0.008 n=5+5)
    PredicateImplication/many-columns-exact-match100-16           371µs ± 1%   349µs ± 1%   -5.93%  (p=0.008 n=5+5)
    PredicateImplication/many-columns-inexact-match100-16         434µs ± 1%   376µs ± 1%  -13.32%  (p=0.008 n=5+5)

Release notes: None

#### partialidx: rename predicate.go to implicator.go

Now that `Implicator` is a public struct, its more fitting for the file
to be named `implicator.go`. This commit also updates the test file and
test data directory.

Release notes: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: nice speedups!

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50792#-:-MB58Q8s8kwPubYpWnZR:bu4wl3w)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/partialidx/predicate.go, line 427 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50792#-MB502jCBdb_9JsM-t8i:-MB502jCBdb_9JsM-t8j:b31o93h) ([raw file](https://github.com/cockroachdb/cockroach/blob/94528f71da6ade41cc6165bf4ec93d1fae49fcc1/pkg/sql/opt/partialidx/predicate.go#L427)):*
> ```Go
> }
> 
> // fetchConstraint returns a constraint set, tight boolean, and true the cache
> ```

true the cache -> true if the cache
___
*[pkg/sql/opt/partialidx/predicate.go, line 428 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50792#-MB507dA7P1McVwdoI2x:-MB507dB2zmIPKFytbiV:b-hxfr66) ([raw file](https://github.com/cockroachdb/cockroach/blob/94528f71da6ade41cc6165bf4ec93d1fae49fcc1/pkg/sql/opt/partialidx/predicate.go#L428)):*
> ```Go
> 
> // fetchConstraint returns a constraint set, tight boolean, and true the cache
> // contains and entry for the given scalar expression. It returns ok = false if
> ```

and entry -> an entry
___
*[pkg/sql/opt/partialidx/predicate.go, line 434 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50792#-MB5-gJpAVrsiE5BcP1q:-MB5-gJpAVrsiE5BcP1r:b1zugc5) ([raw file](https://github.com/cockroachdb/cockroach/blob/94528f71da6ade41cc6165bf4ec93d1fae49fcc1/pkg/sql/opt/partialidx/predicate.go#L434)):*
> ```Go
> 		return res.c, res.tight, true
> 	}
> 	return c, tight, false
> ```

better to just `return nil, false, false` here to make clear what's happening.
___
*[pkg/sql/opt/partialidx/predicate.go, line 169 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50792#-MB50N3jDPrvwnfJqCbD:-MB50N3jDPrvwnfJqCbE:b6hoby7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1995893f2086d9da2615f384ed9430090c522fb/pkg/sql/opt/partialidx/predicate.go#L169)):*
> ```Go
> 		op := f.Condition.Op()
> 		if f.ScalarProps().Constraints != nil && op != opt.AndOp && op != opt.OrOp && op != opt.RangeOp {
> 			// TODO: try not doing this if it already exists in the cache.
> ```

[nit] TODO(mgartner):

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50792)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/partialidx/predicate.go, line 427 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50792#-MB502jCBdb_9JsM-t8i:-MB5KPSHAtd7cVL-8fvY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/94528f71da6ade41cc6165bf4ec93d1fae49fcc1/pkg/sql/opt/partialidx/predicate.go#L427)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

true the cache -> true if the cache
</blockquote></details>

Done.
___
*[pkg/sql/opt/partialidx/predicate.go, line 428 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50792#-MB507dA7P1McVwdoI2x:-MB5KVNm2loZHYWzynBR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/94528f71da6ade41cc6165bf4ec93d1fae49fcc1/pkg/sql/opt/partialidx/predicate.go#L428)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

and entry -> an entry
</blockquote></details>

Done.
___
*[pkg/sql/opt/partialidx/predicate.go, line 434 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50792#-MB5-gJpAVrsiE5BcP1q:-MB5Kcyr8RuKzvrK5EXz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/94528f71da6ade41cc6165bf4ec93d1fae49fcc1/pkg/sql/opt/partialidx/predicate.go#L434)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

better to just `return nil, false, false` here to make clear what's happening.
</blockquote></details>

Done.
___
*[pkg/sql/opt/partialidx/predicate.go, line 169 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50792#-MB50N3jDPrvwnfJqCbD:-MB5NWvI3njZefaMpus5:b-1nke82) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1995893f2086d9da2615f384ed9430090c522fb/pkg/sql/opt/partialidx/predicate.go#L169)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] TODO(mgartner):
</blockquote></details>

I went ahead and updated `cacheConstraint` to only update the map if there was no entry. This seemed to have a marginal speed-up in some cases (3-5%).

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50792#-:-MB5j10SCJJmGUrxQa2R:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by RaduBerinde — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50792)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 43 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50792#-MB6FbTZ8XaKyXAxQaPP:-MB6FbTZ8XaKyXAxQaPQ:b-dteges) ([raw file](https://github.com/cockroachdb/cockroach/blob/21831d8f606ed63746480ddf08ba6f703eeeec84/pkg/sql/opt/xform/custom_funcs.go#L43)):*
> ```Go
> 	norm.CustomFuncs
> 	e  *explorer
> 	im *partialidx.Implicator
> ```

Where do we allocate this? (or is the `*` a typo)?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50792)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 43 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50792#-MB6FbTZ8XaKyXAxQaPP:-MB6YpZFAgqA8C_h5628:b-9vx7sg) ([raw file](https://github.com/cockroachdb/cockroach/blob/21831d8f606ed63746480ddf08ba6f703eeeec84/pkg/sql/opt/xform/custom_funcs.go#L43)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Where do we allocate this? (or is the `*` a typo)?
</blockquote></details>

Oops. Typo.

**Pull request merged**
