### PR TITLE
opt: Push hard row limit into Scan operator

### PR DESCRIPTION
**Pull request by andy-kimball**
This PR adds a HardLimit field to the ScanOpDef, as well as a new
PushLimitIntoScan rule that combines a Limit operator with an input
Scan operator if it has a constant limit value. This can substantially
reduce the cost of execution, as rows are never fetched to begin with,
rather than fetched only to be discarded by a Limit operator.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 32 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/sql/opt/memo/memo.go, line 437 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383#-L9091DPEZN618z_X1M-:-L9091DPEZN618z_X1M0:bywkrqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/07237f81a247f65c700308d104504c841fb93941/pkg/sql/opt/memo/memo.go#L437)):*
> ```Go
> 		case *ScanOpDef:
> 			m.formatScanPrivate(buf, t)
> 			if t.Constraint != nil {
> ```

[nit] I would keep this code together in `formatScanPrivate`. We can add a `short bool` argument to indicate if we want them or not.

Eventually we will probably want to plumb a flag that tells us if we're formatting things for an expression tree or a memo.

---

*[pkg/sql/opt/memo/private_defs_test.go, line 64 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383#-L90A1hn7jVFMzY6tVvi:-L90A1hn7jVFMzY6tVvj:b82krjn) ([raw file](https://github.com/cockroachdb/cockroach/blob/07237f81a247f65c700308d104504c841fb93941/pkg/sql/opt/memo/private_defs_test.go#L64)):*
> ```Go
> 	md := opt.NewMetadata()
> 	a := md.AddTable(cat.Table("a"))
> 	altIndex1 := 1
> ```

[nit] would be good to add a comment here and below with the index definition (`INDEX (i, k)`)

---

*[pkg/sql/opt/memo/private_defs_test.go, line 84 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383#-L90AIuq-99usEVz4LJu:-L90AIuq-99usEVz4LJv:b-ydw999) ([raw file](https://github.com/cockroachdb/cockroach/blob/07237f81a247f65c700308d104504c841fb93941/pkg/sql/opt/memo/private_defs_test.go#L84)):*
> ```Go
> 
> 	// Index is longer than ordering.
> 	def = &memo.ScanOpDef{Table: a, Index: altIndex1}
> ```

why are we setting def again to the same thing here?

---

*[pkg/sql/opt/memo/private_defs_test.go, line 94 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383#-L90AT9b8KBWOd-mlZXp:-L90AT9b8KBWOd-mlZXq:b-2guby3) ([raw file](https://github.com/cockroachdb/cockroach/blob/07237f81a247f65c700308d104504c841fb93941/pkg/sql/opt/memo/private_defs_test.go#L94)):*
> ```Go
> 
> 	// Index contains storing column.
> 	def = &memo.ScanOpDef{Table: a, Index: altIndex2}
> ```

same here

---

*[pkg/sql/opt/xform/explorer.go, line 347 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383#-L90B9-s8tkNUs-Ik8e6:-L90B9-s8tkNUs-Ik8e7:bxhvsgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/07237f81a247f65c700308d104504c841fb93941/pkg/sql/opt/xform/explorer.go#L347)):*
> ```Go
> 	scanOpDef := e.mem.LookupPrivate(def).(*memo.ScanOpDef)
> 	limitVal := int64(*e.mem.LookupPrivate(limit).(*tree.DInt))
> 	return e.mem.InternScanOpDef(&memo.ScanOpDef{
> ```

[nit] it would be less fragile to do `defCopy := *scanOpDef; defCopy.HardLimit = limitVal; intern(&defCopy)` (in case other fields get added)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383#-:-L90CD5T1ptsStNsLgMr:bnfp4nl)*

**Comment by andy-kimball** [comment]
Review status: 0 of 32 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/memo/memo.go, line 437 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383#-L9091DPEZN618z_X1M-:-L91e7kg1mS4O-LR8B3-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/07237f81a247f65c700308d104504c841fb93941/pkg/sql/opt/memo/memo.go#L437)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I would keep this code together in `formatScanPrivate`. We can add a `short bool` argument to indicate if we want them or not.

Eventually we will probably want to plumb a flag that tells us if we're formatting things for an expression tree or a memo.
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/private_defs_test.go, line 64 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383#-L90A1hn7jVFMzY6tVvi:-L91eUYm66aUrByf8uzL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/07237f81a247f65c700308d104504c841fb93941/pkg/sql/opt/memo/private_defs_test.go#L64)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] would be good to add a comment here and below with the index definition (`INDEX (i, k)`)
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/private_defs_test.go, line 84 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383#-L90AIuq-99usEVz4LJu:-L91ecpX-DQym2P3Q-qH:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/07237f81a247f65c700308d104504c841fb93941/pkg/sql/opt/memo/private_defs_test.go#L84)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

why are we setting def again to the same thing here?
</blockquote></details>

Removed.

---

*[pkg/sql/opt/memo/private_defs_test.go, line 94 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383#-L90AT9b8KBWOd-mlZXp:-L91edl76H-958-F5Mk_:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/07237f81a247f65c700308d104504c841fb93941/pkg/sql/opt/memo/private_defs_test.go#L94)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

same here
</blockquote></details>

Removed.

---

*[pkg/sql/opt/xform/explorer.go, line 347 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383#-L90B9-s8tkNUs-Ik8e6:-L91f7TFCoat71DCawSd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/07237f81a247f65c700308d104504c841fb93941/pkg/sql/opt/xform/explorer.go#L347)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] it would be less fragile to do `defCopy := *scanOpDef; defCopy.HardLimit = limitVal; intern(&defCopy)` (in case other fields get added)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383)*

**Comment by RaduBerinde** [comment]
Reviewed 28 of 32 files at r1, 4 of 4 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 28 of 32 files at r1, 4 of 4 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/sql/opt/memo/expr_view.go, line 246 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383#-L95CuSWDieK2yjRLT4J:-L95CuSWDieK2yjRLT4K:bx97gvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/be252326d0d7cec18768353d5309c3e51bb1b23c/pkg/sql/opt/memo/expr_view.go#L246)):*
> ```Go
> 	switch ev.Operator() {
> 	case opt.ScanOp:
> 		ev.mem.formatScanPrivate(&buf, ev.Private().(*ScanOpDef), true /* short */)
> ```

Why not use one of the fmt flags instead of a "short" bool?

---

*[pkg/sql/opt/memo/logical_props_factory.go, line 284 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383#-L95DVEp67BV6yBrq9Jr:-L95DVEp67BV6yBrq9Js:b-yh756g) ([raw file](https://github.com/cockroachdb/cockroach/blob/be252326d0d7cec18768353d5309c3e51bb1b23c/pkg/sql/opt/memo/logical_props_factory.go#L284)):*
> ```Go
> 	if limit.Operator() == opt.ConstOp {
> 		hardLimit := *limit.Private().(*tree.DInt)
> 		if hardLimit > 0 {
> ```

shouldn't you also check if `hardLimit < props.Relational.Stats.RowCount`?

---

*[pkg/sql/opt/memo/private_storage.go, line 179 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383#-L95FUTWBDG7FlTqPyb7:-L95FUTWBDG7FlTqPyb8:boi656f) ([raw file](https://github.com/cockroachdb/cockroach/blob/be252326d0d7cec18768353d5309c3e51bb1b23c/pkg/sql/opt/memo/private_storage.go#L179)):*
> ```Go
> 	// generated multiple times.
> 	ps.keyBuf.writeUvarint(uint64(uintptr(unsafe.Pointer(def.Constraint))))
> 	ps.keyBuf.writeVarint(def.HardLimit)
> ```

shouldn't the hard limit be unsigned? (writeUvarint)?

---

*[pkg/sql/opt/memo/testdata/logprops/limit, line 45 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383#-L95GFsl9qKqyQEghNvq:-L95GFsl9qKqyQEghNvr:b-cjvcc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/be252326d0d7cec18768353d5309c3e51bb1b23c/pkg/sql/opt/memo/testdata/logprops/limit#L45)):*
> ```
> 
> build
> SELECT * FROM a LIMIT 0
> ```

how will we handle this query? we need some way to distinguish between 0 and "unknown"

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383#-:-L95Im3H9WrTb20gUcWi:bnfp4nl)*

**Comment by rytaft** [comment]
*[pkg/sql/opt/memo/expr_view.go, line 246 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383#-L95CuSWDieK2yjRLT4J:-L95JQqMAEr5vYt7cHnQ:b-tut9qu) ([raw file](https://github.com/cockroachdb/cockroach/blob/be252326d0d7cec18768353d5309c3e51bb1b23c/pkg/sql/opt/memo/expr_view.go#L246)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why not use one of the fmt flags instead of a "short" bool?
</blockquote></details>

Just realized Radu suggested adding this now and using a flag in the future. Feel free to save the flag for a future PR... (maybe add a TODO for now)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/memo/expr_view.go, line 246 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383#-L95CuSWDieK2yjRLT4J:-L95b95m7Ss7FfhDocqz:b-cs5e3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/be252326d0d7cec18768353d5309c3e51bb1b23c/pkg/sql/opt/memo/expr_view.go#L246)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Just realized Radu suggested adding this now and using a flag in the future. Feel free to save the flag for a future PR... (maybe add a TODO for now)
</blockquote></details>

I doubt it will ever get more complex than a boolean, so I'm not too motivated to use a flag. I can add a comment if I end up needing to re-run all the tests.

---

*[pkg/sql/opt/memo/logical_props_factory.go, line 284 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383#-L95DVEp67BV6yBrq9Jr:-L95_xmL2_2lNsAJef1O:b-wl7bi8) ([raw file](https://github.com/cockroachdb/cockroach/blob/be252326d0d7cec18768353d5309c3e51bb1b23c/pkg/sql/opt/memo/logical_props_factory.go#L284)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

shouldn't you also check if `hardLimit < props.Relational.Stats.RowCount`?
</blockquote></details>

Not necessarily, because `RowCount` is just an estimate, and may be inaccurate. I think a number provided by the user is likely to be more accurate. Anyway, the current code is just placeholder code, so we can always change later based on how the stats end up working.

---

*[pkg/sql/opt/memo/private_storage.go, line 179 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383#-L95FUTWBDG7FlTqPyb7:-L95aGSX5_QKUvPJ5eFP:bvbcxke) ([raw file](https://github.com/cockroachdb/cockroach/blob/be252326d0d7cec18768353d5309c3e51bb1b23c/pkg/sql/opt/memo/private_storage.go#L179)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

shouldn't the hard limit be unsigned? (writeUvarint)?
</blockquote></details>

It's `int64` in 2.0, so I stuck with that.

---

*[pkg/sql/opt/memo/testdata/logprops/limit, line 45 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383#-L95GFsl9qKqyQEghNvq:-L95aNam8h9n6-7jCQiM:b-s5g4ne) ([raw file](https://github.com/cockroachdb/cockroach/blob/be252326d0d7cec18768353d5309c3e51bb1b23c/pkg/sql/opt/memo/testdata/logprops/limit#L45)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

how will we handle this query? we need some way to distinguish between 0 and "unknown"
</blockquote></details>

We don't push down `LIMIT = 0`, so there's no ambiguity. The execution code does not allow pushdown of limit=0, which is why I check whether limit>0 elsewhere. If Limit=0 in the ScanOpDef, it means "no limit". If Limit=0 in the Limit operator, it means max zero rows. This is how it works in 2.0 as far as I can tell, so I stuck with that, since it's not a particularly important case. Also, if we decide to handle 0, we should just replace the entire query with a zero-row Values operator.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383)*

**Comment by rytaft** [comment]
*[pkg/sql/opt/memo/testdata/logprops/limit, line 45 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383#-L95GFsl9qKqyQEghNvq:-L95lOIeAzZhsf-PmBWB:b5vjmdl) ([raw file](https://github.com/cockroachdb/cockroach/blob/be252326d0d7cec18768353d5309c3e51bb1b23c/pkg/sql/opt/memo/testdata/logprops/limit#L45)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

We don't push down `LIMIT = 0`, so there's no ambiguity. The execution code does not allow pushdown of limit=0, which is why I check whether limit>0 elsewhere. If Limit=0 in the ScanOpDef, it means "no limit". If Limit=0 in the Limit operator, it means max zero rows. This is how it works in 2.0 as far as I can tell, so I stuck with that, since it's not a particularly important case. Also, if we decide to handle 0, we should just replace the entire query with a zero-row Values operator.
</blockquote></details>

Got it - thanks!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/memo/testdata/logprops/limit, line 45 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383#-L95GFsl9qKqyQEghNvq:-L95ly7u0hd6MAa3M29C:b-ccvhas) ([raw file](https://github.com/cockroachdb/cockroach/blob/be252326d0d7cec18768353d5309c3e51bb1b23c/pkg/sql/opt/memo/testdata/logprops/limit#L45)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Got it - thanks!
</blockquote></details>

A zero-row operator would be useful in other cases too - a constrained scan with a contradiction constraint, or more generally a select where the filter constraints indicate a contradiction.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24383)*

**Pull request merged**
