### PR TITLE
roachtest: Use encryption-at-rest in some random clearrange runs

### PR DESCRIPTION
**Pull request by itsbilal**
Currently, we always run the `clearrange/*` roachtests with
encryption-at-rest disabled. It's valuable to sometimes
run it with encryption-at-rest enabled, as that could surface
bugs in that functionality. A recent bug in pebble
would have been uncovered earlier if we were running this
roachtest with encryption enabled.

This change updates the clearrange roachtest to use encryption
on some runs.

Release note: None.

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
This was simpler than I was expecting.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57086#-:-MMzu6X809-M2mX637gQ:b-gletlu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/cmd/roachtest/clearrange.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57086#-MMzu0bK14-VDhrCqaSZ:-MMzu0bL1Up2HMnpWXof:b-18esff) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada4a296dc20240b0e78f7ba5173fcd6957369b7/pkg/cmd/roachtest/clearrange.go#L49)):*
> ```Go
> 	if rng.Intn(2) == 1 {
> 		c.l.Printf("starting with encryption at rest enabled")
> 		c.Start(ctx, t, startArgs("--encrypt"))
> ```

Should we pass in `--encrypt` to all the invocations of `Start`?

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57086#-:-MMzv8MGEsj218sadlB9:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

**Review by itsbilal — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57086#-:-MN-K3qV28vA0YD3xnpD:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

___
*[pkg/cmd/roachtest/clearrange.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57086#-MMzu0bK14-VDhrCqaSZ:-MN-HoplBPqdSIhOoqWz:b-e292sl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada4a296dc20240b0e78f7ba5173fcd6957369b7/pkg/cmd/roachtest/clearrange.go#L49)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Should we pass in `--encrypt` to all the invocations of `Start`?
</blockquote></details>

Like across all roachtests, or non-randomly? I think it's still a better idea to randomize, as you can dive into hosed store directories if it's a non-encrypted case. And for the performance-critical ones it might be a bad idea to do it randomly or at all. Sorry if I misunderstood your suggestion.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57086)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal)

___
*[pkg/cmd/roachtest/clearrange.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57086#-MMzu0bK14-VDhrCqaSZ:-MN-L289-hT0_t4X2FoX:bvzy30s) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada4a296dc20240b0e78f7ba5173fcd6957369b7/pkg/cmd/roachtest/clearrange.go#L49)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Like across all roachtests, or non-randomly? I think it's still a better idea to randomize, as you can dive into hosed store directories if it's a non-encrypted case. And for the performance-critical ones it might be a bad idea to do it randomly or at all. Sorry if I misunderstood your suggestion.
</blockquote></details>

I was just referring to the `Start` invocations below in the `if aggressiveChecks` block.

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57086)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

___
*[pkg/cmd/roachtest/clearrange.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57086#-MMzu0bK14-VDhrCqaSZ:-MN-MzC71tl1B38Bir9L:b-inl2az) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada4a296dc20240b0e78f7ba5173fcd6957369b7/pkg/cmd/roachtest/clearrange.go#L49)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I was just referring to the `Start` invocations below in the `if aggressiveChecks` block.
</blockquote></details>

Oh, right. Oops. Fixed.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57086#-:-MN-OEu08voUVBDQUZdl:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal)

___
*[pkg/cmd/roachtest/clearrange.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57086#-MN-O4Fh-QllpNvX6z_9:-MN-O4Fh-QllpNvX6z_A:b-k0yy3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba02711970271a08a2e64c13cfe654ca9783fd1e/pkg/cmd/roachtest/clearrange.go#L47)):*
> ```Go
> 	// Randomize starting with encryption-at-rest enabled.
> 	rng := rand.New(rand.NewSource(timeutil.Now().UnixNano()))
> 	opts := make([]option, 0)
> ```

Nit: this can be written as `var opts []option`. The `make` style actually allocates a zero-length slice.

**Comment by itsbilal** [comment]
TFTR! Made that little fix.

bors r+

**Pull request merged**
