### PR TITLE
roachtest: add some new tests to hibernate blacklist

### PR DESCRIPTION
**Pull request by jordanlewis**
These tests got added in a recent version of hibernate.

Release note: None

### CODE REVIEW

**Comment by BramGruneir** [comment]
What changed?  Why were these tests not in the blacklist before?

**Comment by jordanlewis** [comment]
@BramGruneir the tests were recently added to the Hibernate test suite and weren't even in the software before!

**Review by BramGruneir — APPROVED** [review]
Excellent.  Please add the fact that a new version of hibernate was released as part of the commit message and then :lgtm:.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38298#-:-Lhl5po_5ZxnkYpOpV3V:b-r7c1s7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @BramGruneir)

**Comment by jordanlewis** [comment]
TFTR!

bors r+

**Pull request merged**
