### PR TITLE
physicalplan: add support for multi-stage execution of var_pop and stddev_pop

### PR DESCRIPTION
**Pull request by mneverov**
physicalplan: add support for multi-stage execution of var_pop and stddev_pop.

See #58347.

Release note (performance improvement): var_pop and stddev_pop aggregate
functions are now evaluated more efficiently in a distributed setting.

### CODE REVIEW

**Review by mneverov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73712)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/73712#-MqzK-t12wI6kJkjDu0b:-MqzK-t12wI6kJkjDu0c:b-50ttqx) (no related file):*
@yuzefovich I think this can be merged before #73062.

---
___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal, line 644 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73712#-MqzJeOm9k8i2OKCrktA:-MqzJeOm9k8i2OKCrktB:b-770p6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d3bd6d2e23ca0137b8b4b25fb2e960d451553a4/pkg/sql/logictest/testdata/logic_test/crdb_internal#L644)):*
> ```
> /Table/62/2/1  /Table/62/2/2
> /Table/62/2/2  /Table/62/2/3
> /Table/62/2/3  /Table/62/3/1
> ```

This (as well as two above) was added after I rebased master branch and rerun testlogic with rewrite flag.

**Comment by yuzefovich** [comment]
Apologies for the delay, I'll take a look early next week.

**Review by yuzefovich — APPROVED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73712)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mneverov and @RichardJCai)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/73712#-MqzK-t12wI6kJkjDu0b:-MrO5g2R4wD0NP13Ovj8:bgaarua) (no related file):*
<details><summary><i>Previously, mneverov (Max Neverov) wrote…</i></summary><blockquote>

@yuzefovich I think this can be merged before #73062.
</blockquote></details>

Thanks for working on this! :lgtm:

---
___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73712#-MrO-kz8ADBVo88IhYoW):*
nit: `s/function is/functions are/`.
___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal, line 644 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73712#-MqzJeOm9k8i2OKCrktA:-MrO4lNaDYIp2D38P5ys:bpqd8ka) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d3bd6d2e23ca0137b8b4b25fb2e960d451553a4/pkg/sql/logictest/testdata/logic_test/crdb_internal#L644)):*
<details><summary><i>Previously, mneverov (Max Neverov) wrote…</i></summary><blockquote>

This (as well as two above) was added after I rebased master branch and rerun testlogic with rewrite flag.
</blockquote></details>

I've already seen this diff on another PR where `rewrite` flag was used although the PR in question didn't modify anything related. I'm guessing it's because of the `retry` option - we expect the output to be what you added here on the first try (and this is what's written down with `rewrite` flag), but on consequent tries we get the output without this new stuff. I'd revert the changes in this file, and I think CI will still pass.

@richardjcai can you confirm what is the expected output for this logic test?

**Review by yuzefovich — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73712)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mneverov and @RichardJCai)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/73712#-MqzK-t12wI6kJkjDu0b:-MrOzHtoEmYHU3TRCWCE:b-5br0rs) (no related file):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Thanks for working on this! :lgtm:
</blockquote></details>

Thanks for your contribution!

bors r=yuzefovich

---

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73712)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mneverov and @RichardJCai)

___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal, line 644 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73712#-MqzJeOm9k8i2OKCrktA:-MrP-Mzv64UlbHOscovw:b-ona2kf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d3bd6d2e23ca0137b8b4b25fb2e960d451553a4/pkg/sql/logictest/testdata/logic_test/crdb_internal#L644)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I've already seen this diff on another PR where `rewrite` flag was used although the PR in question didn't modify anything related. I'm guessing it's because of the `retry` option - we expect the output to be what you added here on the first try (and this is what's written down with `rewrite` flag), but on consequent tries we get the output without this new stuff. I'd revert the changes in this file, and I think CI will still pass.

@richardjcai can you confirm what is the expected output for this logic test?
</blockquote></details>

Filed #74107 to track this.

**Pull request merged**
