### PR TITLE
server/license: Enable the License Enforcer

### PR DESCRIPTION
**Pull request by spilchen**
Previously, the license enforcer was disabled by default, and only certain test cases specifically written for it were enabled. This change activates the license enforcer across the board and removes the ability to disable it.

With the deprecation of the core license, there’s no longer a need to check whether enterprise features are enabled—all features are now always enabled. If a license policy violation occurs, such as an expired license, we will throttle connections, but all enterprise features will remain functional. I’ve left the API for checking if enterprise features are enabled in the code, but these functions are now no-ops and can be removed in the future.

I also had to adjust some tests that were explicitly disabling enterprise features, as that’s no longer possible. Some tests were rewritten to fit the new model, while others were removed entirely because they were no longer relevant.

This change will be backported to versions 24.2, 24.1, 23.2, and 23.1.

Epic: CRDB-39988
Closes: CRDB-41758
Closes: CRDB-41998
Release note: none

### CODE REVIEW

**Review by angles-n-daemons — CHANGES_REQUESTED** [review]
nice, this model seems a lot simpler - added a couple questions but looks good overall

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131821#-:-O8N3c6L-dM1GA3rmupU:b-8tky8y)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andyyang890, @kev-cao, and @spilchen)

___
*[`pkg/ccl/utilccl/license_check.go` line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131821#-O8N3AAZ8a9R5W1ncA7R:-O8N3AAZ8a9R5W1ncA7S:bd41jwo) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac0b244cd463f1b2fb1a8cd858eeb1506db84579/pkg/ccl/utilccl/license_check.go#L140)):*
> ```Go
> // should be replaced once it is possible to read the host cluster's
> // enterprise.license setting.
> func ApplyTenantLicense() error {
> ```

qq, how will tenant licenses be verified in the new model?
___
*[`pkg/server/license/enforcer.go` line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131821#-O8N-yx16Fk_CBOUUeFw:-O8N-yx16Fk_CBOUUeFx:b44uc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac0b244cd463f1b2fb1a8cd858eeb1506db84579/pkg/server/license/enforcer.go#L100)):*
> ```Go
> 	// rollout of these changes. It will be removed or changed to opt-out as we near
> 	// the final stages of the CockroachDB core licensing deprecation.
> 	// TODO(spilchen): Update or remove this knob closer to the completion of the
> ```

🎉
___
*[`pkg/ccl/backupccl/create_scheduled_backup_test.go` line 401 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131821#-O8N1REG8Tg860GA9Qg5:-O8N1REG8Tg860GA9Qg6:b-2my51z) ([raw file](https://github.com/cockroachdb/cockroach/blob/5357ca77125cceb7464e0a465ca34837db903e07/pkg/ccl/backupccl/create_scheduled_backup_test.go#L401)):*
> ```Go
> 					backupStmt:                    "BACKUP INTO 'nodelocal://1/backup?AWS_SECRET_ACCESS_KEY=neverappears' WITH OPTIONS (detached)",
> 					shownStmt:                     "BACKUP INTO 'nodelocal://1/backup?AWS_SECRET_ACCESS_KEY=redacted' WITH OPTIONS (detached)",
> 					period:                        24 * time.Hour,
> ```

out of curiosity, why did this change?
___
*[`pkg/ccl/partitionccl/partition_test.go` line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131821#-O8N1jyD-SUgkewi34Zh:-O8N1jyD-SUgkewi34Zi:b9s3k8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac0b244cd463f1b2fb1a8cd858eeb1506db84579/pkg/ccl/partitionccl/partition_test.go#L59)):*
> ```Go
> 	const partitionErr = "use of partitions requires an enterprise license"
> 	const zoneErr = "use of replication zones on indexes or partitions requires an enterprise license"
> 	expectErr := func(q string, expErr string) {
> ```

I like these tests, would it be possible to rename this test to `TestRemovePartitioning` and change this func from `expectErr(q string, err string) -> expectNoErr(q string)`

**Review by spilchen — COMMENTED** [review]
@angles-n-daemons Thanks for reviewing! There are a number of additional changes needed to get the tests passing that I hadn’t anticipated. Rather than overloading this PR, I’m planning to split them into separate PRs. I’ll make sure to address your comments in the new ones. Thanks again!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131821#-:-O8NElWeB5xoCmvV_OOx:b-1c7clh)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andyyang890, @angles-n-daemons, and @kev-cao)

___
*[`pkg/ccl/utilccl/license_check.go` line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131821#-O8N3AAZ8a9R5W1ncA7R:-O8NE1wP47E0bDx-Zsik:b2k9z2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac0b244cd463f1b2fb1a8cd858eeb1506db84579/pkg/ccl/utilccl/license_check.go#L140)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

qq, how will tenant licenses be verified in the new model?
</blockquote></details>

I’m not sure what’s meant by "tenant licenses" here. Currently, there’s a single license configuration that applies across all tenants. This might not have been the case before, which is probably what the comment is referring to. However, all this function did was enable enterprise features, which is no longer necessary since those features are now always enabled.
___
*[`pkg/ccl/backupccl/create_scheduled_backup_test.go` line 401 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131821#-O8N1REG8Tg860GA9Qg5:-O8NCOqx233VIR7fhkv4:b-i4fmxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5357ca77125cceb7464e0a465ca34837db903e07/pkg/ccl/backupccl/create_scheduled_backup_test.go#L401)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

out of curiosity, why did this change?
</blockquote></details>

Previously, certain backup features (e.g., incremental backups) required an enterprise license to function. With the deprecation of the core license, these checks have been removed. Now, all backup features are available regardless of the installed license. This change simply reflects the functionality that is now supported.
___
*[`pkg/ccl/partitionccl/partition_test.go` line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131821#-O8N1jyD-SUgkewi34Zh:-O8NDKbj8rNdB0AvYxyT:b-7jwfty) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac0b244cd463f1b2fb1a8cd858eeb1506db84579/pkg/ccl/partitionccl/partition_test.go#L59)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

I like these tests, would it be possible to rename this test to `TestRemovePartitioning` and change this func from `expectErr(q string, err string) -> expectNoErr(q string)`
</blockquote></details>

There are additional changes needed if we want to verify that these features are now functioning correctly. Some of the SQL statements that were previously expected to fail (e.g., the entire "Once removed, they cannot be added back" block) would no longer be valid. I removed the entire test initially because it didn’t seem to add much value, but I can look into salvaging parts of it.

**Comment by spilchen** [comment]
Closing this PR. I’m planning to split it into two, as I expect more changes will be necessary. One PR will enable the license enforcer, and the other will make the enterprise checks no-ops.

**Comment by spilchen** [comment]
Here are the two PRs that were split from this:
- #131944 
- #131943

**Pull request closed without merging**
