### PR TITLE
opt: Improve list and optbuilder perf

### PR DESCRIPTION
**Pull request by andy-kimball**
- Improve perf of list storage
- Improve perf of USING and natural joins

Together, the changes give a perf boost for this case:
```
SELECT * FROM foo NATURAL JOIN bar

name                 old time/op    new time/op    delta
Phases/test/Explore     115µs ± 2%     109µs ± 1%  -4.63%  (p=0.008 n=5+5)

name                 old alloc/op   new alloc/op   delta
Phases/test/Explore    44.3kB ± 0%    42.6kB ± 0%  -3.76%  (p=0.008 n=5+5)

name                 old allocs/op  new allocs/op  delta
Phases/test/Explore       189 ± 0%       181 ± 0%  -4.23%  (p=0.008 n=5+5)
```

### CODE REVIEW

**Review by rytaft — CHANGES_REQUESTED** [review]
Nice improvements!

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29472#-:-LLZk9hADnaAHbdwBs7w:b-kzhh6i)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/list_storage.go, line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29472#-LLZaD3cDkT5EWu3gYSn:-LLZaD3cDkT5EWu3gYSo:bmpsxqu) ([raw file](https://github.com/cockroachdb/cockroach/blob/68ceb342a8715fb9866fe8e194d692a26ffcd782/pkg/sql/opt/memo/list_storage.go#L92)):*
> ```Go
> type prefixID uint32
> 
> const minStorageCap = 16
> ```

What is this used for?
___
*[pkg/sql/opt/memo/list_storage.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29472#-LLZWZQyEzt2NLQjZNka:-LLZWZQyEzt2NLQjZNkb:b-7h7ier) ([raw file](https://github.com/cockroachdb/cockroach/blob/68ceb342a8715fb9866fe8e194d692a26ffcd782/pkg/sql/opt/memo/list_storage.go#L106)):*
> ```Go
> // listStorageVal stores the offset of this node's list in the "lists" slice.
> // The offset is 1-based, so to index into the slice, first subtract one from
> // this value (0 is reserved to mean "undefined" list). listStorageValue also
> ```

[nit] listStorageValue -> listStorageVal
___
*[pkg/sql/opt/memo/list_storage.go, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29472#-LLZ_0x_CTnSIWxu2ZHw:-LLZ_0x_CTnSIWxu2ZHx:bi3wudu) ([raw file](https://github.com/cockroachdb/cockroach/blob/68ceb342a8715fb9866fe8e194d692a26ffcd782/pkg/sql/opt/memo/list_storage.go#L109)):*
> ```Go
> // stores a unique prefix identifier, which can be used to look up lists that
> // are one greater in length, and that have this list as a prefix.
> type listStorageVal struct {
> ```

This is a bit confusing. It took me a while to understand that for a given <key, value> pair, the `prefix` field in the value is one larger than the `prefix` field in the key.  It would help to make this explicit, and also add some commentary about why this is better than just storing the offset. You alluded to it above, but I think this is tricky and deserves a bit more...
___
*[pkg/sql/opt/optbuilder/join.go, line 144 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29472#-LLZbqZ_BG1CuZf4nakh:-LLZbqZaAQePHsSbdqun:b-gohaag) ([raw file](https://github.com/cockroachdb/cockroach/blob/45b351e00c8f455a509f17548e5314493d469737/pkg/sql/opt/optbuilder/join.go#L144)):*
> ```Go
> 	joinType sqlbase.JoinType, left, right, filter memo.GroupID,
> ) memo.GroupID {
> 	// Wrap the ON condition in a FiltersOp.
> ```

This comment is out of place
___
*[pkg/sql/opt/optbuilder/join.go, line 330 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29472#-LLZhB00DCMHcCyLu0iC:-LLZhB00DCMHcCyLu0iD:b-f6pjfd) ([raw file](https://github.com/cockroachdb/cockroach/blob/45b351e00c8f455a509f17548e5314493d469737/pkg/sql/opt/optbuilder/join.go#L330)):*
> ```Go
> // one of the following actions:
> // (1) If the column is part of the hideCols set, then it is a join column that
> //     needs to be added to output scope.
> ```

also mention that it needs to have `hidden` set to true
___
*[pkg/sql/opt/optbuilder/join.go, line 358 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29472#-LLZd3I6BMGUrnZD8GIt:-LLZd3I6BMGUrnZD8GIu:badfe57) ([raw file](https://github.com/cockroachdb/cockroach/blob/45b351e00c8f455a509f17548e5314493d469737/pkg/sql/opt/optbuilder/join.go#L358)):*
> ```Go
> 		if !col.hidden && col.name == name {
> 			if foundCol != nil {
> 				jb.raiseDuplicateColError(name)
> ```

The error message in `raiseDuplicateColError` seems like it is intended for the case when there are multiple identical columns in the USING clause (e.g., `USING (x, x, y)`). It seems like this would catch a different error: when a table has two identical columns (I don't think that error should ever happen -- it should be checked elsewhere).

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29472)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/list_storage.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29472#-LLZqApm6orPfkfon9cN:-LLZqApm6orPfkfon9cO:b-dcbn5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/68ceb342a8715fb9866fe8e194d692a26ffcd782/pkg/sql/opt/memo/list_storage.go#L90)):*
> ```Go
> }
> 
> type prefixID uint32
> ```

This could use a comment. Also, another name for this to consider is `nodeID` because it identifies a node in the prefix tree. Then the key would have a "prefix nodeID" and the value would have a "node nodeID".
___
*[pkg/sql/opt/memo/list_storage.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29472#-LLZpihuC32Ojw48gJqP:-LLZpihuC32Ojw48gJqQ:b-izisq0) ([raw file](https://github.com/cockroachdb/cockroach/blob/68ceb342a8715fb9866fe8e194d692a26ffcd782/pkg/sql/opt/memo/list_storage.go#L95)):*
> ```Go
> 
> // listStorageKey is the path to a node in the prefix tree. The path is a
> // (prefix, item) pair, where prefix uniquely identifies the list of edges from
> ```

[nit] I would move the description of each field above the field (same below)
___
*[pkg/sql/opt/memo/list_storage.go, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29472#-LLZ_0x_CTnSIWxu2ZHw:-LLZprpb1wwTBWR9NUH3:b-um0owt) ([raw file](https://github.com/cockroachdb/cockroach/blob/68ceb342a8715fb9866fe8e194d692a26ffcd782/pkg/sql/opt/memo/list_storage.go#L109)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This is a bit confusing. It took me a while to understand that for a given <key, value> pair, the `prefix` field in the value is one larger than the `prefix` field in the key.  It would help to make this explicit, and also add some commentary about why this is better than just storing the offset. You alluded to it above, but I think this is tricky and deserves a bit more...
</blockquote></details>

Same here. I was going to suggest to not name this field `prefix` (since the type already shows it's a prefix id), maybe just `id`

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29472)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/list_storage.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29472#-LLZqApm6orPfkfon9cN:-LLcFgIn-oP8fSO8OFzW:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/68ceb342a8715fb9866fe8e194d692a26ffcd782/pkg/sql/opt/memo/list_storage.go#L90)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This could use a comment. Also, another name for this to consider is `nodeID` because it identifies a node in the prefix tree. Then the key would have a "prefix nodeID" and the value would have a "node nodeID".
</blockquote></details>

Good idea. Done.
___
*[pkg/sql/opt/memo/list_storage.go, line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29472#-LLZaD3cDkT5EWu3gYSn:-LLcFiRTC3PcNkaYSQsu:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/68ceb342a8715fb9866fe8e194d692a26ffcd782/pkg/sql/opt/memo/list_storage.go#L92)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

What is this used for?
</blockquote></details>

Removed.
___
*[pkg/sql/opt/memo/list_storage.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29472#-LLZWZQyEzt2NLQjZNka:-LLcNtXN0vEijyWZVBYO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/68ceb342a8715fb9866fe8e194d692a26ffcd782/pkg/sql/opt/memo/list_storage.go#L106)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] listStorageValue -> listStorageVal
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/list_storage.go, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29472#-LLZ_0x_CTnSIWxu2ZHw:-LLcNtsnAQ-UMWH8N0VV:bb9pbsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/68ceb342a8715fb9866fe8e194d692a26ffcd782/pkg/sql/opt/memo/list_storage.go#L109)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Same here. I was going to suggest to not name this field `prefix` (since the type already shows it's a prefix id), maybe just `id`
</blockquote></details>

I rewrote the comments.
___
*[pkg/sql/opt/optbuilder/join.go, line 144 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29472#-LLZbqZ_BG1CuZf4nakh:-LLcGf1L9-jrIu7DUcRq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/45b351e00c8f455a509f17548e5314493d469737/pkg/sql/opt/optbuilder/join.go#L144)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This comment is out of place
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/join.go, line 330 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29472#-LLZhB00DCMHcCyLu0iC:-LLcGrxUAKb6CuPGJVBN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/45b351e00c8f455a509f17548e5314493d469737/pkg/sql/opt/optbuilder/join.go#L330)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

also mention that it needs to have `hidden` set to true
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/join.go, line 358 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29472#-LLZd3I6BMGUrnZD8GIt:-LLcOeo3832F6VhqTe9b:bttzr4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/45b351e00c8f455a509f17548e5314493d469737/pkg/sql/opt/optbuilder/join.go#L358)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

The error message in `raiseDuplicateColError` seems like it is intended for the case when there are multiple identical columns in the USING clause (e.g., `USING (x, x, y)`). It seems like this would catch a different error: when a table has two identical columns (I don't think that error should ever happen -- it should be checked elsewhere).
</blockquote></details>

I was matching this behavior, which exists in both 2.0 and 2.1:
```
root@:26257/defaultdb> SELECT * FROM (SELECT x, x+1 AS x FROM onecolumn) AS a NATURAL JOIN onecolumn as b;
pq: column "x" appears more than once in USING clause
```
Postgres doesn't even allow this situation to happen; it doesn't allow duplicate column names even in constructed data sources. Not sure why Cockroach allows this.

I switched both `NATURAL JOIN` and `USING` cases to use this error instead:
```
duplicate column name: 'x'
```

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 1 of 3 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29472#-:-LLdhGM-2SsXJPWLLMAI:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29472#-:-LLdkXAS7Angw4eR6GKY:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
