### PR TITLE
docs: add a tech note on API authn/authz

### PR DESCRIPTION
**Pull request by knz**
Text of the tech note here: https://github.com/knz/cockroach/blob/20230202-api-authn-tech-note/docs/tech-notes/api_authentication.md

Release note: None
Epic: None

### CODE REVIEW

**Review by andreimatei — APPROVED** [review]
:lgtm: 

good note

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96427#-:-NNlunic3rPQiUhm3SDp:b-9gm10a)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[`docs/tech-notes/api_authentication.md` line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96427#-NNlsoquCq-9oWWBx00X:-NNlsoquCq-9oWWBx00Y:b-mhka3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7f272902b4ac1247a72a28c893c75750d2b5c8a/docs/tech-notes/api_authentication.md#L47)):*
> ```Markdown
> ### Unauthenticated pure HTTP handler
> 
> HTTP -> direct HTTP handler
> ```

could you explain how come `authenticationV2Mux` is not in the call chain here? Where's the distinction being made between handlers that want auth and those who don't?

**Review by dhartunian — APPROVED** [review]
:lgtm: thankyou Raphael.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96427#-:-NNlyrZ89YZ8rx4IuiQ2:belbqh)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96427)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andreimatei and @dhartunian)

___
*[`docs/tech-notes/api_authentication.md` line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96427#-NNlsoquCq-9oWWBx00X:-NO88vhD1W0zw9r2RDM1:bacbz7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7f272902b4ac1247a72a28c893c75750d2b5c8a/docs/tech-notes/api_authentication.md#L47)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

could you explain how come `authenticationV2Mux` is not in the call chain here? Where's the distinction being made between handlers that want auth and those who don't?
</blockquote></details>

it's just health and vars. We opted them out, because they don't leak state out of the cluster.

**Comment by knz** [comment]
@dhartunian Andrei's question raises a good point: the prometheus vars endpoint is currently exposed without authentication (for reasons that can be pulled back from the git history).

What do you think will happen if we start exposing more "intelligent" labels for metrics? I remember your project to annotate metrics using statement fingerprints. Maybe tenant labels as well. Do we want this data to be scrapable without authentication? This might need followup issues to investigate further.

**Comment by knz** [comment]
bors r=andreimatei,dhartunian

**Pull request merged**
