### PR TITLE
roachtest: respect ctx cancelation in admission-control/elastic-io

### LINKED ISSUE #136557: roachtest: admission-control/elastic-io failed
roachtest.admission-control/elastic-io [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18008228?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18008228?buildTab=artifacts#/admission-control/elastic-io) on release-24.1.8-rc @ [8450f1eef817abf295de10517cf0720e65e7a9b0](https://github.com/cockroachdb/cockroach/commits/8450f1eef817abf295de10517cf0720e65e7a9b0):

```
VMs preempted during the test run: teamcity-18008228-1733208434-12-n2cpu8-0001 (us-central1-a)

**Other Failures:**
(cluster.go:2396).Run: context canceled
(test_runner.go:1257).runTest: test timed out (1h0m0s)
test artifacts and logs in: /artifacts/admission-control/elastic-io/cpu_arch=arm64/run_1
```

Parameters:
 - <code>arch=arm64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=8</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=false</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-18008228/admission-control-elastic-io/1733208932092/1733212851587)

</p>
</details>
/cc @cockroachdb/storage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*admission-control/elastic-io.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-45125

### PR DESCRIPTION
**Pull request by aadityasondhi**
Fixes #136557.

Release note: None

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]

**Review by DarrylWong — APPROVED** [review]

**Comment by herkolategan** [comment]
I think this is a flake that has been happening since we fixed post assertions (https://github.com/cockroachdb/cockroach/pull/135156).
```
  --- FAIL: acceptance/gossip/restart-node-one (55.43s)
  (test_runner.go:1474).func1: failed during post test assertions (see test-post-assertions.log): pq: setting updated but timed out waiting to read new value
  test artifacts and logs in: /github-actions-runner/_work/cockroach/cockroach/artifacts/acceptance/gossip/restart-node-one/run_1
  2024/12/05 04:30:04 test_runner.go:1201: ::error title=acceptance/gossip/restart-node-one failed::(test_runner.go:1474).func1: failed during post test assertions (see test-post-assertions.log): pq: setting updated but timed out waiting to read new value
  Error: (test_runner.go:1474).func1: failed during post test assertions (see test-post-assertions.log): pq: setting updated but timed out waiting to read new value
  2024/12/05 04:30:04 test_runner.go:1201: ::error title=acceptance/gossip/restart-node-one failed::test artifacts and logs in: /github-actions-runner/_work/cockroach/cockroach/artifacts/acceptance/gossip/restart-node-one/run_1
  Error: test artifacts and logs in: /github-actions-runner/_work/cockroach/cockroach/artifacts/acceptance/gossip/restart-node-one/run_1
  ```

**Review by herkolategan — APPROVED** [review]

**Comment by herkolategan** [comment]
Yep, thought I saw this before:
Another instance of this failure:
Also on `acceptance/gossip/restart-node-one`
https://github.com/cockroachdb/cockroach/pull/136521

I suspect it has something to do with starting a `special node` and then stopping and restarting it right before the end of the tests, that maybe cause the cluster setting to timeout in post validations.

**Comment by aadityasondhi** [comment]
@herkolategan do we have a fix for this issue? Don't think I can merge this with the failing CI.

**Comment by aadityasondhi** [comment]
Ah re-running CI gave me clean run.

bors r=srosenberg,DarrylWong,herkolategan

**Comment by srosenberg** [comment]
> Yep, thought I saw this before: Another instance of this failure: Also on `acceptance/gossip/restart-node-one` #136521
> 
> I suspect it has something to do with starting a `special node` and then stopping and restarting it right before the end of the tests, that maybe cause the cluster setting to timeout in post validations.

I suspect the settings propagation timeout is more likely in `local_roachtest` due to resource contention. If this continues to flake, we should opt out from consistency checking under `local`.

**Pull request merged**
