### PR TITLE
sql/parser: remove *StrVal from Statements when not necessary

### PR DESCRIPTION
**Pull request by nvb**
This change removes instances of `*StrVal` from the types:
- `parser.Backup`
- `parser.Restore`
- `parser.CreateDatabase`
- `parser.CreateUser`

These `*StrVal`s were not being used as general Expressions, but instead
were being type checked, required to return a *DString, and cast to a
string.

The change also has the side effect of making the grammar for the first
three of these statements more general. Instead of only allowing SCONSTs
for certain fields, we now accept the YACC rule
`non_reserved_word_or_sconst`. This change was intentional because it is
how Postgres has implemented the grammar, meaning that we gain a bit of
compatibility. In practice, it means that where before only the first of
the following statements was accepted, now all three are:
```
CREATE DATABASE a TEMPLATE = 'template0'
CREATE DATABASE a TEMPLATE = template0
CREATE DATABASE a TEMPLATE = "template0"
```

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12862)

### CODE REVIEW

**Comment by danhhz** [comment]
:LGTM: everything optional except the one about using string instead of Name in the Backup struct

---

Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/backup.go, line 24 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12862#-KaIFFsT4Aw1dZ61F9ib:-KaIFFsT4Aw1dZ61F9ic:b-z8fcfy) ([raw file](https://github.com/cockroachdb/cockroach/blob/99e18d3b05ce39b60b089362b5cb703dc80fc7fa/pkg/sql/parser/backup.go#L24)):*
> ```Go
> type Backup struct {
> 	Database        Name
> 	To              Name
> ```

these aren't names, they're uris (but really they're opaque to the parser). string type plz

---

*[pkg/sql/parser/backup.go, line 30 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12862#-KaIFO6hfP3LxbxyB12c:-KaIFO6hfP3LxbxyB12d:bojuta9) ([raw file](https://github.com/cockroachdb/cockroach/blob/99e18d3b05ce39b60b089362b5cb703dc80fc7fa/pkg/sql/parser/backup.go#L30)):*
> ```Go
> var _ Statement = &Backup{}
> 
> // HasIncrementalFrom returns if the Backup has an incremental from clause.
> ```

I don't think these methods add anything except one more jump when reading this code. Why all the indirection?

regardless, "returns true"

---

*[pkg/sql/parser/create.go, line 683 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12862#-KaIFuV94ZttiGo_hF1g:-KaIFuV94ZttiGo_hF1h:b-uvs5kt) ([raw file](https://github.com/cockroachdb/cockroach/blob/99e18d3b05ce39b60b089362b5cb703dc80fc7fa/pkg/sql/parser/create.go#L683)):*
> ```Go
> 
> // HasPassword returns if the CreateUser has a password.
> func (node *CreateUser) HasPassword() bool {
> ```

unlike the other HasFoos introduced, this one makes sense to me b/c of the nil vs empty distinction

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12862#-:-KaIGayeYvMTWw9gai5m:b1gay1x)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/parser/backup.go, line 24 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12862#-KaIFFsT4Aw1dZ61F9ib:-KaPDupBgiWCU1q5Tr1s:bytssbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/99e18d3b05ce39b60b089362b5cb703dc80fc7fa/pkg/sql/parser/backup.go#L24)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

these aren't names, they're uris (but really they're opaque to the parser). string type plz
</blockquote></details>

The reason I set these to `Name`s, along with those in `CreateDatabase`, is because of the formatting provided by the type. Without it, strings like `'abc.def'` would be printed unquoted as `abc.def` (of course, we could work around this, but I'd like to follow precedent if possible). `Name` is meant to be used for a SQL identifier, but I don't _think_ they carry a set-in-stone connotation. I definitely might be wrong, though. cc. @knz

---

*[pkg/sql/parser/backup.go, line 30 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12862#-KaIFO6hfP3LxbxyB12c:-KaPBqzf8ILNxsj7_gDw:bd9hik9) ([raw file](https://github.com/cockroachdb/cockroach/blob/99e18d3b05ce39b60b089362b5cb703dc80fc7fa/pkg/sql/parser/backup.go#L30)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I don't think these methods add anything except one more jump when reading this code. Why all the indirection?

regardless, "returns true"
</blockquote></details>

Got rid of the `Has___` methods in most places.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12862)*

**Comment by danhhz** [comment]
Reviewed 4 of 7 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/backup.go, line 24 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12862#-KaIFFsT4Aw1dZ61F9ib:-Kah9AGnTZrUt4X4gHr0:b-wbpjk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/99e18d3b05ce39b60b089362b5cb703dc80fc7fa/pkg/sql/parser/backup.go#L24)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The reason I set these to `Name`s, along with those in `CreateDatabase`, is because of the formatting provided by the type. Without it, strings like `'abc.def'` would be printed unquoted as `abc.def` (of course, we could work around this, but I'd like to follow precedent if possible). `Name` is meant to be used for a SQL identifier, but I don't _think_ they carry a set-in-stone connotation. I definitely might be wrong, though. cc. @knz
</blockquote></details>

That makes sense but it still feels like the wrong conclusion to me. Why not just call "encodeSQLIdent" (the method that Name uses in format) to implement Backup.Format?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12862)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/backup.go, line 24 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12862#-KaIFFsT4Aw1dZ61F9ib:-KaiOr5HB_AzptqhU6K8:bkqfokp) ([raw file](https://github.com/cockroachdb/cockroach/blob/99e18d3b05ce39b60b089362b5cb703dc80fc7fa/pkg/sql/parser/backup.go#L24)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

That makes sense but it still feels like the wrong conclusion to me. Why not just call "encodeSQLIdent" (the method that Name uses in format) to implement Backup.Format?
</blockquote></details>

Done. Switched to `string` and using `encodeSQLStringWithFlags` which should give this the desired behavior and meaning.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12862)*

**Comment by nvanbenschoten** [comment]
Rebased onto master after #12956 merged.

**Comment by danhhz** [comment]
:lgtm: Sorry about the merge conflict, I had other work blocked on getting that merged and rebased into enterprise

---

Review status: 1 of 7 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12862#-:-KarMHqBfEPnhKmU54Ry:b7o88th)*

**Comment by nvanbenschoten** [comment]
No problem, TFTR!

**Comment by knz** [comment]
Nice clean-up

---

Reviewed 1 of 7 files at r1, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12862#-:-Kb5Tzx11XOC2dHnHq6i:b7owph9)*

**Pull request merged**
