### PR TITLE
protectedts: fix panic when fetching protectedts records

### LINKED ISSUE #79684: protectedts: v22.1.0-beta: interface conversion: tree.Datum is tree.dNull, not *tree.DBytes
This issue was autofiled by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry link: https://sentry.io/organizations/cockroach-labs/issues/3173966052/?referrer=webhooks_plugin

Panic message:

>panic.go:1038: interface conversion: tree.Datum is tree.dNull, not *tree.DBytes
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:1038
  | runtime.panicdottypeE
  | 	GOROOT/src/runtime/iface.go:261
  | runtime.panicdottypeI
  | 	GOROOT/src/runtime/iface.go:271
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/protectedts/ptstorage.rowToRecord
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/protectedts/ptstorage/pkg/kv/kvserver/protectedts/ptstorage/storage.go:418
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/protectedts/ptstorage.(*storage).getRecords
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/protectedts/ptstorage/pkg/kv/kvserver/protectedts/ptstorage/storage.go:372
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/protectedts/ptstorage.(*storage).GetState
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/protectedts/ptstorage/pkg/kv/kvserver/protectedts/ptstorage/storage.go:324
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/protectedts/ptcache.(*Cache).doUpdate.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/protectedts/ptcache/cache.go:245
  | github.com/cockroachdb/cockroach/pkg/kv.runTxn.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:932
  | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec
  | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:985
  | github.com/cockroachdb/cockroach/pkg/kv.runTxn
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:931
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:894
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/protectedts/ptcache.(*Cache).doUpdate
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/protectedts/ptcache/cache.go:229
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:344
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/protectedts/ptcache.(*Cache).doSingleFlightUpdate
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/protectedts/ptcache/cache.go:208
  | github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).doCall
  | 	github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:128
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1581
Wraps: (2) interface conversion: tree.Datum is tree.dNull, not *tree.DBytes
Error types: (1) *withstack.withStack (2) *runtime.TypeAssertionError
-- report composition:
*runtime.TypeAssertionError
panic.go:1038: *withstack.withStack (top exception)

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

GOROOT/src/runtime/panic.go#L1037-L1039 in runtime.gopanic
GOROOT/src/runtime/iface.go#L260-L262 in runtime.panicdottypeE
GOROOT/src/runtime/iface.go#L270-L272 in runtime.panicdottypeI
https://github.com/cockroachdb/cockroach/blob/a88367d7bd168a3614b7946cd7b77bb9c6374a30/pkg/kv/kvserver/protectedts/ptstorage/pkg/kv/kvserver/protectedts/ptstorage/storage.go#L417-L419 in pkg/kv/kvserver/protectedts/ptstorage.rowToRecord
https://github.com/cockroachdb/cockroach/blob/a88367d7bd168a3614b7946cd7b77bb9c6374a30/pkg/kv/kvserver/protectedts/ptstorage/pkg/kv/kvserver/protectedts/ptstorage/storage.go#L371-L373 in pkg/kv/kvserver/protectedts/ptstorage.(*storage).getRecords
https://github.com/cockroachdb/cockroach/blob/a88367d7bd168a3614b7946cd7b77bb9c6374a30/pkg/kv/kvserver/protectedts/ptstorage/pkg/kv/kvserver/protectedts/ptstorage/storage.go#L323-L325 in pkg/kv/kvserver/protectedts/ptstorage.(*storage).GetState
https://github.com/cockroachdb/cockroach/blob/a88367d7bd168a3614b7946cd7b77bb9c6374a30/pkg/kv/kvserver/protectedts/ptcache/cache.go#L244-L246 in pkg/kv/kvserver/protectedts/ptcache.(*Cache).doUpdate.func1
https://github.com/cockroachdb/cockroach/blob/a88367d7bd168a3614b7946cd7b77bb9c6374a30/pkg/kv/db.go#L931-L933 in pkg/kv.runTxn.func1
https://github.com/cockroachdb/cockroach/blob/a88367d7bd168a3614b7946cd7b77bb9c6374a30/pkg/kv/txn.go#L984-L986 in pkg/kv.(*Txn).exec
https://github.com/cockroachdb/cockroach/blob/a88367d7bd168a3614b7946cd7b77bb9c6374a30/pkg/kv/db.go#L930-L932 in pkg/kv.runTxn
https://github.com/cockroachdb/cockroach/blob/a88367d7bd168a3614b7946cd7b77bb9c6374a30/pkg/kv/db.go#L893-L895 in pkg/kv.(*DB).Txn
https://github.com/cockroachdb/cockroach/blob/a88367d7bd168a3614b7946cd7b77bb9c6374a30/pkg/kv/kvserver/protectedts/ptcache/cache.go#L228-L230 in pkg/kv/kvserver/protectedts/ptcache.(*Cache).doUpdate
https://github.com/cockroachdb/cockroach/blob/a88367d7bd168a3614b7946cd7b77bb9c6374a30/pkg/util/stop/stopper.go#L343-L345 in pkg/util/stop.(*Stopper).RunTaskWithErr
https://github.com/cockroachdb/cockroach/blob/a88367d7bd168a3614b7946cd7b77bb9c6374a30/pkg/kv/kvserver/protectedts/ptcache/cache.go#L207-L209 in pkg/kv/kvserver/protectedts/ptcache.(*Cache).doSingleFlightUpdate
https://github.com/cockroachdb/cockroach/blob/a88367d7bd168a3614b7946cd7b77bb9c6374a30/pkg/util/syncutil/singleflight/singleflight.go#L127-L129 in pkg/util/syncutil/singleflight.(*Group).doCall
src/runtime/asm_amd64.s#L1580-L1582 in runtime.goexit
</details>

```
GOROOT/src/runtime/panic.go in runtime.gopanic at line 1038
GOROOT/src/runtime/iface.go in runtime.panicdottypeE at line 261
GOROOT/src/runtime/iface.go in runtime.panicdottypeI at line 271
pkg/kv/kvserver/protectedts/ptstorage/pkg/kv/kvserver/protectedts/ptstorage/storage.go in pkg/kv/kvserver/protectedts/ptstorage.rowToRecord at line 418
pkg/kv/kvserver/protectedts/ptstorage/pkg/kv/kvserver/protectedts/ptstorage/storage.go in pkg/kv/kvserver/protectedts/ptstorage.(*storage).getRecords at line 372
pkg/kv/kvserver/protectedts/ptstorage/pkg/kv/kvserver/protectedts/ptstorage/storage.go in pkg/kv/kvserver/protectedts/ptstorage.(*storage).GetState at line 324
pkg/kv/kvserver/protectedts/ptcache/cache.go in pkg/kv/kvserver/protectedts/ptcache.(*Cache).doUpdate.func1 at line 245
pkg/kv/db.go in pkg/kv.runTxn.func1 at line 932
pkg/kv/txn.go in pkg/kv.(*Txn).exec at line 985
pkg/kv/db.go in pkg/kv.runTxn at line 931
pkg/kv/db.go in pkg/kv.(*DB).Txn at line 894
pkg/kv/kvserver/protectedts/ptcache/cache.go in pkg/kv/kvserver/protectedts/ptcache.(*Cache).doUpdate at line 229
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTaskWithErr at line 344
pkg/kv/kvserver/protectedts/ptcache/cache.go in pkg/kv/kvserver/protectedts/ptcache.(*Cache).doSingleFlightUpdate at line 208
pkg/util/syncutil/singleflight/singleflight.go in pkg/util/syncutil/singleflight.(*Group).doCall at line 128
src/runtime/asm_amd64.s in runtime.goexit at line 1581
```

| Tag | Value |
|---|---|
| Cockroach Release | `v22.1.0-beta.1` |
| Cockroach SHA: | a88367d7bd168a3614b7946cd7b77bb9c6374a30 |
| Platform | darwin amd64 |
| Distribution | CCL |
| Environment | v22.1.0-beta.1 |
| Command | start-single-node |
| Go Version | ``|
| # of CPUs ||
| # of Goroutines ||

Jira issue: CRDB-14978

### PR DESCRIPTION
**Pull request by adityamaru**
Previously, we incorrectly assumed that all records in the
`system.protectedts_records` table would have a non NULL target
column. While this is enforced for all protected timestamp
records written in a 22.1+ cluster, this is not true for records
that might have been prior to the 22.1 cluster version being
finalized.

This change makes the method responsible for reading protectedts
records more defensive when encountering a NULL target column.

Fixes: #79684

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79787#-:-N-OzHjg648yToii0O-s:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79787#-:-N-PHMfZ4Hj6ugdmkLEa:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru)

___
*[pkg/kv/kvserver/protectedts/ptstorage/storage.go, line 421 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79787#-N-PH9-I209gREeZNsWq:-N-PH9-I209gREeZNsWr:bo8knwb) ([raw file](https://github.com/cockroachdb/cockroach/blob/1788ab9a0d5ab3c07318f644b718c2b2c429fbde/pkg/kv/kvserver/protectedts/ptstorage/storage.go#L421)):*
> ```Go
> 		if !ok {
> 			// We are reading a pre-22.1 protected timestamp record that has a NULL
> 			// target column, so there is nothing more to do.
> ```

nit: add a TODO to remove this code in the next release?

**Comment by adityamaru** [comment]
> nit: add a TODO to remove this code in the next release?
I promise I'll remember, don't make me push again 😋

**Comment by adityamaru** [comment]
TFTRs!

bors r+

**Pull request merged**
