### PR TITLE
sql: add a knob to parallelize lookup joins in all cases

### PR DESCRIPTION
**Pull request by yuzefovich**
Currently, due to limitations of the BatchRequest API, the users of the
DistSender have to make a choice between using memory limits (safety)
and concurrency (performance). In particular, the joinReader thinks that
it is safe to parallelize its lookup requests if each request is
guaranteed to return at most one row in the result. However, when this
is not guaranteed, the joinReader chooses the safe side and doesn't
parallelize the lookup requests which can be a big performance hit. This
commit introduces a cluster setting with the corresponding session
variable that tells the joinReader to parallelize the lookup requests in
all cases. It is marked as "unsafe" since using the knob might lead to
an increased chance of OOMs, so we leave it up to the user to take the
responsibility.

We do have an RFC in place that introduces a different API, and my hope
is that this knob will become redundant before 22.1 is out.

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
I feel like this sort of cluster setting is on its way out now that we have database-level session defaults.

**Review by nvb — COMMENTED** [review]
Thanks!

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72960#-:-MoqKZxm8XsNeCWU1xdl:b-ucfknh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/rowexec/joinreader.go, line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72960#-MoqJcSJBjAYYuVglFYW:-MoqJcSJBjAYYuVglFYX:b-n9mhut) ([raw file](https://github.com/cockroachdb/cockroach/blob/35cb6eee63cc8d2a76a5305858a83fab3bd4fd94/pkg/sql/rowexec/joinreader.go#L211)):*
> ```Go
> // parallelizes KV batches in all cases.
> var UnsafeParallizeLookupJoinsEnabled = settings.RegisterBoolSetting(
> 	"sql.distsql.unsafe_parallelize_lookup_joins.enabled",
> ```

Is "unsafe" the right term here? If used correctly, it's no less safe than what we're already doing with fanning out lookup joins without an overall batch memory limit. Even if we're only looking up single keys, those keys could each be huge. Perhaps we could be more explicit and just call this something like `sql.distsql.parallelize_multi_key_lookup_joins.enabled` and then explain in the description that this is a memory vs. concurrency trade-off.

**Review by yuzefovich — COMMENTED** [review]
> this sort of cluster setting is on its way out now that we have database-level session defaults.

I'm pretty sure that this cluster setting will be removed before 22.1 is out, so I wouldn't worry too much about it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72960#-:-MouDO1B4tx6xloW8Wz-:b-ej80ba)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/sql/rowexec/joinreader.go, line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72960#-MoqJcSJBjAYYuVglFYW:-MouCSV9-4FV43l_hBHN:b-q3thxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/35cb6eee63cc8d2a76a5305858a83fab3bd4fd94/pkg/sql/rowexec/joinreader.go#L211)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is "unsafe" the right term here? If used correctly, it's no less safe than what we're already doing with fanning out lookup joins without an overall batch memory limit. Even if we're only looking up single keys, those keys could each be huge. Perhaps we could be more explicit and just call this something like `sql.distsql.parallelize_multi_key_lookup_joins.enabled` and then explain in the description that this is a memory vs. concurrency trade-off.
</blockquote></details>

That's a good point. I like your suggestion, done.

**Review by nvb — APPROVED** [review]
:lgtm_strong: 

> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72960#-:-MouMwsd23evx1q4Q4QS:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
