### PR TITLE
sql: add support for materialized views

### LINKED ISSUE #41649: sql: missing support for CREATE MATERIALIZED VIEW
PostgreSQL supports materialized views with CREATE MATERIALIZED VIEW. CockroachDB is missing support for this feature. It is unclear if the semantics PostgreSQL provides would be good to add to CockroachDB, but this issue exists as a placeholder to point to when discussing this missing support.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #41649.

This commit adds support for materialized views in CockroachDB. These
materialized views follow the Postgres style, where the `REFRESH
MATERIALIZED VIEW` command is needed to update the stored view data.
This commit does not include adding the various `ALTER MATERIALIZED
VIEW` and `DROP MATERIALIZED VIEW` extensions and will be added in a
follow up PR.

Release note (sql change): Add support for materialized views.

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
Wow, awesome work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52530#-:-MEOvYpwE-P6NKIDgZVU:bpszj51)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @jordanlewis, @RaduBerinde, and @rohany)

___
*[pkg/sql/resolver.go, line 392 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52530#-MEOd2t69RC0AxIbpN0c:-MEOd2t69RC0AxIbpN0d:b-b0ql0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/84e0e7b1167d2262597af3b0d42c06025adea741/pkg/sql/resolver.go#L392)):*
> ```Go
> 		if desc != nil && desc.IsView() && !desc.MaterializedView() {
> 			// TODO (rohany): Return a pgerror here.
> 			return nil, nil, errors.New("its a viewwwww")
> ```

:angry: 
___
*[pkg/sql/schema_changer.go, line 333 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52530#-MEOdcke1ViH_XgG-5tR:-MEOdcke1ViH_XgG-5tS:b4link7) ([raw file](https://github.com/cockroachdb/cockroach/blob/84e0e7b1167d2262597af3b0d42c06025adea741/pkg/sql/schema_changer.go#L333)):*
> ```Go
> 		return nil
> 	}
> 	log.Info(ctx, "starting backfill for CREATE TABLE AS")
> ```

add the table details to this message
___
*[pkg/sql/schema_changer.go, line 344 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52530#-MEOd_u6AK6LcBlFERX5:-MEOd_u6AK6LcBlFERX6:b-2p1c58) ([raw file](https://github.com/cockroachdb/cockroach/blob/84e0e7b1167d2262597af3b0d42c06025adea741/pkg/sql/schema_changer.go#L344)):*
> ```Go
> 		return nil
> 	}
> 	log.Infof(ctx, "starting backfill for CREATE MATERIALIZED VIEW")
> ```

Add the view details to this message
___
*[pkg/sql/catalog/descpb/structured.proto, line 548 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52530#-MEOuuug8axpX32wKkPF:-MEOuuug8axpX32wKkPG:b-jrpiyn) ([raw file](https://github.com/cockroachdb/cockroach/blob/84e0e7b1167d2262597af3b0d42c06025adea741/pkg/sql/catalog/descpb/structured.proto#L548)):*
> ```protobuf
>   optional IndexDescriptor new_primary_index = 1 [(gogoproto.nullable) = false];
>   repeated IndexDescriptor new_indexes = 2 [(gogoproto.nullable) = false];
>   optional util.hlc.Timestamp as_of = 3 [(gogoproto.nullable) = false];
> ```

Comments on these please
___
*[pkg/sql/catalog/descpb/structured.proto, line 870 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52530#-MEOuxaABkNqT5bvVNL3:-MEOuxaABkNqT5bvVNL4:bom49jb) ([raw file](https://github.com/cockroachdb/cockroach/blob/84e0e7b1167d2262597af3b0d42c06025adea741/pkg/sql/catalog/descpb/structured.proto#L870)):*
> ```protobuf
>   // a TableDescriptor represents a view.
>   optional string view_query = 24 [(gogoproto.nullable) = false];
>   optional bool is_materialized_view = 41 [(gogoproto.nullable) = false];
> ```

Comment on this (e.g. it should only be set if view_query is also set)
___
*[pkg/sql/logictest/testdata/logic_test/materialized_view, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52530#-MEOvLWRAS7AO1h6LWzd:-MEOvLWRAS7AO1h6LWze:b-qsjrdi) ([raw file](https://github.com/cockroachdb/cockroach/blob/84e0e7b1167d2262597af3b0d42c06025adea741/pkg/sql/logictest/testdata/logic_test/materialized_view#L91)):*
> ```
> 
> statement error pq: cannot mutate materialized view "v"
> DELETE FROM v WHERE x = 1
> ```

What does TRUNCATE do?

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52530)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @jordanlewis, and @RaduBerinde)

___
*[pkg/sql/resolver.go, line 392 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52530#-MEOd2t69RC0AxIbpN0c:-MEOzkgF-JzgBdU99Bqu:b-7h4w7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/84e0e7b1167d2262597af3b0d42c06025adea741/pkg/sql/resolver.go#L392)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

:angry: 
</blockquote></details>

woops
___
*[pkg/sql/schema_changer.go, line 333 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52530#-MEOdcke1ViH_XgG-5tR:-MEOzlQc2L51oFNkZYOy:b-e98h1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/84e0e7b1167d2262597af3b0d42c06025adea741/pkg/sql/schema_changer.go#L333)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

add the table details to this message
</blockquote></details>

Done. Added the query -- the table ID etc are already in the context's logtags
___
*[pkg/sql/schema_changer.go, line 344 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52530#-MEOd_u6AK6LcBlFERX5:-MEOzoux0ULkkUKhVA2J:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/84e0e7b1167d2262597af3b0d42c06025adea741/pkg/sql/schema_changer.go#L344)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Add the view details to this message
</blockquote></details>

Done.
___
*[pkg/sql/catalog/descpb/structured.proto, line 548 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52530#-MEOuuug8axpX32wKkPF:-MEOzpO28Bj9JBkSSAfg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/84e0e7b1167d2262597af3b0d42c06025adea741/pkg/sql/catalog/descpb/structured.proto#L548)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Comments on these please
</blockquote></details>

Done.
___
*[pkg/sql/catalog/descpb/structured.proto, line 870 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52530#-MEOuxaABkNqT5bvVNL3:-MEOzpnC4V3207-R4lFu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/84e0e7b1167d2262597af3b0d42c06025adea741/pkg/sql/catalog/descpb/structured.proto#L870)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Comment on this (e.g. it should only be set if view_query is also set)
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/materialized_view, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52530#-MEOvLWRAS7AO1h6LWzd:-MEOzqIp1Je0VG8cyubR:bsqyezv) ([raw file](https://github.com/cockroachdb/cockroach/blob/84e0e7b1167d2262597af3b0d42c06025adea741/pkg/sql/logictest/testdata/logic_test/materialized_view#L91)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

What does TRUNCATE do?
</blockquote></details>

Done, checked against the postgres error.

**Review by jordanlewis — APPROVED** [review]
pg_class.relkind needs to be updated to store `m` for materialized views.

:lgtm:, I think a review from a schema/bulkio focused person would be good. :tada: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52530#-:-MEYMpWk-h0S-QlGowyO:bll5far)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @RaduBerinde, and @rohany)

___
*[pkg/sql/refresh_materialized_view.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52530#-MEYNZKa1kfwK-Zo4sMW:-MEYNZKa1kfwK-Zo4sMX:b-wi5qci) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae886a59ead9ac080657fc014834eb393427cf9e/pkg/sql/refresh_materialized_view.go#L83)):*
> ```Go
> 		NewPrimaryIndex: *newPrimaryIndex,
> 		NewIndexes:      newIndexes,
> 		AsOf:            params.p.Txn().ReadTimestamp(),
> ```

Should we make this in the past to avoid contention?

**Comment by rohany** [comment]
> :lgtm:, I think a review from a schema/bulkio focused person would be good. 🎉

Yeah, I want @ajwerner to take a peek

> Should we make this in the past to avoid contention?

What do you mean -- we have to take the read timestamp of the actual call to refresh. By the time that the schema change runs it's in the past however.

**Review by RaduBerinde — COMMENTED** [review]
Opt part LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52530#-:-MEcS2DgDZ_qmh9RYJNe:ba48r2n)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @ajwerner, @RaduBerinde, and @rohany)

**Review by ajwerner — APPROVED** [review]
:lgtm: mod disabling hash sharded indexes 

> Reviewed 10 of 41 files at r1, 5 of 6 files at r2, 29 of 29 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52530#-:-MEdkRAZ77FKdqCihig7:b-t8ekj7)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @jordanlewis, and @rohany)

___
*[pkg/sql/create_index.go, line 67 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52530#-MEdfS73-ce_GZdZRTwS:-MEdfS753a6HVTJLpHAY:bmjadzg) ([raw file](https://github.com/cockroachdb/cockroach/blob/49f562643afce6ff37f3c065b5f81ea871afe549/pkg/sql/create_index.go#L67)):*
> ```Go
> 			return nil, pgerror.New(pgcode.InvalidObjectDefinition,
> 				"cannot create interleaved index on materialized view")
> 		}
> ```

Can we disable hash sharded indexes here too? I don't think I want to deal with adding the column and they don't really make sense. 
___
*[pkg/sql/refresh_materialized_view.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52530#-MEYNZKa1kfwK-Zo4sMW:-MEdgJe12lQ-jzA-Eqhq:b-l6t8ve) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae886a59ead9ac080657fc014834eb393427cf9e/pkg/sql/refresh_materialized_view.go#L83)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Should we make this in the past to avoid contention?
</blockquote></details>

Meh, I think it'd be weird to do that without the user telling us. Like say we do a write and then a refresh, I definitely want to see that write. I'd be cool with creating a follow-up item to support an `AS OF SYSTEM TIME` clause. 
___
*[pkg/sql/refresh_materialized_view.go, line 47 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52530#-MEdgAll4mhXkYE3LYLH:-MEdgAll4mhXkYE3LYLI:bcrkcfv) ([raw file](https://github.com/cockroachdb/cockroach/blob/49f562643afce6ff37f3c065b5f81ea871afe549/pkg/sql/refresh_materialized_view.go#L47)):*
> ```Go
> 		mut := &desc.Mutations[i]
> 		if mut.GetMaterializedViewRefresh() != nil {
> 			return nil, pgerror.Newf(pgcode.SQLStatementNotYetComplete, "view is already being refreshed")
> ```

nit: maybe `pgcode.ObjectNotInPrerequisiteState` instead?
___
*[pkg/sql/logictest/testdata/logic_test/materialized_view, line 44 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52530#-MEdiiTH-cS7w_XwzFZ2:-MEdiiTJ4SJrDjiLV9Hm:b2l6frf) ([raw file](https://github.com/cockroachdb/cockroach/blob/49f562643afce6ff37f3c065b5f81ea871afe549/pkg/sql/logictest/testdata/logic_test/materialized_view#L44)):*
> ```
> query I rowsort
> SELECT y FROM v WHERE y > 4
> ```
how do you know you're using it? Maybe force the use with `v@i`

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52530)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @adityamaru, @ajwerner, and @jordanlewis)

___
*[pkg/sql/create_index.go, line 67 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52530#-MEdfS73-ce_GZdZRTwS:-MEeWR5E-BlNcUtBmDWI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/49f562643afce6ff37f3c065b5f81ea871afe549/pkg/sql/create_index.go#L67)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can we disable hash sharded indexes here too? I don't think I want to deal with adding the column and they don't really make sense. 
</blockquote></details>

Done.
___
*[pkg/sql/refresh_materialized_view.go, line 47 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52530#-MEdgAll4mhXkYE3LYLH:-MEeWSLCESQWydlVgvtD:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/49f562643afce6ff37f3c065b5f81ea871afe549/pkg/sql/refresh_materialized_view.go#L47)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: maybe `pgcode.ObjectNotInPrerequisiteState` instead?
</blockquote></details>

done
___
*[pkg/sql/logictest/testdata/logic_test/materialized_view, line 44 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52530#-MEdiiTH-cS7w_XwzFZ2:-MEeWU4YD1PnbBdMIhED:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/49f562643afce6ff37f3c065b5f81ea871afe549/pkg/sql/logictest/testdata/logic_test/materialized_view#L44)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> query I rowsort
> SELECT y FROM v WHERE y > 4
> ```
how do you know you're using it? Maybe force the use with `v@i`
</blockquote></details>

Done.

**Comment by rohany** [comment]
TFTRs!

bors r+

**Comment by wzrdtales** [comment]
Great, will materialized views carry support for indexes on them? That would be amazing, then cockroachdb could catch up in the analytical space even more by building multi dimensional indexed data representations (like in a data warehouse). Looking forward to this!

**Pull request merged**
