### PR TITLE
sql: fix memory monitoring of hash mem row container

### LINKED ISSUE #55204: roachtest: out of memory sqlsmith/setup=tpcc/setting=no-ddl
[(roachtest).sqlsmith/setup=tpcc/setting=no-ddl failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2341039&tab=buildLog) on [master@602aa34aca935b5dc17e2cde6c71b672866ec770](https://github.com/cockroachdb/cockroach/commits/602aa34aca935b5dc17e2cde6c71b672866ec770):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/sqlsmith/setup=tpcc/setting=no-ddl/run_1
	cluster.go:1654,context.go:135,cluster.go:1643,test_runner.go:836: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-2341039-1601705948-01-n4cpu4 --oneshot --ignore-empty-nodes: exit status 1 1: 9347
		2: dead
		4: 6043
		3: 8282
		Error: UNCLASSIFIED_PROBLEM: 2: dead
		(1) UNCLASSIFIED_PROBLEM
		Wraps: (2) attached stack trace
		  -- stack trace:
		  | main.glob..func14
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1143
		  | main.wrap.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:267
		  | github.com/spf13/cobra.(*Command).execute
		  | 	/home/agent/work/.go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830
		  | github.com/spf13/cobra.(*Command).ExecuteC
		  | 	/home/agent/work/.go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
		  | github.com/spf13/cobra.(*Command).Execute
		  | 	/home/agent/work/.go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
		  | main.main
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1839
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:203
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		Wraps: (3) 2: dead
		Error types: (1) errors.Unclassified (2) *withstack.withStack (3) *errutil.leafError

```

<details><summary>More</summary><p>

Artifacts: [/sqlsmith/setup=tpcc/setting=no-ddl](https://teamcity.cockroachdb.com/viewLog.html?buildId=2341039&tab=artifacts#/sqlsmith/setup=tpcc/setting=no-ddl)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Asqlsmith%2Fsetup%3Dtpcc%2Fsetting%3Dno-ddl.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, we incorrectly were using the memory monitor from the eval
context when creating a `HashMemRowContainer`. This could result in that
container using a lot more than `64MB` (the default
`temp_storage.workmem` setting) and could lead to a crash because we
might try to use up to `max-sql-memory` amount of memory and our memory
accounting elsewhere is off. Now it is fixed by using the correct memory
monitor to instantiate a memory account.

Note that we still don't account for the usage of `map` in the hash mem
row container, so in theory the crashes are still possible, yet they
should be highly unlikely (because of this container in particular)
since we should fall-back to the disk backed container once we reach the
memory budget of a single processor.

Additionally, this commit fixes an issue that could occur when using
`HashDiskBackedRowContainer` when falling back from the in-memory to
disk-backed container. Namely, if a memory error was encountered during
`addRowToBucket` (after the row was added to the underlying row container),
that row would have been added to the disk container twice. This is now
fixed. Note that this condition was pretty unlikely to occur because of
the first issue (using the wrong memory monitor).

Fixes: #55204.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I think we should backport the fix (without the stringarena change) to all versions.

**Comment by yuzefovich** [comment]
Actually, I'll make two separate commits so that it was easier to backport.

**Review by asubiotto — CHANGES_REQUESTED** [review]
Great find.

Could you make the commit title of the second commit more specific (i.e. what is the optimization)? Something like `reduce allocations in hash mem row container`

> Reviewed 7 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55309#-:-MJ6gLPl3vI3c3nK-QNv:b-whuj2m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/rowcontainer/hash_row_container.go, line 208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55309#-MJ6h1GG3ueJCyniOGRm:-MJ6h1GG3ueJCyniOGRn:b-qzues8) ([raw file](https://github.com/cockroachdb/cockroach/blob/04bfabba490c5e24810907cc7c76d23737ab1ad6/pkg/sql/rowcontainer/hash_row_container.go#L208)):*
> ```Go
> 		MemRowContainer: rowContainer,
> 		buckets:         make(map[string][]int),
> 		bucketsAcc:      rowContainer.evalCtx.Mon.MakeBoundAccount(),
> ```

Is it an issue that the `rowContainer` argument has access to this monitor and might be using it in its own `AddRow` implementation?
___
*[pkg/sql/rowcontainer/hash_row_container.go, line 269 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55309#-MJ6iuw81o-xYFKfLuhg:-MJ6iuw81o-xYFKfLuhh:b-mxfz7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/b977918e63464f33764a94253ff1f4668d336c9d/pkg/sql/rowcontainer/hash_row_container.go#L269)):*
> ```Go
> 	}
> 
> 	s := string(encoded)
> ```

I think `h.buckets[string(encoded)]`is optimized by the compiler not to do result in an allocation for string maps so I think your code actually forces an allocation where there wasn't one before. What do the benchmarks say? 
___
*[pkg/sql/rowcontainer/hash_row_container_test.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55309#-MJ6hSvH7WkrYJRrcHaU:-MJ6hSvH7WkrYJRrcHaV:bsrbnux) ([raw file](https://github.com/cockroachdb/cockroach/blob/80e5637fad55ca1af6015be191c93e031a91201a/pkg/sql/rowcontainer/hash_row_container_test.go#L73)):*
> ```Go
> 
> 	getRowContainer := func() *HashDiskBackedRowContainer {
> 		rc := NewHashDiskBackedRowContainer(nil, &evalCtx, memoryMonitor, diskMonitor, tempEngine)
> ```

How were these tests working? The `evalCtx` monitor is separate from the `memoryMonitor`, right? So any limit applied to the memory monitor would not cause the row container to fall back to disk
___
*[pkg/sql/rowcontainer/hash_row_container_test.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55309#-MJ6gnIJ6d3Jg59jDaOD:-MJ6gnIJ6d3Jg59jDaOE:b-jx01fg) ([raw file](https://github.com/cockroachdb/cockroach/blob/04bfabba490c5e24810907cc7c76d23737ab1ad6/pkg/sql/rowcontainer/hash_row_container_test.go#L95)):*
> ```Go
> 
> 		defer func() {
> 			if err := rc.UnsafeReset(ctx); err != nil {
> ```

Why are you removing `UnsafeReset`? This tests correct resetting of the hash row container.

**Review by yuzefovich — COMMENTED** [review]
I removed the second commit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55309#-:-MJ93PLjCGf_5xIppl70:b4ewc3a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/rowcontainer/hash_row_container.go, line 208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55309#-MJ6h1GG3ueJCyniOGRm:-MJ9-VuQ03Uf1QBo2tot:b-klaga7) ([raw file](https://github.com/cockroachdb/cockroach/blob/04bfabba490c5e24810907cc7c76d23737ab1ad6/pkg/sql/rowcontainer/hash_row_container.go#L208)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is it an issue that the `rowContainer` argument has access to this monitor and might be using it in its own `AddRow` implementation?
</blockquote></details>

I think it was a mis-use of the contract - `MemRowContainer` needs to have the access to `evalCtx` in order to support ordering of the rows, so we cannot easily remove that, yet the problem was that we used the memory monitor from that `evalCtx` mistakenly, without giving it enough thought. I don't know how to prevent that from happening other than trying to be very conscious when using `evalCtx.Mon`.

One idea could be adding a linter rule that would prohibit such usage, and the developer would have to explicitly specify that the usage is ok with something like `nolint:monitor`, what do you think?
___
*[pkg/sql/rowcontainer/hash_row_container.go, line 269 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55309#-MJ6iuw81o-xYFKfLuhg:-MJ90SgPBiz4y-jsmfsX:b-f4if8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/b977918e63464f33764a94253ff1f4668d336c9d/pkg/sql/rowcontainer/hash_row_container.go#L269)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think `h.buckets[string(encoded)]`is optimized by the compiler not to do result in an allocation for string maps so I think your code actually forces an allocation where there wasn't one before. What do the benchmarks say? 
</blockquote></details>

Hm, I think you're right. The benchmarks don't show any difference because they don't have duplicate rows, and I think I'll just remove the second commit entirely.
___
*[pkg/sql/rowcontainer/hash_row_container_test.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55309#-MJ6hSvH7WkrYJRrcHaU:-MJ91QPn8CQ7d3Kxdl4k:b-diqbtz) ([raw file](https://github.com/cockroachdb/cockroach/blob/80e5637fad55ca1af6015be191c93e031a91201a/pkg/sql/rowcontainer/hash_row_container_test.go#L73)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

How were these tests working? The `evalCtx` monitor is separate from the `memoryMonitor`, right? So any limit applied to the memory monitor would not cause the row container to fall back to disk
</blockquote></details>

Yes, `evalCtx` monitor and `memoryMonitor` are not related, but the tests were working because `MemRowContainer` used `memoryMonitor` to create an account while `HashMemRowContainer` used `evalCtx.Mon` to do that, and the memory error would occur on `h.MemRowContainer.AddRow` line, before we try add the row to bucket. Basically, the correct monitor was used in one code path but not the other.
___
*[pkg/sql/rowcontainer/hash_row_container_test.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55309#-MJ6gnIJ6d3Jg59jDaOD:-MJ92pukDo-0KNEwjepz:b9utk0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/04bfabba490c5e24810907cc7c76d23737ab1ad6/pkg/sql/rowcontainer/hash_row_container_test.go#L95)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why are you removing `UnsafeReset`? This tests correct resetting of the hash row container.
</blockquote></details>

`UnsafeReset` has only been used in tests, so it is now removed.

What prompted me to change the tests is that with the previous layout once we started creating a memory account from `memoryMonitor`, we needed to close the row container before we stop the monitor, otherwise there would be leftover unreleased memory.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55309)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/rowcontainer/hash_row_container.go, line 208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55309#-MJ6h1GG3ueJCyniOGRm:-MJJbrvPBIn88EqVrAgZ:b5r1a29) ([raw file](https://github.com/cockroachdb/cockroach/blob/04bfabba490c5e24810907cc7c76d23737ab1ad6/pkg/sql/rowcontainer/hash_row_container.go#L208)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think it was a mis-use of the contract - `MemRowContainer` needs to have the access to `evalCtx` in order to support ordering of the rows, so we cannot easily remove that, yet the problem was that we used the memory monitor from that `evalCtx` mistakenly, without giving it enough thought. I don't know how to prevent that from happening other than trying to be very conscious when using `evalCtx.Mon`.

One idea could be adding a linter rule that would prohibit such usage, and the developer would have to explicitly specify that the usage is ok with something like `nolint:monitor`, what do you think?
</blockquote></details>

Implemented that idea in #55415.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55309#-:-MJRBn978sJyJNGb5OiQ:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/rowcontainer/hash_row_container_test.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55309#-MJ6gnIJ6d3Jg59jDaOD:-MJRA0laAP-KBmCTBMDH:bi3prxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/04bfabba490c5e24810907cc7c76d23737ab1ad6/pkg/sql/rowcontainer/hash_row_container_test.go#L95)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

`UnsafeReset` has only been used in tests, so it is now removed.

What prompted me to change the tests is that with the previous layout once we started creating a memory account from `memoryMonitor`, we needed to close the row container before we stop the monitor, otherwise there would be leftover unreleased memory.
</blockquote></details>

But doesn't `UnsafeReset` implement some interface that needs to be implemented? Doesn't seem like it. It seems like overkill to remove a method to avoid closing an account but since it's not used elsewhere :shrug: up to you

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55309#-:-MJSVle4-wZoftHtFoOJ:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/rowcontainer/hash_row_container_test.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55309#-MJ6gnIJ6d3Jg59jDaOD:-MJSV-R75OUsSRM8pb_v:b-lyqfys) ([raw file](https://github.com/cockroachdb/cockroach/blob/04bfabba490c5e24810907cc7c76d23737ab1ad6/pkg/sql/rowcontainer/hash_row_container_test.go#L95)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

But doesn't `UnsafeReset` implement some interface that needs to be implemented? Doesn't seem like it. It seems like overkill to remove a method to avoid closing an account but since it's not used elsewhere :shrug: up to you
</blockquote></details>

`UnsafeReset` is part of `SortableRowContainer` interface but not of `HashRowContainer`, so it is not necessary to have it. I remember that I only added `HashDiskBackedRowContainer.UnsafeReset` when implementing it only because containers in `row_container.go` had that, and I followed the same test layout as in `row_container_test.go`, so I think it is ok to remove it.

**Pull request merged**
