### PR TITLE
server: fix testserver's splitRange

### PR DESCRIPTION
**Pull request by BramGruneir**
If the errors are wrapped, they won't be retried.

### CODE REVIEW

**Comment by a-robinson** [comment]
Was there a flaky test that this fixes?

**Comment by BramGruneir** [comment]
This only fixes the setup of the flaky tests, more work needs to be done to fix the tests themselves.  Fun times!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15330#-:-Kia6l68cLJ_m-vqrfmf:b-zaaovb)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/server/testserver.go, line 522 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15330#-Kia8lEd-pXPlrYJW58-:-Kia8lEeGtmGJyIsgEv0:bu0e9gf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c44bb9c6d4583fbef09c439613ec154cdf00a6b/pkg/server/testserver.go#L522)):*
> ```Go
> 	// scans (in case there are other splits happening).
> 	var leftRangeDesc, rightRangeDesc roachpb.RangeDescriptor
> 	var wrappedMsg string
> ```

this deserves a comment that begins with "NB:"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15330)*

**Comment by RaduBerinde** [comment]
:lgtm: Thanks!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/server/testserver.go, line 522 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15330#-Kia8lEd-pXPlrYJW58-:-Kia9HNfwVoMM9E_9fsA:bwwotdj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c44bb9c6d4583fbef09c439613ec154cdf00a6b/pkg/server/testserver.go#L522)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this deserves a comment that begins with "NB:"
</blockquote></details>

+1 We should explain somewhere that we need to make sure the returned error is retryable (perhaps above the two `return err` lines)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15330#-:-Kia9Fpp8HvlFZuthEHP:b-g2a5fb)*

**Comment by BramGruneir** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/server/testserver.go, line 522 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15330#-Kia8lEd-pXPlrYJW58-:-KiaXkQUeqE95A-f7Xp2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c44bb9c6d4583fbef09c439613ec154cdf00a6b/pkg/server/testserver.go#L522)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

+1 We should explain somewhere that we need to make sure the returned error is retryable (perhaps above the two `return err` lines)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15330)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/server/testserver.go, line 547 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15330#-KiaZjKZT-OEdAzkQvPu:-KiaZjKZT-OEdAzkQvPv:bl6udyz) ([raw file](https://github.com/cockroachdb/cockroach/blob/22dc0f17e24f21845f764d4c5d76539b847c02b3/pkg/server/testserver.go#L547)):*
> ```Go
> 		}
> 
> 		// Errors returned from scanMeta cannot be wrapped or retryable errors
> ```

please put this on `wrappedMsg`; this location seems prone to rotting to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15330)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15330#-:-Kia_YZ770rTh9_IWrae:bnfp4nl)*

**Comment by BramGruneir** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/server/testserver.go, line 547 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15330#-KiaZjKZT-OEdAzkQvPu:-KiadUfQg5i1E8e_sSpI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/22dc0f17e24f21845f764d4c5d76539b847c02b3/pkg/server/testserver.go#L547)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

please put this on `wrappedMsg`; this location seems prone to rotting to me.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15330)*

**Comment by andreimatei** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/server/testserver.go, line 560 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15330#-KiaklbOseCJ89ILOwW3:-KiaklbOseCJ89ILOwW4:be7f972) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e77071bc6dc4fbfe849c03e14c014474d57f247/pkg/server/testserver.go#L560)):*
> ```Go
> 		if err != nil {
> 			wrappedMsg = "could not look up left-hand side descriptor"
> 			return err
> ```

I suggest adding a `WrapIfNotRetryable` as a better pattern for wrapping errors inside a txn closure, rather than this ad-hoc thing. The wrap instinct was  good, except that retryable errors are not to be seen outside of the closure, so wrapping them would be meaningless (besides currently also breaking the handling of the closure result).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15330)*

**Pull request merged**
