### PR TITLE
rangefeed: handle closed timestamps with logical parts

### LINKED ISSUE #61176: roachtest: cdc/poller/rangefeed=false failed
[(roachtest).cdc/poller/rangefeed=false failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2721381&tab=buildLog) on [master@6601d827b814d4e85a1081b03bf2562d8ac2a4ab](https://github.com/cockroachdb/cockroach/commits/6601d827b814d4e85a1081b03bf2562d8ac2a4ab):

```
		  | (1) signal: killed
		  | Error types: (1) *exec.ExitError
		Wraps: (5) context canceled
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *main.withCommandDetails (4) *secondary.withSecondaryError (5) *errors.errorString

	cluster.go:2688,cdc.go:207,cdc.go:611,test_runner.go:767: monitor failure: unexpected node event: 3: dead
		(1) attached stack trace
		  -- stack trace:
		  | main.(*monitor).WaitE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2676
		  | main.(*monitor).Wait
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2684
		  | main.cdcBasicTest
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cdc.go:207
		  | main.registerCDC.func3
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cdc.go:611
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:767
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1374
		Wraps: (2) monitor failure
		Wraps: (3) unexpected node event: 3: dead
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *errors.errorString

	cluster.go:1667,context.go:140,cluster.go:1656,test_runner.go:848: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-2721381-1614322964-28-n4cpu16 --oneshot --ignore-empty-nodes: exit status 1 4: skipped
		3: dead
		1: 5139
		2: 4856
		Error: UNCLASSIFIED_PROBLEM: 3: dead
		(1) UNCLASSIFIED_PROBLEM
		Wraps: (2) attached stack trace
		  -- stack trace:
		  | main.glob..func14
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1147
		  | main.wrap.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:271
		  | github.com/spf13/cobra.(*Command).execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:830
		  | github.com/spf13/cobra.(*Command).ExecuteC
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:914
		  | github.com/spf13/cobra.(*Command).Execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:864
		  | main.main
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1852
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:204
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1374
		Wraps: (3) 3: dead
		Error types: (1) errors.Unclassified (2) *withstack.withStack (3) *errutil.leafError

```

<details><summary>More</summary><p>

Artifacts: [/cdc/poller/rangefeed=false](https://teamcity.cockroachdb.com/viewLog.html?buildId=2721381&tab=artifacts#/cdc/poller/rangefeed=false)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Acdc%2Fpoller%2Frangefeed%3Dfalse.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by andreimatei**
Before this patch, the resolved timestamp computation code didn't handle
closed timestamps with logical parts properly. I believe we didn't use
to have such closed timestamps under "the old" closed timestamp
mechanism, and we also don't have with the "new one" [*]. Still,
the resolved timestamp should support them.

The trouble was when the resolved timestamp was tracking an intent at,
say, 11.0, with the closed timestamp at 10.2.
resolvedTimestamp.recompute() was doing FloorPrev(11)==10, and compared
that with the closed ts. It was freaking out when the FloorPrev was
going below the closed timestamp.
This patch rewords this logic to handle this case.

[*] Before #61559, the new closed ts code did sometimes close logical
timestamps - when we were trying to close above the lease expiration, we
were doing Backwards(leaseExpiration) (and leases with a logical
expiration are possible, although that seems separately dubious to me).
This case change in #61559, which added physical rounding to the
respective lease expiration.

Fixes #61176 - although I think the bug has gone back to hidden after #61559

Release note: None
Release justification: Sort of bug fix for new functionality. But more
importantly, this affords extra flexibility to 21.1 in dealing with
potential changes in 21.2.

### CODE REVIEW

**Review by nvb — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61662)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @miretskiy, and @tbg)

___
*[pkg/kv/kvserver/rangefeed/resolved_timestamp.go, line 221 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61662#-MVJQmyKB_RArY1wVev2:-MVJQmyKB_RArY1wVev3:b2nhx3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/b17fa7f8ca0ad6f1419ffc17fc434853fbef2bfb/pkg/kv/kvserver/rangefeed/resolved_timestamp.go#L221)):*
> ```Go
> 	}
> 	if rts.closedTS.Less(rts.resolvedTS) {
> 		panic(fmt.Sprintf("closed timestamp below resolved timestamp: %s <= %s",
> ```

`<`
___
*[pkg/kv/kvserver/rangefeed/resolved_timestamp.go, line 230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61662#-MVJQm-YEf7lZyubJ2vt:-MVJQm-YEf7lZyubJ2vu:bdb70q0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b17fa7f8ca0ad6f1419ffc17fc434853fbef2bfb/pkg/kv/kvserver/rangefeed/resolved_timestamp.go#L230)):*
> ```Go
> 	if txn := rts.intentQ.Oldest(); txn != nil {
> 		if txn.timestamp.LessEq(rts.resolvedTS) {
> 			panic(fmt.Sprintf("unresolved txn below resolved timestamp: %s <=%s",
> ```

equal to or below
___
*[pkg/kv/kvserver/rangefeed/resolved_timestamp.go, line 233 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61662#-MVJQq9SCJPmBaWtak7s:-MVJQq9SCJPmBaWtak7t:b-fw12xc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b17fa7f8ca0ad6f1419ffc17fc434853fbef2bfb/pkg/kv/kvserver/rangefeed/resolved_timestamp.go#L233)):*
> ```Go
> 				txn.timestamp, rts.resolvedTS))
> 		}
> 		// txn.timestamp cannot be resolved, so we need a lower timestamp.
> ```

s/we need/the resolved timestamp must be earlier/
___
*[pkg/kv/kvserver/rangefeed/resolved_timestamp.go, line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61662#-MVJR18iBgI84ZugpRfg:-MVJR18iBgI84ZugpRfh:b-5bsfth) ([raw file](https://github.com/cockroachdb/cockroach/blob/b17fa7f8ca0ad6f1419ffc17fc434853fbef2bfb/pkg/kv/kvserver/rangefeed/resolved_timestamp.go#L236)):*
> ```Go
> 		// txn.timestamp.Prev is dangerous to use, potentially having
> 		// Logical=MaxInt32. So, we do a FloorPrev, but that might be too much - it
> 		// might takes us down below the resolved timestamp (although that'd be
> ```

"the existing resolved timestamp"
___
*[pkg/kv/kvserver/rangefeed/resolved_timestamp.go, line 241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61662#-MVJRI_WCBc4NZNPJQm7:-MVJRI_WCBc4NZNPJQm8:b-kigzig) ([raw file](https://github.com/cockroachdb/cockroach/blob/b17fa7f8ca0ad6f1419ffc17fc434853fbef2bfb/pkg/kv/kvserver/rangefeed/resolved_timestamp.go#L241)):*
> ```Go
> 		// resolvedTS.
> 		txnTS := txn.timestamp.FloorPrev()
> 		txnTS.Forward(rts.resolvedTS)
> ```

I'm torn on this. I get why you did it (and it's a nice find!), but it's also a shame that the resolved timestamp computation is now stateful and path-dependent. It was quite nice to have the resolved timestamp be a simple function of the closed timestamp and the oldest active transaction.

I wonder if we can express this as a function of the closed timestamp instead of a function of the existing resolved timestamp. Is it sufficient to say something like:
```go
txnTS := txn.timestamp.Prev()
if txnTS.Less(newTS) {
    newTS = txn.timestamp.FloorPrev()
}
```
___
*[pkg/kv/kvserver/rangefeed/resolved_timestamp.go, line 242 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61662#-MVJQEBX66B_LNq0jZUv:-MVJQEBY2Blfherz3Dwk:b-c63miw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b17fa7f8ca0ad6f1419ffc17fc434853fbef2bfb/pkg/kv/kvserver/rangefeed/resolved_timestamp.go#L242)):*
> ```Go
> 		txnTS := txn.timestamp.FloorPrev()
> 		txnTS.Forward(rts.resolvedTS)
> 		if txnTS.Less(newTS) {
> ```

Is this just `newTS.Backward(txnTS)`?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61662)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/rangefeed/resolved_timestamp.go, line 221 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61662#-MVJQmyKB_RArY1wVev2:-MVMT2rH6S5Jh2JrPlI9:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b17fa7f8ca0ad6f1419ffc17fc434853fbef2bfb/pkg/kv/kvserver/rangefeed/resolved_timestamp.go#L221)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`<`
</blockquote></details>

done
___
*[pkg/kv/kvserver/rangefeed/resolved_timestamp.go, line 230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61662#-MVJQm-YEf7lZyubJ2vt:-MVMT9zO1IUOkgL_izAj:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b17fa7f8ca0ad6f1419ffc17fc434853fbef2bfb/pkg/kv/kvserver/rangefeed/resolved_timestamp.go#L230)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

equal to or below
</blockquote></details>

done
___
*[pkg/kv/kvserver/rangefeed/resolved_timestamp.go, line 233 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61662#-MVJQq9SCJPmBaWtak7s:-MVMTG9H05LsVI6x5bxr:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b17fa7f8ca0ad6f1419ffc17fc434853fbef2bfb/pkg/kv/kvserver/rangefeed/resolved_timestamp.go#L233)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

s/we need/the resolved timestamp must be earlier/
</blockquote></details>

done
___
*[pkg/kv/kvserver/rangefeed/resolved_timestamp.go, line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61662#-MVJR18iBgI84ZugpRfg:-MVMTLZ-7MtgmJHKJ53x:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b17fa7f8ca0ad6f1419ffc17fc434853fbef2bfb/pkg/kv/kvserver/rangefeed/resolved_timestamp.go#L236)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"the existing resolved timestamp"
</blockquote></details>

done
___
*[pkg/kv/kvserver/rangefeed/resolved_timestamp.go, line 241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61662#-MVJRI_WCBc4NZNPJQm7:-MVMZi8I0-GGfvly7E8E:b-6ar8jq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b17fa7f8ca0ad6f1419ffc17fc434853fbef2bfb/pkg/kv/kvserver/rangefeed/resolved_timestamp.go#L241)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm torn on this. I get why you did it (and it's a nice find!), but it's also a shame that the resolved timestamp computation is now stateful and path-dependent. It was quite nice to have the resolved timestamp be a simple function of the closed timestamp and the oldest active transaction.

I wonder if we can express this as a function of the closed timestamp instead of a function of the existing resolved timestamp. Is it sufficient to say something like:
```go
txnTS := txn.timestamp.Prev()
if txnTS.Less(newTS) {
    newTS = txn.timestamp.FloorPrev()
}
```
</blockquote></details>

But your code introduces the resolved ts regression, doesn't it?
Imagine:
```
rts.resolvedTS (i.e. the old resolved) = 10.5
txn.timestamp = 11
newTS (i.e. closed ts) = 15

=>

txnTS = 10.Max
newTS = 10
```

What we can technically resolve in this situation is 10.Max. But if we don't want to do that (cause the Max part is dangerous), then we need memory about what we resolved before.

Or, an alternative is that we always truncate the resolved timestamps to not resolve logical time. But I don't know if I like it.
___
*[pkg/kv/kvserver/rangefeed/resolved_timestamp.go, line 242 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61662#-MVJQEBX66B_LNq0jZUv:-MVMbQ1yA8dJ62tYSy38:byxqxm7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b17fa7f8ca0ad6f1419ffc17fc434853fbef2bfb/pkg/kv/kvserver/rangefeed/resolved_timestamp.go#L242)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this just `newTS.Backward(txnTS)`?
</blockquote></details>

doneg difgit

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61662)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @miretskiy, and @tbg)

___
*[pkg/kv/kvserver/rangefeed/resolved_timestamp.go, line 241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61662#-MVJRI_WCBc4NZNPJQm7:-MVTdGtKCYBUDvoJcYbn:b-yr5aer) ([raw file](https://github.com/cockroachdb/cockroach/blob/b17fa7f8ca0ad6f1419ffc17fc434853fbef2bfb/pkg/kv/kvserver/rangefeed/resolved_timestamp.go#L241)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

But your code introduces the resolved ts regression, doesn't it?
Imagine:
```
rts.resolvedTS (i.e. the old resolved) = 10.5
txn.timestamp = 11
newTS (i.e. closed ts) = 15

=>

txnTS = 10.Max
newTS = 10
```

What we can technically resolve in this situation is 10.Max. But if we don't want to do that (cause the Max part is dangerous), then we need memory about what we resolved before.

Or, an alternative is that we always truncate the resolved timestamps to not resolve logical time. But I don't know if I like it.
</blockquote></details>

Yeah, you're completely right. We need some kind of memory if we're not ok with truncating the resolve timestamp's logical portion entirely. I do wonder how much of a problem that would be. We're already ok with truncating the resolved timestamp's logical portion when it comes from an intent, so why are things different when it comes from the closed timestamp? Especially because you don't seem to like closed timestamps with logical portions anyway.

It does seem like a simpler and less fragile solution. We could revert most of the changes in this method, switch from FloorPrev to Prev, and then set `newTs.Logical=0` right before performing the comparison.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61662)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/rangefeed/resolved_timestamp.go, line 241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61662#-MVJRI_WCBc4NZNPJQm7:-MVTlER_6XSctDfKWVPn:b-ncf8t6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b17fa7f8ca0ad6f1419ffc17fc434853fbef2bfb/pkg/kv/kvserver/rangefeed/resolved_timestamp.go#L241)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, you're completely right. We need some kind of memory if we're not ok with truncating the resolve timestamp's logical portion entirely. I do wonder how much of a problem that would be. We're already ok with truncating the resolved timestamp's logical portion when it comes from an intent, so why are things different when it comes from the closed timestamp? Especially because you don't seem to like closed timestamps with logical portions anyway.

It does seem like a simpler and less fragile solution. We could revert most of the changes in this method, switch from FloorPrev to Prev, and then set `newTs.Logical=0` right before performing the comparison.
</blockquote></details>

agreed. See noe.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61662#-:-MVUdTQp5kqUreXApcwM:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @miretskiy, and @tbg)

___
*[pkg/kv/kvserver/rangefeed/resolved_timestamp.go, line 241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61662#-MVJRI_WCBc4NZNPJQm7:-MVUd8iE5jCLj_vtiv9g:b-xeoyic) ([raw file](https://github.com/cockroachdb/cockroach/blob/b17fa7f8ca0ad6f1419ffc17fc434853fbef2bfb/pkg/kv/kvserver/rangefeed/resolved_timestamp.go#L241)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

agreed. See noe.
</blockquote></details>

I guess the new assertions are fine, but I think we should also bring back the `if newTS.Less(rts.resolvedTS) {` assertion as a final sanity check that the resolved timestamp is never regressing.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61662)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @miretskiy, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/rangefeed/resolved_timestamp.go, line 241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61662#-MVJRI_WCBc4NZNPJQm7:-MVX8RD04o948X97bsOm:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b17fa7f8ca0ad6f1419ffc17fc434853fbef2bfb/pkg/kv/kvserver/rangefeed/resolved_timestamp.go#L241)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I guess the new assertions are fine, but I think we should also bring back the `if newTS.Less(rts.resolvedTS) {` assertion as a final sanity check that the resolved timestamp is never regressing.
</blockquote></details>

done

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61662#-:-MVXVUM_4c49MGwmgEev:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @miretskiy, @nvanbenschoten, and @tbg)

**Pull request merged**
