### PR TITLE
roachtest: fetch dmesg also in local runs

### PR DESCRIPTION
**Pull request by tbg**
Over the last few weeks, we've regularly seen test failures in local
mode (i.e. acceptance) in which a `*monitor` claims that a node is dead,
without evidence in the logs. One explanation for this is OOM killing,
so make sure we fetch dmesg in local runs to be able to look into this.

Touches #47325.

Release note: None

### CODE REVIEW

**Review by irfansharif — APPROVED** [review]
LGTM, looks like this CI run was able to tickle the same opaque version-upgrade failure we were discussing yesterday, though the dmesg files seem to be empty. Is that expected after this patch?

**Comment by tbg** [comment]
```
10:49:17 cluster.go:380: > /go/src/github.com/cockroachdb/cockroach/bin/roachprod ssh local -- /bin/bash -c 'sudo -n dmesg > dmesg.txt'
local: /bin/bash -c 'sudo -n dmesg...
   1: /bin/bash: sudo: command not found
COMMAND_PROBLEM: exit status 127
   2: /bin/bash: sudo: command not found
COMMAND_PROBLEM: exit status 127
   3: /bin/bash: sudo: command not found
COMMAND_PROBLEM: exit status 127
   4: /bin/bash: sudo: command not found
COMMAND_PROBLEM: exit status 127
Error: COMMAND_PROBLEM: exit status 127
(1) COMMAND_PROBLEM
```

I'll see what can be done on these machines.

**Comment by tbg** [comment]
Hm. This just works on the agents:

```
agent@gce-agent-20200709-no-preempt-12:~/work/.go/src/github.com/cockroachdb/cockroach$ ./bin/roachprod ssh local:1 sudo echo hi
hi
```

teamcity-acceptance.sh has an additional `env` invocation and goes through `go test`, but at least the former doesn't seem to "hide" sudo. Hmm.

**Comment by tbg** [comment]
Oh, ok, this ends up running inside of a `builder.sh`. Hmm. Nothing good can come out of this then, it's not like you can read the system's dmesg from inside the builder.

**Comment by tbg** [comment]
Hmm I don't know where to go from here. We are running the whole thing in builder.sh because we kind of have to. We build `roachtest` through the builder, so it won't run on the host machine (we don't link it using the proper cross-compile buildchain and it's not obvious how to invoke it in that way).

I do feel like running local roachtest from within a builder is a bad idea for many reasons. We need to do something.

**Pull request closed without merging**
