### PR TITLE
storage/simulation: move to cmd

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10742)

### CODE REVIEW

**Comment by BramGruneir** [comment]
Why are we avoiding os.Exit?

LGTM

**Comment by petermattis** [comment]
Should we bother keeping this around. I turn to `allocsim` when I need to testing allocator behavior. @BramGruneir?

**Comment by BramGruneir** [comment]
I'd be down with removing it entirely.  I've only used it recently to ensure that we don't create rebalance cycles.

**Comment by tamird** [comment]
On reconsideration I've reverted the changes from fmt to log; this just moves things to cmd now.

**Pull request merged**
