### PR TITLE
build: add 'make coveralls' to upload code coverage to Coveralls

### PR DESCRIPTION
**Pull request by d4l3k**
This is for nightly code coverage builds in teamcity.

https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_Coverage_Coverage

https://coveralls.io/github/cockroachdb/cockroach

Most of this code was written by @nvanbenschoten  https://github.com/cockroachdb/cockroach/commit/c97dc5a61db8d8733caf66b97125382d097f7dd1.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7952)

### CODE REVIEW

**Comment by jordanlewis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[build/coveralls.sh, line 2 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7952#-KN9Vd5xo3-IokJ7PVfA:-KN9Vd5xo3-IokJ7PVfB:-1778081128) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff5b0684ec1d4eddaed5111a4f01220446beaaa5/build/coveralls.sh#L2)):*
> ```Shell
> if [ -n "${CIRCLE_ARTIFACTS-}" ]; then
>   outdir="${CIRCLE_ARTIFACTS}"
> ```

I don't see any value in saving these results as artifacts if we're going to upload them to coveralls as well - I think it'll just eat up disk space for no reason. Do we care about looking at the raw output of the coverage report?

---

*[build/coveralls.sh, line 35 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7952#-KN9VtJ39jdehgrNLuxL:-KN9VtJ39jdehgrNLuxM:1745025851) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff5b0684ec1d4eddaed5111a4f01220446beaaa5/build/coveralls.sh#L35)):*
> ```Shell
>     -ignore='*/*.pb.go,*/*/*.pb.go' \
>     -service=teamcity \
>     -repotoken=$COVERALLS_TOKEN
> ```

Can you make this script die if this token doesn't exist?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7952)*

**Comment by jordanlewis** [comment]
LGTM besides some minor comments. Thanks!

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7952#-:-KN9VzAcL4RDRu0Cx8RB:373898569)*

**Comment by d4l3k** [comment]
I just updated the command to generate coverage profiles spanning across packages. I'm slightly worried that it'll take too long since the go tool recompiles all specified packages when provided with `-coverpkg a,b,...`.

I added a check to make sure there are test files before running tests for that package.

You can also improve performance by only generating coverage for the dependencies of those packages, however, the tool we're using (https://github.com/wadey/gocovmerge) doesn't support merging different sets of source code. 

The general rule of thumb that I'm seeing is it adds 1m of time per package.
```
ok  	github.com/cockroachdb/cockroach/gossip/resolver	0.175s

real	0m57.770s
user	1m54.235s
sys	0m17.831s
```

It's probably fine since it's running once a day during the night.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[build/coveralls.sh, line 2 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7952#-KN9Vd5xo3-IokJ7PVfA:-KND0j9yICHqIGHooMcX:122022178) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff5b0684ec1d4eddaed5111a4f01220446beaaa5/build/coveralls.sh#L2)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary>
> I don't see any value in saving these results as artifacts if we're going to upload them to coveralls as well - I think it'll just eat up disk space for no reason. Do we care about looking at the raw output of the coverage report?
</details>
The raw report could be useful at other times since you can use it with `go tool cover`, but it's probably not needed. Removed.

---

*[build/coveralls.sh, line 35 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7952#-KN9VtJ39jdehgrNLuxL:-KND1-hMVeO87MSfpu4D:-14586563) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff5b0684ec1d4eddaed5111a4f01220446beaaa5/build/coveralls.sh#L35)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary>
> Can you make this script die if this token doesn't exist?
</details>
Dies early now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7952#-:-KND13uURKef_V7EdRMs:-803227224)*

**Comment by d4l3k** [comment]
On CI that's looking like 2-3m compile time per package.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7952#-:-KND4d7mDmbACfLP83mR:-73589309)*

**Comment by jordanlewis** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7952#-:-KNDEaIn7n5oPPLy7qUy:1417088721)*

**Pull request merged**
