### PR TITLE
[wip] sql: add pushdown to virtual tables

### PR DESCRIPTION
**Pull request by jordanlewis**
This commit adds the capability to push filters down into virtual
tables, by exposing "indexes" on virtual tables that are implemented by
populate functions that take exact constraints on the index's prefix.

It also has an example of what you'd have to do per-table on the execution 
side, in the pg_constraint table.

This is a work in progress, I'm looking for feedback. It adds a prototype of the execution capabilities, as well as some infrastructure within the optimizer, but it's missing the exploration rule that turns filters into constraints.

The reason I stopped working on it here was that I was about to introduce a whole bunch of code duplication for that exploration rule, and I've already introduced a decent chunk, so I wanted to step back and ask for feedback. Do you think we should try to unify some things between VirtualScanExpr and ScanExpr? I wasn't exactly sure how to do it, but I think we could probably get pretty far by having the virtual tables and indexes pretend to be ordinary tables and indexes in most respects.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
To unify them, ideally all virtual tables would present a primary index and the virtual table scan in the exec factory would support arbitrary spans. If we had those, I don't think we'd need a different VirtualScan operator at all.

Note that arbitrary span support could be "emulated" in the exec factory - it would extract the exact prefix and convert the rest of the spans to regular filters (and put them in a filterNode). Then in the future the exec operator can become more sophisticated (e.g. allowing range scans) without opt changes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42908#-:-LvBYnC97EY-rkIRylUV:b9oz50y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

**Comment by jordanlewis** [comment]
I see, I like that idea. I don't think it's going to be hard to do it, so I'll give it a try.

The main hiccup is that the primary index that we expose is weird - it won't have any columns in the index, which I'm sure not about - is that a valid state for things? Or maybe we could introduce a fake column, but then nobody would be able to query based on it, unlike rowid...

**Comment by RaduBerinde** [comment]
I was thinking about that. Having no columns is not really valid because there's no correct thing to return for `KeyColumnCount` and `LaxKeyColumnCount`. This API assumes that the prefix of all columns form a key.

I think having a hidden column (similar to `rowid`) makes more sense. We could extend `Column.IsHidden()` to return a tri-state (visible, hidden but selectable, completely hidden).

**Review by rytaft — COMMENTED** [review]
Sorry for the delay, don't have much to add beyond what Radu said. Left a few comments, but feel free to ignore them since I know this is still in progress.

I still think it's worth investigating how hard it would be to represent the virtual tables as views, but if that's not possible, this seems like a good approach. I like Radu's idea of trying to unify `Scan` and `VirtualScan` so we can avoid duplication.

> Reviewed 10 of 13 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42908#-:-LvMj2NV1ZQrOynVHWeq:bsv495z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/create_table.go, line 1139 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42908#-LvM_wWaDoY3p87biL21:-LvM_wWb2f8gB2FKgQFq:bmjtgcd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d897f5dd87b1041f4d4781ee6f182ae974e33f2/pkg/sql/create_table.go#L1139)):*
> ```Go
> 				return desc, unimplemented.NewWithIssue(9148, "use CREATE INDEX to make interleaved indexes")
> 			}
> 			fmt.Printf("%+v\n", idx)
> ```

stray debug line
___
*[pkg/sql/opt_catalog.go, line 1233 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42908#-LvMaEFDCrNAdWKQOxv5:-LvMaEFF2Hw4_3iPzjl_:bakr6uq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d897f5dd87b1041f4d4781ee6f182ae974e33f2/pkg/sql/opt_catalog.go#L1233)):*
> ```Go
> 	// colMap is a mapping from unique ColumnID to column ordinal within the
> 	// table. This is a common lookup that needs to be fast.
> 	colMap map[sqlbase.ColumnID]int
> ```

consider using `util.FastIntMap`?
___
*[pkg/sql/opt_catalog.go, line 1298 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42908#-LvMd5_m4j2_Z5O8zBvf:-LvMd5_m4j2_Z5O8zBvg:bwd2fmp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d897f5dd87b1041f4d4781ee6f182ae974e33f2/pkg/sql/opt_catalog.go#L1298)):*
> ```Go
> 		}
> 
> 		fmt.Println("Making index", ot.desc.Name, idxDesc.Name, idxDesc.ColumnNames, idxDesc.StoreColumnNames)
> ```

more debug stuff
___
*[pkg/sql/opt_catalog.go, line 1528 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42908#-LvMeoM58cJSF-dL-hFq:-LvMeoM58cJSF-dL-hFr:ble37y2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d897f5dd87b1041f4d4781ee6f182ae974e33f2/pkg/sql/opt_catalog.go#L1528)):*
> ```Go
> 	length := len(oi.desc.ColumnIDs)
> 	if i < length {
> 		ord, _ := oi.tab.lookupColumnOrdinal(oi.desc.ColumnIDs[i])
> ```

Are you sure you don't need to check the error? If so, maybe the `lookupColumnOrdinal` function should just panic instead of return an error.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 893 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42908#-LvMi_TN2-hA9GV16VAd:-LvMi_TN2-hA9GV16VAe:bg2yvza) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d897f5dd87b1041f4d4781ee6f182ae974e33f2/pkg/sql/opt/xform/custom_funcs.go#L893)):*
> ```Go
> 	md := c.e.mem.Metadata()
> 	index := md.Table(tabID).Index(indexOrd)
> 	fmt.Println("Index:", index.Name(), index.ID(), index.Ordinal(), index.ColumnCount(), index.Column(0))
> ```

debug line
___
*[pkg/sql/opt/xform/custom_funcs.go, line 904 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42908#-LvMia_K9Bm9eVUDPLG6:-LvMia_K9Bm9eVUDPLG7:bg2yvza) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d897f5dd87b1041f4d4781ee6f182ae974e33f2/pkg/sql/opt/xform/custom_funcs.go#L904)):*
> ```Go
> 			return true
> 		}
> 		fmt.Println("Did not contain fic", filterProps.OuterCols, firstIndexCol)
> ```

debug line

**Comment by jordanlewis** [comment]
Sorry to make you review all this debug code, I should have un-requested the review - I have turned this branch into just a place to experiment for the time being. Thanks for the feedback!

**Comment by jordanlewis** [comment]
Closing this in favor of some separate PRs to come.

**Pull request closed without merging**
