### PR TITLE
release-22.2: go.mod: use the crdb fork for etcd

### PR DESCRIPTION
**Pull request by pav-kv**
In order to cherry-pick bug fixes from upstream etcd-io/raft, use our fork. The fixes will be manually added because the etcd/raft has migrated to its own repo at etcd-io/raft.

Release justification: necessary to cherry-pick a bug fix from upstream
Epic: None
Release note: None

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]

**Comment by pavelkalinnikov** [comment]
Couldn't get `go mod tidy` to succeed:

```
...
github.com/cockroachdb/cockroach/pkg/kv/kvnemesis imports
        github.com/cockroachdb/cockroach/pkg/kv/kvnemesis/kvnemesisutil: no matching versions for query "latest"
github.com/cockroachdb/cockroach/pkg/sql/plpgsql/parser imports
        github.com/cockroachdb/cockroach/pkg/sql/sem/plpgsqltree: no matching versions for query "latest"
github.com/cockroachdb/cockroach/pkg/ccl/kvccl/kvtenantccl/upgradeinterlockccl tested by
        github.com/cockroachdb/cockroach/pkg/ccl/kvccl/kvtenantccl/upgradeinterlockccl.test imports
        github.com/cockroachdb/cockroach/pkg/ccl/kvccl/kvtenantccl/upgradeinterlockccl/sharedtestutil: no matching versions for query "latest"

```

**Review by tbg — APPROVED** [review]
Not sure about the go mod issues. Maybe dev-inf can help us?

**Comment by pavelkalinnikov** [comment]
@tbg @erikgrinaker Could you take another look? I updated deps in `vendor`. For now this should point at our fork at the same hash.

**Review by erikgrinaker — APPROVED** [review]
LGTM

**Comment by pavelkalinnikov** [comment]
bors r=erikgrinaker,tbg

**Pull request merged**
