### PR TITLE
direct GC of Txn and Sequence entries

### PR DESCRIPTION
**Pull request by tbg**
upon resolving successfully all the external intents
of a transaction on EndTransaction, the transaction
record and the sequence cache entries are deleted
asynchronously.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3140)

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM


---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

<sup>**[storage/gc_queue.go, line 254 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3140#-K3HDMOMZuAAlvQUo82c)** ([raw file](https://github.com/cockroachdb/cockroach/blob/382fc7d548b4db9243e22faf35cf9964ae9ac213/storage/gc_queue.go#L254)):</sup>
s/sync/wait/ (or change everything in the other direction, but both "sync" and "wait" are currently used)


---

<sup>**[storage/replica.go, line 1469 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3140#-K3HDGMr8rKLj66Z0-g5)** ([raw file](https://github.com/cockroachdb/cockroach/blob/382fc7d548b4db9243e22faf35cf9964ae9ac213/storage/replica.go#L1469)):</sup>
s/sync/wait/


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3140)

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[storage/replica.go, line 1546 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3140#-K3GtI513yKXa0fyRKmd)** ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f0b355a630eee2083154c593ca0b78c7ce407a/storage/replica.go#L1546)):</sup>
nope, it was used to carry the error to the outside when `sync=true`. I've refactored this so that the `action` returns an error for clarity.


---

<sup>**[storage/replica.go, line 1572 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3140#-K3GtVJvZjYOVPr6Oa2f)** ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f0b355a630eee2083154c593ca0b78c7ce407a/storage/replica.go#L1572)):</sup>
ditto back.


---

<sup>**[storage/replica_test.go, line 2016 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3140#-K3GtdrQ3m2-EONEOwuW)** ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f0b355a630eee2083154c593ca0b78c7ce407a/storage/replica_test.go#L2016)):</sup>
this needs to be outside of where the store may be running.


---

<sup>**[storage/replica_test.go, line 2107 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3140#-K3GuB7lOsH7Q2F4zpwZ)** ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f0b355a630eee2083154c593ca0b78c7ce407a/storage/replica_test.go#L2107)):</sup>
reworded.


---

<sup>**[storage/replica_test.go, line 1930 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3140#-K3GuVig-L0esr_-pcmz)** ([raw file](https://github.com/cockroachdb/cockroach/blob/382fc7d548b4db9243e22faf35cf9964ae9ac213/storage/replica_test.go#L1930)):</sup>
the AfterTest line needs to be first in the tests (it's linted).


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3140)

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[storage/replica_test.go, line 2016 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3140#-K3GtdrQ3m2-EONEOwuW)** ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f0b355a630eee2083154c593ca0b78c7ce407a/storage/replica_test.go#L2016)):</sup>
Sorry, I meant "move this up so it's below `defer leaktest.AfterTest(t)`


---

<sup>**[storage/replica_test.go, line 1930 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3140#-K3GuVig-L0esr_-pcmz)** ([raw file](https://github.com/cockroachdb/cockroach/blob/382fc7d548b4db9243e22faf35cf9964ae9ac213/storage/replica_test.go#L1930)):</sup>
gah, i meant just after the aftertest


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3140)

**Comment by tschottdorf** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[storage/replica_test.go, line 2016 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3140#-K3GtdrQ3m2-EONEOwuW)** ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f0b355a630eee2083154c593ca0b78c7ce407a/storage/replica_test.go#L2016)):</sup>
I prefer to have it adjacent to where `TestingCommandFilter` is mutated, and that mandates the current position.


---

<sup>**[storage/replica_test.go, line 1930 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3140#-K3GuVig-L0esr_-pcmz)** ([raw file](https://github.com/cockroachdb/cockroach/blob/382fc7d548b4db9243e22faf35cf9964ae9ac213/storage/replica_test.go#L1930)):</sup>
same reason as for the other comment.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3140)

**Comment by tamird** [comment]
Reviewed 3 of 4 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3140)

**Pull request merged**
