### PR TITLE
sql: column equivalency groups

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change adds equivalency groups to orderingInfo, replacing the multi-column
groups in ordering. This addresses a big limitation of the current structure - 
that we are not able to convey equivalency between columns that are not part of
the ordering. This will enable more optimizations, like setting equivalencies
between non-index columns according to filters.

Please ignore the first commit, it's a separate PR (#18461).

Because it's a non-trivial change, I don't plan on merging this for a couple of weeks but I wanted to get some early comments and give a heads-up to whomever might be working with `orderingInfo` code.

CC @arjunravinarayan in case you want to take a look at the changes related to merge-joins.

### CODE REVIEW

**Comment by knz** [comment]
I'll need a few days to review that.

**Comment by knz** [comment]
Okay so I reviewed this. All the code but one piece (a function called `project`) LGTM - I'll review `project` when I understand it. 

I have placed many requests to add comments and examples. A little bit to check my own understanding, but largely to ensure the next people working on this can re-discover the thinking from the ground up, using examples.

I find that the new data structure greatly improves readability of the code and the tests. Even if the concepts are a bit more "sophisticated" (hah!) than before, the maintainability is actually improved. It's quite good work!

---

Reviewed 24 of 24 files at r1.
Review status: all files reviewed at latest revision, 15 unresolved discussions, all commit checks successful.

---

*[pkg/sql/expand_plan.go, line 203 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI55xdQef9AxSG7v21:-KuI55xdQef9AxSG7v22:b-ez2xo3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/expand_plan.go#L203)):*
> ```Go
> 		if !ordering.isEmpty() {
> 			n.columnsInOrder = make([]bool, len(planColumns(n.plan)))
> 			for i := range n.columnsInOrder {
> ```

Add a comment here to explain what is going on.

---

*[pkg/sql/ordering.go, line 147 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI2CL2iiLKufgUn_4t:-KuI2CL2iiLKufgUn_4u:b-vznna0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/ordering.go#L147)):*
> ```Go
> // equivalency group representative and removing any columns that are redundant
> // (thanks to the physical properties). If no modifications are necessary,
> // returns the same slice.
> ```

Please add an example of elimination of a redundant column.

---

*[pkg/sql/ordering.go, line 211 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI2LutGeDGLpfgOHBH:-KuI2LutGeDGLpfgOHBI:b-t1a9p7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/ordering.go#L211)):*
> ```Go
> 
> 	firstGroup := true
> 	semiColon := func() {
> ```

Wow that's elegant. I'll remember that. Thanks for the trick.

---

*[pkg/sql/ordering.go, line 272 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI2Y4zsUkmur4eD6du:-KuI2Y4zsUkmur4eD6dv:bizgo3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/ordering.go#L272)):*
> ```Go
> }
> 
> func (ord *orderingInfo) addConstantColumn(colIdx int) {
> ```

Add a comment here and above which reminds the reader why the key property disappears when the ordering info is eliminated.

---

*[pkg/sql/ordering.go, line 328 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI34XMJJwFfSMkB7A4:-KuI34XMJJwFfSMkB7A5:b1tgvoa) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/ordering.go#L328)):*
> ```Go
> //
> // The map allows arbitrary remapping of columns for cases where projected
> // columns are intermingled with rendered expressions.
> ```

I'm sorry I do not understand what this function does - neither what you intended it to do.
Could you please explain a bit more (either here as a review comment or in the code comment) what the intent is, perhaps with examples. 

Also remind the reader where the colMap is computed and what the -1 special value represents.

---

*[pkg/sql/ordering.go, line 456 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI42OGKlLMiWIl7WUp:-KuI42OGKlLMiWIl7WUq:b-ehl07v) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/ordering.go#L456)):*
> ```Go
> //   before := ord.computeMatch(desired)
> //   ord.trim(desired)
> //   after := ord.computeMatch(desired)
> ```

Extend this comment to explain what happens with the isKey property and why.

---

*[pkg/sql/ordering.go, line 603 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI4QRgcsNwERyI9DZ4:-KuI4QRgcsNwERyI9DZ5:bc03hh0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/ordering.go#L603)):*
> ```Go
> 		// See if any column in the first group in A is "seen" in B. Or, if
> 		// we consumed B and it is a "key", then we are free to add any other
> 		// columns in A.
> ```

Add an example in the comment.

---

*[pkg/sql/ordering.go, line 618 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI4RuDRnetwxOfRKqz:-KuI4RuDRnetwxOfRKr-:b-rqxvo7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/ordering.go#L618)):*
> ```Go
> 		// See if any column in the first group in B is "seen" in A. Or, if
> 		// we consumed A and it is a "key", then we are free to add any other
> 		// columns in B.
> ```

ditto.

---

*[pkg/sql/ordering_test.go, line 316 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI0umy6Ein1Ti363vf:-KuI0umy6Ein1Ti363vg:bz5a14s) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/ordering_test.go#L316)):*
> ```Go
> 	for _, ts := range testSets {
> 		for _, tc := range ts.cases {
> 			t.Run(fmt.Sprintf("line%d", tc.line), func(t *testing.T) {
> ```

nit: t.Parallel()

---

*[pkg/sql/ordering_test.go, line 348 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI0_rnfs0W42ZOlsEC:-KuI0_rnfs0W42ZOlsED:b-a9kpy2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/ordering_test.go#L348)):*
> ```Go
> 			for _, numOrderCols := range []int{0, 1, 2, 4, 7} {
> 				for _, isKey := range []bool{false, true} {
> 					for tries := 0; tries < 20; tries++ {
> ```

nit: these could use sub-tests and t.Parallel()

---

*[pkg/sql/ordering_test.go, line 507 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI0lSrsC9EnepmXbn2:-KuI0lSrsC9EnepmXbn3:bz5a14s) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/ordering_test.go#L507)):*
> ```Go
> 
> 	for _, tc := range testCases {
> 		t.Run(tc.name, func(t *testing.T) {
> ```

nit: t.Parallel()

---

*[pkg/sql/ordering_test.go, line 700 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI0opD-A0imTxar6mE:-KuI0opD-A0imTxar6mF:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/ordering_test.go#L700)):*
> ```Go
> 	}
> 	for _, tc := range testCases {
> 		t.Run(tc.name, func(t *testing.T) {
> ```

ditto

---

*[pkg/sql/ordering_test.go, line 758 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI0qX9qqGGC4DgLaDj:-KuI0qXASPKDx8E8H90s:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/ordering_test.go#L758)):*
> ```Go
> 	}
> 	for tIdx, tc := range testCases {
> 		t.Run(fmt.Sprintf("%d", tIdx), func(t *testing.T) {
> ```

ditto

---

*[pkg/sql/render.go, line 591 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI0-1wPloxAIxtfIXZ:-KuI0-1wPloxAIxtfIX_:bt6vwbq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/render.go#L591)):*
> ```Go
> 	r.ordering = orderingInfo{}
> 
> 	projMap := make([]int, len(r.sourceInfo[0].sourceColumns))
> ```

Write a comment above this block of code with an example SQL query that causes an equivalency group to be created.

---

*[pkg/sql/render.go, line 598 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI-tiqoi6HFUyuBmt3:-KuI-tirMPvtANlWrj7A:bzbgo1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/render.go#L598)):*
> ```Go
> 		if ivar, ok := expr.(*parser.IndexedVar); ok {
> 			// Column ivar.Idx of the source becomes column i of the render node.
> 			projMap[ivar.Idx] = i
> ```

`break`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-:-KuI5WlscJOk0EImgY9g:b-f5kxsc)*

**Comment by RaduBerinde** [comment]
Thanks for the review! I'm glad you like it overall! I will gladly make the
suggested improvements when I get back.

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions, all commit checks successful.

---

*[pkg/sql/expand_plan.go, line 203 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI55xdQef9AxSG7v21:-KvTZAOzkPLEyYp7RlI0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/expand_plan.go#L203)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Add a comment here to explain what is going on.
</blockquote></details>

Done.

---

*[pkg/sql/ordering.go, line 147 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI2CL2iiLKufgUn_4t:-KvTZihq5i1TzxZBHUHH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/ordering.go#L147)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please add an example of elimination of a redundant column.
</blockquote></details>

Done.

---

*[pkg/sql/ordering.go, line 272 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI2Y4zsUkmur4eD6du:-KvT_2xRvD19GwNKkPJj:b-awlnbs) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/ordering.go#L272)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Add a comment here and above which reminds the reader why the key property disappears when the ordering info is eliminated.
</blockquote></details>

Added a TODO, this is a limitation of the current representation (I have another PR out for generalizing keys).

---

*[pkg/sql/ordering.go, line 328 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI34XMJJwFfSMkB7A4:-KvTab4D0yH9GWDnyo3u:b-c7qlje) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/ordering.go#L328)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'm sorry I do not understand what this function does - neither what you intended it to do.
Could you please explain a bit more (either here as a review comment or in the code comment) what the intent is, perhaps with examples. 

Also remind the reader where the colMap is computed and what the -1 special value represents.
</blockquote></details>

Indeed, I had to think for a while to remember what's going on. While working on the comment I realized it doesn't neatly handle cases where we project a column multiple times (e.g. `SELECT a, b, a FROM t`), which required a bit of a hack in `renderNode.computeOrdering`; I reversed the way the map works and reworked the method. I hope it's clearer now.

---

*[pkg/sql/ordering.go, line 456 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI42OGKlLMiWIl7WUp:-KvTpNvieDDQ0NmKOF4C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/ordering.go#L456)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Extend this comment to explain what happens with the isKey property and why.
</blockquote></details>

Done.

---

*[pkg/sql/ordering.go, line 603 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI4QRgcsNwERyI9DZ4:-KvTxRv2FsqP2MyD1FTy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/ordering.go#L603)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Add an example in the comment.
</blockquote></details>

Done.

---

*[pkg/sql/ordering.go, line 618 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI4RuDRnetwxOfRKqz:-KvTxSUnjUyw9OuOBsC2:b-qkkyi5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/ordering.go#L618)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Just mentioned it's symmetric (the example would be the same, with A and B swapped)

---

*[pkg/sql/ordering_test.go, line 316 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI0umy6Ein1Ti363vf:-KvTnNQNmTHHOkzvMpCt:bt2jiz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/ordering_test.go#L316)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: t.Parallel()
</blockquote></details>

Done. Though I can't say I'm happy with the change, these tests are very fast so it doesn't make a difference and `Parallel` introduces some subtle headaches (can't use loop vars like `ts`, `tc` directly inside Run anymore).

---

*[pkg/sql/ordering_test.go, line 348 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI0_rnfs0W42ZOlsEC:-KvTnMvrzIHt2uKsB4pZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/ordering_test.go#L348)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: these could use sub-tests and t.Parallel()
</blockquote></details>

Done.

---

*[pkg/sql/ordering_test.go, line 507 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI0lSrsC9EnepmXbn2:-KvTmz26aOxHGLyxjZJ2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/ordering_test.go#L507)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: t.Parallel()
</blockquote></details>

Done.

---

*[pkg/sql/ordering_test.go, line 700 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI0opD-A0imTxar6mE:-KvTn-8QZJWFnUkrUGfW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/ordering_test.go#L700)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

---

*[pkg/sql/ordering_test.go, line 758 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI0qX9qqGGC4DgLaDj:-KvTxYfjIH2mCFRkds-Z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/ordering_test.go#L758)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

---

*[pkg/sql/render.go, line 591 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI0-1wPloxAIxtfIXZ:-KvTyG3sWqMCQK4Y6oDO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/render.go#L591)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Write a comment above this block of code with an example SQL query that causes an equivalency group to be created.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/expand_plan.go, line 203 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-KuI55xdQef9AxSG7v21:-KvXgb2HbXVg-H6M-dxP:b-vmyd17) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa92e06925d840f763c8b4b8b5d665b63ea6c34/pkg/sql/expand_plan.go#L203)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks, much clearer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18475#-:-KvXhXJxMJvWbaDW3Qfs:bnfp4nl)*

**Pull request merged**
