### PR TITLE
Switch to secure distroless Docker image

### PR DESCRIPTION
**Pull request by hazcod**
Since there is no point in having a shell and/or libraries in a container that we don't use, these should not be included to vastly reduce the attack surface.

Google publishes the so-called 'distroless' Docker images that only contain the necessary.

I even go a bit further in https://github.com/ironPeakServices/iron-cockroachdb/blob/master/Dockerfile where I use a static build of cockroachdb, so glibc is pulled in from the build toolchain.

### CODE REVIEW

**Comment by bdarnell** [comment]
I like the idea of using distroless as a base system. We've looked at this before and one problem is that it's missing the terminfo database, which limits the functionality of `cockroach sql` when run from this docker image. That's not critical (it's primarily a server image, after all), but we also use this image as a simple way to run the client. It would be nice to have a docker image with terminfo, either in the main image or maybe a separate client-oriented image that's not as locked down and includes terminfo.

What's the backwards-compatibility impact of the `USER` change? If someone was using this image before, would it be writing files that they wouldn't be able to read after the upgrade? 

There are other backwards-compatibility breaks here too. [Our k8s configs](https://github.com/cockroachdb/cockroach/blob/1e62ef12ef3bccfa50f3133a4f5fd3e56afd7eee/cloud/kubernetes/cockroachdb-statefulset-secure.yaml#L229) hard-code the path as `/cockroach/cockroach` (instead of `/cockroach` as you've changed it to) and rely on the existence of `/bin/bash` and `hostname`. 

Overall I'm not sure that the reduction in attack surface is worth the backwards-compatibility churn here.

**Comment by bdarnell** [comment]
We've since switched to `ubi8/ubi-minimal` for our base image and are no longer considering using distroless.

**Comment by hazcod** [comment]
@bdarnell can you elaborate on why that image?
I see it's 37.7 MB so curious why that for a static build.

**Comment by bdarnell** [comment]
A shell is sometimes useful; we use it in our k8s configurations for example. We need enough stuff that it doesn't make a lot of sense to push for absolute minimalism.

**Pull request closed without merging**
