### PR TITLE
security: set tenant's ServerName to tenant-%d

### PR DESCRIPTION
**Pull request by chrisseto**
Previously, tenant client TLS configs relied on standard
    verification. In CockroachCloud's Serverless deployment, tenant
    certificates do not contain IP SANs. This resulted in TLS
    verification errors as tenant <-> tenant connections were
    established via direct IP. This commit overrides the .ServerName of
    tenant client tls.Configs to allow successful verification without
    introducing DNS or continously re-minting certificates.

Release note (security update, backward-incompatible change): Tenant
server certificates must now include tenant-{TenantID} as a SAN.

### CODE REVIEW

**Review by mberhault — COMMENTED** [review]
You also need to add the tenant ID in https://github.com/cockroachdb/cockroach/blob/master/pkg/security/certs_tenant_test.go#L59

> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69002#-:-MhFVMVW7sUgvUPnt7UA:b-abpiyr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @catj-cockroach)

**Review by catj-cockroach — COMMENTED** [review]
> Reviewed 20 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69002)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chrisseto)

___
*[pkg/security/certificate_manager.go, line 999 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69002#-MhGE4R11KCbXBJu93xr:-MhGE4R11KCbXBJu93xs:b-pc28dq) ([raw file](https://github.com/cockroachdb/cockroach/blob/30d5cf373e36dd665f7c772ecffb8a476c76d2d0/pkg/security/certificate_manager.go#L999)):*
> ```Go
> 	// certificates for every Tenant server, they share the ServerName of
> 	// tenant-%d.
> 	cfg.ServerName = fmt.Sprintf("tenant-%d", cm.tenantIdentifier)
> ```

@chrisseto kindly walked me through the reasoning for this solution today, but I think I need to dig more into the code around this before I'm comfortable giving it an approval.

**Review by catj-cockroach — CHANGES_REQUESTED** [review]
Having looked over the code and reasoned about what it's doing, I want to discuss this further with you (@chrisseto) and see if we can find a solution that doesn't require overriding the ServerName.

**Comment by chrisseto** [comment]
Superseded by https://github.com/cockroachdb/cockroach/pull/69113

**Pull request closed without merging**
