### PR TITLE
catalog/lease: add metrics for tracking long lease waits

### LINKED ISSUE #119209: lease: add metrics for WaitFor{No|One}Version and twoVersionInvariantViolationError
**Is your feature request related to a problem? Please describe.**
As we roll out session-based leasing, we need a way to make sure the leasing system is healthy.

**Describe the solution you'd like**
Let's add histogram metrics for [WaitForNoVersion](https://github.com/cockroachdb/cockroach/blob/49592b71a3fbacb81a1381f8bc8bcb542b25247b/pkg/sql/catalog/lease/lease.go#L126) and [WaitForOneVersion](https://github.com/cockroachdb/cockroach/blob/49592b71a3fbacb81a1381f8bc8bcb542b25247b/pkg/sql/catalog/lease/lease.go#L174). These ones should be timer histograms, so we can see the count/rate these are called, as well as the duration we spend waiting.

Let's also add a counter metric for  the number of `twoVersionInvariantViolationError`s that occur.

**Describe alternatives you've considered**
Logs? Not good since they're more verbose.

Jira issue: CRDB-36093

Epic CRDB-35665

### PR DESCRIPTION
**Pull request by fqazi**
Previously, we had no way of knowing if WaitForOneVersion, WaitForNoVersion, or CheckTwoVersionInvariant, which wait for leases to expire are stuck. This becomes more problematic as we added migration to session-based leasing. If something goes wrong during this migration, there is a danger of schema changes hanging while waiting for leases to expire. To address this, this patch will add new metrics for detecting long waits in these code paths

Fixes: #119209

Release note: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119590)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/catalog/descs/leased_descriptors.go` line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119590#-Nrqsp3R7e97D7ueOckB:-Nrqsp3R7e97D7ueOckC:b-fzz8q5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b1fc4a26c9d963c073b42b07279f6c6261fceab/pkg/sql/catalog/descs/leased_descriptors.go#L40)):*
> ```Go
> 	) (lease.LeasedDescriptor, error)
> 
> 	IncTwoVersionWaitGaugeAfterLeaseDuration() func()
> ```

instead of making `incGaugeAfterLeaseDuration` a private function of `storage`, can we just keep this one here as the generalized function? (and add a comment)

this one can be renamed to `IncGaugeAfterLeaseDuration`
___
*[`pkg/sql/catalog/descs/txn.go` line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119590#-NrqxoRe1zRG_9HHtgrx:-NrqxoRe1zRG_9HHtgry:b-y4kkq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b1fc4a26c9d963c073b42b07279f6c6261fceab/pkg/sql/catalog/descs/txn.go#L137)):*
> ```Go
> 		}
> 	}
> 	return &twoVersionInvariantViolationError{
> ```

earlier we were thinking to return a count of two version invariant violations. should we still add that?
___
*[`pkg/sql/catalog/lease/lease.go` line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119590#-NrqujyT5i6U0ryYz7z4:-NrqujyT5i6U0ryYz7z5:b-hg5q9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b1fc4a26c9d963c073b42b07279f6c6261fceab/pkg/sql/catalog/lease/lease.go#L182)):*
> ```Go
> 		},
> 	}
> 	incLongWaitCleanup := m.storage.incGaugeAfterLeaseDuration(m.storage.longWaitForNoVersionsActive)
> ```

nit: rename `incLongWaitCleanup` to `decAfterWait` or `cleanupGauge` or something
___
*[`pkg/sql/catalog/lease/lease.go` line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119590#-Nrqwd2h-DfgyM06fJGY:-Nrqwd2h-DfgyM06fJGZ:b3wi0h3) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b1fc4a26c9d963c073b42b07279f6c6261fceab/pkg/sql/catalog/lease/lease.go#L226)):*
> ```Go
> ) (desc catalog.Descriptor, _ error) {
> 	incLongWaitCleanup := m.storage.incGaugeAfterLeaseDuration(m.storage.longWaitForOneVersionsActive)
> 	defer incLongWaitCleanup()
> ```

nit: rename to `decAfterWait` or `cleanupGauge` or something
___
*[`pkg/sql/catalog/lease/storage.go` line 384 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119590#-NrqxkQ7DYDP5cysjA_S:-NrqxkQ89jPOVWvC6lMi:b-lbr5qj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b1fc4a26c9d963c073b42b07279f6c6261fceab/pkg/sql/catalog/lease/storage.go#L384)):*
> ```Go
> 
> // incGaugeAfterLeaseDuration increments any wait metric after the lease duration
> // has passed. A function is returned to decrement the same metric after.
> ```

nit: this comment could be on the interface-level

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119590)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/catalog/descs/leased_descriptors.go` line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119590#-Nrqsp3R7e97D7ueOckB:-NrvXiwF-5iwmkRayHY0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b1fc4a26c9d963c073b42b07279f6c6261fceab/pkg/sql/catalog/descs/leased_descriptors.go#L40)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

instead of making `incGaugeAfterLeaseDuration` a private function of `storage`, can we just keep this one here as the generalized function? (and add a comment)

this one can be renamed to `IncGaugeAfterLeaseDuration`
</blockquote></details>

Done.
___
*[`pkg/sql/catalog/descs/txn.go` line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119590#-NrqxoRe1zRG_9HHtgrx:-NrvRzcKAgRljTbt1k1M:b-tnemd3) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b1fc4a26c9d963c073b42b07279f6c6261fceab/pkg/sql/catalog/descs/txn.go#L137)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

earlier we were thinking to return a count of two version invariant violations. should we still add that?
</blockquote></details>

I don't think its worth adding because its hard to filter noise, since any one holding leases during your schema change will cause those errors. Those waits being long are a better signal, and the active number on a cluster.
___
*[`pkg/sql/catalog/lease/storage.go` line 384 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119590#-NrqxkQ7DYDP5cysjA_S:-NrvSQBS7iEusgzRromB:bs7wumb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b1fc4a26c9d963c073b42b07279f6c6261fceab/pkg/sql/catalog/lease/storage.go#L384)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: this comment could be on the interface-level
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119590#-:-Ns9MrPT6Ba4VV7HkEs7:b-7nbn20)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/catalog/descs/leased_descriptors.go` line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119590#-Ns9MB-r5LH2xAoV7lkb:-Ns9MB-r5LH2xAoV7lkc:b6y824y) ([raw file](https://github.com/cockroachdb/cockroach/blob/2245529b16904a72c14bdf1eb3adb037bc73c6aa/pkg/sql/catalog/descs/leased_descriptors.go#L40)):*
> ```Go
> 	) (lease.LeasedDescriptor, error)
> 
> 	IncGaugeAfterLeaseDuration(
> ```

nit: this function could use a comment that mentions more details about how the gauge gets incremented with a timer. (you could use the comment you have on the function implementation)

**Comment by fqazi** [comment]
@rafiss TFTR!

**Pull request merged**
