### PR TITLE
build: publish build metadata as a part of Make and Publish Build

### LINKED ISSUE #137109: Publish build metadata as a part of Make and Publish Build
We already publish the build metadata as a part of release qualification in https://github.com/cockroachdb/cockroach/blob/1efb25591528b4335957985574351c6898ddf64f/build/release/teamcity-mark-build.sh#L42. Sometimes we need this information before the qualification test is finished.

Let's publish this metadata as a part of Make and Publish build as well, but to a different location, so we can distinguish them.

Jira issue: CRDB-45390

### PR DESCRIPTION
**Pull request by rail**
We already publish the build metadata as a part of release qualification. Sometimes we need this information before the qualification test is finished.

Let's publish this metadata as a part of Make and Publish build as well, but to a different location, so we can distinguish them.

Fixes: #137109
Release note: None

### CODE REVIEW

**Comment by rail** [comment]
Example custom build: https://teamcity.cockroachdb.com/buildConfiguration/Internal_Cockroach_Release_Customized_MakeAndPublishCustomizedBuild/18123627?buildTab=log&focusLine=2888&logView=flowAware&linesState=2849.2888

https://storage.googleapis.com/cockroach-release-qualification-test/builds/8c462427ca24c7404fde3d649b13feaff4b2e627.json

**Review by celiala — APPROVED** [review]
LGTM -- wooo! \o/ thank you!

**Comment by rail** [comment]
bors r=celiala

**Comment by rail** [comment]
I will proceed with the backports tomorrow, after the master branch build is ready.

**Pull request merged**
