### PR TITLE
backupccl: properly propagate error when failing to commit job txn

### PR DESCRIPTION
**Pull request by ajwerner**
This bug was introduced in 20.1. It means that any errors to commit the job
are not reported and instead an inscrutible error is reported.

```
 ERROR: cannot resume *backupccl.backupResumer job which is not committed
```

Release note (bug fix): Fixed a bug which lead to inscrutible errors being
returned when creating a backup failed, for example, due to protected timestamp
limits.

### CODE REVIEW

**Comment by adityamaru** [comment]
I believe `restore_planning` has the same "not returning err" bug, do you want me to push out a separate fix or will you include it in this PR?

**Comment by ajwerner** [comment]
I'll pick it up in this PR.

**Review by miretskiy — APPROVED** [review]

**Review by pbardea — APPROVED** [review]

**Comment by ajwerner** [comment]
Okay, added a second commit to deal with restore

**Comment by ajwerner** [comment]
bors r=pbardea,miretskiy

**Comment by dt** [comment]
yikes, it turns out this can actually crash process if it leaves `sj` nil and then calls `Start`

**Comment by shermanCRL** [comment]
Should we do some formatting while we’re in the neighborhood? I’d argue that’s one reason this was easy to miss. Maybe split out the func (the inline parameter) into a local variable, and a comment to point out that we close over `sj`.

**Pull request merged**
