### PR TITLE
sql: permit VISIBLE to be used as a table/col name

### LINKED ISSUE #70532: sql: VISIBLE is not usable as a table or column name without quoting
This is an incompatibility with Postgres, which allows VISIBLE to be used as a table or column name without quoting.

### PR DESCRIPTION
**Pull request by jordanlewis**
Closes #70532

Previously, VISIBLE had been mistakenly included in the reserved keyword
list, rendering it unusable for table and column names. This was
unnecessary.

Release note (sql change): "visible" is now usable as a table or column
name without extra quoting.

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
should we backport?

**Comment by jordanlewis** [comment]
Assuming tests pass, yes

**Pull request merged**
