### PR TITLE
sql: move jobs to own package; thread transactions through job operations

### PR DESCRIPTION
**Pull request by jordanlewis**
- Move the jobs API to its own package.
- Add an optional fluent API call to cause a jobLogger operation to occur in a transaction, e.g. `jobLogger.WithTxn(txn).Created()`
- Have schema changes use those transactional methods when appropriate

### CODE REVIEW

**Comment by benesch** [comment]
:lgtm:, but :woman_scientist: :dog: on the schema change transaction flow. Just a few nits below!

---

Reviewed 17 of 17 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: 11 of 13 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/jobs/jobs.go, line 131 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390#-Km3Td2b2LssaBNy0MwI:-Km3Td2b2LssaBNy0MwJ:b-14fper) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eb9bd1878e35c5d3a2e4e0d33cbb71e1156ecd1/pkg/sql/jobs/jobs.go#L131)):*
> ```Go
> 	}
> 	return jl.db.Txn(ctx, retryable)
> }
> ```

This is a much smaller patch than I was expecting! Resetting `jl.txn` to `nil` after every operation is somewhat odd, but I can live with it.

---

*[pkg/sql/jobs/jobs.go, line 135 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390#-Km3RMzg-IkIjP3ord2y:-Km3RMzg-IkIjP3ord2z:b-inrkcf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eb9bd1878e35c5d3a2e4e0d33cbb71e1156ecd1/pkg/sql/jobs/jobs.go#L135)):*
> ```Go
> // WithTxn sets the transaction that this JobLogger will use for its next
> // operation. If the transaction is nil, the JobLogger will create a one-off
> // trasnaction instead.
> ```

"transaction"

---

*[pkg/sql/jobs/jobs_test.go, line 307 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390#-Km3UOcM8ZBVw81GIKfa:-Km3UOcM8ZBVw81GIKfb:b-o95icn) ([raw file](https://github.com/cockroachdb/cockroach/blob/54a6cec699c576cdb62174e23173e1f775b3d025/pkg/sql/jobs/jobs_test.go#L307)):*
> ```Go
> 	isDuplicateOperationError := func(err error, re string) bool {
> 		switch err.(type) {
> 		case jobs.DuplicateOperationError:
> ```

`if jobs.IsDuplicateOperationError(err)`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390#-:-Km3UgxCf3tOQz6wNV-b:b1xi5vv)*

**Comment by benesch** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390)*

**Comment by benesch** [comment]
Oof, looks like there's a race because `.Progressed` gets called from multiple threads in backup/restore.

You could potentially return a *new* job logger from `WithTxn`?
```
Oof, looks like there's a race because `.Progressed` gets called from multiple threads in backup/restore.

You could potentially return a *new* job logger from `WithTxn`? Something like:

```
func (jl JobLogger) WithTxn(txn *client.Txn) *JobLogger {
  jl.txn = txn
  return &jl
}
```

Then you wouldn't need to reset the transaction on the next call to `runInTxn` either.

**Comment by jordanlewis** [comment]
Good idea, done. (Trying out a fixup reviewable flow - i'll rebase these together once we're satisfied)

---

Review status: 11 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/jobs/jobs.go, line 131 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390#-Km3Td2b2LssaBNy0MwI:-Km3YeQg1mCB0gU2TTuu:b-xteitw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eb9bd1878e35c5d3a2e4e0d33cbb71e1156ecd1/pkg/sql/jobs/jobs.go#L131)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This is a much smaller patch than I was expecting! Resetting `jl.txn` to `nil` after every operation is somewhat odd, but I can live with it.
</blockquote></details>

Well, I figure it prevents confusing behavior when a job logger is used inside of a transaction and then outside of a transaction at some later point. That's why I went with the fluent interface - otherwise you'd have to SetTxn(txn), Created(), SetTxn(nil) or whatever which seems yuck.

---

*[pkg/sql/jobs/jobs.go, line 135 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390#-Km3RMzg-IkIjP3ord2y:-Km3Ys7E-GN1a-x63ZZs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eb9bd1878e35c5d3a2e4e0d33cbb71e1156ecd1/pkg/sql/jobs/jobs.go#L135)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

"transaction"
</blockquote></details>

Done.

---

*[pkg/sql/jobs/jobs_test.go, line 307 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390#-Km3UOcM8ZBVw81GIKfa:-Km3ZOGOmHnlc8lzqKDz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/54a6cec699c576cdb62174e23173e1f775b3d025/pkg/sql/jobs/jobs_test.go#L307)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

`if jobs.IsDuplicateOperationError(err)`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390#-:-Km3ZiBIXvNtQQu9I0RO:b-ml9fb3)*

**Comment by benesch** [comment]
Whoops, suggesting that you copy the job logger in `WithTxn` was a flawed suggestion. `jobLogger.WithTxn(txn).Created()` needs to be able to update the master copy of `jobLogger.jobId`.

**Comment by jordanlewis** [comment]
Yeah I discovered that via CI and haven't updated the PR since. Adding a lock around the txn should work okay.

**Comment by benesch** [comment]
True, but it means you need to be very careful not to call `WithTxn()` if you're using multiple threads.

**Comment by jordanlewis** [comment]
Reverted the change to `WithTxn` and simply moved the racy bit of `restore.go` within the lock that was available. It's not ideal that the critical section now includes the database query, but I don't know if it matters here - please advise.

**Comment by benesch** [comment]
I think consensus is it's not obviously wrong but not ideal. The original PR actually sent the request inside the morally-equivalent lock, but [@danhhz objected](https://reviewable.io/reviews/cockroachdb/cockroach/14459#-KgZmbaTxDN8OwRkaFVF). 

I think we're better off just copying the `jobs.JobLogger` into each `sqlccl.jobProgressLogger`. If you swap the `jobLogger` field type from a `*jobs.JobLogger` to `jobs.JobLogger`, does it just work? 

If we go this route, can you also add a comment noting that `jobs.JobLogger` is not thread safe?

---

Reviewed 3 of 17 files at r1, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390#-:-Km9ZU0fR7XbvDQA2xLo:by0ui0z)*

**Comment by jordanlewis** [comment]
No, that won't work, because there's only one jobProgressLogger that gets used from many goroutines.

I backed out the changes to `restore` and modified JobLogger to only reset its txn if its txn has been set in the first place. This has the effect of making JobLogger threadsafe unless `WithTxn` gets used - I added that documentation to `WithTxn`.

---

Review status: 11 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390#-:-KmCTZ0OhnfrNf_6Uhvv:b6vgl0d)*

**Comment by benesch** [comment]
Doh! Of course.

---

Reviewed 1 of 17 files at r1, 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/jobs/jobs.go, line 153 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390#-KmCaplHgkuLL0ISOt5n:-KmCamcKX3zMRJ_J7wwV:bsbrhh5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3356a4cd6f73a83c153933481e0e92c13065774a/pkg/sql/jobs/jobs.go#L153)):*
> ```Go
> 	}()
> 	if jl.txn != nil {
> 		return jl.txn.Exec(ctx, client.TxnExecOptions{AutoRetry: true, AssignTimestampImmediately: true},
> ```

Can't you just move the call to `defer func() { jl.txn = nil }` inside this if block? That makes the control flow clearer in my head, at least.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390#-:-KmCZOMn8JjMDPJ4XpxV:bo8wdr5)*

**Comment by jordanlewis** [comment]
Done and squashed

---

Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/jobs/jobs.go, line 153 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390#-KmCaplHgkuLL0ISOt5n:-KmCtBlfY8Bs-VXsYahH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3356a4cd6f73a83c153933481e0e92c13065774a/pkg/sql/jobs/jobs.go#L153)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Can't you just move the call to `defer func() { jl.txn = nil }` inside this if block? That makes the control flow clearer in my head, at least.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390#-:-KmCtMFwxOzHvl41miTV:bh4ljts)*

**Comment by benesch** [comment]
:lgtm: modulo @vivekmenezes's review of the schema change stuff.

---

Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390#-:-KmD392vKb4ss_TebPrW:b36p55m)*

**Comment by benesch** [comment]
Reviewed 1 of 17 files at r1, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390)*

**Comment by vivekmenezes** [comment]
Nice work on the PR!

It looks good with the exception of the whole duplicate error dance that you're doing here. It's not clear why you need to do it. Do you have to return an error if the operation has already been done? Can you make these operations idempotent?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390#-:-KmDJ3ce35w2Wek3kcbn:b-88pwwt)*

**Comment by jordanlewis** [comment]
@vivekmenezes I'm merely preserving the JobLogger API's semantics - if @benesch is okay with it I could merely remove the errors on duplicate operations as they would be idempotent as you suggest.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390#-:-KmDN-LBiJ_VJE2uN5-g:bfmni87)*

**Comment by vivekmenezes** [comment]
I see. @benesch any reason for preserving them?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390#-:-KmD_4kV6tToSA7LNudX:bwkybhu)*

**Comment by benesch** [comment]
I don't mind removing the duplicate operation errors; they exist merely to prevent programmer errors, and they're 33% less useful if one of the three consumers of the API ignores them entirely.

@jordanlewis and I discussed this in person, but mentioning it again here just in case: beware that `Created` isn't idempotent!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390#-:-KmONabVUxzlldHUhxvX:b-zbugr5)*

**Comment by jordanlewis** [comment]
@benesch actually I'm remembering why I added the duplicate operation guard for `Created` - it *is* actually idempotent when the `JobLogger` you're calling `Created` on already has a job id!

**Comment by jordanlewis** [comment]
Removed the duplicate error exceptions, RFAL

**Comment by vivekmenezes** [comment]
:lgtm:

---

Review status: 6 of 13 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/jobs/jobs.go, line 125 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390#-KmUKZiOfLULTAvXLmIr:-KmUKZiOfLULTAvXLmIs:b-g7mavf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a696f09d8f13adf43a10e92373fda602bb26db5e/pkg/sql/jobs/jobs.go#L125)):*
> ```Go
> 	if jl.txn != nil {
> 		defer func() { jl.txn = nil }()
> 		return jl.txn.Exec(ctx, client.TxnExecOptions{AutoRetry: true, AssignTimestampImmediately: true},
> ```

do we really need the AssignTimestampImmediately param?

---

*[pkg/sql/sqlutil/internal_executor.go, line 42 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390#-KmUKxW60rEUmdTE-jXK:-KmUKxW79wzokl4BFqco:b-xiwf70) ([raw file](https://github.com/cockroachdb/cockroach/blob/a696f09d8f13adf43a10e92373fda602bb26db5e/pkg/sql/sqlutil/internal_executor.go#L42)):*
> ```Go
> 	QueryRowInTransaction(
> 		ctx context.Context, opName string, txn *client.Txn, statement string, qargs ...interface{},
> 	) (parser.Datums, error)
> ```

leftover from a previous commit?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390#-:-KmUL1ndHhCNyyjNlekV:bnfp4nl)*

**Comment by jordanlewis** [comment]
TFTRs!

---

Review status: 6 of 13 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/jobs/jobs.go, line 125 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390#-KmUKZiOfLULTAvXLmIr:-KmWwwnKv0QRPoJjQgqB:bz16kl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a696f09d8f13adf43a10e92373fda602bb26db5e/pkg/sql/jobs/jobs.go#L125)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

do we really need the AssignTimestampImmediately param?
</blockquote></details>

That's what the standard Exec does - I was just trying to keep the previous behavior.

---

*[pkg/sql/sqlutil/internal_executor.go, line 42 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390#-KmUKxW60rEUmdTE-jXK:-KmWwoo3cnGckJ9Ibnkp:bcivpz5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a696f09d8f13adf43a10e92373fda602bb26db5e/pkg/sql/sqlutil/internal_executor.go#L42)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

leftover from a previous commit?
</blockquote></details>

No this is required.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390#-:-KmWx3KaIB7UrPtQX3IR:bz5mair)*

**Comment by benesch** [comment]
Review status: 6 of 13 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/jobs/jobs.go, line 125 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390#-KmUKZiOfLULTAvXLmIr:-KmWxOLLrJbEPB8vSnmo:b9qep1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/a696f09d8f13adf43a10e92373fda602bb26db5e/pkg/sql/jobs/jobs.go#L125)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

That's what the standard Exec does - I was just trying to keep the previous behavior.
</blockquote></details>

Without `AssignTimestampImmediately` attempting to execute the SQL function `now()` will blow up. See #14119.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16390)*

**Pull request merged**
