### PR TITLE
server: pass AC soft slot granter to Pebble

### PR DESCRIPTION
**Pull request by bananabrick**
Allow Pebble to make use of the AC soft slot granter to
perform additional CPU work.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84006)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick)

___
*[`pkg/server/config.go` line 526 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84006#-N6OZuJdA5-z5NynUiVR:-N6OZuJdA5-z5NynUiVS:bltb6d5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a958418126e4968419dfaa63f702251e7c7eed20/pkg/server/config.go#L526)):*
> ```Go
> 
> func (c *cpuWorkPermissionGranter) TryGetProcs(count int) int {
> 	return c.TryGetSlots(count)
> ```

I think we should add a cluster setting to disable granting any soft slots, without restarting nodes. And we conveniently have this level of indirection for using the cluster setting.

**Review by bananabrick — COMMENTED** [review]
Should be good for another look. I haven't yet manually tested the cluster setting which I'll be doing now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84006#-:-N6P6OhmA7tmdvyQSAX7:b-lz7zmz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick and @sumeerbhola)

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84006#-:-N6PvGIxBd0fY3S83Nb-:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bananabrick)

**Pull request merged**
