### PR TITLE
sql: fix UPSERT RETURNING in presence of schema changes

### LINKED ISSUE #29436: sql: v2.0.5: panic while executing 1 statements: UPSERT panics in AddRow
https://sentry.io/cockroach-labs/cockroachdb/issues/669605580/

```
*log.safeError: conn_executor.go:521: panic while executing 1 statements: INSERT INTO _(_, _, _, _, _, _, _, _, _, _, _, _) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) ON CONFLICT (_, _, _) DO UPDATE SET _ = _._, _ = _._, _ = _._, _ = _._, _ = _._, _ = _._ RETURNING _: caused by <redacted>
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go", line 489, in func2
  File "github.com/cockroachdb/cockroach/pkg/sql/sqlbase/row_container.go", line 266, in AddRow
  File "github.com/cockroachdb/cockroach/pkg/sql/tablewriter.go", line 514, in finalize
  File "github.com/cockroachdb/cockroach/pkg/sql/upsert.go", line 320, in internalNext
  File "github.com/cockroachdb/cockroach/pkg/sql/upsert.go", line 280, in startExec
...
(16 additional frame(s) were not displayed)

conn_executor.go:521: panic while executing 1 statements: INSERT INTO _(_, _, _, _, _, _, _, _, _, _, _, _) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) ON CONFLICT (_, _, _) DO UPDATE SET _ = _._, _ = _._, _ = _._, _ = _._, _ = _._, _ = _._ RETURNING _: caused by <redacted>
```

### PR DESCRIPTION
**Pull request by jordanlewis**
Fixes #29436.

Release note (bug fix): fix crash caused by certain kinds of UPSERT
RETURNING statements on tables with active schema changes.

### CODE REVIEW

**Review by vivekmenezes — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29487)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/descriptor_mutation_test.go, line 191 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29487#-LLXDynd11InDbbBJE8h:-LLXDynd11InDbbBJE8i:b-efxvyq) ([raw file](https://github.com/cockroachdb/cockroach/blob/25e56d898c6f3185f5053cdd789db435474575d8/pkg/sql/descriptor_mutation_test.go#L191)):*
> ```Go
> 	mTest.Exec(t, `UPSERT INTO t.test VALUES('a', 'bar')`)
> 
> 	mTest.Exec(t, `UPSERT INTO t.test VALUES('foo') RETURNING k`)
> ```

Looks like you only need this statement in this test; right?

Also, could you add an INSERT statement as well. Thanks!
___
*[pkg/sql/tablewriter_upsert.go, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29487#-LLXCI37DTQGUDDesa-s:-LLXCI38DgNbzaNxLQZ5:b-w6fhrd) ([raw file](https://github.com/cockroachdb/cockroach/blob/25e56d898c6f3185f5053cdd789db435474575d8/pkg/sql/tablewriter_upsert.go#L43)):*
> ```Go
> 	// rowIdxToRetIdx maps the indices in the inserted rows
> 	// back to indices in rowTemplate. Contains -1 for indices in the inserted
> 	// rows that shouldn't be returned to the user - mutation columns.
> ```

how about creating

const dontReturnCol = -1

It will make this code more readable

**Comment by jordanlewis** [comment]
Thanks, will do. Also, this fix isn't complete, there's another bug lurking... will send another patch.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29487)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/descriptor_mutation_test.go, line 191 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29487#-LLXDynd11InDbbBJE8h:-LLXcoZC30w069BR_Rdc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/25e56d898c6f3185f5053cdd789db435474575d8/pkg/sql/descriptor_mutation_test.go#L191)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Looks like you only need this statement in this test; right?

Also, could you add an INSERT statement as well. Thanks!
</blockquote></details>

Done.
___
*[pkg/sql/tablewriter_upsert.go, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29487#-LLXCI37DTQGUDDesa-s:-LLXco4A4Xn2jjZLJcGU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/25e56d898c6f3185f5053cdd789db435474575d8/pkg/sql/tablewriter_upsert.go#L43)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

how about creating

const dontReturnCol = -1

It will make this code more readable
</blockquote></details>

Done.

**Pull request merged**
