### PR TITLE
opt: support SHOW statements for table details

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: add SkipCache flag to Catalog

Adding the ability to specify `SkipCache` when resolving a schema or a
data source. This will be needed for various SHOW statements.

Release note: None

#### opt: support SHOW statements for table details

Move implementation of `SHOW CREATE TABLE`, `SHOW COLUMNS`,
`SHOW INDEX`, `SHOW CONSTRAINTS` to `sql/delegate`.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
@knz let me know if you want to keep reviewing this kind of change, or we can talk to Jordan to pick someone else

**Review by knz — COMMENTED** [review]
sql changes lgtm - please ask someone else for the opt changes.

> Reviewed 9 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36911#-:-Lcg971S7qS2_3njifJm:bkdo56t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rytaft)

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, 10 of 10 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36911#-:-LchDnEsC8cbw0iXuk2Z:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by RaduBerinde** [comment]
Added a commit to avoid getting table stats, and one to fix a non-determinism in the execbuilder.

**Comment by RaduBerinde** [comment]
Renamed `SkipTableCache` to `AvoidDescriptorCaches` since it applies to more than tables.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 2 of 14 files at r4, 9 of 11 files at r5, 2 of 2 files at r6, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36911#-:-LcmQwg568fybbUFM4As:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 944 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/36911#-LcmQeuu2zLM97KyAeCk:-LcmQeuu2zLM97KyAeCl:b-9ieb85) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d3171b8ff532b0379fbff741937d980ae5cf7c2/pkg/sql/opt/exec/execbuilder/relational_builder.go#L944)):*
> ```Go
> 		if !ordOk {
> 			panic(pgerror.NewAssertionErrorf("needed column not produced by group-by input"))
> 		}
> ```

what does this change have to do with this PR?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36911)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 944 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/36911#-LcmQeuu2zLM97KyAeCk:-LcnJ5lY1JUqpN5-uBeA:bmoe2xh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d3171b8ff532b0379fbff741937d980ae5cf7c2/pkg/sql/opt/exec/execbuilder/relational_builder.go#L944)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

what does this change have to do with this PR?
</blockquote></details>

It's in a separate commit, with the description below. It fixes a flaky test with EXPLAIN SHOW COLUMNS.

----
When the execbuilder tries to trim down unnecessary columns from a
group-by input, it uses `FastIntMap.ForEach` which does not always
return the keys in order.

To fix this, we instead go through the needed columns in order.

Release note: None

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36911#-:-LcnJQo9786ENbUn07p9:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

**Pull request merged**
