### PR TITLE
opt: store internal FDs for Project

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: add optgen support for unexported fields

Currently internal fields (typically used to cache various properties)
have to reside in the Private and there is no general way to
initialize them. This change adds support for unexported expression
fields. Any expression with such fields must define an `init(*Memo)`
method which is called when an expression is constructed.

Release note: None

#### opt: move unexported Private fields

This change moves existing unexported fields from the private to the
expression itself.

Release note: None

#### opt: store internal FDs for Project

It is useful to keep track of the functional dependencies between all
columns involved in a project, not just the ones that are being
projected. An example is when we have a synthesized column which is
constant-folded to be equivalent to an input column, and that input
column is not projected.

This change adds these "internal" FDs as an unexported field for
ProjectExpr, and uses them to better pass orderings through Project.

Related to #43360.

Release note (performance improvement): Better execution plans in some
cases where there is an ordering on an expression that can be
constant-folded to a simple column reference.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Looking for comments especially for the unexported field infrastructure. Should `init()` have a more specific name (`initUnexportedFields`)? Should I use `internal` instead of `unexported` for these fields?

**Review by justinj — COMMENTED** [review]
I wish I had a suggestion for a better name than "private", it's sort of confusing that we have both that and "unexported" in the same domain.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43724#-:-Lxvd68Q-VqBFzXc0NqS:b-60hy63)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/expr.go, line 508 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43724#-Lxw0woU3nR7SmJ3Dm85:-Lxw0woU3nR7SmJ3Dm86:bv4pvjs) ([raw file](https://github.com/cockroachdb/cockroach/blob/233c539d5aea13094d15115863372cee9459c5fd/pkg/sql/opt/memo/expr.go#L508)):*
> ```Go
> // init is called when a project expression is created. It initializes the
> // internalFuncDeps field.
> func (prj *ProjectExpr) init(mem *Memo) {
> ```

should this just call `DeriveInternalFDs`?
___
*[pkg/sql/opt/memo/expr.go, line 521 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43724#-Lxw0I3b6R_Td2wW1je2:-Lxw0I3b6R_Td2wW1je3:bu407s0) ([raw file](https://github.com/cockroachdb/cockroach/blob/233c539d5aea13094d15115863372cee9459c5fd/pkg/sql/opt/memo/expr.go#L521)):*
> ```Go
> 			// BY expression.
> 			prj.internalFuncDeps.AddEquivalency(variable.Col, item.Col)
> 		}
> ```

we can skip the second block if we do the first one, right? not sure if it would be simpler or not to make this an elseif
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 294 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43724#-Lxw1W3s1tNpt3pzPjOE:-Lxw1W3s1tNpt3pzPjOF:b-z581kb) ([raw file](https://github.com/cockroachdb/cockroach/blob/233c539d5aea13094d15115863372cee9459c5fd/pkg/sql/opt/memo/logical_props_builder.go#L294)):*
> ```Go
> 	rel.FuncDeps.CopyFrom(&prj.internalFuncDeps)
> 	rel.FuncDeps.MakeNotNull(rel.NotNullCols)
> 	rel.FuncDeps.ProjectCols(rel.OutputCols)
> ```

kind of a pain that we can't precompute this version since we don't have the NotNullCols/OutputCols at that point... maybe it would make sense to precompute them too? I'm not sure. I like the current system but this feels like it might be an argument for lazily computing the stored FDs (but I'm not sure what other problems that would bring about)
___
*[pkg/sql/opt/optbuilder/testdata/orderby, line 482 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43724#-Lxw37bm3Nrdxg65JgMp:-Lxw37bm3Nrdxg65JgMq:b-hjmbnx) ([raw file](https://github.com/cockroachdb/cockroach/blob/233c539d5aea13094d15115863372cee9459c5fd/pkg/sql/opt/optbuilder/testdata/orderby#L482)):*
> ```
> 
> 
> # Sort should be skipped if the ORDER BY clause is constant.
> ```

nice improvement on this one (even if it just simplifies the shape of the plan)!
___
*[pkg/sql/opt/optgen/cmd/optgen/metadata.go, line 306 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43724#-LxvZeUwDZDneCNpqwrI:-LxvZeUx4mypuPuaI6TS:b-jgnz37) ([raw file](https://github.com/cockroachdb/cockroach/blob/358eeb79767d19179dd3b62030c615756cd2047d/pkg/sql/opt/optgen/cmd/optgen/metadata.go#L306)):*
> ```Go
> //
> // The Input and Projections fields are children, but the Passthrough and
> // the interanlFuncDeps fields will not be returned.
> ```

nit: interanl

**Review by justinj — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43724#-:-Lxw4vid767CLlh2y2Fc:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, @RaduBerinde, and @rytaft)

**Review by rytaft — APPROVED** [review]
:lgtm:

>  Should init() have a more specific name (initUnexportedFields)? Should I use internal instead of unexported for these fields?

I like the name `unexported`, and I'd change `init` to `initUnexportedFields`

> Reviewed 7 of 7 files at r1, 2 of 2 files at r2, 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43724#-:-Ly-_z8hA2p0l_7Ix4Il:b-szutq3)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andy-kimball and @RaduBerinde)

___
*[pkg/sql/opt/memo/expr.go, line 440 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43724#-Ly-XVZy-xQynDI8e4U3:-Ly-XVZy-xQynDI8e4U4:b-4mc95x) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffb135129d82bb87b35f8474ec697f3506a65391/pkg/sql/opt/memo/expr.go#L440)):*
> ```Go
> }
> 
> func (lj *ZigzagJoinExpr) init(mem *Memo) {
> ```

[nit] I'd make the receiver name something like `zj` instead of `lj`
___
*[pkg/sql/opt/ops/README.md, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43724#-Ly-TpBCDhybXTtvZPJC:-Ly-TpBDA-e1gDMOxrcy:bax1mku) ([raw file](https://github.com/cockroachdb/cockroach/blob/358eeb79767d19179dd3b62030c615756cd2047d/pkg/sql/opt/ops/README.md#L9)):*
> ```Markdown
> operator can contain, in this order:
>  - any number of "child" expressions (relational and/or scalar);
>  - at most one "private" field. If multiple fields are necessary, the private
> ```

It would help to give some intuition here about what the difference is between the "private" and the unexported fields. What kinds of things should go in the private v. unexported fields?
___
*[pkg/sql/opt/optgen/cmd/optgen/metadata.go, line 338 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43724#-Ly-VO7YD9Vcx1lEfkNn:-Ly-VO7YD9Vcx1lEfkNo:br19srj) ([raw file](https://github.com/cockroachdb/cockroach/blob/358eeb79767d19179dd3b62030c615756cd2047d/pkg/sql/opt/optgen/cmd/optgen/metadata.go#L338)):*
> ```Go
> 		if !typ.isExpr {
> 			if !isEmbeddedField(field) && !isExportedField(field) {
> 				// This is an unexported field; there is no private.
> ```

[nit] mention that you know there is no private because of the way the fields are ordered
___
*[pkg/sql/opt/ordering/project.go, line 65 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43724#-Ly-aoM4COxaCjJw_eJX:-Ly-aoM4COxaCjJw_eJY:buzfzst) ([raw file](https://github.com/cockroachdb/cockroach/blob/233c539d5aea13094d15115863372cee9459c5fd/pkg/sql/opt/ordering/project.go#L65)):*
> ```Go
> // isOrderingBoundBy returns true if the given ordering can be satisfied using
> // only the columns produced by input.
> func isOrderingBoundBy(input memo.RelExpr, ordering *physical.OrderingChoice) bool {
> ```

Do you need this function anymore?

**Review by andy-kimball — COMMENTED** [review]
Possible alternatives to `Private`: `Auxiliary`, `Extra`, `Other`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43724#-:-Ly-p9GRBQFlHME8Z3uB:btqoyi4)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andy-kimball and @RaduBerinde)

**Review by RaduBerinde — COMMENTED** [review]
Updated to store the not-null columns as well, and used `ExprIsNeverNull` for better and cleaner not-null projection detection.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43724#-:-Ly37I9Y62BbqXKD0Ujo:bnqkdyo)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @justinj and @rytaft)

___
*[pkg/sql/opt/memo/expr.go, line 440 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43724#-Ly-XVZy-xQynDI8e4U3:-Ly0H-6bCO5vAuVfNyjb:bs7wuoz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffb135129d82bb87b35f8474ec697f3506a65391/pkg/sql/opt/memo/expr.go#L440)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] I'd make the receiver name something like `zj` instead of `lj`
</blockquote></details>

Done.j
___
*[pkg/sql/opt/memo/expr.go, line 508 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43724#-Lxw0woU3nR7SmJ3Dm85:-Ly0JquV4_uX3dkusPyG:b7xirza) ([raw file](https://github.com/cockroachdb/cockroach/blob/233c539d5aea13094d15115863372cee9459c5fd/pkg/sql/opt/memo/expr.go#L508)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

should this just call `DeriveInternalFDs`?
</blockquote></details>

I meant to remove that function - done.
___
*[pkg/sql/opt/memo/expr.go, line 521 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43724#-Lxw0I3b6R_Td2wW1je2:-Ly36uyI1_dtV3SpqwoJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/233c539d5aea13094d15115863372cee9459c5fd/pkg/sql/opt/memo/expr.go#L521)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

we can skip the second block if we do the first one, right? not sure if it would be simpler or not to make this an elseif
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 294 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43724#-Lxw1W3s1tNpt3pzPjOE:-Ly0HdO76AUt3WC-RvJ6:b-9f0l2w) ([raw file](https://github.com/cockroachdb/cockroach/blob/233c539d5aea13094d15115863372cee9459c5fd/pkg/sql/opt/memo/logical_props_builder.go#L294)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

kind of a pain that we can't precompute this version since we don't have the NotNullCols/OutputCols at that point... maybe it would make sense to precompute them too? I'm not sure. I like the current system but this feels like it might be an argument for lazily computing the stored FDs (but I'm not sure what other problems that would bring about)
</blockquote></details>

We don't want to precompute the version after `ProjectCols` (the point is to have the FDs that include any columns that are projected away; otherwise we can just use the "output" FDs in the logical props). As for `NotNullCols`, it feels like the right thing to calculate those in the same place where we calculate the internal FDs - both "analyze" the projections. Plus technically we'd want to use all the not-null columns, not just those that intersect with the output cols. I went ahead and did that. I also improved the code to use `ExprIsNeverNull` which results in better not-null detection.
___
*[pkg/sql/opt/ops/README.md, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43724#-Ly-TpBCDhybXTtvZPJC:-Ly0FHeb54ovLLP53dpj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/358eeb79767d19179dd3b62030c615756cd2047d/pkg/sql/opt/ops/README.md#L9)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

It would help to give some intuition here about what the difference is between the "private" and the unexported fields. What kinds of things should go in the private v. unexported fields?
</blockquote></details>

Done.
___
*[pkg/sql/opt/optgen/cmd/optgen/metadata.go, line 338 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43724#-Ly-VO7YD9Vcx1lEfkNn:-Ly0GH0ZA3VwmhZW1Jh7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/358eeb79767d19179dd3b62030c615756cd2047d/pkg/sql/opt/optgen/cmd/optgen/metadata.go#L338)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] mention that you know there is no private because of the way the fields are ordered
</blockquote></details>

Done.
___
*[pkg/sql/opt/ordering/project.go, line 65 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43724#-Ly-aoM4COxaCjJw_eJX:-Ly0JnaWCVavoDTzOK3c:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/233c539d5aea13094d15115863372cee9459c5fd/pkg/sql/opt/ordering/project.go#L65)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Do you need this function anymore?
</blockquote></details>

Removed.

**Review by rytaft — APPROVED** [review]
Awesome that you could infer so many new not null cols!

> Reviewed 5 of 14 files at r4, 67 of 67 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43724#-:-Ly597IuDjz5XUT4AcED:bbog03s)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @justinj and @RaduBerinde)

___
*[pkg/sql/opt/ordering/project.go, line 65 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43724#-Ly-aoM4COxaCjJw_eJX:-Ly58t0qEi3wvxEuIpOk:b-co0zrf) ([raw file](https://github.com/cockroachdb/cockroach/blob/233c539d5aea13094d15115863372cee9459c5fd/pkg/sql/opt/ordering/project.go#L65)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Removed.
</blockquote></details>

Looks like it's still here...

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43724)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @justinj and @rytaft)

___
*[pkg/sql/opt/ordering/project.go, line 65 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43724#-Ly-aoM4COxaCjJw_eJX:-LyAWwQd8k2JVjf1BAK3:bt3aeyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/233c539d5aea13094d15115863372cee9459c5fd/pkg/sql/opt/ordering/project.go#L65)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Looks like it's still here...
</blockquote></details>

Thanks, fixed, not sure how I screwed that up haha

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43724)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @justinj, @RaduBerinde, and @rytaft)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/43724#-Ly08bZd8AcwRd8EGHgz:-Ly08bZe7SY1HLuBnSta:bfzil6u) (no related file):*
A meta-question. What if we were to re-define the null props, FD set, etc. in logical properties as showing info for all output _and_ all input columns, for _all_ operators? Does that run into lots of problems? Would there be any advantages?

---

**Comment by RaduBerinde** [comment]
*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/43724#-Ly08bZd8AcwRd8EGHgz:-LyHRQT2CIga_g-riSqK:b-9fgn3t) (no related file):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

A meta-question. What if we were to re-define the null props, FD set, etc. in logical properties as showing info for all output _and_ all input columns, for _all_ operators? Does that run into lots of problems? Would there be any advantages?
</blockquote></details>

I think it can get confusing. In particular there are ops (select, join) for which the same colIDs are both input and output but they have different FDs in the two contexts.

---

**Pull request merged**
