### PR TITLE
tests: bump predecessor version to v22.2.0-beta.5

### PR DESCRIPTION
**Pull request by adityamaru**
There are a few mixed version roachtests that are failing because of the fix (https://github.com/cockroachdb/cockroach/pull/90833) being in 22.2.0-beta.5. Such as:

#90928
#90754

Release note: None

### CODE REVIEW

**Review by celiala — APPROVED** [review]
Thanks for bumping & fixing the tests!

**Review by srosenberg — APPROVED** [review]

**Comment by adityamaru** [comment]
`TetsComposeGSS` failed but it seems to have been red on PRs before this diff to with a 404 error. I'll flag it to the right team but merging this anyway.

TFTR!

bors r+

**Comment by renatolabs** [comment]
Seems like `22.2.0-beta.5` (388261dcdb873ba60fa1e27eb9132a50a492b36f) doesn't include the fix, I still see the same error. The related failures here might still happen until the new beta is pushed and the predecessor is bumped again.

**Comment by adityamaru** [comment]
oh oops, i thought I checked the tag that contains the fix, but I must've messed it up.

**Pull request merged**
