### PR TITLE
cli: stop synctest if the supplied dir is not empty

### LINKED ISSUE #23242: cli: synctest clobbers the specified directory
This is completely undocumented and not warned, so naively running `cockroach debug synctest ~` destroyed my VM (since it clobbered `~/.ssh` and I couldn't log back in).

`synctest` should be changed to refuse to work on existing directories.

I am fixing this now.

### PR DESCRIPTION
**Pull request by rjnn**
Prior to this commit, synctest would just clobber the entire supplied directory, with no warning. Fixes #23242.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/cli/synctest/synctest.go, line 135 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23248#-L6TVdfP20INZSJIq4Wh:-L6TVdfP20INZSJIq4Wi:b-ngc8yz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cdd72b4107f9502b12341c8bdcf548279a159d2/pkg/cli/synctest/synctest.go#L135)):*
> ```Go
> 	_, err := os.Stat(opts.Dir)
> 	if err == nil {
> 		// The directory exists. Check if it is empty.
> ```

Any reason you're not error'ing out here? `synctest` will create the directory if it doesn't exist, so I think it would be fine to error if the directory already exists to prevent it from removing the contents of an existing directory.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23248)*

**Comment by arjunravinarayan** [comment]
*[pkg/cli/synctest/synctest.go, line 135 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23248#-L6TVdfP20INZSJIq4Wh:-L6XPOhj81zBh331yCVv:bpusxoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cdd72b4107f9502b12341c8bdcf548279a159d2/pkg/cli/synctest/synctest.go#L135)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Any reason you're not error'ing out here? `synctest` will create the directory if it doesn't exist, so I think it would be fine to error if the directory already exists to prevent it from removing the contents of an existing directory.
</blockquote></details>

Sure, that would be simpler. Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23248)*

**Comment by benesch** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/cli/synctest/synctest.go, line 135 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23248#-L6TVdfP20INZSJIq4Wh:-L6YCFfcIfyvl0URMVQI:b-ka2tul) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cdd72b4107f9502b12341c8bdcf548279a159d2/pkg/cli/synctest/synctest.go#L135)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Sure, that would be simpler. Done.
</blockquote></details>

To be 100% correct I think you also want to fail if the error is something other than `os.IsExist(err)`, but it's not critical, and especially not in this code path.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23248#-:-L6YC9e_5-9s4BOptPEJ:bnfp4nl)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23248#-:-L6YDJBDQd-6WfD18KZp:bnfp4nl)*

**Comment by arjunravinarayan** [comment]
TFTRs!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/cli/synctest/synctest.go, line 135 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23248#-L6TVdfP20INZSJIq4Wh:-L6YDv8HqhJW9CtM-Iup:bxk65i1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cdd72b4107f9502b12341c8bdcf548279a159d2/pkg/cli/synctest/synctest.go#L135)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

To be 100% correct I think you also want to fail if the error is something other than `os.IsExist(err)`, but it's not critical, and especially not in this code path.
</blockquote></details>

Nice tip. Not doing it for this little debug tool, but good point for the future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23248#-:-L6YDu5Crs_LEJJk83pG:bz5mair)*

**Pull request merged**
