### PR TITLE
Create chinese.stop

### PR DESCRIPTION
**Pull request by zhenruyan**
add tsearch chinese stopwords

I'm considering using cockroachdb for Chinese searches, so I hope I can contribute something.

Release note: None
Epic: None

### CODE REVIEW

**Comment by michae2** [comment]
Thank you for your contribution! We appreciate it!

If you could please apply the following diff to your PR, it should help pass CI:

```
diff --git a/pkg/util/tsearch/BUILD.bazel b/pkg/util/tsearch/BUILD.bazel
index b0fde092e8..6adb1cd2e4 100644
--- a/pkg/util/tsearch/BUILD.bazel
+++ b/pkg/util/tsearch/BUILD.bazel
@@ -30,6 +30,7 @@ go_library(
         "stopwords/spanish.stop",
         "stopwords/swedish.stop",
         "stopwords/turkish.stop",
+        "stopwords/chinese.stop",
     ],
```

**Comment by rickystewart** [comment]
@michae2 Please keep the list *sorted*, i.e., `chinese.stop` should be in alphabetical order and not at the end of the list.

**Comment by zhenruyan** [comment]
> Thank you for your contribution! We appreciate it!
> 
> If you could please apply the following diff to your PR, it should help pass CI:
> 
> ```
> diff --git a/pkg/util/tsearch/BUILD.bazel b/pkg/util/tsearch/BUILD.bazel
> index b0fde092e8..6adb1cd2e4 100644
> --- a/pkg/util/tsearch/BUILD.bazel
> +++ b/pkg/util/tsearch/BUILD.bazel
> @@ -30,6 +30,7 @@ go_library(
>          "stopwords/spanish.stop",
>          "stopwords/swedish.stop",
>          "stopwords/turkish.stop",
> +        "stopwords/chinese.stop",
>      ],
> ```

Thank you for the reminder.

Do I need to withdraw the PR and resubmit?

**Comment by zhenruyan** [comment]
> 



> @michae2 Please keep the list _sorted_, i.e., `chinese.stop` should be in alphabetical order and not at the end of the list.

When dealing with Chinese, if sorted by first letter, is it sorted by the first letter of pinyin pronunciation?

**Comment by zhenruyan** [comment]
@michae2  https://github.com/cockroachdb/cockroach/pull/108983

I submitted it. I think I understand the meaning. The file names should be sorted alphabetically.

At first, I thought it was the internal content of the file.

**Review by rickystewart — CHANGES_REQUESTED** [review]
Can you please squash these 3 commits into one commit? We should be good to go after that.

**Comment by Xiang-Gu** [comment]
@zhenruyan do you mind providing some reasoning behind this?

**Comment by zhenruyan** [comment]
> Can you please squash these 3 commits into one commit? We should be good to go after that.

I am more than happy to do so.

**Comment by zhenruyan** [comment]
> @zhenruyan do you mind providing some reasoning behind this?

On why the Chinese stop words were included. ：

I'm building a general purpose search engine platform using pg/cockroach. I was pleasantly surprised to find that it's much more flexible than elasticsearch, which is great in a variable real-world business. But the experience isn't completely out-of-the-box, so I'm hoping to patch that up.

On the definition of Chinese stop words:

When postgresql uses the plug-in mechanism to add a Chinese word-splitting tool, a similar Chinese stop word is added. And these stop words have been verified in tens of millions of Chinese blog posts.

**Review by zhenruyan — COMMENTED** [review]
Add Chinese stop words, and compile dependency paths.

**Comment by zhenruyan** [comment]
> > When postgresql uses the plug-in mechanism to add a Chinese word-splitting tool, a similar Chinese stop word is added. And these stop words have been verified in tens of millions of Chinese blog posts.
> 
> Can you give me a link to where those Chinese stop words were added? Is it in a commit or some web page? Thank you very much!

https://www.oschina.net/project 
and
https://www.oschina.net/blog

We are China's open source community, open source software index directory inclusion as well as the blog's tags in the word segmentation, are used in the Chinese stop words of the word segmentation tool. In the near future, will be online based on cockroachdb or pg search (which will be based on the later ab stress test).

**Comment by Xiang-Gu** [comment]
Thanks for the reply. My only concern/question is that the list of stopwords you provided does not really match my intuitive understanding of Chinese stopwords. 

A colleague found this website https://towardsdatascience.com/chinese-natural-language-pre-processing-an-introduction-995d16c2705f in which it talked a bit about Chinese stopwords:
> In NLP, stop words are “meaningless” words that make the data too noisy or ambiguous. In our example sentence, the stop words are 是, 在 and 的. We could manually filter them out, but that’s also very tedious. Just like with English, there are pre-set lists of stop words out there. There are about 119 official stop words in Chinese, and they can be viewed on [this website](https://countwordsfree.com/stopwords/chinese). Instead of manually removing them, could import the stopwordsiso package for a full list of Chinese stop words. More information can be found [here](https://pypi.org/project/stopwordsiso/). And with this, we can easily create code to filter out any stop words in large text data.

Looking at the Chinese stopwords provided there (https://pypi.org/project/stopwordsiso/), it match more to my intuitive understanding of  Chinese stopwords.  I suggest we use that as the source for Chinese stopwords list, and you can modify it locally to best suit your own application and use case. What do you think?

**Comment by zhenruyan** [comment]
> Thanks for the reply. My only concern/question is that the list of stopwords you provided does not really match my intuitive understanding of Chinese stopwords.
> 
> A colleague found this website https://towardsdatascience.com/chinese-natural-language-pre-processing-an-introduction-995d16c2705f in which it talked a bit about Chinese stopwords:
> 
> > In NLP, stop words are “meaningless” words that make the data too noisy or ambiguous. In our example sentence, the stop words are 是, 在 and 的. We could manually filter them out, but that’s also very tedious. Just like with English, there are pre-set lists of stop words out there. There are about 119 official stop words in Chinese, and they can be viewed on [this website](https://countwordsfree.com/stopwords/chinese). Instead of manually removing them, could import the stopwordsiso package for a full list of Chinese stop words. More information can be found [here](https://pypi.org/project/stopwordsiso/). And with this, we can easily create code to filter out any stop words in large text data.
> 
> Looking at the Chinese stopwords provided there (https://pypi.org/project/stopwordsiso/), it match more to my intuitive understanding of Chinese stopwords. I suggest we use that as the source for Chinese stopwords list, and you can modify it locally to best suit your own application and use case. What do you think?


It's good to have an evaluable standard, and I think it's great， that it doesn't conflict with my desire for it to have a better Chinese search experience. I will resubmit the commit chinese.stop.

**Comment by Xiang-Gu** [comment]
Note: The list of stopwrods is copied from https://github.com/stopwords-iso/stopwords-zh/blob/master/stopwords-zh.txt

@zhenruyan Please add a `Release note: None` in your commit and you are good to merge! Thanks again for contributing.

**Review by Xiang-Gu — APPROVED** [review]

**Review by rickystewart — APPROVED** [review]

**Comment by zhenruyan** [comment]
> Note: The list of stopwrods is copied from https://github.com/stopwords-iso/stopwords-zh/blob/master/stopwords-zh.txt
> 
> @zhenruyan Please add a `Release note: None` in your commit and you are good to merge! Thanks again for contributing.
> 
> Update: `Epic: None` as well

> Yes, please update the commit to add Release note: None and Epic: None.



@Xiang-Gu @rickystewart   Thank you very much for your patience.   I resubmitted the commit.

**Comment by rickystewart** [comment]
Thanks!

bors r=rickystewart,Xiang-Gu

**Pull request merged**
