### PR TITLE
roachtest: add a cluster.Start() flavor

### PR DESCRIPTION
**Pull request by andreimatei**
that returns an error.

Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
First commit is elsewhere.

**Review by petermattis — COMMENTED** [review]
Given that literally every single call to `cluster.Start` is followed by a `t.Fatal`, I'm not sure why this is better. Perhaps you can elaborate on your future vision here. Simply sprinkling `if ...; err != nil {}` through this code is not exciting me.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31141#-:-LOOmEsq68bUQ4uFJV7J:b-8p9rr3)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by andreimatei** [comment]
It's better because a cluster should have nothing to do with any one particular test. Yes, a cluster is currently created according to a particular (root) test's spec, but we can imagine that need not be the case forever - we should be pre-allocating and pooling clusters, as my other PR around parallel execution is starting to deep its toes into.
Even with a root test fixed, imagine you now are trying to allocate 100 clusters to run instance of it and subtests in parallel, and 1 of the 100 fails. Should a test fail at that point? If so, which? If two cluster start operations start, should the 2nd error overwrite the first one as the test's failure message? These are not questions for the `cluster` to answer; they need to be hoisted up.
Also, as the code stands today, a cluster takes a `testI` interface for a test - which is also implemented by go's `test.Test`. Except that interface doesn't allow for `t.Fatal()` to be called willy-nilly; it places restrictions on the goroutine on which it can be called. Which means that we cannot let a library like `cluster` call it; `Fatal` calls need to be coordinated at a test's highest level, not delegated down.

Besides particular arguments about this particular method, there's also a higher level principle at play here. By default, when possible, returning errors is good, and doing something else with them in a low-level library is bad; low-level libraries shouldn't have much say in how errors are handled.
By this principle alone, a `cluster` should have never done stuff like calling `t.Fatal()`.

**Comment by petermattis** [comment]
FYI, we hashed this out in person. I think @andreimatei has a plan.

**Comment by andreimatei** [comment]
PTAL.

Went with `c.StartOrFatal()` (and also a `FailIfErr()` cause why not) instead of `c.MustStart()` because I dislike the `Must` functions: like the `Maybe` functions, they don't sort properly. Google had it as a suffix - "...OrDie", which was better because the sorting and also because the "die" part was unambiguous.
I tried to introduce a `..Maybe()` function in our codebase in the past but people started stomping of me cause "consistency", and so the way I've continued to live is by deciding to not say "maybe" any more but try to be more explicit about the condition (and encode that as a name suffix). And I think the same arguments hold for "MustFoo/FooOrFatal").

**Review by petermattis — CHANGES_REQUESTED** [review]
I personally don't feel any hang up about the sorting, but I don't use `go doc` on our code. My suggestion for `Must` is because we have a ton of precedent in our code for that term, and no precedent for `OrFatal`. But also see my comment below about `Run` vs `RunE` and how the `Start` vs `StartOrFatal` differs. I guess I'm not too hung up about being globally consistent across our code base, but I would like to be consistent within the roachtest code.

LGTM other than this bikeshedding. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31141#-:-LOPUeqrA71pih-pNtb-:bgxykul)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/cluster.go, line 916 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31141#-LOPWMeZ0W06U36iBKFI:-LOPWMeZ0W06U36iBKFJ:b-qeq8u8) ([raw file](https://github.com/cockroachdb/cockroach/blob/53ea52f08f1e90b9bf970e23f631ca8acdf58c91/pkg/cmd/roachtest/cluster.go#L916)):*
> ```Go
> // StartOrFatal is like Start() except it takes a test and, on error, calls
> // t.Fatal().
> func (c *cluster) StartOrFatal(ctx context.Context, t *test, opts ...option) {
> ```

Hrmm, now we have another consistency problem: `Run` vs `RunE`. Sorry I didn't mention this before. I forgot about it.

**Review by andreimatei — COMMENTED** [review]
How about I rename `Run()` -> `RunOrFatal()` and `RunE()` -> `Run()` (and `RunL()` stays in place).
And `StartOrFatal()` stays -> the fact that it's different then `Must` is a feature (besides sorting properly) because, again, I take `Must` to mean panic or `log.Fatal`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31141#-:-LOPa98iDykawPnOp4iy:b-8xt7zd)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by andreimatei** [comment]
Went with a new `StartE()`

**Review by petermattis — APPROVED** [review]
:lgtm:

> Went with a new StartE()

:thumbsup: I'm glad that discussion was so easy.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31141#-:-LOPvpDIBhKEtS7nbPc1:blfu0i9)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/cluster.go, line 916 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31141#-LOPw3UrCd9o4F3V2f6y:-LOPw3UrCd9o4F3V2f6z:bxouz1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/252d0492549002767ad042d5ea66c940d1dbdeb8/pkg/cmd/roachtest/cluster.go#L916)):*
> ```Go
> // Start is like StartE() except it takes a test and, on error, calls t.Fatal().
> func (c *cluster) Start(ctx context.Context, t *test, opts ...option) {
> 	if t.Failed() {
> ```

I wonder if this should be in `StartE` and have that function return a sentinel error (`ErrAlreadyFailed`?) so that we don't fail again in this method.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31141)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/cluster.go, line 916 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31141#-LOPw3UrCd9o4F3V2f6y:-LOQ7IkuBeIWRYog71Iy:b-hd7ugg) ([raw file](https://github.com/cockroachdb/cockroach/blob/252d0492549002767ad042d5ea66c940d1dbdeb8/pkg/cmd/roachtest/cluster.go#L916)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I wonder if this should be in `StartE` and have that function return a sentinel error (`ErrAlreadyFailed`?) so that we don't fail again in this method. 
</blockquote></details>

I say no :)
 StartE() doesn't take a test and I dream of the day when c.t doesn't exist.

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31141)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/cluster.go, line 916 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31141#-LOPw3UrCd9o4F3V2f6y:-LOQLQpX-ny7xm8hwXaW:bzccjwo) ([raw file](https://github.com/cockroachdb/cockroach/blob/252d0492549002767ad042d5ea66c940d1dbdeb8/pkg/cmd/roachtest/cluster.go#L916)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I say no :)
 StartE() doesn't take a test and I dream of the day when c.t doesn't exist.
</blockquote></details>

Fine. If you take my other suggestion and make `t.Fatal{,f}` cancel the context, we could implement this in `c.StartE` by checking to see if the context is cancelled (looking at `ctx.Done()`).

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31141)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/cluster.go, line 916 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31141#-LOPw3UrCd9o4F3V2f6y:-LOT_dS2A7FnUynzN9vd:bpk3qm9) ([raw file](https://github.com/cockroachdb/cockroach/blob/252d0492549002767ad042d5ea66c940d1dbdeb8/pkg/cmd/roachtest/cluster.go#L916)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Fine. If you take my other suggestion and make `t.Fatal{,f}` cancel the context, we could implement this in `c.StartE` by checking to see if the context is cancelled (looking at `ctx.Done()`).
</blockquote></details>

I was going to take your suggestion separately. I've included it here now in a new commit; PTAL.
But we should talk about the intended semantics of a failed subtests. Failure used to propagate from child to parent (i.e. the parent's `t.failed` field is set when the child fails). And, as far as I can see, that used to cause every future subtests to fail to start cluster.
My patch changes that; a subtest failing will only cancel its context, not the parent's. But I haven't touched other `cluster` methods that still check `t.Failed()` and short-circuit. What was the intent here / has thought been put into this?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31141)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/cluster.go, line 916 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31141#-LOPw3UrCd9o4F3V2f6y:-LOUBLk90khn6qjM8hdn:b-wide69) ([raw file](https://github.com/cockroachdb/cockroach/blob/252d0492549002767ad042d5ea66c940d1dbdeb8/pkg/cmd/roachtest/cluster.go#L916)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I was going to take your suggestion separately. I've included it here now in a new commit; PTAL.
But we should talk about the intended semantics of a failed subtests. Failure used to propagate from child to parent (i.e. the parent's `t.failed` field is set when the child fails). And, as far as I can see, that used to cause every future subtests to fail to start cluster.
My patch changes that; a subtest failing will only cancel its context, not the parent's. But I haven't touched other `cluster` methods that still check `t.Failed()` and short-circuit. What was the intent here / has thought been put into this?
</blockquote></details>

What I was missing above is the realization that subtest objects are created early, before the parent is marked as failed. As so the parent can be failed and subsequent subtests still run fine.

**Review by petermattis — APPROVED** [review]
:lgtm:

Thanks for doing that `test.Fatal -> cancel` work.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31141#-:-LOVqAAID2xV40sPZByi:bc218lb)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/test.go, line 499 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31141#-LOVpxYz5OjBd3JlDYyW:-LOVpxYz5OjBd3JlDYyX:bhsa3mw) ([raw file](https://github.com/cockroachdb/cockroach/blob/931b657a0f71a66dccd3cd88d8d33eedce344f88/pkg/cmd/roachtest/test.go#L499)):*
> ```Go
> 		failed bool
> 		// cancel, if set, is called from the t.Fatal() family of functions when the
> 		// test is being marked as failed(i.e. when the failed field above is also
> ```

`s/failed(/failed (/g`

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31141#-:-LOW1noL7n_y_WCxh3Kh:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/test.go, line 499 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31141#-LOVpxYz5OjBd3JlDYyW:-LOW1cq_BAtYzjF7NmVJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/931b657a0f71a66dccd3cd88d8d33eedce344f88/pkg/cmd/roachtest/test.go#L499)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/failed(/failed (/g`
</blockquote></details>

Done.

**Pull request merged**
