### PR TITLE
sql: block operations properly on implicit transactions

### PR DESCRIPTION
**Pull request by fqazi**
Previously, an enhancement was made to allow implicit
transactions to execute multiple statements, which caused
code to block operations in implicit transactions to break.
This was problematic because these scenarios cared that
only a single statement is executed, and not if it was
only an implicit transition. For example, the declarative
schema changer and legacy schema changer could be mixed
in implicit transactions after this change. To address this,
this patch modifies places that we're checking for implicit
transactions to instead check for single statement transactions.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
Yikes that we were allowing `SET CLUSTER SETTING` in a transaction with other statements! It so actively assumes that it's alone. @rafiss can we get you involved in this? 

> Reviewed 14 of 15 files at r1, 1 of 46 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-:-MzIK02ABYE-ZkoFHgxO:btl49ls)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @shermanCRL)

___
*[pkg/ccl/streamingccl/streamingtest/replication_helpers.go, line 197 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzIJEpC4OFtyWmY4nx1:-MzIJEpC4OFtyWmY4nx2:bz3iox0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3490dcf5b244aa57316aed143bb3779de2abcb73/pkg/ccl/streamingccl/streamingtest/replication_helpers.go#L197)):*
> ```Go
> 
> 	// Set required cluster settings.
> 	for _, stmt := range strings.Split(`
> ```

do you have any interest in adding a variadic `sqlutils.SQLRunner` method to exec multiple statements?
___
*[pkg/sql/internal.go, line 751 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzIJQoc3A7ASrCs3___:-MzIJQoc3A7ASrCs3__a:b-ck3sw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3490dcf5b244aa57316aed143bb3779de2abcb73/pkg/sql/internal.go#L751)):*
> ```Go
> 				ParseStart:   parseStart,
> 				ParseEnd:     parseEnd,
> 				LastInBatch:  true,
> ```

I don't understand the significance of this or the other change in this file. Can you motivate them with commentary?
___
*[pkg/sql/planner.go, line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzIIwsADbouH018vGI3:-MzIIwsADbouH018vGI4:b-wwtnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/77965b811c5328935e94d65badcdf530003f5599/pkg/sql/planner.go#L211)):*
> ```Go
> 
> 	// afterFirstStmt indicates that an earlier statement was executed before the commit.
> 	afterFirstStmt bool
> ```

I'm generally anxious about state stored exclusively on the planner. The planner gets reset in a bunch of places and I can never reason clearly about them. I also find the places where you set this to be somewhat non-obvious. I wonder if there's a way to work this logic into the connExecutor's state machine to be more certain that it will not get messed up in future refactorings. 

I also am generally sad about the `planner` as an object that things need. The `EvalContext` for better or for worse, is less onerous of a dependency. It feels like the state should be on the `connExecutor` and exposed, somehow, via the `EvalContext` or the `extendedEvalContext`. Perhaps it can be in the `extraTxnState`. Let's see what @rafiss thinks.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78512)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @rafiss, and @shermanCRL)

___
*[pkg/ccl/streamingccl/streamingtest/replication_helpers.go, line 197 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzIJEpC4OFtyWmY4nx1:-MzILx70BrrHk5rxPh5Z:baodtdu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3490dcf5b244aa57316aed143bb3779de2abcb73/pkg/ccl/streamingccl/streamingtest/replication_helpers.go#L197)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

do you have any interest in adding a variadic `sqlutils.SQLRunner` method to exec multiple statements?
</blockquote></details>

Let me modify things to do that instead.
___
*[pkg/sql/internal.go, line 751 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzIJQoc3A7ASrCs3___:-MzIM-A4BdftFIpq5Mzd:b-taf3ez) ([raw file](https://github.com/cockroachdb/cockroach/blob/3490dcf5b244aa57316aed143bb3779de2abcb73/pkg/sql/internal.go#L751)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't understand the significance of this or the other change in this file. Can you motivate them with commentary?
</blockquote></details>

LastInBatch flag is used to determine if an auto-commit is needed.
___
*[pkg/sql/planner.go, line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzIIwsADbouH018vGI3:-MzIM9IkCcWC3H2WO8kE:b-owjpop) ([raw file](https://github.com/cockroachdb/cockroach/blob/77965b811c5328935e94d65badcdf530003f5599/pkg/sql/planner.go#L211)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'm generally anxious about state stored exclusively on the planner. The planner gets reset in a bunch of places and I can never reason clearly about them. I also find the places where you set this to be somewhat non-obvious. I wonder if there's a way to work this logic into the connExecutor's state machine to be more certain that it will not get messed up in future refactorings. 

I also am generally sad about the `planner` as an object that things need. The `EvalContext` for better or for worse, is less onerous of a dependency. It feels like the state should be on the `connExecutor` and exposed, somehow, via the `EvalContext` or the `extendedEvalContext`. Perhaps it can be in the `extraTxnState`. Let's see what @rafiss thinks. 
</blockquote></details>

Yes, let me check with him

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78512)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @fqazi, and @miretskiy)

___
*[pkg/ccl/streamingccl/streamingtest/replication_helpers.go, line 204 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzLKvFb6kh3cy_u08NH:-MzLKvFb6kh3cy_u08NI:b-ucpopk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e84fbc2de56d4ebaacf75304a67b20f462509fc7/pkg/ccl/streamingccl/streamingtest/replication_helpers.go#L204)):*
> ```Go
> `,
> 		";") {
> 		_, err := db.Exec(stmt)
> ```

could update this (and a few of the other lines below) to use sqlRunner
___
*[pkg/sql/conn_executor_exec.go, line 146 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzLE8DL4JeUyqBFPiIJ:-MzLE8DL4JeUyqBFPiIK:b-7lz0wb) ([raw file](https://github.com/cockroachdb/cockroach/blob/fae1134ccd2c07cf71f02e42760a5a1aba19dfb2/pkg/sql/conn_executor_exec.go#L146)):*
> ```Go
> 		}
> 		// Track that the first statement has been executed.
> 		ex.extraTxnState.firstStmtExecuted = true
> ```

i think this line would work better in `execStmtInOpenState`, maybe even right after  the line where you set `isSingleStmtTxn`
___
*[pkg/sql/planner.go, line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzIIwsADbouH018vGI3:-MzLBuWyAKKK3MCwz06G:b451zyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/77965b811c5328935e94d65badcdf530003f5599/pkg/sql/planner.go#L211)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Yes, let me check with him
</blockquote></details>

the field could be added alongside: https://github.com/cockroachdb/cockroach/blob/b9ea426e68bc8866641578d7e8ed88a5d99d7a85/pkg/sql/sem/tree/eval.go#L3605

but we'd still need to set it around the same place where `p.isSingleStmtTxn` is being set now.

we'd also want to update the `resetEvalCtx` function to reset this new field

---

though IDK if storing this in EvalContext addresses @ajwerner's concern about resetting, since resetPlanner calls resetEvalCtx

i think it sounds fine though

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78512)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @miretskiy, and @rafiss)

___
*[pkg/ccl/streamingccl/streamingtest/replication_helpers.go, line 204 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzLKvFb6kh3cy_u08NH:-MzLr_Ix9Whv1ZB7VUwd:bq6p672) ([raw file](https://github.com/cockroachdb/cockroach/blob/e84fbc2de56d4ebaacf75304a67b20f462509fc7/pkg/ccl/streamingccl/streamingtest/replication_helpers.go#L204)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could update this (and a few of the other lines below) to use sqlRunner
</blockquote></details>

Let me go through and revaluate these.
___
*[pkg/sql/conn_executor_exec.go, line 146 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzLE8DL4JeUyqBFPiIJ:-MzLrgbg0xtIe6TUED77:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fae1134ccd2c07cf71f02e42760a5a1aba19dfb2/pkg/sql/conn_executor_exec.go#L146)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think this line would work better in `execStmtInOpenState`, maybe even right after  the line where you set `isSingleStmtTxn`
</blockquote></details>

Done.
___
*[pkg/sql/planner.go, line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzIIwsADbouH018vGI3:-MzLrheT5Dsh9VgN08_m:bpqxstr) ([raw file](https://github.com/cockroachdb/cockroach/blob/77965b811c5328935e94d65badcdf530003f5599/pkg/sql/planner.go#L211)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

the field could be added alongside: https://github.com/cockroachdb/cockroach/blob/b9ea426e68bc8866641578d7e8ed88a5d99d7a85/pkg/sql/sem/tree/eval.go#L3605

but we'd still need to set it around the same place where `p.isSingleStmtTxn` is being set now.

we'd also want to update the `resetEvalCtx` function to reset this new field

---

though IDK if storing this in EvalContext addresses @ajwerner's concern about resetting, since resetPlanner calls resetEvalCtx

i think it sounds fine though


</blockquote></details>

Okay moved the flag over into the eval context.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78512)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @fqazi, @miretskiy, and @rafiss)

___
*[pkg/sql/conn_executor.go, line 2678 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzM1rxD62ASLOWAS3y9:-MzM1rxECEIFJUEaO3bQ:bxujcwr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f32e1bd390cbff729302292007d781d9de11d83/pkg/sql/conn_executor.go#L2678)):*
> ```Go
> 	evalCtx.TxnReadOnly = ex.state.readOnly
> 	evalCtx.TxnImplicit = ex.implicitTxn()
> 	evalCtx.TxnIsSingleStmt = evalCtx.TxnImplicit
> ```

would it be better to make this default to false? in practice it shouldn't matter too much, since we set it when needed, but let's do whatever makes it easier to understand
___
*[pkg/sql/conn_executor_exec.go, line 673 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzLy8iv4Xzxr1u3pMtG:-MzLy8iv4Xzxr1u3pMtH:bqzr6pk) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f32e1bd390cbff729302292007d781d9de11d83/pkg/sql/conn_executor_exec.go#L673)):*
> ```Go
> 	p.autoCommit = canAutoCommit && !ex.server.cfg.TestingKnobs.DisableAutoCommitDuringExec
> 	p.extendedEvalCtx.TxnIsSingleStmt = canAutoCommit && !ex.extraTxnState.firstStmtExecuted
> ```

i think you still need to set `ex.extraTxnState.firstStmtExecuted = true` here. shouldn't a test have caught this?
___
*[pkg/sql/planner.go, line 905 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzLxfSJ5pVT70nZtgEP:-MzLxfSJ5pVT70nZtgEQ:b-jxasge) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f32e1bd390cbff729302292007d781d9de11d83/pkg/sql/planner.go#L905)):*
> ```Go
> // IsSingleStatementTxn returns if the current transaction is a single statement
> // one or consists of multiple statements.
> func (p *planner) IsSingleStatementTxn() bool {
> ```

i don't think there's a need to expose this as a function. anyone who wants it can just use the `TxnIsSingleStmt` field.

for example, see how the `TxnImplicit` field is used
___
*[pkg/sql/sem/tree/eval.go, line 3606 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzLxxVHDOvnvobjKPF0:-MzLxxVHDOvnvobjKPF1:bkuoevr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f32e1bd390cbff729302292007d781d9de11d83/pkg/sql/sem/tree/eval.go#L3606)):*
> ```Go
> 	TxnReadOnly bool
> 	TxnImplicit bool
> 	// TxnIsSingleStmt transaction consists of only a single statement.
> ```

nit: not a full sentence. should it be "TxnIsSingleStmt is true if the transaction consists of only a single statement."

also, to be fully accurate, it's only try for implicit transactions right?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78512)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @miretskiy, and @rafiss)

___
*[pkg/sql/conn_executor.go, line 2678 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzM1rxD62ASLOWAS3y9:-MzMJCS46WJ7DaYp5Jt-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f32e1bd390cbff729302292007d781d9de11d83/pkg/sql/conn_executor.go#L2678)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

would it be better to make this default to false? in practice it shouldn't matter too much, since we set it when needed, but let's do whatever makes it easier to understand
</blockquote></details>

Done.
___
*[pkg/sql/conn_executor_exec.go, line 673 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzLy8iv4Xzxr1u3pMtG:-MzMJDH043yQRND-qOxo:b-ya4wcb) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f32e1bd390cbff729302292007d781d9de11d83/pkg/sql/conn_executor_exec.go#L673)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think you still need to set `ex.extraTxnState.firstStmtExecuted = true` here. shouldn't a test have caught this?
</blockquote></details>

It's interesting, we survived the logic test. My guess is because we defaulted to the implicit txn flag, exposing the bad behaviour again. So, I added a logic test to confirm that we disallow these ops with multiple statements.
___
*[pkg/sql/planner.go, line 905 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzLxfSJ5pVT70nZtgEP:-MzMMCsY4EnsxOlXQeRV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f32e1bd390cbff729302292007d781d9de11d83/pkg/sql/planner.go#L905)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i don't think there's a need to expose this as a function. anyone who wants it can just use the `TxnIsSingleStmt` field.

for example, see how the `TxnImplicit` field is used
</blockquote></details>

Done.

**Comment by ajwerner** [comment]
Can you also take a look at the uses of `AutoCommit()` like: https://github.com/cockroachdb/cockroach/blob/548c5e4e579eccb84aa442f7f4c7718cac0462a0/pkg/ccl/backupccl/restore_planning.go#L1152

**Comment by fqazi** [comment]
> Can you also take a look at the uses of `AutoCommit()` like:
> 
> https://github.com/cockroachdb/cockroach/blob/548c5e4e579eccb84aa442f7f4c7718cac0462a0/pkg/ccl/backupccl/restore_planning.go#L1152

Let me go over those as well

**Review by fqazi — COMMENTED** [review]
Updated  those as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-:-MzR260XAK19qBjiW08z:b-p28ihx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @miretskiy, and @rafiss)

___
*[pkg/ccl/streamingccl/streamingtest/replication_helpers.go, line 204 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzLKvFb6kh3cy_u08NH:-MzR1v1qC07BRaTyT84Y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e84fbc2de56d4ebaacf75304a67b20f462509fc7/pkg/ccl/streamingccl/streamingtest/replication_helpers.go#L204)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Let me go through and revaluate these.
</blockquote></details>

Done.
___
*[pkg/sql/conn_executor_exec.go, line 673 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzLy8iv4Xzxr1u3pMtG:-MzR1xeV8P8jn39crS9o:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f32e1bd390cbff729302292007d781d9de11d83/pkg/sql/conn_executor_exec.go#L673)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

It's interesting, we survived the logic test. My guess is because we defaulted to the implicit txn flag, exposing the bad behaviour again. So, I added a logic test to confirm that we disallow these ops with multiple statements.
</blockquote></details>

Done.

**Review by rafiss — CHANGES_REQUESTED** [review]
lgtm, except just fixes to comments and error messages now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-:-MzRY013-XX_MyAe8hWV:b5weast)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @fqazi, @miretskiy, and @rafiss)

___
*[pkg/sql/alter_column_type.go, line 262 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzRX2En-V-VyHKv1_KY:-MzRX2En-V-VyHKv1_KZ:b1vvsxg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b4832134f801015cb238e8dbb1607a9d5794fcb/pkg/sql/alter_column_type.go#L262)):*
> ```Go
> 	}
> 
> 	// Disallow ALTER COLUMN TYPE general inside an explicit transaction.
> ```

could be good to update the comment
___
*[pkg/sql/create_table.go, line 378 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzRXNGAEuk-LCEekb9C:-MzRXNGAEuk-LCEekb9D:b-wwxwbj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b4832134f801015cb238e8dbb1607a9d5794fcb/pkg/sql/create_table.go#L378)):*
> ```Go
> 		}
> 
> 		// If we have an implicit txn we want to run CTAS async, and consequently
> ```

nit: "If we have a single statement txn"
___
*[pkg/sql/create_table.go, line 503 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzRXRn7DJq_eAGeVL4M:-MzRXRn7DJq_eAGeVL4N:b5gbsdw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b4832134f801015cb238e8dbb1607a9d5794fcb/pkg/sql/create_table.go#L503)):*
> ```Go
> 	}
> 
> 	// If we are in an explicit txn or the source has placeholders, we execute the
> ```

nit: "If we are in a multi-statement txn"
___
*[pkg/sql/planner.go, line 900 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzRXYFx7VG5o0Zeu9C3:-MzRXYFx7VG5o0Zeu9C4:bcsrezc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b4832134f801015cb238e8dbb1607a9d5794fcb/pkg/sql/planner.go#L900)):*
> ```Go
> // IsSingleStatementTxn returns if the current transaction is a single statement
> // one or consists of multiple statements.
> func (p *planner) IsSingleStatementTxn() bool {
> ```

nit: remove this function
___
*[pkg/sql/refresh_materialized_view.go, line 34 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzRXbQ92I5dVcLXBmpH:-MzRXbQ92I5dVcLXBmpI:b769xom) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b4832134f801015cb238e8dbb1607a9d5794fcb/pkg/sql/refresh_materialized_view.go#L34)):*
> ```Go
> ) (planNode, error) {
> 	if !p.extendedEvalCtx.TxnIsSingleStmt {
> 		return nil, pgerror.Newf(pgcode.InvalidTransactionState, "cannot refresh view in an explicit transaction")
> ```

"in a multi-statement transaction"
___
*[pkg/sql/session_state.go, line 117 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzRXfvyER59-f3G3j2W:-MzRXfvyER59-f3G3j2X:bbhvp1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b4832134f801015cb238e8dbb1607a9d5794fcb/pkg/sql/session_state.go#L117)):*
> ```Go
> 		return nil, pgerror.Newf(
> 			pgcode.InvalidTransactionState,
> 			"cannot deserialize a session whilst inside a transaction",
> ```

"inside a multi-statement transaction"
___
*[pkg/sql/set_cluster_setting.go, line 195 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzRXj0DE1uoWFMKlM2Y:-MzRXj0DE1uoWFMKlM2Z:bbhvp1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b4832134f801015cb238e8dbb1607a9d5794fcb/pkg/sql/set_cluster_setting.go#L195)):*
> ```Go
> func (n *setClusterSettingNode) startExec(params runParams) error {
> 	if !params.extendedEvalCtx.TxnIsSingleStmt {
> 		return errors.Errorf("SET CLUSTER SETTING cannot be used inside an explicit transaction")
> ```

"inside a multi-statement transaction"
___
*[pkg/sql/tenant.go, line 538 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzRXoUWBaovjQBEknhR:-MzRXoUWBaovjQBEknhS:bbhvp1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b4832134f801015cb238e8dbb1607a9d5794fcb/pkg/sql/tenant.go#L538)):*
> ```Go
> 	// changes are deployed to all Cockroach Cloud serverless hosts.
> 	if !p.extendedEvalCtx.TxnIsSingleStmt {
> 		return errors.Errorf("gc_tenant cannot be used inside a transaction")
> ```

"inside a multi-statement transaction"

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78512)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @miretskiy, and @rafiss)

___
*[pkg/sql/alter_column_type.go, line 262 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzRX2En-V-VyHKv1_KY:-MzTPA5uDHSh2VuK0VOB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b4832134f801015cb238e8dbb1607a9d5794fcb/pkg/sql/alter_column_type.go#L262)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could be good to update the comment
</blockquote></details>

Done.
___
*[pkg/sql/refresh_materialized_view.go, line 34 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzRXbQ92I5dVcLXBmpH:-MzTPcafDGPU1YO1U_9w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b4832134f801015cb238e8dbb1607a9d5794fcb/pkg/sql/refresh_materialized_view.go#L34)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

"in a multi-statement transaction"
</blockquote></details>

Done.
___
*[pkg/sql/session_state.go, line 117 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzRXfvyER59-f3G3j2W:-MzTPdQwDE_RB97-0grg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b4832134f801015cb238e8dbb1607a9d5794fcb/pkg/sql/session_state.go#L117)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

"inside a multi-statement transaction"
</blockquote></details>

Done.
___
*[pkg/sql/set_cluster_setting.go, line 195 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzRXj0DE1uoWFMKlM2Y:-MzTPdv92D3UpqlR85Uy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b4832134f801015cb238e8dbb1607a9d5794fcb/pkg/sql/set_cluster_setting.go#L195)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

"inside a multi-statement transaction"
</blockquote></details>

Done.
___
*[pkg/sql/tenant.go, line 538 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzRXoUWBaovjQBEknhR:-MzTPeaZBj-7mkNWq8xa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b4832134f801015cb238e8dbb1607a9d5794fcb/pkg/sql/tenant.go#L538)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

"inside a multi-statement transaction"
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
looks very close - just one more message to fix. feel free to merge after

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-:-MzVSsCs4KS_DuYNiHYu:b9dyfat)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @fqazi, @miretskiy, and @rafiss)

___
*[pkg/sql/refresh_materialized_view.go, line 34 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzVSNzN2bwgzTBbJK-M:-MzVSNzN2bwgzTBbJK-N:bpqce7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e96c0e69bd7362f1dbb0539da6f0ecbf94d811e/pkg/sql/refresh_materialized_view.go#L34)):*
> ```Go
> ) (planNode, error) {
> 	if !p.extendedEvalCtx.TxnIsSingleStmt {
> 		return nil, pgerror.Newf(pgcode.InvalidTransactionState, "cannot refresh view in a single statement transaction")
> ```

this is saying the opposite. should say "in a multi-statement transaction" (notice the `!` in the if condition)
___
*[pkg/sql/logictest/testdata/logic_test/materialized_view, line 84 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzVSnTG73qMEtY3yL08:-MzVSnTG73qMEtY3yL09:buibi58) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e96c0e69bd7362f1dbb0539da6f0ecbf94d811e/pkg/sql/logictest/testdata/logic_test/materialized_view#L84)):*
> ```
> BEGIN
> 
> statement error  pq: cannot refresh view in a single statement transaction
> ```

should say "mutli-statement"

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78512)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @miretskiy, and @rafiss)

___
*[pkg/sql/refresh_materialized_view.go, line 34 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzVSNzN2bwgzTBbJK-M:-MzVeQf49bf3jysnJazS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e96c0e69bd7362f1dbb0539da6f0ecbf94d811e/pkg/sql/refresh_materialized_view.go#L34)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this is saying the opposite. should say "in a multi-statement transaction" (notice the `!` in the if condition)
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/materialized_view, line 84 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/78512#-MzVSnTG73qMEtY3yL08:-MzVeR8Z1pcl3vOf8LF6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e96c0e69bd7362f1dbb0539da6f0ecbf94d811e/pkg/sql/logictest/testdata/logic_test/materialized_view#L84)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should say "mutli-statement"
</blockquote></details>

Done.

**Pull request merged**
