### PR TITLE
sql: add new Datum type for column name literals

### LINKED ISSUE #12207: sql: pgwire behavior for string arrays is partially incorrect
Sequelize queries various `pg_catalog` tables to assemble an array of column names, using the following query:

```
SELECT i.relname AS name,
       ix.indisprimary AS PRIMARY,
       ix.indisunique AS UNIQUE,
       ix.indkey AS indkey,
       ARRAY_AGG(a.attnum) AS column_indexes,
       ARRAY_AGG(a.attname) AS column_names,
       pg_get_indexdef(ix.indexrelid) AS definition
FROM pg_class t,
     pg_class i,
     pg_index ix,
     pg_attribute a
WHERE t.oid = ix.indrelid
AND   i.oid = ix.indexrelid
AND   a.attrelid = t.oid
AND   t.relkind = 'r'
AND   t.relname = 'customers' -- this query is run once for each table
GROUP BY i.relname,
         ix.indexrelid,
         ix.indisprimary,
         ix.indisunique,
         ix.indkey
ORDER BY i.relname
```

One of the return values is the result of `ARRAY_AGG(a.attname)`, which we treat as an array of strings. We return arrays of strings as strings that look like this: `{'foo','bar','baz'}`.

Sequelize fails to parse the representation of this array that we send over the pg wire protocol for two separate reasons.

1. Sequelize expects that the strings inside the array are not quoted, and in fact postgres returns string arrays that look like `{foo,bar,baz}` unless a string has a `,` character in it in which case it'll be `{foo,"bar,",baz}`.
2. Sequelize expects that the type we report for this array over pgwire is `1003`, corresponding to an array of `name` types. We report that this array is of type `1009`, or an array of `text` types. If we report `1009`, Sequelize actually blows up while trying to parse the returned array.

It shouldn't be too hard to solve the first one. The second one is a little bit more involved - we'll need to make a `Datum` type for column name literal values, as well as a corresponding type for arrays of those. Then we'll need to change the relevant column definitions in `pg_catalog` to use this new type.

### PR DESCRIPTION
**Pull request by jordanlewis**
This PR adds a new column type, `name`, that describes fields that are SQL identifiers. This type is primarily for postgres compatibility -there are several fields in pg_catalog tables with type `name` in
postgres, and at least one ORM (sequelize) expects that the pgwire type returned for these columns corresponds with the `name` type.

`pg_catalog` is also updated to use the new type.

This PR ended up being larger than I would have liked. Ideally, adding `name` shouldn't require adding a new column type to the enum in `structured.proto` since all `name` types are going to stay in virtual tables and not be persisted. Unfortunately it seems like we need to add that new column type anyway - it's used in various non-persistence operations that get done during e.g. `GROUP BY` or array aggregation.

Resolves #12207.

Feedback about ways to simplify this would be very welcome.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12281)

### CODE REVIEW

**Comment by cuongdo** [comment]
Review status: 0 of 21 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/datum.go, line 512 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12281#-KYnr0Th4qRfW4wgl1Zy:-KYnr0Th4qRfW4wgl1Zz:bu10mp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e71bf9d675364bdd1607e6eb3bf4d226116fd108/pkg/sql/parser/datum.go#L512)):*
> ```Go
> 		panic(makeUnsupportedComparisonMessage(d, other))
> 	}
> 	if *d < *v {
> ```

I know this code didn't originate with you, but isn't the rest of the method equivalent to `return strings.Compare(*d.BackingDString(), *v.BackingDString())`?

---

*[pkg/sql/parser/datum.go, line 576 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12281#-KYnrhsL_paM2_V9NPnx:-KYnrhsL_paM2_V9NPny:b-e7eybc) ([raw file](https://github.com/cockroachdb/cockroach/blob/090bb5318d77365c1aa15dd46cea676103eae1e4/pkg/sql/parser/datum.go#L576)):*
> ```Go
> // DName is the Datum for column name literals.
> type DName struct {
> 	DString DString
> ```

Could half of the code below be eliminated by embedding `DString`? e.g. `DString DString` -> `DString`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12281)*

**Comment by jordanlewis** [comment]
Review status: 0 of 21 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/datum.go, line 512 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12281#-KYnr0Th4qRfW4wgl1Zy:-KYnuI9nSOL99LR0XWqA:b-orumjy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e71bf9d675364bdd1607e6eb3bf4d226116fd108/pkg/sql/parser/datum.go#L512)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

I know this code didn't originate with you, but isn't the rest of the method equivalent to `return strings.Compare(*d.BackingDString(), *v.BackingDString())`?
</blockquote></details>

Good point

---

*[pkg/sql/parser/datum.go, line 576 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12281#-KYnrhsL_paM2_V9NPnx:-KYntuZIpMwds3eUcvxI:b-z4825c) ([raw file](https://github.com/cockroachdb/cockroach/blob/090bb5318d77365c1aa15dd46cea676103eae1e4/pkg/sql/parser/datum.go#L576)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

Could half of the code below be eliminated by embedding `DString`? e.g. `DString DString` -> `DString`
</blockquote></details>

Yes - I had this originally, but I got rid of it because it made it really hard to track down some issues. There are lots of methods that `DString` defines, scattered across a few different files, and some of them need to be redefined for `DName`. I could re-embed the struct now that I've tracked down all of the required redefinitions, but it feels slightly disingenuous. Thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12281)*

**Comment by cuongdo** [comment]
Review status: 0 of 21 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/datum.go, line 576 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12281#-KYnrhsL_paM2_V9NPnx:-KYnvFszc6JitTjbs3Lc:b-kfqssr) ([raw file](https://github.com/cockroachdb/cockroach/blob/090bb5318d77365c1aa15dd46cea676103eae1e4/pkg/sql/parser/datum.go#L576)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Yes - I had this originally, but I got rid of it because it made it really hard to track down some issues. There are lots of methods that `DString` defines, scattered across a few different files, and some of them need to be redefined for `DName`. I could re-embed the struct now that I've tracked down all of the required redefinitions, but it feels slightly disingenuous. Thoughts?
</blockquote></details>

Yeah, I see that now. It's probably better to not embed then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12281)*

**Comment by jordanlewis** [comment]
Review status: 0 of 21 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/datum.go, line 512 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12281#-KYnr0Th4qRfW4wgl1Zy:-KYoB2xeZXEpk4YDU53V:b-k5rhkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e71bf9d675364bdd1607e6eb3bf4d226116fd108/pkg/sql/parser/datum.go#L512)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Good point
</blockquote></details>

Actually, if you look at the docs of `strings.Compare`, it seems that it's better not to use it: https://golang.org/src/strings/compare.go?s=490:519#L3 . If I had to guess, this doc is why we're not using `strings.Compare` in the first place. Weird!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12281)*

**Comment by jordanlewis** [comment]
I should mention that I tried the approach of modifying the `Compare` and `Equals` methods on `DString` and `TypeString` to allow comparisons between the two types so as to reduce the number of new comparison operators in this pull request. This approach didn't work, because the type system uses the `Equals` methods on the `TypeFoo` structs to do overload matching as well as comparisons. Pointers on how to clean this aspect up would be appreciated.

**Comment by knz** [comment]
I think we need nathan's input on this. @nvanbenschoten care to comment?

(Perhaps even we'll need to keep this sit until the end of the week when nathan is available again)

---

Reviewed 19 of 19 files at r1.
Review status: 17 of 21 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor.go, line 1422 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12281#-KYohiPqi2cZ0bYrinzl:-KYohiPqi2cZ0bYrinzm:bxijeeo) ([raw file](https://github.com/cockroachdb/cockroach/blob/090bb5318d77365c1aa15dd46cea676103eae1e4/pkg/sql/executor.go#L1422)):*
> ```Go
> 	case parser.TypeTimestampTZ:
> 	case parser.TypeInterval:
> 	case parser.TypeStringArray:
> ```

Here I'm not sure why we special case the array types. Can't we have a general case with FamilyEqual for all the array types?

---

*[pkg/sql/parser/aggregate_builtins.go, line 74 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12281#-KYohw4XmXa2bvl2oPJB:-KYohw4XmXa2bvl2oPJC:b-y9it10) ([raw file](https://github.com/cockroachdb/cockroach/blob/090bb5318d77365c1aa15dd46cea676103eae1e4/pkg/sql/parser/aggregate_builtins.go#L74)):*
> ```Go
> // Exported for use in documentation.
> var Aggregates = map[string][]Builtin{
> 	"array_agg": {
> ```

This ought to be replaced by a single aggregate which takes TypeAny as argument and returns tArray{...} as return value. If you can't figure this out here perhaps file an issue and mark this here with a TODO.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12281#-:-KYoipxco3_o32mrkb0D:be9h5dt)*

**Comment by jordanlewis** [comment]
Review status: 13 of 23 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/sql/executor.go, line 1422 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12281#-KYohiPqi2cZ0bYrinzl:-KYpP2218luiUVgPHVUU:b-miubfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/090bb5318d77365c1aa15dd46cea676103eae1e4/pkg/sql/executor.go#L1422)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Here I'm not sure why we special case the array types. Can't we have a general case with FamilyEqual for all the array types?
</blockquote></details>

Only certain array types are supported. Decimal array types, for instance, are unsupported.

---

*[pkg/sql/parser/aggregate_builtins.go, line 74 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12281#-KYohw4XmXa2bvl2oPJB:-KYpPrtFZwP2xIFvbS88:b-apy1ie) ([raw file](https://github.com/cockroachdb/cockroach/blob/090bb5318d77365c1aa15dd46cea676103eae1e4/pkg/sql/parser/aggregate_builtins.go#L74)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This ought to be replaced by a single aggregate which takes TypeAny as argument and returns tArray{...} as return value. If you can't figure this out here perhaps file an issue and mark this here with a TODO.
</blockquote></details>

I made a TODO.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12281)*

**Comment by jordanlewis** [comment]
Ready for review - I'd definitely like some feedback on the modifications I made to the type checker in commit 3. I think the way I've (ab?)used the `Type` `Equals`/`FamilyEquals` methods warrants attention - specifically I'm not sure if it makes sense to have two types that are equal via Equals but not via FamilyEquals. The rationale here is that `String` and `Name` should be comparable but are not created via the same constructor, the way `FamilyEquals` requires.

**Comment by nvanbenschoten** [comment]
Most of this looks good! However, I don't think I like what's going on in `Equals`/`FamilyEquals` for `TypeName`. It looks like the change is trying to get around the previous decision to disallow implicit mixed-type comparisons. If we want to revisit that discussion, I'd be happy to, but this doesn't seem like the right approach. The change also looks like it's missing a good amount of testing in the parser package.

An alternative idea that came to mind when I heard about adding this change was to instead add better support for type aliasing without needing to add all new datum types. Right now, we map a large number of type names to a single Datum type and then map this single Datum type back to a single OID. As an example, we have a similar issue to what prompted this change with `INT2`. We currently map this to `TypeInt/DInt`, which then maps to `oid.T_int8`. If instead, we could remember the aliasing while using the same internal Datum representation/behavior, we wouldn't need a new Datum type but could support returning the correct OID. Correct me if I'm wrong, but the only reason we're adding this new Datum type is so we can return the right OID. If so, this seems like a somewhat unscalable solution to a problem we'll likely see again.

---

Reviewed 13 of 19 files at r1, 1 of 1 files at r2, 3 of 4 files at r3, 4 of 6 files at r4.
Review status: 21 of 23 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/aggregate_builtins.go, line 74 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12281#-KYohw4XmXa2bvl2oPJB:-KYsE7P6ayx7eFS6fu4u:bkd4eve) ([raw file](https://github.com/cockroachdb/cockroach/blob/090bb5318d77365c1aa15dd46cea676103eae1e4/pkg/sql/parser/aggregate_builtins.go#L74)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I made a TODO.
</blockquote></details>

The issue is that the signature would be `array_agg(T, tArray{T})`, not `array_agg(*, tArray{*})` (ie. the arg type and the array's param type need to be the same, not arbitrary). We don't currently expose a good way to represent this and have pretty much avoided the issue in the past with solutions like this.

@knz: we should chat sometime next week in person about how we'd want to represent cases like this.

---

*[pkg/sql/parser/constant.go, line 303 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12281#-KYsPjswwIJHSEjn5O9D:-KYsPjswwIJHSEjn5O9E:b-lh3y6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/f869548ede077bc20c7c4ba51b1ae3854856950e/pkg/sql/parser/constant.go#L303)):*
> ```Go
> 
> var (
> 	strValAvailAllParsable = []Type{
> ```

You're missing some code here that would allow literal type inference to properly work with the Name type.

---

*[pkg/sql/parser/constant.go, line 330 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12281#-KYsG403dIq8sgBjyQWG:-KYsG404EqhKhtLXO-vw:b-cnl9ez) ([raw file](https://github.com/cockroachdb/cockroach/blob/f869548ede077bc20c7c4ba51b1ae3854856950e/pkg/sql/parser/constant.go#L330)):*
> ```Go
> 	switch typ {
> 	case TypeString:
> 		expr.resString = DString(expr.s)
> ```

While you're here, could you fix this and the TypeBytes case to use their respective constructors?

---

*[pkg/sql/parser/datum.go, line 512 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12281#-KYnr0Th4qRfW4wgl1Zy:-KYsGnMqfwVsufSPHbW1:bljo5x1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e71bf9d675364bdd1607e6eb3bf4d226116fd108/pkg/sql/parser/datum.go#L512)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Actually, if you look at the docs of `strings.Compare`, it seems that it's better not to use it: https://golang.org/src/strings/compare.go?s=490:519#L3 . If I had to guess, this doc is why we're not using `strings.Compare` in the first place. Weird!
</blockquote></details>

Strange! Nice find though

---

*[pkg/sql/parser/datum.go, line 576 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12281#-KYnrhsL_paM2_V9NPnx:-KYsH0jyMT4S0e2rRI-h:b-1qtv4w) ([raw file](https://github.com/cockroachdb/cockroach/blob/090bb5318d77365c1aa15dd46cea676103eae1e4/pkg/sql/parser/datum.go#L576)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

Yeah, I see that now. It's probably better to not embed then.
</blockquote></details>

Maybe just name the field `s` (capital if it needs to be exported) then.

---

*[pkg/sql/parser/expr.go, line 1029 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12281#-KYsRM1ied-Ljq_dWJ1k:-KYsRM1j-bHi7wyXG_oo:bli0rhh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f869548ede077bc20c7c4ba51b1ae3854856950e/pkg/sql/parser/expr.go#L1029)):*
> ```Go
> 
> // validCastTypes returns a set of types that can be cast into the provided type.
> func validCastTypes(t Type) []Type {
> ```

Don't we need some changes here (and in eval.go) to allow the expected casts to work?

---

*[pkg/sql/sqlbase/structured.go, line 1644 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12281#-KYsIYWWdkMJaf2hQlsP:-KYsIYWXd2EXO_Ym66nS:b-fqsjnr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f869548ede077bc20c7c4ba51b1ae3854856950e/pkg/sql/sqlbase/structured.go#L1644)):*
> ```Go
> 		return ColumnType_STRING
> 	case parser.TypeName:
> 		return ColumnType_STRING
> ```

Is this intentional?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12281#-:-KYsQ1ZlG1bClOOejotJ:b-lzyxcs)*

**Comment by jordanlewis** [comment]
TFTR!

I agree that the `Equals`/`FamilyEquals` stuff is sketchy. I didn't realize there was a previous decision to disallow implicit mixed-type comparison actually - agreed that this would not be the right approach for a general solution.

I love the idea of switching this approach out for a type aliasing approach. I think that would be so much cleaner - as you note, `name` types are completely equivalent to `string` types except for how they are represented over pgwire and `SHOW TABLE` and the like. Did you already have ideas about how to add type aliasing to the system? Let's talk about it.

In the meantime, I'll put this PR on hold.

---

Review status: 21 of 23 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/expr.go, line 1029 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12281#-KYsRM1ied-Ljq_dWJ1k:-KYsmdTA3YWa5k9M7Xf7:b-muzp5t) ([raw file](https://github.com/cockroachdb/cockroach/blob/f869548ede077bc20c7c4ba51b1ae3854856950e/pkg/sql/parser/expr.go#L1029)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Don't we need some changes here (and in eval.go) to allow the expected casts to work?
</blockquote></details>

Yeah, I just didn't get to that in this commit.

---

*[pkg/sql/sqlbase/structured.go, line 1644 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12281#-KYsIYWWdkMJaf2hQlsP:-KYsmh4ixJnNF9ujRFdm:b-26yxzk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f869548ede077bc20c7c4ba51b1ae3854856950e/pkg/sql/sqlbase/structured.go#L1644)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this intentional?
</blockquote></details>

No - in fact I'm surprised tests pass with this. I left this here by accident when I was experimenting to see whether we could get away with not adding a new column type kind to structured.proto.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12281#-:-KYsmrxge63pvAOkdwga:b-7a07ik)*

**Comment by jordanlewis** [comment]
Closing this - superseded by #12641

**Pull request closed without merging**
