### PR TITLE
opt: add missing initialization to Metadata.Init

### LINKED ISSUE #43773: sentry: opt: assertion failed "CopyFrom requires empty destination"
This issue was autofiled by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry link: https://sentry.io/organizations/cockroach-labs/issues/1422508596/?referrer=webhooks_plugin

Panic message:

>conn_executor.go:442: panic while executing 1 statements: SELECT _._, _._ AS _, has_schema_privilege(_._, _) AS _, has_schema_privilege(_._, _) AS _ FROM _ AS _ WHERE (_._ = _::OID) AND (NOT ((((_._ = _) AND EXISTS (SELECT _ FROM _ WHERE (_ = _) AND (_ = _._) LIMIT _)) OR ((_._ = _) AND EXISTS (SELECT _ FROM _ WHERE (_ = _) AND (_ = _._) LIMIT _))) OR ((_._ = _) AND EXISTS (SELECT _ FROM _ WHERE (_ = _) AND (_ = _._) LIMIT _)))) ORDER BY _: caused by <redacted>

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/conn_executor.go#L441-L443 in pkg/sql.(*Server).ServeConn.func1
/usr/local/go/src/runtime/panic.go#L521-L523 in runtime.gopanic
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/opt/metadata.go#L151-L153 in pkg/sql/opt.(*Metadata).CopyFrom
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/opt/norm/factory.go#L198-L200 in pkg/sql/opt/norm.(*Factory).CopyAndReplace
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/opt/exec/execbuilder/relational.go#L604-L606 in pkg/sql/opt/exec/execbuilder.ReplaceVars
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/apply_join.go#L256-L258 in pkg/sql.(*applyJoinNode).Next
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/plan_node_to_row_source.go#L170-L172 in pkg/sql.(*planNodeToRowSource).Next
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/rowexec/aggregator.go#L400-L402 in pkg/sql/rowexec.(*hashAggregator).accumulateRows
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/rowexec/aggregator.go#L637-L639 in pkg/sql/rowexec.(*hashAggregator).Next
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/row_source_to_plan_node.go#L74-L76 in pkg/sql.(*rowSourceToPlanNode).Next
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/ordinality.go#L95-L97 in pkg/sql.(*ordinalityNode).Next
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/apply_join.go#L215-L217 in pkg/sql.(*applyJoinNode).Next
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/plan_node_to_row_source.go#L170-L172 in pkg/sql.(*planNodeToRowSource).Next
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/rowexec/aggregator.go#L400-L402 in pkg/sql/rowexec.(*hashAggregator).accumulateRows
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/rowexec/aggregator.go#L637-L639 in pkg/sql/rowexec.(*hashAggregator).Next
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/rowexec/ordinality.go#L87-L89 in pkg/sql/rowexec.(*ordinalityProcessor).Next
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/row_source_to_plan_node.go#L74-L76 in pkg/sql.(*rowSourceToPlanNode).Next
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/apply_join.go#L215-L217 in pkg/sql.(*applyJoinNode).Next
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/plan_node_to_row_source.go#L170-L172 in pkg/sql.(*planNodeToRowSource).Next
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/rowexec/aggregator.go#L400-L402 in pkg/sql/rowexec.(*hashAggregator).accumulateRows
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/rowexec/aggregator.go#L637-L639 in pkg/sql/rowexec.(*hashAggregator).Next
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/rowexec/sorter.go#L295-L297 in pkg/sql/rowexec.(*sortAllProcessor).fill
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/rowexec/sorter.go#L276-L278 in pkg/sql/rowexec.(*sortAllProcessor).Start
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/execinfra/processorsbase.go#L723-L725 in pkg/sql/execinfra.(*ProcessorBase).Run
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/flowinfra/flow.go#L374-L376 in pkg/sql/flowinfra.(*FlowBase).Run
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/distsql_running.go#L371-L373 in pkg/sql.(*DistSQLPlanner).Run
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/distsql_running.go#L996-L998 in pkg/sql.(*DistSQLPlanner).PlanAndRun
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/conn_executor_exec.go#L824-L826 in pkg/sql.(*connExecutor).execWithDistSQLEngine
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/conn_executor_exec.go#L716-L718 in pkg/sql.(*connExecutor).dispatchToExecutionEngine
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/conn_executor_exec.go#L415-L417 in pkg/sql.(*connExecutor).execStmtInOpenState
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/conn_executor_exec.go#L97-L99 in pkg/sql.(*connExecutor).execStmt
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/conn_executor.go#L1242-L1244 in pkg/sql.(*connExecutor).execCmd
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/conn_executor.go#L1171-L1173 in pkg/sql.(*connExecutor).run
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/conn_executor.go#L443-L445 in pkg/sql.(*Server).ServeConn
https://github.com/cockroachdb/cockroach/blob/3cbd05602d4aeaebbccea18d66ad0fdf8db482a5/pkg/sql/pgwire/conn.go#L583-L585 in pkg/sql/pgwire.(*conn).processCommandsAsync.func1
</details>

```
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn.func1 at line 442
/usr/local/go/src/runtime/panic.go in runtime.gopanic at line 522
pkg/sql/opt/metadata.go in pkg/sql/opt.(*Metadata).CopyFrom at line 152
pkg/sql/opt/norm/factory.go in pkg/sql/opt/norm.(*Factory).CopyAndReplace at line 199
pkg/sql/opt/exec/execbuilder/relational.go in pkg/sql/opt/exec/execbuilder.ReplaceVars at line 605
pkg/sql/apply_join.go in pkg/sql.(*applyJoinNode).Next at line 257
pkg/sql/plan_node_to_row_source.go in pkg/sql.(*planNodeToRowSource).Next at line 171
pkg/sql/rowexec/aggregator.go in pkg/sql/rowexec.(*hashAggregator).accumulateRows at line 401
pkg/sql/rowexec/aggregator.go in pkg/sql/rowexec.(*hashAggregator).Next at line 638
pkg/sql/row_source_to_plan_node.go in pkg/sql.(*rowSourceToPlanNode).Next at line 75
pkg/sql/ordinality.go in pkg/sql.(*ordinalityNode).Next at line 96
pkg/sql/apply_join.go in pkg/sql.(*applyJoinNode).Next at line 216
pkg/sql/plan_node_to_row_source.go in pkg/sql.(*planNodeToRowSource).Next at line 171
pkg/sql/rowexec/aggregator.go in pkg/sql/rowexec.(*hashAggregator).accumulateRows at line 401
pkg/sql/rowexec/aggregator.go in pkg/sql/rowexec.(*hashAggregator).Next at line 638
pkg/sql/rowexec/ordinality.go in pkg/sql/rowexec.(*ordinalityProcessor).Next at line 88
pkg/sql/row_source_to_plan_node.go in pkg/sql.(*rowSourceToPlanNode).Next at line 75
pkg/sql/apply_join.go in pkg/sql.(*applyJoinNode).Next at line 216
pkg/sql/plan_node_to_row_source.go in pkg/sql.(*planNodeToRowSource).Next at line 171
pkg/sql/rowexec/aggregator.go in pkg/sql/rowexec.(*hashAggregator).accumulateRows at line 401
pkg/sql/rowexec/aggregator.go in pkg/sql/rowexec.(*hashAggregator).Next at line 638
pkg/sql/rowexec/sorter.go in pkg/sql/rowexec.(*sortAllProcessor).fill at line 296
pkg/sql/rowexec/sorter.go in pkg/sql/rowexec.(*sortAllProcessor).Start at line 277
pkg/sql/execinfra/processorsbase.go in pkg/sql/execinfra.(*ProcessorBase).Run at line 724
pkg/sql/flowinfra/flow.go in pkg/sql/flowinfra.(*FlowBase).Run at line 375
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 372
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 997
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 825
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 717
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 416
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 98
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 1243
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 1172
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 444
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 584
```

| Tag | Value |
|---|---|
| Cockroach Release | `v19.2.2` |
| Cockroach SHA: | 3cbd05602d4aeaebbccea18d66ad0fdf8db482a5 |
| Platform | linux amd64 |
| Distribution | CCL |
| Environment | v19.2.2 |
| Command | start-single-node |
| Go Version | `go1.12.12`|
| # of CPUs |2 |
| # of Goroutines |144 |

### PR DESCRIPTION
**Pull request by RaduBerinde**
We weren't resetting the sequences. Improved the comments and the
test.

Fixes #43773.

Release note (bug fix): fixed "CopyFrom requires empty destination"
internal error.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44114#-:-Lz7rQmxE4F4smH_24H5:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, and @RaduBerinde)

___
*[pkg/sql/opt/metadata.go, line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44114#-Lz7pFfq9-cHHXWK8CEq:-Lz7pFfq9-cHHXWK8CEr:b-70k02d) ([raw file](https://github.com/cockroachdb/cockroach/blob/612579277d162b69e8309fe09b987f989fe6fb49/pkg/sql/opt/metadata.go#L92)):*
> ```Go
> 	// needed for EXPLAIN (opt, env).
> 	views []cat.View
> 	//
> ```

[nit] extra comment line
___
*[pkg/sql/opt/metadata.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44114#-Lz7pozTAT0GNup86lvL:-Lz7pozTAT0GNup86lvM:bj9pfq5) ([raw file](https://github.com/cockroachdb/cockroach/blob/612579277d162b69e8309fe09b987f989fe6fb49/pkg/sql/opt/metadata.go#L181)):*
> ```Go
> 	}
> 	// TODO(radu): we aren't copying the scalar expressions in Constraints and
> 	// ComputedCols..
> ```

I guess this is a problem now that we're no longer initializing them lazily? Would help to update the comment to explain why this is ok or not.
___
*[pkg/sql/opt/metadata.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44114#-Lz7qCa7-Y6zGLCuBji6:-Lz7qCa7-Y6zGLCuBji7:b-lxt1ev) ([raw file](https://github.com/cockroachdb/cockroach/blob/612579277d162b69e8309fe09b987f989fe6fb49/pkg/sql/opt/metadata.go#L183)):*
> ```Go
> 	// ComputedCols..
> 
> 	md.views = append(md.views, from.views...)
> ```

Maybe move this below `md.deps` to keep everything in the same order as the struct and `Init`?

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44114#-:-Lz7yRDb6NZk4nJRS_tJ:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, and @rytaft)

___
*[pkg/sql/opt/metadata.go, line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44114#-Lz7pFfq9-cHHXWK8CEq:-Lz7xl0i-3jxNMCD2Edw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/612579277d162b69e8309fe09b987f989fe6fb49/pkg/sql/opt/metadata.go#L92)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] extra comment line
</blockquote></details>

Done.
___
*[pkg/sql/opt/metadata.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44114#-Lz7pozTAT0GNup86lvL:-Lz7xm6YDytesIQy-j73:b-pkzgeu) ([raw file](https://github.com/cockroachdb/cockroach/blob/612579277d162b69e8309fe09b987f989fe6fb49/pkg/sql/opt/metadata.go#L181)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I guess this is a problem now that we're no longer initializing them lazily? Would help to update the comment to explain why this is ok or not.
</blockquote></details>

It was always a problem, these things are initialized in the optbuilder. In practice we don't see issues because they're strictly scalar expressions, but I think we should copy them.
___
*[pkg/sql/opt/metadata.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44114#-Lz7qCa7-Y6zGLCuBji6:-Lz7yOH5-AP6c7HYDlXd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/612579277d162b69e8309fe09b987f989fe6fb49/pkg/sql/opt/metadata.go#L183)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Maybe move this below `md.deps` to keep everything in the same order as the struct and `Init`?
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44114)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/metadata.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44114#-Lz7pozTAT0GNup86lvL:-Lz82Z_jE85AgCicFaGY:b-y9my6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/612579277d162b69e8309fe09b987f989fe6fb49/pkg/sql/opt/metadata.go#L181)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It was always a problem, these things are initialized in the optbuilder. In practice we don't see issues because they're strictly scalar expressions, but I think we should copy them.
</blockquote></details>

Sorry for being dense -- why does it matter that they are strictly scalar?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44114)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @justinj, and @rytaft)

___
*[pkg/sql/opt/metadata.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44114#-Lz7pozTAT0GNup86lvL:-Lz83Y237-d6R-Ssiips:b-n1h6s) ([raw file](https://github.com/cockroachdb/cockroach/blob/612579277d162b69e8309fe09b987f989fe6fb49/pkg/sql/opt/metadata.go#L181)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Sorry for being dense -- why does it matter that they are strictly scalar?
</blockquote></details>

Sharing expressions between memos is bad because optimization sets physical properties in them. There are no physical properties to be set in scalars. There may be other ways in which sharing these expressions is bad though.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44114)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @justinj)

___
*[pkg/sql/opt/metadata.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44114#-Lz7pozTAT0GNup86lvL:-Lz8Gpjd4J74ckW0lp-L:b-6yc0nv) ([raw file](https://github.com/cockroachdb/cockroach/blob/612579277d162b69e8309fe09b987f989fe6fb49/pkg/sql/opt/metadata.go#L181)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Sharing expressions between memos is bad because optimization sets physical properties in them. There are no physical properties to be set in scalars. There may be other ways in which sharing these expressions is bad though.
</blockquote></details>

:thumbsup: thanks!

**Pull request merged**
