### PR TITLE
sql: enable primary key change into a hash sharded primary key

### LINKED ISSUE #43769: support primary key change into a hash sharded index
Once #42922 merges, we should extend `ALTER PRIMARY KEY` to allow switching to an index that is hash sharded.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #43769.

This PR enables primary key changes into primary
indexes that are hash sharded.

Release note (sql change): This PR allows for primary key
changes into hash sharded indexes.

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

Not too bad! Could maybe use some tests around the mixing of interleaving and hash sharding. 

> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44993#-:-M-qAq7S9U7YePBTkZO-:b-nitpuh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/logictest/testdata/logic_test/alter_primary_key, line 436 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44993#-M-qAhaL9F1q4oL9oV8E:-M-qAhaN4STYOyZR1VXw:bfltzlz) ([raw file](https://github.com/cockroachdb/cockroach/blob/674b7227b8b320c1c111d6a32351f0173231f5b7/pkg/sql/logictest/testdata/logic_test/alter_primary_key#L436)):*
> ```
> statement ok
> ROLLBACK
> ```

Want to add tests for the error cases around interleaving?

**Comment by rohany** [comment]
Woops, forgot about that, will update.

**Review by ajwerner — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 7 files at r1, 3 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44993#-:-M-qs4kQ5MUjIXgIAviu:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by rohany** [comment]
bors r=ajwerner

**Pull request merged**
