### PR TITLE
sql: use catalog.TableColSet instead of map[descpb.ColumnID]struct{}

### PR DESCRIPTION
**Pull request by mgartner**
#### sql: move TableColSet from schemaexpr package to catalog

The `TableColSet` type describes a set of columns of a table. This
commit moves the type to the `catalog` package because it its usage is
not specific to the functionality in the `schemaexpr` package.

Release note: None

#### sql: use catalog.TableColSet instead of map[descpb.ColumnID]struct{}

This commit converts all instances where a set of column IDs was
implemented with a `map[descpb.ColumnID]struct{}` with the more
efficient `catalog.TableColSet`, a wrapper around `util.FastIntSet`.

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm_strong: 

> Reviewed 7 of 7 files at r1, 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56660#-:-MM1uLOJ0C4bZIRDJgGb:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Review by jordanlewis — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56660#-:-MM2syrF0DEn7SdT5ruB:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/catalog/tabledesc/structured.go, line 3667 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56660#-MM2re2y9VoyPkqivwik:-MM2re2y9VoyPkqivwil:b-8yzp3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/f073cdeaeea2f87ebbb5683fdd4431ecc72a323c/pkg/sql/catalog/tabledesc/structured.go#L3667)):*
> ```Go
> 
> 	cc.ColumnIDs = make([]descpb.ColumnID, 0, colIDsUsed.Len())
> 	colIDsUsed.ForEach(func(colID descpb.ColumnID) {
> ```

We could do better here: I think this will allocate because of the closure. We could instead use the .Next() iteration pattern on FastIntSet. I notice that .Next() isn't exposed to the wrapper, but we could expose it and make this loop a little bit cheaper.
___
*[pkg/sql/schemaexpr/default_exprs.go, line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56660#-MM2sq3M0ZZyHqUvYT4n:-MM2sq3M0ZZyHqUvYT4o:be4oepv) ([raw file](https://github.com/cockroachdb/cockroach/blob/f073cdeaeea2f87ebbb5683fdd4431ecc72a323c/pkg/sql/schemaexpr/default_exprs.go#L105)):*
> ```Go
> 		if inSet(col) {
> 			if !colIDSet.Contains(col.ID) {
> 				colIDSet.Add(col.ID)
> ```

Any reason to do the contains check first? Why not unconditionally add?

**Review by jordanlewis — COMMENTED** [review]
> Reviewed 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56660)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56660)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/catalog/tabledesc/structured.go, line 3667 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56660#-MM2re2y9VoyPkqivwik:-MM3Ercw9C5a_shPS2vB:bdpg4da) ([raw file](https://github.com/cockroachdb/cockroach/blob/f073cdeaeea2f87ebbb5683fdd4431ecc72a323c/pkg/sql/catalog/tabledesc/structured.go#L3667)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

We could do better here: I think this will allocate because of the closure. We could instead use the .Next() iteration pattern on FastIntSet. I notice that .Next() isn't exposed to the wrapper, but we could expose it and make this loop a little bit cheaper.
</blockquote></details>

Ahh, I wasn't sure if the closure would be significant enough. Done.
___
*[pkg/sql/schemaexpr/default_exprs.go, line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56660#-MM2sq3M0ZZyHqUvYT4n:-MM3Fgmc7mwWAI-LIX1U:b-xyalk8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f073cdeaeea2f87ebbb5683fdd4431ecc72a323c/pkg/sql/schemaexpr/default_exprs.go#L105)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Any reason to do the contains check first? Why not unconditionally add?
</blockquote></details>

We only want to append to `cols` if `col.ID` is not yet in the set, so we need to do the contains check before the `Add`. I could move the `Add` until after the `if` block, but I don't see any advantage to that.

**Review by jordanlewis — APPROVED** [review]
Thanks for the revisions - looks good once you get the tests to pass.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56660#-:-MMD6RYB31Dz3uEVACVT:b-5l4fkk)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @jordanlewis, and @mgartner)

___
*[pkg/sql/catalog/tabledesc/structured.go, line 3667 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56660#-MM2re2y9VoyPkqivwik:-MMD68mz2QVTCX6mUkaz:b-crlpky) ([raw file](https://github.com/cockroachdb/cockroach/blob/f073cdeaeea2f87ebbb5683fdd4431ecc72a323c/pkg/sql/catalog/tabledesc/structured.go#L3667)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Ahh, I wasn't sure if the closure would be significant enough. Done.
</blockquote></details>

Probably not super significant, but changing it is so easy that feels like we might as well.
___
*[pkg/sql/schemaexpr/default_exprs.go, line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56660#-MM2sq3M0ZZyHqUvYT4n:-MMD6H3UEKgnAFXc-1QN:bvc38qx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f073cdeaeea2f87ebbb5683fdd4431ecc72a323c/pkg/sql/schemaexpr/default_exprs.go#L105)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

We only want to append to `cols` if `col.ID` is not yet in the set, so we need to do the contains check before the `Add`. I could move the `Add` until after the `if` block, but I don't see any advantage to that.
</blockquote></details>

Gotcha, ok.

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
