### PR TITLE
importccl: Improve delimited import performance.

### PR DESCRIPTION
**Pull request by miretskiy**
Parallelize mysql delimited import code to improve
it's throughput by around ~5x.

Release notes (performance): Improve delimited import throughput.

### CODE REVIEW

**Comment by miretskiy** [comment]
@dt @spaskob 
Just rebased on top of newly submitted avro changes -- so, this pr is ready for a review.

**Comment by miretskiy** [comment]
Sorry -- not ready for rewview.  Found some problems.

**Comment by miretskiy** [comment]
@spaskob  @dt 
Ready for review.  I've verified that all DELIMITED tests (TestImportData) do pass.

**Review by spaskob — APPROVED** [review]
> Reviewed 1 of 10 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45543)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @spaskob)

**Comment by kenliu** [comment]
5x performance improvement! Nice work.

**Pull request merged**
