### PR TITLE
distsql: support UNION operation

### PR DESCRIPTION
**Pull request by solongordon**
The distsql physical planner now supports UNION. This is implemented
just like UNION ALL but with additional distinct processors.

Release note (performance improvement): Support distributed execution of
UNION queries.

### CODE REVIEW

**Comment by arjunravinarayan** [comment]
:lgtm: modulo adding a few more tests.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 365 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175#-L1u9nh_wf-sc07Gpo0E:-L1u9nh_wf-sc07Gpo0F:bvebt4h) ([raw file](https://github.com/cockroachdb/cockroach/blob/486e89c139f272a8717dac1cf5ff89268bd57f38/pkg/sql/distsql_physical_planner.go#L365)):*
> ```Go
> 
> 	case *unionNode:
> 		// Only UNION and UNION ALL are supported so far.
> ```

AFAIK this comment is no longer necessary.

---

*[pkg/sql/distsql_physical_planner.go, line 1939 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175#-L1uAHwvrv2uTPAc9bCK:-L1uAHwvrv2uTPAc9bCL:b-u11owf) ([raw file](https://github.com/cockroachdb/cockroach/blob/486e89c139f272a8717dac1cf5ff89268bd57f38/pkg/sql/distsql_physical_planner.go#L1939)):*
> ```Go
> 		// results have been grouped together.
> 		//
> 		// Note there is the potential for further optimization here since rows
> ```

The current planning is not ideal - if the data is completely unordered and random, then we currently do 3x as much work as necessary. We should add that information to the comment.

---

*[pkg/sql/logictest/testdata/logic_test/distsql_union, line 59 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175#-L1u9hcO0czuiOH12yeL:-L1u9hcPNAzTr90A6Hgm:b-r219ry) ([raw file](https://github.com/cockroachdb/cockroach/blob/486e89c139f272a8717dac1cf5ff89268bd57f38/pkg/sql/logictest/testdata/logic_test/distsql_union#L59)):*
> ```
> https://cockroachdb.github.io/distsqlplan/decode.html?eJzElU-PokAQxe_7KTZ13d7EavAfJ69edOPObcKBoSuGRGnS3SQ6xu8-AQ6ORquHEODIn997r7teUhfItaJNciQL0TsgCJAgIAABIQiYQiygMDola7WpfmmAtTpBNBGQ5UXpqtexgFQbgugCLnMHggjeko8D7ShRZECAIpdkh9qkMNkxMefV6fwJArali36vEOKrAF26m551yZ4gwqsY3FO28fyvjXu0W-Gfl-LBOOI3TW0UGVLPRJ8k2Oi_urj795V3eOeNI7RjGE_ZxrPbAHsVlyNMaBhP2caz10vsJh6MMKFhPGUbz14vsZt4OMKEhvGUbTx7vcReF-yObKFzSz_acJNqQZLaU7NQrS5NSv-MTmub5nFbc_ULRdY1X2XzsM6bT1XA7zCycMDDkoXDOxgf4aALHPJnRj73lKXnPDxj4QUPz7scetEFXrIwem4M-ZKhr2V8zTzRsVPPkC8aTj3R-arhzIPzXfNl58vmo_m24dITne-bnHhwvnGe7JIv3CMdX399BQAA__9E1reF
> 
> query I
> ```

I'd like to see a couple more tests: currently you union two sets that are identical (but with different orderings). I'd like to also see a test of two sets that are completely nonidentical, and a test of two sets that are partially overlapping.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175#-:-L1uB-JKw8qOAjvIHstY:bw6xyzx)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 1942 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175#-L1t5cqL4oqr2SEN7riJ:-L1t5cqL4oqr2SEN7riK:b-yhoron) ([raw file](https://github.com/cockroachdb/cockroach/blob/486e89c139f272a8717dac1cf5ff89268bd57f38/pkg/sql/distsql_physical_planner.go#L1942)):*
> ```Go
> 		// are not deduplicated between left and right until the single group
> 		// stage. In the worst case (total duplication), this causes double the
> 		// amount of data to be streamed as necessary.
> ```

We should consult the physicalProps of each input and check for a strong key (see similar code in expandDistinctNode). If we have a key, then we know the rows on that side are already unique, so we can elide the local stage.  Actually, I think we have other code that would benefit from the same so you can just leave a TODO and file an issue.

---

*[pkg/sql/distsql_physical_planner.go, line 1954 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175#-L1t50qNHirRWAQckF6M:-L1t50qOgWxdhFTEXadw:b4x4bgo) ([raw file](https://github.com/cockroachdb/cockroach/blob/486e89c139f272a8717dac1cf5ff89268bd57f38/pkg/sql/distsql_physical_planner.go#L1954)):*
> ```Go
> 			},
> 		}
> ```

I would skip adding the local stage if that plan has only one ResultStream on the same node. On a single node, we don't want three processors instead of one.

Ideally, even if there are multiple streams, we should put a processor only on those that are on different nodes. But it would add some complexity (we can't use AddNoGroupingStage anymore) so I'm not sure it's worth it.

---

*[pkg/sql/logictest/testdata/logic_test/distsql_union, line 117 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175#-L1t81LztlNYPOoGl3BY:-L1t81LztlNYPOoGl3BZ:b-tcnkom) ([raw file](https://github.com/cockroachdb/cockroach/blob/486e89c139f272a8717dac1cf5ff89268bd57f38/pkg/sql/logictest/testdata/logic_test/distsql_union#L117)):*
> ```
> 5
> ```

[nit] extra line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175)*

**Comment by solongordon** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 365 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175#-L1u9nh_wf-sc07Gpo0E:-L1w_0rimRsL9NCGd_w9:btkk3jm) ([raw file](https://github.com/cockroachdb/cockroach/blob/486e89c139f272a8717dac1cf5ff89268bd57f38/pkg/sql/distsql_physical_planner.go#L365)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

AFAIK this comment is no longer necessary.
</blockquote></details>

Confusingly the `unionNode` can also represent `INTERSECT` or `EXCEPT`.

---

*[pkg/sql/distsql_physical_planner.go, line 1939 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175#-L1uAHwvrv2uTPAc9bCK:-L1wmI547CP4jLJsAuqy:bxndj8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/486e89c139f272a8717dac1cf5ff89268bd57f38/pkg/sql/distsql_physical_planner.go#L1939)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

The current planning is not ideal - if the data is completely unordered and random, then we currently do 3x as much work as necessary. We should add that information to the comment.
</blockquote></details>

Would you mind elaborating on this? How might we detect in advance that we're doing unnecessary work in this scenario and plan differently?

---

*[pkg/sql/distsql_physical_planner.go, line 1942 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175#-L1t5cqL4oqr2SEN7riJ:-L1wcfb9o-_KPNuowNh9:b9q43ej) ([raw file](https://github.com/cockroachdb/cockroach/blob/486e89c139f272a8717dac1cf5ff89268bd57f38/pkg/sql/distsql_physical_planner.go#L1942)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We should consult the physicalProps of each input and check for a strong key (see similar code in expandDistinctNode). If we have a key, then we know the rows on that side are already unique, so we can elide the local stage.  Actually, I think we have other code that would benefit from the same so you can just leave a TODO and file an issue.
</blockquote></details>

Ah good point. Yeah, looks like `createPlanForDistinct` would benefit from this as well. I'll create an issue.

---

*[pkg/sql/distsql_physical_planner.go, line 1954 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175#-L1t50qNHirRWAQckF6M:-L1wiHTpCx-WNqPHkA-B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/486e89c139f272a8717dac1cf5ff89268bd57f38/pkg/sql/distsql_physical_planner.go#L1954)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I would skip adding the local stage if that plan has only one ResultStream on the same node. On a single node, we don't want three processors instead of one.

Ideally, even if there are multiple streams, we should put a processor only on those that are on different nodes. But it would add some complexity (we can't use AddNoGroupingStage anymore) so I'm not sure it's worth it.
</blockquote></details>

Done.

---

*[pkg/sql/logictest/testdata/logic_test/distsql_union, line 59 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175#-L1u9hcO0czuiOH12yeL:-L1wjLB-J382ie0K2DQT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/486e89c139f272a8717dac1cf5ff89268bd57f38/pkg/sql/logictest/testdata/logic_test/distsql_union#L59)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

I'd like to see a couple more tests: currently you union two sets that are identical (but with different orderings). I'd like to also see a test of two sets that are completely nonidentical, and a test of two sets that are partially overlapping.
</blockquote></details>

Done.

---

*[pkg/sql/logictest/testdata/logic_test/distsql_union, line 117 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175#-L1t81LztlNYPOoGl3BY:-L1w_l6QA1V23AIZVqtS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/486e89c139f272a8717dac1cf5ff89268bd57f38/pkg/sql/logictest/testdata/logic_test/distsql_union#L117)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] extra line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsql_physical_planner.go, line 1954 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175#-L1t50qNHirRWAQckF6M:-L1wwM9wZTijGDshz7gn:bptv618) ([raw file](https://github.com/cockroachdb/cockroach/blob/486e89c139f272a8717dac1cf5ff89268bd57f38/pkg/sql/distsql_physical_planner.go#L1954)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The local stage could still be worthwhile if the one stream is on a different node than the final stage (which is `dsp.nodeDesc.NodeID`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175)*

**Comment by solongordon** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsql_physical_planner.go, line 1954 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175#-L1t50qNHirRWAQckF6M:-L1xP3Yg3o2CcgfPdwj0:bps343f) ([raw file](https://github.com/cockroachdb/cockroach/blob/486e89c139f272a8717dac1cf5ff89268bd57f38/pkg/sql/distsql_physical_planner.go#L1954)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The local stage could still be worthwhile if the one stream is on a different node than the final stage (which is `dsp.nodeDesc.NodeID`).
</blockquote></details>

Ah makes sense. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175)*

**Comment by arjunravinarayan** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 1939 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175#-L1uAHwvrv2uTPAc9bCK:-L1xREI3oPLBXSo-qHm3:b8o3eb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/486e89c139f272a8717dac1cf5ff89268bd57f38/pkg/sql/distsql_physical_planner.go#L1939)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Would you mind elaborating on this? How might we detect in advance that we're doing unnecessary work in this scenario and plan differently?
</blockquote></details>

If we have a fine-grained sort ordering (i.e. sort on all columns) on columns then doing the distincts on the left, right, and then finally would be fine. If we don't have a sort ordering at all, then the distinct processors are going to buffer the entire streams. So having 2 levels of distinct processing will double the latency of the distinct stage.

It also depends "how good" the sort is (i.e. we need to examine histograms of the values, which we can't do as of yet) - a sort ordering where the amount of duplication post-sorting is minimal would benefit greatly from this plan. A completely unsorted bucket of rows would probably be better off with a single final sorting step.

None of this can be sanely detected without all the optimizer work. The comment here led me to believe that you thought the enumerated optimization is the only potential one, but that's upon further reflection, I think that's just me misreading. Perhaps you can say "Note there is the potential for further optimization, for example the rows are not deduplicated...". 

---

*[pkg/sql/logictest/testdata/logic_test/distsql_union, line 59 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175#-L1u9hcO0czuiOH12yeL:-L1xXUp34a31-3wjvvCc:bkpimz6) ([raw file](https://github.com/cockroachdb/cockroach/blob/486e89c139f272a8717dac1cf5ff89268bd57f38/pkg/sql/logictest/testdata/logic_test/distsql_union#L59)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Whenever you add a test, also add the corresponding `SELECT "URL" FROM` test as well just preceding the test. The test themselves LGTM, thank you!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175)*

**Comment by solongordon** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 1939 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175#-L1uAHwvrv2uTPAc9bCK:-L1xdYv5TLs2MREL6Zfv:b-hnl8o1) ([raw file](https://github.com/cockroachdb/cockroach/blob/486e89c139f272a8717dac1cf5ff89268bd57f38/pkg/sql/distsql_physical_planner.go#L1939)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

If we have a fine-grained sort ordering (i.e. sort on all columns) on columns then doing the distincts on the left, right, and then finally would be fine. If we don't have a sort ordering at all, then the distinct processors are going to buffer the entire streams. So having 2 levels of distinct processing will double the latency of the distinct stage.

It also depends "how good" the sort is (i.e. we need to examine histograms of the values, which we can't do as of yet) - a sort ordering where the amount of duplication post-sorting is minimal would benefit greatly from this plan. A completely unsorted bucket of rows would probably be better off with a single final sorting step.

None of this can be sanely detected without all the optimizer work. The comment here led me to believe that you thought the enumerated optimization is the only potential one, but that's upon further reflection, I think that's just me misreading. Perhaps you can say "Note there is the potential for further optimization, for example the rows are not deduplicated...". 
</blockquote></details>

Got it, thank you. Yeah, when I wrote the comment I was only thinking about optimizing network I/O. I'll make that clearer.

---

*[pkg/sql/logictest/testdata/logic_test/distsql_union, line 59 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175#-L1u9hcO0czuiOH12yeL:-L1xhG2Tvr8URbyideh_:bhiz6t4) ([raw file](https://github.com/cockroachdb/cockroach/blob/486e89c139f272a8717dac1cf5ff89268bd57f38/pkg/sql/logictest/testdata/logic_test/distsql_union#L59)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Whenever you add a test, also add the corresponding `SELECT "URL" FROM` test as well just preceding the test. The test themselves LGTM, thank you!
</blockquote></details>

Oops, I had the order swapped. Fixed that and added the missing URL checks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175)*

**Comment by arjunravinarayan** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175#-:-L1xki7e42zGGgq69ZQf:bnfp4nl)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsql_physical_planner.go, line 1921 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175#-L1xlG0hflcpr73NgEuf:-L1xlG0hflcpr73NgEug:b-dac1xs) ([raw file](https://github.com/cockroachdb/cockroach/blob/9de9310bbcc8b574985a5a873bb80df9a4fe0f8d/pkg/sql/distsql_physical_planner.go#L1921)):*
> ```Go
> }
> 
> // isSingleNode returns true if a physical plan only involves one node.
> ```

[nit] The name and comment are appropriate for a function that doesn't do the NodeID check.. Maybe `isOnlyOnGateway`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175#-:-L1xlXGASvhqHM7HbwxT:bnfp4nl)*

**Comment by solongordon** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/distsql_physical_planner.go, line 1921 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175#-L1xlG0hflcpr73NgEuf:-L1xqgzMjOsOQ9fSNty1:b-szy9ji) ([raw file](https://github.com/cockroachdb/cockroach/blob/9de9310bbcc8b574985a5a873bb80df9a4fe0f8d/pkg/sql/distsql_physical_planner.go#L1921)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] The name and comment are appropriate for a function that doesn't do the NodeID check.. Maybe `isOnlyOnGateway`
</blockquote></details>

Thanks, still figuring out terminology.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21175)*

**Pull request merged**
