### PR TITLE
vector: add vector.Set implementation

### PR DESCRIPTION
**Pull request by andy-kimball**
Implement vector.Set, which is a set of float32 vectors of equal dimension. Vectors in the set are stored contiguously in a slice, in row-wise order. Future PR's will take advantage of this layout to implement fast set operations.

Epic: CRDB-42943

Release note: None

### CODE REVIEW

**Review by DrewKimball — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133319)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @mw5h)

___
*[`pkg/util/vector/vector_set.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133319#-O9wXGcMEYuLseZydIYj:-O9wXGcMEYuLseZydIYk:b-y15s52) ([raw file](https://github.com/cockroachdb/cockroach/blob/815e93ef224e276b7e0cea5392d2c22e998d47cc/pkg/util/vector/vector_set.go#L38)):*
> ```Go
> 
> // At returns the vector at the given offset in the set.
> func (vs *Set) At(offset int) T {
> ```

Note: For these simple methods that we expect to be inlined, we could use `//gcassert:inline` if you add the package to `pkg/testutils/lint/gcassert_paths.txt`.
___
*[`pkg/util/vector/vector_set.go` line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133319#-O9wXnWl4gGXfLw-TQGb:-O9wXnWl4gGXfLw-TQGc:b-2tpfj8) ([raw file](https://github.com/cockroachdb/cockroach/blob/815e93ef224e276b7e0cea5392d2c22e998d47cc/pkg/util/vector/vector_set.go#L61)):*
> ```Go
> 	// Specify capacity of the slice so that it's safe to add vectors to this
> 	// set without impacting the returned set.
> 	vs.Data = vs.Data[:offset:offset]
> ```

Should we be setting the `Count` of this Set equal to `offset`? If so, let's also add a test for that.
___
*[`pkg/util/vector/vector_set.go` line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133319#-O9wYauw3lfbgB7XaklB:-O9wYauw3lfbgB7XaklC:b690tt2) ([raw file](https://github.com/cockroachdb/cockroach/blob/815e93ef224e276b7e0cea5392d2c22e998d47cc/pkg/util/vector/vector_set.go#L89)):*
> ```Go
> func (vs *Set) AddZero(count int) {
> 	vs.Count += count
> 	vs.Data = slices.Grow(vs.Data, count*vs.Dims)
> ```

Is this guaranteed to result in zero vectors? What happens if we had previously removed vectors from the set? For similar cases in the vectorized engine, we define a global all-zeroes slice and copy from that to "reset" a slice. Ex: https://github.com/cockroachdb/cockroach/blob/03393addb27b1209b4f2473b0a02b596ad95c83c/pkg/col/coldata/bytes.go#L523-L525
___
*[`pkg/util/vector/vector_set_test.go` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133319#-O9wZf_g8ih6NOXn_5pb:-O9wZf_g8ih6NOXn_5pc:b-onynf6) ([raw file](https://github.com/cockroachdb/cockroach/blob/815e93ef224e276b7e0cea5392d2c22e998d47cc/pkg/util/vector/vector_set_test.go#L36)):*
> ```Go
> 	vs.AddZero(0)
> 	require.Equal(t, 8, vs.Count)
> 	require.Equal(t, []float32{1, 2, 5, 3, 6, 6, 1, 2, 5, 3, 6, 6, 0, 0, 0, 0}, vs.Data)
> ```

Can we move this section after the `Remove` tests to make sure `AddZero` works properly when vectors have been removed?

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133319)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mw5h)

___
*[`pkg/util/vector/vector_set.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133319#-O9wXGcMEYuLseZydIYj:-O9wzs6f6VJBrKBwVAUZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/815e93ef224e276b7e0cea5392d2c22e998d47cc/pkg/util/vector/vector_set.go#L38)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Note: For these simple methods that we expect to be inlined, we could use `//gcassert:inline` if you add the package to `pkg/testutils/lint/gcassert_paths.txt`.
</blockquote></details>

Done.
___
*[`pkg/util/vector/vector_set.go` line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133319#-O9wXnWl4gGXfLw-TQGb:-O9wzx4N8RKljsQbgvWV:bg8bi1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/815e93ef224e276b7e0cea5392d2c22e998d47cc/pkg/util/vector/vector_set.go#L61)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Should we be setting the `Count` of this Set equal to `offset`? If so, let's also add a test for that.
</blockquote></details>

Yes, this is a bug. I made some changes to this function from my prototype and forgot to add tests.
___
*[`pkg/util/vector/vector_set.go` line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133319#-O9wYauw3lfbgB7XaklB:-O9x1tI4DOFQ6YtAI0NX:b-7vhmzy) ([raw file](https://github.com/cockroachdb/cockroach/blob/815e93ef224e276b7e0cea5392d2c22e998d47cc/pkg/util/vector/vector_set.go#L89)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Is this guaranteed to result in zero vectors? What happens if we had previously removed vectors from the set? For similar cases in the vectorized engine, we define a global all-zeroes slice and copy from that to "reset" a slice. Ex: https://github.com/cockroachdb/cockroach/blob/03393addb27b1209b4f2473b0a02b596ad95c83c/pkg/col/coldata/bytes.go#L523-L525
</blockquote></details>

Nice catch. I did think Grow guaranteed the memory would be zero'd, but a bit of testing showed I was wrong.
___
*[`pkg/util/vector/vector_set_test.go` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133319#-O9wZf_g8ih6NOXn_5pb:-O9x3fus41oJRnbdCb4F:byrhmqu) ([raw file](https://github.com/cockroachdb/cockroach/blob/815e93ef224e276b7e0cea5392d2c22e998d47cc/pkg/util/vector/vector_set_test.go#L36)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Can we move this section after the `Remove` tests to make sure `AddZero` works properly when vectors have been removed?
</blockquote></details>

I added a test for this case.

**Review by DrewKimball — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133319)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @mw5h)

___
*[`pkg/util/vector/vector_set.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133319#-O9wXGcMEYuLseZydIYj:-O9zUpzb9Yc5J3KO-kLs:b-mov5ee) ([raw file](https://github.com/cockroachdb/cockroach/blob/815e93ef224e276b7e0cea5392d2c22e998d47cc/pkg/util/vector/vector_set.go#L38)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I had to make a few changes, so the list might not be fully correct, but here are the inlining decisions from godbolt:
```
<source>:21:6: can inline MakeSet
<source>:45:6: can inline (*Set).At
<source>:111:6: can inline (*Set).Remove
<source>:122:6: can inline (*Set).EnsureCapacity
```
if the assertions are removed, these are also inlined:
```
<source>:29:6: can inline MakeSetFromRawData
<source>:50:6: can inline (*Set).SplitAt
<source>:75:6: can inline (*Set).Add
<source>:71:6: can inline (*Set).AddSet
```
___
*[`pkg/util/vector/vector_set.go` line 106 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/133319#-O9zXheb0b7RNe0tG9cE:-O9zXheb0b7RNe0tG9cF:b-vl3uxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8579fe279e769e14e07f363167c6de49a6091445/pkg/util/vector/vector_set.go#L106)):*
> ```Go
> // NB: This operation changes the ordering of vectors in the set, with the last
> // vector moved to the removed vector's offset.
> func (vs *Set) Remove(offset int) {
> ```

What happens if you call `Remove` on an empty set?

There are also a bunch of places where I think passing in a negative number would cause problems. Worth adding validation for that, or passing around unsigned ints instead?

**Comment by andy-kimball** [comment]
*[`pkg/util/vector/vector_set.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133319#-O9wXGcMEYuLseZydIYj:-O9zdCXY4mGKQl6Rv_KD:b8agpr) ([raw file](https://github.com/cockroachdb/cockroach/blob/815e93ef224e276b7e0cea5392d2c22e998d47cc/pkg/util/vector/vector_set.go#L38)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I had to make a few changes, so the list might not be fully correct, but here are the inlining decisions from godbolt:
```
<source>:21:6: can inline MakeSet
<source>:45:6: can inline (*Set).At
<source>:111:6: can inline (*Set).Remove
<source>:122:6: can inline (*Set).EnsureCapacity
```
if the assertions are removed, these are also inlined:
```
<source>:29:6: can inline MakeSetFromRawData
<source>:50:6: can inline (*Set).SplitAt
<source>:75:6: can inline (*Set).Add
<source>:71:6: can inline (*Set).AddSet
```
</blockquote></details>

I think the only important one to inline is `At`. The others are not too important.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133319)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mw5h)

___
*[`pkg/util/vector/vector_set.go` line 106 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/133319#-O9zXheb0b7RNe0tG9cE:-O9zdLau-LaLzevqOB7p:bslzyow) ([raw file](https://github.com/cockroachdb/cockroach/blob/8579fe279e769e14e07f363167c6de49a6091445/pkg/util/vector/vector_set.go#L106)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

What happens if you call `Remove` on an empty set?

There are also a bunch of places where I think passing in a negative number would cause problems. Worth adding validation for that, or passing around unsigned ints instead?
</blockquote></details>

I added some more tests to ensure that invalid operations panic.

**Review by DrewKimball — APPROVED** [review]
:lgtm: overall, just one final question/comment.

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133319#-:-OA-8Ov7DBc5rOuJA-CX:bv9c782)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @mw5h)

___
*[`pkg/util/vector/vector_set.go` line 105 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/133319#-OA-8_C0DYvaa19pISma:-OA-8_C0DYvaa19pISmb:b-qx3qft) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6252fd3bbf13799a6f84c8ee186e7e9369c531c/pkg/util/vector/vector_set.go#L105)):*
> ```Go
> // operation.
> // NB: This operation changes the ordering of vectors in the set, with the last
> // vector moved to the removed vector's offset.
> ```

How are you envisioning that we use this `Set` thing? Will we ever have to keep track of it alongside other columns in a batch (e.g. primary key)? If so, this re-ordering will be problematic, since we need to make sure that all columns in a batch have the same order. Storing `[]byte` values has a similar problem, though it's actually even harder since elements there can have different lengths:
https://github.com/cockroachdb/cockroach/blob/da4dd1184cb35aa98f6658057f33e30b0e29de0b/pkg/col/coldata/bytes.go#L155-L165

**Comment by andy-kimball** [comment]
*[`pkg/util/vector/vector_set.go` line 105 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/133319#-OA-8_C0DYvaa19pISma:-OA-CNwM94OQzyDc7AVV:b-6a5lr9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6252fd3bbf13799a6f84c8ee186e7e9369c531c/pkg/util/vector/vector_set.go#L105)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

How are you envisioning that we use this `Set` thing? Will we ever have to keep track of it alongside other columns in a batch (e.g. primary key)? If so, this re-ordering will be problematic, since we need to make sure that all columns in a batch have the same order. Storing `[]byte` values has a similar problem, though it's actually even harder since elements there can have different lengths:
https://github.com/cockroachdb/cockroach/blob/da4dd1184cb35aa98f6658057f33e30b0e29de0b/pkg/col/coldata/bytes.go#L155-L165
</blockquote></details>

No, the `Set` should only be used to store vectors that are being processed in memory. It should have anything to do with other columns.

**Comment by DrewKimball** [comment]
bors r=DrewKimball

**Pull request merged**
