### PR TITLE
WIP xform: increase the cost of hash aggregation

### PR DESCRIPTION
**Pull request by yuzefovich**
Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Some guiding queries I used are on TPCH dataset:
```
select l_orderkey, max(l_shipdate) from lineitem where l_shipdate IS NOT NULL group by l_orderkey limit 10;

select l_orderkey, max(l_shipdate) from lineitem where l_shipdate IS NOT NULL group by l_orderkey offset 1499990 limit 10;
```
The current approach is probably not good enough :/

**Review by rytaft — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63051)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/opt/exec/execbuilder/testdata/distinct_on, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63051#-MXXnc1B0GMIJX1Ycnb_:-MXXnc1C3IWkMhw70Q3v:b-47raqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/df928e46361aa5a0213e5d89ed602dfd6177c385/pkg/sql/opt/exec/execbuilder/testdata/distinct_on#L202)):*
> ```
>     └── • scan
>           columns: (a, b, c)
>           ordering: +a
> ```

this seems like a suboptimal change
___
*[pkg/sql/opt/xform/coster.go, line 1055 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63051#-MXXoxyICoTHwqZwq1qP:-MXXoxyICoTHwqZwq1qQ:b-lb7vnq) ([raw file](https://github.com/cockroachdb/cockroach/blob/48e04fba825001f1bfb8edd33fc0cdd5a69bfb9a/pkg/sql/opt/xform/coster.go#L1055)):*
> ```Go
> 			// because we can short-circuit the execution once the limit is
> 			// satisfied, unlike in the case of the hash aggregation which has
> 			// to fully consume the input before it can emit any output.
> ```

This is a great question. I don't think we currently take limit or limit hint into account at all for GroupBy operations, but we should if the execution engine can short-circuit as you say. Could you open an issue? Thanks!
___
*[pkg/sql/opt/xform/coster.go, line 1074 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63051#-MXXqwY79Br-xn4DiuRs:-MXXqwY79Br-xn4DiuRt:bcc44zn) ([raw file](https://github.com/cockroachdb/cockroach/blob/48e04fba825001f1bfb8edd33fc0cdd5a69bfb9a/pkg/sql/opt/xform/coster.go#L1074)):*
> ```Go
> 				hashingCost := memo.Cost(groupingColCount) * 0.25
> 				lookupCost := memo.Cost(outputRowCount) / 100000
> 				singleRowHashTableCost = (hashingCost + lookupCost) * cpuCostFactor
> ```

since these are all fractions, it's possible that this cost is actually smaller than `cpuCostFactor`. I think this could be the source of the problem I mentioned below
___
*[pkg/sql/opt/xform/coster.go, line 1077 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63051#-MXXoWVR651DKOpPMDgb:-MXXoWVR651DKOpPMDgc:b-8a5frx) ([raw file](https://github.com/cockroachdb/cockroach/blob/48e04fba825001f1bfb8edd33fc0cdd5a69bfb9a/pkg/sql/opt/xform/coster.go#L1077)):*
> ```Go
> 			}
> 			cost += memo.Cost(inputRowCount) * singleRowHashTableCost
> 		}
> ```

There's something not quite right here, since according to the changed tests it seems like this has now reduced the estimated overhead of building a hash table, causing us to choose that plan *more* frequently.

**Review by RaduBerinde — APPROVED** [review]
> The current approach is probably not good enough :/

Can you expand? How do we want this change to affect the plans for those queries?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63051#-:-MXYYCAD0GNIZ4ROGoG2:bff6oxu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[pkg/sql/opt/exec/execbuilder/testdata/distinct_on, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63051#-MXXnc1B0GMIJX1Ycnb_:-MXYW1ro0DBmEAFRbElD:bsmrzmp) ([raw file](https://github.com/cockroachdb/cockroach/blob/df928e46361aa5a0213e5d89ed602dfd6177c385/pkg/sql/opt/exec/execbuilder/testdata/distinct_on#L202)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

this seems like a suboptimal change
</blockquote></details>

It makes sense if  we can't use a partial ordering for streaming aggregation anymore :/
___
*[pkg/sql/opt/xform/coster.go, line 1048 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63051#-MXYRrwZBb3y0B6qAvn_:-MXYRrwZBb3y0B6qAvna:b-jm2qmv) ([raw file](https://github.com/cockroachdb/cockroach/blob/48e04fba825001f1bfb8edd33fc0cdd5a69bfb9a/pkg/sql/opt/xform/coster.go#L1048)):*
> ```Go
> 			// Unless we are doing a streaming aggregation where all the
> 			// grouping columns are ordered, add a cost that reflects the use of
> 			// a hash table. The vectorized execution engine doesn't take
> ```

This is kind of unfortunate. Does the vectorized engine still guarantee that if we have an ordering on a subset of grouping columns, the output order is preserved on those columns? (if not, we have a correctness issue)

We will likely need some changes to the `GenerateStreamingGroupBy` rule since it was designed with partial streaming groupbys in mind.

Does the vectorized engine support segmented sort? And does it shortcircuit if we have an enclosing limit? We implemented segmented sort specifically for cases where it stops a scan early (rather than reading the entire table and then sorting it), it would be unfortunate if that feature also went away.
___
*[pkg/sql/opt/xform/coster.go, line 1051 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63051#-MXYU07V9AiC0j_s6l1v:-MXYU07V9AiC0j_s6l1w:b-12qa1) ([raw file](https://github.com/cockroachdb/cockroach/blob/48e04fba825001f1bfb8edd33fc0cdd5a69bfb9a/pkg/sql/opt/xform/coster.go#L1051)):*
> ```Go
> 			// advantage of the partially ordered columns, so we'll treat such
> 			// case as having no useful ordering.
> 			// TODO(rytaft): how do limits play with aggregation? If we have a
> ```

[nit] adding TODOs should be in your name in the vast majority of cases.. It doesn't mean you need to do it, just that you are the one who wrote it and has some context on it.
___
*[pkg/sql/opt/xform/coster.go, line 1058 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63051#-MXYTgTR3eLSgdwBlvYL:-MXYTgTR3eLSgdwBlvYM:b-u93cuy) ([raw file](https://github.com/cockroachdb/cockroach/blob/48e04fba825001f1bfb8edd33fc0cdd5a69bfb9a/pkg/sql/opt/xform/coster.go#L1058)):*
> ```Go
> 			var singleRowHashTableCost memo.Cost
> 			if avgGroupSize := inputRowCount / outputRowCount; avgGroupSize >= 10 {
> 				// When the aggregation significantly reduces the cardinality,
> ```

This kind of heuristic is contrary to the principle of using costs.. We should calculate a cost and let the optimizer figure out when it's better to sort. If something like this is the only option, we should still make it a "smooth" function rather than defining a sharp cutoff.

What is this case intended to help with?
___
*[pkg/sql/opt/xform/coster.go, line 1072 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63051#-MXYTLcGCRGN2Pez-NZq:-MXYTLcGCRGN2Pez-NZr:b7tngll) ([raw file](https://github.com/cockroachdb/cockroach/blob/48e04fba825001f1bfb8edd33fc0cdd5a69bfb9a/pkg/sql/opt/xform/coster.go#L1072)):*
> ```Go
> 				// TODO(rytaft): this doesn't account for the fact that we might
> 				// spill to disk.
> 				hashingCost := memo.Cost(groupingColCount) * 0.25
> ```

All constants should be defined at the top of the file
___
*[pkg/sql/opt/xform/coster.go, line 1072 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63051#-MXYX6l40PUiBO9rnQE9:-MXYX6l40PUiBO9rnQEA:b-eqtm7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/48e04fba825001f1bfb8edd33fc0cdd5a69bfb9a/pkg/sql/opt/xform/coster.go#L1072)):*
> ```Go
> 				// TODO(rytaft): this doesn't account for the fact that we might
> 				// spill to disk.
> 				hashingCost := memo.Cost(groupingColCount) * 0.25
> ```

We already added a cpuCost per grouping column. I think that should be sufficient, it accounts for either hashing the value (non-streaming case) or comparing it against the previous row (streaming case).
___
*[pkg/sql/opt/xform/coster.go, line 1074 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63051#-MXYXRM86V01v1qtCguy:-MXYXRM86V01v1qtCguz:b-rf9xy7) ([raw file](https://github.com/cockroachdb/cockroach/blob/48e04fba825001f1bfb8edd33fc0cdd5a69bfb9a/pkg/sql/opt/xform/coster.go#L1074)):*
> ```Go
> 				hashingCost := memo.Cost(groupingColCount) * 0.25
> 				lookupCost := memo.Cost(outputRowCount) / 100000
> 				singleRowHashTableCost = (hashingCost + lookupCost) * cpuCostFactor
> ```

What is 100,000? Do we use a fixed number of buckets in execution?

**Comment by rytaft** [comment]
___
*[pkg/sql/opt/exec/execbuilder/testdata/distinct_on, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63051#-MXXnc1B0GMIJX1Ycnb_:-MXYe-sZ6hrX9xFqEu34:b-kn1kc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/df928e46361aa5a0213e5d89ed602dfd6177c385/pkg/sql/opt/exec/execbuilder/testdata/distinct_on#L202)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It makes sense if  we can't use a partial ordering for streaming aggregation anymore :/
</blockquote></details>

Ohh right...

**Review by yuzefovich — COMMENTED** [review]
> Can you expand? How do we want this change to affect the plans for those queries?

I think currently the constants are overfitted for these particular queries. Also - if I'm not mistaken - if we remove the offset and the limit from the second query above, with this PR we choose the sort + streaming aggregation and it is slower than the hash aggregation, so the current cost is probably too high (or the equation is poor). I want to do more experiments.

On that note I started looking into Justin's `opbench` framework but couldn't figure out how to convert the query to the optimizer plan. How do I do that? I looked at some examples of `PREPARE AS OPT PLAN` but didn't find any with GroupBy.

I think this PR is not very urgent and would like to use it as a learning exercise for myself, so no hurry in responding to me.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63051#-:-MXZH9ON-7TgFh8DzqQa:bpvxfpw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/opt/xform/coster.go, line 1048 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63051#-MXYRrwZBb3y0B6qAvn_:-MXZI5K12tokClo8-qkW:b6n4n1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/48e04fba825001f1bfb8edd33fc0cdd5a69bfb9a/pkg/sql/opt/xform/coster.go#L1048)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is kind of unfortunate. Does the vectorized engine still guarantee that if we have an ordering on a subset of grouping columns, the output order is preserved on those columns? (if not, we have a correctness issue)

We will likely need some changes to the `GenerateStreamingGroupBy` rule since it was designed with partial streaming groupbys in mind.

Does the vectorized engine support segmented sort? And does it shortcircuit if we have an enclosing limit? We implemented segmented sort specifically for cases where it stops a scan early (rather than reading the entire table and then sorting it), it would be unfortunate if that feature also went away.
</blockquote></details>

Yes, as Radu and I quickly discussed on Slack, we have a correctness issue here. The segmented sort + streaming aggregation would work in the vectorized engine, but I still will want to prototype updating the hash aggregation to take advantage of the partial ordering and see which way is faster (I expect the hash aggregation).
___
*[pkg/sql/opt/xform/coster.go, line 1055 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63051#-MXXoxyICoTHwqZwq1qP:-MXZJDRL7fET5BcNP0aw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/48e04fba825001f1bfb8edd33fc0cdd5a69bfb9a/pkg/sql/opt/xform/coster.go#L1055)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This is a great question. I don't think we currently take limit or limit hint into account at all for GroupBy operations, but we should if the execution engine can short-circuit as you say. Could you open an issue? Thanks!
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/coster.go, line 1074 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63051#-MXYXRM86V01v1qtCguy:-MXZJLLs3WTKqGSR5gt5:bwujcp7) ([raw file](https://github.com/cockroachdb/cockroach/blob/48e04fba825001f1bfb8edd33fc0cdd5a69bfb9a/pkg/sql/opt/xform/coster.go#L1074)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

What is 100,000? Do we use a fixed number of buckets in execution?
</blockquote></details>

This is a number I took out of the hat, and I want to spend more time tuning it (and/or coming up with better cost equation for hash aggregation).

**Review by rytaft — COMMENTED** [review]
The `PREPARE AS OPT PLAN` stuff is defined here: https://github.com/cockroachdb/cockroach/tree/942b8a9356d5b87a3f46d234220920f7606fbb20/pkg/sql/opt/optgen/exprgen. Unfortunately I don't see any group by examples in those test files either, but [this comment](https://github.com/cockroachdb/cockroach/blob/942b8a9356d5b87a3f46d234220920f7606fbb20/pkg/sql/opt/optgen/exprgen/expr_gen.go#L32-L73) might be helpful. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63051#-:-MXg9pkF7MP-pcCb8fxG:bxco8ef)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @yuzefovich)

___
*[pkg/sql/opt/xform/coster.go, line 1077 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63051#-MXXoWVR651DKOpPMDgb:-MXg8IA58fSosvcFKXid:b88j73p) ([raw file](https://github.com/cockroachdb/cockroach/blob/48e04fba825001f1bfb8edd33fc0cdd5a69bfb9a/pkg/sql/opt/xform/coster.go#L1077)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

There's something not quite right here, since according to the changed tests it seems like this has now reduced the estimated overhead of building a hash table, causing us to choose that plan *more* frequently.
</blockquote></details>

Looks like the tests that changed were all for the partial ordering case, but I would still expect that some cases would change in the other direction (i.e., some tests where we currently prefer hash aggregation would switch to streaming)

**Comment by yuzefovich** [comment]
We now support partially-ordered aggregation thanks to Rachael's work, so I think this PR is mostly obsolete. We might still want to increase the cost of the hash aggregation, but it'll probably better to start from scratch.

**Pull request closed without merging**
