### PR TITLE
ui: network latency page

### LINKED ISSUE #43206: ui: network latency follow up work
**Feedback for network latency matrix #40311**

- [x] Default to 'Region' (if available) instead of 'Cluster' for the view dropdown 

_current:_ 
Screen Shot 2019-12-17 at 3 44 11 PM

- [x] Tooltip readability: Update latency tool tip to display node info in 2 columns so it is easier to read

_current:_ 
Screen Shot 2019-12-17 at 1 21 16 PM

_new:_
Screen Shot 2019-12-17 at 1 05 04 PM

- [x]  Add links to Node headers to click through on nodes to node detail page 

_new:_
Screen Shot 2019-12-17 at 1 54 45 PM

- [x]  Make “ms” lowercase in matrix 
Screen Shot 2019-12-17 at 1 56 23 PM

**Style updates:**

- [ ] Match latency font in Standard Deviation legend to latency font in matrix (make bold)

_current_
Screen Shot 2019-12-17 at 3 44 49 PM

- [x]  Reduce size of network latency icon to match other icons in nav from 36px to 24px

_current:_
Screen Shot 2019-12-17 at 1 10 29 PM

- [x]  Add spacing above regions header to match spacing below

_current:_
Screen Shot 2019-12-17 at 1 21 05 PM

- [x]  When clicking to “no connections’ modal something flashes 

**Questions**
- Should we disable the collapse node check box when viewing group by 'Cloud' or any other grouping that doesn't show an aggregated number? 

_current:_
Screen Shot 2019-12-17 at 1 21 50 PM

- What does scrolling look like for very large clusters? We should test

### PR DESCRIPTION
**Pull request by vladlos**
created new menu item for network latencies reports, redesign, added sort-by and filtering features

Resolves: #43206

Release note (ui): none

Screenshot 2019-12-18 at 16 43 02
Screenshot 2019-12-18 at 16 43 15

### CODE REVIEW

**Review by dhartunian — CHANGES_REQUESTED** [review]
> Reviewed 14 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43288)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @elkmaster)

___
*[pkg/ui/yarn-vendor, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43288#-Ly4uceC3FT5Fpw5BLfm:-Ly4uceC3FT5Fpw5BLfn:bqmy8u5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f1e342c386973c35246bef68c177fcd0b8b609b/pkg/ui/yarn-vendor#L1)):*
> ```
> Subproject commit 594a1b989233ac5ae958eec4b2bdb2473f7a9272
> ```

package.json didn't change so why is there a change to `yarn-vendor` here?
___
*[pkg/ui/src/index.tsx, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43288#-Ly4zqq0BRGAqK9xlQzb:-Ly4zqq168aoaNoVPszf:b-ktygxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf1709d1f916c3e7f10d73ff2155560a0e463/pkg/ui/src/index.tsx#L165)):*
> ```XML
>           </Route>
>           <Route path="localities" component={ Localities } />
>           {/* <Route path="network" component={ Network } /> */}
> ```

What is this path? Should we just remove it?

**Comment by elkmaster** [comment]
@dhartunian rebased branch, removed commented code. 

Not sure why exactly submodule marked updated as latest commit number in master branch for yarn-vendor is `0491dd136a1113079354dcde4d7bb934212cf7ae`, the same as I pushing.

(https://github.com/cockroachdb/yarn-vendored/commits/master)

**Review by dhartunian — APPROVED** [review]
Looks great! Thanks for the small commits.

Agree that the `yarn-vendor` dir looks okay.

:lgtm: 

> Reviewed 13 of 28 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43288#-:-LyaYoWzBrdDXtr4BNPl:b-dim99r)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @elkmaster)

**Comment by dhartunian** [comment]
@Annebirzin can you let me know if you've seen the latest on this PR? It's ready to merge from my end.

**Comment by Annebirzin** [comment]
@dhartunian I haven't seen this one yet. Would you be able to build it for me?

**Comment by Annebirzin** [comment]
@elkmaster I only noticed one issue on this PR

- The network latency tool tip text flows outside the container: 
Screen Shot 2020-01-15 at 4 07 08 PM

**Comment by dhartunian** [comment]
@elkmaster I got some merge conflicts when pulling this down locally, it might need a rebase on the latest master (just a few `styl` files, no big deal). Can you take a look?

**Pull request merged**
