### PR TITLE
server: remove unused params

### PR DESCRIPTION
**Pull request by ecwall**
Informs #105448

1) Remove unnecessary `conn` method params.
2) Remove unused `conn.sendErr` execCfg param.

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106066)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by knz — COMMENTED** [review]
I'm not opposed to this PR, but note that it is in fact idiomatic in crdb to pass `context.Context` to methods _even when it is not currently used_. The reason for this is that it makes it easy(ier) to _add logging_ later when we are troubleshooting an issue and get proper context tags (especially wrt client connection parameters).

**Comment by knz** [comment]
When troubleshooting an issue usually we are in a hurry (to fix the issue) and having to do the work needed to pass the `context.Context` at the time of troubleshooting is frustrating.

**Comment by ecwall** [comment]
> I'm not opposed to this PR, but note that it is in fact idiomatic in crdb to pass `context.Context` to methods _even when it is not currently used_. The reason for this is that it makes it easy(ier) to _add logging_ later when we are troubleshooting an issue and get proper context tags (especially wrt client connection parameters).

Ok, I removed the `ctx` changes.

**Comment by ecwall** [comment]
bors r=rafiss

**Pull request merged**
