### PR TITLE
storage: perform Raft ready processing after handling a Raft message

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12356)

### CODE REVIEW

**Comment by tamird** [comment]
is this just cleanup? commit message lacks motivation

LGTM because it looks like cleanup

**Comment by petermattis** [comment]
Enhanced the commit message.

**Comment by tamird** [comment]
:+1:

**Comment by bdarnell** [comment]
LGTM, but have you measured the performance change? It looks like it could improve latency a bit but reduce throughput (since we call handleRaftReady for every message with this change, but before we could queue up multiple messages and handle them all at once). 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12356#-:-KZ0EN8s0oHKUkFbPdPk:b-fqdwa7)*

**Comment by petermattis** [comment]
I would think the latency improvement would be worth the throughput hit. Hard to measure a performance change here. I'm going to hold off on merging and do an experiment on a test cluster either this weekend or next week.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12356#-:-KZ2PW-KFpaMYxfnKE1i:bwbtj9f)*

**Comment by petermattis** [comment]
I experimented with this change on `blue` but was unable to see any performance improvement or regression. I'd like to merge this anyways due to the minor code simplification. 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12356#-:-Ka2uZNiK4yKH2XhkO8m:brsdsjn)*

**Comment by bdarnell** [comment]
LGTM

**Pull request merged**
