### PR TITLE
kvclient: assorted cleanups to the range desc cache

### PR DESCRIPTION
**Pull request by andreimatei**
See individual commits.

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 6 of 6 files at r2, 2 of 2 files at r3, 6 of 6 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, 1 of 1 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49648#-:-M8kIkYU-GMyX5haB4y8:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @irfansharif)

___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 416 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49648#-M8kEJcJ-1Pex8kPEMos:-M8kEJcJ-1Pex8kPEMot:bx51019) ([raw file](https://github.com/cockroachdb/cockroach/blob/31d1bb4cb1c44b1f4a1d9b0c5287917eb2e42998/pkg/kv/kvclient/kvcoord/range_cache.go#L416)):*
> ```Go
> 			// (if any), since it overlaps with rs[0]; rs[1] will be handled by
> 			// rs[0]'s eviction token.
> 			rdc.insertRangeDescriptorsLocked(ctx, append(preRs, rs[0])...)
> ```

Why allocate a new slice instead of calling `insertRangeDescriptorsLocked` twice?
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 513 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49648#-M8kG7fsApDdOwcZecXC:-M8kG7fsApDdOwcZecXD:b-jer8iw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ab40d4ebee1917f10dc68c7e8d3bb55d6bd0ae1/pkg/kv/kvclient/kvcoord/range_cache.go#L513)):*
> ```Go
> //
> // seenDesc should always be passed in if available, and is used as the basis of
> // a compare-and-evict strategy. This means that if the cache does
> ```

"generation-based"?
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 507 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49648#-M8kHV5d4GFuFhDpBXY0:-M8kHV5d4GFuFhDpBXY1:b-ah5zea) ([raw file](https://github.com/cockroachdb/cockroach/blob/c436d90e5e986ad7aea0a7dcd0ca9e62c2bcabd5/pkg/kv/kvclient/kvcoord/range_cache.go#L507)):*
> ```Go
> }
> 
> // EvictForKey evicts the descriptor containing the given key, if any.
> ```

"EvictByKey" sounds more common, doesn't it?
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 401 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49648#-M8kIApZ4NP7HwQo7of9:-M8kIAp_3iiEfcsbjMpz:b-6dxycb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8374358d6d283f7a7c227176e3a372a8830caaf/pkg/kv/kvclient/kvcoord/range_cache.go#L401)):*
> ```Go
> 				lookupRes = lookupResult{
> 					desc:       desc,
> 					evictToken: rdc.makeEvictionToken(desc, &nextDesc),
> ```

```go
nextDesc := &rs[1]
lookupRes = lookupResult{
    ...
    evictToken: rdc.makeEvictionToken(desc, nextDesc),
}
```

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49648)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif)

___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 416 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49648#-M8kEJcJ-1Pex8kPEMos:-M8kYIYY4od416gCV3KR:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/31d1bb4cb1c44b1f4a1d9b0c5287917eb2e42998/pkg/kv/kvclient/kvcoord/range_cache.go#L416)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why allocate a new slice instead of calling `insertRangeDescriptorsLocked` twice?
</blockquote></details>

done
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 513 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49648#-M8kG7fsApDdOwcZecXC:-M8kYa2r8NEndsKSbCp1:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ab40d4ebee1917f10dc68c7e8d3bb55d6bd0ae1/pkg/kv/kvclient/kvcoord/range_cache.go#L513)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"generation-based"?
</blockquote></details>

done
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 507 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49648#-M8kHV5d4GFuFhDpBXY0:-M8kYyLR6d9zvTzlsEgf:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c436d90e5e986ad7aea0a7dcd0ca9e62c2bcabd5/pkg/kv/kvclient/kvcoord/range_cache.go#L507)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"EvictByKey" sounds more common, doesn't it?
</blockquote></details>

done
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 401 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49648#-M8kIApZ4NP7HwQo7of9:-M8kX0SE7FJb2dGhaon7:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8374358d6d283f7a7c227176e3a372a8830caaf/pkg/kv/kvclient/kvcoord/range_cache.go#L401)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

```go
nextDesc := &rs[1]
lookupRes = lookupResult{
    ...
    evictToken: rdc.makeEvictionToken(desc, nextDesc),
}
```
</blockquote></details>

done

**Review by nvb — APPROVED** [review]
> Reviewed 3 of 6 files at r10, 3 of 6 files at r12, 2 of 3 files at r14, 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49648)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif)

___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 416 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49648#-M8kEJcJ-1Pex8kPEMos:-M8kl3avDphxhNuY8x9p:bb2hh2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/31d1bb4cb1c44b1f4a1d9b0c5287917eb2e42998/pkg/kv/kvclient/kvcoord/range_cache.go#L416)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

done
</blockquote></details>

This will still allocate. Try `rs[0:1:1]...`.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49648)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif and @nvanbenschoten)

___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 416 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49648#-M8kEJcJ-1Pex8kPEMos:-M8kxVdy-LKHHBB8w9-3:bhlqnok) ([raw file](https://github.com/cockroachdb/cockroach/blob/31d1bb4cb1c44b1f4a1d9b0c5287917eb2e42998/pkg/kv/kvclient/kvcoord/range_cache.go#L416)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This will still allocate. Try `rs[0:1:1]...`.
</blockquote></details>

:thumbsup: 
Verified that your suggestion does not allocate.

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49648#-:-M8lq0MpBvZIETroX1gc:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif and @nvanbenschoten)

**Pull request merged**
