### PR TITLE
sql: add APIs for output streams and routers

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6582)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/distsql/data.proto, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHKumwwWXa2KDwcFdeY:-KHKumwx0cZJLQ-TUt_Y:1406970864) ([raw file](https://github.com/cockroachdb/cockroach/blob/4641b9833053432398c36c4270f1b05df577a970/sql/distsql/data.proto#L20)):*
> ```protobuf
> // All the concepts here are "physical plan" concepts.
> 
> syntax = "proto2";
> ```

Just out of curiosity, was there a discussion about proto2 vs proto3 that I missed?

---

*[sql/distsql/data.proto, line 104 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHKtrMxyNHdFXbkOYov:-KHKtrMxyNHdFXbkOYow:-943243766) ([raw file](https://github.com/cockroachdb/cockroach/blob/4641b9833053432398c36c4270f1b05df577a970/sql/distsql/data.proto#L104)):*
> ```protobuf
>         BY_HASH = 2;
>         // Each row is sent to one stream, chosen according to preset boundaries
>         // for the values of certain columns of the row. TODO(radu)
> ```

What are you planning on doing?

---

*[sql/distsql/data.proto, line 112 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHKu1srsR6Pwjvg0rr7:-KHKu1srsR6Pwjvg0rr8:232699652) ([raw file](https://github.com/cockroachdb/cockroach/blob/4641b9833053432398c36c4270f1b05df577a970/sql/distsql/data.proto#L112)):*
> ```protobuf
> 
> message ProcessorSpec {
>     // One of the following will be filled in.
> ```

You might want to mirror the pattern used for `RequestUnion` and `ResponseUnion` here to achieve a union. Another alternative would be to use `oneof ` although there might be a reason we dont use them elsewhere and they probably dont work with `repeated` fields.

---

*[sql/distsql/data.proto, line 112 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHKvKHqX_ZfBzMlcvfT:-KHKvKHqX_ZfBzMlcvfU:1755274543) ([raw file](https://github.com/cockroachdb/cockroach/blob/4641b9833053432398c36c4270f1b05df577a970/sql/distsql/data.proto#L112)):*
> ```protobuf
> 
> message ProcessorSpec {
>     // One of the following will be filled in.
> ```

Could you touch upon why one or the other would be used in the comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/distsql/data.proto, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHKumwwWXa2KDwcFdeY:-KHKwamhHqZqKyT9KBcf:-1471591152) ([raw file](https://github.com/cockroachdb/cockroach/blob/4641b9833053432398c36c4270f1b05df577a970/sql/distsql/data.proto#L20)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Just out of curiosity, was there a discussion about proto2 vs proto3 that I missed?</details>
it is ongoing https://github.com/cockroachdb/cockroach/pull/5891

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[sql/distsql/api.proto, line 29 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHKx93Pv78K_6z87jzE:-KHKx93QZbXshRK9Cel_:-247603155) ([raw file](https://github.com/cockroachdb/cockroach/blob/4641b9833053432398c36c4270f1b05df577a970/sql/distsql/api.proto#L29)):*
> ```protobuf
> 
> message SetupFlowsRequest {
>   // TODO(radu): would TxnMeta suffice?
> ```

Interesting question - if the recipient of this ever needs to carry out work in the name of this transaction then no. Is this used for more than the ID (I suppose strongly that yes, but I definitely need to go back to the RFC).

---

*[sql/distsql/data.proto, line 80 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHL2U_BtKmpk1bTbGbW:-KHL2U_BtKmpk1bTbGbX:1338989482) ([raw file](https://github.com/cockroachdb/cockroach/blob/4641b9833053432398c36c4270f1b05df577a970/sql/distsql/data.proto#L80)):*
> ```protobuf
>         // overhead (extra RPCs) compared to the normal "async" mode where the
>         // RPC just sets up the flow. There can be at most one such endpoint in
>         // one flow, and such a flow cannot have any REMOTE endpoints.
> ```

So all other endpoints must be local? Should the message be called `StreamEndpointSpec`?

---

*[sql/distsql/data.proto, line 87 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHKzsRG8FlRWBwCMgyK:-KHKzsRHv3Kvc-taJYo8:-1982555505) ([raw file](https://github.com/cockroachdb/cockroach/blob/4641b9833053432398c36c4270f1b05df577a970/sql/distsql/data.proto#L87)):*
> ```protobuf
>     // For the LOCAL type, this is the ID of the corresponding endpoint within
>     // the same flow. For the REMOTE type, this is the ID of a mailbox.
>     optional int32 id = 2 [(gogoproto.nullable) = false,
> ```

Just curious why you're encoding it this way (and not a oneof which combines Type and the ID). The above looks like the generated code would be easier to handle - is that it? Comment applies below as well, and probably even more so there (as you'll have more info assigned only to some of the Types).

---

*[sql/distsql/data.proto, line 95 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHL2mNkCfgUxtEMTrFy:-KHL2mNkCfgUxtEMTrFz:625546638) ([raw file](https://github.com/cockroachdb/cockroach/blob/4641b9833053432398c36c4270f1b05df577a970/sql/distsql/data.proto#L95)):*
> ```protobuf
> message OutputRouterSpec {
>     enum Type {
>         // There is only one output stream.
> ```

Why do you need a special mode for this? Wouldn't MIRROR do the same thing since you only have one output?

---

*[sql/distsql/data.proto, line 112 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHKu1srsR6Pwjvg0rr7:-KHL22-TVXWXjzhAbeHX:66258330) ([raw file](https://github.com/cockroachdb/cockroach/blob/4641b9833053432398c36c4270f1b05df577a970/sql/distsql/data.proto#L112)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> You might want to mirror the pattern used for `RequestUnion` and `ResponseUnion` here to achieve a union. Another alternative would be to use `oneof ` although there might be a reason we dont use them elsewhere and they probably dont work with `repeated` fields.</details>
While I also like the simplicity of the approach here, it's going to be a little awkward once some of the options get more data attached to them. I think there's merit to considering Nathan's ideas (I'm on the fence).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582)*

**Comment by RaduBerinde** [comment]
Review status: 1 of 5 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[sql/distsql/api.proto, line 29 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHKx93Pv78K_6z87jzE:-KHL5l7CKGuaXANaLejS:1628197019) ([raw file](https://github.com/cockroachdb/cockroach/blob/4641b9833053432398c36c4270f1b05df577a970/sql/distsql/api.proto#L29)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Interesting question - if the recipient of this ever needs to carry out work in the name of this transaction then no. Is this used for more than the ID (I suppose strongly that yes, but I definitely need to go back to the RFC).</details>
Yes, the recipient will do work in the name of this transaction. For now only scans.

---

*[sql/distsql/data.proto, line 87 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHKzsRG8FlRWBwCMgyK:-KHL5Gx-M0L3PcZepADY:1267595068) ([raw file](https://github.com/cockroachdb/cockroach/blob/4641b9833053432398c36c4270f1b05df577a970/sql/distsql/data.proto#L87)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Just curious why you're encoding it this way (and not a oneof which combines Type and the ID). The above looks like the generated code would be easier to handle - is that it? Comment applies below as well, and probably even more so there (as you'll have more info assigned only to some of the Types).</details>
Yes it seems easier if you have a type rather than having to check one of X pointers, plus it's not great having all those pointers and indirections for simple fields.

---

*[sql/distsql/data.proto, line 95 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHL2mNkCfgUxtEMTrFy:-KHL4QUeA52Hlguizxy0:639916582) ([raw file](https://github.com/cockroachdb/cockroach/blob/4641b9833053432398c36c4270f1b05df577a970/sql/distsql/data.proto#L95)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Why do you need a special mode for this? Wouldn't MIRROR do the same thing since you only have one output?</details>
Technically yes, but IMO this is a bit cleaner.. A spec which specifies "mirroring" when there is only one stream would be a bit confusing. It's basically like mirroring + an extra sanity check.

---

*[sql/distsql/data.proto, line 104 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHKtrMxyNHdFXbkOYov:-KHL4IkC08GvActrYuX5:-2074285276) ([raw file](https://github.com/cockroachdb/cockroach/blob/4641b9833053432398c36c4270f1b05df577a970/sql/distsql/data.proto#L104)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> What are you planning on doing?</details>
Just like the case above there will need to be extra data that describes the ranges.

---

*[sql/distsql/data.proto, line 112 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHKu1srsR6Pwjvg0rr7:-KHL3gDhdzHNh1JU8xge:808019292) ([raw file](https://github.com/cockroachdb/cockroach/blob/4641b9833053432398c36c4270f1b05df577a970/sql/distsql/data.proto#L112)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> While I also like the simplicity of the approach here, it's going to be a little awkward once some of the options get more data attached to them. I think there's merit to considering Nathan's ideas (I'm on the fence).</details>
This is intended to be that pattern. The "one of the following" comment refers to other processor types which will follow. So there will be a bunch of `optional`s, only one of which will be set. The comment has nothing to do with the `repeated` field which will be present in all cases. I moved and clarified the comment.

I didn't know about `oneof`, I just followed those structures you mentioned and they didn't use it. Not sure why.. @bdarnell do you know of any issues around `oneof`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582)*

**Comment by tschottdorf** [comment]
Reviewed 5 of 5 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[sql/distsql/api.proto, line 29 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHKx93Pv78K_6z87jzE:-KHL9ScKqybxg-zO7qNs:801106427) ([raw file](https://github.com/cockroachdb/cockroach/blob/4641b9833053432398c36c4270f1b05df577a970/sql/distsql/api.proto#L29)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Yes, the recipient will do work in the name of this transaction. For now only scans.</details>
Ok. The TODO can go then, scans already need pretty much everything.

---

*[sql/distsql/data.proto, line 95 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHL2mNkCfgUxtEMTrFy:-KHL8fc5tnGix9mZrk_H:-685180220) ([raw file](https://github.com/cockroachdb/cockroach/blob/4641b9833053432398c36c4270f1b05df577a970/sql/distsql/data.proto#L95)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Technically yes, but IMO this is a bit cleaner.. A spec which specifies "mirroring" when there is only one stream would be a bit confusing. It's basically like mirroring + an extra sanity check.</details>
I disagree (but I don't have the big picture; go ahead, it's just noise). Mind adding a comment that briefly justifies the existence of the separate mode?

---

*[sql/distsql/data.proto, line 112 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHKu1srsR6Pwjvg0rr7:-KHL8y6DMNOzGL6lpJyX:1085574711) ([raw file](https://github.com/cockroachdb/cockroach/blob/4641b9833053432398c36c4270f1b05df577a970/sql/distsql/data.proto#L112)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> This is intended to be that pattern. The "one of the following" comment refers to other processor types which will follow. So there will be a bunch of `optional`s, only one of which will be set. The comment has nothing to do with the `repeated` field which will be present in all cases. I moved and clarified the comment.
> 
> I didn't know about `oneof`, I just followed those structures you mentioned and they didn't use it. Not sure why.. @bdarnell do you know of any issues around `oneof`?</details>
I'm not fond of how `oneof` feel anyway. I'm not opposed to keeping the fields inline even if it looks a bit "thrown together" - the one thing I don't know is whether over time, we'll have 10 fields here and then it's a bit nightmarish to reason about which ones are set in conjunction with which others, in which case logical separation now could be a good idea.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[sql/distsql/data.proto, line 112 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHKu1srsR6Pwjvg0rr7:-KHL9aj11gm2QIMrPhY5:560875066) ([raw file](https://github.com/cockroachdb/cockroach/blob/4641b9833053432398c36c4270f1b05df577a970/sql/distsql/data.proto#L112)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> I'm not fond of how `oneof` feel anyway. I'm not opposed to keeping the fields inline even if it looks a bit "thrown together" - the one thing I don't know is whether over time, we'll have 10 fields here and then it's a bit nightmarish to reason about which ones are set in conjunction with which others, in which case logical separation now could be a good idea.</details>
Ah, those existing cases use `gogoproto.onlyone`. I can only use that if I move the optionals to a separate message though.

I see we did add `oneof` at some point (#529) but then it got removed in https://github.com/bdarnell/cockroach/commit/263c6ee30c508354f001849338b6fdb142eae3aa (even though that commit actually switches *to* `oneof` in other structs?). @tamird I'm confused.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[sql/distsql/data.proto, line 95 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHL2mNkCfgUxtEMTrFy:-KHLBf-oM-fb3zN2taSB:-1413343282) ([raw file](https://github.com/cockroachdb/cockroach/blob/4641b9833053432398c36c4270f1b05df577a970/sql/distsql/data.proto#L95)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> I disagree (but I don't have the big picture; go ahead, it's just noise). Mind adding a comment that briefly justifies the existence of the separate mode?</details>
Ok, I'll remove it, geez :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/distsql/data.proto, line 112 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHKu1srsR6Pwjvg0rr7:-KHLIdcu4oAgomgNCrtg:-362986859) ([raw file](https://github.com/cockroachdb/cockroach/blob/4641b9833053432398c36c4270f1b05df577a970/sql/distsql/data.proto#L112)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Ah, those existing cases use `gogoproto.onlyone`. I can only use that if I move the optionals to a separate message though.
> 
> I see we did add `oneof` at some point (#529) but then it got removed in https://github.com/bdarnell/cockroach/commit/263c6ee30c508354f001849338b6fdb142eae3aa (even though that commit actually switches *to* `oneof` in other structs?). @tamird I'm confused.</details>
Ok, I see now. The generated code for `oneof` is less than ideal, that's why we're not using it everywhere. Moved to a union which uses `onlyone`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582)*

**Comment by andreimatei** [comment]
:lgtm:

<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> #### sql: add APIs for output streams and routers
> 
> 
> 
> 
> </details>


---

Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[sql/distsql/api.proto, line 29 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHLSSldPfM2tbHlhzXi:-KHLSSldPfM2tbHlhzXj:-1069429336) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1c6591972fcbd38454659691413d8c4c6c9f175/sql/distsql/api.proto#L29)):*
> ```protobuf
> 
> message SetupFlowsRequest {
>   // TODO(radu): would TxnMeta suffice?
> ```

how come that TxnMeta does not suffice? Maybe we could move some more fields to it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-:-KHLVEsIIvuOs_dZxDB6:1417088721)*

**Comment by tamird** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[sql/distsql/data.proto, line 72 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHL_fmj8Tmb4y-jWsMP:-KHL_fmkhgscLD0VwTOS:140190409) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f2e1e6fa2850410e1f9a077750cb8f6d8fce89b/sql/distsql/data.proto#L72)):*
> ```protobuf
>   enum Type {
>     // The ending is part of the same flow.
>     LOCAL = 0;
> ```

Might be a good idea to make 0 `UNKNOWN`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582)*

**Comment by tschottdorf** [comment]
:lgtm:

<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> :lgtm:</details>


---

Reviewed 4 of 4 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[sql/distsql/api.proto, line 29 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHLSSldPfM2tbHlhzXi:-KHLgP-IfhtANyK1slpI:433066542) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1c6591972fcbd38454659691413d8c4c6c9f175/sql/distsql/api.proto#L29)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> how come that TxnMeta does not suffice? Maybe we could move some more fields to it?</details>
The point of TxnMeta is to be minimal (it's on each intent). If we need to issue Scan, you really need al(most al)l of the full Txn proto already.

---

*[sql/distsql/data.proto, line 95 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHL2mNkCfgUxtEMTrFy:-KHLgGmWvqzanKND-_7R:1244727780) ([raw file](https://github.com/cockroachdb/cockroach/blob/4641b9833053432398c36c4270f1b05df577a970/sql/distsql/data.proto#L95)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Ok, I'll remove it, geez :)</details>
Now I feel bad (a little bit), but thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-:-KHLh0Lb91OiMH0AxaLI:1417088721)*

**Comment by bdarnell** [comment]
Review status: 4 of 5 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[sql/distsql/data.proto, line 112 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHKu1srsR6Pwjvg0rr7:-KHPFvnjMiMT4Pvl_3BL:-547621955) ([raw file](https://github.com/cockroachdb/cockroach/blob/4641b9833053432398c36c4270f1b05df577a970/sql/distsql/data.proto#L112)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Ok, I see now. The generated code for `oneof` is less than ideal, that's why we're not using it everywhere. Moved to a union which uses `onlyone`.</details>
Originally, we used `onlyone` instead of `oneof` because the latter wasn't supported in Go at the time (it was a noop, which is why we had both in #529 and later removed `oneof`). Since `oneof` support was added, we've mostly stuck with `onlyone` because the generated API is nicer for our purposes (using type switches, although this comes at the expense of being able to have multiple fields with the same type but different names)

---

*[sql/distsql/server.go, line 79 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHPFp9XMoX4_L6xOgSg:-KHPFp9XMoX4_L6xOgSh:196546559) ([raw file](https://github.com/cockroachdb/cockroach/blob/752504602c9be470fb1a70b2ee470cb38bd0941a/sql/distsql/server.go#L79)):*
> ```Go
> }
> 
> // TODO(radu): prevent varcheck from complaining about (yet) unused constants
> ```

We have a whitelist in check-style.sh to exclude generated files; we should just add .pb.go to the list.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582)*

**Comment by RaduBerinde** [comment]
*[sql/distsql/server.go, line 79 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHPFp9XMoX4_L6xOgSg:-KHPv6o_sBfjTfnAgVCE:-966883997) ([raw file](https://github.com/cockroachdb/cockroach/blob/752504602c9be470fb1a70b2ee470cb38bd0941a/sql/distsql/server.go#L79)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> We have a whitelist in check-style.sh to exclude generated files; we should just add .pb.go to the list.</details>
Good idea, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582)*

**Comment by RaduBerinde** [comment]
*[sql/distsql/server.go, line 79 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582#-KHPFp9XMoX4_L6xOgSg:-KHPynk6oUY8ouC2FuMY:811758861) ([raw file](https://github.com/cockroachdb/cockroach/blob/752504602c9be470fb1a70b2ee470cb38bd0941a/sql/distsql/server.go#L79)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Good idea, done.</details>
Ah lol, forgot I merged this branch. Will post a separate PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6582)*

**Pull request merged**
