### PR TITLE
storage: add Replica.metrics()

### LINKED ISSUE #12003: storage: refactor and test replication gauges
`Store.updateReplicationGauges` has evolved into spaghetti. It needs to be refactored for readability and tested. In particular, the per-Replica computation can be pulled out into a function that operates on the Raft status, lease, liveness map and zone config.

### PR DESCRIPTION
**Pull request by petermattis**
Move logic from Store.updateReplicationGauges() to Replica.metrics(). Add a
test.

Fixes #12003

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12026)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/replica_test.go, line 7073 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12026#-KYFXGZq8xAu8FTmqHRj:-KYFXGZq8xAu8FTmqHRk:b-n0abcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a1de2e96c7aa6ddb4e3e4168fef9c83e83699a/pkg/storage/replica_test.go#L7073)):*
> ```Go
> 				unavailable:     false,
> 				underreplicated: false,
> 			}},
> ```

These test cases are not exhaustive, but I don't think they need to be.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12026)*

**Comment by tamird** [comment]
:lgtm: did not thoroughly review test cases

---

Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica.go, line 4424 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12026#-KYFYbG_hhvrwXYFRisC:-KYFYbG_hhvrwXYFRisD:bjhkuzd) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a1de2e96c7aa6ddb4e3e4168fef9c83e83699a/pkg/storage/replica.go#L4424)):*
> ```Go
> 
> 	// To avoid double counting, most stats are only counted on the raft
> 	// leader. The lease holder count is the exception, which is counted by
> ```

this comment is oddly placed _below_ the line where the lease holder field is set.

---

*[pkg/storage/replica.go, line 4432 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12026#-KYFYhi-wPllne0KjaEl:-KYFYhi-wPllne0KjaEm:b-vh08a8) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a1de2e96c7aa6ddb4e3e4168fef9c83e83699a/pkg/storage/replica.go#L4432)):*
> ```Go
> 	// leader, the largest live replica ID. Note that the largest ID is an
> 	// arbitrary choice. We want to select one live replica to do the
> 	// counting that all replicas can agree on.
> ```

final appeal to use the first live replica in the replicas slice for simplicity =/

---

*[pkg/storage/replica.go, line 4455 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12026#-KYFZ2QnNGiBrdVn14TT:-KYFZ2QnNGiBrdVn14TU:b1kw1ik) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a1de2e96c7aa6ddb4e3e4168fef9c83e83699a/pkg/storage/replica.go#L4455)):*
> ```Go
> 
> 	if m.rangeCounter {
> 		// Count good replicas: those which are on a live node and, if there is a
> ```

duplicates the method comment on calcGoodReplicas. optional.

---

*[pkg/storage/store.go, line 3733 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12026#-KYFYHuz0kBpIh-_a5aH:-KYFYHuz0kBpIh-_a5aI:b-ynlofc) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a1de2e96c7aa6ddb4e3e4168fef9c83e83699a/pkg/storage/store.go#L3733)):*
> ```Go
> 		if metrics.leader {
> 			raftLeaderCount++
> 			if metrics.leaderNotLeaseholder {
> ```

isn't `leaderNotLeaseHolder` redundant with `leader` and `leaseholder`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12026#-:-KYFZBmySMiJZMVvneK8:b-21nbq3)*

**Comment by petermattis** [comment]
Review status: 1 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/storage/replica.go, line 4424 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12026#-KYFYbG_hhvrwXYFRisC:-KYFZgqTntv7kuFUSx7-:bg8a9eh) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a1de2e96c7aa6ddb4e3e4168fef9c83e83699a/pkg/storage/replica.go#L4424)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this comment is oddly placed _below_ the line where the lease holder field is set.
</blockquote></details>

Yes, this was copied from the old code. I'm just going to remove it. 

---

*[pkg/storage/replica.go, line 4432 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12026#-KYFYhi-wPllne0KjaEl:-KYF_CQLNXEPdtvVsQO7:b-69whhj) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a1de2e96c7aa6ddb4e3e4168fef9c83e83699a/pkg/storage/replica.go#L4432)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

final appeal to use the first live replica in the replicas slice for simplicity =/
</blockquote></details>

Sure. Done. I was actually intending to simplify this once we had a test (which we now do).

---

*[pkg/storage/replica.go, line 4455 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12026#-KYFZ2QnNGiBrdVn14TT:-KYF_Khmwdczt6VWiV2-:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a1de2e96c7aa6ddb4e3e4168fef9c83e83699a/pkg/storage/replica.go#L4455)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

duplicates the method comment on calcGoodReplicas. optional.
</blockquote></details>

Removed.

---

*[pkg/storage/store.go, line 3733 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12026#-KYFYHuz0kBpIh-_a5aH:-KYF_LxdZE9KOo7IU-XL:bu7lirg) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a1de2e96c7aa6ddb4e3e4168fef9c83e83699a/pkg/storage/store.go#L3733)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

isn't `leaderNotLeaseHolder` redundant with `leader` and `leaseholder`?
</blockquote></details>

Not quite as there is a third option: we have a leader but nobody holds the lease. That currently can happen somewhat frequently with expiration-based leases and we want to distinguish that case from the one where we have a lease but it is not owned by the leader.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12026)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica.go, line 4430 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12026#-KYFcaQoDbQ90LU14-ol:-KYFcaQoDbQ90LU14-om:b75kqu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b6733d8f892a3d0448b2a68f20caa0e3c31551a/pkg/storage/replica.go#L4430)):*
> ```Go
> 	// counting that all replicas can agree on.
> 	//
> 	// Note that the current heuristics can double count. If the largest live
> ```

update this comment in light of the change to the selection mechanism

---

*[pkg/storage/store.go, line 3733 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12026#-KYFYHuz0kBpIh-_a5aH:-KYFcrEYbxTZnfFQZ_wQ:b-mvxcwf) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a1de2e96c7aa6ddb4e3e4168fef9c83e83699a/pkg/storage/store.go#L3733)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Not quite as there is a third option: we have a leader but nobody holds the lease. That currently can happen somewhat frequently with expiration-based leases and we want to distinguish that case from the one where we have a lease but it is not owned by the leader.
</blockquote></details>

Oh, so this is really `leaderButLeaseIsElsewhere`? Perhaps it would make more sense to have a "leaseValid" field.

Actually, I don't feel strongly about which way you go, but as-written, it is odd that this is nested under `metrics.leader`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12026)*

**Comment by petermattis** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica.go, line 4430 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12026#-KYFcaQoDbQ90LU14-ol:-KYFdVznYn3CTq9IKQ7J:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b6733d8f892a3d0448b2a68f20caa0e3c31551a/pkg/storage/replica.go#L4430)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

update this comment in light of the change to the selection mechanism
</blockquote></details>

Done.

---

*[pkg/storage/store.go, line 3733 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12026#-KYFYHuz0kBpIh-_a5aH:-KYFdZ5Dyf5sG49IRw_X:b93ynq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/88a1de2e96c7aa6ddb4e3e4168fef9c83e83699a/pkg/storage/store.go#L3733)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Oh, so this is really `leaderButLeaseIsElsewhere`? Perhaps it would make more sense to have a "leaseValid" field.

Actually, I don't feel strongly about which way you go, but as-written, it is odd that this is nested under `metrics.leader`.
</blockquote></details>

Added `replicaMetrics.leaseValid` and removed `replicaMetrics.leaderNotLeaseHolder`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12026)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12026)*

**Pull request merged**
