### PR TITLE
libroach: optimize MVCC reverse scans

### PR DESCRIPTION
**Pull request by petermattis**
The previous reverse scan code was performing a seek between every
key. This is very slow. The new code maintains a one element buffer
allowing it to "peek" at the previous key.

```
name                                                          old time/op    new time/op     delta
MVCCReverseScan_RocksDB/rows=1/versions=1/valueSize=8-8         10.9µs ± 9%      7.4µs ± 2%   -32.01%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=1/versions=2/valueSize=8-8         10.8µs ± 2%      8.1µs ± 2%   -24.74%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=1/versions=10/valueSize=8-8        11.7µs ± 3%     10.5µs ± 2%   -10.02%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=1/versions=100/valueSize=8-8       14.7µs ± 1%     17.5µs ± 3%   +19.32%  (p=0.000 n=8+9)
MVCCReverseScan_RocksDB/rows=10/versions=1/valueSize=8-8        27.4µs ± 2%     11.6µs ± 3%   -57.71%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=10/versions=2/valueSize=8-8        28.6µs ± 2%     15.9µs ± 2%   -44.30%  (p=0.000 n=9+9)
MVCCReverseScan_RocksDB/rows=10/versions=10/valueSize=8-8       33.7µs ± 2%     32.3µs ± 2%    -4.07%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=10/versions=100/valueSize=8-8      57.0µs ± 2%     72.9µs ± 2%   +27.91%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=100/versions=1/valueSize=8-8        187µs ± 4%       44µs ± 1%   -76.23%  (p=0.000 n=10+9)
MVCCReverseScan_RocksDB/rows=100/versions=2/valueSize=8-8        192µs ± 4%       84µs ± 1%   -56.50%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=100/versions=10/valueSize=8-8       237µs ± 1%      233µs ± 2%    -1.53%  (p=0.000 n=9+10)
MVCCReverseScan_RocksDB/rows=100/versions=100/valueSize=8-8      457µs ± 3%      606µs ± 1%   +32.56%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=1000/versions=1/valueSize=8-8      1.75ms ± 3%     0.36ms ± 2%   -79.50%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=1000/versions=2/valueSize=8-8      1.79ms ± 2%     0.73ms ± 1%   -59.11%  (p=0.000 n=10+9)
MVCCReverseScan_RocksDB/rows=1000/versions=10/valueSize=8-8     2.31ms ± 7%     2.23ms ± 2%    -3.27%  (p=0.035 n=10+10)
MVCCReverseScan_RocksDB/rows=1000/versions=100/valueSize=8-8    4.58ms ± 6%     5.92ms ± 5%   +29.39%  (p=0.000 n=9+10)
```

Release note (performance improvement): Improve low-level reverse scan
throughput by up almost 4x when there are a few versions per key.

### CODE REVIEW

**Comment by petermattis** [comment]
I think making iters-per-seek adaptive might address the performance hit for the `versions=100` benchmarks. I'm going to experiment with that soon.

**Comment by petermattis** [comment]
I added a second commit which makes iters-before-seek adaptive. @arjunravinarayan please take a look.

**Comment by petermattis** [comment]
Keeping track of all of the benchmark numbers and what versions they apply to is a bit daunting. The following numbers are using `old` from before the reimplementation work began and `new` using this PR:

```
name                                                          old time/op    new time/op     delta
MVCCScan_RocksDB/rows=1/versions=1/valueSize=8-8                6.02µs ± 1%     5.30µs ± 2%   -12.07%  (p=0.000 n=8+10)
MVCCScan_RocksDB/rows=1/versions=2/valueSize=8-8                6.93µs ± 2%     5.43µs ± 5%   -21.64%  (p=0.000 n=10+10)
MVCCScan_RocksDB/rows=1/versions=10/valueSize=8-8               8.41µs ± 3%     5.85µs ± 2%   -30.37%  (p=0.000 n=10+10)
MVCCScan_RocksDB/rows=1/versions=100/valueSize=8-8              9.48µs ± 2%     7.04µs ± 3%   -25.74%  (p=0.000 n=9+10)
MVCCScan_RocksDB/rows=10/versions=1/valueSize=8-8               12.7µs ± 2%      8.3µs ± 1%   -34.75%  (p=0.000 n=10+10)
MVCCScan_RocksDB/rows=10/versions=2/valueSize=8-8               20.0µs ± 1%      9.0µs ± 1%   -55.25%  (p=0.000 n=10+10)
MVCCScan_RocksDB/rows=10/versions=10/valueSize=8-8              31.3µs ± 2%     14.3µs ± 1%   -54.43%  (p=0.000 n=10+9)
MVCCScan_RocksDB/rows=10/versions=100/valueSize=8-8             38.2µs ± 2%     30.9µs ± 4%   -19.19%  (p=0.000 n=9+10)
MVCCScan_RocksDB/rows=100/versions=1/valueSize=8-8              72.6µs ± 1%     31.0µs ± 2%   -57.38%  (p=0.000 n=10+10)
MVCCScan_RocksDB/rows=100/versions=2/valueSize=8-8               142µs ± 2%       37µs ± 1%   -73.73%  (p=0.000 n=10+10)
MVCCScan_RocksDB/rows=100/versions=10/valueSize=8-8              246µs ± 2%       81µs ± 2%   -67.20%  (p=0.000 n=10+10)
MVCCScan_RocksDB/rows=100/versions=100/valueSize=8-8             304µs ± 1%      241µs ± 2%   -20.92%  (p=0.000 n=10+10)
MVCCScan_RocksDB/rows=1000/versions=1/valueSize=8-8              635µs ± 2%      246µs ± 1%   -61.20%  (p=0.000 n=10+10)
MVCCScan_RocksDB/rows=1000/versions=2/valueSize=8-8             1.33ms ± 2%     0.30ms ± 1%   -77.30%  (p=0.000 n=10+9)
MVCCScan_RocksDB/rows=1000/versions=10/valueSize=8-8            2.35ms ± 2%     0.71ms ± 1%   -69.62%  (p=0.000 n=9+10)
MVCCScan_RocksDB/rows=1000/versions=100/valueSize=8-8           2.94ms ± 2%     2.29ms ± 1%   -22.08%  (p=0.000 n=10+9)
MVCCReverseScan_RocksDB/rows=1/versions=1/valueSize=8-8         10.9µs ± 1%      7.2µs ± 2%   -34.23%  (p=0.000 n=9+9)
MVCCReverseScan_RocksDB/rows=1/versions=2/valueSize=8-8         12.0µs ± 2%      8.1µs ± 3%   -32.34%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=1/versions=10/valueSize=8-8        12.9µs ± 1%     11.3µs ± 2%   -12.57%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=1/versions=100/valueSize=8-8       14.1µs ± 1%     15.0µs ± 2%    +6.22%  (p=0.000 n=10+8)
MVCCReverseScan_RocksDB/rows=10/versions=1/valueSize=8-8        34.9µs ± 1%     11.2µs ± 2%   -67.86%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=10/versions=2/valueSize=8-8        43.3µs ± 1%     15.7µs ± 1%   -63.82%  (p=0.000 n=9+8)
MVCCReverseScan_RocksDB/rows=10/versions=10/valueSize=8-8       51.5µs ± 1%     35.6µs ± 5%   -30.90%  (p=0.000 n=9+10)
MVCCReverseScan_RocksDB/rows=10/versions=100/valueSize=8-8      57.8µs ± 1%     51.3µs ± 2%   -11.22%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=100/versions=1/valueSize=8-8        264µs ± 3%       44µs ± 2%   -83.35%  (p=0.000 n=10+9)
MVCCReverseScan_RocksDB/rows=100/versions=2/valueSize=8-8        342µs ± 1%       82µs ± 1%   -75.99%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=100/versions=10/valueSize=8-8       417µs ± 2%      237µs ± 2%   -43.13%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=100/versions=100/valueSize=8-8      482µs ± 2%      391µs ± 2%   -18.84%  (p=0.000 n=10+8)
MVCCReverseScan_RocksDB/rows=1000/versions=1/valueSize=8-8      2.52ms ± 2%     0.36ms ± 2%   -85.74%  (p=0.000 n=9+10)
MVCCReverseScan_RocksDB/rows=1000/versions=2/valueSize=8-8      3.28ms ± 2%     0.73ms ± 1%   -77.64%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=1000/versions=10/valueSize=8-8     4.08ms ± 3%     2.22ms ± 2%   -45.67%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=1000/versions=100/valueSize=8-8    4.66ms ± 1%     3.76ms ± 3%   -19.14%  (p=0.000 n=7+10)

name                                                          old speed      new speed       delta
MVCCScan_RocksDB/rows=1/versions=1/valueSize=8-8              1.33MB/s ± 1%   1.51MB/s ± 2%   +13.85%  (p=0.000 n=8+10)
MVCCScan_RocksDB/rows=1/versions=2/valueSize=8-8              1.16MB/s ± 2%   1.48MB/s ± 5%   +27.71%  (p=0.000 n=10+10)
MVCCScan_RocksDB/rows=1/versions=10/valueSize=8-8              956kB/s ± 2%   1366kB/s ± 2%   +42.95%  (p=0.000 n=9+10)
MVCCScan_RocksDB/rows=1/versions=100/valueSize=8-8             843kB/s ± 2%   1137kB/s ± 2%   +34.82%  (p=0.000 n=9+10)
MVCCScan_RocksDB/rows=10/versions=1/valueSize=8-8             6.31MB/s ± 2%   9.67MB/s ± 1%   +53.26%  (p=0.000 n=10+10)
MVCCScan_RocksDB/rows=10/versions=2/valueSize=8-8             4.00MB/s ± 1%   8.93MB/s ± 1%  +123.09%  (p=0.000 n=9+10)
MVCCScan_RocksDB/rows=10/versions=10/valueSize=8-8            2.56MB/s ± 2%   5.61MB/s ± 1%  +119.40%  (p=0.000 n=10+9)
MVCCScan_RocksDB/rows=10/versions=100/valueSize=8-8           2.08MB/s ± 5%   2.59MB/s ± 4%   +24.46%  (p=0.000 n=10+10)
MVCCScan_RocksDB/rows=100/versions=1/valueSize=8-8            11.0MB/s ± 1%   25.8MB/s ± 2%  +134.63%  (p=0.000 n=10+10)
MVCCScan_RocksDB/rows=100/versions=2/valueSize=8-8            5.65MB/s ± 2%  21.52MB/s ± 1%  +280.65%  (p=0.000 n=10+10)
MVCCScan_RocksDB/rows=100/versions=10/valueSize=8-8           3.25MB/s ± 2%   9.92MB/s ± 2%  +204.92%  (p=0.000 n=10+10)
MVCCScan_RocksDB/rows=100/versions=100/valueSize=8-8          2.63MB/s ± 1%   3.33MB/s ± 1%   +26.46%  (p=0.000 n=10+10)
MVCCScan_RocksDB/rows=1000/versions=1/valueSize=8-8           12.6MB/s ± 2%   32.5MB/s ± 1%  +157.74%  (p=0.000 n=10+10)
MVCCScan_RocksDB/rows=1000/versions=2/valueSize=8-8           6.03MB/s ± 2%  26.56MB/s ± 1%  +340.39%  (p=0.000 n=10+9)
MVCCScan_RocksDB/rows=1000/versions=10/valueSize=8-8          3.41MB/s ± 1%  11.22MB/s ± 1%  +229.06%  (p=0.000 n=9+10)
MVCCScan_RocksDB/rows=1000/versions=100/valueSize=8-8         2.72MB/s ± 2%   3.48MB/s ± 1%   +28.13%  (p=0.000 n=10+8)
MVCCReverseScan_RocksDB/rows=1/versions=1/valueSize=8-8        730kB/s ± 0%   1113kB/s ± 2%   +52.51%  (p=0.000 n=6+9)
MVCCReverseScan_RocksDB/rows=1/versions=2/valueSize=8-8        667kB/s ± 2%    985kB/s ± 3%   +47.68%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=1/versions=10/valueSize=8-8       618kB/s ± 2%    706kB/s ± 2%   +14.24%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=1/versions=100/valueSize=8-8      565kB/s ± 1%    533kB/s ± 3%    -5.60%  (p=0.000 n=10+9)
MVCCReverseScan_RocksDB/rows=10/versions=1/valueSize=8-8      2.29MB/s ± 1%   7.13MB/s ± 2%  +210.90%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=10/versions=2/valueSize=8-8      1.84MB/s ± 1%   5.11MB/s ± 1%  +176.95%  (p=0.000 n=8+8)
MVCCReverseScan_RocksDB/rows=10/versions=10/valueSize=8-8     1.55MB/s ± 1%   2.25MB/s ± 5%   +44.63%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=10/versions=100/valueSize=8-8    1.38MB/s ± 1%   1.56MB/s ± 2%   +12.64%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=100/versions=1/valueSize=8-8     3.03MB/s ± 3%  18.13MB/s ± 4%  +498.05%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=100/versions=2/valueSize=8-8     2.34MB/s ± 1%   9.74MB/s ± 1%  +316.55%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=100/versions=10/valueSize=8-8    1.92MB/s ± 2%   3.37MB/s ± 2%   +75.81%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=100/versions=100/valueSize=8-8   1.66MB/s ± 2%   2.04MB/s ± 2%   +23.19%  (p=0.000 n=10+8)
MVCCReverseScan_RocksDB/rows=1000/versions=1/valueSize=8-8    3.17MB/s ± 2%  22.26MB/s ± 2%  +601.23%  (p=0.000 n=9+10)
MVCCReverseScan_RocksDB/rows=1000/versions=2/valueSize=8-8    2.44MB/s ± 2%  10.90MB/s ± 1%  +347.07%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=1000/versions=10/valueSize=8-8   1.96MB/s ± 3%   3.61MB/s ± 2%   +83.91%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=1000/versions=100/valueSize=8-8  1.72MB/s ± 1%   2.12MB/s ± 3%   +23.65%  (p=0.000 n=7+10)
```

There is only one benchmark that shows a performance hit: `MVCCReverseScan_RocksDB/rows=1/versions=100/valueSize=8`. The reason for the hit is that previously we were doing 2 `iter->Seek` calls and now we're doing 2 `iter->Seek` + 5 `iter->Prev` (this is the `kMaxItersBeforeSeek` optimization). If we tweak that optimization we can get rid of the performance hit on this benchmark, but it would bring down the numbers for other benchmarks.

**Comment by arjunravinarayan** [comment]
Took a quick look at commit 2 only.

---

Reviewed 1 of 1 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[c-deps/libroach/db.cc, line 2530 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21438#-L2kcA4FG8T1ln5huhdP:-L2kcA4GJ8nJNnSVsfkg:b2clvv1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2d0b5978ac707e77683fd0271d58db28265b947/c-deps/libroach/db.cc#L2530)):*
> ```cpp
> // number adaptive. It starts with a value of kMaxItersPerSeek/2 and
> // increases the value every time a call to iter->{Next,Prev}()
> // successfully finds the desired next key. It decrements the value
> ```

My thought was that you'd halve the value when a call to `Seek()` occurs. Then you rapidly reduce the number of `Next()` calls in the unsuccessful path. This `+1/-1` strategy is fine though because you're bounding the maximum window size to 10, so the maximum number of unnecessary `Seek()` calls is bound at 55. But if we pushed it higher, then Additive Increase Multiplicative Decrease might work better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21438#-:-L2kkFTiw5Ox_1Nd5Ftr:b-gxpsj7)*

**Comment by petermattis** [comment]
@arjunravinarayan Your suggestions wins in some benchmarks and loses in others. And some of the losses are quite dramatic. (`old` is this PR, `new` is this PR plus your heuristic).

```
name                                                          old time/op    new time/op    delta
MVCCScan_RocksDB/rows=1/versions=1/valueSize=8-8                5.50µs ± 2%    5.46µs ± 1%     ~     (p=0.211 n=9+10)
MVCCScan_RocksDB/rows=1/versions=2/valueSize=8-8                5.54µs ± 2%    5.76µs ± 4%   +4.08%  (p=0.005 n=9+10)
MVCCScan_RocksDB/rows=1/versions=10/valueSize=8-8               6.06µs ± 2%    6.15µs ± 2%   +1.48%  (p=0.001 n=9+10)
MVCCScan_RocksDB/rows=1/versions=100/valueSize=8-8              7.31µs ± 3%    7.47µs ± 3%   +2.20%  (p=0.003 n=10+10)
MVCCScan_RocksDB/rows=10/versions=1/valueSize=8-8               8.48µs ± 1%    8.50µs ± 1%     ~     (p=0.516 n=10+10)
MVCCScan_RocksDB/rows=10/versions=2/valueSize=8-8               9.30µs ± 2%    9.31µs ± 2%     ~     (p=0.670 n=10+10)
MVCCScan_RocksDB/rows=10/versions=10/valueSize=8-8              14.8µs ± 2%    15.4µs ± 2%   +3.94%  (p=0.000 n=10+10)
MVCCScan_RocksDB/rows=10/versions=100/valueSize=8-8             32.3µs ± 2%    32.0µs ± 3%     ~     (p=0.133 n=9+10)
MVCCScan_RocksDB/rows=100/versions=1/valueSize=8-8              31.7µs ± 1%    32.5µs ± 6%   +2.72%  (p=0.000 n=10+10)
MVCCScan_RocksDB/rows=100/versions=2/valueSize=8-8              38.0µs ± 1%    38.6µs ± 1%   +1.66%  (p=0.000 n=10+9)
MVCCScan_RocksDB/rows=100/versions=10/valueSize=8-8             83.4µs ± 1%    83.2µs ± 2%     ~     (p=0.842 n=9+10)
MVCCScan_RocksDB/rows=100/versions=100/valueSize=8-8             254µs ± 3%     249µs ± 2%   -2.08%  (p=0.005 n=10+10)
MVCCScan_RocksDB/rows=1000/versions=1/valueSize=8-8              248µs ± 1%     250µs ± 2%     ~     (p=0.165 n=10+10)
MVCCScan_RocksDB/rows=1000/versions=2/valueSize=8-8              308µs ± 2%     310µs ± 1%     ~     (p=0.079 n=10+9)
MVCCScan_RocksDB/rows=1000/versions=10/valueSize=8-8             734µs ± 2%     728µs ± 1%     ~     (p=0.247 n=10+10)
MVCCScan_RocksDB/rows=1000/versions=100/valueSize=8-8           2.44ms ± 2%    2.40ms ± 2%   -1.49%  (p=0.043 n=10+10)
MVCCReverseScan_RocksDB/rows=1/versions=1/valueSize=8-8         7.44µs ± 2%    7.56µs ± 3%     ~     (p=0.055 n=10+10)
MVCCReverseScan_RocksDB/rows=1/versions=2/valueSize=8-8         8.31µs ± 2%    8.34µs ± 2%     ~     (p=0.516 n=10+10)
MVCCReverseScan_RocksDB/rows=1/versions=10/valueSize=8-8        11.8µs ± 2%    11.8µs ± 2%     ~     (p=0.858 n=9+10)
MVCCReverseScan_RocksDB/rows=1/versions=100/valueSize=8-8       15.6µs ± 3%    15.1µs ± 3%   -3.57%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=10/versions=1/valueSize=8-8        11.6µs ± 3%    11.6µs ± 1%     ~     (p=0.353 n=10+10)
MVCCReverseScan_RocksDB/rows=10/versions=2/valueSize=8-8        16.3µs ± 2%    16.3µs ± 3%     ~     (p=0.781 n=10+10)
MVCCReverseScan_RocksDB/rows=10/versions=10/valueSize=8-8       36.1µs ± 2%    39.0µs ± 2%   +7.92%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=10/versions=100/valueSize=8-8      53.7µs ± 2%    51.3µs ± 3%   -4.41%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=100/versions=1/valueSize=8-8       45.5µs ± 1%    45.1µs ± 2%   -0.98%  (p=0.008 n=10+10)
MVCCReverseScan_RocksDB/rows=100/versions=2/valueSize=8-8       85.8µs ± 2%    84.8µs ± 1%   -1.26%  (p=0.035 n=10+10)
MVCCReverseScan_RocksDB/rows=100/versions=10/valueSize=8-8       251µs ± 1%     293µs ± 1%  +16.93%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=100/versions=100/valueSize=8-8      409µs ± 3%     396µs ± 2%   -3.20%  (p=0.000 n=9+10)
MVCCReverseScan_RocksDB/rows=1000/versions=1/valueSize=8-8       370µs ± 1%     364µs ± 2%   -1.50%  (p=0.001 n=9+10)
MVCCReverseScan_RocksDB/rows=1000/versions=2/valueSize=8-8       760µs ± 2%     752µs ± 2%     ~     (p=0.075 n=10+10)
MVCCReverseScan_RocksDB/rows=1000/versions=10/valueSize=8-8     2.32ms ± 2%    2.85ms ± 3%  +22.64%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=1000/versions=100/valueSize=8-8    3.93ms ± 3%    3.94ms ± 8%     ~     (p=0.393 n=10+10)
```

Futzing with the adaptation heuristic is likely only going to give small wins. The big win for speeding up scans with lots of versions is to move the historic versions somewhere else.

**Comment by bdarnell** [comment]
:lgtm: 

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[c-deps/libroach/db.cc, line 2541 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21438#-L2vjiJ9GgaLJxK7w7bP:-L2vjiJ9GgaLJxK7w7bQ:bkb4qno) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2d0b5978ac707e77683fd0271d58db28265b947/c-deps/libroach/db.cc#L2541)):*
> ```cpp
> // efficiently while still reusing the common code without difficulty.
> //
> // WARNING: Do not use iter_rep_->key() or iter_rep_->value()
> ```

Add "use current_key_ and current_value_ instead" to this comment. 

---

*[c-deps/libroach/db.cc, line 3037 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21438#-L2vov1mLVG9y_r7i2MC:-L2vov1mLVG9y_r7i2MD:b7ni1m0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2d0b5978ac707e77683fd0271d58db28265b947/c-deps/libroach/db.cc#L3037)):*
> ```cpp
>       // this saved data.
>       peeked_ = true;
>       peek_buf_.resize(0);
> ```

I found this confusing on first reading because I thought `peek_buf_` would be the thing we peeked ahead to, instead of being the old value that the iterator has now been moved past. A comment might be worthwhile (or maybe a better name, but I don't have a suggestion). 

---

*[c-deps/libroach/db.cc, line 3095 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21438#-L2vkoMfVBQ_9DX62aW0:-L2vkoMfVBQ_9DX62aW1:b-j5vuj4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2d0b5978ac707e77683fd0271d58db28265b947/c-deps/libroach/db.cc#L3095)):*
> ```cpp
>   cockroach::storage::engine::enginepb::MVCCMetadata meta_;
>   rocksdb::Slice cur_iter_key_;
>   rocksdb::Slice cur_key_;
> ```

Comment the difference between `cur_iter_key_` and `cur_key_` (all of these fields could use some documentation; there's getting to be a lot of state here). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21438#-:-L2vp806NxT71JTznAJn:bg7igkv)*

**Comment by petermattis** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[c-deps/libroach/db.cc, line 2541 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21438#-L2vjiJ9GgaLJxK7w7bP:-L2wT596PRJVhKKPH0nb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2d0b5978ac707e77683fd0271d58db28265b947/c-deps/libroach/db.cc#L2541)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Add "use current_key_ and current_value_ instead" to this comment. 
</blockquote></details>

Done.

---

*[c-deps/libroach/db.cc, line 3037 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21438#-L2vov1mLVG9y_r7i2MC:-L2wTESZt03QjYTA9g4c:b-b6p263) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2d0b5978ac707e77683fd0271d58db28265b947/c-deps/libroach/db.cc#L3037)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I found this confusing on first reading because I thought `peek_buf_` would be the thing we peeked ahead to, instead of being the old value that the iterator has now been moved past. A comment might be worthwhile (or maybe a better name, but I don't have a suggestion). 
</blockquote></details>

Added a comment and renamed `peek_buf_` to `saved_buf_`.

---

*[c-deps/libroach/db.cc, line 3095 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21438#-L2vkoMfVBQ_9DX62aW0:-L2wYEd6FfImEUhCVFPU:bp9iq5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2d0b5978ac707e77683fd0271d58db28265b947/c-deps/libroach/db.cc#L3095)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Comment the difference between `cur_iter_key_` and `cur_key_` (all of these fields could use some documentation; there's getting to be a lot of state here). 
</blockquote></details>

Yes, there is a lot of state. I've renamed `cur_iter_key_` to `cur_raw_key_` to hopefully make things a bit clearer, and added some comments. I also investigated pulling bits of this out to a `PeekableIterator` class, but ran into complexities there that didn't seem to make anything clearer. I might take another whack at that tomorrow. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21438)*

**Comment by arjunravinarayan** [comment]
SGTM. As I mentioned, I think AIMD only really becomes a factor if we bump the max beyond 10, as the number of `Next()` calls in the worst case grows as `n(n-1)/2`. ~50 calls is not a big deal.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21438#-:-L2zPATlsp0ksExpaybl:b-tyvc0e)*

**Comment by petermattis** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[c-deps/libroach/db.cc, line 3095 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21438#-L2vkoMfVBQ_9DX62aW0:-L2zS7aJMC4wCWFscZ_-:bp3slhr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2d0b5978ac707e77683fd0271d58db28265b947/c-deps/libroach/db.cc#L3095)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Yes, there is a lot of state. I've renamed `cur_iter_key_` to `cur_raw_key_` to hopefully make things a bit clearer, and added some comments. I also investigated pulling bits of this out to a `PeekableIterator` class, but ran into complexities there that didn't seem to make anything clearer. I might take another whack at that tomorrow. 
</blockquote></details>

Nix that. I'm going to merge this as-is and  file an issue instead. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21438)*

**Pull request merged**
