### PR TITLE
Add Build Info into NodeStatus message

### LINKED ISSUE #4530: server/status: NodeStatus should contain build info
The NodeStatus should include the build info. We should then make this info available in the `cockroach node status` command and visible in the ui.

### PR DESCRIPTION
**Pull request by mrtracy**
The NodeStatus message, used to report the status of a node to our UI, now
contains build info.
- util.BuildInfo has been converted to a protocol buffer message.
- NodeStatus message now contains BuildInfo.
- Updated cli "node status" command to display the build of a node.
- Updated web ui to display a node's build on the "Node" page.

Resolves #4530 

screen shot 2016-03-21 at 6 28 07 pm

screen shot 2016-03-21 at 7 02 30 pm

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5456)

### CODE REVIEW

**Comment by maxlang** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ui/ts/pages/nodes.ts, line 768 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5456#-KDQWTjSRw6zY8gJtfZE:-KDQWTjSRw6zY8gJtfZF:-1373118432) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd77e6dd8bb7a8b1e4142572adff72f419f6ab96/ui/ts/pages/nodes.ts#L768)):*
Does this not complain that primaryContent isn't a MithrilElement?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5456)*

**Comment by maxlang** [comment]
:lgtm: for the frontend component. Someone else should look at the backend.

---

Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5456#-:-KDQXf5pVICaJY84VhtN:588162239)*

**Comment by cuongdo** [comment]
:lgtm: for backend, with a comment about re-numbering fields in the `NodeStatus` message

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/status/status.proto, line 34 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5456#-KDR52aEzwkxlHmQy79h:-KDR52aEzwkxlHmQy79i:267770565) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd77e6dd8bb7a8b1e4142572adff72f419f6ab96/server/status/status.proto#L34)):*
We should ditch the habit of renumbering proto fields. It breaks backward compatibility.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5456#-:-KDR6tlrYpdVkKn-Bf0a:476597900)*

**Comment by mrtracy** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/status/status.proto, line 34 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5456#-KDR52aEzwkxlHmQy79h:-KDR9v-Xi7NPx6FYOl4e:-1683461289) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd77e6dd8bb7a8b1e4142572adff72f419f6ab96/server/status/status.proto#L34)):*
I'm not sure it's a habit; we are still in the grace period and should be re-numbering for clarity until the cutoff (on thursday I think).  We want to send these off into the world of backwards-compatibility in a pristine state.

---

*[ui/ts/pages/nodes.ts, line 768 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5456#-KDQWTjSRw6zY8gJtfZE:-KDR9bdn5PC_LaumLEzT:1606619465) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd77e6dd8bb7a8b1e4142572adff72f419f6ab96/ui/ts/pages/nodes.ts#L768)):*
MithrilVirtualElement is one of those types that is satisfied by anything.  It has four optional properties, so an array satisfies it by having 0 of those properties.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5456)*

**Pull request merged**
