### PR TITLE
sql: use udf in check constraint

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
Informs #87699

**sql: use UDFs in check constraints**

This commit turns on UDF usages in CHECK constraints.
It does a few things:
1. Add a concept of `SchemaExprContext`, which used to be a
pure string. This commit makes it a type so that we can
switch on different context of a expression. This allow fine
grain control over in which circumstance that a UDF is allowed.
2. Serialize Function Expression to use OID reference to UDF.
This allows objects reference UDFs by ID so that functions can
be renamed.
3. Refine cross reference validation in function descriptor
and table descriptor for more safety.
4. Fix legacy schema changer, so that cross references between
UDF and tables are properly tracked when CHECK constraints are
added and dropped.
5. Fix declarative schema changer, so that UDFs are recognized
in check constraint elements, and ops are added to add and remove
UDF back references.

Release note (sql change): previously UDFs are not allowed in
tables and any other object. This patch enables UDF usage in
CHECK constraints of tables in both legacy schema changer and
delcarative schema changer. Dependency circles are not allowed,
namely if a UDF depends on a table, then the table can't use that
UDF.

**sql: version gate udf usage check**

This commit adds version gate for udf usage check, so that
cross reference won't be broken because there won't be cases
like a constraint is added in new version, but dropped in
an old version.

Release note (sql change): This patch adds version gate so the
UDF usage in CHECK constraints are not allowed until cluster is
fully upgraded to 23.1.

**backupccl: fix backup and restore to work with objects referencing UDFs**

Release note (enterprise change): Previously UDFs can't be referenced
from other objects, so backup and restore oly needs to read and
write UDF descriptors without worrying about missing UDFs when
doing `RESTORE TABLE`. Now that we turned UDF's usage in table
CHECK constraints. We need to be able to handle all function ID
rewrites in CHECK constraint expressions during `RESTORE`. A new
`RSTORE` command option `skip_missing_udfs` is added, so that
when the option is given, UDF dependencies will be skipped if UDF
descriptors are missing. The main use case, as of this patch is that
 currently when doing `RESTORE TABLE`, we don't restore referenced
UDFs together, so UDFs are consider missing, which blocks the table
restore unless the `skip_missing_udfs` option is specified, so that
those check constraints are dropped to remove the dependency to
unblock `RESTORE TABLE`.

### CODE REVIEW

**Review by fqazi — CHANGES_REQUESTED** [review]
> Dependency circles 
Cyclic dependencies

> Reviewed 75 of 91 files at r1, 21 of 21 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-:-NOVNzO879ySbD4g8P3P:b-7eijkf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan)

___
*[`pkg/sql/backfill.go` line 468 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOVP2hr8aFDdfT3FWCO:-NOVP2hr8aFDdfT3FWCP:b-x26660) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/backfill.go#L468)):*
> ```Go
> 				// Either it's found or not we need to always try to remove the references.
> 				// 1. If it's found, we should just remove reference.
> 				// 2. If it's not found, which means it's in a rollback or retry, we
> ```

Is that true? I would think in a retry case we would just see it again or am I missing something? Also do you mean a job retry or a transaction one here?



_Code quote:_
```Go
or retry
```
___
*[`pkg/sql/catalog/descriptor_id_set.go` line 86 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOVrXoMAWmqaZt4oeRw:-NOVrXoMAWmqaZt4oeRx:bgfg4wb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/catalog/descriptor_id_set.go#L86)):*
> ```Go
> }
> 
> type ConstraintIDSet struct {
> ```

Give this a comment for documentation
___
*[`pkg/sql/catalog/descs/dist_sql_function_resolver.go` line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOVswm3AKq2UKFl0uPp:-NOVswm3AKq2UKFl0uPq:b-t33glm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/catalog/descs/dist_sql_function_resolver.go#L41)):*
> ```Go
> 
> // ResolveFunction implements tree.FunctionReferenceResolver interface.
> // It only resolves builtin functions.
> ```

Maybe have this as a TODO? I know references are stored as OIDs but someone is going to accidentally use this at some point.
___
*[`pkg/sql/catalog/funcdesc/func_desc.go` line 544 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOVvAt513hgAXk1oUz8:-NOVvAt513hgAXk1oUz9:bnwqbfk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/catalog/funcdesc/func_desc.go#L544)):*
> ```Go
> 			ids := catalog.MakeConstraintIDSet(desc.DependedOnBy[i].ConstraintIDs...)
> 			ids.Add(constraintID)
> 			desc.DependedOnBy[i].ConstraintIDs = ids.Ordered()
> ```

Why are make a new set here? Is it just to make a copy?
___
*[`pkg/sql/catalog/funcdesc/func_desc.go` line 565 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOVvnhPAH6_ym7TpUpX:-NOVvnhPAH6_ym7TpUpY:b-pezais) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/catalog/funcdesc/func_desc.go#L565)):*
> ```Go
> 		if desc.DependedOnBy[i].ID == id {
> 			ids := catalog.MakeConstraintIDSet(desc.DependedOnBy[i].ConstraintIDs...)
> 			ids.Remove(constraintID)
> ```

The set here seems like its over kill for removal?
___
*[`pkg/sql/catalog/rewrite/rewrite.go` line 105 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOVwG8h95ICvA4q77rk:-NOVwG8h95ICvA4q77rl:b-10rsdb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/catalog/rewrite/rewrite.go#L105)):*
> ```Go
> 				for _, fnID := range fnIDs.Ordered() {
> 					if _, ok := descriptorRewrites[fnID]; !ok {
> 						keepMutation = false
> ```

I guess before this point we validated it's okay to drop the mutation. Think this is used in the restore?
___
*[`pkg/sql/catalog/rewrite/rewrite.go` line 426 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOVxmNVBJPjjJUfPC77:-NOVxmNVBJPjjJUfPC78:b-ngjrp3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/catalog/rewrite/rewrite.go#L426)):*
> ```Go
> 			return true, ex, nil
> 		}
> 		if !funcdesc.IsOIDUserDefinedFunc(oidRef.OID) {
> ```

Shouldn't this always hold and if it doesn't isn't a fatal thing?



_Code quote:_
```Go
IsOIDUserDefinedFunc
```
___
*[`pkg/sql/catalog/rewrite/rewrite.go` line 753 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOVzC-qDJmDrghCL04D:-NOVzC-qDJmDrghCL04E:bkrcxwj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/catalog/rewrite/rewrite.go#L753)):*
> ```Go
> 		switch el := t.Element().(type) {
> 		case *scpb.ConstraintWithoutIndexName:
> 			if !droppedConstraints.Contains(el.ConstraintID) {
> ```

We can should be able to rel to do this, see attr.go
___
*[`pkg/sql/catalog/schemaexpr/expr.go` line 611 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOW0ootBWryu5hSrK2-:-NOW0ootBWryu5hSrK20:b-pc5hgj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/catalog/schemaexpr/expr.go#L611)):*
> ```Go
> // GetUdfIDs extracts all UDF descriptor ids from the given expression,
> // assuming that the UDF names has been replaced with OID references.
> func GetUdfIDs(e tree.Expr) (catalog.DescriptorIDSet, error) {
> ```

Nit: UDF
___
*[`pkg/sql/catalog/tabledesc/structured.go` line 388 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOW1Un98LgW_LmeQX5a:-NOW1Un98LgW_LmeQX5b:bxmyasu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/catalog/tabledesc/structured.go#L388)):*
> ```Go
> func (desc *wrapper) GetAllReferencedFunctionIDsInConstraint(
> 	cstID descpb.ConstraintID,
> ) (catalog.DescriptorIDSet, error) {
> ```

Might be cleaner to name the variables here?
___
*[`pkg/sql/schemachanger/scdeps/sctestdeps/test_deps.go` line 575 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOW32gF-vOPJWqTqkRr:-NOW32gF-vOPJWqTqkRs:b-1xi7pw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/schemachanger/scdeps/sctestdeps/test_deps.go#L575)):*
> ```Go
> func (s *TestState) getQualifiedNameComponentsByID(
> 	id descpb.ID,
> ) (dbName string, scName string, objName string, err error) {
> ```

Maybe switch this to tree.ObjectNamePrefix and tree.Name



_Code quote:_
```Go
NewTableNameWithSchema
```
___
*[`pkg/sql/schemachanger/scexec/scmutationexec/references.go` line 287 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOW3RwK0z5MCe07Nrsv:-NOW3RwK0z5MCe07Nrsw:bq3mr49) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/schemachanger/scexec/scmutationexec/references.go#L287)):*
> ```Go
> 	ctx context.Context, op scop.RemoveAllTableBackReferencesFromFunctions,
> ) error {
> 	for _, fnID := range op.FunctionIDs {
> ```

This is suspicious and is never used. So, we probably should axe it
___
*[`pkg/sql/logictest/testdata/logic_test/computed` line 286 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOW4H7-EBnUp3dC7s0b:-NOW4H702pkd5LjIAD9H:b-6j8vx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/logictest/testdata/logic_test/computed#L286)):*
> ```
> DROP TABLE tmp
> 
> statement error expected STORED COMPUTED COLUMN expression to have type int, but ''not an integer!'::STRING' has type string
> ```

Might be worth checking the precedence of error messages to see how we normally refer to these things, especially the upper case part.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_in_constraints` line 341 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOW4ta328Ymyz5m8XQk:-NOW4ta328Ymyz5m8XQl:b6s8v0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/logictest/testdata/logic_test/udf_in_constraints#L341)):*
> ```
> BEGIN;
> ALTER TABLE t1 DROP CONSTRAINT check_b;
> DROP FUNCTION f1;
> ```

This seems weird we should wait for the job at END even in the legacy world?



_Code quote:_
```
# In legacy schema changer, constraints are formally dropped in jobs.
# So by the point we do DROP FUNCTION, constraints are still there.
```

**Review by fqazi — COMMENTED** [review]
Great work, some stuff needs to be tweaked. Didn't notice anything too major

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-:-NOW5m-B3iidjpf79LV_:b-v1yedi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan)

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97038)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/backfill.go` line 468 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOVP2hr8aFDdfT3FWCO:-NOWE_U21B5VsToepQW8:bl7a8qs) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/backfill.go#L468)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Is that true? I would think in a retry case we would just see it again or am I missing something? Also do you mean a job retry or a transaction one here?
</blockquote></details>

I meant a job retry here. Unfortunately, looks like we create several different internal transactions here and there within one job. So it possible that this `dropConstraint` gets committed, but something else failed... A transaction retry would be a lot easier, since everything stays the same on each try. I'll update the comment a bit. Also FYI that he removal of references are noop if there is no reference.
___
*[`pkg/sql/catalog/funcdesc/func_desc.go` line 544 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOVvAt513hgAXk1oUz8:-NOWGyZ1AXAL2_ok4mqM:b-kqsgim) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/catalog/funcdesc/func_desc.go#L544)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Why are make a new set here? Is it just to make a copy?
</blockquote></details>

yeah, also wanted to deduplicate constraint IDs.
___
*[`pkg/sql/catalog/funcdesc/func_desc.go` line 565 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOVvnhPAH6_ym7TpUpX:-NOWHLE0CbmRG8Z24CID:bbec00u) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/catalog/funcdesc/func_desc.go#L565)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

The set here seems like its over kill for removal?
</blockquote></details>

heh, yeah, I just thing using set is convenient here. Also I think it's safer now to do copies because of the generalized execution time work in declarative schema changer. Because we redo things in pre-commit phase which are done in statement phase, so reusing underlying arrays of slices is dangerous... I hit into one funny bug because of this when doing the `DROP FUNCTION`....
___
*[`pkg/sql/catalog/rewrite/rewrite.go` line 105 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOVwG8h95ICvA4q77rk:-NOWI-oL1GGi8eogl1s_:bfglwi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/catalog/rewrite/rewrite.go#L105)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I guess before this point we validated it's okay to drop the mutation. Think this is used in the restore?
</blockquote></details>

correct, this is for restore. there is some code checking the `skip_missing_udfs` flag before this, here we assume the dropping is expected.
___
*[`pkg/sql/catalog/rewrite/rewrite.go` line 426 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOVxmNVBJPjjJUfPC77:-NOWIFse7tROquF8AHZG:bc4jvy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/catalog/rewrite/rewrite.go#L426)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Shouldn't this always hold and if it doesn't isn't a fatal thing?
</blockquote></details>

good question, I was thinking users might be crazy to use the `[Function OID]` syntax themselves heh, maybe I'm paranoid lol. I'd like to keep this if you don't feel strongly against it.
___
*[`pkg/sql/catalog/rewrite/rewrite.go` line 753 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOVzC-qDJmDrghCL04D:-NOWIXpGBaJuDG_t_cgI:b-iza3g4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/catalog/rewrite/rewrite.go#L753)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

We can should be able to rel to do this, see attr.go
</blockquote></details>

Good point, will refactor this a bit.
___
*[`pkg/sql/catalog/tabledesc/structured.go` line 388 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOW1Un98LgW_LmeQX5a:-NOWIdDw1Ou6owpWG8FD:bh90wl7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/catalog/tabledesc/structured.go#L388)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Might be cleaner to name the variables here?
</blockquote></details>

Good point, will do.
___
*[`pkg/sql/schemachanger/scexec/scmutationexec/references.go` line 287 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOW3RwK0z5MCe07Nrsv:-NOWJ0PB13JB9pWBIl1E:b-wrrra7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/schemachanger/scexec/scmutationexec/references.go#L287)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

This is suspicious and is never used. So, we probably should axe it
</blockquote></details>

heh, good catch, I was trying to use this for `DROP TABLE` in declarative schema changer, then figure it doesn't work. Then your remove `skip ops` work saved me. will remove this.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_in_constraints` line 341 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOW4ta328Ymyz5m8XQk:-NOWJQwf-JTvTVrHyN1w:b6pgt6r) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/logictest/testdata/logic_test/udf_in_constraints#L341)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

This seems weird we should wait for the job at END even in the legacy world?
</blockquote></details>

yeah very weird...

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97038)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/backfill.go` line 468 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOVP2hr8aFDdfT3FWCO:-NOWL4nfD0HJaAFhwYgv:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/backfill.go#L468)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

I meant a job retry here. Unfortunately, looks like we create several different internal transactions here and there within one job. So it possible that this `dropConstraint` gets committed, but something else failed... A transaction retry would be a lot easier, since everything stays the same on each try. I'll update the comment a bit. Also FYI that he removal of references are noop if there is no reference.
</blockquote></details>

done
___
*[`pkg/sql/catalog/descriptor_id_set.go` line 86 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOVrXoMAWmqaZt4oeRw:-NOWL7a1BPVpXjJQHJyM:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/catalog/descriptor_id_set.go#L86)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Give this a comment for documentation
</blockquote></details>

done.
___
*[`pkg/sql/catalog/descs/dist_sql_function_resolver.go` line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOVswm3AKq2UKFl0uPp:-NOWLH8f4N--TpQ8nOCz:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/catalog/descs/dist_sql_function_resolver.go#L41)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Maybe have this as a TODO? I know references are stored as OIDs but someone is going to accidentally use this at some point.
</blockquote></details>

done
___
*[`pkg/sql/catalog/rewrite/rewrite.go` line 753 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOVzC-qDJmDrghCL04D:-NOWO7gh5eIHZMOHVT9n:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/catalog/rewrite/rewrite.go#L753)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

Good point, will refactor this a bit.
</blockquote></details>

done
___
*[`pkg/sql/catalog/schemaexpr/expr.go` line 611 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOW0ootBWryu5hSrK2-:-NOWOMUwEjKzd3t_jbQq:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/catalog/schemaexpr/expr.go#L611)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Nit: UDF
</blockquote></details>

done
___
*[`pkg/sql/catalog/tabledesc/structured.go` line 388 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOW1Un98LgW_LmeQX5a:-NOWO_SFCQTuHjFrhGgg:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/catalog/tabledesc/structured.go#L388)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

Good point, will do.
</blockquote></details>

done
___
*[`pkg/sql/schemachanger/scdeps/sctestdeps/test_deps.go` line 575 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOW32gF-vOPJWqTqkRr:-NOWPnTr30z2-UhK6Wfz:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/schemachanger/scdeps/sctestdeps/test_deps.go#L575)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Maybe switch this to tree.ObjectNamePrefix and tree.Name
</blockquote></details>

done
___
*[`pkg/sql/schemachanger/scexec/scmutationexec/references.go` line 287 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOW3RwK0z5MCe07Nrsv:-NOWQI57DZfrv8mXvJNa:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/schemachanger/scexec/scmutationexec/references.go#L287)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

heh, good catch, I was trying to use this for `DROP TABLE` in declarative schema changer, then figure it doesn't work. Then your remove `skip ops` work saved me. will remove this.
</blockquote></details>

done

**Comment by chengxiong-ruan** [comment]
*[`pkg/sql/logictest/testdata/logic_test/computed` line 286 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOW4H7-EBnUp3dC7s0b:-NOWRRSfB9C6PHyX6xgh:bdepo88) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/logictest/testdata/logic_test/computed#L286)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Might be worth checking the precedence of error messages to see how we normally refer to these things, especially the upper case part.
</blockquote></details>

Oh, previously they're just pure string and we just used them for logging which were all passed downed to the level of `DequalifyAndValidateExprImpl` where all expression are validated and checked.  Now I changed them to upper case and a stronger type to make it for an easier read and also made it more consistent through different cases. Also now easier to do `switch` on them for context checking.

**Review by fqazi — APPROVED** [review]
:lgtm: Please double-check if the error message changes are consistent in all contexts. Consistency wise it would be bad if we were using upper case in one context and lower case in some other type of message referring to the same object.

> Reviewed 34 of 34 files at r4, 21 of 21 files at r5, 1 of 20 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-:-NOjEO0dBn-WoDW5tUsM:bjpnje1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @chengxiong-ruan)

___
*[`-- commits` line 25 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOjCLST0PiTp1YiWxhx):*
Nit: circular dependencies



_Code quote:_
```
Dependency circles 
```
___
*[`pkg/sql/sem/tree/udf.go` line 554 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOjDF0q7LVhvJH2KOz5:-NOjDF0q7LVhvJH2KOz6:b8uyaf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f601e7e09f93a67b8a304d00c93ddf7ff17d7409/pkg/sql/sem/tree/udf.go#L554)):*
> ```Go
> 
> const (
> 	AlterColumnTypeUsingExpr        SchemaExprContext = "ALTER COLUMN TYPE USING EXPRESSION"
> ```

This stuff touches a lot of messages my only concern is if we are consistent in the messages with the upper case stuff (in other scenarios). I know syntax wise it makes sense, just something to think about.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_in_constraints` line 341 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOW4ta328Ymyz5m8XQk:-NOjDWR9AMdYxWgBo1Bv:b-kg8tne) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/logictest/testdata/logic_test/udf_in_constraints#L341)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

yeah very weird...
</blockquote></details>

This is worth investigating and filing an issue. This can have really bad side effects, a user transaction is returning success before it actually completes. I don't think your changes caused this one.

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97038)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`-- commits` line 25 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOjCLST0PiTp1YiWxhx):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Nit: circular dependencies
</blockquote></details>

Done
___
*[`pkg/sql/sem/tree/udf.go` line 554 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOjDF0q7LVhvJH2KOz5:-NOkv6c83gsJlCuKHgN2:bsybnbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f601e7e09f93a67b8a304d00c93ddf7ff17d7409/pkg/sql/sem/tree/udf.go#L554)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

This stuff touches a lot of messages my only concern is if we are consistent in the messages with the upper case stuff (in other scenarios). I know syntax wise it makes sense, just something to think about.
</blockquote></details>

Good call. I just checked with a regex search through our logic test with something like `statement error .* create table` (or alter table), looks like the convention is upper case. It's actually funny the we were not consistent with all the strings listed here. For example `TTL DEFAULT` and `TTL UPDATE` were upper case, and most of other things are lower cases....
___
*[`pkg/sql/logictest/testdata/logic_test/udf_in_constraints` line 341 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97038#-NOW4ta328Ymyz5m8XQk:-NOl-ehNBVsmMt81oVjV:ba7lzoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a106b018a9288e4a06e39721f1f135e046472af9/pkg/sql/logictest/testdata/logic_test/udf_in_constraints#L341)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

This is worth investigating and filing an issue. This can have really bad side effects, a user transaction is returning success before it actually completes. I don't think your changes caused this one.
</blockquote></details>

I think this is an known issue and limitation on legacy schema changer which make it hard to support transactional schema change in the old world :(
Another example is you have a column `a` uses a enum type `e`, then you would see similar issues:
```
BEGIN:
ALTER TABLE t DROP COLUMN a;
DROP TYPE e;
END;
```
The good news is that declarative schema changer handles the side effects really well now :)

**Comment by chengxiong-ruan** [comment]
TFTR! @fqazi 
bors r+

**Pull request merged**
