### PR TITLE
colserde: optimize arrow encoding for some types

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, the arrow batch encoder used an inefficient method to encode
the following datatypes:

- Decimal
- Interval
- Timestamp
- Other datatypes without builtin support in vectorized

This commit improves the performance significantly for these types, by
avoiding extra allocations and copies for scratch buffers for each of
the elements in a column. This will provide marginally increased
performance for distributed queries that need to send a lot of data of
these datatypes across the network.

```
name                                                             old time/op    new time/op     delta
ArrowBatchConverter/decimal/nullFraction=0.00/BatchToArrow-32    231µs ± 1%      138µs ± 1%     -40.36%  (p=0.000 n=10+10)
ArrowBatchConverter/decimal/nullFraction=0.00/ArrowToBatch-32    379µs ± 1%      384µs ± 1%     +1.34%   (p=0.001 n=10+10)
ArrowBatchConverter/timestamp/nullFraction=0.00/BatchToArrow-32  55.5µs ± 1%     44.5µs ± 1%    -19.80%  (p=0.000 n=10+10)
ArrowBatchConverter/timestamp/nullFraction=0.00/ArrowToBatch-32  92.3µs ± 1%     92.2µs ± 1%    ~        (p=0.912 n=10+10)
ArrowBatchConverter/interval/nullFraction=0.00/BatchToArrow-32   26.5µs ± 1%     7.6µs ± 1%     -71.14%  (p=0.000 n=10+10)
ArrowBatchConverter/interval/nullFraction=0.00/ArrowToBatch-32   2.17µs ± 3%     2.11µs ± 3%    ~        (p=0.136 n=10+10)

name                                                             old speed      new speed       delta
ArrowBatchConverter/decimal/nullFraction=0.00/BatchToArrow-32    98.8MB/s ± 1%  165.9MB/s ± 1%  +67.90%   (p=0.000 n=10+10)
ArrowBatchConverter/decimal/nullFraction=0.00/ArrowToBatch-32    60.2MB/s ± 1%  59.5MB/s ± 1%   -1.19%    (p=0.001 n=10+10)
ArrowBatchConverter/timestamp/nullFraction=0.00/BatchToArrow-32  443MB/s ± 1%   552MB/s ± 1%    +24.69%   (p=0.000 n=10+10)
ArrowBatchConverter/timestamp/nullFraction=0.00/ArrowToBatch-32  266MB/s ± 1%   266MB/s ± 1%    ~         (p=0.912 n=10+10)
ArrowBatchConverter/interval/nullFraction=0.00/BatchToArrow-32   927MB/s ± 1%   3213MB/s ± 1%   +246.52%  (p=0.000 n=10+10)
ArrowBatchConverter/interval/nullFraction=0.00/ArrowToBatch-32   11.3GB/s ± 3%  11.6GB/s ± 3%     ~       (p=0.143 n=10+10)

name                                                             old alloc/op   new alloc/op    delta
ArrowBatchConverter/decimal/nullFraction=0.00/BatchToArrow-32    200kB ± 0%     102kB ± 0%      -48.87%  (p=0.001 n=8+9)
ArrowBatchConverter/decimal/nullFraction=0.00/ArrowToBatch-32    110kB ± 0%     110kB ± 0%      +0.50%   (p=0.000 n=10+10)
ArrowBatchConverter/timestamp/nullFraction=0.00/BatchToArrow-32  64.5kB ± 0%    54.3kB ± 0%     -15.77%  (p=0.000 n=10+10)
ArrowBatchConverter/timestamp/nullFraction=0.00/ArrowToBatch-32  164kB ± 0%     164kB ± 0%      ~        (all equal)
ArrowBatchConverter/interval/nullFraction=0.00/BatchToArrow-32   89.0kB ± 0%    29.7kB ± 0%     -66.62%  (p=0.000 n=10+10)
ArrowBatchConverter/interval/nullFraction=0.00/ArrowToBatch-32   0.00B          0.00B           ~        (all equal)

name                                                             old allocs/op  new allocs/op   delta
ArrowBatchConverter/decimal/nullFraction=0.00/BatchToArrow-32    5.36k ± 0%     2.06k ± 0%      -61.67%  (p=0.000 n=10+10)
ArrowBatchConverter/decimal/nullFraction=0.00/ArrowToBatch-32    4.97k ± 0%     5.00k ± 0%      +0.48%   (p=0.000 n=10+10)
ArrowBatchConverter/timestamp/nullFraction=0.00/BatchToArrow-32  1.05k ± 0%     1.03k ± 0%      -1.72%   (p=0.000 n=10+10)
ArrowBatchConverter/timestamp/nullFraction=0.00/ArrowToBatch-32  3.07k ± 0%     3.07k ± 0%      ~        (all equal)
ArrowBatchConverter/interval/nullFraction=0.00/BatchToArrow-32   26.0 ± 0%      6.0 ± 0%        -76.92%  (p=0.000 n=10+10)
ArrowBatchConverter/interval/nullFraction=0.00/ArrowToBatch-32   0.00           0.00            ~        (all equal)
```

Release note (performance improvement): improve the performance for
distributed queries that need to send a lot of data of certain datatypes
across the network.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Very nice!

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64169#-:-MZ0N8e40JBMD2nB96lO:b-j7qk9t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/col/colserde/arrowbatchconverter.go, line 62 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64169#-MZ0MwPt07VunWFcc7V-:-MZ0MwPt07VunWFcc7V0:btzv9to) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9f81163222a22a3a7522708ae90a7b4ef6df489/pkg/col/colserde/arrowbatchconverter.go#L62)):*
> ```Go
> 	c := &ArrowBatchConverter{typs: typs}
> 	c.builders.boolBuilder = array.NewBooleanBuilder(memory.DefaultAllocator)
> 	c.builders.binaryBuilder = array.NewBinaryBuilder(memory.DefaultAllocator, arrow.BinaryTypes.Binary)
> ```

I think we can now remove `binaryBuilder` entirely.
___
*[pkg/col/colserde/arrowbatchconverter.go, line 124 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64169#-MZ0L0vS3g0v8o65OBag:-MZ0L0vS3g0v8o65OBah:b-mpou17) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9f81163222a22a3a7522708ae90a7b4ef6df489/pkg/col/colserde/arrowbatchconverter.go#L124)):*
> ```Go
> 			var offsets []int32
> 			values, offsets = vec.Bytes().ToArrowSerializationFormat(n)
> 			unsafeCastOffsetsArray(offsets, &offsetsBytes)
> ```

super nit: it'd be nice to insert empty lines after every case for consistency.
___
*[pkg/col/colserde/arrowbatchconverter.go, line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64169#-MZ0Ljcb-r_hLlDbMWrO:-MZ0Ljcb-r_hLlDbMWrP:b-v892kz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9f81163222a22a3a7522708ae90a7b4ef6df489/pkg/col/colserde/arrowbatchconverter.go#L174)):*
> ```Go
> 			intervalSize := sizeOfInt64 * 3
> 			values = make([]byte, intervalSize*n)
> 			var curNonNullInterval int
> ```

Itd be curious to see whether it would be faster to pre-calculate the number of nulls (by iterating over the null bitmap) and then allocate `values` of the exact needed capacity. Probably wouldn't matter much though.
___
*[pkg/col/colserde/arrowbatchconverter.go, line 234 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64169#-MZ0MTepAL_6fRKFQCj0:-MZ0MTepAL_6fRKFQCj1:b-c21l6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9f81163222a22a3a7522708ae90a7b4ef6df489/pkg/col/colserde/arrowbatchconverter.go#L234)):*
> ```Go
> 			}
> 			offsets = append(offsets, int32(len(values)))
> 			unsafeCastOffsetsArray(offsets, &offsetsBytes)
> ```

super nit: ditto for an empty line.
___
*[pkg/col/colserde/arrowbatchconverter.go, line 279 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64169#-MZ0MbwECxDPmRTpEArb:-MZ0MbwECxDPmRTpEArc:b62bzs9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9f81163222a22a3a7522708ae90a7b4ef6df489/pkg/col/colserde/arrowbatchconverter.go#L279)):*
> ```Go
> 	// Cast int32Offsets to []byte.
> 	int32Header := (*reflect.SliceHeader)(unsafe.Pointer(&offsetsInt32))
> 	offsetsHeader := (*reflect.SliceHeader)(unsafe.Pointer(offsetsBytes))
> ```

nit: `s/offsetsHeader/bytesHeader/`.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64169)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/col/colserde/arrowbatchconverter.go, line 62 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64169#-MZ0MwPt07VunWFcc7V-:-MZAjrRj8lvyAv1JKl10:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9f81163222a22a3a7522708ae90a7b4ef6df489/pkg/col/colserde/arrowbatchconverter.go#L62)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think we can now remove `binaryBuilder` entirely.
</blockquote></details>

Done.
___
*[pkg/col/colserde/arrowbatchconverter.go, line 124 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64169#-MZ0L0vS3g0v8o65OBag:-MZAjrly62UfbMDLMc6Q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9f81163222a22a3a7522708ae90a7b4ef6df489/pkg/col/colserde/arrowbatchconverter.go#L124)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

super nit: it'd be nice to insert empty lines after every case for consistency.
</blockquote></details>

Done.
___
*[pkg/col/colserde/arrowbatchconverter.go, line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64169#-MZ0Ljcb-r_hLlDbMWrO:-MZAkWSnBQdXPfgJOD2l:borso6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9f81163222a22a3a7522708ae90a7b4ef6df489/pkg/col/colserde/arrowbatchconverter.go#L174)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Itd be curious to see whether it would be faster to pre-calculate the number of nulls (by iterating over the null bitmap) and then allocate `values` of the exact needed capacity. Probably wouldn't matter much though.
</blockquote></details>

Good idea. It requires implementing .Count() on Nulls, which is a slight project in and of itself (bits.OnesCount can be used, but really we should be using fast x86 `popcnt` instruction which is not available in Go). So I will leave this for another time.
___
*[pkg/col/colserde/arrowbatchconverter.go, line 234 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64169#-MZ0MTepAL_6fRKFQCj0:-MZAlrMW-nAVqXb3lMXO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9f81163222a22a3a7522708ae90a7b4ef6df489/pkg/col/colserde/arrowbatchconverter.go#L234)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

super nit: ditto for an empty line.
</blockquote></details>

Done.

**Review by yuzefovich — APPROVED** [review]
:lgtm: needs `make bazel-generate`.

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64169#-:-MZB8aXfAYxh7_9SQFqe:b-b4mbji)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/col/colserde/arrowbatchconverter.go, line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64169#-MZ0Ljcb-r_hLlDbMWrO:-MZB8ARiCPorzU1b5qCG:b7zej0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9f81163222a22a3a7522708ae90a7b4ef6df489/pkg/col/colserde/arrowbatchconverter.go#L174)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Good idea. It requires implementing .Count() on Nulls, which is a slight project in and of itself (bits.OnesCount can be used, but really we should be using fast x86 `popcnt` instruction which is not available in Go). So I will leave this for another time.
</blockquote></details>

Maybe leave a TODO here?
___
*[pkg/col/colserde/arrowbatchconverter.go, line 195 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64169#-MZB8mvl037JDW7Ox0s7:-MZB8mvl037JDW7Ox0s8:bgxdl6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b67da2581fa82a6c389d8faf393e50af075deb/pkg/col/colserde/arrowbatchconverter.go#L195)):*
> ```Go
> 			offsets := make([]int32, 0, n+1)
> 			timestamps := vec.Timestamp()[:n]
> 			// See implementation of time.MarshalBinary
> ```

nit: missing period.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64169)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/col/colserde/arrowbatchconverter.go, line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64169#-MZ0Ljcb-r_hLlDbMWrO:-MZDEdec6gKRJ5K-2qjO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9f81163222a22a3a7522708ae90a7b4ef6df489/pkg/col/colserde/arrowbatchconverter.go#L174)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Maybe leave a TODO here?
</blockquote></details>

Done.

**Review by jordanlewis — COMMENTED** [review]
bors r+

TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64169#-:-MZDOHo4CsrXV35ByYdv:b7q5wln)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

**Comment by jordanlewis** [comment]
bors r+

rebased to avoid flakes hopefully

**Pull request merged**
