### PR TITLE
Re-merge ambiguous commit error PR with locking fixes

### LINKED ISSUE #10184: sql: TestAmbiguousCommit is susceptible to deadlock
Spotted in https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=35691#_focus=8201

Interesting part of the log:

```
[19:47:18][TestAmbiguousCommit] goroutine 2742 [chan receive, 1 minutes]:
[19:47:18][TestAmbiguousCommit] github.com/cockroachdb/cockroach/pkg/sql_test.TestAmbiguousCommit(0xc4209b6240)
[19:47:18][TestAmbiguousCommit] 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/ambiguous_commit_test.go:140 +0x7e7
[19:47:18][TestAmbiguousCommit] testing.tRunner(0xc4209b6240, 0x19e3ff8)
[19:47:18][TestAmbiguousCommit] 	/usr/local/go/src/testing/testing.go:610 +0x81
[19:47:18][TestAmbiguousCommit] created by testing.(*T).Run
[19:47:18][TestAmbiguousCommit] 	/usr/local/go/src/testing/testing.go:646 +0x2ec
```

Also reproduced locally:
```
make stress PKG=./pkg/sql TESTS=TestAmbiguousCommit TESTTIMEOUT=30s
6 runs so far, 0 failures, over 5s
6 runs so far, 0 failures, over 10s
10 runs so far, 0 failures, over 15s
14 runs so far, 0 failures, over 20s
16 runs so far, 0 failures, over 25s
17 runs so far, 0 failures, over 30s
23 runs so far, 0 failures, over 35s
31 runs so far, 0 failures, over 40s
36 runs so far, 0 failures, over 45s
...
goroutine 7 [chan receive]:
github.com/cockroachdb/cockroach/pkg/sql_test.TestAmbiguousCommit(0xc42008c540)
	/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/ambiguous_commit_test.go:140 +0x7e7
testing.tRunner(0xc42008c540, 0x54bade0)
	/Users/tamird/src/go1.7/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/Users/tamird/src/go1.7/src/testing/testing.go:646 +0x2ec
```

So looks like there's a real problem with the test.

### LINKED ISSUE #10204: Un-revert #10154 (Return error if result of a txn commit is unknown)
To get `delta` working again, @tschottdorf had to revert #10154. Let's fix and have it re-enter the stability queue to be merged serially as we originally intended.

### PR DESCRIPTION
**Pull request by spencerkimball**
See #10154
Fixes #10204 
Fixes #10184

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10207)

### CODE REVIEW

**Comment by spencerkimball** [comment]
I'm still working on the split queue issue.

**Comment by tamird** [comment]
Note that you need a separate "Fixes #..." line for each issue you wish to close. https://github.com/cockroachdb/cockroach/issues/7604 and https://github.com/cockroachdb/cockroach/issues/10023 were not closed by your original PR.

**Comment by petermattis** [comment]
Review status: 0 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/kv/transport.go, line 166 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUx9d4JdkF0_7_32fXr:-KUx9d4JdkF0_7_32fXs:b-o7kcpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/kv/transport.go#L166)):*
> ```Go
> 	client.pending = true
> 	gt.clientIndex++
> 	gt.Unlock()
> ```

How could the previous code get away without locking while this code can't? Seems to me that you only need to protect `client.pending` here as `gt.clientIndex` is always accessed from a single goroutine. Also note that `IsExhausted` accesses `gt.clientIndex` without grabbing the lock. If this is true, I think you should rename `grpcTransport.Mutex` to `grpcTransport.clientPendingMu`. 

---

*[pkg/kv/transport.go, line 235 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUxAAYEoxGfodBlJASw:-KUxAAYEoxGfodBlJASx:b2qbad4) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/kv/transport.go#L235)):*
> ```Go
> 			// Swap the client representing this replica to the front.
> 			gt.orderedClients[i], gt.orderedClients[gt.clientIndex] =
> 				gt.orderedClients[gt.clientIndex], gt.orderedClients[i]
> ```

I think this has a bad interaction with `SendNext`. `SendNext` grabs a pointer to the i-th client, but you're swapping the underlying elements (not pointers) here which means when `SendNext` finishes it could clear `client.pending` for the wrong `batchClient`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207)*

**Comment by tamird** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/kv/dist_sender.go, line 1055 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUx8EqukoVwtGaEQEvJ:-KUx8EqukoVwtGaEQEvK:b7rw9en) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/kv/dist_sender.go#L1055)):*
From the original PR:

> where did you read that this is the error code to check for? aren't there other codes which correspond to the definitely-not-sent condition?

> I looked at the GRPC source code. This is the fail fast condition and it's an error code which isn't used for any other purpose.

Can you add this to the comment, preferably with a link to the relevant part of the grpc source? Remember to replace `blob/master` with `blob/SHA` where SHA is the specific commit you looked at.

---

*[pkg/kv/dist_sender.go, line 1075 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUx9blH54OkuZkfMhQf:-KUx9blH54OkuZkfMhQg:b-94yeoi) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/kv/dist_sender.go#L1075)):*
From the original PR:
> That would lose the very-purposeful verbosity level specified here. I'm still not sure what appropriate usage of the recent explosion of new log/tracing/event APIs is. I'm wrapping log.ErrEvent in a log.V(2) as a solution, but it doesn't necessarily feel right. Did you have something else in mind?

@raduberinde: care to weigh in?

---

*[pkg/kv/transport.go, line 151 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUxA33jNGZRE5ThcjXE:-KUxA33jNGZRE5ThcjXF:b5bj9bz) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/kv/transport.go#L151)):*
> ```Go
> 	clientIndex    int
> 	orderedClients []batchClient
> 	syncutil.Mutex
> ```

not everything in this structure is protected by this mutex. Can you please introduce an anonymous struct that includes only the mutex and fields protected by it?

---

*[pkg/kv/transport_test.go, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUxAdfOBHLT3bbD3m66:-KUxAdfOBHLT3bbD3m67:biipw6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/kv/transport_test.go#L41)):*
From the original PR:

> As discussed in many recent PRs, this is bad practice that results in this line number being reported in failures, which makes it impossible to determine which invocation of this function resulted in an unexpected result. Helpers such as this one should return errors for this reason.

> It would nearly triple the size of this method. And FYI, this is why I made the error a t.Fatalf, so that the stack trace shows the line number in the test that resulted in the failure.

`t.Fatal` does not produce a stack trace, so I still think this needs to change.

---

*[pkg/sql/ambiguous_commit_test.go, line 45 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUxBhvneIXgvH7EYIs0:-KUxBhvneIXgvH7EYIs1:b-cpl6tf) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/sql/ambiguous_commit_test.go#L45)):*
> ```Go
> // key is specified in advance, it can result in violated uniqueness
> // constraints, or duplicate key violations. See #6053, #7604, and #10023.
> func TestAmbiguousCommit(t *testing.T) {
> ```

Please be sure to address https://github.com/cockroachdb/cockroach/issues/10184 before merging this.

---

*[pkg/sql/ambiguous_commit_test.go, line 86 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUxAya_AImfKUDEivAm:-KUxAyaawWeGW87xvExu:b2zgwp2) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/sql/ambiguous_commit_test.go#L86)):*
From the original PR:

> please check these errors.

> It's a SQLRunner, which already asserts there are no errors.

OK, but that's not clear to me as a reader of this code, so I would prefer that you check the errors to minimize head-scratching.

---

*[pkg/sql/ambiguous_commit_test.go, line 147 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUxBRH_LWQYnIFdLOin:-KUxBRH_LWQYnIFdLOio:bs5wkvl) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/sql/ambiguous_commit_test.go#L147)):*
From the original PR:
> unchecked error? how did this pass lint?

> Because the SQLRunner asserts no error.

Huh? The linter doesn't know that. For the reasons mentioned above, I would prefer that you check this error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[pkg/kv/dist_sender.go, line 1022 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUyeMqlCFma5aFWkpDu:-KUyeMqlCFma5aFWkpDv:b-uo6dhs) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/kv/dist_sender.go#L1022)):*
> ```Go
> 					// should return it instead of trying other replicas. However,
> 					// if there are still other RPCs outstanding or an ambiguous
> 					// RPC error was received, we must continue.
> ```

The meaning of "continue" here is unclear. How about "we must return an ambiguous status instead of the returned error"? 

---

*[pkg/kv/transport.go, line 235 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUxAAYEoxGfodBlJASw:-KUys8wboS0v_BGpY4-k:b-a15bh3) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/kv/transport.go#L235)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I think this has a bad interaction with `SendNext`. `SendNext` grabs a pointer to the i-th client, but you're swapping the underlying elements (not pointers) here which means when `SendNext` finishes it could clear `client.pending` for the wrong `batchClient`.
</details>
Yeah, this needs to change to pointers. 

---

*[pkg/sql/ambiguous_commit_test.go, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUyhM12RZI9ClCjqb-G:-KUyhM12RZI9ClCjqb-H:bhfv51q) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/sql/ambiguous_commit_test.go#L53)):*
> ```Go
> 	committed := make(chan struct{})
> 	wait := make(chan struct{})
> 	tableStartKey := keys.MakeTablePrefix(51 /* initial table ID */)
> ```

Define this in terms of some constant (keys.MaxReservedTableID?). Or could we query for the table ID after creating it? (I don't think it's in information_schema yet but we should add it)

---

*[pkg/sql/ambiguous_commit_test.go, line 121 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUyiPV8VXQfnhYWhvwu:-KUyiPV8VXQfnhYWhvwv:b1orexh) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/sql/ambiguous_commit_test.go#L121)):*
> ```Go
> 	go func() {
> 		// Use a connection other than through the node which is the current
> 		// leaseholder to ensure that we use GRPC instead of the local server.
> ```

Why does it matter that we use GRPC here? Isn't the ambiguous commit logic at a high enough level that we'd get an ambiguous commit error if the local node was hanging? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-:-KUytKasOOm9-R8GVAt-:b593vm9)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[pkg/sql/ambiguous_commit_test.go, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUyhM12RZI9ClCjqb-G:-KV0SASFYC_bWHOyehno:b-rgm0o5) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/sql/ambiguous_commit_test.go#L53)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Define this in terms of some constant (keys.MaxReservedTableID?). Or could we query for the table ID after creating it? (I don't think it's in information_schema yet but we should add it)
</details>
I have such a query in `pkg/cmd/zerosum/main.go`. I borrowed this query in #10232.

---

*[pkg/sql/ambiguous_commit_test.go, line 86 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUxAya_AImfKUDEivAm:-KV0SQjtqrg3HQ2P34u-:b-4r73fl) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/sql/ambiguous_commit_test.go#L86)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> From the original PR:
> 
> > please check these errors.
> 
> > It's a SQLRunner, which already asserts there are no errors.
> 
> OK, but that's not clear to me as a reader of this code, so I would prefer that you check the errors to minimize head-scratching.
</details>
`SQLRunner.Exec` does not return an error. 

---

*[pkg/sql/ambiguous_commit_test.go, line 147 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUxBRH_LWQYnIFdLOin:-KV0SZLd9XPZha0mPd9V:b-5d8qkk) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/sql/ambiguous_commit_test.go#L147)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> From the original PR:
> > unchecked error? how did this pass lint?
> 
> > Because the SQLRunner asserts no error.
> 
> Huh? The linter doesn't know that. For the reasons mentioned above, I would prefer that you check this error.
</details>
`sqlutils.Row.Scan` does not return an error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[pkg/sql/ambiguous_commit_test.go, line 86 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUxAya_AImfKUDEivAm:-KV0Vg5aDdiXeWZIQPU4:b95zjsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/sql/ambiguous_commit_test.go#L86)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `SQLRunner.Exec` does not return an error. 
</details>
Ah, I thought this thing was a `database/sql.DB`.

---

*[pkg/sql/ambiguous_commit_test.go, line 147 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUxBRH_LWQYnIFdLOin:-KV0Vl65I3m6pDKUmJCO:b-bex6p7) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/sql/ambiguous_commit_test.go#L147)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `sqlutils.Row.Scan` does not return an error.
</details>
Oh, that structure generally produces sucky error message. Sigh.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207)*

**Comment by spencerkimball** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[pkg/kv/dist_sender.go, line 1022 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUyeMqlCFma5aFWkpDu:-KV0eYWOlNbEIUxAa05D:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/kv/dist_sender.go#L1022)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> The meaning of "continue" here is unclear. How about "we must return an ambiguous status instead of the returned error"? 
</details>
Done.

---

*[pkg/kv/dist_sender.go, line 1055 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUx8EqukoVwtGaEQEvJ:-KUxJDX8-OjRC3KMNVWW:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/kv/dist_sender.go#L1055)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> From the original PR:
> 
> > where did you read that this is the error code to check for? aren't there other codes which correspond to the definitely-not-sent condition?
> 
> > I looked at the GRPC source code. This is the fail fast condition and it's an error code which isn't used for any other purpose.
> 
> Can you add this to the comment, preferably with a link to the relevant part of the grpc source? Remember to replace `blob/master` with `blob/SHA` where SHA is the specific commit you looked at.
</details>
Done

---

*[pkg/kv/dist_sender.go, line 1075 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUx9blH54OkuZkfMhQf:-KV0eaKfAtqABj9-nsGI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/kv/dist_sender.go#L1075)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> From the original PR:
> > That would lose the very-purposeful verbosity level specified here. I'm still not sure what appropriate usage of the recent explosion of new log/tracing/event APIs is. I'm wrapping log.ErrEvent in a log.V(2) as a solution, but it doesn't necessarily feel right. Did you have something else in mind?
> 
> @raduberinde: care to weigh in?
</details>
Done.

---

*[pkg/kv/transport.go, line 151 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUxA33jNGZRE5ThcjXE:-KUxG_Me-s4MvqqR6v8v:b-tpr1bd) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/kv/transport.go#L151)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> not everything in this structure is protected by this mutex. Can you please introduce an anonymous struct that includes only the mutex and fields protected by it?
</details>
Reorganized for more clarity.

---

*[pkg/kv/transport.go, line 166 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUx9d4JdkF0_7_32fXr:-KUxGbsjWHDzh25qrdI6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/kv/transport.go#L166)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> How could the previous code get away without locking while this code can't? Seems to me that you only need to protect `client.pending` here as `gt.clientIndex` is always accessed from a single goroutine. Also note that `IsExhausted` accesses `gt.clientIndex` without grabbing the lock. If this is true, I think you should rename `grpcTransport.Mutex` to `grpcTransport.clientPendingMu`. 
</details>
Done.

---

*[pkg/kv/transport.go, line 235 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUxAAYEoxGfodBlJASw:-KUxGjnSKdwjLp10mdUr:b-k2rwtz) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/kv/transport.go#L235)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I think this has a bad interaction with `SendNext`. `SendNext` grabs a pointer to the i-th client, but you're swapping the underlying elements (not pointers) here which means when `SendNext` finishes it could clear `client.pending` for the wrong `batchClient`.
</details>
Good catch. Fixed.

---

*[pkg/kv/transport_test.go, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUxAdfOBHLT3bbD3m66:-KUxI3WNOaAsIeb83RnR:bq3xiax) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/kv/transport_test.go#L41)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> From the original PR:
> 
> > As discussed in many recent PRs, this is bad practice that results in this line number being reported in failures, which makes it impossible to determine which invocation of this function resulted in an unexpected result. Helpers such as this one should return errors for this reason.
> 
> > It would nearly triple the size of this method. And FYI, this is why I made the error a t.Fatalf, so that the stack trace shows the line number in the test that resulted in the failure.
> 
> `t.Fatal` does not produce a stack trace, so I still think this needs to change.
</details>
I added caller's line number to the verify function instead.

---

*[pkg/sql/ambiguous_commit_test.go, line 45 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUxBhvneIXgvH7EYIs0:-KV0jlQnOOGVDBTFqvIH:b1r57gx) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/sql/ambiguous_commit_test.go#L45)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Please be sure to address https://github.com/cockroachdb/cockroach/issues/10184 before merging this.
</details>
#10184 has been reassigned to pete, who's submitted a fix.

---

*[pkg/sql/ambiguous_commit_test.go, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUyhM12RZI9ClCjqb-G:-KV0fy21glUaXoGQBsd_:blkpdod) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/sql/ambiguous_commit_test.go#L53)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I have such a query in `pkg/cmd/zerosum/main.go`. I borrowed this query in #10232.
</details>
I moved it into `sqlutils`.

---

*[pkg/sql/ambiguous_commit_test.go, line 86 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUxAya_AImfKUDEivAm:-KUxHCqg_skPK3D8oxyc:b4zxo35) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/sql/ambiguous_commit_test.go#L86)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> From the original PR:
> 
> > please check these errors.
> 
> > It's a SQLRunner, which already asserts there are no errors.
> 
> OK, but that's not clear to me as a reader of this code, so I would prefer that you check the errors to minimize head-scratching.
</details>
There are no errors returned from `SQLRunner`. What's being ignored is the returned `sql.Result` object.

---

*[pkg/sql/ambiguous_commit_test.go, line 121 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUyiPV8VXQfnhYWhvwu:-KV0jXIdytv8iKoLPhjK:b-mkjur8) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/sql/ambiguous_commit_test.go#L121)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Why does it matter that we use GRPC here? Isn't the ambiguous commit logic at a high enough level that we'd get an ambiguous commit error if the local node was hanging? 
</details>
Because the local server doesn't run a goroutine – it executes synchronously, so the dist sender thread of execution does not time out. I expanded the comment.

---

*[pkg/sql/ambiguous_commit_test.go, line 147 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUxBRH_LWQYnIFdLOin:-KUxHM5qFT-UcI1kwyOt:b7x723i) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/sql/ambiguous_commit_test.go#L147)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> From the original PR:
> > unchecked error? how did this pass lint?
> 
> > Because the SQLRunner asserts no error.
> 
> Huh? The linter doesn't know that. For the reasons mentioned above, I would prefer that you check this error.
</details>
Because there's no error returned. This returns a single `sql.Row` result, which this code calls `Scan()` on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207)*

**Comment by tamird** [comment]
I'll address my own comments in a follow-up.

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/kv/transport.go, line 241 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KV19ggZRZipyUC8e85z:-KV19ggZRZipyUC8e86-:br1njcn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a477ff10d983ba2bcf0caf9865882161b3e43a6a/pkg/kv/transport.go#L241)):*
> ```Go
> }
> 
> func (gt *grpcTransport) setPending(replica roachpb.ReplicaDescriptor, pending bool) {
> ```

i don't understand the purpose of this function. all the callers already have a reference to the client, why can't they take `clientPendingMu` and set `pending` directly? Some of the callers currently hold a copy of the client, but there's no reason they couldn't take a reference.

---

*[pkg/kv/transport_test.go, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUxAdfOBHLT3bbD3m66:-KV19wa22NjvI4YzEWCw:b-t6htor) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/kv/transport_test.go#L41)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary>
> I added caller's line number to the verify function instead.
</details>
Please use `caller.Lookup` instead of `runtime.Caller` as we do everywhere else.

---

*[pkg/sql/ambiguous_commit_test.go, line 86 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KUxAya_AImfKUDEivAm:-KV1ABifTdxm2RMlWicw:b-poq88k) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd578f5a8db7fad83a8560d5d473e6767284f241/pkg/sql/ambiguous_commit_test.go#L86)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary>
> There are no errors returned from `SQLRunner`. What's being ignored is the returned `sql.Result` object.
</details>
It would be preferable not to assign it to `_`, since it will cause exactly the confusion that lead me to leave that comment.

---

*[pkg/sql/ambiguous_commit_test.go, line 103 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KV1Auyxm_lgMDTQrBSg:-KV1Auyxm_lgMDTQrBSh:bhl5xbp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a477ff10d983ba2bcf0caf9865882161b3e43a6a/pkg/sql/ambiguous_commit_test.go#L103)):*
> ```Go
> 			t.Fatal(err)
> 		}
> 		if !desc.StartKey.Equal(tableStartKey.Load().([]byte)) {
> ```

please extract a local variable for `tableStartKey.Load().([]byte)`. This looks inherently flaky to me, as written.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-:-KV1CEem4BFp3i4FWjR0:bngrlnu)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/kv/transport.go, line 241 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KV19ggZRZipyUC8e85z:-KV1DWxtFwDtGfnvKApe:bix7vnz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a477ff10d983ba2bcf0caf9865882161b3e43a6a/pkg/kv/transport.go#L241)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> i don't understand the purpose of this function. all the callers already have a reference to the client, why can't they take `clientPendingMu` and set `pending` directly? Some of the callers currently hold a copy of the client, but there's no reason they couldn't take a reference.
</details>
The previous code (which was doing as you suggest) was incorrect. See my comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/kv/transport.go, line 241 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207#-KV19ggZRZipyUC8e85z:-KV1E6QwDrgLi7K9wnkE:b-q8svyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a477ff10d983ba2bcf0caf9865882161b3e43a6a/pkg/kv/transport.go#L241)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> The previous code (which was doing as you suggest) was incorrect. See my comment.
</details>
Ah, I see; of course. I'll add a comment to this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10207)*

**Pull request merged**
