### PR TITLE
sqlsmith: m000re

### PR DESCRIPTION
**Pull request by madelynnblue**
Release note: None

### CODE REVIEW

**Review by justinj — CHANGES_REQUESTED** [review]
:Lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36000#-:-LaRvc0qDT13q7q_g8zx:bmy3po1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj and @mjibson)

___
*[pkg/internal/sqlsmith/scalar.go, line 314 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/36000#-LaRv3ES81pajdZdB657:-LaRv3ES81pajdZdB658:b-qcrvmj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a00e8a81609d812f5cad45314e13b47f9a2eee80/pkg/internal/sqlsmith/scalar.go#L314)):*
> ```Go
> 
> 	t := getRandType()
> 	return tree.NewTypedComparisonExpr(
> ```

I feel like we should have both tuples and subqueries (and arrays) here? Maybe add a TODO to round this out.

**Review by justinj — APPROVED** [review]
didn't mean to block

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36000#-:-LaRve1g3xt-ybDuIlTw:b9sayis)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj and @mjibson)

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36000)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj)

___
*[pkg/internal/sqlsmith/scalar.go, line 314 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/36000#-LaRv3ES81pajdZdB657:-LaRwIxQ5jW3cV8Tghxo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a00e8a81609d812f5cad45314e13b47f9a2eee80/pkg/internal/sqlsmith/scalar.go#L314)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I feel like we should have both tuples and subqueries (and arrays) here? Maybe add a TODO to round this out.
</blockquote></details>

Done.

**Pull request merged**
