### PR TITLE
colexec: fix performance regression for sorting with decimals

### LINKED ISSUE #66713: sql: in-memory sort is slower than on-disk sort
When using the vectorized engine, an in-memory sort seems to be almost 3x slower than an on-disk sort. The issue does not manifest for the row engine. Using the TPC-C dataset with 10 warehouses, I ran the following on my laptop:
```
root@:26257/tpcc> set distsql_workmem = '640 MiB';
SET

Time: 0ms total (execution 0ms / network 0ms)

root@:26257/tpcc> show distsql_workmem;
  distsql_workmem
-------------------
  640 MiB
(1 row)

Time: 1ms total (execution 1ms / network 0ms)

root@:26257/tpcc> explain analyze (verbose) select * from order_line order by ol_d_id;
                                                                 info
---------------------------------------------------------------------------------------------------------------------------------------
  planning time: 267µs
  execution time: 30.6s
  distribution: full
  vectorized: true
  rows read from KV: 3,001,222 (216 MiB)
  cumulative time spent in KV: 3.3s
  maximum memory usage: 549 MiB
  network usage: 0 B (0 messages)

  • sort
  │ columns: (ol_o_id, ol_d_id, ol_w_id, ol_number, ol_i_id, ol_supply_w_id, ol_delivery_d, ol_quantity, ol_amount, ol_dist_info)
  │ ordering: +ol_d_id
  │ nodes: n1
  │ actual row count: 3,001,222
  │ vectorized batch count: 2,931
  │ estimated row count: 3,001,222
  │ order: +ol_d_id
  │
  └── • scan
        columns: (ol_o_id, ol_d_id, ol_w_id, ol_number, ol_i_id, ol_supply_w_id, ol_delivery_d, ol_quantity, ol_amount, ol_dist_info)
        nodes: n1
        actual row count: 3,001,222
        vectorized batch count: 2,931
        KV time: 3.3s
        KV contention time: 0µs
        KV rows read: 3,001,222
        KV bytes read: 216 MiB
        estimated row count: 3,001,222 (100% of the table; stats collected 8 minutes ago)
        table: order_line@primary
        spans: FULL SCAN
(30 rows)

Time: 30.580s total (execution 30.580s / network 0.000s)

root@:26257/tpcc> reset distsql_workmem;
SET

Time: 0ms total (execution 0ms / network 0ms)

root@:26257/tpcc> show distsql_workmem;
  distsql_workmem
-------------------
  64 MiB
(1 row)

Time: 1ms total (execution 1ms / network 0ms)

root@:26257/tpcc> explain analyze (verbose) select * from order_line order by ol_d_id;
                                                                 info
---------------------------------------------------------------------------------------------------------------------------------------
  planning time: 186µs
  execution time: 10.5s
  distribution: full
  vectorized: true
  rows read from KV: 3,001,222 (216 MiB)
  cumulative time spent in KV: 2.8s
  maximum memory usage: 111 MiB
  network usage: 0 B (0 messages)
  max sql temp disk usage: 142 MiB

  • sort
  │ columns: (ol_o_id, ol_d_id, ol_w_id, ol_number, ol_i_id, ol_supply_w_id, ol_delivery_d, ol_quantity, ol_amount, ol_dist_info)
  │ ordering: +ol_d_id
  │ nodes: n1
  │ actual row count: 3,001,222
  │ vectorized batch count: 2,940
  │ estimated row count: 3,001,222
  │ order: +ol_d_id
  │
  └── • scan
        columns: (ol_o_id, ol_d_id, ol_w_id, ol_number, ol_i_id, ol_supply_w_id, ol_delivery_d, ol_quantity, ol_amount, ol_dist_info)
        nodes: n1
        actual row count: 3,001,222
        vectorized batch count: 2,931
        KV time: 2.8s
        KV contention time: 0µs
        KV rows read: 3,001,222
        KV bytes read: 216 MiB
        estimated row count: 3,001,222 (100% of the table; stats collected 9 minutes ago)
        table: order_line@primary
        spans: FULL SCAN
(31 rows)

Time: 10.456s total (execution 10.455s / network 0.000s)
```
This performance difference is consistent, even when running the query multiple times in a row.

### PR DESCRIPTION
**Pull request by DrewKimball**
Previously, the memory accounting performed by the vectorized engine
induced a performance regression (vs row-based) in some cases when
sorting a relation with one or more decimal columns. This is because
the in-memory sorter must call `PerformOperation` as each input batch
is appended to the buffer. For decimal columns, `PerformOperation`
iterates through all elements in the buffer and retrieves their memory
footprints - twice. This causes significant overhead for inputs with
many rows and at least one decimal column. This problem is not unique
to in-memory sorting; for example, hash aggregations and joins also
need to buffer tuples.

This patch adds an allocator function `PerformAppend` that takes
advantage of the fact that the expensive portion of the cost calculation
really only needs to take place over the newly appended tuples. This
can lead to significant savings for operators that store a decimal
column in an `AppendOnlyBufferedBatch`.

Fixes #66713

Release note (performance improvement): Fixed a performance regression
that made the in-memory vectorized sorter slower than the row-engine
sorter when the input had decimal columns.

### CODE REVIEW

**Comment by DrewKimball** [comment]
Execution times for the query from #66713 with memory limits of 64MiB and 640MiB:
```
root@:26257/tpcc> SHOW CLUSTER SETTING sql.distsql.temp_storage.workmem;
  sql.distsql.temp_storage.workmem
------------------------------------
  64 MiB
(1 row)

Time: 1ms total (execution 0ms / network 0ms)

root@:26257/tpcc> explain analyze (verbose) select * from order_line order by ol_d_id;
                                                                 info
---------------------------------------------------------------------------------------------------------------------------------------
  planning time: 46ms
  execution time: 10s
  distribution: full
  vectorized: true
  rows read from KV: 3,001,222 (219 MiB)
  cumulative time spent in KV: 2.5s
  maximum memory usage: 256 MiB
  network usage: 0 B (0 messages)
  max sql temp disk usage: 142 MiB

  • sort
  │ columns: (ol_o_id, ol_d_id, ol_w_id, ol_number, ol_i_id, ol_supply_w_id, ol_delivery_d, ol_quantity, ol_amount, ol_dist_info)
  │ ordering: +ol_d_id
  │ nodes: n1
  │ actual row count: 3,001,222
  │ vectorized batch count: 2,940
  │ estimated row count: 3,001,222
  │ order: +ol_d_id
  │
  └── • scan
        columns: (ol_o_id, ol_d_id, ol_w_id, ol_number, ol_i_id, ol_supply_w_id, ol_delivery_d, ol_quantity, ol_amount, ol_dist_info)
        nodes: n1
        actual row count: 3,001,222
        vectorized batch count: 2,931
        KV time: 2.5s
        KV contention time: 0µs
        KV rows read: 3,001,222
        KV bytes read: 219 MiB
        estimated row count: 3,001,222 (100% of the table; stats collected 15 hours ago)
        table: order_line@primary
        spans: FULL SCAN
(31 rows)

Time: 10.039s total (execution 10.039s / network 0.000s)


root@:26257/tpcc> SHOW CLUSTER SETTING sql.distsql.temp_storage.workmem;
  sql.distsql.temp_storage.workmem
------------------------------------
  640 MiB
(1 row)

Time: 1ms total (execution 0ms / network 0ms)

root@:26257/tpcc> explain analyze (verbose) select * from order_line order by ol_d_id;
                                                                 info
---------------------------------------------------------------------------------------------------------------------------------------
  planning time: 51ms
  execution time: 3.5s
  distribution: full
  vectorized: true
  rows read from KV: 3,001,222 (219 MiB)
  cumulative time spent in KV: 2.5s
  maximum memory usage: 549 MiB
  network usage: 0 B (0 messages)

  • sort
  │ columns: (ol_o_id, ol_d_id, ol_w_id, ol_number, ol_i_id, ol_supply_w_id, ol_delivery_d, ol_quantity, ol_amount, ol_dist_info)
  │ ordering: +ol_d_id
  │ nodes: n1
  │ actual row count: 3,001,222
  │ vectorized batch count: 2,931
  │ estimated row count: 3,001,222
  │ order: +ol_d_id
  │
  └── • scan
        columns: (ol_o_id, ol_d_id, ol_w_id, ol_number, ol_i_id, ol_supply_w_id, ol_delivery_d, ol_quantity, ol_amount, ol_dist_info)
        nodes: n1
        actual row count: 3,001,222
        vectorized batch count: 2,931
        KV time: 2.5s
        KV contention time: 0µs
        KV rows read: 3,001,222
        KV bytes read: 219 MiB
        estimated row count: 3,001,222 (100% of the table; stats collected 15 hours ago)
        table: order_line@primary
        spans: FULL SCAN
(30 rows)

Time: 3.510s total (execution 3.510s / network 0.000s)
```

**Comment by DrewKimball** [comment]
Comparison vs master for a simple unordered distinct with one decimal column, both with default operator memory limit:
```
MASTER:

root@:26257/tpcc> explain analyze (verbose) SELECT DISTINCT ON (ol_amount) * FROM order_line;
                                                                 info
---------------------------------------------------------------------------------------------------------------------------------------
  planning time: 182µs
  execution time: 5.3s
  distribution: full
  vectorized: true
  rows read from KV: 3,001,222 (219 MiB)
  cumulative time spent in KV: 2.8s
  maximum memory usage: 48 MiB
  network usage: 0 B (0 messages)

  • distinct
  │ columns: (ol_o_id, ol_d_id, ol_w_id, ol_number, ol_i_id, ol_supply_w_id, ol_delivery_d, ol_quantity, ol_amount, ol_dist_info)
  │ nodes: n1
  │ actual row count: 592,778
  │ vectorized batch count: 980
  │ estimated row count: 588,894
  │ distinct on: ol_amount
  │
  └── • scan
        columns: (ol_o_id, ol_d_id, ol_w_id, ol_number, ol_i_id, ol_supply_w_id, ol_delivery_d, ol_quantity, ol_amount, ol_dist_info)
        nodes: n1
        actual row count: 3,001,222
        vectorized batch count: 2,931
        KV time: 2.8s
        KV contention time: 0µs
        KV rows read: 3,001,222
        KV bytes read: 219 MiB
        estimated row count: 3,001,222 (100% of the table; stats collected 1 day ago)
        table: order_line@primary
        spans: FULL SCAN
(29 rows)

Time: 5.351s total (execution 5.350s / network 0.000s)

BRANCH:

root@:26257/tpcc> explain analyze (verbose) SELECT DISTINCT ON (ol_amount) * FROM order_line;
                                                                 info
---------------------------------------------------------------------------------------------------------------------------------------
  planning time: 284µs
  execution time: 3.5s
  distribution: full
  vectorized: true
  rows read from KV: 3,001,222 (219 MiB)
  cumulative time spent in KV: 2.6s
  maximum memory usage: 48 MiB
  network usage: 0 B (0 messages)

  • distinct
  │ columns: (ol_o_id, ol_d_id, ol_w_id, ol_number, ol_i_id, ol_supply_w_id, ol_delivery_d, ol_quantity, ol_amount, ol_dist_info)
  │ nodes: n1
  │ actual row count: 592,778
  │ vectorized batch count: 980
  │ estimated row count: 588,894
  │ distinct on: ol_amount
  │
  └── • scan
        columns: (ol_o_id, ol_d_id, ol_w_id, ol_number, ol_i_id, ol_supply_w_id, ol_delivery_d, ol_quantity, ol_amount, ol_dist_info)
        nodes: n1
        actual row count: 3,001,222
        vectorized batch count: 2,931
        KV time: 2.6s
        KV contention time: 0µs
        KV rows read: 3,001,222
        KV bytes read: 219 MiB
        estimated row count: 3,001,222 (100% of the table; stats collected 1 day ago)
        table: order_line@primary
        spans: FULL SCAN
(29 rows)

Time: 3.537s total (execution 3.536s / network 0.000s)
```

**Review by michae2 — CHANGES_REQUESTED** [review]
Nice job getting to the bottom of this! :smile:

It looks like `DatumVec` also has this same problem. (I bet we could reproduce it with a `GEOMETRY` or `ARRAY` column.) I propose we fix that in the same way. (Maybe you'd have to add `CheapSize` and `ExpensiveSize` methods to `DatumVec`?)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-:-McvMGg98g5ps4gBTdfV:b-fl8nuj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @yuzefovich)

___
*[pkg/sql/colmem/allocator.go, line 312 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-McvPqfg8T9S2ycWiPAf:-McvPqfg8T9S2ycWiPAg:b-opxdt9) ([raw file](https://github.com/cockroachdb/cockroach/blob/767020402be7afa940b94c62fee0f8ae9bb2b47d/pkg/sql/colmem/allocator.go#L312)):*
> ```Go
> // for appending to Decimal column types since the expensive portion of the cost
> // calculation only needs to be performed for the newly appended elements.
> func (a *Allocator) PerformAppend(destVecs []coldata.Vec, prevLength int, operation func()) {
> ```

Instead of passing `prevLength` in, can we get it from `destVecs` before calling `operation()`?

**Comment by DrewKimball** [comment]
> It looks like `DatumVec` also has this same problem. (I bet we could reproduce it with a `GEOMETRY` or `ARRAY` column.) I propose we fix that in the same way. (Maybe you'd have to add `CheapSize` and `ExpensiveSize` methods to `DatumVec`?)

Done. Looks like you were right - this query gets about 3 times faster: 
```
SELECT x FROM (SELECT ST_MakePoint(a::float, b::float) FROM (SELECT t % 3 AS a, t % 7 AS b FROM generate_series(1, 1000000) g(t))) AS f(x) ORDER BY x;
```

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66807)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[pkg/sql/colmem/allocator.go, line 312 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-McvPqfg8T9S2ycWiPAf:-Mcvfula7Hm0_yfcrcE4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/767020402be7afa940b94c62fee0f8ae9bb2b47d/pkg/sql/colmem/allocator.go#L312)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Instead of passing `prevLength` in, can we get it from `destVecs` before calling `operation()`?
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm: great find!

> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-:-MczxKzi4hZCfKw2MmzE:b-3952fu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, and @yuzefovich)

___
*[pkg/col/coldataext/datum_vec.go, line 188 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-Mczwkvc-OtBQRK1qlpx:-Mczwkvc-OtBQRK1qlpy:b-odod92) ([raw file](https://github.com/cockroachdb/cockroach/blob/be1d8ea0bda363dbd60d24106b250d3fc713a96c/pkg/col/coldataext/datum_vec.go#L188)):*
> ```Go
> 
> // CheapSize returns the portion of the vector's memory footprint that is
> // cheap to calculate in bytes.
> ```

nit: would help to give an idea of what "cheap" means here (and "expensive" below)

**Review by michae2 — APPROVED** [review]
It might be too late, but I had one idea to make this a little easier to understand. Instead of dividing the size methods into "cheap" and "expensive" variants, you could have a single size method that starts at an offset. When the offset >= len(), the calculation would naturally be cheap and when the offset < len() the calculation would naturally be expensive. So you could call this size method with `prevLength` both before and after `operation()` and the first time it would be cheap, second time expensive. And that size method might be easier to think about than these two new ones.

But that is just a suggestion, and this already :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-:-McztVKzCXNGMpBjUyIb:bq4uxw1)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball and @yuzefovich)

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66807)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[pkg/col/coldataext/datum_vec.go, line 188 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-Mczwkvc-OtBQRK1qlpx:-Md0-ZFu-VIeUJBw3O9q:b-etad7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/be1d8ea0bda363dbd60d24106b250d3fc713a96c/pkg/col/coldataext/datum_vec.go#L188)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: would help to give an idea of what "cheap" means here (and "expensive" below)
</blockquote></details>

As per Michael's suggestion, I'm going to change the interface to just have a single `Cost` function with a `startIdx` parameter. But, I'll clarify when it is cheap vs expensive. Done.

**Review by rytaft — APPROVED** [review]
Nice cleanup (and good suggestion, @michae2)!

Is there some way to test this stuff? Not sure how we currently test memory accounting, but seems like it would be good to add a test if one doesn't already exist to sanity check that we're accounting for the same memory that we were before.

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-:-Md2EZSB9mz_66_jj8Yl:b-2qrmc3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball and @yuzefovich)

___
*[pkg/col/coldataext/datum_vec.go, line 199 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-Md2CE9UBAWcQ1WfGalN:-Md2CE9UBAWcQ1WfGalO:b-twwufy) ([raw file](https://github.com/cockroachdb/cockroach/blob/0da263485104cbb05f83d2434682cc2a4e62bc15/pkg/col/coldataext/datum_vec.go#L199)):*
> ```Go
> 		size += (count - uintptr(dv.Len())) * datumSize
> 	} else {
> 		size += datumSize * count
> ```

should you subtract `startIdx` from `count` here?
___
*[pkg/sql/colmem/allocator.go, line 320 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-Md2Cbg8D3o52eAyw8gv:-Md2Cbg8D3o52eAyw8gw:b-6odx8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/0da263485104cbb05f83d2434682cc2a4e62bc15/pkg/sql/colmem/allocator.go#L320)):*
> ```Go
> 			// Don't add the size of the existing decimals to the 'before' cost, since
> 			// they are guaranteed not to be modified by an append operation.
> 			before += int64(sizeOfDecimals(dest.Decimal(), dest.Length()))
> ```

nit: why not just use `=` instead of `+=`? I think that would be clearer.
nit: you could move assignment of `prevLength` to before this line and reuse `prevLength` here
___
*[pkg/sql/colmem/allocator.go, line 323 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-Md2D5Qg7VzzTJ1HN9oT:-Md2D5Qg7VzzTJ1HN9oU:b-wrxvkg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0da263485104cbb05f83d2434682cc2a4e62bc15/pkg/sql/colmem/allocator.go#L323)):*
> ```Go
> 			prevLength = dest.Length()
> 		case typeconv.DatumVecCanonicalTypeFamily:
> 			before += int64(dest.Datum().Size(dest.Length()))
> ```

nit: ditto regarding using `prevLength`

**Review by michae2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66807)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball, @rytaft, and @yuzefovich)

___
*[pkg/col/coldataext/datum_vec.go, line 199 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-Md2CE9UBAWcQ1WfGalN:-Md3-HFk21xjSt72R5uf:bpmxq70) ([raw file](https://github.com/cockroachdb/cockroach/blob/0da263485104cbb05f83d2434682cc2a4e62bc15/pkg/col/coldataext/datum_vec.go#L199)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

should you subtract `startIdx` from `count` here?
</blockquote></details>

Oh, yes, and all the usages of count above this as well. We should try to make this correct even if `startIdx > dv.Len()`.
___
*[pkg/sql/colmem/allocator.go, line 320 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-Md2Cbg8D3o52eAyw8gv:-Md2zOp53NiphbqezRTT:b-raz9sg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0da263485104cbb05f83d2434682cc2a4e62bc15/pkg/sql/colmem/allocator.go#L320)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: why not just use `=` instead of `+=`? I think that would be clearer.
nit: you could move assignment of `prevLength` to before this line and reuse `prevLength` here
</blockquote></details>

`+=` is needed in case there are multiple `destVecs`
___
*[pkg/sql/colmem/allocator.go, line 391 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-Md3R_JsD252oP0pZmUF:-Md3R_JsD252oP0pZmUG:blmkzht) ([raw file](https://github.com/cockroachdb/cockroach/blob/0da263485104cbb05f83d2434682cc2a4e62bc15/pkg/sql/colmem/allocator.go#L391)):*
> ```Go
> // when startIdx = 0.
> func sizeOfDecimals(decimals coldata.Decimals, startIdx int) uintptr {
> 	size := uintptr(cap(decimals)-len(decimals)) * sizeOfDecimal
> ```

If `startIdx > len(decimals)` this won't be correct.

**Review by DrewKimball — COMMENTED** [review]
It's a bit difficult to test without the tests being flaky. That being said, I'll add a test that uses both `PerformOperation` and `PerformAppend` and tests that the amount of memory reserved by the allocator is equal for both (within some margin to make sure the test isn't flaky).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-:-Md4DiEuERLfGsTbA2IM:b-9zp4w6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @michae2, @rytaft, and @yuzefovich)

___
*[pkg/col/coldataext/datum_vec.go, line 199 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-Md2CE9UBAWcQ1WfGalN:-Md4GZvZ6_EKan68kE9t:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0da263485104cbb05f83d2434682cc2a4e62bc15/pkg/col/coldataext/datum_vec.go#L199)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Oh, yes, and all the usages of count above this as well. We should try to make this correct even if `startIdx > dv.Len()`.
</blockquote></details>

Done.
___
*[pkg/sql/colmem/allocator.go, line 320 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-Md2Cbg8D3o52eAyw8gv:-Md3nYdyExiAC2o8pz37:b-b57deu) ([raw file](https://github.com/cockroachdb/cockroach/blob/0da263485104cbb05f83d2434682cc2a4e62bc15/pkg/sql/colmem/allocator.go#L320)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

`+=` is needed in case there are multiple `destVecs`
</blockquote></details>

Done (for the second one)
___
*[pkg/sql/colmem/allocator.go, line 323 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-Md2D5Qg7VzzTJ1HN9oT:-Md3nZwA90j_gRYm2j2w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0da263485104cbb05f83d2434682cc2a4e62bc15/pkg/sql/colmem/allocator.go#L323)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: ditto regarding using `prevLength`
</blockquote></details>

Done.
___
*[pkg/sql/colmem/allocator.go, line 391 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-Md3R_JsD252oP0pZmUF:-Md42D1A1UdVO3NTFJ_n:bkgajv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0da263485104cbb05f83d2434682cc2a4e62bc15/pkg/sql/colmem/allocator.go#L391)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

If `startIdx > len(decimals)` this won't be correct.
</blockquote></details>

My original intent was for `startIdx` to indicate the start of memory accounting only for the memory referenced by the individual decimal objects, since that takes linear time to compute. But using `startIdx` for the portion of the memory that is constant to calculate as well is definitely more intuitive, so I'll change it.

Done.

**Review by michae2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66807)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball, @rytaft, and @yuzefovich)

___
*[pkg/sql/colmem/allocator_test.go, line 232 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-Md4MjDZBT3v2b6ZztJc:-Md4MjDZBT3v2b6ZztJd:bqrdxz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/151525cf77fd872823d3e12fe4ad25a1e6b3a0a5/pkg/sql/colmem/allocator_test.go#L232)):*
> ```Go
> 
> 		beforePerformAppend := afterPerformOperation
> 		testAllocator.PerformOperation(batch2.ColVecs(), func() {
> ```

Should this be `PerformAppend`?

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66807)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @michae2, @rytaft, and @yuzefovich)

___
*[pkg/sql/colmem/allocator_test.go, line 232 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-Md4MjDZBT3v2b6ZztJc:-Md4RWEzEB3QNUPEc84C:b-mnk8nd) ([raw file](https://github.com/cockroachdb/cockroach/blob/151525cf77fd872823d3e12fe4ad25a1e6b3a0a5/pkg/sql/colmem/allocator_test.go#L232)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Should this be `PerformAppend`?
</blockquote></details>

Ah, that would certainly explain why the results were so similar...

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66807)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @michae2, @rytaft, and @yuzefovich)

___
*[pkg/sql/colmem/allocator_test.go, line 232 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-Md4MjDZBT3v2b6ZztJc:-Md4cgPq4svKtP7B-fsH:b-88asuq) ([raw file](https://github.com/cockroachdb/cockroach/blob/151525cf77fd872823d3e12fe4ad25a1e6b3a0a5/pkg/sql/colmem/allocator_test.go#L232)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Ah, that would certainly explain why the results were so similar...
</blockquote></details>

All done. Once the test was fixed, it actually managed to catch a bug in `datumVec.Cost` that slightly under accounted when `startIdx` was greater than or equal to the length of the vector.

**Review by michae2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66807)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball, @rytaft, and @yuzefovich)

___
*[pkg/col/coldataext/datum_vec.go, line 203 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-Md4faSwERuFJ7egNzNM:-Md4faSwERuFJ7egNzNN:b-1qvsa3) ([raw file](https://github.com/cockroachdb/cockroach/blob/247407709057628f7b656ea4a425bf3f6c986eae/pkg/col/coldataext/datum_vec.go#L203)):*
> ```Go
> 			}
> 		}
> 		size += uintptr(dv.Cap()-dv.Len()) * datumSize
> ```

Hmm... *scratches head profusely*... then is there one more bug here? If `startIdx > dv.Len()` then I think we would want to add `uintptr(dv.Cap()-startIdx) * datumSize` instead, right?
___
*[pkg/sql/colmem/allocator_test.go, line 232 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-Md4MjDZBT3v2b6ZztJc:-Md4g-or-_LSrHtfOY5I:bdibb6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/151525cf77fd872823d3e12fe4ad25a1e6b3a0a5/pkg/sql/colmem/allocator_test.go#L232)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

All done. Once the test was fixed, it actually managed to catch a bug in `datumVec.Cost` that slightly under accounted when `startIdx` was greater than or equal to the length of the vector.
</blockquote></details>

Nice! :smile:

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66807)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @michae2, @rytaft, and @yuzefovich)

___
*[pkg/col/coldataext/datum_vec.go, line 203 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-Md4faSwERuFJ7egNzNM:-Md4ghakEla3r0jRh8of:bcistuc) ([raw file](https://github.com/cockroachdb/cockroach/blob/247407709057628f7b656ea4a425bf3f6c986eae/pkg/col/coldataext/datum_vec.go#L203)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Hmm... *scratches head profusely*... then is there one more bug here? If `startIdx > dv.Len()` then I think we would want to add `uintptr(dv.Cap()-startIdx) * datumSize` instead, right?
</blockquote></details>

Ack, forgot that that case is no longer filtered.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66807)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @michae2, @rytaft, and @yuzefovich)

___
*[pkg/col/coldataext/datum_vec.go, line 203 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-Md4faSwERuFJ7egNzNM:-Md4iOie1iDH9osp0qE4:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/247407709057628f7b656ea4a425bf3f6c986eae/pkg/col/coldataext/datum_vec.go#L203)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Ack, forgot that that case is no longer filtered.
</blockquote></details>

Fixed.

**Review by michae2 — APPROVED** [review]
:lgtm:

Thanks! This is a really great catch!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-:-MdIhUNT6X7psPhwMBhW:bbxi2de)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft and @yuzefovich)

**Comment by DrewKimball** [comment]
TFTRs!

**Review by rytaft — APPROVED** [review]
:lgtm: Nice test!

> Reviewed 2 of 4 files at r4, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-:-MdJVI7X-GapOFUM5oW4:bcl2h3v)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colmem/allocator.go, line 320 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66807#-Md2Cbg8D3o52eAyw8gv:-MdJUaG7AbehwNasaHNt:bw318lc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0da263485104cbb05f83d2434682cc2a4e62bc15/pkg/sql/colmem/allocator.go#L320)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Done (for the second one)
</blockquote></details>

oops thanks!

**Pull request merged**
