### PR TITLE
backupccl: add full cluster restore

### PR DESCRIPTION
**Pull request by pbardea**
This commit adds the ability to entirely restore a full cluster backup.
This includes replacing the contents of some system tables to match the
data in the backup. Full cluster restore can be used using the `RESTORE
FROM ...` syntax and is expected to be run on a new cluster with no user
data.

Release note (enterprise change): Add full cluster restore feature which
restores all the information contained in a full cluster backup. This
includes all of the user data as well as relevant data from system
tables. It is expected to be run on a new cluster with no user data.

### CODE REVIEW

**Review by dt — APPROVED** [review]
> Reviewed 8 of 10 files at r1, 6 of 8 files at r3, 5 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43828)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/ccl/backupccl/backup.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43828#-Ly67DdO0NNiJgqHoDQW:-Ly67DdPBAHzGe8Pj_z3:bjffgxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3a4c1fbdbd7c9bac427d3f3c999d69a0b0c873e/pkg/ccl/backupccl/backup.go#L97)):*
> ```Go
> 
> // Databases which are present in the cluster by default.
> var defaultUserDBs = map[string]struct{}{sessiondata.DefaultDatabaseName: {}, sessiondata.PgDatabaseName: {}}
> ```

this seems like it belongs in restore.go ?
___
*[pkg/ccl/backupccl/restore.go, line 407 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43828#-LyBAp3T7ZBoqtMqcIb5:-LyBAp3T7ZBoqtMqcIb6:b-a8r0q9) ([raw file](https://github.com/cockroachdb/cockroach/blob/de82149294886a92a8179cae2fd09b1276d4b9db/pkg/ccl/backupccl/restore.go#L407)):*
> ```Go
> 		numberOfIncrements := maxDescIDInBackup - uint32(maxDefaultID)
> 		for i := uint32(0); i <= numberOfIncrements; i++ {
> 			_, err = sql.GenerateUniqueDescID(ctx, p.ExecCfg().DB)
> ```

Huh, why the loop? why can't we just _set_ it to maxDescIDInBackup?
___
*[pkg/ccl/backupccl/restore.go, line 431 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43828#-LyBBMjn6LSlgbtbyD7v:-LyBBMjn6LSlgbtbyD7w:bftuq7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/de82149294886a92a8179cae2fd09b1276d4b9db/pkg/ccl/backupccl/restore.go#L431)):*
> ```Go
> 			}
> 			if found && descriptorCoverage == tree.AllDescriptors {
> 				if foundID > 52 {
> ```

is there a name for this constant we could use?
___
*[pkg/ccl/backupccl/restore.go, line 1707 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43828#-LzcxRTK9yv2Z8BP2Yyf:-LzcxRTK9yv2Z8BP2Yyg:b6qyzay) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c5831895ead0ee29b0cf313dc174305a5e93c03/pkg/ccl/backupccl/restore.go#L1707)):*
> ```Go
> 		if t := desc.Table(hlc.Timestamp{}); t != nil {
> 			// Don't count the default tables or system tables.
> 			if t.ParentID != sqlbase.SystemDB.ID {
> ```

i'd love to move this logic into a `IsDefaultCreatedTable` or something method in sqlbase so that new tables get included correctly.

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43828)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/ccl/backupccl/backup.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43828#-Ly67DdO0NNiJgqHoDQW:-M-G9R6R9I7x5fw_1jJP:bo67zlc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3a4c1fbdbd7c9bac427d3f3c999d69a0b0c873e/pkg/ccl/backupccl/backup.go#L97)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

this seems like it belongs in restore.go ?
</blockquote></details>

Moved it over to `sql/descriptor.go` so that it can be used to identify user created tables in general.
___
*[pkg/ccl/backupccl/restore.go, line 407 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43828#-LyBAp3T7ZBoqtMqcIb5:-M-G8KVuATorYQJPTvx6:b-4cr9ae) ([raw file](https://github.com/cockroachdb/cockroach/blob/de82149294886a92a8179cae2fd09b1276d4b9db/pkg/ccl/backupccl/restore.go#L407)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Huh, why the loop? why can't we just _set_ it to maxDescIDInBackup?
</blockquote></details>

It looks like the key it writes to only expects increments. Specifically when this key is incremented the comments say: "If the key exists but was set using Put or CPut an error will be returned."
___
*[pkg/ccl/backupccl/restore.go, line 431 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43828#-LyBBMjn6LSlgbtbyD7v:-M-G960m3izez3fmNrYB:bm8i46b) ([raw file](https://github.com/cockroachdb/cockroach/blob/de82149294886a92a8179cae2fd09b1276d4b9db/pkg/ccl/backupccl/restore.go#L431)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

is there a name for this constant we could use?
</blockquote></details>

Yep, moved this to the `sql` package along with helpers to identify user created tables.
___
*[pkg/ccl/backupccl/restore.go, line 1707 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43828#-LzcxRTK9yv2Z8BP2Yyf:-M-G9BqO-Cf5xIx4pSF9:b-1uc2bm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c5831895ead0ee29b0cf313dc174305a5e93c03/pkg/ccl/backupccl/restore.go#L1707)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

i'd love to move this logic into a `IsDefaultCreatedTable` or something method in sqlbase so that new tables get included correctly.
</blockquote></details>

Moved this over to `sql/descriptor.go` along with the list of expected user tables.

**Review by dt — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43828)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/ccl/backupccl/restore.go, line 407 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43828#-LyBAp3T7ZBoqtMqcIb5:-M-Grp6e5ocLQVj5fGL1:b-nwht8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/de82149294886a92a8179cae2fd09b1276d4b9db/pkg/ccl/backupccl/restore.go#L407)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

It looks like the key it writes to only expects increments. Specifically when this key is incremented the comments say: "If the key exists but was set using Put or CPut an error will be returned."
</blockquote></details>

huh, interesting. let's put a TODO and follow up with KV to see if we can change this later.

**Pull request merged**
