### PR TITLE
roachtest/tests/cdc: effectively disable exponential backoff in jobs

### LINKED ISSUE #68963: roachtest: cdc/crdb-chaos failed
roachtest.cdc/crdb-chaos [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3303319&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3303319&tab=artifacts#/cdc/crdb-chaos) on master @ [ee3efd6b1e24a3e1676778f5028fa0a35266f683](https://github.com/cockroachdb/cockroach/commits/ee3efd6b1e24a3e1676778f5028fa0a35266f683):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/cdc/crdb-chaos/run_1
	cdc.go:1620,cdc.go:273,cdc.go:722,test_runner.go:777: max latency was more than allowed: 11m43.870293266s vs 5m0s
```
<details><summary>Reproduce</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/roachtest)

See: [CI job to stress roachtests](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestStress)

<p>For the CI stress job, click the ellipsis (...) next to the Run button and fill in:
* Changes / Build branch: master
* Parameters / `env.TESTS`: `^cdc/crdb-chaos$`
* Parameters / `env.COUNT`: &lt;number of runs&gt;
</p>
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #68047 roachtest: cdc/crdb-chaos failed [C-test-failure O-roachtest O-robot T-cdc branch-release-21.1]
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/crdb-chaos.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by ajwerner**
Fixes #68963.

Release note: None

### CODE REVIEW

**Review by stevendanna — APPROVED** [review]

**Review by sajjadrizvi — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69034#-:-MhJMrw49TbEglNBRLbh:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by sajjadrizvi — COMMENTED** [review]
Sorry for commenting after approving. It just occurred to me that if we want to disable backoff, why not set both initial delay and max delay to longer than test timeout, e.g., a minute?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69034#-:-MhJNIBo2Nlt_PQ7G1Uz:b-hqyqp)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by ajwerner** [comment]
> It just occurred to me that if we want to disable backoff, why not set both initial delay and max delay to longer than test timeout, e.g., a minute?

I don't understand. Can you explain how this would help fix this test which is broken because the job is not being resumed in a timely manner in the face of chaos?

**Review by sajjadrizvi — COMMENTED** [review]
The title says "... effectively disable exponential backoff", so I thought we want to disable retries completely.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69034#-:-MhJgty1-iy6Y7dP6rCf:b-bcw3jo)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by ajwerner — COMMENTED** [review]
>The title says "... effectively disable exponential backoff", so I thought we want to disable retries completely.

It does not say disable retries, it says disable backoff. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69034#-:-MhK6l9E2qs1oaD0zvij:b-4m8llj)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
