### PR TITLE
bulk: split-and-scatter when SSTBatcher 'fills' range

### PR DESCRIPTION
**Pull request by dt**
By keeping track of how many bytes have added to range we just added to, we can decide to split and scatter a new range when we decide we have 'filled' the one to which we've been adding.
When we do so, we split at the end of what we just added and scatter the next range, i.e. not what we just imported (sicne scattering a full range is expensive) but rather what we can assume we're about to ingest into -- since given that we just ingested multiple SSTs without hitting a split, it seems likely we will keep doing so.

With this change backup2tb's 620GB IMPORT of the bank table shows even growth in ranges across nodes and even leaseholders-per-stores, and runs in 59m8s or 179.48 MiB/s. That appears to be a large improvement over the most recent run on master where it took 1h49m24s / 97.02 MiB/s (some master runs have also been crashing when a node ran out of space).

Release note: none.

### CODE REVIEW

**Review by pbardea — APPROVED** [review]
LGTM, great to see how much this helped! Have you run it on the 4-node cluster to see if the distribution issues were addressed?

Left a few minor comments.

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40243#-:-LnJXaxe2AZipVSGzIhD:b-4ifnqa)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/storage/bulk/buffering_adder.go, line 96 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40243#-LnJOQwP6DATPjVLT4tA:-LnJOQwP6DATPjVLT4tB:btp04ir) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0737a55da3983ef1d2df9dafc970da99c3090a2/pkg/storage/bulk/buffering_adder.go#L96)):*
> ```Go
> 			skipDuplicates:    opts.SkipDuplicates,
> 			disallowShadowing: opts.DisallowShadowing,
> 			splitAfter:        int64(opts.SSTSize * 3),
> ```

It may be useful to either assigning `3` to a named constant, or adding a comment about why 3 was chosen. Maybe something like: `// After seeing 3 flushes 
___
*[pkg/storage/bulk/sst_batcher.go, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40243#-LnJIwHu-rEXpcIkF8oO:-LnJIwHv8b4yT66-cu5b:buf2c0n) ([raw file](https://github.com/cockroachdb/cockroach/blob/11be364ec84981ee10aa2eddc1f6a0a990caa8e9/pkg/storage/bulk/sst_batcher.go#L71)):*
> ```Go
> 	}
> 
> 	// Thee rest of the fields are per-batch and are reset via Reset() before each
> ```

Typo: `The` instead of `Thee`
___
*[pkg/storage/bulk/sst_batcher.go, line 169 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40243#-LnJJU4653t8MQDIB8Ie:-LnJJU4653t8MQDIB8If:bqo2gre) ([raw file](https://github.com/cockroachdb/cockroach/blob/11be364ec84981ee10aa2eddc1f6a0a990caa8e9/pkg/storage/bulk/sst_batcher.go#L169)):*
> ```Go
> 
> const (
> 	manualFlush = iota
> ```

Nit: setting this to `iota + 1` would make it so that instances where it is accidentally uninitialize don't default to a legal value.
___
*[pkg/storage/bulk/sst_batcher.go, line 285 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40243#-LnJX8yl6HczdftGs77v:-LnJX8yl6HczdftGs77w:b-7cr2di) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0737a55da3983ef1d2df9dafc970da99c3090a2/pkg/storage/bulk/sst_batcher.go#L285)):*
> ```Go
> 		if b.splitAfter > 0 && b.flushedToCurrentRange > b.splitAfter {
> 			log.VEventf(ctx, 2, "%s added since last split, splitting/scattering for next range at %v", sz(b.flushedToCurrentRange), end)
> 			if err := b.db.SplitAndScatter(ctx, end, hour); err != nil {
> ```

If we're always going to swallow this error (and I assume we will since it doesn't affect correctness and seems scatter is unreliable), it may make sense to bring it into `SplitAndScatter` and have it return nothing.

**Review by pbardea — COMMENTED** [review]
Also minor comment, there's a typo in the commit message: /s/sicne/since

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40243#-:-LnJXtO7DReXsDZCTQtx:byumwop)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40243)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/storage/bulk/buffering_adder.go, line 96 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40243#-LnJOQwP6DATPjVLT4tA:-LnOLm7r507gCW4nPTBR:bj48yit) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0737a55da3983ef1d2df9dafc970da99c3090a2/pkg/storage/bulk/buffering_adder.go#L96)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

It may be useful to either assigning `3` to a named constant, or adding a comment about why 3 was chosen. Maybe something like: `// After seeing 3 flushes 
</blockquote></details>

Whoops, just noticed that something funky went on at the end of this comment. The rest is supposed to say something like: `// After seeing 3 flushes of 16M, we know that the current range will add to be 64M so a size split will occur next`. or something along those lines.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40243)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

___
*[pkg/storage/bulk/buffering_adder.go, line 96 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40243#-LnJOQwP6DATPjVLT4tA:-LnOM83W9FtJRgQPr1IO:b-pwial2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0737a55da3983ef1d2df9dafc970da99c3090a2/pkg/storage/bulk/buffering_adder.go#L96)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

It may be useful to either assigning `3` to a named constant, or adding a comment about why 3 was chosen. Maybe something like: `// After seeing 3 flushes 
</blockquote></details>

Done.

Moved it to options entirely.
___
*[pkg/storage/bulk/sst_batcher.go, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40243#-LnJIwHu-rEXpcIkF8oO:-LnOM7Jq4vvjWnGaCTRM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/11be364ec84981ee10aa2eddc1f6a0a990caa8e9/pkg/storage/bulk/sst_batcher.go#L71)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Typo: `The` instead of `Thee`
</blockquote></details>

Done.
___
*[pkg/storage/bulk/sst_batcher.go, line 169 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40243#-LnJJU4653t8MQDIB8Ie:-LnOKI_cCbvV-Oll6vYu:brh5piu) ([raw file](https://github.com/cockroachdb/cockroach/blob/11be364ec84981ee10aa2eddc1f6a0a990caa8e9/pkg/storage/bulk/sst_batcher.go#L169)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Nit: setting this to `iota + 1` would make it so that instances where it is accidentally uninitialize don't default to a legal value.
</blockquote></details>

we don't actually `switch` on it anywhere since we just test for specific values in certain places so I don't think we'd notice the invalid default anyway. I think I'm fine with it as-is since this is a private/internal api that just between flushIfNeeded and doFlush as opposed to a public API where we'd want to consider potential misuse more.
___
*[pkg/storage/bulk/sst_batcher.go, line 285 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40243#-LnJX8yl6HczdftGs77v:-LnOLnLWAjQB2Ci2fFPf:b-q1yild) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0737a55da3983ef1d2df9dafc970da99c3090a2/pkg/storage/bulk/sst_batcher.go#L285)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

If we're always going to swallow this error (and I assume we will since it doesn't affect correctness and seems scatter is unreliable), it may make sense to bring it into `SplitAndScatter` and have it return nothing.
</blockquote></details>

Hm, ideally I wouldn't always swallow it, so even if we do for now, I'd rather that still be up to the caller to decide than encourage it at the API level.

**Review by pbardea — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40243)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
