### PR TITLE
vendor: bump Pebble to b38417b0835b

### PR DESCRIPTION
**Pull request by itsbilal**
b38417b0 db: wait for table cache releasing goroutines to exit
c751cef4 *: optimize external iters for single-file, no-rangekey cases
e729e744 metamorphic: test Clone with Options

Release note: None.

Release justification: bug fixes and low-risk updates to new functionality

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
looks like there might be a issue. test failures across the board

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86961#-:-NAQsoDX2oA1jGD6xggD:b-i40qut)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal)

**Comment by itsbilal** [comment]
Looks like it's a bug that crept in with https://github.com/cockroachdb/pebble/pull/1929 :

```
generated_test.go:94: Leaked goroutine: goroutine 9122 [chan receive]:
        github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop.func1({0x5679b00, 0xc003d10030})
        	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/table_cache.go:324 +0x9f
        runtime/pprof.Do({0x5679a90?, 0xc000074128?}, {{0xc0000d2ca0?, 0xfe7b80?, 0xc00197a750?}}, 0xc002cb0fa8)
        	/usr/local/go/src/runtime/pprof/runtime.go:40 +0xa3
        github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop(0xc002cb0f70?)
        	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/table_cache.go:322 +0x58
        created by github.com/cockroachdb/pebble.(*tableCacheShard).init
        	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/table_cache.go:314 +0xe5
```

**Comment by itsbilal** [comment]
Actually, I take that back - it's likely a bug that crept in due to https://github.com/cockroachdb/pebble/pull/1925

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10584d058]

goroutine 2072 [running]:
github.com/cockroachdb/pebble/sstable.(*blockIter).readEntry(0x1?)
        github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/block.go:359 +0x28
github.com/cockroachdb/pebble/sstable.(*blockIter).SeekGE(0x140034f8378, {0x14000dfb380, 0x10, 0x10}, 0x20?)
        github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/block.go:626 +0x298
github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).seekGEHelper(0x140034f8300, {0x14000dfb380, 0x10, 0x10}, 0x10?, 0x0)
        github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go:709 +0x27c
github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).SeekGE(0x14000dfb380?, {0x14000dfb380?, 0x10?, 0x1400098d002?}, 0x3?)
        github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go:628 +0xb4
github.com/cockroachdb/pebble.(*Iterator).SeekGEWithLimit(0x14002be8000, {0x14000dfb380, 0x10, 0x10}, {0x0, 0x0, 0x0})
        github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go:1063 +0x408
github.com/cockroachdb/pebble.(*Iterator).SeekGE(...)
        github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go:982
github.com/cockroachdb/cockroach/pkg/storage.(*pebbleIterator).SeekGE(0x14002f797c0, {{0x14000dfab88, 0x2, 0x8}, {0x7fffffffffffffff, 0x7fffffff, 0x0}})
        github.com/cockroachdb/cockroach/pkg/storage/pebble_iterator.go:320 +0xf4
github.com/cockroachdb/cockroach/pkg/storage.(*ReadAsOfIterator).SeekGE(0x14005029ef0, {{0x14000dfab88, 0x2, 0x8}, {0x0, 0x0, 0x0}})
        github.com/cockroachdb/cockroach/pkg/storage/read_as_of_iterator.go:56 +0x9c
github.com/cockroachdb/cockroach/pkg/ccl/backupccl.(*restoreDataProcessor).processRestoreSpanEntry(0x14003870a00, {0x10a12bcf8, 0x140032dc080}, 0x140011557a0, {{{{0x14000dfab88, 0x2, 0x8}, {0x14000dfab90, 0x2, 0x8}}, ...}, ...})
        github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_data_processor.go:451 +0x3f4
github.com/cockroachdb/cockroach/pkg/ccl/backupccl.(*restoreDataProcessor).runRestoreWorkers.func1.1(0x14000c01410?, 0x14003870a00, {0x10a12bcf8, 0x140032dc080}, 0x1?)
        github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_data_processor.go:370 +0xb4
github.com/cockroachdb/cockroach/pkg/ccl/backupccl.(*restoreDataProcessor).runRestoreWorkers.func1({0x10a12bcf8, 0x140032dc080}, 0x0?)
        github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_data_processor.go:382 +0xac
github.com/cockroachdb/cockroach/pkg/util/ctxgroup.GroupWorkers.func1({0x10a12bcf8?, 0x140032dc080?})
        github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:178 +0x34
github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx.func1()
        github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:169 +0x30
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:74 +0x60
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:71 +0xa8
```

It's just that this panic triggers a second panic for the leaked iterator (as expected), and this set of changes just coincidentally happens to touch both things. I'll dive into this on Monday.

**Comment by itsbilal** [comment]
Bug fixed in https://github.com/cockroachdb/pebble/pull/1930 , this vendor bump is now superseded by #87039.

**Pull request closed without merging**
