### PR TITLE
cherrypick-1.1: sql: attempt txn auto-commit before flushing txnResults

### PR DESCRIPTION
**Pull request by nvb**
From #22721.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
Was this the fix that prevents double results?

**Comment by nvanbenschoten** [comment]
@knz yeah this is the fix.

**Comment by knz** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22740#-:-L5rzme-OYlcroygExil:bnfp4nl)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22740#-:-L5t-KCP-HozUFTbr7uc:bnfp4nl)*

**Pull request merged**
