### PR TITLE
sql: remove PHYSICAL scrub code

### PR DESCRIPTION
**Pull request by RaduBerinde**
The PHYSICAL scrub code is experimental and not considered production
ready. It complicates a lot of code paths involved in normal query
execution (it significantly overloads the semantics of TableReader and
of the Fetcher) and is getting in the way of some improvements in how
the fetchers work. In particular, we are trying to reduce the amount
of information passed to TableReader/Fetcher (which in the
non-scrubbing case should be a lot less than the full table
descriptor).

There are some proposals for a better design floating around, e.g.
provide a facility for returning KVs as results from DistSQL and have
some higher-level code run the scrub checks.

This change removes the code for the PHYSICAL scrub for now.

Release note (sql change): the experimental SCRUB PHYSICAL is no
longer implemented.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: Although I was never familiar with this SCRUB code or whether it provided value for testing correctness. Might be worth getting another set of eyes too.

> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74761#-:-MtFC5DP4eWDpjyspW1K:b-y08re5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @shermanCRL)

**Comment by yuzefovich** [comment]
I think I brought up the idea of removing this some time ago, and @jordanlewis was a bit opposed to it. At the time I didn't have any justification other than "it's not being used", but if this code is in the way of pushing more logic into the KV pods, then I'd guess the balance has shifted. It'd be good to get an ack from Jordan though.

**Comment by RaduBerinde** [comment]
I also brought it up here: https://cockroachlabs.slack.com/archives/CV581CE78/p1637081958010400

**Comment by jordanlewis** [comment]
I have no objection, I can't remember why I was opposed but now seems like a great time to do it.

**Comment by RaduBerinde** [comment]
TFTRs!

bors r+

**Pull request merged**
