### PR TITLE
[DO NOT MERGE] sql: pool allocate RowFetcher

### PR DESCRIPTION
**Pull request by petermattis**
RowFetcher is heavyweight, totalling 2432 bytes. Change scanNode.fetcher
to a pointer and use a sync.Pool to allocate. We don't sync.Pool
allocate the scanNode due to the embedded NoCopy struct which prevents
easy zeroing. This reduces the size of scanNode from 3384 bytes to 960
bytes. In a read-only workload, this change reduced total bytes
allocated by 9% and improved throughput by 4.5%.

### CODE REVIEW

**Comment by petermattis** [comment]
DNM because this change is specific to `scanNode` but there are other users of `RowFetcher`. Specifically,`distsqlrun.tableReader` and `sql.table{Upserter,Deleter}`.

**Comment by petermattis** [comment]
Heh, the testrace failures indicate this isn't even safe. Somehow we're holding on to data pointed to by the `RowFetcher` after `scanNode.Close`.

**Comment by petermattis** [comment]
Ah, `planNode.Close` is called when a statement is finished executing but before the results have been consumed. So this PR is not currently workable, but perhaps when `DatumAlloc` is extracted from `RowFetcher` it will be.

**Comment by RaduBerinde** [comment]
I thought most of the size of the `RowFetcher` came from `DatumAlloc.env.Buffer` which is 4k. How can the entire `RowFetcher` only 2432 bytes if it contains this structure?

Couldn't we make `env` or `env.Buffer` be allocated on-demand the first time we actually use it? (we only use it for collated strings and I believe always through the same function `NewDCollatedString`)

**Comment by RaduBerinde** [comment]
Ah, you already did that in a separate change, don't mind me.

**Pull request closed without merging**
