### PR TITLE
vendor: bump pebble to b9b70cfab7dac7e8427b11ee6b145fa5ab4db487

### PR DESCRIPTION
**Pull request by petermattis**
* db: manually managed memTable arena memory
* sstable: Unset external format version for self-made SSTs
* sstable: document "rocksdb.external_sst_file.version" property
* internal/cache: explicitly manage Cache lifetime
* internal/cache: add robinHoodMap
* docs: add doc describing manual memory management
* ci: add no-invariants test configuration
* internal/cache: optimize allocation of entry objects
* internal/cache: optimize allocation of manual Values
* internal/cache: move the bulk of allocations off the Go heap
* db: properly lock compaction picking and ingestion
* db: fix WAL replay in read-only mode
* ci: trim down build matrix
* ci: only build PRs targeted at master
* db: better ingestion heuristic
* db: move flushable and flushableEntry to their own file
* db: add flushableEntry which wraps a flushable
* internal/arenaskl: remove extValueThreshold detritus

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
@itsbilal I'm not sure if this is all of the test changes that are necessary. I'm sending this PR out to get CI involved in the hunt. And I haven't tried running with `COCKROACH_STORAGE_ENGINE=pebble` yet which will undoubtedly shake a few more things loose.

**Review by petermattis — COMMENTED** [review]
Actually, it appears these are all the changes that are needed. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45118#-:-M03hIHeBpxMvtDRlizs:bynb4hh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal)

___
*[pkg/storage/engine/bench_pebble_test.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45118#-M03hP6k3BdM1hWMLx2F:-M03hP6k3BdM1hWMLx2G:b-hbsufg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0469f81f863cb9a70f287ef4272da7c854ccdc2d/pkg/storage/engine/bench_pebble_test.go#L29)):*
> ```Go
> )
> 
> func testPebbleOptions(fs vfs.FS) *pebble.Options {
> ```

Note that I removed `testPebbleOptions` because it felt fragile to return a `pebble.Options` where the caller was required to perform `opts.Cache.Unref()`. We now have a world where `git grep -A1 pebble.NewCache` shows both the allocation of cache, and the subsequent unref.

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45118#-:-M03jnkb9rmkPN3J_YRd:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by petermattis** [comment]
Ugh, the `verify archive` CI step failed with:

`[Test archive] vendor/github.com/cockroachdb/pebble/sstable/properties.go:148:7: f.IsZero undefined (type reflect.Value has no field or method IsZero)`

The problem is that `build/teamcity-verify-archive.sh` verifies the source archive using go1.12 and `reflect.Value.IsZero` arrived in go1.13. See https://github.com/cockroachdb/pebble/pull/535 which temporarily removes the use of `reflect.Value.IsZero`.

**Comment by itsbilal** [comment]
Unfortunate. I've approved the pebble PR, and I'm assuming all you need is a vendor bump to fix the build.

**Comment by petermattis** [comment]
TFTR! We're all good now.

bors r+

**Comment by petermattis** [comment]
Unrelated CI failure (`unexpected WriteTooOld request`).

bors r+

**Comment by petermattis** [comment]
Unrelated CI failure: https://github.com/cockroachdb/cockroach/issues/43043

bors r+

**Pull request merged**
