### PR TITLE
[DNM] storage: factor out evaluation of BatchRequest

### PR DESCRIPTION
**Pull request by tbg**
The first two commits are #18785.

----

See #18779.

This doesn't carry out all the work but does all the basic required
refactoring (mod cleanups).

I don't love that we're passing `ReplicaEvalContext` through an interface.
That should be avoidable and doing so should be instructive (I suspect
we'll trim some fat in the process):

Many methods roughly take the following form:

```go
// GetMVCCStats returns the Replica's MVCCStats. func (rec
ReplicaEvalContext) GetMVCCStats() enginepb.MVCCStats {
   r := rec.repl
   r.mu.RLock()
defer r.mu.RUnlock()
return *r.mu.state.Stats, nil
}
```

and to define this method inside of the `batcheval` package, we'd have
instead

```go
type ReplicaEvalContext {
   // ...
   state struct {
       *sync.Mutex
       *storagebase.ReplicaState
   }
}
```

### CODE REVIEW

**Comment by petermattis** [comment]
Very nice! I'm not in love with the name `batcheval`, but I don't have a better suggestion right now and the bike shedding there can wait until later.

---

Review status: 0 of 30 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18796#-:-Kv2Vrz4MOp4E1nHpDnv:b-wshphr)*

**Comment by tschottdorf** [comment]
Let the bike shed begin, @petermattis. I'd prefer not having to carry out a rename once I brush this up.

I like `batcheval` and have no better name. @andreimatei suggested `eval` which I find is a bit ambiguous but could also work.

**Comment by petermattis** [comment]
`eval` feels too general. `kveval`? Shorter than `batcheval` and not ambiguous like `eval`.

**Comment by a-robinson** [comment]
I like `batcheval`, FWIW

**Comment by petermattis** [comment]
I'm also ok with `batcheval`. I don't have a strong preference between that and `kveval`.

**Comment by tschottdorf** [comment]
Superseded by #19888.

**Pull request closed without merging**
