### PR TITLE
sql: don't return an error when no healthy instances are available

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, we would return an error that "no healthy instances are available for physical planning" if the instance storage returned no instances. However, we always have the gateway pod to plan on, so this commit makes it that we use the gateway in such a scenario (unless we have a locality filter in which case we still return an error).

Informs: #109410.
Epic: None

Release note: None

### CODE REVIEW

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110222#-:-Ndlp4Ny84gMaDBDHWUH:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt)

**Review by rharding6373 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110222)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @yuzefovich)

___
*[`pkg/sql/distsql_physical_planner.go` line 1413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110222#-NdlpJSW05g3i0Q2mZ7W:-NdlpJSW05g3i0Q2mZ7X:bxf8pnm) ([raw file](https://github.com/cockroachdb/cockroach/blob/18ef8d75630cf085882901751830ce4c54086473/pkg/sql/distsql_physical_planner.go#L1413)):*
> ```Go
> 		// the sql_instances table), but we always have the gateway pod to
> 		// execute on, so we'll use it.
> 		return dsp.alwaysUseGateway, nil
> ```

Given that this is an unexpected situation, I think it may merit a warning log.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110222#-:-Ndpx7Ui6HiK9eV60QFS:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt and @rharding6373)

___
*[`pkg/sql/distsql_physical_planner.go` line 1413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110222#-NdlpJSW05g3i0Q2mZ7W:-Ndpx7-6-uOJP4qShIAp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/18ef8d75630cf085882901751830ce4c54086473/pkg/sql/distsql_physical_planner.go#L1413)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Given that this is an unexpected situation, I think it may merit a warning log.
</blockquote></details>

Done.

**Review by yuzefovich — COMMENTED** [review]
Actually, I'll adjust the logic slightly in case we have the locality filter to still return an error.

bors r-

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110222#-:-NdpxIQR3clkESana5_x:bi2o9g8)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt and @rharding6373)

**Review by yuzefovich — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110222#-:-NdpyGDg6QQYXKAPtSJM:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt and @rharding6373)

**Pull request merged**
