### PR TITLE
sql: add undocumented SURVIVE AVAILABILITY ZONE FAILURE syntax

### LINKED ISSUE #59251: sql: alias availability zone and zone
We should focus on using Zone in our docs, but it would be nice to alias availability zone in case someone forgets:
```SQL
root@127.0.0.1:26257/movr> ALTER DATABASE movr SURVIVE AVAILABILITY ZONE FAILURE;
invalid syntax: statement ignored: at or near "availability": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
ALTER DATABASE movr SURVIVE AVAILABILITY ZONE FAILURE
                            ^
HINT: try \h ALTER DATABASE
root@127.0.0.1:26257/movr> ALTER DATABASE movr SURVIVE ZONE FAILURE;
ALTER DATABASE SURVIVE

Time: 45ms total (execution 24ms / network 22ms)
```

### PR DESCRIPTION
**Pull request by otan**
Release note: None

Resolves #59251

### CODE REVIEW

**Review by ajstorm — COMMENTED** [review]
Wow, that was fast, even for you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59270#-:-MRbYd6k87FW4rP8W9yo:b-j9t8yb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/parser/parse_test.go, line 1812 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59270#-MRbYYf01yw1DrIW3nOl:-MRbYYf01yw1DrIW3nOm:b-6he1ur) ([raw file](https://github.com/cockroachdb/cockroach/blob/de65772f62350dc8df447f780cbf4db759d5c1a3/pkg/sql/parser/parse_test.go#L1812)):*
> ```Go
> 		},
> 		{
> 			`CREATE DATABASE IF NOT EXISTS a SURVIVE = AVAILABILITY ZONE FAILURE`,
> ```

Nit: why the `=`?

**Comment by otan** [comment]
___
*[pkg/sql/parser/parse_test.go, line 1812 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59270#-MRbYYf01yw1DrIW3nOl:-MRbZd5V7akM4b5NBySv:b-887bwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/de65772f62350dc8df447f780cbf4db759d5c1a3/pkg/sql/parser/parse_test.go#L1812)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Nit: why the `=`?
</blockquote></details>

the `=` is optional, so felt like we should celebrate it's existence by including it

**Comment by otan** [comment]
bors r=ajstorm

**Comment by otan** [comment]
bors r=ajstorm

**Pull request merged**
