### PR TITLE
docs: fix indentation in date/time function description

### LINKED ISSUE #9912: Fix wrong formatting in generated functions and operators page
See text with black background: https://www.cockroachlabs.com/docs/stable/functions-and-operators.html#date-and-time-functions

This might need to be fixed in `cockroach` itself. But perhaps we can solve it on our end with CSS. Need to check.

### PR DESCRIPTION
**Pull request by jseldess**
Release justification: low-risk, high benefit changes to existing functionality

Release note: None

Fixes cockroachdb/docs#9912

### CODE REVIEW

**Review by knz — COMMENTED** [review]
:lgtm: very nice!

You will want to add this to your commit message + PR description (both):

```
Release justification: low-risk, high benefit changes to existing functionality
```

Also I think you need to run `make buildshort` to auto-regenerate the doc files.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61339#-:-MUnziKc2nlFAGkgWv8H:b-8erm2p)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by knz** [comment]
cc @rafiss can you guide Jesse towards completion of this PR and merge it when compelte thanks

**Comment by jseldess** [comment]
@knz, @rafiss, I updated the commit message and PR description, and I tried running `make buildshort`, but it doesn't seem to have worked or regenerated any docs. Might need help there. Perhaps my version of `make` is too old.

**Comment by rafiss** [comment]
@jseldess did `make buildshort` fail when you ran it? I confirmed that it does cause docs to be regenerated when I run it locally.

If you're on a Mac, can you make sure you have a recent `make` version? GNU Make 4.2+ is known to work. You can get it with `brew install make` and then `echo 'PATH="/usr/local/opt/make/libexec/gnubin:$PATH"' >> ~/.zshrc` (or else update the PATH in whichever you customize your shell profile). Confirm the version with `make --version`.

**Comment by jseldess** [comment]
Done. PTAL, @rafiss.

**Review by rafiss — APPROVED** [review]
thank you @jseldess !

bors r+

**Pull request merged**
