### PR TITLE
kvserver: allow retrying scatter processing with more errors

### LINKED ISSUE #124522: kvserver: admin scatter should retry processing on a descriptor change error
**Is your feature request related to a problem? Please describe.**
`AdminScatter` currently only retries processing upon encountering a snapshot error:

https://github.com/cockroachdb/cockroach/blob/2fc6cd0ec921fc0f7f06e480e45381d92f85c6f9/pkg/kv/kvserver/replica_command.go#L4158-L4164

It is commonly the case that splits will interleave scatters, as callers attempt to distribute the keyspace before some operation, such as RESTORE or an index backfill.

When a split races with the scatter and changes the descriptor whilst a scatter is being processed, the scatter will fail.

**Describe the solution you'd like**

Retry descriptor change errors, similar to snapshot errors for admin scatter.

Jira issue: CRDB-38942

### PR DESCRIPTION
**Pull request by kvoli**
Previously, scatter processing would only be retried when encountering a snapshot error. Other errors commonly occur, which we expect to be transient and retryable, such as the range descriptor changing or rejected lease transfers. The range descriptor change error being most common, due to the proclivity of clients to issue splits alongside scatter requests, which would update the range descriptor.

Retry failed scatter replicate processing if the returned error matches any of `IsRetriableReplicationChangeError`s, similar to range splits. Note the maximum number of retries remains at 5 for scatter.

Resolves: #124522
Release note: None

### CODE REVIEW

**Comment by dt** [comment]
Maybe while we're here we should rename `maxAttempts` and `currentAttempt` to `maxSuccesses` and `successes` to avoid confusing them with the retry attempt limit?

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124537#-:-NyfAbkd94vz5seP1N4V:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt)

**Review by kvoli — COMMENTED** [review]
>Maybe while we're here we should rename `maxAttempts` and `currentAttempt` to `maxSuccesses` and `successes` to avoid confusing them with the retry attempt limit?

I'd prefer to update all of the retry logic (including updating the attempt logic) in a separate PR, to avoid muddling the change here.


TYFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124537#-:-Nz-l5Nu2q867z5YNSe8:b3mphwf)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt)

**Comment by kvoli** [comment]
bors r=nvanbenschoten

**Pull request merged**
