### PR TITLE
opt: add index acceleration support for ~ and && bounding box operators

### PR DESCRIPTION
**Pull request by rytaft**
This commit adds index acceleration support for the bounding box comparison
operators, `~` and `&&`. It maps `~` to Covers and `&&` to Intersects.

Release note (performance improvement): The ~ and && geospatial bounding
box operations can now benefit from index acceleration if one of the
operands is an indexed geometry column.

### CODE REVIEW

**Comment by otan** [comment]
LGTM, but not fully read up on optimizer bits to point out anything major.
heads up you'll probably need to set the cluster setting for some of these in a rebase though.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53023)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson, @otan, and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/inverted_join_geospatial, line 223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53023#-MF6NDmVEKQBmxKN5M2_:-MF6NDmVEKQBmxKN5M2a:b-1xaxa9) ([raw file](https://github.com/cockroachdb/cockroach/blob/09ba79a81bd5d471a9589fcfb7f04638157d4a42/pkg/sql/logictest/testdata/logic_test/inverted_join_geospatial#L223)):*
> ```
> 
> query II
> SELECT lk, rk FROM ltable JOIN rtable@geom_index ON rtable.geom && ltable.geom1
> ```

can you add some tests here and for inverted_filterer where one of these is cast to a box2d before doing `&&` or `~`.
___
*[pkg/sql/opt/invertedidx/geo.go, line 348 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53023#-MF6MVBQ3zxlfDVlcm7U:-MF6MVBQ3zxlfDVlcm7V:bzbvbv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/09ba79a81bd5d471a9589fcfb7f04638157d4a42/pkg/sql/opt/invertedidx/geo.go#L348)):*
> ```Go
> 			t.Child(0).(opt.ScalarExpr), t.Child(1).(opt.ScalarExpr),
> 		}
> 		// Cast the arguments to type Geometry if needed (they may be type box2d).
> ```

same question as below about the cast failing.
___
*[pkg/sql/opt/invertedidx/geo.go, line 532 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53023#-MF6LtJ_2XIREoOKqiBW:-MF6LtJ_2XIREoOKqiBX:b-54o29m) ([raw file](https://github.com/cockroachdb/cockroach/blob/09ba79a81bd5d471a9589fcfb7f04638157d4a42/pkg/sql/opt/invertedidx/geo.go#L532)):*
> ```Go
> 			t.Child(0).(opt.ScalarExpr), t.Child(1).(opt.ScalarExpr),
> 		}
> 		// Cast the arguments to type Geometry if needed (they may be type box2d).
> ```

what if the argument is not box2d? How is that cast error handled?
___
*[pkg/sql/opt/xform/testdata/rules/join, line 3491 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53023#-MF6Kti926UCVcE8ptCX:-MF6Kti926UCVcE8ptCY:b-h5vefj) ([raw file](https://github.com/cockroachdb/cockroach/blob/09ba79a81bd5d471a9589fcfb7f04638157d4a42/pkg/sql/opt/xform/testdata/rules/join#L3491)):*
> ```
> FROM nyc_census_blocks AS c
> JOIN nyc_neighborhoods@nyc_neighborhoods_geo_idx AS n
> ON c.geom::box2d ~ n.geom
> ```

can you add a test with 
```
 n.geom ~ c.geom::box2d
```
to show that it uses `st_coveredby` for the join.
___
*[pkg/sql/opt/xform/testdata/rules/select, line 2186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53023#-MF6K4IO15YEQGnvC5Qx:-MF6K4IO15YEQGnvC5Qy:b50l012) ([raw file](https://github.com/cockroachdb/cockroach/blob/09ba79a81bd5d471a9589fcfb7f04638157d4a42/pkg/sql/opt/xform/testdata/rules/select#L2186)):*
> ```
> 
> opt
> SELECT k FROM g WHERE geom ~ 'BOX(1 2, 3 4)'::box2d
> ```

this is the CoveredBy case for the index yes?
I'm surprised that this isn't resulting in any intersection in the inverted expression below. It may be because these tests use a cell covering that is very coarse, so maybe the inner covering for this Box was a single cell. Can you tweak that to confirm that the right thing is happening?

**Review by rytaft — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53023#-:-MF7Onq5-W02sjzU-B0G:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson, @otan, and @sumeerbhola)

___
*[pkg/sql/logictest/testdata/logic_test/inverted_join_geospatial, line 223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53023#-MF6NDmVEKQBmxKN5M2_:-MF7LpbXBqO5u99Hx--S:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/09ba79a81bd5d471a9589fcfb7f04638157d4a42/pkg/sql/logictest/testdata/logic_test/inverted_join_geospatial#L223)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you add some tests here and for inverted_filterer where one of these is cast to a box2d before doing `&&` or `~`.
</blockquote></details>

Done.
___
*[pkg/sql/opt/invertedidx/geo.go, line 348 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53023#-MF6MVBQ3zxlfDVlcm7U:-MF7LqsK1w5qpLVbxtWK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/09ba79a81bd5d471a9589fcfb7f04638157d4a42/pkg/sql/opt/invertedidx/geo.go#L348)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

same question as below about the cast failing.
</blockquote></details>

Done.
___
*[pkg/sql/opt/invertedidx/geo.go, line 532 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53023#-MF6LtJ_2XIREoOKqiBW:-MF7H7jO9nqWmDxhndys:bjgh01o) ([raw file](https://github.com/cockroachdb/cockroach/blob/09ba79a81bd5d471a9589fcfb7f04638157d4a42/pkg/sql/opt/invertedidx/geo.go#L532)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

what if the argument is not box2d? How is that cast error handled?
</blockquote></details>

This works because the optimizer will not fold a cast if it would cause an error. If an argument is not either type `geometry` or `box2d`, that means this is not a bounding box operator, and therefore the checks inside `constrainGeoIndexFromExpr` will fail anyway.

However, I agree this is not obvious, and it seems like it only works by accident. I've cleaned it up a bit so hopefully it's clearer that it should work.
___
*[pkg/sql/opt/xform/testdata/rules/join, line 3491 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53023#-MF6Kti926UCVcE8ptCX:-MF7L7EZDeR1cOIa7M0V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/09ba79a81bd5d471a9589fcfb7f04638157d4a42/pkg/sql/opt/xform/testdata/rules/join#L3491)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you add a test with 
```
 n.geom ~ c.geom::box2d
```
to show that it uses `st_coveredby` for the join.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/rules/select, line 2186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53023#-MF6K4IO15YEQGnvC5Qx:-MF7LkeL6_s3tiPPvxhO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/09ba79a81bd5d471a9589fcfb7f04638157d4a42/pkg/sql/opt/xform/testdata/rules/select#L2186)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this is the CoveredBy case for the index yes?
I'm surprised that this isn't resulting in any intersection in the inverted expression below. It may be because these tests use a cell covering that is very coarse, so maybe the inner covering for this Box was a single cell. Can you tweak that to confirm that the right thing is happening?
</blockquote></details>

Done.

**Comment by mgartner** [comment]
___
*[pkg/sql/opt/invertedidx/geo.go, line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53023#-MF7Te480q5ZSsegRcxF:-MF7Te480q5ZSsegRcxG:bn2mqyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/801e0446a13c5f6e803d079f563fc83a4cb787d7/pkg/sql/opt/invertedidx/geo.go#L48)):*
> ```Go
> 		return geoindex.Covers, true
> 	}
> 	if _, ok := expr.(*memo.OverlapsExpr); ok {
> ```

Would it make sense to have different memo expressions for the geo version of these operators? It might be safer in the case that normalization rules are added for `*memo.RegMatchExpr` or `*memo.OverlapsExpr` that don't apply to the geo versions.

I did something similar for the `IS NULL` operator here, FWIW: https://github.com/cockroachdb/cockroach/pull/48299/files#diff-15f17802e304627c3b80d68ac3394c4f

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53023#-:-MFB-FoYDNHcpfxvXsUc:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson, @otan, @rytaft, and @sumeerbhola)

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53023)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mjibson, @otan, and @sumeerbhola)

___
*[pkg/sql/opt/invertedidx/geo.go, line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53023#-MF7Te480q5ZSsegRcxF:-MFBIsib6Ft19YhYoGw4:bqopw4u) ([raw file](https://github.com/cockroachdb/cockroach/blob/801e0446a13c5f6e803d079f563fc83a4cb787d7/pkg/sql/opt/invertedidx/geo.go#L48)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Would it make sense to have different memo expressions for the geo version of these operators? It might be safer in the case that normalization rules are added for `*memo.RegMatchExpr` or `*memo.OverlapsExpr` that don't apply to the geo versions.

I did something similar for the `IS NULL` operator here, FWIW: https://github.com/cockroachdb/cockroach/pull/48299/files#diff-15f17802e304627c3b80d68ac3394c4f


</blockquote></details>

Good idea - Done.

**Review by madelynnblue — APPROVED** [review]

**Review by mgartner — APPROVED** [review]
:lgtm: 

Are changes in `execbuilder/scalar.go` required to turn `*memo.BBoxCoversExpr` and `*memo.BBoxIntersectsExpr` back into their original tree representation in the case that a query does not use an inverted index?

> Reviewed 6 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53023#-:-MFBhE5Q-Sq91JH3fMVa:b-q9vbyj)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @otan, @rytaft, and @sumeerbhola)

___
*[pkg/sql/opt/ops/scalar.opt, line 475 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53023#-MFBYoAJEcG3mDyMDgjP:-MFBYoAJEcG3mDyMDgjQ:b-2a5452) ([raw file](https://github.com/cockroachdb/cockroach/blob/a83f64ad4238a1525e2bc87a54159d331905d812/pkg/sql/opt/ops/scalar.opt#L475)):*
> ```
> 
> [Scalar, Bool, Comparison]
> define BBoxCovers {
> ```

[nit] add a brief comment here explaining that these are `~` and `&&` expressions for Geometry or Box2d types.
___
*[pkg/sql/opt/optbuilder/testdata/scalar, line 1382 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53023#-MFBZLCJ5SLRmFtqvF1H:-MFBZLCJ5SLRmFtqvF1I:b6qjvsj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a83f64ad4238a1525e2bc87a54159d331905d812/pkg/sql/opt/optbuilder/testdata/scalar#L1382)):*
> ```
> overlaps [type=bool]
>  ├── variable: "@1":1 [type=int[]]
>  └── variable: "@2":2 [type=int[]]
> ```

[nit] add a test for when one child is a geometry/box2d and the other is not

**Review by rytaft — COMMENTED** [review]
TFTRs!

> Are changes in execbuilder/scalar.go required to turn *memo.BBoxCoversExpr and *memo.BBoxIntersectsExpr back into their original tree representation in the case that a query does not use an inverted index?

Nope, `ComparisonOpReverseMap` in `operator.go` does that. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53023#-:-MFBlz4a5l4rd_1x2yAb:b-nw2e6w)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner, @otan, and @sumeerbhola)

___
*[pkg/sql/opt/ops/scalar.opt, line 475 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53023#-MFBYoAJEcG3mDyMDgjP:-MFBkV9e51GpAWFvVnCI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a83f64ad4238a1525e2bc87a54159d331905d812/pkg/sql/opt/ops/scalar.opt#L475)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] add a brief comment here explaining that these are `~` and `&&` expressions for Geometry or Box2d types.
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/testdata/scalar, line 1382 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53023#-MFBZLCJ5SLRmFtqvF1H:-MFBleVI8JYhqTLh-I_H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a83f64ad4238a1525e2bc87a54159d331905d812/pkg/sql/opt/optbuilder/testdata/scalar#L1382)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] add a test for when one child is a geometry/box2d and the other is not
</blockquote></details>

Done.

**Review by mgartner — COMMENTED** [review]
> Nope, ComparisonOpReverseMap in operator.go does that.

Ahh, very good.

:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53023#-:-MFBmfi0AolHOzqXuEP1:b-u1c7w4)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @otan, and @sumeerbhola)

**Pull request merged**
