### PR TITLE
 sql,opt: propagate composite types (labeled tuples)

### LINKED ISSUE #24866: sql: support lightweight composite types for in-flight values
Forked off #24832.
Needed for #16971.

The PostgreSQL type system supports "composite types" which are really just tuples of values where the arity is constant (same for every row) and each column in the tuple has a static label (same for every row). 

They show up mainly as follows.

### Reification of tables as composite values

If an identifier in a *scalar expression* refers to one of the *relational expressions* in the current context (e.g. a table name in the FROM clause), then the result of evaluating that identifier in the scalar context is a  composite expression, with the relexp's columns as elements.

For example:

```
> SELECT kv FROM kv;
   kv
---------
 (37,2)
 (94,3)
 (30,3)

> SELECT (kv, kv) AS woo FROM kv;
          woo
-----------------------
 ("(37,2)","(37,2)")
 ("(94,3)","(94,3)")
 ("(30,3)","(30,3)")
```

**Note: in these examples, the result tables have just 1 column. This is a radically different path/concept than e.g. `SELECT kv.* FROM kv` (star expansion) which produces as many columns as the FROM table.**

Implementation wise, the identifier to the relexpr must be replaced by a suitable tuple constructor, e.g. `ROW(...)` with some extended syntax to define labels in the type.

### Access to tuple columns in scalar contexts

If a scalar expression `E` has composite type `(..., "a", ...)` (tuple with at least some column label "a"), then the expression `(E).a` is valid and refers to the element labeled "a" in the tuple `E`.

For example:

```
> SELECT (kv).v FROM kv;
 v
---
 2
 3
 3
```

**Note: This is a mechanism that is distinct from the common column name resolution on data sources, e.g. `kv.v`. The relational expression is first reified as a tuple in the scalar context, and then one of the tuple columns is accessed.**

Implementation wise, the expression of the form `(E).label` must be handled by a dedicated scalar expression node type, for example `ColumnAccessExpr` introduced in #24832.

### Propagation across relational expression boundaries

Composite types are regular types, and propagate naturally across sub-queries.

For example:

```
>  SELECT (a).v FROM (SELECT kv AS a FROM kv) AS woo;
 v
---
 2
 3
 3
```

Implementation wise, CockroachDB must recognize composite types during type checking. We can perhaps use the existing `types.Table` for this purpose, some more investigation needed to check this.

### "Star expansion" in composite expressions

If an expression of the form `(E).*` is present at the top-level of a render expression (a.k.a. "Select target expression", "projection expression" or `SelectExpr` in the current source code), then a special rule for star expansion kicks in: 

- the expression `E` is checked to have composite type (according to the rules above)
- the render expr is replaced by a sequence of expressions of the form `(@n).lbl1, (@n).lbl2, (@n).lbl3, ...` where:
  - `@n` refers to the single IndexedVar of an underlying projection that will compute the composite expression just once
  - `lbl1`, `lbl2`, ... refer to the labels of the composite.

**Note: this seems to be a separate mechanism than the regular star expansion.**

###  Fancy example

This is the original example that motivates this issue:

```
> SELECT (i.keys).n FROM (SELECT information_schema._pg_expandarray(ARRAY[3,2,1]) AS keys) AS i;
```

This query really means the following:

```
> WITH i AS SELECT (tmp_tbl) AS keys -- generates a composite expr, rename it to `keys`
              FROM information_schema._pg_expandarray(ARRAY[3,2,1])) AS tmp_tbl
    SELECT (tmp_tuple).n  -- uses a tuple element access sub-expression
      FROM (SELECT keys AS tmp_tuple FROM i)
```

So in order to support this query CockroachDB must be able to:

1. lift an SRF in render position into the FROM clause and *replace it by a composite constructor*
2. properly type composite expressions and propagate their types
3. support the tuple element access expression for composite types

We can start the work by introducing the proper typing and evaluation rules and use `types.Table` for composite expressions. No need to support storing of composite values yet.

### PR DESCRIPTION
**Pull request by knz**
Needed to resolve #24866.

This patch adds more complete support for composite types (labeled
tuples) by ensuring the following:

- tuple labels are preserved during constant folding of tuple
  expressions.
- tuple labels are preserved during expression transformations
  in optimizations.
- subqueries in scalar contexts receive a composite type with labels.

Note that there is currently a bug in DTuple serialization which break
composite literals in distributed execution, so the composite type
support is not fully ready yet.
This is tracked as separate bug #26624.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
@RaduBerinde @rytaft can you help me with the last remaining bit: the derived scalar type for a subquery in scalar context is not computed properly in the optimizer. Where is that type computed today?

**Comment by knz** [comment]
> can you help me with the last remaining bit: the derived scalar type for a subquery in scalar context is not computed properly in the optimizer. Where is that type computed today?

Never mind, found it!

RFAL

**Comment by RaduBerinde** [comment]
opt part LGTM

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26621#-:-LEpcNvTCD3flzYQlhif:b-33fro1)*

**Comment by knz** [comment]
@BramGruneir can you propagate the comments you made on #26628 that really pertain to this PR here? I'd like to iterate and merge this one before I rebase the other one.

**Comment by knz** [comment]
@BramGruneir I have replied to your comments that pertain to this PR over in https://github.com/cockroachdb/cockroach/pull/26628#issuecomment-396881675.

**Comment by BramGruneir** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26621#-:-LEtYSjc6urXY1Gbdukf:bnfp4nl)*

**Comment by knz** [comment]
TFYR!

bors r+

**Pull request merged**
