### PR TITLE
2023 06 26 non lease changes

### PR DESCRIPTION
**Pull request by andrewbaptist**
Numerous small changes to clean up the liveness interface and prepare for converting all code to have a unified view of liveness. After these changes everything but the lease management is correctly converted over to the new Liveness/Vitality interface.

Epic: none

Release note: None

### CODE REVIEW

**Comment by andrewbaptist** [comment]
This is the bulk of the remaining changes. There are 3 small additional changes after this:
1) Change the lease code to stop using IsLiveMap (only 1 test still failing on it).
2) Remove some of the dead methods after these changes. (Simple code deletion).
3) Introduce the flag to stop updating liveness (a number of test failures).

I'm hoping to finish the last remaining test for 1 today and continue working on 3 and possibly finish tomorrow. I'm assuming there will be some amount of feedback from these changes, so I'll try and address that when I can.

**Review by erikgrinaker — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 8 of 8 files at r2, 8 of 8 files at r3, 2 of 2 files at r4, 4 of 4 files at r5, 4 of 4 files at r6, 6 of 6 files at r7, 18 of 18 files at r8, 5 of 5 files at r9, 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105572)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist)

___
*[`pkg/kv/kvserver/replica_metrics.go` line 67 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/105572#-NZ0PAnf2bG3Jpnn4Mfl:-NZ0PAng7_cGleiv3fBo:bip2jk8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e23c09b9dbe08af883a121b037a7ee8f1f1001a/pkg/kv/kvserver/replica_metrics.go#L67)):*
> ```Go
> 	ctx context.Context,
> 	now hlc.ClockTimestamp,
> 	livenessMap livenesspb.NodeVitalityMap,
> ```

nit: `vitalityMap`? Goes throughout.
___
*[`pkg/kv/kvserver/liveness/liveness.go` line 648 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/105572#-NZ0JCpt9R10O--BzpL6:-NZ0JCpt9R10O--BzpL7:b-k35dew) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8df578f0f3a437394e0d75a060daab83b953db3/pkg/kv/kvserver/liveness/liveness.go#L648)):*
> ```Go
> }
> 
> // OnNodeDecommissionCallback is a callback that is invoked when a node is
> ```

I believe this type is unused now.
___
*[`pkg/kv/kvserver/liveness/liveness.go` line 1313 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/105572#-NZ0JNQW4voj_nVXaABX:-NZ0JNQW4voj_nVXaABY:b2gnq52) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8df578f0f3a437394e0d75a060daab83b953db3/pkg/kv/kvserver/liveness/liveness.go#L1313)):*
> ```Go
> // TestingGetLivenessThreshold returns the maximum duration between heartbeats
> // before a node is considered not-live.
> func (nl *NodeLiveness) TestingGetLivenessThreshold() time.Duration {
> ```

Can we move this out to a `helpers_test.go` or something?
___
*[`pkg/kv/kvserver/liveness/liveness.go` line 642 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/105572#-NZ0OM1g45WJFie-jaHS:-NZ0OM1g45WJFie-jaHT:b-jemye6) ([raw file](https://github.com/cockroachdb/cockroach/blob/94c86d3ac76dcebda91a5f037aea17864618312d/pkg/kv/kvserver/liveness/liveness.go#L642)):*
> ```Go
> 		// once we re-visit the caching structure used within NodeLiveness;
> 		// we should be able to return ErrMissingRecord instead.
> 		return false, ErrRecordCacheMiss
> ```

There are some code paths that rely on `ErrRecordCacheMiss` being returned. I think it's test-only, and most likely we can get rid of the error entirely, but worth verifying that any older versions (we may need to maintain both 23.1 and 22.2 compatibility) don't rely on it being returned either. For example:

https://github.com/cockroachdb/cockroach/blob/6369846e12471585b1063e9bc7d19597428f53aa/pkg/kv/kvnemesis/validator.go#L1259-L1261¨
___
*[`pkg/server/admin.go` line 2715 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/105572#-NZ0LaIJ8te-PdOhKLOp:-NZ0LaIJ8te-PdOhKLOq:b-r55s8p) ([raw file](https://github.com/cockroachdb/cockroach/blob/94c86d3ac76dcebda91a5f037aea17864618312d/pkg/server/admin.go#L2715)):*
> ```Go
> 				DecommissionReadiness: serverpb.DecommissionPreCheckResponse_ALREADY_DECOMMISSIONED,
> 			}
> 		} else if !vitality.IsLive(livenesspb.DecommissionCheck) {
> ```

Is this functionally equivalent to `UNKNOWN`? I though `UNKNOWN` were nodes we didn't have any liveness information at all, while `!IsLive` is nodes that are (temporarily) unavailable. Is there a big difference in time scales for these conditions?
___
*[`pkg/server/auto_upgrade.go` line 145 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/105572#-NZ0MEq9CjVpycTSZxP1:-NZ0MEq9CjVpycTSZxP2:bi2min) ([raw file](https://github.com/cockroachdb/cockroach/blob/94c86d3ac76dcebda91a5f037aea17864618312d/pkg/server/auto_upgrade.go#L145)):*
> ```Go
> 		}
> 
> 		if !v.IsAvailableNotDraining() {
> ```

Why do we reject draining nodes? What if an operator wants to keep a node drained for good reason during the upgrade?
___
*[`pkg/server/server.go` line 508 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/105572#-NZ0J_aA6awrAavA6oTG:-NZ0J_aBEKZ35mI-MXuU:b-3htss2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8df578f0f3a437394e0d75a060daab83b953db3/pkg/server/server.go#L508)):*
> ```Go
> 			}
> 			if err := nodeTombStorage.SetDecommissioned(
> 				ctx, id, clock.PhysicalTime().UTC(),
> ```

Is this change safe? What was the motivation for setting it to the liveness expiration time in the first place?
___
*[`pkg/sql/crdb_internal.go` line 4679 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105572#-NZ0Bzpl5Rj2T_wFlXX4:-NZ0Bzpl5Rj2T_wFlXX5:b-t7olea) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd0c51843884b9f30af6780280eb370bfc288ad1/pkg/sql/crdb_internal.go#L4679)):*
> ```Go
> 			// We want the generated liveness which will simulate the expiration in
> 			// the liveness record is not activily updated.
> 			livenesses[i] = v.GenLiveness()
> ```

nit: can use `append(livenesses, v.GenLiveness())` to omit `i`, `livenesses` allocated with capacity.

**Review by andrewbaptist — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105572)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[`pkg/kv/kvserver/replica_metrics.go` line 67 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/105572#-NZ0PAnf2bG3Jpnn4Mfl:-NZ1AwyECXsn_pXTrJxk:b-rvv3vd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e23c09b9dbe08af883a121b037a7ee8f1f1001a/pkg/kv/kvserver/replica_metrics.go#L67)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

nit: `vitalityMap`? Goes throughout.
</blockquote></details>

Done - changed all instances
___
*[`pkg/kv/kvserver/liveness/liveness.go` line 648 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/105572#-NZ0JCpt9R10O--BzpL6:-NZ1BUMmE6e-a_Q2BuO6:bobclp9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8df578f0f3a437394e0d75a060daab83b953db3/pkg/kv/kvserver/liveness/liveness.go#L648)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I believe this type is unused now.
</blockquote></details>

Good catch. Removed.
___
*[`pkg/kv/kvserver/liveness/liveness.go` line 1313 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/105572#-NZ0JNQW4voj_nVXaABX:-NZ1DkDVE3xod0pmGkPy:b-xte0hr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8df578f0f3a437394e0d75a060daab83b953db3/pkg/kv/kvserver/liveness/liveness.go#L1313)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Can we move this out to a `helpers_test.go` or something?
</blockquote></details>

Moved (this and other test methods in this file). 
___
*[`pkg/kv/kvserver/liveness/liveness.go` line 642 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/105572#-NZ0OM1g45WJFie-jaHS:-NZ1R0jF5UoIxK-lizEy:b4wgr0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/94c86d3ac76dcebda91a5f037aea17864618312d/pkg/kv/kvserver/liveness/liveness.go#L642)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

There are some code paths that rely on `ErrRecordCacheMiss` being returned. I think it's test-only, and most likely we can get rid of the error entirely, but worth verifying that any older versions (we may need to maintain both 23.1 and 22.2 compatibility) don't rely on it being returned either. For example:

https://github.com/cockroachdb/cockroach/blob/6369846e12471585b1063e9bc7d19597428f53aa/pkg/kv/kvnemesis/validator.go#L1259-L1261¨
</blockquote></details>

I spent some time tracking down why this is necessary and how it is handled. I still don't completely understand how we could get here on lookup. This error is also returned from `updateLivenessAttempt` and I updated the comment there as that is more likely to be encountered in the wild. 
___
*[`pkg/server/admin.go` line 2715 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/105572#-NZ0LaIJ8te-PdOhKLOp:-NZ1IhKM4pDl8iZKg36x:b-wtb4l8) ([raw file](https://github.com/cockroachdb/cockroach/blob/94c86d3ac76dcebda91a5f037aea17864618312d/pkg/server/admin.go#L2715)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Is this functionally equivalent to `UNKNOWN`? I though `UNKNOWN` were nodes we didn't have any liveness information at all, while `!IsLive` is nodes that are (temporarily) unavailable. Is there a big difference in time scales for these conditions?
</blockquote></details>

You're right these are different. I changed back to matching the "unknown" check and added a comment. The check is a little strange and should probably be changed, but leaving for now.
___
*[`pkg/server/auto_upgrade.go` line 145 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/105572#-NZ0MEq9CjVpycTSZxP1:-NZ1KLW02P-uklw6na2T:bfymc85) ([raw file](https://github.com/cockroachdb/cockroach/blob/94c86d3ac76dcebda91a5f037aea17864618312d/pkg/server/auto_upgrade.go#L145)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Why do we reject draining nodes? What if an operator wants to keep a node drained for good reason during the upgrade?
</blockquote></details>

I was attempting to minimize changes in behavior as part of this refactor. I added a comment to the check and will look at changing this as a separate PR. I agree that this is too strict of a check.
___
*[`pkg/server/server.go` line 508 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/105572#-NZ0J_aA6awrAavA6oTG:-NZ1LO3T85pVAkNlyPeW:b-z05p6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8df578f0f3a437394e0d75a060daab83b953db3/pkg/server/server.go#L508)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Is this change safe? What was the motivation for setting it to the liveness expiration time in the first place?
</blockquote></details>

I looked a little more what this timestamp is used for, and it appears the only usage is here:
https://github.com/cockroachdb/cockroach/blob/master/pkg/server/decommission.go#L135. This is just checking against non-zero and then returning the time in the log. A decommissioned node should have no replicas (and therefore no valid leases) at the time it is marked as decommissioned. 

I'm not 100% sure that we even need to keep all this tombstone infrastructure as we could just look it up in the liveness record, but I didn't want to touch any of that as part of this PR.
___
*[`pkg/sql/crdb_internal.go` line 4679 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105572#-NZ0Bzpl5Rj2T_wFlXX4:-NZ1Ne-b9SRxp7yXKsgx:b499q7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd0c51843884b9f30af6780280eb370bfc288ad1/pkg/sql/crdb_internal.go#L4679)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

nit: can use `append(livenesses, v.GenLiveness())` to omit `i`, `livenesses` allocated with capacity.
</blockquote></details>

Changed

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105572)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist)

___
*[`pkg/server/auto_upgrade.go` line 145 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/105572#-NZ0MEq9CjVpycTSZxP1:-NZ1UKfs4aM8GURjB-g8:b-vejsub) ([raw file](https://github.com/cockroachdb/cockroach/blob/94c86d3ac76dcebda91a5f037aea17864618312d/pkg/server/auto_upgrade.go#L145)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

I was attempting to minimize changes in behavior as part of this refactor. I added a comment to the check and will look at changing this as a separate PR. I agree that this is too strict of a check.
</blockquote></details>

The previous check didn't fail on draining nodes though, only decommissioning nodes.
___
*[`pkg/server/server.go` line 508 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/105572#-NZ0J_aA6awrAavA6oTG:-NZ1UZtFAbtf5mF-N7Ab:b-jfbxcr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8df578f0f3a437394e0d75a060daab83b953db3/pkg/server/server.go#L508)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

I looked a little more what this timestamp is used for, and it appears the only usage is here:
https://github.com/cockroachdb/cockroach/blob/master/pkg/server/decommission.go#L135. This is just checking against non-zero and then returning the time in the log. A decommissioned node should have no replicas (and therefore no valid leases) at the time it is marked as decommissioned. 

I'm not 100% sure that we even need to keep all this tombstone infrastructure as we could just look it up in the liveness record, but I didn't want to touch any of that as part of this PR.
</blockquote></details>

Right, probably fine then. We need the tombstone infrastructure, otherwise a node that's just starting up (and haven't yet connected to gossip or KV) may begin communicating with a node that's no longer part of the cluster. This will necessarily be best-effort, but seems worthwhile to make that effort.

**Comment by knz** [comment]
drive by review: don't forget to populate the PR title and description.

**Comment by andrewbaptist** [comment]
bors r=erikgrinaker

**Pull request merged**
