### PR TITLE
rttanalysis, catalog: add benchmark for scanning comments, database-aware scans for comments

### LINKED ISSUE #114822: catalog: teach ScanAllComments to only scan namespace entries for the database it needs to
**Is your feature request related to a problem? Please describe.**

The code to fetch comments works like this: https://github.com/cockroachdb/cockroach/blob/c3b0af2bef1231d47bd3a4de5e4f0ee9e5222536/pkg/sql/catalog/internal/catkv/catalog_reader.go#L166-L177

It scans the system.comments, as well as _all_ the entries in system.namespace. We have seen cases where this can perform badly when there a large number of namespace entries. A common pattern that makes them get so large is that a cluster may have multiple databases, and each one may have a copy of the same schemas/tables inside of it.

**Describe the solution you'd like**

Rather than scanning all of the namespace entries, we can change the scan to also add the database ID as a prefix to the query against system.namespace (NB: the primary key of system.namespace is `("parentID" ASC, "parentSchemaID" ASC, name ASC)`).

There are two cases to handle:
- when populating `pg_catalog.pg_shdescription`, we use: https://github.com/cockroachdb/cockroach/blob/0ce5debe6731e21afb8c1c13c8e5a885abe58ad3/pkg/sql/vtable/pg_catalog.go#L334-L338
- when populating `pg_catalog.pg_description`, we use https://github.com/cockroachdb/cockroach/blob/0ce5debe6731e21afb8c1c13c8e5a885abe58ad3/pkg/sql/vtable/pg_catalog.go#L317-L328 

These queries access `crdb_internal.kv_catalog_comments` here: https://github.com/cockroachdb/cockroach/blob/30515487044ca731d656751df19625a7b73a0ad1/pkg/sql/crdb_internal.go#L5779-L5783

In the first case, `dbContext` should be `nil`, meaning we should only scan system.namespace entries where `parentID` is 0.

In the second case, `dbContext` should have a database descriptor, meaning we should only scan system.namespace entries where the parentID equals that descriptor's ID.

**Describe alternatives you've considered**
Somehow avoid scanning namespace entries at all. I'm not entirely sure what else would need to change, so this is a bigger lift.

**Additional context**
See https://github.com/cockroachlabs/support/issues/2722

Jira issue: CRDB-33699

### PR DESCRIPTION
**Pull request by annrpom**
### rttanalysis: add a benchmark for scanning comments

This patch adds a query made by liquibase migrations
as a benchmark test. The example setup (15 dbs, 40 tables each)
mimicks a pattern we have seen before that causes said query to
be particularly slow during the scanning of comments. In addition
to the multiple database setup, this query is benchmarked under
a single database setup as well - allowing us to compare the
behaviors of both patterns.

Epic: none
Informs: https://github.com/cockroachdb/cockroach/issues/114822

Release note: None

---

### catalog: perform database-aware scans for comments in namespace

Previously, we would look at the entirety of system.namespace
when we performed a scan of all comments (even though we only wanted to
pull comments for the current database). We saw that this operation
proved to be slow in cases where we had multiple databases with
multiple tables each. This patch ensures that we only perform a scan
for comments in the current database.

Benchmarks from multiple database test:
```
ORMQueries/liquibase_migrations_on_multiple_dbs-10     sec/op             sec/op vs base
                    				       163.03m ± 41%      22.50m ± 2%   -86.20% (p=0.000 n=10)

ORMQueries/liquibase_migrations_on_multiple_dbs-10     roundtrips         roundtrips vs base
			  			       7.000   ± 0% 	  8.000 ± 0%    +14.29% (p=0.000 n=10)

ORMQueries/liquibase_migrations_on_multiple_dbs-10     B/op               B/op vs base
			  			       44.82Mi ± 11%      27.47Mi ± 6%  -38.71% (p=0.000 n=10)

ORMQueries/liquibase_migrations_on_multiple_dbs-10     allocs/op          allocs/op vs base
			 			       407.3k  ± 15%      253.7k ± 4%   -37.71% (p=0.000 n=10)
```

Benchmarks from single database test:
```
ORMQueries/liquibase_migrations-10     sec/op             sec/op vs base
                                       9.86m    ± 1%      14.29m ± 4%   -28.06% (p=0.000 n=10)

ORMQueries/liquibase_migrations-10     roundtrips         roundtrips vs base
                                       3.000    ± 0%      4.000 ± 0%    +33.33% (p=0.000 n=10)

ORMQueries/liquibase_migrations-10     B/op               B/op vs base
                                       11.739Mi ± 2%      7.606Mi ± 5%  -35.20% (p=0.000 n=10)

ORMQueries/liquibase_migrations-10     allocs/op          allocs/op vs base
			 	       107.51k  ± 4%      67.53k ± 8%   -37.19% (p=0.000 n=10)
```

Epic: none
Fixes: https://github.com/cockroachdb/cockroach/issues/114822

Release note: None

### CODE REVIEW

**Comment by annrpom** [comment]
Note: the amount of roundtrips increases by 1 with the new change, but this doesn't seem to affect the overall impact of this change (i.e. even with a setup of a single database, the speed of the benchmark query is improved by database-aware scans)

**Review by rafiss — APPROVED** [review]
this is great work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114993#-:-NkMo9Vv4ZttopzmpRex:b-41aws)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by fqazi — APPROVED** [review]
:lgtm:

One minor comment

> Reviewed 2 of 2 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114993#-:-NkMpQ77D3zle_QVX85a:b-bzoufr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @annrpom)

___
*[`pkg/sql/catalog/internal/catkv/testdata/testdata_app` line 448 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114993#-NkMpGWp2TffdjDKqRum:-NkMpGWp2TffdjDKqRun:bsdrw06) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f1268c6745146786a76798a7fd30a4ef5d6d812/pkg/sql/catalog/internal/catkv/testdata/testdata_app#L448)):*
> ```
> # Scanning all comments after resetting should only
> # give us comments
> scan_all_comments db_id=100
> ```

May be have coverage for the case where we don't have an ID too
___
*[`pkg/bench/rttanalysis/orm_queries_bench_test.go` line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114993#-NkMpNLk1uCa7vsgcYCk:-NkMpNLk1uCa7vsgcYCl:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/25fa16f3c8edafd780c37c0cc6bc54f8a7873537/pkg/bench/rttanalysis/orm_queries_bench_test.go#L21)):*
> ```Go
> func BenchmarkORMQueries(b *testing.B) { reg.Run(b) }
> func init() {
> 	liquibaseSetup, liquibaseReset := buildNDatabasesWithMTables(15, 40)
> ```

Nice!

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114993)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/catalog/internal/catkv/testdata/testdata_app` line 448 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114993#-NkMpGWp2TffdjDKqRum:-NkMwDom-QI8sqtrXzLV:bmenfe0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f1268c6745146786a76798a7fd30a4ef5d6d812/pkg/sql/catalog/internal/catkv/testdata/testdata_app#L448)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

May be have coverage for the case where we don't have an ID too
</blockquote></details>

Good point - done. Couldn't get it to work with how we parse arguments right now (maybe I'm just being silly), but found a workaround for now

**Comment by annrpom** [comment]
TFTRs! ('-')7

bors r=rafiss, fqazi

**Comment by annrpom** [comment]
facepalm. now we're good - new test pushed. wanted to touch up a comment or two as well

TFTRs! ('-')7

bors r=rafiss, fqazi

**Pull request merged**
