### PR TITLE
roachtest: deflake cdc/initial-scan-rolling-restart/shutdown-checkpoint

### LINKED ISSUE #124547: roachtest: cdc/initial-scan-rolling-restart/shutdown-checkpoint failed
roachtest.cdc/initial-scan-rolling-restart/shutdown-checkpoint [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/15356582?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/15356582?buildTab=artifacts#/cdc/initial-scan-rolling-restart/shutdown-checkpoint) on master @ [8156d095961d7271df61fe2e2f716ef072bc5f96](https://github.com/cockroachdb/cockroach/commits/8156d095961d7271df61fe2e2f716ef072bc5f96):

```
(test_runner.go:1253).runTest: test timed out (15m0s)
test artifacts and logs in: /artifacts/cdc/initial-scan-rolling-restart/shutdown-checkpoint/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-15356582/cdc-initial-scan-rolling-restart-shutdown-checkpoint/1716357438051/1716358496578)

</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/initial-scan-rolling-restart/shutdown-checkpoint.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-38948

### PR DESCRIPTION
**Pull request by andyyang890**
Fixes #124547

Release note: None

### CODE REVIEW

**Review by asg0451 — APPROVED** [review]

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125765)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andyyang890, @nameisbhaskar, and @vidit-bhat)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1052 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125765#-O-axwh29sZkdoGGNrHh:-O-axwh29sZkdoGGNrHi:b-eoxmmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8b5bb0ef57b5f79e2c4898890bb534a9ca0b0da/pkg/cmd/roachtest/tests/cdc.go#L1052)):*
> ```Go
> 					return err
> 				}
> 				restartDur := timeutil.Since(start)
> ```

Why did you decide to wait for the time that the last restart took instead of a constant time between restarts?

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125765)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nameisbhaskar, @rharding6373, and @vidit-bhat)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1052 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125765#-O-axwh29sZkdoGGNrHh:-O-bMy5yBT6xjTdYWbLU:b9c413l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8b5bb0ef57b5f79e2c4898890bb534a9ca0b0da/pkg/cmd/roachtest/tests/cdc.go#L1052)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Why did you decide to wait for the time that the last restart took instead of a constant time between restarts?
</blockquote></details>

No particular reason, I thought it might be good to have it be dynamic in case we get a really slow server. I guess ideally I'd like to quantify how long it takes for a changefeed to plan and make some progress but I wasn't sure what a good way to measure that would be.

In my own empirical observations, a restart takes about 6-7s. I could change it to a static time or maybe `max(restartDur, <some fixed time>)`? WDYT?

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125765)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andyyang890, @nameisbhaskar, and @vidit-bhat)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1052 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125765#-O-axwh29sZkdoGGNrHh:-O-bxsSW1QMih09QCe27:b76xrv9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8b5bb0ef57b5f79e2c4898890bb534a9ca0b0da/pkg/cmd/roachtest/tests/cdc.go#L1052)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

No particular reason, I thought it might be good to have it be dynamic in case we get a really slow server. I guess ideally I'd like to quantify how long it takes for a changefeed to plan and make some progress but I wasn't sure what a good way to measure that would be.

In my own empirical observations, a restart takes about 6-7s. I could change it to a static time or maybe `max(restartDur, <some fixed time>)`? WDYT?
</blockquote></details>

restartDur doesn't seem like it captures information about planning and progress, does it? I would consider either a fixed time (maybe 10s) that we could lengthen if this turns out to be flaky, or monitor the changefeed job (hwm increased after the restart).

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125765)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nameisbhaskar, @rharding6373, and @vidit-bhat)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1052 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125765#-O-axwh29sZkdoGGNrHh:-O-c7ssd18uaQVt953D8:buxh28a) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8b5bb0ef57b5f79e2c4898890bb534a9ca0b0da/pkg/cmd/roachtest/tests/cdc.go#L1052)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

restartDur doesn't seem like it captures information about planning and progress, does it? I would consider either a fixed time (maybe 10s) that we could lengthen if this turns out to be flaky, or monitor the changefeed job (hwm increased after the restart).
</blockquote></details>

Changed to 10s. Monitoring the changefeed highwater wouldn't work here since the changefeeds are initial-scan-only.

**Review by rharding6373 — APPROVED** [review]
:lgtm: Nice find!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125765#-:-O-cLD6x0Xb-QwABNdO6:bcdfsno)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nameisbhaskar and @vidit-bhat)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1052 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125765#-O-axwh29sZkdoGGNrHh:-O-cKue33UfoDztJEBgm:bt0g4s3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8b5bb0ef57b5f79e2c4898890bb534a9ca0b0da/pkg/cmd/roachtest/tests/cdc.go#L1052)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Changed to 10s. Monitoring the changefeed highwater wouldn't work here since the changefeeds are initial-scan-only.
</blockquote></details>

Ah, good point. Could probably track something like backfill pending ranges instead, but this is fine with me.

**Comment by andyyang890** [comment]
TFTR!

bors r=asg0451,rharding6373

**Comment by andyyang890** [comment]
Not sure why bors didn't pick it up.

bors r=asg0451,rharding6373

**Pull request merged**
