### PR TITLE
build: fix bugs in roachtest scripts

### PR DESCRIPTION
**Pull request by tbg**
TODO once this merges:

- [x] update [GCE build] to not hard-code this PR's branch (but `master`)
- [ ] put the script in [GCE build] in a template that is shared with the [AWS build] (which retains the old script; it needs to be switched over completely still).

[GCE build]: https://teamcity.cockroachdb.com/admin/editBuild.html?init=1&id=buildType%3ACockroach_Nightlies_WorkloadNightly&cameFromUrl=%2FviewQueued.html%3FitemId%3D1877809&branch_Cockroach_Nightlies=%3Cdefault%3E
[AWS build]: https://teamcity.cockroachdb.com/admin/editRunType.html?id=buildType:Cockroach_Nightlies_RoachtestNightlyAws&runnerId=RUNNER_39&cameFromUrl=%2Fadmin%2FeditBuildRunners.html%3Fid%3DbuildType%253ACockroach_Nightlies_RoachtestNightlyAws%26init%3D1&cameFromTitle=

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
A build using this PR is running at https://teamcity.cockroachdb.com/viewLog.html?buildId=1877809&buildTypeId=Cockroach_Nightlies_WorkloadNightly&tab=buildLog&branch_Cockroach_Nightlies=%3Cdefault%3E

It's already in roachtest, so the only remaining question is if it'll upload the stats.json files correctly.

**Review by jlinder — APPROVED** [review]
:lgtm: modulo two questions.

I looked for the artifacts in google storage, but didn't find them. It looked like they'd be in the `cockroach-nightly` bucket under the `cockroach-ephemeral` project. Where should they be?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47507#-:-M4yWSCf5zZOlSpo430y:b-te4val)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jlinder and @tbg)

___
*[build/teamcity-nightly-roachtest.sh, line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47507#-M4yW30-9zfV-tTdrB5p:-M4yW30-9zfV-tTdrB5q:bz3fk7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/959a7178733b6400ec7bdb8a256b00f9f8ebc60e/build/teamcity-nightly-roachtest.sh#L10)):*
> ```Shell
> # already exists in the current directory.
> COCKROACH_BINARY="$PWD/cockroach.linux-2.6.32-gnu-amd64"
> if [[ ! -x ./cockroach ]]; then
> ```

Am I correct that this was removed  because `${PWD}/cockroach.linux-2.6.32-gnu-amd64` must be there since the build configuration requires it being there and wouldn't have gotten there if the file wasn't there?

**Review by tbg — COMMENTED** [review]
Depends on which artifacts you mean. The build artifacts are stored in TeamCity (for example here: https://teamcity.cockroachdb.com/viewLog.html?buildId=1877809&buildTypeId=Cockroach_Nightlies_WorkloadNightly&tab=artifacts&branch_Cockroach_Nightlies=%3Cdefault%3E#%2Fencryption;%2Fengine;%2Fkv%2Fquiescence%2Fnodes%3D3%2Frun_1%2F1.logs;%2Fkv%2Fquiescence%2Fnodes%3D3%2Frun_1%2F3.logs)

The only artifacts we push to Google Storage are the perf stats.  See `gsutil ls gs://cockroach-nightly/artifacts{-aws}`. Did that help?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47507#-:-M4yXKeE6RaqdBA4cNGW:b-j7bpdj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jlinder)

___
*[build/teamcity-nightly-roachtest.sh, line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47507#-M4yW30-9zfV-tTdrB5p:-M4yXh0N9s6K1G68hjgM:brsj86u) ([raw file](https://github.com/cockroachdb/cockroach/blob/959a7178733b6400ec7bdb8a256b00f9f8ebc60e/build/teamcity-nightly-roachtest.sh#L10)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

Am I correct that this was removed  because `${PWD}/cockroach.linux-2.6.32-gnu-amd64` must be there since the build configuration requires it being there and wouldn't have gotten there if the file wasn't there?
</blockquote></details>

I removed it because I needed the `chmod +x`, which will fail if the file isn't there. The check that was removed was redundant with that.

**Review by tbg — COMMENTED** [review]
bors r=jlinder

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47507#-:-M524ur2DcaQIphnPdQJ:b-6izb8u)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jlinder)

___
*[build/teamcity-nightly-roachtest.sh, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47507#-M522x2m7Vd8eIbg_Hku:-M522x2m7Vd8eIbg_Hkv:bptwrem) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bfac238140e78cae39abedffe5f4c9b5d7adfe3/build/teamcity-nightly-roachtest.sh#L58)):*
> ```Shell
>       # `find` below will expand "{}" as ./path/to/test/stats.json.
>       (cd "${artifacts}" && find . -name stats.json -exec \
>         gsutil cp "{}" "gs://${bucket}/artifacts/${stats_dir}/{}" ';')
> ```

Had to change this to

```
(cd "${artifacts}" && \
while IFS= read -r f; do
  gsutil cp "${f}" "gs://${bucket}/artifacts/${stats_dir}/${f}"
done <<< "$(find . -name stats.json | sed 's/^\.\///')")

```

because `find .` returns all matches with a leading `./` and that makes gsutil cp create `.` folders...

I tested this locally on a dummy setup.

**Comment by tbg** [comment]
Merging this now. I updated the GCE build (i.e. it'll use master next time it runs) but I'm out of steam to update the AWS build. Will file issues for that.

**Comment by tbg** [comment]
Filed https://github.com/cockroachdb/dev-inf/issues/80.

**Comment by jlinder** [comment]
> _[build/teamcity-nightly-roachtest.sh, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47507#-M522x2m7Vd8eIbg_Hku:-M522x2m7Vd8eIbg_Hkv:bptwrem) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bfac238140e78cae39abedffe5f4c9b5d7adfe3/build/teamcity-nightly-roachtest.sh#L58)):_
> 
> > ```shell
> >       # `find` below will expand "{}" as ./path/to/test/stats.json.
> >       (cd "${artifacts}" && find . -name stats.json -exec \
> >         gsutil cp "{}" "gs://${bucket}/artifacts/${stats_dir}/{}" ';')
> > ```
> 
> Had to change this ...

Ah! Another way to do this is:

```
(cd "${artifacts}" && find $(pwd) -name stats.json -exec \
  gsutil cp "{}" "gs://${bucket}/artifacts/${stats_dir}/{}" ';')

```

**Comment by tbg** [comment]
Sure this would do the right thing? `find /some/absolute/path/x` as you suggest would bind `{}`to `/some/absolute/path/some/hit`, so you're calling

`gsutil cp /some/absolute/path/x/some/hit "gs://${bucket}/artifacts/${stats_dir}//some/absolute/path/x/some/hit"`

but you want

`gsutil cp /some/absolute/path/x/some/hit "gs://${bucket}/artifacts/${stats_dir}/x/some/hit".

**Comment by jlinder** [comment]
Drat. I focused on the local side. You are right.

**Pull request merged**
