### PR TITLE
kvserver: don't let closed timestamps squeeze writes

### PR DESCRIPTION
**Pull request by andreimatei**
Before this patch, we'd close up to the lease expiration. This is
particularly relevant for leading ranges, where the closed timestamp is
in the future of present time. On these ranges, it can easily happen
that, when either the Raft transport or the side transport wants to
close a timestamp, the lease is currently valid (relative to present
time), but the target closed is above the lease expiration. Before this
patch, this would result in closing up to the lease expiration.

This patch makes it so that we never close within the last (full)
nanosecond of the lease. If the lease expires at (10,20), we'll close at
most (9.0). This ensures that there's infinite (logical) time left for
writes to be pushed into, while staying within the lease validity.
Before this patch, writes would have been pushed above the lease
expiration. They would have executed there, which is not ok.

Release note: None
Release justification: Bug fix for new functionality.

### CODE REVIEW

**Review by nvb — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61559)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvserver/replica_closedts.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61559#-MV303dZ7lD88SwiuciY:-MV303dZ7lD88SwiuciZ:b8023tu) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e51c807e79c6f56ef66d8e69504c7a738091a15/pkg/kv/kvserver/replica_closedts.go#L106)):*
> ```Go
> 		return false, 0, 0
> 	}
> 	// We can't close timestamps within the same nanosecond as the lease
> ```

Can we add a test case for this in `TestBumpSideTransportClosed`?
___
*[pkg/kv/kvserver/replica_closedts.go, line 109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61559#-MV3-xraEmOilvYem_eV:-MV3-xraEmOilvYem_eW:bwejpjr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e51c807e79c6f56ef66d8e69504c7a738091a15/pkg/kv/kvserver/replica_closedts.go#L109)):*
> ```Go
> 	// expiration. To see why, check the comments on the similar logic in
> 	// propBuf.assignClosedTimestampToProposalLocked.
> 	upperBound := st.Expiration().FloorPrev()
> ```

`WallPrev`?
___
*[pkg/util/hlc/timestamp.go, line 273 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61559#-MV3-pqIEcwOnTcW0lJk:-MV3-pqJ19Ya-ewY2Jwx:b-x6w7d0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e51c807e79c6f56ef66d8e69504c7a738091a15/pkg/util/hlc/timestamp.go#L273)):*
> ```Go
> }
> 
> // WallPrev subtracts 1 from the WallTime and resets Logical.
> ```

Add a test for this in `timestamp_test.go`. Like `TestTimestampFloorPrev`.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61559)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/kv/kvserver/replica_closedts.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61559#-MV303dZ7lD88SwiuciY:-MV3OFUTCqNic6FMgLoM:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e51c807e79c6f56ef66d8e69504c7a738091a15/pkg/kv/kvserver/replica_closedts.go#L106)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we add a test case for this in `TestBumpSideTransportClosed`?
</blockquote></details>

done
___
*[pkg/kv/kvserver/replica_closedts.go, line 109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61559#-MV3-xraEmOilvYem_eV:-MV3OG8x4XH5b9nEBJYM:b-535ue0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e51c807e79c6f56ef66d8e69504c7a738091a15/pkg/kv/kvserver/replica_closedts.go#L109)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`WallPrev`?
</blockquote></details>

done :)
___
*[pkg/util/hlc/timestamp.go, line 273 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61559#-MV3-pqIEcwOnTcW0lJk:-MV3TSDzEee5zF63b_Q_:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e51c807e79c6f56ef66d8e69504c7a738091a15/pkg/util/hlc/timestamp.go#L273)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Add a test for this in `timestamp_test.go`. Like `TestTimestampFloorPrev`.
</blockquote></details>

done

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61559#-:-MVIDK6XC-kKn2voZnKZ:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by andreimatei** [comment]
flaked on #60300

bors r+

**Review by nvb — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 6 files at r4, 1 of 1 files at r5, 5 of 6 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61559#-:-MVI_2Bd3-alhKhnz5aq:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Pull request merged**
