### PR TITLE
workload/movr: initial implementation of MovR workload.Generator

### PR DESCRIPTION
**Pull request by danhhz**
This is a partial port of the cockroachdb/movr project to a
workload.Generator to enable easier large-scale testing (and integration
with our cli commands, like `cockroach demo`). Only the initial data
load is supported for now; use the official MovR port for queryload.

Release note: None

### CODE REVIEW

**Comment by danhhz** [comment]
@nstewart I could keep going on making this more exactly match the reference impl, but I was thinking that this might be close enough to be mergeable. Then we can do any fixes (the dates and times are a little different and maybe we could port a small bit of the faker lib) as incremental improvements. Thoughts?

**Comment by nstewart** [comment]
Can you add a release note cc @jseldess

**Comment by nstewart** [comment]
LGTM -- I can test it with the movr image and provide feedback on master

**Comment by danhhz** [comment]
Thanks for the review!

bors r=nstewart

**Comment by danhhz** [comment]
Resolved merge conflict

bors r=nstewart

**Pull request merged**
