### PR TITLE
[CC-24092] cluster-ui: lint for usages of console logging

### PR DESCRIPTION
**Pull request by fantapop**
In order to provide more structured error data in management-console, setLogger and getLogger methods were previously added to cluster-ui. They allow the logger to be overridden when used from the cloud. The benefits rely on using the new methods in console-ui instead of console logging methods.  This change adds a lint rule to ensure console logging methods are not used.

Release note: none
Epic: none

### CODE REVIEW

**Review by sjbarag — APPROVED** [review]
Looks good! I'm a little surprised the initial value for `getLogger()` didn't trigger this 😃

**Comment by sjbarag** [comment]
To fix the "blathers/lint-epic-issue-refs" check, you'll need to add "Epic: none" to the commit message as well IIRC

**Comment by fantapop** [comment]
It's a good thing its easier to do this:

// eslint-disable-next-line no-console
console.info("hi");

than this:

const cons0le = console;
cons0le.info("hi");

**Pull request merged**
