### PR TITLE
sql: tag crash reports with relevant statement

### LINKED ISSUE #22865: sql: Include query in "leftover bytes" report
#22685 changed the "unexpected leftover bytes" assertion to only report to Sentry rather than panic in release builds. But now those reports no longer include the relevant SQL statement, which limits how useful the reports are. Find a way to include the statement, probably by passing it down through a context.

### PR DESCRIPTION
**Pull request by solongordon**
Our Sentry reports now include an anonymized version of the relevant SQL
statement if it is set in the context, and I modified connExecutor to
add the statement to the context whenever curStmt is set. This means
that "unexpected leftover bytes" reports now include the statement
again. (The statement stopped being reported when we changed that from a
panic to a warning in 91ed508.)

Fixes #22865

Release note: None

### CODE REVIEW

**Comment by solongordon** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/conn_executor.go, line 504 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23278#-L6Y-PlNaRgP8xSpgjO6:-L6Y-PlNaRgP8xSpgjO7:b-ooyndl) ([raw file](https://github.com/cockroachdb/cockroach/blob/32de3bcad975a5fd6bbf28fd9ebf40ba5beb4fe1/pkg/sql/conn_executor.go#L504)):*
> ```Go
> 		ex.state.Ctx = log.RemoveAnonymizedStatement(ex.state.Ctx)
> 	} else {
> 		anonStmt := tree.AsStringWithFlags(stmt, tree.FmtAnonymize|tree.FmtHideConstants)
> ```

I'd rather only build the anonymized statement when it's needed, but I couldn't figure out how to do this without causing an import cycle between `sql` and `util/log`.

---

*[pkg/sql/conn_executor.go, line 505 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23278#-L6Xzwnzd_f--zdjmOgq:-L6Xzwo-jlt-fiZtq884:bqfo0nh) ([raw file](https://github.com/cockroachdb/cockroach/blob/32de3bcad975a5fd6bbf28fd9ebf40ba5beb4fe1/pkg/sql/conn_executor.go#L505)):*
> ```Go
> 	} else {
> 		anonStmt := tree.AsStringWithFlags(stmt, tree.FmtAnonymize|tree.FmtHideConstants)
> 		ex.state.Ctx = log.WithAnonymizedStatement(ex.state.Ctx, anonStmt)
> ```

Is it poor form to hijack the context for this purpose? It feels icky, but I couldn't find a better way of passing the statement all the way down to where it needs to be reported (`BytesMonitor.doStop`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23278)*

**Comment by andreimatei** [comment]
I think that putting the statement in the context is a great idea.
I'm not sure about including it in sentry reports, though. I think we should be more paranoid about the data we collect. I'm afraid we're going to screw something up and not anonymize properly.
I think we should put the non-anonymized query in the log when we crash and invite people to file an issue. The anonymized one is probably not helping us much anyway.
What do you think?

Is this really expected to help with #22865? Do the panics about leftover bytes happen while running a statement - i.e. do we have any per-statement monitors? I assumed they only happen when the session is terminated, no?

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/conn_executor.go, line 497 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23278#-L6Z2let4HJrHbfVmBDG:-L6Z2let4HJrHbfVmBDH:b-tfokfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/32de3bcad975a5fd6bbf28fd9ebf40ba5beb4fe1/pkg/sql/conn_executor.go#L497)):*
> ```Go
> )
> 
> // setCurStmt sets ex.curStmt and stores an anonymized version of the statement
> ```

pls comment that stmt can be nil

---

*[pkg/sql/conn_executor.go, line 502 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23278#-L6Z3JhsH6norihe5lqv:-L6Z3JhsH6norihe5lqw:b-hoah5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/32de3bcad975a5fd6bbf28fd9ebf40ba5beb4fe1/pkg/sql/conn_executor.go#L502)):*
> ```Go
> 	ex.curStmt = stmt
> 	if stmt == nil {
> 		ex.state.Ctx = log.RemoveAnonymizedStatement(ex.state.Ctx)
> ```

I think what you're doing here is no bueno - you keep deriving contexts, adding a new level to the chain of contexts every time this method is called (right)? Contexts are immutable; every time you set a value you get a new one linking to the parent.
Instead, you want to save the original context somewhere and restore it.

---

*[pkg/sql/conn_executor.go, line 504 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23278#-L6Y-PlNaRgP8xSpgjO6:-L6Z598yeY7HtYWm6pzl:b32cb2p) ([raw file](https://github.com/cockroachdb/cockroach/blob/32de3bcad975a5fd6bbf28fd9ebf40ba5beb4fe1/pkg/sql/conn_executor.go#L504)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

I'd rather only build the anonymized statement when it's needed, but I couldn't figure out how to do this without causing an import cycle between `sql` and `util/log`.
</blockquote></details>

what you can do is have the log package export a setter for a function producing the anonymized string, say `RegisterReportHelper(ctx) string` and call it from an `init()` function defined in this file - `init()` functions run at startup. We do this sort of thing elsewhere.
This way, the log package wouldn't need to know anything about anonymized statements, so all the context manipulations functions could move here.

---

*[pkg/sql/conn_executor.go, line 505 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23278#-L6Xzwnzd_f--zdjmOgq:-L6Z4XYql6KCxloVz3p4:b-kdluk2) ([raw file](https://github.com/cockroachdb/cockroach/blob/32de3bcad975a5fd6bbf28fd9ebf40ba5beb4fe1/pkg/sql/conn_executor.go#L505)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Is it poor form to hijack the context for this purpose? It feels icky, but I couldn't find a better way of passing the statement all the way down to where it needs to be reported (`BytesMonitor.doStop`).
</blockquote></details>

I think using the context for saving the statement is a good thing. I wished we had this before.

I don't think you can modify `ex.state.Ctx` like this, though. This will race with statements being executed through the parallel queue when they want to use `ex.state.Ctx`. Stuff inside `state` should generally only be mutated by the state machine in `conn_fsm.go`. 
I think what you want to do is create a per-statement context and pass that to `ex.execStmt()`. This way there's nothing to restore.

---

*[pkg/util/log/crash_reporting.go, line 479 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23278#-L6Z5sQ3MOxPc8JwmL52:-L6Z5sQ3MOxPc8JwmL53:b265nl7) ([raw file](https://github.com/cockroachdb/cockroach/blob/32de3bcad975a5fd6bbf28fd9ebf40ba5beb4fe1/pkg/util/log/crash_reporting.go#L479)):*
> ```Go
> // anonymized) to the provided context. The statement will then be included in
> // crash reports which use that context.
> func WithAnonymizedStatement(ctx context.Context, stmt string) context.Context {
> ```

it's common practice to also define a `AnonymizedStatementFromCtx` function next to this guy, returning the typed value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23278#-:-L6Z69LSo0KF0mxwIOR1:bjoj4ei)*

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/conn_executor.go, line 504 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23278#-L6Y-PlNaRgP8xSpgjO6:-L6_BB-BC-PE3x3DCaH1:b-1y4981) ([raw file](https://github.com/cockroachdb/cockroach/blob/32de3bcad975a5fd6bbf28fd9ebf40ba5beb4fe1/pkg/sql/conn_executor.go#L504)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what you can do is have the log package export a setter for a function producing the anonymized string, say `RegisterReportHelper(ctx) string` and call it from an `init()` function defined in this file - `init()` functions run at startup. We do this sort of thing elsewhere.
This way, the log package wouldn't need to know anything about anonymized statements, so all the context manipulations functions could move here.
</blockquote></details>

we often already have a copy of the anonymized statement i think, since we use that as the key for stat collection, in the in the `AnonymizedStr` field of `sql.Statement`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23278)*

**Comment by dt** [comment]
If the statement isn't anonymized properly, we'd already have a problem in the diagnostics reports, and if they're disabled, crash reports are too, so I don't think this significantly changes the risk of reporting something that shouldn't be reported. 

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23278#-:-L6b3RurKKHtS0UuE3FA:bnqtsys)*

**Comment by solongordon** [comment]
I think the issue with just logging the query is that this is for warnings we want reports on but which will be mostly silent to the user. So we would depend on someone both noticing the warning in the logs and filing an issue, which seems unreliable.

Re #22865, I think we do have some statement-specific monitors, for instance on distsql flows. But that's a good point that I should make sure this doesn't produce confusing results for less granular monitors like the session one.

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/conn_executor.go, line 502 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23278#-L6Z3JhsH6norihe5lqv:-L6bLM68KjLYk--ALFYb:b-a7nhi5) ([raw file](https://github.com/cockroachdb/cockroach/blob/32de3bcad975a5fd6bbf28fd9ebf40ba5beb4fe1/pkg/sql/conn_executor.go#L502)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think what you're doing here is no bueno - you keep deriving contexts, adding a new level to the chain of contexts every time this method is called (right)? Contexts are immutable; every time you set a value you get a new one linking to the parent.
Instead, you want to save the original context somewhere and restore it.
</blockquote></details>

Got it, makes sense that if I use contexts correctly I shouldn't have to "unset" a value.

---

*[pkg/sql/conn_executor.go, line 504 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23278#-L6Y-PlNaRgP8xSpgjO6:-L6bOj0fGBU-Us-3vPJa:b-l5254e) ([raw file](https://github.com/cockroachdb/cockroach/blob/32de3bcad975a5fd6bbf28fd9ebf40ba5beb4fe1/pkg/sql/conn_executor.go#L504)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

we often already have a copy of the anonymized statement i think, since we use that as the key for stat collection, in the in the `AnonymizedStr` field of `sql.Statement`
</blockquote></details>

I initially tried using `AnonymizedStr` but it didn't seem to be set when I needed it. I'll take another look to try and figure out when I can expect it to be set.

---

*[pkg/sql/conn_executor.go, line 505 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23278#-L6Xzwnzd_f--zdjmOgq:-L6bKL4fBFeHAmWYZNdt:b-5ii68q) ([raw file](https://github.com/cockroachdb/cockroach/blob/32de3bcad975a5fd6bbf28fd9ebf40ba5beb4fe1/pkg/sql/conn_executor.go#L505)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think using the context for saving the statement is a good thing. I wished we had this before.

I don't think you can modify `ex.state.Ctx` like this, though. This will race with statements being executed through the parallel queue when they want to use `ex.state.Ctx`. Stuff inside `state` should generally only be mutated by the state machine in `conn_fsm.go`. 
I think what you want to do is create a per-statement context and pass that to `ex.execStmt()`. This way there's nothing to restore.
</blockquote></details>

Ah that makes sense. So just add the statement to `ex.Ctx()` before passing it to `execStmt()`, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23278#-:-L6bM6RsaC35kpX0HBVq:bd33cd6)*

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/conn_executor.go, line 504 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23278#-L6Y-PlNaRgP8xSpgjO6:-L6bTe2OjXFir9MZQ_Iv:bllec3k) ([raw file](https://github.com/cockroachdb/cockroach/blob/32de3bcad975a5fd6bbf28fd9ebf40ba5beb4fe1/pkg/sql/conn_executor.go#L504)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

I initially tried using `AnonymizedStr` but it didn't seem to be set when I needed it. I'll take another look to try and figure out when I can expect it to be set.
</blockquote></details>

it is set for prepared statements I think... we could just always set it though I think @knz?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23278)*

**Comment by solongordon** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/conn_executor.go, line 504 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23278#-L6Y-PlNaRgP8xSpgjO6:-L6r4X2TU3p7Q1GSOF5h:bkoqx97) ([raw file](https://github.com/cockroachdb/cockroach/blob/32de3bcad975a5fd6bbf28fd9ebf40ba5beb4fe1/pkg/sql/conn_executor.go#L504)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

it is set for prepared statements I think... we could just always set it though I think @knz?
</blockquote></details>

I implemented the `init` setter approach for now, which I think works nicely. There may be some redundant anonymization logic now though.

---

*[pkg/sql/conn_executor.go, line 505 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23278#-L6Xzwnzd_f--zdjmOgq:-L6r4VDtlvak41jIeq6W:b-4kcfma) ([raw file](https://github.com/cockroachdb/cockroach/blob/32de3bcad975a5fd6bbf28fd9ebf40ba5beb4fe1/pkg/sql/conn_executor.go#L505)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Ah that makes sense. So just add the statement to `ex.Ctx()` before passing it to `execStmt()`, right?
</blockquote></details>

I remember now that this doesn't work because the context passed to `execStmt` isn't the one which is used to stop the BytesMonitor:
https://github.com/cockroachdb/cockroach/blob/3e28ade818825d6aac302840864925c0e106166b/pkg/sql/txn_state.go#L217-L218

I'll look for another solution though since it's clear that mutating `ex.state.Ctx` is no good.

---

*[pkg/util/log/crash_reporting.go, line 479 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23278#-L6Z5sQ3MOxPc8JwmL52:-L6r3BFmjmEnA1rcOxQq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/32de3bcad975a5fd6bbf28fd9ebf40ba5beb4fe1/pkg/util/log/crash_reporting.go#L479)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

it's common practice to also define a `AnonymizedStatementFromCtx` function next to this guy, returning the typed value.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23278)*

**Comment by andreimatei** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/conn_executor.go, line 505 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23278#-L6Xzwnzd_f--zdjmOgq:-L6rT1Qwrki1frpFQMBG:b-bhramp) ([raw file](https://github.com/cockroachdb/cockroach/blob/32de3bcad975a5fd6bbf28fd9ebf40ba5beb4fe1/pkg/sql/conn_executor.go#L505)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

I remember now that this doesn't work because the context passed to `execStmt` isn't the one which is used to stop the BytesMonitor:
https://github.com/cockroachdb/cockroach/blob/3e28ade818825d6aac302840864925c0e106166b/pkg/sql/txn_state.go#L217-L218

I'll look for another solution though since it's clear that mutating `ex.state.Ctx` is no good.
</blockquote></details>

If you want, I'll be in the office tomorrow and we can talk about things. I have a bunch of context management stuff paged in, so I'm probably a good person to talk about it with.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23278)*

**Comment by solongordon** [comment]
@andreimatei It ended up not working out very well to add the statement to the state machine `Args` since they live in another package and are more generic than I realized. But it turned out to be pretty straightforward to piggyback on the transaction context (though not as semantically accurate as adding a statement-specific one.) Let me know if you think this is reasonable for now.

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23278#-:-L7033Lx4O-l3xHH4J3k:by82tcy)*

**Comment by andreimatei** [comment]
Everything here LGTM, but this PR doesn't do anything about the panics from DistSQL (which I thought were the motivation for this whole thing), right?

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23278#-:-L772e6pVlvNa9nmkZjX:bhc23jz)*

**Comment by andreimatei** [comment]
I think we really should have some sort of test checking the anonymizing of these queries. I guess an acceptance test where look at a report would be great, or if not at least a unit test for that tagging function.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23278#-:-L7742xar-sPO9T68J7C:b9qh3gp)*

**Comment by solongordon** [comment]
Yeah, you're right that this will not report the query for flows that aren't on the gateway node. But I believe that's already the case for panics, and the main goal of this ticket was to bring back query reporting for the thing I changed from a panic to a warning. If it's ok with you, I'll make a separate ticket to propagate queries to remote distsql nodes for reporting.

I'll add a test for the anonymization.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23278#-:-L7e-75jA0poWt5hdQtV:b-rpbffs)*

**Comment by andreimatei** [comment]
LGTM

**Comment by solongordon** [comment]
I shared my anonymize function with `AnonymizeStatementsForReporting` so it's now covered by that function's tests.

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23278#-:-L7egP-96_ZP0-ptwNRg:bxepenk)*

**Pull request merged**
