### PR TITLE
sql: fix a comment

### PR DESCRIPTION
**Pull request by knz**
This incorrect comment was introduced in #75747.
Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
thanks!

**Comment by knz** [comment]
bors r=rafiss

**Comment by knz** [comment]
bors cancel

**Comment by rafiss** [comment]
this caused https://github.com/cockroachdb/cockroach/issues/93700

**Comment by knz** [comment]
> this caused https://github.com/cockroachdb/cockroach/issues/93700

how come we're filing issues on failed bors runs?

**Comment by rafiss** [comment]
I was mistaken. I was viewing the wrong link

**Comment by knz** [comment]
bors r=rafiss

**Comment by knz** [comment]
bors cancel

**Comment by knz** [comment]
bors r=rafiss

**Comment by knz** [comment]
bors r=rafiss

**Pull request merged**
