### PR TITLE
[serverccl] Fix flaky tenant status test.

### LINKED ISSUE #72079: ccl/serverccl: TestTenantCannotSeeNonTenantStats failed
ccl/serverccl.TestTenantCannotSeeNonTenantStats [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3647637&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3647637&tab=artifacts#/) on master @ [d91fead28392841a943251842fbd43a0affb2eca](https://github.com/cockroachdb/cockroach/commits/d91fead28392841a943251842fbd43a0affb2eca):

```
=== RUN   TestTenantCannotSeeNonTenantStats
    test_log_scope.go:79: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestTenantCannotSeeNonTenantStats745513442
    test_log_scope.go:80: use -show-logs to present logs inline
=== CONT  TestTenantCannotSeeNonTenantStats
    tenant_status_test.go:206: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestTenantCannotSeeNonTenantStats745513442
--- FAIL: TestTenantCannotSeeNonTenantStats (2.86s)
=== RUN   TestTenantCannotSeeNonTenantStats/tenant-stats
    tenant_status_test.go:170: 
        	Error Trace:	tenant_status_test.go:165
        	            				tenant_status_test.go:170
        	Error:      	Not equal: 
        	            	expected: []string{"CREATE DATABASE roachblog_t", "CREATE TABLE posts_t (id INT8 PRIMARY KEY, body STRING)", "INSERT INTO posts_t VALUES (_, '_')", "SELECT * FROM posts_t", "SET database = roachblog_t"}
        	            	actual  : []string(nil)
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,8 +1,2 @@
        	            	-([]string) (len=5) {
        	            	- (string) (len=27) "CREATE DATABASE roachblog_t",
        	            	- (string) (len=55) "CREATE TABLE posts_t (id INT8 PRIMARY KEY, body STRING)",
        	            	- (string) (len=35) "INSERT INTO posts_t VALUES (_, '_')",
        	            	- (string) (len=21) "SELECT * FROM posts_t",
        	            	- (string) (len=26) "SET database = roachblog_t"
        	            	-}
        	            	+([]string) <nil>
        	            	 
        	Test:       	TestTenantCannotSeeNonTenantStats/tenant-stats
    --- FAIL: TestTenantCannotSeeNonTenantStats/tenant-stats (0.00s)
```
<details><summary>Help</summary>
<p>
See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)Parameters in this failure:

- GOFLAGS=-parallel=4
</p>
</details>
/cc @cockroachdb/server Azhng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTenantCannotSeeNonTenantStats.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by rimadeodhar**
The Statements method on the tenant status server
relies on the sqlinstance system to retrieve SQL
pod information. The sqlinstance system was updated
recently to cache SQL pod data backed by a rangefeed.
This caused the tenant status test to fail occasionally
with make stress as there could be a race between
when the cache is populated and the statements are
queried. This PR updates the test to ensure this race
condition is eliminated.

Release note: None
Fixes: https://github.com/cockroachdb/cockroach/issues/72079

### CODE REVIEW

**Review by Azhng — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72408#-:-MnbWVkd6D5YZskvOMP9:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng and @rimadeodhar)

___
*[pkg/ccl/serverccl/tenant_status_test.go, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72408#-MnbWQJk7PI-2RkSSKaH:-MnbWQJk7PI-2RkSSKaI:b-uce31w) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b04f3da5568024ce4de04e695040ca4cb98e543/pkg/ccl/serverccl/tenant_status_test.go#L136)):*
> ```Go
> 		}
> 		if tenantStats == nil || len(tenantStats.Statements) == 0 {
> 			return errors.Newf("tenant statements are unexpectedly empty")
> ```

nit: do we need to use `Newf` here?

**Review by rimadeodhar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72408)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/ccl/serverccl/tenant_status_test.go, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72408#-MnbWQJk7PI-2RkSSKaH:-MnbZIXb87HEu9w9fjJc:b3zcd7o) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b04f3da5568024ce4de04e695040ca4cb98e543/pkg/ccl/serverccl/tenant_status_test.go#L136)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: do we need to use `Newf` here? 
</blockquote></details>

Nope, we don't. Will modify it before merging.

**Comment by rimadeodhar** [comment]
TFTR!

bors r= azhng

**Comment by Azhng** [comment]
blathers backport 21.2

**Pull request merged**
