### PR TITLE
WIP: libroach: Use protobuf arena to control block (de)allocation.

### PR DESCRIPTION
**Pull request by mberhault**
This is still a WIP. At the very least, this needs the following:
- ensure builds succeed on all targets
- figure out how to build with `MADV_DONTDUMP` available on linux

Using the arena is left for a follow-up PR.

Using the arena allows us to setup wrappers around block (de)allocators.
We call mlock/madvise on a per-page basis (these call do not stack and
on some systems require page alighment) and keep track of how many
references we have per page.

Upon deallocation, we also fill the memory with random bytes.

Release note: None

### CODE REVIEW

**Review by bdarnell — COMMENTED** [review]
Setting RLIMIT_CORE to zero to disable core dumps entirely is probably a better solution than setting MADV_DONTDUMP on the key pages. Users of encryption won't want any core dumps to be written because they'll be full of the decrypted data. (Would the same argument mean that encryption users should disable swap and then we don't need to worry about mlock either?)

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27276#-:-LGzkBklCj-lm0XWpVsu:big27mq)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[c-deps/libroach/ccl/db.cc, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27276#-LGzdMYiCy_1E4HM7pob:-LGzdMYiCy_1E4HM7poc:b-fw9tsy) ([raw file](https://github.com/cockroachdb/cockroach/blob/757c0058aeae6a2beeb0f034188013cf6818ce36/c-deps/libroach/ccl/db.cc#L132)):*
> ```cpp
>   auto status = CanLockPages();
>   if (!status.ok()) {
>     // Shout loudly on standard out.
> ```

s/out/err/, but it would be even better to send this to the logs. Stdout/stderr are not necessarily collected anywhere useful or visible. 

Can we make this a fatal error or are there important platforms where we want to be able to support encryption where we can't lock pages?
___
*[c-deps/libroach/ccl/key_arena.h, line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27276#-LGzeJhK4riiY7zxTVrk:-LGzeJhK4riiY7zxTVrl:b-4z1ock) ([raw file](https://github.com/cockroachdb/cockroach/blob/757c0058aeae6a2beeb0f034188013cf6818ce36/c-deps/libroach/ccl/key_arena.h#L14)):*
> ```objc
> #include <rocksdb/status.h>
> 
> // The returned Arena performs the following:
> ```

Add a comment saying specifically that this arena doesn't do the fast batch-allocation that arenas are typically used for and that we're just using the arena interface to get the appropriate hooks. 
___
*[c-deps/libroach/ccl/key_arena.h, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27276#-LGzeawz0WZeoceVfXjm:-LGzeawz0WZeoceVfXjn:b-9y4es6) ([raw file](https://github.com/cockroachdb/cockroach/blob/757c0058aeae6a2beeb0f034188013cf6818ce36/c-deps/libroach/ccl/key_arena.h#L21)):*
> ```objc
> // - munlock pages
> // - madvise(MADV_DODUMP) to re-enable inclusion in core dumps
> // - overwrite memory with random bytes
> ```

Why random? The [CERT security guidelines](https://wiki.sei.cmu.edu/confluence/display/c/MEM06-C.+Ensure+that+sensitive+data+is+not+written+out+to+disk) just zero-fill. I know random overwriting is recommended for disk but I'm not aware of similar concerns for memory. 

That page is also slightly skeptical of the value of `mlock()`. 
___
*[c-deps/libroach/ccl/key_arena.cc, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27276#-LGziofs2EplgMQOvksJ:-LGziofs2EplgMQOvksK:bxuc771) ([raw file](https://github.com/cockroachdb/cockroach/blob/757c0058aeae6a2beeb0f034188013cf6818ce36/c-deps/libroach/ccl/key_arena.cc#L97)):*
> ```cpp
> 
>     if (increment) {
>       // We don't have a good way to surface mlock/madvise errors. Log to stdout instead.
> ```

s/out/err/

Again, should this be fatal? It seems like users should at least be able to opt in to fatal errors instead of allowing keys to be stored in unlocked memory.  This is especially important since there is a limit on how many pages can be locked, so `mlock` could start failing at runtime even if the initial CanLockPages check succeeded. 
___
*[c-deps/libroach/ccl/key_arena.cc, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27276#-LGzik1C0iSEr2OrNDkm:-LGzik1C0iSEr2OrNDkn:b-mow3zc) ([raw file](https://github.com/cockroachdb/cockroach/blob/757c0058aeae6a2beeb0f034188013cf6818ce36/c-deps/libroach/ccl/key_arena.cc#L132)):*
> ```cpp
> 
> // Try to lock/madvise and release a single page containing 'addr'.
> rocksdb::Status TryLockUnlock(size_t addr) {
> ```

This should use the code above instead of an entirely separate path. 
___
*[c-deps/libroach/ccl/key_arena.cc, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27276#-LGziPmY9M2BPhPH8JuB:-LGziPmY9M2BPhPH8JuC:b-5h6zug) ([raw file](https://github.com/cockroachdb/cockroach/blob/757c0058aeae6a2beeb0f034188013cf6818ce36/c-deps/libroach/ccl/key_arena.cc#L146)):*
> ```cpp
>   }
> #else
>   return rocksdb::Status::NotSupported("madvise(MADV_DONTDUMP) is not supported");
> ```

This leaves the block locked. We need to ensure that `munlock` gets called if `mlock` succeeded.

**Review by mberhault — COMMENTED** [review]
We should definitely recommend disabling swap and code dumps when running with encryption. If we want to push the responsibility on the users, then we can just drop the entire PR. My understanding from the design doc was that we wanted this though.

The main downside here is that the default limit for locked memory is 64K on a lot of systems (`ulimit -l`). It's been upped to 16MB on some newer ones but that's still pretty rare. We can warn on it the same way we do for low open FD limits.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27276#-:-LGzmT1U6Qv1F9uEj5jy:b5tc2vp)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[c-deps/libroach/ccl/db.cc, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27276#-LGzdMYiCy_1E4HM7pob:-LGzm3i97c_JQtFrHAH4:b-2vcla7) ([raw file](https://github.com/cockroachdb/cockroach/blob/757c0058aeae6a2beeb0f034188013cf6818ce36/c-deps/libroach/ccl/db.cc#L132)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

s/out/err/, but it would be even better to send this to the logs. Stdout/stderr are not necessarily collected anywhere useful or visible. 

Can we make this a fatal error or are there important platforms where we want to be able to support encryption where we can't lock pages?
</blockquote></details>

Well, Darwin doesn't support `madvise`, and windows doesn't have anything. While I want to discourage people from using encryption on those, they should still be able to play with it. Older kernels (eg: <3.4) also don't have `MADV_DONTDUMP` (or our release binaries for some reason).

Logs are not a great option as we don't have a mechanism in place to force logging when we don't have `vmodule=rocksdb=3` (we could add it though).
As for stderr, we opted for stdout for lack of AES instruction support. Is stderr clearer or easier to find? Ultimately, I think all of these should be surfaced to the admin UI. For now, I'm leaving it on stdout here but switching the `errno` logging to stderr.
___
*[c-deps/libroach/ccl/key_arena.h, line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27276#-LGzeJhK4riiY7zxTVrk:-LGzp5-b3FAh_gT-Vuen:bwi6p9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/757c0058aeae6a2beeb0f034188013cf6818ce36/c-deps/libroach/ccl/key_arena.h#L14)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Add a comment saying specifically that this arena doesn't do the fast batch-allocation that arenas are typically used for and that we're just using the arena interface to get the appropriate hooks. 
</blockquote></details>

It does. And fast-dealloc. That's actually the main point of it. We may actually consider using it in other places now that it supports strings in the arena.
___
*[c-deps/libroach/ccl/key_arena.h, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27276#-LGzeawz0WZeoceVfXjm:-LGzpKYgApv8tjw9I65d:bhzp3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/757c0058aeae6a2beeb0f034188013cf6818ce36/c-deps/libroach/ccl/key_arena.h#L21)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Why random? The [CERT security guidelines](https://wiki.sei.cmu.edu/confluence/display/c/MEM06-C.+Ensure+that+sensitive+data+is+not+written+out+to+disk) just zero-fill. I know random overwriting is recommended for disk but I'm not aware of similar concerns for memory. 

That page is also slightly skeptical of the value of `mlock()`. 
</blockquote></details>

Aww, but I had this nice function all ready to use. Just kidding, switched to `memset`.

mlock is not greatly standardized but it's mostly with respect page alignment of arguments and stacking of mlock/munlock calls (eg: the BSD version requires as many calls to munlock as you have for mlock. Linux says just 1 munlock does the trick). This is why the page registry operates on entire pages and does reference counting.
___
*[c-deps/libroach/ccl/key_arena.cc, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27276#-LGziofs2EplgMQOvksJ:-LGzrS8qBTvD27FGiVfa:b7bklyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/757c0058aeae6a2beeb0f034188013cf6818ce36/c-deps/libroach/ccl/key_arena.cc#L97)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

s/out/err/

Again, should this be fatal? It seems like users should at least be able to opt in to fatal errors instead of allowing keys to be stored in unlocked memory.  This is especially important since there is a limit on how many pages can be locked, so `mlock` could start failing at runtime even if the initial CanLockPages check succeeded. 
</blockquote></details>

Switched to stderr. For fatal and max locked mem, please see replies above.
___
*[c-deps/libroach/ccl/key_arena.cc, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27276#-LGzik1C0iSEr2OrNDkm:-LGzrZ-g0xcTYaZEYZ0H:b-w8nx13) ([raw file](https://github.com/cockroachdb/cockroach/blob/757c0058aeae6a2beeb0f034188013cf6818ce36/c-deps/libroach/ccl/key_arena.cc#L132)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This should use the code above instead of an entirely separate path. 
</blockquote></details>

I wanted to avoid building strings in the common path but then again that's only on error conditions. Merged.
___
*[c-deps/libroach/ccl/key_arena.cc, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27276#-LGziPmY9M2BPhPH8JuB:-LGzweje-r8NdAMpHT38:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/757c0058aeae6a2beeb0f034188013cf6818ce36/c-deps/libroach/ccl/key_arena.cc#L146)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This leaves the block locked. We need to ensure that `munlock` gets called if `mlock` succeeded. 
</blockquote></details>

Done.

**Comment by mberhault** [comment]
FYI: our release binaries respectively have the following:
- linux: no madvise support
- darwin: no madvise support
- windows: nothing whatsoever

I'm trying to figure out why we can't find `MADV_DONTDUMP` in our linux release builds.

**Comment by benesch** [comment]
> I'm trying to figure out why we can't find MADV_DONTDUMP in our linux release builds.

MADV_DONTDUMP was added in Linux 3.4, but our Linux release builds target 2.6.32. 😬

**Comment by mberhault** [comment]
ugh! That was 5 years ago. We may want to think about bumping our builder image. Probably too late in the cycle though. I can dump `madvise` for now and put it back in later.

**Review by bdarnell — COMMENTED** [review]
> If we want to push the responsibility on the users, then we can just drop the entire PR. My understanding from the design doc was that we wanted this though.

Well, we can set RLIMIT_CORE to zero ourselves; that doesn't require extra permissions and is pretty standard. I would do that instead of MADV_DONTDUMP.

That leaves swap. I think it's reasonable to ask/expect users of encryption to either disable or encrypt their swap partition (encrypted swap is easier than other disk encryption since the key doesn't have to be persisted anywhere), but we may want to check with some prospective users of this feature to make sure (and also to find out whether they want the inability to mlock the keys to be a fatal or soft failure). 

We chose kernel 2.6.32 as our baseline because that's the version used in RHEL 6.x. We have customers using this platform so we need to be careful about phasing it out.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27276#-:-LH-pSAu957Eo48tlG0G:b-a627vg)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[c-deps/libroach/ccl/key_arena.h, line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27276#-LGzeJhK4riiY7zxTVrk:-LH-sGX81yyEsM5JegdZ:b-yr53hb) ([raw file](https://github.com/cockroachdb/cockroach/blob/757c0058aeae6a2beeb0f034188013cf6818ce36/c-deps/libroach/ccl/key_arena.h#L14)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

It does. And fast-dealloc. That's actually the main point of it. We may actually consider using it in other places now that it supports strings in the arena.
</blockquote></details>

Ah, got it. It looked like single allocations but that was just me not reading the arena docs.

**Comment by mberhault** [comment]
ok, I'll leave this here for now and instead go for 1) rlimit settings ourselves and 2) strongly worded recommendations.

**Pull request closed without merging**
