### PR TITLE
rac2: fix race on last send queue stats

### PR DESCRIPTION
**Pull request by kvoli**
The race would occur when setting `lastSendQueueStats` for a new replica on `updateReplicaSet` because we didn't lock `rangeController.mu` before doing so, while the reader would i.e., no sync.

Lock `rangeController.mu` before setting `lastSendQueueStats`.

Part of: #128040
Release note: None

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132316)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 1480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132316#-O8r1oUd9YznncFNTn7n:-O8r1oUd9YznncFNTn7o:bbonvn2) ([raw file](https://github.com/cockroachdb/cockroach/blob/790d36be9baea2482210b298dd086a30420ba5b3/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L1480)):*
> ```Go
> 	// grabbing lastSendQueueStats, which acquires rc.mu, but doesn't acquire
> 	// raftMu. The other writer is updateSendQueueStatsRaftMuRCLocked, which as
> 	// the name suggests, holds both locks.
> ```

I think this comment could be simpler. The explanation of why lastSendQueueState is protected by rc.mu belongs in the declaration of lastSendQueueStats.
// Acquire rc.mu since we need to update rc.mu.lastSendQueueStats.

And we are modifying it in the previous loop too. So this isn't a sufficient fix.

I don't think we should be holding `rc.mu` while creating and closing `replicaSendStreams`/`replicaState` -- it's on the critical eval path. How about accumulating the removals in a slice (using a pre-allocated array of length 5 as backing), and same for additions. And then at the end of this method acquire `rc.mu` once and make the changes.

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132316)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 1480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132316#-O8r1oUd9YznncFNTn7n:-O8r3zgN-PpA4zxi_UZs:b-e7zkb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/790d36be9baea2482210b298dd086a30420ba5b3/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L1480)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think this comment could be simpler. The explanation of why lastSendQueueState is protected by rc.mu belongs in the declaration of lastSendQueueStats.
// Acquire rc.mu since we need to update rc.mu.lastSendQueueStats.

And we are modifying it in the previous loop too. So this isn't a sufficient fix.

I don't think we should be holding `rc.mu` while creating and closing `replicaSendStreams`/`replicaState` -- it's on the critical eval path. How about accumulating the removals in a slice (using a pre-allocated array of length 5 as backing), and same for additions. And then at the end of this method acquire `rc.mu` once and make the changes.
</blockquote></details>

SGTM -- I'll build up the delta and then acquire and release rc.mu once, down the bottom.

**Review by kvoli — COMMENTED** [review]
TYFTR

should be good for another look @sumeerbhola 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132316#-:-O8r67v_0Rn7-3AZSdLV:b-7fnb57)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 1480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132316#-O8r1oUd9YznncFNTn7n:-O8r512y-MH3X5weruW4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/790d36be9baea2482210b298dd086a30420ba5b3/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L1480)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

SGTM -- I'll build up the delta and then acquire and release rc.mu once, down the bottom.
</blockquote></details>

Done.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132316#-:-O8r7p6v4zoOyX8DO7In:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

**Comment by kvoli** [comment]
TYFTR!

**Comment by kvoli** [comment]
TYFTR

bors r=sumeerbhola

**Pull request merged**
