### PR TITLE
sql: evaluate filters at scan node; split filter during indexJoin

### PR DESCRIPTION
**Pull request by RaduBerinde**
Broken up into two commits, each one is a working change. See their descriptions for more info.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4713)

### CODE REVIEW

**Comment by tamird** [comment]
The first commit seems to replace many references to selectNode.filter with references to scanNode.filter, but it's not clear why that's OK to do given that scanNode.filter isn't removed.

---

Reviewed 9 of 9 files at r1.
Review status: 7 of 10 files reviewed at latest revision, 12 unresolved discussions.

---

*[sql/analyze.go, line 1221 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhUdyOsxunzz1Nm9jH:-KBhUdyOsxunzz1Nm9jI:-1466575939) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/analyze.go#L1221)):*
should this really be a type assertion on `parser.VariableExpr`?

---

*[sql/expr_filter.go, line 76 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhUqbAZq40l9K6pm7G:-KBhUqbBFrY6TWM-XM6Q:704808444) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/expr_filter.go#L76)):*
how come this is newly needed?

---

*[sql/expr_filter.go, line 91 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhUwLf3prUkEge7hHs:-KBhUwLf3prUkEge7hHt:2037666098) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/expr_filter.go#L91)):*
can you help me understand why this changed?

---

*[sql/expr_filter.go, line 268 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhV5Tl2TpycS61ryp0:-KBhV5Tl2TpycS61ryp1:773053493) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/expr_filter.go#L268)):*
Was there a strong reason to panic here rather than return an error?

---

*[sql/expr_filter_test.go, line 159 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhVNjCJ9xLTsipNzHl:-KBhVNjCJ9xLTsipNzHm:-481146447) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/expr_filter_test.go#L159)):*
this seems unrelated?

---

*[sql/group.go, line 47 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhVWGhvD3iL4iQum0D:-KBhVWGhvD3iL4iQum0E:339732003) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2616dfc9b486d08be672148e81c35cd510686f2/sql/group.go#L47)):*
how come this is no longer necessary?

---

*[sql/join.go, line 80 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhVnI8eOHCE5BBX0e7:-KBhVnI8eOHCE5BBX0e8:-1177384621) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/join.go#L80)):*
I'm :-1: on the named parameters here, but your call.

---

*[sql/scan_qvalue.go, line 17 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhTApLykEZAvw863-g:-KBhTApLykEZAvw863-h:113524239) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/scan_qvalue.go#L17)):*
I'm not sure what the prevailing style is, but I'd put this below the `package` declaration so that it's clear it isn't part of the standard header.

---

*[sql/scan_qvalue.go, line 29 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhTRdjCVozHnROl4xr:-KBhTRdjCVozHnROl4xs:-2069925799) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/scan_qvalue.go#L29)):*
Is scanQValue meant to be a special case of qvalue? When qvalue vs scanQValue would be used isn't clear to me.

---

*[sql/scan_qvalue.go, line 56 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhU3XwqctOIsz6ajfQ:-KBhU3XwqctOIsz6ajfR:-1922345140) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/scan_qvalue.go#L56)):*
this isn't idiomatic Go; can you use a constructor instead?

---

*[sql/select.go, line 214 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhWjvxZDuIwZ4d_kAP:-KBhWjvyS7_eV3uph1z0:-1076627260) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/select.go#L214)):*
s/conv/convFunc/  for consistency

---

*[sql/select.go, line 890 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhX-3xqmN_jPGCzYzg:-KBhX-3xqmN_jPGCzYzh:706323850) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/select.go#L890)):*
ditto re named returns

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-:-KBhX3hReyI0fCRr0kw7:-1692446152)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713)*

**Comment by RaduBerinde** [comment]
If you point me to a specifc instance where it's not clear, I can elaborate. Note that e.g. all code related to `selectIndex` is about a single `scanNode` (I have it on my TODO list to move it out of `select.go`)

---

Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[sql/analyze.go, line 1221 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhUdyOsxunzz1Nm9jH:-KBi-EFI7kTGO_4X4mgm:-161489113) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/analyze.go#L1221)):*
ValArgs can also be VariableExprs

---

*[sql/expr_filter.go, line 76 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhUqbAZq40l9K6pm7G:-KBi-GPu_R2JPD4rAhlP:-78466433) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/expr_filter.go#L76)):*
This is the first time this code is actually hooked up. `ValArg` also implements `VariableExpr` even though it doesn't conform with the intent of that interface, which is `an Expr that may change per row.`

---

*[sql/expr_filter.go, line 91 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhUwLf3prUkEge7hHs:-KBi-_djnE5qsQ2_F2eI:956186019) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/expr_filter.go#L91)):*
we don't need to recurse "inside" the VariableExpr

---

*[sql/expr_filter.go, line 268 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhV5Tl2TpycS61ryp0:-KBi2tt68XF9iB74auwL:2055820165) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/expr_filter.go#L268)):*
I'm confused, maybe this comment shows up in the wrong place? I couldn't figure out which panic you are referring to.

---

*[sql/expr_filter_test.go, line 159 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhVNjCJ9xLTsipNzHl:-KBi01K6TzSkXks5DuNS:-2102334003) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/expr_filter_test.go#L159)):*
Well it's improving the test to `splitFilter`, and this is the first time we are actually using `splitFilter` and relying on it not modifying the original expression.

---

*[sql/group.go, line 47 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhVWGhvD3iL4iQum0D:-KBi0CPOHGsVEJw-y9rh:1747996397) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2616dfc9b486d08be672148e81c35cd510686f2/sql/group.go#L47)):*
It was moved inside select code.

---

*[sql/join.go, line 80 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhVnI8eOHCE5BBX0e7:-KBi0Iylwb9MlEAGz9gp:1731306789) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/join.go#L80)):*
This way we know what the "bool" means without looking up the definition of `exprConvVars`. How would you document that?

---

*[sql/scan_qvalue.go, line 29 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhTRdjCVozHnROl4xr:-KBi0UipxE1CEYVkhnb2:-1924970235) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/scan_qvalue.go#L29)):*
`qvalue` is used at the `selectNode` level (I might rename it to selectQValue later). It can refer to columns in multiple tables. It can only be evaluated in the context of select code.
`scanQValue` is used at the `scanNode` level. It can only refer to columns in a specific table. It can be avaluated in the context of a `scanNode`.

---

*[sql/scan_qvalue.go, line 56 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhU3XwqctOIsz6ajfQ:-KBi0ppOOWolYZrv5AbP:1684444606) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/scan_qvalue.go#L56)):*
I am allocating all the `scanQValue`s in a single slice then calling `initQValue`. Would you prefer for this function to return a non-pointer `scanQValue` and replace `n.qvals[i].initQValue` with `n.qvals[i] = makeQValue()` ?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-:-KBi1xfPjUUIryJIpbVK:-1761145109)*

**Comment by petermattis** [comment]
LGTM

---

Reviewed 9 of 9 files at r1, 3 of 3 files at r2.
Review status: 7 of 10 files reviewed at latest revision, 14 unresolved discussions.

---

*[sql/join.go, line 80 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhVnI8eOHCE5BBX0e7:-KBiSxc4EsYGEQVdhcrt:-1925007251) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/join.go#L80)):*
I like the documentation of naming the return values. I think we should be :thumbsdown: on using naked `return` to utilize those variables.

---

*[sql/scan_qvalue.go, line 64 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBiVm0ZESCuyQgz5-GS:-KBiVm0ZESCuyQgz5-GT:374266116) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a5cb04f7f529b08df81624c920abd985e7727cf/sql/scan_qvalue.go#L64)):*
Is there any danger of `colIdx` being out of bounds?

---

*[sql/testdata/select_non_covering_index_filtering, line 105 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBiVsJ-uJvywsuWTuWn:-KBiVsJ-uJvywsuWTuWo:61039102) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a5cb04f7f529b08df81624c920abd985e7727cf/sql/testdata/select_non_covering_index_filtering#L105)):*
Nice tests!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-:-KBiVwwrhFqVWbYfKpl4:676834233)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[sql/expr_filter.go, line 91 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhUwLf3prUkEge7hHs:-KBicuTpx4jRaRnbFZRX:-923201747) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/expr_filter.go#L91)):*
So this was just wrong before but not really used?

---

*[sql/expr_filter.go, line 268 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhV5Tl2TpycS61ryp0:-KBicyVXPX3SR4bfAtOz:-1965607193) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/expr_filter.go#L268)):*
the unchecked type assertion will panic.

---

*[sql/group.go, line 47 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhVWGhvD3iL4iQum0D:-KBidKCBU_Cj7smOwut2:-2051389027) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2616dfc9b486d08be672148e81c35cd510686f2/sql/group.go#L47)):*
Where?

---

*[sql/scan_qvalue.go, line 29 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhTRdjCVozHnROl4xr:-KBidT-pRoX_HGpMkAVl:546013781) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/scan_qvalue.go#L29)):*
OK. I think that rename would be a nice disambiguation.

---

*[sql/scan_qvalue.go, line 56 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhU3XwqctOIsz6ajfQ:-KBidWl7ITRshbqW8eg1:-2043861436) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/scan_qvalue.go#L56)):*
Yep, that's better.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[sql/expr_filter.go, line 91 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhUwLf3prUkEge7hHs:-KBifYfRTPtLbE4t5NFc:-232534607) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/expr_filter.go#L91)):*
It's not a huge difference, the only issue is that if you recurse the VariableExpr has to have an implemented `Walk` routine. I purposely wanted to keep `scanQValue.Walk` unimplemented to make sure we aren't inadvertently walking them in other contexts.

---

*[sql/expr_filter.go, line 268 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhV5Tl2TpycS61ryp0:-KBifrFOVVoNRfa25-xG:96509605) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/expr_filter.go#L268)):*
Ah, yes.  I just moved this code (used to be `filterRow` in `select.go`). I took a look and we check that the type is `bool` beforehand (in `initWhere`).

---

*[sql/group.go, line 47 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBhVWGhvD3iL4iQum0D:-KBih9Iw9j7q51IJ4nmw:-1851439457) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2616dfc9b486d08be672148e81c35cd510686f2/sql/group.go#L47)):*
select.go:373. Easier to just CTRL-F `aggregateInExpr`

---

*[sql/scan_qvalue.go, line 64 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBiVm0ZESCuyQgz5-GS:-KBihMgWuSFVQbIBFf3f:786632401) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a5cb04f7f529b08df81624c920abd985e7727cf/sql/scan_qvalue.go#L64)):*
Only if there's a bug - scanQValues are derived from qvalues which only refer to valid columns.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713)*

**Comment by spencerkimball** [comment]
@RaduBerinde does this address #4299 at all?

**Comment by RaduBerinde** [comment]
@spencerkimball no, work for #2966 will help with that (I'm working on that too; though to make it work in general we will need #4696 addressed too)

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[sql/join.go, line 95 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBnIHNlW0r4bx1pIUwf:-KBnIHNlW0r4bx1pIUwg:-2072778037) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1834ed2edd7aaf2a779da6cdee14f1150649889/sql/join.go#L95)):*
ain't this a beauty

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[sql/join.go, line 82 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBn9IlUnyj3N8_BUk_H:-KBnMrqPGECtddUfOmap:2035865857) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/join.go#L82)):*
It's relative to the resultColumns/visibleCols/rows/valNeededForCol in the scan node. These are all the columns in the table, regardless if we are using an index or not (not all of colums might be populated of course).

Note the previous loop also assumes there is a 1:1 mapping between the columns in `table` and in `indexScan`.

The only case when we only have certain columns is the special case of selecting from a specific index (`SELECT * FROM t@idx`) which can't be involved in an indexJoin.

---

*[sql/scan_qvalue.go, line 64 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBn8Rx6dobsQXaVxHGL:-KBnO8Yr0i5b9aoDS0ij:-881478949) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/scan_qvalue.go#L64)):*
Ok, I will move it. I expected it to have more code haha

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713)*

**Comment by andreimatei** [comment]
LGTM

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[sql/join.go, line 82 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBn9IlUnyj3N8_BUk_H:-KBnPg4RS70RbSo8hMWw:927742393) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/join.go#L82)):*
Yeah, I looked more closely at the comments in scanNode afterwards. It probably would've been cleaner if that wasn't the case?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-:-KBnQ1uc6veFdgb9VTti:676834233)*

**Comment by RaduBerinde** [comment]
*[sql/join.go, line 82 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBn9IlUnyj3N8_BUk_H:-KBnS0kDtmsWfVmm3mwj:144711545) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/join.go#L82)):*
It would make a bunch of stuff harder.. E.g. think of using a covering index - the layer above scanNode would need to have specific code to adjust for the difference in columns between that and a "regular" scanNode.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[sql/join.go, line 82 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBn9IlUnyj3N8_BUk_H:-KBnZPy7stI7KQO6LN7k:-1578697895) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/join.go#L82)):*
well I was thinking a consumer would never index directly into a scan node; a scan node would expose a map from column alias to index

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713)*

**Comment by RaduBerinde** [comment]
*[sql/join.go, line 82 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713#-KBn9IlUnyj3N8_BUk_H:-KBncuCERxfkW6R6pmJX:116999804) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fdc5a0d12a5fc45c1addfb5b2ce06150ad8fd3/sql/join.go#L82)):*
This is a "what if" discussion that really would have been appropriate over my "separate select from scan" changes a month back :) `scanNode` implements `planNode` and `planNodes` don't expose maps, they expose lists of ResultColumns and lists of values..  If you want to make it something other than `planNode` then you need to add more code in select because it has to work against other `planNode`s like VALUES.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4713)*

**Pull request merged**
