### PR TITLE
rangefeed: gracefully handle feed cancellation in budget

### LINKED ISSUE #86859: rangefeed: ~100ms busy loop on TryGet on shutdown
Observed the following in tight loops in the logs on v22.1.9 during an L2 escalation (https://github.com/cockroachlabs/support/issues/1729)

> kv/kvserver/rangefeed/budget.go:166 ⋮ [n102,s425,r509150/2:‹/Table/54/6/111345{1/"…-6/"…}›,rangefeed] 1512552 trying to get allocation from already closed budget

This comes from

https://github.com/cockroachdb/cockroach/blob/0fbc2d56f7e3a69749f5cf9836d6baecc94425c0/pkg/kv/kvserver/rangefeed/budget.go#L165-L168

The log file contained >100k such records (from a number of such bursts). One burst I checked took ~100ms.

The spammy logging is a stability problem. But it is also problematic that we're busy-looping for ~100ms, as this can cause performance issues:

https://github.com/cockroachdb/cockroach/blob/0fbc2d56f7e3a69749f5cf9836d6baecc94425c0/pkg/kv/kvserver/rangefeed/budget.go#L189-L193

That loop should pace itself and avoid busy-looping. Ideally it would not loop at all if the budget is already closed.

Perhaps there is an issue with teardown that needs to be investigated.

Jira issue: CRDB-18969

### PR DESCRIPTION
**Pull request by aliher1911**
Previously budget acquire loop will retry acquire last time even if budget is closed and request is cancelled generating log spam. This commit changes logic to only retry once before failing in case waiting deadline is exceeded and moves budget closing to be done as the last step of processor loop terminating.

Release note: None

Fixes #86859

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89481)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911)

___
*[`pkg/kv/kvserver/rangefeed/processor.go` line 254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89481#-NE_9Lo39dCSfBCMqECE:-NE_9Lo39dCSfBCMqECF:b-dgftw0) ([raw file](https://github.com/cockroachdb/cockroach/blob/06caa2af2207d5f857780d2d259fd3c12d620b9d/pkg/kv/kvserver/rangefeed/processor.go#L254)):*
This sentence doesn't quite parse for me. I think it's trying to say something along the lines of:

> Close the memory budget last, or there will be a period of time during which requests are still ongoing but will run into the closed budget, causing shutdown noise and busy retries. Closing the budget after stoppedC ensures that all other goroutines are (very close to being) shut down by the time the budget goes away.
___
*[`pkg/kv/kvserver/rangefeed/processor.go` line 610 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89481#-NE_9yIwBgF4odmccdnf:-NE_9yIwBgF4odmccdng:b-60zwqu) ([raw file](https://github.com/cockroachdb/cockroach/blob/06caa2af2207d5f857780d2d259fd3c12d620b9d/pkg/kv/kvserver/rangefeed/processor.go#L610)):*
> ```Go
> 			}
> 			defer func() {
> 				alloc.Release(ctx)
> ```

It doesn't seem wise to call `alloc.Release` if we didn't have an alloc. Isn't this a straight-up NPE?

**Review by aliher1911 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89481)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[`pkg/kv/kvserver/rangefeed/processor.go` line 610 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89481#-NE_9yIwBgF4odmccdnf:-NElHGYWDU72Lfy5BPfe:b3hm0cw) ([raw file](https://github.com/cockroachdb/cockroach/blob/06caa2af2207d5f857780d2d259fd3c12d620b9d/pkg/kv/kvserver/rangefeed/processor.go#L610)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

It doesn't seem wise to call `alloc.Release` if we didn't have an alloc. Isn't this a straight-up NPE?
</blockquote></details>

Release is nil safe. This property is used to move allocation into event. If send succeeds then this variable is also reset to let channel consumer to release allocations when they are processed and associated memory released.

**Review by tbg — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89481)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911)

**Comment by aliher1911** [comment]
TFTR

bors r+

**Comment by erikgrinaker** [comment]
Let's get this backported too.

**Pull request merged**
