### PR TITLE
roachtest: extract version map into separate file

### PR DESCRIPTION
**Pull request by rail**
Previously, we had to patch the code in order to update the version
upgrade test's version mapping. This made automation a bit complicated,
thus it was done manually.

Additionally, when we upgraded to a new major version, we would need to
patch the same test in order to generate fixtures.

This patch extracts the version mapping into a separate file, which will
be easier to patch using automation. Additionally, it extracts the fixture
generation code into a separate test which is skipped by CI, but can be
run manually.

Release note: None

### CODE REVIEW

**Comment by rail** [comment]
TBD: 
* Backport this change to all release branches
* update the release and branching (or minting) docs in order to use the new location

**Review by celiala — COMMENTED** [review]
Thanks for making this change! The overall approach looks good to me.

I had one suggestion of making use of `--build-tag` (inline): from reading the comment/note, it seems like we only use this fixture generation code when generating new fixtures for the next major release ( @tbg - please chime in if this is not the case :) ).

> Backport this change to all release branches

If the only time we generate fixtures for the next major release (i.e. master), then we don't need to backport this to any release branches.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82088#-:-N3UPoNg5cUz5AXw7_0G:b-6om8lr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rail and @tbg)

___
*[`pkg/cmd/roachtest/tests/acceptance.go` line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82088#-N3UQtt4EfLsBZish-va:-N3UQtt5-IbrEIp-_yZu:b-35b0hp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa8073ed5b8c56af5e595963806e27c2a6f319d/pkg/cmd/roachtest/tests/acceptance.go#L95)):*
> ```Go
> 					// next release. The release team runbooks, at time of writing, reflect
> 					// this.
> 					makeFixtureVersion := "22.1.0-beta.3" // for 22.1 release
> ```

It would be great it the user didn't have to go into this file to modify this line of code.

If we took advantage of the `--build-tag`[1] parameter, then this could be:

```
makeFixtureVersion :=  strings.Trim(t.BuildVersion().String(), "v")
```

(And then the above comment would move to wherever we show the usage example)

[1] I quickly skimmed `makeVersionFixtureAndFatal` and it didn't seem like `t.BuildVersion()` was being used for another context, but we should test to verify, if we use it for this purpose
___
*[`pkg/cmd/roachtest/tests/predecessor_version.go` line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82088#-N3UTcn29FnkTSpAPKan:-N3UTcn29FnkTSpAPKao:b-7m74ox) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa8073ed5b8c56af5e595963806e27c2a6f319d/pkg/cmd/roachtest/tests/predecessor_version.go#L53)):*
> ```Go
> 	}
> 
> 	verMap, err := unmarshallVersionMap()
> ```

nice!

**Review by rail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82088)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @celiala, @rail, and @tbg)

___
*[`pkg/cmd/roachtest/tests/acceptance.go` line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82088#-N3UQtt4EfLsBZish-va:-N3UVzcyEDhXLs2eNWI1:b-n7unbm) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa8073ed5b8c56af5e595963806e27c2a6f319d/pkg/cmd/roachtest/tests/acceptance.go#L95)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

It would be great it the user didn't have to go into this file to modify this line of code.

If we took advantage of the `--build-tag`[1] parameter, then this could be:

```
makeFixtureVersion :=  strings.Trim(t.BuildVersion().String(), "v")
```

(And then the above comment would move to wherever we show the usage example)

[1] I quickly skimmed `makeVersionFixtureAndFatal` and it didn't seem like `t.BuildVersion()` was being used for another context, but we should test to verify, if we use it for this purpose

</blockquote></details>

Very good point! Let me try to come up with some solution for this!

**Review by rail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82088)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @celiala, @rail, and @tbg)

___
*[`pkg/cmd/roachtest/tests/acceptance.go` line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82088#-N3UQtt4EfLsBZish-va:-N3VLTxK7_W7hiFjp97v:bpzh5rz) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa8073ed5b8c56af5e595963806e27c2a6f319d/pkg/cmd/roachtest/tests/acceptance.go#L95)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Very good point! Let me try to come up with some solution for this!
</blockquote></details>

`t.BuildVersion()` gives me an unreleased version, and the test fails downloading it. I ended up with an explicit solution, similar to what we have now, not not hard coded.

**Review by tbg — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82088)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @celiala and @rail)

___
*[`pkg/cmd/roachtest/tests/acceptance.go` line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82088#-N3UQtt4EfLsBZish-va:-N3Z68g3Bkexu0WkCq4_:b-gmw8yw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa8073ed5b8c56af5e595963806e27c2a6f319d/pkg/cmd/roachtest/tests/acceptance.go#L95)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

`t.BuildVersion()` gives me an unreleased version, and the test fails downloading it. I ended up with an explicit solution, similar to what we have now, not not hard coded.
</blockquote></details>

I thought Celia's suggestion was to pass in the build version flag (`roachtest run --build-version "something" <testname>`), does that not work? I get that if we don't specify it explicitly, it will be populated from the git tag and is (at least on master) not a released version. It really should work to pass it explicitly, as it will simply be taken in by this code:

https://github.com/cockroachdb/cockroach/blob/92fedb9ed6050332d4a1a04bac9a30b2a7752ab2/pkg/cmd/roachtest/test_registry.go#L59-L66

The env var works too, though it is a little less clean.
___
*[`pkg/cmd/roachtest/tests/acceptance.go` line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82088#-N3Z5XNTAqHtYVFs_FtV:-N3Z5XNTAqHtYVFs_FtW:bhajfdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/061883defc34bd1e5715d77ab7094d1a93980067/pkg/cmd/roachtest/tests/acceptance.go#L65)):*
> ```Go
> 				// running. If that branch corresponds to an older release, then upgrading
> 				// to head after 19.2 fails.
> 				minVersion: "v19.2.0",
> ```

we shouldn't need this since 19.2 is so long in the past. It looks like you added this, which I am puzzled by.
___
*[`pkg/cmd/roachtest/tests/acceptance.go` line 98 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82088#-N3Z6Wjv9vXL7txlxXCH:-N3Z6Wjv9vXL7txlxXCI:bjdeso2) ([raw file](https://github.com/cockroachdb/cockroach/blob/061883defc34bd1e5715d77ab7094d1a93980067/pkg/cmd/roachtest/tests/acceptance.go#L98)):*
> ```Go
> 					fixtureVersion := os.Getenv("FIXTURE_VERSION")
> 					if fixtureVersion == "" {
> 						t.Skip("FIXTURE_VERSION not specified")
> ```

Skipping it here will mean that a cluster will already have been created for no good reason. It is better to skip via the test spec, i.e. set the `Skip` field based on whether the env var is around. It's smelly, though.

Instead of the skipping dance, you could also use a "tag", maybe this is cleaner: `roachtest run tag:gen-fixtures` though I must say the tags stuff is haphazardly implemented (you can only run "all tests" under a tag, here there will only be one so that's fine). This seems better than skipping based on the absence of the env var since it hides this test completely from "everyday runs".

Also, please make this a top-level test - it has little reason to be under the `acceptance/` prefix. The acceptance tests are the ones that run in CI, this isn't one of them and even if we hide it behind a tag it's still awkward to have it here.
___
*[`pkg/cmd/roachtest/tests/predecessor_version.go` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82088#-N3Z7Nbk317ge2FxHcn3:-N3Z7Nbk317ge2FxHcn4:b-17xrlh) ([raw file](https://github.com/cockroachdb/cockroach/blob/061883defc34bd1e5715d77ab7094d1a93980067/pkg/cmd/roachtest/tests/predecessor_version.go#L35)):*
> ```Go
> type versionMap map[string]string
> 
> func unmarshallVersionMap() (versionMap, error) {
> ```

nit: unmarshal
___
*[`pkg/cmd/roachtest/tests/versionupgrade.go` line 609 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82088#-N3Z7K7S7TxXPF6wZXab:-N3Z7K7S7TxXPF6wZXac:b-vsb9t7) ([raw file](https://github.com/cockroachdb/cockroach/blob/061883defc34bd1e5715d77ab7094d1a93980067/pkg/cmd/roachtest/tests/versionupgrade.go#L609)):*
> ```Go
> for i in 1 2 3 4; do
>   mkdir -p pkg/cmd/roachtest/fixtures/${i} && \
>   mv artifacts/acceptance/generate-fixtures/run_1/logs/${i}.unredacted/checkpoint-*.tgz \
> ```

nb: this path will change if we move the test out of acceptance

**Review by rail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82088)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @celiala, @rail, and @tbg)

___
*[`pkg/cmd/roachtest/tests/acceptance.go` line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82088#-N3UQtt4EfLsBZish-va:-N3ZeKIF86qAuwgGhGyV:bdd5ngv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa8073ed5b8c56af5e595963806e27c2a6f319d/pkg/cmd/roachtest/tests/acceptance.go#L95)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I thought Celia's suggestion was to pass in the build version flag (`roachtest run --build-version "something" <testname>`), does that not work? I get that if we don't specify it explicitly, it will be populated from the git tag and is (at least on master) not a released version. It really should work to pass it explicitly, as it will simply be taken in by this code:

https://github.com/cockroachdb/cockroach/blob/92fedb9ed6050332d4a1a04bac9a30b2a7752ab2/pkg/cmd/roachtest/test_registry.go#L59-L66

The env var works too, though it is a little less clean.
</blockquote></details>

Totally agree that using an env variable is a bit dirty - it's less explicit and harder to find. My worry about `--build-tag` is that it may mess with the tests.

As an option I can add something like `--fixture-version` and use it.
___
*[`pkg/cmd/roachtest/tests/acceptance.go` line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82088#-N3Z5XNTAqHtYVFs_FtV:-N3Ze2724YFt_H30zQ8b:be31040) ([raw file](https://github.com/cockroachdb/cockroach/blob/061883defc34bd1e5715d77ab7094d1a93980067/pkg/cmd/roachtest/tests/acceptance.go#L65)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

we shouldn't need this since 19.2 is so long in the past. It looks like you added this, which I am puzzled by.
</blockquote></details>

Hehe, I just blindly copied it :) 
___
*[`pkg/cmd/roachtest/tests/acceptance.go` line 98 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82088#-N3Z6Wjv9vXL7txlxXCH:-N3Zf9RX3m2HWhPNyh96:bsbm1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/061883defc34bd1e5715d77ab7094d1a93980067/pkg/cmd/roachtest/tests/acceptance.go#L98)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Skipping it here will mean that a cluster will already have been created for no good reason. It is better to skip via the test spec, i.e. set the `Skip` field based on whether the env var is around. It's smelly, though.

Instead of the skipping dance, you could also use a "tag", maybe this is cleaner: `roachtest run tag:gen-fixtures` though I must say the tags stuff is haphazardly implemented (you can only run "all tests" under a tag, here there will only be one so that's fine). This seems better than skipping based on the absence of the env var since it hides this test completely from "everyday runs".

Also, please make this a top-level test - it has little reason to be under the `acceptance/` prefix. The acceptance tests are the ones that run in CI, this isn't one of them and even if we hide it behind a tag it's still awkward to have it here.
</blockquote></details>

Good points. Now I want to extract this in as separate subcommand, so we don't event execute it in normal situation. :thinking: 
___
*[`pkg/cmd/roachtest/tests/predecessor_version.go` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82088#-N3Z7Nbk317ge2FxHcn3:-N3ZffXkDG5vnar0u3lK:b-t69q0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/061883defc34bd1e5715d77ab7094d1a93980067/pkg/cmd/roachtest/tests/predecessor_version.go#L35)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

nit: unmarshal
</blockquote></details>

Oooops.
___
*[`pkg/cmd/roachtest/tests/versionupgrade.go` line 609 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82088#-N3Z7K7S7TxXPF6wZXab:-N3Zfk8C2GUL-3UiVGxy:bqohj8l) ([raw file](https://github.com/cockroachdb/cockroach/blob/061883defc34bd1e5715d77ab7094d1a93980067/pkg/cmd/roachtest/tests/versionupgrade.go#L609)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

nb: this path will change if we move the test out of acceptance
</blockquote></details>

Roger. I'll make sure the output works.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82088)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @celiala, @rail, and @tbg)

___
*[`pkg/cmd/roachtest/tests/acceptance.go` line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82088#-N3UQtt4EfLsBZish-va:-N3d-rEcD3VCvkkNmBiY:blqd75r) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa8073ed5b8c56af5e595963806e27c2a6f319d/pkg/cmd/roachtest/tests/acceptance.go#L95)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Totally agree that using an env variable is a bit dirty - it's less explicit and harder to find. My worry about `--build-tag` is that it may mess with the tests.

As an option I can add something like `--fixture-version` and use it.

</blockquote></details>

We definitely shouldn't add a new flag for this. I'm not sure I follow your worry about "--build-tag messing with the tests". Which tests are you worried about? We wouldn't be changing anything about how `--build-tag` works. The only thing you would do is to make this new "test" you're adding (which isn't really a test) use that flag.
___
*[`pkg/cmd/roachtest/tests/acceptance.go` line 98 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82088#-N3Z6Wjv9vXL7txlxXCH:-N3d05vj3WsCsmjSJGEd:b-b3pdhn) ([raw file](https://github.com/cockroachdb/cockroach/blob/061883defc34bd1e5715d77ab7094d1a93980067/pkg/cmd/roachtest/tests/acceptance.go#L98)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Good points. Now I want to extract this in as separate subcommand, so we don't event execute it in normal situation. :thinking: 
</blockquote></details>

The tag idea essentially does this and I'd recommend you do that. We only ever run the default tag and "weekly" as tests.

**Review by rail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82088)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @celiala, @rail, and @tbg)

___
*[`pkg/cmd/roachtest/tests/acceptance.go` line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82088#-N3UQtt4EfLsBZish-va:-N3eOyTS01K1YP54sYUs:b-h8m76f) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa8073ed5b8c56af5e595963806e27c2a6f319d/pkg/cmd/roachtest/tests/acceptance.go#L95)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

We definitely shouldn't add a new flag for this. I'm not sure I follow your worry about "--build-tag messing with the tests". Which tests are you worried about? We wouldn't be changing anything about how `--build-tag` works. The only thing you would do is to make this new "test" you're adding (which isn't really a test) use that flag.
</blockquote></details>

Roger, makes sense. The new iteration uses `--build-tag` and skips the test unless `tag:fixtures` is specified. Using the `.Skip` won't let you run the test.
___
*[`pkg/cmd/roachtest/tests/acceptance.go` line 98 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82088#-N3Z6Wjv9vXL7txlxXCH:-N3ePYqh1miVQUkHuZ68:b-2prfo8) ([raw file](https://github.com/cockroachdb/cockroach/blob/061883defc34bd1e5715d77ab7094d1a93980067/pkg/cmd/roachtest/tests/acceptance.go#L98)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

The tag idea essentially does this and I'd recommend you do that. We only ever run the default tag and "weekly" as tests.
</blockquote></details>

Thank you for the tip!

**Review by tbg — APPROVED** [review]

**Pull request merged**
