### PR TITLE
sql: support SHOW SYSTEM GRANTS

### LINKED ISSUE #85549: sql: support SHOW for synthetic privileges
Add a delegate show command for synthetic privileges in system.privileges.

Jira issue: CRDB-18304
Epic CRDB-11725

### PR DESCRIPTION
**Pull request by RichardJCai**
fixes https://github.com/cockroachdb/cockroach/issues/85549

Release justification: Observability only command

Release note (sql change): SHOW SYSTEM GRANTS [FOR ROLE ...]
allows you to see the grants done by GRANT SYSTEM ...

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86700)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai and @rimadeodhar)

___
*[`pkg/sql/delegate/show_grants.go` line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86700#-NAQ9ZDW-UQoKHG-RHvw:-NAQ9ZDW-UQoKHG-RHvx:b-v5h17s) ([raw file](https://github.com/cockroachdb/cockroach/blob/17ec538f396867d3c3778f91e8340a9b8839e11b/pkg/sql/delegate/show_grants.go#L65)):*
> ```Go
> FROM "".information_schema.type_privileges`
> 	const systemPrivilegeQuery = `
> SELECT * FROM (
> ```

what's the reason for the outer `SELECT *`?
___
*[`pkg/sql/delegate/show_grants.go` line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86700#-NAQ9lIH00EQ-eL7cEcJ:-NAQ9lIH00EQ-eL7cEcK:b-d5hgwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/17ec538f396867d3c3778f91e8340a9b8839e11b/pkg/sql/delegate/show_grants.go#L73)):*
> ```Go
>             FROM system.privileges
>            WHERE username = a.username
>         ) AS grantable
> ```

i think the other SHOW GRANTS commands use `is_grantable` for this right?
___
*[`pkg/sql/delegate/show_grants.go` line 312 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86700#-NAQAXQO-UJknDzMKFXE:-NAQAXQP7oMzPenBX_uI:bal2crv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d26d9b035236bb18d5d9999362e31eb80c29bc8/pkg/sql/delegate/show_grants.go#L312)):*
> ```Go
> 		SELECT * FROM (%s) %s ORDER BY %s
> 	`, source.String(), cond.String(), orderBy)
> 	fmt.Println(query)
> ```

nit: remove print
___
*[`pkg/sql/logictest/testdata/logic_test/external_connection_privileges` line 84 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86700#-NAQAdQNE4ILKcir2FhZ:-NAQAdQNE4ILKcir2Fh_:b-u2vwcf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d26d9b035236bb18d5d9999362e31eb80c29bc8/pkg/sql/logictest/testdata/logic_test/external_connection_privileges#L84)):*
> ```
> GRANT DROP, USAGE ON EXTERNAL CONNECTION foo TO testuser2 WITH GRANT OPTION
> 
> query TTTB
> ```

nit: add colnames
___
*[`pkg/sql/logictest/testdata/logic_test/show_grants_on_virtual_table` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86700#-NAQAFDbANGYYkIn0yJX:-NAQAFDbANGYYkIn0yJY:b8px8rb) ([raw file](https://github.com/cockroachdb/cockroach/blob/06a18468a543430a68e4cf404c1987d43efbed44/pkg/sql/logictest/testdata/logic_test/show_grants_on_virtual_table#L1)):*
> ```
> query TTTTTB
> ```

can you use `colnames` for these tests too?
___
*[`pkg/sql/logictest/testdata/logic_test/show_grants_synthetic` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86700#-NAQ9pKV9j9_LPc6AcJw:-NAQ9pKV9j9_LPc6AcJx:b-j5cllu) ([raw file](https://github.com/cockroachdb/cockroach/blob/17ec538f396867d3c3778f91e8340a9b8839e11b/pkg/sql/logictest/testdata/logic_test/show_grants_synthetic#L10)):*
> ```
> GRANT SYSTEM EXTERNALCONNECTION TO testuser WITH GRANT OPTION
> 
> query TTB
> ```

can you add `colnames` here so the output is a bit easier to understand?
___
*[`pkg/sql/parser/testdata/show_grants_external_connections` line 2 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86700#-NAQAgVi8pd_V9sEn6cO:-NAQAgVi8pd_V9sEn6cP:b6yed82) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d26d9b035236bb18d5d9999362e31eb80c29bc8/pkg/sql/parser/testdata/show_grants_external_connections#L2)):*
> ```
> parse
> SHOW GRANTS ON EXTERNAL CONNECTION foo
> ```

in the README for adding synthetic privileges, can we make sure there's a step about adding a SHOW command, so that other teams start doing it on their own?

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86700)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @rimadeodhar)

___
*[`pkg/sql/delegate/show_grants.go` line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86700#-NAQ9ZDW-UQoKHG-RHvw:-NAeZqM9E1cNRYVESO0Z:b-dno38a) ([raw file](https://github.com/cockroachdb/cockroach/blob/17ec538f396867d3c3778f91e8340a9b8839e11b/pkg/sql/delegate/show_grants.go#L65)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

what's the reason for the outer `SELECT *`?
</blockquote></details>

Don't think it's actually necessary, I just added it so reading the WHERE and ORDER clauses were a little more clear but I've removed it.
___
*[`pkg/sql/delegate/show_grants.go` line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86700#-NAQ9lIH00EQ-eL7cEcJ:-NAeXd-f7mhQG5scvRRC:b-q3kob5) ([raw file](https://github.com/cockroachdb/cockroach/blob/17ec538f396867d3c3778f91e8340a9b8839e11b/pkg/sql/delegate/show_grants.go#L73)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think the other SHOW GRANTS commands use `is_grantable` for this right?
</blockquote></details>

Yeah, updated
___
*[`pkg/sql/delegate/show_grants.go` line 312 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86700#-NAQAXQO-UJknDzMKFXE:-NAe_1Hh7GIx9GlYOSAi:bu1jxa7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d26d9b035236bb18d5d9999362e31eb80c29bc8/pkg/sql/delegate/show_grants.go#L312)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: remove print
</blockquote></details>

Oops forgot to delete this one, done.
___
*[`pkg/sql/logictest/testdata/logic_test/show_grants_on_virtual_table` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86700#-NAQAFDbANGYYkIn0yJX:-NAe_B6eC1hQKvpvZ7gW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/06a18468a543430a68e4cf404c1987d43efbed44/pkg/sql/logictest/testdata/logic_test/show_grants_on_virtual_table#L1)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can you use `colnames` for these tests too?
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/show_grants_synthetic` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86700#-NAQ9pKV9j9_LPc6AcJw:-NAe_PrM9xhiY2J_0GUp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/17ec538f396867d3c3778f91e8340a9b8839e11b/pkg/sql/logictest/testdata/logic_test/show_grants_synthetic#L10)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can you add `colnames` here so the output is a bit easier to understand?
</blockquote></details>

Done.
___
*[`pkg/sql/parser/testdata/show_grants_external_connections` line 2 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86700#-NAQAgVi8pd_V9sEn6cO:-NAeaJ6YA4t5Y0HJgSCn:b-dmdfdk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d26d9b035236bb18d5d9999362e31eb80c29bc8/pkg/sql/parser/testdata/show_grants_external_connections#L2)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

in the README for adding synthetic privileges, can we make sure there's a step about adding a SHOW command, so that other teams start doing it on their own?
</blockquote></details>

Ack will do, need to make some updates there

**Review by rafiss — APPROVED** [review]
lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86700#-:-NAgxuYJ9fDmX25FmUTo:b-7nbn20)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @rimadeodhar)

**Comment by RichardJCai** [comment]
Thanks!

bors r=rafiss

**Pull request merged**
