### PR TITLE
release: save local copy of archives

### PR DESCRIPTION
**Pull request by rail**
Previously, the release script uploaded the release tarballs without saving them, then downloaded again in order to generate docker images. This adds an extra failure point and an unnecessary download operation.

This PR adds an ability to save local copied of uploaded files and reuses the tarballs for docker image generation.

Epic: none
Release note: None

### CODE REVIEW

**Review by celiala — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94622)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jlinder)

**Comment by rail** [comment]
I'll rebase it after https://github.com/cockroachdb/cockroach/pull/94624 is merged - I bet there will some minor conflicts.

**Comment by rail** [comment]
bors r=celiala

**Comment by rail** [comment]
blathers backport release-22.1

**Comment by rail** [comment]
I tried to backport this to 22.1, but requires more backports, so I'm going to leave it as is.

**Pull request merged**
