### PR TITLE
server: actually check that catalog doesn't contain non-existent metrics

### PR DESCRIPTION
**Pull request by tbg**
TestChartCatalogMetrics is our main enforcement mechanism around the
hygiene of the chart catalog. Concretely, it checks that all metrics
are present in the catalog. However, its attempt to check the other
direction, namely that any metric mentioned in the catalog actually
(still) exists was thwarted because `GenerateCatalog` silently drops
such metrics (and so the test didn't ever get to see the stale entries).

This commit adds a `strict` flag to `GenerateCatalog` and removes all
stale metrics from the catalog.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
Friendly ping.

**Review by knz — COMMENTED** [review]
See my comments below. Maybe the reasoning is flawed since many metrics are generated during server initialization, and the test doesn't account for that?

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81038#-:-N2CLCHa-130XgziQ04B:b18y0cw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[`pkg/ts/catalog/chart_catalog.go` line 1288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81038#-N2CJsYu2frOmoZonycT:-N2CJsYu2frOmoZonycU:briqfom) ([raw file](https://github.com/cockroachdb/cockroach/blob/d63a3693480d2b62aebd15c11799d2ccdc8564a4/pkg/ts/catalog/chart_catalog.go#L1288)):*
> ```Go
> 				Title: "Emitted Bytes",
> 				Metrics: []string{
> 					"changefeed.emitted_bytes",
> ```

Removing this is incorrect. The metric still exists. I think you need to run the test with ccl packages imported. 
___
*[`pkg/ts/catalog/chart_catalog.go` line 2114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81038#-N2CL5Z6EmY3z-DL6Z_1:-N2CL5Z745vgIpOvy1aI:b-dpz5hv) ([raw file](https://github.com/cockroachdb/cockroach/blob/d63a3693480d2b62aebd15c11799d2ccdc8564a4/pkg/ts/catalog/chart_catalog.go#L2114)):*
> ```Go
> 			{
> 				Title:   "All",
> 				Metrics: []string{"sql.mem.admin.max"},
> ```

Removing these seems incorrect. I see them still generated at run-time (via `sql.Make{Base,}MemMetrics()`)

**Review by tbg — COMMENTED** [review]
Good catch about the ccl packages! Moved this test to `serverccl` and indeed it now finds ... lots of additional metrics.
The test does use a running server to pull the registry though, and I think some of the SQL metrics are legit gone. There are a bunch of similarly named metrics, which perhaps made it seem like they were still around.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81038#-:-N2FzDyE3WVzIAhPI5KB:b-uvpfj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/ts/catalog/chart_catalog.go` line 1288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81038#-N2CJsYu2frOmoZonycT:-N2Fy34b0ORenMNz0uAp:b-3rnhkx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d63a3693480d2b62aebd15c11799d2ccdc8564a4/pkg/ts/catalog/chart_catalog.go#L1288)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Removing this is incorrect. The metric still exists. I think you need to run the test with ccl packages imported. 
</blockquote></details>

Good point, I'll have to move this into a ccl package.
___
*[`pkg/ts/catalog/chart_catalog.go` line 2114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81038#-N2CL5Z6EmY3z-DL6Z_1:-N2Fxsk2D9B5KBv7fhkF:b-9d23ez) ([raw file](https://github.com/cockroachdb/cockroach/blob/d63a3693480d2b62aebd15c11799d2ccdc8564a4/pkg/ts/catalog/chart_catalog.go#L2114)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Removing these seems incorrect. I see them still generated at run-time (via `sql.Make{Base,}MemMetrics()`)
</blockquote></details>

Are you sure? The test pulls the catalog off a running cluster. I think these particular prefixes just went away.

**Comment by tbg** [comment]
Assigning this to @cockroachdb/obs-inf-prs to pick up at an opportune time. This probably isn't super pressing but if we are planning to use the catalog for anything new in the future it will be important that it is up to date. Currently, `tsdump` will possibly be missing some metrics, which could be problematic.

What's needed to land this is to backfill all of the missing metrics into the catalog. This is a bit annoying, but really just mindless work, to break things out into enough charts so that we stop hitting

> changefeed.backfill_count and changefeed.buffer_pushback_nanos have different MetricTypes, but are being 
        			added to the same chart

If we wanted to actually make the organization within the chart catalog useful, that would be a much larger task, but that can't be the goal at this point.

**Comment by tbg** [comment]
@nkodali apologies for throwing another PR over your fence. Could you see if this could be picked up by someone? It isn't urgent, but most of the work is done and it fixes an actual problem that could have a small impact in some L2 escalations.

**Comment by tbg** [comment]
Closing since https://github.com/cockroachdb/cockroach/issues/81359 was since addressed (thanks @koorosh!)

**Pull request closed without merging**
