### PR TITLE
sql: add a --rewrite-results-in-testfiles mode to logic test

### PR DESCRIPTION
**Pull request by RaduBerinde**
Adding a special mode to logic tests which rewrites the tests, replacing the
results if there are any mismatches. This is useful when a change produces many
changes (most commonly for `EXPLAIN` statements). However, it should be used
with care: the diffs must always be inspected manually to confirm there are no
unexpected changes.

### CODE REVIEW

**Comment by jordanlewis** [comment]
:lgtm_strong: This seems super ripe for abuse :). Does it work against the files in `bigtest`, out of curiosity?

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/logic_test.go, line 232 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15741#-KjUIavOLXTE9lwthoEy:-KjUIavOLXTE9lwthoEz:b-f5qdmj) ([raw file](https://github.com/cockroachdb/cockroach/blob/fda3479166c9275d892a33288c756f2fcc2cfe34/pkg/sql/logic_test.go#L232)):*
> ```Go
> 			"or -flex-types.",
> 	)
> 	generateTestfiles = flag.Bool(
> ```

bikeshed: can we make this name a little scarier? how about rewriteExpectedResults or something?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15741#-:-KjUILuVPC2PK3xm6ZfQ:bz1qaox)*

**Comment by RaduBerinde** [comment]
It should work with `bigtest` but I don't see the point of doing that.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15741#-:-KjUMPxgYCsgU8IUHCfX:b-24apsv)*

**Comment by tamird** [comment]
Haven't reviewed but this is awesome! 💯

**Comment by knz** [comment]
:lgtm: good idea!

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15741#-:-KjZQKT-0_CaeQrjemiN:bbzbus6)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/logic_test.go, line 232 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15741#-KjUIavOLXTE9lwthoEy:-KjZQRSClEj8p2aHnqe1:bu2iw09) ([raw file](https://github.com/cockroachdb/cockroach/blob/d62864e908f1b707a55fd1925fe1db3f2348df07/pkg/sql/logic_test.go#L232)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

bikeshed: can we make this name a little scarier? how about rewriteExpectedResults or something?
</blockquote></details>

I'm ok with `--rewrite-expected-results` or maybe even `--rewrite-results-in-testfiles`. Waiting to see if anyone else has an opinion before I change it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15741)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/logic_test.go, line 232 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15741#-KjUIavOLXTE9lwthoEy:-Kjc74buuH8JwYqMfWgb:b-4fxjr4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d62864e908f1b707a55fd1925fe1db3f2348df07/pkg/sql/logic_test.go#L232)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I'm ok with `--rewrite-expected-results` or maybe even `--rewrite-results-in-testfiles`. Waiting to see if anyone else has an opinion before I change it.
</blockquote></details>

Switched to `--rewrite-results-in-testfiles` It's intentionally long and clunky :)  Will merge like this if there are no objections.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15741)*

**Comment by knz** [comment]
ggftw

**Pull request merged**
