### PR TITLE
sql: improve func expression type checking performance

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
2 commits:
(1) change overloads returned from function resolver to pointers to avoid value copying.
(2) expand the `overloadImpl` interface to allow accessing function overload properties without type casting. This allows us to get rid of the slice allocation in type checking.

All these would be able to improve the type checking performance by 20% cpu time overall:
```
name                                                       old time/op    new time/op    delta
FuncExprTypeCheck/builtin_called_on_null_input-24            1.05µs ± 1%    0.68µs ± 1%  -35.53%  (p=0.000 n=10+10)
FuncExprTypeCheck/builtin_not_called_on_null_input-24        1.00µs ± 1%    0.66µs ± 1%  -34.04%  (p=0.000 n=9+10)
FuncExprTypeCheck/builtin_aggregate-24                       2.17µs ± 0%    1.06µs ± 0%  -51.07%  (p=0.000 n=10+10)
FuncExprTypeCheck/builtin_aggregate_not_called_on_null-24    1.23µs ± 1%    0.80µs ± 1%  -35.02%  (p=0.000 n=10+9)
FuncExprTypeCheck/udf_same_name_as_builtin-24                1.50µs ± 0%    0.91µs ± 1%  -39.53%  (p=0.000 n=10+9)
FuncExprTypeCheck/udf_across_different_schemas-24            2.43µs ± 0%    1.80µs ± 1%  -25.90%  (p=0.000 n=8+10)
FuncExprTypeCheck/unary_operator-24                           344ns ± 2%     349ns ± 2%     ~     (p=0.065 n=10+10)
FuncExprTypeCheck/binary_operator-24                         1.36µs ± 0%    1.35µs ± 0%   -0.72%  (p=0.000 n=10+10)
FuncExprTypeCheck/comparison_operator-24                     2.16µs ± 0%    2.18µs ± 0%   +0.81%  (p=0.000 n=10+10)
FuncExprTypeCheck/tuple_comparison_operator-24               6.45µs ± 0%    6.47µs ± 1%     ~     (p=0.239 n=10+10)
FuncExprTypeCheck/tuple_in_operator-24                       1.13µs ± 1%    1.14µs ± 0%   +1.21%  (p=0.000 n=10+9)

name                                                       old alloc/op   new alloc/op   delta
FuncExprTypeCheck/builtin_called_on_null_input-24              132B ± 6%       34B ±10%  -74.53%  (p=0.000 n=10+10)
FuncExprTypeCheck/builtin_not_called_on_null_input-24          129B ± 0%       33B ± 2%  -74.81%  (p=0.000 n=8+8)
FuncExprTypeCheck/builtin_aggregate-24                         467B ± 0%       73B ± 0%  -84.37%  (p=0.000 n=9+8)
FuncExprTypeCheck/builtin_aggregate_not_called_on_null-24      145B ± 0%       32B ± 0%  -77.93%  (p=0.000 n=8+8)
FuncExprTypeCheck/udf_same_name_as_builtin-24                  273B ± 0%       64B ± 1%  -76.53%  (p=0.000 n=9+8)
FuncExprTypeCheck/udf_across_different_schemas-24              674B ± 0%      465B ± 0%  -30.90%  (p=0.000 n=8+9)
FuncExprTypeCheck/unary_operator-24                           0.00B          0.00B          ~     (all equal)
FuncExprTypeCheck/binary_operator-24                           113B ± 0%      113B ± 1%     ~     (p=0.214 n=6+9)
FuncExprTypeCheck/comparison_operator-24                       153B ± 0%      155B ± 4%     ~     (p=0.793 n=9+9)
FuncExprTypeCheck/tuple_comparison_operator-24                 894B ± 0%      892B ± 0%     ~     (p=0.057 n=9+8)
FuncExprTypeCheck/tuple_in_operator-24                         400B ± 0%      400B ± 0%     ~     (p=1.161 n=8+9)

name                                                       old allocs/op  new allocs/op  delta
FuncExprTypeCheck/builtin_called_on_null_input-24              7.00 ± 0%      3.00 ± 0%  -57.14%  (p=0.000 n=10+10)
FuncExprTypeCheck/builtin_not_called_on_null_input-24          7.00 ± 0%      3.00 ± 0%  -57.14%  (p=0.000 n=10+10)
FuncExprTypeCheck/builtin_aggregate-24                         16.0 ± 0%       4.0 ± 0%  -75.00%  (p=0.000 n=10+10)
FuncExprTypeCheck/builtin_aggregate_not_called_on_null-24      8.00 ± 0%      3.00 ± 0%  -62.50%  (p=0.000 n=10+10)
FuncExprTypeCheck/udf_same_name_as_builtin-24                  11.0 ± 0%       4.0 ± 0%  -63.64%  (p=0.000 n=10+10)
FuncExprTypeCheck/udf_across_different_schemas-24              16.0 ± 0%       9.0 ± 0%  -43.75%  (p=0.002 n=8+10)
FuncExprTypeCheck/unary_operator-24                            0.00           0.00          ~     (all equal)
FuncExprTypeCheck/binary_operator-24                           5.00 ± 0%      5.00 ± 0%     ~     (all equal)
FuncExprTypeCheck/comparison_operator-24                       5.00 ± 0%      5.00 ± 0%     ~     (all equal)
FuncExprTypeCheck/tuple_comparison_operator-24                 19.0 ± 0%      19.0 ± 0%     ~     (all equal)
FuncExprTypeCheck/tuple_in_operator-24                         7.00 ± 0%      7.00 ± 0%     ~     (all equal)
```

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
Is there a way we allocate both slices up front? I find all the type assertions pretty painful for the seemingly tiny number of cases where we want that second slice. WDYT?

> Reviewed 4 of 4 files at r1, 7 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89503#-:-NDie12A2RGueLvsj7i4:b9emtt8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by chengxiong-ruan** [comment]
@ajwerner not sure you hate it less or not. But I went to the direction of expanding the `overloadImpl` interface so that we can access several function properties without doing type assertion. To avoid value copy, I also make `Overload` methods to have pointer receiver. By doing all of these, it seemed that the performance was improve even greater than previous change by looking the type checking benchmark. (20% improvement -> 35% improvement in most cases) also good to see operators are not affected.

**Comment by ajwerner** [comment]
I didn't love it. I have a refactoring which I think I like more. I spent a little longer on it than I'd like to admit. See how it makes you feel. 	https://github.com/cockroachdb/cockroach/pull/89832

**Comment by chengxiong-ruan** [comment]
> I didn't love it. I have a refactoring which I think I like more. I spent a little longer on it than I'd like to admit. See how it makes you feel. #89832

It looks good. Though I feel like the complexity grows a bit, it's definitely much cleaner than my kinda ugly solution here. I'm also ok with slightly less cpu gain since I'm super happy with the much better allocation gain. Thanks for working on this! Closing this PR in favor of it.

**Comment by ajwerner** [comment]
The CPU gains are not clear. Did you rebase yours? Mine beat the old version of yours strictly when I pulled it yesterday. Probably it's not worth agonizing over the nanoseconds anymore on this one.

**Comment by chengxiong-ruan** [comment]
Yeah, I just rebased and ran it again...but yeah, I can sleep with it.

**Pull request closed without merging**
