### PR TITLE
server: add check for sql instance ID in tenant status server rpc handlers

### PR DESCRIPTION
**Pull request by lindseyjin**
Previously, most RPC handlers in tenant_status.go did not check if the
request was received by the status server before the sql pod had
finished its instance ID initialization. This commit adds in those
missing checks.

Release note: None

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72717#-:-MoLdaX71Mf-swaK8GPg:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lindseyjin)

**Review by lindseyjin — COMMENTED** [review]
As mentioned in #72660, I've created a separate PR for adding the missing `SQLInstanceID` checks to the rpc handlers in the tenant status server.

A few questions:
1. I added this to all of the functions mentioned in the `SQLStatusServer` interface except for the local ones (`ListLocalContentionEvents`, `ListLocalDistSQLFlows`) Should I be adding this check in those as well? 
2. Do I need to add this check onto the statusServer version of these function implementations as well?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72717#-:-MoLd3VA6HB30NA-0kgs:b-9dikwf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lindseyjin)

**Review by Azhng — APPROVED** [review]
1. Let's add them there, since those RPC endpoints are also exposed to RPC clients too as well
2. No there's no need for those checks in the regular `statusServer`, since the old `statusServer` does not depend on SQLInstance subsystem. 

Otherwise :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72717#-:-Mo_HlHkDcqXVIn4PWL3:b-x3dngl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @lindseyjin)

**Review by lindseyjin — COMMENTED** [review]
Done! Also added in functions to override `baseStatusServer` functions as discussed offline. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72717#-:-Mo_UudH1EOcjDdsnzUt:brz47ud)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @maryliag)

**Comment by lindseyjin** [comment]
blathers backport 21.2

**Pull request merged**
