### PR TITLE
sql: don't write/parse exprs in local mode

### PR DESCRIPTION
**Pull request by jordanlewis**
Note to reviewers: I resurrected this from some work last month. It still needs some cleanup. But it appears to work okay, so I'm sending it out for early feedback. I haven't performance tested against TPCC yet - kv has no change because there's no exprs to serialize in that workload.

Previously, expressions that needed to be used in processors were
written to a buffer with FmtParsable and re-parsed and type checked
with the parser, even if the processors were running in the local flow
mode. This was inefficient.

Now, we use a similar strategy to the "LocalPlanNode" system to avoid
this inefficiency. When we go to save an Expr to a processor spec, if
we're writing to a spec that will be inflated on the gateway, instead of
formatting the Expr to text, we save the Expr in a slice and record its
index. Then, at inflation time, instead of parsing the text we would
have written, we simply look up the Expr in the slice we saved it to.

This should eliminate one of the major inefficiences introduced by the
distsql merge.

Release note: None

### CODE REVIEW

**Review by rjnn — CHANGES_REQUESTED** [review]
Very elegantly done, I like where this is going. You should definitely clean it up and get this merged. :thumbsup: 

> Reviewed 5 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30464#-:-LMsL7VI2ib5e33vUnsr:b-y66ty2)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlplan/expression.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30464#-LMsGUaz8nVxW7MXt8Dr:-LMsGUaz8nVxW7MXt8Ds:b5eljz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/27ef0f8fa98c6b4e6d79a4d83597345a12c13f97/pkg/sql/distsqlplan/expression.go#L60)):*
> ```Go
> 	// the current plan is local, returning the index of the expression in the
> 	// list if so. Returns -1 if the current plan isn't local.
> 	MaybeAddLocalExpr(expr tree.TypedExpr, indexVarMap []int) int
> ```

nitty nit (sorry): given how easy Go makes returning multi-arguments, I don't like the C convention of returning -1. just return a bool and `ok, idx := ...` feels more natural.
___
*[pkg/sql/distsqlrun/expr.go, line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30464#-LMsJ2sm5-G3eID1puwf:-LMsJ2sm5-G3eID1puwg:bk61k19) ([raw file](https://github.com/cockroachdb/cockroach/blob/27ef0f8fa98c6b4e6d79a4d83597345a12c13f97/pkg/sql/distsqlrun/expr.go#L167)):*
> ```Go
> 		//fmt.Println(expr.LocalExprIdx, len(*evalCtx.LocalExprs))
> 		eh.expr = (*evalCtx.LocalExprs)[expr.LocalExprIdx-1]
> 		eh.vars.Rebind(eh.expr, true, false)
> ```

can you please add the comment `/* alsoReset, normalizeToNonNil */` to those bools?

**Review by asubiotto — APPROVED** [review]
LGTM. I believe you can also run `BenchmarkFlowSetup` to see the improvement in the best case since it has a where clause. Might be nice to run that and share the results.

> Reviewed 13 of 23 files at r1, 4 of 8 files at r2, 14 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30464#-:-LNC1lR2D-yP2SdjzDjS:b-bi7j49)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 3280 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30464#-LNBsMCM1nQLEYN1e8d5:-LNBsMCM1nQLEYN1e8d6:b-jdsjwm) ([raw file](https://github.com/cockroachdb/cockroach/blob/26d98ae83d68f98a99f852fab7da5a70f81c7c43/pkg/sql/distsql_physical_planner.go#L3280)):*
> ```Go
> 		ExtendedEvalCtx: evalCtx,
> 	}
> 	return ret
> ```

nit: `return &PlanningCtx{` immediately instead of assigning to ret?
___
*[pkg/sql/distsqlplan/aggregator_funcs_test.go, line 105 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30464#-LNBt1Py3JpLuDlDC6wI:-LNBt1Py3JpLuDlDC6wJ:b-6s25zz) ([raw file](https://github.com/cockroachdb/cockroach/blob/26d98ae83d68f98a99f852fab7da5a70f81c7c43/pkg/sql/distsqlplan/aggregator_funcs_test.go#L105)):*
> ```Go
> }
> 
> type fakeExprContext struct{}
> ```

nit: consider putting this in `utils_test.go`
___
*[pkg/sql/distsqlrun/data.proto, line 46 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30464#-LNC1Cx8Axb8du5FKfjl:-LNC1Cx90yK5VrJDwvhS:b-qh1fzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/26d98ae83d68f98a99f852fab7da5a70f81c7c43/pkg/sql/distsqlrun/data.proto#L46)):*
> ```protobuf
> message Expression {
>   // Don't generate a typedecl, so we can add the LocalExpr field.
>   option (gogoproto.typedecl) = false;
> ```

Nice. Haven't thought about this much but can we somehow use this for local processors too (asking because the problem this is trying to solve seems very similar)?

**Review by rjnn — CHANGES_REQUESTED** [review]
I like how that works, but we should make sure we have some more tests to ensure that we catch any proto changes. We might need a regression test util for `typedecl=false` struct declarations in particular.

> Reviewed 8 of 8 files at r2, 7 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30464#-:-LNBsSPa8NYLBVGA_EUj:b-1if61j)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/data.go, line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30464#-LNBrvM3Bz6Bua2OTWR_:-LNBrvM3Bz6Bua2OTWRa:bngy6qg) ([raw file](https://github.com/cockroachdb/cockroach/blob/26d98ae83d68f98a99f852fab7da5a70f81c7c43/pkg/sql/distsqlrun/data.go#L91)):*
> ```Go
> 
> // Expression is the representation of a SQL expression.
> // See data.proto for the corresponding proto definition.
> ```

I'd also explicitly say in the header comment that 
`automatic type declaration is suppressed in the protobuf via the typedecl=false , so that we can add the LocalExpr field (which is not serialized)`
___
*[pkg/sql/distsqlrun/data.go, line 105 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30464#-LNBsCACAdIeu2HTrGEC:-LNBsCACAdIeu2HTrGED:b41lrmk) ([raw file](https://github.com/cockroachdb/cockroach/blob/26d98ae83d68f98a99f852fab7da5a70f81c7c43/pkg/sql/distsqlrun/data.go#L105)):*
> ```Go
> 	LocalExpr tree.TypedExpr
> }
> ```

Also add a test that marshals and unmarshals an Expression struct so that any unwitting user who changes the proto without updating this type declaration will encounter an error.
___
*[pkg/sql/distsqlrun/data.proto, line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30464#-LNBqevN6IBayYgMlrW6:-LNBqevN6IBayYgMlrW7:b77pghb) ([raw file](https://github.com/cockroachdb/cockroach/blob/26d98ae83d68f98a99f852fab7da5a70f81c7c43/pkg/sql/distsqlrun/data.proto#L45)):*
> ```protobuf
> 
> message Expression {
>   // Don't generate a typedecl, so we can add the LocalExpr field.
> ```

This could use a succinct comment describing what `typedecl` does. From my reading of the gogoproto docs (which are sparse), this is also a beta feature. Not sure what our thoughts are on that, but you might want to rope someone in who knows what that means, and I don't want to be the one to give that a go ahead.

**Review by jordanlewis — COMMENTED** [review]
TFTRs! Arjun, I think the fact that the struct definition still needs to be right to allow the marshalling code to compile should assuage your concerns, but LMK if not.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30464#-:-LNCLtSL5bvDRV8vaJ_0:b-wyptrp)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlplan/expression.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30464#-LMsGUaz8nVxW7MXt8Dr:-LMsmG_2DoyrJha6O1NO:b-yh16lj) ([raw file](https://github.com/cockroachdb/cockroach/blob/27ef0f8fa98c6b4e6d79a4d83597345a12c13f97/pkg/sql/distsqlplan/expression.go#L60)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

nitty nit (sorry): given how easy Go makes returning multi-arguments, I don't like the C convention of returning -1. just return a bool and `ok, idx := ...` feels more natural.
</blockquote></details>

Done. Good call!
___
*[pkg/sql/distsqlrun/data.go, line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30464#-LNBrvM3Bz6Bua2OTWR_:-LNCLvB44D4NRPqcLwLk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26d98ae83d68f98a99f852fab7da5a70f81c7c43/pkg/sql/distsqlrun/data.go#L91)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

I'd also explicitly say in the header comment that 
`automatic type declaration is suppressed in the protobuf via the typedecl=false , so that we can add the LocalExpr field (which is not serialized)`


</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/data.go, line 105 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30464#-LNBsCACAdIeu2HTrGEC:-LNCLvXp2pEFLxVS0ZZE:b-pujaql) ([raw file](https://github.com/cockroachdb/cockroach/blob/26d98ae83d68f98a99f852fab7da5a70f81c7c43/pkg/sql/distsqlrun/data.go#L105)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Also add a test that marshals and unmarshals an Expression struct so that any unwitting user who changes the proto without updating this type declaration will encounter an error.
</blockquote></details>

I don't think we need to - the generated Marshal and Unmarshal code still references all of the fields of the proto that we defined in Expression, so it'll just fail to compile if somebody doesn't update the type declaration.
___
*[pkg/sql/distsqlrun/data.proto, line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30464#-LNBqevN6IBayYgMlrW6:-LNCM4S98iCS21MWLwev:b-to8c1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/26d98ae83d68f98a99f852fab7da5a70f81c7c43/pkg/sql/distsqlrun/data.proto#L45)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

This could use a succinct comment describing what `typedecl` does. From my reading of the gogoproto docs (which are sparse), this is also a beta feature. Not sure what our thoughts are on that, but you might want to rope someone in who knows what that means, and I don't want to be the one to give that a go ahead.
</blockquote></details>

It's beta, but the only behavior it changes is to not emit the `type Expression = struct{`... lines that we defined above. You can verify for yourself - the `pb.go` file didn't change except for removing that struct definition.
___
*[pkg/sql/distsqlrun/data.proto, line 46 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30464#-LNC1Cx8Axb8du5FKfjl:-LNCM4yjA9cfTsgfHuLw:bfj8d5r) ([raw file](https://github.com/cockroachdb/cockroach/blob/26d98ae83d68f98a99f852fab7da5a70f81c7c43/pkg/sql/distsqlrun/data.proto#L46)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Nice. Haven't thought about this much but can we somehow use this for local processors too (asking because the problem this is trying to solve seems very similar)?
</blockquote></details>

Yes, I wish I had known about this when doing the local processors work. It would have made things simpler.
___
*[pkg/sql/distsqlrun/expr.go, line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30464#-LMsJ2sm5-G3eID1puwf:-LMsmYQ09vini0awraK6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/27ef0f8fa98c6b4e6d79a4d83597345a12c13f97/pkg/sql/distsqlrun/expr.go#L167)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

can you please add the comment `/* alsoReset, normalizeToNonNil */` to those bools?
</blockquote></details>

Done.

**Review by jordanlewis — COMMENTED** [review]
Also, squashed to 1 commit

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30464#-:-LNCNHo97-AV6DvuAnDP:bz3btnt)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by rjnn — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30464#-:-LNCPrYUE3iISuiJAW3b:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsqlrun/data.go, line 105 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30464#-LNBsCACAdIeu2HTrGEC:-LNCNdP_37PoN3bKjU_f:bbvotq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/26d98ae83d68f98a99f852fab7da5a70f81c7c43/pkg/sql/distsqlrun/data.go#L105)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I don't think we need to - the generated Marshal and Unmarshal code still references all of the fields of the proto that we defined in Expression, so it'll just fail to compile if somebody doesn't update the type declaration.
</blockquote></details>

OK. I tried it out, and compilation failed. SGTM.
___
*[pkg/sql/distsqlrun/data.proto, line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30464#-LNBqevN6IBayYgMlrW6:-LNCPou425RsBOHFbnvz:b-81nlyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/26d98ae83d68f98a99f852fab7da5a70f81c7c43/pkg/sql/distsqlrun/data.proto#L45)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

It's beta, but the only behavior it changes is to not emit the `type Expression = struct{`... lines that we defined above. You can verify for yourself - the `pb.go` file didn't change except for removing that struct definition.
</blockquote></details>

SGTM.

**Comment by jordanlewis** [comment]
```
name                          old time/op    new time/op    delta
FlowSetup/distribute=true-8     43.1µs ±11%    42.9µs ± 2%     ~     (p=0.853 n=10+10)
FlowSetup/distribute=false-8    37.5µs ± 3%    30.6µs ± 7%  -18.35%  (p=0.000 n=10+10)

name                          old alloc/op   new alloc/op   delta
FlowSetup/distribute=true-8     38.1kB ± 0%    38.5kB ± 0%   +1.18%  (p=0.000 n=9+9)
FlowSetup/distribute=false-8    32.3kB ± 0%    30.2kB ± 0%   -6.65%  (p=0.000 n=10+8)

name                          old allocs/op  new allocs/op  delta
FlowSetup/distribute=true-8        342 ± 0%       344 ± 0%   +0.59%  (p=0.000 n=10+10)
FlowSetup/distribute=false-8       296 ± 0%       258 ± 0%  -12.84%  (p=0.000 n=10+10)```

The extra allocations in `distribute=true` are unexpected, but will be tamped down by #30556 once that gets cleaned up.

**Pull request merged**
