### PR TITLE
exec: plan sum aggregate

### PR DESCRIPTION
**Pull request by jordanlewis**
On top of #32120.

This adds planning for sum aggregates to experimental_vectorize.

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32138)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32138#-LR7wTXv8A17c9pUWqYQ:-LR7wTXw6nTbsMhhbdB2:btanbuh) ([raw file](https://github.com/cockroachdb/cockroach/blob/689c2a4bbe72bad87bdbf5a292d6ba9732b1cebc/pkg/sql/distsqlrun/column_exec_setup.go#L74)):*
> ```Go
> 		for i, col := range aggSpec.GroupCols {
> 			if !orderedCols.Contains(int(col)) {
> 				allSorted = false
> ```

I would move the `unsorted aggregation not supported` error here and get rid of `allSorted`.
___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32138#-LR7zWLf5YfetvzjFOIC:-LR7zWLf5YfetvzjFOID:b-abc374) ([raw file](https://github.com/cockroachdb/cockroach/blob/689c2a4bbe72bad87bdbf5a292d6ba9732b1cebc/pkg/sql/distsqlrun/column_exec_setup.go#L111)):*
> ```Go
> 				case types.Int8, types.Int16, types.Int32, types.Int64:
> 					// TODO(asubiotto): prevent this somehow
> 					return nil, errors.New("sum on int cols not supported (use sum_int)")
> ```

Am I right in saying that what needs to be done here is cast the output to a decimal when done? If so, could you add that context to the TODO?
___
*[pkg/sql/exec/aggregator.go, line 128 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32138#-LR8-Z6Q7-YAkFo2MOL-:-LR8-Z6Q7-YAkFo2MOL0:b-uuuqzi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2f8e89e0cae4b3cd8b0c8f142d71473cb99e7aa/pkg/sql/exec/aggregator.go#L128)):*
> ```Go
> 	if len(groupCols) == 0 {
> 		// If there were no groupCols, we can't rely on the distinct operators to
> 		// mark the first row as distinct, so we have to do it ourselves. Set up a
> ```

Would it make sense to make this the responsibility of the distinct operator?
___
*[pkg/sql/exec/aggregator.go, line 215 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32138#-LR8-qCDATs5gzZpvHId:-LR8-qCE8ZKYAA9msBR8:b-9qxfh1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2f8e89e0cae4b3cd8b0c8f142d71473cb99e7aa/pkg/sql/exec/aggregator.go#L215)):*
> ```Go
> 
> 	for a.scratch.resumeIdx < a.scratch.outputSize {
> 		fmt.Println(a.groupCol[0])
> ```

Stray `Println` here and below.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32138)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32138#-LR7wTXv8A17c9pUWqYQ:-LRAYBjEEQkfPPEQHWPq:b32cc9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/689c2a4bbe72bad87bdbf5a292d6ba9732b1cebc/pkg/sql/distsqlrun/column_exec_setup.go#L74)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I would move the `unsorted aggregation not supported` error here and get rid of `allSorted`.
</blockquote></details>

Great point - done.
___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32138#-LR7zWLf5YfetvzjFOIC:-LRAYKcQ6HzGIuoRX0QX:bntqpdt) ([raw file](https://github.com/cockroachdb/cockroach/blob/689c2a4bbe72bad87bdbf5a292d6ba9732b1cebc/pkg/sql/distsqlrun/column_exec_setup.go#L111)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Am I right in saying that what needs to be done here is cast the output to a decimal when done? If so, could you add that context to the TODO?
</blockquote></details>

I'm going to delete the TODO as the picture is more complex. You can't just cast to a decimal when done, since there could be overflows. I think the right thing to do would be to make int64 sums actually use an int128 (2 int64s) accumulator and check at the end of each batch for overflow - if there's an overflow, convert the accumulator to a decimal.

And the int32/int16/int8 sums could just write to int64s as they do today.
___
*[pkg/sql/exec/aggregator.go, line 128 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32138#-LR8-Z6Q7-YAkFo2MOL-:-LRAZ-ekBwdvyjOVdy0g:b5kuu36) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2f8e89e0cae4b3cd8b0c8f142d71473cb99e7aa/pkg/sql/exec/aggregator.go#L128)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Would it make sense to make this the responsibility of the distinct operator?
</blockquote></details>

I'm not really sure... on the one hand, it would somewhat make sense to have the distinct operator consider nothing distinct after the first row if there are no columns to distinct upon. On the other hand, that's not really an allowable mode for the distinct sql keyword - you always have to have columns.
___
*[pkg/sql/exec/aggregator.go, line 215 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32138#-LR8-qCDATs5gzZpvHId:-LRC_iho4uiKTAF5OrUh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2f8e89e0cae4b3cd8b0c8f142d71473cb99e7aa/pkg/sql/exec/aggregator.go#L215)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Stray `Println` here and below.
</blockquote></details>

Done.

**Review by asubiotto — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32138)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32138#-LR7zWLf5YfetvzjFOIC:-LRCrk-j8lIPkuidYdij:b-7hsrro) ([raw file](https://github.com/cockroachdb/cockroach/blob/689c2a4bbe72bad87bdbf5a292d6ba9732b1cebc/pkg/sql/distsqlrun/column_exec_setup.go#L111)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I'm going to delete the TODO as the picture is more complex. You can't just cast to a decimal when done, since there could be overflows. I think the right thing to do would be to make int64 sums actually use an int128 (2 int64s) accumulator and check at the end of each batch for overflow - if there's an overflow, convert the accumulator to a decimal.

And the int32/int16/int8 sums could just write to int64s as they do today.
</blockquote></details>

Right, I meant this with the assumption that we're not considering overflows (just to get it working type-wise). I would keep the TODO just to remember why and have the context behind the reason for this error in a couple of months time.
___
*[pkg/sql/exec/aggregator.go, line 128 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32138#-LR8-Z6Q7-YAkFo2MOL-:-LRCt00LARZzA9FiKdOX:b-gxztsp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2f8e89e0cae4b3cd8b0c8f142d71473cb99e7aa/pkg/sql/exec/aggregator.go#L128)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I'm not really sure... on the one hand, it would somewhat make sense to have the distinct operator consider nothing distinct after the first row if there are no columns to distinct upon. On the other hand, that's not really an allowable mode for the distinct sql keyword - you always have to have columns.
</blockquote></details>

Fair enough.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32138)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32138#-LR7zWLf5YfetvzjFOIC:-LRDTuE48UUmrSmH3EDW:b-hd8r99) ([raw file](https://github.com/cockroachdb/cockroach/blob/689c2a4bbe72bad87bdbf5a292d6ba9732b1cebc/pkg/sql/distsqlrun/column_exec_setup.go#L111)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Right, I meant this with the assumption that we're not considering overflows (just to get it working type-wise). I would keep the TODO just to remember why and have the context behind the reason for this error in a couple of months time.
</blockquote></details>

Oh, right. Okay, added back.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32138)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/aggregator.go, line 128 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32138#-LR8-Z6Q7-YAkFo2MOL-:-LRDVBr786JHRbX_Roe7:b4iqaj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2f8e89e0cae4b3cd8b0c8f142d71473cb99e7aa/pkg/sql/exec/aggregator.go#L128)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Fair enough.
</blockquote></details>

I'm down to fix this at some point but for now I'll leave it, just to get this part finished.

**Pull request merged**
