### PR TITLE
storage,sql: add a fast mode to CheckConsistency and expose via SQL

### PR DESCRIPTION
**Pull request by tbg**
It has always been difficult to diagnose consistency check failures for
to three reasons:

1. they're rare (and often go undetected)
2. they require the data directories to meaningfully investigate
3. failures often occur long after the likely triggers

This PR works to address some of all of these. Note that none of this is
for end user consumption at this point.

We add a "quick" mode to CheckConsistency. In that mode, the hash of a
replica is simply the hash of its RangeAppliedState. We know only of one
incident in which a detected replica inconsistency did not include this
key. This is because the consistently replicated MVCCStats are stored
under this key, and because consistency failures are almost always
caused by to an "atomic" failure to apply a batch.
That is, when a write gets lost, it's very likely that on the replica
losing the write the corresponding stats update will also be missing.

The only known exception is one recent incident involving only time
series data, where there is vague hope that the problem might instead
have been caused by some problem specific to RocksDB merges.

Having the quick mode available makes it feasible to run the consistency
checks throughout our various roachtests, and to detect more
inconsistencies close to when they happen, both of which will naturally
improve our ability to get to the bottom of them.

Consistency checks are usually run on a queue at low frequency, making
it hard to predict when a given range will be checked. To make this
more convenient, we add a sql builtin `crdb_internal.check_consistency`
which does not trigger fatal node errors when it detects an
inconsistency, and takes three parameters:

1. whether to use quick mode (bool)
2. start key (byte)
3. end key (byte)

These three inputs roughly translate to a

    CheckConsistencyRequest{Key: key, EndKey: end_key, Quick: quick}.

and the output is returned as a array of tuples, which can be consumed
conveniently via the desired variant of

```
SELECT
	(t).*
FROM
	unnest(
		crdb_internal.check_consistency(
			true,
			e'\\x02'::BYTES,
			e'\\xff'::BYTES
		)
	)
		AS t;

  range_id |      status      | detail
+----------+------------------+--------+
         1 | RANGE_CONSISTENT |
         2 | RANGE_CONSISTENT |
         3 | RANGE_CONSISTENT |
         4 | RANGE_CONSISTENT |
         5 | RANGE_CONSISTENT |
         6 | RANGE_CONSISTENT |
         7 | RANGE_CONSISTENT |
         8 | RANGE_CONSISTENT |
         9 | RANGE_CONSISTENT |
        10 | RANGE_CONSISTENT |
        11 | RANGE_CONSISTENT |
        12 | RANGE_CONSISTENT |
        13 | RANGE_CONSISTENT |
        14 | RANGE_CONSISTENT |
        15 | RANGE_CONSISTENT |
        16 | RANGE_CONSISTENT |
        17 | RANGE_CONSISTENT |
        18 | RANGE_CONSISTENT |
        19 | RANGE_CONSISTENT |
        20 | RANGE_CONSISTENT |
```

The plan is to sprinkle this through some candidate roachtests in the
hope that something will fall out.

Release note: None

### CODE REVIEW

**Review by andreimatei — CHANGES_REQUESTED** [review]
bonus points if you also add a function for checking the accuracy of the `MVCCStats`.

> Reviewed 3 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-:-LaHJXT438Yyr6mlTP1f:b-lrsgb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/roachpb/api.proto, line 435 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaGhXYR3_YwSDbKn08X:-LaGhXYR3_YwSDbKn08Y:b-lj9vjk) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/roachpb/api.proto#L435)):*
> ```protobuf
>   // log a diff of inconsistencies if such inconsistencies are found.
>   bool with_diff = 2;
>   bool quick = 3;
> ```

pls comment.
And also can we give this a more descriptive name like "consult only stats"? Elsewhere too.
___
*[pkg/roachpb/api.proto, line 439 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaGh_m5B_6IBwq-sE7k:-LaGh_m5B_6IBwq-sE7l:b-k5hpzo) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/roachpb/api.proto#L439)):*
> ```protobuf
> 
> // A CheckConsistencyResponse is the return value from the CheckConsistency() method.
> // If a replica finds itself to be inconsistent with its lease holder it will panic.
> ```

is this comment still the whole story?
___
*[pkg/roachpb/api.proto, line 460 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaGhkkHCSO_34V96lrl:-LaGhkkHCSO_34V96lrm:b499yls) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/roachpb/api.proto#L460)):*
> ```protobuf
>   }
> 
>   repeated Result result = 2 [(gogoproto.nullable) = false];
> ```

say something about how there'll be one entry for each range within the requested span? Will they be sorted?
___
*[pkg/roachpb/api.proto, line 1052 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaGhrCg4UT_TGEYRerd:-LaGhrCg4UT_TGEYRere:bjenqlp) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/roachpb/api.proto#L1052)):*
> ```protobuf
>   // used in logging a diff during checksum verification.
>   bool snapshot = 4;
>   bool quick = 5;
> ```

pls comment.
___
*[pkg/sql/logictest/testdata/logic_test/builtin_function, line 2081 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaGgQ-W0TBnbx20Ss7Z:-LaGgQ-W0TBnbx20Ss7_:bxvo1ia) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2939ec9a4f15b7fb8683a5805deeb241953e7aa/pkg/sql/logictest/testdata/logic_test/builtin_function#L2081)):*
> ```
> # Ensure that privileged builtins work from DistSQL.
> statement ok
> SELECT crdb_internal.set_vmodule('foo=2') FROM foo
> ```

what happened to this test? You've left part of the comment.
___
*[pkg/sql/logictest/testdata/logic_test/builtin_function, line 2082 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaHHomYAuDXd9AuYQ3-:-LaHHomYAuDXd9AuYQ30:b-jsdkxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/sql/logictest/testdata/logic_test/builtin_function#L2082)):*
> ```
> # Sanity-check crdb_internal.check_consistency works.
> query ITT
> SELECT (t).* FROM unnest(crdb_internal.check_consistency(true, '\x02'::bytea, '\xff'::bytea)) as t WHERE (t).range_id = 1
> ```

can you comment about the start and end keys and why the expected result is `indeterminate`?
___
*[pkg/sql/sem/builtins/builtins.go, line 2802 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaGh09w0vR4XRAjhVsE:-LaGh09w0vR4XRAjhVsF:brvdxt6) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/sql/sem/builtins/builtins.go#L2802)):*
> ```Go
> 					Quick: quick,
> 				})
> 				if err := ctx.Txn.DB().Run(ctx.Ctx(), &b); err != nil {
> ```

I'm assuming these request don't need to be transactional. If you have access to the `db`, I'd use that instead of ctx.Txn.
___
*[pkg/sql/sem/builtins/builtins.go, line 2821 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaGgcyr4Vim3TwOM_aZ:-LaGgcyr4Vim3TwOM_a_:buz98ro) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/sql/sem/builtins/builtins.go#L2821)):*
> ```Go
> 				return arr, nil
> 			},
> 			// Example usage:
> ```

put this in the `Info`.

And pls comment the arguments and ret vals
___
*[pkg/storage/replica_consistency.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaGivCe8IoH0zv7P0JU:-LaGivCe8IoH0zv7P0JV:bjjcert) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/storage/replica_consistency.go#L75)):*
> ```Go
> // other replicas. When an inconsistency is detected and no diff was requested,
> // the consistency check will be re-run to collect a diff, which is then printed
> // before calling `log.Fatal`.
> ```

comment is stale
___
*[pkg/storage/replica_consistency.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaGhJMH3hUg9Az1X5Qz:-LaGhJMH3hUg9Az1X5R-:b-wbyub1) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/storage/replica_consistency.go#L77)):*
> ```Go
> // before calling `log.Fatal`.
> func (r *Replica) CheckConsistency(
> 	ctx context.Context, args roachpb.CheckConsistencyRequest, fatalOnMismatch bool,
> ```

pls make that bool an enum
___
*[pkg/storage/replica_consistency.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaHI5It6pQjjEaW8jMf:-LaHI5It6pQjjEaW8jMg:bdnd7ce) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/storage/replica_consistency.go#L94)):*
> ```Go
> 
> 	var inconsistencyCount int
> 	var missingCount int
> ```

what's this var? It doesn't seem to be used for anything.
___
*[pkg/storage/replica_consistency.go, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaHIT3g9178GSk-eIzx:-LaHIT3h3HmUIZZBtVeC:bfzzqte) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/storage/replica_consistency.go#L124)):*
> ```Go
> 		res.Status = roachpb.CheckConsistencyResponse_RANGE_INCONSISTENT
> 	} else if !args.Quick {
> 		res.Status = roachpb.CheckConsistencyResponse_RANGE_CONSISTENT
> ```

I think we should return `RANGE_CONSISTENT` even if `args.Quick`. It's weird to have a flavor of the RPC for which the possible responses are `inconsistent` and `indeterminate`.
I think we should make `INDETERMINATE` mean strictly that we failed contacting some replicas. Which btw, I don't really understand how it's handled... Did you intend to do something with `missingCount`? 
___
*[pkg/storage/replica_consistency.go, line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaHIIV20v8CfZ9oiTjW:-LaHIIV20v8CfZ9oiTjX:baho6z1) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/storage/replica_consistency.go#L190)):*
> ```Go
> 
> 	// No diff was printed, so we want to re-run with diff.
> 	// Note that this will call Fatal recursively in `CheckConsistency` (in the code above).
> ```

update comment
___
*[pkg/storage/storagepb/proposer_kv.proto, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaGhSe_6G34tti4-rpQ:-LaGhSe_6G34tti4-rpR:b-iz4ctr) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/storage/storagepb/proposer_kv.proto#L81)):*
> ```protobuf
>   // should be saved so that a diff of divergent replicas can later be computed.
>   bool save_snapshot = 2;
>   bool quick = 3;
> ```

pls comment

**Review by andreimatei — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35861)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/storage/replica_consistency.go, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaM20bMAj_VY-HewFc7:-LaM20bMAj_VY-HewFc8:b-mcton3) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/storage/replica_consistency.go#L130)):*
> ```Go
> 
> 	if !fatalOnMismatch {
> 		return resp, nil
> ```

how come we early return here and don't do the stats recomputation? What's the thinking?

**Review by andreimatei — COMMENTED** [review]
The `\x02` sprinkled everywhere is some `LocalMax`. It'd be cool if that was documented. And also if a `null` input would translate to that, and a `null` input for the end key would represent the end of the key space.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-:-LaqqrmM-kqAoHWDUy8P:b431hyx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Review by tbg — COMMENTED** [review]
Addressed the comments, RFAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-:-Lau1O730L_P_-7kKWMm:b3h8vw9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/roachpb/api.proto, line 435 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaGhXYR3_YwSDbKn08X:-Latsm5I3FCIAZ5Vo6Ia:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/roachpb/api.proto#L435)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls comment.
And also can we give this a more descriptive name like "consult only stats"? Elsewhere too.
</blockquote></details>

Done.
___
*[pkg/roachpb/api.proto, line 439 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaGh_m5B_6IBwq-sE7k:-Latszd81bUSprkNOFXV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/roachpb/api.proto#L439)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

is this comment still the whole story?
</blockquote></details>

Done.
___
*[pkg/roachpb/api.proto, line 460 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaGhkkHCSO_34V96lrl:-Latt-S-8VLm_voaUJ44:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/roachpb/api.proto#L460)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

say something about how there'll be one entry for each range within the requested span? Will they be sorted?
</blockquote></details>

Done.
___
*[pkg/roachpb/api.proto, line 1052 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaGhrCg4UT_TGEYRerd:-Latt5W58bDWsWBT0RST:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/roachpb/api.proto#L1052)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls comment.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/builtin_function, line 2081 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaGgQ-W0TBnbx20Ss7Z:-Latt6Jd6_HtR4amIZnK:br2589r) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2939ec9a4f15b7fb8683a5805deeb241953e7aa/pkg/sql/logictest/testdata/logic_test/builtin_function#L2081)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what happened to this test? You've left part of the comment.
</blockquote></details>

Done. I didn't like that test, it called vmodule(foo=2) and didn't reset it. What the hell? Also unclear what it was testing.
___
*[pkg/sql/logictest/testdata/logic_test/builtin_function, line 2082 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaHHomYAuDXd9AuYQ3-:-LattBeY591Zg2-TqGza:b-b3jbv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/sql/logictest/testdata/logic_test/builtin_function#L2082)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can you comment about the start and end keys and why the expected result is `indeterminate`?
</blockquote></details>

Obsolete.
___
*[pkg/sql/sem/builtins/builtins.go, line 2802 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaGh09w0vR4XRAjhVsE:-LattEX185gwWG6oX23Y:btg2u3g) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/sql/sem/builtins/builtins.go#L2802)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'm assuming these request don't need to be transactional. If you have access to the `db`, I'd use that instead of ctx.Txn.
</blockquote></details>

I'm using the DB. I don't know of a better way to get my fingers on it, if you know one please let me know.
___
*[pkg/sql/sem/builtins/builtins.go, line 2821 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaGgcyr4Vim3TwOM_aZ:-LatttIhCkzQ43dAMNJ6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/sql/sem/builtins/builtins.go#L2821)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

put this in the `Info`.

And pls comment the arguments and ret vals
</blockquote></details>

Done.
___
*[pkg/storage/replica_consistency.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaGivCe8IoH0zv7P0JU:-LatulKR0JvucNA-e8KJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/storage/replica_consistency.go#L75)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

comment is stale
</blockquote></details>

Done.
___
*[pkg/storage/replica_consistency.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaGhJMH3hUg9Az1X5Qz:-Latulbz1tlPEdxU2l4w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/storage/replica_consistency.go#L77)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls make that bool an enum
</blockquote></details>

Done.
___
*[pkg/storage/replica_consistency.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaHI5It6pQjjEaW8jMf:-LatumGtEPA5jEDqIlT2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/storage/replica_consistency.go#L94)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what's this var? It doesn't seem to be used for anything.
</blockquote></details>

Done.
___
*[pkg/storage/replica_consistency.go, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaHIT3g9178GSk-eIzx:-LatunF-0dplX7UvX5EG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/storage/replica_consistency.go#L124)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think we should return `RANGE_CONSISTENT` even if `args.Quick`. It's weird to have a flavor of the RPC for which the possible responses are `inconsistent` and `indeterminate`.
I think we should make `INDETERMINATE` mean strictly that we failed contacting some replicas. Which btw, I don't really understand how it's handled... Did you intend to do something with `missingCount`? 
</blockquote></details>

Done.
___
*[pkg/storage/replica_consistency.go, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaM20bMAj_VY-HewFc7:-Latuo7AEB49jCic2wAJ:b-8rzjcl) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/storage/replica_consistency.go#L130)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

how come we early return here and don't do the stats recomputation? What's the thinking?
</blockquote></details>

The thinking is that this isn't something this method ought to be triggering in the first place.
___
*[pkg/storage/replica_consistency.go, line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaHIIV20v8CfZ9oiTjW:-LatuttK5uJYjABUj_8B:b-2k3skf) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/storage/replica_consistency.go#L190)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

update comment
</blockquote></details>

Update how?
___
*[pkg/storage/storagepb/proposer_kv.proto, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaGhSe_6G34tti4-rpQ:-Latuw1V2l0SGmPgQ4tZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/storage/storagepb/proposer_kv.proto#L81)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls comment
</blockquote></details>

Done.

**Review by andreimatei — APPROVED** [review]
LGTM except it looks to me that a diff is not generated if a range is found to be inconsistent, right? Could we generate it? :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-:-Lav8OwxBIXLsPozlp25:b-y4ivj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[docs/generated/sql/functions.md, line 939 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-Lav1Ykd-fl-wdHHmjih:-Lav1Ykd-fl-wdHHmjii:b4eb4yi) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d738a4d268719006ab673df55d893bf99290045/docs/generated/sql/functions.md#L939)):*
> ```
> stats_only should only be used...
> ```

stats_only is the cheap one, right? So why do you call this out to be expensive? Is that sentence missing a negation?
___
*[pkg/roachpb/api.proto, line 439 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-Lav1wmR9LgoqK3U_W-8:-Lav1wmR9LgoqK3U_W-9:btre2dq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d738a4d268719006ab673df55d893bf99290045/pkg/roachpb/api.proto#L439)):*
> ```protobuf
>     //
>     // TODO(tbg): these semantics are an artifact of how consistency checks were
>     // first implemented. The extra behavior here would move to the consistency
> ```

s/would/should
___
*[pkg/roachpb/api.proto, line 495 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-Lav7Eo24O_jb9PB6IoW:-Lav7Eo24O_jb9PB6IoX:b7im8jm) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d738a4d268719006ab673df55d893bf99290045/pkg/roachpb/api.proto#L495)):*
> ```protobuf
>     int64 range_id = 1 [(gogoproto.customname) = "RangeID", (gogoproto.casttype) = "RangeID"];
>     Status status = 2;
>     string detail = 3;
> ```

does the detail include the diff, if there's a diff? If so, please say that in a comment.
___
*[pkg/sql/sem/builtins/builtins.go, line 2802 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaGh09w0vR4XRAjhVsE:-Lav3s955xz6g_UKCMMV:b-rhk6ve) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/sql/sem/builtins/builtins.go#L2802)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I'm using the DB. I don't know of a better way to get my fingers on it, if you know one please let me know.
</blockquote></details>

ugh yeah I guess the DB is not part of the `EvalContext`. Whatevs.
___
*[pkg/sql/sem/builtins/builtins.go, line 2797 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-Lav3O8H5qGbPbw6hYJG:-Lav3O8H5qGbPbw6hYJH:b-4r9q0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d738a4d268719006ab673df55d893bf99290045/pkg/sql/sem/builtins/builtins.go#L2797)):*
> ```Go
> 				}
> 
> 				kFrom := roachpb.Key(*args[1].(*tree.DBytes))
> ```

so do `NULLs` work here, or would it be easy to make them work?
___
*[pkg/sql/sem/builtins/builtins.go, line 2845 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-Lav47M6BDPe2gHlWs_J:-Lav47M6BDPe2gHlWs_K:b-bp46a0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d738a4d268719006ab673df55d893bf99290045/pkg/sql/sem/builtins/builtins.go#L2845)):*
> ```Go
> 			},
> 			Info: "Runs a consistency check on ranges touching the specified key range. " +
> 				"the start and end keys default to the minimum and maximum possible. " +
> ```

I'm not sure what "default to" means; maybe say `if empty, ...`.

**Review by tbg — COMMENTED** [review]
I made the change so that when you do the full computation, a diff is generated. Generating a diff when we were only comparing the stats amounts to re-running another internal consistency check and is exactly the kind of work I want to move to higher layers in the future.

Hmm, I should return the `start_key` in the result so that we can programmatically run deep checks on the individual ranges when the shallow check fails without bending over backwards. Done.

I'll merge this tomorrow morning, but feel free to bors it for me if TC is green

TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-:-LavvmDv0zOpezwCWEWX:b-1lk1gj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[docs/generated/sql/functions.md, line 939 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-Lav1Ykd-fl-wdHHmjih:-LavuvP-9Ad5ZbqFgQuK:b-4c5ezp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d738a4d268719006ab673df55d893bf99290045/docs/generated/sql/functions.md#L939)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> ```
> stats_only should only be used...
> ```

stats_only is the cheap one, right? So why do you call this out to be expensive? Is that sentence missing a negation?
</blockquote></details>

Good catch, done.
___
*[pkg/roachpb/api.proto, line 439 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-Lav1wmR9LgoqK3U_W-8:-Lavv1eq2GE_Seeuj4PL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d738a4d268719006ab673df55d893bf99290045/pkg/roachpb/api.proto#L439)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/would/should
</blockquote></details>

Done.
___
*[pkg/roachpb/api.proto, line 495 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-Lav7Eo24O_jb9PB6IoW:-Lavv4DY7S_7qckCOUCE:bil4uan) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d738a4d268719006ab673df55d893bf99290045/pkg/roachpb/api.proto#L495)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

does the detail include the diff, if there's a diff? If so, please say that in a comment.
</blockquote></details>

It does if `WithDiff` was specified. Updated.
___
*[pkg/sql/sem/builtins/builtins.go, line 2802 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-LaGh09w0vR4XRAjhVsE:-LavvU805NarfPWtROkC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ba51736f38397ee9d4ad1659783478d3835164/pkg/sql/sem/builtins/builtins.go#L2802)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

ugh yeah I guess the DB is not part of the `EvalContext`. Whatevs.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/builtins.go, line 2797 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-Lav3O8H5qGbPbw6hYJG:-LavvSIWCsPd8tIAUVtj:b-t545im) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d738a4d268719006ab673df55d893bf99290045/pkg/sql/sem/builtins/builtins.go#L2797)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

so do `NULLs` work here, or would it be easy to make them work?
</blockquote></details>

I don't want to get into that.
___
*[pkg/sql/sem/builtins/builtins.go, line 2845 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35861#-Lav47M6BDPe2gHlWs_J:-LavvjA6DHnextcuemDa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d738a4d268719006ab673df55d893bf99290045/pkg/sql/sem/builtins/builtins.go#L2845)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'm not sure what "default to" means; maybe say `if empty, ...`.
</blockquote></details>

Done.

**Comment by tbg** [comment]
bors r=andreimatei

**Pull request merged**
