### PR TITLE
ui: add Range Merges to Replication -> Range Operations graph

### PR DESCRIPTION
**Pull request by nvb**
Release note (admin ui change): Range merges will now show up in the Range Operations graph.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36198)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @vilterp)

**Review by celiala — APPROVED** [review]
:lgtm:

**Comment by nvanbenschoten** [comment]
`TestLogic/local/rename_table` flake.

bors r+

**Pull request merged**
