### PR TITLE
sql: fix sub-query plan expansion for queries with indexed joins.

### LINKED ISSUE #6986: sql: can't expandPlan twice!
The daily logic tests are failing. Guessing this is a recent change to subquery handling. See https://groups.google.com/a/cockroachlabs.com/forum/?hl=en#!topic/daily/Ki7HOhrM1qY.

```
panic: can't expandPlan twice!

goroutine 501 [running]:
panic(0x15c6760, 0xc820a412e0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/cockroachdb/cockroach/sql.(*selectTopNode).expandPlan(0xc820a95240, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/select_top.go:65 +0xa1
github.com/cockroachdb/cockroach/sql.(*subqueryPlanVisitor).VisitPre(0xc820dc0ed8, 0x7f66f3c423e0, 0xc8209f4540, 0xc820e0a4e8, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/subquery.go:200 +0xcd
github.com/cockroachdb/cockroach/sql/parser.WalkExpr(0x7f66f3b30708, 0xc820dc0ed8, 0x7f66f3c423e0, 0xc8209f4540, 0x0, 0x0, 0x1862900)
	/go/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:407 +0x56
github.com/cockroachdb/cockroach/sql/parser.(*ComparisonExpr).Walk(0xc820809500, 0x7f66f3b30708, 0xc820dc0ed8, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:164 +0xce
github.com/cockroachdb/cockroach/sql/parser.WalkExpr(0x7f66f3b30708, 0xc820dc0ed8, 0x7f66f3c3bd60, 0xc820809500, 0x7f66f3c3bd60, 0xc820809500, 0xc8209f4300)
	/go/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:410 +0x98
github.com/cockroachdb/cockroach/sql/parser.(*OrExpr).Walk(0xc820861680, 0x7f66f3b30708, 0xc820dc0ed8, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:260 +0xc0
github.com/cockroachdb/cockroach/sql/parser.WalkExpr(0x7f66f3b30708, 0xc820dc0ed8, 0x7f66f3c3cd88, 0xc820861680, 0x7f66f3c3cd88, 0xc820861680, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:410 +0x98
github.com/cockroachdb/cockroach/sql/parser.(*AndExpr).Walk(0xc8208616b0, 0x7f66f3b30708, 0xc820dc0ed8, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:58 +0x5f
github.com/cockroachdb/cockroach/sql/parser.WalkExpr(0x7f66f3b30708, 0xc820dc0ed8, 0x7f66f3bbc4a8, 0xc8208616b0, 0x7f66f3bbc4a8, 0xc8208616b0, 0x7f66f3c80000)
	/go/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:410 +0x98
github.com/cockroachdb/cockroach/sql.(*planner).expandSubqueryPlans(0xc820dc0890, 0x7f66f3bbc4a8, 0xc8208616b0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/subquery.go:223 +0x107
github.com/cockroachdb/cockroach/sql.(*scanNode).expandPlan(0xc820d52580, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/scan.go:118 +0x81
github.com/cockroachdb/cockroach/sql.(*indexJoinNode).expandPlan(0xc8208095e0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/join.go:156 +0x6b
github.com/cockroachdb/cockroach/sql.(*selectNode).expandPlan(0xc8202f77a0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/select.go:427 +0x904
github.com/cockroachdb/cockroach/sql.(*selectTopNode).expandPlan(0xc820b0dec0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/select_top.go:71 +0xf4
github.com/cockroachdb/cockroach/sql.(*planner).makePlan(0xc820dc0890, 0x7f66f3bb6848, 0xc820a45590, 0x829f01, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/plan.go:215 +0xe2
github.com/cockroachdb/cockroach/sql.(*Executor).execStmt(0xc8203042a0, 0x7f66f3bb6848, 0xc820a45590, 0xc820dc0890, 0xc820a45501, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:923 +0x93
github.com/cockroachdb/cockroach/sql.(*Executor).execStmtInOpenTxn(0xc8203042a0, 0x7f66f3bb6848, 0xc820a45590, 0xc820dc0890, 0x101, 0xc820dc0828, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:826 +0x545
github.com/cockroachdb/cockroach/sql.(*Executor).execStmtsInCurrentTxn(0xc8203042a0, 0xc820a402a0, 0x1, 0x1, 0xc820dc0890, 0xc820dc0828, 0x1f10101, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:605 +0x5da
github.com/cockroachdb/cockroach/sql.runTxnAttempt(0xc8203042a0, 0xc820dc0890, 0x1, 0xc820dc0828, 0xc820d1a7a0, 0xc820a402a0, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:535 +0x18d
github.com/cockroachdb/cockroach/sql.(*Executor).execRequest.func1(0xc820121b80, 0xc820d1a7a0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:444 +0x34a
github.com/cockroachdb/cockroach/client.(*Txn).Exec(0xc820121b80, 0xc8208f0101, 0x1453d9b52c1267c0, 0x0, 0xc8208f19a0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/client/txn.go:527 +0x2eb
github.com/cockroachdb/cockroach/sql.(*Executor).execRequest(0xc8203042a0, 0x7f66f3c3ad50, 0xc8210d4780, 0xc820dc0800, 0xc82075aa72, 0x1a5, 0x0, 0x0, 0x0, 0x7f66f3bbaf00)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:449 +0x962
github.com/cockroachdb/cockroach/sql.(*Executor).ExecuteStatements(0xc8203042a0, 0x7f66f3c3ad50, 0xc8210d4780, 0xc820dc0800, 0xc82075aa72, 0x1a5, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:338 +0xe5
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).executeStatements(0xc820e40480, 0x7f66f3c3ad50, 0xc8210d4780, 0xc82075aa72, 0x1a5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:648 +0xb2
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc820e40480, 0x7f66f3c3ad50, 0xc8210d4780, 0xc820e404a8, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:325 +0xf2
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).serve(0xc820e40480, 0xc820688880, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:281 +0x1095
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).ServeConn(0xc821055b00, 0x7f66f3bbaef0, 0xc82023e900, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:224 +0x99b
github.com/cockroachdb/cockroach/server.(*Server).Start.func8.1(0x7f66f3bf33e8, 0xc82032e000)
	/go/src/github.com/cockroachdb/cockroach/server/server.go:361 +0x42
github.com/cockroachdb/cockroach/util.(*Server).ServeWith.func1(0xc8203360b0, 0x7f66f3bf33e8, 0xc82032e000, 0xc8210360c0)
	/go/src/github.com/cockroachdb/cockroach/util/net.go:131 +0x62
created by github.com/cockroachdb/cockroach/util.(*Server).ServeWith
	/go/src/github.com/cockroachdb/cockroach/util/net.go:133 +0x333
```

[Archive.zip](https://github.com/cockroachdb/cockroach/files/293486/Archive.zip)

### PR DESCRIPTION
**Pull request by knz**
Found in #6986: the selectNode expanded the sub-queries in its filter
expression, then splits the filter for an indexed join, then the
indexJoinNode re-expands the sub-queries in its children node
including the scanNode with the remainder of the filter
expression. The double expansion was invalid.

This patch fixes the issue by delaying expansion of filter sub-queries
in the selectNode until after the index node has been
initialized. This ensure that it only expands the part of the filter
split away from the scanNode under responsibility of the
indexJoinNode.

Fixes #6986.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6994)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/select.go, line 411 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994#-KJMyNQykpBiB8UtJnoJ:-KJMyNQzZy9J2RwQVDfO:1850553900) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9edcaa11a244b1028f56d44f304305d4cca03a2/sql/select.go#L411)):*
> ```Go
> 	}
> 
> 	s.ordering = s.computeOrdering(s.source.plan.Ordering())
> ```

is there any reason this moved? i'm guessing no, but just checking for sanity.

---

*[sql/select.go, line 417 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994#-KJMyW8Wru2qoSYbefAg:-KJMyW8Wru2qoSYbefAh:-1503744698) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9edcaa11a244b1028f56d44f304305d4cca03a2/sql/select.go#L417)):*
> ```Go
> 	// the filter, since part of the filter may have landed in the source
> 	// scanNode and will be expanded there.
> 	if err := s.planner.expandSubqueryPlans(s.filter); err != nil {
> ```

so s.filter got mutated above?

---

*[sql/testdata/subquery, line 325 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994#-KJMyfC1DlMdUiznS8o4:-KJMyfC1DlMdUiznS8o5:1000761037) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9edcaa11a244b1028f56d44f304305d4cca03a2/sql/testdata/subquery#L325)):*
> ```
> 
> query ITTT
> EXPLAIN(VERBOSE) SELECT pk FROM tab1 WHERE (col4 IN (5.85,5.95,6.30,0.0,1.27) AND (col4 IN (9.41,4.56,2.55,0.83,3.95,6.92) AND (col1 = 6.24)) OR col0 IN (SELECT col3 FROM tab1 WHERE (((((col0 IN (8,1) AND col0 IS NULL AND col1 < 9.21) AND col4 > 8.64 AND (col3 >= 9) OR col0 < 5)))))) AND (col1 < 7.95 OR col0 < 0) AND col3 >= 9 AND col0 < 2 OR col4 BETWEEN 1.13 AND 0.71 AND (col3 > 9) AND (col0 < 3);
> ```

this is awfully complicated, is there really no smaller test case that will do?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/select.go, line 411 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994#-KJMyNQykpBiB8UtJnoJ:-KJN5X82RV40NAnX67SU:676201645) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9edcaa11a244b1028f56d44f304305d4cca03a2/sql/select.go#L411)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> is there any reason this moved? i'm guessing no, but just checking for sanity.
</details>
No reason, other than ensuring that expansions of the sub-plans is the last thing that happens here.

---

*[sql/select.go, line 417 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994#-KJMyW8Wru2qoSYbefAg:-KJN5cVV6BLBcF929WnE:-1249916573) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9edcaa11a244b1028f56d44f304305d4cca03a2/sql/select.go#L417)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> so s.filter got mutated above?
</details>
Yes, if an index was selected the filter has been split.

---

*[sql/testdata/subquery, line 325 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994#-KJMyfC1DlMdUiznS8o4:-KJN5frPt61ro2vFMg1c:-319298167) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9edcaa11a244b1028f56d44f304305d4cca03a2/sql/testdata/subquery#L325)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this is awfully complicated, is there really no smaller test case that will do?
</details>
Hmm probably I could simplify this. I'll have a look.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994)*

**Comment by RaduBerinde** [comment]
*[sql/select.go, line 417 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994#-KJN5My66jiF5RdCyHmL:-KJN5My66jiF5RdCyHmM:1287204103) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9edcaa11a244b1028f56d44f304305d4cca03a2/sql/select.go#L417)):*
> ```Go
> 	// the filter, since part of the filter may have landed in the source
> 	// scanNode and will be expanded there.
> 	if err := s.planner.expandSubqueryPlans(s.filter); err != nil {
> ```

So now we do index selection *before* expanding the subqueris? That seems like a huge change no? Something as simple as `SELECT k FROM kv WHERE k=(..subquery..)` is now a scan of the entire table?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994)*

**Comment by RaduBerinde** [comment]
*[sql/testdata/subquery, line 325 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994#-KJMyfC1DlMdUiznS8o4:-KJN4wPSb3oYldOSLYx1:-677171799) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9edcaa11a244b1028f56d44f304305d4cca03a2/sql/testdata/subquery#L325)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this is awfully complicated, is there really no smaller test case that will do?
</details>
+1, this will be very hard to debug if it gets broken by a change

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994)*

**Comment by RaduBerinde** [comment]
Part of the problem here is not respecting the "no in-place node changes" principle that `splitFilter` is based on. We could add some state to `subquery` to prevent the double expansion. @nvanbenschoten 

<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> #### sql: fix sub\-query plan expansion for queries with indexed joins\.
> 
> Found in #6986: the selectNode expanded the sub-queries in its filter
> 
> expression, then splits the filter for an indexed join, then the
> 
> indexJoinNode re-expands the sub-queries in its children node
> 
> including the scanNode with the remainder of the filter
> 
> expression. The double expansion was invalid.
> 
> 
> 
> This patch fixes the issue by delaying expansion of filter sub-queries
> 
> in the selectNode until after the index node has been
> 
> initialized. This ensure that it only expands the part of the filter
> 
> split away from the scanNode under responsibility of the
> 
> indexJoinNode.
> 
> 
> 
> Fixes #6986.
> 
> 
> 
</details>


---

Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994#-:-KJN6KoLj9Wly6bKKMkH:1427856443)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/select.go, line 417 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994#-KJN5My66jiF5RdCyHmL:-KJN6_yA2y8GkUF9pUpR:458779836) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9edcaa11a244b1028f56d44f304305d4cca03a2/sql/select.go#L417)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> So now we do index selection *before* expanding the subqueris? That seems like a huge change no? Something as simple as `SELECT k FROM kv WHERE k=(..subquery..)` is now a scan of the entire table?
</details>
For now, it is yes. 
Note that the previous implementation was not really the right way to optimize this case anyways.
To do this right there are two approaches. 
Either we flatten the sub-query by transforming it to a join; or 
we dynamically enhance the index selection after the plan execution has started, depending on whatever heuristics can be defined based on the initial computation by Start(). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994)*

**Comment by knz** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/testdata/subquery, line 325 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994#-KJMyfC1DlMdUiznS8o4:-KJN8sGhEfPSW2liTzNn:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9edcaa11a244b1028f56d44f304305d4cca03a2/sql/testdata/subquery#L325)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> +1, this will be very hard to debug if it gets broken by a change
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994)*

**Comment by knz** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/select.go, line 417 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994#-KJN5My66jiF5RdCyHmL:-KJN9416mSby9Qx2QqjP:-2091800281) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9edcaa11a244b1028f56d44f304305d4cca03a2/sql/select.go#L417)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> For now, it is yes. 
> Note that the previous implementation was not really the right way to optimize this case anyways.
> To do this right there are two approaches. 
> Either we flatten the sub-query by transforming it to a join; or 
> we dynamically enhance the index selection after the plan execution has started, depending on whatever heuristics can be defined based on the initial computation by Start(). 
</details>
There's another strategy to optimize this: implement a new node that allows to create variables (LET var = expr IN expr), then replace subqueries used as simple values in a select by a LET node that evaluates the subquery first then runs the body with that variable defined to a Datum. This may also be good to support WITH.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994)*

**Comment by RaduBerinde** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/select.go, line 417 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994#-KJN5My66jiF5RdCyHmL:-KJN7_ODAY8xuUfZ5Vjo:2073930856) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9edcaa11a244b1028f56d44f304305d4cca03a2/sql/select.go#L417)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> There's another strategy to optimize this: implement a new node that allows to create variables (LET var = expr IN expr), then replace subqueries used as simple values in a select by a LET node that evaluates the subquery first then runs the body with that variable defined to a Datum. This may also be good to support WITH.
</details>
I think this PR could lead to important regressions..

I don't see why starting with a bad plan then going back and redoing the index selection would be a "right" way, versus the way we were doing it before. Regardless, we are taking a step back and the proposed "right" approaches are nowhere close to something we could implement soon.

IMO this is a "big hammer" fix for the particular issue with double expansion of shared subquery nodes (which we could deal with in other ways).

Let's get some input from @petermattis as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994)*

**Comment by knz** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/select.go, line 417 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994#-KJN5My66jiF5RdCyHmL:-KJNAU8eAtxTDHb-76X7:1047759966) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9edcaa11a244b1028f56d44f304305d4cca03a2/sql/select.go#L417)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I think this PR could lead to important regressions..
> 
> I don't see why starting with a bad plan then going back and redoing the index selection would be a "right" way, versus the way we were doing it before. Regardless, we are taking a step back and the proposed "right" approaches are nowhere close to something we could implement soon.
> 
> IMO this is a "big hammer" fix for the particular issue with double expansion of shared subquery nodes (which we could deal with in other ways).
> 
> Let's get some input from @petermattis as well.
</details>
Please note that the fact that sub-queries are not simplified any more before index selection is not a consequence of this PR, but rather of #6735. Since #6735 was merged, there is no way any more that a subquery be simplified to a Datum and embarked by splitFilter towards index optimization.

The fix in the present PR does not introduce performance regressions that were not there since #6735 was merged -- it is thus performance neutral. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994)*

**Comment by RaduBerinde** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/select.go, line 417 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994#-KJN5My66jiF5RdCyHmL:-KJNDc6W5O75_jEnLQEJ:-763492079) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9edcaa11a244b1028f56d44f304305d4cca03a2/sql/select.go#L417)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Please note that the fact that sub-queries are not simplified any more before index selection is not a consequence of this PR, but rather of #6735. Since #6735 was merged, there is no way any more that a subquery be simplified to a Datum and embarked by splitFilter towards index optimization.
> 
> The fix in the present PR does not introduce performance regressions that were not there since #6735 was merged -- it is thus performance neutral. 
</details>
That isn't really good news :) Please file an issue to track fixing this. We used to do this correctly before..

And please keep in mind that if it's something that we want to fix soon, this PR is moving in the wrong direction.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994)*

**Comment by knz** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/select.go, line 417 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994#-KJN5My66jiF5RdCyHmL:-KJNY1Gas3575iT7uukp:-1929813444) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9edcaa11a244b1028f56d44f304305d4cca03a2/sql/select.go#L417)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> That isn't really good news :) Please file an issue to track fixing this. We used to do this correctly before..
> 
> And please keep in mind that if it's something that we want to fix soon, this PR is moving in the wrong direction.
</details>
Done, see #7042.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994)*

**Comment by knz** [comment]
Since #7042 is filed, I'd propose merging this PR so as to get the sql bigtest back on rails (it's been failing for a week now due to this particular bug).

<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Part of the problem here is not respecting the "no in-place node changes" principle that `splitFilter` is based on. We could add some state to `subquery` to prevent the double expansion. @nvanbenschoten 
</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994#-:-KJNbu54T_b6V2ysBqKR:-148330455)*

**Comment by RaduBerinde** [comment]
Sounds good to me.

<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Since #7042 is filed, I'd propose merging this PR so as to get the sql bigtest back on rails (it's been failing for a week now due to this particular bug).
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6994#-:-KJkoi9VBP_FDbfvp-gM:-682275779)*

**Pull request merged**
