### PR TITLE
sql/types: types.EnumMetadata implements encoding.TextMarshaler interface

### LINKED ISSUE #63379: sql: calling String() on some ColumnDescriptors (and possibly other types) can panic
**Describe the problem**

(This might be a dupe of #63299)

If we run `\set auto_trace=on,kv` and then `ALTER TABLE foo SET LOCALITY REGIONAL BY ROW`, you may receive trace data that shows evidence of a panic:

```
 2021-04-08 18:41:50.999899+00:00:00 | 00:00:00.007879 | Put /Table/3/1/55/2/1 -> %!s(PANIC=String method: reflect.Value.Bytes of non-byte slice)                       | [n1,client=[::1]:53927,hostnossl,user=root]                                     | ©g356o:356  | flow             |   36
```

The following test is capable of reproducing this particular panic:

```go
import (
	"testing"

	"github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb"
	"github.com/cockroachdb/cockroach/pkg/sql/catalog/typedesc"
	"github.com/cockroachdb/cockroach/pkg/sql/types"
	"github.com/stretchr/testify/require"
)

func TestDescriptorProtoString(t *testing.T) {
	enumMembers := []string{"hi", "hello"}
	enumType := types.MakeEnum(typedesc.TypeIDToOID(500), typedesc.TypeIDToOID(100500))
	enumType.TypeMeta = types.UserDefinedTypeMetadata{
		Name: &types.UserDefinedTypeName{
			Schema: "test",
			Name:   "greeting",
		},
		EnumData: &types.EnumMetadata{
			LogicalRepresentations: enumMembers,
			PhysicalRepresentations: [][]byte{
				{0x42, 0x1},
				{0x42},
			},
			IsMemberReadOnly: make([]bool, len(enumMembers)),
		},
	}
	desc := &descpb.ColumnDescriptor{
		Name: "c",
		ID:   1,
		Type: enumType,
	}
	require.NotPanics(t, func() { _ = desc.String() })
}
```

which will fail with:

```
=== RUN   TestDescriptorProtoString
    descriptor_test.go:50: 
                Error Trace:    descriptor_test.go:50
                Error:          func (assert.PanicTestFunc)(0x533dce0) should not panic
                                        Panic value:    reflect.Value.Bytes of non-byte slice
                                        Panic stack:    goroutine 40 [running]:
                                runtime/debug.Stack(0xc000af62c0, 0x5500ba0, 0x5eaab00)
                                        /usr/local/Cellar/go/1.16.2/libexec/src/runtime/debug/stack.go:24 +0x9f
                                github.com/stretchr/testify/assert.didPanic.func1.1(0xc000af7e20, 0xc000af7e0f, 0xc000af7e10)
                                        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/github.com/stretchr/testify/assert/assertions.go:1013 +0x6b
                                panic(0x5500ba0, 0x5eaab00)
                                        /usr/local/Cellar/go/1.16.2/libexec/src/runtime/panic.go:965 +0x1b9
                                reflect.Value.Bytes(0x54daec0, 0xc000a95360, 0x197, 0x6070a0e49ba95b2b, 0xc00034ab60, 0xc000af6750)
                                        /usr/local/Cellar/go/1.16.2/libexec/src/reflect/value.go:291 +0x118
                                github.com/gogo/protobuf/proto.(*TextMarshaler).writeAny(0x697497a, 0xc000ad2320, 0x54daec0, 0xc000a95360, 0x197, 0xc000aef200, 0x5fbe050, 0x54daec0)
                                        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/github.com/gogo/protobuf/proto/text.go:557 +0x62e
                                github.com/gogo/protobuf/proto.(*TextMarshaler).writeStruct(0x697497a, 0xc000ad2320, 0x561d4e0, 0xc000a95360, 0x199, 0x199, 0x0)
                                        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/github.com/gogo/protobuf/proto/text.go:453 +0x8e7
                                github.com/gogo/protobuf/proto.(*TextMarshaler).writeAny(0x697497a, 0xc000ad2320, 0x554bfc0, 0xc000a92470, 0x196, 0xc000aeed00, 0x5fbe050, 0x554bfc0)
                                        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/github.com/gogo/protobuf/proto/text.go:604 +0x287
                                github.com/gogo/protobuf/proto.(*TextMarshaler).writeStruct(0x697497a, 0xc000ad2320, 0x561d660, 0xc000a92460, 0x199, 0x199, 0x0)
                                        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/github.com/gogo/protobuf/proto/text.go:453 +0x8e7
                                github.com/gogo/protobuf/proto.(*TextMarshaler).writeAny(0x697497a, 0xc000ad2320, 0x561d660, 0xc000a92460, 0x199, 0xc000a88c00, 0x5fbe050, 0x561d660)
                                        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/github.com/gogo/protobuf/proto/text.go:604 +0x287
                                github.com/gogo/protobuf/proto.(*TextMarshaler).writeStruct(0x697497a, 0xc000ad2320, 0x55e4980, 0xc000a923c0, 0x199, 0x199, 0x0)
                                        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/github.com/gogo/protobuf/proto/text.go:453 +0x8e7
                                github.com/gogo/protobuf/proto.(*TextMarshaler).writeAny(0x697497a, 0xc000ad2320, 0x573c9c0, 0xc000a6bf18, 0x196, 0xc000a88a00, 0x5fbe050, 0x573c9c0)
                                        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/github.com/gogo/protobuf/proto/text.go:604 +0x287
                                github.com/gogo/protobuf/proto.(*TextMarshaler).writeStruct(0x697497a, 0xc000ad2320, 0x57013e0, 0xc000a6bf00, 0x199, 0x199, 0x7700a68)
                                        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/github.com/gogo/protobuf/proto/text.go:453 +0x8e7
                                github.com/gogo/protobuf/proto.(*TextMarshaler).Marshal(0x697497a, 0x5ec4720, 0xc000ad5a10, 0x5ee7ab0, 0xc000a6bf00, 0x9, 0x22)
                                        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/github.com/gogo/protobuf/proto/text.go:894 +0x22e
                                github.com/gogo/protobuf/proto.(*TextMarshaler).Text(0x697497a, 0x5ee7ab0, 0xc000a6bf00, 0x40654db, 0xc000411590)
                                        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/github.com/gogo/protobuf/proto/text.go:906 +0x6e
                                github.com/gogo/protobuf/proto.CompactTextString(...)
                                        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/github.com/gogo/protobuf/proto/text.go:928
                                github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb.(*ColumnDescriptor).String(...)
                                        /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb/structured.pb.go:877
                                github.com/cockroachdb/cockroach/pkg/sql/catalog_test.TestDescriptorProtoString.func1()
                                        /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descriptor_test.go:50 +0x45
                                github.com/stretchr/testify/assert.didPanic.func1(0xc000411620, 0xc00041160f, 0xc000411610, 0xc000ade540)
                                        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/github.com/stretchr/testify/assert/assertions.go:1018 +0x6c
                                github.com/stretchr/testify/assert.didPanic(0xc000ade540, 0x2f6d7a38, 0xc0003b3c80, 0x2f6d7a58, 0xc0003b3c80, 0xc0003b3c01)
                                        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/github.com/stretchr/testify/assert/assertions.go:1020 +0x5f
                                github.com/stretchr/testify/assert.NotPanics(0x2f6d7a38, 0xc0003b3c80, 0xc000ade540, 0x0, 0x0, 0x0, 0xc000ade540)
                                        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/github.com/stretchr/testify/assert/assertions.go:1091 +0x77
                                github.com/stretchr/testify/require.NotPanics(0x5ede130, 0xc0003b3c80, 0xc000ade540, 0x0, 0x0, 0x0)
                                        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/github.com/stretchr/testify/require/require.go:1236 +0xbe
                                github.com/cockroachdb/cockroach/pkg/sql/catalog_test.TestDescriptorProtoString(0xc0003b3c80)
                                        /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descriptor_test.go:50 +0x330
                                testing.tRunner(0xc0003b3c80, 0x5c87610)
                                        /usr/local/Cellar/go/1.16.2/libexec/src/testing/testing.go:1194 +0xef
                                created by testing.(*T).Run
                                        /usr/local/Cellar/go/1.16.2/libexec/src/testing/testing.go:1239 +0x2b3
                Test:           TestDescriptorProtoString
```

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
Fixes #63379

`types.EnumMetadata` needs to implement `encoding.TextMarshaler`
interface so that goto/protobuf won't panic when text marshaling
protobuf struct has child field of type `types.EnumMetadata`.
See the issue for more details why it would fail without this
fix.

Release note: None

### CODE REVIEW

**Comment by chengxiong-ruan** [comment]
___
*[pkg/sql/types/types.go, line 231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72640#-MoEM6K95ffDAz1uRuvs:-MoEM6K95ffDAz1uRuvt:bqpzihw) ([raw file](https://github.com/cockroachdb/cockroach/blob/309f765925b6a7434bd919614ffa05c67ab4fcbf/pkg/sql/types/types.go#L231)):*
> ```Go
> 	for i, bs := range e.PhysicalRepresentations {
> 		if i > 0 {
> 			bf.WriteString(",")
> ```

I'm totally open to remove this kind of logic to insert separator, we would just have an extra comma at the end...

**Review by ajwerner — COMMENTED** [review]
The more I think about it, the less I think I care about actually populating these. The biggest reason is that the type metadata in the cases we're dealing with should not be populated. The point of the types.T having the embedded internal type and then the type metadata is to support in-memory operations and to make sure we never, ever serialize the user-defined metadata to disk. The reason for all of this is that the user-defined metadata can change and needs to be "hydrated" into the type descriptor. This is a topic we can unpack at some future point.

I think what I'd prefer is that we just skip the user defined type metadata altogether. To do this, I'd do the following and be done with it. 

```go
// MarshalText is implemented because ...
func (e *T) MarshalText() (text []byte, err error) {
	var buf bytes.Buffer
        if err := proto.MarshalText(&buf, e.InternalType); err != nil {
            return nil, err
        }
        return buf.Bytes(), nil
}
```

It'd then be good to write some tests of marshaling protos which use types and may or may not have populated user-defined type data to string. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72640#-:-MoEW4aj7I_lXCEvoAWt:bi6rqc3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan and @postamar)

___
*[pkg/sql/types/types.go, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72640#-MoEV9ax95MH78a59yBp:-MoEV9ax95MH78a59yBq:b9ywb69) ([raw file](https://github.com/cockroachdb/cockroach/blob/309f765925b6a7434bd919614ffa05c67ab4fcbf/pkg/sql/types/types.go#L228)):*
> ```Go
> 	// Convert PhysicalRepresentations to byte slice representation of string like
> 	// "PhysicalRepresentations<[0x12,0x34],[0x56]>".
> 	bf.WriteString("PhysicalRepresentations<")
> ```

If we're going to go for a prototext format, may as well go all the way. However,

**Review by chengxiong-ruan — COMMENTED** [review]
good call out and thanks for the context! :thumbsup: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72640#-:-MoEqDIM7sOR5Ny4d9-y:b-qlrmwo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan and @postamar)

**Comment by chengxiong-ruan** [comment]
___
*[pkg/sql/types/types.go, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72640#-MoEV9ax95MH78a59yBp:-MoEqQgyDhBIwb2E7IEP:bpl2mol) ([raw file](https://github.com/cockroachdb/cockroach/blob/309f765925b6a7434bd919614ffa05c67ab4fcbf/pkg/sql/types/types.go#L228)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

If we're going to go for a prototext format, may as well go all the way. However, 
</blockquote></details>

this part is removed :)

**Comment by chengxiong-ruan** [comment]
___
*[pkg/sql/opt/exec/execbuilder/testdata/show_trace_nonmetamorphic, line 42 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72640#-MoFAcVW9jHH0RdX76Wt:-MoFAcVXBM2Cjps_3Asx:bnoreoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/4271af43e1590fed222583a707431f34c42de7df/pkg/sql/opt/exec/execbuilder/testdata/show_trace_nonmetamorphic#L42)):*
> ```
> ----
> batch flow coordinator  CPut /NamespaceTable/30/1/53/29/"kv"/4/1 -> 54
> batch flow coordinator  CPut /Table/3/1/54/2/1 -> table:<name:"kv" id:54 version:1 modification_time:<> parent_id:53 unexposed_parent_schema_id:29 columns:<name:"k" id:1 type:<family: IntFamily width: 64 precision: 0 locale: "" visible_type: 0 oid: 20 time_precision_is_set: false > nullable:false hidden:false inaccessible:false generated_as_identity_type:NOT_IDENTITY_COLUMN virtual:false pg_attribute_num:0 alter_column_type_in_progress:false system_column_kind:NONE > columns:<name:"v" id:2 type:<family: IntFamily width: 64 precision: 0 locale: "" visible_type: 0 oid: 20 time_precision_is_set: false > nullable:true hidden:false inaccessible:false generated_as_identity_type:NOT_IDENTITY_COLUMN virtual:false pg_attribute_num:0 alter_column_type_in_progress:false system_column_kind:NONE > next_column_id:3 families:<name:"primary" id:0 column_names:"k" column_names:"v" column_ids:1 column_ids:2 default_column_id:2 > next_family_id:1 primary_index:<name:"kv_pkey" id:1 unique:true version:4 key_column_names:"k" key_column_directions:ASC store_column_names:"v" key_column_ids:1 store_column_ids:2 foreign_key:<table:0 index:0 name:"" validity:Validated shared_prefix_len:0 on_delete:NO_ACTION on_update:NO_ACTION match:SIMPLE > interleave:<> partitioning:<num_columns:0 num_implicit_columns:0 > type:FORWARD created_explicitly:false encoding_type:1 sharded:<is_sharded:false name:"" shard_buckets:0 > disabled:false geo_config:<> predicate:"" > next_index_id:2 privileges:<users:<user_proto:"admin" privileges:2 > users:<user_proto:"public" privileges:0 > users:<user_proto:"root" privileges:2 > owner_proto:"root" version:2 > next_mutation_id:1 format_version:3 state:PUBLIC offline_reason:"" view_query:"" is_materialized_view:false new_schema_change_job_id:0 drop_time:0 replacement_of:<id:0 time:<> > audit_mode:DISABLED drop_job_id:0 create_query:"" create_as_of_time:<> temporary:false partition_all_by:false >
> ```

these logic test case were updated with `--rewrite`

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72640#-:-MoFeHDr0O9uhqpaYITv:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)

**Pull request merged**
