### PR TITLE
kv: muck with the RangeDescriptor encoding

### PR DESCRIPTION
**Pull request by andreimatei**
See individual commits.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
I'm very happy to see this cleanup!

The refactoring (commits 1 and 2) looks good to me, based on my understanding of the state of the migration in #38302.

The removal of generation_compatible (commit 3) is a bit more nuanced. I am confused by the discussion of a migration in #36654 and how that relates to range snapshots. I think that was all only relevant if we ended up using range generations to solve #36611, but we ended up solving it a different way. So I think we need a different safety argument for the third commit, specifically around the uses of the field during range lookups and in the range descriptor cache.

For range lookups, I think the argument goes something like:
- we only use the generation_compatible field when a range lookup's inconsistent scan observes overlapping range descriptors
- (assuming all abandoned intents are eventually cleaned up) overlapping range descriptors are only possible in the meta ranges due to concurrent txns
- all concurrent txns in a 20.2 cluster should obey the correct generation rules
- so we can say that all cases where we currently use descriptor generations during range lookups can assume that the descriptor generations are comparable

For the range descriptor cache, the argument is something like:
- the range descriptor cache contains only volatile state
- it starts by fetching the latest state of the meta range
- we use the generation_compatible field to compare overlapping descriptors
- at least one of the two overlapping descriptors during a comparison must have been changed by a 20.1+ node
- changes to descriptors by 20.1+ nodes will use the correct generation rules
- so we can say that all cases where we currently use descriptor generations in the range descriptor cache can assume that the descriptor generations are comparable

> Reviewed 5 of 5 files at r1, 13 of 13 files at r2, 15 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49091#-:-M7OVgmzEEXL2WCGr3vD:b-oto0wd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @tbg)

**Review by andreimatei — COMMENTED** [review]
Yeah, thanks. I was generally thinking of the correctness argument more generically as the fact that wherever we compare two generations, at least one of the two descriptors involved must have been written with a good generation (meaning written by 19.1+). 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49091#-:-M7P8heOBZSkWC-Cr0Vu:bhlwdkh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @nvanbenschoten, and @tbg)

**Review by bdarnell — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 2 of 14 files at r5, 16 of 16 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49091)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r1, 17 of 17 files at r4, 14 of 14 files at r5, 16 of 16 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49091#-:-M7fxQ-yDKavaHveQctf:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49091#-:-M7hDkQ42qiH0IbdUHLa:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
