### PR TITLE
sql: add random JSON generator

### PR DESCRIPTION
**Pull request by justinj**
This can be the basis for an RSG test in the future, right now it's just
used for a round-tripping test.

Considered making this a separate package but opted against it, no real
basis to that decision though, open to hearing otherwise.

### CODE REVIEW

**Comment by mjibson** [comment]
All of our other rand datum code is in the sqlbase package. Does it make sense to put this there? We should add it to sqlbase.RandDatum at least I think.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/json_random.go, line 23 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19608#-KxkxdP_4GG8DakeGX43:-KxkxdP_4GG8DakeGX44:blf963k) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cc321137c83854606c1f4700ac3c8eff848ae49/pkg/sql/parser/json_random.go#L23)):*
> ```Go
> )
> 
> func randomDJSON(complexity int) DJSON {
> ```

I'd remove this function and call it directly in the test. It feels unsafe to have a function that ignores errors in a non-test file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19608#-:-KxkwDI6v7dCVLipMEdh:bzh32nm)*

**Comment by justinj** [comment]
A recent PR added a `util/json` package so I've put it there now. It can't be added to `RandDatum` at the moment because it doesn't have a corresponding column type (but I'll make a note in my to-do list that it should go there with that PR). So this doesn't actually generate a Datum at the moment, but it's still useful for internal JSON testing.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/parser/json_random.go, line 23 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19608#-KxkxdP_4GG8DakeGX43:-Kxtkw87xA7YinR_g8wh:b-etdmyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cc321137c83854606c1f4700ac3c8eff848ae49/pkg/sql/parser/json_random.go#L23)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I'd remove this function and call it directly in the test. It feels unsafe to have a function that ignores errors in a non-test file.
</blockquote></details>

I just made it pass through the error so the test has to handle it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19608#-:-Kxtl-1NUddMs2_gTG_3:bapjw4)*

**Comment by justinj** [comment]
@mjibson anything else in the immediate term for this PR? I'd like to have this for testing round-tripping of encoding and decoding. Interested in particular if you have any thoughts on if the quality of the random objects could be improved in any way.

**Comment by jordanlewis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19608#-:-KyRMHaVdQ79WM4ZaFiU:bnfp4nl)*

**Comment by mjibson** [comment]
Add something to https://github.com/cockroachdb/cockroach/blob/8fbbcee51ea89f72f8c6aee6ccf1c29a17b2a4cc/pkg/internal/rsg/rsg.go#L215 so the RSG tests work again.

I think the quality of the random objects is good.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19608#-:-KyRucxKMlWRKiX0AxLB:b2pid37)*

**Comment by justinj** [comment]
Ok, done.

I ran
```
make test PKG="./pkg/sql" TESTS=TestRandomSyntaxGeneration
```
and nothing exploded, is there anything else I need to update to get them running again?

**Comment by mjibson** [comment]
Run `make test PKG=./pkg/sql 'TESTS=TestRandomSyntaxFunctions' 'TESTFLAGS=-rsg 1m'`

**Comment by mjibson** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/internal/rsg/rsg.go, line 267 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/19608#-KyYymowJntfWQw7a-Xx:-KyYymowJntfWQw7a-Xy:b7ci1r9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef884bb2c79468ed3ea77b022e91795f2349eb6d/pkg/internal/rsg/rsg.go#L267)):*
> ```Go
> 			panic(err)
> 		}
> 		v = parser.DJSON{JSON: j}
> ```

See a few lines below where `v` is used with %v in fmt.Sprintf. Will a parser.DJSON convert itself to a string in that case? If not, then v should be set to the correct string here, just like the other types.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19608)*

**Comment by justinj** [comment]
OK, updated and rebased!

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19608#-:-Kyvr0oTNqsRCS3fVF2C:bnfp4nl)*

**Comment by justinj** [comment]
Thanks for the reviews!

**Pull request merged**
