### PR TITLE
changefeedccl/cdctest: change beforeAfterValidator to use to_json

### PR DESCRIPTION
**Pull request by wenyihu6**
**changefeedccl: Revert "changefeedccl: support validator with geometry types**

This reverts commit https://github.com/cockroachdb/cockroach/commit/fb7544d733ab9767e7a11575fdc50edb8c2c5a53.

We have found a better way for beforeAfterValidator to compare
against json values directly. Future commits will address it.

Informs: #124146
Release note: none

---

**changefeedccl/cdctest: change beforeAfterValidator to use to_json**

Previously, beforeAfterValidator parses json message and passes the parsed data
into argument $1 for `SELECT ... FROM ... WHERE col = $1`. This usually works,
but `gojson.Unmarshal` does not work well with all data types. This patch changes
beforeAfterValidator to directly compare against the json message using
`SELECT ... FROM ... WHERE to_json(col) = $1`.

Informs: #124146
Release note: none

### CODE REVIEW

**Comment by wenyihu6** [comment]
Unfortunately, this idea doesn't work nicely with finger print validator where it uses UPSERT and INSERT to insert the data back to a new scratch table and verifies that the finger prints match https://github.com/cockroachdb/cockroach/blob/24569eb5014ec97f18f38e8972e2470221e556af/pkg/ccl/changefeedccl/cdctest/validator.go#L497-L498.

After discussing with Miles and sql, we might still need to write a json decoder ourselves using the schema info. I'm taking a stab at it for now. If it turns out to be an overkill, we can disable finger print validator for nemesis. To avoid losing test coverage, I can create a new test that does the same thing as nemesis but uses sql smith without fprint validator.

**Review by rharding6373 — APPROVED** [review]
Nice! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136003#-:-OC_832I5OZORpq1Q3Pe:bfd61qr)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @asg0451 and @wenyihu6)

___
*[`pkg/ccl/changefeedccl/cdctest/validator_test.go` line 261 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136003#-OCZN3AF3PMDB7duko11:-OCZN3AG2ZC699zdT6QH:bg18lg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ce6c0482ab9ef3ae932dae530aec12110217c70/pkg/ccl/changefeedccl/cdctest/validator_test.go#L261)):*
> ```Go
> 
> 	sqlDB.Exec(t, `CREATE DATABASE d`)
> 	sqlDB.Exec(t, `CREATE TABLE foo (k INT PRIMARY KEY,  geom geometry(point))`)
> ```

minor nit: s/geometry(point)/GEOMETRY(POINT)
___
*[`pkg/ccl/changefeedccl/cdctest/validator.go` line 282 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136003#-OCZMo4RAo9N1pKp_cMi:-OCZMo4RAo9N1pKp_cMj:b-8erub9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ce6c0482ab9ef3ae932dae530aec12110217c70/pkg/ccl/changefeedccl/cdctest/validator.go#L282)):*
> ```Go
> 				fmt.Fprintf(&stmtBuf, `%s IS NULL`, v.primaryKeyCols[i])
> 			} else {
> 				fmt.Fprintf(&stmtBuf, `to_json(%s)::text = $%d`, v.primaryKeyCols[i], i+1)
> ```

minor nit: s/::text/::TEXT here and below (capitalizing SQL is good form)

**Review by asg0451 — APPROVED** [review]

**Review by wenyihu6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136003)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rharding6373)

___
*[`pkg/ccl/changefeedccl/cdctest/validator.go` line 282 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136003#-OCZMo4RAo9N1pKp_cMi:-OCePFRBAhdGh2Zin8qv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ce6c0482ab9ef3ae932dae530aec12110217c70/pkg/ccl/changefeedccl/cdctest/validator.go#L282)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

minor nit: s/::text/::TEXT here and below (capitalizing SQL is good form)
</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/cdctest/validator_test.go` line 261 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136003#-OCZN3AF3PMDB7duko11:-OCePIvN4kfk0G7BUgEb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ce6c0482ab9ef3ae932dae530aec12110217c70/pkg/ccl/changefeedccl/cdctest/validator_test.go#L261)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

minor nit: s/geometry(point)/GEOMETRY(POINT)
</blockquote></details>

Done.

**Comment by wenyihu6** [comment]
TFTR!

bors r=rharding6373, asg0451

**Comment by wenyihu6** [comment]
Extended CI failure looks unrelated.

**Comment by wenyihu6** [comment]
bors retry

**Comment by wenyihu6** [comment]
bors r=rharding6373, asg0451

**Pull request merged**
