### PR TITLE
sql: track and report number of errors returned by error code

### PR DESCRIPTION
**Pull request by dt**
First commit:
Return the pgerror for division by zero rather than the raw apd error @mjibson for review.

Second commit:
Allow `force_error` to throw non-pg errors (to test any pgerror-specific handling) @knz for review.

Third commit:
Record the number of errors returned by pg error code -- Non-pg errors are counted as “unknown”.

These counts can then be included in diagnostics reports, indicating what issues users are hitting and may need to be looked at more closely.

These numbers are similar to, but distinct from what we can learn from reported statement statistic -- only parsed queries are even eligible for statistics reporting (as parsing is a pre-requisit of sanitizing), while these numbers capture all error codes returned to clients. @knz @BramGruneir for review, and @andreimatei for review of the slight re-arragment of the conditionals in conn_executor.go

### CODE REVIEW

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22912#-:-L5u_oxUKk7LOkPhv8Eq:bnfp4nl)*

**Review by madelynnblue — APPROVED** [review]

**Comment by dt** [comment]
Cc @awoods187

**Comment by knz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: 1 of 10 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22912#-:-L5ugQD4guD7Kn8zbLZi:bnfp4nl)*

**Comment by knz** [comment]
Reviewed 2 of 2 files at r1, 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/conn_executor.go, line 313 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22912#-L5xzjkkHURMnM71wyp9:-L5xzjkkHURMnM71wypA:b-iajhr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3207db570df9962ecc4033d305f65e44f13cfdc6/pkg/sql/conn_executor.go#L313)):*
> ```Go
> 		s.errorCounts.codes[pgErr.Code]++
> 
> 		if pgErr.Code == pgerror.CodeFeatureNotSupportedError {
> ```

Oy, if the error is CodeFeatureNotSupportedError but there is no InternalCommand, you're dropping the error on the floor entirely. It should be at least billed in the "unknown" category.

But then I wouldn't like "unknown" too much.
I would suggest creature a feature string out of thin air containing:
- the file name, optionally lineno
- the format string

This requires extending our pgerror constructors to embed this information in the error object, but that would actually be a good thing.

---

*[pkg/sql/executor.go, line 727 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22912#-L5y-Q2ywCWMYwp75PEG:-L5y-Q3-CV4gZxFRn1lt:br6w785) ([raw file](https://github.com/cockroachdb/cockroach/blob/3207db570df9962ecc4033d305f65e44f13cfdc6/pkg/sql/executor.go#L727)):*
> ```Go
> 				}
> 				e.errorCounts.unimplemented[feature]++
> 			}
> ```

ditto above, else missing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22912)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/conn_executor.go, line 313 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22912#-L5xzjkkHURMnM71wyp9:-L5y-nQbnHNEIsLicmFc:b-8f3h5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/3207db570df9962ecc4033d305f65e44f13cfdc6/pkg/sql/conn_executor.go#L313)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Oy, if the error is CodeFeatureNotSupportedError but there is no InternalCommand, you're dropping the error on the floor entirely. It should be at least billed in the "unknown" category.

But then I wouldn't like "unknown" too much.
I would suggest creature a feature string out of thin air containing:
- the file name, optionally lineno
- the format string

This requires extending our pgerror constructors to embed this information in the error object, but that would actually be a good thing.
</blockquote></details>

We're not dropping it entirely -- we're still counting it, by code, immediately above, so we'd know we had an error of type  CodeFeatureNotSupportedError, just not what feature. The `else` block below where we count `unknown` is if the error wasn't a `pgerror` at all (i.e. some other `error` bubbled up).

For `InternalCommand` to be empty, I think you'd need to call pgerror.Unsupported() and pass `""` for the feature arg -- I guess I'm not opposed to having it automatically fill file:line of the caller in that case, but I'd like to think we won't do that, and indeed, I'd also be fine with a panic there too as that is invalid usage?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22912)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/conn_executor.go, line 313 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22912#-L5xzjkkHURMnM71wyp9:-L5y2ZkPSpv4RzLefMMW:btvrj5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/3207db570df9962ecc4033d305f65e44f13cfdc6/pkg/sql/conn_executor.go#L313)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

We're not dropping it entirely -- we're still counting it, by code, immediately above, so we'd know we had an error of type  CodeFeatureNotSupportedError, just not what feature. The `else` block below where we count `unknown` is if the error wasn't a `pgerror` at all (i.e. some other `error` bubbled up).

For `InternalCommand` to be empty, I think you'd need to call pgerror.Unsupported() and pass `""` for the feature arg -- I guess I'm not opposed to having it automatically fill file:line of the caller in that case, but I'd like to think we won't do that, and indeed, I'd also be fine with a panic there too as that is invalid usage?
</blockquote></details>

oh sorry I hadn't seen the thing two lines above. Carry on.

I do think that we could make some effort at tracking the caller of NewErrorf in more places. Not necessary for this PR though.

---

*[pkg/sql/executor.go, line 727 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22912#-L5y-Q2ywCWMYwp75PEG:-L5y2jSY6ICRTvQYeIMn:b-o2531e) ([raw file](https://github.com/cockroachdb/cockroach/blob/3207db570df9962ecc4033d305f65e44f13cfdc6/pkg/sql/executor.go#L727)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto above, else missing
</blockquote></details>

ok nothing to see here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22912)*

**Comment by dt** [comment]
I think we'll want to grab #22939 too when we cherrypick this.

**Pull request merged**
