### PR TITLE
kvserver: improve TestReplicaLatchingOptimisticEvaluationKeyLimit

### PR DESCRIPTION
**Pull request by arulajmani**
This test would fail opaquely previously, which wasn't helpful. This patch sets up tracing on the read path to help investigate future failures.

Informs https://github.com/cockroachdb/cockroach/issues/135197

Release note: None

### CODE REVIEW

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135234#-:-OC-X-bs9BkkvONcf4kX:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by kvoli** [comment]
Looks like extended CI even got the failure w/ the trace on this PR (`TestReplicaLatchingOptimisticEvaluationKeyLimit/point-reads=true/{writeKey:b_limit:1_interferes:false}`):
- https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/17771526?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&expandBuildTestsSection=true

**Comment by arulajmani** [comment]
```
Failed
=== RUN   TestReplicaLatchingOptimisticEvaluationKeyLimit/point-reads=true/{writeKey:b_limit:1_interferes:false}
    replica_test.go:2888:      0.000ms      0.000ms    === operation:read-req _verbose:1
             0.039ms      0.039ms    event:kv/kvserver/replica_send.go:171 [s1,r1/1:/M{in-ax}] read-only path
             0.058ms      0.019ms    event:kv/kvserver/concurrency/concurrency_manager.go:212 [s1,r1/1:/M{in-ax}] optimistically sequencing request
             0.090ms      0.031ms    event:kv/kvserver/concurrency/concurrency_manager.go:284 [s1,r1/1:/M{in-ax}] optimistically acquiring latches
             0.106ms      0.017ms    event:kv/kvserver/concurrency/concurrency_manager.go:330 [s1,r1/1:/M{in-ax}] optimistically scanning lock table for conflicting locks
             0.130ms      0.024ms    event:kv/kvserver/replica_read.go:421 [s1,r1/1:/M{in-ax}] executing read-only batch
             0.229ms      0.099ms    event:kv/kvserver/replica_evaluate.go:511 [s1,r1/1:/M{in-ax}] evaluated Get command header:<key:"a" > , txn=<nil> : resp=header:<num_keys:1 num_bytes:10 > value:<raw_bytes:"\000\000\000\000\003value" timestamp:<wall_time:1731631227373116633 > > , err=<nil>
             0.263ms      0.035ms    event:kv/kvserver/replica_evaluate.go:511 [s1,r1/1:/M{in-ax}] evaluated Get command header:<key:"b" > , txn=<nil> : resp=header:<resume_span:<key:"b" > resume_reason:RESUME_KEY_LIMIT > , err=<nil>
             0.293ms      0.030ms    event:kv/kvserver/replica_evaluate.go:511 [s1,r1/1:/M{in-ax}] evaluated Get command header:<key:"c" > , txn=<nil> : resp=header:<resume_span:<key:"c" > resume_reason:RESUME_KEY_LIMIT > , err=<nil>
             0.330ms      0.037ms    event:kv/kvserver/replica_evaluate.go:511 [s1,r1/1:/M{in-ax}] evaluated Get command header:<key:"d" > , txn=<nil> : resp=header:<resume_span:<key:"d" > resume_reason:RESUME_KEY_LIMIT > , err=<nil>
             0.364ms      0.034ms    event:n1 scan stats: stepped 0 times (0 internal); seeked 2 times (2 internal); block-bytes: (total 0 B, cached 0 B, duration 0s); points: (count 1, key-bytes 11 B, value-bytes 10 B, tombstoned: 0) ranges: (count 0), (contained-points 0, skipped-points 0) evaluated requests: 1 gets, 0 scans, 0 reverse scans
             0.430ms      0.066ms    event:kv/kvserver/replica_send.go:507 [s1,r1/1:/M{in-ax}] concurrency retry error: optimistic eval encountered conflict
             0.446ms      0.017ms    event:kv/kvserver/concurrency/concurrency_manager.go:233 [s1,r1/1:/M{in-ax}] re-sequencing request after optimistic sequencing failed
             0.458ms      0.011ms    event:kv/kvserver/concurrency/concurrency_manager.go:307 [s1,r1/1:/M{in-ax}] optimistic failed, so waiting for latches
             0.516ms      0.059ms    event:kv/kvserver/spanlatch/manager.go:580 [s1,r1/1:/M{in-ax}] waiting to acquire read latch b@1731631227.387628855,0 for request Get ["a"], Get ["b"], Get ["c"], Get ["d"], [max_span_request_keys: 1], [target_bytes: 0], held by write latch b@1731631227.387505547,0 for request Put ["b"]
         15000.986ms  15000.470ms    event:kv/kvserver/spanlatch/manager.go:606 [s1,r1/1:/M{in-ax}] have been waiting 15s to acquire read latch b@1731631227.387628855,0 for request Get ["a"], Get ["b"], Get ["c"], Get ["d"], [max_span_request_keys: 1], [target_bytes: 0], held by write latch b@1731631227.387505547,0 for request Put ["b"]
         30001.238ms  15000.252ms    event:kv/kvserver/spanlatch/manager.go:613 [s1,r1/1:/M{in-ax}] context deadline exceeded while acquiring read latch b@1731631227.387628855,0 for request Get ["a"], Get ["b"], Get ["c"], Get ["d"], [max_span_request_keys: 1], [target_bytes: 0], held by write latch b@1731631227.387505547,0 for request Put ["b"]
         30001.294ms      0.057ms    event:kv/kvserver/replica_send.go:190 [s1,r1/1:/M{in-ax}] replica.Send got error: context deadline exceeded
             0.334ms -30000.960ms    structured:{"@type":"type.googleapis.com/cockroach.roachpb.ScanStats","numInterfaceSeeks":"2","numInternalSeeks":"2","keyBytes":"11","valueBytes":"10","pointCount":"1","numGets":"1","nodeId":1}
    replica_test.go:2911: unexpected error: context deadline exceeded
        --- FAIL: TestReplicaLatchingOptimisticEvaluationKeyLimit/point-reads=true/{writeKey:b_limit:1_interferes:false} (30.00s)
```

Seems like we tried optimistic evaluation, but we found an unexpected latch. We don't know much about what the conflicting latch is, in particular if we're incorrectly considering a latch as a conflict or whether there's a latch in the latch manager that the test doesn't expect. I'll add more observability, but I'll merge this PR as well given there's no reason not to.

**Comment by arulajmani** [comment]
TFTR! 

bors r+

**Pull request merged**
