### PR TITLE
decimal: Create powers of 10 lookup table for inf.Dec and big.Int

### LINKED ISSUE #5814: util: create a cache / lookup table for powers of 10 to accelerate numeric computations
As requested by @nvanbenschoten in https://github.com/cockroachdb/cockroach/pull/5750#issuecomment-204478877

To be used in `sql/table.go checkValueWidth` (#5750) and `sql/parser/eval.go SetClusterTimestamp` (#5805).

### LINKED ISSUE #5815: sql: accelerate checkValueWidth for DECIMAL
As suggested by @nvanbenschoten in https://github.com/cockroachdb/cockroach/pull/5750#issuecomment-204478877

" We may be able to do this without allocation, in a similar approach to how we get digit length in decimal encoding straight for the bits themselves without allocation."

### PR DESCRIPTION
**Pull request by nvb**
Fixes #5814.
Closes #5815.

This change creates a powers of 10 lookup table and then uses it where
possible. This allows us to reduce the need to allocate in a few key
places when dealing with decimals.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6716)

### CODE REVIEW

**Comment by knz** [comment]
:lgtm:

<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> #### decimal: Create powers of 10 lookup table for inf\.Dec and big\.Int
> 
> Fixes #5814.
> 
> Closes #5815.
> 
> 
> 
> This change creates a powers of 10 lookup table and then uses it where
> 
> possible. This allows us to reduce the need to allocate in a few key
> 
> places when dealing with decimals.
> 
> 
> 
> 
> 
> </details>


---

Reviewed 4 of 4 files at r1.
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[util/decimal/table.go, line 27 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716#-KHvvKEkwaN0i1JR60pZ:-KHvvKEkwaN0i1JR60p_:-1905024813) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dddb98eefdaf683189d0a6e039e56114eaed249/util/decimal/table.go#L27)):*
> ```Go
> const tableSize = 32
> 
> var pow10LookupTable [2*tableSize + 1]inf.Dec
> ```

Please explain the size in a comment.

---

*[util/decimal/table.go, line 42 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716#-KHvv_2iHrbZGqwHBvCi:-KHvv_2iHrbZGqwHBvCj:-1294471196) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dddb98eefdaf683189d0a6e039e56114eaed249/util/decimal/table.go#L42)):*
> ```Go
> func PowerOfTenDec(pow int) *inf.Dec {
> 	if pow >= -tableSize && pow <= tableSize {
> 		return &pow10LookupTable[pow+tableSize]
> ```

What is the rationale for using a fixed precomputed table, as opposed to a fully-fledged cache?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716#-:-KHvvj4PdhTtZNJUpPSC:1417088721)*

**Comment by nvanbenschoten** [comment]
TFTR!

<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> :lgtm:</details>


---

Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[util/decimal/table.go, line 27 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716#-KHvvKEkwaN0i1JR60pZ:-KHzFapHncfnA4iSwpdO:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dddb98eefdaf683189d0a6e039e56114eaed249/util/decimal/table.go#L27)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Please explain the size in a comment.</details>
Done.

---

*[util/decimal/table.go, line 42 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716#-KHvv_2iHrbZGqwHBvCi:-KHyxO37g7YpffVFgK-A:387963562) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dddb98eefdaf683189d0a6e039e56114eaed249/util/decimal/table.go#L42)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> What is the rationale for using a fixed precomputed table, as opposed to a fully-fledged cache?</details>
Complexity and bounded size. If we used a cache, we would want to use some sort of bounded size cache (LRU or something). This would make things more complicated and I doubt it would have any impact because I doubt we will often need values outside of the range `10^-32 - 10^32` (and in the cases that we do, this still isnt a loss). A cache would also be significantly larger that a single contiguous chunk of memory.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716#-:-KHzFireFP0o-MxmXj4L:-485616692)*

**Comment by RaduBerinde** [comment]
Review status: 3 of 6 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[util/decimal/table.go, line 38 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716#-KHzLNyqYoBZ0Tmjkw_h:-KHzLNyqYoBZ0Tmjkw_i:-819889861) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd78d55094efeb3ffcc17e29a3d397e8f4884516/util/decimal/table.go#L38)):*
> ```Go
> 		bi := pow10LookupTable[i+tableSize].UnscaledBig()
> 		bi.SetInt64(10)
> 		bi.Exp(bi, tmpInt.SetInt64(int64(i)), nil)
> ```

How is this supposed to work for negative `i` if we're just working with BigInt?

---

*[util/decimal/table.go, line 48 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716#-KHzL-u8UQtihkXbcwQZ:-KHzL-u8UQtihkXbcwQ_:518454810) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd78d55094efeb3ffcc17e29a3d397e8f4884516/util/decimal/table.go#L48)):*
> ```Go
> 		return &pow10LookupTable[pow+tableSize]
> 	}
> 	dec := inf.NewDec(10, 0)
> ```

So we have scale 0. How does this work for negative powers?

---

*[util/decimal/table.go, line 56 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716#-KHzLdxMiJFu4dTFvYV2:-KHzLdxMiJFu4dTFvYV3:-1954877683) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd78d55094efeb3ffcc17e29a3d397e8f4884516/util/decimal/table.go#L56)):*
> ```Go
> // PowerOfTenInt returns a *big.Int with the value 10^pow. It should
> // be treated as immutable.
> func PowerOfTenInt(pow int) *big.Int {
> ```

Can you add a test for this function? It should test all pairings of negative/positve, cached/uncached.

---

*[util/decimal/table.go, line 57 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716#-KHzKlL3cpCxc4sPMt3b:-KHzKlL3cpCxc4sPMt3c:-342765460) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd78d55094efeb3ffcc17e29a3d397e8f4884516/util/decimal/table.go#L57)):*
> ```Go
> // be treated as immutable.
> func PowerOfTenInt(pow int) *big.Int {
> 	return PowerOfTenDec(pow).UnscaledBig()
> ```

Should this panic for negative pow? Also don't we assume here that the scale of `PowerOfTenDec` is 0?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716)*

**Comment by RaduBerinde** [comment]
Review status: 3 of 6 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[util/decimal/table.go, line 42 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716#-KHvv_2iHrbZGqwHBvCi:-KHzSTBjoyG2o6f6ZAOc:756929736) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dddb98eefdaf683189d0a6e039e56114eaed249/util/decimal/table.go#L42)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Complexity and bounded size. If we used a cache, we would want to use some sort of bounded size cache (LRU or something). This would make things more complicated and I doubt it would have any impact because I doubt we will often need values outside of the range `10^-32 - 10^32` (and in the cases that we do, this still isnt a loss). A cache would also be significantly larger that a single contiguous chunk of memory.</details>
Plus it would need synchronization (a mutex).

---

*[util/decimal/table.go, line 48 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716#-KHzL-u8UQtihkXbcwQZ:-KHzTwLv642sg6mrW_-4:-1127299251) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd78d55094efeb3ffcc17e29a3d397e8f4884516/util/decimal/table.go#L48)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> So we have scale 0. How does this work for negative powers?</details>
Seems like for negative powers the caller should specify the desired precision and we can only use the precalculated values if they have enough precision..

---

*[util/decimal/table.go, line 56 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716#-KHzLdxMiJFu4dTFvYV2:-KHzSyYZjzoVUnoKI0yj:-1347671671) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd78d55094efeb3ffcc17e29a3d397e8f4884516/util/decimal/table.go#L56)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Can you add a test for this function? It should test all pairings of negative/positve, cached/uncached.</details>
(the negative/positive part only applies to the Dec version)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716)*

**Comment by nvanbenschoten** [comment]
Review status: 3 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[util/decimal/table.go, line 38 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716#-KHzLNyqYoBZ0Tmjkw_h:-KHzTsfbvMDiH2uAw8Xt:-2105921290) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd78d55094efeb3ffcc17e29a3d397e8f4884516/util/decimal/table.go#L38)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> How is this supposed to work for negative `i` if we're just working with BigInt?</details>
Ah yeah, thanks for catching that! I pulled the logic into `setDecWithPow` so that it remains consistent between cached and uncached values. PTAL

---

*[util/decimal/table.go, line 48 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716#-KHzL-u8UQtihkXbcwQZ:-KHzP671RTFuUl432PNB:369656218) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd78d55094efeb3ffcc17e29a3d397e8f4884516/util/decimal/table.go#L48)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Seems like for negative powers the caller should specify the desired precision and we can only use the precalculated values if they have enough precision..</details>
Done. I'm not quite sure what you mean about the precision though. Why would we want to limit the precalculated values to any precision?

---

*[util/decimal/table.go, line 56 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716#-KHzLdxMiJFu4dTFvYV2:-KHzP5wJWGvzF3i9t58o:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd78d55094efeb3ffcc17e29a3d397e8f4884516/util/decimal/table.go#L56)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Can you add a test for this function? It should test all pairings of negative/positve, cached/uncached.</details>
Done.

---

*[util/decimal/table.go, line 57 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716#-KHzKlL3cpCxc4sPMt3b:-KHzQhflLKHY_dfEll0n:-819570128) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd78d55094efeb3ffcc17e29a3d397e8f4884516/util/decimal/table.go#L57)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Should this panic for negative pow? Also don't we assume here that the scale of `PowerOfTenDec` is 0?</details>
Added a check for negative powers and non-zero scales.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716)*

**Comment by RaduBerinde** [comment]
Review status: 3 of 7 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[util/decimal/table.go, line 48 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716#-KHzL-u8UQtihkXbcwQZ:-KHzXkR0T0dSsZkwY2up:610209340) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd78d55094efeb3ffcc17e29a3d397e8f4884516/util/decimal/table.go#L48)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Done. I'm not quite sure what you mean about the precision though. Why would we want to limit the precalculated values to any precision?</details>
Ah never mind, we only need scale/precision as big as the exponent. Forgot we're dealing with powers of 10 and not some arbitrary number :)

---

*[util/decimal/table.go, line 45 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716#-KHzYm5ceh8v7SA7-k6k:-KHzYm5ceh8v7SA7-k6l:903807377) ([raw file](https://github.com/cockroachdb/cockroach/blob/7de3362ef7807b8956f153d1d64cfc92c0b4d00f/util/decimal/table.go#L45)):*
> ```Go
> // UnscaledBig value will also have a value of 10 to the provided power. A nullable *big.Int can
> // be provided to avoid an allocation during computation.
> func setDecWithPow(dec *inf.Dec, tmpInt *big.Int, pow int) {
> ```

If the caller is actually interested in a `Dec`, it's not ideal that we are actually computing the big int instead of just using the scale (like in the negative case).. Maybe we want separate tables for Dec and for BigInt?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716)*

**Comment by nvanbenschoten** [comment]
Review status: 3 of 7 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[util/decimal/table.go, line 45 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716#-KHzYm5ceh8v7SA7-k6k:-KHzeTorYVLAFWgxw98O:2123142315) ([raw file](https://github.com/cockroachdb/cockroach/blob/7de3362ef7807b8956f153d1d64cfc92c0b4d00f/util/decimal/table.go#L45)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> If the caller is actually interested in a `Dec`, it's not ideal that we are actually computing the big int instead of just using the scale (like in the negative case).. Maybe we want separate tables for Dec and for BigInt?</details>
Why is that not ideal? The `inf.Dec` library takes care of rescaling, and having a scale of 0 is more likely than any other scale to not force allocations on arithmetic.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716)*

**Comment by knz** [comment]
Reviewed 2 of 4 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716)*

**Comment by RaduBerinde** [comment]
:lgtm:

<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> TFTR!</details>


---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[util/decimal/table.go, line 45 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716#-KHzYm5ceh8v7SA7-k6k:-KHzkIecHp9Nq_AyJeTu:1089946468) ([raw file](https://github.com/cockroachdb/cockroach/blob/7de3362ef7807b8956f153d1d64cfc92c0b4d00f/util/decimal/table.go#L45)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Why is that not ideal? The `inf.Dec` library takes care of rescaling, and having a scale of 0 is more likely than any other scale to not force allocations on arithmetic.</details>
Because 1 with scale -100 is a much more efficient representation compared to a 100 digit bigint with scale 0. E.g. multiplying with the latter is 100 times slower..
Anyway, I will leave it to your judgement - maybe just make sure to document it for `PowerOfTenDec` so the caller knows what to expect. The rest of the change LGTM.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716#-:-KHzmfgBR0HOL498gZus:1417088721)*

**Comment by nvanbenschoten** [comment]
Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[util/decimal/table.go, line 45 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716#-KHzYm5ceh8v7SA7-k6k:-KHzuaRf6L1Dl2FvYFDo:-731898361) ([raw file](https://github.com/cockroachdb/cockroach/blob/7de3362ef7807b8956f153d1d64cfc92c0b4d00f/util/decimal/table.go#L45)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Because 1 with scale -100 is a much more efficient representation compared to a 100 digit bigint with scale 0. E.g. multiplying with the latter is 100 times slower..
> Anyway, I will leave it to your judgement - maybe just make sure to document it for `PowerOfTenDec` so the caller knows what to expect. The rest of the change LGTM.</details>
I see what you're saying, but I also dont think it's that straightforward. A lot of the operations (Add, Sub, Cmp) actually rescale values before the operation (see `upscale`). In this case, if the scales are different, it forces an allocation and we'd end up creating the current representation anyway, only on every operation. I think by far the most important case to handle here is comparing against a decimal that also has a scale of 0. I'll add a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6716)*

**Pull request merged**
