### PR TITLE
ui: Replacing "Admin UI" with "DB Console"

### PR DESCRIPTION
**Pull request by nathanstilwell**
Updated copy on Login page with the current name of the UI application
for CockroachDB ("DB Console").

for #70714

### CODE REVIEW

**Comment by celiala** [comment]
Hi @nathanstilwell - is there a GH issue or JIRA ticket tracking the this?

**Review by celiala — APPROVED** [review]
Change itself LGTM, although it would be nice to link this back to a GH/Jira ticket/Slack convo, if possible.

**Comment by nathanstilwell** [comment]
Good call @celiala. 

Here is the [Issue](https://github.com/cockroachdb/cockroach/issues/70714). I heard it from Tommy, so now sure where the larger Slack convo was happening.

**Comment by celiala** [comment]
:lgtm:

**Pull request merged**
