### PR TITLE
pgwire: various panic fixes during binary parameter decoding

### PR DESCRIPTION
**Pull request by madelynnblue**
All found with go-fuzz.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Awesome. I reviewed all commits but the last (Jordan/Justin, please have a look at the array fix). :lgtm: for the rest.

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38346#-:-LhtGuLL1fGnUp7xbtwK:b-nm5p14)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @justinj, @mjibson, and @rafiss)

___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 553 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38346#-LhtGbIi6bp6S6AIpaDa:-LhtGbIi6bp6S6AIpaDb:b1oho99) ([raw file](https://github.com/cockroachdb/cockroach/blob/86876133da2e8a52a7f97d2fd463ff4c78aaeb34/pkg/sql/pgwire/pgwirebase/encoding.go#L553)):*
> ```Go
> 		case oid.T_jsonb:
> 			if len(b) < 1 {
> 				return nil, NewProtocolViolationErrorf("insufficient data: %d", len(b))
> ```

maybe `no data to decode` is a better message? len is always 0 in this case.

**Review by jordanlewis — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38346)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @mjibson, and @rafiss)

**Comment by jordanlewis** [comment]
Great finds.

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38346)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @justinj, @knz, and @rafiss)

___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 553 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38346#-LhtGbIi6bp6S6AIpaDa:-LhvvM8WCrWlf8CDXY5B:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/86876133da2e8a52a7f97d2fd463ff4c78aaeb34/pkg/sql/pgwire/pgwirebase/encoding.go#L553)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

maybe `no data to decode` is a better message? len is always 0 in this case.
</blockquote></details>

done

**Pull request merged**
