### PR TITLE
storage/engine: lift Go MVCC implementation above Iterator interface

### PR DESCRIPTION
**Pull request by nvb**
This commit removes the `MVCCGet` and `MVCCScan` methods from `engine.Iterator` and uses the rest of the interface to implement these methods as free functions. This restructuring allows the MVCC operations to support polymorphism of the iterator, which is what the code was intending to do when originally written.

The code was moved to the current structure as a way of avoiding cgo calls when using RocksDB's iterator implementation. This is an important optimization when using RocksDB (but not Pebble) so the commit retains it through optional specializations of `MVCCGet` and `MVCCScan`. RocksDB's iterator implements this specialization but Pebble's does not need to.

This isn't quite ready for a review. I'm mainly pushing it in case others want to take a look. It will be used to get the prototype of #41720 up and running. Benchmarks show about a 0-1% performance regression due to this change. More testing should be done if we actually want to productionize this.

cc. @petermattis @itsbilal

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
Looks reasonable overall, though I'm saddened about the need to switch from `SeekLT` to `SeekReverse`. Is it urgent to get this in? Perhaps someone on the Storage team can find time to change `SeekReverse` to `SeekLT` everywhere. (Or perhaps you can). There are only a few uses the last time I checked.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42210#-:-Lt005QT1mcvhgWUhtSt:b2ow19)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @petermattis)

___
*[pkg/storage/engine/pebble_iterator.go, line 245 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42210#-Lt-n6W85khYtP9B6tOd:-Lt-n6W85khYtP9B6tOe:b-q37mf9) ([raw file](https://github.com/cockroachdb/cockroach/blob/79b4c775862f184d2b6dc6f5ba89cdff04d0c052/pkg/storage/engine/pebble_iterator.go#L245)):*
> ```Go
> 	// The seek key may have been past the last key. If so, position the
> 	// iterator at the last key.
> 	if !p.iter.Valid() && !p.iter.Last() {
> ```

I think this can be:

```
if !p.iter.Valid() {
  p.iter.Last()
  return
}
```

If the iterator isn't valid, we position it at the last key. Regardless of the validity of the iterator at that point, we return as there is nothing else to do.
___
*[pkg/storage/engine/pebble_iterator.go, line 251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42210#-Lt-nViu82sTCwY8keNl:-Lt-nViu82sTCwY8keNm:b-76nhp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/79b4c775862f184d2b6dc6f5ba89cdff04d0c052/pkg/storage/engine/pebble_iterator.go#L251)):*
> ```Go
> 	// The new key could either be greater or equal to the supplied key.
> 	// Backtrack one step if it is greater.
> 	p.keyBuf = EncodeKeyToBuf(p.keyBuf[:0], key)
> ```

We already encoded `key` to `keyBuf` in `pebbleIterator.Seek`. Perhaps that is using too much of an implementation detail. Rather than encoding `key`, it would probably be better to decode `p.iter.Key()` here as doing so doesn't involve a memory copy. I realize you're copying the existing pattern in this code, but I only just noticed this.
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42210#-Lt0-yGGAqYSk6_Rc_i9:-Lt0-yGGAqYSk6_Rc_iA:b7s6gfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/56f99c492d7a4a87e6148fdb404b347a468acfb0/pkg/storage/engine/pebble_mvcc_scanner.go#L76)):*
> ```Go
> 	binary.LittleEndian.PutUint32(p.repr[startIdx:], uint32(len(value)))
> 	binary.LittleEndian.PutUint32(p.repr[startIdx+4:], uint32(lenKey))
> 	encodeKeyToBuf(p.repr[startIdx+kvLenSize:startIdx+kvLenSize+lenKey], key, lenKey)
> ```

I'm surprised this isn't any slower compared to the previous code which was just doing a copy.
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 597 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42210#-Lt0-_L8E9yDpqppBD_u:-Lt0-_L8E9yDpqppBD_v:b-bclefa) ([raw file](https://github.com/cockroachdb/cockroach/blob/56f99c492d7a4a87e6148fdb404b347a468acfb0/pkg/storage/engine/pebble_mvcc_scanner.go#L597)):*
> ```Go
> 	// SeekReverse positions the iterator at the last key that is less than or
> 	// equal to key AND strictly less than IterOptions.UpperBound.
> 	p.parent.SeekReverse(key)
> ```

This is unfortunate. I really dislike the semantics of `SeekReverse`. I'd like to do a big rename of `Iterator.Seek` to `Iterator.SeekGE` and `Iterator.SeekReverse` to `Iterator.SeekLT` and change the semantics of `SeekReverse` to match `pebble.Iterator.SeekLT`.

**Review by petermattis — COMMENTED** [review]
> There are only a few uses the last time I checked.

Actually, outside of test code, there is only a single use of `SeekReverse`: `StateLoader.LoadLastIndex`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42210#-:-Lt00XTiBbNYBFK9ngFh:b-ghg5mx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @petermattis)

**Comment by nvanbenschoten** [comment]
Thanks for the review Peter.

> Is it urgent to get this in?

Nope, I'm just using it for my lock-table prototype. Although I might try to push it through later this week since I'd rather it not rot and it's a good change on its own. I'll take a close look at the performance impact of the extra memcpys when I do so.

> This is unfortunate. I really dislike the semantics of SeekReverse. I'd like to do a big rename of Iterator.Seek to Iterator.SeekGE and Iterator.SeekReverse to Iterator.SeekLT and change the semantics of SeekReverse to match pebble.Iterator.SeekLT.

Agreed. I had the same thought while making this change. It was a shame that the interface didn't line up with Pebble. How does #42390 look?

**Review by nvb — COMMENTED** [review]
Rebased on #42390. Running some numbers now and looking at profiles to see if there's any perf we can win back.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42210#-:-LtWFrvHE_Bx4wlLNoJI:b19w58g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis)

___
*[pkg/storage/engine/pebble_iterator.go, line 245 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42210#-Lt-n6W85khYtP9B6tOd:-LtW42jf-JiAlcMaQ5Sm:b-8zu7l0) ([raw file](https://github.com/cockroachdb/cockroach/blob/79b4c775862f184d2b6dc6f5ba89cdff04d0c052/pkg/storage/engine/pebble_iterator.go#L245)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think this can be:

```
if !p.iter.Valid() {
  p.iter.Last()
  return
}
```

If the iterator isn't valid, we position it at the last key. Regardless of the validity of the iterator at that point, we return as there is nothing else to do.
</blockquote></details>

No longer necessary.
___
*[pkg/storage/engine/pebble_iterator.go, line 251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42210#-Lt-nViu82sTCwY8keNl:-LtW45Js7U1neEjMa0BZ:b-8zu7l0) ([raw file](https://github.com/cockroachdb/cockroach/blob/79b4c775862f184d2b6dc6f5ba89cdff04d0c052/pkg/storage/engine/pebble_iterator.go#L251)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

We already encoded `key` to `keyBuf` in `pebbleIterator.Seek`. Perhaps that is using too much of an implementation detail. Rather than encoding `key`, it would probably be better to decode `p.iter.Key()` here as doing so doesn't involve a memory copy. I realize you're copying the existing pattern in this code, but I only just noticed this.
</blockquote></details>

No longer necessary.
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42210#-Lt0-yGGAqYSk6_Rc_i9:-LtWFVXM-VM24ab0T3ru:b-xcy4y9) ([raw file](https://github.com/cockroachdb/cockroach/blob/56f99c492d7a4a87e6148fdb404b347a468acfb0/pkg/storage/engine/pebble_mvcc_scanner.go#L76)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm surprised this isn't any slower compared to the previous code which was just doing a copy.
</blockquote></details>

`encodeKeyToBuf` isn't really doing all that much more than a copy, but I agree, I'm surprised it's not at least a bit slower. Do you think it's worth adding an `UnsafeRawKey` method to the `Iterator` interface to address this? I'm somewhat opposed because it makes key translations in intermediate iterators harder to do.
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 597 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42210#-Lt0-_L8E9yDpqppBD_u:-LtWFNST9RJH0t0TZvjx:bxgxzhu) ([raw file](https://github.com/cockroachdb/cockroach/blob/56f99c492d7a4a87e6148fdb404b347a468acfb0/pkg/storage/engine/pebble_mvcc_scanner.go#L597)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This is unfortunate. I really dislike the semantics of `SeekReverse`. I'd like to do a big rename of `Iterator.Seek` to `Iterator.SeekGE` and `Iterator.SeekReverse` to `Iterator.SeekLT` and change the semantics of `SeekReverse` to match `pebble.Iterator.SeekLT`. 
</blockquote></details>

Addressed elsewhere.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42210)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis)

___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42210#-Lt0-yGGAqYSk6_Rc_i9:-LtWL1E7CvASxGuIntv8:b-a12dvv) ([raw file](https://github.com/cockroachdb/cockroach/blob/56f99c492d7a4a87e6148fdb404b347a468acfb0/pkg/storage/engine/pebble_mvcc_scanner.go#L76)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`encodeKeyToBuf` isn't really doing all that much more than a copy, but I agree, I'm surprised it's not at least a bit slower. Do you think it's worth adding an `UnsafeRawKey` method to the `Iterator` interface to address this? I'm somewhat opposed because it makes key translations in intermediate iterators harder to do.
</blockquote></details>

I made just this portion of the change on `master` and it had the following impact:
```
name                                                old time/op    new time/op    delta
MVCCScan_Pebble/rows=10/versions=100/valueSize=8-8    52.8µs ± 2%    53.3µs ± 1%    ~     (p=0.123 n=10+10)

name                                                old speed      new speed      delta
MVCCScan_Pebble/rows=10/versions=100/valueSize=8-8  1.52MB/s ± 2%  1.50MB/s ± 1%  -0.99%  (p=0.074 n=10+10)
```

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42210)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @petermattis)

___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 597 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42210#-Lt0-_L8E9yDpqppBD_u:-LtWNW1f-rOza1XDQBAx:b-vosy7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/56f99c492d7a4a87e6148fdb404b347a468acfb0/pkg/storage/engine/pebble_mvcc_scanner.go#L597)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Addressed elsewhere.
</blockquote></details>

I'm not seeing your changes here. Did you forget to push?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42210)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis)

___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 597 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42210#-Lt0-_L8E9yDpqppBD_u:-LtWVm8_0s6aKk2Uu9D4:b-k1iili) ([raw file](https://github.com/cockroachdb/cockroach/blob/56f99c492d7a4a87e6148fdb404b347a468acfb0/pkg/storage/engine/pebble_mvcc_scanner.go#L597)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm not seeing your changes here. Did you forget to push?
</blockquote></details>

No, I hadn't pushed yet. Done.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42210#-:-LtWZFp-77KZ231P1n9P:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @petermattis)

___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42210#-Lt0-yGGAqYSk6_Rc_i9:-LtWX7tO8Nk0ATrqgF3j:bvkmddp) ([raw file](https://github.com/cockroachdb/cockroach/blob/56f99c492d7a4a87e6148fdb404b347a468acfb0/pkg/storage/engine/pebble_mvcc_scanner.go#L76)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I made just this portion of the change on `master` and it had the following impact:
```
name                                                old time/op    new time/op    delta
MVCCScan_Pebble/rows=10/versions=100/valueSize=8-8    52.8µs ± 2%    53.3µs ± 1%    ~     (p=0.123 n=10+10)

name                                                old speed      new speed      delta
MVCCScan_Pebble/rows=10/versions=100/valueSize=8-8  1.52MB/s ± 2%  1.50MB/s ± 1%  -0.99%  (p=0.074 n=10+10)
```
</blockquote></details>

Ack. Thanks for checking. I'm ok with this size of an effect. This is sort of worst-case as the keys in the benchmark are small. 
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 330 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42210#-LtWXxasCvxgFYKBgg3D:-LtWXxasCvxgFYKBgg3E:b-rkbu1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bde3fabeff3203ab296a134e3b87e10bd5ab00e/pkg/storage/engine/pebble_mvcc_scanner.go#L330)):*
> ```Go
> 		}
> 		p.keyBuf = EncodeKeyToBuf(p.keyBuf[:0], p.curMVCCKey())
> 		p.err = p.intents.Set(p.keyBuf, p.curValue, nil)
> ```

We don't expect to scan many intents, right? If we do, we could use the `SetDeferred` API to encode directly into the batch repr.
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 596 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42210#-LtWXISf9GWbH7CmzrMj:-LtWXISf9GWbH7CmzrMk:b-8gy7cl) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bde3fabeff3203ab296a134e3b87e10bd5ab00e/pkg/storage/engine/pebble_mvcc_scanner.go#L596)):*
> ```Go
> 
> 	// SeekReverse positions the iterator at the last key that is less than or
> 	// equal to key AND strictly less than IterOptions.UpperBound.
> ```

This comment is now incorrect.

**Review by nvb — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42210#-:-LtXCCpxCGh_CgM4ohIs:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten and @petermattis)

___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 330 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42210#-LtWXxasCvxgFYKBgg3D:-LtX925CAPRYU1e8PHGm:b-9clhhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bde3fabeff3203ab296a134e3b87e10bd5ab00e/pkg/storage/engine/pebble_mvcc_scanner.go#L330)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

We don't expect to scan many intents, right? If we do, we could use the `SetDeferred` API to encode directly into the batch repr.
</blockquote></details>

No, scanning over an intent should be fairly rare and we don't expect to scan very many even when we do. And if we do find an intent then an extra memcopy is probably the least of our concerns, so I don't think it's worth complicating the code to avoid the copy.

For reference though, this is what that change would look like:
```
diff --git a/pkg/storage/engine/pebble_mvcc_scanner.go b/pkg/storage/engine/pebble_mvcc_scanner.go
index 20d38b9f75..e8b287171f 100644
--- a/pkg/storage/engine/pebble_mvcc_scanner.go
+++ b/pkg/storage/engine/pebble_mvcc_scanner.go
@@ -326,11 +326,13 @@ func (p *pebbleMVCCScanner) getAndAdvance() bool {
                        // that lie before the resume key.
                        return false
                }
-               p.keyBuf = EncodeKeyToBuf(p.keyBuf[:0], p.curMVCCKey())
-               p.err = p.intents.Set(p.keyBuf, p.curValue, nil)
-               if p.err != nil {
-                       return false
-               }
+               curKey := p.curMVCCKey()
+               curKeyLen := curKey.Len()
+               deferredOp := p.intents.SetDeferred(curKeyLen, len(p.curValue))
+               encodeKeyToBuf(deferredOp.Key, curKey, curKeyLen)
+               copy(deferredOp.Value, p.curValue)
+               // NB: the batch is not indexed, obviating the need to call
+               // deferredOp.Finish.

                return p.seekVersion(prevTS, false)
        }
@@ -341,11 +343,14 @@ func (p *pebbleMVCCScanner) getAndAdvance() bool {
                // intent. Note that this will trigger an error on the Go
                // side. We continue scanning so that we can return all of the
                // intents in the scan range.
-               p.keyBuf = EncodeKeyToBuf(p.keyBuf[:0], p.curMVCCKey())
-               p.err = p.intents.Set(p.keyBuf, p.curValue, nil)
-               if p.err != nil {
-                       return false
-               }
+               curKey := p.curMVCCKey()
+               curKeyLen := curKey.Len()
+               deferredOp := p.intents.SetDeferred(curKeyLen, len(p.curValue))
+               encodeKeyToBuf(deferredOp.Key, curKey, curKeyLen)
+               copy(deferredOp.Value, p.curValue)
+               // NB: the batch is not indexed, obviating the need to call
+               // deferredOp.Finish.
+
                return p.advanceKey()
        }
```
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 596 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42210#-LtWXISf9GWbH7CmzrMj:-LtXAYU36hafwHE6oiCT:b-4c5ezp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bde3fabeff3203ab296a134e3b87e10bd5ab00e/pkg/storage/engine/pebble_mvcc_scanner.go#L596)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This comment is now incorrect.
</blockquote></details>

Good catch, done.

**Pull request merged**
