### PR TITLE
cli: misc zip-related fixes

### LINKED ISSUE #43966: cli: cockroach zip will not complete if there are decommissioned nodes
Reported by @roncrdb 

Currently if some nodes are fully decommissioned (i.e. also down)  `cockroach zip` will still try (and fail) to connect to them and retrieve data.

Failing to do so, it reports noisy error messages like this:

```
debug/nodes/1/crdb_internal.node_statement_statistics.txt
^- resulted in dial tcp 10.69.129.60:26257: i/o timeout
debug/nodes/1/crdb_internal.node_txn_stats.txt
^- resulted in dial tcp 10.69.129.60:26257: i/o timeout
debug/nodes/1/details.json
^- resulted in rpc error: code = Unknown desc = unable to look up descriptor for n1
debug/nodes/1/gossip.json
^- resulted in rpc error: code = Unknown desc = unable to look up descriptor for n1
```

This stops the cockroach debug zip from completing a rolling restart may fix this issue, but it would be good to find the root cause of what is happening as well.

### PR DESCRIPTION
**Pull request by knz**
Fixes #43966.
Mostly fixes the `zip` regression introduced in 19.2 by #36813.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
Very nice, thank you @knz 

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44064#-:-LyiRU7mDaJ0ggTjQDYD:b-nyia1w)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by knz** [comment]
TFYR

bors r=tbg

**Comment by knz** [comment]
let's queue this with the other one

bors r=tbg

**Comment by knz** [comment]
pulling this out until the bors queue clears

bors r-

**Comment by knz** [comment]
bors r=tbg

**Pull request merged**
