### PR TITLE
changefeedccl: disambiguate kv buffer metrics & logs

### LINKED ISSUE #127647: changefeedccl: improve observability into blocking buffer quota issues
We often see this error message in escalations and test failures:
https://github.com/cockroachdb/cockroach/blob/dc932b0aefac8b659f7639def224055b160e8cac/pkg/ccl/changefeedccl/kvevent/blocking_buffer.go#L466-L467

However, we use blocking buffers in 2 different places and it is difficult to tell from the error message which use of blocking buffer it is:
1. To copy the events from the rangefeed to the kvfeed https://github.com/cockroachdb/cockroach/blob/569b25ebc84dbf7ade336f29e74ad936462c02cf/pkg/ccl/changefeedccl/kvfeed/kv_feed.go#L118-L120
2. To copy the events from the kvfeed to the change aggregator so that we can send it to the change frontier or sink https://github.com/cockroachdb/cockroach/blob/d224681e50f3e3c791ccdc21eb4597241cb19bb7/pkg/ccl/changefeedccl/changefeed_processors.go#L338-L340

It would be nice if we updated the logs/metrics to make it easier to determine which site is experiencing the bottleneck.

Jira issue: CRDB-40533

Epic CRDB-37337

### PR DESCRIPTION
**Pull request by asg0451**
Disambiguates metrics and logs for the 2 buffers
used by the kv feed, so we can better identify
bottlenecks. The old versions are kept around for
backwards compatibility, though their use is not
recommended.

Fixes: #127647

Release note (enterprise change): Disambiguate
metrics and logs for the 2 buffers used by the kv
feed. Affected metrics now have a suffix
indicating which buffer they correspond to.
Affected metrics: `changefeed.buffer_entries.*`,
`changefeed.buffer_entries_mem.*`,
`changefeed.buffer_pushback_nanos.*`. The old
versions are kept around for backwards
compatibility, though their use is not
recommended.

### CODE REVIEW

**Review by rharding6373 — COMMENTED** [review]
This is going to be really helpful debugging issues in the future. Thank you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128813#-:-O47Rssc0IBZ_0vgG5Nn:b-axamwr)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andyyang890 and @asg0451)

___
*[`pkg/ccl/changefeedccl/kvevent/blocking_buffer.go` line 488 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128813#-O47Rkgz2h_TslCmSTf8:-O47Rkgz2h_TslCmSTf9:b-33d9s6) ([raw file](https://github.com/cockroachdb/cockroach/blob/49f704a9164b2d4f256aa1fec0a49635858e98c1/pkg/ccl/changefeedccl/kvevent/blocking_buffer.go#L488)):*
> ```Go
> 		return func() {
> 			if shouldLog {
> 				log.Infof(ctx, "acquired changefeed quota after %s", timeutil.Since(start))
> ```

Could you add the buffer type to this log message here, too?
___
*[`pkg/ccl/changefeedccl/kvevent/metrics.go` line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128813#-O47Qg6A2TOyv7RRPEu9:-O47Qg6A2TOyv7RRPEuA:bx09ivu) ([raw file](https://github.com/cockroachdb/cockroach/blob/49f704a9164b2d4f256aa1fec0a49635858e98c1/pkg/ccl/changefeedccl/kvevent/metrics.go#L85)):*
> ```Go
> func (PerBufferMetrics) MetricStruct() {}
> 
> type whichBuffer string
> ```

nit: I think that bufferName or bufferType would be clearer names.
___
*[`pkg/ccl/changefeedccl/kvevent/metrics.go` line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128813#-O47TNBK7gIbqYtm-emn:-O47TNBK7gIbqYtm-emo:b-qxr9lc) ([raw file](https://github.com/cockroachdb/cockroach/blob/49f704a9164b2d4f256aa1fec0a49635858e98c1/pkg/ccl/changefeedccl/kvevent/metrics.go#L94)):*
> ```Go
> // MakeMetrics constructs a Metrics struct with the provided histogram window.
> func MakeMetrics(histogramWindow time.Duration) Metrics {
> 	// HACK: we don't want to rely on labels for this, since tsdb doesn't support them. TODO: do we?
> ```

nit: update comment based on slack discussion (i.e., tsdb doesn't support labels)

**Review by asg0451 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128813)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andyyang890 and @rharding6373)

___
*[`pkg/ccl/changefeedccl/kvevent/blocking_buffer.go` line 488 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128813#-O47Rkgz2h_TslCmSTf8:-O4B6ONo9DCxlySPeI7z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/49f704a9164b2d4f256aa1fec0a49635858e98c1/pkg/ccl/changefeedccl/kvevent/blocking_buffer.go#L488)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Could you add the buffer type to this log message here, too?
</blockquote></details>

Done.

**Review by andyyang890 — COMMENTED** [review]
Thanks for making this change! Left a few comments about naming.

> Reviewed 6 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128813#-:-O4BDBaO6oL3GjIHT2Uq:b-9b3chq)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @asg0451 and @rharding6373)

___
*[`pkg/ccl/changefeedccl/kvevent/metrics.go` line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128813#-O4BCIoBC3f4kIrLfNWe:-O4BCIoBC3f4kIrLfNWf:bqub7u5) ([raw file](https://github.com/cockroachdb/cockroach/blob/093f8a7b46a418ae978b39571e5dd87266bf1175/pkg/ccl/changefeedccl/kvevent/metrics.go#L66)):*
> ```Go
> type Metrics struct {
> 	RangefeedBufferMetrics PerBufferMetrics
> 	KVFeedBufferMetrics    PerBufferMetrics
> ```

At the risk of bikeshedding, I'd prefer a name like `AggregatorBufferMetrics` since both of these buffers are used by the kvfeed. One is for copying in to the kvfeed from the rangefeed and the other is for copying out of the kvfeed by the aggregator.

Alternative name ideas: `KVFeedInBufferMetrics`/`KVFeedOutBufferMetrics`
___
*[`pkg/ccl/changefeedccl/kvevent/metrics.go` line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128813#-O4BAaCZDx4EZUUw5vHC:-O4BAaCZDx4EZUUw5vHD:b-i7pt97) ([raw file](https://github.com/cockroachdb/cockroach/blob/093f8a7b46a418ae978b39571e5dd87266bf1175/pkg/ccl/changefeedccl/kvevent/metrics.go#L70)):*
> ```Go
> 
> type PerBufferMetrics struct {
> 	Which                    bufferType
> ```

nit: would prefer a field name like `BufferType` or `BufferLabel`

**Review by rharding6373 — APPROVED** [review]
:lgtm: Left a nit given the recent refactor, but it looks very close. Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128813#-:-O4C2z6gEm6lcZ6z4frp:b-251y6p)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andyyang890 and @asg0451)

___
*[`pkg/ccl/changefeedccl/kvevent/metrics.go` line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128813#-O4C2gc24DwJXGzZ1scB:-O4C2gc24DwJXGzZ1scC:bjyzrpt) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad35c7cb582a9cce8a5c5a28afc751ea6792e078/pkg/ccl/changefeedccl/kvevent/metrics.go#L91)):*
> ```Go
> const (
> 	rangefeedBuffer bufferType = "rangefeed"
> 	kvFeedBuffer    bufferType = "kvfeed"
> ```

nit: consider renaming this to aggregator instead of kvfeed, too, since it looks like you're adopting Andy's naming suggestion.

**Review by andyyang890 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128813#-:-O4CIhY81OUFC0p-doXl:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @asg0451)

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128813)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @asg0451)

___
*[`pkg/ccl/changefeedccl/kvevent/metrics.go` line 96 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/128813#-O4GVtNN9-IJ-v8Egipv:-O4GVtNN9-IJ-v8Egipw:bwh2vqt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ea67ccd150cac6fca8f464ba417876ecce007ff/pkg/ccl/changefeedccl/kvevent/metrics.go#L96)):*
> ```Go
> 	}
> 	return Metrics{
> 		BufferEntriesIn:          metric.NewCounter(metaChangefeedBufferEntriesIn),
> ```

Thanks for catching that this would remove a publicly available metric. As discussed offline, we should keep the old one since this would be a breaking change. There's no harm in keeping it, so we don't need to start the deprecation process.

**Review by rharding6373 — APPROVED** [review]
:lgtm: after changing the language around deprecation. Thanks for the last-minute changes!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128813#-:-O4GrrfFCp_JzYHmoc8V:b-rj1hfg)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andyyang890 and @asg0451)

___
*[`-- commits` line 8 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/128813#-O4GrHOI-XdAQQfgK04H):*
nit: remove the "though they are now deprecated" here and in the release notes.
___
*[`pkg/ccl/changefeedccl/kvevent/metrics.go` line 65 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/128813#-O4Gm_GV9SR8k_fvEZnm:-O4Gm_GV9SR8k_fvEZnn:b-v50f18) ([raw file](https://github.com/cockroachdb/cockroach/blob/199f7bcb4c34547de4a0ec7875a5e397d44f523a/pkg/ccl/changefeedccl/kvevent/metrics.go#L65)):*
> ```Go
> // Metrics is a metric.Struct for kvfeed metrics.
> type Metrics struct {
> 	//rRangefeedBufferMetrics tracks metrics for the buffer between the rangefeed and the kvfeed.
> ```

nit: s/rRange/ Range/
___
*[`pkg/ccl/changefeedccl/kvevent/metrics.go` line 82 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/128813#-O4GrnTc2zzJnOO_Cc89:-O4GrnTc2zzJnOO_Cc8A:b-mboxla) ([raw file](https://github.com/cockroachdb/cockroach/blob/199f7bcb4c34547de4a0ec7875a5e397d44f523a/pkg/ccl/changefeedccl/kvevent/metrics.go#L82)):*
> ```Go
> 
> 	// DeprecatedBufferMetrics tracks the old metrics for both buffers.
> 	DeprecatedBufferMetrics PerBufferMetrics
> ```

Let's call this something like "CombinedBufferMetrics" instead since we aren't deprecating it and it might confuse us later on.

**Comment by asg0451** [comment]
bors r=rharding6373,andyyang890

**Review by andyyang890 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 8 files at r5, 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128813#-:-O4LbNPO-6kT4q8er28q:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @asg0451)

___
*[`pkg/ccl/changefeedccl/kvevent/metrics.go` line 100 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/128813#-O4Lb5DJ0H5U_VDjSWEs:-O4Lb5DJ0H5U_VDjSWEt:b-6pqh2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/78f620b8d36e38e1666e2c9a18bfe9dbcf44c929/pkg/ccl/changefeedccl/kvevent/metrics.go#L100)):*
> ```Go
> }
> 
> // forwardingCounter is a wrapper around multiple `*metric.Counter`s that
> ```

Thanks for adding comments!

**Comment by asg0451** [comment]
bors r=rharding6373,andyyang890

**Pull request merged**
