### PR TITLE
colexec: add support for Interval-related projections

### LINKED ISSUE #42044: colexec: add projections for TIMESTAMP
When #41662 is merged, we will have the support for `TIMESTAMP` type, but projections with timestamps will not be supported because other types (like `INTERVAL`) that are alongside the timestamps in the binary operations are still unsupported.

### PR DESCRIPTION
**Pull request by yuzefovich**
**util/duration: remove AdditionMode**

Over a year ago we made a backwards-incompatible change to fix the
normalization of dates during addition. To allow for mixed-version
clusters to work correctly, `AdditionMode` was introduced to enable old
"legacy" behavior. This tool is no longer needed because since 19.1
release all nodes "speak" the compatible addition mode.

Release note: None

**colexec: add support for Interval-related projections**

Almost all binary projections that have types.Interval as one of its
arguments are now supported. The only exception is with types.Date since
that would overlap with types.Int in "physical type" space.

Fixes: #42044.

Release note: None

**colexec: minor clean up of zeroing out in aggregates**

Previously we had "zero vectors" of which only a single zero value was
used when reset the current state of the SUM and AVG aggregates. This is
now refactored to store only the zero value.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
@bobvawter could you please review the first commit?

I think we don't need to add any unit tests for the vectorized projections because those are exercised via `TestEval.Vectorized` (I doubled-checked that those are run via the vectorized engine).

**Review by bobvawter — COMMENTED** [review]
The removal of `AdditionMode` LGTM.

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44609#-:-M-BWNKPAPKoRruhBlks:b-ndd42s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @bobvawter)

**Review by asubiotto — COMMENTED** [review]
Is there any overflow we have to worry about in some of these cases? OOC, how does this affect the amount of generated code?

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44609#-:-M-HKnLfEpMAnj0VXbEP:bw9tpl1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/utils.go, line 20 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44609#-M-HLrbg07tzhmxbddz-:-M-HLrbg07tzhmxbddz0:bulvj71) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5ae7eb6b900b839e22bc450753c087d24f0b0f6/pkg/sql/colexec/utils.go#L20)):*
> ```Go
> )
> 
> // TODO(yuzefovich): in most cases only need a single zero value.
> ```

nit: elaborate

**Review by yuzefovich — COMMENTED** [review]
I copied the behavior of overloads from `eval.go`, so the current behavior is identical to row-by-row execution. I think that your intuition is correct that there are cases when an overflow could occur, but I'd argue that should be a part of separate PR.

This change doesn't add much to the amount of generated code (only `proj_...eg.go` files are slightly impacted). The introduction of `Interval` type previously did increase the volume by roughly a factor of 1/8 (the same will go for every new type we add to `coltypes.T`). And if we refactor the type system somehow to pay attention to the logical SQL type in addition to the physical type, then the amount of generated code will increase significantly (any change to comparison overload code has big impact since pretty much all templates inline that).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44609#-:-M-IFU-u-8w4361vDZ1D:b-79q1ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @bobvawter)

___
*[pkg/sql/colexec/utils.go, line 20 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44609#-M-HLrbg07tzhmxbddz-:-M-IFNStCPInIz-BDTL_:btu0e8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5ae7eb6b900b839e22bc450753c087d24f0b0f6/pkg/sql/colexec/utils.go#L20)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: elaborate
</blockquote></details>

Added a third commit to address the TODO.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 8 of 8 files at r3, 5 of 5 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44609#-:-M-KpgP1Bzhh7N5FCKce:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
