### PR TITLE
cliccl/load: update `load show` with `summary` subcommand to display backup meta information

### PR DESCRIPTION
**Pull request by Elliebababa**
Previously, `cockroach load show <backup_path>` is used for debugging purposes, and displays all the metadata (including Spans, Files, Descriptors) of a single backup manifest file. 

With this PR, we update `load show` with `summary` subcommand. Users can inspect metadata of a single manifest by using `load show summary <backup_url>`. User-defined types and user-defined schemas are added to the output. Also, we add support of "nodelocal://0/" access.

see
#18434
#60790

Release justification: Non-production code changes
Release note (cli change): Update `load show` with `summary` subcommand to display information of backup metadata. Users can inspect metadata information of a single manifest by using `.cockroach load show summary <backup_url>`.

--------------------
```
$ ./cockroach load show summary "nodelocal://self/f1"                       
StartTime: 1970-01-01T00:00:00Z (0,0)
EndTime: 2021-02-24T02:14:12.635069Z (1614132852.635069000,0)
DataSize: 15772 (15 KiB)
Rows: 58
IndexEntries: 70
FormatVersion: 1
ClusterID: 171d37c2-0cb1-4f14-af20-5d9a51ccbbf3
NodeID: 0
BuildInfo: CockroachDB CCL v21.1.0-alpha.1-2022-g497a9c01d1 (x86_64-apple-darwin19.6.0, built 2021/02/17 17:23:27, go1.15.7)
Spans:
        /Table/4/{1-2}
        /Table/5/{1-2}
        /Table/6/{1-2}
        /Table/14/{1-2}
        /Table/15/{1-4}
        /Table/21/{1-2}
        /Table/23/{1-4}
        /Table/24/{1-2}
        /Table/33/{1-2}
        /Table/37/{1-3}
        /Table/52/{1-2}
        /Table/75/{1-2}
        /Table/76/{1-2}
        /Table/77/{1-2}
Files:
        635903846438207489.sst:
                Span: /Table/4/{1-2}
                DataSize: 99 (99 B)
                Rows: 2
                IndexEntries: 0
        635903846681772033.sst:
                Span: /Table/5/{1-2}
                DataSize: 282 (282 B)
                Rows: 7
                IndexEntries: 0
        635903846438338561.sst:
                Span: /Table/6/{1-2}
                DataSize: 374 (374 B)
                Rows: 5
                IndexEntries: 0
        635903846605324289.sst:
                Span: /Table/15/{1-4}
                DataSize: 14480 (14 KiB)
                Rows: 34
                IndexEntries: 68
        635903846439354369.sst:
                Span: /Table/21/{1-2}
                DataSize: 261 (261 B)
                Rows: 5
                IndexEntries: 0
        635903846599852033.sst:
                Span: /Table/23/{1-4}
                DataSize: 94 (94 B)
                Rows: 1
                IndexEntries: 2
        635903847072792577.sst:
                Span: /Table/75/{1-2}
                DataSize: 182 (182 B)
                Rows: 4
                IndexEntries: 0
Databases:
        1: system
        50: defaultdb
        51: postgres
Schemas:
        29: public
Types:
        (No user-defined types included in the specified backup path.)
Tables:
        4: system.public.users
        5: system.public.zones
        6: system.public.settings
        14: system.public.ui
        15: system.public.jobs
        21: system.public.locations
        23: system.public.role_members
        24: system.public.comments
        33: system.public.role_options
        37: system.public.scheduled_jobs
        52: defaultdb.public.products
        75: defaultdb.public.customers
        76: defaultdb.public.abc
        77: defaultdb.public.deep_folder
```

### CODE REVIEW

**Review by pbardea — COMMENTED** [review]
Looking good, did a first pass of it. Will go for a more indepth pass later today as well.

> Reviewed 1 of 4 files at r1, 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-:-MVHPcAP0X4nP-fC1lo-:b58to2p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Elliebababa and @pbardea)

___
*[pkg/ccl/cliccl/load.go, line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVHFfzG0y394xBKqxWq:-MVHFfzG0y394xBKqxWr:b-rfzpwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b82aa99379be63200359646eed32690e1c6f003e/pkg/ccl/cliccl/load.go#L214)):*
> ```Go
> }
> 
> func showDescriptor(desc backupccl.BackupManifest) {
> ```

Since this command claims to show all descriptors, we chatted about that we'll probably also want to display things like user defined schemas and types. Is the plan to add those in a follow up PR?
___
*[pkg/ccl/cliccl/load.go, line 232 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVHHzC0BV-d_SNZgC5-:-MVHHzC0BV-d_SNZgC50:b-a9cww) ([raw file](https://github.com/cockroachdb/cockroach/blob/b82aa99379be63200359646eed32690e1c6f003e/pkg/ccl/cliccl/load.go#L232)):*
> ```Go
> 	}
> 
> 	fmt.Printf("Tables:\n")
> ```

I think listing the descriptors would be interesting, more as a debugging tool. But I think users would be particularly interested  in the tables included in the backup. I think that offering a specific `cockroach load show tables command` that shows the fully qualified name would be nice since the output would be better format to pipe into other command (like potentially reading the data for that table).

This can be added in a follow up.

Listing the tables like:
```
$ cockroach load show tables <backup_url>
foodb.fooschema.footable
foodb.public.footable2
```

Should be what the user is really after, especially since the expected use-case of this tool is to see what tables are in the backup, so that they can get access to the data.
___
*[pkg/ccl/cliccl/load.go, line 172 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVHPR5L3FOsa-2Huw_N:-MVHPR5L3FOsa-2Huw_O:bainh1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffc78bf819b5c3fbdb8e719d01c755767c841d03/pkg/ccl/cliccl/load.go#L172)):*
> ```Go
> 	if _, ok := options[descriptors]; ok {
> 		err = showDescriptor(desc)
> 		if err != nil {
> ```

nit: just as an FYI, we frequently do:
```
if err := showDescriptors(desc); err != nil {
    return err
}
```
With this pattern/
___
*[pkg/ccl/cliccl/load.go, line 213 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVHL7yU6sxKzMUhhQI-:-MVHL7yU6sxKzMUhhQI0:b-dxjtcy) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffc78bf819b5c3fbdb8e719d01c755767c841d03/pkg/ccl/cliccl/load.go#L213)):*
> ```Go
> 	for _, f := range desc.Files {
> 		fmt.Printf("%s%s:\n", tabfmt, f.Path)
> 		fmt.Printf("	Span: %s\n", f.Span)
> ```

Should we be using `tabfmt` here and below?
___
*[pkg/ccl/cliccl/load_test.go, line 56 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVHOZvh6e6qfnNmc19T:-MVHOZvi1LDM7JSPTsxG:b-m9jfqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffc78bf819b5c3fbdb8e719d01c755767c841d03/pkg/ccl/cliccl/load_test.go#L56)):*
> ```Go
> 	}
> 
> 	// load show with spans option
> ```

nit: We usually format full line comments as full sentences: `// Test load show with span optiosn`. I think this would be a good candidate for a subtest e.g. `t.Run("show-spans", func(t *testing.T) { // test here}`.
___
*[pkg/ccl/cliccl/load_test.go, line 59 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVHOwVi0t9MEvigxeJf:-MVHOwVi0t9MEvigxeJg:b-aqbo50) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffc78bf819b5c3fbdb8e719d01c755767c841d03/pkg/ccl/cliccl/load_test.go#L59)):*
> ```Go
> 	out, err = c.RunWithCapture(fmt.Sprintf("load show %s spans --external-io-dir=%s", backupPath, dir))
> 	require.NoError(t, err)
> 	expectedSpansOutput :=
> ```

I think we can put this output to 1 line.
___
*[pkg/ccl/cliccl/load_test.go, line 75 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVHP0O9DnKM7moD5bHX:-MVHP0O9DnKM7moD5bHY:bxtxa8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffc78bf819b5c3fbdb8e719d01c755767c841d03/pkg/ccl/cliccl/load_test.go#L75)):*
> ```Go
> 	out, err = c.RunWithCapture(fmt.Sprintf("load show %s descriptors --external-io-dir=%s", backupPath, dir))
> 	require.NoError(t, err)
> 	expectedDescOutput :=
> ```

nit: can we unindent the first line of this string all the way for readability?

**Review by Elliebababa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

___
*[pkg/ccl/cliccl/load.go, line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVHFfzG0y394xBKqxWq:-MVI0sEm7AiaOn0JQboG:b-zd6gtk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b82aa99379be63200359646eed32690e1c6f003e/pkg/ccl/cliccl/load.go#L214)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Since this command claims to show all descriptors, we chatted about that we'll probably also want to display things like user defined schemas and types. Is the plan to add those in a follow up PR?
</blockquote></details>

Yes. It is displaying user-defined schemas now (under the `Schemas:` in `load show descriptors` command).  Will include types in the same PR.
___
*[pkg/ccl/cliccl/load.go, line 232 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVHHzC0BV-d_SNZgC5-:-MVI2OCgEvjFPfn9KcwV:b-bnxzkn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b82aa99379be63200359646eed32690e1c6f003e/pkg/ccl/cliccl/load.go#L232)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I think listing the descriptors would be interesting, more as a debugging tool. But I think users would be particularly interested  in the tables included in the backup. I think that offering a specific `cockroach load show tables command` that shows the fully qualified name would be nice since the output would be better format to pipe into other command (like potentially reading the data for that table).

This can be added in a follow up.

Listing the tables like:
```
$ cockroach load show tables <backup_url>
foodb.fooschema.footable
foodb.public.footable2
```

Should be what the user is really after, especially since the expected use-case of this tool is to see what tables are in the backup, so that they can get access to the data.
</blockquote></details>

Will add it in a follow up PR.
___
*[pkg/ccl/cliccl/load.go, line 213 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVHL7yU6sxKzMUhhQI-:-MVI0dIB1IhbInTgWg5i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffc78bf819b5c3fbdb8e719d01c755767c841d03/pkg/ccl/cliccl/load.go#L213)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Should we be using `tabfmt` here and below?
</blockquote></details>

Done.
___
*[pkg/ccl/cliccl/load_test.go, line 59 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVHOwVi0t9MEvigxeJf:-MVI368K7nQ32xQBom2r:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffc78bf819b5c3fbdb8e719d01c755767c841d03/pkg/ccl/cliccl/load_test.go#L59)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I think we can put this output to 1 line.
</blockquote></details>

Done.

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Elliebababa and @pbardea)

___
*[pkg/ccl/cliccl/load.go, line 46 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVMNBh89yRiQN2eDCOV:-MVMNBh89yRiQN2eDCOW:bt8mh7t) ([raw file](https://github.com/cockroachdb/cockroach/blob/e71331d88dbcc583363e1c1983f3182f7c07318b/pkg/ccl/cliccl/load.go#L46)):*
> ```Go
> 		Short: "show backups summary",
> 		Long:  "Shows summary of meta information about a SQL backup.",
> 		Args:  cobra.MinimumNArgs(1),
> ```

Should this be `cobra.ExactArgs(1)`?
___
*[pkg/ccl/cliccl/load.go, line 53 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVMMw_f8Sy1E37mke0V:-MVMMw_f8Sy1E37mke0W:b-brxpnx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e71331d88dbcc583363e1c1983f3182f7c07318b/pkg/ccl/cliccl/load.go#L53)):*
> ```Go
> 		Use:   "show [command]",
> 		Short: "show backup information",
> 		Long:  "Shows subset(s) of information about a SQL backup.",
> ```

I think we can keep this as the old description now.
___
*[pkg/ccl/cliccl/load.go, line 85 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVMNS6y5xrmoAIecd2I:-MVMNS6y5xrmoAIecd2J:b-ve6pln) ([raw file](https://github.com/cockroachdb/cockroach/blob/e71331d88dbcc583363e1c1983f3182f7c07318b/pkg/ccl/cliccl/load.go#L85)):*
> ```Go
> func newBlobFactory(ctx context.Context, dialing roachpb.NodeID) (blobs.BlobClient, error) {
> 	if dialing != 0 {
> 		return nil, errors.Errorf(`only support nodelocal (0/self) under cli inspection`)
> ```

nit: The phrasing of this error message is a bit confusing to me. Perhaps something like `errors.Errorf(`accessing node %d during nodelocal access is unsupported for CLI inspection; only local access is supported with nodelocal://self`, dialing)`?
___
*[pkg/ccl/cliccl/load.go, line 165 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVMRW1m2L56nlphnCnn:-MVMRW1n94B2KNeBBmsS:btui09a) ([raw file](https://github.com/cockroachdb/cockroach/blob/e71331d88dbcc583363e1c1983f3182f7c07318b/pkg/ccl/cliccl/load.go#L165)):*
> ```Go
> 	schemaIDToNameChain := make(map[descpb.ID]string)
> 	schemaIDToNameChain[keys.PublicSchemaID] = sessiondata.PublicSchemaName
> 	typeIDs := make([]descpb.ID, 0)
> ```

It looks like the slices and maps here are storing the same information? Can we just use the map here?
___
*[pkg/ccl/cliccl/load.go, line 186 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVMS7srBR20iruyWQj-:-MVMS7srBR20iruyWQj0:b-98ledi) ([raw file](https://github.com/cockroachdb/cockroach/blob/e71331d88dbcc583363e1c1983f3182f7c07318b/pkg/ccl/cliccl/load.go#L186)):*
> ```Go
> 			typeIDToNameChain[id] = parentSchema + "." + typeName
> 			typeIDs = append(typeIDs, id)
> 		}
> ```

We'll still want `showDescriptors` to show the tables as well I think. I think that users may be interested in showing just the tables as a separate command that we can add in a follow-up, but I think we'll want to keep tables here like we had before.
___
*[pkg/ccl/cliccl/load.go, line 202 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVMPYaY5hF0G5HhhnCc:-MVMPYaY5hF0G5HhhnCd:b-ce7ee2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e71331d88dbcc583363e1c1983f3182f7c07318b/pkg/ccl/cliccl/load.go#L202)):*
> ```Go
> 
> 	if len(typeIDs) > 0 {
> 		fmt.Printf("Types:\n")
> ```

Let's put the header above the `if` check to explicitly show that there are no types included in the backup.
___
*[pkg/ccl/cliccl/load_test.go, line 59 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVMKs3d1CCqf-WYqC8m:-MVMKs3d1CCqf-WYqC8n:b38gqah) ([raw file](https://github.com/cockroachdb/cockroach/blob/e71331d88dbcc583363e1c1983f3182f7c07318b/pkg/ccl/cliccl/load_test.go#L59)):*
> ```Go
> 		expectedDescOutput := `
> Databases:
> 	52.testdb
> ```

I think we should avoid formatting this as `id.name` since names are partitioned by `.` (e.g. `testdb.public.footype`). Let's instead format it as either `52: testdb` or `testdb (52)`.
___
*[pkg/cli/cli_test.go, line 50 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVMPoZZ1vN3zDMgGvK7:-MVMPoZZ1vN3zDMgGvK8:bpgkxh9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e71331d88dbcc583363e1c1983f3182f7c07318b/pkg/cli/cli_test.go#L50)):*
> ```Go
> 	skip.UnderShort(t)
> 
> 	c := NewCliTest(TestCliParams{T: t})
> ```

I think I preferred `NewCLITest` returning a `CLITest`. I think things get a bit more confusing when renaming the structs to `TestCli`. The rename is also a separate change from what the commit is achieving, which is exporting the helpers for ccl tests to access.
___
*[pkg/cli/doctor_test.go, line 24 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVMMMVY7tRV1LApZsGo:-MVMMMVY7tRV1LApZsGp:bmqnyd5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e71331d88dbcc583363e1c1983f3182f7c07318b/pkg/cli/doctor_test.go#L24)):*
> ```Go
> func TestDoctorCluster(t *testing.T) {
> 	defer leaktest.AfterTest(t)()
> 	c := NewCliTest(TestCliParams{T: t})
> ```

nit: I think the old capitalization of CLI is what we typically do. For acronyms, the later letters usually follow the casing of the first one.
___
*[pkg/cli/testutils.go, line 114 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVMLP6x08G8DbZuLxUe:-MVMLP6x08G8DbZuLxUf:b-molk0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e71331d88dbcc583363e1c1983f3182f7c07318b/pkg/cli/testutils.go#L114)):*
> ```Go
> }
> 
> // NewCliTest export for cclcli
> ```

nit: we usually format comments that are on their own line as full sentences (ie end in a `.`). Here and the couple of other places in this file.

**Review by pbardea — APPROVED** [review]
LGTM with a minor comment nit, also tagging @itsbilal to take a look from the CLI side. Note: the load command is currently undocumented and we're cleaning it up. The main thing to review from the CLI side is https://github.com/cockroachdb/cockroach/pull/61131/commits/5c95fcfebb9c9c2421b377eed1ef00af3b481bd5.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-:-MVXQHoW968Rh-sYloB8:bmw2dhp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Elliebababa and @pbardea)

___
*[pkg/cli/testutils.go, line 43 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVXPXmL2fkk9Xqp93V6:-MVXPXmL2fkk9Xqp93V7:b-5iri8x) ([raw file](https://github.com/cockroachdb/cockroach/blob/f33e92115af97e3277650121f2b70bbacc062700/pkg/cli/testutils.go#L43)):*
> ```Go
> }
> 
> // TestCLI represents test for cli.
> ```

nit: I think we can say a bit more in this comment, something like: `TestCLI wraps a test server and is used by tests to make assertions about the output of CLI commands.`

**Review by itsbilal — APPROVED** [review]
5c96fcf looks good to me! I've left some comments but they're mostly just about style / struct naming that should be fairly easy to fix. Good work!

> Reviewed 16 of 16 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-:-MVY4fuC7FKJGdNl0wpl:bkh00x0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Elliebababa, @itsbilal, and @pbardea)

___
*[pkg/ccl/cliccl/load.go, line 223 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVY1ome2vq34khqg5lj:-MVY1ome2vq34khqg5lk:brwzgfd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c95fcfebb9c9c2421b377eed1ef00af3b481bd5/pkg/ccl/cliccl/load.go#L223)):*
> ```Go
> 	// Note that these descriptors could be from any past version of the cluster,
> 	// in case more fields need to be added to the output.
> 	dbIDs := make([]descpb.ID, 0)
> ```

Nit: You can save some repeat allocations by passing a capacity like `dbIDs := make([]descpb.ID, 0, len(desc.Descriptors))`. It's okay if it's larger than what it ends up being.
___
*[pkg/ccl/cliccl/load_test.go, line 41 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVY2gMYA6F3LzTOTU_o:-MVY2gMZC6Pp1tFz7mXf:b5dkyhp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c95fcfebb9c9c2421b377eed1ef00af3b481bd5/pkg/ccl/cliccl/load_test.go#L41)):*
> ```Go
> 
> 	sqlDB := sqlutils.MakeSQLRunner(db)
> 	sqlDB.Exec(t, `CREATE DATABASE testDB`)
> ```

Probably a good idea to throw a `require.NoError` around these Execs.
___
*[pkg/cli/testutils.go, line 44 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVY3xEG5cHJTEJOEoAR:-MVY3xEG5cHJTEJOEoAS:biszcxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c95fcfebb9c9c2421b377eed1ef00af3b481bd5/pkg/cli/testutils.go#L44)):*
> ```Go
> 
> // TestCLI represents test for cli
> type TestCLI struct {
> ```

I see Paul alluded to this earlier, but can we go with calling this `CLITest` (and the params struct `CLITestParams`) instead? That way it's both more consistent with the existing code, and leads to less confusion / naming conflicts with functions named `TestCLI*` that are actual test functions. I don't feel very strongly about this so if y'all have agreed to go with this for some reason, feel free to ignore this little point.

**Review by Elliebababa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @pbardea)

___
*[pkg/ccl/cliccl/load.go, line 46 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVMNBh89yRiQN2eDCOV:-MVMeupq3GKxhV7f1Dvb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e71331d88dbcc583363e1c1983f3182f7c07318b/pkg/ccl/cliccl/load.go#L46)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Should this be `cobra.ExactArgs(1)`?
</blockquote></details>

Done.
___
*[pkg/ccl/cliccl/load.go, line 53 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVMMw_f8Sy1E37mke0V:-MVMg4UN2mQ2DVvV-1V7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e71331d88dbcc583363e1c1983f3182f7c07318b/pkg/ccl/cliccl/load.go#L53)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I think we can keep this as the old description now.
</blockquote></details>

Done.
___
*[pkg/ccl/cliccl/load.go, line 165 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVMRW1m2L56nlphnCnn:-MVMyaM-4q-mv1mEtags:b-b6y5k8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e71331d88dbcc583363e1c1983f3182f7c07318b/pkg/ccl/cliccl/load.go#L165)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

It looks like the slices and maps here are storing the same information? Can we just use the map here?
</blockquote></details>

Note: the slices are used to keep descriptors sorted by IDs. We can remove it once we found sorting descriptors is not necessarily needed.
___
*[pkg/ccl/cliccl/load.go, line 186 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVMS7srBR20iruyWQj-:-MVMit1X3ykOsq8IiD-E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e71331d88dbcc583363e1c1983f3182f7c07318b/pkg/ccl/cliccl/load.go#L186)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

We'll still want `showDescriptors` to show the tables as well I think. I think that users may be interested in showing just the tables as a separate command that we can add in a follow-up, but I think we'll want to keep tables here like we had before.
</blockquote></details>

Done.
___
*[pkg/ccl/cliccl/load.go, line 202 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVMPYaY5hF0G5HhhnCc:-MVMmZJX-_mQsmd6g581:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e71331d88dbcc583363e1c1983f3182f7c07318b/pkg/ccl/cliccl/load.go#L202)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Let's put the header above the `if` check to explicitly show that there are no types included in the backup.
</blockquote></details>

Done.
___
*[pkg/ccl/cliccl/load.go, line 223 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVY1ome2vq34khqg5lj:-MVYWDVN0YRvYyX8vXT4:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c95fcfebb9c9c2421b377eed1ef00af3b481bd5/pkg/ccl/cliccl/load.go#L223)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Nit: You can save some repeat allocations by passing a capacity like `dbIDs := make([]descpb.ID, 0, len(desc.Descriptors))`. It's okay if it's larger than what it ends up being.
</blockquote></details>

Done
___
*[pkg/ccl/cliccl/load_test.go, line 59 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVMKs3d1CCqf-WYqC8m:-MVMn2CU3P_vrP_cwh-y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e71331d88dbcc583363e1c1983f3182f7c07318b/pkg/ccl/cliccl/load_test.go#L59)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I think we should avoid formatting this as `id.name` since names are partitioned by `.` (e.g. `testdb.public.footype`). Let's instead format it as either `52: testdb` or `testdb (52)`.
</blockquote></details>

Done.
___
*[pkg/ccl/cliccl/load_test.go, line 41 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVY2gMYA6F3LzTOTU_o:-MVYcp0U5x0zpERA57Hx:b2mes5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c95fcfebb9c9c2421b377eed1ef00af3b481bd5/pkg/ccl/cliccl/load_test.go#L41)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Probably a good idea to throw a `require.NoError` around these Execs.
</blockquote></details>

SQLRunner exec comment says:'Exec is a wrapper around gosql.Exec that kills the test on error'. If I didn't get it wrong, the error will be catched by running `sqlDB.Exec` (I tried, it did). But if I missed something else, please correct me :)
___
*[pkg/cli/cli_test.go, line 50 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVMPoZZ1vN3zDMgGvK7:-MVO-GWu9zzmefefT_R-:b5o0ryy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e71331d88dbcc583363e1c1983f3182f7c07318b/pkg/cli/cli_test.go#L50)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I think I preferred `NewCLITest` returning a `CLITest`. I think things get a bit more confusing when renaming the structs to `TestCli`. The rename is also a separate change from what the commit is achieving, which is exporting the helpers for ccl tests to access.
</blockquote></details>

Note: cliTest is renamed to TestCLI to pass linter check.
___
*[pkg/cli/testutils.go, line 44 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/61131#-MVY3xEG5cHJTEJOEoAR:-MVYYmqU-BYyjOv1qR3p:b-fg2hiu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c95fcfebb9c9c2421b377eed1ef00af3b481bd5/pkg/cli/testutils.go#L44)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I see Paul alluded to this earlier, but can we go with calling this `CLITest` (and the params struct `CLITestParams`) instead? That way it's both more consistent with the existing code, and leads to less confusion / naming conflicts with functions named `TestCLI*` that are actual test functions. I don't feel very strongly about this so if y'all have agreed to go with this for some reason, feel free to ignore this little point.
</blockquote></details>

I tried CLITest and CLITestParams, but given that those exported structs are in cli pkg, struct names starting with 'CLI..' is failing by the linter. If you got other thoughts about the naming, I will follow up with this :)

**Review by pbardea — APPROVED** [review]
LGTM, I think this is good to merge!

**Comment by Elliebababa** [comment]
TFTR!
bors = pbardea, itsbilal

**Comment by Elliebababa** [comment]
TFTR!
bors r=pbardea,itsbilal

**Pull request merged**
