### PR TITLE
colexec: speed up aggregator benchmark

### PR DESCRIPTION
**Pull request by yuzefovich**
Our existing BenchmarkAggregator takes unreasonably long time to run
because we benchmark every aggregate function against 48 different
configurations (2 aggregator kinds x 3 types x 4 group sizes x 2 nulls
configs). However, most of those numbers follow the same pattern and
don't provide us with a lot of useful data, so this commit splits the
benchmark into two and reduces the number of configs. One benchmark is
now responsible for measuring the performance of aggregator operators,
but we do so only on a single aggregate function and a single input
type which is sufficient. Another one is running the benchmark of all
aggregate functions with just 4 configurations with the goal of giving
us a sense of relative speeds of different functions. I kept the naming
of the runs of the former benchmark to be the same as the original
benchmark had so that we could perform a limited comparison against the
old branches.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
The updated `BenchmarkAggregator` now takes about 30s, and the newly added `BenchmarkAllAggregateFunctions` takes about 60s.

[Here](https://gist.github.com/yuzefovich/a3d0dd7064b19536d8a96e72411a213b) is the output of running `BENCHES=BenchmarkAggregator scripts/bench` against master with `count=1` (the goal was to check that we can compare against the old branches - meaning that the benchmark run name is the same).

**Comment by jordanlewis** [comment]
Nice idea. LGTM.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by asubiotto** [comment]
Do we want to run these benchmarks with `benchshort`? 60s seems too long to want to do so. You could add:
```
if testing.Short() {
    b.Skip()
}
```
Like we do in other long-running benchmarks.

**Review by yuzefovich — COMMENTED** [review]
The old very long running `BenchmarkAggregator` wasn't skipped for some reason-  I think we haven't been very principal with marking the benchmarks to be skipped for `benchshort`, we probably need to audit the existing benchmarks. By the way, I don't see any guideline on what is considered "long" for the purposes of `benchshort`? Like 10 second threshold? It might also make sense depending on the -short flag to change the set of configurations that we run with, instead of skipping the whole benchmark altogether.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50933#-:-MBZjKLH0aD6cBBQB_Vz:b-l8kgo5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by asubiotto** [comment]
> It might also make sense depending on the -short flag to change the set of configurations that we run with

That's a good idea.

> I think we haven't been very principal with marking the benchmarks to be skipped for benchshort,

We haven't. I remember doing an audit when I added it but nothing since. The point is to just make sure the benchmarks don't rot.

**Pull request merged**
