### PR TITLE
sqlsmith: improve desired type generation

### PR DESCRIPTION
**Pull request by madelynnblue**
Teach SELECT to generate desired types from tables in the FROM clause
to increase the chance that the SELECT expressions are chosen from among
those columns. This prevents the super common problem of `SELECT [buncha
consts] FROM table1, table2` where none of the columns from table1 or
table2 are selected.

Consts are still generated with some frequency and so will still appear
at times.

In order for functions and binary operators where the inputs types aren't
the output type (which could cause certain binary ops or functions to
never be chosen), tables should contain all types (as our manual tests
do) or eventually generate all types (as the random table creator does).

Release note: None

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
:lgtm:

> In order for functions and binary operators where the inputs types aren't
> the output type (which could cause certain binary ops or functions to
> never be chosen), tables should contain all types (as our manual tests
> do) or eventually generate all types (as the random table creator does).
I don't quite follow this, I think it might be missing a few words? "In order for functions and binary operators .... [to be generated]" maybe?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38027#-:-LgbyDy06ah6FqChbWs7:b-m34oi2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @mjibson, and @rafiss)

___
*[pkg/internal/sqlsmith/relational.go, line 499 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38027#-Lgc-HY42ZQ1N9C4Qv3l:-Lgc-HY42ZQ1N9C4Qv3m:bxo9ogk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e940375e503e42beea820082d32670b49214992/pkg/internal/sqlsmith/relational.go#L499)):*
> ```Go
> 	if len(desiredTypes) == 0 {
> 		typeRefs := refs.extend()
> 		s.schema.rnd.Shuffle(len(typeRefs), func(i, j int) {
> ```

I've used this pattern before too, feels like there could be a generalized helper in the same vein to get `k` random elements from a list, called like
```
Sample(len(typeRefs), func(i int) {
  append(desiredTypes, typeRefs[i].typ)
})
```
(obviously what you have here is fine too)
___
*[pkg/internal/sqlsmith/relational.go, line 502 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38027#-LgbypyeERsdyHd2v2TE:-LgbypyeERsdyHd2v2TF:b-fwn5s8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e940375e503e42beea820082d32670b49214992/pkg/internal/sqlsmith/relational.go#L502)):*
> ```Go
> 			typeRefs[i], typeRefs[j] = typeRefs[j], typeRefs[i]
> 		})
> 		for len(typeRefs) > 0 && s.d6() >= 2 {
> ```

super nit: could also be `s.d6() == 1` right? then I think the probability achieved might be a little clearer.

**Review by justinj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38027)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson and @rafiss)

___
*[pkg/internal/sqlsmith/relational.go, line 499 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38027#-Lgc-HY42ZQ1N9C4Qv3l:-LgcenlC8MR05bUG7-36:b-ny4wdy) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e940375e503e42beea820082d32670b49214992/pkg/internal/sqlsmith/relational.go#L499)):*
> Sample(len(typeRefs), func(i int) {
>   append(desiredTypes, typeRefs[i].typ)
> })

realized i omitted `k`, which would be the number of samples:
```
Sample(len(typeRefs), k, func(i int) {
  append(desiredTypes, typeRefs[i].typ)
})
```
To make this more usable, to get `k` in this particular case, you're rolling a d6 until you get a 1, which I think is a geometric random variable with `p = 5/6` which could just be a function:
```
func Geom(p float64) int {
  count = 0
  for math.RandFloat64() < p {
    count++
  }
  return count
}
```
then
```
Sample(len(typeRefs), Geom(5/6), func(i int) {
  append(desiredTypes, typeRefs[i].typ)
})
```

**Review by madelynnblue — COMMENTED** [review]
I just removed that whole paragraph. It was weird and not that useful.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38027#-:-LgdLPLBEvU0XlVJqbB9:b-q55r9e)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj and @rafiss)

___
*[pkg/internal/sqlsmith/relational.go, line 499 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38027#-Lgc-HY42ZQ1N9C4Qv3l:-LgdLSmm0WvCdtdaTSDy:bdig31u) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e940375e503e42beea820082d32670b49214992/pkg/internal/sqlsmith/relational.go#L499)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

> Sample(len(typeRefs), func(i int) {
>   append(desiredTypes, typeRefs[i].typ)
> })

realized i omitted `k`, which would be the number of samples:
```
Sample(len(typeRefs), k, func(i int) {
  append(desiredTypes, typeRefs[i].typ)
})
```
To make this more usable, to get `k` in this particular case, you're rolling a d6 until you get a 1, which I think is a geometric random variable with `p = 5/6` which could just be a function:
```
func Geom(p float64) int {
  count = 0
  for math.RandFloat64() < p {
    count++
  }
  return count
}
```
then
```
Sample(len(typeRefs), Geom(5/6), func(i int) {
  append(desiredTypes, typeRefs[i].typ)
})
```
</blockquote></details>

Done. I've added a new commit that does this.
___
*[pkg/internal/sqlsmith/relational.go, line 502 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38027#-LgbypyeERsdyHd2v2TE:-LgdLV5C2QndgL7c3WD2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e940375e503e42beea820082d32670b49214992/pkg/internal/sqlsmith/relational.go#L502)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

super nit: could also be `s.d6() == 1` right? then I think the probability achieved might be a little clearer.
</blockquote></details>

Done.

**Review by justinj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38027)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj, @mjibson, and @rafiss)

___
*[pkg/internal/sqlsmith/random.go, line 51 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38027#-LgdQNIA61amPU4KwbMh:-LgdQNIA61amPU4KwbMi:blj921) ([raw file](https://github.com/cockroachdb/cockroach/blob/d08121116d2d0b549ce032ca5a825ce4cce4e4b1/pkg/internal/sqlsmith/random.go#L51)):*
> ```Go
> // .5 to this function (whose mean would thus be 2), and 50% of the time this
> // function will return 1, 25% will return 2, 12.5% return 3, 6.25% will return
> // 4, etc.
> ```

nit: include a link to the wikipedia page maybe, or provide a quick definition of a geometric distribution
___
*[pkg/internal/sqlsmith/relational.go, line 499 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38027#-Lgc-HY42ZQ1N9C4Qv3l:-LgdO6Vm4sy0bOC_qNs-:b-ijk9mn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e940375e503e42beea820082d32670b49214992/pkg/internal/sqlsmith/relational.go#L499)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Done. I've added a new commit that does this.
</blockquote></details>

Nice! I love it

**Pull request merged**
