### PR TITLE
sql: modulo by prime in shard calculation for hash-sharded indexes

### LINKED ISSUE #91109: sql: non-uniform hash-sharded index with power-of-2 number of buckets
Looks like the hash bucket calculation `mod(fnv32(crdb_internal.datums_to_bytes(x, y)), z)` is poorly distributed when x and y are INT8 columns with equal values, and z is a power of 2. For example:

```sql
CREATE TABLE ijk (i, j, k) AS SELECT x, x, x FROM generate_series(0, 1048575) s (x);
CREATE INDEX ON ijk (i) USING HASH WITH BUCKET_COUNT = 8;
CREATE INDEX ON ijk (i, j) USING HASH WITH BUCKET_COUNT = 8;
CREATE INDEX ON ijk (i, j, k) USING HASH WITH BUCKET_COUNT = 8;
SELECT crdb_internal_i_shard_8, COUNT(crdb_internal_i_shard_8) FROM ijk GROUP BY 1 ORDER BY 1;
SELECT crdb_internal_i_j_shard_8, COUNT(crdb_internal_i_j_shard_8) FROM ijk GROUP BY 1 ORDER BY 1;
SELECT crdb_internal_i_j_k_shard_8, COUNT(crdb_internal_i_j_k_shard_8) FROM ijk GROUP BY 1 ORDER BY 1;
```

Gives:

```
demo@127.0.0.1:26257/defaultdb> SELECT crdb_internal_i_shard_8, COUNT(crdb_internal_i_shard_8) FROM ijk GROUP BY 1 ORDER BY 1;
  crdb_internal_i_shard_8 | count
--------------------------+---------
                        0 | 131071
                        1 | 131071
                        2 | 131072
                        3 | 131072
                        4 | 131073
                        5 | 131073
                        6 | 131072
                        7 | 131072
(8 rows)


Time: 770ms total (execution 770ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> SELECT crdb_internal_i_j_shard_8, COUNT(crdb_internal_i_j_shard_8) FROM ijk GROUP BY 1 ORDER BY 1;
  crdb_internal_i_j_shard_8 | count
----------------------------+---------
                          1 | 376905
                          3 |  16348
                          5 | 638976
                          7 |  16347
(4 rows)


Time: 836ms total (execution 835ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> SELECT crdb_internal_i_j_k_shard_8, COUNT(crdb_internal_i_j_k_shard_8) FROM ijk GROUP BY 1 ORDER BY 1;
  crdb_internal_i_j_k_shard_8 | count
------------------------------+---------
                            0 | 131073
                            1 | 131071
                            2 | 131071
                            3 | 131072
                            4 | 131072
                            5 | 131073
                            6 | 131072
                            7 | 131072
(8 rows)


Time: 976ms total (execution 976ms / network 0ms)
```

The hash-sharded index is still unevenly distributed with 16 buckets:

```
demo@127.0.0.1:26257/defaultdb> CREATE INDEX ij16 ON ijk (i, j) USING HASH WITH BUCKET_COUNT = 16;
CREATE INDEX


Time: 5.629s total (execution 5.629s / network 0.000s)

demo@127.0.0.1:26257/defaultdb> SELECT crdb_internal_i_j_shard_16, COUNT(crdb_internal_i_j_shard_16) FROM ijk GROUP BY 1 ORDER BY 1;
  crdb_internal_i_j_shard_16 | count
-----------------------------+---------
                           1 | 184357
                           3 |  12224
                           5 | 487461
                           7 |   8174
                           9 | 192548
                          11 |   4124
                          13 | 151515
                          15 |   8173
(8 rows)


Time: 819ms total (execution 819ms / network 0ms)
```

With 14 it's evenly distributed across half the buckets:

```
demo@127.0.0.1:26257/defaultdb> CREATE INDEX ij14 ON ijk (i, j) USING HASH WITH BUCKET_COUNT = 14;
CREATE INDEX


Time: 6.913s total (execution 6.912s / network 0.000s)

demo@127.0.0.1:26257/defaultdb> SELECT crdb_internal_i_j_shard_14, COUNT(crdb_internal_i_j_shard_14) FROM ijk GROUP BY 1 ORDER BY 1;
  crdb_internal_i_j_shard_14 | count
-----------------------------+---------
                           1 | 149778
                           3 | 150045
                           5 | 149398
                           7 | 149531
                           9 | 150521
                          11 | 149379
                          13 | 149924
(7 rows)


Time: 846ms total (execution 846ms / network 0ms)
```

With a prime number of buckets it's fine:

```
demo@127.0.0.1:26257/defaultdb> CREATE INDEX ij17 ON ijk (i, j) USING HASH WITH BUCKET_COUNT = 17;
CREATE INDEX


Time: 6.533s total (execution 6.532s / network 0.000s)

demo@127.0.0.1:26257/defaultdb> SELECT crdb_internal_i_j_shard_17, COUNT(crdb_internal_i_j_shard_17) FROM ijk GROUP BY 1 ORDER BY 1;
  crdb_internal_i_j_shard_17 | count
-----------------------------+--------
                           0 | 61416
                           1 | 61852
                           2 | 61537
                           3 | 61534
                           4 | 61605
                           5 | 62347
                           6 | 61745
                           7 | 61611
                           8 | 61527
                           9 | 61494
                          10 | 62198
                          11 | 61752
                          12 | 61749
                          13 | 61353
                          14 | 61502
                          15 | 61921
                          16 | 61433
(17 rows)


Time: 849ms total (execution 849ms / network 0ms)
```

This example is (admittedly) contrived, but there could be other cases like this. Maybe we should default to creating a prime number of buckets?

Jira issue: CRDB-21107

Epic CRDB-27601

### PR DESCRIPTION
**Pull request by michae2**
We've discovered a case where a combination of non-random data and a power-of-two number of buckets causes an uneven distribution of rows in a hash-sharded index. While this specific case is very contrived, it illustrates a small weakness in the current hash-shard calculation: modulo by a power-of-two number of buckets only uses the last few bits of the hash value.

Radu suggested this would be a problem in #67865 and also suggested a fix: add an intermediate modulo by a larger prime before modulo by num buckets, so we'll try that.

Fixes: #91109

Epic: None

Release note (performance improvement): This change updates the shard calculation of newly-created hash-sharded indexes so that uneven distributions of rows are less likely.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
:lgtm: Consider rewording the release note to make it clear that it was a rare scenario in which they were uneven in the first place? 

Did you try it out on your experiment? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91155#-:-NFu-Omc1t9p0czjFkqa:bjy6jig)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Comment by Xiang-Gu** [comment]
Even though we module by 16 (power of two, non-prime), but the actual hash-function is [fnv32](https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function), which is supposed to give even distributions. If you see a uneven outcome, then isn't this `fnv32` to blame?

**Comment by michae2** [comment]
Hmm, this modulo-of-modulo is giving worse results for the common cases, especially with large numbers of buckets. With 512 buckets we get five buckets with 20% more rows than the rest of the buckets. (2053 % 512 = 5.) The skew gets better with the prime much larger than the number of buckets, but then it gets worse again as the prime gets close to max uint32. This feels half-baked to me... maybe we need some other way to incorporate more of the bits of the hash value while not introducing a skew.

Using a prime number of buckets is evenly distributed. But this modulo of modulo is not.

> Even though we module by 16 (power of two, non-prime), but the actual hash-function is [fnv32](https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function), which is supposed to give even distributions. If you see a uneven outcome, then isn't this `fnv32` to blame?

Good point. Maybe it would be simpler to use a different hash function, one more robust to power-of-two number of buckets.

**Comment by ajwerner** [comment]
> If you see a uneven outcome, then isn't this fnv32 to blame?

Yes

**Comment by ajwerner** [comment]
This is a very specific and weird input. I don't know how much we care about it. In practice I don't think we've seen this skew.

**Comment by ajwerner** [comment]
I'm happy to do nothing here

**Comment by michae2** [comment]
How about we suggest in docs that people use a prime number of buckets?

**Comment by ajwerner** [comment]
> How about we suggest in docs that people use a prime number of buckets?

I feel like we need more evidence that this pattern of values actually shows up.

**Comment by michae2** [comment]
> > How about we suggest in docs that people use a prime number of buckets?
> 
> I feel like we need more evidence that this pattern of values actually shows up.

**Pull request closed without merging**
