### PR TITLE
colbuilder: optimize casting in edge cases

### PR DESCRIPTION
**Pull request by yuzefovich**
**colbuilder: return custom error for LocalPlanNode core**

If a particular processor core is not supported, we return a general
error (in order to not incur any allocations when printing out the type
of the core). However, `LocalPlanNode` core is quite special (because we
don't have any plans on vectorizing it at the moment, if ever), so it
deserves a separate error object.

Release note: None

**colbuilder: optimize casting in edge cases**

In order to make sure that `NewColOperator` call produces the type
schema as expected, we are planning casts between the mismatched types.
If a particular cast is not supported natively by the vectorized engine,
we have to fallback to wrapping a row-execution noop processor.
Previously, we would create a separate processor for each such
mismatched column. However, this is quite inefficient if multiple
columns need to be casted this way (the processor itself isn't free but
also we need to plan another pair of materializer - columnarizer
wrappers).

This commit switches that casting planning to be a bit smarter - to
check explicitly whether all necessary casts are supported natively -
which allows us to plan a single row-execution processor to handle all
unsupported casts at once. Currently, if a row-execution processor is
needed, we will use it to handle all mismatched types, even the ones for
which we have native cast operation. The reasoning behind this change is
that this commit needs to be backportable (so it must be as bullet-proof
as possible) but also it might be actually a better option since all
vectorized casts will append more columns to go through the
materializer-columnarizer pair. It is left as a TODO to explore which
way is better in more detail.

Fixes: https://github.com/cockroachlabs/support/issues/1008.

Release note: None

### CODE REVIEW

**Review by michae2 — CHANGES_REQUESTED** [review]
Great find! This is really, really nice.

> Reviewed 1 of 1 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65972#-:-MbD8-Ld2BNFKfITr9wx:b-q1p1ep)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/colbuilder/execplan.go, line 1480 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65972#-MbCjquH6uKE29HNcaqW:-MbCjquH6uKE29HNcaqX:b707ehs) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b691d8b7bc061a5337d320723e1cd8778fb507b/pkg/sql/colexec/colbuilder/execplan.go#L1480)):*
> ```Go
> }
> 
> var errWrappedCast = errors.New("mismatched types in NewColOperator and unsupported casts")
> ```

nit: Could we move this to the set of errors at the top of the file?
___
*[pkg/sql/colexec/colexecbase/cast_tmpl.go, line 144 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65972#-MbCoEL3-g57iBW_CBav:-MbCoEL3-g57iBW_CBaw:bosv98i) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b691d8b7bc061a5337d320723e1cd8778fb507b/pkg/sql/colexec/colexecbase/cast_tmpl.go#L144)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
> 			switch typeconv.TypeFamilyToCanonicalTypeFamily(rightType.Family()) {
> 			// {{range .RightFamilies}}
> 			case _RIGHT_CANONICAL_TYPE_FAMILY:
> 				switch rightType.Width() {
> 				// {{range .RightWidths}}
> 				case _RIGHT_TYPE_WIDTH:
> 					return true
> 					// {{end}}
> 				}
> 				// {{end}}
> 			}
> ```
</details>


Is this is just checking that both types are in the set of types native to the vectorized engine? If so, I think it would be better to have a single function like `func IsTypeNative(type *types.T) bool` and then check it for both left and right types, as that would lead to O(Types) code instead of O(Types ^ 2) code.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65972)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2)

___
*[pkg/sql/colexec/colbuilder/execplan.go, line 1480 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65972#-MbCjquH6uKE29HNcaqW:-MbDew7NEgr4wCL-BcRb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b691d8b7bc061a5337d320723e1cd8778fb507b/pkg/sql/colexec/colbuilder/execplan.go#L1480)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: Could we move this to the set of errors at the top of the file?
</blockquote></details>

Done.
___
*[pkg/sql/colexec/colexecbase/cast_tmpl.go, line 144 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65972#-MbCoEL3-g57iBW_CBav:-MbDezaA5C_7SeJa3jZv:b-awcved) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b691d8b7bc061a5337d320723e1cd8778fb507b/pkg/sql/colexec/colexecbase/cast_tmpl.go#L144)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

> ```
> 			switch typeconv.TypeFamilyToCanonicalTypeFamily(rightType.Family()) {
> 			// {{range .RightFamilies}}
> 			case _RIGHT_CANONICAL_TYPE_FAMILY:
> 				switch rightType.Width() {
> 				// {{range .RightWidths}}
> 				case _RIGHT_TYPE_WIDTH:
> 					return true
> 					// {{end}}
> 				}
> 				// {{end}}
> 			}
> ```

Is this is just checking that both types are in the set of types native to the vectorized engine? If so, I think it would be better to have a single function like `func IsTypeNative(type *types.T) bool` and then check it for both left and right types, as that would lead to O(Types) code instead of O(Types ^ 2) code.
</blockquote></details>

No, the check in this PR is much more restrictive than what you're suggesting. We currently have very limited support of native casts (take a look at the generated `cast.eg.go`); e.g. we don't have any casts from bytes-like types at all as well as from intervals or timestamps. The tracking issue is #48135. We register these "cast overloads" in `overloads_cast.go`.

**Review by michae2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65972#-:-MbDjjl1CnSg-LMfOsoM:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/colexecbase/cast_tmpl.go, line 144 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65972#-MbCoEL3-g57iBW_CBav:-MbDhnUX9A1k1EC0Ajr9:b-wqq5ox) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b691d8b7bc061a5337d320723e1cd8778fb507b/pkg/sql/colexec/colexecbase/cast_tmpl.go#L144)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

No, the check in this PR is much more restrictive than what you're suggesting. We currently have very limited support of native casts (take a look at the generated `cast.eg.go`); e.g. we don't have any casts from bytes-like types at all as well as from intervals or timestamps. The tracking issue is #48135. We register these "cast overloads" in `overloads_cast.go`.
</blockquote></details>

Ah, I see, I needed to look at `twoArgsResolvedOverloadsInfo.CastOverloads`. Sorry about that! Looks good!

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65972#-:-MbDkXFJ0yZW89FtYEv3:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/colexecbase/cast_tmpl.go, line 144 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65972#-MbCoEL3-g57iBW_CBav:-MbDkVmS6n5aM4GN98Uc:b-vqkjus) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b691d8b7bc061a5337d320723e1cd8778fb507b/pkg/sql/colexec/colexecbase/cast_tmpl.go#L144)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Ah, I see, I needed to look at `twoArgsResolvedOverloadsInfo.CastOverloads`. Sorry about that! Looks good!
</blockquote></details>

No worries!

**Pull request merged**
