### PR TITLE
distsql: add `distsql-disk` configuration to logic tests (incl. bigtest)

### PR DESCRIPTION
**Pull request by asubiotto**
Previously we only used the `distsql-disk` configuration in `postgresjoin`.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
For many of the files, it doesn't make much sense to run in this configuration (e.g. event_log, dependencies, inet). It would be useful to trim them down to avoid making logic tests take 30% longer.

**Comment by asubiotto** [comment]
Done, PTAL. I left a couple of files (`collatedstring_*`, `datetime`) where I think it's interesting to test the ORDER BY statements.

**Comment by RaduBerinde** [comment]
What about the `distsql_*` tests? Should we have a `5node-disk` config as well?

**Comment by asubiotto** [comment]
Added a `5node-distsql-disk` config

**Comment by RaduBerinde** [comment]
LGTM 💯

**Pull request merged**
