### PR TITLE
sql/parser: parse CREATE PROCEDURE

### PR DESCRIPTION
**Pull request by mgartner**
#### sql/parser: parse CREATE PROCEDURE

`CREATE PROCEDURE` statements can now be parsed by the SQL parser.
Currently, executing `CREATE PROCEDURE` will produce an unimplemented
error.

Epic: CRDB-25388

Release note: None

#### sem/tree: rename function AST nodes

This commit renames UDF-related AST nodes with "function" in the name to
use the more general term "routine". The term "routine" is inclusive of
both UDFs and procedures (e.g., Postgres implements a `DROP ROUTINE`
statement which drops both UDFs and procedures), which is fitting
because we'll be using the same AST nodes for both `CREATE FUNCTION` and
`CREATE PROCEDURE` statements.

Release note: None

#### sem/tree: rename udf.go to create_routine.go

Release note: None

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm: Definitely more renaming to do, but we can do more passes later.

> Reviewed 16 of 16 files at r1, 49 of 49 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106325#-:-N_5vm9f4qWA5gps4qx6:b-3nnhc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @mgartner, and @samiskin)

___
*[`pkg/sql/parser/help_test.go` line 576 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106325#-N_5Pp568p1vKEqhkurc:-N_5Pp568p1vKEqhkurd:b-vu853o) ([raw file](https://github.com/cockroachdb/cockroach/blob/07f31eb0a340b4887a89f9dbe26edb97eed430f4/pkg/sql/parser/help_test.go#L576)):*
> ```Go
> 		{`ALTER FUNCTION ??`, `ALTER FUNCTION`},
> 		{`DROP FUNCTION ??`, `DROP FUNCTION`},
> ```

[nit] Is this line meant to be here?

**Review by mgartner — COMMENTED** [review]
Any specific renaming you had in mind?

I originally renamed everything, then reverted a few things like options that only apply to UDFs and not procedures. We could rename them anyway - whatever is less confusing.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106325#-:-N_LJeqj4uYdDtZusVjM:bpbuvvr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @DrewKimball, and @samiskin)

___
*[`pkg/sql/parser/help_test.go` line 576 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106325#-N_5Pp568p1vKEqhkurc:-N_LJysq9tfcQcjAeggl:bhow2hw) ([raw file](https://github.com/cockroachdb/cockroach/blob/07f31eb0a340b4887a89f9dbe26edb97eed430f4/pkg/sql/parser/help_test.go#L576)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Is this line meant to be here?
</blockquote></details>

I added the new line to separate it from the UDF statements, to follow the pattern above.

**Comment by DrewKimball** [comment]
>Any specific renaming you had in mind?

Just small things like `createFunctionNode`, `setFuncOptions`, that sort of thing.

>I originally renamed everything, then reverted a few things like options that only apply to UDFs and not procedures.

This sounds reasonable to me.

**Comment by chengxiong-ruan** [comment]
I'll give this a look today as well.

**Review by chengxiong-ruan — APPROVED** [review]
LGTM. Nice work

**Comment by yuzefovich** [comment]
I think this might need a rebase.
```
[20:44:43][CheckGeneratedCode] pkg/sql/sem/builtins/pg_builtins.go:742:28: undefined: tree.FunctionLangSQL
[20:44:43][CheckGeneratedCode] pkg/sql/sem/builtins/pg_builtins.go:2206:28: undefined: tree.FunctionLangSQL
```

bors r-

**Pull request merged**
