### PR TITLE
reduce: add SQL reducer

### PR DESCRIPTION
**Pull request by madelynnblue**
reduce is a new command and package that reduces SQL based on a target
error. It is implemented in 3 separate packages for reuse.

The reduce package contains the base reduction algorithm described in
its godoc. It has some helpers, but otherwise doesn't know about any
specific language.

The reducesql package contains the reducers for SQL.

The reduce command wraps both of those packages in a CLI command that
reduces SQL by running cockroach demo.

Release note: None

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
This is unreal! So cool. :lgtm: with some requests for more explanation

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-:-LkP2xQ6C36pTcMgDb43:b-kfedkl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @justinj, @mjibson, and @yuzefovich)

___
*[pkg/testutils/reduce/datadriven.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkP34_G10xALu-tdZtD:-LkP34_G10xALu-tdZtE:b-how2xf) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/datadriven.go#L30)):*
> ```Go
> }
> 
> // RunTest executes reducer commands. In verobes mode, output is written to
> ```

nite: verobes
___
*[pkg/testutils/reduce/datadriven.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkP3BhFB32zVMw6iIXc:-LkP3BhG5Dl-CKClendg:b-ekkevh) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/datadriven.go#L33)):*
> ```Go
> // stderr. Supported commands:
> //
> // "contains": Sets the contains variable that is passed to interesting. No
> ```

nit: this comment could be a little more descriptive: "Sets the substring that must be contained by an error message for a test case to be marked as interesting"
___
*[pkg/testutils/reduce/reduce.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkP6UzG4C_Ls-ZxrCQ8:-LkP6UzHABGYcbCmLt7-:b-48h3c8) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/reduce.go#L27)):*
> ```Go
> // Pass defines a reduce pass.
> type Pass interface {
> 	New(File) State
> ```

Can you explain what the contracts are for these methods?
___
*[pkg/testutils/reduce/reduce.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkPA_dN8_Wl-8JdOLmy:-LkPA_dN8_Wl-8JdOLmz:bvili25) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/reduce.go#L98)):*
> ```Go
> 		}
> 	}
> 	log("total time: %v\n", timeutil.Since(start))
> ```

how long does this tend to take, ooc?
___
*[pkg/testutils/reduce/reduce.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkPAx9cB0tmUweXd8mi:-LkPAx9dCqsR7fZHBJH9:b3flkxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/reduce.go#L101)):*
> ```Go
> 	log("original size: %v\n", originalTestCase.Size())
> 	log("final size: %v\n", current.Size())
> 	log("reduction: %v%%\n", 100-int(100*float64(current.Size())/float64(originalTestCase.Size())))
> ```

it would be neat to also optionally see a list of the transformations that were applied to get to the reduced state
___
*[pkg/testutils/reduce/reduce.go, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkP3gYr-8ITJu95neym:-LkP3gYr-8ITJu95neyn:b-sgxjp3) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/reduce.go#L109)):*
> ```Go
> // MakeIntPass returns a Pass with a state that starts at 0 and increments
> // by 1 each Advance. f is a transformation function that takes the input and
> // current state (that is, it should transform the i'th (zero-based) unit. It
> ```

nit: unclosed paren
___
*[pkg/testutils/reduce/reduce.go, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkP6DqW4rKB5xvsVTbc:-LkP6DqW4rKB5xvsVTbd:b5ksvfm) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/reduce.go#L109)):*
> ```Go
> // MakeIntPass returns a Pass with a state that starts at 0 and increments
> // by 1 each Advance. f is a transformation function that takes the input and
> // current state (that is, it should transform the i'th (zero-based) unit. It
> ```

I know you linked to John Regehr's post, but I think the algorithm/terminology here could be explained in some more detail—what is a "unit", for example? And what does it mean for `i` to be exhausted?
___
*[pkg/testutils/reduce/reduce.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkP7P9j0ob3wr6A6R9Y:-LkP7P9j0ob3wr6A6R9Z:b7kljj7) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/reduce.go#L112)):*
> ```Go
> // returns the possibly transformed output and a boolean that is false if a
> // transformation could not be done because i was exhausted.
> func MakeIntPass(f func(s string, i int) (out string, ok bool, err error)) Pass {
> ```

Given that there aren't `Pass`es that aren't `IntPass`es, I think it would be helpful to describe in more detail what it is that this specialization is, since the reader doesn't have anything else to contrast it to (or just remove the interface).
___
*[pkg/testutils/reduce/reducesql/reducesql.go, line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkP7o9rEYbcCx2N_ef3:-LkP7o9rEYbcCx2N_ef4:bn1jutp) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/reducesql/reducesql.go#L92)):*
> ```Go
> 
> 	semaCtx := tree.MakeSemaContext()
> 	_ = semaCtx
> ```

still needed?
___
*[pkg/testutils/reduce/reducesql/reducesql.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkP7xjL3Xi_aXZLARck:-LkP7xjL3Xi_aXZLARcl:bdm69q8) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/reducesql/reducesql.go#L101)):*
> ```Go
> 	var replacement tree.NodeFormatter
> 	var walk func(...interface{})
> 	walk = func(nodes ...interface{}) {
> ```

is there any way you can hook into the existing `Walk` code? Probably not, I guess?
___
*[pkg/testutils/reduce/reducesql/reducesql.go, line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkP4P868TTGg2JfRnHZ:-LkP4P868TTGg2JfRnH_:b8zmf0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/reducesql/reducesql.go#L211)):*
> ```Go
> 				if !unknownTypes[n] {
> 					unknownTypes[n] = true
> 					//fmt.Println("UNKNOWN", n)
> ```

nit: stray comment
___
*[pkg/testutils/reduce/reducesql/reducesql.go, line 240 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkP5UnL1q8h4EcVHj07:-LkP5UnL1q8h4EcVHj08:b1508o0) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/reducesql/reducesql.go#L240)):*
> ```Go
> 
> var (
> 	removeLimit = walkSQL(func(xfi int, node interface{}) int {
> ```

nice, I like this pattern of being able to use the same function to both detect and perform transformations :thumbsup:
___
*[pkg/testutils/reduce/reducesql/reducesql.go, line 563 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkPBBUs5FIHtBc7lOtY:-LkPBBUs5FIHtBc7lOtZ:bvaqkyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/reducesql/reducesql.go#L563)):*
> ```Go
> 			if node.With != nil {
> 				if xf {
> 					node.With = nil
> ```

Maybe explain somewhere that we can safely mutate these since we re-parse every time?
___
*[pkg/testutils/reduce/reducesql/reducesql.go, line 790 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkP8c8H4MPcO7VRiaHn:-LkP8c8H4MPcO7VRiaHo:bf5cqla) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/reducesql/reducesql.go#L790)):*
> ```Go
> 		return 0
> 	})
> ```

nit: extra line
___
*[pkg/testutils/reduce/reducesql/testdata/simple, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkPBKQH-Sau3vBrC3t7:-LkPBKQH-Sau3vBrC3t8:bkxcaes) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/reducesql/testdata/simple#L1)):*
> ```
> contains
> ```

nit: mix of spaces and tabs in this file
___
*[pkg/testutils/reduce/reducesql/testdata/simple, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkPBMTZ-4AjI6cvPd6p:-LkPBMTZ-4AjI6cvPd6q:b-6q4em6) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/reducesql/testdata/simple#L5)):*
> ```
> ----
> 
> reduce
> ```

datadriven has a facility to pass arguments into these, like
```
reduce contains=...
```
however I don't think it can handle strings with whitespace, so you'd probably have to change that to be able to use that here.
___
*[pkg/testutils/reduce/testdata/go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkP8w_9E7ty3a5EXpB8:-LkP8w_A5AcVcJMqMJ1r:b-215vrk) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/testdata/go#L1)):*
> ```
> contains
> ```

are these tests necessary given the SQL ones?

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39004)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @justinj, and @yuzefovich)

___
*[pkg/testutils/reduce/datadriven.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkP34_G10xALu-tdZtD:-LkPspgH3SkVYpaOZRiZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/datadriven.go#L30)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nite: verobes
</blockquote></details>

Done.
___
*[pkg/testutils/reduce/datadriven.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkP3BhFB32zVMw6iIXc:-LkPt0pe9RXuDu669kD2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/datadriven.go#L33)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nit: this comment could be a little more descriptive: "Sets the substring that must be contained by an error message for a test case to be marked as interesting"
</blockquote></details>

Done.
___
*[pkg/testutils/reduce/reduce.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkP6UzG4C_Ls-ZxrCQ8:-LkPtgmDCGOZX0WXsAb9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/reduce.go#L27)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Can you explain what the contracts are for these methods?
</blockquote></details>

Done.
___
*[pkg/testutils/reduce/reduce.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkPA_dN8_Wl-8JdOLmy:-LkPti6o-O608I3AWawf:bgoyfh5) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/reduce.go#L98)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

how long does this tend to take, ooc?
</blockquote></details>

most of the time between 5s and 60s
___
*[pkg/testutils/reduce/reduce.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkPAx9cB0tmUweXd8mi:-LkPtnfaDuFHghed00PL:b-5le9su) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/reduce.go#L101)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

it would be neat to also optionally see a list of the transformations that were applied to get to the reduced state
</blockquote></details>

yes. i'd also like to report times on each of these so i can rearrange the order of them and put the more useful ones first and slower ones later.
___
*[pkg/testutils/reduce/reduce.go, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkP6DqW4rKB5xvsVTbc:-LkPvOjy6K26AIlRSgeK:b-l75b1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/reduce.go#L109)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I know you linked to John Regehr's post, but I think the algorithm/terminology here could be explained in some more detail—what is a "unit", for example? And what does it mean for `i` to be exhausted?
</blockquote></details>

I added some words. Is it clearer?
___
*[pkg/testutils/reduce/reduce.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkP7P9j0ob3wr6A6R9Y:-LkPvQPTAD_dHMwdHu5g:b-a4fh3m) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/reduce.go#L112)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Given that there aren't `Pass`es that aren't `IntPass`es, I think it would be helpful to describe in more detail what it is that this specialization is, since the reader doesn't have anything else to contrast it to (or just remove the interface).
</blockquote></details>

Added some words about this. Better?
___
*[pkg/testutils/reduce/reducesql/reducesql.go, line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkP7o9rEYbcCx2N_ef3:-LkPvXxV7RxuwzssGf1a:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/reducesql/reducesql.go#L92)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

still needed?
</blockquote></details>

Done.
___
*[pkg/testutils/reduce/reducesql/reducesql.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkP7xjL3Xi_aXZLARck:-LkPvYj069OjolFm8ZD1:b-gjcekn) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/reducesql/reducesql.go#L101)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

is there any way you can hook into the existing `Walk` code? Probably not, I guess?
</blockquote></details>

Walk works on expressions, not statements, so I don't think it's what I needed.
___
*[pkg/testutils/reduce/reducesql/reducesql.go, line 240 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkP5UnL1q8h4EcVHj07:-LkPxejYDqdfh8GoJPFS:b-gjl7up) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/reducesql/reducesql.go#L240)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nice, I like this pattern of being able to use the same function to both detect and perform transformations :thumbsup:
</blockquote></details>

It started out as two funcs, but they were mostly copies of each other. Merging them into one is way better.
___
*[pkg/testutils/reduce/reducesql/reducesql.go, line 563 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkPBBUs5FIHtBc7lOtY:-LkPyalRBZVeAY6hFy7l:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/reducesql/reducesql.go#L563)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Maybe explain somewhere that we can safely mutate these since we re-parse every time?
</blockquote></details>

Done.
___
*[pkg/testutils/reduce/reducesql/testdata/simple, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkPBMTZ-4AjI6cvPd6p:-LkPzYUv0QXqmnSuuR03:bv9y8l6) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/reducesql/testdata/simple#L5)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

datadriven has a facility to pass arguments into these, like
```
reduce contains=...
```
however I don't think it can handle strings with whitespace, so you'd probably have to change that to be able to use that here.
</blockquote></details>

That's specifically why I had to do it this way. datadriven also supports things like `cmd arg=(val1, val2, val3)`. Keeping those semantics while also allowing single argument strings with spaces seemed like not worth the effort.
___
*[pkg/testutils/reduce/testdata/go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkP8w_9E7ty3a5EXpB8:-LkPzmSsCM5mnbL5OVnw:bcgniss) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/testdata/go#L1)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

are these tests necessary given the SQL ones?
</blockquote></details>

I think so, yes. These tests are a stdlib-only way of verifying this algorithm works. If we or someone else wants to take this code and move it somewhere else (like we did to the datadriven package, which is now its own repo), they can also move these tests without having to deal with sql-isms to make sure the reducer algorithm works.

**Review by justinj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39004)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @justinj, @mjibson, and @yuzefovich)

___
*[pkg/testutils/reduce/reduce.go, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkP6DqW4rKB5xvsVTbc:-LkQ-tm_82cKe3h1OKlG:bn1wz0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/reduce.go#L109)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I added some words. Is it clearer?
</blockquote></details>

:thumbsup:
___
*[pkg/testutils/reduce/reduce.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39004#-LkP7P9j0ob3wr6A6R9Y:-LkQ-xtICsjEiXuvi8t8:bn1wz0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/450d429d938df6d7ea753b0df42da89d9d2c991b/pkg/testutils/reduce/reduce.go#L112)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Added some words about this. Better?
</blockquote></details>

:thumbsup:

**Pull request merged**
