### PR TITLE
Allow implicit casting to int[], decimal[]

### LINKED ISSUE #41405: sql: cast string to int[] or decimal[] when appropriate
The following works in postgres, but not CockroachDB.

```
> create table arrtest (intarr int[], decarr decimal(2,1)[], strarr text[]);
CREATE TABLE

> INSERT INTO arrtest VALUES ('{1,2,3}','{3.1,1.4}', '{abc,f''a,"fa\"b",def}');
pq: value type string doesn't match type int[] of column "intarr"
```

Adding explicit casts makes it work.

```
> INSERT INTO arrtest VALUES ('{1,2,3}'::int[],'{3.1,1.4}'::decimal[], '{abc,f''a,"fa\"b",def}');
INSERT 1
```

### PR DESCRIPTION
**Pull request by apantel**
Fixes #41405

Release note (sql change): Cast string to int[] or decimal[] when appropriate

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
minor nit: typo in commit message for `strign`

other than very small comments, looks great! thanks

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42704#-:-LuJdUOy1Dmh4KgsJfIs:bc3ao8x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @apantel and @rafiss)

___
*[pkg/sql/sem/tree/constant_test.go, line 269 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42704#-LuJdYUb-LmCOqtY8377:-LuJdYUb-LmCOqtY8378:b-b32dum) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f732e63532de6720f248cddd4a60c8bd0ac9ccb/pkg/sql/sem/tree/constant_test.go#L269)):*
> ```Go
> 	types.Interval:    mustParseDInterval,
> 	types.Jsonb:       mustParseDJSON,
> 	types.IntArray: 	 mustParseDIntArray,
> ```

can a test also be added for DecimalArray?

**Review by apantel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42704)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/sem/tree/constant_test.go, line 269 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42704#-LuJdYUb-LmCOqtY8377:-LuJgXM_9t6gC9Z8C48E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f732e63532de6720f248cddd4a60c8bd0ac9ccb/pkg/sql/sem/tree/constant_test.go#L269)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can a test also be added for DecimalArray?
</blockquote></details>

Done.

**Review by apantel — COMMENTED** [review]
> Dismissed @rafiss from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42704)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
