### PR TITLE
 exec: add constrained ordered aggregator

### PR DESCRIPTION
**Pull request by asubiotto**
The ordered aggregator currently only performs n sumInt64s on the input
columns.

To be templated and extended with multiple aggregate functions.

Release note: None

Addresses #31527

Adding slicing and removing the overflow check from SumInt improved aggregation throughput by a nice amount:
```
BenchmarkSumInt/groupSize=1/numInputBatches=1-8         	 1000000	      1431 ns/op	5721.59 MB/s
BenchmarkSumInt/groupSize=1/numInputBatches=2-8         	 1000000	      2454 ns/op	6674.04 MB/s
BenchmarkSumInt/groupSize=1/numInputBatches=32-8        	   50000	     33438 ns/op	7839.70 MB/s
BenchmarkSumInt/groupSize=1/numInputBatches=64-8        	   20000	     64856 ns/op	8083.77 MB/s
BenchmarkSumInt/groupSize=2/numInputBatches=1-8         	 1000000	      1408 ns/op	5815.04 MB/s
BenchmarkSumInt/groupSize=2/numInputBatches=2-8         	 1000000	      2490 ns/op	6578.89 MB/s
BenchmarkSumInt/groupSize=2/numInputBatches=32-8        	   50000	     33507 ns/op	7823.40 MB/s
BenchmarkSumInt/groupSize=2/numInputBatches=64-8        	   20000	     66320 ns/op	7905.35 MB/s
BenchmarkSumInt/groupSize=512/numInputBatches=1-8       	 1000000	      1432 ns/op	5717.23 MB/s
BenchmarkSumInt/groupSize=512/numInputBatches=2-8       	 1000000	      2416 ns/op	6779.65 MB/s
BenchmarkSumInt/groupSize=512/numInputBatches=32-8      	   50000	     33267 ns/op	7879.86 MB/s
BenchmarkSumInt/groupSize=512/numInputBatches=64-8      	   20000	     64798 ns/op	8091.07 MB/s
BenchmarkSumInt/groupSize=1024/numInputBatches=1-8      	 1000000	      1455 ns/op	5627.84 MB/s
BenchmarkSumInt/groupSize=1024/numInputBatches=2-8      	 1000000	      2386 ns/op	6864.40 MB/s
BenchmarkSumInt/groupSize=1024/numInputBatches=32-8     	   50000	     32955 ns/op	7954.58 MB/s
BenchmarkSumInt/groupSize=1024/numInputBatches=64-8     	   20000	     67595 ns/op	7756.25 MB/s
```

### CODE REVIEW

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32064)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/sum_int64_agg.go, line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32064#-LQF-ptq3ozmToShbqgz:-LQF-ptq3ozmToShbqh-:b-yrumkl) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b0ab80aacb87ed8e186935b482e29bfcd0dc4ee/pkg/sql/exec/sum_int64_agg.go#L18)):*
> ```Go
> 
> type sumInt64Agg struct {
> 	input Operator
> ```

Unused

**Review by jordanlewis — CHANGES_REQUESTED** [review]
This looks good! What are the throughput numbers?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32064#-:-LQFyK9F6dtyS5O8bzxq:b-spcvwn)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/aggregator.go, line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32064#-LQFvXJm6xwvOBErIcRE:-LQFvXJm6xwvOBErIcRF:b-sqlg7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b0ab80aacb87ed8e186935b482e29bfcd0dc4ee/pkg/sql/exec/aggregator.go#L55)):*
> ```Go
> }
> 
> type orderedAggregator struct {
> ```

You should add a comment above this that explains what the orderedAggregator does. The algorithm is not clear without a description. You should include that this needs ordered distinct input to make sense, how it uses that ordered distinct input, and what it writes to the output and how.
___
*[pkg/sql/exec/aggregator.go, line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32064#-LQFwFeu2lGZ2_DmDMyq:-LQFwFeu2lGZ2_DmDMyr:bgwwdij) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b0ab80aacb87ed8e186935b482e29bfcd0dc4ee/pkg/sql/exec/aggregator.go#L152)):*
> ```Go
> 	// Copy the second part of the output batch into the first and resume from
> 	// there.
> 	if a.scratch.resumeIdx >= a.scratch.outputSize {
> ```

Do we always have to do this? An `if` statement at this level (outside the inner loop) is cheap - and if it means you can avoid one copy per col, it's a good thing.
___
*[pkg/sql/exec/aggregator_test.go, line 269 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32064#-LQFy0jcCaIyoGFqUm4Y:-LQFy0jcCaIyoGFqUm4Z:b-wj82x5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b0ab80aacb87ed8e186935b482e29bfcd0dc4ee/pkg/sql/exec/aggregator_test.go#L269)):*
> ```Go
> 				func(b *testing.B) {
> 					// Only count the int64 column.
> 					b.SetBytes(int64(8 * ColBatchSize * numInputBatches))
> ```

What are the benchmark results with the throughput included?
___
*[pkg/sql/exec/sum_int64_agg.go, line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32064#-LQF-ptq3ozmToShbqgz:-LQFyBZ_03zMf2hjFk2s:b3kre) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b0ab80aacb87ed8e186935b482e29bfcd0dc4ee/pkg/sql/exec/sum_int64_agg.go#L18)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Unused
</blockquote></details>

?

**Review by asubiotto — COMMENTED** [review]
Throughput numbers are in the benchmark results (they're just hidden, you have to scroll right)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32064#-:-LQFyp7T4GCn_eT2tKXi:bdmql2q)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/aggregator.go, line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32064#-LQFwFeu2lGZ2_DmDMyq:-LQFyui94zjNzZ1dt94M:b-j1y2p1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b0ab80aacb87ed8e186935b482e29bfcd0dc4ee/pkg/sql/exec/aggregator.go#L152)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Do we always have to do this? An `if` statement at this level (outside the inner loop) is cheap - and if it means you can avoid one copy per col, it's a good thing.
</blockquote></details>

I'm a bit confused, am I not doing what you're saying?
___
*[pkg/sql/exec/aggregator_test.go, line 269 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32064#-LQFy0jcCaIyoGFqUm4Y:-LQFz9IoAlcJwHX8jUjW:b-i47k10) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b0ab80aacb87ed8e186935b482e29bfcd0dc4ee/pkg/sql/exec/aggregator_test.go#L269)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

What are the benchmark results with the throughput included?
</blockquote></details>

In the first message.
___
*[pkg/sql/exec/sum_int64_agg.go, line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32064#-LQF-ptq3ozmToShbqgz:-LQFzMNz-Y2WIKgywOkP:bjyeq8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b0ab80aacb87ed8e186935b482e29bfcd0dc4ee/pkg/sql/exec/sum_int64_agg.go#L18)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

?
</blockquote></details>

Just a note to self that I should get rid of this because the agg funcs don't call `Next()`

**Review by jordanlewis — COMMENTED** [review]
Oh yeah, woops! Looks good

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32064#-:-LQG1weT9ZgOCjiPVrgQ:b2x2yl5)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by jordanlewis — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32064)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/aggregator.go, line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32064#-LQFwFeu2lGZ2_DmDMyq:-LQG221I913tZ-LIQ6CC:bhd94dt) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b0ab80aacb87ed8e186935b482e29bfcd0dc4ee/pkg/sql/exec/aggregator.go#L152)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm a bit confused, am I not doing what you're saying?
</blockquote></details>

Wow, no, you're totally doing what I'm saying...

I think I was thrown by the comment above this if, which sounds like you're doing it unconditionally. You should change that comment to say when it has to happen

**Review by jordanlewis — COMMENTED** [review]
:lgtm: once you add a better description of the overall operator flow

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32064#-:-LQG2F4X9svXvpZv-JeT:b-cyuyd8)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by asubiotto** [comment]
Added more comments and removed the need for a special carry variable in aggregate functions by modifying the interface contract. This will also make templating easier. PTAL.

**Review by jordanlewis — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32064#-:-LQK9Dvf9hGD6g_ISNlN:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by asubiotto** [comment]
batch crashed

bors r+

**Pull request merged**
