### PR TITLE
build: use `TESTS` to filter libroach tests to run.

### PR DESCRIPTION
**Pull request by mberhault**
Also added some help messages for `check-libroach` to make it easier to
find.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
Thanks! This looks good to me, but others will know better.

**Comment by benesch** [comment]
For consistency with `make test` I think it makes more sense for PKG to select the test binary and TESTS to select the internal gtest tests. Thoughts?

**Comment by mberhault** [comment]
We can fairly easily filter by test binary filename (which includes the directory name), but filtering by gtest name requires passing args to the test binaries themselves. This would still be rather polluted on the  output side.

We could use `PKG` for dir/filename filtering, but I'm not sure that's such a great match either. Honestly, as long as it's documented somewhere, I don't really care which we use.

**Review by benesch — APPROVED** [review]
Ok, let's just merge this as is!

**Pull request merged**
