### PR TITLE
sqlstats: lower default sqlstats in-memory fingerprint limits

### LINKED ISSUE #123074: sqlstats: adjust default cluster settings for in-memory fingerprint thresholds
Currently, the defaults values for the maximum number of fingerprints we track in-memory per node before flushing to disk is 100,000. We've determined this threshold is too high - a consequence of this is that for workloads that reach these limits, a single flush operation can take up to 10m+ to complete. This also allows us to collect a large number of fingerprints in one aggregation interval.

Cluster settings:
```
sql.metrics.max_mem_stmt_fingerprints
sql.metrics.max_mem_txn_fingerprints
```

We should lower this limit to something more reasonable, like 2500. Some initial teting with sysbench suggests that a flush operation with 2500 stmts and 2500 txns can take up to 2m, which is much more reasonable.

As a part of this change we can introduce 2 benchmarks for the flush operation:
1. Benchmark the flush operation with the max amount of fingerprints, where every fingerprint is a new write to the system table
2. Benchmark the flush operation with the max amount of fingerprints, where every fingerprint is an update (aggregation into) the system table.

This should give us a good idea of the range of the flush operation, since it's a mix of update and inserts ops.

Jira issue: CRDB-38188

Epic CRDB-37544

### PR DESCRIPTION
**Pull request by xinhaoz**
**sqlstats: bench flush operation**

This commit introduces a benchmark for the sql stats
flush operation. Specifically, it times how long the
a single flush operation takes when flushing the default
value for the max amount of in-memory fingerprints.

There are 2 sub benchmarks in the test to give us a rough
range (in ideal conditions) for the flush operation:

1. Flush time when all fingerprints are INSERTS
2. Flush time when all fingerpritns are UPDATES

Informs: https://github.com/cockroachdb/cockroach/issues/123074

**sqlstats: lower default sqlstats in-memory fingerprint limits**

The following cluster settings control how many stmt
and txn fingerprints we can store in-memory before
flushign to disk:
- sql.metrics.max_mem_stmt_fingerprints
- sql.metrics.max_mem_txn_fingerprints

**sqlstats: lower default sqlstats in-memory fingerprint limits** 

Prior to this change these values were set at 100,000.
In practice we've found this to be too high a number
for the flush operation to complete in a reasonable time.

This commit lowers these caps to be 5000 respectively.
This means a single flush operation can write up to
10,000 rows (stmts + txns). The following commit will
introduce benchmarks for the flush time to verify these
limits.

Benchmark results with GOMAXPROCS=10:
```
BenchmarkSqlStatsMaxFlushTime/single-application/writes=insert/10000-fingerprints-10    1     10835655666 ns/op
BenchmarkSqlStatsMaxFlushTime/single-application/writes=update/10000-fingerprints-10    1     32487051083 ns/op
```
Epic: none
Fixes: #123074

### CODE REVIEW

**Comment by xinhaoz** [comment]
```
BenchmarkSqlStatsFlushTime/singe-application/writes=insert/10000-fingerprints-10         	       1	10234145042 ns/op
    flush_test.go:1356: statement_statistics row count: 5003
    flush_test.go:1358: transaction_statistics row count: 5000
BenchmarkSqlStatsFlushTime/singe-application/writes=update/10000-fingerprints
BenchmarkSqlStatsFlushTime/singe-application/writes=update/10000-fingerprints-10         	       1	31146862209 ns/op
    flush_test.go:1356: statement_statistics row count: 5034
    flush_test.go:1358: transaction_statistics row count: 5005
```
This is showing ~10s and ~30s respectively.

**Review by dhartunian — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123246)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123246#-NwfgB4KA4uG7aExgQ9k):*
nit: spelling
___
*[`-- commits` line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123246#-NwfgI0M2hwVrYpkAwd9):*
Add release note with explanation of how this limits stats in SQL Activity.
___
*[`-- commits` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123246#-NwfgS_i-BINEajb7JYc):*
can you add a small explanation of why insert/update distinction covers the range of time this op can take?
___
*[`pkg/sql/sqlstats/cluster_settings.go` line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123246#-Nwfg_Oz2y9tbhYvADXw:-Nwfg_Oz2y9tbhYvADXx:bspmqza) ([raw file](https://github.com/cockroachdb/cockroach/blob/903ef109748d9e4c738578afeb35739041a0e799/pkg/sql/sqlstats/cluster_settings.go#L108)):*
> ```Go
> 	"sql.metrics.max_mem_reported_stmt_fingerprints",
> 	"the maximum number of reported statement fingerprints stored in memory",
> 	100000,
> ```

did you mean to include this change?
___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/testutils.go` line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123246#-Nwfgl0g6MNUPV2HYyfS:-Nwfgl0g6MNUPV2HYyfT:b5skyt5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d648530d44fa8d7fa3886c38aea0b40436ab1eb/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/testutils.go#L126)):*
> ```Go
> }
> 
> func FillObject(t testutils.TestFataler, val reflect.Value, data *randomData) {
> ```

why is this necessary?
___
*[`pkg/sql/sqlstats/persistedsqlstats/flush_test.go` line 1363 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123246#-NwfguE10ZMqosVvbKQZ:-NwfguE10ZMqosVvbKQ_:b-8pl5ym) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d648530d44fa8d7fa3886c38aea0b40436ab1eb/pkg/sql/sqlstats/persistedsqlstats/flush_test.go#L1363)):*
> ```Go
> 	// statement is an UPDATE.
> 	totalFingerprints := stmtFingerprintLimit + txnFingerprintLimit
> 	b.Run(fmt.Sprintf("singe-application/writes=insert/%d-fingerprints", totalFingerprints), func(b *testing.B) {
> ```

nit: "single"
___
*[`pkg/sql/sqlstats/persistedsqlstats/flush_test.go` line 1376 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123246#-Nwfh3WH4sSO5cS4JVTs:-Nwfh3WH4sSO5cS4JVTt:bhv8kpa) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d648530d44fa8d7fa3886c38aea0b40436ab1eb/pkg/sql/sqlstats/persistedsqlstats/flush_test.go#L1376)):*
> ```Go
> 		b.ResetTimer()
> 		require.True(b, sqlStats.MaybeFlush(ctx, s.AppStopper()))
> 	})
> ```

If we're only testing a single run (as opposed to looping over `b.N` like benchmarks are supposed to), then I don't think we can really use the benchmark output reliably since it won't be statistically significant.

Maybe this should just be a normal test that returns an elapsed time.

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123246)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123246#-NwfgB4KA4uG7aExgQ9k):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: spelling
</blockquote></details>

Done.
___
*[`-- commits` line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123246#-NwfgI0M2hwVrYpkAwd9):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Add release note with explanation of how this limits stats in SQL Activity.
</blockquote></details>

Done.
___
*[`-- commits` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123246#-NwfgS_i-BINEajb7JYc):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

can you add a small explanation of why insert/update distinction covers the range of time this op can take?
</blockquote></details>

Done.
___
*[`pkg/sql/sqlstats/cluster_settings.go` line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123246#-Nwfg_Oz2y9tbhYvADXw:-NwjIyMg55ZZd490yIuX:bp3aow6) ([raw file](https://github.com/cockroachdb/cockroach/blob/903ef109748d9e4c738578afeb35739041a0e799/pkg/sql/sqlstats/cluster_settings.go#L108)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

did you mean to include this change?
</blockquote></details>

Reverted.
___
*[`pkg/sql/sqlstats/persistedsqlstats/flush_test.go` line 1363 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123246#-NwfguE10ZMqosVvbKQZ:-NwjJmHH9c01VBmU2pFR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d648530d44fa8d7fa3886c38aea0b40436ab1eb/pkg/sql/sqlstats/persistedsqlstats/flush_test.go#L1363)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: "single"
</blockquote></details>

Done.
___
*[`pkg/sql/sqlstats/persistedsqlstats/flush_test.go` line 1376 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123246#-Nwfh3WH4sSO5cS4JVTs:-NwjJnWTEA1LQOYRNgE-:b-p6fx7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d648530d44fa8d7fa3886c38aea0b40436ab1eb/pkg/sql/sqlstats/persistedsqlstats/flush_test.go#L1376)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

If we're only testing a single run (as opposed to looping over `b.N` like benchmarks are supposed to), then I don't think we can really use the benchmark output reliably since it won't be statistically significant.

Maybe this should just be a normal test that returns an elapsed time.
</blockquote></details>

Changed both to be run b.N times, but the 2nd bench (with all updates) only ever runs once since it's such a long running operation. I believe the test will choose N dynamically based on how long the op takes. Thoughts? 
___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/testutils.go` line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123246#-Nwfgl0g6MNUPV2HYyfS:-NwjIfz2Dv60y62NklWt:b-5tvymo) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d648530d44fa8d7fa3886c38aea0b40436ab1eb/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/testutils.go#L126)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

why is this necessary?
</blockquote></details>

Forgot to revert this, was going to use it for some mocking initially. Reverted.

**Review by dhartunian — COMMENTED** [review]
You included the 3 commits from the other PR you have open, I assume those will get removed before merge.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123246#-:-NwjSdPD7Hb5MfIr_g_7:btknudd)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`-- commits` line 69 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/123246#-NwjQzgq3TAkxmbJGq13):*
Can you add the reasoning and benchmark output in the commit message that led to the decision. Having an audit trail that we can reference and compare to is helpful here.
___
*[`pkg/sql/sqlstats/persistedsqlstats/flush_test.go` line 1379 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/123246#-NwjR9iREF0B0YDNRV4E:-NwjR9iREF0B0YDNRV4F:bmmazyl) ([raw file](https://github.com/cockroachdb/cockroach/blob/db66c404708d860c49415871c601f0c6fc64794a/pkg/sql/sqlstats/persistedsqlstats/flush_test.go#L1379)):*
> ```Go
> 
> 	b.Run(fmt.Sprintf("single-application/writes=update/%d-fingerprints", totalFingerprints), func(b *testing.B) {
> 		b.ResetTimer()
> ```

is the `ResetTimer()` necessary at the start of the func? I don't quite understand. I would assume this function starts with a fresh timer, no?

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123246)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @nkodali)

___
*[`-- commits` line 69 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/123246#-NwjQzgq3TAkxmbJGq13):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Can you add the reasoning and benchmark output in the commit message that led to the decision. Having an audit trail that we can reference and compare to is helpful here.
</blockquote></details>

Done.
___
*[`pkg/sql/sqlstats/persistedsqlstats/flush_test.go` line 1379 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/123246#-NwjR9iREF0B0YDNRV4E:-NwoUXIeBS7EgT4h4RlJ:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/db66c404708d860c49415871c601f0c6fc64794a/pkg/sql/sqlstats/persistedsqlstats/flush_test.go#L1379)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

is the `ResetTimer()` necessary at the start of the func? I don't quite understand. I would assume this function starts with a fresh timer, no?
</blockquote></details>

Removed.

**Review by dhartunian — APPROVED** [review]
:lgtm: just a stray diff in the cluster setting. thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123246#-:-Nwpamch6_MrlwJUBjmt:b-ed6z7e)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nkodali and @xinhaoz)

___
*[`pkg/sql/sqlstats/cluster_settings.go` line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123246#-Nwfg_Oz2y9tbhYvADXw:-NwpaTUX-4M3W8oqsJc9:b8pb6gu) ([raw file](https://github.com/cockroachdb/cockroach/blob/903ef109748d9e4c738578afeb35739041a0e799/pkg/sql/sqlstats/cluster_settings.go#L108)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Reverted.
</blockquote></details>

Can you check this again, it looks like you removed a zero.

**Pull request merged**
