### PR TITLE
tracing: enable always-on tracing by default

### PR DESCRIPTION
**Pull request by irfansharif**
This is follow-up work from #58712, where we measured the overhead for
always-on tracing and found it to be minimal/acceptable. Lets switch
this on by default to shake the implications of doing so. We can
reasonably expect two kinds of fallout:

1. Unexpected blow up in memory usage due to resource leakage (which is
a can be problem now that we're always maintaining open spans in an
internal registry, see #58721)

2. Performance degradation due to tracing overhead per-request
(something #58712) was spot checking for.

For 1 we'll introduce a future test in a separate PR. For 2, we'll
monitor roachperf over the next few weeks.

---

Also moved some of the documentation for the cluster setting into a
comment form above. Looking at what's rendered in our other cluster
settings (`SHOW ALL CLUSTER SETTINGS`), we default to a very pity,
unwrapped description.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
Wow, so much red in CI! Curious what this is all about.

**Comment by irfansharif** [comment]
Probably the span leak we found in https://github.com/cockroachdb/cockroach/pull/58902. I'm not sure what to do about it yet.

**Comment by tbg** [comment]
How can it be that? We're not checking for span leaks in this PR.

**Comment by irfansharif** [comment]
Was a stab in the dark, but I was thinking it could be due to some memory blow up. I'll take a closer look in the morning.

**Comment by irfansharif** [comment]
Looks like it was something else, but I'm not really sure what to do about it. With always on tracing, even spans with "nothing in them" generaterecordings. Cause it's always on, we'll at least generate the portion of the trace with the operation name.

```
0.000ms      0.000ms    === operation:table reader
```

With the legacy tracing mode, cause we weren't explicitly recording, we used to return `nil` traces when requested:

https://github.com/cockroachdb/cockroach/blob/ff1442b276a914e30b324b16e973b26c53159f6d/pkg/util/tracing/crdbspan.go#L136-L143


Now that this is not nil, we'll attach it to the our processor's `trailingMeta` here:

https://github.com/cockroachdb/cockroach/blob/ff1442b276a914e30b324b16e973b26c53159f6d/pkg/sql/execinfra/processorsbase.go#L710-L712

Most of the failing tests aren't expecting this:

https://github.com/cockroachdb/cockroach/blob/fb03099982a2387919cffe328db2f6ca3eb3212f/pkg/sql/flowinfra/server_test.go#L109-L113

I'm not sure what to do here. At first I figured if it's just tests, we could ignore the metas with trace data. Using something like:

```go
// ignoreTraceData takes a slice of metadata and returns the entries
// excluding the ones with trace data.
func ignoreTraceData(metas []execinfrapb.ProducerMetadata) []execinfrapb.ProducerMetadata {
	res := make([]execinfrapb.ProducerMetadata, 0)
	for _, m := range metas {
		if m.TraceData == nil {
			res = append(res, m)
		}
	}
	return res
}
```

But I'm not sure that's right, and also it doesn't help `TestCSVImportCanBeResumed`, which fails legitimately (the import process doesn't actually resume with always-on tracing). I think it's because we use `trailingMeta` in our control flow?

https://github.com/cockroachdb/cockroach/blob/fb03099982a2387919cffe328db2f6ca3eb3212f/pkg/sql/execinfra/processorsbase.go#L627-L632

I'm don't know what the right patch here would be. Should we not include the trace data in trailing meta if there are no remote+children spans (aka behave like earlier)? Should we change our handling of `trailingMeta` to possibly account for these "spans with nothing in them"? Perhaps @asubiotto or @yuzefovich have ideas; I'm lost.

**Comment by yuzefovich** [comment]
I don't see that we need to do anything special at this moment (other than silencing these TraceData meta if it is empty as you suggested, in tests). `TestCSVImportCanBeResumed` fails legitimately because there is a bug in the implementation of the import processor, try this diff:
```
diff --git a/pkg/ccl/importccl/import_processor.go b/pkg/ccl/importccl/import_processor.go
index 9da93ace86..9fdb3ed043 100644
--- a/pkg/ccl/importccl/import_processor.go
+++ b/pkg/ccl/importccl/import_processor.go
@@ -135,16 +135,15 @@ func (idp *readImportDataProcessor) Next() (rowenc.EncDatumRow, *execinfrapb.Pro
        // Once the import is done, send back to the controller the serialized
        // summary of the import operation. For more info see roachpb.BulkOpSummary.
        countsBytes, err := protoutil.Marshal(idp.summary)
+       idp.MoveToDraining(err)
        if err != nil {
-               idp.MoveToDraining(err)
                return nil, idp.DrainHelper()
        }
 
-       idp.MoveToDraining(nil /* err */)
        return rowenc.EncDatumRow{
                rowenc.DatumToEncDatum(types.Bytes, tree.NewDBytes(tree.DBytes(countsBytes))),
                rowenc.DatumToEncDatum(types.Bytes, tree.NewDBytes(tree.DBytes([]byte{}))),
-       }, idp.DrainHelper()
+       }, nil
 }
```
The contract of `RowSource.Next` method is that only one of `row` and `meta` is non-nil, and it was broken.

**Comment by irfansharif** [comment]
Thanks for the tip, sent it out #59115. @tbg/@knz, mind rubber stamping the second commit here?

**Review by tbg — APPROVED** [review]

**Comment by irfansharif** [comment]
> curl: (22) The requested URL returned error: 504 GATEWAY_TIMEOUT

bors r+

**Pull request merged**
