### PR TITLE
sqlproxyccl: rework sqlproxy connection throttler

### LINKED ISSUE #71400: sqlproxyccl: rework throttle to track ip,tenant pairs
This is tracking the work for SEC-640. The throttle logic in the sqlproxy will be switched back to exponential backoff. In order to avoid the usability issues with the original throttle implementation, the throttle will track state per (ip, tenant).

### PR DESCRIPTION
**Pull request by jeffswenson**
This change switches the sqlproxy connection throttling logic back to
exponential backoff. The tokenbucket approach was introduced by
PR #69041. There are a few behavior differences between this and the
original exponential backoff implementation.

1. The throttling logic is maintained per (ip, tenant) instead of per
   (ip). Some platform as a service provides share a single outbound ip
   address between multiple clients. These users would occasionaly see
   throttling caused by a second user sharing their IP.
2. The throttling logic was triggered before there was an authentication
   failure. It takes ~100ms-1000ms to authenticate with the tenant
   process.  Any requests that arrived after the first request, but
   before it was processed, would trigger the throttle. Now, we only
   trigger the throttle in response to an explict authorization error.

Release note: None

### CODE REVIEW

**Review by kpatron-cockroachlabs — APPROVED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71412)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @darinpp)

**Comment by andy-kimball** [comment]
@darinpp, can you take a look as well?

**Review by darinpp — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71412)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @JeffSwenson and @kpatron-cockroachlabs)

___
*[pkg/ccl/sqlproxyccl/authentication.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71412#-Mlm2oz43GuJybiNKrP4:-Mlm2oz43GuJybiNKrP5:b-5yjfad) ([raw file](https://github.com/cockroachdb/cockroach/blob/55ba27e7020cd9565891d81195e8d720abd5dae4/pkg/ccl/sqlproxyccl/authentication.go#L35)):*
> ```Go
> 			return newErrorf(codeBackendReadFailed, "unable to receive message from backend: %v", err)
> 		}
> ```

I don't think we should be reporting throttle errors as such. This gives an attacker information that we don't need to give back. Reporting authentication error when there is one but also when they are throttled prevents them from knowing that password they tried is incorrect. This also eliminates the need to have `throttleHook` in `authenticate` so this code is not needed. 
___
*[pkg/ccl/sqlproxyccl/proxy_handler.go, line 266 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71412#-MlmCSXo0tQt8yUqhSca:-MlmCSXo0tQt8yUqhScb:byuucop) ([raw file](https://github.com/cockroachdb/cockroach/blob/55ba27e7020cd9565891d81195e8d720abd5dae4/pkg/ccl/sqlproxyccl/proxy_handler.go#L266)):*
> ```Go
> 	throttleTime, err := handler.throttleService.LoginCheck(throttleTags)
> 	if err != nil {
> 		log.Errorf(ctx, "throttler refused connection: %v", err.Error())
> ```

This should be authentication error. Reporting that they are throttled let's an attacked know that the password may be correct and to try later. Making all throttler errors looks like authentication errors, hides the actual length of the throttle period and prevents the attackers to get reliable feedback on incorrect passwords. 
___
*[pkg/ccl/sqlproxyccl/proxy_handler.go, line 402 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71412#-MlmB5k590q4qZiPwSrv:-MlmB5k590q4qZiPwSrw:b-m3qzty) ([raw file](https://github.com/cockroachdb/cockroach/blob/55ba27e7020cd9565891d81195e8d720abd5dae4/pkg/ccl/sqlproxyccl/proxy_handler.go#L402)):*
> ```Go
> 
> 	// Perform user authentication.
> 	if err := authenticate(conn, crdbConn, func(status throttler.AttemptStatus) *pgproto3.ErrorResponse {
> ```

If all errors are authenticate errors then we don't need this hook. 
___
*[pkg/ccl/sqlproxyccl/throttler/local.go, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71412#-Mlm5yNv64JNgBj7UQPy:-Mlm5yNv64JNgBj7UQPz:b-flnsvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/55ba27e7020cd9565891d81195e8d720abd5dae4/pkg/ccl/sqlproxyccl/throttler/local.go#L61)):*
> ```Go
> 		maxCacheSize: 1e6, /* 1 million */
> 		baseDelay:    time.Second,
> 		maxDelay:     time.Hour,
> ```

I don't think one hours works. If I run `workload init tpcc` for example with 36 connections but I make a mistake in the password. That will activate the throttler and it will make me wait an hour. We should probably have more like 10,15 or 30 seconds. Another issue with one hour (or any long period in general) is if the connections don't get spread equally across sqlproxies. Imagine that 16 connections get spread over 3 proxies as 4,5,7. So one proxy will block for 16 sec while another will block for 2+min. So if I try again my workload in 20 sec, I will get 1/3 of my connections fine and 2/3 throttled. There isn't much we can do about it now but that is one more reason why we shouldn't have a very high max delay as this can lead to bad experience due to a small mistake.
___
*[pkg/ccl/sqlproxyccl/throttler/local.go, line 103 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71412#-Mlm8pHV7I31DHrbA3om:-Mlm8pHV7I31DHrbA3on:b-3qlqeb) ([raw file](https://github.com/cockroachdb/cockroach/blob/55ba27e7020cd9565891d81195e8d720abd5dae4/pkg/ccl/sqlproxyccl/throttler/local.go#L103)):*
> ```Go
> 
> func (s *localService) ReportAttempt(
> 	connection ConnectionTags, throttleTime time.Time, status AttemptStatus,
> ```

If the only two status choices are `OK` and `Credentials` it may be simpler to not have the status and instead have `ReportSuccess` and `ReportFailure` methods. 
___
*[pkg/ccl/sqlproxyccl/throttler/throttle.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71412#-Mlm9Pk-AhBDExlGLydP:-Mlm9Pk-AhBDExlGLydQ:b-9bad9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/55ba27e7020cd9565891d81195e8d720abd5dae4/pkg/ccl/sqlproxyccl/throttler/throttle.go#L35)):*
> ```Go
> func (l *throttle) triggerThrottle(now time.Time, maxBackoff time.Duration) {
> 	l.nextTime = now.Add(l.nextBackoff)
> 	l.nextBackoff *= 2
> ```

Do we ever reset that to `initialBackoff`? If I run `workload init tpcc` with say 48 connections and get locked for one hour and then in one hour I try `cockroach sql` making a mistake in my password - am I going to be locked for one more hour? My preference would be to keep it as is (not reset it) but have something like 10 sec maximum backoff.

**Review by jeffswenson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71412)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @darinpp and @kpatron-cockroachlabs)

___
*[pkg/ccl/sqlproxyccl/authentication.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71412#-Mlm2oz43GuJybiNKrP4:-MloV-w6AZorZj13qJen:b3c335y) ([raw file](https://github.com/cockroachdb/cockroach/blob/55ba27e7020cd9565891d81195e8d720abd5dae4/pkg/ccl/sqlproxyccl/authentication.go#L35)):*
<details><summary><i>Previously, darinpp wrote…</i></summary><blockquote>

I don't think we should be reporting throttle errors as such. This gives an attacker information that we don't need to give back. Reporting authentication error when there is one but also when they are throttled prevents them from knowing that password they tried is incorrect. This also eliminates the need to have `throttleHook` in `authenticate` so this code is not needed. 
</blockquote></details>

The throttle hook is here to prevent leaking authentication state. authenticate does some frame level proxying back to the client. If we didn't check the throttle here, it would forward an AuthenticationOK or ErrorResponse to the client.
___
*[pkg/ccl/sqlproxyccl/proxy_handler.go, line 266 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71412#-MlmCSXo0tQt8yUqhSca:-MloXRlJ7KmBGrwgt0Pm:bcxp5wo) ([raw file](https://github.com/cockroachdb/cockroach/blob/55ba27e7020cd9565891d81195e8d720abd5dae4/pkg/ccl/sqlproxyccl/proxy_handler.go#L266)):*
> error. Reporting that they are throttled let's an attacked know that the password may be correct and to try later. Making all th

This is not a behavior change. It is the same throttle error we returned in previous iterations of the throttle.

I think it would be a bad user experience to report these as authentication errors. If a user misconfigures their password, then fixes it, we should show an error message indicating we didn't actually check their password. 

Even if we returned an authentication error here, it would still be obvious to an attacker that we didn't actually check the credentials. The sql server responds with a AuthenticationCleartextPassword message prompting the client to send its password. Throttling before we try to dial the backend means we would send an authentication error before the client has sent us its credentials.
___
*[pkg/ccl/sqlproxyccl/proxy_handler.go, line 402 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71412#-MlmB5k590q4qZiPwSrv:-MloY_ie11wGig7jo-0D:b-jvavc4) ([raw file](https://github.com/cockroachdb/cockroach/blob/55ba27e7020cd9565891d81195e8d720abd5dae4/pkg/ccl/sqlproxyccl/proxy_handler.go#L402)):*
<details><summary><i>Previously, darinpp wrote…</i></summary><blockquote>

If all errors are authenticate errors then we don't need this hook. 
</blockquote></details>

The hook would still be necessary to consult throttle state and suppress a potential AuthenticationOK response from the sql server.
___
*[pkg/ccl/sqlproxyccl/throttler/local.go, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71412#-Mlm5yNv64JNgBj7UQPy:-MloYkbS1UYPWPFe-HHk:b-isac0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/55ba27e7020cd9565891d81195e8d720abd5dae4/pkg/ccl/sqlproxyccl/throttler/local.go#L61)):*
> suppress
The exponential backoff doesn't trigger if the request was throttled. Only attempts let past the throttle trigger an exponential backoff. So the total time period of authentication errors is going to be at most double the time your script was retrying with a bad password.
___
*[pkg/ccl/sqlproxyccl/throttler/local.go, line 103 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71412#-Mlm8pHV7I31DHrbA3om:-Mlob_zm9vOTpMTeJL0l:bp78i79) ([raw file](https://github.com/cockroachdb/cockroach/blob/55ba27e7020cd9565891d81195e8d720abd5dae4/pkg/ccl/sqlproxyccl/throttler/local.go#L103)):*
<details><summary><i>Previously, darinpp wrote…</i></summary><blockquote>

If the only two status choices are `OK` and `Credentials` it may be simpler to not have the status and instead have `ReportSuccess` and `ReportFailure` methods. 
</blockquote></details>

I tried splitting them. They share all but one line of code and having a function handle both status allows us to pass a single throttle hook function to authenticate.
___
*[pkg/ccl/sqlproxyccl/throttler/throttle.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71412#-Mlm9Pk-AhBDExlGLydP:-MloZlIrD9Lk72nngzjk:b-8qlz2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/55ba27e7020cd9565891d81195e8d720abd5dae4/pkg/ccl/sqlproxyccl/throttler/throttle.go#L35)):*
<details><summary><i>Previously, darinpp wrote…</i></summary><blockquote>

Do we ever reset that to `initialBackoff`? If I run `workload init tpcc` with say 48 connections and get locked for one hour and then in one hour I try `cockroach sql` making a mistake in my password - am I going to be locked for one more hour? My preference would be to keep it as is (not reset it) but have something like 10 sec maximum backoff.
</blockquote></details>

I chose a 1 hour backoff because that is the value used by the original throttle logic. In general you won't get locked out for an hour unless you leave the script retrying for at least 30 minutes.

**Review by darinpp — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71412)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @JeffSwenson and @kpatron-cockroachlabs)

___
*[pkg/ccl/sqlproxyccl/authentication.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71412#-Mlm2oz43GuJybiNKrP4:-Mlp9TKJ-wUEEyPv-brw:bktgulv) ([raw file](https://github.com/cockroachdb/cockroach/blob/55ba27e7020cd9565891d81195e8d720abd5dae4/pkg/ccl/sqlproxyccl/authentication.go#L35)):*
<details><summary><i>Previously, JeffSwenson (Jeff Swenson) wrote…</i></summary><blockquote>

The throttle hook is here to prevent leaking authentication state. authenticate does some frame level proxying back to the client. If we didn't check the throttle here, it would forward an AuthenticationOK or ErrorResponse to the client.
</blockquote></details>

OK. Sounds good. Can you still merge this switch into the on below by moving the `fe.Send(backendMsg)` into the switch?
___
*[pkg/ccl/sqlproxyccl/proxy_handler.go, line 266 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71412#-MlmCSXo0tQt8yUqhSca:-MlpA6Nn9yYfC2I2jdfq:bdnes1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/55ba27e7020cd9565891d81195e8d720abd5dae4/pkg/ccl/sqlproxyccl/proxy_handler.go#L266)):*
<details><summary><i>Previously, JeffSwenson (Jeff Swenson) wrote…</i></summary><blockquote>

> error. Reporting that they are throttled let's an attacked know that the password may be correct and to try later. Making all th

This is not a behavior change. It is the same throttle error we returned in previous iterations of the throttle.

I think it would be a bad user experience to report these as authentication errors. If a user misconfigures their password, then fixes it, we should show an error message indicating we didn't actually check their password. 

Even if we returned an authentication error here, it would still be obvious to an attacker that we didn't actually check the credentials. The sql server responds with a AuthenticationCleartextPassword message prompting the client to send its password. Throttling before we try to dial the backend means we would send an authentication error before the client has sent us its credentials.
</blockquote></details>

Sounds good. 
___
*[pkg/ccl/sqlproxyccl/proxy_handler.go, line 402 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71412#-MlmB5k590q4qZiPwSrv:-MlpAvUX92H28HafjlLi:b32w0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/55ba27e7020cd9565891d81195e8d720abd5dae4/pkg/ccl/sqlproxyccl/proxy_handler.go#L402)):*
<details><summary><i>Previously, JeffSwenson (Jeff Swenson) wrote…</i></summary><blockquote>

The hook would still be necessary to consult throttle state and suppress a potential AuthenticationOK response from the sql server.
</blockquote></details>

OK
___
*[pkg/ccl/sqlproxyccl/throttler/local.go, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71412#-Mlm5yNv64JNgBj7UQPy:-MlpB3SbBVRiQRjmKRe4:bg8bnxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/55ba27e7020cd9565891d81195e8d720abd5dae4/pkg/ccl/sqlproxyccl/throttler/local.go#L61)):*
<details><summary><i>Previously, JeffSwenson (Jeff Swenson) wrote…</i></summary><blockquote>

> suppress
The exponential backoff doesn't trigger if the request was throttled. Only attempts let past the throttle trigger an exponential backoff. So the total time period of authentication errors is going to be at most double the time your script was retrying with a bad password.
</blockquote></details>

I see. So a quick burst of connection requests with invalid passwords won't cause a problem but a persistent stream of invalid password connections over time will push the backoff time up. 
___
*[pkg/ccl/sqlproxyccl/throttler/throttle.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71412#-Mlm9Pk-AhBDExlGLydP:-MlpCOfq7hgMcFVCrNBb:b-v2n8p6) ([raw file](https://github.com/cockroachdb/cockroach/blob/55ba27e7020cd9565891d81195e8d720abd5dae4/pkg/ccl/sqlproxyccl/throttler/throttle.go#L35)):*
<details><summary><i>Previously, JeffSwenson (Jeff Swenson) wrote…</i></summary><blockquote>

I chose a 1 hour backoff because that is the value used by the original throttle logic. In general you won't get locked out for an hour unless you leave the script retrying for at least 30 minutes. 
</blockquote></details>

I see. It may be helpful to add a line to the log when the backoff gets to the one hour mark for a given tenant/IP. It should be very rare but may be a good signal for security.

**Review by jeffswenson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71412)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @darinpp, @JeffSwenson, and @kpatron-cockroachlabs)

___
*[pkg/ccl/sqlproxyccl/authentication.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71412#-Mlm2oz43GuJybiNKrP4:-MlqGAuW4gcyhjtupANo:b-h901uh) ([raw file](https://github.com/cockroachdb/cockroach/blob/55ba27e7020cd9565891d81195e8d720abd5dae4/pkg/ccl/sqlproxyccl/authentication.go#L35)):*
<details><summary><i>Previously, darinpp wrote…</i></summary><blockquote>

OK. Sounds good. Can you still merge this switch into the on below by moving the `fe.Send(backendMsg)` into the switch?
</blockquote></details>

Done. PTAL the refactor was non-trivial. I made one small behavior change. If there is an unexpected message type during authentication, we used to forward the message, then immediately close the connection. Now we close the connection without forwarding the unexpected message.
___
*[pkg/ccl/sqlproxyccl/throttler/throttle.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71412#-Mlm9Pk-AhBDExlGLydP:-MlqGtC16R0CHxZLpWnu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/55ba27e7020cd9565891d81195e8d720abd5dae4/pkg/ccl/sqlproxyccl/throttler/throttle.go#L35)):*
<details><summary><i>Previously, darinpp wrote…</i></summary><blockquote>

I see. It may be helpful to add a line to the log when the backoff gets to the one hour mark for a given tenant/IP. It should be very rare but may be a good signal for security.
</blockquote></details>

Done.

**Review by darinpp — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71412)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @darinpp, @JeffSwenson, and @kpatron-cockroachlabs)

**Pull request merged**
