### PR TITLE
util, server: fix memory detection with non-root cgroups

### PR DESCRIPTION
**Pull request by darinpp**
The cgroup information is constructed by looking at `/proc/self/cgroup`,
matching with the mount point in `/proc/self/mountinfo`
and then inpsecting the `memory.stat` file. The matching between the
cgroup and the mount point was working only in case that the mount and
the cgroup are exact match relative to cgroup NS. This is however
inadequate as while true for the docker case, it isn't true in the general
case. In this example determining the cgroup memory limit isn't possible:
```
cgcreate -t $USER:$USER -a $USER:$USER -g memory:crdb_test
echo 3999997952 > /sys/fs/cgroup/memory/crdb_test/memory.limit_in_bytes
cgexec -g memory:crdb_test ./cockroach start-single-nod
```
To address this, this patch instead constructs the expected
relative path of the cgroup's memory info by starting with the
mount path and then adding the cgroup.

Release note: None

### CODE REVIEW

**Review by ajwerner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56840)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @darinpp, @itsbilal, and @knz)

___
*[pkg/util/cgroups/cgroups.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56840#-MMOt3G96B-40XksgYCr:-MMOt3G96B-40XksgYCs:b-3jeax6) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfaca632df010399f53a677b664fd09d18d49140/pkg/util/cgroups/cgroups.go#L289)):*
> ```Go
> }
> 
> // Reads /proc/[pid]/mountinfo for cgoup or cgroup2 mount which defines the used version.
> ```

Is there a case in v1 cgroups where the memory and cpu cgroups can be mounted in totally different trees? Is this going to throw of the work bilal just did? the v1 cgroup APIs are too fiddly. I get this change but I wonder if we’d be better served by saying which cgroup controller we’re looking for the mount point for. In v1 iiuc it’s just convention that the different controllers get mounted at the same root directory. 
___
*[pkg/util/cgroups/cgroups.go, line 323 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56840#-MMOu5UU7RAqiVquW2Fm:-MMOu5UV93QjjVP2eZhK:b-4b3zv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfaca632df010399f53a677b664fd09d18d49140/pkg/util/cgroups/cgroups.go#L323)):*
> ```Go
> 			// cockroach.log -> server/config.go:433 ⋮ system total memory: ‹63 GiB›
> 			memNSRelativePath := string(fields[3])
> 			if !strings.Contains(memNSRelativePath, "..") {
> ```

When is this true? Can you add tests for it? 
___
*[pkg/util/cgroups/cgroups.go, line 324 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56840#-MMOsGuv81aD7SWhLXrY:-MMOsGuv81aD7SWhLXrZ:bdjqzes) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfaca632df010399f53a677b664fd09d18d49140/pkg/util/cgroups/cgroups.go#L324)):*
> ```Go
> 			memNSRelativePath := string(fields[3])
> 			if !strings.Contains(memNSRelativePath, "..") {
> 				if relPath, err := filepath.Rel(memNSRelativePath, cRoot); err == nil {
> ```

I imagine the linter isn’t happy about your throwing away this error.

**Review by itsbilal — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56840)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @darinpp, and @knz)

___
*[pkg/util/cgroups/cgroups.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56840#-MMOt3G96B-40XksgYCr:-MMS05kN4MKasSeE7b7E:b7s1z3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfaca632df010399f53a677b664fd09d18d49140/pkg/util/cgroups/cgroups.go#L289)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Is there a case in v1 cgroups where the memory and cpu cgroups can be mounted in totally different trees? Is this going to throw of the work bilal just did? the v1 cgroup APIs are too fiddly. I get this change but I wonder if we’d be better served by saying which cgroup controller we’re looking for the mount point for. In v1 iiuc it’s just convention that the different controllers get mounted at the same root directory. 
</blockquote></details>

I'm not sure if I understand what you're referring to - this does take a `controller` arg that it then tries to match. The `mountinfopath` will be the same in both cases, but the cgroup controller mount points could be completely different based on the controller specified, yeah.
___
*[pkg/util/cgroups/cgroups.go, line 313 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56840#-MMS20x16dGY3gjJn8mb:-MMS20x2BEJGXo3MF9aa:b-s8i0iu) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfaca632df010399f53a677b664fd09d18d49140/pkg/util/cgroups/cgroups.go#L313)):*
> ```Go
> 				return mountPoint, ver, nil
> 			}
> 			// It is possible that the memory controller mount and the cgroup path are not the same (both are relative to the NS root).
> ```

s/memory controller/controller/ and similar changes below.
___
*[pkg/util/cgroups/cgroups_test.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56840#-MMS3hwi5WSNP_21FmwT:-MMS3hwi5WSNP_21FmwU:b-6qn6vb) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfaca632df010399f53a677b664fd09d18d49140/pkg/util/cgroups/cgroups_test.go#L74)):*
> ```Go
> 				"/proc/self/cgroup":                 v1CgroupWithMemoryControllerNS,
> 				"/proc/self/mountinfo":              v1MountsWithMemControllerNS,
> 				"/sys/fs/cgroup/memory/cgroup_test/memory.stat": v1MemoryStat,
> ```

Worthwhile adding a similar test for the cpu,cpuacct controllers.

**Review by darinpp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56840)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @itsbilal, and @knz)

___
*[pkg/util/cgroups/cgroups.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56840#-MMOt3G96B-40XksgYCr:-MMTLAPg0EtWUeAsk4dA:bmlzfkc) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfaca632df010399f53a677b664fd09d18d49140/pkg/util/cgroups/cgroups.go#L289)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I'm not sure if I understand what you're referring to - this does take a `controller` arg that it then tries to match. The `mountinfopath` will be the same in both cases, but the cgroup controller mount points could be completely different based on the controller specified, yeah.
</blockquote></details>

I renamed the variable as this code now is controller agnostic and works for both cpu, memory etc. It doesn't matter which controller is mounted where. This simply looks at the controller that is passed in relation to the cgroup root. 
___
*[pkg/util/cgroups/cgroups.go, line 313 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56840#-MMS20x16dGY3gjJn8mb:-MMTM0D0DvjD3sPty9nq:b-n9tkhd) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfaca632df010399f53a677b664fd09d18d49140/pkg/util/cgroups/cgroups.go#L313)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

s/memory controller/controller/ and similar changes below.
</blockquote></details>

changed
___
*[pkg/util/cgroups/cgroups.go, line 323 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56840#-MMOu5UU7RAqiVquW2Fm:-MMTM1mM1q4ImGMBHdMN:b-oo3m4g) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfaca632df010399f53a677b664fd09d18d49140/pkg/util/cgroups/cgroups.go#L323)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

When is this true? Can you add tests for it? 
</blockquote></details>

I added few tests. The mount point changes as the namespace change. So a mount done outside of the namespace will have `..`. In this case it isn't possible to construct the path but is possible to mount within the namespace as I showed in the added test.
___
*[pkg/util/cgroups/cgroups.go, line 324 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56840#-MMOsGuv81aD7SWhLXrY:-MMTN1fC6qBrHm-7ZyRZ:b2r45ul) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfaca632df010399f53a677b664fd09d18d49140/pkg/util/cgroups/cgroups.go#L324)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I imagine the linter isn’t happy about your throwing away this error. 
</blockquote></details>

I didn't see it complaining. Will check and fix.
___
*[pkg/util/cgroups/cgroups_test.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56840#-MMS3hwi5WSNP_21FmwT:-MMTN719BRLYxkrdAQMk:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfaca632df010399f53a677b664fd09d18d49140/pkg/util/cgroups/cgroups_test.go#L74)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Worthwhile adding a similar test for the cpu,cpuacct controllers.
</blockquote></details>

Done.

**Review by itsbilal — APPROVED** [review]
:lgtm: good work!

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56840#-:-MMWAlGc7NNgfxOJMpBS:bc789to)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @knz)

**Review by ajwerner — APPROVED** [review]
Just the one error handling thing and I can be convinced to not care. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56840#-:-MMXRKWE0Yu2F1K_3BXX:b-w28782)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @darinpp, and @knz)

___
*[pkg/util/cgroups/cgroups.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56840#-MMOt3G96B-40XksgYCr:-MMXQcfz5guEvn4iJ12C:b-qq1n17) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfaca632df010399f53a677b664fd09d18d49140/pkg/util/cgroups/cgroups.go#L289)):*
<details><summary><i>Previously, darinpp wrote…</i></summary><blockquote>

I renamed the variable as this code now is controller agnostic and works for both cpu, memory etc. It doesn't matter which controller is mounted where. This simply looks at the controller that is passed in relation to the cgroup root. 
</blockquote></details>

:sweat: 
___
*[pkg/util/cgroups/cgroups.go, line 324 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56840#-MMOsGuv81aD7SWhLXrY:-MMXQjuT7tTyTVAFb58K:b-b8q60y) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfaca632df010399f53a677b664fd09d18d49140/pkg/util/cgroups/cgroups.go#L324)):*
<details><summary><i>Previously, darinpp wrote…</i></summary><blockquote>

I didn't see it complaining. Will check and fix.
</blockquote></details>

What's the deal if this fails? Is it possible we're going to find another entry for the desired controller or should we return an error?

**Pull request merged**
