### PR TITLE
sql: fix CREATE AS [SHOW CREATE FUNCTION] job failure

### LINKED ISSUE #106268: sql: CREATE AS [SHOW CREATE FUNCTION] job fails
Running 
```
CREATE FUNCTION fn(i int) RETURNS INT AS 'SELECT i' LANGUAGE SQL;
CREATE TABLE t AS SELECT * FROM [SHOW CREATE FUNCTION fn];
```
or 
```
CREATE FUNCTION fn(i int) RETURNS INT AS 'SELECT i' LANGUAGE SQL;
CREATE MATERIALIZED VIEW v AS SELECT * FROM [SHOW CREATE FUNCTION fn];
```

results in a job failure (error message is slightly different for CREATE MATERIALIZED VIEW):
```
SELECT job_id, status, error, description 
FROM [SHOW JOBS] 
WHERE job_type IN ('SCHEMA CHANGE', 'NEW SCHEMA CHANGE')
AND status != 'succeeded''

880081200324935681, failed, unknown function: fn(): function undefined, CREATE TABLE defaultdb.public.t (function_name STRING, create_statement STRING) AS SELECT * FROM [SHOW CREATE FUNCTION fn]
```

Jira issue: CRDB-29473

Epic CRDB-27601

### PR DESCRIPTION
**Pull request by ecwall**
Fixes #106268

Previously `CREATE TABLE AS`/`CREATE MATERIALIZED VIEW AS` sourcing from `SHOW CREATE FUNCTION <function>` generated a failing schema change job with a `unknown function: f(): function undefined` error because the job runs in the system database and functions cannot be referenced cross database.

This PR fixes this by using the original user session (which includes the database) in the schema change job.

Release note (bug fix): Fixes the schema changer job when CREATE AS sources from SHOW CREATE FUNCTION:
CREATE TABLE t AS SELECT * FROM [SHOW CREATE FUNCTION f];

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
nice, 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107567#-:-NaPj96YCWjx167Nc0P4:b-n0sv8q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @rhu713)

___
*[`pkg/sql/schema_changer.go` line 311 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107567#-NaPjVAe7rPRenUymdHF:-NaPjVAe7rPRenUymdHG:b-3r6s6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0ad3c914eeed314977e5203302bf11705e1a703/pkg/sql/schema_changer.go#L311)):*
> ```Go
> 
> 		sd := NewInternalSessionData(ctx, sc.execCfg.Settings, "backfillQueryIntoTable")
> 		sd.SessionData = *sc.sessionData
> ```

it seems like this will affect the `applicationName` and `User` (and other fields) used for the internal session data. `NewInternalSessionData` sets the appName to `backfillQueryIntoTable` and the user to `node`, but then that gets overwritten with whatever was in `sc.SessionData`.

i wonder if we should be more conservative here, and only pass along the `Database`, rather than all of the `sessionData`
___
*[`pkg/sql/delegate/show_function.go` line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107567#-NaPicqoBqQlS9mJQSi6:-NaPicqoBqQlS9mJQSi7:b-7jl2le) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0ad3c914eeed314977e5203302bf11705e1a703/pkg/sql/delegate/show_function.go#L65)):*
> ```Go
> 		}
> 		if !referenceByName.HasExplicitCatalog() {
> 			referenceByName.Parts[2] = d.evalCtx.SessionDataStack.Top().Database
> ```

nit: use `d.evalCtx.SessionData().Database`

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107567)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @rhu713)

___
*[`pkg/sql/schema_changer.go` line 311 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107567#-NaPjVAe7rPRenUymdHF:-NaTK3TeB5Wi47pQaYub:b-imo1js) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0ad3c914eeed314977e5203302bf11705e1a703/pkg/sql/schema_changer.go#L311)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it seems like this will affect the `applicationName` and `User` (and other fields) used for the internal session data. `NewInternalSessionData` sets the appName to `backfillQueryIntoTable` and the user to `node`, but then that gets overwritten with whatever was in `sc.SessionData`.

i wonder if we should be more conservative here, and only pass along the `Database`, rather than all of the `sessionData`
</blockquote></details>

I'm guessing there are other inconsistencies when a user query delegates to a job because the session data changes because of this. 

Can you think of any reasons why we would want the session data to change? It seems to me like an impl detail that the query runs in a job so I would expect the job to respect whatever session data the user originally set.
___
*[`pkg/sql/delegate/show_function.go` line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107567#-NaPicqoBqQlS9mJQSi6:-NaTEf-h9WBcq-hgks0q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0ad3c914eeed314977e5203302bf11705e1a703/pkg/sql/delegate/show_function.go#L65)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: use `d.evalCtx.SessionData().Database`
</blockquote></details>

Done.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107567)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @ecwall, and @rhu713)

___
*[`pkg/sql/schema_changer.go` line 311 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107567#-NaPjVAe7rPRenUymdHF:-Nan8afn3FoV5C-VnZ54:b7l5rlt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0ad3c914eeed314977e5203302bf11705e1a703/pkg/sql/schema_changer.go#L311)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

I'm guessing there are other inconsistencies when a user query delegates to a job because the session data changes because of this. 

Can you think of any reasons why we would want the session data to change? It seems to me like an impl detail that the query runs in a job so I would expect the job to respect whatever session data the user originally set.
</blockquote></details>

hm i see. since this inheritance is only happening for jobs started by user-submitted queries, i think it's fine then
___
*[`pkg/sql/vars.go` line 696 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/107567#-Nan8CyZBecI2Rf9CTme:-Nan8CyZBecI2Rf9CTmf:bvfzj6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/21cef6ac6c664394c054450c572f0445be01807e/pkg/sql/vars.go#L696)):*
> ```Go
> 					sessiondatapb.VectorizeOff.String(),
> 					sessiondatapb.VectorizeOn.String(),
> 					sessiondatapb.VectorizeExperimentalAlways.String(),
> ```

i think these are the wrong strings to use here. my reading of this is that this would result in an incorrect message.

the test here should be updated to check the error message too: https://github.com/cockroachdb/cockroach/blob/509f8c8ee5c7c9d13c46e60436c5dbb3363cfeea/pkg/sql/logictest/testdata/logic_test/set#L246

current behavior is:
```
root@localhost:26257/defaultdb> set vectorize = bogus;
ERROR: invalid value for parameter "vectorize": "bogus"
SQLSTATE: 22023
HINT: Available values: off,on,experimental_always
```
___
*[`pkg/sql/sessiondatapb/session_data.proto` line 142 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/107567#-Nan8k3CBrkHbKE2KLR0:-Nan8k3CBrkHbKE2KLR1:b-di9q8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/21cef6ac6c664394c054450c572f0445be01807e/pkg/sql/sessiondatapb/session_data.proto#L142)):*
> ```proto
>   // the first enum value as zero is required by proto3. This is mapped to
>   // VectorizeOn.
>   unset = 0 [(gogoproto.enumvalue_customname) = "VectorizeUnset"];
> ```

could we make these custom names be `unset`, `on`, `off,` and `experimental_always`? why do we want to keep those camel-cased ones?

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107567)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @rafiss, and @rhu713)

___
*[`pkg/sql/sessiondatapb/session_data.proto` line 142 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/107567#-Nan8k3CBrkHbKE2KLR0:-NanLlAmDhZ1jRQ2kZDr:b-ugznne) ([raw file](https://github.com/cockroachdb/cockroach/blob/21cef6ac6c664394c054450c572f0445be01807e/pkg/sql/sessiondatapb/session_data.proto#L142)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could we make these custom names be `unset`, `on`, `off,` and `experimental_always`? why do we want to keep those camel-cased ones?
</blockquote></details>

The value of the enum (`unset`) determines what the string value of the enum is - we need this to match the JSON (de)serializer to prevent the error in the linked issue.

`gogoproto.enumvalue_customname` determines what the const name is (`sessiondatapb.VectorizeUnset`). I think we want it to remain `sessiondatapb.VectorizeUnset` to make it clear it is a "vectorize" value and it needs to be uppercased to be public. It is already being referenced this way in the code.

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107567)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @rafiss, and @rhu713)

___
*[`pkg/sql/vars.go` line 696 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/107567#-Nan8CyZBecI2Rf9CTme:-NanQl7c8B_Zfq3xPQ3p:b-spkul0) ([raw file](https://github.com/cockroachdb/cockroach/blob/21cef6ac6c664394c054450c572f0445be01807e/pkg/sql/vars.go#L696)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think these are the wrong strings to use here. my reading of this is that this would result in an incorrect message.

the test here should be updated to check the error message too: https://github.com/cockroachdb/cockroach/blob/509f8c8ee5c7c9d13c46e60436c5dbb3363cfeea/pkg/sql/logictest/testdata/logic_test/set#L246

current behavior is:
```
root@localhost:26257/defaultdb> set vectorize = bogus;
ERROR: invalid value for parameter "vectorize": "bogus"
SQLSTATE: 22023
HINT: Available values: off,on,experimental_always
```
</blockquote></details>

I updated the test. The `sessiondatapb.VectorizeX.String()` calls print out the lowercased protobuf enum value to match the JSON serializer.

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107567)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @ecwall, and @rhu713)

___
*[`pkg/sql/vars.go` line 696 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/107567#-Nan8CyZBecI2Rf9CTme:-Nao10WqEokwqT8s8DO2:b-nzhft5) ([raw file](https://github.com/cockroachdb/cockroach/blob/21cef6ac6c664394c054450c572f0445be01807e/pkg/sql/vars.go#L696)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

I updated the test. The `sessiondatapb.VectorizeX.String()` calls print out the lowercased protobuf enum value to match the JSON serializer.
</blockquote></details>

ah ok, thanks for clarifying!

**Review by rafiss — APPROVED** [review]
> Reviewed 1 of 9 files at r2, 1 of 13 files at r7, 17 of 17 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107567)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @ecwall, and @rhu713)

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107567)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @ecwall, and @rhu713)

___
*[`pkg/sql/logictest/testdata/logic_test/vectorize` line 1296 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/107567#-Nao3WwR05IeX4aW_5Nz:-Nao3WwS9U6IdvR9aAfS:b-rpfr2k) ([raw file](https://github.com/cockroachdb/cockroach/blob/0695f6a597cf91cf298d64810f2dd78dc046781c/pkg/sql/logictest/testdata/logic_test/vectorize#L1296)):*
> ```
> subtest end
> 
> subtest todo4
> ```

nit: i just noticed all the todos in the names. could you update them?

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107567)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @rafiss, and @rhu713)

___
*[`pkg/sql/logictest/testdata/logic_test/vectorize` line 1296 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/107567#-Nao3WwR05IeX4aW_5Nz:-NaqKvRV-oyAVffIgV7K:bg9net3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0695f6a597cf91cf298d64810f2dd78dc046781c/pkg/sql/logictest/testdata/logic_test/vectorize#L1296)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: i just noticed all the todos in the names. could you update them?
</blockquote></details>

These "todo" subtests aren't really subtests - they are groups of statements that were not part of the subtests that I was trying to fix.

They should probably be broken down into subtests, but I think that is outside of the scope of this PR.

**Comment by ecwall** [comment]
bors r=rafiss

**Pull request merged**
