### PR TITLE
importccl: Added row limit option for importing bundle formats

### LINKED ISSUE #26493: importccl: add dry-run mode to show what would be imported
With the addition of `IMPORT` formats with configurable delimiters and or the ability to convert schemas from other DBs on the fly (rather than providing explicit, cockroach-dialect syntaxes in the statement itself), the result of IMPORT has become somewhat more complex to predict from the statement.

It thus now seems like it would be useful to a user to have some form of "dry-run" mode that, at the very least, showed the tables that would be imported and their schemas. Additionally it might be nice to show the first row or something, to verify decoding was properly configured along with something like row count, or even estimated imported size.

### PR DESCRIPTION
**Pull request by mokaixu**
A row limit option allows users to specify a fixed number of rows
that they want to import. This functionality is only available for
CSV/DELIMITED/AVRO formats.

With this code change, users can limit the number of rows they want
to import for PGDUMP and MYSQLDUMP bundle data formats. That is, they can
specify: `WITH row_limit="{$num}"` to only import $num rows.

Release note (sql change): Added WITH row_limit="{$num}" option for importing
bundle formats to allow users to do a quick test run on an import of $num rows.
Ex. IMPORT ... WITH row_limit="3";

Resolves: #26493

### CODE REVIEW

**Review by adityamaru — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56587)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @mokaixu)

___
*[pkg/ccl/importccl/import_stmt.go, line 538 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56587#-MMuUMlk-bWqp62Nbaw-:-MMuUMlk-bWqp62Nbaw0:b-lq9w82) ([raw file](https://github.com/cockroachdb/cockroach/blob/b532cfa0feb0677ed57b52dd086428ff503a6278/pkg/ccl/importccl/import_stmt.go#L538)):*
> ```Go
> 			}
> 			format.Format = roachpb.IOFileFormat_Mysqldump
> ```

nit: can we undo this change
___
*[pkg/ccl/importccl/import_stmt.go, line 549 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56587#-MMuUQ846EtVuWrqp_DA:-MMuUQ846EtVuWrqp_DB:b-iipjm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b532cfa0feb0677ed57b52dd086428ff503a6278/pkg/ccl/importccl/import_stmt.go#L549)):*
> ```Go
> 				format.MysqlDump.RowLimit = int64(rowLimit)
> 			}
> ```

nit: ditto
___
*[pkg/ccl/importccl/import_stmt_test.go, line 1598 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56587#-MMuWLWHErxmxpq61eSJ:-MMuWLWHErxmxpq61eSK:b-s33irb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffa5da5b005f46e9654762e91d0f7eedc6317435/pkg/ccl/importccl/import_stmt_test.go#L1598)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 		res := sqlDB.QueryStr(t, "SELECT * FROM second")
> 		if actualRowCount := len(res); expectedRowLimit != actualRowCount {
> 			t.Fatalf("expected %d, got %d", expectedRowLimit, actualRowCount)
> 		}
> ```
</details>

I think you can do something like:

var numRows int
sqlDB.QueryRow("SELECT count(*) FROM second").Scan(&numRows)
require.Equal(t, expectedRowLimit, numRows)

Here and elsewhere in the tests.
___
*[pkg/roachpb/io-formats.proto, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56587#-MMQr0FtB5yGcytP0HtI:-MMQr0FtB5yGcytP0HtJ:b52nnqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b532cfa0feb0677ed57b52dd086428ff503a6278/pkg/roachpb/io-formats.proto#L110)):*
> ```
> CSV file
> ```
I think you need to update the comment.
___
*[pkg/roachpb/io-formats.proto, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56587#-MMQr4gJ25Dmqc7jbSqs:-MMQr4gJ25Dmqc7jbSqt:bppclm2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b532cfa0feb0677ed57b52dd086428ff503a6278/pkg/roachpb/io-formats.proto#L117)):*
> ```
>   // Indicates the number of rows to import per CSV file.
>   // Must be a non-zero positive number.
> ```
ditto as above

**Review by mokaixu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56587)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @mokaixu)

___
*[pkg/ccl/importccl/import_stmt.go, line 538 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56587#-MMuUMlk-bWqp62Nbaw-:-MMxW43F16A9uzh6aF1u:bm2b0hx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b532cfa0feb0677ed57b52dd086428ff503a6278/pkg/ccl/importccl/import_stmt.go#L538)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

nit: can we undo this change
</blockquote></details>

like separate the mysqldump logic? If I undo this change, all the mysqldump imports with rowlimits fail
___
*[pkg/ccl/importccl/import_stmt_test.go, line 1598 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56587#-MMuWLWHErxmxpq61eSJ:-MMxPl7T40MlZrJH09TN:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffa5da5b005f46e9654762e91d0f7eedc6317435/pkg/ccl/importccl/import_stmt_test.go#L1598)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

> ```
> 		res := sqlDB.QueryStr(t, "SELECT * FROM second")
> 		if actualRowCount := len(res); expectedRowLimit != actualRowCount {
> 			t.Fatalf("expected %d, got %d", expectedRowLimit, actualRowCount)
> 		}
> ```
I think you can do something like:

var numRows int
sqlDB.QueryRow("SELECT count(*) FROM second").Scan(&numRows)
require.Equal(t, expectedRowLimit, numRows)

Here and elsewhere in the tests.
</blockquote></details>

done
___
*[pkg/roachpb/io-formats.proto, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56587#-MMQr0FtB5yGcytP0HtI:-MMxPWui2CNcLrpgKBMl:b269h3d) ([raw file](https://github.com/cockroachdb/cockroach/blob/b532cfa0feb0677ed57b52dd086428ff503a6278/pkg/roachpb/io-formats.proto#L110)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

> ```
> CSV file
> ```
I think you need to update the comment.
</blockquote></details>

oops! done changed to per table
___
*[pkg/roachpb/io-formats.proto, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56587#-MMQr4gJ25Dmqc7jbSqs:-MMxPZIl7TB60fccIzkH:b-dnlvzn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b532cfa0feb0677ed57b52dd086428ff503a6278/pkg/roachpb/io-formats.proto#L117)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

> ```
>   // Indicates the number of rows to import per CSV file.
>   // Must be a non-zero positive number.
> ```
ditto as above
</blockquote></details>

done, changed to per table

**Comment by adityamaru** [comment]
This LGTM! Feel free to merge over the weekend once CI is green 🥳

**Review by adityamaru — APPROVED** [review]
> Reviewed 1 of 8 files at r1, 1 of 4 files at r2, 2 of 4 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56587)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @mokaixu)

**Comment by mokaixu** [comment]
bors r=adityamaru

**Comment by mokaixu** [comment]
bors r=adityamaru

**Pull request merged**
