### PR TITLE
roachtest: add ability to perform multiple upgrades in mixedversion

### PR DESCRIPTION
**Pull request by renatolabs**
This commit adds the ability for `mixedversion` tests to perform
multiple upgrades in certain tests runs. It has been observed that
certain types of errors only manifest when features are enabled in
older releases, and this makes it possible for us to get some coverage
for these scenarios.

By default, `mixedversion` tests will perform a random number of
upgrades (up to a maximum of 3). Test authors are able to override
this default by providing a minimum, maximum, or exact number of
upgrades test runs should go through.

Epic: CRDB-19321

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
There's a likely legit bug that causes this test to fail when a `RESTORE` is attempted while the cluster is finalizing the 22.1 -> 22.2 upgrade:

```[mixed-version-test/20_run-verify-some-backups] 01:51:05 runner.go:336: mixed-version test failure while running step 20 (run "verify some backups"): mixed-version: waiting for job to finish: job 891269071918759937 failed with error: version mismatch for descriptor 132, expected version 2, got 1```

I'll let @cockroachdb/disaster-recovery deal with this failure as they see fit when it happens in the nightly build.

**Review by smg260 — APPROVED** [review]
The feature generally makes sense to me.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108773#-:-NcOi1ZE50ukIJkdpBN0:b-y8nhfd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 929 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108773#-NcOaUNi4NPnrdfySJTK:-NcOaUNi4NPnrdfySJTL:bz96iuq) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc5456a70c41be8634e51a44ec05536e7c951fb3/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L929)):*
> ```Go
> 	if test.options.minUpgrades > test.options.maxUpgrades {
> 		err := fmt.Errorf(
> 			"invalid test options: minUpgrades=%d maxUpgrades=%d",
> ```

minor: might make sense to be explicit about the error here. 

e.g. `maxUpgrades (%d) must be greater than minUpgrades (%d)`

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108773)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 929 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108773#-NcOaUNi4NPnrdfySJTK:-NcScHNh45icvDiG9pVs:b-g1hs46) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc5456a70c41be8634e51a44ec05536e7c951fb3/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L929)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

minor: might make sense to be explicit about the error here. 

e.g. `maxUpgrades (%d) must be greater than minUpgrades (%d)`
</blockquote></details>

Makes sense, done.

**Comment by renatolabs** [comment]
Added another commit to adapt the new `cdc/mixed-versions` to multiple upgrades (also updated test ownership back to CDC; always happy to help debug mixed-version issues, but it makes more sense for cdc to own that test).

@jayshrivastava FYI.

**Comment by renatolabs** [comment]
TFTR!

bors r=smg260

**Pull request merged**
