### PR TITLE
serverutils: redirect the implicit `ApplicationLayerInterface` properly

### PR DESCRIPTION
**Pull request by knz**
All commits but the last 3 are from #110008.
Epic: CRDB-18499

Prior to this patch, the *implicit* `ApplicationLayerInterface`
implementation inside `TestServerInterface` was redirecting to
`SystemLayer()`. This was confusing, likely the source of bugs, and
resulted in insufficient test coverage.

This commit fixes it.

followup issues identified thanks to this work:
- actual bug: https://github.com/cockroachdb/cockroach/issues/110003
- possible bug: https://github.com/cockroachdb/cockroach/issues/110002
- possible bug: https://github.com/cockroachdb/cockroach/issues/110007
- possible bug: https://github.com/cockroachdb/cockroach/issues/110012
- feature gap: https://github.com/cockroachdb/cockroach/issues/110009
- feature gap: https://github.com/cockroachdb/cockroach/issues/110018
- feature gap: https://github.com/cockroachdb/cockroach/issues/110019
- feature gap: https://github.com/cockroachdb/cockroach/issues/110020
- feature gap: https://github.com/cockroachdb/cockroach/issues/110022
- feature gap: https://github.com/cockroachdb/cockroach/issues/110023
- feature gap: https://github.com/cockroachdb/cockroach/issues/110024

### CODE REVIEW

**Comment by knz** [comment]
The remaining failure in //pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl is not specific to this PR and discussed [here](https://cockroachlabs.slack.com/archives/C019A8NANH0/p1693930522041749).

**Comment by yuzefovich** [comment]
Nice, very happy to see this! LGTM, but I'll defer to others for approval.

**Comment by knz** [comment]
rebased; PTAL

**Review by stevendanna — APPROVED** [review]
Reminder to remove the `wip` commit before merge.

**Comment by knz** [comment]
TFYR!

bors r=stevendanna

**Pull request merged**
