### PR TITLE
cli: remove mention of RocksDB

### PR DESCRIPTION
**Pull request by erikgrinaker**
This removes any reference to RocksDB in the `debug` CLI code, using
Pebble instead.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
I'm not so sure about capitalizing Pebble but that truly doesn't matter.

**Comment by erikgrinaker** [comment]
> I'm not so sure about capitalizing Pebble but that truly doesn't matter.

Yeah, I've seen that comments often don't capitalize proper nouns, but it doesn't appear to be consistent. What's the rationale? Happy to follow any established conventions, but I couldn't find any mention of it in the coding style guide.

**Comment by tbg** [comment]
I'm not sure, I think it is an odd case. #storage should probably get last
word but I would just capitalize it.

(sent from mobile, please excuse my brevity)

**Comment by erikgrinaker** [comment]
Well, Pebble is capitalized in comments in the `storage` package, so I suppose it's fine. TFTR!

bors r=tbg

**Comment by erikgrinaker** [comment]
bors r=tbg

**Comment by erikgrinaker** [comment]
Third time's the charm!

bors r=tbg

**Comment by erikgrinaker** [comment]
These all seem to be random flakes. 😐 Let's try this again.

bors r=tbg

**Pull request merged**
