### PR TITLE
go.mod: bump Pebble to 4199154043c5

### PR DESCRIPTION
**Pull request by jbowens**
```
41991540 db: tweak to BenchmarkIteratorScanNextPrefix and performance commentary
bb1a420f internal/rangekey: optimize Coalesce
76159f92 sstable: remove Writer.RangeKey{Set,Unset,Delete} coalescing
9057cd24 sstable: update two sstable benchmarks to also read the value
012c0ce3 replay: unflake TestCollectCorpus
152a19ea *: apply Go 1.19
```

Epic: None
Release note: None

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95834)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick)

___
*[`pkg/storage/testdata/mvcc_histories/sst_writer` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95834#-NMdcq620iVSASqZPoNy:-NMdcq620iVSASqZPoNz:bx0pzlb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b84f0eb4c05e6a39d8e73b20fb042cb614968a6a/pkg/storage/testdata/mvcc_histories/sst_writer#L2)):*
> ```
> # Writing keys out of order fails, except for overlapping range keys by
> # timestamp which succeeds.
> ```

@erikgrinaker —you're not aware of anywhere we're dependent on this range key behavior, correct? I removed the logic that 'coalesces' overlapping range keys within the SST writer under the expectation that the client is responsible for writing consistent data (Eg, a suffix cannot be both set and unset). I still need to follow up to turn out-of-order suffixes into an error condition.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95834)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick and @jbowens)

___
*[`pkg/storage/testdata/mvcc_histories/sst_writer` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95834#-NMdcq620iVSASqZPoNy:-NMeLMDW8UVmcwqrFMmh:b-gyeiht) ([raw file](https://github.com/cockroachdb/cockroach/blob/b84f0eb4c05e6a39d8e73b20fb042cb614968a6a/pkg/storage/testdata/mvcc_histories/sst_writer#L2)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

@erikgrinaker —you're not aware of anywhere we're dependent on this range key behavior, correct? I removed the logic that 'coalesces' overlapping range keys within the SST writer under the expectation that the client is responsible for writing consistent data (Eg, a suffix cannot be both set and unset). I still need to follow up to turn out-of-order suffixes into an error condition.
</blockquote></details>

Off-hand, I don't believe so, no. When we're writing range keys we'll often do so based on some iterator, which has already done the coalescing.

**Review by nicktrav — APPROVED** [review]
Unclear if that test failure is relevant or not. Otherwise :lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95834#-:-NMef2bgBTmJlEB4_Cpq:b-can7cm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bananabrick and @jbowens)

**Comment by jbowens** [comment]
TFTR!

bors r=nicktrav

**Pull request merged**
