### PR TITLE
pkg/sql: expand metrics used by the SQL stats activity update job

### PR DESCRIPTION
**Pull request by abarganier**
pkg/sql: expand metrics used by the SQL stats activity update job

Addresses: https://github.com/cockroachdb/cockroach/issues/119779

Epic: CRDB-24527

Currently, the SQL activity update job is lacking observability. While
we have a metric for job failures, we've seen instances whe the query
run by the job gets caught in a retry loop, meaning the metric is rarely
incremented.

Therefore, additional metrics, such as counts of successful runs, and
the latency of successful runs, will be helpful to further inspect the
state of the job.

This patch adds metrics for both.

We've also had escalations recently involving the SQL activity update job
running for extended periods of time, such that the signal made to the
job indicating a flush has completed was not received because there was
no listener.

While we've added a default case to prevent this from hanging the flush
job, and some logging to go with it, a counter metric indicating when
this occurs would also be useful to have when debugging.

This patch adds such a counter.

Finally, we rename the metric counting failures of the job to `sql.stats.activity_job.runs.failed`,
as the old metric name was not descriptive. 

Release note (ops change): Two new metrics have been added to track the
status of the SQL activity update job, which is used to pre-aggregate
top K information within the SQL stats subsytem and write the results to
`system.statement_activity` and `system.transaction_activity`.

The new metrics are:
- `sql.stats.activity_job.runs.successful`: Number of successful runs made
   by the SQL activity updater job
- `sql.stats.activity_job.latency`: The latency of successful runs made by
  the SQL activity updater job

Release note (ops change): A new counter metric,
`sql.stats.flush.done_signals_ignored`, has been introduced. The metric
tracks the number of times the SQL Stats activity update job ignored
the signal sent to it indicating a flush has completed. This may
indicate that the SQL Activity update job is taking longer than expected
to complete.

Release note (ops change): A new counter metric,
`sql.stats.activity_job.runs.failed`, has been introduced to measure the
number of runs made by the SQL activity updater job that failed with
errors. The SQL activity update job is used to pre-aggregate top K
information within the SQL stats subsystem and write the results to
`system.statement_activity` and `system.transaction_activity`.

### CODE REVIEW

**Review by koorosh — COMMENTED** [review]
> Reviewed 3 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120522)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @xinhaoz)

___
*[`pkg/sql/sql_activity_update_job.go` line 140 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/120522#-Nt2FbLYAlfgX5l2duSK:-Nt2FbLYAlfgX5l2duSL:b-6zowmj) ([raw file](https://github.com/cockroachdb/cockroach/blob/15b3c4eda65fb8d763ae37eab383d0fe02a7ff57/pkg/sql/sql_activity_update_job.go#L140)):*
> ```Go
> 			Name:        "sql.stats.activity_job.runs.failed",
> 			Help:        "Number of runs made by the SQL activity updater job that failed with errors",
> 			Measurement: "failed runs",
> ```

Is it appropriate measurement? I assume it should be `jobs` as it measures number of jobs. Metric name describes that it counts failed job executions. WDYT?
___
*[`pkg/sql/sql_activity_update_job.go` line 147 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/120522#-Nt2G1UP6CP2N8wmiHxZ:-Nt2G1UP6CP2N8wmiHx_:b2nreh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/15b3c4eda65fb8d763ae37eab383d0fe02a7ff57/pkg/sql/sql_activity_update_job.go#L147)):*
> ```Go
> 			Name:        "sql.stats.activity_job.runs.successful",
> 			Help:        "Number of successful runs made by the SQL activity updater job",
> 			Measurement: "successful runs",
> ```

Same as above.

**Comment by xinhaoz** [comment]
*[`pkg/sql/sql_activity_update_job.go` line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120522#-Nt2yeCcAcf3gSWeXscr:-Nt2yeCcAcf3gSWeXscs:b-8gdm2y) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b6071c80d9a1dde6c8266f51a47d4efa02ab663/pkg/sql/sql_activity_update_job.go#L154)):*
> ```Go
> 			Metadata: metric.Metadata{
> 				Name:        "sql.stats.activity_job.latency",
> 				Help:        "The latency of successful runs made by the SQL activity updater job",
> ```

I'm wondering if we should also track latency of unsuccessful runs too. WDYT? So this can just be latency and the job result can be viewed using the other 2 metrics.

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120522)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @xinhaoz)

___
*[`pkg/sql/sqlstats/persistedsqlstats/provider.go` line 206 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/120522#-Nt65KEJ0CF9d2Fu8KPX:-Nt65KEJ0CF9d2Fu8KPY:by0k565) ([raw file](https://github.com/cockroachdb/cockroach/blob/94736c3f2e77a4bca89f08a4a35ffdaa46d500a1/pkg/sql/sqlstats/persistedsqlstats/provider.go#L206)):*
> ```Go
> 			}(); sigCh != nil {
> 				select {
> 				case sigCh <- struct{}{}:
> ```

Unrelated to main fix question but curious to clarify and submit separate issue if needed.
What is the chance to receive signal here if we have `default` case?
I assume that flushing takes at least some time and default case will be called most of the time?

**Review by abarganier — COMMENTED** [review]
Thanks for the reviews! PTAL. Also note that I added a 4th commit, adding a new counter to track the # of unique stmt & txn fingerprints included in each flush. I expect this to be a useful metric as we continue working on fingerprinting improvements/cardinality reduction. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120522#-:-NtHPdBP-z47Eq2T9XjR:b-ubuaf8)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @koorosh and @xinhaoz)

___
*[`pkg/sql/sql_activity_update_job.go` line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120522#-Nt2yeCcAcf3gSWeXscr:-NtHOwM_1dPCZYz_cWDh:bvl1a78) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b6071c80d9a1dde6c8266f51a47d4efa02ab663/pkg/sql/sql_activity_update_job.go#L154)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

I'm wondering if we should also track latency of unsuccessful runs too. WDYT? So this can just be latency and the job result can be viewed using the other 2 metrics.
</blockquote></details>

Good idea! I've switched it to record the latency in either case. 
___
*[`pkg/sql/sql_activity_update_job.go` line 140 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/120522#-Nt2FbLYAlfgX5l2duSK:-NtHOoP30WVkvF4gHr3I:b-tpx354) ([raw file](https://github.com/cockroachdb/cockroach/blob/15b3c4eda65fb8d763ae37eab383d0fe02a7ff57/pkg/sql/sql_activity_update_job.go#L140)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Is it appropriate measurement? I assume it should be `jobs` as it measures number of jobs. Metric name describes that it counts failed job executions. WDYT?
</blockquote></details>

As discussed on Slack, changed the terminology to `updates`. 
___
*[`pkg/sql/sql_activity_update_job.go` line 147 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/120522#-Nt2G1UP6CP2N8wmiHxZ:-NtHOuH51mCkxCJFScY1:bsjte78) ([raw file](https://github.com/cockroachdb/cockroach/blob/15b3c4eda65fb8d763ae37eab383d0fe02a7ff57/pkg/sql/sql_activity_update_job.go#L147)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

See above comment.
___
*[`pkg/sql/sqlstats/persistedsqlstats/provider.go` line 206 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/120522#-Nt65KEJ0CF9d2Fu8KPX:-NtHP53BC6A_IfzGF-F7:b-4js6nm) ([raw file](https://github.com/cockroachdb/cockroach/blob/94736c3f2e77a4bca89f08a4a35ffdaa46d500a1/pkg/sql/sqlstats/persistedsqlstats/provider.go#L206)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Unrelated to main fix question but curious to clarify and submit separate issue if needed.
What is the chance to receive signal here if we have `default` case?
I assume that flushing takes at least some time and default case will be called most of the time?
</blockquote></details>

When this was created, I believe the assumption was that the activity job would always be listening on the channel, which is why there was no `default` case originally. As we've seen, that's not always the case, especially when a customer has a workload that generates high cardinality stats.

I don't think we have a great answer to your question yet, unfortunately. Hopefully these metrics help us answer that!

**Review by koorosh — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r6, 5 of 5 files at r7, 2 of 2 files at r8, 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120522#-:-NtHfxq6AJCGe3dRx0_S:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @abarganier and @xinhaoz)

___
*[`pkg/sql/sqlstats/persistedsqlstats/provider.go` line 206 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/120522#-Nt65KEJ0CF9d2Fu8KPX:-NtHeVfd9QWEeUcZTTZc:b-vocqrv) ([raw file](https://github.com/cockroachdb/cockroach/blob/94736c3f2e77a4bca89f08a4a35ffdaa46d500a1/pkg/sql/sqlstats/persistedsqlstats/provider.go#L206)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

When this was created, I believe the assumption was that the activity job would always be listening on the channel, which is why there was no `default` case originally. As we've seen, that's not always the case, especially when a customer has a workload that generates high cardinality stats.

I don't think we have a great answer to your question yet, unfortunately. Hopefully these metrics help us answer that!
</blockquote></details>

👍🏼

**Comment by abarganier** [comment]
TFTR! 

bors r=koorosh

**Pull request merged**
