### PR TITLE
cli/zip: clamp file retrieval by date, default to last 48 hours

### LINKED ISSUE #57795: cli: Decrease the size of the debug.zip file
**Is your feature request related to a problem? Please describe.**
As we continue to grow and see clusters that have a larger number of nodes, we are starting to see debug zips climb into the gigabyte range.  We can only assume that this will continue to grow.
 
**Describe the solution you'd like**
Can we have the current debug zip become the "verbose" version of a debug zip. 
The debug zip should only contain a small subset of data such as just logs from each of the nodes. 

**Describe alternatives you've considered**
Perhaps we can also add flags to the `cockroach debug zip` command to get other files we need/want. 
An example would be if we just wanted the ranges for each node, we could do something like 
`cockroach debug zip ranges <filename>` 
It looks like some of the code for that is here: 

https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/zip.go#L692

**Additional context**

### PR DESCRIPTION
**Pull request by knz**
All commits but the last from #64094 and prior.
Fixes #57795

The size of generated `debug zip` outputs is mostly attributable to
the discrete files retrieved from the server:

- log files
- goroutine dumps
- heap profiles

Even though we have various garbage collection techniques applied to
these files, they still yield very large `debug zip` outputs:

- the default retained cap for log files is 100MB per group,
  so with the default of up to 5 log groups per node, we are retaining
  up to 500MB of log files per node.
- the default retained cap for goroutine dumps, heap profiles and
  memory stats is 128MB for each, so we are retaining up to 384MB of
  these files per node.

For example, for a 10-node cluster we are looking at up to 7GB of data
retained in these files in the default configuration.

While this amount of data is relatively innocuous while it remains
in the data directories server-side, the `debug zip` behavior
which was previously to retrieve *all* of it was detrimental
to the process of troubleshooting anomalies: this is a lot
of data to move around, it cannot be e-mailed effectively, etc.

In comparison, the other items retrieved by the `debug zip`
command (range descriptors, SQL system tables) are typically just
kilobytes large. Even a large cluster with tens of thousands of ranges
and system tables typically incurs `zip` payloads no greater than a dozen
megabytes.

Hence the change described in the release note below.

Release note (cli change): The `cockroach debug zip` command now
retrieves only the log files, goroutine dumps and heap profiles
pertaining to the last 48 hours prior to the command invocation.

This behavior is supported entirely client-side, i.e. it is not
necessary to upgrade the server nodes to effect these newly
configurable limits.

This behavior can be customized by the two new flags `--files-from`
and `--files-until`. Both are optional. See the command-line
help text for details.

The other data items retrieved by `debug zip` are not affected
by this time limit.

The two new flags are also supported by `cockroach debug list-files`.
It is advised to experiment with `list-files` prior to issuing
a `debug zip` command that may retrieve a large amount of data.

### CODE REVIEW

**Comment by knz** [comment]
cc @thtruo

**Review by stevendanna — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 2 of 2 files at r2, 14 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64128)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @nickelnickel, @stevendanna, and @tbg)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/64128#-MYyuxfE1YMRlzI7HRxY:-MYyuxfE1YMRlzI7HRxZ:b43p3x2) (no related file):*
I like this feature. Most tools I've seen that produce debug bundles have _some_ way of limiting log output, either based on size, number of lines, or date range. Given CRDB's distributed nature, I think a date range like you've used here makes the most sense.

In the future I could imagine  trying to support more flexible time parsing similar to git-log's or journalctl's `--since` flag (which supports strings such as "2 days ago").

It might also be nice to provide some warning/hint to users that lead them to this option if they run `zip` and end up creating an archive over some threshold.

But both of those can come later if needed.

(I just reviewed r4 as I assume the rest are more or less the same as in the other PRs)

---
___
*[pkg/cli/zip_helpers.go, line 324 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64128#-MYypKP66XfZkiYQBUJy:-MYypKP66XfZkiYQBUJz:bvyqcg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa49de2549fd2cf99ec75896526d995313cfa914/pkg/cli/zip_helpers.go#L324)):*
> ```Go
> 	}
> 	// And the selected "until" time must not be before the ctime.
> 	if (*time.Time)(&fs.endTimestamp).Before(ctime) {
> ```

Is there much advantage to this over:

```go
time.Time(fs.endTimestamp).Before(ctime)
```

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64128)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nickelnickel, @stevendanna, and @tbg)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/64128#-MYyuxfE1YMRlzI7HRxY:-MYzdZ_Q4ehNqD9dw0zD:b-or9ib3) (no related file):*
>  I could imagine  trying to support more flexible time parsing similar to git-log's or journalctl's --since flag

I started with this idea too, but then I also realized it would create an entire _chapter_ of documentation to thoroughly explain everything we don't support and what we do not. Also it would be odd for that flag to support extended timestamp syntax, whereas we don't support it in SQL. If we start using this kind of logic, I'd like to use a holistic approach and make it available in every place where crdb accepts timestamps, not just this cli flag.

> It might also be nice to provide some warning/hint to users that lead them to this option if they run zip and end up creating an archive over some threshold.

This is a good idea! How do you envision this warning/hint to be presented? At the end? In the middle?

- in the beginning/middle: this might drown within the other output
- at the end: it's sad because by that time the data has been collected already

---
___
*[pkg/cli/zip_helpers.go, line 324 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64128#-MYypKP66XfZkiYQBUJy:-MYzeJ1j4qNGD1iTB_I7:b-u9x0z4) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa49de2549fd2cf99ec75896526d995313cfa914/pkg/cli/zip_helpers.go#L324)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Is there much advantage to this over:

```go
time.Time(fs.endTimestamp).Before(ctime)
```
</blockquote></details>

That's incorrect. `Before` is strict inequality, and we want to include the upper bound.
The unit test catches it.

**Review by tbg — COMMENTED** [review]
Only reviewed the last commit as well. Great stuff, will be looking forward to having this in the wild.

Re: the comments, we could make the warning pretty aggressive and chose "all of the above". When the file size breaks a preset limit (say 100mb), then we print the hint after each line of output. The operator can either ignore it (if they're even looking) or CTRL+C the process to adjust the flag. I considered another alternative, which is to *abort* the operation and ask for a re-invocation with an override should the giant zip really be desired, but I think that is poor UX and will break scripts pretty badly when you need them to work the most.

> Reviewed 2 of 5 files at r1, 15 of 15 files at r9, 2 of 2 files at r10, 15 of 15 files at r11, 7 of 7 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64128#-:-MZCCw5vCSGiJ1o28Cgm:b3f1tgp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @nickelnickel, and @stevendanna)

___
*[pkg/cli/context.go, line 352 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/64128#-MZC9vN86nUG4V73RDYQ:-MZC9vN86nUG4V73RDYR:btsocvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/583c6aa27e747ebd5ca4949f2f31680111027fa0/pkg/cli/context.go#L352)):*
> ```Go
> 	now := timeutil.Now()
> 	zipCtx.files.startTimestamp = timestampValue(now.Add(-48 * time.Hour))
> 	zipCtx.files.endTimestamp = timestampValue(now)
> ```

Shouldn't this be "infinity"? We wouldn't want to exclude a current file based on some delay passing between when `now()` is chosen on the client and the server receives the request.
___
*[pkg/cli/flags.go, line 629 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/64128#-MZCAKTW-5rotE_VHItE:-MZCAKTXCH-81us9Jgxo:b-2r4wib) ([raw file](https://github.com/cockroachdb/cockroach/blob/583c6aa27e747ebd5ca4949f2f31680111027fa0/pkg/cli/flags.go#L629)):*
> ```Go
> 		intFlag(f, &zipCtx.concurrency, cliflags.ZipConcurrency)
> 	}
> 	// List-nodes + Zip commands.
> ```

List-files
___
*[pkg/cli/zip_per_node.go, line 306 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/64128#-MZCBkP0DE27kjMEXDCp:-MZCBkP0DE27kjMEXDCq:bagzebw) ([raw file](https://github.com/cockroachdb/cockroach/blob/583c6aa27e747ebd5ca4949f2f31680111027fa0/pkg/cli/zip_per_node.go#L306)):*
> ```Go
> 			fs := nodePrinter.start("retrieving %s", file.Name)
> 			var oneprof *serverpb.GetFilesResponse
> 			if fileErr := zc.runZipFn(ctx, fs, func(ctx context.Context) error {
> ```

This is done back-to-back, but concurrently across all nodes, right? Just trying to understand how this impacts the duration of the debug.zip. (Before we had one round-trip, now we have O(files) round-trips). Just to suggest an alternative, we could list the files only first, filter them, and then request a specific list of files to get back to two round-trips which will always be ok. Whether this is worth optimizing - don't know.

Same comment applies to the other retrievals of this style.
___
*[pkg/cli/zip_per_node.go, line 384 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/64128#-MZCCJhM16W4ApImVXQv:-MZCCJhM16W4ApImVXQw:b-aeziii) ([raw file](https://github.com/cockroachdb/cockroach/blob/583c6aa27e747ebd5ca4949f2f31680111027fa0/pkg/cli/zip_per_node.go#L384)):*
> ```Go
> 				if len(onedump.Files) < 1 {
> 					// This is possible in theory, if the file was removed in-between
> 					// the list request above and the content retrieval request.
> ```

I see this in practice regularly, btw, with `roachprod get` which often (10% of the time?) throws an error when retrieving the logs due to files having gotten GC'ed. So it may not be as rare as these comments make it out to be.
___
*[pkg/cli/cliflags/flags.go, line 1291 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/64128#-MZCE6AK4dE2_62_qcNE:-MZCE6AK4dE2_62_qcNF:b-wwi8ta) ([raw file](https://github.com/cockroachdb/cockroach/blob/583c6aa27e747ebd5ca4949f2f31680111027fa0/pkg/cli/cliflags/flags.go#L1291)):*
> ```Go
> 	}
> 
> 	ZipIncludedFiles = FlagInfo{
> ```

Should clarify what filenames these patterns correspond to. I guess they will never be considered as full paths, we're only matching filenames here, right? Also, the operator might think that these refer to filenames in the `debug.zip` and might, say, try to exclude `nodes/*/ranges/*.json` which just won't do anything. So maybe just spell out what files these patterns apply to.
___
*[pkg/cli/cliflags/flags.go, line 1311 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/64128#-MZCChSsDpJl1m-Ra---:-MZCChSsDpJl1m-Ra--0:besjxay) ([raw file](https://github.com/cockroachdb/cockroach/blob/583c6aa27e747ebd5ca4949f2f31680111027fa0/pkg/cli/cliflags/flags.go#L1311)):*
> ```Go
> be excluded from the output. The list can be specified
> as a comma-delimited list of patterns, or by using the
> flag multiple times.
> ```

Intuitively clear, but it might be worth spelling out that exclusion overrides inclusion, i.e. including `*.log` and then excluding `*foo*.log` will exclude `barfoos.log`.

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64128)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @nickelnickel)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/64128#-MYyuxfE1YMRlzI7HRxY:-MZCI57b0WMftlneqo0I:btd02lo) (no related file):*
> at the end: it's sad because by that time the data has been collected already

I was thinking we display it at the end despite this downside.  The large file likely poses multiple problems for the user: (1) collection time, (2) time to transfer it out of a potentially higher-security portion of their network, (3) time to upload it to our servers.  While we wouldn't help with (1) at least we would be helping with (2) and (3) and save support engineers or on-call engineers from having to deal with the very large file in some cases.

I think Tobias' idea of warning throughout might work as well. Perhaps we could rate limit the rate of the spamming a bit.

---
___
*[pkg/cli/zip_helpers.go, line 324 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64128#-MYypKP66XfZkiYQBUJy:-MZCHGp83T2FXMmilE3n:b-g2sr7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa49de2549fd2cf99ec75896526d995313cfa914/pkg/cli/zip_helpers.go#L324)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

That's incorrect. `Before` is strict inequality, and we want to include the upper bound.
The unit test catches it.
</blockquote></details>

Sorry, I was simply referring to the type being cast to. That is `*time.Time` vs `time.Time`, not any change in the logic.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64128)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @nickelnickel, @stevendanna, and @tbg)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/64128#-MYyuxfE1YMRlzI7HRxY:-MZCrfZoCCyMQ6oFgLIR:b527eid) (no related file):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

> at the end: it's sad because by that time the data has been collected already

I was thinking we display it at the end despite this downside.  The large file likely poses multiple problems for the user: (1) collection time, (2) time to transfer it out of a potentially higher-security portion of their network, (3) time to upload it to our servers.  While we wouldn't help with (1) at least we would be helping with (2) and (3) and save support engineers or on-call engineers from having to deal with the very large file in some cases.

I think Tobias' idea of warning throughout might work as well. Perhaps we could rate limit the rate of the spamming a bit.

</blockquote></details>

Processing the first batch of comments, which really belong to the prefix PR  #64094.

---
___
*[pkg/cli/flags.go, line 629 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/64128#-MZCAKTW-5rotE_VHItE:-MZCozfVC90Xt2tMISDu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/583c6aa27e747ebd5ca4949f2f31680111027fa0/pkg/cli/flags.go#L629)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

List-files
</blockquote></details>

Done.
___
*[pkg/cli/zip_per_node.go, line 306 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/64128#-MZCBkP0DE27kjMEXDCp:-MZCpNL571UhbKCQ9z32:b-iwpdt1) ([raw file](https://github.com/cockroachdb/cockroach/blob/583c6aa27e747ebd5ca4949f2f31680111027fa0/pkg/cli/zip_per_node.go#L306)):*
Before we had:
- time cost, per node: 1 x roundtrip + #totalsize / bandwidth.
- space cost, per node: #totalsize  (the entire file contents were accumulated in RAM in one response)

Now we have:
- time cost, per node: #files x roundtrip + #totalsize / bandwidth
- space cost, per node: max(#1filesize)

Notice how the time cost involves transmitting the bytes over the network.  We have relatively few files (less than hundreds)  but  many bytes to transmit (dozens of megabytes). The transmission dominates, so I believe we can neglect the roundtrip cost.

> request a specific list of files to get back to two round-trips which will always be ok.

No it is not OK, we actually had a known issue with that (even though it wasn't filed), which is that all the file contents are loaded up in RAM in one response--this can increase the risk of OOM crashes.

The current code is strictly better as it loads only 1 file at a time in responses.

Added a comment to explain.
___
*[pkg/cli/zip_per_node.go, line 384 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/64128#-MZCCJhM16W4ApImVXQv:-MZCpFo17pSIN2ikWv7n:bmg35k4) ([raw file](https://github.com/cockroachdb/cockroach/blob/583c6aa27e747ebd5ca4949f2f31680111027fa0/pkg/cli/zip_per_node.go#L384)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I see this in practice regularly, btw, with `roachprod get` which often (10% of the time?) throws an error when retrieving the logs due to files having gotten GC'ed. So it may not be as rare as these comments make it out to be.
</blockquote></details>

Removed the "in theory" from the comment.
___
*[pkg/cli/cliflags/flags.go, line 1291 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/64128#-MZCE6AK4dE2_62_qcNE:-MZCs4NqCkR33i5yRhsq:b-qu6n94) ([raw file](https://github.com/cockroachdb/cockroach/blob/583c6aa27e747ebd5ca4949f2f31680111027fa0/pkg/cli/cliflags/flags.go#L1291)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Should clarify what filenames these patterns correspond to. I guess they will never be considered as full paths, we're only matching filenames here, right? Also, the operator might think that these refer to filenames in the `debug.zip` and might, say, try to exclude `nodes/*/ranges/*.json` which just won't do anything. So maybe just spell out what files these patterns apply to.
</blockquote></details>

Good point. Done.
___
*[pkg/cli/cliflags/flags.go, line 1311 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/64128#-MZCChSsDpJl1m-Ra---:-MZCs3PQ2Abj1ofRAWl4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/583c6aa27e747ebd5ca4949f2f31680111027fa0/pkg/cli/cliflags/flags.go#L1311)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Intuitively clear, but it might be worth spelling out that exclusion overrides inclusion, i.e. including `*.log` and then excluding `*foo*.log` will exclude `barfoos.log`.
</blockquote></details>

Done.

**Review by tbg — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64128)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @nickelnickel, and @stevendanna)

___
*[pkg/cli/zip_per_node.go, line 306 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/64128#-MZCBkP0DE27kjMEXDCp:-MZDKl746mT3RRL6Eq_8:b-4jtix6) ([raw file](https://github.com/cockroachdb/cockroach/blob/583c6aa27e747ebd5ca4949f2f31680111027fa0/pkg/cli/zip_per_node.go#L306)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Before we had:
- time cost, per node: 1 x roundtrip + #totalsize / bandwidth.
- space cost, per node: #totalsize  (the entire file contents were accumulated in RAM in one response)

Now we have:
- time cost, per node: #files x roundtrip + #totalsize / bandwidth
- space cost, per node: max(#1filesize)

Notice how the time cost involves transmitting the bytes over the network.  We have relatively few files (less than hundreds)  but  many bytes to transmit (dozens of megabytes). The transmission dominates, so I believe we can neglect the roundtrip cost.

> request a specific list of files to get back to two round-trips which will always be ok.

No it is not OK, we actually had a known issue with that (even though it wasn't filed), which is that all the file contents are loaded up in RAM in one response--this can increase the risk of OOM crashes.

The current code is strictly better as it loads only 1 file at a time in responses.

Added a comment to explain.

</blockquote></details>

Thank you, makes sense to me.

**Review by tbg — APPROVED** [review]

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64128)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @nickelnickel, @stevendanna, and @tbg)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/64128#-MYyuxfE1YMRlzI7HRxY:-MZDZUczD0wudEnKqFSw:bguhm2j) (no related file):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Processing the first batch of comments, which really belong to the prefix PR  #64094.
</blockquote></details>

Coming back to the idea of showing a message to the user:

- I have implemented this logic in a different PR #64210
- I wonder how much useful this will be in practice. As you recall with this PR (#64128) the command will now narrow down the amount of data to just the last 48 hours. Hopefully, the amount of data will already be limited thanks to this new default. If the user gets a message from PR #64210, what can they do with this?
(Feel free to continue this conversation on that other PR instead)


I plan to merge this one after it passes CI.

---
___
*[pkg/cli/context.go, line 352 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/64128#-MZC9vN86nUG4V73RDYQ:-MZCstXq5cfDkgLX-tQj:b-qu6n94) ([raw file](https://github.com/cockroachdb/cockroach/blob/583c6aa27e747ebd5ca4949f2f31680111027fa0/pkg/cli/context.go#L352)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Shouldn't this be "infinity"? We wouldn't want to exclude a current file based on some delay passing between when `now()` is chosen on the client and the server receives the request.
</blockquote></details>

Good point. Done.
___
*[pkg/cli/zip_helpers.go, line 324 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64128#-MYypKP66XfZkiYQBUJy:-MZCtWvjBLMmt7rR_vU7:b5u2s8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa49de2549fd2cf99ec75896526d995313cfa914/pkg/cli/zip_helpers.go#L324)):*
Oh sorry I misread!

> Is there much advantage to this over [...]

it's a general instinct I have: I don't know whether the method is implemented by reference or by value, and if it happens to be implemented by reference, the by-value cast wouldn't work. This one is guaranteed to work.

**Comment by knz** [comment]
TFYR - deferring the discussion of notifications to #64210

bors r=tbg,stevendanna

**Comment by knz** [comment]
bors crashed, have to queue again

bors r=tbg,stevendanna

**Pull request merged**
