### PR TITLE
kvclient: rework range cache retries

### PR DESCRIPTION
**Pull request by andreimatei**
The range cache coalesces lookups to do fewer trips to the database.
Sometimes it coalesces keys that end up being in different descriptors,
in which case one of the lookups needs to be retried. Before this patch
the retry was external to the cache. It didn't make sense for callers to
deal with it though, so this patch internalizes the handling of these
retries.

In the process, the lookup interface is cleaned up. It used to take a
waitgroup with very weird semantics for testing. That became untenable
with the retries, so it's gone.

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48604)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 1867 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48604#-M790IRT5lV4YNRNbkBW:-M790IRT5lV4YNRNbkBX:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/650e37ba92a6ffcc15705acaadc59ee91c24ec6e/pkg/kv/kvclient/kvcoord/dist_sender.go#L1867)):*
> ```Go
> 		ds.metrics.NextReplicaErrCount.Inc(1)
> 		curReplica = transport.NextReplica()
> 		log.VEventf(ctx, 2, "error: %v %v; trying next peer %s", br, err, curReplica.String())
> ```

:thumbsup: 
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 522 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48604#-M790cFf-tNRyE1sQ1qr:-M790cFf-tNRyE1sQ1qs:b5b05n3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c552117c2a35e45e4c11bd6a8b9ed7893e7e73a5/pkg/kv/kvclient/kvcoord/dist_sender.go#L522)):*
> ```Go
> 	}
> 
> 	// Sanity check: the descriptor we're about to return must include the key
> ```

Did you ever see this fire?
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48604#-M78wi_O4LYrzGp3fStn:-M78wi_O4LYrzGp3fSto:b1m8n06) ([raw file](https://github.com/cockroachdb/cockroach/blob/650e37ba92a6ffcc15705acaadc59ee91c24ec6e/pkg/kv/kvclient/kvcoord/range_cache.go#L308)):*
> ```Go
> 			return nil, nil, err
> 		}
> 		return desc, newToken, err
> ```

`return desc, newToken, nil`
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 319 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48604#-M78x2mfA9DS05Y7j3my:-M78x2mfA9DS05Y7j3mz:bjzfsh9) ([raw file](https://github.com/cockroachdb/cockroach/blob/650e37ba92a6ffcc15705acaadc59ee91c24ec6e/pkg/kv/kvclient/kvcoord/range_cache.go#L319)):*
> ```Go
> // should be retried.
> type lookupCoalescingError struct {
> 	key  roachpb.RKey
> ```

Neither of these fields are very clear. Are they our key and descriptor or the incorrect ones from the request we got grouped in with? I think it's our key and the incorrect descriptor. If so, consider renaming `desc` to `wrongDesc`.
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48604#-M78wP8m1d9xZmjydwJj:-M78wP8m1d9xZmjydwJk:byexa5) ([raw file](https://github.com/cockroachdb/cockroach/blob/650e37ba92a6ffcc15705acaadc59ee91c24ec6e/pkg/kv/kvclient/kvcoord/range_cache.go#L335)):*
> ```Go
> }
> 
> func (rdc *RangeDescriptorCache) lookupRangeDescriptorInner(
> ```

Let's name this something more desciptive. We now have a `lookupRangeDescriptorInternal` and a `lookupRangeDescriptorInner`. Maybe `tryLookupRangeDescriptor` or something. Also, give it a comment about why it can fail.
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 468 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48604#-M78xsXM1rL0nyKMAH8B:-M78xsXM1rL0nyKMAH8C:bbqw43w) ([raw file](https://github.com/cockroachdb/cockroach/blob/650e37ba92a6ffcc15705acaadc59ee91c24ec6e/pkg/kv/kvclient/kvcoord/range_cache.go#L468)):*
> ```Go
> 			containsFn = (*roachpb.RangeDescriptor).ContainsKeyInverted
> 		}
> 		// We might get a descriptor that doesn't contain the key we're looking for
> ```

Isn't this saying the same thing as the previous comment (which now looks incorrect)? Maybe merge them?
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 470 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48604#-M78y62n-LjzNIT7VyhV:-M78y62n-LjzNIT7VyhW:b-o3qify) ([raw file](https://github.com/cockroachdb/cockroach/blob/650e37ba92a6ffcc15705acaadc59ee91c24ec6e/pkg/kv/kvclient/kvcoord/range_cache.go#L470)):*
> ```
> as ; in
> ```
Something's off here.
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48604#-M78yo7z7feskHeHvzRX:-M78yo7z7feskHeHvzRY:be1tlwo) ([raw file](https://github.com/cockroachdb/cockroach/blob/650e37ba92a6ffcc15705acaadc59ee91c24ec6e/pkg/kv/kvclient/kvcoord/range_cache.go#L478)):*
> ```Go
> 		// original lookup.
> 		if !containsFn(desc, key) {
> 			return nil, nil, newLookupCoalescingError(key, *desc)
> ```

nit: why copy `desc`? It should be immutable.
___
*[pkg/kv/kvclient/kvcoord/range_cache_test.go, line 735 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48604#-M79-EeRCpzXkLZeHfny:-M79-EeRCpzXkLZeHfnz:bds3i29) ([raw file](https://github.com/cockroachdb/cockroach/blob/650e37ba92a6ffcc15705acaadc59ee91c24ec6e/pkg/kv/kvclient/kvcoord/range_cache_test.go#L735)):*
> ```Go
> // retried internally because they've been wrongly-coalesced the first time
> // around.
> func TestRangeCacheHandleDoubleSplit(t *testing.T) {
> ```

Nice test!
___
*[pkg/kv/kvclient/kvcoord/range_iter.go, line 183 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48604#-M7915l42LybujTRy794:-M7915l42LybujTRy795:bl6zo9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/298ef0ea16314ed5307088470f159ef2b25385c3/pkg/kv/kvclient/kvcoord/range_iter.go#L183)):*
> ```Go
> 		// We evict and retry in such a case.
> 		// TODO: this code is subject to removal. See
> 		// https://groups.google.com/d/msg/cockroach-db/DebjQEgU9r4/_OhMe7atFQAJ
> ```

I don't remember this discussion at all, but I'm happy to see this go.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48604)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 522 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48604#-M790cFf-tNRyE1sQ1qr:-M799tlK5sODjUqCJITh:bb7lgjf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c552117c2a35e45e4c11bd6a8b9ed7893e7e73a5/pkg/kv/kvclient/kvcoord/dist_sender.go#L522)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did you ever see this fire?
</blockquote></details>

nope
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48604#-M78wi_O4LYrzGp3fStn:-M7938_CB-ticcRTkYgz:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/650e37ba92a6ffcc15705acaadc59ee91c24ec6e/pkg/kv/kvclient/kvcoord/range_cache.go#L308)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`return desc, newToken, nil`
</blockquote></details>

done
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 319 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48604#-M78x2mfA9DS05Y7j3my:-M794EDg4W1Kt66jxxeb:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/650e37ba92a6ffcc15705acaadc59ee91c24ec6e/pkg/kv/kvclient/kvcoord/range_cache.go#L319)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Neither of these fields are very clear. Are they our key and descriptor or the incorrect ones from the request we got grouped in with? I think it's our key and the incorrect descriptor. If so, consider renaming `desc` to `wrongDesc`.
</blockquote></details>

done
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48604#-M78wP8m1d9xZmjydwJj:-M794Tte9t7dZIAMlu_l:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/650e37ba92a6ffcc15705acaadc59ee91c24ec6e/pkg/kv/kvclient/kvcoord/range_cache.go#L335)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's name this something more desciptive. We now have a `lookupRangeDescriptorInternal` and a `lookupRangeDescriptorInner`. Maybe `tryLookupRangeDescriptor` or something. Also, give it a comment about why it can fail.
</blockquote></details>

done
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 468 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48604#-M78xsXM1rL0nyKMAH8B:-M795PxC4GkX-1nVMZ7h:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/650e37ba92a6ffcc15705acaadc59ee91c24ec6e/pkg/kv/kvclient/kvcoord/range_cache.go#L468)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Isn't this saying the same thing as the previous comment (which now looks incorrect)? Maybe merge them?
</blockquote></details>

done
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 470 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48604#-M78y62n-LjzNIT7VyhV:-M795hRaDS0p1TLLI1rP:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/650e37ba92a6ffcc15705acaadc59ee91c24ec6e/pkg/kv/kvclient/kvcoord/range_cache.go#L470)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> as ; in
> ```
Something's off here.
</blockquote></details>

done
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48604#-M78yo7z7feskHeHvzRX:-M799eLqDmJu6IxTi9Wx:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/650e37ba92a6ffcc15705acaadc59ee91c24ec6e/pkg/kv/kvclient/kvcoord/range_cache.go#L478)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: why copy `desc`? It should be immutable.
</blockquote></details>

done
___
*[pkg/kv/kvclient/kvcoord/range_iter.go, line 183 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48604#-M7915l42LybujTRy794:-M793L-xDZqxuRck-HlR:b-5zdaz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/298ef0ea16314ed5307088470f159ef2b25385c3/pkg/kv/kvclient/kvcoord/range_iter.go#L183)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I don't remember this discussion at all, but I'm happy to see this go.
</blockquote></details>

hey, it did say it was "subject to removal"

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48604#-:-M79Gz089dfaj7LUBiC3:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48604#-M78wP8m1d9xZmjydwJj:-M79GlIYEcS5u1AvnHy2:b-35znb8) ([raw file](https://github.com/cockroachdb/cockroach/blob/650e37ba92a6ffcc15705acaadc59ee91c24ec6e/pkg/kv/kvclient/kvcoord/range_cache.go#L335)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

done
</blockquote></details>

I still wouldn't mix "internal" and "inner".
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 335 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/48604#-M79GqaT0HUgoWptIVYb:-M79GqaT0HUgoWptIVYc:b-7b8tho) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7ba4a4200634a266e2f7a1565fc4ec121a6144e/pkg/kv/kvclient/kvcoord/range_cache.go#L335)):*
> ```Go
> }
> 
> // tryLookupRangeDescriptorInner can return lookupCoalescingError.
> ```

"return a"

**Review by andreimatei — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48604#-:-M79XtNh1iLtOZk5FvxJ:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48604#-M78wP8m1d9xZmjydwJj:-M79U8SWCBJVrnlctN3A:bthr8u6) ([raw file](https://github.com/cockroachdb/cockroach/blob/650e37ba92a6ffcc15705acaadc59ee91c24ec6e/pkg/kv/kvclient/kvcoord/range_cache.go#L335)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I still wouldn't mix "internal" and "inner".
</blockquote></details>

got rid of the `inner`
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 335 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/48604#-M79GqaT0HUgoWptIVYb:-M79UDgrEYeq-SiYz4aU:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7ba4a4200634a266e2f7a1565fc4ec121a6144e/pkg/kv/kvclient/kvcoord/range_cache.go#L335)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"return a"
</blockquote></details>

done

**Pull request merged**
