### PR TITLE
rfcs: Repairing SQL errors

### PR DESCRIPTION
**Pull request by lgo**
This RFC proposes methods to repair SQL data errors that have been
detected by the [SCRUB command][scrub command rfc]. The primary goal of
the repair process is to bring the database into a usable state, which
may not have been possible in some situations prior to this RFC.

The command, the errors being repaired, and the strategy for repairing
are discussed in this RFC. The strategy for repair suggested which
matches the motivations consists of directly deleting bad data from the
database.

[scrub command rfc]: 20171025_scrub_sql_consistency_check_command.md

### CODE REVIEW

**Comment by justinj** [comment]
I have no substantial comments but was a very good read!

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/repairing_sql_errors.md, line 31 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20293#-L--BFpPcf1V3m2mf0Jn:-L--BFpPcf1V3m2mf0Jo:b-rm8k70) ([raw file](https://github.com/cockroachdb/cockroach/blob/093784c15531b6f62b1e1689628bf6137a8409ae/docs/RFCS/repairing_sql_errors.md#L31)):*
> ```Markdown
> 
> Not only do we need to find errors, but we need to resolve them. This is
> crucial for disaster recovery where errors may cause data may become
> ```

nit: `data to become`

---

*[docs/RFCS/repairing_sql_errors.md, line 217 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20293#-L--CjSTxBtp12YXdUVV:-L--CjSTxBtp12YXdUVW:bygw11n) ([raw file](https://github.com/cockroachdb/cockroach/blob/093784c15531b6f62b1e1689628bf6137a8409ae/docs/RFCS/repairing_sql_errors.md#L217)):*
> ```Markdown
> For the cases 1 and 2 the primary index data will be correct, so it is
> safe to delete the secondary index entry. It should be noted that the
> index may still not correct after deleting the entry, as a new entry
> ```

`not be correct`

---

*[docs/RFCS/repairing_sql_errors.md, line 312 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20293#-L--DV7KaHUL2U6-8U_I:-L--DV7KaHUL2U6-8U_J:bkms0s7) ([raw file](https://github.com/cockroachdb/cockroach/blob/093784c15531b6f62b1e1689628bf6137a8409ae/docs/RFCS/repairing_sql_errors.md#L312)):*
> ```Markdown
> 
> As for implementing this alternative, it would be possible with a system
> table, `quarantine`, and a reserved key space, `/Qaurantine/` for
> ```

`Quarantine`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20293#-:-L--EDOEh9abP-T5i3bc:bm9gqpy)*

**Comment by jordanlewis** [comment]
Just grammar things - this looks good!

---

Review status: 0 of 2 files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/repairing_sql_errors.md, line 17 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20293#-L-2DvBtU8jdSUk-6Rxd:-L-2DvBtU8jdSUk-6Rxe:b3lf0hk) ([raw file](https://github.com/cockroachdb/cockroach/blob/093784c15531b6f62b1e1689628bf6137a8409ae/docs/RFCS/repairing_sql_errors.md#L17)):*
> ```Markdown
> 
> The command, the errors being repaired, and the strategy for repairing
> are discussed in this RFC. The strategy for repair suggested which
> ```

I can't understand this sentence - can you try to clarify it?

---

*[docs/RFCS/repairing_sql_errors.md, line 26 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20293#-L-2EGsrz4CZK3a0gjrP:-L-2EGsrz4CZK3a0gjrQ:bgilpja) ([raw file](https://github.com/cockroachdb/cockroach/blob/093784c15531b6f62b1e1689628bf6137a8409ae/docs/RFCS/repairing_sql_errors.md#L26)):*
> ```Markdown
> # Motivation
> 
> Several data errors can happen during the lifetime of the database and
> ```

`Several types of data error` would be more clear I think. And consider splitting this into 2 sentences: `Several types of data error can happen during the lifetime of the database. While rare, they're bound to happen.`

---

*[docs/RFCS/repairing_sql_errors.md, line 30 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20293#-L-2EzTwBIlMkIB6SZtU:-L-2EzTwBIlMkIB6SZtV:be5oif1) ([raw file](https://github.com/cockroachdb/cockroach/blob/093784c15531b6f62b1e1689628bf6137a8409ae/docs/RFCS/repairing_sql_errors.md#L30)):*
> ```Markdown
> the [scrub command RFC motivation section][scrub_command_rfc#motivation].
> 
> Not only do we need to find errors, but we need to resolve them. This is
> ```

maybe "It's not sufficient to only find errors; we also need to resolve them."

---

*[docs/RFCS/repairing_sql_errors.md, line 34 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20293#-L-2FLiYHYrIQOK15Nw6:-L-2FLiYHYrIQOK15Nw7:b19qfcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/093784c15531b6f62b1e1689628bf6137a8409ae/docs/RFCS/repairing_sql_errors.md#L34)):*
> ```Markdown
> inaccessible. Correctness issues may also surface as a result of errors.
> 
> For example, if a non-nullable column has a NULL value the database will
> ```

comma after`value`

---

*[docs/RFCS/repairing_sql_errors.md, line 36 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20293#-L-2FPSotCRnLcrHBR1j:-L-2FPSotCRnLcrHBR1k:bifrfbh) ([raw file](https://github.com/cockroachdb/cockroach/blob/093784c15531b6f62b1e1689628bf6137a8409ae/docs/RFCS/repairing_sql_errors.md#L36)):*
> ```Markdown
> For example, if a non-nullable column has a NULL value the database will
> abort the scanning process immediately upon encountering it. This makes
> it difficult to do any database-wide operation that scans that row. Also
> ```

comma after 'Also'

---

*[docs/RFCS/repairing_sql_errors.md, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20293#-L-2FTB-F_wBzJrubZ9t:-L-2FTB-F_wBzJrubZ9u:b-wk54c6) ([raw file](https://github.com/cockroachdb/cockroach/blob/093784c15531b6f62b1e1689628bf6137a8409ae/docs/RFCS/repairing_sql_errors.md#L41)):*
> ```Markdown
> provide a way to avoid certain keys, such as backup.
> 
> This leads to the core motivations for this RFC which is to repair
> ```

plural agreement - motivations vs is

---

*[docs/RFCS/repairing_sql_errors.md, line 45 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20293#-L-2LcUQJ2kpL7pzDCJD:-L-2LcUQJ2kpL7pzDCJE:b-uktj61) ([raw file](https://github.com/cockroachdb/cockroach/blob/093784c15531b6f62b1e1689628bf6137a8409ae/docs/RFCS/repairing_sql_errors.md#L45)):*
> ```Markdown
> problems are because of correctness problems or being unable to access
> data, if it was caused by a data error then scrub is responsible for
> detecting it and repairing.
> ```

I think you need another "it" at the end to keep the sentence nicely parallel.

---

*[docs/RFCS/repairing_sql_errors.md, line 278 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20293#-L-2MTrCZnhwkho29DKI:-L-2MTrCZnhwkho29DKJ:b9oza8j) ([raw file](https://github.com/cockroachdb/cockroach/blob/093784c15531b6f62b1e1689628bf6137a8409ae/docs/RFCS/repairing_sql_errors.md#L278)):*
> ```Markdown
> 
> While data loss may occur, this repair process does ensure all data that
> is removed will be appropriately logged and reported so that an operator
> ```

This seems fine as long as there's a mode of operation that logs exactly the same stuff but doesn't actually delete the data yet. A dry run. Does scrub report these same errors?

---

*[docs/RFCS/repairing_sql_errors.md, line 367 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20293#-L-2PIdCcem1tDn5za-R:-L-2PIdCcem1tDn5za-S:b3swnbw) ([raw file](https://github.com/cockroachdb/cockroach/blob/093784c15531b6f62b1e1689628bf6137a8409ae/docs/RFCS/repairing_sql_errors.md#L367)):*
> ```Markdown
> do all of that within the same transaction as scrub repairs.
> 
> Is this something that seems possible, if it is not already?
> ```

Seems unlikely to work - this transaction might be super long!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20293#-:-L-2Pb_iYQeQWNkDI2tw:b-wgtuas)*

**Comment by jordanlewis** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20293)*

**Comment by BramGruneir** [comment]
With any of these repairs where values are deleted, what if the there are dangling foreign key references to other tables?  Will this delete fail?

And how will these repairs interact with https://github.com/cockroachdb/cockroach/pull/19570?  Will a delete cascade to other updates and/or deletes?

**Comment by knz** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/repairing_sql_errors.md, line 47 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20293#-L-2SdVgiSPRl8-9Mf-S:-L-2SdVhDEwaFN6kOPSH:b-sdivhf) ([raw file](https://github.com/cockroachdb/cockroach/blob/093784c15531b6f62b1e1689628bf6137a8409ae/docs/RFCS/repairing_sql_errors.md#L47)):*
> ```Markdown
> detecting it and repairing.
> 
> The first strategy for repairing data is where any bad data is fixed, if
> ```

I don't understand the first sentence in this paragraph. Please rephrase.

---

*[docs/RFCS/repairing_sql_errors.md, line 271 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20293#-L-2ZuqY5elk6JyTW-gF:-L-2ZuqZ1WftuTN8X97m:b64kvb7) ([raw file](https://github.com/cockroachdb/cockroach/blob/093784c15531b6f62b1e1689628bf6137a8409ae/docs/RFCS/repairing_sql_errors.md#L271)):*
> ```Markdown
> chosen for dealing with errors as it solves the key motivation, bringing
> the database into a correct and usable state, even if it results in data
> loss.
> ```

I don't agree this is a good strategy. If the data was supposed to be there because it was inserted as part of an atomic transaction that was inserting other items in other places (including other tables), it would be a consistency violation to delete that item and not the related data. And I'm not just talking about FK relationships here -- not all related data is explicitly related via FKs.
The same argument can be made the other way (if we were to repair by keeping the data and make it consistent, this would cause inconsistencies wrt atomic txns performing multiple deletes).

This tells me that having a feature that blindly applies either strategy is probably not a good idea.

I'd rather have the SCRUB statement without "REPAIR" produce a list of results *formatted as a list of possible fixup / delete operators* (a sort of change list), then let the operator manually edit their list of fixup/delete actions, then feed that list back to a separate REPAIR statement/option. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20293)*

**Comment by knz** [comment]
Also missing: the repairs will be done at a "current" timestamp. This means that the data is still corrupted for any AS OF SYSTEM TIME queries. I wonder if this is OK.

---

Review status: all files reviewed at latest revision, 14 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20293#-:-L-2ajGsjix7FFfskJIb:bigw1e6)*

**Comment by vivekmenezes** [comment]
@lego we need to discuss this because you're not going to have the time to implement this. I'd like to explore merging this in with status draft as a possible outcome of this RFC. This will allow someone to reopen it and bring it up to the level of a proposal and implement it. Is everyone okay with that? Thanks!

**Comment by lego** [comment]
@BramGruneir thanks for bringing that up.

I can't give a satisfying answer for how the main strategy mentioned will work with that. At best, if deletes are done through the SQL client, I would assume the violations would bubble up from there (which is not what we want). At worst, we go through the KV client to directly delete keys which will violate a lot of assumptions there. 

It is clear there will need to be a lot more thought here about how modifications will work. Going to think about this more with the alternative @knz mentioned.


@vivekmenezes I'm fine with having this RFC stay as a draft, as there is lots of room to over extend the scope of this. I would be happier if we can reach a conclusion on a draft that can answer the motivations.

Sure, scrub can help diagnose issues. Heck, it can be useful as a debugging tool for diagnosing SQL issues that is always run first. What it is really lacking though is a way to address many of the possible issues. A few of the problems cannot be fixed with just SQL: broken indexes and bad keys (encoding). (For what it's worth, everything else can be done via. a `DELETE` I believe.)

As far as implementation goes, this isn't too difficult. It's about doing it right -- but I also don't think this needs to be right the first time.

---

Review status: 1 of 2 files reviewed at latest revision, 14 unresolved discussions, some commit checks pending.

---

*[docs/RFCS/repairing_sql_errors.md, line 271 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20293#-L-2ZuqY5elk6JyTW-gF:-L-36I-LbDC7O_th-Ino:btmgteu) ([raw file](https://github.com/cockroachdb/cockroach/blob/093784c15531b6f62b1e1689628bf6137a8409ae/docs/RFCS/repairing_sql_errors.md#L271)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't agree this is a good strategy. If the data was supposed to be there because it was inserted as part of an atomic transaction that was inserting other items in other places (including other tables), it would be a consistency violation to delete that item and not the related data. And I'm not just talking about FK relationships here -- not all related data is explicitly related via FKs.
The same argument can be made the other way (if we were to repair by keeping the data and make it consistent, this would cause inconsistencies wrt atomic txns performing multiple deletes).

This tells me that having a feature that blindly applies either strategy is probably not a good idea.

I'd rather have the SCRUB statement without "REPAIR" produce a list of results *formatted as a list of possible fixup / delete operators* (a sort of change list), then let the operator manually edit their list of fixup/delete actions, then feed that list back to a separate REPAIR statement/option. 


</blockquote></details>

@knz great suggestion about repair presenting a "change list" the operator can act on.

I really like this because it gives complete control of decisions to the operator. It also answers the question in the RFC about allowing repair to happen in the same transaction. This makes it very easy to do it and also has failure handling (i.e. human response).

The focus of repair will need to change because this gives control to the operator. It will be very important to have documentation describing what they need to do, what they should do, and what they should be aware of. I see this document as a good start for that.

A smaller problem I see with this is if the error was temporary. Before, repair done by scrub will be able to do all changes in the same transaction where the errors were detected. After, the problems could have already been "resolved". 

In order to do this at all though, we will need to have an answer for fixing errors that can't be fixed via. SQL commands (as mentioned in the comment at the top). The only ones I can think of are broken indexes or bad keys. Other errors which come close to this are NULL in non-nullable columns and bad value encoding as these won't be readable, but they can be deleted directly (as far as I know, I might be wrong).

As a suggestion (albeit, not a great one), we could introduce a scrub repair command to fix these _specific_ issues. This is in the case that we don't have any other way a user can fix these issues since I don't have a better suggestion. For example:

```sql
# This will delete any dangling index references or generate a missing index reference, which cannot be repaired otherwise.
SCRUB REPAIR INDEX <index_name> VALUES (<value>...)

# This will remove a bad key that cannot be deleted otherwise.
SCRUB REPAIR DELETE KEY 'some/key/string'
```

(Deleting keys directly seems extremely risky. But if these are only suggested operations, this should be _okay_?)


I will be a lot more satisfied with this strategy once if there is an answer for that problem that we agree on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20293#-:-L-36EF65YBHrw5hWN5H:b-e4srwt)*

**Comment by vivekmenezes** [comment]
I'm happy to have you merge this in as a draft. Thanks for thinking through this.

**Comment by lego** [comment]
I've pushed up amendments, adding the alternative @knz suggested. This alternative seems like the right way to go, but I haven't changed the entirety of the RFC for this yet (due to the lack of discussion on it so far). LMK if this is fine to merge as is @vivekmenezes :)

---

Review status: 0 of 2 files reviewed at latest revision, 14 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20293#-:-L0GRk3zblR1enK3Nov-:b-htfa5s)*

**Review by knz — COMMENTED** [review]
I rebased this after incorporating the latest discussion.

Even though the work has not been implemented yet, this discussion is a valuable addition to our RFC directory. Merging as-is.

bors r=jordanlewis,knz

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/20293#-:-M_52zeNAngE9NFmEuL6:b-9xauvd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @justinj, @knz, and @vivekmenezes)

___
*[docs/RFCS/repairing_sql_errors.md, line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/20293#-L-2ZuqY5elk6JyTW-gF:-M_52u_Z6t0FjXw1BJ5v:b-qlvk7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/093784c15531b6f62b1e1689628bf6137a8409ae/docs/RFCS/repairing_sql_errors.md#L271)):*
<details><summary><i>Previously, lgo (Joey Pereira) wrote…</i></summary><blockquote>

@knz great suggestion about repair presenting a "change list" the operator can act on.

I really like this because it gives complete control of decisions to the operator. It also answers the question in the RFC about allowing repair to happen in the same transaction. This makes it very easy to do it and also has failure handling (i.e. human response).

The focus of repair will need to change because this gives control to the operator. It will be very important to have documentation describing what they need to do, what they should do, and what they should be aware of. I see this document as a good start for that.

A smaller problem I see with this is if the error was temporary. Before, repair done by scrub will be able to do all changes in the same transaction where the errors were detected. After, the problems could have already been "resolved". 

In order to do this at all though, we will need to have an answer for fixing errors that can't be fixed via. SQL commands (as mentioned in the comment at the top). The only ones I can think of are broken indexes or bad keys. Other errors which come close to this are NULL in non-nullable columns and bad value encoding as these won't be readable, but they can be deleted directly (as far as I know, I might be wrong).

As a suggestion (albeit, not a great one), we could introduce a scrub repair command to fix these _specific_ issues. This is in the case that we don't have any other way a user can fix these issues since I don't have a better suggestion. For example:

```sql
# This will delete any dangling index references or generate a missing index reference, which cannot be repaired otherwise.
SCRUB REPAIR INDEX <index_name> VALUES (<value>...)

# This will remove a bad key that cannot be deleted otherwise.
SCRUB REPAIR DELETE KEY 'some/key/string'
```

(Deleting keys directly seems extremely risky. But if these are only suggested operations, this should be _okay_?)


I will be a lot more satisfied with this strategy once if there is an answer for that problem that we agree on.
</blockquote></details>

Added this discussion as an unresolved question at the end.

**Comment by knz** [comment]
flaking on #58488 - retrying

bors r=jordanlewis,knz

**Pull request merged**
