### PR TITLE
timeutil: misc cleanups

### PR DESCRIPTION
**Pull request by andreimatei**
These are all the commits from #71355 except the more important (but also more controversial) one.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72666#-:-MoHjmLZ47cCBY52T3UC:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72666#-:-MoJqHrv6knl4Lkgzyae:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72666)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/testutils/lint/lint_test.go, line 776 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72666#-MoK3R0DE1WxWNjOq-gK:-MoK3R0DE1WxWNjOq-gL:b-buea1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab6dc85f664da1344a5aa59dd49aa7c74d20ccef/pkg/testutils/lint/lint_test.go#L776)):*
> ```Go
> 
> 		if err := stream.ForEach(filter, func(s string) {
> 			t.Errorf("\n%s <- forbidden; use 'timeutil.Since() or timeutil.Since()' instead "+
> ```

nit: something is off in "timeutil.Since() or timeutil.Since()".

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72666)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/testutils/lint/lint_test.go, line 776 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72666#-MoK3R0DE1WxWNjOq-gK:-MoK4xqHC9ggc8qt9MWl:bvoqixj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab6dc85f664da1344a5aa59dd49aa7c74d20ccef/pkg/testutils/lint/lint_test.go#L776)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: something is off in "timeutil.Since() or timeutil.Since()".
</blockquote></details>

Oops, I don't know what I wanted here. https://github.com/cockroachdb/cockroach/pull/72691

**Pull request merged**
