### PR TITLE
sqlinstance: add sql_addr field to instances table

### LINKED ISSUE #76175: sqlinstance: Split InstanceAddr field into SQL and RPC address.
We need to support separate fields for storing SQL and RPC address within the `sqlinstance` subsystem. We need this for unification of single tenant and multi-tenant architectures. This will require updating the `sql_instance` system table with a new field for storing RPC address. We will also need to update the `sqlinstance` interface to return a separate address for SQL and RPC.

Jira issue: CRDB-13011

Epic CRDB-18407

### PR DESCRIPTION
**Pull request by dhartunian**
Previously, there was only a single address stored per tenant in the `sql_instances` table. This made it difficult to differentiate between a gRPC and SQL address. This change treats the existing `addr` as a gRPC address, and adds a `sql_addr` column to the table. This column is populated with the SQL address of the node, and if it's missing the sql instance in-memory representation will use the `addr` field for both gRPC and SQL for backwards compatibility.

Resolves: #76175

Release note: None
Epic: CRDB-18407

### CODE REVIEW

**Review by aadityasondhi — APPROVED** [review]
:lgtm: thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94630#-:-NL1MI1IBfK9OmAtRwYR:brfqlux)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, @knz, @renatolabs, and @smg260)

___
*[`pkg/server/fanout_clients.go` line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94630#-NL1JJVuCf0HFiv7AMU5:-NL1JJVuCf0HFiv7AMU6:baf5dnv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0e80224069968fb91d39e7c2bbcd0261b9040c7/pkg/server/fanout_clients.go#L120)):*
> ```Go
> }
> 
> // TODO(davidh): This implementation is incorrect and should be fixed
> ```

Can we remove this TODO comment since this commit resolves that issue?

**Review by knz — APPROVED** [review]
:lgtm: thank you!!

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94630#-:-NL1PWBn3rA8PnBim1t6:b5d8k56)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, @renatolabs, and @smg260)

**Comment by knz** [comment]
Merging; I need this as a prereq to make progress on #92580.

bors r=knz,aadityasondhi a=dhartunian

**Comment by knz** [comment]
unrelated flake #94738; skipping.

**Comment by knz** [comment]
bors r=knz,aadityasondhi a=dhartunian

**Pull request merged**
