### PR TITLE
 opt: support SHOW GRANTS

### PR DESCRIPTION
**Pull request by RaduBerinde**
The first commit rewrites `expandTableGlob` to use the catalog. The second commit moves the ShowGrants implementation to `delegate`.

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37049#-:-LdKNgh_9py5X2X1JGcS:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz, @RaduBerinde, and @rytaft)

___
*[pkg/sql/plan.go, line 695 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37049#-LdKNkNsDIRqIfUTN5JF:-LdKNkNsDIRqIfUTN5JG:b-bfdl3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/7aa40205c6399b04ee471135744322a95775d50a/pkg/sql/plan.go#L695)):*
> ```Go
> 	case *tree.ShowVar:
> 		return p.ShowVar(ctx, n)
> 	case *tree.ShowGrants:
> ```

Are these not accessible from the HP at all anymore?
___
*[pkg/sql/opt/cat/utils.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37049#-LdKNKGP-78vx9QbfJ-C:-LdKNKGQAk3f187WXdzI:bxqvv28) ([raw file](https://github.com/cockroachdb/cockroach/blob/25a6f4b75c87a141839100bcdfdc949fc416bc48/pkg/sql/opt/cat/utils.go#L1)):*
> ```Go
> // Copyright 2018 The Cockroach Authors.
> ```

nit: 2019

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37049#-:-LdKOVsq5RxcNzf_umdu:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @knz, and @rytaft)

___
*[pkg/sql/plan.go, line 695 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37049#-LdKNkNsDIRqIfUTN5JF:-LdKOPmsE90bRICUvh_G:baxiufo) ([raw file](https://github.com/cockroachdb/cockroach/blob/7aa40205c6399b04ee471135744322a95775d50a/pkg/sql/plan.go#L695)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Are these not accessible from the HP at all anymore?
</blockquote></details>

They are, using the new code, see the call below to `delegate.TryDelegate`.

**Comment by RaduBerinde** [comment]
Lint OOM 2 - 0 Radu

bors r+

**Comment by RaduBerinde** [comment]
Filed #37162 for a TestLatchManager failure.

bors r+

**Pull request merged**
