### PR TITLE
cli/sql: add some additional client-side commands

### LINKED ISSUE #25178: cli: running commands from an SQL file should be easier
As pointed out by a [post on the forum](https://forum.cockroachlabs.com/t/running-cockroachdb-commands-in-file-from-cli/1572), it's not as straightforward as it should be to run SQL commands from a file when using the CLI.  Currently, users must run:

```
> \| cat file.sql
```

It seems like there should be some meta command to run the SQL file directly without using `cat`.

### PR DESCRIPTION
**Pull request by knz**
Fixes  #25178 
Supports use cases promoted by  #54771 

Adds `\p`, `\r` `\echo` and especially `\i` / `\ir` (recursive include).

### CODE REVIEW

**Review by otan — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 7 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @knz)

___
*[pkg/cli/sql.go, line 1050 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/54796#-MIKCMXIACdw7JQDccx0:-MIKCMXIACdw7JQDccx1:b-3c4ukp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e98854e8d99373d942707ddd4ff28ce9a98db5d9/pkg/cli/sql.go#L1050)):*
> ```Go
> 		return c.runSyscmd(c.lastInputLine, loopState, errState)
> 
> 	case `\i`:
> ```

looks like `\ir` may be a cool follow up.
___
*[pkg/cli/sql.go, line 1124 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/54796#-MIKBq5904Xjd1X-2fhZ:-MIKBq5904Xjd1X-2fh_:b-8dua1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/e98854e8d99373d942707ddd4ff28ce9a98db5d9/pkg/cli/sql.go#L1124)):*
> ```Go
> const maxRecursionLevels = 10
> 
> func (c *cliState) runRecursive(
> ```

nit: had a bit of trouble understanding what this function did. maybe `importCLICommandFile`? the recursion concept is not evident here because this function doesn't actually do any recursion.
___
*[pkg/cli/sql.go, line 1132 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/54796#-MIKBBxXDPk7RKdsY5-D:-MIKBBxXDPk7RKdsY5-E:b-elypf3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e98854e8d99373d942707ddd4ff28ce9a98db5d9/pkg/cli/sql.go#L1132)):*
> ```Go
> 
> 	if c.levels >= maxRecursionLevels {
> 		c.exitErr = errors.New(`\i: too many recursion levels`)
> ```

nit: useful to print max recursion level here. maybe even be more descriptive, e.g. `recursed into too many files running \i (maximum %d)`
___
*[pkg/cli/sql.go, line 1151 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/54796#-MIKB18DDsanx2SuKRZJ:-MIKB18DDsanx2SuKRZK:b741zuc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e98854e8d99373d942707ddd4ff28ce9a98db5d9/pkg/cli/sql.go#L1151)):*
> ```Go
> 	defer func() {
> 		if err := f.Close(); err != nil {
> 			fmt.Fprintf(stderr, "closing %s: %v\n", filename, err)
> ```

nit: does some sort of `ERROR` thing show up in front of this? it may look confusing otherise

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

___
*[pkg/cli/sql.go, line 1050 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/54796#-MIKCMXIACdw7JQDccx0:-MIPyKGN2PVGhAV7HLwV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e98854e8d99373d942707ddd4ff28ce9a98db5d9/pkg/cli/sql.go#L1050)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

looks like `\ir` may be a cool follow up.
</blockquote></details>

Done.
___
*[pkg/cli/sql.go, line 1124 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/54796#-MIKBq5904Xjd1X-2fhZ:-MIPyLx41DLnFISA2i-B:biv30ii) ([raw file](https://github.com/cockroachdb/cockroach/blob/e98854e8d99373d942707ddd4ff28ce9a98db5d9/pkg/cli/sql.go#L1124)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: had a bit of trouble understanding what this function did. maybe `importCLICommandFile`? the recursion concept is not evident here because this function doesn't actually do any recursion.
</blockquote></details>

Renamed as suggested.
___
*[pkg/cli/sql.go, line 1132 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/54796#-MIKBBxXDPk7RKdsY5-D:-MIPyNCf27xYPhH8Sxu5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e98854e8d99373d942707ddd4ff28ce9a98db5d9/pkg/cli/sql.go#L1132)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: useful to print max recursion level here. maybe even be more descriptive, e.g. `recursed into too many files running \i (maximum %d)`
</blockquote></details>

Done.
___
*[pkg/cli/sql.go, line 1151 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/54796#-MIKB18DDsanx2SuKRZJ:-MIPyOAM2RpWN9HnRFGI:bs7wune) ([raw file](https://github.com/cockroachdb/cockroach/blob/e98854e8d99373d942707ddd4ff28ce9a98db5d9/pkg/cli/sql.go#L1151)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: does some sort of `ERROR` thing show up in front of this? it may look confusing otherise
</blockquote></details>

Done.1

**Review by otan — APPROVED** [review]
> Reviewed 2 of 10 files at r6, 1 of 2 files at r7, 1 of 2 files at r8, 1 of 2 files at r9, 8 of 8 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

**Comment by knz** [comment]
TFYR!

bors r=otan

**Pull request merged**
