### PR TITLE
cli: default host to "localhost" in client commands

### LINKED ISSUE #10119: cli: localhost not set to default in commands
When trying to run commands on a secure cluster, you must add the `--host=localhost` flag, otherwise you receive `Error: rpc error: code = 13 desc = connection error: desc = "transport: tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config"`

### Steps to repro

1. On GCE: `cockroach start --background --ca-cert=certs/ca.cert --cert=certs/node1.cert --key=certs/node1.key --advertise-host=10.138.0.2`
2. `cockroach node status --ca-cert=certs/ca.cert --cert=certs/root.cert --key=certs/root.key`

### Expected behavior

The `cockroach node status` command runs

### Actual beavior

You receive `Error: rpc error: code = 13 desc = connection error: desc = "transport: tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config"`

However, you can resolve this issue by running the command as:
`cockroach node status --ca-cert=certs/ca.cert --cert=certs/root.cert --key=certs/root.key --host=localhost`

### PR DESCRIPTION
**Pull request by asubiotto**
Fixes #10119

@tamird @sploiselle

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10134)

### CODE REVIEW

**Comment by tamird** [comment]
You should include "Fixes #10119" in the commit message. Also, can you add a test?

**Comment by tamird** [comment]
Updated this for you, take a look.

**Comment by asubiotto** [comment]
The changes look good, thanks.

**Comment by asubiotto** [comment]
LGTM

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10134#-:-KUcp5wSJP9uNavqvrSL:bb6ywmx)*

**Comment by bdarnell** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cli/cli_test.go, line 184 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10134#-KUgSpY9lycCsLAVfPP-:-KUgSpY9lycCsLAVfPP0:b-jbong2) ([raw file](https://github.com/cockroachdb/cockroach/blob/6446ded242ae7868ee33ff3038ff042e9f8a2423/pkg/cli/cli_test.go#L184)):*
> ```Go
> 		}
> 		{
> 			// When testing on Linux, we use a non-localhost loopback address (see
> ```

And when testing on darwin, we bind to `127.0.0.1` instead of `localhost` (i.e. ipv4-only, because the mac firewall pops up dialogs whenever something binds to `localhost` in ipv6). Using `localhost` on the client side is therefore slightly incorrect: it may (depending on implementation details) try to connect to ipv6 first, fail, and retry on ipv4.

Currently, `net.ResolveIPAddr` prefers ipv4. When/if it changes to prefer ipv6 on a future version of go, this test will begin passing `--host` on darwin too, and we'll lose test coverage of the default case for the `--host` flag. 

This test should continue to unconditionally add the `--host` flag. If we want an end-to-end test of the default value it should be in an acceptance test docker container where we know we can use `localhost` on both client and server. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10134)*

**Comment by tamird** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/cli/cli_test.go, line 184 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10134#-KUgSpY9lycCsLAVfPP-:-KUhUn48Mz_9EzwZ7Ayu:b-pogdyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/6446ded242ae7868ee33ff3038ff042e9f8a2423/pkg/cli/cli_test.go#L184)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> And when testing on darwin, we bind to `127.0.0.1` instead of `localhost` (i.e. ipv4-only, because the mac firewall pops up dialogs whenever something binds to `localhost` in ipv6). Using `localhost` on the client side is therefore slightly incorrect: it may (depending on implementation details) try to connect to ipv6 first, fail, and retry on ipv4.
> 
> Currently, `net.ResolveIPAddr` prefers ipv4. When/if it changes to prefer ipv6 on a future version of go, this test will begin passing `--host` on darwin too, and we'll lose test coverage of the default case for the `--host` flag. 
> 
> This test should continue to unconditionally add the `--host` flag. If we want an end-to-end test of the default value it should be in an acceptance test docker container where we know we can use `localhost` on both client and server. 
</details>
OK, restored to passing unconditionally. I'll look into adding an acceptance test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10134)*

**Comment by tamird** [comment]
Added an acceptance test; gonna merge on green.

**Comment by asubiotto** [comment]
LGTM

**Pull request merged**
