### PR TITLE
kvserver: don't transfer leases to draining nodes during scatters

### PR DESCRIPTION
**Pull request by aayushshah15**
**kvserver: introduce Allocator.ValidLeaseTargets()**

This commit is a minor refactor of the `Allocator.TransferLeaseTarget` logic in
order to make it more readable and, to abstract out a new exported `Allocator`
method called `ValidLeaseTargets()`.

The contract of `ValidLeaseTargets()` is as follows:
```
// ValidLeaseTargets returns a set of candidate stores that are suitable to be
// transferred a lease for the given range.
//
// - It excludes stores that are dead, or marked draining or suspect.
// - If the range has lease_preferences, and there are any non-draining,
// non-suspect nodes that match those preferences, it excludes stores that don't
// match those preferences.
// - It excludes replicas that may need snapshots. If replica calling this
// method is not the Raft leader (meaning that it doesn't know whether follower
// replicas need a snapshot or not), produces no results.

```

Previously, there were multiple places where we were performing the logic
that's encapsulated by `ValidLeaseTargets()`, which was a potential source of
bugs. This is an attempt to unify this logic in one place that's relatively
well-tested. This commit is only a refactor, and does not attempt to change any
behavior. As such, no existing tests have been changed, with the exception of a
subtest inside `TestAllocatorTransferLeaseTargetDraining`. See the comment over
that subtest to understand why the behavior change made by this patch is
desirable.

The next commit in this PR uses this method to fix (at least part of) https://github.com/cockroachdb/cockroach/issues/74691.

Release note: none

**kvserver: don't transfer leases to draining nodes during scatters**

Previously, `AdminScatter` called with the `RandomizeLeases` option could
potentially transfer leases to nodes marked draining.  This commit leverages
the refactor from the last commit to fix this bug by first filtering the set of
candidates down to a set of valid candidates that meet lease preferences and
are not marked suspect or draining.

Relates to and fixes a part of https://github.com/cockroachdb/cockroach/issues/74691.

Release note (bug fix): Fixes a bug where draining / drained nodes could
re-acquire leases during an import or an index backfill.

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
Great to see this! A drive-by question I had is whether the backport of this will be problematic, and whether we're planning a surgical fix to backport instead.

**Comment by aayushshah15** [comment]
Yeah, I was thinking that we'd just backport a small two-liner but fix it "properly" on `master`.

**Review by kvoli — APPROVED** [review]
LGTM!

> Reviewed 5 of 5 files at r5, 3 of 3 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79295#-:-Mzlsz2m73eR6LZRaTWR:b-85i648)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by tbg — APPROVED** [review]
Nice! Always a pleasure to see shifty ad-hoc code gone.

> Reviewed 5 of 5 files at r5, 3 of 3 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79295#-:-MzvLk9-9e5fe3RkslMA:b2rvs5r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @nvanbenschoten)

___
*[pkg/kv/kvserver/allocator.go, line 1502 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/79295#-MzvIhcFAUIhd9BIWYN4:-MzvIhcFAUIhd9BIWYN5:bv3zaoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92ffb3adfc854c0803b4046af092a9e3f1cc1c8/pkg/kv/kvserver/allocator.go#L1502)):*
> ```Go
> 	candidates := make([]roachpb.ReplicaDescriptor, 0, len(existing))
> 	for i := range existing {
> 		if existing[i].GetType() != roachpb.VOTER_FULL {
> ```

Is this correct? I thought we now possibly transferred leases to a VOTER_INCOMING. Is this only occurring on a separate ad-hoc path?
___
*[pkg/kv/kvserver/allocator.go, line 1570 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/79295#-MzvJV_K6qI6VheUtBNO:-MzvJV_K6qI6VheUtBNP:bl53jek) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92ffb3adfc854c0803b4046af092a9e3f1cc1c8/pkg/kv/kvserver/allocator.go#L1570)):*
> ```Go
> 		}
> 	}
> 	if !leaseholderInExisting && !buildutil.CrdbTestBuild {
> ```

It's unusual to have an assertion that's *only* in production but not in tests. Could you add a comment on why that is necessary? It might be cleaner to use a testing knob here to selectively disable the assertion. I also think we may want to avoid fataling in prod for something like this, when there is the reasonable enough option to "do nothing". I wouldn't want to deal with the fatal error in prod, as it will be hard to contain and thus difficult to keep the cluster alive.
___
*[pkg/kv/kvserver/allocator.go, line 1620 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/79295#-MzvK1_jAwHxHxOV7HKB:-MzvK1_jAwHxHxOV7HKC:b2yxkay) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92ffb3adfc854c0803b4046af092a9e3f1cc1c8/pkg/kv/kvserver/allocator.go#L1620)):*
> ```Go
> 	opts transferLeaseOptions,
> ) roachpb.ReplicaDescriptor {
> 	checkTransferLeaseSource := opts.checkTransferLeaseSource
> ```

I wonder if it's worth to pull through and rename this parameter to `allowLeaseRepl`. `checkTransferLeaseSource` seems cryptic.
___
*[pkg/kv/kvserver/allocator.go, line 1640 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/79295#-MzvKKMQAmoYV60oN6qC:-MzvKKMQAmoYV60oN6qD:bzhrwc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92ffb3adfc854c0803b4046af092a9e3f1cc1c8/pkg/kv/kvserver/allocator.go#L1640)):*
> ```Go
> 	}
> 
> 	existing = a.ValidLeaseTargets(
> ```

:heart_eyes: 
___
*[pkg/kv/kvserver/allocator.go, line 1865 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/79295#-MzvKftbA9sEYXIEpsa-:-MzvKftbA9sEYXIEpsa0:b-djeflu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92ffb3adfc854c0803b4046af092a9e3f1cc1c8/pkg/kv/kvserver/allocator.go#L1865)):*
> ```Go
> 	stats *replicaStats,
> ) bool {
> 	if a.leaseholderViolatesPreferences(ctx, conf, leaseRepl, existing) {
> ```

Maybe this method would be more aptly named `leaseholderShouldMoveDueToPreferences`, since this makes it clear that the method checks more than just a violation of preferences (it also verifies that there's a better place to put the lease according to prefs)
___
*[pkg/kv/kvserver/replica_command.go, line 3331 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/79295#-MzvLPzXB0U_Q_CH33mI:-MzvLPzXB0U_Q_CH33mJ:bubi9y8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2c0c32a2a5b8d4b19451012a88bce1004d591cc/pkg/kv/kvserver/replica_command.go#L3331)):*
> ```Go
> 			targetStoreID := potentialLeaseTargets[newLeaseholderIdx].StoreID
> 			if targetStoreID != r.store.StoreID() {
> 				log.VEventf(ctx, 2, "randomly transferring lease to s%d", targetStoreID)
> ```

Does `ctx` have the repl in it? With these kinds of messages you always want the range we're talking about.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79295)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @kvoli, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/allocator.go, line 1502 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/79295#-MzvIhcFAUIhd9BIWYN4:-MzvkWUm7o85ToiUsV5n:bkugscq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92ffb3adfc854c0803b4046af092a9e3f1cc1c8/pkg/kv/kvserver/allocator.go#L1502)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Is this correct? I thought we now possibly transferred leases to a VOTER_INCOMING. Is this only occurring on a separate ad-hoc path?
</blockquote></details>

We do transfer leases to incoming voters now, but that's ad-hoc code for replication changes. `AdminChangeReplicas` calling into the allocator was always a bit fraught, and we're no longer doing that now since https://github.com/cockroachdb/cockroach/pull/77841. 
___
*[pkg/kv/kvserver/allocator.go, line 1570 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/79295#-MzvJV_K6qI6VheUtBNO:-Mzw9l0d-8uijFTfoDlP:b-qu6qrs) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92ffb3adfc854c0803b4046af092a9e3f1cc1c8/pkg/kv/kvserver/allocator.go#L1570)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

It's unusual to have an assertion that's *only* in production but not in tests. Could you add a comment on why that is necessary? It might be cleaner to use a testing knob here to selectively disable the assertion. I also think we may want to avoid fataling in prod for something like this, when there is the reasonable enough option to "do nothing". I wouldn't want to deal with the fatal error in prod, as it will be hard to contain and thus difficult to keep the cluster alive.
</blockquote></details>

All the current callers of this do include the `leaseRepl` in the slice of existing replicas, so I just wanted some regression insurance for this. Based on your comment, I've downgraded this to a `log.Error` for now. 
___
*[pkg/kv/kvserver/allocator.go, line 1620 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/79295#-MzvK1_jAwHxHxOV7HKB:-MzwHF986cBDSOAdE7A9:bgsqyb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92ffb3adfc854c0803b4046af092a9e3f1cc1c8/pkg/kv/kvserver/allocator.go#L1620)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I wonder if it's worth to pull through and rename this parameter to `allowLeaseRepl`. `checkTransferLeaseSource` seems cryptic.
</blockquote></details>

Added it as the final commit in this PR. 
___
*[pkg/kv/kvserver/allocator.go, line 1865 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/79295#-MzvKftbA9sEYXIEpsa-:-MzwB3Bp4mlfTi9IdVKN:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92ffb3adfc854c0803b4046af092a9e3f1cc1c8/pkg/kv/kvserver/allocator.go#L1865)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Maybe this method would be more aptly named `leaseholderShouldMoveDueToPreferences`, since this makes it clear that the method checks more than just a violation of preferences (it also verifies that there's a better place to put the lease according to prefs)
</blockquote></details>

Done. 
___
*[pkg/kv/kvserver/replica_command.go, line 3331 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/79295#-MzvLPzXB0U_Q_CH33mI:-MzwBFnF0kM0CMnOE_7a:b7hgo5q) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2c0c32a2a5b8d4b19451012a88bce1004d591cc/pkg/kv/kvserver/replica_command.go#L3331)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Does `ctx` have the repl in it? With these kinds of messages you always want the range we're talking about.
</blockquote></details>

Yep, It should be added here: https://github.com/cockroachdb/cockroach/blob/68566b693ea1819c24aa25facf833f291747ec82/pkg/kv/kvserver/replica_send.go#L132-L134

**Review by aayushshah15 — COMMENTED** [review]
Optimistically merging based on the approvals. TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79295#-:-MzzjBST7bq5nGI3wgwM:bt2rpot)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @kvoli, @nvanbenschoten, and @tbg)

**Review by tbg — APPROVED** [review]
> Reviewed 8 of 8 files at r11, 4 of 4 files at r12, 6 of 6 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79295)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @nvanbenschoten)

___
*[pkg/kv/kvserver/allocator.go, line 1570 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/79295#-N--77ZIDuywBOe7recU:-N--77ZIDuywBOe7recV:b-430i52) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a8d5c1f703ad6dcbd18bebb3d985c5d83ec836/pkg/kv/kvserver/allocator.go#L1570)):*
> ```Go
> 	}
> 	if !leaseholderInExisting {
> 		log.Errorf(ctx, "programming error: expected leaseholder store to be in the slice of existing replicas")
> ```

But then don't you want to return?
___
*[pkg/kv/kvserver/allocator.go, line 1653 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/79295#-N--7OzQ6kiiBlxZ31qi:-N--7OzQ6kiiBlxZ31qj:b-uflc2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a8d5c1f703ad6dcbd18bebb3d985c5d83ec836/pkg/kv/kvserver/allocator.go#L1653)):*
> ```Go
> 			ctx, source, existing, stats, nil, candidateLeasesMean,
> 		)
> 		if !excludeLeaseRepl {
> ```

Hadn't read this code before. I don't understand it. You're sure this is all correct, right? I know you're not changing anything in this PR, so just a drive by comment.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79295)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/kv/kvserver/allocator.go, line 1570 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/79295#-N--77ZIDuywBOe7recU:-N-0gxTX9ETYbtE3w2aQ:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a8d5c1f703ad6dcbd18bebb3d985c5d83ec836/pkg/kv/kvserver/allocator.go#L1570)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

But then don't you want to return?
</blockquote></details>

Done. 
___
*[pkg/kv/kvserver/allocator.go, line 1653 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/79295#-N--7OzQ6kiiBlxZ31qi:-N-0h4bMDJIxZUS9BQ-r:buvd695) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a8d5c1f703ad6dcbd18bebb3d985c5d83ec836/pkg/kv/kvserver/allocator.go#L1653)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Hadn't read this code before. I don't understand it. You're sure this is all correct, right? I know you're not changing anything in this PR, so just a drive by comment.
</blockquote></details>

I don't really understand why it's written the way it is, and it could use some further clean-up. I'll try and do something about it soon™.

**Pull request merged**
