### PR TITLE
roachprod: Configure Azure disks.

### PR DESCRIPTION
**Pull request by miretskiy**
Add ability to specify the size of the attached disks for Azure.
Use read only caching for Azure premium disks.

Release Notes: None

### CODE REVIEW

**Review by arulajmani — APPROVED** [review]
LGTM modulo one suggestion. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55975#-:-MK_ZQiWBdeHdhKQHzB2:b-j4kbt9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @miretskiy)

___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 595 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55975#-MK_YdQy97On0j6pxohx:-MK_YdQy97On0j6pxohy:bgx125x) ([raw file](https://github.com/cockroachdb/cockroach/blob/90261ac4f961a16fe4972f5c3aa80755307ffdcd/pkg/cmd/roachprod/vm/azure/azure.go#L595)):*
> ```Go
> 		case "premium-disk":
> 			storageAccType = compute.StorageAccountTypesPremiumLRS
> 			caching = compute.CachingTypesReadOnly
> ```

Can we make this configurable and have it default to `None`? Considering how many times we've gotten burned by hard coded things in roachprod, I think we should surface this to users rather than have them find this "magic" only if they go digging in.

**Comment by miretskiy** [comment]
Done.  Added --azure-disk-caching flag.

**Review by arulajmani — APPROVED** [review]
Thanks! one nit but otherwise this should be good to merge. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55975#-:-MK_bGkwBC2Zi4vOmzyb:b-tjvkj5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 605 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55975#-MK_b0h54-iA4KBsNueM:-MK_b0h6DJna7ckXlkPg:b-se9byt) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a23a2c5d885041e62172baec47b8b12ea07a64e/pkg/cmd/roachprod/vm/azure/azure.go#L605)):*
> ```Go
> 			caching = compute.CachingTypesReadOnly
> 		case "read-write":
> 			caching = compute.CachingTypesReadWrite
> ```

nit: could you add a case for `None` and a `default` option so that if the user makes a typo or something they're informed rather than surprised?

**Comment by miretskiy** [comment]
done.

**Review by arulajmani — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55975#-:-MK_rcgHB8jmJ_jRa2Um:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy)

**Pull request merged**
