### PR TITLE
cmd/roachtest: hardcode list of roachmart zones to use

### PR DESCRIPTION
**Pull request by petermattis**
Roachmart requires that the list of zones in the roachtest match the
list of zones in workload/roachmart which matches the list of zones used
to create the cluster. Make sure these are all explicitly configured
now. No functional change except roachmart now uses us-central1-b
instead of us-east1-b. The us-central1-b zone is where we run nightly
tests, while us-east1-b is used for manually created roachprod clusters.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
@danhhz This will allow us to specify `--zones` for the roachtest nightlies without disrupting `roachmart`. Remember when we couldn't figure out why the roachtest nightlies were specifying `us-central1-b`? That was to avoid running out of quota in `us-east1-b`.

**Comment by petermattis** [comment]
@tschottdorf or @nvanbenschoten do either of you have time to give this a quick look today? I'd like to get this in so I can change the roachtest nightlies to run use `us-central1-b` instead of `us-east1-b` and avoid the quota issue we ran into last night.

**Comment by nvanbenschoten** [comment]
I can take a look today. @m-schneider might also be interested because of some of her work relating to https://github.com/cockroachdb/cockroach/issues/25878.

**Comment by petermattis** [comment]
FYI, I've updated the roachtest nightly config to specify `--zones` to `roachtest run`. The effect is that the `roachmart` tests will fail tonight unless this change is merged. That seems preferable than running out of quota in `us-east1-b`. Even better would be to get this PR merged.

**Comment by nvanbenschoten** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/cmd/roachtest/cluster.go, line 402 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26046#-LDJ2Hrl712ygi9CTX3Q:-LDJ2Hrl712ygi9CTX3R:b-6xnakf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f07a72b7a83c27035c33fbb69a880f852c005d32/pkg/cmd/roachtest/cluster.go#L402)):*
> ```Go
> 
> // zones is a node option which requests geo-distributed nodes. Note that this
> // overrides the --zones flag and is useful for tests that require running on
> ```

Is it more useful to override the zone flag or complain if they're both provided and they disagree? I'd lean towards the latter, similar to how I'm working on complaining when a `cpu()` option disagrees with an existing clusters cpu count.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26046)*

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26046#-:-LDJ2dDZ3vwJBwyEcUKI:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/cmd/roachtest/cluster.go, line 353 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26046#-LDJ2v9y8hL4yP8vUDqk:-LDJ2v9y8hL4yP8vUDql:b-4ffvh2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f07a72b7a83c27035c33fbb69a880f852c005d32/pkg/cmd/roachtest/cluster.go#L353)):*
> ```Go
> 	}
> 	if s.Zones != "" {
> 		args = append(args, "--gce-zones="+s.Zones)
> ```

I'm trying to refresh my memory on why it makes sense to have a `geo` flag and a `zones` flag. Do you know the answer off the top of your head? This is a roachprod question so no need to hold up this PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26046)*

**Comment by petermattis** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/cmd/roachtest/cluster.go, line 402 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26046#-LDJ2Hrl712ygi9CTX3Q:-LDJ2ssp2kkobczLrUAY:b-3myceq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f07a72b7a83c27035c33fbb69a880f852c005d32/pkg/cmd/roachtest/cluster.go#L402)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is it more useful to override the zone flag or complain if they're both provided and they disagree? I'd lean towards the latter, similar to how I'm working on complaining when a `cpu()` option disagrees with an existing clusters cpu count.
</blockquote></details>

Complaining seems burdensome. We want the roachtest nightlies to use a `--zones` flag that avoids `us-east1-b` which we use for manually created clusters. I'm not sure how we'd have the `roachmart` tests run both with and without a `--zones` flag if we were to complain when there is a discrepancy. The `cpu()` option vs an existing cluster seems a bit different and I can see complaining there is useful.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26046)*

**Comment by petermattis** [comment]
I'm going to merge this. We can revisit the behavior of `zones()` vs `--zones` in a follow-on PR.

bors r=nvanbenschoten

---

Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26046#-:-LDJ7B6M7CSMW-SrI3O5:b-7agf7z)*

**Comment by petermattis** [comment]
`TestDockerStartFlags` flake. Not sure what happened. Still investigating.

bors r=nvanbenschoten

**Comment by petermattis** [comment]
https://github.com/cockroachdb/cockroach/issues/26074 flake

bors r=nvanbenschoten

**Comment by petermattis** [comment]
bors r=nvanbenschoten

**Pull request merged**
