### PR TITLE
build: run benchshort on CI

### PR DESCRIPTION
**Pull request by asubiotto**

### CODE REVIEW

**Comment by benesch** [comment]
LGTM though this looks like it takes 7.5m in CI to complete. That's not including an additional ~3m of compilation. It's not the longest test in our GitHub CI suite, though, so I'm ok with it, but definitely get someone else to sign off too before merging.

**Comment by asubiotto** [comment]
Weird, it took 3m20s on my machine. Will check the logs and see what's up/maybe skip some other benchmarks.

**Comment by asubiotto** [comment]
From the logs:
```
[19:18:23][Run Benchmarks] go test  -tags ' make x86_64_pc_linux_gnu' -ldflags '-X github.com/cockroachdb/cockroach/pkg/build.typ=development -extldflags "" -X "github.com/cockroachdb/cockroach/pkg/build.tag=v2.1.0-alpha.20180702-923-gd066f23" -X "github.com/cockroachdb/cockroach/pkg/build.rev=d066f2331b2fe0c8891c51bc346ba8b711351635" -X "github.com/cockroachdb/cockroach/pkg/build.cgoTargetTriple=x86_64-pc-linux-gnu"  ' -run "-" -bench "." -timeout 5m ./pkg/... -v -logtostderr=NONE -benchtime=1ns -short
[19:21:47][Run Benchmarks] not running with `acceptance` build tag; skipping
[19:21:47][Run Benchmarks] ?   	github.com/cockroachdb/cockroach/pkg/acceptance/cluster	[no test files]
[19:21:47][Run Benchmarks] ?   	github.com/cockroachdb/cockroach/pkg/acceptance/localcluster	[no test files]
[19:21:47][Run Benchmarks] ?   	github.com/cockroachdb/cockroach/pkg/acceptance/localcluster/tc	[no test files]
```
It seems that the `test` command didn't actually start executing benchmarks until 3 minutes after it was run. Not sure what's going on there but @benesch and I agreed to move forward with the merge since the CI steps are parallelized and it still lasts less than acceptance. Will hold off on merging this until next week.

**Pull request merged**
