### PR TITLE
changefeedccl: signal memBuffer with a channel instead of polling

### PR DESCRIPTION
**Pull request by danhhz**
With RangeFeed now firmly in place in changefeeds, we're very close to
end-to-end push, which will dramatically improve latencies of row
changes (resolved timestamps, however, will continue to be limited by
closed timestamp latency).

This commit removes one of two remaining places where we poll (the other
is detailed in #36289). No functional change besides more responsiveness
after the first changed kv gets written to memBuffer after it being
empty for a while (and so the old polling would have already backed off
to the max interval).

Touches #36289

Release note: None

### CODE REVIEW

**Review by nvb — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37094)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/buffer.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37094#-LdG4joJ7gOpLR9XXotB:-LdG4joJ7gOpLR9XXotC:b-24esfr) ([raw file](https://github.com/cockroachdb/cockroach/blob/59e59ccf4097c0c85b2dd62155e7b53cbcdefd0a/pkg/ccl/changefeedccl/buffer.go#L104)):*
> ```Go
> // events. It's size is limited only by the BoundAccount passed to the
> // constructor.
> type memBuffer struct {
> ```

You're using mutexes here to make this type thread-safe, but it's unclear whether you're targetting single-producer/single-consumer, multi-producer/multi-consumer, or some combination of the two. I'd clarify this.

Concretely, I bring this up because the approach we have here will only work for single-consumer use cases.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37094)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/buffer.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37094#-LdG4joJ7gOpLR9XXotB:-LdGFrBD0VWLzzHWdcGo:b-zd9g6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/59e59ccf4097c0c85b2dd62155e7b53cbcdefd0a/pkg/ccl/changefeedccl/buffer.go#L104)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

You're using mutexes here to make this type thread-safe, but it's unclear whether you're targetting single-producer/single-consumer, multi-producer/multi-consumer, or some combination of the two. I'd clarify this.

Concretely, I bring this up because the approach we have here will only work for single-consumer use cases.
</blockquote></details>

This is only used for single-producer single-consumer. Added a mention of that

**Review by nvb — APPROVED** [review]
LGTM

**Comment by danhhz** [comment]
TFTR!

bors r=nvanbenschoten

**Pull request merged**
