### PR TITLE
sql/pgwire: fix binary decimal encoding

### LINKED ISSUE #8298: sql/pgwire: DECIMAL columnn results perhaps not properly encoded
Reported by @fishcakez in https://github.com/cockroachdb/cockroach/issues/5582#issuecomment-236400566:

"""
The DataRow message from `SELECT 42::numeric` has 1 column value in length. However it will include 2 empty column values `\x00\x00` after the numeric column value.
"""

### PR DESCRIPTION
**Pull request by tamird**
Closes #8298.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8319)

### CODE REVIEW

**Comment by mjibson** [comment]
How did this test pass locally? `numeric` doesn't appear to be a valid symbol and it should have error'd with a compile error.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[acceptance/c_test.go, line 195 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8319#-KOI22uDSrYq4oN4mC-x:-KOI22uDSrYq4oN4mC-y:-1464253180) ([raw file](https://github.com/cockroachdb/cockroach/blob/841ea811d00f24273985b2247a8cf0eed6264082/acceptance/c_test.go#L195)):*
> ```Go
> 			}
> 			if (strcmp(recvnumeric1, numeric1)) {
> 				fprintf(stderr, "expected: %s, got: %s\n", numeric, recvnumeric1);
> ```

numeric -> numeric1?

---

*[acceptance/c_test.go, line 205 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8319#-KOI1wsJm7FcsNl6CWJH:-KOI1wsJm7FcsNl6CWJI:-1464253149) ([raw file](https://github.com/cockroachdb/cockroach/blob/841ea811d00f24273985b2247a8cf0eed6264082/acceptance/c_test.go#L205)):*
> ```Go
> 			}
> 			if (strcmp(recvnumeric2, numeric2)) {
> 				fprintf(stderr, "expected: %s, got: %s\n", numeric, recvnumeric2);
> ```

numeric -> numeric2?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8319#-:-KOI25_xTXWcI5ZhrxJ0:1858898163)*

**Comment by tamird** [comment]
Derp, I ran `make test PKG=./acceptance`, which silently did nothing but skip the test. After fixing that compile error, the acceptance test indeed fails with an obscure error `ERROR: Trying to get type 16 'pg_catalog.bool' but server returned 20 (position 1)`.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8319#-:-KOIE1-mz5tw9zTqPOuK:614706708)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[acceptance/c_test.go, line 195 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8319#-KOI22uDSrYq4oN4mC-x:-KOITy30CXsGlvhl45B6:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/841ea811d00f24273985b2247a8cf0eed6264082/acceptance/c_test.go#L195)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> numeric -> numeric1?
</details>
Done.

---

*[acceptance/c_test.go, line 205 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8319#-KOI1wsJm7FcsNl6CWJH:-KOITyKji0j3NVGBsJsf:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/841ea811d00f24273985b2247a8cf0eed6264082/acceptance/c_test.go#L205)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> numeric -> numeric2?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8319)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8319#-:-KOM2si-O4XITCviDIRH:1417088721)*

**Comment by mjibson** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/pgwire/types.go, line 232 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8319#-KOfquYZiw04OuVjQMNJ:-KOfquYZiw04OuVjQMNK:b-qm6vyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d95391ff6b709e063ecfcd562bcc9b0c82d4e49/sql/pgwire/types.go#L232)):*
> ```Go
> 
> 		switch sign := v.Sign(); {
> 		case sign > 0:
> ```

I think this should remain as `>= 0` because the zero check code in libpqtypes sets the sign to POS.

---

*[sql/pgwire/types.go, line 292 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8319#-KOfrb_Mecrdm1pNzoUH:-KOfrb_NYZn-hpuON8ml:b-3a2p5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d95391ff6b709e063ecfcd562bcc9b0c82d4e49/sql/pgwire/types.go#L292)):*
> ```Go
> 		b.putInt16(alloc.pgNum.dscale)
> 
> 		// Emulate stripping leading zeroes.
> ```

This comment got moved up and it's no longer accurate here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8319)*

**Comment by tamird** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/pgwire/types.go, line 232 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8319#-KOfquYZiw04OuVjQMNJ:-KOfsausZgEfO0uQeIP7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d95391ff6b709e063ecfcd562bcc9b0c82d4e49/sql/pgwire/types.go#L232)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> I think this should remain as `>= 0` because the zero check code in libpqtypes sets the sign to POS.
</details>
Done.

---

*[sql/pgwire/types.go, line 292 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8319#-KOfrb_Mecrdm1pNzoUH:-KOfsbi4EMzKW7XwtIXv:bz57pdj) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d95391ff6b709e063ecfcd562bcc9b0c82d4e49/sql/pgwire/types.go#L292)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> This comment got moved up and it's no longer accurate here.
</details>
No, it's still accurate. We're only writing the first digit if it's non-zero.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8319)*

**Comment by mjibson** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/pgwire/binary_test.go, line 84 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8319#-KOfwH3xkvhQm7vwkjOf:-KOfwH3yBPoZ64i21yg-:b-v72vbv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d95391ff6b709e063ecfcd562bcc9b0c82d4e49/sql/pgwire/binary_test.go#L84)):*
> ```Go
> 		buf.wrapped.Reset()
> 
> 		dec.SetString(test.in)
> ```

Need to check for errors here. That's why the exponent didn't work. No bug in the decimal library. We don't need to add the exponent test back, but just gotta make sure the parse went ok to prevent bad tests in the future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8319)*

**Comment by tamird** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/pgwire/binary_test.go, line 84 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8319#-KOfwH3xkvhQm7vwkjOf:-KOh1FCz8QQ1ahgCR_uA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d95391ff6b709e063ecfcd562bcc9b0c82d4e49/sql/pgwire/binary_test.go#L84)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Need to check for errors here. That's why the exponent didn't work. No bug in the decimal library. We don't need to add the exponent test back, but just gotta make sure the parse went ok to prevent bad tests in the future.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8319)*

**Comment by fishcakez** [comment]
FWIW this branch fixes the encoding issue mentioned in #8298. However the precision is lost, I did not check whether that was the case before this branch sorry. For example we want to send `1.0000` and keep the number of decimal places. However it is simplified to `1` by cockroach. Postgres keeps the precision and sends back the same scale, i.e. `1.0000`.

**Comment by tamird** [comment]
@fishcakez thanks for the update! I bet we're losing the precision on the incoming side. I'll take a look.

**Comment by tamird** [comment]
@fishcakez can you try that again? There was a bug on the parsing side that I just fixed.

**Comment by fishcakez** [comment]
@tamird still see the same problem. I don't have go 1.7rc so had to rebase these commits on top of 729c3c0. I will check that the postgresql client's test suite with this issue isn't flawed later.

**Comment by tamird** [comment]
cc @nvanbeschoten are we doing some inappropriate simplification?

**Comment by nvanbenschoten** [comment]
It sounds like the case @fishcakez is referring to is inserting a value like `1.000` into a `DECIMAL` column, then selecting it back from that column. In that case, if the column does not have an explicit scale attached to it, we will return `1`. 

```
root@:26257> create table dec (d decimal);
CREATE TABLE
root@:26257> insert into dec values (1.0000), (1.00);
INSERT 2
root@:26257> select * from dec;
+---+
| d |
+---+
| 1 |
| 1 |
+---+
(2 rows)
```

This is a limit of our on-disk decimal encoding, because we cut off trailing zeros during decimal normalization before encoding. However, this is also the exact same behavior as MySQL. 

If a certain scale is desired, a decimal column with that specific scale should be used (ie. `DECIMAL(4, 3)`). This should (but doesn't currently because of a TODO) pad out trailing zeros to give a desired scale when decoding on-disk decimal values.

**Comment by tamird** [comment]
Yikes, that seems like a pretty serious problem. cc @petermattis because I think we need to be able to transit decimals through a table with unspecified scale.

**Comment by fishcakez** [comment]
@nvanbenschoten explained the issue exactly but I don't like the suggested fix because if a scale isn't set it is possible for that column value to have different scale in different rows to represent the precision of the value. This is lost by normalised or fixed scaling.

**Comment by fishcakez** [comment]
Sorry I have used scale and precision interchangeably because I got confused which is which :smile:. I mean either.

**Comment by tamird** [comment]
@mjibson turns out the fix here was pretty simple, and our code looks about the same as libpqtypes' now, which is a nice bonus. take a look!

Also, I couldn't get the random generator working. Can you sprinkle some additional commentary on that code?

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/pgwire/testdata/decimal_test.json, line 146 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8319#-KPP0-S0osGwtQeOBskk:-KPP0-S0osGwtQeOBskl:b-wcsfn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/50be634ad7edda9b416386497a5945835bb0dbfa/sql/pgwire/testdata/decimal_test.json#L146)):*
> ```JSON
> 		"Expect": [0, 0, 0, 12, 0, 2, 0, 0, 0, 0, 0, 1, 0, 1, 3, 232]
> 	},
> 	{
> ```

This entry is a duplicate of above, need to rerun generate-decimal or delete it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8319#-:-KPP0PSE4BWDGVkoc91i:bnfp4nl)*

**Comment by mjibson** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cmd/generate-decimal/main.go, line 178 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8319#-KPP13k8XDjTqtCOf5fb:-KPP13k8XDjTqtCOf5fc:b-bf3khs) ([raw file](https://github.com/cockroachdb/cockroach/blob/50be634ad7edda9b416386497a5945835bb0dbfa/cmd/generate-decimal/main.go#L178)):*
> ```Go
> 	}
> 	idx := 12
> 	end := bytes.Index(b, []byte{67, 0, 0, 0})
> ```

Index -> LastIndex

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8319)*

**Pull request merged**
