### PR TITLE
ccl: refactor tenant status server test to statusccl package

### PR DESCRIPTION
**Pull request by Azhng**
Previously, tenant status server tests live within serverccl package.
However, this caused all nightly test failures to automaticallly
notify server team through GitHub code owner file.
This commit moves all tenant status server into statusccl package
and update statusccl package code owner to SQL O11y.

Release note: None

### CODE REVIEW

**Review by lindseyjin — COMMENTED** [review]
> Reviewed 2 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72556)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/ccl/serverccl/statusccl/main_test.go, line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72556#-Mo4VQNYC7_CmbDYwMUi:-Mo4VQNYC7_CmbDYwMUj:b-3cbvyz) ([raw file](https://github.com/cockroachdb/cockroach/blob/80efd5009943ff468205e6633546883e28e447f9/pkg/ccl/serverccl/statusccl/main_test.go#L15)):*
> ```Go
> 	"testing"
> 
> 	_ "github.com/cockroachdb/cockroach/pkg/ccl"
> ```

Btw, is there supposed to be an underscore here? What does that mean?

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72556)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/ccl/serverccl/statusccl/main_test.go, line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72556#-Mo4VQNYC7_CmbDYwMUi:-Mo4Wuom6qRxlIgpkl7u:b-kw0l1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/80efd5009943ff468205e6633546883e28e447f9/pkg/ccl/serverccl/statusccl/main_test.go#L15)):*
> is there supposed to be an underscore here

Yes.

> What does that mean?

When importing a package, all the symbols within the package will be available under the package name, e.g. 

``` golang
import "github.com/cockroachdb/cockroach/pkg/security"

//...  later in the same file

security.ExportedSymbols // <- exported symbols are available under the `security` package name
```

However, in golang, there is a special function called `init`, which is defined as :

```
package some_package_name

func init() {
   // does stuff 
}
```

This function is not exported since it's lowercase. However, if this package is being imported by some other package, then the `init` function will be executed upon startup. This is done in `ccl` package to inject `ccl` functionalities into the CRDB

**Review by lindseyjin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72556)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/ccl/serverccl/statusccl/main_test.go, line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72556#-Mo4VQNYC7_CmbDYwMUi:-Mo4aYJ-8bxD_38EFR7T:bp1csay) ([raw file](https://github.com/cockroachdb/cockroach/blob/80efd5009943ff468205e6633546883e28e447f9/pkg/ccl/serverccl/statusccl/main_test.go#L15)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

> is there supposed to be an underscore here

Yes.

> What does that mean?

When importing a package, all the symbols within the package will be available under the package name, e.g. 

``` golang
import "github.com/cockroachdb/cockroach/pkg/security"

//...  later in the same file

security.ExportedSymbols // <- exported symbols are available under the `security` package name
```

However, in golang, there is a special function called `init`, which is defined as :

```
package some_package_name

func init() {
   // does stuff 
}
```

This function is not exported since it's lowercase. However, if this package is being imported by some other package, then the `init` function will be executed upon startup. This is done in `ccl` package to inject `ccl` functionalities into the CRDB
</blockquote></details>

Ah, I see, so we're importing the package just to execute the `init` function?

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72556)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/ccl/serverccl/statusccl/main_test.go, line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72556#-Mo4VQNYC7_CmbDYwMUi:-Mo4eG3S0oZEW99h4A-W:bm5we9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/80efd5009943ff468205e6633546883e28e447f9/pkg/ccl/serverccl/statusccl/main_test.go#L15)):*
<details><summary><i>Previously, lindseyjin (Lindsey Jin) wrote…</i></summary><blockquote>

Ah, I see, so we're importing the package just to execute the `init` function? 
</blockquote></details>

for `pkg/ccl` here yes :+1:

**Review by maryliag — APPROVED** [review]
just one small nit and :lgtm: 

> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72556#-:-Mo9RMPeEYCWwhEHg0TH:bsgchky)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng and @knz)

___
*[pkg/ccl/serverccl/statusccl/main_test.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72556#-Mo9R3wP0K4D0zgsr1Z1:-Mo9R3wVEklsPCpRmaD1:b9gawfo) ([raw file](https://github.com/cockroachdb/cockroach/blob/c95e0d79c2ac48a61f58168943f7fb64a659f833/pkg/ccl/serverccl/statusccl/main_test.go#L34)):*
> ```Go
> }
> 
> //go:generate ../../../util/leaktest/add-leaktest.sh *_test.go
> ```

nit: did you forget to remove this comment?

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72556)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @maryliag)

___
*[pkg/ccl/serverccl/statusccl/main_test.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72556#-Mo9R3wP0K4D0zgsr1Z1:-Mo9s2L_5Ue-ShW27j9V:bpe90xl) ([raw file](https://github.com/cockroachdb/cockroach/blob/c95e0d79c2ac48a61f58168943f7fb64a659f833/pkg/ccl/serverccl/statusccl/main_test.go#L34)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: did you forget to remove this comment?
</blockquote></details>

I think this comment was originally explicitly left to to ensure leak test are injected into all unit tests.

**Comment by Azhng** [comment]
TFTR!

bors r=maryliag

**Pull request merged**
