### PR TITLE
roachtest: improvements in connection to mixedversion services

### PR DESCRIPTION
**Pull request by renatolabs**
**roachtest/mixedversion: limit max time spent in internal queries**
In this commit, we change the `BinaryVersion` and `ClusterVersion` functions accept a `context` parameter. In addition, we change the mixedversion calls to these functions to pass a context with a fixed timeout. This effectively limits the maximum amount of time we will spend trying to gather this debug information.

In some failure scenarios, nodes may become unresponsive, which may make the test seem "stuck." With this change, tests should fail if, for whatever reason, we can't determine a node's binary or cluster version within 10s.

**roachtest: make sure tenant is ready after restart in mixedversion**
This updates the start and restart steps in the mixedversion framework
to wait for the shared-process tenant (if any) to be able to handle
incoming requests before moving on, as the test plan generated by the
framework assumes that the tenant is able to handle connections after
the `start` step.

In rare occasions, it is possible for the tenant to have started but, by
the time the framework attempts to query internal debug information
from the tenant, the tenant is not ready to accept requests yet.

We retry for a short period of time until we are sure the tenant
server is up.

Epic: none

Release note: None

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]

**Comment by renatolabs** [comment]
TFTR!

bors r=srosenberg

**Comment by renatolabs** [comment]
bors cancel

**Comment by renatolabs** [comment]
CI managed to [reproduce](https://github.com/cockroachdb/cockroach/actions/runs/10182709305/job/28165930080) the issue originally reported by Darryl when the shared-process PR was up (https://github.com/cockroachdb/cockroach/pull/127393#pullrequestreview-2184105558).

I added another commit to this PR since that error is somewhat related to the original changes in this PR (connection to services). Specifically, what causes the error is the following sequence of events:

* framework creates the shared-process tenant on the cluster using roachprod's API. The SQL statement used to start the SQL server (`START SERVICE SHARED`) returns early and does not wait for the server to be ready to handle client requests.
* the next step in test starts to run and, as part of gathering debug data, we attempt to query the cluster version on the newly started tenant. That fails because the SQL server is still starting up.

This second commit in this PR deals with this situation by making sure the server is up before returning from the start or restart steps.

@srosenberg or @DarrylWong: mind taking another pass please?

**Review by DarrylWong — APPROVED** [review]
LGTM!

**Comment by renatolabs** [comment]
Things look good on this branch:

https://teamcity.cockroachdb.com/viewLog.html?buildId=16283252

TFTRs!

bors r=srosenberg,DarrylWong

**Pull request merged**
