### PR TITLE
all: fork span for async tasks

### PR DESCRIPTION
**Pull request by RaduBerinde**
Pass a context to `RunAsyncTask` and `RunLimitedAsyncTask`; create a child span
if necessary and pass the resulting context to the task.

Part of #9284.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9324)

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm:

The usual precautions for the master->develop merges apply.

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[server/admin.go, line 521 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9324#-KRZs0c1CxGoPepZwQTi:-KRZs0c1CxGoPepZwQTj:by6ro9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba81fafca66dd6d5dac70fae0d1f7f6d5ca5cce/server/admin.go#L521)):*
> ```Go
> 	// these queries.
> 	responses := make(chan nodeResponse)
> 	nodeCtx, cancel := context.WithTimeout(ctx, base.NetworkTimeout)
> ```

Mind commenting on the role of `nodeCtx` (I noticed you fixed a buglet below).

---

*[server/admin.go, line 934 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9324#-KRZtbB3eAZ4rtkypR3V:-KRZtbB3eAZ4rtkypR3W:b7eh8l6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba81fafca66dd6d5dac70fae0d1f7f6d5ca5cce/server/admin.go#L934)):*
> ```Go
> 			// won't run if the semaphore is full (or the node is draining).
> 			// Both are handled by the surrounding retry loop.
> 			if err := s.server.stopper.RunLimitedAsyncTask(context.Background(), sem,
> ```

There isn't a base context accessible from `*adminServer` (note that it has a reference to `*Server`).

---

*[storage/replica_raftstorage.go, line 321 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9324#-KRZuqaVcWMk1xwSBl95:-KRZuqaVcWMk1xwSBl96:b-ymjzra) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba81fafca66dd6d5dac70fae0d1f7f6d5ca5cce/storage/replica_raftstorage.go#L321)):*
> ```Go
> 	if r.store.Stopper().RunAsyncTask(ctx, func(ctx context.Context) {
> 		defer close(ch)
> 		sp := r.store.Tracer().StartSpan("snapshot async")
> ```

Weird that the span is created here when the main method here is already taking a context. It looks like there are only two callers, one of which is for testing only.

---

*[util/tracing/tracer.go, line 96 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9324#-KRZvT96NBM_9YlMZNtb:-KRZvT96NBM_9YlMZNtc:b-pj7nfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba81fafca66dd6d5dac70fae0d1f7f6d5ca5cce/util/tracing/tracer.go#L96)):*
> ```Go
> }
> 
> // ForkCtxSpan checks if ctx has a Span open; if it does, it creates a new Span
> ```

I would personally `s/CtxSpan//` though I'll defer to your preference.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9324#-:-KRZvcb1HjdJx-bd2bf0:bxgacuu)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[server/admin.go, line 521 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9324#-KRZs0c1CxGoPepZwQTi:-KRZxrUkmiYWWL1aa1XA:bf9kygb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba81fafca66dd6d5dac70fae0d1f7f6d5ca5cce/server/admin.go#L521)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Mind commenting on the role of `nodeCtx` (I noticed you fixed a buglet below).
</details>
I didn't fix anything (other than forking the span), we're still using `nodeCtx` as our base context.

---

*[server/admin.go, line 934 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9324#-KRZtbB3eAZ4rtkypR3V:-KRZyEXEVMa0-0DTdmyG:b-wtehjg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba81fafca66dd6d5dac70fae0d1f7f6d5ca5cce/server/admin.go#L934)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> There isn't a base context accessible from `*adminServer` (note that it has a reference to `*Server`).
</details>
Not yet, it's on my todo list to add contexts to this stuff (and a few other similar things in server). Anyway, we're not using the context here at all.

---

*[storage/replica_raftstorage.go, line 321 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9324#-KRZuqaVcWMk1xwSBl95:-KRZys6TtvyHhPdPai6L:b-9vi5ot) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba81fafca66dd6d5dac70fae0d1f7f6d5ca5cce/storage/replica_raftstorage.go#L321)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Weird that the span is created here when the main method here is already taking a context. It looks like there are only two callers, one of which is for testing only.
</details>
Hm this is very strange. It doesn't seem we are actually using the span. Maybe it's still useful to track the duration of a snapshot? Either way, we should put it in ctx so the log messages go to it..

It would make sense to start a span here if the context we are given here normally doesn't contain a span.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9324)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[server/admin.go, line 521 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9324#-KRZs0c1CxGoPepZwQTi:-KR_12QqiNcoY80eTqqI:b9pmyso) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba81fafca66dd6d5dac70fae0d1f7f6d5ca5cce/server/admin.go#L521)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I didn't fix anything (other than forking the span), we're still using `nodeCtx` as our base context.
</details>
Ah, you're right. Shouldn't this be the main context below though?

---

*[server/admin.go, line 545 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9324#-KR_19UW9pC1qWyg2Wcc:-KR_19UW9pC1qWyg2Wcd:bb6wzo5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba81fafca66dd6d5dac70fae0d1f7f6d5ca5cce/server/admin.go#L545)):*
> ```Go
> 			case responses <- response:
> 				// Response processed.
> 			case <-ctx.Done():
> ```

Here

---

*[storage/replica_raftstorage.go, line 321 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9324#-KRZuqaVcWMk1xwSBl95:-KR_1H9OxYZe2uAic48L:bx974t3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba81fafca66dd6d5dac70fae0d1f7f6d5ca5cce/storage/replica_raftstorage.go#L321)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Hm this is very strange. It doesn't seem we are actually using the span. Maybe it's still useful to track the duration of a snapshot? Either way, we should put it in ctx so the log messages go to it..
> 
> It would make sense to start a span here if the context we are given here normally doesn't contain a span.
</details>
Looks ok the way it is for now. We might reconsider if we decide to trace more Raft operations (but most of them are so short-lived that that would be a lot of churn).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9324)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[server/admin.go, line 521 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9324#-KRZs0c1CxGoPepZwQTi:-KR_4hXgD-Vp-oDhl4Qw:bsdghwm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba81fafca66dd6d5dac70fae0d1f7f6d5ca5cce/server/admin.go#L521)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Ah, you're right. Shouldn't this be the main context below though?
</details>
`ctx` is based off of `nodeCtx`. It has the same `Done`. It is identical except the span.

---

*[storage/replica_raftstorage.go, line 321 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9324#-KRZuqaVcWMk1xwSBl95:-KR_4oR762DgbW9s0F5S:b-a83f4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba81fafca66dd6d5dac70fae0d1f7f6d5ca5cce/storage/replica_raftstorage.go#L321)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Looks ok the way it is for now. We might reconsider if we decide to trace more Raft operations (but most of them are so short-lived that that would be a lot of churn).
</details>
I should at least put it in `ctx` so the messages/errors make it in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9324)*

**Pull request merged**
