### PR TITLE
changefeedccl: Rework sink flushing behavior.

### PR DESCRIPTION
**Pull request by miretskiy**
The purpose of this change is to improve changefeed scalability,
particularly when dealing with large tables, by eliminating
unnecessary sink flushes and reducing the number and the frequency
of messages between change aggregator and change frontier.

Prior to this PR, change aggregator would flush its sink every
`resolved` seconds (5 seconds by default, but could be more rapid).
In addition, change aggregator would also collect and flush the set
of spans that have been resolved since the last flush.
Flushes every `resolved` seconds are unnecessary.

In particular, the reason why the sink is flushed is because
by forwarding resolved span messages to the change frontier, we can
cause the frontier to checkpoint high water mark progress -- and before
we do that, we must make sure all messages below watermark have been
emitted.  However, the change frontier will never be able to checkpoint
high water mark until all of the aggregator frontiers have advanced.
Therefore, we only need to forward resolved spans once local aggregator
frontier advances.

This PR accomplishes this by utilizing span frontier to determine
when local aggregator frontier advances and forwards resolved spans once
that happens.

A "side effect" of this change is that we no longer need to keep track
of update time in the span frontier -- so, that code has been removed as
it is no longer used.

Release Notes: Changefeed will now flush the sink only when frontier
advances.  This elliminates unnecessary sink flushes.

### CODE REVIEW

**Review by HonoreDB — COMMENTED** [review]
How does this interact with throttling and pushback? Specifically, is there a scenario where we're waiting on a flush in order to free up some quota that's necessary to advance the frontier?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67988#-:-MfK7Zoc8IAOpQSOHdRb:bk88f9q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @stevendanna)

**Review by miretskiy — COMMENTED** [review]
I think it interacts fine.  Let's not conflate flushing because we want to checkpoint with sink flushing because it has buffered enough data.  If we can't flush the sink, we won't forward resolved spans, and thus won't checkpoint. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67988#-:-MfK9g9I3tS0pPbau4oR:b-ccislb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @stevendanna)

**Comment by amruss** [comment]
Does this impact resolved messages at all (the ones we send to the sink)?

**Comment by miretskiy** [comment]
Not that I can see -- we never send resolved messages to the sink until frontier advances.

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67988)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @miretskiy)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/67988#-MfbW75OBwBVT2lVQjDC:-MfbW75OBwBVT2lVQjDD:bck1ah) (no related file):*
Is the change from sending `ResolvedSpan` to `ResolvedSpans` going to be a problem in multi-version clusters when we go to unmarshal the message in the change frontier?  I believe that:

Trying to unmarshal a `ResolvedSpan` as a `ResolvedSpans` will result in an error.
Trying to unmarshal a `ResolvedSpans` as a `ResolvedSpan` will result in a zero-valued message.

---

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67988)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @miretskiy)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 518 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67988#-MfbiWXa48_4y4DmSV-m:-MfbiWXa48_4y4DmSV-n:b-s949gk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d4891d4454f7af690ab13f060fdede8791c8f1/pkg/ccl/changefeedccl/changefeed_processors.go#L518)):*
> ```Go
> 		defer func() {
> 			ca.lastFlush = timeutil.Now()
> 		}()
> ```

We would previously only reset lastFlush if the flush was successful. Now, it appears we always reset it, is this definitely what we want?

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67988)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/67988#-MfbW75OBwBVT2lVQjDC:-Mfbqui_1hEjjQVvHvBU:b-d3p47b) (no related file):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Is the change from sending `ResolvedSpan` to `ResolvedSpans` going to be a problem in multi-version clusters when we go to unmarshal the message in the change frontier?  I believe that:

Trying to unmarshal a `ResolvedSpan` as a `ResolvedSpans` will result in an error.
Trying to unmarshal a `ResolvedSpans` as a `ResolvedSpan` will result in a zero-valued message.

</blockquote></details>

Argh; I thought it was okay because these were never persisted; good point. I'm going to backout of this change.
It's a bummer, but I don't feel strongly enough to keep it w/ cluster version guards.  As is, I suspect the number and the rate of emitted resolved messages will be rather small.

---
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 518 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67988#-MfbiWXa48_4y4DmSV-m:-MfbqocyEoS4m1KXM2wF:btjbsq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d4891d4454f7af690ab13f060fdede8791c8f1/pkg/ccl/changefeedccl/changefeed_processors.go#L518)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

We would previously only reset lastFlush if the flush was successful. Now, it appears we always reset it, is this definitely what we want?
</blockquote></details>

If we fail, we will tear down the flow anyway.

**Comment by miretskiy** [comment]
@stevendanna @HonoreDB
Rebased; Ready for another look..

**Review by stevendanna — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67988)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @miretskiy, and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/67988#-Mg6VIQG5BpNdSGGTxvD:-Mg6VIQG5BpNdSGGTxvE:b-jwg5n5) (no related file):*
:lgtm: 

We now have a few mechanisms working together to reduce the amount of resolved span processing and job progress updating that needs to happen:

1) changeAggregators use a frontier to buffer seen spans. The frontier merges adjacent spans so we hopefully forward updates for a smaller number (but larger) spans.
2) changeAggregators only forward spans when the frontier actually advances
3) changeFrontiers skips job updates if they are happening too rapidly

---
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 515 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67988#-Mg6SWdB24XxqlbBI7rV:-Mg6SWdB24XxqlbBI7rW:b5c7vly) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d43fa38f153b8abb444b5bfa8a91aecfee5514d/pkg/ccl/changefeedccl/changefeed_processors.go#L515)):*
> ```Go
> 	forceFlush := resolved.BoundaryType != jobspb.ResolvedSpan_NONE
> 	checkpointFrontier := advanced &&
> 		(forceFlush || ca.lastFlush.Add(ca.flushFrequency).Before(timeutil.Now()))
> ```

Note to self: I think because of how the "kvfeed" works when it hits a boundary this is correct, because it will put out a resolved span for every span with the BoundaryType set:

https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/changefeedccl/kvfeed/kv_feed.go#L229

I think this line is the one I've stared at the longest in this PR. Perhaps because the naming of `forceFlush` (maybe `schemaChangeBoundary` or something).

**Comment by miretskiy** [comment]
tftr
bors r=stevendanna

**Pull request merged**
