### PR TITLE
opt: Use protobuf ZoneConfig.Equal method instead of custom method

### LINKED ISSUE #36451: ccl/logictestccl: TestCCLLogic failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/c6df752eefe4609b8a5bbada0955f79a2cfb790e

Parameters:
```
TAGS=
GOFLAGS=-parallel=4
```

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=TestCCLLogic PKG=github.com/cockroachdb/cockroach/pkg/ccl/logictestccl TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1217865&tab=buildLog

```
=== RUN   TestCCLLogic
--- FAIL: TestCCLLogic (47.49s)
    test_log_scope.go:81: test logs captured to: /tmp/logTestCCLLogic865338793
    test_log_scope.go:62: use -show-logs to present logs inline
=== RUN   TestCCLLogic/5node-dist-opt
    --- FAIL: TestCCLLogic/5node-dist-opt (0.00s)
=== RUN   TestCCLLogic/5node-dist-opt/zone
=== PAUSE TestCCLLogic/5node-dist-opt/zone
=== CONT  TestCCLLogic/5node-dist-opt/zone
--- done: testdata/logic_test/zone with config 5node-dist-opt: 24 tests, 0 failures
--- total: 274 tests, 0 failures
test logs left over in: /tmp/logTestCCLLogic865338793
        --- FAIL: TestCCLLogic/5node-dist-opt/zone (45.87s)
            logic.go:1536: condition failed to evaluate within 45s: 
                testdata/logic_test/zone:151: EXPLAIN SELECT * FROM t WHERE k=10
                expected:
                    scan  ·      ·
                    ·     table  t@tertiary
                    ·     spans  /10-/11
                    
                but found (query options: "retry") :
                    scan  ·      ·
                    ·     table  t@primary
                    ·     spans  /10-/10/#
                    
                
                goroutine 3387 [running]:
                runtime/debug.Stack(0xa7a358200, 0xc004197a70, 0x39250e0)
                	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
                github.com/cockroachdb/cockroach/pkg/testutils.SucceedsSoon(0x3992e20, 0xc002a16000, 0xc002ec3d60)
                	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:49 +0x103
                github.com/cockroachdb/cockroach/pkg/sql/logictest.(*logicTest).processSubtest(0xc0010cf680, 0x0, 0x0, 0xc00315d3b0, 0x0, 0xc0002d6260, 0x18, 0x322d72f, 0xe, 0x5, ...)
                	/go/src/github.com/cockroachdb/cockroach/pkg/sql/logictest/logic.go:1536 +0x1da2
                github.com/cockroachdb/cockroach/pkg/sql/logictest.(*logicTest).processTestFile(0xc0010cf680, 0xc0002d6260, 0x18, 0x322d72f, 0xe, 0x5, 0x0, 0x3219045, 0x2, 0x3219045, ...)
                	/go/src/github.com/cockroachdb/cockroach/pkg/sql/logictest/logic.go:1186 +0x698
                github.com/cockroachdb/cockroach/pkg/sql/logictest.(*logicTest).runFile(0xc0010cf680, 0xc0002d6260, 0x18, 0x322d72f, 0xe, 0x5, 0x0, 0x3219045, 0x2, 0x3219045, ...)
                	/go/src/github.com/cockroachdb/cockroach/pkg/sql/logictest/logic.go:2085 +0xe1
                github.com/cockroachdb/cockroach/pkg/sql/logictest.RunLogicTest.func1.1(0xc002a16000)
                	/go/src/github.com/cockroachdb/cockroach/pkg/sql/logictest/logic.go:2196 +0x1cc
                testing.tRunner(0xc002a16000, 0xc0029b74a0)
                	/usr/local/go/src/testing/testing.go:827 +0xbf
                created by testing.(*T).Run
                	/usr/local/go/src/testing/testing.go:878 +0x35c

```

### PR DESCRIPTION
**Pull request by andy-kimball**
In some cases, an outdated ZoneConfig wasn't being detected due to a
bug in the zonesAreEqual method. Rather than fix that, I realized that
protobuf already generates an Equal method which does the same thing,
and yet will automatically be updated if we add any fields to the
ZoneConfig. Switch to use Equal instead, and remove the custom equality
method.

Fixes #36451

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Great, thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36509#-:-LbaMRKxAZn-d0qocpyJ:b-cd7l7e)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt_catalog.go, line 1050 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36509#-LbaMNKyBbVNrGNFJES3:-LbaMNKyBbVNrGNFJES4:b-nuqdal) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6b3c540b696002b2ed07036a657612995d6d1ab/pkg/sql/opt_catalog.go#L1050)):*
> ```Go
> 		}
> 
> 		return zonesAreEqual(&leftSubzone.Config, &rightSubzone.Config)
> ```

the bug was on this line?

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36509)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt_catalog.go, line 1050 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36509#-LbaMNKyBbVNrGNFJES3:-LbaTdUb8MPIOBvZbSFE:b-15fki0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6b3c540b696002b2ed07036a657612995d6d1ab/pkg/sql/opt_catalog.go#L1050)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

the bug was on this line?
</blockquote></details>

I didn't delve further, once I realized it was a comparison bug, and then realized I could just use `Equal` (I realized this because of the other work I've been doing with SQL `ColumnType`, where I'm using `Equal`).

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36509#-:-LbdLV0n1GX_GPX4da6n:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)

**Pull request merged**
