### PR TITLE
sql: make CREATE STATISTICS work properly with EXPLAIN ANALYZE (DEBUG)

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: migrate other EXPLAIN variants to new exec factory interface

This change migrates the other EXPLAIN variants to the new interface,
which uses an explain factory to build the explained plan.

This fixes a TODO in the experimental factory.

Release note: None

#### opt: add operator for CREATE STATISTICS

This change adds an optimizer operator for CREATE STATISTICS (instead
of using the opaque operator).

Release note: None

#### sql: reimplement EXPLAIN handling of CREATE STATISTICS

CREATE STATISTICS runs the statistics plan inside a job. The plan node
tree ends in a dead end at the createStatsNode. For explain purposes,
we want to see information about the actual plan that runs inside the
job.

The current solution is to pretend that we build the plan directly in
certain contexts. This solution is hard to extend for the new
top-level instrumentation for EXPLAIN ANALYZE.

This commit changes this solution to add a `runAsJob` flag and
actually plan the distributed plan directly when we don't run as a
job. We automatically set `runAsJob=false` whenever we are building
inside Explain.

Release note: None

#### sql: make CREATE STATISTICS work properly with EXPLAIN ANALYZE (DEBUG)

With this change, the bundle now contains the diagram for the
underlying plan.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 6 files at r1, 16 of 16 files at r2, 7 of 7 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57606#-:-MNz8WBME-DG_EkktBx-:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/instrumentation.go, line 264 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57606#-MNz80Br-wDT_iVmbgvc:-MNz80BsDvIrFX17YA-v:b-6dufxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/14e9ad68bd256cca1674d7c2751d952506e1acb6/pkg/sql/instrumentation.go#L264)):*
> ```Go
> // EXPLAIN ANALYZE, in which case we want to run any CREATE STATISTICS plan
> // directly (and not through a job).
> func (ih *instrumentationHelper) ShouldInlineCreateStatsJob() bool {
> ```

[nit] this name doesn't really explain what this function does. "inline" seems a bit far from "don't run as a job".

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57606)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/sql/instrumentation.go, line 264 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57606#-MNz80Br-wDT_iVmbgvc:-MNzCTVPAd2Wk-5mAgsO:b-end7sg) ([raw file](https://github.com/cockroachdb/cockroach/blob/14e9ad68bd256cca1674d7c2751d952506e1acb6/pkg/sql/instrumentation.go#L264)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] this name doesn't really explain what this function does. "inline" seems a bit far from "don't run as a job".
</blockquote></details>

Done. Inverted to `ShouldUseCreateStatsJob()`.

**Review by rytaft — APPROVED** [review]
> Reviewed 13 of 16 files at r6, 6 of 7 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57606)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
