### PR TITLE
tracing: untangle local/remove parent vs recording collection

### PR DESCRIPTION
**Pull request by andreimatei**
Before this patch, two concepts were bundled together: whether or not
the parent of a span is local or remote to the child's node, and whether
or not the parent should include the child in its recording. You could
create a child span with either:
- the WithParentAndAutoCollection option, which would give you a local
  parent which includes the child in its recording, or
- the WithParentAndManualCollection option, which would give you a
  remote parent (which naturally would not / couldn't include the child
  in its recording).

The WithParentAndManualCollection is sometimes used even when the parent
is local, which is a) quite confusing, because at a lower level it
produced what was called a "remote parent" and b) sub-optimal, because
the child looked like a "local root", which meant it had to be put into
the active spans registry. Were it not for the bundling of the two
concerns together, such a child of a local parent, but for whom the
parent is not in charge of collecting the recording, would not need to
be put directly into the span registry; such a span (like other child
spans) should be part of the registry indirectly, through its parent -
which is cheaper because it doesn't add contention on the global mutex
lock.

The funky case of a local parent whose recording does not include the
child's is used by DistSQL processors - each processor gets a span whose
recording is collected by the DistSQL infrastructure, independent of the
parent.

This patch untangles the parent-child relationship from the
recording collection concern, and cleans up the API in the process. Now
you have the following options for creating a span:

WithParent(parent) - creates a parent/child relationship. The parent has
a reference to the child. The child is part of the active spans registry
through the parent. Unless WithDetachedRecording() is also specified,
the parent's recording includes the child's.

WithRemoteParent(parentMeta) - creates a parent/child relationship
across process boundaries.

WithDetachedRecording() - asks the parent to not include the new child
in its recording. This is a no-op in case WithRemoteParent() is used.
This option is used by DistSQL.

So, we get a cleaner API, and a more efficient active spans registry
implementation because the DistSQL spans are no longer directly part of
it. Also, we open the door for a new possibility in the future: you can
imagine that, in certain scenarios, it'd be interesting for a span to
collect the recording of all its children, including the ones whose
recording, under normal circumstances, is not the parent's
responsibility to collect. For example, when asking for the recording of
a span in the registry in an out-of-band way (i.e. when debugging), I
want all the info I can get. So, I should be able to point to a DistSQL
flow span and ask it for the recording of all processors on its node.
This is not implemented yet.

Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
Only the last 3 commits are to be reviewed here. The rest are test fixes sent out separately.

**Review by abarganier — APPROVED** [review]
:lgtm: with a nit and minor question. Overall I think this decoupling makes a lot of sense, and makes API much more intuitive. Well done!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72898#-:-MpCxf1KEjXd3RdWOXms:b-qfll3n)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier and @andreimatei)

___
*[pkg/util/tracing/crdbspan.go, line 652 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/72898#-MpCuhLc84LMYu16guns:-MpCuhLc84LMYu16gunt:b-2vo7jo) ([raw file](https://github.com/cockroachdb/cockroach/blob/648c169fec330f7aaa03ac284b9444e87ff85353/pkg/util/tracing/crdbspan.go#L652)):*
> ```
> "should have been handled above"
> ```
nit: can this be more descriptive? I imagine this message would be cryptic if we somehow hit this condition.  
___
*[pkg/util/tracing/span_options.go, line 64 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/72898#-MpCwNGi67iHmiwHdkk8:-MpCwNGi67iHmiwHdkk9:b-lnw8ew) ([raw file](https://github.com/cockroachdb/cockroach/blob/648c169fec330f7aaa03ac284b9444e87ff85353/pkg/util/tracing/span_options.go#L64)):*
> ```
> parentDoesNotCollectRecording bool
> ```
Why make this field private when the rest are public?

**Review by knz — COMMENTED** [review]
LGTM for all the changes other than the changes to the `tracing` package in the last commit. For that you can take a review from someone else.

> Reviewed 18 of 18 files at r15, 12 of 12 files at r16, 26 of 35 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72898#-:-MpD0Rc_CNbq8eHLefcO:b86t0ul)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @andreimatei, and @knz)

___
*[pkg/kv/kvserver/replica_application_decoder.go, line 156 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/72898#-MpCVzaD5v3Ta_Ge-QPl:-MpCVzaEALfW0T2sTyKl:b-bginlb) ([raw file](https://github.com/cockroachdb/cockroach/blob/648c169fec330f7aaa03ac284b9444e87ff85353/pkg/kv/kvserver/replica_application_decoder.go#L156)):*
> ```Go
> 					opName,
> 					// NB: Nobody is collecting the recording of this span; we have no
> 					// mechanism for it.
> ```

Does this need a followup issue?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72898)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier and @knz)

___
*[pkg/kv/kvserver/replica_application_decoder.go, line 156 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/72898#-MpCVzaD5v3Ta_Ge-QPl:-MplVyTN0Q9jtq8f8WEi:b-lwioe) ([raw file](https://github.com/cockroachdb/cockroach/blob/648c169fec330f7aaa03ac284b9444e87ff85353/pkg/kv/kvserver/replica_application_decoder.go#L156)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Does this need a followup issue?
</blockquote></details>

I don't think so... It's hard to imagine who'd collect recordings for async application and what they'd do with them...
___
*[pkg/util/tracing/crdbspan.go, line 652 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/72898#-MpCuhLc84LMYu16guns:-MplXMXdEo78ZMGx_Dhy:bqwu7x9) ([raw file](https://github.com/cockroachdb/cockroach/blob/648c169fec330f7aaa03ac284b9444e87ff85353/pkg/util/tracing/crdbspan.go#L652)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
> "should have been handled above"
> ```
nit: can this be more descriptive? I imagine this message would be cryptic if we somehow hit this condition.  
</blockquote></details>

well I'm not sure what to say other than "shouldn't get here". If anyone runs into this, they'll have to read the source for context. More realistically, they'll need to read the source from the time when the assertion was introduced. I think it's a fairly common pattern to have complete `switches` like this and explicitly mark the impossible branches.
___
*[pkg/util/tracing/span_options.go, line 64 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/72898#-MpCwNGi67iHmiwHdkk8:-MplYSPz5bbQVWbUnSKV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/648c169fec330f7aaa03ac284b9444e87ff85353/pkg/util/tracing/span_options.go#L64)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
> parentDoesNotCollectRecording bool
> ```
Why make this field private when the rest are public? 
</blockquote></details>

Done.

**Review by andreimatei — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72898#-:-MpmJItq7Ru6-Ncv6xGy:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier and @knz)

**Comment by andreimatei** [comment]
TestComposeGSS flake

bors r+

**Pull request merged**
