### PR TITLE
storageccl: don't clear existing data in AddSSTable

### PR DESCRIPTION
**Pull request by danhhz**
Any given AddSSTable command needs to be idempotent, so we can retry it
(in the face of AmbiguousResultError, etc). Previously, this was
accomplished by clearing the request span before ingest. This meant that
when the request completed successfully, the affected span contained
exactly the data in the payload sstable.

Instead, ingest the file and adjust MVCCStats as appropriate. Motivations:

- An unlikely race condition in the upcoming resumable RESTORE
  coordinator work. It will be possible that one half of a split-brain
  RESTORE will finish and expose the table publicly for writes before
  the other half gets off one last AddSSTable. This would destroy user
  data in a subtle, non-transactional way.

- Adding a range tombstone basically guarantees that the ingested
  sstable will be placed in L0 instead of some lower level, increasing
  read amplification.

### CODE REVIEW

**Comment by danhhz** [comment]
The first commit is in another PR and I need to rewrite TestAddSSTableMVCCStats but the rest of this is ready for review.

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17079#-:-KpLdbVxk_huxHmn3gXL:bnfp4nl)*

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/storageccl/add_sstable.go, line 49 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17079#-KpLk0ipW3gbAPYGdKBY:-KpLk0ipW3gbAPYGdKBZ:b4wxn7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/10f29380c1cb73dd2700ca859e73cab38b677c85/pkg/ccl/storageccl/add_sstable.go#L49)):*
> ```Go
> 	// being ingested can overwrite all, some, or none of the existing kvs.
> 	// (Note: the expected case is that it's none or, in the case of a retry of
> 	// the request, all.) So subtract out the existing mvcc stats, and add back
> ```

Misplaced `.`.

---

*[pkg/ccl/storageccl/add_sstable.go, line 59 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17079#-KpLk8fNbgSl08ayc1hN:-KpLk8fNbgSl08ayc1hO:bpc4g2k) ([raw file](https://github.com/cockroachdb/cockroach/blob/10f29380c1cb73dd2700ca859e73cab38b677c85/pkg/ccl/storageccl/add_sstable.go#L59)):*
> ```Go
> 		log.Eventf(ctx, "target key range not empty, will merge existing data with sstable")
> 	}
> 	existingStats, err := existingIter.ComputeStats(mvccStartKey, mvccEndKey, h.Timestamp.WallTime)
> ```

This is cheap when there isn't any data, right?

---

*[pkg/ccl/storageccl/add_sstable.go, line 116 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17079#-KpLkQks4FJT6bLoFa4x:-KpLkQks4FJT6bLoFa4y:baczjk4) ([raw file](https://github.com/cockroachdb/cockroach/blob/10f29380c1cb73dd2700ca859e73cab38b677c85/pkg/ccl/storageccl/add_sstable.go#L116)):*
> ```Go
> 	}
> 
> 	mergedIter := engineccl.MakeMultiIterator([]engine.SimpleIterator{existingIter, dataIter})
> ```

Perhaps add a comment about the importance of the ordering `{existingIter, dataIter}`.

---

*[pkg/ccl/storageccl/writebatch.go, line 83 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17079#-KpLkqtm8Z8XU4lycZk4:-KpLkqtm8Z8XU4lycZk5:bnha655) ([raw file](https://github.com/cockroachdb/cockroach/blob/10f29380c1cb73dd2700ca859e73cab38b677c85/pkg/ccl/storageccl/writebatch.go#L83)):*
> ```Go
> }
> 
> func clearExistingData(
> ```

Is this still called?

---

*[pkg/ccl/storageccl/engineccl/multi_iterator.go, line 29 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17079#-KpLiQbdC03CLgSaCRg3:-KpLiQbdC03CLgSaCRg4:b-lwe5je) ([raw file](https://github.com/cockroachdb/cockroach/blob/28c1c709cc85f66dc019f141f05dedee116d7e68/pkg/ccl/storageccl/engineccl/multi_iterator.go#L29)):*
> ```Go
> 	// The indexes of every iterator with the same key and timestamp as the one
> 	// in currentIdx.
> 	itersWithCurrentKeyTimestamp []int
> ```

Not suggesting that you necessarily should, but could you remove `currentIdx` and just make that the last entry in `itersWithCurrentKeyTimestamp`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17079#-:-KpLksvTODZbWCmlEPL8:bnfp4nl)*

**Comment by danhhz** [comment]
Thanks for the reviews! Finished the test. RFAL

---

Review status: 2 of 7 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/storageccl/add_sstable.go, line 49 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17079#-KpLk0ipW3gbAPYGdKBY:-KpMJiLThCQLhoTpqkkE:bcemzfy) ([raw file](https://github.com/cockroachdb/cockroach/blob/10f29380c1cb73dd2700ca859e73cab38b677c85/pkg/ccl/storageccl/add_sstable.go#L49)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Misplaced `.`.
</blockquote></details>

Really? Where? Why?

---

*[pkg/ccl/storageccl/add_sstable.go, line 59 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17079#-KpLk8fNbgSl08ayc1hN:-KpMJabRZrYqIXyEWD21:bkdmp06) ([raw file](https://github.com/cockroachdb/cockroach/blob/10f29380c1cb73dd2700ca859e73cab38b677c85/pkg/ccl/storageccl/add_sstable.go#L59)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

This is cheap when there isn't any data, right?
</blockquote></details>

Added a note

---

*[pkg/ccl/storageccl/add_sstable.go, line 116 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17079#-KpLkQks4FJT6bLoFa4x:-KpMKTU5SFRoEO254ka2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/10f29380c1cb73dd2700ca859e73cab38b677c85/pkg/ccl/storageccl/add_sstable.go#L116)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Perhaps add a comment about the importance of the ordering `{existingIter, dataIter}`.
</blockquote></details>

Done.

---

*[pkg/ccl/storageccl/writebatch.go, line 83 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17079#-KpLkqtm8Z8XU4lycZk4:-KpMKU67dBO0Y7SmZvgN:b-oa41ee) ([raw file](https://github.com/cockroachdb/cockroach/blob/10f29380c1cb73dd2700ca859e73cab38b677c85/pkg/ccl/storageccl/writebatch.go#L83)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Is this still called?
</blockquote></details>

Yeah, in WriteBatch. I haven't worked through how the migration for it would work (and won't before 1.1)

---

*[pkg/ccl/storageccl/engineccl/multi_iterator.go, line 29 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17079#-KpLiQbdC03CLgSaCRg3:-KpMKcQdyILRLYDijicD:b-czja39) ([raw file](https://github.com/cockroachdb/cockroach/blob/28c1c709cc85f66dc019f141f05dedee116d7e68/pkg/ccl/storageccl/engineccl/multi_iterator.go#L29)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Not suggesting that you necessarily should, but could you remove `currentIdx` and just make that the last entry in `itersWithCurrentKeyTimestamp`?
</blockquote></details>

I think that would work

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17079#-:-KpMLQhF1EpsaDBNlADZ:bc4osam)*

**Comment by tschottdorf** [comment]
Reviewed 3 of 3 files at r4, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/storageccl/add_sstable.go, line 49 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17079#-KpLk0ipW3gbAPYGdKBY:-KpMPwHVrAkyGGhkzFoR:b-9ulekn) ([raw file](https://github.com/cockroachdb/cockroach/blob/10f29380c1cb73dd2700ca859e73cab38b677c85/pkg/ccl/storageccl/add_sstable.go#L49)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Really? Where? Why?
</blockquote></details>

The comment isn't here any more.

---

*[pkg/ccl/storageccl/add_sstable_test.go, line 195 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/17079#-KpMQEHtrdhn0cj-d-SQ:-KpMQEHtrdhn0cj-d-SR:b-vvodaa) ([raw file](https://github.com/cockroachdb/cockroach/blob/883cb7405e67b5e3c855c6f9ff38e35947af6bff/pkg/ccl/storageccl/add_sstable_test.go#L195)):*
> ```Go
> func TestAddSSTableMVCCStats(t *testing.T) {
> 	defer leaktest.AfterTest(t)()
> 	rng, _ := randutil.NewPseudoRand()
> ```

Probably want to log the seed because if it fails, then what?

---

*[pkg/ccl/storageccl/add_sstable_test.go, line 236 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/17079#-KpMQo73PYGum45Ut8iq:-KpMQo73PYGum45Ut8ir:bqec5al) ([raw file](https://github.com/cockroachdb/cockroach/blob/883cb7405e67b5e3c855c6f9ff38e35947af6bff/pkg/ccl/storageccl/add_sstable_test.go#L236)):*
> ```Go
> 
> 		var sstBytes []byte
> 		{
> ```

Make this `func() { }()` so that the `defer` within fires more coherently.

---

*[pkg/ccl/storageccl/writebatch.go, line 83 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17079#-KpLkqtm8Z8XU4lycZk4:-KpMQW1JjmK-AEhiP0V4:b-oxxi88) ([raw file](https://github.com/cockroachdb/cockroach/blob/10f29380c1cb73dd2700ca859e73cab38b677c85/pkg/ccl/storageccl/writebatch.go#L83)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Yeah, in WriteBatch. I haven't worked through how the migration for it would work (and won't before 1.1)
</blockquote></details>

Gotcha. Seems like you might be able to toss this out for free when 1.1->1.2 happens (I suppose we don't allow upgrades from 1.0 to 1.2).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17079)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/storageccl/writebatch.go, line 83 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17079#-KpLkqtm8Z8XU4lycZk4:-KpMRCj_fEL5zI32mp_l:be0rwqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/10f29380c1cb73dd2700ca859e73cab38b677c85/pkg/ccl/storageccl/writebatch.go#L83)):*
>  (I suppose we don't allow upgrades from 1.0 to 1.2)

Correct. We'll require that you are running 1.1 and have set the cluster's "use version" setting (or whatever that ends up being called) to 1.1 before beginning the process to upgrade to 1.2.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17079)*

**Comment by danhhz** [comment]
Review status: 6 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/ccl/storageccl/add_sstable_test.go, line 195 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/17079#-KpMQEHtrdhn0cj-d-SQ:-KpMU5KZnEgMXNbOcycA:brb8yqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/883cb7405e67b5e3c855c6f9ff38e35947af6bff/pkg/ccl/storageccl/add_sstable_test.go#L195)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Probably want to log the seed because if it fails, then what?
</blockquote></details>

Whoops, yep. Meant to do this and forgot. Thanks

---

*[pkg/ccl/storageccl/add_sstable_test.go, line 236 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/17079#-KpMQo73PYGum45Ut8iq:-KpMUZe-aTOpsOMUa8OQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/883cb7405e67b5e3c855c6f9ff38e35947af6bff/pkg/ccl/storageccl/add_sstable_test.go#L236)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Make this `func() { }()` so that the `defer` within fires more coherently.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17079)*

**Pull request merged**
