### PR TITLE
roachtest: add unquiesced version of kv/splits

### PR DESCRIPTION
**Pull request by tbg**
See https://github.com/cockroachdb/cockroach/issues/30832, where we suspect
that the cluster can't sustain the large number of ranges assuming they for
some reason unquiesce. We expect to see this new test grind to a halt every
time, with symptoms similar to those observed in the issue.

Note that both tests have been marked as UNSTABLE, for we know they are not
stable.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm: thanks! How does the new test do? Does it ever pass?

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30912#-:-LNuObtB6lzvBDSQ6GVy:b-uih1ln)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by tschottdorf** [comment]
Gonna try before I merge.

**Comment by tschottdorf** [comment]
The unquiesced version ground to a halt before the cluster was destroyed (12h).

**Comment by tschottdorf** [comment]
We might decide to skip the quiesced=false test if we find that we can't fix it within a reasonable amount of time, but I'm going to go ahead and merge it as enabled for now.

bors r=nvanbenschoten

**Pull request merged**
