### PR TITLE
storageccl: fix "empty sstable" log spam

### LINKED ISSUE #14178: backup: audit all possible zero-entry files
views, empty tables, and incremental with no changes (and maybe other situations) can emit empty sstables, which are invalid.

### PR DESCRIPTION
**Pull request by danhhz**
Closes #14178.

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm_strong: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/ccl/storageccl/export.go, line 111 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15467#-KipDTSrfC1cewdsBYhu:-KipDTSrfC1cewdsBYhv:b-m5dj81) ([raw file](https://github.com/cockroachdb/cockroach/blob/9073e0d58cdccc8b069c2ba29d495fe8d2c0e8f4/pkg/ccl/storageccl/export.go#L111)):*
> ```Go
> 		// path. If the sstable was empty, ignore the error because empty
> 		// sstables are not allowed.
> 		if closeErr := sst.Close(); sst.DataSize > 0 && closeErr != nil {
> ```

while you're here, could you call this variable simply `err`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15467#-:-KipDeZrkhZH6ZlrRoC3:b-uwkowd)*

**Comment by danhhz** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/ccl/storageccl/export.go, line 111 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15467#-KipDTSrfC1cewdsBYhu:-KipHMpsjfsltilbcgUP:beb3dt8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9073e0d58cdccc8b069c2ba29d495fe8d2c0e8f4/pkg/ccl/storageccl/export.go#L111)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

while you're here, could you call this variable simply `err`?
</blockquote></details>

Done. This also reminded me that I could un-name the return types

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15467)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/ccl/storageccl/export.go, line 111 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15467#-KipDTSrfC1cewdsBYhu:-KipJrRLXTF9NSezGgcD:b-83sjo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/9073e0d58cdccc8b069c2ba29d495fe8d2c0e8f4/pkg/ccl/storageccl/export.go#L111)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Done. This also reminded me that I could un-name the return types
</blockquote></details>

Nice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15467)*

**Comment by danhhz** [comment]
Thanks for the review!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15467#-:-KipLAcwYa7O233P_kt-:b-9qdoz3)*

**Pull request merged**
