### PR TITLE
server: introduce Test{ClusterConnectivity,JoinVersionGate}

### PR DESCRIPTION
**Pull request by irfansharif**
Re-adding a few tests that I didn't check in while working on #52526.

---

TestClusterConnectivity sets up an uninitialized cluster with custom join
flags (individual nodes point to specific others, constructed using
connectivity matrices). Included in the test configurations are the more
"standard" ones where every node points to n1, or where there are
bidirectional links set up between nodes. It tests various topologies
and ensures that cluster IDs are distributed throughout connected
components, and store/node IDs are allocated in the way we'd expect them
to be.

TestJoinVersionGate checks to see that improperly versioned cockroach
nodes are not able to join a cluster.

Release note: None

### CODE REVIEW

**Comment by irfansharif** [comment]
(Gentle ping. This PR is not super important, but would still give me some peace of mind.)

**Review by knz — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54072)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @tbg)

___
*[pkg/base/test_server_args.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54072#-MGsplov4zIKiQSmnsaT:-MGsplox-7MPveSEi4TD:be2jk7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/c36463e5b071ae5ada393454f7b310da43924ac2/pkg/base/test_server_args.go#L53)):*
> ```Go
> 	// manual control over how the join flags (`JoinAddr`) are populated, and
> 	// installs listeners manually to know which addresses to point to.
> 	Listener net.Listener
> ```

Curious: can you point me to the code responsible to close this?

(Maybe even include this pointer in the comment)
___
*[pkg/server/connectivity_test.go, line 176 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/54072#-MGsq3w7DGlNSD49nDFx:-MGsq3w7DGlNSD49nDFy:bxs3jvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/d27c908602763fe7edbfe09ba129b69e7c66d70a/pkg/server/connectivity_test.go#L176)):*
> ```Go
> 			//
> 			// NB: That aside, TestCluster very much wants to live on the main
> 			// goroutine running the test. THat's mostly to do with its internal
> ```

nit: typo

**Review by irfansharif — COMMENTED** [review]
Thanks for looking Rafa!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54072#-:-MGt0EjU0jR-Ij9hPKcU:bgicul6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @tbg)

___
*[pkg/base/test_server_args.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54072#-MGsplov4zIKiQSmnsaT:-MGt-leU0A_uriURmHOK:b82fo6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/c36463e5b071ae5ada393454f7b310da43924ac2/pkg/base/test_server_args.go#L53)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Curious: can you point me to the code responsible to close this?

(Maybe even include this pointer in the comment)
</blockquote></details>

It's here: https://github.com/irfansharif/cockroach/blob/d27c908602763fe7edbfe09ba129b69e7c66d70a/pkg/server/connectivity_test.go#L135-L138

Was included in the follow-on commit. It's accessible when jumping to usages now, so I'll skip the comment.
___
*[pkg/server/connectivity_test.go, line 176 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/54072#-MGsq3w7DGlNSD49nDFx:-MGt-kzhCHlcEK9Gb-WZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d27c908602763fe7edbfe09ba129b69e7c66d70a/pkg/server/connectivity_test.go#L176)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: typo
</blockquote></details>

Done.

**Comment by tbg** [comment]
Ugh, sorry for letting this slip again. Had the tab open but got distracted.

**Comment by irfansharif** [comment]
image

**Pull request merged**
