### PR TITLE
storageccl: Fix tests with ENABLE_ROCKSDB_ASSERTIONS

### PR DESCRIPTION
**Pull request by bdarnell**
Updates #23754. The only thing left is the makefile magic.

### CODE REVIEW

**Review by benesch — APPROVED** [review]
LGTM!

Re the Makefile magic: it's probably easiest to require that the user set `ENABLE_ROCKSDB_ASSERTIONS`, and then run `make testrace ENABLE_ROCKSDB_ASSERTIONS` in teamcity-testrace.sh. Trying to automatically infer whether to use the assertion-enabled build of RocksDB is fraught with peril. (E.g., what should `make test testrace` do?) I'm all ears if you have another solution, though.

**Comment by bdarnell** [comment]
I was assuming the makefile magic would be something like the line that adds `-race` to `GOFLAGS`:

https://github.com/cockroachdb/cockroach/blob/e54d51351ee83f753d80ce2d4cb6f88a6f8c77c2/Makefile#L757

But I'm not sure about the order of evaluations and whether this would actually work to set `ROCKSDB_DIR` appropriately. I'm fine with a solution that just sets the flag explicitly in teamcity rather than iterating on the Makefile, although it's kind of unfortunate to have this difference that we'd need to document.

**Comment by benesch** [comment]
> But I'm not sure about the order of evaluations and whether this would actually work to set ROCKSDB_DIR appropriately.

Yeah, that's exactly the problem. Target-specific variables are only available within the context of that target's recipe (and its prerequisites' recipes).

**Comment by bdarnell** [comment]
OK, added a commit to set this flag in `build/teamcity-*race.sh`

**Pull request merged**
