### PR TITLE
[dnm] storage: use engine.Batch in replica read codepath 

### PR DESCRIPTION
**Pull request by irfansharif**
By making this change, I observe `TestReplicaLookupUseReverseScan`
failing after being stuck emitting just the following:

```
W191220 03:55:37.815241 21 internal/client/range_lookup.go:259  range lookup of key "c" found only non-matching ranges []; retrying
W191220 03:55:37.816682 21 internal/client/range_lookup.go:259  range lookup of key "c" found only non-matching ranges []; retrying
W191220 03:55:37.818981 21 internal/client/range_lookup.go:259  range lookup of key "c" found only non-matching ranges []; retrying
W191220 03:55:37.824012 21 internal/client/range_lookup.go:259  range lookup of key "c" found only non-matching ranges []; retrying
```

This does not match with my expected behavior of NewBatch. Should the
behavior not be identical to when Engine().NewReadOnly() is used to
evaluate the read only command? If no, why not?

Release note: None

### CODE REVIEW

**Comment by irfansharif** [comment]
Welp, it looks like a hundred other tests are also broken. I didn't realize `engine.Batch`es didn't have a "read at snapshot of underlying engine at time of creation" guarantee.

**Review by petermattis — COMMENTED** [review]
> Welp, it looks like a hundred other tests are also broken. I didn't realize engine.Batches didn't have a "read at snapshot of underlying engine at time of creation" guarantee.

Huh. That's strange. `NewReadOnly` and `NewBatch` should have the same behavior with regards to snapshotting the underlying engine. In both cases, the snapshot does not occur until the first iterator is created.

I'm curious what is motivating this change, though. Are you attempting to get rid of `NewReadOnly`?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43388#-:-LwYofQn9d5ncWIHSSwC:b3v0sdf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nvanbenschoten, and @petermattis)

**Review by irfansharif — COMMENTED** [review]
I was trying to see what plumbing an `engine.Batch` type throughout `batcheval` would look like, which in turn was motivated by raft storage work where I wanted more precisely specified usage of `engine.Batch` vs. `engine.Engine` types. If this helps makes `pkg/engine` interfaces any smaller, I'm all for it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43388#-:-LwYpM-I2ESgvexrexvg:bkepg4t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

**Review by petermattis — COMMENTED** [review]
>  I was trying to see what plumbing an engine.Batch type throughout batcheval would look like, which in turn was motivated by raft storage work where I wanted more precisely specified usage of engine.Batch vs. engine.Engine types. If this helps makes pkg/engine interfaces any smaller, I'm all for it.

I believe we originally had an `engine.Batch` plumbed throughout batcheval (or the precursor to batcheval), but intentionally moved to using `engine.NewReadOnly` for read-only requests. It would be nice if `NewReadOnly` returned a `Reader` instead of a `ReadWriter`, but plumbing that through `batcheval` seemed onerous.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43388#-:-LwYrz4Q3KiZVYPgvP64:bl1wctw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

**Review by irfansharif — COMMENTED** [review]
Digging through history I find #16406 where we moved from using the raw engine to `engine.NewReadOnly` to be able to reuse iterators. (Bonus: there are benchmarks comparing `engine.Batch` vs `engine.ReadOnly`). Previous to that we've always used the raw engine for read-only requests, or at least as of 2015: https://github.com/cockroachdb/cockroach/blob/433125d3f872850506b26e0e977898319d342935/storage/range.go#L608-L609

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43388#-:-LwYy9I-9jmExdP-s-w7:b-8yq26u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

**Comment by irfansharif** [comment]
Ok so lazily stealing numbers from [benchdiff](https://docs.google.com/spreadsheets/d/1shQluFPtACoU_HV2iK_EUQXaxDkOz1WQk3maJMCcONM/edit#gid=1):

```
                                          time/op (ns/op)

IterOnBatch_RocksDB/writes=10-24	      1601.5	        (p=0.002 n=10+10)
IterOnEngine_RocksDB/writes=10-24	      1950.8	        (p=0.549 n=9+10)
IterOnReadOnly_RocksDB/writes=10-24	      966.8888889	    (p=0.324 n=10+9)

IterOnBatch_RocksDB/writes=100-24	      2015.2	        (p=0.000 n=8+10)
IterOnEngine_RocksDB/writes=100-24	      2110.7	        (p=0.617 n=10+10)
IterOnReadOnly_RocksDB/writes=100-24	  1163.444444	    (p=0.764 n=10+9)

IterOnBatch_RocksDB/writes=1000-24	      2618.8	        (p=0.211 n=10+10)
IterOnEngine_RocksDB/writes=1000-24	      2355	            (p=0.912 n=10+10)
IterOnReadOnly_RocksDB/writes=1000-24	  1385.888889	    (p=0.324 n=10+9)

IterOnBatch_RocksDB/writes=10000-24	      3338.1	        (p=0.579 n=10+10)
IterOnEngine_RocksDB/writes=10000-24	  2570.1	        (p=0.278 n=9+10)
IterOnReadOnly_RocksDB/writes=10000-24	  1593.8	        (p=0.566 n=10+10)
```

The overhead in reading through `engine.Batch` vs. `engine.NewReadOnly` is is not as small as I thought it would be (correct me if I'm wrong). I'll abandon this now.

**Comment by irfansharif** [comment]
> I didn't realize engine.Batches didn't have a "read at snapshot of underlying engine at time of creation" guarantee.

I'm still surprised this is a thing, and it sounds like it should not be? I can file separately if storage is interested in digging into it.

**Comment by petermattis** [comment]
> I'm still surprised this is a thing, and it sounds like it should not be? I can file separately if storage is interested in digging into it.

Are there any bugs due to this? I would be interested in understanding why replacing `engine.NewReadOnly` with `engine.NewBatch` caused test failures (they should be equivalent for read-only operations), but changing the semantics of `engine.NewBatch` to take a snapshot of the underlying database is very likely to have performance implications.

**Comment by nvanbenschoten** [comment]
> It would be nice if NewReadOnly returned a Reader instead of a ReadWriter, but plumbing that through batcheval seemed onerous.

I'm pretty sure @benesch tried to do this at some point and eventually gave up. That should tell you all you need to know about how onerous this would be.

**Comment by benesch** [comment]
Actually IIRC I gave up because I was on my way out and ran out of time,
not because it was terribly technically challenging. 😄

The PR is here:
https://github.com/cockroachdb/cockroach/pull/26916. There is still some
weirdness where you still have a ReadWriter when you really want a Reader,
but I think the PR fixed a lot more weirdness than it created!

**Pull request closed without merging**
