### PR TITLE
sql: add metrics measuring distributed execution

### PR DESCRIPTION
**Pull request by michae2**
**sql: add sql.distsql.select.distributed_exec.count metrics**

Add a new planFlag and counter to EngineMetrics.

Note that `planFlagDistributedExecution` is set if *any* part of a query
uses distributed execution, including pre- or post-queries. This seemed
both simpler and more likely to be useful than only counting main
queries that use distributed execution.

Epic: None

Release note (ops change): Add two new metrics,
`sql.distsql.select.distributed_exec.count` and
`sql.distsql.select.distributed_exec.count.internal`. These metrics count the
number of SELECT statements that actually execute with full or partial
distribution. These metrics differ from `sql.distsql.select.count` and
`sql.distsql.select.count.internal` in that the latter count the number
of SELECT statements that are *planned* with full or partial
distribution, but might not necessarily execute with full or partial
distribution, depending on the location of data.

---

**sql: add sql.distsql.distributed_exec.count metric**

Epic: None

Release note (ops change): Add new metric
`sql.distsql.distributed_exec.count` which counts the number of
invocations of the execution engine with full or partial
distribution. (This is in contrast to `sql.distsql.queries.total` which
counts the total number of invocations of the execution engine.)

---

**sql: clarify scope of a few sql.distsql metrics**

Epic: None

Release note (ops change): Add some clarification that the following
metrics count invocations of the execution engine and not SQL queries
(which could each result in multiple invocations of the execution
engine):

- `sql.distsql.queries.active`
- `sql.distsql.queries.total`
- `sql.distsql.distributed_exec.count`

### CODE REVIEW

**Review by mgartner — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, 4 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135236)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2, @mw5h, and @yuzefovich)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135236#-OBk2QjL0kPi_Dnuu6G3:-OBk2QjL0kPi_Dnuu6G4:bjbz7ba):*
just bikeshedding on the name: would `sql.distsql.select.exec.count` be better? Maybe that's more confusing...
___
*[`-- commits` line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135236#-OBk36Sb5FUEkx8bEnNC:-OBk36Sb5FUEkx8bEnND:b-3pzywc):*
Doesn't this count invocations when distsql is disabled too? So it effectively counts all invocations of the execution engine, right?
___
*[`docs/generated/metrics/metrics.html` line 1647 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/135236#-OBk3Otq5tas4I1vX6-w:-OBk3Otr-Sj-C3kQE0Dm:bx83a8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f4dce18f11686fe03873ed8dc30aa0ff0e58258/docs/generated/metrics/metrics.html#L1647)):*
> ```HTML
> <tr><td>APPLICATION</td><td>sql.distsql.dist_query_rerun_locally.count</td><td>Total number of cases when distributed query error resulted in a local rerun</td><td>Queries</td><td>COUNTER</td><td>COUNT</td><td>AVG</td><td>NON_NEGATIVE_DERIVATIVE</td></tr>
> <tr><td>APPLICATION</td><td>sql.distsql.dist_query_rerun_locally.failure_count</td><td>Total number of cases when the local rerun of a distributed query resulted in an error</td><td>Queries</td><td>COUNTER</td><td>COUNT</td><td>AVG</td><td>NON_NEGATIVE_DERIVATIVE</td></tr>
> <tr><td>APPLICATION</td><td>sql.distsql.distributed.count</td><td>Number of invocations of the DistSQL engine executed with full or partial distribution</td><td>DistSQL runs</td><td>COUNTER</td><td>COUNT</td><td>AVG</td><td>NON_NEGATIVE_DERIVATIVE</td></tr>
> ```

Unless I'm mistaken, there is only the "DistSQL engine" and no alternative. Qualifying this as the "DistSQL engine" makes it sound like there is an alternative, and a user might expect `distsql=off` to use that alternative, which may be confusing. Should we say just "invocation of the execution engine ... multiple of which may occur for a single SQL statement ... and can also occur for internal processes ...".

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, 4 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135236)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @mw5h)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135236#-OBk2QjL0kPi_Dnuu6G3:-OBmWlUr2pCikl9bw825:bb5pxkh):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

just bikeshedding on the name: would `sql.distsql.select.exec.count` be better? Maybe that's more confusing...
</blockquote></details>

I like having word `distributed` in the metric name. `sql.distsql` prefix is confusing, but it's an existing one, and it'll be annoying to change. Perhaps I would go even more verbose and do `sql.distsql.select.actually_distributed.count` or something like that.
___
*[`-- commits` line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135236#-OBk36Sb5FUEkx8bEnNC:-OBmY0nhB4uLQWrXSbAP:birgvl5):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Doesn't this count invocations when distsql is disabled too? So it effectively counts all invocations of the execution engine, right?
</blockquote></details>

Sounds right.
___
*[`docs/generated/metrics/metrics.html` line 1647 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/135236#-OBk3Otq5tas4I1vX6-w:-OBmYKvcEktEEiVzX9Eo:b3aklzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f4dce18f11686fe03873ed8dc30aa0ff0e58258/docs/generated/metrics/metrics.html#L1647)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Unless I'm mistaken, there is only the "DistSQL engine" and no alternative. Qualifying this as the "DistSQL engine" makes it sound like there is an alternative, and a user might expect `distsql=off` to use that alternative, which may be confusing. Should we say just "invocation of the execution engine ... multiple of which may occur for a single SQL statement ... and can also occur for internal processes ...".
</blockquote></details>

I like this suggestion.

**Review by michae2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135236)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @mw5h, and @yuzefovich)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135236#-OBk2QjL0kPi_Dnuu6G3:-OC5uLN_EYzIKYt9DX7-:by42w8c):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I like having word `distributed` in the metric name. `sql.distsql` prefix is confusing, but it's an existing one, and it'll be annoying to change. Perhaps I would go even more verbose and do `sql.distsql.select.actually_distributed.count` or something like that.
</blockquote></details>

I updated it to `sql.distsql.select.distributed_exec.count` (and the next one to `sql.distsql.distributed_exec.count`). How do those sound?
___
*[`-- commits` line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/135236#-OBk36Sb5FUEkx8bEnNC:-OC5u_An-LmKHAbzVxkQ:b-sm8hoe):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Sounds right.
</blockquote></details>

Changed the release note to say "execution engine" instead of "DistSQL engine".
___
*[`docs/generated/metrics/metrics.html` line 1647 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/135236#-OBk3Otq5tas4I1vX6-w:-OC5uh3Z0Qkuuum-vhKl:bdrbk10) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f4dce18f11686fe03873ed8dc30aa0ff0e58258/docs/generated/metrics/metrics.html#L1647)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I like this suggestion.
</blockquote></details>

Changed those three `Help` fields to say "execution engine" and "(multiple of which may occur for a single SQL statement)".

**Review by yuzefovich — APPROVED** [review]
I like it! :lgtm:

> Reviewed 5 of 5 files at r4, 4 of 4 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135236#-:-OC6T4pO8EiF3P6EF5OO:b-mg7t6l)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @mw5h)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135236#-OBk2QjL0kPi_Dnuu6G3:-OC6SaGn2DdtB4Ql1hPZ:b4c9lyr):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I updated it to `sql.distsql.select.distributed_exec.count` (and the next one to `sql.distsql.distributed_exec.count`). How do those sound?
</blockquote></details>

:thumbsup:

**Review by mgartner — APPROVED** [review]
:lgtm: Thanks for doing this!

> Reviewed 5 of 5 files at r4, 4 of 4 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135236#-:-OCZJw9s35ccaZf-YvX5:b-pt8m11)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @mw5h)

**Comment by michae2** [comment]
YW, TFTRs!

bors r=yuzefovich,mgartner

**Pull request merged**
