### PR TITLE
storage: serialize applying Raft snapshots

### PR DESCRIPTION
**Pull request by petermattis**
Serialize applying Raft snapshots by making them go through the
reservation system.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12192)

### CODE REVIEW

**Comment by petermattis** [comment]
This needs a test.

**Comment by petermattis** [comment]
Added a test.

**Comment by tamird** [comment]
Is this expected to improve performance? What's the motivation?

---

Reviewed 2 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192#-:-KYVFIYrQ4iLz9eqy8Fi:b-g9kr2z)*

**Comment by petermattis** [comment]
Yes, this is expected to improve behavior when a lot of replicas need to be caught up via Raft snapshots.

---

Review status: 1 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192#-:-KYVWbcSItQvG1A7T4BT:b-nmih0i)*

**Comment by tamird** [comment]
:lgtm: though in the general case, this throttles applying raft snapshots rather than serializing them (i.e. if `COCKROACH_MAX_RESERVATIONS` is more than 1) and the commit message should indicate that, along with the motivation.

---

Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/storage/reservation.go, line 87 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192#-KYWK0Lv0TWKqQEciCeK:-KYWK0Lv0TWKqQEciCeL:bp0cfme) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e87140e36346ff0896538d44d5e598c3f746fd4/pkg/storage/reservation.go#L87)):*
> ```Go
> 	}
> 
> 	for {
> ```

should this be `for ;;b.mu.cond.Wait() {`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192#-:-KYWKIhAOhPQNiXQhry4:b-yxky9t)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/storage/reservation.go, line 154 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192#-KYWNpEb8PbDf6AqGjM7:-KYWNpEb8PbDf6AqGjM8:b-n0scqy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e87140e36346ff0896538d44d5e598c3f746fd4/pkg/storage/reservation.go#L154)):*
> ```Go
> 
> 		// Make sure that we don't add back a destroyed replica.
> 		if req.CanDecline {
> ```

This check is still valid even if we can't decline the snapshot (we can't decline it, but we can drop it on the floor). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192#-:-KYWOhY-A5yCpoHN9OD3:bnfp4nl)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/storage/reservation.go, line 87 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192#-KYWK0Lv0TWKqQEciCeK:-KYWPN9m5ATH2AlfWQxc:b-a2zkeg) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e87140e36346ff0896538d44d5e598c3f746fd4/pkg/storage/reservation.go#L87)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

should this be `for ;;b.mu.cond.Wait() {`?
</blockquote></details>

The loop should also check for context cancelation (can't interrupt the `sync.Cond`, but we can at least bail out the next time it's triggered)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192)*

**Comment by tamird** [comment]
Perhaps a semaphore channel would be a better fit so it can compose with
the context.

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/storage/reservation.go, line 154 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192#-KYWNpEb8PbDf6AqGjM7:-KYYv7ckZoVu2KwByHHc:b8pderz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e87140e36346ff0896538d44d5e598c3f746fd4/pkg/storage/reservation.go#L154)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This check is still valid even if we can't decline the snapshot (we can't decline it, but we can drop it on the floor). 
</blockquote></details>

Good point. I'm going to do another pass at this PR which does a more significant reworking of reservations. The dead replicas check deserve to be pulled up to the caller so that we don't need to construct the list of dead replicas. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192)*

**Comment by petermattis** [comment]
`bookie` is now gone. This is ready for another look.

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/storage/store.go, line 2682 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192#-KYZ24Wgn_vwrBeNcdAv:-KYZ24Wgn_vwrBeNcdAw:baeb5r0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9c9f64762454f457bb1005a39208959f90b8399/pkg/storage/store.go#L2682)):*
> ```Go
> 			return errors.Errorf("stopped")
> 		}
> 	}
> ```

The duplication of the `select` statements is unfortunate, but I don't see another option. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192#-:-KYZ1uf6C5B2G7mVT6rU:boi3ws9)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/storage/store.go, line 2257 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192#-KYZARs-fq2aPv1bKF_1:-KYZARs-fq2aPv1bKF_2:b-wb350x) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9c9f64762454f457bb1005a39208959f90b8399/pkg/storage/store.go#L2257)):*
> ```Go
> }
> 
> func (s *Store) isDeadReplica(rangeID roachpb.RangeID) error {
> ```

there's some similar logic in tryGetOrCreateReplica - perhaps they can be consolidated, perhaps not.

---

*[pkg/storage/store.go, line 2657 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192#-KYZAVwwi_yZQf58rwOg:-KYZAVwwi_yZQf58rwOh:b-izjwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9c9f64762454f457bb1005a39208959f90b8399/pkg/storage/store.go#L2657)):*
> ```Go
> 	}
> 
> 	if err := s.isDeadReplica(header.State.Desc.RangeID); err != nil {
> ```

is this exercised in any tests? per discussion in #12201, it's not clear to me that this is needed.

---

*[pkg/storage/store.go, line 2682 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192#-KYZ24Wgn_vwrBeNcdAv:-KYZAbR9NNQaivvxj6yH:bmphlbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9c9f64762454f457bb1005a39208959f90b8399/pkg/storage/store.go#L2682)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The duplication of the `select` statements is unfortunate, but I don't see another option. 
</blockquote></details>

Seems fine. In fact, I'd probably duplicate the below into the `case s.snapshotApplySem <- struct{}{}:` for clarity.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192#-:-KYZAjxx7nB3atsZeETs:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: 3 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/storage/store.go, line 2257 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192#-KYZARs-fq2aPv1bKF_1:-KYZBC7wJ5TQO0jdOfJN:b-52o7mk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9c9f64762454f457bb1005a39208959f90b8399/pkg/storage/store.go#L2257)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

there's some similar logic in tryGetOrCreateReplica - perhaps they can be consolidated, perhaps not.
</blockquote></details>

Yeah, I took this logic from there. I didn't see an easy way to consolidate it. But per my other comment, this is no longer necessary and has been removed.

---

*[pkg/storage/store.go, line 2657 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192#-KYZAVwwi_yZQf58rwOg:-KYZBIJFcAdmYw-fpIuK:bdc9k26) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9c9f64762454f457bb1005a39208959f90b8399/pkg/storage/store.go#L2657)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is this exercised in any tests? per discussion in #12201, it's not clear to me that this is needed.
</blockquote></details>

It's not strictly necessary because we'll fail the snapshot later if the replica is dead. I doubt this is tested. I was just trying to maintain the existing logic, but thinking about this further, corrupted replicas are rare so it doesn't seem worth having a faster check.

---

*[pkg/storage/store.go, line 2682 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192#-KYZ24Wgn_vwrBeNcdAv:-KYZBViC8H_988PLXB-I:b-3qt6go) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9c9f64762454f457bb1005a39208959f90b8399/pkg/storage/store.go#L2682)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Seems fine. In fact, I'd probably duplicate the below into the `case s.snapshotApplySem <- struct{}{}:` for clarity.
</blockquote></details>

Duplicate the what? The metric increments?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192)*

**Comment by BramGruneir** [comment]
:LGTM:
This is much cleaner.  I really like it.

Do we have a test for sending a bunch of snapshots at once?  

---

Reviewed 4 of 4 files at r3.
Review status: 3 of 4 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192#-:-KYZ73gaXqSxkGdDYCSL:b-n7fnxz)*

**Comment by tamird** [comment]
+1 to a test of this throttling, though it might prove tricky to write.

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/storage/store.go, line 2682 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192#-KYZ24Wgn_vwrBeNcdAv:-KYZKIPVSGMR198_ca6n:b-to1s8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9c9f64762454f457bb1005a39208959f90b8399/pkg/storage/store.go#L2682)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Duplicate the what? The metric increments?
</blockquote></details>

Well, I'd extract some function:
```
func foo(rangeSize int64) func() {
	s.metrics.ReservedReplicaCount.Inc(1)
	s.metrics.Reserved.Inc(header.RangeSize)
	return func() {
		s.metrics.ReservedReplicaCount.Dec(1)
		s.metrics.Reserved.Dec(header.RangeSize)
		<-s.snapshotApplySem
	}
}
```

and then `defer foo()()` in both `switch`es.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192#-:-KYZKak6u91YdgRqzsvC:bdw0wne)*

**Comment by petermattis** [comment]
No, we don't appear to have an existing test for concurrent Raft snapshots. Let me investigate what can be done here. 

---

Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/storage/store.go, line 2682 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192#-KYZ24Wgn_vwrBeNcdAv:-KYZOUBwFBm-8ASnPD5R:bd9rocb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9c9f64762454f457bb1005a39208959f90b8399/pkg/storage/store.go#L2682)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Well, I'd extract some function:
```
func foo(rangeSize int64) func() {
	s.metrics.ReservedReplicaCount.Inc(1)
	s.metrics.Reserved.Inc(header.RangeSize)
	return func() {
		s.metrics.ReservedReplicaCount.Dec(1)
		s.metrics.Reserved.Dec(header.RangeSize)
		<-s.snapshotApplySem
	}
}
```

and then `defer foo()()` in both `switch`es.
</blockquote></details>

That doesn't seem any clearer than the current code (at least, it doesn't to me).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192#-:-KYZOcOtEj_58K5CRSBq:bsndz51)*

**Comment by petermattis** [comment]
Getting multiple concurrent Raft snapshots in a test is a bit difficult, so I restructured the code in order to be able to test just the reservation portion. PTAL.

---

Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192#-:-KYZlf4Tc69IuUKz3W77:b-dcl5mg)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/storage/store_test.go, line 2663 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192#-KY_ElSz56dmnjI8dRRn:-KY_ElSz56dmnjI8dRRo:b-ftsvdl) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fb0fc4abd03592cc9bf38b3ae9ff773bc9ac078/pkg/storage/store_test.go#L2663)):*
> ```Go
> 
> 	ctx := context.Background()
> 	cleanup, err := s.reserveSnapshot(ctx, &SnapshotRequest_Header{}, nil)
> ```

nit: cleanup1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192#-:-KY_EoRa6nzlrK89OL-f:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/storage/store_test.go, line 2663 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192#-KY_ElSz56dmnjI8dRRn:-KY_FOHo-3TNTQ_KSHvV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fb0fc4abd03592cc9bf38b3ae9ff773bc9ac078/pkg/storage/store_test.go#L2663)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: cleanup1
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12192)*

**Pull request merged**
