### PR TITLE
Revert "Revert "rocksdb: Bump version to 4.9 and fix broken interface usage""

### PR DESCRIPTION
**Pull request by petermattis**
This reverts commit fe70c5f84d4cf2865c97d06d981a0d6e1ead76c2.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9609)

### CODE REVIEW

**Comment by petermattis** [comment]
Do not merge. This is for sharing purposes at the moment.

**Comment by petermattis** [comment]
We've verified that RocksDB 4.9 has a data corruption issue. See #9029.

**Comment by tschottdorf** [comment]
Does this mean we want to stick with 4.8 or upgrade to 4.11?

**Comment by tschottdorf** [comment]
Nevermind, just found https://github.com/cockroachdb/cockroach/pull/9616.

**Pull request closed without merging**
