### PR TITLE
sql: fix emitting maximum memory usage ComponentStat

### PR DESCRIPTION
**Pull request by asubiotto**
While working on some frontend changes, I realized that we weren't displaying max memory usage correctly. This PR fixes that. Please see individual commits for details.

Release note: None (no user-visible change)

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59293#-:-MRfXXwAEsPj9JUUEzY_:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @RaduBerinde)

___
*[pkg/sql/execinfrapb/component_stats.proto, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59293#-MRfWCNB1BAgT1Om2OtQ:-MRfWCNB1BAgT1Om2OtR:b-j1g3m1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fef48e8f82e914309d483234af37f864a6785ca/pkg/sql/execinfrapb/component_stats.proto#L53)):*
> ```protobuf
>   // NodeID of the node this component ran on.
>   // TODO(asubiotto): This is only used when Type = FLOW to uniquely describe
>   // a flow (since flows on different nodes still have the same FlowID. Use this
> ```

nit: missing closing parenthesis.
___
*[pkg/sql/execstats/traceanalyzer.go, line 134 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59293#-MRfWqaiAeHaatuu9xPO:-MRfWqaiAeHaatuu9xPP:b-6eki3k) ([raw file](https://github.com/cockroachdb/cockroach/blob/e588cd8b1afd2ff1afc13347ea222ff28aa941e5/pkg/sql/execstats/traceanalyzer.go#L134)):*
> ```Go
> func (a *TraceAnalyzer) AddTrace(trace []tracingpb.RecordedSpan, makeDeterministic bool) error {
> 	m := execinfrapb.ExtractStatsFromSpans(trace, makeDeterministic)
> 	fmt.Println("Calling AddTrace")
> ```

leftover

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59293)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/execstats/traceanalyzer.go, line 134 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59293#-MRfWqaiAeHaatuu9xPO:-MRt_vXk4Aa3vAScYwTF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e588cd8b1afd2ff1afc13347ea222ff28aa941e5/pkg/sql/execstats/traceanalyzer.go#L134)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

leftover
</blockquote></details>

Done.

**Comment by asubiotto** [comment]
bors r=yuzefovich

**Comment by asubiotto** [comment]
bors r-

Looks like something's still off with this PR

**Comment by asubiotto** [comment]
bors r=yuzefovich

**Pull request merged**
