### PR TITLE
tabledesc: forbid computed columns from having DEFAULT expressions

### LINKED ISSUE #72881: sql,catalog: should not allow a column definition to have a computed column and default expression
**Describe the problem**

We disallow computed columns from having `ON UPDATE` -- but currently they are allowed to have `DEFAULT` expressions. This is confusing.

The postgres behavior is to disallow it:
```
rafiss@127:postgres> create table t (a int, b int generated always as (a+1) stored);
CREATE TABLE

rafiss@127:postgres> alter table t alter column b set default 3;
column "b" of relation "t" is a generated column
```

**To Reproduce**

Run the above commands on CockroachDB

**Expected behavior**
It should error.

There also potentially could be some descriptor validation, but that might get complicated if there are already clusters in the wild that are in this state.

**Environment:**
 - CockroachDB commit d16a755cfa

### PR DESCRIPTION
**Pull request by postamar**
Previously, we didn't have a table descriptor validation check to ensure
that computed columns didn't also have DEFAULT expressions. It is
therefore possible that clusters and cluster backups exist in production
which contain tables with such columns. This commit therefore fixes this
bug by adding the missing validation check, and by removing default
expressions from computed columns when necessary after deserializing
a descriptor protobuf.

Fixes #72881.

Release note (sql change, bug fix): fixes a bug which allowed computed
columns to also have DEFAULT expressions.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
Thoughts on adding parallel testing for `ON UPDATE`? If so, do it as a separate commit which you don't backport to 21.1.`backport` has tools to pick commits. 

> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73090#-:-MpEsw9fAWJiDYc_f6wY:b2aooy8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/logictest/testdata/logic_test/computed, line 1054 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73090#-MpEtN2f1IkaHDs4buSf:-MpEtN2f1IkaHDs4buSg:b-vscnpz) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ec6c33625757e04a0ba9ab2f11abd3ed7809622/pkg/sql/logictest/testdata/logic_test/computed#L1054)):*
> ```
> statement error computed column "v" cannot also have a DEFAULT expression
> ALTER TABLE t69327 ALTER COLUMN v SET DEFAULT 'foo'
> ```
what's the pgcode here? Are we only catching this with validation? Ideally not.

**Review by postamar — COMMENTED** [review]
Sure, I can add a test for ON UPDATE in a separate commit. It wouldn't hurt.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73090#-:-MpGf2FmEpX_nJmQeCN0:b-yb0xru)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/logictest/testdata/logic_test/computed, line 1054 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73090#-MpEtN2f1IkaHDs4buSf:-MpGf62O15Gxx322Z1ol:bqtr7mx) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ec6c33625757e04a0ba9ab2f11abd3ed7809622/pkg/sql/logictest/testdata/logic_test/computed#L1054)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> statement error computed column "v" cannot also have a DEFAULT expression
> ALTER TABLE t69327 ALTER COLUMN v SET DEFAULT 'foo'
> ```
what's the pgcode here? Are we only catching this with validation? Ideally not. 
</blockquote></details>

No, because it's one of these cases I don't like where the validation function serves a dual purpose of (1) actually validating the descriptor and (2) validating the statement's effects. For some reason I don't understand, a lot of the errors which can be thrown in this way simply don't have pgcodes. If we care about pgcodes let's please address that in a separate issue and PR I feel this is out of scope here.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73090)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/logictest/testdata/logic_test/computed, line 1054 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73090#-MpEtN2f1IkaHDs4buSf:-MpH99-D1HTC6O9sT8Al:bsp0ee1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ec6c33625757e04a0ba9ab2f11abd3ed7809622/pkg/sql/logictest/testdata/logic_test/computed#L1054)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

No, because it's one of these cases I don't like where the validation function serves a dual purpose of (1) actually validating the descriptor and (2) validating the statement's effects. For some reason I don't understand, a lot of the errors which can be thrown in this way simply don't have pgcodes. If we care about pgcodes let's please address that in a separate issue and PR I feel this is out of scope here.
</blockquote></details>

At this point, I’m of the mindset that have two such checks is fine. The validation level check ought not to carry a pgcode and ought to be a defense in depth mechanism that additionally protects us in cases like restore and upgrades. The statement time checks give better errors to the user and carry the intention. It is duplication, but it’s duplication that I think has served us well thus far. 

Fine with not doing it now. Were the randomized schema change workload in good shape, it’d reveal the missing pgcode.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73090#-:-MpIDBcA5m4X57lseVY6:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

**Comment by postamar** [comment]
Thanks for the review!

bors r+

**Pull request merged**
