### PR TITLE
sql: correctly trim and set trailing zeros in decimals in non-indexes

### PR DESCRIPTION
**Pull request by madelynnblue**
This brings us in line with postgres (again, for non-indexes).

Partial fix of #13384

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13813)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Pretty cool! LGTM

If there are no "trimdecimals" uses left, maybe revert c3971004c5d6a37d00d790d0cf1780e55c511a02 entirely

**Comment by mjibson** [comment]
You may have read just the first revision of the PR, which failed the LogicDistSQL tests when decimals were used in an index. We still need `trimdecimals` because of those, and in fact added it in a few places until the index behavior is fixed. Still LG?

**Comment by RaduBerinde** [comment]
Got it, LGTM. Make sure to do a `make stress PKG=./pkg/sql TESTS=LogicDistSQL` run (the distsql tests split things into span randomly so some cases only fail occasionally).

**Comment by mjibson** [comment]
The stress test didn't fail at 20 runs, so things appear ok.

**Pull request merged**
