### PR TITLE
opt: fix bug with incorrect results produced by paired left inverted join

### LINKED ISSUE #58892: sql: left inverted join pair produces incorrect results
**Describe the problem**

See the logictest with the `NOTE` below. The output row's `j2.k` value should be `NULL` because no rows on the right match the `ON` condition.

```
statement ok
CREATE TABLE j1 (
  k INT PRIMARY KEY,
  j JSON
)

statement ok
INSERT INTO j1 VALUES (1, '{"a": "b"}')

statement ok
CREATE TABLE j2 (
  k INT PRIMARY KEY,
  j JSON,
  INVERTED INDEX j_idx (j)
)

statement ok
INSERT INTO j2 VALUES (1, '{"a": "b"}')

query T
EXPLAIN (OPT, VERBOSE)
SELECT j1.*, j2.*
FROM j1 LEFT INVERTED JOIN j2@j_idx
  ON j2.j @> j1.j AND j2.j = '"foo"'
ORDER BY j1.k, j2.k
----
sort (segmented)
 ├── columns: k:1 j:2 k:5 j:6
 ├── immutable
 ├── stats: [rows=1000, distinct(1)=1000, null(1)=0]
 ├── cost: 102714.07
 ├── key: (1,5)
 ├── fd: (1)-->(2), (1,5)-->(6)
 ├── ordering: +1,+5
 ├── prune: (1,5)
 ├── interesting orderings: (+1) (+5)
 └── left-join (lookup j2)
      ├── columns: j1.k:1 j1.j:2 j2.k:5 j2.j:6
      ├── key columns: [5] = [5]
      ├── lookup columns are key
      ├── immutable
      ├── stats: [rows=1000, distinct(1)=1000, null(1)=0]
      ├── cost: 102684.06
      ├── key: (1,5)
      ├── fd: (1)-->(2), (1,5)-->(6)
      ├── ordering: +1
      ├── prune: (1,5)
      ├── interesting orderings: (+1) (+5)
      ├── left-join (inverted j2@j_idx)
      │    ├── columns: j1.k:1 j1.j:2 j2.k:5 continuation:11
      │    ├── flags: force inverted join (into right side)
      │    ├── inverted-expr
      │    │    └── j2.j:6 @> j1.j:2
      │    ├── stats: [rows=10000, distinct(1)=1000, null(1)=0]
      │    ├── cost: 41984.03
      │    ├── key: (1,5)
      │    ├── fd: (1)-->(2), (5)-->(11)
      │    ├── ordering: +1
      │    ├── scan j1
      │    │    ├── columns: j1.k:1 j1.j:2
      │    │    ├── stats: [rows=1000, distinct(1)=1000, null(1)=0]
      │    │    ├── cost: 1084.02
      │    │    ├── key: (1)
      │    │    ├── fd: (1)-->(2)
      │    │    ├── ordering: +1
      │    │    ├── prune: (1,2)
      │    │    ├── interesting orderings: (+1)
      │    │    └── unfiltered-cols: (1-4)
      │    └── filters (true)
      └── filters
           ├── j2.j:6 @> j1.j:2 [outer=(2,6), immutable]
           └── j2.j:6 = '"foo"' [outer=(6), immutable, constraints=(/6: [/'"foo"' - /'"foo"']; tight), fd=()-->(6)]

# NOTE: The output should be:
#
#   1  {"a": "b"}  NULL  NULL
#
query ITIT
SELECT j1.*, j2.*
FROM j1 LEFT INVERTED JOIN j2@j_idx
  ON j2.j @> j1.j AND j2.j = '"foo"'
ORDER BY j1.k, j2.k
----
1  {"a": "b"}  1  NULL
```

When I remove the join and index hints, a cross join is performed with a different result:

```
query T
EXPLAIN (OPT, VERBOSE)
SELECT j1.*, j2.*
FROM j1 LEFT JOIN j2
  ON j2.j @> j1.j AND j2.j = '"foo"'
ORDER BY j1.k, j2.k
----
sort
 ├── columns: k:1 j:2 k:5 j:6
 ├── immutable
 ├── stats: [rows=1000, distinct(1)=1000, null(1)=0]
 ├── cost: 2521.04647
 ├── key: (1,5)
 ├── fd: (1)-->(2), (1,5)-->(6)
 ├── ordering: +1,+5
 ├── prune: (1,5)
 ├── interesting orderings: (+1) (+5)
 └── left-join (cross)
      ├── columns: j1.k:1 j1.j:2 j2.k:5 j2.j:6
      ├── immutable
      ├── stats: [rows=1000, distinct(1)=1000, null(1)=0]
      ├── cost: 2290.755
      ├── key: (1,5)
      ├── fd: (1)-->(2), (1,5)-->(6)
      ├── prune: (1,5)
      ├── interesting orderings: (+1) (+5)
      ├── scan j1
      │    ├── columns: j1.k:1 j1.j:2
      │    ├── stats: [rows=1000, distinct(1)=1000, null(1)=0]
      │    ├── cost: 1084.02
      │    ├── key: (1)
      │    ├── fd: (1)-->(2)
      │    ├── prune: (1,2)
      │    ├── interesting orderings: (+1)
      │    └── unfiltered-cols: (1-4)
      ├── select
      │    ├── columns: j2.k:5 j2.j:6
      │    ├── immutable
      │    ├── stats: [rows=10, distinct(6)=1, null(6)=0]
      │    ├── cost: 1094.04
      │    ├── key: (5)
      │    ├── fd: ()-->(6)
      │    ├── prune: (5)
      │    ├── interesting orderings: (+5)
      │    ├── scan j2
      │    │    ├── columns: j2.k:5 j2.j:6
      │    │    ├── stats: [rows=1000, distinct(5)=1000, null(5)=0, distinct(6)=100, null(6)=10]
      │    │    ├── cost: 1084.02
      │    │    ├── key: (5)
      │    │    ├── fd: (5)-->(6)
      │    │    ├── prune: (5,6)
      │    │    └── interesting orderings: (+5)
      │    └── filters
      │         └── j2.j:6 = '"foo"' [outer=(6), immutable, constraints=(/6: [/'"foo"' - /'"foo"']; tight), fd=()-->(6)]
      └── filters
           └── j2.j:6 @> j1.j:2 [outer=(2,6), immutable]

query ITIT
SELECT j1.*, j2.*
FROM j1 LEFT JOIN j2
  ON j2.j @> j1.j AND j2.j = '"foo"'
ORDER BY j1.k, j2.k
----
1  {"a": "b"}  NULL  NULL
```

**Environment:**

I'm currently seeing this on master@[`0d6f0ddd`](https://github.com/cockroachdb/cockroach/tree/0d6f0ddd0958a134887623be44da33f6726eac85).

cc @rytaft @sumeerbhola

### PR DESCRIPTION
**Pull request by rytaft**
Prior to this patch, it was possible for a paired join to produce incorrect
results for a left inverted join. In particular, some output rows had
non-NULL values for right-side columns when the right-side columns should
have been NULL.

This commit fixes the issue by updating the optimizer to ensure that
only columns from the second join in the paired join (the lookup join)
are projected, not columns from the first (the inverted join).

Fixes #58892

Release note (bug fix): Fixed an issue where a left inverted join could
have incorrect results. In particular, some output rows could have non-NULL
values for right-side columns when the right-side columns should
have been NULL. This issue has only existed in alpha releases of 21.1 so
far, and it is now fixed.

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
Very nice! Thanks for fixing this. :lgtm: 

> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59279#-:-MRuuMRV9352Cp_kps_t:bfa8dum)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde, @rytaft, and @sumeerbhola)

___
*[pkg/sql/logictest/testdata/logic_test/inverted_join_multi_column, line 161 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59279#-MRuuJwf9eVuye3hDiQV:-MRuuJwf9eVuye3hDiQW:bgc7vqv) ([raw file](https://github.com/cockroachdb/cockroach/blob/23efbe8a05233f88edec14c5906e679d92412296/pkg/sql/logictest/testdata/logic_test/inverted_join_multi_column#L161)):*
> ```
> # This query performs a left inverted join on ij_idx with no matching rows on
> # the right.
> # TODO(mgartner): This test is broken, see #58892.
> ```

:heart: 
___
*[pkg/sql/opt/xform/join_funcs.go, line 710 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59279#-MRutP4W02JLyUL5Si6P:-MRutP4W02JLyUL5Si6Q:bd602b1) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1ba5f4181e58f97368eea4ba8336e6691dab6e/pkg/sql/opt/xform/join_funcs.go#L710)):*
> ```Go
> 	invertedJoin.Cols = invertedJoin.Cols.Difference(indexCols).Union(newIndexCols)
> 	invertedJoin.ConstFilters = c.MapFilterCols(invertedJoin.ConstFilters, srcCols, dstCols)
> 	invertedJoin.On = c.MapFilterCols(invertedJoin.On, srcCols, dstCols)
> ```

I suppose `invertedJoin.PrefixKeyCols` do not need to be mapped because those are columns from the input of the join? Maybe add to the `mapInvertedJoin` function comment that columns from the input are not mapped. You could call out `PrefixKeyCols` specifically if you think that's appropriate.
___
*[pkg/sql/opt/xform/select_funcs.go, line 1691 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59279#-MRupEno4_7f1KzQJyZf:-MRupEno4_7f1KzQJyZg:b-pueo8l) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1ba5f4181e58f97368eea4ba8336e6691dab6e/pkg/sql/opt/xform/select_funcs.go#L1691)):*
> ```Go
> }
> 
> func (c *CustomFuncs) mapScalarExprCols(scalar opt.ScalarExpr, src, dst opt.ColSet) opt.ScalarExpr {
> ```

[nit] you could move this to `general_funcs.go` now that select and join funcs rely on it.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
I'm wondering if this will easily extend to pairs of lookup joins as done in https://github.com/cockroachdb/cockroach/pull/58261-- what do you think?

> Reviewed 3 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59279#-:-MRvCmaZ5RICTU2KlDi8:b-s7inm1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/ordering/lookup_join.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59279#-MRvC0Ik4ZomZYefS-Tp:-MRvC0Ik4ZomZYefS-Tq:bsfbxex) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1ba5f4181e58f97368eea4ba8336e6691dab6e/pkg/sql/opt/ordering/lookup_join.go#L35)):*
> ```Go
> 		child := expr.Child(0).(memo.RelExpr)
> 		res := projectOrderingToInput(child, required)
> 		res = trimColumnGroups(&res, &child.Relational().FuncDeps)
> ```

why this additional code? The remapping in this PR should not have changed what ordering the first join can provide since their orderings are based on their input side, which is not being remapped.
Could you add a code comment?
___
*[pkg/sql/opt/xform/join_funcs.go, line 593 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59279#-MRvCKeJ8jf97qz-j4yi:-MRvCKeJ8jf97qz-j4yj:b-vgesck) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1ba5f4181e58f97368eea4ba8336e6691dab6e/pkg/sql/opt/xform/join_funcs.go#L593)):*
> ```Go
> 		// Create a new ScanPrivate, which will be used below for the inverted join.
> 		// Note: this must happen before the continuation column is created to ensure
> 		// that the continuation column will have the highest column ID.
> ```

Could you add a code comment about paired joins that explains why we are doing this remapping?
___
*[pkg/sql/opt/xform/join_funcs.go, line 645 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59279#-MRv8LcQ22Mrm5rfvLNy:-MRv8LcQ22Mrm5rfvLNz:byaq5fe) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1ba5f4181e58f97368eea4ba8336e6691dab6e/pkg/sql/opt/xform/join_funcs.go#L645)):*
> ```Go
> 		indexJoin.Table = scanPrivate.Table
> 		indexJoin.Index = cat.PrimaryIndex
> 		indexJoin.KeyCols = c.getPkCols(invertedJoin.Table)
> ```

Am I correct in understanding that `invertedJoin.Table` is the mapped table?
___
*[pkg/sql/opt/xform/join_funcs.go, line 654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59279#-MRvBFnb2M1vWytXKus0:-MRvBFnc9iP6y5nxzk-2:b-qner35) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1ba5f4181e58f97368eea4ba8336e6691dab6e/pkg/sql/opt/xform/join_funcs.go#L654)):*
> ```Go
> 		// If this is a semi- or anti-join, ensure the columns do not include any
> 		// unneeded right-side columns.
> 		if joinType == opt.SemiJoinOp || joinType == opt.AntiJoinOp {
> ```

I don't quite understand the simplification that happened here. Could you explain, if possible with a simple example?

**Review by rytaft — COMMENTED** [review]
TFTRs!

> I'm wondering if this will easily extend to pairs of lookup joins as done in #58261 what do you think?

I think so! We'll just need to define a similar function `mapLookupJoin` and map the first join.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59279#-:-MRzRa6H7yL2V7n_pY5x:bl2wdt)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @RaduBerinde, and @sumeerbhola)

___
*[pkg/sql/opt/ordering/lookup_join.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59279#-MRvC0Ik4ZomZYefS-Tp:-MRyfSPP2xVSr6xu7f84:b-sdfx5) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1ba5f4181e58f97368eea4ba8336e6691dab6e/pkg/sql/opt/ordering/lookup_join.go#L35)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why this additional code? The remapping in this PR should not have changed what ordering the first join can provide since their orderings are based on their input side, which is not being remapped.
Could you add a code comment?
</blockquote></details>

I was getting an error that the ordering passed to `CanProvide` included some columns not provided by the input. I've copied some of the comments from `lookupOrIndexJoinBuildChildReqOrdering` below and added a bit more. 

This is needed because we represent required orderings as an `OrderingChoice` which basically allows you to order by any of several different columns. For example, if the required ordering is on `a`, but we happen to know that `a=b` and `c` is constant, then the ordering would be represented as `+(a|b) opt(c)`, indicating that we can order by `a`, `b`, `(c,a)`, or `(c,b)`. We can remove one of the required columns and all of the optional columns, and still have it be valid. (Not going to include all of this info since it's documented in the comment for `OrderingChoice`).
___
*[pkg/sql/opt/xform/join_funcs.go, line 593 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59279#-MRvCKeJ8jf97qz-j4yi:-MRzLpVS1yfuIZieY84x:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1ba5f4181e58f97368eea4ba8336e6691dab6e/pkg/sql/opt/xform/join_funcs.go#L593)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Could you add a code comment about paired joins that explains why we are doing this remapping?
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/join_funcs.go, line 645 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59279#-MRv8LcQ22Mrm5rfvLNy:-MRzLsDU1Q13-HK6ZOFR:b8pei5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1ba5f4181e58f97368eea4ba8336e6691dab6e/pkg/sql/opt/xform/join_funcs.go#L645)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Am I correct in understanding that `invertedJoin.Table` is the mapped table?
</blockquote></details>

Yes, that's right.
___
*[pkg/sql/opt/xform/join_funcs.go, line 654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59279#-MRvBFnb2M1vWytXKus0:-MRzNB40C5eBrlOPL_KZ:b-gxchc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1ba5f4181e58f97368eea4ba8336e6691dab6e/pkg/sql/opt/xform/join_funcs.go#L654)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't quite understand the simplification that happened here. Could you explain, if possible with a simple example?
</blockquote></details>

The test case that caused us to require the added projection was this one:
```
SELECT lk FROM ltable
WHERE NOT EXISTS (
  SELECT * FROM rtable WHERE ST_Covers(ltable.geom1, rtable.geom) AND lk > 5 AND rk1 > 12
)
```
Normally, the `execbuilder` can add a projection on top of the anti join to remove the columns that should not be output: https://github.com/cockroachdb/cockroach/blob/706006eb340a87233f21b15dd66eade0a8e5eda0/pkg/sql/opt/exec/execbuilder/relational.go#L1517 But the problem was that it could not tell the difference between columns from the inverted join and true input columns. In the above example, it was not effectively removing `rk1`. That's why I added this special logic in #50993.

This PR removes the need for the special logic, since columns from the inverted join will never be part of the `indexJoin.On` condition, and therefore won't be included in `indexJoin.Cols`. Now the logic in the `execbuilder` is effective (I updated the comment there).
___
*[pkg/sql/opt/xform/join_funcs.go, line 710 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59279#-MRutP4W02JLyUL5Si6P:-MRzR5m_6K7iGAPNJagj:bs7wumb) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1ba5f4181e58f97368eea4ba8336e6691dab6e/pkg/sql/opt/xform/join_funcs.go#L710)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I suppose `invertedJoin.PrefixKeyCols` do not need to be mapped because those are columns from the input of the join? Maybe add to the `mapInvertedJoin` function comment that columns from the input are not mapped. You could call out `PrefixKeyCols` specifically if you think that's appropriate.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/select_funcs.go, line 1691 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59279#-MRupEno4_7f1KzQJyZf:-MRzRYSSDFo9f4zBNYAL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1ba5f4181e58f97368eea4ba8336e6691dab6e/pkg/sql/opt/xform/select_funcs.go#L1691)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] you could move this to `general_funcs.go` now that select and join funcs rely on it.
</blockquote></details>

Done.

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59279#-:-MRzqmSn3LFi8jCPtquP:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @sumeerbhola)

**Review by sumeerbhola — APPROVED** [review]
Thanks for fixing this!
:lgtm: 

> Reviewed 12 of 15 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59279#-:-MS-qNa78orzSKG1aIjT:boacmf7)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde and @sumeerbhola)

**Review by rytaft — COMMENTED** [review]
Thanks!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59279#-:-MS-qldS18a0BV_eM6Y3:b-voiyyw)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde and @sumeerbhola)

**Pull request merged**
