### PR TITLE
colcontainer: fix diskqueue with unexpectedly "wide" batches

### PR DESCRIPTION
**Pull request by yuzefovich**
Currently (because of issue 43964) we sometimes need to allocate new
vectors when dequeueing from `diskQueue`. Previously, the code that does
that would look at every vector in `ColVecs()` of the batch; however, it
is possible that the caller uses a batch that is wider than the type
schema provided at `diskQueue`'s instantiation. This commit fixes it by
looking only at the prefix of all vectors of the batch.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
First commit is in a separate PR.

**Comment by yuzefovich** [comment]
The second commit needs a test, and I will update the PR tomorrow.

**Comment by yuzefovich** [comment]
It seems as if we reduce the test further even by one row, the bug doesn't trigger. It's still probably useful having such logic test.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47168#-:-M4nxXVl93jqUFfUaI60:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
