### PR TITLE
log: initialize ambient contexts with non-nil background ctx

### PR DESCRIPTION
**Pull request by irfansharif**
Release note: None

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87655#-:-NBUBnGP1s9AXP18-XAF:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif)

**Review by michae2 — COMMENTED** [review]
I think `tags` and `eventLog` should also be protected by the mutex, since they can change after initialization.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87655#-:-NBUEv8KEk7Bk7e9OH7e:bbfwdn4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2)

**Comment by irfansharif** [comment]
That sounds right. I'm not looking to merge this yet (and will make those changes once I am); added some debug logging to see the customer over at https://github.com/cockroachlabs/support/issues/1789 is willing to try running with this patch in their QA environment to get more data.

**Comment by michae2** [comment]
👍 glad you're adding the stopper debugging, too

**Review by michae2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87655)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif and @michae2)

___
*[`pkg/util/stop/stopper.go` line 434 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/87655#-NBUVi9hEVN852mM45hn:-NBUVi9hEVN852mM45ho:b6ejmfx) ([raw file](https://github.com/cockroachdb/cockroach/blob/598d1e15f360f2c10b0bcfae18fec03717ac4c99/pkg/util/stop/stopper.go#L434)):*
> ```Go
> 		}()
> 		_ = ctx.Value("non-existent-key")
> 	}
> ```

Was the intention of the code block to scope the defer? If so, I think it needs to be a function literal, not a code block.

Also, I think we should move the check to just before the goroutine starts.

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87655)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2)

___
*[`pkg/util/stop/stopper.go` line 434 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/87655#-NBUVi9hEVN852mM45hn:-NBUo-5E6f4jM0cW_XTI:b-s3i882) ([raw file](https://github.com/cockroachdb/cockroach/blob/598d1e15f360f2c10b0bcfae18fec03717ac4c99/pkg/util/stop/stopper.go#L434)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Was the intention of the code block to scope the defer? If so, I think it needs to be a function literal, not a code block.

Also, I think we should move the check to just before the goroutine starts.


</blockquote></details>

No the code block was just to keep it stanza-d; moved it within the goroutine.

**Review by michae2 — COMMENTED** [review]
Thank you for staying up late and putting this together!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87655#-:-NBVHJyi4F-2UuXkS2BE:b5k5f80)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif and @michae2)

___
*[`pkg/util/stop/stopper.go` line 497 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87655#-NBVGRlH878tW4i6ajkI:-NBVGRlH878tW4i6ajkJ:b-j2tete) ([raw file](https://github.com/cockroachdb/cockroach/blob/c327f437504b5d7875e776ada9d6b21976418f1c/pkg/util/stop/stopper.go#L497)):*
> ```Go
> 			defer func() {
> 				if r := recover(); r != nil {
> 					log.Warningf(context.Background(), "BUG: recovering from panic: %v\n\n\nstack trace: %s", r, debug.Stack())
> ```

Maybe this is too late, but one thought:

If this is inside the goroutine, then won't the call to `debug.Stack()` only ever produce one stack frame? (The frame for this goroutine.) Seems like this was more useful outside the goroutine, so that we could see the full stack when a nil context was passed into `RunAsyncTask`.

**Pull request closed without merging**
