### PR TITLE
jobs,upgrades: prefer NodeUser to RootUser

### PR DESCRIPTION
**Pull request by stevendanna**
This changes some uses of RootUser to NodeUser in the jobs and upgrades packages.

This doesn't change nearly all of the users of RootUser, but is intended to start a discussion about
whether this is a reasonable cleanup to pursue over the 24.1 release cycle.

See individual commits for details.

Epic: none

Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
+1 to doing this more

**Comment by rickystewart** [comment]
bors r- 

Failing CI

**Comment by stevendanna** [comment]
Let's try this again.

bors r=rafiss

**Pull request closed without merging**
