### PR TITLE
cherry-pick 2.0: log improvements + deflake test + add missing test

### PR DESCRIPTION
**Pull request by knz**
Picks #23760.
Picks #23803.

### CODE REVIEW

**Comment by knz** [comment]
I had to pick my commits and then Nikhil's separately (instead of squashing them all together) so that the commit message line up in our script that checks cherry-picks.

**Review by benesch — APPROVED** [review]
Code LGTM, but I'd like @bdarnell to make sure he's okay with this!

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/cli/interactive_tests/test_rotate_flush.tcl, line 0 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/23783#-L7_e_S76OmDQdPzGLqb:-L7_e_S76OmDQdPzGLqc:bn7tn62) ([raw file](https://github.com/cockroachdb/cockroach/blob/8074732d34a41c0cdb5c8bf27b28ab5acd0a7e2f/pkg/cli/interactive_tests/test_rotate_flush.tcl#L0)):*
Are you committing an empty file here or is reviewable just confused? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23783#-:-L7_efg6Km12lQIoyrkJ:bnfp4nl)*

**Comment by knz** [comment]
reviewable is confused.

**Comment by knz** [comment]
thanks for your reviews!

**Pull request merged**
