### PR TITLE
geo/geomfn: implement ST_ShiftLongitude

### LINKED ISSUE #49034: geo/geomfn: implement ST_ShiftLongitude({geometry})
Implement `ST_ShiftLongitude` on arguments {geometry}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_ShiftLongitude.html).

_Observers: Please react to this issue if you need this functionality._

For Geometry builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geomfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geomfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
  * When using GEOS, you can reference the [C API](https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in) for which functions are available. Unfortunately, Windows is not currently supported when using GEOS.
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end (your exhaustive unit tests go the above mentioned packages!).
* Ensure the documentation is regenerated by calling `make buildshort`. You can also play with it by calling `./cockroach demo --empty` afterwards.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48552 for an example PR.

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2021-01-11T01:52:34Z. Changes to titles, body and labels may be overwritten.</sub>

### PR DESCRIPTION
**Pull request by andyyang890**
This patch implements the geometry builtin `ST_ShiftLongitude`.

Resolves #49034.

Release note (sql change): Implemented the geometry builtin function
`ST_ShiftLongitude`, which is useful for plotting data on a
Pacific-centred map.

### CODE REVIEW

**Review by otan — CHANGES_REQUESTED** [review]
Looks like you need a `make bazel-generate`.

also -- midnight PRs?! gah!

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59234#-:-MRYa6U3-YXFu9MBQj3F:b993vsp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890)

___
*[pkg/geo/geomfn/shiftlongitude_test.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59234#-MRY_NMb1gY1hzyGmbQs:-MRY_NMc49_0TOsdHd29:b-wxwmgu) ([raw file](https://github.com/cockroachdb/cockroach/blob/99b17492e48694f1ff7903d52cca1503a64c4dc7/pkg/geo/geomfn/shiftlongitude_test.go#L119)):*
> ```Go
> 			desc:     "shift longitude for empty geometry collection",
> 			input:    geom.NewGeometryCollection(),
> 			expected: geom.NewGeometryCollection(),
> ```

can you add a test with SRID set on something?
___
*[pkg/sql/logictest/testdata/logic_test/geospatial, line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59234#-MRY_SQF8t_msFA0P5Sf:-MRY_SQF8t_msFA0P5Sg:b-5partk) ([raw file](https://github.com/cockroachdb/cockroach/blob/99b17492e48694f1ff7903d52cca1503a64c4dc7/pkg/sql/logictest/testdata/logic_test/geospatial#L14)):*
> ```
>   (1, 'POINT(1.0 1.0)', 'POINT(2.0 2.0)', 'POINT(3.0 3.0)'),
>   (2, 'LINESTRING(1.0 1.0, 2.0 2.0)', 'POINT(1.0 1.0)', 'POINT(3.0 3.0)'),
>   (4, 'POINT(-171.0 45.0)', 'POINT(320.0 -52.0)', 'POINT(118.0 23.0)')
> ```

nit: let's not modify this table.

see below
___
*[pkg/sql/logictest/testdata/logic_test/geospatial, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59234#-MRY_VWwAuAKBpBBrwqm:-MRY_VWwAuAKBpBBrwqn:b-id6rxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/99b17492e48694f1ff7903d52cca1503a64c4dc7/pkg/sql/logictest/testdata/logic_test/geospatial#L108)):*
> ```
> SELECT ST_ShiftLongitude(geom) FROM geo_table
> ----
> 010100000000000000000000400000000000000040
> ```

this is unfortunately intelligble since it is EWKB :) 

can you do something like
```
SELECT ST_AsEWKT(ST_ShiftLongitude(geom)) FROM ( VALUES
 (...::geometry),
  (...::geometry),
 (...::geometry),
)
```

like we do for some tests at the bottom
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 2778 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59234#-MRY_kaF0r6XgJK2JoM7:-MRY_kaF0r6XgJK2JoM8:b-ynthh1) ([raw file](https://github.com/cockroachdb/cockroach/blob/99b17492e48694f1ff7903d52cca1503a64c4dc7/pkg/sql/sem/builtins/geo_builtins.go#L2778)):*
> ```Go
> 			types.Geometry,
> 			infoBuilder{
> 				info: `Returns a modified version of a geometry in which the X coordinate (longitude) of each point is ` +
> ```

i would switch the terminology of X coordinate around, i.e. longitude (X coordinate)

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59234)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/geo/geomfn/shiftlongitude_test.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59234#-MRY_NMb1gY1hzyGmbQs:-MRb5B7w1DocWWNF9eyL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/99b17492e48694f1ff7903d52cca1503a64c4dc7/pkg/geo/geomfn/shiftlongitude_test.go#L119)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

can you add a test with SRID set on something?
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/geospatial, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59234#-MRY_VWwAuAKBpBBrwqm:-MRb5Hn26Of3njlUu65P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/99b17492e48694f1ff7903d52cca1503a64c4dc7/pkg/sql/logictest/testdata/logic_test/geospatial#L108)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

this is unfortunately intelligble since it is EWKB :) 

can you do something like
```
SELECT ST_AsEWKT(ST_ShiftLongitude(geom)) FROM ( VALUES
 (...::geometry),
  (...::geometry),
 (...::geometry),
)
```

like we do for some tests at the bottom
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 2778 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59234#-MRY_kaF0r6XgJK2JoM7:-MRb5JRy1UuZjRS_q-Ng:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/99b17492e48694f1ff7903d52cca1503a64c4dc7/pkg/sql/sem/builtins/geo_builtins.go#L2778)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i would switch the terminology of X coordinate around, i.e. longitude (X coordinate)
</blockquote></details>

Done.

**Review by otan — APPROVED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59234)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890 and @otan)

___
*[pkg/geo/geomfn/shiftlongitude.go, line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59234#-MRbIq68AL1R5KmElS0M:-MRbIq68AL1R5KmElS0N:b-b6denm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6017b11eb385d373c1a9002497e3a13590bff84b/pkg/geo/geomfn/shiftlongitude.go#L15)):*
> ```Go
> import (
> 	"github.com/cockroachdb/cockroach/pkg/geo"
> 	"github.com/twpayne/go-geom"
> ```

can you rename these `shift_longitude.go` / _test.go?

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59234)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/geo/geomfn/shiftlongitude.go, line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59234#-MRbIq68AL1R5KmElS0M:-MRbVmqM2SnzMHNuBKNV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6017b11eb385d373c1a9002497e3a13590bff84b/pkg/geo/geomfn/shiftlongitude.go#L15)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

can you rename these `shift_longitude.go` / _test.go?
</blockquote></details>

Done.

**Comment by otan** [comment]
image

🚢

**Comment by andyyang890** [comment]
bors r=otan

**Pull request merged**
