### PR TITLE
sql: change users from strings to url.Users

### LINKED ISSUE #9876: sql: change users from strings to url.Users
Currently we represent users like security.RootUser and server.TestUser as their string username ("root" and "testuser"). It makes more sense for these to be url.Users since #9794 uses them to construct PGURLs with passwords and currently makes unnecessary conversions.

### PR DESCRIPTION
**Pull request by yznming**
fix #9876
@asubiotto pls help to review the code.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10591)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
LGTM, thanks!

**Comment by tamird** [comment]
Reviewed 1 of 48 files at r1.
Review status: 1 of 48 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/security/auth.go, line 29 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591#-KWDJ8VWcCuzJqGFbVRq:-KWDJ8VWcCuzJqGFbVRr:b-t0kl5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbad7176c14b42197911c22c1d4bdcf9fc5abe1/pkg/security/auth.go#L29)):*
> ```Go
> const (
> 	// NodeUserName is name of user used by nodes for intra-cluster traffic.
> 	NodeUserName = "node"
> ```

can this be removed? it's not used except for in NodeUser.

---

*[pkg/security/auth.go, line 32 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591#-KWDJDHpVobpdqifUVib:-KWDJDHpVobpdqifUVic:b-rqxvo7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbad7176c14b42197911c22c1d4bdcf9fc5abe1/pkg/security/auth.go#L32)):*
> ```Go
> 
> 	// RootUserName is name of the default cluster administrator.
> 	RootUserName = "root"
> ```

ditto.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591)*

**Comment by asubiotto** [comment]
Review status: 1 of 48 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/acceptance/cluster/localcluster.go, line 807 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591#-KWDri3rAe3fNulErbtN:-KWDri3rAe3fNulErbtO:bz82i5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbad7176c14b42197911c22c1d4bdcf9fc5abe1/pkg/acceptance/cluster/localcluster.go#L807)):*
> ```Go
> // PGUrl returns a URL string for the given node postgres server.
> func (l *LocalCluster) PGUrl(i int) string {
> 	certUser := security.RootUser.Username()
> ```

Remove this line and use `security.RootUser` directly when constructing the url.

---

*[pkg/security/auth.go, line 147 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591#-KWDuG3c-5m6NUiAXB8h:-KWDuG3c-5m6NUiAXB8i:b-vn6t4o) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbad7176c14b42197911c22c1d4bdcf9fc5abe1/pkg/security/auth.go#L147)):*
> ```Go
> 
> 		if requestedUser == RootUser.Username() {
> 			return errors.Errorf("user %s must authenticate using a client certificate ", RootUser)
> ```

`url.Userinfo`'s `String()` method prints the username if the user doesn't have a password set and `username:pwd` if it does. Although `RootUser` doesn't have a password, I would be more comfortable changing this to `RootUser.Username()` or `requestedUser`. Make sure to take this into account in tests as well (e.g. in `pkg/sql/pgwire_test.go`) for the sake of consistency.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591)*

**Comment by yznming** [comment]
Review status: 1 of 48 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/security/auth.go, line 32 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591#-KWDJDHpVobpdqifUVib:-KWDvusu8CL-Znosz7Af:b-qh98xz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbad7176c14b42197911c22c1d4bdcf9fc5abe1/pkg/security/auth.go#L32)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> ditto.
</details>
the RootUserName is referred by the default config in config.go. It need a const variable.
```
const(
...
defaultUser     = security.RootUserName
...
)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591)*

**Comment by tamird** [comment]
Reviewed 4 of 48 files at r1.
Review status: 5 of 48 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/security/auth.go, line 32 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591#-KWDJDHpVobpdqifUVib:-KWE7Cdfgd9kitKaod9z:bvtymzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbad7176c14b42197911c22c1d4bdcf9fc5abe1/pkg/security/auth.go#L32)):*
<details><summary><i>Previously, yznming (Yan Long) wrote…</i></summary>
> the RootUserName is referred by the default config in config.go. It need a const variable.
> ```
> const(
> ...
> defaultUser     = security.RootUserName
> ...
> )
> ```
</details>
just remove config.defaultUser and use `security.RootUser.Username()` instead

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591)*

**Comment by yznming** [comment]
Review status: 5 of 48 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/security/auth.go, line 32 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591#-KWDJDHpVobpdqifUVib:-KWE7OlUyVtE8EPLVU15:b-6c91xy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbad7176c14b42197911c22c1d4bdcf9fc5abe1/pkg/security/auth.go#L32)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> just remove config.defaultUser and use `security.RootUser.Username()` instead
</details>
config.defaultUser is a constant variable, can not accept a non-constant variable
```
pkg/base/config.go:39: const initializer security.RootUser.Username() is not a constant
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591)*

**Comment by tamird** [comment]
Review status: 5 of 48 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/security/auth.go, line 32 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591#-KWDJDHpVobpdqifUVib:-KWE8t6zG_GZjTv3Rmn1:b-kn7ari) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbad7176c14b42197911c22c1d4bdcf9fc5abe1/pkg/security/auth.go#L32)):*
<details><summary><i>Previously, yznming (Yan Long) wrote…</i></summary>
> config.defaultUser is a constant variable, can not accept a non-constant variable
> ```
> pkg/base/config.go:39: const initializer security.RootUser.Username() is not a constant
> ```
</details>
I understand that, but it is only used in one place, and that place *can* accept a non-constant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591)*

**Comment by yznming** [comment]
Review status: 5 of 48 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/security/auth.go, line 32 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591#-KWDJDHpVobpdqifUVib:-KWE9G6gFq7nwDnwzPT3:bbqiko2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbad7176c14b42197911c22c1d4bdcf9fc5abe1/pkg/security/auth.go#L32)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I understand that, but it is only used in one place, and that place *can* accept a non-constant.
</details>
got it, thx.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591)*

**Comment by yznming** [comment]
Review status: 4 of 48 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/acceptance/cluster/localcluster.go, line 807 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591#-KWDri3rAe3fNulErbtN:-KWH-Z7mlQfQsWohhFIW:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbad7176c14b42197911c22c1d4bdcf9fc5abe1/pkg/acceptance/cluster/localcluster.go#L807)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary>
> Remove this line and use `security.RootUser` directly when constructing the url.
</details>
done

---

*[pkg/security/auth.go, line 29 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591#-KWDJ8VWcCuzJqGFbVRq:-KWH07xRicYMUEc6lSiF:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbad7176c14b42197911c22c1d4bdcf9fc5abe1/pkg/security/auth.go#L29)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can this be removed? it's not used except for in NodeUser.
</details>
done

---

*[pkg/security/auth.go, line 32 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591#-KWDJDHpVobpdqifUVib:-KWH08rhurkxn4g4GoIV:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbad7176c14b42197911c22c1d4bdcf9fc5abe1/pkg/security/auth.go#L32)):*
<details><summary><i>Previously, yznming (Yan Long) wrote…</i></summary>
> got it, thx.
</details>
done

---

*[pkg/security/auth.go, line 147 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591#-KWDuG3c-5m6NUiAXB8h:-KWH-VUX7f3zDiSXjxyg:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbad7176c14b42197911c22c1d4bdcf9fc5abe1/pkg/security/auth.go#L147)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary>
> `url.Userinfo`'s `String()` method prints the username if the user doesn't have a password set and `username:pwd` if it does. Although `RootUser` doesn't have a password, I would be more comfortable changing this to `RootUser.Username()` or `requestedUser`. Make sure to take this into account in tests as well (e.g. in `pkg/sql/pgwire_test.go`) for the sake of consistency.
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591)*

**Comment by tamird** [comment]
Reviewed 41 of 48 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/security/auth.go, line 147 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591#-KWDuG3c-5m6NUiAXB8h:-KWHGHlptx2NuZ0TaiN7:bupfh13) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbad7176c14b42197911c22c1d4bdcf9fc5abe1/pkg/security/auth.go#L147)):*
<details><summary><i>Previously, yznming (Yan Long) wrote…</i></summary>
> done
</details>
+1 to `requestedUser`

---

*[pkg/sql/pgwire_test.go, line 146 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591#-KWHGk8OD9N6Gqf6b8tn:-KWHGk8OD9N6Gqf6b8to:b-37k9nk) ([raw file](https://github.com/cockroachdb/cockroach/blob/5954f01bac2cd77650ed50069b5627e1c8835890/pkg/sql/pgwire_test.go#L146)):*
> ```Go
> 
> 		{
> 			for _, optUser := range []string{server.TestUser, security.RootUser.Username()} {
> ```

this should be `[]url.User{url.User(server.TestUser), security.RootUser}`

or perhaps `server.TestUser` should also change to be a url.User

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591)*

**Comment by yznming** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/security/auth.go, line 147 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591#-KWDuG3c-5m6NUiAXB8h:-KWHr0Tts5SFfsf_4j_W:bbg93wl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbad7176c14b42197911c22c1d4bdcf9fc5abe1/pkg/security/auth.go#L147)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> +1 to `requestedUser`
</details>
 what do you mean `requestedUser`? the `requestedUser` is a string now. I think no need to convert it again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/security/auth.go, line 147 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591#-KWDuG3c-5m6NUiAXB8h:-KWKfuXBUkNP-3pN4-5x:b-ksdkgs) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbad7176c14b42197911c22c1d4bdcf9fc5abe1/pkg/security/auth.go#L147)):*
<details><summary><i>Previously, yznming (Yan Long) wrote…</i></summary>
>  what do you mean `requestedUser`? the `requestedUser` is a string now. I think no need to convert it again.
</details>
`return errors.Errorf("user %s must authenticate using a client certificate ", requestedUser)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591)*

**Comment by yznming** [comment]
Review status: 41 of 48 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/security/auth.go, line 147 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591#-KWDuG3c-5m6NUiAXB8h:-KWLEi7gUk0PORZBqliK:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbad7176c14b42197911c22c1d4bdcf9fc5abe1/pkg/security/auth.go#L147)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> `return errors.Errorf("user %s must authenticate using a client certificate ", requestedUser)`
</details>
done

---

*[pkg/sql/pgwire_test.go, line 146 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591#-KWHGk8OD9N6Gqf6b8tn:-KWLEtbzIH0CrNubgHj6:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5954f01bac2cd77650ed50069b5627e1c8835890/pkg/sql/pgwire_test.go#L146)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this should be `[]url.User{url.User(server.TestUser), security.RootUser}`
> 
> or perhaps `server.TestUser` should also change to be a url.User
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591)*

**Comment by tamird** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591)*

**Comment by yznming** [comment]
@tamird sorry, I cann't see any comment in your review. Is there any problem?

**Comment by tamird** [comment]
nope, LGTM, but @asubiotto should take a final look

**Comment by yznming** [comment]
@tamird thanks a lot

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/base/config.go, line 118 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591#-KWOAj7ZN_FcjXb7AGMT:-KWOAj7ZN_FcjXb7AGMU:b96mpq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9655b724bf10736c3fed31df6854b5bc73ad1d5/pkg/base/config.go#L118)):*
> ```Go
> func (cfg *Config) InitDefaults() {
> 	cfg.Insecure = defaultInsecure
> 	cfg.User = security.RootUser.Username()
> ```

I think it might be nicer to make `Config.User` a `url.User` instead of a string (and similar changes to other functions that take users). We can pass things around as `url.User` as long as possible and only call `Username()` at the point where we specifically need a string. We haven't gained much if we remove calls to `url.User` conversions at half the uses of these constants only to add calls to `.Username()` to the other half.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591)*

**Comment by yznming** [comment]
Review status: 37 of 46 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/base/config.go, line 118 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591#-KWOAj7ZN_FcjXb7AGMT:-KWa3d8enOjt41sSYR2X:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9655b724bf10736c3fed31df6854b5bc73ad1d5/pkg/base/config.go#L118)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> I think it might be nicer to make `Config.User` a `url.User` instead of a string (and similar changes to other functions that take users). We can pass things around as `url.User` as long as possible and only call `Username()` at the point where we specifically need a string. We haven't gained much if we remove calls to `url.User` conversions at half the uses of these constants only to add calls to `.Username()` to the other half.
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591)*

**Comment by bdarnell** [comment]
I'm having second thoughts about this change (and #9876). Sometimes we use these usernames to construct URLs, and sometimes we use them in other ways. And one of the main benefits of url.UserInfo, the ability to pair a password with the username, we never use at all. We could replace all of our string usernames with a url.UserInfo containing a string username, but why? (in the long run we may want to replace string usernames with something more structured, but using url.UserInfo doesn't help us with that) And if we do make this change, I think it should go even further than this change does now. For example, the security.RequestWithUser.GetUser method should return the same type as the `{Node,Root}User` constants. @asubiotto What do you think?

---

Reviewed 10 of 48 files at r1, 3 of 7 files at r3, 7 of 11 files at r4.
Review status: 44 of 46 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591#-:-KWaiABB3_b9qHxwAxXq:b-nekab5)*

**Comment by asubiotto** [comment]
The ability to pair a password with the username is used when constructing a postgres url which is how a password is "passed" to be used by lib/pq. I think that you're right. This change would be nice to have so that we don't need to construct url.Userinfos when creating postgres urls but on the other hand I think we actually lose out because everything else uses users as strings and even if we do change those instances to care about url.Userinfos we never care about the password field anyway.

@yznming I appreciate the work you've put into this and I apologize for wasting your time.

---

Review status: 44 of 46 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10591#-:-KWcSzS8s_8VoiaEnZ5e:bneofop)*

**Comment by yznming** [comment]
@asubiotto it doesn't metter.  shall I close this pr now?

**Comment by asubiotto** [comment]
Yes, go ahead.

**Pull request closed without merging**
