### PR TITLE
sql: decode utf-8 runes in colexec substring

### LINKED ISSUE #76359: In the vectorized execution engine, incorrect execution result of function substr
```sql
root@localhost:26257/defaultdb> create table t(a string);
CREATE TABLE


Time: 127ms total (execution 126ms / network 0ms)

root@localhost:26257/defaultdb> insert into t values('你好吗');
INSERT 1


Time: 87ms total (execution 86ms / network 1ms)


root@localhost:26257/defaultdb> select substr(a,1,2) from t;
   substr
------------
  \xe4\xbd
(1 row)


Time: 2ms total (execution 2ms / network 0ms)

root@localhost:26257/defaultdb> set session vectorize=off;
SET


Time: 0ms total (execution 0ms / network 0ms)

root@localhost:26257/defaultdb> select substr(a,1,2) from t;
  substr
----------
  你好
(1 row)


Time: 1ms total (execution 1ms / network 0ms)
```

Jira issue: CRDB-13080

### PR DESCRIPTION
**Pull request by rharding6373**
Before this change, the substring implementation in colexec assumed that
each character in a string was 1 byte. However, in some character
encodings like UTF-8 a character may be represented using more than 1
byte, which meant that using the `substr()` function may cut off
characters in unexpected ways.
    
This change decodes runes to get the byte offsets for the start and end
of a substring, and increases test coverage for substring.
    
Fixes: #76359
    
Release justification: bug fix
Release note (bug fix): Fixes the implementation of function `substr()`
in the vectorized execution engine for UTF-8 encodings.

### CODE REVIEW

**Comment by rharding6373** [comment]
This PR is a highly collaborative effort with @cucaroach, who both found the root cause and the library to solve it. Thanks!

I ran the substring benchmark, and we increase our runtime by ~75%. Thoughts?: https://gist.github.com/rharding6373/bb0b4abd475f794073b721b5f671ce9d

**Review by cucaroach — COMMENTED** [review]
:LGTM: while the perf hit is disconcerting its still way faster than the default.     

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77308#-:-MxCWoibBgupuYDaOEVf:be2bn8m)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek, @rharding6373, and @yuzefovich)

___
*[pkg/sql/colexec/substring_tmpl.go, line 172 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77308#-MxCVWKl8H-WDsDnkNMZ:-MxCVWKl8H-WDsDnkNM_:b-qz3wn3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dfd052cf296ed1ba04c07584aed36abebb3f350/pkg/sql/colexec/substring_tmpl.go#L172)):*
> ```Go
> 					count++
> 				}
> 				start = totalSize
> ```

nit: I think this code would be easier to follow if runes was called bytes and we didn't resuse rune indices as byte indices,  i.e, just introduce two new variables for the start, end utf8 indices.   Conceptually byte indices and character indices should be viewed as separate types IMHO.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77308)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek and @rharding6373)

___
*[pkg/sql/colexec/substring_tmpl.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77308#-MxChInRBtdr4QMrZQw3:-MxChInRBtdr4QMrZQw4:b9ti7cn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dfd052cf296ed1ba04c07584aed36abebb3f350/pkg/sql/colexec/substring_tmpl.go#L106)):*
> ```Go
> 
> 	sel := batch.Selection()
> 	runeVec := batch.ColVec(s.argumentCols[0]).Bytes()
> ```

Is it possible to determine quickly whether `[]byte` contains any characters that need more than 1 byte? I'm thinking we could ask the `Bytes` vector to return its whole `data` slice (via a new method, or by abusing the serialization to Arrow format) and run the check on the whole vector, and then for each row we would adjust the behavior depending on whether the vector has such characters or not.

**Review by msirek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77308)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach, @msirek, @rharding6373, and @yuzefovich)

___
*[pkg/sql/colexec/substring_tmpl.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77308#-MxChInRBtdr4QMrZQw3:-MxDCU_3Be7gUIoVphZh:bpq2y3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dfd052cf296ed1ba04c07584aed36abebb3f350/pkg/sql/colexec/substring_tmpl.go#L106)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Is it possible to determine quickly whether `[]byte` contains any characters that need more than 1 byte? I'm thinking we could ask the `Bytes` vector to return its whole `data` slice (via a new method, or by abusing the serialization to Arrow format) and run the check on the whole vector, and then for each row we would adjust the behavior depending on whether the vector has such characters or not.
</blockquote></details>

I think you can just look at the local bytes slice to determine if they're all single-byte chars using the `RuneCount` function.  It seems to reduce the amount of the regression:
https://gist.github.com/msirek/f65000e3908c85a2814f485adad21d0b

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77308)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach, @msirek, @rharding6373, and @yuzefovich)

___
*[pkg/sql/colexec/substring_tmpl.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77308#-MxChInRBtdr4QMrZQw3:-MxDJIeu7tPEuaZA2KOs:b-ca9nfo) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dfd052cf296ed1ba04c07584aed36abebb3f350/pkg/sql/colexec/substring_tmpl.go#L106)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

I think you can just look at the local bytes slice to determine if they're all single-byte chars using the `RuneCount` function.  It seems to reduce the amount of the regression:
https://gist.github.com/msirek/f65000e3908c85a2814f485adad21d0b
</blockquote></details>

The code in this gist fails the unit test, but this modified check works because it can check for a double-byte char in the last position:
`if utf8.RuneCount(runes[:end+1]) != end+1 {`
Some more work is probably needed to refine this and also make sure `end+1` isn't past the end of the byte slice.

**Review by rharding6373 — COMMENTED** [review]
Thanks for all the suggestions! RFAL now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77308#-:-MyJuez_ChFKCMZCCh2T:b-w8f88u)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach, @msirek, and @yuzefovich)

___
*[pkg/sql/colexec/substring_tmpl.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77308#-MxChInRBtdr4QMrZQw3:-MyJWYup9dOqJkzEgWGd:b-3etr9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dfd052cf296ed1ba04c07584aed36abebb3f350/pkg/sql/colexec/substring_tmpl.go#L106)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

The code in this gist fails the unit test, but this modified check works because it can check for a double-byte char in the last position:
`if utf8.RuneCount(runes[:end+1]) != end+1 {`
Some more work is probably needed to refine this and also make sure `end+1` isn't past the end of the byte slice.
</blockquote></details>

Thanks for the suggestions! Because `RuneCount` will treat short encodings as 1 byte, which could lead to incorrect behavior if the substring end cuts off a rune, I think we need to use `RuneCount` on the entire `bytes`. There's still a lot of variation in the benchmark, unfortunately (though I got quite a bit of variation when I tried the benchmark on master without my change, too): https://gist.github.com/rharding6373/148f6e9c92674f88da3f12799179b272
___
*[pkg/sql/colexec/substring_tmpl.go, line 172 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77308#-MxCVWKl8H-WDsDnkNMZ:-MxazHz98uqyTJmm31Pu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dfd052cf296ed1ba04c07584aed36abebb3f350/pkg/sql/colexec/substring_tmpl.go#L172)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

nit: I think this code would be easier to follow if runes was called bytes and we didn't resuse rune indices as byte indices,  i.e, just introduce two new variables for the start, end utf8 indices.   Conceptually byte indices and character indices should be viewed as separate types IMHO.
</blockquote></details>

Done.

**Review by cucaroach — APPROVED** [review]
:LGTM:

> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77308#-:-MyKUoGvAlM-TvCtP1yh:bmxilld)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by yuzefovich — APPROVED** [review]
Looks like you need to regenerate `eg.go` file, but otherwise :lgtm:

> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77308#-:-MyKdRGh1mUE59lmV-LA:b-y7ptcx)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @rharding6373)

___
*[-- commits, line 6 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77308#-MyKd4M90lEy01w3GvmQ):*
Are there other encodings we have to be concerned about?

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77308)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @rharding6373)

___
*[pkg/sql/colexec/substring_tmpl.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77308#-MxChInRBtdr4QMrZQw3:-MyMvqyZDn05mtTM0KTW:bgj8003) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dfd052cf296ed1ba04c07584aed36abebb3f350/pkg/sql/colexec/substring_tmpl.go#L106)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Thanks for the suggestions! Because `RuneCount` will treat short encodings as 1 byte, which could lead to incorrect behavior if the substring end cuts off a rune, I think we need to use `RuneCount` on the entire `bytes`. There's still a lot of variation in the benchmark, unfortunately (though I got quite a bit of variation when I tried the benchmark on master without my change, too): https://gist.github.com/rharding6373/148f6e9c92674f88da3f12799179b272
</blockquote></details>

Looks good.  Does something need to be run to update `substring.eg.go` with the new template code?  It looks like it's referring to the old code.

**Review by rharding6373 — COMMENTED** [review]
Thanks for all the reviews!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77308#-:-MyNimOO7GSwLtVR0X_w:bd36oot)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @cucaroach and @yuzefovich)

___
*[-- commits, line 6 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77308#-MyKd4M90lEy01w3GvmQ):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Are there other encodings we have to be concerned about?
</blockquote></details>

CRDB only supports utf8 and unicode at the moment [0], so I don't think we have to worry about covering the other encodings supported by postgres [1] at this time.

[0] https://www.cockroachlabs.com/docs/v21.2/create-database.html
[1] https://www.postgresql.org/docs/current/multibyte.html#MULTIBYTE-CHARSET-SUPPORTED
___
*[pkg/sql/colexec/substring_tmpl.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77308#-MxChInRBtdr4QMrZQw3:-MyNiMS10ut3XCveh6Us:bn1q83) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dfd052cf296ed1ba04c07584aed36abebb3f350/pkg/sql/colexec/substring_tmpl.go#L106)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Looks good.  Does something need to be run to update `substring.eg.go` with the new template code?  It looks like it's referring to the old code.
</blockquote></details>

Thanks for catching this, I don't know why `make generate` didn't catch this, but looks like `./dev generate go` did. I reran the benchmark and got down to +43%, but there's still quite a bit of variance.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77308)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rharding6373)

___
*[pkg/sql/colexec/substring_tmpl.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77308#-MxChInRBtdr4QMrZQw3:-MyNjGpG-cKRFmYp8QPO:b-f2ua46) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dfd052cf296ed1ba04c07584aed36abebb3f350/pkg/sql/colexec/substring_tmpl.go#L106)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Thanks for catching this, I don't know why `make generate` didn't catch this, but looks like `./dev generate go` did. I reran the benchmark and got down to +43%, but there's still quite a bit of variance.
</blockquote></details>

The right command is `make execgen` - not sure if `make generate` does generate the execgen code.

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77308)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rharding6373)

___
*[pkg/sql/colexec/substring_tmpl.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77308#-MxChInRBtdr4QMrZQw3:-MyNpQ0z0eVo4ZhykYjX:b-zcjvte) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dfd052cf296ed1ba04c07584aed36abebb3f350/pkg/sql/colexec/substring_tmpl.go#L106)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

The right command is `make execgen` - not sure if `make generate` does generate the execgen code.
</blockquote></details>

Thanks

**Comment by rharding6373** [comment]
Test failure is a known flake.

bors r+

**Review by msirek — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77308#-:-MyO74UR61pVK3w39sP8:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @rharding6373)

**Pull request merged**
