### PR TITLE
changefeedccl: use a btree instead of a map of files in cloudstorage sink

### PR DESCRIPTION
**Pull request by ajwerner**
In #41615 we fixed an ordering bug by making sure when flushing a file for a
topic at a given schema version to always flush the files of the same topic at
earlier schema versions first. Prior to this commit we stored open files in an
unordered map.  In order to perform the flushing logic we would scan all of the
open files, put them into a slice and sort them.

This PR instead stores the files in an ordered btree which allows the flush
ordering to be achieved more simply.

Release note: None.

### CODE REVIEW

**Comment by ajwerner** [comment]
I'll be the first to admit this doesn't really end up being all that much simpler and while theoretically more efficient it probably is premature optimization. :woman_shrugging:

**Review by danhhz — COMMENTED** [review]
Cool!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41730#-:-LrVPTmf8kuaS64RShUI:b-89q77x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, and @danhhz)

___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 442 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41730#-LrVOrEt5XP2CT7mLcwc:-LrVOrEt5XP2CT7mLcwd:b-c2eo87) ([raw file](https://github.com/cockroachdb/cockroach/blob/e331ef02a9c9a5e5d3d8047d5247fdbf5d20a445/pkg/ccl/changefeedccl/sink_cloudstorage.go#L442)):*
> ```Go
> 	for called := true; called && key.schemaID <= maxVersionToFlush; {
> 		called = false
> 		s.files.AscendRange(key, lt, func(i btree.Item) (wantMore bool) {
> ```

why do this instead of appending the file key to a slice whenever flushFile doesn't error and unconditionally remove everything in the slide from the btree before returning?
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 523 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41730#-LrVPQuX-jEfnpqA-QK-:-LrVPQuX-jEfnpqA-QK0:bbtqg2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/e331ef02a9c9a5e5d3d8047d5247fdbf5d20a445/pkg/ccl/changefeedccl/sink_cloudstorage.go#L523)):*
> ```Go
> }
> 
> type keyer interface {
> ```

why the interface indirection here?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41730)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @danhhz)

___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 442 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41730#-LrVOrEt5XP2CT7mLcwc:-LrVPj4--V5f97UJ-g2S:bonfjsu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e331ef02a9c9a5e5d3d8047d5247fdbf5d20a445/pkg/ccl/changefeedccl/sink_cloudstorage.go#L442)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

why do this instead of appending the file key to a slice whenever flushFile doesn't error and unconditionally remove everything in the slide from the btree before returning?
</blockquote></details>

The thought crossed my mind. A major reason for the btree was to try to not allocate the slice. I felt like once I got to this point I might as well go all the way. Premature optimization for sure. 
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 523 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41730#-LrVPQuX-jEfnpqA-QK-:-LrVQD8Z9WrmOlaKAQge:b95lku0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e331ef02a9c9a5e5d3d8047d5247fdbf5d20a445/pkg/ccl/changefeedccl/sink_cloudstorage.go#L523)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

why the interface indirection here?
</blockquote></details>

So that I can use both `cloudStoreSinkKey`and `*cloudStorageSinkFile` to key into the tree. It was more complicated than it needed to be. I simplified.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41730)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @ajwerner)

___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 442 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41730#-LrVOrEt5XP2CT7mLcwc:-LrVbPoCDHzLP8D6NPWt:bkjpp9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/e331ef02a9c9a5e5d3d8047d5247fdbf5d20a445/pkg/ccl/changefeedccl/sink_cloudstorage.go#L442)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

The thought crossed my mind. A major reason for the btree was to try to not allocate the slice. I felt like once I got to this point I might as well go all the way. Premature optimization for sure. 
</blockquote></details>

I liked the btree because the version now in master has to scan all sorts of map keys from unrelated topics to flush a file past its size threshold, which felt like it could have gotten arbitrarily bad with long flush intervals

I don't think we care about the slice. There's no concurrency issues, so we can store it on `cloudStorageSink` and reuse it. A slice on cloudStorageSink with a length bounded by the high-water of files we simultaneously buffered sounds totally fine

I'm only pushing back on this bit because the execution flow in this for loop is hard for me to follow. All of the rest of the btree usage in this PR seems pretty straightforward, so I just want to make sure this really is necessary
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 523 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41730#-LrVPQuX-jEfnpqA-QK-:-LrVdWHi37VbEi_Kb7LD:b-e76dst) ([raw file](https://github.com/cockroachdb/cockroach/blob/e331ef02a9c9a5e5d3d8047d5247fdbf5d20a445/pkg/ccl/changefeedccl/sink_cloudstorage.go#L523)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

So that I can use both `cloudStoreSinkKey`and `*cloudStorageSinkFile` to key into the tree. It was more complicated than it needed to be. I simplified. 
</blockquote></details>

oh that seems fine if you preferred it. just deserved a comment on why it was there

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41730)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 442 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41730#-LrVOrEt5XP2CT7mLcwc:-LrVSG2r7YOjTBM5_zM-:bmufcx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e331ef02a9c9a5e5d3d8047d5247fdbf5d20a445/pkg/ccl/changefeedccl/sink_cloudstorage.go#L442)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I liked the btree because the version now in master has to scan all sorts of map keys from unrelated topics to flush a file past its size threshold, which felt like it could have gotten arbitrarily bad with long flush intervals

I don't think we care about the slice. There's no concurrency issues, so we can store it on `cloudStorageSink` and reuse it. A slice on cloudStorageSink with a length bounded by the high-water of files we simultaneously buffered sounds totally fine

I'm only pushing back on this bit because the execution flow in this for loop is hard for me to follow. All of the rest of the btree usage in this PR seems pretty straightforward, so I just want to make sure this really is necessary
</blockquote></details>

Totally fair. I added a 1-line premature optimization which will cover just about every situation that meaningfully happens, feel free to push back against it too.

**Review by danhhz — COMMENTED** [review]
:lgtm: awesome!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41730#-:-LrVhRex5pdENxRUg3u7:bru7mod)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)

**Review by ajwerner — COMMENTED** [review]
TFTR!

bors r=danhhz

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41730#-:-LrVqvXJ85CHUrZyiRTh:b-vwgs12)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)

**Pull request merged**
