### PR TITLE
acceptance: log docker-spy output

### PR DESCRIPTION
**Pull request by petermattis**
Trying to track down DNS failures as seen in #4894..

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4924)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[acceptance/cluster/localcluster.go, line 646 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4924#-KCCtIKIrPQNKgro1vja:-KCCtIKJ0hwdF0pGD9YW:566440297) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ef07e2279a0ef8d85eff4a4598f68006804881a/acceptance/cluster/localcluster.go#L646)):*
stuff below this line is still duplicated (while stuff above is not)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4924#-:-KCCtNwNPRZp2IVFcb2a:1417088721)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[acceptance/cluster/localcluster.go, line 646 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4924#-KCCtIKIrPQNKgro1vja:-KCCueFDXTqcI4TRa6ar:-317148601) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ef07e2279a0ef8d85eff4a4598f68006804881a/acceptance/cluster/localcluster.go#L646)):*
Is that better?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4924)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[acceptance/cluster/localcluster.go, line 607 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4924#-KCCv-p7T9w2-Cg0oxmt:-KCCv-p7T9w2-Cg0oxmu:-1884272422) ([raw file](https://github.com/cockroachdb/cockroach/blob/609217f360635b3e6663a7a7ed219c8d8dce51ea/acceptance/cluster/localcluster.go#L607)):*
fwiw `Container`s know their own `Name()`s

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4924)*

**Comment by petermattis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[acceptance/cluster/localcluster.go, line 607 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4924#-KCCv-p7T9w2-Cg0oxmt:-KCE-jB2Cyo3uG51ZNOS:320136536) ([raw file](https://github.com/cockroachdb/cockroach/blob/609217f360635b3e6663a7a7ed219c8d8dce51ea/acceptance/cluster/localcluster.go#L607)):*
Oh, good point. The commit is now a mess because I'm trying to debug stuff on circleci. I'll clean it up again before merging.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4924)*

**Comment by petermattis** [comment]
Obsoleted by #4927.

**Pull request closed without merging**
