### PR TITLE
cli: Respect signals during server initialization

### LINKED ISSUE #10138: cli: process doesn't handle SIGTERM while trying to join cluster on startup
Start a cockroach process and try to join it to a port that isn't listening:

```
./cockroach start --logtostderr --join=localhost:2628 --store=./initially-empty-dir
```

The process will get in an endless retry loop, repeatedly complaining about its inability to connect to the join target with log messages like:

```
I161021 15:00:57.121690 69 /Users/alex/go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:26258: getsockopt: connection refused"; Reconnecting to {"localhost:26258" <nil>}
```

Pressing CTRL+C has no effect on the process while it's in this state, no matter how many times I press it, even though pressing it twice is typically supposed to bring the process down immediately. Similarly, running `./cockroach quit` on it just hangs and running `kill <pid>` on it also has no effect.

### PR DESCRIPTION
**Pull request by a-robinson**
Fixes #10138

The `runStart` change was thrown together perhaps a little hastily, so let me know if you think it needs more work.

@knz

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12743)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks pending.

---

*[pkg/cli/start.go, line 333 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pCle1bkafavpxx8y9:-K_pCle1bkafavpxx8yA:b-4pk6f5) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbbc23c137385ef35e1f5209ab5e4d3910c2e61b/pkg/cli/start.go#L333)):*
> ```Go
> 	var serverCreated bool
> 	var serverDraining bool
> 	var serverStatusMu syncutil.Mutex // protects serverCreated and serverDraining
> ```

how about
```
var serverStatusMu struct {
  sync.Mutex
  created, draining bool
}
```

---

*[pkg/cli/start.go, line 336 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pCundE4rnzD2klnrr:-K_pCundE4rnzD2klnrs:bhxjn3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbbc23c137385ef35e1f5209ab5e4d3910c2e61b/pkg/cli/start.go#L336)):*
> ```Go
> 	var s *server.Server
> 	errChan := make(chan error, 1)
> 	go func() {
> ```

Consider:
```
go func() {
  errChan <- func() error {
    ...
  }()
}()
```
to avoid repeating yourself with the `return`s.

---

*[pkg/cli/start.go, line 338 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pDBc8dqFDdVU0BOnw:-K_pDBc8dqFDdVU0BOnx:b5hrq77) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbbc23c137385ef35e1f5209ab5e4d3910c2e61b/pkg/cli/start.go#L338)):*
> ```Go
> 	go func() {
> 		if err := serverCfg.InitNode(); err != nil {
> 			errChan <- fmt.Errorf("failed to initialize node: %s", err)
> ```

while you're here - wrap?

---

*[pkg/cli/start.go, line 350 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pD6VsbaH46M7Avxyb:-K_pD6VsbaH46M7Avxyc:b5hrq77) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbbc23c137385ef35e1f5209ab5e4d3910c2e61b/pkg/cli/start.go#L350)):*
> ```Go
> 		s, err = server.NewServer(serverCfg, stopper)
> 		if err != nil {
> 			errChan <- fmt.Errorf("failed to start Cockroach server: %s", err)
> ```

while you're here - wrap?

---

*[pkg/cli/start.go, line 357 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pDdE00ORaZihNcchV:-K_pDdE00ORaZihNcchW:b-ojb06q) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbbc23c137385ef35e1f5209ab5e4d3910c2e61b/pkg/cli/start.go#L357)):*
> ```Go
> 		serverCreated = true
> 		if serverDraining {
> 			return
> ```

is it intended that this leaves the lock held?

---

*[pkg/cli/start.go, line 412 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pDG1azdT3ODBipp6x:-K_pDG1azdT3ODBipp6y:b1j9rqp) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbbc23c137385ef35e1f5209ab5e4d3910c2e61b/pkg/cli/start.go#L412)):*
> ```Go
> 	signalCh := make(chan os.Signal, 1)
> 	signal.Notify(signalCh, os.Interrupt)
> 	// TODO(spencer): move this behind a build tag.
> ```

i don't understand this TODO. Do you?

---

*[pkg/cli/start.go, line 417 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pDWtbcetkEDszpxYA:-K_pDNT9jV_5dtQG_ZJx:b-s4hzt7) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbbc23c137385ef35e1f5209ab5e4d3910c2e61b/pkg/cli/start.go#L417)):*
> ```Go
> 	// Block until one of the signals above is received or the stopper
> 	// is stopped externally (for example, via the quit endpoint).
> 	var returnErr error
> ```

nit: put this back - confusing to see it as part of this diff

---

*[pkg/cli/start.go, line 435 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pDptNMeWplzd9-6KD:-K_pDptNMeWplzd9-6KE:btqw1me) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbbc23c137385ef35e1f5209ab5e4d3910c2e61b/pkg/cli/start.go#L435)):*
> ```Go
> 		go func() {
> 			serverStatusMu.Lock()
> 			defer serverStatusMu.Unlock()
> ```

the code below can be slow, any reason to hold the mutex throughout?

---

*[pkg/cli/start.go, line 442 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pDnEmeMPYoEHZ7G2R:-K_pDnEmeMPYoEHZ7G2S:bwdbm68) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbbc23c137385ef35e1f5209ab5e4d3910c2e61b/pkg/cli/start.go#L442)):*
> ```Go
> 				}
> 			}
> 			stopper.Stop()
> ```

is this change meaningful?

---

*[pkg/server/node.go, line 568 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pCe3b7pC7KOu-FrRd:-K_pCe3b7pC7KOu-FrRe:b-t1ntkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/9525b97d32b20d802aed21e2994c21b6b9e0ee3a/pkg/server/node.go#L568)):*
> ```Go
> // for a match. If not part of a cluster, the cluster ID is set. The
> // node's address is gossiped with node ID as the gossip key.
> func (n *Node) connectGossip(ctx context.Context) {
> ```

might be time to return an error.

---

*[pkg/server/node.go, line 570 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pCVjriyBB7I4qxXyr:-K_pCVjriyBB7I4qxXys:b2ni78k) ([raw file](https://github.com/cockroachdb/cockroach/blob/a35fdc7f37f087688b5539c28d344426143d54c6/pkg/server/node.go#L570)):*
> ```Go
> func (n *Node) connectGossip(ctx context.Context) {
> 	log.Infof(ctx, "connecting to gossip network to verify cluster ID...")
> 	// No timeout or stop condition is needed here. Log statements should be
> ```

lol

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743)*

**Comment by a-robinson** [comment]
Review status: 1 of 2 files reviewed at latest revision, 10 unresolved discussions.

---

*[pkg/cli/start.go, line 333 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pCle1bkafavpxx8y9:-K_pErpteG4xltyMbgnv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbbc23c137385ef35e1f5209ab5e4d3910c2e61b/pkg/cli/start.go#L333)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

how about
```
var serverStatusMu struct {
  sync.Mutex
  created, draining bool
}
```
</blockquote></details>

Done.

---

*[pkg/cli/start.go, line 336 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pCundE4rnzD2klnrr:-K_pEwbofhwjqYYDyfur:bgtszsw) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbbc23c137385ef35e1f5209ab5e4d3910c2e61b/pkg/cli/start.go#L336)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Consider:
```
go func() {
  errChan <- func() error {
    ...
  }()
}()
```
to avoid repeating yourself with the `return`s.
</blockquote></details>

But then we have an extra layer of indentation, and will have to special the channel send to avoid passing on a nil error in the case of a successful initialization

---

*[pkg/cli/start.go, line 338 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pDBc8dqFDdVU0BOnw:-K_pFVjKAH8Hk_s08jhg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbbc23c137385ef35e1f5209ab5e4d3910c2e61b/pkg/cli/start.go#L338)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

while you're here - wrap?
</blockquote></details>

Done.

---

*[pkg/cli/start.go, line 350 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pD6VsbaH46M7Avxyb:-K_pFWLQwFQ2dVF6GyF1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbbc23c137385ef35e1f5209ab5e4d3910c2e61b/pkg/cli/start.go#L350)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

while you're here - wrap?
</blockquote></details>

Done.

---

*[pkg/cli/start.go, line 357 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pDdE00ORaZihNcchV:-K_pFYAbbzFY3OyU-ZC5:bka3h06) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbbc23c137385ef35e1f5209ab5e4d3910c2e61b/pkg/cli/start.go#L357)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is it intended that this leaves the lock held?
</blockquote></details>

Nope, thanks.

---

*[pkg/cli/start.go, line 412 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pDG1azdT3ODBipp6x:-K_pFc5MOYy5CBtEeie_:bybnyxh) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbbc23c137385ef35e1f5209ab5e4d3910c2e61b/pkg/cli/start.go#L412)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

i don't understand this TODO. Do you?
</blockquote></details>

No. I'll remove it unless @spencerkimball can remember what he may have been thinking when he wrote it.

---

*[pkg/cli/start.go, line 417 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pDWtbcetkEDszpxYA:-K_pFnmMFN3uMGGP9-6H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbbc23c137385ef35e1f5209ab5e4d3910c2e61b/pkg/cli/start.go#L417)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: put this back - confusing to see it as part of this diff
</blockquote></details>

Done.

---

*[pkg/cli/start.go, line 435 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pDptNMeWplzd9-6KD:-K_pG7_uoip6U7tm3oMq:b-oqrkmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbbc23c137385ef35e1f5209ab5e4d3910c2e61b/pkg/cli/start.go#L435)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

the code below can be slow, any reason to hold the mutex throughout?
</blockquote></details>

Not really. Changed

---

*[pkg/cli/start.go, line 442 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pDnEmeMPYoEHZ7G2R:-K_pG91dqJ0iNkWJbizQ:ba9446o) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbbc23c137385ef35e1f5209ab5e4d3910c2e61b/pkg/cli/start.go#L442)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is this change meaningful?
</blockquote></details>

Yes - if the server hasn't been created, then it won't have a stopper.

---

*[pkg/server/node.go, line 568 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pCe3b7pC7KOu-FrRd:-K_pIugZ5vocpNaxw7Uj:b-yjmqse) ([raw file](https://github.com/cockroachdb/cockroach/blob/9525b97d32b20d802aed21e2994c21b6b9e0ee3a/pkg/server/node.go#L568)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

might be time to return an error.
</blockquote></details>

I thought so too, but for some reason the server is getting stuck in a mux Accept call even though the mux should have already been closed - https://github.com/cockroachdb/cockroach/blob/master/pkg/server/server.go#L505

I'll dig more into why

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/cli/start.go, line 336 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pCundE4rnzD2klnrr:-K_pJcrWUHYyLHNYde-5:b-3q4hcm) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbbc23c137385ef35e1f5209ab5e4d3910c2e61b/pkg/cli/start.go#L336)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

But then we have an extra layer of indentation, and will have to special the channel send to avoid passing on a nil error in the case of a successful initialization
</blockquote></details>

I don't think the indentation is that bad, and regarding the channel send - you could nil check on the receiving end?

---

*[pkg/cli/start.go, line 357 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pDdE00ORaZihNcchV:-K_pJp577H9CVslYKSSi:bxd7kjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbbc23c137385ef35e1f5209ab5e4d3910c2e61b/pkg/cli/start.go#L357)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Nope, thanks.
</blockquote></details>

nit: i'd write
```
draining := serverStatusMu.draining
serverStatusMu.Unlock()
if draining {
...
```

---

*[pkg/cli/start.go, line 425 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pKMkrN3Hn8k-7gv2y:-K_pKMkrN3Hn8k-7gv2z:bycl4mt) ([raw file](https://github.com/cockroachdb/cockroach/blob/58e58ad7fa5efcc53a60cfd79617226d5d2a5ab9/pkg/cli/start.go#L425)):*
> ```Go
> 	case <-stopper.ShouldStop():
> 	case sig := <-signalCh:
> 		log.Infof(context.TODO(), "received signal '%s'", sig)
> ```

optional: there are a bunch of context.TODOs here, but there'a context available here. separate commit plz if you decide to do it

---

*[pkg/server/node.go, line 568 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pCe3b7pC7KOu-FrRd:-K_pKgRBKFf33qJ-pqoW:bwumq4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/9525b97d32b20d802aed21e2994c21b6b9e0ee3a/pkg/server/node.go#L568)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I thought so too, but for some reason the server is getting stuck in a mux Accept call even though the mux should have already been closed - https://github.com/cockroachdb/cockroach/blob/master/pkg/server/server.go#L505

I'll dig more into why
</blockquote></details>

and that has to do with returning an error? Not sure I follow.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743)*

**Comment by a-robinson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/cli/start.go, line 336 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pCundE4rnzD2klnrr:-K_pja21QQTWRPM1TJAX:baotv64) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbbc23c137385ef35e1f5209ab5e4d3910c2e61b/pkg/cli/start.go#L336)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I don't think the indentation is that bad, and regarding the channel send - you could nil check on the receiving end?
</blockquote></details>

Doing a nil check on the other end complicates the code since it's part of a select along with the stopper and signal channel. I'm going to leave this as is unless you feel strongly.

---

*[pkg/cli/start.go, line 357 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pDdE00ORaZihNcchV:-K_pjx_AesxQ-cOeLgtx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbbc23c137385ef35e1f5209ab5e4d3910c2e61b/pkg/cli/start.go#L357)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: i'd write
```
draining := serverStatusMu.draining
serverStatusMu.Unlock()
if draining {
...
```
</blockquote></details>

Done.

---

*[pkg/cli/start.go, line 425 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pKMkrN3Hn8k-7gv2y:-K_pmUZdSmRRoMaMvvre:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/58e58ad7fa5efcc53a60cfd79617226d5d2a5ab9/pkg/cli/start.go#L425)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

optional: there are a bunch of context.TODOs here, but there'a context available here. separate commit plz if you decide to do it
</blockquote></details>

Done.

---

*[pkg/server/node.go, line 568 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pCe3b7pC7KOu-FrRd:-K_piyBszKT61GXAuWvE:b-tz6suf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9525b97d32b20d802aed21e2994c21b6b9e0ee3a/pkg/server/node.go#L568)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

and that has to do with returning an error? Not sure I follow.
</blockquote></details>

Mostly unrelated. It's just that returning an error from here allowed us to continue with graceful shutdown, whereas not returning an error would cause a log.Fatal due to failure to allocate a nodeID. The continued graceful shutdown wasn't working, though, because the particular RunWorker call I linked to isn't stopping. https://github.com/cockroachdb/cmux/pull/7 fixes it such that the server completes its shutdown.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cli/start.go, line 336 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pCundE4rnzD2klnrr:-K_pp7yXhHTgRVHBTv4a:b-xa1nz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbbc23c137385ef35e1f5209ab5e4d3910c2e61b/pkg/cli/start.go#L336)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Doing a nil check on the other end complicates the code since it's part of a select along with the stopper and signal channel. I'm going to leave this as is unless you feel strongly.
</blockquote></details>

Oh, I see. Well, I still think I'd do the inner function and nil check before sending, but I guess I don't feel strongly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743)*

**Comment by a-robinson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cli/start.go, line 336 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_pCundE4rnzD2klnrr:-K_q0IAd1qKp8ouQJxvT:bhb09cf) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbbc23c137385ef35e1f5209ab5e4d3910c2e61b/pkg/cli/start.go#L336)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Oh, I see. Well, I still think I'd do the inner function and nil check before sending, but I guess I don't feel strongly.
</blockquote></details>

Eh, sure, I'll do it. Changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743)*

**Comment by knz** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/cli/start.go, line 333 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_s5WXuGR2h_oKRVf56:-K_s5WXvZDltSLAs2QOI:b-51xwxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f191ebcf0fd301ea509680052c43a09c556f06f4/pkg/cli/start.go#L333)):*
> ```Go
> 	var serverStatusMu struct {
> 		syncutil.Mutex
> 		created, draining bool
> ```

Document these two: which code can write to them, in which order, under which conditions, why it's needed, etc.

---

*[pkg/cli/start.go, line 411 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_s5uKXXw1PNaicEMk4:-K_s5uKXXw1PNaicEMk5:b9jlguw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f191ebcf0fd301ea509680052c43a09c556f06f4/pkg/cli/start.go#L411)):*
> ```Go
> 	signalCh := make(chan os.Signal, 1)
> 	signal.Notify(signalCh, os.Interrupt)
> 	signal.Notify(signalCh, syscall.SIGTERM, syscall.SIGQUIT)
> ```

Spencer's TODO here has to do with the fact that `syscall.SIGTERM` and `syscall.SIGQUIT` are unixisms, and if we wanted to build this code on non-unix platforms this line has to go behind a build tag (Whereas `os.Interrupt` above hopefully is more portable).
(I had asked)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743)*

**Comment by a-robinson** [comment]
Added a new commit that pulls in https://github.com/cockroachdb/cmux/pull/7 to complete the job. Without it, we get hung up in the cmux Accept method, as described in that PR.

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/cli/start.go, line 333 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_s5WXuGR2h_oKRVf56:-Ka0bzYpUUmTJZ_hzxHe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f191ebcf0fd301ea509680052c43a09c556f06f4/pkg/cli/start.go#L333)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Document these two: which code can write to them, in which order, under which conditions, why it's needed, etc.
</blockquote></details>

Done.

---

*[pkg/cli/start.go, line 411 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-K_s5uKXXw1PNaicEMk4:-Ka0_tDmJ45faIRz175x:b-h0n0ev) ([raw file](https://github.com/cockroachdb/cockroach/blob/f191ebcf0fd301ea509680052c43a09c556f06f4/pkg/cli/start.go#L411)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Spencer's TODO here has to do with the fact that `syscall.SIGTERM` and `syscall.SIGQUIT` are unixisms, and if we wanted to build this code on non-unix platforms this line has to go behind a build tag (Whereas `os.Interrupt` above hopefully is more portable).
(I had asked)
</blockquote></details>

Ah, thanks. Re-added the TODO with your clarification.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-:-Ka0c0L43qhx2d0UBpct:bqht2o9)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r9, 1 of 1 files at r10.
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-:-Ka1hOV58lp2-gb5jEsx:bnfp4nl)*

**Comment by knz** [comment]
Reviewed 1 of 1 files at r12.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743)*

**Comment by a-robinson** [comment]
Reworked the cmux code in server.Start as discussed offline with @tamird.

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r13, 1 of 1 files at r14, 1 of 1 files at r15, 1 of 1 files at r16, 1 of 1 files at r17.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-:-Ka8wMyESNVitGYr4EEL:bnfp4nl)*

**Comment by a-robinson** [comment]
@knz I had to make a minor change to test_missing_log_output.tcl to get it passing when run as part of the `TestDockerCLI` acceptance test. I don't think the tweak violates the spirit of the test, but you'd know better than me.

**Comment by a-robinson** [comment]
@knz these TestDockerCLI interactive tests are driving me mad. Even after disabling the bad logging mentioned in #12853, they're only failing on TeamCity and only with propEvalKv enabled, but the output doesn't make any sense. The [latest run](https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&buildTypeId=Cockroach_UnitTests_AcceptanceProposerEvaluatedKv&buildId=115326#_) is failing because the input `^Cecho marker; /cockroach/cockroach start --alsologtostderr=FATAL\r\n\r\n` is somehow losing the "e" in "echo", leading to "bash: cho: command not found" errors...

Any recommendations?

**Comment by knz** [comment]
Yes the problem is that Bash has a bug and will silently swallow the first character of input that follows a Ctrl+C entered on its prompt if it is entered too soon after the Ctrl+C.
I am preparing a fix to this. Will let you know.

**Comment by a-robinson** [comment]
I'm very glad that your bash knowledge and/or googling skills are better than mine. Thank you @knz!

**Comment by knz** [comment]
IIRC this is a misfeature (documented limitation) in libreadline that has to do with compatibility with 30 year old terminals.

**Comment by knz** [comment]
Reviewed 1 of 4 files at r13, 1 of 1 files at r19, 1 of 1 files at r20, 1 of 2 files at r21, 1 of 1 files at r22.
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/cli/start.go, line 259 at r23](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-KaMfmFWqw2L9nVViiGv:-KaMfmFXc7YZnY3vulIw:b-udwl4) ([raw file](https://github.com/cockroachdb/cockroach/blob/00f3ef523a4204676b457753411087011dd92266/pkg/cli/start.go#L259)):*
> ```Go
> 	}
> 
> 	tracer := tracing.NewTracer()
> ```

I don't understand why you moved the signal channel creation to below. It seems to me that given your changes to gossiping and using a goroutine below, blocking the signals starting here should be fine. Why is this not true?

---

*[pkg/cli/start.go, line 414 at r23](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-KaMeSC93CtjLWAdPPXg:-KaMeSC93CtjLWAdPPXh:b-1zu9wf) ([raw file](https://github.com/cockroachdb/cockroach/blob/00f3ef523a4204676b457753411087011dd92266/pkg/cli/start.go#L414)):*
> ```Go
> 
> 	signalCh := make(chan os.Signal, 1)
> 	signal.Notify(signalCh, os.Interrupt)
> ```

Please create and prime the signal channel at least just before starting the goroutine above, so as to prevent a case where Go decides to run it eagerly and a signal during the server initialization is not handled properly.

---

*[pkg/cli/interactive_tests/test_missing_log_output.tcl, line 35 at r21](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-KaMfJN4G6pp9AL_AVlB:-KaMfJN51NV2HKnAIlKZ:b4vkzfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2c1f97552fd17447f8bb1416da1651912ec1634/pkg/cli/interactive_tests/test_missing_log_output.tcl#L35)):*
> ```Tcl
> # Check that --alsologtostderr can override the threshold
> # regardless of what --logtostderr has set.
> send "echo marker; $argv start --alsologtostderr=FATAL\r"
> ```

Why change this? Is still expected after #12882? I think if there is a server start-up error we'll want to know it during testing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743)*

**Comment by a-robinson** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/cli/start.go, line 259 at r23](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-KaMfmFWqw2L9nVViiGv:-KaNnRkA4QGh1brm3q-f:b-z6qsmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/00f3ef523a4204676b457753411087011dd92266/pkg/cli/start.go#L259)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't understand why you moved the signal channel creation to below. It seems to me that given your changes to gossiping and using a goroutine below, blocking the signals starting here should be fine. Why is this not true?
</blockquote></details>

It is true. IIRC I moved it down mostly for readability.

---

*[pkg/cli/start.go, line 414 at r23](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-KaMeSC93CtjLWAdPPXg:-KaNnQ6CxwM2UPj60fWa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00f3ef523a4204676b457753411087011dd92266/pkg/cli/start.go#L414)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please create and prime the signal channel at least just before starting the goroutine above, so as to prevent a case where Go decides to run it eagerly and a signal during the server initialization is not handled properly.
</blockquote></details>

Done.

---

*[pkg/cli/interactive_tests/test_missing_log_output.tcl, line 35 at r21](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-KaMfJN4G6pp9AL_AVlB:-KaNnjIBOqI2eap51Wpf:b-zfggyp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2c1f97552fd17447f8bb1416da1651912ec1634/pkg/cli/interactive_tests/test_missing_log_output.tcl#L35)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Why change this? Is still expected after #12882? I think if there is a server start-up error we'll want to know it during testing.
</blockquote></details>

I was seeing some (non-propEvalKV) error messages from server startup squeezing in before the stdout message, but I'm not seeing them anymore. Changed back.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r24, 1 of 1 files at r25, 1 of 1 files at r26, 1 of 1 files at r28.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-:-KaO3j2dCDSLYrBqmom_:bnfp4nl)*

**Comment by knz** [comment]
Regarding the stray error messages, I now see what you mean:
```
purgatory: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
```

I know how to fix this, I'll submit a PR shortly.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12743#-:-KaO3yxQK54el4WzrKk-:b-5i3bgo)*

**Pull request merged**
