### PR TITLE
storage: add MVCCStats.SeparatedIntentCount

### PR DESCRIPTION
**Pull request by sumeerbhola**
This is informational, plus can be used for the future
long running migration to rewrite interleaved intents
to separated intents. Ranges with
IntentCount==SeparatedIntentCount can avoid scanning
the engine to find interleaved intents, which will
be the common case.

Informs #41720

Release note: None

### CODE REVIEW

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59600#-:-MSjAKuU7ZRmwG1yWJ1Z:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten, @petermattis, and @sumeerbhola)

___
*[pkg/storage/enginepb/mvcc.proto, line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59600#-MSjA7Bk87qhmbFKkgOb:-MSjA7Bk87qhmbFKkgOc:b-5n0upr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8b3ed7aa7c9f3456e8d58013c427109e4b60396/pkg/storage/enginepb/mvcc.proto#L203)):*
> ```protobuf
>   // intents, so mixed-version clusters with nodes preceding this knowledge
>   // will always have a 0 value for this field.
>   optional sfixed64 separated_intent_count = 16 [(gogoproto.nullable) = false];
> ```

Nit / feel free to ignore: I see the point of putting this next to `intent_count` but the convention seems to be ordering all of these by the proto number. It seems better to just put it on the bottom then?

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59600#-:-MSmel7HBABT22NpDfpU:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal, @nvanbenschoten, and @petermattis)

___
*[pkg/storage/enginepb/mvcc.proto, line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59600#-MSjA7Bk87qhmbFKkgOb:-MSmTdGBEmqoLvhk3yvQ:bg0g7ku) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8b3ed7aa7c9f3456e8d58013c427109e4b60396/pkg/storage/enginepb/mvcc.proto#L203)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Nit / feel free to ignore: I see the point of putting this next to `intent_count` but the convention seems to be ordering all of these by the proto number. It seems better to just put it on the bottom then?
</blockquote></details>

I did it for readability here and in the generated golang struct -- gogoproto puts the `SeparatedIntentCount` field in the struct based on the text ordering here and not the tag number.
Happy to change to whatever you all agree upon. @nvanbenschoten do you have an opinion?

**Review by nvb — APPROVED** [review]
:lgtm: 

Do we need to make updates in `pkg/kv/kvserver/metrics.go` and `pkg/kv/kvserver/stateloader/stateloader.go`? I searched for other uses of the `IntentCount` field and found those.

> Reviewed 17 of 19 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59600#-:-MSnl4oH1BLAShs3Pe8j:b-2h2lko)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/enginepb/mvcc.proto, line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59600#-MSjA7Bk87qhmbFKkgOb:-MSnk2eCAXiMF8GZiObr:bqk9mtd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8b3ed7aa7c9f3456e8d58013c427109e4b60396/pkg/storage/enginepb/mvcc.proto#L203)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I did it for readability here and in the generated golang struct -- gogoproto puts the `SeparatedIntentCount` field in the struct based on the text ordering here and not the tag number.
Happy to change to whatever you all agree upon. @nvanbenschoten do you have an opinion?  
</blockquote></details>

I think I prefer the ordering you have here. Better to have the fields ordered in a readable way for every future reader than to have them ordered by tag number for the single person that adds the next field.

**Review by sumeerbhola — COMMENTED** [review]
The use of `IntentCount` in `stateloader.go` is for the `MVCCStatsLegacyRepresentation` which we don't want `SeparatedIntentCount` in.
Regarding metrics, I figured this isn't very useful for a casual examination of the system, and soon all intents will be separated intents. The `SeparatedIntentCount` is mostly for internal use, and for deep examination of the system. Can one can get hold of `MVCCStats` via the admin console for some desired range?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59600#-:-MTCezT24d-26irQYJY-:b-ekfp08)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @itsbilal, @nvanbenschoten, @petermattis, and @sumeerbhola)

**Comment by sumeerbhola** [comment]
The TestMultiplePrimaryKeyChanges failure in pkg/sql seems like a flake

**Pull request merged**
