### PR TITLE
server, ui: Move the diagnostics endpoint from admin to status

### PR DESCRIPTION
**Pull request by BramGruneir**
This move allows us to request the diagnostics from any node, not just the node
receiving the request.

Release note (admin ui change): The endpoint for diagnostic reports has been
moved from `/_admin/v1/diagnostics` to `/_status/diagnostics/{node_id}` and
you can now request the report from any node.

### CODE REVIEW

**Comment by BramGruneir** [comment]
This is mostly just code movement and a good about of testing to make sure it all works as advertised.

**Review by dt — APPROVED** [review]

**Comment by BramGruneir** [comment]
I updated this response proto to return the report directly.  Please take a quick look, but this enables us to grab the proto directly via curl and pass it to the reg cluster.  Extremely useful for testing.
Also fixed the form/from in the commit title.

**Review by vilterp — APPROVED** [review]
Is there some reason these two changes are in the same PR and commit? Seems like they could be independent; just wondering if I missed something.

**Comment by BramGruneir** [comment]
Since we're changing the endpoint, it's best to make both changes at once.
So there is never a potential commit where the endpoint returns a different
result.

I can amend the commit message if you think that's necessary.

The secondary use case for this endpoint is to be able to curl a proto to
be fed directly into the reg cluster.

**Comment by vilterp** [comment]
Ah, I see. You can amend the message if you want; not a big deal.

**Comment by BramGruneir** [comment]
bors +r

**Pull request merged**
