### PR TITLE
kv/kvserver: use fixed proposal timestamp in TestProposalOverhead

### LINKED ISSUE #48473: kv/kvserver: TestProposalOverhead failed
[(kv/kvserver).TestProposalOverhead failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1923272&tab=buildLog) on [master@80fdcc7277927c3dbf319b6e6eafa0e90a43e3ed](https://github.com/cockroachdb/cockroach/commits/80fdcc7277927c3dbf319b6e6eafa0e90a43e3ed):

```
=== RUN   TestProposalOverhead
I200506 06:51:50.672511 25645 util/stop/stopper.go:539  quiescing
--- FAIL: TestProposalOverhead (0.01s)
    replica_test.go:6753: storagepb.RaftCommand{
            ProposerLeaseSequence:   1,
            DeprecatedProposerLease: (*roachpb.Lease)(nil),
            MaxLeaseIndex:           0x0,
            ReplicatedEvalResult:    storagepb.ReplicatedEvalResult{
                State:                (*storagepb.ReplicaState)(nil),
                Split:                (*storagepb.Split)(nil),
                Merge:                (*storagepb.Merge)(nil),
                ComputeChecksum:      (*storagepb.ComputeChecksum)(nil),
                IsLeaseRequest:       false,
                Timestamp:            hlc.Timestamp{WallTime:1588747910671904812, Logical:1},
                DeprecatedDelta:      (*enginepb.MVCCStats)(nil),
                Delta:                enginepb.MVCCStatsDelta{ContainsEstimates:0, LastUpdateNanos:1588747910671904812, IntentAge:0, GCBytesAge:0, LiveBytes:20, LiveCount:1, KeyBytes:14, KeyCount:1, ValBytes:6, ValCount:1, IntentBytes:0, IntentCount:0, SysBytes:0, SysCount:0},
                ChangeReplicas:       (*storagepb.ChangeReplicas)(nil),
                RaftLogDelta:         0,
                AddSSTable:           (*storagepb.ReplicatedEvalResult_AddSSTable)(nil),
                SuggestedCompactions: nil,
                PrevLeaseProposal:    (*hlc.Timestamp)(nil),
            },
            WriteBatch:   (*storagepb.WriteBatch)(nil),
            LogicalOpLog: (*storagepb.LogicalOpLog)(nil),
            TraceData:    {},
        }
    replica_test.go:6777: expected overhead of 42, but found 44

```

<details><summary>More</summary><p>
Parameters:

- TAGS=
- GOFLAGS=-parallel=4

```
make stressrace TESTS=TestProposalOverhead PKG=./pkg/kv/kvserver TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestProposalOverhead.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by nvb**
Fixes #48473.

Use a realistic timestamp with no logical portion to guarantee that the
timestamp in the proposal has a deterministic size. The test was flaky
because the proposal would occasionally be given a timestamp with a
logical tick of 1 (as we see in #48473), which would add two bytes to
the proposal size (proto field tag + varint size).

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
I hit this last week in  https://github.com/cockroachdb/cockroach/blob/8f08c4f79cf919e791058ee5a512cf220962aa0d/pkg/kv/kvserver/client_replica_test.go#L3149 and ended up moving the test in part to make the write go to a user range. 

In that PR I still hit this flake using a regular clock under a bunch of stress and ended up clearing out the logical bits underneath the overhead calculation. 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48667#-:-M7-pTT_8XIrCs6mUEOY:b-4qtuk9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis)

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48667#-:-M70DLe3AoWBmi9E5LGr:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @petermattis)

**Comment by nvanbenschoten** [comment]
TFTRs!

bors r+

**Comment by nvanbenschoten** [comment]
Flaked on https://github.com/cockroachdb/cockroach/issues/48413.

bors r+

**Pull request merged**
