### PR TITLE
gssapiccl: switch to pure-go GSSAPI client

### PR DESCRIPTION
**Pull request by dt**
This switches from calling the c gssapi functions in krb5 to using
a pure-go implementaiton from github.com/jcmturner/gokrb5. This was
previously considered but not pursued due to a lack of confidence in
pure-go library, but it has a couple more years of maturity now and
with rocksdb and c protobuf no longer being linked in our binaries,
krb5 becomes one of our larger c-deps making its elimination more
appealing.

Release note (build change): GSS / Kerberos support is now implemented entirely in Go instead of using libkrb5.

### CODE REVIEW

**Comment by dt** [comment]
I know we've looked at this before and didn't do it then, but I spent a flex friday trying to see how much of our c-deps build I could eliminate so figured I'd see what this would look like if we wanted to pursue it now to see if we like it any more now, e.g. maybe some of the inputs to the math around that decision have changed since we last looked at it. Specifically, we no longer build and link the hefty rocksdb/protobuf c-deps, so krb5 now becomes one of the bigger c-deps builds remaining, while gokrb5 has had a couple more years to mature and build confidence in the meantime.

**Review by petermattis — COMMENTED** [review]
This is a surprisingly small change. Will definitely need @bdarnell to get on board with it, though. Possibly @aaron-crl too.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66935#-:-MdHvQp5Em8xLq0HnnOR:b-db5moz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @bdarnell, and @dt)

___
*[go.mod, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66935#-MdHuhAM-QHAunOgIzZp:-MdHuhAN9rDjkXlscJjc:b-i9o6x8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9deceae8b27ec4da87bfdce6c4f2ddad47198c9d/go.mod#L99)):*
> ```XML
> 	github.com/jackc/pgx/v4 v4.6.0
> 	github.com/jaegertracing/jaeger v1.18.1
> 	github.com/jcmturner/gofork v1.0.0
> ```

I believe this was a big part of the concern with using `jcmturner/gokrb5`. This package is a fork of some of the Go stdlib packages. @bdarnell was quite concerned about this if I recall correctly.
___
*[pkg/ccl/gssapiccl/gssapi.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66935#-MdHvCy-2c7biJUVR7QM:-MdHvCy-2c7biJUVR7QN:buzfbzk) ([raw file](https://github.com/cockroachdb/cockroach/blob/9deceae8b27ec4da87bfdce6c4f2ddad47198c9d/pkg/ccl/gssapiccl/gssapi.go#L46)):*
> ```Go
> ) (security.UserAuthHook, error) {
> 	return func(ctx context.Context, requestedUser security.SQLUsername, clientConnection bool) (func(), error) {
> 		ktPath := os.Getenv("KRB5_KTNAME")
> ```

I'm not familiar with our krb5 testing. What level of test coverage do we have? One way to test this is to put errors in various paths below and see if they cause test failures.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66935)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @bdarnell, @dt, and @petermattis)

___
*[pkg/ccl/gssapiccl/gssapi.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66935#-MdHvCy-2c7biJUVR7QM:-MdHx6ndEqyxQFEus90F:big5snv) ([raw file](https://github.com/cockroachdb/cockroach/blob/9deceae8b27ec4da87bfdce6c4f2ddad47198c9d/pkg/ccl/gssapiccl/gssapi.go#L46)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm not familiar with our krb5 testing. What level of test coverage do we have? One way to test this is to put errors in various paths below and see if they cause test failures.
</blockquote></details>

we test this in TestComposeGSS(Python), in the docker-based acceptance tests. That test did indeed fail on some of the CI runs of earlier revisions of this PR, because gokrb5 returns `DisplayName` and `Domain` separately while `gss_display_name` returns "user@domain", before I switched the code that was splitting that string. https://github.com/cockroachdb/cockroach/blob/master/pkg/acceptance/compose/gss/psql/gss_test.go

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66935)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @bdarnell, and @petermattis)

___
*[go.mod, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66935#-MdHuhAM-QHAunOgIzZp:-MdIfEkpEMtTTC_-qz0v:b-2wloz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9deceae8b27ec4da87bfdce6c4f2ddad47198c9d/go.mod#L99)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I believe this was a big part of the concern with using `jcmturner/gokrb5`. This package is a fork of some of the Go stdlib packages. @bdarnell was quite concerned about this if I recall correctly.
</blockquote></details>

Yeah, I took a brief look at the patches in the two forked packages. The added marshaling formats in asn.1 looked like they could be upstreamed (indeed, one has been, one has a PR open but inactive for years). The pbkdf2 switch, from int to int64, seems less irrelevant to us (since we don't support 32b).

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66935)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @dt, and @petermattis)

___
*[go.mod, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66935#-MdHuhAM-QHAunOgIzZp:-MdJ5RjR13vMWsduiduJ:b-rzz6rj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9deceae8b27ec4da87bfdce6c4f2ddad47198c9d/go.mod#L99)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Yeah, I took a brief look at the patches in the two forked packages. The added marshaling formats in asn.1 looked like they could be upstreamed (indeed, one has been, one has a PR open but inactive for years). The pbkdf2 switch, from int to int64, seems less irrelevant to us (since we don't support 32b).
</blockquote></details>

There are two distinct concerns here: one is about the safety of the additions, and the other is that any fixes to the underlying libraries get picked up in a timely manner. The gofork package hasn't had a substantial update since 2017, while there have been 17 commits to the asn1 package since then. I have not tried to evaluate how important those commits are, but it doesn't seem great. 
___
*[pkg/ccl/gssapiccl/gssapi.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66935#-MdJ51PT5zmhBQpRGn70:-MdJ51PT5zmhBQpRGn71:b-bbhd0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/9deceae8b27ec4da87bfdce6c4f2ddad47198c9d/pkg/ccl/gssapiccl/gssapi.go#L25)):*
> ```Go
> 	"gopkg.in/jcmturner/goidentity.v3"
> 	"gopkg.in/jcmturner/gokrb5.v7/keytab"
> 	"gopkg.in/jcmturner/gokrb5.v8/gssapi"
> ```

Both v7 and v8 at the same time? 
___
*[pkg/ccl/gssapiccl/gssapi.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66935#-MdHvCy-2c7biJUVR7QM:-MdJ70mx4UrSIwWz3mwH:bw6l835) ([raw file](https://github.com/cockroachdb/cockroach/blob/9deceae8b27ec4da87bfdce6c4f2ddad47198c9d/pkg/ccl/gssapiccl/gssapi.go#L46)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

we test this in TestComposeGSS(Python), in the docker-based acceptance tests. That test did indeed fail on some of the CI runs of earlier revisions of this PR, because gokrb5 returns `DisplayName` and `Domain` separately while `gss_display_name` returns "user@domain", before I switched the code that was splitting that string. https://github.com/cockroachdb/cockroach/blob/master/pkg/acceptance/compose/gss/psql/gss_test.go
</blockquote></details>

My biggest concern is that we're testing with kdc because it's opensource and easy to automate, but AIUI every customer using this functionality is using it with active directory, which we only test manually. If we want to make this change we should be sure to test with AD manually (and take advantage of customer success's knowledge of customer setups).

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66935)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @dt, and @petermattis)

___
*[go.mod, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66935#-MdHuhAM-QHAunOgIzZp:-MdJL8FJ9e_DpIIx7vVC:bwi9vz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/9deceae8b27ec4da87bfdce6c4f2ddad47198c9d/go.mod#L99)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

There are two distinct concerns here: one is about the safety of the additions, and the other is that any fixes to the underlying libraries get picked up in a timely manner. The gofork package hasn't had a substantial update since 2017, while there have been 17 commits to the asn1 package since then. I have not tried to evaluate how important those commits are, but it doesn't seem great. 
</blockquote></details>

I wonder if there's anything we could do to try to get the changes that motived the fork upstream, e.g. https://github.com/golang/go/pull/27579 has been quiet for years.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66935)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @dt, and @petermattis)

___
*[go.mod, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66935#-MdHuhAM-QHAunOgIzZp:-MdJLXfOAXKlpNZgQyU9:b-2b1byt) ([raw file](https://github.com/cockroachdb/cockroach/blob/9deceae8b27ec4da87bfdce6c4f2ddad47198c9d/go.mod#L99)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I wonder if there's anything we could do to try to get the changes that motived the fork upstream, e.g. https://github.com/golang/go/pull/27579 has been quiet for years.
</blockquote></details>

If we had a reasonable expectation that it would be short-lived, I'd happily make another fork and rebase the patches until everything was upstream and we could get off the fork, but owning a fork long-term isn't as appealing (even though it would make keeping up with upstream easier for us to own).

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66935)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @dt, and @petermattis)

___
*[go.mod, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66935#-MdHuhAM-QHAunOgIzZp:-MdNUg6a2RBWYBQICOAT:bjfm0fx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9deceae8b27ec4da87bfdce6c4f2ddad47198c9d/go.mod#L99)):*
> If we had a reasonable expectation that it would be short-lived, I'd happily make another fork and rebase the patches

That's also scary since our fork would diverge from what's been tested by third parties with gokrb5. Hopefully it's not an issue, but it's a potential risk. In the end, we're trusting jcmturner (and anyone else who may be sharing in the maintenance of these packages) to keep on top of bugs in both gofork and gokrb5 itself. If we feel like we need to make our own version of gofork to be safe, that's a bad sign for adopting other packages by the same maintainers.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66935)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @dt, and @petermattis)

___
*[go.mod, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66935#-MdHuhAM-QHAunOgIzZp:-MdPCMQD6--k0n4z7Qf2:b-6fogtz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9deceae8b27ec4da87bfdce6c4f2ddad47198c9d/go.mod#L99)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

> If we had a reasonable expectation that it would be short-lived, I'd happily make another fork and rebase the patches

That's also scary since our fork would diverge from what's been tested by third parties with gokrb5. Hopefully it's not an issue, but it's a potential risk. In the end, we're trusting jcmturner (and anyone else who may be sharing in the maintenance of these packages) to keep on top of bugs in both gofork and gokrb5 itself. If we feel like we need to make our own version of gofork to be safe, that's a bad sign for adopting other packages by the same maintainers. 
</blockquote></details>

Yeah, good points. So I guess the question is, do we trust it and the maintainer enough to use it as-is?

It seems like at least some other folks are using this library for the last couple years, and it does seem to get somewhat regular bug fixes and improvements, so hopefully that means they're keeping up with required dependency issues.

I'd still feel better about it though if we could get some movement on upstreaming those patches to get off the fork long term.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66935)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @bdarnell, @dt, and @petermattis)

___
*[go.mod, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66935#-MdHuhAM-QHAunOgIzZp:-MdRv_wa6zk3dgkwHXNL:brdgee7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9deceae8b27ec4da87bfdce6c4f2ddad47198c9d/go.mod#L99)):*
> I'd still feel better about it though if we could get some movement on upstreaming those patches to get off the fork long term.

Do you want me to ping the Go folks to see if we can get some movement there? Do you want to ping them?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66935)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @dt, and @petermattis)

___
*[go.mod, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66935#-MdHuhAM-QHAunOgIzZp:-MdS8KJt6j0D5Rwi2NLm:b-z510my) ([raw file](https://github.com/cockroachdb/cockroach/blob/9deceae8b27ec4da87bfdce6c4f2ddad47198c9d/go.mod#L99)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

> I'd still feel better about it though if we could get some movement on upstreaming those patches to get off the fork long term.

Do you want me to ping the Go folks to see if we can get some movement there? Do you want to ping them?
</blockquote></details>

I can go comment on the open asn1 PR, but it looks someone else just did that so a couple months ago without any reaction. 

There's also the other couple patches that don't yet have upstream CLs though. 

Maybe we want to ping the go folks to see if someone on the go side is willing to take a look all 4 issues and either shepherd CLs through for them or suggest gokrb5 pursue alternatives (e.g. the pbkfd2 change, for int->int64, seems unnecessary, since 32b platforms could instead just refuse to do that many iterations and still be compliant with the RFC it seems) to get off the fork.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66935)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @bdarnell, @dt, and @petermattis)

___
*[go.mod, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66935#-MdHuhAM-QHAunOgIzZp:-MdSIuAC71gyntFJdtcj:b-gfj43g) ([raw file](https://github.com/cockroachdb/cockroach/blob/9deceae8b27ec4da87bfdce6c4f2ddad47198c9d/go.mod#L99)):*
> I can go comment on the open asn1 PR, but it looks someone else just did that so a couple months ago without any reaction.
>
> There's also the other couple patches that don't yet have upstream CLs though.

If you write up a message about what would need to be upstreamed, I can send it along and see if we can get some movement. Would you be willing to generate the additional upstream CLs that are necessary?

**Comment by knz** [comment]
@abarganier can you add this to the list of things that would help us motivate a customized go runtime thanks

**Comment by dt** [comment]
@knz what go runtime changes would have helped us here?

**Comment by knz** [comment]
Maybe "runtime" was not the right word. I mean the golang crypto CLs that are not upstreamed yet.

**Comment by dt** [comment]
Ah, yeah, it'd indeed be nice if the asn1 stdlib changes made it upstream so the lib could get off its fork.

Anyway, I closed this for now since in addition to the discomfort with said fork, and the fact that there has been no apparently movement for *years* on the upstream CLs / tickets to resolve it, it _also_ seems like the library maintainer may not be actively monitoring / responding to [filed](https://github.com/jcmturner/gokrb5/issues/444) [issues](https://github.com/jcmturner/gokrb5/issues/424) or submitted [patches](https://github.com/jcmturner/gokrb5/pull/425) currently, which, given they've taken responsibility for maintaining a forked crypto lib, is concerning enough that I think we just don't have enough confidence to proceed here at this time. Hopefully if we just punt for now the library matures a little more and we can make this switch in the future since it is a hefty, annoying to build c-dep.

**Pull request closed without merging**
