### PR TITLE
opt: Cleanup opt packages

### PR DESCRIPTION
**Pull request by andy-kimball**
This PR contains a number of cleanup items in the opt packages that
have been on my list of things to do:

1. Add an Executor test helper class that is shared by various opt
   tests, and contains boiler-plate code to exercise various aspects
   of the optimization process.

2. Make MaxSteps a control property on the Optimizer class rather than
   passing it to the constructor. Most callers don't need to set this,
   and it's one less constructor parameter in that common case.

3. Put MaxSteps in Optimizer rather than factory so that the explorer
   will also have easy access to it. The factory now holds a ref to
   the optimizer.

4. Nuke the opt.Factory interface. I only created it to solve package
   dependency cycles, but those are better solved by putting most test
   code into _test packages (which this PR also does).

5. Move LogicalProps to the main opt package, so that it's co-located
   with PhysicalProps.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm_strong: 

---

Review status: 0 of 36 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/exec/execbuilder/builder_test.go, line 167 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23998#-L7qd59FaaQhoU_ezSai:-L7qd59FaaQhoU_ezSaj:b-n7taau) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaf649a90049b1bfd463fa90690295b159a7ba02/pkg/sql/opt/exec/execbuilder/builder_test.go#L167)):*
> ```Go
> 					defer eng.Close()
> 
> 					executor := testutils.NewExecutor(eng.Catalog(), d.Input)
> ```

Not sure Executor is the best name, it overlaps with the sql executor. Maybe Framework, Harness, Library

---

*[pkg/sql/opt/testutils/executor.go, line 32 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23998#-L7qcMYlNXaOmcJhwc3h:-L7qcMYlNXaOmcJhwc3i:b-yirk1) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaf649a90049b1bfd463fa90690295b159a7ba02/pkg/sql/opt/testutils/executor.go#L32)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/sql/sem/tree"
> 	"github.com/cockroachdb/cockroach/pkg/sql/sqlbase"
> 	"github.com/pmezard/go-difflib/difflib"
> ```

[nit] move this up before the cockroachdb includes (with blank line in-between)

---

*[pkg/sql/opt/testutils/executor.go, line 72 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23998#-L7qcjzr7B9X2_AWJH3v:-L7qcjzr7B9X2_AWJH3w:b-8a7fbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaf649a90049b1bfd463fa90690295b159a7ba02/pkg/sql/opt/testutils/executor.go#L72)):*
> ```Go
> 
> // OptBuild constructs an opt expression tree for the SQL query, with no
> // transformations applied to it. This is a straightforward translation of the
> ```

I wouldn't call it straightforward :)

---

*[pkg/sql/opt/xform/optimizer.go, line 73 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23998#-L7qeNRpLcDKe1L8PkQH:-L7qeNRqyvCWYE6Yv_CN:b-gfz8tt) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaf649a90049b1bfd463fa90690295b159a7ba02/pkg/sql/opt/xform/optimizer.go#L73)):*
> ```Go
> 	lastRuleName RuleName
> 
> 	// MaxSteps, if set, limits the number of normalization and exploration
> ```

[nit] remove "if set", it "conflicts" with "MaxStep is set to OptimizeAll" below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23998#-:-L7qfSGRdrgSLsZllzjT:b-uwkowd)*

**Comment by andy-kimball** [comment]
Review status: 0 of 36 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/exec/execbuilder/builder_test.go, line 167 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23998#-L7qd59FaaQhoU_ezSai:-L7qsAtc5WnMlUlGDzMH:bc6n98t) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaf649a90049b1bfd463fa90690295b159a7ba02/pkg/sql/opt/exec/execbuilder/builder_test.go#L167)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Not sure Executor is the best name, it overlaps with the sql executor. Maybe Framework, Harness, Library
</blockquote></details>

True, I renamed to `OptTester`.

---

*[pkg/sql/opt/testutils/executor.go, line 32 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23998#-L7qcMYlNXaOmcJhwc3h:-L7qsMYu0jTQ4W4DSffz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaf649a90049b1bfd463fa90690295b159a7ba02/pkg/sql/opt/testutils/executor.go#L32)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] move this up before the cockroachdb includes (with blank line in-between)
</blockquote></details>

Done.

---

*[pkg/sql/opt/testutils/executor.go, line 72 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23998#-L7qcjzr7B9X2_AWJH3v:-L7qt52k6rdavm8-ldEC:b-iygg0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaf649a90049b1bfd463fa90690295b159a7ba02/pkg/sql/opt/testutils/executor.go#L72)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I wouldn't call it straightforward :)
</blockquote></details>

Ha true, I tweaked that comment to better reflect reality.

---

*[pkg/sql/opt/xform/optimizer.go, line 73 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23998#-L7qeNRpLcDKe1L8PkQH:-L7qtGBk5phNTTqD1T6C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaf649a90049b1bfd463fa90690295b159a7ba02/pkg/sql/opt/xform/optimizer.go#L73)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] remove "if set", it "conflicts" with "MaxStep is set to OptimizeAll" below.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23998)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Reviewed 30 of 43 files at r1, 12 of 16 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23998#-:-L7qu4795w1G9ZyAxLhe:bnfp4nl)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/exec/execbuilder/builder_test.go, line 167 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23998#-L7qd59FaaQhoU_ezSai:-L7tKjJQ6U05uWBaoilt:b-s3rbys) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaf649a90049b1bfd463fa90690295b159a7ba02/pkg/sql/opt/exec/execbuilder/builder_test.go#L167)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

True, I renamed to `OptTester`.
</blockquote></details>

Hmm, did you? Or is that in a following PR?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23998)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/exec/execbuilder/builder_test.go, line 167 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23998#-L7qd59FaaQhoU_ezSai:-L7tLnG27O4JTIwqsY_l:b-8ccyng) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaf649a90049b1bfd463fa90690295b159a7ba02/pkg/sql/opt/exec/execbuilder/builder_test.go#L167)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Hmm, did you? Or is that in a following PR?
</blockquote></details>

Oh,  I see, you renamed the type but not `NewExecutor`  (and the `executor` var names)..

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23998)*

**Comment by andy-kimball** [comment]
*[pkg/sql/opt/exec/execbuilder/builder_test.go, line 167 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23998#-L7qd59FaaQhoU_ezSai:-L7tTaj16YhmVvn-5Nkw:b-xmo3k6) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaf649a90049b1bfd463fa90690295b159a7ba02/pkg/sql/opt/exec/execbuilder/builder_test.go#L167)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Oh,  I see, you renamed the type but not `NewExecutor`  (and the `executor` var names)..
</blockquote></details>

Whoops, I'll fix in next PR.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23998)*

**Pull request merged**
