### PR TITLE
Changing NewInMem to have storeSize and setting cacheSize to 0

### LINKED ISSUE #16750: server: In-memory `size` attribute sizes cache, not store
The store specification for an in-memory store has a `size` parameter, which is supposed to set the size of the store. However, [when we use this value](https://github.com/cockroachdb/cockroach/blob/e164c2e16f3770bc49835374bd1aee9e35805d4b/pkg/server/config.go#L448), [it is passed as the cache size](https://github.com/cockroachdb/cockroach/blob/e164c2e16f3770bc49835374bd1aee9e35805d4b/pkg/storage/engine/in_mem.go#L29-L35), not the store size (the store is always hard-coded to 512MB). This is low-priority since in-memory stores are test-only, but it would still be nice to clean this up.

### PR DESCRIPTION
**Pull request by soniabhishek**
fixes #16750
what else need to be done in this PR?

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

I think this is all we need, but we're having some issues with our CI builds right now. When #16879 is merged you'll need to rebase on top of it. 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16876#-:-KoNQpHHp_aFMJibzmsV:bug28ul)*

**Comment by tschottdorf** [comment]
Friendly ping.

**Comment by soniabhishek** [comment]
Oh sorry, I forgot! Is this still open and can I merge this @tschottdorf

**Comment by tschottdorf** [comment]
Fixed up the commit for you. Thanks @soniabhishek and sorry about letting this sit for so long.

bors r+

**Comment by tschottdorf** [comment]
Wow, this really blew up CI. Guess it needs more love.

**Comment by soniabhishek** [comment]
OOPS! a lot of failures, what might have been the issue @tschottdorf interested in fixing this.

**Comment by tschottdorf** [comment]
I'm not sure. I would've said that changing the cache size or applying the store size some tests pass is messing things up, but somehow the test passed under `race` (which is usually where things that break under regular test break as well).

Does `make test` pass locally for you?

**Comment by soniabhishek** [comment]
Will have to check again! (Long time)

**Pull request closed without merging**
