### PR TITLE
sql,roachpb: improve BatchResponse.combine

### LINKED ISSUE #33200: kv: too much time spent in ScanResponse.combine
While testing a scan over a table with large values, I noticed that a very large portion of CPU time is spent in `ScanResponse.combine`, concatenating byte slices of multiple range's scan responses.

This is totally inefficient and silly. We should improve this situation by "combining" the two byte slices into a slice of slices, rather than appending the slices together.

This might improve scan speed significantly.

image

### PR DESCRIPTION
**Pull request by jordanlewis**
Closes #33200.

Instead of concatenating the two batch response slices, which is
expensive for large scans, append the slices to a slice of slices. The
kv batch fetcher is taught to read those one by one.

This improves large cross-range scans by a factor of 50% in my testing.

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
Nice find!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33218#-:-LTyonhn2ALXw4gbR3bP:bdkgtm2)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/roachpb/api.proto, line 369 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33218#-LTyoWaW0rp__x1C6UeP:-LTyoWaW0rp__x1C6UeQ:bmwzi4u) ([raw file](https://github.com/cockroachdb/cockroach/blob/302d96096f5d58dbb5b9c1e219f4f2ce5799ebd9/pkg/roachpb/api.proto#L369)):*
> ```protobuf
> message ScanResponse {
>   // Don't generate a typedecl, so we can add a slice of batch_responses.
>   option (gogoproto.typedecl) = false;
> ```

This is neat, but fragile. What happens when we add another field to this proto? Is there another way to achieve this?

**Comment by jordanlewis** [comment]
> This is neat, but fragile. What happens when we add another field to this proto? Is there another way to achieve this?

When another field is added to the proto, the generated code will not compile until the corresponding field is correctly added to the struct. So, it is safe. Perhaps unideal though.

One alternative is to add an empty slice field to the proto itself, and document that it is only for combining and should not be filled in. But this seems possibly worse.

I think the real better way would be to drop the whole combinable interface idea and have clients interact with non-merged batch results. Preserving the illusion that batches came from a single range is a lot of work and computationally expensive. But, that's clearly beyond the scope of this PR.

**Review by andreimatei — COMMENTED** [review]
You already know my response to this; I'm calling your bluff :)
Is there a way to hack into the serialization of the proto with some more magic? If not, this is a bridge too far for me for the DistSender interface and so I think you should change it. The speedups sound very impressive, but that's all the more reason to change the DistSender. I can be overruled, though.
Another hack that I might find more palatable is to return multiple ScanResponses in a BatchResponse if the request is flagged somehow. It'd be just for requests with a single scan - so you don't need to generally "have clients interact with non-merged results".

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33218#-:-LTzXkWuEYXC2RYvsp0b:bga6q0z)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by jordanlewis** [comment]
What do you mean by "Is there a way to hack into the serialization of the proto with some more magic"? What would you want to hack exactly?

I like your flag idea, kinda, but I don't really see what's wrong with my idea. Protos are just code, we can change them if we want - and the thing I've done hardly has anything to do with the dist sender interface, does it? Are you worried about mucking up the interface for another user - I'd ask, what other user?

**Review by nvb — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33218)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/roachpb/api.proto, line 382 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33218#-LTzhA--Bo637yocOUz1:-LTzhA-06xBRfDGNsHol:bejifb) ([raw file](https://github.com/cockroachdb/cockroach/blob/302d96096f5d58dbb5b9c1e219f4f2ce5799ebd9/pkg/roachpb/api.proto#L382)):*
> ```protobuf
>   // are num_keys pairs, as defined by the ResponseHeader. If set, rows will not
>   // be set and vice versa.
>   bytes batch_response = 4;
> ```

What if we just made this field `repeated`? Doing so would be backwards compatible and we could have a server-side contract to never have more than a single element. `combine` could then simply create a slice of byte slices instead of merging the bytes directly.

**Comment by jordanlewis** [comment]
Good point, I forgot that you can make fields repeated without removing backward compatibility.

**Review by nvb — APPROVED** [review]
:lgtm: but I would love to see the results of a few benchmarks.

> Reviewed 4 of 8 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33218#-:-LU1Okas1HrN0Iuti1yh:bknz579)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/roachpb/api.proto, line 382 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33218#-LTzhA--Bo637yocOUz1:-LU1OExDEs6eqUUmt1GH:b9unvxm) ([raw file](https://github.com/cockroachdb/cockroach/blob/302d96096f5d58dbb5b9c1e219f4f2ce5799ebd9/pkg/roachpb/api.proto#L382)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What if we just made this field `repeated`? Doing so would be backwards compatible and we could have a server-side contract to never have more than a single element. `combine` could then simply create a slice of byte slices instead of merging the bytes directly.
</blockquote></details>

We can also change this name to `batch_responses` while remaining backwards compatible. Do you think that's needed for clarity?

**Review by andreimatei — APPROVED** [review]
:clap: 
I had assumed repeated fields don't just work, but it's fantastic that they do!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33218#-:-LU1m30e1K2qKlNTjA4T:b-jbpfsr)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/roachpb/api.proto, line 376 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33218#-LU1m-0UAonJEPEFXn3m:-LU1m-0UAonJEPEFXn3n:b-8tijpn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9181bf2dea8a59597b98fc0cb830f9725c74c641/pkg/roachpb/api.proto#L376)):*
> ```protobuf
>   repeated KeyValue intent_rows = 3 [(gogoproto.nullable) = false];
> 
>   // If set, the results of the scan in batch format - the key/value pairs are
> ```

this comment needs more words now

**Comment by jordanlewis** [comment]
@nvanbenschoten said:
> but I would love to see the results of a few benchmarks.

Finally got around to doing this: I used the relatively new `kv --span-percent` flag.

Before:

```
[16:27]% ./bin/workload run kv --min-block-bytes 10000 --max-block-bytes 10001  --batch=1000 --write-seq=R36800 --span-percent=100 --max-ops=1 --concurrency=1
Highest sequence written: 36800. Can be passed as --write-seq=R36800 to the next run.

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
   18.3s        0              1            0.1  18790.5  19327.4  19327.4  19327.4  19327.4  span

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
   18.3s        0              1            0.1  18790.5  19327.4  19327.4  19327.4  19327.4
```

After:

```
[16:27]% ./bin/workload run kv --min-block-bytes 10000 --max-block-bytes 10001  --batch=1000 --write-seq=R36800 --span-percent=100 --max-ops=1 --concurrency=1
Highest sequence written: 36800. Can be passed as --write-seq=R36800 to the next run.

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
   10.2s        0              1            0.1  10469.0  10737.4  10737.4  10737.4  10737.4  span

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
   10.2s        0              1            0.1  10469.0  10737.4  10737.4  10737.4  10737.4
```

That almost doubles the base scan speed of a query that has large values. Not too bad!

**Comment by jordanlewis** [comment]
Ok I was way too eager with those benchmark numbers. It's not nearly double - I just got unlucky with a few runs I think. Doing a bunch more runs shows a lot closer to parity.

Before: `7.2625` seconds over an average of ten runs.
After: `5.7625` seconds over an average of ten runs.

And from`pprof`: Before:

image

After:

image

**Pull request merged**
