### PR TITLE
jepsen: Add disk fault injection nemesis

### PR DESCRIPTION
**Pull request by bdarnell**
Another temporary PR to get something i can test on teamcity

### CODE REVIEW

**Comment by bdarnell** [comment]
OK, this is ready to go with jepsen-io/jepsen#235. The branch reference in main.tf will be reverted once I've updated the branch in our fork.

**Review by benesch — APPROVED** [review]
🎉 🎉 🎉

**Comment by tschottdorf** [comment]
@bdarnell, what's the plan with this PR?

**Comment by bdarnell** [comment]
This PR is obsolete. I want to push the disk nemesis upstream but Aphyr wants it in the main jepsen pacakge instead of a separate one and that means I need to update our tests to work with jepsen master, so I've got some yaks to shave....

**Pull request closed without merging**
