### PR TITLE
storage/engine: tune target_file_size_{base,multiplier}

### PR DESCRIPTION
**Pull request by petermattis**
The previous settings of `target_file_size_{base,multiplier}` were
horrifically bad. A base size of `64 MB` and multiplier of `8` caused
the following target file sizes per level:

```
    L1   64 MB
    L2  512 MB
    L3    4 GB
    L4   32 GB
    L5  256 GB
    L6    2 TB
```

Combined with `level_compaction_dynamic_level_bytes` which fills from
the lowest level (L6) up, this caused excessively large
compactions. RocksDB is design such that compactions at higher levels
only compact part of the level, but our settings were forcing compaction
of the entire level. The settings have been tuned to result in the
following target file sizes:

```
    L1    4 MB
    L2    8 MB
    L3   16 MB
    L4   32 MB
    L5   64 MB
    L6  128 MB
```

The result is a lot more files, but this is expected. For large data
storage on a node we'll need to be sure to have large open file limits.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7562)

### CODE REVIEW

**Comment by tamird** [comment]
in the commit message: s/design/designed/

do we need to add something to the readme regarding open file limits?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[storage/engine/rocksdb/db.cc, line 1430 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7562#-KLY2X9_E8QnXzgSTboN:-KLY2X9ak2boOpEEX4BM:-466731813) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebae47c57d46993836386fc388a03ba031bb89d3/storage/engine/rocksdb/db.cc#L1430)):*
> ```cpp
>   // Target the base file size as 1/4 of the base size which will give
>   // us ~4 files in the base level (level 0). Each additional level
>   // grow the file size by 2. If max_bytes_for_level_base is 16 MB,
> ```

grows

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7562#-:-KLY2rhs2_wZayWKyUM3:1365862011)*

**Comment by cuongdo** [comment]
:lgtm:

This seems to fix the sparse file / disk full issue for me.

It also looks like this helps performance for #7280 considerably. I'll keep my test running to see what the long-term performance impact is.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7562#-:-KLY9621ULO3VUD7MXzK:-313111239)*

**Comment by petermattis** [comment]
Fixed the commit message.

I don't think the readme is a good place to discover open file limit recommendations. @jseldess?

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/engine/rocksdb/db.cc, line 1430 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7562#-KLY2X9_E8QnXzgSTboN:-KLYBjcoo80u8oI7-cKb:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebae47c57d46993836386fc388a03ba031bb89d3/storage/engine/rocksdb/db.cc#L1430)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> grows
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7562#-:-KLYBkDcPhIoPRLlmkWw:331365168)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7562)*

**Comment by bdarnell** [comment]
FYI this change forced us to increase the file descriptor limits on the beta clusters. They were previously running with a limit of 2048 (I don't know how many they were actually using); now they use between 1500 and 5000 in the steady state (with between 150 and 300GB of data)

**Comment by bdarnell** [comment]
This is going to be a headache on some linux distributions. On some of our test clusters (beta/gamma/rho; these are all running ubuntu 15.10), the default file descriptor limits are 1024 (soft) and 65536 (hard). This is fine, we can just increase our soft limit to 65536. On others (register, running ubuntu 14.04), the default hard limit is 4096. This means that we require root access to increase the limit for a reasonably-sized store.

This isn't a dealbreaker, but it does complicate our installation story. How much performance do we gain by using such tiny (4MB) files? It might be worth increasing these sizes to reduce this barrier to deployment.

**Comment by BramGruneir** [comment]
I'm working on a PR to make sure we have the right file descriptor limits per store.  What should be the minimum?  5000?

**Comment by bdarnell** [comment]
If we set the minimum to 5000, we can't run out of the box on ubuntu 14.04 (presumably among other distros), which seems like a problem for small test environments. On the other hand, if we're going to require 5k file descriptors for production use we might as well get that checked early.

**Comment by petermattis** [comment]
The performance gain is pretty dramatic. We can futz with the specifics to slightly reduce that number, but I think we should expect a file limit of 10k. This doesn't have to be a hard requirement.

We can also tell RocksDB to limit the number of files it has open. If we detect that the open file limit is less than 10k we can set `rocksdb::Options::max_open_files` to something like 1/2 of the limit.

**Comment by petermattis** [comment]
Here's my proposal for what we should do:
* Increase the open file limit to the max allowed in `cockroach start`.
* Add `DBOptions.max_open_files` which will get passed through to `rocksdb::Options::max_open_files`.
* If the open file limit is less than 10k, set `max_open_files` to 1/2 of that limit, log a warning and display an error in the admin UI.

**Comment by BramGruneir** [comment]
This is on a per store basis right?  If we have 2 stores on the same machine, we're going to need twice the limit?

**Comment by bdarnell** [comment]
Why only set max_open_files when the limit is less than 10k? We always need to save some room under the limit for network connections, so it seems like we should never allow rocksdb to consume the entire limit.

**Comment by petermattis** [comment]
Setting `max_open_files` is apparently a performance hit, but I just discovered it defaults to 5000. So scratch my comment about only setting it if the open file limit is less than 10k. Let's set the value to `open_file_limit / (2 * number_stores)`. That is, we set aside half of the open files for RocksDB and evenly divide the open files amongst the stores.

**Comment by BramGruneir** [comment]
SGTM

Should we have a minimum number of open files?  Say 1024 (or 512) per store?

**Comment by petermattis** [comment]
I think a lower value will hurt performance, but I'm not sure by how much. We should have a metric for the number of open files. A hard requirement makes me somewhat anxious, so I'd like it to be fairly low. Perhaps 128 or 256.

**Comment by bdarnell** [comment]
For a random point of comparison (just because I have these docs in front of me), `supervisord` will refuse to start if the hard file descriptor limit is lower than 1024.

**Comment by BramGruneir** [comment]
Ok, here's what I'll setup.

- If the hard limit is less than 128/store, fail during startup.
- Always set the soft limit to the hard limit if they don't match.
- Set max_open_files per store to be `open_file_limit / (2 * number_stores)`

**Comment by BramGruneir** [comment]
Looks like max_open_files has been updated again to `-1`
https://github.com/facebook/rocksdb/blob/1b166928c7c45cca9ada1dfab6b808ed3d2d0ffc/DEFAULT_OPTIONS_HISTORY.md

You can see it here:
https://github.com/facebook/rocksdb/blob/32df9733d10662705d594b8b6c0476c34a7c567c/util/options.cc

**Comment by petermattis** [comment]
Interesting. We're not using 4.8 (yet).

**Comment by BramGruneir** [comment]
I'm inclined to still set it.  We can always revisit the setting in the future.

**Comment by petermattis** [comment]
Looks like using `max_open_files == -1` causes RocksDB to use the open files limit. So apparently nothing to explore here.

**Comment by BramGruneir** [comment]
Trying to set it on osx... And I keep getting stuck because you can't set it via golang past the hidden max of 10240.

http://krypted.com/mac-os-x/maximum-files-in-mac-os-x/

**Comment by petermattis** [comment]
@BramGrunier Yeah, Mac OS X isn't reporting the true max via `getrlimit`. Not sure what to suggest here.

**Comment by cuongdo** [comment]
Unfortunately, this is causing failures of the 1->3 10GiB up-replication test:

http://teamcity.cockroachdb.com/viewLog.html?buildId=933&buildTypeId=Cockroach_AllocatorTest1to310g&tab=buildLog

The node logs weren't saved in the artifacts, because the test timeout kills the test forcefully, skipping the copying of node logs to the artifact directory. However, I happened to catch an in-progress failing test, and `cockroach` did crash because it ran out of file descriptors.

cc @jordanlewis since we need to up the allowed # of file descriptors for TeamCity (I've done this in an ad-hoc way for now)

**Comment by BramGruneir** [comment]
@cuongdo That's exactly why I'll have a fix out soon. Just putting the finishing touches on the commit.

**Pull request merged**
