### PR TITLE
sql/parser: support additional interval formats

### LINKED ISSUE #2710: sql: Improve INTERVAL input format
INTERVAL input uses a golang format: '2h2m4s'. While this is a nice modern way of inputting intervals, we should also support the SQL standard format as described here.

http://www.postgresql.org/docs/9.1/static/datatype-datetime.html#DATATYPE-INTERVAL-INPUT-EXAMPLES

### PR DESCRIPTION
**Pull request by danhhz**
Adds support for ISO8601 intervals as well as the Postgres "traditional" format.

Forked from https://github.com/cockroachdb/cockroach/pull/4858.

Closes #2710.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6216)

### CODE REVIEW

**Comment by paperstreet** [comment]
Hi, @theangryangel. I hope you don't mind, but I went ahead and responded to the last round of code review comments from your pull request. I also updated it to use the new duration.Duration, which explicitly models months, days, and nanos instead of converting them.

**Comment by theangryangel** [comment]
@paperstreet No problem at all. I've simply had no time to address the issues. Sorry I let it linger.

**Comment by dt** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/parser/interval.go, line 29 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6216#-KFz3-PSomHf5ZuOqwKC:-KFz3-PSomHf5ZuOqwKD:-856230416) ([raw file](https://github.com/cockroachdb/cockroach/blob/8099d714529cde9f66cea5a3cdbc3b7434038227/sql/parser/interval.go#L29)):*
nit: i'd give this a more interval-specific name (or make the errors it returns more generic).

---

*[sql/parser/interval.go, line 115 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6216#-KFz3dqAaeOF3PK9w-A-:-KFz3dqAaeOF3PK9w-A0:796020593) ([raw file](https://github.com/cockroachdb/cockroach/blob/8099d714529cde9f66cea5a3cdbc3b7434038227/sql/parser/interval.go#L115)):*
nit: `l.offset < len(s)`?

---

*[sql/parser/interval.go, line 152 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6216#-KFz3ALgcTgj_CG1VZw3:-KFz3ALgcTgj_CG1VZw4:1430383897) ([raw file](https://github.com/cockroachdb/cockroach/blob/8099d714529cde9f66cea5a3cdbc3b7434038227/sql/parser/interval.go#L152)):*
hm, this will allocate a new string every time. is it much uglier to configure the lexer to handle the spaces?

---

*[sql/parser/interval.go, line 156 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6216#-KFz6EONOP24izgM970h:-KFz6EONOP24izgM970i:1549847052) ([raw file](https://github.com/cockroachdb/cockroach/blob/8099d714529cde9f66cea5a3cdbc3b7434038227/sql/parser/interval.go#L156)):*
Would it make sense for the lexer do a little lookahead on consume-unit to throw away trailing `s`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6216)*

**Comment by paperstreet** [comment]
Review status: 4 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/parser/interval.go, line 29 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6216#-KFz3-PSomHf5ZuOqwKC:-KFzI1YIbIFfDmKYLhqG:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/8099d714529cde9f66cea5a3cdbc3b7434038227/sql/parser/interval.go#L29)):*
Done.

---

*[sql/parser/interval.go, line 115 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6216#-KFz3dqAaeOF3PK9w-A-:-KFzIBbYZ48nOIv_IXSU:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/8099d714529cde9f66cea5a3cdbc3b7434038227/sql/parser/interval.go#L115)):*
Done.

---

*[sql/parser/interval.go, line 152 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6216#-KFz3ALgcTgj_CG1VZw3:-KFzJ_EpZUlOTyxSK1fX:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/8099d714529cde9f66cea5a3cdbc3b7434038227/sql/parser/interval.go#L152)):*
Done.

---

*[sql/parser/interval.go, line 156 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6216#-KFz6EONOP24izgM970h:-KFzIHGSry2_7SJ5Tx6o:-1928612274) ([raw file](https://github.com/cockroachdb/cockroach/blob/8099d714529cde9f66cea5a3cdbc3b7434038227/sql/parser/interval.go#L156)):*
I'd rather just add entries for days, weeks, etc to the maps.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6216)*

**Comment by dt** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6216#-:-KFzM1DXuLBPHs2Moxkp:1417088721)*

**Comment by jseldess** [comment]
Docs updated with https://github.com/cockroachdb/docs/pull/462

**Pull request merged**
