### PR TITLE
roachtest: extract spec package

### PR DESCRIPTION
**Pull request by tbg**
This continues the work started in #66355 and #66365 to make the `Cluster`
interface depend only on subpackages.

The majority of this PR is concerned with moving `clusterSpec` into a
subpackage. This isn't used prominently by `Cluster` - we could've changed the
interface and probably would have gotten away with leaving it in the main
package - but it is also a solid chunk of code that was riddled with references
to the command-line flags, which is not a good pattern.

- roachtest: extract nodeListOption
- roachtest: move clusterSpec to its own file
- roachtest: avoid access to globals in clusterSpec
- roachtest: avoid access to createArgs from cluster_spec.go
- roachtest: remove instanceType dep of clusterSpec
- roachtest: don't use zonesF in clusterSpec
- roachtest: move cpu->machine type fns to spec package
- roachtest: extract clusterSpec to spec subpackage

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
Only skimmed this since I expect this package to be in flux for quite some time, but the general direction is promising!

**Comment by tbg** [comment]
TFTR! I'm going to "test" this by running the `indexes/2/nodes=6/multi-region` test against AWS. I did have to make a few logic changes related to the `cloud` and `zonesF` flags and want to make sure we're getting what we're asking for.

**Comment by tbg** [comment]
bors r+

Still have to test, but this is already rotting due to competing merges, so I will merge it while I test.

**Comment by tbg** [comment]
bors r-
Found something already.

**Comment by tbg** [comment]
bors r=erikgrinaker

**Comment by tbg** [comment]
bors r=erikgrinaker

**Comment by tbg** [comment]
bors r=erikgrinaker

**Comment by tbg** [comment]
bors r-

Getting annoyed with this yet Erik? :D

**Comment by erikgrinaker** [comment]
>Getting annoyed with this yet Erik? :D

Not as annoyed as you are, I'm guessing. :)

**Comment by tbg** [comment]
Now there's some fairly comprehensive testing for `(ClusterSpec).Args()`, feel fairly good about this now.

bors r=erikgrinaker

**Pull request merged**
