### PR TITLE
sql/ir: implement a front end for the IR definition compiler

### PR DESCRIPTION
**Pull request by knz**
This defines the Go structs that serve as building blocks to implement the various code generators. 

The commit is by David, but was sitting on an idle branch.  I am pushing this to the main repo so that we can each send PRs against the main repo separately.

### CODE REVIEW

**Comment by knz** [comment]
LGTM modulo this passes the linter.

**Comment by jordanlewis** [comment]
:man_scientist: :dog: - a couple of random comments. I'm curious to keep following this as it comes along!

---

Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/ir/irgen/main.go, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16730#-KndfA1-hf96RydMUOYl:-KndfA1-hf96RydMUOYm:bt0rssz) ([raw file](https://github.com/cockroachdb/cockroach/blob/207a4c12e220af374f8458e781daf6fc5a5bca94/pkg/sql/ir/irgen/main.go#L1)):*
> ```Go
> package main
> ```

missing license, and throughout;

---

*[pkg/sql/ir/irgen/parser/irgen.y, line 6 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16730#-KndfXLuq1snfmuVfl2h:-KndfXLuq1snfmuVfl2i:b-mnl1np) ([raw file](https://github.com/cockroachdb/cockroach/blob/207a4c12e220af374f8458e781daf6fc5a5bca94/pkg/sql/ir/irgen/parser/irgen.y#L6)):*
> ```Yacc
> import "io"
> 
> // Parse parses definitions from an io.Reader.
> ```

could use an example file so readers can have a point of reference to the grammar that this parser is meant to parse. or tests! but it's early still, i know.

---

*[pkg/sql/ir/irgen/parser/irgen.y, line 9 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16730#-KndfNFsqaK5Q087tK5t:-KndfNFsqaK5Q087tK5u:bcjxmvm) ([raw file](https://github.com/cockroachdb/cockroach/blob/207a4c12e220af374f8458e781daf6fc5a5bca94/pkg/sql/ir/irgen/parser/irgen.y#L9)):*
> ```Yacc
> func Parse(filename string, src io.Reader) ([]Def, error) {
> 	l := newLexer(filename, src)
> 	irgenParse(l)
> ```

s/tabs/spaces/ i think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16730#-:-KndfsbEw43G1igUpRMF:bxpyvjk)*

**Comment by knz** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/ir/irgen/main.go, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16730#-KndfA1-hf96RydMUOYl:-Kndh8PfZTSzbai4xt3g:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/207a4c12e220af374f8458e781daf6fc5a5bca94/pkg/sql/ir/irgen/main.go#L1)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

missing license, and throughout;
</blockquote></details>

Done.

---

*[pkg/sql/ir/irgen/parser/irgen.y, line 6 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16730#-KndfXLuq1snfmuVfl2h:-KndhOVrqCGwksyohMOI:b-o0ac96) ([raw file](https://github.com/cockroachdb/cockroach/blob/207a4c12e220af374f8458e781daf6fc5a5bca94/pkg/sql/ir/irgen/parser/irgen.y#L6)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

could use an example file so readers can have a point of reference to the grammar that this parser is meant to parse. or tests! but it's early still, i know.
</blockquote></details>

I'm on it

---

*[pkg/sql/ir/irgen/parser/irgen.y, line 9 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16730#-KndfNFsqaK5Q087tK5t:-KndhO5Aggi1ovzF3yt1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/207a4c12e220af374f8458e781daf6fc5a5bca94/pkg/sql/ir/irgen/parser/irgen.y#L9)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

s/tabs/spaces/ i think?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16730)*

**Comment by knz** [comment]
@eisenstatdavid I added some tests, PTAL

**Comment by knz** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/ir/irgen/parser/irgen.y, line 6 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16730#-KndfXLuq1snfmuVfl2h:-Kne0HT0_v6FYOhm3I2O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/207a4c12e220af374f8458e781daf6fc5a5bca94/pkg/sql/ir/irgen/parser/irgen.y#L6)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'm on it
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16730)*

**Comment by eisenstatdavid** [comment]
:lgtm:

---

Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16730#-:-Kne6Q_DS2ooqniMM58e:bnfp4nl)*

**Pull request merged**
