### PR TITLE
exec: add templating to vectorized merge join 

### PR DESCRIPTION
**Pull request by georgeutsin**
The second last step in the vectorized merge join operator is the
introduction of templating so that the equality type isn't limited
to just int64s.

With this change, there are also performance boosts as the
selection vector switching is now moved outside the tight loop.

Further, we noticed a bug in the previous completeGroups
implementation, so we killed two birds with one stone by both
templating and fixing that edge case with the use of the distinct
operator.

Special thanks to @jordanlewis who is really a coauthor of this
PR.

And as usual, some benchmarks:

```
name                                      old time/op    new time/op    delta
MergeJoiner/rows=1024-8                     44.9µs ± 1%    35.3µs ± 0%  -21.43%  (p=0.000 n=10+10)
MergeJoiner/rows=4096-8                      171µs ± 0%     133µs ± 0%  -22.15%  (p=0.000 n=10+10)
MergeJoiner/rows=16384-8                     656µs ± 1%     508µs ± 1%  -22.60%  (p=0.000 n=10+10)
MergeJoiner/rows=1048576-8                  40.3ms ± 1%    30.8ms ± 1%  -23.43%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=1024-8       45.4µs ± 0%    35.4µs ± 0%  -22.19%  (p=0.000 n=10+9)
MergeJoiner/oneSideRepeat-rows=4096-8        171µs ± 0%     133µs ± 0%  -22.16%  (p=0.000 n=10+8)
MergeJoiner/oneSideRepeat-rows=16384-8       655µs ± 0%     508µs ± 0%  -22.54%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=1048576-8    40.3ms ± 1%    31.0ms ± 1%  -23.12%  (p=0.000 n=10+9)
MergeJoiner/bothSidesRepeat-rows=1024-8     48.3µs ± 1%    37.6µs ± 1%  -22.25%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=4096-8      186µs ± 1%     174µs ± 0%   -6.05%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=16384-8    1.41ms ± 0%    1.39ms ± 1%   -1.59%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=32768-8    4.93ms ± 1%    5.28ms ± 1%   +7.17%  (p=0.000 n=9+10)

name                                      old speed      new speed      delta
MergeJoiner/rows=1024-8                   1.46GB/s ± 1%  1.86GB/s ± 0%  +27.28%  (p=0.000 n=10+10)
MergeJoiner/rows=4096-8                   1.53GB/s ± 0%  1.97GB/s ± 0%  +28.46%  (p=0.000 n=10+10)
MergeJoiner/rows=16384-8                  1.60GB/s ± 1%  2.06GB/s ± 1%  +29.20%  (p=0.000 n=10+10)
MergeJoiner/rows=1048576-8                1.67GB/s ± 1%  2.18GB/s ± 1%  +30.60%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=1024-8     1.44GB/s ± 0%  1.85GB/s ± 0%  +28.52%  (p=0.000 n=10+9)
MergeJoiner/oneSideRepeat-rows=4096-8     1.54GB/s ± 0%  1.97GB/s ± 0%  +28.47%  (p=0.000 n=10+8)
MergeJoiner/oneSideRepeat-rows=16384-8    1.60GB/s ± 0%  2.07GB/s ± 0%  +29.10%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=1048576-8  1.67GB/s ± 1%  2.17GB/s ± 1%  +30.07%  (p=0.000 n=10+9)
MergeJoiner/bothSidesRepeat-rows=1024-8   1.36GB/s ± 1%  1.74GB/s ± 1%  +28.62%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=4096-8   1.41GB/s ± 1%  1.50GB/s ± 0%   +6.43%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=16384-8   743MB/s ± 0%   755MB/s ± 1%   +1.62%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=32768-8   426MB/s ± 1%   397MB/s ± 1%   -6.69%  (p=0.000 n=9+10)

name                                      old alloc/op   new alloc/op   delta
MergeJoiner/rows=1024-8                     4.23kB ± 0%    4.23kB ± 0%   -0.07%  (p=0.000 n=10+10)
MergeJoiner/rows=4096-8                     4.25kB ± 0%    4.25kB ± 0%     ~     (all equal)
MergeJoiner/rows=16384-8                    4.34kB ± 0%    4.30kB ± 0%   -0.92%  (p=0.000 n=10+10)
MergeJoiner/rows=1048576-8                  12.2kB ± 0%     9.0kB ± 0%  -26.16%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=1024-8       4.23kB ± 0%    4.23kB ± 0%   -0.07%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=4096-8       4.25kB ± 0%    4.25kB ± 0%     ~     (all equal)
MergeJoiner/oneSideRepeat-rows=16384-8      4.34kB ± 0%    4.30kB ± 0%   -0.92%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=1048576-8    12.2kB ± 0%     9.0kB ± 0%  -26.16%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=1024-8     4.23kB ± 0%    4.23kB ± 0%   -0.07%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=4096-8     4.25kB ± 0%    4.25kB ± 0%     ~     (all equal)
MergeJoiner/bothSidesRepeat-rows=16384-8    4.46kB ± 0%    4.46kB ± 0%     ~     (all equal)
MergeJoiner/bothSidesRepeat-rows=32768-8    5.02kB ± 0%    5.02kB ± 0%     ~     (all equal)

name                                      old allocs/op  new allocs/op  delta
MergeJoiner/rows=1024-8                       4.00 ± 0%      4.00 ± 0%     ~     (all equal)
MergeJoiner/rows=4096-8                       4.00 ± 0%      4.00 ± 0%     ~     (all equal)
MergeJoiner/rows=16384-8                      4.00 ± 0%      4.00 ± 0%     ~     (all equal)
MergeJoiner/rows=1048576-8                    6.00 ± 0%      5.00 ± 0%  -16.67%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=1024-8         4.00 ± 0%      4.00 ± 0%     ~     (all equal)
MergeJoiner/oneSideRepeat-rows=4096-8         4.00 ± 0%      4.00 ± 0%     ~     (all equal)
MergeJoiner/oneSideRepeat-rows=16384-8        4.00 ± 0%      4.00 ± 0%     ~     (all equal)
MergeJoiner/oneSideRepeat-rows=1048576-8      6.00 ± 0%      5.00 ± 0%  -16.67%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=1024-8       4.00 ± 0%      4.00 ± 0%     ~     (all equal)
MergeJoiner/bothSidesRepeat-rows=4096-8       4.00 ± 0%      4.00 ± 0%     ~     (all equal)
MergeJoiner/bothSidesRepeat-rows=16384-8      4.00 ± 0%      4.00 ± 0%     ~     (all equal)
MergeJoiner/bothSidesRepeat-rows=32768-8      4.00 ± 0%      4.00 ± 0%     ~     (all equal)

```

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
Awesome work! :lgtm:

> Reviewed 1 of 2 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36386#-:-LbQA-GD67srZQdD14vC:bkr2yf2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, and @jordanlewis)

___
*[pkg/sql/exec/mergejoiner.go, line 337 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36386#-LbQ8XVG7AFYULXN3mFS:-LbQ8XVG7AFYULXN3mFT:bryqqun) ([raw file](https://github.com/cockroachdb/cockroach/blob/761d50df0cdd6a065e6475a6efacfad48ad674fc/pkg/sql/exec/mergejoiner.go#L337)):*
> ```Go
> 		input.distincterInput.bat = bat
> 		input.distincter.Next()
> 		// Now, the input.distinctOutput column will contain true in the 0th row,
> ```

[nit]: I think this comment is true only for the first iteration of the `for` loop, so I'd put it right above `loopStartIndex`.
___
*[pkg/sql/exec/mergejoiner.go, line 504 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36386#-LbQAF0V52T3EoAmhNWU:-LbQAF0V52T3EoAmhNWV:b-66k0jf) ([raw file](https://github.com/cockroachdb/cockroach/blob/761d50df0cdd6a065e6475a6efacfad48ad674fc/pkg/sql/exec/mergejoiner.go#L504)):*
> ```Go
> }
> 
> type fakeOperator struct {
> ```

[nit]: this deserves a comment (mention how we use it to "feed" the distinct operator with a batch).
___
*[pkg/sql/exec/mergejoiner_test.go, line 604 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36386#-LbQ2AMbCkMewWxIBg5u:-LbQ2AMbCkMewWxIBg5v:b-21xjv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/761d50df0cdd6a065e6475a6efacfad48ad674fc/pkg/sql/exec/mergejoiner_test.go#L604)):*
> ```Go
> 		},
> 		{
> 			description:  "templating reordered eq columns",
> ```

Add a test or two with reordered equality columns but with different orders on each side (i.e. `2, 0` and `1, 2` for example).
___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36386#-LbQ2cfX2nP7M_NYEA52:-LbQ2cfX2nP7M_NYEA53:b-9gtow6) ([raw file](https://github.com/cockroachdb/cockroach/blob/761d50df0cdd6a065e6475a6efacfad48ad674fc/pkg/sql/exec/mergejoiner_tmpl.go#L73)):*
> ```Go
> const _L_SEL_IND = 0
> 
> // _L_SEL_IND is the template type variable for the loop variable that's either
> ```

[nit]: `_R_SEL_IND`. Also, it seems to be not a good practice to use variable names in the comments "far away" from where the variables are used/defined, so possibly describe the "inherent" meaning of the variable that is templated out.
___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 474 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36386#-LbQ4sAq9TNrHgTHYNNy:-LbQ4sAq9TNrHgTHYNNz:b-aq0asn) ([raw file](https://github.com/cockroachdb/cockroach/blob/761d50df0cdd6a065e6475a6efacfad48ad674fc/pkg/sql/exec/mergejoiner_tmpl.go#L474)):*
> ```Go
> 	input *mergeJoinInput,
> 	savedGroup coldata.Batch,
> 	savedGroupIdx *int,
> ```

[nit]: `savedGroupIdx` is not modified here, so a pointer is not necessary.
___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 484 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36386#-LbQ5JkJEH5VTnF7kY_Y:-LbQ5JkJEH5VTnF7kY_Z:b-9y5dzl) ([raw file](https://github.com/cockroachdb/cockroach/blob/761d50df0cdd6a065e6475a6efacfad48ad674fc/pkg/sql/exec/mergejoiner_tmpl.go#L484)):*
> ```Go
> 
> 	// Check all equality columns before the last equality column to make sure we're in the same group.
> 	for _, colIdx := range input.eqCols[:len(input.eqCols)] {
> ```

I think a minus one is missing, i.e. it should be `range input.eqCols[:len(input.eqCols)-1]`.
___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 513 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36386#-LbQ74MN7Sp25_i-iyAJ:-LbQ74MN7Sp25_i-iyAK:b64yy5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/761d50df0cdd6a065e6475a6efacfad48ad674fc/pkg/sql/exec/mergejoiner_tmpl.go#L513)):*
> ```Go
> // starting at idx, given the comparison value. Also returns a boolean indicating whether the group
> // is known to be complete.
> func getGroupLengthForValue(
> ```

This function is not templated, so I don't see a reason to move it into `_tmpl` file. Also, I can't seem to find where it is used, maybe it is not needed any more?
___
*[pkg/sql/exec/execgen/cmd/execgen/mergejoiner_gen.go, line 80 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36386#-LbQ10v35yM2MvPSTyAR:-LbQ10v35yM2MvPSTyAS:bslek99) ([raw file](https://github.com/cockroachdb/cockroach/blob/761d50df0cdd6a065e6475a6efacfad48ad674fc/pkg/sql/exec/execgen/cmd/execgen/mergejoiner_gen.go#L80)):*
> ```Go
> 		return err
> 	}
> 	//return tmpl.Execute(wr, comparisonOpToOverloads[tree.EQ])
> ```

[nit]: remove the commented line.

**Review by georgeutsin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36386)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/exec/mergejoiner.go, line 337 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36386#-LbQ8XVG7AFYULXN3mFS:-LbU21fv9WcL24LZiVlq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/761d50df0cdd6a065e6475a6efacfad48ad674fc/pkg/sql/exec/mergejoiner.go#L337)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: I think this comment is true only for the first iteration of the `for` loop, so I'd put it right above `loopStartIndex`.
</blockquote></details>

Done.
___
*[pkg/sql/exec/mergejoiner.go, line 504 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36386#-LbQAF0V52T3EoAmhNWU:-LbU22cwE8trBvBgvVBW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/761d50df0cdd6a065e6475a6efacfad48ad674fc/pkg/sql/exec/mergejoiner.go#L504)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: this deserves a comment (mention how we use it to "feed" the distinct operator with a batch).
</blockquote></details>

Done.
___
*[pkg/sql/exec/mergejoiner_test.go, line 604 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36386#-LbQ2AMbCkMewWxIBg5u:-LbU24g4ASNVdvVY4FSm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/761d50df0cdd6a065e6475a6efacfad48ad674fc/pkg/sql/exec/mergejoiner_test.go#L604)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Add a test or two with reordered equality columns but with different orders on each side (i.e. `2, 0` and `1, 2` for example).
</blockquote></details>

Done.
___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36386#-LbQ2cfX2nP7M_NYEA52:-LbU25O1DlQIc4iuxE6a:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/761d50df0cdd6a065e6475a6efacfad48ad674fc/pkg/sql/exec/mergejoiner_tmpl.go#L73)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: `_R_SEL_IND`. Also, it seems to be not a good practice to use variable names in the comments "far away" from where the variables are used/defined, so possibly describe the "inherent" meaning of the variable that is templated out.
</blockquote></details>

Done.
___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 474 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36386#-LbQ4sAq9TNrHgTHYNNy:-LbU263Z0e7U2BTw_qBG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/761d50df0cdd6a065e6475a6efacfad48ad674fc/pkg/sql/exec/mergejoiner_tmpl.go#L474)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: `savedGroupIdx` is not modified here, so a pointer is not necessary.
</blockquote></details>

Done.
___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 484 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36386#-LbQ5JkJEH5VTnF7kY_Y:-LbU26ZhESi_D9mS_RDv:b-n81nq5) ([raw file](https://github.com/cockroachdb/cockroach/blob/761d50df0cdd6a065e6475a6efacfad48ad674fc/pkg/sql/exec/mergejoiner_tmpl.go#L484)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think a minus one is missing, i.e. it should be `range input.eqCols[:len(input.eqCols)-1]`.
</blockquote></details>

Done. Out of date comment.
___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 513 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36386#-LbQ74MN7Sp25_i-iyAJ:-LbU29oA1VMhsiIARrwp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/761d50df0cdd6a065e6475a6efacfad48ad674fc/pkg/sql/exec/mergejoiner_tmpl.go#L513)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

This function is not templated, so I don't see a reason to move it into `_tmpl` file. Also, I can't seem to find where it is used, maybe it is not needed any more?
</blockquote></details>

Done.
___
*[pkg/sql/exec/execgen/cmd/execgen/mergejoiner_gen.go, line 80 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36386#-LbQ10v35yM2MvPSTyAR:-LbU2ASD0uCc5LyBQcVj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/761d50df0cdd6a065e6475a6efacfad48ad674fc/pkg/sql/exec/execgen/cmd/execgen/mergejoiner_gen.go#L80)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: remove the commented line.
</blockquote></details>

Done.

**Review by jordanlewis — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36386#-:-LbV672bEuppv8eqqlXc:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @georgeutsin, and @yuzefovich)

___
*[pkg/sql/exec/mergejoiner.go, line 206 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36386#-LbV5WsC96HkoDvKXroU:-LbV5WsC96HkoDvKXroV:b7z2bqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fb4dbce015616dbadb1d6c605406d09d8ceba5c/pkg/sql/exec/mergejoiner.go#L206)):*
> ```Go
> 		&c.left.distincterInput, leftEqCols, leftTypes)
> 	if err != nil {
> 		panic(err)
> ```

Could you replace these with `return nil, err` and change the signature of `NewMergeJoinOp` to include an error, like the other operators?

**Comment by georgeutsin** [comment]
Seems like a flaky test trying again:

bors r+

**Pull request merged**
