### PR TITLE
sql: add EXPERIMENTAL SHOW LOCALITY TRACE

### LINKED ISSUE #20873: sql: implement SHOW LOCALITY TRACE
TODO(dan): Fill in details.

### PR DESCRIPTION
**Pull request by danhhz**
EXPERIMENTAL SHOW LOCALITY TRACE executes a sql query and returns the
timestamp, node, store, and range for each kv read and write. This can
be joined with other system tables, such as `crdb_internal.gossip_nodes`
to view the localities and attributes assigned to those nodes.

Release note (sql change): Add EXPERIMENTAL SHOW LOCALITY TRACE command
which executes a sql query and returns which nodes served data reads and
writes.

Closes #20873.

### CODE REVIEW

**Comment by jordanlewis** [comment]
Dropped in to see what the output's going to be like - but there are no logic tests to see a sample! Could you include a sample in the PR/commit message at least (but preferably also a logic test or two)?

**Comment by a-robinson** [comment]
Is there a different name that would work similarly well? It's not a huge deal, but "locality" already has a different meaning to our users.

**Comment by benesch** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/show_trace_locality.go, line 29 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21349#-L2RN1NIsPiT_mDQKBnl:-L2RN1NIsPiT_mDQKBnm:bkn64xo) ([raw file](https://github.com/cockroachdb/cockroach/blob/0908c9fd9fefc92a31afb32dc7f32e3384599516/pkg/sql/show_trace_locality.go#L29)):*
> ```Go
> )
> 
> const nodeStoreRangeRE = `^\[n(\d+),s(\d+),r(\d+)/`
> ```

How about this instead?

```
var nodeStoreRangeRE = regexp.MustCompile(...)
```

---

*[pkg/sql/show_trace_locality.go, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21349#-L2RN7Oj2b1hui2eop-4:-L2RN7Oj2b1hui2eop-5:b-wr8caz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0908c9fd9fefc92a31afb32dc7f32e3384599516/pkg/sql/show_trace_locality.go#L42)):*
> ```Go
> 
> 	run struct {
> 		nodeStoreRange *regexp.Regexp
> ```

Then you can ditch this.

---

*[pkg/sql/show_trace_locality_test.go, line 97 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21349#-L2RN_aIAYiDLGi2HR-_:-L2RN_aIAYiDLGi2HR-a:b-sfz58o) ([raw file](https://github.com/cockroachdb/cockroach/blob/0908c9fd9fefc92a31afb32dc7f32e3384599516/pkg/sql/show_trace_locality_test.go#L97)):*
> ```Go
> 				`SELECT node_id, store_id FROM [EXPERIMENTAL SHOW LOCALITY TRACE FOR %s]`,
> 				test.query)
> 			actual := sqlDB.QueryStr(t, query)
> ```

`sqlDB.CheckQueryResults`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21349#-:-L2RNr9QhPXaX2mKUJZR:bnfp4nl)*

**Comment by danhhz** [comment]
Ah, it originally included the locality information, but we ended up normalizing that out of the schema. Changed the name to SHOW EXPERIMENTAL_REPLICA TRACE (the experimental moved positions to reflect our brand new best practice). I also added a logic test and example output in the commit message.

---

Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/show_trace_replica.go, line 29 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21349#-L2RN1NIsPiT_mDQKBnl:-L2Wmk9NagoI4pHvOClu:b37999f) ([raw file](https://github.com/cockroachdb/cockroach/blob/0908c9fd9fefc92a31afb32dc7f32e3384599516/pkg/sql/show_trace_replica.go#L29)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

How about this instead?

```
var nodeStoreRangeRE = regexp.MustCompile(...)
```
</blockquote></details>

i originally didn't do this because i didn't want to compile it on binary startup if the feature was never used. switched to a sync.Once to avoid doing it for every query

---

*[pkg/sql/show_trace_replica_test.go, line 97 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21349#-L2RN_aIAYiDLGi2HR-_:-L2WmxdtDYF3EjiJKWZF:b6km7eq) ([raw file](https://github.com/cockroachdb/cockroach/blob/0908c9fd9fefc92a31afb32dc7f32e3384599516/pkg/sql/show_trace_replica_test.go#L97)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

`sqlDB.CheckQueryResults`?
</blockquote></details>

doesn't play well with testutils.SucceedsSoon, unfortunately

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21349#-:-L2WmMOHSG-30IsuIwlK:b-1lzl0t)*

**Comment by benesch** [comment]
Still :lgtm:!

---

Reviewed 15 of 15 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/show_trace_replica.go, line 29 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21349#-L2RN1NIsPiT_mDQKBnl:-L2Wn_D_PQhIw3wsanHQ:bci15d6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0908c9fd9fefc92a31afb32dc7f32e3384599516/pkg/sql/show_trace_replica.go#L29)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

i originally didn't do this because i didn't want to compile it on binary startup if the feature was never used. switched to a sync.Once to avoid doing it for every query
</blockquote></details>

I'd be shocked if compiling this regex ever made a noticeable difference in binary boot time, but fair enough.

---

*[pkg/sql/show_trace_replica_test.go, line 97 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21349#-L2RN_aIAYiDLGi2HR-_:-L2WnjQLueP1DRjDFUlX:b9psuy2) ([raw file](https://github.com/cockroachdb/cockroach/blob/0908c9fd9fefc92a31afb32dc7f32e3384599516/pkg/sql/show_trace_replica_test.go#L97)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

doesn't play well with testutils.SucceedsSoon, unfortunately
</blockquote></details>

Ah, of course.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21349#-:-L2Wo2EZKN1E3Nr6odp2:b-dbkjmw)*

**Comment by jordanlewis** [comment]
:lgtm: cool!

---

Review status: 13 of 15 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21349#-:-L2Ww3OdQKhoXindeDcm:b-84whef)*

**Comment by danhhz** [comment]
TFTRs!

**Comment by spencerkimball** [comment]
Woah, very cool!

**Pull request merged**
