### PR TITLE
allocator2: preliminary interface definition

### PR DESCRIPTION
**Pull request by sumeerbhola**
Informs #103320

Epic: CRDB-25222

Release note: None

### CODE REVIEW

**Review by kvoli — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104334)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/allocator/allocator2/allocator.go` line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104334#-NXGbWDa4OjivAY9yc-t:-NXGbWDa4OjivAY9yc-u:bqvz6hh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1454a398e28acaeee062d4878a20383e2f3bd467/pkg/kv/kvserver/allocator/allocator2/allocator.go#L33)):*
> ```Go
> 
> 	// AddNodeID informs the allocator of a new node.
> 	AddNodeID(nodeID roachpb.NodeID) error
> ```

Not an important point -

Would `AddStore` fail if the store descriptor's node ID wasn't previously added with `AddNodeID(..)`? 

Likewise, would `ChangeStore` fail if the store wasn't previously added via `AddStore(..)`?

I'm wondering what does the separation give us, over say `SetStore` (in place of `AddStore` and `AddNodeID`) which handles the node initialization as well.
___
*[`pkg/kv/kvserver/allocator/allocator2/allocator.go` line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104334#-NXGduYT4PXpv0vX2eIy:-NXGduYU2GEeCywj9YLW:bi58ga5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1454a398e28acaeee062d4878a20383e2f3bd467/pkg/kv/kvserver/allocator/allocator2/allocator.go#L59)):*
> ```Go
> 	// and local synthesis:
> 	//
> 	// - storeLoadMsg.storeRanges is the list of ranges at the node, and is
> ```

The gossip info origin timestamp isn't readily available outside the internal gossip state. So we'd either need to add a timestamp field to the `StoreDescriptor` (or start using a new) proto or update to expose the origin TS.

https://github.com/cockroachdb/cockroach/blob/bc460496d54fe51bfe4effc9e8b828d2e25318eb/pkg/gossip/gossip.proto#L140-L141
___
*[`pkg/kv/kvserver/allocator/allocator2/allocator.go` line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104334#-NXGcc9w2kMZReGABI6I:-NXGcc9w2kMZReGABI6J:b-esy9ft) ([raw file](https://github.com/cockroachdb/cockroach/blob/1454a398e28acaeee062d4878a20383e2f3bd467/pkg/kv/kvserver/allocator/allocator2/allocator.go#L71)):*
> ```Go
> 	//   local node is the leaseholder.
> 	//
> 	// - storeLoadMsg.topKRanges could be locally synthesized by estimating the
> ```

+1 This seems doable. What we are missing is follower non-raft CPU. The other follower load dimensions can be estimated for writeBytes, size and raft CPU.
___
*[`pkg/kv/kvserver/allocator/allocator2/allocator.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104334#-NXGi6s_-Y31nW6JrlYR:-NXGi6s_-Y31nW6JrlYS:bus2oey) ([raw file](https://github.com/cockroachdb/cockroach/blob/1454a398e28acaeee062d4878a20383e2f3bd467/pkg/kv/kvserver/allocator/allocator2/allocator.go#L92)):*
> ```Go
> 	AdjustPendingChangesDisposition(changes []pendingReplicaChange, success bool) error
> 
> 	// ComputeChanges is called periodically and frequently, say every 10s.
> ```

Did you have any thoughts on the distributed allocators responsibility for rebalancing? 

The options I've been thinking of are:

1. Each allocator is responsible for keeping the store its on out of overload/above means.
2. Each allocator is responsible for keeping every store in the cluster out of overload/above means.

Then the legal changes an allocator could issue:

A. Allocator can issue changes for all ranges where it has the range leaseholder for.
B. Allocator can issue changes for all ranges where it has a replica for.
C. Allocator can issue changes for all ranges.

The store rebalancer does 1A currently.
The replicate queue (inc rebalancing) does 2A currently.

In 1A, stores which have no leaseholders won't be effectively dealt (happens today).
___
*[`pkg/kv/kvserver/allocator/allocator2/allocator.go` line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104334#-NXGkBM99PQSDIDxm6i4:-NXGkBMAD5Hmxo8sFsu7:b7hn32s) ([raw file](https://github.com/cockroachdb/cockroach/blob/1454a398e28acaeee062d4878a20383e2f3bd467/pkg/kv/kvserver/allocator/allocator2/allocator.go#L112)):*
> should we use load?

I'm not sure if there are any callers which would benefit.

StoreRebalancer always provides the final LH.
MergeQueue doesn't provide the final LH, but probably doesn't matter since the RHS LH will go away soon.

I don't know about any other uses in the code.
___
*[`pkg/kv/kvserver/allocator/allocator2/allocator.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104334#-NXFhcpe5T-8dRU-nq_j:-NXFhcpe5T-8dRU-nq_k:bx7iym8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1454a398e28acaeee062d4878a20383e2f3bd467/pkg/kv/kvserver/allocator/allocator2/allocator.go#L119)):*
> ```Go
> 	//
> 	// Note for reviewer: the intention here is to subsume some of the code in
> 	// replica_send.go, and this method will be called from
> ```

ack. Is this supposed to be `replica_command.go`?
___
*[`pkg/kv/kvserver/allocator/allocator2/allocator.go` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104334#-NXGoaNq1V_OAgjAWWMt:-NXGoaNq1V_OAgjAWWMu:bn3mcmg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1454a398e28acaeee062d4878a20383e2f3bd467/pkg/kv/kvserver/allocator/allocator2/allocator.go#L122)):*
> ```Go
> 	// Replica.relocateReplicas (ReplocateOne code is no longer needed).
> 	//
> 	// TODO(sumeer): is leaseholderStore needed. Presumably we are doing this at
> ```

`relocateRanges` issues DB commands like `AdminTransferLease`  and `AdminChangeReplicas` instead of local leaseholder variants like `changeReplicasImpl`. 

I think we do need to know the current leaseholder and we don't need to keep the leaseholder on the local store until the end.
___
*[`pkg/kv/kvserver/allocator/allocator2/messages.go` line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104334#-NXGnQf_-9aKdaeBE3Qn:-NXGnQf_-9aKdaeBE3Qo:b-871oyq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1454a398e28acaeee062d4878a20383e2f3bd467/pkg/kv/kvserver/allocator/allocator2/messages.go#L89)):*
> ```Go
> 	// complete load even if the sender asked for a diff.
> 	//
> 	// TODO(sumeer): the diff story is not properly fleshed out for the local
> ```

ack - I've been struggling a bit with this.

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

Also added a summary of our synchronous discussion.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104334#-:-NXLY7sM3N4UfwjPsot4:b-3vdg2w)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocator2/allocator.go` line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104334#-NXGbWDa4OjivAY9yc-t:-NXLEs1IBzAVtkTEZQ7R:b-eh2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/1454a398e28acaeee062d4878a20383e2f3bd467/pkg/kv/kvserver/allocator/allocator2/allocator.go#L33)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Not an important point -

Would `AddStore` fail if the store descriptor's node ID wasn't previously added with `AddNodeID(..)`? 

Likewise, would `ChangeStore` fail if the store wasn't previously added via `AddStore(..)`?

I'm wondering what does the separation give us, over say `SetStore` (in place of `AddStore` and `AddNodeID`) which handles the node initialization as well.
</blockquote></details>

Good point. I was mirroring what was initially done in `clusterState`, and looking at it again, there isn't any data-structural benefit. I've cleaned this up.
___
*[`pkg/kv/kvserver/allocator/allocator2/allocator.go` line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104334#-NXGduYT4PXpv0vX2eIy:-NXLFH6rAXWUTy0x-u_u:bbpu3lf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1454a398e28acaeee062d4878a20383e2f3bd467/pkg/kv/kvserver/allocator/allocator2/allocator.go#L59)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

The gossip info origin timestamp isn't readily available outside the internal gossip state. So we'd either need to add a timestamp field to the `StoreDescriptor` (or start using a new) proto or update to expose the origin TS.

https://github.com/cockroachdb/cockroach/blob/bc460496d54fe51bfe4effc9e8b828d2e25318eb/pkg/gossip/gossip.proto#L140-L141

</blockquote></details>

Since it's already there in the gossip proto, I think we should try to expose it. It's all our code after all.

(from sync discussion)
- Default gossip with up-to-date load information is every 10s.
- There is additional gossip when lease count and range count have changed by higher than some threshold. This has stale load information, and up to date range and leaseholder information, so this message is partially stale. It makes the problem described in https://github.com/cockroachdb/cockroach/issues/93532 worse. The main benefit of this additional gossip is that it prevents a thundering herd of lease transfers to a store. We tentatively decided that allocator2 will ignore such partially stale messages, and that we will handle the thundering herd problem of lease transfers to a store due to distributed allocators via a distributed throttling mechanism.
___
*[`pkg/kv/kvserver/allocator/allocator2/allocator.go` line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104334#-NXGcc9w2kMZReGABI6I:-NXLFoDu9uCqAPCfgim2:b-p64u4u) ([raw file](https://github.com/cockroachdb/cockroach/blob/1454a398e28acaeee062d4878a20383e2f3bd467/pkg/kv/kvserver/allocator/allocator2/allocator.go#L71)):*
> What we are missing is follower non-raft CPU

Can we start with 0? I assume we don't have this in the current allocator either.
My understanding is that `StoreDescriptor` is being gossiped (looking at `StorePool.storeGossipUpdate`), and I don't see any per-range information in the contained `StoreCapacity`. Is my understanding correct?

I updated the code comment here.
___
*[`pkg/kv/kvserver/allocator/allocator2/allocator.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104334#-NXGi6s_-Y31nW6JrlYR:-NXLKY0nE8b05PkDMMfp:b-hjuous) ([raw file](https://github.com/cockroachdb/cockroach/blob/1454a398e28acaeee062d4878a20383e2f3bd467/pkg/kv/kvserver/allocator/allocator2/allocator.go#L92)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Did you have any thoughts on the distributed allocators responsibility for rebalancing? 

The options I've been thinking of are:

1. Each allocator is responsible for keeping the store its on out of overload/above means.
2. Each allocator is responsible for keeping every store in the cluster out of overload/above means.

Then the legal changes an allocator could issue:

A. Allocator can issue changes for all ranges where it has the range leaseholder for.
B. Allocator can issue changes for all ranges where it has a replica for.
C. Allocator can issue changes for all ranges.

The store rebalancer does 1A currently.
The replicate queue (inc rebalancing) does 2A currently.

In 1A, stores which have no leaseholders won't be effectively dealt (happens today).
</blockquote></details>

(from sync discussion)
- We will do both 1A and 2A, and the replicateQueue will not do rebalancing when allocator2 is configured.
- Some more details about replicateQueue, related to rebalancing:
  - Can take 10min or longer to make a pass through all ranges and call `shouldQueue`. When large number of ranges (common in large production clusters), this can be significantly longer than 10min. If no recovery action is needed, will fall into the `AllocatorConsiderRebalance` path. In this case will do a dry-run and if it gets a target, it will queue.
  - Consequently, `replicateQueue` can lag significantly in rebalancing to relieve overload on other stores, and allocator2 should be able to react faster.
  - The distributed throttling scheme mentioned earlier for lease transfers will also be used here to reduce the probability of a thundering herd of transfers.

Updated the code comment. 
___
*[`pkg/kv/kvserver/allocator/allocator2/allocator.go` line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104334#-NXGkBM99PQSDIDxm6i4:-NXLgLlFCWOSrTCN6ZCw:b5670sf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1454a398e28acaeee062d4878a20383e2f3bd467/pkg/kv/kvserver/allocator/allocator2/allocator.go#L112)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

> should we use load?

I'm not sure if there are any callers which would benefit.

StoreRebalancer always provides the final LH.
MergeQueue doesn't provide the final LH, but probably doesn't matter since the RHS LH will go away soon.

I don't know about any other uses in the code.


</blockquote></details>

Updated to say that load is not used.
___
*[`pkg/kv/kvserver/allocator/allocator2/allocator.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104334#-NXFhcpe5T-8dRU-nq_j:-NXLgYiVA5SiRANIqVGs:b669eu7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1454a398e28acaeee062d4878a20383e2f3bd467/pkg/kv/kvserver/allocator/allocator2/allocator.go#L119)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

ack. Is this supposed to be `replica_command.go`?
</blockquote></details>

Ah yes. Fixed.
___
*[`pkg/kv/kvserver/allocator/allocator2/allocator.go` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104334#-NXGoaNq1V_OAgjAWWMt:-NXLh8hc1YV4DTYxrLfo:b-xv6fzs) ([raw file](https://github.com/cockroachdb/cockroach/blob/1454a398e28acaeee062d4878a20383e2f3bd467/pkg/kv/kvserver/allocator/allocator2/allocator.go#L122)):*
> `relocateRanges` issues DB commands like `AdminTransferLease` and `AdminChangeReplicas` instead of local leaseholder variants like `changeReplicasImpl`.

Does allocator2 need to be involved in `AdminTransferLease` -- I am guessing not since there isn't any decision to be made here other than doing the thing?
Regarding `AdminChangeReplicasRequest`, it seems to be called from 2 places, (a) internally, as the enactment steps for `AdminRelocateRange`, and (b) externally by `sql.relocateRange`. Does (b) need any interaction with allocator2 or has the caller specified the exact sequence of changes?

> I think we do need to know the current leaseholder and we don't need to keep the leaseholder on the local store until the end.

I updated the comment to say that a store on this node does not need to be the leaseholder. And added a `SpanConfig` parameter for the same reason.
___
*[`pkg/kv/kvserver/allocator/allocator2/allocator.go` line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104334#-NXLlB0l97C3yVnsSzjI:-NXLlB0l97C3yVnsSzjJ:bo2x035) ([raw file](https://github.com/cockroachdb/cockroach/blob/1454a398e28acaeee062d4878a20383e2f3bd467/pkg/kv/kvserver/allocator/allocator2/allocator.go#L151)):*
> ```Go
> 	// TODO(sumeer):
> 	// - understand what is really happening as a consequence of
> 	//   ScorerOptionsForScatter.
> ```

Let's discuss this in our next synchronous session.
___
*[`pkg/kv/kvserver/allocator/allocator2/messages.go` line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104334#-NXGnQf_-9aKdaeBE3Qn:-NXLkczK4OypGJX23K4_:b-kcwe2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/1454a398e28acaeee062d4878a20383e2f3bd467/pkg/kv/kvserver/allocator/allocator2/messages.go#L89)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

ack - I've been struggling a bit with this.
</blockquote></details>

Ack. I think it will be easy to make such improvements once we have something working end-to-end.

**Comment by sumeerbhola** [comment]
For some reason github is not picking up the latest commit in the branch, to show in this PR. I'll wait for some time to see if it fixes itself.

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104334#-:-NXQJunG3Jmoi9SNXmB2:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/allocator/allocator2/allocator.go` line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104334#-NXGcc9w2kMZReGABI6I:-NXQFEqD7giRijahjTrH:b-kztkun) ([raw file](https://github.com/cockroachdb/cockroach/blob/1454a398e28acaeee062d4878a20383e2f3bd467/pkg/kv/kvserver/allocator/allocator2/allocator.go#L71)):*
> Can we start with 0?

Yup sgtm.

> My understanding is that `StoreDescriptor` is being gossiped (looking at `StorePool.storeGossipUpdate`), and I don't see any per-range information in the contained `StoreCapacity`. Is my understanding correct?

Understanding is correct. No per-range information in StoreCapacity

The current system never knows about a range's non-leaseholder replica load. 
___
*[`pkg/kv/kvserver/allocator/allocator2/allocator.go` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104334#-NXGoaNq1V_OAgjAWWMt:-NXQGjiX7drKrIqDbQ0V:b-hi985d) ([raw file](https://github.com/cockroachdb/cockroach/blob/1454a398e28acaeee062d4878a20383e2f3bd467/pkg/kv/kvserver/allocator/allocator2/allocator.go#L122)):*
> Does allocator2 need to be involved in `AdminTransferLease` -- I am guessing not since there isn't any decision to be made here other than doing the thing?

It doesn't need to be involved.

> [..] (b) externally by `sql.relocateRange`. Does (b) need any interaction with allocator2 or has the caller specified the exact sequence of changes?

No interaction necessary with allocator2. `changeReplicas` does have a dependency on the storepool (currently) for determining live and dead replicas used [here](https://github.com/cockroachdb/cockroach/blob/fdf04ffe5403daab580ab0a6fb0ad407ccc23c2e/pkg/kv/kvserver/replica_command.go#L2380-L2382). 


The caller does not specify the exact sequence of changes though, it is enacted in a symmetric priority to the allocator action (replicate queue) priority.

https://github.com/cockroachdb/cockroach/blob/fdf04ffe5403daab580ab0a6fb0ad407ccc23c2e/pkg/kv/kvserver/replica_command.go#L1038-L1043
___
*[`pkg/kv/kvserver/allocator/allocator2/allocator.go` line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104334#-NXLlB0l97C3yVnsSzjI:-NXQJwM77o3dveuuuM9z:brxp9sq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1454a398e28acaeee062d4878a20383e2f3bd467/pkg/kv/kvserver/allocator/allocator2/allocator.go#L151)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Let's discuss this in our next synchronous session.
</blockquote></details>

Sounds good.
___
*[`pkg/kv/kvserver/allocator/allocator2/allocator.go` line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104334#-NXQEDiu4FCJ59pw55Z3:-NXQEDiu4FCJ59pw55Z4:b-gf4mze) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1b7ea257473d273bab860043f885c645f99b70f/pkg/kv/kvserver/allocator/allocator2/allocator.go#L43)):*
> ```Go
> 	// stores.
> 	//
> 	// TODO(sumeer): do we need a RemoveStore(store roachpb.StoreDescriptor)
> ```

I imagine the only time a store would be removed is when the membership record for the node its on transitions from decommissioning -> decommissioned

It isn't possible to decommission just a store afaik, only nodes.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104334)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocator2/allocator.go` line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104334#-NXGcc9w2kMZReGABI6I:-NXRFCNZAsvn_XicR2Fz:b-qhq769) ([raw file](https://github.com/cockroachdb/cockroach/blob/1454a398e28acaeee062d4878a20383e2f3bd467/pkg/kv/kvserver/allocator/allocator2/allocator.go#L71)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

> Can we start with 0?

Yup sgtm.

> My understanding is that `StoreDescriptor` is being gossiped (looking at `StorePool.storeGossipUpdate`), and I don't see any per-range information in the contained `StoreCapacity`. Is my understanding correct?

Understanding is correct. No per-range information in StoreCapacity

The current system never knows about a range's non-leaseholder replica load. 
</blockquote></details>

Ack. Left the comment in place.
___
*[`pkg/kv/kvserver/allocator/allocator2/allocator.go` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104334#-NXGoaNq1V_OAgjAWWMt:-NXRu1RDAXl7p8k73kFl:bc1uafa) ([raw file](https://github.com/cockroachdb/cockroach/blob/1454a398e28acaeee062d4878a20383e2f3bd467/pkg/kv/kvserver/allocator/allocator2/allocator.go#L122)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

> Does allocator2 need to be involved in `AdminTransferLease` -- I am guessing not since there isn't any decision to be made here other than doing the thing?

It doesn't need to be involved.

> [..] (b) externally by `sql.relocateRange`. Does (b) need any interaction with allocator2 or has the caller specified the exact sequence of changes?

No interaction necessary with allocator2. `changeReplicas` does have a dependency on the storepool (currently) for determining live and dead replicas used [here](https://github.com/cockroachdb/cockroach/blob/fdf04ffe5403daab580ab0a6fb0ad407ccc23c2e/pkg/kv/kvserver/replica_command.go#L2380-L2382). 


The caller does not specify the exact sequence of changes though, it is enacted in a symmetric priority to the allocator action (replicate queue) priority.

https://github.com/cockroachdb/cockroach/blob/fdf04ffe5403daab580ab0a6fb0ad407ccc23c2e/pkg/kv/kvserver/replica_command.go#L1038-L1043


</blockquote></details>

Thanks for the pointers. IIUC, that issue is the main reason we still have some value-add from `AdminRelocateRange`, and can't simply pass all that information to a single `AdminChangeReplicasRequest`.
___
*[`pkg/kv/kvserver/allocator/allocator2/allocator.go` line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104334#-NXQEDiu4FCJ59pw55Z3:-NXRF59G5jKDkze_SlMx:b5lrt43) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1b7ea257473d273bab860043f885c645f99b70f/pkg/kv/kvserver/allocator/allocator2/allocator.go#L43)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

I imagine the only time a store would be removed is when the membership record for the node its on transitions from decommissioning -> decommissioned

It isn't possible to decommission just a store afaik, only nodes.
</blockquote></details>

Ack. Removed the todo.

**Comment by sumeerbhola** [comment]
bors r=kvoli

**Pull request merged**
