### PR TITLE
sql: disable interleaved tables by default

### LINKED ISSUE #58628: sql: add interleave table cluster setting; error on creation if unset
Add a new cluster setting, called `sql.defaults.interleaved_tables.enabled`, that when set to false causes any DDLs that add new interleaved tables or indexes to fail with an error pointing to the deprecation documentation.

When this setting is set to true, any such DDLs should have the current behavior (returning a NOTICE to the user explaining the deprecation).

This relates to #52009.

### PR DESCRIPTION
**Pull request by jordanlewis**
This commit adds a new cluster setting,
sql.defaults.interleaved_tables.enabled, which controls whether or not
new interleaved tables or indexes can be created. This is disabled by
default.

Closes #58628.

cc @vy-ton 

Release note (sql change): creation of interleaved tables and indexes is
now disabled by default. They can be re-enabled temporarily by running
SET CLUSTER SETTING sql.defaults.interleaved_tables.enabled=true.

### CODE REVIEW

**Review by postamar — COMMENTED** [review]
> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59248)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/ccl/logictestccl/testdata/logic_test/partitioning, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59248#-MR_t3Ch7C0cVzhl_TiQ:-MR_t3Ci4YQY0xhqch9h:b5yjf83) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c6b581b1d8dd0e7c2fcfe3613b5517e35f87678/pkg/ccl/logictestccl/testdata/logic_test/partitioning#L101)):*
> ```
> 
> statement ok
> SET CLUSTER SETTING sql.defaults.interleaved_tables.enabled = true
> ```

Seeing how a whole load of unit tests are failing in CI because this flag isn't set, perhaps instead of having to set it explicitly in all tests, the flag could be set by default when starting a test server?
___
*[pkg/sql/exec_util.go, line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59248#-MR_sCdmEtLpvTRiGSkg:-MR_sCdmEtLpvTRiGSkh:b-cpom6g) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c6b581b1d8dd0e7c2fcfe3613b5517e35f87678/pkg/sql/exec_util.go#L255)):*
> ```Go
> var interleavedTablesEnabled = settings.RegisterBoolSetting(
> 	"sql.defaults.interleaved_tables.enabled",
> 	"allows creation of interleaved tables",
> ```

"allows creation of interleaved tables and indexes" perhaps?

**Comment by jordanlewis** [comment]
Good call on the default, did that.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59248#-:-MRaFYyhEYrMs6iJnVuT:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @postamar)

___
*[pkg/sql/logictest/testdata/logic_test/interleaved, line 466 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59248#-MRaFHGQ2nu7qReBK3Yv:-MRaFHGQ2nu7qReBK3Yw:b-p4ce8f) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cc7971606ea44e28f8a1adc97b84e056e29fd4d/pkg/sql/logictest/testdata/logic_test/interleaved#L466)):*
> ```
> 
> statement ok
> SET CLUSTER SETTING sql.defaults.interleaved_tables.enabled = false
> ```

[nit] shouldn't be necessary anymore

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59248)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @postamar, and @RaduBerinde)

___
*[pkg/sql/logictest/testdata/logic_test/interleaved, line 466 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59248#-MRaFHGQ2nu7qReBK3Yv:-MRaJQHqAtqWS2JABz0I:b-c2he3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cc7971606ea44e28f8a1adc97b84e056e29fd4d/pkg/sql/logictest/testdata/logic_test/interleaved#L466)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] shouldn't be necessary anymore
</blockquote></details>

We still need this - this last part is testing that the error messages are properly produced. The code is currently leaving interleaved tables *on* by default in test servers so we don't have to change every test.

**Review by thoszhang — COMMENTED** [review]
> Reviewed 2 of 17 files at r1, 16 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59248)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/create_index.go, line 381 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59248#-MRaYjlS8sxATUrAPMvn:-MRaYjlS8sxATUrAPMvo:bvypgal) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cc7971606ea44e28f8a1adc97b84e056e29fd4d/pkg/sql/create_index.go#L381)):*
> ```Go
> 
> var interleavedTableDisabledError = errors.WithIssueLink(
> 	pgnotice.Newf("interleaved tables and indexes are disabled, and will be removed in 21.2. To re-enable temporarily, "+
> ```

nit: The capitalization is inconsistent here. Should these be full sentences, or not? Maybe @vy-ton has an opinion.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/logictest/testdata/logic_test/interleaved, line 466 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59248#-MRaFHGQ2nu7qReBK3Yv:-MRab7KT3ZNtvn3mqao8:b-f4pd9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cc7971606ea44e28f8a1adc97b84e056e29fd4d/pkg/sql/logictest/testdata/logic_test/interleaved#L466)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

We still need this - this last part is testing that the error messages are properly produced. The code is currently leaving interleaved tables *on* by default in test servers so we don't have to change every test.
</blockquote></details>

Sorry, I misread it.

**Review by vy-ton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59248)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @lucy-zhang)

___
*[pkg/sql/create_index.go, line 376 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59248#-MRabNkG5tdwuhJDQT20:-MRabNkG5tdwuhJDQT21:b2y9adn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cc7971606ea44e28f8a1adc97b84e056e29fd4d/pkg/sql/create_index.go#L376)):*
> ```Go
> 
> var interleavedTableDeprecationError = errors.WithIssueLink(
> 	pgnotice.Newf("interleaved tables and indexes are deprecated in 20.2 and will be removed in 21.2"),
> ```

Can we make this 
```
NOTICE: Interleaved tables and interleaved indexes are deprecated as of 20.2 and will be removed in 21.2.
HINT: See: https://go.crdb.dev/issue-v/52009/v20.2
```
___
*[pkg/sql/create_index.go, line 381 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59248#-MRaYjlS8sxATUrAPMvn:-MRab5rl5D_gjQqFb15S:bwdgjor) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cc7971606ea44e28f8a1adc97b84e056e29fd4d/pkg/sql/create_index.go#L381)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

nit: The capitalization is inconsistent here. Should these be full sentences, or not? Maybe @vy-ton has an opinion.
</blockquote></details>

```
ERROR: By default, interleaved tables and interleaved indexes are disabled with the sql.defaults.interleaved_tables.enabled cluster setting. Note that interleaved tables and interleaved indexes will be removed in a future release. For details, see https://www.cockroachlabs.com/docs/releases/v20.2.0#deprecations
```

We should use this message that Eric reviewed to be consistent with our docs

**Review by thoszhang — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59248)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis)

**Pull request merged**
