### PR TITLE
roachprod: support managing shared process virtual clusters

### PR DESCRIPTION
**Pull request by renatolabs**
This PR adds support for shared process virtual clusters using `start-sql` and `stop-sql`; previously, these subcommands would always create separate process virtual clusters. After this PR, `start-sql` will create shared process tenants by default. Alternatively, the `--external-cluster` command line flag can be used to indicate where the separate processes should be deployed. Similarly, `stop-sql` may be used to stop separate process virtual clusters, as before, by killing the corresponding OS process; or shared process virtual clusters by using SQL (`STOP SERVICE`).

A few other changes introduced in this PR, done to support this work:

* Made `ExecSQL` more flexible;
* Fixed a bug in `pgurl`, where we would include the virtual cluster name in the connection url returned by `roachprod pgurl`. This is not allowed since the URL pointed to the SQL server process, which does not handle that option.
* Remove ability to create tenants by specifying a tenant ID. We are now creating tenants with `CREATE TENANT` instead of `crdb_internal.create_tenant`. The tenant ID is computed automatically and used when starting the cockroach process for separate process deployments.

Epic: none

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
Apologies for the relatively large PR; it's hard to break it down. Creating and starting virtual clusters via SQL basically requires us to stop referencing them by ID as before, as we no longer have control of the `id` column in `system.tenants`.

**Review by herkolategan — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111533)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong and @renatolabs)

___
*[`pkg/cmd/roachprod/main.go` line 575 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111533#-Nh2JFF_-Rg7M5hIeAlE:-Nh2JFF_-Rg7M5hIeAlF:b-1e52ux) ([raw file](https://github.com/cockroachdb/cockroach/blob/2775926403c56e118c89631543d5d98ee0e23ef2/pkg/cmd/roachprod/main.go#L575)):*
> ```Go
> 		// clusters. We do not expose the functionality of choosing a
> 		// specific port for separate-process deployments; for
> 		// shared-process, the port always be based on the system tenant
> ```

Nit: the port will always...
___
*[`pkg/roachprod/install/cluster_synced.go` line 463 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111533#-Nh2WdXa6sIkinyEBWxT:-Nh2WdXa6sIkinyEBWxU:b4vdbqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/2775926403c56e118c89631543d5d98ee0e23ef2/pkg/roachprod/install/cluster_synced.go#L463)):*
> ```Go
> 	} else {
> 		res, err := c.ExecSQL(ctx, l, c.Nodes[:1], "", 0, []string{
> 			"-e", fmt.Sprintf("ALTER TENANT '%s' STOP SERVICE", virtualClusterName),
> ```

"ALTER VIRTUAL CLUSTER" may work here.
___
*[`pkg/roachprod/install/cockroach.go` line 234 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111533#-Nh2M8XyB0cqg48gmk4M:-Nh2M8XyB0cqg48gmk4N:bh2195) ([raw file](https://github.com/cockroachdb/cockroach/blob/2775926403c56e118c89631543d5d98ee0e23ef2/pkg/roachprod/install/cockroach.go#L234)):*
> ```Go
> 		for _, serviceType := range []ServiceType{ServiceTypeSQL, ServiceTypeUI} {
> 			if _, ok := serviceMap[sharedProcessVirtualClusterNode][serviceType]; !ok {
> 				servicesToRegister = append(servicesToRegister, ServiceDesc{
> ```

I think we still need to provide the port here for the storage / system layer, as this will get registered against DNS with port 0, unless I'm missing something?
___
*[`pkg/roachprod/install/cockroach.go` line 969 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111533#-Nh2PeEaAuFB5_4sDGYK:-Nh2PeEaAuFB5_4sDGYL:b-2hmkn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2775926403c56e118c89631543d5d98ee0e23ef2/pkg/roachprod/install/cockroach.go#L969)):*
> ```Go
> 	var tenantPrefix string
> 	if virtualCluster != "" && virtualCluster != SystemInterfaceName {
> 		tenantPrefix = fmt.Sprintf("ALTER TENANT '%s' ", virtualCluster)
> ```

I think "ALTER VIRTUAL CLUSTER" also works.
___
*[`pkg/roachprod/install/cockroach.go` line 981 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111533#-Nh2OXTOBEfPgSGj8aqG:-Nh2OXTOBEfPgSGj8aqH:b1tvpij) ([raw file](https://github.com/cockroachdb/cockroach/blob/2775926403c56e118c89631543d5d98ee0e23ef2/pkg/roachprod/install/cockroach.go#L981)):*
> ```Go
> 	var clusterSettingsString string
> 	for name, value := range clusterSettings {
> 		clusterSettingsString += fmt.Sprintf("%sSET CLUSTER SETTING %s = '%s';\n", tenantPrefix, name, value)
> ```

Nice catch on the cluster settings!
___
*[`pkg/roachprod/install/cockroach.go` line 1156 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111533#-Nh2PljdAMSigMzEnuwA:-Nh2PljdAMSigMzEnuwB:bm5pbgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2775926403c56e118c89631543d5d98ee0e23ef2/pkg/roachprod/install/cockroach.go#L1156)):*
> ```Go
> 		// If the virtual cluster metadata does not exist yet, create it.
> 		virtualClusterStmts = append(virtualClusterStmts,
> 			fmt.Sprintf("CREATE TENANT '%s'", startOpts.VirtualClusterName),
> ```

Alias "CREATE VIRTUAL CLUSTER" may also work.
___
*[`pkg/roachprod/install/cockroach.go` line 1161 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111533#-Nh2PvPA6QK-HcfNq633:-Nh2PvPA6QK-HcfNq634:bh1eyle) ([raw file](https://github.com/cockroachdb/cockroach/blob/2775926403c56e118c89631543d5d98ee0e23ef2/pkg/roachprod/install/cockroach.go#L1161)):*
> ```Go
> 
> 	virtualClusterStmts = append(virtualClusterStmts, fmt.Sprintf(
> 		"ALTER TENANT '%s' START SERVICE %s",
> ```

Same as above, I think "ALTER VIRTUAL CLUSTER" is supported.
___
*[`pkg/roachprod/install/services.go` line 181 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111533#-Nh2UN2x5oQJoBgP3hfv:-Nh2UN2x5oQJoBgP3hfw:b8kprlk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2775926403c56e118c89631543d5d98ee0e23ef2/pkg/roachprod/install/services.go#L181)):*
> ```Go
> 	services, err := c.DiscoverServices(
> 		ctx, virtualClusterName, serviceType,
> 		ServiceNodePredicate(node), ServiceModePredicate(ServiceModeExternal), ServiceInstancePredicate(sqlInstance),
> ```

Not sure if this matters here and just an observation; but since a virtual cluster (tenant) must exclusively run in shared or external mode, and is not allowed both at the same time I'm not sure if the predicate has an effect, but I could be missing some logic here. It might be a result of shared processes not having the port set requiring the more intensive branch logic below?
___
*[`pkg/roachprod/install/services.go` line 217 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111533#-Nh2VpvE3eL74ktbk8e8:-Nh2VpvE3eL74ktbk8e9:bcgalic) ([raw file](https://github.com/cockroachdb/cockroach/blob/2775926403c56e118c89631543d5d98ee0e23ef2/pkg/roachprod/install/services.go#L217)):*
> ```Go
> 			// interface service.
> 			if len(services) > 0 {
> 				services[0].Port = systemServices[0].Port
> ```

Any reason for not setting the port when register a shared process service? I noticed it above, and was unsure of the reasoning. In a sense the service descriptors were designed to allow semi-transparent listing and the mode was included in the service registry so that the logic for including the cluster option (virtual cluster name) in pgurl is possible.

**Review by herkolategan — COMMENTED** [review]
Nice work! I left a few questions for my own understanding, and some minor improvements possibly.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111533#-:-Nh2XIEw5-IGhpq8uday:bz3n4h1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong and @renatolabs)

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111533)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong and @herkolategan)

___
*[`pkg/cmd/roachprod/main.go` line 575 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111533#-Nh2JFF_-Rg7M5hIeAlE:-Nh3g37_EC2rhJOXOg-Y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2775926403c56e118c89631543d5d98ee0e23ef2/pkg/cmd/roachprod/main.go#L575)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

Nit: the port will always...
</blockquote></details>

Done.
___
*[`pkg/roachprod/install/cluster_synced.go` line 463 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111533#-Nh2WdXa6sIkinyEBWxT:-Nh3g46Z1YGQB6heX6Wk:bl4mhmb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2775926403c56e118c89631543d5d98ee0e23ef2/pkg/roachprod/install/cluster_synced.go#L463)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

"ALTER VIRTUAL CLUSTER" may work here.
</blockquote></details>

It does work; the reason l chose to use `ALTER TENANT` is because I want this to work in upgrade tests (23.1+), where that syntax won't be available.
___
*[`pkg/roachprod/install/cockroach.go` line 234 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111533#-Nh2M8XyB0cqg48gmk4M:-Nh3gSSh886Ist2O3Rtd:bdtttf5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2775926403c56e118c89631543d5d98ee0e23ef2/pkg/roachprod/install/cockroach.go#L234)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

I think we still need to provide the port here for the storage / system layer, as this will get registered against DNS with port 0, unless I'm missing something?
</blockquote></details>

The port is left at 0 intentionally. There's no safe way to set a port for a shared-process virtual cluster since it depends on the node. For now, the approach is as follows: when a shared process virtual cluster is created, we create a single service descriptor, with fixed values for node (`sharedProcessVirtualClusterNode`), and Port (`0`). During discovery time, if we find that the service is shared, we inherit these properties from the corresponding system service.

Consider the following:

* User starts system interface on nodes 1,2
* User creates shared-process virtual cluter
* User starts system interface on nodes 3,4

Now, if I want to connect to the virtual cluster through node 3, how do I route it? If we just use the information available during creation time, we won't be able to find the proper URL. To work around this type of scenario, handling of this logic exists during `DiscoverServices`.
___
*[`pkg/roachprod/install/services.go` line 181 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111533#-Nh2UN2x5oQJoBgP3hfv:-Nh3h5CK9X91ZcW7ZwZR:b-kdjpzm) ([raw file](https://github.com/cockroachdb/cockroach/blob/2775926403c56e118c89631543d5d98ee0e23ef2/pkg/roachprod/install/services.go#L181)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

Not sure if this matters here and just an observation; but since a virtual cluster (tenant) must exclusively run in shared or external mode, and is not allowed both at the same time I'm not sure if the predicate has an effect, but I could be missing some logic here. It might be a result of shared processes not having the port set requiring the more intensive branch logic below?
</blockquote></details>

See comment I made on the "port 0" thread. I also made this code a little simpler after some reflection and added some comments. Let me know if it's clearer of if there's still something that you feel should be better handled or documented.

In the near future, I want to handle the TODO you left below and return an error if there are no services to be discovered. We can't do that at the moment because there are still tests (`c2c`) that create virtual clusters via SQL directly, and therefore there won't be any service descriptors for them.
___
*[`pkg/roachprod/install/services.go` line 217 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111533#-Nh2VpvE3eL74ktbk8e8:-Nh3hWKJ9aI3HxOWJeI7:b-k42vrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2775926403c56e118c89631543d5d98ee0e23ef2/pkg/roachprod/install/services.go#L217)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

Any reason for not setting the port when register a shared process service? I noticed it above, and was unsure of the reasoning. In a sense the service descriptors were designed to allow semi-transparent listing and the mode was included in the service registry so that the logic for including the cluster option (virtual cluster name) in pgurl is possible.
</blockquote></details>

See comments above. Let me know if that makes sense.

**Review by herkolategan — APPROVED** [review]
Thanks for the responses!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111533#-:-Nh6ZbsyDfy9HIy2PfXB:bjkr0cn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong and @renatolabs)

___
*[`pkg/roachprod/install/cluster_synced.go` line 463 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111533#-Nh2WdXa6sIkinyEBWxT:-Nh6YgACA-PmkfSmTY91:b-r26xcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2775926403c56e118c89631543d5d98ee0e23ef2/pkg/roachprod/install/cluster_synced.go#L463)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

It does work; the reason l chose to use `ALTER TENANT` is because I want this to work in upgrade tests (23.1+), where that syntax won't be available.
</blockquote></details>

Ah good catch, that makes sense.
___
*[`pkg/roachprod/install/cockroach.go` line 234 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111533#-Nh2M8XyB0cqg48gmk4M:-Nh6ZTuu5C-9DqU4p6_P:b-ff8bf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2775926403c56e118c89631543d5d98ee0e23ef2/pkg/roachprod/install/cockroach.go#L234)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

The port is left at 0 intentionally. There's no safe way to set a port for a shared-process virtual cluster since it depends on the node. For now, the approach is as follows: when a shared process virtual cluster is created, we create a single service descriptor, with fixed values for node (`sharedProcessVirtualClusterNode`), and Port (`0`). During discovery time, if we find that the service is shared, we inherit these properties from the corresponding system service.

Consider the following:

* User starts system interface on nodes 1,2
* User creates shared-process virtual cluter
* User starts system interface on nodes 3,4

Now, if I want to connect to the virtual cluster through node 3, how do I route it? If we just use the information available during creation time, we won't be able to find the proper URL. To work around this type of scenario, handling of this logic exists during `DiscoverServices`.
</blockquote></details>

Right, I agree the underlying storage cluster port vs. shared service port is a bit of a conundrum. In a sense we can drop using the weight field as the qualifier for indicating a shared process and infer it from port 0. But we can do that in another PR, as it will likely also cause versioning issues with roachprod.

**Review by renatolabs — COMMENTED** [review]
TFTR!

bors r=herkolategan

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111533#-:-Nh7Fi3P3bYsogXbqNrF:bqd8yzq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong and @herkolategan)

___
*[`pkg/roachprod/install/cockroach.go` line 234 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111533#-Nh2M8XyB0cqg48gmk4M:-Nh7FGyoBL74HhDKfKZ7:b-p3gadn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2775926403c56e118c89631543d5d98ee0e23ef2/pkg/roachprod/install/cockroach.go#L234)):*
> In a sense we can drop using the weight field as the qualifier for indicating a shared process and infer it from port 0

Hrmm true. I'll consider making this change in follow-up PRs, but it's also not too terrible to keep as-is IMO.

**Pull request merged**
