### PR TITLE
storage: add verbose split-queue logging

### PR DESCRIPTION
**Pull request by petermattis**
Add verbose split queue logging from tests.

See #29144

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
https://github.com/cockroachdb/cockroach/issues/30181 has logging that shows we split the first 15 ranges quickly and then nothing. The additional logging in this PR should take us a step further in debugging this. I want to verify that the final split is finishing and that the newly created range is being queued for another split. This will either point the finger at something going wrong in the split queue or somewhere in the post processing of the split.

**Review by benesch — APPROVED** [review]

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30395#-:-LMjVfxlBD3IiltwfWCL:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by petermattis** [comment]
bors r=nvanbenschoten,benesch

**Comment by petermattis** [comment]
TestGossipAlertsTable flake.

bors r=nvanbenschoten,benesch

**Pull request merged**
