### PR TITLE
storage: improve transaction deadline exceeded error msg

### PR DESCRIPTION
**Pull request by vivekmenezes**
Release note: None

### CODE REVIEW

**Comment by vivekmenezes** [comment]
I've seen these kinds of errors on the schema change tpcc test

```
TransactionStatusError: transaction deadline exceeded 1549942176.743100827,2 >= 1549942148.426669242,0, start-time = 1549942036.205106937,0 
```

which makes me think we still need to understand why some transactions are stalling for so long.

**Comment by tbg** [comment]
would you mind adding human-readable deltas? I was thinking something like

> TransactionStatusError: transaction deadline 1549942148.426669242,0 exceeded by 15ms (1549942176.743100827,2), original timestamp 15.2s ago (1549942036.205106937,0)

**Comment by vivekmenezes** [comment]
yes will do, is there anything else valuable like epochs?

**Comment by tbg** [comment]
yes, the Epoch would also be helpful. In fact, if this is only for our consumption, might as well print the whole transaction.

**Comment by vivekmenezes** [comment]
done

**Review by nvb — APPROVED** [review]
:lgtm: thanks for the improvement. You're still planning on getting the plan you proposed in https://github.com/cockroachdb/cockroach/issues/18684#issuecomment-435059379 into 19.1, right?

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34824#-:-LYY9Fnz2vDKifqT4QSY:b-93lsj8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @vivekmenezes)

___
*[pkg/roachpb/errors.go, line 431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34824#-LYY8Vl1DAcA0auTP_Qe:-LYY8Vl23ZdaA0vEiSbO:bnvmt3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c9b3bf9475ca8ff73da8ca808b90362a85d032/pkg/roachpb/errors.go#L431)):*
> ```Go
> // IsTxnDeadlineExceededErr returns an error if deadlineErr is not a
> // transaction deadline exceeded roachpb.TransactionStatusError.
> func IsTxnDeadlineExceededErr(deadlineErr error) error {
> ```

"Is..." isn't the right name for this since it returns an error. Consider something like `CheckTxnDeadlineExceededErr`.

**Pull request merged**
