### PR TITLE
sql: add interface for ForceRetryError for crdb_internal.force_retry

### PR DESCRIPTION
**Pull request by RichardJCai**
Start of effort for creating an interface whenever builtins need
to interact with KV.

Release note: None

### CODE REVIEW

**Comment by otan** [comment]
thanks for taking a look!

are we planning to make one of these interfaces for each `kv.Txn` builtin? seems burdensome to continually add these to `EvalContext`.  i wonder if naming it `kvinterfaces` is the right "abstraction" as well, since it still kind of breaks the abstraction of the `sql` package with the mentioning of `kv`. (idk maybe I'm saying pile onto `EvalPlanner`?! probably a bad idea though)

will we still need these after #80504 ?

**Comment by RichardJCai** [comment]
> thanks for taking a look!
> 
> are we planning to make one of these interfaces for each `kv.Txn` builtin? seems burdensome to continually add these to `EvalContext`. i wonder if naming it `kvinterfaces` is the right "abstraction" as well, since it still kind of breaks the abstraction of the `sql` package with the mentioning of `kv`. (idk maybe I'm saying pile onto `EvalPlanner`?! probably a bad idea though)
> 
> will we still need this after #80504 ?

Not necessarily, some things can be re-used. There's actually not too many of these we have to add at the moment.
Yeah `kvinterfaces` is probably not the right name, open to suggestions.

> will we still need this after #80504 ?
I guess it'll still be good to have this to make the boundaries clear. Either way I'll probably wait for that Pr to get merged before I continue with this.

**Review by otan — COMMENTED** [review]
sg!

**Comment by jordanlewis** [comment]
Is this worth reviving? I'm not familiiar with the context around it. If not, let's close it. @ajwerner @rafiss @otan

**Comment by rafiss** [comment]
This is part of a larger effort (e.g. https://github.com/cockroachdb/cockroach/pull/88787), and I think this PR has become a bit outdated, so I don't think we need this open.

**Pull request closed without merging**
