### PR TITLE
cloudstorage: Fix flaky test.

### LINKED ISSUE #50958: storage/cloudimpl/cloudimpltests: TestHttpGet failed
[(storage/cloudimpl/cloudimpltests).TestHttpGet failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2061897&tab=buildLog) on [master@b6e7102a76b696bde6acd9d5d0ffcccfbf37006b](https://github.com/cockroachdb/cockroach/commits/b6e7102a76b696bde6acd9d5d0ffcccfbf37006b):

```
E200703 06:29:45.011642 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": EOF (attempt 57)
E200703 06:29:45.023616 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": http: server closed idle connection (attempt 58)
E200703 06:29:45.034358 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": read tcp 127.0.0.1:46884->127.0.0.1:34731: read: connection reset by peer (attempt 59)
E200703 06:29:45.045145 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": EOF (attempt 60)
E200703 06:29:45.057081 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": http: server closed idle connection (attempt 61)
E200703 06:29:45.067813 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": EOF (attempt 62)
E200703 06:29:45.080717 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": EOF (attempt 63)
E200703 06:29:45.092190 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": EOF (attempt 64)
E200703 06:29:45.102753 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": EOF (attempt 65)
E200703 06:29:45.113304 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": http: server closed idle connection (attempt 66)
E200703 06:29:45.126640 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": read tcp 127.0.0.1:46900->127.0.0.1:34731: read: connection reset by peer (attempt 67)
E200703 06:29:45.137094 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": http: server closed idle connection (attempt 68)
E200703 06:29:45.149161 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": http: server closed idle connection (attempt 69)
E200703 06:29:45.160694 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": EOF (attempt 70)
E200703 06:29:45.171437 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": http: server closed idle connection (attempt 71)
E200703 06:29:45.184379 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": http: server closed idle connection (attempt 72)
E200703 06:29:45.197033 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": http: server closed idle connection (attempt 73)
E200703 06:29:45.209158 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": EOF (attempt 74)
E200703 06:29:45.220975 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": EOF (attempt 75)
E200703 06:29:45.233110 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": http: server closed idle connection (attempt 76)
E200703 06:29:45.243683 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": http: server closed idle connection (attempt 77)
E200703 06:29:45.253962 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": http: server closed idle connection (attempt 78)
E200703 06:29:45.264770 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": EOF (attempt 79)
E200703 06:29:45.277646 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": EOF (attempt 80)
E200703 06:29:45.288425 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": EOF (attempt 81)
E200703 06:29:45.300691 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": EOF (attempt 82)
E200703 06:29:45.313069 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": http: server closed idle connection (attempt 83)
E200703 06:29:45.324152 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": http: server closed idle connection (attempt 84)
E200703 06:29:45.334891 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": EOF (attempt 85)
E200703 06:29:45.346597 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": EOF (attempt 86)
E200703 06:29:45.359643 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": http: server closed idle connection (attempt 87)
E200703 06:29:45.371607 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": http: server closed idle connection (attempt 88)
E200703 06:29:45.382538 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": http: server closed idle connection (attempt 89)
E200703 06:29:45.395556 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": read tcp 127.0.0.1:46946->127.0.0.1:34731: read: connection reset by peer (attempt 90)
E200703 06:29:45.406408 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": http: server closed idle connection (attempt 91)
E200703 06:29:45.417644 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": EOF (attempt 92)
E200703 06:29:45.430526 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": EOF (attempt 93)
E200703 06:29:45.442402 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": http: server closed idle connection (attempt 94)
E200703 06:29:45.455244 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": read tcp 127.0.0.1:46956->127.0.0.1:34731: read: connection reset by peer (attempt 95)
E200703 06:29:45.466373 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": http: server closed idle connection (attempt 96)
E200703 06:29:45.478121 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": EOF (attempt 97)
E200703 06:29:45.491448 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": http: server closed idle connection (attempt 98)
E200703 06:29:45.502161 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": http: server closed idle connection (attempt 99)
E200703 06:29:45.513057 6436 storage/cloudimpl/http_storage.go:202  HTTP:Req error: err=retryable http error: Get "http://127.0.0.1:34731/something": EOF (attempt 100)
    TestHttpGet/read-2: http_storage_test.go:268: 
        	Error Trace:	http_storage_test.go:268
        	Error:      	Received unexpected error:
        	            	retryable http error: Get "http://127.0.0.1:34731/something": EOF
        	Test:       	TestHttpGet/read-2
    --- FAIL: TestHttpGet/read-2 (1.75s)

```

<details><summary>More</summary><p>
Parameters:

- TAGS=
- GOFLAGS=-race -parallel=2

```
make stressrace TESTS=TestHttpGet PKG=./pkg/storage/cloudimpl/cloudimpltests TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestHttpGet.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by miretskiy**
Fixes #50958

Make antagonistic TestHttpGet test less antogonistic by adding
a limit on how many times connection may be closed.

Release Notes: None

### CODE REVIEW

**Review by adityamaru — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51351)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @miretskiy)

___
*[pkg/storage/cloudimpl/cloudimpltests/http_storage_test.go, line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51351#-MC2VxYWDaJdW7Y2Pqdk:-MC2VxYWDaJdW7Y2Pqdl:b-7mhpva) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d3368eebb79a3fdc18f51a397381b709ae9c213/pkg/storage/cloudimpl/cloudimpltests/http_storage_test.go#L244)):*
> ```Go
> 				}
> 				for attempt, try := 0, retry.StartWithCtx(ctx, opts); attempt <
> 					cloudimpl.HTTPRetryOptions.MaxRetries && try.Next(); attempt++ {
> ```

Can we just set the MaxRetries in the opts struct above? I think try.Next() has an if condition checking that the currentAttempt < MaxRetries.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51351)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

___
*[pkg/storage/cloudimpl/cloudimpltests/http_storage_test.go, line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51351#-MC2VxYWDaJdW7Y2Pqdk:-MC2rOKx-Z_tN6kxajtB:b-ct3s6s) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d3368eebb79a3fdc18f51a397381b709ae9c213/pkg/storage/cloudimpl/cloudimpltests/http_storage_test.go#L244)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

Can we just set the MaxRetries in the opts struct above? I think try.Next() has an if condition checking that the currentAttempt < MaxRetries.
</blockquote></details>

Doh...   Done

**Pull request merged**
