### PR TITLE
concurrency: generalize lock promotion from Exclusive to Intent 

### PR DESCRIPTION
**Pull request by arulajmani**
Transactions commonly promote locks from Exclusive to Intent lock
strengths. Previously, this was handled as a special case -- requests
trying to promote would simply skip the lock and not add themselves in
the lock's wait queue.

This patch removes this special casing. Instead, requests trying to
promote are added as inactive waiters in the lock's wait queue.
Moreover, they sort before any other waiting requests, regardless of
arrival order. This isn't a functional change. However, it will
generalize better to Shared -> Exclusive/Intent promotion in the future
compared to our current structure.

Informs https://github.com/cockroachdb/cockroach/issues/110435

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
This is less invasive than I was imagining, which is a nice sign that the concepts we're introducing are slotting into place.

We should take a look at whether this has any impact on YCSB-A performance. It shouldn't, but it's difficult to predict the emergent behavior of some of these tweaks to locking interactions.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118484#-:-NqDk1-QD6FNDcxgwaU6:bauolov)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118484#-NqDfVBs7CmceHhJ2mYQ:-NqDfVBs7CmceHhJ2mYR:b-9c6ssd) ([raw file](https://github.com/cockroachdb/cockroach/blob/79e71ce0b1c5c80bb2cfc46d8e956db246c0b9ab/pkg/kv/kvserver/concurrency/lock_table.go#L654)):*
> ```Go
> 	// Note that we don't need to check newState.guardStrength as it's
> 	// automatically assigned when updating the state.
> 	return g.mu.state.kind == newState.kind && g.mu.state.txn.ID == newState.txn.ID &&
> ```

Can `newState.txn` be nil? The comment on the field indicates that it can be for certain `waitKind`s. Also, we have a nil check in `canPushWithPriority` (which maybe isn't necessary).
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1018 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118484#-NqDgJ7U0E37nzCT5QR7:-NqDgJ7U0E37nzCT5QR8:b6oftqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a467593d88b405b7ea10239dee40b0b57eabb0d/pkg/kv/kvserver/concurrency/lock_table.go#L1018)):*
> ```Go
> func makeQueueOrder(g *lockTableGuardImpl, kl *keyLocks) queueOrder {
> 	isPromoting := false
> 	if g.txn != nil && kl.isLockedBy(g.txn.ID) {
> ```

ignorable nit: `isPromoting := g.txn != nil && kl.isLockedBy(g.txn.ID)`
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1039 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118484#-NqDgYWc7wAEWun3Abug:-NqDgYWc7wAEWun3Abuh:bttmuqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a467593d88b405b7ea10239dee40b0b57eabb0d/pkg/kv/kvserver/concurrency/lock_table.go#L1039)):*
> ```Go
> 	}
> 	switch {
> 	case (o1.isPromoting && o2.isPromoting) || (!o1.isPromoting && !o2.isPromoting):
> ```

`o1.isPromoting == o2.isPromoting`

But also, this entire function could be more succinctly written as:
```go
if o1.isPromoting != o2.isPromoting {
    return o2.isPromoting
}
return o1.reqSeqNum > o2.reqSeqNum
```

Without the need for the "same request" branch, which is already handled below and just raises questions of whether `(o1.isPromoting != o2.isPromoting) && (o1.reqSeqNum == o2.reqSeqNum)` would ever be possible.

This more closely follows the usual pattern for a multi-field sort order.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2614 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118484#-NqDi1GaBfYU--CcVkbN:-NqDi1GaBfYU--CcVkbO:bmactb6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a467593d88b405b7ea10239dee40b0b57eabb0d/pkg/kv/kvserver/concurrency/lock_table.go#L2614)):*
> ```Go
> 
> 		if g.isSameTxn(lockHolderTxn) {
> 			// We should never get here if the lock is already held by another request
> ```

Is this comment now stale?
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2877 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118484#-NqDiZJjEkzbFBbotZHk:-NqDiZJjEkzbFBbotZHl:b37e4oj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a467593d88b405b7ea10239dee40b0b57eabb0d/pkg/kv/kvserver/concurrency/lock_table.go#L2877)):*
> ```Go
> 			return false
> 		}
> 		if g.txn != nil && qqg.guard.isSameTxn(g.txnMeta()) {
> ```

This is checking whether a queued request conflicts with another queued request from the same transaction, right? Was it needed for this PR? Not saying we shouldn't make the change, just trying to understand the motivation and effect of the code change.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 3305 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118484#-NqDjSWI4rkZEhuGiN08:-NqDjSWI4rkZEhuGiN09:b68a4ua) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a467593d88b405b7ea10239dee40b0b57eabb0d/pkg/kv/kvserver/concurrency/lock_table.go#L3305)):*
I recall we landed on the change you have here, but I don't recall exactly why.

> Clearing the lock holder impacts the sort order of the lock's wait queue, as requests that belong to a holder's transaction sort before requests that do not.

This doesn't feel entirely correct, as we're not actually modifying the `queueOrder`. But I seem to remember there being a hazard if we didn't do so. What was that?
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 3311 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118484#-NqDjDadD49-jSNSvMDL:-NqDjDadD49-jSNSvMDM:bu8ky5t) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a467593d88b405b7ea10239dee40b0b57eabb0d/pkg/kv/kvserver/concurrency/lock_table.go#L3311)):*
> ```Go
> 			// doing so. Instead, we could just remove the request from the wait
> 			// queue. This works in both the cases described above.
> 			kl.releaseLockingRequestsFromTxn(&up.Txn)
> ```

Do we need similar logic in the other two places where we call `clearLockHeldBy`?
___
*[`pkg/kv/kvserver/concurrency/testdata/lock_table/lock_promotion` line 17 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118484#-NqDkU3o3QcpxgcYGvVX:-NqDkU3o3QcpxgcYGvVY:b8ftj2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a467593d88b405b7ea10239dee40b0b57eabb0d/pkg/kv/kvserver/concurrency/testdata/lock_table/lock_promotion#L17)):*
> ```
> 
> # ------------------------------------------------------------------------------
> # Basic test form Exclusive -> Intent lock promotion when there are no waiters
> ```

`s/form/for/` here and below?
___
*[`pkg/kv/kvserver/concurrency/testdata/lock_table/lock_promotion` line 132 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118484#-NqDkoZiAuVRNiYC9dwK:-NqDkoZiAuVRNiYC9dwL:b-s6gqmr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a467593d88b405b7ea10239dee40b0b57eabb0d/pkg/kv/kvserver/concurrency/testdata/lock_table/lock_promotion#L132)):*
> ```
> # Ensure a request trying to promote from Exclusive -> Intent does not conflict
> # with any requests in the wait queue that belong to its own transaction. (If
> # they're already there they'll sort before it).
> ```

This relates to the `qqg.guard.isSameTxn(g.txnMeta())` case from above? Is it important that we handle this case this way?

**Review by arulajmani — COMMENTED** [review]
Addressed review comments. I'll give YCSB-A a spin on this and report back. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118484#-:-NrBYfqY1LAIOg5SuLk1:b-2zu08q)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118484#-NqDfVBs7CmceHhJ2mYQ:-Nr6pfaiChoto-0evoWC:b8lulc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/79e71ce0b1c5c80bb2cfc46d8e956db246c0b9ab/pkg/kv/kvserver/concurrency/lock_table.go#L654)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can `newState.txn` be nil? The comment on the field indicates that it can be for certain `waitKind`s. Also, we have a nil check in `canPushWithPriority` (which maybe isn't necessary).
</blockquote></details>

The comment on `waitKind` doesn't cover two cases -- `waitQueueMaxLengthExceeded` and `doneWaiting`. Looks like it's mistaken about the former -- `waitingState.txn` is also not-nil for `waitQueueMaxLengthExceeded`. I'll update the comment.

We handle state transitions to `doneWaiting` separately, using `updateStateToDoneWaitingLocked`. So it means that `newState.txn` can't be nil here. I'll add an assert here with a comment explaining all this, so that we don't have to rediscover this in the future.

----

I think all this also means the nil check in `canPushWithPriority` isn't needed, as it isn't called for the `doneWaiting` state.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1039 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118484#-NqDgYWc7wAEWun3Abug:-Nr75-BE44LytcbltwoO:b-71ug7r) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a467593d88b405b7ea10239dee40b0b57eabb0d/pkg/kv/kvserver/concurrency/lock_table.go#L1039)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`o1.isPromoting == o2.isPromoting`

But also, this entire function could be more succinctly written as:
```go
if o1.isPromoting != o2.isPromoting {
    return o2.isPromoting
}
return o1.reqSeqNum > o2.reqSeqNum
```

Without the need for the "same request" branch, which is already handled below and just raises questions of whether `(o1.isPromoting != o2.isPromoting) && (o1.reqSeqNum == o2.reqSeqNum)` would ever be possible.

This more closely follows the usual pattern for a multi-field sort order.
</blockquote></details>

This is much nicer, thanks!
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2614 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118484#-NqDi1GaBfYU--CcVkbN:-Nr75PMM6xRu7BClzvrB:b-msseel) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a467593d88b405b7ea10239dee40b0b57eabb0d/pkg/kv/kvserver/concurrency/lock_table.go#L2614)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this comment now stale?
</blockquote></details>

I think this comment still applies, though it was worded slightly incorrectly -- instead of saying ".. sufficient strength: read: less than or equal to ...)" it should have said "greater than or equal to ..."). Updated the comment. 
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2877 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118484#-NqDiZJjEkzbFBbotZHk:-Nr7K72mDNFkKdIUTqEY:b2m9q8v) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a467593d88b405b7ea10239dee40b0b57eabb0d/pkg/kv/kvserver/concurrency/lock_table.go#L2877)):*
> This is checking whether a queued request conflicts with another queued request from the same transaction, right?

Yeah, we're making sure we don't consider requests from the same transaction conflicting. None of the lock table tests break without this change, but that's only because we were lacking coverage for when this would be needed. I added a test case below -- it might be easier to explain why we need this change while referencing an example, so I'll just do it below.

All this being said, our randomized tests do fail if I comment this bit out.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 3305 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118484#-NqDjSWI4rkZEhuGiN08:-Nr7Nb7I8LWuZl1rDCaY:bivrhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a467593d88b405b7ea10239dee40b0b57eabb0d/pkg/kv/kvserver/concurrency/lock_table.go#L3305)):*
> This doesn't feel entirely correct, as we're not actually modifying the `queueOrder`. But I seem to remember there being a hazard if we didn't do so. What was that?

Sorry for the confusion here. This entire diff wasn't changed after switching to the `queueOrder` approach (and our discussion). The commentary (and the call to `releaseLockingRequestsFromTxn`) is outdated. 

> I recall we landed on the change you have here, but I don't recall exactly why.

We discussed this offline, and we don't actually need this anymore -- switching to the `queueOrder` approach prevents the validation failures this was initially trying to address. There's nothing wrong with calling `releaseLockingRequestsFromTxn` here, but there's no good reason to either. We decided to remove this call entirely.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 3311 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118484#-NqDjDadD49-jSNSvMDL:-NrBVWDK6HBQZk0-os9q:b-v3b8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a467593d88b405b7ea10239dee40b0b57eabb0d/pkg/kv/kvserver/concurrency/lock_table.go#L3311)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need similar logic in the other two places where we call `clearLockHeldBy`?
</blockquote></details>

Superseded by the comment above.
___
*[`pkg/kv/kvserver/concurrency/testdata/lock_table/lock_promotion` line 132 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118484#-NqDkoZiAuVRNiYC9dwK:-NrBVv5U8qUAMq1yUhwk:b-z0lxnz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a467593d88b405b7ea10239dee40b0b57eabb0d/pkg/kv/kvserver/concurrency/testdata/lock_table/lock_promotion#L132)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This relates to the `qqg.guard.isSameTxn(g.txnMeta())` case from above? Is it important that we handle this case this way?
</blockquote></details>

We discussed this offline, and decided to keep this as is. Doing this ensures the behaviour stays the same for this case before and after this patch. We discussed that there's no good reason not to handle it this way, and there may be some minor added concurrency benefits of doing this. For example, if the first request that's inactively waiting at this lock starts blocking on a different key, but the second request could proceed to evaluation, this approach allows it to do so.

**Review by nvb — APPROVED** [review]
:lgtm: assuming the YCSB results look good. Otherwise, we'll need to eliminate any regression first.

> Reviewed 3 of 3 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118484#-:-NrBeO1sBzK_XIK7GJtj:b1ag7h3)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1039 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118484#-NqDgYWc7wAEWun3Abug:-NrBdbRu5PBrLRuEkx2M:bwm5r1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a467593d88b405b7ea10239dee40b0b57eabb0d/pkg/kv/kvserver/concurrency/lock_table.go#L1039)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

This is much nicer, thanks!
</blockquote></details>

nit: you also don't need the `o1.reqSeqNum == o2.reqSeqNum // same request` branch above, but I don't feel strongly about it being removed, so up to you.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2877 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118484#-NqDiZJjEkzbFBbotZHk:-NrBe-CW62T4h21UgTz-:brlcdyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a467593d88b405b7ea10239dee40b0b57eabb0d/pkg/kv/kvserver/concurrency/lock_table.go#L2877)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

> This is checking whether a queued request conflicts with another queued request from the same transaction, right?

Yeah, we're making sure we don't consider requests from the same transaction conflicting. None of the lock table tests break without this change, but that's only because we were lacking coverage for when this would be needed. I added a test case below -- it might be easier to explain why we need this change while referencing an example, so I'll just do it below.

All this being said, our randomized tests do fail if I comment this bit out.
</blockquote></details>

Thanks for explaining here and during our 1:1. This makes sense to me now.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 660 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/118484#-NrBdBxG7SRHBp5L-tNG:-NrBdBxG7SRHBp5L-tNH:bwhjy1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/75ceec740b3d3a3f30d0e12421d162c74445200c/pkg/kv/kvserver/concurrency/lock_table.go#L660)):*
> ```Go
> 	// invariants hold by asserting them.
> 	assert(newState.kind != doneWaiting, "unexpected waiting state kind")
> 	assert(newState.txn != nil, "txn cannot be unset if waiting state isn't DoneWaiting")
> ```

nit: `s/DoneWaiting/doneWaiting/`

**Comment by arulajmani** [comment]
It seems like this improved YCSB -- 

```
                │ before_summarized.txt │        after_summarized.txt         │
                │         ops/s         │   ops/s     vs base                 │
YCSB-throughput             123.0k ± 2%   128.3k ± ?  +4.31% (p=0.023 n=26+6)

         │ before_summarized.txt │        after_summarized.txt         │
         │         ms/s          │    ms/s     vs base                 │
YCSB-P50              3.100 ± 6%    2.900 ± ?  -6.45% (p=0.003 n=26+6)
YCSB-Avg             900.0m ± 0%   900.0m ± ?       ~ (p=0.274 n=26+6)
geomean               1.670         1.616      -3.28%
```

Do note that `before_summarized` has 25 samples, whereas after_summarized has only 5.

**Review by arulajmani — COMMENTED** [review]
The logic test failures pointed me to there being a need to update `tryFreeOnReplicatedAcquire` to handle lock promotions correctly. That's because locking requests in the wait queue can now belong to the lock holder transaction, which changes how "uncontended" is determined. @nvanbenschoten could you take a quick look? 

Separately, while working through the logic test failures, I realized there's something weird going on with `crdb_internal.cluster_locks`. The output in that file includes uncontended replicated locks. I'll investigate that separately.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118484#-:-NrHA_Mn1AZZ8Cz-dZXl:b-flidz7)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1039 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118484#-NqDgYWc7wAEWun3Abug:-NrHA1Cw3ZSPgJsWdvPx:b-m0g2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a467593d88b405b7ea10239dee40b0b57eabb0d/pkg/kv/kvserver/concurrency/lock_table.go#L1039)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: you also don't need the `o1.reqSeqNum == o2.reqSeqNum // same request` branch above, but I don't feel strongly about it being removed, so up to you.
</blockquote></details>

I'll leave it, if only to document how same requests are handled explicitly. That's because we use this function while looping in a few places up till a request that's already in the queue.

**Comment by arulajmani** [comment]
@nvanbenschoten given we discussed the changes to `tryFreeOnReplicatedAcquire` on Thursday, and you were on board, I'll optimistically bors this assuming the LGTM from before stands. 

bors r=nvanbenschoten

**Pull request merged**
