### PR TITLE
release-2.1: pretty: implement various statements

### PR DESCRIPTION
**Pull request by madelynnblue**
Backport 10/10 commits from #29979.

/cc @cockroachdb/release

---

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
Before I approve this, can you briefly outline why it is important we have this code "up to date" in the release? Is it just because of the command `cockroach sqlfmt`? 

IMHO the code on http://sqlfum.pt could use the `master` branch permanently. 

Then IMHO too we could change the `cockroach sqlfmt` command to use a HTTP request to sqlfum.pt instead of using the internal code, so that it always picks up the latest changes.

I am saying this because I foresee a lot of churn in this area over time, even post-release. I don't think it will be fun to do backports in the long run.

**Comment by benesch** [comment]
> Then IMHO too we could change the cockroach sqlfmt command to use a HTTP request to sqlfum.pt instead of using the internal code, so that it always picks up the latest changes.

That seems like an out of character suggestion for you, @knz! I would very much prefer that `cockroach sqlfmt` not send my SQL elsewhere to be formatted. Mostly because I sometimes find myself without internet, but also because my SQL might contain something sensitive.

**Comment by bdarnell** [comment]
Yeah, -1 to sending the SQL out to a remote server. If we aren't willing to keep `cockroach sqlfmt` up to date, we shouldn't offer it in the mainline build and just leave it as a separate binary.

**Comment by couchand** [comment]
One more wrench: `cockroach sqlfmt` should be able to format experimental syntax that was valid for that version but is no longer valid.

**Comment by knz** [comment]
yeah ok I see the point. That being said I am not yet entirely sure what the best approach is to avoid churn.

**Comment by knz** [comment]
LGTM for this PR, but we'll want to revisit the topic later.

**Pull request merged**
