### PR TITLE
util/log: log to stderr if requested

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10959)

### CODE REVIEW

**Comment by petermattis** [comment]
@knz This makes `./cockroach start --logtostderr` work as I expect. Previously, that wasn't logging anything which seemed wrong (and a change from previous behavior).

**Comment by knz** [comment]
LGTM, but I thought I had taken care of this in `start.go` with this:
```
+                       ls := pf.Lookup(logflags.LogToStderrName)
+                       if !ls.Changed {
+                               if err := vf.Value.Set(log.Severity_NONE.String()); err != nil {
+                                       return err
+                               }
+                       }
```

Why does it default to NONE when you specify `--logtostderr`? I would expect that specifying the flag changes `Changed`. If that check doesn't work and your PR is needed, perhaps the code in `start.go` could be cleaned up.

**Comment by knz** [comment]
Oh never mind, I know what went wrong. Mind me taking over this one?

**Comment by petermattis** [comment]
Go ahead.

**Comment by knz** [comment]
Superseded by #10962.

**Pull request closed without merging**
