### PR TITLE
build: Expand jepsen test coverage

### PR DESCRIPTION
**Pull request by bdarnell**
Enable more nemeses: subcritical-skews, strobe-skews, split
Enable more tests: bank-mulittable, g2

Updates #19697

### CODE REVIEW

**Review by tbg — APPROVED** [review]

**Comment by bdarnell** [comment]
Running a test [on teamcity](https://teamcity.cockroachdb.com/viewLog.html?buildId=402485&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_Jepsen). And since I forgot to put a `if branch == 'master'` in the issue-posting script, this will double as a test of that change if any of these fail.

**Comment by knz** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19910)*

**Comment by knz** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19910#-:-KySSx7yIEg-zCWd5NCA:bnfp4nl)*

**Comment by bdarnell** [comment]
Made some more tweaks to this: Dropped the strobe-skews nemesis (it didn't find any failures, and I don't think it has ever been any better at exposing problems than subcritical-skews). Removed the comments test which is expected to fail. Reduced the running time per test as a quick fix for the full-disk failures in #19930.

**Comment by knz** [comment]
Thanks, still LGTM.

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19910#-:-KyVQbiVXt2m-fl29N12:bq4g9sw)*

**Pull request merged**
