### PR TITLE
kv/kvclient: remove GetLeafTxnInputState{OrRejectClient} split

### PR DESCRIPTION
**Pull request by nvb**
Informs #99269.

This PR includes two refactors with no production behavior changes. They combine to make the reference counting attempted in #99269 easier to implement.

### kv/kvclient: introduce txn.GetReadSeqNum

This commit introduces a new `txn.GetReadSeqNum` method.

It then uses this method to avoid unnecessarily heavyweight calls into GetLeafTxnInputState. It turns out that this removes all production calls into `GetLeafTxnInputState`.

### kv/kvclient: remove GetLeafTxnInputState{OrRejectClient} split

This commit removes the split between the `txn.GetLeafTxnInputState` and `txn.GetLeafTxnInputStateOrRejectClient` methods, consolidating on a single method that behaves like the old `txn.GetLeafTxnInputStateOrRejectClient` method behaved. As of the previous commit, there were no remaining production callers of `txn.GetLeafTxnInputState`.

This split between the two methods was introduced in d8630d00, which was a targeted fix that did not questions whether all callers of `GetLeafTxnInputState` (`GetTxnCoordMeta` at the time) could be switched to have this new behavior. It may have also been more difficult to switch all callers over before c00ea847 and 0461b006.

In consolidating this logic, we also remove the `kv.TxnStatusOpt` enum and simplify the `kv.TxnSender` interface.

Release note: None

### CODE REVIEW

**Review by arulajmani — APPROVED** [review]
Nice cleanup! :lgtm: 

> Reviewed 6 of 6 files at r1, 17 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99378#-:-NRE6g8j7Ut2qoEse4rv:bkt4ztb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miraradeva, @nvanbenschoten, and @yuzefovich)

___
*[`-- commits` line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/99378#-NRE2IkC4E7YqvwAr5Gl):*
nit: should we remove the backticks around the commit hash so that it's clickable? 
___
*[`pkg/kv/kvclient/kvcoord/txn_coord_sender.go` line 1209 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/99378#-NRE4MjZ5gEKwqLe6fIh:-NRE4MjZ5gEKwqLe6fIi:b-2jk2r9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0386c76929a0a9481b026a334977490a3bba608c/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1209)):*
> ```Go
> 	// TODO(nvanbenschoten): should we be calling maybeRejectClientLocked here?
> 	// The caller in execinfra.GetLeafTxnFinalState is not set up to propagate
> 	// errors, so for not, we don't.
> ```

"for now" 

Separately, should we just return the error and let the thing panic? we already have this TODO that covers this https://github.com/cockroachdb/cockroach/blob/8d534b8418fb0c8534c2be738d513d87145f2d2c/pkg/sql/execinfra/base.go#L291-L295
___
*[`pkg/sql/rowexec/tablereader_test.go` line 333 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/99378#-NRE4-VJ8TbpL1fRbGkA:-NRE4-VJ8TbpL1fRbGkB:b-2tyai6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0386c76929a0a9481b026a334977490a3bba608c/pkg/sql/rowexec/tablereader_test.go#L333)):*
> ```Go
> 	rootTxn := kv.NewTxn(ctx, s.DB(), s.NodeID())
> 	leafInputState, err := rootTxn.GetLeafTxnInputState(ctx)
> 	if err != nil {
> ```

nit: here, and in a few other places where we're fatal-ing, could we just switch to `require.NoError`?

**Review by nvb — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99378#-:-NREsasr2uff_v3QBj71:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani, @miraradeva, and @yuzefovich)

___
*[`-- commits` line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/99378#-NRE2IkC4E7YqvwAr5Gl):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: should we remove the backticks around the commit hash so that it's clickable? 
</blockquote></details>

Done.
___
*[`pkg/kv/kvclient/kvcoord/txn_coord_sender.go` line 1209 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/99378#-NRE4MjZ5gEKwqLe6fIh:-NREs0nGC3Zeub-CdtZi:bbnv6j0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0386c76929a0a9481b026a334977490a3bba608c/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1209)):*
> "for now"

Done.

> Separately, ...

I don't think we want to panic in this case. I think it's entirely valid to hit, so we'll end up needing to do another patch like https://github.com/cockroachdb/cockroach/pull/99306.
___
*[`pkg/sql/rowexec/tablereader_test.go` line 333 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/99378#-NRE4-VJ8TbpL1fRbGkA:-NREsJ91-l3NVReZQJ6g:b-2tm71i) ([raw file](https://github.com/cockroachdb/cockroach/blob/0386c76929a0a9481b026a334977490a3bba608c/pkg/sql/rowexec/tablereader_test.go#L333)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: here, and in a few other places where we're fatal-ing, could we just switch to `require.NoError`? 
</blockquote></details>

Yeah, I was trying to not introduce `require` into files that were not yet using the testing utility. Better to switch those over wholesale.

**Comment by nvanbenschoten** [comment]
bors r=arulajmani

Backporting so that we can also backport reference counting.

**Review by yuzefovich — COMMENTED** [review]
Nice!

> Reviewed 6 of 6 files at r1, 16 of 17 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99378#-:-NRFWbYODsrYf9OS9S97:b-83sjoh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by dt** [comment]
blathers backport 23.1

**Pull request merged**
