### PR TITLE
cluster-ui: populate db name in v2 db details page and add breadcrumbs

### LINKED ISSUE #131119: cluster-ui: get db name by id in v2 db details page
We haven't populated the db page name in the new db details page yet.
This is because we are currently using the db id in the route params - we can swap back to the name in the route params or provide an api to get the name by id.

Epic: CRDB-37558

Jira issue: CRDB-42385

### PR DESCRIPTION
**Pull request by xinhaoz**
This commit populates the db name in the db details page. A new hook is created that fetches and caches db names by id from the backend by querying crdb_internal.databases. We use `useSWRImmutable` for data fetching  since we don't expect the payload to change in the session.

This commit also fixes the placeholder image for an empty table.

Fixes: #131119
Epic: CRDB-37558

Release note: None

### CODE REVIEW

**Comment by xinhaoz** [comment]
https://www.loom.com/share/a57e50ba08184c6faa7da01503d5643b

**Review by dhartunian — COMMENTED** [review]
@xinhaoz why can't we include this in the backend request for db metadata? I'd really like the page to be powered by a single API call.

Sidenote, maybe this is happening in a separate PR: what's the deal with "unknown region" in the loom? Can we omit that when regions aren't configured?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131247#-:-O7VrZGP6LYEC55_K-_v:b-4jbzp)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons and @kyle-a-wong)

**Comment by xinhaoz** [comment]
@dhartunian Sure, let me talk to Kyle about reorganizing the api into a database detail level one that would also include grants, rather than having the single one that lists table metadata. I've asked Inna what we should do in the case where no regions are defined. Just waiting on updated feedback / updated designs for that.

**Comment by xinhaoz** [comment]
On second thought, keeping the grants info separate makes sense right now since the table information needs pagination state, and we're not caching the grants information yet. Seems like we should just annotate the table metadata response with the db name.

**Pull request closed without merging**
