### PR TITLE
storage: Maintain contains_estimates flag on MVCCStats

### LINKED ISSUE #7290: storage: MVCC stats after initial splits have negative values
```
{RaftAppliedIndex:42 LeaseAppliedIndex:25 Desc:range_id:1 start_key:"" end_key:"\223" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2  Lease:replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407251h36m37.60286253s TruncatedState:index:0 term:0  GCThreshold:0.000000000,0 Stats:{LastUpdateNanos:1466105792859562525 IntentAge:0 GCBytesAge:2276 LiveBytes:36283 LiveCount:204 KeyBytes:7697 KeyCount:204 ValBytes:28829 ValCount:212 IntentBytes:0 IntentCount:0 SysBytes:455 SysCount:6} Frozen:false}

{RaftAppliedIndex:22 LeaseAppliedIndex:9 Desc:range_id:2 start_key:"\223" end_key:"\224" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2  Lease:replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407251h36m42.592591058s TruncatedState:index:0 term:0  GCThreshold:0.000000000,0 Stats:{LastUpdateNanos:1466105783090649289 IntentAge:0 GCBytesAge:0 LiveBytes:0 LiveCount:0 KeyBytes:0 KeyCount:0 ValBytes:0 ValCount:0 IntentBytes:0 IntentCount:0 SysBytes:503 SysCount:7} Frozen:false}

{RaftAppliedIndex:20 LeaseAppliedIndex:8 Desc:range_id:3 start_key:"\224" end_key:"\225" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2  Lease:replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407251h36m27.840649289s TruncatedState:index:0 term:0  GCThreshold:0.000000000,0 Stats:{LastUpdateNanos:1466105783090649289 IntentAge:0 GCBytesAge:0 LiveBytes:430 LiveCount:5 KeyBytes:204 KeyCount:5 ValBytes:226 ValCount:5 IntentBytes:0 IntentCount:0 SysBytes:742 SysCount:8} Frozen:false}

{RaftAppliedIndex:18 LeaseAppliedIndex:6 Desc:range_id:4 start_key:"\225" end_key:"\226" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2  Lease:replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407251h36m27.840649289s TruncatedState:index:0 term:0  GCThreshold:0.000000000,0 Stats:{LastUpdateNanos:1466105783090649289 IntentAge:0 GCBytesAge:0 LiveBytes:2125 LiveCount:24 KeyBytes:884 KeyCount:24 ValBytes:1241 ValCount:24 IntentBytes:0 IntentCount:0 SysBytes:714 SysCount:8} Frozen:false}

{RaftAppliedIndex:10 LeaseAppliedIndex:0 Desc:range_id:5 start_key:"\226" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2  Lease:replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 TruncatedState:index:0 term:0  GCThreshold:0.000000000,0 Stats:{LastUpdateNanos:1466105783090649289 IntentAge:0 GCBytesAge:0 LiveBytes:-7600 LiveCount:-172 KeyBytes:-6912 KeyCount:-172 ValBytes:-688 ValCount:-172 IntentBytes:0 IntentCount:0 SysBytes:487 SysCount:4} Frozen:false}
```

TL;DR: last two lines have

```
LiveBytes:-7600 LiveCount:-172 KeyBytes:-6912 KeyCount:-172 ValBytes:-688 ValCount:-172
```

The in-memory and on-disk stats are identical. We must be messing up the computations, but at least we do so in a consistent way.

Pushed a repro to `tschottdorf/repro-7290`. Check it out, run

`rm -rf cockroach-data; make build && ./cockroach start --alsologtostderr=INFO`

and hit http://localhost:8080/_status/ranges/local to see the output above in the logs.

### PR DESCRIPTION
**Pull request by nvb**
Closes #7290.

This change adds a `contains_estimates` to the `MVCCStats` object. The
flag is set whenever a stats computation is only an estimate (such as
with Merge requests), and is propagated through stats arithmetic. Later,
computations which require accurate statistics can use this field to
determine if they need to recompute the stats or not.

The only case where this is currently necessary is during range splits,
where stats arithmetic is only possible if the current stats object is 100%
accurate. If not, the split will call `ComputeStatsForRange` for both
halves of the split, instead of just the left half.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7721)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Not thrilled about the additional complexity in the split trigger, but I suppose it's easy enough to take out when we get a chance at a more comprehensive solution. :lgtm: but give the others a chance to see.

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7721#-:-KMJbtVxKHXAPO_HXhUp:760673015)*

**Comment by petermattis** [comment]
:lgtm: 

I think you should update `MVCCStats.{Add,Subtract}` to propagate `contains_estimates`. 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7721#-:-KMJvykMLnb01Pt8WUFH:-1321811737)*

**Comment by nvanbenschoten** [comment]
TFTRs. @petermattis Isn't it already propagating the flag? See `storage/engine/enginepb/mvcc.go`.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7721#-:-KMKIptqqnRZqEjVwrWA:-1041533980)*

**Comment by petermattis** [comment]
Not sure how I missed the changes to `storage/engine/enginepb/mvcc.go`. Apparently I can't use search correctly. :lgtm_strong: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7721#-:-KMKQnEYXbxk2x4ZbsCd:776422841)*

**Comment by tschottdorf** [comment]
There's the usual slight migration concern about ranges being caught
mid-split by this upgrade, so maybe you want to give Ben a chance to chime
in. As far as I know we hit timeseries inaccuracies quite a bit (right? If
so is that tracked anywhere?), and so this change would only add
inconsistencies in MVCCStats for those ranges, which seems ... acceptable
to me.

On Sun, Jul 10, 2016 at 11:32 AM Peter Mattis <notifications@github.com>
wrote:

> Not sure how I missed the changes to storage/engine/enginepb/mvcc.go.
> Apparently I can't use search correctly. [image: :lgtm_strong:]
> <https://camo.githubusercontent.com/aef7967e4818b7dc97469bd2853c2255784874e2/68747470733a2f2f72657669657761626c652e696f2f6c67746d5f7374726f6e672e706e67>
> ------------------------------
>
> Review status: all files reviewed at latest revision, all discussions
> resolved, some commit checks failed.
> ------------------------------
>
> *Comments from Reviewable
> <https://reviewable.io:443/reviews/cockroachdb/cockroach/7721#-:-KMKQnEYXbxk2x4ZbsCd:776422841>*
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/7721#issuecomment-231594887>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135FH3V8KBxt-XSOHg8EGl4S_JpjLhks5qURCEgaJpZM4JIx2b>
> .
>
-- 

-- Tobias

**Comment by petermattis** [comment]
We'll definitely have to recommend a freeze-the-cluster upgrade for this. As soon as one node starts writing `MVCCStats` containing the `constains_estimates` field, all nodes have to do so in order for the consistency checker to not complain.

**Comment by bdarnell** [comment]
:lgtm: I think we still want to recommend stop-the-world without freeze for now; we still have open issues regarding the freeze command. The risk of inconsistency is unfortunate, but we already have a history of inconsistency on TS keys so this just postpones our ability to enable the consistency checker by a little longer.

---

Reviewed 14 of 14 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/engine/enginepb/mvcc.proto, line 116 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7721#-KML6DbgcRxMI_MVVMrC:-KML6DbgcRxMI_MVVMrD:92202596) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bbf9b3aa31753235cbec69588d6556112149ce3/storage/engine/enginepb/mvcc.proto#L116)):*
> ```protobuf
>   option (gogoproto.populate) = true;
> 
>   // contains_estimates indicates that the MVCCStats object contains values
> ```

Should we invert this boolean to `certain` so that all existing data is considered uncertain and will be recomputed? 

---

*[storage/engine/enginepb/mvcc.proto, line 124 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7721#-KML75C2YY5zwHlbq85C:-KML75C2YY5zwHlbq85D:-87534585) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bbf9b3aa31753235cbec69588d6556112149ce3/storage/engine/enginepb/mvcc.proto#L124)):*
> ```protobuf
>   // to true for all stats during a migration to force full recomputation on
>   // splits, otherwise the previously computed stats calculations could be off,
>   // which will never be corrected. See #5690.
> ```

If we need to correct old stats, we should have a separate queue for this purpose. We can't assume that all ranges will be active enough to split. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7721#-:-KMLE08QW3tAIom56wml:780190978)*

**Comment by tamird** [comment]
Reviewed 1 of 14 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/replica_command.go, line 2462 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7721#-KMLJA8kbOGLE8ESqzN9:-KMLJA8lJcTlc0AZKPyy:-1401898623) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bbf9b3aa31753235cbec69588d6556112149ce3/storage/replica_command.go#L2462)):*
> ```Go
> 		rightMS, err = ComputeStatsForRange(&split.NewDesc, batch, ts.WallTime)
> 		if err != nil {
> 			return errors.Errorf("unable to compute stats for new range after split: %s", err)
> ```

throughout: errors.Wrapf this pattern

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7721)*

**Comment by nvanbenschoten** [comment]
Reviewed 1 of 1 files at r2.
Review status: 12 of 15 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[storage/replica_command.go, line 2462 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7721#-KMLJA8kbOGLE8ESqzN9:-KMSD-Kp31qP-kqBak34:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bbf9b3aa31753235cbec69588d6556112149ce3/storage/replica_command.go#L2462)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> throughout: errors.Wrapf this pattern
</details>
Done.

---

*[storage/engine/enginepb/mvcc.proto, line 116 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7721#-KML6DbgcRxMI_MVVMrC:-KMSDgaZD_UkiCpjlvf0:-1197403671) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bbf9b3aa31753235cbec69588d6556112149ce3/storage/engine/enginepb/mvcc.proto#L116)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Should we invert this boolean to `certain` so that all existing data is considered uncertain and will be recomputed? 
</details>
I was hoping to have the default value for this field be convenient to use, and for the notion of uncertain stats to be discouraged. Because of this, I figured it would be best if this field could be ignored in most cases, and would have to be explicitly referenced when necessary, so I went with `contains_estimates`.

That said, if you think the migration benefit gained from inverting the field is strong enough to justify the less desirable default value, I'll switch it.

---

*[storage/engine/enginepb/mvcc.proto, line 124 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7721#-KML75C2YY5zwHlbq85C:-KMSD4qWNZiYJM1AjzDS:-570825798) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bbf9b3aa31753235cbec69588d6556112149ce3/storage/engine/enginepb/mvcc.proto#L124)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> If we need to correct old stats, we should have a separate queue for this purpose. We can't assume that all ranges will be active enough to split. 
</details>
Good point. This was added primarily as a suggestion, but like you pointed out, it's not the complete solution to the problem discussed. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7721)*

**Comment by bdarnell** [comment]
LGTM

**Pull request merged**
