### PR TITLE
rowenc,encoding: pre-allocate EWKB slice for unmarshalling

### PR DESCRIPTION
**Pull request by sumeerbhola**
Unmarshalling a geopb.SpatialObject needs to allocate a
byte slice for EWKB. This is now pre-allocated using
DatumAlloc in a 2-step process: claim the complete unused
byte slice in DatumAlloc, and then after unmarshalling
return the unused space.

This improves expensive queries
```
name                                   old ms     new ms     delta
Test/postgis_geometry_tutorial/11.2b   1.38 ±31%  1.35 ±32%     ~     (p=0.352 n=50+49)
Test/postgis_geometry_tutorial/11.6    1.43 ±21%  1.45 ±28%     ~     (p=0.810 n=47+48)
Test/postgis_geometry_tutorial/12.1.2  0.81 ±28%  0.84 ±27%     ~     (p=0.174 n=47+50)
Test/postgis_geometry_tutorial/12.2.3  1.22 ±19%  1.23 ±20%     ~     (p=0.879 n=46+49)
Test/postgis_geometry_tutorial/12.2.4  1.18 ±20%  1.19 ±20%     ~     (p=0.659 n=47+48)
Test/postgis_geometry_tutorial/13.0    1.30 ±17%  1.38 ±25%   +5.81%  (p=0.007 n=45+48)
Test/postgis_geometry_tutorial/13.1a    242 ±19%   232 ±10%   -3.98%  (p=0.001 n=49+48)
Test/postgis_geometry_tutorial/13.1c   25.7 ±28%  24.2 ±19%   -5.87%  (p=0.000 n=50+50)
Test/postgis_geometry_tutorial/13.2     327 ±18%   315 ±12%   -3.66%  (p=0.001 n=49+49)
Test/postgis_geometry_tutorial/14.1a   1.48 ±22%  1.75 ±35%  +17.82%  (p=0.000 n=48+50)
Test/postgis_geometry_tutorial/14.2b   6.20 ±23%  7.03 ±22%  +13.33%  (p=0.000 n=48+50)
Test/postgis_geometry_tutorial/14.2c   3.77 ±19%  3.76 ±12%     ~     (p=0.418 n=47+49)
Test/postgis_geometry_tutorial/14.3c   32.7 ±12%  32.2 ± 8%     ~     (p=0.187 n=44+50)
Test/postgis_geometry_tutorial/15.0    1.51 ±25%  1.49 ±25%     ~     (p=0.404 n=48+47)
Test/nyc/nyc-intersects                80.8 ±19%  78.1 ±17%   -3.24%  (p=0.042 n=48+48)
Test/nyc/nyc-dwithin                    233 ±19%   223 ±12%   -4.66%  (p=0.000 n=47+50)
Test/nyc/nyc-coveredby                 83.9 ±19%  79.1 ±18%   -5.79%  (p=0.000 n=48+49)
Test/nyc/nyc-expand-blocks             89.6 ±18%  87.6 ±11%     ~     (p=0.077 n=46+45)
```

Release justification: The geospatial functionality is
new for this release so this falls under category 2
(low-risk updates to new functionality)

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53555)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten, @otan, @sumeerbhola, and @yuzefovich)

___
*[pkg/sql/rowenc/datum_alloc.go, line 242 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53555#-MFkkrl-21kFl3BUJu6G:-MFkkrl0-7eCwgtbFqQC:b5pyk3m) ([raw file](https://github.com/cockroachdb/cockroach/blob/061992d66174b05dd054091fafef5e65ac343b81/pkg/sql/rowenc/datum_alloc.go#L242)):*
> ```Go
> // pre-allocated space to the DatumAlloc.
> func (a *DatumAlloc) NewDGeographyEmpty() *tree.DGeography {
> 	if a.AllocSize == 0 {
> ```

Can this call into `NewDGeography`?
___
*[pkg/sql/rowenc/datum_alloc.go, line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53555#-MFklwYXBHVq7cRtCT6d:-MFklwYXBHVq7cRtCT6e:b5giosv) ([raw file](https://github.com/cockroachdb/cockroach/blob/061992d66174b05dd054091fafef5e65ac343b81/pkg/sql/rowenc/datum_alloc.go#L253)):*
> ```Go
> 	so := r.SpatialObjectRef()
> 	if a.ewkbAlloc == nil && !a.lastEWKBBeyondAllocSize {
> 		so.EWKB = make([]byte, 0, defaultEWKBAlloc)
> ```

Can we tell how large this is going to need to be ahead of time? I guess not because we have length prefixed byte values. If we had any ability to then this would all become a lot cleaner.
___
*[pkg/sql/rowenc/datum_alloc.go, line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53555#-MFkrZ1e9Qs6xWlzJ0cO:-MFkrZ1e9Qs6xWlzJ0cP:bkx5snu) ([raw file](https://github.com/cockroachdb/cockroach/blob/061992d66174b05dd054091fafef5e65ac343b81/pkg/sql/rowenc/datum_alloc.go#L253)):*
> ```Go
> 	so := r.SpatialObjectRef()
> 	if a.ewkbAlloc == nil && !a.lastEWKBBeyondAllocSize {
> 		so.EWKB = make([]byte, 0, defaultEWKBAlloc)
> ```

Should we exponentially increase the allocation size over time?
___
*[pkg/sql/rowenc/datum_alloc.go, line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53555#-MFkrjIk0HMvcKeRiaL9:-MFkrjIk0HMvcKeRiaLA:bpfkyrq) ([raw file](https://github.com/cockroachdb/cockroach/blob/061992d66174b05dd054091fafef5e65ac343b81/pkg/sql/rowenc/datum_alloc.go#L271)):*
> ```Go
> 	l := len(so.EWKB)
> 	if (c - l) > l {
> 		a.ewkbAlloc = so.EWKB[l:c]
> ```

Consider `a.ewkbAlloc = so.EWKB[l:l:c]`

So that we don't have to slice above with `so.EWKB = a.ewkbAlloc[:0]`

**Review by yuzefovich — COMMENTED** [review]
Do you have an insight into why we're seeing a decrease in performance on non-expensive queries? Because we're allocating a bigger buffer than necessary?

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53555#-:-MFl74mk9ZvQmPD5H-gT:bty2zbq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten, @otan, and @sumeerbhola)

___
*[pkg/sql/rowenc/datum_alloc.go, line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53555#-MFkrZ1e9Qs6xWlzJ0cO:-MFl6MqFB1-EQTXIihND:b-fyrknb) ([raw file](https://github.com/cockroachdb/cockroach/blob/061992d66174b05dd054091fafef5e65ac343b81/pkg/sql/rowenc/datum_alloc.go#L253)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we exponentially increase the allocation size over time?
</blockquote></details>

+1 (probably until we get to some threshold).
___
*[pkg/sql/rowenc/datum_alloc.go, line 305 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53555#-MFl6tBt7WKfUJoSNoPg:-MFl6tBt7WKfUJoSNoPh:b-gixhaq) ([raw file](https://github.com/cockroachdb/cockroach/blob/061992d66174b05dd054091fafef5e65ac343b81/pkg/sql/rowenc/datum_alloc.go#L305)):*
> ```Go
> 	*buf = (*buf)[1:]
> 	so := r.SpatialObjectRef()
> 	if a.ewkbAlloc == nil && !a.lastEWKBBeyondAllocSize {
> ```

nit: I'd extract this `if` into an unexported helper method.

**Review by sumeerbhola — COMMENTED** [review]
TFTRs!

> Do you have an insight into why we're seeing a decrease in performance on non-expensive queries? Because we're allocating a bigger buffer than necessary?

I believe so, but it is hard to be certain based on looking at profiles. For the 14.2b query, which is the most expensive of the "non-expensive" queries that shows an increase, there are 2 places we use a DatumAlloc for allocating Geometry:
- the left side of the invertedJoiner which are subway stations (each is a POINT): it sees 38 rows. The EWKBs are 25 bytes, so we waste ~3000 of the 4096 bytes.
- the left and right sides of the joinReader: which is 142 + 32 rows. Here the allocations increase to the max of 16384 and allocate that max 5 times, and leave 5000 bytes of the last allocation unused (there isn't much wasted space from the previous allocations).
Maybe those two effects are sufficient for the increase, but it isn't borne out by the profiles. So it may be just noise.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53555#-:-MFlrxmZ0llOe3bzm9xL:b2ht6wc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten, @otan, and @yuzefovich)

___
*[pkg/sql/rowenc/datum_alloc.go, line 242 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53555#-MFkkrl-21kFl3BUJu6G:-MFlt0QVDT5fp6e_6z_a:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/061992d66174b05dd054091fafef5e65ac343b81/pkg/sql/rowenc/datum_alloc.go#L242)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can this call into `NewDGeography`?
</blockquote></details>

Done
___
*[pkg/sql/rowenc/datum_alloc.go, line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53555#-MFklwYXBHVq7cRtCT6d:-MFlt38FAUrtu5pckAzE:brkkr9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/061992d66174b05dd054091fafef5e65ac343b81/pkg/sql/rowenc/datum_alloc.go#L253)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we tell how large this is going to need to be ahead of time? I guess not because we have length prefixed byte values. If we had any ability to then this would all become a lot cleaner.
</blockquote></details>

Yes, we know the length only in the unmarshalling code when it reaches this field.
___
*[pkg/sql/rowenc/datum_alloc.go, line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53555#-MFkrZ1e9Qs6xWlzJ0cO:-MFlwbV94s_8CVdus5IQ:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/061992d66174b05dd054091fafef5e65ac343b81/pkg/sql/rowenc/datum_alloc.go#L253)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

+1 (probably until we get to some threshold).
</blockquote></details>

Done
___
*[pkg/sql/rowenc/datum_alloc.go, line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53555#-MFkrjIk0HMvcKeRiaL9:-MFlu3Cz1ppeFpqTjJYP:b21phq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/061992d66174b05dd054091fafef5e65ac343b81/pkg/sql/rowenc/datum_alloc.go#L271)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Consider `a.ewkbAlloc = so.EWKB[l:l:c]`

So that we don't have to slice above with `so.EWKB = a.ewkbAlloc[:0]`
</blockquote></details>

Done. I guess it saves one write to the slice header.
___
*[pkg/sql/rowenc/datum_alloc.go, line 305 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53555#-MFl6tBt7WKfUJoSNoPg:-MFlv8_-CvyrCHk3_gP7:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/061992d66174b05dd054091fafef5e65ac343b81/pkg/sql/rowenc/datum_alloc.go#L305)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: I'd extract this `if` into an unexported helper method.
</blockquote></details>

Done

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53555#-:-MFpfLit8owCQjsgBa0x:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @otan)

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53555)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @otan)

___
*[pkg/testutils/lint/lint_test.go, line 985 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53555#-MFpy_PX5JHSD2eu0HTQ:-MFpy_PX5JHSD2eu0HTR:b-m3gcog) ([raw file](https://github.com/cockroachdb/cockroach/blob/e612ba896114b8845d3335a9375b7d955eb12977/pkg/testutils/lint/lint_test.go#L985)):*
> ```Go
> 			":!util/protoutil/marshal.go",
> 			":!util/protoutil/marshaler.go",
> 			":!util/encoding/encoding.go",
> ```

is there a tighter way to fix the lint failure (than excluding the whole file)?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53555)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten, @otan, and @sumeerbhola)

___
*[pkg/testutils/lint/lint_test.go, line 985 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53555#-MFpy_PX5JHSD2eu0HTQ:-MFqhL2NBpZR47n6emGi:b-x6xb8y) ([raw file](https://github.com/cockroachdb/cockroach/blob/e612ba896114b8845d3335a9375b7d955eb12977/pkg/testutils/lint/lint_test.go#L985)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is there a tighter way to fix the lint failure (than excluding the whole file)?
</blockquote></details>

I'm not aware of such, but I'm also not very concerned about this linter. I believe `protoutil.Unmarshal` business was added back in 2016 in order to enforce some things related to raft protobufs during testing, so I wouldn't worry much about adding an exception to this linter.

**Pull request merged**
