### PR TITLE
Fork golang's stress program.

### PR DESCRIPTION
**Pull request by BramGruneir**
Does anyone know what I'm supposed to do with the license here?  
My plan is to add some new functionality to it.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3995)

### CODE REVIEW

**Comment by tamird** [comment]
Can you add your proposed new functionality? I don't see a reason to merge this as-is.

**Comment by petermattis** [comment]
Copy the LICENSE file.

LGTM

**Comment by BramGruneir** [comment]
I'll add the functionality in the next PR.  Wanted to keep the changes and the fork separate.

**Comment by tamird** [comment]
Separate commit seems like enough separation to me.

**Comment by bdarnell** [comment]
If we keep the name `stress` it might get tricky to deal with which one is on the `$PATH` (in case people do a blanket install of `golang.org/x/tools/cmd/...`) Probably best to give it a different name.

**Comment by petermattis** [comment]
I think @BramGruneir is only going to add a few new flags (exit on first failure, exit after running for a fixed duration, etc). Should be backward compatible.

**Comment by BramGruneir** [comment]
I'll rename it to stresstest.

**Comment by petermattis** [comment]
I'd prefer not to rename this program if we're not planning to make significant changes (which you aren't). Btw, I only just noticed you were putting this in the `cockroachdb/cockroach` repo. Shouldn't this go into its own repository?

**Comment by BramGruneir** [comment]
closing for cockroachdb/stress/pull/1 instead

**Pull request closed without merging**
