### PR TITLE
sql, tracing: save traces in Jaeger format

### PR DESCRIPTION
**Pull request by andreimatei**
This patch adds a new file to a statement diagnostics bundle:
trace-jaeger.json. This file can be manually imported in Jaeger, which
will the display the trace.
This is in addition to our own JSON format, and to a human-readable
format, which also remain in the bundle.

A source file with the structure of the respective JSON is copied over
from the Jaeger source code.

No longer shall we live in darkness.

Release note (general change): Statement diagnostics zip bundles now
contain a representation of the statement trace that can be imported
into Jaeger for visualization.

### CODE REVIEW

**Comment by andreimatei** [comment]
Looks like this in Jaeger
Screenshot 2020-04-09 16 18 45

@dhartunian fyi

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47303)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/util/tracing/jaegerjson/jaeger_json.go, line 16 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/47303#-M4WJNhZA8_EJgFlLOk4:-M4WJNhZA8_EJgFlLOk5:bhybajq) ([raw file](https://github.com/cockroachdb/cockroach/blob/63d55c2bfe64be3b40ce9b43e15fcaced0984ed9/pkg/util/tracing/jaegerjson/jaeger_json.go#L16)):*
> ```Go
> // limitations under the License.
> 
> // This file was copied from
> ```

hey Ben, is it OK to copy this file from the Apache-licensed Jaeger like this?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47303)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/util/tracing/jaegerjson/jaeger_json.go, line 16 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/47303#-M4WJNhZA8_EJgFlLOk4:-M4WM_fv0zmpCOnHskV6:baigqi7) ([raw file](https://github.com/cockroachdb/cockroach/blob/63d55c2bfe64be3b40ce9b43e15fcaced0984ed9/pkg/util/tracing/jaegerjson/jaeger_json.go#L16)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

hey Ben, is it OK to copy this file from the Apache-licensed Jaeger like this?
</blockquote></details>

I meant hey @bdarnell, is it OK to copy this file from the Apache-licensed Jaeger like this?

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

Very nice work!  Consider backporting this to 20.1.1.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47303#-:-M4XEN2mA16rbmhn1QhW:b2ka8f4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @RaduBerinde)

___
*[pkg/util/tracing/tags.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47303#-M4XD31Q-TSVL1DYUrQ4:-M4XD31R4rFj7Mk50y9e:b-aqkzlp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ffcef6cc35a40045b77a518b817b7142f15d57b/pkg/util/tracing/tags.go#L26)):*
> ```Go
> 
> // Apply is part of the opentracing.StartSpanOption interface.
> //
> ```

[nit] perhaps mention the remapping here as well
___
*[pkg/util/tracing/tags.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47303#-M4XCxYk4v0YghsOS_xi:-M4XCxYlCyogKNAJsaS0:b-mm07gl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ffcef6cc35a40045b77a518b817b7142f15d57b/pkg/util/tracing/tags.go#L29)):*
> ```Go
> // Note that our tracer does not call Apply() for this options. Instead, it
> // recognizes it as a special case and treats it more efficiently, avoiding
> // allocations for each tag. The Apply() is still used by shadow tracers.
> ```

[nit] remove The
___
*[pkg/util/tracing/tags_test.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47303#-M4XDEiH3HWdpm1-Zlid:-M4XDEiH3HWdpm1-Zlie:br4t8x) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ffcef6cc35a40045b77a518b817b7142f15d57b/pkg/util/tracing/tags_test.go#L25)):*
> ```Go
> 	tr.setShadowTracer(&mockTracerManager{}, &shadowTracer)
> 
> 	l := logtags.SingleTagBuffer("tag1", "val1")
> ```

maybe register some tag translations for some of the tags in this test

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47303)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/util/tracing/jaegerjson/jaeger_json.go, line 16 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/47303#-M4WJNhZA8_EJgFlLOk4:-M4ZXCD91j2Yl3MJM5l9:bbqcl4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/63d55c2bfe64be3b40ce9b43e15fcaced0984ed9/pkg/util/tracing/jaegerjson/jaeger_json.go#L16)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I meant hey @bdarnell, is it OK to copy this file from the Apache-licensed Jaeger like this?
</blockquote></details>

From a licensing perspective this is fine. If we haven't modified this file then it would be nice to depend on it instead of copying it. Does it pull in too much junk to depend on this package? (the entire jaeger repo is huge, but so is etcd and we're able to depend on etcd/raft without pulling the rest of etcd into vendor).

**Review by andreimatei — COMMENTED** [review]
> Very nice work! Consider backporting this to 20.1.1.


I'd like to backport it to 20.1.0. You don't think so?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47303#-:-M4_t3Tf2w8KcbpBIvwy:b-bcrqbn)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bdarnell and @RaduBerinde)

___
*[pkg/util/tracing/tags.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47303#-M4XD31Q-TSVL1DYUrQ4:-M4__SDCDMLjihAkAwbP:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ffcef6cc35a40045b77a518b817b7142f15d57b/pkg/util/tracing/tags.go#L26)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] perhaps mention the remapping here as well
</blockquote></details>

done
___
*[pkg/util/tracing/tags.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47303#-M4XCxYk4v0YghsOS_xi:-M4__TKw-YAqMJOunwCP:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ffcef6cc35a40045b77a518b817b7142f15d57b/pkg/util/tracing/tags.go#L29)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] remove The
</blockquote></details>

done
___
*[pkg/util/tracing/tags_test.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47303#-M4XDEiH3HWdpm1-Zlid:-M4ZoYnM2tYlPCbwXZ7j:b-491m96) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ffcef6cc35a40045b77a518b817b7142f15d57b/pkg/util/tracing/tags_test.go#L25)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

maybe register some tag translations for some of the tags in this test
</blockquote></details>

the test does this below. Or did you mean something else?
___
*[pkg/util/tracing/jaegerjson/jaeger_json.go, line 16 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/47303#-M4WJNhZA8_EJgFlLOk4:-M4_Yrv92BfF1ZHjeVCW:bbm5znv) ([raw file](https://github.com/cockroachdb/cockroach/blob/63d55c2bfe64be3b40ce9b43e15fcaced0984ed9/pkg/util/tracing/jaegerjson/jaeger_json.go#L16)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

From a licensing perspective this is fine. If we haven't modified this file then it would be nice to depend on it instead of copying it. Does it pull in too much junk to depend on this package? (the entire jaeger repo is huge, but so is etcd and we're able to depend on etcd/raft without pulling the rest of etcd into vendor). 
</blockquote></details>

I've switched to vendoring. The package that I need doesn't pull in crap.

Originally I hadn't done that because, as a matter of policy, I was thinking that if I only want some data definition and not actual code, a copy-paste is simpler for everybody. But since I have to fight the copyright-linter anyway, screw it.

**Review by andreimatei — COMMENTED** [review]
> I'd like to backport it to 20.1.0. You don't think so?

Actually, it seems like we're pretty close to cutting an RC, so maybe I'll wait for 20.1.1.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47303#-:-M4a3OpADFznbxa7pOlc:bhko9cf)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bdarnell and @RaduBerinde)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47303#-:-M4aYoOx1hf8w_gr7yMi:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bdarnell and @RaduBerinde)

**Comment by RaduBerinde** [comment]
Added a docs-todo label to add info about this file in https://www.cockroachlabs.com/docs/dev/explain-analyze.html#debug-option (for master and for 20.1.1)

**Pull request merged**
