### PR TITLE
release-23.2: roachtest: use secure clusters and non root authentication by default

### PR DESCRIPTION
**Pull request by DarrylWong**
This backports a series of PRs that culminate in roachtests using non root authentication by default.

Backport:
  * 1/1 commits from "roachprod: remove default port assumption in start and start-sql" (#114097)
  * 1/1 commits from "roachtest: specify port for post test timeseries collection" (#116695)
  * 1/1 commits from "roachtest: pass startopts to SetDefaultPort helpers by reference" (#116452)
  * 1/1 commits from "roachprod: revert AdminUIPort back to DefaultAdminUIPort" (#117141)
  * 1/1 commits from "roachtest: add check that network/authentication test blocks traffic" (#118112)
  * 3/3 commits from "roachtest: create secure clusters by default" (#118504)
  * 1/1 commits from "roachtest: run pg_regress on insecure clusters" (#119136)
  * 1/1 commits from "roachtest: run follower-reads/mixed-version on insecure mode" (#119143)
  * 1/1 commits from "roachtest: use http url in follower-reads test" (#119250)
  * 5/5 commits from "roachprod: small fixes and refactors for pgurl" (#119323)
  * 3/3 commits from "roachtest: use non root authentication by default" (#119310)
  * 1/1 commits from "awsdms: don't use secure roachprod cluster" (#119394)
   * 1/1 commits from "roachtest: flip restore cluster default" (#119774)
  * 1/1 commits from "roachtest: escape url in debug zip" (#119996)

Please see individual PRs for details.

Epic: None
Fixes: None
Release justification: Test only change.

### CODE REVIEW

**Comment by DarrylWong** [comment]
[Gonna go ahead and rerun the entire suite.](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14287972?hideProblemsFromDependencies=false&hideTestsFromDependencies=false) There were A LOT of merge conflicts.

**Comment by srosenberg** [comment]
> I can't figure out `tpchvec/direct_scans/mt-shared-process` though. For some reason it errors out with `pq: operation is disabled within a virtual cluster` when trying to scatter the tables. It's not a secure cluster issue, because it works when I use the old multitenant API with a secure cluster. But I looked for a decent bit and I don't see any divergences from the roachprod/roachtest side.
> 

It appears in Renato's recent PR [1] he may have run into a similar issue. He's explicitly setting `sql.split_at.allow_for_secondary_tenant.enabled` via the system (tenant) connection, so that the setting propagates into the app tenant. Note that this setting (`SecondaryTenantSplitAtEnabled`) is intended to be enabled by default, and indeed for unit tests, `grantDefaultTenantCapabilities` ensures these settings are enabled and propagated. I am not sure why we're not following the same logic in roachtest. @herkolategan Any ideas?

For now, you could follow the same workaround by enabling `SecondaryTenantScatterEnabled` via the system tenant, before the app tenant is created.

[1] https://github.com/cockroachdb/cockroach/blame/41da9eccc216413c09cc66ad4c6bfa5f92c506e3/pkg/cmd/roachtest/tests/multitenant_tpch.go#L109-L115

> For now I reverted it back to the old API but if anyone has an idea I'm happy to dig into it again.

It's strange that it works on master? I also don't see anything which explicitly enables `SecondaryTenantScatterEnabled` in the app tenant.

**Review by srosenberg — APPROVED** [review]

**Comment by herkolategan** [comment]
> It's strange that it works on master?

Indeed, I brushed over the code, and no trace of setting those cluster settings. I'm curious if we ran the test from master with an older cockroach binary if the same would happen. I'll look into this a bit.

> For now I reverted it back to the old API but if anyone has an idea I'm happy to dig into it again.

This should likely have been part of the port, so I think it would be a good idea to rather add default capabilities somewhere. Would need to decide if it's a convenience method on the `roachtest` side, or part of a flag/default on the `roachprod` side when starting a shared process tenant.

> I am not sure why we're not following the same logic in `roachtest`.

I think at the time we haven't ported anything that required the settings yet. May be a good time to formalise and implement it now.

**Comment by herkolategan** [comment]
So my suspicion was correct, *master/roachtest* does indeed fail when running against an older version of cockroach (I used 23.2.2 binaries). But running against the latest passes (used the 24 alpha cut). Thus something must have changed in cockroach between those versions that allows not passing that setting; question is if this is a bug?

**Review by herkolategan — APPROVED** [review]
Thanks for doing this backport! For maintenance it would probably be nice to have the new MT API backported as well, but there will definitely be some divergence as on master the defaults for shared tenant capabilities seems to have changed, and need to be accounted for.

**Comment by DarrylWong** [comment]
>For now, you could follow the same workaround by enabling SecondaryTenantScatterEnabled

Nice, that did the trick!

>The default capabilities for shared tenants have been updated, hence why this passes on master, but the backport fails.

That makes sense. 

>For maintenance it would probably be nice to have the new MT API backported as well

👍 I've added in the setting change and reverted back to the new API.

**Comment by DarrylWong** [comment]
TFTRs!

**Pull request merged**
