### PR TITLE
sql: use AmbientContext in Executor

### PR DESCRIPTION
**Pull request by RaduBerinde**
Part of #9807.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10006)

### CODE REVIEW

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/pgwire/v3.go, line 141 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10006#-KU8-5b9rN0XVRpDCtUZ:-KU8-5b9rN0XVRpDCtU_:b-xudjht) ([raw file](https://github.com/cockroachdb/cockroach/blob/a786d91a673ca1d892c7ba06fdc18468f97e77fd/pkg/sql/pgwire/v3.go#L141)):*
> ```Go
> 		writeBuf: writeBuffer{bytecount: metrics.BytesOutCount},
> 		metrics:  metrics,
> 		session:  sql.NewSession(context.TODO(), sessionArgs, executor, conn.RemoteAddr()),
> ```

well if you've made the one in `startupSession` be `context.Background`, I think we should use the same here? Or the other way around?
I'm not sure what we want from this context here. Maybe a tag with the client's address?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10006#-:-KU8-d36AAlKEmRjV7bB:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/pgwire/v3.go, line 141 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10006#-KU8-5b9rN0XVRpDCtUZ:-KU804LCyn2cwbJaXblU:b9u0egs) ([raw file](https://github.com/cockroachdb/cockroach/blob/a786d91a673ca1d892c7ba06fdc18468f97e77fd/pkg/sql/pgwire/v3.go#L141)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> well if you've made the one in `startupSession` be `context.Background`, I think we should use the same here? Or the other way around?
> I'm not sure what we want from this context here. Maybe a tag with the client's address?
> 
</details>
Switched to `Background`. We set a `client` tag with the address inside `NewSession`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10006)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/pgwire/v3.go, line 141 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10006#-KU8-5b9rN0XVRpDCtUZ:-KU81vaWjkuFz2SXYpkV:btmbrym) ([raw file](https://github.com/cockroachdb/cockroach/blob/a786d91a673ca1d892c7ba06fdc18468f97e77fd/pkg/sql/pgwire/v3.go#L141)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Switched to `Background`. We set a `client` tag with the address inside `NewSession`
</details>
ah, right. Well but maybe we should extract that out to the caller, so that `startupSession` and maybe other internal users can set a more specific tag?
Anyway no big deal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10006#-:-KU82BgYKUQfpxrdCjjy:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/pgwire/v3.go, line 141 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10006#-KU8-5b9rN0XVRpDCtUZ:-KU851ahgmaT89ZRRhnz:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a786d91a673ca1d892c7ba06fdc18468f97e77fd/pkg/sql/pgwire/v3.go#L141)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> ah, right. Well but maybe we should extract that out to the caller, so that `startupSession` and maybe other internal users can set a more specific tag?
> Anyway no big deal.
</details>
Good idea, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10006)*

**Comment by tamird** [comment]
Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor.go, line 252 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10006#-KU8SGpsyo6I_ApfVAMy:-KU8SGptUKdYbUAi_o7Q:bzvzs0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecb247d997cd778ab7de5065a76d9be5dc119aad/pkg/sql/executor.go#L252)):*
> ```Go
> func NewExecutor(cfg ExecutorConfig, stopper *stop.Stopper) *Executor {
> 	if cfg.AmbientCtx.Tracer == nil {
> 		panic("ExecutorConfig.AmbientCtx must have a tracer")
> ```

is this a thing? in other words, do we assert this way on other similar cases? I'd just as soon remove this.

---

*[pkg/sql/executor.go, line 290 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10006#-KU8SU9yUasCCnRzYTQp:-KU8SU9znfzGcJoOGevw:bq7ood1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecb247d997cd778ab7de5065a76d9be5dc119aad/pkg/sql/executor.go#L290)):*
> ```Go
> 	startupSession := NewSession(ctx, SessionArgs{}, exec, nil)
> 	if err := exec.virtualSchemas.init(&startupSession.planner); err != nil {
> 		panic(err)
> ```

`log.Fatal(ctx, err)`?

---

*[pkg/sql/session.go, line 491 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10006#-KU8T879h1R8zZvVMin-:-KU8T879h1R8zZvVMin0:bo93rw9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecb247d997cd778ab7de5065a76d9be5dc119aad/pkg/sql/session.go#L491)):*
> ```Go
> 					results[scEntry.idx] = Result{Err: err}
> 				}
> 				log.Warningf(ctx, "Error executing schema change: %s", err)
> ```

downcase "error" while you're here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10006)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor.go, line 252 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10006#-KU8SGpsyo6I_ApfVAMy:-KU8yLUwvVG8ocCpKN2t:b-vwf37z) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecb247d997cd778ab7de5065a76d9be5dc119aad/pkg/sql/executor.go#L252)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> is this a thing? in other words, do we assert this way on other similar cases? I'd just as soon remove this.
</details>
In this layer we explicitly start root spans for sql transactions using this tracer, so we need it to be set.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10006)*

**Comment by RaduBerinde** [comment]
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/executor.go, line 252 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10006#-KU8SGpsyo6I_ApfVAMy:-KU8zgsjxtBmA4ikVtiE:baz8tzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecb247d997cd778ab7de5065a76d9be5dc119aad/pkg/sql/executor.go#L252)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> In this layer we explicitly start root spans for sql transactions using this tracer, so we need it to be set.
</details>
Hm, although technically that's no different than other layers where we use `AnnotateCtxWithSpan`. Removed.

---

*[pkg/sql/executor.go, line 290 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10006#-KU8SU9yUasCCnRzYTQp:-KU8z-CNaTsEb08iA4CJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecb247d997cd778ab7de5065a76d9be5dc119aad/pkg/sql/executor.go#L290)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> `log.Fatal(ctx, err)`?
</details>
Done.

---

*[pkg/sql/session.go, line 491 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10006#-KU8T879h1R8zZvVMin-:-KU8zJfAknDlhrKUzl4k:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecb247d997cd778ab7de5065a76d9be5dc119aad/pkg/sql/session.go#L491)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> downcase "error" while you're here
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10006)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10006)*

**Comment by tamird** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10006#-:-KU90tojOsCueONKH-_G:bnfp4nl)*

**Pull request merged**
