### PR TITLE
cli/start: unify code between `cockroach start` and `cockroach mt start-sql`

### LINKED ISSUE #89974: cli: `cockroach mt start-sql` does not react to sigint/sigterm before initialization completes
Found while working on #89966.

**Describe the problem**

I ran `cockroach mt start-sql` and it got stuck during initialization (this was expected)

However after that I was not able to terminate it using SIGINT/SIGTERM. Only SIGKILL could get rid of it.

Jira issue: CRDB-20525
Epic: CRDB-14537

### LINKED ISSUE #90524: server: missing support for DISABLE_STARTING_BACKGROUND_JOBS in secondary tenants
The parameter `jobAdoptionStopFile` in `sqlServerArgs` is not set properly for secondary tenants. It should.

Epic: CRDB-14537

Jira issue: CRDB-20819

### PR DESCRIPTION
**Pull request by knz**
Fixes #89974.
Fixes #90524.

This PR merges the server initialization code between `cockroach start` and `cockroach mt start-sql`.

In doing so, it brings `cockroach mt start-sql` closer to what we expect from proper CockroachDB server processes:

- it fixes support for the (test-only)
  `COCKROACH_EXPERIMENTAL_LINEARIZABLE` env var. (from #4754)

- it adds a tracing span for the startup code. (from https://github.com/cockroachdb/cockroach/pull/8712!!)

- it properly supports `--listening-url-file`. (from https://github.com/cockroachdb/cockroach/pull/15468)

- it properly does sanitization of `--external-io-dir`. (from https://github.com/cockroachdb/cockroach/pull/19725)

- it sets the proper log severity level for gRPC. (from https://github.com/cockroachdb/cockroach/pull/20308)

- it reports the command-line and env config to logs. (from https://github.com/cockroachdb/cockroach/pull/21344)

- it prevents startup if there is a `_CRITICAL_ALERT.txt` file
  in the store directory. (from https://github.com/cockroachdb/cockroach/pull/42401)

- sets the umask for newly created file to remove "other" permission
  bits. This was a security team request originally. (from https://github.com/cockroachdb/cockroach/pull/44043)

- it recovers support for `DISABLE_STARTING_BACKGROUND_JOBS`. (from #44786)

- it sets `GOMAXPROCS` from current cgroup limits. (from https://github.com/cockroachdb/cockroach/pull/57390)

- it stops the server early if the storage disk is full. (from https://github.com/cockroachdb/cockroach/pull/66893)

- it fixes support for the `COCKROACH_DISABLE_SPAN_CONFIGS` config env
  var. (from #73876)

See the individual commit for details.

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
I'm sure this is all God's work and I'm excited to review it, but please do me a favor and review #90208 so we can rebase this on it. They'll conflict (hopefully for the better), and I was first :P

> First 10 commits in this PR from #90143 and #90173. Please ignore them during review.

Did you mean first 9 commits? I can't figure out where `r10 -  cli/start: extract the server init deps into an interface` comes from, and I think I should be looking at it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-:-NErSAqy2_IylKjdjurd:bezs3lu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/cli/mt_start_sql.go` line 65 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NErQmLXDFGkM_uD_pmu:-NErQmLXDFGkM_uD_pmv:b-sjgykf) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc858f26b9c3e166db9ab34b72d6199164241fa3/pkg/cli/mt_start_sql.go#L65)):*
> ```Go
> 			return err
> 		}
> 		// This value is injected in order to have something populated during startup.
> ```

since you're taking all this blame, perhaps check whether all or some this comment can go away.
___
*[`pkg/cli/start.go` line 570 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NErOZRh2gKTX_QGQRfj:-NErOZRh2gKTX_QGQRfk:b6gh72u) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf996727642a61245bfe8153439468dcea5e1b0f/pkg/cli/start.go#L570)):*
> ```Go
> 		// Run SQL for new clusters.
> 		//
> 		// TODO(knz): If/when we want auto-creation of an initial admin user,
> ```

think twice about whether this TODO needs to exist
___
*[`pkg/cli/start.go` line 615 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NErPT8w8HMe0heVwaDN:-NErPT8w8HMe0heVwaDO:b-hgk8h8) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf996727642a61245bfe8153439468dcea5e1b0f/pkg/cli/start.go#L615)):*
> ```Go
> 	maybeRunInitialSQL func(context.Context, serverStartupInterface) error,
> 	serverType redact.SafeString,
> ) (getS func() serverShutdownInterface, srvStatus *serverStatus, serverStartupErrC <-chan error) {
> ```

Shameless plug, but this `getS` thing bothered me and I believe I've gotten rid of it somehow in #90208.
It might look better if you rebase :P.
___
*[`pkg/cli/start.go` line 637 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NErPw2P9GpWukEWdC2B:-NErPw2Q6cMPQ3CdIuqS:b-59x0g5) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf996727642a61245bfe8153439468dcea5e1b0f/pkg/cli/start.go#L637)):*
> ```Go
> 			}
> 		}()
> 		// When the start up goroutine completes, so can the start up span
> ```

this comment doesn't fully make sense any more

**Comment by knz** [comment]
TODO(self): mention job prevention start #90524

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-:-NFPwhEr8_yEH18luEzA:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NFPfgdY4202AqAKPKkr):*
I've red this patch several times, and I have no idea what its effects are - like I don't know what the default for what store was before, and how it changes. I don't really care, but consider spelling it out more in the commit message - particularly if it actually has some user effect.
___
*[`pkg/cli/mt_start_sql.go` line 89 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NFPpakoECcRIeYc9FqS:-NFPpakoECcRIeYc9FqT:b-4xz2zz) ([raw file](https://github.com/cockroachdb/cockroach/blob/71cecb626e16871a7b231b8cfcf2746d08178d73/pkg/cli/mt_start_sql.go#L89)):*
> ```Go
> 	// Change the permission mask for all created files.
> 	//
> 	// We're considering everything produced by a cockroach node
> ```

I'm trying to not police bro, but you never wrap :)
___
*[`pkg/cli/mt_start_sql.go` line 110 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NFPq4BzBmIiVJ2BWR5s:-NFPq4BzBmIiVJ2BWR5t:b-69aqdi) ([raw file](https://github.com/cockroachdb/cockroach/blob/71cecb626e16871a7b231b8cfcf2746d08178d73/pkg/cli/mt_start_sql.go#L110)):*
> ```Go
> 	// flapping exit code can affect alerting, including the alerting
> 	// performed within CockroachCloud.
> 	if err := exitIfDiskFull(vfs.Default, serverCfg.Stores.Specs); err != nil {
> ```

does this apply to sql nodes? Same with `serverCfg.StorageEngine` below.
___
*[`pkg/cli/mt_start_sql.go` line 286 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NFPr3Vj81HeOuMO1DeQ:-NFPr3Vj81HeOuMO1DeR:bvsba6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/71cecb626e16871a7b231b8cfcf2746d08178d73/pkg/cli/mt_start_sql.go#L286)):*
> ```Go
> 	log.Flush()
> 
> 	// When the start up completes, so can the start up span
> ```

why isn't this done immediately after opening the span, both here and in `runStart()`?
___
*[`pkg/cli/start.go` line 434 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NFPiteu6emgqj-NHECD:-NFPitev6fFsZLCsqRO6:boslcx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/42b67a52d7d302b6d3d3d727077d490f2bdd582b/pkg/cli/start.go#L434)):*
> ```Go
> 		return clierror.NewError(err, exit.FatalError())
> 	}
> 	stopper.SetTracer(serverCfg.BaseConfig.AmbientCtx.Tracer)
> ```

`serverCfg.Tracer`
___
*[`pkg/cli/start.go` line 434 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NFPkeNh6vBNuhfnsrJs:-NFPjSGxDkEtg8vNC-Jt:bcbbydr) ([raw file](https://github.com/cockroachdb/cockroach/blob/42b67a52d7d302b6d3d3d727077d490f2bdd582b/pkg/cli/start.go#L434)):*
> ```Go
> 		return clierror.NewError(err, exit.FatalError())
> 	}
> 	stopper.SetTracer(serverCfg.BaseConfig.AmbientCtx.Tracer)
> ```

Feel free to ignore, but any chance I can snipe you into figuring out a better patch for the tracer?
There's a couple of things that bother me with the status quo:
- server.NewServer()` also does what you're doing here, so one of the two calls is unnecessary.
- The stopper allocates a useless tracer that gets discarded here.

I think ideally a function like this `runStart()` should create the tracer explicitly, and then passing it both into the stopper, and into `serverCfg`; I also think we should make `serverCfg` not be a global any more (what's up with that anyway), 
___
*[`pkg/cli/start.go` line 473 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NFPmdCoCJrldGUMCNxt:-NFPmdCoCJrldGUMCNxu:b-g6b3gx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6566574f9e8ea479141527caab0c7d45738147c/pkg/cli/start.go#L473)):*
> ```Go
> 
> 	// Configure the default storage engine.
> 	// NB: we only support one engine type for now.
> ```

scratch the "for now". Better yet, scratch the whole comment :P - we're hardly "configuring the default storage engine".
In fact, is this `engine.EngineType` vestigial / can it be deleted?
___
*[`pkg/cli/start.go` line 653 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NFPsHI7AfQCkcLDHuKb:-NFPsHI7AfQCkcLDHuKc:b8f3220) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0aca0c515b49487743fae0f6c4a78ebf779cbba/pkg/cli/start.go#L653)):*
> ```Go
> 				// Run SQL for new clusters.
> 				//
> 				// TODO(knz): If/when we want auto-creation of an initial admin user,
> ```

If it starts with a "if we want", is it really a `TODO`?
I am curious what this is referring to, though. We already create a `root` user for example somehow,  don't we?

In any case, consider scratching the comment. I doubt it serves enough purpose to justify its existence.
___
*[`pkg/cli/start.go` line 656 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NFPsaPi4oVKthClG5Zi:-NFPsaPi4oVKthClG5Zj:b-if3awv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0aca0c515b49487743fae0f6c4a78ebf779cbba/pkg/cli/start.go#L656)):*
> ```Go
> 				// this can be achieved here.
> 				//
> 				// TODO(knz): It's unfortunate that this conditional is piercing the
> ```

it's not clear what the `TODO` is, so make it a note, if anything.
But how about making `runInitialSQL` be a method on the `Server`, and then it can be in the interface too.
___
*[`pkg/cli/start.go` line 651 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NFPvAkn-d8AngAHHu5S:-NFPvAkn-d8AngAHHu5T:bua0mgj) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf996727642a61245bfe8153439468dcea5e1b0f/pkg/cli/start.go#L651)):*
> ```Go
> 			// Instantiate the server.
> 			var err error
> 			s, err = newServerFn(ctx, *serverCfg, stopper)
> ```

you sure this call needs to be async? If it doesn't, let's make it sync and return the server instead of the `getS()` things. If an async scheme needs to stay for some reason, return a channel instead.
___
*[`pkg/server/config.go` line 814 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NFPol4L3mJSfFGz-lK6:-NFPol4L3mJSfFGz-lK7:b3booj4) ([raw file](https://github.com/cockroachdb/cockroach/blob/71cecb626e16871a7b231b8cfcf2746d08178d73/pkg/server/config.go#L814)):*
> ```Go
> 
> func (cfg *Config) readSQLEnvironmentVariables() {
> 	cfg.SpanConfigsDisabled = envutil.EnvOrDefaultBool("COCKROACH_DISABLE_SPAN_CONFIGS", cfg.SpanConfigsDisabled)
> ```

is this something that applies to sql servers?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90176)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NFPfgdY4202AqAKPKkr):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I've red this patch several times, and I have no idea what its effects are - like I don't know what the default for what store was before, and how it changes. I don't really care, but consider spelling it out more in the commit message - particularly if it actually has some user effect.
</blockquote></details>

Good point. Done.
___
*[`pkg/cli/mt_start_sql.go` line 89 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NFPpakoECcRIeYc9FqS:-NFTbqXnBd1HMCe3zyeQ:b4zqmrk) ([raw file](https://github.com/cockroachdb/cockroach/blob/71cecb626e16871a7b231b8cfcf2746d08178d73/pkg/cli/mt_start_sql.go#L89)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'm trying to not police bro, but you never wrap :)
</blockquote></details>

These comments are copy-pasted from start.go. I didn't write them. Also I wanted them to be identical across the two files so I could more easily see what differs with `diff -y`.

Anyway this is moot as all this code disappears in the last commit.
___
*[`pkg/cli/mt_start_sql.go` line 110 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NFPq4BzBmIiVJ2BWR5s:-NFTc-Sf5Cn3BbA7xdQu:b-nx2pz) ([raw file](https://github.com/cockroachdb/cockroach/blob/71cecb626e16871a7b231b8cfcf2746d08178d73/pkg/cli/mt_start_sql.go#L110)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

does this apply to sql nodes? Same with `serverCfg.StorageEngine` below.
</blockquote></details>

Yes it does. They use a store for disk spilling.
___
*[`pkg/cli/mt_start_sql.go` line 286 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NFPr3Vj81HeOuMO1DeQ:-NFTd9G-DB4NbFI3pbqx:b-gsk8by) ([raw file](https://github.com/cockroachdb/cockroach/blob/71cecb626e16871a7b231b8cfcf2746d08178d73/pkg/cli/mt_start_sql.go#L286)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

why isn't this done immediately after opening the span, both here and in `runStart()`?
</blockquote></details>

Because we want only finish the span when the startup goroutine completes. In this file *in this commit* it's not a goroutine yet -- the goroutine is introduced in a later commit.
___
*[`pkg/cli/mt_start_sql.go` line 65 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NErQmLXDFGkM_uD_pmu:-NFTd57J1mktKNkjc06a:b-fhxfol) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc858f26b9c3e166db9ab34b72d6199164241fa3/pkg/cli/mt_start_sql.go#L65)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

since you're taking all this blame, perhaps check whether all or some this comment can go away.
</blockquote></details>

Yah good question.
Filed https://github.com/cockroachdb/cockroach/issues/90831 to follow up.
___
*[`pkg/cli/start.go` line 434 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NFPiteu6emgqj-NHECD:-NFTfS4e1IN37xZHOR1A:be8r5kv) ([raw file](https://github.com/cockroachdb/cockroach/blob/42b67a52d7d302b6d3d3d727077d490f2bdd582b/pkg/cli/start.go#L434)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

`serverCfg.Tracer`
</blockquote></details>

I'll do this in the next PR.
___
*[`pkg/cli/start.go` line 434 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NFPkeNh6vBNuhfnsrJs:-NFTfUSk9jOXjAMix8FF:be8r5kv) ([raw file](https://github.com/cockroachdb/cockroach/blob/42b67a52d7d302b6d3d3d727077d490f2bdd582b/pkg/cli/start.go#L434)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Feel free to ignore, but any chance I can snipe you into figuring out a better patch for the tracer?
There's a couple of things that bother me with the status quo:
- server.NewServer()` also does what you're doing here, so one of the two calls is unnecessary.
- The stopper allocates a useless tracer that gets discarded here.

I think ideally a function like this `runStart()` should create the tracer explicitly, and then passing it both into the stopper, and into `serverCfg`; I also think we should make `serverCfg` not be a global any more (what's up with that anyway), 
</blockquote></details>

I'll do this in the next PR.
___
*[`pkg/cli/start.go` line 473 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NFPmdCoCJrldGUMCNxt:-NFTdaFs2u6ihF9sq-Hm:b4p4k4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6566574f9e8ea479141527caab0c7d45738147c/pkg/cli/start.go#L473)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

scratch the "for now". Better yet, scratch the whole comment :P - we're hardly "configuring the default storage engine".
In fact, is this `engine.EngineType` vestigial / can it be deleted?
</blockquote></details>

Removed the comment. I'll defer commenting on the StorageEngine field to someone in the storage team, in https://github.com/cockroachdb/cockroach/issues/90832
___
*[`pkg/cli/start.go` line 653 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NFPsHI7AfQCkcLDHuKb:-NFTeyva8zlZtWk-VhsF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0aca0c515b49487743fae0f6c4a78ebf779cbba/pkg/cli/start.go#L653)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

If it starts with a "if we want", is it really a `TODO`?
I am curious what this is referring to, though. We already create a `root` user for example somehow,  don't we?

In any case, consider scratching the comment. I doubt it serves enough purpose to justify its existence.
</blockquote></details>

Done.
___
*[`pkg/cli/start.go` line 656 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NFPsaPi4oVKthClG5Zi:-NFTf1-6BapKpotOEFII:b-cwa4vc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0aca0c515b49487743fae0f6c4a78ebf779cbba/pkg/cli/start.go#L656)):*
> how about making runInitialSQL be a method on the Server

Good idea. I'll do this in a separate followup PR.
___
*[`pkg/cli/start.go` line 570 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NErOZRh2gKTX_QGQRfj:-NFTeEt095rdhlarBjEl:b-ypnthv) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf996727642a61245bfe8153439468dcea5e1b0f/pkg/cli/start.go#L570)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

think twice about whether this TODO needs to exist
</blockquote></details>

It's removed in a later commit.
___
*[`pkg/cli/start.go` line 615 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NErPT8w8HMe0heVwaDN:-NFTeI3O47s_B7BmS6cM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf996727642a61245bfe8153439468dcea5e1b0f/pkg/cli/start.go#L615)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Shameless plug, but this `getS` thing bothered me and I believe I've gotten rid of it somehow in #90208.
It might look better if you rebase :P.
</blockquote></details>

Done.
___
*[`pkg/cli/start.go` line 637 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NErPw2P9GpWukEWdC2B:-NFTeKg44zPwNpa6Y8-y:b-huivew) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf996727642a61245bfe8153439468dcea5e1b0f/pkg/cli/start.go#L637)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this comment doesn't fully make sense any more
</blockquote></details>

It does! startupSpan is bound to startupCtx whose scope is bound to this function/goroutine.
___
*[`pkg/cli/start.go` line 651 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NFPvAkn-d8AngAHHu5S:-NFTeTXW739DM9dpwPSX:bk04vct) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf996727642a61245bfe8153439468dcea5e1b0f/pkg/cli/start.go#L651)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

you sure this call needs to be async? If it doesn't, let's make it sync and return the server instead of the `getS()` things. If an async scheme needs to stay for some reason, return a channel instead.
</blockquote></details>

Yes it needs to remain async because we've seen it hang in the past. (It can also hang because of a disk stall etc)

The async scheme is solved by your new definition of the serverStatus interface. So there's nothing else to do here.
___
*[`pkg/server/config.go` line 814 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NFPol4L3mJSfFGz-lK6:-NFTfHDt4FUX45sFk2-r:bgm95o) ([raw file](https://github.com/cockroachdb/cockroach/blob/71cecb626e16871a7b231b8cfcf2746d08178d73/pkg/server/config.go#L814)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

is this something that applies to sql servers?
</blockquote></details>

Yep it does - the logic for span configs can be disabled sql-side with the SpanConfigsDisabled flag (this is even used in tests already)

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90176)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei)

___
*[`pkg/cli/start.go` line 656 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NFPsaPi4oVKthClG5Zi:-NFTrs2D4oPJjqrGBr7i:bbqlx5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0aca0c515b49487743fae0f6c4a78ebf779cbba/pkg/cli/start.go#L656)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

> how about making runInitialSQL be a method on the Server

Good idea. I'll do this in a separate followup PR.
</blockquote></details>

#90835

**Review by andreimatei — APPROVED** [review]
:lgtm: towards a unified future

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-:-NF_QB4hAYOmjeMR7SMu:b-hqq5gd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/cli/start.go` line 637 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NErPw2P9GpWukEWdC2B:-NF_Po5VDM94w56iwAbj:b-yo62o8) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf996727642a61245bfe8153439468dcea5e1b0f/pkg/cli/start.go#L637)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

It does! startupSpan is bound to startupCtx whose scope is bound to this function/goroutine.
</blockquote></details>

The "defined above" part doesn't really make much sense now that this is a separate function taking the span as an argument. Consider putting a comment on the argument saying that the function takes ownership.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90176)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei)

___
*[`pkg/cli/start.go` line 637 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/90176#-NErPw2P9GpWukEWdC2B:-NFiIJZoAjtBChAI8JIF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf996727642a61245bfe8153439468dcea5e1b0f/pkg/cli/start.go#L637)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

The "defined above" part doesn't really make much sense now that this is a separate function taking the span as an argument. Consider putting a comment on the argument saying that the function takes ownership.
</blockquote></details>

Done.

**Pull request merged**
