### PR TITLE
distsql: make 'Auto' the cluster default mode

### PR DESCRIPTION
**Pull request by rjnn**

### CODE REVIEW

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15442#-:-KimMKUG6IQrfuG9E7fV:bnfp4nl)*

**Comment by arjunravinarayan** [comment]
There are 3 outstanding test failures that need to be looked at:
- [ ] TestMonotonicInserts, which I have no idea why is failing.
- [ ] TestPGPreparedQuery, which I have no idea why is failing.
- [ ] TestQueryCounts, which is failing because it runs some queries, and counts up metrics on the number of queries run via SQL and DistSQL. However, turning DistSQL on changes the counts, which causes the test to fail. I have skipped the test for now.

**Comment by RaduBerinde** [comment]
With this change, we run most of the logictests in distsql auto mote (`default`) and on mode (`distsql`). I think maybe we should override it to off in the default mode to keep covering everything as we were until now.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15442#-:-KimTkQSCDm-sDo78cMO:b6hx8q3)*

**Comment by arjunravinarayan** [comment]
Done.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15442#-:-KimXcrOk4KaqiyCnnev:b-896fix)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/metric_test.go, line 49 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15442#-KimYeEu_fKGHyb5Xb5M:-KimYeEu_fKGHyb5Xb5N:b-e1cph) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3468bc08161eb49c617011bec107c8b4572f5ce/pkg/sql/metric_test.go#L49)):*
> ```Go
> func TestQueryCounts(t *testing.T) {
> 	defer leaktest.AfterTest(t)()
> 	t.Skipf("TODO(arjun): #15442")
> ```

we could override distsql mode to off instead of skipping.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15442)*

**Comment by arjunravinarayan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/metric_test.go, line 49 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15442#-KimYeEu_fKGHyb5Xb5M:-Kim_h9n4UbiFGUO9vov:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3468bc08161eb49c617011bec107c8b4572f5ce/pkg/sql/metric_test.go#L49)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

we could override distsql mode to off instead of skipping.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15442)*

**Comment by arjunravinarayan** [comment]
It appears the `TestMonotonicInserts` failure is more serious than we thought. @andreimatei is investigating, and I'm signing off for the night. This needs a little more work before it can be merged. To be continued...

**Comment by RaduBerinde** [comment]
The `TestPGPreparedQuery` failure is due to the serialization of an array. It is printed as `{x}` but that is not something the syntax accepts. This didn't trigger any error with logic tests because we don't support arrays as renders (we can't currently encode them in streams), but in this case it's just in a filter expression which is allowed. @knz what do you suggest? Format as `ARRAY[x]` all the time? Conditionally for `FmtParsable`?

**Comment by knz** [comment]
Yes I would suggest either `ARRAY[x]` all the time (for expressions! in results for pgwire we should keep the {} notation)

**Comment by RaduBerinde** [comment]
TestPGPreparedQuery should be fine now.

**Comment by arjunravinarayan** [comment]
Rebased off master, to see what the updated test statuses are.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15442#-:-Kipha6heCPOB_3hFlWJ:b-cqpii2)*

**Comment by arjunravinarayan** [comment]
It's just `TestMonotonicInserts` now.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15442#-:-Kipk5GlyTLnk3SGtbgp:b-ack96e)*

**Review by knz — APPROVED** [review]

**Comment by knz** [comment]
Are you pushing this big green button? :wink:

**Pull request merged**
