### PR TITLE
opt: separate IndexJoin operator

### PR DESCRIPTION
**Pull request by RaduBerinde**
While index join is at a high level a specific case of lookup join, it
has a lot of particularities that warrant a separate operator:
 - index joins are always exactly one output row per input row;
 - the column IDs that are input to index joins match column IDs from
   the table we are looking up into (specifically the PKs);
 - lookup joins will be created from joins and won't need to be
   considered for the pushdown rules specific to index joins.

This change adds `IndexJoinOp` and splits `LookupJoinOp` into
`LookupInnerJoinOp` and `LookupLeftJoinOp`. These lookup join ops are
not yet supported.

### CODE REVIEW

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 18 of 18 files at r1, 13 of 13 files at r2.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/memo/private_defs.go, line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27019#-LG6jhWM9pp2HWVpUc1a:-LG6jhWM9pp2HWVpUc1b:btf0skr) ([raw file](https://github.com/cockroachdb/cockroach/blob/be28fca056ba53883e76b55cb0dc80171418f616/pkg/sql/opt/memo/private_defs.go#L126)):*
> ```Go
> 	Table opt.TableID
> 
> 	// Cols specifies the set of columns that the scan operator projects. This
> ```

scan -> IndexJoin

---

*[pkg/sql/opt/ops/relational.opt, line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27019#-LG6l4hx6fG4BPuB02Qj:-LG6l4hx6fG4BPuB02Qk:b17lpk0) ([raw file](https://github.com/cockroachdb/cockroach/blob/be28fca056ba53883e76b55cb0dc80171418f616/pkg/sql/opt/ops/relational.opt#L138)):*
> ```
> }
> 
> # LookupInnerJoin represents an left outer join between an input expression and
> ```

LookupInnerJoin -> LookupLeftJoin
an left -> a left

---

*[pkg/sql/opt/xform/rules/limit.opt, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27019#-LG6mQBE5F54d1wAqgcc:-LG6mQBE5F54d1wAqgcd:b-mcdg1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/be28fca056ba53883e76b55cb0dc80171418f616/pkg/sql/opt/xform/rules/limit.opt#L22)):*
> ```
> 
> # PushLimitIntoIndexJoin pushes a limit through a lookup join, if we know that
> # the lookup join produces exactly one row per input row (most importantly,
> ```

Update comment since this only applies to index joins now

---

*[pkg/sql/opt/xform/rules/select.opt, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27019#-LG6my-2-rr5ysPuk6Vs:-LG6my-2-rr5ysPuk6Vt:bosgzmw) ([raw file](https://github.com/cockroachdb/cockroach/blob/be28fca056ba53883e76b55cb0dc80171418f616/pkg/sql/opt/xform/rules/select.opt#L102)):*
> ```
> # TODO(rytaft): try to find a mechanism for pushdown that is more powerful than
> # finding conjuncts that are fully bound.
> [ConstrainIndexJoinIndexScan, Explore]
> ```

Make the rule name match the comment

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27019#-:-LG6oWSq3_d7q4l3T4XN:bnfp4nl)*

**Comment by RaduBerinde** [comment]
TFTR!

I collapsed the lookup join ops back into a single op and stored the join type in the def like merge join (at @andy-kimball's suggestion).

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/memo/private_defs.go, line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27019#-LG6jhWM9pp2HWVpUc1a:-LG7HLEe6ijV0VrbOQMi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/be28fca056ba53883e76b55cb0dc80171418f616/pkg/sql/opt/memo/private_defs.go#L126)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

scan -> IndexJoin
</blockquote></details>

Done.

---

*[pkg/sql/opt/ops/relational.opt, line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27019#-LG6l4hx6fG4BPuB02Qj:-LG7IeJc9ZG0gR-zPp0G:b-jm1h98) ([raw file](https://github.com/cockroachdb/cockroach/blob/be28fca056ba53883e76b55cb0dc80171418f616/pkg/sql/opt/ops/relational.opt#L138)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

LookupInnerJoin -> LookupLeftJoin
an left -> a left
</blockquote></details>

Removed altogether.

---

*[pkg/sql/opt/xform/rules/limit.opt, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27019#-LG6mQBE5F54d1wAqgcc:-LG7Iokr524SryDVff5x:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/be28fca056ba53883e76b55cb0dc80171418f616/pkg/sql/opt/xform/rules/limit.opt#L22)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Update comment since this only applies to index joins now
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/rules/select.opt, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27019#-LG6my-2-rr5ysPuk6Vs:-LG7JMxd0UQCoovc_4JJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/be28fca056ba53883e76b55cb0dc80171418f616/pkg/sql/opt/xform/rules/select.opt#L102)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Make the rule name match the comment
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27019#-:-LG7JmHR7kpqbcaXFE_h:bbvy8vw)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 6 of 21 files at r3, 2 of 15 files at r5, 13 of 13 files at r6.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27019#-:-LG7M-gqE9qELHkz3FCt:bnfp4nl)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/memo/private_defs.go, line 122 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/27019#-LG7h3PO1ZTc3wykwsVa:-LG7h3PO1ZTc3wykwsVb:b-su356t) ([raw file](https://github.com/cockroachdb/cockroach/blob/f422d5597c5ded9f9009b9793d5f0e8fdc7f8f8f/pkg/sql/opt/memo/private_defs.go#L122)):*
> ```Go
> // operator.
> type IndexJoinDef struct {
> 	// Table identifies the table do to lookups in. The primary index is
> ```

NIT: `do to` => `to do`

---

*[pkg/sql/opt/memo/private_storage_test.go, line 487 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/27019#-LG7hfX7ABI54_3UjBKO:-LG7hfX7ABI54_3UjBKP:b11uzod) ([raw file](https://github.com/cockroachdb/cockroach/blob/f422d5597c5ded9f9009b9793d5f0e8fdc7f8f8f/pkg/sql/opt/memo/private_storage_test.go#L487)):*
> ```Go
> 		ps.internScanOpDef(scanOpDef)
> 		ps.internGroupByDef(groupByDef)
> 		ps.internMergeOnDef(mergeOnDef)
> ```

NIT: Missing index/lookup join here.

---

*[pkg/sql/opt/memo/testdata/logprops/lookup-join, line 38 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/27019#-LG7hpS47iobq6ZKNaIu:-LG7hpS509azBBu_8Fzg:btmnj80) ([raw file](https://github.com/cockroachdb/cockroach/blob/f422d5597c5ded9f9009b9793d5f0e8fdc7f8f8f/pkg/sql/opt/memo/testdata/logprops/lookup-join#L38)):*
> ```
>  ├── key: (1)
>  ├── fd: ()-->(3), (1)-->(2-4), (3,4)-->(1,2), (2,3)~~>(1,4)
>  ├── index-join a
> ```

Should this file be renamed to `index-join`? Probably some other files to consider as well.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27019#-:-LG7iaSD6GjD15Nf6-s5:bnfp4nl)*

**Pull request merged**
