### PR TITLE
sql: support LIMIT and ORDER BY in views

### PR DESCRIPTION
**Pull request by benesch**
Previously, LIMIT and ORDER BY clauses in view definitions were silently
ignored. For example, given the following view

    CREATE VIEW v AS SELECT generate_series FROM generate_series(1, 100) ORDER BY 1 DESC LIMIT 10

the following query would return 100 results in ascending order, instead
of the expected ten results in descending order:

    SELECT * FROM v

This commit ensures the above query instead observes the ORDER BY and
LIMIT specified in the view definition, as Postgres does. As in
Postgres, additional ORDER BY and LIMIT clauses can be specified at query time

    SELECT * FROM v ORDER BY 1 ASC LIMIT 10

in which case the effect is the same as if the view definition had been
specified inline as a subquery:

    SELECT *
      FROM (SELECT generate_series FROM generate_series(1, 100) ORDER BY 1 DESC LIMIT 10)
      ORDER BY 1 ASC LIMIT 10

---

XXX: The TODO I removed suggests there's some gotcha I'm not considering here.

### CODE REVIEW

**Comment by knz** [comment]
:lgtm_strong: 
You're not missing anything. The comment was stale. Thank you!

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/views, line 10 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20246#-KztEfKy5TX9s9LovyVU:-KztEfKzfZgVU-DeC5zM:b-6qzrwi) ([raw file](https://github.com/cockroachdb/cockroach/blob/568f810b2f664c38a663adc6973ef220b962aee0/pkg/sql/logictest/testdata/logic_test/views#L10)):*
> ```
> 
> statement ok
> CREATE VIEW v1 AS select a, b from t
> ```

nit: although the historical version of this logic test file uses lowercase view queries, for consistency with the other logic tests I'd rather see them uppercased throughout while you're around here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20246#-:-KztFOnHMjO5dsEBLyiY:b-agm99)*

**Review by a-robinson — APPROVED** [review]
Thanks for fixing this, @benesch!

**Comment by benesch** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/logictest/testdata/logic_test/views, line 10 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20246#-KztEfKy5TX9s9LovyVU:-L-8lRBgZxyDzQJta3ix:b-qsvnoa) ([raw file](https://github.com/cockroachdb/cockroach/blob/568f810b2f664c38a663adc6973ef220b962aee0/pkg/sql/logictest/testdata/logic_test/views#L10)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: although the historical version of this logic test file uses lowercase view queries, for consistency with the other logic tests I'd rather see them uppercased throughout while you're around here.
</blockquote></details>

Done. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20246)*

**Comment by knz** [comment]
:+1: thanks!

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20246#-:-L-CoalX1WB2KBktiEyX:bcpg9vb)*

**Comment by benesch** [comment]
Thank _you_ for the review!

**Comment by jseldess** [comment]
@benesch, are there other `SELECT` options that are not supported when used in views? If so, we should probably call them out in the [`CREATE VIEW`](https://www.cockroachlabs.com/docs/stable/create-view.html#parameters) docs. The only limitation mentioned is that `select *` is not supported.

**Comment by benesch** [comment]
To my knowledge that's the only remaining feature that's not supported.

**Pull request merged**
