### PR TITLE
distsql: support outer joins in interleavedReaderJoiner (no planning)

### PR DESCRIPTION
**Pull request by richardwu**
This PR adds support for OUTER joins for the full interleaved prefix
case in the interleavedReaderJoiner processor.

This PR does not introduce planning for OUTER joins using interleaved
joins (that will be in a follow-up PR along with corresponding logic
tests).

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
Unrelated to this PR, but it would be to replace the direct usage of `MultiRowFetcher` inside of `interleavedReaderJoiner`with an interface that covered `MultiRowFetcher.{Init,GetRangeInfo,StartScan,NextRow}`. That way we could benchmark the innards of `interleavedReaderJoiner` without the overhead of `MultiRowFetcher` distorting our view. I think doing that would also testing, though that isn't something I've looked at.

PS A similar argument applies to `tableReader`.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20768#-:-L0UdHsQl333sVri7vao:b-jm8agh)*

**Comment by RaduBerinde** [comment]
:lgtm:

The cleanup in the planning code and the new tests are unrelated to the changes in the interleavedReaderJoiner (right?). It would have been less confusing if those were a separate commit.

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/interleaved_reader_joiner_test.go, line 126 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20768#-L0opE8y9Yg-VN9BOga_:-L0opE8y9Yg-VN9BOgaa:byrugna) ([raw file](https://github.com/cockroachdb/cockroach/blob/010c3dce5d3d281c169c2357abb36c4e6c24ba6e/pkg/sql/distsqlrun/interleaved_reader_joiner_test.go#L126)):*
> ```Go
> 	cd3 := sqlbase.GetTableDescriptor(kvDB, sqlutils.TestDB, "child3")
> 
> 	pdCd1Spec := InterleavedReaderJoinerSpec{
> ```

These vars need some comments.

---

*[pkg/sql/distsqlrun/interleaved_reader_joiner_test.go, line 145 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20768#-L0op1MvnK1Jpt050Vyr:-L0op1MvnK1Jpt050Vys:b8rkmpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/010c3dce5d3d281c169c2357abb36c4e6c24ba6e/pkg/sql/distsqlrun/interleaved_reader_joiner_test.go#L145)):*
> ```Go
> 
> 	copyTables := func(tables []InterleavedReaderJoinerSpec_Table) []InterleavedReaderJoinerSpec_Table {
> 		temp := make([]InterleavedReaderJoinerSpec_Table, len(tables))
> ```

[nit] this can be just `append([]InterleavedReaderJoinerSpec_Table(nil), tables...)`

---

*[pkg/sql/distsqlrun/interleaved_reader_joiner_test.go, line 184 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20768#-L0opR0WTI8Y6pseEYjx:-L0opR0WTI8Y6pseEYjy:bhe523r) ([raw file](https://github.com/cockroachdb/cockroach/blob/010c3dce5d3d281c169c2357abb36c4e6c24ba6e/pkg/sql/distsqlrun/interleaved_reader_joiner_test.go#L184)):*
> ```Go
> 				spec.OnExpr = Expression{Expr: "@1 = @5"}
> 				return spec
> 			}(pdCd1Spec),
> ```

why are we passing this as an argument instead of using it directly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20768#-:-L0ophC-oOSqqzyYJDpq:bjj5s6a)*

**Comment by richardwu** [comment]
Yes, the cleanup is unrelated: I've separate it out into a separate commit.

I also rebased ontop of #20938.

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/interleaved_reader_joiner_test.go, line 126 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20768#-L0opE8y9Yg-VN9BOga_:-L0pgPazENeJZtt_WDPw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/010c3dce5d3d281c169c2357abb36c4e6c24ba6e/pkg/sql/distsqlrun/interleaved_reader_joiner_test.go#L126)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

These vars need some comments.
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/interleaved_reader_joiner_test.go, line 145 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20768#-L0op1MvnK1Jpt050Vyr:-L0pgNpFokEHA_2YNQES:b-dzg07c) ([raw file](https://github.com/cockroachdb/cockroach/blob/010c3dce5d3d281c169c2357abb36c4e6c24ba6e/pkg/sql/distsqlrun/interleaved_reader_joiner_test.go#L145)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] this can be just `append([]InterleavedReaderJoinerSpec_Table(nil), tables...)`
</blockquote></details>

Good point :+1: 

---

*[pkg/sql/distsqlrun/interleaved_reader_joiner_test.go, line 184 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20768#-L0opR0WTI8Y6pseEYjx:-L0pfkPTMx7PjET4igxu:b-cp904) ([raw file](https://github.com/cockroachdb/cockroach/blob/010c3dce5d3d281c169c2357abb36c4e6c24ba6e/pkg/sql/distsqlrun/interleaved_reader_joiner_test.go#L184)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

why are we passing this as an argument instead of using it directly?
</blockquote></details>

I needed to swap the tables for the specific test case and I don't believe you can do that in-place. I was considering doing swaps down in the test code, but some of the `OnExpr`s have a non-trivial dependency on the positions of table.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20768#-:-L0pgSFU1z-wy8HZ-nXu:beod5lh)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/distsqlrun/interleaved_reader_joiner_test.go, line 184 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20768#-L0opR0WTI8Y6pseEYjx:-L0pl-oo4HdHHHGIbTj9:b1p9mef) ([raw file](https://github.com/cockroachdb/cockroach/blob/010c3dce5d3d281c169c2357abb36c4e6c24ba6e/pkg/sql/distsqlrun/interleaved_reader_joiner_test.go#L184)):*
<details><summary><i>Previously, richardwu (Richard Wu) wrote…</i></summary><blockquote>

I needed to swap the tables for the specific test case and I don't believe you can do that in-place. I was considering doing swaps down in the test code, but some of the `OnExpr`s have a non-trivial dependency on the positions of table.
</blockquote></details>

I understand why we're copying Tables, I don't understand why `pdCd1Spec` is passed as an argument. Unless we're modifying `pdCd1Spec` somewhere, this should be equivalent to `func() { spec := pdCd1Spec ... }`

Instead of `copyTables` we could have something`spec := copy(pdCd1Spec)` which returns a new spec with the same contents.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20768)*

**Comment by richardwu** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/distsqlrun/interleaved_reader_joiner_test.go, line 184 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20768#-L0opR0WTI8Y6pseEYjx:-L0puX4hXgM7lJVP6d0v:b-dzrgsf) ([raw file](https://github.com/cockroachdb/cockroach/blob/010c3dce5d3d281c169c2357abb36c4e6c24ba6e/pkg/sql/distsqlrun/interleaved_reader_joiner_test.go#L184)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I understand why we're copying Tables, I don't understand why `pdCd1Spec` is passed as an argument. Unless we're modifying `pdCd1Spec` somewhere, this should be equivalent to `func() { spec := pdCd1Spec ... }`

Instead of `copyTables` we could have something`spec := copy(pdCd1Spec)` which returns a new spec with the same contents.
</blockquote></details>

Ahh right, closures.  Gotcha, updated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20768)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/distsqlrun/interleaved_reader_joiner_test.go, line 184 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20768#-L0opR0WTI8Y6pseEYjx:-L0pxBDKTzSe_g0MOsbm:b3ca9fn) ([raw file](https://github.com/cockroachdb/cockroach/blob/010c3dce5d3d281c169c2357abb36c4e6c24ba6e/pkg/sql/distsqlrun/interleaved_reader_joiner_test.go#L184)):*
<details><summary><i>Previously, richardwu (Richard Wu) wrote…</i></summary><blockquote>

Ahh right, closures.  Gotcha, updated.
</blockquote></details>

Thanks, looks good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20768)*

**Pull request merged**
