### PR TITLE
storage: Drastically speed up TestGossipHandlesReplacedNode

### PR DESCRIPTION
**Pull request by a-robinson**
It used to take > 12 seconds on laptops, now it's a few hundred
milliseconds.

The downside of this is that not using the node that holds most of the
leases isn't as good of a test. When I initially wrote this test,
it would pass if I used the 2nd/3rd nodes, but not if I used the first,
so there's a meaningful difference in coverage to doing this. It'd be
nice to be able to switch back once we actively drain leases.

@tamird - it may be worthwhile for me to dig in further and see if I can shorten the duration of the things that are taking a long time, both from an educational perspective and a better test coverage perspective. I may be able to time things out faster than in a real cluster given that it's just a test. Do you think it'd be worth it for me to spend more time on that?

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/11780)

### CODE REVIEW

**Comment by tamird** [comment]
Yeah, I would encourage you to dig into that. Based on past experience, you might end up uncovering something unexpected and broadly useful.

:lgtm: anyway.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/storage/gossip_test.go, line 145 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11780#-KY-FsW-B1maCqL1sUul:-KY-FsW-B1maCqL1sUum:bc8mdt7) ([raw file](https://github.com/cockroachdb/cockroach/blob/356595f7d635620cbfa22f84bc75a5c12b911c3d/pkg/storage/gossip_test.go#L145)):*
> ```Go
> 	defer tc.Stopper().Stop()
> 
> 	// Take down the a node other than first node and replace it with a new one.
> ```

"the a" double artcile
"than first node" missing article

---

*[pkg/storage/gossip_test.go, line 146 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11780#-KY-FzfKK6zfz4mnB6kf:-KY-FzfKK6zfz4mnB6kg:boisfi0) ([raw file](https://github.com/cockroachdb/cockroach/blob/356595f7d635620cbfa22f84bc75a5c12b911c3d/pkg/storage/gossip_test.go#L146)):*
> ```Go
> 
> 	// Take down the a node other than first node and replace it with a new one.
> 	// Replacing the first node would be better from an adversarial testing,
> ```

spurious comma

---

*[pkg/storage/gossip_test.go, line 164 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11780#-KY-G7NQgstdSTi3Wao-:-KY-G7NQgstdSTi3Wao0:b-o6wo7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/356595f7d635620cbfa22f84bc75a5c12b911c3d/pkg/storage/gossip_test.go#L164)):*
> ```Go
> 	// original nodes don't refresh their connection to the address of the first
> 	// node, they can get stuck here.
> 	for _, i := range []int{0, 2, 3} {
> ```

```
for i, server := range tc.Servers {
  if i == oldNodeIdx {
    continue
  }
  kvClient := server.KVClient()....
...
}
```
Would be more self-documenting (and won't require a change when you eventually switch this back to the first node).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11780#-:-KY-FgWQGjcJZZvTxcpp:b-wr7ise)*

**Comment by a-robinson** [comment]
Will do, I agree that it may unearth something useful and at the very lease I'll learn something. Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/storage/gossip_test.go, line 145 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11780#-KY-FsW-B1maCqL1sUul:-KY-Kn-exRWRn4aMIx4E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/356595f7d635620cbfa22f84bc75a5c12b911c3d/pkg/storage/gossip_test.go#L145)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

"the a" double artcile
"than first node" missing article
</blockquote></details>

Done.

---

*[pkg/storage/gossip_test.go, line 146 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11780#-KY-FzfKK6zfz4mnB6kf:-KY-KowfM7HnSpYOAvxJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/356595f7d635620cbfa22f84bc75a5c12b911c3d/pkg/storage/gossip_test.go#L146)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

spurious comma
</blockquote></details>

Done.

---

*[pkg/storage/gossip_test.go, line 164 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11780#-KY-G7NQgstdSTi3Wao-:-KY-Kpiu49IHAxNVF_ji:b-48vilg) ([raw file](https://github.com/cockroachdb/cockroach/blob/356595f7d635620cbfa22f84bc75a5c12b911c3d/pkg/storage/gossip_test.go#L164)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

```
for i, server := range tc.Servers {
  if i == oldNodeIdx {
    continue
  }
  kvClient := server.KVClient()....
...
}
```
Would be more self-documenting (and won't require a change when you eventually switch this back to the first node).
</blockquote></details>

Good call, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11780#-:-KY-L2A77q8uAORz0rZz:b-wlc5xa)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11780)*

**Comment by a-robinson** [comment]
Merging now to speed things up, but I'll investigate further soon.

**Pull request merged**
