### PR TITLE
opt: enable semi/anti join for GenerateLookupJoinsWithFilter

### PR DESCRIPTION
**Pull request by RaduBerinde**
First commit is form a separate PR.

#### opt: enable semi/anti join for GenerateLookupJoinsWithFilter

I noticed that this rule doesn't support semi/anti join; there's no reason why
it wouldn't work.

The plan change for TPCH Q04 is a clear improvement (~18s to 2.7s).

Release notes (performance improvement): Better execution plans in some cases
involving EXISTS.

### CODE REVIEW

**Review by andy-kimball — APPROVED** [review]
:lgtm:, very nice improvement. Are you planning to backport the bug fix part of this?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50846#-:-MB6WfwWE3cTpVG2q2qQ:byfmy74)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

**Review by rytaft — APPROVED** [review]
:lgtm: nice improvement!

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50846#-:-MB6XWrW4MfHuILjdaEw:b-j5h9d)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by RaduBerinde** [comment]
Yeah, I made the bug fix a separate PR that will be backported.

**Pull request merged**
