### PR TITLE
rac2: add token tracker

### LINKED ISSUE #128026: kvflowcontrol: implement token tracker v2
The existing token tracker in replication AC v1 has slightly different types and methods than what is required for v2:

**v1**

```go
type TokenTracker interface {
	Track(
		ctx context.Context,
		pri admissionpb.WorkPriority,
		tokens kvflowcontrol.Tokens,
		pos kvflowcontrolpb.RaftLogPosition,
	) bool
	Untrack(
		ctx context.Context, pri admissionpb.WorkPriority, upto kvflowcontrolpb.RaftLogPosition,
	) kvflowcontrol.Tokens
	Iter(_ context.Context, f func(admissionpb.WorkPriority, kvflowcontrol.Tokens))
	LowerBound() kvflowcontrolpb.RaftLogPosition
}
```

**v2**

```go
type TokenTracker interface {
	Track(
		ctx context.Context,
		index uint64,
		inheritedPri kvflowcontrolpb.RaftPriority,
		originalPri kvflowcontrolpb.RaftPriority,
		tokens kvflowcontrol.Tokens,
	) bool
	Untrack(
		inheritedPri kvflowcontrolpb.RaftPriority,
		uptoIndex uint64,
		f func(index uint64, originalPri kvflowcontrolpb.RaftPriority, tokens kvflowcontrol.Tokens),
	)
	UntrackGE(
		index uint64,
		f func(index uint64, inheritedPri kvflowcontrolpb.RaftPriority, originalPri kvflowcontrolpb.RaftPriority, tokens kvflowcontrol.Tokens),
	)
	UntrackAll(
		f func(index uint64, inheritedPri kvflowcontrolpb.RaftPriority, originalPri kvflowcontrolpb.RaftPriority, tokens kvflowcontrol.Tokens),
) 
```

The token tracker should support these methods. See the [prototype code](https://github.com/sumeerbhola/cockroach/blob/2064b279e95bbd68b0a7898503168d384cd0158c/pkg/kv/kvserver/kvflowcontrol/kvflowconnectedstream/token_tracker.go#L26) for more information.

Jira issue: CRDB-40749

Epic CRDB-37515

### PR DESCRIPTION
**Pull request by kvoli**
This commit introduces the token `Tracker`, which will be used to track
token deductions for in-flight entries at a given `RaftPriority`.

Resolves: https://github.com/cockroachdb/cockroach/issues/128026
Release note: None

### CODE REVIEW

**Comment by kvoli** [comment]
This is good for a look, almost entirely taken from the prototype. I may be incorrect but it didn't appear as though the tracker required any changes now that we only really inherit a low priority, instead of a potentially multiple higher priorities. I assume we could still inherit a higher priority if we need to force send entries and those entries were slated as low priority previously.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
- Priority override only goes from <original-pri> => LowPri in the latest design
- Also, the priority override, if any, is applied at the time when the decision is made to queue the entry or not. So the effective priority is used for deducting eval tokens, and that same priority is used for deducting the send tokens. So the tracker only need to track this effective priority for the entry, and not two priorities (in the prototype, since priority inheritance elevated the priority, and this could happen later, the eval token deduction priority and send token deduction priority could be different).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129413#-:-O4uaT673KdeSKCL3bqP:b-rkst4d)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go` line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129413#-O4uc6TBC5BQ-Tc6O9Dr:-O4uc6TBC5BQ-Tc6O9Ds:bk5dgsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f60d70c086f09968c9ad032620f729004bd12b0d/pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go#L35)):*
> ```Go
> type tracked struct {
> 	tokens                    kvflowcontrol.Tokens
> 	originalPri, inheritedPri raftpb.Priority
> ```

odd that we had the inheritedPri duplicated here even though it was already implicit in the `tracked` slide index.
Anyway, now that we have a single priority, we can drop both fields.

I think this starts looking exactly like `kvflowtokentracker.tracked` in that we need
```
type tracked struct {
	tokens   kvflowcontrol.Tokens
	position kvflowcontrolpb.RaftLogPosition
}
```
I am not suggesting we try to reuse it -- we should continue to copy and simplify to what we need.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go` line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129413#-O4uf8ZP860Zy6cfL6zC:-O4uf8ZP860Zy6cfL6zD:b-wjng38) ([raw file](https://github.com/cockroachdb/cockroach/blob/f60d70c086f09968c9ad032620f729004bd12b0d/pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go#L82)):*
> ```Go
> 	inheritedPri raftpb.Priority,
> 	uptoIndex uint64,
> 	f func(index uint64, originalPri raftpb.Priority, tokens kvflowcontrol.Tokens),
> ```

Let's simplify these untrack interfaces. I am not a fan of callback based interfaces when the are not essential given how they spread out the code (and I doubt they can inline). And the `Untrack` is always happening with an admitted vector in the prototype, so how about

```
Untrack(leaderTerm uint64, admitted [raftpb.NumPriorities]) [NumWorkClasses]kvflowcontrol.Tokens
UntrackGE(index uint64) [NumWorkClasses]kvflowcontrol.Tokens
UntrackAll() [NumWorkClasses]kvflowcontrol.Tokens
```

**Review by kvoli — COMMENTED** [review]
TYFTR - pushed some changes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129413#-:-O4vqA-c3Ad_GVCq-sdf:bibnrpl)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go` line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129413#-O4uc6TBC5BQ-Tc6O9Dr:-O4vpcJ16ifP1Dt29ELL:bmgjndc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f60d70c086f09968c9ad032620f729004bd12b0d/pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go#L35)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

odd that we had the inheritedPri duplicated here even though it was already implicit in the `tracked` slide index.
Anyway, now that we have a single priority, we can drop both fields.

I think this starts looking exactly like `kvflowtokentracker.tracked` in that we need
```
type tracked struct {
	tokens   kvflowcontrol.Tokens
	position kvflowcontrolpb.RaftLogPosition
}
```
I am not suggesting we try to reuse it -- we should continue to copy and simplify to what we need.
</blockquote></details>

Updated to remove the priorities here.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go` line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129413#-O4uf8ZP860Zy6cfL6zC:-O4vpf8vEjk5KYmS4o_L:bn4a91y) ([raw file](https://github.com/cockroachdb/cockroach/blob/f60d70c086f09968c9ad032620f729004bd12b0d/pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go#L82)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Let's simplify these untrack interfaces. I am not a fan of callback based interfaces when the are not essential given how they spread out the code (and I doubt they can inline). And the `Untrack` is always happening with an admitted vector in the prototype, so how about

```
Untrack(leaderTerm uint64, admitted [raftpb.NumPriorities]) [NumWorkClasses]kvflowcontrol.Tokens
UntrackGE(index uint64) [NumWorkClasses]kvflowcontrol.Tokens
UntrackAll() [NumWorkClasses]kvflowcontrol.Tokens
```
</blockquote></details>

Update to these signatures. Question on the `leaderTerm` being included in `Untrack(...)`, is the intent for a higher leader term to wipe all tracked entries at a lower term? Why does `UntrackGE` not require the same term arg?

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129413)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go` line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129413#-O4uf8ZP860Zy6cfL6zC:-O4vqk_85hFVdDDTzCVY:b-ft4qaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f60d70c086f09968c9ad032620f729004bd12b0d/pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go#L82)):*
For reference, the leader term argument will be used to:

> [...] since the token tracker on the leader can return tokens for entries that have a an index <= admitted and entry.term <= leader-term.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
Is this ready for another look?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129413#-:-O4w3eLg2ajoMavBLmkc:bqppz9a)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go` line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129413#-O4uf8ZP860Zy6cfL6zC:-O4w30jZER65Hfo8ERoe:b-1y4z5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f60d70c086f09968c9ad032620f729004bd12b0d/pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go#L82)):*
> Question on the `leaderTerm` being included in `Untrack(...)`, is the intent for a higher leader term to wipe all tracked entries at a lower term?

Correct

>  Why does `UntrackGE` not require the same term arg?

We use `UntrackGE` for a short-lived or unnoticed probe state and when we see that we need to add back to the send-queue some entries that we had already sent (and return their send tokens). I looked at the prototype this morning to remind myself why we needed this.

**Comment by kvoli** [comment]
Not yet ready for another look @sumeerbhola. I will ping on slack when it is, likely tomorrow morning.

**Comment by kvoli** [comment]
Should be good now @sumeerbhola

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129413)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go` line 22 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129413#-O5FE2FT7ad69FUbVuZr:-O5FE2FT7ad69FUbVuZs:b-kg0gju) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ec8abfd47e290b7453d770179dcfe0f5597779/pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go#L22)):*
> ```Go
> 
> // Tracker tracks flow token deductions for a replicaSendStream. Tokens are
> // deducted for an in-flight log entry (identified by raft index position),
> ```

nit: identified by raft index and term ...
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go` line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129413#-O5FEXnf5BelMJ9_8LFL:-O5FEXnf5BelMJ9_8LFM:b-q197np) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ec8abfd47e290b7453d770179dcfe0f5597779/pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go#L25)):*
> ```Go
> // with a given RaftPriority.
> type Tracker struct {
> 	tracked [raftpb.NumPriorities][]tracked
> ```

Are these in increasing order of the (term, index) tuple?
If yes, can you add a code comment.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go` line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129413#-O5FE9etCS-4rTzYBDYb:-O5FE9etCS-4rTzYBDYc:bo96a7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ec8abfd47e290b7453d770179dcfe0f5597779/pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go#L31)):*
> ```Go
> 
> // tracked represents tracked flow tokens; they're tracked with respect to a
> // raft log position (typically where the proposed command is expected to end
> ```

nit: this "typically where the ..." is no longer accurate. In RACv1 we were adding to the tracker at proposal time, hence this comment. Now are are adding to it on `MsgStorageAppend` so it *is* where it ended up. Could just drop this part of the comment.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go` line 53 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129413#-O5FEnPU76atUn94rEat:-O5FEnPU76atUn94rEau:b-2k0uen) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ec8abfd47e290b7453d770179dcfe0f5597779/pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go#L53)):*
> ```Go
> 	if len(t.tracked[pri]) >= 1 {
> 		last := t.tracked[pri][len(t.tracked[pri])-1]
> 		if last.index >= index {
> ```

We are not tolerating the index regressing when the term advances. I think this is correct, but worth a comment. Something like
// Tracker exists in the context of a single replicaSendStream, which cannot span the leader losing leadership and regaining it. So the indices must advance.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go` line 82 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129413#-O5FFHwG5FbW2TJz8ZMw:-O5FFHwG5FbW2TJz8ZMx:b-7jb3y8) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ec8abfd47e290b7453d770179dcfe0f5597779/pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go#L82)):*
> ```Go
> 	if t == nil {
> 		return returned
> 	}
> ```

Is this nil case relevant? I think it was in RACv1, but now this will only be called by a non-nil `replicaSendStream` which ought to have a non-nil Tracker.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go` line 87 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129413#-O5FGH8f3mw_eKROZSX0:-O5FGH8f3mw_eKROZSX1:bgap6lz) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ec8abfd47e290b7453d770179dcfe0f5597779/pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go#L87)):*
> ```Go
> 		uptoIndex := admitted[pri]
> 		var untracked int
> 		for {
> ```

nit: it seems simpler to write the following loop

```
for n := len(t.tracked[pri]); untracked < n; untracked++ {
  tracked := t.tracked[pri][untracked]
  if tracked.term > term || (tracked.term == term && tracked.index > uptoIndex) {
    break
  }
  returned[pri] += tracked.tokens
}
```

**Review by kvoli — COMMENTED** [review]
TYFTR

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129413#-:-O5FUoZdAOBGGWrfWdcz:b-80sls6)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go` line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129413#-O4uf8ZP860Zy6cfL6zC:-O5FUlV886fCDLh20s73:b-udvak3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f60d70c086f09968c9ad032620f729004bd12b0d/pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go#L82)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> Question on the `leaderTerm` being included in `Untrack(...)`, is the intent for a higher leader term to wipe all tracked entries at a lower term?

Correct

>  Why does `UntrackGE` not require the same term arg?

We use `UntrackGE` for a short-lived or unnoticed probe state and when we see that we need to add back to the send-queue some entries that we had already sent (and return their send tokens). I looked at the prototype this morning to remind myself why we needed this.
</blockquote></details>

Updated with these comments earlier.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go` line 22 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129413#-O5FE2FT7ad69FUbVuZr:-O5FTHFT9DM331_EhR2y:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ec8abfd47e290b7453d770179dcfe0f5597779/pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go#L22)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: identified by raft index and term ...
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go` line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129413#-O5FEXnf5BelMJ9_8LFL:-O5FTRxe1A23qiZM3O44:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ec8abfd47e290b7453d770179dcfe0f5597779/pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go#L25)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Are these in increasing order of the (term, index) tuple?
If yes, can you add a code comment.
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go` line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129413#-O5FE9etCS-4rTzYBDYb:-O5FTYv65rMYq9qd38gp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ec8abfd47e290b7453d770179dcfe0f5597779/pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go#L31)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: this "typically where the ..." is no longer accurate. In RACv1 we were adding to the tracker at proposal time, hence this comment. Now are are adding to it on `MsgStorageAppend` so it *is* where it ended up. Could just drop this part of the comment.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go` line 53 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129413#-O5FEnPU76atUn94rEat:-O5FTjAz9kxUEllrhJkV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ec8abfd47e290b7453d770179dcfe0f5597779/pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go#L53)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We are not tolerating the index regressing when the term advances. I think this is correct, but worth a comment. Something like
// Tracker exists in the context of a single replicaSendStream, which cannot span the leader losing leadership and regaining it. So the indices must advance.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go` line 82 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129413#-O5FFHwG5FbW2TJz8ZMw:-O5FUH7d-O23MX5BBPCH:bft3tge) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ec8abfd47e290b7453d770179dcfe0f5597779/pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go#L82)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is this nil case relevant? I think it was in RACv1, but now this will only be called by a non-nil `replicaSendStream` which ought to have a non-nil Tracker.
</blockquote></details>

No longer relevant, I've updated the init method to create a new tracker instead as well.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go` line 87 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129413#-O5FGH8f3mw_eKROZSX0:-O5FURT6DeHP3MWq-aFo:b-3taaev) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ec8abfd47e290b7453d770179dcfe0f5597779/pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go#L87)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: it seems simpler to write the following loop

```
for n := len(t.tracked[pri]); untracked < n; untracked++ {
  tracked := t.tracked[pri][untracked]
  if tracked.term > term || (tracked.term == term && tracked.index > uptoIndex) {
    break
  }
  returned[pri] += tracked.tokens
}
```
</blockquote></details>

Nice, updated.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129413#-:-O5FfB3-EKq5Zpz7StOJ:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go` line 39 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/129413#-O5FemESD4eKdUVEfrMZ:-O5FemETB24uQddob8Ht:b-6hwrd0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c69cf0f0d492eca56b8683d0248ab375bd0f785/pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go#L39)):*
> ```Go
> }
> 
> func NewTracker(stream kvflowcontrol.Stream) *Tracker {
> ```

Tracker was a member of `replicaSendStream` in the prototype, so Init seems perfectly acceptable instead of allocating.

**Review by kvoli — COMMENTED** [review]
TYFTR!

I moved back to an `Init` method and renamed the inner-loop variable `tracked` to `deduction` to appease the linter, as it shadowed the struct naming.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129413#-:-O5FinKI4LGC3iQ30dUd:b8ius9r)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @pav-kv and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go` line 39 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/129413#-O5FemESD4eKdUVEfrMZ:-O5FixXy1YlbcNOlwn-a:b4kf8jj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c69cf0f0d492eca56b8683d0248ab375bd0f785/pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go#L39)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Tracker was a member of `replicaSendStream` in the prototype, so Init seems perfectly acceptable instead of allocating.
</blockquote></details>

Switched back.

**Comment by kvoli** [comment]
bors r=sumeerbhola

**Pull request merged**
