### PR TITLE
pgwire: remove bogus empty commandComplete

### PR DESCRIPTION
**Pull request by andreimatei**
This patch removes the sending of a funky commandComplete message with
an empty command tag. The current code doesn't make much sense - it send
the message if results have been produced by the last transaction.
Before the recent move to results streaming, the code was sending this
message if, after executing a _batch_, it didn't get any results. I
can't see how that case would ever happen (and checked that it didn't
happen in our tests), because we have special handling of query strings
that don't result in any statements.
Also, the protocol doesn't say anything about such a message with an
empty tag.

### CODE REVIEW

**Comment by jordanlewis** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18104#-:-Ksu1Ul3BvCXGtygAlpd:bnfp4nl)*

**Comment by andreimatei** [comment]
Added a prequel commit. PTAL
cc @knz

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18104#-:-KsuCrutdD1L-H5jfTn8:bh9dpqz)*

**Comment by jordanlewis** [comment]
So you found some cases where the original commit's code would fire? In that case, it should be easy to write tests that fail without the "prequel commit" - Let's get those in!

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18104#-:-KsuDNZqIiSW4nVlkS7-:b-tr5628)*

**Comment by andreimatei** [comment]
I'm not sure I follow. Without the first commit, but with the 2nd commit, we have plenty of tests that fail - because the statements fixed in the 1st commit wouldn't send any results to the client.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18104#-:-KsuEfAZTTSOoRtfZj5b:b5tqjb2)*

**Comment by jordanlewis** [comment]
Oh, in that case, all's well - I only commented because you had said that you ran all the tests without encountering the codepath you removed. Presumably the tests did in fact hit that codepath, then?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18104#-:-KsuFeMrUr3tdwujfogu:b-f27i5j)*

**Comment by andreimatei** [comment]
Before result streaming, the funky commandComplete was not hit. After result streaming, it was inadvertently hit.
With enough error tolerance, all the tests pass :)

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18104#-:-KsuG5lK7uI1hqWG4OTL:bj82zez)*

**Comment by jordanlewis** [comment]
Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18104)*

**Pull request merged**
