### PR TITLE
Dynamic port binding for PGAddr in test context

### PR DESCRIPTION
**Pull request by madelynnblue**
Happening because PG now binds to 15432.

See https://circleci.com/gh/cockroachdb/cockroach/10758

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3679)

### CODE REVIEW

**Comment by tamird** [comment]
add this commit to your other PR; neither PR can build green at the moment.

**Comment by mjibson** [comment]
Added both commits to this PR.

**Comment by tamird** [comment]
LGTM

**Comment by mjibson** [comment]
Merged with Ben

**Pull request merged**
