### PR TITLE
distsql: return all trailing metadata from sorter

### LINKED ISSUE #23121: distsql: sorter is not forwarding all metadata
details to follow.

### PR DESCRIPTION
**Pull request by rjnn**
Not yet ready for review.

Fixes #23121.

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/sorter.go, line 211 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23132#-L6JhBooSBA1OPQHWPtR:-L6JhBooSBA1OPQHWPtS:b-a5spr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd123f39eac8dcc5e054754451609944734d331e/pkg/sql/distsqlrun/sorter.go#L211)):*
> ```Go
> 		return nil, meta
> 	}
> 	s.close()
> ```

It is confusing to me that `Next()` sometimes calls `producerMeta` and sometimes calls `trailingMeta`. I can't convince myself this is correct. I think you should fold this functionality into `producerMeta`. See `tableReader.producerMeta` for an example of how. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23132)*

**Comment by petermattis** [comment]
Was this causing a serious issue, or something you noticed in passing?

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23132#-:-L6Jhq9989m2j8tsdafJ:b-l3alzx)*

**Comment by arjunravinarayan** [comment]
This was one of many causes of an issue relating to misplanning of TableReaders for some queries with lots of spans (>10). This issue was causing `misplannedMetadata` to not be correctly propagated (as they were being swallowed), so that subsequent queries would be correctly planned. Another issue w.r.t. the misplanning that was uncovered was #23129.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/sorter.go, line 211 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23132#-L6JhBooSBA1OPQHWPtR:-L6Jj7-OBoLYXQ3vzptE:bhy9ot6) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd123f39eac8dcc5e054754451609944734d331e/pkg/sql/distsqlrun/sorter.go#L211)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

It is confusing to me that `Next()` sometimes calls `producerMeta` and sometimes calls `trailingMeta`. I can't convince myself this is correct. I think you should fold this functionality into `producerMeta`. See `tableReader.producerMeta` for an example of how. 
</blockquote></details>

Will do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23132#-:-L6JiyOfkTVgJakL9Fem:b8gb621)*

**Comment by andreimatei** [comment]
Not swallowing metadata has becoming critical since we've started putting
the read spans in the metadata - the ones used to check whether a txn's ts
can be pushed without a retry.

**Comment by arjunravinarayan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/distsqlrun/sorter.go, line 211 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23132#-L6JhBooSBA1OPQHWPtR:-L6KERGj74XmA2W_L96i:b-7emei9) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd123f39eac8dcc5e054754451609944734d331e/pkg/sql/distsqlrun/sorter.go#L211)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Will do.
</blockquote></details>

Done. Not sure the logic on `sortChunksProcessor` is correct. Might need some other "draining" flag in the processor that gets set once we start emitting `trailingMetadata` which gets checked on the call to `Next()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23132)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/sorter.go, line 350 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23132#-L6MmiiBKMTIC3u2MJJD:-L6MmiiBKMTIC3u2MJJE:b-xdc98b) ([raw file](https://github.com/cockroachdb/cockroach/blob/285d9a615c13b3b96faf509f4a85bfad0be4d275/pkg/sql/distsqlrun/sorter.go#L350)):*
> ```Go
> 			s.meta = s.meta[1:]
> 			return meta
> 		}
> ```

I think you need to follow the logic of `tableReader.producerMeta`:

```
	if !tr.closed {
	...
	}
	if len(tr.trailingMetadata) > 0 {
		meta := &tr.trailingMetadata[0]
		tr.trailingMetadata = tr.trailingMetadata[1:]
		return meta
	}
	return nil
```

That is, `producerMeta` needs to return the trailing metadata even if `s.closed` is true. Is there a reason you're attempting different logic here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23132)*

**Comment by arjunravinarayan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/distsqlrun/sorter.go, line 350 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23132#-L6MmiiBKMTIC3u2MJJD:-L6N0101gkn4KG7aB2KM:bn26he4) ([raw file](https://github.com/cockroachdb/cockroach/blob/285d9a615c13b3b96faf509f4a85bfad0be4d275/pkg/sql/distsqlrun/sorter.go#L350)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think you need to follow the logic of `tableReader.producerMeta`:

```
	if !tr.closed {
	...
	}
	if len(tr.trailingMetadata) > 0 {
		meta := &tr.trailingMetadata[0]
		tr.trailingMetadata = tr.trailingMetadata[1:]
		return meta
	}
	return nil
```

That is, `producerMeta` needs to return the trailing metadata even if `s.closed` is true. Is there a reason you're attempting different logic here?
</blockquote></details>

Done. No, there was no reason.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23132)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23132#-:-L6N4uvAK4CQL01nq0KX:bnfp4nl)*

**Pull request merged**
