### PR TITLE
kvstreamer: add support for InOrder mode

### PR DESCRIPTION
**Pull request by yuzefovich**
**rowcontainer: break dependency on execinfra in tests**

This is done in order to prevent an import cycle in tests when
`kvstreamer` becomes dependent on `rowcontainer` in the following
commit.

Release note: None

Release justification: test only change.

**kvstreamer: extract some abstractions for requests and results**

This commit extracts a couple of interfaces (`requestProvider` and
`resultsBuffer`) for the logic of handling the requests that need to be
served and results already received, respectively. At the moment, only
a single implementation of both interfaces exist, but the following
commit will introduce the support for `InOrder` mode with new
implementations.

Both abstractions are concurrency-safe, so this refactor allowed us to
clean up the code a bit.

The only notable change worth calling out is that a condition variable
in the `resultsBuffer` has been replaced with a buffered channel. This
was done to make the implementation of the `InOrder` mode simpler (in `get`
method there we need to be able to consume some budget while already
holding the `resultsBuffer`'s lock; at the same time we want to unlock
both mutexes when `Wait`ing on the variable).

Release note: None

Release justification: bug fixes and low-risk updates to new functionality.

**kvstreamer: add support for InOrder mode**

This commit adds the support for `InOrder` mode to the `Streamer`. It is
done by implementing `requestsProvider` and `resultsBuffer` in such
a manner so that requests and results, respectively, with higher
priority are executed first. This is achieved by maintaining heaps in
both implementations.

An additional complication is that `inOrderResultsBuffer` needs to be
able to spill to disk if it has received some Results that are needed
later in order to free up the budget for the head-of-the-line requests.
Such a scenario could occur whenever we had a poor estimate for the
head-of-the-line request (i.e. we issued it with too low value of
`TargetBytes`, yet it had `headOfLine=true`, so it put the budget into
debt) whereas we had good estimates for the later requests (i.e. the
responses fit into the `TargetBytes` allowance). In order to stay within
the limit, we need to spill those later results to disk to free up the
budget.

The spilling to disk is supported by using the disk-backed row
container. Currently the implementation has a known deficiency due to
the interface of the row container - the rows cannot be deleted - so
whenever a Result is pulled up from disk (and becomes no longer needed),
it still stays on disk, and we have to skip over it every time. However,
I imagine that the scenario when the spilling to disk is needed is
somewhat of an edge case, so it's ok to accept this deficiency, at least
for now.

It's worth noting that `inOrderResultsBuffer` currently doesn't work for
cases when there are multiple `Result`s for a single `ScanRequest`
spanning multiple ranges. It is ok for index joins because we never
break a single row across multiple ranges, and we'll need to fix it when
the lookup joins are supported.

Addresses: #54680.

Release note: None

Release justification: bug fixes and low-risk updates to new functionality.

**kvstreamer: move the package from kv/kvclient into sql**

Seems like `pkg/sql` is a better place for the `kvstreamer` package
since SQL Queries is the owner of it, it now has a dependency on
`sql/rowcontainer`, and is mainly used by `sql/row`.

Release note: None

Release justification: bug fixes and low-risk updates to new functionality.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76864)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373 and @rytaft)

___
*[pkg/sql/kvstreamer/requests_provider.go, line 44 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/76864#-Mwo9y2n1yIEkll1i4I8:-Mwo9y2n1yIEkll1i4I9:b-hx13bw) ([raw file](https://github.com/cockroachdb/cockroach/blob/07ff36494cf960bd3676acff322e80c52673a1be/pkg/sql/kvstreamer/requests_provider.go#L44)):*
> ```Go
> 	// necessary but might not be sufficient for the response to be non-empty.
> 	minTargetBytes int64
> 	// priority is the smallest number in positions. It is the priority of this
> ```

I find this terminology a bit confusing but couldn't come up with something better, so I'm curious in suggestions.

`singleRangeBatch` has the highest priority or urgency whenever it contains a request with the smallest position.

**Comment by yuzefovich** [comment]
Friendly ping @rharding6373 @rytaft

**Review by rharding6373 — CHANGES_REQUESTED** [review]
Excited to see InOrder mode!

> Reviewed 3 of 3 files at r1, 7 of 7 files at r5, 2 of 13 files at r6, 23 of 23 files at r8, 6 of 7 files at r9, 12 of 13 files at r10, 17 of 20 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76864#-:-MxHSz0aE9tYdiNRIAnd:b19y1ds)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373, @rytaft, and @yuzefovich)

___
*[pkg/kv/kvclient/kvstreamer/requests_provider.go, line 144 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76864#-Mx5TMxZ3AJihLKLy08T:-Mx5TMxZ3AJihLKLy08U:bgnmnuk) ([raw file](https://github.com/cockroachdb/cockroach/blob/74b00bcb51c656f8798ab3fd263c2bfd3f43f643/pkg/kv/kvclient/kvstreamer/requests_provider.go#L144)):*
> ```Go
> }
> 
> func (b *requestsProviderBase) waitLocked() {
> ```

Here and in `emptyLocked` and `removeFirstLocked`, could we add an assert to check that the lock is held?
___
*[pkg/kv/kvclient/kvstreamer/requests_provider.go, line 175 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76864#-Mx5TUP46lAJR5O5JtSH:-Mx5TUP46lAJR5O5JtSI:b-x9r8lg) ([raw file](https://github.com/cockroachdb/cockroach/blob/74b00bcb51c656f8798ab3fd263c2bfd3f43f643/pkg/kv/kvclient/kvstreamer/requests_provider.go#L175)):*
> ```Go
> 	p.Lock()
> 	defer p.Unlock()
> 	p.requests = requests
> ```

Why not append? It seems like the only difference between `enqueue` and `add` is whether there are one or many requests. [nit] This also makes me wonder whether they could have more similar names, like `addRequest` and `addRequests`.
___
*[pkg/kv/kvclient/kvstreamer/requests_provider.go, line 220 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/76864#-Mx76Ig40rnO7L0vn7P6:-Mx76Ig40rnO7L0vn7P7:b-48ah0h) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53c82716c2651a447802039096c3b8373300a19/pkg/kv/kvclient/kvstreamer/requests_provider.go#L220)):*
> ```Go
> }
> 
> func (p *inOrderRequestsProvider) Less(i, j int) bool {
> ```

nit: Do these need comments like "Less implements the sort interface"?
___
*[pkg/kv/kvclient/kvstreamer/requests_provider.go, line 257 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/76864#-Mx76kNH71y1MO32ZMfD:-Mx76kNH71y1MO32ZMfE:b-w88ybz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53c82716c2651a447802039096c3b8373300a19/pkg/kv/kvclient/kvstreamer/requests_provider.go#L257)):*
> ```Go
> 
> func (p *inOrderRequestsProvider) firstLocked() singleRangeBatch {
> 	if len(p.requests) == 0 {
> ```

Assert lock held here and in `removeFirstLocked`.
___
*[pkg/kv/kvclient/kvstreamer/results_buffer.go, line 87 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/76864#-Mx79Rg990qmZhc6lFYc:-Mx79Rg990qmZhc6lFYd:b97oz6s) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53c82716c2651a447802039096c3b8373300a19/pkg/kv/kvclient/kvstreamer/results_buffer.go#L87)):*
> ```Go
> 	// spill returns true if the resultsBuffer is able to spill already buffered
> 	// results to disk so that atLeastBytes (or more) bytes are returned to the
> 	// budget. Only buffered results with higher values of priority (and less
> ```

nit: this comment could use more specificity to be less confusing. Is there a priority level at which we will never spill to disk? Or do we spill starting at highest priority and continue until we've released `atLeastBytes` bytes?
___
*[pkg/kv/kvclient/kvstreamer/results_buffer.go, line 91 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/76864#-Mx79K7IBgbfoIO7D7gY:-Mx79K7IBgbfoIO7D7gZ:buvmu4z) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53c82716c2651a447802039096c3b8373300a19/pkg/kv/kvclient/kvstreamer/results_buffer.go#L91)):*
> ```Go
> 	//
> 	// It is assumed that the budget's mutex is already being held.
> 	spill(_ context.Context, atLeastBytes int64, spillingPriority int) (bool, error)
> ```

Would it be useful to return the bytes actually returned to the budget?
___
*[pkg/kv/kvclient/kvstreamer/results_buffer.go, line 433 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/76864#-MxHQTV_6F5JYkV1isyp:-MxHQTV_6F5JYkV1isyq:b-w07sw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53c82716c2651a447802039096c3b8373300a19/pkg/kv/kvclient/kvstreamer/results_buffer.go#L433)):*
> ```Go
> }
> 
> func (b *inOrderResultsBuffer) stringLocked() string {
> ```

nit: add assertion for lock held
___
*[pkg/kv/kvclient/kvstreamer/results_buffer.go, line 526 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/76864#-Mx77QFRAGsijEeuECG5:-Mx77QFRAGsijEeuECG6:bxez0ko) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53c82716c2651a447802039096c3b8373300a19/pkg/kv/kvclient/kvstreamer/results_buffer.go#L526)):*
> ```Go
> 		}
> 	}
> 	return false, nil
> ```

If we reach here we have buffered results but were unable to spill them. Should we return an error in this case? Not sure what the caller should do if it's returned false and no error.
___
*[pkg/kv/kvclient/kvstreamer/streamer_test.go, line 447 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/76864#-MxHS8PEAxzwT6t5mSt4:-MxHS8PEAxzwT6t5mSt5:b-yftxds) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53c82716c2651a447802039096c3b8373300a19/pkg/kv/kvclient/kvstreamer/streamer_test.go#L447)):*
> ```Go
> }
> 
> // TODO(yuzefovich): once lookup joins are supported, add a test for InOrder
> ```

We could add some basic InOrder tests here though, right? Seems like InOrder mode is lacking coverage.

**Review by yuzefovich — COMMENTED** [review]
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76864#-:-MxpBmhNBvEMRvLW0d9i:b-9qdoz3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373 and @rytaft)

___
*[pkg/kv/kvclient/kvstreamer/requests_provider.go, line 144 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76864#-Mx5TMxZ3AJihLKLy08T:-Mxjj7so8P8tlBThEIu6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/74b00bcb51c656f8798ab3fd263c2bfd3f43f643/pkg/kv/kvclient/kvstreamer/requests_provider.go#L144)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Here and in `emptyLocked` and `removeFirstLocked`, could we add an assert to check that the lock is held?
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvstreamer/requests_provider.go, line 175 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76864#-Mx5TUP46lAJR5O5JtSH:-MxjlEPN3j_N21upQaYa:b-vqix5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/74b00bcb51c656f8798ab3fd263c2bfd3f43f643/pkg/kv/kvclient/kvstreamer/requests_provider.go#L175)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Why not append? It seems like the only difference between `enqueue` and `add` is whether there are one or many requests. [nit] This also makes me wonder whether they could have more similar names, like `addRequest` and `addRequests`.
</blockquote></details>

Since we currently don't support pipelining, `enqueue` is only called when all previous requests have been responded to, so here `p.requests` is always empty, and I think appending to it would be a bit confusing. I extended the comment in the interface and added an assertion.

Re: different names - in my mental model `enqueue` and `add` occur at different points in time, with different characteristics (which are more clear in the InOrder mode). Namely, `enqueue` is called once per "input chunk" coming from the user and `add` is called by the Streamer itself whenever a single request needs to be re-evaluated.
___
*[pkg/kv/kvclient/kvstreamer/requests_provider.go, line 220 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/76864#-Mx76Ig40rnO7L0vn7P6:-MxjkDX758pNN0sJPSJ4:b-2j9air) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53c82716c2651a447802039096c3b8373300a19/pkg/kv/kvclient/kvstreamer/requests_provider.go#L220)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

nit: Do these need comments like "Less implements the sort interface"?
</blockquote></details>

The linter doesn't complain, so no. I think for some code paths the linter is disabled, so we don't have to provide comments to the exported methods.
___
*[pkg/kv/kvclient/kvstreamer/requests_provider.go, line 257 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/76864#-Mx76kNH71y1MO32ZMfD:-MxjkN8O4N_XlJV6ujK4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53c82716c2651a447802039096c3b8373300a19/pkg/kv/kvclient/kvstreamer/requests_provider.go#L257)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Assert lock held here and in `removeFirstLocked`.
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvstreamer/results_buffer.go, line 87 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/76864#-Mx79Rg990qmZhc6lFYc:-MxjnHvu0KWiTsX16gL3:bt8r52f) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53c82716c2651a447802039096c3b8373300a19/pkg/kv/kvclient/kvstreamer/results_buffer.go#L87)):*
Added more words, please let me know if they make sense.

> Is there a priority level at which we will never spill to disk?

If `spillingPriority == math.MaxInt64`, then no result will be spilled.

> do we spill starting at highest priority and continue until we've released `atLeastBytes` bytes?

Roughly speaking yes. It's not exactly that we're iterating in strictly non-increasing order of priorities - we have a min heap, so in order to iterate it like a max heap, it'd be a bit expensive - we're iterating in reverse over the slice backing the min heap. Since for each `i` we have `heap[i] <= heap[2*i]` and `heap[i] <= heap[2*i+1]`, iterating over `i` in reverse is similar to iterating over larger values of `heap` first, but not in an exact fashion. This seems reasonable for our use case.

I consciously didn't add anything about the order in the comment on `resultsBuffer.spill` to leave it up to the implementation, but let me know if you think more words are needed in `inOrderResultsBuffer.spill` about it.
___
*[pkg/kv/kvclient/kvstreamer/results_buffer.go, line 91 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/76864#-Mx79K7IBgbfoIO7D7gY:-MxjpRDZ6eZP4wUxZY-m:b5foj4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53c82716c2651a447802039096c3b8373300a19/pkg/kv/kvclient/kvstreamer/results_buffer.go#L91)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Would it be useful to return the bytes actually returned to the budget?
</blockquote></details>

I don't think so - at least right now we only have a use case where it's a binary "do we now have enough budget for TargetBytes? yes/no" decision, so boolean seems natural.
___
*[pkg/kv/kvclient/kvstreamer/results_buffer.go, line 526 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/76864#-Mx77QFRAGsijEeuECG5:-Mxjpdhz4oknX_FqxOAJ:b-vwt60) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53c82716c2651a447802039096c3b8373300a19/pkg/kv/kvclient/kvstreamer/results_buffer.go#L526)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

If we reach here we have buffered results but were unable to spill them. Should we return an error in this case? Not sure what the caller should do if it's returned false and no error.
</blockquote></details>

That would indicate that the spilling wasn't successful in freeing up enough budget, but also that no unrecoverable error was encountered either, so we can proceed to waiting for some results to be released.
___
*[pkg/kv/kvclient/kvstreamer/streamer_test.go, line 447 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/76864#-MxHS8PEAxzwT6t5mSt4:-Mxp9jpx91yuiJncgac6:bg51pd3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53c82716c2651a447802039096c3b8373300a19/pkg/kv/kvclient/kvstreamer/streamer_test.go#L447)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

We could add some basic InOrder tests here though, right? Seems like InOrder mode is lacking coverage.
</blockquote></details>

Thanks for this callout.

I think there are a couple of dimensions on the testing front to this PR - we need to make sure that we don't deadlock and that the correct results are produced.

On the deadlock side - `TestLargeKeys` is extremely good in making sure that we don't deadlock because it randomizes a lot of stuff. It has been fundamental when I was writing the code. I have pretty high confidence in the test.

On the correctness side - I've just added unit tests for the InOrder requests provider and results buffer which are the new components introduced in this PR. I also plan to add another logic test config which randomizes `distsql_workmem` limit, and in combination with `fakedist` setup, it should provide decent test coverage.

**Comment by yuzefovich** [comment]
Finally fixed the test, RFAL.

**Review by rharding6373 — APPROVED** [review]
Nice work! :lgtm: 

> Reviewed 23 of 23 files at r12, 7 of 7 files at r13, 15 of 15 files at r14, 20 of 22 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76864#-:-MyE6Q1EDZe564ol9Hxj:bnahwna)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[pkg/kv/kvclient/kvstreamer/requests_provider.go, line 175 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76864#-Mx5TUP46lAJR5O5JtSH:-MxtsKGS3HeR_eyqRG4e:b-69k6nd) ([raw file](https://github.com/cockroachdb/cockroach/blob/74b00bcb51c656f8798ab3fd263c2bfd3f43f643/pkg/kv/kvclient/kvstreamer/requests_provider.go#L175)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Since we currently don't support pipelining, `enqueue` is only called when all previous requests have been responded to, so here `p.requests` is always empty, and I think appending to it would be a bit confusing. I extended the comment in the interface and added an assertion.

Re: different names - in my mental model `enqueue` and `add` occur at different points in time, with different characteristics (which are more clear in the InOrder mode). Namely, `enqueue` is called once per "input chunk" coming from the user and `add` is called by the Streamer itself whenever a single request needs to be re-evaluated.
</blockquote></details>

Ok. My sense is that there are some amount of assumptions derived from the specific usage of the implementation instead of letting this struct stand alone. However, I don't have very strong feelings on it at this point and it seems to work.
___
*[pkg/kv/kvclient/kvstreamer/results_buffer.go, line 87 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/76864#-Mx79Rg990qmZhc6lFYc:-MyE2_VjCQZXKqBy96H-:b-nofc4h) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53c82716c2651a447802039096c3b8373300a19/pkg/kv/kvclient/kvstreamer/results_buffer.go#L87)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Added more words, please let me know if they make sense.

> Is there a priority level at which we will never spill to disk?

If `spillingPriority == math.MaxInt64`, then no result will be spilled.

> do we spill starting at highest priority and continue until we've released `atLeastBytes` bytes?

Roughly speaking yes. It's not exactly that we're iterating in strictly non-increasing order of priorities - we have a min heap, so in order to iterate it like a max heap, it'd be a bit expensive - we're iterating in reverse over the slice backing the min heap. Since for each `i` we have `heap[i] <= heap[2*i]` and `heap[i] <= heap[2*i+1]`, iterating over `i` in reverse is similar to iterating over larger values of `heap` first, but not in an exact fashion. This seems reasonable for our use case.

I consciously didn't add anything about the order in the comment on `resultsBuffer.spill` to leave it up to the implementation, but let me know if you think more words are needed in `inOrderResultsBuffer.spill` about it.
</blockquote></details>

This helps a lot. Thanks!
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 768 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/76864#-MyE3h9EAt6Oh6oHf5S7:-MyE3h9EAt6Oh6oHf5S8:b1xd87y) ([raw file](https://github.com/cockroachdb/cockroach/blob/30ed2518a65b213d947e3b16adf0a128d6a6279b/pkg/kv/kvclient/kvstreamer/streamer.go#L768)):*
> ```Go
> 		); err != nil {
> 			w.s.results.setError(err)
> 			shouldExit = true
> ```

minor nit: just `return true` for consistency
___
*[pkg/kv/kvclient/kvstreamer/streamer_test.go, line 447 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/76864#-MxHS8PEAxzwT6t5mSt4:-MyE-HrOAgBxYu_DE8dJ:brxp9sq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53c82716c2651a447802039096c3b8373300a19/pkg/kv/kvclient/kvstreamer/streamer_test.go#L447)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Thanks for this callout.

I think there are a couple of dimensions on the testing front to this PR - we need to make sure that we don't deadlock and that the correct results are produced.

On the deadlock side - `TestLargeKeys` is extremely good in making sure that we don't deadlock because it randomizes a lot of stuff. It has been fundamental when I was writing the code. I have pretty high confidence in the test.

On the correctness side - I've just added unit tests for the InOrder requests provider and results buffer which are the new components introduced in this PR. I also plan to add another logic test config which randomizes `distsql_workmem` limit, and in combination with `fakedist` setup, it should provide decent test coverage.
</blockquote></details>

Sounds good.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76864#-:-MyEIBS31HxjMLv-G5YE:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rharding6373 and @rytaft)

**Comment by yuzefovich** [comment]
@rytaft thoughts on backporting this to 22.1 branch? The streamer there is disabled by default, so this will only matter if a user explicitly enables the new functionality, so the backport seems safe. My arguments to make the backport is that it'll be simple to know what is supported by the streamer (i.e. simply "index joins are fully supported") as well as a possible ease of backporting fixes (the last commit in this PR moves the code around). However, it doesn't appear to satisfy the criteria for the backport.

**Comment by rytaft** [comment]
I think this makes sense. Can you create a backport request using the new process?

**Comment by yuzefovich** [comment]
Done.

**Comment by yuzefovich** [comment]
blathers backport 22.1

**Pull request merged**
