### PR TITLE
roachtest: add acceptance/bank/{cluster-recovery,node-restart}

### PR DESCRIPTION
**Pull request by petermattis**
Move the cluster-recovery and node-restart acceptance tests to
acceptance/bank/{cluster-recovery,node-restart} roachtests.

See #29151

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29449)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/bank.go, line 14 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29449#-LLGuG6H6LYEMPuDbqm8:-LLGuG6H6LYEMPuDbqm9:b-63ittz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1ce1137a791d143cda361efb62a477ae408027b/pkg/cmd/roachtest/bank.go#L14)):*
> ```Go
> // implied. See the License for the specific language governing
> // permissions and limitations under the License. See the AUTHORS file
> // for names of contributors.
> ```

I copied pasted this from another file. We should probably remove the `See the AUTHORS file` line everywhere because we don't have one.

**Review by petermattis — COMMENTED** [review]
I tried to keep the first commit minimal (though I failed slightly). 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29449#-:-LLGuV9O0abXAljjGH0j:b-fq1nkz)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by benesch — APPROVED** [review]
This is exciting cleanup!

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 3 of 3 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29449#-:-LLIBrXL-LWSlpBLiK8O:bcsztkt)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/acceptance.go, line 23 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/29449#-LLIBJ9g8MhmeELm4L_B:-LLIBJ9g8MhmeELm4L_C:b-tk49k1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d27dc1826fb4bdf4d9953612b65f330f982e4c49/pkg/cmd/roachtest/acceptance.go#L23)):*
> ```Go
> 	spec := testSpec{
> 		Name:  "acceptance",
> 		Nodes: nodes(4),
> ```

Ooh, nice catch.
___
*[pkg/cmd/roachtest/bank.go, line 14 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29449#-LLGuG6H6LYEMPuDbqm8:-LLIA_53-XYO9LT5iBtC:bgrki4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1ce1137a791d143cda361efb62a477ae408027b/pkg/cmd/roachtest/bank.go#L14)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I copied pasted this from another file. We should probably remove the `See the AUTHORS file` line everywhere because we don't have one.
</blockquote></details>

Yeah, only 109 of the files have this extra sentence, out of 1870 total that use the Apache license. How odd. This is like a disease that is spreading through our license headers.

**Review by petermattis — COMMENTED** [review]
TFTR! I should be able to finish the rest in another few hours. As predicted, this is mostly mechanical work.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29449#-:-LLKDqM1CSR0kkcVaWxp:b8emh9b)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/acceptance.go, line 23 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/29449#-LLIBJ9g8MhmeELm4L_B:-LLKDfmSAZxUPDNez-zj:b-82gp4j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d27dc1826fb4bdf4d9953612b65f330f982e4c49/pkg/cmd/roachtest/acceptance.go#L23)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Ooh, nice catch.
</blockquote></details>

Yeah, well one of the "local" acceptance tests I haven't got to requires 4 nodes which made this sort of obvious at that point.
___
*[pkg/cmd/roachtest/bank.go, line 14 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29449#-LLGuG6H6LYEMPuDbqm8:-LLKDmaPBW9hotldXMOu:b-3gll4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1ce1137a791d143cda361efb62a477ae408027b/pkg/cmd/roachtest/bank.go#L14)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Yeah, only 109 of the files have this extra sentence, out of 1870 total that use the Apache license. How odd. This is like a disease that is spreading through our license headers.
</blockquote></details>

I'll do this in a follow-on PR. Maybe further into the 2.2 cycle.

**Comment by petermattis** [comment]
bors r=benesch

**Comment by petermattis** [comment]
bors r=benesch

**Pull request merged**
