### PR TITLE
replica_rac2: integrate admitted tracking on leader

### PR DESCRIPTION
**Pull request by pav-kv**
This PR plumbs the admitted vectors into the RACv2 `Processor`. Admitted vectors are applied to `replicaSendStream` and cause releasing the tokens held by the leader.

The admitted vectors are plumbed to `replicaSendStream` via 3 paths:
- The leader's own admitted vector is applied from `HandleRaftReadyRaftMuLocked`, calling into `RangeController.AdmitRaftMuLocked` directly.
- The followers' admitted vectors in most cases are received via annotated `RaftMessageRequest.AdmittedState`, which is dispatched from `stepRaftGroupRaftMuLocked` into the `Processor` via `Processor.AdmitRaftMuLocked` method.
- The followers' piggybacked admitted vectors from `RaftMessageRequestBatch` are queued on the `Processor` via `EnqueuePiggybackedAdmittedAtLeader` method, and later applied from `HandleRaftReadyRaftMuLocked`.

Part of #129508

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130427)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130427#-O6S1BUADuMWE3pO8Do4:-O6S1BUBBDlh-pZuWiNo:bf69ukc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7158243ae609b70f80abc9f64482019ccc048852/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L68)):*
> ```Go
> 	//
> 	// Requires replica.raftMu to be held.
> 	AdmitRaftMuLocked(context.Context, roachpb.ReplicaID, AdmittedVector)
> ```

(1) I was initially not quite convinced that this pushing the `AdmittedVector` into the `RangeController` and it pushing into the `replicaSendStream` was the right approach.
`replicaSendStream` only exits in `StateReplicate` and are otherwise nil. We may have an `AdmittedVector` response that happens to come when the `replicaSendStream` did not exist, and would have wanted to remember it, so that it can be fetched later.

But I suppose it does not matter, since if the `replicaSendStream` does not exist, there are no tokens being held by it, so the `AdmittedVector` is also useless. btw, we are going to start creating `replicaSendStream`s only in `HandleRaftEventRaftMuLocked`, so the `MsgAppResp` in step that calls `AdmitRaftMuLocked` may not find a `replicaSendStream`. Again, this is not a real problem since tokens are not held, but coupling the lifecycle requirement does make me nervous.

(2) The prototype kept the AdmittedVectors for the followers in `processorImpl` since it also helped track when to ping. One could push the pinging responsibility into replicaSendStream, but I really wanted to keep `replicaSendStream` focused on queue management and being more passive, and not concerned with liveness. Also, there is more integration-y code there -- `TickAndReturnFollowerAdmittedProbesRaftMuLocked()` returns `RaftMessageRequest`, which better belong in `processorImpl`. Later we will also add a way for the Replica to query across the admitted vectors (without holding `raftMu`?) to decide whether the range can quiesce -- it seems to me that integration should also be satisfied by `processorImpl` instead of having to call into `rangeController` and it calling into `replicaSendStreams`.

(3) (minor point) I have a slight distaste for state-change interfaces, when there are a N methods related to N different things that can happen. One has to remember to call them in the right place which places more of a burden on the integration code being correct, in that we can't forget some place to call. A query interface to ask for the current state becomes an implementation detail of data-structure which is doing the query, and is more robust to forgetting state transitions (all we care about is the current state). This may not matter too much here, and I can certainly live with another method on `RangeController`, but I would like to keep this in-mind for the future. There was a conscious effort to try to reduce such state-change methods when going from the prototype to the merged changes, and we have been expanding these methods (first with the replica-side integration, e.g. `SyncedLogStorage`).

----
(2) is still a concern. I would like to see the pinging change in this PR, otherwise I worry about sub-optimal placement of the functionality. btw, it doesn't need to be split into too many commits if that adds overhead to doing the work -- I don't mind reviewing larger commits.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 12 files at r12, 1 of 1 files at r13, 2 of 2 files at r14, 2 of 2 files at r15, 3 of 3 files at r16, 1 of 1 files at r17, 7 of 7 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130427#-:-O6WZVZP2Clg0eIwB1pi:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/log_tracker.go` line 50 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/130427#-O6WWvZ09MRJo0hRiGbo:-O6WWvZ09MRJo0hRiGbp:b1harl9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f614b049ce4beb499f0a117362ce2f7c9b47b6b0/pkg/kv/kvserver/kvflowcontrol/rac2/log_tracker.go#L50)):*
> ```Go
> 			av.Admitted[pri] = their
> 		}
> 	}
> ```

Does this need a small unit test or are all the paths covered by the RangeController test?
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 388 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/130427#-O6WVKtY0sDXC70ayuC4:-O6WVKtY0sDXC70ayuC5:b-4cqmmh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c94c1b0da03c798677623bb8b1b98ca34f0287a/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L388)):*
> ```Go
> // vector is stale (either in Term, or the indices).
> //
> // Requires replica.raftMu to be held.
> ```

tiniest nit and unrelated to this PR @kvoli 
Is there a reason all the `rangeController` public methods copy the comment from the interface instead of saying `// AdmitRaftMuLocked implements RangeController.`. It's much more likely that the two comments will diverge. 
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 446 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/130427#-O6WXpCsCUOctz33oSiJ:-O6WXpCt26jkrFDtIQZF:byaisp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f70124048d9077356644385041adf242d6c6210f/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L446)):*
> ```Go
> 			// Invariant: rc == nil ==> len(admitted) == 0.
> 			// Invariant: len(admitted) != 0 ==> the processing is scheduled.
> 			admitted map[roachpb.ReplicaID]rac2.AdmittedVector
> ```

nit: how about calling these `enqueuedAdmitted` to make it clearer that these have not been applied.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 887 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/130427#-O6WYKASCxIFXxymtpdH:-O6WYKASCxIFXxymtpdI:b-eomc2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f70124048d9077356644385041adf242d6c6210f/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L887)):*
> ```Go
> 	from roachpb.ReplicaID, state kvflowcontrolpb.AdmittedState,
> ) {
> 	// TODO(pav-kv): we don't want to lock the wide mutex here.
> ```

future PR?

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130427)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/log_tracker.go` line 50 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/130427#-O6WWvZ09MRJo0hRiGbo:-O6Wv-iv8xpQCkg4hSDR:bh73a5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/f614b049ce4beb499f0a117362ce2f7c9b47b6b0/pkg/kv/kvserver/kvflowcontrol/rac2/log_tracker.go#L50)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Does this need a small unit test or are all the paths covered by the RangeController test?
</blockquote></details>

Done. No harm in adding a test.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130427#-O6S1BUADuMWE3pO8Do4:-O6Wz7jS6X4HmvUPe3O7:b-ntrc0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/7158243ae609b70f80abc9f64482019ccc048852/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L68)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

(1) I was initially not quite convinced that this pushing the `AdmittedVector` into the `RangeController` and it pushing into the `replicaSendStream` was the right approach.
`replicaSendStream` only exits in `StateReplicate` and are otherwise nil. We may have an `AdmittedVector` response that happens to come when the `replicaSendStream` did not exist, and would have wanted to remember it, so that it can be fetched later.

But I suppose it does not matter, since if the `replicaSendStream` does not exist, there are no tokens being held by it, so the `AdmittedVector` is also useless. btw, we are going to start creating `replicaSendStream`s only in `HandleRaftEventRaftMuLocked`, so the `MsgAppResp` in step that calls `AdmitRaftMuLocked` may not find a `replicaSendStream`. Again, this is not a real problem since tokens are not held, but coupling the lifecycle requirement does make me nervous.

(2) The prototype kept the AdmittedVectors for the followers in `processorImpl` since it also helped track when to ping. One could push the pinging responsibility into replicaSendStream, but I really wanted to keep `replicaSendStream` focused on queue management and being more passive, and not concerned with liveness. Also, there is more integration-y code there -- `TickAndReturnFollowerAdmittedProbesRaftMuLocked()` returns `RaftMessageRequest`, which better belong in `processorImpl`. Later we will also add a way for the Replica to query across the admitted vectors (without holding `raftMu`?) to decide whether the range can quiesce -- it seems to me that integration should also be satisfied by `processorImpl` instead of having to call into `rangeController` and it calling into `replicaSendStreams`.

(3) (minor point) I have a slight distaste for state-change interfaces, when there are a N methods related to N different things that can happen. One has to remember to call them in the right place which places more of a burden on the integration code being correct, in that we can't forget some place to call. A query interface to ask for the current state becomes an implementation detail of data-structure which is doing the query, and is more robust to forgetting state transitions (all we care about is the current state). This may not matter too much here, and I can certainly live with another method on `RangeController`, but I would like to keep this in-mind for the future. There was a conscious effort to try to reduce such state-change methods when going from the prototype to the merged changes, and we have been expanding these methods (first with the replica-side integration, e.g. `SyncedLogStorage`).

----
(2) is still a concern. I would like to see the pinging change in this PR, otherwise I worry about sub-optimal placement of the functionality. btw, it doesn't need to be split into too many commits if that adds overhead to doing the work -- I don't mind reviewing larger commits.
</blockquote></details>

(1) Seems like a valid concern w.r.t. the initialization race. But yeah, I thought it's fine because we only care about times when any tokens are held. The initial `MsgAppResp` that brings the replica to `StateReplicate`, sets `Match = MsgAppResp.Index`, and `Next > Match` (by invariant). Admitted indices in this message <= `Match`, and the stream starts acquiring tokens from `Next` which is > `Match` and does not overlap what's been admitted.

So we lose this "initial/handshake admission" information, but we don't use it. I can see why it could be useful though: we could (in some future) bootstrap the stream into a state which is more aware of the current situation on the follower, which can prevent initial send bursts. Whereas now we start from an unthrottled state.

(2) Possibly we'll want to move some thing to `processorImpl`, I'm not sure yet. If that proves necessary, we'll repurpose the `pendingAdmitted` map into just `admitted` with some dirty bit(s). Note that this PR doesn't go into some completely opposite direction. We still need: (a) an interface between `RangeController` and `Processor` to exchange the admitted vector, (b) a map to buffer the vectors.

For (a), this PR changed `AdmittedTracker` reverse-looking interface into a direct `AdmitRaftMuLocked` calls - that's related to your point (3). There is no much material difference, just preferences; and maybe the fact that `AdmitRaftMuLocked` is called only if necessary (i.e. the admitted vector has some updates), whereas the `AdmittedTracker`-based approach calls `GetAdmitted` every time from `makeConsistentInStateReplicate`. I would also add that with the direct call approach it is easier to trace the admission path(s) for the code reader, whereas with the `GetAdmitted` interface there is indirection which makes the code reader have to search for who modifies the things inside the `GetAdmitted` interface implementation and which implementation that is.

For (b), this PR adds a map which just happens to be a cache/queue cleared all the time. But if need be, we can stop clearing it and make it watch desc changes for compensating the need to GC removed replicas.

For now, this PR just does a minimal necessary change.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 388 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/130427#-O6WVKtY0sDXC70ayuC4:-O6Wv5lG0a-DvFMifWAY:b-h436fz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c94c1b0da03c798677623bb8b1b98ca34f0287a/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L388)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

tiniest nit and unrelated to this PR @kvoli 
Is there a reason all the `rangeController` public methods copy the comment from the interface instead of saying `// AdmitRaftMuLocked implements RangeController.`. It's much more likely that the two comments will diverge.
</blockquote></details>

Ack. Will leave as is to follow the pattern in this file, but we can fix commenting in a follow-up if needed.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 446 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/130427#-O6WXpCsCUOctz33oSiJ:-O6XEmVt-6huSvQDQbb2:b-ottrw7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f70124048d9077356644385041adf242d6c6210f/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L446)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: how about calling these `enqueuedAdmitted` to make it clearer that these have not been applied.
</blockquote></details>

Renamed to `pendingAdmitted`.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 887 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/130427#-O6WYKASCxIFXxymtpdH:-O6WvP3q4jygtAMuqV7Q:bv3wlzy) ([raw file](https://github.com/cockroachdb/cockroach/blob/f70124048d9077356644385041adf242d6c6210f/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L887)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

future PR?
</blockquote></details>

Yeah, removed this TODO because there is a large refactor #130459 on the way.

**Review by kvoli — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130427#-:-O6XaeEW1AIDXwz6sfRp:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130427#-O6S1BUADuMWE3pO8Do4:-O6X_NG_8LIxcObNAFA1:b-6qbfbx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7158243ae609b70f80abc9f64482019ccc048852/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L68)):*
I'm also less of a fan of having another mutation path unless necessary, like for replica / lease changes. IMO it complicates reasoning about mutation ordering, where previously almost all mutation logic took place in the `HandleRaftEventRaftMuLocked`.  
> (2) Possibly we'll want to move some thing to `processorImpl`, I'm not sure yet.

SGTM to reassess then.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 388 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/130427#-O6WVKtY0sDXC70ayuC4:-O6XWh9w9HGlnu7_deKO:bnvy2cj) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c94c1b0da03c798677623bb8b1b98ca34f0287a/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L388)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Ack. Will leave as is to follow the pattern in this file, but we can fix commenting in a follow-up if needed.
</blockquote></details>

I'll open a follow up for this later. My reasoning was convenience when reading impl methods, the risk of divergence is higher.

**Review by kvoli — APPROVED** [review]
:lgtm: (again, may have borked the reviewer state, unsure where the review approval went on github).

> Reviewed 2 of 3 files at r23, 2 of 2 files at r24, 7 of 7 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130427#-:-O6XbPct5letizzXXb-6:b-jswijq)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @sumeerbhola)

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r24, 3 of 7 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130427#-:-O6Y6uEIBZIq8I-hMDFS:bg7igkv)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @pav-kv)

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130427)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/log_tracker.go` line 50 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/130427#-O6WWvZ09MRJo0hRiGbo:-O6_iwKv0YGOdkU-KlcE:bpjk50b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f614b049ce4beb499f0a117362ce2f7c9b47b6b0/pkg/kv/kvserver/kvflowcontrol/rac2/log_tracker.go#L50)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Done. No harm in adding a test.
</blockquote></details>

Also added some basic piggybacked vector parsing into the `enqueue-piggybacked-admitted` datadriven command and extended the test a bit to make sure merging works in that path too. For now the command takes only one priority, but since we have the merging behaviour it's ok/convenient to do one at a time in tests.

**Pull request merged**
