### PR TITLE
insights: crdb_internal.cluster_execution_insights

### PR DESCRIPTION
**Pull request by matthewtodd**
Here we introduce a new virtual table for a cluster-wide view of
"insights," a subsystem of sqlstats that is currently disabled by
default but that will identify slow- and slower-than-usual statement
executions, along with other potentially problematic behaviors we will
be building support for.

This table will back the upcoming insights UI over the new SQL-over-HTTP
endpoint.

Release note (sql change): A new `crdb_internal` virtual table,
`cluster_execution_insights`, was introduced, offering a cluster-wide view
of the same node-local information available in `node_execution_insights`.
The insights subsystem is, as of this commit, still under development
and disabled by default, so there will not yet be much to see here.

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
Looks great! :D 

> Reviewed 25 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85339#-:-N8ATMMH60JKw5Yhrzlm:bhtdnaz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @matthewtodd)

___
*[`pkg/server/serverpb/status.proto` line 2284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85339#-N8AQuCz86u7SHpsjNEe:-N8AQuCz86u7SHpsjNEf:bpb10ww) ([raw file](https://github.com/cockroachdb/cockroach/blob/8581ae3d32576845eb9b3743c43191d94ba9b22f/pkg/server/serverpb/status.proto#L2284)):*
> ```protobuf
>   rpc ListExecutionInsights(ListExecutionInsightsRequest) returns (ListExecutionInsightsResponse) {}
> 
>   // ListExecutionInsights returns potentially problematic statements executed on this node,
> ```

nit: ListLocalExecutionInsights
___
*[`pkg/sql/sqlstats/insights/integration/insights_test.go` line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85339#-N8ATEGk3Z7bqKhi9yYf:-N8ATEGk3Z7bqKhi9yYg:b-jx641o) ([raw file](https://github.com/cockroachdb/cockroach/blob/8581ae3d32576845eb9b3743c43191d94ba9b22f/pkg/sql/sqlstats/insights/integration/insights_test.go#L58)):*
> ```Go
> 	// See no recorded insights.
> 	var count int
> 	row := conn.QueryRowContext(ctx, "SELECT count(*) FROM crdb_internal.cluster_execution_insights")
> ```

should we keep a test for the node level and then add one for the cluster level?

**Review by j82w — COMMENTED** [review]
> Reviewed 26 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85339)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)

___
*[`pkg/server/status.go` line 3144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85339#-N8APskE9Zepi7Ap_9c1:-N8APskE9Zepi7Ap_9c2:brmhflk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8581ae3d32576845eb9b3743c43191d94ba9b22f/pkg/server/status.go#L3144)):*
> ```Go
> 		}
> 		if len(resp.Errors) > 0 {
> 			return nil, errors.Errorf("%s", resp.Errors[0].Message)
> ```

Should this use "errors.CombineErrors" so it will have all the errors instead of just the first message?
___
*[`pkg/sql/crdb_internal.go` line 6261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85339#-N8ASJiFE0ffB5iLBUdF:-N8ASJiFE0ffB5iLBUdG:bwse3wc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8581ae3d32576845eb9b3743c43191d94ba9b22f/pkg/sql/crdb_internal.go#L6261)):*
> ```Go
> 			return err
> 		}
> 		response, err := p.extendedEvalCtx.SQLStatusServer.ListExecutionInsights(ctx, &serverpb.ListExecutionInsightsRequest{})
> ```

Will this table fail to load if one node is down or will it still load the content from all the other nodes that completed successfully?

**Review by matthewtodd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85339)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @maryliag)

___
*[`pkg/server/status.go` line 3144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85339#-N8APskE9Zepi7Ap_9c1:-N8AeH1A8BHDI0m-h-jo:b-nh2t0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/8581ae3d32576845eb9b3743c43191d94ba9b22f/pkg/server/status.go#L3144)):*
<details><summary><i>Previously, j82w wrote…</i></summary><blockquote>

Should this use "errors.CombineErrors" so it will have all the errors instead of just the first message?
</blockquote></details>

There will only be one error in this local response, so we can get away with it here. (Reusing the response types for the node-local and the cluster-wide requests makes the typing a little looser here.)
___
*[`pkg/server/serverpb/status.proto` line 2284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85339#-N8AQuCz86u7SHpsjNEe:-N8Aeikp8tj1oHOE7JaN:b5elb7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/8581ae3d32576845eb9b3743c43191d94ba9b22f/pkg/server/serverpb/status.proto#L2284)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: ListLocalExecutionInsights
</blockquote></details>

Oops! Thanks. Done.
___
*[`pkg/sql/crdb_internal.go` line 6261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85339#-N8ASJiFE0ffB5iLBUdF:-N8Af-DxEuEAY_cNMYX9:b-piczt6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8581ae3d32576845eb9b3743c43191d94ba9b22f/pkg/sql/crdb_internal.go#L6261)):*
<details><summary><i>Previously, j82w wrote…</i></summary><blockquote>

Will this table fail to load if one node is down or will it still load the content from all the other nodes that completed successfully? 
</blockquote></details>

It still loads from all the other nodes.
___
*[`pkg/sql/sqlstats/insights/integration/insights_test.go` line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85339#-N8ATEGk3Z7bqKhi9yYf:-N8Af2gdAejUiFbFuOv_:b-w5jhlq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8581ae3d32576845eb9b3743c43191d94ba9b22f/pkg/sql/sqlstats/insights/integration/insights_test.go#L58)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

should we keep a test for the node level and then add one for the cluster level?
</blockquote></details>

Good q. The existence and permission-checking of the node-level one are both tested elsewhere, so I'm inclined to trust the code sharing between the 2 implementations and not worry about it here -- especially since, now that we have the cluster-level view, there's not a strong need to keep the node-level one. WDYT?

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 1 of 27 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85339#-:-N8d7P4453WXtd0afMgc:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @j82w and @matthewtodd)

___
*[`pkg/sql/sqlstats/insights/integration/insights_test.go` line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85339#-N8ATEGk3Z7bqKhi9yYf:-N8d7LYX0-8Kl8HJC1ON:b-hfghm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8581ae3d32576845eb9b3743c43191d94ba9b22f/pkg/sql/sqlstats/insights/integration/insights_test.go#L58)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Good q. The existence and permission-checking of the node-level one are both tested elsewhere, so I'm inclined to trust the code sharing between the 2 implementations and not worry about it here -- especially since, now that we have the cluster-level view, there's not a strong need to keep the node-level one. WDYT?
</blockquote></details>

Sounds good

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85339)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @j82w and @matthewtodd)

___
*[`pkg/server/status.go` line 3144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85339#-N8APskE9Zepi7Ap_9c1:-N8dAQZL77TlMP-YYK0z:b-hf5ndn) ([raw file](https://github.com/cockroachdb/cockroach/blob/8581ae3d32576845eb9b3743c43191d94ba9b22f/pkg/server/status.go#L3144)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

There will only be one error in this local response, so we can get away with it here. (Reusing the response types for the node-local and the cluster-wide requests makes the typing a little looser here.)
</blockquote></details>

is `resp.Errors` ever populated by the `ListLocalExecutionInsights` call?
___
*[`pkg/server/serverpb/status.proto` line 1838 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85339#-N8dBBx91cVOIpxo-COU:-N8dBBx91cVOIpxo-COV:b-p42qps) ([raw file](https://github.com/cockroachdb/cockroach/blob/edc2871b146b58d28e7ff8dcc5662a565674250d/pkg/server/serverpb/status.proto#L1838)):*
> ```protobuf
> 
>   // errors holds any errors that occurred during fan-out calls to other nodes.
>   repeated ListActivityError errors = 2 [
> ```

shouldn't we use [`errorspb.EncodedErrors`](`https://github.com/cockroachdb/errors/blob/217058372e2042c4d08384adbd883316372f1070/errorspb/errors.proto#L10`) like the cool kids? `ListActivityError` can be a go type, and the client code that wants a node ID can access it, for example, as
```
type errWithNode interface {
  NodeID NodeID()
}

var ewn ErrWithNode
if errors.As(err, &ewn) {
  ewn.NodeID()
}
```
___
*[`pkg/server/serverpb/status.proto` line 2286 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85339#-N8d8wlT5SswKhK682Pt:-N8d8wlT5SswKhK682Pu:b-58j1qi) ([raw file](https://github.com/cockroachdb/cockroach/blob/edc2871b146b58d28e7ff8dcc5662a565674250d/pkg/server/serverpb/status.proto#L2286)):*
> ```protobuf
>   // ListLocalExecutionInsights returns potentially problematic statements executed on this node,
>   // along with actions we suggest the application developer might take to remedy them.
>   rpc ListLocalExecutionInsights(ListExecutionInsightsRequest) returns (ListExecutionInsightsResponse) {}
> ```

If you chose to have two different RPCs (as opposed to one with an optional `node_id`, as used to be the pattern), do we want these two RPCs to share a response proto? The `errors` field looks like it doesn't apply to this one.
___
*[`pkg/sql/crdb_internal.go` line 6233 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85339#-N8d9cYf-FR4lYWEougY:-N8d9cYf-FR4lYWEougZ:b-uept5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/edc2871b146b58d28e7ff8dcc5662a565674250d/pkg/sql/crdb_internal.go#L6233)):*
> ```Go
> }
> 
> const executionInsightsSchemaPattern = `
> ```

please list the tables that share this schema
___
*[`pkg/sql/crdb_internal.go` line 6241 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85339#-N8d9VCO6CV5ngTTRdEw:-N8d9VCO6CV5ngTTRdEx:b-jitat) ([raw file](https://github.com/cockroachdb/cockroach/blob/edc2871b146b58d28e7ff8dcc5662a565674250d/pkg/sql/crdb_internal.go#L6241)):*
> ```Go
> 	stmt_fingerprint_id        BYTES NOT NULL,
> 	query                      STRING NOT NULL,
> 	status                     STRING NOT NULL,
> ```

I think this `status` needs a comment.

**Review by matthewtodd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85339)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @j82w, @maryliag, and @matthewtodd)

___
*[`pkg/server/status.go` line 3144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85339#-N8APskE9Zepi7Ap_9c1:-N8y1ysZ-Yo0kEXAutCi:b-dgk2ky) ([raw file](https://github.com/cockroachdb/cockroach/blob/8581ae3d32576845eb9b3743c43191d94ba9b22f/pkg/server/status.go#L3144)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

is `resp.Errors` ever populated by the `ListLocalExecutionInsights` call?
</blockquote></details>

Good call, fixed by using a single RPC endpoint.
___
*[`pkg/server/serverpb/status.proto` line 1838 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85339#-N8dBBx91cVOIpxo-COU:-N8y270xBbaJK0ZXOGmU:b-qr3t63) ([raw file](https://github.com/cockroachdb/cockroach/blob/edc2871b146b58d28e7ff8dcc5662a565674250d/pkg/server/serverpb/status.proto#L1838)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

shouldn't we use [`errorspb.EncodedErrors`](`https://github.com/cockroachdb/errors/blob/217058372e2042c4d08384adbd883316372f1070/errorspb/errors.proto#L10`) like the cool kids? `ListActivityError` can be a go type, and the client code that wants a node ID can access it, for example, as
```
type errWithNode interface {
  NodeID NodeID()
}

var ewn ErrWithNode
if errors.As(err, &ewn) {
  ewn.NodeID()
}
```


</blockquote></details>

Cool, I didn't know about this. Switched. (Decided to just pass the unadorned errors for now, unclear whether we'll care about knowing the `NodeID`.)
___
*[`pkg/server/serverpb/status.proto` line 2286 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85339#-N8d8wlT5SswKhK682Pt:-N93BCZp-qLRWMkBF4Ju:b-dgk2ky) ([raw file](https://github.com/cockroachdb/cockroach/blob/edc2871b146b58d28e7ff8dcc5662a565674250d/pkg/server/serverpb/status.proto#L2286)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

If you chose to have two different RPCs (as opposed to one with an optional `node_id`, as used to be the pattern), do we want these two RPCs to share a response proto? The `errors` field looks like it doesn't apply to this one.
</blockquote></details>

Good call, fixed by using a single RPC endpoint.
___
*[`pkg/sql/crdb_internal.go` line 6233 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85339#-N8d9cYf-FR4lYWEougY:-N939mI009eLXqVKaczd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/edc2871b146b58d28e7ff8dcc5662a565674250d/pkg/sql/crdb_internal.go#L6233)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please list the tables that share this schema
</blockquote></details>

Done.
___
*[`pkg/sql/crdb_internal.go` line 6241 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85339#-N8d9VCO6CV5ngTTRdEw:-N939ncI-sFyN4vFA6gs:b7l8qyp) ([raw file](https://github.com/cockroachdb/cockroach/blob/edc2871b146b58d28e7ff8dcc5662a565674250d/pkg/sql/crdb_internal.go#L6241)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think this `status` needs a comment.
</blockquote></details>

Agreed. @j82w WDYT? Do we need this column? Could it be an enum instead?

**Pull request merged**
