### PR TITLE
opt: push filter into lookup join

### PR DESCRIPTION
**Pull request by rytaft**
This commit adds two exploration rules to push a filter
into a lookup join. One rule applies when the filter conditions
are fully bound by the input to the lookup join, in which case
the entire filter can be pushed down. The other applies when
only some of the filter conditions are bound by the input
to the lookup join. In that case, only the bound conditions
can be pushed down.

This commit supercedes a previous commit which only pushed
down conditions that could be expressed as constraints on
a Scan node.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Why are this explore rules and not normalization? Are there cases where we don't want to push down filters?

I have some WIP that will be adding an OnExpr to LookupJoin (and probably split it into LookupInnerJoin and LookupLeftJoin). Will it be easy to adjust the new rules? I was hoping we could just reuse existing rules for joins

**Comment by rytaft** [comment]
Regarding exploration v. normalization: @andy-kimball can probably answer this better than I can, but the problem is that expressions created by exploration rules do not trigger normalization of nodes higher up in the tree. In this case, the lookup join expression is created by the `GenerateIndexScans` rule, which only modifies the subtree of the Scan node matched by the rule. If there is a Select above the Scan, it will not be re-normalized.

Regarding adjustment of the new rules: I need a bit more context, but I think it should be possible....

---







*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26472#-:-LELY31F9PR4OVoy5buk:b5yypfu)*

**Comment by RaduBerinde** [comment]
I see, yeah the rule would be on a select that is not being re-constructed.

OnExpr will be like the On expression in any other join. The rules of pushing filters into the OnExpr of InnerJoin, and pushing (parts of) the OnExpr into the right input should apply.

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[pkg/sql/opt/xform/rules/select.opt, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26472#-LELd0PLAOw9mMil98fB:-LELd0PLAOw9mMil98fC:b-7sew1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/a243414026327320f44ad26a763fbd98bff9e9a7/pkg/sql/opt/xform/rules/select.opt#L20)):*
> ```
> # which the Select filter condition is fully bound by the input to the lookup
> # join. If this rule matches, it pushes the Select fully below the lookup join.
> [PushFilterIntoLookupJoinNoRemainder, Explore]
> ```

Is this rule an optimization, to avoid repeated applications of the next rule in this case? I'm asking because it seems that functionally, the other rule should be enough (without the `^(IsBoundBy $filter $input)` condition)

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26472#-:-LELdSkc1_qb37fdg6PD:bnfp4nl)*

**Comment by rytaft** [comment]
*[pkg/sql/opt/xform/rules/select.opt, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26472#-LELd0PLAOw9mMil98fB:-LELdbRf6WHEXTLctPtU:bf3ttz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a243414026327320f44ad26a763fbd98bff9e9a7/pkg/sql/opt/xform/rules/select.opt#L20)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Is this rule an optimization, to avoid repeated applications of the next rule in this case? I'm asking because it seems that functionally, the other rule should be enough (without the `^(IsBoundBy $filter $input)` condition)
</blockquote></details>

The problem is that the other rule would create a `Select` with filter condition `True`, which would not get normalized away (since exploration rules don't re-construct the root node).

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26472)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/opt/xform/rules/select.opt, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26472#-LELd0PLAOw9mMil98fB:-LELmvc39qsOsIkil7Kb:b-ggi061) ([raw file](https://github.com/cockroachdb/cockroach/blob/a243414026327320f44ad26a763fbd98bff9e9a7/pkg/sql/opt/xform/rules/select.opt#L20)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

The problem is that the other rule would create a `Select` with filter condition `True`, which would not get normalized away (since exploration rules don't re-construct the root node).
</blockquote></details>

Oh, I see, thanks for the explanation!

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26472)*

**Comment by andy-kimball** [comment]
The trouble is that we don't always push the filter down. If the memo looks like this:
```
[G10] Select G9 ...
[G9] Scan | LookupJoin
...
```
The `Select` only gets pushed down into the `LookupJoin`, not into the `Scan`. We still want to retain the original `Select->Scan` complex as well, since its cost might be lower than `LookupJoin->Select`. So we can't use a normalization, since that discards the tree it matches in favor of the replacement tree.

That said, Rebecca and I were talking about the possibility of running normalization rules on the root of the tree produced by an exploration rule (before adding it to the existing memo group). Today we don't do that, which leads to the issue of a `Select True` dummy node that's not optimized away (and is why Rebecca needed to add 2 exploration rules). This is something we should probably improve.

---

Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26472#-:-LEMZCJu3aLCIuEoh43I:b-2lp86c)*

**Comment by andy-kimball** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/opt/exec/execbuilder/testdata/select_index, line 1201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26472#-LEMcZdh8oDRdtYRf3hg:-LEMcZdh8oDRdtYRf3hh:b-bwoknr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a243414026327320f44ad26a763fbd98bff9e9a7/pkg/sql/opt/exec/execbuilder/testdata/select_index#L1201)):*
> ```
>  │         render 0  a                                                                   ·          ·
>  └── scan  ·         ·                                                                   (a, b, s)  ·
> ·          table     t2@primary                                                          ·          ·
> ```

This seems like a worse plan than before. How come the optimizer is choosing it?

---

*[pkg/sql/opt/norm/factory.go, line 624 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26472#-LEMczK_BWsWJCyJ-Z9y:-LEMczK_BWsWJCyJ-Z9z:bkc13vt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a243414026327320f44ad26a763fbd98bff9e9a7/pkg/sql/opt/norm/factory.go#L624)):*
> ```Go
> // The (Eq) expression is fully bound by the (Scan a) expression because all of
> // its outer references are satisfied by the columns produced by the Scan.
> func (f *Factory) IsBoundBy(src, dst memo.GroupID) bool {
> ```

This violates the current design of `Factory`, because it exports methods that are really not meant to be part of the factory interface, but are instead meant to be used internally by rules. My concern is that this will lead to a very messy "kitchen-sink" design for the factory, with all kinds of random methods being exported purely on the basis if some other package happens to need them. We should talk further about possible ways to avoid this.

---

*[pkg/sql/opt/optgen/cmd/optgen/rule_gen.go, line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26472#-LEMdz3nAybPEx0GvtfL:-LEMdz3nAybPEx0GvtfM:btesyom) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c70e54e7fd2f858c14c504f908712b808916fe3/pkg/sql/opt/optgen/cmd/optgen/rule_gen.go#L243)):*
> ```Go
> 
> func (g *ruleGen) genMatchList(match lang.Expr, contextName string, noMatch bool) {
> 	if !g.normalize {
> ```

Need a few exploration tests for the new functionality we're exposing here.

---

*[pkg/sql/opt/xform/explorer.go, line 360 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26472#-LEMe6hx6zbgjbDtbY2x:-LEMe6hx6zbgjbDtbY2y:bxsja15) ([raw file](https://github.com/cockroachdb/cockroach/blob/a243414026327320f44ad26a763fbd98bff9e9a7/pkg/sql/opt/xform/explorer.go#L360)):*
> ```Go
> }
> 
> // isBoundBy returns true if all outer references in the source expression are
> ```

The other side of using newly exported `Factory` methods is that we still need to cut and paste a number of lines of comments/code, which is not ideal either. We need a clean way to reuse shared custom functions that minimizes cut-and-paste, as well as API cluttering.

---

*[pkg/sql/opt/xform/rules/select.opt, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26472#-LELd0PLAOw9mMil98fB:-LEMeWVR8_59XfgYJVCc:bhd59bo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a243414026327320f44ad26a763fbd98bff9e9a7/pkg/sql/opt/xform/rules/select.opt#L20)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Oh, I see, thanks for the explanation!
</blockquote></details>

Add to the comment explaining that. In addition, I usually would add a note to the rule below to remind developers that it should stay ordered *after* this rule.

---

*[pkg/sql/opt/xform/testdata/external/tpcc, line 597 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26472#-LEMeujrC5BGNxxrJQYK:-LEMeujrC5BGNxxrJQYL:bs49fo0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a243414026327320f44ad26a763fbd98bff9e9a7/pkg/sql/opt/xform/testdata/external/tpcc#L597)):*
> ```
> ORDER BY s_i_id
> ----
> sort
> ```

This looks like a significantly worse plan. How come we don't use the secondary index any more?

---

*[pkg/sql/opt/xform/testdata/rules/select, line 295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26472#-LEMfKB6BvhuZddTLp4x:-LEMfKB6BvhuZddTLp4y:b-d6y5nc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a243414026327320f44ad26a763fbd98bff9e9a7/pkg/sql/opt/xform/testdata/rules/select#L295)):*
> ```
>  ├── keys: (1) (3)
>  └── scan b@v
>       ├── columns: k:1(int!null) v:3(int!null)
> ```

What part of this change caused us to start inferring not null in various places?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26472)*

**Comment by rytaft** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/norm/factory.go, line 624 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26472#-LEMczK_BWsWJCyJ-Z9y:-LEuchfy2F9BJinDg4cc:bu0wkop) ([raw file](https://github.com/cockroachdb/cockroach/blob/a243414026327320f44ad26a763fbd98bff9e9a7/pkg/sql/opt/norm/factory.go#L624)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This violates the current design of `Factory`, because it exports methods that are really not meant to be part of the factory interface, but are instead meant to be used internally by rules. My concern is that this will lead to a very messy "kitchen-sink" design for the factory, with all kinds of random methods being exported purely on the basis if some other package happens to need them. We should talk further about possible ways to avoid this.
</blockquote></details>

Fixed in #26578

---

*[pkg/sql/opt/xform/explorer.go, line 360 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26472#-LEMe6hx6zbgjbDtbY2x:-LEud01H2D1Q3-3snhJo:bu0wkop) ([raw file](https://github.com/cockroachdb/cockroach/blob/a243414026327320f44ad26a763fbd98bff9e9a7/pkg/sql/opt/xform/explorer.go#L360)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

The other side of using newly exported `Factory` methods is that we still need to cut and paste a number of lines of comments/code, which is not ideal either. We need a clean way to reuse shared custom functions that minimizes cut-and-paste, as well as API cluttering.
</blockquote></details>

Fixed in #26578

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26472)*

**Comment by rytaft** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/exec/execbuilder/testdata/select_index, line 1201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26472#-LEMcZdh8oDRdtYRf3hg:-LEzNEY0EJNwVXcJ6zZG:b-3g4zyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a243414026327320f44ad26a763fbd98bff9e9a7/pkg/sql/opt/exec/execbuilder/testdata/select_index#L1201)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This seems like a worse plan than before. How come the optimizer is choosing it?
</blockquote></details>

Fixed so it's choosing the same plan as before

---

*[pkg/sql/opt/xform/testdata/external/tpcc, line 597 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26472#-LEMeujrC5BGNxxrJQYK:-LEzNQRHDHDZxagXjrYi:b-3g4zyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a243414026327320f44ad26a763fbd98bff9e9a7/pkg/sql/opt/xform/testdata/external/tpcc#L597)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This looks like a significantly worse plan. How come we don't use the secondary index any more?
</blockquote></details>

Fixed so it's choosing the same plan as before

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26472)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/xform/rules/select.opt, line 93 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26472#-LF2VnpJ6x_dKigGz6j9:-LF2VnpJ6x_dKigGz6jA:b-2ksw01) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8a8bfb6d16ab00fafe19fbe14b8bbe52f7a5e8/pkg/sql/opt/xform/rules/select.opt#L93)):*
> ```
> #   )
> #
> # Neither of the above two rules would find this plan.
> ```

Do we have a test in `testdata/rules/select` where this rule is important?

Also, maybe add a TODO that we might want in general to have a mechanism for pushdown than is more powerful than finding conjuncts that are fully bound.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26472#-:-LF2Wp3q1zKId5f_st2U:bnfp4nl)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/xform/rules/select.opt, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26472#-LELd0PLAOw9mMil98fB:-LF3zm-e9OWXOx96dO0e:biae22d) ([raw file](https://github.com/cockroachdb/cockroach/blob/a243414026327320f44ad26a763fbd98bff9e9a7/pkg/sql/opt/xform/rules/select.opt#L20)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Added to the comment. I don't think the order matters, since these two rules are mutually exclusive (they will match disjoint sets of queries).
</blockquote></details>

It does matter a bit for performance. There's no reason to iterate over the filter conditions if the entire filter can be pushed down at once. All else being equal, it's better to keep this rule first.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26472#-:-LF40p2f5whuqhHoHPas:bnfp4nl)*

**Comment by rytaft** [comment]
TFTRs!

bors r+

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

---

*[pkg/sql/opt/xform/rules/select.opt, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26472#-LELd0PLAOw9mMil98fB:-LF5cr2j3T0D99t53iLl:b-2xf2ui) ([raw file](https://github.com/cockroachdb/cockroach/blob/a243414026327320f44ad26a763fbd98bff9e9a7/pkg/sql/opt/xform/rules/select.opt#L20)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

It does matter a bit for performance. There's no reason to iterate over the filter conditions if the entire filter can be pushed down at once. All else being equal, it's better to keep this rule first.
</blockquote></details>

Ah good point. Updated the comment.

---

*[pkg/sql/opt/xform/rules/select.opt, line 93 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26472#-LF2VnpJ6x_dKigGz6j9:-LF5czKJ2OwxKMPrtC1t:b-qw00p8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8a8bfb6d16ab00fafe19fbe14b8bbe52f7a5e8/pkg/sql/opt/xform/rules/select.opt#L93)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Do we have a test in `testdata/rules/select` where this rule is important?

Also, maybe add a TODO that we might want in general to have a mechanism for pushdown than is more powerful than finding conjuncts that are fully bound.
</blockquote></details>

Good point - added a test. Also added a TODO.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26472#-:-LF5dA5X8_2mwMi8dBfe:b-tlx7ko)*

**Pull request merged**
