### PR TITLE
kv: disallow 1PC evaluation when heartbeating and txn record present

### LINKED ISSUE #53403: roachtest: kv/contention/nodes=4 failed
[(roachtest).kv/contention/nodes=4 failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2219091&tab=buildLog) on [master@300dbe9a958a9461f320e262b0929cf2c44b7c24](https://github.com/cockroachdb/cockroach/commits/300dbe9a958a9461f320e262b0929cf2c44b7c24):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/kv/contention/nodes=4/run_1
	ts_util.go:130,kv.go:259,cluster.go:2575,errgroup.go:57: spent 80.701754% of time below target of 100.000000 txn/s, wanted no more than 5.000000%

	cluster.go:2597,kv.go:262,test_runner.go:754: monitor failure: monitor task failed: t.Fatal() was called
		(1) attached stack trace
		  -- stack trace:
		  | main.(*monitor).WaitE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2585
		  | main.(*monitor).Wait
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2593
		  | main.registerKVContention.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/kv.go:262
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:754
		Wraps: (2) monitor failure
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | main.(*monitor).wait.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2641
		Wraps: (4) monitor task failed
		Wraps: (5) attached stack trace
		  -- stack trace:
		  | main.init
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2555
		  | runtime.doInit
		  | 	/usr/local/go/src/runtime/proc.go:5228
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:190
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		Wraps: (6) t.Fatal() was called
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.leafError

```

<details><summary>More</summary><p>

Artifacts: [/kv/contention/nodes=4](https://teamcity.cockroachdb.com/viewLog.html?buildId=2219091&tab=artifacts#/kv/contention/nodes=4)
Related:
- #52878 roachtest: kv/contention/nodes=4 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-provisional_202008151325_v19.2.10](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-provisional_202008151325_v19.2.10) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #45698 roachtest: kv/contention/nodes=4 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-19.2](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-19.2) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Akv%2Fcontention%2Fnodes%3D4.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #53518: roachtest: kv/contention/nodes=4 failed
[(roachtest).kv/contention/nodes=4 failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2225322&tab=buildLog) on [provisional_202008261913_v20.2.0-beta.1@eaa939ce6548a54a23970814ff00f30ad87680ac](https://github.com/cockroachdb/cockroach/commits/eaa939ce6548a54a23970814ff00f30ad87680ac):

```
The test failed on branch=provisional_202008261913_v20.2.0-beta.1, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/kv/contention/nodes=4/run_1
	ts_util.go:116,kv.go:260,cluster.go:2591,errgroup.go:57: average txns per second 93.895596 was under target 100.000000

	cluster.go:2613,kv.go:263,test_runner.go:754: monitor failure: monitor task failed: t.Fatal() was called
		(1) attached stack trace
		  -- stack trace:
		  | main.(*monitor).WaitE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2601
		  | main.(*monitor).Wait
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2609
		  | main.registerKVContention.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/kv.go:263
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:754
		Wraps: (2) monitor failure
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | main.(*monitor).wait.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2657
		Wraps: (4) monitor task failed
		Wraps: (5) attached stack trace
		  -- stack trace:
		  | main.init
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2571
		  | runtime.doInit
		  | 	/usr/local/go/src/runtime/proc.go:5228
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:190
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		Wraps: (6) t.Fatal() was called
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.leafError

```

<details><summary>More</summary><p>

Artifacts: [/kv/contention/nodes=4](https://teamcity.cockroachdb.com/viewLog.html?buildId=2225322&tab=artifacts#/kv/contention/nodes=4)
Related:
- #53403 roachtest: kv/contention/nodes=4 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-master](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-master) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #52878 roachtest: kv/contention/nodes=4 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-provisional_202008151325_v19.2.10](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-provisional_202008151325_v19.2.10) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #45698 roachtest: kv/contention/nodes=4 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-19.2](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-19.2) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Akv%2Fcontention%2Fnodes%3D4.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #53772: roachtest: kv/contention/nodes=4 failed
[(roachtest).kv/contention/nodes=4 failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2236998&tab=buildLog) on [master@4a25ab1bc85e404b1a8b3e28660e41e7e5063e0b](https://github.com/cockroachdb/cockroach/commits/4a25ab1bc85e404b1a8b3e28660e41e7e5063e0b):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/kv/contention/nodes=4/run_1
	ts_util.go:130,kv.go:261,cluster.go:2617,errgroup.go:57: spent 14.035088% of time below target of 100.000000 txn/s, wanted no more than 5.000000%

	cluster.go:2639,kv.go:264,test_runner.go:754: monitor failure: monitor task failed: t.Fatal() was called
		(1) attached stack trace
		  -- stack trace:
		  | main.(*monitor).WaitE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2627
		  | main.(*monitor).Wait
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2635
		  | main.registerKVContention.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/kv.go:264
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:754
		Wraps: (2) monitor failure
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | main.(*monitor).wait.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2683
		Wraps: (4) monitor task failed
		Wraps: (5) attached stack trace
		  -- stack trace:
		  | main.init
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2597
		  | runtime.doInit
		  | 	/usr/local/go/src/runtime/proc.go:5228
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:190
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		Wraps: (6) t.Fatal() was called
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.leafError

```

<details><summary>More</summary><p>

Artifacts: [/kv/contention/nodes=4](https://teamcity.cockroachdb.com/viewLog.html?buildId=2236998&tab=artifacts#/kv/contention/nodes=4)
Related:
- #53518 roachtest: kv/contention/nodes=4 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-provisional_202008261913_v20.2.0-beta.1](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-provisional_202008261913_v20.2.0-beta.1) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Akv%2Fcontention%2Fnodes%3D4.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #54094: roachtest: kv/contention/nodes=4 failed
[(roachtest).kv/contention/nodes=4 failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2254937&tab=buildLog) on [release-20.2@d9ff57ed3d5891ab93b7756be657ba868ecc87a6](https://github.com/cockroachdb/cockroach/commits/d9ff57ed3d5891ab93b7756be657ba868ecc87a6):

```
The test failed on branch=release-20.2, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/kv/contention/nodes=4/run_1
	ts_util.go:116,kv.go:261,cluster.go:2626,errgroup.go:57: average txns per second 22.178049 was under target 100.000000

	cluster.go:2648,kv.go:264,test_runner.go:754: monitor failure: monitor task failed: t.Fatal() was called
		(1) attached stack trace
		  -- stack trace:
		  | main.(*monitor).WaitE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2636
		  | main.(*monitor).Wait
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2644
		  | main.registerKVContention.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/kv.go:264
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:754
		Wraps: (2) monitor failure
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | main.(*monitor).wait.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2692
		Wraps: (4) monitor task failed
		Wraps: (5) attached stack trace
		  -- stack trace:
		  | main.init
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2606
		  | runtime.doInit
		  | 	/usr/local/go/src/runtime/proc.go:5228
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:190
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		Wraps: (6) t.Fatal() was called
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.leafError

```

<details><summary>More</summary><p>

Artifacts: [/kv/contention/nodes=4](https://teamcity.cockroachdb.com/viewLog.html?buildId=2254937&tab=artifacts#/kv/contention/nodes=4)
Related:
- #53772 roachtest: kv/contention/nodes=4 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-master](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-master) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #53518 roachtest: kv/contention/nodes=4 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-provisional_202008261913_v20.2.0-beta.1](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-provisional_202008261913_v20.2.0-beta.1) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #53403 roachtest: kv/contention/nodes=4 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-master](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-master) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Akv%2Fcontention%2Fnodes%3D4.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by nvb**
Fixes #53403.
Fixes #53518.
Fixes #53772
Fixes #54094.

This commit disables one-phase commit evaluation for transactions with existing PENDING transaction records. As we saw in https://github.com/cockroachdb/cockroach/issues/53518#issuecomment-690626279, failing to do so can lead to a transaction that commits on the one-phase commit fast-path but still has a PENDING transaction record. It doesn't seem like this can actually cause serious correctness issues today other than in the presence of replays because a 1PC transaction does not have remote intents (by definition). However, it was creating the appearance of abandoned transaction records in `kv/contention/nodes=4` and causing that test to fail.

This commit needs a backport to release-20.2 and release-20.1. This was not an issue before release-20.1 because before then, we would never begin a transaction's heartbeat loop for 1PC transactions. This changed in v20.1 because of unreplicated locks. We allow transactions that acquire unreplicated locks to still hit the one-phase commit fast-path, but we also need to start heartbeating once a transaction has acquired any locks so that it doesn't get aborted by conflicting transactions.

In the vast majority of these cases, the heartbeat loop will never actually fire (for any txn that takes less than 1s), so with this change, we'll still be able to perform a 1PC evaluation. However, this is adding in a disk read for those cases, which is a little disappointing but doesn't seem easy to avoid without disabling the heartbeat loop before issuing the 1PC batch (another alternative, happy to discuss). The upside of this is that we now have enough information on the server to avoid a bit of work for 1PC txns that have not previously acquired locks (see TODO in evaluate1PC).

### CODE REVIEW

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54230#-:-MGyxyDa704HqAKMuyht:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_write.go, line 511 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54230#-MGyxTLH3C_4oxzK-QHG:-MGyxTLH3C_4oxzK-QHH:bdqe9nj) ([raw file](https://github.com/cockroachdb/cockroach/blob/30bae6cb32aa962ed0d08a2253e8e654d9ce2544/pkg/kv/kvserver/replica_write.go#L511)):*
> ```Go
> 	// be released.
> 	//
> 	// TODO(nvanbenschoten): once we can rely on EndTxn.TxnHeartbeating being
> ```

Would we really want to do that? What's the harm in replicating these ResolvedLocks?
___
*[pkg/kv/kvserver/batcheval/transaction.go, line 197 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54230#-MGywkiQ1EU-v5a-xnUv:-MGywkiQ1EU-v5a-xnUw:b-cxp6bm) ([raw file](https://github.com/cockroachdb/cockroach/blob/30bae6cb32aa962ed0d08a2253e8e654d9ce2544/pkg/kv/kvserver/batcheval/transaction.go#L197)):*
> ```Go
> }
> 
> // HasTxnRecord returns whether the provided transaction has a transaction
> ```

say that this can only be used on the transaction's range

**Review by nvb — COMMENTED** [review]
TFTR!

I'm testing this now to see how much of an impact it has on YCSB-A.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54230#-:-MHCVw7w5uSt_txpx1mZ:b-r5g16t)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei)

___
*[pkg/kv/kvserver/replica_write.go, line 511 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54230#-MGyxTLH3C_4oxzK-QHG:-MHCW0nf5bOQl30pwK-1:bm4o7gr) ([raw file](https://github.com/cockroachdb/cockroach/blob/30bae6cb32aa962ed0d08a2253e8e654d9ce2544/pkg/kv/kvserver/replica_write.go#L511)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Would we really want to do that? What's the harm in replicating these ResolvedLocks?
</blockquote></details>

Just a few memory allocations and a few lock-table traversals. Nothing serious, but there's also no reason to if we can avoid it.
___
*[pkg/kv/kvserver/batcheval/transaction.go, line 197 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54230#-MGywkiQ1EU-v5a-xnUv:-MHCWTpn35hHF5N2gwpX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30bae6cb32aa962ed0d08a2253e8e654d9ce2544/pkg/kv/kvserver/batcheval/transaction.go#L197)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

say that this can only be used on the transaction's range
</blockquote></details>

Done.

**Comment by nvanbenschoten** [comment]
There doesn't seem to be a statistically significant difference in performance with and without this change on YCSB-A. If anything, I measured a speedup over 12 runs, which doesn't make any sense and so likely means that the effect of this is all in the noise:
```
name                   old ops/sec  new ops/sec  delta
ycsb/A/nodes=3          16.5k ± 7%   16.7k ± 9%    ~     (p=0.671 n=12+12)
ycsb/A/nodes=3/cpu=32   27.3k ± 8%   28.4k ± 5%  +4.30%  (p=0.024 n=12+12)

name                   old p50(ms)  new p50(ms)  delta
ycsb/A/nodes=3           3.80 ± 3%    3.88 ± 8%    ~     (p=0.592 n=10+12)
ycsb/A/nodes=3/cpu=32    2.70 ± 7%    2.52 ± 5%  -6.73%  (p=0.000 n=12+11)

name                   old p99(ms)  new p99(ms)  delta
ycsb/A/nodes=3           44.9 ±35%    40.4 ±30%    ~     (p=0.307 n=12+11)
ycsb/A/nodes=3/cpu=32    73.8 ± 8%    68.5 ±10%  -7.21%  (p=0.020 n=10+12)
```

bors r+

**Comment by andreimatei** [comment]
Nathan were you going to backport this? Asking cause the contention roachtest failed on 20.2 again https://github.com/cockroachdb/cockroach/issues/54554

**Comment by nvanbenschoten** [comment]
I was holding off while looking into shutting down the heartbeat loop early when possible to be able to set the new `TxnHeartbeating=false` flag more often. That was fairly successful, but got messy when a transaction restarted and had to re-start its heartbeat loop. I don't think it's a good idea to backport that, so I just opened #54571.

**Pull request merged**
