### PR TITLE
sql: fix test to use timestamptz

### PR DESCRIPTION
**Pull request by vivekmenezes**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9579)

### CODE REVIEW

**Comment by knz** [comment]
Please add a comment to explain what the test is doing and why you needed to make the change.

**Comment by vivekmenezes** [comment]
I'm actually not sure why this fixes it. I think I'm going to disable the
test for now so that the develop branch is not broken.

**Comment by vivekmenezes** [comment]
Okay now I understand the problem. Updated the comments. Thanks

**Comment by vivekmenezes** [comment]
I'm going to sleep, so merge this if you want

**Comment by knz** [comment]
I checked the problem and the fix. 
Basically merging #9444 broke this test by introducing a subtle bug that would trigger any time between 7pm and 12am every day: `now()` creates a timestamp using the session's TZ (which in the test is set to -5), but `current_date()` ignores the session's TZ. 

Of course the test fails but really the bug is in `current_date()`. I'll merge this once CircleCI passes as a workaround, but really we ought to fix `current_date()`.

**Pull request merged**
