### PR TITLE
packer: add packer template for arm linux build agent

### PR DESCRIPTION
**Pull request by rickystewart**
Release note: None
Release justification: Non-production code changes

### CODE REVIEW

**Review by rail — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77842#-:-NAC1l8NApryZ3vqHlXU:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jlinder)

**Review by jlinder — CHANGES_REQUESTED** [review]
One change request and then this is good to go!

**Comment by rickystewart** [comment]
bors r=rail

**Comment by rickystewart** [comment]
bors r=rail

**Comment by rickystewart** [comment]
@jlinder You'll have to re-review for `bors` to accept this.

**Review by jlinder — APPROVED** [review]
LGTM!

**Pull request merged**
