### PR TITLE
exec: implement remaining distributed flow work

### LINKED ISSUE #37051: exec: plan distributed flows
Once the components in #36661 are completed, they will need to be planned in `column_exec_setup.go`.

The main thing that needs to change is that we will now support outputs specified as `OutputRouterSpec_BY_HASH ` that potentially have more than one `Stream`. This is the case in which we reach a `HashRouter` in the plan. At a high level, a `HashRouter` will need to be instantiated as well as a corresponding `Outbox` for each `routerOutput` that is not designated as `distsqlpb.StreamEndpointSpec_LOCAL`. Once that is done, the `Outboxes` will be added to the flow as `startables` (i.e. run in their own goroutine) and can be forgotten, while the local endpoints will be added to the queue to be processed as inputs on further iterations of `setupVectorized`.

There is an additional case where there is no router, but just a remote stream. This can be observed by checking for `StreamEndpointSpec_REMOTE`. This means that an `Outbox` must be created for this stream and appended as a `startable` to the flow. The `Inbox`es in all cases will be added to a registry (similar to what is done now).

Once these cases are handled, there is a missing piece regarding remote communication. The `FlowStream` handler on the distsql server must be extended to recognize a `FlowStream` RPC as a vectorized `FlowStream` RPC which will fetch an `Inbox` from a registry and call `RunWithStream`. The specifics of this will probably become clearer but this can be done with an extra field in the header or based on the `FowID`.

Here are the more concrete points:

- [ ] Create `HashRouter` and `routerOutput`s when encountering `OutputRouterSpec_BY_HASH`
- [ ] Create `Outbox`es for the above outputs, as well as solitary `distsqlpb.StreamEndpointSpec_REMOTE` specs.
- [ ] Plan synchronizers (ordered/unordered).
- [ ] Register inboxes somehow to be accessed when handling `FlowStream` RPCs.
- [ ] Cancellation strategy for inbox in case a remote stream does not
arrive in time.
- [ ] hashRouter implementation of the DrainMeta interface to propagate
metadata.
- [ ] Flow teardown when at least one node in the plan gets a plan
unsupported by vectorized execution.

### PR DESCRIPTION
**Pull request by asubiotto**
See individual commits for details. Only the last three are new. This PR implements the remaining work for distributed vectorized flow execution outlined in #38030 
- Cancellation strategy for inbox in case a remote stream does not
arrive in time.
- Flow teardown when at least one node in the plan gets a plan
unsupported by vectorized execution. This is implemented by retrying the flow setup requests with vectorized off. The old flow will be torn down after a timeout.
- hashRouter implementation of the DrainMeta interface to propagate
metadata.

Closes #37051

I might close #38030 and merge the last versions of those commits in this PR to merge as a unit.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Three new commits look good to me. I'd also close the other PR to make it easier for Jordan to review all the changes.

> Reviewed 3 of 3 files at r6, 2 of 2 files at r7, 4 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38233#-:-Lhbp10B1yKPcSHFXbJ3:b6f0uum)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 212 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38233#-LhbmZJG4lVk7dGjDtrs:-LhbmZJH9p8KGF1hBHI1:b4wdzb7) ([raw file](https://github.com/cockroachdb/cockroach/blob/420e0d43a5b6a0b427a9743fe6c3f67913b4bf95/pkg/sql/distsql_running.go#L212)):*
> ```Go
> 			resultChan: resultChan,
> 		}
> 		defer distsqlplan.ReleaseSetupFlowRequest(&req)
> ```

What is the reason for this change (moving the deferral from `run` into `Run`)?
___
*[pkg/sql/distsql_running.go, line 236 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/38233#-LhbnaWH9lLqs4qEGvHQ:-LhbnaWI4fV6ex9sqPD7:b-5n7714) ([raw file](https://github.com/cockroachdb/cockroach/blob/344570696c3b351bc52014cfe65fa66e12864c5a/pkg/sql/distsql_running.go#L236)):*
> ```Go
> 	if firstErr != nil {
> 		if pgErr, ok := pgerror.GetPGCause(firstErr); ok &&
> 			pgErr.Code == pgerror.CodeFeatureNotSupportedError &&
> ```

Do these two conditions uniquely "define" the vectorization setup error?

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38233)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 212 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38233#-LhbmZJG4lVk7dGjDtrs:-LhejoHWBdV_lYfJ19eb:b-i1sokz) ([raw file](https://github.com/cockroachdb/cockroach/blob/420e0d43a5b6a0b427a9743fe6c3f67913b4bf95/pkg/sql/distsql_running.go#L212)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

What is the reason for this change (moving the deferral from `run` into `Run`)?
</blockquote></details>

The release of the `SetupFlowRequest` would zero out the processor specs as soon as the request is sent, so if we would retry, that would result in sending empty processor specs, so we keep them around for longer. This also makes more sense from a general lifecycle perspective, in the sense that whoever created the setup flow request should also release it.
___
*[pkg/sql/distsql_running.go, line 236 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/38233#-LhbnaWH9lLqs4qEGvHQ:-Lhel2yh53IlGrfMmJRy:bbheah8) ([raw file](https://github.com/cockroachdb/cockroach/blob/344570696c3b351bc52014cfe65fa66e12864c5a/pkg/sql/distsql_running.go#L236)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Do these two conditions uniquely "define" the vectorization setup error?
</blockquote></details>

As strictly as possible without introducing a custom error code. All errors from `setupVectorized` are returned as `pgerror.CodeFeatureNotSupported`. This might catch other errors that possibly return with that code in the setup path, but I think it's fine to retry on those as well.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38233)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 236 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/38233#-LhbnaWH9lLqs4qEGvHQ:-Lhkk3iODDX0PBIuuZbe:btw5rwl) ([raw file](https://github.com/cockroachdb/cockroach/blob/344570696c3b351bc52014cfe65fa66e12864c5a/pkg/sql/distsql_running.go#L236)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

As strictly as possible without introducing a custom error code. All errors from `setupVectorized` are returned as `pgerror.CodeFeatureNotSupported`. This might catch other errors that possibly return with that code in the setup path, but I think it's fine to retry on those as well.
</blockquote></details>

Made this stricter using the new error library PTAL

**Review by yuzefovich — APPROVED** [review]
I think Jordan is planning on taking a look shortly, but it :lgtm: 

> Reviewed 4 of 5 files at r1, 1 of 27 files at r9, 3 of 6 files at r10, 4 of 4 files at r11, 4 of 5 files at r12, 6 of 12 files at r13, 3 of 3 files at r14, 2 of 3 files at r15, 4 of 4 files at r16.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38233#-:-LhlIcgZ2JxAoOxy5diC:bw4iqgj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/distsql_running.go, line 212 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38233#-LhbmZJG4lVk7dGjDtrs:-LhkphekD1ZYSTbcMupn:bcr5s31) ([raw file](https://github.com/cockroachdb/cockroach/blob/420e0d43a5b6a0b427a9743fe6c3f67913b4bf95/pkg/sql/distsql_running.go#L212)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

The release of the `SetupFlowRequest` would zero out the processor specs as soon as the request is sent, so if we would retry, that would result in sending empty processor specs, so we keep them around for longer. This also makes more sense from a general lifecycle perspective, in the sense that whoever created the setup flow request should also release it.
</blockquote></details>

Got it, thanks.
___
*[pkg/sql/distsql_running.go, line 236 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/38233#-LhbnaWH9lLqs4qEGvHQ:-Lhkq9N50kHN9mtgHZMw:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/344570696c3b351bc52014cfe65fa66e12864c5a/pkg/sql/distsql_running.go#L236)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Made this stricter using the new error library PTAL
</blockquote></details>

Thanks!
___
*[pkg/sql/logictest/testdata/logic_test/dist_vectorize, line 52 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/38233#-LhlISEYCfpCyZBaEB3N:-LhlISEYCfpCyZBaEB3O:b1coqft) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4a1b3651cf961a31000f7ff08ad9d61a92c48f8/pkg/sql/logictest/testdata/logic_test/dist_vectorize#L52)):*
> ```
> /5         NULL     {5}       5
> 
> # Verify EXPLAIN ANALYZE works in a distributed setting.
> ```

[nit]: "Verify that EXPLAIN ..."

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38233)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/distsql_running.go, line 238 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/38233#-Lho1CHk8x4v0Q9vK5n0:-Lho1CHk8x4v0Q9vK5n1:b-o4k0of) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4a1b3651cf961a31000f7ff08ad9d61a92c48f8/pkg/sql/distsql_running.go#L238)):*
> ```Go
> 	if firstErr != nil {
> 		if _, ok := markers.If(firstErr, func(err error) (v interface{}, ok bool) {
> 			v, ok = err.(*distsqlrun.VectorizedSetupError)
> ```

yep, that's correct!
___
*[pkg/sql/distsql_running.go, line 246 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/38233#-Lho1Xy1Do14OJzbNDG2:-Lho1Xy1Do14OJzbNDG3:bn0nv0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4a1b3651cf961a31000f7ff08ad9d61a92c48f8/pkg/sql/distsql_running.go#L246)):*
> ```Go
> 			newFlowID := uuid.MakeV4()
> 			log.Infof(
> 				ctx, "error vectorizing remote flow %s, restarting with vectorize=off and ID %s: %s", flows[thisNodeID].FlowID, newFlowID, firstErr,
> ```

maybe here you want to format `firstErr` with `%+v` instead of `%s`
___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 939 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/38233#-Lho0mPWCVBeIZZ8L6xx:-Lho0mPWCVBeIZZ8L6xy:b-ixzwbg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4a1b3651cf961a31000f7ff08ad9d61a92c48f8/pkg/sql/distsqlrun/column_exec_setup.go#L939)):*
> ```Go
> }
> 
> func encodeVectorizedSetupError(ctx context.Context, err error) (string, []string, proto.Message) {
> ```

You do not need this function. In fact, it's counterproductive: the library already does this for you, and you doing that here makes the cause be encoded twice.
___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 951 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/38233#-Lho0vOP9exr1KN7Opoq:-Lho0vOP9exr1KN7Opor:b-e5vwkr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4a1b3651cf961a31000f7ff08ad9d61a92c48f8/pkg/sql/distsqlrun/column_exec_setup.go#L951)):*
> ```Go
> 
> func init() {
> 	errors.RegisterWrapperEncoder(errbase.GetTypeKey((*VectorizedSetupError)(nil)), encodeVectorizedSetupError)
> ```

you can remove the register for encode

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38233)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @jordanlewis, @knz, and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 246 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/38233#-Lho1Xy1Do14OJzbNDG2:-Lhqa-Nn0GcsYNQB3MaT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4a1b3651cf961a31000f7ff08ad9d61a92c48f8/pkg/sql/distsql_running.go#L246)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

maybe here you want to format `firstErr` with `%+v` instead of `%s`
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 939 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/38233#-Lho0mPWCVBeIZZ8L6xx:-Lhq_z9OC9EnlKnzilPA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4a1b3651cf961a31000f7ff08ad9d61a92c48f8/pkg/sql/distsqlrun/column_exec_setup.go#L939)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You do not need this function. In fact, it's counterproductive: the library already does this for you, and you doing that here makes the cause be encoded twice.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 951 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/38233#-Lho0vOP9exr1KN7Opoq:-Lhq_zUs-b8TuEh7oHPF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4a1b3651cf961a31000f7ff08ad9d61a92c48f8/pkg/sql/distsqlrun/column_exec_setup.go#L951)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

you can remove the register for encode
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/dist_vectorize, line 52 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/38233#-LhlISEYCfpCyZBaEB3N:-Lhq_OQLAOf3psYNl-T0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4a1b3651cf961a31000f7ff08ad9d61a92c48f8/pkg/sql/logictest/testdata/logic_test/dist_vectorize#L52)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: "Verify that EXPLAIN ..."
</blockquote></details>

Done.

**Review by jordanlewis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38233#-:-Li8m807-O_yraI7F6Rz:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @knz, and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 251 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/38233#-Li8ldoZARtYstUgAtYr:-Li8ldoZARtYstUgAtYs:bb6c2eq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d0d8d95fc2118df3e0a4e2d10287306fd6f4ea7/pkg/sql/distsql_running.go#L251)):*
> ```Go
> 				flows[i].FlowID.UUID = newFlowID
> 			}
> 			evalCtx.SessionData.Vectorize = sessiondata.VectorizeOff
> ```

This seems somewhat suspicious - is it possible that some remote flows would work, but some wouldn't? Would that cause any problems?
___
*[pkg/sql/distsql_running.go, line 253 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/38233#-Li8lmKC7rsPRgNNV_M_:-Li8lmKC7rsPRgNNV_Ma:b-4xay8v) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d0d8d95fc2118df3e0a4e2d10287306fd6f4ea7/pkg/sql/distsql_running.go#L253)):*
> ```Go
> 			evalCtx.SessionData.Vectorize = sessiondata.VectorizeOff
> 			defer func() { evalCtx.SessionData.Vectorize = sessiondata.VectorizeOn }()
> 			goto StartFlows
> ```

Is there a way to avoid this goto? It seems like it would be easy to write a bug in this code, since changes to stack variables down here will be reflected above.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38233)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @jordanlewis, @knz, and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 251 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/38233#-Li8ldoZARtYstUgAtYr:-Li8meRY8B2PZuflqLPF:b69q0ph) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d0d8d95fc2118df3e0a4e2d10287306fd6f4ea7/pkg/sql/distsql_running.go#L251)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This seems somewhat suspicious - is it possible that some remote flows would work, but some wouldn't? Would that cause any problems?
</blockquote></details>

You mean before setting this setting to `VectorizeOff`? It's possible that some remote flows work but some errored out, but we generate a new ID for the flow retry so that flows that succeeded will time out and we won't connect incompatible flows on this retry.
___
*[pkg/sql/distsql_running.go, line 253 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/38233#-Li8lmKC7rsPRgNNV_M_:-Li8nc6F8gDl7NlFM4Z8:bowb7s0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d0d8d95fc2118df3e0a4e2d10287306fd6f4ea7/pkg/sql/distsql_running.go#L253)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Is there a way to avoid this goto? It seems like it would be easy to write a bug in this code, since changes to stack variables down here will be reflected above.
</blockquote></details>

Good point, I think I was just being lazy. Will rework this.

**Comment by asubiotto** [comment]
OK rebased and changed the goto to a recursive function call (factored out part of `Run`). Will merge this tomorrow morning.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38233)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asubiotto, @jordanlewis, @knz, and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 187 at r32](https://reviewable.io/reviews/cockroachdb/cockroach/38233#-LiHMZ4454tyQw44PI8c:-LiHMZ45-fABiahgcSAP:b-6ea68q) ([raw file](https://github.com/cockroachdb/cockroach/blob/22f05a5bc6bafc86af11ae1ae7a7a3aa1229b4d4/pkg/sql/distsql_running.go#L187)):*
> ```Go
> 			}
> 			evalCtx.SessionData.Vectorize = sessiondata.VectorizeOff
> 			ctx, flow, err := dsp.setupFlows(ctx, evalCtx, txnCoordMeta, flows, recv, localState)
> ```

I like this, but please add a comment that spells out the condition that stops the recursion, maybe something like this:

```
// recurse once: this call is under the condition `.Vectorize == VectorizeOn`, so will not be reached the second time.
```

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38233)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asubiotto, @jordanlewis, @knz, and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 187 at r32](https://reviewable.io/reviews/cockroachdb/cockroach/38233#-LiHMZ4454tyQw44PI8c:-LiJ1mI41aa424Fbhcsw:boyexb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/22f05a5bc6bafc86af11ae1ae7a7a3aa1229b4d4/pkg/sql/distsql_running.go#L187)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I like this, but please add a comment that spells out the condition that stops the recursion, maybe something like this:

```
// recurse once: this call is under the condition `.Vectorize == VectorizeOn`, so will not be reached the second time.
```

</blockquote></details>

Done. Thanks!

**Comment by asubiotto** [comment]
bors r=yuzefovich,jordanlewis

**Comment by asubiotto** [comment]
Looks like a flake

bors r=yuzefovich,jordanlewis

**Comment by asubiotto** [comment]
Looks like something is going on: `Canceled with comment: Build agent shutdown`

**Comment by asubiotto** [comment]
I guess I'll try again
bors r=yuzefovich,jordanlewis

**Comment by asubiotto** [comment]
Latest failure was actual test failure. Fixed and retrying.

bors r=yuzefovich,jordanlewis

**Pull request merged**
