### PR TITLE
kv: check for 1-phase commit after request, not before

### PR DESCRIPTION
**Pull request by nvb**
Found while verifying that #40518 didn't negatively impact YCSB performance.
As it turns out, most txns that restart hit the check in DistSender instead,
and that ends up being critical for forward progress. Without it, transactions
appear to starve because they never write intents.

The commit doesn't make any changes there, but it does fix an issue where
1PC transactions were being incorrectly detected. The detection was ignoring
the fact that a 1PC attempt could be rejected by DistSender or a Replica.
We now tie the metric to whether an EndTransaction actually evaluated as
a 1PC txn instead of tying it to whether the EndTransaction _wanted_ to
be evaluated as a 1PC txn.

Release justification: low risk and improves metric reporting

Release note: None

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
I stared at this a bunch but still not sure I got it right. The previous code counted 1PC attempts instead of successes? I know that DistSender will prevent 1PC when the epoch is not zero any more. Are you saying that without that behavior there's starvation? Shouldn't the 1PC attempt at the replica also lay down an intent if it doesn't go through?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41104#-:-LphsqnD-QCChNNjx9rl:b-fxeqoq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

**Review by andreimatei — COMMENTED** [review]
LGTM

Tobi, this PR is strictly for the 1PC metric. Before the patch, we'd count 1pc attempts, with the patch we count 1pc successes.

Nathan, it does appear that that commit message could be improved :P

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41104#-:-Lpi2Y0-0OFXO-Fzsxov:b-4hs2fv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

**Comment by nvanbenschoten** [comment]
> Nathan, it does appear that that commit message could be improved :P

Ah yes, you're right. I guess I still had the experiment on my mind and didn't realize I had failed to mention what the PR was actually changing. Updated.

**Pull request merged**
