### PR TITLE
kvserver: add AdminSplit and AdminScatter to secondary tenants API

### LINKED ISSUE #74389: kv: Add API to allow for split/scatter behavior in multi-tenant environments
Bulk jobs currently send AdminSplit and AdminScatter requests to KV when it thinks it has sent a lot of data to one range, before it keeps sending, to give kv a chance to make a new empty range and move it somewhere. Perhaps most importantly, it gives kv a chance to split that new range off and move it to a new node before the bulk job proceeds to go and send it a bunch more data, that would then all need to be rebalanced over if we instead waited for the range / allocator to decide it is over-full and split and move on its own. If we can get it split and moved before we fill it, it's much cheaper.

_But_ we don't do any of this when a tenant is the one generating and sending data. Of course, deciding a range is too full and should be split, or a node has too much on it and should rebalance replicas away, is obviously kv/allocator work, but the bulk job has information that the range and allocator doesn't here, which is that it is going to be sending more data so it might be advantageous to split and rebalance it now, while it is cheap.

One idea that was proposed was to create an advisory request that bulk could send to KV to indicate when a proactive split may be beneficial.  The thinking is that if bulk could send some indication that it's about to send a large number of sequential keys to a given sst, KV could use that info to determine if/when to split.  See parent Epic for the full discussion.

Initially, for 22.1, however we want to just open the existing AdminSplit and AdminScatter APIs to tenants, while still blocking them at the SQL statement level, and add monitoring on number of spans per tenant, so existing code will work with party between tenant and dedicated clusters.

Epic: CRDB-10720

### PR DESCRIPTION
**Pull request by shralex**
This adds support for AdminSplit and AdminScatter for secondary tenants. This API allows indicating to KV that more data will be ingested, and so the range should be split and re-distributed across the cluster. This API will not be exposed through SQL, and in the future we might change it to give KV more control over whether and how to deal with expected ingest load. More discussion can be found in the github issue: https://github.com/cockroachdb/cockroach/issues/74389 and Epic: https://cockroachlabs.atlassian.net/browse/CRDB-10720

Release Note: None

### CODE REVIEW

**Review by ajstorm — COMMENTED** [review]
:tada: thanks for getting to this so quickly.

Do we have a test we need to update to validate this behavior?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74835#-:-MtNqBISDQf_yNEv7LgT:b-rm778c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, and @shralex)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74835#-MtNqJAF8JyjKnHUMsLw):*
Might be good to give a bit more context as to why we're making this change.  The context from https://github.com/cockroachdb/cockroach/issues/74389 might help.  Also, can you link this epic to that issue (but maybe informs and not resolves)?

**Review by shralex — COMMENTED** [review]
Updated now, thank you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74835#-:-MtZEDUh5n8hWfdAjSLo:b-gs6g08)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, and @shralex)

**Review by ajstorm — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74835#-:-MtcLYee5L5W71-S9oot:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, and @shralex)

**Review by ajstorm — COMMENTED** [review]
Might be good to get someone from KV to quickly double check though.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74835#-:-MtcLiJh7uhEcDEgV4Jm:b-m5dqq9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, and @shralex)

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74835)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @shralex)

___
*[-- commits, line 13 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74835#-MtjIPVD6fth9GJiL6vs):*
nit: extra release note.
___
*[pkg/rpc/auth_test.go, line 252 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74835#-Mtj55G43opj7Va1Bh5M:-Mtj55G43opj7Va1Bh5N:bs81ik5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fdfc8fcb6f48c3a733e43ed94f9751065bf60fd/pkg/rpc/auth_test.go#L252)):*
> ```Go
> 			{
> 				req: &roachpb.BatchRequest{Requests: makeReqs(
> 					makeAdminReq("a"),
> ```

These test cases were meant to represent an arbitrary unsupported admin operation — not a split in particular. Let's change `makeAdminReq` so that it doesn't perform an `AdminSplit` and instead performs an admin operation that still isn't permitted, like `AdminRelocateRange`. Then we can add additional test cases for `AdminSplit` and `AdminScatter`.

**Review by shralex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74835)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @ajstorm, @nvanbenschoten, and @shralex)

___
*[pkg/rpc/auth_test.go, line 252 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74835#-Mtj55G43opj7Va1Bh5M:-MtjcS7vAI7xaCu4O9oS:brq7egs) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fdfc8fcb6f48c3a733e43ed94f9751065bf60fd/pkg/rpc/auth_test.go#L252)):*
> AdminRelocateRange
Done

**Review by shralex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74835)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @ajstorm, @nvanbenschoten, and @shralex)

___
*[-- commits, line 13 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74835#-MtjIPVD6fth9GJiL6vs):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: extra release note.
</blockquote></details>

Done

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74835#-:-MtnROsC91UEaqdHWoca:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15 and @shralex)

**Pull request merged**
