### PR TITLE
workload/schemachange: create function could have invalid invocations

### LINKED ISSUE #131502: roachtest: schemachange/random-load failed [return type mismatch in function declared to return table_w16_201]
roachtest.schemachange/random-load [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17061021?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17061021?buildTab=artifacts#/schemachange/random-load) on release-24.1 @ [627d811b9a7e72e47cff241db14ba89297388552](https://github.com/cockroachdb/cockroach/commits/627d811b9a7e72e47cff241db14ba89297388552):

```
(schemachange_random_load.go:123).runSchemaChangeRandomLoad: full command output in run_121340.487818004_n1_workload-run-schemac.log: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/schemachange/random-load/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-17061021/schemachange-random-load/1727439190066/1727439787655)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #131405 roachtest: schemachange/random-load failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-release-23.2 release-blocker]
- #131345 roachtest: schemachange/random-load failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-master release-blocker]
- #129857 roachtest: schemachange/random-load failed [relation &#34;[1285]&#34; does not exist] [C-test-failure O-roachtest O-robot P-2 T-sql-foundations branch-release-24.2.1-rc]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/random-load.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-42578

### PR DESCRIPTION
**Pull request by fqazi**
Previously, when creating functions inside the schema changer workload, it was possible for these functions to have the return type of a table record. This meant the return type was linked to the schema of a table. If the table was modified with an ALTER TABLE command, then these functions will no longer be invokable. When generating function invocations we also added the ability to add function references, and it was possible to select functions which were no longer invokable after an ALTER as a side effect. To address this, this patch adds InvalidFunctionDefinition as a possibility if we decide to invoke user defined functions in the body of any new functions that we create.

Fixes: #131502

Release note: None

### CODE REVIEW

**Review by spilchen — APPROVED** [review]
LGTM! Just a minor nit—feel free to ignore if you'd like.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133676#-:-OAOOj5390NB3patm_p_:b-1rg5vw)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @fqazi, and @herkolategan)

___
*[`pkg/workload/schemachange/operation_generator.go` line 4259 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133676#-OAOO4Ve1KcrnRYfRXLc:-OAOO4Ve1KcrnRYfRXLd:bqx6b9z) ([raw file](https://github.com/cockroachdb/cockroach/blob/8708c4552f193551a1ceca27d02e610b12043b58/pkg/workload/schemachange/operation_generator.go#L4259)):*
> ```Go
> 			hasFuncRefs = len(funcRefs) > 0
> 			refs = append(refs, funcRefs...)
> 			err = errors.CombineErrors(err, secondErr)
> ```

nit: we don't need to do anything if `requiredFuncRefs` is 0. Maybe suggest something like this to make it easier to read.



_Suggestion:_
```Go
			if len(refs) == 0 {
				funcRefs, secondErr := PickAtLeast(og.params.rng, 1, possibleBodyFuncReferences)
				err = errors.CombineErrors(err, secondErr)
				hasFuncRefs = len(funcRefs) > 0
				refs = append(refs, funcRefs...)
			}
```

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133676)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @herkolategan, and @spilchen)

___
*[`pkg/workload/schemachange/operation_generator.go` line 4259 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133676#-OAOO4Ve1KcrnRYfRXLc:-OAOygWqCTNDri-q6WfM:b-47g3qu) ([raw file](https://github.com/cockroachdb/cockroach/blob/8708c4552f193551a1ceca27d02e610b12043b58/pkg/workload/schemachange/operation_generator.go#L4259)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

nit: we don't need to do anything if `requiredFuncRefs` is 0. Maybe suggest something like this to make it easier to read.
</blockquote></details>

I tweaked this a bit. I noticed my logic was sort of bad since function references may not exist.

**Review by spilchen — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133676#-:-OAS7QP_Es64TtTm_ScV:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong and @herkolategan)

**Comment by fqazi** [comment]
@spilchen TFTR!

bors r+

**Comment by fqazi** [comment]
blathers backport 24.1

**Pull request merged**
