### PR TITLE
pgwire: fix flaky test

### LINKED ISSUE #33422: pgwire: TestPGWireDrainOngoingTxns flaky
```
make stress PKG='./pkg/sql/pgwire' TESTS=TestPGWireDrainOngoingTxns/CancelResponseSuccess

--- FAIL: TestPGWireDrainOngoingTxns (1.37s)
    --- FAIL: TestPGWireDrainOngoingTxns/CancelResponseSuccess (1.00s)
    	pgwire_test.go:381: unexpected error: read tcp 127.0.0.1:56437->127.0.0.1:56421: read: connection reset by peer
FAIL


ERROR: exit status 1

4 runs completed, 1 failures, over 1s
```

### PR DESCRIPTION
**Pull request by jordanlewis**
Closes #33422.

Release note: None
Release justification: test only change

### CODE REVIEW

**Review by andreimatei — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40979)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @asubiotto, and @jordanlewis)

___
*[pkg/sql/pgwire/pgwire_test.go, line 366 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40979#-LpU2Kha2jpJ-5LlI8DR:-LpU2Kha2jpJ-5LlI8DS:blnckfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41ef18480b77a63467e5af42d1840a9cc8cde00/pkg/sql/pgwire/pgwire_test.go#L366)):*
> ```Go
> 		}
> 
> 		// Set draining with no drainWait timeout and a 1s cancelWait timeout.
> ```

comment says 1s, code says 2. Pls take the opportunity to fix it.
___
*[pkg/sql/pgwire/pgwire_test.go, line 375 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40979#-LpU1V4_DNrNlTDZ_hra:-LpU1V4_DNrNlTDZ_hrb:b-dcrvil) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41ef18480b77a63467e5af42d1840a9cc8cde00/pkg/sql/pgwire/pgwire_test.go#L375)):*
> ```Go
> 		}
> 
> 		if err := txn.Commit(); err == nil || (err != driver.ErrBadConn && !strings.Contains(err.Error(), "connection reset by peer")) {
> ```

long line
___
*[pkg/sql/pgwire/pgwire_test.go, line 375 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40979#-LpU2Oi_BczKFElLo9jC:-LpU2Oi_BczKFElLo9jD:b-cv5eif) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41ef18480b77a63467e5af42d1840a9cc8cde00/pkg/sql/pgwire/pgwire_test.go#L375)):*
> ```Go
> 		}
> 
> 		if err := txn.Commit(); err == nil || (err != driver.ErrBadConn && !strings.Contains(err.Error(), "connection reset by peer")) {
> ```

What's going on here? Why are we expecting a nil error here? Or rather why is the error sometimes not? Sounds to me like we want to add some more synchronization. The test says that we're expecting the connection to " correctly respond to this
cancellation by closing itself."
So I think we shouldn't be expecting no error, and also it'd be nice to explain why there's two possible errors (presumably depending on how the driver finds out about the server having closed the connection?).

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40979)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @asubiotto)

___
*[pkg/sql/pgwire/pgwire_test.go, line 366 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40979#-LpU2Kha2jpJ-5LlI8DR:-LpUq8M58vti5i3cK75y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41ef18480b77a63467e5af42d1840a9cc8cde00/pkg/sql/pgwire/pgwire_test.go#L366)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

comment says 1s, code says 2. Pls take the opportunity to fix it.
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/pgwire_test.go, line 375 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40979#-LpU2Oi_BczKFElLo9jC:-LpUq2sX53o25Hitgzfb:b9x458s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41ef18480b77a63467e5af42d1840a9cc8cde00/pkg/sql/pgwire/pgwire_test.go#L375)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

What's going on here? Why are we expecting a nil error here? Or rather why is the error sometimes not? Sounds to me like we want to add some more synchronization. The test says that we're expecting the connection to " correctly respond to this
cancellation by closing itself."
So I think we shouldn't be expecting no error, and also it'd be nice to explain why there's two possible errors (presumably depending on how the driver finds out about the server having closed the connection?).
</blockquote></details>

We're not expecting a nil error - we're expecting the opposite. We expect either ErrBaddConn or connection reset by peer. I think it's expected.
___
*[pkg/sql/pgwire/pgwire_test.go, line 375 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40979#-LpU1V4_DNrNlTDZ_hra:-LpUq8-NAvlcp1NapcYA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41ef18480b77a63467e5af42d1840a9cc8cde00/pkg/sql/pgwire/pgwire_test.go#L375)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

long line
</blockquote></details>

Done.

**Review by andreimatei — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40979#-:-LpV2CXa4JY0x87613Ed:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @asubiotto, and @jordanlewis)

___
*[pkg/sql/pgwire/pgwire_test.go, line 375 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40979#-LpU2Oi_BczKFElLo9jC:-LpV25Bz-e8hoeveFZmm:b-mxjkt1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41ef18480b77a63467e5af42d1840a9cc8cde00/pkg/sql/pgwire/pgwire_test.go#L375)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

We're not expecting a nil error - we're expecting the opposite. We expect either ErrBaddConn or connection reset by peer. I think it's expected.
</blockquote></details>

oh sorry misread it.

**Pull request merged**
