### PR TITLE
spanconfigreconciler{ccl}: apply system span config diffs to the store

### PR DESCRIPTION
**Pull request by adityamaru**
This change teaches the reconciler about system span configs. Concretely,
we make the following changes:

- A full reconciliation when checking for existing span configurations now
asks for SpanConfigs corresponding to the SystemTargets relevant to the tenant.

For the host tenant this includes the SystemTarget for the `entire-keyspace` as
well as the SystemTarget for span configs installed by the host tenant on its
tenant keyspace, and on other secondary tenant keyspaces.

For secondary tenants this only includes the SystemTarget for span configs installed
by it on its own tenant keyspace.

- During incremental reconciliation, before applying our updates to the Store,
we now also check for "missing protected timestamp system targets". These correspond
to protected timestamp records that target a `Cluster` or a `Tenant` but no longer
exist in the system.protected_ts_records table as they have been released by the client.
For every such unique missing system target we apply a spanconfig.Deletion to the Store.

In order to make the above possible, this change moves the ptsStateReader from the
`spanconfigsqltranslator` package, to the top level `spanconfig` package.

Informs: #73727

Release note: None

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
This should be good to go once we've enhanced the datadriven tests to let secondary tenants set PTS records on their "logical" cluster as well. Exciting to see this entire thing so close to being wired up end to end! 

> Reviewed 17 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76948#-:-MwgpEgl7c6Kh1Ufk7cc:bg66zfg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @irfansharif)

___
*[pkg/ccl/spanconfigccl/spanconfigreconcilerccl/testdata/protectedts, line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76948#-MwgmmCO4UII941UvT1V:-MwgmmCO4UII941UvT1W:b6ja89g) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b7d2e5ab3caed57029a64f4c85e07a0d206c7d6/pkg/ccl/spanconfigccl/spanconfigreconcilerccl/testdata/protectedts#L15)):*
> ```
> ----
> 
> mutations
> ```

nit: you could reconcile, discard mutations, and then do the protection you do above to make this a bit more readable. 
___
*[pkg/ccl/spanconfigccl/spanconfigreconcilerccl/testdata/protectedts, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76948#-MwgnCmz8RcOvMyiKd8B:-MwgnCmz8RcOvMyiKd8C:bs8i1sq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b7d2e5ab3caed57029a64f4c85e07a0d206c7d6/pkg/ccl/spanconfigccl/spanconfigreconcilerccl/testdata/protectedts#L128)):*
> ```
> release record-id=5
> ----
> ```

nit: Let's print out the mutations here as well before releasing record-id=1?
___
*[pkg/ccl/spanconfigccl/spanconfigreconcilerccl/testdata/multitenant/protectedts, line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76948#-MwgoB-kEHFfLS7JW6eg:-MwgoB-kEHFfLS7JW6eh:b1id6qq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b7d2e5ab3caed57029a64f4c85e07a0d206c7d6/pkg/ccl/spanconfigccl/spanconfigreconcilerccl/testdata/multitenant/protectedts#L116)):*
> ```
> ...
> 
> # Release all the protected timestamp records from the host tenant.
> ```

In addition to setting/releasing records from the host tenant, we should extend this test to do so as a tenant as well. How about adding an optional `tenant` arg to both protect and release? 
___
*[pkg/ccl/spanconfigccl/spanconfigreconcilerccl/datadriven_test.go, line 219 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76948#-MwgotQtBaZLcrDSmy0J:-MwgotQtBaZLcrDSmy0K:b-ofqjq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b7d2e5ab3caed57029a64f4c85e07a0d206c7d6/pkg/ccl/spanconfigccl/spanconfigreconcilerccl/datadriven_test.go#L219)):*
> ```Go
> 				return spanconfigtestutils.MaybeLimitAndOffset(t, d, "...", lines)
> 
> 			case "protect":
> ```

nit: we should add this thing to the comment explaining the datadriven language above as well. 
___
*[pkg/spanconfig/protectedts_state_reader.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76948#-MwgjmtQ0A--VdOaWRJy:-MwgjmtRDlU13QMwzfp-:bl08qej) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b7d2e5ab3caed57029a64f4c85e07a0d206c7d6/pkg/spanconfig/protectedts_state_reader.go#L78)):*
> ```Go
> // GetProtectionPoliciesForTenant returns all the protected timestamps that
> // apply to a particular tenant's keyspace.
> func (p *ProtectedTimestampStateReader) GetProtectionPoliciesForTenant(
> ```

Looks like we usage of this is of the form `if len(GetProtectionPolicies) == 0` -- consider changing this thing to something like `ProtectionExistsForTenant(roachpb.TenantID) bool`

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76948)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @irfansharif)

___
*[pkg/ccl/spanconfigccl/spanconfigreconcilerccl/testdata/protectedts, line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76948#-MwgmmCO4UII941UvT1V:-MwhKVip1ZkZl9FPkC0D:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b7d2e5ab3caed57029a64f4c85e07a0d206c7d6/pkg/ccl/spanconfigccl/spanconfigreconcilerccl/testdata/protectedts#L15)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: you could reconcile, discard mutations, and then do the protection you do above to make this a bit more readable. 
</blockquote></details>

Good point, done.
___
*[pkg/ccl/spanconfigccl/spanconfigreconcilerccl/testdata/protectedts, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76948#-MwgnCmz8RcOvMyiKd8B:-MwhK8R25P494FhyP16M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b7d2e5ab3caed57029a64f4c85e07a0d206c7d6/pkg/ccl/spanconfigccl/spanconfigreconcilerccl/testdata/protectedts#L128)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: Let's print out the mutations here as well before releasing record-id=1?
</blockquote></details>

Done.
___
*[pkg/ccl/spanconfigccl/spanconfigreconcilerccl/testdata/multitenant/protectedts, line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76948#-MwgoB-kEHFfLS7JW6eg:-MwhQRDoEovQDGh6Y0H0:b5jt7y6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b7d2e5ab3caed57029a64f4c85e07a0d206c7d6/pkg/ccl/spanconfigccl/spanconfigreconcilerccl/testdata/multitenant/protectedts#L116)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

In addition to setting/releasing records from the host tenant, we should extend this test to do so as a tenant as well. How about adding an optional `tenant` arg to both protect and release? 
</blockquote></details>

I have some of these tests in `multitenant/protectedts`. Let me know if it's missing something we should test.
___
*[pkg/ccl/spanconfigccl/spanconfigreconcilerccl/datadriven_test.go, line 219 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76948#-MwgotQtBaZLcrDSmy0J:-MwhKBa1CQzwkmWAs2JR:b-48vilg) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b7d2e5ab3caed57029a64f4c85e07a0d206c7d6/pkg/ccl/spanconfigccl/spanconfigreconcilerccl/datadriven_test.go#L219)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: we should add this thing to the comment explaining the datadriven language above as well. 
</blockquote></details>

Good call, done.
___
*[pkg/spanconfig/protectedts_state_reader.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76948#-MwgjmtQ0A--VdOaWRJy:-MwhK0aaDqF7mProE6CQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b7d2e5ab3caed57029a64f4c85e07a0d206c7d6/pkg/spanconfig/protectedts_state_reader.go#L78)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Looks like we usage of this is of the form `if len(GetProtectionPolicies) == 0` -- consider changing this thing to something like `ProtectionExistsForTenant(roachpb.TenantID) bool`
</blockquote></details>

Done.

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76948#-:-Mwhn4AH0QVL8SH0bOWG:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @arulajmani, and @irfansharif)

___
*[pkg/ccl/spanconfigccl/spanconfigreconcilerccl/testdata/multitenant/protectedts, line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76948#-MwgoB-kEHFfLS7JW6eg:-MwhmwWk2nopAxcDjafF:bofs9q5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b7d2e5ab3caed57029a64f4c85e07a0d206c7d6/pkg/ccl/spanconfigccl/spanconfigreconcilerccl/testdata/multitenant/protectedts#L116)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

I have some of these tests in `multitenant/protectedts`. Let me know if it's missing something we should test.
</blockquote></details>

Na, I think I just missed the snippet; my bad.

**Comment by adityamaru** [comment]
bors r=arulajmani

**Comment by adityamaru** [comment]
Filed https://github.com/cockroachdb/cockroach/issues/77046 for the unrelated flake, tried re-running twice so im inclined to bors this once bazel CI finishes. I'll independently skip the flakey test.

**Comment by adityamaru** [comment]
Both flakes are known issues.

bors r=arulajmani

**Pull request merged**
