### PR TITLE
sql: make SET and SET CLUSTER SETTING support the prepare protocol

### LINKED ISSUE #17563: sql: SET does not support placeholders
```
error executing 'SET CLUSTER SETTING enterprise.license = $1': pq: got 1 parameters but the statement requires 0
```

@knz says:

> it's because Set does not currently implement the prepare protocol
> `plan.go` function `prepare()`
> (if you do not move the logic from the planNode constructror to a Start() method, then the SET will take effect as soon as the PREPARE is run, which is most definitely not correct)
> the constructor needs to type check yes
> but the logic that effects the change must migrate to Start()

Assigning to @knz for triage.

### PR DESCRIPTION
**Pull request by knz**
This patch ensures that a client can use placeholders in the value
field of SET and SET CLUSTER SETTING statements.

For example:

```sql
PREPARE lateset(string) AS SET application_name = $1
EXECUTE lateset('myapp')
```

And there was much rejoicing!

As a side effect of supporting this, these two statements now also
support values defined by subqueries. For example:

```sql
SET application_name = (SELECT 'my' || 'app')
```

Note: this patch does *not* support placeholders on the LHS of the
assignment. This is because the type required for the RHS depends on
the value of the LHS (which setting is being modified). This is the
same reason why we do not currently support placeholders for table
names in INSERT, etc.

Fixes #17563.
Informs #8270.

cc @benesch @dt.

### CODE REVIEW

**Comment by tschottdorf** [comment]
FWIW, I've been wanting this a few times in the last few days, but it doesn't technically block me. I'm leaving a few TODOs in the code linking to this PR in the meantime, perhaps we can remember to grep for those when this merges.

**Comment by knz** [comment]
@tschottdorf I found your TODO and fixed it.

**Comment by knz** [comment]
@a-robinson @dt can you have a look a this in the light of  #17866 thanks

**Comment by a-robinson** [comment]
It looks like this gels alright with #17866. I tried patching it on top of this and it still has its intended effect.

```
diff --git a/pkg/sql/parser/constant.go b/pkg/sql/parser/constant.go
index 8f992bb08..36834835d 100644
--- a/pkg/sql/parser/constant.go
+++ b/pkg/sql/parser/constant.go
@@ -358,7 +358,7 @@ func (expr *StrVal) Format(buf *bytes.Buffer, f FmtFlags) {
 	if expr.bytesEsc {
 		encodeSQLBytes(buf, expr.s)
 	} else {
-		encodeSQLString(buf, expr.s)
+		encodeSQLStringWithFlags(buf, expr.s, f)
 	}
 }

diff --git a/pkg/sql/parser/format_test.go b/pkg/sql/parser/format_test.go
index b574c4c44..b1a7eeadb 100644
--- a/pkg/sql/parser/format_test.go
+++ b/pkg/sql/parser/format_test.go
@@ -96,6 +96,8 @@ func TestFormatStatement(t *testing.T) {
 			`SET "time zone" = utc`},
 		{`SET "time zone" = UTC`, FmtBareIdentifiers,
 			`SET time zone = utc`},
+		{`SET "time zone" = UTC`, FmtBareStrings,
+			`SET "time zone" = utc`},
 	}

 	for i, test := range testData {
diff --git a/pkg/sql/set.go b/pkg/sql/set.go
index 8dc377cc7..304cdfdb0 100644
--- a/pkg/sql/set.go
+++ b/pkg/sql/set.go
@@ -15,6 +15,7 @@
 package sql

 import (
+	"bytes"
 	"fmt"
 	"strings"
 	"time"
@@ -174,14 +175,17 @@ func (n *setClusterSettingNode) Start(params runParams) error {

 	var reportedValue string
 	if n.value == nil {
+		reportedValue = "DEFAULT"
 		if _, err := ie.ExecuteStatementInTransaction(
 			params.ctx, "reset-setting", params.p.txn,
 			"DELETE FROM system.settings WHERE name = $1", n.name,
 		); err != nil {
 			return err
 		}
-		reportedValue = "DEFAULT"
 	} else {
+		var buf bytes.Buffer
+		v[0].Format(&buf, parser.FmtBareStrings)
+		reportedValue = buf.String()
 		// TODO(dt): validate and properly encode str according to type.
 		encoded, err := params.p.toSettingString(params.ctx, ie, n.name, n.setting, n.value)
 		if err != nil {
@@ -195,7 +199,6 @@ func (n *setClusterSettingNode) Start(params runParams) error {
 		); err != nil {
 			return err
 		}
-		reportedValue = encoded
 	}

 	return MakeEventLogger(params.p.LeaseMgr()).InsertEventRecord(
```

**Comment by knz** [comment]
Justin I would welcome your review while Jordan is away.

**Comment by justinj** [comment]
Review status: 0 of 34 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/set.go, line 56 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17591#-KsjBfM7ySEkZJSfCg18:-KsjBfM7ySEkZJSfCg19:beejuqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/225abc84466ef564e3fd91fa7c84f9573da6c2c2/pkg/sql/set.go#L56)):*
> ```Go
> 	if len(n.Values) > 0 {
> 		// SET var = DEFAULT is really a RESET in disguise.
> 		if _, ok := n.Values[0].(parser.DefaultVal); !ok || len(n.Values) > 1 {
> ```

Consider expanding in this comment, or setting a flag maybe? It wasn't clear to me immediately how we'd handle this RESET in disguise, and the fact that we detect a reset by `typedValues` being nil feels a little ad-hoc to me?

---

*[pkg/sql/set.go, line 109 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17591#-KsjDN-ZaFEo0LiGX9g7:-KsjDN-ZaFEo0LiGX9g8:b9gzmrm) ([raw file](https://github.com/cockroachdb/cockroach/blob/225abc84466ef564e3fd91fa7c84f9573da6c2c2/pkg/sql/set.go#L109)):*
> ```Go
> 	name    string
> 	setting settings.Setting
> 	// if value is nil, the setting should be reset.
> ```

nit: capitalize `i`?

---

*[pkg/sql/set.go, line 225 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17591#-KsjHxWN_A1CPm0XYK2Y:-KsjHxWN_A1CPm0XYK2Z:bq8338l) ([raw file](https://github.com/cockroachdb/cockroach/blob/225abc84466ef564e3fd91fa7c84f9573da6c2c2/pkg/sql/set.go#L225)):*
> ```Go
> 	val parser.TypedExpr,
> ) (string, error) {
> 	d, err := val.Eval(&p.evalCtx)
> ```

:thumbsup: i like the change to this function a lot.

---

*[pkg/sql/walk.go, line 383 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17591#-KsjIQILYLlPbO714G0q:-KsjIQILYLlPbO714G0r:b-fujuko) ([raw file](https://github.com/cockroachdb/cockroach/blob/225abc84466ef564e3fd91fa7c84f9573da6c2c2/pkg/sql/walk.go#L383)):*
> ```Go
> 
> 	case *setClusterSettingNode:
> 		if n.value != nil {
> ```

I really wish Go had sum types so the `RESET` case could be given a better name than `nil` :cry: 

---

*[pkg/sql/logictest/testdata/logic_test/prepare, line 284 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17591#-KsjF9pcTCShe_KgaT3O:-KsjF9pcTCShe_KgaT3P:b-92igia) ([raw file](https://github.com/cockroachdb/cockroach/blob/225abc84466ef564e3fd91fa7c84f9573da6c2c2/pkg/sql/logictest/testdata/logic_test/prepare#L284)):*
> ```
> 
> statement
> PREPARE SETs(string) AS SET CLUSTER SETTING cluster.organization = $1
> ```

any reason this is capitalized differently than the other prepares?

---

*[pkg/sql/parser/parse_test.go, line 895 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17591#-KsjFiptzxw0EQNCNiOF:-KsjFiptzxw0EQNCNiOG:b-9pobis) ([raw file](https://github.com/cockroachdb/cockroach/blob/225abc84466ef564e3fd91fa7c84f9573da6c2c2/pkg/sql/parser/parse_test.go#L895)):*
> ```Go
> 			`SET "time zone" = -7.3`},
> 		{`SET TIME ZONE DEFAULT`,
> 			`SET "time zone" = DEFAULT`},
> ```

should we add a test for `= DEFAULT` as input as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17591)*

**Comment by knz** [comment]
Review status: 0 of 34 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/sql/set.go, line 56 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17591#-KsjBfM7ySEkZJSfCg18:-KsjeCd9yY3zhFRXqTdV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/225abc84466ef564e3fd91fa7c84f9573da6c2c2/pkg/sql/set.go#L56)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Consider expanding in this comment, or setting a flag maybe? It wasn't clear to me immediately how we'd handle this RESET in disguise, and the fact that we detect a reset by `typedValues` being nil feels a little ad-hoc to me?
</blockquote></details>

Done.

---

*[pkg/sql/set.go, line 109 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17591#-KsjDN-ZaFEo0LiGX9g7:-KsjeGRIWw2FnI28sJ7r:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/225abc84466ef564e3fd91fa7c84f9573da6c2c2/pkg/sql/set.go#L109)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nit: capitalize `i`?
</blockquote></details>

Done.

---

*[pkg/sql/logictest/testdata/logic_test/prepare, line 284 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17591#-KsjF9pcTCShe_KgaT3O:-KsjeTQXLCx34Sskfu51:blfug0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/225abc84466ef564e3fd91fa7c84f9573da6c2c2/pkg/sql/logictest/testdata/logic_test/prepare#L284)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

any reason this is capitalized differently than the other prepares?
</blockquote></details>

No reason. Fixed.

---

*[pkg/sql/parser/parse_test.go, line 895 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17591#-KsjFiptzxw0EQNCNiOF:-KsjehArjVJLy4ClbuG5:bni2v0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/225abc84466ef564e3fd91fa7c84f9573da6c2c2/pkg/sql/parser/parse_test.go#L895)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

should we add a test for `= DEFAULT` as input as well?
</blockquote></details>

Added here. There's already a test for = DEFAULT in the logic tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17591)*

**Comment by justinj** [comment]
:lgtm:

---

Reviewed 5 of 34 files at r1, 6 of 11 files at r2.
Review status: 11 of 34 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17591#-:-KsjhwFLiuz1SSEVMuIR:bnfp4nl)*

**Comment by knz** [comment]
TFYR!

**Pull request merged**
