### PR TITLE
Ignore generated protos in diffs

### PR DESCRIPTION
**Pull request by tbg**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7110)

### CODE REVIEW

**Comment by tamird** [comment]
what's the difference between this and `binary`?

**Comment by tschottdorf** [comment]
I suppose that `binary` involves more special treatment, but I haven't looked closely since the generated protos aren't binary.

Excerpt from [the docs](https://git-scm.com/docs/gitattributes) below:

Git usually guesses correctly whether a blob contains text or binary data by examining the beginning of the contents. However, sometimes you may want to override its decision, either because a blob contains binary data later in the file, or because the content, while technically composed of text characters, is opaque to a human reader. For example, many postscript files contain only ASCII characters, but produce noisy and meaningless diffs.

The simplest way to mark a file as binary is to unset the diff attribute in the .gitattributes file:

*.ps -diff
This will cause Git to generate Binary files differ (or a binary patch, if binary patches are enabled) instead of a regular diff.

However, one may also want to specify other diff driver attributes. For example, you might want to use textconv to convert postscript files to an ASCII representation for human viewing, but otherwise treat them as binary files. You cannot specify both -diff and diff=ps attributes. The solution is to use the diff.*.binary config option:

**Comment by tamird** [comment]
I see. Seems like embedded.go and sql.go aren't binary either.

LGTM

**Comment by tamird** [comment]
LGTM

**Comment by dt** [comment]
I think we want `-merge` too if we're not going to use the `binary` macro, no?

(also, why don't we like the `binary` macro anymore?)

**Comment by dt** [comment]
also, last time I proposed the change merged in this PR, @bdarnell said:
> The diffs in *.pb.* files are relatively legible and a standard merge has a decent chance of doing the right thing, so I'd leave those alone (we have the circleci check to catch any bad merges there).

**Comment by tamird** [comment]
Isn't that a reason to not use -merge, then?

**Comment by tschottdorf** [comment]
I'm happy using any other modifiers that seem more appropriate, but I don't
want to see my proto changes when I review my PRs before sending them up.
That seems unnecessary.

On Thu, Jun 9, 2016 at 8:58 PM Tamir Duberstein <notifications@github.com>
wrote:

> Isn't that a reason to not use -merge, then?
> On Jun 9, 2016 20:43, "David Taylor" <notifications@github.com> wrote:
>
> > also, last time I proposed the change merged in this PR, @bdarnell
> > <https://github.com/bdarnell> said:
> >
> > The diffs in *.pb.* files are relatively legible and a standard merge has
> > a decent chance of doing the right thing, so I'd leave those alone (we
> have
> > the circleci check to catch any bad merges there).
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/cockroachdb/cockroach/pull/7110#issuecomment-225066920
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ABdsPJidmAEDZ-x567v6TLuDqKqqX6pgks5qKLNCgaJpZM4IxSjb
> >
> > .
> >
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/7110#issuecomment-225068737>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135JRhP_v4HeUVvolzIveN4QVuWjU5ks5qKLa3gaJpZM4IxSjb>
> .
>
-- 

-- Tobias

**Comment by dt** [comment]
IMO we should be using `-merge` on all generated files, since the "correct" merge handling behavior for conflicts there is to merge the source file then regenerate, but at least for `sql.go` and `embedded.go` there's very little chance of a standard merge doing the right thing so they should go back to being `-merge` (or just `binary`).

**Comment by tschottdorf** [comment]
SGTM, wanna send that out? Also, where are you looking for an explanation
of `binary`? I wasn't able to find it.

On Thu, Jun 9, 2016 at 10:30 PM David Taylor <notifications@github.com>
wrote:

> IMO we should be using -merge on all generated files, since the "correct"
> merge handling behavior for conflicts there is to merge the source file
> then regenerate, but at least for sql.go and embedded.go there's very
> little chance of a standard merge doing the right thing so they should go
> back to being -merge (or just binary).
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/7110#issuecomment-225079536>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135IIqTVuQo-KfJYmsf-in_LlkJXyaks5qKMxjgaJpZM4IxSjb>
> .
>
-- 

-- Tobias

**Pull request merged**
