### PR TITLE
cdc: change cdc ux violation to assertion failure in test builds

### PR DESCRIPTION
**Pull request by stevendanna**
We don't think this should ever happen so perhaps it should always be an assertion failure. But perhaps let's run like this in CI for a bit.

Release note: None
Epic: none

### CODE REVIEW

**Comment by stevendanna** [comment]
Just for your consideration. Not urgent.

**Review by rharding6373 — APPROVED** [review]
:lgtm: Good idea. I think we should backport this for more coverage.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119294#-:-NqmDyBk1R70q17GkoEm:b87sc0p)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[`pkg/ccl/changefeedccl/event_processing.go` line 396 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119294#-NqmDYNs0ew-Lr5NE47I:-NqmDYNs0ew-Lr5NE47J:b4hioyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7301ef3cfb10996eff9bf81480e7f281460a4666/pkg/ccl/changefeedccl/event_processing.go#L396)):*
> ```Go
> 	// it's forwarded before.
> 	if schemaTS.LessEq(c.frontier.Frontier()) && !schemaTS.Equal(c.cursor) {
> 		if build.IsRelease() {
> ```

Would using `logcrash.ReportOrPanic` here be better? Then we will panic in test builds, which seems even more desirable than returning an error, as well as get a log and sentry report from binaries in the wild.

**Comment by stevendanna** [comment]
> Would using logcrash.ReportOrPanic here be better? Then we will panic in test builds, which seems even more desirable than returning an error, as well as get a log and sentry report from binaries in the wild.

Good idea. Done.

**Comment by stevendanna** [comment]
bors r=rharding6373

**Pull request merged**
