### PR TITLE
importccl: start benchmarking low-level sstable operations

### PR DESCRIPTION
**Pull request by danhhz**
This PR adds two sub-benchmarks, both dealing with the sstables
corresponding to tpcc/warehouses=1. One is a speed of light measurement
for writing to disk and calling RocksDB's IngestExternalFile. The other
is writing the same set of sstables to our kv layer with the AddSSTable
command.

Benchmark results on my laptop:

    name                                             time/op
    ImportWorkload/tpcc/warehouses=1/WriteAndLink-8    146ms ±28%
    ImportWorkload/tpcc/warehouses=1/AddSStable-8      664ms ± 2%

    name                                             speed
    ImportWorkload/tpcc/warehouses=1/WriteAndLink-8  589MB/s ±35%
    ImportWorkload/tpcc/warehouses=1/AddSStable-8    126MB/s ± 2%

    name                                             alloc/op
    ImportWorkload/tpcc/warehouses=1/WriteAndLink-8   3.92kB ± 3%
    ImportWorkload/tpcc/warehouses=1/AddSStable-8      315MB ± 0%

    name                                             allocs/op
    ImportWorkload/tpcc/warehouses=1/WriteAndLink-8     50.6 ± 3%
    ImportWorkload/tpcc/warehouses=1/AddSStable-8      23.5k ± 4%

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
Mostly :lgtm: 

`s/simply/simplify/` in the second commit message.

> Reviewed 3 of 3 files at r1, 9 of 9 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36817#-:-LcShPIh2mek9rdTvJaa:bo4xl5q)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz and @dt)

___
*[pkg/ccl/importccl/bench_test.go, line 119 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36817#-LcSnNK99WWTMcDlx7UN:-LcSnNK99WWTMcDlx7UO:bhihzj8) ([raw file](https://github.com/cockroachdb/cockroach/blob/79b1d1ad14940220de5e0d161512dc7d4e391852/pkg/ccl/importccl/bench_test.go#L119)):*
> ```Go
> 	b.ResetTimer()
> 	for i := 0; i < b.N; i++ {
> 		b.StopTimer()
> ```

Is it ok to stop a stopped timer? If so, you can remove the `b.StartTimer()` at the end of the benchmark loop in `benchmarkWriteAndLink`. If not, there's something to fix here.
___
*[pkg/ccl/importccl/read_import_workload.go, line 99 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36817#-LcSjcY9EHZaf84RPplF:-LcSjcYAA1re5aBI4dd3:b-dlef25) ([raw file](https://github.com/cockroachdb/cockroach/blob/016f6c1ddbbf0e00835f8a5ee9aa849501847ece/pkg/ccl/importccl/read_import_workload.go#L99)):*
> ```Go
> 	finishedBatchFn := func() {
> 		if finishedBatches := atomic.AddInt64(&finishedBatchesAtomic, 1); finishedBatches%1000 == 0 {
> 			lastReportedBatches := atomic.SwapInt64(&lastReportedBatchesAtomic, finishedBatches)
> ```

This is kind of awkward and I think it can result in passing a negative delta to `progress.Add` if multiple workers are completing batches very quickly. The logic that we had before seems to be easier to reason about and is likely less bug-prone. Can we do something similar here?

```
const batchesPerProgress = 1000
if finishedBatches := atomic.AddInt64(&finishedBatchesAtomic, 1); finishedBatches%batchesPerProgress == 0 {
    delta := batchesPerProgress/numTotalBatches
    progress.Add(ctx, delta)
}
```

**Review by danhhz — COMMENTED** [review]
TFTR! @dt I'd also like to get your thoughts before merging

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36817#-:-LcWWsX31t3bF44p3nH4:b-yzi4ya)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt and @nvanbenschoten)

___
*[pkg/ccl/importccl/bench_test.go, line 119 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36817#-LcSnNK99WWTMcDlx7UN:-LcWSaxm46wx-waIAch6:b-hwo0fw) ([raw file](https://github.com/cockroachdb/cockroach/blob/79b1d1ad14940220de5e0d161512dc7d4e391852/pkg/ccl/importccl/bench_test.go#L119)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is it ok to stop a stopped timer? If so, you can remove the `b.StartTimer()` at the end of the benchmark loop in `benchmarkWriteAndLink`. If not, there's something to fix here.
</blockquote></details>

It's not in the godoc but you definitely can: `if b.timerOn {`. Removed the `b.StartTimer` call and made the benchmarkWriteAndLink newline spacing match benchmarkAddSSTable
___
*[pkg/ccl/importccl/read_import_workload.go, line 99 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36817#-LcSjcY9EHZaf84RPplF:-LcWSs5q5l53vphhpjiA:b4l1rvm) ([raw file](https://github.com/cockroachdb/cockroach/blob/016f6c1ddbbf0e00835f8a5ee9aa849501847ece/pkg/ccl/importccl/read_import_workload.go#L99)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is kind of awkward and I think it can result in passing a negative delta to `progress.Add` if multiple workers are completing batches very quickly. The logic that we had before seems to be easier to reason about and is likely less bug-prone. Can we do something similar here?

```
const batchesPerProgress = 1000
if finishedBatches := atomic.AddInt64(&finishedBatchesAtomic, 1); finishedBatches%batchesPerProgress == 0 {
    delta := batchesPerProgress/numTotalBatches
    progress.Add(ctx, delta)
}
```
</blockquote></details>

Yeah, that's better, thanks. This also made me realize that this "only report job progress" stuff lives in two places (here and inside Add). Left a TODO to unify

**Review by dt — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36817#-:-LcWuuiBA4ry_cbOJgPe:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @dt and @nvanbenschoten)

**Comment by danhhz** [comment]
Thanks for the reviews!

bors r=dt,nvanbenschoten

**Pull request merged**
