### PR TITLE
exec: switch .og.go suffix to .eg.go

### PR DESCRIPTION
**Pull request by solongordon**
I accidentally cargo culted the ".og.go" suffix from optgen.
execgen-generated files now use ".eg.go" to distinguish themselves.

Release note: None

### CODE REVIEW

**Comment by solongordon** [comment]
Thanks @vilterp for pointing this out.

**Review by rjnn — APPROVED** [review]
:lgtm: Is there a sunset period you have in mind for removing the hack?

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32265#-:-LRChWbm4yPbb8PYBGl3:b-umwfeu)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by solongordon — COMMENTED** [review]
I don't know, it's not really hurting anything so maybe I shouldn't call it a temporary hack and leave it in indefinitely. But it's not necessary anymore once people have pulled and built, so a few weeks should be plenty.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32265#-:-LRChyJkEi010IJ8CX9u:b-b67x5y)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by rjnn — APPROVED** [review]
If you changed the comment to read: "remove execgen files generated with the .og suffix prior to the merging of #32265." then leaving it in perpetuity wouldn't be so bad, and it would be obvious to a reader reading this a year from now that it can easily be eliminated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32265#-:-LRCisav3rmkWQp7xzRh:b-g09yvk)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by solongordon — COMMENTED** [review]
done!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32265#-:-LRCkpKf1BBFvaVWrNzz:b-7rl0jq)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by rjnn — APPROVED** [review]
:shipit:!

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32265#-:-LRCnHdT7H8FGwMbJNuW:bizlbj7)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by jordanlewis** [comment]
This seems fine but possibly unnecessary - the reason I'm not fully gung ho about it is that it's going to cause annoying compilation problems for people going forward, because the .og.go/.eg.go files aren't checked in and therefore will not get cleaned up when switching branches.

You can already see this when you just check out an older SHA that's missing some of the .og.go generation - it will fail to compile.

So I think when we commit this, everybody will have to manually delete the .og.go files unless we do something about it.

Maybe we need a branch-change cleanup step?

**Comment by jordanlewis** [comment]
To be fully clear I think this is a good idea but I want to make sure that it doesn't cause annoying compilation problems for people!

**Comment by solongordon** [comment]
Yeah I just realized that about switching to older branches. Oy. I'll see about a git hook.

**Comment by solongordon** [comment]
Seems like Git offers a `post-checkout` hook but no `pre-checkout`, which is what we need. Best I can think of is to first commit just a `post-checkout` hook for deleting `*eg.go` files, and then sometime down the line make the switch from `og.go` to `eg.go`. But I'm tempted to just abandon this before investing any more time into this cosmetic fix.

**Comment by jordanlewis** [comment]
How about a `make` rule that deletes all `og.go` files that aren't explicitly listed in the various rules?

**Comment by solongordon** [comment]
Adding a `make` rule doesn't help with switching to older branches, does it?

**Comment by jordanlewis** [comment]
I guess not, but if you add it now, at least it'll help going forward?

**Review by benesch — COMMENTED** [review]
The only sane way that we have of handling things like this is making stray files non-ignored. I've been trying to enforce the invariant that `git checkout ANY_SHA && git clean -fd && make build` will always do the right thing.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32265#-:-LRD77nQ8r-yOtH6Eshn:b-86itfd)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[Makefile, line 1324 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32265#-LRD6nw31KuXxokpf3do:-LRD6nw31KuXxokpf3dp:b-zdr2uj) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb99d29de606e8f341af697fd9276169c9996804/Makefile#L1324)):*
> ```Makefile
> 	@# Remove generated files with the old suffix to avoid conflicts.
> 	@# See https://github.com/cockroachdb/cockroach/pull/32265.
> 	@rm -f pkg/sql/exec/*og.go
> ```

I think you want `pkg/sql/exec/*.og.go`. Otherwise you might pick up `dog.go`.
___
*[pkg/sql/exec/.gitignore, line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32265#-LRD70KY-BuNLIyA_xxV:-LRD70KY-BuNLIyA_xxW:b-l0obe5) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb99d29de606e8f341af697fd9276169c9996804/pkg/sql/exec/.gitignore#L2)):*
> ```
> *.eg.go
> *.og.go
> ```

Drop the `*.og.go`. This will make the stray files "obvious" to anyone running `git status`, and make them eligible for cleanup with `git clean`.

**Review by solongordon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32265)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[Makefile, line 1324 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32265#-LRD6nw31KuXxokpf3do:-LRDHfIIEqXMidT_A_WN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb99d29de606e8f341af697fd9276169c9996804/Makefile#L1324)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I think you want `pkg/sql/exec/*.og.go`. Otherwise you might pick up `dog.go`.
</blockquote></details>

Done.
___
*[pkg/sql/exec/.gitignore, line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32265#-LRD70KY-BuNLIyA_xxV:-LRDHjeGACTEjli9KDsX:bkcul6r) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb99d29de606e8f341af697fd9276169c9996804/pkg/sql/exec/.gitignore#L2)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Drop the `*.og.go`. This will make the stray files "obvious" to anyone running `git status`, and make them eligible for cleanup with `git clean`.
</blockquote></details>

Ah that's reasonable. Done.

**Review by benesch — APPROVED** [review]
Makefile stuff :lgtm_strong:.

> Reviewed 8 of 11 files at r1, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32265#-:-LRDJvf69xoue0RaEyEn:b-oaul5z)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
