### PR TITLE
telemetryccl: Split `TestTelemetry` into smaller sub-tests

### PR DESCRIPTION
**Pull request by Santamaura**
This change breaks up `TestTelemetry` and the `multiregion` test into four tests due to the test being quite large. The tests are: `multiregion`, `multiregion_db`, `multiregion_table`, and `multiregion_row`.

Informs: #103004

Release note: None

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106912)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @Santamaura)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106912#-N_ZHvHr8AeZyJoEikMl):*
nit: this doesn't really fix that test flake, so maybe switch to "Informs: ". We can separately close the flake with a note that we're waiting for a better repro later.
___
*[`pkg/ccl/telemetryccl/testdata/telemetry/multiregion_db` line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106912#-N_ZI6I9AMppN5gvFonp:-N_ZI6I9AMppN5gvFonq:bhz29hm) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b8cba518c8919e52153d0adc07db19b65b32c86/pkg/ccl/telemetryccl/testdata/telemetry/multiregion_db#L93)):*
> ```
> USE d;
> ALTER DATABASE d ADD REGION "ap-southeast-2"
> ----
> ```

This last exec line seems out of place. It would only be here to set up later tests, but this file has no more. Does it belong elsewhere?
___
*[`pkg/ccl/telemetryccl/telemetry_test.go` line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106912#-N_ZHMTX8vKkoFY579rn:-N_ZHMTX8vKkoFY579ro:b-g87g9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b8cba518c8919e52153d0adc07db19b65b32c86/pkg/ccl/telemetryccl/telemetry_test.go#L22)):*
> ```Go
> )
> 
> func TestTelemetryMultiregion(t *testing.T) {
> ```

Why are there separate test functions with identical setup inside? The datadriven test runner will automatically walk every individual test if you give it the directory.

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106912)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @ericharmeling)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106912#-N_ZHvHr8AeZyJoEikMl):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: this doesn't really fix that test flake, so maybe switch to "Informs: ". We can separately close the flake with a note that we're waiting for a better repro later.
</blockquote></details>

Right, changed to informs.
___
*[`pkg/ccl/telemetryccl/testdata/telemetry/multiregion_db` line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106912#-N_ZI6I9AMppN5gvFonp:-N_ZL9OtBtMBtUwlnbiE:bazldfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b8cba518c8919e52153d0adc07db19b65b32c86/pkg/ccl/telemetryccl/testdata/telemetry/multiregion_db#L93)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

This last exec line seems out of place. It would only be here to set up later tests, but this file has no more. Does it belong elsewhere?
</blockquote></details>

Thanks for the catch it's leftovers from splitting the test, removed.
___
*[`pkg/ccl/telemetryccl/telemetry_test.go` line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106912#-N_ZHMTX8vKkoFY579rn:-N_ZLGQN8adI0Wbc7UfX:b-st2357) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b8cba518c8919e52153d0adc07db19b65b32c86/pkg/ccl/telemetryccl/telemetry_test.go#L22)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Why are there separate test functions with identical setup inside? The datadriven test runner will automatically walk every individual test if you give it the directory.
</blockquote></details>

I thought we would want them as separate go tests but if not I've changed it back to the original.

**Review by dhartunian — APPROVED** [review]
Test breakup :lgtm: just some nits.

can you make sure your git author/email settings are correct? that might be why the CLA thing thinks you haven't signed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106912#-:-N_eCILk9TSprPWo3qv_:brkgivl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling and @Santamaura)

___
*[`pkg/ccl/telemetryccl/testdata/telemetry/multiregion_row` line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106912#-N_eE6zO4Wx-K6JlRqbi:-N_eE6zO4Wx-K6JlRqbj:b-sxqthy) ([raw file](https://github.com/cockroachdb/cockroach/blob/09a32d6d7c18bf488cd3a981be8ad418d0200c53/pkg/ccl/telemetryccl/testdata/telemetry/multiregion_row#L179)):*
> ```
> 
> exec
> ALTER TABLE t6 SET LOCALITY REGIONAL BY ROW AS "cr"
> ```

another stray exec
___
*[`pkg/ccl/telemetryccl/testdata/telemetry/multiregion_table` line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106912#-N_eD0g_0cEhgsnuf69k:-N_eD0g_0cEhgsnuf69l:b-aviwst) ([raw file](https://github.com/cockroachdb/cockroach/blob/09a32d6d7c18bf488cd3a981be8ad418d0200c53/pkg/ccl/telemetryccl/testdata/telemetry/multiregion_table#L12)):*
> ```
> SET enable_multiregion_placement_policy = true;
> USE d;
> ALTER DATABASE d ADD REGION "ap-southeast-2"
> ```

you can combine this with `exec` above.

**Review by Santamaura — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106912#-:-N_ihoW774Hwi1f1Gqt_:b-896fix)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian and @ericharmeling)

___
*[`pkg/ccl/telemetryccl/testdata/telemetry/multiregion_row` line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106912#-N_eE6zO4Wx-K6JlRqbi:-N_ihq1Y89_JIlkwkVWv:bo3vl6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/09a32d6d7c18bf488cd3a981be8ad418d0200c53/pkg/ccl/telemetryccl/testdata/telemetry/multiregion_row#L179)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

another stray exec
</blockquote></details>

Thanks, done.
___
*[`pkg/ccl/telemetryccl/testdata/telemetry/multiregion_table` line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106912#-N_eD0g_0cEhgsnuf69k:-N_ihsKx5zzM0nU1dx0o:bc9g5lr) ([raw file](https://github.com/cockroachdb/cockroach/blob/09a32d6d7c18bf488cd3a981be8ad418d0200c53/pkg/ccl/telemetryccl/testdata/telemetry/multiregion_table#L12)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

you can combine this with `exec` above.
</blockquote></details>

Actually when I tried to combine with the above previously the test fails on syntax error..not sure why.

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106912)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian and @ericharmeling)

___
*[`pkg/ccl/telemetryccl/testdata/telemetry/multiregion_table` line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106912#-N_eD0g_0cEhgsnuf69k:-N_ii4K9C10NU00I0VRP:bm9sv5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/09a32d6d7c18bf488cd3a981be8ad418d0200c53/pkg/ccl/telemetryccl/testdata/telemetry/multiregion_table#L12)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

Actually when I tried to combine with the above previously the test fails on syntax error..not sure why.
</blockquote></details>

`error: pq: at or near "set": syntax error`

**Pull request merged**
