### PR TITLE
storage/engine/enginepb: document MVCCMetadata.Txn existence

### PR DESCRIPTION
**Pull request by petermattis**
Release note: None

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41982)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/enginepb/mvcc.proto, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41982#-LsN2qKu5M8ccf8tmdO3:-LsN2qKu5M8ccf8tmdO4:ba2mmn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b790bcf1276c016947157e6005d4205438a8a6be/pkg/storage/engine/enginepb/mvcc.proto#L30)):*
> ```protobuf
>   // values (e.g. timeseries data). Also not present for
>   // "reconstructed" metadata that is used during MVCC processing when
>   // no intent exists on disk.
> ```

just for my understanding, is there a short explanation of reconstructed metadata?

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41982)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sumeerbhola)

___
*[pkg/storage/engine/enginepb/mvcc.proto, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41982#-LsN2qKu5M8ccf8tmdO3:-LsN4R7oEtX3hnggo0CL:btzqep8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b790bcf1276c016947157e6005d4205438a8a6be/pkg/storage/engine/enginepb/mvcc.proto#L30)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

just for my understanding, is there a short explanation of reconstructed metadata?
</blockquote></details>

The original KV layout for CRDB had the "metadata" record for a key always existing. An intent was distinguished by the presence of `MVCCMetadata.Txn`. If `MVCCMetadata.Txn == nil` we'd know that no intent was present and we'd look for the timestamped record. We discovered fairly early that always storing the metadata record was a bad idea for performance. So now we only store the metadata record when an intent is present. If an intent isn't present, we reconstruct the metadata record from the most recent versioned value. See `mvcc.go:mvccGetMetadata` for how that is done. 

It might be beneficial to plumb through knowledge of the lack of the metadata record to more places in the MVCC code.

**Comment by petermattis** [comment]
TFTR!

bors r+

**Review by nvb — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41982#-:-LsOJBOtC6zH_v5lkSs3:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sumeerbhola)

**Pull request merged**
