### PR TITLE
acceptance: extend remote Cluster implementation

### PR DESCRIPTION
**Pull request by tbg**
Implemented `NewClient`, `ExecRoot`, `InternalIP` and verified that
`TestPartitionBank` works (though it will likely exhibit the same
timeouts for which the test is already skipped). Minor edits to the
`iptables` partitioner to be able to run against a steady cluster even
when crashing half-way through.
`checkRangeReplication` also works against remote clusters now.
Fixed an off-by-one in remote cluster's PGUrl (we start at zero, not one).

From here on, should be easy to add additional nemeses which periodically
kill nodes or perform other shenanigans.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8091)

### CODE REVIEW

**Comment by tamird** [comment]
Second commit is broken

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: 1 of 8 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8091#-:-KNl_KED3ZKVK6rhl7rj:-1853988023)*

**Comment by tschottdorf** [comment]
Care to be more specific?

**Comment by tamird** [comment]
It doesn't compile - you removed the "os" import but not the code that
wants it.

**Comment by tschottdorf** [comment]
Thanks, had it in the wrong commit.
-- 

-- Tobias

**Comment by tamird** [comment]
Heh, that commit message is incorrect now since you're duplicating the assertion rather than moving it.

**Comment by tschottdorf** [comment]
Sometimes I wonder how I manage. PTAL.
-- 

-- Tobias

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 8 files at r4, 1 of 1 files at r5, 8 of 8 files at r7, 8 of 8 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[acceptance/allocator_test.go, line 115 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8091#-KNli6oTHUwSBg7O9Wn9:-KNli6oTHUwSBg7O9WnA:-1189717218) ([raw file](https://github.com/cockroachdb/cockroach/blob/172a8bfc195198883504e2667187ee1e910811fd/acceptance/allocator_test.go#L115)):*
> ```Go
> func (at *allocatorTest) Run(t *testing.T) {
> 	at.f = farmer(t, at.Prefix)
> 	if e := "GOOGLE_PROJECT"; os.Getenv(e) == "" {
> ```

this one probably also wants to be in the previous commit (which moved this to the farmer)

---

*[acceptance/partition.go, line 63 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8091#-KNlj-IpKLDFa9b3IJMU:-KNlj-IpKLDFa9b3IJMV:-858052417) ([raw file](https://github.com/cockroachdb/cockroach/blob/722e47cd21ceed0dba8281bde1d01d56eb14dfac/acceptance/partition.go#L63)):*
> ```Go
> 	randSec := func() time.Duration { return time.Duration(rand.Int63n(15 * int64(time.Second))) }
> 	log.Infof(context.Background(), "cleaning up any previous rules")
> 	_ = restoreNetwork(t, c) // clean up any potential leftovers
> ```

see question below - if we don't do the recover down there, we shouldn't need this.

---

*[acceptance/partition.go, line 100 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8091#-KNlitvP49TfGGdK1rxh:-KNlitvP49TfGGdK1rxi:1053881732) ([raw file](https://github.com/cockroachdb/cockroach/blob/722e47cd21ceed0dba8281bde1d01d56eb14dfac/acceptance/partition.go#L100)):*
> ```Go
> 	defer func() {
> 		if r := recover(); r != nil {
> 			panic(r)
> ```

why? this seems to have the only effect that the network won't be cleaned up on panic. is that intended?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8091#-:-KNljHl9YZ7ftmn3pDs2:1417088721)*

**Comment by tschottdorf** [comment]
Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[acceptance/allocator_test.go, line 115 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8091#-KNli6oTHUwSBg7O9Wn9:-KNllx8Ri7ZoDDZbqMa6:1121403250) ([raw file](https://github.com/cockroachdb/cockroach/blob/172a8bfc195198883504e2667187ee1e910811fd/acceptance/allocator_test.go#L115)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this one probably also wants to be in the previous commit (which moved this to the farmer)
</details>
Done (squashed).

---

*[acceptance/partition.go, line 63 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8091#-KNlj-IpKLDFa9b3IJMU:-KNll0CXdOxgrdwD7bEt:-1947711161) ([raw file](https://github.com/cockroachdb/cockroach/blob/722e47cd21ceed0dba8281bde1d01d56eb14dfac/acceptance/partition.go#L63)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> see question below - if we don't do the recover down there, we shouldn't need this.
</details>
The test runner could be killed and the defers would not run.

---

*[acceptance/partition.go, line 100 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8091#-KNlitvP49TfGGdK1rxh:-KNllE5Td9XDOxiXsYVI:194888467) ([raw file](https://github.com/cockroachdb/cockroach/blob/722e47cd21ceed0dba8281bde1d01d56eb14dfac/acceptance/partition.go#L100)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why? this seems to have the only effect that the network won't be cleaned up on panic. is that intended?
</details>
No, just put this in on instinct because `restoreNetwork` does a lot of complicated things and if we get here with a panic, we'd likely just panic again. But that doesn't seem worse. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8091)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8091)*

**Comment by cuongdo** [comment]
:lgtm: w/ comments

---

Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[acceptance/allocator_test.go, line 188 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8091#-KNlxaObUYX6JtzLzYHo:-KNlxaOcD0gAXSsOPk9J:-1130413695) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbad552a91e5a129e96e4c4089e0b7d1ff396d62/acceptance/allocator_test.go#L188)):*
> ```Go
> }
> 
> func (at *allocatorTest) RunWait(t *testing.T) {
> ```

Since the main thing this method does is call `WaitForRebalance`, I think it makes for this method to subsume `WaitForRebalance`.

---

*[acceptance/allocator_terraform/main.tf, line 102 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8091#-KNlyZkzS24o9kTPWdDm:-KNlyZkzS24o9kTPWdDn:-1653798733) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbad552a91e5a129e96e4c4089e0b7d1ff396d62/acceptance/allocator_terraform/main.tf#L102)):*
> ```HCL
>       "export CLOUD_SDK_REPO=\"cloud-sdk-$(lsb_release -c -s)\"",
>       "echo \"deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main\" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list",
>       "curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -",
> ```

`-s` -> `-sS`

`-s` makes curl completely silent, even for errors. The `S` flag makes it show errors again.

---

*[acceptance/terrafarm/farmer.go, line 231 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8091#-KNlyqKbdK5_bkPDl7hr:-KNlyqKbdK5_bkPDl7hs:-61752527) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbad552a91e5a129e96e4c4089e0b7d1ff396d62/acceptance/terrafarm/farmer.go#L231)):*
> ```Go
> 	// might do it: `curl http://instance-data/latest/meta-data/public-ipv4`.
> 	// See https://flummox-engineering.blogspot.com/2014/01/get-ip-address-of-google-compute-engine.html
> 	cmd := `curl -s "http://metadata/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip" -H "X-Google-Metadata-Request: True"`
> ```

`-s` -> `-sS` otherwise you'll never see any errors

---

*[acceptance/terrafarm/farmer.go, line 232 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8091#-KNlzR81PDLAHeMSAXI2:-KNlzR824g71kUvQ9Iwr:1916376188) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbad552a91e5a129e96e4c4089e0b7d1ff396d62/acceptance/terrafarm/farmer.go#L232)):*
> ```Go
> 	// See https://flummox-engineering.blogspot.com/2014/01/get-ip-address-of-google-compute-engine.html
> 	cmd := `curl -s "http://metadata/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip" -H "X-Google-Metadata-Request: True"`
> 	stdOut, stdErr, err := f.ssh(f.Nodes()[i], f.defaultKeyFile(), cmd)
> ```

Its more standard to not camelCase `stdOut` and `stdErr`. See `os.Stdout` and `os.Stderr`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8091#-:-KNm-C2YNPMMtI9Fy7m2:-1477467219)*

**Comment by tschottdorf** [comment]
@cuongdo addressed your comments. Actually folded almost everything back into `Run` in the allocator tests (except `Cleanup`). I started that decomposition thinking it was going somewhere, but it wasn't really.

**Comment by cuongdo** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8091#-:-KNmA29rCy5nRC9oHpT9:1417088721)*

**Pull request merged**
