### PR TITLE
ui: unify cluster-ui stores for Statement and Transaction Page

### LINKED ISSUE #72009: Clear SQL stats on the Transactions page does not work on serverless
A user reported that clicking on “clear SQL stats” on the Transactions page doesn’t do anything. On the Statements page, there's at least a spinner to indicate progress when clearing SQL stats.

Epic: CC-5060

### PR DESCRIPTION
**Pull request by Azhng**
Previously, on CC Conosle, Statement Page and Transaction Page were backed by
their own Redux stores and their own Redux Sagas. However, both Statement
and Transaction Page were backed by a single API endpoint, namely
`/_status/statements`. This resulted in unnecessary API calls and bugs
like #72009, which was caused by Reset SQL Stats sagas failing to
reset the Transaction Page Redux store.

This commit unifies the following Redux store and sagas into a single
store / sagas:
1. Statement Page store / sagas
2. Transaciton Page store / sagas
3. Reset SQL Stats store / sagas

This greatly removed the code duplication and test duplication and simplify
the logic. Statement Page and Transaction Page can reuse the same store
by their own selectors.

Resolves #72009

Release note: None

CC Console: 

https://user-images.githubusercontent.com/9267198/141212289-00c5196b-87c0-4bae-a163-3542e1a2b6a0.mov

DB Console: 

https://user-images.githubusercontent.com/9267198/141048060-482d23e6-dc77-4868-98dd-e209d0965cf9.mov

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> Reviewed 19 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72627)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/store/sagas.ts, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72627#-Mo_OGXM40Y7qUkIFvwo:-Mo_OGXM40Y7qUkIFvwp:b-hvz5f1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab15b8e648465dc26d73fa22001078811633c299/pkg/ui/workspaces/cluster-ui/src/store/sagas.ts#L31)):*
> ```XML
>     fork(notifificationsSaga),
>     fork(sqlStatsSaga),
>     fork(terminateSaga),
> ```

what is this one for?
___
*[pkg/ui/workspaces/cluster-ui/src/store/sqlStats/sqlStats.sagas.spec.ts, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72627#-Mo_NaaK3eTaZ7EHwgT-:-Mo_NaaLC1eVQpSlVbyE:babepz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab15b8e648465dc26d73fa22001078811633c299/pkg/ui/workspaces/cluster-ui/src/store/sqlStats/sqlStats.sagas.spec.ts#L54)):*
> ```XML
>     });
> 
>     it("requests combined SQL Stats if combined=true in the request message", () => {
> ```

nit: test also with combined false
___
*[pkg/ui/workspaces/db-console/src/redux/sqlStats/sqlStatsSagas.ts, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72627#-Mo_O46M-6-U8PIZI0My:-Mo_O46N8ZgMg9exWsCo:bm8msyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c996e386c2be49db5babcb438e8af3770cd2dfc/pkg/ui/workspaces/db-console/src/redux/sqlStats/sqlStatsSagas.ts#L33)):*
> ```XML
>     yield put(resetSQLStatsCompleteAction());
>     yield put(invalidateStatements());
>     yield put(refreshStatements() as any);
> ```

we don't want to refresh sql stats here?

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72627)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/store/sagas.ts, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72627#-Mo_OGXM40Y7qUkIFvwo:-MojPYyn32TyFOQhcaVw:b-ghs0re) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab15b8e648465dc26d73fa22001078811633c299/pkg/ui/workspaces/cluster-ui/src/store/sagas.ts#L31)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

what is this one for?
</blockquote></details>

Removed, I noticed we had an unused import for `terminateSaga` and thought we just missed it. I just remembered that we disabled that button already.
___
*[pkg/ui/workspaces/cluster-ui/src/store/sqlStats/sqlStats.sagas.spec.ts, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72627#-Mo_NaaK3eTaZ7EHwgT-:-MojPVwYEhjmwtPN0ZBz:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab15b8e648465dc26d73fa22001078811633c299/pkg/ui/workspaces/cluster-ui/src/store/sqlStats/sqlStats.sagas.spec.ts#L54)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: test also with combined false
</blockquote></details>

Done. 
___
*[pkg/ui/workspaces/db-console/src/redux/sqlStats/sqlStatsSagas.ts, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72627#-Mo_O46M-6-U8PIZI0My:-MojOn5N4zG2WsIv_ZUq:bjkscvm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c996e386c2be49db5babcb438e8af3770cd2dfc/pkg/ui/workspaces/db-console/src/redux/sqlStats/sqlStatsSagas.ts#L33)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

we don't want to refresh sql stats here?
</blockquote></details>

I am a bit uncertain about this. If we invalidate the state, this would cause the selector to return `null`, which in turn will trigger the `componentDidUpdate()` React component hook, which in turn will invoke the `refreshStatement` sagas anyway.

That's why I'm a bit not so sure if we should let the React component to handle this or if we should let the Sagas to handle this. Thoughts ?

**Review by maryliag — COMMENTED** [review]
> Reviewed 1 of 23 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72627)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @maryliag)

___
*[pkg/ui/workspaces/db-console/src/redux/sqlStats/sqlStatsSagas.ts, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72627#-Mo_O46M-6-U8PIZI0My:-Mojc4geCv-8Pu7CUb6Z:bhdqya2) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c996e386c2be49db5babcb438e8af3770cd2dfc/pkg/ui/workspaces/db-console/src/redux/sqlStats/sqlStatsSagas.ts#L33)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

I am a bit uncertain about this. If we invalidate the state, this would cause the selector to return `null`, which in turn will trigger the `componentDidUpdate()` React component hook, which in turn will invoke the `refreshStatement` sagas anyway.

That's why I'm a bit not so sure if we should let the React component to handle this or if we should let the Sagas to handle this. Thoughts ? 
</blockquote></details>

If we keep the refresh here, is the refreshStatement being called twice? (here and on the component did mount), or if we call it here it doesn't get called there again?
If is being called twice, there isn't need for the refresh here, otherwise we can keep this here

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72627)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[pkg/ui/workspaces/db-console/src/redux/sqlStats/sqlStatsSagas.ts, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72627#-Mo_O46M-6-U8PIZI0My:-Mp7nOsUD0Gvn8HMAOeV:b-xdo29e) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c996e386c2be49db5babcb438e8af3770cd2dfc/pkg/ui/workspaces/db-console/src/redux/sqlStats/sqlStatsSagas.ts#L33)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

If we keep the refresh here, is the refreshStatement being called twice? (here and on the component did mount), or if we call it here it doesn't get called there again?
If is being called twice, there isn't need for the refresh here, otherwise we can keep this here
</blockquote></details>

Hmm thinking about this a bit more, if we refresh here, then yes `refreshStatement()` will called twice, (once here and once on the component did update). 

However I think that is probably fine, since `refreshStatement()` is only issuing `refresh` redux actions. Since this is backed by a `CachedDataReducer`, two subsequent `refresh` actions will only result in API calls. 

I think letting the saga to deal with the refresh would be ideal for the long term, as we move to use functional components and no longer rely on React lifecycle method in the future. 


Added `refreshStatements()` call here.

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72627#-:-MpHoSJ74l-gpLmbmAwk:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

**Comment by Azhng** [comment]
TFTR!

bors r=maryliag

**Comment by Azhng** [comment]
bors r=maryliag

**Pull request merged**
