### PR TITLE
roachprod, roachtest: grafana dashboard migration and flag

### LINKED ISSUE #83663: roachprod: set up default grafana dashboard in `grafana-start`
When a roachprod user runs `grafana-start`, regardless of whether they pass a `grafana-config`, a user should be able to see a default dashboard, perhaps with the following [pages](https://github.com/cockroachdb/cockroach/tree/master/monitoring/grafana-dashboards). 

Jira issue: CRDB-17197

### PR DESCRIPTION
**Pull request by herkolategan**
The only way to currently pass a grafana dashboard to roachprod is via URL. This change enables adding a JSON string to the config which allows for more flexibility from various sources. Multiple configs can be added or passed to `StartGrafana`.

The JSON string based configs are written to the target Prometheus node, with Grafana, via `PutString` and indexed in order that it does not conflict with any other configs.

Additionally add a flag to `roachprod` for pointing to a local grafana dashboard json config. If no config is specified through one of the grafana config flags a set of default dashboards will be used.

Instead of hosting the dashboards somewhere and passing the URLs a change has been made to rather embed the dashboards so that it can form part of the repository for easier maintenance and improvements.

In roachtest the URLs provided for grafana dashboards in the tests are replaced with embedded configs.

Resolves: #83663, #83662, #97382

Epic: None
Release note: None

### CODE REVIEW

**Review by smg260 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 6 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97352)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @srosenberg)

___
*[`pkg/cmd/roachprod/grafana/dashboards.go` line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97352#-NOzxN2782DA0gueVpnf:-NOzxN2782DA0gueVpng:b-3oj3ih) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e7346bc147100ab1b42b4bb7e18af9e7d80995b/pkg/cmd/roachprod/grafana/dashboards.go#L23)):*
> ```Go
> // GetDashboards returns the grafana dashboards to be installed.
> // or if none is specified, the default dashboards.
> func GetDashboards(grafanaConfigFile string) ([]string, error) {
> ```

IMO this should be split into 2 separate functions.  `GetDashboardJSONFromFile` and GetDefaultDashboardJSONs`. I think there is a mismatch in specifying a single file path arg, and being returned an array of strings. 

Also if a file path is specified, then would it make sense that the file should exist and if it doesn't, perhaps an error should be returned?

**Review by herkolategan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97352)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @smg260 and @srosenberg)

___
*[`pkg/cmd/roachprod/grafana/dashboards.go` line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97352#-NOzxN2782DA0gueVpnf:-NP-1ur94Owuy0HM_MUG:b-vj28bs) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e7346bc147100ab1b42b4bb7e18af9e7d80995b/pkg/cmd/roachprod/grafana/dashboards.go#L23)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

IMO this should be split into 2 separate functions.  `GetDashboardJSONFromFile` and GetDefaultDashboardJSONs`. I think there is a mismatch in specifying a single file path arg, and being returned an array of strings. 

Also if a file path is specified, then would it make sense that the file should exist and if it doesn't, perhaps an error should be returned?
</blockquote></details>

It does return an error if a file is specified and does not exist;

but I agree with the argument that the function is ambiguous, and a split in logic would make more sense. 



_Code snippet:_
```Go
❯ ./bin/roachprod grafana-start herko-test --grafana-config-file non_existant.json
Error: UNCLASSIFIED_PROBLEM: open non_existant.json: no such file or directory
(1) UNCLASSIFIED_PROBLEM
Wraps: (2) open non_existant.json
Wraps: (3) no such file or directory
Error types: (1) errors.Unclassified (2) *fs.PathError (3) syscall.Errno
```

**Review by renatolabs — COMMENTED** [review]
Agree with Miral's comment. LGTM otherwise!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97352#-:-NP-Na990RIicTTYzkwm:bi1glrw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @smg260, and @srosenberg)

___
*[`pkg/roachprod/prometheus/prometheus.go` line 400 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97352#-NP-NXf5EtgSEgie8LNS:-NP-NXf5EtgSEgie8LNT:b-vztljy) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb994924ec848d8adfd13a4a69ca4e00e8610713/pkg/roachprod/prometheus/prometheus.go#L400)):*
> ```Go
> 		for idx, json := range cfg.Grafana.DashboardJSON {
> 			if err := c.PutString(ctx, l, cfg.PrometheusNode, json,
> 				fmt.Sprintf("/var/lib/grafana/dashboards/s-%d.json", idx), 0777); err != nil {
> ```

Are the filenames relevant at all? Curious why the `s` prefix.

**Review by herkolategan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97352)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs, @smg260, and @srosenberg)

___
*[`pkg/roachprod/prometheus/prometheus.go` line 400 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97352#-NP-NXf5EtgSEgie8LNS:-NP1ac0g6lCKApzmAEtj:b-y3fdeo) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb994924ec848d8adfd13a4a69ca4e00e8610713/pkg/roachprod/prometheus/prometheus.go#L400)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Are the filenames relevant at all? Curious why the `s` prefix.
</blockquote></details>

Correct, the filenames are not relevant. The only reason for the prefix is to avoid collision with files added from URLs by the code just above this. Alternatively could have pulled `idx` out of the for loop and sticked with no prefix.

**Review by renatolabs — APPROVED** [review]

**Review by smg260 — APPROVED** [review]
> Reviewed 6 of 16 files at r2, 15 of 15 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97352)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs and @srosenberg)

**Comment by herkolategan** [comment]
TFTR!
bors r=renatolabs,smg260

**Pull request merged**
