### PR TITLE
ui: add list of fingerprints used by index

### PR DESCRIPTION
**Pull request by maryliag**
Part Of #93087

This commits adds on the Index Details page the list of fingerprints that were used by that index.

This first commit shows all statement fingerprints, follow PRs will add features such as: search, filter, time selection and listing Transactions.

Screen Shot 2023-01-06 at 5 00 59 PM

https://www.loom.com/share/7ac91cd489204808a381e8b995442d67

This PR also updates the ui-components package to include the fix on the Tooltip component.

Release note (ui change): Adds on the Index Details page a list of all statement fingerprints that used that index.

### CODE REVIEW

**Review by j82w — APPROVED** [review]
:lgtm:

> Reviewed 13 of 14 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94863#-:-NLWKIkM5Z-aZEWDfRVc:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kevin-v-ngo)

**Review by gtr — COMMENTED** [review]
> Reviewed 12 of 14 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94863)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kevin-v-ngo and @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/indexDetailsApi.ts` line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94863#-NLWX1sF1-cFpCie1h4l:-NLWX1sF1-cFpCie1h4m:b-y5lwqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/42c82d991b0cbdb66c8ec5e06ee815b98d798059/pkg/ui/workspaces/cluster-ui/src/api/indexDetailsApi.ts#L73)):*
> ```XML
> };
> 
> export function StatementsListRequestFromDetails(
> ```

Just one question: is there a reason this exported function uses PascalCase but the other exported functions (`getStatementsUsingIndex`) use camelCase?

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94863)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @gtr and @kevin-v-ngo)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/indexDetailsApi.ts` line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94863#-NLWX1sF1-cFpCie1h4l:-NLWhVS5C-Q1BZDVul9G:b-nkomvm) ([raw file](https://github.com/cockroachdb/cockroach/blob/42c82d991b0cbdb66c8ec5e06ee815b98d798059/pkg/ui/workspaces/cluster-ui/src/api/indexDetailsApi.ts#L73)):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

Just one question: is there a reason this exported function uses PascalCase but the other exported functions (`getStatementsUsingIndex`) use camelCase?
</blockquote></details>

I was creating the type right below and got mixed up. I have another PR coming with the extra changes, so I'll add this update there too

**Comment by rail** [comment]
bors r-
We have temporarily disabled bors for merges. Please merge the PR manually when all required checks pass.

**Comment by rail** [comment]
bors r-
We have temporarily disabled bors for merges. Please merge the PR manually when all required checks pass.

**Pull request merged**
