### PR TITLE
colexec: make merge joiner more dynamic

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: cleanup and extend the merge joiner benchmark**

This commit refactors the merge joiner benchmark to remove the code
duplication as well as extends it to support the number of rows smaller
than coldata.BatchSize().

Additionally, it fixes the issue with the benchmark in which we used the
same coldata.Batch object for both sources, and as a result
"oneSideRepeat" config happened to behave exactly like "no repeats"
since the later source (the right one) wasn't repeated (internally, we
populated the batch with repeated rows for the left source and then
overwrote the same batch with non-repeated rows).

Another issue was not using the "chunks" sources that adjust the
batches so that they are, in fact, ordered on the equality columns
(previously, we were returning the same batch over and over, without
adjustments, i.e. we had tuple stream like 1, 2, 3, ..., 1024, 1, 2,
3 ...).

This commit also changes the benchmark to be very similar to what we
have in the row-execution with the following:
- change the number of columns to 1
- make the right side repeated for "oneSideRepeat" config
- change the computation of "numRepeats".

Release note: None

**colexec: make groups buffer in merge joiner dynamic**

Previously, we would always allocate the maximum possible number of
groups that could ever occur (FULL OUTER JOIN with no matches), however,
this is not necessary in most cases. This commit refactors the circular
groups buffer to grow dynamically if necessary while starting out with
small initial slices.

Release note: None

**colexec: make spilling queue more dynamic**

This commit introduces the dynamic allocation of items slice until the
estimated maximum which makes the spilling queue more dynamic.

Also, currently, we're always allocating a dequeue scratch batch of
coldata.BatchSize() capacity when creating a spilling queue. However,
that batch is only needed if we actually spill to disk, so this commit
makes that allocation lazy.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
[Here](https://gist.github.com/yuzefovich/7b38b03a595c42d7f359b9a5a3a241d4) are the detailed benchmarks, but the benchmarks of the second and the third commits together are:
```
name                                       old time/op    new time/op     delta
MergeJoiner/rows=1-24                        19.0µs ± 1%      6.5µs ± 2%   -65.95%  (p=0.000 n=10+10)
MergeJoiner/rows=16-24                       30.4µs ± 1%     14.1µs ± 2%   -53.53%  (p=0.000 n=10+10)
MergeJoiner/rows=128-24                      47.3µs ± 1%     43.0µs ± 1%    -8.95%  (p=0.000 n=10+10)
MergeJoiner/rows=1024-24                      115µs ± 1%      192µs ± 6%   +65.87%  (p=0.000 n=9+10)
MergeJoiner/rows=8192-24                      526µs ± 2%      582µs ± 1%   +10.54%  (p=0.000 n=10+9)
MergeJoiner/rows=65536-24                    3.50ms ± 1%     3.71ms ± 1%    +5.88%  (p=0.000 n=9+10)
MergeJoiner/oneSideRepeat-rows=1-24          12.0µs ± 1%      2.7µs ± 3%   -77.16%  (p=0.000 n=9+10)
MergeJoiner/oneSideRepeat-rows=16-24         28.9µs ± 0%     13.0µs ± 3%   -54.89%  (p=0.000 n=9+10)
MergeJoiner/oneSideRepeat-rows=128-24        44.0µs ± 1%     40.1µs ± 2%    -9.06%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=1024-24        116µs ± 0%      184µs ± 1%   +58.72%  (p=0.000 n=9+9)
MergeJoiner/oneSideRepeat-rows=8192-24        204µs ± 4%      201µs ± 3%      ~     (p=0.105 n=10+10)
MergeJoiner/oneSideRepeat-rows=65536-24       590µs ± 2%      570µs ± 2%    -3.34%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=1-24        19.1µs ± 2%      6.6µs ± 2%   -65.68%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=16-24       30.7µs ± 1%     14.4µs ± 2%   -53.21%  (p=0.000 n=9+10)
MergeJoiner/bothSidesRepeat-rows=128-24      46.8µs ± 1%     43.1µs ± 4%    -7.99%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=1024-24      116µs ± 3%      183µs ± 1%   +57.72%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=8192-24      675µs ± 1%      665µs ± 1%    -1.38%  (p=0.001 n=8+10)
MergeJoiner/bothSidesRepeat-rows=65536-24    9.74ms ± 0%     9.12ms ± 1%    -6.40%  (p=0.000 n=9+10)

name                                       old speed      new speed       delta
MergeJoiner/rows=1-24                       840kB/s ± 0%   2466kB/s ± 1%  +193.52%  (p=0.000 n=8+9)
MergeJoiner/rows=16-24                     8.41MB/s ± 1%  18.11MB/s ± 2%  +115.26%  (p=0.000 n=10+10)
MergeJoiner/rows=128-24                    43.3MB/s ± 1%   47.6MB/s ± 1%    +9.83%  (p=0.000 n=10+10)
MergeJoiner/rows=1024-24                    142MB/s ± 1%     86MB/s ± 6%   -39.57%  (p=0.000 n=9+10)
MergeJoiner/rows=8192-24                    249MB/s ± 2%    225MB/s ± 1%    -9.54%  (p=0.000 n=10+9)
MergeJoiner/rows=65536-24                   299MB/s ± 1%    283MB/s ± 1%    -5.54%  (p=0.000 n=9+10)
MergeJoiner/oneSideRepeat-rows=1-24        1.33MB/s ± 1%   5.84MB/s ± 3%  +337.56%  (p=0.000 n=9+10)
MergeJoiner/oneSideRepeat-rows=16-24       8.85MB/s ± 0%  19.63MB/s ± 3%  +121.81%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=128-24      46.5MB/s ± 1%   51.1MB/s ± 2%    +9.98%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=1024-24      141MB/s ± 0%     89MB/s ± 1%   -37.00%  (p=0.000 n=9+9)
MergeJoiner/oneSideRepeat-rows=8192-24      644MB/s ± 4%    653MB/s ± 3%      ~     (p=0.105 n=10+10)
MergeJoiner/oneSideRepeat-rows=65536-24    1.78GB/s ± 2%   1.84GB/s ± 2%    +3.46%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=1-24       837kB/s ± 2%   2442kB/s ± 2%  +191.76%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=16-24     8.35MB/s ± 2%  17.84MB/s ± 2%  +113.74%  (p=0.000 n=9+10)
MergeJoiner/bothSidesRepeat-rows=128-24    43.7MB/s ± 1%   47.5MB/s ± 4%    +8.72%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=1024-24    141MB/s ± 3%     90MB/s ± 1%   -36.60%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=8192-24    194MB/s ± 0%    197MB/s ± 1%    +1.41%  (p=0.001 n=8+10)
MergeJoiner/bothSidesRepeat-rows=65536-24   108MB/s ± 0%    115MB/s ± 1%    +6.84%  (p=0.000 n=9+10)

name                                       old alloc/op   new alloc/op    delta
MergeJoiner/rows=1-24                        1.21kB ± 0%     1.20kB ± 0%    -0.83%  (p=0.002 n=8+10)
MergeJoiner/rows=16-24                       3.95kB ± 0%     3.94kB ± 0%    -0.42%  (p=0.000 n=10+10)
MergeJoiner/rows=128-24                      15.8kB ± 0%     52.4kB ± 0%  +231.75%  (p=0.000 n=10+10)
MergeJoiner/rows=1024-24                     53.7kB ± 0%    377.0kB ± 0%  +601.82%  (p=0.000 n=8+8)
MergeJoiner/rows=8192-24                     57.2kB ± 0%    380.2kB ± 0%  +564.98%  (p=0.000 n=10+6)
MergeJoiner/rows=65536-24                    84.8kB ± 0%    406.3kB ± 0%  +379.09%  (p=0.000 n=10+9)
MergeJoiner/oneSideRepeat-rows=1-24            374B ± 0%       368B ± 0%    -1.60%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=16-24         2.85kB ± 0%     2.83kB ± 0%    -0.58%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=128-24        9.26kB ± 0%    45.84kB ± 0%  +395.25%  (p=0.000 n=8+10)
MergeJoiner/oneSideRepeat-rows=1024-24       53.7kB ± 0%    377.0kB ± 0%  +601.82%  (p=0.001 n=7+7)
MergeJoiner/oneSideRepeat-rows=8192-24       57.6kB ± 0%     94.1kB ± 0%   +63.40%  (p=0.000 n=10+8)
MergeJoiner/oneSideRepeat-rows=65536-24      84.7kB ± 0%     84.4kB ± 0%    -0.36%  (p=0.000 n=9+8)
MergeJoiner/bothSidesRepeat-rows=1-24        1.21kB ± 0%     1.20kB ± 0%    -0.83%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=16-24       3.95kB ± 0%     3.94kB ± 0%    -0.43%  (p=0.002 n=8+10)
MergeJoiner/bothSidesRepeat-rows=128-24      15.8kB ± 0%     52.4kB ± 0%  +231.76%  (p=0.000 n=9+10)
MergeJoiner/bothSidesRepeat-rows=1024-24     53.7kB ± 0%    377.0kB ± 0%  +601.82%  (p=0.000 n=8+8)
MergeJoiner/bothSidesRepeat-rows=8192-24     57.3kB ± 0%     93.5kB ± 0%   +63.32%  (p=0.000 n=10+9)
MergeJoiner/bothSidesRepeat-rows=65536-24    88.3kB ± 0%     83.2kB ± 0%    -5.77%  (p=0.001 n=7+7)

name                                       old allocs/op  new allocs/op   delta
MergeJoiner/rows=1-24                          36.0 ± 0%       36.0 ± 0%      ~     (all equal)
MergeJoiner/rows=16-24                         80.0 ± 0%       80.0 ± 0%      ~     (all equal)
MergeJoiner/rows=128-24                         113 ± 0%        119 ± 0%    +5.31%  (p=0.000 n=10+10)
MergeJoiner/rows=1024-24                        135 ± 0%        147 ± 0%    +8.89%  (p=0.000 n=10+10)
MergeJoiner/rows=8192-24                        233 ± 0%        245 ± 0%    +5.15%  (p=0.000 n=10+10)
MergeJoiner/rows=65536-24                     1.02k ± 0%      1.03k ± 0%    +1.18%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=1-24            11.0 ± 0%       11.0 ± 0%      ~     (all equal)
MergeJoiner/oneSideRepeat-rows=16-24           69.0 ± 0%       69.0 ± 0%      ~     (all equal)
MergeJoiner/oneSideRepeat-rows=128-24           102 ± 0%        108 ± 0%    +5.88%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=1024-24          135 ± 0%        147 ± 0%    +8.89%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=8192-24          247 ± 0%        253 ± 0%    +2.43%  (p=0.000 n=10+10)
MergeJoiner/oneSideRepeat-rows=65536-24       1.03k ± 0%      1.03k ± 0%      ~     (all equal)
MergeJoiner/bothSidesRepeat-rows=1-24          36.0 ± 0%       36.0 ± 0%      ~     (all equal)
MergeJoiner/bothSidesRepeat-rows=16-24         80.0 ± 0%       80.0 ± 0%      ~     (all equal)
MergeJoiner/bothSidesRepeat-rows=128-24         113 ± 0%        119 ± 0%    +5.31%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=1024-24        135 ± 0%        147 ± 0%    +8.89%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=8192-24        233 ± 0%        239 ± 0%    +2.58%  (p=0.000 n=10+10)
MergeJoiner/bothSidesRepeat-rows=65536-24     1.02k ± 0%      1.02k ± 0%      ~     (all equal)
```
There is a regression when the input sizes are around `coldata.BatchSize()` because essentially the previous code happened to be optimized for that case in particular and the inputs are small enough that the overhead of dynamic groups buffer isn't amortized across the consequent batches. In any case, the benchmarks look very good to me.

I also think it'd be beneficial to backport the third commit to 20.2 branch because it reduces the memory footprint of the spilling queues which are used by the hash routers.

**Comment by yuzefovich** [comment]
Here are the numbers of the row-execution benchmarks (which I manually modified to be the same as the one used for the colexec numbers above) for reference:
```
BenchmarkMergeJoiner/InputSize=1-24         	  164748	      6940 ns/op	   2.31 MB/s
BenchmarkMergeJoiner/InputSize=16-24        	  107223	     11219 ns/op	  22.82 MB/s
BenchmarkMergeJoiner/InputSize=128-24       	   25456	     47366 ns/op	  43.24 MB/s
BenchmarkMergeJoiner/InputSize=1024-24      	    3723	    331480 ns/op	  49.43 MB/s
BenchmarkMergeJoiner/InputSize=8192-24      	     458	   2599771 ns/op	  50.42 MB/s
BenchmarkMergeJoiner/InputSize=65536-24     	      56	  20493937 ns/op	  51.17 MB/s
BenchmarkMergeJoiner/OneSideRepeatInputSize=1-24         	  169501	      6916 ns/op	   2.31 MB/s
BenchmarkMergeJoiner/OneSideRepeatInputSize=16-24        	  106706	     11368 ns/op	  22.52 MB/s
BenchmarkMergeJoiner/OneSideRepeatInputSize=128-24       	   25562	     47722 ns/op	  42.92 MB/s
BenchmarkMergeJoiner/OneSideRepeatInputSize=1024-24      	    3700	    332334 ns/op	  49.30 MB/s
BenchmarkMergeJoiner/OneSideRepeatInputSize=8192-24      	     506	   2370816 ns/op	  55.29 MB/s
BenchmarkMergeJoiner/OneSideRepeatInputSize=65536-24     	      67	  18083038 ns/op	  57.99 MB/s
BenchmarkMergeJoiner/BothSidesRepeatInputSize=1-24       	  171222	      6888 ns/op	   2.32 MB/s
BenchmarkMergeJoiner/BothSidesRepeatInputSize=16-24      	  104878	     11219 ns/op	  22.82 MB/s
BenchmarkMergeJoiner/BothSidesRepeatInputSize=128-24     	   25400	     47274 ns/op	  43.32 MB/s
BenchmarkMergeJoiner/BothSidesRepeatInputSize=1024-24    	    3522	    329782 ns/op	  49.68 MB/s
BenchmarkMergeJoiner/BothSidesRepeatInputSize=8192-24    	     266	   4470469 ns/op	  29.32 MB/s
BenchmarkMergeJoiner/BothSidesRepeatInputSize=65536-24   	       6	 179170067 ns/op	   5.85 MB/s
```
These show that the vectorized merge joiner performance now should be always at least on par (more or less) as in the row engine.

Note that I'll update the first commit to bring the colexec benchmark in sync with the rowexec one, but I won't rerun the benchmarks.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56838#-:-MMR8G6d-TCbLslaCYPs:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/mergejoiner_util.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56838#-MMR6NcoALk1VUPozGJf:-MMR6NcoALk1VUPozGJg:b-70rfg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c498ae833c300abdcf78384cc20c47bcff7849a7/pkg/sql/colexec/mergejoiner_util.go#L33)):*
> ```Go
> 	// slices can support. numGroupsInBuffer will never reach this number,
> 	// instead, we'll allocate bigger slices and increase cap accordingly.
> 	cap int
> ```

nit: `s/cap/capacity`

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56838#-:-MMRCFDRCrqhJYFIz5BB:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/colexec/mergejoiner_util.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56838#-MMR6NcoALk1VUPozGJf:-MMRCDRVEXKkCgAgMlcw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c498ae833c300abdcf78384cc20c47bcff7849a7/pkg/sql/colexec/mergejoiner_util.go#L33)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: `s/cap/capacity`
</blockquote></details>

Done.

**Pull request merged**
