### PR TITLE
roachtest: register the 19.2 version

### PR DESCRIPTION
**Pull request by andreimatei**
See individual commits.

### CODE REVIEW

**Comment by andreimatei** [comment]
I've made a mention about updating this map in the release procedure.

**Review by tbg — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37186#-:-LdeVFcz3sFkq_D-Dm2V:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/cmd/roachtest/upgrade.go, line 271 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37186#-LdeVPcH6s4GAtI9CUuF:-LdeVPcH6s4GAtI9CUuG:b-6e7uqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/104daef13c69e0bda64679cd4c308591cc433c92/pkg/cmd/roachtest/upgrade.go#L271)):*
> ```Go
> 	mixedWithVersion, err := r.PredecessorVersion()
> 	if err != nil {
> 		panic(err)
> ```

I don't think the roachtest invocation should panic, we won't get issues posted and may not act quickly. Consider renaming the test to `fmt.Sprintf("upgrade/mixed/%s", clusterSpec)` and put this code in the `Run` method where it can `t.Fatal`.
___
*[pkg/cmd/roachtest/version.go, line 230 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37186#-LdeVv0X5optMx9IHHOH:-LdeVv0X5optMx9IHHOI:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/104daef13c69e0bda64679cd4c308591cc433c92/pkg/cmd/roachtest/version.go#L230)):*
> ```Go
> 	mixedWithVersion, err := r.PredecessorVersion()
> 	if err != nil {
> 		panic(err)
> ```

ditto

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37186)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

___
*[pkg/cmd/roachtest/upgrade.go, line 271 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37186#-LdeVPcH6s4GAtI9CUuF:-Ldfx5MM6NiVGAy9V5yH:b-io6y5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/104daef13c69e0bda64679cd4c308591cc433c92/pkg/cmd/roachtest/upgrade.go#L271)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I don't think the roachtest invocation should panic, we won't get issues posted and may not act quickly. Consider renaming the test to `fmt.Sprintf("upgrade/mixed/%s", clusterSpec)` and put this code in the `Run` method where it can `t.Fatal`.
</blockquote></details>

Done, except I simplified the name of this test to "upgrade".
___
*[pkg/cmd/roachtest/version.go, line 230 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37186#-LdeVv0X5optMx9IHHOH:-Ldfx448-wGEbnG9ueMg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/104daef13c69e0bda64679cd4c308591cc433c92/pkg/cmd/roachtest/version.go#L230)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by tbg — APPROVED** [review]

**Review by tbg — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37186)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

**Pull request merged**
