### PR TITLE
sqlccl: use unsafe key in import sst iteration

### PR DESCRIPTION
**Pull request by dt**
```
Import-8    6.91ms ± 3%    7.16ms ±13%    ~      (p=0.408 n=8+10)

name      old alloc/op   new alloc/op   delta
Import-8    2.48MB ± 1%    2.45MB ± 1%  -1.19%  (p=0.000 n=10+10)

name      old allocs/op  new allocs/op  delta
Import-8     42.8k ± 0%     39.8k ± 0%  -7.00%  (p=0.000 n=10+10)
```

### CODE REVIEW

**Comment by danhhz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/sqlccl/csv.go, line 1189 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17993#-KsivXjD486YNrxZLNKH:-KsivXjD486YNrxZLNKI:bty69iy) ([raw file](https://github.com/cockroachdb/cockroach/blob/241cb2071dcf1789ad5f32c476926c1ed38c1fe8/pkg/ccl/sqlccl/csv.go#L1189)):*
> ```Go
> 			}
> 		}
> 		lastKey := append([]byte(nil), kv.Key.Key.Next()...)
> ```

you can reuse lastKey for even more allocation saving: `lastKey = append(lastKey[:0], kv.Key.Key.Next()...)`

---

*[pkg/storage/engine/disk_map.go, line 63 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17993#-KsivnmlbvCI-whmdeeR:-KsivnmlbvCI-whmdeeS:bbvx787) ([raw file](https://github.com/cockroachdb/cockroach/blob/241cb2071dcf1789ad5f32c476926c1ed38c1fe8/pkg/storage/engine/disk_map.go#L63)):*
> ```Go
> 
> 	UnsafeKey() []byte
> 	// Value returns the current value. The resulting byte slice is still valid
> ```

the comments here seem incorrect

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17993)*

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/ccl/sqlccl/csv.go, line 1189 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17993#-KsivXjD486YNrxZLNKH:-KsixBtPtr_STre2WqBm:b-t7qd9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/241cb2071dcf1789ad5f32c476926c1ed38c1fe8/pkg/ccl/sqlccl/csv.go#L1189)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

you can reuse lastKey for even more allocation saving: `lastKey = append(lastKey[:0], kv.Key.Key.Next()...)`
</blockquote></details>

er, is lastKey assigned more than once?

---

*[pkg/storage/engine/disk_map.go, line 63 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17993#-KsivnmlbvCI-whmdeeR:-Ksiweo2PyOjAGRUNQQG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/241cb2071dcf1789ad5f32c476926c1ed38c1fe8/pkg/storage/engine/disk_map.go#L63)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

the comments here seem incorrect
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17993)*

**Comment by danhhz** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/sqlccl/csv.go, line 1189 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17993#-KsivXjD486YNrxZLNKH:-Ksj-KQRDHBJ6PsNwOCX:b-pmivgc) ([raw file](https://github.com/cockroachdb/cockroach/blob/241cb2071dcf1789ad5f32c476926c1ed38c1fe8/pkg/ccl/sqlccl/csv.go#L1189)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

er, is lastKey assigned more than once?
</blockquote></details>

heh, nevermind

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17993#-:-Ksj-aejRzgyvelQw-b5:bnfp4nl)*

**Comment by mjibson** [comment]
:lgtm: after the comment fixes

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/storage/engine/disk_map.go, line 63 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17993#-Ksj171nx6QlAVmh_5rQ:-Ksj171nx6QlAVmh_5rR:bywy4jj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e067f783092091850be1d2d43a45c5091949fa2/pkg/storage/engine/disk_map.go#L63)):*
> ```Go
> 
> 	// UnsafeKey returns the same value as Key, but the memory is invalidated on
> 	// the next call to {Next,Prev,Seek,SeekReverse,Close}.
> ```

Prev and SeekReverse don't exist in this interface, and it's missing Rewind.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17993#-:-Ksj1ccyHn5MNYbWRf_T:bo50s5c)*

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/sqlccl/csv.go, line 1189 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17993#-KsivXjD486YNrxZLNKH:-Ksj83zu8xpyykuqT9BU:bd3mka0) ([raw file](https://github.com/cockroachdb/cockroach/blob/241cb2071dcf1789ad5f32c476926c1ed38c1fe8/pkg/ccl/sqlccl/csv.go#L1189)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

heh, nevermind
</blockquote></details>

ah, but it _should_ have been -- @danhhz points out that since kv.Key is now backed by the unsafe key, we can't look at it again outside the loop, since we called `Next` to break out of the loop.

Nice catch!

Done.

---

*[pkg/storage/engine/disk_map.go, line 63 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17993#-Ksj171nx6QlAVmh_5rQ:-Ksj8-GgQHU7KmAfu4XZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e067f783092091850be1d2d43a45c5091949fa2/pkg/storage/engine/disk_map.go#L63)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Prev and SeekReverse don't exist in this interface, and it's missing Rewind.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17993)*

**Comment by danhhz** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17993)*

**Pull request merged**
