### PR TITLE
server: adopt for settings rangefeed-backed settingswatcher, remove g…

### PR DESCRIPTION
**Pull request by ajwerner**
…ossip

This commit removes the code which connected the settings to their backing
table via the gossipped system config. Instead it unconditionally enables the
rangefeed-backed `settingswatcher` which was developed to support tenants.

Note that it is rather tested code that has been used in multi-tenant sql
pods for about a year now and all the existing tests still pass.

Release justification: Low risk, high benefit change to existing functionality

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
Actually there's a bit more to do here.

**Comment by ajwerner** [comment]
@RaduBerinde I've rebased this and I think it's ready for a pass. I suspect there's missing testing somewhere. Please let me know what you're looking for.

**Review by RaduBerinde — COMMENTED** [review]
Thanks for working on this.

It feels like we're processing each rangefeed event in two different places and in two different ways (one indirectly, after buffering). What's the benefit of buffering events? Why not just keep `mu.data` up to date in in the main rangefeed callback? That would make everything a lot simpler. I don't think we'd even need to keep track of frontier timestamps anymore - whenever we get an event, we either spawn the async storage task, or if it is running already, we set a flag indicating that it needs to run again (and the task can check that flag and restart).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69269#-:-MrVP6d58ijb3rF9Edi7:b-z9vnzk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @RaduBerinde)

___
*[pkg/server/settingswatcher/settings_watcher.go, line 66 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69269#-MrVFS23DEFI-wwkR1Dx:-MrVFS23DEFI-wwkR1Dy:bc3qd7s) ([raw file](https://github.com/cockroachdb/cockroach/blob/a35cf0ca09bf4c488ed926f23194573c86a3c44f/pkg/server/settingswatcher/settings_watcher.go#L66)):*
> ```Go
> // bootstrap settings state.
> type Storage interface {
> 	WriteKVs(ctx context.Context, kvs []roachpb.KeyValue) error
> ```

[nit] This suggests that we may be writing KVs in batches, whereas IIUC each call is a full snapshot. Maybe `SaveKVs` or `SnapshotKVs`?

We guarantee that one instance of the call will be running at any one time, right? We should advertise that here.
___
*[pkg/server/settingswatcher/settings_watcher.go, line 255 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69269#-MrVH_0W4tPEVdj5ebev:-MrVH_0W4tPEVdj5ebew:b77lx7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/a35cf0ca09bf4c488ed926f23194573c86a3c44f/pkg/server/settingswatcher/settings_watcher.go#L255)):*
> ```Go
> 				return
> 			}
> 		}
> ```

[nit] add a comment here saying that a call was already running and we need to try again.

This singleflight+retry mechanism feels awkward to me (perhaps because each call still spawns an async task separately waiting for what should really be a single process). Wouldn't it be simpler to have at most one async task running, along the lines of:
 - invariant: if `frontierToSave < frontierSaved` then there is an async task running or starting. If `frontierToSave >= frontierSaved` the async task is not running (or it's exiting).
 - Before we forward `frontierToSave`, we check the above condition and if we didn't have an async task running, we start it after the forward.
 - In the async task, we run a loop until frontierSaved >= frontierToSave. The latter can change during the loop, causing more iterations.
___
*[pkg/server/settingswatcher/settings_watcher_external_test.go, line 186 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69269#-MrVRPqh1Badk-HfHweO:-MrVRPqh1Badk-HfHweP:bmo6yor) ([raw file](https://github.com/cockroachdb/cockroach/blob/a35cf0ca09bf4c488ed926f23194573c86a3c44f/pkg/server/settingswatcher/settings_watcher_external_test.go#L186)):*
> ```Go
> func (f *fakeStorage) WriteKVs(ctx context.Context, kvs []roachpb.KeyValue) error {
> 	f.Lock()
> 	defer f.Unlock()
> ```

[nit] should we introduce a random delay here? I want to make sure to test the situation where an event comes in while the async storage task is running. If we do that, we should also assert that only one instance of the method is running at a time (we can increment and defer(decrement) an atomic counter and check that it was 0)

**Review by ajwerner — COMMENTED** [review]
> What's the benefit of buffering events? Why not just keep mu.data up to date in in the main rangefeed callback? That would make everything a lot simpler. 

The complexity exists to ensure that whenever we write out a snapshot of settings, it corresponds to a snapshot which actually existed in the settings table at some point in time. The problem is that updates may come out-of-order. The buffer is a hack to avoid needing to maintain a versioned store for data. I'm not sure it's saving much in the way of complexity. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69269#-:-Mr_ISheDkE08t7dTMjY:b-yibin)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @RaduBerinde)

**Comment by RaduBerinde** [comment]
Huh, the range feed events don't have monotonically increasing timestamps?? That is a huge thing, it should be documented in at least 3 places (the RangeFeed Internal API itself, `kvDB.RangeFeed()`, and in `rangefeed.RangeFeed`).

If we care about the ordering in the settings snapshot, it feels like we should care about it in memory as well (even though the window of potential problems would be much smaller in practice).

I assume that more often than not, we will care about the proper ordering when we write a range feed "client" (which means each use will have to get involved with buffering and frontiers). At the very least, it's much easier to reason about things if you can just get the nice semantics.

So I think we should build a small layer into `rangefeed.RangeFeed` (or maybe even `kvDB.RangeFeed`) that can be used optionally which internally buffers the KV events and provides the nice monotonic guarantee on the callback. We can specify a memory limit after which the range feed errors out.

**Comment by ajwerner** [comment]
> Huh, the range feed events don't have monotonically increasing timestamps??

It has very specific ordering guarantees. It guarantees for that any individual key you will see writes *for the first time* in increasing timestamp order. It makes no statement at all about ordering of events corresponding to different rows. In cockroach, you can have a txn write to row A at t2 and then subsequently a txn writes to row B at t1. To not emit the t2 event until a t1 event becomes impossible would effectively negate the design of rangefeeds.

> That is a huge thing, it should be documented in at least 3 places (the RangeFeed Internal API itself, kvDB.RangeFeed(), and in rangefeed.RangeFeed).

I don't disagree that it is under-documented. Here's a comment which says some things but is far afield from where one might look. https://github.com/cockroachdb/cockroach/blob/707af75d7993f838e8600725271b347136d2f7d2/pkg/ccl/changefeedccl/sink_cloudstorage.go#L84-L100

> If we care about the ordering in the settings snapshot, it feels like we should care about it in memory as well (even though the window of potential problems would be much smaller in practice).

It's a tradeoff. If we wanted to wait for a snapshot, we'd have to wait for the closed timestamp which is on the order of seconds. Even today we don't update the settings atomically with the gossip update, though the window for things to be out of sync is extremely small; the updater is non-atomic. 

One approach to reducing the delay is https://github.com/cockroachdb/cockroach/issues/73399

> So I think we should build a small layer into rangefeed.RangeFeed (or maybe even kvDB.RangeFeed) that can be used optionally which internally buffers the KV events and provides the nice monotonic guarantee on the callback. 

This is what @irfansharif was setting out to do with https://github.com/cockroachdb/cockroach/blob/24465b8c3fa7eadc4dfb9f5e0a1c29a9ecf96b2e/pkg/kv/kvclient/rangefeed/rangefeedbuffer/buffer.go#L32-L36 but I agree it's too low-level. 

> We can specify a memory limit after which the range feed errors out.

Yeah. The data structure can in principle maintain exactly one entry per key while waiting for a checkpoint. Hitting a memory error for these use cases we're intending to use this for ought to be extremely rare and indicative of something pathological. I'm all for it existing as a guard rail, but at least for settings, it feels like the sort of thing where if we use too much ram, we ought to be crashing the server or something drastic like that. Thinking through more complex handling doesn't seem worth it.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm: 

> If we wanted to wait for a snapshot, we'd have to wait for the closed timestamp which is on the order of seconds.

This is another critical detail that should be better advertised, e.g. in the comments for `WithOnFrontierAdvance / OnFrontierAdvance`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69269#-:-MsqMeYP6dHmUr3sElfo:b-tyiw6i)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @RaduBerinde)

___
*[pkg/server/settingswatcher/settings_watcher.go, line 53 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69269#-MsqMpQR0uU4oMAkYAnr:-MsqMpQR0uU4oMAkYAns:b-2c0prz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e8c2c4d37d7ead6cb0826083ace3c3ab4571c26/pkg/server/settingswatcher/settings_watcher.go#L53)):*
> ```Go
> 
> 	// State used to store settings values to disk.
> 	buffer *rangefeedbuffer.Buffer
> ```

Can you add a comment here explaining that we need the buffer because the range feed callbacks can be out-of-order? Also mention that the buffer will hold a few seconds worth of changes in practice.

**Comment by irfansharif** [comment]
> One approach to reducing the delay is #73399

For posterity another would be setting a more aggressive `kv.closed_timestamp.target_duration` over specific tables (we default to 3s): https://github.com/cockroachdb/cockroach/issues/70614#issuecomment-956903381.

**Comment by ajwerner** [comment]
>> One approach to reducing the delay is #73399
>
> For posterity another would be setting a more aggressive kv.closed_timestamp.target_duration over specific tables (we default to 3s): #70614 (comment).

That's a particularly legit idea for the `settings` table. We don't allow transactional writes to that table. If we set it to zero and we implemented the logic to stop tracking point reads to which we've written as mentioned in https://github.com/cockroachdb/cockroach/issues/52768#issue-678435293, then, hopefully, we'd insta-close the range for the settings table. This would also rely on the whole table being in one range, but that is not that farfetched in a future release where we break up the system config span.

**Comment by ajwerner** [comment]
Replacing this with some form of https://github.com/cockroachdb/cockroach/pull/74612. It's much cleaner.

**Pull request closed without merging**
