### PR TITLE
release-23.1: server, tenant: Hot ranges structured logging 

### PR DESCRIPTION
**Pull request by koorosh**
Backport:
  * 1/1 commits from "server, tenant: Hot ranges structured logging for serverless clusters" (#89511)
  * 1/1 commits from "server: fix proper call for StartHotRangesLoggingScheduler" (#101959)

Please see individual PRs for details.

Release justification: bug fixes and low-risk updates to new functionality

/cc @cockroachdb/release

### CODE REVIEW

**Comment by j82w** [comment]
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102123#-NUziy6m-8HHg1unVEeW):*
@kevin-v-ngo or @maryliag is there any concerns about breaking customer's if new events are added to existing pipelines?

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102123)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kevin-v-ngo and @thtruo)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102123#-NUziy6m-8HHg1unVEeW):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

@kevin-v-ngo or @maryliag is there any concerns about breaking customer's if new events are added to existing pipelines?
</blockquote></details>

I don't believe is a problem, as long is not changing existing events (which this doesn't seems to be doing)

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102123)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kevin-v-ngo and @thtruo)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102123#-NUziy6m-8HHg1unVEeW):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I don't believe is a problem, as long is not changing existing events (which this doesn't seems to be doing)
</blockquote></details>

correct, it is new events that doesn't affect existing one.

**Comment by j82w** [comment]
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102123#-NUziy6m-8HHg1unVEeW):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

correct, it is new events that doesn't affect existing one.
</blockquote></details>

@knz or @dhartunian does this need to be disabled by default?

**Comment by dhartunian** [comment]
Frequency seems low enough to me that it's fine.

**Review by maryliag — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102123#-:-NWNLGgi7DS5DxGYLPfo:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian, @kevin-v-ngo, @knz, and @thtruo)

**Pull request merged**
