### PR TITLE
cli: extend `dump` to support dumping multiple tables.

### LINKED ISSUE #8881: cli: dump should allow multi-table backups
The dump command requires a `database` and a `table` argument. The table has to be specified and there is no "all" alias. This means that it's impossible at the moment to obtain a full database dump that preserves consistency of the data across tables.

It's common for transactions to span multiple tables, so ideally the backups should also allow consistency beyond a single table.

### PR DESCRIPTION
**Pull request by knz**
With this patch `dump` now both accepts multiple table names as
argument, which dumps all the specified tables, or none at all, which
indicates to dump all tables.

All the tables are dumped at the same "logical" instant to capture a consistent mutual state.

It also adds a new flag `--dump-mode` to choose either schema+data
(`--dump-mode=both`, which is default), schema only
(`--dump-mode=schema`) or data only (`--dump-mode=data`).

Fixes #8881.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12759)

### CODE REVIEW

**Comment by mjibson** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/cli/cli_test.go, line 745 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759#-Ka1Fiipn9qO8ZkhATii:-Ka1Fiiqm1-IIHkMYhIx:b-p2fma8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389e4cfb6c506dfd58a5177e89c0bb687c03228/pkg/cli/cli_test.go#L745)):*
> ```Go
> 	// 	FAMILY "primary" (x, y, rowid)
> 	// );
> 	// CREATE TABLE g (
> ```

A newline between CREATEs would be nice.

---

*[pkg/cli/dump.go, line 35 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759#-Ka1CDrHc0sIsg51StzN:-Ka1CDrHc0sIsg51StzO:b-f5vin2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389e4cfb6c506dfd58a5177e89c0bb687c03228/pkg/cli/dump.go#L35)):*
> ```Go
> // dumpCmd dumps SQL tables.
> var dumpCmd = &cobra.Command{
> 	Use:   "dump [options] <database> <table> <table> <table>...",
> ```

I think: `dump [options] <database> [<table> [<table2>...]]` would be the way to express this, based on existing `Use` strings.

---

*[pkg/cli/dump.go, line 72 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759#-Ka1Eo2JBmt8bQUKSbXA:-Ka1Eo2JBmt8bQUKSbXB:b-696jrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389e4cfb6c506dfd58a5177e89c0bb687c03228/pkg/cli/dump.go#L72)):*
> ```Go
> 
> 	for _, md := range mds {
> 		if err := dumpCreateTable(os.Stdout, md); err != nil {
> ```

Does it make sense to dump create tables immediately before the table data instead of all the creates up top? That's how I've seen other DBs write backup files.

---

*[pkg/cli/dump.go, line 174 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759#-Ka1EIHC_70nYLh3V79j:-Ka1DUPLaKahlLjN3T0X:b-xrthj4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389e4cfb6c506dfd58a5177e89c0bb687c03228/pkg/cli/dump.go#L174)):*
> ```Go
> 	// descriptors which is a problem in multi-tenancy.
> 
> 	if err := conn.Exec(fmt.Sprintf("SET DATABASE = %s", dbName), nil); err != nil {
> ```

Should this be set higher and only once, since only one database should ever be accessed? Should be safe since we're in a transaction here.

---

*[pkg/cli/dump.go, line 289 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759#-Ka1F76s7ZkGGQOrGLQO:-Ka1F76s7ZkGGQOrGLQP:bisipx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389e4cfb6c506dfd58a5177e89c0bb687c03228/pkg/cli/dump.go#L289)):*
> ```Go
> 	// Build the SELECT query.
> 	var sbuf bytes.Buffer
> 	fmt.Fprintf(&sbuf, "SELECT %s, %s FROM %s@%s AS OF SYSTEM TIME %s",
> ```

Why is using * bad?

---

*[pkg/cli/dump.go, line 396 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759#-Ka1FLud52JFoIEjfT3x:-Ka1FLud52JFoIEjfT3y:bc5toey) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389e4cfb6c506dfd58a5177e89c0bb687c03228/pkg/cli/dump.go#L396)):*
> ```Go
> 			break
> 		}
> 		fmt.Fprintf(w, "\nINSERT INTO %s(%s) VALUES", md.name.TableName, md.columnNames)
> ```

Space needed before `(` is usually how I see this formatted. But maybe I've been doing it wrong my entire life.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759)*

**Comment by knz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/cli/dump.go, line 35 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759#-Ka1CDrHc0sIsg51StzN:-Ka1ma6YEnvOXGxU8DVp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389e4cfb6c506dfd58a5177e89c0bb687c03228/pkg/cli/dump.go#L35)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I think: `dump [options] <database> [<table> [<table2>...]]` would be the way to express this, based on existing `Use` strings.
</blockquote></details>

Done.

---

*[pkg/cli/dump.go, line 72 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759#-Ka1Eo2JBmt8bQUKSbXA:-Ka1mfA3QLGMo7-G7rDM:b-1vpp20) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389e4cfb6c506dfd58a5177e89c0bb687c03228/pkg/cli/dump.go#L72)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Does it make sense to dump create tables immediately before the table data instead of all the creates up top? That's how I've seen other DBs write backup files.
</blockquote></details>

Yes that's a design consideration, I had to think a while about it.
My reasoning: from a UX perspective it's terrible if there's any problem creating the schema: suppose you have two very large tables one after the other, and you have to wait the first load to realize that there's a schema problem with the 2nd table...
Of course we could make it configurable too. Would it be worthwhile to add a flag to dump each table to its own file?

---

*[pkg/cli/dump.go, line 174 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759#-Ka1EIHC_70nYLh3V79j:-Ka1n696Xbvvp0Et40MW:bb7hxo5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389e4cfb6c506dfd58a5177e89c0bb687c03228/pkg/cli/dump.go#L174)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Should this be set higher and only once, since only one database should ever be accessed? Should be safe since we're in a transaction here.
</blockquote></details>

My reasoning is that with how the code is organized now, we can easily add another mode that dumps tables from multiple databases. In this case you'd want to reset the database for each table.

---

*[pkg/cli/dump.go, line 289 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759#-Ka1F76s7ZkGGQOrGLQO:-Ka1nxmyC77hehYfJTtj:b-ebrn0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389e4cfb6c506dfd58a5177e89c0bb687c03228/pkg/cli/dump.go#L289)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Why is using * bad?
</blockquote></details>

There's no API guarantee that SHOW COLUMNS returns columns in the same order that `*` expands to. We could make it part of the specification of SHOW COLUMNS but I figured this way decouples the two and is future-proof.

---

*[pkg/cli/dump.go, line 396 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759#-Ka1FLud52JFoIEjfT3x:-Ka1oSBUloFSWiw7sONE:b-hnzpev) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389e4cfb6c506dfd58a5177e89c0bb687c03228/pkg/cli/dump.go#L396)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Space needed before `(` is usually how I see this formatted. But maybe I've been doing it wrong my entire life.
</blockquote></details>

I've seen it either way. But your way is fine by me :)

---

*[pkg/cli/cli_test.go, line 745 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759#-Ka1Fiipn9qO8ZkhATii:-Ka1m_JGOOSjKwz-7-jw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389e4cfb6c506dfd58a5177e89c0bb687c03228/pkg/cli/cli_test.go#L745)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

A newline between CREATEs would be nice.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759#-:-Ka3cp2j_nGJxyVR9whz:bnfp4nl)*

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/cli/dump.go, line 72 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759#-Ka1Eo2JBmt8bQUKSbXA:-Ka4CdQRlVfJeI2LNd-V:bdply3g) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389e4cfb6c506dfd58a5177e89c0bb687c03228/pkg/cli/dump.go#L72)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Yes that's a design consideration, I had to think a while about it.
My reasoning: from a UX perspective it's terrible if there's any problem creating the schema: suppose you have two very large tables one after the other, and you have to wait the first load to realize that there's a schema problem with the 2nd table...
Of course we could make it configurable too. Would it be worthwhile to add a flag to dump each table to its own file?

</blockquote></details>

Many dump tools allow `schema-only` or `data-only` dumps which is potentially similar -- you could use that if you wanted to just quickly do structure first, then move on to data.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759)*

**Comment by knz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/cli/dump.go, line 72 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759#-Ka1Eo2JBmt8bQUKSbXA:-Ka4FQ1hsJT6z-DkS8A6:bvsoegr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389e4cfb6c506dfd58a5177e89c0bb687c03228/pkg/cli/dump.go#L72)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Many dump tools allow `schema-only` or `data-only` dumps which is potentially similar -- you could use that if you wanted to just quickly do structure first, then move on to data.
</blockquote></details>

Ok but do our tools allow this? Are you suggesting to add these flags? Should I file a followup issue for that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759)*

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/cli/dump.go, line 72 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759#-Ka1Eo2JBmt8bQUKSbXA:-Ka4FaBQthljQWLm9aQA:b-brskss) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389e4cfb6c506dfd58a5177e89c0bb687c03228/pkg/cli/dump.go#L72)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Ok but do our tools allow this? Are you suggesting to add these flags? Should I file a followup issue for that?
</blockquote></details>

I don't have strong opinions on it, but it might be nice to have w.r.t. your concerns about separating time-consuming data loading from the structure creation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759)*

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/cli/dump.go, line 72 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759#-Ka1Eo2JBmt8bQUKSbXA:-Ka4GCsOLSwRWd4CgQEC:bqcdyff) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389e4cfb6c506dfd58a5177e89c0bb687c03228/pkg/cli/dump.go#L72)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I don't have strong opinions on it, but it might be nice to have w.r.t. your concerns about separating time-consuming data loading from the structure creation.
</blockquote></details>

Either way, I like dumping all structure first, so that any failures to create happen fast, before hours of loading.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759)*

**Comment by knz** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/cli/dump.go, line 72 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759#-Ka1Eo2JBmt8bQUKSbXA:-Ka753tHXUlamlTYhTvA:b-px8442) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389e4cfb6c506dfd58a5177e89c0bb687c03228/pkg/cli/dump.go#L72)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Either way, I like dumping all structure first, so that any failures to create happen fast, before hours of loading.
</blockquote></details>

@dt I added a flag to do what you suggested. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759)*

**Comment by mjibson** [comment]
Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/cli/cliflags/flags.go, line 141 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759#-Ka8jcy7jeaIWjTIwqZY:-Ka8jcy7jeaIWjTIwqZZ:bbixalw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24774c3808196d430e0d4e0c32e0106d303e262/pkg/cli/cliflags/flags.go#L141)):*
> ```Go
> 		Description: `
> What to dump. "schema" dumps the schema only. "data" dumps the data only.
> "both" (default) dumps the schema then the data.`,
> ```

I don't see how `both` is set as the default , and there's no test for it. Could you add a test to verify it's the default?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759)*

**Comment by knz** [comment]
Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/cli/cliflags/flags.go, line 141 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759#-Ka8jcy7jeaIWjTIwqZY:-Ka9WEHdUKx7w_cqPHRJ:b-8iy9bq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24774c3808196d430e0d4e0c32e0106d303e262/pkg/cli/cliflags/flags.go#L141)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I don't see how `both` is set as the default , and there's no test for it. Could you add a test to verify it's the default?
</blockquote></details>

I don't get it. TestDumpMultiTable calls dump on multiple tables without giving the flag and is thus using the default. What's missing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/cli/cliflags/flags.go, line 141 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759#-Ka8jcy7jeaIWjTIwqZY:-KaDq40yfXR3jD8bNX6V:bg5iyvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24774c3808196d430e0d4e0c32e0106d303e262/pkg/cli/cliflags/flags.go#L141)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't get it. TestDumpMultiTable calls dump on multiple tables without giving the flag and is thus using the default. What's missing?
</blockquote></details>

Yup, I missed that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12759#-:-KaDq9I5G9EXUzR40JsP:bnfp4nl)*

**Pull request merged**
