### PR TITLE
raft: integrate check quorum with leader fortification 

### LINKED ISSUE #125353: raft: integrate fortification with CheckQuorum
**Describe the problem**

Part of https://github.com/cockroachdb/cockroach/issues/123847

A leader should not be allowed to step down, even if `CheckQuorum` would indicate it should, until its QSE hasn't expired. This needs integration.

Jira issue: CRDB-39404

Epic CRDB-37522

### PR DESCRIPTION
**Pull request by arulajmani**
This commit ensures that a leader only steps down due to check quorum
if its LeadSupportUntil has expired.

closes https://github.com/cockroachdb/cockroach/issues/125353

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130286)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/raft/raft.go` line 1439 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130286#-O6E2bBLAZFbHdloL-QH:-O6E2bBLAZFbHdloL-QI:b-dm9c6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3adc7f6b1ed60a6075368aedd86aa1e70e34fcd/pkg/raft/raft.go#L1439)):*
> ```Go
> 		if !r.trk.QuorumActive() {
> 			r.logger.Debugf(
> 				"%x has not received messages from a quorum peers in the last election timeout", r.id,
> ```

"quorum of peers"
___
*[`pkg/raft/raft.go` line 1445 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130286#-O6DzLxC69JKeSrDWTNC:-O6DzLxC69JKeSrDWTND:b-44mu0n) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3adc7f6b1ed60a6075368aedd86aa1e70e34fcd/pkg/raft/raft.go#L1445)):*
> ```Go
> 			r.logger.Debugf("%x does not have store liveness support from a quorum of peers", r.id)
> 		}
> 		if !r.trk.QuorumActive() && !r.supportTracker.QuorumActive() {
> ```

These `QuorumActive` conditions aren't cheap to compute, so we should avoid computing them more than necessary. Can we extract a pair of variables? `quorumActiveByHeartbeats` and `quorumActiveByFortification`?
___
*[`pkg/raft/rafttest/interaction_env_handler_raftstate.go` line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130286#-O6Dysol2zlzcJvijsWA:-O6Dysol2zlzcJvijsWB:bzczw4z) ([raw file](https://github.com/cockroachdb/cockroach/blob/efdf592063560a0a4e411884ad655b3f31289bf7/pkg/raft/rafttest/interaction_env_handler_raftstate.go#L51)):*
> ```Go
> 			voterStatus = "(Non-Voter)"
> 		}
> 		fmt.Fprintf(env.Output, "%d: %s %s Term:%d Lead:%d LeadEpoch: %d\n",
> ```

There is no space between the field name and value (`Term:%d`, `Lead:%d`) in the other cases, so we should follow the lead with `LeadEpoch:%d` .
___
*[`pkg/raft/tracker/supporttracker.go` line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130286#-O6E2D5k6HpKYvnyBz58:-O6E2D5k6HpKYvnyBz59:b-m87t3r) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3adc7f6b1ed60a6075368aedd86aa1e70e34fcd/pkg/raft/tracker/supporttracker.go#L84)):*
> ```Go
> }
> 
> // QuorumActive returns whether the leader's currently supported by a quorum or
> ```

nit: "leader is"
___
*[`pkg/raft/testdata/fortification_checkquorum.txt` line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130286#-O6E2ugr40-njyV8ltG3:-O6E2ugr40-njyV8ltG4:b87ih2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3adc7f6b1ed60a6075368aedd86aa1e70e34fcd/pkg/raft/testdata/fortification_checkquorum.txt#L28)):*
> two tick-election twice

Should this be "to tick-election twice"

**Review by arulajmani — COMMENTED** [review]
RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130286#-:-O6bRP6E7Gm5otQ_1oek:bb72pd0)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/raft/raft.go` line 1445 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130286#-O6DzLxC69JKeSrDWTNC:-O6bQQ53BIXqZhD1-RAZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3adc7f6b1ed60a6075368aedd86aa1e70e34fcd/pkg/raft/raft.go#L1445)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

These `QuorumActive` conditions aren't cheap to compute, so we should avoid computing them more than necessary. Can we extract a pair of variables? `quorumActiveByHeartbeats` and `quorumActiveByFortification`?
</blockquote></details>

Done.
___
*[`pkg/raft/testdata/fortification_checkquorum.txt` line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130286#-O6E2ugr40-njyV8ltG3:-O6bQsdo7J9W8buSYyeV:bi91ff2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3adc7f6b1ed60a6075368aedd86aa1e70e34fcd/pkg/raft/testdata/fortification_checkquorum.txt#L28)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> two tick-election twice

Should this be "to tick-election twice"
</blockquote></details>

Yup; fixed.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 18 of 18 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130286#-:-O6cQjQV4iiZ1CYeoOLO:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by arulajmani** [comment]
Thanks! 

bors r=nvanbenschoten

**Pull request merged**
