### PR TITLE
storage: unexport TimestampCache and methods

### PR DESCRIPTION
**Pull request by petermattis**
Performed via go-rename.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6704)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM

**Comment by tschottdorf** [comment]
Reducing visibility into internals in `godoc` is one thing, but it's not clear internally which methods are internal and which ones represent the API which is to be used from `*Replica`. I don't think blindly unexporting everything that can be unexported makes a lot of sense. It should be obvious that I'm supposed to call `AddRequest` to add something to the cache, for example. I think that can be achieved by keeping `timestampCache` unexported, but by exporting some of its methods (or does that trigger a linter)? Really the timestamp cache should be in its own package to define the interface better, but I'm not going to advocate for that.

**Comment by petermattis** [comment]
Placing timestamp cache in its own package seems premature until there is a second user. I can revert the unexporting of `{AddRequest,ExpandRequests,GetMax{Read,Write},MergeInto}` as those are the "public" interface to `TimestampCache`. Sound good?

**Comment by bdarnell** [comment]
+1 to unexporting the type but leaving the methods exported.

I think that moving parts of the storage package into subpackages would make sense even without a second user. That package is so large that it would be good to get some privacy enforcement between its components (although getting there from this point may be more trouble than it's worth).

**Comment by tschottdorf** [comment]
SGTM

On Mon, May 16, 2016 at 1:41 PM Ben Darnell <notifications@github.com>
wrote:

> +1 to unexporting the type but leaving the methods exported.
>
> I think that moving parts of the storage package into subpackages would
> make sense even without a second user. That package is so large that it
> would be good to get some privacy enforcement between its components
> (although getting there from this point may be more trouble than it's
> worth).
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/6704#issuecomment-219492237>
>
-- 

-- Tobias

**Comment by petermattis** [comment]
Updated. PTAL.

**Comment by tschottdorf** [comment]
LGTM, thanks!

**Pull request merged**
