### PR TITLE
storage/bulk: attempt to avoid making range-spanning SSTs

### PR DESCRIPTION
**Pull request by dt**
SSTables that span a range boundry cannot be added and must be rebuilt
on error and retried. This is likely expensive -- SSTables are intended
to be large and have many keys, so having to build copies is additional
memory overhead and iteration, making it an operation we would prefer to
avoid if we can.

By looking at a range cache, we can attempt to flush our SST before
adding a key beyond the range currently being added to.

Release note: none.

### CODE REVIEW

**Comment by tbg** [comment]
Is this fixing something or does it relate to some issue? Just curious.

**Comment by dt** [comment]
No filed issue -- currently we assume (and observe) that the non-overlapping SSTs added by RESTORE and IMPORT, which both split explicitly before adding, to empty key space, very rarely hit a split.

However, when we start using addsst to add to non-empty keyspace, it will already has its own splits, the data we will be will have keys that span many ranges (i.e. when produced by an index backfill chunk or the hypothetical no-sort IMPORT we've spitballed), so this becomes a bigger deal.

**Comment by tbg** [comment]
Thanks David, makes sense.

**Review by vivekmenezes — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33722)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/bulk/sst_batcher.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33722#-LWHH8wS82e0ZCHhlCMe:-LWHH8wS82e0ZCHhlCMf:b-97vz54) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d8f29eccac8fd9841d9b022b72645d6e0d3f231/pkg/storage/bulk/sst_batcher.go#L42)):*
> ```Go
> // non-nil, it will be used to minimize retries due to SSTs that span ranges.
> func MakeFixedTimestampSSTBatcher(
> 	db *client.DB, rangeCache *kv.RangeDescriptorCache, flushBytes int64, timestamp hlc.Timestamp,
> ```

would we ever need to pass a nil rangeCache?
___
*[pkg/storage/bulk/sst_batcher.go, line 141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33722#-LWHGbnaCmfG1FarO6IU:-LWHGbnaCmfG1FarO6IV:b-mxe5ar) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d8f29eccac8fd9841d9b022b72645d6e0d3f231/pkg/storage/bulk/sst_batcher.go#L141)):*
> ```Go
> 			log.Warningf(ctx, "failed to get RKey for flush key lookup")
> 		} else {
> 			r, err := b.rc.GetCachedRangeDescriptor(k, false)
> ```

false /* inverted */
___
*[pkg/storage/bulk/sst_batcher.go, line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33722#-LWHIzYc55pY2uNYRYEp:-LWHIzYc55pY2uNYRYEq:b660o24) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d8f29eccac8fd9841d9b022b72645d6e0d3f231/pkg/storage/bulk/sst_batcher.go#L154)):*
> ```Go
> 
> 	if b.flushKey != nil {
> 		if b.flushKey.Compare(nextKey) <= 0 {
> ```

combine the two ifs with an &&
___
*[pkg/storage/bulk/sst_batcher_test.go, line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33722#-LWHJcFJ1dxKBjbytGw3:-LWHJcFJ1dxKBjbytGw4:b-1zl89s) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d8f29eccac8fd9841d9b022b72645d6e0d3f231/pkg/storage/bulk/sst_batcher_test.go#L176)):*
> ```Go
> 					}
> 				}
> 			}
> ```

finding the log message is rather unfortunate. Can you add splitRetries to the testCase?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33722)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/bulk/sst_batcher.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33722#-LWHH8wS82e0ZCHhlCMe:-LWMKnDRD6mAdqe8f95w:b-2tlhni) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d8f29eccac8fd9841d9b022b72645d6e0d3f231/pkg/storage/bulk/sst_batcher.go#L42)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

would we ever need to pass a nil rangeCache?
</blockquote></details>

RESTORE does not currently pass it one, and doesn't really expect its SSTs to span splits since it explicitly splits empty ranges, so it doesn't really need to. 
___
*[pkg/storage/bulk/sst_batcher.go, line 141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33722#-LWHGbnaCmfG1FarO6IU:-LWMPXyg5JSz2XDOMtyG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d8f29eccac8fd9841d9b022b72645d6e0d3f231/pkg/storage/bulk/sst_batcher.go#L141)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

false /* inverted */
</blockquote></details>

Done.
___
*[pkg/storage/bulk/sst_batcher.go, line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33722#-LWHIzYc55pY2uNYRYEp:-LWMPXXo5xN1QRUxWV48:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d8f29eccac8fd9841d9b022b72645d6e0d3f231/pkg/storage/bulk/sst_batcher.go#L154)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

combine the two ifs with an &&
</blockquote></details>

Done.
___
*[pkg/storage/bulk/sst_batcher_test.go, line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33722#-LWHJcFJ1dxKBjbytGw3:-LWIy2t01LZi9Gwe_9Hn:b2xcpup) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d8f29eccac8fd9841d9b022b72645d6e0d3f231/pkg/storage/bulk/sst_batcher_test.go#L176)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

finding the log message is rather unfortunate. Can you add splitRetries to the testCase?
</blockquote></details>

we're searching the trace to determine if we retried -- the test case can tell us if we expect to (or we can derive it from the test case), but to verify the actual number of retires matches the expected retries, we need to determine how many actual retries we did and since they're done automatically internally, it is hard to observe them from outside. Inspecting the trace provides a window into what we did that allows avoiding plumbing though a testing hook or something.  Added a comment to this effect to the test.

**Review by tbg — APPROVED** [review]
LGTM on range descriptor cache usage!

**Pull request merged**
