### PR TITLE
go.mod: bump datadriven to e384cf455877

### PR DESCRIPTION
**Pull request by wenyihu6**
```
e384cf4 Merge pull request #45 from wenyihu6/add-float64arr
f4b8e52 add scan implementation for float64, time.Duration, and []float64
```
Release Note: None
Epic: None

### CODE REVIEW

**Review by kvoli — COMMENTED** [review]
This LGTM, but I also haven't added/reviewed a go mod bump before.

@irfansharif  could you be a second reviewer here?

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107964#-:-NamlMWmEtqYwHbW9KeL:bwdr76m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107964#-NamktUM38j7o77JqBtF):*
Coulld you include the list of commits from datadriven being added here, and also the PR message?

I'm thinking something similar to https://github.com/cockroachdb/cockroach/pull/94096/commits/12ed6bc0e5b7d00e11e0a654a8f2ef0fab883e45

**Review by irfansharif — APPROVED** [review]
LGTM, I assume you just did "go get github.com/cockroachdb/datadriven@latest; go mod tidy; dev gen bazel --mirror", right? https://github.com/cockroachdb/cockroach/blob/master/build/README.md#installing-a-new-dependency BTW are the steps I follow.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107964#-:-NamliI0DJE8kTKGVBBs:bq6p79s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @wenyihu6)

**Review by kvoli — APPROVED** [review]

**Comment by wenyihu6** [comment]
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107964#-NamktUM38j7o77JqBtF):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Coulld you include the list of commits from datadriven being added here, and also the PR message?

I'm thinking something similar to https://github.com/cockroachdb/cockroach/pull/94096/commits/12ed6bc0e5b7d00e11e0a654a8f2ef0fab883e45
</blockquote></details>

Done.

**Comment by wenyihu6** [comment]
TFTRs!

bors r=kvoli,irfansharif

**Pull request merged**
