### PR TITLE
kvserver: fix bug in ephemeral app batch

### LINKED ISSUE #94409: roachtest: kv/contention/nodes=4 failed
roachtest.kv/contention/nodes=4 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8127821?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8127821?buildTab=artifacts#/kv/contention/nodes=4) on master @ [64e4fc9faa4e0ab19fe5ba78f053bc2b1390cb5e](https://github.com/cockroachdb/cockroach/commits/64e4fc9faa4e0ab19fe5ba78f053bc2b1390cb5e):

```
test artifacts and logs in: /artifacts/kv/contention/nodes=4/run_1
(cluster.go:1933).Run: output in run_075158.753543425_n5_workload_run_kv: ./workload run kv --init --secondary-index --duration=1h0m0s --cycle-length=512 --concurrency=128 --batch=4 --splits=4 {pgurl:1-4} returned: COMMAND_PROBLEM: exit status 1
(monitor.go:127).Wait: monitor failure: monitor task failed: t.Fatal() was called
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*kv/contention/nodes=4.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-22877

Epic CRDB-18656

### PR DESCRIPTION
**Pull request by tbg**
A bug was introduced recently[^1] which could lead to commands being
early-acked despite ultimately being rejected during command
application. The reason for this was that we previously updated
the lease applied index of the ephemeral batch and didn't any more,
meaning that commands that would fail the MaxLeaseIndex check on the
actual apply batch could erroneously pass it on the ephemeral batch.

Actually, I believe that change only made an existing bug (or at least
semantic incorrectness) more common: it was removing that update
altogether, but the old code blindly updated the MaxLeaseIndex, which
also doesn't seem correct as not all commands (in particular leases)
specify it in the first place. So conceivably, a command that would
be rejected could have reset the MaxLeaseIndex and then allowed a
later command that should also have been rejected to pass.

I think this was mostly theoretical in nature since we only batch
"trivial" commands but this PR improves the update to only occur
for non-rejected commands.

A regression test is added.

Thanks to Nathan for bisecting and diagnosis.

No release note because unreleased.

Fixes #94409.

[^1]: https://github.com/cockroachdb/cockroach/commit/e61de155017a1821d08ba0a414967927adabe0eb#diff-0fd06523f1f485024aef0c7a11d3472945d5ac7cf228d6007b2475ccf6f44cd6L795

Epic: CRDB-220
Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm: 

> Actually, I believe that change only made an existing bug (or at least
> semantic incorrectness) more common: it was removing that update
> altogether, but the old code blindly updated the MaxLeaseIndex, which
> also doesn't seem correct as not all commands (in particular leases)
> specify it in the first place. So conceivably, a command that would
> be rejected could have reset the MaxLeaseIndex and then allowed a
> later command that should also have been rejected to pass.
>
> I think this was mostly theoretical in nature since we only batch
> "trivial" commands

Right, we were only batching trivial commands that could not affect the outcome of later commands (other than through the lease applied index check). Admin operations like splits and especially lease requests have more complicated side effects, so we never consider them or entries later than them for early ack-ing. In fact, we never batch them at all.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94930#-:-NLMc-2v43EaYyDRnmRx:b-dshtc4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @pavelkalinnikov and @tbg)

___
*[`pkg/kv/kvserver/replica_app_batch.go` line 768 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94930#-NLMcS2d24sES4z6OjcZ:-NLMcS2d24sES4z6Ojc_:b-twbd57) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b1c02f8de5599ae3fa079efa892b78e53f9b8f4/pkg/kv/kvserver/replica_app_batch.go#L768)):*
> ```Go
> 	fr = replicaApplyTestingFilters(ctx, mb.r, cmd, fr)
> 	cmd.ForcedErrResult = fr
> 	if !cmd.Rejected() && cmd.LeaseIndex > mb.state.LeaseAppliedIndex {
> ```

Should we change this to exactly mirror the logic in `replicaAppBatch.stageTrivialReplicatedEvalResult`?

**Comment by tbg** [comment]
Let me know if you see a nice way of doing that and I'll send a follow-up, but this didn't seem trivial to me. The "real" code relies on the command having been cleared if it has been rejected but the ephemeral batch here is sort of weird already in that it mutates the command (assigning the results of the forced err check), but it seems even weirder if it cleared it out (maybe I'm wrong?).

TFTR!

bors r=nvanbenschoten

**Comment by erikgrinaker** [comment]
bors single on

**Comment by rail** [comment]
bors r-
We have temporarily disabled bors for merges. Please merge the PR manually when all required checks pass.

**Comment by rail** [comment]
bors r-
We have temporarily disabled bors for merges. Please merge the PR manually when all required checks pass.

**Pull request merged**
