### PR TITLE
scripts: Add MemorySanitizer support to {gce,az}workers

### PR DESCRIPTION
**Pull request by bdarnell**
This requires a custom build of libc++ and using the standard malloc instead of jemalloc.

Fix a false positive in `storage/engine/rocksdb`. Other than this issue, our test suite is now msan-clean.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13047)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[scripts/bootstrap-debian.sh, line 24 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13047#-Kb6o7itEExXej_L3WOg:-Kb6o7itEExXej_L3WOh:bh4mdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/11a071aa00acd672187f08fafb2867a2334136db/scripts/bootstrap-debian.sh#L24)):*
> ```Shell
> (cd ~/libcxx_msan &&
> cmake ../llvm -DCMAKE_BUILD_TYPE=Release -DLLVM_USE_SANITIZER=Memory -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ &&
> make cxx -j12)
> ```

Not sure about the Azure worker, but the GCE worker has 24 CPUs. This could be `-j24`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13047#-:-Kb6oooC5cGS9ekPStdM:bnfp4nl)*

**Comment by tamird** [comment]
:lgtm: except for building libc++ from HEAD

---

Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[scripts/bootstrap-debian.sh, line 17 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13047#-Kb76_fT99mCmBB6G9_s:-Kb76_fT99mCmBB6G9_t:b-og46xs) ([raw file](https://github.com/cockroachdb/cockroach/blob/11a071aa00acd672187f08fafb2867a2334136db/scripts/bootstrap-debian.sh#L17)):*
> ```Shell
> # Install an msan-enabled build of libc++, following instructions from
> # https://github.com/google/sanitizers/wiki/MemorySanitizerLibcxxHowTo
> svn co -q http://llvm.org/svn/llvm-project/llvm/trunk ~/llvm
> ```

```
mkdir llvm && curl -sfSL http://releases.llvm.org/3.9.1/llvm-3.9.1.src.tar.xz | tar --strip-components=1 -C llvm -xJ
mkdir llvm/projects/libcxx && curl -sfSL http://releases.llvm.org/3.9.1/libcxx-3.9.1.src.tar.xz | tar --strip-components=1 -C llvm/projects/libcxx -xJ
mkdir llvm/projects/libcxxabi && curl -sfSL http://releases.llvm.org/3.9.1/libcxxabi-3.9.1.src.tar.xz | tar --strip-components=1 -C llvm/projects/libcxxabi -xJ
```

---

*[scripts/with-msan, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13047#-Kb7745YWkN4qSf-TTz0:-Kb7745YWkN4qSf-TTz1:b-8elbsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/11a071aa00acd672187f08fafb2867a2334136db/scripts/with-msan#L1)):*
> ```
> #!/bin/sh
> ```

call this file `.sh`? -- at least, if you don't, reviewable gets confused about the syntax.

---

*[scripts/with-msan, line 17 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13047#-Kb77ExVTbpOWoFeHdcz:-Kb77ExVTbpOWoFeHdd-:bt2g9wj) ([raw file](https://github.com/cockroachdb/cockroach/blob/11a071aa00acd672187f08fafb2867a2334136db/scripts/with-msan#L17)):*
> ```
> export CC=clang
> export CXX=clang++
> export CGO_CPPFLAGS="-fsanitize=memory -fsanitize-memory-track-origins -fno-omit-frame-pointer -I${HOME}/libcxx_msan/include -I${HOME}/libcxx_msan/include/c++/v1"
> ```

don't you need `-nostdlib`?

---

*[scripts/with-msan, line 21 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13047#-Kb78JCmKICs5HWgcopP:-Kb78JCmKICs5HWgcopQ:b-dq0hs3) ([raw file](https://github.com/cockroachdb/cockroach/blob/11a071aa00acd672187f08fafb2867a2334136db/scripts/with-msan#L21)):*
> ```
> 
> # Runtime variable (needed to run anything built with the above config)
> export LD_LIBRARY_PATH=${HOME}/libcxx_msan/lib
> ```

I think you can use `-Wl,-rpath,${HOME}/libcxx_msan/lib` in `CGO_LDFLAGS` instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13047#-:-Kb76utijC4uTtepuqcF:b-xcwsvj)*

**Comment by bdarnell** [comment]
Review status: 1 of 4 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[scripts/bootstrap-debian.sh, line 17 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13047#-Kb76_fT99mCmBB6G9_s:-KbAojwvZfT3W8k5LCbj:b-667cnl) ([raw file](https://github.com/cockroachdb/cockroach/blob/11a071aa00acd672187f08fafb2867a2334136db/scripts/bootstrap-debian.sh#L17)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

```
mkdir llvm && curl -sfSL http://releases.llvm.org/3.9.1/llvm-3.9.1.src.tar.xz | tar --strip-components=1 -C llvm -xJ
mkdir llvm/projects/libcxx && curl -sfSL http://releases.llvm.org/3.9.1/libcxx-3.9.1.src.tar.xz | tar --strip-components=1 -C llvm/projects/libcxx -xJ
mkdir llvm/projects/libcxxabi && curl -sfSL http://releases.llvm.org/3.9.1/libcxxabi-3.9.1.src.tar.xz | tar --strip-components=1 -C llvm/projects/libcxxabi -xJ
```
</blockquote></details>

Unfortunately, rocksdb 4.11 doesn't build with libcxx 3.9 (due to silly header hygiene issues: facebook/rocksdb#1233). I'm leaving the svn checkouts for now with a comment to switch after we upgrade to rocksdb 5.0.

---

*[scripts/bootstrap-debian.sh, line 24 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13047#-Kb6o7itEExXej_L3WOg:-KbAomAWly8i07ZuFm1B:b-4l6ox6) ([raw file](https://github.com/cockroachdb/cockroach/blob/11a071aa00acd672187f08fafb2867a2334136db/scripts/bootstrap-debian.sh#L24)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Not sure about the Azure worker, but the GCE worker has 24 CPUs. This could be `-j24`. 
</blockquote></details>

Changed to 16, which is what we have on azure. (this is also not a large package - building it is faster than the `cmake` step above (which is like `./configure`))

---

*[scripts/with-msan, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13047#-Kb7745YWkN4qSf-TTz0:-KbAozPLVVXaEd2V9JsH:bbxdvbj) ([raw file](https://github.com/cockroachdb/cockroach/blob/11a071aa00acd672187f08fafb2867a2334136db/scripts/with-msan#L1)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

call this file `.sh`? -- at least, if you don't, reviewable gets confused about the syntax.
</blockquote></details>

I'd rather not expose that level of implementation detail as a part of the command interface - I almost made this a function in `.bashrc`. 

---

*[scripts/with-msan, line 17 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13047#-Kb77ExVTbpOWoFeHdcz:-KbAp9nGrktAI5Ap9FAc:b-9x2nm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/11a071aa00acd672187f08fafb2867a2334136db/scripts/with-msan#L17)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

don't you need `-nostdlib`?
</blockquote></details>

Apparently not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13047)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13047)*

**Pull request merged**
