### PR TITLE
pkg/ui: Visually suport nested tags in trace UI

### PR DESCRIPTION
**Pull request by benbardin**
Note that this design is not final - our intention is to land now, and learn and iterate over the next few months.

Screen Shot 2022-06-27 at 6 11 13 PM
Screen Shot 2022-06-27 at 6 11 06 PM

Addresses https://github.com/cockroachdb/cockroach/issues/81332

### CODE REVIEW

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83417#-:-N5alGeP5L1xzl5ehxtI:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @benbardin, and @dhartunian)

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83417#-N5afLMp8K9JzzKR8yOA):*
Consider taking the opportunity to make the hidden tags (the gray ones) similarly collapsible. They were collapsible at first, but then we lost it when we reactified the page. If you don't, make sure they don't use the "warning" styling.
___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83417#-N5afMX-9DN98wh59Jah):*
I see in the screenshot that `ExportStats` ended up in front of `job:...`. I'm curious why that is and whether we can make it be the other way around, given that the job tag surely was probably applied before the `ExportStats` one. I remember thinking that the tags in the anonymous group would end up first first, and I think I like that. Perhaps this `job:` is coming from `LogTags`?
Consider checking if this is something that can easily be tweaked.
___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83417#-N5ajfOV4ufTyvFZFJrP):*
I think there's been a small regression in your previous patch. Before, when a `LazyTag.Render` was returning 0 tags, that `LazyTag` was no reflected in any way in `tracez` and String and wherever else. I think now it is, because of this code:
https://github.com/cockroachdb/cockroach/blob/6ca1864c0fba2b6ed4b2db39a2544190ba068fd0/pkg/util/tracing/crdbspan.go#L841
We add the group non-conditionally, and I think this causes it to show up, right? The `ContentionEventTracer` doesn't render any tags when there's been no contention, and so we don't want it to show up.
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83417#-N5agMQSCzfd0JihR-R7):*
 Not your code, but why do all the tags yell at me in caps? Consider seeing if we can render them as they were recorded.
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83417#-N5ae9Md0I7RPrG5sugv):*
I haven't said anything about tracez in release notes before. Let's not start with this.
Also, this note won't make sense to any user :P
___
*[`pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx` line 198 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83417#-N5agggNCTZYB1AQje7r:-N5agggO7MAPI9Fje_03:bjt7bjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5846c156d846679706d789db07bcc0184d849c/pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx#L198)):*
> ```XML
>   // Table rows have a minimum height of 70px, and this is not configurable.
>   //
>   // With this particular badge styling, that gives the illusion of 15 pixels of padding, with the TagBadge centered
> ```

long lines; please wrap
___
*[`pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx` line 208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83417#-N5ak_Kk0tUXqISw3YjD:-N5ak_Kk0tUXqISw3YjE:bq2cq7s) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5846c156d846679706d789db07bcc0184d849c/pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx#L208)):*
> ```XML
>             <TagBadge t={t}
>                       setSearch={props.setSearch}
>                       isExpanded={expandedTagIndex == i}
> ```

so only one tag at a time can be expended? I guess that's fine

**Review by koorosh — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83417)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @benbardin, and @dhartunian)

___
*[`pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx` line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83417#-N5bGoYTCNIfO95Puxfd:-N5bGoYTCNIfO95Puxfe:bnf6p3r) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5846c156d846679706d789db07bcc0184d849c/pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx#L162)):*
> ```XML
>         }
>         size="small"
>         status={status ? status : isExpandable ? "warning" : !t.hidden ? "info" : "default"}
> ```

Such ternary construction looks a bit complicated and difficult to read. Would you mind refactoring it with `if ... else` conditions? 
___
*[`pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx` line 192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83417#-N5bF0d9AbBEmj2RVedh:-N5bF0d9AbBEmj2RVedi:bqfqut3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5846c156d846679706d789db07bcc0184d849c/pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx#L192)):*
> ```XML
>   const [expandedTagIndex, setExpandedTagIndex] = useState<Number>(-1);
>   const processedTags = props.sr.span.processed_tags
>   const orderedTags = [...processedTags.filter(t => !t.hidden), ...processedTags.filter(t => t.hidden)]
> ```

It can be simplified with lodash's `sortBy` func: 
```javascript
_.sortBy(processedTags, t => t.hidden)
```
___
*[`pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx` line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83417#-N5bIPUt9-R0yQZVRwRx:-N5bIPUu4pe4z2MwWJkt:b-j769av) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5846c156d846679706d789db07bcc0184d849c/pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx#L202)):*
> ```XML
>   // to move up 8 pixels. This is disorienting, so avoid it by making the padding official.
>   return (
>     <div style={{paddingTop: "8px", paddingBottom: "8px", display: "flex", flexDirection: "column", gap: "10px"}}>
> ```

Can be defined as a `class` in `tracez.styl`. Styles that don't rely on dynamically calculated values can be moved in `styl` files.

**Review by benbardin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83417)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @andreimatei, @benbardin, @dhartunian, and @koorosh)

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83417#-N5afLMp8K9JzzKR8yOA):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Consider taking the opportunity to make the hidden tags (the gray ones) similarly collapsible. They were collapsible at first, but then we lost it when we reactified the page. If you don't, make sure they don't use the "warning" styling.
</blockquote></details>

Will do in a follow-up diff.
___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83417#-N5afMX-9DN98wh59Jah):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I see in the screenshot that `ExportStats` ended up in front of `job:...`. I'm curious why that is and whether we can make it be the other way around, given that the job tag surely was probably applied before the `ExportStats` one. I remember thinking that the tags in the anonymous group would end up first first, and I think I like that. Perhaps this `job:` is coming from `LogTags`?
Consider checking if this is something that can easily be tweaked.
</blockquote></details>

My mistake! It's just an old screenshot, that predates the revisions you suggested. I've updated the screenshots.
___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83417#-N5ajfOV4ufTyvFZFJrP):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think there's been a small regression in your previous patch. Before, when a `LazyTag.Render` was returning 0 tags, that `LazyTag` was no reflected in any way in `tracez` and String and wherever else. I think now it is, because of this code:
https://github.com/cockroachdb/cockroach/blob/6ca1864c0fba2b6ed4b2db39a2544190ba068fd0/pkg/util/tracing/crdbspan.go#L841
We add the group non-conditionally, and I think this causes it to show up, right? The `ContentionEventTracer` doesn't render any tags when there's been no contention, and so we don't want it to show up.
</blockquote></details>

Yup, I think that's right. Corrected.
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83417#-N5agMQSCzfd0JihR-R7):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

 Not your code, but why do all the tags yell at me in caps? Consider seeing if we can render them as they were recorded.
</blockquote></details>

discussed offline, will address in a followup diff.
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83417#-N5ae9Md0I7RPrG5sugv):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I haven't said anything about tracez in release notes before. Let's not start with this.
Also, this note won't make sense to any user :P
</blockquote></details>

It's gone!
___
*[`pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx` line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83417#-N5bGoYTCNIfO95Puxfd:-N5fB-hGAzihJRrxqjJ6:b-7rl0jq) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5846c156d846679706d789db07bcc0184d849c/pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx#L162)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Such ternary construction looks a bit complicated and difficult to read. Would you mind refactoring it with `if ... else` conditions? 
</blockquote></details>

done!
___
*[`pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx` line 192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83417#-N5bF0d9AbBEmj2RVedh:-N5f9mvk8ZPJBB7o1Vzv:b90bfyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5846c156d846679706d789db07bcc0184d849c/pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx#L192)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

It can be simplified with lodash's `sortBy` func: 
```javascript
_.sortBy(processedTags, t => t.hidden)
```
</blockquote></details>

oh neat! didn't figure that was a stable sort, TIL!
___
*[`pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx` line 198 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83417#-N5agggNCTZYB1AQje7r:-N5fBI16Cclx4DWndzY0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5846c156d846679706d789db07bcc0184d849c/pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx#L198)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

long lines; please wrap
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx` line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83417#-N5bIPUt9-R0yQZVRwRx:-N5fGbBeB71QexiKkTvx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5846c156d846679706d789db07bcc0184d849c/pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx#L202)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Can be defined as a `class` in `tracez.styl`. Styles that don't rely on dynamically calculated values can be moved in `styl` files.
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx` line 208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83417#-N5ak_Kk0tUXqISw3YjD:-N5f9rMh81IlzvDEQRfs:b-muyz9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5846c156d846679706d789db07bcc0184d849c/pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx#L208)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

so only one tag at a time can be expended? I guess that's fine
</blockquote></details>

Yeah, with this UI at least I think that makes sense. We'll have a designer actually think about this page soon, but until then we'll have to make do!

**Review by benbardin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83417)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @andreimatei, @dhartunian, and @koorosh)

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83417#-N5afLMp8K9JzzKR8yOA):*
<details><summary><i>Previously, benbardin (Ben Bardin) wrote…</i></summary><blockquote>

Will do in a follow-up diff.
</blockquote></details>

Done.

**Review by andreimatei — COMMENTED** [review]
:lgtm:  as far as I'm concerned

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83417#-:-N5fi61E6MyN68d44hdJ:bbemyrq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @andreimatei, @dhartunian, and @koorosh)

**Review by koorosh — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83417)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @adityamaru, @andreimatei, @benbardin, @dhartunian, and @koorosh)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/83417#-N5fmWZiCnFDta2W13GQ:-N5fmWZiCnFDta2W13GR:bg7igkv) (no related file):*
:lgtm: 

___

**Pull request merged**
