### PR TITLE
sql: improve RSG internals

### PR DESCRIPTION
**Pull request by madelynnblue**
Plumb contexts down for use in db.Exec functions. Use an errgroup for
workers so they can coordinate stoppage better. Move the exec timeout
that was previously just on func testing to the db so all statements
are checked for timeout.

Release note: None

### CODE REVIEW

**Comment by mjibson** [comment]
This should fix the current RSG breakage.

**Comment by jordanlewis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[pkg/sql/tests/rsg_test.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26401#-LEB_NRQ-6n4ToK4c6OC:-LEB_NRQ-6n4ToK4c6OD:bik5tct) ([raw file](https://github.com/cockroachdb/cockroach/blob/37af7d62d69cfd78e3d0d945556cacb52a98b8bd/pkg/sql/tests/rsg_test.go#L80)):*
> ```Go
> 	verifyFormatErr error
> 	mu              struct {
> 		sync.Mutex
> ```

isn't this supposed to be syncutil?

---

*[pkg/sql/tests/rsg_test.go, line 152 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26401#-LEB_VyfDJVCzJEgLbqN:-LEB_VyfDJVCzJEgLbqO:biuanm9) ([raw file](https://github.com/cockroachdb/cockroach/blob/37af7d62d69cfd78e3d0d945556cacb52a98b8bd/pkg/sql/tests/rsg_test.go#L152)):*
> ```Go
> 		// a previous run. Should always succeed.
> 		if err := db.exec(ctx, `CREATE DATABASE IF NOT EXISTS ident`); err != nil {
> 			return (err)
> ```

nit: remove the parens (i didn't know this compiled!)

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26401#-:-LEB_ugtAvKZzZB86Kfu:bnfp4nl)*

**Pull request merged**
