### PR TITLE
opt: remove confusing sentence in comment

### PR DESCRIPTION
**Pull request by mgartner**
Epic: None

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
I believe this comment was incorrect, but I'm not 100% sure. This seems like the most likely intended phrasing.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119896)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/opt/xform/select_funcs.go` line 913 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119896#-NsB09Nm5vF19Hsjq4ls:-NsB09NnD0P6EN3vwyMD:bqg9o7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e3014971769b6e8d6ec924688e1c4dca47f8a2d/pkg/sql/opt/xform/select_funcs.go#L913)):*
> ```Go
> 		// eliminate the UNION operator in the tree, replacing it with a non-nil
> 		// FactoredUnionSpans in the SpanExpression, and that case needs to be
> 		// noticed and filtered.
> ```

It's unclear, but I think the original comment might be right. See this logic that can remove the operator: https://github.com/cockroachdb/cockroach/blob/bf013ea0a5311726e65d37e8f047ce39ea2d5f10/pkg/sql/inverted/expression.go#L711-L713

**Comment by mgartner** [comment]
*[`pkg/sql/opt/xform/select_funcs.go` line 913 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119896#-NsB09Nm5vF19Hsjq4ls:-NsDuXDG-6niNGji0sxU:b-5qaoyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e3014971769b6e8d6ec924688e1c4dca47f8a2d/pkg/sql/opt/xform/select_funcs.go#L913)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

It's unclear, but I think the original comment might be right. See this logic that can remove the operator: https://github.com/cockroachdb/cockroach/blob/bf013ea0a5311726e65d37e8f047ce39ea2d5f10/pkg/sql/inverted/expression.go#L711-L713
</blockquote></details>

The first paragraph explains the check for `!spanExpr.Unique`, so something is wrong with the second paragraph. 

The function you linked to can set `spanExpr.Operator` to `inverted.None` here: https://github.com/cockroachdb/cockroach/blob/bf013ea0a5311726e65d37e8f047ce39ea2d5f10/pkg/sql/inverted/expression.go#L765

Isn't that what the second paragraph is referring to?

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119896)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/opt/xform/select_funcs.go` line 913 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119896#-NsB09Nm5vF19Hsjq4ls:-NsEcDeH2Dbjehv4tJWg:b-axpyed) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e3014971769b6e8d6ec924688e1c4dca47f8a2d/pkg/sql/opt/xform/select_funcs.go#L913)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Oh I see, the first paragraph explains both conditions. I really don't understand the second paragraph at all then...
</blockquote></details>

Yeah, it might be most clear to just remove it.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119896)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/opt/xform/select_funcs.go` line 913 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119896#-NsB09Nm5vF19Hsjq4ls:-NsF9Vo8-0Qc3uFOHIVO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e3014971769b6e8d6ec924688e1c4dca47f8a2d/pkg/sql/opt/xform/select_funcs.go#L913)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Yeah, it might be most clear to just remove it.
</blockquote></details>

Done.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Thanks!

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119896#-:-NsFKdba1kaW95rR7Sao:b-g2a5fb)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119896#-NsFK_5yA2ToV82Sjw3X):*
[nit] This needs an update.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119896)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119896#-NsFK_5yA2ToV82Sjw3X):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] This needs an update.
</blockquote></details>

Done.

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
