### PR TITLE
ci: ensure roachtest can find libgeos on TC agent

### LINKED ISSUE #104988: roachtest: tlp failed
roachtest.tlp [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10539670?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10539670?buildTab=artifacts#/tlp) on master @ [3c55b81a4e64b62b7a1a59fad76c8d8a39f867a0](https://github.com/cockroachdb/cockroach/commits/3c55b81a4e64b62b7a1a59fad76c8d8a39f867a0):

```
(test_runner.go:1053).1: test panicked: geos: no locations to init GEOS
test artifacts and logs in: /artifacts/tlp/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tlp.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-28813

### PR DESCRIPTION
**Pull request by srosenberg**
After adding support for multiple cpu architectures, a regression was introduced in CI [1]. Roachtests running locally (i.e., on TC agent), and occasionally even non-local roachtests (e.g., TLP) may require libgeos on the host. Previously, libgeos was cross-compiled and placed under `lib`, but with the architecture suffix,
e.g., `libgeos.linux-amd64.so`.

The lazy initialization in libgeos (see geos.go) doesn't support it, i.e., it looks only for `libgeos.so`. Thus, we augment the CI script to place libgeos, compiled for the host architecture, under `lib`, without the architecture suffix.

[1] https://github.com/cockroachdb/cockroach/pull/104303

Epic: none
Fixes: #104988

Release note: None

### CODE REVIEW

**Review by rail — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105119)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @srosenberg)

___
*[`build/teamcity/cockroach/nightlies/roachtest_compile_bits.sh` line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105119#-NYB681V1JX1EYlKIQiV:-NYB681V1JX1EYlKIQiW:b-txn45n) ([raw file](https://github.com/cockroachdb/cockroach/blob/d59704d2f1b780582e7051513045f2dce3cc05b8/build/teamcity/cockroach/nightlies/roachtest_compile_bits.sh#L45)):*
> ```Shell
>     bazel build --config $platform --config ci  -c opt //pkg/cmd/roachtest
> 
>     cp $BAZEL_BIN/pkg/cmd/roachtest/roachtest_/roachtest bin/roachtest
> ```

Looks like `$BAZEL_BIN` is defined below. Move it also up?

**Review by srosenberg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105119)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @rail, and @renatolabs)

___
*[`build/teamcity/cockroach/nightlies/roachtest_compile_bits.sh` line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105119#-NYB681V1JX1EYlKIQiV:-NYB7Uu-E9J4cYTtYVlc:b-fpxdh3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d59704d2f1b780582e7051513045f2dce3cc05b8/build/teamcity/cockroach/nightlies/roachtest_compile_bits.sh#L45)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Looks like `$BAZEL_BIN` is defined below. Move it also up?
</blockquote></details>

Yikes, refactoring bash (without tests) is like playing russian roulette :) Good catch! I wouldn't have seen it until triggering a CI run.

**Review by rail — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105119)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

**Comment by srosenberg** [comment]
Three successful runs of TLP, so hopefully that should resolve the issue. 🤞 

- https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10578426?buildTab=tests
- https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10584930?buildTab=tests
- https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10585115?buildTab=tests

**Comment by srosenberg** [comment]
TFTR!

bors r=rail

**Pull request merged**
