### PR TITLE
sql: use IsSQLRetryableError in IsPermanentSchemaChangeError

### LINKED ISSUE #36489: Index creation failed with "Result is ambiguous"
**Describe the problem**

Index creation job ran for ~ 7 days before failing with error: 

`result is ambiguous (error=unable to dial n18: break open [exhausted])`

**To Reproduce**
Index that was being created: 

`CREATE INDEX <INDEX NAME> ON <TABLE>(geo_key, expiry_timestamp) PARTITION BY LIST (geo_key) (PARTITION eti_mt_idx VALUES IN ('MT'), PARTITION eti_be_idx VALUES IN ('BE'), PARTITION eti_de_idx VALUES IN ('DE'))`

**Expected behavior**
Index creation should complete successfully

**Environment:**
 - CockroachDB v19.1.0-beta.20190318

### PR DESCRIPTION
**Pull request by vivekmenezes**
fixes #36489 

Release note: None

### CODE REVIEW

**Comment by vivekmenezes** [comment]
@dt thoughts on this one?

**Comment by dt** [comment]
I think @knz would actually be more qualified to look at this than me -- I'm not too concerned about all the test calls, but that helper has a bunch of patterns it checks and those were presumably added when it was a _test_ helper. I don't know exactly when/what each of those mean though, and I know @knz has looked a lot at classifying and handling errors lately so I'll defer to him here.

**Review by knz — APPROVED** [review]
I'm OK with this change because it's just a refactoring.

However the regular expression is a huge red flag and bound to fail in mysterious ways. For example if a node is permanently down, this code will livelock. we'll need to fix this later.

Meanwhile heads up I am currently working on a review of various flaws in error handling, and I found it useful that you brought up this PR to my attention. Thank you!

**Comment by vivekmenezes** [comment]
Thanks @knz appreciate all the work you're putting into creating an architecture for errors and error handling. I'd appreciate you giving a talk on it when you're done!

**Comment by knz** [comment]
However please **do not** backport this to 19.1.

**Comment by vivekmenezes** [comment]
This is fixing an issue seen by a customer

**Comment by knz** [comment]
If the issue observed by the customer is important, then please build a correct fix and not use this ad-hoc hack, which will yield **Strictly worse** results in edge cases.

I am OK with this PR on the `master` branch because I will refactor this predicate away in a later error refactor, however for the 19.1 branch I will not be doing this refactor and the code you're introducing here will make the 19.1 code strictly worse.

**Comment by vivekmenezes** [comment]
The problem the customer observes is that a schema change that runs for many hours fails due to a network/node failure. I understand it's a hack but better than having a customer waste many hours of work on their cluster.

**Comment by knz** [comment]
The fix you provide here is simply not good.
@andreimatei @bdarnell I would be grateful if you could suggest a more robust approach that would both solve the problem in 19.1 and avoid introducing new hard-to-debug livelock scenarios.

**Review by bdarnell — COMMENTED** [review]
Yeah, this is not a good fix. In addition to general hygiene issues around matching errors with regexes, I don't think the set of strings matched by this function are particularly coherent. 

Specifically, ambiguous errors are generally *not* considered retryable, for good reason. Retrying non-idempotent operations after an ambiguous error could result in them applying more than once. A general IsRetryable matcher should only return true for unambiguously retryable errors, and ambiguous errors should be matched separately so that only operations that are known to be idempotent can retry them.

>  I understand it's a hack but better than having a customer waste many hours of work on their cluster.

I disagree. A single incident that resulted in hours of "wasted work" (computer time, not human time) is not a reason to rush out a hacky fix. 


I think we should try to get rid of both the testutils IsSQLRetryableError functions and the schema changer's IsPermanentSchemaChangeError. Instead, run all errors through the pgerror machinery and make decisions about what to retry based on the same error codes we'd return to the client. If we want to retry in a certain way, we should make sure that is getting captured in an error code so clients can make corresponding decisions without matching error strings. 

The ambiguous error from #36489 should already be getting the appropriate error code; if there are other errors that we want to retry on we should make sure that pgerror knows about them instead of adding them to another special-case list of errors.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36495#-:-Lc7KKrJ7PDiST_GfRBx:b-y0qyxc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Pull request merged**
