### PR TITLE
sql: miscellaneous INSERT, UPSERT and UPDATE correctness fixes

### LINKED ISSUE #25726: sql: correctness bug with UPSERT and FAMILY
On master:
```sql
CREATE TABLE t (a INT PRIMARY KEY, b INT, c INT, FAMILY (a, b), FAMILY (c));
INSERT INTO t VALUES (1, 2, 3);
UPSERT INTO t VALUES (1, NULL, NULL);
SELECT * FROM t;
```
returns
```
+---+------+---+
| a |  b   | c |
+---+------+---+
| 1 | NULL | 3 |
+---+------+---+
```
but should return `(1, NULL, NULL)`. This reproduces without the `b` column, but I thought the example was more obvious with it.

Looks like the all-NULL column family isn't actually getting a tombstone written. The equivalent UPDATE works fine.  @knz you've touched UPSERT last, mind looking into this?

### PR DESCRIPTION
**Pull request by knz**
Fixes #25726.
Performs a long-awaited cleanup requested by @danhhz.

This code is ripe for rewriting (there's a bunch of common tests that should really be performed once for the entire table, instead of anew every row) but we'll do this later.

### CODE REVIEW

**Comment by BramGruneir** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/sql/sqlbase/rowwriter.go, line 282 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26169#-LDh9aYJCmQfDxOirCpL:-LDh9aYJCmQfDxOirCpM:b-a2imkq) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb51e55a2ddd72a8c9473eb99b48fd8db8562/pkg/sql/sqlbase/rowwriter.go#L282)):*
> ```Go
> 		putFn = insertPutFn
> 	}
> 	delFn := insertDelFn
> ```

Why is this needed?  You're not potentially overriding it.

Actually, reading through the code, why is the function passed around at all and not just called directly?

---

*[pkg/sql/sqlbase/rowwriter.go, line 327 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26169#-LDh9vX82Lnq-yTckNAn:-LDh9vX82Lnq-yTckNAo:bg4fvkv) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb51e55a2ddd72a8c9473eb99b48fd8db8562/pkg/sql/sqlbase/rowwriter.go#L327)):*
> ```Go
> // prepareInsertOrUpdateBatch constructs a KV batch that inserts or
> // updates a row in KV.
> // - batch is the KV batch where commands should be appended.
> ```

I love this comment.  It's probably about time to turn this into a struct.  But not in the PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26169#-:-LDhAnhq0RP3TwWlzG1v:bnfp4nl)*

**Comment by knz** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/sqlbase/rowwriter.go, line 282 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26169#-LDh9aYJCmQfDxOirCpL:-LDhKktt38eiDN-ztr5e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb51e55a2ddd72a8c9473eb99b48fd8db8562/pkg/sql/sqlbase/rowwriter.go#L282)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why is this needed?  You're not potentially overriding it.

Actually, reading through the code, why is the function passed around at all and not just called directly?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26169)*

**Comment by BramGruneir** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26169)*

**Comment by knz** [comment]
TFYR!

bors r+

**Pull request merged**
