### PR TITLE
sql: add support for SHOW CREATE PROCEDURE

### PR DESCRIPTION
**Pull request by mgartner**
#### sql/tree: rename ShowCreateFunction to ShowCreateRoutine

Release note: None

#### sql/logictest: move create_function_statements tests to crdb_internal

Release note: None

#### sql: add crdb_internal.show_procedure_statements

This commit adds the `crdb_internal.show_procedure_statements` table. It
is very similar to the `show_function_statements` table, but it shows
procedures instead of user-defined functions.

Release note: None

#### sql: add SHOW CREATE PROCEDURE

This commit adds support for the `SHOW CREATE PROCEDURE` statement.

Epic: CRDB-25388

Release note: None

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm: Looks great!

> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, 15 of 15 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111597#-:-Nfm3PK33LsO_N3e8Udh:b-2t11ox)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/logictest/testdata/logic_test/crdb_internal` line 1460 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111597#-Nfm-cBsBfWfNCxNyMiS:-Nfm-cBsBfWfNCxNyMiT:bulmix3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d4e25205f5ab34aa4f79988a47bac5c8910b69f/pkg/sql/logictest/testdata/logic_test/crdb_internal#L1460)):*
> ```
> 
> statement ok
> CREATE PROCEDURE f(BOOL) LANGUAGE SQL AS $$ SELECT 1 $$;
> ```

Is this to check that the procedure CREATE doesn't show up in `create_function_statements`?

**Comment by DrewKimball** [comment]
Looks like some logic tests will have to be regenerated before this passes CI.

**Review by rharding6373 — APPROVED** [review]
:lgtm: Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111597#-:-NfmFiJo-Q4BQgq2JSSi:bcmw7ss)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111597)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/logictest/testdata/logic_test/crdb_internal` line 1460 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111597#-Nfm-cBsBfWfNCxNyMiS:-NfrHAk15LBx8CD6DvOz:b2uayfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d4e25205f5ab34aa4f79988a47bac5c8910b69f/pkg/sql/logictest/testdata/logic_test/crdb_internal#L1460)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Is this to check that the procedure CREATE doesn't show up in `create_function_statements`?
</blockquote></details>

Exactly. I've added a comment to explain this.

**Comment by mgartner** [comment]
TFTRs! Finally fixed up the tests.

bors r+

**Pull request merged**
