### PR TITLE
cli: skip TestRemoveDeadReplicas

### PR DESCRIPTION
**Pull request by tbg**
https://github.com/cockroachdb/cockroach/issues/41586

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41631#-:-LrJbY0i89viCWWt9Q6j:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bdarnell and @knz)

**Comment by knz** [comment]
LGTM
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tbg** [comment]
bors r=knz,ajwerner

**Comment by tbg** [comment]
acceptance/version-upgrade flaked, I'm looking into it but it's not this PR's fault

bors r=knz,ajwerner

**Comment by tbg** [comment]
Same thing, but I reverted the thing that made the flake happen, so let's
go agtgain

bors r=knz,ajwerner

**Pull request merged**
