### PR TITLE
pkg/sql: move logic_test to pkg/sql/logictest

### PR DESCRIPTION
**Pull request by jordanlewis**
This will improve test parallelization, enabling faster builds locally
and on CI.

### CODE REVIEW

**Comment by knz** [comment]
:dog: why not

:lgtm:

---

Review status: 0 of 127 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16430#-:-KmDpugLgVkcNCiXchLA:b-yv91qe)*

**Comment by benesch** [comment]
:lgtm: too, but you'll need to split `build/teamcity-testrace.sh` into two as well to actually speed up CI, no?

---

Reviewed 252 of 252 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16430#-:-KmDqIhz-rRG_FrBAuVm:b-ivu6nf)*

**Comment by jordanlewis** [comment]
Hmm, no based on the discussion we had I thought that since `sql` is by far the slowest packge, splitting it in half would enable further parallelization without us having to do anything.

Let's give this a try first?

---

Review status: 126 of 127 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16430#-:-KmDqpmUtohtTpppTsPc:b-5lk5hq)*

**Comment by jordanlewis** [comment]
Here's the `testrace` build for the last run of this patch: https://teamcity.cockroachdb.com/viewLog.html?buildId=268523&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Testrace

It's 11 minutes instead of the 15-20 of the other recent testrace builds.

---

Review status: 126 of 127 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16430#-:-KmDsq5e5Hlluq4ac7q-:b-3dh6nm)*

**Comment by benesch** [comment]
Sure, happy to see this go in as is.

Still, I'm skeptical this will have much of an impact. `make testrace` already maxes out my CPU for most of its duration.

---

Review status: 126 of 127 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16430#-:-KmDrTjBJ30L8sse81Sr:bx4aobd)*

**Comment by benesch** [comment]
Ha, I stand corrected!

(Are you opposed to splitting `make testrace` into `make testrace PKG=NOT-LOGICTEST` and `make testrace PKG=./pkg/sql/logictest`?)

---

Review status: 126 of 127 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16430#-:-KmDtf9B7OuktKASdQYS:b-xm3x7y)*

**Comment by jordanlewis** [comment]
Not opposed! I don't know if it'll make too much of a difference either though. Logic test under testrace takes about 6 minutes on TeamCity. It seems like we've already extracted much of that gain in the (noisy) difference between 11 minutes and 15-20 minutes.

---

Review status: 126 of 127 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16430#-:-KmDtjjsHcfURT3SP1DI:b-9ba9sd)*

**Comment by knz** [comment]
To facilitate any future changes on the release-1.0 branch I strongly advise to cherry-pick this there too.

**Comment by tamird** [comment]
This forgot to update teamcity-sqllogictest.sh which still runs `build/builder.sh env make test 'TESTFLAGS=-v -bigtest -config default' TESTTIMEOUT=24h PKG=./pkg/sql 'TESTS=^TestLogic$$'` and now fails with `flag provided but not defined: -bigtest`.

https://teamcity.cockroachdb.com/viewLog.html?buildId=269190&tab=buildResultsDiv&buildTypeId=Cockroach_SqlLogicTests

**Pull request merged**
