### PR TITLE
storage: terminate nodes in minority on stats mismatch

### PR DESCRIPTION
**Pull request by tbg**
First commit is https://github.com/cockroachdb/cockroach/pull/41893

----

Following up on the parent commit, the consistency checker now instructs
the replicas corresponding to the SHA with the lowest multiplicity to
terminate.

Note that this change is a candidate for backporting into 19.2. An "old"
leaseholder will never populate the newly introduced field, and will always
terminate itself. A new leaseholder will populate the field, but only new
nodes will interpret it. In the worst case, the result will be a
consistency failure that does not lead to a fatal error (but collects
RocksDB checkpoints just the same). Since no significant time is usually
spent in a mixed-patch-releases, this is not a concern that outweighs the
benefit of terminating (heuristically) the "right" nodes.

Release note (general improvement): when the replicas within a range have
found to been corrupted, the outliers will be terminated. Previously, the
leaseholder replica would terminate, regardless of which replicas disagreed
with each other. This is expected to curb the spreading of corrupted data
better than the previous approach.

### CODE REVIEW

**Review by irfansharif — APPROVED** [review]
:lgtm: Mostly just asking for comments to help my :microscope: :dog: self. Remember to change the second commit message to remove reference to "parent commit" once #41893 is merged separately.

> Reviewed 2 of 2 files at r1, 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41902#-:-Lrza09lDIHG3K1Pt7Ws:b-luysm3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/roachpb/api.proto, line 488 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41902#-LrzV3519N53QMrXKDsP:-LrzV3519N53QMrXKDsQ:b1zr0ax) ([raw file](https://github.com/cockroachdb/cockroach/blob/582b960dec16e83a3695ed24cffc00ef36ed4857/pkg/roachpb/api.proto#L488)):*
> ```protobuf
>   // directory and needs to be removed manually to avoid leaking disk space.
>   bool checkpoint = 4;
>   repeated ReplicaDescriptor terminate = 5 [(gogoproto.nullable) = false];
> ```

Could use a comment, as below. I have no real suggestions to make but 'terminate' sounds like a boolean, not a list of replicas to be terminated.
___
*[pkg/roachpb/api.proto, line 1208 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41902#-LrzVnIr6UvuwI2eiHJf:-LrzVnIr6UvuwI2eiHJg:b7eozws) ([raw file](https://github.com/cockroachdb/cockroach/blob/582b960dec16e83a3695ed24cffc00ef36ed4857/pkg/roachpb/api.proto#L1208)):*
> ```protobuf
>   // in the engine's auxiliary directory.
>   bool checkpoint = 6;
>   // If set, specifies the replicas which are the most likely source of the
> ```

[nit] set -> non-empty.
___
*[pkg/storage/consistency_queue_test.go, line 243 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41902#-LrzbOC69zUua6EXBmF0:-LrzbOC69zUua6EXBmF1:ba2p2g0) ([raw file](https://github.com/cockroachdb/cockroach/blob/582b960dec16e83a3695ed24cffc00ef36ed4857/pkg/storage/consistency_queue_test.go#L243)):*
> ```Go
> 			notifyReportDiff <- struct{}{}
> 		}
> 	// Store 0 will panic.
> ```

Update this comment. also, notifyFatal?
___
*[pkg/storage/replica_consistency.go, line 268 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41902#-LrzcpU8EJ0ZKHwZJh30:-LrzcpU8EJ0ZKHwZJh31:ba1zbey) ([raw file](https://github.com/cockroachdb/cockroach/blob/582b960dec16e83a3695ed24cffc00ef36ed4857/pkg/storage/replica_consistency.go#L268)):*
> ```Go
> 	}
> 
> 	// Diff was printed above, so call logFunc with a short message only.
> ```

`logFunc` no longer applicable.
___
*[pkg/storage/replica_proposal.go, line 254 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41902#-LrziG494dmK38RPQ0Zr:-LrziG494dmK38RPQ0Zs:b-s0itlo) ([raw file](https://github.com/cockroachdb/cockroach/blob/582b960dec16e83a3695ed24cffc00ef36ed4857/pkg/storage/replica_proposal.go#L254)):*
> ```Go
> 		if shouldFatal {
> 			// This node should fatal as a result of a previous consistency
> 			// check (i.e. this round is carried out only to obtain a diff).
> ```

Aside: The fact that this takes place over two rounds, is this documented somewhere? From a quick skim I couldn't find it. If there, the fact that replicas self terminate in the second round merits a mention there.
___
*[pkg/storage/storagepb/proposer_kv.proto, line 87 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41902#-LrzZFm--8LNE-c4IWlB:-LrzZFm--8LNE-c4IWlC:b7vyxbs) ([raw file](https://github.com/cockroachdb/cockroach/blob/582b960dec16e83a3695ed24cffc00ef36ed4857/pkg/storage/storagepb/proposer_kv.proto#L87)):*
> ```protobuf
>   // inconsistency and we want to preserve as much state as possible.
>   bool checkpoint = 4;
>   repeated roachpb.ReplicaDescriptor terminate = 6 [(gogoproto.nullable) = false];
> ```

Comment here.

**Review by tbg — COMMENTED** [review]
TFTR!

> change the second commit message to remove reference to "parent commit" once #41893 is merged separately.

Done

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41902#-:-Ls1GVt65Y9dzvWNgo2i:b-ty6wzs)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif)

___
*[pkg/roachpb/api.proto, line 488 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41902#-LrzV3519N53QMrXKDsP:-Ls1HNfs8f66uq0eisw9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/582b960dec16e83a3695ed24cffc00ef36ed4857/pkg/roachpb/api.proto#L488)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Could use a comment, as below. I have no real suggestions to make but 'terminate' sounds like a boolean, not a list of replicas to be terminated.
</blockquote></details>

Done.
___
*[pkg/roachpb/api.proto, line 1208 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41902#-LrzVnIr6UvuwI2eiHJf:-Ls1HmeiEucaS2-YVHW3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/582b960dec16e83a3695ed24cffc00ef36ed4857/pkg/roachpb/api.proto#L1208)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

[nit] set -> non-empty.
</blockquote></details>

Done.
___
*[pkg/storage/consistency_queue_test.go, line 243 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41902#-LrzbOC69zUua6EXBmF0:-Ls1Ht5235gqg5JiKv23:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/582b960dec16e83a3695ed24cffc00ef36ed4857/pkg/storage/consistency_queue_test.go#L243)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Update this comment. also, notifyFatal?
</blockquote></details>

Done.
___
*[pkg/storage/replica_consistency.go, line 268 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41902#-LrzcpU8EJ0ZKHwZJh30:-Ls1IUMB3Njr3PrWpcrs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/582b960dec16e83a3695ed24cffc00ef36ed4857/pkg/storage/replica_consistency.go#L268)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

`logFunc` no longer applicable.
</blockquote></details>

Done.
___
*[pkg/storage/replica_proposal.go, line 254 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41902#-LrziG494dmK38RPQ0Zr:-Ls1IqEL5pjt3DZ-Krrp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/582b960dec16e83a3695ed24cffc00ef36ed4857/pkg/storage/replica_proposal.go#L254)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Aside: The fact that this takes place over two rounds, is this documented somewhere? From a quick skim I couldn't find it. If there, the fact that replicas self terminate in the second round merits a mention there.
</blockquote></details>

Done.
___
*[pkg/storage/storagepb/proposer_kv.proto, line 87 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41902#-LrzZFm--8LNE-c4IWlB:-Ls1J4zq7RHjvEt5qpXB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/582b960dec16e83a3695ed24cffc00ef36ed4857/pkg/storage/storagepb/proposer_kv.proto#L87)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Comment here.
</blockquote></details>

Done.

**Review by irfansharif — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41902)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif and @tbg)

___
*[pkg/storage/consistency_queue_test.go, line 243 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41902#-LrzbOC69zUua6EXBmF0:-Ls2Jzdh6A5apy67fzfE:bxjg9hp) ([raw file](https://github.com/cockroachdb/cockroach/blob/582b960dec16e83a3695ed24cffc00ef36ed4857/pkg/storage/consistency_queue_test.go#L243)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Did you mean s1?
___
*[pkg/storage/storagepb/proposer_kv.proto, line 87 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41902#-LrzZFm--8LNE-c4IWlB:-Ls2JsJY9QTX7inKkiAq:b-q03nd5) ([raw file](https://github.com/cockroachdb/cockroach/blob/582b960dec16e83a3695ed24cffc00ef36ed4857/pkg/storage/storagepb/proposer_kv.proto#L87)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ha, "processing this comment"?

**Review by irfansharif — APPROVED** [review]
> Reviewed 2 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41902)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif and @tbg)

**Review by irfansharif — COMMENTED** [review]
> Reviewed 1 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41902)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41902)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif)

___
*[pkg/storage/consistency_queue_test.go, line 243 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41902#-LrzbOC69zUua6EXBmF0:-Ls2KKPI4FvkhD7pTOXa:bpnitw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/582b960dec16e83a3695ed24cffc00ef36ed4857/pkg/storage/consistency_queue_test.go#L243)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Did you mean s1?
</blockquote></details>

It's always a struggle with indexes vs IDs -- `mtc.Store(1).Ident.StoreID == 2`, `s2` refers to "the store with ID 2". I added a reference to the index.
___
*[pkg/storage/storagepb/proposer_kv.proto, line 87 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41902#-LrzZFm--8LNE-c4IWlB:-Ls2Kr4l7gVWQgi7SP-g:brm5fxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/582b960dec16e83a3695ed24cffc00ef36ed4857/pkg/storage/storagepb/proposer_kv.proto#L87)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

ha, "processing this comment"?
</blockquote></details>

:see_no_evil: done.

**Review by irfansharif — APPROVED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41902)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
