### PR TITLE
roachtest: rework child logger creation

### LINKED ISSUE #29139: roachtest: fix misuse of newLogger
Noticed in https://github.com/cockroachdb/cockroach/issues/29112#issuecomment-416332875. A quick inspect of the various `newLogger` calls show that many are passing in the command to run as the first parameter which is inappropriate. Need to change the API so that child loggers are always created relative to the test artifact directory.

### PR DESCRIPTION
**Pull request by petermattis**
Many tests were creating loggers via newLogger and doing so
incorrectly (i.e. specifying a command string for the parameter which
control the directory to log in). Revamped the creation of loggers to
make it harder to accidentally call newLogger. Added a loggerConfig
struct which holds the configuration for a logger and loggerOption
interface for easily applying changes to a log config. These combine and
are mostly invisible behind varargs that are passed to
logger.ChildLogger. Changed all of the existing uses of newLogger to use
ChildLogger.

Also took the opportunity to export logger.Printf and logger.Errorf to
make it clearer that these are part of the public interface to a
logger.

Fixes #29139

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 24 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29311#-:-LL96o9A7w9HA_UyT2wl:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by petermattis** [comment]
bors r=tschottdorf

**Comment by petermattis** [comment]
`Example-ORMs` is currently broken. Temporarily disabled until someone more knowledgable can diagnose.

bors r=tschottdorf

**Comment by petermattis** [comment]
No need to backport as roachtests against earlier releases use the roachtest from master.

**Pull request merged**
