### PR TITLE
clusterversion: allow skip-version upgrade without env var

### PR DESCRIPTION
**Pull request by renatolabs**
Starting from 24.3, we are now able to upgrade directly from
`MinSupported` without the need to set any environment variables.

Epic: none

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
@msbutler I also reverted #128961, as it should not longer be needed now.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm: 

I believe we also need to update the logic around `minSupportedSkipVersionUpgrade` (e.g. along the lines of #128666). We are currently saying that any version >= 24.3 can skip a release, but that won't be correct for innovation releases.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128982#-:-O4HbehK1UNsjnXTWvuy:b-wekt9i)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @srosenberg)

___
*[`pkg/cli/context.go` line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128982#-O4HbD_h3XjczokiBV45:-O4HbD_i4VzHkp4l5Ahe:b-4d33d7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4294b18ee705e21bba46424cd9cc71779878d4f5/pkg/cli/context.go#L99)):*
> ```Go
> 
> func makeClusterSettings() *cluster.Settings {
> 	// Even though the code supports upgrading from multiple previous releases,
> ```

For innovation releases, we don't want to allow skipping the previous (non-innovation) version. Will we make sure to advance MinSupported accordingly? Or do we want to retain the possibility of an experimental skip upgrade even in those cases?

**Review by renatolabs — COMMENTED** [review]
> I believe we also need to update the logic around `minSupportedSkipVersionUpgrade`

Yes. As we discussed in #128666, I think it is better to do this change first, and fix the skip-version logic later. Ideally I would want for us to consume structured data from some source telling us which releases are innovation (so that we don't need to implement a release schedule in code, and have to change the code when there is a process change).

In any case, until we figure that out, we should start testing skip-version upgrades, so this change should be merged earlier.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128982#-:-O4HfV2K4wEKYZQag_7v:b-5zi1ro)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @RaduBerinde, and @srosenberg)

___
*[`pkg/cli/context.go` line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128982#-O4HbD_h3XjczokiBV45:-O4Hg0oqAMQGEsMQj9yz:bm3ihwl) ([raw file](https://github.com/cockroachdb/cockroach/blob/4294b18ee705e21bba46424cd9cc71779878d4f5/pkg/cli/context.go#L99)):*
> Will we make sure to advance MinSupported accordingly?

I would assume so, that's the purpose of the `MinSupported` flag. I don't think we should support experimental upgrades unless we have a specific purpose in mind: are we going to test it? If so, are we going to fix bugs that only happen in experimental upgrades? In my mind, it's a bigger headache than it's worth, so we should focus our testing and development efforts in real upgrade paths.

**Review by RaduBerinde — APPROVED** [review]
Sounds good, thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128982#-:-O4HhKQkEGq0ujTrjr8g:b-k6rpao)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @srosenberg)

**Comment by renatolabs** [comment]
TFTR!

bors r=RaduBerinde

**Comment by RaduBerinde** [comment]
> Ideally I would want for us to consume structured data from some source telling us which releases are innovation

That would be nice. It would help with this hacky map as well: https://github.com/cockroachdb/cockroach/blob/master/pkg/roachpb/version.go#L185

**Pull request merged**
