### PR TITLE
util/json: copy/paste vendor gogo's jsonpb

### PR DESCRIPTION
**Pull request by dt**
jsonpb is a single-file leaf package in gogo, so it hardly seems worth switching
our whole dependency to a fork versus just copying that one file (and then several
testdata files).

Upstream gogo has shifted to be mostly unmaintained and is not accepting patches, so
pulling this one file library into our tree directly should make it easier for us to
fix bugs or extend it as needed (we have a fix for a bug in EmitDefaults and
have had to fight with the Marshal API a bit as well).

Release note: none.

### CODE REVIEW

**Comment by postamar** [comment]
This seems like a good idea!

Do I guess correctly that this will enable us to remove, at some point in the future, the linter check that prevents us from using jsonpb?

**Comment by miretskiy** [comment]
I'm cool with this change.  Will make it possible to fix protoreflect/redact.go
:lgtm:

**Review by miretskiy — APPROVED** [review]

**Review by knz — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72643)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @shermanCRL)

**Review by shermanCRL — APPROVED** [review]

**Comment by dt** [comment]
I'm reconsidering pulling this in vs just forking gogo and switching to the fork. With gogo abandoned it isn't like it'll be hard to keep up with upstream, and pulling the tests for this one file in is proving to be quite the battle with out linters, which would happily ignore it if it stayed under vendor.

I guess I could also make a standalone `cockroachlabs/jsonpb` and include that in our deps to get the whole exclusion from lint without forking all of gogo, but I dunno, I'm this has already consumed more fighting with linters than fixing the EmitDefaults bug really seems worth.

**Comment by dt** [comment]
Eh. I think we should probably just fork gogo or make a standalone lib and outside our repo and depend on it -- these tests aren't going to look anything like upstream by the time out linters are happy.

**Pull request closed without merging**
