### PR TITLE
Add the typescript definitions for Angular.

### PR DESCRIPTION
**Pull request by BramGruneir**
And moved the libraries to be under js.

Next up is going to be hooking up the typescript compiler to go generate (and convert our files to typescript).

### CODE REVIEW

**Comment by tamird** [comment]
LGTM. It'd be cool to not have to vendor all this stuff quite so manually: maybe you could hook bower up to go generate to fetch the assets rather than having them checked into the cockroach repo? Something for a follow-on PR.

**Comment by bdarnell** [comment]
LGTM

We have to have everything checked in to remain compatible with `go get`; we don't want to let javascript tools get into the critical path for building the main cockroach binary. Even requiring them for `go generate` makes me nervous.

**Comment by tamird** [comment]
@bdarnell fair point. Still would be nice to be able to update these vendored files with `go generate`, though.

**Comment by bdarnell** [comment]
`go generate` should depend only on the current source tree and not touch the network; we verify in CI that all changes `go generate` would make are checked in. We can and should script the management of these vendored files, but it should be with a separate Makefile target or script and not `go generate`.

**Comment by tamird** [comment]
Fair enough.

**Comment by BramGruneir** [comment]
I used tsd to grab the definitions (but it isn't very polished).
I'd love to script the upgrading, but that will be an exercise for later.

**Pull request merged**
