### PR TITLE
opt: Add CreateTable support to optimizer

### PR DESCRIPTION
**Pull request by andy-kimball**
Add support for the CREATE TABLE statement. The optimizer is most
relevant when an AS clause is used to insert rows into the new table:

  CREATE TABLE t (a, b) AS SELECT x, y FROM xy

Construct createTableNode in execbuilder. Unlike the heuristic planner,
the optimizer projects the initial value for the rowid column when an
AS clause is used in the CREATE TABLE statement.

### CODE REVIEW

**Review by rytaft — CHANGES_REQUESTED** [review]
Reviewed the first commit -- taking a break and will review the others in a bit.

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-:-LVEV7Rm-bwUO_cC8bLF:bl23rbm)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt_catalog.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVEIge-DOxvPGwii8w0:-LVEIge-DOxvPGwii8w1:b9ffoya) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a353b270f357d36cb3c8b53a960c559f360ebd9/pkg/sql/opt_catalog.go#L77)):*
> ```Go
> }
> 
> // ResolveDataSource is part of the cat.Catalog interface.
> ```

ResolveDataSource -> ResolveSchema
___
*[pkg/sql/opt_catalog.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVELoCi0IIDYphHOKYC:-LVELoCi0IIDYphHOKYD:b-l8k6wa) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a353b270f357d36cb3c8b53a960c559f360ebd9/pkg/sql/opt_catalog.go#L83)):*
> ```Go
> 	p.avoidCachedDescriptors = true
> 
> 	// Skip call to ResolveTargetObject, because it assumes that the only use for
> ```

It would help to explain here how `ResolveTarget` is different from `ResolveTargetObject`.
___
*[pkg/sql/opt/metadata.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVEOgbj4aiKW4NcGrKC:-LVEOgbk2UMG2HQTTZtr:bqk0tij) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a353b270f357d36cb3c8b53a960c559f360ebd9/pkg/sql/opt/metadata.go#L132)):*
> ```Go
> }
> 
> // CheckDependencies resolves each data source on which this metadata depends,
> ```

Update comment to include schema
___
*[pkg/sql/opt/cat/data_source.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVER1W64kcU62LS6ws9:-LVER1W64kcU62LS6wsA:b-7xb9g1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a353b270f357d36cb3c8b53a960c559f360ebd9/pkg/sql/opt/cat/data_source.go#L35)):*
> ```Go
> 
> 	// Name returns the fully normalized, fully qualified, and fully resolved
> 	// name of the data source (<db-name>.<schema-name>.<data-source-name>. The
> ```

[nit] missing closing parentheses
___
*[pkg/sql/opt/testutils/testcat/test_catalog.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVET1qG2Kg-r9wbH02j:-LVET1qG2Kg-r9wbH02k:b-3tnzfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a353b270f357d36cb3c8b53a960c559f360ebd9/pkg/sql/opt/testutils/testcat/test_catalog.go#L70)):*
> ```Go
> 	if name.ExplicitSchema {
> 		if name.ExplicitCatalog {
> 			// Already 3 parts: nothing to do.
> ```

should be 2 parts, right?
___
*[pkg/sql/opt/testutils/testcat/test_catalog.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVET9jxB6pay0ZBPk5O:-LVET9jxB6pay0ZBPk5P:bkrnoqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a353b270f357d36cb3c8b53a960c559f360ebd9/pkg/sql/opt/testutils/testcat/test_catalog.go#L74)):*
> ```Go
> 		}
> 
> 		// Two parts: D.T.
> ```

This is just one part, right? Just the schema?
___
*[pkg/sql/opt/testutils/testcat/test_catalog.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVETCKxEQwbkSksY64w:-LVETCKxEQwbkSksY64x:bg2ba5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a353b270f357d36cb3c8b53a960c559f360ebd9/pkg/sql/opt/testutils/testcat/test_catalog.go#L82)):*
> ```Go
> 		}
> 
> 		// No luck so far. Compatibility with CockroachDB v1.1: use D.public.T
> ```

And this should probably be just `D.public`
___
*[pkg/sql/opt/testutils/testcat/test_catalog.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVEU3AeBgBjwwe2oE_Q:-LVEU3AeBgBjwwe2oE_R:b-uoiw28) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a353b270f357d36cb3c8b53a960c559f360ebd9/pkg/sql/opt/testutils/testcat/test_catalog.go#L90)):*
> ```Go
> 	}
> 
> 	// Neither schema or catalog was specified, so use testdb.public.
> ```

testdb -> t

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, 11 of 11 files at r3, 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-:-LVEm3R6DTBZNm2qoLJR:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/create_table.go, line 97 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVEjdXeE7I1YK9bpYoN:-LVEjdXeE7I1YK9bpYoO:b-2mk2jc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11309c9cd5270235744f285d04f8117a338a91f/pkg/sql/create_table.go#L97)):*
> ```Go
> 	// execution. The heuristic planner does this, while the optimizer instead
> 	// adds it as part of the input query.
> 	addRowID bool
> ```

Does this only apply to the case where there is an AS clause? How does the rowid column get created when there is no AS clause?
___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 135 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVEkmY46D8MgEVg9TDT:-LVEkmY5A-71r_wZwN83:bhffr7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11309c9cd5270235744f285d04f8117a338a91f/pkg/sql/opt/exec/execbuilder/relational_builder.go#L135)):*
> ```Go
> 	// `BEGIN; INSERT INTO ...; CREATE TABLE IF NOT EXISTS ...; COMMIT;`
> 	// where the table already exists. This will generate some false
> 	// refreshes, but that's expected to be quite rare in practice.
> ```

what are false refreshes?
___
*[pkg/sql/opt/memo/interner_test.go, line 273 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVEbnWz-3ktthQr7jMP:-LVEbnX-2kvEJktRglsE:b-9yo08o) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e8f6d38302b5330e7f915bec18cbacc082b12b6/pkg/sql/opt/memo/interner_test.go#L273)):*
> ```Go
> 		}},
> 
> 		{hashFn: in.hasher.HashTableID, eqFn: in.hasher.IsTableIDEqual, variations: []testVariation{
> ```

Do you need to add a test for SchemaID?

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33356)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/create_table.go, line 97 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVEjdXeE7I1YK9bpYoN:-LVEnxL06ctRxXh9DXsM:bwy1q1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11309c9cd5270235744f285d04f8117a338a91f/pkg/sql/create_table.go#L97)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Does this only apply to the case where there is an AS clause? How does the rowid column get created when there is no AS clause?
</blockquote></details>

It applies in both cases, as long as the user has not declared a primary key. In the `AS` case, there's no syntax to declare a primary key, so it always happens there.
___
*[pkg/sql/opt_catalog.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVEIge-DOxvPGwii8w0:-LVEoMxKD07cBtG_8Nhg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a353b270f357d36cb3c8b53a960c559f360ebd9/pkg/sql/opt_catalog.go#L77)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

ResolveDataSource -> ResolveSchema
</blockquote></details>

Done.
___
*[pkg/sql/opt_catalog.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVELoCi0IIDYphHOKYC:-LVEpTIm1mSzr_aMTm8p:bgehzm0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a353b270f357d36cb3c8b53a960c559f360ebd9/pkg/sql/opt_catalog.go#L83)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

It would help to explain here how `ResolveTarget` is different from `ResolveTargetObject`.
</blockquote></details>

I rewrote the comment.
___
*[pkg/sql/opt/metadata.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVEOgbj4aiKW4NcGrKC:-LVEpvEY0Auo1slIVnPM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a353b270f357d36cb3c8b53a960c559f360ebd9/pkg/sql/opt/metadata.go#L132)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Update comment to include schema
</blockquote></details>

Done.
___
*[pkg/sql/opt/cat/data_source.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVER1W64kcU62LS6ws9:-LVEpz5V8ycY5WUplzkK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a353b270f357d36cb3c8b53a960c559f360ebd9/pkg/sql/opt/cat/data_source.go#L35)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] missing closing parentheses
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 135 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVEkmY46D8MgEVg9TDT:-LVEq2DsERqihy50KkN8:b-ug5fdr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11309c9cd5270235744f285d04f8117a338a91f/pkg/sql/opt/exec/execbuilder/relational_builder.go#L135)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

what are false refreshes?
</blockquote></details>

I don't know; I copied this comment and code from `planner.newPlan`.
___
*[pkg/sql/opt/memo/interner_test.go, line 273 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVEbnWz-3ktthQr7jMP:-LVEr0jhBh6nZ1KOsMl1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e8f6d38302b5330e7f915bec18cbacc082b12b6/pkg/sql/opt/memo/interner_test.go#L273)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Do you need to add a test for SchemaID?
</blockquote></details>

Done.
___
*[pkg/sql/opt/testutils/testcat/test_catalog.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVET1qG2Kg-r9wbH02j:-LVEr7MI7jPQM-pjf5_B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a353b270f357d36cb3c8b53a960c559f360ebd9/pkg/sql/opt/testutils/testcat/test_catalog.go#L70)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

should be 2 parts, right?
</blockquote></details>

Done.
___
*[pkg/sql/opt/testutils/testcat/test_catalog.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVET9jxB6pay0ZBPk5O:-LVErcmt6dmSfPcVDD0Y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a353b270f357d36cb3c8b53a960c559f360ebd9/pkg/sql/opt/testutils/testcat/test_catalog.go#L74)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This is just one part, right? Just the schema?
</blockquote></details>

Done.
___
*[pkg/sql/opt/testutils/testcat/test_catalog.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVETCKxEQwbkSksY64w:-LVEs4J_DeIOa79hMwEf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a353b270f357d36cb3c8b53a960c559f360ebd9/pkg/sql/opt/testutils/testcat/test_catalog.go#L82)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

And this should probably be just `D.public`
</blockquote></details>

Done.
___
*[pkg/sql/opt/testutils/testcat/test_catalog.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVEU3AeBgBjwwe2oE_Q:-LVEs8XX3LvSbI9ikg3Y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a353b270f357d36cb3c8b53a960c559f360ebd9/pkg/sql/opt/testutils/testcat/test_catalog.go#L90)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

testdb -> t
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 4 of 26 files at r5, 4 of 4 files at r6, 11 of 11 files at r7, 8 of 8 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33356)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/create_table.go, line 97 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVEjdXeE7I1YK9bpYoN:-LVJJsyRB853Ikc5m6gf:b-z0pjzv) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11309c9cd5270235744f285d04f8117a338a91f/pkg/sql/create_table.go#L97)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

It applies in both cases, as long as the user has not declared a primary key. In the `AS` case, there's no syntax to declare a primary key, so it always happens there.
</blockquote></details>

But in the `optbuilder` code it looks like you're only synthesizing the `rowid` column if there is an `AS` clause. Did I miss something?
___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 135 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVEkmY46D8MgEVg9TDT:-LVJKWlo5IDfu1pEuKWt:bnuxo06) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11309c9cd5270235744f285d04f8117a338a91f/pkg/sql/opt/exec/execbuilder/relational_builder.go#L135)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I don't know; I copied this comment and code from `planner.newPlan`.
</blockquote></details>

Ok -- seems to me like the comment is more confusing than helpful... Can you either remove it or rewrite it a bit?

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33356)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/create_table.go, line 97 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVEjdXeE7I1YK9bpYoN:-LVJMgQSDTgarxoeZ_Nz:b-mxghjk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11309c9cd5270235744f285d04f8117a338a91f/pkg/sql/create_table.go#L97)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

But in the `optbuilder` code it looks like you're only synthesizing the `rowid` column if there is an `AS` clause. Did I miss something?
</blockquote></details>

I see what you're asking. This flag is not about adding a column to the _table_ (which happens whether or not the `AS` clause is present). It's about adding a column to the _input_, in order to provide the default value for the column. That only happens when the `AS` clause is present. I changed the code and comments to try and make this more clear.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33356)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/create_table.go, line 97 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVEjdXeE7I1YK9bpYoN:-LVJS77pELJyN7sR4E3i:b-qn06j7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11309c9cd5270235744f285d04f8117a338a91f/pkg/sql/create_table.go#L97)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I see what you're asking. This flag is not about adding a column to the _table_ (which happens whether or not the `AS` clause is present). It's about adding a column to the _input_, in order to provide the default value for the column. That only happens when the `AS` clause is present. I changed the code and comments to try and make this more clear.
</blockquote></details>

Great - thanks!

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33356)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 135 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVEkmY46D8MgEVg9TDT:-LVP0aFZCQAJlav6w7dh:b3tbcna) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11309c9cd5270235744f285d04f8117a338a91f/pkg/sql/opt/exec/execbuilder/relational_builder.go#L135)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Ok -- seems to me like the comment is more confusing than helpful... Can you either remove it or rewrite it a bit?
</blockquote></details>

I'd rather keep it in, because it might be helpful in the future if we ever need to look more closely into what this is doing. It's confusing now because we don't understand enough details about how the system schema works. But I assume it's perfectly clear to Vivek et. al. who do understand it well. I did change it a bit to be "some false schema cache refreshes", since I assume it's referring to cases where we have to invalidate the schema cache and then refresh it.

**Comment by rytaft** [comment]
___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 135 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVEkmY46D8MgEVg9TDT:-LVPGKv24oRLVMUPbtGq:bpdgb2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11309c9cd5270235744f285d04f8117a338a91f/pkg/sql/opt/exec/execbuilder/relational_builder.go#L135)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I'd rather keep it in, because it might be helpful in the future if we ever need to look more closely into what this is doing. It's confusing now because we don't understand enough details about how the system schema works. But I assume it's perfectly clear to Vivek et. al. who do understand it well. I did change it a bit to be "some false schema cache refreshes", since I assume it's referring to cases where we have to invalidate the schema cache and then refresh it.
</blockquote></details>

Ok makes sense. Looks like you didn't push your changes, though.

**Comment by andy-kimball** [comment]
___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 135 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVEkmY46D8MgEVg9TDT:-LVPfDoL4217okKotcdi:btu9l0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11309c9cd5270235744f285d04f8117a338a91f/pkg/sql/opt/exec/execbuilder/relational_builder.go#L135)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Ok makes sense. Looks like you didn't push your changes, though.
</blockquote></details>

Whoops, I'll just add it to my other Upsert checkin.

**Review by RaduBerinde — COMMENTED** [review]
Sorry for the late review, I just have one (nitty) question.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-:-LVQaQyx2hmcH3WzHVYA:b93yb2m)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/memo.go, line 275 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVQ_eTu3vimXXx8_Na6:-LVQ_eTu3vimXXx8_Na7:b763zur) ([raw file](https://github.com/cockroachdb/cockroach/blob/09532f8be7967e0a279707b2bbf2a4a50c2bb991/pkg/sql/opt/memo/memo.go#L275)):*
> ```Go
> 	// access the object.
> 	if depsUpToDate, err := m.Metadata().CheckDependencies(ctx, catalog); err != nil {
> 		return true, err
> ```

What's the reason for this change? The usual semantics are to ignore any other returns in error cases, unless it's explicitly documented otherwise. I don't think any calling code looks at the bool if there is an error, and logically it wouldn't make sense (if we encounter an error, we definitely can't assume it's not stale).

**Comment by andy-kimball** [comment]
___
*[pkg/sql/opt/memo/memo.go, line 275 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/33356#-LVQ_eTu3vimXXx8_Na6:-LVRNfnFCtefy5wN6wmz:br3zadc) ([raw file](https://github.com/cockroachdb/cockroach/blob/09532f8be7967e0a279707b2bbf2a4a50c2bb991/pkg/sql/opt/memo/memo.go#L275)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

What's the reason for this change? The usual semantics are to ignore any other returns in error cases, unless it's explicitly documented otherwise. I don't think any calling code looks at the bool if there is an error, and logically it wouldn't make sense (if we encounter an error, we definitely can't assume it's not stale).
</blockquote></details>

You're right that it shouldn't matter, but it was my "defense in depth" instinct kicking in. If a caller forgets to check the error and only look at the boolean, it's better that they assume the memo is stale.

**Pull request merged**
