### PR TITLE
cli: add bulkingest workload to main binary

### PR DESCRIPTION
**Pull request by dt**
Release note: none

### CODE REVIEW

**Comment by danhhz** [comment]
This PR makes me realize that workload registration is currently conflating two things. First is making them available for things like the IMPORT magic. Second is making them available as subcommands of `./cockroach workload`. You need this for the first one (I'm assuming), but so far the second one has been a more curated list (that the docs team keeps documented). Correct me if I'm wrong, but is this more for our internal testing than something an external user might want to use?

I think it'd be pretty easy to have a second set of "internal" registrations to mirror the current list. Anything that was registered in either list would be eligible for the IMPORT magic, but the cli parts of the second list would be somewhere else, probably under debug. Strawman: `./cockroach debug workload-internal fixtures import bulkingest.

**Comment by dt** [comment]
yeah, I'd say we should have a flag on the `Workload` that indicates if it is Public

**Comment by danhhz** [comment]
counterproposal: instead of
```
func init() {
	workload.Register(fooMeta)
}
```

it would have (mod name bikeshed)
```
func init() {
	workload.RegisterInternal(fooMeta)
}
```

**Comment by dt** [comment]
hmm, and that would in turn put it in a separate `registered` map, and then have the getters and such look in both? 

Or would it just flip a flag on the workload and put it in the same map?

I think I have a slight preference for just keeping them all together and filtering only when listing for display and thus a flag on the workload, but I guess I don't really care about whether it is set inline or during registration by one of two methods. I guess my preference isn't too strong though in either case.

**Comment by dt** [comment]
added a second commit to hide workloads marked as Internal from cli help when doing user-facing binary, and a `RegisterInternal` func that flips that bit before registering.

**Review by danhhz — COMMENTED** [review]
:lgtm: thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35135#-:-LZa4ZMq6gnhPwZfFD-H:brfqlux)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz and @dt)

___
*[pkg/workload/workload.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35135#-LZa3F8r2m60hA1Wpx6C:-LZa3F8r2m60hA1Wpx6D:bet7gbv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f5e78702b49d88122ce9dc5cd762ad4ebfa0919/pkg/workload/workload.go#L128)):*
> ```Go
> 	// own evaluations) and thus may not be as well documented or publicized (e.g.
> 	// in command-line help) as other workloads.
> 	Internal bool
> ```

Invert the semantics of the bool, please. The zero value should be the more common (and less "scary") case of not exposing this to users.
___
*[pkg/workload/workload.go, line 213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35135#-LZa3JEv7YfjkwkJlKtD:-LZa3JEv7YfjkwkJlKtE:bn44e3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f5e78702b49d88122ce9dc5cd762ad4ebfa0919/pkg/workload/workload.go#L213)):*
> ```Go
> 
> // RegisterInternal marks a workload as for internal usage and registers it.
> func RegisterInternal(m Meta) {
> ```

I was thinking two maps, but now that I see it, I like the bool on meta better. Agree that if we're doing it this way, the second Register method isn't necessary.
___
*[pkg/workload/cli/run.go, line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35135#-LZa3Yk50RjIFDXL3nRE:-LZa3Yk50RjIFDXL3nRF:b-p5dedj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f5e78702b49d88122ce9dc5cd762ad4ebfa0919/pkg/workload/cli/run.go#L86)):*
> ```Go
> 			genInitCmd.Run = CmdHelper(gen, runInit)
> 			if userFacing && meta.Internal {
> 				genInitCmd.Hidden = true
> ```

hidden is much better than a second tree under debug. nice!

**Review by dt — COMMENTED** [review]
While I was here, I kept getting annoyed at the big ugly KV help text so I tried to clean that up too.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35135#-:-LZaB6WbENfvXUtx6vDL:b5o80bi)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/workload/workload.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35135#-LZa3F8r2m60hA1Wpx6C:-LZa61pd7_r1OAuqIsOK:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f5e78702b49d88122ce9dc5cd762ad4ebfa0919/pkg/workload/workload.go#L128)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Invert the semantics of the bool, please. The zero value should be the more common (and less "scary") case of not exposing this to users.
</blockquote></details>

Done
___
*[pkg/workload/workload.go, line 213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35135#-LZa3JEv7YfjkwkJlKtD:-LZaB2oSCJs3uumypOCo:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f5e78702b49d88122ce9dc5cd762ad4ebfa0919/pkg/workload/workload.go#L213)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I was thinking two maps, but now that I see it, I like the bool on meta better. Agree that if we're doing it this way, the second Register method isn't necessary.
</blockquote></details>

Done

**Pull request merged**
