### PR TITLE
stats: adaptive throttling of auto stats

### LINKED ISSUE #35346: opt: Create statistics jobs taking too long
**Describe the problem**

Stats look hung in the webui:
image

`Show Jobs`
```
root@localhost:26257/defaultdb> show jobs;
        job_id       |   job_type   |                                                 description                                                  | user_name |  status   | running_status |             created              |             started              |             finished             |             modified             | fraction_completed | error | coordinator_id
+--------------------+--------------+--------------------------------------------------------------------------------------------------------------+-----------+-----------+----------------+----------------------------------+----------------------------------+----------------------------------+----------------------------------+--------------------+-------+----------------+
  431363664286449665 | CREATE STATS | CREATE STATISTICS __auto__ FROM [60] AS OF SYSTEM TIME '-30s'                                                | root      | running   | NULL           | 2019-03-04 15:09:03.251493+00:00 | 2019-03-04 15:09:03.255912+00:00 | NULL                             | 2019-03-04 15:18:57.213032+00:00 |                  0 |       |              1
  431363361037877249 | CREATE STATS | CREATE STATISTICS __auto__ FROM [59] AS OF SYSTEM TIME '-30s'                                                | root      | succeeded | NULL           | 2019-03-04 15:07:30.707371+00:00 | 2019-03-04 15:07:30.712102+00:00 | 2019-03-04 15:09:03.24189+00:00  | 2019-03-04 15:09:03.24189+00:00  |                  1 |       |              1
  431363345394040833 | CREATE STATS | CREATE STATISTICS __auto__ FROM [58] AS OF SYSTEM TIME '-30s'                                                | root      | succeeded | NULL           | 2019-03-04 15:07:25.933245+00:00 | 2019-03-04 15:07:25.937884+00:00 | 2019-03-04 15:07:30.697574+00:00 | 2019-03-04 15:07:30.697575+00:00 |                  1 |       |              1
  431363299113992193 | CREATE STATS | CREATE STATISTICS __auto__ FROM [57] AS OF SYSTEM TIME '-30s'                                                | root      | succeeded | NULL           | 2019-03-04 15:07:11.809693+00:00 | 2019-03-04 15:07:11.814122+00:00 | 2019-03-04 15:07:25.923187+00:00 | 2019-03-04 15:07:25.923188+00:00 |                  1 |       |              1
  431363297093386241 | CREATE STATS | CREATE STATISTICS __auto__ FROM [56] AS OF SYSTEM TIME '-30s'                                                | root      | succeeded | NULL           | 2019-03-04 15:07:11.193052+00:00 | 2019-03-04 15:07:11.197848+00:00 | 2019-03-04 15:07:11.799813+00:00 | 2019-03-04 15:07:11.799814+00:00 |                  1 |       |              1
  431363270582370305 | CREATE STATS | CREATE STATISTICS __auto__ FROM [55] AS OF SYSTEM TIME '-30s'                                                | root      | succeeded | NULL           | 2019-03-04 15:07:03.102537+00:00 | 2019-03-04 15:07:03.10715+00:00  | 2019-03-04 15:07:11.18345+00:00  | 2019-03-04 15:07:11.183451+00:00 |                  1 |       |              1
  431362431262982145 | RESTORE      | RESTORE TABLE tpch.* FROM 'gs://cockroach-fixtures/workload/tpch/scalefactor=1/backup' WITH into_db = 'tpch' | root      | succeeded | NULL           | 2019-03-04 15:02:46.962591+00:00 | 2019-03-04 15:02:46.968325+00:00 | 2019-03-04 15:05:57.58245+00:00  | 2019-03-04 15:05:57.582451+00:00 |                  1 |       |              1
(7 rows)

Time: 3.328167ms
```

**To Reproduce**

Setup SQL 20 and compelted the initial restore. Did not run any load. 

**Expected behavior**
Progress to be made on the job and the job to have already completed. The cluster is small so this should be a fast job:
image

**Environment:**
v19.1.0-beta.20190225-281-gfb3c5c0

### PR DESCRIPTION
**Pull request by RaduBerinde**
We currently throttle statistics by doing a bit of work and then
sleeping 9x longer than it took to do the work; this is done to avoid
impacting running workloads.

There are two problems with this:

 - the stats can take a very long time even if the cluster is idle.
   This is counter-intuitive and on large datasets it can take many
   hours until all the stats are populated.

 - even worse, the throttling mechanism is very inefficient when CPU
   load is low; by sleeping for relatively long periods, we allow the
   CPU to go into a deeper power-saving state which makes it run
   slower for a little while after it wakes up (all the caches are
   gone, and other things like that). This effect is more significant
   than it sounds: we see stat runs on idle clusters that take 10
   minutes without throttling but 2-3 hours with throttling (instead
   of 90 minutes).

This change makes the throttling adaptive. Throughout the run, we look
at the current value of the `sys.cpu.combined.percent-normalized`
metric, which is the average CPU usage of the CRDB process over all
cores in the last 10 seconds (it is updated every 10 seconds). When
this usage is under 25%, we don't throttle; when it is over 75%, we
throttle to the maximum configured value; in-between we interpolate
linearly.

This is not something that can be tested reliably in an automated
fashion. I wrote a manual test that can be run with a special flag.
The intention is that we will run this test manually if we make any
changes to the throttling logic.

Fixes #35346.

Release note (bug fix): Automatic statistic jobs should be much faster
on clusters with low load.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
Nice! :lgtm: 

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35698#-:-L_sbP6OAT0n6fAhCvZz:bfd61qr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @RaduBerinde)

___
*[pkg/sql/distsqlpb/processors.proto, line 776 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35698#-L_sYW1uDyeYjl1Y42vo:-L_sYW1uDyeYjl1Y42vp:b-vcmyv1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae54dc3d34d5096a026ba29d131ad34a4c4f979a/pkg/sql/distsqlpb/processors.proto#L776)):*
> ```protobuf
>   // Currently, this field is set only for automatic statistics based on the
>   // value of the cluster setting
>   // sql.stats.experimental_automatic_collection.fraction_idle.
> ```

perhaps we should update the name of the cluster setting too?
___
*[pkg/sql/distsqlrun/sampler.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35698#-L_sZOS52PUR3LIpd1OI:-L_sZOS52PUR3LIpd1OJ:b1dboj7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae54dc3d34d5096a026ba29d131ad34a4c4f979a/pkg/sql/distsqlrun/sampler.go#L218)):*
> ```Go
> 
> 			if s.maxFractionIdle > 0 {
> 				// Look at CRDB's average CPU usage in the last 10 seconds (0 to 1):
> ```

[nit] does (0 to 1) refer to the range of possible CPU usage values? It's a bit unclear as-is.
___
*[pkg/sql/stats/automatic_stats_manual_test.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35698#-L_sabg79EDjApgQYPe_:-L_sabg87BvSOWEQqEJQ:b-x1s4ja) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae54dc3d34d5096a026ba29d131ad34a4c4f979a/pkg/sql/stats/automatic_stats_manual_test.go#L58)):*
> ```Go
> //     automatic_stats_manual_test.go:72: Create stats took 15.886412857s
> //
> func TestAdaptiveThrottling(t *testing.T) {
> ```

Nice test! Isn't this the sort of thing that `roachtests` are used for? Maybe it could be run on a nightly or weekly basis?

**Comment by RaduBerinde** [comment]
Switched to using a `RuntimeStats` interface so we don't directly use `server/status` from `sql`.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35698)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @rytaft)

___
*[pkg/sql/distsqlpb/processors.proto, line 776 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35698#-L_sYW1uDyeYjl1Y42vo:-L_sd8jE35ptB4LuguQz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae54dc3d34d5096a026ba29d131ad34a4c4f979a/pkg/sql/distsqlpb/processors.proto#L776)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

perhaps we should update the name of the cluster setting too?
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/sampler.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35698#-L_sZOS52PUR3LIpd1OI:-L_sdJhtAG3b7KaEtyVQ:bhm3b5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae54dc3d34d5096a026ba29d131ad34a4c4f979a/pkg/sql/distsqlrun/sampler.go#L218)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] does (0 to 1) refer to the range of possible CPU usage values? It's a bit unclear as-is.
</blockquote></details>

Removed since the scale is not relevant in this code, it's only relevant for the values of the constants (0.25, 0.75) where it's already clear.
___
*[pkg/sql/stats/automatic_stats_manual_test.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35698#-L_sabg79EDjApgQYPe_:-L_sbrTE8LDOvnJXqkPs:bhiq7bu) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae54dc3d34d5096a026ba29d131ad34a4c4f979a/pkg/sql/stats/automatic_stats_manual_test.go#L58)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Nice test! Isn't this the sort of thing that `roachtests` are used for? Maybe it could be run on a nightly or weekly basis?
</blockquote></details>

It would need to have a passing criteria if we want to run them periodically but it kind of has to be eyeballed.  The "synthetic" cpu usage would be difficult to achieve with roachtests (here we are inside the cockroach process).

**Review by rytaft — APPROVED** [review]
> Reviewed 4 of 4 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35698)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball)

___
*[pkg/sql/stats/automatic_stats_manual_test.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35698#-L_sabg79EDjApgQYPe_:-L_sfBXS7ce_uR85e16U:b2ni9b4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae54dc3d34d5096a026ba29d131ad34a4c4f979a/pkg/sql/stats/automatic_stats_manual_test.go#L58)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It would need to have a passing criteria if we want to run them periodically but it kind of has to be eyeballed.  The "synthetic" cpu usage would be difficult to achieve with roachtests (here we are inside the cockroach process).
</blockquote></details>

ok!

**Comment by RaduBerinde** [comment]
Filed #35747 for the test flake.

bors r+

**Comment by RaduBerinde** [comment]
Hit #35549.

bors r+

**Comment by RaduBerinde** [comment]
Hit #35758.

bors r+

**Pull request merged**
