### PR TITLE
release-23.1: sql: fix formatting of export and changefeed

### PR DESCRIPTION
**Pull request by annrpom**
Informs: #99185

This commit cherry-picked changes from #107892.

Release note: None
Fixes: #108254 and #108233 (partially)
Release justification: fixes bug with random syntax generation

### CODE REVIEW

**Review by jayshrivastava — APPROVED** [review]
LGTM! The change itself looks good to me, but can you explain how it fixes the randomized test? Just for my own understanding.

**Comment by miretskiy** [comment]
I'm also curious... We always supported `WITH OPTIONS`, but the options was ... well, optional.  Is this now recommended to use?  I'm not too sure if this raises to the backport level though.  Do we need it?

**Comment by annrpom** [comment]
@jayshrivastava from my understanding, TestRandomSyntaxGeneration has failed before with the same pattern - this is a very specific case due to the fact that a `BUCKET_COUNT` option that is not wrapped with `OPTIONS (...)` gets converted to the other `WITH BUCKET_COUNT` syntax (mentioned https://github.com/cockroachdb/cockroach/pull/107185 and demonstrated in the lexer: https://github.com/cockroachdb/cockroach/blob/da6a7c4a36a30ce184813dcf8d944fdd90badff3/pkg/sql/parser/lexer.go#L245-L249). thus, `CREATE CHANGEFEED ... WITH_LA bucket_count;` is actually the statement that is being parsed - causing the syntax error that we see:

```
sql="CREATE CHANGEFEED FOR SURVIVE . ident . FAMILY , ISERROR INTO PLACEHOLDER WITH OPTIONS ( BUCKET_COUNT )", formattedSQL="CREATE CHANGEFEED FOR TABLE survive.ident.family, TABLE \"iserror\" INTO 'placeholder' WITH bucket_count": at or near "with": syntax error
```

@miretskiy that's a good question - `WITH` and `WITH OPTIONS` both should be supported (except in the special case of bucket_count), but the tests don't really reflect that... I will be adding the `WITH` tests back in with a new PR

**Comment by rafiss** [comment]
> Do we need it?

Yes, otherwise https://github.com/cockroachdb/cockroach/issues/108254 will continue failing. In general, it's a good idea to make sure any statement can roundtrip format->parse->format. In some cases, that is actually critical.

**Comment by jayshrivastava** [comment]
https://github.com/cockroachdb/cockroach/issues/108254 fails because this SQL
```
CREATE CHANGEFEED FOR SURVIVE . ident . FAMILY , ISERROR INTO PLACEHOLDER WITH OPTIONS ( BUCKET_COUNT )
```
Formats to
```
CREATE CHANGEFEED FOR TABLE survive.ident.family, TABLE \"iserror\" INTO 'placeholder' WITH bucket_count
```
The latter cannot be parsed because it uses a reserved keyword `bucket_count`. This change fixes it by making sure we format KV options like this, so it can be parsed. 
```
CREATE CHANGEFEED FOR TABLE survive.ident.family, TABLE \"iserror\" INTO 'placeholder' WITH (bucket_count)
```

I think the real problem is that both statements (with and without brackets) should be equivalent, but they are not. One can be parsed and the other cannot.

**Comment by jayshrivastava** [comment]
Actually on second thought, maybe they aren't equivalent. Using brackets allows you to pass in reserved keywords and missing brackets does not let you pass them in. 

Nevertheless, I think it's better to format the statement using brackets because we would want formatting to produce the most a parseable output.

**Pull request merged**
