### PR TITLE
acceptance: bidir and forward reference tests

### PR DESCRIPTION
**Pull request by danhhz**
Split the ReadWrite reference test into one that tests bidirectional
compatibility and one that tests forward-only.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7106)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[acceptance/reference_test.go, line 73 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7106#-KJlEpWWVkMyHuroN6Dl:-KJlEpWWVkMyHuroN6Dm:1451212349) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc3c2fd566d3b000204af1b572fb19748f501f36/acceptance/reference_test.go#L73)):*
> ```Go
> 
> func TestDockerReadWriteForwardReferenceVersion(t *testing.T) {
> 	func() { // OneShot assumes it is at specific call depth from TestFoo.
> ```

i think you can extract this function without messing up OneShot's assumptions

---

*[acceptance/reference_test.go, line 83 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7106#-KJlF-oxK9LJ_fbteP6J:-KJlF-oyYb10ktvr_vQY:-1983810697) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc3c2fd566d3b000204af1b572fb19748f501f36/acceptance/reference_test.go#L83)):*
> ```Go
> cd /old
> 
> export PGHOST=localhost
> ```

can this be done without copying the entire test? hard to tell the difference currently.

---

*[acceptance/util_test.go, line 241 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7106#-KJlEb3hyNBrb6y25wDy:-KJlEb3hyNBrb6y25wDz:1040730947) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc3c2fd566d3b000204af1b572fb19748f501f36/acceptance/util_test.go#L241)):*
> ```Go
> 
> const (
> 	// NB: postgresTestTag is grepped for in circle-deps.sh, so don't rename it.
> ```

nit: separate commit for this stuff =/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7106)*

**Comment by paperstreet** [comment]
TFTR!

<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> #### acceptance: bidir and forward reference tests
> 
> Split the ReadWrite reference test into one that tests bidirectional
> 
> compatibility and one that tests forward-only.
> 
> 
> 
</details>


---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[acceptance/reference_test.go, line 73 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7106#-KJlEpWWVkMyHuroN6Dl:-KJlLloGKJEYzCMF73h8:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc3c2fd566d3b000204af1b572fb19748f501f36/acceptance/reference_test.go#L73)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> i think you can extract this function without messing up OneShot's assumptions
</details>
Done.

---

*[acceptance/reference_test.go, line 83 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7106#-KJlF-oxK9LJ_fbteP6J:-KJlLlTJdvG-7WK2viNc:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc3c2fd566d3b000204af1b572fb19748f501f36/acceptance/reference_test.go#L83)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can this be done without copying the entire test? hard to tell the difference currently.
</details>
Done.

---

*[acceptance/util_test.go, line 241 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7106#-KJlEb3hyNBrb6y25wDy:-KJlLjsem7HxOBxUQt-j:201294969) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc3c2fd566d3b000204af1b572fb19748f501f36/acceptance/util_test.go#L241)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: separate commit for this stuff =/
</details>
Fair point

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7106#-:-KJqDEwI7NGzYGjz-NYn:-485616692)*

**Comment by dt** [comment]
:lgtm:

<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> TFTR!
</details>


---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7106#-:-KJqGH-hHZOcUq2IsNIZ:1417088721)*

**Comment by tamird** [comment]
:lgtm:

<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> :lgtm:
</details>


---

Reviewed 1 of 1 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7106#-:-KJqQFEY9ueTeEaYf2xc:1417088721)*

**Pull request merged**
