### PR TITLE
sql: support \\ in regexp_replace

### LINKED ISSUE #19046: sql: regexp_replace backreference escapes
**BUG REPORT**

1. cockroach version (git latest)
Build Tag:    v1.2-alpha.20170901-617-g5e8f3a6fe
Build Time:   2017/10/04 23:00:46
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.9
C Compiler:   gcc 7.2.0
Build SHA-1:  5e8f3a6fe180e7c697635be06ebbb0bd7159b697
Build Type:   development

2. Please describe the issue you observed:
the builtin function regexp_replace does not properly escape the back references

- What did you do?
`select regexp_replace('ReRe','R(e)','1\\1','g');`
- What did you expect to see? 
`1\11\1`
- What did you see instead?
`1\e1\e`

### PR DESCRIPTION
**Pull request by justinj**
Fixes #19046.

I tried to find a way to augment the existing code here to support this,
but I couldn't find a nice way to do it, so I had to change the inner
loop around.

### CODE REVIEW

**Comment by knz** [comment]
It's ok, but please add more explanatory comments.

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/builtins.go, line 2617 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19168#-Kw9Wzy6GdD8--9KdPGX:-Kw9Wzy6GdD8--9KdPGY:b15t4tt) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c6118aed9ff2ee342eddbe7456a404ff946d9f3/pkg/sql/parser/builtins.go#L2617)):*
> ```Go
> 	// pattern.
> 	for _, matchIndex := range patternRe.FindAllStringSubmatchIndex(s, matchCount) {
> 		matchStart := matchIndex[0]
> ```

Remind in a comment to the reader the layout of matchIndex.

---

*[pkg/sql/parser/builtins.go, line 2624 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19168#-Kw9WboKOLOeY2HBSZoc:-Kw9WboKOLOeY2HBSZod:bqnvmd5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c6118aed9ff2ee342eddbe7456a404ff946d9f3/pkg/sql/parser/builtins.go#L2624)):*
> ```Go
> 		newString.WriteString(preMatch)
> 
> 		chunkStart := 0
> ```

Explain what `chunkStart` and `i` refer to in the code below, in a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19168#-:-Kw9X5ePXroeGiFkTcSa:b-2e7vxk)*

**Comment by justinj** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/parser/builtins.go, line 2617 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19168#-Kw9Wzy6GdD8--9KdPGX:-KwAUxnu45KraJseiWxJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c6118aed9ff2ee342eddbe7456a404ff946d9f3/pkg/sql/parser/builtins.go#L2617)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Remind in a comment to the reader the layout of matchIndex.
</blockquote></details>

Done.

---

*[pkg/sql/parser/builtins.go, line 2624 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19168#-Kw9WboKOLOeY2HBSZoc:-KwAVmahYkp1NER3mupv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c6118aed9ff2ee342eddbe7456a404ff946d9f3/pkg/sql/parser/builtins.go#L2624)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Explain what `chunkStart` and `i` refer to in the code below, in a comment.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19168)*

**Comment by knz** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/parser/builtins.go, line 2617 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19168#-Kw9Wzy6GdD8--9KdPGX:-KwAb-RSBdSNz9itWWjQ:begv2vl) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c6118aed9ff2ee342eddbe7456a404ff946d9f3/pkg/sql/parser/builtins.go#L2617)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

what is the layout of matchIndex?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19168)*

**Comment by justinj** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/parser/builtins.go, line 2617 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19168#-Kw9Wzy6GdD8--9KdPGX:-KwAdjdTqfZ6EucltQzL:b-x11fcl) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c6118aed9ff2ee342eddbe7456a404ff946d9f3/pkg/sql/parser/builtins.go#L2617)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

what is the layout of matchIndex?
</blockquote></details>

There's a comment from before this PR right above here that explains it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19168)*

**Comment by knz** [comment]
:lgtm:

consider cherry-pick into 1.1

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/parser/builtins.go, line 2617 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19168#-Kw9Wzy6GdD8--9KdPGX:-KwAfv1KJErblqmfZFiw:b9xkzgf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c6118aed9ff2ee342eddbe7456a404ff946d9f3/pkg/sql/parser/builtins.go#L2617)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

There's a comment from before this PR right above here that explains it.
</blockquote></details>

Huh somehow Reviewable was hiding it from me. Bad reviewable, bad.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19168#-:-KwAfzZkQeqPd27vp_T6:b-960bwr)*

**Comment by justinj** [comment]
Are we still cherry-picking into 1.1.0? Or would this be 1.1.1?

**Comment by knz** [comment]
the patches you cherry-pick into the release-1.1 branch will be automatically included in 1.1.1. It's too late to cherry-pick into "1.1" now.

**Comment by nvanbenschoten** [comment]
:lgtm: nice change!

---

Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/builtins.go, line 2634 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/19168#-KwB9_MdLyPFQkgUsS0-:-KwB9_MeQxw18vVJrFMo:b-uj5fb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f8711f2663703dcfe084613476ca1236279d428/pkg/sql/parser/builtins.go#L2634)):*
> ```Go
> 		i := 0
> 		for i < len(to) {
> 			if to[i] == '\\' && i+1 < len(to) {
> ```

Do we have a test for the replacement string having a single `\` at the end of the pattern? In other words, one where `to[i] == '\\' && i+1 == len(to)`?

---

*[pkg/sql/parser/builtins.go, line 2640 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/19168#-KwBABko1RpI7Aid0noj:-KwBABko1RpI7Aid0nok:bgioyuj) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f8711f2663703dcfe084613476ca1236279d428/pkg/sql/parser/builtins.go#L2640)):*
> ```Go
> 					newString.WriteString(to[chunkStart:i])
> 					chunkStart = i + 1
> 				} else if '0' <= to[i] && to[i] <= '9' || to[i] == '&' {
> ```

nit: `('0' <= to[i] && to[i] <= '9')` to avoid ambiguity

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19168#-:-KwBAUQbqAYe-jGX-UZb:b-iu510j)*

**Comment by justinj** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/parser/builtins.go, line 2634 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/19168#-KwB9_MdLyPFQkgUsS0-:-KwDkbhrEyuUX1pKxrJ3:b-48vilg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f8711f2663703dcfe084613476ca1236279d428/pkg/sql/parser/builtins.go#L2634)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we have a test for the replacement string having a single `\` at the end of the pattern? In other words, one where `to[i] == '\\' && i+1 == len(to)`?
</blockquote></details>

Good call, done.

---

*[pkg/sql/parser/builtins.go, line 2640 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/19168#-KwBABko1RpI7Aid0noj:-KwDkZq_rpbeShTiIjob:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f8711f2663703dcfe084613476ca1236279d428/pkg/sql/parser/builtins.go#L2640)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: `('0' <= to[i] && to[i] <= '9')` to avoid ambiguity
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19168)*

**Comment by justinj** [comment]
TFTRs!

**Pull request merged**
