### PR TITLE
sql: enable referring to columns symbolically

### PR DESCRIPTION
**Pull request by knz**
This patch introduces a new semantic concept that is useful for
pretty-printing the AST back to valid SQL and again back to AST; this
will be useful during development work on optimizations. The
motivation is detailed below.

A side effect is that it also introduces a user-visible feature.
Because it is visible to user it will need to be documented, but some
caveats apply. More details are given below too.

**Motivation**

During optimizations, column references (IndexedVar) can move around
and be substituted in ways that may lose track of the original name
used in the query to name the column. More specifically, we can move a
reference to a position where there is no name known for the column
*yet*. For example we want to go from:

  `SELECT * FROM (SELECT * FROM (VALUES (1), (2))) AS a(x) WHERE x > 2`

to:

  `SELECT * FROM (SELECT * FROM ... WHERE ??? > 2) AS a(x)`

Now although we can move the IndexedVar to the position in the `???`
it is not so clear which *name* to give this indexed var if we
pretty-print the resulting tree -- in this example the name "x" does
not exist at that position.

This patch makes it possible to side-step this issue, by introducing a
new SQL syntax that refers to columns at the "current level" by ordinal
position: "@N" where N is an integer literal.

With this patch the example above can then be reliably serialized to:

  `SELECT * FROM (SELECT * FROM ... WHERE @1 > 2) AS a(x)`

**User-visible changes**

SQL already has a traditional, limited way to do refer to column
numerically in some syntactic positions, specifically ORDER BY and
GROUP BY.  For example, in `SELECT a + b FROM foo ORDER BY 1`, "1"
refers to the first value rendered, i.e. `a + b`.

These are called "column ordinals"; they are supported in *some* SQL
engines, sometimes for backward compatibility, sometimes because of
historical reasons.

The feature added in this patch complements and extends this mechanism.

**However, the use of column ordinals by client applications is also
customarily strongly discouraged.** The use of the new column ordinal
references added in this patch should be equally discouraged. The
reason why is that they are not robust against schema updates. Say, a
table is initially created with columns `a, b, c` in this order. Then
a query is designed to refer to column `a` by position, with number 1. 
Then later, independently a DB admin changes the schema and removes
column `a`, and adds a new version of column `a` with e.g. a different
type. Now the schema is `b, c, a`, and all the queries that expect to
refer to `a` by position 1 are now broken. The new feature in this
patch is also subject to this limitation. It is intended primarily for
use during development when the schema updates are tightly controlled
by the operator manipulating the query.

Meanwhile, since the feature is visible to users it should still be
(minimally) documented. The salient aspects that should be
communicated are:

1) don't use this feature in client applications unless you 100%
   understand the limitation described above.

2) **the @ notation refers to a column number in the data source, not
   in the rendered columns**. The data source is the thing named after
   FROM.  For example, suppose a table `foo` has columns `a` and `b`
   in this order. Then the query

     `SELECT b, a FROM foo WHERE @2 = 123`

   is equivalent to `SELECT b, a FROM foo WHERE b = 123`.

3) point 2 above means that there is a difference between the new
   column ordinal references and the traditional SQL ordinals, which
   can be illustrated as follows. With SQL ordinals, the query

     `SELECT b, a FROM foo ORDER BY 1`

   sorts with column `b`, because this is the first value rendered
   (columns after SELECT); whereas

     `SELECT b, a FROM foo ORDER BY @1`

   sorts with column `a`, because this is the first column in the data
   source (columns after FROM).

This feature is needed for #10632.

cc @nvanbenschoten.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10729)

### CODE REVIEW

**Comment by knz** [comment]
I just realized I forgot to add the tests. Please comment on the general direction, I'll add the tests in parallel.

**Comment by RaduBerinde** [comment]
Nice, I like this idea! Seems like something we should use for distsql (I'm currently using `$0, $1, ..`). Though I would still need to have my own visitor which does just the `OrdinalReference->IndexedVar` conversion.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10729#-:-KWmUzrHgTGtDwPkQi9h:bu2z1cs)*

**Comment by nvanbenschoten** [comment]
LGTM so far, but as you mentioned this needs lots of testing.

Also, this is introducing new syntax into SQL, so I'd like to think through the syntax as a user-facing feature here as well. A full RFC isn't necessary, but do you mind writing up a brief description of these new Ordinal References (something like what you'd find in our docs). I get the motivation for their introduction in regard to #10632, but talking through their introduction as a user-facing feature would help justify this approach over others.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/expr.go, line 548 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10729#-KWo1yGsCLVdU4o81wbm:-KWo1yGsCLVdU4o81wbn:b-a372ft) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5e3bb2f28296ae168fe1ecf9228a4384317d66e/pkg/sql/parser/expr.go#L548)):*
> ```Go
> func (DefaultVal) ResolvedType() Type { return nil }
> 
> var _ VariableExpr = &Placeholder{}
> ```

Looks like this assertion got separated from its declaration.

---

*[pkg/sql/parser/sql.y, line 32 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10729#-KWo1ZI4mItMj-AdkUXB:-KWo1ZI4mItMj-AdkUXC:b-ztcbl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5e3bb2f28296ae168fe1ecf9228a4384317d66e/pkg/sql/parser/sql.y#L32)):*
> ```Yacc
> 
> const maxUint = ^uint(0)
> const maxInt = int(^uint(0) >> 1)
> ```

`s/^uint(0)/maxUint/`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10729#-:-KWo2ADSZuUJmRpQ-unO:bkmo738)*

**Comment by RaduBerinde** [comment]
Didn't we conclude that it makes more sense to make all node types pointers? E.g. `OrdinalReference.Walk` returns a new instance.

Anyway, I was thinking that it would be great if we didn't need to visit expressions to simply convert between `OrdinalReference`s and `IndexedVar`s. Couldn't we simply use `IndexedVar` for this? We could make an IndexedVar with `nil` container act as an `OrdinalReference` (i.e. format as `@(idx+1)`, and disallow evaluation). We would still to populate the `container` and check the indices, but we wouldn't need to change the tree itself.

**Comment by knz** [comment]
@RaduBerinde thanks for your suggestions.
Indeed a pointer type was needed, that is fixed.

Regarding using IndexedVar I will try it and see if it fits. I like the idea!

@nvanbenschoten: I will add some more text in the commit message to explain with examples.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/expr.go, line 548 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10729#-KWo1yGsCLVdU4o81wbm:-KWqJZkixppMeM64w6qR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5e3bb2f28296ae168fe1ecf9228a4384317d66e/pkg/sql/parser/expr.go#L548)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Looks like this assertion got separated from its declaration.
</details>
Done.

---

*[pkg/sql/parser/sql.y, line 32 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10729#-KWo1ZI4mItMj-AdkUXB:-KWqJdTzauhkwW3bChr8:b-6r1ypk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5e3bb2f28296ae168fe1ecf9228a4384317d66e/pkg/sql/parser/sql.y#L32)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> `s/^uint(0)/maxUint/`?
</details>
Yes that's what I meant. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10729#-:-KWqKBobdq3gia9Mi1D1:by3fqly)*

**Comment by knz** [comment]
@RaduBerinde I have simplified to use only IndexedVar as you suggested. PTAL.

@nvanbenschoten I have extended the commit message (and the header of this PR) with your suggestions. PTAL.

**Comment by knz** [comment]
Note that there are two commits now but the first one will disappear after #10799 gets merged.

**Comment by RaduBerinde** [comment]
Awesome!! :lgtm_strong: 

---

Review status: 0 of 22 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10729#-:-KX30CQzFh64aIUwIEuZ:b-cfickw)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 23 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/indexed_vars.go, line 93 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10729#-KX3XBY2W3x6UNnG27D1:-KX3XBY2W3x6UNnG27D2:b-wnk70o) ([raw file](https://github.com/cockroachdb/cockroach/blob/8309d5419b3737d0356774327d51d78aaf8817ae/pkg/sql/parser/indexed_vars.go#L93)):*
> ```Go
> }
> 
> // IndexedVarHelper is a structure that helps with initialization of IndexVars.
> ```

IndexedVars

---

*[pkg/sql/parser/indexed_vars.go, line 101 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10729#-KX3XUU0H4MjOeDYWgm-:-KX3XUU0H4MjOeDYWgm0:bwp1d1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/8309d5419b3737d0356774327d51d78aaf8817ae/pkg/sql/parser/indexed_vars.go#L101)):*
> ```Go
> // BindIfUnbound attaches an IndexedVar to an existing container.
> // This is needed for standalone column ordinals created during parsing.
> func (h *IndexedVarHelper) BindIfUnbound(ivar *IndexedVar) error {
> ```

It feels a bit off that we need to allocate a set of `IndexedVar`s (as part of `IndexedVarHelper`) just to bind a container to existing `IndexedVars`. I don't have a better suggestion though (given that we need to support IndexedVarUsed)..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10729)*

**Comment by nvanbenschoten** [comment]
:lgtm: I like this approach better than adding a new `Expr` type.

---

Review status: 0 of 23 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/expr.go, line 548 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10729#-KWo1yGsCLVdU4o81wbm:-KX4FSdxzD1o_mTz8ftV:bihg2xp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5e3bb2f28296ae168fe1ecf9228a4384317d66e/pkg/sql/parser/expr.go#L548)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Done.
</details>
The move isn't necessary now that you removed the new expression type. I'd revert the change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10729#-:-KX4FziIore8Ewd8dQKd:bu488ol)*

**Comment by knz** [comment]
TFYRs!

---

Review status: 0 of 23 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/parser/expr.go, line 548 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10729#-KWo1yGsCLVdU4o81wbm:-KX4veZOa65iOKsddEuS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5e3bb2f28296ae168fe1ecf9228a4384317d66e/pkg/sql/parser/expr.go#L548)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> The move isn't necessary now that you removed the new expression type. I'd revert the change.
</details>
Done.

---

*[pkg/sql/parser/indexed_vars.go, line 93 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10729#-KX3XBY2W3x6UNnG27D1:-KX4vEZHtFSp8fP96yTS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8309d5419b3737d0356774327d51d78aaf8817ae/pkg/sql/parser/indexed_vars.go#L93)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> IndexedVars
</details>
Done.

---

*[pkg/sql/parser/indexed_vars.go, line 101 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10729#-KX3XUU0H4MjOeDYWgm-:-KX4vFQ_cark7Bu4T6cj:b-1g3izw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8309d5419b3737d0356774327d51d78aaf8817ae/pkg/sql/parser/indexed_vars.go#L101)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> It feels a bit off that we need to allocate a set of `IndexedVar`s (as part of `IndexedVarHelper`) just to bind a container to existing `IndexedVars`. I don't have a better suggestion though (given that we need to support IndexedVarUsed)..
</details>
Do not forget that the helper is also supporting the indexedvars created by name resolution (`a` -> IndexedVar), and this will be the more common case. I do not feel anything off here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10729#-:-KX4vS4gjWdtTYwo_MEv:bz5phge)*

**Pull request merged**
