### PR TITLE
sql: add 'max sql temp disk usage' stat to explain analyze output

### LINKED ISSUE #64111: sql: make spill to disk events more transparent
Investigating the performance of some tpch queries I noticed the system doing a lot of write I/O that confused me as it wasn't apparent the query would ever need to spill to disk. 

It should be clearer when this happens, for instance perhaps the explain analyze output could include information about how much disk spilling I/O was performed.

For reference the root cause is a [known issue](https://github.com/cockroachdb/cockroach/issues/59409).  

explain analyze for this query:

```
  planning time: 262µs
  execution time: 10s
  distribution: full
  vectorized: true
  rows read from KV: 6,001,215 (806 MiB)
  cumulative time spent in KV: 4.9s
  maximum memory usage: 32 MiB
  network usage: 0 B (0 messages)
```

Adding a line about disk spilling usage would be nice.

### PR DESCRIPTION
**Pull request by cucaroach**
```
   sql: add 'max sql temp disk usage' stat to explain analyze output

    Disk usage is currently tracked per node but we don't report it.
    Having to look at the sql.disk.distsql.spilled.bytes.written metric or
    examine explain analyze (distsql) diagram is cumbersome.   Example:

    > explain analyze (distsql) SELECT ...
      planning time: 2ms
      execution time: 18.6s
      distribution: full
      vectorized: true
      rows read from KV: 6,001,215 (806 MiB)
      cumulative time spent in KV: 10.8s
      maximum memory usage: 32 MiB
      network usage: 0 B (0 messages)
      max sql temp disk usage: 170 MiB

    Add a unit test to confirm output is as expected and doesn't appear in
    non-spill situations.   Also this field is completely omitted in redact
    situations as whether we spill is a metamorphic random variable so
    spilling isn't deterministic.

    Release note (sql): Add line to explain analyze output to show disk spill
    usage to make it clear when disk spilling occurs executing a query.  This
    output is only shown when the disk usage is greater than zeor.  The
    verbiage in the distsql explain diagrams changed from 'max scratch disk
    allocated' to 'max sql temp disk usage' for consistency and too match
    how we talk about sql spill disk usage elsewhere.
```

fixes #64111

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
LGTM, but I'd like for Radu to take a look as well.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-:-MZE9or522d3QYwDPB5P:b-2q9q2u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @RaduBerinde)

___
*[pkg/sql/instrumentation.go, line 434 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZE6pwg1GueXUCVGioD:-MZE6pwh5v1SpDc_2z98:bjpp6vu) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdba6008cec6a817e0203a23c91bd7935f393957/pkg/sql/instrumentation.go#L434)):*
> ```Go
> 	ob.AddMaxMemUsage(queryStats.MaxMemUsage)
> 	ob.AddNetworkStats(queryStats.NetworkMessages, queryStats.NetworkBytesSent)
> 	ob.AddMaxDiskUsage(queryStats.MaxDiskUsage)
> ```

super nit: might be nice to move it one line up, right after mem usage.
___
*[pkg/sql/opt/exec/explain/output.go, line 391 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZE7nWg1xcNmJf83uM7:-MZE7nWg1xcNmJf83uM8:b-f8h4id) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdba6008cec6a817e0203a23c91bd7935f393957/pkg/sql/opt/exec/explain/output.go#L391)):*
> ```Go
> }
> 
> // AddMaxDiskUsage adds a top-level field for the disk space used by the query.
> ```

nit: I'd mention that the field is added only if `bytes` is positive.
___
*[pkg/sql/opt/exec/explain/output.go, line 396 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZE85KDASFAj7gnkDrw:-MZE85KDASFAj7gnkDrx:b-ua1k7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdba6008cec6a817e0203a23c91bd7935f393957/pkg/sql/opt/exec/explain/output.go#L396)):*
> ```Go
> 	// independent of disk spilling.  Disk spilling is controlled by a metamorphic
> 	// constant so it may or may not occur randomly so it makes sense to omit this
> 	// information entirely if we're redacting.   RFC: do we redact in any other
> ```

I think currently we're only redacting if `DeterminsticExplain` testing knob is set, which is the case only for logic tests.
___
*[pkg/sql/opt/exec/explain/output.go, line 399 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZE7hDrAd_X3jDGyM6R:-MZE7hDrAd_X3jDGyM6S:b-w963r2) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdba6008cec6a817e0203a23c91bd7935f393957/pkg/sql/opt/exec/explain/output.go#L399)):*
> ```Go
> 	// contexts besides logictest where this might be undesirable?
> 	if !ob.flags.Redact.Has(RedactVolatile) && bytes > 0 {
> 		// RFC: diagram uses "max scratch disk allocated" should I unify?
> ```

Yeah, I think it'd be great to unify, one way or another.
___
*[pkg/sql/opt/exec/explain/output.go, line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZE8NCC51Ox6Be8rXmv:-MZE8NCC51Ox6Be8rXmw:b-s36g5q) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdba6008cec6a817e0203a23c91bd7935f393957/pkg/sql/opt/exec/explain/output.go#L400)):*
> ```Go
> 	if !ob.flags.Redact.Has(RedactVolatile) && bytes > 0 {
> 		// RFC: diagram uses "max scratch disk allocated" should I unify?
> 		ob.AddTopLevelField("maximum sql temp disk usage",
> ```

I'd use `AddRedactableTopLevelField` to be in line with the max mem usage above. Keeping `bytes > 0` still makes sense though.
___
*[pkg/sql/opt/exec/explain/output_test.go, line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZE7WVn7eQ_9k4HQo3U:-MZE7WVn7eQ_9k4HQo3V:b-pudl3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdba6008cec6a817e0203a23c91bd7935f393957/pkg/sql/opt/exec/explain/output_test.go#L143)):*
> ```Go
> 	testClusterArgs.ServerArgs.Knobs.DistSQL = distSQLKnobs
> 	testClusterArgs.ServerArgs.Insecure = true
> 	serverutils.InitTestServerFactory(server.TestServerFactory)
> ```

nit: this call should probably be moved to `explain/main_test.go`. (At least that's how we usually do this.)
___
*[pkg/sql/opt/exec/explain/output_test.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZE90bMEly9UPP7EYyL:-MZE90bMEly9UPP7EYyM:bov3zjk) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdba6008cec6a817e0203a23c91bd7935f393957/pkg/sql/opt/exec/explain/output_test.go#L150)):*
> ```Go
> 	conn := tc.Conns[0]
> 
> 	// Create the table with disabled automatic table stats collection (so
> ```

nit: this commit doesn't seem to be applicable.
___
*[pkg/sql/opt/exec/explain/output_test.go, line 153 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZE9d0E9e7cQod6bjbE:-MZE9d0E9e7cQod6bjbF:b-k72byu) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdba6008cec6a817e0203a23c91bd7935f393957/pkg/sql/opt/exec/explain/output_test.go#L153)):*
> ```Go
> 	// that we can control whether they are present or not).
> 	_, err := conn.ExecContext(ctx, `
> CREATE TABLE t (a PRIMARY KEY, b) AS SELECT i, i FROM generate_series(1, 511) AS g(i)
> ```

nit: could have less rows in the table, 511 seems very weird here.
___
*[pkg/sql/opt/exec/explain/output_test.go, line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZE9VBq5_XGkUSYy_EJ:-MZE9VBq5_XGkUSYy_EK:bod45rh) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdba6008cec6a817e0203a23c91bd7935f393957/pkg/sql/opt/exec/explain/output_test.go#L174)):*
> ```Go
> 		return false
> 	}
> 	assert.True(t, queryMatchRE(`EXPLAIN ANALYZE (VERBOSE, DISTSQL) select * from t join t AS x on t.b=x.a`, maxDiskUsageRE), "didn't find maximum sql temp disk usage in explain")
> ```

nit: I'd add a comment mentioning that because we set `ForceDiskSpill` to `true` above, we expect this hash join to use temp disk storage.

**Review by yuzefovich — COMMENTED** [review]
Also, you'll need `make bazel-generate`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-:-MZE9xNO4GEM7yKcUIhD:b-s0m66m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @RaduBerinde)

**Review by RaduBerinde — APPROVED** [review]
:lgtm: 

[nit] Make sure the commit message contains the phrasing that you end up with (it currently doesn't match the "maximum sql temp disk usage" in the code)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-:-MZERTpkEWWEqDUP7gFD:brh0o6d)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[pkg/sql/opt/exec/explain/output.go, line 394 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZERB3qBCSH5snDqM2z:-MZERB3qBCSH5snDqM3-:b-x3udqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdba6008cec6a817e0203a23c91bd7935f393957/pkg/sql/opt/exec/explain/output.go#L394)):*
> ```Go
> func (ob *OutputBuilder) AddMaxDiskUsage(bytes int64) {
> 	// If we're redacting just leave this out to avoid keep logic test output
> 	// independent of disk spilling.  Disk spilling is controlled by a metamorphic
> ```

[nit] double space
___
*[pkg/sql/opt/exec/explain/output.go, line 399 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZE7hDrAd_X3jDGyM6R:-MZERz4U-0OXj2UOX9ut:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdba6008cec6a817e0203a23c91bd7935f393957/pkg/sql/opt/exec/explain/output.go#L399)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Yeah, I think it'd be great to unify, one way or another.
</blockquote></details>

+1

**Review by cucaroach — COMMENTED** [review]
Thanks for the comments, please take another look

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-:-MZEmN2KAzr8tiA5juDo:b-ysbi9)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @yuzefovich)

___
*[pkg/sql/instrumentation.go, line 434 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZE6pwg1GueXUCVGioD:-MZETGhH5OyS-C630uKR:bswa2xz) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdba6008cec6a817e0203a23c91bd7935f393957/pkg/sql/instrumentation.go#L434)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

super nit: might be nice to move it one line up, right after mem usage.
</blockquote></details>

My inclination was to put new stuff at the bottom, what's the motivation?    
___
*[pkg/sql/opt/exec/explain/output.go, line 391 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZE7nWg1xcNmJf83uM7:-MZEUdcg5SZqpyqCT77E:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdba6008cec6a817e0203a23c91bd7935f393957/pkg/sql/opt/exec/explain/output.go#L391)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I'd mention that the field is added only if `bytes` is positive.
</blockquote></details>

:thumbsup: 
___
*[pkg/sql/opt/exec/explain/output.go, line 394 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZERB3qBCSH5snDqM2z:-MZEU_HL0DGMlt4-rNzz:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdba6008cec6a817e0203a23c91bd7935f393957/pkg/sql/opt/exec/explain/output.go#L394)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] double space
</blockquote></details>

:thumbsup: 
___
*[pkg/sql/opt/exec/explain/output.go, line 396 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZE85KDASFAj7gnkDrw:-MZEUg_r1ehvdRja3pRN:bb6mt9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdba6008cec6a817e0203a23c91bd7935f393957/pkg/sql/opt/exec/explain/output.go#L396)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think currently we're only redacting if `DeterminsticExplain` testing knob is set, which is the case only for logic tests.
</blockquote></details>

:+1:
___
*[pkg/sql/opt/exec/explain/output.go, line 399 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZE7hDrAd_X3jDGyM6R:-MZEUk7j6DAcfMhI4iAo:b-zck0qz) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdba6008cec6a817e0203a23c91bd7935f393957/pkg/sql/opt/exec/explain/output.go#L399)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

+1
</blockquote></details>

I'll go with "maximum sql temp disk" usage since I think that's the clearest.
___
*[pkg/sql/opt/exec/explain/output.go, line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZE8NCC51Ox6Be8rXmv:-MZEUs-j56j3MLG4rQtA:baz1u5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdba6008cec6a817e0203a23c91bd7935f393957/pkg/sql/opt/exec/explain/output.go#L400)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I'd use `AddRedactableTopLevelField` to be in line with the max mem usage above. Keeping `bytes > 0` still makes sense though.
</blockquote></details>

Not sure I agree, I'm not redacting this field ever, I'm completely leaving it out if we're redacting.
___
*[pkg/sql/opt/exec/explain/output_test.go, line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZE7WVn7eQ_9k4HQo3U:-MZE_YJk7oAGzihyU0bX:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdba6008cec6a817e0203a23c91bd7935f393957/pkg/sql/opt/exec/explain/output_test.go#L143)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this call should probably be moved to `explain/main_test.go`. (At least that's how we usually do this.)
</blockquote></details>

:+1: 
___
*[pkg/sql/opt/exec/explain/output_test.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZE90bMEly9UPP7EYyL:-MZEbtR522nh_qGkvPa6:b-xe2kno) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdba6008cec6a817e0203a23c91bd7935f393957/pkg/sql/opt/exec/explain/output_test.go#L150)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this commit doesn't seem to be applicable.
</blockquote></details>

Ooops, cut n pasto
___
*[pkg/sql/opt/exec/explain/output_test.go, line 153 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZE9d0E9e7cQod6bjbE:-MZEbx_b7BZ7o4-Abu29:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdba6008cec6a817e0203a23c91bd7935f393957/pkg/sql/opt/exec/explain/output_test.go#L153)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: could have less rows in the table, 511 seems very weird here.
</blockquote></details>

:+1: 
___
*[pkg/sql/opt/exec/explain/output_test.go, line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZE9VBq5_XGkUSYy_EJ:-MZEcIQ32JiLrqRvltdc:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdba6008cec6a817e0203a23c91bd7935f393957/pkg/sql/opt/exec/explain/output_test.go#L174)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I'd add a comment mentioning that because we set `ForceDiskSpill` to `true` above, we expect this hash join to use temp disk storage.
</blockquote></details>

:+1:

**Review by cucaroach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64137)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @yuzefovich)

___
*[pkg/sql/opt/exec/explain/main_test.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZEmeTXBDkecoaXNvrY:-MZEmeTXBDkecoaXNvrZ:b-wuyqua) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0e6858d960047c7799bb0874640c1296ac70756/pkg/sql/opt/exec/explain/main_test.go#L1)):*
> ```Go
> // Copyright 2015 The Cockroach Authors.
> ```

Am I supposed to fast forward this date?

**Review by yuzefovich — APPROVED** [review]
I think I only have nits left, so :LGTM: I assume you are familiar with `-rewrite` option in the logic tests, right?

nit: update PR description to include both the commit message (so that it is included in the merge commit created by bors) and "fixes" line (so that the issue is automatically closed).

> Reviewed 6 of 6 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-:-MZF4Jpp1j9hVPwF68cd:b-yf2688)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @RaduBerinde)

___
*[pkg/sql/instrumentation.go, line 434 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZE6pwg1GueXUCVGioD:-MZEzD3FA5uIaurHgmUE:b-6jup67) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdba6008cec6a817e0203a23c91bd7935f393957/pkg/sql/instrumentation.go#L434)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

My inclination was to put new stuff at the bottom, what's the motivation?    
</blockquote></details>

I like symmetry and `AddMaxDiskUsage` is defined right after `AddMaxMemUsage` in `explain/output.go`, so I'd restore the symmetry either here or there. My personal preference is updating it here because "max mem" and "max disk" seem very related, so they might as well be grouped together.

Generally speaking though I agree with you - putting the new stuff at the bottom is a good rule of thumb for me too, but IMO symmetry wins :) . And also "super nits" in my mind are free to be completely ignored (you can just mark the comment as "resolved") if you prefer not taking the suggestion.
___
*[pkg/sql/execinfrapb/component_stats.go, line 160 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZF-IKIEwfu_HMQfzJE:-MZF-IKIEwfu_HMQfzJF:b-6743zs) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0e6858d960047c7799bb0874640c1296ac70756/pkg/sql/execinfrapb/component_stats.go#L160)):*
> ```Go
> 	}
> 	if s.Exec.MaxAllocatedDisk.HasValue() {
> 		fn("maximum sql temp disk usage", humanize.IBytes(s.Exec.MaxAllocatedDisk.Value()))
> ```

nit: I'd keep "max" not "maximum". Again, for symmetry with above, but also because the boxes on the diagrams will be wider with longer wording which is probably undesirable in most cases.

nit: this change also will need to be mentioned in the release note.
___
*[pkg/sql/opt/exec/explain/main_test.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZEmeTXBDkecoaXNvrY:-MZEyf73BhAWAqucNn0c:b-a349l) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0e6858d960047c7799bb0874640c1296ac70756/pkg/sql/opt/exec/explain/main_test.go#L1)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Am I supposed to fast forward this date?
</blockquote></details>

Yeah, you need to use the date when the file was created. The idea is that according to BSL license, the code becomes truly open source in year "created + 3".
___
*[pkg/sql/opt/exec/explain/output.go, line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZE8NCC51Ox6Be8rXmv:-MZF-rz_0bTeuymPIH2I:b-vuhhij) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdba6008cec6a817e0203a23c91bd7935f393957/pkg/sql/opt/exec/explain/output.go#L400)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Not sure I agree, I'm not redacting this field ever, I'm completely leaving it out if we're redacting.
</blockquote></details>

What I mean is doing something like
```
if bytes > 0 {
  ob.AddRedactableTopLevelField(<args>)
}
```
This way we hide the field if no spilling occurred, but if we do show it, we'll redact it in the logic tests. I think this is exactly what you have here.

**Review by cucaroach — COMMENTED** [review]
By PR description is that the first comment?   Did I do it right?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-:-MZF990rAV5NZFoa_Bff:bmj25ej)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @RaduBerinde and @yuzefovich)

___
*[pkg/sql/instrumentation.go, line 434 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZE6pwg1GueXUCVGioD:-MZF7VmHCz7I7tBBk68A:b-boxi36) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdba6008cec6a817e0203a23c91bd7935f393957/pkg/sql/instrumentation.go#L434)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I like symmetry and `AddMaxDiskUsage` is defined right after `AddMaxMemUsage` in `explain/output.go`, so I'd restore the symmetry either here or there. My personal preference is updating it here because "max mem" and "max disk" seem very related, so they might as well be grouped together.

Generally speaking though I agree with you - putting the new stuff at the bottom is a good rule of thumb for me too, but IMO symmetry wins :) . And also "super nits" in my mind are free to be completely ignored (you can just mark the comment as "resolved") if you prefer not taking the suggestion.
</blockquote></details>

okay I'll put AddMaxDiskUsage at the bottom. 
___
*[pkg/sql/execinfrapb/component_stats.go, line 160 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZF-IKIEwfu_HMQfzJE:-MZF7nEE5aVPkEbOBUHk:bkpo1ik) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0e6858d960047c7799bb0874640c1296ac70756/pkg/sql/execinfrapb/component_stats.go#L160)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I'd keep "max" not "maximum". Again, for symmetry with above, but also because the boxes on the diagrams will be wider with longer wording which is probably undesirable in most cases.

nit: this change also will need to be mentioned in the release note.
</blockquote></details>

I started with max but we use both so wasn't sure, I went with "max" but memory still uses "maximum".
___
*[pkg/sql/opt/exec/explain/main_test.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZEmeTXBDkecoaXNvrY:-MZF7yW9EHq-GGCOzZQB:bb6mt9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0e6858d960047c7799bb0874640c1296ac70756/pkg/sql/opt/exec/explain/main_test.go#L1)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Yeah, you need to use the date when the file was created. The idea is that according to BSL license, the code becomes truly open source in year "created + 3".
</blockquote></details>

:+1:
___
*[pkg/sql/opt/exec/explain/output.go, line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZE8NCC51Ox6Be8rXmv:-MZF86OY2Bd3dgy_LWtk:b-ewighb) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdba6008cec6a817e0203a23c91bd7935f393957/pkg/sql/opt/exec/explain/output.go#L400)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

What I mean is doing something like
```
if bytes > 0 {
  ob.AddRedactableTopLevelField(<args>)
}
```
This way we hide the field if no spilling occurred, but if we do show it, we'll redact it in the logic tests. I think this is exactly what you have here.
</blockquote></details>

No that's not what I'm doing.   This code will have "max sql temp usage: <hidden>" in the output when spilling occurs which is randomly controlled by a metamorphic variable.    The way I coded it will show nothing which is why I didn't have to add this to any logictests expected output.   Its a full redaction instead of a value redaction.   Hopefully my comment makes it clear.

**Review by yuzefovich — APPROVED** [review]
Yeah, by PR description I mean the very first comment on the PR page (https://github.com/cockroachdb/cockroach/pull/64137#issue-622173575). Looks good (although a bit unusual to me - it seems like you indented the copy-pasted commit message, so it shows up with a gray background). Also note that when linking issues or PRs within the same public repo you can just use "#issue_number", for example: "Fixes: #64111." to link the issue this PR is closing.

nit: use `sql change` and not just `sql` in the release note. I think we have a pre-defined set of release note categories, and we definitely have some automated scripting going on that might (or might not) be looking for particular categories, so it's best to stick with the existing ones. They are mentioned in the commit hook in the commented section.

> Reviewed 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-:-MZFPoESAkSPztCDzhFz:bxeu7cz)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @cucaroach and @RaduBerinde)

___
*[pkg/sql/opt/exec/explain/output.go, line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZE8NCC51Ox6Be8rXmv:-MZFQUlo8VKVQECCvCJr:b-4vuetx) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdba6008cec6a817e0203a23c91bd7935f393957/pkg/sql/opt/exec/explain/output.go#L400)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

No that's not what I'm doing.   This code will have "max sql temp usage: <hidden>" in the output when spilling occurs which is randomly controlled by a metamorphic variable.    The way I coded it will show nothing which is why I didn't have to add this to any logictests expected output.   Its a full redaction instead of a value redaction.   Hopefully my comment makes it clear.
</blockquote></details>

Oh, I see, yeah, makes sense, I misread the code and your comment. Never mind, carry on.

**Review by cucaroach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64137)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @cucaroach, @RaduBerinde, and @yuzefovich)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZICEWv1JpWLqlJA9Fr:-MZICEWv1JpWLqlJA9Fs:b-qs4gkc) (no related file):*
Thanks for all the tips Yahor!   ¡Muchas Gracias!

---
___
*[pkg/sql/opt/exec/explain/output.go, line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64137#-MZE8NCC51Ox6Be8rXmv:-MZIC6cS251R9vJqvoWA:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdba6008cec6a817e0203a23c91bd7935f393957/pkg/sql/opt/exec/explain/output.go#L400)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Oh, I see, yeah, makes sense, I misread the code and your comment. Never mind, carry on.
</blockquote></details>

:+1:

**Pull request merged**
