### PR TITLE
geogfn: apply bounding box calculations for DWithin

### PR DESCRIPTION
**Pull request by otan**
Expand a BoundingRect by a given radius (using s2.Cap) and apply
intersection to do fairly cheap bounding box calculations before doing
the expensive DWithin logic.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50825)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/geo/geogfn/dwithin.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50825#-MB67IJD4GVkVWH1EE8q:-MB67IJE55d7Q34ZCOVA:bnnac94) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea4b673074ab694e0dce243ccabded0016e4d289/pkg/geo/geogfn/dwithin.go#L35)):*
> ```Go
> 	}
> 
> 	distanceToExpand := s1.Angle(distance / spheroid.SphereRadius)
> ```

how about s/distanceToExpand/angleToExpand/

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50825)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/geo/geogfn/dwithin.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50825#-MB67IJD4GVkVWH1EE8q:-MB69kQ37OmFtKo-Y5BO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea4b673074ab694e0dce243ccabded0016e4d289/pkg/geo/geogfn/dwithin.go#L35)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

how about s/distanceToExpand/angleToExpand/
</blockquote></details>

Done.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50825#-:-MB9hdpqAp3ke2avJM4t:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by otan** [comment]
bors r=sumeerbhola

**Pull request merged**
