### PR TITLE
cloud: remove warnings with terraform v0.7.2

### PR DESCRIPTION
**Pull request by vivekmenezes**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9129)

### CODE REVIEW

**Comment by mberhault** [comment]
Will this still work with the version running on the nightly tests?

**Comment by tamird** [comment]
That version is already broken, (upgrade discussion in #teamcity).

**Comment by cuongdo** [comment]
What warnings are you removing? Can you include an example?

**Comment by tamird** [comment]
Here are the warnings from last night's run: https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=18878#_focus=433

**Comment by vivekmenezes** [comment]
https://www.terraform.io/upgrade-guides/0-7.html

see the migrate to data sources section.

I also needed to remove the count var because of an error I was seeing once
I eliminated the warning.

**Comment by tamird** [comment]
@cuongdo @vivekmenezes @mberhault is this good to go? @vivekmenezes I believe it should go to master, not develop.

**Comment by cuongdo** [comment]
Could you also change `acceptance/terraform/*.tf`?

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9129#-:-KRAAV9T2S7fePMeo6dQ:b1nwoys)*

**Comment by cuongdo** [comment]
Other changes LGTM

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9129#-:-KRAAYp2bGRw0wHx-uny:b-9sg1ay)*

**Comment by vivekmenezes** [comment]
Added acceptance terraform config to this PR.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9129#-:-KRAV11ba9wd85YMncpJ:b25j0td)*

**Pull request merged**
