### PR TITLE
storage: lazify & shard sideloadeded storage

### LINKED ISSUE #17769: storage: overabundance of directories in auxiliary
After creating hundreds of thousands of ranges on a cluster, I noticed the `auxiiliary` directory use for side-loaded storage contained hundreds of thousands of empty directories. Do we have to create the side-loaded storage directory for a replica if it is never used? I have mild performance concerns about having so many entries in a single directory, but mostly this is just an aesthetic issue.

### PR DESCRIPTION
**Pull request by tbg**
Create sideloaded directories on-demand. Shard them by RangeID and ReplicaID mod
1024. This should make sure we can afford a very large number of left-over
directories until we run into file directory limits (roughly `1M*limit`, where
typically `limit >= 32K`).

Closes #17769.

### CODE REVIEW

**Comment by petermattis** [comment]
Commit message: `s/sideloadeded/sideloaded/g`

---

Reviewed 2 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/storage/replica_sideload_disk.go, line 46 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17787#-Ks5pYhjxcsRySrPW4LG:-Ks5pYhjxcsRySrPW4LH:bs9qhl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/516bb241ab143aab9f5fc60efb37b8e297c686a9/pkg/storage/replica_sideload_disk.go#L46)):*
> ```Go
> 		dir: filepath.Join(
> 			baseDir,
> 			"sideloading",
> ```

Any reason to be adding the "sideloading" directory to the hierarchy? Seems like the "auxiliary" dir is otherwise empty.

---

*[pkg/storage/replica_sideload_disk.go, line 48 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17787#-Ks5qAgI6_zA1HPxkHyz:-Ks5qAgI6_zA1HPxkHz-:bbbxwkp) ([raw file](https://github.com/cockroachdb/cockroach/blob/516bb241ab143aab9f5fc60efb37b8e297c686a9/pkg/storage/replica_sideload_disk.go#L48)):*
> ```Go
> 			"sideloading",
> 			fmt.Sprintf("%d", rangeID%1024),
> 			fmt.Sprintf("%d", replicaID%1024),
> ```

I wonder how useful the `replicaID` level is given that replica IDs are usually small. I've never actually seen a triple digit replica ID. Perhaps there should be a single level that combines the two: `fmt.Sprintf("%d", (rangeID + replicaID) % 1024)`. I'm not sure if we need a 2 level scheme as what we're trying to do is get the number of directory entries based on the expected max number of replicas to some reasonable value. With 1m replicas (64 TB of data), a single level scheme gets us to 1024 directories and 1024 entries per directory.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17787#-:-Ks5oPJNDPQ8aoON7w4E:b-e3lg69)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/storage/replica_sideload_disk.go, line 48 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17787#-Ks5qAgI6_zA1HPxkHyz:-Ks9DS9JFX6gqRr6m7DN:b-sxdfia) ([raw file](https://github.com/cockroachdb/cockroach/blob/516bb241ab143aab9f5fc60efb37b8e297c686a9/pkg/storage/replica_sideload_disk.go#L48)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I wonder how useful the `replicaID` level is given that replica IDs are usually small. I've never actually seen a triple digit replica ID. Perhaps there should be a single level that combines the two: `fmt.Sprintf("%d", (rangeID + replicaID) % 1024)`. I'm not sure if we need a 2 level scheme as what we're trying to do is get the number of directory entries based on the expected max number of replicas to some reasonable value. With 1m replicas (64 TB of data), a single level scheme gets us to 1024 directories and 1024 entries per directory.
</blockquote></details>

More importantly, one store is never supposed to have multiple replica ID directories at a time for long (you'd only have two replica IDs briefly when a new replica ID has been created but the old one hasn't yet been cleaned up. Even without the TDOO below I'm not worried about one store accumulating tens of thousands of replica IDs for one range). So just sharding on rangeID should be sufficient. 

Since the range IDs are encoded in decimal, we should shard by 1000 instead of 1024 (or change to print the IDs in hex).

---

*[pkg/storage/replica_sideload_disk.go, line 132 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17787#-Ks9ERf307SL770OGgG9:-Ks9ERf307SL770OGgGA:b5j1n1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/516bb241ab143aab9f5fc60efb37b8e297c686a9/pkg/storage/replica_sideload_disk.go#L132)):*
> ```Go
> 	// remove the directory.
> 	// We could also remove empty parts of the two-level shard structure, but due to
> 	// concurrency concerns that would have to happen at node startup.
> ```

Removing the replica ID level is safer than the range ID level - old replica IDs are never supposed to be recreated, so it should be safe to drop the directory when it becomes empty.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17787#-:-Ks9Eb1aDhgdl3b0efvf:bnfp4nl)*

**Comment by tschottdorf** [comment]
TFTRs!

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/storage/replica_sideload_disk.go, line 46 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17787#-Ks5pYhjxcsRySrPW4LG:-Ks5spbBq5kGJFbbKD1I:bsy3hp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/516bb241ab143aab9f5fc60efb37b8e297c686a9/pkg/storage/replica_sideload_disk.go#L46)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Any reason to be adding the "sideloading" directory to the hierarchy? Seems like the "auxiliary" dir is otherwise empty.
</blockquote></details>

It might be empty when you're looking today, but it seems better to create another directory than to have to live with multiple things intermingling for eternity when something new pops up.

---

*[pkg/storage/replica_sideload_disk.go, line 48 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17787#-Ks5qAgI6_zA1HPxkHyz:-Ks5tFh53u_HO8PsM9ML:bpkbc4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/516bb241ab143aab9f5fc60efb37b8e297c686a9/pkg/storage/replica_sideload_disk.go#L48)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

More importantly, one store is never supposed to have multiple replica ID directories at a time for long (you'd only have two replica IDs briefly when a new replica ID has been created but the old one hasn't yet been cleaned up. Even without the TDOO below I'm not worried about one store accumulating tens of thousands of replica IDs for one range). So just sharding on rangeID should be sufficient. 

Since the range IDs are encoded in decimal, we should shard by 1000 instead of 1024 (or change to print the IDs in hex).
</blockquote></details>

Good points, now sharding only by `rangeID % 1000`.

---

*[pkg/storage/replica_sideload_disk.go, line 132 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17787#-Ks9ERf307SL770OGgG9:-KsquU_GWgreKoj7iO0i:b8fk1i6) ([raw file](https://github.com/cockroachdb/cockroach/blob/516bb241ab143aab9f5fc60efb37b8e297c686a9/pkg/storage/replica_sideload_disk.go#L132)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Removing the replica ID level is safer than the range ID level - old replica IDs are never supposed to be recreated, so it should be safe to drop the directory when it becomes empty.
</blockquote></details>

Done (by means of obsoletion).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17787#-:-KsquXDw3MYRw7CJn_Sc:bz5mair)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/storage/replica_sideload_disk.go, line 46 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17787#-Ks5pYhjxcsRySrPW4LG:-KsrtOkax5D8pDgdzRD4:b-ip8m8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/516bb241ab143aab9f5fc60efb37b8e297c686a9/pkg/storage/replica_sideload_disk.go#L46)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

It might be empty when you're looking today, but it seems better to create another directory than to have to live with multiple things intermingling for eternity when something new pops up.
</blockquote></details>

I assumed we'd add another directory at the same level as `auxiliary`, just as we have `local` now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17787#-:-KsrtjXJQE-V808gXh7R:bnfp4nl)*

**Comment by tschottdorf** [comment]
```
$ make stress PKG=./pkg/sql/logictest TESTS=TestLogic/5node/distsql_numtables
...
ERROR: exit status 1

23 runs completed, 1 failures, over 2m26s
SUCCESS
```

```
I170831 10:12:38.290409 1151 storage/replica_proposal.go:453  [n5,s5,r5/2:/{Table/52/1/8…-Max}] new range lease repl=(n5,s5):2 start=1504188758.287853325,0 epo=1 pro=1504188758.287854748,0 following repl=(n1,s1):1 start=0.000000000,0 exp=1504188766.731608957,0 pro=1504188757.731640335,0
I170831 10:12:38.291778 1881 storage/replica_command.go:3646  [n5,s5,r5/2:/{Table/52/1/8…-Max}] change replicas (REMOVE_REPLICA (n1,s1):1): read existing descriptor r5:/{Table/52/1/8000-Max} [(n1,s1):1, (n5,s5):2, next=3]
I170831 10:12:38.297250 1910 storage/replica.go:3026  [n5,s5,r5/2:/{Table/52/1/8…-Max}] proposing REMOVE_REPLICA((n1,s1):1): updated=[(n5,s5):2] next=3
I170831 10:12:38.298683 1865 storage/store.go:3212  [n1,s1,r5/1:/{Table/52/1/8…-Max}] added to replica GC queue (peer suggestion)
I170831 10:12:38.299925 40 storage/store.go:2150  [replicaGC,n1,s1,r5/1:/{Table/52/1/8…-Max}] removing replica
I170831 10:12:38.300077 40 storage/replica.go:759  [replicaGC,n1,s1,r5/1:/{Table/52/1/8…-Max}] removed 10 (0+10) keys in 0ms [clear=0ms commit=0ms]
W170831 10:12:41.733788 2204 storage/replica.go:2112  [n3,s3,r3/2:/Table/52/1/{4000-6000}] context deadline exceeded while in command queue: ResolveIntent [/Table/52/1/5100/0,/Min), ResolveIntent [/Table/52/1/5101/0,/Min), ResolveIntent [/Table/52/1/5102/0,/Min), ResolveIntent [/Table/52/1/5103/0,/Min), ResolveIntent [/Table/52/1/5104/0,/Min), ResolveIntent [/Table/52/1/5105/0,/Min), ResolveIntent [/Table/52/1/5106/0,/Min), ResolveIntent [/Table/52/1/5107/0,/Min), ResolveIntent [/Table/52/1/5108/0,/Min), ResolveIntent [/Table/52/1/5109/0,/Min), ResolveIntent [/Table/52/1/5110/0,/Min), ResolveIntent [/Table/52/1/5111/0,/Min), ResolveIntent [/Table/52/1/5112/0,/Min), ResolveIntent [/Table/52/1/5113/0,/Min), ResolveIntent [/Table/52/1/5114/0,/Min), ResolveIntent [/Table/52/1/5115/0,/Min), ResolveIntent [/Table/52/1/5116/0,/Min), ResolveIntent [/Table/52/1/5117/0,/Min), ResolveIntent [/Table/52/1/5118/0,/Min), ResolveIntent [/Table/52/1/5119/0,/Min), ... 75 skipped ..., ResolveIntent [/Table/52/1/5195/0,/Min), ResolveIntent [/Table/52/1/5196/0,/Min), ResolveIntent [/Table/52/1/5197/0,/Min), ResolveIntent [/Table/52/1/5198/0,/Min), ResolveIntent [/Table/52/1/5199/0,/Min)
W170831 10:12:41.733914 2058 storage/intent_resolver.go:486  unable to resolve external intents: context deadline exceeded
W170831 10:12:41.733988 2117 storage/intent_resolver.go:486  unable to resolve external intents: context deadline exceeded
...
W170831 10:14:09.529634 1176 storage/store.go:3552  [n5,s5] handle raft ready: 90.6s [processed=1]
```

there's definitely *something* going wrong here. I can't imagine that `make stress` would stress the system *that* much.

**Pull request merged**
