### PR TITLE
storeliveness: add SupportManager metrics

### LINKED ISSUE #125067: storeliveness: add metrics (internal and external)
Decide what store liveness metrics to expose and external and/or internal metrics.

### PR DESCRIPTION
**Pull request by miraradeva**
This commit adds 9 new metrics for the Store Liveness `SupportManager`:

- `storeliveness.heartbeat.successes`: Number of Store Liveness heartbeats sent out by the Store Liveness Support Manager.

- `storeliveness.heartbeat.failures`: Number of Store Liveness heartbeats that failed to be sent out by the Store Liveness Support Manager.

- `storeliveness.message_handle.successes`: Number of incoming Store Liveness messages handled by the Store Liveness Support Manager.

- `storeliveness.message_handle.failures`: Number of incoming Store Liveness messages that failed to be handled by the Store Liveness Support Manager.

- `storeliveness.support_withdraw.successes`: Number of times the Store Liveness Support Manager has successfully withdrawn support for another store.

- `storeliveness.support_withdraw.failures`: Number of times the Store Liveness Support Manager has encountered an error while withdrawing support for another store.

- `storeliveness.support_from.stores`: Number of stores that the Store Liveness Support Manager is requesting support from by sending heartbeats.

- `storeliveness.transport.receive-queue-size`: Number of pending incoming messages from the Store Liveness Transport.

- `storeliveness.transport.receive-queue-bytes`: Total byte size of pending incoming messages from Store Liveness Transport.

Fixes: #125067

Release note: None

### CODE REVIEW

**Comment by miraradeva** [comment]
Looking for feedback on other metrics to add. I was thinking of also adding something like `storeliveness.support_from.provided` and `storeliveness.support_for.provided`, denoting the store's view of support from/for. But I think these might be confusing for two reasons: (1) there is a real-time component, so the metric will capture support-from with an expiration in the past, and (2) these metrics will show that store's view of support, which may be different at the support provider/requester. I think it will be much cleaner to capture this information as support transitions in the new log channel we'll add but I'm happy to consider these also as metrics somehow.

**Review by nvb — COMMENTED** [review]
Do we want a `storeliveness.support_for.stores`, which just reports the total number of stores that the Store Liveness Support Manager is tracking as having ever provided support to? Essentially just the size of the `supporterStateHandler.supporterState.supportFor` map.

> I think it will be much cleaner to capture this information as support transitions in the new log channel we'll add but I'm happy to consider these also as metrics somehow.

Agreed.

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131505#-:-O834G6wDCgWmlj52JgF:b-n1skb2)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @miraradeva)

___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131505#-O8339KP7u5oCdFSNNlH:-O8339KP7u5oCdFSNNlI:bxy6j68) ([raw file](https://github.com/cockroachdb/cockroach/blob/a48ccc49e4205e196174451f5a13427d3cbb726f/pkg/kv/kvserver/storeliveness/support_manager.go#L272)):*
> ```Go
> func (sm *SupportManager) maybeMarkIdleStores() {
> 	numIdle := sm.requesterStateHandler.markIdleStores()
> 	sm.metrics.SupportFromStores.Dec(int64(numIdle))
> ```

We are decrementing this value when the store becomes idle, but not when it becomes active again. Don't we need to do that? Or alternatively, should we just remove this logic and count idle stores as part of `SupportFromStores`?
___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 273 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131505#-O832bDpAtP7A507eHUO:-O832bDq6EDqyeTG7nbw:b-zeudbb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a48ccc49e4205e196174451f5a13427d3cbb726f/pkg/kv/kvserver/storeliveness/support_manager.go#L273)):*
> ```Go
> 	numIdle := sm.requesterStateHandler.markIdleStores()
> 	sm.metrics.SupportFromStores.Dec(int64(numIdle))
> 	log.VInfof(context.Background(), 2, "store %+v makrked %d stores as idle", sm.storeID, numIdle)
> ```

"marked"
___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131505#-O833fH7DkjJWixL10t3:-O833fH7DkjJWixL10t4:b-366eag) ([raw file](https://github.com/cockroachdb/cockroach/blob/a48ccc49e4205e196174451f5a13427d3cbb726f/pkg/kv/kvserver/storeliveness/support_manager.go#L294)):*
> ```Go
> 	for _, msg := range heartbeats {
> 		if sent := sm.sender.SendAsync(ctx, msg); sent {
> 			sm.metrics.HeartbeatSuccesses.Inc(1)
> ```

nit: Should we just do a single increment of each of these below the loop? `sm.metrics.HeartbeatSuccesses.Inc(successes)` and `sm.metrics.HeartbeatFailures.Inc(len(heartbeats) - successes)`.
___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 319 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131505#-O833yUXARCNNope2P-z:-O833yUXARCNNope2P0-:b3aeftl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a48ccc49e4205e196174451f5a13427d3cbb726f/pkg/kv/kvserver/storeliveness/support_manager.go#L319)):*
> ```Go
> 	if err := ssfu.write(ctx, batch); err != nil {
> 		log.Warningf(ctx, "failed to write supporter meta and state: %v", err)
> 		sm.metrics.SupportWithdrawFailures.Inc(int64(len(ssfu.inProgress.supportFor)))
> ```

here and below: can `len(ssfu.inProgress.supportFor)` be replaced by `numWithdrawn`?

**Review by miraradeva — COMMENTED** [review]
Added `storeliveness.support_for.stores`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131505#-:-O83KfQf7lU1sZdHMnPS:b31mnga)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131505#-O8339KP7u5oCdFSNNlH:-O83NeD9CR7gUvildBCt:b3895m7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a48ccc49e4205e196174451f5a13427d3cbb726f/pkg/kv/kvserver/storeliveness/support_manager.go#L272)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We are decrementing this value when the store becomes idle, but not when it becomes active again. Don't we need to do that? Or alternatively, should we just remove this logic and count idle stores as part of `SupportFromStores`?
</blockquote></details>

Yes, good point. I was hoping to capture the number of stores we're actively heartbeating to. But (a) that would not parallel the new `storeliveness.support_for.stores` well, and (b) we will be able to see how many heartbeats are being sent out per store in the new logging that I'm adding. So yeah, let's count idle stores as part of `SupportFromStores`.
___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 273 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131505#-O832bDpAtP7A507eHUO:-O83MyeL7jGa7o1hYSNP:b-xa98f6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a48ccc49e4205e196174451f5a13427d3cbb726f/pkg/kv/kvserver/storeliveness/support_manager.go#L273)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"marked"
</blockquote></details>

Removed this log line. I'll log each individual store marked as idle as part of the logging PR.
___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131505#-O833fH7DkjJWixL10t3:-O83NW_XAwAIkIxUJnyc:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a48ccc49e4205e196174451f5a13427d3cbb726f/pkg/kv/kvserver/storeliveness/support_manager.go#L294)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: Should we just do a single increment of each of these below the loop? `sm.metrics.HeartbeatSuccesses.Inc(successes)` and `sm.metrics.HeartbeatFailures.Inc(len(heartbeats) - successes)`.
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 319 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131505#-O833yUXARCNNope2P-z:-O83N7c94MiUXvhXQfQ9:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a48ccc49e4205e196174451f5a13427d3cbb726f/pkg/kv/kvserver/storeliveness/support_manager.go#L319)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

here and below: can `len(ssfu.inProgress.supportFor)` be replaced by `numWithdrawn`?
</blockquote></details>

Done

**Review by nvb — COMMENTED** [review]
> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131505)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @miraradeva)

___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 368 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131505#-O83VevjBwJCUi_P24jE:-O83VevjBwJCUi_P24jF:b8k9ro3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cfe06a153beb92800801421fa71a9ea4906a632/pkg/kv/kvserver/storeliveness/support_manager.go#L368)):*
> ```Go
> 	sm.metrics.MessageHandleSuccesses.Inc(int64(len(msgs)))
> 	// Handling heartbeats is the only way to add a store to the supportFor map.
> 	sm.metrics.SupportForStores.Update(int64(sm.supporterStateHandler.getNumSupportFor()))
> ```

Should we also initialize this value on startup?

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131505)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 368 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131505#-O83VevjBwJCUi_P24jE:-O83_-Cm46OuHiNujs6Z:bmiskcq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cfe06a153beb92800801421fa71a9ea4906a632/pkg/kv/kvserver/storeliveness/support_manager.go#L368)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we also initialize this value on startup?
</blockquote></details>

Yes, good idea.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131505#-:-O83aW1oDrojfb0A51WV:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by miraradeva** [comment]
TFTR!

bors r=nvanbenschoten

**Pull request merged**
