### PR TITLE
log: reduce the logging critical section

### PR DESCRIPTION
**Pull request by knz**

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/util/log/clog.go, line 1019 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15536#-Kj3HYx9jGbsIQmx0f3b:-Kj3HYx9jGbsIQmx0f3c:b-thmhrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3c0263179baf3a9f51a1db2886266693bb30335/pkg/util/log/clog.go#L1019)):*
> ```Go
> 	// doesn't need to be Stop()'d as the loop never escapes
> 	for range time.Tick(flushInterval) {
> 		if !l.disableDaemons {
> ```

this doesn't look equivalent to me; I think `disableDaemons` is protected by this same mutex.

---

*[pkg/util/log/color.go, line 23 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15536#-Kj3HgDmLUhiLirwAhkR:-Kj3HgDmLUhiLirwAhkS:b-vzfixh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc311d767e37fab4a7e3fc01dbfd1faea9b3d97/pkg/util/log/color.go#L23)):*
> ```Go
> )
> 
> // colorProfile defines escape sequences which provide color in
> ```

is all this code movement necessary? at least, can you put it in its own commit? The review is made harder by this, for little benefit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15536)*

**Comment by petermattis** [comment]
The movement of the color profile initialization seems good. Not so sure about the adjustment of the logging critical section. More specifically, I'm not sure how problematic the change will be in practice. Perhaps we should hold off on merging until after 1.0.

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/util/log/clog.go, line 729 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15536#-Kj3H0EH_PJw8ccAw7my:-Kj3H0EIcsYnAWcYM_sD:b-38w5x3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc311d767e37fab4a7e3fc01dbfd1faea9b3d97/pkg/util/log/clog.go#L729)):*
> ```Go
> 	if logDir.isSet() && s >= l.fileThreshold.get() {
> 		l.outputLogEntryInner(now, entry, stacks)
> 	}
> ```

With the previous locking, we'd log to stderr and the log file "atomically". With this new locking we could get different orderings of log messages to stderr and the file. Does this matter? I'm not sure, but it would be easy to fix.

Also, this PR logs to stderr without holding `logging.mu` which would allow interleaving of concurrent log messages. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15536#-:-Kj3Hop4dyo4iAiEaql5:bovw4gm)*

**Comment by knz** [comment]
I'm ok holding off with merging.

---

Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/util/log/clog.go, line 1019 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15536#-Kj3HYx9jGbsIQmx0f3b:-Kj3e3VkBy9bK5gDuTEV:b-kk855g) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3c0263179baf3a9f51a1db2886266693bb30335/pkg/util/log/clog.go#L1019)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this doesn't look equivalent to me; I think `disableDaemons` is protected by this same mutex.
</blockquote></details>

Oh right; reverted.

---

*[pkg/util/log/clog.go, line 729 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15536#-Kj3H0EH_PJw8ccAw7my:-Kj3jkbknRp5Cs_kS_aJ:b-x52gbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc311d767e37fab4a7e3fc01dbfd1faea9b3d97/pkg/util/log/clog.go#L729)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

With the previous locking, we'd log to stderr and the log file "atomically". With this new locking we could get different orderings of log messages to stderr and the file. Does this matter? I'm not sure, but it would be easy to fix.

Also, this PR logs to stderr without holding `logging.mu` which would allow interleaving of concurrent log messages. 
</blockquote></details>

Thanks, fixed.

---

*[pkg/util/log/color.go, line 23 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15536#-Kj3HgDmLUhiLirwAhkR:-Kj3jZgQwTj988wLES4e:bcj3tyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc311d767e37fab4a7e3fc01dbfd1faea9b3d97/pkg/util/log/color.go#L23)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is all this code movement necessary? at least, can you put it in its own commit? The review is made harder by this, for little benefit.
</blockquote></details>

I split to a different commit. And yes, moving the color initialization to the init function was necessary, otherwise there's a race on `hasColorCodes`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15536#-:-Kj3e-mlkoZ6wxkD3UWr:b7bihh3)*

**Comment by tamird** [comment]
Reviewed 2 of 4 files at r2, 2 of 2 files at r3, 1 of 2 files at r4.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15536)*

**Comment by petermattis** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/util/log/clog.go, line 729 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15536#-Kj3H0EH_PJw8ccAw7my:-Kj3lBWdtHPNrMyAeaGJ:b-8u3ajz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc311d767e37fab4a7e3fc01dbfd1faea9b3d97/pkg/util/log/clog.go#L729)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Thanks, fixed.
</blockquote></details>

I might be missing something, but it looks like the code will now only log to stderr if file logging is enabled. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15536)*

**Comment by knz** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/util/log/clog.go, line 729 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15536#-Kj3H0EH_PJw8ccAw7my:-Kj3mFe3j3FGSVCtrIvC:becim0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc311d767e37fab4a7e3fc01dbfd1faea9b3d97/pkg/util/log/clog.go#L729)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I might be missing something, but it looks like the code will now only log to stderr if file logging is enabled. 
</blockquote></details>

Duh, I forgot to remove the conditional I had migrated. Thanks for spotting it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15536)*

**Comment by petermattis** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/util/log/clog.go, line 667 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/15536#-Kj3otOk98DbNJZ5duXJ:-Kj3otOk98DbNJZ5duXK:binq82e) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b079bbdc4eac544b1856ce3d6ce2bb3730193cb/pkg/util/log/clog.go#L667)):*
> ```Go
> // of outputLogEntry()
> func (l *loggingT) outputLogEntryInner(s Severity, now time.Time, entry Entry, stacks []byte) {
> 	buf := l.formatLogEntry(entry, stacks, nil)
> ```

If we're logging to stderr with a color profile and not to a file, we'll be formatting the log entry twice when it is only necessary to do so once. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15536)*

**Comment by tschottdorf** [comment]
@knz happy to review this but it seems that both of us are busy on other things right now. Just reassign me when you're ready and I'll take a look (and no rush obviously)!

**Comment by knz** [comment]
After correcting my various errors I notice that the remaining code is not much improving the current state of affairs. I extracted the bit of useful change away to #16710 and am closing this PR.

**Pull request closed without merging**
