### PR TITLE
backupccl: correctly restore tables that conflict with system tables

### LINKED ISSUE #84359: restore: system tables with dynamically assigned IDs are missing after restoring from previous version
Repro:

On 21.2 cluster (I did start-single-node)
```
BACKUP INTO 'nodelocal://1/foo`.
```

Kill the 21.2 cluster, start a 22.1 cluster (make sure the EXTERN directory is the same so we can re-use nodelocal backup), easiest way to do this is to simply have the 21.2 and 22.1 binary in the same folder.

On 22.1 (I'm on version  v22.1.3 (x86_64-apple-darwin19, built 2022/07/11 14:17:45, go1.17.11) node:
```
root@localhost:26257/defaultdb> show tables from system;
  schema_name |           table_name            | type  | owner | estimated_row_count | locality
--------------+---------------------------------+-------+-------+---------------------+-----------
  public      | comments                        | table | NULL  |                   0 | NULL
  public      | database_role_settings          | table | NULL  |                   0 | NULL
  public      | descriptor                      | table | NULL  |                   0 | NULL
  public      | eventlog                        | table | NULL  |                   0 | NULL
  public      | jobs                            | table | NULL  |                   0 | NULL
  public      | join_tokens                     | table | NULL  |                   0 | NULL
  public      | lease                           | table | NULL  |                   0 | NULL
  public      | locations                       | table | NULL  |                   0 | NULL
  public      | migrations                      | table | NULL  |                   0 | NULL
  public      | namespace                       | table | NULL  |                   0 | NULL
  public      | protected_ts_meta               | table | NULL  |                   0 | NULL
  public      | protected_ts_records            | table | NULL  |                   0 | NULL
  public      | rangelog                        | table | NULL  |                   0 | NULL
  public      | replication_constraint_stats    | table | NULL  |                   0 | NULL
  public      | replication_critical_localities | table | NULL  |                   0 | NULL
  public      | replication_stats               | table | NULL  |                   0 | NULL
  public      | reports_meta                    | table | NULL  |                   0 | NULL
  public      | role_members                    | table | NULL  |                   0 | NULL
  public      | role_options                    | table | NULL  |                   0 | NULL
  public      | scheduled_jobs                  | table | NULL  |                   0 | NULL
  public      | settings                        | table | NULL  |                   0 | NULL
  public      | span_configurations             | table | NULL  |                   0 | NULL
  public      | sql_instances                   | table | NULL  |                   0 | NULL
  public      | sqlliveness                     | table | NULL  |                   0 | NULL
  public      | statement_bundle_chunks         | table | NULL  |                   0 | NULL
  public      | statement_diagnostics           | table | NULL  |                   0 | NULL
  public      | statement_diagnostics_requests  | table | NULL  |                   0 | NULL
  public      | statement_statistics            | table | NULL  |                   0 | NULL
  public      | table_statistics                | table | NULL  |                   0 | NULL
  public      | tenant_settings                 | table | NULL  |                   0 | NULL
  public      | tenant_usage                    | table | NULL  |                   0 | NULL
  public      | tenants                         | table | NULL  |                   0 | NULL
  public      | transaction_statistics          | table | NULL  |                   0 | NULL
  public      | ui                              | table | NULL  |                   0 | NULL
  public      | users                           | table | NULL  |                   0 | NULL
  public      | web_sessions                    | table | NULL  |                   0 | NULL
  public      | zones                           | table | NULL  |                   0 | NULL
(37 rows)
root@localhost:26257/defaultdb> restore from latest in 'nodelocal://1/foo';
        job_id       |  status   | fraction_completed | rows | index_entries | bytes
---------------------+-----------+--------------------+------+---------------+--------
  778746589609590785 | succeeded |                  1 |   22 |             8 |  2117
(1 row)

----- after restore -----

root@localhost:26257/defaultdb> show tables from system;
  schema_name |           table_name            | type  | owner | estimated_row_count | locality
--------------+---------------------------------+-------+-------+---------------------+-----------
  public      | comments                        | table | NULL  |                   0 | NULL
  public      | database_role_settings          | table | NULL  |                   0 | NULL
  public      | descriptor                      | table | NULL  |                   0 | NULL
  public      | eventlog                        | table | NULL  |                   0 | NULL
  public      | jobs                            | table | NULL  |                   0 | NULL
  public      | join_tokens                     | table | NULL  |                   0 | NULL
  public      | lease                           | table | NULL  |                   0 | NULL
  public      | locations                       | table | NULL  |                   0 | NULL
  public      | migrations                      | table | NULL  |                   0 | NULL
  public      | namespace                       | table | NULL  |                   0 | NULL
  public      | protected_ts_meta               | table | NULL  |                   0 | NULL
  public      | protected_ts_records            | table | NULL  |                   0 | NULL
  public      | rangelog                        | table | NULL  |                   0 | NULL
  public      | replication_constraint_stats    | table | NULL  |                   0 | NULL
  public      | replication_critical_localities | table | NULL  |                   0 | NULL
  public      | replication_stats               | table | NULL  |                   0 | NULL
  public      | reports_meta                    | table | NULL  |                   0 | NULL
  public      | role_members                    | table | NULL  |                   0 | NULL
  public      | role_options                    | table | NULL  |                   0 | NULL
  public      | scheduled_jobs                  | table | NULL  |                   0 | NULL
  public      | settings                        | table | NULL  |                   0 | NULL
  public      | span_configurations             | table | NULL  |                   0 | NULL
  public      | sql_instances                   | table | NULL  |                   0 | NULL
  public      | sqlliveness                     | table | NULL  |                   0 | NULL
  public      | statement_bundle_chunks         | table | NULL  |                   0 | NULL
  public      | statement_diagnostics           | table | NULL  |                   0 | NULL
  public      | statement_diagnostics_requests  | table | NULL  |                   0 | NULL
  public      | statement_statistics            | table | NULL  |                   0 | NULL
  public      | table_statistics                | table | NULL  |                   0 | NULL
  public      | tenant_usage                    | table | NULL  |                   0 | NULL
  public      | tenants                         | table | NULL  |                   0 | NULL
  public      | transaction_statistics          | table | NULL  |                   0 | NULL
  public      | ui                              | table | NULL  |                   0 | NULL
  public      | users                           | table | NULL  |                   0 | NULL
  public      | web_sessions                    | table | NULL  |                   0 | NULL
  public      | zones                           | table | NULL  |                   0 | NULL
(36 rows)

```

Notice how we're missing one table (`system.tenant_settings`)

—

Fixes & follow-ups:

- [x] https://github.com/cockroachdb/cockroach/pull/84495
  - [x] https://github.com/cockroachdb/cockroach/pull/84904
- [ ] https://github.com/cockroachdb/cockroach/issues/84561 (for v22.2) 
- [ ] Open issues for tests we intend to write, to capture broader classes of these errors. Start narrow, then expand, then expand again. 
  - [ ] System table restore tests
  - [ ] Mixed-version tests
  - [ ] What else?

Jira issue: CRDB-17614

### PR DESCRIPTION
**Pull request by stevendanna**
This change fixes a bug in which a restore on 22.1 clusters would
either fail with an error such as

    restoring system table ‹tenant_settings›: deleting data from
    system.‹tenant_settings›: ‹tenant_settings-data-deletion›: relation
    ‹"system.tenant_settings"› does not exist-

Or succeed but overwrite the descriptor for the tenant_settings table.

The descriptor IDs contained in a backup may conflict with the IDs
that already exist in the database. During restore, we look for such
conflicts, allocate new IDs for the objects being restored, and rekey
any KV data that has descriptor IDs embedded in the key while
importing the data.

However, during a _full cluster restore_, we assume that we do not
need to rekey any databases or tables other than system tables that
exist in the backup, because the destination cluster is otherwise
empty.

In previous releases, this was a good assumption. The only tables that
could conflict were system tables. All system tables in the backup are
restored to a temporary database under new IDs; and any system tables
in the existing cluster were at known, reserved IDs that could not
conflict with user data.

However, in 22.1 we removed the arbitrary limit on system tables,
requiring that their IDs are no longer fixed.

In a fresh 22.1 cluster, the tenant_settings table has ID 50. However,
in a cluster that was upgraded from 21.2, ID 50 is likely already
allocated (likely as the database descriptor ID for defaultdb) as it
was previously the first non-reserved ID.  A backup created on such a
cluster thus has descriptors using ID 50 which won't be rekeyed but
which will conflict with the tenant_settings table.

Here we fix this by detecting such conflicts and both (1) preparing
the necessary descriptor rewrites and rekeys and (2) accounting for
system table ID conflicts when setting the id generator key to avoid
leaking too many IDs.

Note that in the case of 22.1 backups, the conflict is likely to occur
on id 50, which means that it is likely that _every_ table in the
backup will be rewritten for users whose clusters started on versions
before 22.1.

Fixes #84359

Release note (bug fix): Fix bug that prevents restoring a backup taken
on 22.1.

### CODE REVIEW

**Comment by stevendanna** [comment]
More tests to add but I wanted to get this out for review in case I've missed something.

**Comment by stevendanna** [comment]
The test failure is unrelated, should be fixed here https://github.com/cockroachdb/cockroach/pull/84419

**Comment by shermanCRL** [comment]
Thanks @stevendanna . Let’s get this reviewed and tested ASAP.

**Comment by stevendanna** [comment]
After discussing with @adityamaru and @dt we think a better path is to _always_ rewrite the IDs. So hold of on review for a bit.

**Comment by stevendanna** [comment]
The situation is unfortunately a bit more complex than we would like.

Some notes:

If we remap descriptors in a full cluster backup, then system table
entries that hold on to IDs or descriptors need may be incorrect.

Of the tables included in a backup:

- system.zones
- system.jobs
- system.comments
- system.scheduled_jobs
- system.database_role_settings

`zones`, `comments`, and `database_role_settings` can be handled with
straightforward custom restore funcs for those tables.

`jobs` is the most complex.

Quick survey of descriptors and descriptor IDs held in job
records.

- DescriptorID field on top level job record.
- Most jobs hold onto descriptors or IDs of some type:

```
| Job Type                     |                                                                                                                     |
|------------------------------+---------------------------------------------------------------------------------------------------------------------|
| Backup                       | Uff                                                                                                                 |
| Restore                      | Uff, restore moves this to reverting.                                                                               |
| SchemaChange                 | IDs all over.                                                                                                       |
| Import                       | Holds Type, Schema, and Table descriptors, restore moves to reverting, where we drop table's and schema's...        |
| Changefeed                   | Holds Table descriptor IDs, and checkpoints that include spans which reference table IDs.                           |
| CreateStats                  | Holds Table descriptors                                                                                             |
| SchemaChangeGC               | Holds Table descriptor IDs and database IDs                                                                         |
| TypeSchemaChange             | Holds Type descriptor ID                                                                                            |
| StreamIngest                 | Holds spans, but they should by fully contained in tenants.                                                         |
| NewSchemaChange              | Backfill/Merge progress holds spans and table descriptor IDs.                                                       |
| Migration                    | OK                                                                                                                  |
| AutoSpanConfigReconciliation | OK                                                                                                                  |
| AutoSQLStatsCompaction       | OK                                                                                                                  |
| StreamReplication            | Holds spans, but they should be contained inside a tenant.                                                          |
| RowLevelTTL                  | Holds table ID. If the table in question doesn't have a TTL, the job should fail on resume, so this is likely fine. |
```

- For some jobs such as Changefeed, StreamReplication, StreamIngest,
  and Backup. I think we should consider moving those to reverting as
  well, but even then we'll need to make sure they don't break things
  on cleanup.

*Alternatives I haven't fully thought through*

- Since we know that the only conflict during a restore on 22.1 is almost surely the tenant_settings table with the defaultdb database, we could limit the scope of a near-term fix to only looking at database descriptors and failing on any other conflict. We would still need to fix a good number of jobs.

- Full cluster restores have to happen on a fresh cluster.  Instead of resolving the conflict by rewriting the descriptors in the backup, perhaps we move any conflicting system tables in the cluster to new IDs instead. That would look something like: (1) collect conflicting tables, (2) advance descIdGenerator to `max(max(ids_in_backup), existing_id_gen_val)+1`, in a transaction: create new tables for the conflict system tables, copy data from the old tables to the new tables, swap the new tables into place by updating the namespace table and the descriptors for the new table.

**Comment by stevendanna** [comment]
> Full cluster restores have to happen on a fresh cluster. Instead of resolving the conflict by rewriting the descriptors in the backup, perhaps we move any conflicting system tables in the cluster to new IDs instead. That would look something like: (1) collect conflicting tables, (2) advance descIdGenerator to max(max(ids_in_backup), existing_id_gen_val)+1, in a transaction: create new tables for the conflict system tables, copy data from the old tables to the new tables, swap the new tables into place by updating the namespace table and the descriptors for the new table.

I'm pursuing this option on another branch.

**Comment by RichardJCai** [comment]
>Full cluster restores have to happen on a fresh cluster. Instead of resolving the conflict by rewriting the descriptors in the backup, perhaps we move any conflicting system tables in the cluster to new IDs instead. That would look something like: (1) collect conflicting tables, (2) advance descIdGenerator to max(max(ids_in_backup), existing_id_gen_val)+1, in a transaction: create new tables for the conflict system tables, copy data from the old tables to the new tables, swap the new tables into place by updating the namespace table and the descriptors for the new table.

This sounds promising to me, we also likely won't have to consider the system table ids in schema change jobs.

**Comment by RichardJCai** [comment]
>Since we know that the only conflict during a restore on 22.1 is almost surely the tenant_settings table with the defaultdb database, we could limit the scope of a near-term fix to only looking at database descriptors and failing on any other conflict. We would still need to fix a good number of jobs.

We can also full cluster restore for non-tenants right? In this case we'd be missing the SpanCount table

```
	// Tables introduced in 22.1.

	target.AddDescriptorForSystemTenant(systemschema.TenantSettingsTable)
	target.AddDescriptorForNonSystemTenant(systemschema.SpanCountTable)
```

**Comment by ajwerner** [comment]
Can we just remap system table descriptors above some constant and leave all the user tables as they are? In practice that'll mean that these two tables get ids above all the user table ids, but that seems totally fine.

**Comment by stevendanna** [comment]
@ajwerner 

> Can we just remap system table descriptors above some constant and leave all the user tables as they are? In practice that'll mean that these two tables get ids above all the user table ids, but that seems totally fine.

Do you mean remap them at the time of the restore? If so, that seems similar to what I mentioned here https://github.com/cockroachdb/cockroach/pull/84403#issuecomment-1185601681.  If not, can you elaborate a bit?  One problem I'm unsure of with an approach of moving them at runtime is what breaks at restore time when a previously used descriptor ID now refers to a completely different table. For example, is it a problem for any rangefeeds that are watching the table spans that then get moved, is it a problem for leases, is it a problem for anything that does historical queries too far into the past.  Hopefully once I finish spiking this out I will know more, but it feels like a long tail of things to test.

As mentioned in a recent slack update.  We are now looking at a short term 3rd option of starting new clusters with the IDs for these tables inside the reserved range, allowing us a targetted fix for 22.1 while we work on the larger fix here.

**Comment by stevendanna** [comment]
@RichardJCai 

> We can also full cluster restore for non-tenants right? In this case we'd be missing the SpanCount table

Good catch.

**Comment by RichardJCai** [comment]
> @ajwerner
> 
> > Can we just remap system table descriptors above some constant and leave all the user tables as they are? In practice that'll mean that these two tables get ids above all the user table ids, but that seems totally fine.
> 
  > Do you mean remap them at the time of the restore? If so, that seems similar to what I mentioned here [#84403 (comment)](https://github.com/cockroachdb/cockroach/pull/84403#issuecomment-1185601681). If not, can you elaborate a bit? One problem I'm unsure of with an approach of moving them at runtime is what breaks at restore time when a previously used descriptor ID now refers to a completely different table. For example, is it a problem for any rangefeeds that are watching the table spans that then get moved, is it a problem for leases, is it a problem for anything that does historical queries too far into the past. Hopefully once I finish spiking this out I will know more, but it feels like a long tail of things to test.

What's the order of restoring things, do we do the system table / database restore after restoring all the other tables? If so could we just drop all the system tables (with dynamic ids) before restoring all the non-system tables, then recreate the system table, then do the system table restores (insert rows / migration).

**Comment by stevendanna** [comment]
>  If so could we just drop all the system tables (with dynamic ids) before restoring all the non-system tables, then recreate the system table, then do the system table restores (insert rows / migration).

I think we probably could for now.  But I suppose it would require that the cluster can run correctly for a prolonged period of time without those tables in place. For the two tables in question now, I imagine it would work -- although perhaps you would hit a problem if someone did something like try to start a tenant sql pod during the restore which seems unlikely.

**Comment by adityamaru** [comment]
I'm closing this so that we congregate over here https://github.com/cockroachdb/cockroach/pull/84495.

**Pull request closed without merging**
