### PR TITLE
Add SCRUB TABLE ... INDEX and SCRUB TABLE ... INDEX(idxname) syntax

### PR DESCRIPTION
**Pull request by lgo**
`SCRUB TABLE ... INDEX` is placeholder syntax for the SCRUB feature of
checking secondary indexes. With no indexes specified, this checks all
indexes.

This also adds `SCRUB TABLE ... WITH INDEX(idx_name)`. This provides 
the ability to specify the indexes to check, as opposed to checking them all.

### CODE REVIEW

**Comment by lego** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/parser/sql.y, line 1995 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-KxPU202zs067rZ4B0Z6:-KxPU203GB9ZS4csPoIL:bdxnvgf) ([raw file](https://github.com/cockroachdb/cockroach/blob/95fdf42e1a43a706067e8833b02b5cb4d06a3ebc/pkg/sql/parser/sql.y#L1995)):*
> ```Yacc
> //
> scrub_table_stmt:
>   EXPERIMENTAL SCRUB TABLE qualified_name
> ```

I changed this back to a `qualified_name` as I wasn't quite sure how to go from the placeholder `StrVal` to a table descriptor. The table name is still not used during planning, nor does it need to be in the future. Is there a straightforward way to go from `StrVal` to table descriptor @knz?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583)*

**Comment by jordanlewis** [comment]
:lgtm: with a bunch of nits. Nice!

---

Reviewed 1 of 8 files at r1, 7 of 7 files at r3, 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/sql/scrub.go, line 66 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-Kxnbh-4KPF11w2EbStZ:-Kxnbh-4KPF11w2EbSt_:bd3z1uy) ([raw file](https://github.com/cockroachdb/cockroach/blob/83451eb13f3333aa018cb30b99816a875fe25b03/pkg/sql/scrub.go#L66)):*
> ```Go
> 
> 	if tableDesc.IsView() {
> 		return pgerror.NewErrorf(pgerror.CodeSyntaxError, "cannot run SCRUB on views")
> ```

nit: this seems more like a runtime error than a syntax error to me. maybe there's an available pgerror that's like "wrong kind of table entity" that you could reuse?

---

*[pkg/sql/scrub.go, line 83 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-KxncAsfKyAoqaYL2f7P:-KxncAsfKyAoqaYL2f7Q:bfugc2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/83451eb13f3333aa018cb30b99816a875fe25b03/pkg/sql/scrub.go#L83)):*
> ```Go
> 			}
> 		default:
> 			panic(fmt.Sprintf("Unhandled SCRUB option received: %s", v))
> ```

nit: I think usually we use %+v on error structs in panic in case they're not representable as strings

---

*[pkg/sql/logictest/testdata/logic_test/scrub, line 23 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-KxnchizcpK4GZxiyGkm:-Kxnchj-lAMp1I6hH_2w:b-sap23) ([raw file](https://github.com/cockroachdb/cockroach/blob/83451eb13f3333aa018cb30b99816a875fe25b03/pkg/sql/logictest/testdata/logic_test/scrub#L23)):*
> ```
> 
> statement ok
> CREATE INDEX name_idx ON t (name)
> ```

I suggest putting this create index above the expected error case and adding the valid index name to the expected error case, to ensure that only the missing index names are added to the error message.

---

*[pkg/sql/parser/scrub.go, line 48 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-Kxnb8OUn5DKe-s1ojXG:-Kxnb8OUn5DKe-s1ojXH:b-qqahtt) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f2c6f4df1551ff6de944cc9a002c68b90292e57/pkg/sql/parser/scrub.go#L48)):*
> ```Go
> 	}
> 
> 	if len(n.Options) > 0 {
> ```

Isn't a SCRUB statement with 0 options invalid?

---

*[pkg/sql/parser/scrub.go, line 62 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-Kxnb3yPbyBBogUG5Zsl:-Kxnb3yPbyBBogUG5Zsm:b-fw8l22) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f2c6f4df1551ff6de944cc9a002c68b90292e57/pkg/sql/parser/scrub.go#L62)):*
> ```Go
> type ScrubOptions []ScrubOption
> 
> // ScrubOption representts a scrub option.
> ```

nit: s/representts/represents/

---

*[pkg/sql/parser/scrub.go, line 73 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-Kxnb0PSk0Iayz9OH0gS:-Kxnb0PSk0Iayz9OH0gT:bc23qf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f2c6f4df1551ff6de944cc9a002c68b90292e57/pkg/sql/parser/scrub.go#L73)):*
> ```Go
> 
> // ScrubOptionIndex represents an INDEX scrub check.
> type ScrubOptionIndex struct {
> ```

ignorable nit: could put this on one line

---

*[pkg/sql/parser/scrub.go, line 81 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-Kxnd1Cw8m2QMV_Gxs9H:-Kxnd1Cw8m2QMV_Gxs9I:b-eeoy64) ([raw file](https://github.com/cockroachdb/cockroach/blob/83451eb13f3333aa018cb30b99816a875fe25b03/pkg/sql/parser/scrub.go#L81)):*
> ```Go
> // ScrubOptionIndex represents an INDEX scrub check.
> type ScrubOptionIndex struct {
> 	IndexNames NameList
> ```

ah, not by the next commit you can't! :thumbsup: 

---

*[pkg/sql/parser/sql.y, line 1995 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-KxPU202zs067rZ4B0Z6:-Kxn_xUd7KYy5Dgaf8IF:bej6cgb) ([raw file](https://github.com/cockroachdb/cockroach/blob/95fdf42e1a43a706067e8833b02b5cb4d06a3ebc/pkg/sql/parser/sql.y#L1995)):*
<details><summary><i>Previously, lego (Joey Pereira) wrote…</i></summary><blockquote>

I changed this back to a `qualified_name` as I wasn't quite sure how to go from the placeholder `StrVal` to a table descriptor. The table name is still not used during planning, nor does it need to be in the future. Is there a straightforward way to go from `StrVal` to table descriptor @knz?
</blockquote></details>

We don't have any precedent for placeholders that resolve to Names yet. Seems smart to leave this a qualified name for now.

---

*[pkg/sql/parser/sql.y, line 1993 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-KxnaVn29UzhlN7aJbGT:-KxnaVn29UzhlN7aJbGU:b-raxijr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f2c6f4df1551ff6de944cc9a002c68b90292e57/pkg/sql/parser/sql.y#L1993)):*
> ```Yacc
> //
> // Options:
> //   SCRUB TABLE ... WITH INDEX
> ```

Forgive me and ignore this comment if this was already bikeshedded and I missed it/forgot, but it seems slightly weird to me that the way to specify the list of checks to perform is with the `WITH` keyword. It would make more sense to me if this was something like `WITH CHECKS <option>...` or similar.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-:-KxndBYbItcA8YYMRcWS:b8ru3jt)*

**Comment by lego** [comment]
Review status: 5 of 8 files reviewed at latest revision, 9 unresolved discussions.

---

*[pkg/sql/scrub.go, line 66 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-Kxnbh-4KPF11w2EbStZ:-KxnhEQhe8BmQpRNaN3z:bn2cjjl) ([raw file](https://github.com/cockroachdb/cockroach/blob/83451eb13f3333aa018cb30b99816a875fe25b03/pkg/sql/scrub.go#L66)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: this seems more like a runtime error than a syntax error to me. maybe there's an available pgerror that's like "wrong kind of table entity" that you could reuse?
</blockquote></details>

Hmm yea `CodeWrongObjectTypeError` may be the most appropriate. A few others were:
```
- CodeInvalidTableDefinitionError
- CodeInvalidNameError
```

---

*[pkg/sql/scrub.go, line 83 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-KxncAsfKyAoqaYL2f7P:-KxnhlUCUw4XFCHAfohW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83451eb13f3333aa018cb30b99816a875fe25b03/pkg/sql/scrub.go#L83)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: I think usually we use %+v on error structs in panic in case they're not representable as strings
</blockquote></details>

Done.

---

*[pkg/sql/logictest/testdata/logic_test/scrub, line 23 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-KxnchizcpK4GZxiyGkm:-Kxnhy8dml_9pXY8fu7V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83451eb13f3333aa018cb30b99816a875fe25b03/pkg/sql/logictest/testdata/logic_test/scrub#L23)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I suggest putting this create index above the expected error case and adding the valid index name to the expected error case, to ensure that only the missing index names are added to the error message.
</blockquote></details>

Done.

---

*[pkg/sql/parser/scrub.go, line 48 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-Kxnb8OUn5DKe-s1ojXG:-KxniAh5IqmME5_Lqoua:b-k12c51) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f2c6f4df1551ff6de944cc9a002c68b90292e57/pkg/sql/parser/scrub.go#L48)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Isn't a SCRUB statement with 0 options invalid?
</blockquote></details>

The default behavior will be to check everything that's possible for a table. (see [RFC#Command Usage](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20171025_scrub_sql_consistency_check_command.md#command-usage))

---

*[pkg/sql/parser/scrub.go, line 62 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-Kxnb3yPbyBBogUG5Zsl:-KxniUHUxKnVvUx3zskO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f2c6f4df1551ff6de944cc9a002c68b90292e57/pkg/sql/parser/scrub.go#L62)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: s/representts/represents/
</blockquote></details>

Done.

---

*[pkg/sql/parser/sql.y, line 1993 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-KxnaVn29UzhlN7aJbGT:-Kxnj0gCLwAJ9PEfVXTB:b-y2890m) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f2c6f4df1551ff6de944cc9a002c68b90292e57/pkg/sql/parser/sql.y#L1993)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Forgive me and ignore this comment if this was already bikeshedded and I missed it/forgot, but it seems slightly weird to me that the way to specify the list of checks to perform is with the `WITH` keyword. It would make more sense to me if this was something like `WITH CHECKS <option>...` or similar.
</blockquote></details>

TBH there wasn't any bikeshedding that came up on this, so I'm happy to discuss here. I do agree, it is slightly weird.

Something to also consider is how the repair option comes into play here -- see the [RFC#Repair Process](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20171025_scrub_sql_consistency_check_command.md#repair-process). The `REPAIR`/`REPAIR(...)` options don't fit in with the `WITH CHECKS <option>...` syntax, but the `REPAIR(<option>..)` syntax is also a bit quirky as is. This could maybe also be another expanded part. Maybe `SCRUB TABLE ... WITH CHECKS <option>... WITH REPAIR <option>...`? Or is there saner SQL syntax rather than specifying `WITH` twice?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583)*

**Comment by jordanlewis** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[pkg/sql/scrub.go, line 66 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-Kxnbh-4KPF11w2EbStZ:-KxnnBst_EihZSZAm-v6:bf536w6) ([raw file](https://github.com/cockroachdb/cockroach/blob/83451eb13f3333aa018cb30b99816a875fe25b03/pkg/sql/scrub.go#L66)):*
<details><summary><i>Previously, lego (Joey Pereira) wrote…</i></summary><blockquote>

Hmm yea `CodeWrongObjectTypeError` may be the most appropriate. A few others were:
```
- CodeInvalidTableDefinitionError
- CodeInvalidNameError
```
</blockquote></details>

WrongObjectTypeError SGTM

---

*[pkg/sql/parser/scrub.go, line 48 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-Kxnb8OUn5DKe-s1ojXG:-KxnmNojx5dujp_lvHnm:bmybaa5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f2c6f4df1551ff6de944cc9a002c68b90292e57/pkg/sql/parser/scrub.go#L48)):*
<details><summary><i>Previously, lego (Joey Pereira) wrote…</i></summary><blockquote>

The default behavior will be to check everything that's possible for a table. (see [RFC#Command Usage](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20171025_scrub_sql_consistency_check_command.md#command-usage))
</blockquote></details>

Oh right.  I missed that in the grammar (and I see why now - left another comment). Was going to ask you to add a parse test for this but I see you've already done so :thumbsup: 

---

*[pkg/sql/parser/sql.y, line 1993 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-KxnaVn29UzhlN7aJbGT:-Kxnn0m37G9VPZ8Mi4II:b-uwnb4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f2c6f4df1551ff6de944cc9a002c68b90292e57/pkg/sql/parser/sql.y#L1993)):*
<details><summary><i>Previously, lego (Joey Pereira) wrote…</i></summary><blockquote>

TBH there wasn't any bikeshedding that came up on this, so I'm happy to discuss here. I do agree, it is slightly weird.

Something to also consider is how the repair option comes into play here -- see the [RFC#Repair Process](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20171025_scrub_sql_consistency_check_command.md#repair-process). The `REPAIR`/`REPAIR(...)` options don't fit in with the `WITH CHECKS <option>...` syntax, but the `REPAIR(<option>..)` syntax is also a bit quirky as is. This could maybe also be another expanded part. Maybe `SCRUB TABLE ... WITH CHECKS <option>... WITH REPAIR <option>...`? Or is there saner SQL syntax rather than specifying `WITH` twice?
</blockquote></details>

Okay how about `SCRUB _ WITH OPTIONS INDEX(foo), REPAIR(blah)`? That sounds good to me and we already have `WITH OPTIONS` somewhere else I believe. Sorry I didn't chime in about this during the RFC process.

---

*[pkg/sql/parser/sql.y, line 1999 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-KxnnNaViza0y35D9D_p:-KxnnNaW0so_jiLn3Ap9:bryhus3) ([raw file](https://github.com/cockroachdb/cockroach/blob/14606d08e1caa0aacbf443676675fdeb19b0d9d2/pkg/sql/parser/sql.y#L1999)):*
> ```Yacc
>   {
>     $$.val = &Scrub{Typ: ScrubTable, Table: $4.normalizableTableName()}
>   }scrub_table_stmt:
> ```

I think we're missing a newline here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583)*

**Comment by lego** [comment]
Review status: 1 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/sql/scrub.go, line 66 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-Kxnbh-4KPF11w2EbStZ:-KxnrZLj0jWdgMqD_x8O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83451eb13f3333aa018cb30b99816a875fe25b03/pkg/sql/scrub.go#L66)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

WrongObjectTypeError SGTM
</blockquote></details>

Done.

---

*[pkg/sql/parser/sql.y, line 1993 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-KxnaVn29UzhlN7aJbGT:-KxnrcMCGO_Y5MqH4nPS:b-yb7p8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f2c6f4df1551ff6de944cc9a002c68b90292e57/pkg/sql/parser/sql.y#L1993)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Okay how about `SCRUB _ WITH OPTIONS INDEX(foo), REPAIR(blah)`? That sounds good to me and we already have `WITH OPTIONS` somewhere else I believe. Sorry I didn't chime in about this during the RFC process.
</blockquote></details>

All good! I'm happy with that.

---

*[pkg/sql/parser/sql.y, line 1999 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-KxnnNaViza0y35D9D_p:-Kxns3fQ_zrsBDU6nPfx:b5c584o) ([raw file](https://github.com/cockroachdb/cockroach/blob/14606d08e1caa0aacbf443676675fdeb19b0d9d2/pkg/sql/parser/sql.y#L1999)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think we're missing a newline here
</blockquote></details>

Huh yea, some funky rebase byproduct. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583)*

**Comment by knz** [comment]
Reviewed 1 of 8 files at r1, 8 of 8 files at r6, 7 of 7 files at r7.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/scrub.go, line 43 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-Kxs9VicdaCqxCNtzkPQ:-Kxs9Vidir492q7SQlGy:biimi0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd93ef0d9af6f0a6ac040ebbe66d07ebe1f7e79d/pkg/sql/parser/scrub.go#L43)):*
> ```Go
> 	case ScrubTable:
> 		buf.WriteString("TABLE ")
> 		buf.WriteString(n.Table.String())
> ```

Use `Format` here already in the first commit.

---

*[pkg/sql/parser/scrub.go, line 49 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-Kxs85K2DrXywAaQ_H78:-Kxs85K2DrXywAaQ_H79:b-q694i5) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd93ef0d9af6f0a6ac040ebbe66d07ebe1f7e79d/pkg/sql/parser/scrub.go#L49)):*
> ```Go
> 
> 	if len(n.Options) > 0 {
> 		buf.WriteString(" WITH ")
> ```

" WITH OPTIONS " must already be present in the first commit, otherwise it won't pass its parser tests.

Also I think the two commit messages do not reflect well what is being done in each commit.

I have noticed this here and other PRs -- I think it would benefit you to exercise a bit more diligence about this "each commit must stand on its own" policy we have.
I noticed you have been using a mix of "small fixup commits meant to be squashed at the end" and "layered commits with separate concerns" on different PRs. It's obvious you know how to use small fixup commits with final squash; perhaps you could start to exercise the "layered, separate concerns commits" a bit more.

Think about it like a reviewer: as a reviewer, if I see commits that intend to be layered, I review each commit separately. I do not wish (nor practically can) "peek in the future" and look at later commits to check the correctness of an early commit. The changes must be like a story. 

If you'd rather organize the PR as a single patch, and leave yourself the freedom to use fixup commits, that's also OK as long as you play by the rules: 1) you must tell me upfront, so that I do not waste my time looking at the individual commits (it changes the way I start using reviewable) 2)  the overall change, all commits considered should be smaller in size. 

Here I'm confused. It looks like you have two layered commits, but then it wasn't done properly. 
If you intended the 2nd commit to be a fixup, that's not clear either, and also I'd argue the overall patch is a bit large and would benefit from layered commits.

Where to go from here? If you want to be correct while making me slightly unhappy, you can squash them and I'll review again as a single thing. If you want to exercise a bit and get some good reusable experience in the process, then check out your first commit, make it correct on its own, then amend that, and then rebase the 2nd commit on top of that.

---

*[pkg/sql/parser/sql.y, line 1995 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-KxPU202zs067rZ4B0Z6:-Kxs7vkZXpwjwTHHJDSJ:bb6mt9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/95fdf42e1a43a706067e8833b02b5cb4d06a3ebc/pkg/sql/parser/sql.y#L1995)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

We don't have any precedent for placeholders that resolve to Names yet. Seems smart to leave this a qualified name for now.
</blockquote></details>

:+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583)*

**Comment by lego** [comment]
Review status: 2 of 9 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/sql/parser/scrub.go, line 43 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-Kxs9VicdaCqxCNtzkPQ:-KxsFDoiLpF05I1Ed_XX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd93ef0d9af6f0a6ac040ebbe66d07ebe1f7e79d/pkg/sql/parser/scrub.go#L43)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Use `Format` here already in the first commit.
</blockquote></details>

Done.

---

*[pkg/sql/parser/scrub.go, line 49 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-Kxs85K2DrXywAaQ_H78:-KxsFEampc5UU-6CZWkh:b-8w0cd3) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd93ef0d9af6f0a6ac040ebbe66d07ebe1f7e79d/pkg/sql/parser/scrub.go#L49)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

" WITH OPTIONS " must already be present in the first commit, otherwise it won't pass its parser tests.

Also I think the two commit messages do not reflect well what is being done in each commit.

I have noticed this here and other PRs -- I think it would benefit you to exercise a bit more diligence about this "each commit must stand on its own" policy we have.
I noticed you have been using a mix of "small fixup commits meant to be squashed at the end" and "layered commits with separate concerns" on different PRs. It's obvious you know how to use small fixup commits with final squash; perhaps you could start to exercise the "layered, separate concerns commits" a bit more.

Think about it like a reviewer: as a reviewer, if I see commits that intend to be layered, I review each commit separately. I do not wish (nor practically can) "peek in the future" and look at later commits to check the correctness of an early commit. The changes must be like a story. 

If you'd rather organize the PR as a single patch, and leave yourself the freedom to use fixup commits, that's also OK as long as you play by the rules: 1) you must tell me upfront, so that I do not waste my time looking at the individual commits (it changes the way I start using reviewable) 2)  the overall change, all commits considered should be smaller in size. 

Here I'm confused. It looks like you have two layered commits, but then it wasn't done properly. 
If you intended the 2nd commit to be a fixup, that's not clear either, and also I'd argue the overall patch is a bit large and would benefit from layered commits.

Where to go from here? If you want to be correct while making me slightly unhappy, you can squash them and I'll review again as a single thing. If you want to exercise a bit and get some good reusable experience in the process, then check out your first commit, make it correct on its own, then amend that, and then rebase the 2nd commit on top of that.

</blockquote></details>

Sorry, this was a bit sloppy. I have been putting an effort in to have separate commits to help with reviewing more recently and that is what I intended here. This was meant to be separate commits from the start.

On that note, I still haven't figured out navigate to use reviewable with separate commits even though the option to review separate commits selected. Are there always two revisions that aren't out of date, and are those the latest revision of each respective commits?

(:S oops, while fixing this I accidentally amended everything into one commit instead of rebasing the second commit and pushed without noticing, but that's fixed now)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583)*

**Comment by knz** [comment]
Right now I see 4 separate commits, not two.

---

Review status: 2 of 9 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-:-KxsIsm6F1rrQEQJtoz0:b-6di9y3)*

**Comment by knz** [comment]
I :heart: this! Well done

---

Reviewed 7 of 7 files at r8, 7 of 7 files at r9.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---

*[pkg/sql/parser/parse_test.go, line 799 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-KxsMHqLgbqLDi1l56IC:-KxsMHqOWGMiX0AtJ6z6:b3y4d7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/71ef054024dcc9e79b3a6d3f0c159de21eed3eeb/pkg/sql/parser/parse_test.go#L799)):*
> ```Go
> 		{`EXPERIMENTAL SCRUB TABLE x`},
> 		{`EXPERIMENTAL SCRUB TABLE x WITH OPTIONS INDEX`},
> 		{`EXPERIMENTAL SCRUB TABLE x WITH OPTIONS INDEX(index_name)`},
> ```

nit: space before `(`

---

*[pkg/sql/parser/scrub.go, line 88 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-KxsMCNVfQLZSXnoY0Mn:-KxsMCNVfQLZSXnoY0Mo:b3y4d7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/71ef054024dcc9e79b3a6d3f0c159de21eed3eeb/pkg/sql/parser/scrub.go#L88)):*
> ```Go
> 	buf.WriteString("INDEX")
> 	if n.IndexNames != nil {
> 		buf.WriteString("(")
> ```

nit: space before `(`

---

*[pkg/sql/parser/scrub.go, line 90 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-KxsMEM1hP5deK2oKr3O:-KxsMEM1hP5deK2oKr3P:bop9ikl) ([raw file](https://github.com/cockroachdb/cockroach/blob/71ef054024dcc9e79b3a6d3f0c159de21eed3eeb/pkg/sql/parser/scrub.go#L90)):*
> ```Go
> 		buf.WriteString("(")
> 		n.IndexNames.Format(buf, f)
> 		buf.WriteString(")")
> ```

`buf.WriteByte(')')`

---

*[pkg/sql/parser/sql.y, line 1993 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-KxsLtzGFZrbE9NjkH4k:-KxsLtzGFZrbE9NjkH4l:b-2z1svu) ([raw file](https://github.com/cockroachdb/cockroach/blob/71ef054024dcc9e79b3a6d3f0c159de21eed3eeb/pkg/sql/parser/sql.y#L1993)):*
> ```Yacc
> //
> // Options:
> //   SCRUB TABLE ... WITH OPTIONS INDEX
> ```

I'm confused about the difference between `INDEX` and `INDEX(...)`. Is the one without argument meant to mean "all the indexes"? In that case I'd recommend `WITH OPTIONS INDEX ALL` for one and `WITH OPTIONS INDEX(...)` for the other.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-:-KxsML-uoCUsCyqo3NvY:bkaoqg9)*

**Comment by lego** [comment]
Addressed everything. Looks like reviewable is still mucked on connecting the rebased commits.

---

Review status: 1 of 9 files reviewed at latest revision, 10 unresolved discussions.

---

*[pkg/sql/parser/parse_test.go, line 799 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-KxsMHqLgbqLDi1l56IC:-Kxse1HiCn73abYnPEgj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/71ef054024dcc9e79b3a6d3f0c159de21eed3eeb/pkg/sql/parser/parse_test.go#L799)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: space before `(`
</blockquote></details>

Done.

---

*[pkg/sql/parser/scrub.go, line 88 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-KxsMCNVfQLZSXnoY0Mn:-Kxse2WocphIlwq5kTF7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/71ef054024dcc9e79b3a6d3f0c159de21eed3eeb/pkg/sql/parser/scrub.go#L88)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: space before `(`
</blockquote></details>

Done.

---

*[pkg/sql/parser/scrub.go, line 90 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-KxsMEM1hP5deK2oKr3O:-Kxse2tHNTQfHVLdO1Yj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/71ef054024dcc9e79b3a6d3f0c159de21eed3eeb/pkg/sql/parser/scrub.go#L90)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`buf.WriteByte(')')`
</blockquote></details>

Done.

---

*[pkg/sql/parser/sql.y, line 1993 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-KxsLtzGFZrbE9NjkH4k:-KxsX3zQAtClw_Op-VfK:b-76497y) ([raw file](https://github.com/cockroachdb/cockroach/blob/71ef054024dcc9e79b3a6d3f0c159de21eed3eeb/pkg/sql/parser/sql.y#L1993)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'm confused about the difference between `INDEX` and `INDEX(...)`. Is the one without argument meant to mean "all the indexes"? In that case I'd recommend `WITH OPTIONS INDEX ALL` for one and `WITH OPTIONS INDEX(...)` for the other.
</blockquote></details>

Ah yes! At first glance, `INDEX ALL` seemed inconsistent with the other options, but along with the change to add a preceding space before the `(<idxname>...)`, the syntax is both elegant and consistent with other statements :).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-:-KxseGXibmhmjtFlRrYN:brrgamr)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 1 of 8 files at r10, 7 of 7 files at r11.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19583#-:-KxshNlCqKAfgx_MVgkx:bnfp4nl)*

**Pull request merged**
