### PR TITLE
Map "flag" package flags into the "pflag" package.

### LINKED ISSUE #931: the glog flags are broken
this is due to the change from go-commander to cobra.

basically everything shown by `./cockroach listparams` isn't working any more.

* we need to mirror glog's flags to cobra and after parsing those flags, store them with the flag package. i think `flag.Set(name, k, v)` can be useful here. Then `flag.Parse()` when they're all updated.
* note that listparams includes all the test flags - that suggests that we're compiling in the test package
in our real code. probably that happens with some of the exported test functions that we pass a *testing.T to - we should re-evaluate whether that's a good idea.
* listparams should list cobra's flags, not the others. but i suspect this is a good moment to ditch listparams - all flags should be explained by the actual help.

### PR DESCRIPTION
**Pull request by petermattis**
Remove the "listparams" command. It is no longer useful now that the
help message displays the flags for a particular command.

Fixes #931.

### CODE REVIEW

**Comment by tamird** [comment]
Could you add a test for this using http://godoc.org/flag#VisitAll and http://godoc.org/github.com/ogier/pflag#VisitAll ?

**Comment by petermattis** [comment]
I added a test that the glog flags are now functional. Working on adding one using `VisitAll` as well.

**Comment by petermattis** [comment]
Ok, got the `VisitAll` test working as well. PTAL.

**Comment by tamird** [comment]
:+1: good stuff

**Pull request merged**
