### PR TITLE
sql: parse VALIDATE commands, implement VALIDATE of CHECK

### PR DESCRIPTION
**Pull request by dt**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9152)

### CODE REVIEW

**Comment by paperstreet** [comment]
Reviewed 4 of 4 files at r1, 7 of 7 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[sql/alter_table.go, line 251 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152#-KR0BI0c90jt7oU28dPz:-KR0BI0c90jt7oU28dQ-:b-ur1sdl) ([raw file](https://github.com/cockroachdb/cockroach/blob/70502f96896e8ab97e45f01c93a9ccefd6db2019/sql/alter_table.go#L251)):*
> ```Go
> 			}
> 			name := string(t.Constraint)
> 			details, ok := info[name]
> ```

nit: "details" could have a better name. maybe "constraint"?

---

*[sql/alter_table.go, line 261 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152#-KR0BrZr-9SZofS0bFDz:-KR0BrZr-9SZofS0bFE-:b-8mzu78) ([raw file](https://github.com/cockroachdb/cockroach/blob/2173babbff3b94db0a7dbe0fa09336c6a49b9a1d/sql/alter_table.go#L261)):*
> ```Go
> 			switch details.Kind {
> 			case sqlbase.ConstraintTypeCheck:
> 				var idx int
> ```

pull this all out into a method?

---

*[sql/alter_table.go, line 266 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152#-KR0COHiCZQ-y6-4_Ycs:-KR0COHiCZQ-y6-4_Yct:bh8e3fz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2173babbff3b94db0a7dbe0fa09336c6a49b9a1d/sql/alter_table.go#L266)):*
> ```Go
> 						break
> 					}
> 				}
> ```

hmm, this does handle the not found case right now, but it still makes me a little uncomfortable to not check for idx == 0 here

---

*[sql/alter_table.go, line 273 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152#-KR0Cv6DbAqluRk4Mprt:-KR0Cv6DbAqluRk4Mpru:b-pzef20) ([raw file](https://github.com/cockroachdb/cockroach/blob/2173babbff3b94db0a7dbe0fa09336c6a49b9a1d/sql/alter_table.go#L273)):*
> ```Go
> 				}
> 				rows, err := n.p.SelectClause(&parser.SelectClause{
> 					Exprs: sqlbase.ColumnsSelectors(n.tableDesc.Columns),
> ```

this is only the public columns, right? you have publicAndNonPublicColumns below

---

*[sql/alter_table.go, line 275 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152#-KR0D3U46bZq_XceM37K:-KR0D3U46bZq_XceM37L:b-v69mcv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2173babbff3b94db0a7dbe0fa09336c6a49b9a1d/sql/alter_table.go#L275)):*
> ```Go
> 					Exprs: sqlbase.ColumnsSelectors(n.tableDesc.Columns),
> 					From:  &parser.From{Tables: parser.TableExprs{&n.n.Table}},
> 					Where: &parser.Where{Expr: &parser.NotExpr{Expr: expr}},
> ```

woah. very nice

---

*[sql/alter_table.go, line 276 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152#-KR0DBhJdClmBNCOiLR-:-KR0DBhJdClmBNCOiLR0:bq2dtye) ([raw file](https://github.com/cockroachdb/cockroach/blob/2173babbff3b94db0a7dbe0fa09336c6a49b9a1d/sql/alter_table.go#L276)):*
> ```Go
> 					From:  &parser.From{Tables: parser.TableExprs{&n.n.Table}},
> 					Where: &parser.Where{Expr: &parser.NotExpr{Expr: expr}},
> 				}, nil, &parser.Limit{Count: parser.NewDInt(1)}, nil, publicAndNonPublicColumns)
> ```

i didn't see this limit clause at first. line wrapping here could be improved

---

*[sql/testdata/alter_table, line 134 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152#-KR0CR-yH2uP0nmubCi7:-KR0CR-zx8DhP4avkDqW:b-2qiev) ([raw file](https://github.com/cockroachdb/cockroach/blob/2173babbff3b94db0a7dbe0fa09336c6a49b9a1d/sql/testdata/alter_table#L134)):*
> ```
> 
> statement ok
> ALTER TABLE t VALIDATE CONSTRAINT check_a
> ```

test to validate a constraint that doesn't exist?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152)*

**Comment by nvanbenschoten** [comment]
Reviewed 4 of 4 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

*[sql/alter_table.go, line 266 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152#-KR0COHiCZQ-y6-4_Ycs:-KR0F1hg7-LxTq3oLGEX:bj86vn5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2173babbff3b94db0a7dbe0fa09336c6a49b9a1d/sql/alter_table.go#L266)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> hmm, this does handle the not found case right now, but it still makes me a little uncomfortable to not check for idx == 0 here
</details>
I agree, it seems like there should be some assertion here.

---

*[sql/alter_table.go, line 272 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152#-KR0Fe3OUSryqfJKQP-h:-KR0Fe3OUSryqfJKQP-i:b6rwk26) ([raw file](https://github.com/cockroachdb/cockroach/blob/2173babbff3b94db0a7dbe0fa09336c6a49b9a1d/sql/alter_table.go#L272)):*
> ```Go
> 					return err
> 				}
> 				rows, err := n.p.SelectClause(&parser.SelectClause{
> ```

Is there a benefit to doing this over calling `planner.queryRow`?

---

*[sql/alter_table.go, line 293 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152#-KR0FrRlK0SZZPfF87KT:-KR0FrRlK0SZZPfF87KU:bdk0ssf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2173babbff3b94db0a7dbe0fa09336c6a49b9a1d/sql/alter_table.go#L293)):*
> ```Go
> 				}
> 				n.tableDesc.Checks[idx].Validity = sqlbase.ConstraintValidity_Validated
> 				descriptorChanged = true
> ```

I'm not sure if it matters, but do we want to set this only if `n.tableDesc.Checks[idx].Validity` wasnt already  `ConstraintValidity_Validated`?

---

*[sql/parser/alter_table.go, line 165 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152#-KR0ETOiVHGaqguS0TCD:-KR0ETOiVHGaqguS0TCE:bco2nkg) ([raw file](https://github.com/cockroachdb/cockroach/blob/70502f96896e8ab97e45f01c93a9ccefd6db2019/sql/parser/alter_table.go#L165)):*
> ```Go
> 
> // AlterTableValidateConstraint represents a VALIDATE CONSTRAINT command.
> type AlterTableValidateConstraint struct {
> ```

nit: Should AlterTable structs in this file be ordered alphabetically?

---

*[sql/parser/sql.y, line 903 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152#-KR0DlsSkyizAaWJAj92:-KR0DlsT93OXpxToTcOj:b-yt9jqq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9945072f5b6a9a4b76a08c4e8b18b99ff92d19bb/sql/parser/sql.y#L903)):*
> ```Yacc
> | /* EMPTY */
>   {
>   $$.val = ValidationDefault
> ```

Missing two spaces.

---

*[sql/testdata/alter_table, line 128 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152#-KR0G7b4YCd-FlX-XTDC:-KR0G7b4YCd-FlX-XTDD:b8cajp5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2173babbff3b94db0a7dbe0fa09336c6a49b9a1d/sql/testdata/alter_table#L128)):*
> ```
> 
> statement error validation of CHECK "a > 0" failed on row: a=-2, f=9, b=NULL, c=NULL
> ALTER TABLE t VALIDATE CONSTRAINT check_a
> ```

add a test to validate a constraint that is not failing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

*[sql/alter_table.go, line 261 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152#-KR0BrZr-9SZofS0bFDz:-KR0DUmzi16R3m7V5QV2:bs0z29a) ([raw file](https://github.com/cockroachdb/cockroach/blob/2173babbff3b94db0a7dbe0fa09336c6a49b9a1d/sql/alter_table.go#L261)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> pull this all out into a method?
</details>
heh, that's in the followup that makes `ADD CONSTRAINT` call this for you (if you don't specify `NOT VALID`).

---

*[sql/alter_table.go, line 266 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152#-KR0COHiCZQ-y6-4_Ycs:-KR0DowCkpKBs6k7up46:b-zelaef) ([raw file](https://github.com/cockroachdb/cockroach/blob/2173babbff3b94db0a7dbe0fa09336c6a49b9a1d/sql/alter_table.go#L266)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> hmm, this does handle the not found case right now, but it still makes me a little uncomfortable to not check for idx == 0 here
</details>
The not found case is theoretically impossible, since the map was generated by iterating over the desc... but I could add an explicit panic.

what's special about `idx == 0` though?

---

*[sql/alter_table.go, line 272 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152#-KR0Fe3OUSryqfJKQP-h:-KR0HBDI9QgfvhOHSrvT:b-3j9qv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2173babbff3b94db0a7dbe0fa09336c6a49b9a1d/sql/alter_table.go#L272)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Is there a benefit to doing this over calling `planner.queryRow`?
</details>
constructing a query string just to parse it again felt a little gross to me?

---

*[sql/alter_table.go, line 293 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152#-KR0FrRlK0SZZPfF87KT:-KR0HLbYWhxzA_jrDPz8:b-c755pr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2173babbff3b94db0a7dbe0fa09336c6a49b9a1d/sql/alter_table.go#L293)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> I'm not sure if it matters, but do we want to set this only if `n.tableDesc.Checks[idx].Validity` wasnt already  `ConstraintValidity_Validated`?
</details>
There's a `continue` above it it wasn't unvalidated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152)*

**Comment by paperstreet** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

*[sql/alter_table.go, line 266 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152#-KR0COHiCZQ-y6-4_Ycs:-KR0IIdnah9cFtlj3UCA:b-wtsu3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/2173babbff3b94db0a7dbe0fa09336c6a49b9a1d/sql/alter_table.go#L266)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> The not found case is theoretically impossible, since the map was generated by iterating over the desc... but I could add an explicit panic.
> 
> what's special about `idx == 0` though?
> 
</details>
I guess my point is that it's theoretically impossible _now_, but who knows what code will creep in later.

I was thinking`idx == 0` as a sentinel, but that's wrong. You'd have to use -1 or something.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152)*

**Comment by dt** [comment]
Review status: 0 of 8 files reviewed at latest revision, 12 unresolved discussions, some commit checks pending.

---

*[sql/alter_table.go, line 251 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152#-KR0BI0c90jt7oU28dPz:-KR5HaJOoPtjFPJEQldf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/70502f96896e8ab97e45f01c93a9ccefd6db2019/sql/alter_table.go#L251)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> nit: "details" could have a better name. maybe "constraint"?
</details>
Done.

---

*[sql/alter_table.go, line 261 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152#-KR0BrZr-9SZofS0bFDz:-KR5Hakb-MorHEAIUseJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2173babbff3b94db0a7dbe0fa09336c6a49b9a1d/sql/alter_table.go#L261)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> heh, that's in the followup that makes `ADD CONSTRAINT` call this for you (if you don't specify `NOT VALID`).
</details>
Done.

---

*[sql/alter_table.go, line 266 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152#-KR0COHiCZQ-y6-4_Ycs:-KR5IaPHs8FHvToGcVO7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2173babbff3b94db0a7dbe0fa09336c6a49b9a1d/sql/alter_table.go#L266)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> I guess my point is that it's theoretically impossible _now_, but who knows what code will creep in later.
> 
> I was thinking`idx == 0` as a sentinel, but that's wrong. You'd have to use -1 or something.
</details>
Done.

---

*[sql/alter_table.go, line 276 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152#-KR0DBhJdClmBNCOiLR-:-KR5IyRWf3iXW7YKvj3V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2173babbff3b94db0a7dbe0fa09336c6a49b9a1d/sql/alter_table.go#L276)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> i didn't see this limit clause at first. line wrapping here could be improved
</details>
Done.

---

*[sql/parser/alter_table.go, line 165 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152#-KR0ETOiVHGaqguS0TCD:-KR5JxznQqNIoS8szTKn:b-k12zji) ([raw file](https://github.com/cockroachdb/cockroach/blob/70502f96896e8ab97e45f01c93a9ccefd6db2019/sql/parser/alter_table.go#L165)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> nit: Should AlterTable structs in this file be ordered alphabetically?
</details>
Huh, should they? I assumed it should go near the other constraint ones.

In practice I assume most people jump into the parser.* structs via grep/guru/gocode rather than browsing them, so can't imagine it matters either way really.

---

*[sql/parser/sql.y, line 903 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152#-KR0DlsSkyizAaWJAj92:-KR5JruiWvNs2fCYImN5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9945072f5b6a9a4b76a08c4e8b18b99ff92d19bb/sql/parser/sql.y#L903)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Missing two spaces.
</details>
Done.

---

*[sql/testdata/alter_table, line 128 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152#-KR0G7b4YCd-FlX-XTDC:-KR5J2XmhPTEOJ4quEbk:beg9gi) ([raw file](https://github.com/cockroachdb/cockroach/blob/2173babbff3b94db0a7dbe0fa09336c6a49b9a1d/sql/testdata/alter_table#L128)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> add a test to validate a constraint that is not failing?
</details>
Isn't that what the one two lines below does?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 8 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[sql/alter_table.go, line 272 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152#-KR0Fe3OUSryqfJKQP-h:-KR6bCN1bbAkTI2pztD4:b5wp5mw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2173babbff3b94db0a7dbe0fa09336c6a49b9a1d/sql/alter_table.go#L272)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> constructing a query string just to parse it again felt a little gross to me?
</details>
I guess, but I hate to see the details of `expandPlan`/`Start`/`Next` scattered even further throughout this code. Encapsulating logic like this as much as possible seems like the way to go, if possible. Your call though.

---

*[sql/testdata/alter_table, line 128 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152#-KR0G7b4YCd-FlX-XTDC:-KR6biKGtafw3TbfYT0X:brxr927) ([raw file](https://github.com/cockroachdb/cockroach/blob/2173babbff3b94db0a7dbe0fa09336c6a49b9a1d/sql/testdata/alter_table#L128)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> Isn't that what the one two lines below does?
</details>
yep, didnt see that!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9152)*

**Pull request merged**
