### PR TITLE
sql: fix incorrect follower read and testing knob for sql stats compaction job

### PR DESCRIPTION
**Pull request by Azhng**
Previously, the SQL Stats Compaction job did not check for nil testing 
knobs and constructed its SQL query with incorrect follower read syntax.
This commit address those two bugs.

Release justification: Category 2: Bug fixes and low-risk updates
 to new functionality

Release note: None

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69346)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69346#-MhxTygB9kDGndON8DWk:-MhxTygB9kDGndON8DWl:b-2g0rxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f19d4f2ba2d21b91c47f15c4012bcaf9bb057e7/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L199)):*
> ```Go
> SELECT count(*)
> FROM %[1]s
> %[3]s
> ```

why it was necessary to change to order of this clause?

**Review by matthewtodd — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69346)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69346#-MhxgSJN77bWCi6rB_2X):*
nit: spelling / grammar: "Previously, the SQL Stats Compaction job did not check for nil testing knobs and constructed its SQL query with incorrect follower read syntax."
___
*[-- commits, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69346#-MhxhPev6B2ASa_IA8Mx):*
über-nit: leading space
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69346#-MhxhZNi7G__aTQMrYSD:-MhxhZNi7G__aTQMrYSE:b-6uzwlb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f19d4f2ba2d21b91c47f15c4012bcaf9bb057e7/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L199)):*
> ```Go
> SELECT count(*)
> FROM %[1]s
> %[3]s
> ```

Is it possible to write a test for this fix?
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69346#-MhxhwIR8nae8xPTaq-d:-MhxhwISB8H3wA3QBqaZ:bnklyhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f19d4f2ba2d21b91c47f15c4012bcaf9bb057e7/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L199)):*
> ```Go
> SELECT count(*)
> FROM %[1]s
> %[3]s
> ```

And would you want to reorder the placeholder indexes now to match their positions?

```
SELECT count(*)
FROM %[1]s
%[2]s
WHERE %[3]s = $1
```
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69346#-MhxhdNz06l5TwxmuYb4:-MhxhdO-1Otowa-Nr8pb:boxpaw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f19d4f2ba2d21b91c47f15c4012bcaf9bb057e7/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L204)):*
> ```Go
> 	followerReadClause := "AS OF SYSTEM TIME follower_read_timestamp()"
> 
> 	if c.knobs != nil && c.knobs.DisableFollowerRead {
> ```

Is it possible to write a test for this fix? Or, better yet, is there a way to make these knobs never nil in the first place?

**Review by matthewtodd — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69346)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69346)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @matthewtodd)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69346#-MhxgSJN77bWCi6rB_2X):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: spelling / grammar: "Previously, the SQL Stats Compaction job did not check for nil testing knobs and constructed its SQL query with incorrect follower read syntax."
</blockquote></details>

Done.
___
*[-- commits, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69346#-MhxhPev6B2ASa_IA8Mx):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

über-nit: leading space
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69346#-MhxTygB9kDGndON8DWk:-Mhy9Egt0mcJQGBsilO3:bb8c2fz) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f19d4f2ba2d21b91c47f15c4012bcaf9bb057e7/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L199)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

why it was necessary to change to order of this clause?
</blockquote></details>

This is because the ASOT clause was placed in a wrong place.

Originally, it generates queries like:

```sql
SELECT count(*)
FROM system.statement_statistics
WHERE ...
AS OF SYSTEM TIME follower_read_timestamp()
```

but the correct syntax should be


```sql
SELECT count(*)
FROM system.statement_statistics
AS OF SYSTEM TIME follower_read_timestamp()
WHERE ...
```

We disabled follower read in test because this would cause historical reads into a point where system tables are not even created yet. This is a scenario where it doesn't happen outside of testing. 
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69346#-MhxhZNi7G__aTQMrYSD:-MhyA75V-HUjczQgElKf:bqlkhly) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f19d4f2ba2d21b91c47f15c4012bcaf9bb057e7/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L199)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Is it possible to write a test for this fix?
</blockquote></details>

Would be difficult, follower read is difficult for us to test in the SQL land. The only hack would be `time.Sleep()` and wait for the follower read timestamp to be higher than the point where system tables are created. But we really want to avoid doing those in test. 
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69346#-MhxhwIR8nae8xPTaq-d:-MhyBuUY-6KtKTzS4UFo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f19d4f2ba2d21b91c47f15c4012bcaf9bb057e7/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L199)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

And would you want to reorder the placeholder indexes now to match their positions?

```
SELECT count(*)
FROM %[1]s
%[2]s
WHERE %[3]s = $1
```
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69346#-MhxhdNz06l5TwxmuYb4:-MhyApsP93t3AFgvooDZ:b-b8piou) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f19d4f2ba2d21b91c47f15c4012bcaf9bb057e7/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L204)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Is it possible to write a test for this fix? Or, better yet, is there a way to make these knobs never nil in the first place?
</blockquote></details>

Hmm, since this is only used for test, I hope we can avoid the extra allocation unless it's necessary.

**Review by matthewtodd — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69346)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @matthewtodd)

___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69346#-MhxhZNi7G__aTQMrYSD:-MhyEn5QDppu1m-KvS3J:b-t44m6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f19d4f2ba2d21b91c47f15c4012bcaf9bb057e7/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L199)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Would be difficult, follower read is difficult for us to test in the SQL land. The only hack would be `time.Sleep()` and wait for the follower read timestamp to be higher than the point where system tables are created. But we really want to avoid doing those in test. 
</blockquote></details>

Understood. It's a shame we can't protect ourselves from bad SQL. Like maybe we'd want some infrastructure to run the query through the parser or something. But non-blocking for now.
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69346#-MhxhdNz06l5TwxmuYb4:-MhyFPAp2LDlDipHFD2l:b57tygk) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f19d4f2ba2d21b91c47f15c4012bcaf9bb057e7/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L204)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm, since this is only used for test, I hope we can avoid the extra allocation unless it's necessary. 
</blockquote></details>

Fair enough. :-) Thoughts on a test somehow?

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69346)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @matthewtodd)

___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69346#-MhxhdNz06l5TwxmuYb4:-MhyR76Q62sG8vr2qOts:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f19d4f2ba2d21b91c47f15c4012bcaf9bb057e7/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L204)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Fair enough. :-) Thoughts on a test somehow?
</blockquote></details>

Done.

**Review by matthewtodd — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69346#-:-MhyRbUkAJaEwGUydz_w:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag and @matthewtodd)

**Review by maryliag — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69346#-:-Mi1a4UhCNqrVOQBxRrg:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng)

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69346)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng)

___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69346#-MhxhZNi7G__aTQMrYSD:-Mi1iKgiEjMXmZAp3faC:b-p3wjmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f19d4f2ba2d21b91c47f15c4012bcaf9bb057e7/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L199)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Understood. It's a shame we can't protect ourselves from bad SQL. Like maybe we'd want some infrastructure to run the query through the parser or something. But non-blocking for now.
</blockquote></details>

You could pass a different expression in the follower read clause like `'-1us'` and then sleep for 1 microsecond. I prefer that to no testing.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69346)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng)

___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69346#-MhxhZNi7G__aTQMrYSD:-Mi1iSBH9pwYNzwIgZW6:b-z9q8j9) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f19d4f2ba2d21b91c47f15c4012bcaf9bb057e7/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L199)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

You could pass a different expression in the follower read clause like `'-1us'` and then sleep for 1 microsecond. I prefer that to no testing. 
</blockquote></details>

In fact, maybe that's the answer here. Maybe we get rid of the knob to disable follower reads and replace it with a knob to set up the fixed timestamp to `'-1us'`. I don't think you need to sleep 1us.

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69346)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @maryliag)

___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69346#-MhxhZNi7G__aTQMrYSD:-Mi1yMoJ3_4XFInkatvC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f19d4f2ba2d21b91c47f15c4012bcaf9bb057e7/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L199)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

In fact, maybe that's the answer here. Maybe we get rid of the knob to disable follower reads and replace it with a knob to set up the fixed timestamp to `'-1us'`. I don't think you need to sleep 1us. 
</blockquote></details>

Done.

**Review by ajwerner — APPROVED** [review]
:lgtm: :ship: it

> Reviewed 2 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69346#-:-Mi1zJGO8dBWSyUwY3wb:byyqhtk)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @Azhng and @maryliag)

___
*[pkg/sql/sqlstats/persistedsqlstats/reader_test.go, line 57 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69346#-Mi1zB6a6Oq3tfhgp2__:-Mi1zB6a6Oq3tfhgp2_a:b-t05b38) ([raw file](https://github.com/cockroachdb/cockroach/blob/fab0c78a0154af45092437e810dd321824228382/pkg/sql/sqlstats/persistedsqlstats/reader_test.go#L57)):*
> ```
> 	// Wait for the system table to be created by ASOT timestamp.
> 	time.Sleep(time.Microsecond)
> ```
Do you actually need these? I have a feeling the answer is no.

**Review by matthewtodd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69346)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @Azhng and @maryliag)

___
*[pkg/sql/sqlstats/persistedsqlstats/test_utils.go, line 27 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69346#-Mi20Y9ZCSJRax0jCJq4:-Mi20Y9ZCSJRax0jCJq5:b7d4klx) ([raw file](https://github.com/cockroachdb/cockroach/blob/fab0c78a0154af45092437e810dd321824228382/pkg/sql/sqlstats/persistedsqlstats/test_utils.go#L27)):*
> ```Go
> 	// ASOTClause overrides the AS OF SYSTEM TIME clause in queries used in
> 	// persistedsqlstats.
> 	ASOTClause string
> ```

nit: Do you want this to be `AOSTClause` instead?

**Review by Azhng — COMMENTED** [review]
Human brain is interesting 🤯

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69346#-:-Mi22kbs5DyM8ZpjUd5h:b-4qs70z)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @ajwerner and @maryliag)

___
*[pkg/sql/sqlstats/persistedsqlstats/reader_test.go, line 57 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69346#-Mi1zB6a6Oq3tfhgp2__:-Mi22xhW0bubEZEUvO2f:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/fab0c78a0154af45092437e810dd321824228382/pkg/sql/sqlstats/persistedsqlstats/reader_test.go#L57)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	// Wait for the system table to be created by ASOT timestamp.
> 	time.Sleep(time.Microsecond)
> ```
Do you actually need these? I have a feeling the answer is no. 
</blockquote></details>

Removed.
___
*[pkg/sql/sqlstats/persistedsqlstats/test_utils.go, line 27 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69346#-Mi20Y9ZCSJRax0jCJq4:-Mi22zJFDworrW6R4ljV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fab0c78a0154af45092437e810dd321824228382/pkg/sql/sqlstats/persistedsqlstats/test_utils.go#L27)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: Do you want this to be `AOSTClause` instead?
</blockquote></details>

Done.

**Pull request merged**
