### PR TITLE
sql/sqlbase: memoize parsed, type checked computed col expressions

### PR DESCRIPTION
**Pull request by eriktrinh**
Parse and type check computed column expressions at most once for the
duration of the lease on the table version. Reuse the results in
subsequent write commands.

Release note (performance improvement): Inserts and updates on tables
with computed columns skips the parsing stage of the computed
expressions.

### CODE REVIEW

**Comment by eriktrinh** [comment]
```
name                                                        old time/op    new time/op    delta
SQL/Cockroach/InsertComputedColumns/count=1-24                 948µs ± 4%     746µs ±11%  -21.27%  (p=0.000 n=10+9)
SQL/Cockroach/InsertComputedColumns/count=10-24               4.37ms ±13%    3.21ms ± 9%  -26.40%  (p=0.000 n=10+10)
SQL/Cockroach/InsertComputedColumns/count=100-24              14.6ms ± 6%    11.2ms ± 9%  -23.25%  (p=0.000 n=10+10)
SQL/Cockroach/InsertComputedColumns/count=1000-24             75.7ms ± 7%    65.0ms ± 4%  -14.13%  (p=0.000 n=10+10)
name                                                        old alloc/op   new alloc/op   delta
SQL/Cockroach/InsertComputedColumns/count=1-24                 132kB ± 0%     102kB ± 5%  -22.70%  (p=0.000 n=9+10)
SQL/Cockroach/InsertComputedColumns/count=10-24                597kB ± 3%     457kB ± 7%  -23.44%  (p=0.000 n=10+10)
SQL/Cockroach/InsertComputedColumns/count=100-24              2.20MB ± 2%    1.86MB ± 3%  -15.59%  (p=0.000 n=10+10)
SQL/Cockroach/InsertComputedColumns/count=1000-24             13.3MB ± 1%    12.2MB ± 2%   -8.15%  (p=0.000 n=10+10)
name                                                        old allocs/op  new allocs/op  delta
SQL/Cockroach/InsertComputedColumns/count=1-24                 1.02k ± 0%     0.53k ± 8%  -48.11%  (p=0.000 n=9+10)
SQL/Cockroach/InsertComputedColumns/count=10-24                4.77k ± 4%     2.65k ± 8%  -44.49%  (p=0.000 n=10+10)
SQL/Cockroach/InsertComputedColumns/count=100-24               19.0k ± 2%     13.6k ± 3%  -28.08%  (p=0.000 n=10+10)
SQL/Cockroach/InsertComputedColumns/count=1000-24               121k ± 1%      105k ± 1%  -13.09%  (p=0.000 n=8+10)
```
Results are somewhat promising for a table with 10 computed columns.

**Review by vivekmenezes — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33034)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/lease_internal_test.go, line 224 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33034#-LTzAFnj-uq9RyMCp6Ig:-LTzAFnkBnPxl7CQcbyh:b-305tag) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d59d44bc4b744ee8b4de2b376b9dea0361cc34c/pkg/sql/lease_internal_test.go#L224)):*
> ```Go
> 	ts.mu.Lock()
> 	tableVersion := &tableVersionState{
> 		ImmutableTableDescriptor: *sqlbase.NewImmutableTableDescriptor(tables[0]),
> ```

Why did you need all these changes in this file?
___
*[pkg/sql/sqlbase/structured.go, line 139 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33034#-LTzCPBH6ygJp6hMjC8x:-LTzCPBI6lJwAdtfEG3C:b4dnvxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d59d44bc4b744ee8b4de2b376b9dea0361cc34c/pkg/sql/sqlbase/structured.go#L139)):*
> ```Go
> 	ReadableColumns []ColumnDescriptor
> 
> 	mu struct {
> ```

Add a comment here that this mutex is for holding values that are lazily evaluated. One might consider always evaluating a value thereby saving the cost of acquiring the lock.

**Review by eriktrinh — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33034#-:-LU13Yag0Cv4Cm4HZplM:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/lease_internal_test.go, line 224 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33034#-LTzAFnj-uq9RyMCp6Ig:-LU12dqy5ORpg-rthFlk:bt322q5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d59d44bc4b744ee8b4de2b376b9dea0361cc34c/pkg/sql/lease_internal_test.go#L224)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Why did you need all these changes in this file?
</blockquote></details>

`go vet` reports copied structs which have a lock value, so instead we just create a new table descriptor here.
___
*[pkg/sql/sqlbase/structured.go, line 139 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33034#-LTzCPBH6ygJp6hMjC8x:-LU12jyu116tgar7Ty7W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d59d44bc4b744ee8b4de2b376b9dea0361cc34c/pkg/sql/sqlbase/structured.go#L139)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Add a comment here that this mutex is for holding values that are lazily evaluated. One might consider always evaluating a value thereby saving the cost of acquiring the lock.
</blockquote></details>

Done.

**Review by vivekmenezes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33034)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/lease_internal_test.go, line 224 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33034#-LTzAFnj-uq9RyMCp6Ig:-LU15iSp3mOiEpL-MAnm:b-i7eufe) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d59d44bc4b744ee8b4de2b376b9dea0361cc34c/pkg/sql/lease_internal_test.go#L224)):*
<details><summary><i>Previously, eriktrinh (Erik Trinh) wrote…</i></summary><blockquote>

`go vet` reports copied structs which have a lock value, so instead we just create a new table descriptor here.
</blockquote></details>

hmmm, perhaps we should consider not using the lazy approach. I know you're concerned with the cost of computing this once when it's not needed, but I think in the not so distant future we are moving away from refreshing table leases and we will not be computing these so often. Also I feel we should consider making the change to distsql to get the cached descriptor when it wants an immmutable descriptor. So I think we should ditch the lazy approach and make it purely immutable.

**Pull request closed without merging**
