### PR TITLE
sql: add MVCC steps and seeks to EXPLAIN ANALYZE

### PR DESCRIPTION
**Pull request by jordanlewis**
Updates #57322. It doesn't track number of bytes scanned over, not sure how to efficiently do that.

    This commit adds 4 new fields to EXPLAIN ANALYZE for each operator that
    reads data from disk: MVCC steps and seeks, as well as MVCC "internal"
    steps and seeks when verbose mode is toggled.

    MVCC steps is the number of times that the underlying storage iterator
    stepped forward during the work to serve the operator's reads, including
    stepping over MVCC keys that were too old for user in a scan. MVCC seeks
    is the number of times that the underlying storage iterator jumped
    (seeked) to a different data location. Seeks are more expensive than
    steps.

    Comparing MVCC steps to KVs read helps indicate to a user when a scan
    might be slower than expected due to MVCC garbage in the middle of the
    keyspace being scanned. A high number of MVCC seeks might also indicate
    a lot of skipped MVCC garbage, especially when doing a sequential scan.

    Release note (sql change): EXPLAIN ANALYZE now contains more information
    about the MVCC behavior of operators that scan data from disk. See
    commit message for more details.

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64503)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/storage/pebble_mvcc_scanner.go, line 149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64503#-MZmRnbZ8bjSdj5CfTPv:-MZmRnbZ8bjSdj5CfTPw:b7kpv3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd7beb485ceb7cb4ba71d58c2ecf7f8f500c0738/pkg/storage/pebble_mvcc_scanner.go#L149)):*
> ```Go
> 	// numSeeks is the number of times that this scanner had to seek due to
> 	// exceeding its itersBeforeSeek configuration value for a given key.
> 	numSeeks uint64
> ```

Thanks for starting on this! We really need to expose more iteration stats, and this is a good start.

I'm going to nit-pick about a few things here:
- `numMVCCKeysRead` is being incremented in `iterNext` and there are many reasons that is being called, not just "read and then skip due to having too-old ...". There are a variable number of `MVCCIterator.Next` calls that happen in `iterNext`, while this is counting once per `iterNext`.
- This instrumentation for seeks is somewhat fragile since it is happening at the caller and not the callee. And `pebbleMVCCScanner` is not the only place where we incur read costs.
- The instrumentation for reverse scan is partial. The SeekLTs are being counted, but I don't see the `p.parent.Prev` calls being counted. I think this relates to the above fragility.

I would prefer a lower-level instrumentation point to which we can add more over time.
- Add `numSeeks`, `numNexts`, `numPrevs` to the existing `storage.IteratorStats`,
- Change `pebbleIterator` to track these and reset these on `Close` (even if the iterator is reusable).
- The one other real implementation of `MVCCIterator` (other than `pebbleIterator`) is `intentInterleavingIter`. It uses an `MVCCIterator` and an `EngineIterator` both of which are implemented by `pebbleIterator`. We can add the `Stats` method to the `EngineIterator` interface, and sum the two stats when returning to the caller.

**Comment by jordanlewis** [comment]
Thanks for the review! Definitely it makes sense that these basic counters are too simplistic. I think it would make sense for you or one of the storage team members to take on the task of doing the iteration stats correctly - I don't really know what is going on too well at this part of the stack. I'm happy to keep banging away on this on Fridays but realistically it will take a long time that way :)

I wonder, is there some kind of low hanging fruit that could start stats collection off on the right foot but still provide some basic metrics to the user of whether the scan was slower than expected due to MVCC garbage?

**Comment by sumeerbhola** [comment]
> I wonder, is there some kind of low hanging fruit that could start stats collection off on the right foot but still provide some basic metrics to the user of whether the scan was slower than expected due to MVCC garbage?

I added some stuff to Pebble in https://github.com/cockroachdb/pebble/pull/1129. I'll follow that up with a change to the `MVCCIterator` implementations. And then I am hoping you can rebase this PR to use those.

The way I am currently thinking about this is that if the number of seeks or steps on the `pebble.Iterator` is high compared to the number of keys returned in the MVCCScan, then the likely cause is a high number of versions (we switch from doing next to doing seek in a dynamic manner based on the number of versions we are seeing). And if the number of steps on the lower-level iterator (`internalIterator`) in Pebble is high that suggests we are encountering a lot of deletes or stale Pebble versions that have not been compacted away (this has also been a problem sometimes, in production). None of this is precise counting of the number of versions (MVCC or Pebble) but should give strong hints regarding the source of the problem when encountering slowness.

**Comment by jordanlewis** [comment]
Very awesome, thank you for turning this around in Pebble so quickly. Will be happy to rebase to use your work soon.

The heuristic you describe makes some sense to me. Perhaps we could expose these quantities as multipliers, and if the multiplier is high enough, perhaps we could emit some kind of warning.

**Review by sumeerbhola — COMMENTED** [review]
Hopefully https://github.com/cockroachdb/cockroach/blob/f5b21cf904be4a6273aefe573b70fb43f1f5ee3a/pkg/storage/engine.go#L90-L105, which just merged, can unblock you.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64503#-:-Mb89IE76QvHApnh8qAQ:b-mqjuse)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

**Review by sumeerbhola — COMMENTED** [review]
Looks good, with some minor comments, plus why the seek and step stats are all 0.
I didn't look very carefully at the plumbing.

> Reviewed 1 of 25 files at r3, 10 of 25 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64503#-:-MbdPDrl-Wz-cOqVjkyD:b-v5b9to)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/roachpb/api.go, line 1542 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64503#-MbdO6p65a97jsALxEt0:-MbdO6p65a97jsALxEt1:b-dncjz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/327fef7eadfe8ace63829646bad71c9e53c3c825/pkg/roachpb/api.go#L1542)):*
> ```Go
> // SafeFormat implements redact.SafeFormatter.
> func (s *ScanStats) SafeFormat(w redact.SafePrinter, _ rune) {
> 	w.Printf("scan stats: stepped %d times (%d internal); sought %d times (%d internal)",
> ```

seeked?
sought will be confusing I think.
___
*[pkg/sql/execinfrapb/component_stats.proto, line 134 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64503#-MbdNgVa6mHJAIml9czC:-MbdNgVb4gFMBnxYngh0:b-69yri6) ([raw file](https://github.com/cockroachdb/cockroach/blob/327fef7eadfe8ace63829646bad71c9e53c3c825/pkg/sql/execinfrapb/component_stats.proto#L134)):*
> ```protobuf
>   optional util.optional.Duration contention_time = 4 [(gogoproto.nullable) = false];
> 
>   optional util.optional.Uint num_interface_steps = 5 [(gogoproto.nullable) = false];
> ```

can we just embed `roachpb.ScanStats` here?
___
*[pkg/sql/logictest/testdata/logic_test/dist_vectorize, line 74 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64503#-MbdOh7D4GG9KG_z5wPx:-MbdOh7D4GG9KG_z5wPy:br8c7z2) ([raw file](https://github.com/cockroachdb/cockroach/blob/327fef7eadfe8ace63829646bad71c9e53c3c825/pkg/sql/logictest/testdata/logic_test/dist_vectorize#L74)):*
> ```
>       KV rows read: 5
>       KV bytes read: 40 B
>       MVCC step count: 0
> ```

do you know why these counts are 0? We must have done at least 1 seek to position the `pebble.Iterator`. Perhaps something wrong in the plumbing?

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64503)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/execinfra/stats.go, line 64 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64503#-MbgKoPB4MQL9TCLRZO9:-MbgKoPB4MQL9TCLRZOA:bktp4fl) ([raw file](https://github.com/cockroachdb/cockroach/blob/327fef7eadfe8ace63829646bad71c9e53c3c825/pkg/sql/execinfra/stats.go#L64)):*
> ```Go
> 
> // PopulateKVStats adds data from the input ScanStats to the input KVStats.
> func PopulateKVStats(kvStats *execinfrapb.KVStats, ss *ScanStats) {
> ```

nit: perhaps 'PopulateKVScanStats' or 'PopulateKVMVCCStats' ? 
___
*[pkg/sql/execinfrapb/component_stats.go, line 325 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64503#-MbgPEKB3oO_OR_XRt3b:-MbgPEKB3oO_OR_XRt3c:b-x2s3v1) ([raw file](https://github.com/cockroachdb/cockroach/blob/327fef7eadfe8ace63829646bad71c9e53c3c825/pkg/sql/execinfrapb/component_stats.go#L325)):*
> ```Go
> 	timeVal(&s.KV.KVTime)
> 	timeVal(&s.KV.ContentionTime)
> 	resetUint(&s.KV.StepCount)
> ```

Are these stats something non-deterministic? If so, perhaps we should override it with a useful value like what we do with `s.KV.BytesRead`
___
*[pkg/sql/row/kv_fetcher.go, line 143 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64503#-MbgNETD4oHjmnins7K0:-MbgNETD4oHjmnins7K1:bax0uls) ([raw file](https://github.com/cockroachdb/cockroach/blob/327fef7eadfe8ace63829646bad71c9e53c3c825/pkg/sql/row/kv_fetcher.go#L143)):*
> ```Go
> 		f.newSpan = true
> 		nBytes := len(f.batchResponse)
> 		for i := range f.kvs {
> ```

Hmm, is this change related to tracking MVCC stats? Or it's a bug fix to our accoutning for `bytesRead` ?

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64503)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jordanlewis, and @sumeerbhola)

___
*[pkg/sql/logictest/testdata/logic_test/dist_vectorize, line 74 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64503#-MbdOh7D4GG9KG_z5wPx:-Mbfoqfx5KG2rmi6NAxW:bc4xtpo) ([raw file](https://github.com/cockroachdb/cockroach/blob/327fef7eadfe8ace63829646bad71c9e53c3c825/pkg/sql/logictest/testdata/logic_test/dist_vectorize#L74)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

do you know why these counts are 0? We must have done at least 1 seek to position the `pebble.Iterator`. Perhaps something wrong in the plumbing? 
</blockquote></details>

We set values like this to 0 in test output because it's nondeterministic when run in a logic test.
___
*[pkg/sql/row/kv_fetcher.go, line 143 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64503#-MbgNETD4oHjmnins7K0:-MbwQ0gP23B4BL1Z0VvR:b-ypsthq) ([raw file](https://github.com/cockroachdb/cockroach/blob/327fef7eadfe8ace63829646bad71c9e53c3c825/pkg/sql/row/kv_fetcher.go#L143)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm, is this change related to tracking MVCC stats? Or it's a bug fix to our accoutning for `bytesRead` ?
</blockquote></details>

It was just a small improvement to the way we were tracking bytesRead. I think it's a small bugfix too, but most of the time we don't use the old kvs format so things were right before.

**Review by jordanlewis — COMMENTED** [review]
> Dismissed @sumeerbhola from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64503)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @sumeerbhola)

___
*[pkg/roachpb/api.go, line 1542 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64503#-MbdO6p65a97jsALxEt0:-MbwXWw-8Y3R2mmJ-APE:b-2ac5l5) ([raw file](https://github.com/cockroachdb/cockroach/blob/327fef7eadfe8ace63829646bad71c9e53c3c825/pkg/roachpb/api.go#L1542)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

seeked?
sought will be confusing I think.
</blockquote></details>

Done. Yeah this was sort of silly.
___
*[pkg/sql/execinfra/stats.go, line 64 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64503#-MbgKoPB4MQL9TCLRZO9:-MbwYKVkC33cbDKh01AK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/327fef7eadfe8ace63829646bad71c9e53c3c825/pkg/sql/execinfra/stats.go#L64)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: perhaps 'PopulateKVScanStats' or 'PopulateKVMVCCStats' ? 
</blockquote></details>

Done.
___
*[pkg/sql/execinfrapb/component_stats.go, line 325 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64503#-MbgPEKB3oO_OR_XRt3b:-MbwXsq53o75ZYoM9Kmk:bog3p4z) ([raw file](https://github.com/cockroachdb/cockroach/blob/327fef7eadfe8ace63829646bad71c9e53c3c825/pkg/sql/execinfrapb/component_stats.go#L325)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Are these stats something non-deterministic? If so, perhaps we should override it with a useful value like what we do with `s.KV.BytesRead`
</blockquote></details>

Yes, these are non-deterministic in logic tests. Not sure what useful value we'd have here.
___
*[pkg/sql/execinfrapb/component_stats.proto, line 134 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64503#-MbdNgVa6mHJAIml9czC:-MbwXYt55W4uTm0gG2C8:bysc7lj) ([raw file](https://github.com/cockroachdb/cockroach/blob/327fef7eadfe8ace63829646bad71c9e53c3c825/pkg/sql/execinfrapb/component_stats.proto#L134)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can we just embed `roachpb.ScanStats` here?
</blockquote></details>

Unfortunately we can't, assuming we want to follow the pattern in this file, because the roachpb.ScanStats use ordinary primitive uint32s, whereas things in this protobuf use this util.optional.Uint thing which as I understand gets around the inability to distinguish 0 from not-present in protobuf otherwise.

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 1 of 26 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64503)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jordanlewis, and @sumeerbhola)

___
*[pkg/sql/logictest/testdata/logic_test/dist_vectorize, line 74 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64503#-MbdOh7D4GG9KG_z5wPx:-McA0_wDE3iwdsnlFSUa:byieycj) ([raw file](https://github.com/cockroachdb/cockroach/blob/327fef7eadfe8ace63829646bad71c9e53c3c825/pkg/sql/logictest/testdata/logic_test/dist_vectorize#L74)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

We set values like this to 0 in test output because it's nondeterministic when run in a logic test.
</blockquote></details>

Is there any test that validates that the end-to-end plumbing is working ok? If not, I think it is worth having one test.
And was there a particular count you were seeing the non-determinism in? I would expect that a single node setup with a simple table with a single version for each key should be deterministic for these counts -- these are not really affected by the shape of the LSM since they are generated by operations in the top-level iterator which does not see the details of the underlying merging iterator.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64503)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @sumeerbhola)

___
*[pkg/sql/logictest/testdata/logic_test/dist_vectorize, line 74 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64503#-MbdOh7D4GG9KG_z5wPx:-MeCOQpq7bMjstqGyh2y:bqhdmyf) ([raw file](https://github.com/cockroachdb/cockroach/blob/327fef7eadfe8ace63829646bad71c9e53c3c825/pkg/sql/logictest/testdata/logic_test/dist_vectorize#L74)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is there any test that validates that the end-to-end plumbing is working ok? If not, I think it is worth having one test.
And was there a particular count you were seeing the non-determinism in? I would expect that a single node setup with a simple table with a single version for each key should be deterministic for these counts -- these are not really affected by the shape of the LSM since they are generated by operations in the top-level iterator which does not see the details of the underlying merging iterator.
</blockquote></details>

Yeah, I've added a test.

The non-determinism comes into play because these tests are run on several different configurations of distribution. Agreed, on a fixed cluster type there should be no nondeterminism.

**Review by jordanlewis — COMMENTED** [review]
@sumeerbhola there is some pretty weird behavior in the test that I added. It seems to be flaky, but I would not expect it to be flaky.

Sometimes, it claims that there were 1000 steps and 2 seeks (for a scan over a 1000-row table that was just inserted).

But sometimes, for the same test setup, it claims there were 1000 steps and 1000 seeks. This seems wrong... but not sure where the wrongness is coming from just yet. Any thoughts?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64503#-:-MeC_2UdBBJTDs9hzDtu:b-z9c9wn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @sumeerbhola)

**Review by sumeerbhola — COMMENTED** [review]
Is this the `UPDATE ab SET b=b+1 WHERE true`?
I am assuming this is being executed using a single ScanRequest followed by a BatchRequest with a 1000 PutRequests.
And the stats are only coming from the ScanRequest, since there isn't any plumbing in mvcc.go for the PutRequests (can you add a TODO somewhere in mvcc.go that we should rectify such gaps since the PutRequests are going to do as much iterator work).

The 1000 seeks suggests that it is the `kvBatchSize` logic that is setting a limit of 1 row on the ScanRequest, and repeating it. Can you try after overriding it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64503#-:-MePU6aN2iZhmDPYr7j1:bvg24bv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @sumeerbhola)

**Review by jordanlewis — COMMENTED** [review]
Actually, the test case is looking at the `SELECT` after the `UPDATE`. The `UPDATE` is not checked, and I agree it would be a little more complex to understand what it's doing.

That being said, the flakiness was caused by the metamorphic KV batch size setting, so I've disabled this test under the metamorphic configuration and it should be ready to go.

PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64503#-:-MekobPqEdaj5sCy8g8Z:bqcva23)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @sumeerbhola)

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 26 files at r5, 1 of 27 files at r7, 1 of 27 files at r9, 23 of 26 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64503#-:-MekxNghApinLLie68ZN:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng and @sumeerbhola)

**Comment by jordanlewis** [comment]
Thanks for the reviews!

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64503)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @RaduBerinde, and @sumeerbhola)

___
*[pkg/sql/explain_test.go, line 345 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/64503#-MezEsMN9lJDtvpuzDKo:-MezEsMN9lJDtvpuzDKp:by4ynbj) ([raw file](https://github.com/cockroachdb/cockroach/blob/14e3e40f8632c06dbc67a9233faabd30becea9d9/pkg/sql/explain_test.go#L345)):*
> ```Go
> 	foundSteps, foundSeeks := getMVCCStats(t, r)
> 
> 	assert.Equal(t, expectedSteps, foundSteps)
> ```

Seems like we are having a mix of `assert.Equal()` vs `require.Equal()` in our testing code, is there a preference for one over another?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64503)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/rowexec/joinreader.go, line 886 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/64503#-MjUK8K19rzOCZnGGRJc:-MjUK8K19rzOCZnGGRJd:bbqahrx) ([raw file](https://github.com/cockroachdb/cockroach/blob/77d424a01c9157ffa541cdfb5e772175be54c776/pkg/sql/rowexec/joinreader.go#L886)):*
> ```Go
> 
> func (jr *joinReader) close() {
> 	// Make sure to clone any tracing span so that stats can pick it up later.
> ```

I don't understand why we're fetching the scan stats in different places in the row-by-row processors - I would expect for all four disk-reading processors we would have exactly the same new logic, why is this not the case?

**Pull request merged**
