### PR TITLE
add licensing info to README

### LINKED ISSUE #7441: acceptance/examples: update nodejs example to use latest driver version's suggestion connection methods
Current nodjs examples and acceptance tests use `pg.connect` which the latest release of the `pg` node driver say will be deprecated: https://github.com/brianc/node-postgres/blob/master/CHANGELOG.md#v600

We should also probably be careful to specify driver versions we tested with on these.

### LINKED ISSUE #7441: License summary in main repo README.md
We should have a clear summary of our licenses in the main repo's README.md. See cockroachdb/cockroach#49615 for an external contributor's take on this. It's a good start, but I think it needs some work to clarify that each release is under two licenses (not three) and emphasize the current state instead of starting with the old 19.1 releases. (The main audience for the github readme is potential contributors who need to understand the license terms for the repo they're contributing to).

### PR DESCRIPTION
**Pull request by gemma-shay**
Added a section on licensing info.
Links to the new Licensing doc (#9338) will not work yet, so will wait to merge until they are up.
Closes https://github.com/cockroachdb/docs/issues/7441

### CODE REVIEW

**Review by bdarnell — COMMENTED** [review]
I worry that this is just enough information to be confusing - maybe we should just say that the software is licensed under a combination of the BSL and CCL and link out to the full docs for more details?

If we do want more of a summary here I think it's important to emphasize that there are basically two paths: core/free and enterprise. Both editions use a combination of BSL and CCL (the third option, BSL-only, should be discussed only in relation to what happens when the BSL converts to APL)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59490#-:-MS4ab3CB_130X9QtT0Z:b-p75n1w)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @piyush-singh)

___
*[README.md, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59490#-MS4ZlxhBn_oN6eLWRC4:-MS4ZlxhBn_oN6eLWRC5:b8l1asb) ([raw file](https://github.com/cockroachdb/cockroach/blob/767419b488a1122290e8900d16a973320d31fd05/README.md#L115)):*
> ```Markdown
> - [Cockroach Community License (Paid)](https://www.cockroachlabs.com/docs/stable/licensing.html#ccl-paid)
> 
> Core features released up to and including version 19.1 are licensed under [Apache 2.0](https://www.cockroachlabs.com/docs/stable/licensing.html#apache). After version 19.1, core features are licensed under the BSL for three years before converting to the Apache 2.0 license.
> ```

Maybe say "Beginning with version 19.2" instead of "After 19.1"?

The second sentence uses "core features" without defining it. 
___
*[README.md, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59490#-MS4ZuxR2xmaUB66Jn7p:-MS4ZuxR2xmaUB66Jn7q:b-z7k7ro) ([raw file](https://github.com/cockroachdb/cockroach/blob/767419b488a1122290e8900d16a973320d31fd05/README.md#L117)):*
> ```Markdown
> Core features released up to and including version 19.1 are licensed under [Apache 2.0](https://www.cockroachlabs.com/docs/stable/licensing.html#apache). After version 19.1, core features are licensed under the BSL for three years before converting to the Apache 2.0 license.
> 
> BSL features are free to use and the source code is available, but users may not use CockroachDB as a service without an agreement with Cockroach Labs. Outside of this usage, BSL features will continue to be free to use and source code will continue to be available.
> ```

Be more specific about what's not allowed: "but users may not offer CockroachDB as a commercial database service without an agreement..." The second sentence seems redundant to me.

**Review by bdarnell — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59490)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @piyush-singh)

**Review by piyush-singh — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59490)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

**Comment by lnhsingh** [comment]
bors r=bdarnell

**Comment by gemma-shay** [comment]
bors r=bdarnell

**Comment by lnhsingh** [comment]
bors r=bdarnell

**Pull request merged**
