### PR TITLE
Admin APIs for databases

### PR DESCRIPTION
**Pull request by cuongdo**
Implemented two API endpoints for the admin UI:
1. databases - lists databases
2. databases/<DATABASE> - shows grants and tables for a database

This is a starting point to collect feedback. The rest of the endpoints
should be simple once I incorporate feedback on these initial endpoints. 

cc @maxlang

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4582)

### CODE REVIEW

**Comment by petermattis** [comment]
LGTM, though you should let others chime in before merging.

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/admin.go, line 69 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBA3Ui_hq3afHdRs1l-:-KBA3UiabTX_IXSKbOVU:228278542) ([raw file](https://github.com/cockroachdb/cockroach/blob/60677cfb80e8f7babdd117abbe514e8a29e526e5/server/admin.go#L69)):*
Should we be versioning the `statusEndpoint` as well? Wondering what the distinction is between `adminEndpoint` and `statusEndpoint`. Certainly seems the `/databases/` endpoints could leave under `/_status/databases`. 

---

*[server/admin.go, line 167 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBA1wPYyweWGwtBwPW9:-KBA1wPYyweWGwtBwPWA:590800696) ([raw file](https://github.com/cockroachdb/cockroach/blob/60677cfb80e8f7babdd117abbe514e8a29e526e5/server/admin.go#L167)):*
A single element struct would work as well:

```
result := &struct{Databases interface{}}{databases}
```

Though having written that I might prefer the `map`. 

---

*[server/admin.go, line 207 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBA2MrTThU83KX1uxQP:-KBA2MrTThU83KX1uxQQ:-1649075842) ([raw file](https://github.com/cockroachdb/cockroach/blob/60677cfb80e8f7babdd117abbe514e8a29e526e5/server/admin.go#L207)):*
`s/handleDatabase/handleDatabaseDetails/g`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-:-KBA3ufwSWhDkFHlM4wv:-198084921)*

**Comment by bdarnell** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[server/admin.go, line 144 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBAOMg0jlfWt_82T69K:-KBAOMg0jlfWt_82T69L:72144417) ([raw file](https://github.com/cockroachdb/cockroach/blob/60677cfb80e8f7babdd117abbe514e8a29e526e5/server/admin.go#L144)):*
Instead of hard-coding "root" this should use some function to extract a user from the `http.Request` (even if it's just a placeholder for now that hard-codes "root", this will give us one place to change in the future).

---

*[server/admin.go, line 213 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBAOoH3pHiugDjQ26J2:-KBAOoH3pHiugDjQ26J3:-161737212) ([raw file](https://github.com/cockroachdb/cockroach/blob/60677cfb80e8f7babdd117abbe514e8a29e526e5/server/admin.go#L213)):*
This is a trivial SQL injection. We must *always* use placeholders for queries derived from user input. 

---

*[server/admin.go, line 222 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBAPUCvGsZ8oI8isIdb:-KBAPUCvGsZ8oI8isIdc:665166329) ([raw file](https://github.com/cockroachdb/cockroach/blob/60677cfb80e8f7babdd117abbe514e8a29e526e5/server/admin.go#L222)):*
It's unfortunate that we do string matching on the error here. Not for this PR but there should probably be a better structured way of passing this error up.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582)*

**Comment by maxlang** [comment]
LGTM on my end

**Comment by cuongdo** [comment]
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[server/admin.go, line 69 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBA3Ui_hq3afHdRs1l-:-KBAjR5R3dJgpApEWEJR:1065939817) ([raw file](https://github.com/cockroachdb/cockroach/blob/60677cfb80e8f7babdd117abbe514e8a29e526e5/server/admin.go#L69)):*
OK, I'm versioning everything now and have moved everything in `server/admin.go` to `/_admin/v1/*`

---

*[server/admin.go, line 144 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBAOMg0jlfWt_82T69K:-KBAk3dG4TDqmC6JF7MF:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/60677cfb80e8f7babdd117abbe514e8a29e526e5/server/admin.go#L144)):*
Done.

---

*[server/admin.go, line 167 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBA1wPYyweWGwtBwPW9:-KBAkCUqayBaoiibQ42r:321011379) ([raw file](https://github.com/cockroachdb/cockroach/blob/60677cfb80e8f7babdd117abbe514e8a29e526e5/server/admin.go#L167)):*
I think it's more readable as a `map`.

---

*[server/admin.go, line 207 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBA2MrTThU83KX1uxQP:-KBAkLxilK9jpB7dHz6M:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/60677cfb80e8f7babdd117abbe514e8a29e526e5/server/admin.go#L207)):*
Done.

---

*[server/admin.go, line 213 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBAOoH3pHiugDjQ26J2:-KBAnv1-chY37JlmX6-4:-495246544) ([raw file](https://github.com/cockroachdb/cockroach/blob/60677cfb80e8f7babdd117abbe514e8a29e526e5/server/admin.go#L213)):*
Yeah, this is a bad security hole. How should I fix it? I tried using a bind variable, but the SQL grammar doesn't seem to support bind variables like I need (`SHOW GRANTS ON DATABASE $1`). Should I modify the grammar? Or is there another SQL escaping function or placeholder mechanism I can use?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582)*

**Comment by cuongdo** [comment]
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[server/admin.go, line 222 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBAPUCvGsZ8oI8isIdb:-KBAwhBbo_jvI3CBRG13:-1530771663) ([raw file](https://github.com/cockroachdb/cockroach/blob/60677cfb80e8f7babdd117abbe514e8a29e526e5/server/admin.go#L222)):*
Agreed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582)*

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/admin.go, line 213 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBAOoH3pHiugDjQ26J2:-KBB28CzUyemvKPQPEor:-1765258397) ([raw file](https://github.com/cockroachdb/cockroach/blob/60677cfb80e8f7babdd117abbe514e8a29e526e5/server/admin.go#L213)):*
I haven't double-checked this, but I think you can use `sql.parser.Name`: 

```
query := fmt.Sprintf("SHOW GRANTS ON DATABASE %s; SHOW TABLES FROM %s;", sql.Parser.Name(dbname), sql.Parser.Name(dbname))

```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582)*

**Comment by cuongdo** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/admin.go, line 213 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBAOoH3pHiugDjQ26J2:-KBDhkbCwwCsPjhaawg9:-231601466) ([raw file](https://github.com/cockroachdb/cockroach/blob/60677cfb80e8f7babdd117abbe514e8a29e526e5/server/admin.go#L213)):*
Yes, I've verified that this does work. I've added a test for SQL injection as well.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582)*

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[server/admin.go, line 221 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBDn4m6JejwQPcgek8U:-KBDn4m6JejwQPcgek8V:-338583344) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba517dbe1a2cd6c9cf8c4d818ab7c9f6c8eff23/server/admin.go#L221)):*
That's a mouthful of lowercase. Perhaps `escDBName`.

---

*[server/admin_test.go, line 233 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBDoNhokCNUlqHUUbrm:-KBDoNhokCNUlqHUUbrn:1033280542) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba517dbe1a2cd6c9cf8c4d818ab7c9f6c8eff23/server/admin_test.go#L233)):*
The invalid database will be in the error message, right? I think you should check for that.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582)*

**Comment by bdarnell** [comment]
LGTM. I filed #4597 for a better fix to the sql injection problem.

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-:-KBDxFhuJIEcatt1lGVV:424135825)*

**Comment by tamird** [comment]
Reviewed 2 of 4 files at r1, 2 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[server/admin.go, line 43 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBAai05SXSNFJ-E3mkL:-KBAai05SXSNFJ-E3mkM:-623882598) ([raw file](https://github.com/cockroachdb/cockroach/blob/60677cfb80e8f7babdd117abbe514e8a29e526e5/server/admin.go#L43)):*
should be above the cockroachdb group of imports

---

*[server/admin.go, line 146 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBECajDw-u4PU_CGc8e:-KBECajFpGoLUZiR01qW:-298148746) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba517dbe1a2cd6c9cf8c4d818ab7c9f6c8eff23/server/admin.go#L146)):*
security.RootUser

---

*[server/admin.go, line 153 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBED5sEphmQtVHxkk_A:-KBED5sEphmQtVHxkk_B:-1900935460) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba517dbe1a2cd6c9cf8c4d818ab7c9f6c8eff23/server/admin.go#L153)):*
there are some implicit assumptions here about the shape of the result (one row, one column). could you make them explicit, and return errors if they don't hold?

---

*[server/admin.go, line 190 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBEDG7mSsocw3KUX9OY:-KBEDG7mSsocw3KUX9OZ:-1325740125) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba517dbe1a2cd6c9cf8c4d818ab7c9f6c8eff23/server/admin.go#L190)):*
I didn't expect this behaviour from the method name.

---

*[server/admin.go, line 204 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBEEAVjxsrIc2wm2mtN:-KBEEAVjxsrIc2wm2mtO:5173157) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba517dbe1a2cd6c9cf8c4d818ab7c9f6c8eff23/server/admin.go#L204)):*
??

---

*[server/admin.go, line 222 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBEEEVegKZxst4Eymxf:-KBEEEVegKZxst4Eymxg:-423147546) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba517dbe1a2cd6c9cf8c4d818ab7c9f6c8eff23/server/admin.go#L222)):*
add a TODO that this should use placeholders

---

*[server/admin.go, line 223 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBEEGF2l9Ua_3XgR-BC:-KBEEGF2l9Ua_3XgR-BD:-298148746) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba517dbe1a2cd6c9cf8c4d818ab7c9f6c8eff23/server/admin.go#L223)):*
security.RootUser

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582)*

**Comment by cuongdo** [comment]
Review status: 3 of 6 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[server/admin.go, line 43 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBAai05SXSNFJ-E3mkL:-KBER63RBB-H33pwTk0I:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/60677cfb80e8f7babdd117abbe514e8a29e526e5/server/admin.go#L43)):*
Done.

---

*[server/admin.go, line 146 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBECajDw-u4PU_CGc8e:-KBERK65SA4m6YjVyZ1q:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba517dbe1a2cd6c9cf8c4d818ab7c9f6c8eff23/server/admin.go#L146)):*
Done.

---

*[server/admin.go, line 153 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBED5sEphmQtVHxkk_A:-KBEWaT15Ndg49T4x3Ii:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba517dbe1a2cd6c9cf8c4d818ab7c9f6c8eff23/server/admin.go#L153)):*
Done.

---

*[server/admin.go, line 190 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBEDG7mSsocw3KUX9OY:-KBESHKAkTtzFXK_6bLU:-2015246091) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba517dbe1a2cd6c9cf8c4d818ab7c9f6c8eff23/server/admin.go#L190)):*
renamed to `firstColumnToSlice`

---

*[server/admin.go, line 204 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBEEAVjxsrIc2wm2mtN:-KBEWe_8GAwL-0G_XIl6:-1728642076) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba517dbe1a2cd6c9cf8c4d818ab7c9f6c8eff23/server/admin.go#L204)):*
forgot remove remove this. done.

---

*[server/admin.go, line 221 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBDn4m6JejwQPcgek8U:-KBEX573ZcmRPNCrTKNF:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba517dbe1a2cd6c9cf8c4d818ab7c9f6c8eff23/server/admin.go#L221)):*
Done.

---

*[server/admin.go, line 222 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBEEEVegKZxst4Eymxf:-KBEXKvdVturzvwygEnG:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba517dbe1a2cd6c9cf8c4d818ab7c9f6c8eff23/server/admin.go#L222)):*
Done.

---

*[server/admin.go, line 223 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBEEGF2l9Ua_3XgR-BC:-KBEXPIshkL0HALko49m:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba517dbe1a2cd6c9cf8c4d818ab7c9f6c8eff23/server/admin.go#L223)):*
Done.

---

*[server/admin_test.go, line 233 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBDoNhokCNUlqHUUbrm:-KBE_OZYDjZonYw9-CT6:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba517dbe1a2cd6c9cf8c4d818ab7c9f6c8eff23/server/admin_test.go#L233)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/admin.go, line 166 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBEbCA74eJmxObjIGt4:-KBEbCA8dXL6yxVkMKsH:1738883586) ([raw file](https://github.com/cockroachdb/cockroach/blob/58e663719ba41a8770cd3f0da124b0d971d35294/server/admin.go#L166)):*
this needs to come after the length checks below.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582)*

**Comment by cuongdo** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/admin.go, line 166 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBEbCA74eJmxObjIGt4:-KBEcGP7nkP27Dr-ZHU-:116984301) ([raw file](https://github.com/cockroachdb/cockroach/blob/58e663719ba41a8770cd3f0da124b0d971d35294/server/admin.go#L166)):*
Moved to below the `len(resp.Results)` check. I still want it above the check on the length of `resp.Results[0].Columns`, because the reason that we aren't getting the number of columns we expect could be a SQL error. In that case, getting the SQL error back is more useful than getting back a column # mismatch error.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/admin.go, line 166 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582#-KBEbCA74eJmxObjIGt4:-KBEd-gAhourzoyPFcr5:-1795627047) ([raw file](https://github.com/cockroachdb/cockroach/blob/58e663719ba41a8770cd3f0da124b0d971d35294/server/admin.go#L166)):*
Yeah, that's fine. The way you had it before could cause an out of bounds panic.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4582)*

**Comment by tamird** [comment]
Something of a late afterthought: how do you feel about having protobuf service definitions for these? that'd allow us to support grpc, protobuf-on-http, and JSON using something like https://github.com/gengo/grpc-gateway.

**Comment by cuongdo** [comment]
I'm giving it a quick trial run to see how much work `grpc-gateway` is to
integrate.

**Comment by tamird** [comment]
Nice!

**Pull request merged**
