### PR TITLE
sql,opt: enrich the reported errors, avoid "naked" panics

### PR DESCRIPTION
**Pull request by knz**
First commit from  #35704.
Informs https://github.com/cockroachlabs/registration/issues/203.

The `optbuilder` package's error handling was deficient in two ways:

- it would fail assertions with a hard panic and cause a node
  shutdown;
- it did not enrich errors with a suitable pg error code in many
  cases, including missing references to issues that track
  unimplemented features.

This patch fixes the former by introducing a new primitive
`assertionErrorf` that creates a pgerror with CodeInternalError (this
is picked up in telemetry automatically).

It fixes the latter by adding the missing error codes.  Where
applicable, errors have been either picked from the HP code, or from
PostgreSQL. In the latter cases the code was also backported to the HP
for consistency.

Additionally, a linter is added to prevent the addition of new
undecorated panics.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

Very nice, thank you! I plan to do something similar for `execbuilder` assertions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35714#-:-L_t_S-z2wOMCS3jTrpg:biefzj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @RaduBerinde)

**Comment by knz** [comment]
TFYR!

bors r+

**Review by andy-kimball — COMMENTED** [review]
Thanks for making this change; it was needed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35714#-:-L_vmgr4C0MdGw4iE7Yc:b-8sh8h4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @knz)

___
*[pkg/sql/opt/optbuilder/builder.go, line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35714#-L_vmYAb8-r__Hx1nTQz:-L_vmYAc0mFmgtJQMKrI:b-ojvst0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f58263efebc6679b31ae979877cfa45575609df4/pkg/sql/opt/optbuilder/builder.go#L171)):*
> ```Go
> // assertionErrorf formats an internal error (or assertion failure)
> // using a pgerror object, so that it can be picked up by telemetry.
> func assertionErrorf(format string, args ...interface{}) builderError {
> ```

After this change, do we still get call stacks printed in the console when we have a panic bug in optbuilder?

**Comment by knz** [comment]
> After this change, do we still get call stacks printed in the console when we have a panic bug in optbuilder?

There's currently a small trace (3 levels deep) captured. I'm sending out a PR today to add more.

**Comment by RaduBerinde** [comment]
I was doing the same in execbuilder but I don't see any trace.
```
        --- FAIL: TestExecBuild/5node-dist-opt/lookup_join (1.59s)
            logic.go:2329: 
                
                testdata/lookup_join:170: EXPLAIN (VERBOSE) SELECT DISTINCT b1.title FROM books as b1 JOIN books2 as b2 ON b1.title = b2.title WHERE b1.shelf <> b2.shelf
                expected success, but found
                pq: internal error: lol
            logic.go:2313: 
                 pq: internal error: lol
            logic.go:2345: 
                testdata/lookup_join:187: error while processing
            logic.go:2346: testdata/lookup_join:187: too many errors encountered, skipping the rest of the input
```

**Comment by knz** [comment]
> I was doing the same in execbuilder but I don't see any trace.

The trace is in the "InternalCommand" field. Not sure the code in logic.go reveals it.

**Comment by RaduBerinde** [comment]
Would something break if we made `Error()` show the Detail or InternalCommand as well?

**Comment by knz** [comment]
> Would something break if we made Error() show the Detail or InternalCommand as well?

Yes, several things would break. It's not super catastrophic, just unpleasant to fix up everywhere that needs fixing.

Anyway I'm going to enhance this thing today. I'm just going to make `pgerror` implement the same as `errors.withStack` so we can get nice stack traces.

**Comment by andy-kimball** [comment]
One other question: once we've switched to errors instead of panics, will SQLSmith still report the bugs it finds? Will this change mask issues it would otherwise find?

**Comment by jordanlewis** [comment]
SQLSmith still reports errors that aren't panics, but they're slightly harder to see in the logs.

**Comment by knz** [comment]
> One other question: once we've switched to errors instead of panics, will SQLSmith still report the bugs it finds? Will this change mask issues it would otherwise find?

I will make sure that internal errors are turned into panics when encountered during tests (like we do in log.ReportPanic already)

**Pull request merged**
