### PR TITLE
    sql: support for temporary table clean up for tenants

### LINKED ISSUE #67401: sql: session-scoped temporary objects do not work with tenant clusters
Repro:
```
export COCKROACH=./cockroach

# Create certificates.
export CERTSDIR=$HOME/.cockroach-certs
export COCKROACH_CA_KEY=$CERTSDIR/ca.key
$COCKROACH cert create-ca
$COCKROACH cert create-client root
$COCKROACH cert create-node 127.0.0.1 localhost
$COCKROACH mt cert create-tenant-client 123 --certs-dir=${HOME}/.cockroach-certs

# Start KV process.
$COCKROACH start-single-node --host 127.0.0.1

# Create tenant
$COCKROACH sql --host 127.0.0.1 -e 'select crdb_internal.create_tenant(123);'

# Start SQL tenant process.
COCKROACH_TRUST_CLIENT_PROVIDED_SQL_REMOTE_ADDR=true $COCKROACH mt start-sql --tenant-id 123 --kv-addrs 127.0.0.1:26257 --http-addr 127.0.0.1:8081 --sql-addr 127.0.0.1:36257
```

Notice that already there's a warning in the log, despite not having created any temporary objects:
```
W210709 00:19:08.472581 195 sql/temporary_schema.go:601  [-] 2  failed to clean temp objects: isMeta1Leaseholder is not available to secondary tenants
```

Now create a temporary table in the SQL CLI:
```
$COCKROACH sql --port 36257

SET experimental_enable_temp_tables = 'on';
CREATE TEMP TABLE t (x INT PRIMARY KEY, y INT);
```

While still in the CLI, kill the SQL tenant process with ctrl-C. Then start it up again. Back in the SQL CLI:
```
SHOW TABLES;
```

EXPECTED: The temp table should be gone, since it was tied to the previous session, which got terminated.
ACTUAL: The temp table is still showing:
```
root@:36257/defaultdb> show tables;
             schema_name            | table_name | type  | owner | estimated_row_count | locality
------------------------------------+------------+-------+-------+---------------------+-----------
  pg_temp_1625790426654356000_10001 | t          | table | root  |                   0 | NULL
```

Even if we decide not to fix this right now, we need to at least disable temporary object creation in tenant clusters and stop spamming the logs (logs are filled with the warning message even when temp objects are not ever used). That change needs to be back-ported to 21.1.x.

Also, here's @ajwerner's commentary from Slack:
> Oh, that’s not good. Interesting that it’s new.
> This needs some tracking. Seems like we didn’t think through temporary objects on tenants.
> If a node crashes or is shut down with an open session that created temporary objects, nothing will ever clean them up.
> There’s different levels of solutions. I think what I’d do is just get rid of the leasing component. It’s idemponent work. That being said, the code also makes RPCs to the other instances to find out which sessions are live which is also busted on tenants.
> We’re working on the sessions listing stuff (I think). At that point, it’s just about deciding whether we care about the leasing. For that I think there are two simple solutions:
> No leasing, just jitter a long loop
> Use the fact that you have the lowest instance ID you know about like being the leaseholder of meta1.
> All in all, it is non-trivial, but it is small.

### PR DESCRIPTION
**Pull request by fqazi**
Fixes: #67401
Previously, the temporary table clean-up did not execute for
tenants. This was inadequate that temporary tables would last
longer than the life span of user sessions. To address this,
this patch adds support for cleaning up on a single tenant
pod. Specifically removing checks for meta1 lease when under
a tenant, and support for listing sessions.

Release justification: low risk and fixes a tenant-related bug
Release note (bug fix): Temporary tables were not properly cleaned up for
tenants.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
I'd like to see some testing of this in a tenant where we forcibly shut down a tenant pod and then see a new tenant pod run cleanup. It'd be nice on the second commit to exercise the RPCs. 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69486#-:-MiKQEfB8ZrNj6fOMYVN:bq7jvs3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[pkg/server/tenant.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69486#-MiKPHvp4u1-uRw0rjK_:-MiKPHvp4u1-uRw0rjKa:bvzy7ea) ([raw file](https://github.com/cockroachdb/cockroach/blob/40fe8843660bec07f5ec5db09ac487d099a9f687/pkg/server/tenant.go#L142)):*
> ```
> 	args.sqlStatusServer = tenantStatusServer
> 	s, err := newSQLServer(ctx, args)
> 	tenantStatusServer.sqlServer = s
> ```
this circularity deserves some commentary.
___
*[pkg/server/tenant.go, line 135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69486#-MiKQcyv6TKdqrJWS7RB:-MiKQcyv6TKdqrJWS7RC:b-6qq91d) ([raw file](https://github.com/cockroachdb/cockroach/blob/a20ad3f5aa61f93400b2cf025883e13d72b568ef/pkg/server/tenant.go#L135)):*
> ```Go
> 	httpLAddr := httpL.Addr().String()
> 	args.advertiseAddr = baseCfg.AdvertiseAddr
> 	tenantStatusServer := newTenantStatusServer(
> ```

maybe construction of this status server should somehow be pushed down into the construction of the sql server?  I'm not actually sure. How do we do this for the system tenent?
___
*[pkg/server/tenant.go, line 142 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69486#-MiKQr5aAtSe6in71q9Z:-MiKQr5aAtSe6in71q9_:b-svck4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a20ad3f5aa61f93400b2cf025883e13d72b568ef/pkg/server/tenant.go#L142)):*
> ```Go
> 	args.sqlStatusServer = tenantStatusServer
> 	s, err := newSQLServer(ctx, args)
> 	tenantStatusServer.sqlServer = s
> ```

does this change belong in the second commit rather than the first one? I think we want to backport only the first one. 
___
*[pkg/server/tenant_status.go, line 121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69486#-MiKPwM74kGuaBxBmBNI:-MiKPwM74kGuaBxBmBNJ:b7maei7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a20ad3f5aa61f93400b2cf025883e13d72b568ef/pkg/server/tenant_status.go#L121)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
> 	dialFn := func(ctx context.Context, instanceID base.SQLInstanceID, addr string) (interface{}, error) {
> 		client, err := t.dialPod(ctx, instanceID, addr)
> 		return client, err
> 	}
> 	nodeStatement := func(ctx context.Context, client interface{}, _ base.SQLInstanceID) (interface{}, error) {
> 		statusClient := client.(serverpb.StatusClient)
> 		return statusClient.ListLocalSessions(ctx, req)
> 	}
> ```
</details>

in both of these cases can you do the more verbose nil checking? The reasons is that both of these methods return structs. A real gotcha in go is if you return a nil struct type from a function that returns an interface type, the return value won't be nil. This can cause subtle bugs. We should probably lint against it.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69486)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/server/tenant.go, line 135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69486#-MiKQcyv6TKdqrJWS7RB:-MiMpJZB1clEPajECFxg:b-877ave) ([raw file](https://github.com/cockroachdb/cockroach/blob/a20ad3f5aa61f93400b2cf025883e13d72b568ef/pkg/server/tenant.go#L135)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

maybe construction of this status server should somehow be pushed down into the construction of the sql server?  I'm not actually sure. How do we do this for the system tenent?
</blockquote></details>

We do something similar for the system tenant, we assign the sqlServer after construction.
___
*[pkg/server/tenant.go, line 142 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69486#-MiKQr5aAtSe6in71q9Z:-MiMqaEm9bclQ7jaLH3Z:b-3zc3x7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a20ad3f5aa61f93400b2cf025883e13d72b568ef/pkg/server/tenant.go#L142)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

does this change belong in the second commit rather than the first one? I think we want to backport only the first one. 
</blockquote></details>

Good point, it should be in the second one
___
*[pkg/server/tenant_status.go, line 121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69486#-MiKPwM74kGuaBxBmBNI:-MiMkLOb3hSpaEdxsNQz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a20ad3f5aa61f93400b2cf025883e13d72b568ef/pkg/server/tenant_status.go#L121)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	dialFn := func(ctx context.Context, instanceID base.SQLInstanceID, addr string) (interface{}, error) {
> 		client, err := t.dialPod(ctx, instanceID, addr)
> 		return client, err
> 	}
> 	nodeStatement := func(ctx context.Context, client interface{}, _ base.SQLInstanceID) (interface{}, error) {
> 		statusClient := client.(serverpb.StatusClient)
> 		return statusClient.ListLocalSessions(ctx, req)
> 	}
> ```
in both of these cases can you do the more verbose nil checking? The reasons is that both of these methods return structs. A real gotcha in go is if you return a nil struct type from a function that returns an interface type, the return value won't be nil. This can cause subtle bugs. We should probably lint against it. 
</blockquote></details>

Done.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69486)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[-- commits, line 22 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69486#-MiRPnODCx8RshWSs1SH):*
not need to capitalize `POD`, it does not stand for anything.
___
*[pkg/server/tenant_status.go, line 119 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69486#-MiRN3nw2KFe6i0em0jy:-MiRN3nw2KFe6i0em0jz:b-jm2aaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a1d4c6fa9f35376c11b4b9e4d0687847973872/pkg/server/tenant_status.go#L119)):*
> ```Go
> 		return nil, err
> 	}
> 	dialFn := func(ctx context.Context, instanceID base.SQLInstanceID, addr string) (interface{}, error) {
> ```

can you factor all of this logic out? It looks repeated with `Statements`. 
___
*[pkg/server/tenant_status.go, line 122 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69486#-MiRMEeT0l5SvLuwHLzA:-MiRMEeT0l5SvLuwHLzB:b-rhuq1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a1d4c6fa9f35376c11b4b9e4d0687847973872/pkg/server/tenant_status.go#L122)):*
> ```Go
> 		client, err := t.dialPod(ctx, instanceID, addr)
> 		if client == nil {
> 			log.Errorf(ctx, "dialing node  (%s, %d) for list session returned nil",
> ```

nit: extra space
___
*[pkg/server/tenant_status.go, line 122 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69486#-MiRMKFR6Hxp4_qlvCw7:-MiRMKFR6Hxp4_qlvCw8:b-nvbhf9) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a1d4c6fa9f35376c11b4b9e4d0687847973872/pkg/server/tenant_status.go#L122)):*
> ```Go
> 		client, err := t.dialPod(ctx, instanceID, addr)
> 		if client == nil {
> 			log.Errorf(ctx, "dialing node  (%s, %d) for list session returned nil",
> ```

nit: call it an instance rather than a node. `node` is the language we use for data storing things. 
___
*[pkg/server/tenant_status.go, line 127 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69486#-MiRMXvv12NQ87cdSsE9:-MiRMXvv12NQ87cdSsEA:b6h3ad6) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a1d4c6fa9f35376c11b4b9e4d0687847973872/pkg/server/tenant_status.go#L127)):*
> ```Go
> 		return client, err
> 	}
> 	nodeStatement := func(ctx context.Context, client interface{}, _ base.SQLInstanceID) (interface{}, error) {
> ```

does the contract allow this thing to be nil? 
___
*[pkg/server/tenant_status.go, line 128 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69486#-MiRPWFt5NXWjR0_jyeh:-MiRPWFt5NXWjR0_jyei:bcogtgt) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a1d4c6fa9f35376c11b4b9e4d0687847973872/pkg/server/tenant_status.go#L128)):*
> ```Go
> 	}
> 	nodeStatement := func(ctx context.Context, client interface{}, _ base.SQLInstanceID) (interface{}, error) {
> 		statusClient := client.(serverpb.StatusClient)
> ```

but actually, if client were nil, you'd already have panic'd here: https://play.golang.org/p/hu4byMid97o
___
*[pkg/server/tenant_status.go, line 130 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69486#-MiRP3bXBd9FKqvXEape:-MiRP3bXBd9FKqvXEapf:b-98ls2f) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a1d4c6fa9f35376c11b4b9e4d0687847973872/pkg/server/tenant_status.go#L130)):*
> ```Go
> 		statusClient := client.(serverpb.StatusClient)
> 		if statusClient == nil {
> 			log.Error(ctx, "unexpected nil client for list session")
> ```

given you're going to panic on the next line if this thing is nil, may as well log.Fatal. 
___
*[pkg/server/tenant_status.go, line 132 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69486#-MiRP7tt3y8xwCFzRhkn:-MiRP7tt3y8xwCFzRhko:b-vxu7hj) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a1d4c6fa9f35376c11b4b9e4d0687847973872/pkg/server/tenant_status.go#L132)):*
> ```Go
> 			log.Error(ctx, "unexpected nil client for list session")
> 		}
> 		return statusClient.ListLocalSessions(ctx, req)
> ```

What I was saying before is to nil check the return of this

**Review by ajwerner — COMMENTED** [review]
cc @cockroachdb/obs-inf-prs since this status server API is yours. 

> Reviewed 1 of 4 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69486#-:-MiWxK1C4lFglIH5jnfs:b-mrkxcs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[pkg/server/tenant_status.go, line 135 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69486#-MiWx8Hs1biK1jYZSlbM:-MiWx8Hs1biK1jYZSlbN:bxulutl) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a1d4c6fa9f35376c11b4b9e4d0687847973872/pkg/server/tenant_status.go#L135)):*
> ```Go
> 	}
> 	lastErr := err
> 	if err := t.iteratePods(ctx, fmt.Sprintf("sessions for nodes"),
> ```

this is so javascript :)

**Review by rimadeodhar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69486)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @fqazi)

___
*[pkg/server/tenant_status.go, line 137 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/69486#-MibOO5o7nChdALFrwfQ:-MibOO5p8_o9UsSFxOFn:b-s0dtkx) ([raw file](https://github.com/cockroachdb/cockroach/blob/051fb92cafb143a31059cedbeac6e193f0d36a80/pkg/server/tenant_status.go#L137)):*
> ```Go
> 		return localResponse, err
> 	}
> 	if err := t.iteratePods(ctx, "sessions for nodes",
> ```

One thing I want to call out is that iteratePods is based on the sqlinstance subsystem and I'm working on a change which will introduce caching to this layer. So there is a chance that the pods returned by this call maybe stale. That is, there could be a newly created pod which is not returned by this call as soon as it is added. Will that cause any problems with the way this cleanup is supposed to work?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69486)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @fqazi, and @rimadeodhar)

___
*[pkg/server/tenant_status.go, line 137 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/69486#-MibOO5o7nChdALFrwfQ:-MibP5NOBlEBh9ylBqpD:bjkk0gf) ([raw file](https://github.com/cockroachdb/cockroach/blob/051fb92cafb143a31059cedbeac6e193f0d36a80/pkg/server/tenant_status.go#L137)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

One thing I want to call out is that iteratePods is based on the sqlinstance subsystem and I'm working on a change which will introduce caching to this layer. So there is a chance that the pods returned by this call maybe stale. That is, there could be a newly created pod which is not returned by this call as soon as it is added. Will that cause any problems with the way this cleanup is supposed to work?
</blockquote></details>

We intentionally have a delay between the modification time and when the objects are dropped. So, cached data shouldn't present any risk in the design, since we will wait for modification time + N minutes before dropping objects. So, the caching layer shouldn't create problems for the temporary schema object clean-up logic. @rimadeodhar

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69486#-:-Mj9kWuC2MHA-2VT68q-:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @rimadeodhar)

**Review by dhartunian — COMMENTED** [review]
> Reviewed 4 of 8 files at r8, 1 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69486)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @fqazi, and @rimadeodhar)

___
*[pkg/server/tenant_status.go, line 123 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/69486#-Mj9sDSC83FBed9NfVfH:-Mj9rNE18awJCLRHpJsG:bdcffv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c62321b3e86359cdd99f755da5c199d96d65dc9/pkg/server/tenant_status.go#L123)):*
> ```Go
> 	}
> 
> 	response, err := t.ListLocalSessions(ctx, req)
> ```

My understanding of `iteratePods` was that it would include the pod that's executing this RPC as well so this might introduce duplication to seed it with the result of `ListLocalSessions`. Am I misunderstanding something?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69486)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @ajwerner, @dhartunian, and @rimadeodhar)

___
*[pkg/server/tenant_status.go, line 123 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/69486#-Mj9sDSC83FBed9NfVfH:-MjBDhBlDkK0waOOxG_K:b7imf23) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c62321b3e86359cdd99f755da5c199d96d65dc9/pkg/server/tenant_status.go#L123)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

My understanding of `iteratePods` was that it would include the pod that's executing this RPC as well so this might introduce duplication to seed it with the result of `ListLocalSessions`. Am I misunderstanding something?
</blockquote></details>

Done.

This was a misunderstanding on my part, and we would get duplicate entries because of it.

**Review by rimadeodhar — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 6 files at r7, 1 of 6 files at r9, 1 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69486#-:-MjBGy5m1yY66EjSMhjC:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @ajwerner, and @dhartunian)

**Review by dhartunian — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69486#-:-MjBo1Nu9HfrZNOP9d3E:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @ajwerner, and @dhartunian)

**Comment by ajwerner** [comment]
@fqazi can you backport this?

**Comment by fqazi** [comment]
@ajwerner Yes, I'll backport this one over

**Pull request merged**
