### PR TITLE
sql: code for splitting filter expressions

### PR DESCRIPTION
**Pull request by RaduBerinde**
Adding code that splits a filter expression according to a set of VariableExprs
(qvalues). This will be used:
- to convert qvalues to a type that is suitable to be evaluated in scanNode
  (and later on the remote side or in the KV layer),
- in indexJoin to run whatever part of the filter we can on the keys in the
  index, and
- (later) when we filter across multiple tables (joins).

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4304)

### CODE REVIEW

**Comment by tamird** [comment]
looks like your git settings are messed up - either committer or author is not set properly.

**Comment by RaduBerinde** [comment]
Thanks, should be fixed now

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-:-KACIkqkiTh0WYbz8Nkz:7518328)*

**Comment by tamird** [comment]
Partial review posted, still looking at the rest.

---

Reviewed 4 of 6 files at r1.
Review status: 4 of 6 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[sql/group.go, line 624 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KACQ26zLBDOUogeEBBx:-KACQ26zLBDOUogeEBBy:780534527) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ffb3fe06773c9b0daca347044854541177deb/sql/group.go#L624)):*
tip: `panic(fmt.Sprintf("deep copy not implemented for %T, a"))` might save some future work.

---

*[sql/parser/deep_copy.go, line 26 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KACRcZs6mfXBiJdnUP0:-KACRcZs6mfXBiJdnUP1:-496346346) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ffb3fe06773c9b0daca347044854541177deb/sql/parser/deep_copy.go#L26)):*
we need a better strategy for these recursive copies - if someone adds a field that needs a deep copy to any of these structures, the behaviour will be subtly wrong.

I think the best you can do is add reflection-based tests to mitigate this. See `roachpb.TestTransactionClone` for some prior art.

---

*[sql/parser/deep_copy.go, line 142 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KACQXOAVP4ahJl0GpsD:-KACQXOAVP4ahJl0GpsE:180600945) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ffb3fe06773c9b0daca347044854541177deb/sql/parser/deep_copy.go#L142)):*
nit: you can do this in two lines as explained below

---

*[sql/parser/deep_copy.go, line 159 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KACQQ61ty2C3-opwavR:-KACQQ61ty2C3-opwavS:1747750831) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ffb3fe06773c9b0daca347044854541177deb/sql/parser/deep_copy.go#L159)):*
consider the `%T` thing here, though it won't generate as nice a string

---

*[sql/parser/deep_copy.go, line 164 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KACQOUzZ4toZ8Vg5pvn:-KACQOUzZ4toZ8Vg5pvo:313298375) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ffb3fe06773c9b0daca347044854541177deb/sql/parser/deep_copy.go#L164)):*
what happens if someone adds a field?

---

*[sql/parser/deep_copy.go, line 181 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KACQG4gHStpz5RDfjoP:-KACQG4gHStpz5RDfjoQ:1473939258) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ffb3fe06773c9b0daca347044854541177deb/sql/parser/deep_copy.go#L181)):*
This is error prone. You should instead write:
```
tCopy := *t
return &t
``

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-:-KACRwdTBjdTiONaEwCY:-1804424470)*
<!-- Sent from Reviewable.io -->

**Comment by RaduBerinde** [comment]
*[sql/parser/deep_copy.go, line 26 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KACRcZs6mfXBiJdnUP0:-KACXX9eRlDERzaR_tid:552720314) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ffb3fe06773c9b0daca347044854541177deb/sql/parser/deep_copy.go#L26)):*
Good idea, I will add tests.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304)*

**Comment by tamird** [comment]
Reviewed 2 of 6 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[sql/expr_filter.go, line 57 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KACYRatZ6kfPGtkLNPa:-KACYRatZ6kfPGtkLNPb:-1268841085) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ffb3fe06773c9b0daca347044854541177deb/sql/expr_filter.go#L57)):*
instead of panicking, could you replace `v.result` with an `error` field and return an error from `exprConverVars`?

---

*[sql/expr_filter.go, line 78 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KACYrsrjwRpaHTLpm_U:-KACYrsrjwRpaHTLpm_V:1817531365) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ffb3fe06773c9b0daca347044854541177deb/sql/expr_filter.go#L78)):*
shouldn't `justCheck` be `false`? add a test for this, please.

---

*[sql/expr_filter.go, line 83 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KACZ4lXpMhZK5bsXiXO:-KACZ4lXpMhZK5bsXiXP:2007563573) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ffb3fe06773c9b0daca347044854541177deb/sql/expr_filter.go#L83)):*
I'm not 100% sure, but I think each of these `parser.DBool()` interface-boxing calls allocates.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[sql/expr_filter.go, line 57 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KACYRatZ6kfPGtkLNPa:-KACgPFfW3mRWFiZkVfQ:-1255042725) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ffb3fe06773c9b0daca347044854541177deb/sql/expr_filter.go#L57)):*
Things are designed so that we always CheckVars before ConvertVars. A variable that cannot be converted is not some kind of failure but it denotes that we don't want the variable in the "result" expression (normally this means that it refers to a column or table not in a "target" set of columns/tables).

---

*[sql/expr_filter.go, line 83 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KACZ4lXpMhZK5bsXiXO:-KACip3WomVkvkL2J8Ag:-888560216) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ffb3fe06773c9b0daca347044854541177deb/sql/expr_filter.go#L83)):*
Hm, I can't find any clear information one way or the other. Why do you think there is boxing?

Just doing `DBool()` is a type conversion, it doesn't do much (`DBool` is just a `bool` with some compile-time constraints).

Interface vs non-interface equality is defined as "the type in the interface matches, and the values match", so internally it should be the same with `if ok, v := left.(DBool); ok && v == parser.DBool(false)`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304)*

**Comment by RaduBerinde** [comment]
*[sql/expr_filter.go, line 78 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KACYrsrjwRpaHTLpm_U:-KACq10T5d_e1WnGexL1:159626043) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ffb3fe06773c9b0daca347044854541177deb/sql/expr_filter.go#L78)):*
Good catch, the test wasn't actually doing any conversions. Added.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[sql/expr_filter.go, line 57 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KACYRatZ6kfPGtkLNPa:-KACnK5xokKYHVAmwQDE:1184986015) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ffb3fe06773c9b0daca347044854541177deb/sql/expr_filter.go#L57)):*
I see. I didn't see that in any of the comments.

I still don't think putting it in the comments is the right way to go - it should return an error, and handling of that error at the caller will illustrate to the reader the invariant much better than a comment.

---

*[sql/expr_filter.go, line 83 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KACZ4lXpMhZK5bsXiXO:-KACruXhwBbiRLgkxth3:-316925132) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ffb3fe06773c9b0daca347044854541177deb/sql/expr_filter.go#L83)):*
Oh, you're not actually using the `parser.DBool` literal as a `parser.Datum`. Duh, ignore me.

---

*[sql/expr_filter.go, line 78 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KACtG6Sy8XAwI6CeXEg:-KACsf_MzUkuN2svx_vM:-1053215216) ([raw file](https://github.com/cockroachdb/cockroach/blob/f50e4ea787f68b4a847a579993873bca846a42bf/sql/expr_filter.go#L78)):*
just remove the initialization of `result` here, I stared at it for about 30 seconds trying to work out why it mattered.

---

*[sql/expr_filter_test.go, line 37 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KACsyg1SuEPF7OfRnfQ:-KACsyg1SuEPF7OfRnfR:-836907762) ([raw file](https://github.com/cockroachdb/cockroach/blob/f50e4ea787f68b4a847a579993873bca846a42bf/sql/expr_filter_test.go#L37)):*
nit: consider a type switch

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304)*

**Comment by andreimatei** [comment]
LGTM

I like this :smile: 

---

Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[sql/expr_filter.go, line 18 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KAFm82_ZCZcmmpOxdQ-:-KAFm82af9q4Pb18uPi4:1572006297) ([raw file](https://github.com/cockroachdb/cockroach/blob/f50e4ea787f68b4a847a579993873bca846a42bf/sql/expr_filter.go#L18)):*
can you give more intuition here, or in the `varConvertFunc` about what these converters do? Like what you said in the PR description, maybe with one or two examples?

---

*[sql/expr_filter.go, line 30 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KAFvWKwexG0Kdsg6Zml:-KAFvWKwexG0Kdsg6Zmm:-621060309) ([raw file](https://github.com/cockroachdb/cockroach/blob/f50e4ea787f68b4a847a579993873bca846a42bf/sql/expr_filter.go#L30)):*
I don't really understand this comment. There's no context for "output expression" or the "target set of columns". Maybe give an example.

---

*[sql/expr_filter.go, line 40 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KAFliKck0tsmrpSagto:-KAFliKck0tsmrpSagtp:-1370999035) ([raw file](https://github.com/cockroachdb/cockroach/blob/f50e4ea787f68b4a847a579993873bca846a42bf/sql/expr_filter.go#L40)):*
does this need to be initialized to `true` when `justCheck` is set? How about turning it into `checkFailed`?

---

*[sql/expr_filter.go, line 49 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KAFmuKn2IhzrYmbidOO:-KAFmuKn2IhzrYmbidOP:1509611467) ([raw file](https://github.com/cockroachdb/cockroach/blob/f50e4ea787f68b4a847a579993873bca846a42bf/sql/expr_filter.go#L49)):*
does it matter if we're in `pre` or not, or that we only run once per node?

---

*[sql/expr_filter.go, line 131 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KAFqzMgYKjva71H_u1S:-KAFqzMgYKjva71H_u1T:-694046303) ([raw file](https://github.com/cockroachdb/cockroach/blob/f50e4ea787f68b4a847a579993873bca846a42bf/sql/expr_filter.go#L131)):*
do we need the `weaker = false` case?

---

*[sql/expr_filter.go, line 134 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KAFpMJ9ei-hxGhEkyy2:-KAFpMJ9ei-hxGhEkyy3:1431431804) ([raw file](https://github.com/cockroachdb/cockroach/blob/f50e4ea787f68b4a847a579993873bca846a42bf/sql/expr_filter.go#L134)):*
took me a bit here to see why REM is `parser.DBool(weaker)`. Maybe add a comment.

---

*[sql/expr_filter.go, line 159 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KAFqes3B7YbwobUKs8T:-KAFqes3B7YbwobUKs8U:312951444) ([raw file](https://github.com/cockroachdb/cockroach/blob/f50e4ea787f68b4a847a579993873bca846a42bf/sql/expr_filter.go#L159)):*
nit: above weaker is handled first

---

*[sql/expr_filter_test.go, line 56 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KAFnidd73hGiaiYcqV_:-KAFnidd73hGiaiYcqVa:1143929892) ([raw file](https://github.com/cockroachdb/cockroach/blob/f50e4ea787f68b4a847a579993873bca846a42bf/sql/expr_filter_test.go#L56)):*
can you add a comment explaining this test?
Is is `Split expressions with respect to some columns for which values are known`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-:-KAFvrQpGIshmjW6_3V8:263854749)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[sql/expr_filter.go, line 57 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KACYRatZ6kfPGtkLNPa:-KAG5DpARPJaQZFxZg03:-250179746) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ffb3fe06773c9b0daca347044854541177deb/sql/expr_filter.go#L57)):*
I hesitate using an error for things that are not errors but completely expected code paths.. (if nothing else, we will allocate errors each time for no reason). How about adding a bool flag in addition to the VariableExpr return value? That would make it clearer and easier to explain (including the things Andrei mentioned above)

---

*[sql/expr_filter.go, line 18 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KAFm82_ZCZcmmpOxdQ-:-KAG7I4JaJa71bWrjIG0:1765789710) ([raw file](https://github.com/cockroachdb/cockroach/blob/f50e4ea787f68b4a847a579993873bca846a42bf/sql/expr_filter.go#L18)):*
I will add more comments

---

*[sql/expr_filter.go, line 131 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KAFqzMgYKjva71H_u1S:-KAG5cGu7D7iosLhs77L:-1827254284) ([raw file](https://github.com/cockroachdb/cockroach/blob/f50e4ea787f68b4a847a579993873bca846a42bf/sql/expr_filter.go#L131)):*
Unfortunately yes, for NOT. We always start with `weaker=true` but inside a NOT we have to invert it.

---

*[sql/expr_filter.go, line 159 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KAFqes3B7YbwobUKs8T:-KAG5iu-zyB1YstMoXGU:472235416) ([raw file](https://github.com/cockroachdb/cockroach/blob/f50e4ea787f68b4a847a579993873bca846a42bf/sql/expr_filter.go#L159)):*
The first cases (weaker for AND, !weaker for OR) are analogous - they're the cases where "it works out" so to speak.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[sql/expr_filter.go, line 57 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KACYRatZ6kfPGtkLNPa:-KAGDM-4Km_En7VL2nmL:1851631977) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ffb3fe06773c9b0daca347044854541177deb/sql/expr_filter.go#L57)):*
You can avoid the allocation simply by having a package-level variable `var errFooBar = errors.New("blabla")`.

Isn't VariableExpr an interface?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304)*

**Comment by RaduBerinde** [comment]
*[sql/expr_filter.go, line 57 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KACYRatZ6kfPGtkLNPa:-KAGErqBBY3cPRFadQbi:-1375470476) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ffb3fe06773c9b0daca347044854541177deb/sql/expr_filter.go#L57)):*
Let me post an update with better comments and a bool flag and take it from there. I feel like I haven't described the usage properly. In my mind using an error would be analogous to the golang map lookup or type assertion return an error instead of a flag.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304)*

**Comment by RaduBerinde** [comment]
Updated, hope the new comments help.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-:-KAHQPFymEJgug0dL0a5:2071752618)*

**Comment by RaduBerinde** [comment]
Review status: 4 of 9 files reviewed at latest revision, 12 unresolved discussions.

---

*[sql/expr_filter.go, line 49 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KAFmuKn2IhzrYmbidOO:-KAGQwJASIxcWLp3xheP:998546791) ([raw file](https://github.com/cockroachdb/cockroach/blob/f50e4ea787f68b4a847a579993873bca846a42bf/sql/expr_filter.go#L49)):*
We don't want to call conv() on an already converted variable so we only want to run once per node. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304)*

**Comment by tamird** [comment]
Reviewed 5 of 5 files at r4.
Review status: 8 of 9 files reviewed at latest revision, 10 unresolved discussions.

---

*[util/reflect.go, line 15 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KAHhF5kBj6JDQYRnJvd:-KAHhF5kBj6JDQYRnJve:676744488) ([raw file](https://github.com/cockroachdb/cockroach/blob/23de7d8bc2f3dc191280af1d08023cb1effd00aa/util/reflect.go#L15)):*
Heh.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304)*

**Comment by RaduBerinde** [comment]
*[util/reflect.go, line 15 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KAHhF5kBj6JDQYRnJvd:-KAHiaeenOqMZuuXa63S:-1312286618) ([raw file](https://github.com/cockroachdb/cockroach/blob/23de7d8bc2f3dc191280af1d08023cb1effd00aa/util/reflect.go#L15)):*
Force of habit when creating a new file. If you know who wrote this function I can put their name

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[util/reflect.go, line 15 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KAHhF5kBj6JDQYRnJvd:-KAHjFcpUQBJWp41-tBg:-882352496) ([raw file](https://github.com/cockroachdb/cockroach/blob/23de7d8bc2f3dc191280af1d08023cb1effd00aa/util/reflect.go#L15)):*
Put my name. Peter wrote an earlier version, but it was never committed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304)*

**Comment by andreimatei** [comment]
Review status: 8 of 9 files reviewed at latest revision, 10 unresolved discussions.

---

*[sql/expr_filter.go, line 41 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KALapvbvhFXI3I3tUlM:-KALapvbvhFXI3I3tUlN:1022105588) ([raw file](https://github.com/cockroachdb/cockroach/blob/96fcaaace6500eece4c808ece6c7d3be7ee830f5/sql/expr_filter.go#L41)):*
Maybe also hint about this type conversion - is it about transforming a QualifiedName into a qvalue? Btw do/will we have an equivalent for qvalues for references to values in an index?

---

*[sql/expr_filter.go, line 48 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KALeT3KF9VbjbwEWhXm:-KALeT3LgT8PR0pqyMXc:-1379231255) ([raw file](https://github.com/cockroachdb/cockroach/blob/96fcaaace6500eece4c808ece6c7d3be7ee830f5/sql/expr_filter.go#L48)):*
I don't understand this cast, here and in the test. Isn't this function expected to be called on anything but qvalues? How come? If that's so, can you make it take a qvalue param?

---

*[sql/expr_filter.go, line 216 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KALd4ytgbe_Q2i9pXTx:-KALd4ytgbe_Q2i9pXTy:616366061) ([raw file](https://github.com/cockroachdb/cockroach/blob/96fcaaace6500eece4c808ece6c7d3be7ee830f5/sql/expr_filter.go#L216)):*
why not? what about if all variables in `expr` can be converted?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304)*

**Comment by RaduBerinde** [comment]
Review status: 8 of 9 files reviewed at latest revision, 10 unresolved discussions.

---

*[sql/expr_filter.go, line 41 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KALapvbvhFXI3I3tUlM:-KALfcgccVfk2LdpFweJ:-519892146) ([raw file](https://github.com/cockroachdb/cockroach/blob/96fcaaace6500eece4c808ece6c7d3be7ee830f5/sql/expr_filter.go#L41)):*
This is not meant for doing qualified name lookup. We would have done that already before calling splitFilter (currently that means we will have *qvalues). That's what I was thinking - we probably want a different qvalue-like type for references to values in an index, though I don't really have all the details yet.

---

*[sql/expr_filter.go, line 48 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KALeT3KF9VbjbwEWhXm:-KALg3JUfqVYpU_Ghmrj:-1522662265) ([raw file](https://github.com/cockroachdb/cockroach/blob/96fcaaace6500eece4c808ece6c7d3be7ee830f5/sql/expr_filter.go#L48)):*
*qvalue is currently our only implementation of VariableExpr. But we may need to have multiple implementations that's why the function is generic.

What do you mean anything but qvalues? It's exactly meant to be called on the nodes that refer to row values (aka VariableExpr).

---

*[sql/expr_filter.go, line 216 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KALd4ytgbe_Q2i9pXTx:-KALgTYiiKXstipOwgTV:-643420992) ([raw file](https://github.com/cockroachdb/cockroach/blob/96fcaaace6500eece4c808ece6c7d3be7ee830f5/sql/expr_filter.go#L216)):*
We already checked for that above. I improved the comment.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304)*

**Comment by andreimatei** [comment]
still LGTM, but see the discussion on ValArgs implementing VariableExpr

---

Review status: 7 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[sql/expr_filter.go, line 48 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KALeT3KF9VbjbwEWhXm:-KALk4tp8nM3F4SVxp--:-2061062949) ([raw file](https://github.com/cockroachdb/cockroach/blob/96fcaaace6500eece4c808ece6c7d3be7ee830f5/sql/expr_filter.go#L48)):*
well `VariableExpr` seems to also be implemented by ValArg and DValArg (besides QualifiedName)...But maybe those are replaced by a datum by the time this splitting is called (but then I guess splitting can only be called iff `prepareOnly` is not set on the planner)?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-:-KALl-C5akL1a5YYnMXU:-568043321)*

**Comment by RaduBerinde** [comment]
*[sql/expr_filter.go, line 48 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KALeT3KF9VbjbwEWhXm:-KALm4gZhqSK5FAku5cO:-1323512361) ([raw file](https://github.com/cockroachdb/cockroach/blob/96fcaaace6500eece4c808ece6c7d3be7ee830f5/sql/expr_filter.go#L48)):*
Can ValArgs be part of WHERE expressions in SELECT? I don't think I've seen any code handling them

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[sql/expr_filter.go, line 48 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KALeT3KF9VbjbwEWhXm:-KALoDXbD3GUUeRq5bx9:-985426881) ([raw file](https://github.com/cockroachdb/cockroach/blob/96fcaaace6500eece4c808ece6c7d3be7ee830f5/sql/expr_filter.go#L48)):*
During preparation, yes, but not during execution.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[sql/expr_filter.go, line 48 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KALeT3KF9VbjbwEWhXm:-KALqNSJw-StKD2Dkhgp:-1630794671) ([raw file](https://github.com/cockroachdb/cockroach/blob/96fcaaace6500eece4c808ece6c7d3be7ee830f5/sql/expr_filter.go#L48)):*
Makes sense, thanks, we should be good then.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[sql/expr_filter.go, line 48 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KALeT3KF9VbjbwEWhXm:-KALr7CnhNtHXgpGwiHD:-605484606) ([raw file](https://github.com/cockroachdb/cockroach/blob/96fcaaace6500eece4c808ece6c7d3be7ee830f5/sql/expr_filter.go#L48)):*
is ValArg replaced by a DValArg during execution? Cause that guy also implements VariableExpr.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[sql/expr_filter.go, line 48 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304#-KALeT3KF9VbjbwEWhXm:-KALs8wkP-xfieudXcBN:1332890088) ([raw file](https://github.com/cockroachdb/cockroach/blob/96fcaaace6500eece4c808ece6c7d3be7ee830f5/sql/expr_filter.go#L48)):*
Those are both placeholder types. We can't execute a query with placeholders (though I can't remember why there are two types).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4304)*

**Pull request merged**
