### PR TITLE
sql: add SHOW DEFAULT SESSION VARIABLES FOR ROLE command

### PR DESCRIPTION
**Pull request by jasminejsun**
Epic: [CRDB-26921](https://cockroachlabs.atlassian.net/browse/CRDB-26921)
Issue: #117500

Release note (sql change): Previously, if a database administrator wanted to know which session variables they had set by default for a role they would need to switch into that user or scan a system table manually. This could be more time consuming or difficult to us. To address this, this patch adds a new command: SHOW VARIABLES FOR ROLE, which allows the database administrator to easily view the default values for a session variables applied to a given user.

### CODE REVIEW

**Review by fqazi — CHANGES_REQUESTED** [review]
Great work, just a few minor things!

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117875#-:-NomndLhE2CjtRppfYgR:b-9pj4r1)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jasminejsun)

___
*[`pkg/sql/delegate/show_variables_for_role.go` line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117875#-Nommlca32Zk4UFKaF0f:-Nommlca32Zk4UFKaF0g:b-a51kmg) ([raw file](https://github.com/cockroachdb/cockroach/blob/08ac19d79552f0643a1cb1af83a5a23068259745/pkg/sql/delegate/show_variables_for_role.go#L26)):*
> ```Go
> ) (tree.Statement, error) {
> 	getVariablesForRoleQuery := `SELECT split_part(split_part(unnest(settings), ',', 1), '=', 1) as session_variables,
> 		split_part(split_part(unnest(settings), ',', 1), '=', 2) as default_values
> ```

I worry this might break if we have things with commands or equal signs within the settings themselves. i.e. 

Imagine if someone did something stupid like: 
'alter role demo set search_path='a='';
___
*[`pkg/sql/parser/testdata/show` line 2125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117875#-NomnWqd9gQzZv54L6m0:-NomnWqd9gQzZv54L6m1:b-mt5bah) ([raw file](https://github.com/cockroachdb/cockroach/blob/08ac19d79552f0643a1cb1af83a5a23068259745/pkg/sql/parser/testdata/show#L2125)):*
> ```
> SHOW VARIABLES FOR ROLE ALL -- fully parenthesized
> SHOW VARIABLES FOR ROLE ALL -- literals removed
> SHOW VARIABLES FOR ROLE ALL -- identifiers removed
> ```

One more test here try using a parametrized query...i.e. ROLE $1

**Comment by jasminejsun** [comment]
*[`pkg/sql/delegate/show_variables_for_role.go` line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117875#-Nommlca32Zk4UFKaF0f:-Non35Ch2jj7r-efPxif:bvetd5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/08ac19d79552f0643a1cb1af83a5a23068259745/pkg/sql/delegate/show_variables_for_role.go#L26)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I worry this might break if we have things with commands or equal signs within the settings themselves. i.e. 

Imagine if someone did something stupid like: 
'alter role demo set search_path='a='';
</blockquote></details>

Good point! 
Is it safe to assume that the session variable name will never include an equal sign, and just split on the first equal sign in the string?

**Review by fqazi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117875)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jasminejsun)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117875#-NonFthl924D2Jg-umRg):*
Add a release note describing the functionality and follow the format from the wiki

**Comment by jasminejsun** [comment]
*[`pkg/sql/parser/testdata/show` line 2125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117875#-NomnWqd9gQzZv54L6m0:-NoqorhKCTAiRnIcADh4:bsas4sd) ([raw file](https://github.com/cockroachdb/cockroach/blob/08ac19d79552f0643a1cb1af83a5a23068259745/pkg/sql/parser/testdata/show#L2125)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

One more test here try using a parametrized query...i.e. ROLE $1
</blockquote></details>

Non-applicables since role_spec utilizes identifiers rather than expressions! :smile:

**Comment by jasminejsun** [comment]
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117875#-NonFthl924D2Jg-umRg):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Add a release note describing the functionality and follow the format from the wiki
</blockquote></details>

Done!

**Review by fqazi — APPROVED** [review]
:lgtm: Just a few more minor nits, once those are sorted its ready to merge.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117875#-:-NoqsIdb0kJTadX6PbDV:brf363t)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jasminejsun)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117875#-Noqr6dMBnxJQpxFRAWN):*
Instead of going low level lets focus on why this was needed / what it solves i.e.:

Previously, if a database administrator wanted to know which session variables they had set by default for a role they would need to switch into that user or scan a system table manually. This could be more time consuming or difficult to us. To address this, this patch adds a new command: SHOW VARIABLES FOR ROLE, which allows the database administrator to easily view the default values for a session variables applied to a given user.
___
*[`pkg/sql/delegate/show_variables_for_role.go` line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117875#-Noqs1TW60-Fs7UU3DaG:-Noqs1TW60-Fs7UU3DaH:bht1t6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c540823b9035a0323906edd35f21e9bcd28d87/pkg/sql/delegate/show_variables_for_role.go#L19)):*
> ```Go
> )
> 
> // delegateShowVariablesForRole implements SHOW VARIABLES FOR ROLE <name> which returns all the default session values
> ```

Nit: session variables for a user.

**Review by rafiss — CHANGES_REQUESTED** [review]
this is nice work! i have a few comments that i think we should address before merging

i saw that `SHOW VARIABLES FOR ROLE` was the syntax that @dikshant suggested in CRDB-26921. However, I don't think this is that intuitive -- we don't use the word "variable" like this anywhere else in our product. Can we change the command to something even more explicit, like: `SHOW DEFAULT SESSION VARIABLES FOR ROLE ...` ?

the rest of my comments are inline

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117875#-:-NorQNb89wzZJhQj2OEE:b-b2cbz6)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi and @jasminejsun)

___
*[`pkg/sql/delegate/show_variables_for_role.go` line 28 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117875#-NorQyFK2pGWn6K2GYN4:-NorQyFK2pGWn6K2GYN5:b7doxi) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc9040991d6ceba0ea1f60ef5fc8bc915c435049/pkg/sql/delegate/show_variables_for_role.go#L28)):*
> ```Go
> 	getVariablesForRoleQuery := `SELECT split_part(setting, '=', 1) AS session_variables,
> 		substring(setting FROM position('=' in setting) + 1) AS default_values
> 		FROM system.database_role_settings,
> ```

implementing the query this way, with a lookup on `system.database_role_settings`, has a downside. it means that you need to have privileges on the system table, which is something that normally only admins have. instead, i think we should make the query look at `pg_catalog.pg_db_role_setting`, which does not require additional privileges.

then, at the beginning of this function, we should have the specific privilege checks we need in place. let's make the required privileges be the same as the ones needed to run `ALTER ROLE ... SET`; that is, running this SHOW command requires at least one of CREATEROLE, MODIFYCLUSTERSETTING, or MODIFYSQLCLUSTERSETTING. you can see that they are checked in this part of the code: https://github.com/cockroachdb/cockroach/blob/df6457a64a172560732897c5ada083ebe78ad610/pkg/sql/alter_role.go#L301-L316

here is an example of how a different SHOW command does privilege checking: https://github.com/cockroachdb/cockroach/blob/df6457a64a172560732897c5ada083ebe78ad610/pkg/sql/delegate/show_all_cluster_settings.go#L29-L50

finally, let's make sure that the logictests cover the privilege checking too
___
*[`pkg/sql/logictest/testdata/logic_test/alter_role_set` line 303 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117875#-NorTClZ4Tr8GeUoN8Jz:-NorTCl_CnsV84XoZq2Y:bvy91nx) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc9040991d6ceba0ea1f60ef5fc8bc915c435049/pkg/sql/logictest/testdata/logic_test/alter_role_set#L303)):*
> ```
> statement ok
> ALTER ROLE ALL SET application_name = 'c';
> ```

can we add more tests for the following:
```
ALTER ROLE roach IN DATABASE defaultdb SET ...

ALTER ROLE ALL IN DATABASE defaultdb SET ...
```

as you can see,  some of the defaults are per-database. so i think it would be important for the SHOW output to indicate if a given default is applicable to all databases, or a specific database. i think maybe there should be a third column, named something like `database_name`, and if that's NULL it means the default applies to all databases

**Comment by dikshant** [comment]
+1 on SHOW DEFAULT SESSION VARIABLES FOR ROLE ...

**Review by rafiss — APPROVED** [review]
this looks great! really nice work coming up with the delegate SQL query

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117875#-:-NpLzFU06gl0J7aVMMd7:bjhrglc)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi and @jasminejsun)

**Review by fqazi — APPROVED** [review]
> Reviewed 16 of 18 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117875)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jasminejsun)

___
*[`-- commits` line 11 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117875#-NpPxZKv4UrdtUVzWfmo):*
This should be the body of the commit message. Release note can simply just say you added SHOW VARIABLES FOR ROLE with a brief description of the feature.

**Pull request merged**
