### PR TITLE
sql/catalog: reduce NameKey allocations

### LINKED ISSUE #121300: catalog/descs: consider optimizing getNonVirtualDescriptorID
Here is a snippet of `alloc_objects` profile from one of the nodes (on v23.1.17):
```
ROUTINE ======================== github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getNonVirtualDescriptorID.func5 in github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go
2630107188 2630107188 (flat, cum)  1.82% of Total
         .          .    556:			return haltLookups, ud.GetID(), nil
         .          .    557:		}
         .          .    558:		return continueLookups, descpb.InvalidID, nil
         .          .    559:	}
         .          .    560:	lookupStoreCacheID := func() (continueOrHalt, descpb.ID, error) {
1316932341 1316932341    561:		ni := descpb.NameInfo{ParentID: parentID, ParentSchemaID: parentSchemaID, Name: name}
1313174847 1313174847    562:		if tc.isShadowedName(ni) {
         .          .    563:			return continueLookups, descpb.InvalidID, nil
         .          .    564:		}
         .          .    565:		if tc.cr.IsNameInCache(&ni) {
         .          .    566:			if e := tc.cr.Cache().LookupNamespaceEntry(&ni); e != nil {
         .          .    567:				return haltLookups, e.GetID(), nil
```
I'm guessing we could easily avoid these objects escaping.

Jira issue: CRDB-37175

Epic CRDB-42584

### LINKED ISSUE #135905: descs: catalog cache lookups needlessly allocate (1.42% allocs in oltp_read_only)
`lookupStoreCacheID`[^1] in `oltp_read_only`:

[^1]: https://github.com/cockroachdb/cockroach/blob/6a7b1e20e70c0ba8e6bb7a42d52512d9437cd75b/pkg/sql/catalog/descs/descriptor.go#L555-L567

image

It looks like we're heap allocating purely because the `NameKey` for the cache is an interface:

https://github.com/cockroachdb/cockroach/blob/6a7b1e20e70c0ba8e6bb7a42d52512d9437cd75b/pkg/sql/catalog/descriptor.go#L153-L161

This seems unfortunate. We can make a deeper change there or at least pool this particular allocation.

Epic: CRDB-42584

Jira issue: CRDB-44785

### PR DESCRIPTION
**Pull request by mgartner**
#### sql/catalog: change `LookupNamespaceEntry` parameter type

The `Catalog.LookupNamespaceEntry` method now accepts the concrete type
`descpb.NameInfo` instead of the `catalog.NameKey` interface. This,
along with future commits, will help reduce allocations.

Release note: None

#### sql/catalog: change `IsNameInCache` parameter type

The `CatalogReader.IsNameInCache` method now accepts the concrete type
`descpb.NameInfo` instead of the `catalog.NameKey` interface. This,
along with other commits, will help reduce allocations.

Release note: None

#### sql/catalog: change `(*Collection).isShadowedName` parameter type

The `(*Collection).isShadowedName` method now accepts the concrete type
`descpb.NameInfo` instead of the `catalog.NameKey` interface. This,
along with other commits, will help reduce allocations.

Informs #105867
Fixes #135905
Fixes #121300

Release note: None

#### sql/catalog: refactor `(*SystemDatabaseCache).lookupDescriptorID`

Now that `(*SystemDatabaseCache).lookupDescriptorID` accepts a
`descpb.NameInfo` parameter, it can access its exported field directly
instead of using getters.

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
`BenchmarkEndToEnd/kv-read` shows the improvement:

```
name                                     old time/op    new time/op    delta
EndToEnd/kv-read/vectorize=on/Simple        422µs ±10%     422µs ± 4%    ~     (p=0.690 n=5+5)
EndToEnd/kv-read/vectorize=on/Prepared      272µs ± 6%     276µs ± 2%    ~     (p=0.841 n=5+5)
EndToEnd/kv-read/vectorize=off/Simple       415µs ± 2%     428µs ± 7%    ~     (p=0.690 n=5+5)
EndToEnd/kv-read/vectorize=off/Prepared     269µs ± 4%     271µs ± 6%    ~     (p=1.000 n=5+5)

name                                     old alloc/op   new alloc/op   delta
EndToEnd/kv-read/vectorize=on/Simple       36.2kB ± 1%    36.0kB ± 1%    ~     (p=0.343 n=4+4)
EndToEnd/kv-read/vectorize=on/Prepared     25.9kB ±16%    26.0kB ±17%    ~     (p=1.000 n=5+5)
EndToEnd/kv-read/vectorize=off/Simple      37.8kB ± 4%    38.1kB ±11%    ~     (p=0.421 n=5+5)
EndToEnd/kv-read/vectorize=off/Prepared    26.0kB ± 2%    25.8kB ± 0%    ~     (p=0.111 n=5+4)

name                                     old allocs/op  new allocs/op  delta
EndToEnd/kv-read/vectorize=on/Simple          321 ± 0%       311 ± 0%  -3.19%  (p=0.029 n=4+4)
EndToEnd/kv-read/vectorize=on/Prepared        237 ±12%       233 ±13%    ~     (p=0.190 n=5+5)
EndToEnd/kv-read/vectorize=off/Simple         313 ± 0%       303 ± 0%  -3.19%  (p=0.029 n=4+4)
EndToEnd/kv-read/vectorize=off/Prepared       221 ± 0%       216 ± 0%  -2.09%  (p=0.000 n=5+4)
```

**Comment by rafiss** [comment]
does this close out https://github.com/cockroachdb/cockroach/issues/121300 and https://github.com/cockroachdb/cockroach/issues/135905?

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136234)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/catalog/internal/catkv/system_database_cache.go` line 90 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/136234#-OCeVSnF8VqJtysB4bqD:-OCeVSnF8VqJtysB4bqE:blot1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d6dbb62ce07c677490d03adab494d91bc37dbab/pkg/sql/catalog/internal/catkv/system_database_cache.go#L90)):*
> ```Go
> 	version clusterversion.ClusterVersion, key descpb.NameInfo,
> ) (descpb.ID, hlc.Timestamp) {
> 	// TODO: Refactor this a bit.
> ```

nit: can this comment provide a clue as to what we'd like to refactor?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136234)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/catalog/internal/catkv/system_database_cache.go` line 90 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/136234#-OCeVSnF8VqJtysB4bqD:-OCiJZbx6pj4b6rC2BvX:bfbdfie) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d6dbb62ce07c677490d03adab494d91bc37dbab/pkg/sql/catalog/internal/catkv/system_database_cache.go#L90)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: can this comment provide a clue as to what we'd like to refactor?
</blockquote></details>

Oops, that was a left-over comment. This commit already does the refactoring. Good catch!

**Comment by mgartner** [comment]
> does this close out https://github.com/cockroachdb/cockroach/issues/121300 and https://github.com/cockroachdb/cockroach/issues/135905?

Yes, it fixes both of them. I've added them to the PR description. Thanks for finding those!

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
