### PR TITLE
colexec: aggregator accounting fix and performance optimizations

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: fix wrong usage of pointer when getting the size of a struct**

I mistakenly used `unsafe.SizeOf(&aggFuncStruct{})` when calculating the
size of the struct, and as a result, the sizes were all 8 bytes, but
they should have been higher. This fixed the discrepancy I saw in the
heap profiles and reported usage to bytes monitor.

Addresses: #48428.

Release note: None

**colexec: put aggregate funcs in a separate file**

This is just code movement and some files' renaming.

Release note: None

**colexec: introduce aggregate function allocator**

This commit introduces an aggregate functions allocator object that
supports an arbitrary function schema as well as a single aggregate
function alloc that pools allocations of the same statically-typed
aggregate function. All of these objects support arbitrary allocation
size, so ordered aggregator sets it to 1 whereas hash aggregator sets it
to 64.

Release note: None

**colexec: pool allocations of slices of pointers in hash aggregator**

This gives modest (5% or so) improvements on microbenchmarks when group
sizes are small.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
This PR (namely the third commit) shows nice performance improvements [here](https://gist.github.com/yuzefovich/f7d5f9a4b5d94c66daa0245fe78fd672), somewhat surprisingly to me that gains are present on ordered aggregator as well.

**Comment by yuzefovich** [comment]
Fourth commit improvement is [here](https://gist.github.com/yuzefovich/cd11b94be03b8b8d2a82409b1335d486).

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 7 of 7 files at r1, 3 of 3 files at r2, 9 of 9 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49102#-:-M7cKz-V9gDH2Tga1fl3:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
