### PR TITLE
explain: warn in EXPLAIN ANALYZE when estimate for scans is inaccurate

### LINKED ISSUE #86578: EXPLAIN ANALYZE should detect stale stats and print a warning message
**Is your feature request related to a problem? Please describe.**
A common cause of poor query plan selection by the optimizer is stale table statistics, which can often be detected by observing a large difference between the estimated and actual row count of Scan operations in the statement bundle generated by EXPLAIN ANALYZE(DEBUG). The solution is often just to recollect statistics on the table. Support escalations could be avoided by making this solution more obvious.

**Describe the solution you'd like**
Update the EXPLAIN ANALYZE(DEBUG) statement to print a warning message indicating tables which have a large difference between the estimated and actual row counts in scan operations, with a suggestion that statistics should be recollected on those tables.

**Describe alternatives you've considered**
Instead of updating EXPLAIN ANALYZE(DEBUG), print the warning message after actual execution of the query with the stats recollection recommendation. 

**Additional context**
N/A

Jira issue: CRDB-18825

### PR DESCRIPTION
**Pull request by yuzefovich**
**explain: remove a couple of functions only used in tests**

This commit removes a couple of functions that are now only used in
tests. (Previously, we did use them in the production code, but that
changed at the end of 2020.)

Release justification: low-risk cleanup.

Release note: None

**explain: warn in EXPLAIN ANALYZE when estimate for scans is inaccurate**

This commit adds the logic to check whether the estimated row count is
inaccurate in comparison to the actual row count and adds a warning for
scan nodes. (We only do this for scans because for other nodes the
estimates can be quite wrong.) The estimate is deemed "inaccurate" if it
is off by at least a factor of 2 and a fixed offset of 100. The warning
also includes a suggestion to manually run `ANALYZE <table name>` to
collect the stats since the inaccurate estimate is most likely due to
stale stats.

The warnings are added in line with the scan nodes as well as separately
at the end of the EXPLAIN ANALYZE output (but before the index
recommendations if any) to make them more visible. In addition, all
warnings are printed out in the CLI for EXPLAIN ANALYZE (DEBUG) so that
our TSEs got hints at what could be the problem.

Fixes: #86578

Release justification: low-risk improvement.

Release note (sql change): EXPLAIN ANALYZE output now contains a warning
when the estimated row count for scans is inaccurate and includes a hint
to collect the table statistics manually.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
There are some questions to consider:
- do we want this warning to be printed for any node or only for scans? My understanding is that for scans we expect estimates to be quite precise, but for others they might be wrong.
- do we want to allow a small fixed offset in the check? For example, `4*x + 4 < y || 4*y + 4 < x` - this could hide some of the warning when the estimate or the actual row count was zero.
- does the multiple of four sound good?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-:-NAAc-LhEBjliirs9wJL:bbntrjg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @rytaft)

**Review by rytaft — COMMENTED** [review]
Nice! 

> do we want this warning to be printed for any node or only for scans? My understanding is that for scans we expect estimates to be quite precise, but for others they might be wrong.

Yea, we should only print the warning for scans

> do we want to allow a small fixed offset in the check? For example, 4*x + 4 < y || 4*y + 4 < x - this could hide some of the warning when the estimate or the actual row count was zero.

Sounds like a good idea, although I'm not sure what the offset should be. Maybe 10?

> does the multiple of four sound good?

I think we could even do 2. That would fit with the 1.9 q-error threshold (comment from `stats_tester.go`):
```
// qErr calculates the q-error for the given estimated and actual values.
// q-error is symmetric and multiplicative, and satisfies the formula:
//
//   (1/q) * actual <= estimated <= q * actual
//
// A q-error of 1 is a perfect estimate, and a q-error <= 1.9 is considered
// acceptable.
//
// We use q-error because it is a better predictor of plan quality than
// other error metrics. See "Preventing Bad Plans by Bounding the Impact of
// Cardinality Estimation Errors" by Moerkotte et al. for details.
```

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-:-NABi9uYAPMnPZGoCZbZ:bka7p52)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @yuzefovich)

___
*[`pkg/sql/opt/exec/explain/emit.go` line 382 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-NABjfMGBikioL6gk-E0:-NABhGyO3Kd4YBJGtNcW:b-m7zqaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/29680e629224bf8148ae88920eca6312d8ab68a1/pkg/sql/opt/exec/explain/emit.go#L382)):*
> ```Go
> }
> 
> const staleStatsWarning = "  ----------------------  WARNING: the estimate is way off, consider manually collecting table stats"
> ```

nit: "way off" seems a bit informal. Maybe just "inaccurate"? And maybe just say `"ANALYZE " + tableName` since people may not know how to manually collect stats?

**Review by michae2 — COMMENTED** [review]
This is genius!

>> do we want to allow a small fixed offset in the check? For example, 4x + 4 < y || 4y + 4 < x - this could hide some of the warning when the estimate or the actual row count was zero.
> 
> Sounds like a good idea, although I'm not sure what the offset should be. Maybe 10?

I think the fixed offset should be more like 1000 or 10000. A 10 row difference isn't going to hurt anything. For example, in the two recent issues it was 445,439 actual rows vs 0 estimated and 212,147 actual vs 11 estimated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-:-NABqqgG2fJPPfmpRSbk:b-o9v5mp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @yuzefovich)

**Review by msirek — COMMENTED** [review]
Cool! Quick turnaround time.  Regarding a fixed offset, if the scan is an input to a lookup join, a bad estimate could have a magnifying effect if the lookups are costly, so we might not want to set too high of an offset.  For example, the difference of scanning 1 row vs 1000 rows might not be too costly, but doing 1 lookup vs. 1000 lookups might be.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-:-NABuExZ8PHMe43NaX1e:b-kuh57t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/sql/opt/exec/explain/emit.go` line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-NABt7wI3tV9LC1yPwXp:-NABt7wI3tV9LC1yPwXq:bh6q4gt) ([raw file](https://github.com/cockroachdb/cockroach/blob/29680e629224bf8148ae88920eca6312d8ab68a1/pkg/sql/opt/exec/explain/emit.go#L451)):*
> ```Go
> 			minEstimatedRowCount := uint64(math.Ceil(math.Min(s.LimitHint, s.RowCount)))
> 			estimatedRowCountString = fmt.Sprintf("%s - %s", humanizeutil.Count(minEstimatedRowCount), humanizeutil.Count(maxEstimatedRowCount))
> 			if hasActualRowCount && s.TableStatsAvailable {
> ```

It may be just as important to recommend stats collection when there are no existing stats. So, in addition to a stale stats message, maybe a missing stats message could be displayed.  If in the future we tracked estimated and actual elapsed time, then maybe the message could be suppressed if actual time were close to estimated time.



_Code quote:_
```Go
emitNodeAttributes
```

**Review by yuzefovich — COMMENTED** [review]
So I switched the inaccurate range to use a factor of 2 and a fixed offset of 100 and added the warning only to scans.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-:-NABxs0Q5jlNjPH38x6o:b-feggil)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @rytaft)

___
*[`pkg/sql/opt/exec/explain/emit.go` line 382 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-NABjfMGBikioL6gk-E0:-NABsOtBA-segidC10yi:b-nu0rul) ([raw file](https://github.com/cockroachdb/cockroach/blob/29680e629224bf8148ae88920eca6312d8ab68a1/pkg/sql/opt/exec/explain/emit.go#L382)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: "way off" seems a bit informal. Maybe just "inaccurate"? And maybe just say `"ANALYZE " + tableName` since people may not know how to manually collect stats?
</blockquote></details>

Good point, done. This is how it would look like
```
  actual row count: 1
  KV time: 0µs
  KV contention time: 0µs
  KV rows read: 1
  KV bytes read: 8 B
  KV gRPC calls: 1
  estimated max memory allocated: 0 B
  estimated row count: 0
  table: ab@ab_pkey  ----------------------  WARNING: the estimate is inaccurate, consider running 'ANALYZE ab'
```
___
*[`pkg/sql/opt/exec/explain/emit.go` line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-NABt7wI3tV9LC1yPwXp:-NAByBA45ZW10SO6zMwa:buqykv) ([raw file](https://github.com/cockroachdb/cockroach/blob/29680e629224bf8148ae88920eca6312d8ab68a1/pkg/sql/opt/exec/explain/emit.go#L451)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

It may be just as important to recommend stats collection when there are no existing stats. So, in addition to a stale stats message, maybe a missing stats message could be displayed.  If in the future we tracked estimated and actual elapsed time, then maybe the message could be suppressed if actual time were close to estimated time.
</blockquote></details>

We already add "missing stats" annotation for scans when stats weren't available. Do you think we want to highlight it more?

**Review by michae2 — APPROVED** [review]
:lgtm: Very nice!

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-:-NAC-gdq2aRtnZHHg1i9:b-kerl87)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek and @rytaft)

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86677)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek, @rytaft, and @yuzefovich)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/prepare` line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-NABy-SGCDwznZMNdULC:-NABy-SGCDwznZMNdULD:b-qdkgm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/29680e629224bf8148ae88920eca6312d8ab68a1/pkg/sql/opt/exec/execbuilder/testdata/prepare#L133)):*
> ```
>   KV gRPC calls: 1
>   estimated max memory allocated: 0 B
>   estimated row count: 0  ----------------------  WARNING: the estimate is way off, consider manually collecting table stats
> ```

Is it possible to show these warnings in the EXPLAIN ANALYZE(DEBUG) case (in the SQL client, without opening the statement bundle)?  Or maybe collect them all in a warnings README file in the statement bundle?  The more prominent the warnings are, the less likely a support ticket would get escalated.  Even in the non-DEBUG case, if the query plan is long, it may be easier to notice the warnings if they were also displayed in the summary section which includes planning time, execution time, etc.

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86677)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[`pkg/sql/opt/exec/explain/emit.go` line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-NABt7wI3tV9LC1yPwXp:-NAC0-zg3f27mJzB2CTu:b-5bmw72) ([raw file](https://github.com/cockroachdb/cockroach/blob/29680e629224bf8148ae88920eca6312d8ab68a1/pkg/sql/opt/exec/explain/emit.go#L451)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

We already add "missing stats" annotation for scans when stats weren't available. Do you think we want to highlight it more?
</blockquote></details>

Maybe if those were also included in the summary section (see other comment), and/or also labeled with a WARNING message they might stand out more.  Also, the single-table case is less interesting than multi-table join cases.  I don't know if we'd like to detect when we have both stale/missing stats and also the presence of joins, and print something like, "Warning: stale statistics detected!  Query plan may be suboptimal."

**Review by rytaft — COMMENTED** [review]
Is there any way you can add a test case for this?

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-:-NAC2YVVEgs6ODo6Vcna:b-bizae1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/sql/opt/exec/explain/emit.go` line 382 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-NABjfMGBikioL6gk-E0:-NAC2LH83dLzrUj10jHw:b-47fafm) ([raw file](https://github.com/cockroachdb/cockroach/blob/29680e629224bf8148ae88920eca6312d8ab68a1/pkg/sql/opt/exec/explain/emit.go#L382)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Good point, done. This is how it would look like
```
  actual row count: 1
  KV time: 0µs
  KV contention time: 0µs
  KV rows read: 1
  KV bytes read: 8 B
  KV gRPC calls: 1
  estimated max memory allocated: 0 B
  estimated row count: 0
  table: ab@ab_pkey  ----------------------  WARNING: the estimate is inaccurate, consider running 'ANALYZE ab'
```
</blockquote></details>

looks good

**Review by yuzefovich — COMMENTED** [review]
> Is there any way you can add a test case for this?

Yeah, currently working on this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-:-NAC2ntf-NK1CRnfhRTb:b-qfiat4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/prepare` line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-NABy-SGCDwznZMNdULC:-NAC2r5C6_lixAjmmXW-:bdodaq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/29680e629224bf8148ae88920eca6312d8ab68a1/pkg/sql/opt/exec/execbuilder/testdata/prepare#L133)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Is it possible to show these warnings in the EXPLAIN ANALYZE(DEBUG) case (in the SQL client, without opening the statement bundle)?  Or maybe collect them all in a warnings README file in the statement bundle?  The more prominent the warnings are, the less likely a support ticket would get escalated.  Even in the non-DEBUG case, if the query plan is long, it may be easier to notice the warnings if they were also displayed in the summary section which includes planning time, execution time, etc.  
</blockquote></details>

It's an interesting idea, I'll see what we can do.
___
*[`pkg/sql/opt/exec/explain/emit.go` line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-NABt7wI3tV9LC1yPwXp:-NAC2xW_-dLCGSyMwI2w:bdavkla) ([raw file](https://github.com/cockroachdb/cockroach/blob/29680e629224bf8148ae88920eca6312d8ab68a1/pkg/sql/opt/exec/explain/emit.go#L451)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Maybe if those were also included in the summary section (see other comment), and/or also labeled with a WARNING message they might stand out more.  Also, the single-table case is less interesting than multi-table join cases.  I don't know if we'd like to detect when we have both stale/missing stats and also the presence of joins, and print something like, "Warning: stale statistics detected!  Query plan may be suboptimal."
</blockquote></details>

Interesting idea as well, but I think I'll defer highlighting the missing stats to another PR. I want this PR to be backported and the missing stats update will incur merge conflicts. I'll open up a separate issue for that.

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86677)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/prepare` line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-NABy-SGCDwznZMNdULC:-NAC3e782_c8-KKjxk9S:b-ucfkn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/29680e629224bf8148ae88920eca6312d8ab68a1/pkg/sql/opt/exec/execbuilder/testdata/prepare#L133)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

It's an interesting idea, I'll see what we can do.
</blockquote></details>

Thanks.
___
*[`pkg/sql/opt/exec/explain/emit.go` line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-NABt7wI3tV9LC1yPwXp:-NAC3gCg5auLCz1QOwS2:b32w0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/29680e629224bf8148ae88920eca6312d8ab68a1/pkg/sql/opt/exec/explain/emit.go#L451)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Interesting idea as well, but I think I'll defer highlighting the missing stats to another PR. I want this PR to be backported and the missing stats update will incur merge conflicts. I'll open up a separate issue for that.
</blockquote></details>

OK

**Review by yuzefovich — COMMENTED** [review]
>> Is there any way you can add a test case for this?
> 
> Yeah, currently working on this.

Added tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-:-NACMo1xDK0GdfuOs9L7:b-fmqiuv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2, @msirek, and @rytaft)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/prepare` line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-NABy-SGCDwznZMNdULC:-NACMLsi7TjiY1ociAfq:b-rt8c00) ([raw file](https://github.com/cockroachdb/cockroach/blob/29680e629224bf8148ae88920eca6312d8ab68a1/pkg/sql/opt/exec/execbuilder/testdata/prepare#L133)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Thanks.
</blockquote></details>

Added warnings to the bottom of EXPLAIN ANALYZE output as well as to the CLI output of EXPLAIN ANALYZE (DEBUG). Here is how that looks like:
```
root@127.0.0.1:26257/defaultdb> EXPLAIN ANALYZE (DEBUG) SELECT * FROM warnings;
                                              info
------------------------------------------------------------------------------------------------
  Statement diagnostics bundle generated. Download from the Admin UI (Advanced
  Debug -> Statement Diagnostics History), via the direct link below, or using
  the SQL shell or command line.
  Admin UI: http://127.0.0.1:8080
  Direct link: http://127.0.0.1:8080/_admin/v1/stmtbundle/790471570583224321
  SQL shell: \statement-diag download 790471570583224321
  Command line: cockroach statement-diag download 790471570583224321
  WARNING: the estimate on table "warnings" is inaccurate, consider running 'ANALYZE warnings'
```

**Review by yuzefovich — COMMENTED** [review]
Added empty lines before warning summaries and filed #86721 for the missing stats idea. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-:-NACOggN02MsEsm91FDh:b19393n)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2, @msirek, and @rytaft)

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-:-NACavyJ7fy6PoWcLQ-r:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @msirek and @yuzefovich)

___
*[`-- commits` line 34 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-NACafgTAGSiseeV2GLC):*
nit: could you add an example explain output statement somewhere in this commit?
___
*[`pkg/sql/opt/exec/explain/emit.go` line 554 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-NACaGVy7suzm-FRhwjn:-NACaGVz3knahBmfCIIR:b-mb2y3y) ([raw file](https://github.com/cockroachdb/cockroach/blob/558d8d92b1d319c9860ff0536bddd18def96d72b/pkg/sql/opt/exec/explain/emit.go#L554)):*
> ```Go
> 			)
> 			ob.AddWarning(fmt.Sprintf(
> 				"WARNING: the estimate on table %[1]q is inaccurate, "+
> ```

nit: maybe say "the row count estimate" instead of "the estimate"?

**Review by msirek — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-:-NAFK8Y45EP_eJxkrxAF:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 1 stale) (waiting on @msirek and @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-:-NAFNPl76BfDQZUFxjAl:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @msirek and @rytaft)

___
*[`-- commits` line 34 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86677#-NACafgTAGSiseeV2GLC):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: could you add an example explain output statement somewhere in this commit?
</blockquote></details>

Done.

**Comment by yuzefovich** [comment]
This needs a rebase.

bors r-

**Pull request merged**
