### PR TITLE
distsql: support tuples

### PR DESCRIPTION
**Pull request by rjnn**
Release note (feature): using tuples in a query no longer reverts you
to single node local SQL execution.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Nice to close on this. What is the versioning story? Seems like we should at least bump the distsql version no?

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/util/encoding/encoding.go, line 2189 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDDXk8a6xAJ_63zAwwR:-LDDXk8a6xAJ_63zAwwS:bb75yva) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d28ed00c34e0ca348a27655f7a2ac451c058c86/pkg/util/encoding/encoding.go#L2189)):*
> ```Go
> 
> func getTupleKeyLength(buf []byte) (int, error) {
> 	return 0, errors.Errorf("TODO(donotmerge)")
> ```

WIP?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-:-LDDY0QwDjXvsHxnfCfA:b9tij4n)*

**Comment by arjunravinarayan** [comment]
Good point, this requires a version bump. Added.

---

Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/util/encoding/encoding.go, line 2189 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDDXk8a6xAJ_63zAwwR:-LDD_keAEswXvBS1G-vP:bc0rqyv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d28ed00c34e0ca348a27655f7a2ac451c058c86/pkg/util/encoding/encoding.go#L2189)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

WIP?
</blockquote></details>

Removed. Cruft code that wasn't used. Thanks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-:-LDD_nvH4KkJz60aOewX:bt1s72r)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[pkg/sql/sqlbase/table.go, line 1436 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDDbBvPDgKkRr0lV1ng:-LDDbBvPDgKkRr0lV1nh:bnbkpc5) ([raw file](https://github.com/cockroachdb/cockroach/blob/219bc8b4b5389487538a1e74f685b16d14c4593d/pkg/sql/sqlbase/table.go#L1436)):*
> ```Go
> 		return a.NewDOid(tree.MakeDOid(tree.DInt(i))), rkey, err
> 	default:
> 		if t, ok := valType.(types.TCollatedString); ok {
> ```

[nit] this block could be moved to a second `switch t := valType.(type)`

---

*[pkg/sql/sqlbase/testutils.go, line 119 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDDgtShAgCUBR0U6WhM:-LDDgtShAgCUBR0U6WhN:b8cu0kd) ([raw file](https://github.com/cockroachdb/cockroach/blob/219bc8b4b5389487538a1e74f685b16d14c4593d/pkg/sql/sqlbase/testutils.go#L119)):*
> ```Go
> 	case ColumnType_TUPLE:
> 		// TODO(arjun)
> 		return tree.DNull
> ```

This violates `nullOk`, surprising it doesn't break something

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-:-LDDh24F56WOKh2_ee4s:bnfp4nl)*

**Comment by jordanlewis** [comment]
I think this needs some testing. I would recommend adding tests to `encoding.go`, alongside the tests like `TestValueEncodeDecodeBytes` and so forth, following the pattern of encoding random tuples, decoding them, and asserting that the output's equal to the input.

---

Review status: 0 of 14 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/sem/tree/format_test.go, line 197 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDDlhdp3-E6E-wXv0aF:-LDDlhdp3-E6E-wXv0aG:b-lcflpu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cd2d05f31c591162dd9711fa2f26a4e601b4c70/pkg/sql/sem/tree/format_test.go#L197)):*
> ```Go
> 		{`sqrt(123.0) + 456`, tree.FmtParsable,
> 			`sqrt(123.0:::DECIMAL) + 456:::DECIMAL`},
> 		{`row()`, tree.FmtParsable, `row()`},
> ```

this might need to be ROW() since we explicitly output that as the string.

---

*[pkg/sql/sqlbase/encoded_datum.go, line 142 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDDlrN9B8UMLXvRqRaj:-LDDlrN9B8UMLXvRqRak:bja6p0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0c6e90be8e6ecef934ba59f5a16069356584d0b/pkg/sql/sqlbase/encoded_datum.go#L142)):*
> ```Go
> 		panic(fmt.Sprintf("invalid datum type given: %s, expected %s",
> 			d.ResolvedType(), ptyp))
> 	}
> ```

Why did you remove this?

---

*[pkg/sql/sqlbase/encoded_datum.go, line 202 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDDluE174bpqoH8QFui:-LDDluE174bpqoH8QFuj:b56dd9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cd2d05f31c591162dd9711fa2f26a4e601b4c70/pkg/sql/sqlbase/encoded_datum.go#L202)):*
> ```Go
> 	}
> 	if err != nil {
> 		return errors.Wrapf(err, "error decoding % bytes", len(ed.encoded))
> ```

This format string probably should be %d :)

---

*[pkg/sql/sqlbase/table.go, line 1449 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDDmbog9UwNF09h1bWO:-LDDmbog9UwNF09h1bWP:bfv9rbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cd2d05f31c591162dd9711fa2f26a4e601b4c70/pkg/sql/sqlbase/table.go#L1449)):*
> ```Go
> 			for i, tupleType := range tupleTypes.Types {
> 				var err error
> 				dtuple.D[i], rkey, err = DecodeTableKey(a, tupleType, rkey, dir)
> ```

I'm confused about how this works. You encode with `EncodeTableValue` but decode with `DecodeTableKey`. How is this possible?

Now that I think about it, is this code even used? We never encode tuple types with key encoding. I have a feeling this stanza is dead code. If not, I'd love to know why it isn't

---

*[pkg/sql/sqlbase/table.go, line 1678 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDDoqlDDiUPsmQNlHBw:-LDDoqlDDiUPsmQNlHBx:b-g5iv2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cd2d05f31c591162dd9711fa2f26a4e601b4c70/pkg/sql/sqlbase/table.go#L1678)):*
> ```Go
> 			return decodeArray(a, typ.Typ, buf)
> 		case types.TTuple:
> 			return decodeTuple(a, typ, buf[1:])
> ```

why is this `buf[1:]`? what byte gets eaten? we don't seem to do that elsewhere.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-:-LDDpt1-ChilB6_5TRja:b-im313d)*

**Comment by petermattis** [comment]
Review status: 0 of 14 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/sql/sqlbase/table.go, line 731 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDM_q488cDrsQif7jIm:-LDM_q488cDrsQif7jIn:b7y9cb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1919c1c54b5d287da9fd03adaaca1c0a5d3d1b64/pkg/sql/sqlbase/table.go#L731)):*
> ```Go
> 	case *tree.DTuple:
> 		scratch = scratch[0:0]
> 		// TODO(arjun): How do we eliminate this allocation?
> ```

Be kind to your future self and specify which allocation you're concerned about eliminating. 

Seems like you're encoding a `TupleValue` as an encoded tuple that is then encoded again similarly to a bytes value. Did you consider the alternative of encoding a tuple value as a tag, a count of the number of items in the tuple and then the individual tuple values? I think with that encoding you'd be able to encode the tuple values directly into `appendTo`. Something like:

```
appendTo = encoding.EncodeValueTag(appendTo, uint32(colID), encoding.Tuple)
appendTo = encoding.EncodeNonsortingUvarint(appendTo, len(t.D))
for _, dd := range t.D {
  var err error
  appendTo, err = EncodeTableValue(appendTo, ColumnID(encoding.NoColumnID), dd, scratch)
  if err != nil {
    return nil, err
  }
}
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25860)*

**Comment by arjunravinarayan** [comment]
*[pkg/sql/sqlbase/table.go, line 1559 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDhZXp-6pcVDrtxVsVK:-LDhcsbc8DCW_9gJSy-y:bj419nn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff461611e980f3ad4e2a5c1a715c7e4d1b93e026/pkg/sql/sqlbase/table.go#L1559)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Do we need to add `DatumAlloc.dtupleAlloc []tree.DTuple`?
</blockquote></details>

Sure, but the main allocation is the below line with `make([]tree.Datum` and that's hard to pre-allocate. Any thoughts on batching those allocations?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25860)*

**Comment by petermattis** [comment]
Review status: 0 of 15 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/sqlbase/table.go, line 1559 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDhZXp-6pcVDrtxVsVK:-LDhdVHDCt8sQT2vFNt9:b-vukpdf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff461611e980f3ad4e2a5c1a715c7e4d1b93e026/pkg/sql/sqlbase/table.go#L1559)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Sure, but the main allocation is the below line with `make([]tree.Datum` and that's hard to pre-allocate. Any thoughts on batching those allocations?
</blockquote></details>

`DatumAlloc.datumAlloc []tree.Datum`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25860)*

**Comment by arjunravinarayan** [comment]
Review status: 0 of 15 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[pkg/sql/sqlbase/table.go, line 1559 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDhZXp-6pcVDrtxVsVK:-LDhn7z_DfRgqKwAXhk0:bns9upf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff461611e980f3ad4e2a5c1a715c7e4d1b93e026/pkg/sql/sqlbase/table.go#L1559)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`DatumAlloc.datumAlloc []tree.Datum`?
</blockquote></details>

I did both. The latter feels hacky, but not much more hacky than the existing `DatumAlloc` stuff.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25860)*

**Comment by petermattis** [comment]
Review status: 0 of 15 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/sqlbase/table.go, line 1559 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDhZXp-6pcVDrtxVsVK:-LDhydNuAhRhbvGwUmWC:bu2dfjr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff461611e980f3ad4e2a5c1a715c7e4d1b93e026/pkg/sql/sqlbase/table.go#L1559)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

I did both. The latter feels hacky, but not much more hacky than the existing `DatumAlloc` stuff.
</blockquote></details>

Seems ok to me. 

---

*[pkg/sql/sqlbase/table.go, line 1102 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDhyTN40HkmwGcCChGl:-LDhyTN55a-aHMKLhSNa:b-jvhaqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e12e2cfa49988cc7702bd25456dbf36579e8d75/pkg/sql/sqlbase/table.go#L1102)):*
> ```Go
> 		*buf = make(tree.Datums, extensionSize)
> 	}
> 	r := (*buf)[0:num]
> ```

Nit: the `0` isn't necessary. This could be `(*buf)[;num]`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25860)*

**Comment by arjunravinarayan** [comment]
Review status: 0 of 16 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[pkg/sql/sqlbase/table.go, line 1449 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDDmbog9UwNF09h1bWO:-LDmx-l-Cz_-kTjmTdR2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cd2d05f31c591162dd9711fa2f26a4e601b4c70/pkg/sql/sqlbase/table.go#L1449)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

:scream_cat: You are right! Will fix.
</blockquote></details>

Done.

---

*[pkg/sql/sqlbase/table.go, line 1559 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDhZXp-6pcVDrtxVsVK:-LDmwSi77x1m81Y4JIa7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff461611e980f3ad4e2a5c1a715c7e4d1b93e026/pkg/sql/sqlbase/table.go#L1559)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Seems ok to me. 
</blockquote></details>

Done.

---

*[pkg/sql/sqlbase/table.go, line 1102 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDhyTN40HkmwGcCChGl:-LDmw_8w9cIsQuuvuSCd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e12e2cfa49988cc7702bd25456dbf36579e8d75/pkg/sql/sqlbase/table.go#L1102)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: the `0` isn't necessary. This could be `(*buf)[;num]`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25860)*

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/sqlbase/table.go, line 1099 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDqha4D4mwwVTQP_tR6:-LDqha4D4mwwVTQP_tR7:b-9oaw4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d3fe195217dcf45f526f38ad29b4a524ee5d6/pkg/sql/sqlbase/table.go#L1099)):*
> ```Go
> 		extensionSize := datumAllocSize
> 		if extensionSize < num*datumAllocMultiplier {
> 			extensionSize = num * datumAllocMultiplier
> ```

mega nit: save the result of num*datumAllocMultipler so you don't have to put it twice

---

*[pkg/sql/sqlbase/table.go, line 1576 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDqvlWjE6dF4_E_WVTw:-LDqvlWjE6dF4_E_WVTx:b-ephz2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d3fe195217dcf45f526f38ad29b4a524ee5d6/pkg/sql/sqlbase/table.go#L1576)):*
> ```Go
> 	}
> 	if int(l) != len(elementTypes.Types) {
> 		// This is permissible only if the top level value is NULL
> ```

I don't understand what's going on here. What is the top level value you are referring to?

Also, when would this ever happen? This is saying that it's possible for the encoded number of elements (`l`) to differ from the number of expected type slots. I don't see how this has anything to do with NULL.

---

*[pkg/sql/sqlbase/table.go, line 1582 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDqxHTI9XnrKHlyJCdy:-LDqxHTI9XnrKHlyJCdz:bht6k45) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d3fe195217dcf45f526f38ad29b4a524ee5d6/pkg/sql/sqlbase/table.go#L1582)):*
> ```Go
> 			return nil, nil, err
> 		}
> 		if int(l) == 1 && datum == tree.DNull {
> ```

Ah, so this is a special case for size-1 tuples that contain only null? Still, I don't understand why this would trigger a problem, and wouldn't for a size-n tuple that contains intermittent nulls, for example.

---

*[pkg/util/encoding/encoding.go, line 1060 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDqxjvq7To6_FY4Pg0q:-LDqxjvq7To6_FY4Pg0r:bwa5u7k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d3fe195217dcf45f526f38ad29b4a524ee5d6/pkg/util/encoding/encoding.go#L1060)):*
> ```Go
> 	// manipulation in EncodeValueTag.
> 	SentinelType Type = 15 // Used in the Value encoding.
> 	JSON         Type = iota
> ```

do you need to re-iota here?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25860)*

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/sqlbase/encoded_datum_test.go, line 486 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDqz7uS747urruhpP1n:-LDqz7uS747urruhpP1o:b-1ux4ir) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d3fe195217dcf45f526f38ad29b4a524ee5d6/pkg/sql/sqlbase/encoded_datum_test.go#L486)):*
> ```Go
> }
> 
> func TestValueEncodeDecodeTuple(t *testing.T) {
> ```

Also sorry for not catching this sooner but this test belongs in encoding_test.go with all of the other tests that do this kind of thing.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25860)*

**Comment by arjunravinarayan** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/sql/sqlbase/encoded_datum_test.go, line 486 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDqz7uS747urruhpP1n:-LDrFnmN-Rh8oeVJewrw:b65g5hu) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d3fe195217dcf45f526f38ad29b4a524ee5d6/pkg/sql/sqlbase/encoded_datum_test.go#L486)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Also sorry for not catching this sooner but this test belongs in encoding_test.go with all of the other tests that do this kind of thing.
</blockquote></details>

It can't be in `encoding_test` because tuples fundamentally need to reflect on the type information, which is in `sqlbase`. You can't refer to `sqlbase` from `encoding`.

---

*[pkg/util/encoding/encoding.go, line 1060 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDqxjvq7To6_FY4Pg0q:-LDrG-7YBmis2q6Y47TY:b-4u2iw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d3fe195217dcf45f526f38ad29b4a524ee5d6/pkg/util/encoding/encoding.go#L1060)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

do you need to re-iota here?
</blockquote></details>

I needed to, empirically, as otherwise the value of `Tuple` was equal to the value of `JSON`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25860)*

**Comment by petermattis** [comment]
Review status: 14 of 17 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/util/encoding/encoding.go, line 1060 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDqxjvq7To6_FY4Pg0q:-LDrP2sP-MRM8JaYtCyu:b3ynh5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d3fe195217dcf45f526f38ad29b4a524ee5d6/pkg/util/encoding/encoding.go#L1060)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

I needed to, empirically, as otherwise the value of `Tuple` was equal to the value of `JSON`.
</blockquote></details>

I don't think the comments here does justice to the requirement: we can't change any of these values. I think it would be worthwhile to replace the use of `iota` with explicitly listing the values. That is:

```
const (
  Unknown Type = 0
  Null Type = 1
  NotNull Type = 2
...
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25860)*

**Comment by arjunravinarayan** [comment]
*[pkg/util/encoding/encoding.go, line 1060 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDqxjvq7To6_FY4Pg0q:-LDrPnky9qp2ZWLqhAcW:b-aima4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d3fe195217dcf45f526f38ad29b4a524ee5d6/pkg/util/encoding/encoding.go#L1060)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I don't think the comments here does justice to the requirement: we can't change any of these values. I think it would be worthwhile to replace the use of `iota` with explicitly listing the values. That is:

```
const (
  Unknown Type = 0
  Null Type = 1
  NotNull Type = 2
...
```
</blockquote></details>

I agree; I will do so in this PR. And it needs to be moved to a proto in a subsequent PR. I've already lost hours.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25860)*

**Comment by arjunravinarayan** [comment]
Review status: 14 of 17 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/sqlbase/table.go, line 1099 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDqha4D4mwwVTQP_tR6:-LDrYyrG-_lxeHFgp87j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d3fe195217dcf45f526f38ad29b4a524ee5d6/pkg/sql/sqlbase/table.go#L1099)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

mega nit: save the result of num*datumAllocMultipler so you don't have to put it twice
</blockquote></details>

Done.

---

*[pkg/sql/sqlbase/table.go, line 1576 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDqvlWjE6dF4_E_WVTw:-LDraqxm5zl7-QExYzan:b-7ew21k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d3fe195217dcf45f526f38ad29b4a524ee5d6/pkg/sql/sqlbase/table.go#L1576)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I don't understand what's going on here. What is the top level value you are referring to?

Also, when would this ever happen? This is saying that it's possible for the encoded number of elements (`l`) to differ from the number of expected type slots. I don't see how this has anything to do with NULL.


</blockquote></details>

I've removed that comment since it seems to only cause confusion. 

---

*[pkg/sql/sqlbase/table.go, line 1582 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDqxHTI9XnrKHlyJCdy:-LDrax5XDBVxB0S7yR6s:b-g3tev5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d3fe195217dcf45f526f38ad29b4a524ee5d6/pkg/sql/sqlbase/table.go#L1582)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Ah, so this is a special case for size-1 tuples that contain only null? Still, I don't understand why this would trigger a problem, and wouldn't for a size-n tuple that contains intermittent nulls, for example.
</blockquote></details>

So if you are given a `DNull`, that is an acceptable value when you're expecting any Tuple. If you are given `(1, NULL, 'foo')`, that is only an acceptable value when you're expecting a tuple of type `(int, any, string)`. In this case we are only  checking if we are given a `DNull`. In this case, we won't see a tuple encoding header. If we are in the latter scenario, we'd see a tuple encoding header and the normal decoding path would work.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25860)*

**Comment by jordanlewis** [comment]
Review status: 12 of 17 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/sqlbase/table.go, line 1582 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDqxHTI9XnrKHlyJCdy:-LDs64867-4DBqZbnDpY:b-pj6prw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d3fe195217dcf45f526f38ad29b4a524ee5d6/pkg/sql/sqlbase/table.go#L1582)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

So if you are given a `DNull`, that is an acceptable value when you're expecting any Tuple. If you are given `(1, NULL, 'foo')`, that is only an acceptable value when you're expecting a tuple of type `(int, any, string)`. In this case we are only  checking if we are given a `DNull`. In this case, we won't see a tuple encoding header. If we are in the latter scenario, we'd see a tuple encoding header and the normal decoding path would work.
</blockquote></details>

Recapping offline conversation:

This stanza exists to prevent null tuples from being incorrectly decoded. However, this isn't a problem in practice - null values are already decoded separately up in `DecodeTableValue`, which peels off the type byte from an encoding and makes a decision. By the time control is passed to `decodeTuple`, we're 100% positive we're not decoding a NULL tuple.

The tests can be converted to use `EncodeTableValue` and `DecodeTableValue` to get around this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25860)*

**Comment by arjunravinarayan** [comment]
PTAL @jordanlewis 

---

Review status: 12 of 19 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/sql/sqlbase/table.go, line 1582 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-LDqxHTI9XnrKHlyJCdy:-LEAy7x_7vQZZgQe98ew:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d3fe195217dcf45f526f38ad29b4a524ee5d6/pkg/sql/sqlbase/table.go#L1582)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Recapping offline conversation:

This stanza exists to prevent null tuples from being incorrectly decoded. However, this isn't a problem in practice - null values are already decoded separately up in `DecodeTableValue`, which peels off the type byte from an encoding and makes a decision. By the time control is passed to `decodeTuple`, we're 100% positive we're not decoding a NULL tuple.

The tests can be converted to use `EncodeTableValue` and `DecodeTableValue` to get around this.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-:-LEB4Xvn79nUSSzATz6T:b-1fwxf4)*

**Comment by jordanlewis** [comment]
:lgtm: :shipit: 

---

Review status: 12 of 19 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25860#-:-LEBADuy5y3vXprhAWG8:byzm7aw)*

**Comment by arjunravinarayan** [comment]
Build failures seem to be due to newly added logic tests that require `rowsort`. They weren't caught until the rebase. Nice work, bors, caught what would have turned into maddeningly flaky tests.

Will fix and retry.

**Comment by arjunravinarayan** [comment]
The bors is really paying its rent today, found #26402. Will rebase on top of that and retry once that merges.

**Pull request merged**
