### PR TITLE
sql: use IndexFetchSpec in JoinReader

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### descpb: add IndexID to IndexFetchSpec

Release note: None

#### span: make Builder and Splitter without descriptors

Allow creation of span.Builder and span.Splitter without table and
index descriptors.

Release note: None

#### rowexec: move eqCols to hashjoiner

This commit moves eqCols from joinerBase to hashJoiner because that is
the only processor that uses them. This simplifies the initialization
code for other processors.

Release note: None

#### sql: use IndexFetchSpec in JoinReader

This commit changes `JoinReader` to use an `IndexFetchSpec` (plus a
list of family IDs for span splitting) instead of table and index
descriptors.

As part of making this switch, the "internal schema" of the processor
no longer contains all table columns; instead it contains the specific
`FetchedColumns` in the spec. This simplifies both planning and
execution code.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Nice! I'm very happy to see the code in `cfetcher_setup.go` gone. However, there appears to be a regression in that we're using Scans instead of Gets now.

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 5 of 5 files at r3, 20 of 20 files at r4, 23 of 23 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76963#-:-MwdVyi99VAUF2pwgu6k:b-yruiyi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/distsql_physical_planner.go, line 2178 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76963#-MwdQuCA7pIZONbezp4d:-MwdQuCA7pIZONbezp4e:bwobo7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/213fda435d20cf3c63e970778057227d88d3c54e/pkg/sql/distsql_physical_planner.go#L2178)):*
> ```Go
> 	}
> 
> 	// Calculate the output columns from n.cols.
> ```

nit: the comment seems no longer applicable.
___
*[pkg/sql/colexec/colexecspan/span_assembler.go, line 31 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76963#-MwdRjjm6wEoehbeva37:-MwdRjjm6wEoehbeva38:beopdhs) ([raw file](https://github.com/cockroachdb/cockroach/blob/213fda435d20cf3c63e970778057227d88d3c54e/pkg/sql/colexec/colexecspan/span_assembler.go#L31)):*
> ```Go
> // NewColSpanAssembler returns a ColSpanAssembler operator that is able to
> // generate lookup spans from input batches.
> // - neededColOrdsInWholeTable is a set containing the ordinals of all columns
> ```

nit: this should be now removed.
___
*[pkg/sql/opt/exec/execbuilder/testdata/autocommit_nonmetamorphic, line 646 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76963#-MwdV06v1ZUvv5e48LCz:-MwdV06v1ZUvv5e48LD-:b-cd12o9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a217ab45b767581590ebdc3e4436a9dad9ae29da/pkg/sql/opt/exec/execbuilder/testdata/autocommit_nonmetamorphic#L646)):*
> ```
> ----
> dist sender send  r44: sending batch 2 CPut to (n1,s1):1
> dist sender send  r44: sending batch 2 Scan to (n1,s1):1
> ```

This change is suspicious, any idea what this is about? There are similar changes in other files (like `regional_by_row_query_behavior`) where we seem to now have spans with EndKey prompting us to use Scan requests, instead of Gets.
___
*[pkg/sql/opt/exec/execbuilder/testdata/show_trace_nonmetamorphic, line 372 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76963#-MwdVqgh-caprLSLp3A8:-MwdVqgh-caprLSLp3A9:b-tylcfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f4dde2c5fdccf831e1fc4abc210df507350f8fa/pkg/sql/opt/exec/execbuilder/testdata/show_trace_nonmetamorphic#L372)):*
> ```
>   AND message NOT LIKE '%QueryTxn%'
> ----
> dist sender send  r45: sending batch 42 Get to (n1,s1):1
> ```

This is not good.
___
*[pkg/sql/colexec/colexecspan/span_assembler_test.go, line 115 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76963#-MwdTdEhDs-A0lzBbkf2:-MwdTdEhDs-A0lzBbkf3:b-i9e0hn) ([raw file](https://github.com/cockroachdb/cockroach/blob/213fda435d20cf3c63e970778057227d88d3c54e/pkg/sql/colexec/colexecspan/span_assembler_test.go#L115)):*
> ```Go
> 
> 							colBuilder := NewColSpanAssembler(
> 								keys.TODOSQLCodec, testAllocator,
> ```

nit: the only line with two arguments.
___
*[pkg/sql/rowexec/joinerbase_test.go, line 85 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76963#-MwdTnX9ArULJHkoP4-P:-MwdTnX9ArULJHkoP4-Q:b-veafqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f4dde2c5fdccf831e1fc4abc210df507350f8fa/pkg/sql/rowexec/joinerbase_test.go#L85)):*
> ```Go
> 			descpb.InnerJoin,
> 			tc.onExpr,
> 			nil,   /* leftEqColumns */
> ```

nit: this change should be in the third commit.

**Review by RaduBerinde — COMMENTED** [review]
Very nice catch, thank you for your careful review!! I forgot to initialize `SplitFamilyIDs` during planning.

I combed through the test changes now and they are only diagrams, plus a few cases where traces show more decoded columns (these cases are expected if we have an equality key column that is then projected away).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76963#-:-MwdtFM7E4nOmm1G-APt:b-kdl5sq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/opt/exec/execbuilder/testdata/autocommit_nonmetamorphic, line 646 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76963#-MwdV06v1ZUvv5e48LCz:-Mwdui-1BFm3bM_o4mFD:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/a217ab45b767581590ebdc3e4436a9dad9ae29da/pkg/sql/opt/exec/execbuilder/testdata/autocommit_nonmetamorphic#L646)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

This change is suspicious, any idea what this is about? There are similar changes in other files (like `regional_by_row_query_behavior`) where we seem to now have spans with EndKey prompting us to use Scan requests, instead of Gets.
</blockquote></details>

Fixed.
___
*[pkg/sql/opt/exec/execbuilder/testdata/show_trace_nonmetamorphic, line 372 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76963#-MwdVqgh-caprLSLp3A8:-Mwduit56IfV1iFJQjIx:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f4dde2c5fdccf831e1fc4abc210df507350f8fa/pkg/sql/opt/exec/execbuilder/testdata/show_trace_nonmetamorphic#L372)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

This is not good.
</blockquote></details>

Fixed.

**Review by yuzefovich — APPROVED** [review]
I'm assuming you'll squash the fifth commit into the fourth, right?

:lgtm:

> Reviewed 48 of 48 files at r6, 2 of 2 files at r7, 6 of 6 files at r8, 19 of 19 files at r9, 23 of 23 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76963#-:-MwdyLhKBJSETWwg0RiB:b-eryvqz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Comment by RaduBerinde** [comment]
Sure, done.

**Pull request merged**
