### PR TITLE
sql: use adaptive sampling rate for telemetry logging

### LINKED ISSUE #70553: Improve SQL query telemetry collection with an adaptive sampling rate
In the new telemetry logging channel, we should update the sampling rate to ensure we maximize representative data of the customer workload while limiting the volume of data sent through the pipeline  (< 10 events per second per node). 

The proposal is outlined in the following doc: https://docs.google.com/document/d/1evo7ZtZZpsk8hKC888A_8f6dhM_utFCBPoMsWxr5YyA/edit

### PR DESCRIPTION
**Pull request by xinhaoz**
Resolves #70553

Previously, telemetry logging used a configurable QPS threshold
and sampling rate, for which we would log all statements if we
were under the QPS threshold, and then start sampling at the
given rate once at the threshold. Using this technique meant
that we will often see a sharp decreaes in telemetry logging
once the sampling rate increases, as sampling rates would typically
need to be at low values to accomodate a high QPS.

This commit replaces the above technique with an adaptive sampling
rate which merely logs events to telemetry at a maximum frequency.
Rather than relying on QPS, we will simply track when we have
last logged to the telemtry channel, and decide whether or not to
log a given event accordingly.

Release note (sql change): The cluster setting
`sql.telemetry.query_sampling.qps_threshold`, and
`sql.telemetry.query_sampling.sample_rate` have been removed.
A new setting, `sql.telemetry.query_sampling.max_event_frequency`
has been introduced, with default value of 10 events per second.

----------------------------
### roachrod results
cluster created with:
```
roachprod create $CLUSTER -n 4 --gce-machine-type=n1-standard-16
```
results of tpcc 1000
### Telemetry OFF
```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0         151075           21.0     53.9     48.2     67.1    109.1   5905.6  delivery

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0        1509788          209.7     42.7     25.2     39.8     83.9   9663.7  newOrder

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0         151161           21.0      7.8      5.0      7.6     13.6   5905.6  orderStatus

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0        1511404          209.9     22.4     13.6     23.1     46.1   9663.7  payment

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0         151079           21.0     14.2     10.5     17.8     27.3   7247.8  stockLevel

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
 7200.0s        0        3474507          482.6     31.6     19.9     46.1     75.5   9663.7
Audit check 9.2.1.7: PASS
Audit check 9.2.2.5.1: PASS
Audit check 9.2.2.5.2: PASS
Audit check 9.2.2.5.5: PASS
Audit check 9.2.2.5.6: PASS
Audit check 9.2.2.5.3: PASS
Audit check 9.2.2.5.4: PASS

_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
 7200.0s    12581.5  97.8%     42.7     25.2     33.6     39.8     83.9   9663.7
```
#### Telemetry ON
```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0         150953           21.0     61.9     54.5     71.3     96.5   5637.1  delivery

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0        1509498          209.7     36.8     26.2     39.8     60.8   6174.0  newOrder

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0         151110           21.0      9.2      5.5      7.9     14.2   4831.8  orderStatus

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0        1510864          209.8     34.0     14.2     23.1     35.7   8321.5  payment

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0         151026           21.0     17.0     11.5     18.9     29.4   5637.1  stockLevel

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
 7200.0s        0        3473451          482.4     34.6     21.0     46.1     67.1   8321.5
Audit check 9.2.1.7: PASS
Audit check 9.2.2.5.1: PASS
Audit check 9.2.2.5.2: PASS
Audit check 9.2.2.5.3: PASS
Audit check 9.2.2.5.4: PASS
Audit check 9.2.2.5.5: PASS
Audit check 9.2.2.5.6: PASS

_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
 7200.0s    12579.1  97.8%     36.8     26.2     33.6     39.8     60.8   6174.0
```

### CODE REVIEW

**Review by knz — COMMENTED** [review]
I like the simplification.
I understand this does not remove the QPS estimation code yet? If not, please ensure there's a follow-up issue for that.

Also we want the configuration setting to reflect the new purpose. "Rate" is not the right word.

> Reviewed 4 of 4 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70786#-:-MkdAflH2o6XoxXqJD-V:b-h9ap88)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[pkg/sql/telemetry_logging.go, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70786#-MklXETNErnH90dW6CEj:-MklXETO0iEv9GKJre3I:b-4uyn6e) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c7e0848b9b9851ffd3050a7bb2d0980221abb8b/pkg/sql/telemetry_logging.go#L27)):*
> ```Go
> 
> var telemetrySampleRate = settings.RegisterFloatSetting(
> 	"sql.telemetry.query_sampling.sample_rate",
> ```

Please rename this variable and the cluster setting below to reflect its new purpose.
We'll aim for something like "max event frequency" as the configuration knob, and you'll need to invert the value in the code to get a wait delay.

**Review by knz — COMMENTED** [review]
Sorry, I see the QPS estimation code is removed now. My other comments still apply.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70786#-:-MklXVqu1pMGwsy9b85P:bzg12mz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70786)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/sql/telemetry_logging.go, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70786#-MklXETNErnH90dW6CEj:-Mkm1Fye5zp3RzrXxVXv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c7e0848b9b9851ffd3050a7bb2d0980221abb8b/pkg/sql/telemetry_logging.go#L27)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please rename this variable and the cluster setting below to reflect its new purpose.
We'll aim for something like "max event frequency" as the configuration knob, and you'll need to invert the value in the code to get a wait delay.
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70786)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[-- commits, line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70786#-MkmFcBo2fuFwA1WWpSa):*
I don't understand why you changed "query sampling" to "query logging". What was your rationale?

**Comment by xinhaoz** [comment]
___
*[-- commits, line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70786#-MkmFcBo2fuFwA1WWpSa):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't understand why you changed "query sampling" to "query logging". What was your rationale?
</blockquote></details>

Oh, it seemed to reflect the purpose of the setting more, but I'm pretty impartial to either name. Should I change it back?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70786)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[-- commits, line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70786#-MkmFcBo2fuFwA1WWpSa):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Oh, it seemed to reflect the purpose of the setting more, but I'm pretty impartial to either name. Should I change it back?
</blockquote></details>

my thinking is that the term "query logging" implies that we log every query. 
The functionality, here and even with your change, is still sampling-based.

**Comment by xinhaoz** [comment]
___
*[-- commits, line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70786#-MkmFcBo2fuFwA1WWpSa):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

my thinking is that the term "query logging" implies that we log every query. 
The functionality, here and even with your change, is still sampling-based.

</blockquote></details>

Ah, fair enough! I've changed it back now.

**Review by knz — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70786)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

**Review by yuzefovich — COMMENTED** [review]
Looks good!

In terms of benchmarking, you have already run the TPCC with the new change, but we also would like to see the TPCC without the new change. This way we get two sets of results, and we can compare the impact this change has on the TPCC numbers.

> Reviewed 2 of 8 files at r2, 2 of 5 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70786#-:-MkrPriv6ounTvavvhMe:b-79vq83)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[pkg/sql/exec_log.go, line 365 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70786#-MkrO7F37ljlXx4fjdw3:-MkrO7F37ljlXx4fjdw4:b-6t4b86) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca7c7e437c55377eaf8045c89fedd2685c58f69a/pkg/sql/exec_log.go#L365)):*
> ```Go
> 
> 	if telemetryLoggingEnabled {
> 		// We only log to the telemetry channel if enough time has elapsed from the last event emission.
> ```

nit: wrap comments at 80 characters. If you're using GoLand, there is a "Wrap To Column" plugin that is pretty helpful.
___
*[pkg/sql/query_sampling.go, line 44 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70786#-MkrOsYu7JXr7QJoCAJl:-MkrOsYvE3DDkxTeE07S:bddb9sd) ([raw file](https://github.com/cockroachdb/cockroach/blob/150d5b79dc9ac7fc35cca9571304b36c4c690ba7/pkg/sql/query_sampling.go#L44)):*
> ```Go
> 
> var telemetrySmoothingAlpha = settings.RegisterFloatSetting(
> 	"sql.telemetry.query_sampling.smoothing_alpha",
> ```

Removed settings should be added to `retiredSettings` map in `settings/registry.go`.
___
*[pkg/sql/telemetry_logging.go, line 59 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70786#-MkrP9tn6a3kTHJkDxUD:-MkrP9tn6a3kTHJkDxUE:bj58ag4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca7c7e437c55377eaf8045c89fedd2685c58f69a/pkg/sql/telemetry_logging.go#L59)):*
> ```Go
> 
> // NewTelemetryLoggingMetrics returns a new TelemetryLoggingMetrics object.
> func NewTelemetryLoggingMetrics() *TelemetryLoggingMetrics {
> ```

nit: since now this method doesn't do much other than allocate a new struct, I'd just get rid off it entirely.
___
*[pkg/sql/telemetry_logging_test.go, line 119 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70786#-MkrPaqO4FAXh1wJJ-CZ:-MkrPaqO4FAXh1wJJ-C_:b-xyg99g) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca7c7e437c55377eaf8045c89fedd2685c58f69a/pkg/sql/telemetry_logging_test.go#L119)):*
> ```Go
> 			// Even though the queries are executed within the required
> 			// elapsed interval, we should still see that they were all
> 			// logged, we log all statements that are not of type DML.
> ```

super nit: "logged, we log" -> "logged since we log".

**Review by xinhaoz — COMMENTED** [review]
Addressed comments, will update message with results of TPCC with telemetry turned off once the run completes!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70786#-:-MkrdE6XA28qpfca7TGT:b-fnp4ct)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @yuzefovich)

___
*[pkg/sql/exec_log.go, line 365 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70786#-MkrO7F37ljlXx4fjdw3:-MkrbKc_DYrAEVEPkcDG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca7c7e437c55377eaf8045c89fedd2685c58f69a/pkg/sql/exec_log.go#L365)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: wrap comments at 80 characters. If you're using GoLand, there is a "Wrap To Column" plugin that is pretty helpful.
</blockquote></details>

Done.
___
*[pkg/sql/query_sampling.go, line 44 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70786#-MkrOsYu7JXr7QJoCAJl:-MkrcLj82wqelsTfR7Xn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/150d5b79dc9ac7fc35cca9571304b36c4c690ba7/pkg/sql/query_sampling.go#L44)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Removed settings should be added to `retiredSettings` map in `settings/registry.go`.
</blockquote></details>

Done.
___
*[pkg/sql/telemetry_logging.go, line 59 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70786#-MkrP9tn6a3kTHJkDxUD:-MkrcosB75RygVu8z4cO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca7c7e437c55377eaf8045c89fedd2685c58f69a/pkg/sql/telemetry_logging.go#L59)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: since now this method doesn't do much other than allocate a new struct, I'd just get rid off it entirely.
</blockquote></details>

Done.
___
*[pkg/sql/telemetry_logging_test.go, line 119 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70786#-MkrPaqO4FAXh1wJJ-CZ:-MkrcqSuA0mh_i1vBQyi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca7c7e437c55377eaf8045c89fedd2685c58f69a/pkg/sql/telemetry_logging_test.go#L119)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

super nit: "logged, we log" -> "logged since we log".
</blockquote></details>

Done.

**Comment by xinhaoz** [comment]
Description has been updated with a roachprod run, where telemetry is disabled.

**Review by yuzefovich — APPROVED** [review]
Thanks! tpmC doesn't change. :lgtm:

> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70786#-:-Mks3Nbr0LDPmRa7QNIP:b-tddewj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

**Review by maryliag — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 8 files at r2, 4 of 5 files at r3, 2 of 5 files at r4, 4 of 7 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70786#-:-Mks68FG0VSEi5h8_yIz:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @xinhaoz)

**Comment by xinhaoz** [comment]
TFTR!!!
bors r=knz,yuzefovich,maryliag

**Pull request merged**
