### PR TITLE
storage: remove TODO about MaxKeys on MVCCScanOptions

### PR DESCRIPTION
**Pull request by nvb**
This TODO was addressed by #45069.

Release justification: comment only
Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Friendly ping.

**Review by itsbilal — APPROVED** [review]
:lgtm: Sorry for the delay!

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46434#-:-M3g406D3sbURRVnMJKk:b-8yidu2)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
TFTR!

**Pull request merged**
