### PR TITLE
sql: use udf in column default value in new table

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
Informs: https://github.com/cockroachdb/cockroach/issues/87699

**sql: split ColumnDefaultExpr context into more granular ones**
Previously we only have one `ColumnDefaultExpr` context. This is
not enough for the granularity we want to control over UDF use case
allowance because we want to allow UDF in column default for new
tables but not existing tables. We also want allow UDF for
`SET DEFAULT`. To address, this commit split the context into more
granular ones so that we can do better allowance control.

**sql: use UDFs in column DEFAULT of new tables and SET DEFAULT**
Release note (sql change): Previously, we didn't allow using
UDFs in column DEFAULT. This commit adds support for that but
only allows UDFs in column DEFAULT when creating a new table or
doing SET DEFAULT.

**sql: add test cases of renaming a function used in CHECK**
Release note: None

**sql: fix backup and restore to work with UDFs in column DEFAULT**
Release note (enterprise change): previously UDFs can't be referenced
from column DEFAULTs. Now we turned on UDF's usage in DEFAULTs, we need
to teach BACKUP and RESTORE to rewrite UDF ids referenced in column's
DEFAULT expressions. If UDF dependencies are missing and `skip_missing_udfs`
flag is given, the DEFAULT expressions would be dropped during the RESTORE.

### CODE REVIEW

**Comment by chengxiong-ruan** [comment]
This is ready for a look! The failed test should be fixe by https://github.com/cockroachdb/cockroach/pull/97577

**Review by fqazi — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, 65 of 65 files at r2, 73 of 73 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97501)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan)

___
*[`pkg/sql/catalog/funcdesc/func_desc.go` line 589 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97501#-NP3h7XaD-jjokGMN0yP:-NP3h7XaD-jjokGMN0yQ:bqb55k2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad1f18c789d20a583e4028bb1602ac550afbe6d6/pkg/sql/catalog/funcdesc/func_desc.go#L589)):*
> ```Go
> 		if dep == id {
> 			return errors.AssertionFailedf(
> 				"Cannot add dependency from descriptor %d to function %s (%d) because there will be a dependency cycle", id, desc.GetName(), desc.GetID(),
> ```

normally these are all lowercase
___
*[`pkg/sql/catalog/funcdesc/func_desc.go` line 609 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97501#-NP3hMrx69D2g1KtXuG0:-NP3hMrx69D2g1KtXuG1:b-2g2oxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad1f18c789d20a583e4028bb1602ac550afbe6d6/pkg/sql/catalog/funcdesc/func_desc.go#L609)):*
> ```Go
> 	)
> 	sort.Slice(desc.DependedOnBy, func(i, j int) bool {
> 		return desc.DependedOnBy[i].ID < desc.DependedOnBy[j].ID
> ```

Is this always sorted?
___
*[`pkg/sql/schemachanger/scexec/scmutationexec/references.go` line 292 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97501#-NP3i4QY47OPsYAuwF7e:-NP3i4QY47OPsYAuwF7f:b-3n6qfr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad1f18c789d20a583e4028bb1602ac550afbe6d6/pkg/sql/schemachanger/scexec/scmutationexec/references.go#L292)):*
> ```Go
> 	}
> 	var fnIDsInUse catalog.DescriptorIDSet
> 	if !tblDesc.Dropped() {
> ```

Make this an early return, maybe in the checkout above?
___
*[`pkg/sql/schemachanger/scexec/scmutationexec/references.go` line 294 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97501#-NP3iDH19sx8Ke0hiPVP:-NP3iDH19sx8Ke0hiPVQ:bjxq9ug) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad1f18c789d20a583e4028bb1602ac550afbe6d6/pkg/sql/schemachanger/scexec/scmutationexec/references.go#L294)):*
> ```Go
> 	if !tblDesc.Dropped() {
> 		// If table is dropped then there is no functions in use.
> 		fnIDsInUse, err = tblDesc.GetAllReferencedFunctionIDsInColumnExprs(op.BackReferencedColumnID)
> ```

What cleans up the backreferences in the functions? This seems suspicious
___
*[`pkg/sql/logictest/testdata/logic_test/udf` line 557 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97501#-NP3iWPU1AbaUZUqLgIz:-NP3iWPU1AbaUZUqLgJ-:b-lfq4nd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9e513d6f196cbc1c064aaa5c64511249001e582/pkg/sql/logictest/testdata/logic_test/udf#L557)):*
> ```
> 
> statement error pq: unimplemented: usage of user-defined function from relations not supported
> CREATE TABLE test_tbl_t (a INT PRIMARY KEY, b INT DEFAULT (test_tbl_f() + 1));
> ```

Keep these as statement ok?

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97501)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/catalog/funcdesc/func_desc.go` line 589 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97501#-NP3h7XaD-jjokGMN0yP:-NP4sgZ7DjFg0MrklDUI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad1f18c789d20a583e4028bb1602ac550afbe6d6/pkg/sql/catalog/funcdesc/func_desc.go#L589)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

normally these are all lowercase
</blockquote></details>

Done.
___
*[`pkg/sql/catalog/funcdesc/func_desc.go` line 609 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97501#-NP3hMrx69D2g1KtXuG0:-NP4sklrAtBENa8iwAIu:b-9715a8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad1f18c789d20a583e4028bb1602ac550afbe6d6/pkg/sql/catalog/funcdesc/func_desc.go#L609)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Is this always sorted?
</blockquote></details>

yes, but it doesn't have to be.
___
*[`pkg/sql/schemachanger/scexec/scmutationexec/references.go` line 292 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97501#-NP3i4QY47OPsYAuwF7e:-NP4uzrI7jXhhhOuG46c:b-aqnv28) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad1f18c789d20a583e4028bb1602ac550afbe6d6/pkg/sql/schemachanger/scexec/scmutationexec/references.go#L292)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Make this an early return, maybe in the checkout above?
</blockquote></details>

actually can't do that, because if the table is dropped, then we need to remove back references from all functions referenced before, so still need to go through the logic below.
___
*[`pkg/sql/schemachanger/scexec/scmutationexec/references.go` line 294 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97501#-NP3iDH19sx8Ke0hiPVP:-NP4vO5t-iq5W_odTXc-:b-2vvdkg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad1f18c789d20a583e4028bb1602ac550afbe6d6/pkg/sql/schemachanger/scexec/scmutationexec/references.go#L294)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

What cleans up the backreferences in the functions? This seems suspicious
</blockquote></details>

Heh, this method is doing this work. see line 307, `fnDesc.RemoveColumnReference`.
the logic here is that, let say we're dropping a `ColumnDefaultExpression` which uses a list of function IDs.
the function IDs are in the `op` here, but, we need to check if any of these function IDs are still used by other expressions of the column (for example ON UPDATE and Computed column expression we don't support now). If you look at `opgen_column_default_expression.go`, we set the default value expression to `nil` first then we execute this op.
So what we need to drop is the different between functions used in this expression and the functions still being used by other expressions.
Hope this make sense.
___
*[`pkg/sql/logictest/testdata/logic_test/udf` line 557 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97501#-NP3iWPU1AbaUZUqLgIz:-NP4xPwZEZgj4_2_Ughu:bgpjaav) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9e513d6f196cbc1c064aaa5c64511249001e582/pkg/sql/logictest/testdata/logic_test/udf#L557)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Keep these as statement ok?
</blockquote></details>

oh, there is no need to keep them since we have new and better test covering this. Also keep them might break some other tests in this test file (which is trivial to fix though). I'm leaving it as is if you don't feel strongly so.

**Review by fqazi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97501)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan)

___
*[`pkg/sql/schemachanger/scexec/scmutationexec/references.go` line 294 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97501#-NP3iDH19sx8Ke0hiPVP:-NP5JExNDz06Aw0gE7Em:b6tthcu) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad1f18c789d20a583e4028bb1602ac550afbe6d6/pkg/sql/schemachanger/scexec/scmutationexec/references.go#L294)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

Heh, this method is doing this work. see line 307, `fnDesc.RemoveColumnReference`.
the logic here is that, let say we're dropping a `ColumnDefaultExpression` which uses a list of function IDs.
the function IDs are in the `op` here, but, we need to check if any of these function IDs are still used by other expressions of the column (for example ON UPDATE and Computed column expression we don't support now). If you look at `opgen_column_default_expression.go`, we set the default value expression to `nil` first then we execute this op.
So what we need to drop is the different between functions used in this expression and the functions still being used by other expressions.
Hope this make sense.
</blockquote></details>

Ah I mismatched the brackets looking at this.

**Comment by chengxiong-ruan** [comment]
TFTR!
bors r+

**Pull request merged**
