### PR TITLE
Cluster overview fixes

### LINKED ISSUE #4801: ui: cluster graphs should be in order of importance
First pass of guesses are:
1. # of nodes
2. SQL operations/sec
3. Bytes in/out
4. Count of active clients within last 1m
5. Capacity (I think this graph should probably just have the % utilized, instead of utilized and max capacity
6. SQL query latency 

We'll revise after tomorrow's discussion.

### LINKED ISSUE #4802: ui: "latency" graphs should be renamed
"latency" is ambiguous. Possibilities include:
1. Query time
2. SQL query latency

### LINKED ISSUE #4936: ui: make Cluster/Overview graphs more relevant
After our discussion, this is our proposed layout for beta:

Col 1 | Col 2 | Col 3 | Col 4 | Col 5 |
----- | ---- | ---- | ----- | ----
Big number: # of nodes | Gauge: capacity | Graph: SQL latency (p50, p75, p99) | Graph:load / normalized CPU (cluster pain) | Graph: memory average or total memory
Graph: client connections & QPS (on separate axes) | Graph: SQL bytes in/out | Graph: SELECTs | Graph: SQL INSERTs, UPDATES, DELETEs | (something else here?)

### LINKED ISSUE #4955: ui: reorganize Nodes page
- [ ] Remove events tab
- [ ] Remove "Node Overview" subheading
- [ ] Remove graphs on the first page (just keep the nodes table)

### LINKED ISSUE #5102: ui: really weird graph layout
Build sha: 0ed1dcea959db2c68e027cce85e1938631e7a128
see image:
ui

### PR DESCRIPTION
**Pull request by maxlang**
Fix nodes page tabs and stub out nodes graph page
fixes #4955

Fix chart area width
fixes #5102

Add agreed upon charts to cluster overview and fix some minor issues

Fixes #5102
Fixes #4936
Fixes #4801
Fixes #4802

Cluster overview page
screen shot 2016-03-14 at 9 31 42 am

Nodes page
screen shot 2016-03-14 at 9 31 52 am

---

This change is [Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5225)

### CODE REVIEW

**Comment by cuongdo** [comment]
I've given this the best review I can, though my feedback isn't particularly comprehensive due to my lack of familiarity with TypeScript and Stylus.

---

Reviewed 5 of 5 files at r1, 3 of 3 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[ui/styl/partials/layout.styl, line 263 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5225#-KCq7v7m_Pb53cCEg7Fs:-KCq7v7m_Pb53cCEg7Ft:3914411) ([raw file](https://github.com/cockroachdb/cockroach/blob/89ad62cb6ea2102c0f69fd4a35f1d556242b234d/ui/styl/partials/layout.styl#L263)):*
Is this the best fix for the wrapping issue? What if `axesSmall`had a style with the attribute `clear: both`? I'm a little wary of a fixed maximum width that has to exactly fit the graphs, but maybe I worry too much. 

---

*[ui/ts/models/metrics.ts, line 254 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5225#-KCqDTbzumPa6fG9Wg35:-KCqDTbzumPa6fG9Wg36:42251711) ([raw file](https://github.com/cockroachdb/cockroach/blob/af26e9857b0c5b30eb3db81887db050bd5c8e337/ui/ts/models/metrics.ts#L254)):*
Should the `null` default value be `false` instead?

---

*[ui/ts/pages/cluster.ts, line 77 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5225#-KCqBSLqvDS8DIhw8X09:-KCqBSLqvDS8DIhw8X0A:436328446) ([raw file](https://github.com/cockroachdb/cockroach/blob/af26e9857b0c5b30eb3db81887db050bd5c8e337/ui/ts/pages/cluster.ts#L77)):*
Why comment out instead of remove entirely? We have revision control in case you want to restore these later.

---

*[ui/ts/pages/cluster.ts, line 217 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5225#-KCqCPhYTpN87gni8ezV:-KCqCPhYTpN87gni8ezW:751233443) ([raw file](https://github.com/cockroachdb/cockroach/blob/af26e9857b0c5b30eb3db81887db050bd5c8e337/ui/ts/pages/cluster.ts#L217)):*
If it exists in TS, I think using the ternary operator (`? :`) would make the intent a little clearer here. Same comment applies again below.

---

*[ui/ts/pages/nodes.ts, line 315 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5225#-KCq3lZOl5LJz9Ty3mqa:-KCq3lZPgjN1A8WPyWPc:-1756227299) ([raw file](https://github.com/cockroachdb/cockroach/blob/8abc3d3bb9557362cf41e37e5bbac5d1caf95b5b/ui/ts/pages/nodes.ts#L315)):*
incomplete comment?

---

*[ui/ts/pages/nodes.ts, line 316 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5225#-KCq42qvrpkxzE23hrZB:-KCq42qvrpkxzE23hrZC:-1883534090) ([raw file](https://github.com/cockroachdb/cockroach/blob/8abc3d3bb9557362cf41e37e5bbac5d1caf95b5b/ui/ts/pages/nodes.ts#L316)):*
Shouldn't the parameters be reversed?  Also, if the intention is for `/nodes/`(with nothing after it) to go to the overview page, shouldn't this be `if (m.route() == "/nodes/" || m.route() == "/nodes") {` (not sure if Mithril adds a trailing slash)?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5225#-:-KCqDySmkfvC9s2WEV5f:50182058)*

**Comment by maxlang** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[ui/styl/partials/layout.styl, line 263 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5225#-KCq7v7m_Pb53cCEg7Fs:-KCqEkMMX3IZSZF8j1AZ:2024963704) ([raw file](https://github.com/cockroachdb/cockroach/blob/89ad62cb6ea2102c0f69fd4a35f1d556242b234d/ui/styl/partials/layout.styl#L263)):*
Good point, I'll try that out.

---

*[ui/ts/models/metrics.ts, line 254 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5225#-KCqDTbzumPa6fG9Wg35:-KCqFDs54K40eXY4Ickk:-496386262) ([raw file](https://github.com/cockroachdb/cockroach/blob/af26e9857b0c5b30eb3db81887db050bd5c8e337/ui/ts/models/metrics.ts#L254)):*
I want to distinguish between when it's set vs never set. If it's ```null``` I choose whether or not to show it automatically, but if it's a boolean I override that logic. If it were ```false``` it would never be shown.

---

*[ui/ts/pages/cluster.ts, line 77 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5225#-KCqBSLqvDS8DIhw8X09:-KCqFZ-Or06hmFRWYt0s:1636052328) ([raw file](https://github.com/cockroachdb/cockroach/blob/af26e9857b0c5b30eb3db81887db050bd5c8e337/ui/ts/pages/cluster.ts#L77)):*
No reason except that I felt it convenient to keep around a list of all the valid values.  I can delete these.

---

*[ui/ts/pages/cluster.ts, line 217 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5225#-KCqCPhYTpN87gni8ezV:-KCqFpvHK2AwNG9UkiOE:-1534709508) ([raw file](https://github.com/cockroachdb/cockroach/blob/af26e9857b0c5b30eb3db81887db050bd5c8e337/ui/ts/pages/cluster.ts#L217)):*
Ternary operator does exist. I typically use ``` ... && ... || ...``` if the intent is to check if something is ```null``` or ```undefined``` and ``` ... ? ... : ...``` more for branching logic. What do you think?

---

*[ui/ts/pages/nodes.ts, line 316 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5225#-KCq42qvrpkxzE23hrZB:-KCqGT0FmMJ6DuKIFRGB:2145610050) ([raw file](https://github.com/cockroachdb/cockroach/blob/8abc3d3bb9557362cf41e37e5bbac5d1caf95b5b/ui/ts/pages/nodes.ts#L316)):*
Now that I think about it, this logic is broken. I want to express ```if (m.route() == "/nodes/" || m.route() == "/nodes")``` but this issue is that if there's a query string (eg ```/nodes/?key=val``` it will fail. The current logic will fail as well. I'll fix this.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5225)*

**Comment by maxlang** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[ui/styl/partials/layout.styl, line 263 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5225#-KCq7v7m_Pb53cCEg7Fs:-KCqKY3R6WtsrDXU6KiJ:-670578935) ([raw file](https://github.com/cockroachdb/cockroach/blob/89ad62cb6ea2102c0f69fd4a35f1d556242b234d/ui/styl/partials/layout.styl#L263)):*
Unfortunately, given the differing sizes of the visualizations, shrinking the window results in this:



Probably best to set the exact width at this point and make something responsive later.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5225)*

**Comment by cuongdo** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[ui/ts/pages/cluster.ts, line 77 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5225#-KCqBSLqvDS8DIhw8X09:-KCqMvyPNZdJD9KoQwEM:1608732338) ([raw file](https://github.com/cockroachdb/cockroach/blob/af26e9857b0c5b30eb3db81887db050bd5c8e337/ui/ts/pages/cluster.ts#L77)):*
Please do.

---

*[ui/ts/pages/cluster.ts, line 217 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5225#-KCqCPhYTpN87gni8ezV:-KCqN60L8F-cD47cEzR4:-1064050702) ([raw file](https://github.com/cockroachdb/cockroach/blob/af26e9857b0c5b30eb3db81887db050bd5c8e337/ui/ts/pages/cluster.ts#L217)):*
I'll defer to your judgment on whether this is idiomatic for TS.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5225)*

**Comment by maxlang** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[ui/ts/pages/cluster.ts, line 217 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5225#-KCqCPhYTpN87gni8ezV:-KCqSfI7PeElk5SsFoFw:1107805452) ([raw file](https://github.com/cockroachdb/cockroach/blob/af26e9857b0c5b30eb3db81887db050bd5c8e337/ui/ts/pages/cluster.ts#L217)):*
I'm not sure about typescript, but this pattern is used more for "default" values http://javascript.crockford.com/style2.html

Not sure exactly what would apply here but since I think the ternary operator reads better, and here they're equivalent, I'll switch to that.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5225)*

**Comment by cuongdo** [comment]
:lgtm:

---

Review status: 3 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5225#-:-KCqs1A6BN5WeVYUjOhG:1417088721)*

**Pull request merged**
