### PR TITLE
colflow: correctly track number of queries spilled to disk

### LINKED ISSUE #79706: sql: sql.distsql.queries.spilled is incorrect
This metric should count the number of queries that spill to disk using the vectorized engine, and any query should be included at most once (zero if it doesn't spill). However, currently we increment the metric every time a disk queue is created which can happen many times for a single query.

Jira issue: CRDB-14990

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, we would increment the corresponding metric every time when
a disk queue is created, which - for a single query - could happen many
times. This would lead to inflated counter, and it is now fixed by
incrementing the metric only once, when the path to the temporary
storage directory is computed first.

Fixes: #79706.

Release note (bug fix): Previously, a custom time series metric
`sql.distsql.queries.spilled` was computed incorrectly leading to
exaggerated number, and this has now been fixed.

### CODE REVIEW

**Review by msirek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79818)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[pkg/sql/colflow/vectorized_flow.go, line 286 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79818#-N-QZ0m-A3oz7-YK3wrd:-N-QZ0m-A3oz7-YK3wre:bjdna3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/46e1319e7f6d202273e4b609262e9fe478c4caad/pkg/sql/colflow/vectorized_flow.go#L286)):*
> ```Go
> 	// increment the counter of the number of queries spilled - this code won't
> 	// be executed for this flow in the future since we short-circuit above.
> 	f.Cfg.Metrics.QueriesSpilled.Inc(1)
> ```

`diskQueue.rotateFile()` also calls `GetPath`, so that may also increment the counter when the file size limit is reached and we have to spill to a new file.  Maybe this operation shouldn't be so tightly coupled to `GetPath`.  If someone wants to add a new call to it for a different purpose than the initial spilling, they may inadvertently bump this counter.  Maybe in`newDiskQueue()` where `d.querySpilled()` is called is a good location for it.



_Code quote:_
```Go
(f *vectorizedFlow) GetPath(ctx context.Context) string {
```

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79818)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @msirek)

___
*[pkg/sql/colflow/vectorized_flow.go, line 286 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79818#-N-QZ0m-A3oz7-YK3wrd:-N-UaDjz2npz6qrfa6uU:bt5prk0) ([raw file](https://github.com/cockroachdb/cockroach/blob/46e1319e7f6d202273e4b609262e9fe478c4caad/pkg/sql/colflow/vectorized_flow.go#L286)):*
> `diskQueue.rotateFile()` also calls `GetPath`, so that may also increment the counter when the file size limit is reached and we have to spill to a new file.

The additional increment won't happen because `GetPath` will short-circuit before this line since `f.tempStorage.path` has already been computed.

I can see an argument that I'm abusing `GetPath` here for a somewhat different purpose. A cleaner solution might involve creating a separate callback that is passed to `DiskQueueCfg`, the callback would increment the counter on the first call and become a noop for all other calls. The same callback would be used by all disk queues created so that increment happens only once for a single vectorized flow.

However, to me it seems like `GetPath` is already essentially doing just that, and since the metric is about disk spilling and `GetPath` is about temporary disk storage too, it seems ok to combine them.

**Review by msirek — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79818#-:-N-V-XKd7cp0CEWdXfUv:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach)

___
*[pkg/sql/colflow/vectorized_flow.go, line 286 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79818#-N-QZ0m-A3oz7-YK3wrd:-N-V-B7G6tbmxHCA0lY0:br1zur1) ([raw file](https://github.com/cockroachdb/cockroach/blob/46e1319e7f6d202273e4b609262e9fe478c4caad/pkg/sql/colflow/vectorized_flow.go#L286)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

> `diskQueue.rotateFile()` also calls `GetPath`, so that may also increment the counter when the file size limit is reached and we have to spill to a new file.

The additional increment won't happen because `GetPath` will short-circuit before this line since `f.tempStorage.path` has already been computed.

I can see an argument that I'm abusing `GetPath` here for a somewhat different purpose. A cleaner solution might involve creating a separate callback that is passed to `DiskQueueCfg`, the callback would increment the counter on the first call and become a noop for all other calls. The same callback would be used by all disk queues created so that increment happens only once for a single vectorized flow.

However, to me it seems like `GetPath` is already essentially doing just that, and since the metric is about disk spilling and `GetPath` is about temporary disk storage too, it seems ok to combine them.
</blockquote></details>

OK, I do see `GetPath` does already log a `spilled to disk` message.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
Oops, gotta delete a helper.

bors r-

**Review by yuzefovich — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79818#-:-N-WJ6yZ8wbqcWvYuZfD:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach)

**Pull request merged**
