### PR TITLE
c-deps: bump rocksdb to pick up segfault fix

### LINKED ISSUE #29824: storage: segfault in RocksDB
Adriatic 2 is reliably segfaulting several seconds after booting up due to a memory error in RocksDB. Stack trace:

```
#0  runtime.raise () at /usr/local/go/src/runtime/sys_linux_amd64.s:159
#1  0x00000000006f2372 in runtime.raisebadsignal (c=0x7f4b295fbf98, sig=11) at /usr/local/go/src/runtime/signal_unix.go:491
#2  0x00000000006f2793 in runtime.badsignal (c=0x7f4b295fbf98, sig=11) at /usr/local/go/src/runtime/signal_unix.go:600
#3  0x00000000006f1f78 in runtime.sigtrampgo (ctx=0x7f4b295fc040, info=0x7f4b295fc170, sig=11) at /usr/local/go/src/runtime/signal_unix.go:297
#4  0x000000000070d1c3 in runtime.sigtramp () at /usr/local/go/src/runtime/sys_linux_amd64.s:352
#5  <signal handler called>
#6  cockroach::SplitKey () at /go/src/github.com/cockroachdb/cockroach/c-deps/libroach/encoding.cc:194
#7  0x00000000020000f7 in cockroach::DBComparator::Compare () at /go/src/github.com/cockroachdb/cockroach/c-deps/libroach/comparator.cc:23
#8  0x000000000219db6f in rocksdb::BlockBasedTableIterator::FindKeyForward () at /go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/table/block_based_table_reader.cc:2010
#9  0x000000000212fd19 in rocksdb::IteratorWrapper::Next () at /go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/table/iterator_wrapper.h:61
#10 Next () at /go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/db/version_set.cc:637
#11 0x00000000021be3d2 in rocksdb::IteratorWrapper::Next () at /go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/table/iterator_wrapper.h:61
#12 rocksdb::MergingIterator::Next () at /go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/table/merging_iterator.cc:170
#13 0x0000000002244bf2 in rocksdb::CompactionIterator::NextFromInput () at /go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/db/compaction_iterator.cc:472
#14 0x0000000002245d6d in rocksdb::CompactionIterator::Next () at /go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/db/compaction_iterator.cc:140
#15 0x000000000224d841 in rocksdb::CompactionJob::ProcessKeyValueCompaction () at /go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/db/compaction_job.cc:893
#16 0x000000000224ea1a in rocksdb::CompactionJob::Run () at /go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/db/compaction_job.cc:543
#17 0x00000000020b3a1d in rocksdb::DBImpl::BackgroundCompaction () at /go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/db/db_impl_compaction_flush.cc:1848
#18 0x00000000020b5662 in rocksdb::DBImpl::BackgroundCallCompaction () at /go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/db/db_impl_compaction_flush.cc:1455
#19 0x00000000020b5b72 in rocksdb::DBImpl::BGWorkCompaction () at /go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/db/db_impl_compaction_flush.cc:1272
#20 0x00000000022abe35 in std::function<void ()>::operator()() const () at /x-tools/x86_64-unknown-linux-gnu/x86_64-unknown-linux-gnu/include/c++/6.3.0/functional:2127
#21 rocksdb::ThreadPoolImpl::Impl::BGThread () at /go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/util/threadpool_imp.cc:264
#22 0x00000000022abfdf in rocksdb::ThreadPoolImpl::Impl::BGThreadWrapper () at /go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/util/threadpool_imp.cc:302
#23 0x00000000023de3e4 in execute_native_thread_routine ()
#24 0x00007f4b326186ba in start_thread (arg=0x7f4b295ff700) at pthread_create.c:333
#25 0x00007f4b31e2341d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

The frame in block_based_table_reader.cc:2010 indicates that the error is related to range tombstones:

https://github.com/cockroachdb/rocksdb/blob/976a9fb9a0a61da6dbb31366442f86d3438fc34f/table/block_based_table_reader.cc#L2010

We've initiated a Digital Ocean snapshot (`cockroach-adriatic-0002-1536358746882`) to preserve the data directory.

IIRC Adriatic is running the latest beta candidate and has had TPC-C running against it for several days.

### PR DESCRIPTION
**Pull request by benesch**
Bump RocksDB to pick up cockroachdb/rocksdb#12, which fixes a memory
error that was causing an adriatic node to segfault during startup. It
is likely that this bug could also cause corruption, though no such
corruption has been observed.

Fixes #29824.

Release note: None

### CODE REVIEW

**Comment by benesch** [comment]
@petermattis, when you look at this, can you also cross check it with the new beta SHA? 
https://github.com/cockroachdb/cockroach/commit/29ba932763331172432fb1326862357d0ae7293f

**Review by petermattis — APPROVED** [review]
LGTM

**Comment by petermattis** [comment]
https://github.com/cockroachdb/cockroach/commit/29ba932763331172432fb1326862357d0ae7293f LGTM as well, though I'm not seeing where we had listed the previous beta sha so I can verify you didn't pick up anything inadvertently.

**Comment by benesch** [comment]
bors r=petermattis

**Pull request merged**
