### PR TITLE
storage: add a retry loop to periodic gossips

### PR DESCRIPTION
**Pull request by tamird**
Extracted from #13011.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13147)

### CODE REVIEW

**Comment by a-robinson** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147#-:-KbMOCUjvJeS_JXJ_eM7:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/storage/store.go, line 1324 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147#-KbMRCVRGP3W_rr9ZmAN:-KbMRCVRGP3W_rr9ZmAO:b-rqo8wb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a671885efcff68403e8e97d70cf3727961a7ac80/pkg/storage/store.go#L1324)):*
> ```Go
> 				retryOptions.Closer = s.stopper.ShouldStop()
> 				for loop := retry.Start(retryOptions); loop.Next(); {
> 					if !s.cfg.TestingKnobs.DisablePeriodicGossips {
> ```

It's a bold and difficult to prove claim that this movement made the code easier to understand.

---

*[pkg/storage/store.go, line 1325 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147#-KbMRrjF-VLZs-6d7qbE:-KbMRrjF-VLZs-6d7qbF:b-aj8qhr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a671885efcff68403e8e97d70cf3727961a7ac80/pkg/storage/store.go#L1325)):*
> ```Go
> 				for loop := retry.Start(retryOptions); loop.Next(); {
> 					if !s.cfg.TestingKnobs.DisablePeriodicGossips {
> 						if err := gossipFn.fn(ctx); err != nil {
> ```

You didn't copy over the part of #13011 where it gossips the data if the lease is held.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147)*

**Comment by tamird** [comment]
Pushed an update, PTAL. Apparently it's pretty important that `TestingKnobs.DisablePeriodicGossips` doesn't disable periodic first range gossips.

**Comment by tamird** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/store.go, line 1324 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147#-KbMRCVRGP3W_rr9ZmAN:-KbMXgUBRwCDS8BSTbSV:beqytao) ([raw file](https://github.com/cockroachdb/cockroach/blob/a671885efcff68403e8e97d70cf3727961a7ac80/pkg/storage/store.go#L1324)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

It's a bold and difficult to prove claim that this movement made the code easier to understand.
</blockquote></details>

This is changed, PTAL.

---

*[pkg/storage/store.go, line 1325 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147#-KbMRrjF-VLZs-6d7qbE:-KbMXiOXqJswI2r4tMV3:b-m12vdo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a671885efcff68403e8e97d70cf3727961a7ac80/pkg/storage/store.go#L1325)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You didn't copy over the part of #13011 where it gossips the data if the lease is held.
</blockquote></details>

You're right, but I didn't intend to, either.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147)*

**Comment by bdarnell** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica.go, line 4413 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147#-KbMOz8Y67KMdbpy1wk6:-KbMOz8ZdGIoco4d-c6R:baajawc) ([raw file](https://github.com/cockroachdb/cockroach/blob/89eb873cfe4b84579ff62285744a7ec965e184bd/pkg/storage/replica.go#L4413)):*
> ```Go
> 		if err := kv.Value.GetProto(&liveness); err != nil {
> 			log.Errorf(ctx, "failed to unmarshal liveness value %s: %s", kv.Key, err)
> 			continue
> ```

I think this was deliberate so that a single bad liveness value doesn't (reliably) kill the whole cluster.  I don't feel strongly about it (there are plenty of places where we're not robust about issues like this), but I think it's better to keep the log-and-continue pattern here. (maybe leave a TODO pointing to #12680)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147)*

**Comment by a-robinson** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica.go, line 4413 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147#-KbMOz8Y67KMdbpy1wk6:-KbMYHZ0YWHf6pXOWIBJ:b-rb2yrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/89eb873cfe4b84579ff62285744a7ec965e184bd/pkg/storage/replica.go#L4413)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I think this was deliberate so that a single bad liveness value doesn't (reliably) kill the whole cluster.  I don't feel strongly about it (there are plenty of places where we're not robust about issues like this), but I think it's better to keep the log-and-continue pattern here. (maybe leave a TODO pointing to #12680)
</blockquote></details>

It'd be reasonable to continue to gossip all liveness entries but also return any accumulated errors to the caller

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147)*

**Comment by tamird** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica.go, line 4413 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147#-KbMOz8Y67KMdbpy1wk6:-KbMYLev1NkPbDKlUuXd:b-83m5t2) ([raw file](https://github.com/cockroachdb/cockroach/blob/89eb873cfe4b84579ff62285744a7ec965e184bd/pkg/storage/replica.go#L4413)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

It'd be reasonable to continue to gossip all liveness entries but also return any accumulated errors to the caller
</blockquote></details>

Discussed in person - this is the kind of thing that should never happen, so I'm not sure I agree it's better to continue.

@a-robinson returning an error from here, even if all the other entries are gossiped might do bad things since it'll fail commands post-application, the semantics of which aren't clear to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147)*

**Comment by a-robinson** [comment]
Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica.go, line 4413 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147#-KbMOz8Y67KMdbpy1wk6:-KbMjoEo5J_FfCKE_vRf:b-87chvg) ([raw file](https://github.com/cockroachdb/cockroach/blob/89eb873cfe4b84579ff62285744a7ec965e184bd/pkg/storage/replica.go#L4413)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Discussed in person - this is the kind of thing that should never happen, so I'm not sure I agree it's better to continue.

@a-robinson returning an error from here, even if all the other entries are gossiped might do bad things since it'll fail commands post-application, the semantics of which aren't clear to me.
</blockquote></details>

I don't quite understand your comment. It'll do bad things that aren't clear to you, but you didn't change the code to avoid returning an error?

---

*[pkg/storage/store.go, line 1309 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147#-KbMkrRhAWAx3fSey62i:-KbMkrRhAWAx3fSey62j:bn4ehjg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9b5c364cbf5bc355336c4271e357cdca9a46016/pkg/storage/store.go#L1309)):*
> ```Go
> 			fn: func(ctx context.Context, repl *Replica) error {
> 				pErr := repl.maybeGossipFirstRange(ctx)
> 				// Ignore errors where the state of the range is not known.
> ```

Might want to leave in the explanation of why the leaseholder not being known makes things ok.

Also, doesn't this change the retry behavior? Previously, we'd keep retrying if we didn't know the leaseholder, but this looks like it'll make the retry loop below stop retrying.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica.go, line 4413 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147#-KbMOz8Y67KMdbpy1wk6:-KbMnKJbwtFxO4VboyIj:b-visc6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/89eb873cfe4b84579ff62285744a7ec965e184bd/pkg/storage/replica.go#L4413)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I don't quite understand your comment. It'll do bad things that aren't clear to you, but you didn't change the code to avoid returning an error?
</blockquote></details>

The change to return an error here came from @spencerkimball's #13011, and was put in as part of the outer retry loop which is added in store.go.

So this code has roughly the same semantics as before, except in the face of persistent errors, which will now escalate as @bdarnell commented, rather than being merely logged.

---

*[pkg/storage/store.go, line 1309 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147#-KbMkrRhAWAx3fSey62i:-KbMoWvI42LJ32zceP0y:b-hmzye9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9b5c364cbf5bc355336c4271e357cdca9a46016/pkg/storage/store.go#L1309)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Might want to leave in the explanation of why the leaseholder not being known makes things ok.

Also, doesn't this change the retry behavior? Previously, we'd keep retrying if we didn't know the leaseholder, but this looks like it'll make the retry loop below stop retrying.
</blockquote></details>

Good point. I've removed this special sauce entirely.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147)*

**Comment by petermattis** [comment]
I think this PR should be paused until the problem can be reproduced locally or someone can take the time to understand the precise scenario of what is happening on test clusters.

The bug that needs to be fixed is an apparent failure to gossip the system config when a cluster is completely halted and restarted. The bug seems to be related to epoch-based range leases as I don't believe we've seen this problem when they are disabled. The suspicion is that there is either a code path where an epoch-based range lease is acquired without the system config being gossiped, or a range lease is never been acquired for the system config range which shouldn't be possible with the periodic gossip. Curiously, when this problem has occurred on test clusters, making a no-op change to a zone config "fixes" the problem.

Trying to reproduce the problem on a local cluster is hampered by the fact that the system config span starts off in `r1` and thus has an expiration-based lease. It is only when `r1` gets too large and needs to split and the system config span ends up in a range distinct from the node liveness span that we run into problems. I've locally added a bit of code to force the a split at the start of the system config span and in testing I think I reproduced the problem locally, but am now unable to reproduce it after I added some more logging. I'll keep trying.

---

Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147#-:-KbNGOqxZzvy-u9Fq2aH:b-4k9z2c)*

**Comment by tamird** [comment]
Fine by me.

**Comment by petermattis** [comment]
I reproduced the problem locally, but haven't gotten to the bottom of what is going on. Looks like the first call to `Store.maybeGossipSystemData` is failing on all 3 replicas with:

```
W170125 22:00:14.912717 90 storage/store.go:1319  [n3,s3] error gossiping system config: [NotLeaseHolderError] range 3: replica {3 3 2} not lease holder; lease holder unknown
```

Then, some time later one of the nodes discovers it has the lease for the range, but I'm not seeing any gossiping of the system config. Is there some path where an epoch-based range lease can get reused across restarts? I thought we incremented the epoch at startup to avoid that now.

**Comment by petermattis** [comment]
Found the problem. It is most easily reproduced on a 1-node cluster. Consider this code:

```
	if iAmTheLeaseHolder {
		if leaseChangingHands || atomic.CompareAndSwapInt32(&r.store.haveGossipedSystemConfig, 0, 1) {
			if err := r.maybeGossipSystemConfig(ctx); err != nil {
				log.Error(ctx, err)
			}
		}
		if leaseChangingHands || atomic.CompareAndSwapInt32(&r.store.haveGossipedNodeLiveness, 0, 1) {
			if err := r.maybeGossipNodeLiveness(ctx, keys.NodeLivenessSpan); err != nil {
				log.Error(ctx, err)
			}
		}
	}
```

The handling of the `haveGossiped{SystemConfig,NodeLiveness}` booleans is faulty. The problem is that we're only calling `maybeGossip{SystemConfig,NodeLiveness}` the first time this is reached when `leaseChangingHands` is false. Consider what happens if the node-liveness span is in `r1` and the system-config span is in `r3`. In a single node cluster, if we grab the lease for `r1` first, we'll hit this loop, flip the `haveGossipedSystemConfig` flag but fail to gossip the system config because it isn't part of `r1`. There is a related problem where we fail to gossip the node-liveness span if we grab the lease for `r3` first. Given that this happens on a 1-node cluster, it should be feasible to test without much difficulty.

**Comment by a-robinson** [comment]
It's also not clear how much the `leaseChangingHands` check is buying us? It seems undesirable that `leaseChangingHands` is false even when a node restarts and has to re-take the lease at a new epoch (because the store IDs on the leases match).

**Comment by petermattis** [comment]
> It's also not clear how much the leaseChangingHands check is buying us?

For expiration-based leases, the lease gets renewed every 10 sec. I think the worry is that it would be excessive to gossip that frequently, but that's probably an over-optimization.

During normal operation, we rely on the triggers to gossip {system-config,node-liveness} when the data in those spans change. Instead of the current lease-changing heuristic, perhaps we should gossip {system-config,node-liveness} on lease acquisition if those gossip keys have not already been gossiped.

**Comment by tamird** [comment]
Recall that those gossip functions don't do anything if the values in
gossip match the values on disk.

**Comment by bdarnell** [comment]
> It's also not clear how much the leaseChangingHands check is buying us? It seems undesirable that leaseChangingHands is false even when a node restarts and has to re-take the lease at a new epoch (because the store IDs on the leases match).

That's exactly what the `haveGossiped` booleans are supposed to be for. But it might be better to have `isLeaseChangingHands` track epochs, and not just store IDs. In general we want to treat epoch changes as discontinuities in the lease, even if no other node grabbed the lease in between.

**Comment by petermattis** [comment]
> But it might be better to have isLeaseChangingHands track epochs, and not just store IDs. In general we want to treat epoch changes as discontinuities in the lease, even if no other node grabbed the lease in between.

`leaseChangingHands && iAmTheLeaseHolder` currently causes the timestamp cache low-water to be set. Do we want to do that on epoch changes? The answer might be yes.

**Comment by bdarnell** [comment]
> leaseChangingHands && iAmTheLeaseHolder currently causes the timestamp cache low-water to be set. Do we want to do that on epoch changes? The answer might be yes.

We're not required to do so, but it's also fairly harmless to do it (the low-water mark was set at process start, so resetting it here wouldn't set us back much).

**Comment by petermattis** [comment]
> We're not required to do so, but it's also fairly harmless to do it (the low-water mark was set at process start, so resetting it here wouldn't set us back much).

We set the low water to the new lease start time. That doesn't seem harmless, but perhaps I'm misunderstanding the effect.

**Comment by bdarnell** [comment]
> We set the low water to the new lease start time. That doesn't seem harmless, but perhaps I'm misunderstanding the effect.

Yeah, it's disruptive to reset the low water mark. But A) we just reset it anyway at process start, so it won't move far and B) If we're reacquiring our own lease, something fairly disruptive has already happened. Another node could have acquired the lease just as easily as we re-acquired it, and in that case the low-water mark would have to be set anyway.

**Comment by tamird** [comment]
@petermattis rebased this.

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147#-:-Kb_pKG-BVGIp7hMdsws:bnfp4nl)*

**Comment by andreimatei** [comment]
I think it's a good idea to not reset the low water mark when a node re-acquires a lease it previously had. At the very least, for anticipating a reader's question about whether the reset is needed. And also because the "easily" part in "another node could have acquired the lease just as easily as we re-acquired it" might not stay true - if we start having better wits about who the leaseholder should be, then it might become more likely for the same node to reacquire an expired lease. This might apply less to epoch-based leases.

Btw, I don't think we increment a node's epoch on restart. I know for sure that we didn't use to, and more recently Spencer was saying that he was considering doing the increment but I don't seem to see a recent commit to that effect from him.

---

Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147#-:-Kb_uz34zyJguJmPgqrT:bxtd93i)*

**Comment by andreimatei** [comment]
I take the last part back, incrementing the epoch on startup was added in https://reviewable.io/reviews/cockroachdb/cockroach/12798

---

Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147#-:-Kba-1l6DYkKVQXl6Apk:b-ncg0fu)*

**Comment by bdarnell** [comment]
Reviewed 1 of 3 files at r3, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/storage/store.go, line 1302 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147#-KbapY76FISJJAie_xpW:-KbapY77PpUc8fdBT5Lk:b-adl1bg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c0314da4b5b64f4a8d20c86768751d19870ad78/pkg/storage/store.go#L1302)):*
> ```Go
> 			key: roachpb.KeyMin,
> 			fn: func(ctx context.Context, repl *Replica) error {
> 				return repl.maybeGossipFirstRange(ctx).GoError()
> ```

Comment why this one doesn't use `wakeReplica` (i.e. that the first range is gossiped by all replicas, not just the lease holder)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147#-:-Kbapi3mvA-9DYZ1nSVK:bnfp4nl)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/storage/store.go, line 1302 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147#-KbapY76FISJJAie_xpW:-Kbk7I81vXDUvPFNItIT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c0314da4b5b64f4a8d20c86768751d19870ad78/pkg/storage/store.go#L1302)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Comment why this one doesn't use `wakeReplica` (i.e. that the first range is gossiped by all replicas, not just the lease holder)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13147)*

**Pull request merged**
