### PR TITLE
storage: give snapshots for under-replicated ranges more bandwidth

### LINKED ISSUE #15273: storage: Snapshots for under-replicated ranges should have higher bandwidth
We currently divide snapshots into two categories for bandwidth management - preemptive and raft-initiated. Raft-initiated snapshots are given more bandwidth because they indicate an existing follower that is falling behind (and therefore not contributing to the raft quorum). Preemptive snapshots are (often) rebalancing traffic that is low-priority, but when they're used to repair an under-replicated range they should be high priority.

Noticed in https://github.com/cockroachdb/cockroach/issues/15163#issuecomment-296387234

### PR DESCRIPTION
**Pull request by petermattis**
Add SnapshotRequest.Header.Priority field which indicates the priority
of a snapshot: either RECOVERY or REBALANCE. Up-replicating a range was
previously given rebalancing bandwidth (default 2 MB/sec), but is now
given recovery bandwidth (default 8 MB/sec) to reflect its importance.

Fixes #15273

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm: but a test would be nice.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/raft.proto, line 110 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15279#-KiVGrKv803y_WymKjD8:-KiVGrKv803y_WymKjD9:b-fl5938) ([raw file](https://github.com/cockroachdb/cockroach/blob/24b3aec5f2288529cc367e04e7d9338a8cd93d6c/pkg/storage/raft.proto#L110)):*
> ```protobuf
>     // up-replication snapshots (i.e. when a dead node has been
>     // removed and the range needs to be up-replicated).
>     RECOVERY = 0;
> ```

consider prepending an UNKNOWN variant to avoid accidental meaning for the zero value.

---

*[pkg/ui/yarn.lock, line 320 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15279#-KiVH8qiJL4CVoCnlNKF:-KiVH8qiJL4CVoCnlNKG:b-jf0m9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/24b3aec5f2288529cc367e04e7d9338a8cd93d6c/pkg/ui/yarn.lock#L320)):*
> ```
>   resolved "https://registry.yarnpkg.com/assert-plus/-/assert-plus-0.2.0.tgz#d74e1b87e7affc0db8aadb7021f3fe48101ab234"
> 
> assert-plus@^1.0.0, assert-plus@1.0.0:
> ```

this file shouldn't have changed; i think you have an old version of `yarn`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15279#-:-KiVHCD5DGJIAp5ccf42:b-yq0dk0)*

**Comment by petermattis** [comment]
Added a simple test. The snapshot rate limiting isn't currently tested end-to-end. Not obvious how to do so. 

---

Review status: 3 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/raft.proto, line 110 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15279#-KiVGrKv803y_WymKjD8:-KiVIJTOaNkzv8zaj4VG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/24b3aec5f2288529cc367e04e7d9338a8cd93d6c/pkg/storage/raft.proto#L110)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

consider prepending an UNKNOWN variant to avoid accidental meaning for the zero value.
</blockquote></details>

Done.

---

*[pkg/ui/yarn.lock, line 320 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15279#-KiVH8qiJL4CVoCnlNKF:-KiVIKboX03FBi8xqYXJ:bvwvtn8) ([raw file](https://github.com/cockroachdb/cockroach/blob/24b3aec5f2288529cc367e04e7d9338a8cd93d6c/pkg/ui/yarn.lock#L320)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this file shouldn't have changed; i think you have an old version of `yarn`.
</blockquote></details>

Gah, tooling!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15279#-:-KiVINqJ-0kLx_MNddq2:b-s3089d)*

**Comment by tamird** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/store_test.go, line 2628 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15279#-KiVTyKT3VGgepO8RCuF:-KiVTyKT3VGgepO8RCuG:b5o1ho5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4eb119c03cdce9a9c0f756efea94aea4f43ccf79/pkg/storage/store_test.go#L2628)):*
> ```Go
> 	}
> 	for _, c := range testCases {
> 		t.Run("", func(t *testing.T) {
> ```

`c.priority.String()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15279)*

**Comment by petermattis** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/store_test.go, line 2628 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15279#-KiVTyKT3VGgepO8RCuF:-KiVV1Jm96cWvYUIfJoc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4eb119c03cdce9a9c0f756efea94aea4f43ccf79/pkg/storage/store_test.go#L2628)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

`c.priority.String()`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15279)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 3 of 7 files at r1, 3 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15279#-:-KiVx6Y85aahDU2-hW5_:bnfp4nl)*

**Pull request merged**
