### PR TITLE
storage: fix split tests and revive TestStoreRangeSplitAtRangeBounds

### PR DESCRIPTION
**Pull request by nvb**
Prompted by a few issues I noticed when looking at #17565.

Most of the split tests were using `adminSplitArgs`, which took an unnecessary
argument which allowed a lot of callers to use it incorrectly. The first commit
addresses this.

`TestStoreRangeSplitAtRangeBounds` had rotted because some refactoring
since its introduction in 0187440 had begun sending the split requests to the
wrong range. Because of this, it was not picked up by #14273.

### CODE REVIEW

**Comment by tschottdorf** [comment]
> , which took an unnecessary
> argument which allowed a lot of callers to use it incorrectly. The first commit
> addresses this.

I assume the incorrect usage was that split requests were addressed not based on the split key? I understand that that's weird and your simplification is good, but what exactly was incorrect (or more generally, what's incorrect about sending an admin split to a random non-affected range)?

:lgtm: 

---

Reviewed 8 of 8 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17574#-:-KrBuzt0Re9Mbc8R7cSf:b-v9dzvc)*

**Comment by bdarnell** [comment]
Reviewed 7 of 8 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_split_test.go, line 57 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17574#-KrBwaO_t29gqCyFHZv6:-KrBwaO_t29gqCyFHZv7:bszdr1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/99c8c405620d2c6835136610d7f4091826c6a58c/pkg/storage/client_split_test.go#L57)):*
> ```Go
> )
> 
> func adminSplitArgs(key, splitKey roachpb.Key) *roachpb.AdminSplitRequest {
> ```

We apparently weren't doing anything useful with this, but the two-arg version could have been useful by setting `key` but leaving `splitKey` empty (so that AdminSplit must choose the split key itself). I'm fine making this change.

---

*[pkg/storage/client_split_test.go, line 346 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17574#-KrBxOTxUDgIcBISNDKV:-KrBxOTxUDgIcBISNDKW:bj2rf5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f5b226fbcba4feeca233eeffdc0d0e0e3fcf5a7/pkg/storage/client_split_test.go#L346)):*
> ```Go
> 			// outside the bounds for the range. Note that conflicting range
> 			// descriptor errors are retried internally.
> 			if !testutils.IsError(pErr.GoError(), "key range .* outside of bounds of range") {
> ```

This can now be a type assertion on RangeKeyMismatchError. 

Or it might be better to send the AdminSplit command via a DistSender (instead of `rg1(store)`) so RangeKeyMismatchErrors would be retried too and no errors would be expected. (This is a more realistic scenario). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17574)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17574#-:-KrBxpSlnewAWfY2Yqgs:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_split_test.go, line 57 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17574#-KrBwaO_t29gqCyFHZv6:-KrC6BQ3Y5dr0nR5ARl4:bd63lmj) ([raw file](https://github.com/cockroachdb/cockroach/blob/99c8c405620d2c6835136610d7f4091826c6a58c/pkg/storage/client_split_test.go#L57)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

We apparently weren't doing anything useful with this, but the two-arg version could have been useful by setting `key` but leaving `splitKey` empty (so that AdminSplit must choose the split key itself). I'm fine making this change.
</blockquote></details>

What do you think about getting rid of the `SplitKey` field on `AdminSplitRequest` and in its place adding a `FindSplitKey` bool? We would then use the header's key as the split key if this flag was set to false.

---

*[pkg/storage/client_split_test.go, line 300 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17574#-KrBux9EvvTpovYZD86b:-KrBww_EjbHeU1GI_soG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f5b226fbcba4feeca233eeffdc0d0e0e3fcf5a7/pkg/storage/client_split_test.go#L300)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

`testutils.IsPError`

also, this is a structured error, why not use a type assertion?
</blockquote></details>

Done.

---

*[pkg/storage/client_split_test.go, line 313 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17574#-KrBv7yNCs6Hcem717gI:-KrBxCPHK1DqWAFuX_5H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f5b226fbcba4feeca233eeffdc0d0e0e3fcf5a7/pkg/storage/client_split_test.go#L313)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

you might log before and after counts in case this test starts failing for unrelated reasons.
</blockquote></details>

Done.

---

*[pkg/storage/client_split_test.go, line 346 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17574#-KrBxOTxUDgIcBISNDKV:-KrC7EsYpxDGncdh7YMh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f5b226fbcba4feeca233eeffdc0d0e0e3fcf5a7/pkg/storage/client_split_test.go#L346)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This can now be a type assertion on RangeKeyMismatchError. 

Or it might be better to send the AdminSplit command via a DistSender (instead of `rg1(store)`) so RangeKeyMismatchErrors would be retried too and no errors would be expected. (This is a more realistic scenario). 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17574)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/storage/client_split_test.go, line 313 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17574#-KrBv7yNCs6Hcem717gI:-KrC9_j6S2VCy6IJJsi8:b-dvr5gu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f5b226fbcba4feeca233eeffdc0d0e0e3fcf5a7/pkg/storage/client_split_test.go#L313)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

eh, why log it? i think it's only interesting in the failure case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17574)*

**Comment by nvanbenschoten** [comment]
Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/storage/client_split_test.go, line 313 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17574#-KrBv7yNCs6Hcem717gI:-KrCBeMNbrFclUh2GaRI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f5b226fbcba4feeca233eeffdc0d0e0e3fcf5a7/pkg/storage/client_split_test.go#L313)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

eh, why log it? i think it's only interesting in the failure case.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17574)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17574)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_split_test.go, line 57 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17574#-KrBwaO_t29gqCyFHZv6:-KrN66oTOVe5oe6zKpBI:b-gu2fcl) ([raw file](https://github.com/cockroachdb/cockroach/blob/99c8c405620d2c6835136610d7f4091826c6a58c/pkg/storage/client_split_test.go#L57)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What do you think about getting rid of the `SplitKey` field on `AdminSplitRequest` and in its place adding a `FindSplitKey` bool? We would then use the header's key as the split key if this flag was set to false.
</blockquote></details>

That sounds like a better API design (also, if we were redesigning this from scratch I'd probably expose MVCCFindSplitKey as a separate method so that AdminSplit never chose its own key), but the migration seems like more trouble than its worth. We could easily make it an error to provide a SplitKey that is neither nil nor equal to the key in the header, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17574)*

**Pull request merged**
