### PR TITLE
filetable: extend ReadFile to support using either executor

### PR DESCRIPTION
**Pull request by dt**
Release note: none.

### CODE REVIEW

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59847)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

___
*[pkg/storage/cloudimpl/filetable/file_table_read_writer.go, line 655 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59847#-MT6-xXXA9tfcFzPwlU4:-MT6-xXXA9tfcFzPwlU5:b-ii1s6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dac860a95bcc78aac69f0b8748bbd3e40541ae5/pkg/storage/cloudimpl/filetable/file_table_read_writer.go#L655)):*
> ```Go
> 		FROM %s f LEFT OUTER JOIN %s p ON p.file_id = f.file_id
> 		WHERE f.filename = $1 GROUP BY f.file_id`,
> 		fileTableName, payloadTableName)
> ```

Do we need to quote these names or do we control them such that we know they are safe to render unquoted into the query?
___
*[pkg/storage/cloudimpl/filetable/file_table_read_writer.go, line 660 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59847#-MT62PVY45_jdHSHowhB:-MT62PVY45_jdHSHowhC:b-6va3im) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dac860a95bcc78aac69f0b8748bbd3e40541ae5/pkg/storage/cloudimpl/filetable/file_table_read_writer.go#L660)):*
> ```Go
> 		return nil, 0, errors.Wrap(err, "failed to read file info")
> 	}
> 	// Based on the executor type we must process the outputted rows differently.
> ```

The need to type switch here makes me wonder if the return type of Query should know how to handle this somehow. I'm not recommending we change anything, just idle musing.

**Review by adityamaru — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59847)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59847)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[pkg/storage/cloudimpl/filetable/file_table_read_writer.go, line 655 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59847#-MT6-xXXA9tfcFzPwlU4:-MT65ZTf4wE80z6jerLo:b-z18b9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dac860a95bcc78aac69f0b8748bbd3e40541ae5/pkg/storage/cloudimpl/filetable/file_table_read_writer.go#L655)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Do we need to quote these names or do we control them such that we know they are safe to render unquoted into the query?
</blockquote></details>

We can't quote it _here_ since it is already fully qualified, with db and schema which would need to be quoted individually, e.g. `"my db"."my schema"."my table"` vs `"my db.my schema.my table"` (since the latter would be interpreted as just a table name with some dots in it).  Looking at where it comes from, it looks like `GetDatabaseAndSchema` parsed them using the correct helpers and then string-ifies them, so I *think* it is probably OK but I'll admit I'm not 100% sure. This isn't new in this change though, as the prior code was sprintf'ing it too, just in two round-trips instead of one with the JOIN, so if there is more to dig on here I might leave it to a separate change.
___
*[pkg/storage/cloudimpl/filetable/file_table_read_writer.go, line 660 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59847#-MT62PVY45_jdHSHowhB:-MT68Z5h1NgGHCBdXUtV:b9786ox) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dac860a95bcc78aac69f0b8748bbd3e40541ae5/pkg/storage/cloudimpl/filetable/file_table_read_writer.go#L660)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

The need to type switch here makes me wonder if the return type of Query should know how to handle this somehow. I'm not recommending we change anything, just idle musing.
</blockquote></details>

For _sure_. This thing is slightly annoying because it is trying to be used against two different query "executors" where one's "results" are materialized as [][]datum and the other has a iterator/streaming API. We could potentially clean this up by having this helper hide the [][]datum one with its own iterator, but then there's the fact one produces our internal more granular types e.g. uuids or decimals, whereas the other uses a generic go db connection and just ends up with go primitive types (so []byte and string for those two examples). So to completely hide from the caller which we used we'd need to do a lot of work to get to a common result representation.

As long as these ugly switches don't leak out of this package, as annoying as they are, the amount we'd need to invest in the helper to hide them might not be worth it?

**Comment by dt** [comment]
TFTR!

bors r=adityamaru

**Pull request merged**
