### PR TITLE
cli: print the number of rows at the end of pretty-formatted tables.

### PR DESCRIPTION
**Pull request by knz**
(Suggested by @mberhault; useful while investigating #7202)

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7266)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[cli/sql_util.go, line 306 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7266#-KKNsTD4xfY4POmqUzTm:-KKNsTD4xfY4POmqUzTn:166974601) ([raw file](https://github.com/cockroachdb/cockroach/blob/041ab9178fe08337fa7a43d20c2022106556a068/cli/sql_util.go#L306)):*
> ```Go
> 		}
> 		table.Render()
> 		plural := ""
> ```

util.Pluralize

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7266#-:-KKNsXHhh8u1kHdUQNEl:1417088721)*

**Comment by knz** [comment]
TFYR!

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[cli/sql_util.go, line 306 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7266#-KKNsTD4xfY4POmqUzTm:-KKO2E0aVk9vhCnMTJSH:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/041ab9178fe08337fa7a43d20c2022106556a068/cli/sql_util.go#L306)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> util.Pluralize
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7266#-:-KKO2FUME786AIgykF85:-485611887)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7266)*

**Comment by mberhault** [comment]
LGTM

**Pull request merged**
