### PR TITLE
rac2: implement wait for eval

### LINKED ISSUE #128910: rac2: implement wait for eval
This issue is to implement the WaitForEval method defined on the RangeController. See the associated integration issue for supporting WaitForEval above the RangeController #128909.

Jira issue: CRDB-41271

Epic CRDB-37515

### LINKED ISSUE #128914: kv: support leaseholder changes in rac2
This issue is to add support for leaseholder changes as part of replication admission control v2. After this issue is complete, leaseholder changes should be supported via:

https://github.com/sumeerbhola/cockroach/blob/5c2a50ec4d0dcf2502d742ac9036d39995886abc/pkg/kv/kvserver/kvflowcontrol/kvflowconnectedstream/stream.go#L1301-L1301

And hooked up via the integration:

https://github.com/sumeerbhola/cockroach/blob/5c2a50ec4d0dcf2502d742ac9036d39995886abc/pkg/kv/kvserver/flow_control_replica_integration.go#L648-L658

Jira issue: CRDB-41277

Epic CRDB-37515

### LINKED ISSUE #128915: kv: support range replica set changes in rac2
This issue is to add support for a changing range replica set (expected upon rebalancing, promotion, demotion etc) in replication admission control v2. After this issue is complete, rac2 should implement:

https://github.com/sumeerbhola/cockroach/blob/5c2a50ec4d0dcf2502d742ac9036d39995886abc/pkg/kv/kvserver/kvflowcontrol/kvflowconnectedstream/stream.go#L1294-L1299

And integrate calls to the RangeController method above:

https://github.com/sumeerbhola/cockroach/blob/5c2a50ec4d0dcf2502d742ac9036d39995886abc/pkg/kv/kvserver/flow_control_replica_integration.go#L678-L680

Jira issue: CRDB-41278

Epic CRDB-37515

### PR DESCRIPTION
**Pull request by kvoli**
Implement `RangeController.WaitForEval(..)`, which will be used to wait
on a configurable number of streams to have available tokens. Note that
the functionality is currently incomplete without replica state
management, done in `HandleRaftReady`.

Resolves: https://github.com/cockroachdb/cockroach/issues/128910
Release note: None

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129263#-:-O4qFSaX9-fHg0KgatLY:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 387 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129263#-O4qBPKb1WsVD1BHL6Dp:-O4qBPKb1WsVD1BHL6Dq:bhlzst3) ([raw file](https://github.com/cockroachdb/cockroach/blob/425ba55b61b7845fa4a017cc63e4ec72c9b372a2/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L387)):*
> ```Go
> 			// TODO(rac2): Once the send stream is added, check that the send stream
> 			// is initialized here instead and also check that the elastic eval
> 			// tokens are positive.
> ```

I didn't understand this comment about elastic eval tokens.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller_wait_for_eval` line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129263#-O4qEH-Z97v3QiZU6_zG:-O4qEH-Z97v3QiZU6_zH:b-ry4bl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/425ba55b61b7845fa4a017cc63e4ec72c9b372a2/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller_wait_for_eval#L134)):*
> ```
> 
> # Remove tokens from s3, s1 and s2 have tokens which is enough for quorum.
> adjust_tokens
> ```

s3 is no longer a replica. s4 is a replica but already has no tokens. Was this meant to do something else?
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller_wait_for_eval` line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129263#-O4qEUbj8a0dEtQ34FZm:-O4qEUbj8a0dEtQ34FZn:b-otuu3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/425ba55b61b7845fa4a017cc63e4ec72c9b372a2/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller_wait_for_eval#L160)):*
> ```
> # immediately because there are already sufficient tokens for the new
> # leaseholder.
> wait_for_eval name=e range_id=1 pri=HighPri
> ```

can you change the leaseholder to s4 and then wait_for_eval? It should not complete because it is the leaseholder.
And then add tokens to s4, but remove s1's tokens, and do another wait_for_eval which should not complete because of leader.
And then try to make s4 and s1 tokens positive in some sequence and neither eval will succeed until both are positive.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller_wait_for_eval` line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129263#-O4qEvzG5-JkIbIURtyz:-O4qEvzG5-JkIbIURtz-:b-dxlyc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/425ba55b61b7845fa4a017cc63e4ec72c9b372a2/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller_wait_for_eval#L177)):*
> ```
>   store_id=1 replica_id=1 type=VOTER_FULL state=StateReplicate
>   store_id=2 replica_id=2 type=VOTER_FULL state=StateReplicate
>   store_id=3 replica_id=5 type=VOTER_FULL state=StateReplicate
> ```

this is changing the desc for r1 again, yes?
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller_wait_for_eval` line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129263#-O4qF4Nl5-qhqGZcG4m5:-O4qF4Nl5-qhqGZcG4m6:bv3ykv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/425ba55b61b7845fa4a017cc63e4ec72c9b372a2/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller_wait_for_eval#L183)):*
> ```
>   store_id=5 replica_id=5 type=VOTER_FULL state=StateReplicate
> ----
> r1: [(n1,s1):1,(n2,s2):2*,(n3,s3):5]
> ```

is * the leaseholder? Can you add a comment early in this file?

**Review by kvoli — COMMENTED** [review]
TYFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129263#-:-O4q_6B11XWFv_kYcTp5:bzftgo7)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 387 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129263#-O4qBPKb1WsVD1BHL6Dp:-O4qNWXfAxV7UJ8bO1Gw:bqw9xbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/425ba55b61b7845fa4a017cc63e4ec72c9b372a2/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L387)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I didn't understand this comment about elastic eval tokens.
</blockquote></details>

This comment is incorrect w.r.t eval tokens. It should check whether the stream was recently probed or in replicate, similar to https://github.com/sumeerbhola/cockroach/blob/a5051a98bc705f32ebfb5ee431a1b796023dfab5/pkg/kv/kvserver/kvflowcontrol/kvflowconnectedstream/stream.go#L2695-L2697. 


I updated to include that fn and use it instead of `==replicate`.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller_wait_for_eval` line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129263#-O4qEH-Z97v3QiZU6_zG:-O4qOYnLBkLjTJr-EtUq:b-s0trbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/425ba55b61b7845fa4a017cc63e4ec72c9b372a2/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller_wait_for_eval#L134)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

s3 is no longer a replica. s4 is a replica but already has no tokens. Was this meant to do something else?
</blockquote></details>

s3 is still a replica here, see above:

`r1: [(n1,s1):1*,(n2,s2):2,(n3,s3):3,(n4,s4):4NON_VOTER]`

s4 is a replica but already has no tokens. Was this meant to do something else?

All streams start with no tokens, s4 being a non-voter is meant to demonstrate that it doesn't impact quorum and isn't required for non-elastic.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller_wait_for_eval` line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129263#-O4qEUbj8a0dEtQ34FZm:-O4qOr6E7IBMdfrWfBFb:bn4659r) ([raw file](https://github.com/cockroachdb/cockroach/blob/425ba55b61b7845fa4a017cc63e4ec72c9b372a2/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller_wait_for_eval#L160)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you change the leaseholder to s4 and then wait_for_eval? It should not complete because it is the leaseholder.
And then add tokens to s4, but remove s1's tokens, and do another wait_for_eval which should not complete because of leader.
And then try to make s4 and s1 tokens positive in some sequence and neither eval will succeed until both are positive.
</blockquote></details>

Done down below for 'h' and 'i'.

I did need to change the scenario slightly. Even though we remove s1's tokens as we add to the leaseholder, s1 already had positive tokens initially so a handle was never created. Unless we change the replicas/leaseholder after starting the evaluation, it won't get checked again to see the leader (s1) doesn't have available tokens. 
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller_wait_for_eval` line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129263#-O4qEvzG5-JkIbIURtyz:-O4qOy3U9TxU34zeLgrW:bb77ufg) ([raw file](https://github.com/cockroachdb/cockroach/blob/425ba55b61b7845fa4a017cc63e4ec72c9b372a2/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller_wait_for_eval#L177)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this is changing the desc for r1 again, yes?
</blockquote></details>

Yes.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller_wait_for_eval` line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129263#-O4qF4Nl5-qhqGZcG4m5:-O4qOz0uCrLwYqqsUXtu:b-6g7pdt) ([raw file](https://github.com/cockroachdb/cockroach/blob/425ba55b61b7845fa4a017cc63e4ec72c9b372a2/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller_wait_for_eval#L183)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is * the leaseholder? Can you add a comment early in this file?
</blockquote></details>

Yes it is, added at the top to clarify.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129263#-:-O4qbzwEAJu9rvwnFgRK:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller_wait_for_eval` line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129263#-O4qEH-Z97v3QiZU6_zG:-O4qbIr955zz5WUTlSbk:b-jhyysx) ([raw file](https://github.com/cockroachdb/cockroach/blob/425ba55b61b7845fa4a017cc63e4ec72c9b372a2/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller_wait_for_eval#L134)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

s3 is still a replica here, see above:

`r1: [(n1,s1):1*,(n2,s2):2,(n3,s3):3,(n4,s4):4NON_VOTER]`

s4 is a replica but already has no tokens. Was this meant to do something else?

All streams start with no tokens, s4 being a non-voter is meant to demonstrate that it doesn't impact quorum and isn't required for non-elastic.
</blockquote></details>

Got it. Thanks.

**Comment by kvoli** [comment]
bors r=sumeerbhola

**Pull request merged**
