### PR TITLE
workload/schemachange: fixes to improve stability of the test

### LINKED ISSUE #91131: sql: simple cross join in randomized schemachanger workload are hitting in-mem temp storage
Despite having a fetch first rows limit on randomly generated SELECT queries in the schemachanger workload, we are seeing scenarios where the memory limit might be kicking in incorrectly for simple cross-join. The query in question that we observed had the form:
`SELECT t0.col1845_1847 AS col0,t2.col1076_1083 AS col1,t2.col1535_1551 AS col2,t2.col1535_1545 AS col3,t0.col1845_1847 AS col4,t1.col1076_1081 AS col5,t2.col1076_1077 AS col6,t1.col1076_1090 AS col7,t1.col1076_1090 AS col8 FROM schema1900.table1912 AS t0 ,public.table1149 AS t1 ,schema1782.table1897 AS t2  FETCH FIRST 1 ROWS ONLY` 
runs into
`ERROR: in-mem temp storage: disk budget exceeded: 1048576 bytes requested, 104857600 currently allocated, 104857600 bytes in budget (SQLSTATE 53100)`

The logs for the run from the server and randomized workload can be found at:
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/7280551

Jira issue: CRDB-21117

### PR DESCRIPTION
**Pull request by fqazi**
These changes do the following:

Fixes: #91131
Informs: #90695

1. Eliminate log spam inside the schema changer workload due to the watchdog thread incorrectly dealing with null values
2. Expecting disk full errors due to large selects, since spilling does have a limit out of the box inside cockroach
3. Reducing a hang inside the workload due to a no longer necessary retry loop.

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm: thank you

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91163#-:-NFuGFe5AEqjG48w1B2n:ben21ju)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

**Review by renatolabs — APPROVED** [review]
:lgtm:

Thank you for fixing these!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91163#-:-NFxeE_mAtFqLSDH1e20:b-33ni32)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @herkolategan)

**Comment by fqazi** [comment]
@renatolabs @ajwerner TFTR!

**Comment by fqazi** [comment]
bor r-

**Comment by fqazi** [comment]
blathers backport 22.2

**Pull request merged**
