### PR TITLE
settingswatcher: add version guard utility

### PR DESCRIPTION
**Pull request by jeffswenson**
Add the settingswatcher.VersionGuard utility. VersionGuard makes it possible to check a cluster version in the context of a transaction. Until a version gate is reached, VersionGuard will look up the version set in the settings table. Once a version is reached, the guard can skip the KV read because versions never go backwards.

The version guard will be used to migrate the sqlinstance, sql_liveness, lease system tables to a regional by row compatible index. The in-memory IsActive check is insufficient for the migration, because the setting can change in between when the transaction starts and when the transaction commits.

Part of #94843

### CODE REVIEW

**Comment by JeffSwenson** [comment]
This change was extracted from https://github.com/cockroachdb/cockroach/pull/97406. I'm trying to split up the RBR migration work into reviewable chunks.

**Review by ajwerner — COMMENTED** [review]
no major complains from me

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97935#-:-NPZQOwpDf9ngE7yIwQN:b-amrkkp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @JeffSwenson, and @renatolabs)

___
*[`pkg/server/settingswatcher/version_guard.go` line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97935#-NPZQ4JA2wXkcQG4p2M-:-NPZQ4JA2wXkcQG4p2M0:bor5r4j) ([raw file](https://github.com/cockroachdb/cockroach/blob/6827e06a6b5203fe0f14de9bdde60a3d21d2e553/pkg/server/settingswatcher/version_guard.go#L15)):*
> ```Go
> //
> // Example Usage:
> // guard, err := watcher.MakeVersionGuard(ctx, txn, version.MaxVersionGateToCheck)
> ```

Below you call it `iterlock`, also, the indentation is off a bit. 
___
*[`pkg/server/settingswatcher/version_guard.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97935#-NPZQ8TXDLiZSE4vLYZW:-NPZQ8TXDLiZSE4vLYZX:b-ilezxt) ([raw file](https://github.com/cockroachdb/cockroach/blob/6827e06a6b5203fe0f14de9bdde60a3d21d2e553/pkg/server/settingswatcher/version_guard.go#L32)):*
> ```Go
> }
> 
> // MakVersionGuard constructs a version guard for the transaction.
> ```

nit: `Mak`
___
*[`pkg/server/settingswatcher/version_guard_test.go` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97935#-NPZQIINDLA9BqdbMUCG:-NPZQIINDLA9BqdbMUCH:b-pxb19q) ([raw file](https://github.com/cockroachdb/cockroach/blob/6827e06a6b5203fe0f14de9bdde60a3d21d2e553/pkg/server/settingswatcher/version_guard_test.go#L1)):*
> ```Go
> package settingswatcher_test
> ```

header

**Review by jeffswenson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97935)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @herkolategan, and @renatolabs)

___
*[`pkg/server/settingswatcher/version_guard.go` line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97935#-NPZQ4JA2wXkcQG4p2M-:-NPcgprE9JDVEeO6KwpN:bh23g08) ([raw file](https://github.com/cockroachdb/cockroach/blob/6827e06a6b5203fe0f14de9bdde60a3d21d2e553/pkg/server/settingswatcher/version_guard.go#L15)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Below you call it `iterlock`, also, the indentation is off a bit. 
</blockquote></details>

Fixed the naming and made it so the indentation is consistent. crlfmt appears to require a tab indenting the code block.
___
*[`pkg/server/settingswatcher/version_guard_test.go` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97935#-NPZQIINDLA9BqdbMUCG:-NPchAWqCAFOUuh62unE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6827e06a6b5203fe0f14de9bdde60a3d21d2e553/pkg/server/settingswatcher/version_guard_test.go#L1)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

header
</blockquote></details>

Done.

**Review by ajwerner — APPROVED** [review]
LGTM

**Pull request merged**
