### PR TITLE
storage: always initialize Raft groups on receipt of request

### PR DESCRIPTION
**Pull request by spencerkimball**
Previously a Raft group would not load if a request was received for a
replica that didn't hold the lease. On certain restart scenarios, it's
possible for two replicas to hold different leases, where one of the two
is actually behind on Raft. With epoch-based leases and no necessary
expiration, this could lead to `NotLeaseholderError`s pinging back and
forth between the two replicas with uninitialized raft groups.

This change guarantees that the raft group is activated and so no
replica can stubbornly believe the veracity of its lease without also
catching up on Raft.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12465)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_raft_test.go, line 3113 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12465#-KZDsU8v5KVQDREbfnk-:-KZDsU8v5KVQDREbfnk0:b6y7na7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c6adc67f2228da2c3a88ec95c1f79d78a1f306/pkg/storage/client_raft_test.go#L3113)):*
> ```Go
> }
> 
> // TestInitRaftGroupOnRequest verifies that an uninitialized Raft group
> ```

this is testing exactly the implementation, rather than the badness the implementation is meant to prevent.

---

*[pkg/storage/client_raft_test.go, line 3142 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12465#-KZDsA3fov-qgZgra5iF:-KZDsA3fov-qgZgra5iG:b-4nbtu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c6adc67f2228da2c3a88ec95c1f79d78a1f306/pkg/storage/client_raft_test.go#L3142)):*
> ```Go
> 
> 	// Get replica from the store which isn't the leaseholder.
> 	storeIdx := int(lease.Replica.StoreID) % len(mtc.stores)
> ```

can you be more explicit here? if we change how these store IDs are assigned in the test this will silently do the wrong thing.

---

*[pkg/storage/replica.go, line 928 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12465#-KZDqKDtNxixroNXpDmU:-KZDqKDtNxixroNXpDmV:bfcwv2w) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c6adc67f2228da2c3a88ec95c1f79d78a1f306/pkg/storage/replica.go#L928)):*
> ```Go
> 
> 			// If the internal Raft group is not initialized, create it and wake the leader.
> 			if r.mu.internalRaftGroup == nil {
> ```

why do you need this condition? it is already checked in withRaftGroupLocked

---

*[pkg/storage/replica.go, line 933 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12465#-KZDquA0iuNRWHK-zDmp:-KZDquA1TxxLpELVSm2S:b-whokdv) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c6adc67f2228da2c3a88ec95c1f79d78a1f306/pkg/storage/replica.go#L933)):*
> ```Go
> 				r.raftMu.Lock()
> 				r.mu.Lock()
> 				if err := r.withRaftGroupLocked(true /* shouldCampaign */, func(raftGroup *raft.RawNode) (bool, error) {
> ```

can't this be done once outside the loop?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12465)*

**Comment by bdarnell** [comment]
:lgtm: Did you actually observe this or was it just a theory?

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_raft_test.go, line 3142 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12465#-KZDsA3fov-qgZgra5iF:-KZFnMXJQMa_O_C3Jajq:bemhryv) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c6adc67f2228da2c3a88ec95c1f79d78a1f306/pkg/storage/client_raft_test.go#L3142)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can you be more explicit here? if we change how these store IDs are assigned in the test this will silently do the wrong thing.
</blockquote></details>

Assumptions like this are pretty pervasive in tests that use multiTestContext.

---

*[pkg/storage/client_raft_test.go, line 3125 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12465#-KZFmmb4gV0DGrA6kNF_:-KZFmmb4gV0DGrA6kNFa:b-wppwtp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d404727194011290c3e94e2fd7040500edf60a70/pkg/storage/client_raft_test.go#L3125)):*
> ```Go
> 	// We use UserTableDataMin to avoid having the range activated to
> 	// gossip system table data.
> 	splitKey := keys.MakeRowSentinelKey(keys.UserTableDataMin)
> ```

Why not just `roachpb.Key("a")`? Aren't alphabetic keys always "normal"? We certainly use them that way in a lot of tests. 

---

*[pkg/storage/client_raft_test.go, line 3147 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12465#-KZFoY1nw_I6pY332E0w:-KZFoY1nw_I6pY332E0x:b7jtxpg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d404727194011290c3e94e2fd7040500edf60a70/pkg/storage/client_raft_test.go#L3147)):*
> ```Go
> 	}
> 
> 	// Send an increment and verify that initializes the Raft group.
> ```

Assert that the raft group was not initialized prior to the increment. 

---

*[pkg/storage/replica.go, line 928 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12465#-KZDqKDtNxixroNXpDmU:-KZFmBWXADrjF70IGp0r:b-ag76u1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c6adc67f2228da2c3a88ec95c1f79d78a1f306/pkg/storage/replica.go#L928)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why do you need this condition? it is already checked in withRaftGroupLocked
</blockquote></details>

My guess is that it's to avoid grabbing raftMu unnecessarily, but no matter what the answer is it needs a comment (especially since if withRaftGroupLocked *didn't* repeat this check, then you'd need to do it again after releasing and reacquiring r.mu).

---

*[pkg/storage/replica.go, line 933 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12465#-KZDquA0iuNRWHK-zDmp:-KZFqzqMfSm2LbWreaah:b-mpaiw7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c6adc67f2228da2c3a88ec95c1f79d78a1f306/pkg/storage/replica.go#L933)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can't this be done once outside the loop?
</blockquote></details>

Or even earlier, perhaps in Replica.Send? This is one place where a behind-on-raft replica could get stuck, but there could be others and it seems like a good idea to ensure that replicas receiving any kind of traffic have their raft groups activated. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12465#-:-KZFqgzOP_8B-H-WhiWc:bp3tvpu)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica.go, line 933 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12465#-KZDquA0iuNRWHK-zDmp:-KZMpN63lKBf9qlAkghk:bdohd3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c6adc67f2228da2c3a88ec95c1f79d78a1f306/pkg/storage/replica.go#L933)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Or even earlier, perhaps in Replica.Send? This is one place where a behind-on-raft replica could get stuck, but there could be others and it seems like a good idea to ensure that replicas receiving any kind of traffic have their raft groups activated. 
</blockquote></details>

Doing this check within the loop avoids another `Replica.mu` acquisition. The common case is there is nothing to do.

`redirectOnOrAcquireLease` seems to be called early in the lifetime of `{read,admin,write}` commands, so it seems ok to do this here. One oddity I just noticed: why are we going through the command queue for write commands before acquiring the lease. If the replica is not the leaseholder this command queue processing seems unnecessary. If the replica is the leaseholder can't we do it after we've checked the lease?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12465)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12465#-:-KZMqifr686GQvpNkee3:bnfp4nl)*

**Comment by spencerkimball** [comment]
Very observable.

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_raft_test.go, line 3113 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12465#-KZDsU8v5KVQDREbfnk-:-KZMjHkQp-DW2IvxCdM4:b-of20nm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c6adc67f2228da2c3a88ec95c1f79d78a1f306/pkg/storage/client_raft_test.go#L3113)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this is testing exactly the implementation, rather than the badness the implementation is meant to prevent.
</blockquote></details>

The policy that we always load Raft groups on receipt of messages is justified on its own, so I think this test is correct.

A different test, which would simulate the condition which led to the realization we should be doing this, would look entirely like this one, except would require some depressingly fancy choreography to get the two replicas in the "right" state. I'm not convinced it's useful in addition to this test.

---

*[pkg/storage/client_raft_test.go, line 3142 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12465#-KZDsA3fov-qgZgra5iF:-KZMmm7tgQevKYSK6Wsx:b-t4pfv9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c6adc67f2228da2c3a88ec95c1f79d78a1f306/pkg/storage/client_raft_test.go#L3142)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Assumptions like this are pretty pervasive in tests that use multiTestContext.
</blockquote></details>

Yes, if that changes we'll be SOL.

---

*[pkg/storage/client_raft_test.go, line 3125 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12465#-KZFmmb4gV0DGrA6kNF_:-KZMks4NmWBKJQt1SFFt:b-c2ix97) ([raw file](https://github.com/cockroachdb/cockroach/blob/d404727194011290c3e94e2fd7040500edf60a70/pkg/storage/client_raft_test.go#L3125)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Why not just `roachpb.Key("a")`? Aren't alphabetic keys always "normal"? We certainly use them that way in a lot of tests. 
</blockquote></details>

`roachpb.Key("a")` sorts before the beginning of the system config span, so if we split at "a", that RHS range is activated in order to gossip the system config data, ruining the test.

---

*[pkg/storage/client_raft_test.go, line 3147 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12465#-KZFoY1nw_I6pY332E0w:-KZMn4AhEWu5Pj6R9TLR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d404727194011290c3e94e2fd7040500edf60a70/pkg/storage/client_raft_test.go#L3147)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Assert that the raft group was not initialized prior to the increment. 
</blockquote></details>

Done.

---

*[pkg/storage/replica.go, line 928 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12465#-KZDqKDtNxixroNXpDmU:-KZMnMAcP1h0ZYsGk4O8:bej69lq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c6adc67f2228da2c3a88ec95c1f79d78a1f306/pkg/storage/replica.go#L928)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

My guess is that it's to avoid grabbing raftMu unnecessarily, but no matter what the answer is it needs a comment (especially since if withRaftGroupLocked *didn't* repeat this check, then you'd need to do it again after releasing and reacquiring r.mu).
</blockquote></details>

I've moved this into a method and added a comment.

---

*[pkg/storage/replica.go, line 933 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12465#-KZDquA0iuNRWHK-zDmp:-KZMnDk7oub-zybPlzK7:b-zfx0sd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c6adc67f2228da2c3a88ec95c1f79d78a1f306/pkg/storage/replica.go#L933)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Doing this check within the loop avoids another `Replica.mu` acquisition. The common case is there is nothing to do.

`redirectOnOrAcquireLease` seems to be called early in the lifetime of `{read,admin,write}` commands, so it seems ok to do this here. One oddity I just noticed: why are we going through the command queue for write commands before acquiring the lease. If the replica is not the leaseholder this command queue processing seems unnecessary. If the replica is the leaseholder can't we do it after we've checked the lease?
</blockquote></details>

What @petermattis said about why it was done here. However, I think doing inconsistent reads should probably make sure Raft group is initialized as well. The fact that that case slipped through the cracks makes me think @bdarnell is right and we should do this in `Replica.Send`.

@petermattis, do you think it's a problem to just slavishly acquire `raftMu` and `mu` to ensure the raft group is initialized? It's starting to feel like our locking story is verging on idiotic. :-(

As to why we go through the command queue first, it could take a while and lease may no longer be valid. Of course, we'd discover that at execution. Perhaps we should just check it twice?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12465#-:-KZMjBZLrLIiG67rehfT:b34gdxi)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica.go, line 933 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12465#-KZDquA0iuNRWHK-zDmp:-KZNCRy_UlMOlJz9ozHC:bgju0yr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c6adc67f2228da2c3a88ec95c1f79d78a1f306/pkg/storage/replica.go#L933)):*
> do you think it's a problem to just slavishly acquire raftMu and mu to ensure the raft group is initialized?

Problem? No. I imagine we'd eventually change it back to this for performance reasons.

> It's starting to feel like our locking story is verging on idiotic.

There is a lot of complexity in our locking rules, yet this doesn't feel like a good time to change them.

> As to why we go through the command queue first, it could take a while and lease may no longer be valid. Of course, we'd discover that at execution. Perhaps we should just check it twice?

Or perhaps the first check should be `redirectLease` since the common case for a follower receiving a request is that it knows who the leaseholder is. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12465)*

**Pull request merged**
