### PR TITLE
sql: add support for foreign key cascades in udfs

### PR DESCRIPTION
**Pull request by rharding6373**
This commit adds testing and makes some fixes to support foreign key cascades in UDFs.

Epic: CRDB-25388
Informs: #87289

Release note: none

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Nice! I only have a few nits.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110396#-:-NeLGYz8BGIKIhQo2saB:brsjzgx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @rharding6373)

___
*[`pkg/sql/logictest/testdata/logic_test/udf_fk` line 258 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110396#-NeLFHebEza3VfJyTQ72:-NeLFHebEza3VfJyTQ73:b-no9dqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/41d81f00a78707e0aa757a89b217c639007d18b7/pkg/sql/logictest/testdata/logic_test/udf_fk#L258)):*
> ```
> 
> statement ok
> SELECT f_fk_p_cascade(1, 2);
> ```

nit: since we use RETURNING * in our UDFs might as well as double-check what's being returned in all cases, and not only when multiple UDFs are invoked in a single stmt.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_fk` line 424 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110396#-NeLEno1-MsywLOuxYK_:-NeLEno1-MsywLOuxYKa:bnyd4kp) ([raw file](https://github.com/cockroachdb/cockroach/blob/41d81f00a78707e0aa757a89b217c639007d18b7/pkg/sql/logictest/testdata/logic_test/udf_fk#L424)):*
> ```
> query IT rowsort
> SELECT
> 	(SELECT * FROM (VALUES ((SELECT x FROM (VALUES (1)) AS s (x)) + y))),
> ```

nit: there are tabs here (which I think we generally try to avoid (?)).
___
*[`pkg/sql/logictest/testdata/logic_test/udf_fk` line 446 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110396#-NeLFinLBUYGZ8KF4H6L:-NeLFinLBUYGZ8KF4H6M:b-4k3p4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/41d81f00a78707e0aa757a89b217c639007d18b7/pkg/sql/logictest/testdata/logic_test/udf_fk#L446)):*
> ```
> 12
> 13
> ```

nit: it might be interesting to a test case where the first invocation of mutating UDF succeeds but the second one fails, so the stmt errors out and ensure that the tables aren't modified.

It also might be good to have a test case where we have a cascade and a non-cascade FK check (e.g. we have `parent_cascade` and `child_cascade` linked by CASCADE, but also we have `grandchild_fk` which has FK with `child_cascade` but without CASCADE (or something along those lines)). WDYT?

**Review by mgartner — APPROVED** [review]
:LGTM: Nice! Cool to see that it just sort of worked with minimal changes after the other work you put into this. I left a few suggestions for some additional tests, if you agree they could be valuable.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110396#-:-NePTlgL3_SS88OnXMTU:b4rrl6)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @rharding6373, and @yuzefovich)

___
*[`pkg/sql/logictest/testdata/logic_test/udf_fk` line 446 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110396#-NeLFinLBUYGZ8KF4H6L:-NePScu46yBMabIEMnXj:b-67x8y6) ([raw file](https://github.com/cockroachdb/cockroach/blob/41d81f00a78707e0aa757a89b217c639007d18b7/pkg/sql/logictest/testdata/logic_test/udf_fk#L446)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: it might be interesting to a test case where the first invocation of mutating UDF succeeds but the second one fails, so the stmt errors out and ensure that the tables aren't modified.

It also might be good to have a test case where we have a cascade and a non-cascade FK check (e.g. we have `parent_cascade` and `child_cascade` linked by CASCADE, but also we have `grandchild_fk` which has FK with `child_cascade` but without CASCADE (or something along those lines)). WDYT?
</blockquote></details>

To add to those suggestions, these tests might be interesting:

* A UDF with multiple statements that cascade to the same table.
* An update/delete that cascades to multiple rows in the same table (can add this to one of the setups above pretty easily I think)
* A self-referencing FK cascade (a table with a foreign key on the same table)

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110396#-:-Nel2eI86j6P8ox928Gq:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @rharding6373 and @yuzefovich)

___
*[`pkg/sql/apply_join.go` line 341 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110396#-NeeAQSQEG4eCW-W0FM2:-NeeAQSQEG4eCW-W0FM3:b-1fjpzm) ([raw file](https://github.com/cockroachdb/cockroach/blob/41d81f00a78707e0aa757a89b217c639007d18b7/pkg/sql/apply_join.go#L341)):*
> ```Go
> 		// when executing the outer query.
> 		defer func() {
> 			plan.subqueryPlans = nil
> ```

It's not obvious where `subqueryPlans` becomes non-nil since we check `len(plan.subqueryPlans) != 0`. Can you clarify that?

**Review by rharding6373 — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110396#-:-NeoCeXP3Oiy6FQEQCKW:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball, @mgartner, and @yuzefovich)

___
*[`pkg/sql/logictest/testdata/logic_test/udf_fk` line 258 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110396#-NeLFHebEza3VfJyTQ72:-NeiId0oB-vPGAa-gDad:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/41d81f00a78707e0aa757a89b217c639007d18b7/pkg/sql/logictest/testdata/logic_test/udf_fk#L258)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: since we use RETURNING * in our UDFs might as well as double-check what's being returned in all cases, and not only when multiple UDFs are invoked in a single stmt.
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_fk` line 424 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110396#-NeLEno1-MsywLOuxYK_:-NeiIkuvE6Ubu37sPYkM:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/41d81f00a78707e0aa757a89b217c639007d18b7/pkg/sql/logictest/testdata/logic_test/udf_fk#L424)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: there are tabs here (which I think we generally try to avoid (?)).
</blockquote></details>

Fixed.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_fk` line 446 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110396#-NeLFinLBUYGZ8KF4H6L:-NeoC5rl2eQEO2aqdZ4H:b-adg07k) ([raw file](https://github.com/cockroachdb/cockroach/blob/41d81f00a78707e0aa757a89b217c639007d18b7/pkg/sql/logictest/testdata/logic_test/udf_fk#L446)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

To add to those suggestions, these tests might be interesting:

* A UDF with multiple statements that cascade to the same table.
* An update/delete that cascades to multiple rows in the same table (can add this to one of the setups above pretty easily I think)
* A self-referencing FK cascade (a table with a foreign key on the same table)
</blockquote></details>

Thanks for the suggestions! Added these tests. Want to note (since Marcus and I were discussing this offline) that the self-referencing FK cascade test is correct -- I thought it wasn't compared to postgres, but I was accidentally omitting the cascades.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110396#-:-NeoKxnx7uUVW23xGfDT:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @rharding6373)

___
*[`pkg/sql/logictest/testdata/logic_test/udf_fk` line 309 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110396#-NeoKZXB569tginxNviD:-NeoKZXB569tginxNviE:bs1vyph) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f4c7380d82d11be7f85e17f09d8143341082783/pkg/sql/logictest/testdata/logic_test/udf_fk#L309)):*
> ```
> 
> statement ok
> DROP TABLE child_cascade;
> ```

nit: looks like we're recreating `child_cascade` table with the same schema, why not use TRUNCATE?

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110396)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @yuzefovich)

___
*[`pkg/sql/logictest/testdata/logic_test/udf_fk` line 309 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110396#-NeoKZXB569tginxNviD:-NeoRXmAEEclNUZ2sjq1:b6eixsz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f4c7380d82d11be7f85e17f09d8143341082783/pkg/sql/logictest/testdata/logic_test/udf_fk#L309)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: looks like we're recreating `child_cascade` table with the same schema, why not use TRUNCATE?
</blockquote></details>

They aren't actually the same. The first version doesn't have `UNIQUE`, allowing us to test cascading updates to multiple rows. We need `UNIQUE` when we cascade to the `grandchild_cascade` table. I added some comments to the test to help explain what each series of statements is designed to test in the hopes it will clarify this in the future.

**Review by yuzefovich — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110396)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @rharding6373)

___
*[`pkg/sql/logictest/testdata/logic_test/udf_fk` line 309 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110396#-NeoKZXB569tginxNviD:-NeoXQl5ADjaEpKfdyUM:b-kufkxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f4c7380d82d11be7f85e17f09d8143341082783/pkg/sql/logictest/testdata/logic_test/udf_fk#L309)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

They aren't actually the same. The first version doesn't have `UNIQUE`, allowing us to test cascading updates to multiple rows. We need `UNIQUE` when we cascade to the `grandchild_cascade` table. I added some comments to the test to help explain what each series of statements is designed to test in the hopes it will clarify this in the future.
</blockquote></details>

I see, thanks!

**Comment by rharding6373** [comment]
TFTRs!

bors r+

**Pull request merged**
