### PR TITLE
sqlccl: add jobs records for csv import

### PR DESCRIPTION
**Pull request by dt**
no progress tracking or resuability stuff yet, just informational records to start with

### CODE REVIEW

**Comment by benesch** [comment]
Reviewed 11 of 11 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/sqlccl/csv.go, line 774 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17877#-KsG3sttfL5J-Ur9TJBm:-KsG3sttfL5J-Ur9TJBn:b54atdl) ([raw file](https://github.com/cockroachdb/cockroach/blob/10532a303fbb47103c4f794dfa581d39bc113ea1/pkg/ccl/sqlccl/csv.go#L774)):*
> ```Go
> 			},
> 		})
> 		if err := job.Created(ctx, nil); err != nil {
> ```

`job.Created(ctx, jobs.WithoutCancel)` for readability. (`jobs.WithoutCancel == nil`)

---

*[pkg/ccl/sqlccl/csv_test.go, line 505 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17877#-KsG3WVal-KO-20gBdrB:-KsG3WVal-KO-20gBdrC:brujtxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/10532a303fbb47103c4f794dfa581d39bc113ea1/pkg/ccl/sqlccl/csv_test.go#L505)):*
> ```Go
> 			if expected, actual := "import t CSV conversion", jobDesc; expected != actual {
> 				t.Fatalf("expected %v, got %v", expected, actual)
> 			}
> ```

I think you can reuse `verifySystemJob` here, which will additionally verify the type and descriptor IDs. (Getting the expected descriptor IDs will require a `sqlutils.QueryTableID`, but worth it, I think.)

---

*[pkg/sql/jobs/jobs.proto, line 65 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17877#-KsG2facRKt-ascbdSjg:-KsG2facRKt-ascbdSjh:bfrfuj) ([raw file](https://github.com/cockroachdb/cockroach/blob/10532a303fbb47103c4f794dfa581d39bc113ea1/pkg/sql/jobs/jobs.proto#L65)):*
> ```protobuf
>     repeated string uris = 2 [(gogoproto.customname) = "URIs"];
>     roachpb.CSVOptions options = 3;
>     string backupPath = 4;
> ```

`backup_path` by convention.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17877)*

**Comment by dianasaur323** [comment]
Is this going to show up in the admin UI if it's part of the jobs table? If so, what would the treatment look like if we aren't progress tracking?

Also, if we are putting this into jobs, should we also allocate time to cancel and resume in the 1.2, or will that be part of the stabilization of distributed ingest?

**Comment by mjibson** [comment]
Did you mean "resumability" in the commit message? CSV stuff LGTM.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17877#-:-KsHOyXKj6eg-RfwOcD-:b-pb8uon)*

**Comment by dt** [comment]
Fixed.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/sqlccl/csv_test.go, line 505 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17877#-KsG3WVal-KO-20gBdrB:-KsJkaZ-KBbGTxxt8AjL:b4wykrf) ([raw file](https://github.com/cockroachdb/cockroach/blob/10532a303fbb47103c4f794dfa581d39bc113ea1/pkg/ccl/sqlccl/csv_test.go#L505)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I think you can reuse `verifySystemJob` here, which will additionally verify the type and descriptor IDs. (Getting the expected descriptor IDs will require a `sqlutils.QueryTableID`, but worth it, I think.)
</blockquote></details>

Done. (there are no descriptor IDs since it isn't a table yet, and may never be in the transform-only case.)

---

*[pkg/sql/distsqlrun/processors.proto, line 445 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17877#-KsJb0qcCbXYUD22Q4Td:-KsJkfLWFyspkjhtUH1j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/405613a4cbcdd30fa7dac009a89a79fb6a16cbf6/pkg/sql/distsqlrun/processors.proto#L445)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

could renumber here if you feel so inclined
</blockquote></details>

Done.

---

*[pkg/sql/jobs/jobs.proto, line 62 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17877#-KsJbRKcGKkbgifsW2Sh:-KsJliXMYpYUraoDNf9G:b-4dnzut) ([raw file](https://github.com/cockroachdb/cockroach/blob/10532a303fbb47103c4f794dfa581d39bc113ea1/pkg/sql/jobs/jobs.proto#L62)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

we usually serialize sqlbase.Descriptor. not saying this one needs to be, just want to make sure you've though through whether it makes sense to have the future flexibility (and more for new descriptor types than for DatabaseDescriptor)
</blockquote></details>

Eh. I'm not a huge fan of the untyped field and casting -- if we wanted a different desc type later, I'd rather put it in a new, differently typed field and have handling code look at which field is set (and we can safely rename for clarity if that happens).

Also, in this case, the containing message is called `Table`, so I'm relatively comfortable with the current specificity.

That said, if you feel strongly that the convention has value, I'm fine changing it too.

---

*[pkg/sql/jobs/jobs.proto, line 65 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17877#-KsG2facRKt-ascbdSjg:-KsJmDrHG5d41RTXriM7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/10532a303fbb47103c4f794dfa581d39bc113ea1/pkg/sql/jobs/jobs.proto#L65)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

`backup_path` by convention.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17877#-:-KsJp5Tu6JNZL1lawT1J:bt2vr1b)*

**Comment by dt** [comment]
@dianasaur323 added some very basic progress updates to the job when used in the default (local) mode as that was trivial.

**Comment by mjibson** [comment]
Review status: 4 of 16 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/sqlccl/csv.go, line 136 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/17877#-KsQGoEnEBeKk90uCotS:-KsQGoEorUS5d6Mro_gH:bzg6ali) ([raw file](https://github.com/cockroachdb/cockroach/blob/6edb75b9421fa308ca57159ce989a8d2c5777b53/pkg/ccl/sqlccl/csv.go#L136)):*
> ```Go
> 		return err
> 	})
> 	if job != nil {
> ```

These have to be inside the errgroup go routines, otherwise they will always execute immediately and the user would only see the final (3/4) progress.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17877)*

**Comment by dt** [comment]
@mjibson doh, yep, i misread what that was doing completely, thanks! fixed.

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 4 of 16 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17877#-:-KsahzF3ESo1wlWde4nR:bnfp4nl)*

**Pull request merged**
