### PR TITLE
server: fix sync on setting overrides for secondary tenants

### LINKED ISSUE #110560: serverutils: flake in tests that use ALTER TENANT SET CLUSTER SETTING
**Describe the problem**

Found by @miretskiy in #110516:
```
=== RUN   TestAlterChangefeedSwitchFamily/kafka
    alter_changefeed_test.go:282: failed to start feed for job 0: pq: rangefeeds require the kv.rangefeed.enabled setting. See https://www.cockroachlabs.com/docs/v23.2/change-data-capture.html#enable-rangefeeds-to-reduce-latency
```

In a nutshell the test does this:

1. `StartServer()`
2. `ALTER TENANT ALL SET CLUSTER SETTING kv.rangefeed.enabled = true` via SQL
3. `StartTenant()`

then the error happens when the test uses the tenant service.

The problem is that the setting override at step (2) has not yet propagated through the rangefeed when `StartTenant` is invoked.

**Expected behavior**

`StartTenant` should also restart the rangefeed on the setting overrides (currnetly it only restarts the rangefeed on the tenant metadata and capabilities).

Jira issue: CRDB-31506
Epic: CRDB-18499

### PR DESCRIPTION
**Pull request by knz**
Improves/completes #110789
Prerequisite for tests in #110758.
Fixes #110560.
Epic: CRDB-6671

The previous patch in this area was merely restarting the rangefeed but did not actually wait for the initial update event to be received.

This patch fixes it.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Seems good to me, but should we also apply the same change to the other place (tenant caps watcher) where this code was mostly copied from?

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110947#-:-NekmLWd7ohru3Lx1iyb:b-w9456t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

**Comment by knz** [comment]
The cap watcher already had proper wait code, which is used in the TestServer code just underneath the call to TestRestart.

**Comment by yuzefovich** [comment]
I see the wait code in one (`WaitForTenantCapabilities`) out of two places where `TestingRestart` is called - do we not want to wait in `waitForTenantReadinessImpl`? Even if the answer is no, it'd be great if we could unify the waiting between three places that have this `TestingRestart` method.

**Review by yuzefovich — APPROVED** [review]
Discussed offline - we do have waiting in place in both places. :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110947#-:-Nemz9eH88gPnk2F979w:bz2n3gw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @stevendanna)

**Comment by knz** [comment]
Filed followup issue to clean this up: #110969

**Comment by knz** [comment]
bors r=yuzefovich

**Pull request merged**
