### PR TITLE
sql: replace field accesses of Immutable.PrimaryIndex and Immutable.Indexes with method calls

### PR DESCRIPTION
**Pull request by postamar**
Right now, most of the time, we obtain `descpb.IndexDescriptor` values either via getters (`GetPrimaryIndex()` or `GetPublicNonPrimaryIndexes()`) or by direct field access on `tabledesc.Immutable` (`PrimaryIndex` and `Indexes`). It's the same thing either way so it doesn't matter, however implementing https://github.com/cockroachdb/cockroach/issues/57465 means changing the return types on those getters as well as (eventually at least) using those getters instead anyway. This PR is a refactor to make the upcoming changes more tractable.

Note that some of the field accesses were writes on `tabledesc.Mutable` and therefore needed to be replaced by setter calls. This change is the first of the 4 commits in this PR. The remaining commits are one per getter: `GetPrimaryIndexID()`, `GetPrimaryIndex()` and `GetPublicNonPrimaryIndexes()`. Reading one commit at a time should make the review a lot easier.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
The method accesses to slices give me bad feeling for a reason I'm not all the way in touch with right now. Makes me wonder what the right direction for iterating components of a descriptor should look like. 

Baby steps but good stuff on the right path. 

> Reviewed 14 of 14 files at r1, 13 of 30 files at r2, 14 of 35 files at r3, 33 of 33 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57783#-:-MOFQEuQ0fTvWOQyZ1OS:b-bil776)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @postamar)

___
*[pkg/sql/alter_primary_key.go, line 311 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57783#-MOFNzs19MZn6b9znLOB:-MOFNzs19MZn6b9znLOC:b9x67wc) ([raw file](https://github.com/cockroachdb/cockroach/blob/91b32fcc431d010858b0a0e226d750f73c2897c5/pkg/sql/alter_primary_key.go#L311)):*
> ```
> 	primaryIndex := *tableDesc.GetPrimaryIndex()
> 	primaryIndex.Disabled = false
> 	tableDesc.SetPrimaryIndex(primaryIndex)
> ```
Stylistically, how do you feel about putting this all in a block? I personally think it makes these sort of stanzas visually easier to parse and avoid polluting the scope with variables like `primaryIndex` later in the method. This some comment applies generally throughout this commit. 

```go
{
    primaryIndex := *tableDesc.GetPrimaryIndex()
    primaryIndex.Disabled = false
    table.SetPrimaryIndex(primaryIndex)
}
```

___
*[pkg/sql/create_stats.go, line 372 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57783#-MOFPG3U6orfwuiF4LWJ:-MOFPG3U6orfwuiF4LWK:b7nefe4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b12acf604fc5c8871e12a9317ae6a9fb8b5cad1c/pkg/sql/create_stats.go#L372)):*
> ```Go
> 
> 	// Add column stats for each secondary index.
> 	for i := range desc.GetPublicNonPrimaryIndexes() {
> ```

I feel like this code would benefit from just assigning a variable at the top of the loop and then just using them. Then in the loop, you could just take a pointer to the index itself. Like

```go
indexes := descs.GetPublicNonPrimaryIndexes()
for i := range indexes {
    index := &indexes[i]
    ...
``` 
___
*[pkg/sql/create_stats.go, line 372 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57783#-MOFPQbl0oEdDK-7q4C2:-MOFPQbl0oEdDK-7q4C3:b-yx01yn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b12acf604fc5c8871e12a9317ae6a9fb8b5cad1c/pkg/sql/create_stats.go#L372)):*
> ```Go
> 
> 	// Add column stats for each secondary index.
> 	for i := range desc.GetPublicNonPrimaryIndexes() {
> ```

Aside: Indexes or Indices? a flamewar bikeshed for the ages.
___
*[pkg/sql/catalog/tabledesc/table_desc.go, line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57783#-MOFOcI_ArfhgccXj0bx:-MOFOcI_ArfhgccXj0by:b-x8akvv) ([raw file](https://github.com/cockroachdb/cockroach/blob/91b32fcc431d010858b0a0e226d750f73c2897c5/pkg/sql/catalog/tabledesc/table_desc.go#L134)):*
> ```Go
> // RemoveAllPublicNonPrimaryIndexes removes all secondary indexes
> func (desc *Mutable) RemoveAllPublicNonPrimaryIndexes() {
> 	desc.Indexes = desc.Indexes[:0]
> ```

I wonder if this is really better than just setting it to nil.

**Review by postamar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57783)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @dt)

___
*[pkg/sql/alter_primary_key.go, line 311 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57783#-MOFNzs19MZn6b9znLOB:-MOIhDOY5mKjjJJdYUR1:b-s3qpsh) ([raw file](https://github.com/cockroachdb/cockroach/blob/91b32fcc431d010858b0a0e226d750f73c2897c5/pkg/sql/alter_primary_key.go#L311)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	primaryIndex := *tableDesc.GetPrimaryIndex()
> 	primaryIndex.Disabled = false
> 	tableDesc.SetPrimaryIndex(primaryIndex)
> ```
Stylistically, how do you feel about putting this all in a block? I personally think it makes these sort of stanzas visually easier to parse and avoid polluting the scope with variables like `primaryIndex` later in the method. This some comment applies generally throughout this commit. 

```go
{
    primaryIndex := *tableDesc.GetPrimaryIndex()
    primaryIndex.Disabled = false
    table.SetPrimaryIndex(primaryIndex)
}

</blockquote></details>

Agreed & done.
___
*[pkg/sql/create_stats.go, line 372 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57783#-MOFPG3U6orfwuiF4LWJ:-MOIhbXz9DfYZIQyjD6u:b99h443) ([raw file](https://github.com/cockroachdb/cockroach/blob/b12acf604fc5c8871e12a9317ae6a9fb8b5cad1c/pkg/sql/create_stats.go#L372)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I feel like this code would benefit from just assigning a variable at the top of the loop and then just using them. Then in the loop, you could just take a pointer to the index itself. Like

```go
indexes := descs.GetPublicNonPrimaryIndexes()
for i := range indexes {
    index := &indexes[i]
    ...
``` 
</blockquote></details>

I agree in principle however in this case I believe we should leave these be and the reason is I'm following this PR with another very soon which replaces _all_ of these loops with calls to new methods:
```
ForeachPublicNonPrimaryIndex(func (*descpb.IndexDescriptor) error) error
FindPublicNonPrimaryIndex(func (*descpb.IndexDescriptor) (bool, error)) (*descpb.IndexDescriptor, int, error)
```
I remember you telling me the go compiler is now smart enough to do the right thing and not incur too much of a performance penalty (if any). As far as I'm concerned these functional constructs are definitely the way to go here because:
1. I don't like the fact that `GetPublicNonPrimaryIndexes()` returns a slice either;
2. it's going to be a lot easier to change the argument type of the argument func than dealing somehow make `GetPublicNonPrimaryIndexes()` return a slice of interfaces instead.
___
*[pkg/sql/create_stats.go, line 372 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57783#-MOFPQbl0oEdDK-7q4C2:-MOIkUG60XBFTrVbYcCU:b-lgncf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b12acf604fc5c8871e12a9317ae6a9fb8b5cad1c/pkg/sql/create_stats.go#L372)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Aside: Indexes or Indices? a flamewar bikeshed for the ages.
</blockquote></details>

Yes like the very productive viruses vs. virii debate.
___
*[pkg/sql/catalog/tabledesc/table_desc.go, line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57783#-MOFOcI_ArfhgccXj0bx:-MOIkg5mDQ9hSNNJIZ3C:b-3nylw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/91b32fcc431d010858b0a0e226d750f73c2897c5/pkg/sql/catalog/tabledesc/table_desc.go#L134)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I wonder if this is really better than just setting it to nil. 
</blockquote></details>

I looked into this and really this method should be replaced with a `ReplaceAllPublicNonPrimaryIndexes()` method, in which case keeping the reference to the backing array makes more sense.

**Review by postamar — COMMENTED** [review]
Thanks for the feedback! RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57783#-:-MOIpuar4dZlbODSF3tQ:bki1zy3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @dt)

___
*[pkg/sql/alter_primary_key.go, line 311 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57783#-MOFNzs19MZn6b9znLOB:-MOIplVX2cTRaqYh-ZYX:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/91b32fcc431d010858b0a0e226d750f73c2897c5/pkg/sql/alter_primary_key.go#L311)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Agreed & done.
</blockquote></details>

Done

**Review by ajwerner — APPROVED** [review]
:lgtm: after a rebase

> Reviewed 2 of 62 files at r5, 1 of 30 files at r6, 1 of 35 files at r7, 6 of 33 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57783#-:-MOmNTkL2RzoQTeZRSea:b-t5rt2i)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @dt)

**Comment by postamar** [comment]
I had to push some changes to this branch in light of having merged https://github.com/cockroachdb/cockroach/pull/58008 and wrt my ongoing index interface work. These can be boiled down to:
1. Rebasing etc.
2. Changing the meaning of the `indexOrdinal` argument in the new setters to match the existing `indexIdx` concept which I wasn't really aware of when I first submitted this: 0 refers to the primary index, 1 to the first secondary index, etc.
3. I'm actually OK with reading the `Indexes` and `PrimaryIndex` fields of `descpb.TableDescriptor` inside the definitions of methods for `tabledesc.wrapper`, `Immutable` and `Mutable` in `pkg/sql/catalog/tabledesc`, especially now that https://github.com/cockroachdb/cockroach/pull/58008 has been merged. I therefore removed the changes pertaining to that.

**Review by ajwerner — APPROVED** [review]
I'm still good with this.

One thing I'm thinking as we continue this work is that the use of ordinals to refer to indexes is a bit scary in the context of some of these accessors as the type system doesn't ensure that you pass the ordinal to the method that it corresponds to. I think you've made this all a bit more sane, however, I wonder if it makes sense in the long run to make everything ID oriented and to just maintain the mapping. I do not think I'm worried about the performance implications of that. Just food for thought. 

> Reviewed 1 of 62 files at r9, 2 of 27 files at r10, 3 of 33 files at r11, 8 of 30 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57783#-:-MPAbBlT-zg3V3tbWdgN:b-3y9ni)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @dt)

___
*[pkg/sql/drop_index.go, line 463 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/57783#-MPAah737vDY5btqwj6D:-MPAah746uBxjXy0pkLc:b-j47kpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ec5e5829c198ad75128a93eea61ea5e242302ca/pkg/sql/drop_index.go#L463)):*
> ```Go
> 
> 	found := false
> 	for i, idxEntry := range tableDesc.GetPublicNonPrimaryIndexes() {
> ```

Just food for though. It's pretty subtle that this code isn't hazardous. Namely if it didn't break after the call to `RemovePublicNonPrimaryIndex` then we'd have trouble. I get that that's the case all over the place in this code. It's just bad.

**Review by postamar — COMMENTED** [review]
Thanks for giving this another look. As it turns out, I'm now thinking of not dealing with ordinals, and instead going with interface slices after all.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57783#-:-MPAqKGLAxtJKAVRXBCC:bby1maf)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @dt)

___
*[pkg/sql/drop_index.go, line 463 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/57783#-MPAah737vDY5btqwj6D:-MPAq3wO17WY2JkY4uxp:b-lmlxyq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ec5e5829c198ad75128a93eea61ea5e242302ca/pkg/sql/drop_index.go#L463)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Just food for though. It's pretty subtle that this code isn't hazardous. Namely if it didn't break after the call to `RemovePublicNonPrimaryIndex` then we'd have trouble. I get that that's the case all over the place in this code. It's just bad. 
</blockquote></details>

Agreed, especially considering the following block is so big. This is going to be a good use case for the future `FindPublicNonPrimaryIndex` method.

**Pull request merged**
