### PR TITLE
server: Add text format to metrics page, using prometheus formatter

### PR DESCRIPTION
**Pull request by madelynnblue**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7895)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Could you add in the commit message the endpoint at which this is now served, and link to it from  the `./debug/` overview page?

**Comment by tschottdorf** [comment]
I just noticed that we already serve https://golang.org/pkg/expvar/ on `/debug/vars`. Is there any chance for integrating with it or does is simply get replaced?

**Comment by mjibson** [comment]
I've modified the commit message to include the debug page link and instructions for integrating with prometheus. The prometheus data export format is different enough from the expvar page that I'm not sure it can be integrated. We could remove it in a later PR.

**Comment by tschottdorf** [comment]
As far as I can tell, the "text output" is really the prometheus format. Would be good to label it as such (or to clarify).

Needs a (basic) test. Other than that the code LGTM, just curious about whether we should use Histogram or Summary.

---

Reviewed 4 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/debug.go, line 129 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7895#-KN119q7Iv1zO3IIz3xN:-KN119q7Iv1zO3IIz3xO:1339004377) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bd3a8cf8a33d04ad1ccad9ae2f1135b45277f42/server/debug.go#L129)):*
> ```Go
> 	// onto the /debug/metrics endpoint. It includes all expvars registered globally and
> 	// all metrics registered on the DefaultRegistry.
> 	exp.Exp(metrics.DefaultRegistry)
> ```

Don't think we need that now (we're shadowing it, anyway).

---

*[server/status.go, line 96 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7895#-KN123MRVLY5vPZiUcIi:-KN123MRVLY5vPZiUcIj:-1640369736) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bd3a8cf8a33d04ad1ccad9ae2f1135b45277f42/server/status.go#L96)):*
> ```Go
> 	// statusMetricsPattern exposes transient stats for a node.
> 	statusMetricsPattern = statusPrefix + "metrics/:node_id"
> 	// statusVars exposes plain-text metrics for monitoring consumption.
> ```

s/plain-text/prometheus/?

---

*[util/metric/metric.go, line 197 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7895#-KN13Dp131lvHXQuqVXg:-KN13Dp131lvHXQuqVXh:350864103) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bd3a8cf8a33d04ad1ccad9ae2f1135b45277f42/util/metric/metric.go#L197)):*
Have you consciously decided against `&prometheusgo.Histogram`? If so, mind explaining that decision? I just glanced over https://prometheus.io/docs/practices/histograms/ and found this:

>
Two rules of thumb:
>
If you need to aggregate, choose histograms.
>
Otherwise, choose a histogram if you have an idea of the range and distribution of values that will be observed. Choose a summary if you need an accurate quantile, no matter what the range and distribution of the values is.

My intuition was that we want a histogram here. See also #7896.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7895#-:-KN11wqapLlllsX-uT1P:-1455264091)*

**Comment by mjibson** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/debug.go, line 129 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7895#-KN119q7Iv1zO3IIz3xN:-KN3Zr5EZ4HBHjlX2I21:-977115241) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bd3a8cf8a33d04ad1ccad9ae2f1135b45277f42/server/debug.go#L129)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Don't think we need that now (we're shadowing it, anyway).
</details>
I think it can get removed, but in another PR that addresses expvar and exp.Exp specifically. I've opened #7923 to track that.

---

*[server/status.go, line 96 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7895#-KN123MRVLY5vPZiUcIi:-KN3YLHQ_TMS1c--mk_T:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bd3a8cf8a33d04ad1ccad9ae2f1135b45277f42/server/status.go#L96)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> s/plain-text/prometheus/?
</details>
Done.

---

*[util/metric/metric.go, line 197 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7895#-KN13Dp131lvHXQuqVXg:-KN3_2kEESAOMYnfH3tn:-225136060) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bd3a8cf8a33d04ad1ccad9ae2f1135b45277f42/util/metric/metric.go#L197)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Have you consciously decided against `&prometheusgo.Histogram`? If so, mind explaining that decision? I just glanced over https://prometheus.io/docs/practices/histograms/ and found this:
> 
> >
> Two rules of thumb:
> >
> If you need to aggregate, choose histograms.
> >
> Otherwise, choose a histogram if you have an idea of the range and distribution of values that will be observed. Choose a summary if you need an accurate quantile, no matter what the range and distribution of the values is.
> 
> My intuition was that we want a histogram here. See also #7896.
</details>
Yes, discussion between Matt Tracy and me resulted in a decision to use Summary because we have too many buckets. Once that goes down we can switch to or add the Histogram type.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7895)*

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[server/status_test.go, line 550 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7895#-KN7fpyJX-SWGjAdvxY7:-KN7fpyJX-SWGjAdvxY8:566816755) ([raw file](https://github.com/cockroachdb/cockroach/blob/599b0ec81a0e9cc5aec2983a2f6eae9914b2b6f3/server/status_test.go#L550)):*
> ```Go
> 	if body, err := getText(s.AdminURL() + "/_status/vars"); err != nil {
> 		t.Fatal(err)
> 	} else if !bytes.Contains(body, []byte("# TYPE sql_bytesout counter\nsql_bytesout 0")) {
> ```

maybe better to avoid matching the `0`.

---

*[server/status_test.go, line 551 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7895#-KN7foQUiS9GUqBGC9Io:-KN7foQUiS9GUqBGC9Ip:281162258) ([raw file](https://github.com/cockroachdb/cockroach/blob/599b0ec81a0e9cc5aec2983a2f6eae9914b2b6f3/server/status_test.go#L551)):*
> ```Go
> 		t.Fatal(err)
> 	} else if !bytes.Contains(body, []byte("# TYPE sql_bytesout counter\nsql_bytesout 0")) {
> 		t.Errorf("expected sql_bytesout")
> ```

print actual body.

---

*[util/metric/metric.go, line 197 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7895#-KN13Dp131lvHXQuqVXg:-KN7fwEv9SJh8u5XiiiD:27069141) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bd3a8cf8a33d04ad1ccad9ae2f1135b45277f42/util/metric/metric.go#L197)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Yes, discussion between Matt Tracy and me resulted in a decision to use Summary because we have too many buckets. Once that goes down we can switch to or add the Histogram type.
</details>
Ok. Don't want to block this PR on it, but the repeated complaints about the bucket size could probably be addressed by a 30 minute pow-wow and subsequent changing of histogram settings (they're currently very high). I saw this tracked somewhere, so it's ok for now but add a comment that a breaking change here is not unlikely.

---

*[util/metric/registry.go, line 119 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7895#-KN7gFFmdTAFELxAG_Z6:-KN7gFFmdTAFELxAG_Z7:-193895040) ([raw file](https://github.com/cockroachdb/cockroach/blob/599b0ec81a0e9cc5aec2983a2f6eae9914b2b6f3/util/metric/registry.go#L119)):*
> ```Go
> 	var ret error
> 	r.Each(func(name string, v interface{}) {
> 		if metric, ok := v.(PrometheusExportable); ok {
> ```

```go
if ret != nil {
  return
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7895#-:-KN7gKPHknstt2kcBUtc:1417088721)*

**Comment by mjibson** [comment]
Adding the docs tag because we should document that users can monitor cockroach with prometheus. The document should include a sample prometheus.yml config.

**Pull request merged**
