### PR TITLE
opt: Convert InnerJoinApply + Zip to ProjectSet

### LINKED ISSUE #31706: Unable to decorelate query
**To Reproduce**

Ran query in orm and fails.

**Expected behavior**
Expect this query to work and I'm not sure how to manually decorellate.

SQL Error [XX000]: ERROR: could not decorrelate subquery
  ERROR: could not decorrelate subquery
  ERROR: could not decorrelate subquery

**Additional data / screenshots**
```SELECT a0."id", a0."body", a0."description", a0."title", a0."slug", a0."tag_list", a0."user_id", a0."created_at", a0."updated_at" FROM "articles" AS a0 WHERE (exists (select * from unnest(a0."tag_list") tag where tag = 'dragons')) ORDER BY a0."created_at" LIMIT 10 OFFSET 0
```

**Environment:**
 - v2.1.0-beta.20181015
 - Server OS: [e.g. Linux/Distrib]
 - Client app elixir postgres

### PR DESCRIPTION
**Pull request by rytaft**
This commit creates a new relational operator called ProjectSet,
which zips through a list of generators for every row of the input.

As a reminder, a functional zip over generators a,b,c returns tuples of
values from a,b,c picked "simultaneously". NULLs are used when a generator is
"shorter" than another.  For example:

   zip([1,2,3], ['a','b']) = [(1,'a'), (2,'b'), (3, null)]

ProjectSet corresponds to a relational operator project(R, a, b, c, ...)
which, for each row in R, produces all the rows produced by zip(a, b, c, ...)
with the values of R prefixed. Formally, this performs a lateral cross join
of R with zip(a,b,c).

This operator replaces Zip, which was a non-standard relational operator in
the optimizer. Zip had to be joined with its input via an InnerJoinApply cross
join, which caused some difficulties in creating decorrelation patterns. As a
result, certain queries were not decorrelated that should have been fairly
easy to decorrelate.

As part of this commit, the decorrelation patterns have been updated to
allow decorrelation of generator functions inside EXISTS.

Fixes #31706

Release note (sql change): Many queries containing a correlated EXISTS
subquery with a generator function can now be decorrelated and executed
successfully. Previously, these queries caused a decorrelation error.

### CODE REVIEW

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31922)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/statistics_builder.go, line 1662 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31922#-LQ9n8-x3wCKiak5-8o8:-LQ9n8-x3wCKiak5-8o9:b-wo3k3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/d893d3f24c1220b7e5b2d2f37c31b308a87810f4/pkg/sql/opt/memo/statistics_builder.go#L1662)):*
> ```Go
> 	reqZipCols := colSet.Difference(inputCols).Intersection(zipCols)
> 	if !reqZipCols.Empty() {
> 		zipDistinctCount := float64(1)
> ```

Suggest adding a comment here clarifying that `zipDistinctCount` and `zipNullCount` are totaled across all rows, not just zip rows (i.e. totals after cross-join is applied).
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1673 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31922#-LQ9nzWE6rgPlUMauEjA:-LQ9nzWE6rgPlUMauEjB:b-eore36) ([raw file](https://github.com/cockroachdb/cockroach/blob/d893d3f24c1220b7e5b2d2f37c31b308a87810f4/pkg/sql/opt/memo/statistics_builder.go#L1673)):*
> ```Go
> 					// null count based on the type of generator function and its parameters.
> 					zipDistinctCount *= unknownGeneratorRowCount * unknownGeneratorDistinctCountRatio
> 					zipNullCount += (s.RowCount * unknownNullCountRatio) * (1 - zipNullCount/s.RowCount)
> ```

Is there possibility of division by zero error here, if `s.RowCount` = 0?
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31922#-LQAFode-u2W_SqIgu7Q:-LQAFode-u2W_SqIgu7R:b-tsyhg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d893d3f24c1220b7e5b2d2f37c31b308a87810f4/pkg/sql/opt/norm/rules/decorrelate.opt#L56)):*
> ```
> # ProjectSet only need to be executed once in total, instead of once for each
> # input row.
> [DecorrelateProjectSet, Normalize]
> ```

This should be `TryDecorrelateProjectSet` to be consistent with others. It's called that because there's no guarantee that this rule will result in decorrelation - it's just an attempt to do so.
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 471 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31922#-LQAH1RQ05SdSYnWjNhI:-LQAH1RQ05SdSYnWjNhJ:b-ccudcj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d893d3f24c1220b7e5b2d2f37c31b308a87810f4/pkg/sql/opt/norm/rules/decorrelate.opt#L471)):*
> ```
>         (HasOuterCols $right) &
>         (CanHaveZeroRows $right) & # Let EliminateExistsGroupBy match instead.
>         (GroupBy | DistinctOn | Project | ProjectSet)
> ```

Did you add a test for this new case?
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 543 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31922#-LQAHkpS2VL2KRBm0Hor:-LQAHkpS2VL2KRBm0Hos:bfven34) ([raw file](https://github.com/cockroachdb/cockroach/blob/d893d3f24c1220b7e5b2d2f37c31b308a87810f4/pkg/sql/opt/norm/rules/decorrelate.opt#L543)):*
> ```
>             []
>         )
>         $zip
> ```

Did you fully think through cases where the $zip has functions with different cardinalities that are correlated with the $input? Do you have test cases for that?
___
*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31922#-LQAHMbZDbV6yntKb3kk:-LQAHMbZDbV6yntKb3kl:bqntq37) ([raw file](https://github.com/cockroachdb/cockroach/blob/d893d3f24c1220b7e5b2d2f37c31b308a87810f4/pkg/sql/opt/norm/testdata/rules/decorrelate#L89)):*
> ```
> # --------------------------------------------------
> 
> opt expect=DecorrelateProjectSet
> ```

Can you find a test case where this rule must be applied multiple times in succession?
___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 1562 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31922#-LQADSmp0Bj90JDGinNH:-LQADSmp0Bj90JDGinNI:b5nx6kz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d893d3f24c1220b7e5b2d2f37c31b308a87810f4/pkg/sql/opt/norm/testdata/rules/prune_cols#L1562)):*
> ```
> # --------------------------------------------------
> opt expect=PruneProjectSetCols
> SELECT a, b, generate_series(c, 10) FROM abcde
> ```

You need at least one other case to test case where `zip` depends upon input cols.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31922)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/statistics_builder.go, line 1673 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31922#-LQ9nzWE6rgPlUMauEjA:-LQEi0h31yU2UzYjpV1b:bmi0hwb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d893d3f24c1220b7e5b2d2f37c31b308a87810f4/pkg/sql/opt/memo/statistics_builder.go#L1673)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Is there possibility of division by zero error here, if `s.RowCount` = 0?
</blockquote></details>

It's better to write this as
```
zipNullCount = s.RowCount * unknownNullCountRatio + zipNullCount * (1 - unknownNullCountRatio)
```
(same below)

**Review by rytaft — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31922#-:-LQGF4OGEb4gLIBAFW7_:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/statistics_builder.go, line 1662 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31922#-LQ9n8-x3wCKiak5-8o8:-LQFq8bi3rDC8Zmd-oKJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d893d3f24c1220b7e5b2d2f37c31b308a87810f4/pkg/sql/opt/memo/statistics_builder.go#L1662)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Suggest adding a comment here clarifying that `zipDistinctCount` and `zipNullCount` are totaled across all rows, not just zip rows (i.e. totals after cross-join is applied).
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1673 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31922#-LQ9nzWE6rgPlUMauEjA:-LQFtREU4iMpvQB8E5nq:b-kbkotr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d893d3f24c1220b7e5b2d2f37c31b308a87810f4/pkg/sql/opt/memo/statistics_builder.go#L1673)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It's better to write this as
```
zipNullCount = s.RowCount * unknownNullCountRatio + zipNullCount * (1 - unknownNullCountRatio)
```
(same below)
</blockquote></details>

I simplified this expression but couldn't figure out how to do the same below. I added a check at the top of the function to see `if s.RowCount == 0`.
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31922#-LQAFode-u2W_SqIgu7Q:-LQFtp0A308d6seDnFs-:buknr74) ([raw file](https://github.com/cockroachdb/cockroach/blob/d893d3f24c1220b7e5b2d2f37c31b308a87810f4/pkg/sql/opt/norm/rules/decorrelate.opt#L56)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This should be `TryDecorrelateProjectSet` to be consistent with others. It's called that because there's no guarantee that this rule will result in decorrelation - it's just an attempt to do so.
</blockquote></details>

There is a `TryDecorrelateProjectSet` rule below which is similar to the other `TryDecorrelate` rules. But this `DecorrelateProjectSet` rule is guaranteed to decorrelate the `ProjectSet`. (It's basically the equivalent of `DecorrelateJoin` for the cross join between the input and the `Zip`)
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 471 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31922#-LQAH1RQ05SdSYnWjNhI:-LQFvFahDxB99yblF6TT:be371ew) ([raw file](https://github.com/cockroachdb/cockroach/blob/d893d3f24c1220b7e5b2d2f37c31b308a87810f4/pkg/sql/opt/norm/rules/decorrelate.opt#L471)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Did you add a test for this new case?
</blockquote></details>

I've added a new test case now and also added rule expectations to the existing cases.
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 543 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31922#-LQAHkpS2VL2KRBm0Hor:-LQG45il1aLcpxRJSAS9:b-w26tl3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d893d3f24c1220b7e5b2d2f37c31b308a87810f4/pkg/sql/opt/norm/rules/decorrelate.opt#L543)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Did you fully think through cases where the $zip has functions with different cardinalities that are correlated with the $input? Do you have test cases for that?
</blockquote></details>

I added some test cases. These cases are a bit difficult to test and only happen when a `ROWS FROM` clause is used inside a correlated subquery.
___
*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31922#-LQAHMbZDbV6yntKb3kk:-LQG6TO5-AFTzujGmVfl:b-tmz97v) ([raw file](https://github.com/cockroachdb/cockroach/blob/d893d3f24c1220b7e5b2d2f37c31b308a87810f4/pkg/sql/opt/norm/testdata/rules/decorrelate#L89)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Can you find a test case where this rule must be applied multiple times in succession?
</blockquote></details>

Not sure how that would work... can you explain? I added another case where the Zip is correlated with the outer query.
___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 1562 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31922#-LQADSmp0Bj90JDGinNH:-LQGCL7JAyjeQRcbmMQ7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d893d3f24c1220b7e5b2d2f37c31b308a87810f4/pkg/sql/opt/norm/testdata/rules/prune_cols#L1562)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

You need at least one other case to test case where `zip` depends upon input cols.
</blockquote></details>

Done.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31922)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31922#-LQAFode-u2W_SqIgu7Q:-LQGeWaeArKq6yz-uWpR:bz2ox2k) ([raw file](https://github.com/cockroachdb/cockroach/blob/d893d3f24c1220b7e5b2d2f37c31b308a87810f4/pkg/sql/opt/norm/rules/decorrelate.opt#L56)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

There is a `TryDecorrelateProjectSet` rule below which is similar to the other `TryDecorrelate` rules. But this `DecorrelateProjectSet` rule is guaranteed to decorrelate the `ProjectSet`. (It's basically the equivalent of `DecorrelateJoin` for the cross join between the input and the `Zip`)
</blockquote></details>

Ah, yes, I meant to remove this comment after I saw that, but submitted it accidentally.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31922)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31922#-LQAHMbZDbV6yntKb3kk:-LQOulhE0g_IwD93-TRE:b7kp8s8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d893d3f24c1220b7e5b2d2f37c31b308a87810f4/pkg/sql/opt/norm/testdata/rules/decorrelate#L89)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Not sure how that would work... can you explain? I added another case where the Zip is correlated with the outer query.
</blockquote></details>

i mean where there's a `generate_series` nested in another `generate_series`. I often find that "nesting" test cases highlight interesting issues.

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31922)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31922#-LQAHMbZDbV6yntKb3kk:-LQWerma8ufwjFPzdhMd:b-oapim2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d893d3f24c1220b7e5b2d2f37c31b308a87810f4/pkg/sql/opt/norm/testdata/rules/decorrelate#L89)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

i mean where there's a `generate_series` nested in another `generate_series`. I often find that "nesting" test cases highlight interesting issues.
</blockquote></details>

It's not possible to nest SRFs directly (returns an error `unimplemented: nested set-returning functions`), but I added a test case with a subquery containing another `generate_series`.

**Review by rytaft — COMMENTED** [review]
Gentle ping - do the last set of changes look ok? Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31922#-:-LRDaE-Z6N50wt_dnJLc:bftxu0p)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31922#-:-LREDHp-7cq26vLuTa7c:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by rytaft** [comment]
Thanks!

bors r+

**Pull request merged**
