### PR TITLE
storage: plumb tracing into GetSnapshot

### PR DESCRIPTION
**Pull request by BramGruneir**
Part of #7489

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7925)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[storage/replica_raftstorage.go, line 251 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7925#-KN3jwGUwkz3rc6OX9DZ:-KN3jwGUwkz3rc6OX9D_:2074986737) ([raw file](https://github.com/cockroachdb/cockroach/blob/68bba8b1bf6e2703f8b0e16ddd085318af61a440/storage/replica_raftstorage.go#L251)):*
> ```Go
> // Snapshot implements the raft.Storage interface.
> // Snapshot requires that the replica lock is held.
> func (r *Replica) Snapshot() (raftpb.Snapshot, error) {
> ```

We can't change this method signature, but we could move the bulk of the implementation into a `Replica.snapshotWithContext(context.Context)` method.

---

*[storage/replica_raftstorage.go, line 284 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7925#-KN3iwT5HJ_TBuZ3QRuT:-KN3iwT5HJ_TBuZ3QRuU:-1933028437) ([raw file](https://github.com/cockroachdb/cockroach/blob/68bba8b1bf6e2703f8b0e16ddd085318af61a440/storage/replica_raftstorage.go#L284)):*
> ```Go
> 	if r.store.Stopper().RunAsyncTask(func() {
> 		defer close(ch)
> 		sp := r.store.Tracer().StartSpan(fmt.Sprintf("Snapshot Async %s", r))
> ```

`s/Snapshot Async/snapshot async/g` for consistent capitalization.

---

*[storage/replica_raftstorage.go, line 288 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7925#-KN3izZzZkHZbn3ONbe8:-KN3izZzZkHZbn3ONbe9:-105657082) ([raw file](https://github.com/cockroachdb/cockroach/blob/68bba8b1bf6e2703f8b0e16ddd085318af61a440/storage/replica_raftstorage.go#L288)):*
> ```Go
> 		defer sp.Finish()
> 		snap := r.store.NewSnapshot()
> 		log.Trace(ctx, "got snapshot")
> ```

`s/got snapshot/new engine snapshot/g`

---

*[storage/replica_raftstorage.go, line 340 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7925#-KN3jSV4X8xVFs4WjgRr:-KN3jSV4X8xVFs4WjgRs:-1474204353) ([raw file](https://github.com/cockroachdb/cockroach/blob/68bba8b1bf6e2703f8b0e16ddd085318af61a440/storage/replica_raftstorage.go#L340)):*
> ```Go
> 	for retry := retry.Start(retryOptions); retry.Next(); {
> 		i++
> 		log.Trace(ctx, fmt.Sprintf("GetSnapshot retry loop pass %d", i))
> ```

`retry.CurrentAttempt()`?

My grep'ing shows we almost always use lower case for these messages. Perhaps rephrase to `snapshot retry loop pass %d`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7925)*

**Comment by BramGruneir** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[storage/replica_raftstorage.go, line 251 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7925#-KN3jwGUwkz3rc6OX9DZ:-KN3kodEIF-861XDCu_B:1478780405) ([raw file](https://github.com/cockroachdb/cockroach/blob/68bba8b1bf6e2703f8b0e16ddd085318af61a440/storage/replica_raftstorage.go#L251)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> We can't change this method signature, but we could move the bulk of the implementation into a `Replica.snapshotWithContext(context.Context)` method.
</details>
There's no need to really.  Since the interesting stuff is happening in the async block and we shouldn't pass the context or span into that.  That's why I added the new span there.

---

*[storage/replica_raftstorage.go, line 284 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7925#-KN3iwT5HJ_TBuZ3QRuT:-KN3oTP3H9630CqU4qAg:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/68bba8b1bf6e2703f8b0e16ddd085318af61a440/storage/replica_raftstorage.go#L284)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `s/Snapshot Async/snapshot async/g` for consistent capitalization.
</details>
Done.

---

*[storage/replica_raftstorage.go, line 288 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7925#-KN3izZzZkHZbn3ONbe8:-KN3oW92UvKO0RNZyIQa:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/68bba8b1bf6e2703f8b0e16ddd085318af61a440/storage/replica_raftstorage.go#L288)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `s/got snapshot/new engine snapshot/g`
</details>
Done.

---

*[storage/replica_raftstorage.go, line 340 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7925#-KN3jSV4X8xVFs4WjgRr:-KN3lEORFO7JShyCp_-P:-865147411) ([raw file](https://github.com/cockroachdb/cockroach/blob/68bba8b1bf6e2703f8b0e16ddd085318af61a440/storage/replica_raftstorage.go#L340)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `retry.CurrentAttempt()`?
> 
> My grep'ing shows we almost always use lower case for these messages. Perhaps rephrase to `snapshot retry loop pass %d`.
</details>
oh, awesome, didn't even look to see if that existed.  

And done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7925)*

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/replica_raftstorage.go, line 251 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7925#-KN3jwGUwkz3rc6OX9DZ:-KN41qcRA7u3H0_GQoqI:1480443935) ([raw file](https://github.com/cockroachdb/cockroach/blob/68bba8b1bf6e2703f8b0e16ddd085318af61a440/storage/replica_raftstorage.go#L251)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> There's no need to really.  Since the interesting stuff is happening in the async block and we shouldn't pass the context or span into that.  That's why I added the new span there.
</details>
This method can return `raft.ErrSnapshotTemporarilyUnavailable` for multiple reasons and we're not capturing which one is occurring. In particular, I'd want to know if we're hitting the `exceedsDoubleSplitSizeLocked` condition or the `!AcquireRaftSnapshot()` condition.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7925)*

**Comment by BramGruneir** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/replica_raftstorage.go, line 251 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7925#-KN3jwGUwkz3rc6OX9DZ:-KNZ0UyrAC7QHD3U3y4y:332611906) ([raw file](https://github.com/cockroachdb/cockroach/blob/68bba8b1bf6e2703f8b0e16ddd085318af61a440/storage/replica_raftstorage.go#L251)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> This method can return `raft.ErrSnapshotTemporarilyUnavailable` for multiple reasons and we're not capturing which one is occurring. In particular, I'd want to know if we're hitting the `exceedsDoubleSplitSizeLocked` condition or the `!AcquireRaftSnapshot()` condition.
</details>
done, and merged this with Ben's change #8013 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7925)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 3 of 6 files at r1, 2 of 3 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/replica_raftstorage.go, line 281 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7925#-KNZ1U5BKSnQ4EgxEcyz:-KNZ1U5CXDnYFHB2Fdzm:891790805) ([raw file](https://github.com/cockroachdb/cockroach/blob/52ada6b74fe8b25008c7d020dbecd5ad2afe3472/storage/replica_raftstorage.go#L281)):*
> ```Go
> 		size := r.mu.state.Stats.Total()
> 		r.mu.Unlock()
> 		log.Infof(ctx,
> ```

Should this be a `log.Trace` so it goes into the tracer too? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7925#-:-KNZ1eSSWFs3nQOV4_FK:1417088721)*

**Comment by BramGruneir** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/replica_raftstorage.go, line 281 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7925#-KNZ1U5BKSnQ4EgxEcyz:-KNZ2MV7SOisW0W71Hr1:-785540687) ([raw file](https://github.com/cockroachdb/cockroach/blob/52ada6b74fe8b25008c7d020dbecd5ad2afe3472/storage/replica_raftstorage.go#L281)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Should this be a `log.Trace` so it goes into the tracer too? 
</details>
they do :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7925)*

**Comment by BramGruneir** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/replica_raftstorage.go, line 281 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7925#-KNZ1U5BKSnQ4EgxEcyz:-KNZ2gYX8cE7_hnKjm_O:1147320759) ([raw file](https://github.com/cockroachdb/cockroach/blob/52ada6b74fe8b25008c7d020dbecd5ad2afe3472/storage/replica_raftstorage.go#L281)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> they do :)
</details>
To make that clearer, infof calls log.trace now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7925)*

**Pull request merged**
