### PR TITLE
jobs: add VIEWJOB global privilege, remove role option

### PR DESCRIPTION
**Pull request by jayshrivastava**
This change updates `VIEWJOB` to be a global privilege instead of a role option so that it can be inherited from roles to their members.

Previously, `VIEWJOB` was a role option which could be granted to users. Now, `VIEWJOB` is a global privilege. Granting this privilege to a user or role has the syntax `GRANT SYSTEM VIEWJOB TO user`. Using `VIEWJOB` as a role option is deprecated.

Note that the `VIEWJOB` role option was not included in any release so far. It was queued up to be released in 23.1, but was not. This change is also being queued for 23.1, so there should not be any backwards compatibility issues.

Informs: https://github.com/cockroachdb/cockroach/pull/96382
Epic: None
Release Note: None

### CODE REVIEW

**Review by miretskiy — APPROVED** [review]
LG from cdc side, but do get a 👍 from @rafiss before merging

**Review by rafiss — APPROVED** [review]
awesome, thanks for doing this change. just had a very small nit

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97860#-:-NQ3u16i4jfy5MoRYUxy:bphzzi7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97860#-NQ3tOTK0kuxq5zUxsWT):*
nit: for cases like this, where the commit is changing something that never appeared in any release, it's best to not include a release note. the reason being, someone reading our public docs would likely just end up more confused after reading this, since it is impossible for them to have been affected.

the info here is still great for the commit message though, just no need for a release note.
___
*[`-- commits` line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97860#-NQ3uAwMAr-792rnjDam):*
looks like this should resolve https://cockroachlabs.atlassian.net/browse/CRDB-10082 as well
___
*[`pkg/jobs/jobsauth/authorization.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97860#-NQ3tiH857UxUAsWaO94:-NQ3tiH857UxUAsWaO95:ba4iy44) ([raw file](https://github.com/cockroachdb/cockroach/blob/694a3d549284fd2d66c4fb2184eb2c3c7d033b89/pkg/jobs/jobsauth/authorization.go#L62)):*
> ```Go
> 
> 	// HasPrivilege mirrors sql.AuthorizationAccessor.
> 	HasPrivilege(ctx context.Context, privilegeObject privilege.Object, privilege privilege.Kind, user username.SQLUsername) (bool, error)
> ```

nice, thanks! i've been meaning to add this function to this interface
___
*[`pkg/sql/roleoption/role_option.go` line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97860#-NQ3tpS-3YHWU-wi1hT7:-NQ3tpS-3YHWU-wi1hT8:b-8bbs5d) ([raw file](https://github.com/cockroachdb/cockroach/blob/694a3d549284fd2d66c4fb2184eb2c3c7d033b89/pkg/sql/roleoption/role_option.go#L37)):*
> ```Go
> // KindList of role options.
> //
> // NOTE: Before adding a role option (especially a non-postgres one), consider
> ```

+1 thanks for adding this note too!

**Review by jayshrivastava — COMMENTED** [review]
TYFR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97860#-:-NQ61wTX3iLWAnOQEqFg:b-80slv9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97860#-NQ3tOTK0kuxq5zUxsWT):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: for cases like this, where the commit is changing something that never appeared in any release, it's best to not include a release note. the reason being, someone reading our public docs would likely just end up more confused after reading this, since it is impossible for them to have been affected.

the info here is still great for the commit message though, just no need for a release note.
</blockquote></details>

ack!

**Pull request merged**
