### PR TITLE
opt: deduce not-null constraints for functions with non-nullable args

### PR DESCRIPTION
**Pull request by rytaft**
Release justification: low risk, high benefit changes to existing
functionality, bug fixes and low-risk updates to new functionality

This commit enhances the constraint builder code so that it can deduce
not-null constraints for any variable arguments to functions with non-
nullable args. This is important for improving optimizer support for
spatial functions, since many of these functions have non-nullable args
and are used as filter predicates. Deducing not-null constraints for
the arguments to these functions enables us to calculate more accurate
statistics, and may unlock other optimizations.

Release note (performance improvement): The optimizer can now deduce that
certain variable arguments to functions must be non-null. This improves
cardinality estimation for those variables and unlocks other types of
optimizations. As a result, the optimizer may choose better query plans
when a function is used as a filter predicate.

### CODE REVIEW

**Comment by rytaft** [comment]
Thanks @mgartner for the inspiration!

**Review by mgartner — APPROVED** [review]
:lgtm: 

If you want, you can add tests specifically for the changes to constraint building like I did here: https://github.com/cockroachdb/cockroach/pull/54541/files#diff-494eeda1b9127828e2ff68c0740e1bab. Probably not totally necessary so up to you.

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54558#-:-MHX0rNn9Eg2fBIa1wip:bskb9ln)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/opt/memo/testdata/stats/inverted-geo, line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54558#-MHX0Qfo9BXeBJ3VXy2-:-MHX0Qfo9BXeBJ3VXy20:bgcxuqy) ([raw file](https://github.com/cockroachdb/cockroach/blob/176c08c801a028d43d0d6f3f7044af078ff3f4f9/pkg/sql/opt/memo/testdata/stats/inverted-geo#L326)):*
> ```
> # TODO(mjibson): Teach logical_props_builder that st_intersects is
> # a null-rejecting filter. Since we don't have that logic yet these
> # non-zero null counts are correct.
> ```

Haha I saw this TODO yesterday and had the exact same thought as you!

**Comment by rytaft** [comment]
TFTR! 

> you can add tests specifically for the changes

Done.

**Review by mgartner — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54558)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

**Review by RaduBerinde — APPROVED** [review]
LGTM for master

For 20.2 backport, is this fixing a specific known problem? (if yes, is there an issue written up?)
I don't see any of the existing test plans changing, so I wonder how important it is.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54558#-:-MHXKGfPCncqDlr_SM40:b-wt2elh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

**Comment by rytaft** [comment]
TFTR!

Nope, it's not a known problem, although it's something I've been intending to do for a while...

It does have the potential to change the plan due to stats changes in case of a large number of null values, but I don't currently know of any important use cases. I agree it's not essential to backport.

bors r+

**Pull request merged**
