### PR TITLE
Hook up net/trace with opentracing

### PR DESCRIPTION
**Pull request by tbg**
There is still some upstream movement, so for now
a sensible option is to log directly to net/trace.

Removed disabling of tracers in benchmarks: We'll
run tracing in real world loads, so it's good to
have it on the radar and to make sure the performance
impact is palatable.

Apologies for the unrelated-looking renames.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4385)

### CODE REVIEW

**Comment by petermattis** [comment]
Are traces sampled now? If not, this is going to distort benchmarks and yet not be indicative of eventual performance. 

What is the performance impact of this change? In particular, I'm interested in the `(Insert|Update|Delete|Scan).*Cockroach` benchmarks in the `sql` package. Run with `go test -count 10` and then use `benchstat` to compare against master.

---

Review status: 0 of 31 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[kv/dist_sender.go, line 228 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAaebSMTMUYNm6z1Gyh:-KAaebSNXaeYMfjoJV1B:1260808254) ([raw file](https://github.com/cockroachdb/cockroach/blob/df721bd40f4bc7847ed60b565a16aa60fec78359/kv/dist_sender.go#L228)):*
You also need to pass a context in to the `RangeLookup` method so that the span can be associated with the correct trace, right?

---

*[storage/replica.go, line 786 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAaf6pbVFYvSUXUaEuh:-KAaf6pbVFYvSUXUaEui:543530695) ([raw file](https://github.com/cockroachdb/cockroach/blob/df721bd40f4bc7847ed60b565a16aa60fec78359/storage/replica.go#L786)):*
Perhaps replace the `fmt.Sprintf` with `reflect.TypeOf(args).String()`. I think they are equivalent, though the latter avoids the `fmt` machinery.

---

*[util/tracing/nettrace.go, line 92 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAaflAhYXdkJC9Wehmu:-KAaflAhYXdkJC9Wehmv:-199689173) ([raw file](https://github.com/cockroachdb/cockroach/blob/df721bd40f4bc7847ed60b565a16aa60fec78359/util/tracing/nettrace.go#L92)):*
`s/ntwi/ntwe/g`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-:-KAag3hNS5zMqjcDryMf:-1867755225)*

**Comment by tamird** [comment]
Reviewed 31 of 31 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[kv/local_test_cluster.go, line 50 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAaheMsY5dExBzkpdyD:-KAaheMsY5dExBzkpdyE:2124961268) ([raw file](https://github.com/cockroachdb/cockroach/blob/df721bd40f4bc7847ed60b565a16aa60fec78359/kv/local_test_cluster.go#L50)):*
why do you need this member?

---

*[server/server.go, line 68 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAahi-AIxmS6bFos8MD:-KAahi-AIxmS6bFos8ME:2124961268) ([raw file](https://github.com/cockroachdb/cockroach/blob/df721bd40f4bc7847ed60b565a16aa60fec78359/server/server.go#L68)):*
why do you need this member?

---

*[storage/replica.go, line 785 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAah8U-xYwGxfTLjhhG:-KAah8U-xYwGxfTLjhhH:38851203) ([raw file](https://github.com/cockroachdb/cockroach/blob/df721bd40f4bc7847ed60b565a16aa60fec78359/storage/replica.go#L785)):*
Did you want to pass a context containing this new tracer into the methods below here?

---

*[util/tracing/nettrace.go, line 26 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAahqREhD2TIMkG1sME:-KAahqREhD2TIMkG1sMF:-1507354716) ([raw file](https://github.com/cockroachdb/cockroach/blob/df721bd40f4bc7847ed60b565a16aa60fec78359/util/tracing/nettrace.go#L26)):*
there's some interface being implemented here, right? can you add a static assertion?

---

*[util/tracing/tracer.go, line 47 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAahRcJIgHseoX4nqL1:-KAahRcKVVIQMs-EdMjs:1509317595) ([raw file](https://github.com/cockroachdb/cockroach/blob/df721bd40f4bc7847ed60b565a16aa60fec78359/util/tracing/tracer.go#L47)):*
s/currently //

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385)*

**Comment by JackKrupansky** [comment]
Will tracing be a user-visible feature (like logging) or strictly a developer tool? I presume the former. If so, it would be good to flag for doc and roadmap.

**Comment by nvanbenschoten** [comment]
Reviewed 30 of 31 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[server/server.go, line 68 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAahi-AIxmS6bFos8MD:-KAakbW2b_VUkLuvSb-t:1984039903) ([raw file](https://github.com/cockroachdb/cockroach/blob/df721bd40f4bc7847ed60b565a16aa60fec78359/server/server.go#L68)):*
It can just be a local var right now, but I'm guessing there are plans to use it in `Server` methods?

---

*[server/server_test.go, line 310 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAaky5ZtRBTbGUKj8Ma:-KAaky5ZtRBTbGUKj8Mb:-1893744714) ([raw file](https://github.com/cockroachdb/cockroach/blob/df721bd40f4bc7847ed60b565a16aa60fec78359/server/server_test.go#L310)):*
What are the benefits/reasons for tracing during tests?

---

*[storage/replica.go, line 785 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAah8U-xYwGxfTLjhhG:-KAalI7HP4U9JoQRGGDm:-1708345501) ([raw file](https://github.com/cockroachdb/cockroach/blob/df721bd40f4bc7847ed60b565a16aa60fec78359/storage/replica.go#L785)):*
I think @tschottdorf mentioned he was going to do most of the context plumbing in a later change.

---

*[util/tracing/nettrace.go, line 26 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAahqREhD2TIMkG1sME:-KAals28TBJX_39cExY6:-729548395) ([raw file](https://github.com/cockroachdb/cockroach/blob/df721bd40f4bc7847ed60b565a16aa60fec78359/util/tracing/nettrace.go#L26)):*
Line 100?

---

*[util/tracing/tracer.go, line 64 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAam0xWzGCd1luVq830:-KAam0xWzGCd1luVq831:-573117079) ([raw file](https://github.com/cockroachdb/cockroach/blob/df721bd40f4bc7847ed60b565a16aa60fec78359/util/tracing/tracer.go#L64)):*
I find the name `NoopSpan` (as a type or a function name) to be a lot more explicit about the purpose/use. Maybe consider bringing that name back.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385)*

**Comment by tschottdorf** [comment]
@petermattis See below. That should amount to the vanilla overhead of `net/trace`.

```
name                   old time/op    new time/op    delta
Insert1_Cockroach-8       471µs ± 3%     460µs ± 1%   -2.50%    (p=0.000 n=9+9)
Insert10_Cockroach-8      834µs ± 3%     881µs ± 9%   +5.62%  (p=0.015 n=10+10)
Insert100_Cockroach-8    4.22ms ± 1%    4.46ms ± 9%   +5.72%   (p=0.002 n=9+10)
Update1_Cockroach-8       981µs ± 1%    1096µs ±26%  +11.76%  (p=0.000 n=10+10)
Update10_Cockroach-8     6.25ms ± 7%    6.29ms ± 4%     ~      (p=0.661 n=10+9)
Update100_Cockroach-8    58.2ms ± 8%    57.2ms ± 1%     ~      (p=0.211 n=10+9)
Delete1_Cockroach-8      1.02ms ± 8%    1.04ms ±11%     ~      (p=0.278 n=10+9)
Delete10_Cockroach-8     1.83ms ± 5%    1.91ms ± 5%   +4.02%  (p=0.043 n=10+10)
Delete100_Cockroach-8    9.13ms ± 1%    9.51ms ±10%   +4.10%  (p=0.029 n=10+10)
Scan1_Cockroach-8         252µs ± 1%     253µs ± 2%     ~       (p=0.321 n=8+9)
Scan10_Cockroach-8        301µs ± 2%     304µs ± 1%   +0.80%   (p=0.010 n=9+10)
Scan100_Cockroach-8       744µs ± 3%     735µs ± 2%     ~      (p=0.065 n=9+10)

name                   old alloc/op   new alloc/op   delta
Insert1_Cockroach-8      25.2kB ± 0%    27.2kB ± 0%   +7.81%  (p=0.000 n=10+10)
Insert10_Cockroach-8     80.2kB ± 0%    82.2kB ± 0%   +2.47%   (p=0.000 n=10+8)
Insert100_Cockroach-8     630kB ± 0%     633kB ± 0%   +0.33%  (p=0.000 n=10+10)
Update1_Cockroach-8      43.0kB ± 0%    49.5kB ± 0%  +15.02%   (p=0.000 n=10+7)
Update10_Cockroach-8      277kB ± 0%     317kB ± 0%  +14.40%  (p=0.000 n=10+10)
Update100_Cockroach-8    2.61MB ± 0%    2.98MB ± 0%  +14.39%  (p=0.000 n=10+10)
Delete1_Cockroach-8      40.5kB ± 0%    47.0kB ± 0%  +15.97%    (p=0.000 n=9+9)
Delete10_Cockroach-8      137kB ± 0%     144kB ± 0%   +4.75%  (p=0.000 n=10+10)
Delete100_Cockroach-8    1.02MB ± 0%    1.02MB ± 0%   +0.62%  (p=0.000 n=10+10)
Scan1_Cockroach-8        11.0kB ± 0%    12.8kB ± 0%  +16.41%  (p=0.000 n=10+10)
Scan10_Cockroach-8       17.3kB ± 0%    19.1kB ± 0%  +10.54%   (p=0.000 n=10+9)
Scan100_Cockroach-8      68.9kB ± 0%    70.7kB ± 0%   +2.64%  (p=0.000 n=10+10)

name                   old allocs/op  new allocs/op  delta
Insert1_Cockroach-8         370 ± 0%       386 ± 0%   +4.32%  (p=0.000 n=10+10)
Insert10_Cockroach-8        881 ± 0%       897 ± 0%   +1.82%   (p=0.000 n=10+8)
Insert100_Cockroach-8     5.73k ± 0%     5.74k ± 0%   +0.30%    (p=0.000 n=9+9)
Update1_Cockroach-8         804 ± 0%       852 ± 0%   +5.97%  (p=0.000 n=10+10)
Update10_Cockroach-8      5.41k ± 0%     5.71k ± 0%   +5.56%   (p=0.000 n=10+8)
Update100_Cockroach-8     51.3k ± 0%     54.1k ± 0%   +5.51%  (p=0.000 n=10+10)
Delete1_Cockroach-8         748 ± 0%       796 ± 0%   +6.46%   (p=0.000 n=8+10)
Delete10_Cockroach-8      1.65k ± 0%     1.70k ± 0%   +2.90%    (p=0.000 n=9+9)
Delete100_Cockroach-8     10.0k ± 0%     10.1k ± 0%   +0.48%  (p=0.000 n=10+10)
Scan1_Cockroach-8           221 ± 0%       234 ± 0%   +5.88%    (p=0.000 n=8+9)
Scan10_Cockroach-8          324 ± 0%       337 ± 0%   +4.08%  (p=0.000 n=10+10)
Scan100_Cockroach-8       1.23k ± 0%     1.25k ± 0%   +1.08%   (p=0.000 n=10+8)
```

I can take out the tracing for these benchmarks for now - after all, it's not the actual tracer yet.

**Comment by petermattis** [comment]
Thanks for the benchmarks. I think it best if we leave in a facility for disabling tracing for benchmarks. This could be an env variable or method to call like you previously had.

**Comment by tschottdorf** [comment]
I would like it to be user-visible eventually. I'll flag it for documentation when that is happening - will be a while.

---

Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[kv/dist_sender.go, line 228 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAaebSMTMUYNm6z1Gyh:-KAaqUnzEf9KwHqyWOq4:1715634559) ([raw file](https://github.com/cockroachdb/cockroach/blob/df721bd40f4bc7847ed60b565a16aa60fec78359/kv/dist_sender.go#L228)):*
yes, getting traces into places is mostly a matter of sending contexts around. We lose some around the edges currently.

---

*[kv/local_test_cluster.go, line 50 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAaheMsY5dExBzkpdyD:-KAaqdTBvb9fNScbDuoZ:-1665961036) ([raw file](https://github.com/cockroachdb/cockroach/blob/df721bd40f4bc7847ed60b565a16aa60fec78359/kv/local_test_cluster.go#L50)):*
Extract from a PR which is further ahead (we pass a TracerWithConfig around). Removed.

---

*[server/server.go, line 68 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAahi-AIxmS6bFos8MD:-KAawDA84sEjDKeUPo0c:1137303461) ([raw file](https://github.com/cockroachdb/cockroach/blob/df721bd40f4bc7847ed60b565a16aa60fec78359/server/server.go#L68)):*
Yeah, the plan is to have a `TracerWithOptions` later that allows stuff to be changed (like the sampling probability). Removed.

---

*[server/server_test.go, line 310 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAaky5ZtRBTbGUKj8Ma:-KAauI7PdVLMrAlnsvT2:-238400412) ([raw file](https://github.com/cockroachdb/cockroach/blob/df721bd40f4bc7847ed60b565a16aa60fec78359/server/server_test.go#L310)):*
I want to stop throwing around NoopTracers since different type of tracers mean different type of concrete trace impls, and things get hacky/complicated.

---

*[storage/replica.go, line 785 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAah8U-xYwGxfTLjhhG:-KAauenH2YiZqkeJot4T:453395979) ([raw file](https://github.com/cockroachdb/cockroach/blob/df721bd40f4bc7847ed60b565a16aa60fec78359/storage/replica.go#L785)):*
I did want to throw this into a context, but not here. Moved one level up, to `Send`.

---

*[util/tracing/nettrace.go, line 26 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAahqREhD2TIMkG1sME:-KAavnEePVASsIbNF81n:-2097619327) ([raw file](https://github.com/cockroachdb/cockroach/blob/df721bd40f4bc7847ed60b565a16aa60fec78359/util/tracing/nettrace.go#L26)):*
Moved up.

---

*[util/tracing/tracer.go, line 64 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAam0xWzGCd1luVq830:-KAaw8eLR_gRvrB5PO4l:-1971990380) ([raw file](https://github.com/cockroachdb/cockroach/blob/df721bd40f4bc7847ed60b565a16aa60fec78359/util/tracing/tracer.go#L64)):*
Renamed it back. I actually want to get rid of it, but can't yet. Just a heads up.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-:-KAaqKBd56mbSo2ZncNc:819248875)*

**Comment by tschottdorf** [comment]
@petermattis done. Looks about the same now.

```
name                   old time/op    new time/op    delta
Insert1_Cockroach-8       471µs ± 3%     479µs ± 5%    ~            (p=0.211 n=9+10)
Insert10_Cockroach-8      834µs ± 3%     878µs ± 6%  +5.16%        (p=0.009 n=10+10)
Insert100_Cockroach-8    4.22ms ± 1%    4.32ms ± 1%  +2.26%          (p=0.000 n=9+7)
Update1_Cockroach-8       981µs ± 1%    1003µs ± 6%  +2.28%         (p=0.022 n=10+9)
Update10_Cockroach-8     6.25ms ± 7%    6.13ms ± 6%    ~           (p=0.529 n=10+10)
Update100_Cockroach-8    58.2ms ± 8%    55.4ms ± 2%    ~           (p=0.089 n=10+10)
Delete1_Cockroach-8      1.02ms ± 8%    0.99ms ± 5%  -3.24%        (p=0.029 n=10+10)
Delete10_Cockroach-8     1.83ms ± 5%    1.94ms ±11%  +5.74%         (p=0.028 n=10+9)
Delete100_Cockroach-8    9.13ms ± 1%    9.43ms ± 6%  +3.29%        (p=0.001 n=10+10)
Scan1_Cockroach-8         252µs ± 1%     250µs ± 0%  -0.79%          (p=0.005 n=8+8)
Scan10_Cockroach-8        301µs ± 2%     302µs ± 1%    ~            (p=0.156 n=9+10)
Scan100_Cockroach-8       744µs ± 3%     741µs ± 1%    ~            (p=0.661 n=9+10)

name                   old alloc/op   new alloc/op   delta
Insert1_Cockroach-8      25.2kB ± 0%    25.2kB ± 0%    ~           (p=0.643 n=10+10)
Insert10_Cockroach-8     80.2kB ± 0%    80.2kB ± 0%  +0.02%        (p=0.002 n=10+10)
Insert100_Cockroach-8     630kB ± 0%     630kB ± 0%    ~           (p=0.172 n=10+10)
Update1_Cockroach-8      43.0kB ± 0%    43.0kB ± 0%    ~            (p=0.509 n=10+9)
Update10_Cockroach-8      277kB ± 0%     277kB ± 0%    ~           (p=0.853 n=10+10)
Update100_Cockroach-8    2.61MB ± 0%    2.61MB ± 0%    ~           (p=0.436 n=10+10)
Delete1_Cockroach-8      40.5kB ± 0%    40.5kB ± 0%    ~            (p=0.950 n=9+10)
Delete10_Cockroach-8      137kB ± 0%     137kB ± 0%    ~           (p=0.218 n=10+10)
Delete100_Cockroach-8    1.02MB ± 0%    1.02MB ± 0%    ~           (p=0.325 n=10+10)
Scan1_Cockroach-8        11.0kB ± 0%    11.0kB ± 0%    ~            (p=0.234 n=10+9)
Scan10_Cockroach-8       17.3kB ± 0%    17.3kB ± 0%    ~           (p=0.239 n=10+10)
Scan100_Cockroach-8      68.9kB ± 0%    68.9kB ± 0%    ~           (p=0.085 n=10+10)

name                   old allocs/op  new allocs/op  delta
Insert1_Cockroach-8         370 ± 0%       370 ± 0%    ~     (all samples are equal)
Insert10_Cockroach-8        881 ± 0%       881 ± 0%    ~     (all samples are equal)
Insert100_Cockroach-8     5.73k ± 0%     5.73k ± 0%    ~            (p=0.516 n=9+10)
Update1_Cockroach-8         804 ± 0%       804 ± 0%    ~     (all samples are equal)
Update10_Cockroach-8      5.41k ± 0%     5.41k ± 0%    ~           (p=1.000 n=10+10)
Update100_Cockroach-8     51.3k ± 0%     51.3k ± 0%    ~           (p=0.253 n=10+10)
Delete1_Cockroach-8         748 ± 0%       748 ± 0%    ~            (p=0.294 n=8+10)
Delete10_Cockroach-8      1.65k ± 0%     1.65k ± 0%    ~     (all samples are equal)
Delete100_Cockroach-8     10.0k ± 0%     10.0k ± 0%    ~            (p=0.115 n=10+6)
Scan1_Cockroach-8           221 ± 0%       221 ± 0%    ~            (p=0.294 n=8+10)
Scan10_Cockroach-8          324 ± 0%       323 ± 0%  -0.15%         (p=0.013 n=10+8)
Scan100_Cockroach-8       1.23k ± 0%     1.23k ± 0%    ~            (p=0.248 n=10+9)
```

**Comment by tamird** [comment]
Reviewed 11 of 12 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[util/tracing/nettrace.go, line 32 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAb4xGqoWP0ka47VBcs:-KAb4xGqoWP0ka47VBct:1605161528) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c532a6f2c3480a0479842ff692842b7afd00cf2/util/tracing/nettrace.go#L32)):*
nit: it might be better to implement the interface on the pointer, since an allocation is incurred anyway, and you lose some type safety here if you ever need to type assert.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385)*

**Comment by tschottdorf** [comment]
Review status: 30 of 31 files reviewed at latest revision, 5 unresolved discussions.

---

*[util/tracing/nettrace.go, line 32 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAb4xGqoWP0ka47VBcs:-KAbAM7LRw5BEyJJjSuS:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c532a6f2c3480a0479842ff692842b7afd00cf2/util/tracing/nettrace.go#L32)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385)*

**Comment by bdarnell** [comment]
Review status: 29 of 31 files reviewed at latest revision, 9 unresolved discussions.

---

*[storage/queue.go, line 415 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAbBnKscy_udAReDNb_:-KAbBnKtxOIJN22o53es:-840324685) ([raw file](https://github.com/cockroachdb/cockroach/blob/2959c71d713dcabebb292530a67f5e8416448314/storage/queue.go#L415)):*
Every other call to `NoopSpan` is accompanied by a call to `Finish`.

---

*[storage/replica_test.go, line 484 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAbC-k0k2MOy8jVs6Yx:-KAbC-k0k2MOy8jVs6Yy:182839933) ([raw file](https://github.com/cockroachdb/cockroach/blob/2959c71d713dcabebb292530a67f5e8416448314/storage/replica_test.go#L484)):*
More `NoopSpans` without `Finish` in this file.

---

*[util/tracing/tracer.go, line 63 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAbCRgBkR0bcKT6NTR1:-KAbCRgCmIUOv8K-pjlX:-1250274806) ([raw file](https://github.com/cockroachdb/cockroach/blob/2959c71d713dcabebb292530a67f5e8416448314/util/tracing/tracer.go#L63)):*
Is it required to call `Finish` on a `NoopSpan` or not? Some of the changes in this PR added a call to `Finish` when changing from `NilSpan` to `NoopSpan`, but others did not. It sounds like either all calls to `NoopSpan` should call `Finish` or none should.

---

*[util/tracing/tracer.go, line 70 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAbD1USof4lqsaolnaR:-KAbD1UTTx9zR5sWqzeN:1104769637) ([raw file](https://github.com/cockroachdb/cockroach/blob/2959c71d713dcabebb292530a67f5e8416448314/util/tracing/tracer.go#L70)):*
You've removed some uses of this function from the PR; are there any left? If not, why were only some uses removed?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385)*

**Comment by tschottdorf** [comment]
Review status: 29 of 31 files reviewed at latest revision, 7 unresolved discussions.

---

*[util/tracing/tracer.go, line 63 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAbCRgBkR0bcKT6NTR1:-KAbILw_BXCeFXcl1PTq:1237163562) ([raw file](https://github.com/cockroachdb/cockroach/blob/2959c71d713dcabebb292530a67f5e8416448314/util/tracing/tracer.go#L63)):*
No, it's not required. Removed the remaining two call sites.

---

*[util/tracing/tracer.go, line 70 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAbD1USof4lqsaolnaR:-KAbICqAGp1ygJ4Yr929:-1425192993) ([raw file](https://github.com/cockroachdb/cockroach/blob/2959c71d713dcabebb292530a67f5e8416448314/util/tracing/tracer.go#L70)):*
I sprinkled them pretty liberally in a prior PR and had removed all of them here. Pete wanted to hold off on running them in the actual SQL benchmarks, so I reintroduced this, but called it only in `benchmarkCockroach`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385)*

**Comment by petermattis** [comment]
LGTM

I'm surprised there is any difference in the benchmarks at all with tracing disabled. Looks like the allocation numbers are the same.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[storage/queue.go, line 415 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAbBnKscy_udAReDNb_:-KAbiFJ4VL2VK1t5rAq4:1703371132) ([raw file](https://github.com/cockroachdb/cockroach/blob/2959c71d713dcabebb292530a67f5e8416448314/storage/queue.go#L415)):*
Oops, didn't mean to acknowledge this. Can I unacknowledge in reviewable?

---

*[util/tracing/tracer.go, line 69 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-KAbiVzEnNbreOzZGr-2:-KAbiVzEnNbreOzZGr-3:-2092042583) ([raw file](https://github.com/cockroachdb/cockroach/blob/c71ea4d546293d65ff338c2a1890ad9e16576dd9/util/tracing/tracer.go#L69)):*
`returned callback`? I think you mean `returned closure`, but then some other rewording is necessary.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4385#-:-KAbj0EtNUNA4WCZsp_O:1698739845)*

**Comment by tschottdorf** [comment]
> I'm surprised there is any difference in the benchmarks at all with tracing disabled. Looks like the allocation numbers are the same.

Yeah, but there's a good chance of noise in that signal. Maybe just had more stuff running.

**Pull request merged**
