### PR TITLE
client: Check if a txn record in an error has the correct information

### PR DESCRIPTION
**Pull request by kkaneda**
Return an error if an inner txn returns a roachpb.Error to an outer txn with the wrong txn record.

It seems we have nested transactions in some places (e.g., LeaseStore.Acquire). This check is useful to verify that the behavior is correct in such cases

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4284)

### CODE REVIEW

**Comment by tschottdorf** [comment]
when receiving an error which contains a Txn, the kv client should match the Txn against its own (comparing the ID), and fail if the error contains a different Txn. We don't want to mix the transaction states.

**Comment by kkaneda** [comment]
Thanks, @tschottdorf ! Will take a look. I guess we need to (i) add the check in `TxnCoordSender` or (ii) enable the check in `client.Txn` only when `txn.Proto.Id` is set since the ID is initially set by  `TxnCoordSender`.

**Comment by tschottdorf** [comment]
Hey @kkaneda, this should happen in `client` as you suggested. If a nested txn proto completely replaces the previous one, `TxnCoordSender` has no chance of detecting that.

**Comment by kkaneda** [comment]
Thx! Will take the approach.

**Comment by kkaneda** [comment]
Updated the PR. @tschottdorf , could you take another look?

**Comment by tschottdorf** [comment]
LGTM. Please wait for #4230 to merge and then rebase on top of that (only a minor change).

**Comment by kkaneda** [comment]
Sure! Rebased and confirmed that all tests passed. (Just changed `len(txn.Proto.ID) != 0` to `txn.Proto.ID != nil`).

**Pull request merged**
