### PR TITLE
storage: implement "blind put" optimization for InitPut requests

### LINKED ISSUE #14630: storage: extend optimizePuts to support InitPutRequest
`storage.optimizePuts` enables the blind-put optimization when a batch of `Put` or `ConditionalPut` requests is writing to an empty key range. The blind-put optimization avoids reading keys while writing them which is a significant performance win. We should extend `optimizePuts` to support `InitPut` operations which are used by the schema changer for backfill operations.

Marking for 1.0 as this is very low hanging fruit that will likely provide a significant speed up for schema changes.

Cc @vivekmenezes, @jordanlewis

### PR DESCRIPTION
**Pull request by spencerkimball**
```
BenchmarkMVCCInitPut_RocksDB/10Bytes-4         	  500000	      4140 ns/op	   2.41 MB/s
BenchmarkMVCCInitPut_RocksDB/100Bytes-4        	  500000	      4403 ns/op	  22.71 MB/s
BenchmarkMVCCInitPut_RocksDB/1000Bytes-4       	  300000	      5961 ns/op	 167.75 MB/s
BenchmarkMVCCInitPut_RocksDB/10000Bytes-4      	  100000	     20004 ns/op	 499.88 MB/s
BenchmarkMVCCBlindInitPut_RocksDB/10Bytes-4    	 1000000	      1455 ns/op	   6.87 MB/s
BenchmarkMVCCBlindInitPut_RocksDB/100Bytes-4   	 1000000	      1592 ns/op	  62.80 MB/s
BenchmarkMVCCBlindInitPut_RocksDB/1000Bytes-4  	  500000	      2839 ns/op	 352.21 MB/s
BenchmarkMVCCBlindInitPut_RocksDB/10000Bytes-4 	  100000	     13215 ns/op	 756.72 MB/s
```

Fixes #14630

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica.go, line 124 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14937#-KhizlXLw1HNIDkHpr5v:-KhizlXLw1HNIDkHpr5w:b-2w76zt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d2c090c44e7afb02f3d67e308e57e91c63c641d/pkg/storage/replica.go#L124)):*
> ```Go
> 	roachpb.Put:              true,
> 	roachpb.ConditionalPut:   true,
> 	roachpb.InitPut:          true,
> ```

Whoops. Seems like a serious oversight that this was left out before. Perhaps these should be part of `flags()` instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14937#-:-Khj-4KmmeVlAy3g-CiI:bnfp4nl)*

**Comment by spencerkimball** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica.go, line 124 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14937#-KhizlXLw1HNIDkHpr5v:-KhmlS0U4ezrUXZ1YgkR:b-w9av3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d2c090c44e7afb02f3d67e308e57e91c63c641d/pkg/storage/replica.go#L124)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Whoops. Seems like a serious oversight that this was left out before. Perhaps these should be part of `flags()` instead.
</blockquote></details>

The problem is that timestamp cache is such a storage-specific concept that it doesn't map well to a flag at the `roachpb` layer. All the comments around these values here will be out of place there and confusing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14937)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica.go, line 124 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14937#-KhizlXLw1HNIDkHpr5v:-KhtsC35GujZf8802vw_:b-nltcgx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d2c090c44e7afb02f3d67e308e57e91c63c641d/pkg/storage/replica.go#L124)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary><blockquote>

The problem is that timestamp cache is such a storage-specific concept that it doesn't map well to a flag at the `roachpb` layer. All the comments around these values here will be out of place there and confusing.
</blockquote></details>

Still, I think it would be better to manage this in roachpb because that's where people look when they think "I want to add a command that most closely resembles `Put`". I've thought about moving these into roachpb several times in the past. 

---

*[pkg/storage/replica.go, line 143 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14937#-KhtsZfn_tUa83it2GnG:-KhtsZfn_tUa83it2GnH:b-beswy) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d2c090c44e7afb02f3d67e308e57e91c63c641d/pkg/storage/replica.go#L143)):*
> ```Go
> var updatesTimestampCacheMethods = [...]bool{
> 	roachpb.Get: true,
> 	// ConditionalPut and initPut effectively read and may not write,
> ```

Why does InitPut read?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14937#-:-KhtsyyWWdYDZNIKWObJ:bnfp4nl)*

**Comment by spencerkimball** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica.go, line 124 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14937#-KhizlXLw1HNIDkHpr5v:-Khw49Cp35KXQpkk5DND:b-otudmh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d2c090c44e7afb02f3d67e308e57e91c63c641d/pkg/storage/replica.go#L124)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Still, I think it would be better to manage this in roachpb because that's where people look when they think "I want to add a command that most closely resembles `Put`". I've thought about moving these into roachpb several times in the past. 
</blockquote></details>

OK, I'll move them in a separate PR.

---

*[pkg/storage/replica.go, line 143 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14937#-KhtsZfn_tUa83it2GnG:-Khw4BY8xaUwU5WpELmZ:bfkcp7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d2c090c44e7afb02f3d67e308e57e91c63c641d/pkg/storage/replica.go#L143)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Why does InitPut read?
</blockquote></details>

It's a variant of conditional put. It either writes if the field is empty (requiring a read), or succeeds as a noop if the field is equal to the specified value (already a read), or returns an error otherwise.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14937)*

**Pull request merged**
