### PR TITLE
logictest: don't use hardcoded ports for mixed version test

### PR DESCRIPTION
**Pull request by rafiss**
This should resolve flakes we've seen where the server attempts to bind a port that is already in use.

informs https://github.com/cockroachdb/cockroach/issues/95247
informs https://github.com/cockroachdb/cockroach/issues/98549
informs https://github.com/cockroachdb/cockroach/issues/98612
informs https://github.com/cockroachdb/cockroach/issues/98594

We won't know if it fixes them until after CI runs for a few days.

Release note: None

### CODE REVIEW

**Review by ZhouXing19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99001)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown, @rafiss, and @renatolabs)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99001#-NR4N9n40DUCo056rCmb):*
nit: maybe add something like "rather than starting the multi-node server with hardcoded ports, we now retrieve the automatically-assigned ports from the started nodes" (IIUC)
___
*[`pkg/sql/logictest/logic.go` line 3013 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99001#-NR4O-PoEC9F2fYalxtT:-NR4O-PoEC9F2fYalxtU:b-hy16vm) ([raw file](https://github.com/cockroachdb/cockroach/blob/971b4f5204a27be954de349673de726ccfa9f705/pkg/sql/logictest/logic.go#L3013)):*
> ```Go
> 				t.Fatal(err)
> 			}
> 			if err := t.testserverCluster.UpgradeNode(nodeIdx); err != nil {
> ```

Just curious why we're not doing retry anymore.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99001)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown, @renatolabs, and @ZhouXing19)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99001#-NR4N9n40DUCo056rCmb):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: maybe add something like "rather than starting the multi-node server with hardcoded ports, we now retrieve the automatically-assigned ports from the started nodes" (IIUC)
</blockquote></details>

good idea, done
___
*[`pkg/sql/logictest/logic.go` line 3013 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99001#-NR4O-PoEC9F2fYalxtT:-NR4Uvky49EDA49kxYAu:b-3lwglh) ([raw file](https://github.com/cockroachdb/cockroach/blob/971b4f5204a27be954de349673de726ccfa9f705/pkg/sql/logictest/logic.go#L3013)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Just curious why we're not doing retry anymore. 
</blockquote></details>

the retry was previously added to make it select a new port, since there was a race condition. after this chance, the race condition should be addressed (hopefully), so we don't need it

**Review by ZhouXing19 — APPROVED** [review]
:lgtm_strong: Thanks for making this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99001#-:-NR58U87CzYlzobiq9f5:bopk17a)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @e-mbrown and @renatolabs)

**Comment by rafiss** [comment]
tftr

bors r+

**Pull request merged**
