### PR TITLE
tracing: add log tags as span tags

### PR DESCRIPTION
**Pull request by RaduBerinde**
Whenever we create a span, we get the log tags from the context and
add them as tags to the span. The tags show up and can be queried in
Jaeger. Note that the events inside the span can contain more/other
tags if the context is annotated after the span is started.

We include a facility for remapping log tag names, and use it to make
`n`, `s`, `r` show up as `node`, `store`, `range`.

Unfortunately the zipkin library serializes the tags in map iteration
order, so the ordering will be arbitrary and varying across spans. I
filed an issue proposing that the tags get sorted first.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
image

**Review by nvb — DISMISSED** [review]
:lgtm_strong: thanks for doing this!

> I filed an issue proposing that the tags get sorted first.

Mind linking to the issue?

> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30062#-:-LM852LeEsr4KdaNaduB:b-j1ywmb)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/util/log/logtags/tag.go, line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30062#-LM87Ph08pgQH-MeEx_G:-LM87Ph08pgQH-MeEx_H:bvtysiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b99172d712ff7a2f23020588c35f29aa7cb774/pkg/util/log/logtags/tag.go#L43)):*
> ```Go
> 	if str, ok := t.value.(string); ok {
> 		return str
> 	}
> ```

Might be worth attempting a type-assertion to a `fmt.Stringer` as well. I suspect that that will be faster than `fmt.Sprint` due to less copying.

**Review by RaduBerinde — COMMENTED** [review]
https://github.com/openzipkin-contrib/zipkin-go-opentracing/issues/112

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30062#-:-LM8DTDA9MBkrDGW9G6B:b-m81r4)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/util/log/logtags/tag.go, line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30062#-LM87Ph08pgQH-MeEx_G:-LM8DUBZ1J2lGNvrMKhT:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b99172d712ff7a2f23020588c35f29aa7cb774/pkg/util/log/logtags/tag.go#L43)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Might be worth attempting a type-assertion to a `fmt.Stringer` as well. I suspect that that will be faster than `fmt.Sprint` due to less copying.
</blockquote></details>

Good idea, done.

**Review by andreimatei — COMMENTED** [review]
LGTM sweet

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30062#-:-LM8Lh3P4PraHJcRGP33:b-w4ok6v)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
