### PR TITLE
roachtest: bump KV and YCSB benchmark durations

### PR DESCRIPTION
**Pull request by erikgrinaker**
roachtest benchmark performance often deteriorates over time, e.g. due
to garbage buildup in the LSM and MVCC. We previously ran benchmarks for
10 minutes, but this is often not long enough for this buildup to
significantly affect the benchmark.

To better take this performance deterioration into account, this patch
changes the default duration for KV and YCSB benchmarks from 10 minutes
to 30 minutes. It also adds the environment variables
`ROACHTEST_KV_FLAGS` and `ROACHTEST_YCSB_FLAGS` to pass additional flags
to the workloads in order to override the duration (e.g.
`ROACHTEST_KV_FLAGS="--duration 5m"`).

Touches #72499.

Release note: None

A follow-up PR will annotate this change on roachperf graphs.

### CODE REVIEW

**Comment by tbg** [comment]
Looks good, would like @stevendanna's input as well since this is a pretty big change in what the graphs will show.
I think it's fine, but we definitely want to add an annotation to roachperf.

**Comment by erikgrinaker** [comment]
@stevendanna Wdyt?

**Comment by stevendanna** [comment]
While this will make it harder to do historical comparisons using the graphs alone, I don't think we should let that get in the way of making changes we think are important to getting the signal we want from these tests.

I am OK with this change in principle, but we should perhaps give dev-env a heads-up and keep an eye on what this does to the overall nightly test-time and cost.  Since we have tests that take 6-8 hours, my guess is that we'll still finish the kv tests before those tests finish. I suppose we could trigger one of the nightly pipeline's from this branch to be sure.

**Comment by erikgrinaker** [comment]
Sure, I'll trigger a run once today's nightlies finish (to prevent interfering with them by e.g. allocating too many cloud resources).

**Comment by erikgrinaker** [comment]
[Manual run](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_WorkloadNightly/3865938?buildTab=dependencies&mode=timeline&range=1638922732000-1638966627000) took 12h10m for the final roachtest step, [last nightly](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_WorkloadNightly/3860355?buildTab=dependencies&mode=timeline&range=1638861025000-1638904153000) took 11h58m. Don't know how much additional VM-time it costs, but can find out if it's really necessary.

**Review by srosenberg — APPROVED** [review]
Seems negligible; don't think we need to worry about the additional time & cost in this case.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72646#-:-MqRYxu-D_2EBE2N98pd:b-qmggl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

**Review by stevendanna — APPROVED** [review]

**Comment by stevendanna** [comment]
Thanks for doing that run.  LGTM!

**Pull request merged**
