### PR TITLE
sql: improve SHOW CREATE VIEW output

### PR DESCRIPTION
**Pull request by postamar**
Previously, SHOW CREATE VIEW would return the view query on a single
line, making complex view queries hard to read by humans. Furthermore,
column names would also be on a single line, making views with many
columns hard to read as well. This commit fixes both of these
shortcomings.

Release note (sql change): SHOW CREATE VIEW returns prettier SQL.

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73642)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis and @postamar)

___
*[pkg/sql/show_create_clauses.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73642#-MqUpuLe4zr9z8IKbHoi:-MqUpuLe4zr9z8IKbHoj:b-5ybxgz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0501e7ef4444a2ef7f4d3fb25174a0d9a393ffbc/pkg/sql/show_create_clauses.go#L119)):*
> ```Go
> 	f.WriteString(") AS ")
> 
> 	cfg := tree.DefaultPrettyCfg()
> ```

`DefaultPrettyCfg` uses a line width of 60 which is overly narrow in my opinion. I'm not sure what the right default should be here, but it is definitely greater than 60. Perhaps 100 to match the CRDB line length recommendations.

**Comment by postamar** [comment]
> Perhaps 100 to match the CRDB line length recommendations.

Fine by me. I wondered about this, in the end I stuck with the default, probably due to having accumulated too much scar tissue from grumpy unix greybeards who get mad when they saw line wraps in their 80-character-wide terminals.

**Review by postamar — COMMENTED** [review]
This is now ready for review.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73642#-:-MqVL93MCBEWo1tepm65:bp659xb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @petermattis)

___
*[pkg/sql/show_create_clauses.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73642#-MqUpuLe4zr9z8IKbHoi:-MqVL6LfCMOa6bzwqGEM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0501e7ef4444a2ef7f4d3fb25174a0d9a393ffbc/pkg/sql/show_create_clauses.go#L119)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`DefaultPrettyCfg` uses a line width of 60 which is overly narrow in my opinion. I'm not sure what the right default should be here, but it is definitely greater than 60. Perhaps 100 to match the CRDB line length recommendations.
</blockquote></details>

Done.

**Review by fqazi — APPROVED** [review]
> Reviewed 6 of 12 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73642)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @petermattis)

**Review by fqazi — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73642#-:-Mq_yQpoEplni1mxybqI:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm and @petermattis)

**Comment by postamar** [comment]
Thanks for the review!

bors r+

**Pull request merged**
