### PR TITLE
sql: use statement tag for prepare error message

### PR DESCRIPTION
**Pull request by madelynnblue**
[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4094)

### CODE REVIEW

**Comment by tamird** [comment]
Seems brittle, but OK.

**Comment by dt** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/plan.go, line 171 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4094#-K9Yy4259Mb_suQp4s3F:-K9Yy4259Mb_suQp4s3G:264255836) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5832d4db03cc5f903303bfb4c77bce38713a373/sql/plan.go#L171)):*
nuke the TODO too?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4094)*

**Comment by mjibson** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/plan.go, line 171 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4094#-K9Yy4259Mb_suQp4s3F:-K9YyrKM8Ujo5H4DwufV:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5832d4db03cc5f903303bfb4c77bce38713a373/sql/plan.go#L171)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4094)*

**Comment by RaduBerinde** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4094)*

**Comment by dt** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4094)*

**Pull request merged**
