### PR TITLE
sql: add MERGING state to TestOperationsWithIndexMutation

### PR DESCRIPTION
**Pull request by stevendanna**
I failed to git-add this test to the commit that introduced the
merging state.

The diff is large because I added a subtest for each state/upsert
combination, which required indenting all of the code.

The actual change to this test is simply to add the MERGING state to
the list of states that we are iterating over. The rest of the test is
valid because DELETE_AND_WRITE_ONLY is the assumed default path in
most conditionals and the MERGING state behaves just like
DELETE_AND_WRITE_ONLY for the purposes of this test.

Release note: None

### CODE REVIEW

**Comment by stevendanna** [comment]
I recommend the hide-whitespace view on this one: https://github.com/cockroachdb/cockroach/pull/75950/files?diff=unified&w=1

**Review by ajwerner — APPROVED** [review]
LGTM

**Comment by stevendanna** [comment]
CI failure looks unrelated https://github.com/cockroachdb/cockroach/issues/75960

**Comment by stevendanna** [comment]
bors r=ajwerner

**Pull request merged**
