### PR TITLE
roachtest: no splits happen under LBS in certain conditions

### PR DESCRIPTION
**Pull request by ridwanmsharif**
Adds roachtests that reproduce reliably some of the experiments
conducted in #31819. Specifically, it ensures that under a spanning
workload or a sequential write workload, this feature doesn't
hamper performance (as splits would).

Release note: None

### CODE REVIEW

**Review by nvb — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32112)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/split.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32112#-LQITiMH2VG5y63ReU0w:-LQITiMH2VG5y63ReU0x:bi6xsdd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f64f81360449f795d2a167b893c7b1bd88c5a96/pkg/cmd/roachtest/split.go#L40)):*
> ```Go
> 		MinVersion: st.VersionByKey(st.VersionLoadSplits).String(),
> 		Nodes:      nodes(numNodes),
> 		Stable:     true, // DO NOT COPY to new tests
> ```

I missed this in the other review, but none of these should be stable. Tests become stable after passing repeatedly for a few weeks.
___
*[pkg/cmd/roachtest/split.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32112#-LQITrr6DNDZvNu0poeM:-LQITrr6DNDZvNu0poeN:b65dsuz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f64f81360449f795d2a167b893c7b1bd88c5a96/pkg/cmd/roachtest/split.go#L47)):*
> ```
> st.VersionByKey(st.VersionLoadSplits).String()
> ```

Pull into a variable.
___
*[pkg/cmd/roachtest/split.go, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32112#-LQITyfk4Ik6V9Ue_K8I:-LQITyfk4Ik6V9Ue_K8J:bhjm1g7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f64f81360449f795d2a167b893c7b1bd88c5a96/pkg/cmd/roachtest/split.go#L65)):*
> ```Go
> }
> 
> // runUniformLoadSplits tests behavior of load based splitting under
> ```

There's a ton of duplication in all three of these functiosn. Can the few parts that differ simply be parameterized? If that's too much for one function, maybe consider a `type loadSplitTest struct{ ... }` abstraction.

**Review by ridwanmsharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32112)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/split.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32112#-LQITiMH2VG5y63ReU0w:-LRDfDKJ0uTRtSj0uYNC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f64f81360449f795d2a167b893c7b1bd88c5a96/pkg/cmd/roachtest/split.go#L40)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I missed this in the other review, but none of these should be stable. Tests become stable after passing repeatedly for a few weeks.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/split.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32112#-LQITrr6DNDZvNu0poeM:-LRDfF742Ay93nO42-bx:b-njs200) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f64f81360449f795d2a167b893c7b1bd88c5a96/pkg/cmd/roachtest/split.go#L47)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> st.VersionByKey(st.VersionLoadSplits).String()
> ```

Pull into a variable.
</blockquote></details>

This isn't right, using "2.2.0" instead.
___
*[pkg/cmd/roachtest/split.go, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32112#-LQITyfk4Ik6V9Ue_K8I:-LRDfOb1Bd_fEZH0oOT-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f64f81360449f795d2a167b893c7b1bd88c5a96/pkg/cmd/roachtest/split.go#L65)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

There's a ton of duplication in all three of these functiosn. Can the few parts that differ simply be parameterized? If that's too much for one function, maybe consider a `type loadSplitTest struct{ ... }` abstraction. 
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm_strong: this is really good.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32112#-:-LRDkLtL0M_a_9gpvJir:b9ohocj)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/split.go, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32112#-LRDkUniCsfcp7MlqnyI:-LRDkUniCsfcp7MlqnyJ:b-od589o) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0f7f721a0bed5ecec7c55e6948abe50faac2bd4/pkg/cmd/roachtest/split.go#L56)):*
> ```Go
> 			// change this. Used 20 using pure intuition for a suitable split
> 			// count from LBS with this kind of workload.
> 			expSplits := 20
> ```

It would be nice if this was a function of `kv.range_split.load_qps_threshold`, but I don't think that's easy to derive.

**Review by ridwanmsharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32112)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/split.go, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32112#-LRDkUniCsfcp7MlqnyI:-LRE0zto1Gu0_Abbijhw:beuwc4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0f7f721a0bed5ecec7c55e6948abe50faac2bd4/pkg/cmd/roachtest/split.go#L56)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It would be nice if this was a function of `kv.range_split.load_qps_threshold`, but I don't think that's easy to derive.
</blockquote></details>

Shouldn't really matter, the wait duration is set according to what ever we pick for the expected split count.

**Pull request merged**
