### PR TITLE
kv: add a transaction attribute for rangefeed filtering

### LINKED ISSUE #112991: kv: add a transaction attribute for cdc filtering
**Is your feature request related to a problem? Please describe.**
This is part of enabling [write-time CDC filtering](https://docs.google.com/document/d/1bYCLrgOxb2yjTc5aWpZXl8dSB2w60F57GMUcehDRyzY/edit).  In particular, this work completes part 3 of the [Solution Breakdown](https://docs.google.com/document/d/1bYCLrgOxb2yjTc5aWpZXl8dSB2w60F57GMUcehDRyzY/edit#heading=h.ezlbc4xeey2n).

**Describe the solution you'd like**
Users will be able to set a session variable indicating that write-time cdc filtering is enabled for this session. Each transaction in the session will have a boolean attribute set to true to plumb that information to the storage layer. In addition to the attribute we will also need KV API functions to set and unset it. The attribute will be written from the SQL layer, and will be read in `mvccPutInternal`, where it will be persisted in the `MVCCValueHeader`.

### PR DESCRIPTION
**Pull request by miraradeva**
A new boolean transaction attribute allows users to choose which writes are exported to rangefeeds and changefeeds on a per-transaction basis. When the attribute is true, all of the transaction's writes will be filtered out by rangefeeds, and will not be available in changefeeds.

Fixes: #112991

Release note: None

Epic: CRDB-13169

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113522)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @miraradeva, and @nvanbenschoten)

___
*[`pkg/roachpb/data.go` line 953 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113522#-NiBVK5_7AjQO_RtTgN8:-NiBVK5_7AjQO_RtTgN9:b-m9q0y1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e93eaba29d157e13ac96ef5199bf6620597bd8b/pkg/roachpb/data.go#L953)):*
> ```Go
> // baseKey can be nil, in which case it will be set when sending the first
> // write.
> func MakeTransaction(
> ```

The new argument should be documented here.
___
*[`pkg/roachpb/data.proto` line 521 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113522#-NiBVnK_C9uAOAtEC0lU:-NiBVnK_C9uAOAtEC0lV:b-6typoj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e93eaba29d157e13ac96ef5199bf6620597bd8b/pkg/roachpb/data.proto#L521)):*
> ```proto
>   // rangefeeds, and will not be available in changefeeds. This allows users to
>   // choose which writes are exported on a per-transaction basis.
>   bool disable_rangefeed = 20;
> ```

Would "hide_from_rangefeeds" be more accurate?

**Comment by RaduBerinde** [comment]
*[`pkg/roachpb/data.proto` line 521 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113522#-NiBVnK_C9uAOAtEC0lU:-NiBv7iXARb5eyKSLsOo:b-qnwfes) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e93eaba29d157e13ac96ef5199bf6620597bd8b/pkg/roachpb/data.proto#L521)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Would "hide_from_rangefeeds" be more accurate?
</blockquote></details>

Or "omit_in_rangefeeds"

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113522)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @miraradeva, and @nvanbenschoten)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_test.go` line 618 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113522#-NiF7W1o2LqvKt_gf_XX:-NiF7W1o2LqvKt_gf_XY:byijsyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e93eaba29d157e13ac96ef5199bf6620597bd8b/pkg/kv/kvclient/kvcoord/dist_sender_test.go#L618)):*
> ```Go
> 	ds := NewDistSender(cfg)
> 
> 	txn := roachpb.MakeTransaction("test", nil, isolation.Serializable, roachpb.NormalUserPriority, clock.Now(), clock.MaxOffset().Nanoseconds(), int32(ds.nodeIDGetter()), 0, false)
> ```

nit: consider undoing the loss of code comments that happened here and elsewhere because of goland refactoring

**Review by nvb — COMMENTED** [review]
> Reviewed 52 of 52 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113522)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @miraradeva, @RaduBerinde, and @sumeerbhola)

___
*[`pkg/roachpb/data.proto` line 519 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113522#-NiFciqT2dUPWAp7GRmy:-NiFciqT2dUPWAp7GRmz:b-t0ssqt) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e93eaba29d157e13ac96ef5199bf6620597bd8b/pkg/roachpb/data.proto#L519)):*
> ```proto
> 
>   // When set to true, all of the transaction's writes will be filtered out by
>   // rangefeeds, and will not be available in changefeeds. This allows users to
> ```

What did we decide about transactions that write to internal system tables (e.g. `system.span_configurations`, `system.settings`)?  Should they be prevented from setting this option? Should the option be ignored by internal rangefeeds?
___
*[`pkg/roachpb/data.proto` line 521 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113522#-NiBVnK_C9uAOAtEC0lU:-NiFcLV78bg7ree8Q_0z:b-pl9lca) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e93eaba29d157e13ac96ef5199bf6620597bd8b/pkg/roachpb/data.proto#L521)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Or "omit_in_rangefeeds"
</blockquote></details>

I agree that either of those would be better.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_test.go` line 618 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113522#-NiF7W1o2LqvKt_gf_XX:-NiFdT4u08NGmR892i0z:b-7b97vz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e93eaba29d157e13ac96ef5199bf6620597bd8b/pkg/kv/kvclient/kvcoord/dist_sender_test.go#L618)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: consider undoing the loss of code comments that happened here and elsewhere because of goland refactoring
</blockquote></details>

+1

Alternatively, we could cut down the size of this diff by not adding the flag to the transaction constructor and letting the one or two places that set the flag do so separately.

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113522)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @nvanbenschoten, @RaduBerinde, and @sumeerbhola)

___
*[`pkg/roachpb/data.proto` line 519 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113522#-NiFciqT2dUPWAp7GRmy:-NiFh_f96rvedRBx7dvU:bvfwm1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e93eaba29d157e13ac96ef5199bf6620597bd8b/pkg/roachpb/data.proto#L519)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What did we decide about transactions that write to internal system tables (e.g. `system.span_configurations`, `system.settings`)?  Should they be prevented from setting this option? Should the option be ignored by internal rangefeeds?
</blockquote></details>

My understanding was that we'll do the former (i.e. not be able to set this option for internal tables). But it's probably safer to do both?
___
*[`pkg/roachpb/data.proto` line 521 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113522#-NiBVnK_C9uAOAtEC0lU:-NiFhXcM7ngh-szTVsiC:b-1irl6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e93eaba29d157e13ac96ef5199bf6620597bd8b/pkg/roachpb/data.proto#L521)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I agree that either of those would be better.
</blockquote></details>

Agreed, those are better names.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_test.go` line 618 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113522#-NiF7W1o2LqvKt_gf_XX:-NiFhtCS-v89GJ6psn0H:bb8cpqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e93eaba29d157e13ac96ef5199bf6620597bd8b/pkg/kv/kvclient/kvcoord/dist_sender_test.go#L618)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

+1

Alternatively, we could cut down the size of this diff by not adding the flag to the transaction constructor and letting the one or two places that set the flag do so separately.
</blockquote></details>

I put the comments back in. Goland didn't keep them when refactoring.

**Review by nvb — COMMENTED** [review]
> Reviewed 3 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113522)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @miraradeva, @RaduBerinde, and @sumeerbhola)

___
*[`pkg/roachpb/data.proto` line 519 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113522#-NiFciqT2dUPWAp7GRmy:-NitwlFa6zlByN7HObmt:bw2hz15) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e93eaba29d157e13ac96ef5199bf6620597bd8b/pkg/roachpb/data.proto#L519)):*
> not be able to set this option for internal tables

:thumbsup: do we have an issue tracking this, or somewhere that we are discussing how we plan to enforce this constraint?
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_test.go` line 618 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113522#-NiF7W1o2LqvKt_gf_XX:-Nitwww0-WZ-XKZ9GIXv:b1wj5eg) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e93eaba29d157e13ac96ef5199bf6620597bd8b/pkg/kv/kvclient/kvcoord/dist_sender_test.go#L618)):*
> we could cut down the size of this diff by not adding the flag to the transaction constructor and letting the one or two places that set the flag do so separately.

Part of the reason for this suggestion is because if not, we'll want to go and add inline `/* omitInRangefeeds */` comments for each of these params if we're keeping this boolean argument. This is to stay in accordance with the Go style guide (https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/181371303/Go+Golang+coding+guidelines#Avoid-Naked-Parameters) that we follow in the project.

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113522)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @nvanbenschoten, @RaduBerinde, and @sumeerbhola)

___
*[`pkg/roachpb/data.proto` line 519 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113522#-NiFciqT2dUPWAp7GRmy:-Nj-5HThAVzmUkbDky0l:b-332544) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e93eaba29d157e13ac96ef5199bf6620597bd8b/pkg/roachpb/data.proto#L519)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> not be able to set this option for internal tables

:thumbsup: do we have an issue tracking this, or somewhere that we are discussing how we plan to enforce this constraint?
</blockquote></details>

Added a comment in #114083. And also created #114313.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_test.go` line 618 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113522#-NiF7W1o2LqvKt_gf_XX:-Nj-5DgR6BItNRbOaFgZ:b-zc05rp) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e93eaba29d157e13ac96ef5199bf6620597bd8b/pkg/kv/kvclient/kvcoord/dist_sender_test.go#L618)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> we could cut down the size of this diff by not adding the flag to the transaction constructor and letting the one or two places that set the flag do so separately.

Part of the reason for this suggestion is because if not, we'll want to go and add inline `/* omitInRangefeeds */` comments for each of these params if we're keeping this boolean argument. This is to stay in accordance with the Go style guide (https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/181371303/Go+Golang+coding+guidelines#Avoid-Naked-Parameters) that we follow in the project.
</blockquote></details>

Ok, I'm convinced.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 50 of 51 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113522#-:-Nj59YMu6JE6z9QeR8jl:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal, @RaduBerinde, and @sumeerbhola)

**Comment by miraradeva** [comment]
bors r=nvanbenschoten

**Pull request merged**
