### PR TITLE
storage: quieten the GC queue.

### LINKED ISSUE #10325: storage: the GC queue processing is very chatty in logs
I had let a cluster to run idle and I just noticed that when the GC kicked in my logs were spammed with the "GC completed" messages *multiple times per second*. I didn't use any verbosity flags.

Indeed in `storage/gc_queue.go:325`: 
```
        queueCtx := gcq.AnnotateCtx(context.TODO())
        log.Infof(queueCtx, "completed with stats %+v", info)
        log.Eventf(ctx, "completed with stats %+v", info)
```

no condition on log.V for log.Infof(). Is this intentional?

### PR DESCRIPTION
**Pull request by knz**
Fixes #10325.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10332)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Looks like a `V(1)` to me but then again I don't think `V` levels make any sense anyway, so LGTM.

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/gc_queue.go, line 328 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10332#-KVR1yEhdCumf4yTxNqf:-KVR1yEhdCumf4yTxNqg:b-5yla9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba44bc8947818d8767d99aefef420ba79c6892d0/pkg/storage/gc_queue.go#L328)):*
> ```Go
> 		log.Infof(queueCtx, "completed with stats %+v", info)
> 	}
> 	log.Eventf(ctx, "completed with stats %+v", info)
> ```

this also wants the annotated context

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10332)*

**Comment by knz** [comment]
I have set to V(1).

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/gc_queue.go, line 328 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10332#-KVR1yEhdCumf4yTxNqf:-KVR2PT8VZGIQTDodW81:b-orbekh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba44bc8947818d8767d99aefef420ba79c6892d0/pkg/storage/gc_queue.go#L328)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this also wants the annotated context
</details>
Can you explain more?
The caller of this method (`processReplica()`) already annotates `ctx`. Do we need to annotate twice?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10332#-:-KVR2hf4FjRGKihO__8f:biv7snt)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/gc_queue.go, line 328 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10332#-KVR1yEhdCumf4yTxNqf:-KVR3Favk-mLDFtxdfhL:b-br901i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba44bc8947818d8767d99aefef420ba79c6892d0/pkg/storage/gc_queue.go#L328)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Can you explain more?
> The caller of this method (`processReplica()`) already annotates `ctx`. Do we need to annotate twice?
</details>
Well either we do or we don't - it makes no sense to annotate the context passed to `Infof` but not the one passed to `Eventf`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10332)*

**Comment by knz** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/gc_queue.go, line 328 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10332#-KVR1yEhdCumf4yTxNqf:-KVR47CuDmrlQ7CBytDJ:b-t93o5c) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba44bc8947818d8767d99aefef420ba79c6892d0/pkg/storage/gc_queue.go#L328)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Well either we do or we don't - it makes no sense to annotate the context passed to `Infof` but not the one passed to `Eventf`.
</details>
Ok then I decided to use the same context in both places. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10332)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/gc_queue.go, line 328 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10332#-KVR1yEhdCumf4yTxNqf:-KVR4rgoaZN-3AJIiknz:bn44a6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba44bc8947818d8767d99aefef420ba79c6892d0/pkg/storage/gc_queue.go#L328)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Ok then I decided to use the same context in both places. PTAL.
</details>
Ah, yes, this annotation is just unnecessary.

Btw, this is just `log.VEventf(ctx, 1, ....)` now, I think

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10332)*

**Comment by knz** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[pkg/storage/gc_queue.go, line 328 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10332#-KVR1yEhdCumf4yTxNqf:-KVR6I2_REl5u2t-otrZ:b-hfm48w) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba44bc8947818d8767d99aefef420ba79c6892d0/pkg/storage/gc_queue.go#L328)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Ah, yes, this annotation is just unnecessary.
> 
> Btw, this is just `log.VEventf(ctx, 1, ....)` now, I think
</details>
Wow, nice, that simplifies!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10332)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10332#-:-KVR6ZZWT8hLmxIPX_vj:bnfp4nl)*

**Pull request merged**
