### PR TITLE
changefeedccl: set sarama's flush frequency to 0 by default.

### PR DESCRIPTION
**Pull request by stevendanna**
The default of 1 hours was added to avoid a warning that sarama
produces when you set flush.Messages but not flush.Frequency. When
flush.Messages is 1, we believe this warning is incorrect since Sarama
will always try to flush its buffer when it has a message and
flush.Messages = 1.

Unfortunately, sarama creates a new timer after every flush. Under
constant load, we will flush very frequently. The timers it creates
are kept alive by the Go runtime until they expire. This means we can
accumulate 1 hours worth of timers.

During a 1 hour run of the cdc/ledger roachtest, these times grew to
two hundred MBs of inuse space. By setting the timer to 0, we avoid
this accumulation.

Because of this changes, users will occasionally see the following
error message:

    [kafka-producer] 202 ‹Producer.Flush: Bytes or Messages are set,
    but Frequency is not; messages may not get flushed.›

This warning can be ignored for our default configuration.

Release note: None

### CODE REVIEW

**Review by miretskiy — APPROVED** [review]
I would update the PR comment to include the actual text of the warning, and I would just indicate that it's innocuous. 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66040#-:-MbIzLcTCuNRs4gFJpdS:bugrtf8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

**Comment by stevendanna** [comment]
@miretskiy Done.  However, when looking at this, I noted that we get the messages a bunch of times at startup:

```
[kafka-producer] 200  ‹Initializing new client›                                                                                                                                                                             config.go:520 ⋮ [kafka-producer] 201  ‹Producer.Flush: Bytes or Messages are set, but Frequency is not; messages may not get flushed.›
[kafka-producer] 202  ‹Producer.Flush: Bytes or Messages are set, but Frequency is not; messages may not get flushed.›
[kafka-producer] 203  client/metadata fetching metadata for all topics from broker ‹127.0.0.1:58162›
[kafka-producer] 204  Connected to broker at ‹127.0.0.1:58162› (unregistered)                                                                                                                                               client.go:602 ⋮ [kafka-producer] 205  client/brokers registered new broker #0 at ‹127.0.0.1:58162›
[kafka-producer] 206  ‹Successfully initialized new client›
[kafka-producer] 211  ‹Initializing new client›
[kafka-producer] 212  ‹Producer.Flush: Bytes or Messages are set, but Frequency is not; messages may not get flushed.›
[kafka-producer] 213  ‹Producer.Flush: Bytes or Messages are set, but Frequency is not; messages may not get flushed.›
[kafka-producer] 214  client/metadata fetching metadata for all topics from broker ‹127.0.0.1:58162›
[kafka-producer] 215  Connected to broker at ‹127.0.0.1:58162› (unregistered)
[kafka-producer] 216  client/brokers registered new broker #0 at ‹127.0.0.1:58162›
[kafka-producer] 217  ‹Successfully initialized new client›
[kafka-producer] 218  ‹Initializing new client›
[kafka-producer] 219  ‹Producer.Flush: Bytes or Messages are set, but Frequency is not; messages may not get flushed.›
[kafka-producer] 220  ‹Producer.Flush: Bytes or Messages are set, but Frequency is not; messages may not get flushed.›
[kafka-producer] 221  client/metadata fetching metadata for all topics from broker ‹127.0.0.1:58162›
[kafka-producer] 222  Connected to broker at ‹127.0.0.1:58162› (unregistered)
[kafka-producer] 223  client/brokers registered new broker #0 at ‹127.0.0.1:58162›
[kafka-producer] 224  ‹Successfully initialized new client›
```

which I feel like is going to cause more confusion than it is worth. So, in a follow-up commit I moved us to the default all-zero configuration and then included some validation to avoid the most problematic configuration combinations.

I'm thinking we can perhaps backport the first commit to 20.2 & 21.1 but go forward with the stricter validation for the next release.

**Comment by miretskiy** [comment]
We should backport this.

**Comment by stevendanna** [comment]
bors r=miretskiy

**Pull request merged**
