### PR TITLE
sql: add types, datum and encoding for TimeTZ

### PR DESCRIPTION
**Pull request by otan**
Refs: #26097

This PR adds the types to the type system to support TimeTZ, adding the
tree.Datum class to ensure it can be parsed and then also adds the
encoding for TimeTZ to be put in the database. This is the minimum
amount of work needed before any set of tests can pass - trying to keep
the PRs small but in the end did not succeed.

Changes per package (and recommended review order) are as follows:

**sql/types: added the new TimeTZ type and type family.**

**pkg/util/timetz: introduce new TimeTZ type**

Added a custom wrapper around timeofday and offset seconds, which form
follows postgres' implementation of `TimeTzADT`. Note that `OffsetSecs`
being negative / not what you expect is fully handled by all utility
functions from this interface.

**pkg/sql/sem/tree: add Datum for DTimeTZ**

A wrapper around TimeTZ for the tree expressions.
Also removed some magic constants I found whilst form following other
things.

**pkg/util/timeutil/pgdate: remove usage of testutil.IsError**

This causes a circular dependency on the new timetz type, and this was a
very straightforward way of going around it.

**pkg/util/encoding: added encoding for DTimeTZ**
Form following postgres, we store the timeofday and offset into the
database as 12 bytes - an 8 and 4 byte varint. To have sort order right,
and to form follow the btree encoding for TimeTZ, we use UTC time when
storing it for `(En|De)codeTimeTZ[As|Des]cending`.

**pkg/sql/pgwire: added pgwire for DTimeTZ**

**pkg/sql/sqlbase: added necessary changes to encode TimeTZ data**

**ccl/changefeedccl: added encoding for ccl**
Note we must use the string type here as we cannot encode two ints
nicely with avro, nor is one int enough to not lose data.

**sql/parser: added parsing support for TimeTZ**
I wanted to omit this in this PR but some of the automated tests
iterating over every time needs this. Note there are more bits to
implement which I will leave for a later PR.

**pkg/cli: add ability to dump TimeTZ**

**sql/logictest/testdata/logic_test: added basic tests for TimeTZ**
More to come, but here are some now since the parser is all hooked up.

As this is not the fully featured commit yet, I am omitting the release
note until the test suite is more fleshed out.

Release note: none

### CODE REVIEW

**Comment by knz** [comment]
I haven't reviewed yet (and I'll let Solon do the first pass anyway) but I'd like to commend you on the elaborate commit message.

Also you probably want to refer to #26097 in the PR description.

**Review by solongordon — CHANGES_REQUESTED** [review]
Looks great in general! I left some mostly minor thoughts.

> Reviewed 51 of 51 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42481#-:-LtfU5uKD5fvCHVJHG6T:b-93wvl9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/logictest/testdata/logic_test/timetz, line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42481#-Ltf7L6-AjgwACXz0NTC:-Ltf7L6-AjgwACXz0NTD:b-tepfgt) ([raw file](https://github.com/cockroachdb/cockroach/blob/36dcdfd3c41dfe894aafd890aec7828703f5105f/pkg/sql/logictest/testdata/logic_test/timetz#L15)):*
> ```
> # structure underneath should still be correct.
> query B
> SELECT '24:00:00-1459' > '23:59:59-1459';
> ```

Looks like you're just comparing strings here, not TIMETZs. Better to do `SELECT '24:00:00-1459':::TIMETZ > '23:59:59-1459':::TIMETZ` or `SELECT b > '23:59:59-1459' FROM timetz_test WHERE c = 4`.

Also note that if it makes things less confusing, you can cast to string when you select from `timetz_test` in the queries below.
___
*[pkg/sql/sem/tree/datum.go, line 1958 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42481#-LtfDDBT6deaGOunxC4Y:-LtfDDBT6deaGOunxC4Z:bdey6r7) ([raw file](https://github.com/cockroachdb/cockroach/blob/36dcdfd3c41dfe894aafd890aec7828703f5105f/pkg/sql/sem/tree/datum.go#L1958)):*
> ```Go
> 
> var (
> 	dMaxTimeTZOffsetSecs = int32((14*time.Hour + 59*time.Minute) / time.Second)
> ```

This value is mysterious to me. Add a comment?

Also, just from fooling around in a Postgres shell it seems like maybe 15:59 is the max it accepts, not 14:59?

Also it doesn't look like you currently prevent storing a larger offset than this. Though maybe you're planning to handle that in follow-up parsing work?
___
*[pkg/sql/sem/tree/datum_invariants_test.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42481#-LtfHMRI0uKp2b6zryeo:-LtfHMRI0uKp2b6zryep:b-vo4yvn) ([raw file](https://github.com/cockroachdb/cockroach/blob/36dcdfd3c41dfe894aafd890aec7828703f5105f/pkg/sql/sem/tree/datum_invariants_test.go#L62)):*
> ```Go
> 			desc:     "same DTimeTZ are equal",
> 			left:     NewDTimeTZFromOffset(timeofday.New(22, 0, 0, 0), sydneyTimeZone),
> 			right:    NewDTimeTZFromOffset(timeofday.New(22, 0, 0, 0), sydneyTimeZone),
> ```

🇦🇺
___
*[pkg/sql/types/types.go, line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42481#-LtfKITx2njDeInwda7a:-LtfKITx2njDeInwda7b:b-qyxg4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/36dcdfd3c41dfe894aafd890aec7828703f5105f/pkg/sql/types/types.go#L255)):*
> ```Go
> 	// For example:
> 	//
> 	//   HH:MM:SS.sssss+-ZZ:ZZ
> ```

:mag_right: Is there an `s` missing?
___
*[pkg/util/encoding/encoding.go, line 955 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42481#-LtfONxnCSTxNuXKbnOv:-LtfONxnCSTxNuXKbnOw:b-qmfh2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/36dcdfd3c41dfe894aafd890aec7828703f5105f/pkg/util/encoding/encoding.go#L955)):*
> ```Go
> func EncodeTimeTZAscending(b []byte, t timetz.TimeTZ) []byte {
> 	// Do not use TimeOfDay's add function, as it loses 24:00:00 encoding.
> 	return encodeTimeTZ(b, int64(t.TimeOfDay)+int64(t.OffsetSecs)*1000000, t.OffsetSecs)
> ```

Nit: Would be nice to make `1000000` a named constant.
___
*[pkg/util/encoding/encoding_test.go, line 1288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42481#-LtfOw_-2iYNgy59rESm:-LtfOw_-2iYNgy59rESn:b-wp9uxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/36dcdfd3c41dfe894aafd890aec7828703f5105f/pkg/util/encoding/encoding_test.go#L1288)):*
> ```Go
> 	return timetz.MakeTimeTZ(
> 		timeofday.FromInt(rd.Int63n(int64(timeofday.Max))),
> 		rd.Int31n(28*60*60)-14*60*60,
> ```

Minor: Seems like this doesn't quite cover the max and min values.
___
*[pkg/util/timetz/timetz.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42481#-LtfR0nc8uSjLu3iHK0O:-LtfR0nc8uSjLu3iHK0P:b1l008y) ([raw file](https://github.com/cockroachdb/cockroach/blob/36dcdfd3c41dfe894aafd890aec7828703f5105f/pkg/util/timetz/timetz.go#L27)):*
> ```Go
> var (
> 	// TimeTZMaxTimeRegex is a compiled regex for parsing the 24:00 timetz value
> 	TimeTZMaxTimeRegex = regexp.MustCompile(`^24:00((:00)|(:00.0+))?([+-](([\d]+)|(\d{1,2}(:\d{1,2}){0,2})))?$`)
> ```

I'm probably missing something but seems like this regex could just be `^24` without any loss of functionality.
___
*[pkg/util/timetz/timetz.go, line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42481#-LtfTIALCQv0d9hg3fuB:-LtfTIALCQv0d9hg3fuC:b2nif2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/36dcdfd3c41dfe894aafd890aec7828703f5105f/pkg/util/timetz/timetz.go#L116)):*
> ```Go
> 	}
> 	// time.Format does not work for negative zone offsets
> 	// which are in seconds less than 60.
> ```

wat

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42481)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sql/logictest/testdata/logic_test/timetz, line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42481#-Ltf7L6-AjgwACXz0NTC:-LtzYmUK3HjJsfITwBTk:b-4dh6ph) ([raw file](https://github.com/cockroachdb/cockroach/blob/36dcdfd3c41dfe894aafd890aec7828703f5105f/pkg/sql/logictest/testdata/logic_test/timetz#L15)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Looks like you're just comparing strings here, not TIMETZs. Better to do `SELECT '24:00:00-1459':::TIMETZ > '23:59:59-1459':::TIMETZ` or `SELECT b > '23:59:59-1459' FROM timetz_test WHERE c = 4`.

Also note that if it makes things less confusing, you can cast to string when you select from `timetz_test` in the queries below.
</blockquote></details>

Done. Handy tip too - also converted to string casts!
___
*[pkg/sql/sem/tree/datum.go, line 1958 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42481#-LtfDDBT6deaGOunxC4Y:-LtzZlZI7vesV7t4twGc:bqvxxnl) ([raw file](https://github.com/cockroachdb/cockroach/blob/36dcdfd3c41dfe894aafd890aec7828703f5105f/pkg/sql/sem/tree/datum.go#L1958)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

This value is mysterious to me. Add a comment?

Also, just from fooling around in a Postgres shell it seems like maybe 15:59 is the max it accepts, not 14:59?

Also it doesn't look like you currently prevent storing a larger offset than this. Though maybe you're planning to handle that in follow-up parsing work?
</blockquote></details>

I was following https://www.postgresql.org/docs/current/datatype-datetime.html for 14:59 -- guess we might as well do 15:59!  

I will add a comment, and made sure the parser corrects for this.
___
*[pkg/sql/types/types.go, line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42481#-LtfKITx2njDeInwda7a:-Ltz_Tu2Cd626muj_9v4:b4w11ef) ([raw file](https://github.com/cockroachdb/cockroach/blob/36dcdfd3c41dfe894aafd890aec7828703f5105f/pkg/sql/types/types.go#L255)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

:mag_right: Is there an `s` missing?
</blockquote></details>

Done. Nice catch, hah!
___
*[pkg/util/timetz/timetz.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42481#-LtfR0nc8uSjLu3iHK0O:-LtzbkWb1DU7hMBgC2TX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/36dcdfd3c41dfe894aafd890aec7828703f5105f/pkg/util/timetz/timetz.go#L27)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I'm probably missing something but seems like this regex could just be `^24` without any loss of functionality.
</blockquote></details>

Done.
___
*[pkg/util/timetz/timetz.go, line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42481#-LtfTIALCQv0d9hg3fuB:-Ltzbm0l5iaxO-keagS6:bnx5oex) ([raw file](https://github.com/cockroachdb/cockroach/blob/36dcdfd3c41dfe894aafd890aec7828703f5105f/pkg/util/timetz/timetz.go#L116)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

wat
</blockquote></details>

Yep - clarified with a command.

**Review by solongordon — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42481#-:-Lu348npAJqU2nIi_JUR:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @solongordon)

**Comment by solongordon** [comment]
FYI it looks like one of the benchmarks is failing. You can reproduce like this:
```
make bench PKG=./pkg/util/encoding BENCHES=BenchmarkDecodeTimeTZValue
```

**Comment by otan** [comment]
Yeah, I thought it was a flake because `make bench` always flakes. Fixed it!

@knz did you want to review this, or can I push ahead?

**Comment by otan** [comment]
bors r=solongordon

i'm going to land this, i will respond to subsequent comments later - want to progress on this!

**Review by knz — COMMENTED** [review]
I can't review this properly anytime soon. I'll trust Solon on the code review, but please approach mjibson to do throrough random checks including comparison with pg.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42481#-:-Lu5DrXs9XXSXbhAcm6E:b-jqpbeg)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @solongordon)

**Pull request merged**
