### PR TITLE
util/log: replace --color flag with --nocolor flag

### LINKED ISSUE #4819: change --color flag to --nocolor with Boolean value
Currently, the `--color` flag accepts only one value, `auto`. Seems confusing to accept only one value; normally, you'd expect a range of accepted values in such a case.

It'd be clearer to make this a Boolean flag. Since colorizing won't always work, @tschottdorf and I discussed changing the flag to `nocolor` with a default of `false`.

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #4819.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4824)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4824#-:-KBxbrnDw2BzIAGGNU_p:676834233)*

**Comment by tschottdorf** [comment]
LGTM though I thought `--no-color` was more appropriate.

**Comment by petermattis** [comment]
Ok, renamed to `--no-color`.

**Comment by jseldess** [comment]
Added to docs with https://github.com/cockroachdb/docs/pull/88

**Pull request merged**
