### PR TITLE
sql: deprecate gossip-based physical planning

### PR DESCRIPTION
**Pull request by dt**
Previously system tenants and secondary tenants used differnt physical planning implementations, with the system tenant and only the system tenant using nodeIDs while other tenants used the instance table. This unifies those implementations such that all tenants use NodeIDs if running in mixed mode and use the instance table if not.

Release note: none.
Epic: CRDB-16910

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98527#-:-NQRj1Rd09UoixI4PjtB:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @knz, and @rharding6373)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98527#-NQRhLskA7kgOH-3RmsM):*
nit: `s/differnt/different/g`.
___
*[`pkg/sql/distsql_physical_planner.go` line 1289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98527#-NQRhm-s5CYVo1n0Kvoo:-NQRhm-s5CYVo1n0Kvop:b-ckovhx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec1eaf3ca735365e3be8e4ebfee7326105c85995/pkg/sql/distsql_physical_planner.go#L1289)):*
> ```Go
> }
> 
> // partitionSpansTenant assigns SQL instances in a tenant to spans. It performs
> ```

nit: this comment needs a minor adjustment.
___
*[`pkg/sql/distsql_physical_planner.go` line 1371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98527#-NQRiKM96uyOvRItKCE9:-NQRiKM96uyOvRItKCEA:b-9is6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec1eaf3ca735365e3be8e4ebfee7326105c85995/pkg/sql/distsql_physical_planner.go#L1371)):*
> ```Go
> 		// this server is in mixed mode, we can safely assume every other server
> 		// is as well, and thus has IDs matching node IDs.
> 		resolver = func(nodeID roachpb.NodeID) base.SQLInstanceID {
> ```

nit: does this result in an allocation? If so, perhaps it'd be worth to make this function non-anonymous?

**Review by dt — COMMENTED** [review]
Okay, so might not be quite as quick and easy as it initially looked to get this green/merged: Two main issues making this red right now:
1) there's lots of tests where the test setup / mocking / dependency plumbing / etc needs to be updated to just the test to even execute without nil-pointering
2) there are some legitimate behavior differences, namely around the distSQL version, that mean some tests are "correctly" failing

On (2), I'd forgotten this version filter behavior was still here; somehow I thought we'd moved away from this already in favor of more granular per-processor version difference handling. We discussed this on slack though and we do have incompatible changes in some processors between 22.2 and 23.1 that are relying on this version and the filtering for correctness. That said, this change here only uses the new no-version-filtering tenant implementation of planing for system tenants, who would not have previously used it, when the *cluster version* is 23.1, meaning that mixed clusters where 22.2 nodes are still participating in flows are not a concern. So we do not need to version-filtering to the tenant-implementation of planning at all, as long as that planning is only used when V23.1 is active.

So I think that means the tests that specifically expect to see version filtering can just be configured to use a <23.1 cluster version, so they won't try to use tenant planning, with its lack of version filtering.

So I think that just leaves all the stuff in (1) -- all the tests that currently setup gossip or whatever but not the instance reader or nodeid -- and need to be updated. I can start working my way through those, but just wanted to check that this sounds right before I sink a bunch of time into it?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98527#-:-NQRxuTm8xiFIJbimK1W:b-hr5m2r)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz, @rharding6373, and @yuzefovich)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98527#-NQRhLskA7kgOH-3RmsM):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `s/differnt/different/g`.
</blockquote></details>

Done.
___
*[`pkg/sql/distsql_physical_planner.go` line 1289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98527#-NQRhm-s5CYVo1n0Kvoo:-NQRxsq0-aRmc5RBUIck:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec1eaf3ca735365e3be8e4ebfee7326105c85995/pkg/sql/distsql_physical_planner.go#L1289)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this comment needs a minor adjustment.
</blockquote></details>

Done.
___
*[`pkg/sql/distsql_physical_planner.go` line 1371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98527#-NQRiKM96uyOvRItKCE9:-NQRx_7S2A9HPhGEMtqB:b-oon1xw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec1eaf3ca735365e3be8e4ebfee7326105c85995/pkg/sql/distsql_physical_planner.go#L1371)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: does this result in an allocation? If so, perhaps it'd be worth to make this function non-anonymous?
</blockquote></details>

not sure but I lifted anyway since that also lets me move the comment to live on it and then the logic in this function fits on one screen which seems nice.

**Review by rharding6373 — COMMENTED** [review]
Yes, the test setup will need updating with the distsql changes here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98527#-:-NQWcAyM0tfrwD5xbMcm:b45lir6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz and @yuzefovich)

**Comment by dt** [comment]
I'm going to work on the tests this week, but I'm feeling like I might want an escape hatch here in case we discovery any regressions we can't fix quickly in instance-based planning; I assume we'd want to fix them, since tenants use instance-based planning so it does need to work, but it might be nice to have a feature flag/session var/cluster setting/etc we can toggle quickly as well.

Is there an example of how to plumb a session var down here? or should I just go cluster setting?

**Comment by yuzefovich** [comment]
> Is there an example of how to plumb a session var down here? or should I just go cluster setting?

If `here` is to `partitionSpans` method, then we have the extended eval context in `PlanningCtx` which should have the session data available, so it looks like no additional plumbing is needed. Am I misunderstanding your question?

**Comment by dt** [comment]
> Am I misunderstanding your question?

Nope, that was exactly the answer I was looking for -- I just didn't know that the extended eval ctx is what I was looking for (it has been awhile since I spent any time in SQL code, sorry!)

**Comment by yuzefovich** [comment]
I think nowadays a session var is more preferable than a cluster setting (we have `ALTER ROLE ALL` that modifies a session var for all except `root`, if [curious](https://cockroachlabs.slack.com/archives/C0168LW5THS/p1674500089706209)). But overall either sounds reasonable to me.

**Review by knz — COMMENTED** [review]
I like it!

**Comment by dt** [comment]
I elected to comment out the 23.1 check part of this, so this is now just a code re-org, but not a behavior change in this diff, i.e. all system tenants keep using gossip for now, regardless of version. I still want to add the version check and/or session var to have then use the same planning as everyone else, but I have a backup diff on top of this change that is a higher priority right now so I'd rather come back to the behavior change -- an accompanying test breaks -- after that is in.

So I think this is a boring PR now.

**Review by knz — COMMENTED** [review]
I'll let yahor do the final review

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98527#-:-NR3AX0u54NQuo_skWSE:bd4ke4n)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98527#-:-NR4IyFED5U-y40NH513:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt)

___
*[`pkg/sql/distsql_physical_planner_test.go` line 1029 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98527#-NR4Ik-VCn-jDE0xTDG2:-NR4Ik-VCn-jDE0xTDG3:b11z96b) ([raw file](https://github.com/cockroachdb/cockroach/blob/381923760207e04b526fe4b23b4b110827942c8e/pkg/sql/distsql_physical_planner_test.go#L1029)):*
> ```Go
> 			dsp := DistSQLPlanner{
> 				planVersion: tc.planVersion,
> 				st: cluster.MakeTestingClusterSettingsWithVersions(
> ```

nit: is the change to versions here still necessary?

**Comment by dt** [comment]
TFTR!

bors r+

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98527)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz and @yuzefovich)

___
*[`pkg/sql/distsql_physical_planner_test.go` line 1029 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98527#-NR4Ik-VCn-jDE0xTDG2:-NR4JU28EFwQvqu_zr_1:bjrmxic) ([raw file](https://github.com/cockroachdb/cockroach/blob/381923760207e04b526fe4b23b4b110827942c8e/pkg/sql/distsql_physical_planner_test.go#L1029)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: is the change to versions here still necessary?
</blockquote></details>

nope, removed all changes to this file

**Pull request merged**
