### PR TITLE
kvserver: add cross-region snapshot byte metrics to StoreMetrics

### LINKED ISSUE #104124: kv: add metrics for cross-region snapshots
**Is your feature request related to a problem? Please describe.**
	
Currently, it is difficult to observe cross-region snapshots sent and received. 
This limitation becomes problematic when we need to assess the volume of 
cross-region snapshots across regions.
	
**Describe the solution you'd like**

One solution is to collect byte metrics of snapshots sent and received for each
store.

Jira issue: CRDB-28363

### PR DESCRIPTION
**Pull request by wenyihu6**
**kvserver: refactor getSnapshotBytesMetrics**

This commit refactors `getSnapshotBytesMetrics` in `replica_learner_test`
to return a `map[string]snapshotBytesMetrics` instead of
`map[SnapShotRequest_Priority]snapshotBytesMetrics`. This allows us to include
and compare different types of snapshot metrics, removing the constraint of
being limited to `SnapShotRequest_Priority`. This commit does not change any
existing functionality, and the main purpose is to make future commits cleaner.

Part of: https://github.com/cockroachdb/cockroach/issues/104124
Release note: none

---
 
**kvserver: add cross-region snapshot byte metrics to StoreMetrics**

Previously, there were no metrics to observe cross-region snapshot traffic
between stores within a cluster.

To improve this issue, this commit adds two new store metrics -
`range.snapshots.cross-region.sent-bytes` and
`range.snapshots.cross-region.rcvd-bytes`. These metrics track the aggregate of
snapshot bytes sent from and received at a store across different regions.

Resolves: https://github.com/cockroachdb/cockroach/issues/104124

Release note (ops change): Two new store metrics -
`range.snapshots.cross-region.sent-bytes` and
`range.snapshots.cross-region.rcvd-bytes` - are now added to track the aggregate
of snapshot bytes sent from and received at a store across different regions.
Note that these metrics require nodes’ localities to include a “region” tier
key. If a node lacks this key but is involved in cross-region snapshot activities,
an error message will be logged.

### CODE REVIEW

**Review by kvoli — COMMENTED** [review]
Took a brief look, really great! Lets walk though in more detail tomorrow.

> Reviewed 1 of 1 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-:-NWilNm56Xz9NGnySHeU:bbhqtjh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`pkg/kv/kvserver/allocator/storepool/store_pool.go` line 1392 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NWil2TG96jjvYtwbsRj:-NWil2TG96jjvYtwbsRk:brfb7h4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba2566ee6b553f7d78d6b9e5448c8521ba4e187/pkg/kv/kvserver/allocator/storepool/store_pool.go#L1392)):*
> ```Go
> func (sp *StorePool) GetNodeLocalityWithString(nodeID roachpb.NodeID) localityWithString {
> 	nodeLocality := localityWithString{
> 		str:      "",
> ```

nit: remove the extra initialization beyond `localityWithString`

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/allocator/storepool/store_pool.go` line 1392 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NWil2TG96jjvYtwbsRj:-NWlommK0m3gejiY8-Bi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba2566ee6b553f7d78d6b9e5448c8521ba4e187/pkg/kv/kvserver/allocator/storepool/store_pool.go#L1392)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: remove the extra initialization beyond `localityWithString`
</blockquote></details>

Done.

**Review by kvoli — CHANGES_REQUESTED** [review]
Great stuff! Left some suggestions but none are significant changes. Lmk if you have any questions.

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-:-NWm8FIf4GQ7_dWC_kLh:boqlfld)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`-- commits` line 17 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NWm1RcYAX19UnM-2oaC):*
The cross-region traffic is between stores residing in different region localities within a cluster. 

Perhaps reword to "cross region snapshot traffic, between stores in a cluster.
___
*[`-- commits` line 20 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NWm2kz54AOn8XV3yccF):*
nit: reword to "this commit adds two new store metrics - "
___
*[`-- commits` line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NWm22yOBC4zvFF8IEKH):*
Use the metric metadata name instead of the golang struct field name e.g.

`range.snapshots.cross-region.sent-bytes` and `range.snapshots.cross-region.rcvd-bytes`
___
*[`-- commits` line 22 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NWm2taiEailwsejocFE):*
nit: reword to make it clear these are aggregates per store, it is inferred by the counter but could be explicit e.g. "track the aggregate snapshot bytes sent from and received at a store".
___
*[`-- commits` line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NWm3Tws29rzIxqipOFk):*
Is this supposed to mention cross-region batch activities or snapshots?
___
*[`-- commits` line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NWm2eKTC477lNFBW-Ym):*
Same as above for referring to metrics in PRs/commits.
___
*[`pkg/kv/kvserver/replica_command.go` line 3148 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NWm51USB6t8PuuMTKKC:-NWm51USB6t8PuuMTKKD:b-sfzel6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0e047f9cefb38a606f2c46b165ce7f62f28cb0a/pkg/kv/kvserver/replica_command.go#L3148)):*
> ```Go
> 	}
> 
> 	maybeIncrementCrossRegionBatchMetrics := func(inc int64) {
> ```

Why name this `...CrossRegionBatchMetrics` as opposed to `...CrossRegionSnapshotMetrics`?
___
*[`pkg/kv/kvserver/replica_command.go` line 3151 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NWm3iwv6XjLhKuJJZNV:-NWm3iwv6XjLhKuJJZNW:b-hfrzb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0e047f9cefb38a606f2c46b165ce7f62f28cb0a/pkg/kv/kvserver/replica_command.go#L3151)):*
> ```Go
> 		storePool := r.store.cfg.StorePool
> 		if storePool == nil {
> 			log.Eventf(ctx, "store pool is nil")
> ```

When will the storepool be nil? Does this only occur in tests?
___
*[`pkg/kv/kvserver/replica_command.go` line 3155 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NWm4-WT5GxAt8_swG-V:-NWm4-WT5GxAt8_swG-W:btvk2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0e047f9cefb38a606f2c46b165ce7f62f28cb0a/pkg/kv/kvserver/replica_command.go#L3155)):*
> ```Go
> 			isCrossRegion, err := storePool.IsCrossRegion(req.CoordinatorReplica, req.RecipientReplica)
> 			if err != nil {
> 				log.Eventf(ctx, "%v", err)
> ```

This could be spammy and would be better logged as a warning if necessary.

Consider logging at a vmodule level of 2 and adding context to the error.

```go
if err != nil {
    // We are unable to determine if the snapshot was sent to a store in a different 
   // region or not. This can occur when ...
   log.VEventf(ctx, 2, "Unable to determine if batch is cross region %v", err)
}
```
___
*[`pkg/kv/kvserver/allocator/storepool/store_pool.go` line 1408 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NWm5YJJBx9IcS7G9pbN:-NWm5YJJBx9IcS7G9pbO:b7z5r0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0e047f9cefb38a606f2c46b165ce7f62f28cb0a/pkg/kv/kvserver/allocator/storepool/store_pool.go#L1408)):*
> ```Go
> 
> // GetNodeLocality returns the locality information for the given node.
> func (sp *StorePool) GetNodeLocality(nodeID roachpb.NodeID) roachpb.Locality {
> ```

Should these methods also be exported on the `AllocatorStorePool` interface? I'm not certain they necessarily need to, what do you think?

 Also I only see `IsCrossRegion` being used outside this pkg, do the other two methods need to be exported?
___
*[`pkg/kv/kvserver/replica_learner_test.go` line 2211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NWm-wR-Anshtwndawjd:-NWm-wR-Anshtwndawje:b-xthewz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0db476af319497ba69c105643e80e6fd071f6c3/pkg/kv/kvserver/replica_learner_test.go#L2211)):*
> ```Go
> 		}
> 	}
> 	types := [4]string{".unknown", ".recovery", ".rebalancing", ""}
> ```

nit: move types inline with the loop

```go
for _, v := range [4]string{...} {  ... }
```

Is the reason you are using the metric names as constant strings here, as opposed to from the metadata in https://github.com/cockroachdb/cockroach/blob/3ff847a405b89339e9adfc910429db8d0b09cbf9/pkg/kv/kvserver/metrics.go#L890-L890 because they are private to the `kvserver_test` pkg?
___
*[`pkg/kv/kvserver/replica_learner_test.go` line 2413 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NWm7rmy6hBf_TLzAQRC:-NWm7rmy6hBf_TLzAQRD:b-56v4j5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0e047f9cefb38a606f2c46b165ce7f62f28cb0a/pkg/kv/kvserver/replica_learner_test.go#L2413)):*
> ```Go
> 	}
> 	require.Equal(t, receiverMapExpected, receiverMapDelta)
> ```

Nice test extension! Would it be possible to add a case where `region` isn't set, but other locality attributes are such as `zone` and `dc` - then assert that the cross-region metrics are unchanged? It may be helpful to get a feel for how noisy the log messages added above are as well.

**Comment by wenyihu6** [comment]
*[`-- commits` line 20 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NWm2kz54AOn8XV3yccF):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: reword to "this commit adds two new store metrics - "
</blockquote></details>

Done.

**Comment by wenyihu6** [comment]
*[`-- commits` line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NWm22yOBC4zvFF8IEKH):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Use the metric metadata name instead of the golang struct field name e.g.

`range.snapshots.cross-region.sent-bytes` and `range.snapshots.cross-region.rcvd-bytes`
</blockquote></details>

Done.

**Comment by wenyihu6** [comment]
*[`-- commits` line 22 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NWm2taiEailwsejocFE):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: reword to make it clear these are aggregates per store, it is inferred by the counter but could be explicit e.g. "track the aggregate snapshot bytes sent from and received at a store".
</blockquote></details>

Done.

**Comment by wenyihu6** [comment]
*[`-- commits` line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NWm3Tws29rzIxqipOFk):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Is this supposed to mention cross-region batch activities or snapshots?
</blockquote></details>

Oops 😅

**Comment by wenyihu6** [comment]
*[`-- commits` line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NWm2eKTC477lNFBW-Ym):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Same as above for referring to metrics in PRs/commits.
</blockquote></details>

Done.

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/replica_command.go` line 3148 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NWm51USB6t8PuuMTKKC:-NWqjFYa4taLFGdU6Hq6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0e047f9cefb38a606f2c46b165ce7f62f28cb0a/pkg/kv/kvserver/replica_command.go#L3148)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Why name this `...CrossRegionBatchMetrics` as opposed to `...CrossRegionSnapshotMetrics`?
</blockquote></details>

Done.

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/replica_command.go` line 3151 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NWm3iwv6XjLhKuJJZNV:-NWqjHQB4jRXTnpswasa:bhzmfaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0e047f9cefb38a606f2c46b165ce7f62f28cb0a/pkg/kv/kvserver/replica_command.go#L3151)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

When will the storepool be nil? Does this only occur in tests?
</blockquote></details>

Discussed offline - this was for sanity check, but it should never happen. I've removed the check.

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/replica_command.go` line 3155 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NWm4-WT5GxAt8_swG-V:-NWqjnz9-LFoPLBk-dIF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0e047f9cefb38a606f2c46b165ce7f62f28cb0a/pkg/kv/kvserver/replica_command.go#L3155)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

This could be spammy and would be better logged as a warning if necessary.

Consider logging at a vmodule level of 2 and adding context to the error.

```go
if err != nil {
    // We are unable to determine if the snapshot was sent to a store in a different 
   // region or not. This can occur when ...
   log.VEventf(ctx, 2, "Unable to determine if batch is cross region %v", err)
}
```
</blockquote></details>

Done.

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/replica_learner_test.go` line 2211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NWm-wR-Anshtwndawjd:-NWqk_jV-M9q-ZgJEDJb:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0db476af319497ba69c105643e80e6fd071f6c3/pkg/kv/kvserver/replica_learner_test.go#L2211)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: move types inline with the loop

```go
for _, v := range [4]string{...} {  ... }
```

Is the reason you are using the metric names as constant strings here, as opposed to from the metadata in https://github.com/cockroachdb/cockroach/blob/3ff847a405b89339e9adfc910429db8d0b09cbf9/pkg/kv/kvserver/metrics.go#L890-L890 because they are private to the `kvserver_test` pkg?
</blockquote></details>

Done.

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/replica_learner_test.go` line 2413 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NWm7rmy6hBf_TLzAQRC:-NWqkgIj5YP2Pk3sqg-6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0e047f9cefb38a606f2c46b165ce7f62f28cb0a/pkg/kv/kvserver/replica_learner_test.go#L2413)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Nice test extension! Would it be possible to add a case where `region` isn't set, but other locality attributes are such as `zone` and `dc` - then assert that the cross-region metrics are unchanged? It may be helpful to get a feel for how noisy the log messages added above are as well.
</blockquote></details>

Done.

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/allocator/storepool/store_pool.go` line 1408 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NWm5YJJBx9IcS7G9pbN:-NWqkmof6ynT-xFsiJbw:b-agot9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0e047f9cefb38a606f2c46b165ce7f62f28cb0a/pkg/kv/kvserver/allocator/storepool/store_pool.go#L1408)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Should these methods also be exported on the `AllocatorStorePool` interface? I'm not certain they necessarily need to, what do you think?

 Also I only see `IsCrossRegion` being used outside this pkg, do the other two methods need to be exported?
</blockquote></details>

1. Discussed offline - It seems like AllocatorStorePool typically relies on a list of all known stores or replicas within the cluster rather than focusing on a single node. And we already have `GetLocalitiesByNode` serving similar purposes. So we have decided not to include this function to the interface as of now.

2. I changed `GetNodeLocality` to private method. `GetNodeLocalityString` is also used outside of the storepool package in [`pkg/kv/kvserver/replica_init.go`](https://github.com/cockroachdb/cockroach/blob/a69d0ea23211bad7c9332522d99e17cce4c48b06/pkg/kv/kvserver/replica_init.go#L122) .

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/replica_learner_test.go` line 2413 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NWm7rmy6hBf_TLzAQRC:-NWtNdW-0Sj2aqA7p6fu:b-89o0ya) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0e047f9cefb38a606f2c46b165ce7f62f28cb0a/pkg/kv/kvserver/replica_learner_test.go#L2413)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I will check again when we run more experiments on a larger cluster. With just this test case, there were only two error messages (one for sending, one for receiving). But I'm assuming we would want to assess the noise level in a larger cluster where cross-region snapshots are being sent more frequently.

**Review by kvoli — COMMENTED** [review]
:lgtm: @andrewbaptist  would you be able to review as well? This code was last touched heavily by you for delegated snapshots.

> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-:-NXAgpWfBUWsIVhU2jzL:bnc5xkt)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist and @wenyihu6)

___
*[`-- commits` line 22 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NWm2taiEailwsejocFE):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I know its very much implied by the name but adding "...aggregate cross-region snapshot bytes..." would be clearer.
___
*[`-- commits` line 25 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-NXAeoMf0x_Y8mEQSe5V):*
nit: "Resolves" is probably a better linking term, since this wasn't a bug - just a feature.

**Review by kvoli — APPROVED** [review]

**Review by andrewbaptist — APPROVED** [review]
:lgtm: - This will cause a few conflicts in my PR for #102629 - but I will fix that up after this merges. That PR does also remove the UNKNOWN metric since it is never populated, so we could simplify this by removing this here as it is always checked against 0, but its not important to do.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104111#-:-NXAtCVA9kcCoyrAtWZq:b-bep3e4)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @wenyihu6)

**Comment by wenyihu6** [comment]
TFTRs!

bors r=kvoli, andrewbaptist

**Pull request merged**
