### PR TITLE
colexec: memory accounting at row granularity in columnarizer

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: remove redundant allocations when converting from rows**

This redundant allocation has been present since the introduction of the
vectorized engine (it was introduced in
37957a9b4e6964940ed2dd4d94b4dbfa671a11aa I think by accident - the
impact of some changes in that commit were probably not understood and
we didn't have the benchmarks to catch the regression).
```
Columnarize-24                442µs ± 1%     157µs ± 0%   -64.49%  (p=0.000 n=10+9)
ColumnarizeMaterialize-24     801µs ± 1%     513µs ± 0%   -35.89%  (p=0.000 n=10+10)

name                       old speed      new speed      delta
Columnarize-24              362MB/s ± 1%  1019MB/s ± 0%  +181.61%  (p=0.000 n=10+9)
ColumnarizeMaterialize-24   200MB/s ± 1%   312MB/s ± 0%   +55.97%  (p=0.000 n=10+10)

name                       old alloc/op   new alloc/op   delta
Columnarize-24                157kB ± 0%       0kB ± 1%   -99.85%  (p=0.000 n=10+9)
ColumnarizeMaterialize-24     356kB ± 0%     200kB ± 0%   -43.94%  (p=0.000 n=10+9)

name                       old allocs/op  new allocs/op  delta
Columnarize-24                19.5k ± 0%      0.0k ± 0%   -99.98%  (p=0.000 n=10+10)
ColumnarizeMaterialize-24     19.5k ± 0%      0.0k ± 0%   -99.77%  (p=0.000 n=10+10)
```
Additionally, the conversion method no longer returns an error that is
encountered during the datum decoding since every caller of the method
is panicking with the error anyway.

Release justification: low-risk improvement.

Release note: None

**colexec: memory accounting at row granularity in columnarizer**

This commit makes it so that we perform the memory accounting at a row
granularity (rather than a batch granularity) in the columnarizer as
well as the values operator. As a result, we will respect memory limits
much better than previously.

The main idea is that previously we were converting from the row-based
format to the columnar one a column at a time, and now we will perform
the conversion one full row at a time. As expected, this leads to
a performance regression, but given the speedup in the previous commit
and the improvement to the stability of Cockroach, it seems worth it.
```
name                       old time/op    new time/op    delta
Columnarize-24                157µs ± 1%     291µs ± 0%  +85.05%  (p=0.000 n=8+10)
ColumnarizeMaterialize-24     514µs ± 0%     648µs ± 0%  +26.09%  (p=0.000 n=9+9)

name                       old speed      new speed      delta
Columnarize-24             1.02GB/s ± 1%  0.55GB/s ± 0%  -45.96%  (p=0.000 n=8+10)
ColumnarizeMaterialize-24   311MB/s ± 0%   247MB/s ± 0%  -20.69%  (p=0.000 n=9+9)

name                       old alloc/op   new alloc/op   delta
Columnarize-24                 229B ± 1%      375B ± 1%  +63.96%  (p=0.000 n=9+10)
ColumnarizeMaterialize-24     200kB ± 0%     200kB ± 0%   +0.05%  (p=0.000 n=10+10)

name                       old allocs/op  new allocs/op  delta
Columnarize-24                 4.00 ± 0%      7.00 ± 0%  +75.00%  (p=0.000 n=10+10)
ColumnarizeMaterialize-24      44.0 ± 0%      47.0 ± 0%   +6.82%  (p=0.000 n=10+10)
```

This commit makes the corresponding change to the method and file names
to indicate that now the conversion is from a single row into all
vectors at once.

Addresses: #76464.

Release justification: bug fix.

Release note: None

----

The performance impact of both commits combined:
```
name                       old time/op    new time/op    delta
Columnarize-24                441µs ± 0%     292µs ± 1%  -33.80%  (p=0.000 n=9+10)
ColumnarizeMaterialize-24     800µs ± 1%     648µs ± 0%  -18.99%  (p=0.000 n=10+10)

name                       old speed      new speed      delta
Columnarize-24              363MB/s ± 0%   548MB/s ± 1%  +51.07%  (p=0.000 n=9+10)
ColumnarizeMaterialize-24   200MB/s ± 1%   247MB/s ± 0%  +23.44%  (p=0.000 n=10+10)

name                       old alloc/op   new alloc/op   delta
Columnarize-24                157kB ± 0%       0kB ± 1%  -99.76%  (p=0.000 n=10+9)
ColumnarizeMaterialize-24     356kB ± 0%     200kB ± 0%  -43.91%  (p=0.000 n=9+9)

name                       old allocs/op  new allocs/op  delta
Columnarize-24                19.5k ± 0%      0.0k ± 0%  -99.96%  (p=0.000 n=10+10)
ColumnarizeMaterialize-24     19.5k ± 0%      0.0k ± 0%  -99.76%  (p=0.000 n=10+9)
```

### CODE REVIEW

**Review by DrewKimball — COMMENTED** [review]
Great find on that extra allocation!

> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87242#-:-NAqESbj8Q3L9ZkyceTP:byq5fey)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @yuzefovich)

___
*[`pkg/sql/colexec/columnarizer.go` line 221 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87242#-NAqCt4tBk38FX6GSra3:-NAqCt4tBk38FX6GSra4:bvc6i32) ([raw file](https://github.com/cockroachdb/cockroach/blob/3de0434b6fc9b2cfe262e4b33da2b9933f81c26c/pkg/sql/colexec/columnarizer.go#L221)):*
> ```Go
> 			}
> 			c.accumulatedMeta = append(c.accumulatedMeta, *meta)
> 			colexecutils.AccountForMetadata(c.allocator, c.accumulatedMeta[len(c.accumulatedMeta)-1:])
> ```

Is it ok to use the allocator here when the `SetAccountingHelper` is using it?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87242)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @msirek)

___
*[`pkg/sql/colexec/columnarizer.go` line 221 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87242#-NAqCt4tBk38FX6GSra3:-NAqPm-r4a7MHQWDpmW5:b-l0t6ei) ([raw file](https://github.com/cockroachdb/cockroach/blob/3de0434b6fc9b2cfe262e4b33da2b9933f81c26c/pkg/sql/colexec/columnarizer.go#L221)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Is it ok to use the allocator here when the `SetAccountingHelper` is using it?
</blockquote></details>

Nice catch! Fixed.

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87242#-:-NAqpTLa9UPVhTyck8g7:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @msirek, and @yuzefovich)

___
*[`pkg/sql/colexec/columnarizer.go` line 263 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/87242#-NAqovFe8Z3w4q-woCDc:-NAqovFe8Z3w4q-woCDd:b-99pslk) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbc9c9f9939c0de92cf5df56ece4946e3cc9b94b/pkg/sql/colexec/columnarizer.go#L263)):*
> ```Go
> 	c.batch = nil
> 	c.helper.ReleaseMemory()
> 	c.helper.Release()
> ```

Is this the only place where we want / it's ok to do both these things at once? If it's ok to release the allocator's memory in `SetAccountingHelper.Release()`, it would be nice to combine things.

**Review by msirek — APPROVED** [review]
This is great!  It should really help cases with variable size or large data types. 
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87242#-:-NArW1fu2OmGzl8EifaM:b5x9xp4)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball and @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87242#-:-NAtVjwq8bYleVok0VkN:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball)

___
*[`pkg/sql/colexec/columnarizer.go` line 263 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/87242#-NAqovFe8Z3w4q-woCDc:-NAtWj1p4unk40f_kDoC:b-3rqeik) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbc9c9f9939c0de92cf5df56ece4946e3cc9b94b/pkg/sql/colexec/columnarizer.go#L263)):*
> Is this the only place where we want / it's ok to do both these things at once?

Yes, but I moved the call to `Release` into `Close` to make it similar to other operators.

> If it's ok to release the allocator's memory in `SetAccountingHelper.Release()`

I've thought about it and two methods serve different purpose. `Release` is kinda like `execreleasable.Releasable` interface which generally is called at the very end of the execution cleanup, after closing memory accounts, so at that point `ReleaseMemory` would be too late. In case of the columnarizer, we could have combined them, but then we'd need to audit other users of the `SetAccountingHelper` to move the call to `Release` earlier, and I decided against it.

**Pull request merged**
