### PR TITLE
release-22.1: ui: remove some functions generated by protobufjs

### PR DESCRIPTION
**Pull request by sjbarag**
Backport 1/1 commits from #101340 on behalf of @sjbarag.

/cc @cockroachdb/release

-----

Previously, a pretty wide range of methods was generated for each JS class produced by protobufjs. Some of these were unused, or were only used in tests (and were thus easy to replace). Luckily, the pbjs CLI offers flags to not emit some of these! Specifically:

* --no-create removes the static .create() method. It's nearly equivalent to the constructor that's already generated. Foo.create() accepts a pure JS object, but new Foo() requires nested types to be constructed with new Bar(). Its few uses are easily replaced.
* --no-verify removes the .verify() method. It was never used.
* --no-convert removes the .toJSON() and .fromJSON() methods, which were only used in a few tests (most uses were stub definitions).
* --no-delimited removes the .encodeDelimited and .encodeDelimited methods, which were never used.

With these flags added to the pbjs invocation, we can reduce emitted file sizes pretty drastically (all values in kilobytes, measured with `du -k`):

    protos.js                          16532 ->  6944 (-9588)
    cluster-ui/dist/main.js             8184 ->  5372 (-2812)
    db-console-ccl/assets/bundle.js    22068 -> 13612 (-8456)

Part of: #88876
Release note: None

### CODE REVIEW

**Comment by koorosh** [comment]
Looks like it has to be changed in `Makefile` because it is used a build tool for `22.1` 

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BuildTestBinary/9824408?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&showLog=9824408_5293_617.630&logFilter=debug

**Comment by sjbarag** [comment]
> Looks like it has to be changed in `Makefile` because it is used a build tool for `22.1`
> 
> https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BuildTestBinary/9824408?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&showLog=9824408_5293_617.630&logFilter=debug

Oh good catch! I could have sworn we released 22.1 via Bazel, but cluster-ui might get build via Make for manual publishes anyway. I'll fix that up today :)

**Review by koorosh — APPROVED** [review]
Add release justification and it is LGTM!

**Comment by sjbarag** [comment]
> Add release justification and it is LGTM!

Looks like it's not required ([slack link](https://cockroachlabs.slack.com/archives/C4A9ALLRL/p1682700590314729?thread_ts=1682697955.153079&cid=C4A9ALLRL)) 🙂 

Thanks for the review!!

**Pull request merged**
