### PR TITLE
sql: add some missing postgres vars for ORM compatibility

### LINKED ISSUE #12109: sql: support client_min_messages variable
Sequelize tries to set `client_min_messages` when it starts up:

`SET client_min_messages TO warning;`

Support `client_min_messages` as a no-op variable for now.

### LINKED ISSUE #12112: sql: support read-only SERVER_VERSION variable
Sequelize tries to read the value of `SHOW SERVER_VERSION`, which we currently don't support. Internally, it will parse the value of `SERVER_VERSION` as a `semver` and compare it against various known postgres versions to check for feature compatibility.

If we want to support Sequelize without patching it, we'll need to return a value for `SERVER_VERSION` that reflects the latest version of Postgres that we claim to mimic.

### LINKED ISSUE #12113: sql: support STANDARD_CONFORMING_STRINGS
Sequelize tries to run `SET standard_conforming_strings=on` when it starts up.

We don't support this variable, but we need to - it's on by default in postgres. We can make it a runtime error to set this variable to anything except for `on`, since we probably don't care to support anything else. Leaving this on ensures that backslashes in strings are treated literally and not as escape characters.

See the docs: https://www.postgresql.org/docs/9.1/static/runtime-config-compatible.html
Here's the relevant issue from sequelize: https://github.com/sequelize/sequelize/issues/3545

### LINKED ISSUE #12134: sql: support CLIENT_ENCODING variable
ActiveRecord tries to set `CLIENT_ENCODING` to `UTF8` when it starts up, but we don't support this variable.

Perhaps a good first step would be allowing clients to set this variable, but only to `UTF8` if that's all we support. What would it take to support this properly?

### LINKED ISSUE #12137: sql: support SEARCH_PATH variable
ActiveRecord tries to set `SEARCH_PATH` to `public` when it starts up. We need to support this.

See https://www.postgresql.org/docs/9.1/static/runtime-config-client.html

### PR DESCRIPTION
**Pull request by jordanlewis**
This PR adds no-op support for setting the following variables, to improve ORM compatability:

- `SEARCH_PATH`
- `CLIENT_ENCODING`
- `STANDARD_CONFORMING_STRINGS`
- `CLIENT_MIN_MESSAGES`

It also adds support for`SHOW SERVER_VERSION`, always returning the `9.5.0` postgres version that we return over `pgwire`.

Resolves #12137 
Resolves #12134 
Resolves #12113 
Resolves #12109 
Resolves #12112

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12149)

### CODE REVIEW

**Comment by cuongdo** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/set.go, line 126 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12149#-KYTxR4i8sv9SFrt4HF7:-KYTxR4i8sv9SFrt4HF8:b-fqqwlk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f81186ed88f6060a347c30bb90d86d46a15ec5b6/pkg/sql/set.go#L126)):*
> ```Go
> 	// See https://www.postgresql.org/docs/9.6/static/runtime-config-logging.html#GUC-APPLICATION-NAME
> 	case `CLIENT_ENCODING`:
> 	// See https://www.postgresql.org/docs/9.6/static/multibyte.html
> ```

should we return an error if anything but UTF-8 is specified?

---

*[pkg/sql/set.go, line 134 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12149#-KYTynYHHphafd4vpC1D:-KYTynYHHphafd4vpC1E:b-7t5wqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/f81186ed88f6060a347c30bb90d86d46a15ec5b6/pkg/sql/set.go#L134)):*
> ```Go
> 	// See https://www.postgresql.org/docs/9.6/static/runtime-config-client.html
> 	case `STANDARD_CONFORMING_STRINGS`:
> 	// If true, escape backslash literals in strings. We do this by default.
> ```

should we return an error or log a warning if an attempt is made to set to disable this? what happens if a client sets this to `off` and assumes that we honor that?

---

*[pkg/sql/set.go, line 135 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12149#-KYTyfMN4mxB7E4QdR9U:-KYTyfMN4mxB7E4QdR9V:bdjdr6r) ([raw file](https://github.com/cockroachdb/cockroach/blob/f81186ed88f6060a347c30bb90d86d46a15ec5b6/pkg/sql/set.go#L135)):*
> ```Go
> 	case `STANDARD_CONFORMING_STRINGS`:
> 	// If true, escape backslash literals in strings. We do this by default.
> 	// See https://www.postgresql.org/docs/9.6/static/runtime-config-client.html
> ```

This is the right page:
https://www.postgresql.org/docs/9.1/static/runtime-config-compatible.html#GUC-STANDARD-CONFORMING-STRINGS

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12149)*

**Comment by jordanlewis** [comment]
TFTR!

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/set.go, line 126 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12149#-KYTxR4i8sv9SFrt4HF7:-KYUIqFJsW5t_7H47tjZ:b-qbcrof) ([raw file](https://github.com/cockroachdb/cockroach/blob/f81186ed88f6060a347c30bb90d86d46a15ec5b6/pkg/sql/set.go#L126)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

should we return an error if anything but UTF-8 is specified?
</blockquote></details>

I suppose that would be nice of us, yes. Done.

---

*[pkg/sql/set.go, line 134 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12149#-KYTynYHHphafd4vpC1D:-KYUJ1Mqf2DNUyi9YFoY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f81186ed88f6060a347c30bb90d86d46a15ec5b6/pkg/sql/set.go#L134)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

should we return an error or log a warning if an attempt is made to set to disable this? what happens if a client sets this to `off` and assumes that we honor that?
</blockquote></details>

Done.

---

*[pkg/sql/set.go, line 135 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12149#-KYTyfMN4mxB7E4QdR9U:-KYUJ6FAdVdxxn0ux9lT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f81186ed88f6060a347c30bb90d86d46a15ec5b6/pkg/sql/set.go#L135)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

This is the right page:
https://www.postgresql.org/docs/9.1/static/runtime-config-compatible.html#GUC-STANDARD-CONFORMING-STRINGS
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12149#-:-KYUJ7j2GPpRg2-Wzz7l:b-814g8k)*

**Comment by cuongdo** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/set.go, line 126 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12149#-KYTxR4i8sv9SFrt4HF7:-KYULuWzG22EmhnKag1-:b-rv5qm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f81186ed88f6060a347c30bb90d86d46a15ec5b6/pkg/sql/set.go#L126)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I suppose that would be nice of us, yes. Done.
</blockquote></details>

Can you also add a test for the error case?

---

*[pkg/sql/set.go, line 134 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12149#-KYTynYHHphafd4vpC1D:-KYULxRzjFyPCzOi-Pfx:b-dmi5i2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f81186ed88f6060a347c30bb90d86d46a15ec5b6/pkg/sql/set.go#L134)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Could you add a test for the error case?

---

*[pkg/sql/set.go, line 151 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12149#-KYUM-Mx-XN3I3SfEcqY:-KYUM-Mx-XN3I3SfEcqZ:bl4kck6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee2dface77611e55de1b17cb17d697171a23b2df/pkg/sql/set.go#L151)):*
> ```Go
> 		switch parser.Name(s).Normalize() {
> 		case parser.ReNormalizeName("off"):
> 			return nil, fmt.Errorf("STANDARD_CONFORMING_STRINGS=off not supported")
> ```

nit: `errors.New` instead of `fmt.Errorf`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12149)*

**Comment by jordanlewis** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/set.go, line 126 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12149#-KYTxR4i8sv9SFrt4HF7:-KYUOMM3HXiREqTKIyES:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f81186ed88f6060a347c30bb90d86d46a15ec5b6/pkg/sql/set.go#L126)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

Can you also add a test for the error case?
</blockquote></details>

Done.

---

*[pkg/sql/set.go, line 134 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12149#-KYTynYHHphafd4vpC1D:-KYUOMruYOXa7Wiifhdl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f81186ed88f6060a347c30bb90d86d46a15ec5b6/pkg/sql/set.go#L134)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

Could you add a test for the error case?
</blockquote></details>

Done.

---

*[pkg/sql/set.go, line 151 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12149#-KYUM-Mx-XN3I3SfEcqY:-KYUONC5O5yEPPIQvnJW:bz7ola7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee2dface77611e55de1b17cb17d697171a23b2df/pkg/sql/set.go#L151)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

nit: `errors.New` instead of `fmt.Errorf`?
</blockquote></details>

Simplified this case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12149)*

**Comment by cuongdo** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12149#-:-KYUeVy_WBt6Wivifjof:bnfp4nl)*

**Comment by jseldess** [comment]
In the future, when we have a page collecting session variables, these might be included.

**Pull request merged**
