### PR TITLE
sql: fix the sorting in TestLogic

### LINKED ISSUE #12017: sql: TestLogic is confused with sorted rows
If a test specifies a `rowsort` constraint for a query (i.e. the rows from the server must be sorted before comparison with the reference output), but the reference output is not properly sorted, then the test never passes but the error message does not explain why! 

That's because the error message shows the actual and expected results before sorting, so if the sort for the actual results produces something different there will be an invisible failure.

Reproduce with:

```
statement ok
CREATE TABLE kv (
  k INT PRIMARY KEY,
  v INT
)

statement OK
INSERT INTO kv VALUES
(1, 2),
(3, 4),
(5, NULL),
(6, 2),
(7, 2),
(8, 4)

query I rowsort
SELECT k + v FROM kv GROUP BY k + v ORDER BY k + v
----
NULL
3
7
8
9
12
```

it fails with:
```
    		expected:
    		    NULL
    		    3
    		    7
    		    8
    		    9
    		    12
    		but found:
    		    NULL  
    		    3     
    		    7     
    		    8     
    		    9     
    		    12    
    		
FAIL
```

### PR DESCRIPTION
**Pull request by knz**
Fixes #12017.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12018)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12018)*

**Comment by irfansharif** [comment]
:lgtm: wow that was fast, thanks!

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12018#-:-KYF1zUzQerp0LOCSdyt:bgxl5u0)*

**Comment by RaduBerinde** [comment]
Does the second commit solve a real problem? It was more convenient to have the tests be named `TestLogic/join` instead of `TestLogic/testdata/join`..

**Comment by knz** [comment]
Irfan is wanting to put his tests in a "distsql" sub-dir.

**Comment by RaduBerinde** [comment]
I see. So we will have  `/testdata/xxx` and `/testdata/distsql/xxx`? Or separate toplevel dirs `testdata/...` and `distsqltestdata/...` (similar how we have `partestdata/`)?. If it's a separate toplevel dir, we could also make a separate test `TestDistLogic`.

**Comment by irfansharif** [comment]
> Irfan is wanting to put his tests in a "distsql" sub-dir.

not really, i just kept it separate when iterating for ease of change.

**Pull request merged**
