### PR TITLE
all: replace util/errors with github.com/pkg/errors

### PR DESCRIPTION
**Pull request by tamird**
There's lots of room for improvement here, since the interface provided
by github.com/pkg/errors is much richer; we'll get there incrementally.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7424)

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM. Could you augment the commit message with the (negligible) downside that while `%+v` prints the whole stacktrace for such errors, `%s` will not?

**Comment by tamird** [comment]
Done.

**Comment by tamird** [comment]
@bdarnell might want to take a look at this as well.

**Comment by BramGruneir** [comment]
Is the follow up step to this, to move a lot of our current 
```
if err != nil {
        return err
}
```
to
```
if err != nil {
        return errors.Wrap(err, "read failed")
}
```

**Comment by tschottdorf** [comment]
Yes

On Thu, Jun 23, 2016 at 12:35 PM Bram Gruneir <notifications@github.com>
wrote:

> Is the follow up step to this, to move a lot of our current
>
> if err != nil {
>         return err
> }
>
> to
>
> if err != nil {
>         return errors.Wrap(err, "read failed")
> }
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/7424#issuecomment-228107503>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135CLEsKWH5uUC4lqetdJZB92cRf7fks5qOrW3gaJpZM4I83jl>
> .
>
-- 

-- Tobias

**Comment by tamird** [comment]
Yep, but I wouldn't do that eagerly

**Comment by andreimatei** [comment]
Nice! I think this deserves a PSA.

On Thu, Jun 23, 2016 at 12:58 PM, Tamir Duberstein <notifications@github.com

**Comment by tamird** [comment]
Agreed, will send.

**Comment by RaduBerinde** [comment]
The benefit of `util.Errorf` was that we could use it for errors which are probably bugs and the extra information would show up automatically (thinking here of cases where the error is returned to the SQL client for which we presumably use `%s`). 

Would it be worth adding a version of `Errorf` that makes the error "verbose" - i.e. shows more information (like the file/line) with `%s`? (it's something we could propose)

**Comment by tamird** [comment]
Yeah, that was one of the benefits - I'd be in favour of introducing that upstream

**Comment by RaduBerinde** [comment]
Cool - filed https://github.com/pkg/errors/issues/59

**Pull request merged**
