### PR TITLE
sql: generate more varied floats in RSG test

### LINKED ISSUE #9885: sql: investigate why RSG didn't find misuse of pow
See #9756.

The RSG function checking should have found this. Figure out why it didn't.

### PR DESCRIPTION
**Pull request by madelynnblue**
Fixes #9885

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9995)

### CODE REVIEW

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/rsg_test.go, line 122 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9995#-KU4EeU2Cg8VNGVqPjY-:-KU4EeU2Cg8VNGVqPjY0:bp8ytrh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b492745910d5b86b153a4739ffae39e47d57e96d/pkg/sql/rsg_test.go#L122)):*
> ```Go
> 				case *parser.DFloat, *parser.DDecimal:
> 					f := r.Float64()
> 					switch r.Int63() % 3 {
> ```

can't this whole thing be replaced with `f := r.NormFloat64()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9995)*

**Comment by mjibson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/rsg_test.go, line 122 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9995#-KU4EeU2Cg8VNGVqPjY-:-KU5i50Lp6_acp9pem09:b-dxh5bg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b492745910d5b86b153a4739ffae39e47d57e96d/pkg/sql/rsg_test.go#L122)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can't this whole thing be replaced with `f := r.NormFloat64()`?
</details>
Yes. My mistake, r.Float64 already is NormFloat64, which I missed. Changed to just make it very large or very small sometimes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9995)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/rsg_test.go, line 122 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9995#-KU4EeU2Cg8VNGVqPjY-:-KU6zccrJOLY1pr1rqm6:b-77wu1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/b492745910d5b86b153a4739ffae39e47d57e96d/pkg/sql/rsg_test.go#L122)):*
Float64() is not NormFloat64().

> Float64 returns, as a float64, a pseudo-random number in [0.0,1.0).

> NormFloat64 returns a normally distributed float64 in the range [-math.MaxFloat64, +math.MaxFloat64] with standard normal distribution (mean = 0, stddev = 1).

But if you want a uniform random number in the range `[-math.MaxFloat64, +math.MaxFloat64]`, why not `(r.Float64() * 2 -1) * math.MaxFloat64`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9995)*

**Comment by mjibson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/rsg_test.go, line 122 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9995#-KU4EeU2Cg8VNGVqPjY-:-KU8IMOb2Y9-rID5_21y:b-6n5me7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b492745910d5b86b153a4739ffae39e47d57e96d/pkg/sql/rsg_test.go#L122)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Float64() is not NormFloat64().
> 
> > Float64 returns, as a float64, a pseudo-random number in [0.0,1.0).
> 
> > NormFloat64 returns a normally distributed float64 in the range [-math.MaxFloat64, +math.MaxFloat64] with standard normal distribution (mean = 0, stddev = 1).
> 
> But if you want a uniform random number in the range `[-math.MaxFloat64, +math.MaxFloat64]`, why not `(r.Float64() * 2 -1) * math.MaxFloat64`?
</details>
`r` is not a rand.Source, it's an RSG, which has its own implementation of Float64. However I've rethought this and improved it there, instead. The `* 2 - 1` solution generates mostly things in the e308 range, so it's not super useful. The solution in the other function generates a more reasonable distribution, along with NaN and Inf.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9995)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9995#-:-KU8chlu25gHFl2-NlvU:bnfp4nl)*

**Pull request merged**
