### PR TITLE
cli: show encryption flag.

### PR DESCRIPTION
**Pull request by mberhault**
Stop hidding the encryption flag, and improve the description slightly.

Release note (CLI change): Show --enterprise-encryption flag on start command

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm: modulo the html tags in the description.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/ccl/cliccl/cliflagsccl/flags.go, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26061#-LDJoou56IxYqccskf6Y:-LDJoou56IxYqccskf6Z:bxt9bfx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c2937baf62bb0037ba297a3b338eb84e46699e1/pkg/ccl/cliccl/cliflagsccl/flags.go#L18)):*
> ```Go
> 		Name: "enterprise-encryption",
> 		Description: `
> <PRE>
> ```

What is the `<PRE>` doing? I thought these descriptions were only output to the terminal.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26061#-:-LDJp8X26uYAJBIy7hfG:b-2ccqio)*

**Comment by mberhault** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ccl/cliccl/cliflagsccl/flags.go, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26061#-LDJoou56IxYqccskf6Y:-LDJrBdO8kSrj59iOKI3:b-cbf31i) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c2937baf62bb0037ba297a3b338eb84e46699e1/pkg/ccl/cliccl/cliflagsccl/flags.go#L18)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

What is the `<PRE>` doing? I thought these descriptions were only output to the terminal.
</blockquote></details>

Descriptions are wrapped by default, the `<PRE>` tag breaks wrapping: https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/cliflags/flags.go#L40

My guess is that at some point someone thought automatic (and consistent) wrapping was better than easy formatting.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26061)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ccl/cliccl/cliflagsccl/flags.go, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26061#-LDJoou56IxYqccskf6Y:-LDJunF43s1pe79bJsZF:bah4nyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c2937baf62bb0037ba297a3b338eb84e46699e1/pkg/ccl/cliccl/cliflagsccl/flags.go#L18)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

Descriptions are wrapped by default, the `<PRE>` tag breaks wrapping: https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/cliflags/flags.go#L40

My guess is that at some point someone thought automatic (and consistent) wrapping was better than easy formatting.
</blockquote></details>

Hmm, well that wasn't obvious. Ok. Carry on.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26061)*

**Pull request merged**
