### PR TITLE
sql: Avoid evaluating VALUES expressions during prepare.

### LINKED ISSUE #6225: sql: valuesNode executes on creation, failing if preparing with placeholders
I must be missing something because this seems like it would have been caught a while ago. Currently a statement like `INSERT INTO d.T VALUES ($1::INT)` in `TestPGPreparedQuery` will fail because immediately after TypeChecking the values clause during the pgwire prepare phase, it will attempt to [execute](https://github.com/cockroachdb/cockroach/blob/master/sql/values.go#L73) the values expression without the populated placeholder. Without populated placeholders, evaluation of expressions will cause errors/panics for just about anything other than a single placeholder by itself. 

@RaduBerinde @knz is this a recent regression? If not, maybe its time to give `valuesNode` the same treatment as #5903.

### PR DESCRIPTION
**Pull request by knz**
Spotted by @nvanbenschoten: prior to this patch VALUES would evaluate
its expressions during prepare, and thus fail (with either a crash or
an obscure error) if the expression contains a placeholder as argument
to a function.

Fixes #6225.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6242)

### CODE REVIEW

**Comment by knz** [comment]
This patch gets a failure on TestLogic for explain_debug:
```
--- FAIL: TestLogic (3.27s)
        logic_test.go:698: testdata/explain_debug:110: expected:
                "0"    "0"    "(1,"  "2,"   
                "3)"   "ROW"  "1"    "1"    
                "(4,"  "5,"   "6)"   "ROW"  
                but found:
                "0"    "0"    "(1,"  "2,"   
                "3)"   "ROW"  "1"    "1"    
                "(4,"  "5,"   "6)"   "ROW"  
                "2"    "2"    "(1,"  "2,"   
                "3)"   "ROW"  "3"    "3"    
                "(4,"  "5,"   "6)"   "ROW"  
```

Seems EXPLAIN(DEBUG) is now seeing the value rows two times. How come?

cc @RaduBerinde

**Comment by petermattis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[sql/values.go, line 33 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KFyshxko1dcvYdxz7CK:-KFyshxko1dcvYdxz7CL:164047152) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f016589af0f47a7e56960078ebc73332e48d01/sql/values.go#L33)):*
You can move the initialization of `v.rows` into `Start`. 

---

*[sql/values.go, line 50 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KFysm1-n__lTDvS-oWA:-KFysm1-n__lTDvS-oWB:-874580793) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f016589af0f47a7e56960078ebc73332e48d01/sql/values.go#L50)):*
`s/one/once/g`

---

*[sql/values.go, line 51 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KFysnNh3zpqd0vWBFhY:-KFysnNh3zpqd0vWBFhZ:-874580793) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f016589af0f47a7e56960078ebc73332e48d01/sql/values.go#L51)):*
`s/one/once/g`

---

*[sql/values.go, line 77 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KFyt3dxSK7y2aIjHY6X:-KFyt3dxSK7y2aIjHY6Y:322569626) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f016589af0f47a7e56960078ebc73332e48d01/sql/values.go#L77)):*
Somewhat odd to define a method on a type before the type itself. Perhaps `type valuesNode` declaration to the top of this file to follow the pattern used for `{delete,insert,update}Node`.

---

*[sql/values.go, line 83 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KFytM_aGhnel3jpLTOz:-KFytM_bPCquZaOw4vt3:1762284507) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f016589af0f47a7e56960078ebc73332e48d01/sql/values.go#L83)):*
This comment is confusing to me. Which node is coming from a SQL query? The `valuesNode`? That seems obvious, but perhaps I'm missing something.

---

*[sql/values.go, line 94 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KFyspyXBp45Pl5PsshR:-KFyspycrd6UpUK0pqBw:715460782) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f016589af0f47a7e56960078ebc73332e48d01/sql/values.go#L94)):*
`s/aobut/about/g`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242)*

**Comment by RaduBerinde** [comment]
^Looks like that statement is `EXPLAIN (DEBUG) VALUES (1, 2, 3), (4, 5, 6)`. Definitely shouldn't be seeing those twice.. My guess is that `Start` is being called twice which results us appending the rows twice. We should check that `n.rows` is nil and panic if not in that function. We should probably add safeguards like that in more of the Start functions.

---

Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[sql/values_test.go, line 115 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KFz3Ioi2wBp98ouL6Do:-KFz3Ioi2wBp98ouL6Dp:-1316053798) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f016589af0f47a7e56960078ebc73332e48d01/sql/values_test.go#L115)):*
`continue;` instead of else/is. the non-error path should be non-indented as much as possible (see https://github.com/golang/go/wiki/CodeReviewComments#indent-error-flow)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-:-KFz2IFBWzwsNugHYW_B:-728739436)*

**Comment by nvanbenschoten** [comment]
Thanks for fixing this @knz.

---

Review status: 0 of 3 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[sql/values.go, line 77 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KFyt3dxSK7y2aIjHY6X:-KFzSvq9DUQbmzltRXq1:5172523) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f016589af0f47a7e56960078ebc73332e48d01/sql/values.go#L77)):*
+1

---

*[sql/values.go, line 78 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KFzT0wI4LU8vuI2YSdo:-KFzT0wI4LU8vuI2YSdp:-570362687) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f016589af0f47a7e56960078ebc73332e48d01/sql/values.go#L78)):*
Is this check needed?

---

*[sql/values.go, line 93 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KFzTEiY0EQPITOzx26P:-KFzTEiY0EQPITOzx26Q:-35870214) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f016589af0f47a7e56960078ebc73332e48d01/sql/values.go#L93)):*
Double check this for me, but I believe all of these methods could be called directly on the `tuple` without looping over it's sub-expressions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-:-KFzTUQI9nvK08Js4ERK:1655477279)*

**Comment by petermattis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[sql/values.go, line 93 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KFzTEiY0EQPITOzx26P:-KFzhPXSErNH1FVQXSo5:-299670531) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f016589af0f47a7e56960078ebc73332e48d01/sql/values.go#L93)):*
Yes, though we don't want to call `Tuple.Eval` as we've batched allocated the datums for the evaluated expressions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242)*

**Comment by knz** [comment]
Review status: 0 of 8 files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

*[sql/values.go, line 33 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KFyshxko1dcvYdxz7CK:-KG0tuqNNxYerVH5dn2e:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f016589af0f47a7e56960078ebc73332e48d01/sql/values.go#L33)):*
Done.

---

*[sql/values.go, line 50 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KFysm1-n__lTDvS-oWA:-KG0tzsW01G5vHEjKkli:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f016589af0f47a7e56960078ebc73332e48d01/sql/values.go#L50)):*
Done.

---

*[sql/values.go, line 51 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KFysnNh3zpqd0vWBFhY:-KG0u-O11RdHkNC9lelL:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f016589af0f47a7e56960078ebc73332e48d01/sql/values.go#L51)):*
Done.

---

*[sql/values.go, line 77 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KFyt3dxSK7y2aIjHY6X:-KG0u6_3IWDD8a-Cz4eM:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f016589af0f47a7e56960078ebc73332e48d01/sql/values.go#L77)):*
Done.

---

*[sql/values.go, line 78 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KFzT0wI4LU8vuI2YSdo:-KG0unXRpUeEfFW1v7Q9:791886726) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f016589af0f47a7e56960078ebc73332e48d01/sql/values.go#L78)):*
Yes: sort.go and many others create valueNodes out of nothing just to store computed data. 

---

*[sql/values.go, line 83 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KFytM_aGhnel3jpLTOz:-KG0utH2pKswuvWW4yNj:-740967578) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f016589af0f47a7e56960078ebc73332e48d01/sql/values.go#L83)):*
sort.go and many others create valueNodes out of nothing just to store computed data. No need to evaluate expressions for them.

---

*[sql/values.go, line 93 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KFzTEiY0EQPITOzx26P:-KG0vhwjcYIfYK68fMoE:1030473858) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f016589af0f47a7e56960078ebc73332e48d01/sql/values.go#L93)):*
Indeed let's keep the batch alloc and call the individual evals.

---

*[sql/values.go, line 94 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KFyspyXBp45Pl5PsshR:-KG0vmoR8tWxvYT9KNrW:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f016589af0f47a7e56960078ebc73332e48d01/sql/values.go#L94)):*
Done.

---

*[sql/values_test.go, line 115 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KFz3Ioi2wBp98ouL6Do:-KG0vxb0RWm4Ca4yk9Oj:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f016589af0f47a7e56960078ebc73332e48d01/sql/values_test.go#L115)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 8 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[sql/explain.go, line 218 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KG2Q20t0rCYtxTGD8BQ:-KG2Q20t0rCYtxTGD8BR:317883366) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad9c77eb6f78084a711bac06936295cfade42a69/sql/explain.go#L218)):*
Does this need to come after `Start` or can we move it before? I would imagine some nodes might want to know the explain mode during `Start` (especially if we move there some of the one-time initialization code from various `Next` implementations)
Either way we should document this for `MarkDebug` in `planNode` (whether it runs before or after `Start`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242)*

**Comment by knz** [comment]
Review status: 0 of 8 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[sql/explain.go, line 218 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KG2Q20t0rCYtxTGD8BQ:-KG2ZYfAc7_fZFqvafx-:1444690040) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad9c77eb6f78084a711bac06936295cfade42a69/sql/explain.go#L218)):*
MarkDebug recurses into sub-nodes. However sub-nodes may not be determined before Start(). If we ant to make Start aware of the debug mode, we should add it as argument to Start(). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 8 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[sql/explain.go, line 218 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KG2Q20t0rCYtxTGD8BQ:-KG2k-4VPbBamIPgxgnx:-1424657499) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad9c77eb6f78084a711bac06936295cfade42a69/sql/explain.go#L218)):*
Understood - can you add this bit of info to the planNode interface? Just something like "Plan subnodes may not be fully determined until Start is run" as part of the comment for `Start`, and "MarkDebug can only be called between Start and the first call to Next" for `MarkDebug`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242)*

**Comment by knz** [comment]
Review status: 0 of 8 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[sql/explain.go, line 218 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KG2Q20t0rCYtxTGD8BQ:-KG6ENIJyavdGd8EHS_9:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad9c77eb6f78084a711bac06936295cfade42a69/sql/explain.go#L218)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242)*

**Comment by RaduBerinde** [comment]
Reviewed 1 of 3 files at r1, 7 of 7 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[sql/plan.go, line 461 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KG7B_4d1Url-Ug_zr3r:-KG7B_4d1Url-Ug_zr3s:1346264626) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb90f8b513ebfdc6e5ff3b1dfc030c2c757f7b79/sql/plan.go#L461)):*
This is saying the wrong thing, is it missing a "before? E.g. `but before the first call to Next()`

---

*[sql/values.go, line 83 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KFytM_aGhnel3jpLTOz:-KG7C5lWy3T0rjQx6aNL:450659865) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f016589af0f47a7e56960078ebc73332e48d01/sql/values.go#L83)):*
maybe just add "coming from a SQL query (as opposed to being internally created by another node)"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242)*

**Comment by knz** [comment]
Review status: 6 of 9 files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

*[sql/plan.go, line 461 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KG7B_4d1Url-Ug_zr3r:-KGEKxYqAruAiDqqUs6k:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb90f8b513ebfdc6e5ff3b1dfc030c2c757f7b79/sql/plan.go#L461)):*
Done.

---

*[sql/values.go, line 83 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-KFytM_aGhnel3jpLTOz:-KGELHylm06ch2PQAiwU:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f016589af0f47a7e56960078ebc73332e48d01/sql/values.go#L83)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242)*

**Comment by RaduBerinde** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242)*

**Comment by knz** [comment]
LGTY?

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6242#-:-KGHO_6v0vfH9hxLkZ2k:1417088721)*

**Pull request merged**
