### PR TITLE
colexec, colflow: add network latency stat to streams

### LINKED ISSUE #43859: sql: add latency info to EXPLAIN ANALYZE
The `EXPLAIN ANALYZE` output includes stall time for operators, but it does not include latency of the links connecting operators across nodes. It would be useful to include latency, especially to identify bottlenecks in geo-distributed clusters.

Another idea would be to include pairwise node latency separately from the `EXPLAIN ANALYZE` diagram, using node IDs that correspond to the IDs in the diagram. Locality info for the nodes would also be useful (if available).

This info will be helpful as we improve the optimizer to be aware of data distribution. It will also be helpful when debugging slow queries.

cc @awoods187

### LINKED ISSUE #54555: colexec: collect network statistics during query execution
When running EXPLAIN ANALYZE, a user does not currently have a way of seeing how much time was spent sending rows over the network.

### PR DESCRIPTION
**Pull request by cathymw**
This commit adds the information about network latency from an outbox to inbox
on EXPLAIN ANALYZE diagrams. 
To measure network latency, the inbox starts a stopwatch and sends a message to the outbox with a latency request. When the outbox responds to this message, the stopwatch is stopped. 

Closes: #54555 
Close: #43859

The following screenshot shows that EXPLAIN ANALYZE now shows network latency on streams:
image

Release note (sql change): EXPLAIN ANALYZE diagrams now contain "network latency"
information on streams.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
This is looking good, but I think the calculation is not quite right yet.

> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54769#-:-MIR2oOm5UpebqcHFKZH:blrducm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @cathymw)

___
*[pkg/sql/colexec/stats.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54769#-MIQuChi6fNK9q0zie15:-MIQuChi6fNK9q0zie16:b-qxku0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2f6ceaf5db9d1b1bd97191b19c68438cd69544/pkg/sql/colexec/stats.go#L89)):*
> ```Go
> 	// the diagram.
> 	// statsOnStream indicates whether network latency should be displayed
> 	// on the diagram
> ```

nit: missing period. Also, I think we could get rid off `statsOnStream` boolean and set `OnStream` below directly (i.e. `OnStream: networkReader != nil`) - the only reason for having separate `ioTime` is because it has more complicated logic.
___
*[pkg/sql/colexec/execpb/stats.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54769#-MIQvPTL3AAR7LErgXpg:-MIQvPTM6P8LaF358hPp:b-a4dvwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2f6ceaf5db9d1b1bd97191b19c68438cd69544/pkg/sql/colexec/execpb/stats.go#L40)):*
> ```Go
> func (vs *VectorizedStats) Stats() map[string]string {
> 	var timeSuffix string
> 	if vs.IO {
> ```

On the attached image we see that there is `IO time` shown on the stream which is confusing. That timing is actually of the inbox (which includes both the total network latency and the total time it took for the inbox to deserialize the batches from the network).

We should fix that - I think we should do the following for the inbox:
- hide `tuples output` stat (it is redundant on the inbox with `rowsRead`)
- rename `IO time` to `decoding time` or something like that, also only for the inbox (i.e. when `OnStream` is set)
- the value of time *ideally* would only include the deserializing part (i.e. we should subtract total network latency if possible) - this might be a bit more involved though.

Thoughts?
___
*[pkg/sql/colflow/colrpc/inbox.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54769#-MIQzj1uBwVO8gGlQts0:-MIQzj1uBwVO8gGlQts1:bfzqzb7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2f6ceaf5db9d1b1bd97191b19c68438cd69544/pkg/sql/colflow/colrpc/inbox.go#L112)):*
> ```Go
> 	bytesRead int64
> 
> 	latencyStopwatch *timeutil.StopWatch
> ```

This deserves a comment - what exactly this stopwatch measures.
___
*[pkg/sql/colflow/colrpc/inbox.go, line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54769#-MIR2SSX8aNUmbPNP8Sx:-MIR2SSX8aNUmbPNP8Sy:bdps4w4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2f6ceaf5db9d1b1bd97191b19c68438cd69544/pkg/sql/colflow/colrpc/inbox.go#L222)):*
> ```Go
> 	}
> 
> 	i.latencyStopwatch = timeutil.NewStopWatch()
> ```

nit: we should ask for the latency response only if the stats collection is enabled (otherwise, it is a bit pointless - we wouldn't show it anywhere).
___
*[pkg/sql/colflow/colrpc/outbox.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54769#-MIR-BBR80cwdDGyQ8E1:-MIR-BBR80cwdDGyQ8E2:bisuydo) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2f6ceaf5db9d1b1bd97191b19c68438cd69544/pkg/sql/colflow/colrpc/outbox.go#L71)):*
> ```Go
> 
> 	// latencyRequested is an atomic that represents whether Inbox
> 	// has sent a latency request to Outbox
> ```

nit: missing period. I'd also explicitly mention that it is non-zero when the latency message was requested.
___
*[pkg/sql/colflow/colrpc/outbox.go, line 269 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54769#-MIR1UIj-ydK7lvwk9fD:-MIR1UIj-ydK7lvwk9fE:bhggz91) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2f6ceaf5db9d1b1bd97191b19c68438cd69544/pkg/sql/colflow/colrpc/outbox.go#L269)):*
> ```Go
> 		o.scratch.msg.Data.RawBytes = o.scratch.buf.Bytes()
> 
> 		if atomic.CompareAndSwapUint32(&o.latencyRequested, 1, 0) {
> ```

Hm, as it is written currently, the outbox might stall for a while in `nextBatch` method above, so between the time `o.latencyRequested` is set to `1` and the outbox sending the next message pretty long time might pass, which would include the execution time of the whole chain of operators that is an input to the outbox.

I think we need to be more tricky here - one idea is that we might want to spawn a separate goroutine whose only job would be to check whether the latency response was requested, and if it has, sending the message onto the stream and then exiting (i.e. that listener/sender goroutine would only exit while the main outbox goroutine would keep on running). We would also spin up that extra goroutine only if the stats collection was requested (which we know at the plan time). @asubiotto might have other suggestions.
___
*[pkg/sql/execinfrapb/data.proto, line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54769#-MIR0T_Y5GSYQXoxXaz7:-MIR0T_Y5GSYQXoxXaz8:b-bvgwey) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2f6ceaf5db9d1b1bd97191b19c68438cd69544/pkg/sql/execinfrapb/data.proto#L227)):*
> ```protobuf
> }
> 
> // LatencyResponse is the msg an outbox sends an inbox when a LatencyRequest
> ```

nit: should do `s/msg/message/`, also `s/sends an/sends to an/`.
___
*[pkg/sql/execinfrapb/data.proto, line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54769#-MIR0hAJ0_ZCkNqGu9jH:-MIR0hAJ0_ZCkNqGu9jI:b-aq2jkp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2f6ceaf5db9d1b1bd97191b19c68438cd69544/pkg/sql/execinfrapb/data.proto#L247)):*
> ```protobuf
>   optional ProducerData data = 3 [(gogoproto.nullable) = false];
> 
>   optional LatencyResponse latency_response = 4;
> ```

I think I'd actually add `latency_response` as another option to `RemoteProducerMetadata` because to me it seems like the latency response is a type of metadata.

**Review by asubiotto — CHANGES_REQUESTED** [review]
Awesome work! I think this would also benefit from some unit tests to test some cases like an outbox blocked on next. Look at `colrpc_test`, you can probably reuse a mocked transport and assert that the inbox returns correct statistics in a bunch of cases (you could mock out the timer to reduce non-determinism).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54769#-:-MITIW1d45N7UAVv6koE:bmiuhet)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cathymw and @yuzefovich)

___
*[pkg/sql/colexec/stats.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54769#-MIT9NBtE6zAkQjnaBla:-MIT9NBtE6zAkQjnaBlb:bpse0gb) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2f6ceaf5db9d1b1bd97191b19c68438cd69544/pkg/sql/colexec/stats.go#L62)):*
> ```Go
> 	diskMonitors []*mon.BytesMonitor
> 
> 	networkReader NetworkReader
> ```

This struct seems like it's starting to get a bit overloaded with fields and behavior that occurs when these fields are not-nil. I think a better design would be to extract all the fields that are needed by all types of vectorized stats collectors into a `vectorizedStatsCollectorBase` and then have specialized stats collectors that embed this base. For example:

```
type vectorizedStatsCollectorBase struct {
    someStatsCollectedByEveryone int
}

func (b vectorizedStatsCollectorBase) getStats() map[string]string {
   return ...
}

type networkVectorizedStatsCollector struct {
    vectorizedStatsCollectorBase
    networkReader NetworkReader
}

func (n networkVectorizedStatsCollector) getStats() map[string]string {
    baseStats := n.vectorizedStatsCollectorBase.getStats()
    otherStats := n.networkReader.getNetworkLatency()
    return baseStats + otherStats
}
```

This avoids a bunch of confusing conditional logic, is easier to read, and simplifies the constructors a lot more (you don't need to pass in a bunch of `nil`s with comments about what you're not passing in). I don't mind if you do this refactor separately.
___
*[pkg/sql/colexec/execpb/stats.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54769#-MIQvPTL3AAR7LErgXpg:-MITD2JJ7W6PSLDiOKoy:b9ccnmg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2f6ceaf5db9d1b1bd97191b19c68438cd69544/pkg/sql/colexec/execpb/stats.go#L40)):*
I think this should be done with a separate implementation of the `SpanStats` interface called `VectorizedNetworkStats` or `InboxStats` that has fields of exactly what we want. `VectorizedStats` looks like it's overloaded with many different fields that are collected in different cases. Ideally we'd have base stats structs composed into stats so we can pick and choose what we need.

> the value of time ideally would only include the deserializing part (i.e. we should subtract total network latency if possible) - this might be a bit more involved though.

The thing is that it's very difficult to get total network latency (as we discussed, subtracting the inbox input runtime is not correct). I think we'd need to implement something similar to what we had with the two timers before we subtracted subtree time. i.e. start a timer when inbox returns from receiving from the GRPC stream, and stop it when it returns the batch and expose that somehow. I think forcing the inbox to collect its execution/serialization time is probably best. @cathymw this is a bit out of scope for this PR so it's fine to add it in another one.
___
*[pkg/sql/colexec/execpb/stats.proto, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54769#-MITFeos63gmc97ka1AZ:-MITFeos63gmc97ka1A_:b-fk89uj) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2f6ceaf5db9d1b1bd97191b19c68438cd69544/pkg/sql/colexec/execpb/stats.proto#L41)):*
> ```protobuf
>   // on_stream indicates whether the stats are shown on a stream. This decides
>   // if network latency should be shown or not.
>   bool on_stream = 10;
> ```

Based on what I said above, maybe it's better to create a new `message VectorizedInboxStats {` or something similar. This message looks like it's already overloaded.
___
*[pkg/sql/colflow/colrpc/inbox.go, line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54769#-MIR2SSX8aNUmbPNP8Sx:-MITFqRxBJRN1QuwItuA:blgjh36) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2f6ceaf5db9d1b1bd97191b19c68438cd69544/pkg/sql/colflow/colrpc/inbox.go#L222)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: we should ask for the latency response only if the stats collection is enabled (otherwise, it is a bit pointless - we wouldn't show it anywhere).
</blockquote></details>

We'll want to show this in `SHOW QUERIES` in the future (because the collection time doesn't impact performance negatively compared to a network hop) so I think it's fine to leave it as it is.
___
*[pkg/sql/colflow/colrpc/inbox.go, line 223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54769#-MITG00Z-RxY4_9E3GFw:-MITG00Z-RxY4_9E3GFx:bpay3gt) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2f6ceaf5db9d1b1bd97191b19c68438cd69544/pkg/sql/colflow/colrpc/inbox.go#L223)):*
> ```Go
> 
> 	i.latencyStopwatch = timeutil.NewStopWatch()
> 	i.latencyStopwatch.Start()
> ```

Maybe only start this stopwatch on a successful send of the message.
___
*[pkg/sql/colflow/colrpc/inbox.go, line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54769#-MITGpogE4DqJHc8T2HI:-MITGpogE4DqJHc8T2HJ:b-js1686) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2f6ceaf5db9d1b1bd97191b19c68438cd69544/pkg/sql/colflow/colrpc/inbox.go#L224)):*
> ```Go
> 	i.latencyStopwatch = timeutil.NewStopWatch()
> 	i.latencyStopwatch.Start()
> 	if err := i.stream.Send(&execinfrapb.ConsumerSignal{LatencyRequest: &execinfrapb.LatencyRequest{}}); err != nil {
> ```

Out of scope for this PR, but I think something that could be really powerful is seeing how network latency does over time. This is variable because we're not really measuring "network" latency here, it's more like "grpc" latency which depends on a lot of other factors (e.g. how much other traffic is sent on the stream). So it'd be interesting to see if there's a grpc latency slowdown over time. This could probably be done in `Next` using a 
___
*[pkg/sql/colflow/colrpc/inbox.go, line 300 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54769#-MITHDCpAMlm3un0FXf8:-MITHDCpAMlm3un0FXf9:b2of9n4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2f6ceaf5db9d1b1bd97191b19c68438cd69544/pkg/sql/colflow/colrpc/inbox.go#L300)):*
> ```Go
> 			colexecerror.ExpectedError(err)
> 		}
> 		if m.LatencyResponse != nil {
> ```

What happens if we never get a `LatencyResponse`?
___
*[pkg/sql/colflow/colrpc/inbox.go, line 301 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54769#-MITGBbF4O0NLdYQm7NF:-MITGBbF4O0NLdYQm7NG:bhce8xp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2f6ceaf5db9d1b1bd97191b19c68438cd69544/pkg/sql/colflow/colrpc/inbox.go#L301)):*
> ```Go
> 		}
> 		if m.LatencyResponse != nil {
> 			i.latencyStopwatch.Stop()
> ```

The issue with this is that someone needs to call `Next` to receive from this stream so we might inadvertently include that delay in our network latency calculation. An example of this is if we're the left side of a hash join, the join reads the right side completely before it requests the left side for any rows. Maybe a better way to do this would be to start the stop watch and send the message in `init` which does one-time "initialization" of the stream.
___
*[pkg/sql/colflow/colrpc/outbox.go, line 269 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54769#-MIR1UIj-ydK7lvwk9fD:-MITHm5L8G4hcKUaZySp:biv1xu0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2f6ceaf5db9d1b1bd97191b19c68438cd69544/pkg/sql/colflow/colrpc/outbox.go#L269)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Hm, as it is written currently, the outbox might stall for a while in `nextBatch` method above, so between the time `o.latencyRequested` is set to `1` and the outbox sending the next message pretty long time might pass, which would include the execution time of the whole chain of operators that is an input to the outbox.

I think we need to be more tricky here - one idea is that we might want to spawn a separate goroutine whose only job would be to check whether the latency response was requested, and if it has, sending the message onto the stream and then exiting (i.e. that listener/sender goroutine would only exit while the main outbox goroutine would keep on running). We would also spin up that extra goroutine only if the stats collection was requested (which we know at the plan time). @asubiotto might have other suggestions.
</blockquote></details>

This is an interesting dilemma. It's not valid to call `Send` concurrently from two goroutines. What I would suggest is to add a field to the `LatencyResponse`. The outbox would start a stopwatch when it gets a latency request and stop it when it's about to send a response. This duration could then be subtracted from what the inbox recorded.
___
*[pkg/sql/execinfrapb/data.proto, line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54769#-MIR0hAJ0_ZCkNqGu9jH:-MITHWut7a749c-Im9r3:b-nvoedi) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2f6ceaf5db9d1b1bd97191b19c68438cd69544/pkg/sql/execinfrapb/data.proto#L247)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think I'd actually add `latency_response` as another option to `RemoteProducerMetadata` because to me it seems like the latency response is a type of metadata.
</blockquote></details>

I disagree with this because `RemoteProducerMetadata` is trying to get back to the gateway, but this is specific to a single network link, so once it's read by the inbox, it's useless.

**Comment by asubiotto** [comment]
Also, minor nit on the PR title: we don't use carats to specify multiple packages so it can just be: `colexec, colflow: add network latency stat to streams`

**Comment by cathymw** [comment]
Closed in favour of #55705. Starting a fresh PR since the approach changed and most of the feedback is no longer applicable.

**Pull request closed without merging**
