### PR TITLE
roachtest: disable some index schemachange tests 

### LINKED ISSUE #32820: roachtest: schemachange/index/tpcc-100 failed
SHA: https://github.com/cockroachdb/cockroach/commits/e6cb0c5c329617b560eee37527248171b5e06382

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=schemachange/index/tpcc-100 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1038478&tab=buildLog

```
The test failed on master:
	test.go:1025: test timed out (20m0s)
	test.go:630,cluster.go:1141,tpcc.go:111,cluster.go:1467,errgroup.go:58: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1038478-schemachange-index-tpcc-100:5 -- ./workload run tpcc --warehouses=100 --histograms=logs/stats.json --wait=false --tolerate-errors --ramp=5m0s --duration=10m0s {pgurl:1-4} returned:
		stderr:
		
		stdout:
		l
		_elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
		   8m49s        2            5.0           10.1    201.3    570.4    570.4    570.4 delivery
		   8m49s        2          107.0          101.4    302.0    906.0  98784.2 103079.2 newOrder
		   8m49s        2           10.0           10.2     54.5    192.9    192.9    192.9 orderStatus
		   8m49s        2          113.0          100.5    243.3    771.8   1140.9 103079.2 payment
		   8m49s        2           18.0           10.1     35.7    570.4   7516.2   7516.2 stockLevel
		   8m50s        2           16.0           10.2    369.1    520.1    604.0    604.0 delivery
		   8m50s        2          111.0          101.4    352.3    704.6  60129.5  62277.0 newOrder
		   8m50s        2           12.0           10.2     22.0     71.3    100.7    100.7 orderStatus
		   8m50s        2           96.0          100.5    260.0    604.0    838.9   1275.1 payment
		   8m50s        2           14.0           10.2     35.7    113.2    352.3    352.3 stockLevel
		: signal: killed
	test.go:630,schemachange.go:329,schemachange.go:309,cluster.go:1467,errgroup.go:58: pq: server is not accepting clients
	test.go:630,cluster.go:1488,tpcc.go:121,schemachange.go:305: Goexit() was called

```

### PR DESCRIPTION
**Pull request by vivekmenezes**
The tests are failing only because they need more time to run.

fixes #32820

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
Did schema changes get slower and are now hitting the timeout or was the timeout just not chosen well in the first place?

**Comment by vivekmenezes** [comment]
we recently added two more schema changes to this test and I do see progress being made on the test runs. Definitely worth increasing the timeout for now.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33061)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/schemachange.go, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33061#-LTcHv5DA2NvkijWs6lq:-LTcHv5DA2NvkijWs6lr:bbwe4g) ([raw file](https://github.com/cockroachdb/cockroach/blob/048dac112c05716308dff10a78f88b51447e2c42/pkg/cmd/roachtest/schemachange.go#L303)):*
> ```Go
> 		Name:    fmt.Sprintf("schemachange/index/tpcc-%d", warehouses),
> 		Nodes:   nodes(numNodes),
> 		Timeout: length * 4,
> ```

Should you be changing the caller instead? The `length` parameter controls both the timeout as well as the duration to run tpcc.

**Review by vivekmenezes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33061)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/schemachange.go, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33061#-LTcHv5DA2NvkijWs6lq:-LTj13R3BPPgKDRButiG:b-gpnrck) ([raw file](https://github.com/cockroachdb/cockroach/blob/048dac112c05716308dff10a78f88b51447e2c42/pkg/cmd/roachtest/schemachange.go#L303)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Should you be changing the caller instead? The `length` parameter controls both the timeout as well as the duration to run tpcc. 
</blockquote></details>

Makes sense. I've changed the timeout multiple to 3/2 and changed the callers to provide larger tpcc run times.

**Comment by vivekmenezes** [comment]
@dt I've changed this test to only run a single ADD INDEX because the current performance is bad. Let's reenable the other two tests once you've improved the performance.

**Review by dt — APPROVED** [review]

**Pull request merged**
