### PR TITLE
storage: use write only batch for log entry deletions

### LINKED ISSUE #17809: storage: raft log truncation should use a batch
Noticed while inspect WAL entries: raft log truncation is being performed an entry at a time. See https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/replica_proposal.go#L787-L799:

```
// Truncate the Raft log.
start := engine.MakeMVCCMetadataKey(keys.RaftLogKey(r.RangeID, 0))
end := engine.MakeMVCCMetadataKey(
	keys.RaftLogKey(r.RangeID, newTruncState.Index).PrefixEnd(),
)
iter := r.store.engine.NewIterator(false /* !prefix */)
// Clear the log entries. Intentionally don't use range deletion
// tombstones (ClearRange()) due to performance concerns connected
// to having many range deletion tombstones. There is a chance that
// ClearRange will perform well here because the tombstones could be
// "collapsed", but it is hardly worth the risk at this point.
err := r.store.engine.ClearIterRange(iter, start, end)
iter.Close()
```

Creating a write-only batch will minimize Cgo transitions and be faster at the RocksDB level as well.

### PR DESCRIPTION
**Pull request by irfansharif**
Fixes #17809.

While inspecting WAL entries it was noticed that raft log entry
deletions (post-truncation) was being performed an entry at a time.

Using a write-only batch will be faster at the RocksDB level. We also
potentially minimize Cgo transitions as deletions can be batched with
other RocksDB write batches (during command application).

+cc @petermattis.

### CODE REVIEW

**Comment by irfansharif** [comment]
From #17809:
>  raft log truncation is being performed an entry at a time

Isn't this a property of using `ClearIterRange`? From `db.cc`:
```Cpp
DBStatus DBDeleteIterRange(DBEngine* db, DBIterator *iter, DBKey start, DBKey end) {
  rocksdb::Iterator *const iter_rep = iter->rep.get();
  iter_rep->Seek(EncodeKey(start));
  const std::string end_key = EncodeKey(end);
  for (; iter_rep->Valid() && kComparator.Compare(iter_rep->key(), end_key) < 0;
       iter_rep->Next()) {
    DBStatus status = db->Delete(ToDBKey(iter_rep->key()));
    if (status.data != NULL) {
      return status;
    }
  }
  return kSuccess;
}
```

To avoid this we'd ideally use `ClearRange` which comes with the downsides of range deletion tombstones.

**Comment by irfansharif** [comment]
As an aside from https://github.com/facebook/rocksdb/wiki/Delete-A-Range-Of-Keys

> if you never overwrite existing keys, you can try to use DB::SingleDelete() instead of Delete() to kill tombstones sooner. Tombstones will be dropped after it meets the original keys, rather than compacted to the last level.

This is applicable here, I think, can't think of when we'd re-write to the same raft log entry keys. (Though I'm not too familiar with the intricacies of reusing replica IDs and whether or not this is currently possible.)

**Comment by petermattis** [comment]
:lgtm:

> To avoid this we'd ideally use ClearRange which comes with the downsides of range deletion tombstones.

My point about entry at a time deletion was about RocksDB WAL entry at a time. `ClearIterRange` still performs individual deletes for each key, but your change now means we'll bundle these all into a single batch.

> This is applicable here, I think, can't think of when we'd re-write to the same raft log entry keys. 

Raft sometimes tells us to drop a suffix of the Raft log and then overwrite those entries.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17818#-:-KsACXDCT2YwfVemr4SM:bu5gog8)*

**Comment by irfansharif** [comment]
> My point about entry at a time deletion was about RocksDB WAL entry at a time

I see, makes sense.

> Raft sometimes tells us to drop a suffix of the Raft log and then overwrite those entries.

I should have been more clear here, I was talking about the use of `SingleDelete` only during log truncations. To my knowledge the overwriting of truncated entries should not happen.

**Comment by tschottdorf** [comment]
> I should have been more clear here, I was talking about the use of SingleDelete only during log truncations. To my knowledge the overwriting of truncated entries should not happen.

SingleDelete is undefined when the key you've deleted has been written more than once. You can't guarantee that for any Raft log key (at least now), so SingleDelete doesn't apply there.

**Comment by irfansharif** [comment]
oh, misread it to being deleted keys not being written to thereon forth. Thanks for clarifying!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17818#-:-KsAF2m1UixXEESVBwV3:b-30hbui)*

**Pull request merged**
