### PR TITLE
authors: add hand to authors

### PR DESCRIPTION
**Pull request by hand-crdb**
Added myself to the AUTHORS file per the "Your First Commit" MOLTing doc
Release note: None

### CODE REVIEW

**Comment by kenliu** [comment]
Hi @hand-crdb can you change the format of the emails to be in the form `hand@cockroachlabs.com`?

**Comment by hand-crdb** [comment]
> Hi @hand-crdb can you change the format of the emails to be in the form `hand@cockroachlabs.com`?

Thanks for the feedback and I'm happy to do so.  But for my clarification, does this comment at the top of the file not apply to me?

```
# If you wish to keep your @cockroachlabs.com address hidden,
# please still list <@cockroachlabs.com> (with no user name)
# in the list of aliases.
```

**Comment by kenliu** [comment]
oh sorry, I didn't know that was an option here. LGTM.

**Pull request merged**
