### PR TITLE
storage: fix data race

### LINKED ISSUE #8381: storage: datarace on r.mu.state.Desc
```
make stressrace PKG=./server TESTS=TestAdminAPITableStats
```
fails quickly with either one of a couple of races on the `r.mu.state.Desc `, for example the one below.

@tamird I think you've recently done some refactoring on how the replica desc is accessed? Please route fwd.

```
==================
WARNING: DATA RACE
Write at 0x00c420485058 by goroutine 59:
  github.com/cockroachdb/cockroach/storage.(*Replica).setDescWithoutProcessUpdateLocked()
      /Users/andrei/work/src/github.com/cockroachdb/cockroach/storage/replica.go:752 +0xb7
  github.com/cockroachdb/cockroach/storage.(*Replica).setDescWithoutProcessUpdate()
      /Users/andrei/work/src/github.com/cockroachdb/cockroach/storage/replica.go:737 +0x85
  github.com/cockroachdb/cockroach/storage.(*Replica).setDesc()
      /Users/andrei/work/src/github.com/cockroachdb/cockroach/storage/replica.go:724 +0x46
  github.com/cockroachdb/cockroach/storage.(*Replica).handleTrigger()
      /Users/andrei/work/src/github.com/cockroachdb/cockroach/storage/replica_trigger.go:418 +0xfc5
  github.com/cockroachdb/cockroach/storage.(*Replica).processRaftCommand()
      /Users/andrei/work/src/github.com/cockroachdb/cockroach/storage/replica.go:2027 +0x874
  github.com/cockroachdb/cockroach/storage.(*Replica).handleRaftReady()
      /Users/andrei/work/src/github.com/cockroachdb/cockroach/storage/replica.go:1653 +0xb3a
  github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1.1()
      /Users/andrei/work/src/github.com/cockroachdb/cockroach/storage/store.go:2558 +0x8e

Previous read at 0x00c420485058 by goroutine 209:
  github.com/cockroachdb/cockroach/storage.(*Replica).SnapshotWithContext.func1()
      /Users/andrei/work/src/github.com/cockroachdb/cockroach/storage/replica_raftstorage.go:315 +0x422
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunAsyncTask.func1()
      /Users/andrei/work/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:231 +0xa2

Goroutine 59 (running) created at:
  github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
      /Users/andrei/work/src/github.com/cockroachdb/cockroach/storage/store.go:2561 +0x40e
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /Users/andrei/work/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x8a

Goroutine 209 (running) created at:
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunAsyncTask()
      /Users/andrei/work/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:232 +0xc9
  github.com/cockroachdb/cockroach/storage.(*Replica).SnapshotWithContext()
      /Users/andrei/work/src/github.com/cockroachdb/cockroach/storage/replica_raftstorage.go:331 +0x5d8
  github.com/cockroachdb/cockroach/storage.(*Replica).GetSnapshot()
      /Users/andrei/work/src/github.com/cockroachdb/cockroach/storage/replica_raftstorage.go:363 +0x30d
  github.com/cockroachdb/cockroach/storage.(*Replica).ChangeReplicas()
      /Users/andrei/work/src/github.com/cockroachdb/cockroach/storage/replica_command.go:2960 +0x7e8
  github.com/cockroachdb/cockroach/storage.(*replicateQueue).process()
      /Users/andrei/work/src/github.com/cockroachdb/cockroach/storage/replicate_queue.go:153 +0x128b
  github.com/cockroachdb/cockroach/storage.(*baseQueue).processReplica()
      /Users/andrei/work/src/github.com/cockroachdb/cockroach/storage/queue.go:480 +0x726
  github.com/cockroachdb/cockroach/storage.(*baseQueue).maybeAddToPurgatory.func1.1()
      /Users/andrei/work/src/github.com/cockroachdb/cockroach/storage/queue.go:545 +0x6f
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunTask()
      /Users/andrei/work/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:215 +0x10d
  github.com/cockroachdb/cockroach/storage.(*baseQueue).maybeAddToPurgatory.func1()
      /Users/andrei/work/src/github.com/cockroachdb/cockroach/storage/queue.go:548 +0x64c
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /Users/andrei/work/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x8a
==================
```

### PR DESCRIPTION
**Pull request by tamird**
Closes #8381.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8387)

### CODE REVIEW

**Comment by petermattis** [comment]
LGTM

**Comment by bdarnell** [comment]
:lgtm:

Surprising that the bug has existed without being detected for so long.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8387#-:-KOfyA-lf-ipKb9tszIJ:brd2fbj)*

**Comment by tamird** [comment]
Even more surprising that this seems to cause test failures.

**Comment by tamird** [comment]
Also discovered a deadlock (which we've never hit?) while I was here.

**Pull request merged**
