### PR TITLE
sql: support ARRAY(subquery) constructor syntax

### LINKED ISSUE #10763: sql: implement flattening of a data source or subquery to an array
From https://github.com/cockroachdb/cockroach/issues/5582#issuecomment-261254147:

The syntax `ARRAY (subquery ....)` is an array constructor, which transforms the set of values produced by the subquery into a single array datum.

This is the opposite operation to `unnest`, and is an extension to the array literal syntax introduced by #10585 .

### PR DESCRIPTION
**Pull request by jordanlewis**
This commit adds support for array constructors that use the results of a single-column, multi-row subquery to populate the array.

See https://www.postgresql.org/docs/9.1/static/sql-expressions.html#SQL-SYNTAX-ARRAY-CONSTRUCTORS for more details on this syntax.

Resolves #10763.
Updates #5582.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/11766)

### CODE REVIEW

**Comment by knz** [comment]
Excellent work.
I think the code will be simpler/cleaner if you split the Expr nodes though. 

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/parser/eval.go, line 2353 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11766#-KXwemkTCDARqqMXgtYU:-KXwemkU4KqI3Y1oNeY1:b-xxtszd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0af85caf4d459d401c3ddaddebb883d3219108a/pkg/sql/parser/eval.go#L2353)):*
> ```Go
> 		}
> 	} else {
> 		d, err := t.Subquery.(TypedExpr).Eval(ctx)
> ```

Is this eval call necessary? I though that the walk code was depth-first so you only arrive here after the arguments have been evaluated/substituted already.

---

*[pkg/sql/parser/expr.go, line 605 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11766#-KXwf-v5btw4Q-ICtCG9:-KXwf-v6YvlozoNiygRf:b-4gfkg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0af85caf4d459d401c3ddaddebb883d3219108a/pkg/sql/parser/expr.go#L605)):*
> ```Go
> }
> 
> // Array represents an array constructor.
> ```

Can we split this node in two. They are really two different concepts: Array and Flatten :)

---

*[pkg/sql/parser/sql.y, line 3826 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11766#-KXwfDwk6NrIGyIFzQjs:-KXwfDwla-InifAts3dg:bhh7ril) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0af85caf4d459d401c3ddaddebb883d3219108a/pkg/sql/parser/sql.y#L3826)):*
> ```Yacc
>   }
> | ARRAY select_with_parens
>   // $$.val = &FlattenExpr{Subquery: &Subquery{Select: $2.selectStmt()}}
> ```

I like "Flatten" more :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11766#-:-KXwfOz9cr_g_jNwuxkY:byzxh7d)*

**Comment by jordanlewis** [comment]
Thanks for the prompt review! I agree - I'll try that now.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/parser/eval.go, line 2353 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11766#-KXwemkTCDARqqMXgtYU:-KXwgUq0ZNqUyLAXGGMU:b-6pa1om) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0af85caf4d459d401c3ddaddebb883d3219108a/pkg/sql/parser/eval.go#L2353)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Is this eval call necessary? I though that the walk code was depth-first so you only arrive here after the arguments have been evaluated/substituted already.
</blockquote></details>

I believe this `Eval` is really a no-op that just returns the result of the subquery, after the `Subquery` node has been replaced with a `subquery`. See `subquery.go:101-108`.

---

*[pkg/sql/parser/expr.go, line 605 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11766#-KXwf-v5btw4Q-ICtCG9:-KXwgJ3xsSaJPBuRu24C:bhy9ost) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0af85caf4d459d401c3ddaddebb883d3219108a/pkg/sql/parser/expr.go#L605)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can we split this node in two. They are really two different concepts: Array and Flatten :)
</blockquote></details>

Will do!

---

*[pkg/sql/parser/sql.y, line 3826 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11766#-KXwfDwk6NrIGyIFzQjs:-KXwgCMfd83sxQjslFR4:bykfd72) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0af85caf4d459d401c3ddaddebb883d3219108a/pkg/sql/parser/sql.y#L3826)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I like "Flatten" more :)
</blockquote></details>

Hah, I thought I killed this completely! I will resurrect it now that it's clearer to me what needs to be done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11766#-:-KXwh1103JAa_zLii3ML:bi7j55v)*

**Comment by jordanlewis** [comment]
Updated to split out the subquery constructor syntax into its own `Expr` node, `ArrayFlatten`. PTAL.

**Comment by knz** [comment]
Yes, this looks great! Just a minor suggestion left

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/eval.go, line 2378 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11766#-KYDpcXdYINzAwkD2qFU:-KYDpcXdYINzAwkD2qFV:b-robucm) ([raw file](https://github.com/cockroachdb/cockroach/blob/535fb832dd64f6ed50d2612274e14c21ca42a069/pkg/sql/parser/eval.go#L2378)):*
> ```Go
> 		return nil, errors.Errorf("array subquery result (%v) is not DTuple", d)
> 	}
> 	for _, v := range *tuple {
> ```

I think this entire loop can be replaced with a single `array.Array = []Datum(tuple)`. Let's avoid duplicating the tuple array in memory.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11766#-:-KYDpx_ojI6EqwrytYfb:b9vk81l)*

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/eval.go, line 2378 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11766#-KYDpcXdYINzAwkD2qFU:-KYEcpiAos3DBY3vq4GM:b-4k0685) ([raw file](https://github.com/cockroachdb/cockroach/blob/535fb832dd64f6ed50d2612274e14c21ca42a069/pkg/sql/parser/eval.go#L2378)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think this entire loop can be replaced with a single `array.Array = []Datum(tuple)`. Let's avoid duplicating the tuple array in memory.
</blockquote></details>

Good point! Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11766)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/parser/eval.go, line 2378 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11766#-KYDpcXdYINzAwkD2qFU:-KYEeL6vD8mJlJ4wr19t:bb6mt9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/535fb832dd64f6ed50d2612274e14c21ca42a069/pkg/sql/parser/eval.go#L2378)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Good point! Done.
</blockquote></details>

:+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11766#-:-KYEeQreG2b85DPNB2B0:bnfp4nl)*

**Comment by jordanlewis** [comment]
TFTRs!

**Pull request merged**
