### PR TITLE
sql: clean up SCRUB INDEX query, issue via the internal executor

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: clean up SCRUB INDEX query

The scrub index query does a very hacky thing - it forces a merge join
and then goes through the plan and tweaks the merge joiners to convert
equality to "special" equality where NULL equals NULL (aka
`IS NOT DISTINCT FROM`).

This was done because the equality conditions that allow NULLs to
equal NULLs weren't able to be used as equality columns in hash or
merge joins (resulting in a quadratic join).

This change rewrites the query and removes this hack. The main
simplification comes from the fact that the primary columns are never
NULL and we can use regular equality for them. For the other columns,
we can use `IS NOT DISTINCT FROM` because we don't need them to be
hash/merge equality columns (the "groups" already contain a single row
because the PK is unique).

Other improvements: we now select the table by ID, and we only check
an arbitrary PK column on each side for NULLness.

Release note: None

#### sql: use the internal executor for scrub index query

Switch the scrub index check query to use the internal executor.

This was the last user of `delegateQuery`, so we remove that as well.

Release note: None

### CODE REVIEW

**Review by thoszhang — APPROVED** [review]
Nice! I think this should fix #35160. I can open a follow-up PR to get rid of the workaround in https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/schema_changer_test.go#L535-L538.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39267#-:-LlIkmEbEl8oT8WmSRX_:b-jvlg2l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @lucy-zhang, and @RaduBerinde)

___
*[pkg/sql/scrub.go, line 344 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39267#-LlIg849DFBUSO89N-EN:-LlIg84AAy7gJPgjO4LU:b-et57jp) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd38e2d2eac81c5de597fc0c93fdb07036219a72/pkg/sql/scrub.go#L344)):*
> ```Go
> //   []string{"a = x", "b = y"}.
> func pairwiseOp(left []string, right []string, op string) []string {
> 	res := make([]string, len(left))
> ```

Should we panic if these slices have different lengths, like before?
___
*[pkg/sql/scrub_index.go, line 130 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39267#-LlIiOrH8ICPpx_hwJSr:-LlIiOrH8ICPpx_hwJSs:b-c4hqmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd38e2d2eac81c5de597fc0c93fdb07036219a72/pkg/sql/scrub_index.go#L130)):*
> ```Go
> 
> 	// Because the row results include both primary key data and secondary
> 	// key data, the row results will contain two copies of the column
> ```

`secondary index`?

**Review by RaduBerinde — COMMENTED** [review]
TFTR! I added a commit to remove that workaround, figured might as well do it in the same PR. Running `TestRaceWithBackfill` under stress, so far so good.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39267#-:-LlIp0of9wtrH0sxOQIh:b6g3c8u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @lucy-zhang)

___
*[pkg/sql/scrub.go, line 344 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39267#-LlIg849DFBUSO89N-EN:-LlIo5qCAUu8JFYIHzBe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd38e2d2eac81c5de597fc0c93fdb07036219a72/pkg/sql/scrub.go#L344)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Should we panic if these slices have different lengths, like before?
</blockquote></details>

Done.
___
*[pkg/sql/scrub_index.go, line 130 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39267#-LlIiOrH8ICPpx_hwJSr:-LlIoLhU0sK9EGc7vPyf:b4yfi42) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd38e2d2eac81c5de597fc0c93fdb07036219a72/pkg/sql/scrub_index.go#L130)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

`secondary index`?
</blockquote></details>

I removed this block altogether, we don't need the types after the second commit.

**Review by thoszhang — APPROVED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39267#-:-LlJ-hFZ45EtgXEVI11T:b-ucfknh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @lucy-zhang)

**Pull request merged**
