### PR TITLE
cli/zip: avoid quadratic behavior in SQL schema retrieval

### LINKED ISSUE #67515: cli: debug.zip collection of table schema is too slow
I saw a user collecting a debug.zip using a 21.1.5 client binary (against a 20.2 cluster). It looked to me like the collection of table schemas was very slow. It looked like we were collecting one table at a time and each table was taking a few seconds. Across many tables, this was painful. Does this sounds right? Can we parallelize some?

### PR DESCRIPTION
**Pull request by knz**
Fixes #67515.

Prior to this patch, the `debug zip` command would issue a
`DatabaseDetails` request over the network for each database in turn,
and also `TableDetails` for each table.

Server-side, each of these individual requests would cause all
descriptors to be loaded into memory first.

The overall behavior was thus quadratic in performance, and was
resulting in unacceptable delays on large clusters with thousands of
descriptors.

It turns out, none of this is necessary since we already collect the
descriptor details via `system.descriptors` and can collect the CREATE
statements trivially using the `crdb_internal.create_statements`
vtable, which also has linear performance.

Release note (cli change): `cockroach debug zip` no longer retrieves
database and table details into separate files. The schema information
is collected by means of `system.descriptors` and `crdb_internal.create_statements`.

### CODE REVIEW

**Comment by knz** [comment]
planning to backport this

**Review by ajwerner — COMMENTED** [review]
:lgtm_strong: thanks for doing it!

> Reviewed 2 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68284#-:-MfsQ2Ji6F1chkWBeuJ6:bh986wi)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/cli/zip_cluster_wide.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68284#-MfsPS8qESVJ0u2M7Ue7:-MfsPS8qESVJ0u2M7Ue8:b9hv62d) ([raw file](https://github.com/cockroachdb/cockroach/blob/145356d9da819b48d6f5c1eeb223ef0c78df105f/pkg/cli/zip_cluster_wide.go#L88)):*
> ```Go
> 	"system.scheduled_jobs",
> 
> 	// the synthetic SQL CREATE statements for all tables.
> ```

nit: capitalize `The`
___
*[pkg/cli/testdata/zip/unavailable, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68284#-MfsPued5KGL-ye9ZTb7:-MfsPued5KGL-ye9ZTb8:b-s47otc) ([raw file](https://github.com/cockroachdb/cockroach/blob/145356d9da819b48d6f5c1eeb223ef0c78df105f/pkg/cli/testdata/zip/unavailable#L117)):*
> ```
> [node 1] 40 ranges found
> [node 1] writing range 1... converting to JSON... writing binary output: debug/nodes/1/ranges/1.json... done
> ```
How did this test not fail on master? I don't anticipate that this change is the one changing the range count.

**Comment by knz** [comment]
> How did this test not fail on master? I don't anticipate that this change is the one changing the range count.

This test is currently skipped. I un-skipped it to regenerate the reference output, but that picked up a couple of other changes that had been needed while the test was skipped.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68284)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/cli/zip_cluster_wide.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68284#-MfsPS8qESVJ0u2M7Ue7:-MfszloM5OTAr-X3eK6K:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/145356d9da819b48d6f5c1eeb223ef0c78df105f/pkg/cli/zip_cluster_wide.go#L88)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: capitalize `The`
</blockquote></details>

Done.

**Comment by knz** [comment]
tfyr!

bors r=ajwerner

**Comment by knz** [comment]
bors r=ajwerner

**Comment by knz** [comment]
bors r=ajwerner

**Pull request merged**
