### PR TITLE
sql/parser: Support ANY/SOME/ALL array operators

### LINKED ISSUE #10519: sql: add support for ARRAY operators and functions
Subissue of #2115.
See:
- https://www.postgresql.org/docs/9.6/static/functions-array.html 
- https://www.postgresql.org/docs/9.6/static/functions-comparisons.html

We currently have basic support for ARRAYs at the SQL interpreter level, but we do not support operators or functions acting on these arrays. 

The only operator needed immediately for Hibernate is `ANY` and the only function needed is `array_upper`.

### PR DESCRIPTION
**Pull request by nvb**
Closes #10519.

This change adds support for the `ANY`, `SOME`, and `ALL` array
operators, which are needed for Hibernate support. See
https://www.postgresql.org/docs/9.6/static/functions-comparisons.html
for details.

This is a WIP because I think some of the type checking code can be
cleaned up before merging.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12102)

### CODE REVIEW

**Comment by jordanlewis** [comment]
Nice! I wonder if this could become cleaner by adding a new type for the quantifier operators. See comments below.

---

Review status: 0 of 12 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/eval.go, line 1447 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12102#-KYKaSAk31mrArf9IdHh:-KYKaSAk20IcTPdbM_sk:bssdfou) ([raw file](https://github.com/cockroachdb/cockroach/blob/943a5e57c798158cf9f02f4cee0b7c04bcf79066/pkg/sql/parser/eval.go#L1447)):*
> ```Go
> }
> 
> func evalArrayCmp(
> ```

I think a brief header comment on this function could be really helpful, e.g. `evalArrayCmp evaluates the comparison in the scope of subOp (or quantifier could be a better name? see below) against the array right.`

---

*[pkg/sql/parser/eval.go, line 1449 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12102#-KYKb9DL0HQ5CRJGbrTS:-KYKb9DLED_vV2p9XnCZ:b66bckx) ([raw file](https://github.com/cockroachdb/cockroach/blob/943a5e57c798158cf9f02f4cee0b7c04bcf79066/pkg/sql/parser/eval.go#L1449)):*
> ```Go
> func evalArrayCmp(
> 	ctx *EvalContext,
> 	subOp ComparisonOperator,
> ```

Will this function horribly break if subOp isn't any/some/all? Should we check that condition? Alternatively, would it make any sense to break any/some/all out into their own new type? They aren't really ComparisonOperators after all - they're quantifiers.

---

*[pkg/sql/parser/eval.go, line 1452 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12102#-KYKbIqkC3Bv6p0xxuHe:-KYKbIqk4rug-bryVBG3:b-cy8dbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/943a5e57c798158cf9f02f4cee0b7c04bcf79066/pkg/sql/parser/eval.go#L1452)):*
> ```Go
> 	fn CmpOp,
> 	left, right Datum,
> 	all bool,
> ```

Perhaps this argument could be deleted? This function has all the information it needs to decide the value of `all` since it is passed the subOp.

---

*[pkg/sql/parser/eval.go, line 1457 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12102#-KYKb5HAAn0mG8b9232v:-KYKb5HAAKYU69vazegO:b-buk0pz) ([raw file](https://github.com/cockroachdb/cockroach/blob/943a5e57c798158cf9f02f4cee0b7c04bcf79066/pkg/sql/parser/eval.go#L1457)):*
> ```Go
> 	anyTrue := false
> 	sawNull := false
> 	for _, elem := range right.(*DArray).Array {
> ```

Does this cast need an error check?

---

*[pkg/sql/parser/expr.go, line 351 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12102#-KYK_34_AOGr5Bh4puW4:-KYK_34_0xO1AMH0WonH:b46kwil) ([raw file](https://github.com/cockroachdb/cockroach/blob/943a5e57c798158cf9f02f4cee0b7c04bcf79066/pkg/sql/parser/expr.go#L351)):*
> ```Go
> type ComparisonExpr struct {
> 	Operator    ComparisonOperator
> 	SubOperator ComparisonOperator // used for array operators.
> ```

Hmm, so SubOperator is Any/Some/All? I don't think I would have any idea what this indicates if I was reading this code for the first time. Can you think of a better name? Perhaps Quantifier could be suitable, as in the existential/universal quantifiers in math which these operators correspond to. If you disagree, I think a less terse comment is warranted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12102#-:-KYKbxY77T8-sfa-nBWY:b-1hwr3u)*

**Comment by nvanbenschoten** [comment]
Thanks for the review! I'm still working on cleaning some of this up, but as a general comment, `Any`, `Some`, and `All` are never the subOperators, they're always the Operators themselves. The subOperators (qualifiers) are the comparisons like `=` and `<` used by `Any`, `Some`, and `All`. This is important so that all specific handling of basic operators for things like normalization and index selection can stay the same. It also maintains consistency with `In`, which can be thought of as `Any(=)`. In an ideal world, these operators could be defined like (Rust):
```
enum ComparisonOperator {
  EQ,
  LT,
  ...
  Any(ComparisonOperator),
}
```
Clearly, this needs improved documentation so that its not confusing.

---

Review status: 0 of 12 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12102#-:-KYKd4KZ4-GF-w2I4g9U:b-400gyj)*

**Comment by knz** [comment]
Reviewed 11 of 12 files at r1.
Review status: 11 of 12 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/eval.go, line 1449 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12102#-KYKb9DL0HQ5CRJGbrTS:-KYKtunFDFoddRvFqaVZ:btacknc) ([raw file](https://github.com/cockroachdb/cockroach/blob/943a5e57c798158cf9f02f4cee0b7c04bcf79066/pkg/sql/parser/eval.go#L1449)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Will this function horribly break if subOp isn't any/some/all? Should we check that condition? Alternatively, would it make any sense to break any/some/all out into their own new type? They aren't really ComparisonOperators after all - they're quantifiers.
</blockquote></details>

Agreed, these should have their own type. Granted they may not be enums but they cannot be anything else than any/some/all right?

---

*[pkg/sql/parser/sql.y, line 3639 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12102#-KYKuPHK0ZBaLMGOmyt1:-KYKuPHK19OE8HJB8J7E:b-99avpi) ([raw file](https://github.com/cockroachdb/cockroach/blob/943a5e57c798158cf9f02f4cee0b7c04bcf79066/pkg/sql/parser/sql.y#L3639)):*
> ```Yacc
>     $$.val = &ComparisonExpr{Operator: NotIn, Left: $1.expr(), Right: $4.expr()}
>   }
> | a_expr subquery_op sub_type select_with_parens %prec CONCAT
> ```

Once #12111 is merged, I would favor a single rule here instead of two:
```
| a_expr subquery_op sub_type d_expr %prec CONCAT
{ ... }
```

This way we can then write `1 = ANY ARRAY[1,2,3]`, `1 = ANY current_schemas(true)`, etc without needing the parentheses (but the parentheses would still be allowed). What do you think?

---

*[pkg/sql/parser/type_check_test.go, line 124 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12102#-KYKtd_x-JYYWVUzxsrJ:-KYKtd_yBAy0nGO1ZpK8:b-hgv9l8) ([raw file](https://github.com/cockroachdb/cockroach/blob/943a5e57c798158cf9f02f4cee0b7c04bcf79066/pkg/sql/parser/type_check_test.go#L124)):*
> ```Go
> 		{`1 IN ('a', 'b')`, `unsupported comparison operator: 1 IN ('a', 'b'): expected 1 to be of type string, found type int`},
> 		{`1 IN (1, 'a')`, `unsupported comparison operator: 1 IN (1, 'a'): expected 1 to be of type string, found type int`},
> 		{`1 = ANY (2)`, `unsupported comparison operator: 1 = ANY 2: op ANY (array) requires array on right side`},
> ```

I'm not fond of this limitation, I think we should support ANY/SOME on tuples right away not just arrays.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12102)*

**Comment by nvanbenschoten** [comment]
Thanks for the review @knz. Still cleaning some of this up but addresses a few questions,

---

Review status: 11 of 12 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/eval.go, line 1449 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12102#-KYKb9DL0HQ5CRJGbrTS:-KYL1YD0BMj9RvUUU9aR:beunmrx) ([raw file](https://github.com/cockroachdb/cockroach/blob/943a5e57c798158cf9f02f4cee0b7c04bcf79066/pkg/sql/parser/eval.go#L1449)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Agreed, these should have their own type. Granted they may not be enums but they cannot be anything else than any/some/all right?
</blockquote></details>

@knz did you happen to see my comment above? any/some/all are not subOps, they're the primary operators.

---

*[pkg/sql/parser/sql.y, line 3639 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12102#-KYKuPHK0ZBaLMGOmyt1:-KYL1k9-8PMRdc6Iqme7:b-flq8sx) ([raw file](https://github.com/cockroachdb/cockroach/blob/943a5e57c798158cf9f02f4cee0b7c04bcf79066/pkg/sql/parser/sql.y#L3639)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Once #12111 is merged, I would favor a single rule here instead of two:
```
| a_expr subquery_op sub_type d_expr %prec CONCAT
{ ... }
```

This way we can then write `1 = ANY ARRAY[1,2,3]`, `1 = ANY current_schemas(true)`, etc without needing the parentheses (but the parentheses would still be allowed). What do you think?
</blockquote></details>

I'd be in favor of that because it would allow us to address the issue is brought up in `normalize_test.go`!

---

*[pkg/sql/parser/type_check_test.go, line 124 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12102#-KYKtd_x-JYYWVUzxsrJ:-KYL1qJm-5ttHVdOEaLn:buri0wa) ([raw file](https://github.com/cockroachdb/cockroach/blob/943a5e57c798158cf9f02f4cee0b7c04bcf79066/pkg/sql/parser/type_check_test.go#L124)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'm not fond of this limitation, I think we should support ANY/SOME on tuples right away not just arrays.
</blockquote></details>

ANY/SOME is a strictly Postgres extension, and they only support arrays. Is it worth extending their extension even further?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12102#-:-KYL2D_E43j18mdWKSZw:b1qoehl)*

**Comment by knz** [comment]
Review status: 11 of 12 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/eval.go, line 1449 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12102#-KYKb9DL0HQ5CRJGbrTS:-KYL4sMo8UVz5hI8Y5wu:b-sv9yzc) ([raw file](https://github.com/cockroachdb/cockroach/blob/943a5e57c798158cf9f02f4cee0b7c04bcf79066/pkg/sql/parser/eval.go#L1449)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

@knz did you happen to see my comment above? any/some/all are not subOps, they're the primary operators.
</blockquote></details>

I think I did not understand it the first time round. Now it's clearer, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12102)*

**Comment by cuongdo** [comment]
Any chance of getting this in early next week?

**Comment by nvanbenschoten** [comment]
After a bit of cleanup, a rebase, and some trial-and-error to convince myself that there isn't a nicer way to do the sub-operation stuff, this is ready for a full review now.

---

Review status: 1 of 12 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[pkg/sql/parser/eval.go, line 1447 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12102#-KYKaSAk31mrArf9IdHh:-KYrCyDGLSqPwqAuGwH1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/943a5e57c798158cf9f02f4cee0b7c04bcf79066/pkg/sql/parser/eval.go#L1447)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think a brief header comment on this function could be really helpful, e.g. `evalArrayCmp evaluates the comparison in the scope of subOp (or quantifier could be a better name? see below) against the array right.`
</blockquote></details>

Done.

---

*[pkg/sql/parser/eval.go, line 1457 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12102#-KYKb5HAAn0mG8b9232v:-KYr9eafzDfsUL5mrlIY:b-lap7nt) ([raw file](https://github.com/cockroachdb/cockroach/blob/943a5e57c798158cf9f02f4cee0b7c04bcf79066/pkg/sql/parser/eval.go#L1457)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Does this cast need an error check?
</blockquote></details>

It doesn't because type checking and normalization will assure that only a `DArray` can reach here, but it makes more sense to make DArray part of the contract of the function and bring the assertion out to `ComparisonExpr.Eval`. Done.

---

*[pkg/sql/parser/sql.y, line 3639 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12102#-KYKuPHK0ZBaLMGOmyt1:-KYqoYzUwnqLefn7XYXh:b-zc28ls) ([raw file](https://github.com/cockroachdb/cockroach/blob/943a5e57c798158cf9f02f4cee0b7c04bcf79066/pkg/sql/parser/sql.y#L3639)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'd be in favor of that because it would allow us to address the issue is brought up in `normalize_test.go`!
</blockquote></details>

Done. Changed a lot of tests for this too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12102#-:-KYrCw9nCl8C21QCxjie:b34u0sb)*

**Comment by knz** [comment]
Excellent, this looks much cleaner now. Just a nit about one of the main error messages.

---

Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/sql.y, line 3717 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12102#-KYs1WQy_UOUoZuH4Ikz:-KYs1WQzTRz8sS9ItjPX:b4deg3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3bf07e93fc9ed5f369c32f2a8a97195b74b2d9c/pkg/sql/parser/sql.y#L3717)):*
> ```Yacc
>     subOp, ok := $2.op().(ComparisonOperator)
>     if !ok {
>       sqllex.Error(fmt.Sprintf("op %s array requires operator to yield boolean", op))
> ```

I don't like this message because 1) it's not really informative and 2) it doesn't tell the user what to do to fix the problem. What about 

`Sprintf("%s %s <array> is invalid because "%s" is not a boolean operator", $2.op(), op, $2.op)`

---

*[pkg/sql/parser/type_check_test.go, line 124 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12102#-KYKtd_x-JYYWVUzxsrJ:-KYs-xqeTRUWYySSSurY:bklf16k) ([raw file](https://github.com/cockroachdb/cockroach/blob/943a5e57c798158cf9f02f4cee0b7c04bcf79066/pkg/sql/parser/type_check_test.go#L124)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

ANY/SOME is a strictly Postgres extension, and they only support arrays. Is it worth extending their extension even further?
</blockquote></details>

I think they also work on subqueries. But I may be wrong.
Meanwhile this is really a side topic, so if that's really important we can revisit later. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12102#-:-KYs3V9z9pmv_7EMPRWk:b-67afx4)*

**Comment by nvanbenschoten** [comment]
TFTR!

---

Review status: 9 of 12 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/sql/parser/sql.y, line 3717 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12102#-KYs1WQy_UOUoZuH4Ikz:-KYsUpolgcEyy4s1Q0WE:b-14hho7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3bf07e93fc9ed5f369c32f2a8a97195b74b2d9c/pkg/sql/parser/sql.y#L3717)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't like this message because 1) it's not really informative and 2) it doesn't tell the user what to do to fix the problem. What about 

`Sprintf("%s %s <array> is invalid because "%s" is not a boolean operator", $2.op(), op, $2.op)`
</blockquote></details>

This was ripped directly from Postgres, but I like your phrasing better. Done.

---

*[pkg/sql/parser/type_check_test.go, line 124 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12102#-KYKtd_x-JYYWVUzxsrJ:-KYsVdKQuzXAK6YhdBar:ba60ou5) ([raw file](https://github.com/cockroachdb/cockroach/blob/943a5e57c798158cf9f02f4cee0b7c04bcf79066/pkg/sql/parser/type_check_test.go#L124)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think they also work on subqueries. But I may be wrong.
Meanwhile this is really a side topic, so if that's really important we can revisit later. :)
</blockquote></details>

SGTM :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12102#-:-KYsVgFPVpBYhnWMZO9N:b-814g8k)*

**Comment by knz** [comment]
LGTM

I think you need to rebase as your test is hitting a bug in `HandleSnapshot` that was fixed last weekend.

**Pull request merged**
