### PR TITLE
Improve create index privilege tests.

### PR DESCRIPTION
**Pull request by mberhault**
https://github.com/cockroachdb/docs/issues/216

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6004)

### CODE REVIEW

**Comment by andreimatei** [comment]
isn't there a GRANT test where this belongs better?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6004#-:-KFASVQfbgypWoGDuFSA:2034364405)*

**Comment by mberhault** [comment]
yes, but the grant test file is to test the behavior of the grant/revoke statements, not the application of privileges. Which privileges are used are determined in the individual statement implementations, so if feels more natural to keep the tests there.
Then again, not all statements have their own files, so it's not a hard rule.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6004#-:-KFBLJhHrXY-ZaWM63H6:-115381176)*

**Comment by andreimatei** [comment]
:lgtm: 

My vote is we put it all under GRANT tests. That's where I'd look for it.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6004#-:-KFBV6OHa4nUR1Ipq671:761603450)*

**Comment by mberhault** [comment]
really? we have ~15 different files in there that switch users, and also 15 that call `GRANT` although they don't overlap.

**Comment by andreimatei** [comment]
Well but I don't think any of those actually test GRANT. They need the users for starting different transactions, for example, and need to issue the GRANT.

**Comment by tamird** [comment]
LGTM

**Pull request merged**
