### PR TITLE
kvserver: fix bugs in & fortify tenant refcounting

### PR DESCRIPTION
**Pull request by tbg**
This PR fixes a sandwich of two bugs around refcounting the tenant rate limiters and metrics that I found while prototyping around #72374.

We had an accidental early return in `postDestroyRaftMuLocked` that meant that tenant metrics and rate limiters were essentially never released.

We were also continuing to use at least the tenant metrics object after the call to `postDestroyRaftMuLocked` had returned (but note that the above bug meant that we hadn't actually released the ref).

This PR fixes both and adds precautions against regressions of such bugs.

Despite having fixed bugs, I would be cautious about backporting this to 21.2 and 21.1; the bugs here never seem to have caused any problems, and since our day-to-day testing isn't heavy on tenants, it's unclear how reliably we'd be shaking out problems that were previously masked by the bug.

### CODE REVIEW

**Comment by tbg** [comment]
cc @ajwerner curious about your opinion on backporting the bug fixes here. I'd definitely want a lot of bake time but I do wonder if it's even a good idea in general to backport.

**Comment by tbg** [comment]
This is now RFAL.

**Review by ajwerner — APPROVED** [review]
:lgtm: 

I don't have much to say on the defensive checks for the tenant ID. I suspect I added them as I was implementing it to try to catch anything I might have missed. 

> Reviewed 1 of 1 files at r1, 12 of 12 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72471#-:-Mo9I1KIBJG8KNNqws2t:b-o4esu2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/kv/kvserver/metrics.go, line 1446 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72471#-Mo9E-Gz1nPAUSaCz_hG:-Mo9E-Gz1nPAUSaCz_hH:b419g92) ([raw file](https://github.com/cockroachdb/cockroach/blob/a11a5f21cf36e9305d89bcc44ca1ad67e49f18c3/pkg/kv/kvserver/metrics.go#L1446)):*
> ```
> 	_tenantID roachpb.TenantID
> 	_state    int32 // atomic; 0=usable 1=poisoned
> ```
why the `_` prefix? 
___
*[pkg/kv/kvserver/metrics.go, line 1447 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72471#-Mo9EMu2-qsJvsE8gnE6:-Mo9EMu2-qsJvsE8gnE7:bp25v4b) ([raw file](https://github.com/cockroachdb/cockroach/blob/a11a5f21cf36e9305d89bcc44ca1ad67e49f18c3/pkg/kv/kvserver/metrics.go#L1447)):*
> ```Go
> 	_tenantID roachpb.TenantID
> 	_state    int32 // atomic; 0=usable 1=poisoned
> 	stack     []byte
> ```

Comment on when this gets populated and note that this should effectively never be populated and then stick around for a long time. It'd probably be sad if we populated and stored a stack trace for all replicas at all times (which this does not do). 
___
*[pkg/kv/kvserver/metrics.go, line 1554 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72471#-Mo9E6i59UYVOzXbotY8:-Mo9E6i59UYVOzXbotY9:b-gkyr04) ([raw file](https://github.com/cockroachdb/cockroach/blob/a11a5f21cf36e9305d89bcc44ca1ad67e49f18c3/pkg/kv/kvserver/metrics.go#L1554)):*
> ```Go
> 	m := sm.getTenant(ctx, ref) // NB: asserts against use-after-release
> 	if atomic.SwapInt32(&ref._state, 1) != 0 {
> 		log.Fatalf(ctx, "metrics ref released twice")
> ```

Log the stack trace here?
___
*[pkg/kv/kvserver/metrics.go, line 1556 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72471#-Mo9Euh732-l8thaUsDk:-Mo9Euh732-l8thaUsDl:b-ifwbfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a11a5f21cf36e9305d89bcc44ca1ad67e49f18c3/pkg/kv/kvserver/metrics.go#L1556)):*
> ```Go
> 		log.Fatalf(ctx, "metrics ref released twice")
> 	}
> 	ref.stack = debug.Stack()
> ```

Does this not need to be protected by the mutex? Is there some assumption that the Replica.mu or a different mutex is locked?  If so, comment it. 
___
*[pkg/kv/kvserver/metrics.go, line 1479 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72471#-Mo9HGar5EVk7QXqGSV1:-Mo9HGar5EVk7QXqGSV2:b-1n23kc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0e25e0a62cd6a287d77355a14d7e04046e5b2a5/pkg/kv/kvserver/metrics.go#L1479)):*
> ```Go
> 	// This struct is invisible to the metric package.
> 	//
> 	// TODO(tbg): seems bad that this uses int64 keys but tenantIDs can
> ```

Sometimes I wish `uint63` was a datatype.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72471)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

___
*[pkg/kv/kvserver/metrics.go, line 1446 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72471#-Mo9E-Gz1nPAUSaCz_hG:-MoiFaCs5s6r6r_rawWq:b-san9cx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a11a5f21cf36e9305d89bcc44ca1ad67e49f18c3/pkg/kv/kvserver/metrics.go#L1446)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	_tenantID roachpb.TenantID
> 	_state    int32 // atomic; 0=usable 1=poisoned
> ```
why the `_` prefix? 
</blockquote></details>

This stuff lives in the same package as the "user", I want to somehow signal that these fields aren't to be accessed directly by anyone except the type's receivers. This is the best I could do without pulling this into a separate package, which I felt was not worth it.
___
*[pkg/kv/kvserver/metrics.go, line 1479 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72471#-Mo9HGar5EVk7QXqGSV1:-MoiTh6GD_j61nbLjLli:b7w945n) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0e25e0a62cd6a287d77355a14d7e04046e5b2a5/pkg/kv/kvserver/metrics.go#L1479)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Sometimes I wish `uint63` was a datatype. 
</blockquote></details>

Actually not sure what I was thinking in this comment - everything does work. It would be annoying to look at this map through a debugger and to have to do a manual int64->uint64 cast, but honestly that's fine. Re-worded the comment.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 11 of 12 files at r6, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72471)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @tbg)

___
*[pkg/kv/kvserver/metrics.go, line 1463 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72471#-Moifach8O0zkzqwDKSh:-Moifach8O0zkzqwDKSi:b-s3rr36) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b086eb08995b16ba962d5534476dd37adef3838/pkg/kv/kvserver/metrics.go#L1463)):*
> ```Go
> 		ref._stack.Lock()
> 		defer ref._stack.Unlock()
> 		log.Fatalf(ctx, "tenantMetricsRef already finalized in:\n%s", ref._stack.b)
> ```

want to use depth 1?
___
*[pkg/kv/kvserver/metrics.go, line 1572 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72471#-MoifJfNE2wQWcp9mRNv:-Moif94cBeLcTB_vpXTY:b-pytqww) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b086eb08995b16ba962d5534476dd37adef3838/pkg/kv/kvserver/metrics.go#L1572)):*
> ```Go
> 		ref._stack.Lock()
> 		defer ref._stack.Unlock()
> 		log.Fatalf(ctx, "metrics ref released twice, first time in: %s", ref._stack)
> ```

This needs to be `ref._stack.b`

Also, this is almost exactly `assert` but with a different message. Maybe just add a string or redect.SafeString to assert like `inc`, `get`, `release`? Also, want to make sure the stack doesn't get redacted when we do assert?

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72471)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

___
*[pkg/kv/kvserver/metrics.go, line 1572 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72471#-MoifJfNE2wQWcp9mRNv:-MomLry7DJmAGZQbHavy:b-nunc7s) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b086eb08995b16ba962d5534476dd37adef3838/pkg/kv/kvserver/metrics.go#L1572)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This needs to be `ref._stack.b`

Also, this is almost exactly `assert` but with a different message. Maybe just add a string or redect.SafeString to assert like `inc`, `get`, `release`? Also, want to make sure the stack doesn't get redacted when we do assert?
</blockquote></details>

I simplified this by calling `assert`. When it gets hit we get the stack of the second and the first caller so I don't think we need to custom-tailor the message.

I would like to have the stack unredacted, but unfortunately a stack trace in general contains PII, and I don't want to get into the game of trying to guess who the callers are (nor write the redaction logic for a stack trace, we can probably use panicparse to facilitate that though).

**Comment by tbg** [comment]
bors r=ajwerner

**Pull request merged**
