### PR TITLE
kv: commit-wait before running commit triggers and resolving intents

### PR DESCRIPTION
**Pull request by nvb**
Fixes a serious bug revealed by #63747.

This commit fixes a bug revealed by kvnemesis where a range-merge watcher on the
right-hand side of a range merge could incorrectly determine that a range merge
txn had succeeded, when in reality, it had failed. The watcher would then put
the RHS leaseholder replica into a stalled state by setting `r.mu.destroyStatus`
to `destroyReasonMergePending`, effectively stalling any operation on the range
indefinitely.

The setup for this bug was that a range was operating with a `global_reads` zone
configuration attribute, so it was pushing all writers into the future. The
range was split and then rapidly merged back together. During the merge txn, a
range-merge watcher (see `maybeWatchForMergeLocked`) began monitoring the state
of the range merge txn. The problem was that at the time that the range merge
txn committed, neither the meta descriptor version written by the merge or even
the meta descriptor version written by the split were visible to the watcher's
follow-up query. Because the watcher read below the split txn's descriptor, it
came to the wrong conclusion about the merge.

It is interesting to think about what is going wrong here, because it's not
immediately obvious who is at fault. If a transaction has a commit timestamp in
the future of present time, it will need to commit-wait before acknowledging the
client. Typically, this is performed in the TxnCoordSender after the transaction
has committed and resolved its intents (see TxnCoordSender.maybeCommitWait). It
is safe to wait after a future-time transaction has committed and resolved
intents without compromising linearizability because the uncertainty interval of
concurrent and later readers ensures atomic visibility of the effects of the
transaction. In other words, all of the transaction's intents will become
visible and will remain visible at once, which is sometimes called "monotonic
reads". This is true even if the resolved intents are at a high enough timestamp
such that they are not visible to concurrent readers immediately after they are
resolved, but only become visible sometime during the writer's commit-wait
sleep. This property is central to the correctness of non-blocking transactions.
See: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20200811_non_blocking_txns.md

However, if a transaction has a commit trigger, the side-effects of the trigger
will go into effect immediately upon applying the corresponding Raft log entry.
This poses a problem, because we do not want part of a transaction's effects
(e.g. its commit trigger) to become visible to onlookers before the rest of its
effects do (e.g. its intent writes).

To avoid this problem, this commit adds special server-side logic to perform the
commit-wait stage of a transaction with a commit trigger early, before its
EndTxn evaluates and its commit trigger fires. This results in the transaction
waiting longer to commit, run its commit trigger, and resolve its intents, but
it is otherwise safe and effective.

Interestingly, this is quite similar to how Spanner handles its commit-wait rule:

> Before allowing any coordinator replica to apply the commit record, the
> coordinator leader waits until TT.after(s), so as to obey the commit-wait rule
> described in Section 4.1.2. Because the coordinator leader chose s based on
> TT.now().latest, and now waits until that timestamp is guaranteed to be in the
> past, the expected wait is at least 2 ∗ . This wait is typically overlapped with
> Paxos communication. After commit wait, the coordinator sends the commit
> timestamp to the client and all other participant leaders. Each participant
> leader logs the transaction’s outcome through Paxos. All participants apply at
> the same timestamp and then release locks.

Of course, the whole point of non-blocking transactions is that we release locks
early and use clocks (through uncertainty intervals + a reader-side commit-wait
rule) to enforce consistency, so we don't want to make this change for standard
transactions.

Before this change, I could hit the bug in about 5 minutes of stressing
kvnemesis on a roachprod cluster. After this change, I've been able to run
kvnemesis for a few hours without issue.

Release note (bug fix): Fixed a rare bug present in betas where rapid range
splits and merges on a GLOBAL table could lead to a stuck leaseholder replica.
The situation is no longer possible.

cc. @cockroachdb/kv

### CODE REVIEW

**Review by andreimatei — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63971)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/kv/kvserver/replica_send.go, line 370 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63971#-MYptSHH8VPMlvUdnwvE:-MYptSHH8VPMlvUdnwvF:b-zfwcj5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2967b1cb6eba85d5ffaac174e542ddc296439813/pkg/kv/kvserver/replica_send.go#L370)):*
> ```Go
> 		// to move a transaction to a COMMITTED status, but the transaction wanted
> 		// to perform a commit-wait before committing and resolving intents. We
> 		// don't want to do so while holding latches, so we threw the error to up
> ```

"to up here" refers to an "up here" and "down there" that might not be very clear to a reader - perhaps one holding the map upside down. Let's say something else.
___
*[pkg/kv/kvserver/batcheval/cmd_end_transaction.go, line 369 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63971#-MYppwsR5TF4Fr_EP4PG:-MYppwsR5TF4Fr_EP4PH:b-75jl77) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c103726de6994b26706244144d3d9f7dd6b1f58/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L369)):*
> ```Go
> 		)
> 		if err != nil {
> 			return result.Result{}, roachpb.NewReplicaCorruptionError(err)
> ```

What's up with this change, and the new `ReplicaCorruptionErrors` below? Perhaps it deserves a separate commit?
___
*[pkg/kv/kvserver/batcheval/cmd_end_transaction.go, line 643 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63971#-MYpr2Z-DNdnUbx6HDEQ:-MYpr2Z-DNdnUbx6HDER:b-kxnb59) ([raw file](https://github.com/cockroachdb/cockroach/blob/2967b1cb6eba85d5ffaac174e542ddc296439813/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L643)):*
> ```
> 	// will need to commit-wait before acknowledging the client. Typically, this
> 	// is performed in the TxnCoordSender after the transaction has committed and
> 	// resolved its intents (see TxnCoordSender.maybeCommitWait). It is safe to
> ```

You say this here and in the commit message, but is the "after... it resolved its intents" part true? I don't see the `EndTxn` processing waiting for intent resolution when the resolution takes the (normal) async path. In fact, we've wanted to do the waiting as a form of pushback on writers, haven't we?
https://github.com/cockroachdb/cockroach/blob/2d5a43e050bf073cc56a9b06252353e5029a3026/pkg/kv/kvserver/replica_write.go#L211
___
*[pkg/kv/kvserver/batcheval/cmd_end_transaction.go, line 674 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63971#-MYpstK3DvmXdxKUtWLc:-MYpstK3DvmXdxKUtWLd:barg5jq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2967b1cb6eba85d5ffaac174e542ddc296439813/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L674)):*
> ```Go
> 		// Replica.executeBatchWithConcurrencyRetries catch this error, drop
> 		// latches, perform the commit-wait, re-acquire latches, and retry this
> 		// request.
> ```

spell out here or above that replicating the command with the effects of the `{split,merge}Trigger` below is the part can only be done after waiting.
___
*[pkg/kv/kvserver/batcheval/cmd_end_transaction.go, line 675 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63971#-MYpt8tV1nsOpalQEaCM:-MYpt8tV1nsOpalQEaCN:b-36gnzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/2967b1cb6eba85d5ffaac174e542ddc296439813/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L675)):*
> ```Go
> 		// latches, perform the commit-wait, re-acquire latches, and retry this
> 		// request.
> 		return result.Result{}, roachpb.NewCommitWaitBeforeIntentResolutionError(txn.WriteTimestamp)
> ```

mmm this kind of "try evaluation, fail, catch the error higher up, try again" is a kind of action at a distance that's hard to trace. If we can, I think we should avoid. 
Can an `EndTxn` with a trigger be batched with other requests that might change the commit timestamp? I'd say probably not, and even if it could I'm not sure we'd end up here if the write ts was pushed in the same battch. So I'd say let's recognize an `EndTxn{commitTrigger}` request in replica_send, do the waiting, and here just assert that there's no synthetic timestamp. WDYT?
___
*[pkg/roachpb/errors.proto, line 489 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63971#-MYprlLJ9nn_vkg2VE5B:-MYprlLKDWnCf5fj_N7d:b-i5hwke) ([raw file](https://github.com/cockroachdb/cockroach/blob/2967b1cb6eba85d5ffaac174e542ddc296439813/pkg/roachpb/errors.proto#L489)):*
> ```protobuf
> }
> 
> // A CommitWaitBeforeIntentResolutionError indicates that the request attempted
> ```

s/the request/an EndTxn(commit=true. Are there others? It'd be good to be specific.
___
*[pkg/roachpb/errors.proto, line 496 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63971#-MYpruMGCzWp_UlTBOi5:-MYpruMGCzWp_UlTBOi6:b-qcqb8l) ([raw file](https://github.com/cockroachdb/cockroach/blob/2967b1cb6eba85d5ffaac174e542ddc296439813/pkg/roachpb/errors.proto#L496)):*
> ```protobuf
> // effects (i.e. its intent writes) will be visible upon resolution.
> //
> // This error is handled by the Store and should not escape to higher levels.
> ```

s/should not/does not :)

**Review by tbg — COMMENTED** [review]
This looks good to me, mod the comments. Random question I have, the way splits and merges work at all here is that they get bumped but lay down their intents, then can refresh (since they only access the descriptors they have intents on anyway) and then go for the commit trigger (which has the wait inserted here), right? And it doesn't seem that the commit-wait has any effect on user traffic.

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63971#-:-MYsoFWNCrWMbYozeY-t:bik8jew)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvserver/batcheval/cmd_end_transaction.go, line 675 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63971#-MYpt8tV1nsOpalQEaCM:-MYslfTE3BwxxQ4j7vdL:b-cehelo) ([raw file](https://github.com/cockroachdb/cockroach/blob/2967b1cb6eba85d5ffaac174e542ddc296439813/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L675)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

mmm this kind of "try evaluation, fail, catch the error higher up, try again" is a kind of action at a distance that's hard to trace. If we can, I think we should avoid. 
Can an `EndTxn` with a trigger be batched with other requests that might change the commit timestamp? I'd say probably not, and even if it could I'm not sure we'd end up here if the write ts was pushed in the same battch. So I'd say let's recognize an `EndTxn{commitTrigger}` request in replica_send, do the waiting, and here just assert that there's no synthetic timestamp. WDYT?
</blockquote></details>

I had the same thought. If we can pull the logic up and avoid the yo-yo (leaving only a hard error here), I think that would be preferable from a simplicity point of view.
___
*[pkg/kv/kvserver/batcheval/cmd_end_transaction_test.go, line 1082 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63971#-MYsm2cE7NfL67ciXOFx:-MYsm2cE7NfL67ciXOFy:b-w3o771) ([raw file](https://github.com/cockroachdb/cockroach/blob/2967b1cb6eba85d5ffaac174e542ddc296439813/pkg/kv/kvserver/batcheval/cmd_end_transaction_test.go#L1082)):*
> ```Go
> //
> // - futureCommitTime: configures whether or not EndTxn request is sent on
> //     behalf of a transaction with a synthetic commit timestamp that leads the
> ```

so `syntheticCommitTime` and `futureCommitTime` overlap? I see that you're skipping this below, but it looks like it would be less confusing if you had two dimensions:

```go
testutils.RunTrueOrFalse(t, "commitTrigger", func(t *testing.T, commitTrigger bool) {
	for _, cfg := range []struct {
		name     string
		commitTS func(now hlc.Timestamp) hlc.Timestamp
	}{
		{"past", func(now hlc.Timestamp) hlc.Timestamp { return now }},
		{"past-syn", func(now hlc.Timestamp) hlc.Timestamp { return now.WithSynthetic(true) }},
		{"future-syn", func(now hlc.Timestamp) hlc.Timestamp { return now.Add(100, 0).WithSynthetic(true) }},
	} {
		t.Run(cfg.name, func(t *testing.T) {
			// ...
		})
	}
})
```

**Review by nvb — COMMENTED** [review]
Thanks for the reviews! I restructured this to be more in line with the control flow you two preferred. I was initially concerned that waiting before evaluation has determined that the transaction will commit successfully or not would lead to wasted work, and that it would be nice to be able to handle cases where the batch is bumped to a higher timestamp after acquiring latches. The first is still a minor concern, but I don't think it will matter in practice. The second concern was misguided, as trying to handle this case opens us up to an infinite retry loop where the request is continuously pushed and rejected with a `CommitWaitBeforeIntentResolutionError`. Even though we don't expect this situation to be possible, it feels much safer to reject this kind of situation with a hard error instead of letting it silently run wild. PTAL at the new approach.

> Random question I have, the way splits and merges work at all here is that they get bumped but lay down their intents, then can refresh (since they only access the descriptors they have intents on anyway) and then go for the commit trigger (which has the wait inserted here), right?

Yes, exactly.

> And it doesn't seem that the commit-wait has any effect on user traffic.

I haven't noticed any. The intent writes laid down by a split or merge should not be read consistently by foreground traffic. All meta range reads use the READ_UNCOMMITTED consistency level, so they won't block on the intents. The only potential for blocking is due to latching, which is why we're careful not to commit-wait while holding latches here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63971#-:-MZGgJZ339kvAY5MCQM0:b-5wttby)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/kv/kvserver/replica_send.go, line 370 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63971#-MYptSHH8VPMlvUdnwvE:-MYufWhS0Qg7xL2sm94k:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2967b1cb6eba85d5ffaac174e542ddc296439813/pkg/kv/kvserver/replica_send.go#L370)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

"to up here" refers to an "up here" and "down there" that might not be very clear to a reader - perhaps one holding the map upside down. Let's say something else.
</blockquote></details>

Removed.
___
*[pkg/kv/kvserver/batcheval/cmd_end_transaction.go, line 369 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63971#-MYppwsR5TF4Fr_EP4PG:-MZGMnuB54-YIupF_DME:b-8y2u5d) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c103726de6994b26706244144d3d9f7dd6b1f58/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L369)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

What's up with this change, and the new `ReplicaCorruptionErrors` below? Perhaps it deserves a separate commit?
</blockquote></details>

It was a small refactor to break the assumption that all errors from `RunCommitTrigger` amount to replica corruption errors.
___
*[pkg/kv/kvserver/batcheval/cmd_end_transaction.go, line 643 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63971#-MYpr2Z-DNdnUbx6HDEQ:-MZGMmr08I2uexACTKCV:b-k7mx7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/2967b1cb6eba85d5ffaac174e542ddc296439813/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L643)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> ```
> 	// will need to commit-wait before acknowledging the client. Typically, this
> 	// is performed in the TxnCoordSender after the transaction has committed and
> 	// resolved its intents (see TxnCoordSender.maybeCommitWait). It is safe to
> ```

You say this here and in the commit message, but is the "after... it resolved its intents" part true? I don't see the `EndTxn` processing waiting for intent resolution when the resolution takes the (normal) async path. In fact, we've wanted to do the waiting as a form of pushback on writers, haven't we?
https://github.com/cockroachdb/cockroach/blob/2d5a43e050bf073cc56a9b06252353e5029a3026/pkg/kv/kvserver/replica_write.go#L211

</blockquote></details>

Deleted.
___
*[pkg/kv/kvserver/batcheval/cmd_end_transaction.go, line 674 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63971#-MYpstK3DvmXdxKUtWLc:-MZGMjLK28Nbwa29S-O7:b-k7mx7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/2967b1cb6eba85d5ffaac174e542ddc296439813/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L674)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

spell out here or above that replicating the command with the effects of the `{split,merge}Trigger` below is the part can only be done after waiting.
</blockquote></details>

Deleted.
___
*[pkg/kv/kvserver/batcheval/cmd_end_transaction.go, line 675 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63971#-MYpt8tV1nsOpalQEaCM:-MZGMlRdAKiPoRJSgWga:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2967b1cb6eba85d5ffaac174e542ddc296439813/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L675)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I had the same thought. If we can pull the logic up and avoid the yo-yo (leaving only a hard error here), I think that would be preferable from a simplicity point of view.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/batcheval/cmd_end_transaction_test.go, line 1082 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63971#-MYsm2cE7NfL67ciXOFx:-MZGM49yA-Z0caE7wNIy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2967b1cb6eba85d5ffaac174e542ddc296439813/pkg/kv/kvserver/batcheval/cmd_end_transaction_test.go#L1082)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

so `syntheticCommitTime` and `futureCommitTime` overlap? I see that you're skipping this below, but it looks like it would be less confusing if you had two dimensions:

```go
testutils.RunTrueOrFalse(t, "commitTrigger", func(t *testing.T, commitTrigger bool) {
	for _, cfg := range []struct {
		name     string
		commitTS func(now hlc.Timestamp) hlc.Timestamp
	}{
		{"past", func(now hlc.Timestamp) hlc.Timestamp { return now }},
		{"past-syn", func(now hlc.Timestamp) hlc.Timestamp { return now.WithSynthetic(true) }},
		{"future-syn", func(now hlc.Timestamp) hlc.Timestamp { return now.Add(100, 0).WithSynthetic(true) }},
	} {
		t.Run(cfg.name, func(t *testing.T) {
			// ...
		})
	}
})
```
</blockquote></details>

Done.
___
*[pkg/roachpb/errors.proto, line 489 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63971#-MYprlLJ9nn_vkg2VE5B:-MZGN1J50BXG7R08keEF:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2967b1cb6eba85d5ffaac174e542ddc296439813/pkg/roachpb/errors.proto#L489)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/the request/an EndTxn(commit=true. Are there others? It'd be good to be specific.
</blockquote></details>

Removed.
___
*[pkg/roachpb/errors.proto, line 496 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63971#-MYpruMGCzWp_UlTBOi5:-MZGN2bBBk5DbdOGR5LD:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2967b1cb6eba85d5ffaac174e542ddc296439813/pkg/roachpb/errors.proto#L496)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/should not/does not :)
</blockquote></details>

Removed.

**Review by andreimatei — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63971#-:-MZJ0riv9tT9LTsQ1w09:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/replica_send.go, line 146 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63971#-MZJ0EhEDbku9KHvTadX:-MZJ0EhEDbku9KHvTadY:b7vkbpv) ([raw file](https://github.com/cockroachdb/cockroach/blob/80e55cf008a4883845f97f453945c6a6de330821/pkg/kv/kvserver/replica_send.go#L146)):*
> ```Go
> 	}
> 	et := args.(*roachpb.EndTxnRequest)
> 	if !et.Commit || et.InternalCommitTrigger == nil {
> ```

should we assert around here that, if there's a `CommitTrigger`, then there aren't any other requests in the batch other than the `EndTxn`? Cause if there were, then those might cause the `WriteTimestamp` to be bumped later, and could hit the assertion in `RunCommitTrigger`, right?

**Review by nvb — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63971#-:-MZJ_c9G7xftMk7_rLf0:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/kv/kvserver/replica_send.go, line 146 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63971#-MZJ0EhEDbku9KHvTadX:-MZJZtoA8wMI6gqa16MJ:b-89d5da) ([raw file](https://github.com/cockroachdb/cockroach/blob/80e55cf008a4883845f97f453945c6a6de330821/pkg/kv/kvserver/replica_send.go#L146)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

should we assert around here that, if there's a `CommitTrigger`, then there aren't any other requests in the batch other than the `EndTxn`? Cause if there were, then those might cause the `WriteTimestamp` to be bumped later, and could hit the assertion in `RunCommitTrigger`, right?
</blockquote></details>

We do need to support 1PC transactions that contain commit-triggers (e.g. node liveness updates), so we can't make such an assertion here. But these types of transactions should not be run on a global_read range, and I'm ok with the assertion error we have being returned if they are. I added a follow on commit to make sure that we don't get into trouble with the global_reads attribute being set on the node liveness range.

**Pull request merged**
