### PR TITLE
sql: use better contexts

### PR DESCRIPTION
**Pull request by andreimatei**
Release note: None

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
LGTM

**Comment by RaduBerinde** [comment]
LGTM

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36110#-:-LbUMT8AC4xcoUUVb3c4:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36110#-:-LbZmkUT3ElXxbUNXfpO:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Pull request merged**
