### PR TITLE
server: fix diagnostic reporting of tabledescs + stats buckets

### PR DESCRIPTION
**Pull request by dt**
JSON-encoding the protos includes the field names, and thus breaks all the lovely wire compatibility semantics we expect from protobuf.

Instead we keep these protos in binary wire format, and use base64 to make that a legal son string.

Previously when reporting we iterated over the various stats buckets to build a report, but we mistakenly overwrote an existing bucket if the same query also existed with a different DistSQL or failure value.

### CODE REVIEW

**Comment by knz** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/server/updates.go, line 103 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16955#-Koh-rW1vCwj-diDsJHB:-Koh-rW1vCwj-diDsJHC:b-bf8m4r) ([raw file](https://github.com/cockroachdb/cockroach/blob/28be9effd012df74771e5cb6f11e90ef2ada25b8/pkg/server/updates.go#L103)):*
> ```Go
> 
> type reportingInfo struct {
> 	// Do not use json fields "sqlstats" or "schema" (used by 1.0).
> ```

Put more words in the comment to explain why.

---

*[pkg/sql/app_stats.go, line 280 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16955#-Koh8PNoHieKLfUF3fto:-Koh8PNpArxPxElYrZc3:b-73nazz) ([raw file](https://github.com/cockroachdb/cockroach/blob/28be9effd012df74771e5cb6f11e90ef2ada25b8/pkg/sql/app_stats.go#L280)):*
> ```Go
> 	Failed  bool                        `json:"failed"`
> 	Stats   roachpb.StatementStatistics `json:"stats"`
> }
> ```

I do not understand the transition from one data structure with a `map` to another with a slice. Please motivate here, or preferably in the commit message.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16955)*

**Comment by dt** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/server/updates.go, line 103 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16955#-Koh-rW1vCwj-diDsJHB:-KohLnEUsCsEEA5rGmtv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/28be9effd012df74771e5cb6f11e90ef2ada25b8/pkg/server/updates.go#L103)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Put more words in the comment to explain why.
</blockquote></details>

Done.

---

*[pkg/sql/app_stats.go, line 280 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16955#-Koh8PNoHieKLfUF3fto:-KohFV-jIHywEJC5Hm3O:b-f5d4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/28be9effd012df74771e5cb6f11e90ef2ada25b8/pkg/sql/app_stats.go#L280)):*

> also switch to a list of stats bundles (query+info+stats) rather than a map: 
maps require unique keys and we don't have a convenient one, plus we actually
don't want the lookup semantics of a map anyway -- the consumer (e.g. our 
diagnostic collector) can decide always if/how it wants to group the info as
fits its needs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16955)*

**Comment by dt** [comment]
This potentially could go further and just replace the whole HTTP request body with a binary proto, skipping JSON altogether.

**Comment by knz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/app_stats.go, line 280 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16955#-Koh8PNoHieKLfUF3fto:-KolprjBZFtyCdGg_BO3:bb6mt9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/28be9effd012df74771e5cb6f11e90ef2ada25b8/pkg/sql/app_stats.go#L280)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>


> also switch to a list of stats bundles (query+info+stats) rather than a map: 
maps require unique keys and we don't have a convenient one, plus we actually
don't want the lookup semantics of a map anyway -- the consumer (e.g. our 
diagnostic collector) can decide always if/how it wants to group the info as
fits its needs.
</blockquote></details>

:+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16955#-:-Kolq-cZgN1ZTKukHbmt:bnfp4nl)*

**Comment by dt** [comment]
Okay, bit of a rewrite, but updated second commit to do end-to-end protobuf, not just base64'ed tableDesc. At this point it probably makes more sense to squash before merge, but I left the first commit alone for review.

**Comment by dt** [comment]
@benesch I'll update the diagnostics collector server to switch on the content type if we decide we like this.

**Comment by knz** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/roachpb/app_stats.proto, line 73 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16955#-Kom8Fb9b0yfdB5MMd_-:-Kom8Fb9b0yfdB5MMd_0:b-mu4tvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/843d2188ef2b3d9852f3c330d98c8407b5cc5808/pkg/roachpb/app_stats.proto#L73)):*
> ```protobuf
> 
> message StatementStatisticsKey {
> 	optional string query = 1 [(gogoproto.nullable) = false];
> ```

tabs/spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16955)*

**Comment by dt** [comment]
Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/roachpb/app_stats.proto, line 73 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16955#-Kom8Fb9b0yfdB5MMd_-:-KomS3K0seNS5-x6EMwc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/843d2188ef2b3d9852f3c330d98c8407b5cc5808/pkg/roachpb/app_stats.proto#L73)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

tabs/spaces
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16955)*

**Comment by benesch** [comment]
I definitely like this! :thumbsup: 

Will this require versioning the reg server?

---

Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16955#-:-KomaIgMyU59HLD19fdn:b-i2o2od)*

**Comment by dt** [comment]
reg server can switch on content-type for now, and hopefully going forward we get the usual protobuf wirecompat semantics.

**Comment by benesch** [comment]
Oh, sorry, I completely missed the part where you said you were going to switch on Content-Type. Makes perfect sense!

**Pull request merged**
