### PR TITLE
storage: avoid lock ordering violation

### LINKED ISSUE #18298: kv: TestRangeSplitMeta failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/8ef84ea309e3fd54e18f2496794c73484e732a19

Parameters:
```
TAGS=deadlock
GOFLAGS=
```

Stress build found a failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=346181&tab=buildLog

```

I170907 08:12:59.294638 4695 kv/split_test.go:117  starting split at key "G"...
I170907 08:12:59.298123 4695 storage/replica_command.go:2710  [n1,s1,r1/1:/M{in-ax}] initiating a split of this range at key "G" [r2]
POTENTIAL DEADLOCK: Inconsistent locking. saw this ordering in one goroutine:
happened before
../storage/store.go:1104 storage.(*Store).Start { s.mu.Lock() } <<<<<
../testutils/localtestcluster/local_test_cluster.go:159 localtestcluster.(*LocalTestCluster).Start { if err := ltc.Store.Start(ctx, ltc.Stopper); err != nil { }
txn_coord_sender_test.go:75 kv.createTestDBWithContext { s.Start(t, testutils.NewNodeTestBaseContext(), InitSenderForLocalTestCluster) }
txn_coord_sender_test.go:66 kv.createTestDB { return createTestDBWithContext(t, client.DefaultDBContext()) }
split_test.go:103 kv.TestRangeSplitMeta { s, _ := createTestDB(t) }

happened after
../storage/timedmutex.go:92 storage.(*timedMutex).Lock { tm.mu.Lock() } <<<<<
../storage/replica.go:627 storage.(*Replica).init { r.raftMu.Lock() }
../storage/replica.go:621 storage.NewReplica { return r, r.init(desc, store.Clock(), replicaID) }
../storage/store.go:1117 storage.(*Store).Start.func1 { rep, err := NewReplica(&desc, s, 0) }
../storage/store.go:1034 storage.IterateRangeDescriptors.func1 { return fn(desc) }
../storage/engine/mvcc.go:1708 engine.MVCCIterate { done, err := f(roachpb.KeyValue{Key: metaKey.Key, Value: *value}) }
../storage/store.go:1038 storage.IterateRangeDescriptors { false /* !reverse */, kvToDesc) }
../storage/store.go:1147 storage.(*Store).Start { }) }
../testutils/localtestcluster/local_test_cluster.go:159 localtestcluster.(*LocalTestCluster).Start { if err := ltc.Store.Start(ctx, ltc.Stopper); err != nil { }
txn_coord_sender_test.go:75 kv.createTestDBWithContext { s.Start(t, testutils.NewNodeTestBaseContext(), InitSenderForLocalTestCluster) }
txn_coord_sender_test.go:66 kv.createTestDB { return createTestDBWithContext(t, client.DefaultDBContext()) }
split_test.go:103 kv.TestRangeSplitMeta { s, _ := createTestDB(t) }

in another goroutine: happened before
../storage/timedmutex.go:92 storage.(*timedMutex).Lock { tm.mu.Lock() } <<<<<
../storage/replica.go:3142 storage.(*Replica).handleRaftReady { r.raftMu.Lock() }
../storage/store.go:3548 storage.(*Store).processReady { stats, err := r.handleRaftReady(IncomingSnapshot{}) }
../storage/scheduler.go:216 storage.(*raftScheduler).worker { s.processor.processReady(ctx, id) }
../storage/scheduler.go:167 storage.(*raftScheduler).Start.func2 { s.worker(ctx) }
../util/stop/stopper.go:198 stop.(*Stopper).RunWorker.func1 { f(ctx) }

happend after
../storage/store.go:3841 storage.(*Store).tryGetOrCreateReplica { s.mu.Lock() } <<<<<
../storage/store.go:3760 storage.(*Store).getOrCreateReplica { ) }
../storage/replica.go:4422 storage.(*Replica).acquireSplitLock { rightRng, created, err := r.store.getOrCreateReplica(ctx, split.RightDesc.RangeID, 0, nil) }
../storage/replica.go:4412 storage.(*Replica).maybeAcquireSplitMergeLock { return r.acquireSplitLock(ctx, &split.SplitTrigger) }
../storage/replica.go:4280 storage.(*Replica).processRaftCommand { if splitMergeUnlock := r.maybeAcquireSplitMergeLock(ctx, raftCmd); splitMergeUnlock != nil { }
../storage/replica.go:3434 storage.(*Replica).handleRaftReadyRaftMuLocked { if changedRepl := r.processRaftCommand(ctx, commandID, e.Term, e.Index, command); changedRepl { }
../storage/replica.go:3144 storage.(*Replica).handleRaftReady { return r.handleRaftReadyRaftMuLocked(inSnap) }
../storage/store.go:3548 storage.(*Store).processReady { stats, err := r.handleRaftReady(IncomingSnapshot{}) }
../storage/scheduler.go:216 storage.(*raftScheduler).worker { s.processor.processReady(ctx, id) }
../storage/scheduler.go:167 storage.(*raftScheduler).Start.func2 { s.worker(ctx) }
../util/stop/stopper.go:198 stop.(*Stopper).RunWorker.func1 { f(ctx) }


Other goroutines holding locks:
goroutine 4922 lock 0xc4202a3840
../storage/timedmutex.go:92 storage.(*timedMutex).Lock { tm.mu.Lock() } <<<<<
../storage/replica.go:3142 storage.(*Replica).handleRaftReady { r.raftMu.Lock() }
../storage/store.go:3548 storage.(*Store).processReady { stats, err := r.handleRaftReady(IncomingSnapshot{}) }
../storage/scheduler.go:216 storage.(*raftScheduler).worker { s.processor.processReady(ctx, id) }
../storage/scheduler.go:167 storage.(*raftScheduler).Start.func2 { s.worker(ctx) }
../util/stop/stopper.go:198 stop.(*Stopper).RunWorker.func1 { f(ctx) }

goroutine 4922 lock 0xc4202ed100
../storage/timedmutex.go:92 storage.(*timedMutex).Lock { tm.mu.Lock() } <<<<<
../storage/store.go:3836 storage.(*Store).tryGetOrCreateReplica { repl.raftMu.Lock() }
../storage/store.go:3760 storage.(*Store).getOrCreateReplica { ) }
../storage/replica.go:4422 storage.(*Replica).acquireSplitLock { rightRng, created, err := r.store.getOrCreateReplica(ctx, split.RightDesc.RangeID, 0, nil) }
../storage/replica.go:4412 storage.(*Replica).maybeAcquireSplitMergeLock { return r.acquireSplitLock(ctx, &split.SplitTrigger) }
../storage/replica.go:4280 storage.(*Replica).processRaftCommand { if splitMergeUnlock := r.maybeAcquireSplitMergeLock(ctx, raftCmd); splitMergeUnlock != nil { }
../storage/replica.go:3434 storage.(*Replica).handleRaftReadyRaftMuLocked { if changedRepl := r.processRaftCommand(ctx, commandID, e.Term, e.Index, command); changedRepl { }
../storage/replica.go:3144 storage.(*Replica).handleRaftReady { return r.handleRaftReadyRaftMuLocked(inSnap) }
../storage/store.go:3548 storage.(*Store).processReady { stats, err := r.handleRaftReady(IncomingSnapshot{}) }
../storage/scheduler.go:216 storage.(*raftScheduler).worker { s.processor.processReady(ctx, id) }
../storage/scheduler.go:167 storage.(*raftScheduler).Start.func2 { s.worker(ctx) }
../util/stop/stopper.go:198 stop.(*Stopper).RunWorker.func1 { f(ctx) }




ERROR: exit status 2

1 runs completed, 1 failures, over 1s
context canceled
Makefile:260: recipe for target 'stress' failed
make: *** [stress] Error 1
```

### PR DESCRIPTION
**Pull request by petermattis**
Don't grab Replica.{mu,raftMu} during Store.Start as doing so violates
our lock ordering invariants.

Fixes #18298

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/store.go, line 1123 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18318#-KtRslzjwd6ObEDnPGEI:-KtRslzjwd6ObEDnPGEJ:b-hxbf37) ([raw file](https://github.com/cockroachdb/cockroach/blob/652add1eb15d5d8661aa346e495a478f53e71c24/pkg/storage/store.go#L1123)):*
> ```Go
> 			// violates our lock ordering invariants because we're currently holding
> 			// Store.mu.
> 			if err := rep.initRaftMuLockedReplicaMuLocked(&desc, s.Clock(), 0); err != nil {
> ```

The alternative would be to not grab `Store.mu` outside the loop and instead grab it before the call to `addReplicaInternaLocked` before. I went with this approach because I'm not sure if there are repercussions to not holding `Store.mu` for the lifetime of the loop.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18318)*

**Comment by tschottdorf** [comment]
Ah, our wires crossed (though I thought I'd assigned the issue to myself to prevent that from happening). Fine merging this one too, though my personal preference would be to acquire the correct locks even if we can get away without it, as done in #18320. Your call.

**Comment by petermattis** [comment]
Heh, you did self-assign. I was working on it on the train where I didn't have network connectivity. Thing to figure out is which approach is desirable. Let's move the discussion to your PR.

**Comment by petermattis** [comment]
Closed in favor of #18320.

**Pull request closed without merging**
