### PR TITLE
sql/*: round some floats in explain output and test results

### PR DESCRIPTION
**Pull request by dt**
This rounds some floats to fewer places of precision when they appear in row counts in EXPLAIN output and in some logic-test results.
This is done since rendering with more precision can sometimes cause those tests to fail when run on other platforms, such as ARM, which may fuse/round floating point operations differently, leading to small differences and failing the tests.

### CODE REVIEW

**Comment by otan** [comment]
how are we making sure we don't regress on this?
have we / are we putting ARM in CI?

**Comment by dt** [comment]
> how are we making sure we don't regress on this? do have we / are we putting ARM in CI?

Not at the moment. We probably should at some point, but for now this is the same as any other MacOS specific env behaviors, like toolchain resolution, build tags, link flags, etc in that it is only exercised on dev machines.

**Comment by dt** [comment]
Err, to clarify: (almost) all the code changed here *is* exercised in CI, on amd64. The part that only our M1 dev machines exercise is that that code produces the same result when they run it, which like any dev-machine only behavior is already only checked by those dev machines until we add Mac CIs.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75723#-:-Mul2fan4v_JaZaIZHur:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @otan)

___
*[pkg/sql/conn_executor_test.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75723#-Mul0vdoAFsWhqXRA_yp:-Mul0vdoAFsWhqXRA_yq:b-1506e4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7d6e2438496a6aaf68f697a21dffe3fd97f7af8/pkg/sql/conn_executor_test.go#L108)):*
> ```Go
> 	// Edit non-determinstic stack trace filenames from the message.
> 	actSafeRedactedMessage := strings.ReplaceAll(fileref.ReplaceAllString(
> 		redact.Sprintf("%+v", safeErr).Redact().StripMarkers(), "...$2:NN"), "asm_arm64", "asm_amd64")
> ```

[nit] Feels like it would be cleaner to just filter out those lines (or replace the name with `<hidden>.s` instead of "lying"

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75723)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan and @RaduBerinde)

___
*[pkg/sql/conn_executor_test.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75723#-Mul0vdoAFsWhqXRA_yp:-MulXpjJ4WnS-K4WDEZI:b6faumj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7d6e2438496a6aaf68f697a21dffe3fd97f7af8/pkg/sql/conn_executor_test.go#L108)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Feels like it would be cleaner to just filter out those lines (or replace the name with `<hidden>.s` instead of "lying"
</blockquote></details>

changed to replace both arch strings with scrubbed.

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
