### PR TITLE
sql: Improve handling of BIT(n) data type

### PR DESCRIPTION
**Pull request by nvb**
This change was prompted by certain inconsistencies I was seeing while working on `information_schema.columns`.

The first commit improves our parsing of the BIT column type. The new functionality is that:
- Writing BIT without a length is now properly equivalent to BIT(1)
- A non-positive bit length is now an error

The second commit actually uses the bit length to provide value width bounding, like STRING and BYTE ARRAY widths already do.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8326)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/parser/interval.go, line 25 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8326#-KONA6BmfnZKpZ8jd0ju:-KONA6BmfnZKpZ8jd0jv:160422853) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e55f122470813cf7083697950a8562ffb087be/sql/parser/interval.go#L25)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/util/duration"
> 
> 	"fmt"
> ```

wat

---

*[sql/sqlbase/table.go, line 1329 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8326#-KONAs4h63IHNAT9IXWE:-KONAs4h63IHNAT9IXWF:-294174021) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dbc9e144b4aea8174c2ff39ebc6a4974cb03115/sql/sqlbase/table.go#L1329)):*
> ```Go
> 				// flag on the column type, the best we can do here is conservatively
> 				// assume the varying bit type and error only on longer bit strings.
> 				msb := int32(0)
> ```

msb? these rows are short enough that more letters would be ok

---

*[sql/sqlbase/table.go, line 1331 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8326#-KONAkI3vYnFAsaKGN8x:-KONAkI3vYnFAsaKGN8y:-1877799610) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dbc9e144b4aea8174c2ff39ebc6a4974cb03115/sql/sqlbase/table.go#L1331)):*
> ```Go
> 				msb := int32(0)
> 				bits := uint64(*v)
> 				for ; bits != 0; msb++ {
> ```

`for bits := uint64(*v); ....`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8326#-:-KONBT7oge1LA0A-lcOd:1417088721)*

**Comment by nvanbenschoten** [comment]
TFTR!

---

Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/parser/interval.go, line 25 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8326#-KONA6BmfnZKpZ8jd0ju:-KONX3MIdLJ5aQV7LcSt:1664716498) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e55f122470813cf7083697950a8562ffb087be/sql/parser/interval.go#L25)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> wat
</details>
Noticed the messed up import order and didn't think it warranted a separate commit.

---

*[sql/sqlbase/table.go, line 1329 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8326#-KONAs4h63IHNAT9IXWE:-KONXO9DW75XI47Hq4zv:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dbc9e144b4aea8174c2ff39ebc6a4974cb03115/sql/sqlbase/table.go#L1329)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> msb? these rows are short enough that more letters would be ok
</details>
Done.

---

*[sql/sqlbase/table.go, line 1331 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8326#-KONAkI3vYnFAsaKGN8x:-KONXOnS_gVcgxg58TMU:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dbc9e144b4aea8174c2ff39ebc6a4974cb03115/sql/sqlbase/table.go#L1331)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> `for bits := uint64(*v); ....`?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8326#-:-KONXRLnS5vBZgySoJsp:-485616692)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/parser/interval.go, line 25 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8326#-KONA6BmfnZKpZ8jd0ju:-KONYdDALOw-PpM3mHx6:-2112802490) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e55f122470813cf7083697950a8562ffb087be/sql/parser/interval.go#L25)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Noticed the messed up import order and didn't think it warranted a separate commit.
</details>
Heh, yeah, that's fine. I was just musing out loud as to how this might've happened.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8326)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8326#-:-KOPt6_xBkD5dvBhSzYB:bnfp4nl)*

**Pull request merged**
