### PR TITLE
kvserver: implement basic raft info methods for RACv2

### PR DESCRIPTION
**Pull request by pav-kv**
Epic: CRDB-37515
Release note: none

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
nit: can you add the epic CRDB-37515.

:lgtm: 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129451#-:-O4rlpVU813Qt_cf1giU:b-tk2zhf)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv)

___
*[`pkg/raft/rawnode.go` line 449 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129451#-O4rl0_YEl5cih5lvAC-:-O4rl0_YEl5cih5lvAC0:b-yft8hc) ([raw file](https://github.com/cockroachdb/cockroach/blob/89e864615d4ed85c72e80d7487b0e24beb66eb36/pkg/raft/rawnode.go#L449)):*
> ```Go
> }
> 
> // Term returns the current term of this RawNode.
> ```

Is this the HardState.Term? Or the highest term of a leader that this node has seen? Can this regress on a restart? Trying to understand what this means.
A longer code comment could help.

**Review by sumeerbhola — APPROVED** [review]

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129451)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/raft/rawnode.go` line 449 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129451#-O4rl0_YEl5cih5lvAC-:-O4rr4Jn1I7mXNswYHv0:bsc5pb0) ([raw file](https://github.com/cockroachdb/cockroach/blob/89e864615d4ed85c72e80d7487b0e24beb66eb36/pkg/raft/rawnode.go#L449)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is this the HardState.Term? Or the highest term of a leader that this node has seen? Can this regress on a restart? Trying to understand what this means.
A longer code comment could help.
</blockquote></details>

This is just the current in-memory term. The `HardState.Term` in storage is updated soon after this term is updated. Correspondingly, the term can regress on restart.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129451)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv)

___
*[`pkg/raft/rawnode.go` line 449 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129451#-O4rl0_YEl5cih5lvAC-:-O4uMB_36pxxLnzDgzw1:buihbgt) ([raw file](https://github.com/cockroachdb/cockroach/blob/89e864615d4ed85c72e80d7487b0e24beb66eb36/pkg/raft/rawnode.go#L449)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

This is just the current in-memory term. The `HardState.Term` in storage is updated soon after this term is updated. Correspondingly, the term can regress on restart.
</blockquote></details>

Could you update the comment to clarify. I realize this may be obvious to folks with better understanding of Raft, but no harm in making the public methods more accessible to readers.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129451)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/raft/rawnode.go` line 449 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129451#-O4rl0_YEl5cih5lvAC-:-O4vmkyc-JW-deWqHD2O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/89e864615d4ed85c72e80d7487b0e24beb66eb36/pkg/raft/rawnode.go#L449)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Could you update the comment to clarify. I realize this may be obvious to folks with better understanding of Raft, but no harm in making the public methods more accessible to readers.
</blockquote></details>

Done.

**Comment by pav-kv** [comment]
bors r=sumeerbhola

**Pull request merged**
