### PR TITLE
Add expected RangeDescriptor to AdminChangeReplicas and adopt

### PR DESCRIPTION
**Pull request by ajwerner**
This PR comes in two commits. The first updates the roachpb api and the second adopts the update. This is the first of the PRs which will address #36025. See the commit messages for more details.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36244)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/internal/client/db.go, line 509 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36244#-Lb9bl6G2vi5l2HnDreg:-Lb9bl6G2vi5l2HnDreh:b-almzw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/800146f74aef83befa77be416294c0015ecefa3a/pkg/internal/client/db.go#L509)):*
> ```Go
> 		return nil, err
> 	}
> 	responses := b.RawResponse().Responses
> ```

nit: I would change this to be `b.response.Responses`, which is what `Batch.fillResults` uses. This is all a little bit of an abuse because we should be generating this response in `Batch.fillResults` instead given that this is not a "raw" request.

Another option would be to add another response variant to `Result`. I'm not sure what type you'd give it (`other interface{}`?), but would fit in with the current approach of some responses populating `Result.Rows` and others populating `Result.Keys`. Then you could populate this in `Batch.fillResults` and pull the result in `db.AdminChangeReplicas` from `getOneResult`.
___
*[pkg/roachpb/api.proto, line 688 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36244#-Lb9fTjR-t5peB_prqUk:-Lb9fTjR-t5peB_prqUl:b-pqwtms) ([raw file](https://github.com/cockroachdb/cockroach/blob/800146f74aef83befa77be416294c0015ecefa3a/pkg/roachpb/api.proto#L688)):*
> ```protobuf
>   RequestHeader header = 1 [(gogoproto.nullable) = false, (gogoproto.embed) = true];
>   ReplicaChangeType change_type = 2;
>   repeated ReplicationTarget targets = 3 [(gogoproto.nullable) = false];
> ```

We should explain the semantics of this field. Critically, mention that the sequence of changes will can be partially applied if it races with other replica movement, but will always be applied in order.

You might also consider adding a test similar to `TestConcurrentAdminChangeReplicasRequests` that constructs a sequence of replication targets such that there are multiple valid histories for two racing `AdminChangeReplicasRequest`s. Something like:

```
origDesc = 1
actor 1: expDesc: 1, targets: [2, 3, 4]
actor 2: expDesc: 2, targets: [3, 2, 1]
```
You'd then assert that the final target is either `1` or `4`.
___
*[pkg/storage/client_replica_test.go, line 2020 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36244#-Lb9des_A44380eUiP4n:-Lb9des_A44380eUiP4o:bir6o0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/800146f74aef83befa77be416294c0015ecefa3a/pkg/storage/client_replica_test.go#L2020)):*
> ```Go
> 		if err == nil {
> 			numSuccesses++
> 		}
> ```

Let's assert that the only error we get is what we expect when the expected desc doesn't match.
___
*[pkg/storage/replica.go, line 1223 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36244#-Lb9f5qS3yNsBLMrvfEl:-Lb9f5qS3yNsBLMrvfEm:bvkwd4u) ([raw file](https://github.com/cockroachdb/cockroach/blob/800146f74aef83befa77be416294c0015ecefa3a/pkg/storage/replica.go#L1223)):*
> ```Go
> 		}
> 		for _, target := range tArgs.Targets {
> 			expDesc, err = r.ChangeReplicas(
> ```

Could you add a comment about why we set `expDesc` to the result of each previous step?
___
*[pkg/storage/replica_command.go, line 1092 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36244#-Lb9fuoa59eXaFa04Vch:-Lb9fuoa59eXaFa04Vci:b-o5ie1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/800146f74aef83befa77be416294c0015ecefa3a/pkg/storage/replica_command.go#L1092)):*
> ```Go
> 	}
> 
> 	// After each call to the
> ```

This needs some love.
___
*[pkg/storage/replica_command.go, line 1116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36244#-Lb9fyqsE_MdO-Tk7gf7:-Lb9fyqsE_MdO-Tk7gf8:b-oa8b3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/800146f74aef83befa77be416294c0015ecefa3a/pkg/storage/replica_command.go#L1116)):*
> ```Go
> 
> 	// updateRangeDesc updates the passed RangeDescriptor following the successful
> 	// completion of an AdminChangeReplicasRequest with	the single provided target
> ```

Strange tab here.

**Review by ajwerner — COMMENTED** [review]
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36244#-:-LbACUpTBPXsQVB4ABLU:b-9qdoz3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/internal/client/db.go, line 509 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36244#-Lb9bl6G2vi5l2HnDreg:-Lb9lzwFAVCRe6JhqtAt:b-4p04h2) ([raw file](https://github.com/cockroachdb/cockroach/blob/800146f74aef83befa77be416294c0015ecefa3a/pkg/internal/client/db.go#L509)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: I would change this to be `b.response.Responses`, which is what `Batch.fillResults` uses. This is all a little bit of an abuse because we should be generating this response in `Batch.fillResults` instead given that this is not a "raw" request.

Another option would be to add another response variant to `Result`. I'm not sure what type you'd give it (`other interface{}`?), but would fit in with the current approach of some responses populating `Result.Rows` and others populating `Result.Keys`. Then you could populate this in `Batch.fillResults` and pull the result in `db.AdminChangeReplicas` from `getOneResult`.
</blockquote></details>

I went with the first suggestion. Muddying up `Results` further didn't feel clean .
___
*[pkg/roachpb/api.proto, line 688 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36244#-Lb9fTjR-t5peB_prqUk:-LbA-mBkERM_IytsnhCA:b-la9uck) ([raw file](https://github.com/cockroachdb/cockroach/blob/800146f74aef83befa77be416294c0015ecefa3a/pkg/roachpb/api.proto#L688)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We should explain the semantics of this field. Critically, mention that the sequence of changes will can be partially applied if it races with other replica movement, but will always be applied in order.

You might also consider adding a test similar to `TestConcurrentAdminChangeReplicasRequests` that constructs a sequence of replication targets such that there are multiple valid histories for two racing `AdminChangeReplicasRequest`s. Something like:

```
origDesc = 1
actor 1: expDesc: 1, target: [2, 3, 4]
actor 2: expDesc: 2, target: [3, 2, 1]
```
You'd then assert that the final target is either `1` or `4`.
</blockquote></details>

I added this but it needs to be 
```
origDesc = 1
actor 1: expDesc: 1, target: [2, 3, 4]
actor 2: expDesc: 2, target: [3, 5]
```
Because it's an error to add an existing entry. 
___
*[pkg/storage/client_replica_test.go, line 2020 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36244#-Lb9des_A44380eUiP4n:-LbA0eOoEPqeiWYdttBM:bssc1vc) ([raw file](https://github.com/cockroachdb/cockroach/blob/800146f74aef83befa77be416294c0015ecefa3a/pkg/storage/client_replica_test.go#L2020)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's assert that the only error we get is what we expect when the expected desc doesn't match.
</blockquote></details>

Done. It also turns out this test was too pessimistic because it was written when I had the racing goroutines each do a read before they did their write but in that scenario multiple can succeed. It'd be fancy if I built some code to verify that valid history occurred. For now I made it such that it guarantees that only  one succeeds and that it succeeds completely. 

I also added the test you suggested above.
___
*[pkg/storage/replica_command.go, line 1092 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36244#-Lb9fuoa59eXaFa04Vch:-LbABBHN7uz8pwwztL0v:b-6y7oe1) ([raw file](https://github.com/cockroachdb/cockroach/blob/800146f74aef83befa77be416294c0015ecefa3a/pkg/storage/replica_command.go#L1092)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This needs some love.
</blockquote></details>

Actually just stale, removed.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 13 files at r3, 11 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36244#-:-LbAXMmHC1z8K78MYyWp:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Pull request merged**
