### PR TITLE
sql: fix usage of streamer with multiple column families

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, we had the following bug in how the streamer was used under the following conditions:
- we're looking up into a table with at least 3 column families
- not all column families are needed, so we end up creating "family-specific" spans (either Gets or Scans - the latter is possible when multiple contiguous families are needed)
- the streamer is used with OutOfOrder mode (which is the case for index joins when `MaintainOrdering` is `false` and for lookup joins when `MaintainLookupOrdering` is `false`)
- the index we're looking up into is split across multiple ranges.

In such a scenario we could end up with KVs from different SQL rows being intertwined because the streamer could execute a separate BatchRequest for those rows, and in case `TargetBytes` limit estimate was insufficient, we'd end up creating "resume" batches, at which point the "results" stream would be incorrect. Later, at the SQL fetcher level this could either manifest as an internal "non-nullable column with no value" error or with silent incorrect output (we'd create multiple output SQL rows from a true single one).

This problem is now fixed by asking the streamer to maintain the ordering of the requests whenever we have `SplitFamilyIDs` with more than one family, meaning that we might end up creating family-specific spans.

Note that the non-streamer code path doesn't suffer from this problem because there we only parallelize BatchRequests when neither `TargetBytes` nor `MaxSpanRequestKeys` limits are set, which is the requirement for having "resume" batches.

Addresses: #113013.
Epic: None

Release note (bug fix): CockroachDB previously could incorrectly evaluate lookup and index joins into tables with at least 3 column families in some cases (either "non-nullable column with no value" internal error would occur or the query would return incorrect results), and this is now fixed. The bug was introduced in 22.2.

### CODE REVIEW

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113019)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`-- commits` line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113019#-NhbtV4e1uvZdN1_q9tK):*
I think this reasoning only applies when the _table_ has 2 column families, but `MaxKeysPerRow` checks if the _index_ has 2 column families.
___
*[`pkg/sql/colfetcher/index_join.go` line 572 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113019#-NhbuV3SBZJ11AUmakTx:-NhbuV3SBZJ11AUmakTy:bpef05y) ([raw file](https://github.com/cockroachdb/cockroach/blob/14af73099e6743f7dc7f97bd72d2ee149fdc93fc/pkg/sql/colfetcher/index_join.go#L572)):*
> ```Go
> 			}
> 		}
> 		maintainOrdering := spec.MaintainOrdering || (len(spec.SplitFamilyIDs) > 0 && spec.FetchSpec.MaxKeysPerRow >= 3)
> ```

Why can't we check that `len(spec.SplitFamilyIDs) > 1` instead? Doesn't the 1-family case prevent interleaving no matter how many families there are in the table / index?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113019)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @michae2)

___
*[`-- commits` line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113019#-NhbtV4e1uvZdN1_q9tK):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I think this reasoning only applies when the _table_ has 2 column families, but `MaxKeysPerRow` checks if the _index_ has 2 column families.
</blockquote></details>

Nice catch, fixed with your other suggestion.
___
*[`pkg/sql/colfetcher/index_join.go` line 572 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113019#-NhbuV3SBZJ11AUmakTx:-Nhc6FlE9BAuVf-pBTBo:bmmxh9z) ([raw file](https://github.com/cockroachdb/cockroach/blob/14af73099e6743f7dc7f97bd72d2ee149fdc93fc/pkg/sql/colfetcher/index_join.go#L572)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Why can't we check that `len(spec.SplitFamilyIDs) > 1` instead? Doesn't the 1-family case prevent interleaving no matter how many families there are in the table / index?
</blockquote></details>

Yes, we can, and it's a simpler condition, done, thanks.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice fix!

> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113019#-:-NhcDnU99xLPx09tKiuT:b-46lt7k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`-- commits` line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113019#-NhcCBZo3lx_xDPH7WmE):*
[nit] This means "limits being set" is the requirement for resume batches, right?
___
*[`pkg/sql/rowexec/joinreader.go` line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113019#-NhcDOjW708K5t3yZkZy:-NhcCxtEEiG8_kx5zYoY:btep6zl) ([raw file](https://github.com/cockroachdb/cockroach/blob/f30e07af6a00a21a381f915bb8c90943a3a0201e/pkg/sql/rowexec/joinreader.go#L138)):*
> ```Go
> 		// maintainOrdering indicates whether the ordering of the input stream
> 		// needs to be maintained AND that we rely on the streamer for that. We
> 		// currently rely on the streamer in the following cases:
> ```

[nit] This comment seems stale - (3) is a case where we _don't_ rely on the streamer.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113019)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @michae2)

___
*[`-- commits` line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113019#-NhcCBZo3lx_xDPH7WmE):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] This means "limits being set" is the requirement for resume batches, right?
</blockquote></details>

Yes, I'll reword it.
___
*[`pkg/sql/rowexec/joinreader.go` line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113019#-NhcDOjW708K5t3yZkZy:-NhcUFkl8wTolatUtUs1:b-u5rghb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f30e07af6a00a21a381f915bb8c90943a3a0201e/pkg/sql/rowexec/joinreader.go#L138)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] This comment seems stale - (3) is a case where we _don't_ rely on the streamer.
</blockquote></details>

Hm, it seems current to me. When we have a lookup join, we do rely on the streamer for the ordering only when `spac.MaintainLookupOrdering` is set, regardless of `spec.MaintainOrdering` value (which actually must be set when `MaintainLookupOrdering` is set). Am I missing something?

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113019)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2 and @yuzefovich)

___
*[`pkg/sql/rowexec/joinreader.go` line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113019#-NhcDOjW708K5t3yZkZy:-NhcVtIA44y_kker91TO:b-yg63sb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f30e07af6a00a21a381f915bb8c90943a3a0201e/pkg/sql/rowexec/joinreader.go#L138)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, it seems current to me. When we have a lookup join, we do rely on the streamer for the ordering only when `spac.MaintainLookupOrdering` is set, regardless of `spec.MaintainOrdering` value (which actually must be set when `MaintainLookupOrdering` is set). Am I missing something?
</blockquote></details>

Ah, no, I just confused `MaintainOrdering` with `MaintainLookupOrdering`.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113019)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @michae2)

___
*[`pkg/sql/rowexec/joinreader.go` line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113019#-NhcDOjW708K5t3yZkZy:-NhcX83d57tyhpjPBLQf:brnws8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/f30e07af6a00a21a381f915bb8c90943a3a0201e/pkg/sql/rowexec/joinreader.go#L138)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Ah, no, I just confused `MaintainOrdering` with `MaintainLookupOrdering`.
</blockquote></details>

No worries. I just added another commit to introduce a session variable - I think it'd be nice to backport both together. PTAL.

**Review by DrewKimball — APPROVED** [review]
:lgtm: It'd be nice to have a way to force ordering for the lookup-join strategy as well, but I can also just do that elsewhere.

> Reviewed 4 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113019#-:-NhceGrG27mjNehUJk6B:brj3xcl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Review by yuzefovich — COMMENTED** [review]
That seems somewhat more orthogonal to the fix than what the second commit does here, so I think it could be done separately.

TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113019#-:-NhcgOoS6GqsNF5R-upT:b-z5mj1c)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @michae2)

**Pull request merged**
