### PR TITLE
clusterversion: remove 22.2 version key

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### clusterversion: remove 22.2 version key

Remove the no-longer-supported 22.2 version key and all associated
code.

Epic: none
Release note: None

#### scplan: remove 22.2-only code

Epic: none
Release note: None

### CODE REVIEW

**Review by celiala — COMMENTED** [review]
i think we want to leave the V23_1 check in scalars.go as-is, right?.
`return version.IsActive(clusterversion.V23_1)`

everything else LGTM

> Reviewed 34 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114122#-:-NipOowH-DU815PUiMSk:b-3mtp66)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[`pkg/clusterversion/cockroach_versions.go` line 196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114122#-NipNP3s2l5VImWm_T-9:-NipNP3tAbBKTFNu-N92:bjwa7hh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fdc79b95dcff0cc85cf8b3c8bb21431ce97b8fd/pkg/clusterversion/cockroach_versions.go#L196)):*
> ```Go
> 	// TODO_Delete_V22_2 is CockroachDB v22.2. It's used for all v22.2.x patch releases.
> 	TODO_Delete_V22_2
> ```

:tada: 
___
*[`pkg/kv/kvserver/loqrecovery/version.go` line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114122#-NipNeys5cluJpGqi7i3:-NipNeys5cluJpGqi7i4:b-lg1gss) ([raw file](https://github.com/cockroachdb/cockroach/blob/fecef99ff55c32576e0422d974f9ab9dbfc70aaa/pkg/kv/kvserver/loqrecovery/version.go#L63)):*
> ```Go
> // loaded from legacy format files which contained no version info or collected
> // from old clusters.
> var legacyInfoFormatVersion = roachpb.Version{Major: 22, Minor: 2, Internal: 0}
> ```

Will `legacyInfoFormatVersion` forever be mapped to 22.2.0? or will this need to be bumped whenever we do old gate cleanup?
___
*[`pkg/sql/schemachanger/screl/scalars.go` line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114122#-NipOZ1U08Gx5O16L9Jj:-NipOZ1U08Gx5O16L9Jk:b6f2740) ([raw file](https://github.com/cockroachdb/cockroach/blob/fecef99ff55c32576e0422d974f9ab9dbfc70aaa/pkg/sql/schemachanger/screl/scalars.go#L134)):*
> ```Go
> 		*scpb.CompositeTypeAttrType, *scpb.CompositeTypeAttrName:
> 		// These elements need v23.1 so they can be used without checking any version gates.
> 		return true
> ```

i think we want to leave this check as-is, right?
`return version.IsActive(clusterversion.V23_1)`

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114122#-:-Nipsrz-DbQW1bY1TpdL:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @celiala)

___
*[`pkg/kv/kvserver/loqrecovery/version.go` line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114122#-NipNeys5cluJpGqi7i3:-Nips6SL6V8G2FhigD7G:bik2u4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/fecef99ff55c32576e0422d974f9ab9dbfc70aaa/pkg/kv/kvserver/loqrecovery/version.go#L63)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

Will `legacyInfoFormatVersion` forever be mapped to 22.2.0? or will this need to be bumped whenever we do old gate cleanup?
</blockquote></details>

Not very familiar with this code but sounds like it's testing something specific about 22.2, feels like it should just be removed. 
___
*[`pkg/sql/schemachanger/screl/scalars.go` line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114122#-NipOZ1U08Gx5O16L9Jj:-NipsW1QDyZ1Y1pn0YP1:b-d5xx0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/fecef99ff55c32576e0422d974f9ab9dbfc70aaa/pkg/sql/schemachanger/screl/scalars.go#L134)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

i think we want to leave this check as-is, right?
`return version.IsActive(clusterversion.V23_1)`
</blockquote></details>

`V23_1` is `MinSupported`, this would never be false. (we'd need to be on a pre-23.1 version which is no longer supported)

**Review by celiala — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114122)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[`pkg/kv/kvserver/loqrecovery/version.go` line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114122#-NipNeys5cluJpGqi7i3:-NipwZn673Cy-wtrCFv4:bmxel94) ([raw file](https://github.com/cockroachdb/cockroach/blob/fecef99ff55c32576e0422d974f9ab9dbfc70aaa/pkg/kv/kvserver/loqrecovery/version.go#L63)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Not very familiar with this code but sounds like it's testing something specific about 22.2, feels like it should just be removed.
</blockquote></details>

(haven't dug into it's usage either / not sure? i'm also fine with the proposed change as-is)
___
*[`pkg/sql/schemachanger/screl/scalars.go` line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114122#-NipOZ1U08Gx5O16L9Jj:-NipwqI0A7KgRdLQ3bc0:b-iqrojd) ([raw file](https://github.com/cockroachdb/cockroach/blob/fecef99ff55c32576e0422d974f9ab9dbfc70aaa/pkg/sql/schemachanger/screl/scalars.go#L134)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`V23_1` is `MinSupported`, this would never be false. (we'd need to be on a pre-23.1 version which is no longer supported)
</blockquote></details>

ah, yes. cool, makes sense, thanks!

**Pull request merged**
