### PR TITLE
sql: fix dropping table in CTAS/materialized view rollback

### LINKED ISSUE #54186: CTAS statement that fails still seems to create a descriptor
**Describe the problem**

The following sql statement taken from `pkg/sql/logictest/testdata/logic_test/create_as` fails but it seems to have still created a table named `foo7`.

```sql
statement error generate insert row: null value in column "x" violates not-null constraint
CREATE TABLE foo7 (x PRIMARY KEY) AS VALUES (1), (NULL);
```

**To Reproduce**

1. Check out this branch: https://github.com/spaskob/cockroach/tree/validate-builtin
2. Run logictest `make testlogic PKG=./pkg/sql TESTS=TestLogic/local-vec-off/create_as`
3. It should fail with error message:
```
        --- FAIL: TestLogic/local-vec-off/create_as (2.17s)
            logic.go:2709:
                testdata/logic_test/create_as:360: error while processing
            logic.go:2709: descriptor validation failed:
                desc &tabledesc.Mutable{
                    Immutable: tabledesc.Immutable{
                        TableDescriptor: descpb.TableDescriptor{
                            Name:                    "foo7",
...
                }
                : parentID 52 does not exist
```

### PR DESCRIPTION
**Pull request by thoszhang**
When we were dropping the table while rolling back `CREATE TABLE AS` or
`CREATE MATERIALIZED VIEW`, we neglected to move the table from the ADD
state to the DROP state. This is currently blocking us from using logic
tests for testing `DROP DATABASE CASCADE`, because if the descriptor's
parent database is dropped, we'll produce a spurious error from
validation about a missing parent descriptor. The bug also probably
leads to other subtle problems with draining leases, etc., though the GC
job should be able to handle such descriptors, at least. This PR fixes
the bug.

Fixes #54186.
Touches #53810.

Release note (bug fix): Fixed a bug where upon failure of `CREATE TABLE
AS` or `CREATE MATERIALIZED VIEW` tables would be left in an invalid
non-public state until GC instead of being marked as dropped, possibly
causing spurious validation failures. The bug was introduced in earlier
20.2 prereleases.

### CODE REVIEW

**Comment by lucy-zhang** [comment]
@spaskob I ran the `create_as` logic tests with the validation in #53810 and this patch, and they passed.

**Comment by spaskob** [comment]
@lucy-zhang that's great - thanks for the update!

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55272#-:-MJ22I2b62MwKqRYbV-B:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/sql/schema_changer_test.go, line 497 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55272#-MJ21Nsd-RQ4NwK6fU9U:-MJ21Nsd-RQ4NwK6fU9V:b-clz1og) ([raw file](https://github.com/cockroachdb/cockroach/blob/93cbcfcbb573ef4400d90300d682742e3ed080bf/pkg/sql/schema_changer_test.go#L497)):*
> ```Go
> 	var desc descpb.Descriptor
> 	require.NoError(t, protoutil.Unmarshal(descBytes, &desc))
> 	viewDesc := desc.GetTable()
> ```

you can add a `nolint:descriptormarshal` to defeat the linter if you'd like, literally just merged that yesterday. Alternatively you can read the MVCC timestamp using `crdb_internal_mvcc_timestamp` and then `sql.ParseHLC` and pass that timestamp to the relevant function.

**Review by thoszhang — COMMENTED** [review]
TFTR

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55272#-:-MJ2k7LD5Huc204cJU04:b-4as1hm)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

___
*[pkg/sql/schema_changer_test.go, line 497 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55272#-MJ21Nsd-RQ4NwK6fU9U:-MJ2k657DK9KIts2kpPE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/93cbcfcbb573ef4400d90300d682742e3ed080bf/pkg/sql/schema_changer_test.go#L497)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

you can add a `nolint:descriptormarshal` to defeat the linter if you'd like, literally just merged that yesterday. Alternatively you can read the MVCC timestamp using `crdb_internal_mvcc_timestamp` and then `sql.ParseHLC` and pass that timestamp to the relevant function.
</blockquote></details>

Done.

**Pull request merged**
