### PR TITLE
kvserver: replica load distribution metric

### PR DESCRIPTION
**Pull request by kvoli**
This PR adds two histograms, tracking the percentiles of replica CPU time and replica Batch requests received. Previously, there was only point in time insight into either distribution via hotranges. This change enables historical timeseries tracking via the metric `rebalancing.replicas.cpunanospersecond` for CPU and `rebalancing.replicas.queriespersecond` for Batch Requests.

Informs: #98255

### CODE REVIEW

**Comment by kvoli** [comment]
Going to hold off requesting reviews until https://github.com/cockroachdb/cockroach/issues/98266 is settled.

**Comment by kvoli** [comment]
@aadityasondhi mentioned that they expect https://github.com/cockroachdb/cockroach/issues/98266 to be resolved before GA. I'm going to go ahead and req reviews - noting that currently the timseries has periodic gaps.

**Comment by kvoli** [comment]
Reverted to draft. I'm going to rework the approach here using a ManualHistogram after some changes are made to ManualHistogram.

From @aadityasondhi 

> For histograms such as the one above, I would suggest using ManualWindowHistogram. I do recognize that the current interface is cumbersome and I will rework it to make it more easily usable. When you create this histogram, you will be required to provide the promised update interval. The poller will report the last known value of these histograms as long as T-t < update interval. To avoid race conditions such as the one in this issue, we will allow for 1 missed update but start reporting 0 if the poller misses twice in a row.

**Comment by kvoli** [comment]
I took a pretty hacky path to use the ManualHistogram, with the assumption that we will update the iface in 23.2 - lmk what you think @aadityasondhi.

**Review by aadityasondhi — COMMENTED** [review]
Only reviewed the first commit (related to the refactoring of the manual histogram), but overall it looks great! Some of the ideas here are what I had in mind for the refactor in https://github.com/cockroachdb/cockroach/issues/98622. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98267#-:-NRi3DvbDEe_dqK--4EQ:b-9sy57h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist)

**Comment by kvoli** [comment]
@andrewbaptist, could you review the last 3 commits? They are adding two metrics using the histogram modified in c1.

**Review by andrewbaptist — APPROVED** [review]
:lgtm: Thanks for getting this in, this will be useful to see as we continue to make improvements to the allocator.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98267#-:-NRofMeg1_UsRBZtdWFK:b5086yl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/metrics.go` line 363 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98267#-NRobhvtA-NZ1efxCmKD:-NRobhvtA-NZ1efxCmKE:bmsmn0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/88ddb0bbefb8ddd08aabc214c186f51b34d64e93/pkg/kv/kvserver/metrics.go#L363)):*
> ```Go
> 		Unit:        metric.Unit_NANOSECONDS,
> 	}
> 	metaAverageReplicaCPUNanosPerSecond = metric.Metadata{
> ```

nit: The name is confusing. In general average for a histogram is confusing since there are two different ways it could be interpreted: 1) average across replicas, 2) average across time. Maybe something like metaRecentReplicaCPUNanosPerSecond. I think part of the problem is that it is just a complex topic because of the two dimensions. Also, can you add a comment to clarify if this applies to all replicas including quiesced ones. I think it does.
___
*[`pkg/kv/kvserver/metrics.go` line 2376 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98267#-NRob9T55c1v6T5MAwyT:-NRob9T55c1v6T5MAwyU:bt9o7fu) ([raw file](https://github.com/cockroachdb/cockroach/blob/88ddb0bbefb8ddd08aabc214c186f51b34d64e93/pkg/kv/kvserver/metrics.go#L2376)):*
> ```Go
> 		AverageWriteBytesPerSecond: metric.NewGaugeFloat64(metaAverageWriteBytesPerSecond),
> 		AverageReadBytesPerSecond:  metric.NewGaugeFloat64(metaAverageReadBytesPerSecond),
> 		AverageCPUNanosPerSecond:   metric.NewGaugeFloat64(metaAverageCPUNanosPerSecond),
> ```

nit: Is this stat redundant with the AverageReplicaCPUNanosPerSecond now? If so can we remove it? If it is still necessary since ManualHistograms can't be used for computing this average just add a short comment why not.

**Review by kvoli — COMMENTED** [review]
TYFTR

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98267#-:-NS6Hudv7QdQX3x23ePV:b-80sls6)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist and @kvoli)

___
*[`pkg/kv/kvserver/metrics.go` line 363 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98267#-NRobhvtA-NZ1efxCmKD:-NS6HEuF2K-y1JaDEped:b-bl8o5q) ([raw file](https://github.com/cockroachdb/cockroach/blob/88ddb0bbefb8ddd08aabc214c186f51b34d64e93/pkg/kv/kvserver/metrics.go#L363)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: The name is confusing. In general average for a histogram is confusing since there are two different ways it could be interpreted: 1) average across replicas, 2) average across time. Maybe something like metaRecentReplicaCPUNanosPerSecond. I think part of the problem is that it is just a complex topic because of the two dimensions. Also, can you add a comment to clarify if this applies to all replicas including quiesced ones. I think it does.
</blockquote></details>

Added comment to clarify it is for all replicas and renamed to `recent...`.
___
*[`pkg/kv/kvserver/metrics.go` line 2376 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98267#-NRob9T55c1v6T5MAwyT:-NS6HLIN4jQFTG3IZDBT:b4odsk5) ([raw file](https://github.com/cockroachdb/cockroach/blob/88ddb0bbefb8ddd08aabc214c186f51b34d64e93/pkg/kv/kvserver/metrics.go#L2376)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: Is this stat redundant with the AverageReplicaCPUNanosPerSecond now? If so can we remove it? If it is still necessary since ManualHistograms can't be used for computing this average just add a short comment why not. 
</blockquote></details>

It is however I'd rather not break dependencies (lots of tests, probably users and definitely UI) in this PR, since I intend to backport to 23.1.

**Pull request merged**
