### PR TITLE
changefeedccl: Treat memory monitor errors as retryable.

### PR DESCRIPTION
**Pull request by miretskiy**
Treat memory errors as retryable when ingesting new events,
just like we treat such errors as retryable when emitting
them to the sink.

Release Notes: Changefeeds can better handle slow or unavailable
sinks by treating "memory exceeded" errors as retryable.

### CODE REVIEW

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64744)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @miretskiy)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/64744#-M_0vBxX1-CplkH9hEgQ:-M_0vBxX1-CplkH9hEgR:b-61dhkq) (no related file):*
A question you raised earlier but I can't remember if we came to an answer to: When we hit this error, will we drain what is in the buffer before completely failing?

---
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 341 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64744#-M_0u9yn1uEBs90oLjbS:-M_0u9yn1uEBs90oLjbT:b-19gtpx) ([raw file](https://github.com/cockroachdb/cockroach/blob/16957cc6d0117ad0c0692a72d958acee1d8cba34/pkg/ccl/changefeedccl/changefeed_processors.go#L341)):*
> ```Go
> }
> 
> type errorWrapperEventBuffer struct {
> ```

I assume this lives here rather than in kvfeed/buffer.go because MarkRetriableError lives in this package?
___
*[pkg/ccl/changefeedccl/kvfeed/kv_feed.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64744#-M_0ueY17v9wOYqQ-p7j:-M_0ueY17v9wOYqQ-p7k:b-y1afsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/16957cc6d0117ad0c0692a72d958acee1d8cba34/pkg/ccl/changefeedccl/kvfeed/kv_feed.go#L45)):*
> ```Go
> 	Targets            jobspb.ChangefeedTargets
> 	Sink               EventBufferWriter
> 	EventBufferFactory func() EventBuffer
> ```

I might have missed it, is there a reason we need a factory here rather than putting an EventBuffer right in this struct?

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64744)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/64744#-M_0vBxX1-CplkH9hEgQ:-M_1DU6d1KOjTB1EyVvI:bg8mayi) (no related file):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

A question you raised earlier but I can't remember if we came to an answer to: When we hit this error, will we drain what is in the buffer before completely failing?
</blockquote></details>

From what I can see, we will not process anything left in the memory buffers, but we will call MoveToDraining on the processor.. I don't think it kinda matters tbh - I mean, it'd be nice not to waste work, but I don't think we can help that.

---
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 341 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64744#-M_0u9yn1uEBs90oLjbS:-M_1CwkG7cloWuA20cJH:bwmbrbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/16957cc6d0117ad0c0692a72d958acee1d8cba34/pkg/ccl/changefeedccl/changefeed_processors.go#L341)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I assume this lives here rather than in kvfeed/buffer.go because MarkRetriableError lives in this package?
</blockquote></details>

You're exactly right.  I was kinda going back and forth on this.  On one hand, moving errors to changefeedbase sort of makes sense.  On the other hand, keeping things where they are and creating "error wrapper" event buffer is a bit more consistent with errorWrapperSink.   I don't know.  I could go either way. WDYT?
___
*[pkg/ccl/changefeedccl/kvfeed/kv_feed.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64744#-M_0ueY17v9wOYqQ-p7j:-M_1Cr3rA4V2n2Tb2w_j:bohjtvs) ([raw file](https://github.com/cockroachdb/cockroach/blob/16957cc6d0117ad0c0692a72d958acee1d8cba34/pkg/ccl/changefeedccl/kvfeed/kv_feed.go#L45)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I might have missed it, is there a reason we need a factory here rather than putting an EventBuffer right in this struct?
</blockquote></details>

We create separate event buffer per range.

**Review by miretskiy — COMMENTED** [review]
@stevendanna FYI: I changed memory limit test a bit and removed sinkless feeds.
Basically, it's a lot of hassle to try to get it to work for both enterprise and sinkless now that the
enterprise treats those memory errors as retryable, while sinkless doesn't.   This test failed on CI, primarily because
of that difference.  We can re-intro sinkless test (though I'm not too sure it adds that much) later, after my testfeed refactor goes in.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64744#-:-M_1PWbc3Hf_HBG17Xpl:bz6lxau)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @stevendanna)

**Comment by miretskiy** [comment]
@stevendanna ready for another look.

**Review by stevendanna — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64744)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @miretskiy)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/64744#-M_0vBxX1-CplkH9hEgQ:-M_MCMMW1QUC6Epm89_Y:bossxj9) (no related file):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

From what I can see, we will not process anything left in the memory buffers, but we will call MoveToDraining on the processor.. I don't think it kinda matters tbh - I mean, it'd be nice not to waste work, but I don't think we can help that.
</blockquote></details>

:+1: I agree. The big benefit here is being able to continue at all.

---
*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/64744#-M_MUSSj4Ef7jykl5OSW:-M_MUSSj4Ef7jykl5OSX:b16zeod) (no related file):*
Overall I think retrying these errors makes sense.  Thanks for pushing this forward. Marking approved as my previous issues were addressed, but note that Jordan's comment is probably worth addressing. 

>  The memory monitor errors can come in several forms, and I don't think they're necessarily always truly safe to retry.

Do you have more of a pointer here? I reviewed the memory monitor code and it appears we will always get some variation on a NewBudgetExceededError so it isn't clear to me how we would distinguish errors that are unsafe to retry.

---
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 341 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64744#-M_0u9yn1uEBs90oLjbS:-M_MREdhCVnia67o1BpU:b-d53jb5) ([raw file](https://github.com/cockroachdb/cockroach/blob/16957cc6d0117ad0c0692a72d958acee1d8cba34/pkg/ccl/changefeedccl/changefeed_processors.go#L341)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

You're exactly right.  I was kinda going back and forth on this.  On one hand, moving errors to changefeedbase sort of makes sense.  On the other hand, keeping things where they are and creating "error wrapper" event buffer is a bit more consistent with errorWrapperSink.   I don't know.  I could go either way. WDYT?
</blockquote></details>

I think it is fine here. Let's leave any refactoring for follow-ups since we want to backport this.

**Comment by jordanlewis** [comment]
> Do you have more of a pointer here? I reviewed the memory monitor code and it appears we will always get some variation on a NewBudgetExceededError so it isn't clear to me how we would distinguish errors that are unsafe to retry.

No particular pointer. Just wanted to point out that being able to retry on these errors was likely not part of the original design constraints of the memory monitoring library, so I just wanted to recommend proceeding with caution and tests.

> Where we can improve is to perhaps add focused tests to verify that reserved memory is released eventually -- but that can be done separately, imo.

Fine by me.

**Pull request merged**
