### PR TITLE
doctor: add --dump-sql and --verbose flags

### LINKED ISSUE #62459: sql: tool to inject descriptors from a debug.zip into a cluster or a demo
We semi-frequently see problems with schema descriptors that require us to analyze debug.zips and provide commands to clear the corruption. One problem is that we don't have an easy way to get a local environment into the same state that the debug.zip is.

This tool should consume a debug zip and inject the descriptors inside of it into an existing database cluster.

### PR DESCRIPTION
**Pull request by postamar**
The doctor tool can be very helpful for troubleshooting schema
corruption issues. These investigations often involve loading the
corrupted descriptor(s) into a local test environment to either better
understand the root cause or to craft a valid descriptor for a repair.
In any case, until now this required taking the descriptor hex encodings
from the debug.zip and updating the system.descriptor table. This can be
tedious and error-prone. Recent improvements to descriptor validation
logic have also made it harder to deliberately corrupt descriptors,
which has unfortunate side-effects in this use case.

This commit adds a new --dump-sql flag to the debug doctor CLI commands
which, instead of running validation checks on the descriptor and
namespace entries, will output a series of SQL statements. When executed
on an empty cluster these will populate it with all of the non-system
descriptors and namespace table entries.

These descriptors are almost as they were, except:
- the version counter is reset to 1,
- the modification time is unset,
- the create-as-of time is unset (tables only).
 
Maintaining the original values would violate too many assumptions to be
safe.

This commit also adds a --verbose flag, which enables verbose output.
The functionality for this existed already but wasn't accessible.

Fixes #62459.

Release note (cli change): The doctor debug tool now has flags for
verbose output and to write SQL statements to recreate the descriptors
and namespace entries examined by doctor in a new, empty cluster.

### CODE REVIEW

**Comment by postamar** [comment]
CI is consistently timing out and I can't figure out why.

**Comment by postamar** [comment]
This is ready for review now.

**Review by ajwerner — COMMENTED** [review]
My primary feedback is that `--dump-sql` feels like it should be a fresh subcommand rather than a flag on doctor. Subcommands nest as deeply as you want them to so you can nest this underneath the existing ones. I suppose it's a matter of taste.

> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63252#-:-MY7zohl9pIU_2B2BsII:b-khvghn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

**Comment by postamar** [comment]
Fair! I was undecided about this, and like always when sitting on the fence, I default to the lazy solution. I'll give it its own subcommand.

**Comment by postamar** [comment]
Here we go: https://github.com/cockroachdb/cockroach/pull/63656

**Pull request closed without merging**
