### PR TITLE
release-2.1: table caching and zone config improvements

### LINKED ISSUE #30045: roachtest: clearrange failed on release-2.1
SHA: https://github.com/cockroachdb/cockroach/commits/8a240fa6f241cc9c72da3de64b753e38951d548e

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stressrace instead of stress and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
make stress TESTS=clearrange PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-stderr=false -maxtime 20m -timeout 10m'
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=896885&tab=buildLog

```
	test.go:498,cluster.go:1227,clearrange.go:177: pq: syntax error at or near "configure"

```

### PR DESCRIPTION
**Pull request by benesch**
Backport:
  * 10/10 commits from "sql: reduce number of places where skipCache is set" (#29022)
  * 4/4 commits from "cli,sql: improve the UX for viewing and updating zone configurations" (#28612)

Please see individual PRs for details. Grouping these mostly unrelated PRs together avoids a merge conflict in pkg/sql/set_zone_config.go.

/cc @cockroachdb/release

Fix #30045.

### CODE REVIEW

**Comment by knz** [comment]
LGTM but I am getting the impression the review process didn't go as intended?

**Comment by vivekmenezes** [comment]
I reviewed it and hit the merge button. I suppose we're not used to that, but why not on these release branches.

**Comment by benesch** [comment]
Definitely OK to use the big green button on these release branches! (Announcements have been made to that effect on #engineering.) I think @knz may have been expecting to review the backport of his commits before the PR merged—but no harm done, since it looked good to everyone!

**Comment by knz** [comment]
Oh no I was OOO so wasn't expecting to review. I was simply surprised, it's not often that the reviewer is also the person who merges.

**Comment by benesch** [comment]
Oh, I see. In this case I opened the PR at Vivek's request so it wasn't really my PR. :)

**Comment by knz** [comment]
All good :+1:

**Pull request merged**
