### PR TITLE
opt: Upgrade Optgen to infer and check types

### PR DESCRIPTION
**Pull request by andy-kimball**
The new opt node representation is more strongly-typed than the old, and
this requires more awareness of types. This commit adds new support to
Optgen to track and check types.

Expressions in both the match and replace patterns are assigned a data type
that describes the kind of data that will be returned by the expression. These
types are inferred using a combination of top-down and bottom-up type inference
rules. For example:
```
  define Select {
    Input  Expr
    Filter Expr
  }

  (Select $input:(LeftJoin | RightJoin) $filter:*) => $input
```
The type of $input is inferred as "LeftJoin | RightJoin" by bubbling up the type
of the bound expression. That type is propagated to the $input reference in the
replace pattern. By contrast, the type of the * expression is inferred to be
"Expr" using a top-down type inference rule, since the second argument to the
Select operator is known to have type "Expr".

When multiple types are inferred for an expression using different type
inference rules, the more restrictive type is assigned to the expression. For
example:
```
  (Select $input:* & (LeftJoin)) => $input
```
Here, the left input to the And expression was inferred to have type "Expr" and
the right input to have type "LeftJoin". Since "LeftJoin" is the more
restrictive type, the And expression and the $input binding are typed as
"LeftJoin".

Type inference detect and report type contradictions, which occur when multiple
incompatible types are inferred for an expression. For example:
```
  (Select $input:(InnerJoin) & (LeftJoin)) => $input
```
Because the input cannot be both an InnerJoin and a LeftJoin, Optgen reports a
type contradiction error.

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
I've broken this PR out of a larger set of commits that switch to the new representation. I'm actively looking for other ways to break up that massive PR into smaller pieces (but I think will be only partially successful in doing that).

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30995)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/optgen/lang/expr.og.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30995#-LO3F0T9BFryzJHrRECD:-LO3F0TA0O16feHDDvmE:bgu4tbm) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b7d71de79ff32c2676ce796de5b538b733f74b2/pkg/sql/opt/optgen/lang/expr.og.go#L60)):*
> ```Go
> }
> 
> func (e *RootExpr) InferredType() DataType {
> ```

I couldn't find the code that generates this
___
*[pkg/sql/opt/optgen/lang/lang.opt, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30995#-LO3FDo91tKQgG3AvJRL:-LO3FDo91tKQgG3AvJRM:b-ks6n2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b7d71de79ff32c2676ce796de5b538b733f74b2/pkg/sql/opt/optgen/lang/lang.opt#L95)):*
> ```
> }
> 
> [HasType]
> ```

Where is this tag used? Feels like something's missing from the PR

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30995)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/optgen/lang/lang.opt, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30995#-LO3FDo91tKQgG3AvJRL:-LO3Y2hQBsZq9qreeYQo:bx55ddh) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b7d71de79ff32c2676ce796de5b538b733f74b2/pkg/sql/opt/optgen/lang/lang.opt#L95)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Where is this tag used? Feels like something's missing from the PR
</blockquote></details>

Whoops, you're right. I've added in the file (`opt/optgen/cmd/langgen/exprs_gen.go`).

**Review by andy-kimball — COMMENTED** [review]
I also decided to rename `UnknownType` to `AnyType`, and return `AnyType` rather than `nil` for nodes which don't have a more useful type to return.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30995#-:-LO3dL6V2K1G5Jrophlo:bc29u04)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by rytaft — APPROVED** [review]
:lgtm: cool!

[nit] the second `Select` expression in the commit/PR message is missing a right parentheses

> Reviewed 4 of 10 files at r1, 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30995#-:-LOF8EKu1byePEVrsIzP:bmkqqxd)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/optgen/lang/compiler.go, line 287 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30995#-LOF9M2KCYZ4epgTkM3k:-LOF9M2KCYZ4epgTkM3l:b4krh1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/e15f1a849d5e4cfdc4f85ad92d989a6aca5cc7dc/pkg/sql/opt/optgen/lang/compiler.go#L287)):*
> ```Go
> 
> 	// Infer data types for expressions within the match and replace patterns.
> 	// Do this only if the rule triggered no errors.
> ```

It doesn't look like `errCnt` would ever be anything other than `len(c.compiler.errors)`...
___
*[pkg/sql/opt/optgen/lang/compiler.go, line 624 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30995#-LOFCNmZEErL4W3TaWcs:-LOFCNmZEErL4W3TaWct:b-c4k7rc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e15f1a849d5e4cfdc4f85ad92d989a6aca5cc7dc/pkg/sql/opt/optgen/lang/compiler.go#L624)):*
> ```Go
> 
> // checkNames ensures that all function names are valid operator names or tag
> // names, and that they are legal in the current context. expandNames returns
> ```

expandNames -> checkNames
___
*[pkg/sql/opt/optgen/lang/data_type.go, line 131 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30995#-LOFEexN5QiEBcHILDzo:-LOFEexN5QiEBcHILDzp:b1f3f4z) ([raw file](https://github.com/cockroachdb/cockroach/blob/e15f1a849d5e4cfdc4f85ad92d989a6aca5cc7dc/pkg/sql/opt/optgen/lang/data_type.go#L131)):*
> ```Go
> 
> 		case *ExternalDataType:
> 			return IsBuiltinType(dt2)
> ```

Why does a builtin type not match a `DefineSetDataType`, but other external types do? (I think a comment here would help)
___
*[pkg/sql/opt/optgen/lang/doc.go, line 481 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30995#-LOFFEIQDGbBgbwPy_F7:-LOFFEIQDGbBgbwPy_F8:b-6cru89) ([raw file](https://github.com/cockroachdb/cockroach/blob/e15f1a849d5e4cfdc4f85ad92d989a6aca5cc7dc/pkg/sql/opt/optgen/lang/doc.go#L481)):*
> ```Go
> example:
> 
>   (Select $input:* & (LeftJoin) => $input
> ```

missing right parentheses
___
*[pkg/sql/opt/optgen/lang/expr.go, line 109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30995#-LOFFoupCalNU9vfIP3a:-LOFFoupCalNU9vfIP3b:b-z6m38x) ([raw file](https://github.com/cockroachdb/cockroach/blob/e15f1a849d5e4cfdc4f85ad92d989a6aca5cc7dc/pkg/sql/opt/optgen/lang/expr.go#L109)):*
> ```Go
> 	// a statically known set of ops it can match, and that every replace pattern
> 	// has a statically known set of ops it can construct. Code generators can
> 	// also this information to generate strongly-typed code.
> ```

also this -> also use this
___
*[pkg/sql/opt/optgen/lang/lang.opt, line 129 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30995#-LOFHlVG8r0woAH5LB0R:-LOFHlVG8r0woAH5LB0S:bk1pkr3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e15f1a849d5e4cfdc4f85ad92d989a6aca5cc7dc/pkg/sql/opt/optgen/lang/lang.opt#L129)):*
> ```
> }
> 
> define ListAny {
> ```

Why doesn't this one have a type?

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30995)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/optgen/lang/compiler.go, line 287 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30995#-LOF9M2KCYZ4epgTkM3k:-LOQomX73R_4k_qJzVO1:b-l5x795) ([raw file](https://github.com/cockroachdb/cockroach/blob/e15f1a849d5e4cfdc4f85ad92d989a6aca5cc7dc/pkg/sql/opt/optgen/lang/compiler.go#L287)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

It doesn't look like `errCnt` would ever be anything other than `len(c.compiler.errors)`...
</blockquote></details>

The `ruleContentCompiler` can add errors to the collection, which would change the length.
___
*[pkg/sql/opt/optgen/lang/compiler.go, line 624 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30995#-LOFCNmZEErL4W3TaWcs:-LOQoxYC24TC7mhmPilO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e15f1a849d5e4cfdc4f85ad92d989a6aca5cc7dc/pkg/sql/opt/optgen/lang/compiler.go#L624)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

expandNames -> checkNames
</blockquote></details>

Done.
___
*[pkg/sql/opt/optgen/lang/data_type.go, line 131 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30995#-LOFEexN5QiEBcHILDzo:-LOQqvWPB6XiCQmcMElQ:bfz1qdk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e15f1a849d5e4cfdc4f85ad92d989a6aca5cc7dc/pkg/sql/opt/optgen/lang/data_type.go#L131)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why does a builtin type not match a `DefineSetDataType`, but other external types do? (I think a comment here would help)
</blockquote></details>

Added some additional comments.
___
*[pkg/sql/opt/optgen/lang/doc.go, line 481 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30995#-LOFFEIQDGbBgbwPy_F7:-LOQr3Oc-Ocxsdysazh5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e15f1a849d5e4cfdc4f85ad92d989a6aca5cc7dc/pkg/sql/opt/optgen/lang/doc.go#L481)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

missing right parentheses
</blockquote></details>

Done.
___
*[pkg/sql/opt/optgen/lang/expr.go, line 109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30995#-LOFFoupCalNU9vfIP3a:-LOQrAJBEqbJfOcbzgsf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e15f1a849d5e4cfdc4f85ad92d989a6aca5cc7dc/pkg/sql/opt/optgen/lang/expr.go#L109)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

also this -> also use this
</blockquote></details>

Done.
___
*[pkg/sql/opt/optgen/lang/lang.opt, line 129 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30995#-LOFHlVG8r0woAH5LB0R:-LOQrETe-AkyDdRRRrZ7:b-gwessc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e15f1a849d5e4cfdc4f85ad92d989a6aca5cc7dc/pkg/sql/opt/optgen/lang/lang.opt#L129)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why doesn't this one have a type?
</blockquote></details>

It's the `...` operator, so its type just defaults to `Any`. `HasType` is only set for types that might be something other than `Any`, since they require an extra `Typ` field to be generated in the exprs.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 10 files at r1, 5 of 9 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30995#-:-LOT3V6d3ylLgYdgYn1s:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/optgen/lang/compiler.go, line 287 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30995#-LOF9M2KCYZ4epgTkM3k:-LOT2WgG8BgEqp7a0oef:b-x8rbb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e15f1a849d5e4cfdc4f85ad92d989a6aca5cc7dc/pkg/sql/opt/optgen/lang/compiler.go#L287)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

The `ruleContentCompiler` can add errors to the collection, which would change the length.
</blockquote></details>

I was confused here for a while too. It would help if a comment explained that we're checking whether `ruleContentCompiler` added more errors to`c.compiler.errors`. Renaming `errCnt` to `errCntBefore` would also help.

(not worth opening another PR just for this, maybe keep it in mind if you modify this file again soon)

**Comment by andy-kimball** [comment]
OK, I added a comment in my uber-PR for this.

**Pull request merged**
