### PR TITLE
roachtest: add acceptance/version-upgrade

### PR DESCRIPTION
**Pull request by petermattis**
Move the version-upgrade acceptance test to a new
acceptance/version-upgrade roachtest.

See #29151

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
The first 6 commits are #29465.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29470)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/upgrade.go, line 469 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/29470#-LLLtGyB9ofEyx5Of38_:-LLLtGyB9ofEyx5Of38a:bl2e3mm) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb24905130b8fad81b5ec36e38b9073c606a8bcb/pkg/cmd/roachtest/upgrade.go#L469)):*
> ```Go
> 
> 		binaryVersionUpgrade("HEAD", nodes, false /* wipe */),
> 		clusterVersionUpgrade(clusterversion.BinaryServerVersion.String(), false /* manual */),
> ```

TODO(peter): this test is currently failing on this last cluster version upgrade which doesn't seem to be working. The old `TestVersionUpgrade` has the exact same logic (automatic upgrade for the last cluster version upgrade) and it seems to work fine. Anyone have any idea what the difference might be? I haven't had a chance to investigate yet so it might be something stupid in my translation of the test.

**Review by benesch — COMMENTED** [review]
> Reviewed 3 of 4 files at r3, 1 of 1 files at r5, 1 of 1 files at r6, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29470)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/upgrade.go, line 451 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/29470#-LLLuMvR4kjvHpV68YlW:-LLLuMvR4kjvHpV68YlX:bfaw408) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb24905130b8fad81b5ec36e38b9073c606a8bcb/pkg/cmd/roachtest/upgrade.go#L451)):*
FYI, from our style guide:

> Note: For `bool` constants, like for all literals, the comment should indicate
> the name of the parameter and does not depend on the argument value.
> *Do not* put a bang in the comment when commenting the `false` constant. Also,
> do not adapt the comment to negate the name of the parameter.
___
*[pkg/cmd/roachtest/upgrade.go, line 469 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/29470#-LLLtGyB9ofEyx5Of38_:-LLLuWZb3A4QIgBxUT4Z:boo5ih9) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb24905130b8fad81b5ec36e38b9073c606a8bcb/pkg/cmd/roachtest/upgrade.go#L469)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

TODO(peter): this test is currently failing on this last cluster version upgrade which doesn't seem to be working. The old `TestVersionUpgrade` has the exact same logic (automatic upgrade for the last cluster version upgrade) and it seems to work fine. Anyone have any idea what the difference might be? I haven't had a chance to investigate yet so it might be something stupid in my translation of the test.
</blockquote></details>

Not seeing anything obvious. @nvanbenschoten might know; I think he was the last person to seriously touch this test.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29470)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/upgrade.go, line 451 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/29470#-LLLuMvR4kjvHpV68YlW:-LLQkK5H9yv1cCSOOxtP:b-pz10tf) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb24905130b8fad81b5ec36e38b9073c606a8bcb/pkg/cmd/roachtest/upgrade.go#L451)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

FYI, from our style guide:

> Note: For `bool` constants, like for all literals, the comment should indicate
> the name of the parameter and does not depend on the argument value.
> *Do not* put a bang in the comment when commenting the `false` constant. Also,
> do not adapt the comment to negate the name of the parameter.

</blockquote></details>

Not sure what this comment was recommending I do, but I thought I was following the style guide. , I've removed the wipe parameter, so the comment is probably not relevant anymore.
___
*[pkg/cmd/roachtest/upgrade.go, line 469 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/29470#-LLLtGyB9ofEyx5Of38_:-LLQg7qD0C6MkFzdFG4J:b-lu7mkf) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb24905130b8fad81b5ec36e38b9073c606a8bcb/pkg/cmd/roachtest/upgrade.go#L469)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Not seeing anything obvious. @nvanbenschoten might know; I think he was the last person to seriously touch this test.
</blockquote></details>

Well, the problem stems from wiping node 3 a few lines higher. Comment out that line and the automatic upgrade succeeds. Leave it in and the automatic upgrade cannot pass. But this series of upgrade steps is taken directly from `TestVersionUpgrade`. Perhaps the wiping was broken in that acceptance test. I'm tracking down what is going on. From what I can tell, `TestVersionUpgrade` only ever sees 3 nodes in the cluster (`n1`, `n2` and `n3`), while the new `acceptance/version-upgrade` sees 4 nodes with the 4th appearing after `n3` is wiped.

Question for @nvanbenschoten (or perhaps @tschottdorf) is it more useful for this test to checking wiping a node, or to exercise the automatic upgrade path?

Update: Ok, found the bug:

```
// RemoveNodeData removes the given node's data directory.
func (c *Cluster) RemoveNodeData(nodeIdx int) error {
	dir := c.Cfg.PerNodeCfg[nodeIdx].DataDir
	return os.RemoveAll(dir)
}
```

In `TestVersionUpgradeTest`, `c.Cfg.PerNodeCfg.DataDir` is empty so we don't end up removing anything. I've removed the support for wiping nodes since I think we're testing that automatic upgrades are disabled in the "upgrade/oldVersion=..." roachtest.

PTAL

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r7, 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29470#-:-LLXiAlk0f_IUPZTGw4W:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/upgrade.go, line 462 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/29470#-LLXhFQ_2VF1Rjd0-Rhe:-LLXhFQ_2VF1Rjd0-Rhf:b9omrih) ([raw file](https://github.com/cockroachdb/cockroach/blob/87bae7b655731756b5f6588c19917a798577ab87/pkg/cmd/roachtest/upgrade.go#L462)):*
> ```Go
> 
> 		binaryVersionUpgrade("HEAD", nodes),
> 		clusterVersionUpgrade(clusterversion.BinaryServerVersion.String(), false /* manual */),
> ```

How are you expecting this test to interact with `release-2.0` roachtests?
___
*[pkg/cmd/roachtest/upgrade.go, line 530 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/29470#-LLXhyAEDG8q2JQdgplW:-LLXhyAEDG8q2JQdgplX:bf21lj4) ([raw file](https://github.com/cockroachdb/cockroach/blob/87bae7b655731756b5f6588c19917a798577ab87/pkg/cmd/roachtest/upgrade.go#L530)):*
> ```Go
> 	// of cockroach.
> 	c.Run(ctx, c.Node(1), "mkdir -p {store-dir} && touch {store-dir}/settings-initialized")
> 	c.Start(ctx, nodes, args, startArgs("--sequential"))
> ```

Is `--sequential` necessary or does it just assist debugging?

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29470)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/upgrade.go, line 462 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/29470#-LLXhFQ_2VF1Rjd0-Rhe:-LLZFYTd-tX1sQLjmCdY:byq2wno) ([raw file](https://github.com/cockroachdb/cockroach/blob/87bae7b655731756b5f6588c19917a798577ab87/pkg/cmd/roachtest/upgrade.go#L462)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

How are you expecting this test to interact with `release-2.0` roachtests?
</blockquote></details>

Hmm, good point. I've fixed this by removing this `versionStep` and replaced it with custom code at the end of the test which retrieves `crdb_internal.node_executable_version()` and compares it against the most recent cluster upgrade value. PTAL.
___
*[pkg/cmd/roachtest/upgrade.go, line 530 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/29470#-LLXhyAEDG8q2JQdgplW:-LLZGD_RBjISdTQnjca-:bm6b5he) ([raw file](https://github.com/cockroachdb/cockroach/blob/87bae7b655731756b5f6588c19917a798577ab87/pkg/cmd/roachtest/upgrade.go#L530)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is `--sequential` necessary or does it just assist debugging?
</blockquote></details>

Unnecessary. Left over from some debugging. Removed.

**Comment by petermattis** [comment]
bors r=nvanbenschoten

**Pull request merged**
