### PR TITLE
sql: Remove occurrences of EXPERIMENTAL_RANGES and TESTING_RANGES.

### PR DESCRIPTION
**Pull request by rohany**
Release note: None

### CODE REVIEW

**Review by solongordon — APPROVED** [review]
> Reviewed 51 of 51 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39181)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by solongordon** [comment]
Looks like there are still some occurrences in `pkg/sql/logictest/testdata/logic_test/ranges`?

**Comment by rohany** [comment]
ah, i think my editors might have not included the logic test files or something.

**Comment by rohany** [comment]
alright, a grep for EXPERIMENTAL_RANGES returns nothing now.

**Pull request merged**
