### PR TITLE
rfc: update consistency checker RFC

### PR DESCRIPTION
**Pull request by eisenstatdavid**
RFC: update consistency checker RFC

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8032)

### CODE REVIEW

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[docs/RFCS/raft_consistency_checker.md, line 63 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNbg52frhtljPsYC9PM:-KNbg52g2wS1WSMM9dWz:247991835) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a113ac258a3a391cc2ca4552a555897a9fb1ea1/docs/RFCS/raft_consistency_checker.md#L63)):*
> ```Markdown
> time spacing between replicas such that a single iteration spans the
> entire periodicity interval. It will log an error for all consistency
> problems seen.
> ```

why did you take out the part about running it in a scanner? We should keep that.

---

*[docs/RFCS/raft_consistency_checker.md, line 32 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNbeNe1U2my7YAfjqzy:-KNbeNe1U2my7YAfjqzz:843503591) ([raw file](https://github.com/cockroachdb/cockroach/blob/929da717035e4cdbd63e3fa520eadc7205cdde8a/docs/RFCS/raft_consistency_checker.md#L32)):*
> ```Markdown
>     `roachpb.RequestUnion`), marking the point at which all replicas
>     take a snapshot and compute its checksum.
> 2.  The lease holder invokes `CollectChecksum` (in `service internal`)
> ```

s/requestor/raft leader on a range/
s/lease holder/raft leader on a range/

---

*[docs/RFCS/raft_consistency_checker.md, line 35 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNbego1oCOEY7BLJHQt:-KNbego1oCOEY7BLJHQu:-1623944542) ([raw file](https://github.com/cockroachdb/cockroach/blob/929da717035e4cdbd63e3fa520eadc7205cdde8a/docs/RFCS/raft_consistency_checker.md#L35)):*
> ```Markdown
>     on the other replicas, thereby exchanging checksums. If there is an
>     inconsistency, both parties log it.
> 3.  (optional, flag-controlled) Inconsistent replicas attach their
> ```

This should not be optional. Now since this is outside of raft we can make it mandatory.

Although we do not want the leader to keep a copy of the snapshot with the hope that it receives a snapshot back from a follower. So I the more optimal solution here is to have the follower report that it saw a consistency issue, and for the leader to then reissue a new consistency check which then holds on to the snapshot awaiting the snapshot from the replica for the purposes of the diff. In other words, it would be a two step process (as is done today), with the second step for aiding in debugging. This also means that the follower should not kill itself until it has completed the second step. If it doesn't receive a message for the second step it should just continue as normal.

---

*[docs/RFCS/raft_consistency_checker.md, line 48 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNbgNH9gqeOP0mnsbhG:-KNbgNH9gqeOP0mnsbhH:140158871) ([raw file](https://github.com/cockroachdb/cockroach/blob/929da717035e4cdbd63e3fa520eadc7205cdde8a/docs/RFCS/raft_consistency_checker.md#L48)):*
> ```Markdown
> 
> `CollectChecksum` requests are blocking in tests (to avoid flakes) and
> nonblocking in production. Before the lease holder makes these requests,
> ```

We can make it blocking in production now given that it's outside of raft.

Can you expand the description of  CollectChecksum to discuss that the request contains a checksum from the leader and boolean flag requesting  a snapshot if the checksums mismatch. It returns the checksum and the snapshot if it is requested and the checksums are different. On returning a snapshot it can kill the server after say a 10 second timeout.

---

*[docs/RFCS/raft_consistency_checker.md, line 58 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNbhUrXfxbInKDeznxD:-KNbhUrXfxbInKDeznxE:-1814414112) ([raw file](https://github.com/cockroachdb/cockroach/blob/929da717035e4cdbd63e3fa520eadc7205cdde8a/docs/RFCS/raft_consistency_checker.md#L58)):*
> ```Markdown
> and any log entries with index greater than the applied index of the
> `ComputeChecksum` command. If the replica is split or merged before
> `CollectChecksum` is received, the replica returns a `RANGE_CHANGED`
> ```

I don't think this is necessary any more since the compute checksum goes through raft. Either the server has a replica
and is aware of the UUID, or not. If the replica is missing, it can return REPLICA_NOTFOUND which the client can log and move on. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/raft_consistency_checker.md, line 32 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNbeNe1U2my7YAfjqzy:-KNbn0ToOaYan4fJBAgS:1807672843) ([raw file](https://github.com/cockroachdb/cockroach/blob/929da717035e4cdbd63e3fa520eadc7205cdde8a/docs/RFCS/raft_consistency_checker.md#L32)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> s/requestor/raft leader on a range/
> s/lease holder/raft leader on a range/
</details>
is that right? I'm pretty sure it's the lease holder.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/raft_consistency_checker.md, line 32 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNbeNe1U2my7YAfjqzy:-KNbnscR4og9GhCVt-GT:2041828399) ([raw file](https://github.com/cockroachdb/cockroach/blob/929da717035e4cdbd63e3fa520eadc7205cdde8a/docs/RFCS/raft_consistency_checker.md#L32)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> is that right? I'm pretty sure it's the lease holder.
</details>
ComputeChecksum is a raft command that is "writable" in that it is a read command that is repeated on all replicas so it can only be executed by the raft leader. That's my understanding of the term.

CollectChecksum in theory can be executed by anyone since it's not in raft, but is best initiated by whoever ran the ComputeChecksum.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032)*

**Comment by eisenstatdavid** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[docs/RFCS/raft_consistency_checker.md, line 63 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNbg52frhtljPsYC9PM:-KNbkUXAbkz8c3-3bjAo:1975158183) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a113ac258a3a391cc2ca4552a555897a9fb1ea1/docs/RFCS/raft_consistency_checker.md#L63)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> why did you take out the part about running it in a scanner? We should keep that.
</details>
I moved it to the beginning of the section -- "Each node loops continuously through its local replicas, requesting a consistency check on the next replica every 10 seconds."

---

*[docs/RFCS/raft_consistency_checker.md, line 32 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNbeNe1U2my7YAfjqzy:-KNcKqhqZEC90nYKKxdy:1532844108) ([raw file](https://github.com/cockroachdb/cockroach/blob/929da717035e4cdbd63e3fa520eadc7205cdde8a/docs/RFCS/raft_consistency_checker.md#L32)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> ComputeChecksum is a raft command that is "writable" in that it is a read command that is repeated on all replicas so it can only be executed by the raft leader. That's my understanding of the term.
> 
> CollectChecksum in theory can be executed by anyone since it's not in raft, but is best initiated by whoever ran the ComputeChecksum.
</details>
I changed the direction of CollectChecksum -- now follower calls leader. This avoids a race where a follower gets a CollectChecksum call from the leader despite not having processed the ComputeChecksum Raft message yet.

---

*[docs/RFCS/raft_consistency_checker.md, line 35 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNbego1oCOEY7BLJHQt:-KNbprBH6I6J-GI4AmKp:-333962011) ([raw file](https://github.com/cockroachdb/cockroach/blob/929da717035e4cdbd63e3fa520eadc7205cdde8a/docs/RFCS/raft_consistency_checker.md#L35)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> This should not be optional. Now since this is outside of raft we can make it mandatory.
> 
> Although we do not want the leader to keep a copy of the snapshot with the hope that it receives a snapshot back from a follower. So I the more optimal solution here is to have the follower report that it saw a consistency issue, and for the leader to then reissue a new consistency check which then holds on to the snapshot awaiting the snapshot from the replica for the purposes of the diff. In other words, it would be a two step process (as is done today), with the second step for aiding in debugging. This also means that the follower should not kill itself until it has completed the second step. If it doesn't receive a message for the second step it should just continue as normal.
</details>
Done. Do we want to do admission control on checks that exchange full snapshots?

---

*[docs/RFCS/raft_consistency_checker.md, line 48 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNbgNH9gqeOP0mnsbhG:-KNbpeuWieC0Maw2rgik:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/929da717035e4cdbd63e3fa520eadc7205cdde8a/docs/RFCS/raft_consistency_checker.md#L48)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> We can make it blocking in production now given that it's outside of raft.
> 
> Can you expand the description of  CollectChecksum to discuss that the request contains a checksum from the leader and boolean flag requesting  a snapshot if the checksums mismatch. It returns the checksum and the snapshot if it is requested and the checksums are different. On returning a snapshot it can kill the server after say a 10 second timeout.
</details>
Done.

---

*[docs/RFCS/raft_consistency_checker.md, line 58 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNbhUrXfxbInKDeznxD:-KNbpgsPwlwXB_3NadTX:-143586522) ([raw file](https://github.com/cockroachdb/cockroach/blob/929da717035e4cdbd63e3fa520eadc7205cdde8a/docs/RFCS/raft_consistency_checker.md#L58)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> I don't think this is necessary any more since the compute checksum goes through raft. Either the server has a replica
> and is aware of the UUID, or not. If the replica is missing, it can return REPLICA_NOTFOUND which the client can log and move on. 
</details>
Done. We don't need the part about HardState, do we?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/raft_consistency_checker.md, line 26 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNceAWNKNyxs0rMpGzA:-KNceAWNKNyxs0rMpGzB:173331309) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b98819f8f55ad48f525e1003d51371a516e58f/docs/RFCS/raft_consistency_checker.md#L26)):*
> ```Markdown
> ===============
> 
> Each Raft leader loops continuously through its local replicas,
> ```

Each node loops continuously through its local replicas over a 24 hour period, requesting a consistency check on local replicas for which it is the range leader.  

---

*[docs/RFCS/raft_consistency_checker.md, line 32 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNceegcZM3IzaQx6Gvw:-KNceegcZM3IzaQx6Gvx:453577037) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b98819f8f55ad48f525e1003d51371a516e58f/docs/RFCS/raft_consistency_checker.md#L32)):*
> ```Markdown
>     `ComputeChecksum` (in `roachpb.RequestUnion`), marking the point at
>     which all replicas take a snapshot and compute its checksum.
> 2.  Followers invoke `CollectChecksum` (in `service internal`) on the
> ```

you want to say that the Raft leader invokes 'CollectChecksum' on all the followers outside of Raft.

---

*[docs/RFCS/raft_consistency_checker.md, line 39 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNceyOaS5hxNqUMWcrI:-KNceyObHWK0m81PyWhH:-307340247) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b98819f8f55ad48f525e1003d51371a516e58f/docs/RFCS/raft_consistency_checker.md#L39)):*
> ```Markdown
>     of checksums. When a follower's snapshot differs from the leader's,
>     both parties log the differently valued keys. The follower then
>     kills its server.
> ```

In the new mode, the leader again calls ComputeChecksum on all replicas through Raft with the "snapshot" boolean set indicating that it would like all replicas to compute a checksum while holding on to the snapshot. The leader will then call CollectChecksum with its checksum and the "snapshot"  boolean set indicating that the follower should compare checksums and when different return the full snapshot back to the leader. The leader will then diff the collected snapshot against its snapshot and log the diff. The follower will die in a few seconds after returning its snapshot.

---

*[docs/RFCS/raft_consistency_checker.md, line 49 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNcgnQ2H37NrJik3QHK:-KNcgnQ2H37NrJik3QHL:-1456151465) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b98819f8f55ad48f525e1003d51371a516e58f/docs/RFCS/raft_consistency_checker.md#L49)):*
> ```Markdown
> followers finish their checksum, they send it to the leader by calling
> `CollectChecksum`. The leader deletes its record of the check when all
> followers have contacted it or after 30 minutes, whichever comes first.
> ```

this is wrong if you see my notes above. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: 0 of 1 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/raft_consistency_checker.md, line 6 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNe8eH1ml-PjYgrEUVs:-KNe8eH1ml-PjYgrEUVt:1416014566) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a113ac258a3a391cc2ca4552a555897a9fb1ea1/docs/RFCS/raft_consistency_checker.md#L6)):*
> ```Markdown
> -   Authors: Ben Darnell, Bram Gruneir, Vivek Menezes
> -   RFC PR: (PR \# after acceptance of initial draft)
> -   Cockroach Issue: \#837
> ```

We want the unescaped `#` here. On github, this renders as a link to the issue. While you're here, make it `#837, #8032` so it will link to this one too. 

---

*[docs/RFCS/raft_consistency_checker.md, line 32 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNbeNe1U2my7YAfjqzy:-KNeE3cj9zFMeddXj_VG:1851459519) ([raw file](https://github.com/cockroachdb/cockroach/blob/929da717035e4cdbd63e3fa520eadc7205cdde8a/docs/RFCS/raft_consistency_checker.md#L32)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary>
> I changed the direction of CollectChecksum -- now follower calls leader. This avoids a race where a follower gets a CollectChecksum call from the leader despite not having processed the ComputeChecksum Raft message yet.
</details>
This RPC should be renamed from CollectChecksum to ReportChecksum. (and per the previous note raft leader and follower are not the relevant roles here)

---

*[docs/RFCS/raft_consistency_checker.md, line 26 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNceAWNKNyxs0rMpGzA:-KNe9t5vQkK0nb-XjuZh:267103401) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b98819f8f55ad48f525e1003d51371a516e58f/docs/RFCS/raft_consistency_checker.md#L26)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> Each node loops continuously through its local replicas over a 24 hour period, requesting a consistency check on local replicas for which it is the range leader.  
</details>
"range lease holder", not leader. (they're usually but not always the same)

I wouldn't mention either the 24h target cycle time or the 10s minimum sleep in this doc; that's an implementation detail. 

---

*[docs/RFCS/raft_consistency_checker.md, line 29 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNeDSWC2AsbND0wu_tD:-KNeDSWC2AsbND0wu_tE:-1917851889) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b98819f8f55ad48f525e1003d51371a516e58f/docs/RFCS/raft_consistency_checker.md#L29)):*
> ```Markdown
> requesting a consistency check on the next replica every 10 seconds.
> 
> 1.  The Raft leader on a range invokes the Raft command
> ```

s/Raft leader/lease holder/g

Throughout the doc, it's the lease holder and not the leader that matters. In fact, we probably want to give the node that starts the checksum process a new name ("checksum leader"? "checksum coordinator"?) and use that instead - it retains this role even if it subsequently loses the lease. (it's not even important that it ever held the lease, except that this is the most convenient way to guard against multiple replicas initiating a consistency check at once)

---

*[docs/RFCS/raft_consistency_checker.md, line 76 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNeISZGxEJXsYrmax07:-KNeISZGxEJXsYrmax08:113083337) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b98819f8f55ad48f525e1003d51371a516e58f/docs/RFCS/raft_consistency_checker.md#L76)):*
> ```Markdown
>     The replicas, including the new lease holder, will continue
>     computing the SHA. The new lease holder will not send a
>     CollectChecksum command.
> ```

This section needs to be updated to reflect the reversal of CollectChecksum. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-:-KNeIs9MlHf3iOJ4Zw2T:676834233)*

**Comment by eisenstatdavid** [comment]
Review status: 0 of 1 files reviewed at latest revision, 12 unresolved discussions, some commit checks pending.

---

*[docs/RFCS/raft_consistency_checker.md, line 6 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNe8eH1ml-PjYgrEUVs:-KNhUSQnEyjyx5Tj8045:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a113ac258a3a391cc2ca4552a555897a9fb1ea1/docs/RFCS/raft_consistency_checker.md#L6)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> We want the unescaped `#` here. On github, this renders as a link to the issue. While you're here, make it `#837, #8032` so it will link to this one too. 
</details>
Done.

---

*[docs/RFCS/raft_consistency_checker.md, line 32 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNbeNe1U2my7YAfjqzy:-KNhUihZuKNo764ppKUE:92530358) ([raw file](https://github.com/cockroachdb/cockroach/blob/929da717035e4cdbd63e3fa520eadc7205cdde8a/docs/RFCS/raft_consistency_checker.md#L32)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> This RPC should be renamed from CollectChecksum to ReportChecksum. (and per the previous note raft leader and follower are not the relevant roles here)
</details>
After offline discussion with Vivek, I'm reverting to the old CollectChecksum semantics, where the initiator of the check issues the Collect calls.

---

*[docs/RFCS/raft_consistency_checker.md, line 26 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNceAWNKNyxs0rMpGzA:-KNhUUHQ7Pnwxf0j7a6k:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b98819f8f55ad48f525e1003d51371a516e58f/docs/RFCS/raft_consistency_checker.md#L26)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> "range lease holder", not leader. (they're usually but not always the same)
> 
> I wouldn't mention either the 24h target cycle time or the 10s minimum sleep in this doc; that's an implementation detail. 
</details>
Done.

---

*[docs/RFCS/raft_consistency_checker.md, line 29 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNeDSWC2AsbND0wu_tD:-KNhU_733KQDeRthjbPK:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b98819f8f55ad48f525e1003d51371a516e58f/docs/RFCS/raft_consistency_checker.md#L29)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> s/Raft leader/lease holder/g
> 
> Throughout the doc, it's the lease holder and not the leader that matters. In fact, we probably want to give the node that starts the checksum process a new name ("checksum leader"? "checksum coordinator"?) and use that instead - it retains this role even if it subsequently loses the lease. (it's not even important that it ever held the lease, except that this is the most convenient way to guard against multiple replicas initiating a consistency check at once)
</details>
Done.

---

*[docs/RFCS/raft_consistency_checker.md, line 32 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNceegcZM3IzaQx6Gvw:-KNhUa-K9bYbypeqMxrV:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b98819f8f55ad48f525e1003d51371a516e58f/docs/RFCS/raft_consistency_checker.md#L32)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> you want to say that the Raft leader invokes 'CollectChecksum' on all the followers outside of Raft.
</details>
Done.

---

*[docs/RFCS/raft_consistency_checker.md, line 39 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNceyOaS5hxNqUMWcrI:-KNhV-3CEkO2IiAf45nZ:-1857692365) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b98819f8f55ad48f525e1003d51371a516e58f/docs/RFCS/raft_consistency_checker.md#L39)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> In the new mode, the leader again calls ComputeChecksum on all replicas through Raft with the "snapshot" boolean set indicating that it would like all replicas to compute a checksum while holding on to the snapshot. The leader will then call CollectChecksum with its checksum and the "snapshot"  boolean set indicating that the follower should compare checksums and when different return the full snapshot back to the leader. The leader will then diff the collected snapshot against its snapshot and log the diff. The follower will die in a few seconds after returning its snapshot.
</details>
Done (reworded for compactness).

---

*[docs/RFCS/raft_consistency_checker.md, line 49 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNcgnQ2H37NrJik3QHK:-KNhVIjQ72bV3SxqWk0T:676534122) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b98819f8f55ad48f525e1003d51371a516e58f/docs/RFCS/raft_consistency_checker.md#L49)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> this is wrong if you see my notes above. Thanks!
</details>
Ack.

---

*[docs/RFCS/raft_consistency_checker.md, line 76 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNeISZGxEJXsYrmax07:-KNhVM4XDCvh488d7UFo:-719267080) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b98819f8f55ad48f525e1003d51371a516e58f/docs/RFCS/raft_consistency_checker.md#L76)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> This section needs to be updated to reflect the reversal of CollectChecksum. 
</details>
Updated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-:-KNiEiMkNYSsk5NRmQwX:1417088721)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/raft_consistency_checker.md, line 6 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNe8eH1ml-PjYgrEUVs:-KNiGD80JY8Dt716hp-G:317779455) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a113ac258a3a391cc2ca4552a555897a9fb1ea1/docs/RFCS/raft_consistency_checker.md#L6)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary>
> Done.
</details>
nit: this amendment is now in the wrong commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032)*

**Comment by vivekmenezes** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/raft_consistency_checker.md, line 75 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-KNm2M8W6ql3gGBjN_j-:-KNm2M8XM0KYozuuK-Df:-871523376) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4baf93f676c2d1055b9afeae516d4ebb6ada5fd/docs/RFCS/raft_consistency_checker.md#L75)):*
> ```Markdown
> can check the consistency of all ranges for which it is a lease holder
> using the same mechanism provided for the periodic consistency checker.
> This will be used in all acceptance tests.
> ```

The acceptance tests (and future TestCluster tests) use the CheckConsistency(begin, end Key) kv API call to check consistency more aggressively during tests. I'd say this and exposing this API through the CLI as a later useful tool.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8032#-:-KNm3AYN_huPCBzwBXGD:1417088721)*

**Comment by vivekmenezes** [comment]
Congrats! Nice work on getting this passed the finish line!

**Pull request merged**
