### PR TITLE
revertccl: move RevertSpansFanout to revertccl

### PR DESCRIPTION
**Pull request by dt**
Release note: none.
Epic: none.

### CODE REVIEW

**Comment by stevendanna** [comment]
Move seems OK to me, but any particular reason for it?

**Comment by dt** [comment]
Two motivations:

1) intend to add more code related to reverting in the near future, that will be its own feature, so carving out a dedicated home for that 
2) Anything we can get out of the sql mega package we should.

**Review by stevendanna — APPROVED** [review]
+1 on the new package.  I question whether this needs to be a `ccl` package. But, it is only currently used by a CCL feature so I suppose that makes sense.

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
