### PR TITLE
kvflowcontrol: deflake TestFlowControlGranterAdmitOneByOne

### LINKED ISSUE #110425: kv: TestFlowControlGranterAdmitOneByOne failed
This test fails about once a day with the same error.

https://teamcity.cockroachdb.com/test/1304895367360427992?currentProjectId=Cockroach_Ci_TestsGcpLinuxX8664BigVm&expandTestHistoryChartSection=true&orderBy=status&order=desc

```
Failed
=== RUN   TestFlowControlGranterAdmitOneByOne
    test_log_scope.go:167: test logs captured to: /artifacts/tmp/_tmp/efdc05cf79b5dfd2ad5dc565351e4382/logTestFlowControlGranterAdmitOneByOne3800129376
    test_log_scope.go:81: use -show-logs to present logs inline
    datadriven.go:144:
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/13216/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/kv/kvserver/kvserver_test_/kvserver_test.runfiles/com_github_cockroachdb_cockroach/pkg/kv/kvserver/testdata/flow_control_integration/granter_admit_one_by_one:1:
        output didn't match expected:
        @@ -9,27 +9,27 @@
            WHERE name LIKE '%kvadmission%tokens%'
         ORDER BY name ASC;
           kvadmission.flow_controller.elastic_tokens_available   | 21 MiB
           kvadmission.flow_controller.elastic_tokens_deducted    | 3.0 MiB
        -  kvadmission.flow_controller.elastic_tokens_returned    | 0 B
        +  kvadmission.flow_controller.elastic_tokens_returned    | 3.0 KiB
           kvadmission.flow_controller.elastic_tokens_unaccounted | 0 B
           kvadmission.flow_controller.regular_tokens_available   | 45 MiB
           kvadmission.flow_controller.regular_tokens_deducted    | 3.0 MiB
        -  kvadmission.flow_controller.regular_tokens_returned    | 0 B
        +  kvadmission.flow_controller.regular_tokens_returned    | 3.0 KiB
           kvadmission.flow_controller.regular_tokens_unaccounted | 0 B
         -- Observe the total tracked tokens per-stream on n1.
         SELECT range_id, store_id, crdb_internal.humanize_bytes(total_tracked_tokens::INT8)
             FROM crdb_internal.kv_flow_control_handles
           range_id | store_id | total_tracked_tokens
         -----------+----------+-----------------------
        -  65       | 1        | 1.0 MiB
        -  65       | 2        | 1.0 MiB
        -  65       | 3        | 1.0 MiB
        +  65       | 1        | 1023 KiB
        +  65       | 2        | 1023 KiB
        +  65       | 3        | 1023 KiB
         -- (Allow below-raft admission to proceed.)
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/efdc05cf79b5dfd2ad5dc565351e4382/logTestFlowControlGranterAdmitOneByOne3800129376
--- FAIL: TestFlowControlGranterAdmitOneByOne (3.92s)
```

Jira issue: CRDB-31423

### PR DESCRIPTION
**Pull request by aadityasondhi**
This test was flaky because of the async update of cluster settings to other nodes. When we set `kvflowcontrol.Mode` to `apply_to_all`, it would trigger the `OnChange` callback for that setting that returns all tokens early, which disrupted the change. Most of the time the setting worked, but sometimes, it would trigger the callback during the workload causing the test to fail.

This change now uses `Override()` to synchronously update this setting on each node to make sure the callback is called before returning from the `init()` func.

Fixes #110425

Release note: None

### CODE REVIEW

**Comment by aadityasondhi** [comment]
`Stats over 1000 runs: max = 8.5s, min = 4.3s, avg = 5.3s, dev = 0.4s`

from gceworker

more info on reason for flake: https://github.com/cockroachdb/cockroach/issues/110425#issuecomment-1738102645

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111416#-:-NfSUm9Z1J_gTAh9IaT5:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi and @bananabrick)

___
*[`pkg/kv/kvserver/flow_control_integration_test.go` line 2334 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111416#-NfSU4Bc13F1wo0qlEQN:-NfSU4Bc13F1wo0qlEQO:bichj0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/cab17b0d616492dc43d86786b035b1846224e40f/pkg/kv/kvserver/flow_control_integration_test.go#L2334)):*
> ```Go
> 
> func (h *flowControlTestHelper) init() {
> 	for _, s := range h.tc.Servers {
> ```

Can you add a code comment here. Something like.
// Reach into each server's cluster setting and override. This causes any registered change callbacks to run immediately, which is important since running them with some lag (which happens when using SQL and SET CLUSTER SETTING) interferes with the later activities in the test.

**Review by aadityasondhi — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111416#-:-NfSbMRU1eG_4AeFKFRg:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bananabrick and @sumeerbhola)

___
*[`pkg/kv/kvserver/flow_control_integration_test.go` line 2334 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111416#-NfSU4Bc13F1wo0qlEQN:-NfSbLzn8pTYf7HvKrc4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cab17b0d616492dc43d86786b035b1846224e40f/pkg/kv/kvserver/flow_control_integration_test.go#L2334)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add a code comment here. Something like.
// Reach into each server's cluster setting and override. This causes any registered change callbacks to run immediately, which is important since running them with some lag (which happens when using SQL and SET CLUSTER SETTING) interferes with the later activities in the test.
</blockquote></details>

Done.

**Comment by aadityasondhi** [comment]
bors r=sumeerbhola

**Comment by aadityasondhi** [comment]
bors r=sumeerbhola p=99

**Comment by aadityasondhi** [comment]
Seems related to https://cockroachlabs.slack.com/archives/CJ0H8Q97C/p1695929643283739. Will wait before merging

**Comment by aadityasondhi** [comment]
bors r=sumeerbhola p=99

**Pull request merged**
