### PR TITLE
storageccl: clean up batching in Import command and resurrect TestImport

### PR DESCRIPTION
**Pull request by danhhz**
The semantics of Close, Finish, and resetBatcher were a little muddy and caused
an actual bug (Close was being called before Finish sometimes). This
changes resetBatcher to require that the batcher was Close'd and nil'd
beforehand (and fixes the bug).

----

TestImport was skipped during some last minute bug fixing in the runup to 1.0.
I can't remember why, but it works now when unskipped, so do that.

Also extend TestImport to check batching (which would have caught
found that we weren't retrying AmbiguousResultError for the latter. This
also found that allow_blocking_flush wasn't being set to true on the
IngestExternalFile call, but it should be.

Finally, improve the errors being returned from RocksDBSstFileWriter,
which helped me debug what all was going on here.

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/engine/db.cc, line 2337 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16469#-KmSOLUXvDfTEb0Qc-Mf:-KmSOLUXvDfTEb0Qc-Mg:b5uynkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/66757ed76e7611ebad18f8485e804c147938c073/pkg/storage/engine/db.cc#L2337)):*
> ```cpp
>   ingest_options.snapshot_consistency = false;
>   ingest_options.allow_global_seqno = true;
>   ingest_options.allow_blocking_flush = true;
> ```

What's this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16469#-:-KmSOXXxuq5SR_F_iIHg:bnfp4nl)*

**Comment by danhhz** [comment]
TFTR!

---

Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/engine/db.cc, line 2337 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16469#-KmSOLUXvDfTEb0Qc-Mf:-KmSd_HBgvRe3jkqTmpL:bhwf9zp) ([raw file](https://github.com/cockroachdb/cockroach/blob/66757ed76e7611ebad18f8485e804c147938c073/pkg/storage/engine/db.cc#L2337)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

What's this?
</blockquote></details>

Added some comments on all of these

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16469#-:-KmSdXV8PCOZZC7i-h8L:b-814g8k)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/engine/db.cc, line 2337 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16469#-KmSOLUXvDfTEb0Qc-Mf:-KmSeFrRYGuVm51nuKHp:bmtzrwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/66757ed76e7611ebad18f8485e804c147938c073/pkg/storage/engine/db.cc#L2337)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Added some comments on all of these
</blockquote></details>

Typo: flused

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16469)*

**Comment by danhhz** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/engine/db.cc, line 2337 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16469#-KmSOLUXvDfTEb0Qc-Mf:-KmSeu8dU_fUk1fXNHQv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66757ed76e7611ebad18f8485e804c147938c073/pkg/storage/engine/db.cc#L2337)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Typo: flused
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16469)*

**Pull request merged**
