### PR TITLE
Fixes #3124 - Add drainQueue function to queues.

### LINKED ISSUE #3124: Test failure in CI build 9357
The following test appears to have failed:

[#9357](https://circleci.com/gh/cockroachdb/cockroach/9357):

```
I1113 03:29:27.861174 1014 gossip/gossip.go:172  gossiping node descriptor node_id:3 address:<network_field:"localhost" address_field:"3" > attrs:<> 
I1113 03:29:27.862243 1014 storage/queue.go:193  no system config available. skipping...
I1113 03:29:28.940092 1014 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
I1113 03:29:28.940248 1014 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
I1113 03:29:28.940318 1014 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- FAIL: TestRaftLogQueue (1.09s)
	testing.go:157: storage/client_raft_log_queue_test.go:93: condition failed to evaluate within 1s: storage/client_raft_log_queue_test.go:90: raft log has not been truncated yet, currentIndex:11 originalIndex:11
=== RUN   TestStoreRecoverFromEngine
I1113 03:29:28.940804 1014 gossip/gossip.go:172  gossiping node descriptor node_id:1 address:<network_field:"localhost" address_field:"1" > attrs:<> 
I1113 03:29:28.941509 1014 multiraft/multiraft.go:562  node 1 starting
I1113 03:29:28.941631 1014 raft/raft.go:409  [group 1] 1 became follower at term 5
I1113 03:29:28.941683 1014 raft/raft.go:218  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I1113 03:29:28.941755 1014 multiraft/multiraft.go:964  node 1 campaigning because initial confstate is [1]
I1113 03:29:28.941862 1014 storage/replica.go:1259  gossiping cluster id  from store 1, range 1
I1113 03:29:28.942010 1014 raft/raft.go:488  [group 1] 1 is starting a new election at term 5
I1113 03:29:28.942035 1014 raft/raft.go:422  [group 1] 1 became candidate at term 6
--
=== RUN   TestSplitSnapshotRace_SnapshotWins
--- SKIP: TestSplitSnapshotRace_SnapshotWins (0.00s)
	client_split_test.go:740: TODO(bdarnell): https://github.com/cockroachdb/cockroach/issues/3121
=== RUN   Example_rebalancing
--- PASS: Example_rebalancing (0.13s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	20.348s
=== RUN   TestBatchBasics
I1113 03:29:19.309201 991 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I1113 03:29:19.310244 991 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN   TestBatchMerge
I1113 03:29:19.312037 991 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by BramGruneir**
This removes the SucceedsWithin in the test and makes it more deterministic.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3141)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

<sup>**[storage/queue.go, line 403 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141#-K3GqfQlBR6PJnmYaXAa)** ([raw file](https://github.com/cockroachdb/cockroach/blob/4833208b47a0ec9d2f5c4df3da06369e1b004ef8/storage/queue.go#L403)):</sup>
higher verbosity?


---

<sup>**[storage/queue.go, line 407 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141#-K3GpVnLfLAGK3iTRXrB)** ([raw file](https://github.com/cockroachdb/cockroach/blob/4833208b47a0ec9d2f5c4df3da06369e1b004ef8/storage/queue.go#L407)):</sup>
```
for repl := bq.pop(); repl != nil; repl = bq.pop() {
  ....
}
```


---

<sup>**[storage/queue.go, line 408 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141#-K3GqhX4xnGRG0FT3UrD)** ([raw file](https://github.com/cockroachdb/cockroach/blob/4833208b47a0ec9d2f5c4df3da06369e1b004ef8/storage/queue.go#L408)):</sup>
higher verbosity?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141)

**Comment by BramGruneir** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

<sup>**[storage/queue.go, line 403 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141#-K3GqfQlBR6PJnmYaXAa)** ([raw file](https://github.com/cockroachdb/cockroach/blob/4833208b47a0ec9d2f5c4df3da06369e1b004ef8/storage/queue.go#L403)):</sup>
Purposefully, for testing only.


---

<sup>**[storage/queue.go, line 407 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141#-K3GpVnLfLAGK3iTRXrB)** ([raw file](https://github.com/cockroachdb/cockroach/blob/4833208b47a0ec9d2f5c4df3da06369e1b004ef8/storage/queue.go#L407)):</sup>
oh, that's cleaner.  I'll change it.


---

<sup>**[storage/queue.go, line 408 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141#-K3GqhX4xnGRG0FT3UrD)** ([raw file](https://github.com/cockroachdb/cockroach/blob/4833208b47a0ec9d2f5c4df3da06369e1b004ef8/storage/queue.go#L408)):</sup>
again, purposefully


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141)

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[storage/queue.go, line 403 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141#-K3GqfQlBR6PJnmYaXAa)** ([raw file](https://github.com/cockroachdb/cockroach/blob/4833208b47a0ec9d2f5c4df3da06369e1b004ef8/storage/queue.go#L403)):</sup>
Eh, that's not really clear since this is an unexported method. Put the log line in the caller if you're leaving the logs at this verbosity.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141)

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[storage/queue.go, line 401 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141#-K3GsFQjMAUsSU9hebJ2)** ([raw file](https://github.com/cockroachdb/cockroach/blob/4833208b47a0ec9d2f5c4df3da06369e1b004ef8/storage/queue.go#L401)):</sup>
I'd remove this comment. We leave comments like this on exported methods elsewhere as justification for their existence/being exported, but it's not necessary here.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141)

**Comment by BramGruneir** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[storage/queue.go, line 401 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141#-K3GsFQjMAUsSU9hebJ2)** ([raw file](https://github.com/cockroachdb/cockroach/blob/4833208b47a0ec9d2f5c4df3da06369e1b004ef8/storage/queue.go#L401)):</sup>
I'll expose this and add the comment about it being for testing only.


---

<sup>**[storage/queue.go, line 403 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141#-K3GqfQlBR6PJnmYaXAa)** ([raw file](https://github.com/cockroachdb/cockroach/blob/4833208b47a0ec9d2f5c4df3da06369e1b004ef8/storage/queue.go#L403)):</sup>
removed the extra logs


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141)

**Comment by BramGruneir** [comment]
Added the fix for the test now.  PTAL


---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141)

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

<sup>**[storage/client_raft_log_queue_test.go, line 105 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141#-K3HPPRcV7qcs2vewGeU)** ([raw file](https://github.com/cockroachdb/cockroach/blob/3826c4d6d1dee8510c8a5bcf166bdaaf5647b7f9/storage/client_raft_log_queue_test.go#L105)):</sup>
nit: I'd use a new binding for this raft leader


---

<sup>**[storage/client_test.go, line 574 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141#-K3HPgDRDdXw85HwIx1Q)** ([raw file](https://github.com/cockroachdb/cockroach/blob/3826c4d6d1dee8510c8a5bcf166bdaaf5647b7f9/storage/client_test.go#L574)):</sup>
the store appears never to be used?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141)

**Comment by BramGruneir** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

<sup>**[storage/client_test.go, line 574 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141#-K3HPgDRDdXw85HwIx1Q)** ([raw file](https://github.com/cockroachdb/cockroach/blob/3826c4d6d1dee8510c8a5bcf166bdaaf5647b7f9/storage/client_test.go#L574)):</sup>
It is used.  And going from replica to store can be annoying.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141)

**Comment by BramGruneir** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

<sup>**[storage/client_raft_log_queue_test.go, line 105 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141#-K3HPPRcV7qcs2vewGeU)** ([raw file](https://github.com/cockroachdb/cockroach/blob/3826c4d6d1dee8510c8a5bcf166bdaaf5647b7f9/storage/client_raft_log_queue_test.go#L105)):</sup>
I call it 4 times I think and I'm just updating the replRaftLeader.  I think using a new name every time would just confuse matters.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141)

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[storage/client_raft_log_queue_test.go, line 68 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141#-K3HQXU1Xb62Sub9qz07)** ([raw file](https://github.com/cockroachdb/cockroach/blob/3826c4d6d1dee8510c8a5bcf166bdaaf5647b7f9/storage/client_raft_log_queue_test.go#L68)):</sup>
this check appears to be a duplicate of the one inside `getRaftLeader`.


---

<sup>**[storage/client_raft_log_queue_test.go, line 105 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141#-K3HPPRcV7qcs2vewGeU)** ([raw file](https://github.com/cockroachdb/cockroach/blob/3826c4d6d1dee8510c8a5bcf166bdaaf5647b7f9/storage/client_raft_log_queue_test.go#L105)):</sup>
Using a new name each time would ensure that accidental removal of this line won't break the test, but OK.


---

<sup>**[storage/client_test.go, line 574 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141#-K3HPgDRDdXw85HwIx1Q)** ([raw file](https://github.com/cockroachdb/cockroach/blob/3826c4d6d1dee8510c8a5bcf166bdaaf5647b7f9/storage/client_test.go#L574)):</sup>
Looks like the only place it's used is superfluous.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141)

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[storage/client_test.go, line 573 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141#-K3HQRXfLeKvMGuW01md)** ([raw file](https://github.com/cockroachdb/cockroach/blob/3826c4d6d1dee8510c8a5bcf166bdaaf5647b7f9/storage/client_test.go#L573)):</sup>
A leader can be deposed without knowing it yet; multiple nodes may be in `StateLeader` at once.  There's also no guarantee that there *is* a leader (for example, if applying the truncation command takes long enough that followers trigger elections, we could be in a contested election).  It's very difficult to do anything useful with the raft leader in a single pass; nearly everything related to this needs to be in a `SucceedsWithin` (and if you're going to do this you might as well not even inquire about the raft leader and poll the `FirstIndex`)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141)

**Comment by BramGruneir** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[storage/client_raft_log_queue_test.go, line 68 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141#-K3HQXU1Xb62Sub9qz07)** ([raw file](https://github.com/cockroachdb/cockroach/blob/3826c4d6d1dee8510c8a5bcf166bdaaf5647b7f9/storage/client_raft_log_queue_test.go#L68)):</sup>
indeed, removed


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141)

**Comment by BramGruneir** [comment]
Ok, I think this is ready to merge.  Can someone take one last pass?

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_[storage/client_raft_log_queue_test.go, line 68 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141#-K3HQXU1Xb62Sub9qz07:-K3Lvh5Q6E1-GwJfT6FI:-2030642927) ([raw file](https://github.com/cockroachdb/cockroach/blob/3826c4d6d1dee8510c8a5bcf166bdaaf5647b7f9/storage/client_raft_log_queue_test.go#L68)):_
Doesn't look like it got removed, and it still looks like a duplicate.

---

_[storage/client_test.go, line 575 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141#-K3LwKyFhMB2ZUVTvG3f:-K3LwKyFhMB2ZUVTvG3g:-146096406) ([raw file](https://github.com/cockroachdb/cockroach/blob/5476b8bce3c99d165fc346288a88f63de8c60926/storage/client_test.go#L575)):_
the error returned by this function is never not nil.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141)_

**Comment by BramGruneir** [comment]
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

_[storage/client_raft_log_queue_test.go, line 68 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141#-K3HQXU1Xb62Sub9qz07:-K3M0jmLe86zczl2YT5r:1831977685) ([raw file](https://github.com/cockroachdb/cockroach/blob/3826c4d6d1dee8510c8a5bcf166bdaaf5647b7f9/storage/client_raft_log_queue_test.go#L68)):_
removed - for reals this time

---

_[storage/client_test.go, line 573 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141#-K3HQRXfLeKvMGuW01md:-K3M0niHWFp6MoVTVlS7:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3826c4d6d1dee8510c8a5bcf166bdaaf5647b7f9/storage/client_test.go#L573)):_
Done.

---

_[storage/client_test.go, line 574 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141#-K3HPgDRDdXw85HwIx1Q:-K3M10eH7oosTWhR2-gv:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3826c4d6d1dee8510c8a5bcf166bdaaf5647b7f9/storage/client_test.go#L574)):_
Done.

---

_[storage/client_test.go, line 575 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141#-K3LwKyFhMB2ZUVTvG3f:-K3MDmgzQuoRuUbtvCPz:-1021436555) ([raw file](https://github.com/cockroachdb/cockroach/blob/5476b8bce3c99d165fc346288a88f63de8c60926/storage/client_test.go#L575)):_
you're right, panics on a failure.  removed the unneeded error

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141)_

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3141)_

**Pull request merged**
