### PR TITLE
sql/schemachanger: reorder args on Build, clone nodes, minor renaming

### PR DESCRIPTION
**Pull request by ajwerner**
Release note: None

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66837)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Review by fqazi — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r2, 12 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66837)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/schemachanger/scbuild/builder.go, line 67 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66837#-McyKh2y15sl-G478Mak:-McyKh2y15sl-G478Mal:b-ltbohr) ([raw file](https://github.com/cockroachdb/cockroach/blob/65df23cd57199d83e5030e1a629bc2ba8b051a2e/pkg/sql/schemachanger/scbuild/builder.go#L67)):*
> ```Go
> 	// outputNodes contains the internal state when building targets for an individual
> 	// statement.
> 	outputNodes scpb.State
> ```

Nit: Do we want to rename these to outputState?
___
*[pkg/sql/schemachanger/scbuild/builder.go, line 117 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66837#-McyKo4WBRXZlIKIqw3n:-McyKo4WBRXZlIKIqw3o:b-q82lep) ([raw file](https://github.com/cockroachdb/cockroach/blob/65df23cd57199d83e5030e1a629bc2ba8b051a2e/pkg/sql/schemachanger/scbuild/builder.go#L117)):*
> ```Go
> func Build(
> 	ctx context.Context, dependencies Dependencies, initial scpb.State, n tree.Statement,
> ) (outputNodes scpb.State, err error) {
> ```

Nit: Similar here
___
*[pkg/sql/schemachanger/scbuild/builder_test.go, line 97 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66837#-McyKykJEQBTlbMbBPIJ:-McyKykJEQBTlbMbBPIK:bsa82ig) ([raw file](https://github.com/cockroachdb/cockroach/blob/65df23cd57199d83e5030e1a629bc2ba8b051a2e/pkg/sql/schemachanger/scbuild/builder_test.go#L97)):*
> ```Go
> 				stmts, err := parser.Parse(d.Input)
> 				require.NoError(t, err)
> 				var outputNodes scpb.State
> ```

Nit: rename
___
*[pkg/sql/schemachanger/scplan/plan_test.go, line 97 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66837#-McyK_FPDeDlRGRX11UG:-McyK_FPDeDlRGRX11UH:b-u6g3iv) ([raw file](https://github.com/cockroachdb/cockroach/blob/65df23cd57199d83e5030e1a629bc2ba8b051a2e/pkg/sql/schemachanger/scplan/plan_test.go#L97)):*
> ```Go
> 				stmts, err := parser.Parse(d.Input)
> 				require.NoError(t, err)
> 				var outputNodes scpb.State
> ```

Nit: outputState?

**Review by fqazi — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66837)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by ajwerner** [comment]
bors r=fqazi

**Pull request merged**
