### PR TITLE
sql: Allow srf overloads with different number of return columns

### LINKED ISSUE #41924: sql: the result column name for json_array_elements should be "value"
Found by @drewdeally 

```sql
 with a_table(jdata) as (
values (
    '{
        "uid":14105529,
        "o":[
            {"mid":6551,"ac":1913,"ip":"144.36.233.44","adw":5,"at":133000,"ad":151015,"aid":0},
            {"mid":7552,"ac":1913,"ip":"144.36.233.44","adw":5,"at":133000,"ad":151015,"aid":0},
            {"mid":7553,"ac":1913,"ip":"144.36.233.44","adw":5,"at":133000,"ad":151015,"aid":0}
        ] }'::jsonb
    )
)
select jdata->'uid' as uid, value
from a_table, jsonb_array_elements(jdata->'o')
where (value->>'mid')::int > 7000;
```

error:
```
pq: column "value" does not exist
```

This is because the result column for json_array_elements is not called "value" by default, unlike in pg.

Workaround is to use `jsonb_array_elements(jdata->'o') as value`

### PR DESCRIPTION
**Pull request by giorgosp**
Until now, return labels for an srf were hardcoded in the
`FunctionProperties` and shared among all function overloads. These
would also indicate the number of return columns of the function.

This commit removes the `FunctionProperties.ReturnLabels` to
allow different overloads to have different number of return columns/labels.

A multi-column generator must  declare the return labels in the type returned
by `ValueGenerator.ResolvedType()`.
A single column generator may not define the return labels, and the function's
name will be used as the label of the single column.

Release note: None

Fixes #41924

### CODE REVIEW

**Comment by giorgosp** [comment]
This PR is a possible way to unblock the implementation of #41434 .

**Review by rytaft — APPROVED** [review]
:lgtm: nice!

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-:-Lrtoh9D-I5J6uETFZTn:b-7yytuz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @giorgosp, @jordanlewis, and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/scope.go, line 978 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-LrtjdgJ5qkHJwVo_iS4:-LrtjdgJ5qkHJwVo_iS5:b-gjzsgb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9aabf9804f29b59bd49c7ed1b868ba9ded14b34/pkg/sql/opt/optbuilder/scope.go#L978)):*
> ```Go
> 	var outCol *scopeColumn
> 
> 	if len(typedFunc.(*tree.FuncExpr).ResolvedType().TupleLabels()) == 0 {
> ```

[nit] since we're using it in so many places here and below, maybe assign `typedFunc.(*tree.FuncExpr)` to a variable and use that instead

**Review by giorgosp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41861)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/optbuilder/scope.go, line 978 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-LrtjdgJ5qkHJwVo_iS4:-Lrymbn52l0EqoEzjmFA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9aabf9804f29b59bd49c7ed1b868ba9ded14b34/pkg/sql/opt/optbuilder/scope.go#L978)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] since we're using it in so many places here and below, maybe assign `typedFunc.(*tree.FuncExpr)` to a variable and use that instead
</blockquote></details>

Done.

**Comment by giorgosp** [comment]
Hi @rytaft, thank you!
Actually I found a problem. The tests for `crdb_internal.unary_table()` fail, but am not sure what would be the proper way to fix it. There are no other references of this method other than the tests. Could you help me with this?

**Comment by giorgosp** [comment]
I pushed a fix but it may seem to hacky.

**Review by rytaft — APPROVED** [review]
:lgtm: I don't think it's more hacky than what we had before

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-:-LrzDUno0qecbt8jEGgZ:b-n447k5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @giorgosp, @jordanlewis, and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/scope.go, line 980 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-LrzCYZPB90gwWo8hzAy:-LrzCYZPB90gwWo8hzAz:b-d9iyx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dfdfddcc6d8f1fbf392872dca8aadc51ec2cb71/pkg/sql/opt/optbuilder/scope.go#L980)):*
> ```
> len(typedFuncExpr.ResolvedType().TupleLabels()) == 0 && typedFuncExpr.ResolvedType() != types.EmptyTuple
> ```

Since you're doing this check twice, I'd put this into a helper function like `shouldUseDefaultColumnName` or something like that....

**Review by giorgosp — COMMENTED** [review]
Thank you @rytaft! Shall I merge with bors

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-:-Ls0uZ69EIAqkbzVuCQg:b-9iu9rk)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/optbuilder/scope.go, line 980 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-LrzCYZPB90gwWo8hzAy:-Ls0u0ymCDWYwQVvwbQP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dfdfddcc6d8f1fbf392872dca8aadc51ec2cb71/pkg/sql/opt/optbuilder/scope.go#L980)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

> ```
> len(typedFuncExpr.ResolvedType().TupleLabels()) == 0 && typedFuncExpr.ResolvedType() != types.EmptyTuple
> ```

Since you're doing this check twice, I'd put this into a helper function like `shouldUseDefaultColumnName` or something like that....

</blockquote></details>

Done.

**Review by rytaft — COMMENTED** [review]
Looks like bors is still disabled, so you can merge with the big green button

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-:-Ls21T71BRn7dM7N0MTK:be53ke7)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @giorgosp, @jordanlewis, and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/util.go, line 218 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-Ls21IJACBq-SNavMVPQ:-Ls21IJACBq-SNavMVPR:b-pgow5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/776489a587a8bb1c30f0080f2376e6f9cc2bfe5d/pkg/sql/opt/optbuilder/util.go#L218)):*
> ```Go
> }
> 
> func (b *Builder) shouldUseDefaultColumnName(texpr tree.TypedExpr) bool {
> ```

[nit] could use a short comment describing the purpose of the function

**Review by giorgosp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41861)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/optbuilder/util.go, line 218 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-Ls21IJACBq-SNavMVPQ:-Ls76iaCBjm6T999opXQ:b2nhlkw) ([raw file](https://github.com/cockroachdb/cockroach/blob/776489a587a8bb1c30f0080f2376e6f9cc2bfe5d/pkg/sql/opt/optbuilder/util.go#L218)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] could use a short comment describing the purpose of the function
</blockquote></details>

Ok!

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-:-Ls9LdRw4UJ6s6vJv-Gs:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

**Review by RaduBerinde — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41861)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @giorgosp and @jordanlewis)

___
*[pkg/sql/sem/builtins/generator_builtins.go, line 214 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-LsEVvyS6FU1b0d6PyGf:-LsEVvyS6FU1b0d6PyGg:b4fmxcq) ([raw file](https://github.com/cockroachdb/cockroach/blob/eba761b60043011af4e9c09f1443ba4136911027/pkg/sql/sem/builtins/generator_builtins.go#L214)):*
> ```Go
> 
> 	"json_array_elements":       makeBuiltin(genProps(), jsonArrayElementsImpl),
> 	"jsonb_array_elements":      makeBuiltin(genProps(), jsonArrayElementsImpl),
> ```

We are removing the return labels. It is a bug that we are not using them (41924) - we do need them, at least for the cases where it doesn't match the function name (which is the label we are currently using).

**Review by giorgosp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41861)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/sem/builtins/generator_builtins.go, line 214 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-LsEVvyS6FU1b0d6PyGf:-LsHtMtO54L9EVjsNqn7:b-w7b0fp) ([raw file](https://github.com/cockroachdb/cockroach/blob/eba761b60043011af4e9c09f1443ba4136911027/pkg/sql/sem/builtins/generator_builtins.go#L214)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We are removing the return labels. It is a bug that we are not using them (41924) - we do need them, at least for the cases where it doesn't match the function name (which is the label we are currently using).
</blockquote></details>

Thanks for the heads up! I will rethink this PR

**Comment by rytaft** [comment]
Hi @giorgosp, are you still planning to finish this PR? If not, please close, and I'll address #41924 separately. Thank you!

**Comment by giorgosp** [comment]
Hi @rytaft, sorry for taking me so long. Yes I am working on it. I will probably need the weekend before I send an update, is it ok?

**Comment by rytaft** [comment]
@giorgosp That's fine, thanks for the update!

**Comment by giorgosp** [comment]
Hi @rytaft  @RaduBerinde, I have updated this PR (again, sorry for taking me so long).

It can be read commit-by-commit. The first one fixes #41924, utilising the `ReturnLabels` without major refactorings.

The second commit makes `ReturnLabels` optional and necessary only in cases where they don't match the function's name, as @RaduBerinde mentioned. Maybe the variable `ReturnLabels` should be renamed or become just string instead of array, since for multiple-column return types the labels must be declared in the function's resolved type, which must be a labeled tuple.

**Review by rytaft — COMMENTED** [review]
Thanks for fixing this!

Looks like the build is failing on some opt tests which need to be updated. To rewrite the test files, you can run `make test PKG=./pkg/sql/opt/... TESTFLAGS='-rewrite=true'`

Can you update the PR message to also include the line "Fixes #41924"? That will cause the issue to close automatically when this merges.

> Reviewed 1 of 8 files at r5, 7 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-:-Lv5aRVoAizmSP2kB4B5:bwk6tbu)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @giorgosp, @jordanlewis, and @RaduBerinde)

___
*[pkg/sql/logictest/testdata/logic_test/json_builtins, line 485 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-Lv5esLU92kgHVwWKA02:-Lv5esLU92kgHVwWKA03:b7ixt63) ([raw file](https://github.com/cockroachdb/cockroach/blob/473ef676da4596e7ea6e8b06bba32f7bf4f1337e/pkg/sql/logictest/testdata/logic_test/json_builtins#L485)):*
> ```
> # Keys are sorted.
> query T
> SELECT json_object_keys('{"a": 1, "1": 2, "3": {"4": 5, "6": 7}}'::JSON)
> ```

would be good to check the column names for this function too
___
*[pkg/sql/logictest/testdata/logic_test/json_builtins, line 789 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-Lv5btYIDJba28tFNFAW:-Lv5btYJ-KPFszkes6_S:b3rqy91) ([raw file](https://github.com/cockroachdb/cockroach/blob/473ef676da4596e7ea6e8b06bba32f7bf4f1337e/pkg/sql/logictest/testdata/logic_test/json_builtins#L789)):*
> ```
> 
> query TT colnames
> SELECT * FROM json_each('{"f1":[1,2,3],"f2":{"f3":1},"f4":null,"f5":99,"f6":"stringy"}') q
> ```

While you're fixing this one, would be great to fix the other cases in this file. (lower case "from" -> upper case "FROM")
___
*[pkg/sql/logictest/testdata/logic_test/json_builtins, line 839 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-Lv5caJY22YAn-_tl7Ky:-Lv5caJY22YAn-_tl7Kz:b-l6ggxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/473ef676da4596e7ea6e8b06bba32f7bf4f1337e/pkg/sql/logictest/testdata/logic_test/json_builtins#L839)):*
> ```
> 
> query TT
> SELECT * from jsonb_each_text('{}') q
> ```

This test appears to be a duplicate with the one above (not your fault, but since you're editing this file anyway, can you fix it?)
___
*[pkg/sql/sem/builtins/generator_builtins.go, line 705 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-Lv5gRlf3p_q2iUpX9cL:-Lv5gRlf3p_q2iUpX9cM:b-epfdeh) ([raw file](https://github.com/cockroachdb/cockroach/blob/473ef676da4596e7ea6e8b06bba32f7bf4f1337e/pkg/sql/sem/builtins/generator_builtins.go#L705)):*
> ```Go
> var jsonArrayGeneratorType = types.Jsonb
> 
> var jsonObjectKeysGeneratorLabels = []string{"json_object_keys"}
> ```

This should be located down with the other code for jsonObjectKeys. But also, seems unnecessary. Why not just use genProps() for `json_object_keys`? (And have you confirmed that Postgres doesn't use "value" here, too?)

**Review by giorgosp — COMMENTED** [review]
I have referenced the issue in the commit so I think it will be closed but will update the description to be sure.

Thank you for the hint for the failing tests!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-:-Lv6Bqi_7vk6pMXNEoVh:b-sps0b3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/json_builtins, line 485 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-Lv5esLU92kgHVwWKA02:-Lv6CMhf8tyYoCgHnM0q:b-xl5kx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/473ef676da4596e7ea6e8b06bba32f7bf4f1337e/pkg/sql/logictest/testdata/logic_test/json_builtins#L485)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

would be good to check the column names for this function too
</blockquote></details>

Yeap I checked all the json functions defined in `pkg/sql/sem/builtins/generator_builtins.go`.
___
*[pkg/sql/logictest/testdata/logic_test/json_builtins, line 789 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-Lv5btYIDJba28tFNFAW:-Lv6CoGeAmFIcu0Gr2eh:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/473ef676da4596e7ea6e8b06bba32f7bf4f1337e/pkg/sql/logictest/testdata/logic_test/json_builtins#L789)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

While you're fixing this one, would be great to fix the other cases in this file. (lower case "from" -> upper case "FROM")
</blockquote></details>

Done!
___
*[pkg/sql/logictest/testdata/logic_test/json_builtins, line 839 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-Lv5caJY22YAn-_tl7Ky:-Lv6D0UM9VQdg4ywx5zh:b-80tlqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/473ef676da4596e7ea6e8b06bba32f7bf4f1337e/pkg/sql/logictest/testdata/logic_test/json_builtins#L839)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This test appears to be a duplicate with the one above (not your fault, but since you're editing this file anyway, can you fix it?)
</blockquote></details>

Sure!
___
*[pkg/sql/sem/builtins/generator_builtins.go, line 705 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-Lv5gRlf3p_q2iUpX9cL:-Lv6DRrd2qFoynC2itrf:b-asijqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/473ef676da4596e7ea6e8b06bba32f7bf4f1337e/pkg/sql/sem/builtins/generator_builtins.go#L705)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This should be located down with the other code for jsonObjectKeys. But also, seems unnecessary. Why not just use genProps() for `json_object_keys`? (And have you confirmed that Postgres doesn't use "value" here, too?)
</blockquote></details>

Good catch, it was not needed.

**Review by rytaft — COMMENTED** [review]
> Reviewed 9 of 9 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41861)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @giorgosp and @jordanlewis)

___
*[pkg/sql/logictest/testdata/logic_test/json_builtins, line 485 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-Lv5esLU92kgHVwWKA02:-Lv6YifX8fZVegcrteaP:bclurcs) ([raw file](https://github.com/cockroachdb/cockroach/blob/473ef676da4596e7ea6e8b06bba32f7bf4f1337e/pkg/sql/logictest/testdata/logic_test/json_builtins#L485)):*
<details><summary><i>Previously, giorgosp (George Papadrosou) wrote…</i></summary><blockquote>

Yeap I checked all the json functions defined in `pkg/sql/sem/builtins/generator_builtins.go`.
</blockquote></details>

Sorry, I meant include the "colnames" directive in this test and add one test with `SELECT FROM` if it doesn't exist to show that the column name matches what you expect.

**Review by giorgosp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41861)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/json_builtins, line 485 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-Lv5esLU92kgHVwWKA02:-Lv6iPUrE_QNv05BU-yt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/473ef676da4596e7ea6e8b06bba32f7bf4f1337e/pkg/sql/logictest/testdata/logic_test/json_builtins#L485)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Sorry, I meant include the "colnames" directive in this test and add one test with `SELECT FROM` if it doesn't exist to show that the column name matches what you expect.
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm_strong: 

> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-:-Lv7EUTp-QLulTkwhBal:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Review by rytaft — APPROVED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-:-Lv7PPZ4B0LuSne0jKKe:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Review by rytaft — APPROVED** [review]
Thanks for your contribution!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41861#-:-Lv7PU7Z9bl76myY3bU2:b-8ctfzn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Pull request merged**
