### PR TITLE
Add generated sql.go file.

### PR DESCRIPTION
**Pull request by petermattis**
Remove sql/parser/Makefile. This matches up with recommended go practice
of adding generated files to the version control system.

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM

**Comment by petermattis** [comment]
Btw, I've got another change (not sent for review yet) that does this for .pb.{go,cc,h} files. That's quite a bit more generated code, yet if it makes sense here I think it makes sense there as well.

**Comment by bdarnell** [comment]
I think I agree with checking in the generated code for `*.pb.*` files. I'm not sure if it's feasible to go all the way to `go get` compatibility due to our dependencies, but approaching that state is generally a good idea for maximum tool compatibility. (I've just updated my emacs setup and there are a bunch of IDE-like features available, although they don't always work with cockroach because of our non-standard build system. The biggest blocker is actually that a lot of the tools don't understand the cgo pkg-config directive)

**Comment by petermattis** [comment]
Yeah, I don't think we can become "go get" compatible as long as we're using rocksdb and our current vendoring approach. But this is at least moving us in that direction.

What are the new emacs IDE-like features? Is this a new package?

**Comment by bdarnell** [comment]
Package `go-projectile` bundles a bunch of separate packages; the newest ones are `gorename` (safe renaming) and `oracle` (find references/callers, etc). It was much easier to set things up this way when I switched laptops than to recreate the ad-hoc stuff I had done before.

**Pull request merged**
