### PR TITLE
sql: add a new optional secondary logger for internal slow queries

### LINKED ISSUE #50201: sql: add option to remove internal queries from slow query log
The new slow query log allows developers to log all queries that take longer that an user specified time threshold. For example, you could set the threshold to 100ms:
`SET CLUSTER SETTING sql.log.slow_query.latency_threshold = '100ms';`

These queries are then logged in the slow query log `cockroach-sql-slow.log`

Today, both internal and user-specified queries are logged. This is good because both queries can impact cluster performance. However, users have limited ability to influence internal queries and will need to report them to CRDB to improve upon them. Further, it can be hard for the user to find their own queries if many internal queries show up. Look at this gist of the 500+ queries that show up when restoring tpc-c data with 100ms threshold set https://gist.github.com/awoods187/e0362023029b3ed509cb6cefcf6024ea (note this is only halfway through the restore).

I think we should seek out a solution that makes it easier to see user (and not internal) queries. We could:

1. Make an additional log that only shows internal queries and removes them from the slow log. Something like `cockroach-sql-slow-internal-only.log`
2. Add an additional field specifying if its internal or not that allows for filtering 
3. Add a cluster setting to add internal queries to the log (or one to remove). Something like ``SET CLUSTER SETTING sql.log.slow_query.internal = 'true';`

### PR DESCRIPTION
**Pull request by arulajmani**
Previously, all slow queries were logged to the slow query log,
regardless of whether they were internal or from the user. This made
it easy for user queries to get lost in the log. This patch adds
an optional cluster setting, `sql.log.slow_query.internal`. When set to
true, all internal queries that have service latency above the slow
query log threshold will be logged to
`cockroach-slow-log-internal-only.log` instead of
`cockroach-slow-log.log`. This new setting is a no-op if the slow query
log hasn't been turned on, i.e there is no latency threshold set.

Closes #50201

Release note (sql change): adds a new cluster setting
`sql.log.slow_query.internal` which when turned on in conjunction with
the slow query log causes internal queries to be logged to an internal
query only slow query log instead of the main slow query log.

### CODE REVIEW

**Comment by awoods187** [comment]
Is the new default behavior that internal are not shown? I think that should be the default and you should need to opt into showing internal.

**Comment by arulajmani** [comment]
Updated the implementation to completely remove internal queries from the slow query log. Now, only if both the latency threshold and the new internal slow query log opt in cluster setting is set will internal queries be logged to the new log.

**Comment by arulajmani** [comment]
Rebased this as it had a conflict. Should be good for a review @solongordon

**Review by solongordon — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52377)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @solongordon)

___
*[pkg/sql/exec_log.go, line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52377#-MEyArngDEKxTZ_wtorY:-MEyArngDEKxTZ_wtorZ:b1oesk0) ([raw file](https://github.com/cockroachdb/cockroach/blob/71d1502e0e15913f8dbfc0c9e3c297d946b0d533/pkg/sql/exec_log.go#L211)):*
> ```Go
> 		if execType == executorTypeInternal && slowInternalQueryLogEnabled {
> 			logger = p.execCfg.SlowInternalQueryLogger
> 		}
> ```

Hm, it seems like this is written in such a way that if the internal query log is not enabled, internal queries will still end up in the regular slow query log. Could you check that?

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52377)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sql/exec_log.go, line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52377#-MEyArngDEKxTZ_wtorY:-MF3PURu-b3zhn8-4WX5:bmt1sb9) ([raw file](https://github.com/cockroachdb/cockroach/blob/71d1502e0e15913f8dbfc0c9e3c297d946b0d533/pkg/sql/exec_log.go#L211)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Hm, it seems like this is written in such a way that if the internal query log is not enabled, internal queries will still end up in the regular slow query log. Could you check that?
</blockquote></details>

I think `logger` would be `nil` in that case, as we won't enter any if condition, and therefore nothing will be logged, right? I tested it out to confirm, and it works as expected -- 
- external queries are logged to the regular slow query log if they don't meet the threshold (and the threshold is set). 
- internal queries are logged to the internal slow query log if they don't meet the threshold (and the threshold is set) AND the user has explicitly opted into logging internal queries.

**Review by solongordon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52377)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec_log.go, line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52377#-MEyArngDEKxTZ_wtorY:-MF66gjs52-bM8EuXLLr:b-kkk5ri) ([raw file](https://github.com/cockroachdb/cockroach/blob/71d1502e0e15913f8dbfc0c9e3c297d946b0d533/pkg/sql/exec_log.go#L211)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I think `logger` would be `nil` in that case, as we won't enter any if condition, and therefore nothing will be logged, right? I tested it out to confirm, and it works as expected -- 
- external queries are logged to the regular slow query log if they don't meet the threshold (and the threshold is set). 
- internal queries are logged to the internal slow query log if they don't meet the threshold (and the threshold is set) AND the user has explicitly opted into logging internal queries. 
</blockquote></details>

Oh you're totally right, I misread. Carry on. :slightly_smiling_face:

**Comment by arulajmani** [comment]
TFTR!

bors r=solongordon

**Pull request merged**
