### PR TITLE
sql: fix bufferedWriter.Reset()

### PR DESCRIPTION
**Pull request by andreimatei**
It wasn't resetting anything.

### CODE REVIEW

**Comment by petermattis** [comment]
Was this causing a problem? If yes, shouldn't there be a test?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18009#-:-KsjjMcuXmVFkVPqeNek:bue83r2)*

**Comment by knz** [comment]
The change itself LGTM. Nice find! :100:

If this indeed fixes #17592 mention it in the PR description.

Of course, I agree with Peter this can use a test. :)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18009#-:-Ksjk5UZv0_k_x5s9NeU:b-dn6bp2)*

**Comment by andreimatei** [comment]
I don't think this fixes anything; this bufferedWriter (one of the _two_ buffered implementation we have, besides the main v3Conn one) is only used internally I think.
I sent this more to make a point :P. I happened to find it by chance by looking into the fact that `TestStreamingWireFailure` is flaky, which I also found by accident :)
I'll see about adding a test.

I believe we know what's causing #17592 btw and Jordan was working on a fix.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18009#-:-KsjlL_UjOkJLLK2-owY:bsak5eu)*

**Comment by knz** [comment]
Do you plan on merging this? (with a test?)

**Comment by andreimatei** [comment]
Yes, I will.

**Comment by andreimatei** [comment]
Added a test.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18009#-:-KsyEVxXuvZNOmaa7D3F:b-7gclag)*

**Pull request merged**
