### PR TITLE
roachtest: add test that switches the engine from RocksDB to

### PR DESCRIPTION
**Pull request by sumeerbhola**
Pebble and back, repeatedly, for each node

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
Looks very much like what I was expecting. A few minor comments. Did you find any problems?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45401#-:-M0xm2Yw-KA5-noCQzKl:bixmw16)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/cmd/roachtest/engine_switch.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45401#-M0xkgU10-xJvJwAdwmu:-M0xkgU10-xJvJwAdwmv:bnoe5ui) ([raw file](https://github.com/cockroachdb/cockroach/blob/88f13253f6dbb33e1d22dee1a5368d7cdffe0c7b/pkg/cmd/roachtest/engine_switch.go#L26)):*
> ```Go
> func registerEngineSwitch(r *testRegistry) {
> 	runEngineSwitch := func(ctx context.Context, t *test, c *cluster) {
> 		roachNodes := c.Range(1, c.spec.NodeCount-1)
> ```

If I'm reading this correct, this will result in a 2-node cluster. That won't be verify interesting as we'll never upreplicate onto the second node. I think you should create a 4-node roachprod cluster that translates into a 3-node CRDB cluster.
___
*[pkg/cmd/roachtest/engine_switch.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45401#-M0xkuj1BWD_-mSyFcNE:-M0xkuj1BWD_-mSyFcNF:b-qv551l) ([raw file](https://github.com/cockroachdb/cockroach/blob/88f13253f6dbb33e1d22dee1a5368d7cdffe0c7b/pkg/cmd/roachtest/engine_switch.go#L31)):*
> ```Go
> 		c.Put(ctx, cockroach, "./cockroach", roachNodes)
> 		c.Start(ctx, t, roachNodes)
> 		pebbleArgs := startArgs("--args=\"--storage-engine=pebble\"")
> ```

Are the quotes around `--storage-engine=pebble` necessary? I think they can be removed.
___
*[pkg/cmd/roachtest/engine_switch.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45401#-M0xldIY5rG_hRbrFsdw:-M0xldIY5rG_hRbrFsdx:b-d79wx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/88f13253f6dbb33e1d22dee1a5368d7cdffe0c7b/pkg/cmd/roachtest/engine_switch.go#L101)):*
> ```Go
> 					m.ExpectDeath()
> 					l.Printf("stopping node %d\n", node)
> 					return c.StopCockroachGracefullyOnNode(ctx, node)
> ```

Is this necessary for the test? If not, I think you should randomly select between a graceful stop and a hard stop.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45401)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

___
*[pkg/cmd/roachtest/engine_switch.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45401#-M0xmU9Z5csHoyr51GdF:-M0xmU9Z5csHoyr51GdG:b-6g3g0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/88f13253f6dbb33e1d22dee1a5368d7cdffe0c7b/pkg/cmd/roachtest/engine_switch.go#L105)):*
> ```Go
> 
> 				i := rng.Intn(len(roachNodes))
> 				var args option
> ```

I think you should explicitly use `--args=--storage-engine=rocksdb` which will override the `COCKROACH_STORAGE_ENGINE` env var. Let me double check that is the case. Yep, `COCKROACH_STORAGE_ENGINE=pebble roachprod start local --args=--storage-engine=rocksdb` uses RocksDB.

**Review by sumeerbhola — COMMENTED** [review]
Did not find any problems

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45401#-:-M0y0VkzEnT7-13Io7rf:b-kcmpdw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

___
*[pkg/cmd/roachtest/engine_switch.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45401#-M0xkgU10-xJvJwAdwmu:-M0xyUpoCHiVO3P2dy79:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/88f13253f6dbb33e1d22dee1a5368d7cdffe0c7b/pkg/cmd/roachtest/engine_switch.go#L26)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

If I'm reading this correct, this will result in a 2-node cluster. That won't be verify interesting as we'll never upreplicate onto the second node. I think you should create a 4-node roachprod cluster that translates into a 3-node CRDB cluster.
</blockquote></details>

Done
___
*[pkg/cmd/roachtest/engine_switch.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45401#-M0xkuj1BWD_-mSyFcNE:-M0xzLiJ7j1oBOaqDgou:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/88f13253f6dbb33e1d22dee1a5368d7cdffe0c7b/pkg/cmd/roachtest/engine_switch.go#L31)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Are the quotes around `--storage-engine=pebble` necessary? I think they can be removed.
</blockquote></details>

Done
___
*[pkg/cmd/roachtest/engine_switch.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45401#-M0xldIY5rG_hRbrFsdw:-M0y0AfrDkNJjSsdNGoC:b-2zhv44) ([raw file](https://github.com/cockroachdb/cockroach/blob/88f13253f6dbb33e1d22dee1a5368d7cdffe0c7b/pkg/cmd/roachtest/engine_switch.go#L101)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is this necessary for the test? If not, I think you should randomly select between a graceful stop and a hard stop.
</blockquote></details>

Is there an existing way to do a hard stop -- I couldn't spot it based on a quick scan of `cluster.go`.
___
*[pkg/cmd/roachtest/engine_switch.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45401#-M0xmU9Z5csHoyr51GdF:-M0xzDA914OtBsAabq8C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/88f13253f6dbb33e1d22dee1a5368d7cdffe0c7b/pkg/cmd/roachtest/engine_switch.go#L105)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think you should explicitly use `--args=--storage-engine=rocksdb` which will override the `COCKROACH_STORAGE_ENGINE` env var. Let me double check that is the case. Yep, `COCKROACH_STORAGE_ENGINE=pebble roachprod start local --args=--storage-engine=rocksdb` uses RocksDB.
</blockquote></details>

Done.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45401)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

___
*[pkg/cmd/roachtest/engine_switch.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45401#-M0xldIY5rG_hRbrFsdw:-M0yH2T37XP0-_-0vbsR:b-btb486) ([raw file](https://github.com/cockroachdb/cockroach/blob/88f13253f6dbb33e1d22dee1a5368d7cdffe0c7b/pkg/cmd/roachtest/engine_switch.go#L101)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is there an existing way to do a hard stop -- I couldn't spot it based on a quick scan of `cluster.go`.
</blockquote></details>

`c.Stop(ctx, node)`.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45401#-:-M0yHiSX04LBTXKHOUwJ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45401)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal and @petermattis)

___
*[pkg/cmd/roachtest/engine_switch.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45401#-M0xldIY5rG_hRbrFsdw:-M0zc01L0X14-oIZ61sl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/88f13253f6dbb33e1d22dee1a5368d7cdffe0c7b/pkg/cmd/roachtest/engine_switch.go#L101)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`c.Stop(ctx, node)`.
</blockquote></details>

Done.

**Pull request merged**
