### PR TITLE
c-deps: backport RocksDB range deletion performance fix

### LINKED ISSUE #24029: storage: dropping a large table will brick a cluster due to compactions
```shell
$ roachprod create USER-FOO -n10
$ roachprod run USER-FOO 'mkdir -p /mnt/data1/cockroach && gsutil -m -q cp -r gs://cockroach-fixtures/workload/bank/version=1.0.0,payload-bytes=10240,ranges=0,rows=65104166,seed=1/stores=10/$((10#$(hostname | grep -oE [0-9]+$)))/* /mnt/data1/cockroach'
```

Wait ~10m for stores to download. Then drop the 2TiB table:

```SQL
ALTER TABLE bank.bank EXPERIMENTAL CONFIGURE ZONE 'gc: {ttlseconds: 30}';
DROP TABLE bank.bank;
```

The cluster explodes a few minutes later as RocksDB tombstones pile up. I can no longer execute any SQL queries that read from/write to disk.

Very closely related to #21901, but thought I'd file a separate tracking issue. 

/cc @spencerkimball

### PR DESCRIPTION
**Pull request by benesch**
The current implementation of range deletion tombstones in RocksDB
suffers from a performance bug that causes excessive CPU usage on every
read operation in a database with many range tombstones. Dropping a
large table can easily result in several thousand range deletion
tombstones in one store, resulting in an unusable cluster as documented
in #24029.

Backport a refactoring of range deletion tombstone that fixes the
performance problem. This refactoring has also been proposed upstream as
facebook/rocksdb#4014.

A more minimal change was also proposed in facebook/rocksdb#3992--and
that patch better highlights the exact nature of the bug than the patch
backported here, for those looking to understand the problem. But this
refactoring, though more invasive, gets us one step closer to solving a
related problem where range deletions can cause excessively large
compactions (#26693). These large compactions do not appear to brick the
cluster but undoubtedly have some impact on performance.

Fix #24029.

Release note: None

### CODE REVIEW

**Comment by benesch** [comment]
CI passed so... :shipit:?

**Comment by petermattis** [comment]
I'm taking a look.

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26877#-:-LFZ989iD-EKLLZWBGki:b-zaqdhy)*

**Comment by petermattis** [comment]
I left some comments on the upstream PR.

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26877#-:-LFZLzRNCvm5Co3FjYS7:b-dtedfq)*

**Comment by benesch** [comment]
This was taken care of by #27520. h/t @petermattis.

**Pull request closed without merging**
