### PR TITLE
Makefile: simplify `stress{,race}` using `-exec`

### PR DESCRIPTION
**Pull request by tamird**
Release note: None

### CODE REVIEW

**Review by benesch — CHANGES_REQUESTED** [review]
:tada: thank you! See below for a buglet though.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27283#-:-LH-4y6C3kGjNrSuZxMw:bd722rz)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[Makefile, line 886 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27283#-LH-485-8Cy8q-KEjU60:-LH-48500y0KG2RE58VF:bc894g3) ([raw file](https://github.com/cockroachdb/cockroach/blob/36fee5ce8c20888701a05291ffae787f105a6121/Makefile#L886)):*
> ```Makefile
> 
> stressrace: ## Run tests under stress with the race detector enabled.
> stressrace: stress
> ```

This doesn't do quite what you want. It inherits the variable definitions but also causes `stressrace` to stress the test twice:

```
$ make stressrace PKG=./pkg/workload STRESSFLAGS='-maxruns 1'
Running make with -j8
GOPATH set to /Users/benesch/go
go test -race -exec 'stress -maxruns 1' -tags ' make x86_64_apple_darwin17.5.0' -ldflags ' -X github.com/cockroachdb/cockroach/pkg/build.typ=development -X "github.com/cockroachdb/cockroach/pkg/build.tag=v2.1.0-alpha.20180702-301-g36fee5ce8" -X "github.com/cockroachdb/cockroach/pkg/build.rev=36fee5ce8c20888701a05291ffae787f105a6121" -X "github.com/cockroachdb/cockroach/pkg/build.cgoTargetTriple=x86_64-apple-darwin17.5.0"   -X "github.com/cockroachdb/cockroach/pkg/build.tag=v2.1.0-alpha.20180702-301-g36fee5ce8" -X "github.com/cockroachdb/cockroach/pkg/build.rev=36fee5ce8c20888701a05291ffae787f105a6121" -X "github.com/cockroachdb/cockroach/pkg/build.cgoTargetTriple=x86_64-apple-darwin17.5.0"  ' -run "."  -timeout 25m ./pkg/workload -v 
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
1 runs completed, 0 failures, over 12s
SUCCESS
ok  	github.com/cockroachdb/cockroach/pkg/workload	12.118s
go test -race -tags ' make x86_64_apple_darwin17.5.0' -ldflags ' -X github.com/cockroachdb/cockroach/pkg/build.typ=development -X "github.com/cockroachdb/cockroach/pkg/build.tag=v2.1.0-alpha.20180702-301-g36fee5ce8" -X "github.com/cockroachdb/cockroach/pkg/build.rev=36fee5ce8c20888701a05291ffae787f105a6121" -X "github.com/cockroachdb/cockroach/pkg/build.cgoTargetTriple=x86_64-apple-darwin17.5.0"  ' -run "."  -timeout 25m ./pkg/workload 
ok  	github.com/cockroachdb/cockroach/pkg/workload	4.305s
```

I think you want something like this:

```
stress: ## Run tests under stress.

stress stressrace: override GOFLAGS += -exec 'stress $(STRESSFLAGS)'
stress stressrace: override TESTFLAGS += -v # necessary for interactive output from `stress`

stressrace: ## Run tests under stress with the race detector enabled.
stressrace: override GOFLAGS += -race
stressrace: TESTTIMEOUT := $(RACETIMEOUT)
```

**Comment by tamird** [comment]
Ah, very good. Updated!

**Review by tamird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27283)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[Makefile, line 886 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27283#-LH-485-8Cy8q-KEjU60:-LH-7RpI49XXdnMJ-FWd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/36fee5ce8c20888701a05291ffae787f105a6121/Makefile#L886)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This doesn't do quite what you want. It inherits the variable definitions but also causes `stressrace` to stress the test twice:

```
$ make stressrace PKG=./pkg/workload STRESSFLAGS='-maxruns 1'
Running make with -j8
GOPATH set to /Users/benesch/go
go test -race -exec 'stress -maxruns 1' -tags ' make x86_64_apple_darwin17.5.0' -ldflags ' -X github.com/cockroachdb/cockroach/pkg/build.typ=development -X "github.com/cockroachdb/cockroach/pkg/build.tag=v2.1.0-alpha.20180702-301-g36fee5ce8" -X "github.com/cockroachdb/cockroach/pkg/build.rev=36fee5ce8c20888701a05291ffae787f105a6121" -X "github.com/cockroachdb/cockroach/pkg/build.cgoTargetTriple=x86_64-apple-darwin17.5.0"   -X "github.com/cockroachdb/cockroach/pkg/build.tag=v2.1.0-alpha.20180702-301-g36fee5ce8" -X "github.com/cockroachdb/cockroach/pkg/build.rev=36fee5ce8c20888701a05291ffae787f105a6121" -X "github.com/cockroachdb/cockroach/pkg/build.cgoTargetTriple=x86_64-apple-darwin17.5.0"  ' -run "."  -timeout 25m ./pkg/workload -v 
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
1 runs completed, 0 failures, over 12s
SUCCESS
ok  	github.com/cockroachdb/cockroach/pkg/workload	12.118s
go test -race -tags ' make x86_64_apple_darwin17.5.0' -ldflags ' -X github.com/cockroachdb/cockroach/pkg/build.typ=development -X "github.com/cockroachdb/cockroach/pkg/build.tag=v2.1.0-alpha.20180702-301-g36fee5ce8" -X "github.com/cockroachdb/cockroach/pkg/build.rev=36fee5ce8c20888701a05291ffae787f105a6121" -X "github.com/cockroachdb/cockroach/pkg/build.cgoTargetTriple=x86_64-apple-darwin17.5.0"  ' -run "."  -timeout 25m ./pkg/workload 
ok  	github.com/cockroachdb/cockroach/pkg/workload	4.305s
```

I think you want something like this:

```
stress: ## Run tests under stress.

stress stressrace: override GOFLAGS += -exec 'stress $(STRESSFLAGS)'
stress stressrace: override TESTFLAGS += -v # necessary for interactive output from `stress`

stressrace: ## Run tests under stress with the race detector enabled.
stressrace: override GOFLAGS += -race
stressrace: TESTTIMEOUT := $(RACETIMEOUT)
```
</blockquote></details>

Done.

**Review by benesch — APPROVED** [review]
:lgtm: thank you!

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27283#-:-LH-844gA5b9OWbwiRUE:bro3093)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by tamird** [comment]
bors r=benesch

**Pull request merged**
