### PR TITLE
distsql: Use nodedialer instead of GRPCDial

### PR DESCRIPTION
**Pull request by bdarnell**
Due to the distribution of planning and the fact that node addresses
are sent over the wire, the old interface is still supported for
mixed-version clusters.

Release note: None

First three commits are #27423.

### CODE REVIEW

**Review by tbg — CHANGES_REQUESTED** [review]
:LGTM: mod what looks like two unresolved TODOs.

> Reviewed 2 of 2 files at r1, 5 of 5 files at r2, 10 of 10 files at r3, 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27452#-:-LHXkfPW369jBjKhE9N1:b3lx07i)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/kv/transport.go, line 217 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27452#-LHXjWXO98segvFDFsJr:-LHXjWXP72OaBY8mU-Fu:b-82oqa1) ([raw file](https://github.com/cockroachdb/cockroach/blob/28284001da22c01147bfd422818d330ff39722b2/pkg/kv/transport.go#L217)):*
> ```Go
> 		}
> 		reply, err := iface.Batch(ctx, &client.args)
> 		// TODO fastpath: return here for local
> ```

Ping.
___
*[pkg/rpc/nodedialer/nodedialer.go, line 73 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27452#-LHXjG4gCfcrdiuX8vjm:-LHXjG4gCfcrdiuX8vjn:bb7csn9) ([raw file](https://github.com/cockroachdb/cockroach/blob/28284001da22c01147bfd422818d330ff39722b2/pkg/rpc/nodedialer/nodedialer.go#L73)):*
> ```Go
> // node first becomes unreachable or reachable.
> func (n *Dialer) Dial(ctx context.Context, nodeID roachpb.NodeID) (_ *grpc.ClientConn, err error) {
> 	if n == nil && n.resolver == nil {
> ```

`||`
___
*[pkg/rpc/nodedialer/nodedialer.go, line 144 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27452#-LHXjNlI2ylDdYs4LfEQ:-LHXjNlI2ylDdYs4LfER:b-80z19o) ([raw file](https://github.com/cockroachdb/cockroach/blob/28284001da22c01147bfd422818d330ff39722b2/pkg/rpc/nodedialer/nodedialer.go#L144)):*
> ```Go
> 		localCtx := grpcutil.NewLocalRequestContext(ctx)
> 
> 		//gt.opts.metrics.LocalSentCount.Inc(1)
> ```

TODO?
___
*[pkg/sql/distsqlrun/data.proto, line 105 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27452#-LHXju3Z3-JL5ngikEh8:-LHXju3_4HotYyBYxhSr:bsazwwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9cd16e2b44b64785c84a6dd9871d06fddb7f0e9/pkg/sql/distsqlrun/data.proto#L105)):*
> ```protobuf
>                                      (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/roachpb.NodeID"];
>   // Serving address for the target host. Used by 2.0 nodes instead of target_node_id.
>   // TODO(bdarnell): Remove in 2.1
> ```

Can only be removed after 2.1 (i.e. in 2.2).
___
*[pkg/sql/distsqlrun/outbox.go, line 28 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27452#-LHXk7_8Ag3gMvcRprs2:-LHXk7_8Ag3gMvcRprs3:bsoysyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9cd16e2b44b64785c84a6dd9871d06fddb7f0e9/pkg/sql/distsqlrun/outbox.go#L28)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/util/log"
> 	"github.com/cockroachdb/cockroach/pkg/util/timeutil"
> 	grpc "google.golang.org/grpc"
> ```

nit: newline before
___
*[pkg/sql/distsqlrun/outbox_test.go, line 40 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27452#-LHXkJn12dBbqUrEpb12:-LHXkJn12dBbqUrEpb13:bxrt4pr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9cd16e2b44b64785c84a6dd9871d06fddb7f0e9/pkg/sql/distsqlrun/outbox_test.go#L40)):*
> ```Go
> const staticNodeID roachpb.NodeID = 3
> 
> // staticAddressResolver maps staticNodeID to the given address
> ```

nit: dot.

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27452)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/kv/transport.go, line 217 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27452#-LHXjWXO98segvFDFsJr:-LHYu8GJ3HMYKBelr5sn:bhmry2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/28284001da22c01147bfd422818d330ff39722b2/pkg/kv/transport.go#L217)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Ping.
</blockquote></details>

Done (although it's a bit of a hack. None of the options here are appealing, and I don't want to undertake the refactoring necessary for a non-hacky solution while the rangefeed additions to InternalServer are underway). 
___
*[pkg/rpc/nodedialer/nodedialer.go, line 73 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27452#-LHXjG4gCfcrdiuX8vjm:-LHYvLctBT3y0COJgTiO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/28284001da22c01147bfd422818d330ff39722b2/pkg/rpc/nodedialer/nodedialer.go#L73)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

`||`
</blockquote></details>

Done.
___
*[pkg/rpc/nodedialer/nodedialer.go, line 144 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27452#-LHXjNlI2ylDdYs4LfEQ:-LHYwAV527mJYNEF35b9:b-igcvdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/28284001da22c01147bfd422818d330ff39722b2/pkg/rpc/nodedialer/nodedialer.go#L144)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

TODO?
</blockquote></details>

Fixed (using the same hack as above).
___
*[pkg/sql/distsqlrun/data.proto, line 105 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27452#-LHXju3Z3-JL5ngikEh8:-LHYvSFr1KqX04-jioPv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9cd16e2b44b64785c84a6dd9871d06fddb7f0e9/pkg/sql/distsqlrun/data.proto#L105)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Can only be removed after 2.1 (i.e. in 2.2).
</blockquote></details>

Done.

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r5, 9 of 9 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27452#-:-LHZ1UV3AV47okVOYQaZ:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by tbg — APPROVED** [review]
> Reviewed 25 of 25 files at r7, 5 of 5 files at r8, 10 of 10 files at r9, 9 of 9 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27452)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by bdarnell** [comment]
bors r=tschottdorf

**Comment by bdarnell** [comment]
bors r=tschottdorf

Retrying due to #27523

**Pull request merged**
