### PR TITLE
Replace %v with %s.

### PR DESCRIPTION
**Pull request by petermattis**

### CODE REVIEW

**Comment by BramGruneir** [comment]
LGTM

**Comment by tamird** [comment]
LGTM surprised this didn't affect semantics at all

**Comment by petermattis** [comment]
@tamird http://play.golang.org/p/9o-jGgW4e0

```
4. If an operand implements method String() string, that method will be invoked to convert the object to a string, which will then be formatted as required by the verb (if any).
```

`%s` seems to force calling `String()`, while `%v` only calls `String()` if it exists on exactly the same type as the argument.

**Comment by tschottdorf** [comment]
I had wondered about this before, that makes it look like `%v` was the right thing to format any interface with, but I thought that when I checked the docs I didn't see this behaviour mentioned.

**Pull request merged**
