### PR TITLE
sql: support SMALLSERIAL and BIGSERIAL aliases

### LINKED ISSUE #7177: The bigserial "type"
I've seen that we now have the `SERIAL` pseudo-type support, which is nice. Now, how about the `BIGSERIAL` one?
The case is that I have an app using ORM which makes all IDs `BIGSERIAL` and I'd like to move it to Cockroach from Postgres, but keep it compatible.

Given that Cockroach's `SERIAL` is 64-bit anyway, perhaps simply aliasing `BIGSERIAL` to `SERIAL` would do?

As far as I can tell, that's the last thing keeping me from removing Postgres from that app :-).

[Same question can obviously be asked about `SMALLSERIAL` too, but I don't care about that one ;-D.]

### PR DESCRIPTION
**Pull request by danhhz**
Closes #7177.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7187)

### CODE REVIEW

**Comment by mjibson** [comment]
:lgtm:

<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> #### sql: support SMALLSERIAL and BIGSERIAL aliases
> 
> Closes #7177.
> 
> 
> 
</details>


---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7187#-:-KK9gLX_q5x7sokQemRY:1417088721)*

**Comment by paperstreet** [comment]
TFTR!

<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> :lgtm:
</details>


---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7187#-:-KK9ghhAqz_W2Z-K5GgT:-485616692)*

**Comment by paperstreet** [comment]
@jseldess I forgot to add the docs-todo label until just now. Adding you manually, just in case

**Comment by jseldess** [comment]
Docs updated with https://github.com/cockroachdb/docs/pull/378

**Pull request merged**
