### PR TITLE
sql: stop ignoring internal exec for sql metrics

### PR DESCRIPTION
**Pull request by rafiss**
There were if-statements that prevented the metrics from being updated. These conditionals were added in
406139eb6a33dd4fab1cbf239453601b10afdcb2. I confirmed that the test added in that commit still passes after this change, and made the test check that the correct internal metrics are updated.

Epic: None

Release note (bug fix): Fixed a bug that caused the sql.txns.open.internal and sql.statements.active.internal metrics to never get updated. These metrics are gauges that count the number of transactions and statements being executed by operations internal to CockroachDB; they do not include any operations executed by the external SQL client. This bug was present since v22.1.0.

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
Nice find! :lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119251#-:-NqiAAl9-hnx76zu2xRY:boyyrm)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rafiss and @xinhaoz)

___
*[`pkg/sql/conn_executor_test.go` line 1683 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119251#-Nqi9lOgERI822S9nayw:-Nqi9lOgERI822S9nayx:bo56nu) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd6bdfbf1cd9d1fb20c7f8eb9de3db27728055f2/pkg/sql/conn_executor_test.go#L1683)):*
> ```Go
> 
> 	// Check that the number of open transactions has incremented, but not the
> 	// internal metric.
> ```

nit: did you mean to add another `require.Equal` call here?
___
*[`pkg/sql/conn_executor_test.go` line 1695 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119251#-Nqi8ZRLD5YB7wr_uHft:-Nqi8ZRLD5YB7wr_uHfu:bxdwioo) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd6bdfbf1cd9d1fb20c7f8eb9de3db27728055f2/pkg/sql/conn_executor_test.go#L1695)):*
> ```Go
> 	// transaction).
> 	go func() {
> 		wg.Add(1)
> ```

nit: `wg.Add` should be done in the outer goroutine because `wg.Wait` might be reached by outer goroutine before inner goroutines are spawned up.
___
*[`pkg/sql/conn_executor_test.go` line 1718 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119251#-NqiA4Ba4epKiBTKPjWZ:-NqiA4Ba4epKiBTKPjW_:bg80nj8) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd6bdfbf1cd9d1fb20c7f8eb9de3db27728055f2/pkg/sql/conn_executor_test.go#L1718)):*
> ```Go
> 
> 	testutils.SucceedsWithin(t, func() error {
> 		// Check that the number of open transactions has not incremented. We only
> ```

nit: the comments here probably should be updated / removed.

**Review by rafiss — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119251#-:-NqiCMGf5lJfrC85oSVN:b-oduykh)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @xinhaoz and @yuzefovich)

___
*[`pkg/sql/conn_executor_test.go` line 1683 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119251#-Nqi9lOgERI822S9nayw:-NqiAgPc57nBuZbKKYDa:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd6bdfbf1cd9d1fb20c7f8eb9de3db27728055f2/pkg/sql/conn_executor_test.go#L1683)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: did you mean to add another `require.Equal` call here?
</blockquote></details>

done
___
*[`pkg/sql/conn_executor_test.go` line 1695 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119251#-Nqi8ZRLD5YB7wr_uHft:-NqiAh1p7RvOPoOnJS7s:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd6bdfbf1cd9d1fb20c7f8eb9de3db27728055f2/pkg/sql/conn_executor_test.go#L1695)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `wg.Add` should be done in the outer goroutine because `wg.Wait` might be reached by outer goroutine before inner goroutines are spawned up.
</blockquote></details>

done
___
*[`pkg/sql/conn_executor_test.go` line 1718 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119251#-NqiA4Ba4epKiBTKPjWZ:-NqiC6IY5gbBXwQgXWwV:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd6bdfbf1cd9d1fb20c7f8eb9de3db27728055f2/pkg/sql/conn_executor_test.go#L1718)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: the comments here probably should be updated / removed.
</blockquote></details>

done

**Comment by rafiss** [comment]
test is flaky under race

bors r-

**Pull request merged**
