### PR TITLE
logictest: bump parallelism threshold to 5 to speedup 5node

### PR DESCRIPTION
**Pull request by otan**
Release note: None

### CODE REVIEW

**Comment by otan** [comment]
had a derp with the title! but anyway...

before:
```
FAIL	github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder	157.541s
```

now:
```
FAIL	github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder	66.609s
```

----

failure:
```
test logs left over in: /var/folders/xp/752xl3d941zcshjq13h2k4900000gp/T/logTestExecBuild911267904
--- FAIL: TestExecBuild (64.43s)
    test_log_scope.go:79: test logs captured to: /var/folders/xp/752xl3d941zcshjq13h2k4900000gp/T/logTestExecBuild911267904
    test_log_scope.go:80: use -show-logs to present logs inline
    --- FAIL: TestExecBuild/5node (0.00s)
        --- FAIL: TestExecBuild/5node/explain_analyze_plans (23.84s)
            logic.go:2319:

                testdata/explain_analyze_plans:118: EXPLAIN ANALYZE (DISTSQL) SELECT DISTINCT(kw.w) FROM kv JOIN kw ON kv.k = kw.w ORDER BY kw.w
                expected:
                    planning time: 10µs
                    execution time: 100µs
                    distribution: <hidden>
                    vectorized: <hidden>
                    rows read from KV: 10 (80 B)
                    maximum memory usage: <hidden>
                    network usage: <hidden>
                    regions: <hidden>
                    ·
                    • sort
                    │ nodes: <hidden>
                    │ regions: <hidden>
                    │ actual row count: 5
                    │ estimated max memory allocated: 0 B
                    │ estimated max sql temp disk usage: 0 B
                    │ order: +w
                    │
                    └── • distinct
                        │ nodes: <hidden>
                        │ regions: <hidden>
                        │ actual row count: 5
                        │ estimated max memory allocated: 0 B
                        │ estimated max sql temp disk usage: 0 B
                        │ distinct on: w
                        │
                        └── • hash join
                            │ nodes: <hidden>
                            │ regions: <hidden>
                            │ actual row count: 5
                            │ estimated max memory allocated: 0 B
                            │ estimated max sql temp disk usage: 0 B
                            │ equality: (k) = (w)
                            │ left cols are key
                            │
                            ├── • scan
                            │     nodes: <hidden>
                            │     regions: <hidden>
                            │     actual row count: 5
                            │     KV time: 0µs
                            │     KV contention time: 0µs
                            │     KV rows read: 5
                            │     KV bytes read: 40 B
                            │     estimated max memory allocated: 0 B
                            │     missing stats
                            │     table: kv@kv_pkey
                            │     spans: FULL SCAN
                            │
                            └── • scan
                                  nodes: <hidden>
                                  regions: <hidden>
                                  actual row count: 5
                                  KV time: 0µs
                                  KV contention time: 0µs
                                  KV rows read: 5
                                  KV bytes read: 40 B
                                  estimated max memory allocated: 0 B
                                  missing stats
                                  table: kw@kw_pkey
                                  spans: FULL SCAN
                    ·
                    Diagram: https://cockroachdb.github.io/distsqlplan/decode.html#eJzsm9Fuo0YUhu_7FKO52lXxwgzYcZBWijZJ1Wy7cZVEK1WVLwhMY2QbvMw4ThrlsfoCfbIKvKyDMXMg2Yaph7vYgHPmO2fOP_wDD5h_mWEXX57-enp8hU7OLq_Ozo-v0Jvp6t3qLfrpYvQJTW_Rx9HZOZqu0OgcTW_fTdF7lB5Ho4uT0wv04ffsEzZwFAfs3Jszjt0_MMEGptjANjawgw3cx2MDL5LYZ5zHSXrKQ3bBWXCHXcvAYbRYivTrsYH9OGHYfcAiFDOGXXzlXc_YBfMClpgWNnDAhBfOsn8zvT1aJOHcS-6xgS8XXsRd1DPTfzxaChcdpWH88hmJcM5cZP3zN19_9uNIsEiEcVQ6lMQrjhLmBS76evH1vWD5V0P0ARv40-fjY8QFWyA_XkYCvWF3wgwj8dZFVhbh-gTGplUnzL07NGfzOLlH3mwW-55ggYus7NevPeFPGEfxUizSQaTnZ1HlXxA8fjTw-tOaZE7q-h5NPD4pMjpKzx8bmAvvhmGXPBrPQz_YQr8qozfJU_i0g78Nn1bC3_zOMoqTgCUsKPzSOL0SOmVHBn_2-ORjHEYsMcnW5JmxP8WbI_L2fRLeTLK_Cqljd8xfltMko5ce419mSLD5AgUhn6Il927Ys-FuwNlNqvYk5CKMfGGSfikbSoyrWdE4LygaGR1qqUlnM_J-k6xfxolgiUlLOf9RtWENaiR0VzqzsezM6XncixemvZXQikGDkfcrIz8oRE7qiweBddukPdPulLuucjeAf1BDuQvwO-UGlJu8snKTfVFuoGo3yj1QU5teotzNikaq3ERNOlXKDWQ9V-5SzhVXblq_BdMa-mf3TKfTv7r61wD-sIb-FeB3-gfoH31l_aP7on9A1W7070DNDv8S_WtWNFL9o2rSqdI_IOu5_pVyrrj-2fVbsF1D_5ye2e_0r67-NYB_WEP_CvA7_QP0z35l_bP3Rf-Aqt3o31DNDv8S_WtWNFL9s9WkU6V_QNZz_SvlXHH9c-q3YKeG_vV7nfrVVb8G6Puw-vVMgrwoQATFYsKSTgfr6qDzyjro7IsOAvW70cFDNTv9S3SwWdFIddBRk06VDgJZz3WwlHPFdRDYmL1gfBFHnG13g52_bKUJZ8ENW1cHj5eJz35LYj_7N-uPo-y6zFYOGBfro3T94SzKD3HhCdk26H9JzsJZt6sf_WFl9BETqziZopknWOTffws__37lhaI4sIBxloTeLPzLK486v-yrUPksvM2G_eRQrljfjmVjzo_OGU9RbF_8_ZGQfstMiITJ8LswIU2ZUNLVSYnJgY5MSINmSJVrhvLoDyuj1zahW83w9Zm00gyBIiddnQDNUBMmdJuJ9ZSJXUBibV9sS4E6Ki0rd0wRefREy_UCwETL9YKcCbU7JiUmWt6TOdJW2pe30r704kGR5_bFA3kTL3YyS7kl7cEz3Yk9riU5kurp9X9IaOvuhIIZ1dOdAJi0vdpo5cZt-Ex3Yo_LRI6k2vJQoxnKo2_dnVAwo3q6EwCTtt2JVprhoXRhSyz5mprI3e9qf2KPqwxgInE91DBtoPjbXjOomFQ9LQoIipYeBSl54MWOSoGOKreLBzou2AnghWlZZnImek49wFuvdkXUuI-B6rxtB0PJya_ncqTkhHceBsBEz-c25Ewk1ogiHRGo87ZtjHY6IgClbR-jnUqXb--RAbDsLm3wdUYGwETPxzcgKNXLEUXcHXn8mhoZABQ976ZKe4fFjjoEOmrJbe-MDFJy2zsjA2DS9tRTsU70fLwDmjxK7as8I34tjQza5L05TW5lACZtGxmtdESAiZ7PeECTp9odUaMjQvFraWRQ-f4hBfYPaWn_sDMyACZ6GhkQFD2XI3IoEndEDXcHir_tu6l2klraQSx2VAfoqPK3TrQ0MmjJbVfKyFCRiZ5TT85ETyMDmjx6LkcAKErtq-yKH9hC0PKmXc6kbSOjnToH9g_1NDKAydP2Yx5KQql2RxTpiPL9QwrsH1L52zp6GhnAm256rhwAKHoaGcC7blo-5gFBUeql_13rKfnLejbwsp5dsts1NDLGjz_8GwAA__8EUOFJ

                but found (query options: "") :
                    planning time: 10µs
                    execution time: 100µs
                    distribution: <hidden>
                    vectorized: <hidden>
                    rows read from KV: 10 (80 B)
                    maximum memory usage: <hidden>
                    network usage: <hidden>
                    regions: <hidden>
                    ·
                    • sort
                    │ nodes: <hidden>
                    │ regions: <hidden>
                    │ actual row count: 5
                    │ estimated max memory allocated: 0 B
                    │ estimated max sql temp disk usage: 0 B
                    │ order: +w
                    │
                    └── • distinct
                        │ nodes: <hidden>
                        │ regions: <hidden>
                        │ actual row count: 5
                        │ estimated max memory allocated: 0 B
                        │ estimated max sql temp disk usage: 0 B
                        │ distinct on: w
                        │
                        └── • hash join
                            │ nodes: <hidden>
                            │ regions: <hidden>
                            │ actual row count: 5
                            │ estimated max memory allocated: 0 B
                            │ estimated max sql temp disk usage: 0 B
                            │ equality: (k) = (w)
                            │ left cols are key
                            │
                            ├── • scan
                            │     nodes: <hidden>
                            │     regions: <hidden>
                            │     actual row count: 5
                            │     KV time: 0µs
                            │     KV contention time: 0µs
                            │     KV rows read: 5
                            │     KV bytes read: 40 B
                            │     estimated max memory allocated: 0 B
                            │     missing stats
                            │     table: kv@kv_pkey
                            │     spans: FULL SCAN
                            │
                            └── • scan
                                  nodes: <hidden>
                                  regions: <hidden>
                                  actual row count: 5
                                  KV time: 0µs
                                  KV contention time: 0µs
                                  KV rows read: 5
                                  KV bytes read: 40 B
                                  estimated max memory allocated: 0 B
                                  missing stats
                                  table: kw@kw_pkey
                                  spans: FULL SCAN
                    ·
                    Diagram: https://cockroachdb.github.io/distsqlplan/decode.html#eJzsWN1u4zYTvf-eguBVgk9Zi_JvBCwQbJKi3nbtwgkWKApfMNI0FiyLXpKO4wZ5rL5An6yQtKpXlkVKSXZNRLmzRFKeOXPIc4YPWHwJsYuvLn-9PL9GF8Or6-Ho_Bodzdfv1sfop8n4E5rfoY_j4QjN12g8QvO7d3P0HsXjaDy5uJygD78nT9jCEfNhRBcgsPsHJtjCDrZwG08tvOTMAyEYj4cekolD_x67toWDaLmS8euphT3GAbsPWAYyBOzia3oTwgSoD7xlYwv7IGkQJp-f350tebCgfIMtfLWkkXDRSctBNPIRQUzOgGMLj1fSRWdxKL98RjJYgIvsf_4W6bPHIgmRDFhUGOJsLRAH6ruonb652UjIXjkd9AFb-NPn83MkJCyRx1aRREdwL1tBJI9dZCfhphMA5mUTFvQeLWDB-AbRMGQeleC7yE6-fkOlNwOB2Eou4yzi-UlY2Ys2nj5aOH1KYc1gu9mgGRWzPGBnBE8fpxYWkt4Cdsmj9bQ6tHfqsK5eB-etDoU6OKV12H5nFTHuAwc_96VpvFI3ZU8xf6Zi9pEFEfBWLx9aCH_KozNy_J4Ht7PkV650cA_eqlgmFXjxmPgSIgmLJfIDMUcrQW-hMrbODrZb3Np1-HsRCBlEnmydFmphRFr1KNN5BmVU4BDHTHS2mXfrFP2KcQm8Rbq7Wf3ftLR6FQq6r5xJLntrOmInbNkig_z0kqS1kXdLI-_nIifVVYTo1bzlnCRi8wIaToraMTBBOsgLSngN8Dt6Cc-D_yzhfp3gO6Xg_wDd7puu27vYlum2hrRbabLNkKbncabzDM4o0WmbiU6ZcGuqngl3zxDhLk8rL9xO9RPYqSB_7ZPkoH6Tv0ryVwP8bgX5y4H_Jn8a-XN-rPwNTJe_qm2rhrTbA56YccC_ZN9ajzNKdDpmolMmf5qqZ_LXN0T-ntK37klrAmLJIgG7h8HeL9txwcG_hZQdgq24B79x5iV_kz6Ok3WJm_BByHTUSR-GUTYkJJWq5ve7G4c60Z-WRh-BXDM-RyGVEHmb_8LP3q9pIPOJ-SCABzQM_qLFrLNlX3XKg-AOvmpVNpQJVjaWilY2ugARQ_HtBPu7QEK6TcSE1CC5YxzJ1dGflkbf2ILukLwhmDi7mNjfYtLOQWLvLm4rAe2YJANOMXV19IQc-MyzFXSwX4QOdm1M-k3EpKPcIl31FukqF_fyeO4u7ikXk_whbhsnQf0nusRXzCU1JOXW8wAFrR19M13i4Iku8RWTXA1JufU0g-Tq6JvpEk_VQmSrNZCou8tyn_iK94gGE4X7NEPbdfE30imSQoeZ3yeOZp-om7FeE-WVqDuSQ5tIEzE59AXmYbaepnMt96ZmuA5S6DKN8pGH4bkak0PfYR6G52pMFPbUEJ6rL0RITyORhSuRNyupwaSZF5k6UMr9qRmX06Rw15LfJwPNPil0sUZZSUdBCdLTcYJUxXT6-L9_AwAA__8-C--V
            logic.go:3201:
                testdata/explain_analyze_plans:183: error while processing
            logic.go:3201: testdata/explain_analyze_plans:183: too many errors encountered, skipping the rest of the input
        --- FAIL: TestExecBuild/5node/dist_vectorize (7.93s)
            logic.go:2319:

                testdata/dist_vectorize:133: EXPLAIN (VEC, VERBOSE) SELECT count(*) FROM kv
                expected:
                    │
                    ├ Node 1
                    │ └ *colflow.BatchFlowCoordinator
                    │   └ *colexec.invariantsChecker
                    │     └ *colexec.orderedAggregator
                    │       └ *colexecbase.distinctChainOps
                    │         └ *colexec.invariantsChecker
                    │           └ *colexec.ParallelUnorderedSynchronizer
                    │             ├ *colexec.invariantsChecker
                    │             │ └ *colexec.countOp
                    │             │   └ *colexec.invariantsChecker
                    │             │     └ *colexecutils.CancelChecker
                    │             │       └ *colexec.invariantsChecker
                    │             │         └ *colfetcher.ColBatchScan
                    │             ├ *colexec.invariantsChecker
                    │             │ └ *colrpc.Inbox
                    │             ├ *colexec.invariantsChecker
                    │             │ └ *colrpc.Inbox
                    │             ├ *colexec.invariantsChecker
                    │             │ └ *colrpc.Inbox
                    │             └ *colexec.invariantsChecker
                    │               └ *colrpc.Inbox
                    ├ Node 2
                    │ └ *colrpc.Outbox
                    │   └ *colexecutils.deselectorOp
                    │     └ *colexec.invariantsChecker
                    │       └ *colexec.countOp
                    │         └ *colexec.invariantsChecker
                    │           └ *colexecutils.CancelChecker
                    │             └ *colexec.invariantsChecker
                    │               └ *colfetcher.ColBatchScan
                    ├ Node 3
                    │ └ *colrpc.Outbox
                    │   └ *colexecutils.deselectorOp
                    │     └ *colexec.invariantsChecker
                    │       └ *colexec.countOp
                    │         └ *colexec.invariantsChecker
                    │           └ *colexecutils.CancelChecker
  1 logictest: bump parallelism threshold to 5 to speedup 5node
                    │             └ *colexec.invariantsChecker
                    │               └ *colfetcher.ColBatchScan
                    ├ Node 4
                    │ └ *colrpc.Outbox
                    │   └ *colexecutils.deselectorOp
                    │     └ *colexec.invariantsChecker
                    │       └ *colexec.countOp
                    │         └ *colexec.invariantsChecker
                    │           └ *colexecutils.CancelChecker
                    │             └ *colexec.invariantsChecker
                    │               └ *colfetcher.ColBatchScan
                    └ Node 5
                      └ *colrpc.Outbox
                        └ *colexecutils.deselectorOp
                          └ *colexec.invariantsChecker
                            └ *colexec.countOp
                              └ *colexec.invariantsChecker
                                └ *colexecutils.CancelChecker
                                  └ *colexec.invariantsChecker
                                    └ *colfetcher.ColBatchScan

                but found (query options: "") :
                    │
                    ├ Node 1
                    │ └ *colflow.BatchFlowCoordinator
                    │   └ *colexec.orderedAggregator
                    │     └ *colexecbase.distinctChainOps
                    │       └ *colexec.ParallelUnorderedSynchronizer
                    │         ├ *colexec.countOp
                    │         │ └ *colexecutils.CancelChecker
                    │         │   └ *colfetcher.ColBatchScan
                    │         ├ *colrpc.Inbox
                    │         ├ *colrpc.Inbox
                    │         ├ *colrpc.Inbox
                    │         └ *colrpc.Inbox
                    ├ Node 2
                    │ └ *colrpc.Outbox
                    │   └ *colexecutils.deselectorOp
                    │     └ *colexec.countOp
                    │       └ *colexecutils.CancelChecker
                    │         └ *colfetcher.ColBatchScan
                    ├ Node 3
                    │ └ *colrpc.Outbox
                    │   └ *colexecutils.deselectorOp
                    │     └ *colexec.countOp
                    │       └ *colexecutils.CancelChecker
                    │         └ *colfetcher.ColBatchScan
                    ├ Node 4
                    │ └ *colrpc.Outbox
                    │   └ *colexecutils.deselectorOp
                    │     └ *colexec.countOp
                    │       └ *colexecutils.CancelChecker
                    │         └ *colfetcher.ColBatchScan
                    └ Node 5
                      └ *colrpc.Outbox
                        └ *colexecutils.deselectorOp
                          └ *colexec.countOp
                            └ *colexecutils.CancelChecker
                              └ *colfetcher.ColBatchScan
            logic.go:3201:
                testdata/dist_vectorize:195: error while processing
            logic.go:3201: testdata/dist_vectorize:195: too many errors encountered, skipping the rest of the input
    logic.go:3433: -- test log scope end --
FAIL
```

**Comment by RaduBerinde** [comment]
Thanks! These aren't failing on the current master, at least with `make`. Note that #69342 removed a `skip.UnderBazelWithIssue`, is that the problem?

**Comment by otan** [comment]
vectorize always fails for me locally on OSX. maybe @yuzefovich can enlighten us (as he has in the past)

i think it's fine if CI is fine

**Review by RaduBerinde — APPROVED** [review]

**Comment by otan** [comment]
bors r=RaduBerinde

**Comment by yuzefovich** [comment]
> vectorize always fails for me locally in strange and exciting ways on OSX. maybe @yuzefovich can enlighten us (as he has in the past)

Can you say more? `vectorize` logic test is failing? Using bazel?

**Comment by otan** [comment]
a simple `go test ./pkg/sql/opt/exec/execbuilder` yields the above output

**Comment by yuzefovich** [comment]
I see. It's because `crdb_test` tag is not specified - the vectorized planning code adds some assertion-helpers when that tag is used (which is the case for all `make test` commands).

**Pull request merged**
