### PR TITLE
dbconsole,admission: work queue duration graph should use rate

### LINKED ISSUE #114503: admission: `Admission Delay Rate` graph shows no values
**Describe the problem**

On DB console, the `Admission Delay Rate` graph shows no values. It is likely because we are referencing a metric that may have changed.

**Additional data / screenshots**

image

Jira issue: CRDB-33534

### PR DESCRIPTION
**Pull request by aadityasondhi**
Fixes #114503.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116093)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 364 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116093#-NlTQ0eW970wHoM8IzYw:-NlTQ0eW970wHoM8IzYx:b-v4cmkq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6306d459b912907bd3349cf69a2bc8f773ce2118/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L364)):*
> ```XML
>               title={"KV " + nodeDisplayName(nodeDisplayNameByID, nid)}
>               sources={[nid]}
>               nonNegativeRate
> ```

I don't think this is right. The percentile graphs work fine on the db console.
And see some of the other examples which also don't take the rate: 
https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/changefeeds.tsx#L66

https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/distributed.tsx#L117

https://github.com/cockroachdb/cockroach/blob/96374f0c0c4758c93403631ce49c1c7bc93ef42e/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx#L247

**Review by aadityasondhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116093)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 364 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116093#-NlTQ0eW970wHoM8IzYw:-NlTqLai9bOD2pJs-ApI:b-tigewe) ([raw file](https://github.com/cockroachdb/cockroach/blob/6306d459b912907bd3349cf69a2bc8f773ce2118/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L364)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't think this is right. The percentile graphs work fine on the db console.
And see some of the other examples which also don't take the rate: 
https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/changefeeds.tsx#L66

https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/distributed.tsx#L117

https://github.com/cockroachdb/cockroach/blob/96374f0c0c4758c93403631ce49c1c7bc93ef42e/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx#L247
</blockquote></details>

Not familiar with how those metrics are tracking stuff, but if we don't use rate for this metric, we get:


I will take a further look. Now that you mention it, it makes sense that the percentile should not use rate.

**Review by aadityasondhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116093)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 364 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116093#-NlTQ0eW970wHoM8IzYw:-NlTrzeqA0uMtjDb50cJ:b465k63) ([raw file](https://github.com/cockroachdb/cockroach/blob/6306d459b912907bd3349cf69a2bc8f773ce2118/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L364)):*
<details><summary><i>Previously, aadityasondhi (Aaditya Sondhi) wrote…</i></summary><blockquote>

Not familiar with how those metrics are tracking stuff, but if we don't use rate for this metric, we get:


I will take a further look. Now that you mention it, it makes sense that the percentile should not use rate.
</blockquote></details>

Additionally the flow token graph also looks suspicious.

**Comment by aadityasondhi** [comment]
https://github.com/cockroachdb/cockroach/issues/114503#issuecomment-1852663893

**Pull request closed without merging**
