### PR TITLE
all: require go 1.9

### PR DESCRIPTION
**Pull request by RaduBerinde**
We will start using go 1.9 features (like `math/bits` or `testing.T.Helper()`)
soon.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
How should I test the Dockerfile changes? :dog:

**Comment by tschottdorf** [comment]
I'm curious. Once we use these features, cherry-picking might become annoying. Also in general, it'll make switching the branches annoying -- can we just hold off on this until 1.1.1 is out or is there any pressing reason?

**Comment by RaduBerinde** [comment]
Cherry-picking is only a problem if we use any of these features in code that's intended to go into 1.1 as well. Switching branches should not be annoying at all, go 1.9 should work for both.

That said, I can of course hold off.

**Comment by RaduBerinde** [comment]
It looks like TeamCity needs to upgrade the go version before this goes in @jordanlewis

**Comment by RaduBerinde** [comment]
Any tips on how can I build and upload an updated docker image?

**Comment by petermattis** [comment]
I'm fine with merging this, but I'd hold off on using new feature of go1.9 significantly for a little bit. In particular, let's not do a massive code change to use `testing.T.Helper()` until mid-way in the 1.2 cycle. I suppose this falls in the general guidelines to not do massive refactorings early in a cycle.

**Comment by RaduBerinde** [comment]
Agreed, I wasn't planning on refactoring existing code any time soon.

**Comment by jordanlewis** [comment]
@RaduBerinde I think `build/builder.sh init; build/builder.sh push` does it. That will build the new image and send it to Docker Hub. You may need to get an account there first.

Then, you'll need to update the `version` variable in `build/builder.sh` to get TeamCity to pick up the new image. I think that's all there is to do, but I could be forgetting something.

**Comment by jordanlewis** [comment]
Hmm actually you might need to update the version number before you init && push. I'm not sure.

**Comment by benesch** [comment]
Nope, the version number is assigned by `push` (and printed to stdout after the image is successfully uploaded to Docker Hub). Beware: it'll take a few hours to rebuild the builder if you don't have any of the intermediate state cached from a prior rebuild.

**Comment by RaduBerinde** [comment]
Thanks @jordanlewis and @benesch, I think I got it.

**Comment by RaduBerinde** [comment]
@tschottdorf - let me know if you're ok with merging this now or if I should hold off for a couple weeks.

**Comment by tschottdorf** [comment]
Let's do it!
-- 

-- Tobias

**Review by benesch — APPROVED** [review]
Awesome, thanks for doing this @RaduBerinde!

**Pull request merged**
