### PR TITLE
sql: use a fixed name for the rowid generator function

### LINKED ISSUE #3966: sql: rowid's default function should not be experimental
It should have a name that won't change, even if the implementation does.

### PR DESCRIPTION
**Pull request by madelynnblue**
Fixes #3966

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3990)

### CODE REVIEW

**Comment by bdarnell** [comment]
Since this essentially blesses the existing function should we just remove the "experimental" prefix? It's weird to keep the function available under two different names.

**Comment by mjibson** [comment]
A reason to keep it around under two names is the implementations may change in the future. We may find the rowid function needs some tweaking, or that the unique_int func needs some tweaking, but we don't want to change the other one. That it is no more than an alias to another function is fine with me. But I don't care too much either way and would be happy to just rename the other one.

**Comment by petermattis** [comment]
LGTM

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/parser/builtins.go, line 499 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3990#-K93hzIzku1-ITyKCgjJ:-K93hzJ-WIX05ZJkr-jo:-585337993) ([raw file](https://github.com/cockroachdb/cockroach/blob/1889496f1e003be874b41464c58862996fe37832/sql/parser/builtins.go#L499)):*
I recall talk about reversing the bits in the unique id so that the generated values are not sorted (err, k-sorted). There might even be an issue about this. Would be good to add a TODO.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3990#-:-K93iFV3gl6CuNJqYWEz:676834233)*

**Comment by bdarnell** [comment]
If `unique_rowid` needs tweaking, why wouldn't we also apply those tweaks to `experimental_unique_int`? We're already making very weak guarantees about what exactly that function provides. People will use `unique_rowid` for things other than the rowid column (unless we take special steps to prevent this), so once we have a non-experimental ID-generating function it doesn't seem like there's much reason to have the experimental version too.

**Comment by mjibson** [comment]
Updated: did Ben's suggestion and just renamed the function. Also added the bit reversing TODO.

**Comment by bdarnell** [comment]
LGTM

**Comment by petermattis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/parser/builtins.go, line 1386 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3990#-K93tJsrYPtoRXB1zGje:-K93tJsrYPtoRXB1zGjf:-1753202259) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bf7b2ff06585fc05582b8e26f4757c7863cd7ce/sql/parser/builtins.go#L1386)):*
Reversing the bits should be reserved for a different function. Or perhaps the k-sorted version should be given a different name. We definitely want to keep a version of unique int generation that maintains the k-sorted property.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3990)*

**Comment by petermattis** [comment]
LGTM

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3990#-:-K93tjpbxrZn6jCrSbSt:676834233)*

**Comment by mjibson** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/parser/builtins.go, line 499 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3990#-K93hzIzku1-ITyKCgjJ:-K93u0BNYf0ezyuCrrLT:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1889496f1e003be874b41464c58862996fe37832/sql/parser/builtins.go#L499)):*
Done.

---

*[sql/parser/builtins.go, line 1386 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3990#-K93tJsrYPtoRXB1zGje:-K93u0STOMJmSxPiSFSE:387362365) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bf7b2ff06585fc05582b8e26f4757c7863cd7ce/sql/parser/builtins.go#L1386)):*
This is a reason why I think it may be good to keep both functions around. One is for rowids, one is for ints. Although they are the same now, they may differ later. Thoughts @bdarnell?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3990)*

**Comment by bdarnell** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/parser/builtins.go, line 1386 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3990#-K93tJsrYPtoRXB1zGje:-K93vRts2u_-WHADXAeE:-1626747905) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bf7b2ff06585fc05582b8e26f4757c7863cd7ce/sql/parser/builtins.go#L1386)):*
If there's a reason to make them different then that's fine; just make sure that there are comments explaining what properties each is supposed to have.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3990)*

**Comment by petermattis** [comment]
LGTM

**Comment by RaduBerinde** [comment]
LGTM

---

Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3990#-:-K99N35apqrXmUsMOc32:676834233)*

**Comment by mjibson** [comment]
My current thought is to wait on this and wait until there's a bit-reversal implementation. This would allow the `unique_rowid` function and `experimental_unique_int` to coexist with separate properties: unique_rowid will spread writes around ranges and experimental_unique_int will have some increasing-ness to it

**Comment by mjibson** [comment]
Could I get another review of this? Rebasing up to master added some additional changes.

**Comment by bdarnell** [comment]
LGTM

**Pull request merged**
