### PR TITLE
sql: Add pg_catalog.pg_settings

### LINKED ISSUE #10078: sql: Implement pg_catalog.pg_settings as a virtual table
See https://www.postgresql.org/docs/9.6/static/view-pg-settings.html.

Hibernate expects a few settings to be available by default, so we will probably need to mock these out.

### PR DESCRIPTION
**Pull request by a6802739**
Fixes #10078, @nvanbenschoten, please help me see if I done it right.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10293)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Thanks @songhao, just a few comments. Also, this is going to require a rebase.

---

Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/pg_catalog.go, line 594 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293#-KVOAXUKCwXlnTdyB9kp:-KVOAXUKCwXlnTdyB9kq:bh1tbay) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada05d0df8ec4588255a3878c0add1b7ac43a89f/pkg/sql/pg_catalog.go#L594)):*
> ```Go
> }
> 
> // See : https://www.postgresql.org/docs/9.6/static/view-pg-settings.html
> ```

`s/See :/See:` to be consistent.

And proper punctuation at the end of the line.

---

*[pkg/sql/pg_catalog.go, line 600 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293#-KVOAhiyd9SGjBHjlzr4:-KVOAhiyd9SGjBHjlzr5:b-3rvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada05d0df8ec4588255a3878c0add1b7ac43a89f/pkg/sql/pg_catalog.go#L600)):*
> ```Go
>     name STRING,
>     setting STRING,
>     unit   STRING,
> ```

nit: extra space.

---

*[pkg/sql/pg_catalog.go, line 623 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293#-KVOBIitwWmKv4nKtj7N:-KVOBIitwWmKv4nKtj7O:b5uqyd7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada05d0df8ec4588255a3878c0add1b7ac43a89f/pkg/sql/pg_catalog.go#L623)):*
> ```Go
> 			if err := addRow(
> 				parser.NewDString(vName),    // name
> 				parser.NewDString(value),    // setting
> ```

Let's pull `parser.NewDString(value)` into a variable `valueDatum` so that we can avoid multiple calls to `NewDString`.

---

*[pkg/sql/pg_catalog.go, line 628 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293#-KVOAtrwcKYuPCrxZPSE:-KVOAtrwcKYuPCrxZPSF:b-itmwvn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada05d0df8ec4588255a3878c0add1b7ac43a89f/pkg/sql/pg_catalog.go#L628)):*
> ```Go
> 				parser.DNull,                // short_desc
> 				parser.DNull,                // extra_desc
> 				parser.NewDString("user"),   // context
> ```

Let's put these two into variables, like `conTypeCheck`?

---

*[pkg/sql/testdata/pg_catalog, line 140 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293#-KVOB0jQSNUkVQZfngUi:-KVOB0jQSNUkVQZfngUj:bd6651r) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada05d0df8ec4588255a3878c0add1b7ac43a89f/pkg/sql/testdata/pg_catalog#L140)):*
> ```
> 
> query TTTTTTTTTTTTTTTTB colnames
> SELECT * FROM pg_catalog.pg_settings
> ```

Can we split this up into a few queries so it's a little more readable?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293#-:-KVOASnQ_Hh9LLive_bF:b-vktcbq)*

**Comment by a6802739** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/pg_catalog.go, line 623 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293#-KVOBIitwWmKv4nKtj7N:-KVPB0f1M97iYxq8eRN-:b-oxllal) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada05d0df8ec4588255a3878c0add1b7ac43a89f/pkg/sql/pg_catalog.go#L623)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Let's pull `parser.NewDString(value)` into a variable `valueDatum` so that we can avoid multiple calls to `NewDString`.
</details>
sorry, I don't quite understand what do you mean here?

---

*[pkg/sql/pg_catalog.go, line 628 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293#-KVOAtrwcKYuPCrxZPSE:-KVPB8C0dGCJjpf3HQPp:b-7bbcpm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada05d0df8ec4588255a3878c0add1b7ac43a89f/pkg/sql/pg_catalog.go#L628)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Let's put these two into variables, like `conTypeCheck`?
</details>
do you mean two costants here?

---

*[pkg/sql/testdata/pg_catalog, line 140 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293#-KVOB0jQSNUkVQZfngUi:-KVPBOQkFxQj26D8jDaL:bjafc7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada05d0df8ec4588255a3878c0add1b7ac43a89f/pkg/sql/testdata/pg_catalog#L140)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Can we split this up into a few queries so it's a little more readable?
</details>
do you mean a few query with different columns?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/pg_catalog.go, line 623 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293#-KVOBIitwWmKv4nKtj7N:-KVRJcQcQHAIdXqTtVhY:b-9r9ouz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada05d0df8ec4588255a3878c0add1b7ac43a89f/pkg/sql/pg_catalog.go#L623)):*
<details><summary><i>Previously, a6802739 (songhao) wrote…</i></summary>
> sorry, I don't quite understand what do you mean here?
</details>
Add `valueDatum := parser.NewDString(value)` above, and use throughout.

---

*[pkg/sql/pg_catalog.go, line 628 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293#-KVOAtrwcKYuPCrxZPSE:-KVRJs2-UJxWfHBoUTD8:b-q4bxtc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada05d0df8ec4588255a3878c0add1b7ac43a89f/pkg/sql/pg_catalog.go#L628)):*
<details><summary><i>Previously, a6802739 (songhao) wrote…</i></summary>
> do you mean two costants here?
</details>
Add

```
var (
    settingsCtxUser = parser.NewDString("user")
    varTypeString = parser.NewDString("string")
)
```

above, and use the variables here

---

*[pkg/sql/testdata/pg_catalog, line 140 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293#-KVOB0jQSNUkVQZfngUi:-KVRKPeJ7wqb1RMZZpYV:b6gp4nn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada05d0df8ec4588255a3878c0add1b7ac43a89f/pkg/sql/testdata/pg_catalog#L140)):*
<details><summary><i>Previously, a6802739 (songhao) wrote…</i></summary>
> do you mean a few query with different columns?
</details>
Yeah, like we have below. Also, could you move this all down to the end of the file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293)*

**Comment by a6802739** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/sql/pg_catalog.go, line 594 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293#-KVOAXUKCwXlnTdyB9kp:-KVTatnPPhzKOKO88eI4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada05d0df8ec4588255a3878c0add1b7ac43a89f/pkg/sql/pg_catalog.go#L594)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> `s/See :/See:` to be consistent.
> 
> And proper punctuation at the end of the line.
</details>
Done.

---

*[pkg/sql/pg_catalog.go, line 600 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293#-KVOAhiyd9SGjBHjlzr4:-KVTav-RtX1q7RfzAoPo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada05d0df8ec4588255a3878c0add1b7ac43a89f/pkg/sql/pg_catalog.go#L600)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> nit: extra space.
</details>
Done.

---

*[pkg/sql/pg_catalog.go, line 623 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293#-KVOBIitwWmKv4nKtj7N:-KVTawUEtQMdVmh6G2sx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada05d0df8ec4588255a3878c0add1b7ac43a89f/pkg/sql/pg_catalog.go#L623)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Add `valueDatum := parser.NewDString(value)` above, and use throughout.
</details>
Done.

---

*[pkg/sql/pg_catalog.go, line 628 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293#-KVOAtrwcKYuPCrxZPSE:-KVTay3z2fi5vcIZzHL5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada05d0df8ec4588255a3878c0add1b7ac43a89f/pkg/sql/pg_catalog.go#L628)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Add
> 
> ```
> var (
>     settingsCtxUser = parser.NewDString("user")
>     varTypeString = parser.NewDString("string")
> )
> ```
> 
> above, and use the variables here
</details>
Done.

---

*[pkg/sql/pg_catalog.go, line 994 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293#-KVTb-JIr8Rdob8j6YXy:-KVTb-JIr8Rdob8j6YXz:b-hrdv49) ([raw file](https://github.com/cockroachdb/cockroach/blob/d57de662bff1d0ed91a30968a84fbf10be231b1b/pkg/sql/pg_catalog.go#L994)):*
> ```Go
> )
> 
> // See: https://www.postgresql.org/docs/9.6/static/catalog-pg-database.html
> ```

it seems miss `:` here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/pg_catalog.go, line 994 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293#-KVTb-JIr8Rdob8j6YXy:-KVYAjMTMtn1jBg8rMvr:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d57de662bff1d0ed91a30968a84fbf10be231b1b/pkg/sql/pg_catalog.go#L994)):*
<details><summary><i>Previously, a6802739 (songhao) wrote…</i></summary>
> it seems miss `:` here.
</details>
Thanks!

---

*[pkg/sql/pg_catalog.go, line 762 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293#-KVYAaGPon72rq-fnNwR:-KVYAaGPon72rq-fnNwS:b-z7qy6s) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b2f65321d915ca43e14db1e3e03d25563db230a/pkg/sql/pg_catalog.go#L762)):*
> ```Go
> 	varTypeString = parser.NewDString("string")
> 
> 	// Avoid unused warning for constants.
> ```

We're using these variables, so neither of `_ = ...` statements are necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293)*

**Comment by a6802739** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/sql/pg_catalog.go, line 762 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293#-KVYAaGPon72rq-fnNwR:-KVYtZVfpYU7mMHchioH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b2f65321d915ca43e14db1e3e03d25563db230a/pkg/sql/pg_catalog.go#L762)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> We're using these variables, so neither of `_ = ...` statements are necessary.
</details>
Done.

---

*[pkg/sql/testdata/pg_catalog, line 140 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293#-KVOB0jQSNUkVQZfngUi:-KVYtWlWftV6oo4NPAmA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada05d0df8ec4588255a3878c0add1b7ac43a89f/pkg/sql/testdata/pg_catalog#L140)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Yeah, like we have below. Also, could you move this all down to the end of the file?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/testdata/pg_catalog, line 701 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293#-KV_jHNc0qq-a7Qc46rB:-KV_jHNc0qq-a7Qc46rC:boxiew7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0dde9665d477d61d7e9c7babb2782c86fc6a5826/pkg/sql/testdata/pg_catalog#L701)):*
> ```
> 
> query TTTTTT colnames
> SELECT name, setting, category, short_desc, extra_desc, vartype FROM pg_catalog.pg_settings where vartype = 'string'
> ```

Why do we have the WHERE clauses on each of these queries? They seem unnecessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293)*

**Comment by a6802739** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/sql/testdata/pg_catalog, line 701 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293#-KV_jHNc0qq-a7Qc46rB:-KVcdW3Y0-eUy43Zvum9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0dde9665d477d61d7e9c7babb2782c86fc6a5826/pkg/sql/testdata/pg_catalog#L701)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Why do we have the WHERE clauses on each of these queries? They seem unnecessary.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10293)*

**Comment by cuongdo** [comment]
Thanks for your work on this PR, @a6802739!

**Pull request merged**
