### PR TITLE
sql: make NULL ordering more thoroughly consistent

### LINKED ISSUE #12022: sql: tuples with NULLs don't compare sanely
Found by @eisenstatdavid in https://github.com/cockroachdb/cockroach/pull/10475#issuecomment-264911948

> The logic for not defining the previous element of (e.g.) -inf to be null is that, in a filter expression like col < -inf, the null values of col don't satisfy the filter (because null < -inf is null (unknown, technically, but we conflate unknown and boolean null) when we're using the user-accessible builtin and not .Compare), and thus should be excluded.
>
> For arrays, I think Next(a) = a + [null] is good enough for the limited purpose of scanning an index. If we unthinkingly rewrite y > [1] to y >= [1, null], then despite the fact that [1, 2] > [1] is true, [1, 2] > [1, null] should be unknown (guessing this is what PostgreSQL does from its handling of tuples; IIRC, we don't do this because the array builtin calls .Compare, but we should).
>
> For tuples also, we don't have a good answer. (2, null) sorts in between (1, max) and (2, min), so we should include (2, null) when there's a > (1, max) filter. This means that defining Next((1, max)) = (2, min) is bad, because then it's not safe to rewrite, e.g., y > (1, max) to y >= (2, min), because the semantics for (2, null) changes, from true to either false (.Compare) or null (as the builtin should return, but doesn't yet). Defining Next((1, max)) = (2, null) has the problem described above.

Jira issue: CRDB-6132

### PR DESCRIPTION
**Pull request by knz**
Fixes #12022.

- 1st commit is API change + small improvement to EncDatum comparison
- last commit is bug fix + extra tests

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
The proposed APIs look good to me.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27885#-:-LIGmSFR67XhN-CdPEEC:bnku0ok)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/tree/compare.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27885#-LIGl0JPD5LTTLS2Q4oh:-LIGl0JPD5LTTLS2Q4oi:b-1kuirm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f26a3173c23b8ae79fdedcd0f1312ab2572ac930/pkg/sql/sem/tree/compare.go#L33)):*
> ```Go
> //   themselves produce a NULL result.
> //
> //   Function: scalarCompare()
> ```

[nit] Feels odd that this is not exported (even if there are no direct users right now). I'd hate for some future code to have to construct a `ComparisonExpr` just to do a comparison.
___
*[pkg/sql/sem/tree/compare.go, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27885#-LIGlQJ88M0WK2BrTEBp:-LIGlQJ88M0WK2BrTEBq:b-cmah62) ([raw file](https://github.com/cockroachdb/cockroach/blob/f26a3173c23b8ae79fdedcd0f1312ab2572ac930/pkg/sql/sem/tree/compare.go#L126)):*
> ```Go
> 
> // doCompare is the main function.
> func doCompare(ctx *EvalContext, orderedNULLs bool, a, b Datum) int {
> ```

[nit] It would be cleaner for the callers if these were two separate functions. The "sql" variant could return `cmp int, ok bool` with the bool indicating if the result is known (not-NULL), instead of the `-2` special value.

If not, add `/* orderedNULLs */` to all callsites which pass `true` or `false`.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27885)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/tree/compare.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27885#-LIGl0JPD5LTTLS2Q4oh:-LIGnio6DHlFUvHC8SOA:bpmbu7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/f26a3173c23b8ae79fdedcd0f1312ab2572ac930/pkg/sql/sem/tree/compare.go#L33)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Feels odd that this is not exported (even if there are no direct users right now). I'd hate for some future code to have to construct a `ComparisonExpr` just to do a comparison.
</blockquote></details>

Exported.
___
*[pkg/sql/sem/tree/compare.go, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27885#-LIGlQJ88M0WK2BrTEBp:-LIGnk4UC-yjSBQw1vkl:boynwiz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f26a3173c23b8ae79fdedcd0f1312ab2572ac930/pkg/sql/sem/tree/compare.go#L126)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] It would be cleaner for the callers if these were two separate functions. The "sql" variant could return `cmp int, ok bool` with the bool indicating if the result is known (not-NULL), instead of the `-2` special value.

If not, add `/* orderedNULLs */` to all callsites which pass `true` or `false`.
</blockquote></details>

This is an intermediate step. A later patch replaces this argument entirely. Anyway I changed to add the comment in this commit so that the intermediate step becomes clearer.

**Comment by knz** [comment]
I completed the PR and it actually fixes #12022. RFAL. 

Any suggestion as to which benchmark(s) to use?

**Review by nvb — CHANGES_REQUESTED** [review]
I agree, I like these new APIs a lot! Really nice job @knz.

> Reviewed 1 of 32 files at r1, 38 of 43 files at r2, 4 of 4 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, 8 of 8 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27885#-:-LIK5U_p3YhmmcxXNVF9:b-wvs8of)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/disk_row_container_test.go, line 50 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27885#-LIK0oYy7ghhsztS8n61:-LIK0oYy7ghhsztS8n62:b-bnmq9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/0071c4b1a02134456a2c2b5509ca979ad771efb3/pkg/sql/distsqlrun/disk_row_container_test.go#L50)):*
> ```Go
> 	for _, orderInfo := range ordering {
> 		col := orderInfo.ColIdx
> 		cmp, err := l[col].Distinct(&lTypes[col], d, e, &r[orderInfo.ColIdx])
> ```

nit wherever you call `Distinct`. Consider changing the name of the variable you're assigning it to from `cmp` to something else (`dist`?.) so that it's obvious when reading that it's a bool and not the result of `TotalOrderCompare`.
___
*[pkg/sql/distsqlrun/row_container.go, line 189 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27885#-LIK1FAi3GMuUQG-V_ef:-LIK1FAi3GMuUQG-V_eg:b-7ikrsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0071c4b1a02134456a2c2b5509ca979ad771efb3/pkg/sql/distsqlrun/row_container.go#L189)):*
> ```Go
> func (mc *memRowContainer) MaybeReplaceMax(ctx context.Context, row sqlbase.EncDatumRow) error {
> 	max := mc.At(0)
> 	cmp, err := row.LessThanDatums(mc.types, &mc.datumAlloc, mc.ordering, mc.evalCtx, max)
> ```

Same kind of nit as before. The semantics of all of these comparison related methods are hard enough to keep in one's head. Let's help future readers by using different variable names for each one. For instance, here and everywhere else you call `LessThanDatums` we should swap `cmp` for `less`.
___
*[pkg/sql/sem/tree/compare.go, line 165 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/27885#-LIK4O1i6lTDyUCJjzRf:-LIK4O1i6lTDyUCJjzRg:b-8i8dzc) ([raw file](https://github.com/cockroachdb/cockroach/blob/65cb6a0cb20c6a3abd393700c429fcf3d7c7baeb/pkg/sql/sem/tree/compare.go#L165)):*
> ```Go
> 			return 1
> 		}
> 		return -2
> ```

If we're going to start returning more than the standard range of values (`-1, 0, and 1`) then we should enumerate the possible return values somewhere. This is especially true if we return these outside this file (which we do). Maybe create a new `type internalCmpRes int` enum.
___
*[pkg/sql/sem/tree/eval.go, line 4015 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27885#-LIK2PHm6PS9SLclySJV:-LIK2PHm6PS9SLclySJW:b-twqble) ([raw file](https://github.com/cockroachdb/cockroach/blob/0071c4b1a02134456a2c2b5509ca979ad771efb3/pkg/sql/sem/tree/eval.go#L4015)):*
> ```Go
> 		return RegIMatch, left, right, false, true
> 	case IsDistinctFrom:
> 		// Distinct(left, right) is implemented as !IsNotDistinctFrom(left, right)
> ```

Was this intentional?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27885)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/disk_row_container_test.go, line 50 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27885#-LIK0oYy7ghhsztS8n61:-LILeXZAA1fJI_rglCJK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0071c4b1a02134456a2c2b5509ca979ad771efb3/pkg/sql/distsqlrun/disk_row_container_test.go#L50)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit wherever you call `Distinct`. Consider changing the name of the variable you're assigning it to from `cmp` to something else (`dist`?.) so that it's obvious when reading that it's a bool and not the result of `TotalOrderCompare`.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/row_container.go, line 189 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27885#-LIK1FAi3GMuUQG-V_ef:-LILehVrE00TXYlTJwz2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0071c4b1a02134456a2c2b5509ca979ad771efb3/pkg/sql/distsqlrun/row_container.go#L189)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Same kind of nit as before. The semantics of all of these comparison related methods are hard enough to keep in one's head. Let's help future readers by using different variable names for each one. For instance, here and everywhere else you call `LessThanDatums` we should swap `cmp` for `less`.
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/compare.go, line 165 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/27885#-LIK4O1i6lTDyUCJjzRf:-LILi-0q9I_vj_q0Xcrc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/65cb6a0cb20c6a3abd393700c429fcf3d7c7baeb/pkg/sql/sem/tree/compare.go#L165)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

If we're going to start returning more than the standard range of values (`-1, 0, and 1`) then we should enumerate the possible return values somewhere. This is especially true if we return these outside this file (which we do). Maybe create a new `type internalCmpRes int` enum.
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/eval.go, line 4015 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27885#-LIK2PHm6PS9SLclySJV:-LILdPOlChjGggoNc54M:b-qxepbi) ([raw file](https://github.com/cockroachdb/cockroach/blob/0071c4b1a02134456a2c2b5509ca979ad771efb3/pkg/sql/sem/tree/eval.go#L4015)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Was this intentional?
</blockquote></details>

Oops, not, too agressive perl. Reverted.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 16 of 17 files at r8, 3 of 3 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27885#-:-LILsdo1Cp4qujMp5TWL:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsqlrun/disk_row_container_test.go, line 50 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27885#-LIK0oYy7ghhsztS8n61:-LILrhco4YT8_RRaUu-9:b-cbqb0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0071c4b1a02134456a2c2b5509ca979ad771efb3/pkg/sql/distsqlrun/disk_row_container_test.go#L50)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks, this is a lot easier to skim now.
___
*[pkg/sql/sem/tree/compare.go, line 126 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/27885#-LILsG5C3T6cs7SH0-Tq:-LILsG5C3T6cs7SH0-Tr:b-9l2qay) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a4131d0add7514615fe112af8b42fb5b9bb763/pkg/sql/sem/tree/compare.go#L126)):*
> ```Go
> 	}
> 
> 	cmp := int(res)
> ```

You could still technically do `MakeDBool(res == 0)` and all the others. internalCmpResult can be compared against constants. Your call whether to perform this cast of not.

**Review by knz — COMMENTED** [review]
So how do you want me to measure the perf impact on this?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27885#-:-LILwqTC3sz7zuyq0TZB:bp468ey)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sem/tree/compare.go, line 126 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/27885#-LILsG5C3T6cs7SH0-Tq:-LILwp3E7twAN9DrM0Lh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a4131d0add7514615fe112af8b42fb5b9bb763/pkg/sql/sem/tree/compare.go#L126)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

You could still technically do `MakeDBool(res == 0)` and all the others. internalCmpResult can be compared against constants. Your call whether to perform this cast of not.
</blockquote></details>

Done.

**Comment by nvanbenschoten** [comment]
> So how do you want me to measure the perf impact on this?

I think @jordanlewis would have a better idea than I do about the current state of our SQL expression evaluation benchmarking.

**Review by andy-kimball — COMMENTED** [review]
I would run a simple micro-benchmark comparing the performance of calling the old `Compare` method for 2 integer datums with the new static method for 2 integer datums (both run in a tight loop). If there's no difference, then you can quit there.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27885#-:-LIM0sEe6yGb0XfPuumH:b-bq04bu)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by knz** [comment]
As per the discussion in #12022 I will change the PR to be closer to pg semantics. This violates the SQL standard but enables perf gains down the line (+ more pg compatibility).

**Comment by knz** [comment]
Unfortunately this PR has gone stale, even though the issue is still current.
@asubiotto @yuzefovich I'll let you decide if you want to salvage anything from this code.

**Pull request closed without merging**
