### PR TITLE
gossip: always recompute min peers when number of nodes changes

### PR DESCRIPTION
**Pull request by spencerkimball**
Small cleanup.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12799)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/gossip/server.go, line 285 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12799#-Ka4x7mSWrHazuBUnQW4:-Ka4x7mSWrHazuBUnQW5:b-ebm3ds) ([raw file](https://github.com/cockroachdb/cockroach/blob/588136f0dadb4dd4c17e396d9d24b0c3817df5b2/pkg/gossip/server.go#L285)):*
> ```Go
> 			}
> 		} else {
> 			log.Infof(ctx, "received initial gossip connection from %s", args.Addr)
> ```

There is a log message earlier that is formatted as `gossip received from node %d`. Should this one be similar for consistency?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12799#-:-Ka4xUJBMxIVvRtN4jRw:bnfp4nl)*

**Review by a-robinson — APPROVED** [review]
LGTM

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/gossip/gossip.go, line 641 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12799#-Ka8A43rR2uBnX0k-5pB:-Ka8A43rR2uBnX0k-5pC:bzdw6h1) ([raw file](https://github.com/cockroachdb/cockroach/blob/588136f0dadb4dd4c17e396d9d24b0c3817df5b2/pkg/gossip/gossip.go#L641)):*
> ```Go
> 		log.Infof(ctx, "removing node %d which was at same address (%s) as new node %v",
> 			oldNodeID, desc.Address, desc)
> 		g.removeNodeDescriptorLocked(oldNodeID)
> ```

is it possible to test this? previously this would not recompute peer limits.

---

*[pkg/gossip/server.go, line 285 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12799#-Ka4x7mSWrHazuBUnQW4:-Ka89i1mHn_VSAeBR88H:bhgh9wy) ([raw file](https://github.com/cockroachdb/cockroach/blob/588136f0dadb4dd4c17e396d9d24b0c3817df5b2/pkg/gossip/server.go#L285)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

There is a log message earlier that is formatted as `gossip received from node %d`. Should this one be similar for consistency?
</blockquote></details>

consider making this more explicit - you're using "initial" to indicate that the remote node is still bootstrapping, but "initial" can also mean that it is the first connection between these two nodes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12799#-:-Ka8ABoHkdKFopGvn3Mx:bnfp4nl)*

**Comment by spencerkimball** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/gossip/gossip.go, line 641 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12799#-Ka8A43rR2uBnX0k-5pB:-KaCm3mhlq_uOO1op4e0:b-v8vko5) ([raw file](https://github.com/cockroachdb/cockroach/blob/588136f0dadb4dd4c17e396d9d24b0c3817df5b2/pkg/gossip/gossip.go#L641)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is it possible to test this? previously this would not recompute peer limits.
</blockquote></details>

Yes I could test this but it doesn't feel necessary, IMO. Having the number of nodes decrease by an amount which would constitute a change in max peers would be an unusual situation, and not adjusting the max peers downward has no deleterious effects. I see this as a code restructuring for clarity and to avoid future mistakes like the ones that crept in here.

---

*[pkg/gossip/server.go, line 285 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12799#-Ka4x7mSWrHazuBUnQW4:-KaCmpMzrYKkw-asCH2o:bub279e) ([raw file](https://github.com/cockroachdb/cockroach/blob/588136f0dadb4dd4c17e396d9d24b0c3817df5b2/pkg/gossip/server.go#L285)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

consider making this more explicit - you're using "initial" to indicate that the remote node is still bootstrapping, but "initial" can also mean that it is the first connection between these two nodes.
</blockquote></details>

I actually wasn't using "initial" to indicate the node is bootstrapping. We don't know the node ID for any incoming connection when the node is first starting up. What I was trying to capture here is that this is the first connection from a node which has been restarted and is connecting to the cluster to verify the cluster ID. I've changed this slightly. Maybe it's more informative now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12799)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/gossip/server.go, line 285 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12799#-Ka4x7mSWrHazuBUnQW4:-KaD5xeTv7hvJouptKPB:b2wukkn) ([raw file](https://github.com/cockroachdb/cockroach/blob/588136f0dadb4dd4c17e396d9d24b0c3817df5b2/pkg/gossip/server.go#L285)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary><blockquote>

I actually wasn't using "initial" to indicate the node is bootstrapping. We don't know the node ID for any incoming connection when the node is first starting up. What I was trying to capture here is that this is the first connection from a node which has been restarted and is connecting to the cluster to verify the cluster ID. I've changed this slightly. Maybe it's more informative now.
</blockquote></details>

Is this really the case? My understanding was that the node ID was persisted, and so restarting nodes knew their ID even before connecting to any of their peers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12799)*

**Comment by spencerkimball** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/gossip/server.go, line 285 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12799#-Ka4x7mSWrHazuBUnQW4:-KaDB_JaDiYqT77Q44aU:b5ym51t) ([raw file](https://github.com/cockroachdb/cockroach/blob/588136f0dadb4dd4c17e396d9d24b0c3817df5b2/pkg/gossip/server.go#L285)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Is this really the case? My understanding was that the node ID was persisted, and so restarting nodes knew their ID even before connecting to any of their peers.
</blockquote></details>

They do, but that information isn't yet read or available in our code path when connecting to gossip. We might consider changing it, but it's not trivial/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12799)*

**Pull request merged**
