### PR TITLE
server: rewrite of the debug range page in MVC type style

### LINKED ISSUE #13793: storage: range debug page enhancements
screen shot 2017-02-24 at 2 42 58 pm

This range has an epoch-based lease. As such, there is no expiration. The type of lease (epoch or expiration) should be noted.

Does the "Lease" row identify the leaseholder or something else? If the leaseholder, it should be renamed.

The "Key Range" row is a bit confusing. What is the `s{` prefix about?

### PR DESCRIPTION
**Pull request by BramGruneir**
When making updates to the debug range page, I was increasing finding it difficult to determine where the update should go, the template, in postProcessing or in the handler.
In response, this change moves towards a more classic MVC style.  Furthermore, as the code was getting too big for `status.go`, I moved the code and template to its own file.
These changes will allow for faster iteration and it should be a lot easier for others to add/update to the page.

The model is the handler, which performs all required RPCs to each node and gathers all data.
The controller is the postProcessing function, which performs all calculations, aggregations, error detection, etc.
The view is the template, which outputs the tables and contains the styling for this display.

Major changes include:
- All strings are now constants.
- Moved all styling and formatting logic into postProcessing.
- View:
  - Since the data are now row based instead of column based, re-wrote the styling for tables.
  - Removed almost all logic, but specifically all logic pertaining to how an individual item should be styled or titled.
  - From now on, this should remain extremely simple.
- Model:
  - This was left alone besides removing no longer needed lines.
- Controller:
  - Added the debugRangeOutput struct, which contains all information needed to display a single cell (title, value and class).
  - Added Results, which contains all debugRangeOutputs needed to display the replica table, including the headers.
  - Added styling for dormant ranges.
  - Dormant ranges no longer count when determining if the headers should be highlighted.
  - The leader, chosen as a self-identifying leader with the highest term, now has what is considered the "correct" values and values that don't match (in specific headers) are highlighted.
  - A collection of other fixes and optimizations that fell out from the re-write.
- Fixes from #13793
  - Fixed the key range output
  - Displays the lease type
  - Updated the header to be "LeaseHolder" instead of "Lease"

Some aspects from #13749 have been addressed:
  - Right-aligned labels
  - Highlight values that don't match the leader
  - No styling changes as of yet

Fixes #13793

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13842)

### CODE REVIEW

**Comment by BramGruneir** [comment]
Apologies in advance about the size of this PR.

**Comment by BramGruneir** [comment]
screen shot 2017-02-28 at 11 14 06

**Comment by tamird** [comment]
Maybe this is a stupid question, but why aren't we using the UI framework
for this?

**Comment by BramGruneir** [comment]
After discussions with the frontend team, it was determined that at this time it shouldn't be.  We did agree to consider moving it to the UI at a later date.

The primary reasons where
- This is a debug page, so the extra styling isn't needed. Furthermore, most of the rest of the framework isn't needed either.  Reload logic, history, etc.
- We wanted to get something up and running quickly, and without much frontend help (they're fully booked already), that would take me a lot more time.

**Comment by bdarnell** [comment]
LGTM, but I mainly skimmed it. 

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/server/debug_range.go, line 227 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13842#-Ke59ikxICSJep6844uw:-Ke59ikxICSJep6844ux:b-nw0ml2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7720e6208edaa13507e94d2d878f016a1bf1edb5/pkg/server/debug_range.go#L227)):*
> ```Go
> 
> func (d *debugRangeData) postProcessing() {
> 	d.HeaderFakeStoreID = roachpb.StoreID(0)
> ```

Why is this a member instead of a global constant?

---

*[pkg/server/debug_range.go, line 730 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13842#-Ke5AU-JdpCbPr9_SVnA:-Ke5AU-K05Xx_Tz4TSPV:bt95461) ([raw file](https://github.com/cockroachdb/cockroach/blob/7720e6208edaa13507e94d2d878f016a1bf1edb5/pkg/server/debug_range.go#L730)):*
> ```Go
>       <H1>Range r{{$.RangeID}}</H1>
>       {{- if $.ReplicaIDs}}
>         <DIV CLASS="table">
> ```

Why is this all `<div>`s instead of an actual `<table>`?  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13842#-:-Ke59HnPFbqvYcmaEERm:bc2k01w)*

**Comment by BramGruneir** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/server/debug_range.go, line 227 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13842#-Ke59ikxICSJep6844uw:-Ke5CdWElc9VDAHGPR5g:b-b61e3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/7720e6208edaa13507e94d2d878f016a1bf1edb5/pkg/server/debug_range.go#L227)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Why is this a member instead of a global constant?
</blockquote></details>

To be able to access it in the template, it needs to be passed in as part of the struct.

---

*[pkg/server/debug_range.go, line 730 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13842#-Ke5AU-JdpCbPr9_SVnA:-Ke5Cg3EIstHqvslmYEj:blpo8ly) ([raw file](https://github.com/cockroachdb/cockroach/blob/7720e6208edaa13507e94d2d878f016a1bf1edb5/pkg/server/debug_range.go#L730)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Why is this all `<div>`s instead of an actual `<table>`?  
</blockquote></details>

Modern CSS style.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13842)*

**Pull request merged**
