### PR TITLE
sql: DROP TABLE respects dynamic zone config GC TTL

### LINKED ISSUE #21887: sql: can't control time of actual deletion after DROP/TRUNCATE is issued
Discussed with @vivekmenezes.

The scenario went as follows:
1. cluster says "disk full"
2. I go and look and see a large table
3. I run "DROP TABLE", *expecting this to release disk space*
4. the disk space doesn't get released
5. I ask around and I learn "oh there is a GC period by default 25 hours"
6. so I *change the zone config to lower the GC period*
7. disk space still doesn't get released - what up with that?

Problem: **the deletion of entire tables goes via a separate mechanism than the GC period in the zone config**: a periodic task by the schema manager iterates through all dropped table descriptors and, if the delay has expired, calls RocksDB  "ClearRange" on that table's entire range.

That deletion GC delay *is stored in the table descriptor itself* (the descriptor marked for deletion). It is populated at the time the TRUNCATE/DROP is issued by the `ttlseconds` field from the zone config, but the zone config is not used further beyond this point.

**in particular if the zone is modified after DROP is issued, this will have no impact on when the data gets actually deleted.**

This also manifest in another scenario:
1. I truncate a table.
2. A couple hours later, my coworker says "hmm, we're looking into it, but we might still have a couple legacy orders that were in that table -- we'll check and use AS OF SYSTEM TIME to get what we need"
3. I've read about TTLs so I say "oh, okay, well, we have until the TTL to read the old data, so I'll extend the TTL on that table to 7 days"
4. 28 hours later, `AS OF SYSTEM TIME` starts failing on the GC Threshold, even though, according to my TTL, it shouldn't have deleted it yet?

Two main UX problems:
- there is no way to say "drop this table data now!" regardless of current zone config
- can't change "drop this table data in 25 hours" to "drop this table data now" after TRUNCATE/DROP has been issued

Idea by @vivekmenezes: instead of marking table descriptors as "deleted", rename them to go in a special "trash" database (knz: I assume with limited permissions so they also become invisible to app queries). Then if + when desired issue DROP on the "trash" database to actually do ClearRange *synchronously*.

### PR DESCRIPTION
**Pull request by vivekmenezes**
fixes #21887

Release note: None

### CODE REVIEW

**Comment by vivekmenezes** [comment]
I'll be modifying one of the tests to test this. Coming in a few hours

**Comment by dt** [comment]
Reviewed 8 of 9 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/drop_table.go, line 337 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22774#-L5VYyKjg0w7AiXKjgs5:-L5VYyKjg0w7AiXKjgs6:b-xvf2io) ([raw file](https://github.com/cockroachdb/cockroach/blob/92fa21086c2de350fa3034ba6c7f4cc064e009a6/pkg/sql/drop_table.go#L337)):*
> ```Go
> 		}
> 
> 		tableDesc.DropTime = timeutil.Now().UnixNano()
> ```

What happens if someone has a mixed version cluster? Since we reused the ID below, can an older node see this time in the field but think that it is a gcdeadline and immediately decide it is time to clear?

---

*[pkg/sql/schema_changer.go, line 1090 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22774#-L5V_AnSBFkZMusyJBBw:-L5V_AnSBFkZMusyJBBx:b4cqme0) ([raw file](https://github.com/cockroachdb/cockroach/blob/92fa21086c2de350fa3034ba6c7f4cc064e009a6/pkg/sql/schema_changer.go#L1090)):*
> ```Go
> 								if found {
> 									deadline := table.DropTime + int64(c.GC.TTLSeconds)*time.Second.Nanoseconds()
> 									schemaChanger.execAfter = timeutil.Unix(0, deadline)
> ```

huh, does execAfter means it won't wake up again until that time?  How does the test above notice the changed TTL and clear it sooner?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22774)*

**Comment by vivekmenezes** [comment]
Review status: 7 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/drop_table.go, line 337 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22774#-L5VYyKjg0w7AiXKjgs5:-L5djZrlzDcQoZ8JVjHH:b7ky9yw) ([raw file](https://github.com/cockroachdb/cockroach/blob/92fa21086c2de350fa3034ba6c7f4cc064e009a6/pkg/sql/drop_table.go#L337)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

What happens if someone has a mixed version cluster? Since we reused the ID below, can an older node see this time in the field but think that it is a gcdeadline and immediately decide it is time to clear?
</blockquote></details>

This works fine for transitioning from 1.1 to 2.0 if there is an already existing dropped table (its gc_deadline will become drop_time and the gc time will be pushed further out). It's only a problem if during an upgrade a DROP is executed on a 2.0 node and is picked up for a 1.1 node. I think it's okay for us not to support this. I don't see why someone would be dropping a table in the middle of an upgrade, and if they do it's only preventing them from running AS OF SYSTEM TIME queries.

---

*[pkg/sql/schema_changer.go, line 1090 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22774#-L5V_AnSBFkZMusyJBBw:-L5dkC9AlhpciePQsqHO:bdwmcmv) ([raw file](https://github.com/cockroachdb/cockroach/blob/92fa21086c2de350fa3034ba6c7f4cc064e009a6/pkg/sql/schema_changer.go#L1090)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

huh, does execAfter means it won't wake up again until that time?  How does the test above notice the changed TTL and clear it sooner?
</blockquote></details>

I'd originally thought the zone config push would trigger a new system config gossip and that would wake this up. Well it does but unfortunately the code uses cfgFilter.ForModified() which is unable to queue a new schema change with a new zone config. I tried figuring out how we could make cfgFilter.ForModified() work but then I thought it's kind of not worth it, so I've introduced a 10 minute poll which checks if the gc TTL has expired.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22774)*

**Comment by vivekmenezes** [comment]
Ready for another look

**Comment by dt** [comment]
:lgtm: 

---

Review status: 7 of 9 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/drop_table.go, line 337 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22774#-L5VYyKjg0w7AiXKjgs5:-L5ofYNX_-yiX9M3hTPb:b-6unzf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/92fa21086c2de350fa3034ba6c7f4cc064e009a6/pkg/sql/drop_table.go#L337)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

This works fine for transitioning from 1.1 to 2.0 if there is an already existing dropped table (its gc_deadline will become drop_time and the gc time will be pushed further out). It's only a problem if during an upgrade a DROP is executed on a 2.0 node and is picked up for a 1.1 node. I think it's okay for us not to support this. I don't see why someone would be dropping a table in the middle of an upgrade, and if they do it's only preventing them from running AS OF SYSTEM TIME queries.
</blockquote></details>

Hm.  I wasn't thinking about 1.1... in that case, the 1.1 node would just start MVCC deleting the data, right? that's fine w.r.t. AS OF SYSTEM TIME and such.

I was thinking there's an issue if someone has been running a 2.0 alpha, right? A table dropped at time X on node that has this change will write X in this field, then one of the non-upgraded 2.0 alpha nodes would see X, think it is the deadline, is in the past and think it should be instantly GC'ed, right?

---

*[pkg/sql/drop_test.go, line 269 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22774#-L5oZeFa1iDBo92apgJn:-L5oZeFa1iDBo92apgJo:b-fybm6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/48582fa4fb7e68fb4ad9dd6012f6ca99a415e52e/pkg/sql/drop_test.go#L269)):*
> ```Go
> 	tests.CheckKeyCount(t, kvDB, tableSpan, 6)
> 
> 	time.Sleep(100 * time.Millisecond)
> ```

hm. Is there a condition we're waiting for here? If so, could we wait for that with a `SucceedsSoon` instead of just a fixed sleep? Either way (though particularly with just the sleep), could use a comment as to why we're sleeping.

---

*[pkg/sql/schema_changer.go, line 316 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22774#-L5oenJc8SaDXEh22yqU:-L5oenJc8SaDXEh22yqV:b-9dl2vq) ([raw file](https://github.com/cockroachdb/cockroach/blob/48582fa4fb7e68fb4ad9dd6012f6ca99a415e52e/pkg/sql/schema_changer.go#L316)):*
> ```Go
> 			}
> 			if wait {
> 				return false, errors.Errorf("still not hit TTL deadline: %s",
> ```

nit: might be a little easier to debug if we pulled included either the TTL or the time remaining in this message

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22774#-:-L5ofVe2NwcVM6WKp55L:bg7igkv)*

**Comment by vivekmenezes** [comment]
TFTR!

---

Review status: 5 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/drop_table.go, line 337 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22774#-L5VYyKjg0w7AiXKjgs5:-L5on9RjmwjmQuWYYiFt:b-zfz0o5) ([raw file](https://github.com/cockroachdb/cockroach/blob/92fa21086c2de350fa3034ba6c7f4cc064e009a6/pkg/sql/drop_table.go#L337)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Hm.  I wasn't thinking about 1.1... in that case, the 1.1 node would just start MVCC deleting the data, right? that's fine w.r.t. AS OF SYSTEM TIME and such.

I was thinking there's an issue if someone has been running a 2.0 alpha, right? A table dropped at time X on node that has this change will write X in this field, then one of the non-upgraded 2.0 alpha nodes would see X, think it is the deadline, is in the past and think it should be instantly GC'ed, right?
</blockquote></details>

True, but we don't support alpha releases

---

*[pkg/sql/drop_test.go, line 269 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22774#-L5oZeFa1iDBo92apgJn:-L5onGCxmyfppXBiOdeC:b-h62g64) ([raw file](https://github.com/cockroachdb/cockroach/blob/48582fa4fb7e68fb4ad9dd6012f6ca99a415e52e/pkg/sql/drop_test.go#L269)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

hm. Is there a condition we're waiting for here? If so, could we wait for that with a `SucceedsSoon` instead of just a fixed sleep? Either way (though particularly with just the sleep), could use a comment as to why we're sleeping.
</blockquote></details>

removed. Left in by mistake

---

*[pkg/sql/schema_changer.go, line 316 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22774#-L5oenJc8SaDXEh22yqU:-L5ov2w1Qm5mjU4wazmY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/48582fa4fb7e68fb4ad9dd6012f6ca99a415e52e/pkg/sql/schema_changer.go#L316)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

nit: might be a little easier to debug if we pulled included either the TTL or the time remaining in this message
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22774#-:-L5ov3b2R_LgKI-eo2Hp:b-814g8k)*

**Pull request merged**
