### PR TITLE
admission: adjust token computation during WAL failover

### PR DESCRIPTION
**Pull request by sumeerbhola**
During WAL failover, possibly caused by a disk stall in the primary location, flushes and compactions can also be stalled. This can cause admission control to compute artificially low token counts for compaction bandwidth out of L0 (if L0 has elevated score), and flush tokens (which are meant to prevent memtable write stalls).

The solution outlined here detects WAL failover by looking at increases in the pebble metric WAL.Failover.SecondaryWriteDuration. If an increase happened in the last 15s interval (the token computation interval), the current flush and compaction bytes are ignored for the purpose of smoothing and therefore ignored for computing tokens. For regular work, the previous smoothed compaction tokens continue to be used, and flush tokens are unlimited. For elastic work, the tokens are reduced to near zero. An alternative is to allow unlimited tokens during the stall, but it runs the risk of over-admitting. We allow this alternative to be configured by changing the cluster setting
admission.wal.failover.unlimited_tokens.enabled to true.

Informs cockroachdb/pebble#3230

Informs CRDB-35401

Epic: none

Release note (ops change): The cluster setting
admission.wal.failover.unlimited_tokens.enabled can be set to true to cause unlimited admission tokens during WAL failover. This should not be changed without consulting admission control team since the default, which preserves the token counts from the preceding non-WAL-failover interval, is expected to be safer.

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
I'll add tests if this looks ok.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120135#-:-NsTl5cnBe76uFLGwhOG:b84mw30)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi and @jbowens)

**Review by aadityasondhi — COMMENTED** [review]
Looks good to me so far

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120135#-:-NsizNiREanmDMpmp7qS:b9gjig)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jbowens)

**Review by aadityasondhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120135)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @sumeerbhola)

___
*[`pkg/util/admission/io_load_listener.go` line 785 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120135#-Nsizv93-5hV8U7_bBFW:-Nsizv93-5hV8U7_bBFX:bvktfyj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f7a1f5a58d93ff626aa820344587579c6ccc2aa/pkg/util/admission/io_load_listener.go#L785)):*
> ```Go
> 	// once the primary is considered healthy, say within 10s. So a disk stall
> 	// in the primary that lasts 30s, will cause WAL failover for ~40s, and a
> 	// disk stall for 1s will cause failover for ~11s. The latter (11s) is short
> ```

In the former case, are we worried that an extended failover will cause a backlog of flushes that will then hit L0 all at the same time once we failback?

**Review by sumeerbhola — COMMENTED** [review]
TFTR! I will ping when tests are ready.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120135#-:-Nsmxe7Z21AqeJq8f2ZM:bi6ofox)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi and @jbowens)

___
*[`pkg/util/admission/io_load_listener.go` line 785 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120135#-Nsizv93-5hV8U7_bBFW:-NsmxKBd1fmbDbgZfv3I:b7qnukr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f7a1f5a58d93ff626aa820344587579c6ccc2aa/pkg/util/admission/io_load_listener.go#L785)):*
<details><summary><i>Previously, aadityasondhi (Aaditya Sondhi) wrote…</i></summary><blockquote>

In the former case, are we worried that an extended failover will cause a backlog of flushes that will then hit L0 all at the same time once we failback?
</blockquote></details>

If we have a backlog of immutable memtables they are all flushed in one flush, so will add a single sub-level.

**Review by sumeerbhola — COMMENTED** [review]
test is ready

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120135#-:-NstpQZv6wHdUZNfeLxa:bv06lg6)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi and @jbowens)

**Review by aadityasondhi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120135#-:-NsyFHeN3MBhm-yMffYE:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Comment by sumeerbhola** [comment]
bors r=aadityasondhi

**Pull request merged**
