### PR TITLE
catkv,*: remove catkv.Direct interface

### PR DESCRIPTION
**Pull request by postamar**
Informs #64089.

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm: very nice

> Reviewed 5 of 5 files at r1, 5 of 5 files at r2, 2 of 2 files at r3, 12 of 12 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, 31 of 31 files at r7, 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93611#-:-NJHDLNg8Gr0xnSHhD29:b-k1vyq0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)

**Comment by postamar** [comment]
Thanks for the review! CI is unhappy due to an unrelated flaky test.

bors r+

**Comment by postamar** [comment]
The flake wasn't unrelated and in fact the workload test found a legit bug! I'm grateful for it.

**Pull request merged**
