### PR TITLE
storage: Allow the allocator to rebalance replicas away from an incorrect node/store

### PR DESCRIPTION
**Pull request by BramGruneir**
This change allows the allocator to determine when there are replicas on nodes or stores that fail a constraint check. This can happen when a zone config is changed after the replicas are already present. This change cannot remove replicas if they currently hold the lease so a bit more work is still needed.

Before merging, I'd like to test this out on a real cluster and via allocsim.  I'll post any pertinent results to this issue.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13288)

### CODE REVIEW

**Comment by BramGruneir** [comment]
cc: @jseldess

**Comment by tamird** [comment]
> This change cannot remove replicas if they currently hold the lease so a bit more work is still needed.

Meaning this change will not do so, or it would be incorrect for this code to do so? Please be precise.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/storage/allocator.go, line 299 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288#-KblIEoBMTKUOBt_z21c:-KblIEoBMTKUOBt_z21d:b5qatxb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0015b7ad6bc2f5cd2a4795a8864315f5952e626/pkg/storage/allocator.go#L299)):*
> ```Go
> 	rangeID roachpb.RangeID,
> ) (*roachpb.StoreDescriptor, error) {
> ```

random empty line

---

*[pkg/storage/allocator_test.go, line 1642 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288#-KblQudm0JWhgoAX7Cjk:-KblQudm0JWhgoAX7Cjl:b-tuirf6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0015b7ad6bc2f5cd2a4795a8864315f5952e626/pkg/storage/allocator_test.go#L1642)):*
> ```Go
> 		constraint       config.Constraint
> 		existing         []int
> 		expectedStoreIDs []int
> ```

this is really more `permittedStoreIDs`, isn't it? also, it seems like this wants to be a `*int` since it's always one ID or none.

---

*[pkg/storage/allocator_test.go, line 1705 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288#-KblQWYnrKPVP1UwY84V:-KblQWYnrKPVP1UwY84W:b-k91o5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0015b7ad6bc2f5cd2a4795a8864315f5952e626/pkg/storage/allocator_test.go#L1705)):*
> ```Go
> 
> 	for _, tc := range testCases {
> 		t.Run(fmt.Sprintf("%s", tc.constraint), func(t *testing.T) {
> ```

nit: tc.constraint.String()?

---

*[pkg/storage/allocator_test.go, line 1706 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288#-KblQogN_k3ITof6MGR9:-KblQogN_k3ITof6MGRA:b-5sdh19) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0015b7ad6bc2f5cd2a4795a8864315f5952e626/pkg/storage/allocator_test.go#L1706)):*
> ```Go
> 	for _, tc := range testCases {
> 		t.Run(fmt.Sprintf("%s", tc.constraint), func(t *testing.T) {
> 			existingReplicas := make([]roachpb.ReplicaDescriptor, len(tc.existing), len(tc.existing))
> ```

why do you need to specify the capacity?

---

*[pkg/storage/allocator_test.go, line 1726 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288#-KblQfhtcQOeDZ8InN0-:-KblQfhtcQOeDZ8InN00:btd1zeb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0015b7ad6bc2f5cd2a4795a8864315f5952e626/pkg/storage/allocator_test.go#L1726)):*
> ```Go
> 				t.Fatal(err)
> 			}
> 			if result == nil {
> ```

do you really need the special case?

---

*[pkg/storage/allocator_test.go, line 1874 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288#-KblMxXKN3HxAb8k1bA4:-KblMxXKN3HxAb8k1bA5:b-hbxjfv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0015b7ad6bc2f5cd2a4795a8864315f5952e626/pkg/storage/allocator_test.go#L1874)):*
> ```Go
> 	// | gen | store 0  | store 1  | store 2  | store 3  | store 4  | store 5  | store 6  | store 7  | store 8  | store 9  | store 10 | store 11 | store 12 | store 13 | store 14 | store 15 | store 16 | store 17 | store 18 | store 19 |
> 	// +-----+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+
> 	// |   0 |   1  48% |   0   0% |   0   0% |   1  51% |   0   0% |   0   0% |   0   0% |   0   0% |   0   0% |   0   0% |   0   0% |   0   0% |   0   0% |   0   0% |   0   0% |   0   0% |   0   0% |   0   0% |   0   0% |   0   0% |
> ```

this should not have changed.

---

*[pkg/storage/rule_solver.go, line 39 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288#-KblMpAvYvw8Cg3UJC3Q:-KblMpAw5_N9HcZS4NHq:b-g5w43b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0015b7ad6bc2f5cd2a4795a8864315f5952e626/pkg/storage/rule_solver.go#L39)):*
> ```Go
> 
> func rebalanceFromConvergesOnMean(sl StoreList, candidate roachpb.StoreDescriptor) bool {
> 	return float64(candidate.Capacity.RangeCount) > sl.candidateCount.mean+rebalanceThreshold
> ```

why did these change? I think you misunderstood the origin of the value 0.5 here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288#-:-KblIGrypnyl6iBYZUgR:bw7lffe)*

**Comment by petermattis** [comment]
:lgtm:

> This change cannot remove replicas if they currently hold the lease so a bit more work is still needed.

I think this is inaccurate. We will transfer the lease when we select the leaseholder for removal.

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288#-:-KbqNeDoSctUV3cxN_Hx:bqyqmqb)*

**Comment by BramGruneir** [comment]
> We will transfer the lease when we select the leaseholder for removal.

I didn't observe this when I tested it 3 weeks ago.  I'll do some more testing to be sure.  It might be some other issue as well.

---

Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[pkg/storage/allocator.go, line 299 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288#-KblIEoBMTKUOBt_z21c:-KbpEnn8g54MExqgG6rV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0015b7ad6bc2f5cd2a4795a8864315f5952e626/pkg/storage/allocator.go#L299)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

random empty line
</blockquote></details>

Done.

---

*[pkg/storage/allocator_test.go, line 1642 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288#-KblQudm0JWhgoAX7Cjk:-KbpO_Ot_43CgzeOLJjo:bq6o9j4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0015b7ad6bc2f5cd2a4795a8864315f5952e626/pkg/storage/allocator_test.go#L1642)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this is really more `permittedStoreIDs`, isn't it? also, it seems like this wants to be a `*int` since it's always one ID or none.
</blockquote></details>

cleaned this up

---

*[pkg/storage/allocator_test.go, line 1705 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288#-KblQWYnrKPVP1UwY84V:-KbpOeuRiiT-O1as0KvB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0015b7ad6bc2f5cd2a4795a8864315f5952e626/pkg/storage/allocator_test.go#L1705)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: tc.constraint.String()?
</blockquote></details>

Done.

---

*[pkg/storage/allocator_test.go, line 1706 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288#-KblQogN_k3ITof6MGR9:-KbpOlMTbeXcE8R32N9d:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0015b7ad6bc2f5cd2a4795a8864315f5952e626/pkg/storage/allocator_test.go#L1706)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why do you need to specify the capacity?
</blockquote></details>

Done.

---

*[pkg/storage/allocator_test.go, line 1726 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288#-KblQfhtcQOeDZ8InN0-:-KbpOmK6GvL1JnQvRzF_:bb7lgjf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0015b7ad6bc2f5cd2a4795a8864315f5952e626/pkg/storage/allocator_test.go#L1726)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

do you really need the special case?
</blockquote></details>

nope

---

*[pkg/storage/allocator_test.go, line 1874 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288#-KblMxXKN3HxAb8k1bA4:-KcF0qAXsenDKtGFj0vO:b-puoifw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0015b7ad6bc2f5cd2a4795a8864315f5952e626/pkg/storage/allocator_test.go#L1874)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this should not have changed.
</blockquote></details>

In this case it should change.  When shouldRebalance existed, it would act as a filter from calling rebalanceCandidates.  Now that filter is removed and we rely on the rules of rebalanceCandidates alone.

---

*[pkg/storage/rule_solver.go, line 39 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288#-KblMpAvYvw8Cg3UJC3Q:-KbpP3ArmHz7vIBZJcUt:bx2z17z) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0015b7ad6bc2f5cd2a4795a8864315f5952e626/pkg/storage/rule_solver.go#L39)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why did these change? I think you misunderstood the origin of the value 0.5 here.
</blockquote></details>

you're right, they shouldn't have, reverted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288#-:-KcFEvLti6nLl3dC2CKU:b-ko9mgn)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/storage/allocator_test.go, line 1874 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288#-KblMxXKN3HxAb8k1bA4:-KcJ529S0aJTOFjNvn1F:b378ckq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0015b7ad6bc2f5cd2a4795a8864315f5952e626/pkg/storage/allocator_test.go#L1874)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

In this case it should change.  When shouldRebalance existed, it would act as a filter from calling rebalanceCandidates.  Now that filter is removed and we rely on the rules of rebalanceCandidates alone.
</blockquote></details>

There must be something missing in the commit message, because it is surprising that this change given how the commit message is written.

---

*[pkg/storage/allocator_test.go, line 1708 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288#-KcJ4GGFFRgw3XYPxWGn:-KcJ4GGFFRgw3XYPxWGo:b-e9c61y) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a257756e972d8a341e9224ea7356a51dc02f71/pkg/storage/allocator_test.go#L1708)):*
> ```Go
> 				t.Fatal(err)
> 			}
> 			if !reflect.DeepEqual(tc.expected, actual) {
> ```

unusual to do this for comparing values via pointer, but i guess it's ok

---

*[pkg/storage/allocator_test.go, line 1709 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288#-KcJ4MF_AyuRrropgrpC:-KcJ4JkuUppvlwguzb0h:b-wylw60) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a257756e972d8a341e9224ea7356a51dc02f71/pkg/storage/allocator_test.go#L1709)):*
> ```Go
> 			}
> 			if !reflect.DeepEqual(tc.expected, actual) {
> 				t.Errorf("rebalancing to the incorrect store, expected %s, got %s", tc.expected, actual)
> ```

what does this look like when one of the arguments is nil?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288)*

**Comment by BramGruneir** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/storage/allocator_test.go, line 1874 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288#-KblMxXKN3HxAb8k1bA4:-KcTtbuV7g2xhSW4FWc9:bsnk27m) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0015b7ad6bc2f5cd2a4795a8864315f5952e626/pkg/storage/allocator_test.go#L1874)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

There must be something missing in the commit message, because it is surprising that this change given how the commit message is written.
</blockquote></details>

I see what you mean, I've added some details.

---

*[pkg/storage/allocator_test.go, line 1708 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288#-KcJ4GGFFRgw3XYPxWGn:-KcTqMOOSztLI8af-Ii-:by1an7o) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a257756e972d8a341e9224ea7356a51dc02f71/pkg/storage/allocator_test.go#L1708)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

unusual to do this for comparing values via pointer, but i guess it's ok
</blockquote></details>

yeah, changed it to look at storeID instead.

---

*[pkg/storage/allocator_test.go, line 1709 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288#-KcJ4MF_AyuRrropgrpC:-KcT_wPrAP5hyqaAPBYi:bn77rxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a257756e972d8a341e9224ea7356a51dc02f71/pkg/storage/allocator_test.go#L1709)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

what does this look like when one of the arguments is nil?
</blockquote></details>

Pretty ugly, cleaned this up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288)*

**Comment by BramGruneir** [comment]
After testing this in a realistic setting, the replicate queue is continuously full.  So progress is extremely slow.  I'll revisit replicateQueue's shouldQueue and figure out the issue.  But this is not ready for merging yet.

---

Review status: 1 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288#-:-KcxBKHgi_EBbayoB8uX:b-b3yf3s)*

**Comment by BramGruneir** [comment]
I've performed a good amount of further testing and while most of the replicas move correctly, the whole system begins to stall as once we hit some threshold where most of the replicas have been removed from a store or two and there is a large amount of thrashing for all ranges quickly adding and removing replicas from the same store.

I tried re-adding back in shouldRebalance in (both as part of rebalanceCandidates and on its own in front of it), but this didn't change fix the problem.  I'm going to start adding more logging to get some better insight into what's happening.

---

Review status: 1 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288#-:-Ke__2PLnNCNmDSHRd5t:b-lhzcji)*

**Comment by BramGruneir** [comment]
After some more investigation, this thrashing occurs when the replica that needs to be removed during a rebalance is the one holding the lease.
See #13973 for more details.

---

Review status: 1 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288#-:-KeehSjqZy0SA_uuUNvX:beqbbo3)*

**Comment by BramGruneir** [comment]
Replaced by #14106.

---

Review status: 1 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13288#-:-Kf4zlvIu1e5aOpJ__lz:b-3w7dz5)*

**Pull request closed without merging**
