### PR TITLE
col: move types,coldata,colserde under new top-level col package

### PR DESCRIPTION
**Pull request by danhhz**
pkg/sql/exec/types -> pkg/col/coltypes
pkg/sql/exec/coldata -> pkg/col/coldata
pkg/sql/exec/colserde -> pkg/col/colserde
pkg/sql/exec/types/conv -> pkg/sql/exec/typeconv

For three reasons:
1) Make it obvious which of our packages are an independent columnar
   data library and which are tied to our sql execution (colrpc).
2) In the process, rename types to coltypes to clear up importing
   confusion.
3) Allow workload to blanket ban deps on anything in pkg/sql.

Release note: None

### CODE REVIEW

**Comment by danhhz** [comment]
Removing jordan, who is on vacation. whoops

**Review by yuzefovich — APPROVED** [review]
Thanks for taking this on! A few nits, but it :lgtm:

> Reviewed 158 of 158 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39569#-:-LmBSW8o-pw0JNWlcOvK:bqbxtj4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @danhhz)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39569#-LmBPMV2Cx8oa4UpwhMV:-LmBPMV2Cx8oa4UpwhMW:b-nat85e) ([raw file](https://github.com/cockroachdb/cockroach/blob/84ea181543f0cbb895e554a4b55d056025fc8dd4/pkg/sql/distsqlrun/column_exec_setup.go#L112)):*
> ```Go
> 
> 	// Planning additional operators for the PostProcessSpec (filters and render
> 	// expressions) requires knowing the operator's output column coltypes. Currently
> ```

[nit]: `s/coltypes/types/`.
___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 889 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39569#-LmBPYWi9d36QmSssOvy:-LmBPYWi9d36QmSssOvz:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/84ea181543f0cbb895e554a4b55d056025fc8dd4/pkg/sql/distsqlrun/column_exec_setup.go#L889)):*
> ```Go
> 
> // assertHomogeneousTypes checks that the left and right sides of an expression
> // have identical coltypes. (Vectorized execution does not yet handle mixed coltypes.)
> ```

ditto
___
*[pkg/sql/exec/coalescer.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39569#-LmBQ0LN6ppNrMLUYUV1:-LmBQ0LO6KVwGC56kWF0:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/84ea181543f0cbb895e554a4b55d056025fc8dd4/pkg/sql/exec/coalescer.go#L34)):*
> ```Go
> 
> // NewCoalescerOp creates a new coalescer operator on the given input operator
> // with the given column coltypes.
> ```

ditto
___
*[pkg/sql/exec/hashjoiner.go, line 742 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39569#-LmBQKLr9vr6IxI7mxW9:-LmBQKLr9vr6IxI7mxWA:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/84ea181543f0cbb895e554a4b55d056025fc8dd4/pkg/sql/exec/hashjoiner.go#L742)):*
> ```Go
> 	buildDistinct bool,
> ) *hashJoinProber {
> 	// Prepare the output batch by allocating with the correct column coltypes.
> ```

ditto
___
*[pkg/sql/exec/select_in_tmpl.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39569#-LmBR64I3zav5PFRv4zt:-LmBR64J9TOeRoHPaRHR:b-7aq4bo) ([raw file](https://github.com/cockroachdb/cockroach/blob/84ea181543f0cbb895e554a4b55d056025fc8dd4/pkg/sql/exec/select_in_tmpl.go#L44)):*
> ```Go
> var _ apd.Decimal
> 
> // Dummy import to pull in "types" package
> ```

[nit]: `s/types/coltypes/`
___
*[pkg/col/coldata/vec.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39569#-LmBOLmlDAEJvoxRpZmL:-LmBOLmlDAEJvoxRpZmM:b-nat85e) ([raw file](https://github.com/cockroachdb/cockroach/blob/84ea181543f0cbb895e554a4b55d056025fc8dd4/pkg/col/coldata/vec.go#L76)):*
> ```Go
> 
> // Vec is an interface that represents a column vector that's accessible by
> // Go native coltypes.
> ```

[nit]: `s/coltypes/types/`.

**Comment by yuzefovich** [comment]
The blank comments were:
(twice) `s/coltypes/types/`
(once) `s/types/coltypes/`

**Review by danhhz — COMMENTED** [review]
Thanks for the review!

bors r=yuzefovich

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39569#-:-LmDekjM2bDeMYFQ8g04:b-3onzcc)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39569#-LmBPMV2Cx8oa4UpwhMV:-LmC8vH47PZK-DPdm_Wk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/84ea181543f0cbb895e554a4b55d056025fc8dd4/pkg/sql/distsqlrun/column_exec_setup.go#L112)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: `s/coltypes/types/`.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 889 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39569#-LmBPYWi9d36QmSssOvy:-LmC90HFBTLYzmcHOftY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/84ea181543f0cbb895e554a4b55d056025fc8dd4/pkg/sql/distsqlrun/column_exec_setup.go#L889)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/exec/coalescer.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39569#-LmBQ0LN6ppNrMLUYUV1:-LmC95-LAswAP2-b85Ez:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/84ea181543f0cbb895e554a4b55d056025fc8dd4/pkg/sql/exec/coalescer.go#L34)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/exec/hashjoiner.go, line 742 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39569#-LmBQKLr9vr6IxI7mxW9:-LmC9ecVC8RRecyiavQz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/84ea181543f0cbb895e554a4b55d056025fc8dd4/pkg/sql/exec/hashjoiner.go#L742)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/exec/select_in_tmpl.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39569#-LmBR64I3zav5PFRv4zt:-LmC9q9q4dIeRIvsr4b7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/84ea181543f0cbb895e554a4b55d056025fc8dd4/pkg/sql/exec/select_in_tmpl.go#L44)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: `s/types/coltypes/`
</blockquote></details>

Done.
___
*[pkg/col/coldata/vec.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39569#-LmBOLmlDAEJvoxRpZmL:-LmC8f010vz2HB_MjOS3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/84ea181543f0cbb895e554a4b55d056025fc8dd4/pkg/col/coldata/vec.go#L76)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: `s/coltypes/types/`.
</blockquote></details>

Done.

**Pull request merged**
