### PR TITLE
ci: delete most scripts from GitHub CI

### PR DESCRIPTION
**Pull request by rickystewart**
Release note: None
Epic: [CRDB-20016](https://cockroachlabs.atlassian.net/browse/CRDB-20016)

### CODE REVIEW

**Review by jlinder — COMMENTED** [review]
A couple questions:

- Do any of these scripts call other scripts that are only called by these scripts? If so, let's remove them too.
- Wouldn't this change be part of epic CRDB-20016?

**Review by rail — APPROVED** [review]

**Comment by rickystewart** [comment]
> Do any of these scripts call other scripts that are only called by these scripts? If so, let's remove them too

I didn't find any, but I was able to delete an unused function from `build/teamcity-support.sh`.

**Comment by rickystewart** [comment]
YOLO bors r=rail

**Comment by rickystewart** [comment]
YOLO

bors r=rail

**Comment by rickystewart** [comment]
bors r=rail

**Comment by rickystewart** [comment]
bors r=rail

**Pull request merged**
