### PR TITLE
cli: temporarily skip TestPartialZip and CDC tests

### PR DESCRIPTION
**Pull request by knz**
Due to #51538

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
Thanks!

**Comment by knz** [comment]
bors r=tbg

**Comment by knz** [comment]
bors r-

bors r=tbg

**Comment by knz** [comment]
the CI is flaking on  #51543

**Comment by knz** [comment]
Skipping the CDC tests

**Comment by knz** [comment]
bors r=tbg

**Comment by knz** [comment]
The CI is flaking on #51544 and unfortunately I can't skip that.

**Comment by knz** [comment]
typo :facepalm:

**Comment by knz** [comment]
bors r=tbg

**Pull request merged**
