### PR TITLE
kvadmission: bypass AC for `LeaseInfo` requests

### LINKED ISSUE #120411: kvserver: omit `LeaseInfo` requests in admission control
These are used as DistSender circuit breaker probes, and should not be subject to admission control.

Jira issue: CRDB-36677

Epic CRDB-25200

### PR DESCRIPTION
**Pull request by erikgrinaker**
**util/admission: allow application tenants to bypass AC**

This is needed e.g. to allow `LeaseInfo` requests to bypass AC, as these are used as health probes by tenant-side DistSender circuit breakers and should not be delayed.

The determination to bypass is still made on the KV server side, so this won't allow untrusted tenant pods to arbitrarily bypass AC.

**kvadmission: bypass AC for `LeaseInfo` requests**

These are used as makeshift replica health probes for DistSender circuit breakers, and should bypass admission control.

Resolves #120411.
Epic: none
Release note: None

### CODE REVIEW

**Comment by erikgrinaker** [comment]
@sumeerbhola I don't think this does what we want, because the `BypassAdmission` field is ignored for non-system tenants. The `LeaseInfo` health probes will be sent from tenant DistSenders. What's the most reliable way to have these bypass admission control?

I don't think we want these to be subject to AC, because latency increases may cause circuit breakers to trip resulting in unavailability.

**Review by sumeerbhola — COMMENTED** [review]
I think we should change the code in `admission.WorkQueue` so that it does not care whether something is the system tenant or not. It should be the responsibility of the caller to ensure that if `BypassAdmission` is set, the tenant or something else about the request, should allow it to bypass admission. You'll need to tweak the `WorkQueue` datadriven test slightly.

All calls to `WorkQueue.Admit` that are for KVWork originate in `controllerImpl.AdmitKVWork` (whether it is CPU slots WorkQueue, elastic WorkQueue or store WorkQueue), so we already have code centralization for this decision making.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120482#-:-NsxTtEA7MHyLYqGtMVO:bejova8)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by erikgrinaker — COMMENTED** [review]
Thanks, I added on a commit with that change.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120482#-:-Nt0inkHCvQodbAh6Egh:b9qt3h9)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120482#-:-Nt10wwu2o1T_CHFfnss:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by erikgrinaker** [comment]
TFTR!

bors r+

**Pull request merged**
