### PR TITLE
roachtest: update predecessor version and test fixtures for 23.2 version-upgrade roachtest

### PR DESCRIPTION
**Pull request by cameronnunez**
Part of https://cockroachlabs.atlassian.net/browse/REL-284 

This PR generates test fixtures for `acceptance/version-upgrade` so that this test can run on 23.2. It also updates the predecessor version for 23.2

Release note: None

### CODE REVIEW

**Review by renatolabs — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101252#-:-NU8bdLuDAqIvwY17jwN:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @celiala, @herkolategan, and @smg260)

**Review by celiala — APPROVED** [review]
Woo! 🎉 

Thank you for all the effort to unblock this @cameronnunez and @renatolabs 💯 ❤️ !

**Comment by cameronnunez** [comment]
thanks for the help all!

**Comment by cameronnunez** [comment]
bors r=celiala,renatolabs

**Pull request merged**
