### PR TITLE
sql: desugar "TIMESTAMP WITH TIME ZONE" to "TIMESTAMPTZ"

### PR DESCRIPTION
**Pull request by knz**
First commits from #28952 and priors.
Forked off #28690.

This is unfortunate because this is a pretty common type, and is
moreover used to disambiguate the return type of `now()` and thus will
be emitted pretty often in distsql physical plans. Having such a long
type name is unnecessary and indeed adds 50%+ storage, communication
and parsing overhead for every occurrence of this type in
distsql plans.

This patch shortens the canonical CockroachDB name to "TIMESTAMPTZ".

The representation of the type in introspection tables (pg_catalog,
information_schema) is unaffected.

Release note: None

### CODE REVIEW

**Comment by justinj** [comment]
>and indeed adds 50% planning and distribution overhead in common distsql executions.

can you expand on this? this seems quite high?

**Comment by knz** [comment]
> can you expand on this? this seems quite high?

It's a reference to the fact the string "TIMESTAMP WITH TIME ZONE" is more than 50% longer (to store, to parse, to send) than "TIMESTAMPTZ".

**Review by BramGruneir — CHANGES_REQUESTED** [review]
I agree with @justinj, I think the commit message needs to be updated a bit to tone down the 50% savings claim.

That being said, the change :LGTM: but I think we're missing a test or two to ensure the old verbose name still works.

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, 18 of 18 files at r3, 2 of 2 files at r4, 7 of 7 files at r5, 3 of 3 files at r6, 13 of 13 files at r7, 31 of 31 files at r8, 23 of 23 files at r9, 16 of 16 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28955#-:-LKYS_kS98TGz525zGQZ:b-p9a24e)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/logictest/testdata/logic_test/datetime, line 36 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/28955#-LKYSvDECLY7cir4KbEN:-LKYSvDECLY7cir4KbEO:bvv95qh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7efed6d60c1b5f895bf9dcaefd83f8cac03aee2e/pkg/sql/logictest/testdata/logic_test/datetime#L36)):*
> ```
>   a BIGINT PRIMARY KEY,
>   b TIMESTAMP,
>   c TIMESTAMPTZ,
> ```

Since we do still allow the longer type name, we should have at least one test to ensure it still works.

**Review by knz — COMMENTED** [review]
> I think the commit message needs to be updated a bit to tone down the 50% savings claim.

Done.

> I think we're missing a test or two to ensure the old verbose name still works.

- there is a parse test already
- the pgadmin queries in the opt testdata still use the long form (I left them unchanged since they come from an external source)
- filed a separate issue to add more pgdump tests: #29003.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28955#-:-LKaWW_f2YM27Dllbjc3:b1svr7e)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/datetime, line 36 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/28955#-LKYSvDECLY7cir4KbEN:-LKaZa4p5hKomtfTRG9A:b9ni9hu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7efed6d60c1b5f895bf9dcaefd83f8cac03aee2e/pkg/sql/logictest/testdata/logic_test/datetime#L36)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Since we do still allow the longer type name, we should have at least one test to ensure it still works.
</blockquote></details>

I agree, this test exists in two forms: `parse_test.go` verifies that `timestamp with time zone` reduces to the same coltype; and `opt/xform/testdata/external/pgadmin` verifies it works when imported from pgadmin.

**Pull request merged**
