### PR TITLE
sql: split emptyNode into unaryNode and zeroNode

### LINKED ISSUE #17839: sql: clean up emptyNode vs zeroNode, unaryNode
In SQL we have two special data sources:

- the "zero" node which has zero rows (and arbitrary columns); this is the result of e.g. applying a known-false filter like `WHERE false`.

- the "unary" node which has zero columns and exactly one row. This is used e.g. when the FROM clause is omitted altogether.

Currently in the code we use a single type `emptyNode` for both, with an attribute inside the struct to distinguish between them. This makes the code more difficult to read/comprehend in several places. It would be instead better to use two different, aptly named, types.

Requested/suggested by @justinj.
Really a reincarnation of #13203.

cc @andreimatei

### PR DESCRIPTION
**Pull request by justinj**
Fixes #17839.

### CODE REVIEW

**Comment by jordanlewis** [comment]
:lgtm: although I might be missing some context so I'd like to see what @knz thinks as well. Do we need any new EXPLAIN tests? If not, should we distinguish how the two nodes look in EXPLAIN?

---

Reviewed 25 of 25 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17899#-:-KsKkG2ht-vzljMGVB7w:bmo532q)*

**Comment by knz** [comment]
Jordan there are plenty of tests that show the unary node already (although I'd like to be renamed so these tests will need updating). I would like a new test for the zero node though. You can get one with `explain select ... where false`.

---

Reviewed 24 of 25 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/filter_opt.go, line 179 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17899#-KsNk6uvIxAks0ttWo_k:-KsNk6uvIxAks0ttWo_l:b-2u5ro2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2680bef010bde42ceebf0449bbd279c035217596/pkg/sql/filter_opt.go#L179)):*
> ```Go
> 		// are "already applied". Silently absorb any extra filter.
> 		return plan, parser.DBoolTrue, nil
> 		// TODO(knz): We could evaluate the filter here and set/reset
> ```

This TODO pertains to unaryNode, not zeroNode, and needs to be updated now: "We could evaluate the filter here and transform the unaryNode into an emptyNode, assuming ..."
Please pull the case for *unaryNode here and leave the TODO next to it.

---

*[pkg/sql/walk.go, line 478 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17899#-KsNjkQbgvjJtZ_RnCxC:-KsNjkQbgvjJtZ_RnCxD:b3g708a) ([raw file](https://github.com/cockroachdb/cockroach/blob/2680bef010bde42ceebf0449bbd279c035217596/pkg/sql/walk.go#L478)):*
> ```Go
> 	switch n := plan.(type) {
> 	case *unaryNode:
> 		return "nullrow"
> ```

s/nullrow/emptyrow

---

*[pkg/sql/walk.go, line 522 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17899#-KsNjizIY7QMFDU2orLf:-KsNjizJFfg7dfCj9qO1:b4avzv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2680bef010bde42ceebf0449bbd279c035217596/pkg/sql/walk.go#L522)):*
> ```Go
> 	reflect.TypeOf(&dropViewNode{}):         "drop view",
> 	reflect.TypeOf(&dropUserNode{}):         "drop user",
> 	reflect.TypeOf(&zeroNode{}):             "empty",
> ```

s/empty/norows/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17899#-:-KsNk_Ni4aXRpsbDLDEH:b-4tu5z0)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/walk.go, line 478 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17899#-KsNjkQbgvjJtZ_RnCxC:-KsNqhVAbMoAILIh8eDP:b-chclyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2680bef010bde42ceebf0449bbd279c035217596/pkg/sql/walk.go#L478)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

s/nullrow/emptyrow
</blockquote></details>

Move this to planNodeNames below.

---

*[pkg/sql/walk.go, line 522 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17899#-KsNjizIY7QMFDU2orLf:-KsNqdd_v31evTJLXoz2:b-2k4iuk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2680bef010bde42ceebf0449bbd279c035217596/pkg/sql/walk.go#L522)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

s/empty/norows/
</blockquote></details>

Also add the unaryNode in here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17899)*

**Comment by knz** [comment]
you'll probably need some `TESTFLAGS=-rewrite-results-in-testfiles` for some of these.

**Comment by knz** [comment]
:lgtm:

---

Reviewed 1 of 25 files at r1, 16 of 16 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17899#-:-KsdHqh2giulQdmjEZwz:bnfp4nl)*

**Comment by knz** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/zero.go, line 29 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17899#-Ksj4xtFHfX4wjbYlrSW:-Ksj4xtFHfX4wjbYlrSX:bgdf90u) ([raw file](https://github.com/cockroachdb/cockroach/blob/be073b4bce2f9dcdae2a2f1387b5e963a5563d28/pkg/sql/zero.go#L29)):*
> ```Go
> 	// We use planNodes as map keys, and zero-size structs are optimized to all
> 	// point to the same location in memory. As a result, unless we include some
> 	// field in this struct every zeroNode will have the same identity.
> ```

Can you briefly explain which tests would fail as a result. It seems to me that since all zeroNodes are equivalent, any properties we derive from one should be applicable to another.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17899)*

**Comment by justinj** [comment]
Review status: 32 of 33 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/filter_opt.go, line 179 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17899#-KsNk6uvIxAks0ttWo_k:-KsQ4wD1qTRFDhl94Ein:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2680bef010bde42ceebf0449bbd279c035217596/pkg/sql/filter_opt.go#L179)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This TODO pertains to unaryNode, not zeroNode, and needs to be updated now: "We could evaluate the filter here and transform the unaryNode into an emptyNode, assuming ..."
Please pull the case for *unaryNode here and leave the TODO next to it.
</blockquote></details>

Done.

---

*[pkg/sql/walk.go, line 478 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17899#-KsNjkQbgvjJtZ_RnCxC:-KsQ5Hoy0Y1CrTRppzlT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2680bef010bde42ceebf0449bbd279c035217596/pkg/sql/walk.go#L478)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Move this to planNodeNames below.
</blockquote></details>

Done.

---

*[pkg/sql/walk.go, line 522 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17899#-KsNjizIY7QMFDU2orLf:-KsQ5HJqGEsoRKwI8o76:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2680bef010bde42ceebf0449bbd279c035217596/pkg/sql/walk.go#L522)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Also add the unaryNode in here.
</blockquote></details>

Done.

---

*[pkg/sql/zero.go, line 29 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17899#-Ksj4xtFHfX4wjbYlrSW:-Ksj5tG0pkaTNveoKTeE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/be073b4bce2f9dcdae2a2f1387b5e963a5563d28/pkg/sql/zero.go#L29)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you briefly explain which tests would fail as a result. It seems to me that since all zeroNodes are equivalent, any properties we derive from one should be applicable to another.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17899)*

**Comment by knz** [comment]
See my last comment, please explain which tests were failing

**Comment by knz** [comment]
Review status: 32 of 33 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/zero.go, line 29 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17899#-Ksj4xtFHfX4wjbYlrSW:-Ksj6YG9hAvr7K8qbpeP:b-8xa5cs) ([raw file](https://github.com/cockroachdb/cockroach/blob/be073b4bce2f9dcdae2a2f1387b5e963a5563d28/pkg/sql/zero.go#L29)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done - where?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17899)*

**Comment by justinj** [comment]
Review status: 32 of 33 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/zero.go, line 29 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17899#-Ksj4xtFHfX4wjbYlrSW:-Ksj6mAieTUgy1DvNcSh:b-ar4119) ([raw file](https://github.com/cockroachdb/cockroach/blob/be073b4bce2f9dcdae2a2f1387b5e963a5563d28/pkg/sql/zero.go#L29)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Done - where?
</blockquote></details>

Below this comment - reviewable seems to be loading the previous revision for me by default, maybe it's doing the same for you? I just pushed an extra change (forgot a period D:) so maybe it will show up now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17899)*

**Comment by knz** [comment]
LGTM still.

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/zero.go, line 29 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17899#-Ksj4xtFHfX4wjbYlrSW:-KsjXj6OT1eC5ClBJbjj:b-m90kt6) ([raw file](https://github.com/cockroachdb/cockroach/blob/be073b4bce2f9dcdae2a2f1387b5e963a5563d28/pkg/sql/zero.go#L29)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Below this comment - reviewable seems to be loading the previous revision for me by default, maybe it's doing the same for you? I just pushed an extra change (forgot a period D:) so maybe it will show up now.
</blockquote></details>

Oh right, now I understand. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17899#-:-KsjXmFhtDQMq4aNRRfH:b-1n5b1v)*

**Pull request merged**
