### PR TITLE
sql: fix panic with JSON array ops and nulls

### LINKED ISSUE #28811: sql: panic in json builtins that take arrays
They need to check for null array elements, but they assume they're all DStrings.

```
select '{}'::jsonb ?| array['foo', 'bar',null]; 
```

### PR DESCRIPTION
**Pull request by justinj**
Fixes #28811.

Release note (bug fix): Fix a panic with JSON values and operations that
use arrays.

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
:lgtm: but I think this is also a problem for other ops. See getJsonPath

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28830#-:-LKMxXBV4yFfZsHo9Ubs:bi5rvu3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by knz** [comment]
this will also want a backport

**Comment by justinj** [comment]
ptal 😭

**Review by jordanlewis — APPROVED** [review]
Thank you sir 🙌

**Comment by justinj** [comment]
ty

bors r+

**Comment by justinj** [comment]
bors seems to have not picked this up, trying again

bors r+

**Pull request merged**
