### PR TITLE
ts: change timeseries floating point data to fixed point

### LINKED ISSUE #5518: storage: Separate out consistency checks over floating point data
We run periodic consistency checks over all the replicated data. Timeseries data which is cockroach internal, is replicated consistently, but merged independently often outside of raft on each replica. While the consistency checker forces a merge on each replica at a snapshot, thereby making it consistent before computing a checksum on the data, the data itself contains floating points, with the merge operator running floating point math like adding up all the timeseries values. We'd like to continue running consistency checks on this data so we can catch consistency problems on homogenous clusters, while accepting consistency differences on heterogenous one.

Options:
1. Separate out the checksum over timeseries data so that it doesn't interfere with the range checksum (preferred).
2. Convert the floating point values into integers and run integer math on them. Not recommended because we also really don't care about this data being that accurate.

### PR DESCRIPTION
**Pull request by vivekmenezes**
This is to allow the timeseries data to be represented as an int64,
which we are confident has a consistent representation and addition
operation.

The requirements for consistent timeseries data are:
1. a data point A has a single representation.
2. A + B has a predictable value no matter where it is computed.

A scale of 3 was picked for the fixed point representation.

closes #5518

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5560)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Shouldn't `TimeSeriesDatapoint.Value` be part of the change as well?

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5560#-:-KDfHL77GeNiEmlikZc9:743419885)*

**Comment by vivekmenezes** [comment]
It gets converted to InternalTimeSeriesSample before being Merged into the
KV store. It's a value local to a node and doesn't affect consistency.

**Comment by mrtracy** [comment]
LGTM. I did have a few suggestions to increase the clarity of the comments.

---

Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[roachpb/internal.go, line 21 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5560#-KDfc5Q_e4_j_IholtYz:-KDfc5Q_e4_j_IholtZ-:-784873716) ([raw file](https://github.com/cockroachdb/cockroach/blob/fce99cbc2556f4ac0d6e221d7c04b346d2fb4440/roachpb/internal.go#L21)):*
This scale is used for the max, min and average, not just the sum.  It would be better named something like `timeSeriesFixedPointScale`.  Additionally, I think the scale factor should be expressed in comments as simply "1000", rather than "3".

---

*[roachpb/internal.go, line 54 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5560#-KDfcumT6t7VgtixX-wc:-KDfcumU460PUolMUoGs:-7854787) ([raw file](https://github.com/cockroachdb/cockroach/blob/fce99cbc2556f4ac0d6e221d7c04b346d2fb4440/roachpb/internal.go#L54)):*
I would also rename this something like `TimeSeriesFixedPoint`.

---

*[roachpb/internal.proto, line 81 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5560#-KDfdBkalS1j-y2A1KPz:-KDfdBkalS1j-y2A1KQ-:386013776) ([raw file](https://github.com/cockroachdb/cockroach/blob/fce99cbc2556f4ac0d6e221d7c04b346d2fb4440/roachpb/internal.proto#L81)):*
Scale should be expressed as "1000".  Min and Max are also fixed point numbers, and their comments should also be altered.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5560#-:-KDfe68pYeG2prKy-saF:-303733309)*

**Comment by mrtracy** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5560#-:-KDffDG9ZTU5_Gq8he4c:1417088721)*

**Comment by petermattis** [comment]
I'd feel a lot better about this change if there was an actual series of floating point values and merges that demonstrated the failure. It should be possible to generate such test data: ieee-754 addition is not associative (in general). 

The downside to this change is that we're moving to fixed-point math and we've lost the ability to sample data smaller than 1/1000. As an alternative, we could avoid performing addition when merging `InternalTimeSeriesSample` by changing the representation to:

```
message InternalTimeSeriesSample {
  ...
  repeated double sum;
  ...
}
```

---

Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5560#-:-KDfszIKt-5yvDzMe8Lh:2063041077)*

**Comment by mrtracy** [comment]
There is no concern with associativity; the order of addition is now identical for all replicas, no matter how many times the merge operator is called.  Rather, this is motivated by a concern that replicas may generate different floating point values depending on the machine on which they are executed.  I am not an expert on this, but apparently floating point math is subject to reproducibility anomalies when moving between machines (or even on the same machine, if code is compiled differently).

As for your concern about being able to express values less than 1/1000 - from a practical standpoint, I can't conceive of a cockroach metric that would need four significant figures after the decimal. I also don't believe there are any serious ambitions to store non-cockroach metrics in cockroach.

**Comment by mrtracy** [comment]
That said, your solution of just storing the individual values instead of summing them is fairly compelling.  As I said, we have no current ambitions to store non-internal time series data, so the concerns over storing too much data are limited. At most, we'd expect to see two values in a single sample.  That might very well be the simplest solution here.

**Comment by petermattis** [comment]
@mrtracy How is the order of addition guaranteed identical on the replicas? RocksDB controls when `PartialMergeMulti` is called and which "merge" operations it is called on.

The whole point of IEEE 754 was to standardize floating point arithmetic across different architectures (and to get rid of some significant deficiencies in the various floating point implementations that existed before). Compilers can screw up floating point computation stability if they reorder operations, but they aren't supposed to do that without the user condoning it (see [https://gcc.gnu.org/wiki/FloatingPointMath](-fast-math)).

**Comment by mrtracy** [comment]
`PartialMergeMulti` never sums values; the sum values are only ever accumulated in a full merge.  Therefore, there will never be a sample on the "right" side of the merge that is the result of a previous accumulation.

**Comment by mrtracy** [comment]
Hmm, thinking about it, we also need to change the `std::sort` in a full merge to `std::stable_sort`.

**Comment by mrtracy** [comment]
This is no longer the direction we are going: #5905 will fix this without removing floating point (by removing the accumulation process).

**Pull request closed without merging**
