### PR TITLE
sql: add ALTER TABLE/INDEX .. UNSPLIT AT ..

### PR DESCRIPTION
**Pull request by jeffrey-xiao**
Now that manual splits add a sticky bit to the range descriptor, and
the merge queue respects this sticky bit, we can expose functionality to
manually unset this sticky bit.

If the key to unsplit is not the start of a range, then the unsplit
command will throw an error. If the range was manually split (I.E. the
sticky bit is set), then the sticky bit will be unset. Otherwise, this
command is a no-op.

Syntactically, the unsplit command is identical to the split command.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 26 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37603)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jeffrey-xiao, and @nvanbenschoten)

___
*[pkg/sql/unsplit.go, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-LfQzOwX0LBuFRmzWQCg:-LfQzOwX0LBuFRmzWQCh:buadp3y) ([raw file](https://github.com/cockroachdb/cockroach/blob/61e89cf1ac677a5abc4a9620a81da40aa172b61d/pkg/sql/unsplit.go#L115)):*
> ```Go
> 
> 	if err := params.extendedEvalCtx.ExecCfg.DB.AdminUnsplit(params.ctx, rowKey); err != nil {
> 		return false, err
> ```

Do we need to do any special error mapping here? Is it okay to just propagate the error directly? This isn't a question to which I know the answer.
___
*[pkg/sql/unsplit_test.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-LfQzikU8btL-1bYorXY:-LfQzikU8btL-1bYorXZ:b-8ubkoq) ([raw file](https://github.com/cockroachdb/cockroach/blob/61e89cf1ac677a5abc4a9620a81da40aa172b61d/pkg/sql/unsplit_test.go#L96)):*
> ```Go
> 		{
> 			in:    "ALTER TABLE d.t UNSPLIT AT VALUES (1, 'non-existent')",
> 			error: "unsplit key is not the start of a range",
> ```

This is the error case I'm worried about. I mean worst case is that it's just an XX00 SQL error but is that desirable?

**Review by ajwerner — COMMENTED** [review]
> Reviewed 1 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37603)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jeffrey-xiao and @nvanbenschoten)

**Review by nvb — COMMENTED** [review]
> Reviewed 26 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37603)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jeffrey-xiao)

___
*[pkg/internal/client/db.go, line 484 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-LfVK_c68X8mzGcjVrw4:-LfVK_c68X8mzGcjVrw5:b-b74kxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/61e89cf1ac677a5abc4a9620a81da40aa172b61d/pkg/internal/client/db.go#L484)):*
> ```Go
> // AdminUnsplit removes the sticky bit of the range specified by splitKey.
> //
> // spanKey is the start key of the range whose sticky bit should be removed.
> ```

Comment about what happens if the sticky bit doesn't exist. Also, talk about what happens if the provided key is not the start key of the range.
___
*[pkg/roachpb/api.proto, line 672 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-LfVKlwU60rcY4kL7-Sb:-LfVKlwU60rcY4kL7-Sc:b67e6p1) ([raw file](https://github.com/cockroachdb/cockroach/blob/61e89cf1ac677a5abc4a9620a81da40aa172b61d/pkg/roachpb/api.proto#L672)):*
> ```protobuf
> }
> ```

Extra line.
___
*[pkg/sql/unsplit.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-LfVLGqx0vP8utxelmIG:-LfVLGqx0vP8utxelmIH:b-crm17k) ([raw file](https://github.com/cockroachdb/cockroach/blob/61e89cf1ac677a5abc4a9620a81da40aa172b61d/pkg/sql/unsplit.go#L101)):*
> ```Go
> 
> func (n *unsplitNode) startExec(params runParams) error {
> 	return nil
> ```

We'll need to check the cluster version to see if `VersionStickyBit` is active. If not, we'll want to reject the statement.
___
*[pkg/sql/unsplit.go, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-LfVMuzV7boMr_uz_4Z5:-LfVMuzV7boMr_uz_4Z6:bm5mcu3) ([raw file](https://github.com/cockroachdb/cockroach/blob/61e89cf1ac677a5abc4a9620a81da40aa172b61d/pkg/sql/unsplit.go#L124)):*
> ```Go
> 
> func (n *unsplitNode) Values() tree.Datums {
> 	return tree.Datums{
> ```

I'm curious whether you think this is what a user will be interested in as the result of an `UNSPLIT AT` statement. Should we return the split point that we removed? The new start of the range? A boolean saying whether the split point was removed or not? I haven't thought much into the desired UX here. Having written this all up and used it in a few tests, do you have any thoughts about this?
___
*[pkg/sql/unsplit_test.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-LfVL_Yj8fHMMCrResMl:-LfVL_Yj8fHMMCrResMm:b1jcx5r) ([raw file](https://github.com/cockroachdb/cockroach/blob/61e89cf1ac677a5abc4a9620a81da40aa172b61d/pkg/sql/unsplit_test.go#L64)):*
> ```Go
> 	}
> 
> 	tests := []struct {
> ```

Nice tests!

There are a few other logic_tests that we'll want to add as well. To start, I think we'll want to add some basic tests to `alter_table`. Next, we'll want to expand on the `crdb_internal` tests that we added last time. Finally, the `ranges` test seems like an appropriate place to add some higher-level functional tests.
___
*[pkg/storage/client_merge_test.go, line 3434 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-LfVNNDx-lywcQuSbAxP:-LfVNNDyBdcKxb8L9-qf:b-jmlhee) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa1a4de3daf6d1696a5ad373a2b9faa742275a4/pkg/storage/client_merge_test.go#L3434)):*
> ```Go
> 		verifyUnmerged(t)
> 
> 		// TODO(jeffreyxiao): Use same mechanism as ALTER TABLE ... UNSPLIT AT
> ```

Very satisfying.
___
*[pkg/storage/replica_command.go, line 384 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-LfVNXR08n_dkgG7jw8h:-LfVNXR08n_dkgG7jw8i:bvfptr0) ([raw file](https://github.com/cockroachdb/cockroach/blob/61e89cf1ac677a5abc4a9620a81da40aa172b61d/pkg/storage/replica_command.go#L384)):*
> ```Go
> 
> // AdminUnsplit removes the sticky bit of the range specified by the
> // splitKey
> ```

`s/splitKey/args.Key/` right?

Also, period at the end.
___
*[pkg/storage/replica_command.go, line 385 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-LfVNed46lhvmG9YpNuw:-LfVNed46lhvmG9YpNux:b-m796lv) ([raw file](https://github.com/cockroachdb/cockroach/blob/61e89cf1ac677a5abc4a9620a81da40aa172b61d/pkg/storage/replica_command.go#L385)):*
> ```Go
> // AdminUnsplit removes the sticky bit of the range specified by the
> // splitKey
> func (r *Replica) AdminUnsplit(
> ```

For now, this is probably fine, but at some point we'll probably need a retry loop like we have for `AdminSplit`.
___
*[pkg/storage/replica_command.go, line 403 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-LfVO1CV97S6-fiw7KP5:-LfVO1CV97S6-fiw7KP6:b-iqoydn) ([raw file](https://github.com/cockroachdb/cockroach/blob/61e89cf1ac677a5abc4a9620a81da40aa172b61d/pkg/storage/replica_command.go#L403)):*
> ```Go
> 	if err := r.store.DB().Txn(ctx, func(ctx context.Context, txn *client.Txn) error {
> 		b := txn.NewBatch()
> 		desc := *r.Desc()
> ```

We already have a `desc` in scope, so no need to shadow it.
___
*[pkg/storage/replica_command.go, line 419 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-LfVNp3v8gVxSLng6uvL:-LfVNp3v8gVxSLng6uvM:b-z4s951) ([raw file](https://github.com/cockroachdb/cockroach/blob/61e89cf1ac677a5abc4a9620a81da40aa172b61d/pkg/storage/replica_command.go#L419)):*
> ```Go
> 			InternalCommitTrigger: &roachpb.InternalCommitTrigger{
> 				StickyBitTrigger: &roachpb.StickyBitTrigger{
> 					StickyBit: nil,
> ```

Leave a comment noting that this removes the sticky bit. It's always a little strange seeing a field set to nil in a constructor.

**Review by jeffrey-xiao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37603)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jeffrey-xiao, and @nvanbenschoten)

___
*[pkg/sql/unsplit.go, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-LfQzOwX0LBuFRmzWQCg:-LfVtsk16oIvg64-CNsZ:b35zl4z) ([raw file](https://github.com/cockroachdb/cockroach/blob/61e89cf1ac677a5abc4a9620a81da40aa172b61d/pkg/sql/unsplit.go#L115)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Do we need to do any special error mapping here? Is it okay to just propagate the error directly? This isn't a question to which I know the answer.
</blockquote></details>

I've now wrapped it in a `pgerror.CodeDataExceptionError`.
___
*[pkg/sql/unsplit.go, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-LfVMuzV7boMr_uz_4Z5:-LfVVw5e2az5-nhD6Hy8:baufez8) ([raw file](https://github.com/cockroachdb/cockroach/blob/61e89cf1ac677a5abc4a9620a81da40aa172b61d/pkg/sql/unsplit.go#L124)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm curious whether you think this is what a user will be interested in as the result of an `UNSPLIT AT` statement. Should we return the split point that we removed? The new start of the range? A boolean saying whether the split point was removed or not? I haven't thought much into the desired UX here. Having written this all up and used it in a few tests, do you have any thoughts about this?
</blockquote></details>

I think returning the split point we removed makes sense and it's symmetric with that we return with an `SPLIT AT` statement (even in the no-op case the unsplit/split key is returned). The new start of the range is misleading because it's not guaranteed that unsplitting the range will result in the range being merged. 
___
*[pkg/sql/unsplit_test.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-LfQzikU8btL-1bYorXY:-LfVtmCM1E6B1bUekDQ3:b35zl4z) ([raw file](https://github.com/cockroachdb/cockroach/blob/61e89cf1ac677a5abc4a9620a81da40aa172b61d/pkg/sql/unsplit_test.go#L96)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This is the error case I'm worried about. I mean worst case is that it's just an XX00 SQL error but is that desirable?
</blockquote></details>

I've now wrapped it in a `pgerror.CodeDataExceptionError`.
___
*[pkg/storage/client_merge_test.go, line 3434 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-LfVNNDx-lywcQuSbAxP:-LfVW8oPAxS_oIc_jmwo:b32vhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa1a4de3daf6d1696a5ad373a2b9faa742275a4/pkg/storage/client_merge_test.go#L3434)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Very satisfying.
</blockquote></details>

:)

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37603)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @jeffrey-xiao)

___
*[pkg/internal/client/db.go, line 486 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-LfW27Jz7Jun95Iazjf0:-LfW27Jz7Jun95Iazjf1:bulx3hz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c4e9cd52f5d2a8d4c217592f7ce683d295b84c1/pkg/internal/client/db.go#L486)):*
> ```Go
> // splitKey is the start key of the range whose sticky bit should be removed.
> //
> // If spanKey is not the start key of a range, then this method will throw an
> ```

"If splitKey"
___
*[pkg/sql/unsplit.go, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-LfVMuzV7boMr_uz_4Z5:-LfW3jCv2vobyb8Joips:b5i55g7) ([raw file](https://github.com/cockroachdb/cockroach/blob/61e89cf1ac677a5abc4a9620a81da40aa172b61d/pkg/sql/unsplit.go#L124)):*
<details><summary><i>Previously, jeffrey-xiao (Jeffrey Xiao) wrote…</i></summary><blockquote>

I think returning the split point we removed makes sense and it's symmetric with that we return with an `SPLIT AT` statement (even in the no-op case the unsplit/split key is returned). The new start of the range is misleading because it's not guaranteed that unsplitting the range will result in the range being merged. 
</blockquote></details>

Ok, that all sounds reasonable.
___
*[pkg/storage/replica_command.go, line 392 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-LfW4-x0-BeisnqHdIOp:-LfW4-x0-BeisnqHdIOq:b-85bp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c4e9cd52f5d2a8d4c217592f7ce683d295b84c1/pkg/storage/replica_command.go#L392)):*
> ```Go
> 	desc := *r.Desc()
> 	if !bytes.Equal(desc.StartKey.AsRawKey(), args.Header().Key) {
> 		return reply, roachpb.NewError(fmt.Errorf("key is not the start of a range"))
> ```

Why did this change?
___
*[pkg/storage/replica_command.go, line 425 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-LfW44cD1KT77WwRDQGY:-LfW44cD1KT77WwRDQGZ:b-luwk1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c4e9cd52f5d2a8d4c217592f7ce683d295b84c1/pkg/storage/replica_command.go#L425)):*
> ```Go
> 		return txn.Run(ctx, b)
> 	}); err != nil {
> 		return reply, roachpb.NewError(errors.Wrapf(err, "unsplit at key %s failed", args.Key))
> ```

Does `NewErrorf` not work here?

**Review by jeffrey-xiao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37603)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jeffrey-xiao, and @nvanbenschoten)

___
*[pkg/storage/replica_command.go, line 392 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-LfW4-x0-BeisnqHdIOp:-LfZypqhD6boCOaWuWS4:bol5jkv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c4e9cd52f5d2a8d4c217592f7ce683d295b84c1/pkg/storage/replica_command.go#L392)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why did this change?
</blockquote></details>

Originally, I wanted it not to print the file and line number, but since that's fine, I've changed it back.
___
*[pkg/storage/replica_command.go, line 425 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-LfW44cD1KT77WwRDQGY:-LfZz9CpBDmH-MxqX2Cj:bydhks4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c4e9cd52f5d2a8d4c217592f7ce683d295b84c1/pkg/storage/replica_command.go#L425)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does `NewErrorf` not work here?
</blockquote></details>

I'm wrapping another error and it doesn't seem like `roachpb` has a `Wrapf`.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-:-Lf_0OpSEzkqZ52-QUoX:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jeffrey-xiao and @nvanbenschoten)

___
*[pkg/storage/replica_command.go, line 425 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-LfW44cD1KT77WwRDQGY:-Lf_01T84oA_Pz72L8Q9:b77nvgi) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c4e9cd52f5d2a8d4c217592f7ce683d295b84c1/pkg/storage/replica_command.go#L425)):*
<details><summary><i>Previously, jeffrey-xiao (Jeffrey Xiao) wrote…</i></summary><blockquote>

I'm wrapping another error and it doesn't seem like `roachpb` has a `Wrapf`.
</blockquote></details>

This roachpb.NewError is going to serialize the error to a string so the wrapping for use with Cause doesn't matter.

**Review by jeffrey-xiao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37603)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @jeffrey-xiao, and @nvanbenschoten)

___
*[pkg/storage/replica_command.go, line 425 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-LfW44cD1KT77WwRDQGY:-Lf_OaC0EQKxAKx_lIHN:b-vrdac1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c4e9cd52f5d2a8d4c217592f7ce683d295b84c1/pkg/storage/replica_command.go#L425)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This roachpb.NewError is going to serialize the error to a string so the wrapping for use with Cause doesn't matter.
</blockquote></details>

I see, I've changed it to a `NewErrorf`.

**Review by jeffrey-xiao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37603)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/sql/unsplit_test.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-LfVL_Yj8fHMMCrResMl:-Lf_pwCt7DJdqURNp3Lw:b18kj2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/61e89cf1ac677a5abc4a9620a81da40aa172b61d/pkg/sql/unsplit_test.go#L64)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Nice tests!

There are a few other logic_tests that we'll want to add as well. To start, I think we'll want to add some basic tests to `alter_table`. Next, we'll want to expand on the `crdb_internal` tests that we added last time. Finally, the `ranges` test seems like an appropriate place to add some higher-level functional tests.
</blockquote></details>

I can't add tests to `ranges` until `manual_split_time` is added to `SHOW EXPERIMENTAL_RANGES`, but I can do this in a follow-up PR.
___
*[pkg/storage/replica_command.go, line 385 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-LfVNed46lhvmG9YpNuw:-Lf_swzvEMxd6FAMkMAr:b-k4yjjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/61e89cf1ac677a5abc4a9620a81da40aa172b61d/pkg/storage/replica_command.go#L385)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

For now, this is probably fine, but at some point we'll probably need a retry loop like we have for `AdminSplit`.
</blockquote></details>

Left a TODO

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r5, 8 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37603#-:-LfaW3YF32LHS4YtbgYb:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Pull request merged**
