### PR TITLE
sql,sql/parser: Add support for AS OF SYSTEM TIME clause with SCRUB

### PR DESCRIPTION
**Pull request by lgo**
This adds the capability to specify `AS OF SYSTEM TIME <expr>` for all
SCRUB commands. Any checks that do not currently support this optional
clause will throw an error if the option is specified.

Amendments were made to the RFC to add the syntax and a brief section
about its support.

The executor function which checks statements for the AS OF SYSTEM
TIME clause, isAsOf, was refactored. Adding support for AS OF to
new statements is now simpler.

This makes `SCRUB TABLE ... WITH OPTIONS INDEX` respect the `AS OF
SYSTEM TIME` clause.

A change to the executor adds an additional case for setting the global
AS OF SYSTEM TIME when the Scrub AST node is the top-level node. This is
a requirement for running any sub-statement with AS OF SYSTEM TIME.

Each individual check needs to handle AS OF SYSTEM TIME appropriately.
As of now, only the index check supports it.

The scrub indexCheckOperation was also moved to a separate file.
The commit only includes code movement and some additional
documentation to indexCheckOperation to provide more context for the
contents of the file.

### CODE REVIEW

**Comment by lego** [comment]
I'm not very certain about what could possibly happen from using the AS OF SYSTEM TIME in queries like this, so I thought I'd give this a shot! I also don't know the best way to fully test this (both written tests, and manually). I'll come back to this and experiment locally.

**Comment by lego** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/scrub.go, line 130 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/20368#-L-EOWbDOtwsce-1gl8C:-L-EOWbDOtwsce-1gl8D:b-vm58cb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e392b06c4cf9e373fa444463e3dca84c5c564f13/pkg/sql/scrub.go#L130)):*
> ```Go
> 			"unexpected SCRUB type received, got: %v", n.n.Typ)
> 	}
> 	// TODO(joey): Check the GC threshold in relation to the AS OF SYSTEM
> ```

Is this necessary? (I don't know the semantics behind AS OF SYSTEM TIME, so left this as a consideration)

---

*[pkg/sql/scrub.go, line 270 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/20368#-L-EOa1wE6DSkF5lwZsn:-L-EOa1wE6DSkF5lwZso:b-6xyr8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/e392b06c4cf9e373fa444463e3dca84c5c564f13/pkg/sql/scrub.go#L270)):*
> ```Go
> 	}
> 
> 	// TODO(joey): Check for when the indexes are public in relation to
> ```

Again, another thing I wasn't quite sure of. As far as I know, we will get table descriptors for a specific timestamp and will find that the index does not exist and throw an error prior to this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20368)*

**Comment by knz** [comment]
Reviewed 1 of 1 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, 1 of 5 files at r6, 1 of 1 files at r7, 2 of 3 files at r9, 2 of 2 files at r10.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/scrub.go, line 130 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/20368#-L-EOWbDOtwsce-1gl8C:-L-HrsziqtgiBbz_Rm7N:bhtelc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e392b06c4cf9e373fa444463e3dca84c5c564f13/pkg/sql/scrub.go#L130)):*
<details><summary><i>Previously, lego (Joey Pereira) wrote…</i></summary><blockquote>

Is this necessary? (I don't know the semantics behind AS OF SYSTEM TIME, so left this as a consideration)
</blockquote></details>

No, you can remove this comment.

---

*[pkg/sql/scrub.go, line 270 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/20368#-L-EOa1wE6DSkF5lwZsn:-L-Hrx3dbgu_sfRU3UfM:bi38nes) ([raw file](https://github.com/cockroachdb/cockroach/blob/e392b06c4cf9e373fa444463e3dca84c5c564f13/pkg/sql/scrub.go#L270)):*
<details><summary><i>Previously, lego (Joey Pereira) wrote…</i></summary><blockquote>

Again, another thing I wasn't quite sure of. As far as I know, we will get table descriptors for a specific timestamp and will find that the index does not exist and throw an error prior to this.
</blockquote></details>

Correct, the comment is not necessary here either.

---

*[pkg/sql/scrub.go, line 658 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/20368#-L-HsEFMUSheA3gKBRvV:-L-HsEFMUSheA3gKBRvW:brpi99q) ([raw file](https://github.com/cockroachdb/cockroach/blob/e392b06c4cf9e373fa444463e3dca84c5c564f13/pkg/sql/scrub.go#L658)):*
> ```Go
> 	// If SCRUB is called with AS OF SYSTEM TIME <expr> the
> 	// checkIndexQuery will also include the as of clause.
> 	if asOf.Expr != nil {
> ```

This is not the right way to go about plumbing the timestamp. 

pass instead a `hlc.Timestamp`, which you extract in the caller from `planner.txn.OrigTimestamp()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20368)*

**Comment by lego** [comment]
Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/scrub.go, line 130 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/20368#-L-EOWbDOtwsce-1gl8C:-L-WwQDdaHIBc-PVkcUV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e392b06c4cf9e373fa444463e3dca84c5c564f13/pkg/sql/scrub.go#L130)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

No, you can remove this comment.
</blockquote></details>

Done.

---

*[pkg/sql/scrub.go, line 270 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/20368#-L-EOa1wE6DSkF5lwZsn:-L-Ww_Ue3Br3zjgQ46DQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e392b06c4cf9e373fa444463e3dca84c5c564f13/pkg/sql/scrub.go#L270)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Correct, the comment is not necessary here either.
</blockquote></details>

Done.

---

*[pkg/sql/scrub.go, line 658 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/20368#-L-HsEFMUSheA3gKBRvV:-L-X2BlNuG3gZ9drBkmN:b-cpie84) ([raw file](https://github.com/cockroachdb/cockroach/blob/e392b06c4cf9e373fa444463e3dca84c5c564f13/pkg/sql/scrub.go#L658)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This is not the right way to go about plumbing the timestamp. 

pass instead a `hlc.Timestamp`, which you extract in the caller from `planner.txn.OrigTimestamp()`.
</blockquote></details>

Done. I just realized, does every query created during the transaction even need the as of clause? will they automatically inherit the read timestamp because of the transaction's timestamp?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20368)*

**Comment by knz** [comment]
Reviewed 3 of 5 files at r12, 1 of 1 files at r13, 1 of 3 files at r15, 1 of 2 files at r16, 4 of 4 files at r17.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/scrub.go, line 658 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/20368#-L-HsEFMUSheA3gKBRvV:-L-YOv9ws00cdptOBtJe:behss5q) ([raw file](https://github.com/cockroachdb/cockroach/blob/e392b06c4cf9e373fa444463e3dca84c5c564f13/pkg/sql/scrub.go#L658)):*
<details><summary><i>Previously, lego (Joey Pereira) wrote…</i></summary><blockquote>

Done. I just realized, does every query created during the transaction even need the as of clause? will they automatically inherit the read timestamp because of the transaction's timestamp?
</blockquote></details>

We don't (currently) support AOST inside a BEGIN...COMMIT block, only on standalone statements, so your question cannot  (yet) be answered. The jury is still out on what will happen if we want to do more.

However in the mean time what we should always keep in mind is that a statement (e.g. SELECT, but that may also include SCRUB) can also be embedded in the context of a larger statement, e.g. with `[...]`. So the "current timestamp" in the surrounding context could be specified elsewhere, but must align with the one you're seeing here.

---

*[pkg/sql/scrub.go, line 213 at r17](https://reviewable.io:443/reviews/cockroachdb/cockroach/20368#-L-YOHUWJt5slHuQlHfY:-L-YOHUWJt5slHuQlHfZ:b-v4nypa) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f1a33ed30b4df6042aafcbd9384e6dfe414e798/pkg/sql/scrub.go#L213)):*
> ```Go
> 	if n.n.AsOf.Expr != nil {
> 		ts := p.txn.OrigTimestamp()
> 		timestamp = &ts
> ```

1) This is not sufficient (yet). You also need to check they match, and reject the query if they don't. See the code a tthe start of `(p *planner) initFrom` in `render.go` and do the same here (better yet: factor it in a helper function).

2) use `val timestamp hlc.Timestamp` (not pointer) and `timestamp = hlc.MaxTimestamp` in the default case.

---

*[pkg/sql/scrub_constraint.go, line 92 at r17](https://reviewable.io:443/reviews/cockroachdb/cockroach/20368#-L-YPUhyGY-4bOcjgPMT:-L-YPUhyGY-4bOcjgPMU:b-5ciiv9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f1a33ed30b4df6042aafcbd9384e6dfe414e798/pkg/sql/scrub_constraint.go#L92)):*
> ```Go
> 	}
> 	if o.asOf != nil {
> 		sel.From.AsOf = tree.AsOfClause{Expr: &tree.NumVal{Value: constant.MakeInt64(o.asOf.WallTime)}}
> ```

Simplify -- o.asOf should always be set.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20368)*

**Comment by lego** [comment]
Review status: 0 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/scrub.go, line 658 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/20368#-L-HsEFMUSheA3gKBRvV:-L-c7qgaHKpcdWmoN9hh:bo0tyg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e392b06c4cf9e373fa444463e3dca84c5c564f13/pkg/sql/scrub.go#L658)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

We don't (currently) support AOST inside a BEGIN...COMMIT block, only on standalone statements, so your question cannot  (yet) be answered. The jury is still out on what will happen if we want to do more.

However in the mean time what we should always keep in mind is that a statement (e.g. SELECT, but that may also include SCRUB) can also be embedded in the context of a larger statement, e.g. with `[...]`. So the "current timestamp" in the surrounding context could be specified elsewhere, but must align with the one you're seeing here.
</blockquote></details>

Ah, yes. Thank you for pointing this out. I wasn't sure how the AOST machinery works before, but this really helped (also for the other comments)!

---

*[pkg/sql/scrub.go, line 213 at r17](https://reviewable.io:443/reviews/cockroachdb/cockroach/20368#-L-YOHUWJt5slHuQlHfY:-L-cYVK8f0WKXguRXpkr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f1a33ed30b4df6042aafcbd9384e6dfe414e798/pkg/sql/scrub.go#L213)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

1) This is not sufficient (yet). You also need to check they match, and reject the query if they don't. See the code a tthe start of `(p *planner) initFrom` in `render.go` and do the same here (better yet: factor it in a helper function).

2) use `val timestamp hlc.Timestamp` (not pointer) and `timestamp = hlc.MaxTimestamp` in the default case.
</blockquote></details>

Done.

---

*[pkg/sql/scrub_constraint.go, line 92 at r17](https://reviewable.io:443/reviews/cockroachdb/cockroach/20368#-L-YPUhyGY-4bOcjgPMT:-L-cYUVVzEnCEHhxNXOi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f1a33ed30b4df6042aafcbd9384e6dfe414e798/pkg/sql/scrub_constraint.go#L92)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Simplify -- o.asOf should always be set.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20368)*

**Comment by knz** [comment]
Solid, I think the code looks fine but a test is telling you you may have overlooked a corner case. I'll let you figure it out.

---

Reviewed 3 of 5 files at r19, 1 of 1 files at r20, 2 of 4 files at r22, 1 of 2 files at r23, 4 of 4 files at r24.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/scrub.go, line 237 at r24](https://reviewable.io:443/reviews/cockroachdb/cockroach/20368#-L-gNNLZT5AV13VArVj9:-L-gNNL_6CM76HLgWSMC:b-zcrte6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6cabb61096955ddd95f5b1282a463749ab25404/pkg/sql/scrub.go#L237)):*
> ```Go
> 					"cannot specify PHYSICAL option more than once")
> 			}
> 			if ts != hlc.MaxTimestamp {
> ```

maybe the new function should also return a bool, otherwise the user could specify the max ts explicitly and this error check would be none the wiser.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20368#-:-L-gNobFVZnEJBGrc0vc:bl2cmz4)*

**Comment by lego** [comment]
TYFR!

**Pull request merged**
