### PR TITLE
storage: have sequenced reads use the intent history

### PR DESCRIPTION
**Pull request by ridwanmsharif**
Reads can now use the intent history to serve reads from
values written at a lower sequence. Reads no longer read
all writes in a transaction but instead read all writes
in the transaction with a higher sequence than it. If a key
is written to multiple times within a transaction, the read
can now get the appropriate value using the intent history.

Release note: None

### CODE REVIEW

**Review by nvb — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33244)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[c-deps/libroach/mvcc.h, line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-LU7V3OJ65tSwKYtHQmH:-LU7V3OJ65tSwKYtHQmI:bnebmsw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c185bf05a7855046b83e2ee5a28b9b633c32416f/c-deps/libroach/mvcc.h#L169)):*
> ```objc
>   }
> 
>   bool getFromIntentHistory(cockroach::storage::engine::enginepb::MVCCMetadata meta, int32_t seq) {
> ```

It's strange that we pass two fields into this method but then set another field - so it's not a fully static method. I'd recommend passing no fields in here.

@petermattis might also have other comments about the C++ style.
___
*[c-deps/libroach/mvcc.h, line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-LU7UgiNA8VoWGIc0_rx:-LU7UgiO17FXoSFhE2Yk:bspk5y2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c185bf05a7855046b83e2ee5a28b9b633c32416f/c-deps/libroach/mvcc.h#L170)):*
> ```objc
> 
>   bool getFromIntentHistory(cockroach::storage::engine::enginepb::MVCCMetadata meta, int32_t seq) {
>     int32_t largestSeq = -1;
> ```

We should use a [`binary_search`](http://www.cplusplus.com/reference/algorithm/binary_search/) to accomplish this lookup.
___
*[c-deps/libroach/mvcc.h, line 290 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-LU7XWYI0W1acpB-OJSy:-LU7XWYI0W1acpB-OJSz:bu63d6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/c185bf05a7855046b83e2ee5a28b9b633c32416f/c-deps/libroach/mvcc.h#L290)):*
> ```objc
> 
>     if (txn_epoch_ == meta_.txn().epoch()) {
>       if (txn_sequence_ >= meta_.txn().sequence()) {
> ```

We're going to need to make this logic conditional on a cluster version. To do this, we'll need to go through a few steps, outlined in `cockroach_versions.go`. 

We'll then want to check whether this version is "active" somewhere in or above the mvcc layer. This is going to be a little tricky because we'll need the right dependencies in a few places. Here's my suggestion:
1. Add a new `IgnoreSeq` field to `MVCCGetOptions` and `MVCCScanOptions`
2. Comment with a `TODO(nvanbenschoten)` that the field can go away in 2.3.
3. Set this field when the new cluster version is NOT active in `cmd_get.go`, `cmd_scan.go`, and `cmd_reverse_scan.go` (I just counted and I think we'll need to set this in 5 places, but please double check). [Here's](https://github.com/cockroachdb/cockroach/blob/1c5df558971efeb4d88fb6f056bc05240cc26910/pkg/storage/batcheval/cmd_begin_transaction.go#L133) an example of how to check whether a cluster setting is active.
4. Pass this option down through C++
5. Make this condition `(ignore_seq_ || (txn_sequence_ >= meta_.txn().sequence()))`
___
*[c-deps/libroach/mvcc.h, line 291 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-LU7WxJ_0ezX9PgWefyF:-LU7WxJ_0ezX9PgWefyG:b-17pxw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c185bf05a7855046b83e2ee5a28b9b633c32416f/c-deps/libroach/mvcc.h#L291)):*
> ```objc
>     if (txn_epoch_ == meta_.txn().epoch()) {
>       if (txn_sequence_ >= meta_.txn().sequence()) {
>         // 8. We're reading our own txn's intent at a higher sequence.
> ```

"an equal or higher sequence"
___
*[c-deps/libroach/mvcc.h, line 299 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-LU7X5YsE92UH3SOO8tG:-LU7X5Yt42DKRq1HyQlt:b-v9y0z7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c185bf05a7855046b83e2ee5a28b9b633c32416f/c-deps/libroach/mvcc.h#L299)):*
> ```objc
>         // 9. We're reading our own txn's intent at a lower sequence.
>         // This means the intent we're seeing was written after the read.
>         // So we try and read a value from the intent history that is
> ```

`s/So//`
___
*[c-deps/libroach/mvcc.h, line 300 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-LU7X3uu6uIKE25TXRNc:-LU7X3uu6uIKE25TXRNd:b-8u79w1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c185bf05a7855046b83e2ee5a28b9b633c32416f/c-deps/libroach/mvcc.h#L300)):*
> ```objc
>         // This means the intent we're seeing was written after the read.
>         // So we try and read a value from the intent history that is
>         // appropriate instead. If no value is found still, read the value
> ```

`s/still//`
___
*[c-deps/libroach/mvcc.h, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-LU7WlNR6PJ3BIrzvxeE:-LU7WlNR6PJ3BIrzvxeF:byxm4ga) ([raw file](https://github.com/cockroachdb/cockroach/blob/c185bf05a7855046b83e2ee5a28b9b633c32416f/c-deps/libroach/mvcc.h#L303)):*
> ```objc
>         // as though the intent was not present.
>         bool found = getFromIntentHistory(meta_, txn_sequence_);
>         if (!found) {
> ```

nit: invert this condition so that we can separate this into a separate "steps" (e.g. step 10.)
___
*[pkg/kv/txn_interceptor_sequence_nums.go, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-LU7XQA3D2iKqQUyxPmu:-LU7XQA3D2iKqQUyxPmv:bojgdqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/c185bf05a7855046b83e2ee5a28b9b633c32416f/pkg/kv/txn_interceptor_sequence_nums.go#L69)):*
> ```Go
> 
> // populateMetaLocked is part of the txnInterceptor interface. Since reads now
> // require the sequence number, we must pass it through as well.
> ```

No need for this comment.
___
*[pkg/kv/txn_interceptor_sequence_nums.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-LU7XRfr0xXpbhuyvbh1:-LU7XRfs4xvIqgLUtdoC:bojgdqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/c185bf05a7855046b83e2ee5a28b9b633c32416f/pkg/kv/txn_interceptor_sequence_nums.go#L77)):*
> ```Go
> // augmentMetaLocked is part of the txnInterceptor interface. Since reads now
> // require the sequence number, we must ensure we don't ever underestimate
> // the sequence.
> ```

No need for this comment.

**Review by ridwanmsharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33244)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[c-deps/libroach/mvcc.h, line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-LU7V3OJ65tSwKYtHQmH:-LUBrsMTCKW06J8NmNy0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c185bf05a7855046b83e2ee5a28b9b633c32416f/c-deps/libroach/mvcc.h#L169)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's strange that we pass two fields into this method but then set another field - so it's not a fully static method. I'd recommend passing no fields in here.

@petermattis might also have other comments about the C++ style.
</blockquote></details>

Done.
___
*[c-deps/libroach/mvcc.h, line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-LU7UgiNA8VoWGIc0_rx:-LUBrsuZ2aau_I7hZvqQ:b8ov7za) ([raw file](https://github.com/cockroachdb/cockroach/blob/c185bf05a7855046b83e2ee5a28b9b633c32416f/c-deps/libroach/mvcc.h#L170)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We should use a [`binary_search`](http://www.cplusplus.com/reference/algorithm/binary_search/) to accomplish this lookup.
</blockquote></details>

Done. Using `std:lower_bound` that does almost exactly what we want (internally uses binary search).
___
*[c-deps/libroach/mvcc.h, line 290 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-LU7XWYI0W1acpB-OJSy:-LUBsfu_6Tui5IV8a3pV:bgepl0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/c185bf05a7855046b83e2ee5a28b9b633c32416f/c-deps/libroach/mvcc.h#L290)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We're going to need to make this logic conditional on a cluster version. To do this, we'll need to go through a few steps, outlined in `cockroach_versions.go`. 

We'll then want to check whether this version is "active" somewhere in or above the mvcc layer. This is going to be a little tricky because we'll need the right dependencies in a few places. Here's my suggestion:
1. Add a new `IgnoreSeq` field to `MVCCGetOptions` and `MVCCScanOptions`
2. Comment with a `TODO(nvanbenschoten)` that the field can go away in 2.3.
3. Set this field when the new cluster version is NOT active in `cmd_get.go`, `cmd_scan.go`, and `cmd_reverse_scan.go` (I just counted and I think we'll need to set this in 5 places, but please double check). [Here's](https://github.com/cockroachdb/cockroach/blob/1c5df558971efeb4d88fb6f056bc05240cc26910/pkg/storage/batcheval/cmd_begin_transaction.go#L133) an example of how to check whether a cluster setting is active.
4. Pass this option down through C++
5. Make this condition `(ignore_seq_ || (txn_sequence_ >= meta_.txn().sequence()))`
</blockquote></details>

Adding a Commit to the PR that'll add a cluster setting.
___
*[c-deps/libroach/mvcc.h, line 291 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-LU7WxJ_0ezX9PgWefyF:-LUBKRcb2PfVIwk_e3cG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c185bf05a7855046b83e2ee5a28b9b633c32416f/c-deps/libroach/mvcc.h#L291)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"an equal or higher sequence"
</blockquote></details>

Done.
___
*[c-deps/libroach/mvcc.h, line 299 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-LU7X5YsE92UH3SOO8tG:-LUBKXSRA2lnXEVYCq5V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c185bf05a7855046b83e2ee5a28b9b633c32416f/c-deps/libroach/mvcc.h#L299)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/So//`
</blockquote></details>

Done.
___
*[c-deps/libroach/mvcc.h, line 300 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-LU7X3uu6uIKE25TXRNc:-LUBKY1JBihS5wh2Fg7w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c185bf05a7855046b83e2ee5a28b9b633c32416f/c-deps/libroach/mvcc.h#L300)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/still//`
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_sequence_nums.go, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-LU7XQA3D2iKqQUyxPmu:-LUBKFPy-CI0RuzagMBN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c185bf05a7855046b83e2ee5a28b9b633c32416f/pkg/kv/txn_interceptor_sequence_nums.go#L69)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

No need for this comment.
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_sequence_nums.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-LU7XRfr0xXpbhuyvbh1:-LUBKG4l8tHzWlsu4p46:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c185bf05a7855046b83e2ee5a28b9b633c32416f/pkg/kv/txn_interceptor_sequence_nums.go#L77)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

No need for this comment.
</blockquote></details>

Done.

**Review by nvb — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, 11 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33244)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[c-deps/libroach/mvcc.h, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-LUD1_U7CRfF5KrYP0Kt:-LUD1_U8Bt5H-OsU3H55:bogp2qm) ([raw file](https://github.com/cockroachdb/cockroach/blob/776e08fd8720605c7b1cc7c2378ad44d8ac45b6c/c-deps/libroach/mvcc.h#L29)):*
> ```objc
> // compareIntents compares two sequenced intents to check if the first one
> // has a sequence equal or lower than the second.
> bool compareIntents(cockroach::storage::engine::enginepb::MVCCMetadata_SequencedIntent intent1,
> ```

make the args `const &`.
___
*[c-deps/libroach/mvcc.h, line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-LUD1HzQ7O6iR9gHn-US:-LUD1HzQ7O6iR9gHn-UT:ba20w9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/776e08fd8720605c7b1cc7c2378ad44d8ac45b6c/c-deps/libroach/mvcc.h#L31)):*
> ```objc
> bool compareIntents(cockroach::storage::engine::enginepb::MVCCMetadata_SequencedIntent intent1,
>     cockroach::storage::engine::enginepb::MVCCMetadata_SequencedIntent intent2) {
>   if (intent1.sequence() <= intent2.sequence()) {
> ```

This can be `return intent1.sequence() <= intent2.sequence();`, right?

I think it should also be strictly less, based on https://en.cppreference.com/w/cpp/algorithm/lower_bound.
___
*[c-deps/libroach/mvcc.h, line 195 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-LUD1uGQ4cMfCJvV1XPK:-LUD1uGQ4cMfCJvV1XPL:b-gftckq) ([raw file](https://github.com/cockroachdb/cockroach/blob/776e08fd8720605c7b1cc7c2378ad44d8ac45b6c/c-deps/libroach/mvcc.h#L195)):*
> ```objc
>       return false;
>     }
>     const auto intent = *(low - 1);
> ```

`std::lower_bound` returns " the first element in the range [first, last) that is not less than value". So does this logic work if we query at the same sequence as an intent? I think we might want `std::upper_bound`.
___
*[c-deps/libroach/mvcc.h, line 312 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-LUD2L3m1Gw2RtZFo3-r:-LUD2L3m1Gw2RtZFo3-s:b-lpr2h4) ([raw file](https://github.com/cockroachdb/cockroach/blob/776e08fd8720605c7b1cc7c2378ad44d8ac45b6c/c-deps/libroach/mvcc.h#L312)):*
> ```objc
>         // This means the intent we're seeing was written after the read.
>         // If there exists a value in the intent history that has a sequence
>         // number lower than the read sequence, read that value.
> ```

equal to or lower than!
___
*[c-deps/libroach/mvcc.h, line 317 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-LUD2Uln3199vVYgjNv_:-LUD2Uln3199vVYgjNva:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/776e08fd8720605c7b1cc7c2378ad44d8ac45b6c/c-deps/libroach/mvcc.h#L317)):*
> ```objc
>           return true;
>         }
>         // 10. If no value in the intent history has a sequence number lower
> ```

ditto

**Review by ridwanmsharif — COMMENTED** [review]
TFTR! Your last review was too chill @nvanbenschoten. You gave me some hope that this gets through before I leave cause there was nothing to iterate on. Give it another :eyes: to see if you find anything else, pretty excited now!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-:-LUDVhlV6c0f31dEFY3c:b-3w76r)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[c-deps/libroach/mvcc.h, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-LUD1_U7CRfF5KrYP0Kt:-LUDV5ck9xafUmp2Ds6w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/776e08fd8720605c7b1cc7c2378ad44d8ac45b6c/c-deps/libroach/mvcc.h#L29)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

make the args `const &`.
</blockquote></details>

Done.
___
*[c-deps/libroach/mvcc.h, line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-LUD1HzQ7O6iR9gHn-US:-LUDV5xQ60lOWwrPwLOx:bj2cdgo) ([raw file](https://github.com/cockroachdb/cockroach/blob/776e08fd8720605c7b1cc7c2378ad44d8ac45b6c/c-deps/libroach/mvcc.h#L31)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This can be `return intent1.sequence() <= intent2.sequence();`, right?

I think it should also be strictly less, based on https://en.cppreference.com/w/cpp/algorithm/lower_bound.
</blockquote></details>

Well that isn't really necessary because making it `<=` would allow for intents written at the same seq to be read as well. But I changed it anyway as I'm now using `upper_bound`.
___
*[c-deps/libroach/mvcc.h, line 195 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-LUD1uGQ4cMfCJvV1XPK:-LUDVKZL5AOtaW6tzDN5:b-s9bs5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/776e08fd8720605c7b1cc7c2378ad44d8ac45b6c/c-deps/libroach/mvcc.h#L195)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`std::lower_bound` returns " the first element in the range [first, last) that is not less than value". So does this logic work if we query at the same sequence as an intent? I think we might want `std::upper_bound`.
</blockquote></details>

Actually `lower_bound` used to work correctly even in that case as the compare predicate function would consider `<=` instead of just `<`. Since, `upper_bound` achieves the same thing, and is the convention we should stick with it. Done.
___
*[c-deps/libroach/mvcc.h, line 312 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-LUD2L3m1Gw2RtZFo3-r:-LUDVgO_D_UmUQoKcEgf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/776e08fd8720605c7b1cc7c2378ad44d8ac45b6c/c-deps/libroach/mvcc.h#L312)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

equal to or lower than!
</blockquote></details>

Done.
___
*[c-deps/libroach/mvcc.h, line 317 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-LUD2Uln3199vVYgjNv_:-LUDVgnLDJBi0g0r0vEw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/776e08fd8720605c7b1cc7c2378ad44d8ac45b6c/c-deps/libroach/mvcc.h#L317)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by petermattis — COMMENTED** [review]
@ridwanmsharif Have you run any of the `MVCC` benchmarks (in storage/engine) to see the impact of this change? This is performance sensitive code and extra care needs to be taken. I haven't had a chance to look at this change yet, so perhaps there is nothing of concern.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-:-LUDWmioBnz9QEDGqGP_:bmachx1)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by petermattis — COMMENTED** [review]
PS The relevant benchmarks for this change are the various `MVCCScan` benchmarks.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-:-LUDXA8B-F870zCgRqS0:b-foi557)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by ridwanmsharif — COMMENTED** [review]
Ran a few benchmarks and there was virtually no hit in the benchmarks you mention. I believe that makes sense as the extra logic for reading the right value from history would apply on when there are a few writes on the same key by the same transaction. We've not been writing history for a while and the history is expected to be pretty small as well. I defer judgement to @nvanbenschoten now. Doesn't seem like I will be able to iterate on this anymore. I trust you will review this and push this through. I'll check back on this from my flight. Great working with you all. Happy Halloween! And Happy Holidays!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33244#-:-LUGvSTE2riWf37_I6x-:b-jyvtwk)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
@ridwanmsharif sorry for letting this sit. I rebased this on master, fixed a small bug, and cleaned it up a bit. We're close to being ready to merge! The only issue is that I don't have permission to push to the pull request. Do you mind following these steps: https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/?

**Comment by ridwanmsharif** [comment]
That's great to hear! I do see that this PR already checks the "Allow edits from maintainers" option. I don't quite understand why you can't push to it. Also sent you an invitation to be a collaborator on the fork, maybe that fixes this? @nvanbenschoten

**Comment by nvanbenschoten** [comment]
I think the issue was actually that I was pushing to the wrong branch name. Pushing to the correct one fixed it! I left the first two commits alone (other than a rebase) and added two more. @ridwanmsharif you might be interested in looking them over. Otherwise, @petermattis, mind reviewing those two changes when you get a chance?

I'm gone for the next two weeks, so @petermattis feel free to merge this if everything checks out on your end. I'm also happy to merge when I return in case there's any fallout.

**Review by ridwanmsharif — COMMENTED** [review]
Changes LGTM. Thanks for fixing the bug too! I'll defer to @petermattis for the final :heavy_check_mark:

**Comment by nvanbenschoten** [comment]
Ok, now that https://github.com/cockroachdb/cockroach/issues/34025 has calmed down, I'm going to go ahead and merge this. Thanks again for all the hard work on this @ridwanmsharif!

bors r+

**Pull request merged**
