### PR TITLE
storage/engine: micro-optimize FindSplitKey

### PR DESCRIPTION
**Pull request by petermattis**
Both the Pebble and RocksDB implementations of `Iterator.FindSplitKey` were
performing an unnecessary comparison against the end key. This comparison
was unnecessary because `Iterator.FindSplitKey` is always called via
`MVCCFindSplitKey` which sets the upper bound of the iterator to the end
key.

Change `pebbleIterator.FindSplitKey` to avoid comparing against the
no-split spans and against the min-split key in common cases.

```
name                                      old time/op   new time/op    delta
MVCCFindSplitKey_Pebble/valueSize=32-16    79.5ms ± 3%    49.0ms ± 6%  -38.42%  (p=0.000 n=10+10)
MVCCFindSplitKey_RocksDB/valueSize=32-16   85.7ms ± 1%    82.3ms ± 1%   -3.91%  (p=0.000 n=9+9)

name                                      old speed     new speed      delta
MVCCFindSplitKey_Pebble/valueSize=32-16   844MB/s ± 3%  1372MB/s ± 5%  +62.51%  (p=0.000 n=10+10)
MVCCFindSplitKey_RocksDB/valueSize=32-16  783MB/s ± 1%   815MB/s ± 1%   +4.07%  (p=0.000 n=9+9)
```

Release note (performance improvement): Improved the performance of a
low-level routine involved in split operations.

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41791)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

___
*[pkg/storage/engine/pebble_iterator.go, line 300 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41791#-Lrl91Dp9dNTz6-LFngQ:-Lrl91Dp9dNTz6-LFngR:b7ipyut) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a897a671e2444feec5bd5d072fbe772e832672/pkg/storage/engine/pebble_iterator.go#L300)):*
> ```Go
> 			// consider just calling iter.Prev() at the end to get to the same
> 			// key. This isn't quite as easy as it sounds due to the mvccKey and
> 			// noSplitSpans checks.
> ```

I was just toying with this on my train ride home, but it turns out that there was much more significant optimizations nearby. The idea here also turned out to be problematic as just calling `iter.Prev()` isn't correct.

**Review by petermattis — COMMENTED** [review]
Note that we could do the same optimizations to the RocksDB version of `FindSplitKey` as I've done to the Pebble version. The Pebble version and `go test -bench -cpuprofile` made these much easier to find.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41791#-:-LrlBaX0Dp4QITyl7khN:bkqqiz0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41791)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/engine.go, line 100 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41791#-LrnWb2s4WVRHaMc_CH3:-LrnWb2s4WVRHaMc_CH4:b-yd54ii) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a897a671e2444feec5bd5d072fbe772e832672/pkg/storage/engine/engine.go#L100)):*
> ```Go
> 	// sort equal to or after minSplitKey.
> 	//
> 	// DO NOT CALL directly. Use the package-level MVCCFindSplitKey instead.
> ```

- there is another call to this method from `spanset.Iterator.FindSplitKey`which makes it hard to interpret this "DO NOT CALL" comment.
- can we document in the interface here what is required of the caller (e.g. setting the upper bound on the iterator to `end`) ?
___
*[pkg/storage/engine/pebble_iterator.go, line 244 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41791#-LrnZkjJCl87qA0q7N-V:-LrnZkjJCl87qA0q7N-W:bxh5n7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a897a671e2444feec5bd5d072fbe772e832672/pkg/storage/engine/pebble_iterator.go#L244)):*
> ```Go
> func isValidSplitKey(key roachpb.Key, noSplitSpans []roachpb.Span) bool {
> 	for i := range noSplitSpans {
> 		if noSplitSpans[i].ContainsKey(key) {
> ```

once `key` is past the end of a a span I think we can remove it from future isValidSplitKey comparisons (by returning the new spans slice from this method).
___
*[pkg/storage/engine/pebble_iterator.go, line 291 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41791#-LrnYuMCDsQHHfV0RkNG:-LrnYuMCDsQHHfV0RkNH:bxzuir5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a897a671e2444feec5bd5d072fbe772e832672/pkg/storage/engine/pebble_iterator.go#L291)):*
> ```Go
> 
> 		if diff < bestDiff &&
> 			(minSplitKey.Key == nil || !mvccKey.Less(minSplitKey)) &&
> ```

can we set `realStart` to the max of `minSplitKey` and `start` and seek to that before iterating and so avoid this comparison? That would subsume the `minSplitKey.Key = nil` optimization you've added below since that can only be used after we've found the first bestDiff.

And we could ignore the `noSplitSpans` that are before `realStart`.
___
*[pkg/storage/engine/pebble_iterator.go, line 300 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41791#-Lrl91Dp9dNTz6-LFngQ:-Lrn_jxB2GqdZXd5itO-:b3uh4j7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a897a671e2444feec5bd5d072fbe772e832672/pkg/storage/engine/pebble_iterator.go#L300)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I was just toying with this on my train ride home, but it turns out that there was much more significant optimizations nearby. The idea here also turned out to be problematic as just calling `iter.Prev()` isn't correct.
</blockquote></details>

hmm, I overlooked that when suggesting this previously.
btw, are the no split spans all in the early part of the key range and not relevant for the typical call to this function? So once we are past all of them one could use this optimization (if it was worth squeezing out more performance from this code)?

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41791)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

___
*[pkg/storage/engine/engine.go, line 100 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41791#-LrnWb2s4WVRHaMc_CH3:-Lrnbffs1LAuSeWWARoI:b-d2up6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a897a671e2444feec5bd5d072fbe772e832672/pkg/storage/engine/engine.go#L100)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

- there is another call to this method from `spanset.Iterator.FindSplitKey`which makes it hard to interpret this "DO NOT CALL" comment.
- can we document in the interface here what is required of the caller (e.g. setting the upper bound on the iterator to `end`) ?
</blockquote></details>

I've tweaked the commentary here and on some of the other semi-private methods below.
___
*[pkg/storage/engine/pebble_iterator.go, line 244 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41791#-LrnZkjJCl87qA0q7N-V:-Lrnce9G3O15wkh_W0ZH:b-64mksr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a897a671e2444feec5bd5d072fbe772e832672/pkg/storage/engine/pebble_iterator.go#L244)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

once `key` is past the end of a a span I think we can remove it from future isValidSplitKey comparisons (by returning the new spans slice from this method).
</blockquote></details>

Yes, though as you noticed the `noSplitSpans` only applies to a handful of ranges in the system. I'm hesitant to bother optimizing splits for those ranges further (and this is a small component of split cost).
___
*[pkg/storage/engine/pebble_iterator.go, line 291 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41791#-LrnYuMCDsQHHfV0RkNG:-Lrncp723l-aELWeNWOD:b-mu3af6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a897a671e2444feec5bd5d072fbe772e832672/pkg/storage/engine/pebble_iterator.go#L291)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can we set `realStart` to the max of `minSplitKey` and `start` and seek to that before iterating and so avoid this comparison? That would subsume the `minSplitKey.Key = nil` optimization you've added below since that can only be used after we've found the first bestDiff.

And we could ignore the `noSplitSpans` that are before `realStart`.
</blockquote></details>

We can't seek past the keys between `start` and `minSplitKey` as we need to accumulate `sizeSoFar`. Perhaps I'm misunderstanding your suggestion.
___
*[pkg/storage/engine/pebble_iterator.go, line 300 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41791#-Lrl91Dp9dNTz6-LFngQ:-Lrnd1Sw8yzaTTI0BJHL:bqj24ry) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a897a671e2444feec5bd5d072fbe772e832672/pkg/storage/engine/pebble_iterator.go#L300)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

hmm, I overlooked that when suggesting this previously.
btw, are the no split spans all in the early part of the key range and not relevant for the typical call to this function? So once we are past all of them one could use this optimization (if it was worth squeezing out more performance from this code)?
</blockquote></details>

Yes, the no-split spans are all in the first few ranges in the key space. However, we'd still need to handle `minSplitKey`. I suspect it is possible to do (which is why I left the TODO in place).

**Review by sumeerbhola — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 4 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41791)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/pebble_iterator.go, line 291 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41791#-LrnYuMCDsQHHfV0RkNG:-LrniBuz79ozuC6cmzVQ:b-hecs2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a897a671e2444feec5bd5d072fbe772e832672/pkg/storage/engine/pebble_iterator.go#L291)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

We can't seek past the keys between `start` and `minSplitKey` as we need to accumulate `sizeSoFar`. Perhaps I'm misunderstanding your suggestion.
</blockquote></details>

ah yes -- I overlooked the `sizeSoFar`.

**Comment by petermattis** [comment]
TFTR!

**Pull request merged**
