### PR TITLE
Revert "storage: remove useless RunTask"

### LINKED ISSUE #8551: circleci: failed tests: TestStoreRangeRebalance
The following test appears to have failed:

[#21335](https://circleci.com/gh/cockroachdb/cockroach/21335):

```
I160815 18:18:17.004645 storage/replica_trigger.go:453  unable to gossip first range; hasLease=false, err=node unavailable; try another peer
I160815 18:18:17.005990 storage/store.go:2303  store=2:2 range=1 [/Min-/Max): replica {2 2 2} too old, adding to replica GC queue
W160815 18:18:17.010740 storage/raft_transport.go:371  range=1: outgoing raft transport stream to 1 closed by the remote: rpc error: code = 2 desc = unable to accept Raft message from {NodeID:1 StoreID:1 ReplicaID:1}: no store registered for {NodeID:4 StoreID:4 ReplicaID:4}
W160815 18:18:17.011060 storage/raft_transport.go:371  range=1: outgoing raft transport stream to 1 closed by the remote: rpc error: code = 2 desc = unable to accept Raft message from {NodeID:1 StoreID:1 ReplicaID:1}: no store registered for {NodeID:3 StoreID:3 ReplicaID:3}
==================
WARNING: DATA RACE
Write at 0x00c4201e4c18 by goroutine 104:
  golang.org/x/net/trace.freeEventLog()
      /go/src/golang.org/x/net/trace/events.go:417 +0xe6
  golang.org/x/net/trace.(*eventLog).unref()
      /go/src/golang.org/x/net/trace/events.go:355 +0x6e
  golang.org/x/net/trace.(*eventLog).Finish()
      /go/src/golang.org/x/net/trace/events.go:153 +0x7b
  github.com/cockroachdb/cockroach/storage.queueLog.Finish()
      /go/src/github.com/cockroachdb/cockroach/storage/queue.go:148 +0x3e
  github.com/cockroachdb/cockroach/storage.(*baseQueue).Close()
--
  github.com/cockroachdb/cockroach/storage.(*RaftTransport).processQueue.func1.1()
      /go/src/github.com/cockroachdb/cockroach/storage/raft_transport.go:289 +0x60
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x8a

Goroutine 104 (running) created at:
  github.com/cockroachdb/cockroach/storage_test.(*multiTestContext).Stop()
      /go/src/github.com/cockroachdb/cockroach/storage/client_test.go:323 +0x94
  github.com/cockroachdb/cockroach/storage_test.TestStoreRangeRebalance()
      /go/src/github.com/cockroachdb/cockroach/storage/client_raft_test.go:1626 +0xd70
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:610 +0xc9

Goroutine 114 (running) created at:
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x73
  github.com/cockroachdb/cockroach/storage.(*RaftTransport).processQueue.func1()
      /go/src/github.com/cockroachdb/cockroach/storage/raft_transport.go:290 +0x164
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunTask()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:215 +0x10d
  github.com/cockroachdb/cockroach/storage.(*RaftTransport).processQueue()
      /go/src/github.com/cockroachdb/cockroach/storage/raft_transport.go:291 +0x2b1
  github.com/cockroachdb/cockroach/storage.(*RaftTransport).SendAsync.func1.1()
      /go/src/github.com/cockroachdb/cockroach/storage/raft_transport.go:368 +0xa7
--
I160815 18:18:52.892648 stopper.go:408  quiesceing; tasks left:
17     gossip/infostore.go:290
--- PASS: Example_rebalancing (1.42s)
PASS
Found 1 data race(s)
FAIL	github.com/cockroachdb/cockroach/storage	77.894s
=== RUN   TestBatchBasics
I160815 18:19:07.944475 storage/engine/rocksdb.go:354  opening in memory rocksdb instance
I160815 18:19:07.947360 storage/engine/rocksdb.go:402  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.03s)
=== RUN   TestBatchRepr
I160815 18:19:07.971166 storage/engine/rocksdb.go:354  opening in memory rocksdb instance
I160815 18:19:07.973124 storage/engine/rocksdb.go:402  closing in-memory rocksdb instance
--- PASS: TestBatchRepr (0.02s)
=== RUN   TestBatchGet
I160815 18:19:07.982675 storage/engine/rocksdb.go:354  opening in memory rocksdb instance

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by tamird**
Fixes #8551.

PRing to master for now, will backport to develop.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8553)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/queue.go, line 131 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8553#-KPEYfJghCr9lgE81wPK:-KPEYfJghCr9lgE81wPL:b-571fop) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6caa276f1288fa69d8cdd977c916c1f782de9ba/storage/queue.go#L131)):*
> ```Go
> type queueLog struct {
> 	mu struct {
> 		sync.Locker
> ```

Why isn't this a `syncutil.Mutex`? Do we copy the `queueLog` structure somewhere?

---

*[storage/queue.go, line 160 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8553#-KPEZ6rqxDvB06pyOjb2:-KPEZ6rqxDvB06pyOjb3:brvihvo) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6caa276f1288fa69d8cdd977c916c1f782de9ba/storage/queue.go#L160)):*
> ```Go
> 	l.mu.Lock()
> 	l.mu.finished = true
> 	l.mu.traceLog.Finish()
> ```

We're not supposed to be using queues that have been closed. I'd rather have a check in `Queue.Add` that returned quickly if the queue were closed (assuming I understand what the issue here was).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8553)*

**Comment by tamird** [comment]
Updated to revert my change from this morning with an added comment. PTAL.

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[storage/store.go, line 2305 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8553#-KPEw1G9kpybXzvjhf3r:-KPEw1G9kpybXzvjhf3s:bqshzsf) ([raw file](https://github.com/cockroachdb/cockroach/blob/42a12fbfaba4c9752e35287559c662a8d4cea7d8/storage/store.go#L2305)):*
> ```Go
> 		case *roachpb.ReplicaTooOldError:
> 			// NB: This RunTask is used to prevent a race on the queue's event log,
> 			// where it events to it are emitted at the same time that it is being
> ```

Something off with the grammar here. `where it events to it are emitted`? Might be better to have the comment indicate the requirement that `Queue.Add` is only called when the stopper has not been stopped. I wonder if `Queue.Add` should internally call `stopper.RunTask`.

---

*[storage/store.go, line 2306 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8553#-KPEw8155IMkrRq5FC4O:-KPEw8155IMkrRq5FC4P:b-qsrn3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/42a12fbfaba4c9752e35287559c662a8d4cea7d8/storage/store.go#L2306)):*
> ```Go
> 			// NB: This RunTask is used to prevent a race on the queue's event log,
> 			// where it events to it are emitted at the same time that it is being
> 			// closed by the stopper. This protection should be more focused.
> ```

Can you elaborate on this last sentence? How could the protection be more focused?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8553)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[storage/store.go, line 2305 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8553#-KPEw1G9kpybXzvjhf3r:-KPF6tUETpuE_ElxN04g:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/42a12fbfaba4c9752e35287559c662a8d4cea7d8/storage/store.go#L2305)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Something off with the grammar here. `where it events to it are emitted`? Might be better to have the comment indicate the requirement that `Queue.Add` is only called when the stopper has not been stopped. I wonder if `Queue.Add` should internally call `stopper.RunTask`.
</details>
Done.

---

*[storage/store.go, line 2306 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8553#-KPEw8155IMkrRq5FC4O:-KPF6tke4LL8OMdAcZaj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/42a12fbfaba4c9752e35287559c662a8d4cea7d8/storage/store.go#L2306)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Can you elaborate on this last sentence? How could the protection be more focused?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8553)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[storage/store.go, line 2306 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8553#-KPEw8155IMkrRq5FC4O:-KPF7j2W6-q1dZK0tyWg:bsmbe0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/42a12fbfaba4c9752e35287559c662a8d4cea7d8/storage/store.go#L2306)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Done.
</details>
Maybe. Mind filing an issue (low priority) to address this. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8553)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8553#-:-KPF7vUiovqslAVtYLD0:bnfp4nl)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[storage/store.go, line 2306 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8553#-KPEw8155IMkrRq5FC4O:-KPFABYD3XdPzlJK6mUu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/42a12fbfaba4c9752e35287559c662a8d4cea7d8/storage/store.go#L2306)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Maybe. Mind filing an issue (low priority) to address this. 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8553)*

**Pull request merged**
