### PR TITLE
release-22.1: sql: execute batch statements in an implicit transaction

### PR DESCRIPTION
**Pull request by rafiss**
Backport 3/3 commits from #76834.

/cc @cockroachdb/release

---

fixes https://github.com/cockroachdb/cockroach/issues/44803
relates to https://github.com/cockroachdb/cockroach/issues/76490

Release justification: high value bug fix to existing functionality 

### *: prepare tests for batch stmt txn change

This commit will make the next one easier to review.

### sql: execute batch statements in an implicit transaction

Release note (bug fix): Previously statements that arrived in a batch
during the simple query protocol would all execute in their own implicit
transactions. Now, we match the Postgres wire protocol, so all these
statements share the same implicit transaction. If a BEGIN is included
in a statement batch, then the existing implicit transaction is
upgraded to an explicit transaction.

### sql: add session var for old implicit txn behavior

Release note (sql change): The enable_implicit_transaction_for_batch_statements
session variable was added. It defaults to true. When it is true,
multiple statements in a single query (a.k.a. a "batch statement") will
all be run in the same implicit transaction, which matches the Postgres
wire protocol. This setting is provided for users who want to preserve
the behavior of CockroachDB versions v21.2 and earlier.

### CODE REVIEW

**Review by otan — APPROVED** [review]

**Comment by rafiss** [comment]
I viewed it as a bug fix, so didn't think that was necessary. It was discussed here: https://github.com/cockroachdb/cockroach/pull/76834#issuecomment-1058264315 I'm still in favor of keeping the fixed behavior on by default, but also happy to hear more perspectives and discuss.

> won't get to point to a bunch of release notes saying it was coming.

I didn't follow this point though. We don't put up release notes for features that are coming at some point in the future. The release notes only communicate was in the binary that is being documented. Also, now this bug fix will be documented in the `beta.1` release, so we can point people to that and give them a heads up.

If the point is about a release's worth of _testing_, then I see what you mean. But I think all the testing that we'll get on `release-22.1` during stability period before the GA release is sufficient.

I guess ultimately it comes back to the "bug fix or breaking change" debate. I view this one as a bug fix since it's something at the pgwire protocol level, and the general sentiment of our docs says that we implement the pgwire protocol as exactly as we can.

**Comment by ajwerner** [comment]
Just because it's a "bug fix" doesn't mean it is not a breaking change. We've had many a bug fix in the past that broke stuff and customers were unhappy. What's worse about this one, in my opinion, is that it's not a bug in the sense of what we documented or in the sense that it caused corruption or invalid results. It's an incompatibility and behavior difference with postgres, so we call it a bug. I think I'd frame this more as a compatibility improvement that comes with a breaking change which we should give our users notice about.

**Comment by ajwerner** [comment]
Let's get @vy-ton to explicitly sign off. This feels like exactly the sort of thing we should be more cautious about because it costs us nearly nothing to be cautious.

**Comment by rafiss** [comment]
changed to false by default in https://github.com/cockroachdb/cockroach/pull/77973

**Pull request merged**
