### PR TITLE
storage: add a Scatter command to relocate replicas and leaseholders

### PR DESCRIPTION
**Pull request by danhhz**
Scatter is best-effort; ranges that cannot be moved will include an
error detail in the response and won't fail the request.

This initial implementation just moves the existing SCATTER sql
implementation down one level so RESTORE can use it. This dramatically
improves the real-world performance of RESTORE as it now aggressively
evens out the leaseholders, which are tasked with all the Import work,
immediately after splitting out the new ranges.

@bdarnell How do you feel about this being a new command? It's definitely possible to do without (as Radu's sql impl proved), but once this starts hooking into ZoneConfigs and the Allocator and such, maybe this is cleaner? Does anything change if we want to later make it block instead of being best-effort? How would that even work?

@RaduBerinde How attached are you to SCATTER returning what it does? It might be a good idea to start with it returning nothing and add to it later if we need

### CODE REVIEW

**Comment by RaduBerinde** [comment]
> How attached are you to SCATTER returning what it does?

Not at all, I don't think returning something from the sql SCATTER is important.

> just moves the existing SCATTER sql implementation down one level

Well, two levels :) One level would be in `kv`, not in `storage`. Like I mentioned offline, it feels off to me to route this entire operation to one (basically) arbitrary replica (which then calls up into the db). But, I can see the convenience of having direct access to storage layer stuff, and the storage layer indeed already initiates moves as part of rebalancing. Someone with more expertise in kv/storage should have more useful insights here.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14942#-:-KhihD62pa_K1CatwNZP:b1fttrn)*

**Comment by RaduBerinde** [comment]
Ah, actually, SCATTER returns any error encountered for any range. That is useful, given that it's a best-effort command. But it's ok if we leave this plumbing for later.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14942#-:-Khr-2myvtvS2AK5RT9P:b-7mbc6m)*

**Comment by bdarnell** [comment]
:lgtm:

I'm OK with making this a storage command. I agree that logically all of our Admin commands belong somewhere other than storage (maybe KV, although that's not really a great fit for them either), but for now I think it's most practical to add this to the storage monolith. (and using `isRange` and the `DistSender` is certainly handy)

> Like I mentioned offline, it feels off to me to route this entire operation to one (basically) arbitrary replica (which then calls up into the db)

It doesn't assign the entire scattering to a single replica - the DistSender splits up the operation and then assigns the lease holder of each range to scatter that range. 

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/roachpb/api.proto, line 839 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14942#-Khs3vIh00iR14rgC9aL:-Khs3vIh00iR14rgC9aM:b-omye3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d570c6c8fe5f39361963f06d43d20a9cf9bfc44/pkg/roachpb/api.proto#L839)):*
> ```protobuf
> message ScatterRequest {
>   optional Span header = 1 [(gogoproto.nullable) = false, (gogoproto.embed) = true];
>   repeated Span spans = 2 [(gogoproto.nullable) = false];
> ```

Why are there `spans` separate from the span in the header? They don't seem to get set in the `Restore` usage of this method.

---

*[pkg/roachpb/api.proto, line 847 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14942#-Khs4Ta8cD8Roon3R4Il:-Khs4Ta9AMiiXvpmo9dC:b8zs48j) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d570c6c8fe5f39361963f06d43d20a9cf9bfc44/pkg/roachpb/api.proto#L847)):*
> ```protobuf
> 
>   message Range {
>     optional bytes key = 1 [(gogoproto.casttype) = "Key"];
> ```

Shouldn't this be a Span instead of a single Key? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14942#-:-Khs5vTdn6QqRn1xDbih:by42kvz)*

**Comment by RaduBerinde** [comment]
> It doesn't assign the entire scattering to a single replica - the DistSender splits up the operation and then assigns the lease holder of each range to scatter that range.

Ah, this makes a lot more sense. I had seen an earlier version of the change where it didn't do this and I didn't look carefully at the new version. BTW there is still `ScatterRequest.Spans` left over from that old version.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14942#-:-Khssnfo6lCignHZhimY:b-4euf75)*

**Comment by RaduBerinde** [comment]
:lgtm:

Cool stuff! Thanks for plumbing the per-range errors too, great!

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/split_at.go, line 318 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14942#-KhswVaEfyYr9JTefif_:-KhswVaEfyYr9JTefifa:b-mmak6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d570c6c8fe5f39361963f06d43d20a9cf9bfc44/pkg/sql/split_at.go#L318)):*
> ```Go
> 	n.lastRangeStartKey = rangeDesc.StartKey.AsRawKey()
> 
> 	if err := storage.RelocateRange(ctx, n.p.ExecCfg().DB, rangeDesc, targets); err != nil {
> ```

Really cool that we can share this code, thanks for doing that! One question though (maybe for @bdarnell), is there a problem if `sql` depends on `storage`? (I don't think it does currently)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14942#-:-KhsxDdk-OY3h_8CS_Cn:b-kxshsc)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/split_at.go, line 318 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14942#-KhswVaEfyYr9JTefif_:-Kht2CvQu5G-igCu_8hX:b-a18ox3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d570c6c8fe5f39361963f06d43d20a9cf9bfc44/pkg/sql/split_at.go#L318)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Really cool that we can share this code, thanks for doing that! One question though (maybe for @bdarnell), is there a problem if `sql` depends on `storage`? (I don't think it does currently)
</blockquote></details>

I'm OK with sql depending on storage, although it might be better to follow the logic of this change and introduce a KV command for this instead of depending on the code directly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14942)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/split_at.go, line 318 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14942#-KhswVaEfyYr9JTefif_:-Kht88holaCpgZokB255:b-4nd4q8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d570c6c8fe5f39361963f06d43d20a9cf9bfc44/pkg/sql/split_at.go#L318)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I'm OK with sql depending on storage, although it might be better to follow the logic of this change and introduce a KV command for this instead of depending on the code directly.
</blockquote></details>

Makes sense. @danhhz I can volunteer to do that in a follow-up change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14942)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/roachpb/api.proto, line 837 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14942#-KhtLCus-9cEKvKhbmN2:-KhtLCus-9cEKvKhbmN3:b906xvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d570c6c8fe5f39361963f06d43d20a9cf9bfc44/pkg/roachpb/api.proto#L837)):*
> ```protobuf
> // that cannot be moved will include an error detail in the response and won't
> // fail the request.
> message ScatterRequest {
> ```

Should this be `AdminScatterRequest` to match the other `Admin*` commands?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14942)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/roachpb/api.proto, line 837 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14942#-KhtLCus-9cEKvKhbmN2:-Khs4j0M-FxH1M5nDars:bw4irm5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d570c6c8fe5f39361963f06d43d20a9cf9bfc44/pkg/roachpb/api.proto#L837)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Should this be `AdminScatterRequest` to match the other `Admin*` commands?
</blockquote></details>

I almost made the same comment, but only about half of our current "admin" commands currently start with `Admin`. I think the whole area of "admin" commands is due for a refactoring/cleanup, but given the existing inconsistency I don't care too much about enforcing naming conventions here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14942)*

**Comment by danhhz** [comment]
Thanks for the reviews! RFAL if anyone wants to

@bdarnell, I forgot to ask this on in my comment on Friday. Are there any concerns about moving the leaseholder of a range from inside an admin command on that leaseholder? IIUC, it's not guaranteed to stay the leaseholder while executing the command, so it should be okay, but figured I'd double check.

---

Review status: 1 of 13 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/roachpb/api.proto, line 837 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14942#-KhtLCus-9cEKvKhbmN2:-KhwPAFv3HhqzDYgloJZ:b-bnd3vt) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d570c6c8fe5f39361963f06d43d20a9cf9bfc44/pkg/roachpb/api.proto#L837)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I almost made the same comment, but only about half of our current "admin" commands currently start with `Admin`. I think the whole area of "admin" commands is due for a refactoring/cleanup, but given the existing inconsistency I don't care too much about enforcing naming conventions here.
</blockquote></details>

I went ahead and did this

---

*[pkg/roachpb/api.proto, line 839 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14942#-Khs3vIh00iR14rgC9aL:-KhwPMrHPdtRl_3z9DWJ:bhcyfwl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d570c6c8fe5f39361963f06d43d20a9cf9bfc44/pkg/roachpb/api.proto#L839)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Why are there `spans` separate from the span in the header? They don't seem to get set in the `Restore` usage of this method.
</blockquote></details>

Whoops. As Radu mentions, this is from a previous version of this PR

---

*[pkg/roachpb/api.proto, line 847 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14942#-Khs4Ta8cD8Roon3R4Il:-KhwPQ53xHjGUvuUjMXB:b-4nrlns) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d570c6c8fe5f39361963f06d43d20a9cf9bfc44/pkg/roachpb/api.proto#L847)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Shouldn't this be a Span instead of a single Key? 
</blockquote></details>

Yes, that makes much more sense

---

*[pkg/sql/split_at.go, line 318 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14942#-KhswVaEfyYr9JTefif_:-KhwPVgeqGmTT1yT_Csj:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d570c6c8fe5f39361963f06d43d20a9cf9bfc44/pkg/sql/split_at.go#L318)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Makes sense. @danhhz I can volunteer to do that in a follow-up change.
</blockquote></details>

:thumbsup: 

---

*[pkg/storage/replica_command.go, line 3838 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14942#-KhwQ-CPnGpDJ_HaLkV8:-KhwQ-CPnGpDJ_HaLkV9:bfpcc8x) ([raw file](https://github.com/cockroachdb/cockroach/blob/225f782748bd13656a3a5ce99f3a5369be4a76a3/pkg/storage/replica_command.go#L3838)):*
> ```Go
> 		Ranges: []roachpb.AdminScatterResponse_Range{{
> 			Span: roachpb.Span{
> 				Key:    rangeDesc.StartKey.AsRawKey(),
> ```

Is this safe?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14942#-:-KhwQ0plwiB9KZS0cUG3:bbfr4tg)*

**Comment by bdarnell** [comment]
Yes, it's fine to transfer the lease away during an admin command. 

---

Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica_command.go, line 3838 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14942#-KhwQ-CPnGpDJ_HaLkV8:-KhxLRJSMgwnlacMdQbN:b2g8o7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/225f782748bd13656a3a5ce99f3a5369be4a76a3/pkg/storage/replica_command.go#L3838)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Is this safe?
</blockquote></details>

Yes. AsRawKey is safe to be used on the start/end keys of a RangeDescriptor (but not in most other cases).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14942#-:-KhxLdrQv15M_4b9RsKI:b-5kdm4i)*

**Pull request merged**
