### PR TITLE
release-23.1: sql: avoid tenant ID reuse

### PR DESCRIPTION
**Pull request by knz**
Backport

- 2/2 commits from #101322.
- 2/2 commits from #101928.

/cc @cockroachdb/release

Epic: CRDB-23559

---
Release justification: helps prevent data corruption and security issues in multi-tenant deployments

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
> Reviewed 98 of 98 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101845)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @mgartner, and @stevendanna)

___
*[`-- commits` line 20 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101845#-NTUVkoG9xCBerdK4aAM):*
Is it concerning that `create_tenant` could ask for `tenantID = math.MaxUint64`? IIRC if this happens, then we won't be able to create new tenants except by using `create_tenant` builtin. Perhaps we want to ensure that the chosen tenantID doesn't exceed some threshold (say `math.MaxUint32`)?
___
*[`pkg/sql/tenant_creation.go` line 629 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101845#-NTUXBIC00wICBfdJnzv:-NTUXBIC00wICBfdJnzw:b9fx7vr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ddb9c483a8580778c75e260a8d260b31122225d/pkg/sql/tenant_creation.go#L629)):*
> ```Go
> 
> 	// Full name of the sequence.
> 	tn := tree.MakeTableNameWithSchema(catconstants.SystemDatabaseName, tree.PublicSchemaName, tree.Name(catconstants.TenantIDSequenceTableName))
> ```

nit: this seems like it could have been a global singleton, no?

**Comment by knz** [comment]
ok i will make another patch with your suggestions and import it here.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101845)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @stevendanna, and @yuzefovich)

___
*[`-- commits` line 20 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101845#-NTUVkoG9xCBerdK4aAM):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Is it concerning that `create_tenant` could ask for `tenantID = math.MaxUint64`? IIRC if this happens, then we won't be able to create new tenants except by using `create_tenant` builtin. Perhaps we want to ensure that the chosen tenantID doesn't exceed some threshold (say `math.MaxUint32`)?
</blockquote></details>

Done #101928
___
*[`pkg/sql/tenant_creation.go` line 629 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101845#-NTUXBIC00wICBfdJnzv:-NTUlgVk4r2JmR5JR8DI:b1xma5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ddb9c483a8580778c75e260a8d260b31122225d/pkg/sql/tenant_creation.go#L629)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this seems like it could have been a global singleton, no?
</blockquote></details>

Done #101928

**Review by yuzefovich — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101845)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @stevendanna)

**Review by dhartunian — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101845#-:-NTUy4xH9wgtNDQq4bcs:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @stevendanna)

**Pull request merged**
