### PR TITLE
roachtest: Improve jepsen failure detection

### PR DESCRIPTION
**Pull request by bdarnell**
Stop collecting systemd logs; these are extremely verbose but don't
contain anything about the ntp problem.

Discard tar's stderr to avoid breaking the resulting tar files
(works around cockroachdb/roachprod#154)

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[pkg/cmd/roachtest/jepsen.go, line 223 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24976#-LAmZ9zz9V-0BYbftFA1:-LAmZA--7VAG8ISWkz86:b-9fxqty) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd89ff7fae7e28592e2037c4826e07b965f9f1e0/pkg/cmd/roachtest/jepsen.go#L223)):*
> ```Go
> 					// -f- sends the output to stdout, we read it and save it to a local file.
> 					// Redirect stderr to /dev/null to work around
> 					// https://github.com/cockroachdb/roachprod/issues/154
> ```

I just sent out a PR to fix this in roachprod. Not sure if that complete obviates the need for this PR or not.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24976#-:-LAmZOyhE0oIgOepVLq2:bnfp4nl)*

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/cmd/roachtest/jepsen.go, line 223 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24976#-LAmZ9zz9V-0BYbftFA1:-LAmtJMO93m8EGI_NVxq:bkwggfo) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd89ff7fae7e28592e2037c4826e07b965f9f1e0/pkg/cmd/roachtest/jepsen.go#L223)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I just sent out a PR to fix this in roachprod. Not sure if that complete obviates the need for this PR or not.
</blockquote></details>

It eliminates the need for this part. We still want to drop the journalctl step, but I'll wait for another cycle before doing that on the off chance that it's useful in conjunction with non-broken tarballs. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24976)*

**Comment by bdarnell** [comment]
Added another commit to move the jepsen controller's data directory to the data partition. We use nearly all the space on the root partition during a full run, and there's enough variance that occasionally we run out of space.

**Pull request merged**
