### PR TITLE
roachtest: properly fetch logs when a test times out

### PR DESCRIPTION
**Pull request by petermattis**
See #27816

Release note: None

### CODE REVIEW

**Review by benesch — APPROVED** [review]
:lgtm: because there's no way this makes the situation worse, but I'm not convinced we're moving this `registry.run` function in the right direction. I've mostly lost the ability to reason about it.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27817#-:-LHtXdtKEMxKb5XDxsyN:b-3j97ax)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/test.go, line 745 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27817#-LHtX7Wf4e-cDj26_EH5:-LHtX7Wf4e-cDj26_EH6:b-t7ni6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c96e29852d79cb6bd06a5e71ea7d3858ab6a5d0/pkg/cmd/roachtest/test.go#L745)):*
> ```Go
> 				if c != nil {
> 					defer func() {
> 						c.FetchLogs(ctx)
> ```

Won't this defer fire incorrectly fire after the cluster destruction?
___
*[pkg/cmd/roachtest/test.go, line 798 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27817#-LHtXVO98XTdAfOITizC:-LHtXVO98XTdAfOITizD:b-3jlu1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c96e29852d79cb6bd06a5e71ea7d3858ab6a5d0/pkg/cmd/roachtest/test.go#L798)):*
> ```Go
> 		}
> 	}()
> }
> ```

This function is approximately impossible to reason about.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27817)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/test.go, line 745 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27817#-LHtX7Wf4e-cDj26_EH5:-LHtZ1T6-ZszvPZ1o_1f:bd2x3lq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c96e29852d79cb6bd06a5e71ea7d3858ab6a5d0/pkg/cmd/roachtest/test.go#L745)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Won't this defer fire incorrectly fire after the cluster destruction?
</blockquote></details>

Yes, it will, though it will fail to do anything useful as the cluster will have been destroyed. I suppose I could have an atomic that is set to prevent it from doing anything. Do you think that is worthwhile?
___
*[pkg/cmd/roachtest/test.go, line 798 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27817#-LHtXVO98XTdAfOITizC:-LHtYtgl920dXFXAJvWw:b-2ba55g) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c96e29852d79cb6bd06a5e71ea7d3858ab6a5d0/pkg/cmd/roachtest/test.go#L798)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This function is approximately impossible to reason about.
</blockquote></details>

Yes it is. I was thinking about restructuring it while making this change, but stopped short.

**Review by benesch — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27817)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/test.go, line 745 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27817#-LHtX7Wf4e-cDj26_EH5:-LHtby-4-7Jhm4Vo7gGG:b-lw2i47) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c96e29852d79cb6bd06a5e71ea7d3858ab6a5d0/pkg/cmd/roachtest/test.go#L745)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Yes, it will, though it will fail to do anything useful as the cluster will have been destroyed. I suppose I could have an atomic that is set to prevent it from doing anything. Do you think that is worthwhile?
</blockquote></details>

Hmm. I think I'd prefer to not worry about it for now but nudge the task to restructure this function up the queue a few places.
___
*[pkg/cmd/roachtest/test.go, line 798 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27817#-LHtXVO98XTdAfOITizC:-LHtc-qe5uP2hLxrsrJW:b-ejju94) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c96e29852d79cb6bd06a5e71ea7d3858ab6a5d0/pkg/cmd/roachtest/test.go#L798)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Yes it is. I was thinking about restructuring it while making this change, but stopped short. 
</blockquote></details>

Ack. I'd be very happy to review a restructuring, but I don't think you should block this change on such a cleanup.

**Review by benesch — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27817)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by petermattis — COMMENTED** [review]
bors r=benesch

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27817#-:-LHtdc0l-1zVdeTZyJ2R:bevcpba)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/test.go, line 798 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27817#-LHtXVO98XTdAfOITizC:-LHtdZuwBmRLuYUTZHQK:b-ma0mc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c96e29852d79cb6bd06a5e71ea7d3858ab6a5d0/pkg/cmd/roachtest/test.go#L798)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Ack. I'd be very happy to review a restructuring, but I don't think you should block this change on such a cleanup. 
</blockquote></details>

I'll see about doing it soon.

**Pull request merged**
