### PR TITLE
sql/parser: streamline KVOptions syntax, support placeholders

### PR DESCRIPTION
**Pull request by dt**
This changes the canonical KVOption syntax (currently used in sqlccl),
from
```
WITH OPTIONS ('foo'='a', 'bar'='1', 'bar')
```
to
```
WITH foo = 'a', bar = $1, baz
```

Also adds placeholder support and a helper on planner to type all non-empty
values as strings and return a simple string/string map.

While I'm here, make Import walkable.

Thanks for the suggestion @knz!

### CODE REVIEW

**Comment by danhhz** [comment]
We definitely mention this syntax on our restore docs, so there's some work to do there once this lands

**Comment by dt** [comment]
@danhhz yeah, though note the old syntax is still accepted in 1.1, so it isn't quite as time-critical to remove it from docs.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17528#-:-Kr2ubCCmxZ7wDvQ6PlX:bes8dxz)*

**Comment by mjibson** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/csv.go, line 610 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17528#-Kr4dzcfIZWt48ZeJfR3:-Kr4dzcfIZWt48ZeJfR4:bxnwoqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddebf12a7ce7f2e82809e098dd9f01b3e9b10731/pkg/ccl/sqlccl/csv.go#L610)):*
> ```Go
> 		return func() (string, bool, error) { return "", false, nil }, nil
> 	}
> 	strFn, err := p.TypeAsString(expr, "IMPORT")
> ```

"IMPORT" could be an argument to this func which would make it reusable. Also not opposed to leaving it as is until needed again, but it feels like this belongs in another package, like maybe parser and it's a method on KVOptions.

---

*[pkg/ccl/sqlccl/csv_test.go, line 392 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17528#-Kr4f70D73yQZrscIWNz:-Kr4f70D73yQZrscIWO-:b-25byfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddebf12a7ce7f2e82809e098dd9f01b3e9b10731/pkg/ccl/sqlccl/csv_test.go#L392)):*
> ```Go
> 		{
> 			"schema-in-file",
> 			`IMPORT TABLE t CREATE USING $1 CSV DATA (%s) WITH temp = $2`,
> ```

I think we need to add a test to verify an error if temp isn't specified.

---

*[pkg/ccl/sqlccl/restore.go, line 154 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17528#-Kr4fg3WBSwNcQqU2zNq:-Kr4fg3WBSwNcQqU2zNr:b-ahnswh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddebf12a7ce7f2e82809e098dd9f01b3e9b10731/pkg/ccl/sqlccl/restore.go#L154)):*
> ```Go
> 				var targetDB string
> 				if override, ok := opts.Get(restoreOptIntoDB); ok {
> 					fn, err := p.TypeAsString(override, "RESTORE")
> ```

Doesn't RESTORE also need to do whatever to extract a possible placeholder out of its options?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17528)*

**Comment by dt** [comment]
Review status: 0 of 11 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/sqlccl/csv.go, line 610 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17528#-Kr4dzcfIZWt48ZeJfR3:-Kr5wSUSEYOKzjk1-KE-:b3jbrv1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddebf12a7ce7f2e82809e098dd9f01b3e9b10731/pkg/ccl/sqlccl/csv.go#L610)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

"IMPORT" could be an argument to this func which would make it reusable. Also not opposed to leaving it as is until needed again, but it feels like this belongs in another package, like maybe parser and it's a method on KVOptions.
</blockquote></details>

Can't go on kvopts, or in parser, since this uses planner. I hesitated to add to planner at first, but I went ahead and added a helper that just does the whole map and that cleaned this up a bit.

---

*[pkg/ccl/sqlccl/csv_test.go, line 392 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17528#-Kr4f70D73yQZrscIWNz:-Kr5zDfLE5f7HCDwYpFy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddebf12a7ce7f2e82809e098dd9f01b3e9b10731/pkg/ccl/sqlccl/csv_test.go#L392)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I think we need to add a test to verify an error if temp isn't specified.
</blockquote></details>

Done.

---

*[pkg/ccl/sqlccl/restore.go, line 154 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17528#-Kr4fg3WBSwNcQqU2zNq:-Kr6OOPs__noOygLN2_z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddebf12a7ce7f2e82809e098dd9f01b3e9b10731/pkg/ccl/sqlccl/restore.go#L154)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Doesn't RESTORE also need to do whatever to extract a possible placeholder out of its options?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17528)*

**Comment by knz** [comment]
I recommend that Import (and Backup/Restore too actually) also extend the `WalkableStmt` interface so that placeholder typing becomes correct / symmetrical with other statements. Right now you're merely lucky if your placeholders work properly.

rest of the code LGTM.

---

Reviewed 4 of 9 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17528#-:-Kr6PL-jJDKaEaGsBBAh:bpeaql6)*

**Comment by knz** [comment]
Also please extend the commit message and the PR descriptor to announce the general-purpose `parser.KVOptions` struct and the typing method in package `sql` that returns a `map[string]string` I can see that being useful for other people.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17528#-:-Kr6Q1A1QpiPMST0moLF:b-c6xawj)*

**Comment by dt** [comment]
Done (punting RESTORE and BACKUP since there are enough unrelated changes in here already)

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 10 of 12 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/csv_test.go, line 436 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17528#-Kr79KWBBgoA8Pi7TvdL:-Kr79KWBBgoA8Pi7TvdM:bgtwco8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9adeaff9b175bba68e008270603c1be38ec9432d/pkg/ccl/sqlccl/csv_test.go#L436)):*
> ```Go
> 					t.Fatal(err)
> 				}
> 			} else {
> ```

No need for the else since t.Fatal is used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17528#-:-Kr7A7AY6QJQ15NJbF_u:bnfp4nl)*

**Comment by dt** [comment]
Review status: 10 of 12 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/csv_test.go, line 436 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17528#-Kr79KWBBgoA8Pi7TvdL:-Kr7AFp0zqb2cvrml0Tg:b-9j5rzk) ([raw file](https://github.com/cockroachdb/cockroach/blob/9adeaff9b175bba68e008270603c1be38ec9432d/pkg/ccl/sqlccl/csv_test.go#L436)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

No need for the else since t.Fatal is used.
</blockquote></details>

still need the else to avoid looking at result in the expected error case you asked for.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17528)*

**Comment by mjibson** [comment]
Review status: 10 of 12 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/csv_test.go, line 436 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17528#-Kr79KWBBgoA8Pi7TvdL:-Kr7BNqMFkqbLVxvcE6F:big0m23) ([raw file](https://github.com/cockroachdb/cockroach/blob/9adeaff9b175bba68e008270603c1be38ec9432d/pkg/ccl/sqlccl/csv_test.go#L436)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

still need the else to avoid looking at result in the expected error case you asked for.
</blockquote></details>

Ah, yes. I got confused by the diff formatting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17528)*

**Pull request merged**
