### PR TITLE
cli: hide decommissioned dead nodes from `node (status|ls)`

### LINKED ISSUE #18169: `cockroach node status` and `node ls` list decommissioned nodes
After decommissioning a node, the Admin UI correctly show the node as decommissioned:

screen shot 2017-09-01 at 4 35 33 pm

However, the `cockroach node status` and `cockroach node ls` commands continue to list the decommissioned node:

```
~/src/github.com/cockroachdb/docs$ cockroach node status --insecure --host=165.227.60.76
+----+-----------------------+---------------------+---------------------+---------------------+
| id |        address        |        build        |     updated_at      |     started_at      |
+----+-----------------------+---------------------+---------------------+---------------------+
|  1 | 165.227.60.76:26257   | v1.1-alpha.20170817 | 2017-09-01 16:34:35 | 2017-08-30 16:17:05 |
|  2 | 192.241.239.201:26257 | v1.1-alpha.20170817 | 2017-09-01 16:34:40 | 2017-08-30 16:18:20 |
|  3 | 67.207.91.36:26257    | v1.1-alpha.20170817 | 2017-09-01 16:34:41 | 2017-08-30 16:19:20 |
|  4 | 138.197.12.74:26257   | v1.1-alpha.20170817 | 2017-09-01 15:55:23 | 2017-08-30 16:20:13 |
+----+-----------------------+---------------------+---------------------+---------------------+
(4 rows)
~/src/github.com/cockroachdb/docs$ cockroach node ls --insecure --host=165.227.60.76
+----+
| id |
+----+
|  1 |
|  2 |
|  3 |
|  4 |
+----+
(4 rows)
```

### PR DESCRIPTION
**Pull request by tbg**
cc @jseldess

Fixes #18169.

### CODE REVIEW

**Comment by a-robinson** [comment]
:lgtm: 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/acceptance/decommission_test.go, line 81 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18270#-KtS3HD-JxhKrqlSOukE:-KtS3HD-JxhKrqlSOukF:b-ifgfv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3762da976a6a365ef5a80e2502e662f37b048b39/pkg/acceptance/decommission_test.go#L81)):*
> ```Go
> 		return errors.Errorf("csv has %d rows, but expected at least %d", lr, lm)
> 	}
> 	records = records[lr-lm:]
> ```

Maybe it's just me, but this confused me a bit. It looks correct as is, but `records[:lm]` would have been easier to parse.

---

*[pkg/acceptance/decommission_test.go, line 383 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18270#-KtS7-ixcRE5HVhY97Xf:-KtS7-ixcRE5HVhY97Xg:b9h6uj0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3762da976a6a365ef5a80e2502e662f37b048b39/pkg/acceptance/decommission_test.go#L383)):*
> ```Go
> 	}
> 
> 	// Check that (at least after a bit) the node disappears from `node ls`
> ```

Why aren't these retry loops just using `testutils.SucceedsSoon`?

---

*[pkg/cli/node.go, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18270#-KtS-66Bt3RDH-VsbdwW:-KtS-66Bt3RDH-VsbdwX:b-s81gs0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3762da976a6a365ef5a80e2502e662f37b048b39/pkg/cli/node.go#L50)):*
> ```Go
> 	Long: `
> Display the node IDs for all active (that is, running and not decommissioned) members of the cluster.
> To retrieve the IDs for inactive members, see the 'node status --decommission'.
> ```

s/the//

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18270#-:-KtS77rOYkRmr3w2ETHr:bg7igkv)*

**Comment by tschottdorf** [comment]
TFTR!

---

Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/acceptance/decommission_test.go, line 81 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18270#-KtS3HD-JxhKrqlSOukE:-KtSJezZbTwfkJuNDf9D:bczka7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/3762da976a6a365ef5a80e2502e662f37b048b39/pkg/acceptance/decommission_test.go#L81)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Maybe it's just me, but this confused me a bit. It looks correct as is, but `records[:lm]` would have been easier to parse.
</blockquote></details>

But that's not the same, I want the last `lm` records, not the first `lm` records. Added a comment to clarify.

---

*[pkg/acceptance/decommission_test.go, line 383 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18270#-KtS7-ixcRE5HVhY97Xf:-KtSKi6FCoYlv-Kpp_DJ:b-v9cpi) ([raw file](https://github.com/cockroachdb/cockroach/blob/3762da976a6a365ef5a80e2502e662f37b048b39/pkg/acceptance/decommission_test.go#L383)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Why aren't these retry loops just using `testutils.SucceedsSoon`?
</blockquote></details>

`SucceedsSoon` has (last time I checked) a 45s time limit which is reasonable for most things which are expected to happen "quickly", but since we're on the scale of node liveness timeouts (~10s) I thought it was better to explicitly time out than to have a failure and have to wonder: "would this have finished on its own?"

---

*[pkg/cli/node.go, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18270#-KtS-66Bt3RDH-VsbdwW:-KtSKBJPYkYQs2zIIkfT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3762da976a6a365ef5a80e2502e662f37b048b39/pkg/cli/node.go#L50)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

s/the//
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18270#-:-KtSLMW0y_0H6MF3Ntc9:b-814g8k)*

**Comment by a-robinson** [comment]
:lgtm:

---

Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18270#-:-KtSS-bS0s560YiIoqpo:bnfp4nl)*

**Comment by jseldess** [comment]
*[pkg/cli/cliflags/flags.go, line 535 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18270#-KtSSkCOLf_QXwehLcxH:-KtSSkCOLf_QXwehLcxI:b13w5s9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e62dafeb2e3f4b7c4d6f80f49d0b5cb1aa1ab184/pkg/cli/cliflags/flags.go#L535)):*
> ```Go
> 	NodeAll = FlagInfo{
> 		Name: "all", Description: `Show all node details.
> When no node ID is specified, also lists old decommissioned nodes.`,
> ```

Here and for `decommission`, what exactly do we mean by "old decommissioned nodes"? Does that mean "all nodes that have been decommissioned in the history of the cluster" or something like that? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18270)*

**Comment by jseldess** [comment]
Thanks, @tschottdorf. Just one question about a comment that seems a bit vague. Otherwise, LGTM!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18270#-:-KtST3iyU91jSmDYBjFn:b45kt5a)*

**Comment by tschottdorf** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/cli/cliflags/flags.go, line 535 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18270#-KtSSkCOLf_QXwehLcxH:-KtSV8f7U17mFXW-ZV6I:bkkdgh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e62dafeb2e3f4b7c4d6f80f49d0b5cb1aa1ab184/pkg/cli/cliflags/flags.go#L535)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

Here and for `decommission`, what exactly do we mean by "old decommissioned nodes"? Does that mean "all nodes that have been decommissioned in the history of the cluster" or something like that? 
</blockquote></details>

It means "decommissioned and not live". I've changed the wording as you suggested.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18270)*

**Pull request merged**
