### PR TITLE
sql: Add support for composite key MATCH FULL

### PR DESCRIPTION
**Pull request by BramGruneir**
And MATCH SIMPLE as well.

This adds both the grammar and the ability to declare composite foreign
key references as MATCH FULL, as opposed to our current default of MATCH
SIMPLE.

More details in the release note.

Part of #20305.

Release note (sql change): Add support for matching composite foreign keys
using the MATCH FULL method.

Cockroach now supports specifying the matching method for composite keys as
either MATCH SIMPLE or MATCH FULL. MATCH SIMPLE remains as the default. A
composite key is one that includes more than one column.

MATCH FULL differs from MATCH SIMPLE by not allowing the mixing of NULL and
NON-NULL values. Only all NULL values will not be used to validate a foreign
key constraint check or cascading action.

MATCH PARTIAL is still not supported.

For more details see: https://github.com/cockroachdb/cockroach/issues/20305 or
https://www.postgresql.org/docs/11/sql-createtable.html.

### CODE REVIEW

**Comment by BramGruneir** [comment]
cc @rmloveland 
Here's the other half of the composite key matching update.

**Review by andy-kimball — COMMENTED** [review]
Optimizer-related changes :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-:-LTPS2f73vtaFzKVdykl:bkk2dwb)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by bobvawter — APPROVED** [review]
Generally LGTM, just a couple of questions about error presentation to the user and treating a two-value enum as if it were a boolean.

> Reviewed 20 of 20 files at r1, 6 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-:-LTT7afjBY2Ex4lPF3-X:bg6c7u2)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/logictest/testdata/logic_test/cascade, line 3632 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTT4SNN7yO20yhyB8SA:-LTT4SNN7yO20yhyB8SB:bppbtnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/48ffbe8917d3a57580efb6afc7b821501761203e/pkg/sql/logictest/testdata/logic_test/cascade#L3632)):*
> ```
> 
> # C's MATCH FULL should reject this.
> statement error MATCH FULL does not allow mixing of null and nonnull values
> ```

How would the user know that this error actually came from a constraint on table c?  Can the name of the failed fk constraint get plumbed back into these error messages?
___
*[pkg/sql/opt/catalog.go, line 356 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTT7PsnDk0RIRIyiXAb:-LTT7PsnDk0RIRIyiXAc:b-bm8goo) ([raw file](https://github.com/cockroachdb/cockroach/blob/fce3da37542996b995e4c5071e7f1944b46d6f92/pkg/sql/opt/catalog.go#L356)):*
> ```Go
> 	PrefixLen int32
> 
> 	// Match contains the method used for compareing composite foreign keys.
> ```

No `e` in comparing.
___
*[pkg/sql/row/cascader.go, line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTT5gtv8ceIlFbwStYC:-LTT5gtv8ceIlFbwStYD:b-7rfnb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/48ffbe8917d3a57580efb6afc7b821501761203e/pkg/sql/row/cascader.go#L211)):*
> ```Go
> 			}
> 		}
> 	} else {
> ```

Is it worth making this a switch or an else-if and erroring out if an unexpected match is encountered?  I'm thinking of the case where we do implement `match partial` for some reason.
___
*[pkg/sql/row/fk.go, line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTT6awSDbBQ38Eh8aXt:-LTT6awSDbBQ38Eh8aXu:b-89t8qp) ([raw file](https://github.com/cockroachdb/cockroach/blob/48ffbe8917d3a57580efb6afc7b821501761203e/pkg/sql/row/fk.go#L474)):*
> ```Go
> 		// See https://github.com/cockroachdb/cockroach/issues/20305 or
> 		// https://www.postgresql.org/docs/11/sql-createtable.html.
> 		switch fk.ref.Match {
> ```

`default:` that returns an error since it's an enum type?

**Review by knz — COMMENTED** [review]
Thanks for this. Correctness looks OK. I mostly have minor/cosmetic comments, plus one smallish comment about code structure (avoiding a conditional for performance). See below. 

> Reviewed 12 of 20 files at r1, 7 of 7 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-:-LTU8kh09UJGeHwk1zu_:b-suf2xx)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 224 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTU7kCEC5SdeK4hgnEs:-LTU7kCEC5SdeK4hgnEt:bqdhb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac4e80f1957c04df207febd012b4e5bbaabbf49/pkg/sql/opt/optbuilder/mutation_builder.go#L224)):*
> ```Go
> 			// Do nothing.
> 		case 1:
> 			panic(builderError{errors.Errorf(
> ```

you can stick a pgerror inside a builderError, with a suitable pg error code
___
*[pkg/sql/parser/sql.y, line 4216 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTU83E5E9K5KJGTiEAn:-LTU83E5E9K5KJGTiEAo:b-3r0lce) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac4e80f1957c04df207febd012b4e5bbaabbf49/pkg/sql/parser/sql.y#L4216)):*
> ```Yacc
>       // since both MATCH SIMPLE and MATCH FULL act the exact same manner on a
>       // single column key. But postgres does allow you to specify it. So we
>       // won't error here, but the value is just tossed out.
> ```

We discussed this before: is it wise to "toss it out"? Remember clients care about what shows up in introspection via pg_catalog/information_schema.
If pg lets these things remain through introspection, we should probably do the same.
___
*[pkg/sql/row/cascader.go, line 205 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTU8HWACcbi0cqC7EYV:-LTU8HWACcbi0cqC7EYW:b-gcss0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac4e80f1957c04df207febd012b4e5bbaabbf49/pkg/sql/row/cascader.go#L205)):*
> ```Go
> 	// https://www.postgresql.org/docs/11/sql-createtable.html for details on the
> 	// different composite foreign key matching methods.
> 	if match == sqlbase.ForeignKeyReference_SIMPLE {
> ```

Another thought complementary to bob's comments:

perhaps the two blocks of logic (here and below) can be placed in separate functions, and then store a function pointer in the cascader to either function during planning. This way we don't have to run through this conditional on every row.
___
*[pkg/sql/row/fk.go, line 475 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTU8_cP-Aq1P8ICapE0:-LTU8_cP-Aq1P8ICapE1:b-ddtwgy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac4e80f1957c04df207febd012b4e5bbaabbf49/pkg/sql/row/fk.go#L475)):*
> ```Go
> 		// https://www.postgresql.org/docs/11/sql-createtable.html for details on the
> 		// different composite foreign key matching methods.
> 		switch fk.ref.Match {
> ```

ditto splitting into functions with fn ptr
___
*[pkg/sql/row/fk.go, line 721 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTU8dPwExcOMBiP7Ixf:-LTU8dPwExcOMBiP7Ixg:b667als) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac4e80f1957c04df207febd012b4e5bbaabbf49/pkg/sql/row/fk.go#L721)):*
> ```Go
> 	// See https://github.com/cockroachdb/cockroach/issues/20305 or
> 	// https://www.postgresql.org/docs/11/sql-createtable.html for details on the
> 	// different composite foreign key matching methods.
> ```

ditto fns

**Review by BramGruneir — COMMENTED** [review]
TFTR!

So I looked into what PG does with `\d` and it looks like it only displays MATCH FULL if it is present.  MATCH SIMPLE is just assumed.  I've adjusted the outputs to all only show MATCH FULL.

As for the avoiding a conditional, unless you're dealing with more than 2 choices, you don't get any performance gain and the code is harder to read.  So I've changed them all to switches with a default that panics.

I think this is ready to merge, but PTAL.

Also, there will need to be a follow up PR that includes pg_catalog table updates.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-:-LTTVy8d1EFjnefKJs-S:bhjs3ig)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/logictest/testdata/logic_test/cascade, line 3632 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTT4SNN7yO20yhyB8SA:-LTTRQQeCojR5wDSoMJC:brcujnc) ([raw file](https://github.com/cockroachdb/cockroach/blob/48ffbe8917d3a57580efb6afc7b821501761203e/pkg/sql/logictest/testdata/logic_test/cascade#L3632)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

How would the user know that this error actually came from a constraint on table c?  Can the name of the failed fk constraint get plumbed back into these error messages?
</blockquote></details>

I agree.  We need to add more here, I left a todo in the code and will add it as a follow up PR.  It requires a significant amount of plumbing changes to the cascader and I didn't want to put too much in this PR.
___
*[pkg/sql/opt/catalog.go, line 356 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTT7PsnDk0RIRIyiXAb:-LTTRfYw9MxgQcZWKCw0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fce3da37542996b995e4c5071e7f1944b46d6f92/pkg/sql/opt/catalog.go#L356)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

No `e` in comparing.
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 224 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTU7kCEC5SdeK4hgnEs:-LTYwlMAElCMH5JSxXkG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac4e80f1957c04df207febd012b4e5bbaabbf49/pkg/sql/opt/optbuilder/mutation_builder.go#L224)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

you can stick a pgerror inside a builderError, with a suitable pg error code
</blockquote></details>

Done.
___
*[pkg/sql/parser/sql.y, line 4216 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTU83E5E9K5KJGTiEAn:-LTYwlv5Dl-lZDJmfFgL:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac4e80f1957c04df207febd012b4e5bbaabbf49/pkg/sql/parser/sql.y#L4216)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

We discussed this before: is it wise to "toss it out"? Remember clients care about what shows up in introspection via pg_catalog/information_schema.
If pg lets these things remain through introspection, we should probably do the same.
</blockquote></details>

done
___
*[pkg/sql/row/cascader.go, line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTT5gtv8ceIlFbwStYC:-LTTUc_L9MFJs8spne46:b-xr079t) ([raw file](https://github.com/cockroachdb/cockroach/blob/48ffbe8917d3a57580efb6afc7b821501761203e/pkg/sql/row/cascader.go#L211)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Is it worth making this a switch or an else-if and erroring out if an unexpected match is encountered?  I'm thinking of the case where we do implement `match partial` for some reason.
</blockquote></details>

good idea, added a panic
___
*[pkg/sql/row/cascader.go, line 205 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTU8HWACcbi0cqC7EYV:-LTYdQeQ2k9RJyfJf8PA:b-2jd5gg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac4e80f1957c04df207febd012b4e5bbaabbf49/pkg/sql/row/cascader.go#L205)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Another thought complementary to bob's comments:

perhaps the two blocks of logic (here and below) can be placed in separate functions, and then store a function pointer in the cascader to either function during planning. This way we don't have to run through this conditional on every row.
</blockquote></details>

So I looked into this.  As long as there are only 2 options, an `if` vs a `switch` vs `func` all take about the same time.  For readability, I'm going to keep these as a switch.  If the code was used in more than one place, then I would go with the func.  (or there were more than 2 options)
___
*[pkg/sql/row/fk.go, line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTT6awSDbBQ38Eh8aXt:-LTTVoGa7JMCxGBkpNw2:b-s5o2zr) ([raw file](https://github.com/cockroachdb/cockroach/blob/48ffbe8917d3a57580efb6afc7b821501761203e/pkg/sql/row/fk.go#L474)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

`default:` that returns an error since it's an enum type?
</blockquote></details>

done, with a panic
___
*[pkg/sql/row/fk.go, line 475 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTU8_cP-Aq1P8ICapE0:-LTYf6gS032jLuRoC8HP:bwja27d) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac4e80f1957c04df207febd012b4e5bbaabbf49/pkg/sql/row/fk.go#L475)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto splitting into functions with fn ptr
</blockquote></details>

diito, added a default with panic
___
*[pkg/sql/row/fk.go, line 721 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTU8dPwExcOMBiP7Ixf:-LTYf9pS0IsWUok8xlyg:b-6xgshy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac4e80f1957c04df207febd012b4e5bbaabbf49/pkg/sql/row/fk.go#L721)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto fns
</blockquote></details>

again, switch with panic

**Review by knz — APPROVED** [review]
Changes LGTM overall, but, and I surprise myself for ever writing this, you have introduced too many tests :)

see below

> Reviewed 11 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-:-LTb_1AA-z9HLptiHpt3:b-33e4a1)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/show_create.go, line 107 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTbYnin3VCYU3uXiPdg:-LTbYnin3VCYU3uXiPdh:bhgqlld) ([raw file](https://github.com/cockroachdb/cockroach/blob/a92b821c0057c8e2861a429270e30da17c6ed7f9/pkg/sql/show_create.go#L107)):*
> ```Go
> 	buf.WriteByte(')')
> 	idx.ColNamesString()
> 	if fk.Match != sqlbase.ForeignKeyReference_SIMPLE {
> ```

nit: you could add a comment to remind the reader this is omitted because it is also the default.
___
*[pkg/sql/parser/parse_test.go, line 194 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTbZFU9B_7g9PpG-K9B:-LTbZFU9B_7g9PpG-K9C:bsrt21n) ([raw file](https://github.com/cockroachdb/cockroach/blob/a92b821c0057c8e2861a429270e30da17c6ed7f9/pkg/sql/parser/parse_test.go#L194)):*
> ```Go
> 		{`CREATE TABLE a (b INT8, c INT8 REFERENCES foo (bar))`},
> 		{`CREATE TABLE a (b INT8, c INT8 REFERENCES foo MATCH FULL)`},
> 		{`CREATE TABLE a (b INT8, c INT8 REFERENCES foo MATCH FULL ON UPDATE RESTRICT)`},
> ```

yeah no sorry here you're going a bit overboard. Only one test that combines the match spec with a cascading action is needed, to prove that all the other combinations are correct.

Parsing tests are cheap but they are not *that* cheap. I am not thrilled by cpu wastage.
___
*[pkg/sql/parser/parse_test.go, line 1812 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTbZPG9ETkmMMovSm66:-LTbZPGA3YypZSS4CEfD:bkv5sah) ([raw file](https://github.com/cockroachdb/cockroach/blob/a92b821c0057c8e2861a429270e30da17c6ed7f9/pkg/sql/parser/parse_test.go#L1812)):*
> ```Go
> 		{
> 			`CREATE TABLE a (b INT8, c INT8 REFERENCES foo MATCH SIMPLE ON UPDATE RESTRICT)`,
> 			`CREATE TABLE a (b INT8, c INT8 REFERENCES foo ON UPDATE RESTRICT)`,
> ```

ditto everything you added after this test is not needed.
___
*[pkg/sql/parser/parse_test.go, line 1960 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTbZ_kq6zVJUURHy2gg:-LTbZ_kq6zVJUURHy2gh:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/a92b821c0057c8e2861a429270e30da17c6ed7f9/pkg/sql/parser/parse_test.go#L1960)):*
> ```Go
> 		{
> 			`CREATE TABLE a (b INT8, FOREIGN KEY (b) REFERENCES other MATCH FULL ON UPDATE NO ACTION ON DELETE NO ACTION)`,
> 			`CREATE TABLE a (b INT8, FOREIGN KEY (b) REFERENCES other MATCH FULL)`,
> ```

ditto
___
*[pkg/sql/row/cascader.go, line 235 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTbZhYdBH3sgO-2k2n0:-LTbZhYdBH3sgO-2k2n1:b-7cxkwf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a92b821c0057c8e2861a429270e30da17c6ed7f9/pkg/sql/row/cascader.go#L235)):*
> ```Go
> 		}
> 	default:
> 		panic(fmt.Sprintf("unknown composite key match type: %v", match))
> ```

yeah no we don't do `panic` any more in functions that return `error`. Please use `pgerror.NewAssertionError`
___
*[pkg/sql/row/fk.go, line 517 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTbZpWr35AZ8EVP4hqY:-LTbZpWs-rO81Jvpc4y6:bx1htwv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a92b821c0057c8e2861a429270e30da17c6ed7f9/pkg/sql/row/fk.go#L517)):*
> ```Go
> 			}
> 		default:
> 			panic(fmt.Sprintf("unknown composite key match type: %v", fk.ref.Match))
> ```

ditto assertion error
___
*[pkg/sql/row/fk.go, line 755 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTbZvMi5SRXAKzmDLVA:-LTbZvMj1Cy8gD-_4Uui:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/a92b821c0057c8e2861a429270e30da17c6ed7f9/pkg/sql/row/fk.go#L755)):*
> ```Go
> 		}
> 	default:
> 		panic(fmt.Sprintf("unknown composite key match type: %v", ref.Match))
> ```

ditto

**Review by BramGruneir — COMMENTED** [review]
Yeah, I went a little exhaustive.  But they do run really quickly!  

Removed the extra tests and converted the panics to errors.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-:-LTcS28x66Jnemr7fgve:bqii1jl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/show_create.go, line 107 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTbYnin3VCYU3uXiPdg:-LTcHDIB2fAhortp_6fy:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a92b821c0057c8e2861a429270e30da17c6ed7f9/pkg/sql/show_create.go#L107)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: you could add a comment to remind the reader this is omitted because it is also the default.
</blockquote></details>

done
___
*[pkg/sql/parser/parse_test.go, line 194 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTbZFU9B_7g9PpG-K9B:-LTcQlyp6MEIa-h3tJgm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a92b821c0057c8e2861a429270e30da17c6ed7f9/pkg/sql/parser/parse_test.go#L194)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

yeah no sorry here you're going a bit overboard. Only one test that combines the match spec with a cascading action is needed, to prove that all the other combinations are correct.

Parsing tests are cheap but they are not *that* cheap. I am not thrilled by cpu wastage.
</blockquote></details>

Done.
___
*[pkg/sql/parser/parse_test.go, line 1812 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTbZPG9ETkmMMovSm66:-LTcQRu99h2ENXkPnX8H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a92b821c0057c8e2861a429270e30da17c6ed7f9/pkg/sql/parser/parse_test.go#L1812)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto everything you added after this test is not needed.
</blockquote></details>

Done.
___
*[pkg/sql/parser/parse_test.go, line 1960 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTbZ_kq6zVJUURHy2gg:-LTcQFhuASuYb3Zvn_zA:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a92b821c0057c8e2861a429270e30da17c6ed7f9/pkg/sql/parser/parse_test.go#L1960)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

done
___
*[pkg/sql/row/cascader.go, line 235 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTbZhYdBH3sgO-2k2n0:-LTcR7hQA4TCRwVseXcr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a92b821c0057c8e2861a429270e30da17c6ed7f9/pkg/sql/row/cascader.go#L235)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

yeah no we don't do `panic` any more in functions that return `error`. Please use `pgerror.NewAssertionError`
</blockquote></details>

Done.
___
*[pkg/sql/row/fk.go, line 517 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTbZpWr35AZ8EVP4hqY:-LTcRyg1CfXSP2R2QI-e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a92b821c0057c8e2861a429270e30da17c6ed7f9/pkg/sql/row/fk.go#L517)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto assertion error
</blockquote></details>

Done.
___
*[pkg/sql/row/fk.go, line 755 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32998#-LTbZvMi5SRXAKzmDLVA:-LTcRzPtDR_DC71kvO1N:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a92b821c0057c8e2861a429270e30da17c6ed7f9/pkg/sql/row/fk.go#L755)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Comment by BramGruneir** [comment]
TFTRs again!

bors r+

**Pull request merged**
