### PR TITLE
sql: better logging about the optimizer as well as some cancellation checks

### LINKED ISSUE #70245: roachtest/sqlsmith: query timed out during the optimization but didn't cancel
roachtest.sqlsmith/setup=rand-tables/setting=no-mutations [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3445998&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3445998&tab=artifacts#/sqlsmith/setup=rand-tables/setting=no-mutations) on master @ [2baefd353239ddc4e7f4299b8930001675b99aa9](https://github.com/cockroachdb/cockroach/commits/2baefd353239ddc4e7f4299b8930001675b99aa9):

```
SET CLUSTER SETTING sql.stats.automatic_collection.enabled = false;
SET CLUSTER SETTING sql.stats.histogram_collection.enabled = false;
CREATE TABLE table1 (col1_0 TIMESTAMP NULL, col1_1 BYTES[] NOT NULL, col1_2 REGTYPE NULL, col1_3 NAME NOT NULL, col1_4 VARCHAR NOT NULL, col1_5 FLOAT8, col1_6 TIMETZ NOT NULL, col1_7 UUID, col1_8 REGROLE NOT NULL, PRIMARY KEY (col1_3 DESC, col1_6), INVERTED INDEX (col1_5 ASC, col1_1 ASC), UNIQUE (col1_4 DESC, col1_3 ASC, col1_7, col1_8 ASC, col1_6) STORING (col1_1), INDEX (col1_0 ASC, col1_2 ASC) WHERE ((((table1.col1_6 = '24:00:00-15:59:00':::TIMETZ) AND (table1.col1_5 <= '-Inf':::FLOAT8)) OR (table1.col1_4 < '':::STRING)) AND (table1.col1_3 >= '"':::STRING)) AND (table1.col1_0 = '-2000-01-01 00:00:00':::TIMESTAMP), INDEX (col1_2 DESC, col1_8, col1_0 DESC, lower(CAST(col1_0 AS STRING)) ASC, col1_4 DESC) STORING (col1_1, col1_5, col1_7) WHERE table1.col1_3 = 'X':::STRING, INDEX (lower(CAST(col1_2 AS STRING)) DESC) STORING (col1_1, col1_2, col1_4, col1_5, col1_7) WHERE table1.col1_5 < '+Inf':::FLOAT8);
ALTER TABLE table1 INJECT STATISTICS e'[{"columns": ["col1_5"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 138276, "histo_col_type": "", "name": "__auto__", "null_count": 196316, "row_count": 500000}, {"columns": ["col1_7"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 499328, "histo_col_type": "", "name": "__auto__", "null_count": 443402, "row_count": 500000}, {"columns": ["col1_1"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 201318, "histo_col_type": "", "name": "__auto__", "null_count": 0, "row_count": 500000}, {"columns": ["col1_2"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 427135, "histo_col_type": "REGTYPE", "name": "__auto__", "null_count": 113519, "row_count": 500000}, {"columns": ["col1_3"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 295111, "histo_buckets": [{"distinct_range": 0, "num_eq": 6223916942010959526, "num_range": 0, "upper_bound": ""}, {"distinct_range": 17392505.35859956, "num_eq": 90000000, "num_range": 90000000, "upper_bound": "\\u0016"}, {"distinct_range": 573337559.5659553, "num_eq": 149102319233076337, "num_range": 1000000000, "upper_bound": "#"}, {"distinct_range": 0, "num_eq": 5796823224926735315, "num_range": 4397943438374733275, "upper_bound": "\'"}, {"distinct_range": 0, "num_eq": 6313390865291620758, "num_range": 4839790316214612609, "upper_bound": "9%;D\\u000e"}, {"distinct_range": 37530552462786056, "num_eq": 7569889223533147069, "num_range": 78289640422963076, "upper_bound": "S!"}, {"distinct_range": 937882853411466400, "num_eq": 7671545877451517318, "num_range": 1242326909312568640, "upper_bound": "o\\u000bZjvf:\'"}], "histo_col_type": "NAME", "name": "__auto__", "null_count": 0, "row_count": 500000}, {"columns": ["col1_4"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 76330, "histo_buckets": [{"distinct_range": 0, "num_eq": 100000, "num_range": 0, "upper_bound": "\\u000c91Z,h(%"}, {"distinct_range": 91476052466595150, "num_eq": 700000, "num_range": 3206335811550270607, "upper_bound": "\\u000eU\\u0006"}, {"distinct_range": 195.51639868377046, "num_eq": 5184358200953274487, "num_range": 1000, "upper_bound": "\\u0017\\u000e-^3"}, {"distinct_range": 1123905932206117000, "num_eq": 4000, "num_range": 4404771785818298145, "upper_bound": "8F\\u001bW#l"}, {"distinct_range": 0, "num_eq": 8750344073731143828, "num_range": 8000, "upper_bound": "v"}], "histo_col_type": "VARCHAR", "name": "__auto__", "null_count": 0, "row_count": 500000}, {"columns": ["col1_0"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 86844, "histo_col_type": "", "name": "__auto__", "null_count": 259950, "row_count": 500000}, {"columns": ["col1_6"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 331085, "histo_col_type": "", "name": "__auto__", "null_count": 0, "row_count": 500000}, {"columns": ["col1_8"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 443513, "histo_col_type": "", "name": "__auto__", "null_count": 0, "row_count": 500000}]':::JSONB;
SET statement_timeout='10s';

SELECT
	tab_124176.col1_4 AS col_298240, tab_124184.col1_8 AS col_298241
FROM
	defaultdb.public.table1@[0] AS tab_124176,
	defaultdb.public.table1@[0] AS tab_124177
	JOIN defaultdb.public.table1@table1_col1_2_col1_8_col1_0_expr_col1_4_idx AS tab_124178
		JOIN defaultdb.public.table1@table1_expr_idx AS tab_124179
			JOIN defaultdb.public.table1 AS tab_124180
				JOIN defaultdb.public.table1 AS tab_124181 ON
						(tab_124180.col1_0) = (tab_124181.col1_0)
						AND (tab_124180.col1_6) = (tab_124181.col1_6)
						AND (tab_124180.col1_3) = (tab_124181.col1_3)
						AND (tab_124180.col1_2) = (tab_124181.col1_2)
				JOIN defaultdb.public.table1@[0] AS tab_124182 ON
						(tab_124181.col1_2) = (tab_124182.col1_8) AND (tab_124180.col1_2) = (tab_124182.tableoid) ON
					(tab_124179.col1_2) = (tab_124180.col1_2)
			JOIN defaultdb.public.table1@[0] AS tab_124183 ON
					(tab_124182.crdb_internal_idx_expr_1) = (tab_124183.col1_4)
					AND (tab_124182.col1_3) = (tab_124183.crdb_internal_idx_expr_1)
			JOIN defaultdb.public.table1 AS tab_124184
				JOIN defaultdb.public.table1 AS tab_124185 ON
						(tab_124184.col1_2) = (tab_124185.col1_2)
						AND (tab_124184.col1_6) = (tab_124185.col1_6)
						AND (tab_124184.col1_3) = (tab_124185.col1_3)
						AND (tab_124184.col1_4) = (tab_124185.col1_4) ON (tab_124183.col1_8) = (tab_124184.col1_8) ON
				(tab_124178.col1_2) = (tab_124180.col1_2)
				AND (tab_124178.col1_2) = (tab_124185.col1_8)
				AND (tab_124178.crdb_internal_idx_expr) = (tab_124182.crdb_internal_idx_expr_1) ON
			(tab_124177.col1_8) = (tab_124181.col1_2)
			AND (tab_124177.crdb_internal_idx_expr_1) = (tab_124178.crdb_internal_idx_expr)
			AND (tab_124177.crdb_internal_idx_expr_1) = (tab_124183.col1_3);
```
<details><summary>Reproduce</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=rand-tables/setting=no-mutations.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-10001

### PR DESCRIPTION
**Pull request by yuzefovich**
**sql: add logging about the optimizer into the trace**

This commit derives a separate tracing span on the main query path that
covers the whole optimizer as well as adds a few logging messages around
the optbuilder and the optimization. It also audits some of the already
present logs to be written down before performing possibly long
operations.

Release note: None

**xform: check for context cancellation**

reviously, the optimizer didn't check the context cancellation ever
which could lead to surprising behavior - e.g. if the statement timeout
occurs in the middle of the optimization, we would still finish the
whole optimization phase only to realize that we were canceled at the
execution time.

This situation is now improved by periodically checking for the context
cancellation every time a group is optimized by `optimizeGroup`. It's
still possible for the optimizer to continue running long after
cancellation if there is a long running procedure at a deeper level.
For example, a long-running, individual invocation of an exploration
rule will not halt due to context cancellation. However,
the cancellation improvement in this commit should halt long-running
optimization in most cases.

Fixes: #70245.
Addresses: #70314.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Rebased on top of master, RFAL.

**Review by mgartner — APPROVED** [review]
This is great, thanks for doing this! :lgtm: 

> Reviewed 16 of 18 files at r1, 7 of 7 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85041#-:-N80-Ec09dHl3GPHic_H:b-dx3uvs)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[`-- commits` line 20 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85041#-N8-xxlU6BUXqRgfu9ds):*
nit: make this more specific, like:

This situation is now improved by periodically checking for the context cancellation every time a group is optimized by `optimizeGroup`. It's still possible for the optimizer to continue running long after cancellation if there is a long running procedure at a deeper level. For example, a long-running, individual invocation of an exploration rule will not halt due to context cancellation. However, the cancellation improvement in this commit should halt long-running optimization in most cases.

**Comment by yuzefovich** [comment]
Fixed the commit message and moved some changes from the second commit into the first one so that it compiles.

TFTR!

bors r+

**Comment by yuzefovich** [comment]
Forgot to include the new logic test file, now fixed.

bors r+

**Pull request merged**
