### PR TITLE
sql/execinfra: propagate ClosedTimestampPolicy through MisplannedRanges

### PR DESCRIPTION
**Pull request by nvb**
This was causing issues with reads from GLOBAL tables, as a gateway's
RangeCache was forgetting about the ClosedTimestampPolicy if it ever
performed a DistSQL operation. This commit fixes the issue by attaching
the ClosedTimestampPolicy to RangeInfos in MisplannedRanges.

This commit also fixes two bugs in the function:
1. misplanned wasn't being populated, so it's attempt to de-duplicate
   ranges was failing.
2. the log statement was only printing out the first descriptor, even
   if 2 or 3 ranges were misplanned.

This code is also making me wonder: do we count DistSQL flows that are
intentionally planned on followers to execute follower reads using the
ClosestOracle as "misplanned"?

Release justification: necessary for new functionality

### CODE REVIEW

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> This code is also making me wonder: do we count DistSQL flows that are
> intentionally planned on followers to execute follower reads using the
> ClosestOracle as "misplanned"?

No idea. Let's ask... @yuzefovich ?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61244#-:-MUl4J9B4A_oatK3XZNB:bqk70jx)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by yuzefovich — COMMENTED** [review]
I've never looked at this code before, but my reading of the code is the same - that we don't pay attention to whether a read is from a follower when it is planned so or from a follower when it was misplanned, so I'm assuming they all will get counted as "misplanned."

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61244#-:-MUl70Da2QmvEZzq6Ie1:b-nn4gnk)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andreimatei — APPROVED** [review]
@yuzefovich mind if I ask you to file an issue about it?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61244#-:-MUl9gRK5zOL0LM9Rz2Z:b-dwqend)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
Done (#61313).

**Comment by nvanbenschoten** [comment]
Thanks for the reviews and for filing the issue!

bors r+

**Pull request merged**
