### PR TITLE
build: remove roachtest nightly scripts

### PR DESCRIPTION
**Pull request by benesch**
The scripts now live in TeamCity so that they can be run against
multiple versions of Cockroach without being backported to every release
branch. Remove them from version control to avoid confusion.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24386#-:-L90fbhl79SqnmLpXwt6:bnfp4nl)*

**Comment by petermattis** [comment]
Shouldn't that be `bors r=petermattis`? Does it matter?

**Comment by benesch** [comment]
Yeah, probably. I think all it controls is who’s listed in the merge commit
as the reviewer.

**Comment by andreimatei** [comment]
the files deleted here are referenced on the wiki in https://github.com/cockroachdb/cockroach/wiki/Nightly-Tests

Nikhil, would you mind updating that pretty please? I would do it, but I don't really know where these scripts are at the moment (which is why I was reading that doc in the first place).

**Pull request merged**
