### PR TITLE
Add an AnnotateTrace() utility.

### PR DESCRIPTION
**Pull request by petermattis**
AnnotateTrace() adds an annotation trace to the golang execution tracer by
invoking a system call (i.e. a no-op cgo function). Annotations are only
enabled when the ANNOTATE_TRACES environment variable is set to 1.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4010)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[kv/dist_sender.go, line 474 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4010#-K985l9BHwqpO7eMxXh1:-K985l9C2aRgw_crxHbu:-218014805) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbfbba359ddc86c40ff9736b0289f08a41b91931/kv/dist_sender.go#L474)):*
can you consistently buffer with whitespace or not?

---

*[util/tracer/annotate.go, line 24 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4010#-K985_0iKaI2O3vU0gSa:-K985_0iKaI2O3vU0gSb:-1247071060) ([raw file](https://github.com/cockroachdb/cockroach/blob/40ddcdfb717d4676846a2234ecea59de0a6b1ae4/util/tracer/annotate.go#L24)):*
interesting use of parens

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4010)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[kv/dist_sender.go, line 474 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4010#-K985l9BHwqpO7eMxXh1:-K989KgjvUWAJ4s_ACPM:-79122317) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbfbba359ddc86c40ff9736b0289f08a41b91931/kv/dist_sender.go#L474)):*
Yes, I'll add some whitespace above.

---

*[util/tracer/annotate.go, line 24 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4010#-K985_0iKaI2O3vU0gSa:-K989E_7DzK_8_1JoCuO:-1131190630) ([raw file](https://github.com/cockroachdb/cockroach/blob/40ddcdfb717d4676846a2234ecea59de0a6b1ae4/util/tracer/annotate.go#L24)):*
Old C habits. Removed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4010)*

**Comment by tamird** [comment]
LGTM

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/db.go, line 484 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4010#-K98APR2JLbjcGwM_01c:-K98APR3FFNHSRDyZs1d:-1196261571) ([raw file](https://github.com/cockroachdb/cockroach/blob/017f019f08e8fa0a2a45fd186fe46a9b487f7563/client/db.go#L484)):*
whitespace?

---

*[client/txn.go, line 290 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4010#-K98AQbqzbE-By9plH76:-K98AQbqzbE-By9plH77:-1196261571) ([raw file](https://github.com/cockroachdb/cockroach/blob/017f019f08e8fa0a2a45fd186fe46a9b487f7563/client/txn.go#L290)):*
whitespace?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4010#-:-K98ASvFybOpz4OfGlMu:676834233)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/db.go, line 484 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4010#-K98APR2JLbjcGwM_01c:-K98IcRWuxzR9heJoxe5:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/017f019f08e8fa0a2a45fd186fe46a9b487f7563/client/db.go#L484)):*
Done.

---

*[client/txn.go, line 290 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4010#-K98AQbqzbE-By9plH76:-K98IfTuJ-fhhpAQfdUe:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/017f019f08e8fa0a2a45fd186fe46a9b487f7563/client/txn.go#L290)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4010)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4010)*

**Comment by dt** [comment]
Reviewed 1 of 1 files at r1, 6 of 6 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4010)*

**Pull request merged**
