### PR TITLE
sql: Unify the SQL type system

### LINKED ISSUE #32639: sql: Grand Unified Type System
> A Grand Uniform Type System to unify the disparate and partially-disjoint needs of coltypes.T, types.T, ColumnType.proto, and encoding

This is a tracking issue for what would be quite a significant refactoring to unify the disparate typesystems embedded in cockroach.

Take the SQL INT4 type as it exists today:
* A semantic type: coltypes.TInt{Width:4},  “an integer that fits in 4 bytes”
* A computation type: types.TInt, “an integer to do math on”
* A protobuf type: ColumnType{ SemanticType: INT, Width: 32 }
* Multiple representational types: a sequence of 4 bytes or a UTF-8 string [relevant for no-op / deferred casts]

We run into problems where we go semantic (`coltypes.T`) -> computation (`types.T` / `Datum`) -> semantic (`coltypes.T`), etc.

Any given database schema will have a finite number of unified types whose instances we can memoize.

We have many different “equivalences” for semantic, computation, protobuf, and encoding needs.

### PR DESCRIPTION
**Pull request by andy-kimball**
This PR unifies the three different SQL type systems in CRDB:

  `sqlbase.ColumnType` - protobuf representation of table column types
  `coltypes.T` - in-memory representation of table column types
  `types.T` - computation types

The type systems are quite similar, but also subtly different. This causes bugs on a regular basis throughout the codebase. Each type system supports a different subset of the PG type functionality. For example, `sqlbase.ColumnType` stores column widths. `types.T` does not store widths, but it can store a Postgres OID value, which `sqlbase.ColumnType` is unable to do.

In addition, even for supported functionality, the API's are often tricky and error-prone. For example, `types.T` values can sometimes be compared using `==`, but other times `Equivalent` must be called, and it is up to the user to know when to use which. As another example, support for OID values require wrapping `types.T` instances in a special `TOIDWrapper` type. Our developers are expected to know when it needs to be done, but typically they either don't understand when it's needed, or else forget to do it. It also breaks `==` comparison semantics, leading to subtle bugs that only manifest in edge cases with unusual OID values.

Another big problem that comes up repeatedly are lossy conversions. Throughout the codebase, there are frequent conversions to/from the various type systems. Many conversions discard important type information, which often leads to incompatibilities with Postgres, as well as providing a breeding ground for bugs.

This PR unifies the three type systems into just one. The unified type is called `types.T` (in new `sql/types` package). It uses a protobuf-generated struct that is backwards-compatible with `sqlbase.ColumnType` so that it can be embedded in place of `ColumnType` in larger protobuf messages (like `sqlbase.ColumnDescriptor`). The API is locked down so that it's difficult to ignorantly or accidentally create invalid types. The unified type supports everything that the three previous type systems did, and is more compatible with PG as a result (with more work, even more type compatibility is possible).

Resolves #32639

### CODE REVIEW

**Comment by andy-kimball** [comment]
Note to reviewers:
I know this is a real monster of a PR. However, I did it in stages, where each commit is a standalone step that builds and passes tests. This also makes it easier to rebase.

It might be easiest to review the final `sql/types` package first, to see where it all ends up. Then, you might review commit by commit to see each step towards the final product.

**Comment by RaduBerinde** [comment]
This is fantastic. Thank you for doing this!

**Comment by andy-kimball** [comment]
Anyone have suggestions about resolving a `golint` error:
```
pkg/sql/types/types.go:286:2: var Uuid should be UUID
```
I'm already using UUID to signify the name of the `SemanticType`. All other types follow this convention of `types.INT` (SemanticType) vs. `types.Int` (pre-constructed instance). I can't find a way to disable lint for this one line, either.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36598)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @BramGruneir, @jordanlewis, and @knz)

___
*[pkg/sql/pgwire/types.go, line 73 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/36598#-LbxcbDP4knSMBBiYAHR:-LbxcbDP4knSMBBiYAHS:b-xzar0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/021b1c58012ff407e9dc0a5785ae16a6d894017c/pkg/sql/pgwire/types.go#L73)):*
> ```Go
> // mapResultOid performs any necessary mapping of Oid values to be returned to
> // the client. For now, this only includes mapping T_float4 => T_float8.
> func mapResultOid(o oid.Oid) oid.Oid {
> ```

@knz, I wasn't sure what to do about this issue (I believe it's a bug in libpq). I ended up mapping from float4 => float8 to work around it. But it raises larger issues about whether it's a good idea to begin returning the true OID values for selected columns. Should we map all OIDs to "canonical" OIDs (e.g. int2 => int8, varchar => string, etc) in order to match previous version behavior?

P.S. The PG client does not exhibit this bad float4 behavior when pointed at CRDB. It's a libpq thing.

**Comment by andy-kimball** [comment]
Another suggestion for reviewers: compare all changes made to test files (e.g. `information_schema` and `pg_catalog`), since that will tend to show differences in behavior as a result of this PR.

**Comment by RaduBerinde** [comment]
> Anyone have suggestions about resolving a golint error:

Just add an exception here: https://github.com/cockroachdb/cockroach/blob/master/pkg/testutils/lint/lint_test.go#L1451
Something like
`stream.GrepNot("pkg/sql/types/types.go.* var Uuid should be UUID")`
so it's only for this file.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36598)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @BramGruneir, @jordanlewis, and @knz)

___
*[pkg/sql/logictest/testdata/logic_test/array, line 212 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/36598#-LbxfBcS0PNcR_hWV-jm:-LbxfBcS0PNcR_hWV-jn:b-gtz90n) ([raw file](https://github.com/cockroachdb/cockroach/blob/021b1c58012ff407e9dc0a5785ae16a6d894017c/pkg/sql/logictest/testdata/logic_test/array#L212)):*
> ```
> {1,2,3}
> 
> query T
> ```

This new behavior matches PG.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36598)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @BramGruneir, @jordanlewis, and @knz)

___
*[pkg/sql/parser/parse.go, line 374 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/36598#-LbxsesTDUHAreZ4ldkZ:-LbxsesU5mUahL3lom-G:b-xymv7r) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc215c09be4dc0058794663c97913fc71dbeedb2/pkg/sql/parser/parse.go#L374)):*
> ```Go
> }
> 
> // The SERIAL types are pseudo-types that are only used during parsing. After
> ```

@knz, I wanted to call this out. I'm treating SERIAL differently now by not creating a "real" type for it. Instead, it's just different instances of the INT types that I then use == reference comparison to recognize. All "memory" of these types is gone after the analysis phase is complete; they exist only for pretty-printing the parse tree.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36598)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @BramGruneir, @jordanlewis, and @knz)

___
*[pkg/sql/pgwire/types.go, line 73 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/36598#-LbxcbDP4knSMBBiYAHR:-LbxxiCm0-c0sohRwUHt:b358hyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/021b1c58012ff407e9dc0a5785ae16a6d894017c/pkg/sql/pgwire/types.go#L73)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

@knz, I wasn't sure what to do about this issue (I believe it's a bug in libpq). I ended up mapping from float4 => float8 to work around it. But it raises larger issues about whether it's a good idea to begin returning the true OID values for selected columns. Should we map all OIDs to "canonical" OIDs (e.g. int2 => int8, varchar => string, etc) in order to match previous version behavior?

P.S. The PG client does not exhibit this bad float4 behavior when pointed at CRDB. It's a libpq thing.
</blockquote></details>

As another example, not mapping to previous OIDs results in this Java acceptance test failing:
```
    public void testArrayWithProps() throws Exception {
        PreparedStatement stmt = conn.prepareStatement("CREATE TABLE x (a SMALLINT[])");
        stmt.execute();
        stmt = conn.prepareStatement("INSERT INTO x VALUES (ARRAY[123])");
        stmt.execute();
        stmt = conn.prepareStatement("SELECT a FROM x");
        ResultSet rs = stmt.executeQuery();
        rs.next();

        Array ar = rs.getArray(1);
        Long[] fs = (Long[]) ar.getArray();
        Assert.assertArrayEquals(new Long[]{123L}, fs);
    }
```
with the error: `incompatible types: long cannot be converted to java.lang.Integer`
since oid.T__int2 is returned rather than oid.T__int8, as before.

**Comment by knz** [comment]
I'll love to review this when I travel ba k from the conference on Wednesday.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by knz** [comment]
@andy-kimball reviewable and github reviews are barfing on me due to the large number of files. I'm going to do something a little unorthodox to approach this review, bear with me.

**Comment by knz** [comment]
I have split this PR into multiple separate PRs: #36698 to  #36711.
I will be assigning these PRs to separate reviewers to accelerate/facilitate the work.

Since you will need to rebase your work, and/or make changes to individual commits, please operate as follows:

- when making changes, edit/rebase *this branch* (`types` on your repo)
- ensure that you do not remove or add commits
- after every batch of change, re-push the commits to the review branches using my split script included below: `bash split.sh <base commit SHA>`

Here's the `split.sh`:

```sh
#! /bin/bash

set -eux

# stop_at is the first commit which should stop the loop
stop_at=${1:?}

i=1
for commit in `git log --format=oneline $stop_at.. | cut -d' ' -f1 | sed -n '1!G;h;$p'`; do
        git push -f ssh://git@github.com/cockroachdb/cockroach $commit:refs/heads/split-pr-36598-$i
        i=$(expr $i + 1)
done

```

**Comment by knz** [comment]
Also please do not merge the review PRs individually. We'll merge this PR (#36598) when the individual reviews have completed.

**Comment by knz** [comment]
Here's a checkbox list to track completed reviews:


- [ ] sql: Move sqlbase.ColumnType to types package (patch 1/) #36698
- [ ] sql: Rename type codes (patch 2/) #36699
- [ ] sql: Use SemanticType and Equivalent exclusively (patch 3/) #36700
- [ ] sql: Add Oid support to types.ColumnType (patch 4/)\ #36701
- [ ] sql: Add support for nested arrays to ColumnType (patch 5/) #36702
- [ ] sql: Fix cases where ColumnType is unnecessarily passed by value (patch 6/) #36703
- [ ] sql: Convert types.T to use ColumnType (patch 7/) #36704
- [ ] sql: Show more specific types when available (patch 8/) #36705
- [ ] sql: Merge coltypes.T with types.T (patch 9/) #36706
- [ ] sql: Rename SemanticType NULL to UNKNOWN (patch 10/) #36707
- [ ] sql: Rename types.ColumnType to types.T and delete VisibleType (patch 11/) #36708
- [ ] sql: Rename DOIDWrapper to DTypeWrapper (patch 12/) #36709
- [ ] sql: Expose methods rather than fields on types.T (patch 13/) #36710
- [ ] sql: Comment and test types package (patch 14/) #36711
- [ ] sql: Move sql/sem/types package to sql/types (patch 15/) #36712

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 139 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36598)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @bobvawter, @BramGruneir, @jordanlewis, and @knz)

___
*[pkg/sql/pgwire/types.go, line 73 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/36598#-LbxcbDP4knSMBBiYAHR:-Lc5s-Db1viBOyZ2yqbK:bz1thpq) ([raw file](https://github.com/cockroachdb/cockroach/blob/021b1c58012ff407e9dc0a5785ae16a6d894017c/pkg/sql/pgwire/types.go#L73)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

As another example, not mapping to previous OIDs results in this Java acceptance test failing:
```
    public void testArrayWithProps() throws Exception {
        PreparedStatement stmt = conn.prepareStatement("CREATE TABLE x (a SMALLINT[])");
        stmt.execute();
        stmt = conn.prepareStatement("INSERT INTO x VALUES (ARRAY[123])");
        stmt.execute();
        stmt = conn.prepareStatement("SELECT a FROM x");
        ResultSet rs = stmt.executeQuery();
        rs.next();

        Array ar = rs.getArray(1);
        Long[] fs = (Long[]) ar.getArray();
        Assert.assertArrayEquals(new Long[]{123L}, fs);
    }
```
with the error: `incompatible types: long cannot be converted to java.lang.Integer`
since oid.T__int2 is returned rather than oid.T__int8, as before.
</blockquote></details>

Please redirect this discussion to #36704. I have some ideas/proposals.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36598)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @bobvawter, @BramGruneir, @jordanlewis, and @knz)

___
*[pkg/sql/parser/parse.go, line 374 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/36598#-LbxsesTDUHAreZ4ldkZ:-Lc61KopCijaSf61axJa:b-j5la54) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc215c09be4dc0058794663c97913fc71dbeedb2/pkg/sql/parser/parse.go#L374)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

@knz, I wanted to call this out. I'm treating SERIAL differently now by not creating a "real" type for it. Instead, it's just different instances of the INT types that I then use == reference comparison to recognize. All "memory" of these types is gone after the analysis phase is complete; they exist only for pretty-printing the parse tree.
</blockquote></details>

Yes, I reviewed and understood that logic in #36710. LGTM.

**Pull request merged**
