### PR TITLE
ui: save help-us data to the Cockroach Labs servers

### PR DESCRIPTION
**Pull request by maxlang**
cc @jess-edwards

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9783)

### CODE REVIEW

**Comment by tamird** [comment]
No tests?

---

Reviewed 6 of 7 files at r1.
Review status: 6 of 7 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[ui/app/app.tsx, line 64 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KTQ-z8n_EVvuvp-QTFS:-KTQ-z8n_EVvuvp-QTFT:b-hwx0ld) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9440907584086968a144ccb026ee8b5811b6778/ui/app/app.tsx#L64)):*
> ```XML
> import RaftRanges from "./containers/raftRanges";
> 
> // Communicate with Cockroach Labs server
> ```

so just importing this file causes magic to happen in the background? elaborate and make this a proper sentence with punctuation.

---

*[ui/app/containers/helpus.tsx, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KTQ-xi0-Um0ZwCWKzv5:-KTQ-xi0-Um0ZwCWKzv6:brnpxri) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9440907584086968a144ccb026ee8b5811b6778/ui/app/containers/helpus.tsx#L53)):*
> ```XML
>       this.props.saveUIData(
>         { key: KEY_HELPUS, value: this.state },
>        // Mark data as not synchronized to the Cockroach Labs server
> ```

missing period.

---

*[ui/app/containers/helpus.tsx, line 54 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KTQ-n_h53qN9Mc1wsTl:-KTQ-n_h53qN9Mc1wsTm:brtisem) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9440907584086968a144ccb026ee8b5811b6778/ui/app/containers/helpus.tsx#L54)):*
> ```XML
>         { key: KEY_HELPUS, value: this.state },
>        // Mark data as not synchronized to the Cockroach Labs server
>         { key: KEY_REGISTRATION_SYNCHRONIZED, value: false}
> ```

missing space, missing comma.

---

*[ui/app/util/cockroachlabsAPI.ts, line 43 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KTQ0pnSWHVBqXuINQRL:-KTQ0pnSWHVBqXuINQRM:bat6gnx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9440907584086968a144ccb026ee8b5811b6778/ui/app/util/cockroachlabsAPI.ts#L43)):*
> ```XML
> }
> 
> export interface RegistrationRequest {
> ```

where does this come from? comment.

---

*[ui/app/util/cockroachlabsAPI.ts, line 60 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KTQ0xEWhNhjShKXbxiR:-KTQ0xEWhNhjShKXbxiS:brx1hke) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9440907584086968a144ccb026ee8b5811b6778/ui/app/util/cockroachlabsAPI.ts#L60)):*
> ```XML
> 
> export function versionCheck(request: VersionCheckRequest, timeout?: moment.Duration): Promise<VersionList> {
>   return timeoutFetch(`${COCKROACHLABS_ADDR}/api/clusters/updates?uuid=${request.clusterID}&version=${request.buildtag}`, undefined, { timeout });
> ```

why is undefined better than null here?

---

*[ui/app/util/cockroachlabsAPI.ts, line 64 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KTQ16NQuLGjQLHf03rZ:-KTQ16NQuLGjQLHf03r_:b-15f1up) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9440907584086968a144ccb026ee8b5811b6778/ui/app/util/cockroachlabsAPI.ts#L64)):*
> ```XML
> 
> export function registerCluster(request: RegistrationRequest, timeout?: moment.Duration): Promise<{}> {
>   return timeoutFetch(`${COCKROACHLABS_ADDR}/api/clusters/register?uuid=${request.clusterID}`, JSON.stringify(request), { timeout });
> ```

I'm almost positive that there's no need to stringify.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-:-KTQ1Dvkui6Dzdy2BO-W:btvqfw8)*

**Comment by maxlang** [comment]
I'll write up a few.

---

Review status: 2 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[ui/app/app.tsx, line 64 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KTQ-z8n_EVvuvp-QTFS:-KTQ4zpw55hOiFdGxZ3j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9440907584086968a144ccb026ee8b5811b6778/ui/app/app.tsx#L64)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> so just importing this file causes magic to happen in the background? elaborate and make this a proper sentence with punctuation.
</details>
Done.

---

*[ui/app/containers/helpus.tsx, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KTQ-xi0-Um0ZwCWKzv5:-KTQ2-AR2S8P1c2UvsMB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9440907584086968a144ccb026ee8b5811b6778/ui/app/containers/helpus.tsx#L53)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> missing period.
</details>
Done.

---

*[ui/app/containers/helpus.tsx, line 54 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KTQ-n_h53qN9Mc1wsTl:-KTQ215pFpOeh760P8RU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9440907584086968a144ccb026ee8b5811b6778/ui/app/containers/helpus.tsx#L54)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> missing space, missing comma.
</details>
Done.

---

*[ui/app/util/cockroachlabsAPI.ts, line 43 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KTQ0pnSWHVBqXuINQRL:-KTQ2cwAj-qqMDUhPrzZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9440907584086968a144ccb026ee8b5811b6778/ui/app/util/cockroachlabsAPI.ts#L43)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> where does this come from? comment.
</details>
Done.

---

*[ui/app/util/cockroachlabsAPI.ts, line 60 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KTQ0xEWhNhjShKXbxiR:-KTQ39gPJun9ElhmUjEU:bahs8jj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9440907584086968a144ccb026ee8b5811b6778/ui/app/util/cockroachlabsAPI.ts#L60)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why is undefined better than null here?
</details>
At one point I thought it was causing an error but it looks like it was something else.

---

*[ui/app/util/cockroachlabsAPI.ts, line 64 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KTQ16NQuLGjQLHf03rZ:-KTQ3TdqI92mnY9AZ6jo:b-1vezij) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9440907584086968a144ccb026ee8b5811b6778/ui/app/util/cockroachlabsAPI.ts#L64)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I'm almost positive that there's no need to stringify.
</details>
It must be a of type `T extends BodyInit` and `BodyInit` is `Blob | ArrayBufferView | ArrayBuffer | FormData | string`. It must be turned into one of these things before it's passed to `fetch` as the body, at least given the current typings. It's possible the fetch code would handle an object correctly but it wouldn't compile.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-:-KTQ6RpB4s0WiDCGOyfN:b-hq3fd0)*

**Comment by tamird** [comment]
Reviewed 6 of 7 files at r2.
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[ui/app/app.tsx, line 64 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KTQ-z8n_EVvuvp-QTFS:-KTQ9QRppunCkvFwKxK9:b-mmwlg8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9440907584086968a144ccb026ee8b5811b6778/ui/app/app.tsx#L64)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Done.
</details>
Ah, so it's not magic. Just remove the comment IMO.

---

*[ui/app/app.tsx, line 67 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KTQ9Y9Vql9QMm2V5pHv:-KTQ9Y9WW3SeBaXyPG0k:blvt08v) ([raw file](https://github.com/cockroachdb/cockroach/blob/1eb01e56ee20899b993dbb1443e36bacfe19a8e1/ui/app/app.tsx#L67)):*
> ```XML
> // registration data will be synchronized appropriately as the store changes.
> import registrationSyncListener from "./services/registrationService";
> store.subscribe(registrationSyncListener);
> ```

can this be down just before the ReactDOM.render call? this is an unconventional place for it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783)*

**Comment by jess-edwards** [comment]
@maxlang How do we test this is working? 

---

Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-:-KTQgZSvZqEz5q25QXqX:b-v59lmk)*

**Comment by mrtracy** [comment]
It's a pretty complex function, but I think it's written correctly.  Assuming you get the tests in, the code is LGTM (with suggestions).

---

Review status: 8 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[ui/app/services/registrationService.ts, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KTQdUbEAePOri3Mb3Qe:-KTQdUbEAePOri3Mb3Qf:buy1kc0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9440907584086968a144ccb026ee8b5811b6778/ui/app/services/registrationService.ts#L19)):*
> ```XML
>  *  This service keeps the user's registration data synchronized with the Cockroach Labs servers.
>  */
> store.subscribe(function registrationSynchronizer() {
> ```

I don't think this function needs to be named.

---

*[ui/app/services/registrationService.ts, line 81 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KTQjm2GaaesNVCg3kHb:-KTQjm2GaaesNVCg3kHc:b-c6yoej) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9440907584086968a144ccb026ee8b5811b6778/ui/app/services/registrationService.ts#L81)):*
> ```XML
>       email: helpusData.email,
>       clusterID: state.cachedData.cluster.data.cluster_id,
>     }).then(registrationCallback).catch(() => errors++).then(() => saving = false);
> ```

Don't put this last bit on one line, I don't think it's very readable.  Put each subsequent clause on its own line.

---

*[ui/app/services/registrationService.ts, line 85 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KTQjtcTD7jA48HYOFvC:-KTQjtcTD7jA48HYOFvD:b-816h6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9440907584086968a144ccb026ee8b5811b6778/ui/app/services/registrationService.ts#L85)):*
> ```XML
>     unregisterCluster({
>       clusterID: state.cachedData.cluster.data.cluster_id,
>     }).then(registrationCallback).catch(() => errors++).then(() => saving = false);
> ```

Same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-:-KTQl_6mp2oS9XkuZMmF:bq6abv3)*

**Comment by maxlang** [comment]
@jess-edwards good point. I had to pass along one new property to make it work but here's the Hubspot proof:



---

Review status: 8 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[ui/app/app.tsx, line 64 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KTQ-z8n_EVvuvp-QTFS:-KTQKgMM-n5eLH0d24UF:b97o1du) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9440907584086968a144ccb026ee8b5811b6778/ui/app/app.tsx#L64)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Ah, so it's not magic. Just remove the comment IMO.
</details>
Yeah it just caused the file to be run. But you're right that it obscured what that file actually did so I moved the subscribe call to `app.tsx`.

---

*[ui/app/app.tsx, line 67 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KTQ9Y9Vql9QMm2V5pHv:-KTQL-NoQh2sxFPoow19:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1eb01e56ee20899b993dbb1443e36bacfe19a8e1/ui/app/app.tsx#L67)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can this be down just before the ReactDOM.render call? this is an unconventional place for it.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-:-KTQmeDgWNRXtSQjxhhF:b3tb3k1)*

**Comment by tamird** [comment]
Review status: 8 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[ui/app/app.tsx, line 67 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KTQ9Y9Vql9QMm2V5pHv:-KTQoUedjVKup-MVPJPN:bhptoqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1eb01e56ee20899b993dbb1443e36bacfe19a8e1/ui/app/app.tsx#L67)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Done.
</details>
Publish-before-push? Please refrain from publishing comments before the corresponding changes have been pushed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783)*

**Comment by maxlang** [comment]
*[ui/app/app.tsx, line 67 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KTQ9Y9Vql9QMm2V5pHv:-KTSD4AkFN0DMGpSTID5:b4jl5pm) ([raw file](https://github.com/cockroachdb/cockroach/blob/1eb01e56ee20899b993dbb1443e36bacfe19a8e1/ui/app/app.tsx#L67)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Publish-before-push? Please refrain from publishing comments before the corresponding changes have been pushed.
</details>
Sorry I only meant to publish the response to Jess and wasn't paying attention to my drafts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783)*

**Comment by jess-edwards** [comment]
@maxlang - It worked! LGTM! 

---

Review status: 8 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-:-KTUrU3yjwj2aLy-Xk_t:b-3y79gl)*

**Comment by maxlang** [comment]
Added a couple tests.

---

Review status: 4 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[ui/app/services/registrationService.ts, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KTQdUbEAePOri3Mb3Qe:-KTQnPbSq5owcfQgZWU3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9440907584086968a144ccb026ee8b5811b6778/ui/app/services/registrationService.ts#L19)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> I don't think this function needs to be named.
</details>
Done.

---

*[ui/app/services/registrationService.ts, line 81 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KTQjm2GaaesNVCg3kHb:-KTQnEEvcJnt0fBc6Ncf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9440907584086968a144ccb026ee8b5811b6778/ui/app/services/registrationService.ts#L81)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> Don't put this last bit on one line, I don't think it's very readable.  Put each subsequent clause on its own line.
</details>
Done.

---

*[ui/app/services/registrationService.ts, line 85 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KTQjtcTD7jA48HYOFvC:-KTQnDzIqPxni8n_dhzG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9440907584086968a144ccb026ee8b5811b6778/ui/app/services/registrationService.ts#L85)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> Same.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-:-KTVgGsLNCNbjjLFj5Ju:b-stxmon)*

**Comment by tamird** [comment]
Reviewed 5 of 7 files at r3.
Review status: 9 of 11 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[ui/app/redux/state.ts, line 27 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KTVp2EDPP38IUcMZqxB:-KTVp2EDPP38IUcMZqxC:b-3zamwl) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fd5dae7f5f3fb9d70e145ca1750f9e9e2328207/ui/app/redux/state.ts#L27)):*
> ```XML
> }
> 
> // createAdminUIStore is a function that returns a new admin UI store
> ```

proper sentences, please.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783)*

**Comment by maxlang** [comment]
Review status: 7 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[ui/app/redux/state.ts, line 27 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KTVp2EDPP38IUcMZqxB:-KTWBCcI6W4Wcl5aIaJc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fd5dae7f5f3fb9d70e145ca1750f9e9e2328207/ui/app/redux/state.ts#L27)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> proper sentences, please.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r4.
Review status: 9 of 11 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783)*

**Comment by maxlang** [comment]
@mrtracy I wanted to give saving notifications so I started tracking status info per UI key.

screen shot 2016-10-18 at 5 50 45 pm

screen shot 2016-10-18 at 5 39 01 pm
screen shot 2016-10-18 at 5 38 59 pm
screen shot 2016-10-18 at 5 38 46 pm

**Comment by maxlang** [comment]
@tamird you may also wish to rereview

**Comment by maxlang** [comment]
Cc @kuanluo if you have any thoughts here as well

**Comment by tamird** [comment]
What's the second commit about? What's the motivation?

---

Reviewed 18 of 22 files at r5, 1 of 9 files at r6.
Review status: 7 of 15 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/ui/app/containers/helpus.tsx, line 53 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KURueubjFvrgIC1Nfxh:-KURueubjFvrgIC1Nfxi:b-3umkum) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed14af7f545aa9eb4326af592ec0750db026400/pkg/ui/app/containers/helpus.tsx#L53)):*
> ```XML
>       this.props.saveUIData(
>         { key: KEY_HELPUS, value: this.state },
>        // Save an additional key to track that this data is not synchronized to
> ```

misaligned

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-:-KURva8rcwEUvLbZg7v_:b-dy2xj3)*

**Comment by maxlang** [comment]
@tamird I added a longer commit message. I was putting some finishing touches on this PR to show the saving status when you pressed "Submit" and ran into the snag that I couldn't tell when a specific key was saving and if saving that specific key had failed. I refactored the uiData reducer to support this but kept it in its own commit.

---

Review status: 6 of 15 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/ui/app/containers/helpus.tsx, line 53 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KURueubjFvrgIC1Nfxh:-KUSTE5S-m5gVTzL6qju:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed14af7f545aa9eb4326af592ec0750db026400/pkg/ui/app/containers/helpus.tsx#L53)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> misaligned
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-:-KUSTYcxqazoboIjbvGn:b-1nujfk)*

**Comment by kuanluo** [comment]
The visual changes LGTM.

**Comment by maxlang** [comment]
Final visual change @kuanluo 

screen shot 2016-10-19 at 4 21 47 pm

**Comment by kuanluo** [comment]
I'd remove half of the empty space between "...sql terminal:" and the code block, so they are more connected.

**Comment by maxlang** [comment]
Final visual tweak, LGTM'd in slack:
screen shot 2016-10-19 at 4 40 40 pm

QA Checklist for this change:

- [ ] If data fails to load, show "error retrieving data" message.
- [ ] Do not allow saving while a previous save is in progress.
- [ ] While a save is in progress, show the "Saving..." message.
- [ ] If save fails, show the "Save failed." message.
- [ ] If the save succeeds, show the "Saved." message for 2s.
- [ ] If the email updates option hasn't ever been selected, it should be visible.
- [ ] If it has been selected, it should never be visible.
- [ ] If opt-in is selected, the cluster should be registered with the Cockroach Labs server.
- [ ] If opt-in is deselected, the cluster should be unregistered with the Cockroach Labs server.

**Comment by mrtracy** [comment]
Review status: 6 of 15 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/ui/app/containers/helpus.tsx, line 39 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KUYAm61JYFmfNq5sOJz:-KUYAm61JYFmfNq5sOK-:brqxkvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/927e9c3cb845021fb6fcce90a112f54719b5c6e0/pkg/ui/app/containers/helpus.tsx#L39)):*
> ```XML
>   }
> 
>   componentWillReceiveProps(props: HelpUsProps) {
> ```

I don' think this is called on the initial render.  Does this work if you navigate away from the page and then navigate back?  I think this only works because we depend on "loadUIData".

Also, why are we using 

---

*[pkg/ui/app/services/registrationService.spec.ts, line 50 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KUYbc44C37v8Ar8Yq7l:-KUYbc44C37v8Ar8Yq7m:b-ctoiz6) ([raw file](https://github.com/cockroachdb/cockroach/blob/927e9c3cb845021fb6fcce90a112f54719b5c6e0/pkg/ui/app/services/registrationService.spec.ts#L50)):*
> ```XML
>         // actionCreator callback. Instead we set them directly above.
>         // TODO(maxlang): It might be useful to mock uiData responses.
>         return { throws: new Error() };
> ```

Why is this necessary, instead of mocking the UIData response? Is it difficult to mock?  It seems like this is bypassing much of the code in a very odd, potentially error-prone way.

---

*[pkg/ui/app/services/registrationService.ts, line 31 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KUYX6mSEWkhQsGOeXPq:-KUYX6mSEWkhQsGOeXPr:b-qmqt1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/927e9c3cb845021fb6fcce90a112f54719b5c6e0/pkg/ui/app/services/registrationService.ts#L31)):*
> ```XML
>     if (state.uiData[KEY_HELPUS] && (state.uiData[KEY_HELPUS].saving || state.uiData[KEY_HELPUS].loading) ||
>       state.uiData[KEY_REGISTRATION_SYNCHRONIZED] && (state.uiData[KEY_REGISTRATION_SYNCHRONIZED].saving || state.uiData[KEY_REGISTRATION_SYNCHRONIZED].loading) ||
>       saving || errors >= ERROR_LIMIT) {
> ```

This is difficult to parse.  It is checking "loading" and "saving" for both of the keys in "neededKeys"; can we extract this into some sort of method, to tell if a UIData key is synchronized with CockroachDB?

I actually think this entire method could be broken cleanly in two for clarity and improved testing; `shouldSynchronize()` and `synchronize()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783)*

**Comment by maxlang** [comment]
I refactored a bunch, separating out the `registrationService` into a few different functions, each of which is more thoroughly tested. I also figured out the correct way to mock `GetUIDataResponse` objects and added a bunch more tests to the registration service and some to uiData.

---

Review status: 6 of 19 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[pkg/ui/app/containers/helpus.tsx, line 39 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KUYAm61JYFmfNq5sOJz:-KUrw9SC6oN86oouG47I:baycxsu) ([raw file](https://github.com/cockroachdb/cockroach/blob/927e9c3cb845021fb6fcce90a112f54719b5c6e0/pkg/ui/app/containers/helpus.tsx#L39)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> I don' think this is called on the initial render.  Does this work if you navigate away from the page and then navigate back?  I think this only works because we depend on "loadUIData".
> 
> Also, why are we using 
</details>
Yeah, this depends on `loadUIData` in the `componentWillMount`. I could also set it in `componentWillMount`, but figured I might as well wait for the freshest data.

Forget what your second question was.

---

*[pkg/ui/app/services/registrationService.spec.ts, line 50 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KUYbc44C37v8Ar8Yq7l:-KV7xorkxMtFxxi3_Hay:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/927e9c3cb845021fb6fcce90a112f54719b5c6e0/pkg/ui/app/services/registrationService.spec.ts#L50)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> Why is this necessary, instead of mocking the UIData response? Is it difficult to mock?  It seems like this is bypassing much of the code in a very odd, potentially error-prone way.
</details>
Done.

---

*[pkg/ui/app/services/registrationService.ts, line 31 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KUYX6mSEWkhQsGOeXPq:-KV7xnNNJNraD2OITfi3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/927e9c3cb845021fb6fcce90a112f54719b5c6e0/pkg/ui/app/services/registrationService.ts#L31)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> This is difficult to parse.  It is checking "loading" and "saving" for both of the keys in "neededKeys"; can we extract this into some sort of method, to tell if a UIData key is synchronized with CockroachDB?
> 
> I actually think this entire method could be broken cleanly in two for clarity and improved testing; `shouldSynchronize()` and `synchronize()`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-:-KV7xzdcEaUNs9TvcK-_:b7r9zds)*

**Comment by tamird** [comment]
Can you extract your second commit into a separate PR? The currently structure makes things rather hard to review since code is written in commit 1 and then rewritten in commit 2.

---

Reviewed 6 of 9 files at r9, 5 of 13 files at r10.
Review status: 11 of 19 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-:-KVApAa8oExSz-V0tAnE:b-2yigkr)*

**Comment by jess-edwards** [comment]
@maxlang Does this include fixing the HubSpot integration, or is that on a separate issue (if so, which one?)? 

@dianasaur323

**Comment by maxlang** [comment]
@tamird what about squashing them? The 2nd commit fixes issues with the first commit that I didn't want to commit independently.

@jess-edwards @dianasaur323 yes this is the hubspot integration fix.

---

Review status: 11 of 19 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-:-KVNgppXrtG-FGxQ-4Jr:b-sgyax1)*

**Comment by mrtracy** [comment]
I've reviewed this again, my LGTM stands. My concerns re: testability of the registration function have been addressed.

---

Review status: 10 of 19 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/ui/app/containers/helpus.tsx, line 39 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KUYAm61JYFmfNq5sOJz:-KVQh8RlrbYI-YkNRCdi:b-y20xb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/927e9c3cb845021fb6fcce90a112f54719b5c6e0/pkg/ui/app/containers/helpus.tsx#L39)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Yeah, this depends on `loadUIData` in the `componentWillMount`. I could also set it in `componentWillMount`, but figured I might as well wait for the freshest data.
> 
> Forget what your second question was.
</details>
What I'm saying is, I'm not sure if loadUIData() is guaranteed to trigger a redraw if the UI data is already loaded.

The second question was, why are we assigning props.optInAttributes to the react state of the component?  I believe you answered my question, that you use it to track temporary changes in the form before saving it.  That made sense to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-:-KVQkq4YugHiUMjl0R01:bk7ojky)*

**Comment by maxlang** [comment]
Review status: 10 of 19 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/ui/app/containers/helpus.tsx, line 39 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783#-KUYAm61JYFmfNq5sOJz:-KVQmG7nv8HWEBfdU0f-:bnqysjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/927e9c3cb845021fb6fcce90a112f54719b5c6e0/pkg/ui/app/containers/helpus.tsx#L39)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> What I'm saying is, I'm not sure if loadUIData() is guaranteed to trigger a redraw if the UI data is already loaded.
> 
> The second question was, why are we assigning props.optInAttributes to the react state of the component?  I believe you answered my question, that you use it to track temporary changes in the form before saving it.  That made sense to me.
</details>
Ah yes. loadUIData is guaranteed to trigger a redraw even if the data doesn't change because "loading" is a boolean in the props and that will briefly change to true.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9783)*

**Comment by maxlang** [comment]
@jess-edwards @dianasaur323 you should now start seeing registrations again when the next beta comes out.

**Comment by jess-edwards** [comment]
@maxlang Awesome. 

Can you give me a data dump of the email addresses currently trapped in - wherever it is they are trapped - and I will manually upload them to HubSpot?

**Pull request merged**
