### PR TITLE
catalog: pre-compute more column slices

### PR DESCRIPTION
**Pull request by postamar**
catalog: remove FullIndexColumnIDs
    
    Calls to this function can now be replaced with recently-added
    IndexFullColumns and IndexFullColumnDirections method calls on the table
    descriptor.
    
    Release note: None

    catalog: add Index*ColumnDirections methods to table descriptor
    
    This complements the previous commit which added Index*Column methods to
    catalog.TableDescriptor.
    
    Release note: None

    catalog: add Index*Columns methods to table descriptor
    
    These methods return the columns referenced in indexes as
    []catalog.Column slices.
    
    Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74638#-:-Mt4gpjz-CtDAsIM-jig:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/row/fetcher.go, line 469 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74638#-Mt4g9UPE4PAIvZJ6Zgx:-Mt4g9UPE4PAIvZJ6Zgy:b-7a0zsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a55f0d142c490a0a452316575edf7e056b14f86/pkg/sql/row/fetcher.go#L469)):*
> ```Go
> 	}
> 	for i, col := range columns {
> 		if col == nil || !col.Public() {
> ```

you could make this a nicer error in the case that the column is non-nil but non-public. Maybe `ObjectNotInPrerequisiteState` and provide the name of the column and/or the ID? I'm only pushing here because it appears this error shows up in the logic test for that funny case of trying to render a value for the conflict after a drop.  



_Code quote:_
```Go
		if col == nil || !col.Public() {
			return nil, fmt.Errorf("column does not exist")
		}
```

**Review by postamar — COMMENTED** [review]
Thanks for the review. As always, by precomputing these column slices, we're trading off increased overhead vs. ad-hoc allocations. @nvanbenschoten The microbenchmarks for `row` and friends probably are worth running again after this merges. If allocations are too high, what needs to be done is not revert this but instead:
- use these precomputed slices more often, instead of calls to `FindColumnWithID` and friends which look up columns by ID one at a time;
- altogether stop maintaining slices of column IDs in `row.tableInfo` and friends.
 
A lot of this code and these data structures predate the catalog interfaces altogether and can almost certainly be streamlined. I've not done it because I don't know if it's worth doing. I estimate that doing this will take 3.6 days of work: not great, not terrible.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74638#-:-Mt99hzd840JtnldzBhb:bc1jzoa)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

___
*[pkg/sql/row/fetcher.go, line 469 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74638#-Mt4g9UPE4PAIvZJ6Zgx:-Mt99UwQA6QrJliWmUAB:b8uu5z7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a55f0d142c490a0a452316575edf7e056b14f86/pkg/sql/row/fetcher.go#L469)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

you could make this a nicer error in the case that the column is non-nil but non-public. Maybe `ObjectNotInPrerequisiteState` and provide the name of the column and/or the ID? I'm only pushing here because it appears this error shows up in the logic test for that funny case of trying to render a value for the conflict after a drop.  
</blockquote></details>

Done, although I've decided not to add a pgcode. This code would end up overriding any other, which is what ended up happening in the logic test.

**Comment by nvanbenschoten** [comment]
> The microbenchmarks for row and friends probably are worth running again after this merges.

Why not run them before this merges?

```
go get github.com/nvanbenschoten/benchdiff

benchdiff --run='KV/Scan/SQL' ./pkg/sql/tests
```

**Comment by postamar** [comment]
It's that simple? I stupidly assumed it was going to be quite complicated. Sure, I'll do it!

**Comment by nvanbenschoten** [comment]
Yep! Microbenchmarks are nice and easy to run, measure, and iterate on (which is why https://github.com/cockroachdb/cockroach/pull/74443 is so great). Anything system-level that needs real VMs is more involved.

**Comment by postamar** [comment]
I ran this microbenchmark and noticed that the perf regression was statistically significant, in some cases exceeding 2% more allocations. I pushed another commit which basically does the same pre-computations but reuses the same backing slice when possible.

**Comment by ajwerner** [comment]
I wonder if this will hurt given we end up constructing this with the table descriptor each time. This is all more fodder for using leased descriptors with distsql

**Comment by postamar** [comment]
Thanks for the reviews. I'll go ahead and merge this on the assumption that we'll use the leased descriptors at some point. In fact, I've already hacked something to that effect and the results are very promising.

bors r+

**Comment by postamar** [comment]
c.f. https://github.com/cockroachdb/cockroach/pull/74722

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74638)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/colfetcher/cfetcher.go, line 447 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74638#-MtBmZOD95vwdzndbVtj:-MtBmZOD95vwdzndbVtk:bssco7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c1f347a1c00f6bc999e04402399d716826ef59f/pkg/sql/colfetcher/cfetcher.go#L447)):*
> ```Go
> 	needToDecodeDecimalKey := false
> 	for i, col := range fullColumns {
> 		if col == nil {
> ```

Saw this change when rebasing on top of master, and I'm confused by this block - when can `col` be `nil` here?

**Comment by postamar** [comment]
> when can col be nil here?

If the ID doesn't exist.

**Pull request merged**
