### PR TITLE
opt: calculate number of rows processed when costing joins

### LINKED ISSUE #34810: opt: take into account ON conditions for join costing
Repro:
Create the schema and statistics shown below, and then run the following query:
```
SELECT w, x, y, z
FROM wxyz
INNER JOIN abcde
ON w = a AND x = b AND y = c
WHERE w = 'foo' AND x = '2AB23800-06B1-4E19-A3BB-DF3768B808D2'
ORDER BY d
LIMIT 10;
```

EXPECTED: This query should use the `idx_abcd` index, because it's more selective.
ACTUAL: This query uses the `idx_abd` index.

The problem is that the coster does not take into account any remainder ON predicates. While `idx_abcd` has fewer remainder predicates, it is actually considered as _more_ expensive than `idx_abd`. To fix this, we'll need to incorporate remainder predicates into the cost estimation somehow.

```
CREATE TABLE abcde (
	a TEXT NOT NULL,
	b UUID NOT NULL,
	c UUID NOT NULL,
	d VARCHAR(255) NOT NULL,
	e TEXT NOT NULL,
	CONSTRAINT "primary" PRIMARY KEY (a, b, c),
	UNIQUE INDEX idx_abd (a, b, d),
	UNIQUE INDEX idx_abcd (a, b, c, d)
);

ALTER TABLE abcde INJECT STATISTICS '[
  {
    "columns": ["a"],
    "created_at": "2019-02-08 04:10:40.001179+00:00",
    "row_count": 250000,
    "distinct_count": 1
  },
  {
    "columns": ["b"],
    "created_at": "2019-02-08 04:10:40.119954+00:00",
    "row_count": 250000,
    "distinct_count": 2
  },
  {
    "columns": ["d"],
    "created_at": "2019-02-08 04:10:40.119954+00:00",
    "row_count": 250000,
    "distinct_count": 125000
  }
]';

CREATE TABLE wxyz (
	w TEXT NOT NULL,
	x UUID NOT NULL,
	y UUID NOT NULL,
	z TEXT NOT NULL,
	CONSTRAINT "primary" PRIMARY KEY (w, x, y),
	CONSTRAINT "foreign" FOREIGN KEY (w, x, y) REFERENCES abcde (a, b, c)
);

ALTER TABLE wxyz INJECT STATISTICS '[
  {
    "columns": ["w"],
    "created_at": "2019-02-08 04:10:40.001179+00:00",
    "row_count": 10000,
    "distinct_count": 1
  },
  {
    "columns": ["x"],
    "created_at": "2019-02-08 04:10:40.119954+00:00",
    "row_count": 10000,
    "distinct_count": 1
  },
  {
    "columns": ["y"],
    "created_at": "2019-02-08 04:10:40.119954+00:00",
    "row_count": 10000,
    "distinct_count": 2500
  }
]';
```

### PR DESCRIPTION
**Pull request by rytaft**
This PR updates the costing of joins to take into account the number of
rows processed by the operator. This number may be larger than the
number of output rows if an additional filter is applied as part of the
ON condition that is not used to determine equality
columns for the join.

For example, consider the query
  `SELECT * FROM abc JOIN def ON a = e AND b = 3;`

Assuming there is no index on b, if a lookup join is used to execute this
query, the number of rows processed is actually the same as the query
  `SELECT * FROM abc JOIN def ON a = e;`

The difference is that the filter b=3 must also be applied to every row in
the first query. The coster now takes this into account when determining
the cost of joins.

Fixes #34810

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
None of the plans changed in TPC-C or TPC-H, so I wouldn't expect perf to change there.

This change should fix some cases where we are choosing a lookup join when we shouldn't be, or where we are choosing the wrong index for the lookup join. @RaduBerinde mentioned that this is currently a problem for some FK checks, so performance should improve in those cases.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/xform/testdata/external/tpcc, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-LnJ0FBT5qMyfmSwRd3W:-LnJ0FBT5qMyfmSwRd3X:bl7c5oq) ([raw file](https://github.com/cockroachdb/cockroach/blob/32d9973d220e7b91a6fe438a3756f4eb9cfb9549/pkg/sql/opt/xform/testdata/external/tpcc#L199)):*
> ```
>  └── f-k-checks
>       └── f-k-checks-item: order(o_w_id,o_d_id,o_c_id) -> customer(c_w_id,c_d_id,c_id)
>            └── anti-join (lookup customer@customer_idx)
> ```

I would expect this to change - it should use the FK index which has all three columns..

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40248)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/xform/testdata/external/tpcc, line 735 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-LnJ5_NXEP4_aWriTYX3:-LnJ5_NY5glwhMO5NgJ4:bl29u53) ([raw file](https://github.com/cockroachdb/cockroach/blob/32d9973d220e7b91a6fe438a3756f4eb9cfb9549/pkg/sql/opt/xform/testdata/external/tpcc#L735)):*
> ```
>  └── f-k-checks
>       ├── f-k-checks-item: order_line(ol_w_id,ol_d_id,ol_o_id) -> order(o_w_id,o_d_id,o_id)
>       │    └── anti-join (lookup order@order_idx)
> ```

Another instance.
___
*[pkg/sql/opt/xform/testdata/external/tpcc, line 1085 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-LnJ5gDv2hEuM9ByiEGe:-LnJ5gDv2hEuM9ByiEGf:bl29u53) ([raw file](https://github.com/cockroachdb/cockroach/blob/32d9973d220e7b91a6fe438a3756f4eb9cfb9549/pkg/sql/opt/xform/testdata/external/tpcc#L1085)):*
> ```
>  └── f-k-checks
>       ├── f-k-checks-item: history(h_c_w_id,h_c_d_id,h_c_id) -> customer(c_w_id,c_d_id,c_id)
>       │    └── anti-join (lookup customer@customer_idx)
> ```

Another instance.

**Review by justinj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40248)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 2293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-LnJ3aJgD9-q_e1YOiLF:-LnJ3aJh98Bs5nqUZGwQ:b-tqttfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/32d9973d220e7b91a6fe438a3756f4eb9cfb9549/pkg/sql/opt/memo/statistics_builder.go#L2293)):*
> ```Go
> 		// Otherwise, we need to determine the row count of the join before the
> 		// ON conditions are applied.
> 		withoutOn := e.Memo().MemoizeLookupJoin(t.Input, nil /* on */, &t.LookupJoinPrivate)
> ```

is `nil` acceptable for empty List expressions? I had vaguely thought that they should always be non-nil, but maybe it doesn't matter

also nit: `s/on/On/`

**Review by rytaft — COMMENTED** [review]
The problem seems to be that we weren't calculating stats correctly for semi or anti joins. I've added another commit to fix those stats. 

Two plans for TPC-H changed, so I need to update the stats quality tests for those. But in the mean time, I figured I would push this commit to see if there is any feedback. PTAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-:-LnO1Krp4PHqjIMBY12d:b-menood)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 2293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-LnJ3aJgD9-q_e1YOiLF:-LnO2FCJ6hhyKrMPq9nw:b-ovd1fq) ([raw file](https://github.com/cockroachdb/cockroach/blob/32d9973d220e7b91a6fe438a3756f4eb9cfb9549/pkg/sql/opt/memo/statistics_builder.go#L2293)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

is `nil` acceptable for empty List expressions? I had vaguely thought that they should always be non-nil, but maybe it doesn't matter

also nit: `s/on/On/`
</blockquote></details>

Seems like using `nil` isn't a problem, since `len()` of a `nil` list is 0.

What does `s/on/On/` apply to? The name of the parameter in `MemoizeLookupJoin` is `on`, not `On`...
___
*[pkg/sql/opt/xform/testdata/external/tpcc, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-LnJ0FBT5qMyfmSwRd3W:-LnO19LCAGM-bu71PWuN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/32d9973d220e7b91a6fe438a3756f4eb9cfb9549/pkg/sql/opt/xform/testdata/external/tpcc#L199)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I would expect this to change - it should use the FK index which has all three columns..
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/external/tpcc, line 735 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-LnJ5_NXEP4_aWriTYX3:-LnO1B9r78ywEWqvTmgn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/32d9973d220e7b91a6fe438a3756f4eb9cfb9549/pkg/sql/opt/xform/testdata/external/tpcc#L735)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Another instance.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/external/tpcc, line 1085 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-LnJ5gDv2hEuM9ByiEGe:-LnO1DJv57cnQ6fOkTy9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/32d9973d220e7b91a6fe438a3756f4eb9cfb9549/pkg/sql/opt/xform/testdata/external/tpcc#L1085)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Another instance.
</blockquote></details>

Done.

**Review by RaduBerinde — COMMENTED** [review]
Great work! The updated FK plans for TPCC look great!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-:-LnOc-BQ85a07FG2XhSs:b-1sr5v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 909 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-LnOZcjT8itfbVHOyEw0:-LnOZcjT8itfbVHOyEw1:b-fge56o) ([raw file](https://github.com/cockroachdb/cockroach/blob/28d0a38564da12bf09e736ba210ca8fa5910f52b/pkg/sql/opt/memo/statistics_builder.go#L909)):*
> ```Go
> 	// -----------------------------------
> 	s.RowCount = leftStats.RowCount * rightStats.RowCount
> 	inputRowCount := s.RowCount
> ```

This could use a comment, it's not easy to figure out what this value actually means.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 915 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-LnOZiqcDJ1IhG4z9ZvN:-LnOZiqcDJ1IhG4z9ZvO:biko9il) ([raw file](https://github.com/cockroachdb/cockroach/blob/28d0a38564da12bf09e736ba210ca8fa5910f52b/pkg/sql/opt/memo/statistics_builder.go#L915)):*
> ```Go
> 		// calculations. It will be fixed below.
> 		s.RowCount = leftStats.RowCount
> 		inputRowCount = s.RowCount
> ```

[nit] = leftStats.RowCount is more clear (it initially seemed like a no-op)
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1003 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-LnOa8Hl4PcIQxNIekM1:-LnOa8Hl4PcIQxNIekM2:bf3rwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/28d0a38564da12bf09e736ba210ca8fa5910f52b/pkg/sql/opt/memo/statistics_builder.go#L1003)):*
> ```Go
> 	}
> 
> 	// Fix the stats for anti join.
> ```

Seems like `colStatJoin` would need some of this logic too?
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1006 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-LnOZ1fM8gXFmnLV3Yaf:-LnOZ1fM8gXFmnLV3Yag:b-t2o17o) ([raw file](https://github.com/cockroachdb/cockroach/blob/28d0a38564da12bf09e736ba210ca8fa5910f52b/pkg/sql/opt/memo/statistics_builder.go#L1006)):*
> ```Go
> 	switch h.joinType {
> 	case opt.AntiJoinOp, opt.AntiJoinApplyOp:
> 		s.RowCount = max(inputRowCount-s.RowCount, epsilon)
> ```

Would be clearer if we just used `leftStats.RowCount - s.RowCount` directly (that's the formula one would expect)
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1013 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-LnObX4X4x-Zpe_1wtUb:-LnObX4X4x-Zpe_1wtUc:b-6j5pt5) ([raw file](https://github.com/cockroachdb/cockroach/blob/28d0a38564da12bf09e736ba210ca8fa5910f52b/pkg/sql/opt/memo/statistics_builder.go#L1013)):*
> ```Go
> 
> 			// Distinct count is tricky for anti-joins. This is a rough estimate,
> 			// accounting for the way distinct counts are calculated above.
> ```

[nit] can you expand on this? Not sure what aspect of the way we calculate distinct counts above this formula stems from. Also, seems like the total and semi-join row count would play a role, but can't say I can come up with a formula that's reasonable.
___
*[pkg/sql/opt/xform/coster.go, line 403 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-LnOdU3x38iJAb0prYZk:-LnOdU3x38iJAb0prYZl:bju3ly4) ([raw file](https://github.com/cockroachdb/cockroach/blob/28d0a38564da12bf09e736ba210ca8fa5910f52b/pkg/sql/opt/xform/coster.go#L403)):*
> ```Go
> 	// Add a cost if we have to evaluate an ON condition on every row. The more
> 	// leftover conditions, the more expensive it should be. We want to
> 	// differentiate between two lookup joins where one uses only a subset of the
> ```

This comment no longer holds (your change should fix this example).
___
*[pkg/sql/opt/xform/coster.go, line 411 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-LnOe8WL6WJvYTtyqzRk:-LnOe8WMBc8jB3IsEEaM:b-io4gyq) ([raw file](https://github.com/cockroachdb/cockroach/blob/28d0a38564da12bf09e736ba210ca8fa5910f52b/pkg/sql/opt/xform/coster.go#L411)):*
> ```Go
> 	// then discarded).
> 	perRowCost += cpuCostFactor * memo.Cost(len(join.On))
> 	// We also add a constant "setup" cost per ON condition. Without this, the
> ```

This hacky "setup" adjustment to the cost shouldn't be needed anymore. The first one (line above) shouldn't be necessary either with your change, though I don't see a problem with keeping it (especially if removing it changes plans that we're unsure about). Strictly speaking, it's correct to account for running the filters, but then the other join types should also account for that, and Select should account for it similarly (it doesn't look at how many filters we have to evaluate).

**Review by rytaft — COMMENTED** [review]
I've updated the TPC-H stats quality tests. Here are the performance changes (averaged over 3 runs of each, standard deviation is less than 1% for all measurements):

```
Q18
----
old     new    change
14.36s  9.05s  -36.97%

Q22
----
old      new      change
742.1ms  833.6ms  +12.34%
```

As shown above, Q18 improved by 37% but Q22 regressed by 12%.

I also further improved the costing and stats of semi/anti joins.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-:-LnT10dJ7wMtADwct2kT:b-tzhmvd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 909 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-LnOZcjT8itfbVHOyEw0:-LnT2z6aEpZgFNjOFkM-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/28d0a38564da12bf09e736ba210ca8fa5910f52b/pkg/sql/opt/memo/statistics_builder.go#L909)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This could use a comment, it's not easy to figure out what this value actually means.
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 915 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-LnOZiqcDJ1IhG4z9ZvN:-LnT31sDBkQcy6xesOFG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/28d0a38564da12bf09e736ba210ca8fa5910f52b/pkg/sql/opt/memo/statistics_builder.go#L915)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] = leftStats.RowCount is more clear (it initially seemed like a no-op)
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1003 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-LnOa8Hl4PcIQxNIekM1:-LnT3IUyBZQdmhiJgmfD:b-cdpekj) ([raw file](https://github.com/cockroachdb/cockroach/blob/28d0a38564da12bf09e736ba210ca8fa5910f52b/pkg/sql/opt/memo/statistics_builder.go#L1003)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Seems like `colStatJoin` would need some of this logic too?
</blockquote></details>

It shouldn't need any change since we're setting the selectivity here so it's correct for anti joins. For semi/anti joins, `colStatJoin` just applies the selectivity to the given column.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1006 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-LnOZ1fM8gXFmnLV3Yaf:-LnT3haV5XBna1mTc-R0:bs7wumb) ([raw file](https://github.com/cockroachdb/cockroach/blob/28d0a38564da12bf09e736ba210ca8fa5910f52b/pkg/sql/opt/memo/statistics_builder.go#L1006)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Would be clearer if we just used `leftStats.RowCount - s.RowCount` directly (that's the formula one would expect)
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1013 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-LnObX4X4x-Zpe_1wtUb:-LnjfQkD51Px6YaloxBE:b-xk7qdu) ([raw file](https://github.com/cockroachdb/cockroach/blob/28d0a38564da12bf09e736ba210ca8fa5910f52b/pkg/sql/opt/memo/statistics_builder.go#L1013)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] can you expand on this? Not sure what aspect of the way we calculate distinct counts above this formula stems from. Also, seems like the total and semi-join row count would play a role, but can't say I can come up with a formula that's reasonable.
</blockquote></details>

I just removed this -- using the selectivity is easier and seems to be about as accurate.
___
*[pkg/sql/opt/xform/coster.go, line 403 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-LnOdU3x38iJAb0prYZk:-LnjhL3k1mduVFYG3gzX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/28d0a38564da12bf09e736ba210ca8fa5910f52b/pkg/sql/opt/xform/coster.go#L403)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This comment no longer holds (your change should fix this example).
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/coster.go, line 411 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-LnOe8WL6WJvYTtyqzRk:-LnjhOlX-MhM34uIFUMi:b-mg46sw) ([raw file](https://github.com/cockroachdb/cockroach/blob/28d0a38564da12bf09e736ba210ca8fa5910f52b/pkg/sql/opt/xform/coster.go#L411)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This hacky "setup" adjustment to the cost shouldn't be needed anymore. The first one (line above) shouldn't be necessary either with your change, though I don't see a problem with keeping it (especially if removing it changes plans that we're unsure about). Strictly speaking, it's correct to account for running the filters, but then the other join types should also account for that, and Select should account for it similarly (it doesn't look at how many filters we have to evaluate). 
</blockquote></details>

Unfortunately we still need the setup cost to handle the case of a very small row count. When the row count is less than one, we cannot calculate the selectivity of each filter, so we need this hack to discriminate between fully covering indexes and partially covering indexes.

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Thanks for fixing this!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-:-LnrlnHu8eT1iqRoCVCq:b-mws4q9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/testdata/lookup_join, line 247 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-Lnrk550ET3f1sy5H4ic:-Lnrk4Dg8ABWEe2R-LqL:b-rkceys) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4272c86d5c2fb37b9737f9a5047e47def3277c0/pkg/sql/opt/exec/execbuilder/testdata/lookup_join#L247)):*
> ```
> NULL       NULL     {5}       5
> 
> # TODO(radu): this doesn't seem to be a lookup join, but it should be.
> ```

We can remove this now :)
___
*[pkg/sql/opt/memo/statistics_builder.go, line 2358 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-Lnrl8j1DSs-1NvUV4AZ:-Lnrl8j2-S9H_p_lt2m5:b65yk5d) ([raw file](https://github.com/cockroachdb/cockroach/blob/1014541fdedb442c804c2453d707a753f141d59c/pkg/sql/opt/memo/statistics_builder.go#L2358)):*
> ```Go
> 		}
> 
> 		// Otherwise, we need to determine the row count of the join before the
> ```

[nit] not clear anymore what "otherwise" refers to

**Review by rytaft — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-:-LnsP_9sA5Pjgx1dYgtF:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj and @RaduBerinde)

___
*[pkg/sql/opt/exec/execbuilder/testdata/lookup_join, line 247 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-Lnrk550ET3f1sy5H4ic:-LnsG_yZAxt6FSL7y7pD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4272c86d5c2fb37b9737f9a5047e47def3277c0/pkg/sql/opt/exec/execbuilder/testdata/lookup_join#L247)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We can remove this now :)
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 2358 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40248#-Lnrl8j1DSs-1NvUV4AZ:-LnsGo2i0bFZqWrcTyB5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1014541fdedb442c804c2453d707a753f141d59c/pkg/sql/opt/memo/statistics_builder.go#L2358)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] not clear anymore what "otherwise" refers to
</blockquote></details>

Done.

**Pull request merged**
