### PR TITLE
sql/stats: conversion of datums to and from quantile function values

### PR DESCRIPTION
**Pull request by michae2**
To predict histograms in statistics forecasts, we will use linear
regression over quantile functions. (Quantile functions are another
representation of histogram data, in a form more amenable to statistical
manipulation.)

The conversion of histograms to quantile functions will require
conversion of histogram bounds (datums) to quantile values (float64s).
And likewise, the inverse conversion from quantile functions back to
histograms will require the inverse conversion of float64 quantile
values back to datums. These conversions are a little different from our
usual SQL conversions in `eval.PerformCast`, so we add them to a new
quantile file in the `sql/stats` module.

This code was originally part of #77070 but has been pulled out to
simplify that PR. A few changes have been made:
- `histogramValue` has been renamed to `FromQuantileValue`.
- Support for `DECIMAL`, `TIME`, `TIMETZ`, and `INTERVAL` has been
  dropped. Clamping these types in `FromQuantileValue` was too complex
  for the first iteration of statistics forecasting. We expect the
  overwhelming majority of ascending keys to use `INT` or `TIMESTAMP`
  types.
- Bugs in `FLOAT4`, `TIMESTAMP` and `TIMESTAMPTZ` conversions have been
  fixed.
- We're now clamping timestamps to slightly tighter bounds to avoid the
  problems with infinite timestamps (see #41564).

Assists: #79872

Release note: None

### CODE REVIEW

**Review by rharding6373 — CHANGES_REQUESTED** [review]
Thanks for breaking this out! Looks pretty good, mostly just some nits.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83123#-:-N58DVxD19vWFONeMnHd:b-hjftxg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

___
*[`-- commits` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83123#-N58DKna9bDeRuh30Hr6):*
TIL Assists is a keyword.
___
*[`pkg/sql/stats/quantile.go` line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83123#-N58C9Ku2jtlw-2n0-dZ:-N58C9Ku2jtlw-2n0-d_:b-jij918) ([raw file](https://github.com/cockroachdb/cockroach/blob/1943583663722a976ee66c325f46d0f99118f58c/pkg/sql/stats/quantile.go#L120)):*
> ```Go
> 				return tree.NewDInt(tree.DInt(math.MinInt32)), nil
> 			}
> 			if i >= math.MaxInt16 {
> ```

MaxInt32?

Could use another clamping test case.
___
*[`pkg/util/timeutil/pgdate/pgdate.go` line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83123#-N586WK13y4goDVAS69o:-N586WK2AIwv8j4aGUvE:b-i3epcx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1943583663722a976ee66c325f46d0f99118f58c/pkg/util/timeutil/pgdate/pgdate.go#L148)):*
> ```Go
> func MakeDateFromPGEpochClampFinite(days int32) Date {
> 	if days < lowDays {
> 		return Date{days: lowDays}
> ```

Why can't we just return `LowDate` here?
___
*[`pkg/sql/stats/quantile_test.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83123#-N587IZM5mtoHnEd-NZo:-N587IZM5mtoHnEd-NZp:bj6tczt) ([raw file](https://github.com/cockroachdb/cockroach/blob/1943583663722a976ee66c325f46d0f99118f58c/pkg/sql/stats/quantile_test.go#L32)):*
> ```Go
> 		val float64
> 		err bool
> 		res tree.Datum
> ```

There doesn't seem to be a test case that populates `res`. Is that intentional? I infer from below that we always expect the roundtrip to equal `dat`, but in that case I think it's better to remove this and just compare to the original `dat` below.

**Review by michae2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83123)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/stats/quantile.go` line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83123#-N58C9Ku2jtlw-2n0-dZ:-N5Dse9H4PeuVnE4Q8Dz:b-4wtmdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1943583663722a976ee66c325f46d0f99118f58c/pkg/sql/stats/quantile.go#L120)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

MaxInt32?

Could use another clamping test case.
</blockquote></details>

Gaaaah! Good catch! Done, and added more test cases.
___
*[`pkg/util/timeutil/pgdate/pgdate.go` line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83123#-N586WK13y4goDVAS69o:-N5DsiYo1_x6lbXhfV9y:b-4k0685) ([raw file](https://github.com/cockroachdb/cockroach/blob/1943583663722a976ee66c325f46d0f99118f58c/pkg/util/timeutil/pgdate/pgdate.go#L148)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Why can't we just return `LowDate` here?
</blockquote></details>

Good point! Done.
___
*[`pkg/sql/stats/quantile_test.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83123#-N587IZM5mtoHnEd-NZo:-N5DsmYeCF0rEdZOCuAX:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/1943583663722a976ee66c325f46d0f99118f58c/pkg/sql/stats/quantile_test.go#L32)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

There doesn't seem to be a test case that populates `res`. Is that intentional? I infer from below that we always expect the roundtrip to equal `dat`, but in that case I think it's better to remove this and just compare to the original `dat` below.
</blockquote></details>

Good point, done.

**Comment by michae2** [comment]
Bazel CI failures are just flakes. This is RFAL.

**Review by yuzefovich — APPROVED** [review]
Nice work! I have some nits, but it :lgtm:

Another suggestion would be to write a randomized test for round-tripping thought the quantile functions, but it doesn't have to be in this PR, so a TODO will suffice.

> Reviewed 1 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83123#-:-N6GrtaH-Bd1qzqdQyPY:bm3mf38)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @rharding6373)

___
*[`pkg/sql/stats/quantile.go` line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83123#-N6GpbsH4zsE3cMDI_2v:-N6GpbsH4zsE3cMDI_2w:bvbrxca) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7f1d4081aa1d1060566154ab809a6f8afe96d13/pkg/sql/stats/quantile.go#L112)):*
> ```Go
> 		case 16:
> 			if i <= math.MinInt16 {
> 				return tree.NewDInt(tree.DInt(math.MinInt16)), nil
> ```

nit: for consistency with other types below maybe update `i` in-place to have only a single `return` per type?
___
*[`pkg/sql/stats/quantile.go` line 155 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83123#-N6Gq1uE40BZCyShD8jx:-N6Gq1uF3DJI9yrpglww:bfd9f7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7f1d4081aa1d1060566154ab809a6f8afe96d13/pkg/sql/stats/quantile.go#L155)):*
> ```Go
> 		// Then clamp to pgdate.Date.
> 		return tree.NewDDate(pgdate.MakeDateFromPGEpochClampFinite(int32(days))), nil
> 	case types.TimestampFamily:
> ```

nit: cases for Timestamp and TimestampTZ look exactly the same, with one line difference, maybe squash them?
___
*[`pkg/sql/stats/quantile_test.go` line 294 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83123#-N6GrIg2AV_0NVvZE5Hm:-N6GrIg2AV_0NVvZE5Hn:b-fk31m1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7f1d4081aa1d1060566154ab809a6f8afe96d13/pkg/sql/stats/quantile_test.go#L294)):*
> ```Go
> }
> 
> // Test conversions from quantile value to datum and back. TestToQuantileValue
> ```

nit: consider renaming the tests to something like `TestQuantileValueRoundTrip` and `TestQuantileValueRoundTripOverflow`. When I started reading the code in this file I was confused why for `TestToQuantileValue` test we would not do the whole round trip.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Another suggestion would be to write a randomized test for round-tripping thought the quantile functions

+1

> Reviewed 1 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83123#-:-N6Iri4U03RqdvPq8J8E:bta0rs7)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @rharding6373)

___
*[`pkg/sql/stats/quantile.go` line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83123#-N6IsZTQ6SxoZ9pmbAoG:-N6IsZTQ6SxoZ9pmbAoH:bf5sbcp) ([raw file](https://github.com/cockroachdb/cockroach/blob/73db7dbaf8176733e1d75d8078a8e9f499636f32/pkg/sql/stats/quantile.go#L75)):*
> ```Go
> 			return 0, tree.ErrFloatOutOfRange
> 		}
> 		return float64(v.Unix()) + float64(v.Nanosecond())*1e-9, nil
> ```

Doesn't seem like this will round-trip since the location isn't included here. Is there any possible issue with that?

**Review by michae2 — COMMENTED** [review]
Good suggestion. I added a TODO and will do that in another PR. TFTRs!

bors r=yuzefovich,rytaft

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83123#-:-N6M4r4R5YX8yU5Lhmqh:b1hiod6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner, @rharding6373, @rytaft, and @yuzefovich)

___
*[`pkg/sql/stats/quantile.go` line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83123#-N6IsZTQ6SxoZ9pmbAoG:-N6M4zCP9326AuGQiJBf:brsnrc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/73db7dbaf8176733e1d75d8078a8e9f499636f32/pkg/sql/stats/quantile.go#L75)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Doesn't seem like this will round-trip since the location isn't included here. Is there any possible issue with that?
</blockquote></details>

My understanding is that `TIMESTAMPTZ` doesn't actually store a location when written to disk (and neither does `TIMESTAMP`). When we decode them, the `time.Time` in the datum has nil location. When comparing, casting, and printing, we assume that `TIMESTAMPTZ` is in the session time zone and `TIMESTAMP` is UTC, and make adjustments to the `time.Time` to account for these assumptions.

So, I believe in histograms we can treat them the same way as each other, because they are "timezoneless" until comparing, casting, or printing.
___
*[`pkg/sql/stats/quantile.go` line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83123#-N6GpbsH4zsE3cMDI_2v:-N6MEMPY6-o556yJt1zo:blresdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/73db7dbaf8176733e1d75d8078a8e9f499636f32/pkg/sql/stats/quantile.go#L112)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: for consistency with other types below maybe update `i` in-place to have only a single `return` per type?
</blockquote></details>

Done. Had to special case `MaxInt64`.
___
*[`pkg/sql/stats/quantile.go` line 155 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83123#-N6Gq1uE40BZCyShD8jx:-N6MEY6PE-xi8MF2ixsK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/73db7dbaf8176733e1d75d8078a8e9f499636f32/pkg/sql/stats/quantile.go#L155)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: cases for Timestamp and TimestampTZ look exactly the same, with one line difference, maybe squash them?
</blockquote></details>

Done.
___
*[`pkg/sql/stats/quantile_test.go` line 294 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83123#-N6GrIg2AV_0NVvZE5Hm:-N6ME_Sk7baiQ9V7W7qh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/73db7dbaf8176733e1d75d8078a8e9f499636f32/pkg/sql/stats/quantile_test.go#L294)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: consider renaming the tests to something like `TestQuantileValueRoundTrip` and `TestQuantileValueRoundTripOverflow`. When I started reading the code in this file I was confused why for `TestToQuantileValue` test we would not do the whole round trip.
</blockquote></details>

Done.

**Review by mgartner — APPROVED** [review]
Nicely done!

> Reviewed 1 of 5 files at r1, 1 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83123#-:-N6Nnh1O8AscC0owdp7Q:b-ao1qb6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rharding6373 and @rytaft)

___
*[`-- commits` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83123#-N58DKna9bDeRuh30Hr6):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

TIL Assists is a keyword.
</blockquote></details>

It's not a keyword: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

Using a non-keyword like "assists" or "informs" is a way to link to the issue without auto-closing it when the PR is merged.

**Comment by michae2** [comment]
Failing a linter.

bors r-

**Comment by michae2** [comment]
bors r=yuzefovich,rytaft,mgartner

**Pull request merged**
