### PR TITLE
sql, auditloggingccl: consider BEGIN's nil txn when getting MemberOfWithAdminOption

### LINKED ISSUE #123592: sql: consider BEGIN's nil txn when getting MemberOfWithAdminOption
**Describe the problem**
In https://github.com/cockroachdb/cockroach/pull/109655, we stopped using the txn id of a previously executed txn for `BEGIN`s. This change meant that `BEGIN` will be logged with no transaction ID. The logic behind `initializeReducedAuditConfig` does not have this assumption; causing the following telemetry logs:

image

**To Reproduce**
I was able to repro this on 23.2 using the following:

```
-- set enterprise license
root@localhost:26257/defaultdb> SET CLUSTER SETTING sql.log.user_audit = 'audit_role ALL';                                                                        
SET CLUSTER SETTING

Time: 36ms total (execution 36ms / network 0ms)

root@localhost:26257/defaultdb> SET CLUSTER SETTING sql.log.user_audit.reduced_config.enabled = true;
SET CLUSTER SETTING

Time: 36ms total (execution 36ms / network 0ms)

-- 2 explicit txns
```

Jira issue: CRDB-38414

Epic CRDB-37763

### PR DESCRIPTION
**Pull request by annrpom**
In https://github.com/cockroachdb/cockroach/pull/109655, we stopped using the transaction id of a previously executed
transaction for `BEGIN`s. This change meant that `BEGIN` will be logged
with no transaction id. This led to logs related to cluster setting
`sql.log.user_audit.reduced_config.enabled` spewing error messages about
a nil transaction (since the logic behind said cluster setting requires
us to call on `MemberOfWithAdminOption` -- which uses a transaction for
its lookup). This patch ensures that we create an internal transaction
before we perform the `MemberOfWithAdminOption` lookup to handle the
nil BEGIN statement case.

Epic: none
Fixes: https://github.com/cockroachdb/cockroach/issues/123592

Release note: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
nice! could you add a test case to `TestReducedAuditConfig` to make sure there is a regression test?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123599#-:-NxDo-Hb-W037E1rCtfM:brh0gwm)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123599)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @xinhaoz)

___
*[`pkg/ccl/auditloggingccl/audit_logging_test.go` line 479 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/123599#-NxEFOPZ6YyHSe3QDjR8:-NxEFOPZ6YyHSe3QDjR9:b-xi6jdo) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff72cb2936f3a9a8286d413c684ab430c2da2ce1/pkg/ccl/auditloggingccl/audit_logging_test.go#L479)):*
> ```Go
> 		math.MaxInt64,
> 		10000,
> 		regexp.MustCompile(`error getting user role memberships`),
> ```

i may not be following this. it looks like this is asserting that the error is present. shouldn't we instead assert that we can successfully find the audit logs?

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123599)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @xinhaoz)

___
*[`pkg/ccl/auditloggingccl/audit_logging_test.go` line 479 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/123599#-NxEFOPZ6YyHSe3QDjR8:-NxEFiK3ELLC1l6UmuEK:b-6tgogc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff72cb2936f3a9a8286d413c684ab430c2da2ce1/pkg/ccl/auditloggingccl/audit_logging_test.go#L479)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i may not be following this. it looks like this is asserting that the error is present. shouldn't we instead assert that we can successfully find the audit logs?
</blockquote></details>

we have a `if len(entries) != 0` below to assert that we are not getting this error message -- i guess this test is too "on the dot"? would it be better to assert that we can successfully find the audit logs

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123599)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @xinhaoz)

___
*[`pkg/ccl/auditloggingccl/audit_logging_test.go` line 479 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/123599#-NxEFOPZ6YyHSe3QDjR8:-NxIXdmZCR8xGES-YWZo:b-k0qoyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/45ecee740c222aeb95d937e609900d41ebfd521f/pkg/ccl/auditloggingccl/audit_logging_test.go#L479)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

we have a `if len(entries) != 0` below to assert that we are not getting this error message -- i guess this test is too "on the dot? would it be better to assert that we can successfully find the audit logs
</blockquote></details>

ah i see, i missed that. no i think it's fine to keep the check that there's no error. but yeah, we should also have a check that we can find the correct audit logs, since that's the feature that users will want to be working.

**Comment by xinhaoz** [comment]
I've found using [log interceptors](https://github.com/cockroachdb/cockroach/blob/045acd250684d5ca2497478e34a84c4ad1d5699b/pkg/util/log/intercept.go#L47) to be helpful for logging testing. It gives you a bit more control than fetching entries matching a regex. Just thought I'd share in case it could be of use here.

**Review by annrpom — COMMENTED** [review]
oo thank you for the pointer!! i'll stick with following what the rest of `TestReducedAuditConfig` does for now, but i'll keep this suggestion in the back of my mind

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123599#-:-NxKFSV28bMVO2BLVhMN:bsh93tx)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @xinhaoz)

___
*[`pkg/ccl/auditloggingccl/audit_logging_test.go` line 479 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/123599#-NxEFOPZ6YyHSe3QDjR8:-NxEGBbk50js_abPbfui:bxvc2r3) ([raw file](https://github.com/cockroachdb/cockroach/blob/45ecee740c222aeb95d937e609900d41ebfd521f/pkg/ccl/auditloggingccl/audit_logging_test.go#L479)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ah i see, i missed that. no i think it's fine to keep the check that there's no error. but yeah, we should also have a check that we can find the correct audit logs, since that's the feature that users will want to be working.
</blockquote></details>

that makes sense -- done ; the presence of a BEGIN is the same thing as not getting the nil txn error for this regression (so i omitted it in favor of non-redundancy (is that a real word?))

**Review by rafiss — APPROVED** [review]
lgtm! could you make sure it has the appropriate backport labels?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123599#-:-NxP0XLP9p0P9qdIYF5i:bjkxh08)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

**Comment by annrpom** [comment]
TFTR! ('-')7 ! i'll take care of backporting if that's necessary

bors r=rafiss

**Comment by annrpom** [comment]
blathers backport 24.1 23.2

**Pull request merged**
