### PR TITLE
ui: fill out db/table pages

### PR DESCRIPTION
**Pull request by maxlang**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9621)

### CODE REVIEW

**Comment by maxlang** [comment]
Database info filled out:
screen shot 2016-09-29 at 2 08 21 pm

Table info filled out:
screen shot 2016-09-29 at 2 23 47 pm

**Comment by petermattis** [comment]
Are we supporting fractional bytes (re: `448.0 B`)?

**Comment by mrtracy** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[ui/app/containers/databases/databaseDetails.tsx, line 193 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9621#-KSwqDvoqa5KS5H-8o0X:-KSwqDvoqa5KS5H-8o0Y:btxg1vx) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc549e88a2190575bbf4b11c30b277bdf4dbbec7/ui/app/containers/databases/databaseDetails.tsx#L193)):*
> ```XML
>               title: "Last Modified By",
>               cell: (tableInfo) => {
>                 let lastEvent = _.find(sortedEvents, (e) => e.target_id.toNumber() === tableInfo.id);
> ```

I think that table descriptor IDs may be able to overlap with store IDs and node IDs. I think you need to make sure that e.event_type is within an expected set.

---

*[ui/app/containers/databases/databaseDetails.tsx, line 248 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9621#-KSwqqOSdYZtULbd06Av:-KSwqqOTlojDbiq_jO3X:b-yh4x0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc549e88a2190575bbf4b11c30b277bdf4dbbec7/ui/app/containers/databases/databaseDetails.tsx#L248)):*
> ```XML
> );
> 
> let sortedEvents = (state: AdminUIState): Event[] => _.sortBy(state.cachedData.events.data && state.cachedData.events.data.events, (e) => TimestampToMoment(e.timestamp));
> ```

This should be a selector itself;  You should only re-sort if state.cachedData.events.data changes. If possible, you should also share the selector (and the eventCounts selector) between the database page and the tables page. We haven't yet established where to place a shared selector, but I'm guessing it just goes in the redux module for events.

I also don't think you need to convert the timestamps to moments in order to sort them; the original timestamps will also be in the same order, won't they?

Finally: does this not come back from the server already sorted?  Perhaps we should add an ORDER BY clause to the query and let the server take care of it.

---

*[ui/app/containers/databases/databaseList.tsx, line 52 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9621#-KSwrGgO9NYAPbareEGA:-KSwrGgO9NYAPbareEGB:bh8ramg) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc549e88a2190575bbf4b11c30b277bdf4dbbec7/ui/app/containers/databases/databaseList.tsx#L52)):*
> ```XML
>   // A list of databases, which are possibly sorted according to sortSetting.
>   databaseInfos: DatabaseInfo[];
>   // All events
> ```

Mention how they have been sorted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9621)*

**Comment by maxlang** [comment]
Reopening against master.

**Comment by maxlang** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[ui/app/containers/databases/databaseDetails.tsx, line 193 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9621#-KSwqDvoqa5KS5H-8o0X:-KTAeEn8xx5VlVGMc8jz:b26inr0) ([raw file](https://github.com/cockroachdb/cockroach/blob/116cd4dff9f084ec83d2bc25eb51aae4073234c8/ui/app/containers/databases/databaseDetails.tsx#L193)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> I think that table descriptor IDs may be able to overlap with store IDs and node IDs. I think you need to make sure that e.event_type is within an expected set.
</details>
Hmm, is there a good way for me to find the event types for each group of ids?

---

*[ui/app/containers/databases/databaseDetails.tsx, line 248 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9621#-KSwqqOSdYZtULbd06Av:-KTAhquYF0bCCm_ui6-4:b-ahg3b0) ([raw file](https://github.com/cockroachdb/cockroach/blob/116cd4dff9f084ec83d2bc25eb51aae4073234c8/ui/app/containers/databases/databaseDetails.tsx#L248)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> This should be a selector itself;  You should only re-sort if state.cachedData.events.data changes. If possible, you should also share the selector (and the eventCounts selector) between the database page and the tables page. We haven't yet established where to place a shared selector, but I'm guessing it just goes in the redux module for events.
> 
> I also don't think you need to convert the timestamps to moments in order to sort them; the original timestamps will also be in the same order, won't they?
> 
> Finally: does this not come back from the server already sorted?  Perhaps we should add an ORDER BY clause to the query and let the server take care of it.
</details>
Done. I didn't want to put the shared selectors in `apiReducers.ts`, so currently I just export them from `databaseList.tsx` and reuse them.

We can convert them to anything, but the current timestamp format is an object and isn't sortable. I have a `TimestampToMoment` function but no `TimestampToNumber` function.

I guess it already has `ORDER BY timestamp DESC` on the server. So I removed the sorting logic.

---

*[ui/app/containers/databases/databaseList.tsx, line 52 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9621#-KSwrGgO9NYAPbareEGA:-KTAe0hpGDNpSm0awhm0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/116cd4dff9f084ec83d2bc25eb51aae4073234c8/ui/app/containers/databases/databaseList.tsx#L52)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> Mention how they have been sorted.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9621)*

**Comment by maxlang** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[ui/app/containers/databases/databaseDetails.tsx, line 193 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9621#-KSwqDvoqa5KS5H-8o0X:-KTBmXeICralbTwNZECc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/116cd4dff9f084ec83d2bc25eb51aae4073234c8/ui/app/containers/databases/databaseDetails.tsx#L193)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Hmm, is there a good way for me to find the event types for each group of ids?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9621)*

**Comment by mrtracy** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9621#-:-KTFQr8Ix5kH24xVtyS-:bnfp4nl)*

**Pull request merged**
