### PR TITLE
ui: Rename "recent" executions to "active" executions

### PR DESCRIPTION
**Pull request by gtr**
This commit renames all mentions of "recent" executions to "active"
executions in the code as well as the copy appearing in the UI.

Release note (ui change): rename instances of "recent executions" to
"active executions" in the UI.

Loom demos to show that SQL Activity pages are still working as intended:
- [CC Console](https://www.loom.com/share/f10f94c4cf264f2c936d1efacac20e6b)
- [DB Console](https://www.loom.com/share/c36f3bb6adde4979b35438137f774739)

Part of: #100663.

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
can you confirm everything is working on DB and CC? There was some changes made on managed repo to use the "Recent" name, so I want to make sure these changes don't affect that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103784#-:-NWJC__F8nFSVARwtSq2:b-87ulmg)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by gtr** [comment]
> can you confirm everything is working on DB and CC? There was some changes made on managed repo to use the "Recent" name, so I want to make sure these changes don't affect that.

Done, added the links to the PR description. Also fixed merge conflicts.

**Review by maryliag — COMMENTED** [review]
This is changing the Active/Recent pages, so those are the pages I want to see in the videos, for example, showing the details page for both statement and transactions active. On the CC video you clicked on the Transactions one, and I could see the back options saying "Recent Transactions"  instead of "Active". So confirm the back options are indeed updated and that your video include details pages that were affected

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103784#-:-NWc4ogr9GAFFMYJ0kFx:b-q7m63r)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by gtr** [comment]
Updated the links with the new demo for CC and CRDB. I'm not exactly sure what happened with that copy for the back options on CC but I regenerated, and re-linked everything again and it's updated now. Thanks!

**Review by xinhaoz — APPROVED** [review]
Getting some deja vu here 😆 Thanks for the rename!

**Comment by gtr** [comment]
TFTR!
bors r+

**Pull request merged**
