### PR TITLE
sql: reimplement EXPLAIN ANALYZE (DISTSQL)

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: reimplement EXPLAIN ANALYZE (DISTSQL)

This change reimplements EXPLAIN ANALYZE (DISTSQL) to use the new
analyze infrastructure. The output is now a single column which
contains the textual information from `EXPLAIN ANALYZE (PLAN)` plus
the diagrams.

We can now show multiple diagrams when there are subqueries or
postqueries.

We no longer support `EXPLAIN ANALYZE (DISTSQL)` inside a larger
query.

Release note (sql change): New EXPLAIN ANALYZE (DISTSQL) output
format. EXPLAIN ANALYZE (DISTSQL) now only works as a top-level
statement (it can no longer be part of a bigger query).

#### sql: remove old EXPLAIN ANALYZE code

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
The differences in the URLs are due to the SQL statement shown (we now show just the statement without the EXPLAIN ANALYZE part). I will add some tests with multiple URLs, just realized I forgot to do that.

**Review by yuzefovich — APPROVED** [review]
Great stuff! LGTM, but I think it'd be beneficial for Alfonso to take a look too.

I'm a bit out of touch with the recent work, so I have a few questions:
- what is the difference between `EXPLAIN ANALYZE (PLAN)` and `EXPLAIN ANALYZE (DISTSQL)`?
- how does new `EXPLAIN ANALYZE (DISTSQL)` handle subqueries and postqueries? Are they now executed via the same "main" path in the `connExecutor` and we simply perform some "setup" and "finish"?
- curious why `distribution` and `vectorized` are `hidden`.

> Reviewed 9 of 9 files at r1, 17 of 17 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57804#-:-MOEUXVR-Wf5C85EPV7p:b32v4dy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @RaduBerinde, and @rytaft)

___
*[pkg/sql/instrumentation.go, line 264 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57804#-MOETSjv11n1O5jRQu7S:-MOETSjw1ZXQlBzChcf0:b-2ocbup) ([raw file](https://github.com/cockroachdb/cockroach/blob/053e81bcb642722f4515b4f616adb2b454cb7bd3/pkg/sql/instrumentation.go#L264)):*
> ```Go
> }
> 
> // ShouldSaveFlows is true if we should ave the flow specifications (to be able
> ```

nit: `s/ave/save/`.

**Review by RaduBerinde — COMMENTED** [review]
Thanks for taking a look!

 * EXPLAIN ANALYZE (DISTSQL) shows what EXPLAIN ANALYZE (PLAN) shows, plus the diagram URL(s)
 * Yeah, just like with EXPLAIN ANALYZE (DEBUG), we let the regular path run its course, withh a bit of instrumentation code to save the diagrams
 * distibuted and vectorized are hidden by the "make output deterministic" testing knob, so that we can test `EXPLAIN ANALYZE (PLAN)` in logic tests with multiple configurations (fakedist, vec-off, etc)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57804#-:-MOF9EVxExq57iKWGNHT:b-4vh1yg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @RaduBerinde, and @rytaft)

**Review by asubiotto — APPROVED** [review]
:lgtm: minus the comment about the "experimental" line

> Reviewed 6 of 9 files at r1, 18 of 18 files at r4, 17 of 17 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57804#-:-MOVqYzR6dpZt6JJG_Kb:bqx8gwb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/explain_test.go, line 100 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/57804#-MOVp_f1EIYEP1bQkAKs:-MOVp_f1EIYEP1bQkAKt:b-vxvru7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bfc74553b62320e7e99a657dad4be9d122c1176/pkg/sql/explain_test.go#L100)):*
> ```Go
> 		`UPDATE a SET b = 1`,
> 
> 		`EXPLAIN ANALYZE (DISTSQL) SELECT 1`,
> ```

Why the removal? I'm not really sure what this test does at first glance.
___
*[pkg/sql/logictest/testdata/logic_test/explain_analyze_plans, line 245 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/57804#-MOVqO_wCdzx4FP8biOC:-MOVqO_wCdzx4FP8biOD:b-dujw48) ([raw file](https://github.com/cockroachdb/cockroach/blob/de00701307594497d3f8d70907f5d6b544e47b1f/pkg/sql/logictest/testdata/logic_test/explain_analyze_plans#L245)):*
> ```
> 
> query T
> EXPLAIN ANALYZE (DISTSQL) INSERT INTO child VALUES (1, (SELECT min(p) FROM parent))
> ```

This is so nice
___
*[pkg/sql/opt/exec/execbuilder/testdata/distsql_misc, line 109 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57804#-MOVotIs87N6hC_PrMUt:-MOVotIt7xYaBVcf10KS:b5ztzd7) ([raw file](https://github.com/cockroachdb/cockroach/blob/01188330f2a4aabd118b4f7eee0fb4d446175546/pkg/sql/opt/exec/execbuilder/testdata/distsql_misc#L109)):*
> ```
> Diagram: https://cockroachdb.github.io/distsqlplan/decode.html#eJzUldFq2z4Uxu__TyHO1X-g1JLspKmv2pUOQlkz4rCbkQs1PmSmieRJMltX8lh7gT3ZsFVvS5fYKrSUXuocH3-ffnzi3IH9soYUzmcXZ_MLks3P5pNsPjnPiOVkekUkeTebvie5dBIoKJ3jldyghfQTcKAggEIMFBKgMIQFhdLoJVqrTf3JXTMwyb9ByigUqqxcXV5QWGqDkN6BK9waIYW5vF7jDGWOJmJAIUcni3UjU0uflqbYSHMLFLJSKpuSQcSJVDnhRLvPaIDCtHIpOa1NXX4krthgStjPH9afl1o5VK7Q6p-Wq8o1WmJQ5inhjPnq9a37XRwzRt4ChfsvdeXKWqv-drGl4M_3F7NOrhBSvqXhl8_kplyjiYa7F_flrPiOjVbjLHPS3_KQsDgo_EevUtrkaDDf0VtsD1o7W60MrqTTJuIs3CT5XzBGrqvlDTr75qDleMcyDw8KDwlKxAeReI6oiH1R4UcjclnsCYsIDksPgDYsoycPiwgnL4LIi0EUvybyPQBa8sdPTj4OJx8HkY8HUfKayPcAaMmPn5x8Ek4-CSKfDKLhc5CP95EXR_F-8nEw-R4ALfmTZ11Ne4RnaEutLD5YUfv_zOrVhfkK_Z6zujJL_GD0spHxx2kz1xRytM53uT9MlG_VBv8e5p3DYmeYPxwW3co90nHndNI9nDzGd0OxAQoK3VdtbtrkWVTNK66j27Z8_HynffiLh_rDTv1Rt_nRC5s_7tQfd5sfv7D5k-7QsZ68d7-WR9qPD9oXR8m9_cX2v18BAAD__yP9CM4=
> ·
> WARNING: this statement is experimental!
> ```

This doesn't seem right. Should we elide this in this case?

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57804#-:-MOWPRlh96mqLENYDK7Q:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @rytaft)

___
*[pkg/sql/explain_test.go, line 100 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/57804#-MOVp_f1EIYEP1bQkAKs:-MOWOnVR3cDzlvyuWsUo:b-b1ytlv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bfc74553b62320e7e99a657dad4be9d122c1176/pkg/sql/explain_test.go#L100)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why the removal? I'm not really sure what this test does at first glance.
</blockquote></details>

Among other things, it runs the statement inside an EXPLAIN (and EXPLAIN ANALYZE inside a larger statement is no longer supported).
___
*[pkg/sql/opt/exec/execbuilder/testdata/distsql_misc, line 109 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57804#-MOVotIs87N6hC_PrMUt:-MOWPAt-7AfzRlfthvxe:bsjxgrv) ([raw file](https://github.com/cockroachdb/cockroach/blob/01188330f2a4aabd118b4f7eee0fb4d446175546/pkg/sql/opt/exec/execbuilder/testdata/distsql_misc#L109)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This doesn't seem right. Should we elide this in this case?
</blockquote></details>

I will remove it altogether soon

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 9 files at r1, 18 of 18 files at r4, 16 of 17 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57804#-:-MOWtzzI2c_DZPzeRaEx:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @asubiotto and @RaduBerinde)

___
*[pkg/sql/logictest/testdata/logic_test/explain_analyze, line 117 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57804#-MOWogO4Bd_WjIidKmxB:-MOWogO639pqYHN1TMP4:b25eb4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bfc74553b62320e7e99a657dad4be9d122c1176/pkg/sql/logictest/testdata/logic_test/explain_analyze#L117)):*
> ```
> EXPLAIN ANALYZE (DISTSQL) UPSERT INTO a VALUES(10)
> 
> statement error EXPLAIN ANALYZE does not support RETURNING NOTHING statements
> ```

is this supported now? Is there a test elsewhere?
___
*[pkg/sql/opt/exec/execbuilder/testdata/distsql_misc, line 103 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57804#-MOWpERT23x33nS6w-4a:-MOWpERT23x33nS6w-4b:b-pbvmir) ([raw file](https://github.com/cockroachdb/cockroach/blob/01188330f2a4aabd118b4f7eee0fb4d446175546/pkg/sql/opt/exec/execbuilder/testdata/distsql_misc#L103)):*
> ```
> execution time: 100µs
> distribution: <hidden>
> vectorized: <hidden>
> ```

why are these values hidden?
___
*[pkg/sql/opt/exec/execbuilder/testdata/explain, line 1344 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57804#-MOWpIIo6sZ5LEnWn1_Z:-MOWpIIo6sZ5LEnWn1__:b608tg2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bfc74553b62320e7e99a657dad4be9d122c1176/pkg/sql/opt/exec/execbuilder/testdata/explain#L1344)):*
> ```
> 
> query T
> EXPLAIN (VERBOSE) EXPLAIN ANALYZE (DISTSQL) SELECT 1
> ```

Is there a test somewhere showing the error that this produces?
___
*[pkg/sql/opt/optbuilder/builder.go, line 296 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/57804#-MOWtiuMBiTWalyiJqcL:-MOWtiuMBiTWalyiJqcM:bqrslrq) ([raw file](https://github.com/cockroachdb/cockroach/blob/de00701307594497d3f8d70907f5d6b544e47b1f/pkg/sql/opt/optbuilder/builder.go#L296)):*
> ```Go
> 	case *tree.ExplainAnalyze:
> 		// This statement should have been handled by the executor.
> 		panic(errors.New("EXPLAIN ANALYZE can only be used as a top-level statement"))
> ```

should this be an `AssertionFailedf`?
___
*[pkg/sql/sqltelemetry/planning.go, line 95 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57804#-MOWpS9E1QKvPOlhEP-5:-MOWpS9E1QKvPOlhEP-6:b-yjuont) ([raw file](https://github.com/cockroachdb/cockroach/blob/01188330f2a4aabd118b4f7eee0fb4d446175546/pkg/sql/sqltelemetry/planning.go#L95)):*
> ```Go
> var ExplainAnalyzeUseCounter = telemetry.GetCounterOnce("sql.plan.explain-analyze")
> 
> // ExplainAnalyzeDistSQLUseCounter is to be incremented whenever EXPLAIN ANALYZE is run.
> ```

EXPLAIN ANALYZE (DISTSQL)

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57804#-:-MOXJdId8r_X9XagY5AY:b-814g8k)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @asubiotto and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/explain_analyze, line 117 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57804#-MOWogO4Bd_WjIidKmxB:-MOXIObK4JnyekknDO1H:bb1oj6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bfc74553b62320e7e99a657dad4be9d122c1176/pkg/sql/logictest/testdata/logic_test/explain_analyze#L117)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

is this supported now? Is there a test elsewhere?
</blockquote></details>

We no longer do anything special for `RETURNING NOTHING` anywhere (we deprecated that feature).
___
*[pkg/sql/opt/exec/execbuilder/testdata/distsql_misc, line 103 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57804#-MOWpERT23x33nS6w-4a:-MOXIX3Z-LWUW0m7XRKs:b-pax7jf) ([raw file](https://github.com/cockroachdb/cockroach/blob/01188330f2a4aabd118b4f7eee0fb4d446175546/pkg/sql/opt/exec/execbuilder/testdata/distsql_misc#L103)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

why are these values hidden?
</blockquote></details>

They are hidden by a "make explain analyze deterministic" flag; it allows using multiple test configs (e.g. vec-on/vec-off)
___
*[pkg/sql/opt/exec/execbuilder/testdata/explain, line 1344 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57804#-MOWpIIo6sZ5LEnWn1_Z:-MOXJA4MDtYbGPna43Hy:blkur64) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bfc74553b62320e7e99a657dad4be9d122c1176/pkg/sql/opt/exec/execbuilder/testdata/explain#L1344)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Is there a test somewhere showing the error that this produces?
</blockquote></details>

Good point, added back with `statement error`.
___
*[pkg/sql/opt/optbuilder/builder.go, line 296 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/57804#-MOWtiuMBiTWalyiJqcL:-MOXJDdo4HFfAMSWwdf8:bf4yf27) ([raw file](https://github.com/cockroachdb/cockroach/blob/de00701307594497d3f8d70907f5d6b544e47b1f/pkg/sql/opt/optbuilder/builder.go#L296)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

should this be an `AssertionFailedf`?
</blockquote></details>

No, this is user-facing. I improved it to add a pgcode.
___
*[pkg/sql/sqltelemetry/planning.go, line 95 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57804#-MOWpS9E1QKvPOlhEP-5:-MOXJcLI87sibegiCaBf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/01188330f2a4aabd118b4f7eee0fb4d446175546/pkg/sql/sqltelemetry/planning.go#L95)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

EXPLAIN ANALYZE (DISTSQL)
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 18 files at r7, 17 of 18 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57804)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asubiotto)

**Review by RaduBerinde — COMMENTED** [review]
CI failure looks like a flake (timeout).

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57804#-:-MOXoegu8U3TrEDYC0n-:bfkqo41)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asubiotto)

**Pull request merged**
