### PR TITLE
raft: update leader's Next when appending entries

### PR DESCRIPTION
**Pull request by pav-kv**
This PR makes the leader update its `Progress.Next` when it appends entries to its log. This makes the `Progress.Next` updates symmetric.

Previously, we only updated `Next` for followers, when sending a `MsgApp` to them, but updated `Match` symmetrically when getting `MsgAppResp` (both from the leader self-directed messages, and from followers). The leader is a special case: it doesn't send `MsgApp`s to itself. But there is an implicit `MsgApp` that happens in `appendEntry` function. We update `Next` accordingly.

On the leader, `Next` is always equal to `log.lastIndex + 1`. This is consistent with the fact that no more `MsgApp`s need to be sent to the local Acceptor.

Epic: none
Release note: none

### CODE REVIEW

**Review by kvoli — APPROVED** [review]

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126902)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv)

___
*[`pkg/raft/rawnode.go` line 425 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126902#-O1STJvl9hJ_Xhqk7jtU:-O1STJvl9hJ_Xhqk7jtV:b-j0l507) ([raw file](https://github.com/cockroachdb/cockroach/blob/617b1a9b40226a9cd375cabf2c4dc79f04c2e74f/pkg/raft/rawnode.go#L425)):*
> ```Go
> 	}
> 
> 	// On the leader, the entries sent through Ready / MsgStorageAppend are
> ```

Is `RawNode.acceptReady` the right place for this, or should it be done in `raft.appendEntry` when appending to the leader's unstable log? It seems inconsistent that `Next` would be tied to the `MsgStorageAppend` protocol for the leader but the `MsgApp` protocol for followers.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126902)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/raft/rawnode.go` line 425 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126902#-O1STJvl9hJ_Xhqk7jtU:-O1SVIdo-vSP1wtqT-2M:brzlja5) ([raw file](https://github.com/cockroachdb/cockroach/blob/617b1a9b40226a9cd375cabf2c4dc79f04c2e74f/pkg/raft/rawnode.go#L425)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is `RawNode.acceptReady` the right place for this, or should it be done in `raft.appendEntry` when appending to the leader's unstable log? It seems inconsistent that `Next` would be tied to the `MsgStorageAppend` protocol for the leader but the `MsgApp` protocol for followers.
</blockquote></details>

Do you mean updating `Next` to `lastIndex + 1` in `appendEntry`? The feasibility of this depends on what semantics we want `Next` to have on the leader (we might be thinking about different semantics here). The idea of this PR is that entries < `Next` have been sent to the log (local or remote), and entry `Next` will be sent next.

The asymmetry comes from the fact that log appends are asymmetric: to the followers we send `MsgApp`, on the leader we send `MsgStorageAppend` / `Ready` to log storage. Effectively, `MsgStorageAppend` is a local `MsgApp`. Unlike log appends, the responses (which bump the `Match` index) are symmetric: we use `MsgAppResp` for both cases.

The `acceptReady` is the place where we "send" the `MsgStorageAppend`. It is in line with the `Next` bumps on `send(MsgApp)`.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126902)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/raft/rawnode.go` line 425 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126902#-O1STJvl9hJ_Xhqk7jtU:-O1SZ3uB-i8k2i6Uuo24:b-vapo0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/617b1a9b40226a9cd375cabf2c4dc79f04c2e74f/pkg/raft/rawnode.go#L425)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Do you mean updating `Next` to `lastIndex + 1` in `appendEntry`? The feasibility of this depends on what semantics we want `Next` to have on the leader (we might be thinking about different semantics here). The idea of this PR is that entries < `Next` have been sent to the log (local or remote), and entry `Next` will be sent next.

The asymmetry comes from the fact that log appends are asymmetric: to the followers we send `MsgApp`, on the leader we send `MsgStorageAppend` / `Ready` to log storage. Effectively, `MsgStorageAppend` is a local `MsgApp`. Unlike log appends, the responses (which bump the `Match` index) are symmetric: we use `MsgAppResp` for both cases.

The `acceptReady` is the place where we "send" the `MsgStorageAppend`. It is in line with the `Next` bumps on `send(MsgApp)`.
</blockquote></details>

Thinking in "layers", the `Match/Next` is the leader's (Proposer's) concept. It tracks what has been sent to all Acceptors (including the leader's local "acceptor"). We shouldn't update `Next` on `appendEntry` because the latter is a proposer function, whereas `Next` should be updated on sending stuff to an Acceptor.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126902)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv)

___
*[`pkg/raft/rawnode.go` line 425 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126902#-O1STJvl9hJ_Xhqk7jtU:-O1SZyyl7rLVUcvoWcKw:b216sv9) ([raw file](https://github.com/cockroachdb/cockroach/blob/617b1a9b40226a9cd375cabf2c4dc79f04c2e74f/pkg/raft/rawnode.go#L425)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Thinking in "layers", the `Match/Next` is the leader's (Proposer's) concept. It tracks what has been sent to all Acceptors (including the leader's local "acceptor"). We shouldn't update `Next` on `appendEntry` because the latter is a proposer function, whereas `Next` should be updated on sending stuff to an Acceptor.
</blockquote></details>

I agree with what you're saying, but I'm not sure I agree with the conclusion derived from it. `appendEntry` is playing both roles on the leader (proposer and acceptor). This is why it's also where we construct the self-directly `MsgAppResp` for the leader to send back to itself. It then seems appropriate for the proposer role to fully account for the self-directed `MsgApp` (which is never actually materialized) in `appendEntry`, given the current structure of the code.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126902)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/raft/rawnode.go` line 425 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126902#-O1STJvl9hJ_Xhqk7jtU:-O1S_n4Z7HS95Abg0JnF:bq9qlaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/617b1a9b40226a9cd375cabf2c4dc79f04c2e74f/pkg/raft/rawnode.go#L425)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I agree with what you're saying, but I'm not sure I agree with the conclusion derived from it. `appendEntry` is playing both roles on the leader (proposer and acceptor). This is why it's also where we construct the self-directly `MsgAppResp` for the leader to send back to itself. It then seems appropriate for the proposer role to fully account for the self-directed `MsgApp` (which is never actually materialized) in `appendEntry`, given the current structure of the code.
</blockquote></details>

OTOH, I can see a point in setting `Next` to `lastIndex + 1`, to reflect the fact that the leader has "sent" a self-`MsgApp` right on `appendEntry`. Then it looks even nicer layering-wise.

The problem though is that Replication AC wants to rely on this PR, and `Next` being the next thing to be sent to storage rather than `lastIndex + 1`. The reasons for wanting that invariant are feeble, we should discuss them more.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126902)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/raft/rawnode.go` line 425 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126902#-O1STJvl9hJ_Xhqk7jtU:-O1SkDe-25j0g1wpnLcy:bbfo99t) ([raw file](https://github.com/cockroachdb/cockroach/blob/617b1a9b40226a9cd375cabf2c4dc79f04c2e74f/pkg/raft/rawnode.go#L425)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

OTOH, I can see a point in setting `Next` to `lastIndex + 1`, to reflect the fact that the leader has "sent" a self-`MsgApp` right on `appendEntry`. Then it looks even nicer layering-wise.

The problem though is that Replication AC wants to rely on this PR, and `Next` being the next thing to be sent to storage rather than `lastIndex + 1`. The reasons for wanting that invariant are feeble, we should discuss them more.
</blockquote></details>

I agree with you. Updated the PR.

**Review by nvb — COMMENTED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126902)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv)

___
*[`pkg/raft/raft.go` line 825 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126902#-O1SoUmU69JlhK0itUrM:-O1SoUmU69JlhK0itUrN:b-6jdqda) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d2fa4891fb599b26f3a26b7271525d5e8bcf8a3/pkg/raft/raft.go#L825)):*
> ```Go
> 	// progress here as if it was sent.
> 	lastIndex := r.raftLog.lastIndex()
> 	if pr := r.trk.Progress[r.id]; pr != nil {
> ```

Will `pr` ever be nil?
___
*[`pkg/raft/raft.go` line 826 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126902#-O1SoWYZ3ZgzRYUf72NO:-O1SoWYZ3ZgzRYUf72NP:bslcep4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d2fa4891fb599b26f3a26b7271525d5e8bcf8a3/pkg/raft/raft.go#L826)):*
> ```Go
> 	lastIndex := r.raftLog.lastIndex()
> 	if pr := r.trk.Progress[r.id]; pr != nil {
> 		pr.Next = lastIndex + 1
> ```

`Progress.SentEntries` is implemented with `pr.Next += uint64(entries)`. Would it be more consistent to do the same here, instead of reaching back into the unstable log to grab the last index?

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126902)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/raft/raft.go` line 825 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126902#-O1SoUmU69JlhK0itUrM:-O1Sr1QcE78ILUvaJw-D:bg6xr8d) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d2fa4891fb599b26f3a26b7271525d5e8bcf8a3/pkg/raft/raft.go#L825)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Will `pr` ever be nil?
</blockquote></details>

Generally, `pr` on the leader can be nil if the leader has been removed from the config and is about to resign. But it looks like both callers of `appendEntry` check that / assume that it's not nil:

- https://github.com/cockroachdb/cockroach/blob/551dcfbaf516139ab8c6f5d30269a00b0bdce032/pkg/raft/raft.go#L1238-L1243
- https://github.com/cockroachdb/cockroach/blob/551dcfbaf516139ab8c6f5d30269a00b0bdce032/pkg/raft/raft.go#L896-L910

Can remove this `if`.
___
*[`pkg/raft/raft.go` line 826 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126902#-O1SoWYZ3ZgzRYUf72NO:-O1SrgapEiONkJDSSSsD:b-71s80f) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d2fa4891fb599b26f3a26b7271525d5e8bcf8a3/pkg/raft/raft.go#L826)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`Progress.SentEntries` is implemented with `pr.Next += uint64(entries)`. Would it be more consistent to do the same here, instead of reaching back into the unstable log to grab the last index?
</blockquote></details>

I don't know, it feels like it would be better/safer/straighter to do the other way around (in `SentEntries` too) - set `Next` to the last sent index + 1. Today, there is anyway an implicit expectation in `Progress.SentEntries` that the `entries int` batch we're sending starts at the old `Next`. So we could as well say `Progress.SentEntries(lastIndex, bytes)`.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126902)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/raft/raft.go` line 825 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126902#-O1SoUmU69JlhK0itUrM:-O1Svs_ICtj92adS-t4j:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d2fa4891fb599b26f3a26b7271525d5e8bcf8a3/pkg/raft/raft.go#L825)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Generally, `pr` on the leader can be nil if the leader has been removed from the config and is about to resign. But it looks like both callers of `appendEntry` check that / assume that it's not nil:

- https://github.com/cockroachdb/cockroach/blob/551dcfbaf516139ab8c6f5d30269a00b0bdce032/pkg/raft/raft.go#L1238-L1243
- https://github.com/cockroachdb/cockroach/blob/551dcfbaf516139ab8c6f5d30269a00b0bdce032/pkg/raft/raft.go#L896-L910

Can remove this `if`.
</blockquote></details>

Done
___
*[`pkg/raft/raft.go` line 826 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126902#-O1SoWYZ3ZgzRYUf72NO:-O1SvtPW2FzAKvz2OZD-:b-mydrn3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d2fa4891fb599b26f3a26b7271525d5e8bcf8a3/pkg/raft/raft.go#L826)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

I don't know, it feels like it would be better/safer/straighter to do the other way around (in `SentEntries` too) - set `Next` to the last sent index + 1. Today, there is anyway an implicit expectation in `Progress.SentEntries` that the `entries int` batch we're sending starts at the old `Next`. So we could as well say `Progress.SentEntries(lastIndex, bytes)`.
</blockquote></details>

Replaced the raft log last index with `app.lastIndex()` (it's the same thing, but it reflects the semantics of "last sent index").

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126902#-:-O1T44mo8bW0gtfb1hZV:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv)

**Comment by pav-kv** [comment]
bors r=kvoli,nvanbenschoten

**Pull request merged**
