### PR TITLE
sql: make cleanup jobs spawned by alter primary key not cancelable

### LINKED ISSUE #45500: sql: make alter primary key index clean up phase uncancelable
The cleanup phase for the primary key change should not be cancelable, otherwise entire unused indexes will be left behind on a cancel.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #45500.

This PR makes the job spawned by ALTER PRIMARY KEY that cleans
up indexes be uncancelable.

This PR additionally fixes a related bug where ALTER PRIMARY KEY
would spawn a job when it didn't actually enqueue any mutations
on the table descriptor, causing future schema changes on the
table to hang.

Release note (sql change): This PR makes the cleanup job spawned
by ALTER PRIMARY KEY in some cases uncancelable.

### CODE REVIEW

**Comment by rohany** [comment]
@spaskob I decided not to introduce a cancelable field on the job payload because it was unclear how to really version gate it, and we already do something special cased for schema changes right now.

**Comment by lucy-zhang** [comment]
What exactly is the backward compatibility issue with a field on the job payload? I thought that primary key changes would be version-gated for 20.1.

Having "cleanup" jobs be non-cancellable was something @pbardea and I were discussing today, since we need a separate GC job that clears index/table spans which can't be cancelled, so I think a more general solution like a flag on the job payload would be preferable.

**Comment by rohany** [comment]
> What exactly is the backward compatibility issue with a field on the job payload? I thought that primary key changes would be version-gated for 20.1.

The comment in `pkg/jobs/registry.go:590` -- primary key changes are version gated, but I don't have enough context in the jobs system to version gate arbitrarily stop other jobs from marking themselves as non-cancelable. The issue I'm worried about is a < 20.1 node issuing a cancel and ignoring the cancelable field on the job because it doesn't know about it yet.

**Comment by lucy-zhang** [comment]
I think this won't be an issue in practice. 20.1-style schema change jobs will also be version-gated, and AFAIK schema changes (and their associated GC jobs) are the only jobs which would need to be non-cancellable starting in 20.1. We'll also have special handling for schema changes in "cleanup"-like states (rolling back, waiting for GC, dropping indexes after a PK swap) when we run the migration to convert 19.2-style jobs to run in 20.1 after upgrade finalization. @pbardea has been working on all this.

What if we just add the field and add a warning in a comment that it won't be respected on 19.2 nodes? I don't think we're in danger of any of us adding a non-cancellable job without thinking about backward compatibility.

**Comment by rohany** [comment]
Alright, I'll update this PR accordingly.

**Comment by rohany** [comment]
RFAL

**Review by spaskob — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45595)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @spaskob)

___
*[pkg/jobs/jobs.go, line 384 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45595#-M1VZu3XC1RzRZYUXxBw:-M1VZu3XC1RzRZYUXxBx:b-6otcmh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac375148fa7829989b5a33311b76acf2c80ca4a9/pkg/jobs/jobs.go#L384)):*
> ```Go
> 	return j.Update(ctx, func(txn *client.Txn, md JobMetadata, ju *JobUpdater) error {
> 		if md.Payload.Noncancelable {
> 			return errors.Newf("job %d is not a cancelable job", j.ID())
> ```

nit: for jobs we use log format
`job %id: not cancelable`

**Review by spaskob — COMMENTED** [review]
LGTM
please remember to fix the log message format before merging

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45595#-:-M1V_WwmEjhkzurk0NQj:b-hf0pmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @spaskob)

**Comment by rohany** [comment]
bors r=spaskob

**Pull request merged**
