### PR TITLE
geoprojbase: add bounds to geospatial CRSes

### PR DESCRIPTION
**Pull request by otan**
Add bounds information for all geospatial CRSes from EPSG. This can
be useful later for default spatial index bounds.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
Thanks for doing this!

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51091#-:-MBfsqYL66uZRcfUULcr:bxgavm9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/cmd/generate-spatial-ref-sys/main.go, line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51091#-MBfm4CNAqLloMmB7g1r:-MBfm4CNAqLloMmB7g1s:b6zi5ap) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4086292aaf5f3e50e8d4ce1ddc290e855c26685/pkg/cmd/generate-spatial-ref-sys/main.go#L179)):*
> ```Go
> 			bbox := results.Results[0].BBox
> 			// The bounds seem inconsistently ordered. reorder them.
> 			x := []float64{bbox[1], bbox[3]}
> ```

It would be clearer to rename x to lon and y to lat, since I am assuming this is just correcting that ordering.

As I mentioned on slack, I think the following is not quite correct. Working through 26918:
```
lon := {-78.0, -72.0}
lat := {84.0, 28.28}
```

after sorting `lat := {28.28, 84.0}`
which is going to transform points `(-78, 28.28), (-72, 84)`

Which gives
```
  POINT (205723.769271706114523 3131872.261800516862422)
  POINT (534994.655061707017012 9329005.182354301214218)
```
And so we end up with the following in `projections.go`
```
MinX: 205723.7692717061,
MaxX: 534994.655061707,
MinY: 3.131872261800517e+06,
MaxY: 9.329005182354301e+06,
```

The issue here is that we have used only 2 out of the 4 endpoints of a polygon. This polygon is not necessarily a rectangle post-projection (it is probably aligned with the axis, though we don't even need that alignment property). The other two endpoints pre-projection are `(-78, 84), (-72, 28.28)` (since it is a rectangular bbox pre-projection). If we use those points too we get:
```
  POINT (465005.344938293157611 9329005.182354301214218)
  POINT (794276.230728295166045 3131872.261800516862422)                              
```
Note that the higher X this generates -- this is because the original two endpoints we used were bottom-left, top-right of the pre-projection rectangle. The top-right gives us a lower MaxX than the bottom-right as the constant longitude difference in the pre-projection rectangle is a smaller distance on the earth at higher longitudes. In general, if we use all 4 points to compute the min and max we don't need to know the details of the projection.

So here we will get
```
MinX: 205723.7692717061,
MaxX: 794276.23,
MinY: 3.131872261800517e+06,
MaxY: 9.329005182354301e+06,
```
This now roughly agrees with https://spatialreference.org/ref/epsg/26918/ (which is stating minx, miny, maxx, maxy)
```
Projected Bounds: 222357.2382, 3747355.8896, 777642.7618, 9239816.3278
```

**Comment by otan** [comment]
___
*[pkg/cmd/generate-spatial-ref-sys/main.go, line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51091#-MBfm4CNAqLloMmB7g1r:-MBfv1RZCfrRvT_Li-Gf:b-jqm8bd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4086292aaf5f3e50e8d4ce1ddc290e855c26685/pkg/cmd/generate-spatial-ref-sys/main.go#L179)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

It would be clearer to rename x to lon and y to lat, since I am assuming this is just correcting that ordering.

As I mentioned on slack, I think the following is not quite correct. Working through 26918:
```
lon := {-78.0, -72.0}
lat := {84.0, 28.28}
```

after sorting `lat := {28.28, 84.0}`
which is going to transform points `(-78, 28.28), (-72, 84)`

Which gives
```
  POINT (205723.769271706114523 3131872.261800516862422)
  POINT (534994.655061707017012 9329005.182354301214218)
```
And so we end up with the following in `projections.go`
```
MinX: 205723.7692717061,
MaxX: 534994.655061707,
MinY: 3.131872261800517e+06,
MaxY: 9.329005182354301e+06,
```

The issue here is that we have used only 2 out of the 4 endpoints of a polygon. This polygon is not necessarily a rectangle post-projection (it is probably aligned with the axis, though we don't even need that alignment property). The other two endpoints pre-projection are `(-78, 84), (-72, 28.28)` (since it is a rectangular bbox pre-projection). If we use those points too we get:
```
  POINT (465005.344938293157611 9329005.182354301214218)
  POINT (794276.230728295166045 3131872.261800516862422)                              
```
Note that the higher X this generates -- this is because the original two endpoints we used were bottom-left, top-right of the pre-projection rectangle. The top-right gives us a lower MaxX than the bottom-right as the constant longitude difference in the pre-projection rectangle is a smaller distance on the earth at higher longitudes. In general, if we use all 4 points to compute the min and max we don't need to know the details of the projection.

So here we will get
```
MinX: 205723.7692717061,
MaxX: 794276.23,
MinY: 3.131872261800517e+06,
MaxY: 9.329005182354301e+06,
```
This now roughly agrees with https://spatialreference.org/ref/epsg/26918/ (which is stating minx, miny, maxx, maxy)
```
Projected Bounds: 222357.2382, 3747355.8896, 777642.7618, 9239816.3278
```

</blockquote></details>

I think x/y makes more sense, given the naming and usage of the libraries.
Otherwise, applied the changes!

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51091#-:-MBiN35aEMsujcVCeAWb:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by otan** [comment]
bors r=sumeerbhola

**Pull request merged**
