### PR TITLE
release-23.1: sql: add new persistedV22_2 views

### LINKED ISSUE #100501: SQL Activity fail to load on mixed version 22.2 - 23.1 state
SQL Activity page fail to load on mixed version state

Jira issue: CRDB-26467

### PR DESCRIPTION
**Pull request by maryliag**
Fixes #100501

Adds `{statement|transaction}_statistics_persisted_v22_2` like they were added on #96454.
Check the version of the cluster before deciding which view to use.
This is required for mixed version cluster with 22.2 and 23.1 versions.

Release note: None

---
Release justification: bug fix

### CODE REVIEW

**Comment by yuzefovich** [comment]
Is this intentional that this PR is directly against 23.1 branch and not a backport of already merged PR to master? I believe we still will need to forward-port this change to master if this PR merges.

**Comment by maryliag** [comment]
Is intentional, because this change is not required for the main branch.

The main branch is now for 23.2, and the changes added here are to make the migration from 22.2 to 23.1 work. A migration from 23.1 to 23.2 would not use any of the changes added to this commit. So I don't believe it needs to be added to main branch because is a path that would never happen.
If this code was on the main branch, I would just delete it.

If in 23.2 we make changes on the mentioned view, then we would need to update the current view name to 23_1 and then add the new view with the changes.

**Comment by yuzefovich** [comment]
In other words, not forward-porting this PR to 23.2 version results in effectively reverting this PR on master. However, wasn't there some communication that we should no longer be deleting 23_1 version gates? (I don't really know what I'm taking about here though.)

**Review by j82w — COMMENTED** [review]
> Reviewed 7 of 14 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100673)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/server/combined_statement_stats.go` line 415 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100673#-NSGTpPW0QxUVlLJeyA1:-NSGTpPW0QxUVlLJeyA2:b13jtk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff2ccf2b0255c9eea4e5141b3252bac90f4e9809/pkg/server/combined_statement_stats.go#L415)):*
> ```Go
>     metadata,
>     crdb_internal.merge_statement_stats(array_agg(statistics)) AS statistics
> FROM %s%s %s
> ```

Doesn't this need to be updated to use the new view?
https://github.com/cockroachdb/cockroach/blob/917d237b3164f1df66824e46efbd816d9ffe0c76/pkg/ui/workspaces/cluster-ui/src/api/indexDetailsApi.ts#L103

**Review by maryliag — COMMENTED** [review]
@yuzefovich I had forgot about that! That is a good point! I'll create another PR for the main branch with the same changes from here! Thank you for catching that!!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100673#-:-NSGm0193qkzTZVY1g2O:bc0u1z6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`pkg/server/combined_statement_stats.go` line 415 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100673#-NSGTpPW0QxUVlLJeyA1:-NSGmDbm2oqrN26lvC6f:b-6mr5qv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff2ccf2b0255c9eea4e5141b3252bac90f4e9809/pkg/server/combined_statement_stats.go#L415)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Doesn't this need to be updated to use the new view?
https://github.com/cockroachdb/cockroach/blob/917d237b3164f1df66824e46efbd816d9ffe0c76/pkg/ui/workspaces/cluster-ui/src/api/indexDetailsApi.ts#L103

</blockquote></details>

Discussed offline. I won't address any UI calls on this PR. It will instead show a message about not available (current behaviour)

**Review by j82w — APPROVED** [review]
:lgtm:

> Reviewed 4 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100673#-:-NSGmpjm6koKM6udUCSt:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
