### PR TITLE
jobs: runInTxn cannot AutoRetry, could result in partial transactions

### PR DESCRIPTION
**Pull request by nvb**
While auditing the uses of `txn.Exec` with @spencerkimball we stumbled
upon `Job.runInTxn`. The method runs a `retryable` closure in the context
of a transaction and exposes the option to run it in an existing `txn`
provided to `Job.WithTxn`. `Job.WithTxn` is in turn used throughout
`SchemaChanger` to run multiple Jobs within the scope of a single
transaction.

Unfortunately, `Job.runInTxn` was badly abusing `txn.Exec` by allowing
it to auto-retry. This could result in some very bad behavior, including
schema changes that commit with some `Jobs` missing. The reason for this
is that `txn.Exec` is meant to be scoped to an entire transaction. This
is why its retry loop is able to simply re-execute the provided closure
in the case of a transaction retry. If `txn.Exec` in not scoped to an
entire transaction but still attempts to auto-retry then a retry error
that bumps the transaction epoch could result in all work performed by
the transaction before the most recent `retryable` closure being thrown
out.

To address this, we no longer allow `runInTxn` to use the `AutoRetry` option
when running `txn.Exec`. Because this option is no longer set, `txn.Exec`
is useless, so we remove that too.

Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/jobs/jobs.go, line 340 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21802#-L3jKT-9MQfLDs2-3eF3:-L3jKT-9MQfLDs2-3eF4:bkt239m) ([raw file](https://github.com/cockroachdb/cockroach/blob/cba66d76604d0fa0beb18fd3090fd22a0eb3ccb7/pkg/sql/jobs/jobs.go#L340)):*
> ```Go
> 	if j.txn != nil {
> 		defer func() { j.txn = nil }()
> 		// Don't run fn in a retry loop because we need retryable errors to
> ```

the comment at this point is unnecessary - of course you can't put a retry loop here :P

But you can put a comment on the method explaining how retries are handled iff j.txn is not set.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21802#-:-L3jKkm4JWrS6irPdSLX:bnfp4nl)*

**Comment by benesch** [comment]
Yikes, nice find! /cc @jordanlewis just FYE

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/jobs/jobs.go, line 340 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21802#-L3jKT-9MQfLDs2-3eF3:-L3jMRGXOZemq9rReGCZ:b-ppopar) ([raw file](https://github.com/cockroachdb/cockroach/blob/cba66d76604d0fa0beb18fd3090fd22a0eb3ccb7/pkg/sql/jobs/jobs.go#L340)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

the comment at this point is unnecessary - of course you can't put a retry loop here :P

But you can put a comment on the method explaining how retries are handled iff j.txn is not set.
</blockquote></details>

But the previous code did exactly that and put a retry loop there! I, for one, like this comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21802#-:-L3jMXThr--KUOfshKTC:b-4xcpqy)*

**Comment by nvanbenschoten** [comment]
TFTRs!

@benesch are you aware of any flakes or issues that could be in some way related to this?

@andreimatei you'll be happy to hear that we no longer have any legitimate uses of `Txn.Exec` outside of `db.Txn`!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/jobs/jobs.go, line 340 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21802#-L3jKT-9MQfLDs2-3eF3:-L3jN2U9TmpwUISG7VSS:b-23zvo5) ([raw file](https://github.com/cockroachdb/cockroach/blob/cba66d76604d0fa0beb18fd3090fd22a0eb3ccb7/pkg/sql/jobs/jobs.go#L340)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

But the previous code did exactly that and put a retry loop there! I, for one, like this comment.
</blockquote></details>

Yeah, I don't think it hurts to have the comment here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21802#-:-L3jNBdJyfPMSq-T1c1h:b-l23d18)*

**Comment by andreimatei** [comment]
Then can we get rid of those execution options that `Txn.Exec()` takes? Also let's unexport it.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21802#-:-L3jO7PCOTE4s5AI6HzD:b-vh7fhl)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/jobs/jobs.go, line 340 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21802#-L3jKT-9MQfLDs2-3eF3:-L3jOPqzLTW5eKRfMe2J:b-eofdlw) ([raw file](https://github.com/cockroachdb/cockroach/blob/cba66d76604d0fa0beb18fd3090fd22a0eb3ccb7/pkg/sql/jobs/jobs.go#L340)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, I don't think it hurts to have the comment here.
</blockquote></details>

the suggestion to lift it up was good - the function definition should explain what errors the caller can expect and how they depend on the other state of `j`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21802)*

**Comment by jordanlewis** [comment]
Oops - sorry everyone!

For the record, I still feel braindead about this particular issue. @nvanbenschoten's explanation was excellent but I could easily imagine myself making that same mistake tomorrow.

Can we follow @andreimatei's suggestion? Otherwise it seems like a totally reasonable thing to use an autoretry option on the transaction. The long docstring on Exec has no caveats or warnings about this kind of thing, and people less enlightened about the `Txn` interface like myself might just screw it up again without some better internal documentation.

**Comment by benesch** [comment]
Yeah, I’m with Jordan. I code reviewed the original PR and it seeemed like
an AOK usage of txn.Exec.

**Comment by nvanbenschoten** [comment]
>Then can we get rid of those execution options that Txn.Exec() takes? Also let's unexport it.

Yep I agree! I have a WIP change to remove `Txn.Exec()` entirely.

**Comment by mberhault** [comment]
This was coincidentally merged just before the `add isRole column` migration (causing a backfill) started failing under stress. See:

ccl/sqlccl/TestBackupRestoreResume: #21828  
ccl/sqlccl/TestBackupRestoreControlJob: #21846 
sql/jobs/TestRegistryLifecycle: #21844 
sql/jobs/TestRegistryResumeActiveLease: #21808

Also coincidentally (yes, I'm being ironic), all four tests set are the only ones that override `jobs.DefaultAdoptInterval`:
```
  defer func(oldInterval time.Duration) {
    jobs.DefaultAdoptInterval = oldInterval
  }(jobs.DefaultAdoptInterval)
  jobs.DefaultAdoptInterval = 100 * time.Millisecond
```

Any thoughts?

**Comment by nvanbenschoten** [comment]
> This was coincidentally merged just before the add isRole column migration (causing a backfill) started failing under stress.

Have you bisected the flake or are you just speculating that this was the commit that broke things? I'm in the middle of a bisection but would love to stop it short if you've already done one!

> all four tests set are the only ones that override jobs.DefaultAdoptInterval:

I don't really have any thoughts about this yet. I don't know enough about the jobs package to know how this might impact things.

**Comment by nvanbenschoten** [comment]
I was able to narrow down the flake to this change, as @mberhault suggested.

@benesch do you know what the deal with `DefaultAdoptInterval` is? I suspect that this change is causing transactions that hit retry errors to take longer because they now retry the entire transaction. They must be bumping up against this time limit. If I double the value we use in tests, the flake goes away.

**Comment by nvanbenschoten** [comment]
Oh interesting, I think the root issue is that we just ignore txn errors in some cases like https://github.com/cockroachdb/cockroach/blob/0040846f7609d3dcf46edaac1a94cc5e70b5bb76/pkg/sql/table.go#L652-L654

This means that a retryable error will be ignored.

**Comment by benesch** [comment]
DefaultAdoptInterval isn’t a time limit; it’s the amount of time the job
registry waits between looking for abandoned jobs that need to be restarted
on a new node. Are you stressing under race? Perhaps looking for jobs every
100ms causes a read that continually bumps the txn that’s trying to mark
the schema change job as completed. I can’t imagine things being that slow
unless it’s a race build, though.

Sounds like we should look a little harder before bumping the timeout. (Or
at least file an issue to investigate further.) The aborted txn should
retry at a higher priority, right?

**Comment by nvanbenschoten** [comment]
The one I linked to there looks straight up wrong. The other two instances of this are a little more subtle. @jordanlewis do you know why the following two lines are safe? We could detect retryable errors and propagate, but I'm curious why these errors are deliberately ignored

https://github.com/cockroachdb/cockroach/blob/0040846f7609d3dcf46edaac1a94cc5e70b5bb76/pkg/sql/backfill.go#L566-L569

and 

https://github.com/cockroachdb/cockroach/blob/0040846f7609d3dcf46edaac1a94cc5e70b5bb76/pkg/sql/schema_changer.go#L479-L482

**Comment by jordanlewis** [comment]
My understanding when I wrote this was that we shouldn't bother "failing" the schema change due to errors when updating the jobs table, since doing so isn't critical for the schema change, and the schema change will eventually be retried again if we return an error at that point.

**Comment by nvanbenschoten** [comment]
Propagating errors in all three places seemed to do the trick! It's probably breaking other logic though. In general, I think we need to be very explicit about the cases where it's ok to drop an error and which errors are ok to drop.

> My understanding when I wrote this was that we shouldn't bother "failing" the schema change due to errors when updating the jobs table

Got it, thanks @jordanlewis! If we do start failing the schema change on errors when updating the jobs table will we be breaking expected behavior?

> since doing so isn't critical for the schema change

Could ignoring the error in `backfillIndexes` have allowed us to backfill at two different timestamps?

**Pull request merged**
