### PR TITLE
sql: pass statement request id to backend instead of statement fingerprint

### LINKED ISSUE #74226: Add ability to cancel statement diagnostics from the frontend
**Is your feature request related to a problem? Please describe.**
Currently, we do not have any way to cancel already created statement diagnostics from the frontend console.

**Describe the solution you'd like**
We would like to add the functionality to cancel statement diagnostic requests that are still waiting on a result. 
The backend API for this has already been created in https://github.com/cockroachdb/cockroach/issues/73863.

**Additional context**
Figma mocks: https://www.figma.com/file/xdmwvnFQd6KkO9RJ0XLDH0/22.1_SQL-obsrv_query-performance?node-id=5178%3A142577

Epic: CRDB-6619

### PR DESCRIPTION
**Pull request by THardy98**
Previously, the frontend passed a statement
fingerprint to the API to update the corresponding statement diagnostic
request to an expired state. Now we pass the statement diagnostic ID
directly. This resolves a SQL parsing error that occurs when a statement
fingerprint contains single-quotes (i.e. when a statement fingerprint
contains placeholders).

Original PR with discussions: #74818
Resolves: #74226

Release note: None

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75732)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @THardy98)

___
*[pkg/server/serverpb/status.proto, line 1289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75732#-MukqPUdDAd63k6tYtqx:-MukqPUe5vx9PntfuLt1:b-c8k4pg) ([raw file](https://github.com/cockroachdb/cockroach/blob/128eb4a8b1e7056f47adf370a94868522dd1406f/pkg/server/serverpb/status.proto#L1289)):*
> ```protobuf
> 
> message CancelStatementDiagnosticsReportRequest {
>   int64 request_id = 1 [(gogoproto.customname) = "RequestID"];
> ```

It is customary to never change the type of a proto field. Can you introduce a new field instead? Then, once the frontend is migrated over to use it, you can retire the old fingerprint field by saying `reserved 1;`.

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75732)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @dhartunian)

___
*[pkg/server/serverpb/status.proto, line 1289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75732#-MukqPUdDAd63k6tYtqx:-Mukrl710AZuidKZ3jzj:bgwtshw) ([raw file](https://github.com/cockroachdb/cockroach/blob/128eb4a8b1e7056f47adf370a94868522dd1406f/pkg/server/serverpb/status.proto#L1289)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

It is customary to never change the type of a proto field. Can you introduce a new field instead? Then, once the frontend is migrated over to use it, you can retire the old fingerprint field by saying `reserved 1;`.
</blockquote></details>

Hi David, This field was recently introduced in December and it's currently not in any release nor is it being consumed in anyway. [Previous discussion](https://github.com/cockroachdb/cockroach/pull/74818#pullrequestreview-856116324)

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75732)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @dhartunian)

___
*[pkg/server/serverpb/status.proto, line 1289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75732#-MukqPUdDAd63k6tYtqx:-MuktcT_D4G8XVkSbmCl:b-2jew3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/128eb4a8b1e7056f47adf370a94868522dd1406f/pkg/server/serverpb/status.proto#L1289)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hi David, This field was recently introduced in December and it's currently not in any release nor is it being consumed in anyway. [Previous discussion](https://github.com/cockroachdb/cockroach/pull/74818#pullrequestreview-856116324)
</blockquote></details>

Sorry yes we've discussed this already, I should have added the original PR. Added to the PR description (here for quick reference: #74818).

**Review by Azhng — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75732#-:-Mul3SUkEs3rnOvHF5Lj:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng and @dhartunian)

**Pull request merged**
