### PR TITLE
libroach,storage/engine: allow specification of arbitrary RocksDB options

### LINKED ISSUE #21434: engine: RocksDB read/write/space tuning
RocksDB offers a lot of settings that affect various [tradeoffs](http://rocksdb.blogspot.com/2013/10/SparrowTheorem.html) between read performance, write performance, and space amplification. We have mostly tuned these to improve read and write performance at the expense of increased space amplification, but some users may have different preferences. 

We should give users some way to select different rocksdb configurations. Exposing the entire set of rocksdb options would be relatively straightforward for us but daunting for the users. A few different "profiles" (read-optimized, space-optimized, etc) would be easier if we could identify a few sweet spots in the massive configuration space.

### PR DESCRIPTION
**Pull request by petermattis**
Allow specification of arbitrary RocksDB options by extending the
store-spec syntax to to include a `rocksdb=<options>` field. The RocksDB
options are a semicolon separated list of `key=value` pairs. The easiest
way to see the various RocksDB options is to look in
`<store-dir>/OPTIONS-xyz`.

Options in the `DBOptions` and `CFOptions` sections can be specified using
the base `key=value` syntax. For example, to change the
`DBOptions.WAL_ttl_seconds` option, specifying
`rocksdb=WAL_ttl_seconds=60`.

Options in the `TableOptions/BlockBasedTable` section are specified using a
"nested options" syntax. For example,
`rocksdb=block_based_table_factory={block_size=4k}` will set the
`block_size` to 4 KB. Note that the syntax described here is provided from
RocksDB.

Fixes #21434

Release note (cli change): Allow specification of arbitrary RocksDB
options.

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/base/store_spec_test.go, line 37 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22401#-L4cjYKiP6RIknW1up7l:-L4cjYKiP6RIknW1up7m:b-d1bcuc) ([raw file](https://github.com/cockroachdb/cockroach/blob/19830cd23833412e34d50fee2e9b449d172b49c2/pkg/base/store_spec_test.go#L37)):*
> ```Go
> 	}{
> 		// path
> 		{"path=/mnt/hda1", "", StoreSpec{Path: "/mnt/hda1"}},
> ```

I changed all of the test cases to use explicit field initialization syntax to ease extending `StoreSpec` in the future. The other option was to add a `""` string for the `StoreSpec.RocksDB` field which would have been both less obvious and less future proof.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22401)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22401#-:-L4gGQ_VXtPLLUH6Uq9Y:bnfp4nl)*

**Comment by bdarnell** [comment]
We can also get rid of the block size and WAL TTL environment variables and use this mechanism instead.

**Comment by petermattis** [comment]
> We can also get rid of the block size and WAL TTL environment variables and use this mechanism instead.

Good point. I'll send a follow-up PR.

**Pull request merged**
