### PR TITLE
cli: clean up the rendering of pretty-printed tables.

### PR DESCRIPTION
**Pull request by knz**
Due to a bug in the upstream library that caused it to unduly strip
leading spaces, the patch in f839e1a39a569b0a9efe593dcbd53877d9e7007c
had to force the rendering of said spaces by adding an invisible
Unicode character at the beginning of the table values.

Since the upstream library is now fixed, and to avoid any problem with
poor Unicode renderers that do not support the LTR marker properly,
this patch updates the upstream dependency and removes the kludge.

Pretty-printed tables are now clean and can be safely copy-pasted from
a terminal to elsewhere.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13095)

### CODE REVIEW

**Comment by dt** [comment]
I'm assuming you just edited the glide.lock revision and ran `glide install` to bump it?

LGTM, though should check with @tamird, since he mentioned elsewhere that since a RocksDB upgrade is in progress, we might want to wait on dep bumps to reduce rebasing required.

**Comment by tamird** [comment]
@petermattis for the rocksdb upgrade status

**Comment by petermattis** [comment]
Don't let the RocksDB upgrade block anything. I imagine I'll have to regenerate `vendor` a few times before it merges.

**Comment by knz** [comment]
So this one is gtg?

**Comment by dt** [comment]
Yep.

**Comment by knz** [comment]
TFYR

**Pull request merged**
