### PR TITLE
kvcoord: bump default value of max_refresh_span_bytes to 4MB

### PR DESCRIPTION
**Pull request by arulajmani**
We recently saw an escalation where the default value of
`kv.transaction.max_refresh_span_bytes` was causing degraded
performance. This patch bumps the default value for this setting to 4MB
bringing it in line with our recent change to
 `kv.transaction.max_intent_bytes`.

Release note (ops change): increase the default value of
`kv.transaction.max_refresh_span_bytes` from 256KB to 4MB.

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm: thanks!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80115#-:-N-xxTFu7C1v75j1T-zl:brfqlux)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by arulajmani** [comment]
TFTR! bors r+

@nvanbenschoten how do you feel about backporting this to the 22.1.1 release? Or should a default value change like this wait until 22.2.0?

**Comment by nvanbenschoten** [comment]
Let's wait until 22.2.0 for this change. We can revisit that decision if this comes up again, once we're past the initial patch releases for 22.1 and have more confidence that there is no fallout in nightly tests from this change.

**Comment by yuzefovich** [comment]
I believe this change is the cause of a regression in `tpch_concurrency` [roachtest](https://roachperf.crdb.dev/?filter=&view=tpch_concurrency&tab=gce). That test attempts to find the maximum concurrency of TPCH queries that a 3 node roachprod cluster can sustain without OOMing. Before about two days ago that concurrency was roughly in [70, 80] range, but two days ago (as well as the following day) it was recorded as 48 (which is the lower bound of our search, so the actual value might be lower).

True, TPCH is an OLAP benchmark, and CRDB is not really an OLAP database, still it might be worth looking into this more. At least we might want to hook up this KV-related setting to the memory accounting system.

**Pull request merged**
