### PR TITLE
storage,server,sql: capture and expose filesystem details in store descriptors

### LINKED ISSUE #64326: kv,sql: expose store IDs and their location on disk and other parameters in vtable
There is currently no mechanism to map back store Ids to locations on disk, max size and the other command-line parameters.

The workaround is to assign different store attributes in the command line to each store, and then map the store ID to attribute using APIs, then attribute to file path using the command line.

It would be easier to integrate the two steps somehow.

### PR DESCRIPTION
**Pull request by knz**
Fixes #64326. 

See the individual commits for details.

Example use:

```
root@:26257/defaultdb> select node_id, store_id,
  properties->'file_store_properties'->'fs_type' as fs
  from crdb_internal.kv_store_status;

  node_id | store_id |  fs
----------+----------+--------
        1 |        1 | "zfs"
(1 row)
```

This also enables collecting the filesystem information in the output
of `debug zip`.

Release note (sql change): Some filesystem-level properties are now
exposed in `crdb_internal.kv_store_status`. Note that the particular
fields and layout are not stabilized yet.

### CODE REVIEW

**Review by stevendanna — COMMENTED** [review]
This seems like a pretty reasonable feature! 

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 9 of 9 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72435#-:-Mo3y3WpBXyRzUYDFpuE:b-iv4ux3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @jbowens, and @knz)

___
*[pkg/storage/store_properties.go, line 57 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72435#-Mo3xKH52iTeFfDxabpT:-Mo3xKH52iTeFfDxabpU:b53xw1g) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c4660cbe1dd9637fb6e1c839d357d8138123c20/pkg/storage/store_properties.go#L57)):*
> ```Go
> 	//
> 	// Note that scanning the list of mounts is also
> 	// what linux' df(1) command does.
> ```

Yup, this is the canonical way to do it on linux as far as I have seen.
___
*[pkg/storage/store_properties.go, line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72435#-Mo3rSOc-xPu7EmV1hhK:-Mo3rSOc-xPu7EmV1hhL:bbw0r5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c4660cbe1dd9637fb6e1c839d357d8138123c20/pkg/storage/store_properties.go#L68)):*
> ```Go
> 	for i := len(fslist.List) - 1; i >= 0; i-- {
> 		// filepath.Rel can relyably tell us if a path is relative to
> 		// another: if it is not, an error is returned.
> ```

s/relyably/reliably/
___
*[pkg/storage/store_properties.go, line 69 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72435#-Mo3tZ8U4bwm8Imbfyi9:-Mo3tZ8V6z5RheCMJvLz:bymfkha) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c4660cbe1dd9637fb6e1c839d357d8138123c20/pkg/storage/store_properties.go#L69)):*
> ```Go
> 		// filepath.Rel can relyably tell us if a path is relative to
> 		// another: if it is not, an error is returned.
> 		_, err := filepath.Rel(fslist.List[i].DirName, absPath)
> ```

I haven't tested either of these, but two things I would look out for here:

*nested mount points*

Depending on the order that we process the mount file, I'm not sure this will always select the closest match. For instance, what happens if a user has a filesystem mount at `/foo` and `/foo/a` and our absPath is `/foo/a/b`.  The right answer is `/foo/a`, but if we see `/foo` first, then I think we'll get the wrong answer? 

*paths with spaces*

This is an edge case we might not need to worry about, but I'll mention it for completeness.  In gosigar, it looks like they are parsing /etc/mtab. On linux that file escapes various forms of white space that might appear in mount paths in the same way as described in:

https://man7.org/linux/man-pages/man3/getmntent.3.html

I don't see any parsing of those escape characters in gosigar. I haven't tested it, but my guess is that this might end up being incorrect for filesystems with spaces in it.

**Review by dhartunian — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 9 of 9 files at r3, 5 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72435#-:-Mo4A1tdEIzYk-qaA7Mo:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens and @knz)

___
*[pkg/kv/kvserver/store.go, line 2516 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72435#-Mo4EJZZAQsTVeGtktMv:-Mo4EJZZAQsTVeGtktMw:b-cq8s50) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ec64415024ab506a9bed78e6a27201364f979e/pkg/kv/kvserver/store.go#L2516)):*
> ```Go
> // Properties returns the properties of the underlying store.
> func (s *Store) Properties() roachpb.StoreProperties {
> 	return s.engine.Properties()
> ```

nit: just a small docstring question: are these properties of the store or the engine? it's a bit confusing to me to have store info computed in the engine which seems like it's lower in the abstraction tree...but looking at engine.go it seems like we have other store-specific stuff in there already.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72435)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian, @jbowens, @knz, and @stevendanna)

___
*[pkg/kv/kvserver/store.go, line 2516 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72435#-Mo4EJZZAQsTVeGtktMv:-Mo8HPsFByNmveha9iua:bdez4k9) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ec64415024ab506a9bed78e6a27201364f979e/pkg/kv/kvserver/store.go#L2516)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: just a small docstring question: are these properties of the store or the engine? it's a bit confusing to me to have store info computed in the engine which seems like it's lower in the abstraction tree...but looking at engine.go it seems like we have other store-specific stuff in there already.
</blockquote></details>

We have a 1-1 mapping between engine and store.
- Engine: a low-level storage abstraction, hidden behind the Store abstraction.
- Store: the abstraction visible from the server package and other places.

The reason why these properties are defined in the engine is that it's the only place where we know the filesystem directory path. The Store abstraction knows nothing of how an Engine persists data.
___
*[pkg/storage/store_properties.go, line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72435#-Mo3rSOc-xPu7EmV1hhK:-Mo8HrmH-p8MKAJiYu1B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c4660cbe1dd9637fb6e1c839d357d8138123c20/pkg/storage/store_properties.go#L68)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

s/relyably/reliably/
</blockquote></details>

Done.
___
*[pkg/storage/store_properties.go, line 69 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72435#-Mo3tZ8U4bwm8Imbfyi9:-Mo8HtOmE0xfYHiVkAmY:bcf6983) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c4660cbe1dd9637fb6e1c839d357d8138123c20/pkg/storage/store_properties.go#L69)):*
> Depending on the order that we process the mount file

Correct me if I'm wrong, but the mtab is ordered by mount operation: later mounts (in time) appear later in the file. Because one can only mount filesystems "on top" of each other (and an earlier mount cannot be undone until all the later mounts under it are undone), the closest match is necessarily first when starting from the end of the file.

> This is an edge case we might not need to worry about

This is, if confirmed, an issue with the upstream gosigar package. If you would like this to be addressed, I'd encourage you to file an issue upstream.

**Review by stevendanna — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72435)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian, @jbowens, @knz, and @stevendanna)

___
*[pkg/storage/store_properties.go, line 69 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72435#-Mo3tZ8U4bwm8Imbfyi9:-Mo8VDSA1DenPgK7GcP4:bltt2j7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c4660cbe1dd9637fb6e1c839d357d8138123c20/pkg/storage/store_properties.go#L69)):*
> when starting from the end of the file.

Wowzers, completely read past the fact that we were reading this in reverse order, sorry about that. Given that, I believe this should be fine.  Might be worth a comment above the loop iteration, but I leave that to your judgement. 

> This is, if confirmed, an issue with the upstream gosigar package. If you would like this to be addressed, I'd encourage you to file an issue upstream.

I'll make a TODO here to follow up at somepoint.  Since there is no harm (we just don't get fs info), it certainly isn't blocking.

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72435)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian, @jbowens, @knz, and @stevendanna)

___
*[pkg/storage/store_properties.go, line 69 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72435#-Mo3tZ8U4bwm8Imbfyi9:-Mo8W3e51RlhHgLR6rCF:bjpmyna) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c4660cbe1dd9637fb6e1c839d357d8138123c20/pkg/storage/store_properties.go#L69)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

> when starting from the end of the file.

Wowzers, completely read past the fact that we were reading this in reverse order, sorry about that. Given that, I believe this should be fine.  Might be worth a comment above the loop iteration, but I leave that to your judgement. 

> This is, if confirmed, an issue with the upstream gosigar package. If you would like this to be addressed, I'd encourage you to file an issue upstream.

I'll make a TODO here to follow up at somepoint.  Since there is no harm (we just don't get fs info), it certainly isn't blocking.

</blockquote></details>

By 'make a TODO here', I mean on my personal TODO list, nothing else is need in this PR I think.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72435)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian, @jbowens, @knz, and @stevendanna)

___
*[pkg/storage/store_properties.go, line 69 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72435#-Mo3tZ8U4bwm8Imbfyi9:-Mo8dH4g9hLTJ6wU-Vi7:b-l723wq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c4660cbe1dd9637fb6e1c839d357d8138123c20/pkg/storage/store_properties.go#L69)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

By 'make a TODO here', I mean on my personal TODO list, nothing else is need in this PR I think.
</blockquote></details>

added an explanatory comment.

**Comment by knz** [comment]
TFYRs!

bors r=dhartunian,stevendanna

**Pull request merged**
