### PR TITLE
build: re-add a Go toolchain to {gce,az}workers

### PR DESCRIPTION
**Pull request by petermattis**
Add bootstrap-ssd.sh for bootstrapping Google Local SSD devices.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13589)

### CODE REVIEW

**Comment by petermattis** [comment]
@tamird I can maintain this branch locally if you feel this will be too onerous to maintain if merged.

**Comment by tamird** [comment]
Merp, I would prefer that we not merge this.

**Comment by petermattis** [comment]
> Merp, I would prefer that we not merge this.

Would it be more palatable if I indicated in a comment that you do not need to maintain `bootstrap-go.sh`? The changes to the other files are minimal.

**Comment by tamird** [comment]
Maintenance isn't the reason for my objection - it's that the presence of
this step in bootstrapping requires recreation of workers on version bumps.

**Comment by petermattis** [comment]
> it's that the presence of this step in bootstrapping requires recreation of workers on version bumps.

`bootstrap/bootstrap-go.sh` can be re-run with a different Go version. For minor version bumps the script doesn't even need to be updated other than changing the GOVERSION env var. And recreating a worker is intentionally supposed to be easy.

**Comment by tamird** [comment]
I'll say this one last time: adding more non-release toolchains is a step
in the wrong direction.

Your stamina exceeds mine, so go ahead and merge if you remain unmoved.

**Review by bdarnell — APPROVED** [review]
LGTM. I'd also like to have a toolchain on the VM itself instead of just in docker.

**Comment by petermattis** [comment]
> I'll say this one last time: adding more non-release toolchains is a step in the wrong direction.

Ok, we'll have to agree to disagree about this. It's possible that I'm not understanding your objection correctly, but in the short term it doesn't appear onerous to support a native Go toolchain on the workers and it is a decision we can easily revisit in the future.

**Comment by tamird** [comment]
The major objection is not that it's onerous, rather that it is more likely
to produce non-release behaviour. We use a very special toolchain to
produce our release builds, and to use yet another one (in addition to the
one we use on macOS, say) is a step backwards.

**Comment by petermattis** [comment]
I'm merging because I'm pretty sure we're not going to reach agreement.

> The major objection is not that it's onerous, rather that it is more likely to produce non-release behaviour.

Have we ever seen a bug that has been caused by using a non-release toolchain?

**Pull request merged**
