### PR TITLE
*: enable span configs by default

### PR DESCRIPTION
**Pull request by irfansharif**
We were previously using an opt-in flag to enable span configs; this
commit flips it into an opt-out one. This has the following effects:
- fresh crdb nodes/clusters run with span configs enabled.
- our entire test suite runs using the span configs infrastructure, save
   for a select few written:
     - with the gossipped system config span in mind;
     - using legacy testing harnesses that prevent injection of
        spanconfig dependencies due to circular imports.

We also introduce a more minified form of the opt-out testing flag:
UseSystemConfigSpanForQueues. Using the minified form still enables the
SQL-side of span configs to run (Reconciler, SQLWatcher, SQLTranslator)
but defaults to using the system config span down in KV.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
Heads up, you can use draft PRs to avoid sending out emails.

**Review by ajwerner — COMMENTED** [review]
No major concerns from me. What is this missing? 

> Reviewed 86 of 86 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73876#-:-MsjoleRBrWmB0CFQgIW:bre1n9v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @irfansharif, and @nvanbenschoten)

___
*[pkg/ccl/backupccl/backup_test.go, line 6896 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73876#-Msjo3nH6TqwbFAteYUF:-Msjo3nH6TqwbFAteYUG:blq4dd5) ([raw file](https://github.com/cockroachdb/cockroach/blob/51164a3a3df34596eb1e163d9db6e9fd2760f315/pkg/ccl/backupccl/backup_test.go#L6896)):*
> ```Go
> 		}
> 		return nil
> 	})
> ```

what's this about?



_Code quote:_
```Go
	testutils.SucceedsSoon(t, func() error {
		if numExportRequests != 5 {
			return errors.Newf("expected 5 export requests, got %d", numExportRequests)
		}
		if len(expected) != len(exportRequestSpans) {
			return errors.Newf("expected %d export request spans, got %d", len(expected), len(exportRequestSpans))
		}
		return nil
	})
```
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 3582 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73876#-MsjoImW4VBsC0Hyt22Q:-MsjoImW4VBsC0Hyt22R:bd8d7u9) ([raw file](https://github.com/cockroachdb/cockroach/blob/51164a3a3df34596eb1e163d9db6e9fd2760f315/pkg/ccl/changefeedccl/changefeed_test.go#L3582)):*
> ```Go
> 			sqlDB := sqlutils.MakeSQLRunner(db)
> 			sqlDB.Exec(t, `ALTER RANGE default CONFIGURE ZONE USING gc.ttlseconds = 100`)
> 			sqlDB.Exec(t, `ALTER RANGE system CONFIGURE ZONE USING gc.ttlseconds = 100`)
> ```

why do we need this?



_Code quote:_
```Go
			sqlDB.Exec(t, `ALTER RANGE default CONFIGURE ZONE USING gc.ttlseconds = 100`)
			sqlDB.Exec(t, `ALTER RANGE system CONFIGURE ZONE USING gc.ttlseconds = 100`)
```

**Review by irfansharif — COMMENTED** [review]
Nothing's missing (🤞), just the rubber stamp.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73876#-:-MsjxwKjBsqctycvHSWZ:b-qbx1nx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @nvanbenschoten)

___
*[pkg/ccl/backupccl/backup_test.go, line 6896 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73876#-Msjo3nH6TqwbFAteYUF:-Msjx27U5k3EO_HH33b-:b-ash0ks) ([raw file](https://github.com/cockroachdb/cockroach/blob/51164a3a3df34596eb1e163d9db6e9fd2760f315/pkg/ccl/backupccl/backup_test.go#L6896)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

what's this about?
</blockquote></details>

From the commit message:

```
backupccl: future-proof TestPaginatedBackupTenant

This is Yet Another Test that made timing assumptions on how
instantaneously range split decisions appear, assumptions that don't
hold under the span configs infrastructure.  Adding compatibility is a
matter of waiting for splits to appear instead of only expecting it.

Release note: None
```

(This commit was actually part of #74265.)



_Code quote:_
```Go
 TestPaginatedBackupTenant
```
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 3582 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73876#-MsjoImW4VBsC0Hyt22Q:-MsjxlVoBsvGEicGUuMj:b-gll4ik) ([raw file](https://github.com/cockroachdb/cockroach/blob/51164a3a3df34596eb1e163d9db6e9fd2760f315/pkg/ccl/changefeedccl/changefeed_test.go#L3582)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

why do we need this?
</blockquote></details>

From the commit message:

```
changefeedccl: future-proof TestChangefeedProtectedTimestamps

The low gc.ttlseconds in this test that applies to
system.{descriptor,zones}, when run with span configs enabled (in a
future commit), runs into errors introduced in #73086. The span configs
infrastructure makes use of rangefeeds against these tables within the
spanconfig.SQLWatcher process. These rangefeeds error out if the
timestamp they're started with is already GC-ed, something that's very
likely with low GC TTLs. To accommodate, we simply bump the TTL to a
more reasonable 100s.

Release note: None
```

(This commit was also actually part of #74265.)



_Code quote:_
```Go
INSERT INTO foo VALUES (1, 'a'), (2, 'b'), (4, 'c'),
```

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73876)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @irfansharif, and @nvanbenschoten)

___
*[pkg/ccl/backupccl/backup_test.go, line 6896 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73876#-Msjo3nH6TqwbFAteYUF:-MsjzJNc1ZwqZAZz1rUB:b1b15af) ([raw file](https://github.com/cockroachdb/cockroach/blob/51164a3a3df34596eb1e163d9db6e9fd2760f315/pkg/ccl/backupccl/backup_test.go#L6896)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

From the commit message:

```
backupccl: future-proof TestPaginatedBackupTenant

This is Yet Another Test that made timing assumptions on how
instantaneously range split decisions appear, assumptions that don't
hold under the span configs infrastructure.  Adding compatibility is a
matter of waiting for splits to appear instead of only expecting it.

Release note: None
```

(This commit was actually part of #74265.)
</blockquote></details>

What I don't get is how retrying helps. You're not retrying the job, right? If the backup ran and the splits were no there, then what?

**Review by ajwerner — COMMENTED** [review]
When CI is happy, I'm happy, though I would like to understand the circularity thing 

> Reviewed 10 of 86 files at r2, 16 of 28 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73876#-:-MtO9JjwBI8ks5GJEOSU:b-68fjs3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @irfansharif, and @nvanbenschoten)

___
*[pkg/migration/migrations/migrate_span_configs.go, line 38 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/73876#-MtO6xEH8dZ3W8bhqvmT:-MtO6xEH8dZ3W8bhqvmU:b-2ra62b) ([raw file](https://github.com/cockroachdb/cockroach/blob/93b8a2f8cf3ea439cdb741a8ec548405e1d0e13e/pkg/migration/migrations/migrate_span_configs.go#L38)):*
> ```Go
> 		row, err := d.InternalExecutor.QueryRowEx(ctx, "get-spanconfig-progress", nil,
> 			sessiondata.NodeUserSessionDataOverride,
> 			`SELECT progress FROM system.jobs WHERE id = (SELECT job_id FROM [SHOW AUTOMATIC JOBS] WHERE job_type = 'AUTO SPAN CONFIG RECONCILIATION')`)
> ```

nit: format this
___
*[pkg/migration/migrations/migrate_span_configs.go, line 43 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/73876#-MtO73zkEBGXFFy73eh9:-MtO73zkEBGXFFy73ehA:bd1wma8) ([raw file](https://github.com/cockroachdb/cockroach/blob/93b8a2f8cf3ea439cdb741a8ec548405e1d0e13e/pkg/migration/migrations/migrate_span_configs.go#L43)):*
> ```Go
> 		}
> 		if row == nil {
> 			log.Warningf(ctx, "reconciliation job not found")
> ```

Seems like this can be info. Also, if you're going to log every time, set your backoff to be longer or use a log.Every
___
*[pkg/migration/migrations/migrate_span_configs.go, line 55 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/73876#-MtO7I6a75K6CcblrgwN:-MtO7I6a75K6CcblrgwO:b-sgyu3k) ([raw file](https://github.com/cockroachdb/cockroach/blob/93b8a2f8cf3ea439cdb741a8ec548405e1d0e13e/pkg/migration/migrations/migrate_span_configs.go#L55)):*
> ```Go
> 		}
> 		if sp.AutoSpanConfigReconciliation.Checkpoint.IsEmpty() {
> 			log.Warningf(ctx, "waiting for span config reconciliation...")
> ```

why Warning?
___
*[pkg/testutils/localtestcluster/local_test_cluster.go, line 119 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/73876#-MtO7twq6Iv0HFUfmj5S:-MtO7twq6Iv0HFUfmj5T:b-6b0sjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/93b8a2f8cf3ea439cdb741a8ec548405e1d0e13e/pkg/testutils/localtestcluster/local_test_cluster.go#L119)):*
> ```Go
> 	// Because we create the stores from scratch here, enabling span configs
> 	// requires initializing the spanconfigkvsubscriber -- a dependency we can't
> 	// (easily) pick up here.
> ```

I don't understand this, isn't this code set up so we can exactly do that sort of thing? I think it's kind of important to understand the circularity. 



_Code quote:_
```Go
	// requires initializing the spanconfigkvsubscriber -- a dependency we can't
	// (easily) pick up here.
```
___
*[pkg/ccl/importccl/exportcsv_test.go, line 57 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/73876#-MtO8NgV7iSR_Fw_HktN:-MtO8NgV7iSR_Fw_HktO:bsthij6) ([raw file](https://github.com/cockroachdb/cockroach/blob/93b8a2f8cf3ea439cdb741a8ec548405e1d0e13e/pkg/ccl/importccl/exportcsv_test.go#L57)):*
> ```Go
> 				ExternalIODir:      dir,
> 				UseDatabase:        "test",
> 				DisableSpanConfigs: true,
> ```

Is there a solution to this other than disabling it? For example, setting the closed timestamps to be short and waiting for things to propagate? We'll need to do such a thing sooner or later. It'll be painful to find later.

**Review by irfansharif — COMMENTED** [review]
Running a few more CI runs over the weekend to see what shakes out.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73876#-:-MtQTRH03de3VXIy-4FQ:b-8ev4gf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @nvanbenschoten)

___
*[pkg/testutils/localtestcluster/local_test_cluster.go, line 119 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/73876#-MtO7twq6Iv0HFUfmj5S:-MtQLwW3DJi8-jLlR092:b23y4v0) ([raw file](https://github.com/cockroachdb/cockroach/blob/93b8a2f8cf3ea439cdb741a8ec548405e1d0e13e/pkg/testutils/localtestcluster/local_test_cluster.go#L119)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't understand this, isn't this code set up so we can exactly do that sort of thing? I think it's kind of important to understand the circularity. 
</blockquote></details>

Needed a few supporting PRs to make happen (#74865, #74884); removed the limitation in appended commit.
___
*[pkg/ccl/backupccl/backup_test.go, line 6896 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73876#-Msjo3nH6TqwbFAteYUF:-MtQMBOr3q9W_WmXwJwz:b9yunvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/51164a3a3df34596eb1e163d9db6e9fd2760f315/pkg/ccl/backupccl/backup_test.go#L6896)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

What I don't get is how retrying helps. You're not retrying the job, right? If the backup ran and the splits were no there, then what? 
</blockquote></details>

Dropped this commit in #74265.
___
*[pkg/ccl/importccl/exportcsv_test.go, line 57 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/73876#-MtO8NgV7iSR_Fw_HktN:-MtQMWhA-iL5U75cGmrQ:b-r9q25u) ([raw file](https://github.com/cockroachdb/cockroach/blob/93b8a2f8cf3ea439cdb741a8ec548405e1d0e13e/pkg/ccl/importccl/exportcsv_test.go#L57)):*
It wasn't disabled here because of timing delays, it was because of this test's use of TestingSetupZoneConfigHook. I agree we need to update this test sooner or later, I'd rather us do it later. 

> It'll be painful to find later.

I've made it so that search for all uses of DisableSpanConfigs would be sufficient. Does this work for now?

**Review by ajwerner — APPROVED** [review]
:lgtm: :rocket: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73876#-:-MtZGqzYDaPG0EJrsDR-:byykejp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @irfansharif, and @nvanbenschoten)

___
*[pkg/kv/kvclient/rangefeed/rangefeedadaptor/main_test.go, line 34 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/73876#-MtZH7D70XhDiSUFnpFQ:-MtZH7D70XhDiSUFnpFR:b6i4suu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5611c4d968bb1f919dbffe227180b3b9f860a006/pkg/kv/kvclient/rangefeed/rangefeedadaptor/main_test.go#L34)):*
> ```Go
> }
> 
> //go:generate ../../../util/leaktest/add-leaktest.sh *_test.go
> ```

needs an extra `../`

**Review by irfansharif — COMMENTED** [review]
Thanks for the review! I'll let it go through one more CI run before borsing (also letting #74865 land). Though separate commits, the intermediate state between these commits breaks one test or another. Now that it's reviewed, we can either (a) squash them all into a mega commit, or (b) note that if reverting, we'd have to do it for the set of commits all at once. I'm going to go with (b).

Note: Given the blast radius of this PR, I'll count myself lucky if we _didn't_ have to revert these changes once or twice. Hopefully it's not terribly disruptive.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73876#-:-MtccxIK50lpjRmv5QpX:b-2pzybp)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, and @nvanbenschoten)

___
*[pkg/kv/kvclient/rangefeed/rangefeedadaptor/main_test.go, line 34 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/73876#-MtZH7D70XhDiSUFnpFQ:-MtccrInENhea9eNfmzX:b-m75u4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/5611c4d968bb1f919dbffe227180b3b9f860a006/pkg/kv/kvclient/rangefeed/rangefeedadaptor/main_test.go#L34)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

needs an extra `../`
</blockquote></details>

Dropped #74884 (this commit) from the PR.

**Comment by irfansharif** [comment]
Something's up with team city.

bors r-

**Pull request merged**
