### PR TITLE
opt: check for NULL values in tuple inequalities

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: check for NULL values in tuple inequalities

`(@1, @2) >= (1, NULL)` is equivalent to `@1 > 1`. It now results in
span `[/2 - ]` instead of the incorrrect `(/1/NULL - ]`.

Release note: None

#### opt: support nullable columns for tuple inequalities

The current code for tuple inequalities assumes not-nullable columns.

Consider `(a, b, c) <= (1, 2, 3)`.

If the columns are not null, the condition is equivalent to
the span `[ - /1/2/3]`.

If column `a` is nullable, the condition is equivalent to the
span `(/NULL - /1/2/3]`.

However, if column `b` or `c` is nullable, we still have to
filter out the NULLs on those columns, so whatever span we
generate is not "tight".

Also adding logic tests with tuple inequalities and NULLs (note that they don't
exercise `opt` code right now but they will when we switch).

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-:-L1TxeBKphY42NT4Sdgt:bnfp4nl)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/opt/index_constraints.go, line 145 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-L1TyAn-DcNbJSnKGT-N:-L1TyAn-DcNbJSnKGT-O:b-lwa4t2) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd0b53a13535b32f04fdc4ed86db82b58ef95d32/pkg/sql/opt/index_constraints.go#L145)):*
> ```Go
> 	// Check for NULL values in the tuple.
> 	for _, child := range rhs.children {
> 		if child.op == constOp && child.private.(tree.Datum) == tree.DNull {
> ```

I think that can be `child.private == tree.DNull`. The type assertion to `(tree.Datum)` shouldn't be necessary. Maybe.

Might be worth adding an `isConstNull` method. I bet this will come up again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-:-L1TyQe2vOmA_A1cg04Z:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Wait, I don't think this is right. In #12022 it is pointed out that comparison is lexicographic, so for example `(3, 4) > (2, NULL)` is true (whereas `(2, 4) > (2, NULL)` is NULL). Always helps to think "unknown" instead of "null".

**Comment by RaduBerinde** [comment]
Updated, PTAL.   @knz - it would be great if you can take a look and confirm that I'm correct regarding the semantics.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/opt/index_constraints.go, line 145 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-L1TyAn-DcNbJSnKGT-N:-L1U61i2FVb67eyufPEo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd0b53a13535b32f04fdc4ed86db82b58ef95d32/pkg/sql/opt/index_constraints.go#L145)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think that can be `child.private == tree.DNull`. The type assertion to `(tree.Datum)` shouldn't be necessary. Maybe.

Might be worth adding an `isConstNull` method. I bet this will come up again.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-:-L1U62kyMsn5HnCHGJFV:b-8okvso)*

**Comment by RaduBerinde** [comment]
Still a problem here, we are not excluding NULLs from the spans. Will work on it some more tomorrow.

**Comment by knz** [comment]
Yes correct that tuple comparison *should* be lexicographic. I can't seem to find it in the SQL standard but your point that "null" really *means* "unknown" (and that's clearly specified in the SQL standard) is spot on.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-:-L1WzS8punU5mHGWVi-X:bkxxczk)*

**Comment by knz** [comment]
Also FWIW both pg and crdb currently get this right.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-:-L1Wzk3svHmRp6jJGhJ6:b-fv7h0j)*

**Comment by RaduBerinde** [comment]
Thanks Raphael!

I added another commit that corrects the results for tuple inequalities when columns are nullable. PTAL, it would especially help to look over the changed testcases and confirm the new results make sense.

**Comment by knz** [comment]
Reviewed 3 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/testdata/index-constraints, line 614 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-L1XQerpY3qKFQfndhxU:-L1XQerpY3qKFQfndhxV:bpi35zn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1dc64764cf41a3b36a9776ee3e13a1621c64ff3/pkg/sql/opt/testdata/index-constraints#L614)):*
> ```
> (@1, @2, @3) > (1, 2, 3)
> ----
> [ - /1/2/4]
> ```

aw, I do not understand this test. Why is /1/2/4 an upper bound here? Is it because the `desc` specifies inverts the meaning of `>`?

---

*[pkg/sql/opt/testdata/index-constraints, line 629 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-L1XQzUuUriI091-GcHn:-L1XQzUuUriI091-GcHo:b-6j2q3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1dc64764cf41a3b36a9776ee3e13a1621c64ff3/pkg/sql/opt/testdata/index-constraints#L629)):*
> ```
> 
> build-scalar,normalize,index-constraints vars=(int, int, int) index=(@1, @2, @3)
> (@1, @3, @2) != (1, NULL, 2)
> ```

this test and those below I understand.

---

*[pkg/sql/opt/testdata/index-constraints, line 673 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-L1XRBGj0jHMqdhfXUbl:-L1XRBGj0jHMqdhfXUbm:b-i2oy) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1dc64764cf41a3b36a9776ee3e13a1621c64ff3/pkg/sql/opt/testdata/index-constraints#L673)):*
> ```
> (@1, @2) <= (1, NULL)
> ----
> (/NULL - /0]
> ```

This one again I'm confused, why is this not `( - /0]`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/testdata/index-constraints, line 614 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-L1XQerpY3qKFQfndhxU:-L1XV1vAn5R0q1RIJti2:b9f5xi4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1dc64764cf41a3b36a9776ee3e13a1621c64ff3/pkg/sql/opt/testdata/index-constraints#L614)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

aw, I do not understand this test. Why is /1/2/4 an upper bound here? Is it because the `desc` specifies inverts the meaning of `>`?
</blockquote></details>

Sort of, the span is flipped when the columns are desc. The meaning of `>` doesn't change, we still want all values >= 1,2,4.

---

*[pkg/sql/opt/testdata/index-constraints, line 629 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-L1XQzUuUriI091-GcHn:-L1XVZ18MyqGJAcFZjvY:bwl4t5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1dc64764cf41a3b36a9776ee3e13a1621c64ff3/pkg/sql/opt/testdata/index-constraints#L629)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

this test and those below I understand.
</blockquote></details>

There is a TODO above somewhere, we are not doing as well as we could with != when some of the columns are null or not in the index.

In the tests below, we can only use a prefix of the inequality, because the index is just on @1, @2, so we still need to evaluate the filter.

---

*[pkg/sql/opt/testdata/index-constraints, line 673 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-L1XRBGj0jHMqdhfXUbl:-L1XW5Kxstg3NQm8Fso1:b-srw1ia) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1dc64764cf41a3b36a9776ee3e13a1621c64ff3/pkg/sql/opt/testdata/index-constraints#L673)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This one again I'm confused, why is this not `( - /0]`?
</blockquote></details>

We need to exclude NULLs on @1. A row like `NULL, x` is not `<= (1, NULL)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107)*

**Comment by RaduBerinde** [comment]
@petermattis and/or @rytaft - I would appreciate one more look over the code (I had the semantics wrong the first time around). Thanks!

**Comment by petermattis** [comment]
Roger, I'm offline in 5m and won't be back on until later tonight.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-:-L1Yo68Cp5sheQV_gM8l:bhcrvad)*

**Comment by rytaft** [comment]
Added a couple of comments below.

---

Reviewed 1 of 3 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/index_constraints.go, line 230 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-L1Z1fKccPgHusyXpC9u:-L1Z1fKccPgHusyXpC9v:b9n6fbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1dc64764cf41a3b36a9776ee3e13a1621c64ff3/pkg/sql/opt/index_constraints.go#L230)):*
> ```Go
> 		//   (a, b) > (1, NULL)
> 		//   (a, b) >= (1, NULL)
> 		// are exactly equivalent to
> ```

This "exactly equivalent" comment confused me since you've just pointed out that `(1, 2) > (1, NULL)` is NULL, not false.  It might help future readers if you extend this comment to say that when used as a predicate in a where clause, NULL has the same effect as false.

---

*[pkg/sql/opt/index_constraints.go, line 263 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-L1ZC2IrHo7kMxAhhf8g:-L1ZC2IrHo7kMxAhhf8h:b-xyz451) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1dc64764cf41a3b36a9776ee3e13a1621c64ff3/pkg/sql/opt/index_constraints.go#L263)):*
> ```Go
> 	// However, if column b or c is nullable, we still have to
> 	// filter out the NULLs on those columns, so whatever span we
> 	// generate is not "tight".
> ```

Is `NULL` ordered before all other values in the span?  If so, I think this statement only holds for the  `<` and `<=` operators.  For the expression:
`(a, b, c) >= (1, 2, 3)`, I believe the span `[/1/2/3 - ]` is tight.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-:-L1ZHHT8ja2gcuAmkRjq:b477who)*

**Comment by petermattis** [comment]
:lgtm:

NULLs are such a pain.

---

Review status: 1 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/sql/opt/testdata/index-constraints, line 574 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-L1_6KXOiRNGM90PRicA:-L1_6KXOiRNGM90PRicB:b-3spq7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/df3a60f0f1b55765b49140cc30165e2e7a3e21ca/pkg/sql/opt/testdata/index-constraints#L574)):*
> ```
> Remaining filter: (@1, @2) < (1, false)
> 
> build-scalar,normalize,index-constraints vars=(int, int, int) index=(@1 not null, @2 not null, @3 not null)
> ```

Some of these lines are getting long. We might want to extend opt_test to allow a continuation specifier at the end of the line such as `\`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-:-L1_6sY-x3T0VEsynlhB:b-lzl2q7)*

**Comment by RaduBerinde** [comment]
Thanks!

---

Review status: 1 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/sql/opt/index_constraints.go, line 230 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-L1Z1fKccPgHusyXpC9u:-L1ZbdOOH9d4VegdPAYF:b-lsuwgx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1dc64764cf41a3b36a9776ee3e13a1621c64ff3/pkg/sql/opt/index_constraints.go#L230)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This "exactly equivalent" comment confused me since you've just pointed out that `(1, 2) > (1, NULL)` is NULL, not false.  It might help future readers if you extend this comment to say that when used as a predicate in a where clause, NULL has the same effect as false.
</blockquote></details>

Fair point, rephrased to "is true if and only if a > 1"

---

*[pkg/sql/opt/index_constraints.go, line 263 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-L1ZC2IrHo7kMxAhhf8g:-L1ZblCqVEkhOuwrIOwv:bkttef9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1dc64764cf41a3b36a9776ee3e13a1621c64ff3/pkg/sql/opt/index_constraints.go#L263)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Is `NULL` ordered before all other values in the span?  If so, I think this statement only holds for the  `<` and `<=` operators.  For the expression:
`(a, b, c) >= (1, 2, 3)`, I believe the span `[/1/2/3 - ]` is tight.
</blockquote></details>

I thought so too :)  But it's not right, `[/1/2/3 - ]` can `2,NULL,x`. I will add to the comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-:-L1ZcD2ir8rlvQ5M6GYD:b-ucfknh)*

**Comment by RaduBerinde** [comment]
Review status: 1 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/sql/opt/testdata/index-constraints, line 574 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-L1_6KXOiRNGM90PRicA:-L1_7c15iSxXGD8b0Y8M:b-4ukfmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/df3a60f0f1b55765b49140cc30165e2e7a3e21ca/pkg/sql/opt/testdata/index-constraints#L574)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Some of these lines are getting long. We might want to extend opt_test to allow a continuation specifier at the end of the line such as `\`.
</blockquote></details>

Ack, I will keep that in mind.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107)*

**Comment by rytaft** [comment]
Reviewed 1 of 2 files at r5.
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/index_constraints.go, line 263 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-L1ZC2IrHo7kMxAhhf8g:-L1_VJr8qcUunBEmnR5G:b-r089tj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1dc64764cf41a3b36a9776ee3e13a1621c64ff3/pkg/sql/opt/index_constraints.go#L263)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I thought so too :)  But it's not right, `[/1/2/3 - ]` can `2,NULL,x`. I will add to the comment.
</blockquote></details>

But the span *should* contain those values.  I tested this in CRDB (pretty sure that PG also has the same functionality):

```
root@:26257/> select * from test.blah where (a, b, c) >= (1, 2, 3);
+---+------+------+
| a |  b   |  c   |
+---+------+------+
| 1 |    3 | NULL |
| 2 | NULL | NULL |
| 2 | NULL |    2 |
+---+------+------+
(3 rows)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107)*

**Comment by RaduBerinde** [comment]
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/index_constraints.go, line 263 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-L1ZC2IrHo7kMxAhhf8g:-L1bJaTjAb1Jv8swjzzU:b-rxn48v) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1dc64764cf41a3b36a9776ee3e13a1621c64ff3/pkg/sql/opt/index_constraints.go#L263)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

But the span *should* contain those values.  I tested this in CRDB (pretty sure that PG also has the same functionality):

```
root@:26257/> select * from test.blah where (a, b, c) >= (1, 2, 3);
+---+------+------+
| a |  b   |  c   |
+---+------+------+
| 1 |    3 | NULL |
| 2 | NULL | NULL |
| 2 | NULL |    2 |
+---+------+------+
(3 rows)
```
</blockquote></details>

Oh, wow.. Mind blown, you're right. I think we need to adjust the logic even for <= : (/NULL - /1/2/3] is "tight"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/index_constraints.go, line 263 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-L1ZC2IrHo7kMxAhhf8g:-L1bO5efDe9oouaBFJGR:b-sw0jjn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1dc64764cf41a3b36a9776ee3e13a1621c64ff3/pkg/sql/opt/index_constraints.go#L263)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Oh, wow.. Mind blown, you're right. I think we need to adjust the logic even for <= : (/NULL - /1/2/3] is "tight"
</blockquote></details>

Actually, no `(/NULL - /1/2/3]` might contain `1,NULL,NULL` which needs to be filtered out..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107)*

**Comment by RaduBerinde** [comment]
Review status: 1 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/sql/opt/index_constraints.go, line 263 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-L1ZC2IrHo7kMxAhhf8g:-L1bbbfSS2PalHcYRnfE:bd1hrg4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1dc64764cf41a3b36a9776ee3e13a1621c64ff3/pkg/sql/opt/index_constraints.go#L263)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Actually, no `(/NULL - /1/2/3]` might contain `1,NULL,NULL` which needs to be filtered out..
</blockquote></details>

Updated. Also added some logictests because we don't seem to have coverage for this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107)*

**Comment by rytaft** [comment]
:lgtm_strong: 

---

Reviewed 2 of 3 files at r6.
Review status: 3 of 4 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/tuple, line 313 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-L1bpvgQo-YI-NVpmkEg:-L1bpvgQo-YI-NVpmkEh:b-kfg3iv) ([raw file](https://github.com/cockroachdb/cockroach/blob/607662aec3550b08d3bd3c0ab75a5bee0580908a/pkg/sql/logictest/testdata/logic_test/tuple#L313)):*
> ```
> EXPLAIN (VERBOSE) SELECT * FROM uvw WHERE (u, v, w) >= (1, 2, 3) ORDER BY u, v, w
> ----
> render     0  render  ·         ·                       (u, v, w)  u!=NULL; v!=NULL; w!=NULL; +u,+v,+w
> ```

Why does this node show u!=NULL; v!=NULL; w!=NULL? (And the ones below, too?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-:-L1bqg7ZFc2Mq6aFSfyl:b-uwkowd)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/logictest/testdata/logic_test/tuple, line 313 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-L1bpvgQo-YI-NVpmkEg:-L1cPjV9_2wmbSg8l9yK:b-9bxf4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/607662aec3550b08d3bd3c0ab75a5bee0580908a/pkg/sql/logictest/testdata/logic_test/tuple#L313)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why does this node show u!=NULL; v!=NULL; w!=NULL? (And the ones below, too?)
</blockquote></details>

Nice catch! Yeah this is wrong, I'll file an issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/logictest/testdata/logic_test/tuple, line 492 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107#-L1xtxczaKRbWfwl3uHq:-L1xtxczaKRbWfwl3uHr:bk8hccv) ([raw file](https://github.com/cockroachdb/cockroach/blob/607662aec3550b08d3bd3c0ab75a5bee0580908a/pkg/sql/logictest/testdata/logic_test/tuple#L492)):*
> ```
>  └── scan  1  scan    ·         ·                       (u, v, w)  u!=NULL; v!=NULL; w!=NULL; +u,+v,+w
> ·          1  ·       table     uvw@uvw_u_v_w_idx       ·          ·
> ·          1  ·       spans     /!NULL-                 ·          ·
> ```

Lol, this span is broken, we are missing results like `(NULL, 2, 1)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21107)*

**Comment by knz** [comment]
_nulls are hard, who would have thought?_

**Pull request merged**
