### PR TITLE
logictest: unskip mixed version tests

### LINKED ISSUE #117645: logictest: update mixed-version tests now that master's predecessor is 23.2
In #117581, we updated master's predecessor to be 23.2, now that we have two release candidates out. However, a number of mixed-version logictests fail with this change, since they were written with the assumption that the upgrade carried out by the test is 23.1 -> 23.2.

The following tests were skipped in that PR and should be revisited (i.e., rewritten or deleted if they no longer make sense):

* [x] `mixed_version_bootstrap_tenant`
* [x] `mixed_version_can_login`
* [x] `mixed_version_insights_queries`
* [x] `mixed_version_partially_visible_index`
* [x] `mixed_version_procedure`
* [x] `mixed_version_refcursor`
* [x] `mixed_version_schedule_details`
* [x] `mixed_version_udf_execute_privileges`
* [x] `mixed_version_udf_mutations`
* [x] `mixed_version_upgrade_preserve_ttl`
* [x] `pg_lsn_mixed`

Jira issue: CRDB-35287

### PR DESCRIPTION
**Pull request by rafiss**
### logictest: add config for cockroach-go/testserver running 23.1

Previously, the cockroach-go/testserver test config would only allow
boootstrapping from v23.2. Since we are starting to support upgrading
from v23.1 directly to master, now we add a config that allows us to
test that.

### logictest: unskip mixed version tests

This required regenerating the initialvalues that are used when
bootstrapping from 23.2.

Additionally, the logic for validating the system database's
clusterversion had to be updated to account for dev offsets.

### logictest: add test for upgrading from 23.1 to master

This is a basic smoke test that can help catch upgrade-related bugs
sooner than a roachtest would.

---

fixes https://github.com/cockroachdb/cockroach/issues/117645
Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Thanks for updating the 23.2 bootstrap data!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117897#-:-NoSd8nh2EregOYguzzM:b1xppmy)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/server/node.go` line 509 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117897#-NoScx2o29FBC5EMsIoB:-NoScx2o29FBC5EMsIoC:b-empqp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/718cfce9adb6694ccf1a2228ef1b04a12fc399a8/pkg/server/node.go#L509)):*
> ```Go
> 			}
> 			if initialValuesOpts.OverrideKey == 0 {
> 				if initCfg.latestVersion.Less(clusterversion.PreviousRelease.Version()) {
> ```

This doesn't look right to me. We definitely want to be able to create 23.1 nodes if we want to allow 23.1 -> 24.1 upgrades (even experimentally)

What is this change fixing exactly?
___
*[`pkg/sql/logictest/testdata/logic_test/mixed_version_insights_queries` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117897#-NoScdMr21DyPG6HNbuI:-NoScdMr21DyPG6HNbuJ:b-ndm1jb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b10f083f8889cdc1bc549d9428f06fd784ba081/pkg/sql/logictest/testdata/logic_test/mixed_version_insights_queries#L1)):*
> ```
> # LogicTest: cockroach-go-testserver-upgrade-to-master
> ```

We still support 23.1 -> master upgrades so I think tests like this should stay..  Maybe we need a new logic test config?

**Review by RaduBerinde — COMMENTED** [review]
This is only tangentially related, but we'll need to update the upgrade roachtest to test 23.1 -> master upgrades as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117897#-:-NoSdmnW1JLXjP-0OmJ1:b-7dlesv)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117897)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[`pkg/sql/logictest/testdata/logic_test/mixed_version_insights_queries` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117897#-NoScdMr21DyPG6HNbuI:-NoShNi02Sy0mzDiQqxg:b33f62d) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b10f083f8889cdc1bc549d9428f06fd784ba081/pkg/sql/logictest/testdata/logic_test/mixed_version_insights_queries#L1)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We still support 23.1 -> master upgrades so I think tests like this should stay..  Maybe we need a new logic test config?
</blockquote></details>

hm, yeah the issue is that there's no logictest config that uses cockroach-go-testserver and which bootstraps from 23.1. let me see if we can add one
___
*[`pkg/server/node.go` line 509 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117897#-NoScx2o29FBC5EMsIoB:-NoShKc05EocsRW2f4iV:b4gj6g4) ([raw file](https://github.com/cockroachdb/cockroach/blob/718cfce9adb6694ccf1a2228ef1b04a12fc399a8/pkg/server/node.go#L509)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This doesn't look right to me. We definitely want to be able to create 23.1 nodes if we want to allow 23.1 -> 24.1 upgrades (even experimentally)

What is this change fixing exactly?
</blockquote></details>

good catch, this change wasn't needed

**Review by RaduBerinde — COMMENTED** [review]
:lgtm_strong:    Looks great, very nice work!!! Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117897#-:-NoWrAao3fvranfcRHS0:b-rn7ijd)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/tenant_creation.go` line 160 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117897#-NoWpXUs2R68ZgHGzeXm:-NoWpXUs2R68ZgHGzeXn:b-bzal11) ([raw file](https://github.com/cockroachdb/cockroach/blob/8381114a1207e3b38c63dcfc126458169bac4ea0/pkg/sql/tenant_creation.go#L160)):*
> ```Go
> 
> 	var bootstrapVersionOverride clusterversion.Key
> 	if p.EvalContext().TestingKnobs.TenantLogicalVersionKeyOverride != 0 {
> ```

[nit] this would be more readable as a switch:

```go
switch {
case KeyOverride != 0:

case IsActive(Latest):

case IsActive(Previous):

default:
// use MinSupported
}
```
___
*[`pkg/sql/logictest/testdata/logic_test/upgrade_skip_version` line 14 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117897#-NoWqaH20Qyimj0igG9A:-NoWqaH20Qyimj0igG9B:buljm8p) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee21a8f534ea2e44e838f65694ff78b1d147a022/pkg/sql/logictest/testdata/logic_test/upgrade_skip_version#L14)):*
> ```
> sleep 30s
> 
> # Verify that the cluster is upgrading to 24.1. When 24.1 is minted, this
> ```

You can use `crdb_internal.release_series(version) FROM [SHOW CLUSTER SETTING version]` and you'll get 24.1, so it doesn't need changing later.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117897)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[`pkg/sql/tenant_creation.go` line 160 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117897#-NoWpXUs2R68ZgHGzeXm:-NoXxe1s-qJVD1uVoLnN:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8381114a1207e3b38c63dcfc126458169bac4ea0/pkg/sql/tenant_creation.go#L160)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] this would be more readable as a switch:

```go
switch {
case KeyOverride != 0:

case IsActive(Latest):

case IsActive(Previous):

default:
// use MinSupported
}
```
</blockquote></details>

done
___
*[`pkg/sql/logictest/testdata/logic_test/upgrade_skip_version` line 14 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117897#-NoWqaH20Qyimj0igG9A:-NoXxwy6DZ6E2o_8xxT1:b-esfcfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee21a8f534ea2e44e838f65694ff78b1d147a022/pkg/sql/logictest/testdata/logic_test/upgrade_skip_version#L14)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

You can use `crdb_internal.release_series(version) FROM [SHOW CLUSTER SETTING version]` and you'll get 24.1, so it doesn't need changing later.
</blockquote></details>

nice, done

**Comment by rafiss** [comment]
This is ready for another look

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117897#-:-NomlC7M9a672BSvx7i5:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained

**Comment by rafiss** [comment]
tftr!!

bors r+

**Pull request merged**
