### PR TITLE
Ui custom charts metadata descriptions

### PR DESCRIPTION
**Pull request by koorosh**
Metadata information is not available on client side so we need to request it and put in redux store and implement all mechanisms to fetch data from server and put it on UI.
- metricMetadata Api request was added
- redux infrastructure for metricMetadata was built based on existing implementation for readonly api data (apiReducers and CachedDataReducer);
- To display two rows in select item component - it was extended with custom select component which inherits most default props from default implementation.

### CODE REVIEW

**Review by nathanstilwell — APPROVED** [review]
The code looks good, but I couldn't get this to work locally. Is there some additional setup you had to do to populate the metadata in the dropdown?

**Comment by Koorosh** [comment]
@nathanstilwell , any additional setup is required. The only issue that descriptions are not provided for every metric (it was mentioned here https://github.com/cockroachdb/cockroach/issues/31521#issuecomment-430397143 and here  https://github.com/cockroachdb/cockroach/issues/31521#issuecomment-555436516 

Screenshot 2019-12-04 at 21 51 32

**Review by dhartunian — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42586)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @Koorosh)

___
*[pkg/ui/src/views/reports/containers/customChart/metricOption.styl, line 15 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42586#-LwEadsPBPOu4bjdOXwA:-LwEadsPBPOu4bjdOXwB:b-kjodq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/38f7e8ef2601a2b560d363e0f3dab8cfd3518e26/pkg/ui/src/views/reports/containers/customChart/metricOption.styl#L15)):*
> ```Stylus
> 
> .metric-option__label
>   color #394455
> ```

@koorosh are these colors available as variables somewhere that we can reference?

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42586)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[pkg/ui/src/views/reports/containers/customChart/metricOption.styl, line 15 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42586#-LwEadsPBPOu4bjdOXwA:-LwICfgz4Gn5_mhORXNc:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/38f7e8ef2601a2b560d363e0f3dab8cfd3518e26/pkg/ui/src/views/reports/containers/customChart/metricOption.styl#L15)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

@koorosh are these colors available as variables somewhere that we can reference?
</blockquote></details>

Done.

**Review by dhartunian — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42586)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

**Pull request merged**
