### PR TITLE
storage: avoid RaftGroupDeletedError from RHS in splitTrigger

### LINKED ISSUE #21146: storage: *roachpb.RaftGroupDeletedError for RHS in splitPostApply
```go
func splitPostApply(
	ctx context.Context, deltaMS enginepb.MVCCStats, split *roachpb.SplitTrigger, r *Replica,
) {
	// The right hand side of the split was already created (and its raftMu
	// acquired) in Replica.acquireSplitLock. It must be present here.
	rightRng, err := r.store.GetReplica(split.RightDesc.RangeID)
	if err != nil {
		log.Fatalf(ctx, "unable to find RHS replica: %s", err)
	}
	{
		rightRng.mu.Lock()
		// Already holding raftMu, see above.
		err := rightRng.initRaftMuLockedReplicaMuLocked(&split.RightDesc, r.store.Clock(), 0)
		rightRng.mu.Unlock()
		if err != nil {
			log.Fatal(ctx, err) <--
		}
	}
```

https://sentry.io/cockroach-labs/cockroachdb/issues/426530382/

```
*log.safeError: store.go:1820: *roachpb.RaftGroupDeletedError
  File "github.com/cockroachdb/cockroach/pkg/storage/replica_proposal.go", line 718, in handleReplicatedEvalResult
  File "github.com/cockroachdb/cockroach/pkg/storage/replica_proposal.go", line 981, in handleEvalResultRaftMuLocked
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 4480, in processRaftCommand
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 3481, in handleRaftReadyRaftMuLocked
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 3173, in handleRaftReady
...
(4 additional frame(s) were not displayed)

store.go:1820: *roachpb.RaftGroupDeletedError
```

### PR DESCRIPTION
**Pull request by tbg**
The right hand side of a split can be readded before the split trigger
fires, in which case the split trigger fails.

See [bug description].

I [suggested] a test to reprduce this bug "properly", so we should look
into that. In the meantime, it'll be good to see that this passes tests.
I verified manually that setting `minReplicaID` to some large number
before the call to `rightRng.initRaftMuLockedReplicaMuLocked` reproduces
the symptoms prior to this commit, but that doesn't come as a surprise
nor does it prove that the fix works flawlessly.

[bug description]: https://github.com/cockroachdb/cockroach/issues/21146#issuecomment-365757329
[suggested]: https://github.com/cockroachdb/cockroach/pull/39034#issuecomment-520371326

Fixes #21146.

Release note (bug fix): Fixed a rare panic (message: "raft group
deleted") that could occur during splits.

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39571)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz)

**Comment by tbg** [comment]
bors r=bdarnell

**Comment by tbg** [comment]
acceptance/gossip-peerings failed with https://github.com/cockroachdb/cockroach/issues/39604

bors r=bdarnell

**Comment by tbg** [comment]
It failed again, except this time it got stuck during fetching a `debug zip` until the test harness killed the process. But it's very likely that it's #39604 again.

bors r=bdarnell

@jeffrey-xiao I'm going to send a PR to revert b320ff5c5a3338e2207496c88228f781e4b711b1.

**Pull request merged**
