### PR TITLE
storage: add `MVCCIncrementalIterIntentPolicyIgnore`

### PR DESCRIPTION
**Pull request by erikgrinaker**
This allows callers that have already scanned the lock table to disable intent interleaving for a minor performance improvement.

The policy is adopted in `MVCCClearTimeRange` and `MVCCDeleteRangeUsingTombstone`, which already do such lock table scans.

Touches #113116.
Epic: none
Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118726)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @RaduBerinde)

___
*[`pkg/storage/mvcc_incremental_iterator.go` line 489 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118726#-NprMMxO2xLrTbYVg6p1:-NprMMxO2xLrTbYVg6p2:b-tduozm) ([raw file](https://github.com/cockroachdb/cockroach/blob/0834fb11fa4a6fc53929de488ff2c12d2e4f8cbe/pkg/storage/mvcc_incremental_iterator.go#L489)):*
> ```Go
> 			// We don't expect to see this since we disabled intent interleaving, but
> 			// if we do the intent will be filtered out.
> 			return nil
> ```

Should we return an `errors.AssertionFailed` here instead?
___
*[`pkg/storage/mvcc_incremental_iterator.go` line 491 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118726#-NprMcJu2itdX-Ox5rLh:-NprMcJu2itdX-Ox5rLi:bg2ulc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0834fb11fa4a6fc53929de488ff2c12d2e4f8cbe/pkg/storage/mvcc_incremental_iterator.go#L491)):*
> ```Go
> 			return nil
> 		default:
> 			return errors.AssertionFailedf("unknown intent policy: %d", i.intentPolicy)
> ```

Should this be setting `i.err` before returning it? We seem to drop the return value in `advance`.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118726)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @RaduBerinde)

___
*[`pkg/storage/mvcc_incremental_iterator.go` line 489 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118726#-NprMMxO2xLrTbYVg6p1:-NpsWD8r--WFfSbEMLA6:b-ynm1s4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0834fb11fa4a6fc53929de488ff2c12d2e4f8cbe/pkg/storage/mvcc_incremental_iterator.go#L489)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we return an `errors.AssertionFailed` here instead?
</blockquote></details>

May as well, done.
___
*[`pkg/storage/mvcc_incremental_iterator.go` line 491 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118726#-NprMcJu2itdX-Ox5rLh:-NpsWEDNCJQN68wCrCh8:b-xiw2bp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0834fb11fa4a6fc53929de488ff2c12d2e4f8cbe/pkg/storage/mvcc_incremental_iterator.go#L491)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should this be setting `i.err` before returning it? We seem to drop the return value in `advance`.
</blockquote></details>

Nice catch, done.

**Comment by erikgrinaker** [comment]
Updated to make use of the policy in `MVCCClearTimeRange` and `MVCCDeleteRangeUsingTombstone`.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118726#-:-Nq3rueZ8mp9JRxKYg96:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Pull request merged**
