### PR TITLE
kvserver: teach replicateQueue to replace dead/decommisioning non-voters

### LINKED ISSUE #61626: kvserver: remove/replace decommissioning and dead non-voters
We need to address this TODO:
https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvserver/allocator.go#L561-L562

Currently, the allocator will not spit out the right actions to remove / replace decommissioning or dead non-voter replicas. This means that, for instance, a decommissioning process on a node can get stuck when the node has non-voters on it.

### PR DESCRIPTION
**Pull request by aayushshah15**
The PR is very similar to #59403.

Previously, non-voters on dead or decommissioning nodes would not get
removed or replaced. This commit fixes this behaviour.

Resolves https://github.com/cockroachdb/cockroach/issues/61626

Release justification: fixes limitation where dead/decommissioning
non-voters would not be removed or replaced
Release note: None

### CODE REVIEW

**Comment by aayushshah15** [comment]
Note that I only have an "integration" test for testing removal/replacement of non-voters from _decommissioning_ nodes. I haven't yet figured out a good way to test removing or replacing non-voters from _dead_ nodes. I'll update the PR with a good test for that case, but it should be ready for a look aside from that.

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61682)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @andreimatei)

___
*[pkg/kv/kvserver/allocator.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-MVO57M4EYjayOOEI-IM:-MVO57M4EYjayOOEI-IN:b-tutvpn) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dcc6668e4512e8c00034077ac4e6112064a3565/pkg/kv/kvserver/allocator.go#L114)):*
> ```Go
> // These are the possible allocator actions.
> const (
> 	_ AllocatorAction = iota
> ```

Do you have a sense for why we keep actions and priorities separate? It seems like a recipe for bugs. There's an N to 1 mapping between the two concepts, right? So then would a `(AllocatorAction).Priority` method be appropriate to avoid bugs in `ComputeAction`?

(no need to hold up this PR on the discussion)
___
*[pkg/kv/kvserver/allocator.go, line 572 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-MVO4ONJEUQgTQ3Fu2aO:-MVO4ONJEUQgTQ3Fu2aP:bska7xf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dcc6668e4512e8c00034077ac4e6112064a3565/pkg/kv/kvserver/allocator.go#L572)):*
> ```Go
> 	}
> 	liveNonVoters, deadNonVoters := a.storePool.liveAndDeadReplicas(nonVoterReplicas)
> 	if haveNonVoters == neededNonVoters && len(deadNonVoters) > 0 {
> ```

Let's add comments like we have above that explain in prose what each of these cases means.
___
*[pkg/kv/kvserver/replicate_queue.go, line 367 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-MVO5hPWDUBmRqekXrZ8:-MVO5hPWDUBmRqekXrZ9:b4mwggm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2bba4eee1b3e97811f467a7f7e279310213e354/pkg/kv/kvserver/replicate_queue.go#L367)):*
> ```Go
> 		return false, nil
> 
> 	// Add replicas
> ```

nit: punctuation on each of these.
___
*[pkg/kv/kvserver/replicate_queue.go, line 468 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-MVO5xTP0kI29VQmCAkS:-MVO5xTP0kI29VQmCAkT:bxvn6tb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2bba4eee1b3e97811f467a7f7e279310213e354/pkg/kv/kvserver/replicate_queue.go#L468)):*
> ```Go
> func getRemoveIdx(repls, deadOrDecommissioningRepls []roachpb.ReplicaDescriptor) (removeIdx int) {
> 	removeIdx = -1
> 	if len(deadOrDecommissioningRepls) == 0 {
> ```

Aren't we already checking this outside of the function? If so, consider making this a precondition of the method and panicking if it is not upheld.

Or even better, just take a single `deadOrDecommissioningRepl roachpb.ReplicaDescriptor` arg so that callers aren't tricked into thinking that anyone other than the first deadOrDecommissioned replica is considered.
___
*[pkg/kv/kvserver/replicate_queue.go, line 496 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-MVO6wfI-C9-fLMCEzbP:-MVO6wfI-C9-fLMCEzbQ:bhbi8k0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2bba4eee1b3e97811f467a7f7e279310213e354/pkg/kv/kvserver/replicate_queue.go#L496)):*
> ```Go
> 	dryRun bool,
> ) (requeue bool, _ error) {
> 	desc, zone := repl.DescAndZone()
> ```

It's not entirely new logic, but the repeated calls to `repl.DescAndZone()` scare me. It seems error prone to call `allocator.ComputeAction` with one zone and descriptor and then carry out the action with a separate zone and descriptor. Does that concern you at all?
___
*[pkg/kv/kvserver/replicate_queue.go, line 928 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-MVO8b_CAF5lquessOk8:-MVO8b_CAF5lquessOk9:bnugty4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2bba4eee1b3e97811f467a7f7e279310213e354/pkg/kv/kvserver/replicate_queue.go#L928)):*
> ```Go
> 	decommissioningReplica := decommissioningReplicas[0]
> 
> 	if targetType == voterTarget {
> ```

We have logic like this in a few places, but I wonder whether we want it. Is there any reason to bake in this assumption that non-voting replicas will never hold the lease? That will probably never change, but is there a downside to gating calls to `maybeTransferLeaseAway`? Isn't it a quick no-op if the target isn't the leaseholder?
___
*[pkg/kv/kvserver/replicate_queue_test.go, line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-MVO9zB05IN0nZ3W4YIM:-MVO9zB1EyGR2kx8jeXL:b-2befl7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2bba4eee1b3e97811f467a7f7e279310213e354/pkg/kv/kvserver/replicate_queue_test.go#L398)):*
> ```Go
> 		require.Eventually(t, func() bool {
> 			return check(tc, scratchRange)
> 		}, 15*time.Second, time.Second)
> ```

Is a 1 second check a little slow? I'd imagine we'd want to run it every 10 ms or something much faster.
___
*[pkg/kv/kvserver/replicate_queue_test.go, line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-MVOA-Z76dtiRfigvZEy:-MVOA-Z76dtiRfigvZEz:b-bwfrja) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2bba4eee1b3e97811f467a7f7e279310213e354/pkg/kv/kvserver/replicate_queue_test.go#L398)):*
> ```Go
> 		require.Eventually(t, func() bool {
> 			return check(tc, scratchRange)
> 		}, 15*time.Second, time.Second)
> ```

`s/15*time.Second/testutils.DefaultSucceedsSoonDuration/`
___
*[pkg/kv/kvserver/replicate_queue_test.go, line 409 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-MVOA1JvEfOgo3ctEKU9:-MVOA1JvEfOgo3ctEKUA:b-w5jmi7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2bba4eee1b3e97811f467a7f7e279310213e354/pkg/kv/kvserver/replicate_queue_test.go#L409)):*
> ```Go
> 	}
> 
> 	t.Run("replace", func(t *testing.T) {
> ```

Could you give these two subtests comments explaining what they're testing and why they're different.

**Review by andreimatei — COMMENTED** [review]
I've got nothing beyond what Nathan said.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-:-MVOenznAokvBTkm0s8j:b2ueigp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @nvanbenschoten)

___
*[pkg/kv/kvserver/allocator.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-MVO57M4EYjayOOEI-IM:-MVObj5u9iJ9trmcy0TB:b-pidur4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dcc6668e4512e8c00034077ac4e6112064a3565/pkg/kv/kvserver/allocator.go#L114)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you have a sense for why we keep actions and priorities separate? It seems like a recipe for bugs. There's an N to 1 mapping between the two concepts, right? So then would a `(AllocatorAction).Priority` method be appropriate to avoid bugs in `ComputeAction`?

(no need to hold up this PR on the discussion)
</blockquote></details>

+1 and maybe we can get rid of the numerical values of priorities with this occasion, assuming they're meaningless
___
*[pkg/kv/kvserver/allocator.go, line 127 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-MVOdkPo-jXfN1uUsqWs:-MVOdkPo-jXfN1uUsqWt:b-v6e74h) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2bba4eee1b3e97811f467a7f7e279310213e354/pkg/kv/kvserver/allocator.go#L127)):*
> ```Go
> 	AllocatorReplaceDecommissioningNonVoter
> 	AllocatorRemoveDecommissioningVoter
> 	AllocatorRemoveDecommissioningNonVoter
> ```

is there a good reason why there's distinct actions RemoveDead* versus RemoveDecomissioning* ? It would seem to me that a removal is a removal. Perhaps the different priorities are the only reason?
___
*[pkg/kv/kvserver/replicate_queue.go, line 928 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-MVO8b_CAF5lquessOk8:-MVOeYQ_7CnC5s_FyTU4:b-i7e85) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2bba4eee1b3e97811f467a7f7e279310213e354/pkg/kv/kvserver/replicate_queue.go#L928)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We have logic like this in a few places, but I wonder whether we want it. Is there any reason to bake in this assumption that non-voting replicas will never hold the lease? That will probably never change, but is there a downside to gating calls to `maybeTransferLeaseAway`? Isn't it a quick no-op if the target isn't the leaseholder?
</blockquote></details>

+1
The "maybe" in `maybeTransferLeaseAway` sounds like it could handle any pre-conditions.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61682)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvserver/allocator.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-MVO57M4EYjayOOEI-IM:-MVTx1HeC5XXMUiS-Uyn:bzcbq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dcc6668e4512e8c00034077ac4e6112064a3565/pkg/kv/kvserver/allocator.go#L114)):*
The numerical values of the priorities (or something like it) I think do need to exist because of this sort of logic: https://github.com/cockroachdb/cockroach/blob/819d931c6c768f9252cf89b8bc46db72fc1a3175/pkg/kv/kvserver/allocator.go#L483

This logic makes the replicateQueue prioritize ranges that are missing, say 3 voters, over ranges that are missing 1 voter. 

> then would a (AllocatorAction).Priority method be appropriate to avoid bugs in ComputeAction?

Done. LMK if you dislike what I've done.
___
*[pkg/kv/kvserver/allocator.go, line 572 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-MVO4ONJEUQgTQ3Fu2aO:-MVT2wTR9igg3IeaG8d1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dcc6668e4512e8c00034077ac4e6112064a3565/pkg/kv/kvserver/allocator.go#L572)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's add comments like we have above that explain in prose what each of these cases means.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/allocator.go, line 127 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-MVOdkPo-jXfN1uUsqWs:-MVTqFB6Ev_dvHEuy4mD:b-bz947q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2bba4eee1b3e97811f467a7f7e279310213e354/pkg/kv/kvserver/allocator.go#L127)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

is there a good reason why there's distinct actions RemoveDead* versus RemoveDecomissioning* ? It would seem to me that a removal is a removal. Perhaps the different priorities are the only reason?
</blockquote></details>

We could've had different priorities but the same `AllocatorAction`, so that's not it. The differences are encapsulated in `removeDead` and `removeDecommissioning`. They're fairly minor: slightly different logging, different metric being updated, one tries to `maybeTransferLeaseAway` while the other can assume that the replica being removed doesn't have the lease. 
___
*[pkg/kv/kvserver/replicate_queue.go, line 367 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-MVO5hPWDUBmRqekXrZ8:-MVTpfHR4zEnbDb1rpYQ:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2bba4eee1b3e97811f467a7f7e279310213e354/pkg/kv/kvserver/replicate_queue.go#L367)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: punctuation on each of these.
</blockquote></details>

Fixed.
___
*[pkg/kv/kvserver/replicate_queue.go, line 468 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-MVO5xTP0kI29VQmCAkS:-MVTD-ep0oB_Gann0PAb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2bba4eee1b3e97811f467a7f7e279310213e354/pkg/kv/kvserver/replicate_queue.go#L468)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Aren't we already checking this outside of the function? If so, consider making this a precondition of the method and panicking if it is not upheld.

Or even better, just take a single `deadOrDecommissioningRepl roachpb.ReplicaDescriptor` arg so that callers aren't tricked into thinking that anyone other than the first deadOrDecommissioned replica is considered.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replicate_queue.go, line 496 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-MVO6wfI-C9-fLMCEzbP:-MVTr1bN2mbHZzkM0Qg4:bz7eohx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2bba4eee1b3e97811f467a7f7e279310213e354/pkg/kv/kvserver/replicate_queue.go#L496)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's not entirely new logic, but the repeated calls to `repl.DescAndZone()` scare me. It seems error prone to call `allocator.ComputeAction` with one zone and descriptor and then carry out the action with a separate zone and descriptor. Does that concern you at all?
</blockquote></details>

So the hazard here is just that we might have decided to add / remove / rebalance based on one version of the range descriptor but then _execute_ upon that decision based on another version? This can only happen if we raced with the `mergeQueue` or the `StoreRebalancer`, which is definitely possible. However, I don't think anything bad can really happen in such a circumstance since:
1. Those callers won't add / remove replicas (except for short-lived learners, which should be copacetic), they will just rebalance a range.
2. The exact replication change that is executed is still governed by the `{Allocate, Rebalance, Remove}{Voter, NonVoter}` set of methods, so we know that we're not making a decision that could, for instance, drive the range into unavailability or something. 
3. the `replicateQueue` requeues ranges back to be processed again after it executes upon an allocator action. If we raced with something and somehow ended up making a suboptimal rebalancing decision, we will correct it on the next attempt.

Does that make sense? Do you think this reasoning should end up in the comments? 
___
*[pkg/kv/kvserver/replicate_queue.go, line 928 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-MVO8b_CAF5lquessOk8:-MVT8vko-sqD3MVtdb81:bqkwr08) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2bba4eee1b3e97811f467a7f7e279310213e354/pkg/kv/kvserver/replicate_queue.go#L928)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

+1
The "maybe" in `maybeTransferLeaseAway` sounds like it could handle any pre-conditions.
</blockquote></details>

Yeah we make this check right at the beginning of `maybeTransferLeaseAway` anyway. Removed.
___
*[pkg/kv/kvserver/replicate_queue_test.go, line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-MVO9zB05IN0nZ3W4YIM:-MVTAHxs-t6kSIwy5fED:b29hkaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2bba4eee1b3e97811f467a7f7e279310213e354/pkg/kv/kvserver/replicate_queue_test.go#L398)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is a 1 second check a little slow? I'd imagine we'd want to run it every 10 ms or something much faster.
</blockquote></details>

I was hoping for the infrequent checks to make it less likely to flake under race. I bumped it to `100ms`. 
___
*[pkg/kv/kvserver/replicate_queue_test.go, line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-MVOA-Z76dtiRfigvZEy:-MVTB6THDrGwt295ZpRt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2bba4eee1b3e97811f467a7f7e279310213e354/pkg/kv/kvserver/replicate_queue_test.go#L398)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/15*time.Second/testutils.DefaultSucceedsSoonDuration/`
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replicate_queue_test.go, line 409 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-MVOA1JvEfOgo3ctEKU9:-MVTBA4vCQy9HjIwGyXp:b5d1wp7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2bba4eee1b3e97811f467a7f7e279310213e354/pkg/kv/kvserver/replicate_queue_test.go#L409)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you give these two subtests comments explaining what they're testing and why they're different.
</blockquote></details>

Done. LMK if they seem lacking.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-:-MVUcKS6Em_7BnWUMIma:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @andreimatei)

___
*[pkg/kv/kvserver/allocator.go, line 395 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-MVUZcDT9zCbiX6akHz9:-MVUZcDT9zCbiX6akHzA:bv0owo2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dcc6668e4512e8c00034077ac4e6112064a3565/pkg/kv/kvserver/allocator.go#L395)):*
> ```Go
> 	if a.storePool == nil {
> 		// Do nothing if storePool is nil for some unittests.
> 		return AllocatorNoop, 0
> ```

I'm very positive on most of this change! But I'm not sure it improved this particular function. The elimination of short-circuiting makes this more difficult to follow. Now every case needs to ask the question: "what happens after this?" I'd encourage us to revert back to the old style and just have a bit of `return action, action.Priority()` repetition.
___
*[pkg/kv/kvserver/replicate_queue.go, line 496 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-MVO6wfI-C9-fLMCEzbP:-MVU_eiACBQ7m5CeN1RD:b-z6fdff) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2bba4eee1b3e97811f467a7f7e279310213e354/pkg/kv/kvserver/replicate_queue.go#L496)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

So the hazard here is just that we might have decided to add / remove / rebalance based on one version of the range descriptor but then _execute_ upon that decision based on another version? This can only happen if we raced with the `mergeQueue` or the `StoreRebalancer`, which is definitely possible. However, I don't think anything bad can really happen in such a circumstance since:
1. Those callers won't add / remove replicas (except for short-lived learners, which should be copacetic), they will just rebalance a range.
2. The exact replication change that is executed is still governed by the `{Allocate, Rebalance, Remove}{Voter, NonVoter}` set of methods, so we know that we're not making a decision that could, for instance, drive the range into unavailability or something. 
3. the `replicateQueue` requeues ranges back to be processed again after it executes upon an allocator action. If we raced with something and somehow ended up making a suboptimal rebalancing decision, we will correct it on the next attempt.

Does that make sense? Do you think this reasoning should end up in the comments? 
</blockquote></details>

Well, I think the point stands that it took a fairly long message to convince me that it isn't subtly broken :smiley: And the next reader is going to probably think the same thing, at which point they may be right because things may have changed in very distant parts of the system. This kind of logic is such a red flag because its correctness can't be reasoned about locally. It requires the caller to ask - "what could have happened between the first time I looked and this and the next time I looked at it? Could I have raced with a concurrent modification? If so, in which ways can this state be different now from what it looked like when I decided to take some action?".

Do we gain anything from this structure? Would the fix be as straightforward as plumbing the existing `desc` and `zone` down to each of these functions?

Also, no need to make any changes for this here.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61682)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvserver/allocator.go, line 395 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-MVUZcDT9zCbiX6akHz9:-MVXjuHJ-7r_yiFaACTp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dcc6668e4512e8c00034077ac4e6112064a3565/pkg/kv/kvserver/allocator.go#L395)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm very positive on most of this change! But I'm not sure it improved this particular function. The elimination of short-circuiting makes this more difficult to follow. Now every case needs to ask the question: "what happens after this?" I'd encourage us to revert back to the old style and just have a bit of `return action, action.Priority()` repetition.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replicate_queue.go, line 496 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-MVO6wfI-C9-fLMCEzbP:-MVXjvX38YGsa73YD5iq:bou5qx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2bba4eee1b3e97811f467a7f7e279310213e354/pkg/kv/kvserver/replicate_queue.go#L496)):*
>I think the point stands that it took a fairly long message to convince me that it isn't subtly broken 😃

Yaa very fair. 

> Would the fix be as straightforward as plumbing the existing desc and zone down to each of these functions?

I think so, yes. With the plumbing, if we used a stale descriptor, it would get rejected when `AdminChangeReplicas` checks it against the version in KV.

>Also, no need to make any changes for this here.

Added a TODO for now.

**Review by aayushshah15 — COMMENTED** [review]
>I'll update the PR with a good test for that case, but it should be ready for a look aside from that.

I've added this test. PTAL. 

I recognize that this bad boy is blocking the beta, I'll try and get the PR through CI and backport as soon as I get LGTM on the test.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-:-MVcxrB22cg58EVQBFNm:b5k6rwm)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @nvanbenschoten)

**Comment by aayushshah15** [comment]
>I've added this test. PTAL.

This was not a good test, I rewrote it in a way that should be not-flakey.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61682#-:-MWP_Uz90p_dz3qui_mw:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Comment by aayushshah15** [comment]
TFTRs!

bors r+

**Pull request merged**
