### PR TITLE
sql/pgwire/hba: add fuzzer

### PR DESCRIPTION
**Pull request by madelynnblue**
Release note: None

### CODE REVIEW

**Comment by mjibson** [comment]
This immediately found lots of bugs. Run it yourself with `make fuzz 'PKG=./pkg/sql/pgwire/hba'` to see. (You will need to `go get -u github.com/dvyukov/go-fuzz/go-fuzz github.com/dvyukov/go-fuzz/go-fuzz-build` if you upgraded to go1.13.) Not even worthwhile to send you the crashes because it's so fast to generate them.

**Comment by knz** [comment]
Woah this is absolutely fantastic :sparkling_heart: 

I felt both humbled and very excited at the same time. This made my day!

**Comment by knz** [comment]
I found this easier to troubleshoot:

```go
func FuzzParseAndNormalize(data []byte) int {
  conf, err := ParseAndNormalize(string(data))
  if err != nil {
    return 0
  }
  s := conf.String()
  conf2, err := ParseAndNormalize(s)
  if err != nil {
    panic(fmt.Errorf(`-- original:
%s
-- parsed:
%# v
-- new:
%s
-- error:
%v`,
      string(data),
      pretty.Formatter(conf),
      s,
      err))
  }
  s2 := conf2.String()
  if s != s2 {
    panic(fmt.Errorf(`reparse mismatch:
-- original:
%s
-- new:
%# v
-- printed:
%s`,
      s,
      pretty.Formatter(conf2),
      s2))
  }
  return 1
}
```

**Comment by knz** [comment]
All the errors so far stem from two limitations (I would not call them bugs):

- if the conn type or auth method are the quoted empty string `""` they are pretty-printed without the quotes and the column appears empty (but that would be rejected upon validation in `pgwire`).
- if a column contains a control character that also happens to be whitespace, it is stripped/replaced by spaces upon pretty-printing.

The first one is easy to deal with, the second one I will deal with by rejecting control characters in the input altogether.

**Review by knz — APPROVED** [review]
LGTM btw

**Pull request merged**
