### PR TITLE
colexec: make router outputs and external operators more dynamic

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit improves the last uses of the batches with fixed
`coldata.BatchSize()` size:
- it moves the allocations of some batches in external operators from
the constructor into `Init` method. Note that previously, even if the
spilling to disk didn't occur, we were still allocating these batches
(we additionally delay one map creation in the external hash joiner till
`Init` too)
- it makes the allocation of `pendingBatch` in the router outputs
dynamic.

Additionally, this commit makes `tupleHashDistributor` more dynamic too
by allocating the slices at run time.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
The benchmarks are [here](https://gist.github.com/yuzefovich/ce0705f22e083291c174eb67d4a54896).

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56935#-:-MM_Mlcm95BscO5K8zFl:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/routers.go, line 419 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56935#-MM_M1nE1wX7x7KS3zQw:-MM_M1nE1wX7x7KS3zQx:b-hs1gg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3402660cc5f67f8d0f0687a1bc082affd06bc9cc/pkg/sql/colexec/routers.go#L419)):*
> ```Go
> 	for toAppend := len(selection); toAppend > 0; {
> 		if o.mu.pendingBatch == nil {
> 			if o.pendingBatchCapacity < coldata.BatchSize() {
> ```

Is there enough overlap with other dynamically increasing behavior up to `coldata.BatchSize` to put a helper function that all code uses in `coldata`?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56935)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/colexec/routers.go, line 419 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56935#-MM_M1nE1wX7x7KS3zQw:-MMaY3786RB4SJ-yq79u:bozwxdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3402660cc5f67f8d0f0687a1bc082affd06bc9cc/pkg/sql/colexec/routers.go#L419)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is there enough overlap with other dynamically increasing behavior up to `coldata.BatchSize` to put a helper function that all code uses in `coldata`?
</blockquote></details>

I don't think so - `ResetMaybeReallocate` works dynamically based on the assumption that we have an "old batch"  that we can check the capacity of and double it if necessary, but in this case we always don't have that old batch.

We could have reused `ResetMaybeReallocate` method as follows:
```
diff --git a/pkg/sql/colexec/routers.go b/pkg/sql/colexec/routers.go
index 8688d46357..dbadf0a66e 100644
--- a/pkg/sql/colexec/routers.go
+++ b/pkg/sql/colexec/routers.go
@@ -426,12 +426,9 @@ func (o *routerOutputOp) addBatch(ctx context.Context, batch coldata.Batch, sele
                                        o.pendingBatchCapacity = len(selection)
                                } else {
                                        o.pendingBatchCapacity *= 2
-                                       if o.pendingBatchCapacity > coldata.BatchSize() {
-                                               o.pendingBatchCapacity = coldata.BatchSize()
-                                       }
                                }
                        }
-                       o.mu.pendingBatch = o.mu.unlimitedAllocator.NewMemBatchWithFixedCapacity(o.types, o.pendingBatchCapacity)
+                       o.mu.pendingBatch, _ = o.mu.unlimitedAllocator.ResetMaybeReallocate(o.types, o.mu.pendingBatch, o.pendingBatchCapacity)
                }
                available := o.mu.pendingBatch.Capacity() - o.mu.pendingBatch.Length()
                numAppended := toAppend
```
but still we are responsible for calculating min capacity dynamically.

Hm, actually it might be still worth using this diff since it indicates that we have a dynamic batch size behavior (although of a slightly different variant). I'll make that change.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
