### PR TITLE
logictestccl: add some data to partitioning_index test

### PR DESCRIPTION
**Pull request by vivekmenezes**
Release note: None

### CODE REVIEW

**Comment by vivekmenezes** [comment]
@lucy-zhang any thoughts on this?

**Review by thoszhang — APPROVED** [review]
Are these preemptive tests, or is there a related bug?

**Comment by vivekmenezes** [comment]
I added these tests while investigating https://github.com/cockroachdb/cockroach/issues/36937. At the time we were not sure if a simple partitioning example on data could cause the problem.

**Pull request merged**
