### PR TITLE
importccl: Set FK and CHECK constraints to unvalidated after IMPORT INTO

### PR DESCRIPTION
**Pull request by adityamaru27**
This change sets foreign key and CHECK constraints to unvalidated
after the table is imported into, but before the descriptor is
published in a PUBLIC state.

### CODE REVIEW

**Review by dt — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39183)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru27 and @dt)

___
*[pkg/ccl/importccl/import_stmt.go, line 975 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39183#-Ll8wLu7AnqOylPKiMww:-Ll8wLu82LCe_FP7ayVx:b-o0ih9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c33959696f7dab9e841ae44901d68f29ea2969/pkg/ccl/importccl/import_stmt.go#L975)):*
> ```Go
> 
> 		if !tbl.IsNew {
> 			// Set FK constraints to unvalidated before publishing the table imported into.
> ```

there's a helper for this if you didn't want to find all the index yourself `for _, idx := range tbl.AllNonDropIndexes()`
___
*[pkg/ccl/importccl/import_stmt.go, line 990 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39183#-Ll8wT0e6tPuho9QTxTi:-Ll8wT0e6tPuho9QTxTj:b-thp8yo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c33959696f7dab9e841ae44901d68f29ea2969/pkg/ccl/importccl/import_stmt.go#L990)):*
> ```Go
> 			// Set CHECK constraints to unvalidated before publishing the table imported into.
> 			tableDesc.Checks = make([]*sqlbase.TableDescriptor_CheckConstraint, len(tbl.Desc.Checks))
> 			for i, c := range tbl.Desc.Checks {
> ```

this direct access vs using the accessor is okay because we asserted that Mutations is empty

**Review by adityamaru27 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39183)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/ccl/importccl/import_stmt.go, line 975 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39183#-Ll8wLu7AnqOylPKiMww:-LlAC4gt5Zw09f0Zi_C_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c33959696f7dab9e841ae44901d68f29ea2969/pkg/ccl/importccl/import_stmt.go#L975)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

there's a helper for this if you didn't want to find all the index yourself `for _, idx := range tbl.AllNonDropIndexes()`
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/import_stmt.go, line 990 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39183#-Ll8wT0e6tPuho9QTxTi:-LlA6PTg5KrkjgvuM8yU:bddeow6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c33959696f7dab9e841ae44901d68f29ea2969/pkg/ccl/importccl/import_stmt.go#L990)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

this direct access vs using the accessor is okay because we asserted that Mutations is empty
</blockquote></details>

feels cleaner to use the accessor, done.

**Review by dt — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39183)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru27 and @dt)

___
*[pkg/ccl/importccl/import_stmt.go, line 975 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39183#-Ll8wLu7AnqOylPKiMww:-LlANiPS70qGeCaZWLd1:b-xf2j1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c33959696f7dab9e841ae44901d68f29ea2969/pkg/ccl/importccl/import_stmt.go#L975)):*
<details><summary><i>Previously, adityamaru27 (Aditya Maru) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not quite what I meant: the point of the helper returning pointers to index desc is that you can just mutate via the pointer. I actually think the direct field access was arguably bet
___
*[pkg/ccl/importccl/import_stmt.go, line 986 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39183#-LlAO6QG9awhLMwQXGaR:-LlAO6QG9awhLMwQXGaS:b-vj8wx5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad046ee5ba8df09632812c06d150762402869ed5/pkg/ccl/importccl/import_stmt.go#L986)):*
> ```Go
> 					tableDesc.PrimaryIndex = tableIdx
> 				} else {
> 					tableDesc.Indexes = append(tableDesc.Indexes, tableIdx)
> ```

Er, I don't think we want to be appending.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39183)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru27)

___
*[pkg/ccl/importccl/import_stmt.go, line 986 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39183#-LlAO6QG9awhLMwQXGaR:-LlAORG9CtHcO2akKF8Q:bmljtjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad046ee5ba8df09632812c06d150762402869ed5/pkg/ccl/importccl/import_stmt.go#L986)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Er, I don't think we want to be appending.
</blockquote></details>

~To expand on that: `AllNonDropIndexes` is returning pointers to things *already in* `desc.Indexes` (as well as to the PK and indexes in `Mutations`) so if we append like this, I think we're actually *duplicating* the existing indexes, right? Plus, if there were any in mutations (though I think in this case that is not a concern) this would be copying them to the public index list too outside the normal mutation completion path.~ Oh, I missed the blanking of desc.Indexes above, sorry. 🤦‍♂ that said, I'd think I'd still rather edit directly _via the pointer_, rather than in these special-case branches for the different descriptor fields, since apparently I'm prone to mis-reading it otherwise 😬.

**Review by adityamaru27 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39183)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/ccl/importccl/import_stmt.go, line 986 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39183#-LlAO6QG9awhLMwQXGaR:-LlCUHof1qL8ZzTnm54i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad046ee5ba8df09632812c06d150762402869ed5/pkg/ccl/importccl/import_stmt.go#L986)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

To expand on that: `AllNonDropIndexes` is returning pointers to things *already in* `desc.Indexes` (as well as to the PK and indexes in `Mutations`) so if we append like this, I think we're actually *duplicating* the existing indexes, right? Plus, if there were any in mutations (though I think in this case that is not a concern) this would be copying them to the public index list too outside the normal mutation completion path.
</blockquote></details>

Done.

**Pull request merged**
