### PR TITLE
sql: move histogram decoding into the stats cache

### PR DESCRIPTION
**Pull request by RaduBerinde**
Currently the stats cache exposes the encoded histogram data, and the
opt catalog decodes it. The problem is that opt catalog objects are
not shared across connections so this is inefficient (especially in
memory usage).

This change moves the decoding into the stats cache. The opt catalog
objects now simply point to the data computed by the cache.

There are still inefficiencies to improve on in the future: the opt
catalog can hold on to multiple versions of tables, so we will keep
many versions of histograms "alive".

Informs #41206.
Informs #40922.

Release justification: fix for new functionality.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
CC @nvanbenschoten

**Comment by RaduBerinde** [comment]
CC @nvanbenschoten

**Review by rytaft — APPROVED** [review]
:lgtm: Thanks for the fix!

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41220#-:-Lq7GdrNBqz7OeMcGOSh:b-72sm86)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
