### PR TITLE
gossip: Log connectivity no more than once a minute

### PR DESCRIPTION
**Pull request by a-robinson**
Fixes #30088

This will still probably result in logging it once a minute on large
clusters due to the inherent instability caused by connection culling,
but once a minute is a lot more bearable than the current state of
things.

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30730#-:-LNRKuWMEs6PE3xNY9R_:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by a-robinson** [comment]
Opened https://github.com/cockroachdb/cockroach/issues/30740 for the TestCDC flake

**Pull request merged**
