### PR TITLE
roachtest: disable "deadlock" failure in chaos tests

### PR DESCRIPTION
**Pull request by nvb**
Informs #132762.

This commit disables the replica deadlock failure mode in chaos tests. We don't want to run this form of failure in the chaos tests because we do not expect cockroach to recover from it and do not want to lose signal for the chaos tests. The deadlock failure mode continues to be used in its own individual test.

None of the three forms of leases (expiration, epoch, and leader) can survive a replica deadlock under default configuration. Epoch and leader leases cannot survive it by design without the introduction of a replica watchdog. Expiration leases can survive it if combined with DistSender circuit breakers, but those are not yet enabled by default, even though we do enable them in the chaos tests.

Release note: None

### CODE REVIEW

**Review by arulajmani — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133594#-:-OAK6XZAAj8vubKzY0q_:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @iskettaneh, @nvanbenschoten, and @vidit-bhat)

___
*[`pkg/cmd/roachtest/tests/failover.go` line 1438 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133594#-OAK6QLw9VNALqICrUFS:-OAK6QLw9VNALqICrUFT:b-ntj94f) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c52ba1f31a089a681ab1a71abd8c342bcc58a70/pkg/cmd/roachtest/tests/failover.go#L1438)):*
> ```Go
> func (f *deadlockFailer) CanUseChaos() bool {
> 	// We disable the deadlock failer in chaos tests, because none of the three
> 	// forms of leases (expiration, epoch, and leader) and survive it. Epoch and
> ```

comment seems off here. Did you mean "can survive it"?

**Review by nvb — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133594#-:-OAK6uj74SPkaRsS0sRY:b-tlx7ko)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @herkolategan, @iskettaneh, and @vidit-bhat)

___
*[`pkg/cmd/roachtest/tests/failover.go` line 1438 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133594#-OAK6QLw9VNALqICrUFS:-OAK6t5Q3KUKJOg4c3i3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c52ba1f31a089a681ab1a71abd8c342bcc58a70/pkg/cmd/roachtest/tests/failover.go#L1438)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

comment seems off here. Did you mean "can survive it"?
</blockquote></details>

Done.

**Comment by tbg** [comment]
blathers backport 24.2

**Comment by andrewbaptist** [comment]
blathers backport 23.2

**Pull request merged**
