### PR TITLE
Add GCE terraform config for benchmarks/sqllogic/stress

### PR DESCRIPTION
**Pull request by mberhault**
This runs exactly the same thing as the AWS benchmarks config.
The config is almost the same, relying on env variables for the gce credentials.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6094)

### CODE REVIEW

**Comment by mberhault** [comment]
cockroach-prod script change is here: https://github.com/cockroachdb/cockroach-prod/pull/86

**Comment by tschottdorf** [comment]
I somehow would've hoped to not have almost-identical setups for AWS and GCE (but to instead be able to run the same thing against one or the other). Is that too optimistic or just more work?

**Comment by mberhault** [comment]
switching providers in terraform changes a lot: the provide itself, as well as all the objects (aws_instance vs gce_instance), their specific fields (tags vs names, network config etc..), values (machine/image ID), and their dependencies (firewall vs forwarding rule).

Sharing the config between providers is also odd. The best we could do is make terraform modules which would define just the running part and which files to push. I may still do that, but this was the fastest way to test everything and get it running.

**Comment by cuongdo** [comment]
Reviewed 4 of 4 files at r1, 4 of 4 files at r2, 4 of 4 files at r3, 2 of 3 files at r4.
Review status: 10 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[cloud/gce/benchmarks/supervisor.conf, line 1 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6094#-KFdbQKXHc7HIde_hgZP:-KFdbQKYjpYhPxOeyHxt:-568429470) ([raw file](https://github.com/cockroachdb/cockroach/blob/c181a5bb4cfcafbd4e64c48003e87749f94516c1/cloud/gce/benchmarks/supervisor.conf#L1)):*
What's supervisor being used for w.r.t. benchmarks?

---

*[cloud/gce/benchmarks/variables.tf, line 1 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6094#-KFdbr5bXSznveGb_edq:-KFdbr5bXSznveGb_edr:481448791) ([raw file](https://github.com/cockroachdb/cockroach/blob/c181a5bb4cfcafbd4e64c48003e87749f94516c1/cloud/gce/benchmarks/variables.tf#L1)):*
So duplicative of `../variables.tf`. It seems terraform still doesn't have includes.

---

*[cloud/gce/sql_logic_tests/main.tf, line 1 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6094#-KFdcj2s9Cxrrm1eQg8S:-KFdcj2s9Cxrrm1eQg8T:-1955339463) ([raw file](https://github.com/cockroachdb/cockroach/blob/67c7445f64761bc7434411b0634505add8762567/cloud/gce/sql_logic_tests/main.tf#L1)):*
s/AWS/GCE/

---

*[cloud/gce/sql_logic_tests/main.tf, line 43 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6094#-KFdcpeLHbzkj6-2Jto1:-KFdcpeLHbzkj6-2Jto2:1210242232) ([raw file](https://github.com/cockroachdb/cockroach/blob/67c7445f64761bc7434411b0634505add8762567/cloud/gce/sql_logic_tests/main.tf#L43)):*
Does this line have a function, or is it intended to clarify something?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6094)*

**Comment by mberhault** [comment]
Review status: 10 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[cloud/gce/benchmarks/supervisor.conf, line 1 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6094#-KFdbQKXHc7HIde_hgZP:-KFdf6nYwVtAAoTOzusV:1458338430) ([raw file](https://github.com/cockroachdb/cockroach/blob/c181a5bb4cfcafbd4e64c48003e87749f94516c1/cloud/gce/benchmarks/supervisor.conf#L1)):*
the scripts constantly poll supervisor until the job is no longer running. We also get run time and exit code out of it. 

---

*[cloud/gce/benchmarks/variables.tf, line 1 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6094#-KFdbr5bXSznveGb_edq:-KFdfFYTJr2FMtH7ZIJr:-441621075) ([raw file](https://github.com/cockroachdb/cockroach/blob/c181a5bb4cfcafbd4e64c48003e87749f94516c1/cloud/gce/benchmarks/variables.tf#L1)):*
unfortunately not. modules may help, but they're not particularly clearer.

---

*[cloud/gce/sql_logic_tests/main.tf, line 1 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6094#-KFdcj2s9Cxrrm1eQg8S:-KFdfSjKpOYuTTvrktHj:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/67c7445f64761bc7434411b0634505add8762567/cloud/gce/sql_logic_tests/main.tf#L1)):*
Done.

---

*[cloud/gce/sql_logic_tests/main.tf, line 43 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6094#-KFdcpeLHbzkj6-2Jto1:-KFdf-yLIBpwawLYLF7U:-1359621949) ([raw file](https://github.com/cockroachdb/cockroach/blob/67c7445f64761bc7434411b0634505add8762567/cloud/gce/sql_logic_tests/main.tf#L43)):*
just clarifying. it can optionally have permanent addresses, but we don't need those.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6094)*

**Comment by mberhault** [comment]
This takes care of all the nightly runs.

**Comment by cuongdo** [comment]
:lgtm:

---

Review status: 9 of 22 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6094#-:-KFe3_MqiDlyhZGZCiyS:1417088721)*

**Pull request merged**
