### PR TITLE
 kvcoord: Add observability for actively running range feeds.

### PR DESCRIPTION
**Pull request by miretskiy**
Add a `crdb_internal.active_range_feeds` virtual table which lists
all currently running range feeds on a node.

The table lists the span for which the range feed was started, along with all of the ranges 
making up that span.
Per range information, including the node where the range feed is running
against, as well as the timestamp when the last non-error event has
been seen from the range is recorded in the table.

```
root@:26257/defaultdb> select * from crdb_internal.active_range_feeds order by id, range_start;
       id      |              tags              | range_start |  range_end  |            startts             | diff  | node_id |     partial_range_start      |      partial_range_end       |            resolved            | last_event_utc
---------------+--------------------------------+-------------+-------------+--------------------------------+-------+---------+------------------------------+------------------------------+--------------------------------+-----------------
  824655839232 | n?,rangefeed=table-stats-cache | /Table/20   | /Table/21   | 1629329537656207000.0000000000 | false |       1 | /Table/20                    | /Table/21                    | 1629335390881550000.0000000000 |           NULL
  824657576368 | n1,rangefeed=lease             | /Table/3    | /Table/4    | 0.0000000000                   | false |       1 | /Table/3                     | /Table/4                     | 1629335390881550000.0000000000 |           NULL
  824680146768 | n1,job=685578580453523457      | /Table/53/2 | /Table/53/3 | 1629329458537238000.0000000000 | false |       1 | /Table/53/2                  | /Table/53/2/"\x80"           | 1629335390881550000.0000000000 |           NULL
  824680146768 | n1,job=685578580453523457      | /Table/53/2 | /Table/53/3 | 1629329458537238000.0000000000 | false |       1 | /Table/53/2/"\x80"/PrefixEnd | /Table/53/3                  | 1629335390881550000.0000000000 |           NULL
  824680146768 | n1,job=685578580453523457      | /Table/53/2 | /Table/53/3 | 1629329458537238000.0000000000 | false |       1 | /Table/53/2/"\x80"           | /Table/53/2/"\x80"/PrefixEnd | 1629335390881550000.0000000000 |           NULL
(11 rows)
```

Release Notes: Improve range feed observability by adding a
`crdb_internal.active_range_feeds` virtual table which lists  
 all currently executing range feeds on the node.

### CODE REVIEW

**Comment by miretskiy** [comment]
@ajwerner @andreimatei I think this kind of PR might be better than the other one that tries to restart changefeeds.
If needed, we can have an internal process that monitors "slow" ranges, and at least increments some metrics for observability.

**Review by ajwerner — COMMENTED** [review]
This is going to be extremely useful. Can you add querying this to the debug zip endpoint? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-:-MhP63KE69UZw5ODY8-p:b-l9z4m4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @miretskiy)

___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-MhP3_HF7u4hZ8qazPry:-MhP3_HF7u4hZ8qazPrz:bqrwyim) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdeb92a820cec6596d86d089acdb53fb7c70d06/pkg/kv/kvclient/kvcoord/dist_sender.go#L295)):*
> ```Go
> 
> 	// Currently executing range feeds.
> 	activeRangeFeeds sync.Map
> ```

can you put a comment with the types, like, in this case, `// map[*rangeFeedRegistry]nil`
___
*[pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-MhP4xILD_nWUC0tizNC:-MhP4xILD_nWUC0tizND:bz9bn0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdeb92a820cec6596d86d089acdb53fb7c70d06/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L114)):*
> ```Go
> 
> // ActiveRangeFeed structure describes the state of currently executing range feed.
> type ActiveRangeFeed struct {
> ```

How about we use the word `partial` somewhere around here?
___
*[pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-MhP54mv2Ua8TPnxveaZ:-MhP54mv2Ua8TPnxvea_:b-hzhwaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdeb92a820cec6596d86d089acdb53fb7c70d06/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L114)):*
> ```Go
> 
> // ActiveRangeFeed structure describes the state of currently executing range feed.
> type ActiveRangeFeed struct {
> ```

I think we really want to track the current resolved timestamp somehow. 
___
*[pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-MhP4soMBSVeoPSfmErA:-MhP4soMBSVeoPSfmErB:b-oyjvsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdeb92a820cec6596d86d089acdb53fb7c70d06/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L121)):*
> ```Go
> }
> 
> // ActiveRangeFeedIterFn is an iterator function which is passed ActiveRangeFeed structure.
> ```

mention `iterutil.StopIteration`
___
*[pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go, line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-MhP4W_Y6NyBDwZhWotf:-MhP4W_Y6NyBDwZhWotg:b7kio21) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdeb92a820cec6596d86d089acdb53fb7c70d06/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L134)):*
> ```
> 			active := k.(*activeRangeFeed)
> 			active.Lock()
> 			defer active.Unlock()
> ```
how about we just copy the `ActiveRangeFeed` struct out and pass it to the callback. It'd be bad if this callback blocked, and, for virtual tables, it very much may block if the consumer stops consuming rows. 
___
*[pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go, line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-MhP4m5g8y0QKgRr_ZFc:-MhP4m5g8y0QKgRr_ZFd:b-7hv2mr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdeb92a820cec6596d86d089acdb53fb7c70d06/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L143)):*
> ```Go
> 		return iterErr == nil
> 	})
> ```

Can you add:

```
if iterutil.Done(err) {
    err = nil
}
```
___
*[pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-MhP5ahE19y2pf_u6uW4:-MhP5ahE19y2pf_u6uW5:b75i9zz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdeb92a820cec6596d86d089acdb53fb7c70d06/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L165)):*
> ```Go
> 	RangeFeedContext
> 	// Map of ranges (activeRangeFeed* -> nil) started by this registry.
> 	ranges sync.Map
> ```

nit: I prefer a comment to look like

```go
// feel free to put more commentary here.
ranges sync.Map // map[*activeRangeFeed]nil
```
___
*[pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go, line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-MhP5GyWESWBzmrqQivI:-MhP5GyWESWBzmrqQivJ:bc763an) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdeb92a820cec6596d86d089acdb53fb7c70d06/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L169)):*
> ```
> // startPartialRangeFeed starts execution of partial rangefeed.
> func (r *rangeFeedRegistry) startPartialRangeFeed(
> ```
is there any reason to not just pass `rangeFeedRegistry` to `partialRangeFeed` and just inline this there? 
___
*[pkg/sql/crdb_internal.go, line 5063 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-MhP5tWO1XECIUjbK1mY:-MhP5tWO1XECIUjbK1mZ:b-iydi6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdeb92a820cec6596d86d089acdb53fb7c70d06/pkg/sql/crdb_internal.go#L5063)):*
> ```Go
> );`,
> 	populate: func(ctx context.Context, p *planner, _ catalog.DatabaseDescriptor, addRow func(...tree.Datum) error) error {
> 		return p.extendedEvalCtx.DistSQLPlanner.distSender.ForEachActiveRangeFeed(
> ```

nit: don't go in the eval context here. Can you instead do `p.execCfg.DistSender`?

**Review by miretskiy — COMMENTED** [review]
Added to zip_per_node

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-:-MhQLEzV5jSJmiL2-TXy:b4z763m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @andreimatei)

___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-MhP3_HF7u4hZ8qazPry:-MhPGBhi4gejsgSX9Ntp:bnl3z0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdeb92a820cec6596d86d089acdb53fb7c70d06/pkg/kv/kvclient/kvcoord/dist_sender.go#L295)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

can you put a comment with the types, like, in this case, `// map[*rangeFeedRegistry]nil`
</blockquote></details>

Nice.  Done
___
*[pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-MhP4xILD_nWUC0tizNC:-MhPH5WGB8k3_JfQmUVI:box2fgw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdeb92a820cec6596d86d089acdb53fb7c70d06/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L114)):*
> How about we use the word partial somewhere around here?
Done.
___
*[pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-MhP54mv2Ua8TPnxveaZ:-MhPH6XK8k80st4eHzX4:baij5u3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdeb92a820cec6596d86d089acdb53fb7c70d06/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L114)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think we really want to track the current resolved timestamp somehow. 
</blockquote></details>

Done -- updated virtual table to display both the timestamp of the last KV event and the time of last checkpoint.
___
*[pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-MhP4soMBSVeoPSfmErA:-MhQGGEK7BeG5OviGoi0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdeb92a820cec6596d86d089acdb53fb7c70d06/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L121)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

mention `iterutil.StopIteration`
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go, line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-MhP4W_Y6NyBDwZhWotf:-MhQFkxt7vgGhpl-r4-Y:b-y1hsva) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdeb92a820cec6596d86d089acdb53fb7c70d06/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L134)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 			active := k.(*activeRangeFeed)
> 			active.Lock()
> 			defer active.Unlock()
> ```
how about we just copy the `ActiveRangeFeed` struct out and pass it to the callback. It'd be bad if this callback blocked, and, for virtual tables, it very much may block if the consumer stops consuming rows. 
</blockquote></details>

Done... It's true that the consumer may pause if e.g. we have some memory pressure.
___
*[pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go, line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-MhP4m5g8y0QKgRr_ZFc:-MhQG_FcAQLONMWU0P11:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdeb92a820cec6596d86d089acdb53fb7c70d06/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L143)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can you add:

```
if iterutil.Done(err) {
    err = nil
}
```
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-MhP5ahE19y2pf_u6uW4:-MhQGf3F7H-awOZGgSrw:b-1rpo1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdeb92a820cec6596d86d089acdb53fb7c70d06/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L165)):*
> // map[*activeRangeFeed]nil
Done.
___
*[pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go, line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-MhP5GyWESWBzmrqQivI:-MhQHXB-3HI32I8VOwuE:bdg5664) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdeb92a820cec6596d86d089acdb53fb7c70d06/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L169)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> // startPartialRangeFeed starts execution of partial rangefeed.
> func (r *rangeFeedRegistry) startPartialRangeFeed(
> ```
is there any reason to not just pass `rangeFeedRegistry` to `partialRangeFeed` and just inline this there? 
</blockquote></details>

Nope.  Gone.

**Review by ajwerner — APPROVED** [review]
:lgtm:

If you're willing, could you put a snippet of output from the table in the PR description? It'll be cool to see it. This thing is going to be very handy. 

> Reviewed 2 of 5 files at r1, 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-:-MhQ_0-9DqxkvqTdEhKi:b-tfgdu1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, and @miretskiy)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 4414 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-MhQZfZP5x7wAXhYOTpt:-MhQZfZP5x7wAXhYOTpu:bh3slqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/c204943d6d9ac73916fa4ad7ada2ffa1f265a619/pkg/ccl/changefeedccl/changefeed_test.go#L4414)):*
> ```Go
> CREATE TABLE tbl (a INT, b STRING);
> INSERT INTO tbl VALUES (1, 'one'), (2, 'two'), (3, 'three');
> CREATE CHANGEFEED FOR tbl INTO 'null://';
> ```

the `null` sink is nifty
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 4424 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-MhQZkeY-wPvetK92T2P:-MhQZkeY-wPvetK92T2Q:bguve3y) ([raw file](https://github.com/cockroachdb/cockroach/blob/c204943d6d9ac73916fa4ad7ada2ffa1f265a619/pkg/ccl/changefeedccl/changefeed_test.go#L4424)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
> 	testutils.SucceedsSoon(t, func() error {
> 		var numRanges int
> 		sqlDB.QueryRow(t, numRangesQuery).Scan(&numRanges)
> 		if numRanges == 0 {
> 			return errors.New("still waiting for ranges to be registered")
> 		}
> 		return nil
> 	})
> ```
</details>


?
```go
sqlDB.CheckQueryResultsRetry(t, numRangesQuery, [][]string{{"1"}})
```
___
*[pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go, line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-MhP4W_Y6NyBDwZhWotf:-MhQYRFI3kWhCilyZuWf:b-r0d6hy) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdeb92a820cec6596d86d089acdb53fb7c70d06/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L134)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Done... It's true that the consumer may pause if e.g. we have some memory pressure.
</blockquote></details>

By consumer here I meant the reader of the `crdb_internal` table. That is going to be driven by a client connection and underneath the callback here we're likely call a function to push a row up to the connection. That thing can block if the client stops calling `Next()` on their `Rows`. It'd be bad if we couldn't update something in this `*activeRangeFeed` because a SQL client stopped asking for rows. 
___
*[pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-MhQa629-2SygL-CvY-2:-MhQ_KaA-kaIDPPaoYYw:b-bm618g) ([raw file](https://github.com/cockroachdb/cockroach/blob/c204943d6d9ac73916fa4ad7ada2ffa1f265a619/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L98)):*
> ```Go
> // RangeFeed call.  It functions as a kind of key for an active range feed.
> type RangeFeedContext struct {
> 	CtxTags string // context tags
> ```

nit: How crazy would it be to store the `context.Context` here too? Might make some testing pretty interesting. Maybe for later. 
___
*[pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go, line 111 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-MhQazB86GXEcZmjD0Jg:-MhQazB86GXEcZmjD0Jh:bzgp3ld) ([raw file](https://github.com/cockroachdb/cockroach/blob/c204943d6d9ac73916fa4ad7ada2ffa1f265a619/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L111)):*
> ```Go
> 	StartTS   hlc.Timestamp
> 	NodeID    roachpb.NodeID
> 	LastEvent time.Time
> ```

nit: what if we call this `LastValueReceived`? It's only the value events that seem to move this.

**Review by miretskiy — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-:-MhQxAfoBlSC8LYR6tDB:b-896fix)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @andreimatei)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 4414 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-MhQZfZP5x7wAXhYOTpt:-MhQxfBKElUwbJ-8yI5r:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/c204943d6d9ac73916fa4ad7ada2ffa1f265a619/pkg/ccl/changefeedccl/changefeed_test.go#L4414)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

the `null` sink is nifty
</blockquote></details>

Ack.
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 4424 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-MhQZkeY-wPvetK92T2P:-MhQxwKw6tiBLIZ8dJjs:bxwvn4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/c204943d6d9ac73916fa4ad7ada2ffa1f265a619/pkg/ccl/changefeedccl/changefeed_test.go#L4424)):*
> sqlDB.CheckQueryResultsRetry(t, numRangesQuery, [][]string{{"1"}})
Cool.
___
*[pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-MhQa629-2SygL-CvY-2:-MhQy0UWBy8Tw52PGIZx:bown57y) ([raw file](https://github.com/cockroachdb/cockroach/blob/c204943d6d9ac73916fa4ad7ada2ffa1f265a619/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L98)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: How crazy would it be to store the `context.Context` here too? Might make some testing pretty interesting. Maybe for later. 
</blockquote></details>

We could, I suppose.  
___
*[pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go, line 111 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69055#-MhQazB86GXEcZmjD0Jg:-MhQyPlRCGYD6HAGTzli:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c204943d6d9ac73916fa4ad7ada2ffa1f265a619/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L111)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: what if we call this `LastValueReceived`? It's only the value events that seem to move this. 
</blockquote></details>

Done.

**Comment by miretskiy** [comment]
FYI: @ajwerner I'm going to rename some of the columns in the vtable: 
range_start/end -> span_start/end since this is the span for which rangefeed was started
and partial_range_start/end to just range_start/end.

**Comment by miretskiy** [comment]
FYI: Added range id to the list of columns.

**Comment by miretskiy** [comment]
bors r=ajwerner

**Pull request merged**
