### PR TITLE
opt/constraints: add Combine primitive

### PR DESCRIPTION
**Pull request by RaduBerinde**
Combine takes constraints on columns `/a/b/c/d`, `/b/c/d`, `/c/d`, `/d` and
tries to make a refined constraint on `/a/b/c/d`. For example for
`a = 1 AND b > 2` we would have constraints `/a/b: [/1 - /1]` and
`/b: [/2 - ]` which we can combine into `/a/b: [/1/2 - /1]`.

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
:lgtm: Wow that's complicated! But it looks right to me...

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24133#-:-L8DL8DJ0pfxUMMTbA_j:b50h1po)*

**Comment by RaduBerinde** [comment]
Forgot to mention, most of the logic is from https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt/idxconstraint/index_constraints.go#L696

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/constraint/constraint.go, line 304 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24133#-L8DKBTJ0j_kqFiReiU4:-L8DKBTJ0j_kqFiReiU5:bsd7wcx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0727016888ed2e794aac39ccee748498e1535b1/pkg/sql/opt/constraint/constraint.go#L304)):*
> ```Go
> //  - suffixes[1] is a constraint on columns c,d, etc
> //  - and so on.
> func (c *Constraint) Combine(evalCtx *tree.EvalContext, suffixes []Constraint) {
> ```

How come the method needs to take all suffixes at once? Would it be sufficient to just take one at a time in order to simplify the API and needed processing? Is it quite a bit more efficient to do it this way?

---

*[pkg/sql/opt/constraint/constraint.go, line 338 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24133#-L8DLwgW0GoL5mq7dSZE:-L8DLwgW0GoL5mq7dSZF:bdj0yzs) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0727016888ed2e794aac39ccee748498e1535b1/pkg/sql/opt/constraint/constraint.go#L338)):*
> ```Go
> 	result := MakeSpans(c.Spans.Count())
> 	stack := MakeSpans(c.Spans.Count())
> 	for i := 0; i < c.Spans.Count(); i++ {
> ```

If you have to reverse the spans anyway, how come you can't initially add them in reverse order to begin with in order to avoid the final reverse op:
```
for i := c.Spans.Count(); i >= 0; i-- {
```

---

*[pkg/sql/opt/constraint/constraint.go, line 345 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24133#-L8DOv9jgcpMKIMLIShx:-L8DOv9jgcpMKIMLIShy:b6cg6oa) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0727016888ed2e794aac39ccee748498e1535b1/pkg/sql/opt/constraint/constraint.go#L345)):*
> ```Go
> 	for stack.Count() > 0 {
> 		// Pop a span from the stack.
> 		sp = stack.Get(stack.Count() - 1).Copy()
> ```

NIT: Appending to the stack already makes a copy of the span, so do you need the extra `Copy` here?

---

*[pkg/sql/opt/constraint/constraint_test.go, line 332 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24133#-L8DPnHHuozqEyzSNCrx:-L8DPnHHuozqEyzSNCry:b-kqvz0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0727016888ed2e794aac39ccee748498e1535b1/pkg/sql/opt/constraint/constraint_test.go#L332)):*
> ```Go
> 	c[0].Combine(evalCtx, c[1:])
> 
> 	exp := "/1/2/3/4: " +
> ```

Are you sure this one test case is testing all the conditionals and edge cases of the code? What I often do to verify is to temporarily sprinkle panics in various places in the code and make sure the test case is triggering them. Poor man's code coverage. Or you can use the go code coverage tool, which I invoke like this:
```
go test -coverprofile=coverage.out -run TestConstraintCombine
go tool cover -html=coverage.out && rm coverage.out
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24133)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/constraint/constraint.go, line 304 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24133#-L8DKBTJ0j_kqFiReiU4:-L8DSbRGhg4rV-GsbRVl:btuksxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0727016888ed2e794aac39ccee748498e1535b1/pkg/sql/opt/constraint/constraint.go#L304)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

How come the method needs to take all suffixes at once? Would it be sufficient to just take one at a time in order to simplify the API and needed processing? Is it quite a bit more efficient to do it this way?
</blockquote></details>

Hm. I would need to pass or calculate the offset, and then sprinkle checks around to see if the offset matches exactly what we're trying to do. We would create a new set of spans each time, and it may require more intermediate steps (e.g. we may not be able to extend both the start key and the end key in the same operation). We wouldn't need the stack though.

I'll give it a try though and see how it looks.

---

*[pkg/sql/opt/constraint/constraint.go, line 338 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24133#-L8DLwgW0GoL5mq7dSZE:-L8DTrq-zk2bx8wawaT0:b-36yav8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0727016888ed2e794aac39ccee748498e1535b1/pkg/sql/opt/constraint/constraint.go#L338)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

If you have to reverse the spans anyway, how come you can't initially add them in reverse order to begin with in order to avoid the final reverse op:
```
for i := c.Spans.Count(); i >= 0; i-- {
```
</blockquote></details>

we'd have to do the same also in another similar loop below

---

*[pkg/sql/opt/constraint/constraint.go, line 345 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24133#-L8DOv9jgcpMKIMLIShx:-L8DUFY0F14kyTy8PLeB:b8nmlxl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0727016888ed2e794aac39ccee748498e1535b1/pkg/sql/opt/constraint/constraint.go#L345)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: Appending to the stack already makes a copy of the span, so do you need the extra `Copy` here?
</blockquote></details>

We modify `sp` so I'd have to do `*stack.Get()` which is very close to what Copy() is.

---

*[pkg/sql/opt/constraint/constraint_test.go, line 332 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24133#-L8DPnHHuozqEyzSNCrx:-L8DUTu1W1H9QXm6SzYe:b-4fz9ov) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0727016888ed2e794aac39ccee748498e1535b1/pkg/sql/opt/constraint/constraint_test.go#L332)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Are you sure this one test case is testing all the conditionals and edge cases of the code? What I often do to verify is to temporarily sprinkle panics in various places in the code and make sure the test case is triggering them. Poor man's code coverage. Or you can use the go code coverage tool, which I invoke like this:
```
go test -coverprofile=coverage.out -run TestConstraintCombine
go tool cover -html=coverage.out && rm coverage.out
```
</blockquote></details>

It did catch a few bugs. I'm also relying on the index constraints tests. I agree we would need more tests, but these tests are very tedious to write. I'm going to post another PR which adds something that makes writing tests easier, maybe I'll merge that first and try using that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24133)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/opt/constraint/constraint.go, line 304 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24133#-L8DKBTJ0j_kqFiReiU4:-L8E3QZc-v13JL6w18_G:b4uvsra) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0727016888ed2e794aac39ccee748498e1535b1/pkg/sql/opt/constraint/constraint.go#L304)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Don't spend much time on it, I just wanted to make sure you'd considered this other approach, and had good reasons for doing it this way instead.
</blockquote></details>

Done, indeed it's cleaner this way. I'm not sure what to expect efficiency-wise, there's probably cases where the old approach was better, but there are cases where this one is better (for one, the case where we can't combine anything).

---

*[pkg/sql/opt/constraint/constraint.go, line 345 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24133#-L8DOv9jgcpMKIMLIShx:-L8E3seOxrtWbi7UTldn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0727016888ed2e794aac39ccee748498e1535b1/pkg/sql/opt/constraint/constraint.go#L345)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Right, I was suggesting *stack.Get(), since it avoids unnecessary intermediate copies.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24133)*

**Comment by rytaft** [comment]
Reviewed 1 of 4 files at r2.
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/constraint/utils_test.go, line 25 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/24133#-L8EBdSr5SlXZ8sG1nYu:-L8EBdSr5SlXZ8sG1nYv:buvgws) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8304cfe6141c9cf699f597fc493ffd4c3f5ede2/pkg/sql/opt/constraint/utils_test.go#L25)):*
> ```Go
> )
> 
> // parrseConstraint parses a constraint in the format of Constraint.String, e.g:
> ```

parrse -> parse

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24133)*

**Comment by RaduBerinde** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/opt/constraint/utils_test.go, line 25 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24133#-L8EBdSr5SlXZ8sG1nYu:-L8EHzts-ZL-QFiukAuj:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8304cfe6141c9cf699f597fc493ffd4c3f5ede2/pkg/sql/opt/constraint/utils_test.go#L25)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

parrse -> parse
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24133)*

**Comment by RaduBerinde** [comment]
Updated with two improvements: fixed pointer escape problem in `Combine`, and made `Columns.IsSuffix` faster.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24133#-:-L8Hmv5G-T-WgOaQoXCW:b-fvntih)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/opt/constraint/columns.go, line 85 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24133#-L8IkHOrC2pQM7C42Zxy:-L8IkHOrC2pQM7C42Zxz:b-pl7f8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ca461d6aa3c6ed1eadb9acd0952780e3742f220/pkg/sql/opt/constraint/columns.go#L85)):*
> ```Go
> // IsSuffixOf returns true if the columns in c are a strict suffix of the
> // columns in other.
> func (c *Columns) IsSuffixOf(other *Columns) bool {
> ```

NIT: Should this be called `IsStrictSuffixOf` since it is false if the two are equal?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24133#-:-L8IlUYw-ZDAMC0UoB5e:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/opt/constraint/columns.go, line 85 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24133#-L8IkHOrC2pQM7C42Zxy:-L8JHdNq8F8_y9_vwCJQ:b-1eh3wi) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ca461d6aa3c6ed1eadb9acd0952780e3742f220/pkg/sql/opt/constraint/columns.go#L85)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: Should this be called `IsStrictSuffixOf` since it is false if the two are equal?
</blockquote></details>

Sure, done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24133)*

**Pull request merged**
