### PR TITLE
docs: properly generate HTML files for updated SQL diagrams

### PR DESCRIPTION
**Pull request by taroface**
#117651 created several new SQL diagrams and updated an existing diagram. However, the corresponding HTML files used on docs pages weren't being regenerated. This PR should cause the files to regenerate (confirmed locally with `./dev build docs/generated/sql/bnf:svg`).

@DrewKimball The updated HTML files match the screenshots in #117651.

Epic: CRDB-799

Release note: None

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm: Looks like you need to run `./dev gen`.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117937#-:-NoTEAeG2FYWLgB4czGp:bbhml2p)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @taroface)

___
*[`pkg/cmd/docgen/diagrams.go` line 520 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117937#-NoTDwYV-Ur6xZCVu6FU:-NoTDwYV-Ur6xZCVu6FV:bu7r0gf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c50add604bc74bd05d4c7b6976e4b1e5661c4a3d/pkg/cmd/docgen/diagrams.go#L520)):*
> ```Go
> 	{
> 		name:    "alter_proc",
> 		stmt:    "alter_proc_stmt",
> ```

Why split `name` and `stmt` instead of just using `name` like the other cases in this file do? I'm happy with either way, just asking.

**Comment by taroface** [comment]
> Why split `name` and `stmt` instead of just using `name` like the other cases in this file do? I'm happy with either way, just asking.

I wish I understood this better, but changing the name seems to be necessary in order to have the generated HTML files reflect the changes in the definition. I think it is related to the fact that the HTML generation automatically strips `_stmt` from the HTML filenames, so those files end up getting conflated with the initial `_stmt` definitions without any of the additional modifications applied. I last ran into this problem in https://github.com/cockroachdb/cockroach/pull/95591 and had forgotten until now.

**Comment by taroface** [comment]
bors r=DrewKimball

**Comment by rickystewart** [comment]
bors r-

Does not pass CI

**Comment by DrewKimball** [comment]
This is what the failure looks like:
```
Ensure generated files match
  diff: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/docs/generated/sql/bnf/call.bnf: No such file or directory
  diff: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/docs/generated/sql/bnf/create_proc.bnf: No such file or directory
  diff: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/docs/generated/sql/bnf/alter_proc.bnf: No such file or directory
  diff: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/docs/generated/sql/bnf/create_func.bnf: No such file or directory
  diff: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/docs/generated/sql/bnf/drop_proc.bnf: No such file or directory
  Process exited with code 1
```
Did `./dev gen` not regenerate these files?

**Comment by taroface** [comment]
I had to run `./dev gen bnf` to generate new .bnf files, which I hadn't thought was necessary. Sorry!

**Comment by taroface** [comment]
I'm unfortunately at a loss to fix the error `Process exited with code 1 (Step: Build (Command Line))`. Is that a flake?

**Comment by DrewKimball** [comment]
One failure looks like https://github.com/cockroachdb/cockroach/issues/99988, which is a flake. The other is this:
```
00:53:24     File /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/bazel-bin/docs/generated/sql/bnf/alter_proc_stmt.bnf does not exist as a generated artifact. Is docs/generated/sql/bnf/BUILD.bazel up-to-date?
00:53:24     File /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/bazel-bin/docs/generated/sql/bnf/call_stmt.bnf does not exist as a generated artifact. Is docs/generated/sql/bnf/BUILD.bazel up-to-date?
00:53:24     File /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/bazel-bin/docs/generated/sql/bnf/create_func_stmt.bnf does not exist as a generated artifact. Is docs/generated/sql/bnf/BUILD.bazel up-to-date?
00:53:24     File /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/bazel-bin/docs/generated/sql/bnf/create_proc_stmt.bnf does not exist as a generated artifact. Is docs/generated/sql/bnf/BUILD.bazel up-to-date?
00:53:24     File /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/bazel-bin/docs/generated/sql/bnf/drop_proc_stmt.bnf does not exist as a generated artifact. Is docs/generated/sql/bnf/BUILD.bazel up-to-date?
00:53:24     Generated files do not match! Are the checked-in generated files up-to-date?
```
Possibly, you're going to have to manually edit the `bnf/BUILD.bazel` files. Looks like https://github.com/cockroachdb/cockroach/issues/83654 is related to that.

**Comment by taroface** [comment]
blathers backport 23.2

**Pull request merged**
