### PR TITLE
sql: support redaction of EXPLAIN (PLAN)

### PR DESCRIPTION
**Pull request by michae2**
**sql: support redaction of EXPLAIN (PLAN)**

Support redaction of `EXPLAIN (PLAN)` and add plan.txt back to redacted
statement diagnostics bundles.

Part of: #68570

Epic: CRDB-19756

Release note (sql change): Add support for the `REDACT` flag to the
following variants of `EXPLAIN`:
- `EXPLAIN`
- `EXPLAIN (PLAN)`
- `EXPLAIN (VEC)`
- `EXPLAIN ANALYZE`
- `EXPLAIN ANALYZE (PLAN)`
These explain statements (along with `EXPLAIN ANALYZE (DEBUG)`, which
already supported `REDACT`) will have constants, literal values,
parameter values, and any other user data redacted in output.

**explain: rename RedactFlags to DeflakeFlags**

Now that we have a new `RedactValues` field in `explain.Flags` there is
some confusion with the existing `RedactFlags`. Rename these to
`DeflakeFlags`.

Part of: #68570

Epic: CRDB-19756

Release note: None

**sql: add randomized test for EXPLAIN (REDACT)**

Add a randomized test which calls every `EXPLAIN (REDACT)` variant on a
few random statements, and checks that the output does not contain an
injected string representing PII. As more `EXPLAIN (REDACT)` variants
are added the test will naturally include them by virtue of trying every
combination of explain mode and flag.

Part of: #68570

Epic: CRDB-19756

Release note: None

### CODE REVIEW

**Comment by michae2** [comment]
First two commits are #94950 and can be ignored.

**Review by RaduBerinde — APPROVED** [review]
We need tests to verify that stuff in filters, projections, etc (any SQL expression really) get redacted inside `plan.txt`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95136#-:-NLXzdvf0FCbdI4btKPL:bmxuqh4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @michae2, and @yuzefovich)

___
*[`pkg/sql/opt/exec/explain/flags.go` line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95136#-NLXxmP5564UTW6u8pim:-NLXxmP5564UTW6u8pin:b-r60ys0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1007075db47cdda6007960b42585582a7402cb5/pkg/sql/opt/exec/explain/flags.go#L86)):*
> ```Go
> 	}
> 	if options.Flags[tree.ExplainFlagRedact] {
> 		// Confusingly, this doesn't use any of the RedactFlags, which have a
> ```

We should rename `RedactFlags` to something like `TestingEditFlags` or `DeflakeFlags` (and the constants to `HideDistribution` or `DeflakeDistribution` etc).

(sorry I'm not commenting in the right PR but I couldn't find this diff in the other one)

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95136)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @michae2)

___
*[`pkg/sql/opt/exec/explain/output.go` line 210 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95136#-NLchsdBCW6iOcuGvXFq:-NLchsdBCW6iOcuGvXFr:b-5dosv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/19fb321fa2294dcf340160c972642e8cecd1ad22/pkg/sql/opt/exec/explain/output.go#L210)):*
> ```Go
> 		stack = append(stack[:entry.level], child)
> 		if entry.columns != "" {
> 			child.AddLine(fmt.Sprintf("columns: %s", entry.columns))
> ```

We're ok with not redacting the schema, right?

**Review by michae2 — COMMENTED** [review]
* renamed `RedactFlags` to `DeflakeFlags`
* added a randomized test

Looks like the randomized test already caught something, so hold off on reviewing for a little bit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95136#-:-NN4LJh-3A9uy3Oz35bY:b-6z8i0c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @yuzefovich)

___
*[`pkg/sql/opt/exec/explain/flags.go` line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95136#-NLXxmP5564UTW6u8pim:-NN4LNzx2AWLi5YhCzdb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1007075db47cdda6007960b42585582a7402cb5/pkg/sql/opt/exec/explain/flags.go#L86)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We should rename `RedactFlags` to something like `TestingEditFlags` or `DeflakeFlags` (and the constants to `HideDistribution` or `DeflakeDistribution` etc).

(sorry I'm not commenting in the right PR but I couldn't find this diff in the other one)
</blockquote></details>

Done.
___
*[`pkg/sql/opt/exec/explain/output.go` line 210 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95136#-NLchsdBCW6iOcuGvXFq:-NN4L-Z96uwrDapaXfgV:b-kit75r) ([raw file](https://github.com/cockroachdb/cockroach/blob/19fb321fa2294dcf340160c972642e8cecd1ad22/pkg/sql/opt/exec/explain/output.go#L210)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

We're ok with not redacting the schema, right?
</blockquote></details>

Yes, it's fine to print column names. Constants in the schema, (e.g. `DEFAULT` values, constants in virtual column expressions, etc.) should be redacted.

**Comment by michae2** [comment]
Fixed the PII leak caught by the randomized test (it was in `pkg/sql/opt/exec/explain/emit.go` when printing a subquery) and the other test failures. I stressed `TestExplainRedact` a few hundred times without any additional failures. This should be ready, PTAL.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 8 of 8 files at r4, 7 of 7 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95136)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @michae2)

___
*[`pkg/sql/explain_test.go` line 478 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95136#-NNEfNU47mjcZJP7k7iP:-NNEfNU47mjcZJP7k7iQ:bds3i29) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bc1d1ea2a11e8ce738cf87c006fae9dfdff45aa/pkg/sql/explain_test.go#L478)):*
> ```Go
> 
> // TestExplainRedact tests that variants of EXPLAIN (REDACT) do not leak PII.
> func TestExplainRedact(t *testing.T) {
> ```

Nice test!
___
*[`pkg/sql/explain_test.go` line 532 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95136#-NNEfESD74-SwBNXAmdz:-NNEfESD74-SwBNXAme-:b-v4e8in) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bc1d1ea2a11e8ce738cf87c006fae9dfdff45aa/pkg/sql/explain_test.go#L532)):*
> ```Go
> 			continue
> 		}
> 		modes = append(modes, modeStr+", ")
> ```

nit: it might be cleaner to just add the commas explicitly in the `explain := ` assignment in the loop below.

**Review by michae2 — COMMENTED** [review]
The most recent change also fixed a bug where we weren't hiding constants when printing subqueries, and this is what the changes to `TestPlanGistBuilder` are about. This is RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95136#-:-NNIo7tL0DsJTur9rZqi:b-pxrmtv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @yuzefovich)

___
*[`pkg/sql/explain_test.go` line 532 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95136#-NNEfESD74-SwBNXAmdz:-NNInGoE8WPmJnvJPRBf:b-bs54qk) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bc1d1ea2a11e8ce738cf87c006fae9dfdff45aa/pkg/sql/explain_test.go#L532)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: it might be cleaner to just add the commas explicitly in the `explain := ` assignment in the loop below.
</blockquote></details>

Good point. Doing that inspired me to make subtests of the form `TestExplainRedact/ExplainAnalyze/Plan/Verbose` for `EXPLAIN ANALYZE (PLAN, VERBOSE, REDACT)`.

**Comment by michae2** [comment]
Hmm, looks like I need to add a statement timeout. Hold off on reviewing for a bit, sorry!

**Comment by michae2** [comment]
Alright, at long last this is RFAL.

**Comment by michae2** [comment]
@RaduBerinde would you be willing to take one more look at this? The randomized test (great idea!) found a few things, which I have addressed. (Thank you!)

**Review by yuzefovich — APPROVED** [review]
Nice work! :lgtm: 

> Reviewed 1 of 13 files at r7, 17 of 17 files at r10, 7 of 7 files at r11, 5 of 5 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95136#-:-NOGwf-u8KWkyfTopboh:bnahwna)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier and @michae2)

___
*[`pkg/sql/sem/tree/expr.go` line 934 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/95136#-NOGvTXI4SFMEcnyOWjO:-NOGvTXI4SFMEcnyOWjP:b-1691g8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a87672f53690d7052ebf45a9a550804e060108d1/pkg/sql/sem/tree/expr.go#L934)):*
> ```Go
> 
> // Format implements the NodeFormatter interface.
> func (node *TypedExprs) Format(ctx *FmtCtx) {
> ```

nit: perhaps add a type assertion for the `NodeFormatter` interface.
___
*[`pkg/sql/opt/exec/explain/testdata/gists_tpce` line 223 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/95136#-NOGwAfmA44GrvjI0Y3b:-NOGwAfmA44GrvjI0Y3c:bf7cmmm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a87672f53690d7052ebf45a9a550804e060108d1/pkg/sql/opt/exec/explain/testdata/gists_tpce#L223)):*
> ```
> ├── • subquery
> │   │ id: @S1
> │   │ original sql: UPDATE last_trade SET lt_vol = lt_vol + _, lt_price = _::DECIMAL, lt_dts = '_'::TIMESTAMP WHERE lt_s_symb = '_' RETURNING _
> ```

Just to make sure I understand this: the gist (i.e. the encoded representation) didn't change - we only changed how we format the decoded representation, right?

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95136#-:-NOGxBx7DCDTM-j79A-n:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @abarganier and @michae2)

___
*[`pkg/sql/explain_test.go` line 577 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/95136#-NOGww4Q952LohD6M1WB:-NOGww4Q952LohD6M1WC:bf1llja) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7b80d3bfc7ecc2244dc080004b1ba532dd6625e/pkg/sql/explain_test.go#L577)):*
> ```Go
> 								if err != nil {
> 									// Errors are fine. (E.g. EXPLAIN (OPT, JSON) is always an error.)
> 									continue
> ```

[nit] Maybe check the error message for the invalid combo error, so we don't ignore other errors

**Review by michae2 — COMMENTED** [review]
TFYRs! The failure looks like an unrelated flake.

bors r=RaduBerinde,yuzefovich

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95136#-:-NO_Xf1R0HT10dF4fviP:bomrtlk)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @abarganier, @RaduBerinde, and @yuzefovich)

___
*[`pkg/sql/sem/tree/expr.go` line 934 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/95136#-NOGvTXI4SFMEcnyOWjO:-NO_Cn1m2HoywEGND9J8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a87672f53690d7052ebf45a9a550804e060108d1/pkg/sql/sem/tree/expr.go#L934)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: perhaps add a type assertion for the `NodeFormatter` interface.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/exec/explain/testdata/gists_tpce` line 223 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/95136#-NOGwAfmA44GrvjI0Y3b:-NO_F9GUELMBOUVK1TUP:b-f5j328) ([raw file](https://github.com/cockroachdb/cockroach/blob/a87672f53690d7052ebf45a9a550804e060108d1/pkg/sql/opt/exec/explain/testdata/gists_tpce#L223)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Just to make sure I understand this: the gist (i.e. the encoded representation) didn't change - we only changed how we format the decoded representation, right?
</blockquote></details>

That's correct, the gist didn't change. Only the output of `EXPLAIN (SHAPE)` changed.
___
*[`pkg/sql/explain_test.go` line 577 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/95136#-NOGww4Q952LohD6M1WB:-NO_EEj58wJ3T6CqyzG-:bak5e12) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7b80d3bfc7ecc2244dc080004b1ba532dd6625e/pkg/sql/explain_test.go#L577)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Maybe check the error message for the invalid combo error, so we don't ignore other errors
</blockquote></details>

I tried only allowing certain errors (syntax error, unimplemented error, timeout error, etc), but the list grew pretty long and I was still getting false positive failures from errors emitted by `EXPLAIN ANALYZE` (the random queries aren't guaranteed to execute without error). So for now I've changed it to only fail the test on internal errors, which is also what we do in [costfuzz](https://github.com/cockroachdb/cockroach/blob/cc58f15bad0511d3205eae0d659e130e8c861657/pkg/cmd/roachtest/tests/costfuzz.go#L89-L107) and [unoptimized-query-oracle](https://github.com/cockroachdb/cockroach/blob/cc58f15bad0511d3205eae0d659e130e8c861657/pkg/cmd/roachtest/tests/unoptimized_query_oracle.go#L157-L175).

**Pull request merged**
