### PR TITLE
roachtest: port import/mixed-versions to the new framework

### LINKED ISSUE #110529: roachtest: port import/mixed-versions to new mixed-version framework
See the parent issue [1] for details.

[1] https://github.com/cockroachdb/cockroach/issues/110528

Jira issue: CRDB-31479

### PR DESCRIPTION
**Pull request by yuzefovich**
Fixes: #110529.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Got a successful run from the gceworker, so it's RFAL.

**Review by DrewKimball — APPROVED** [review]
:lgtm: That was fast!

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113546#-:-NiAu_Ua4auC852UREZE:b-8hsrdo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @renatolabs)

**Review by renatolabs — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113546)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/cmd/roachtest/tests/mixed_version_import.go` line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113546#-NiAyS5TD6tM_tskF1wH:-NiAyS5TD6tM_tskF1wI:b-xbqfde) ([raw file](https://github.com/cockroachdb/cockroach/blob/df122604f590a88dae75325e96eaffd842baae27/pkg/cmd/roachtest/tests/mixed_version_import.go#L44)):*
> ```Go
> func runImportMixedVersions(ctx context.Context, t test.Test, c cluster.Cluster, warehouses int) {
> 	crdbNodes := c.All()
> 	c.Put(ctx, t.Cockroach(), "./cockroach", crdbNodes)
> ```

You can skip this step and use `tpccImportCmdWithCockroachBinary(test.DefaultCockroachPath)` down below to avoid uploading a new binary to the cluster.
___
*[`pkg/cmd/roachtest/tests/mixed_version_import.go` line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113546#-NiAyeof-s_JmyVBW0e1:-NiAyeof-s_JmyVBW0e2:b-oya0ap) ([raw file](https://github.com/cockroachdb/cockroach/blob/df122604f590a88dae75325e96eaffd842baae27/pkg/cmd/roachtest/tests/mixed_version_import.go#L48)):*
> ```Go
> 	// NB: We rely on the testing framework to choose a random predecessor to
> 	// upgrade from.
> 	mvt := mixedversion.NewTest(ctx, t, t.L(), c, crdbNodes, mixedversion.AlwaysUseFixtures)
> ```

Is there a specific reason to always use fixtures? The test doesn't seem to rely on them.
___
*[`pkg/cmd/roachtest/tests/mixed_version_import.go` line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113546#-NiAynXuA-8eGtsEg2QK:-NiAynXuA-8eGtsEg2QL:bngx870) ([raw file](https://github.com/cockroachdb/cockroach/blob/df122604f590a88dae75325e96eaffd842baae27/pkg/cmd/roachtest/tests/mixed_version_import.go#L52)):*
> ```Go
> 		node := h.RandomNode(r, crdbNodes)
> 		l.Printf("dropping tpcc db if exists on node %d", node)
> 		_, err := h.Connect(node).ExecContext(ctx, "DROP DATABASE IF EXISTS tpcc CASCADE;")
> ```

We can replace the `RandomNode` and log call with `h.Exec()`.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113546)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/mixed_version_import.go` line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113546#-NiAyS5TD6tM_tskF1wH:-NiBCBEg8_F7fK2HBuiQ:b-zcxu07) ([raw file](https://github.com/cockroachdb/cockroach/blob/df122604f590a88dae75325e96eaffd842baae27/pkg/cmd/roachtest/tests/mixed_version_import.go#L44)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

You can skip this step and use `tpccImportCmdWithCockroachBinary(test.DefaultCockroachPath)` down below to avoid uploading a new binary to the cluster.
</blockquote></details>

Nice, thanks, done.
___
*[`pkg/cmd/roachtest/tests/mixed_version_import.go` line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113546#-NiAyeof-s_JmyVBW0e1:-NiBCn8N0Rr_XzVPHsm1:b9f0tgt) ([raw file](https://github.com/cockroachdb/cockroach/blob/df122604f590a88dae75325e96eaffd842baae27/pkg/cmd/roachtest/tests/mixed_version_import.go#L48)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Is there a specific reason to always use fixtures? The test doesn't seem to rely on them.
</blockquote></details>

The original test used fixtures, so I kept that. I also don't see the reason for using them, removed.
___
*[`pkg/cmd/roachtest/tests/mixed_version_import.go` line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113546#-NiAynXuA-8eGtsEg2QK:-NiBCfPj8akEfA4XJlC-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/df122604f590a88dae75325e96eaffd842baae27/pkg/cmd/roachtest/tests/mixed_version_import.go#L52)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

We can replace the `RandomNode` and log call with `h.Exec()`.
</blockquote></details>

Done.

**Review by renatolabs — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113546#-:-NiBKvz--T-UZxWEYrcD:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @yuzefovich)

___
*[`pkg/cmd/roachtest/tests/mixed_version_import.go` line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113546#-NiAyeof-s_JmyVBW0e1:-NiBKVGD2GL2yeHjyniE:bjtfc7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/df122604f590a88dae75325e96eaffd842baae27/pkg/cmd/roachtest/tests/mixed_version_import.go#L48)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

The original test used fixtures, so I kept that. I also don't see the reason for using them, removed.
</blockquote></details>

Yeah, nothing wrong with using them; by default the test will now probabilistically run with them, which makes more sense for tests that don't explicitly rely on the contents of the fixtures.

**Comment by yuzefovich** [comment]
Got a passing run on the gceworker with latest push too.

TFTRs!

bors r+

**Comment by yuzefovich** [comment]
blathers backport 23.1

**Pull request merged**
