### PR TITLE
sql : Implement pg_catalog.pg_index

### LINKED ISSUE #10416: sql: Implement pg_catalog.pg_index as a virtual table
See https://www.postgresql.org/docs/9.6/static/catalog-pg-index.html.

This is needed for Hibernate.

### PR DESCRIPTION
**Pull request by a6802739**
Fixes #10416.

cc @nvanbenschoten @cuongdo .

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10592)

### CODE REVIEW

**Comment by cuongdo** [comment]
Thanks for taking this on! I've given this an initial review.

@nvanbenschoten could you add your thoughts?

---

Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/pg_catalog.go, line 66 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592#-KWDY_int82WDD3QrQyI:-KWDY_int82WDD3QrQyJ:bjyoxl5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c8c10a943c69fb434f8d6cfc8dafbff117767c7/pkg/sql/pg_catalog.go#L66)):*
> ```Go
> 		pgCatalogRolesTable,
> 		pgCatalogSettingsTable,
> 		pgCatalogIndexTable,
> ```

could you alphabetize this (put it just above `pgCatalogIndexesTable`)?

---

*[pkg/sql/pg_catalog.go, line 632 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592#-KWDYuVTPYv8EKAquNC3:-KWDYuVTPYv8EKAquNC4:b79pxv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c8c10a943c69fb434f8d6cfc8dafbff117767c7/pkg/sql/pg_catalog.go#L632)):*
> ```Go
>     indislive BOOL,
>     indisreplident BOOL,
>     indkey INT,
> ```

For now, this should be `STRING`, until #10584 merges. The Postgres definition is `int2vector`, which we don't yet support. So, we mock that out using a `STRING` for now.

---

*[pkg/sql/pg_catalog.go, line 646 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592#-KWDZnDSSN5YoGc4zDpE:-KWDZnDSSN5YoGc4zDpF:b-tb1upd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c8c10a943c69fb434f8d6cfc8dafbff117767c7/pkg/sql/pg_catalog.go#L646)):*
> ```Go
> 				tableOid := h.TableOid(db, table)
> 				return forEachIndexInTable(table, func(index *sqlbase.IndexDescriptor) error {
> 					isValid, isReady := true, true
> ```

For consistency with our other code, please change these to:
```
var isValid bool
var isReady bool
```

Then, you can set `isValid` / `isReady` to `true` where it makes sense below.

---

*[pkg/sql/pg_catalog.go, line 647 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592#-KWD_9IMJdv6KkFSDfBp:-KWD_9IMJdv6KkFSDfBq:b-fmv5wj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c8c10a943c69fb434f8d6cfc8dafbff117767c7/pkg/sql/pg_catalog.go#L647)):*
> ```Go
> 				return forEachIndexInTable(table, func(index *sqlbase.IndexDescriptor) error {
> 					isValid, isReady := true, true
> 					for _, mutation := range table.Mutations {
> ```

I'm glad you thought of the effect of schema changes.

cc @vivekmenezes to get his eyes on this code

---

*[pkg/sql/pg_catalog.go, line 671 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592#-KWDaTu9i19dQEfK1i6T:-KWDaTu9i19dQEfK1i6U:bw2ee5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c8c10a943c69fb434f8d6cfc8dafbff117767c7/pkg/sql/pg_catalog.go#L671)):*
> ```Go
> 						parser.MakeDBool(false),                       // indcheckxmin
> 						parser.MakeDBool(parser.DBool(isReady)),       // indisready
> 						parser.MakeDBool(false),                       // indislive
> ```

this should be `true` unless the index is being dropped right now

---

*[pkg/sql/pg_catalog.go, line 673 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592#-KWDb5plzCu39vrZKuGb:-KWDb5plzCu39vrZKuGc:bku5vvt) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c8c10a943c69fb434f8d6cfc8dafbff117767c7/pkg/sql/pg_catalog.go#L673)):*
> ```Go
> 						parser.MakeDBool(false),                       // indislive
> 						parser.MakeDBool(false),                       // indisreplident
> 						zeroVal,                                       // indkey
> ```

This should populate `indkey` with the columns that are part of this index. For an example of how to do this, see:

https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/pg_catalog.go#L430

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592#-:-KWDbklg2HkJx4EMkdKH:bi2ufnr)*

**Comment by a6802739** [comment]
@cuongdo, Thanks for your review.

**Comment by a6802739** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/sql/pg_catalog.go, line 66 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592#-KWDY_int82WDD3QrQyI:-KWGNMytJb9sRhA-hkFf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c8c10a943c69fb434f8d6cfc8dafbff117767c7/pkg/sql/pg_catalog.go#L66)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> could you alphabetize this (put it just above `pgCatalogIndexesTable`)?
</details>
Done.

---

*[pkg/sql/pg_catalog.go, line 632 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592#-KWDYuVTPYv8EKAquNC3:-KWGNNzAxGHbd75qFM5Q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c8c10a943c69fb434f8d6cfc8dafbff117767c7/pkg/sql/pg_catalog.go#L632)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> For now, this should be `STRING`, until #10584 merges. The Postgres definition is `int2vector`, which we don't yet support. So, we mock that out using a `STRING` for now.
</details>
Done.

---

*[pkg/sql/pg_catalog.go, line 646 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592#-KWDZnDSSN5YoGc4zDpE:-KWGNPUuFA-0bH0HlmLq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c8c10a943c69fb434f8d6cfc8dafbff117767c7/pkg/sql/pg_catalog.go#L646)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> For consistency with our other code, please change these to:
> ```
> var isValid bool
> var isReady bool
> ```
> 
> Then, you can set `isValid` / `isReady` to `true` where it makes sense below.
</details>
Done.

---

*[pkg/sql/pg_catalog.go, line 647 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592#-KWD_9IMJdv6KkFSDfBp:-KWGN_mRPO3qPAhMXWlk:bcki9rq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c8c10a943c69fb434f8d6cfc8dafbff117767c7/pkg/sql/pg_catalog.go#L647)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> I'm glad you thought of the effect of schema changes.
> 
> cc @vivekmenezes to get his eyes on this code
</details>
thanks, I think I have made a mistake before, I have changed the it now.

---

*[pkg/sql/pg_catalog.go, line 671 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592#-KWDaTu9i19dQEfK1i6T:-KWGNU-d0bYdF9ycCqdD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c8c10a943c69fb434f8d6cfc8dafbff117767c7/pkg/sql/pg_catalog.go#L671)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> this should be `true` unless the index is being dropped right now
</details>
Done.

---

*[pkg/sql/pg_catalog.go, line 673 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592#-KWDb5plzCu39vrZKuGb:-KWGNVLljBA1tn2F2wLk:bovgj5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c8c10a943c69fb434f8d6cfc8dafbff117767c7/pkg/sql/pg_catalog.go#L673)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> This should populate `indkey` with the columns that are part of this index. For an example of how to do this, see:
> 
> https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/pg_catalog.go#L430
> 
</details>
Thanks for your reference.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 3 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/sql/pg_catalog.go, line 646 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592#-KWDZnDSSN5YoGc4zDpE:-KWMKwt-xY3UErytPqH1:ba86dvm) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c8c10a943c69fb434f8d6cfc8dafbff117767c7/pkg/sql/pg_catalog.go#L646)):*
<details><summary><i>Previously, a6802739 (songhao) wrote…</i></summary>
> Done.
</details>
I don't know, this looks really weird. I'd do:

```
isValid := true
isReady := false
```

---

*[pkg/sql/pg_catalog.go, line 615 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592#-KWMKE9ZnB-2j_vyL9Zq:-KWMKE9_KEkO8A2Ooxck:b-m914pt) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb84c52f3c327fce1a023b4844a581a032e007cf/pkg/sql/pg_catalog.go#L615)):*
> ```Go
> }
> 
> // See: https://www.postgresql.org/docs/9.6/static/catalog-pg-index.html.
> ```

Let's move this above `pgCatalogIndexesTable` to maintain the correct ordering. 

---

*[pkg/sql/pg_catalog.go, line 667 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592#-KWMLvjSXzZBJpreargu:-KWMLvjSXzZBJpreargv:b-3djnet) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb84c52f3c327fce1a023b4844a581a032e007cf/pkg/sql/pg_catalog.go#L667)):*
> ```Go
> 						parser.MakeDBool(parser.DBool(table.IsPhysicalTable() && index.ID == table.PrimaryIndex.ID)), // indisprimary
> 						parser.MakeDBool(false),                       // indisexclusion
> 						parser.MakeDBool(parser.DBool(!index.Unique)), // indimmediate
> ```

Shouldn't this be the same as `indisunique`? The uniqueness check is enforced immediately on insertion for unique indexes

---

*[pkg/sql/testdata/pg_catalog, line 409 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592#-KWMMM4CbNLYGoekqa2c:-KWMMM4D6JNciI9wF7SP:btq6sto) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb84c52f3c327fce1a023b4844a581a032e007cf/pkg/sql/testdata/pg_catalog#L409)):*
> ```
> SELECT indexrelid, indimmediate, indisclustered, indisvalid, indcheckxmin, indisready
> from pg_catalog.pg_index
> WHERE indnatts = 2
> ```

Why do we switch conditions midway through the columns? I'd like to be able to see all of the columns for at least one of the index in these tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592)*

**Comment by a6802739** [comment]
Review status: 0 of 3 files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

*[pkg/sql/pg_catalog.go, line 646 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592#-KWDZnDSSN5YoGc4zDpE:-KWSDy47Mpye33JA-s8f:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c8c10a943c69fb434f8d6cfc8dafbff117767c7/pkg/sql/pg_catalog.go#L646)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> I don't know, this looks really weird. I'd do:
> 
> ```
> isValid := true
> isReady := false
> ```
</details>
Done.

---

*[pkg/sql/pg_catalog.go, line 615 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592#-KWMKE9ZnB-2j_vyL9Zq:-KWSDwUXeXBonwumQQsW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb84c52f3c327fce1a023b4844a581a032e007cf/pkg/sql/pg_catalog.go#L615)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Let's move this above `pgCatalogIndexesTable` to maintain the correct ordering. 
</details>
Done.

---

*[pkg/sql/pg_catalog.go, line 667 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592#-KWMLvjSXzZBJpreargu:-KWSDzDSZYW3gJ9Wi4hA:b-qq4dxb) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb84c52f3c327fce1a023b4844a581a032e007cf/pkg/sql/pg_catalog.go#L667)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Shouldn't this be the same as `indisunique`? The uniqueness check is enforced immediately on insertion for unique indexes
</details>
my mistake.Done

---

*[pkg/sql/testdata/pg_catalog, line 409 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592#-KWMMM4CbNLYGoekqa2c:-KWSE1cEpUtSeQ0VCJkN:b-o7ptyz) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb84c52f3c327fce1a023b4844a581a032e007cf/pkg/sql/testdata/pg_catalog#L409)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Why do we switch conditions midway through the columns? I'd like to be able to see all of the columns for at least one of the index in these tests.
</details>
hmm, what do you mean here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 3 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/testdata/pg_catalog, line 409 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592#-KWMMM4CbNLYGoekqa2c:-KWWL1yPkb87yToGmuN8:b-y3k59o) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb84c52f3c327fce1a023b4844a581a032e007cf/pkg/sql/testdata/pg_catalog#L409)):*
<details><summary><i>Previously, a6802739 (songhao) wrote…</i></summary>
> hmm, what do you mean here?
</details>
The first half of the columns are queries with `indnatts = 1` and the second half are queries with `indnatts = 2`. This means that there is not a single index that has all of its columns shown here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592)*

**Comment by a6802739** [comment]
Review status: 0 of 3 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/testdata/pg_catalog, line 409 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592#-KWMMM4CbNLYGoekqa2c:-KWXaqZq3hXSQFkbjBT-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb84c52f3c327fce1a023b4844a581a032e007cf/pkg/sql/testdata/pg_catalog#L409)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> The first half of the columns are queries with `indnatts = 1` and the second half are queries with `indnatts = 2`. This means that there is not a single index that has all of its columns shown here.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 3 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/testdata/pg_catalog, line 409 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592#-KWMMM4CbNLYGoekqa2c:-KWYux4tp32G6l24u51K:b-vw27zh) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb84c52f3c327fce1a023b4844a581a032e007cf/pkg/sql/testdata/pg_catalog#L409)):*
<details><summary><i>Previously, a6802739 (songhao) wrote…</i></summary>
> Done.
</details>
I'm confused, now we're querying 3 disjoint sets of indexes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592)*

**Comment by a6802739** [comment]
Review status: 0 of 3 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/testdata/pg_catalog, line 409 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592#-KWMMM4CbNLYGoekqa2c:-KW_v6HL6y0B3fvUalBA:bfx5ewe) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb84c52f3c327fce1a023b4844a581a032e007cf/pkg/sql/testdata/pg_catalog#L409)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> I'm confused, now we're querying 3 disjoint sets of indexes?
</details>
hmm, sorry, I couldn't quite understand what you say?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10592)*

**Comment by nvanbenschoten** [comment]
Why are all the WHERE clauses different?

**Comment by a6802739** [comment]
@nathanejohnson, I just want to split all the columns into more little columns.

**Comment by nvanbenschoten** [comment]
We need to have the exact same WHERE clause for all of the column. If you want to add other queries with different conditions as well, that's fine.

**Comment by a6802739** [comment]
@nvanbenschoten, yeah, I have changed it now.

**Comment by nvanbenschoten** [comment]
LGTM, thanks for all the work here @a6802739!

**Pull request merged**
