### PR TITLE
kvserver/rangefeed: use StreamManager for unbuffered sender

### PR DESCRIPTION
**Pull request by wenyihu6**
Previously, UnbufferedSender was responsible for  forwarding events to the gRPC
stream and managing the stream itself. This patch refactors UnbufferedSender to
separate these responsibilities by adopting the `rangefeed.sender` and
`rangefeed.StreamManager` interfaces. Now, `rangefeed.UnbufferedSender` is dedicated
to sending messages, while rangefeed.StreamManager manages the stream.

Additionally, this patch changes rangefeed disconnection handling at the node
level. Instead of disconnecting individual streams by canceling their contexts,
`node.MuxRangefeed` now uses the `Disconnector` provided by `p.Register` to
manage rangefeed disconnections. Although the benefits may not be immediately
clear, future commits on unbuffered registration - which lack a long lived
goroutine - will rely on this disconnector. This commit allows us to draw more
parallels between the two types of registrations.

Part of: https://github.com/cockroachdb/cockroach/issues/110432
Release note: none

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
I know this is a draft, decided to give it a look anyway. Looks like it's shaping up nicely!

> Reviewed 4 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134959#-:-OBk22j2Am7pC2_avOKV:bb6nlix)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`pkg/kv/kvserver/rangefeed/unbuffered_sender.go` line 113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/134959#-OBk0tTQ5HMH31kum1E1:-OBk0tTQ5HMH31kum1E2:b-t9vjsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b47c6647985ad2e865dfb41e87088e788c8a89ce/pkg/kv/kvserver/rangefeed/unbuffered_sender.go#L113)):*
> ```Go
> }
> 
> // sendBuffered 1. Sends a mux rangefeed completion error to the client without
> ```

I really stumbled over this method named `sendBuffered` whose only job (apparently) is to send an error in the original PR too. Is this going to resolve at some point? It's not the unbuffered sender's business to decide in which circumstances this method gets called and with what, no? Is the comment maybe just out of place and it and the associated assertions should be removed or moved to a higher level?
___
*[`pkg/kv/kvserver/rangefeed/unbuffered_sender.go` line 166 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/134959#-OBk1LZz-cPKHKld84N_:-OBk1LZz-cPKHKld84Na:b-8dkevn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b47c6647985ad2e865dfb41e87088e788c8a89ce/pkg/kv/kvserver/rangefeed/unbuffered_sender.go#L166)):*
> ```Go
> 				onError(clientErr.StreamID)
> 				if err := ubs.sender.Send(clientErr); err != nil {
> 					log.Errorf(ctx,
> ```

ditto log level
___
*[`pkg/kv/kvserver/rangefeed/stream.go` line 87 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/134959#-OBk03dU0GTPjsgbnBVJ:-OBk03dU0GTPjsgbnBVK:b1s2k31) ([raw file](https://github.com/cockroachdb/cockroach/blob/b47c6647985ad2e865dfb41e87088e788c8a89ce/pkg/kv/kvserver/rangefeed/stream.go#L87)):*
> ```Go
> 	})
> 	if err := s.wrapped.sendBuffered(ev, nil); err != nil {
> 		log.Errorf(context.Background(),
> ```

is this worth error-level logging? If the client disconnects, why expect that this should work?

**Review by tbg — COMMENTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134959)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @wenyihu6)

**Review by wenyihu6 — COMMENTED** [review]
> Reviewed 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134959)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[`pkg/kv/kvserver/rangefeed/stream.go` line 87 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/134959#-OBk03dU0GTPjsgbnBVJ:-OByAIVM1T_cule-Of1p:bfuucfx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b47c6647985ad2e865dfb41e87088e788c8a89ce/pkg/kv/kvserver/rangefeed/stream.go#L87)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

is this worth error-level logging? If the client disconnects, why expect that this should work?
</blockquote></details>

Changed it to `log.Infof`.
___
*[`pkg/kv/kvserver/rangefeed/unbuffered_sender.go` line 113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/134959#-OBk0tTQ5HMH31kum1E1:-OByAPHZACNbhVRs7Sge:bvlsko5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b47c6647985ad2e865dfb41e87088e788c8a89ce/pkg/kv/kvserver/rangefeed/unbuffered_sender.go#L113)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I really stumbled over this method named `sendBuffered` whose only job (apparently) is to send an error in the original PR too. Is this going to resolve at some point? It's not the unbuffered sender's business to decide in which circumstances this method gets called and with what, no? Is the comment maybe just out of place and it and the associated assertions should be removed or moved to a higher level?
</blockquote></details>

Good point about that the responsibilities here being unclear. I've moved the assertion one level up to `PerRangeEventSink.SendError` and allow `unbufferedSender.sendBuffered` to be called with any types of events. Does this align with what you had in mind? 

While making this change, I noticed the distinction between unbuffered and buffered sender is minor - one only buffers error events using a slice while the other uses an event queue chunks for all events. A potential follow-up could be to consolidate them into a single sender that can handle both cases. Perhaps this is also what Steven had in mind here https://github.com/cockroachdb/cockroach/pull/134957#pullrequestreview-2435912852. 
___
*[`pkg/kv/kvserver/rangefeed/unbuffered_sender.go` line 166 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/134959#-OBk1LZz-cPKHKld84N_:-OByCX9q8RRsJsauhDWm:b-n7qets) ([raw file](https://github.com/cockroachdb/cockroach/blob/b47c6647985ad2e865dfb41e87088e788c8a89ce/pkg/kv/kvserver/rangefeed/unbuffered_sender.go#L166)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

ditto log level
</blockquote></details>

Changed to `log.Infof`.

**Review by tbg — APPROVED** [review]
> Reviewed 4 of 7 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134959)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[`pkg/kv/kvserver/rangefeed/unbuffered_sender.go` line 113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/134959#-OBk0tTQ5HMH31kum1E1:-OC8XSSX4wOgxmWnCwJ1:brxp9sd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b47c6647985ad2e865dfb41e87088e788c8a89ce/pkg/kv/kvserver/rangefeed/unbuffered_sender.go#L113)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

Good point about that the responsibilities here being unclear. I've moved the assertion one level up to `PerRangeEventSink.SendError` and allow `unbufferedSender.sendBuffered` to be called with any types of events. Does this align with what you had in mind? 

While making this change, I noticed the distinction between unbuffered and buffered sender is minor - one only buffers error events using a slice while the other uses an event queue chunks for all events. A potential follow-up could be to consolidate them into a single sender that can handle both cases. Perhaps this is also what Steven had in mind here https://github.com/cockroachdb/cockroach/pull/134957#pullrequestreview-2435912852.
</blockquote></details>

Sounds good!

**Comment by wenyihu6** [comment]
TFTR!

bors r=tbg

**Comment by wenyihu6** [comment]
bors retry

**Pull request merged**
