### PR TITLE
sql: change %f to microseconds for experimental_str{f,p}time

### LINKED ISSUE #45881: sql: strftime nano and microseconds notation
Minor issue.  For %f notation of strftime using experimental_strftime(), we output nano seconds instead of microseconds which doesn't match python documentation here: https://strftime.org/

```
root@:26257/defaultdb> select experimental_strftime(now(), '%Y-%m-%d %I:%M:%S.%f');
      experimental_strftime
+-------------------------------+
  2020-03-09 01:29:15.580861000
```

I think it's good that we output more rather than less.  A nice to have would be to follow python document and use %f to output microseconds and use a different notation for nano, although python doesn't support nano seconds.  Current workaround is to use 

`select left(experimental_strftime(now(), '%Y-%m-%d %I:%M:%S.%f'),-3);`

which is bit wonky.

### PR DESCRIPTION
**Pull request by otan**
Resolves https://github.com/cockroachdb/cockroach/issues/45881

Release justification: low risk, high benefit changes to existing
functionality (open to waiting until 20.2)

Release note (bug fix, sql change): Previously, experimental_strftime
and experimental_strptime used the non-POSIX standard %f for nanosecond
display. However, as cockroach only supports up to microsecond precision
and python's strftime has %f to microsecond, we have similarly switched
%f to use microsecond instead of nanosecond precision.

### CODE REVIEW

**Comment by knz** [comment]
i think you haven't committed the vendor change properly

**Comment by otan** [comment]
> i think you haven't committed the vendor change properly

yeah and once i committed it i couldn't add it again :\ submodules are weird

**Review by knz — APPROVED** [review]

**Comment by otan** [comment]
bors r=knz

**Comment by otan** [comment]
bors r=knz

**Comment by otan** [comment]
bors r-

merge conflict grumble

**Comment by otan** [comment]
bors r=knz

**Pull request merged**
