### PR TITLE
util/log: various simplifications towards logging channels

### PR DESCRIPTION
**Pull request by knz**
These are general enhancements that I extracted from my work on #51987 into piecemeal commits. I think they are worth merging regardless of whether we adopt the channel proposal.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
:lgtm: 

The bash-based codegen made my toenails curl up a bit, but I suppose it does leave things in a better place than where they started.

> Reviewed 7 of 7 files at r1, 14 of 14 files at r2, 15 of 15 files at r3, 7 of 7 files at r4, 7 of 7 files at r5, 1 of 1 files at r6, 70 of 70 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56336#-:-MLlLTPDB7OJa7uRhHNh:b9ivjlf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bdarnell and @knz)

___
*[pkg/util/log/flags.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56336#-MLlHrsb4a5j10LES2dd:-MLlHrsb4a5j10LES2de:b-8tk6hd) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7ca909d47d85b489f300b1cfc3ce179976cff95/pkg/util/log/flags.go#L32)):*
> ```Go
> 	showLogs bool
> 
> 	// Level beyond which entries submitted to any logger are written
> ```

at or beyond? I.e. if this is ERROR then ERROR does get written.
___
*[pkg/util/log/log_flush.go, line 36 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56336#-MLlJ5BH-TOW_Go-ZGoD:-MLlJ5BH-TOW_Go-ZGoE:b-3xt60o) ([raw file](https://github.com/cockroachdb/cockroach/blob/34efa953d18de4ed639918e8c3c40df5e20eee36/pkg/util/log/log_flush.go#L36)):*
> ```Go
> 	debugLog.lockAndFlushAndSync(true /*doSync*/)
> 	_ = registry.iter(func(l *loggerT) error {
> 		// Some loggers (e.g. the audit log) want to keep all the files.
> ```

Old code, but I don't understand this comment. Is this explaining why we `doSync`?
___
*[pkg/util/log/secondary_log.go, line 22 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56336#-MLlIYqhDEURpsM2OtpE:-MLlIYqhDEURpsM2OtpF:bpfugzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7ca909d47d85b489f300b1cfc3ce179976cff95/pkg/util/log/secondary_log.go#L22)):*
> ```Go
> // whose logging events go to a different file than the main logging
> // facility.
> type SecondaryLogger struct {
> ```

At this point, is there even a true distinction between `loggerT` and `SecondaryLogger`? Does it have extra methods or something?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56336)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bdarnell and @tbg)

___
*[pkg/util/log/flags.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56336#-MLlHrsb4a5j10LES2dd:-MM0LZl_BtIkfyMdXoHv:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7ca909d47d85b489f300b1cfc3ce179976cff95/pkg/util/log/flags.go#L32)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

at or beyond? I.e. if this is ERROR then ERROR does get written.
</blockquote></details>

Fixed.
___
*[pkg/util/log/log_flush.go, line 36 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56336#-MLlJ5BH-TOW_Go-ZGoD:-MM0LpdU4AFqY9qXwYT5:bfi3c1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/34efa953d18de4ed639918e8c3c40df5e20eee36/pkg/util/log/log_flush.go#L36)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Old code, but I don't understand this comment. Is this explaining why we `doSync`?
</blockquote></details>

Yeah this comment doesn't mean anything. Removed.
___
*[pkg/util/log/secondary_log.go, line 22 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56336#-MLlIYqhDEURpsM2OtpE:-MM0Lz6P57Zbz-zFqcgz:bzdpzs4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7ca909d47d85b489f300b1cfc3ce179976cff95/pkg/util/log/secondary_log.go#L22)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

At this point, is there even a true distinction between `loggerT` and `SecondaryLogger`? Does it have extra methods or something?
</blockquote></details>

 yes it does. This is further simplified in  #51987.

**Comment by knz** [comment]
todo: check whether this addresses  #55423

**Review by itsbilal — APPROVED** [review]
:lgtm: great work! Just some minor comments, then this is good to go.

> Reviewed 79 of 79 files at r8, 7 of 7 files at r9, 14 of 14 files at r10, 15 of 15 files at r11, 7 of 7 files at r12, 7 of 7 files at r13, 1 of 1 files at r14, 70 of 70 files at r15, 19 of 19 files at r16, 3 of 3 files at r17, 10 of 10 files at r18, 11 of 11 files at r19, 7 of 7 files at r20, 18 of 18 files at r21, 11 of 11 files at r22, 7 of 7 files at r23.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56336#-:-MMRPVOnA60G9XpEWeuT:b4x08ga)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @bdarnell, @knz, and @tbg)

___
*[pkg/util/log/exit_override.go, line 95 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/56336#-MMRP0muA8em_ectoGgC:-MMRP0muA8em_ectoGgD:b-iewtgm) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f29a691a9987bcbb9d8223c0ece37f3900bcfff/pkg/util/log/exit_override.go#L95)):*
> ```Go
> 
> 	for _, s := range l.sinks {
> 		if s.activeAtSeverity(logpb.Severity_NONE) {
> ```

Wrong severity type?
___
*[pkg/util/log/file.go, line 206 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/56336#-MMRDass6B6HAGS8lrk8:-MMRDass6B6HAGS8lrk9:b-heymr5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea8a47c58b78065e35111573269506828e872fa/pkg/util/log/file.go#L206)):*
> ```Go
> 
> 	// If we can't sync within this duration, exit the process.
> 	t := time.AfterFunc(maxSyncDuration, func() {
> ```

Might be slightly faster if these two timers only stepped in when doSync == true. But I'll let you make the call if the lack of disk slowness checking when doSync == false would be a bad idea.
___
*[pkg/util/log/registry.go, line 45 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/56336#-MMR7xTzCXNCvh_BIWk-:-MMR7xTzCXNCvh_BIWk0:b-qo922l) ([raw file](https://github.com/cockroachdb/cockroach/blob/d282882ac1654d896f4d8321be9757d222d7d62d/pkg/util/log/registry.go#L45)):*
> ```Go
> 
> // iterLocked is like iter but it also locks each logger visited.
> func (r *loggerRegistry) iterLocked(fn func(l *loggerT) error) error {
> ```

`iterLocked` seems to imply the locks are held / need to be held already. Maybe `lockAndIter` ?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56336)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @bdarnell, @itsbilal, and @tbg)

___
*[pkg/util/log/exit_override.go, line 95 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/56336#-MMRP0muA8em_ectoGgC:-MMUs9fM77R6rYvyEKjQ:b-4xc07r) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f29a691a9987bcbb9d8223c0ece37f3900bcfff/pkg/util/log/exit_override.go#L95)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Wrong severity type?
</blockquote></details>

Good catch. fixed.
___
*[pkg/util/log/file.go, line 206 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/56336#-MMRDass6B6HAGS8lrk8:-MMUsAkg1Lo4gmqh4x23:bbvt6be) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea8a47c58b78065e35111573269506828e872fa/pkg/util/log/file.go#L206)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Might be slightly faster if these two timers only stepped in when doSync == true. But I'll let you make the call if the lack of disk slowness checking when doSync == false would be a bad idea.
</blockquote></details>

Actually, I think you just helped identify a bug. Filed as #56893. Will fix in a later PR.
___
*[pkg/util/log/registry.go, line 45 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/56336#-MMR7xTzCXNCvh_BIWk-:-MMUnf585qNQ85pGLsog:bc0tsjy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d282882ac1654d896f4d8321be9757d222d7d62d/pkg/util/log/registry.go#L45)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

`iterLocked` seems to imply the locks are held / need to be held already. Maybe `lockAndIter` ?
</blockquote></details>

You're right. But I decided to remove it in a later commit, because it was used in just one place.

**Comment by knz** [comment]
TFYRs!

bors r=tbg,itsbilal

**Comment by knz** [comment]
bors r=tbg,itsbilal

**Comment by knz** [comment]
bors r=tbg,itsbilal

**Comment by knz** [comment]
bazel build file missing after rebase...

bors r=tbg,itsbilal

**Pull request merged**
