### PR TITLE
ui: use sortedTable from cluster-ui

### PR DESCRIPTION
**Pull request by maryliag**
Previously, we had two different components for sortedTable,
one in cluster-ui, other in db-console.
This commits remove the one on db-console and replaces all
usages to the cluster-ui component.

This change is necessary for the alignment of sortSettings
and saving the sort on the Jobs page, for issue
https://github.com/cockroachdb/cockroach/issues/68199

Release note: None

### CODE REVIEW

**Review by matthewtodd — APPROVED** [review]
:lgtm:, just one non-blocking question below. Thanks for doing this!

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73704#-:-MqoXVIa-wsaWK3NB6ei:b-vtybl5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)

___
*[pkg/ui/workspaces/db-console/src/views/jobs/index.tsx, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73704#-MqoWwK-95A0IMHACame:-MqoWwK-95A0IMHACamf:bjj8tkf) ([raw file](https://github.com/cockroachdb/cockroach/blob/80526daa8f207d02154278336ecbca92e134c1e8/pkg/ui/workspaces/db-console/src/views/jobs/index.tsx#L166)):*
> ```XML
>     }
> 
>     util.syncHistory(
> ```

Is this `syncHistory` part new for this PR? I'm not finding a previous call in the removed code.

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73704)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @matthewtodd)

___
*[pkg/ui/workspaces/db-console/src/views/jobs/index.tsx, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73704#-MqoWwK-95A0IMHACame:-MqobZzjDwy_V2j8jB7M:b86elny) ([raw file](https://github.com/cockroachdb/cockroach/blob/80526daa8f207d02154278336ecbca92e134c1e8/pkg/ui/workspaces/db-console/src/views/jobs/index.tsx#L166)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Is this `syncHistory` part new for this PR? I'm not finding a previous call in the removed code.
</blockquote></details>

yes, it's new. We were already saving things on cache, but where not updating the history

**Review by matthewtodd — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73704)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)

___
*[pkg/ui/workspaces/db-console/src/views/jobs/index.tsx, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73704#-MqoWwK-95A0IMHACame:-Mqobsvr-9LwAFX7j_Ay:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/80526daa8f207d02154278336ecbca92e134c1e8/pkg/ui/workspaces/db-console/src/views/jobs/index.tsx#L166)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

yes, it's new. We were already saving things on cache, but where not updating the history
</blockquote></details>

:thumbsup:

**Pull request merged**
