### PR TITLE
catalog: add descriptor repair to remove missing roles

### LINKED ISSUE #122552: catalog: support validating / repair orphan roles in descriptors
On 23.1 we had a bug where you could end up with descriptor referring to roles that no longer exist, which could lead to SHOW GRANTS breaking. To help repair this error we are going to add validation and automatic repair for fixing scenarios where an dropped role exists within a descriptor.

Jira issue: CRDB-37955

Epic CRDB-37763

### PR DESCRIPTION
**Pull request by fqazi**
Previously, we had a bug that could lead to descriptors having privileages to roles that no longer exist. This could lead to certain commands like SHOW GRANTS breaking. To address this, this patch will add descirptor repair logic to automatically clean up oprhaned privileges.

Fixes: #122552

Release note (bug fix): Add automated clean up / validation for dropped roles inside descriptors.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
nice, this should be really useful! just had a comment

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122557#-:-Nvmhn45759M21xWNbXB:b-l0mesb)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/sem/builtins/builtins.go` line 5454 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122557#-NvmhSb8-K5QpL3FIURB:-NvmhSb8-K5QpL3FIURC:b-4mdazd) ([raw file](https://github.com/cockroachdb/cockroach/blob/699f5a6ecf83d7783061fc36b34b2c69dc01c112/pkg/sql/sem/builtins/builtins.go#L5454)):*
> ```Go
> 					for _, roleDatum := range (*roles).Array {
> 						role := tree.MustBeDString(roleDatum)
> 						roleMap[username.MakeSQLUsernameFromPreNormalizedString(string(role))] = struct{}{}
> ```

this can come from user input, so we must use `MakeSQLUsernameFromUserInput` instead.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122557)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/sem/builtins/builtins.go` line 5454 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122557#-NvmhSb8-K5QpL3FIURB:-NvqYh6d1tGM1V-_Zyh7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/699f5a6ecf83d7783061fc36b34b2c69dc01c112/pkg/sql/sem/builtins/builtins.go#L5454)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this can come from user input, so we must use `MakeSQLUsernameFromUserInput` instead.
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
great work! could we backport to 24.1?

> Reviewed 23 of 24 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122557#-:-Nvr4eOEEDMSzUZburT8:bkc0282)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

**Comment by fqazi** [comment]
@rafiss TFTR!

bors r+

**Comment by fqazi** [comment]
blathers backport 23.2

**Pull request merged**
