### PR TITLE
engine: destroy temp engine data on close

### PR DESCRIPTION
**Pull request by madelynnblue**
A recent PR changed the DistSQL temp storage to always be set, even in
the case of in-memory stores, like the ones in use by tests. But for
an unknown reason some tests now leave artifacts behind that can't
be cleaned up by git since they were created by the docker user. To
fix this, remove the temp rocksdb data when it is closed.

### CODE REVIEW

**Comment by dt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/engine/temp_engine.go, line 65 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17734#-KrlMEcjLTvc36iwxF4X:-KrlMEcjLTvc36iwxF4Y:b8nl8e7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a67ae243ef812c14e7c2340c64429a209935ef05/pkg/storage/engine/temp_engine.go#L65)):*
> ```Go
> func (e *tempEngine) Close() {
> 	e.RocksDB.Close()
> 	if err := os.RemoveAll(e.RocksDB.cfg.Dir); err != nil {
> ```

I think might want to need to check if cfg.Dir != ""

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17734)*

**Comment by mjibson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/engine/temp_engine.go, line 65 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17734#-KrlMEcjLTvc36iwxF4X:-KrlNX9W-7KCyCVrSGQz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a67ae243ef812c14e7c2340c64429a209935ef05/pkg/storage/engine/temp_engine.go#L65)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I think might want to need to check if cfg.Dir != ""
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17734)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17734#-:-KrlQmZGBlNOQbOQtCMY:bnfp4nl)*

**Comment by dt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/storage/engine/temp_engine.go, line 70 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17734#-KrlSFfMAAxroxryDDo6:-KrlSFfMAAxroxryDDo7:b-5527q5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2388423830f1647235dfda8f552287bc9b01525/pkg/storage/engine/temp_engine.go#L70)):*
> ```Go
> 	}
> 	if err := os.RemoveAll(dir); err != nil {
> 		log.Error(context.TODO(), "could not remove rocksdb dir: %v", err)
> ```

a/`Error`/`Errorf`/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17734)*

**Comment by mjibson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/engine/temp_engine.go, line 70 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17734#-KrlSFfMAAxroxryDDo6:-KrlUY5d8jjqEbR02KIv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2388423830f1647235dfda8f552287bc9b01525/pkg/storage/engine/temp_engine.go#L70)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

a/`Error`/`Errorf`/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17734)*

**Review by dt — APPROVED** [review]

**Pull request merged**
