### PR TITLE
distsql: Add INTERSECT ALL to HashJoiner

### PR DESCRIPTION
**Pull request by abhimadan**
Part of #21661.

Release note: None

### CODE REVIEW

**Comment by arjunravinarayan** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/hashjoiner_test.go, line 877 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21746#-L3dCbNooXOHrwOYcue0:-L3dCbNooXOHrwOYcue1:b4ogika) ([raw file](https://github.com/cockroachdb/cockroach/blob/c89b50f65dd2ef8fe3d67c2ffe881c94d7e3caa9/pkg/sql/distsqlrun/hashjoiner_test.go#L877)):*
> ```Go
> 			},
> 		},
> 		{
> ```

You should probably find a way to not duplicate these test cases across the two join processors. Not sure how, but worth thinking about at least. If there's a simple way, please merge them. Otherwise, don't bother.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21746#-:-L3dCm7TPw_xMYuj2hcV:bnfp4nl)*

**Comment by abhimadan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/distsqlrun/hashjoiner_test.go, line 877 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21746#-L3dCbNooXOHrwOYcue0:-L3dZbrPfgwXCkUiVeRM:bh5cpzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d36b4cb5d01bc7f8d1e50cd7eb7f995a8fc20f75/pkg/sql/distsqlrun/hashjoiner_test.go#L877)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

You should probably find a way to not duplicate these test cases across the two join processors. Not sure how, but worth thinking about at least. If there's a simple way, please merge them. Otherwise, don't bother.
</blockquote></details>

Should this duplication be avoided for set op-specific tests, or all of the tests in this file? The latter might be tricky because of different result ordering characteristics of the two joiners, but the former should be doable because the HashJoiner result preserves the order of the stored side, and that's all that's being output.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21746)*

**Comment by arjunravinarayan** [comment]
*[pkg/sql/distsqlrun/hashjoiner_test.go, line 877 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21746#-L3dCbNooXOHrwOYcue0:-L3dbpBLOG7UzlGnxR2y:b-84gy71) ([raw file](https://github.com/cockroachdb/cockroach/blob/d36b4cb5d01bc7f8d1e50cd7eb7f995a8fc20f75/pkg/sql/distsqlrun/hashjoiner_test.go#L877)):*
<details><summary><i>Previously, abhimadan (Abhishek Madan) wrote…</i></summary><blockquote>

Should this duplication be avoided for set op-specific tests, or all of the tests in this file? The latter might be tricky because of different result ordering characteristics of the two joiners, but the former should be doable because the HashJoiner result preserves the order of the stored side, and that's all that's being output.
</blockquote></details>

No just the set op specific tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21746)*

**Comment by abhimadan** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/distsqlrun/hashjoiner_test.go, line 877 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21746#-L3dCbNooXOHrwOYcue0:-L3e0r4mL859yQ4o0Tuq:byah34z) ([raw file](https://github.com/cockroachdb/cockroach/blob/d36b4cb5d01bc7f8d1e50cd7eb7f995a8fc20f75/pkg/sql/distsqlrun/hashjoiner_test.go#L877)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

No just the set op specific tests.
</blockquote></details>

Done. The new test utility doesn't have EXCEPT ALL test data yet, but I'm planning on adding that in the EXCEPT ALL HashJoiner PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21746)*

**Comment by arjunravinarayan** [comment]
Only skimmed, still lgtm.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21746#-:-L3e1XT4XRaP1FkGw5iX:b-by126r)*

**Pull request merged**
