### PR TITLE
pkg: fix formatting for some span tag stats

### PR DESCRIPTION
**Pull request by andreimatei**
They were formatted as bytes.

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41725#-:-LrU_y5b4z3BWRcY-pJq:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @asubiotto)

___
*[pkg/sql/flowinfra/outbox.go, line 470 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41725#-LrU_svBDN6jG6VMnrn6:-LrU_svBDN6jG6VMnrn7:bgwp45n) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8144b08d13c2dc63cbabe0a8c41af141fec2030/pkg/sql/flowinfra/outbox.go#L470)):*
> ```Go
> // StatsForQueryPlan implements the DistSQLSpanStats interface.
> func (os *OutboxStats) StatsForQueryPlan() []string {
> 	return []string{fmt.Sprintf("bytes sent: %d", os.BytesSent)}
> ```

Maybe this needs an adjustment as well?

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41725#-:-LrUbnl41Zkhru0Ayq5h:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/flowinfra/outbox.go, line 470 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41725#-LrU_svBDN6jG6VMnrn6:-LrUbn3743aVXIWoLsFH:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8144b08d13c2dc63cbabe0a8c41af141fec2030/pkg/sql/flowinfra/outbox.go#L470)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Maybe this needs an adjustment as well?
</blockquote></details>

done

**Comment by dt** [comment]
I thought we didn’t bors until github ci was green?

**Comment by andreimatei** [comment]
> I thought we didn’t bors until github ci was green?

sorry

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41725#-:-Lrjunk6EkP56Apayfpl:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @yuzefovich)

**Review by andreimatei — COMMENTED** [review]
TC infra flake

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41725#-:-LrjxTzx2W_zeS_Dro7X:b-z6dioe)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @yuzefovich)

**Pull request merged**
