### PR TITLE
pkg/storage: remove GetCompactionStats, refactor GetMetrics

### PR DESCRIPTION
**Pull request by jbowens**
Refactor the 'compaction stats' and metrics exposed from the
storage.Engine to directly expose `*pebble.Metrics`, embedded within a
`storage.Metrics` struct.

Also, pass the `Metrics` type directly into log lines where we print the
full LSM.

Release note: None

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
@knz is this an appropriate use of `redact.Safe`? I know it's supposed to be an escape hatch, not a regular tool in the toolbox. The ASCII table is constructed from within Pebble.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64132#-:-MYzFoBG3qeZ01VkLrWF:b30xyur)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @knz, and @petermattis)

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64132)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, and @knz)

___
*[pkg/kv/kvserver/store.go, line 2665 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64132#-MYzRNQH5GcH8-hX0XrU:-MYzRNQH5GcH8-hX0XrV:bci0616) ([raw file](https://github.com/cockroachdb/cockroach/blob/2800b9d07cdd5125eef5111cf3cbe6a56daacb75/pkg/kv/kvserver/store.go#L2665)):*
> ```Go
> 	// stats.
> 	if tick%logSSTInfoTicks == 1 /* every 10m */ {
> 		log.Infof(ctx, "%s", redact.Safe(s.engine.GetCompactionStats()))
> ```

Now that we only have Pebble, we could change `GetCompactionStats()` to return a `redact.SafeFormatter` and change `pebble.Metrics` to implement `redact.SafeFormatter`. There is some precedence for this in `pebble/event.go` where various structs implement `SafeFormat()`. Quite a bit more onerous to plumb that through. I'm curious what @knz thinks is the right approach.

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64132)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

___
*[pkg/kv/kvserver/store.go, line 2665 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64132#-MYzRNQH5GcH8-hX0XrU:-MYzvFQQ08Sn4wqSqXGM:bzemg1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/2800b9d07cdd5125eef5111cf3cbe6a56daacb75/pkg/kv/kvserver/store.go#L2665)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Now that we only have Pebble, we could change `GetCompactionStats()` to return a `redact.SafeFormatter` and change `pebble.Metrics` to implement `redact.SafeFormatter`. There is some precedence for this in `pebble/event.go` where various structs implement `SafeFormat()`. Quite a bit more onerous to plumb that through. I'm curious what @knz thinks is the right approach.
</blockquote></details>

I agree with Peter's assessment.

**Comment by knz** [comment]
I think that with your changes to pebble, this is resolved now?

**Comment by jbowens** [comment]
> I think that with your changes to pebble, this is resolved now?

I'd still like to update this PR to thread the `*pebble.Metrics` directly into the logging call (rather than invoking `.String()` on it). I'm off next week but should be able to get around to it the week after.

**Review by sumeerbhola — APPROVED** [review]
Nice to see this cleanup!
This is also handy for the admission control plumbing.

:lgtm: 

> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64132#-:-Mair6y49tmYvwXtSwDD:b-b7xbl6)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

**Review by jbowens — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64132#-:-MajOG1j9IiWX6AprDnz:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

**Pull request merged**
