### PR TITLE
sql: allow mixed int/decimal arithmetic.

### PR DESCRIPTION
**Pull request by knz**
Mixing ints and decimals does not run any risk to lose precision, like
mixed arithmetic with floats would. So enable it.

Suggested by #7414.

Also reduces the number of sqllogictest errors in #7733 greatly.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7756)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
:lgtm: Nice!

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/parser/eval.go, line 584 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7756#-KMSJt1NMj7qZkNXUcJ-:-KMSJt1NMj7qZkNXUcJ0:1615213550) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9db5d5bb6846cc2e204001d17763d3664bc241b/sql/parser/eval.go#L584)):*
> ```Go
> 		},
> 		BinOp{
> 			LeftType:   TypeDecimal,
> ```

nit: Add and Sub have the `(Dec, Dec)` impl before the `(Dec, Int)` and `(Int, Dec)`, but Mul, Div, FloorDiv, and Mod have it after. I would change the ordering of Mul, Div, FloorDiv, and Mod to match Add and Sub (homogeneous impl before heterogeneous impls).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7756#-:-KMSKxafEGZffQoznWWY:-511547851)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/parser/eval.go, line 584 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7756#-KMSJt1NMj7qZkNXUcJ-:-KMT84NmRkH5TUBXk1Nk:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9db5d5bb6846cc2e204001d17763d3664bc241b/sql/parser/eval.go#L584)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> nit: Add and Sub have the `(Dec, Dec)` impl before the `(Dec, Int)` and `(Int, Dec)`, but Mul, Div, FloorDiv, and Mod have it after. I would change the ordering of Mul, Div, FloorDiv, and Mod to match Add and Sub (homogeneous impl before heterogeneous impls).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7756)*

**Comment by knz** [comment]
@nvanbenschoten could you have a look at the failing TestTypeCheckOverloadedExprs? I understand why the two test fails (a demand of Decimal on a + over two non-typed literals is now ambiguous, whereas before there was just one overload). However I don't really know what the test was checking so I am unsure what new test to use instead.

**Comment by nvanbenschoten** [comment]
@knz It looks like I missed your previous comment, sorry about that. Do you still need me to look into TestTypeCheckOverloadedExprs?

**Comment by knz** [comment]
I think I now understand the gist of the original test and replaced the check for demanded types by Float (instead of decimal) to recover from the ambiguity introduced by this PR. Let me know if that wasn't the right approach.

**Comment by nvanbenschoten** [comment]
It looks like the PR slightly changed the meaning of two tests cases, and the fact that this change caused the previous cases to break is a little worrisome (with regard to our overload resolution code, not this change in particular). The difference is that previously we were testing with constant literals (`decConst`, which despite the name is not a typed `DECIMAL`, but instead a decimal-like constant), but we are now testing with typed `FLOAT`s (`NewDFloat`). 

The first test case was `decConst("1.1"), plus(intConst("1"), intConst("2"))`, which would roughly translate to `1.1 + (1 + 2)`. The change made here roughly equates to `ANNOTATE_TYPE(1.1, FLOAT) + (1 + 2)`. Is the original statement now considered ambiguous?

**Comment by knz** [comment]
1.1 + (1 + 2) is now ambiguous because:

1) the outermost + now accepts both int and decimal on its 2nd operand; 

2) even with the homogeneity rule, it would demand decimal on its 2nd operand, but there are now more than 1 candidate that provide this return type (3 of them actually) so the "demanded return type" does not disambiguate.

**Comment by nvanbenschoten** [comment]
Yeah ok, that all makes sense. Fortunately constant folding will take care of this case for us anyway, so the example was a little contrived.

**Comment by knz** [comment]
so what do we do with the test?

**Comment by nvanbenschoten** [comment]
You can leave the new test cases, but would you mind adding back in the old ones with no (`nil`) `expectedOverload`? Maybe pull it down into a separate section and explain what you said in https://github.com/cockroachdb/cockroach/pull/7756#issuecomment-235033869 (or just link to it).

**Pull request merged**
