### PR TITLE
*,isql: introduce isql.Txn and isql.DB

### PR DESCRIPTION
**Pull request by ajwerner**
This massive refactor works to bind the `*kv.Txn` with the internal executor and other sql-layer, txn-associated state. This work follows on from an earlier project to more tightly couple internal executors to the rest of `extraTxnState`. That project resulted in sprawling changes to propagated the paired dependencies through the system. In practice, we're better off coupling them through an object.

There are some refactors added in here to curry and hide some of these dependencies from interfaces. Those may be possible to extract to be separate.

Additionally, not all of the dependency sprawl has been eliminated; there are cases where we could pass a `isql.Txn` but instead keep passing the underlying `isql.Executor` and `*kv.Txn`. We can do more cleanup along the way.

Lastly, I couldn't help myself from lifting some `sql.ExecCfg` arguments up and being more specific in some places.

Epic: none

Release note: None

### CODE REVIEW

**Review by postamar — APPROVED** [review]

**Review by ZhouXing19 — APPROVED** [review]
Thanks for the impressive work! LGTM, only left nit comments.

And just wanted to confirm the main remaining work:
1. Replace parallel {`*kv.DB` and `isql.Executor`} in structs to `isql.DB`(such as in`kvserver/reports.Reporter`), {`*kv.txn` and `isql.Executor`} to `isql.Txn` (such as in `scdeps.buildDeps`). 
2. Deprecate functions such as `sql.DescsTxn` and  make `sql.MakeInternalExecutor` private. Deprecate `sqlServerArgs.circularInternalExecutor`.
3. Remove the `txn` from methods in `isql.Executor` .

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-:-NM0-wv9BkBiC27BaYFK:b-3bkgdp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @michae2, @renatolabs, @rhu713, @samiskin, and @srosenberg)

___
*[`pkg/ccl/backupccl/backup_planning.go` line 830 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM-quFC1iRRmZPcc9CK:-NM-quFC1iRRmZPcc9CL:bi8bg4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/ccl/backupccl/backup_planning.go#L830)):*
> ```Go
> 			return err
> 		}
> 		p.InternalSQLTxn().Descriptors().ReleaseAll(ctx)
> ```

Just curious why we need to release the descriptors here? (in other words, why previously we didn't do this?)
___
*[`pkg/ccl/backupccl/restore_job.go` line 1599 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM08f3p4uks3XQFFiVc:-NM08f3p4uks3XQFFiVd:b-y5t9ng) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/ccl/backupccl/restore_job.go#L1599)):*
> ```Go
> 			return r.publishDescriptors(ctx, txn, p.ExecCfg(), p.User(), descsCol, details, nil)
> 		}
> 		if err := r.execCfg.InternalDB.Txn(ctx, publishDescriptors); err != nil {
> ```

ditto, can we use `InternalDB.DescTxn()`?
___
*[`pkg/ccl/backupccl/restore_job.go` line 1745 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM08_lW5AV6dqKjNGN0:-NM02SnlEgto3aeb14tB:bqf94t7) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/ccl/backupccl/restore_job.go#L1745)):*
> ```Go
> 		return r.publishDescriptors(ctx, txn, p.ExecCfg(), p.User(), descsCol, details, devalidateIndexes)
> 	}
> 	if err := r.execCfg.InternalDB.Txn(ctx, publishDescriptors); err != nil {
> ```

nit: can we just use `r.execCfg.InternalDB.DescsTxn()` here? 
___
*[`pkg/ccl/changefeedccl/schemafeed/schema_feed.go` line 114 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM09e4K90ysfbqBCa_L:-NM09e4K90ysfbqBCa_M:bf7zc20) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/ccl/changefeedccl/schemafeed/schema_feed.go#L114)):*
> ```Go
> type schemaFeed struct {
> 	filter     tableEventFilter
> 	db         descs.DB
> ```

Do we still need the `db` and `collectionFactory` here? It seems that `leaseMgr` already stores them.
___
*[`pkg/jobs/adopt.go` line 449 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM0jI1k4FC_30q9YI43:-NM0jI1k4FC_30q9YI44:bo9c79u) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/jobs/adopt.go#L449)):*
> ```Go
> }
> 
> func (r *Registry) clearLeaseForJobID(jobID jobspb.JobID, ex isql.Executor, txn *kv.Txn) {
> ```

nit: could you add a TODO for using `isql.Txn` rather than `ex isql.Executor, txn *kv.Txn`?
___
*[`pkg/sql/conn_executor.go` line 438 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM-WQysD-B-8F540hR5:-NM-WQysD-B-8F540hR6:b-bqkvjh) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/sql/conn_executor.go#L438)):*
> ```Go
> 	s.schemaTelemetryController = schematelemetrycontroller.NewController(
> 		NewInternalDB(
> 			s, MemoryMetrics{}, sqlStatsInternalExecutorMonitor,
> ```

Previously the internal executor here is initialized with `schemaTelemetryIEMonitor`, now we're using `sqlStatsInternalExecutorMonitor`. Is this intentional? 
___
*[`pkg/sql/internal.go` line 1401 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM-TziC48u4wCXH2q5b:-NM-TziC48u4wCXH2q5c:b4wkasg) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/sql/internal.go#L1401)):*
> ```Go
> type kvTxnFunc = func(context.Context, *kv.Txn) error
> 
> // DescsTxnWithExecutor enables callers to run transactions with a *Collection
> ```

nit: the comment needs to be updated, and all occurrences of `DescsTxnWithExecutor` should be updated to `DescsTxn`
___
*[`pkg/sql/planner.go` line 561 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM-_LXo8wu0AasLdbyM:-NM-_LXo8wu0AasLdbyN:bvkwxw9) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/sql/planner.go#L561)):*
> ```Go
> 
> func (p *planner) InternalSQLTxn() descs.Txn {
> 	if p.internalSQLTxn.txn != p.txn {
> ```

Just out of curiosity -- we're not having `p.internalSqlTxn.txn == nil` here, does it mean that there can be `p.internalSQLTxn.txn != nil && p.p.internalSQLTxn.txn != p.txn`? In what case does this happen?
___
*[`pkg/sql/planner.go` line 701 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM0wXVS91NdAzurjRVM:-NM0wXVS91NdAzurjRVN:bhxh8hr) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/sql/planner.go#L701)):*
> ```Go
> // Note that this function should only be used when using internal executor
> // to run sql statement under the planner context.
> func initInternalExecutor(ctx context.Context, p *planner) isql.Executor {
> ```

All usages of `initInternalExecutor` can be replaced by `planner.InternalSQLTxn()`.
___
*[`pkg/sql/privileged_accessor.go` line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM0x4hd8Jv8OMnO4m9_:-NM0x4hd8Jv8OMnO4m9a:b-dog8le) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/sql/privileged_accessor.go#L37)):*
> ```Go
> 		keys.NamespaceTableID,
> 	)
> 	r, err := p.InternalSQLTxn().QueryRowEx(
> ```

All `planner.InternalSQLTxn().___Ex()` can actually go through `planner.___Ex()` directly. But maybe you want to deprecate the latter?
___
*[`pkg/sql/schema_changer.go` line 2440 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM08tHr6xdtQJYdo7gO:-NM04Zx20DUkR_92yPGq:b-wjbduv) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/sql/schema_changer.go#L2440)):*
> ```Go
> // txn is a convenient wrapper around descs.Txn().
> func (sc *SchemaChanger) txn(
> 	ctx context.Context, f func(context.Context, isql.Txn, *descs.Collection) error,
> ```

nit: can we replace `isql.Txn, *descs.Collection` with `descs.Txn`, and use `sc.execCfg.InternalDB.DescsTxn()` in the return? Or could you add a TODO? 
___
*[`pkg/sql/schema_changer.go` line 2453 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM08rp01O7owCHarwrE:-NM03zm35Vhky8JgFP8J:btyphgk) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/sql/schema_changer.go#L2453)):*
> ```Go
> func (sc *SchemaChanger) txnWithExecutor(
> 	ctx context.Context, f func(
> 		context.Context, isql.Txn, *descs.Collection,
> ```

nit: ditto, can we use `descs.Txn` and `sc.execCfg.InternalDB.DescsTxn()`?
___
*[`pkg/sql/execinfra/server_config.go` line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM0pvJp15GRw5l_4m06:-NM0pvJp15GRw5l_4m07:bdd14sa) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/sql/execinfra/server_config.go#L148)):*
> ```Go
> 	// executors. The idea is that a higher-layer binds some of the arguments
> 	// required, so that users of ServerConfig don't have to care about them.
> 	InternalDB descs.DB
> ```

This seems redundant to the `DB descs.DB` above.
___
*[`pkg/sql/schemachanger/scdeps/build_deps.go` line 67 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM0yuoX6GNM6DI8AScb:-NM0yuoX6GNM6DI8AScc:b-hwp271) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/sql/schemachanger/scdeps/build_deps.go#L67)):*
> ```Go
> 		astFormatter:     astFormatter,
> 		featureChecker:   featureChecker,
> 		internalExecutor: txn,
> ```

This `internalExecutor` is never used so can be removed.
___
*[`pkg/ccl/streamingccl/streamproducer/replication_manager_test.go` line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM0UJoO6IoOEljOg72I:-NM0UJoO6IoOEljOg72J:b-9uzvqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/ccl/streamingccl/streamproducer/replication_manager_test.go#L56)):*
> ```Go
> 		ec := p.(interface{ EvalContext() *eval.Context }).EvalContext()
> 		var man eval.ReplicationStreamManager
> 		if err := execCfg.InternalDB.Txn(ctx, func(
> ```

Any reason why we need to start a new kv transaction here, rather than having the planner created in the same txn?

**Review by ajwerner — COMMENTED** [review]
Those steps all sound right to me. Thanks for the thorough review of a very hard-to-read PR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-:-NM1pi9r97UhDURWyZqL:b-itxs68)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2, @renatolabs, @rhu713, @samiskin, @srosenberg, and @ZhouXing19)

___
*[`pkg/ccl/backupccl/backup_planning.go` line 830 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM-quFC1iRRmZPcc9CK:-NM1lknS9kC01oBi-_4V:b-smgym) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/ccl/backupccl/backup_planning.go#L830)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Just curious why we need to release the descriptors here? (in other words, why previously we didn't do this?)
</blockquote></details>

I added commentary. Before we never acquired leases using the transaction's descs.Collection because every statement we executed was on the internal executor. 
___
*[`pkg/ccl/backupccl/restore_job.go` line 1599 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM08f3p4uks3XQFFiVc:-NM1lth_7pUwT0JXRY4Q:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/ccl/backupccl/restore_job.go#L1599)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

ditto, can we use `InternalDB.DescTxn()`?
</blockquote></details>

Done. 
___
*[`pkg/ccl/backupccl/restore_job.go` line 1745 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM08_lW5AV6dqKjNGN0:-NM1m-NNAWT0q4ob9WMP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/ccl/backupccl/restore_job.go#L1745)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: can we just use `r.execCfg.InternalDB.DescsTxn()` here? 
</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/schemafeed/schema_feed.go` line 114 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM09e4K90ysfbqBCa_L:-NM1m0ze8karPThFRmjA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/ccl/changefeedccl/schemafeed/schema_feed.go#L114)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Do we still need the `db` and `collectionFactory` here? It seems that `leaseMgr` already stores them.
</blockquote></details>

Done.
___
*[`pkg/jobs/adopt.go` line 449 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM0jI1k4FC_30q9YI43:-NM1m3lr4WAaMHZuQuGh:bjgbg6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/jobs/adopt.go#L449)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: could you add a TODO for using `isql.Txn` rather than `ex isql.Executor, txn *kv.Txn`?
</blockquote></details>

I think this is legit. In one call it's transactional and in the other it isn't. What will go away is the need to pass the txn argument.
___
*[`pkg/sql/conn_executor.go` line 438 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM-WQysD-B-8F540hR5:-NM1mC0K2zYyt0Tdp_Pf:b-ht72a0) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/sql/conn_executor.go#L438)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Previously the internal executor here is initialized with `schemaTelemetryIEMonitor`, now we're using `sqlStatsInternalExecutorMonitor`. Is this intentional? 
</blockquote></details>

good catch! fixed
___
*[`pkg/sql/internal.go` line 1401 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM-TziC48u4wCXH2q5b:-NM1mEFk6b1QswOTnMtJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/sql/internal.go#L1401)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: the comment needs to be updated, and all occurrences of `DescsTxnWithExecutor` should be updated to `DescsTxn`
</blockquote></details>

Done.
___
*[`pkg/sql/planner.go` line 561 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM-_LXo8wu0AasLdbyM:-NM1pqrN8nMJ4mcRh7ns:b8n21d0) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/sql/planner.go#L561)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Just out of curiosity -- we're not having `p.internalSqlTxn.txn == nil` here, does it mean that there can be `p.internalSQLTxn.txn != nil && p.p.internalSQLTxn.txn != p.txn`? In what case does this happen?
</blockquote></details>

Yeah, that can definitely happen. Nothing resets this structure except this call. I sprinkled some commentary around. This exists mostly to avoid allocating a new struct. I also added a nil check such that this now returns nil if p.txn is nil.
___
*[`pkg/sql/planner.go` line 701 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM0wXVS91NdAzurjRVM:-NM1qBUm16uwQVNsyL-B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/sql/planner.go#L701)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

All usages of `initInternalExecutor` can be replaced by `planner.InternalSQLTxn()`.
</blockquote></details>

Done.
___
*[`pkg/sql/privileged_accessor.go` line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM0x4hd8Jv8OMnO4m9_:-NM1qKDd9nBvfDg2dnvj:b-1twq15) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/sql/privileged_accessor.go#L37)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

All `planner.InternalSQLTxn().___Ex()` can actually go through `planner.___Ex()` directly. But maybe you want to deprecate the latter?
</blockquote></details>

I think to some extent it's more that I want to move this file out of the sql package. I think probably I'll want to remove those methods from the eval.Planner and, perhaps, just add an isql.Executor to eval.Context as a separate field. I'm not sure. 
___
*[`pkg/sql/schema_changer.go` line 2440 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM08tHr6xdtQJYdo7gO:-NM1qmtf5Dyod_dW0r9B:b-t2x7qd) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/sql/schema_changer.go#L2440)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: can we replace `isql.Txn, *descs.Collection` with `descs.Txn`, and use `sc.execCfg.InternalDB.DescsTxn()` in the return? Or could you add a TODO? 
</blockquote></details>

Added a TODO. It's a lot of code movement that can wait for a follow-up.
___
*[`pkg/sql/schema_changer.go` line 2453 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM08rp01O7owCHarwrE:-NM1qqNoBux9Gtkqt_1t:bwmsf9) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/sql/schema_changer.go#L2453)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: ditto, can we use `descs.Txn` and `sc.execCfg.InternalDB.DescsTxn()`?
</blockquote></details>

We can, it's just more code movement for a later PR. 
___
*[`pkg/sql/execinfra/server_config.go` line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM0pvJp15GRw5l_4m06:-NM1r7aA48PTS6UpPJvn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/sql/execinfra/server_config.go#L148)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

This seems redundant to the `DB descs.DB` above.
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/scdeps/build_deps.go` line 67 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM0yuoX6GNM6DI8AScb:-NM1r8SAEmfF3LvQ4AkQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/sql/schemachanger/scdeps/build_deps.go#L67)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

This `internalExecutor` is never used so can be removed.
</blockquote></details>

Done.
___
*[`pkg/ccl/streamingccl/streamproducer/replication_manager_test.go` line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93218#-NM0UJoO6IoOEljOg72I:-NM1r9NrB0HSNpaeIqSS:b-bc8a4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/964fab6c9ccecc841813b1b571cca284b01790f7/pkg/ccl/streamingccl/streamproducer/replication_manager_test.go#L56)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Any reason why we need to start a new kv transaction here, rather than having the planner created in the same txn?
</blockquote></details>

Done. Took a little bit of interface hackery.

**Comment by ajwerner** [comment]
The flake was https://github.com/cockroachdb/cockroach/issues/92809. I keep trying to repro with `COCKROACH_DEBUG_SPAN_USE_AFTER_FINISH=t` and it won't even though it repros very fast without that set. I'm going to just try again.

bors r+

**Comment by ajwerner** [comment]
bors r+

🤞

**Comment by yuzefovich** [comment]
It seems like this change made it much more likely for the race in #92809 to occur, and I have a fix in flight. Andrew, you could have just pinged me to fix it sooner if it was bothering you :)

**Comment by ajwerner** [comment]
@yuzefovich I stressed it with `COCKROACH_DEBUG_SPAN_USE_AFTER_FINISH=t` for over 30 minutes and I couldn't get it to fail, though it did flake very rapidly without that flag. I have no idea.

**Comment by yuzefovich** [comment]
I think the failure occurs when the node is quescing at the end of the logic test, and perhaps `COCKROACH_DEBUG_SPAN_USE_AFTER_FINISH` knob slows the shutdown process enough for race to be much more rare.

**Pull request merged**
