### PR TITLE
storage: add telemetry counter for txns pushed by the closed timestamp

### LINKED ISSUE #40653: storage: add telemetry around transaction restarts caused by closed timestamps
As we look to reduce the closed timestamp duration, it will be useful to monitor how frequently the closed timestamp duration causes transactions to have to bump their commit timestamp. This will help guide how low we can reasonably set it.

I imagine the telemetry will go somewhere around here:
https://github.com/cockroachdb/cockroach/blob/bdf41f7d03f0dafeeaf3bc6aac40f502ab069a6a/pkg/storage/replica_tscache.go#L258-L260

@ajwerner we talked about this before. Mind if I push this your way?

### PR DESCRIPTION
**Pull request by ajwerner**
Fixes #40653.

Release justification: low risk addition of telemetry.

Release note: None

### CODE REVIEW

**Comment by awoods187** [comment]
Nice! excited to have this data

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41267#-:-LqHkAhu1BhXfbzyB2xg:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/storage/replica_test.go, line 11852 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41267#-LqHeXeE91bKl6ws2PK2:-LqHeXeE91bKl6ws2PK3:b-y258kk) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bac82a53b1cdb7038c5e3365a565d57c35afa14/pkg/storage/replica_test.go#L11852)):*
> ```Go
> 			},
> 		},
> 		// Test the case where we bump due to the read ts cache rather than the minReadTS.
> ```

nit: are the comments on these tests in the curly brackets or outside? We're inconsistent.
___
*[pkg/storage/replica_tscache.go, line 269 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41267#-LqHk0uu6-BTWIgwHZSB:-LqHk0uu6-BTWIgwHZSC:b-wq9mwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bac82a53b1cdb7038c5e3365a565d57c35afa14/pkg/storage/replica_tscache.go#L269)):*
> ```Go
> 			}
> 			nextRTS := rTS.Next()
> 			var didBump bool
> ```

Consider making this name more clearly distinct from `bumped`. Maybe `bumpedCurReq`.
___
*[pkg/storage/store.go, line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41267#-LqHdrND2f5btAM1Z9aw:-LqHdrND2f5btAM1Z9ax:bg7i34r) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bac82a53b1cdb7038c5e3365a565d57c35afa14/pkg/storage/store.go#L400)):*
> ```Go
> 	// transactions which have been pushed due to the closed timestamp.
> 	// See Replica.applyTimestampCache().
> 	txnsPushedDueToClosedTimestamp telemetry.Counter
> ```

I think I led you to add this to `Store`, but after further investigation that might have been the wrong decision. SQL appears to hold all of these counters as static variables.

**Review by ajwerner — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41267#-:-LqI1p4sDfLDMrVSV0xx:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/storage/replica_test.go, line 11852 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41267#-LqHeXeE91bKl6ws2PK2:-LqI1CMN2bxxxneOB_eI:b-u1qbgs) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bac82a53b1cdb7038c5e3365a565d57c35afa14/pkg/storage/replica_test.go#L11852)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: are the comments on these tests in the curly brackets or outside? We're inconsistent.
</blockquote></details>

Moved the comment into the struct. 
___
*[pkg/storage/store.go, line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41267#-LqHdrND2f5btAM1Z9aw:-LqI1GKE3LCbONJSZPAe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bac82a53b1cdb7038c5e3365a565d57c35afa14/pkg/storage/store.go#L400)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think I led you to add this to `Store`, but after further investigation that might have been the wrong decision. SQL appears to hold all of these counters as static variables.
</blockquote></details>

Done.

**Pull request merged**
