### PR TITLE
opt: support index flags

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: support index flags

Support the index flags that force a specific index or that disallow
index-join. An outline of how we achieve this:
 - ScanOpDef contains the flags for the scan.
 - We don't generate index scan expressions for any secondary index
   that doesn't match the forced index, or for non-covering indexes
   (depending on the flags).
 - When forcing the use of a secondary index, the coster gives the
   primary index scan expression a very high cost so that it will
   never be chosen in favor of the secondary index.

Release note: None

#### sql: rename select_index_hints tests to select_index_flags

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Updaeted; had to address an annoying case when you try to force an inverted index and it is not suitable for a query. I added a check for the condition in the execbuilder.

**Review by justinj — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28456#-:-LJZUDt1DlR9qn8kuCAW:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/private_defs.go, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28456#-LJZUHmA72aG_pfo4txQ:-LJZUHmA72aG_pfo4txR:b2gkalz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1ba1383b2e2f58edab8ce15c6cefe755ab014dc/pkg/sql/opt/memo/private_defs.go#L128)):*
> ```Go
> }
> 
> func (sh ScanFlags) String() string {
> ```

nit: it would be mildly annoying to thread through the info I guess, but having the index name in this might be helpful, doesn't matter too much either way

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28456)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/private_defs.go, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28456#-LJZUHmA72aG_pfo4txQ:-LJZWjo6ACW8RD1_DLiB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1ba1383b2e2f58edab8ce15c6cefe755ab014dc/pkg/sql/opt/memo/private_defs.go#L128)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nit: it would be mildly annoying to thread through the info I guess, but having the index name in this might be helpful, doesn't matter too much either way
</blockquote></details>

Done.

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28456#-:-LJkeuzd0T5soe-fwuLn:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/xform/coster.go, line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28456#-LJkeUTwCVkVp_-2vGuu:-LJkeUTwCVkVp_-2vGuv:bqnpqqr) ([raw file](https://github.com/cockroachdb/cockroach/blob/03082b6a69282f20816926d609034663ce35817a/pkg/sql/opt/xform/coster.go#L174)):*
> ```Go
> 		// If we are forcing an index, any other index has a very high cost. In
> 		// practice, this will only happen when this is a primary index scan.
> 		return 1e100
> ```

I'd make this a constant at the top of the file, since the number itself is just a large arbitrary value.

**Review by rytaft — DISMISSED** [review]
:lgtm:

> Reviewed 11 of 16 files at r1, 7 of 7 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28456#-:-LJnybMm8RLcWDGV6zbs:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/exec/execbuilder/testdata/select_index, line 397 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28456#-LJny9yJ0geftvQ6FOzW:-LJny9yJ0geftvQ6FOzX:b74kcum) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5b79b2f4ec9ed4c14b469764f3f6751e51f426b/pkg/sql/opt/exec/execbuilder/testdata/select_index#L397)):*
> ```
>  WHERE message LIKE 'fetched:%' OR message LIKE 'output row%'
> ----
> fetched: /t/ab/1/2 -> NULL
> ```

Is this a sign that we are missing some possible optimizations?
___
*[pkg/sql/opt/memo/private_storage.go, line 249 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28456#-LJnvGmY0ERvnDDk-aQ_:-LJnvGmY0ERvnDDk-aQa:b5ztnk3) ([raw file](https://github.com/cockroachdb/cockroach/blob/03082b6a69282f20816926d609034663ce35817a/pkg/sql/opt/memo/private_storage.go#L249)):*
> ```Go
> 	}
> 	if def.Flags.ForceIndex {
> 		flags += 2 + def.Flags.Index
> ```

[nit] why not just set it equal instead of using `+=`? These two flags should never be used at the same time, right? (If they can, this causes an issue when `def.Flags.Index=1`)
___
*[pkg/sql/opt/exec/execbuilder/testdata/select_index_hints, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28456#-LJnueds6y_ghWTff_yt:-LJnueds6y_ghWTff_yu:bnfznfz) ([raw file](https://github.com/cockroachdb/cockroach/blob/03082b6a69282f20816926d609034663ce35817a/pkg/sql/opt/exec/execbuilder/testdata/select_index_hints#L81)):*
> ```
> ----
> render                ·      ·
>  └── filter           ·      ·
> ```

why do we add a filter?

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28456#-:-LJoFKsE70ulc2zYs0Jr:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale)

___
*[pkg/sql/opt/exec/execbuilder/testdata/select_index, line 397 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28456#-LJny9yJ0geftvQ6FOzW:-LJo33Y425pd7hssvIaz:b9lwzj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5b79b2f4ec9ed4c14b469764f3f6751e51f426b/pkg/sql/opt/exec/execbuilder/testdata/select_index#L397)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Is this a sign that we are missing some possible optimizations?
</blockquote></details>

Yeah, we don't fold `4 - 1`  to `3` so we don't generate index constraints. Before this change, the query ran with the heuristic planner which does do that. Added a TODO.
___
*[pkg/sql/opt/memo/private_storage.go, line 249 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28456#-LJnvGmY0ERvnDDk-aQ_:-LJo43hvB00ThCm1XFe6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/03082b6a69282f20816926d609034663ce35817a/pkg/sql/opt/memo/private_storage.go#L249)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] why not just set it equal instead of using `+=`? These two flags should never be used at the same time, right? (If they can, this causes an issue when `def.Flags.Index=1`)
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/coster.go, line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28456#-LJkeUTwCVkVp_-2vGuu:-LJoEz2e0M4a6DADUUQO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/03082b6a69282f20816926d609034663ce35817a/pkg/sql/opt/xform/coster.go#L174)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I'd make this a constant at the top of the file, since the number itself is just a large arbitrary value.
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/testdata/select_index_hints, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28456#-LJnueds6y_ghWTff_yt:-LJo3kcpDxcsQRSQQmOQ:b-4zjm8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/03082b6a69282f20816926d609034663ce35817a/pkg/sql/opt/exec/execbuilder/testdata/select_index_hints#L81)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

why do we add a filter?
</blockquote></details>

The query requires a post-index-join filter. In the heuristic planner case, this filter is inside the `table` scanNode.

**Pull request merged**
