### PR TITLE
1.1 only: distsqlrun: introduce --extra-1.0-compatibility

### PR DESCRIPTION
**Pull request by andreimatei**
Release note: none; let's not advertise this.

Introduce a new flag forcing 1.1 nodes to be compatible with DistSQL
flows produced by 1.0 gateways. This is motivated by some clients not
finding it easy to upgrade from 1.0 to 1.1 because of DistSQL on 1.1
refusing flows produced by 1.0, and so a mixed-version cluster running
for an extended period has a problem.

--extra-1.0-compatibility does the following:
- makes consumers not send handshake messages to producers upon stream
connection. These messages were new in 1.1 and would confuse 1.0 code.
These handshakes are not actually used at the moment, albeit they may be
in a future version.
- an old proto format for AggregationSpec's is supported.
- the DistSQL MinAcceptedVersion is reset to 3, which is 1.0.x's
version.

These changes are done only on the 1.1 branch. 1.2 will not support this
flag.

Touches #20003

### CODE REVIEW

**Comment by andreimatei** [comment]
Doing some testing now.

**Comment by RaduBerinde** [comment]
Great stuff! LGTM

**Comment by petermattis** [comment]
Will this affect upgrading from a 1.1 cluster which specifies this new flag, to a 2.0 cluster which doesn't?

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cli/cliflags/flags.go, line 574 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20285#-KzzN3GSqAT2dTcvXmDm:-KzzN3GSqAT2dTcvXmDn:b-sjno2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/74b4869a1e0fb6b22162cdcc4839dce7b2d1de6e/pkg/cli/cliflags/flags.go#L574)):*
> ```Go
> 
> 	Extra1_0Compatibility = FlagInfo{
> 		Name: "extra-1.0-compatibility",
> ```

I wonder if this flag name should contain `distsql`. Something like `extra-distsql-1.0-compatibility`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20285#-:-KzzNLbpCt6REN2GjYK6:b-c8fvei)*

**Comment by andreimatei** [comment]
I've tested this in a mixed cluster and it seems to work fine for queries spanning versions and using a 1.0 gateway. I've considered adding an acceptance test, but frankly it'd need to be quite involved for not so much benefit, so I'd merge without it.

@petermattis no; upgrading from 1.1+flag to 2.0 shouldn't be a problem. It's exceedingly unlikely at this point that 2.0 will use those handshake messages that the flag is disabling because none of our error tolerance discussions recently went into the direction that those messages were supposed to work towards.

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/cli/cliflags/flags.go, line 574 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20285#-KzzN3GSqAT2dTcvXmDm:-KzzWQqllYtXAe1Eg9Kw:b-pcpaa0) ([raw file](https://github.com/cockroachdb/cockroach/blob/74b4869a1e0fb6b22162cdcc4839dce7b2d1de6e/pkg/cli/cliflags/flags.go#L574)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I wonder if this flag name should contain `distsql`. Something like `extra-distsql-1.0-compatibility`.
</blockquote></details>

meh; I think the current form is accurate enough :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20285#-:-KzzVlOFo9BMsK-UcKf1:b-2jb3yi)*

**Pull request merged**
