### PR TITLE
cli,server: add heap profiles to debug zip dumps

### LINKED ISSUE #23830: cli: capture heap profiles in debug zip
We need to enhance our debug zip tool so that it is more useful to CRDB developers for debugging.

For this next release (2.1), the only thing we need to do is add heap profiles in. We are explicitly punting additional functionality, or the ability to run debug zip on a down cluster, until we have a better idea of what actionable steps can be taken to improve that workflow. 

cc @petermattis and @vivekmenezes for assignment.

Also, moving this out of our roadmap since it should not take more than a week?

### PR DESCRIPTION
**Pull request by petermattis**
Added a `Status.Profile` RPC for retrieving profiles from remote
notes. Currently only heap profiles are supported, though other profiles
could be added easily.

Added heap profiles for each node to the debug zip output.

Fixes #23830

Release note (cli change): Add per-node heap profiles to the "debug zip"
command output.

### CODE REVIEW

**Comment by BramGruneir** [comment]
Can you also add this new endpoint to https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/src/views/reports/containers/debug/index.tsx

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23843#-:-L7_UpFq1AtooALRqS9r:b-zfx7pl)*

**Comment by bdarnell** [comment]
:lgtm:

No need to add this to the debug index; it's redundant with the /debug/pprof/heap link that is already there. 

---

Reviewed 6 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23843#-:-L7_e-9u2ioahHA4oBHy:b-d4x8fp)*

**Comment by petermattis** [comment]
> No need to add this to the debug index; it's redundant with the /debug/pprof/heap link that is already there.

Well, this does allow you to grab a heap profile from a remote node, but I agree that it isn't terribly important to add to the debug index.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23843#-:-L7_eL-WuRIkqneaBYTR:bcnr2k1)*

**Comment by bdarnell** [comment]
Yeah, probably.

**Pull request merged**
