### PR TITLE
kvserver: do not allow lease transfers to replicas in `StateSnapshot`

### LINKED ISSUE #61604: kvserver: lease transferred to uninitialized follower
**Describe the problem**

In https://github.com/cockroachdb/cockroach/issues/61541#issuecomment-792670508, we saw that a range with an uninitialized follower transferred the lease to that uninitialized follower, leading to the range becoming unavailable until the follower caught up. This indicates a hole in our safety mechanisms.

**To Reproduce**

Unclear, but the test in #61541 definitely achieved it.

**Expected behavior**

**Additional data / screenshots**

**Environment:**

https://github.com/cockroachdb/cockroach/commits/b703e663da8ededaee2e28fc39a24e3880ae54cf

**Additional context**

It looks like aggressive changes in range size can lead to temporary (but substantial) unavailability. 

gz#9425

### PR DESCRIPTION
**Pull request by aayushshah15**
In some roachtest failures(#61541, for example) we've seen disruptive
effects from a range's lease being cooperatively transferred to a
follower replica that was either uninitialized or in need of a snapshot.

As of the time of this change, our default cluster settings make it such
that a snapshot would take ~64 seconds to transfer. This means that, if
our lease rebalancing heuristics (via either the replicate queue or the
store rebalancer) happen to make a decision to transfer a range lease to
a lagging follower during an unfortunate window of time (i.e. when the
follower is in need of a snapshot), we would be wedging all traffic on
that range until this follower applies this snapshot and then applies
the lease.

This commit prevents this behavior by rejecting lease transfers to replicas
that the leader (usually the leaseholder) knows are in need of a snapshot.

Resolves #61604

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63507)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @andreimatei)

___
*[pkg/kv/kvserver/batcheval/cmd_lease_transfer.go, line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63507#-MYgWV1pBN7jFHVn63C7:-MYgWV1pBN7jFHVn63C8:bhi8j01) ([raw file](https://github.com/cockroachdb/cockroach/blob/6699dd3d8e6c9cf1db150bab0bc410bb5f6ca587/pkg/kv/kvserver/batcheval/cmd_lease_transfer.go#L55)):*
> ```Go
> }
> 
> var errTransferLeaseToStateSnapshot = errors.Errorf("cannot transfer lease to replica in need of a snapshot")
> ```

Does kvnemesis hit this under stress and with a high rate of rebalancing + lease transfers?
___
*[pkg/kv/kvserver/batcheval/cmd_lease_transfer.go, line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63507#-MYgVjlC6yruvPjdzhQR:-MYgVjlC6yruvPjdzhQS:b-s1uh4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/6699dd3d8e6c9cf1db150bab0bc410bb5f6ca587/pkg/kv/kvserver/batcheval/cmd_lease_transfer.go#L90)):*
> ```Go
> 	}
> 
> 	if raftProgressTracker := cArgs.EvalCtx.GetProgress(); raftProgressTracker != nil {
> ```

Let's give this a comment, explaining the purpose of this check and that it is best-effort and only performed if the leaseholder also happens to be the leader.
___
*[pkg/kv/kvserver/batcheval/eval_context.go, line 102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63507#-MYgVBaW8W3Ucr5IwROD:-MYgVBaW8W3Ucr5IwROE:b7j6qvn) ([raw file](https://github.com/cockroachdb/cockroach/blob/6699dd3d8e6c9cf1db150bab0bc410bb5f6ca587/pkg/kv/kvserver/batcheval/eval_context.go#L102)):*
> ```Go
> 	GetRangeInfo(context.Context) roachpb.RangeInfo
> 
> 	// GetProgress returns this replica's raft progress tracker.
> ```

`GetProgress` is pretty ambiguous. What "progress" are we talking about? How about `GetRaftProgress`?
___
*[pkg/kv/kvserver/batcheval/eval_context.go, line 102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63507#-MYgVT4r6j09Aqp-2fy3:-MYgVT4r6j09Aqp-2fy4:bowjh4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/6699dd3d8e6c9cf1db150bab0bc410bb5f6ca587/pkg/kv/kvserver/batcheval/eval_context.go#L102)):*
> ```Go
> 	GetRangeInfo(context.Context) roachpb.RangeInfo
> 
> 	// GetProgress returns this replica's raft progress tracker.
> ```

What do you think about exposing the entire `RaftStatus()` method here? It seems more generally useful and allows us to be more explicit about that fact that the check you are adding is best-effort and only run if the leaseholder happens to also be the leader.

**Review by andreimatei — APPROVED** [review]
looks good to me, but a test would be bomb :) Ideally a unit test for `TransferLease` but I don't know if that's doable without a full cluster.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63507#-:-MZ-znK_AUbJ1447-X1r:b-bfa04d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_eval_context_span.go, line 217 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63507#-MZ-zgno1v95UtcN3vam:-MZ-zgno1v95UtcN3van:bxxra2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d8fa944c1f03b65ae0c1c62ff3b99b33e5c3200/pkg/kv/kvserver/replica_eval_context_span.go#L217)):*
> ```Go
> // GetProgress is part of the EvalContext interface.
> func (rec SpanSetReplicaEvalContext) RaftStatus() *raft.Status {
> return rec.i.RaftStatus()
> ```

I think this is missing a tab :P
___
*[pkg/kv/kvserver/batcheval/eval_context.go, line 102 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63507#-MZ-zYU02tpukcPO2k8o:-MZ-zYU02tpukcPO2k8p:b105k36) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d8fa944c1f03b65ae0c1c62ff3b99b33e5c3200/pkg/kv/kvserver/batcheval/eval_context.go#L102)):*
> ```Go
> 	GetRangeInfo(context.Context) roachpb.RangeInfo
> 
> 	// RaftStatus returns this replica's raft status tracker.
> ```

maybe add some comments here about what a leader sees vs what a follower sees?

**Comment by aayushshah15** [comment]
>looks good to me, but a test would be bomb :)

The super aggressive log truncation is currently making the test flake, but I did add a test for it. Am I misunderstanding you?

**Review by andreimatei — APPROVED** [review]
I just missed it; reviewable fail.

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63507#-:-MZ03PgU5ufKMIP8u4YY:b6yxvlh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @nvanbenschoten)

___
*[pkg/kv/kvserver/client_lease_test.go, line 289 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63507#-MZ02n3pDdrc4n2JvwAI:-MZ02n3pDdrc4n2JvwAJ:bbugno5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d8fa944c1f03b65ae0c1c62ff3b99b33e5c3200/pkg/kv/kvserver/client_lease_test.go#L289)):*
> ```Go
> 		ReplicationMode: base.ReplicationManual,
> 		ServerArgs: base.TestServerArgs{
> 			// Encourage very aggressive log truncations.
> ```

tell me why. Isn't this redundant with `MustForceRaftLogScanAndProcess` ?
___
*[pkg/kv/kvserver/client_lease_test.go, line 334 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63507#-MZ035xg9Mjyy92o3jxR:-MZ035xg9Mjyy92o3jxS:b-m0wvz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d8fa944c1f03b65ae0c1c62ff3b99b33e5c3200/pkg/kv/kvserver/client_lease_test.go#L334)):*
> ```Go
> 		progress := leaseholderStore.RaftStatus(scratchDesc.RangeID).Progress
> 		if progress == nil {
> 			return errors.Errorf("expected leaseholder to be collocated with the leader")
> ```

nit: these error don't tell me if they're expected until they eventually go away, or if they're never expected. If they are expected for a while, consider rephrasing as `leaseholder not yet collocated with the leader`.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63507)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvserver/client_lease_test.go, line 289 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63507#-MZ02n3pDdrc4n2JvwAI:-MZ4cp4z0t7KKpj19ynV:b-f6tmsj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d8fa944c1f03b65ae0c1c62ff3b99b33e5c3200/pkg/kv/kvserver/client_lease_test.go#L289)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

tell me why. Isn't this redundant with `MustForceRaftLogScanAndProcess` ?
</blockquote></details>

You're right, this wasn't needed.
___
*[pkg/kv/kvserver/client_lease_test.go, line 334 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63507#-MZ035xg9Mjyy92o3jxR:-MZ4d6S9D49mr6OvmNAH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d8fa944c1f03b65ae0c1c62ff3b99b33e5c3200/pkg/kv/kvserver/client_lease_test.go#L334)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: these error don't tell me if they're expected until they eventually go away, or if they're never expected. If they are expected for a while, consider rephrasing as `leaseholder not yet collocated with the leader`.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_eval_context_span.go, line 217 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63507#-MZ-zgno1v95UtcN3vam:-MZ4d9PlDwY0fw_Lksd_:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d8fa944c1f03b65ae0c1c62ff3b99b33e5c3200/pkg/kv/kvserver/replica_eval_context_span.go#L217)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think this is missing a tab :P
</blockquote></details>

Fixed.
___
*[pkg/kv/kvserver/batcheval/cmd_lease_transfer.go, line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63507#-MYgVjlC6yruvPjdzhQR:-MZ4dBD2Eb_WMSG-3ofc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6699dd3d8e6c9cf1db150bab0bc410bb5f6ca587/pkg/kv/kvserver/batcheval/cmd_lease_transfer.go#L90)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's give this a comment, explaining the purpose of this check and that it is best-effort and only performed if the leaseholder also happens to be the leader.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/batcheval/eval_context.go, line 102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63507#-MYgVT4r6j09Aqp-2fy3:-MZ4dIP23C5O6CRpK781:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6699dd3d8e6c9cf1db150bab0bc410bb5f6ca587/pkg/kv/kvserver/batcheval/eval_context.go#L102)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What do you think about exposing the entire `RaftStatus()` method here? It seems more generally useful and allows us to be more explicit about that fact that the check you are adding is best-effort and only run if the leaseholder happens to also be the leader.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/batcheval/eval_context.go, line 102 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63507#-MZ-zYU02tpukcPO2k8o:-MZ4dJ9_CgBI79IsBYQP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d8fa944c1f03b65ae0c1c62ff3b99b33e5c3200/pkg/kv/kvserver/batcheval/eval_context.go#L102)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

maybe add some comments here about what a leader sees vs what a follower sees?
</blockquote></details>

Done.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63507)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvserver/batcheval/cmd_lease_transfer.go, line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63507#-MYgWV1pBN7jFHVn63C7:-MZ4zz5x3m-FLkwDo2ws:b-w9kddw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6699dd3d8e6c9cf1db150bab0bc410bb5f6ca587/pkg/kv/kvserver/batcheval/cmd_lease_transfer.go#L55)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does kvnemesis hit this under stress and with a high rate of rebalancing + lease transfers?
</blockquote></details>

I had a hard time hitting it with the 16MB `COCKROACH_RAFT_LOG_TRUNCATION_THRESHOLD` but with something like 1MB I can get `kvnemesis` to hit this reasonably quickly.

```
 error applying x.TransferLeaseOperation(ctx, /Table/50/"e5f12ee7", 7) // cannot transfer lease to replica in need of a snapshot
```

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r3, 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63507#-:-MZEtRQ5D8yPz0MBjm55:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @nvanbenschoten)

**Comment by nvanbenschoten** [comment]
One change we could make to harden the protection here is to only allow a leaseholder to transfer its lease away if it is also the leader. However, that still is inherently racy because a leader doesn't immediately know that it needs to send a snapshot to a follower in need. So then we could change the condition from rejecting lease transfers to replicas in `StateSnapshot` to only allowing lease transfers to replicas in `StateReplicate`.

But we would need to be careful that doing so doesn't introduce an undesirable cyclical dependency between lease transfers and raft leaders. Those almost always have subtle and unexpected effects - just ask @andreimatei.

And this will all _still_ be a little racy if we don't ensure lease transfer and log trunation are properly synchronized.

**Comment by nvanbenschoten** [comment]
> So then we could change the condition from rejecting lease transfers to replicas in `StateSnapshot` to only allowing lease transfers to replicas in `StateReplicate`.

This actually seems like a targeted improvement to this PR that incurs very little additional risk. What do you think Aayush?

**Comment by aayushshah15** [comment]
>This actually seems like a targeted improvement to this PR that incurs very little additional risk. What do you think Aayush?

Makes sense, I made the change. 

The test added in this PR ended up being a little flakey because the raft leader doesn't learn about the present state of a follower until it receives a `MsgAppResp` from it. I've updated the test to account for this.

**Comment by aayushshah15** [comment]
@nvanbenschoten, I'd like your take on the following:

I'm not super sure about the approach implemented by this PR anymore. It makes `AdminRelocateRange` flakey (and thus, its callers like `EXPERIMENTAL_RELOCATE ... `) because `AdminRelocateRange` attempts to transfer the range lease right after a rebalance operation. Often, what ends up happening is that the leader has the lease target in `StateSnapshot` until it receives _some_ kind of raft message response from this potential lease target (which might take up to a heartbeat interval unless theres traffic on the range). This makes `AdminRelocateRange` fail to transfer the lease (which can fail the entire thing if the lease transfer was required to remove the current leaseholder).

- We can simply add some kind of re-try logic [here](https://github.com/cockroachdb/cockroach/blob/295338b6073c642751f656eccce93b08d55bf856/pkg/kv/kvserver/replica_command.go#L2737-L2750) and that will "solve" this issue, but I'm not sure how we feel about that.

- Another possibility is that we don't reject anything at the command evaluation level but instead have the allocator / store-rebalancer be cognizant of not transferring leases to replicas that the leader knows are not in `StateReplicate`. 

What do you think?

**Comment by aayushshah15** [comment]
>I think it would help to spell out each of the places that attempt to transfer
leases and discuss what will happen in each case if they run into this new
error.

There's three places where we initiate lease transfers:
1. via the `replicateQueue`
2. via the `StoreRebalancer`
3. via `AdminRelocateRange` (used by the merge queue, store-rebalancer, and by `EXPERIMENTAL_RELOCATE`)

If 1 & 2 run into this new error, they will log an error and move on. The
replicateQueue will re-consider the replica in the next scanner cycle, and the
`StoreRebalancer` might reconsider the replica after about a minute or so. 

For (3), `AdminRelocateRange` will try to do lease transfers for 2 reasons: If
the current leaseholder needs to be removed or in order to move the lease to
the first voting replica supplied to `AdminRelocateRange` (this is part of its
contract). If it gets this error, it will return an error to its client without
rolling any of its completed relocations back. 

So, I dont believe we're risking thrashing of any sort under any circumstance. 
I do think adding a retry logic in `AdminTransferLease` or even in `AdminRelocateRange`
is a little fraught because it feels hard to reason about the consequences of adding 
non-deterministic delays to something like this. Additionally, a raft heartbeat 
interval is ~1s based on our defaults, which is quite long (and it doesn't account
for replication lag).  

I'm going try a new patch that teaches the replicateQueue and `StoreRebalancer`
to not initiate lease transfers to replicas in need of snapshots. It should be 
a fair bit clearer and a much more reasonable backport candidate.

**Comment by aayushshah15** [comment]
Closing in favor of https://github.com/cockroachdb/cockroach/pull/69696

**Pull request closed without merging**
