### PR TITLE
sql: make sequence integer bound consistent with `default_int_size`

### LINKED ISSUE #84554: sql: sequence integer bounds do not correspond to `default_int_size`
**Describe the problem**

```
root@:26257/mydb> SET default_int_size=4;
SET

root@:26257/mydb> CREATE SEQUENCE baz START 2 INCREMENT 5;
CREATE SEQUENCE

root@:26257/mydb> select * from pg_sequence where seqrelid = 'baz'::regclass;
  seqrelid | seqtypid | seqstart | seqincrement |       seqmax        | seqmin | seqcache | seqcycle
-----------+----------+----------+--------------+---------------------+--------+----------+-----------
       108 |       20 |        2 |            5 | 9223372036854775807 |      1 |        1 |  false
(1 row)

```

The `seqmax` is `9223372036854775807`, which is out of the upper bound of `int4` (`2147483647`). 

**Environment:**
 - CockroachDB CCL v22.1.3

Jira issue: CRDB-17731

### PR DESCRIPTION
**Pull request by ZhouXing19**
This PR is based on https://github.com/cockroachdb/cockroach/pull/84034. 
Please just look at the 2nd commit. I'll rebase this PR once #84034 is merged.

Previously, the default bounds of sequence are always`math.MaxInt64` 
or `math.MinInt64` (depending on the sequence's order). This
can be inconsistent with the cluster setting `default_int_size`. This commit
is to fix it.

fixes #84554

Release note (bug fix): make sequence integer bound consistent with the
cluster setting `default_int_size`.

Release justification: fix a bug of sequence integer bound

### CODE REVIEW

**Comment by ZhouXing19** [comment]
Note to myself: do we need a migration for this?

**Review by ajwerner — COMMENTED** [review]
> Note to myself: do we need a migration for this?

What would the migration do? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84555#-:-N8Okzsx8iRh6r2Wz1PU:b-6axgi)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by rafiss — COMMENTED** [review]
this seems like it lgtm after rebasing

**Comment by ZhouXing19** [comment]
> > Note to myself: do we need a migration for this?
> 
> What would the migration do?
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84555#-:-N8Okzsx8iRh6r2Wz1PU:b-6axgi)_ status: :shipit: complete! 0 of 0 LGTMs obtained

nvm, I misunderstood. I thought we needed to reset the existing sequences' min and max values, but it doesn't seem needed.

**Comment by ZhouXing19** [comment]
Rebased and it passed the CI. RFAL, thanks!

**Review by rafiss — CHANGES_REQUESTED** [review]
just a small nit!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84555#-:-N8arG1970zRIiz1qY29:b-qr5ur5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)

___
*[`pkg/sql/information_schema.go` line 486 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/84555#-N8aqXHg052ZcPn4b170:-N8aqXHg052ZcPn4b171:b-q5wzej) ([raw file](https://github.com/cockroachdb/cockroach/blob/45198c948930d664ed87d6702223ef9c94f76970/pkg/sql/information_schema.go#L486)):*
> ```Go
> 				identityMax := tree.DNull
> 				identityMin := tree.DNull
> 				generatedAsIdentitySeqOpt, err := column.GetGeneratedAsIdentitySequenceOption(p.SessionData().DefaultIntSize)
> ```

in this case, i think we should not use the session variable, and should instead inspect the int size from the column type. e.g. pass in `column..GetType().Width()`

otherwise, the result shown in `information_schema.columns` would depend on the session var.

```
CREATE TABLE t (id1 INT GENERATED BY DEFAULT AS IDENTITY);

select identity_maximum from information_schema.columns where table_name = 't' and column_name='id1';

set default_int_size = 4;

select identity_maximum from information_schema.columns where table_name = 't' and column_name='id1';
```

we'd want the two `select`s to return the same value

**Comment by ZhouXing19** [comment]
> in this case, i think we should not use the session variable, and should instead inspect the int size from the column type. e.g. pass in `column..GetType().Width()`

Makes sense. Made the change and updated the tests.

**Review by rafiss — APPROVED** [review]
lgtm, nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84555#-:-N9XXn6x-Ht331VDeoKy:b-up05t5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)

**Comment by ZhouXing19** [comment]
TFTR!
bors r=rafiss

**Pull request merged**
