### PR TITLE
raft: add no-op MsgFortifyLeader and MsgFortifyLeaderResp 

### PR DESCRIPTION
**Pull request by arulajmani**
See individual commits

----

This commit adds two new messages to raft -- MsgFortifyLeader and
MsgFortifyLeaderResp. A candidate attempts to fortify its leadership
term after winning an election. It does so by broadcasting a
MsgFortifyLeader to all followers.

Currently, the handling of MsgFortify is a no-op; requests are trivially
rejected. In subsequent patches, we'll hook into store liveness and
correctly respond.

Informs https://github.com/cockroachdb/cockroach/issues/125261

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 14 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128426)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/raft.go` line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-O3f3hO-1ppBpt63qxmu:-O3f3hO-1ppBpt63qxmv:b-yd8f6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1ac6e28487b2acea0706dbd2c805d1528387bd/pkg/kv/kvserver/raft.go#L29)):*
> ```Go
> 
> // maxRaftMsgType is the maximum value in the raft.MessageType enum.
> const maxRaftMsgType = raftpb.MsgFortifyLeaderResp
> ```

Based on the test failures, it looks like we'll need to do something with `RaftRcvdMessages`. Either we assign fake metrics or we just address https://github.com/cockroachdb/cockroach/issues/124498 immediately. It's probably easiest to just add the real metrics right now, like we did in the prototype.
___
*[`pkg/kv/kvserver/replica_store_liveness.go` line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-O3f438V-skmu04SHLQu:-O3f438W2RdJ5L-25Djl:ba8s4rg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1ac6e28487b2acea0706dbd2c805d1528387bd/pkg/kv/kvserver/replica_store_liveness.go#L45)):*
> ```Go
> 		return 0, false
> 	}
> 	if r.store.storeLiveness == nil {
> ```

Should we also have this case in `SupportFrom`?
___
*[`pkg/raft/raft.go` line 676 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-O3f7vBpBmpyzCCqJtRz:-O3f7vBpBmpyzCCqJtS-:b798ekf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1ac6e28487b2acea0706dbd2c805d1528387bd/pkg/raft/raft.go#L676)):*
> ```Go
> }
> 
> // sendFortify sends a fortification RPC to the supplied follower.
> ```

nit: `s/supplied follower/given peer/` to mirror the language on `sendHeartbeat`.
___
*[`pkg/raft/raft.go` line 708 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-O3f7ET66EBqDjkdgWrY:-O3f7ET66EBqDjkdgWrZ:b-kszo9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1ac6e28487b2acea0706dbd2c805d1528387bd/pkg/raft/raft.go#L708)):*
> including the leader itself

Are there other cases where a leader `r.send`s a message to itself? There are certainly cases where a leader `Step`s a message to itself, but I'm not sure how this will behave.

EDIT: never mind, I see the TODO above. When we get to that, we should make sure whatever we're doing is consistent with how other broadcasts work, like `MsgApp`.
___
*[`pkg/raft/raft.go` line 1649 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-O3f4bZc07BpcPHN1o8w:-O3f4bZd2CkBHXVOKbWD:ba9tf61) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1ac6e28487b2acea0706dbd2c805d1528387bd/pkg/raft/raft.go#L1649)):*
> ```Go
> 				r.becomeLeader()
> 				r.bcastAppend()
> 				r.bcastFortify()
> ```

It shouldn't matter, but consider calling `bcastFortify` before `bcastAppend` so that the fortify messages go out ahead of the append messages. Conceptually, you can think of fortifying as part of "completing the leader election", while broadcasting the empty entry is part of "beginning log replication", so it feels consistent to switch the order.
___
*[`pkg/raft/raft.go` line 1658 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-O3f5lJ8-kvjDT5m29Iq:-O3f5lJ8-kvjDT5m29Ir:b-69ixcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1ac6e28487b2acea0706dbd2c805d1528387bd/pkg/raft/raft.go#L1658)):*
> ```Go
> 	case pb.MsgTimeoutNow:
> 		r.logger.Debugf("%x [term %d state %v] ignored MsgTimeoutNow from %x", r.id, r.Term, r.state, m.From)
> 	case pb.MsgFortifyLeader:
> ```

nit: no strong feelings, but in this function and in `stepFollower`, there seem to be two classes of messages, those that come from the leader and those that don't. You can tell by the `// always m.Term == r.Term` comments. What do you think about moving this right below `MsgSnap` in both functions?
___
*[`pkg/raft/raft.go` line 2125 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-O3f6HJQAJEE7H_1h8qe:-O3f6HJQAJEE7H_1h8qf:bifshsj) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1ac6e28487b2acea0706dbd2c805d1528387bd/pkg/raft/raft.go#L2125)):*
> ```Go
> // runtimeAssert panics with the supplied message if the condition does not hold
> // true.
> func runtimeAssert(condition bool, msg string) {
> ```

Out of curiosity, why the "runtime" prefix?

We could move this to `util.go`, next to `assertConfStatesEquivalent` and follow it's lead about accepting a `Logger`.
___
*[`pkg/raft/util.go` line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-O3f3JejB7ioFL_aRyY9:-O3f3JejB7ioFL_aRyYA:b-l9ame9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7bbceb1163e01124c5967195c4a4d000afb4c69/pkg/raft/util.go#L42)):*
> ```Go
> 	pb.MsgStorageApply:      true,
> 	pb.MsgStorageApplyResp:  true,
> 	pb.MsgForgetLeader:      true,
> ```

We step `MsgForgetLeader` in `forgetLeaderLocked`. Isn't this going to break that by returning a `ErrStepLocalMsg`?
___
*[`pkg/raft/raftpb/raft.proto` line 65 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-O3f4AlB-RU9q1lUvs0K:-O3f4AlB-RU9q1lUvs0L:bl1jn9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1ac6e28487b2acea0706dbd2c805d1528387bd/pkg/raft/raftpb/raft.proto#L65)):*
> ```proto
>   MsgStorageApplyResp  = 22;
>   MsgForgetLeader      = 23;
>   MsgFortifyLeader = 24;
> ```

nit: want to align the numbers with all of the other messages?

**Review by arulajmani — COMMENTED** [review]
RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-:-O3iTPSq32Mr8a-KRhoK:bb72pd0)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/raft.go` line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-O3f3hO-1ppBpt63qxmu:-O3iSfI3Bx-vJ0FfUTxG:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1ac6e28487b2acea0706dbd2c805d1528387bd/pkg/kv/kvserver/raft.go#L29)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Based on the test failures, it looks like we'll need to do something with `RaftRcvdMessages`. Either we assign fake metrics or we just address https://github.com/cockroachdb/cockroach/issues/124498 immediately. It's probably easiest to just add the real metrics right now, like we did in the prototype.
</blockquote></details>

Done. 
___
*[`pkg/raft/raft.go` line 708 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-O3f7ET66EBqDjkdgWrY:-O3iFL6tEYCBS36n8HUM:b-j08pgw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1ac6e28487b2acea0706dbd2c805d1528387bd/pkg/raft/raft.go#L708)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> including the leader itself

Are there other cases where a leader `r.send`s a message to itself? There are certainly cases where a leader `Step`s a message to itself, but I'm not sure how this will behave.

EDIT: never mind, I see the TODO above. When we get to that, we should make sure whatever we're doing is consistent with how other broadcasts work, like `MsgApp`.
</blockquote></details>

We definitely don't want to `r.send` the message to ourselves here. I was imaging we'd do something similar to the prototype, where we handle this special case  in `sendFortify` above. I like that a bit more instead of adding the special case here (like `bcastHeartbeat` and `bcastAppend`), but we no strong feelings -- we can talk about it when we get to the next PR. 
___
*[`pkg/raft/raft.go` line 1649 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-O3f4bZc07BpcPHN1o8w:-O3iFlh98qGeiTePcuv2:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1ac6e28487b2acea0706dbd2c805d1528387bd/pkg/raft/raft.go#L1649)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It shouldn't matter, but consider calling `bcastFortify` before `bcastAppend` so that the fortify messages go out ahead of the append messages. Conceptually, you can think of fortifying as part of "completing the leader election", while broadcasting the empty entry is part of "beginning log replication", so it feels consistent to switch the order.
</blockquote></details>

Done. 
___
*[`pkg/raft/raft.go` line 1658 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-O3f5lJ8-kvjDT5m29Iq:-O3iG3qc5PTsLTHdkD9t:bkft9k3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1ac6e28487b2acea0706dbd2c805d1528387bd/pkg/raft/raft.go#L1658)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: no strong feelings, but in this function and in `stepFollower`, there seem to be two classes of messages, those that come from the leader and those that don't. You can tell by the `// always m.Term == r.Term` comments. What do you think about moving this right below `MsgSnap` in both functions?
</blockquote></details>

Agreed. Done. 
___
*[`pkg/raft/raft.go` line 2125 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-O3f6HJQAJEE7H_1h8qe:-O3iHrKF9Soi-1i6i4Ja:bp89crn) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1ac6e28487b2acea0706dbd2c805d1528387bd/pkg/raft/raft.go#L2125)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Out of curiosity, why the "runtime" prefix?

We could move this to `util.go`, next to `assertConfStatesEquivalent` and follow it's lead about accepting a `Logger`.
</blockquote></details>

It's because some of the tests import a package called `assert` ("github.com/stretchr/testify/assert"). I've moved it to `util` and called it `Assert`. The public bit is unfortunate, but I think it's better than calling it `runtimeAssert` or `assertCondition`. 
___
*[`pkg/raft/util.go` line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-O3f3JejB7ioFL_aRyY9:-O3iH1399TUkEqjQjMNK:bcb9to7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7bbceb1163e01124c5967195c4a4d000afb4c69/pkg/raft/util.go#L42)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We step `MsgForgetLeader` in `forgetLeaderLocked`. Isn't this going to break that by returning a `ErrStepLocalMsg`?
</blockquote></details>

Good catch. I misunderstood what "local" meant in this context; fixed.
___
*[`pkg/raft/raftpb/raft.proto` line 65 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-O3f4AlB-RU9q1lUvs0K:-O3iHFrgBjzab8x5Hr-K:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1ac6e28487b2acea0706dbd2c805d1528387bd/pkg/raft/raftpb/raft.proto#L65)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: want to align the numbers with all of the other messages?
</blockquote></details>

Done. 
___
*[`pkg/kv/kvserver/replica_store_liveness.go` line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-O3f438V-skmu04SHLQu:-O3iEMBpBkaPCTNG96BJ:biosl7e) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1ac6e28487b2acea0706dbd2c805d1528387bd/pkg/kv/kvserver/replica_store_liveness.go#L45)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we also have this case in `SupportFrom`?
</blockquote></details>

We should, but I'm actually going to revert it for now -- it doesn't belong in this commit. I initially had it when I was making use of `StoreLiveness` in the implementation of `handleMsgFortify`; we're stubbing it out now, so we don't need this change.

**Review by nvb — COMMENTED** [review]
Should be good to go after one more round.

> Reviewed 16 of 16 files at r4, 1 of 1 files at r5, 17 of 17 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-:-O3ifASjBo0pSeCI0xx2:bkdiy0c)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/raft/raft.go` line 676 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-O3f7vBpBmpyzCCqJtRz:-O3ieFIi-xAbVGw8JTwp:b-flo8ak) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1ac6e28487b2acea0706dbd2c805d1528387bd/pkg/raft/raft.go#L676)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: `s/supplied follower/given peer/` to mirror the language on `sendHeartbeat`.
</blockquote></details>

No love for this suggestion? My thinking is that by using different language, readers now need to ask whether the wording difference is meaningful or not. In this case it's not, so might as well make their life easier.

I guess that's especially true because we accept `to == r.id`, so the peer may not even be a follower.
___
*[`pkg/raft/raft.go` line 708 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-O3f7ET66EBqDjkdgWrY:-O3iebWJ7w_5ZTzjaz1U:betogny) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1ac6e28487b2acea0706dbd2c805d1528387bd/pkg/raft/raft.go#L708)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

We definitely don't want to `r.send` the message to ourselves here. I was imaging we'd do something similar to the prototype, where we handle this special case  in `sendFortify` above. I like that a bit more instead of adding the special case here (like `bcastHeartbeat` and `bcastAppend`), but we no strong feelings -- we can talk about it when we get to the next PR.
</blockquote></details>

Sounds good. We can decide later.
___
*[`pkg/raft/raft.go` line 1649 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-O3f4bZc07BpcPHN1o8w:-O3if-AM25cGEr47GYg0:bjdnl5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1ac6e28487b2acea0706dbd2c805d1528387bd/pkg/raft/raft.go#L1649)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think you'll need to regen some of the datadriven tests after this change.
___
*[`pkg/raft/raft.go` line 2125 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-O3f6HJQAJEE7H_1h8qe:-O3iehrT5cQ7nwiVZDWQ:b-5lf0pp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1ac6e28487b2acea0706dbd2c805d1528387bd/pkg/raft/raft.go#L2125)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

It's because some of the tests import a package called `assert` ("github.com/stretchr/testify/assert"). I've moved it to `util` and called it `Assert`. The public bit is unfortunate, but I think it's better than calling it `runtimeAssert` or `assertCondition`.
</blockquote></details>

I don't think we want exported `Assert` because then that becomes part of the exported interface of `pkg/raft`. If `assert` doesn't work, then I'm +1 on going back to `runtimeAssert` or `assertTrue`.
___
*[`pkg/raft/util_test.go` line 99 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-O3ie35Q7J1sxuV46vYC:-O3ie35Q7J1sxuV46vYD:b-b0z1gd) ([raw file](https://github.com/cockroachdb/cockroach/blob/99e36b19d2689ecb3a5550d386f7814ef2a1e09a/pkg/raft/util_test.go#L99)):*
> ```Go
> 		{pb.MsgStorageApply, true},
> 		{pb.MsgStorageApplyResp, true},
> 		{pb.MsgFortifyLeader, false},
> ```

Did we lose the test case for `MsgForgetLeader` in the third commit?

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128426)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/raft/raft.go` line 676 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-O3f7vBpBmpyzCCqJtRz:-O3igids9pxLY_8N3Gp1:bmr81n5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1ac6e28487b2acea0706dbd2c805d1528387bd/pkg/raft/raft.go#L676)):*
Ofc there's love for your suggestions, so much so that I decided to address comments on the last round of reviews twice (ran into some git nonsense). I had this marked as resolved, so ended up missing it when I came back to addressing things a second time around.

> I guess that's especially true because we accept `to == r.id`, so the peer may not even be a follower.

+1.
___
*[`pkg/raft/raft.go` line 1649 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-O3f4bZc07BpcPHN1o8w:-O3ighUe6AHZDaeSDB7g:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1ac6e28487b2acea0706dbd2c805d1528387bd/pkg/raft/raft.go#L1649)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think you'll need to regen some of the datadriven tests after this change.
</blockquote></details>

Done.
___
*[`pkg/raft/raft.go` line 2125 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-O3f6HJQAJEE7H_1h8qe:-O3igQ-35vCPVA1Dpl5g:b-4x06u3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1ac6e28487b2acea0706dbd2c805d1528387bd/pkg/raft/raft.go#L2125)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I don't think we want exported `Assert` because then that becomes part of the exported interface of `pkg/raft`. If `assert` doesn't work, then I'm +1 on going back to `runtimeAssert` or `assertTrue`.
</blockquote></details>

Switched to `assertTrue`.
___
*[`pkg/raft/util_test.go` line 99 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-O3ie35Q7J1sxuV46vYC:-O3igfpkATDkkcdzU6no:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/99e36b19d2689ecb3a5550d386f7814ef2a1e09a/pkg/raft/util_test.go#L99)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did we lose the test case for `MsgForgetLeader` in the third commit?
</blockquote></details>

Fixed.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128426#-:-O3ijGkh8G7wX3IzzjMf:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by arulajmani** [comment]
CI failures look unrelated. TFTR!

bors r=nvanbenschoten

**Review by nvb — APPROVED** [review]
LGTM

**Comment by arulajmani** [comment]
Thanks!

bors r=nvanbenschoten

**Pull request merged**
