### PR TITLE
opt: add execbuilder tests for COALESCE

### PR DESCRIPTION
**Pull request by RaduBerinde**
Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/opt/exec/execbuilder/testdata/scalar, line 367 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23237#-L6T1E_AmQAMFu2TrNQ3:-L6T1E_AmQAMFu2TrNQ4:b-6oqv34) ([raw file](https://github.com/cockroachdb/cockroach/blob/b92e70554fc27e470f2872b7759bece0c2ba1c15/pkg/sql/opt/exec/execbuilder/testdata/scalar#L367)):*
> ```
> 
> exec
> SELECT COALESCE(NULL, NULL)
> ```

All these tests will get folded away by the optimizer once I add constant folding. I think you'd either want to have a flag that disables optimizations, or else switch to using non-constants as args.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23237)*

**Comment by rytaft** [comment]
:lgtm: assuming you address Andy's suggestion

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/exec/execbuilder/testdata/scalar, line 307 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23237#-L6T3agvtyaoEe6MNoD-:-L6T3agvtyaoEe6MNoD0:b-f6dfq5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b92e70554fc27e470f2872b7759bece0c2ba1c15/pkg/sql/opt/exec/execbuilder/testdata/scalar#L307)):*
> ```
> 
> exec-explain
> SELECT COALESCE(1, 2)
> ```

Can you add a test for `COALESCE` with a single value?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23237#-:-L6T3nFtraXGgIiEoKpO:bmzyf35)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/exec/execbuilder/testdata/scalar, line 367 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23237#-L6T1E_AmQAMFu2TrNQ3:-L6T4U1505ahpM1CwBvF:b-t4q6lh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b92e70554fc27e470f2872b7759bece0c2ba1c15/pkg/sql/opt/exec/execbuilder/testdata/scalar#L367)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

All these tests will get folded away by the optimizer once I add constant folding. I think you'd either want to have a flag that disables optimizations, or else switch to using non-constants as args.
</blockquote></details>

I want to do something like `SELECT COALESCE(a, b) FROM (VALUES (1, 2), (3, NULL), (NULL, 4), (NULL, NULL)) AS v(a, b)` but we don't yet support values. I think I will hold off on this PR and implement that first.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23237)*

**Comment by RaduBerinde** [comment]
Closing for now, will open a separate PR implementing exec support for VALUES and adding these tests.

**Pull request closed without merging**
