### PR TITLE
sql: new generic planNode walker + EXPLAIN improvements

### PR DESCRIPTION
**Pull request by knz**
This patch:

- captures the ExplanPlan / explainExprs logic into a new
  multi-purpose (reusable) `planVisitor`.

- adapts the back-reference analysis for view definitions to use this
  new visitor, as well as the (temporary) detection of star expansion.

- adapts the EXPLAIN logic to use this new visitor.

- clarifies the output of EXPLAIN even when INDENT is not specified.

Before:
```
EXPLAIN(VERBOSE) SELECT a, b FROM abc ORDER BY b, c
----
0  select                                                                          (a, b)                 +b
1  nosort                   +b,+c                                                  (a, b)                 +b
2  render/filter            from (test.abc.a, test.abc.b, test.abc.c, test.abc.d)  (a, b, c)              +b,+c,unique
2  render/filter  render 0  test.abc.a
2  render/filter  render 1  test.abc.b
2  render/filter  render 2  test.abc.c
3  scan                     abc@bc ALL                                             (a, b, c, d[omitted])  +b,+c,unique
```

After:

```
EXPLAIN(VERBOSE) SELECT a, b FROM abc ORDER BY b, c
----
0  select                               (a, b)                 +b
1  nosort                               (a, b)                 +b
1                 order     +b,+c
2  render/filter                        (a, b, c)              +b,+c,unique
2                 render 0  test.abc.a
2                 render 1  test.abc.b
2                 render 2  test.abc.c
3  scan                                 (a, b, c, d[omitted])  +b,+c,unique
3                 table     abc@bc
3                 spans     ALL
```

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12553)

### CODE REVIEW

**Comment by knz** [comment]
cc @a-robinson; could you check if what I did to `createViewNode`'s analysis of the query plan seems OK to you?

**Comment by a-robinson** [comment]
The view-related changes in create.go LGTM. I like the new planObserver pattern much better than what was there before!

---

Reviewed 2 of 53 files at r3.
Review status: 2 of 53 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-:-KZcKCYZD3q3l2UV73e3:b-3cwssc)*

**Comment by RaduBerinde** [comment]
This is fantastic stuff. I have some suggestions on how to make the walk code easier to digest.

---

Review status: 2 of 53 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/walk.go, line 37 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZcJwT7OVPkckOWUufV:-KZcJwT7OVPkckOWUufW:b-zbw36o) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2ce1c20816513af138eac9389c5f1dd92810bb7/pkg/sql/walk.go#L37)):*
> ```Go
> 	// node is invoked upon entering a tree node. It can return false to
> 	// stop the recursion at this node.
> 	node(nodeName string, plan planNode) bool
> ```

node and leave should have names with similar structure, I think `enterNode/leaveNode` would be much better

---

*[pkg/sql/walk.go, line 65 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZcKgbIRd3QDRib9fuG:-KZcKgbIRd3QDRib9fuH:blramug) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2ce1c20816513af138eac9389c5f1dd92810bb7/pkg/sql/walk.go#L65)):*
> ```Go
> 	prevName := v.nodeName
> 	defer func() {
> 		v.observer.leave(v.nodeName)
> ```

This is a bit strange because we read this code before any call to `node`. Maybe it would be better to just move these after the `switch`?

---

*[pkg/sql/walk.go, line 69 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZcL058rdbFQosy4CHo:-KZcL058rdbFQosy4CHp:b-t4obb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2ce1c20816513af138eac9389c5f1dd92810bb7/pkg/sql/walk.go#L69)):*
> ```Go
> 	}()
> 
> 	v.nodeName = formatNodeName(plan)
> ```

The only purpose of `v.nodeName` is to be used in the node/attr/etc wrappers without having to pass it, correct? It's not that great to use that state and restore it. Could we instead just define the wrappers as local functions here and have them use a local `nodeName` instead? Or define them on a helper container that stores `v` and `nodeName` (and that container would be a local variable).

---

*[pkg/sql/walk.go, line 101 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZcM5jDHosAIQXQZsKm:-KZcM5jDHosAIQXQZsKn:b-8nn8cj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2ce1c20816513af138eac9389c5f1dd92810bb7/pkg/sql/walk.go#L101)):*
> ```Go
> 
> 	case *valueGenerator:
> 		v.nodeName = "generator"
> ```

Could we move these exceptions inside `formatNodeName` itself? It's not ideal to have the name generation logic in two different places..

Assuming we do that, then we can replace all the `if v.node(plan) {}` with a single call before the switch (and just bail out if we don't recurse). This would make this switch a lot nicer and shorter, and we wouldn't need the `node()` wrapper either.

---

*[pkg/sql/walk.go, line 407 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZcJEMim_F1UySVrPSH:-KZcJEMim_F1UySVrPSI:b-w38mjx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2ce1c20816513af138eac9389c5f1dd92810bb7/pkg/sql/walk.go#L407)):*
> ```Go
> 
> // node wraps observer.node() and provides it with the current node's name.
> func (v *planVisitor) node(plan planNode) bool {
> ```

These functions threw me off because they have the same names with the ones in `planObserver`. Could we give them different names? maybe `observeNode/observeAttr/observeExpr`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-:-KZcNkIoEXh5Oz_t-7mW:b-n08can)*

**Comment by knz** [comment]
Review status: 2 of 53 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/walk.go, line 37 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZcJwT7OVPkckOWUufV:-KZco2gPWqRIoiK-0Ov-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2ce1c20816513af138eac9389c5f1dd92810bb7/pkg/sql/walk.go#L37)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

node and leave should have names with similar structure, I think `enterNode/leaveNode` would be much better
</blockquote></details>

Done.

---

*[pkg/sql/walk.go, line 65 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZcKgbIRd3QDRib9fuG:-KZfcMiwREXXQ6dC_S_1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2ce1c20816513af138eac9389c5f1dd92810bb7/pkg/sql/walk.go#L65)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is a bit strange because we read this code before any call to `node`. Maybe it would be better to just move these after the `switch`?
</blockquote></details>

Done.

---

*[pkg/sql/walk.go, line 69 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZcL058rdbFQosy4CHo:-KZfcN63c-t3Jg2sekSm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2ce1c20816513af138eac9389c5f1dd92810bb7/pkg/sql/walk.go#L69)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The only purpose of `v.nodeName` is to be used in the node/attr/etc wrappers without having to pass it, correct? It's not that great to use that state and restore it. Could we instead just define the wrappers as local functions here and have them use a local `nodeName` instead? Or define them on a helper container that stores `v` and `nodeName` (and that container would be a local variable).
</blockquote></details>

Done.

---

*[pkg/sql/walk.go, line 101 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZcM5jDHosAIQXQZsKm:-KZfcOD_YtOkLz-7AcpB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2ce1c20816513af138eac9389c5f1dd92810bb7/pkg/sql/walk.go#L101)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Could we move these exceptions inside `formatNodeName` itself? It's not ideal to have the name generation logic in two different places..

Assuming we do that, then we can replace all the `if v.node(plan) {}` with a single call before the switch (and just bail out if we don't recurse). This would make this switch a lot nicer and shorter, and we wouldn't need the `node()` wrapper either.
</blockquote></details>

Done.

---

*[pkg/sql/walk.go, line 407 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZcJEMim_F1UySVrPSH:-KZfcPb63qR3ITjgA6lj:blnj5b2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2ce1c20816513af138eac9389c5f1dd92810bb7/pkg/sql/walk.go#L407)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

These functions threw me off because they have the same names with the ones in `planObserver`. Could we give them different names? maybe `observeNode/observeAttr/observeExpr`
</blockquote></details>

I don't think that's an issue any more.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553)*

**Comment by RaduBerinde** [comment]
Thanks! :lgtm_strong: other than the remaining `lv.node()` call

---

Review status: 1 of 53 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/sql/walk.go, line 64 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZfnjmzEn27UxZPT4OD:-KZfnjmzEn27UxZPT4OE:bu0gp9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/620fbf5748542971a0cdcaf0c412818f048f7f85/pkg/sql/walk.go#L64)):*
> ```Go
> 	}
> 
> 	lv, ok := v.prepare(plan)
> ```

s/ok/recurse (`!ok` suggests that we didn't enter the node and thus we shouldn't `leaveNode`)

---

*[pkg/sql/walk.go, line 313 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZfoAiK_t3tj_jSqzqW:-KZfoAiK_t3tj_jSqzqX:bn7z9mk) ([raw file](https://github.com/cockroachdb/cockroach/blob/620fbf5748542971a0cdcaf0c412818f048f7f85/pkg/sql/walk.go#L313)):*
> ```Go
> 
> 	case *createViewNode:
> 		if lv.node(plan) {
> ```

How come we enter the node again? I expected the `.node()` function to be gone altogether.

---

*[pkg/sql/walk.go, line 347 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZfp08WOOZSwGgDGnzA:-KZfp08WOOZSwGgDGnzB:b-z38r11) ([raw file](https://github.com/cockroachdb/cockroach/blob/620fbf5748542971a0cdcaf0c412818f048f7f85/pkg/sql/walk.go#L347)):*
> ```Go
> 
> // attr wraps observer.attr() and provides it with the current node's name.
> func (v *planVisitor) attr(name, value string) {
> ```

[nit] I still think that these three remaining wrappers could be local `func`s, removing the need to store the `nodeName` in the visitor at all. Clearly subjective though so feel free to ignore.

---

*[pkg/sql/walk.go, line 376 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZfoMGEg0K6Sjaea-qE:-KZfoMGEg0K6Sjaea-qF:b-9x3a1n) ([raw file](https://github.com/cockroachdb/cockroach/blob/620fbf5748542971a0cdcaf0c412818f048f7f85/pkg/sql/walk.go#L376)):*
> ```Go
> // node, and queries the observer to determine whether the node should
> // be visiter further.
> func (v *planVisitor) prepare(plan planNode) (planVisitor, bool) {
> ```

[nit] This could be inlined, it might make it easier to follow what's going on (especially with respect to the `leaveNode` call).

---

*[pkg/sql/walk.go, line 377 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZfojyTQ0fYTJY1BcYK:-KZfojyTQ0fYTJY1BcYL:b-jw83hb) ([raw file](https://github.com/cockroachdb/cockroach/blob/620fbf5748542971a0cdcaf0c412818f048f7f85/pkg/sql/walk.go#L377)):*
> ```Go
> // be visiter further.
> func (v *planVisitor) prepare(plan planNode) (planVisitor, bool) {
> 	if plan == nil {
> ```

we already check for this before calling

---

*[pkg/sql/walk.go, line 391 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZflXI3iaBtDaN3H6cx:-KZflXI4-ugaH1DJe8oV:b-1jdwsw) ([raw file](https://github.com/cockroachdb/cockroach/blob/620fbf5748542971a0cdcaf0c412818f048f7f85/pkg/sql/walk.go#L391)):*
> ```Go
> // needed.
> func nodeName(plan planNode) string {
> 	name, ok := planNodeNames[reflect.TypeOf(plan)]
> ```

Are we doing the lookup first just to panic in more cases? Otherwise seems unnecessary to look up in the cases below, we could do the switch first and `return "nullrow" etc

---

*[pkg/sql/walk.go, line 418 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZfm3L2nZ57sKArAxOu:-KZfm3L2nZ57sKArAxOv:b-ermhlp) ([raw file](https://github.com/cockroachdb/cockroach/blob/620fbf5748542971a0cdcaf0c412818f048f7f85/pkg/sql/walk.go#L418)):*
> ```Go
> }
> 
> // planNodeNames is the mapping from node type to strings.  The
> ```

I like this, even if it's more "manual"! Easier to see the strings.

---

*[pkg/sql/walk.go, line 451 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZflzfoI3-edJ3ier5Y:-KZflzfoI3-edJ3ier5Z:b5d6kdi) ([raw file](https://github.com/cockroachdb/cockroach/blob/620fbf5748542971a0cdcaf0c412818f048f7f85/pkg/sql/walk.go#L451)):*
> ```Go
> 	reflect.TypeOf(&updateNode{}):         "update",
> 	reflect.TypeOf(&valueGenerator{}):     "generator",
> 	reflect.TypeOf(&valueGenerator{}):     "generator",
> ```

duplicate

---

*[pkg/sql/walk.go, line 453 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZfm-gnO21aIvWSy86F:-KZfm-gnO21aIvWSy86G:b5d6kdi) ([raw file](https://github.com/cockroachdb/cockroach/blob/620fbf5748542971a0cdcaf0c412818f048f7f85/pkg/sql/walk.go#L453)):*
> ```Go
> 	reflect.TypeOf(&valueGenerator{}):     "generator",
> 	reflect.TypeOf(&valuesNode{}):         "values",
> 	reflect.TypeOf(&valuesNode{}):         "values",
> ```

duplicate

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-:-KZfpaQ5S15iO_nkTLXf:bqhokia)*

**Comment by knz** [comment]
TFYR.

---

Review status: 1 of 53 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/sql/walk.go, line 64 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZfnjmzEn27UxZPT4OD:-KZg2qRtB8eEDw66vkws:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/620fbf5748542971a0cdcaf0c412818f048f7f85/pkg/sql/walk.go#L64)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

s/ok/recurse (`!ok` suggests that we didn't enter the node and thus we shouldn't `leaveNode`)
</blockquote></details>

Done.

---

*[pkg/sql/walk.go, line 313 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZfoAiK_t3tj_jSqzqW:-KZg1rJOaaRfgyTNpz2P:b-jlfz68) ([raw file](https://github.com/cockroachdb/cockroach/blob/620fbf5748542971a0cdcaf0c412818f048f7f85/pkg/sql/walk.go#L313)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

How come we enter the node again? I expected the `.node()` function to be gone altogether.
</blockquote></details>

Yes, that was an oversight.
Exactly the kind of stuff why reviews are useful :)
Thanks for noticing!

---

*[pkg/sql/walk.go, line 347 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZfp08WOOZSwGgDGnzA:-KZg1wcv7GP1CK8_Sq9d:b3ie86b) ([raw file](https://github.com/cockroachdb/cockroach/blob/620fbf5748542971a0cdcaf0c412818f048f7f85/pkg/sql/walk.go#L347)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I still think that these three remaining wrappers could be local `func`s, removing the need to store the `nodeName` in the visitor at all. Clearly subjective though so feel free to ignore.
</blockquote></details>

I try to avoid local functions with a small lifetime because allocating a closure in Go is not cheap.

---

*[pkg/sql/walk.go, line 376 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZfoMGEg0K6Sjaea-qE:-KZg2OUz3u6LD2GeJ2F1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/620fbf5748542971a0cdcaf0c412818f048f7f85/pkg/sql/walk.go#L376)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] This could be inlined, it might make it easier to follow what's going on (especially with respect to the `leaveNode` call).
</blockquote></details>

Done.

---

*[pkg/sql/walk.go, line 377 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZfojyTQ0fYTJY1BcYK:-KZg2OvoFjV_lgIJDcV4:b1hzeoz) ([raw file](https://github.com/cockroachdb/cockroach/blob/620fbf5748542971a0cdcaf0c412818f048f7f85/pkg/sql/walk.go#L377)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

we already check for this before calling
</blockquote></details>

Thanks for noticing!

---

*[pkg/sql/walk.go, line 391 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZflXI3iaBtDaN3H6cx:-KZg2TF1cy2leBVjYBFZ:b-eqmyhq) ([raw file](https://github.com/cockroachdb/cockroach/blob/620fbf5748542971a0cdcaf0c412818f048f7f85/pkg/sql/walk.go#L391)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Are we doing the lookup first just to panic in more cases? Otherwise seems unnecessary to look up in the cases below, we could do the switch first and `return "nullrow" etc
</blockquote></details>

I moved the switch to earlier, that's a good idea.
And yeah the panic was necessary, it's not obvious in the output of EXPLAIN that there's an empty string where a non-empty string was expected.

---

*[pkg/sql/walk.go, line 451 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZflzfoI3-edJ3ier5Y:-KZg2mQQhPfnbQgDkzI8:b-bcoutf) ([raw file](https://github.com/cockroachdb/cockroach/blob/620fbf5748542971a0cdcaf0c412818f048f7f85/pkg/sql/walk.go#L451)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

duplicate
</blockquote></details>

Done.
Yay for reviews :)

---

*[pkg/sql/walk.go, line 453 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZfm-gnO21aIvWSy86F:-KZg2mwTtOcEy3D4vXY6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/620fbf5748542971a0cdcaf0c412818f048f7f85/pkg/sql/walk.go#L453)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

duplicate
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-:-KZg2p0eX9M9x2XXMLt4:b-814ciq)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 1 of 53 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/walk.go, line 347 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-KZfp08WOOZSwGgDGnzA:-KZg8rgZqP1rSzwnAK8i:bxewqo8) ([raw file](https://github.com/cockroachdb/cockroach/blob/620fbf5748542971a0cdcaf0c412818f048f7f85/pkg/sql/walk.go#L347)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I try to avoid local functions with a small lifetime because allocating a closure in Go is not cheap.
</blockquote></details>

There's a time and a place :) Optimizing a handful of allocations for EXPLAIN statements is not worth thinking about.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12553#-:-KZg97yRosAwmJKNkGCf:bnfp4nl)*

**Pull request merged**
