### PR TITLE
sql, insights: record error message for failed stmts

### PR DESCRIPTION
**Pull request by xinhaoz**
### Commit 1 sql: modify HasViewActivityOrViewActivityRedactedRole signature

This commit adds an additional return value to the function
`HasViewActivityOrViewActivityRedactedRole` which returns true if
the user has either `VIEWACTIVITY` or `VIEWACTIVITYREDACTED` roles.

In addition to that, the function will now return a boolean indicating
whether the user is not admin and has the `VIEWACTIVITYREDACTED` role.
This simplifies  areas where we need to redact values based on the
presence of this role, allowing callers to skip an additional role check
for admin and VIEWACTIVITYREDACTED.

Epic: none

Release note: None
### Commit 2 sql, insights: record error message for failed stmts

Part of: #87785.

Previously, the insights subsystem did not keep track of the error messages for failed executions, only the error codes.

This commit  updates the `[cluster|node]_execution_insights` and `[cluster|node]_txn_execution_insights` virtual tables to include a `last_error` column which contains the most recent error message.

Release note (sql change): adds `last_error` column to the `[cluster|node]_execution_insights` and `[cluster|node]_txn_execution_insights` tables which keeps track of the error message for failed executions.

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, 9 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110565)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/ccl/logictestccl/testdata/logic_test/crdb_internal` line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110565#-NeJG3hv7UTtGoX2YqwY:-NeJG3hv7UTtGoX2YqwZ:bnvtq9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e849209c9d39e8fdb5001bdb53c99fa63e7981c/pkg/ccl/logictestccl/testdata/logic_test/crdb_internal#L206)):*
> ```
> tenant_id  capability_name    capability_value
> 1          can_admin_split  true
> 5          can_admin_split  true
> ```

is this intentional? seems unrelated to this PR
___
*[`pkg/sql/sqlstats/insights/integration/insights_test.go` line 209 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110565#-NeJGGed5bxTDM4JEddr:-NeJGGed5bxTDM4JEdds:b-5xilsl) ([raw file](https://github.com/cockroachdb/cockroach/blob/39981673c788ded0f53c21a0c6d6e47103071acc/pkg/sql/sqlstats/insights/integration/insights_test.go#L209)):*
> ```Go
> 
> 	// Create VIEWACTIVITY and VIEWACTIVITYREDACTED users.
> 	//const viewUser = "view_user"
> ```

looks like you need to do some cleanup on these comments

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110565)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @maryliag)

___
*[`pkg/ccl/logictestccl/testdata/logic_test/crdb_internal` line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110565#-NeJG3hv7UTtGoX2YqwY:-NeJw2X94ztcaVtAMXGc:b1rue95) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e849209c9d39e8fdb5001bdb53c99fa63e7981c/pkg/ccl/logictestccl/testdata/logic_test/crdb_internal#L206)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

is this intentional? seems unrelated to this PR
</blockquote></details>

I used --rewrite since I added some columns to the internal tables. Not sure why this part was changed, too. I'll check if removing this change will break the test.
___
*[`pkg/sql/sqlstats/insights/integration/insights_test.go` line 209 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110565#-NeJGGed5bxTDM4JEddr:-NeJw1cn3jZ1fT57kkQE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/39981673c788ded0f53c21a0c6d6e47103071acc/pkg/sql/sqlstats/insights/integration/insights_test.go#L209)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

looks like you need to do some cleanup on these comments
</blockquote></details>

Done.

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, 10 of 11 files at r4, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110565#-:-NeNuxNlAYVD4bxsXFNT:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling)

**Review by j82w — COMMENTED** [review]
> Reviewed 1 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110565)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling, @maryliag, and @xinhaoz)

___
*[`pkg/cli/zip_table_registry.go` line 165 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/110565#-NeO3cLi58SDZyu24QiT:-NeO3cLi58SDZyu24QiU:bnnvboo) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ee97b5fb1957ec2312087e9fc4904f7f9042c31/pkg/cli/zip_table_registry.go#L165)):*
> ```Go
> 			"retries",
> 			"last_retry_reason",
> 			"error_code",
> ```

Shouldn't this be a sensitive column?

**Comment by xinhaoz** [comment]
*[`pkg/cli/zip_table_registry.go` line 165 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/110565#-NeO3cLi58SDZyu24QiT:-Necdvvb4D_eQxe8ld-F:b-d2du4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ee97b5fb1957ec2312087e9fc4904f7f9042c31/pkg/cli/zip_table_registry.go#L165)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Shouldn't this be a sensitive column?
</blockquote></details>

The error code itself doesn't have any sensitive info from what I can tell. Looks like the retry reason was added in a separate commit despite it being listed as sensitive :thinking: . We can take it up with sql-foundations.

**Review by knz — COMMENTED** [review]
> Reviewed 6 of 11 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110565)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ericharmeling, @j82w, @maryliag, and @xinhaoz)

___
*[`pkg/cli/zip_table_registry.go` line 165 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/110565#-NeO3cLi58SDZyu24QiT:-Nehokwo2pzI6rSncRNf:b-7kehg0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ee97b5fb1957ec2312087e9fc4904f7f9042c31/pkg/cli/zip_table_registry.go#L165)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

The error code itself doesn't have any sensitive info from what I can tell. Looks like the retry reason was added in a separate commit despite it being listed as sensitive :thinking: . We can take it up with sql-foundations.
</blockquote></details>

indeed error code is safe.
___
*[`pkg/sql/crdb_internal.go` line 8089 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/110565#-NehosncD__-_VXVKf_6:-NehosncD__-_VXVKf_7:bg29clb) ([raw file](https://github.com/cockroachdb/cockroach/blob/64645a377084ddd5c33d46a7ec01476e5df55a18/pkg/sql/crdb_internal.go#L8089)):*
> ```Go
> 
> 		errorMsg := tree.DNull
> 		if insight.Transaction.LastErrorMsg != "" && shouldRedactError {
> ```

can you store the error in the insight data structure as a `redact.RedactableString` and call `.Redact()` here instead of deleting everything?

**Comment by j82w** [comment]
*[`pkg/cli/zip_table_registry.go` line 165 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/110565#-NeO3cLi58SDZyu24QiT:-Necqtt16J_fa_QRFPSG:b-bzurz4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ee97b5fb1957ec2312087e9fc4904f7f9042c31/pkg/cli/zip_table_registry.go#L165)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

indeed error code is safe.
</blockquote></details>

I was referring to the `last_retry_reason`.  A separate issue can be opened for it.

**Comment by j82w** [comment]
*[`pkg/sql/crdb_internal.go` line 8089 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/110565#-NehosncD__-_VXVKf_6:-Neik61K07K48jWAq4Sq:bfv31jm) ([raw file](https://github.com/cockroachdb/cockroach/blob/64645a377084ddd5c33d46a7ec01476e5df55a18/pkg/sql/crdb_internal.go#L8089)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

can you store the error in the insight data structure as a `redact.RedactableString` and call `.Redact()` here instead of deleting everything?
</blockquote></details>

If it's a redacted string can we add it to the debug zip?

**Comment by knz** [comment]
>If it's a redacted string can we add it to the debug zip?

redactable != redacted

at the point it is still *Redactable* it still contains PII. Once *redacted* it does not.

So debug zip _by default_ can only capture _redacted_ errors.

**Comment by xinhaoz** [comment]
*[`pkg/cli/zip_table_registry.go` line 165 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/110565#-NeO3cLi58SDZyu24QiT:-NejIiUJ2KsCczFid6P7:b-v4sig7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ee97b5fb1957ec2312087e9fc4904f7f9042c31/pkg/cli/zip_table_registry.go#L165)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

I was referring to the `last_retry_reason`.  A separate issue can be opened for it.
</blockquote></details>

Filed https://github.com/cockroachdb/cockroach/issues/110938.
For this PR the last_error has been changed to `last_error_redactable` for both tables. It's redacted for the debug zip and directly for VIEWACTIVITYREDACTED users.

**Review by knz — APPROVED** [review]
Nice tests.

LGTM modulo reverting the change to the logic test with the 'retry' clause.

> Reviewed 1 of 11 files at r5, 11 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110565#-:-NeoHrxk6hJOrDy2SnpX:b16nfii)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ericharmeling, @j82w, and @maryliag)

___
*[`pkg/ccl/logictestccl/testdata/logic_test/crdb_internal` line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110565#-NeJG3hv7UTtGoX2YqwY:-NeoHgXj-cusT851c7pv:b-2e9uk2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e849209c9d39e8fdb5001bdb53c99fa63e7981c/pkg/ccl/logictestccl/testdata/logic_test/crdb_internal#L206)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

I used --rewrite since I added some columns to the internal tables. Not sure why this part was changed, too. I'll check if removing this change will break the test.
</blockquote></details>

Yeah let's revert that. that seems incorrect. Generally "--rewrite" is unsafe/inconsistent with the "retry" clause in logic tests.

**Comment by xinhaoz** [comment]
Thanks for the reviews!
bors r+

**Comment by xinhaoz** [comment]
Oops, mistakenly canceled bc I thought there was a CI issue. TFTR!
bors r+

**Comment by yuzefovich** [comment]
bors timed out, courtesy merge

bors r+

**Pull request merged**
