### PR TITLE
UI Telemetry for Statements

### LINKED ISSUE #45506: ui: add telemetry to statements list page
This issue tracks which new actions we would like to record telemetry for in the Statements list page of the Admin UI.

- [x] Changing sort order (want to see which column and asc vs desc)
- [x] Search (how often is enough, we probably want to scrub out any actual search terms)
- [x] Clicking to paginate (we should track whether the user clicked next, or a specific page number)

As part of the diagnostic bundle/tracing work, we should track:
- [x] Diagnostic bundle activations (capturing high level statement performance information as part of the event is nice, e.g. latency or execution count; we should scrub the actual fingerprint)

### PR DESCRIPTION
**Pull request by nathanstilwell**
fixes cockroachdb/cockroach#45506

- [x] Changing sort order (want to see which column and asc vs desc)
- [x] Search
- [x] Clicking to paginate
- [x] Diagnostic bundle activations (capturing high level statement performance information as part of the event is nice, e.g. latency or execution count; we should scrub the actual fingerprint)

Adding a tracking function to [`analytics.ts`]() to send analytics payloads Segment.io. I begin by adding tracking calls to interesting events on the [Statements]() page of the Admin UI. The events being tracked are as follows,

### Table Sort
This event is fired when the sorting order is changed by clicking a column header on the Statements page. 

statements-sort-order
```
{
  userId: 'ac7aafbc-1a79-4a5b-bc60-c1221cf80e1e'
  event: 'Table Sort',
  properties: {
    columnName: 'Txn Type',
    pagePath: '/statements',
    sortDirection: 'desc',
    tableName: 'statements-table'
  }
}
```

### Search
This event is fired when a the statements are filtered using a search term.

statements-search

```
{
  userId: 'ac7aafbc-1a79-4a5b-bc60-c1221cf80e1e',
  event: 'Search',
  properties: {
    numberOfResults: 17,
    pagePath: '/statements',
    searchTerm: 'system'
  }
}
```

### Paginate
This event is fired when the user interacts with pagination on the statements page.
statements-pagination

```
{
  userId: 'ac7aafbc-1a79-4a5b-bc60-c1221cf80e1e',
  event: 'Paginate',
  properties: {
    pagePath: '/statements/',
    selectedPage: 4
  }
}
```

### Diagnostics Activation
This event it tracked when a user clicks "Activate" on the diagnostics activation modal.
statements-diagnostics-activation

```
{
  userId: 'ac7aafbc-1a79-4a5b-bc60-c1221cf80e1e',
  event: 'Diagnostics Activation',
  properties: {
    fingerprint: 'SELECT blah, blah FROM blah.blah WHERE blah blah blah'
    pagePath: '/statements/'
  }
}
```

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
I'm waiting for PRs to pass TeamCity so I've got time to throw some eyes on this. I know it's not finished yet.

> **I have _Prettier_ turned on, so sorry about all the formatting changes

We should talk about what to do here...would love to standardize on something. We've already had issues with imports moving around in everyone's PRs.

> Release note (<category, see below>): <what> <show> <why>

Revise release note in second commit please.

> Reviewed 4 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45920#-:-M21K9qu2TGtz7uaxFmK:b-8diqbx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nathanstilwell)

___
*[pkg/ui/src/redux/analytics.ts, line 193 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45920#-M21ImSj4hGfAqP8-WUD:-M21ImSj4hGfAqP8-WUE:b-g02rbv) ([raw file](https://github.com/cockroachdb/cockroach/blob/41bd9e384b631121bc2167ddeca235e98a580aaa/pkg/ui/src/redux/analytics.ts#L193)):*
> ```XML
>     const cluster = this.getCluster();
>     const { cluster_id } = cluster;
>     const message = Object.assign({ userId: cluster_id }, msg);
> ```

Just curious if there's a reason you prefer this over`{userId: cluster_id, ...msg}`. Or are they different things?
___
*[pkg/ui/src/views/shared/components/sortabletable/index.tsx, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45920#-M21Iw8dDqoOyrlfacA1:-M21Iw8dDqoOyrlfacA2:b-fau62t) ([raw file](https://github.com/cockroachdb/cockroach/blob/41bd9e384b631121bc2167ddeca235e98a580aaa/pkg/ui/src/views/shared/components/sortabletable/index.tsx#L16)):*
> ```XML
> import isUndefined from 'lodash/isUndefined';
> import times from 'lodash/times';
> ```

I like this alternate import style for lodash! I always feel a little bad about typing `_.`
___
*[pkg/ui/src/views/shared/components/sortabletable/index.tsx, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45920#-M21J7ho6mlyGK_H79hB:-M21J7ho6mlyGK_H79hC:bdqyoq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/41bd9e384b631121bc2167ddeca235e98a580aaa/pkg/ui/src/views/shared/components/sortabletable/index.tsx#L19)):*
> ```XML
> import getHighlightedText from "oss/src/util/highlightedText";
> import { DrawerComponent } from "../drawer";
> import { analytics } from '../../../../redux/analytics';
> ```

The existing style is to import directly from the top level `src/` directory instead of relative paths.
___
*[pkg/ui/src/views/shared/components/sortabletable/index.tsx, line 241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45920#-M21JNsK3xZqDp25tyVO:-M21JNsK3xZqDp25tyVP:b46wspk) ([raw file](https://github.com/cockroachdb/cockroach/blob/41bd9e384b631121bc2167ddeca235e98a580aaa/pkg/ui/src/views/shared/components/sortabletable/index.tsx#L241)):*
> ```XML
> 
>   trackTableSort = (name?: String, col?: SortableColumn, sortSetting?: SortSetting) => {
>     const path = window.location.pathname + window.location.hash;
> ```

:thinking: this might need to get sanitized...
___
*[pkg/ui/src/views/statements/statementsPage.tsx, line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45920#-M21L19kAcPx7GRsvDvC:-M21L19kAcPx7GRsvDvD:b-j8e1re) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f7c806a61ef5961d1d08e588447c14207772914/pkg/ui/src/views/statements/statementsPage.tsx#L96)):*
> ```XML
> 
>   componentDidUpdate = () => {
>     if (this.state.search) {
> ```

I recently added a `componentDidUpdate` handler in the jobs table and I think you might need to take a look at the `prevState` parameter here to see if the search state changed. Otherwise, I think every re-render will send an event if something is typed in the box so you might end up with a lot of duplicates.

**Review by nathanstilwell — COMMENTED** [review]
So I just spent some time fussing with my editor setup around Prettier, and I actually had it disabled. When I tried to enable it, it conflicts in places with the TSLINT configurations we have. So I'm going to walk this all back a bit. I think moving forward we should start instituting the same tools and formatting that we are using in cloud, which would mean switching from tslint to eslint with prettier as a plugin.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45920#-:-M259KeFE5ncYHVHQhtN:b-kafdd3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[pkg/ui/src/redux/analytics.ts, line 193 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45920#-M21ImSj4hGfAqP8-WUD:-M257wjTDo42h2oshb1g:b-tz9p55) ([raw file](https://github.com/cockroachdb/cockroach/blob/41bd9e384b631121bc2167ddeca235e98a580aaa/pkg/ui/src/redux/analytics.ts#L193)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Just curious if there's a reason you prefer this over`{userId: cluster_id, ...msg}`. Or are they different things?
</blockquote></details>

I think it's just old habit. I this case, it would be the same thing.
___
*[pkg/ui/src/views/shared/components/sortabletable/index.tsx, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45920#-M21Iw8dDqoOyrlfacA1:-M258Nrh97Z-1Oy_2Vbu:bqp9v48) ([raw file](https://github.com/cockroachdb/cockroach/blob/41bd9e384b631121bc2167ddeca235e98a580aaa/pkg/ui/src/views/shared/components/sortabletable/index.tsx#L16)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I like this alternate import style for lodash! I always feel a little bad about typing `_.`
</blockquote></details>

I like how explicit it is, and this way we can leverage Webpack tree shaking (someday).
___
*[pkg/ui/src/views/shared/components/sortabletable/index.tsx, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45920#-M21J7ho6mlyGK_H79hB:-M258jHI1F_FbC3EqMLM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/41bd9e384b631121bc2167ddeca235e98a580aaa/pkg/ui/src/views/shared/components/sortabletable/index.tsx#L19)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

The existing style is to import directly from the top level `src/` directory instead of relative paths.
</blockquote></details>

Done.
___
*[pkg/ui/src/views/shared/components/sortabletable/index.tsx, line 241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45920#-M21JNsK3xZqDp25tyVO:-M258pEf4rnDl78tHdPt:b-7768yv) ([raw file](https://github.com/cockroachdb/cockroach/blob/41bd9e384b631121bc2167ddeca235e98a580aaa/pkg/ui/src/views/shared/components/sortabletable/index.tsx#L241)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

:thinking: this might need to get sanitized...
</blockquote></details>

What do you mean specifically?
___
*[pkg/ui/src/views/statements/statementsPage.tsx, line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45920#-M21L19kAcPx7GRsvDvC:-M259CDu6IvKh_heFEGs:b-8x1sdu) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f7c806a61ef5961d1d08e588447c14207772914/pkg/ui/src/views/statements/statementsPage.tsx#L96)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I recently added a `componentDidUpdate` handler in the jobs table and I think you might need to take a look at the `prevState` parameter here to see if the search state changed. Otherwise, I think every re-render will send an event if something is typed in the box so you might end up with a lot of duplicates.
</blockquote></details>

That's a good point. I'll test for that case.

**Review by nathanstilwell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45920)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[pkg/ui/src/redux/analytics.ts, line 193 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45920#-M21ImSj4hGfAqP8-WUD:-M2tQtAq6F-XE9Rav3PI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/41bd9e384b631121bc2167ddeca235e98a580aaa/pkg/ui/src/redux/analytics.ts#L193)):*
<details><summary><i>Previously, nathanstilwell (Nathan Stilwell) wrote…</i></summary><blockquote>

I think it's just old habit. I this case, it would be the same thing.
</blockquote></details>

Done.
___
*[pkg/ui/src/views/statements/statementsPage.tsx, line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45920#-M21L19kAcPx7GRsvDvC:-M2tR87o8H-rhIk5Et_W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f7c806a61ef5961d1d08e588447c14207772914/pkg/ui/src/views/statements/statementsPage.tsx#L96)):*
<details><summary><i>Previously, nathanstilwell (Nathan Stilwell) wrote…</i></summary><blockquote>

That's a good point. I'll test for that case.
</blockquote></details>

Done.

**Review by dhartunian — APPROVED** [review]
:lgtm: :thumbsup:

Thanks, this looks great! I asked @piyush-singh to just confirm on the issue whether search terms and fingerprints should be included as I'm a little confused. Feel free to merge once that's settled.

> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45920#-:-M3hYtJYAFCl1pAIkZbs:bibxu0i)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @nathanstilwell)

___
*[pkg/ui/src/views/shared/components/sortabletable/index.tsx, line 241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45920#-M21JNsK3xZqDp25tyVO:-M3hYS593HeQfQbGNrdO:b-rl24z2) ([raw file](https://github.com/cockroachdb/cockroach/blob/41bd9e384b631121bc2167ddeca235e98a580aaa/pkg/ui/src/views/shared/components/sortabletable/index.tsx#L241)):*
<details><summary><i>Previously, nathanstilwell (Nathan Stilwell) wrote…</i></summary><blockquote>

What do you mean specifically?
</blockquote></details>

nvm I thought the table was name was a sql table, my bad. LGTM
___
*[pkg/ui/src/views/statements/statementsPage.tsx, line 200 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/45920#-M3hToBJ77a5KoDBIQaE:-M3hToBJ77a5KoDBIQaF:bqq28wn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0162ac4bdca633e601a9a94ad523131e431fd270/pkg/ui/src/views/statements/statementsPage.tsx#L200)):*
> ```XML
>       event: "Search",
>       properties: {
>         searchTerm,
> ```

I think `searchTerm` should be removed here. Check the issue text.

**Comment by piyush-singh** [comment]
In favor of excluding search terms for now, I'm okay with keeping the fingerprint though.

**Comment by nathanstilwell** [comment]
bors r=dhartunian

**Pull request merged**
