### PR TITLE
opt: simplify optbuilder arbiter logic

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: add arbiterSet to track arbiter indexes and unique constraints

This commit introduces a `arbiterSet` which can contain both indexes and
unique constraints. The `ForEach` function of this set abstracts the
type of arbiter so that consumers of the set need not be concerned with
the type. This cleans up code that builds expressions for each arbiter.
Note that this will allow further cleanup within `buildInputForUpsert`,
once that function supports partial unique constraints.

Release note: None

#### opt: move left-join building logic to mutation_builder_arbiter.go

This commit move the logic for building `UPSERT` left-joins to
`mutation_builder_arbiter.go`, making it consistent with the structure
of `INSERT ON CONFLICT DO NOTHING` logic. Some duplicate code for
building DistinctOn expressions was also removed - both `UPSERT` and
`INSERT ON CONFLICT DO NOTHING` build essentially the same DistinctOn
expressions.

Some of the code for dealing with `UPSERT` arbiter indexes and arbiter
constraints is still repetitive. This will be cleaned up in a follow-up
commit that adds `UPSERT` support for partial unique constraint
arbiters.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60821#-:-MTyVmE_B-ueo8WwQVz5:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/arbiter_set.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60821#-MTyST7mE4LbfZRa7BP5:-MTyST7mE4LbfZRa7BP6:baho6z1) ([raw file](https://github.com/cockroachdb/cockroach/blob/822fe708012963a4b9728f49b997b1e36eb0c3fd/pkg/sql/opt/optbuilder/arbiter_set.go#L63)):*
> ```Go
> }
> 
> // AddIndex adds an index arbiter to the set.
> ```

update comment
___
*[pkg/sql/opt/optbuilder/insert.go, line 790 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60821#-MTyUKNb36-kyQSWE4-7:-MTyUKNc6zOCt7qkB27P:b-2t7bvt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3e6db7ecd9e6291599dc2480e793f50e17b6d8a/pkg/sql/opt/optbuilder/insert.go#L790)):*
> ```Go
> 		// Record a not-null "canary" column. After the left-join, this will be
> 		// null if no conflict has been detected, or not null otherwise. At
> 		// least one not- null column must exist, since primary key columns are
> ```

[nit] not- null -> not-null
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60821#-MTyT8x75ied-xNNyX_N:-MTyT8x75ied-xNNyX_O:ba7jl1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/822fe708012963a4b9728f49b997b1e36eb0c3fd/pkg/sql/opt/optbuilder/mutation_builder.go#L135)):*
> ```Go
> 	canaryColID opt.ColumnID
> 
> 	// arbiters is the set of indexes and unique constraints that are used to detect conflicts
> ```

[nit] comment should be 80 columns wide
___
*[pkg/sql/opt/optbuilder/mutation_builder_arbiter.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60821#-MTyTHRrEJGnyNN5CuHv:-MTyTHRrEJGnyNN5CuHw:bgseqrf) ([raw file](https://github.com/cockroachdb/cockroach/blob/822fe708012963a4b9728f49b997b1e36eb0c3fd/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L28)):*
> ```Go
> )
> 
> // findArbiters returns a set arbiters for an INSERT ON CONFLICT statement. Both
> ```

a set arbiters -> a set of arbiters
___
*[pkg/sql/opt/optbuilder/mutation_builder_arbiter.go, line 180 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60821#-MTyTWo5BxxKvr8Jbmrm:-MTyTWo5BxxKvr8Jbmrn:b-igr479) ([raw file](https://github.com/cockroachdb/cockroach/blob/822fe708012963a4b9728f49b997b1e36eb0c3fd/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L180)):*
> ```Go
> 	}
> 
> 	// Err if we did not previously return and did not any partial arbiters.
> ```

did not any -> did not find any
___
*[pkg/sql/opt/optbuilder/mutation_builder_arbiter.go, line 274 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60821#-MTyUzeF52PIM4HaK8nq:-MTyUzeF52PIM4HaK8nr:blxljmx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3e6db7ecd9e6291599dc2480e793f50e17b6d8a/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L274)):*
> ```Go
> // columns as the join condition.
> //
> // 	 - conflictOrds is the set of table column ordinals that the arbiter
> ```

[nit] weird spacing in front of this line
___
*[pkg/sql/opt/optbuilder/mutation_builder_arbiter.go, line 364 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60821#-MTyVV0O0K8gQkClYSub:-MTyVV0P68gvv44tpQD8:b-lxdxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3e6db7ecd9e6291599dc2480e793f50e17b6d8a/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L364)):*
> ```Go
> //
> //   - insertColScope contains the columns of the insert rows.
> // 	 - conflictOrds is the set of table column ordinals that the arbiter
> ```

more weird spacing

**Review by mgartner — COMMENTED** [review]
Thanks for the thorough review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60821#-:-MU-lRNH4pMXZ-w5Ia98:bst74u7)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/optbuilder/arbiter_set.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60821#-MTyST7mE4LbfZRa7BP5:-MU-lGi58aWBLyDpPyA1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/822fe708012963a4b9728f49b997b1e36eb0c3fd/pkg/sql/opt/optbuilder/arbiter_set.go#L63)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

update comment
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/insert.go, line 790 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60821#-MTyUKNb36-kyQSWE4-7:-MU-lP-a72SozENVsjP4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3e6db7ecd9e6291599dc2480e793f50e17b6d8a/pkg/sql/opt/optbuilder/insert.go#L790)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] not- null -> not-null
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60821#-MTyT8x75ied-xNNyX_N:-MU-kjEr-ZYnPM90wtdV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/822fe708012963a4b9728f49b997b1e36eb0c3fd/pkg/sql/opt/optbuilder/mutation_builder.go#L135)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] comment should be 80 columns wide
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder_arbiter.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60821#-MTyTHRrEJGnyNN5CuHv:-MU-kq-P-V50oZxGRlZ-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/822fe708012963a4b9728f49b997b1e36eb0c3fd/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L28)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

a set arbiters -> a set of arbiters
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder_arbiter.go, line 180 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60821#-MTyTWo5BxxKvr8Jbmrm:-MU-kw4e5XsWRDPm-bGo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/822fe708012963a4b9728f49b997b1e36eb0c3fd/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L180)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

did not any -> did not find any
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder_arbiter.go, line 274 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60821#-MTyUzeF52PIM4HaK8nq:-MU-l1uvBs8OcxkVhsCs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3e6db7ecd9e6291599dc2480e793f50e17b6d8a/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L274)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] weird spacing in front of this line
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder_arbiter.go, line 364 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60821#-MTyVV0O0K8gQkClYSub:-MU-l8JJ9wJTMZbOyMQ9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3e6db7ecd9e6291599dc2480e793f50e17b6d8a/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L364)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

more weird spacing
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 5 of 5 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60821)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60821#-:-MUAKsbv0Cx9B9r6tPhR:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
