### PR TITLE
sql/schemachanger: copy splits and scatter indexes being backfilled

### LINKED ISSUE #114996: schemachanger: split and scatter before index is being backfilled or written to
In https://github.com/cockroachdb/cockroach/pull/94703, we added split and scatter calls in declarative schema changer when creating a new index (primary, secondary, or temporary) before it's backfilled or written to. One question is [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/schemachanger/scexec/exec_deferred_mutation.go#L206-L208) which further leads to [this block of code](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/index_split_scatter.go#L53-L62). The code begs a few questions:
1. Why is temporary index excluded from being splitted and scattered?
2. Why do we only call split without following up with a scatter call?
3. Why do we choose to only split at the beginning of the index span? Is it enough?

@kvoli and I recently sit down to look at the behavior of `ALTER TABLE ADD COLUMN` in the scale cluster that sparked those questions. It seems 
1. temporary index shouldn't be excluded (and it won't hurt too much to also split&scatter on temporary indexes) bc in a real cluster the concurrent writes that go to a temporary index (when new primary index is being backfilled) can be also large; 
2. it's just wrong to call only split but not scatter afterwards; 
3. for temporary indexes, we don't know how large its index span will be (it will be whatever concurrent writes are). Understandably, we don't know where and how many time to split, so it is fair to just split it once at the beginning of index span (better than not splitting at all at least).

cc @fqazi we'd like to hear your thoughts too

Jira issue: CRDB-33830

Epic CRDB-37763

### PR DESCRIPTION
**Pull request by rafiss**
When adding any index (including temporary indexes), the new index will
copy some of the split points from an index with matching keys. This uses a
similar algorithm to what TRUNCATE already does: The number of splits
that are copied is proportional to the number of nodes, and the splits
are sampled uniformly from the source index's splits.

fixes https://github.com/cockroachdb/cockroach/issues/114996
Release note (performance improvement): Schema changes that cause a
data backfill, such as adding a non-nullable column or changing the
primary key, now will split and scatter the temporary indexes used to
perform the change. This reduces the chance of causing a write hotspot
that can slow down foreground traffic.

### CODE REVIEW

**Comment by rafiss** [comment]
testing with schemachange/during/tpcc: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14468019?hideProblemsFromDependencies=false&hideTestsFromDependencies=false

**Comment by rafiss** [comment]
Some results from this PR: 

I'm running the KV workload with:
```
roachprod create -n10 rafi-split-scatter --gce-zones us-east1-c
roachprod put rafi-split-scatter:1-9 artifacts/cockroach
roachprod put rafi-split-scatter:10 artifacts/workload
roachprod start rafi-split-scatter:1-9

roachprod run rafi-split-scatter:10 -- ./workload run kv --max-rate 0 --read-percent 20 --duration=5h --batch 1 --min-block-bytes 1 --max-block-bytes 2 {pgurl:1-9} --concurrency 16 --min-conns 10
```

Once the table got up to 40 GB with ~70 ranges, I ran 2 backfill-causing schema change on one of the nodes:
```
-- when the cluster was running with this PR
ALTER TABLE kv.public.kv ADD COLUMN new INT NOT NULL DEFAULT 0;

-- when the cluster was running without this PR
ALTER TABLE kv.public.kv ADD COLUMN new2 INT NOT NULL DEFAULT 0;
```

The results with this PR are on the left of the time period in these graphs, and the results without this PR are on the right.

image
image
image
image

THE CPU, IOPS, and flushes are all more evenly spread out when we use this PR, but there are more concentrated spikes in the chart when we weren't using this PR.

**Review by fqazi — APPROVED** [review]
Great work. Just one minor issue for this one

> Reviewed 20 of 20 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120736#-:-NvD8CEKCYSJYVClDhFS:bad9g80)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom, @michae2, @msbutler, and @rafiss)

___
*[`pkg/sql/index_split_scatter.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120736#-NvD77fc0U6aDxIqhcvj:-NvD77fc0U6aDxIqhcvk:b95ijsj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0d6b0d2e37353267f88790a035783dee235456b/pkg/sql/index_split_scatter.go#L119)):*
> ```Go
> 			continue
> 		}
> 		if descpb.IndexID(foundIndexID) != copySplitsFromIndexID {
> ```

Do we want to skip this entire loop if the copySplitsFromIndexID isn't set.
___
*[`pkg/sql/index_split_scatter.go` line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120736#-NvD7Wzm-r5-S0hZcPw8:-NvD7Wzm-r5-S0hZcPw9:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0d6b0d2e37353267f88790a035783dee235456b/pkg/sql/index_split_scatter.go#L160)):*
> ```Go
> 		sp := splitPoints[idx]
> 
> 		// Jitter the expiration time by 20% up or down from the default.
> ```

Nice!

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120736)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom, @fqazi, @michae2, and @msbutler)

___
*[`pkg/sql/index_split_scatter.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120736#-NvD77fc0U6aDxIqhcvj:-NvsQDWDEwtMdW-En-Xh:bvqj1n0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0d6b0d2e37353267f88790a035783dee235456b/pkg/sql/index_split_scatter.go#L119)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Do we want to skip this entire loop if the copySplitsFromIndexID isn't set.
</blockquote></details>

yeah i added that above: `for rangeDescIterator.Valid() && copySplitsFromIndexID != 0`

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
