### PR TITLE
deps: bump go-libedit

### PR DESCRIPTION
**Pull request by knz**
Requested by @benesch in https://github.com/cockroachdb/cockroach/pull/32623#issuecomment-504284857, needed for bug fixes.

Release note: None

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
:lgtm: down with sigtramp

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38345#-:-LhucvaW1m_97DxJc3vV:bkdzhnk)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @benesch)

**Comment by benesch** [comment]
Thanks @knz! Unfortunately it looks like we need to also teach the go-libedit .gitignore file to ignore zcgo_flags files (https://github.com/knz/go-libedit/pull/18). I wrestled with dep for a while but couldn't figure out any other solution. (Without that PR, `git status` is forever dirtied by the zcgo_flags file we generate into the vendored copy of go-libedit.)

**Comment by knz** [comment]
rebasing pr

**Comment by benesch** [comment]
Ok, so once knz/go-libedit#18 is in place, we need to bump this PR to include that commit and also apply this diff to Gopkg.toml:

```
diff --git a/Gopkg.toml b/Gopkg.toml
index 456f6c329f..d2455825e8 100644
--- a/Gopkg.toml
+++ b/Gopkg.toml
@@ -25,6 +25,12 @@ ignored = [
   "github.com/google/protobuf/examples/tutorial",
 ]
 
+noverify = [
+  # We generate Go code with cgo configuration flags into go-libedit in order
+  # to link against our own version of libedit.
+  "github.com/knz/go-libedit/unix"
+]
+
 # The collation tables must never change.
 [[constraint]]
   name = "golang.org/x/text"
```

That ensures that we can generate zcgo_flags files into our vendored copy of go-libedit without causing Git to complain about untracked files, or causing dep to complain that there are extra files in go-libedit.

**Comment by benesch** [comment]
Woohoo, thanks @knz! Note that you'll need to run `bin/dep ensure` once more after adding the `noverify` stanza to Gopkg.toml, since that stanza causes `ensure` to generate a slightly different Gopkg.lock.

**Comment by knz** [comment]
done

**Comment by benesch** [comment]
Scratch that bit about needing to re-run `dep ensure`. My patch was just wrong. This is the actual update to Gopkg.toml that's needed:

```diff
diff --git a/Gopkg.toml b/Gopkg.toml
index 456f6c329f..7bb3d5483e 100644
--- a/Gopkg.toml
+++ b/Gopkg.toml
@@ -25,6 +25,12 @@ ignored = [
   "github.com/google/protobuf/examples/tutorial",
 ]
 
+noverify = [
+  # We generate Go code with cgo configuration flags into go-libedit in order
+  # to link against our own version of libedit.
+  "github.com/knz/go-libedit"
+]
+
 # The collation tables must never change.
 [[constraint]]
   name = "golang.org/x/text"

```

**Comment by knz** [comment]
wait how is that different?

**Comment by benesch** [comment]
It doesn't have the trailing `/unix` in the package name. I guess `noverify` takes only "project roots", not packages. This is all so confusing.

Anyway, not to worry! I still have the commit bit here apparently so I was able to update the patch accordingly. 🤞

**Review by benesch — APPROVED** [review]
LGTM if it LGTY, @knz!

**Comment by knz** [comment]
let's fly!

bors r+

**Pull request merged**
