### PR TITLE
sql, client: don't modify txn.mu.Proto without holding the txn.mu

### PR DESCRIPTION
**Pull request by andreimatei**

### CODE REVIEW

**Comment by tamird** [comment]
Does this fix https://github.com/cockroachdb/cockroach/issues/15565 ?

**Comment by andreimatei** [comment]
No, I don't think that guy is related. But it's on my list to look at.

**Comment by petermattis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/internal/client/txn.go, line 1076 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15790#-KjetxW6FuIB3zwy9W5y:-KjetxW6FuIB3zwy9W5z:b-ubpyko) ([raw file](https://github.com/cockroachdb/cockroach/blob/0040c598670677b930ef832211d3598b13f712fe/pkg/internal/client/txn.go#L1076)):*
> ```Go
> }
> 
> // SetFixedTimestamp makes the transaction runs in an unusual way - Timestamp
> ```

`s/runs/run/g`

I'm not quite sure what "Fixed" is referring to here. Perhaps `SetAsOfTimestamp` or `SetHistoricalTimestamp`. 

---

*[pkg/internal/client/txn.go, line 1081 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15790#-KjetYu7JG87DZ-GbnlN:-KjetYu7JG87DZ-GbnlO:b-6lxatf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0040c598670677b930ef832211d3598b13f712fe/pkg/internal/client/txn.go#L1081)):*
> ```Go
> //
> // This is only supposed to support AS OF SYSTEM TIME queries, which are
> // supposed to run this on every retry.
> ```

Lot of supposition in this sentence. Can you make it more concrete?

---

*[pkg/internal/client/txn.go, line 1093 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15790#-KjetaYvydLHdC7G_KKS:-KjetaYwzPYh5cWN4m_3:bw5ikug) ([raw file](https://github.com/cockroachdb/cockroach/blob/0040c598670677b930ef832211d3598b13f712fe/pkg/internal/client/txn.go#L1093)):*
> ```Go
> 	// not strictly needed. However, it doesn't do anything incorrect and it will
> 	// possibly find problems if things change in the future, so it is left in.
> 	txn.UpdateDeadlineMaybe(ts)
> ```

I'm not familiar with the locking here. Why doesn't `UpdateDeadlineMaybe` need to lock? I see that `Txn.deadline` is not part of `Txn.mu`, but that isn't quite satisfactory given the locking needed for the `txn.mu.Proto` timestamp fields.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15790)*

**Comment by andreimatei** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/internal/client/txn.go, line 1076 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15790#-KjetxW6FuIB3zwy9W5y:-KjhvpjAUrUmbn0dwiVB:b-ygzgo6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0040c598670677b930ef832211d3598b13f712fe/pkg/internal/client/txn.go#L1076)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/runs/run/g`

I'm not quite sure what "Fixed" is referring to here. Perhaps `SetAsOfTimestamp` or `SetHistoricalTimestamp`. 
</blockquote></details>

I don't know what a good name is... I like `Fixed` more than your suggestions, and I've added a sentence tying "fixed" to "transaction can't be pushed to a different timestamp".

---

*[pkg/internal/client/txn.go, line 1081 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15790#-KjetYu7JG87DZ-GbnlN:-Kjhw4Wja7Tz-PbWSPaQ:b6eh0u8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0040c598670677b930ef832211d3598b13f712fe/pkg/internal/client/txn.go#L1081)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Lot of supposition in this sentence. Can you make it more concrete?
</blockquote></details>

made the tone more assertive

---

*[pkg/internal/client/txn.go, line 1093 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15790#-KjetaYvydLHdC7G_KKS:-Kjhw7ASgkgNvxgm9lat:bl23hdl) ([raw file](https://github.com/cockroachdb/cockroach/blob/0040c598670677b930ef832211d3598b13f712fe/pkg/internal/client/txn.go#L1093)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm not familiar with the locking here. Why doesn't `UpdateDeadlineMaybe` need to lock? I see that `Txn.deadline` is not part of `Txn.mu`, but that isn't quite satisfactory given the locking needed for the `txn.mu.Proto` timestamp fields.
</blockquote></details>

Prefixing with "i'm just a monkey here, not my code": I did consider moving the deadline under `mu` while moving this code, but I think it's OK without it. This deadline I think is supposed to change only at times where the caller has exclusive access to the `Txn`: i.e. there's a single writer - at the beginning of a txn, and hopefully the reader (`txn.Commit()` and friends) cannot be called concurrently with this beginning of transactions.
Whether or not the `Proto` needs synchronized access in this case I'm less sure of, but that field is under `mu` for different code paths, so I think it's good to always access it under `mu`.

Multi-thread access to a `Txn` object is a new thing; in the interest of a design emerging, I'd like to resist putting all the fields under `mu`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15790)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/internal/client/txn.go, line 1093 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15790#-KjetaYvydLHdC7G_KKS:-Kji5TgPhzrRUfpRpKdx:b-n0tnbj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0040c598670677b930ef832211d3598b13f712fe/pkg/internal/client/txn.go#L1093)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Prefixing with "i'm just a monkey here, not my code": I did consider moving the deadline under `mu` while moving this code, but I think it's OK without it. This deadline I think is supposed to change only at times where the caller has exclusive access to the `Txn`: i.e. there's a single writer - at the beginning of a txn, and hopefully the reader (`txn.Commit()` and friends) cannot be called concurrently with this beginning of transactions.
Whether or not the `Proto` needs synchronized access in this case I'm less sure of, but that field is under `mu` for different code paths, so I think it's good to always access it under `mu`.

Multi-thread access to a `Txn` object is a new thing; in the interest of a design emerging, I'd like to resist putting all the fields under `mu`.
</blockquote></details>

Ok, I can see that this doesn't actually change the prior locking behavior and I agree with not wanting to put all the fields under `mu`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15790#-:-Kji5jIbCqFQU9yuPkOz:bnfp4nl)*

**Pull request merged**
