### PR TITLE
docs: fix generated description for system visible cluster setting

### PR DESCRIPTION
**Pull request by souravcrl**
The description for system visible cluster settings is incorrect as it wrongly implies that these settings are read only for self-hosted and read-write for rest. The correct framing should be read-only for serverless and read-write for rest as was mentioned in this comment:
https://reviewable.io/reviews/cockroachdb/cockroach/122105#-NvX1p9i9-rmLsCXP6lv

fixes None
Epic None

Release note(ops change): We are updating generated doc descriptions for system visible cluster settings to reflect these are read-only for serverless and read-write for rest

### CODE REVIEW

**Review by bdarnell — COMMENTED** [review]
I would make it `Dedicated/Self-hosted (read-write), Serverless (read-only)` to emphasize that serverless is different than the others. (use a semicolon if comma is significant to the class-labels flag?) That does take up a little more space but this table cell is already wrapping to multiple lines anyway (even in a 2000-pixel wide window!)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124028#-:-Nxm2nfU5YltigLrFxus:b-ztos9)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained

**Review by souravcrl — COMMENTED** [review]
updated the description string to have semi-colon separated values. Also made the cmd argument multiline for readability.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124028#-:-NxnLBGA7kLnZ_j0gdqF:b-a3zl9q)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained

**Review by bdarnell — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124028)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @souravcrl)

**Pull request merged**
