### PR TITLE
log: separate per-channel filtering on a single sink

### PR DESCRIPTION
**Pull request by knz**
All commits but the last from #70045.
Needed for #69701 and various other improvements.

Prior to this patch, the filtering on severity levels was defined
sink-wide. For example, setting `filter: WARNING` on the stderr sink
would filter every message at INFO severity away from that sink.

In practice, we have discovered however that users would prefer the
ability to mix and match different levels from different channels on
the same sink. For example, we would like to see the default crdb log
contain STORAGE messages at severity WARNING or higher, mixed with
INFO messages from other channels.

Likewise, users have expressed interest in creating monitoring
channels that contain all messages from the HEALTH channel but also
ERROR messages from other channels.

To achieve this, this commit creates infrastructure that defines
filtering separately for each channel on a single sink.

Release justification: low risk, high benefit changes to existing functionality

Release note (cli change): It is now possible to mix and match
severity filters for different channels on a single log sink.
For example:

```
file-groups:
   monitoring:
     channels: {WARNING: [OPS, STORAGE], INFO: HEALTH}
```

This defines a single file sink "monitoring" which captures
all messages from the HEALTH channel, and only messages
at severity WARNING or higher from the OPS and STORAGE channels.

Another example:

```
file-groups:
   default:
      channels: {INFO: all except STORAGE, WARNING: STORAGE}
```

This captures all messages on all channels except the STORAGE channel,
plus the messages at severity WARNING or higher from STORAGE.

Note: the previous syntax remains supported. When 'channel' is
specified without explicit severities, the 'filter' attribute is used
as default (like previously).

### CODE REVIEW

**Comment by knz** [comment]
@rauchenstein this PR would appreciate an expedited review cycle, as we'll want this merged before next Tuesday when the branch is cut.

**Comment by knz** [comment]
As discussed with @ajwerner and @andreimatei  - this PR is infrastructure only and will be followed by another subsequent PR that actually will change the defaults to make the STORAGE logs more palatable.

**Comment by knz** [comment]
note to self: @andreimatei requests to invert the channel list and the severity around the colon. 
This seems to be possible as per YAML spec. https://play.golang.org/p/fhR6gkV-CZG

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69715)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rauchenstein)

___
*[pkg/util/log/clog.go, line 347 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69715#-MjUGFVW3JO5Q7yQjb5V:-MjUGFVW3JO5Q7yQjb5W:biuaunm) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e9295391846024f1bb518a1600d05a988dc7fc7/pkg/util/log/clog.go#L347)):*
> @rauchenstein Maybe threshold should be of a new type with a type-safe accessor instead of casting channels to int everywhere?

Good idea. Done.
___
*[pkg/util/log/logconfig/config.go, line 741 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69715#-MjUMgCnE7OQ_xsuKVZP:-MjUMgCnE7OQ_xsuKVZQ:b-bjv2ea) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e9295391846024f1bb518a1600d05a988dc7fc7/pkg/util/log/logconfig/config.go#L741)):*
> @rauchenstein Confusing name -- makes a new ChannelFilters, doesn't filter channels. NewChannelFilters?

I went for `SelectChannels`.
___
*[pkg/util/log/logconfig/config.go, line 782 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69715#-MjUMpGc7ntYJCBf2DTo:-MjUMpGc7ntYJCBf2DTp:bka459t) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e9295391846024f1bb518a1600d05a988dc7fc7/pkg/util/log/logconfig/config.go#L782)):*
> @rauchenstein 
> I'd suggest decomposing this into
>
> - a part which does the map transpose, filling out AllChannels and ChannelFilters (which can happen at unmashalling time, so that the presence of Severity_UNKNOWN is the ONLY way a freshly unmashalled value is invalid rather than having unset fields), and
> - a function that can generally remap one severity to another, which we'd use to remap UNKNOWN to the default (and remove the entries from AllChannels if remapping to NONE).

Done. Note that we can't do the thing at unmarshalling time, because many tests construct a ChannelFilters structurally instead of Yaml.

> As is, I also don't like the name "Update". "Validate" is probably better.

Done.
___
*[pkg/util/log/logconfig/config.go, line 842 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69715#-MjUKDd29r8kpI9xLU26:-MjUKDd29r8kpI9xLU27:bptqsxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e9295391846024f1bb518a1600d05a988dc7fc7/pkg/util/log/logconfig/config.go#L842)):*
> @rauchenstein I sort of expected AllFiltered to return a list of all the filtered channels. Perhaps IsAllFiltered or AreAllFiltered or FiltersAll.

Renamed to `noChannelsSelected`
___
*[pkg/util/log/logconfig/validate.go, line 189 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69715#-MjUKlQL38HZMPKY2Yk-:-MjUKlQL38HZMPKY2Yk0:b-12bqwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e9295391846024f1bb518a1600d05a988dc7fc7/pkg/util/log/logconfig/validate.go#L189)):*
> @rauchenstein fluent -> http

Done

**Comment by knz** [comment]
Following up on a separate comment from @andreimatei 
"it seems a bit unnatural that the mapping would be specified with severity first, channel second, e.g. `info: storage` instead of `storage: info`"

Unfortunately we can't swap this, because of YAML map semantics. The input syntax `{[HEALTH, STORAGE]: INFO}` is not valid YAML.

**Review by rauchenstein — CHANGES_REQUESTED** [review]
> Reviewed 31 of 31 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69715)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/util/log/clog.go, line 174 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/69715#-MjWhSPcCyAt5Ay4dP8f:-MjWhSPcCyAt5Ay4dP8g:bb33kf3) ([raw file](https://github.com/cockroachdb/cockroach/blob/da65ff34685252c5cfbc9e3e447fb994bf5f2dbf/pkg/util/log/clog.go#L174)):*
> ```Go
> }
> 
> // setLocked modifies the threshold for the given channel, assuming
> ```

The "Locked" in these names is presumably a remnant from a previous iteration.
___
*[pkg/util/log/flags.go, line 390 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/69715#-MjWjqC90UszEQE-n4Wd:-MjWjqC90UszEQE-n4We:b-vgce3k) ([raw file](https://github.com/cockroachdb/cockroach/blob/da65ff34685252c5cfbc9e3e447fb994bf5f2dbf/pkg/util/log/flags.go#L390)):*
> ```Go
> 
> // applyFilters applies the channel filters to a sinkInfo.
> func (l *sinkInfo) applyFilters(chs logconfig.ChannelFilters) {
> ```

There isn't a case where we applyFilters more than once, is there?  It would probably be cleaner to replace
```
l.threshold.setAll(severity.NONE)
...
l.threshold.applyFilters(c.Channels)
```
with
```
l.threshold = newThreshold(chs.ChannelFilters)
```
___
*[pkg/util/log/test_log_scope.go, line 195 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/69715#-MjWnEhM392RDYphJ1mL:-MjWnEhM392RDYphJ1mM:bbfby2y) ([raw file](https://github.com/cockroachdb/cockroach/blob/da65ff34685252c5cfbc9e3e447fb994bf5f2dbf/pkg/util/log/test_log_scope.go#L195)):*
> ```Go
> 		testConfig.Sinks.Stderr.Filter = severity.INFO
> 		// Ensure all channels go to stderr.
> 		testConfig.Sinks.Stderr.Channels = logconfig.SelectChannels(logconfig.SelectAllChannels()...)
> ```

The falsely implied relationship between these functions made me chuckle.  Maybe some renaming of the old function is in order.
SelectAllChannels -> AllChannels
___
*[pkg/util/log/logconfig/config.go, line 741 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69715#-MjUMgCnE7OQ_xsuKVZP:-MjWu5Uu1abdn1Fugyz2:b-tqe9fp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e9295391846024f1bb518a1600d05a988dc7fc7/pkg/util/log/logconfig/config.go#L741)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

> @rauchenstein Confusing name -- makes a new ChannelFilters, doesn't filter channels. NewChannelFilters?

I went for `SelectChannels`.
</blockquote></details>

Reads well to me.  :-)
___
*[pkg/util/log/logconfig/config.go, line 588 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/69715#-MjWqxcW5DpkjgzWPWAM:-MjWqxcW5DpkjgzWPWAN:b-jaur9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/da65ff34685252c5cfbc9e3e447fb994bf5f2dbf/pkg/util/log/logconfig/config.go#L588)):*
> ```Go
> 	}
> 
> 	if errors.HasType(err, (*yaml.TypeError)(nil)) {
> ```

Consider
```
if err := fn(&a); err != nil {
   ...
} else if !errors.HasType(err, (*yaml.TypeError)(nil)) {
    return err
}
```
to separate error handling of the first case from normal flow of the second case.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69715)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rauchenstein)

___
*[pkg/util/log/clog.go, line 174 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/69715#-MjWhSPcCyAt5Ay4dP8f:-MjZeeDo-fUJwwlJAHCo:b-t8fyss) ([raw file](https://github.com/cockroachdb/cockroach/blob/da65ff34685252c5cfbc9e3e447fb994bf5f2dbf/pkg/util/log/clog.go#L174)):*
<details><summary><i>Previously, rauchenstein wrote…</i></summary><blockquote>

The "Locked" in these names is presumably a remnant from a previous iteration.
</blockquote></details>

Oops. Fixed.
___
*[pkg/util/log/flags.go, line 390 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/69715#-MjWjqC90UszEQE-n4Wd:-MjZetBN1krP0Bh6aIy4:b-3bt7br) ([raw file](https://github.com/cockroachdb/cockroach/blob/da65ff34685252c5cfbc9e3e447fb994bf5f2dbf/pkg/util/log/flags.go#L390)):*
<details><summary><i>Previously, rauchenstein wrote…</i></summary><blockquote>

There isn't a case where we applyFilters more than once, is there?  It would probably be cleaner to replace
```
l.threshold.setAll(severity.NONE)
...
l.threshold.applyFilters(c.Channels)
```
with
```
l.threshold = newThreshold(chs.ChannelFilters)
```
</blockquote></details>

No in fact the two things are called in different places, and not always together.
___
*[pkg/util/log/test_log_scope.go, line 195 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/69715#-MjWnEhM392RDYphJ1mL:-MjZew7RDjJu14Ywd5Gb:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/da65ff34685252c5cfbc9e3e447fb994bf5f2dbf/pkg/util/log/test_log_scope.go#L195)):*
<details><summary><i>Previously, rauchenstein wrote…</i></summary><blockquote>

The falsely implied relationship between these functions made me chuckle.  Maybe some renaming of the old function is in order.
SelectAllChannels -> AllChannels
</blockquote></details>

Good idea. Done.
___
*[pkg/util/log/logconfig/config.go, line 588 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/69715#-MjWqxcW5DpkjgzWPWAM:-MjZfXiECm6dAoj9SYkz:bdd4vz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/da65ff34685252c5cfbc9e3e447fb994bf5f2dbf/pkg/util/log/logconfig/config.go#L588)):*
<details><summary><i>Previously, rauchenstein wrote…</i></summary><blockquote>

Consider
```
if err := fn(&a); err != nil {
   ...
} else if !errors.HasType(err, (*yaml.TypeError)(nil)) {
    return err
}
```
to separate error handling of the first case from normal flow of the second case.
</blockquote></details>

Good idea. done.

**Review by rauchenstein — APPROVED** [review]
But {HEALTH: INFO, STORAGE: INFO} is.  I assume you want the lists for ergonomics.

> Reviewed 9 of 9 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69715#-:-Mj_JycSEtrYm8Ikn6gb:b-tgkn44)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Comment by knz** [comment]
> But {HEALTH: INFO, STORAGE: INFO} is. I assume you want the lists for ergonomics.

yes, especially given that a common case will be `all except health, storage` and similar.

**Comment by knz** [comment]
TFYR!

bors r=rauchenstein

**Pull request merged**
