### PR TITLE
roachpb: Prohibit access to NoopRequest.Header()

### LINKED ISSUE #11195: kv: next() and prev() should ignore NoopRequests
Extracted from https://github.com/cockroachdb/cockroach/issues/10427#issuecomment-262431117

`kv.next()` and `kv.prev()` attempt to find the next key in a batch to seek to. However, they don't skip NoopRequests (whose keys are empty) so it ends up iterating through all range descriptors in order. 

This is the second recent issue where NoopRequests and their dummy keys are processed as if they were real (#10470), so we should probably audit all the places where we iterate over the requests of a batch to ensure NoopRequests are being handled correctly.

### PR DESCRIPTION
**Pull request by bdarnell**
Add explicit type checks to guard against inappropriate access. 

Fixes #11195

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/11919)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 7 of 7 files at r1, 4 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[pkg/kv/batch_test.go, line 102 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/11919#-KY38TFAojKfTsRXO2b3:-KY38TFBBKMM8A2rZlcI:b6fm8a2) ([raw file](https://github.com/cockroachdb/cockroach/blob/241bcbd70826440cf46e91075e77ff475db79799/pkg/kv/batch_test.go#L102)):*
> ```Go
> 			t.Errorf("got %s, expected %s", rk, leftKey)
> 		}
> 		rk, err = prev(ba, leftKey)
> ```

looks like something got truncated here, and there's a spurious empty line below

---

*[pkg/roachpb/gen_batch.go, line 54 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11919#-KY37hz_r4iGy6eFJbiR:-KY37hz_r4iGy6eFJbiS:b-hzejcf) ([raw file](https://github.com/cockroachdb/cockroach/blob/55703351628fbc928eac1a3e19ecdbc8814dfb68/pkg/roachpb/gen_batch.go#L54)):*
> ```Go
> 		field := t.Field(i).Name
> 		info.name = field
> 		// The ResponseUnion fields match those in RequestUnion, with one exception.
> ```

"the following exceptions:" so the next person doesn't have to edit this again

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11919)*

**Comment by tamird** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11919#-:-KY3Zkgle-NizMFM4LlX:bnfp4nl)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[pkg/kv/batch_test.go, line 102 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/11919#-KY38TFAojKfTsRXO2b3:-KY6oH591igAN3ovagNQ:b-vf92z1) ([raw file](https://github.com/cockroachdb/cockroach/blob/241bcbd70826440cf46e91075e77ff475db79799/pkg/kv/batch_test.go#L102)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

looks like something got truncated here, and there's a spurious empty line below
</blockquote></details>

Removed this line and the blank one

---

*[pkg/roachpb/gen_batch.go, line 54 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11919#-KY37hz_r4iGy6eFJbiR:-KY6oFYX9jmv1bKUvKiP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/55703351628fbc928eac1a3e19ecdbc8814dfb68/pkg/roachpb/gen_batch.go#L54)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

"the following exceptions:" so the next person doesn't have to edit this again
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11919)*

**Comment by tamird** [comment]
Reviewed 1 of 7 files at r4, 4 of 4 files at r5, 2 of 2 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11919)*

**Pull request merged**
