### PR TITLE
gossip: export Gossip status to debug ui

### LINKED ISSUE #9817: stability: improve gossip introspection
Prompted by #9749, in which we saw gossip refusing and redirecting lots of clients continuously.

Improve `/debug/gossip`; at the very least it would be on par with the periodic "gossip status" we print in the logs, but it could likely be a tad more verbose. It's likely worth exposing this in the admin ui as well to be more digestible. The [current endpoint](https://gamma.gce.cockroachdb.com:8080/_status/gossip/local) dumps all of the information, but it's hard to look at it if you're not a machine (no human-readable timestamps, etc). The admin ui could easily do this.

Similarly, there are likely some metrics that we should add regarding connection churn, such as the number of redirected clients or times outgoing clients were disconnected.

### PR DESCRIPTION
**Pull request by tbg**
Closes #9817.
Touches #27652.

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28890)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/gossip/gossip.go, line 539 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28890#-LKSa_of1E_Gh5VaRRgN:-LKSa_of1E_Gh5VaRRgO:b-s5f914) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec573482db66e1d2626f8974fc28309529333515/pkg/gossip/gossip.go#L539)):*
> ```Go
> 	log.Infof(
> 		ctx, "gossip status (%s, %d node%s)\n%s%s", status, n, util.Pluralize(int64(n)),
> 		g.clientStatus(), g.server.status(),
> ```

This log message will become significantly less readable which makes me (its author) a bit sad.
___
*[pkg/gossip/gossip.proto, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28890#-LKSaITd4JkohO6FHU0I:-LKSaITd4JkohO6FHU0J:b-v4mc2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec573482db66e1d2626f8974fc28309529333515/pkg/gossip/gossip.proto#L84)):*
> ```protobuf
>   option (gogoproto.goproto_stringer) = false;
> 
>   int64 BytesRcvd = 2;
> ```

`s/Rcvd/Received/g` (I know you're trying hard for consistent variable length here, but it seems excessive).

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28890)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/gossip/gossip.go, line 539 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28890#-LKSa_of1E_Gh5VaRRgN:-LKSgUjl54kKCW-JzS87:bcraq6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec573482db66e1d2626f8974fc28309529333515/pkg/gossip/gossip.go#L539)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This log message will become significantly less readable which makes me (its author) a bit sad.
</blockquote></details>

It's actually identical? Added a test to convince you of this (and fixed a buglet doing so).
___
*[pkg/gossip/gossip.proto, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28890#-LKSaITd4JkohO6FHU0I:-LKSlCcLBsCXQv1ZP1kg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec573482db66e1d2626f8974fc28309529333515/pkg/gossip/gossip.proto#L84)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/Rcvd/Received/g` (I know you're trying hard for consistent variable length here, but it seems excessive).
</blockquote></details>

Done.

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28890)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/gossip/gossip.go, line 539 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28890#-LKSa_of1E_Gh5VaRRgN:-LKSq7K58hx1-NLesR_V:bib2kki) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec573482db66e1d2626f8974fc28309529333515/pkg/gossip/gossip.go#L539)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

It's actually identical? Added a test to convince you of this (and fixed a buglet doing so).
</blockquote></details>

Ah, I completely glossed over the custom `String()` methods you defined. Carry on.

**Comment by tschottdorf** [comment]
TFTR!

bors r=petermattis

**Pull request merged**
