### PR TITLE
go.mod: bump Pebble to e9a8c4ad65c5

### PR DESCRIPTION
**Pull request by RaduBerinde**
e9a8c4ad sstable: fix error path in writer.Close
fdf055dd db: improve documentation of tableNewIters
717cbce0 db: add Options.LoggerAndTracer for tracing
7751e381 objstorage: better Writable API
78c8001e db: add missing error check in TestIngestLoad
1334233b metamorphic: add unit test for Options propagation
ed824c76 objstorage: rename ReadaheadHandle to ReadHandle

Informs #97350.

Release note: none
Epic: none

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
Looks like there are some interface changes that we need to account for. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98078#-:-NPsw90l-FktE6Px8eUi:b693a6c)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by RaduBerinde — COMMENTED** [review]
Yeah, I forgot about the writable API change. The changes were more extensive than I expected. PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98078#-:-NPt5Nx3CDPZkMBG5p3j:bc5njve)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rhu713)

**Review by nicktrav — APPROVED** [review]
I took a fairly mechanical pass through the changes. :lgtm: 

> Reviewed 4 of 4 files at r1, 32 of 32 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98078#-:-NPtFZY85XhtwZlwvHtu:b-j9xv3q)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rhu713)

___
*[`pkg/storage/sst_writer.go` line 461 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98078#-NPtD5AA4o9eJP53Bf8k:-NPtD5AA4o9eJP53Bf8l:bgkcw5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/0126cade3b977f7e6e7e49a2e4c152dffc880ff9/pkg/storage/sst_writer.go#L461)):*
> ```Go
> }
> 
> //// Flush implements the same interface as the standard library's *bufio.Writer's
> ```

nit: dead code?

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98078#-:-NPtIfqB6q9f7ydLmA81:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nicktrav and @rhu713)

___
*[`pkg/storage/sst_writer.go` line 461 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98078#-NPtD5AA4o9eJP53Bf8k:-NPtIgW6AKeh3QABjQvy:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/0126cade3b977f7e6e7e49a2e4c152dffc880ff9/pkg/storage/sst_writer.go#L461)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

nit: dead code?
</blockquote></details>

Fixed.

**Review by nicktrav — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98078)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rhu713)

**Pull request merged**
