### PR TITLE
sql: add in-memory sessions FIFO cache for closed sessions.

### PR DESCRIPTION
**Pull request by gtr**
This the first phase of https://github.com/cockroachdb/cockroach/issues/67888 which simply adds a FIFO cache for closed
sessions. The cache's eviction policy is both row-based and time-based.
Both the capacity and the time to live can be set using the `settings`
package.

Further PRs will focus on exposing these closed sessions to the frontend via
the `ListSessions` endpoint, optimizing the capacity and timeToLive
variables, and making appropriate UI changes.

Release note: None

### CODE REVIEW

**Comment by gtr** [comment]
Note: I had already embedded this into `conn_executor` but it made it harder to test that way. I figured a smaller PR with just the cache would be better. Future PRs will embed this cache into `conn_executor` and expose the closed sessions to the frontend.

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77577)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @gtr)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-Mxl6_N-7HaZV6KxmqOK):*
nit: just write `#67888` here is suffice, github will handle the rendering 
___
*[-- commits, line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-Mxl6obS8Z0T8ra6IHb3):*
The release justification comes from [this page](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/168656965/Guidelines+for+Release+Stability+Period) in the wiki and it has to be one of the 4 categories.
___
*[pkg/sql/session_cache.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-Mxl6vXM54E3Bs3O1erh:-Mxl6vXM54E3Bs3O1eri:bgqko8y) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a692eb1d3902bde8e2bca3d3a8e03fde2f0cbc9/pkg/sql/session_cache.go#L1)):*
> ```Go
> // Copyright 2015 The Cockroach Authors.
> ```

nit: copy right header need to be 2022
___
*[pkg/sql/session_cache.go, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-Mxl6yk72XRKOKqwzCe_:-Mxl6yk72XRKOKqwzCea:b-kvpcpt) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a692eb1d3902bde8e2bca3d3a8e03fde2f0cbc9/pkg/sql/session_cache.go#L18)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/util/syncutil"
> 	"strings"
> 	"time"
> ```

make sure run the auto formatting on the new files. You can find the [guide](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/154206209/Goland+Tips+and+Tricks) on the wiki
___
*[pkg/sql/session_cache.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-Mxl7Daz2y9veVuhaV0b:-Mxl7Db-5mAZ8Hi8CQB5:b-u61o4w) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a692eb1d3902bde8e2bca3d3a8e03fde2f0cbc9/pkg/sql/session_cache.go#L24)):*
> ```Go
> type SessionCache struct {
> 	capacity   int   // The maximum number of sessions in the cache.
> 	timeToLive int64 // The maximum time to live, in seconds.
> ```

How about let's use cluster settings for these so we can change their value at runtime. e.g. https://github.com/cockroachdb/cockroach/blob/c0ddc37972255c4763c8b844e592016312c66d8b/pkg/sql/contention/cluster_settings.go#L31
___
*[pkg/sql/session_cache.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-Mxl7tJz3MAUOocJQqW2:-Mxl7tJz3MAUOocJQqW3:b-vwndi8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a692eb1d3902bde8e2bca3d3a8e03fde2f0cbc9/pkg/sql/session_cache.go#L42)):*
> ```Go
> 
> 	cache.mu.data = make(map[ClusterWideID]SessionNode)
> 	cache.mu.queue = SessionList{}
> ```

Have you thought about just using the data structures provided in the `pkg/util/cache`?  Those data structures already have eviction implemented

I'm not too sure using a separate goroutine for cleanup here would be necessary. If implementing the TTL feature is 100% necessary, then this can be done during the read time. E.g. when this cache is queried, you would loop through all the entries you have stored and return them to the caller. During this loop, if an entry has expired, you can just omit it from you response and delete it from the cache. 
___
*[pkg/sql/session_cache.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-Mxl7fs39JXbYdDhDFbo:-Mxl7fs39JXbYdDhDFbp:bc1n3qa) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a692eb1d3902bde8e2bca3d3a8e03fde2f0cbc9/pkg/sql/session_cache.go#L45)):*
> ```Go
> 
> 	// Start checkForTimeToLiveEviction as a separate goroutine.
> 	go cache.checkForTimeToLiveEviction()
> ```

nit: we are trying our best to not to directly run goroutine in the codebase directly using `go` keyword. `stopper.RunAsyncTask` is a preferred approach since this allows you to cancel the goroutine gracefully during a node shutdown.
___
*[pkg/sql/session_cache.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-Mxl9wyu8pEyiHH9A6ON:-Mxl9wyu8pEyiHH9A6OO:bbfptd6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a692eb1d3902bde8e2bca3d3a8e03fde2f0cbc9/pkg/sql/session_cache.go#L77)):*
> ```Go
> }
> 
> func (c *SessionCache) get(id ClusterWideID) (registrySession, bool) {
> ```

Hmm have you decided on how this cache will be used in `connExecutor` ? You have two getter methods here (`get()` and `getSerializedSession()`) and I'm not sure when the point-lookup `get()` will ever be used ?
___
*[pkg/sql/session_cache.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-Mxl9cdf7Umij1uHRcyn:-Mxl9cdf7Umij1uHRcyo:b-til5yf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a692eb1d3902bde8e2bca3d3a8e03fde2f0cbc9/pkg/sql/session_cache.go#L122)):*
> ```Go
> // evict evicts a specific node from the cache. The caller must handle locking
> // the mutex.
> func (c *SessionCache) evict(node *SessionNode) {
> ```

nit: when a function must be called in the context of locking, the convention in the code base is to name it `.*Locked()`

E.g. `evictLocked()` 
___
*[pkg/sql/session_cache.go, line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-Mxl975LBcCw6Rtmb7g-:-Mxl975LBcCw6Rtmb7g0:b-uzcuzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a692eb1d3902bde8e2bca3d3a8e03fde2f0cbc9/pkg/sql/session_cache.go#L158)):*
> ```Go
> 	data      registrySession
> 	next      *SessionNode
> 	timestamp int64
> ```

nit: `time.Time` ? 
___
*[pkg/sql/session_cache_test.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-MxlAEV7529Z0UBFITHz:-MxlAEV7529Z0UBFITI-:b-vtslq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a692eb1d3902bde8e2bca3d3a8e03fde2f0cbc9/pkg/sql/session_cache_test.go#L1)):*
> ```Go
> package sql
> ```

nit: copyright header

**Review by gtr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77577)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @gtr)

___
*[pkg/sql/session_cache.go, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-Mxl6yk72XRKOKqwzCe_:-MxvRzHYAZUX_UJRJzpn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a692eb1d3902bde8e2bca3d3a8e03fde2f0cbc9/pkg/sql/session_cache.go#L18)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

make sure run the auto formatting on the new files. You can find the [guide](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/154206209/Goland+Tips+and+Tricks) on the wiki
</blockquote></details>

Done.
___
*[pkg/sql/session_cache.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-Mxl7Daz2y9veVuhaV0b:-MxvS3144vi7WaZ_Fh1L:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a692eb1d3902bde8e2bca3d3a8e03fde2f0cbc9/pkg/sql/session_cache.go#L24)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

How about let's use cluster settings for these so we can change their value at runtime. e.g. https://github.com/cockroachdb/cockroach/blob/c0ddc37972255c4763c8b844e592016312c66d8b/pkg/sql/contention/cluster_settings.go#L31
</blockquote></details>

Done.
___
*[pkg/sql/session_cache.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-Mxl7tJz3MAUOocJQqW2:-MxvS4JNDzUkl2wytW0q:b-buaiqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a692eb1d3902bde8e2bca3d3a8e03fde2f0cbc9/pkg/sql/session_cache.go#L42)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Have you thought about just using the data structures provided in the `pkg/util/cache`?  Those data structures already have eviction implemented

I'm not too sure using a separate goroutine for cleanup here would be necessary. If implementing the TTL feature is 100% necessary, then this can be done during the read time. E.g. when this cache is queried, you would loop through all the entries you have stored and return them to the caller. During this loop, if an entry has expired, you can just omit it from you response and delete it from the cache. 
</blockquote></details>

Changed to using `cache.UnorderedCache`, thanks! I think the TTL feature will be necessary but I moved that functionality to the read time.
___
*[pkg/sql/session_cache.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-Mxl7fs39JXbYdDhDFbo:-MxvSQWH8YMR9Fg95ot2:b12n0vr) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a692eb1d3902bde8e2bca3d3a8e03fde2f0cbc9/pkg/sql/session_cache.go#L45)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: we are trying our best to not to directly run goroutine in the codebase directly using `go` keyword. `stopper.RunAsyncTask` is a preferred approach since this allows you to cancel the goroutine gracefully during a node shutdown.
</blockquote></details>

Removed checking for TTL eviction in a separate goroutine but thanks for the heads up!
___
*[pkg/sql/session_cache.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-Mxl9wyu8pEyiHH9A6ON:-MxvSZyO8mHWMUMrDtC9:b-a9sfhs) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a692eb1d3902bde8e2bca3d3a8e03fde2f0cbc9/pkg/sql/session_cache.go#L77)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm have you decided on how this cache will be used in `connExecutor` ? You have two getter methods here (`get()` and `getSerializedSession()`) and I'm not sure when the point-lookup `get()` will ever be used ?
</blockquote></details>

I think the original `get()` method wasn't going to be used so I removed it. `getSerializedSessions()` will definitely be important when the eventual endpoint requests a list of `serverpb.Session`.
___
*[pkg/sql/session_cache.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-Mxl9cdf7Umij1uHRcyn:-MxvSzxP-lSBsDmVPcwS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a692eb1d3902bde8e2bca3d3a8e03fde2f0cbc9/pkg/sql/session_cache.go#L122)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: when a function must be called in the context of locking, the convention in the code base is to name it `.*Locked()`

E.g. `evictLocked()` 
</blockquote></details>

Done.
___
*[pkg/sql/session_cache.go, line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-Mxl975LBcCw6Rtmb7g-:-MxvT1O_2hJfEBKy1UQ2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a692eb1d3902bde8e2bca3d3a8e03fde2f0cbc9/pkg/sql/session_cache.go#L158)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: `time.Time` ? 
</blockquote></details>

Done.
___
*[pkg/sql/session_cache_test.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-MxlAEV7529Z0UBFITHz:-MxvT30MCQw0u66XZf8f:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a692eb1d3902bde8e2bca3d3a8e03fde2f0cbc9/pkg/sql/session_cache_test.go#L1)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: copyright header 
</blockquote></details>

Done.

**Review by maryliag — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 2 of 4 files at r4, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77577)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @gtr, and @maryliag)

___
*[pkg/sql/session_cache.go, line 35 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-Myr2_1a-wx79XZ-Gtby:-Myr2_1a-wx79XZ-Gtbz:b-lzwu06) ([raw file](https://github.com/cockroachdb/cockroach/blob/d766a4c8490cbdacabfec7f51baaf9a2adfd9fc6/pkg/sql/session_cache.go#L35)):*
> ```Go
> ).WithPublic()
> 
> // SessionCacheTimeToLive is the cluster setting that controls the maxumum time
> ```

nit: maximum 
___
*[pkg/sql/session_cache.go, line 36 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-Myr1NFu1ykTaX6xk8kZ:-Myr1NFu1ykTaX6xk8k_:b-2bqz4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d766a4c8490cbdacabfec7f51baaf9a2adfd9fc6/pkg/sql/session_cache.go#L36)):*
> ```Go
> 
> // SessionCacheTimeToLive is the cluster setting that controls the maxumum time
> // to live for a session, in seconds.
> ```

nit: this comments make it seems a session can only live for 1h and not that the cache of its info can only live for 1h.

**Review by gtr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77577)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @gtr, and @maryliag)

___
*[pkg/sql/session_cache.go, line 36 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-Myr1NFu1ykTaX6xk8kZ:-MyrMYaB1LNJspscDhHI:b-ubb87t) ([raw file](https://github.com/cockroachdb/cockroach/blob/d766a4c8490cbdacabfec7f51baaf9a2adfd9fc6/pkg/sql/session_cache.go#L36)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: this comments make it seems a session can only live for 1h and not that the cache of its info can only live for 1h.
</blockquote></details>

Good catch, thanks!

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77577)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @gtr, and @maryliag)

___
*[pkg/sql/session_cache.go, line 32 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-MyoJuOU0lTxAAHZuHFn:-MyoJuOU0lTxAAHZuHFo:b-ws1p0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d766a4c8490cbdacabfec7f51baaf9a2adfd9fc6/pkg/sql/session_cache.go#L32)):*
> ```Go
> 	"sql.session_cache.capacity",
> 	"the maximum number of sessions in the cache",
> 	100, // Totally arbitrary for now
> ```

put a TODO here ? 
___
*[pkg/sql/session_cache.go, line 1 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-MyrsMoO0z4Er11FxvsJ:-MyrsMoO0z4Er11FxvsK:b-sji04s) ([raw file](https://github.com/cockroachdb/cockroach/blob/c091ddbdcadab7f96473981afe04b3dd4e473556/pkg/sql/session_cache.go#L1)):*
> ```Go
> // Copyright 2022 The Cockroach Authors.
> ```

gtr: "renaming this to `closed_session_cache` since it's more accurate" 
___
*[pkg/sql/session_cache.go, line 50 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-MyrphlT7I-Hvf_AZb2y:-MyrphlT7I-Hvf_AZb2z:b-csk58l) ([raw file](https://github.com/cockroachdb/cockroach/blob/c091ddbdcadab7f96473981afe04b3dd4e473556/pkg/sql/session_cache.go#L50)):*
> ```Go
> 	mu struct {
> 		syncutil.RWMutex
> 		queue *cache.UnorderedCache
> ```

since we are not really implementing queue-like interface, this is really a "data store". I guess queue is not really a fitting name here. 
___
*[pkg/sql/session_cache.go, line 70 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-MyrrwMs0DNn2uYRaat_:-MyrrwMs0DNn2uYRaata:b778p44) ([raw file](https://github.com/cockroachdb/cockroach/blob/c091ddbdcadab7f96473981afe04b3dd4e473556/pkg/sql/session_cache.go#L70)):*
> ```Go
> 
> // Add adds a closed session to the SessionCache.
> func (c *SessionCache) Add(id ClusterWideID, session registrySession) {
> ```

We can directly use the `serverpb.Session` proto message here, so we don't need to keep a reference to the `connExecutor` around after we close it. 
___
*[pkg/sql/session_cache.go, line 101 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-MyrshEv2MIBypwIirf1:-MyrshEv2MIBypwIirf2:b5ep55m) ([raw file](https://github.com/cockroachdb/cockroach/blob/c091ddbdcadab7f96473981afe04b3dd4e473556/pkg/sql/session_cache.go#L101)):*
> ```Go
> // cache, ordered from newest to oldest. This function is used for testing
> // purposes.
> func (c *SessionCache) viewCachedSessions() string {
> ```

nit: test-only methods can be implemented in the test drivers since it still has access to all of struct's internal fields.
___
*[pkg/sql/session_cache.go, line 145 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-MyrsZ8GCVcyhtfd753v:-MyrsZ8GCVcyhtfd753w:b-913q86) ([raw file](https://github.com/cockroachdb/cockroach/blob/c091ddbdcadab7f96473981afe04b3dd4e473556/pkg/sql/session_cache.go#L145)):*
> ```Go
> 
> // Clear clears the cache.
> func (c *SessionCache) Clear() {
> ```

nit: if this only used for test then no need to export

**Review by gtr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77577)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @gtr, and @maryliag)

___
*[pkg/sql/session_cache.go, line 32 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-MyoJuOU0lTxAAHZuHFn:-Mys0eRc8IoPb5OaP2co:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d766a4c8490cbdacabfec7f51baaf9a2adfd9fc6/pkg/sql/session_cache.go#L32)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

put a TODO here ? 
</blockquote></details>

Done.
___
*[pkg/sql/session_cache.go, line 1 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-MyrsMoO0z4Er11FxvsJ:-MyrvaVv5MOyvcSTkxUC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c091ddbdcadab7f96473981afe04b3dd4e473556/pkg/sql/session_cache.go#L1)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

gtr: "renaming this to `closed_session_cache` since it's more accurate" 
</blockquote></details>

Done.
___
*[pkg/sql/session_cache.go, line 50 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-MyrphlT7I-Hvf_AZb2y:-MyrvZwe0HDR38kSzkIx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c091ddbdcadab7f96473981afe04b3dd4e473556/pkg/sql/session_cache.go#L50)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

since we are not really implementing queue-like interface, this is really a "data store". I guess queue is not really a fitting name here. 
</blockquote></details>

Done.
___
*[pkg/sql/session_cache.go, line 70 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-MyrrwMs0DNn2uYRaat_:-MyrwRSh-jBfRw1kunaG:bmmh6r6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c091ddbdcadab7f96473981afe04b3dd4e473556/pkg/sql/session_cache.go#L70)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

We can directly use the `serverpb.Session` proto message here, so we don't need to keep a reference to the `connExecutor` around after we close it. 
</blockquote></details>

Done. Great catch!
___
*[pkg/sql/session_cache.go, line 101 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-MyrshEv2MIBypwIirf1:-MyryMziBV6iGVMQ2LF4:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/c091ddbdcadab7f96473981afe04b3dd4e473556/pkg/sql/session_cache.go#L101)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: test-only methods can be implemented in the test drivers since it still has access to all of struct's internal fields.
</blockquote></details>

Done!

**Review by Azhng — COMMENTED** [review]
Nice! The code looks good! Just some nits about the tests sleeping. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-:-MywXcU18LCvg2B9PRdq:b-1ye13z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @gtr, and @maryliag)

___
*[pkg/sql/testdata/closed_session_cache, line 42 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-MywWvbM1ZhzS9wBT2Vs:-MywWvbM1ZhzS9wBT2Vt:bgu5rye) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a069ae5351db13ea1dbc8cfbae7116229178f95/pkg/sql/testdata/closed_session_cache#L42)):*
> ```
> 
> # Wait for 15 seconds, enough time for all sessions in the cache to be evicted.
> wait seconds=15
> ```

Instead of actually doing `time.Sleep`, (which actually extend the CI runtime by another 15 seconds), we can inject a time source object into the `ClosedSessionCache`. This way we can easily adjust the cache's perception of time without actually doing the wait. 

See example https://github.com/cockroachdb/cockroach/blob/a9d07f6fca07659ac132da51a128980cf4f1c9d3/pkg/sql/contention/event_store.go#L125

**Review by gtr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77577)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @maryliag)

___
*[pkg/sql/testdata/closed_session_cache, line 42 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-MywWvbM1ZhzS9wBT2Vs:-Myx7nEiEQ6roJssI5rL:b-qp92hs) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a069ae5351db13ea1dbc8cfbae7116229178f95/pkg/sql/testdata/closed_session_cache#L42)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Instead of actually doing `time.Sleep`, (which actually extend the CI runtime by another 15 seconds), we can inject a time source object into the `ClosedSessionCache`. This way we can easily adjust the cache's perception of time without actually doing the wait. 

See example https://github.com/cockroachdb/cockroach/blob/a9d07f6fca07659ac132da51a128980cf4f1c9d3/pkg/sql/contention/event_store.go#L125
</blockquote></details>

Great idea for testing! I injected the time source object into `ClosedSessionCache` and was able to cut down the test runtime to 2 seconds. However, because I had to rely on the cache's time source object to determine if a an entry of session info was allowed to stay, I also am not able to properly use `time.Now()`. This results in `time.Sleep()`, which will be the real use case for when sessions are added every couple of seconds/minutes, not having any effect on the cache. Check out the `TODO` in the `closed_session_cache_test.go` file.

Should we split methods for simulating time with time source?

**Review by Azhng — APPROVED** [review]
Nice! :lgtm: (just one small nit left) 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-:-Mz0gUXICgmyeN-zKdPQ:b2i5swn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng, @gtr, and @maryliag)

___
*[pkg/sql/closed_session_cache.go, line 70 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/77577#-Mz0gLws0rWmlYrPeejV:-Mz0gLws0rWmlYrPeejW:b-fprpfj) ([raw file](https://github.com/cockroachdb/cockroach/blob/174ebc0b91aa114d0bf828c9476e1e1f0dadb8c8/pkg/sql/closed_session_cache.go#L70)):*
> ```Go
> 
> // Add adds a closed session to the ClosedSessionCache.
> func (c *ClosedSessionCache) Add(id ClusterWideID, session serverpb.Session) {
> ```

nit: `Add` probably doesn't need to be exported since we will be calling it from within the `sql` package

**Pull request merged**
