### PR TITLE
backupccl: copy manifest holding mutex before checkpoint

### PR DESCRIPTION
**Pull request by dt**
While the backup coordinator uses a mutex to ensure concurrent recording
of separate responses is correctly serialized, previously the checkpoint
writing did not acquire that mutex -- it uses a separate checkpoint-only
mutex to avoid a slow write blocking the overall job progress (while
serializing checkpoint writes themselves). This was okay initially since
the actual mutable var -- the list of files -- was read for the purpose
of the checkpoint write while holding the main mutex. However a later
change added an update to a field in the manifest – the revision
StartTime which is the max of the revision start times from each
response. This on its own was fine, as it was done while holding the
mutex, however the checkpoint writing then read that field while _not_
holding that mutex, leading to a race. This could manifest as an out-of-
bounds panic in proto marshalling, when the Size() method on that field
returned a size used to allocate a buffer that then was too small for
the changed value of the field later. Complicating this, one big buffer
is used for all the fields, so it isn't clear which one overflowed its
expected size.

Release note: none.

### CODE REVIEW

**Comment by dt** [comment]
cc @rytaft @RaduBerinde

**Review by pbardea — APPROVED** [review]
Thanks for tracking this down!

**Comment by rytaft** [comment]
Nice find!

**Comment by dt** [comment]
TFTRs!

I think credit for the find goes to @RaduBerinde !

bors+

**Pull request merged**
