### PR TITLE
sql/opt/optbuilder: remove unnecessary allocs in happy path

### PR DESCRIPTION
**Pull request by petermattis**
The `colName` parameter of `FindSourceProvidingColumn` was escaping due
to being passed by reference to `newAmbiguousColumnError` and
`tree.ErrString`.

For reference, the `kv-read` benchmark query performs 75 allocs in the
optbuilder phase. This PR removes 3 of those allocs.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
My first sql/opt PR!

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

Andy: it would be very hard to bring opt to parity on kv.
Peter: challenge accepted.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28592#-:-LJuWMzBDXBjnlpgfHm6:b-plejrh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by andy-kimball — COMMENTED** [review]
Hehe, it was a reverse psychology trick designed to get Pete to perform escape analysis for us.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28592#-:-LJudS50BfCpX1w3UoCd:b4r6634)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andy-kimball — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28592#-:-LJurEapCU0f7ezElEn7:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Comment by petermattis** [comment]
bors r=RaduBerinde

**Pull request merged**
