### PR TITLE
sql/jobs: move package out of sql

### PR DESCRIPTION
**Pull request by benesch**
Jobs have nothing to do with SQL, except that they use the SQL interface
to query and manipulate the jobs in the cluster, so move the sql/jobs
package out of the sql directory. Jobs are important enough as a
standalone entity to warrant this.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
LGTM, though you may want for wait for another LGTM by someone who's actually affected by this.

**Comment by danhhz** [comment]
Also LGTM. What's the immediate motivation?

**Review by madelynnblue — APPROVED** [review]

**Comment by benesch** [comment]
> What's the immediate motivation?

No immediate motivation; this is just the best time to do these refactors. The 2.1 branch hasn't been cut yet but we're pretty much done with 2.0 backports.

**Comment by benesch** [comment]
Not seeing any open jobs PRs, so pulling the trigger! TFTRs!

bors r=mjibson,danhhz,tschottdorf

**Comment by benesch** [comment]
Flake.

bors r+

**Pull request merged**
