### PR TITLE
colrpc: fix the inbox shutdown with premature flow ctx cancellation

### LINKED ISSUE #64294: sql/logictest: timed out
unknown.(unknown) [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2929277&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=2929277&tab=artifacts#/) on master @ [f3286c1e1b8d2d44f0b5c92460c0d5acbfdd1610](https://github.com/cockroachdb/cockroach/commits/f3286c1e1b8d2d44f0b5c92460c0d5acbfdd1610):

```
Slow failing tests:
TestLogic/fakedist/fk/59582_reference_rowid - 980.55s

Slow passing tests:
TestTenantLogic - 1160.95s
TestRegionChangeRacingRegionalByRowChange - 125.94s
TestAllRegisteredImportFixture - 124.04s
TestCCLLogic - 109.28s
TestAlterTableLocalityRegionalByRowError - 96.11s
TestTypeChangeJobCancelSemantics - 92.74s
TestRestoreMidSchemaChange - 82.21s
TestIndexCleanupAfterAlterFromRegionalByRow - 62.81s
TestRemoveDeadReplicas - 59.24s
TestBTreeDeleteInsertCloneEachTime - 59.03s
TestExecBuild - 59.00s
TestImportIntoCSV - 54.54s
TestRaceWithBackfill - 53.16s
TestConcurrentAddDropRegions - 51.80s
TestImportData - 49.27s
TestTelemetry - 49.19s
TestImportCSVStmt - 44.44s
Example_demo - 43.92s
TestFullClusterBackup - 40.88s
TestJSONContains - 38.44s
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
make stressrace TESTS=(unknown) PKG=./pkg/unknown TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```
</p>
<p>Parameters in this failure:

- GOFLAGS=-json
</p>
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*\(unknown\).*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by yuzefovich**
**colrpc: use the correct pgcode for connection failure**

This brings the vectorized inbox in line with the row-based equivalent.

Release note: None

**colrpc: fix the inbox shutdown with premature flow ctx cancellation**

A recent change in 3771c58 exposed
a bug in the "design" of handling of FlowStream RPC on the inbox side
(note that the bug wouldn't occur before that change because we captured
the context during the creation of the inbox - which was a temporary
hack before context argument was moved to `Operator.Init` method).

There are two goroutines involved with handling the server (inbox) side
of the FlowStream RPC:
- the "stream handler" goroutine. Its job is responding to the RPC,
waiting for the second "reader" goroutine to arrive and pass over the
stream to it, and then provide the "result" of the RPC (the error return
argument).
- the "reader" goroutine. Its job is actually recv'ing the data from the
remote node, deserializing it, and propagating it further to its
consumer.

Only when the stream handler goroutine exits does the client side of the
RPC (the outbox) exit too. The stream handler goroutine has two blocking
points:
- it is first blocked until the reader goroutine arrives
- after that, it is blocked until the reader goroutine tells it that it
is done with the stream.

Previously (after the recent change and up until now), in case when the
reader goroutine never arrives (i.e. `Inbox.Init` is never called), the
stream handler would block forever, even if the flow context of the
inbox host node is canceled. This commit fixes this issue by listening
for the flow context cancellation during that first blocking event. Note
that listening for the same type of cancellation during the second
blocking event is not necessary because the reader context is a child of
the flow context.

Just to reiterate, this problem was "hidden" on all previous versions
because we captured the flow context during the construction of the
inbox and listened on that context for the cancellation to go around
`Inbox.Next` not being called ever (which is actually a totally valid
scenario). This commit fixes the issue proper, and in the same way that
we do it in the row-based flows.

Fixes: #64294.

Release note: None (no release with this bug)

### CODE REVIEW

**Comment by yuzefovich** [comment]
I got a hundred successful runs on the gceworker with this (and another) fixes cherry-picked, so PTAL.

@jordanlewis I think you should be the main reviewer for this PR.

**Review by rytaft — APPROVED** [review]
:lgtm: but would be good to get @jordanlewis's eyes on it too

> Reviewed 2 of 2 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64312#-:-MZUuYOn3bDuBXU3w2-P:bw3ujc2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by yuzefovich** [comment]
@jordanlewis could you please take a quick look here?

**Review by jordanlewis — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64312)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colflow/colrpc/inbox.go, line 292 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64312#-MZrTlps-oeB99etVTFP:-MZrTlps-oeB99etVTFQ:b-hl33c) ([raw file](https://github.com/cockroachdb/cockroach/blob/a732ec5a57cbf832ce04fafdece1a00b9b843a43/pkg/sql/colflow/colrpc/inbox.go#L292)):*
> ```Go
> 			// expected on in all cases so that the caller could decide on how
> 			// to handle it.
> 			err = pgerror.Newf(pgcode.InternalConnectionFailure, "communication error: %s", err)
> ```

nit: considering the difficulty of tracking these down, i suggest adding a way to identify this error message. perhaps "inbox communication error"?

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64312#-:-MZsE-cO8084CbbsRIl4:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/sql/colflow/colrpc/inbox.go, line 292 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64312#-MZrTlps-oeB99etVTFP:-MZsDyCF9XoecS25yxRH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a732ec5a57cbf832ce04fafdece1a00b9b843a43/pkg/sql/colflow/colrpc/inbox.go#L292)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: considering the difficulty of tracking these down, i suggest adding a way to identify this error message. perhaps "inbox communication error"?
</blockquote></details>

Done.

**Pull request merged**
