### PR TITLE
storage: fix replicate queue requeuing

### PR DESCRIPTION
**Pull request by petermattis**
After transferring a lease or failing to find a rebalance target we
should not requeue the replica. Doing so leads to a loop where we
process the same replica again and again.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/11982)

### CODE REVIEW

**Comment by petermattis** [comment]
Broken by #11600.

**Comment by tamird** [comment]
:lgtm:

test?

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11982#-:-KY4zV5V2xdwAGJNICuc:bm2voos)*

**Comment by petermattis** [comment]
> test?

Yeah. Any suggestions? We don't have good testing of the queue heuristics. 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11982#-:-KY53oTqVmFRwjtw_NpA:b-d4j5qi)*

**Comment by tamird** [comment]
I don't have a suggestion =/

**Review by spencerkimball — APPROVED** [review]

**Comment by petermattis** [comment]
> I don't have a suggestion

I've filed an issue. I'll try and get to this next week.

**Pull request merged**
