### PR TITLE
cli: stop attributing time spent running schema changes to network lat 

### PR DESCRIPTION
**Pull request by arulajmani**
See individual commits for details.

### CODE REVIEW

**Comment by arulajmani** [comment]
Here's an example of how things look after this patch:

```
demo@127.0.0.1:26257/movr> CREATE TABLE t (a INT);
CREATE TABLE

Time: 3ms total (execution 3ms / network 0ms)

demo@127.0.0.1:26257/movr> INSERT INTO t SELECT i FROM generate_series(1, 100000) AS g(i);
INSERT 100000

Time: 636ms total (execution 636ms / network 0ms)

demo@127.0.0.1:26257/movr> ALTER TABLE t ADD COLUMN i INT DEFAULT 5;
ALTER TABLE

Time: 928ms total (execution 928ms / network 0ms)

demo@127.0.0.1:26257/movr> \set verbose_times on
demo@127.0.0.1:26257/movr> ALTER TABLE t ADD COLUMN i2 INT DEFAULT 5;
ALTER TABLE

Time: 869.745ms total (parse 19µs / plan 1.367ms / exec 2.096ms / schema change 862.399ms / other 3.732ms / network 132µs)

demo@127.0.0.1:26257/movr> BEGIN;
BEGIN

Time: 122µs total (parse 9µs / plan 0s / exec 0s / schema change 0s / other 169µs / network 122µs)

demo@127.0.0.1:26257/movr  OPEN> ALTER TABLE t ADD COLUMN i3 INT DEFAULT 5;
ALTER TABLE

Time: 4.027ms total (parse 18µs / plan 1.561ms / exec 2.251ms / schema change 0s / other 121µs / network 76µs)

demo@127.0.0.1:26257/movr  OPEN> COMMIT;
COMMIT

Time: 1.300762s total (parse 4µs / plan 0s / exec 0s / schema change 1.295962s / other 4.64ms / network 156µs)
```

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65530)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @knz)

___
*[pkg/cli/sql_util.go, line 397 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65530#-MaCZTc556bNAQLeRc1O:-MaCZTc556bNAQLeRc1P:brqzcf6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0313c088f4d4a9c5ff86d6469973cc82235f3992/pkg/cli/sql_util.go#L397)):*
> ```Go
> 	}()
> 
> 	// TODO(arul): In 21.1, SHOW LAST QUERY STATISTICS returned 4 columns. In 21.2,
> ```

hmm it would be good if we could backport this -- it's come up as a common source of confusion. is there a risk to backporting to 21.1? (we can still keep this logic around until 22.1)
___
*[pkg/cli/sql_util.go, line 1044 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65530#-MaCZvlJ0-zGgxqeRMH6:-MaCZvlJ0-zGgxqeRMH7:bpdud9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/0313c088f4d4a9c5ff86d6469973cc82235f3992/pkg/cli/sql_util.go#L1044)):*
> ```Go
> 	otherLat := serviceLat - parseLat - planLat - execLat
> 	if sqlCtx.verboseTimings {
> 		// TODO(arul): I'm preffering schema change here over something like "jobs",
> ```

my one question would be if it's possible that jobs that are not schema changes would ever come up as a big source of latency here, and lead to ppl being confused about why it says there are slow schema changes

tbh, i wonder if we should just include this latency under `execLat` as well? does the end user care about the distinction of what happens before the commit versus post-commit? it's all just execution time. idk, curious for your thoughts on that.

**Review by rafiss — CHANGES_REQUESTED** [review]
awesome! this was nice to read

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65530#-:-MaCa4dT4kHxEh_MN1Fw:br6sg8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @knz)

___
*[pkg/cli/sql_util.go, line 1044 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65530#-MaCZvlJ0-zGgxqeRMH6:-MaCaJ1g0bPnxzP52BjS:b-9rkgep) ([raw file](https://github.com/cockroachdb/cockroach/blob/0313c088f4d4a9c5ff86d6469973cc82235f3992/pkg/cli/sql_util.go#L1044)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

my one question would be if it's possible that jobs that are not schema changes would ever come up as a big source of latency here, and lead to ppl being confused about why it says there are slow schema changes

tbh, i wonder if we should just include this latency under `execLat` as well? does the end user care about the distinction of what happens before the commit versus post-commit? it's all just execution time. idk, curious for your thoughts on that.
</blockquote></details>

hmm though i could see the distinction being useful for a schema change inside an explicit txn

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 5 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65530)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @rafiss)

___
*[pkg/cli/sql_util.go, line 397 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65530#-MaCZTc556bNAQLeRc1O:-MaDTqQ88BFTzx0D6PLg:b-rog23m) ([raw file](https://github.com/cockroachdb/cockroach/blob/0313c088f4d4a9c5ff86d6469973cc82235f3992/pkg/cli/sql_util.go#L397)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hmm it would be good if we could backport this -- it's come up as a common source of confusion. is there a risk to backporting to 21.1? (we can still keep this logic around until 22.1)
</blockquote></details>

I think this is safe to backport and run in mixed-version clusters even with a 20.x server.
___
*[pkg/cli/sql_util.go, line 1044 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65530#-MaDTvc27sS-J3Zl7DCY:-MaDTvc27sS-J3Zl7DCZ:bcj7el6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0313c088f4d4a9c5ff86d6469973cc82235f3992/pkg/cli/sql_util.go#L1044)):*
> ```Go
> 	otherLat := serviceLat - parseLat - planLat - execLat
> 	if sqlCtx.verboseTimings {
> 		// TODO(arul): I'm preffering schema change here over something like "jobs",
> ```

nit: "preferring"
___
*[pkg/cli/sql_util.go, line 1044 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65530#-MaCZvlJ0-zGgxqeRMH6:-MaDTypu0ACBUfmL95Hc:b-m08cob) ([raw file](https://github.com/cockroachdb/cockroach/blob/0313c088f4d4a9c5ff86d6469973cc82235f3992/pkg/cli/sql_util.go#L1044)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hmm though i could see the distinction being useful for a schema change inside an explicit txn
</blockquote></details>

I believe the only jobs that run at txn commit time are schema changes today, so the label wouldn't surprise me.
Maybe worth double-checking with andrew to be sure.
___
*[pkg/cli/sql_util.go, line 1046 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65530#-MaDUH5NExxMYNdX5qJz:-MaDUH5NExxMYNdX5qK-:b-r9yh40) ([raw file](https://github.com/cockroachdb/cockroach/blob/0313c088f4d4a9c5ff86d6469973cc82235f3992/pkg/cli/sql_util.go#L1046)):*
> ```Go
> 		// TODO(arul): I'm preffering schema change here over something like "jobs",
> 		// but I could go either way.
> 		fmt.Fprintf(w, " (parse %s / plan %s / exec %s / schema change %s / other %s / network %s)\n",
> ```

I think you should omit the "schema change" output if the distinction is not supported server-side. Otherwise, folk will see "schema change 0s" after a ALTER TABLE INDEX and will report a bug "the ddl reported latency is zero, that's a bug".

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65530)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[pkg/cli/sql_util.go, line 397 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65530#-MaCZTc556bNAQLeRc1O:-MaUzC1o0DM-AH5Kw3xg:berjwyq) ([raw file](https://github.com/cockroachdb/cockroach/blob/0313c088f4d4a9c5ff86d6469973cc82235f3992/pkg/cli/sql_util.go#L397)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think this is safe to backport and run in mixed-version clusters even with a 20.x server.
</blockquote></details>

Yeah, this should be safe to backport, though this logic will have to stick around till 22.1 even if we backport. 
___
*[pkg/cli/sql_util.go, line 1044 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65530#-MaCZvlJ0-zGgxqeRMH6:-MaUzL1WCLj6s075fJvY:b-ljd6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/0313c088f4d4a9c5ff86d6469973cc82235f3992/pkg/cli/sql_util.go#L1044)):*
Yeah, it's just schema change jobs today. I'm in favour of calling it as such because, to me, it's the least confusing bucket name.

> does the end user care about the distinction of what happens before the commit versus post-commit? 

It's all under "execution" in the normal case. This thing only comes into play when a user has got verbose timings on, in which case, I'd say this deserves its own bucket. Mostly because the user wants us to be verbose, but also because if we add to "execLat" here we won't be consistent with the value displayed in the db console. 
___
*[pkg/cli/sql_util.go, line 1046 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65530#-MaDUH5NExxMYNdX5qJz:-MaUxJ_9ADe-Yqty6WtX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0313c088f4d4a9c5ff86d6469973cc82235f3992/pkg/cli/sql_util.go#L1046)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think you should omit the "schema change" output if the distinction is not supported server-side. Otherwise, folk will see "schema change 0s" after a ALTER TABLE INDEX and will report a bug "the ddl reported latency is zero, that's a bug".
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
new changes look good to me!

> Reviewed 5 of 5 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65530#-:-MaWc_sS24LYKvwEd44K:bov4eeg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

**Review by knz — APPROVED** [review]
:lgtm: for the overall structure but I think we need a little more test.

> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65530#-:-MaY7oG7ErhpKq_K7aUp:b-ajk1v9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @rafiss)

___
*[pkg/cli/sql_util.go, line 385 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/65530#-MaY7IV27B2HYP5KYJ8e:-MaY7IV27B2HYP5KYJ8f:b6mbpdc) ([raw file](https://github.com/cockroachdb/cockroach/blob/43a2e721c0f91b18eefc41a6d0534b101a260135/pkg/cli/sql_util.go#L385)):*
> ```Go
> // the sql row parsed as time.Duration.
> func (c *sqlConn) getLastQueryStatistics() (
> 	parseLat, planLat, execLat, serviceLat, jobsLat time.Duration,
> ```

nit: not your PR, however I think time is coming to return these values as a struct, for clarity.
___
*[pkg/sql/conn_executor_test.go, line 940 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/65530#-MaY7edh1WcP-U8sZ0cH:-MaY7edh1WcP-U8sZ0cI:b-18zelh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d37f7096b10e648b998b8b3ad0397a89eafafb4b/pkg/sql/conn_executor_test.go#L940)):*
> ```Go
> 		}
> 
> 		if postCommitJobsInterval.AsFloat64() < 0 || postCommitJobsInterval.AsFloat64() > 1 {
> ```

Can you have a test that asserts that the job time becomes significantly non-zero when there are actually jobs to run? Right now, a bug could be introduced that makes this zero all the time and we don't have unit tests to check.

**Comment by jordanlewis** [comment]
Thanks for looking at this, @arulajmani! Can youcheck what happens in the presence of retries, explicit transactions, and batched statements? We've repeatedly seen confusion around timings in those scenarios, so it's important to check how they work in cases like this where we're adding more observability features. For example, customers will be unhappy if these times mismatch the times in the DB Console.

Also, as a suggestion, can we hide the "schema change latency" section when it is 0? The line is now very long in the CLI, so hiding information that is not useful is important. I'm also beginning to question whether this level of verbosity is useful by default.

cc @vy-ton @kevin-v-ngo. What do you think about the UX here?

**Comment by rafiss** [comment]
> Oh, nice! Sorry for the duplicate suggestion,
No problem at all; I'm glad we are all caring more about the UX here!

**Comment by arulajmani** [comment]
> Can you check what happens in the presence of retries, explicit transactions, and batched statements? 

I think we should be in the clear with these as well. I'll add more words about the specific cases and their behavior:

- explicit transactions/batched statements: The CLI doesn't display timings for multi-line statements -- we buffer a message of the form `Note: timings for multiple statements on a single line are not supported.`. 
Explicit transactions, entered a line at a time, should work similar to single line statements. The only difference here is that the schema change time will be attributed to the `COMMIT` statement because we run the schema change as a post commit hook (as seen in the code snippet linked above). 

- retries: This shouldn't be affected, as we start collecting the schema change phase after the retry would happen. 

And as Rafi mentioned, in the default case, we attribute the time spent running schema changes to "execution". Before this patch, we would attribute it to "network", which was super confusing.

**Review by arulajmani — COMMENTED** [review]
bors r=rafiss,knz

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65530#-:-MaZt22Y2Fobv_v4-WXn:b-xgc33f)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz and @rafiss)

___
*[pkg/cli/sql_util.go, line 385 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/65530#-MaY7IV27B2HYP5KYJ8e:-MaZswE36ccD23RU1-Fb:bpczqct) ([raw file](https://github.com/cockroachdb/cockroach/blob/43a2e721c0f91b18eefc41a6d0534b101a260135/pkg/cli/sql_util.go#L385)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: not your PR, however I think time is coming to return these values as a struct, for clarity.
</blockquote></details>

There's a few things we can clean up around here that I noticed while working on this patch, I'll pull it in a separate PR soon. 
___
*[pkg/sql/conn_executor_test.go, line 940 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/65530#-MaY7edh1WcP-U8sZ0cH:-MaZstYc1Had38pC33gz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d37f7096b10e648b998b8b3ad0397a89eafafb4b/pkg/sql/conn_executor_test.go#L940)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you have a test that asserts that the job time becomes significantly non-zero when there are actually jobs to run? Right now, a bug could be introduced that makes this zero all the time and we don't have unit tests to check.
</blockquote></details>

Done.

**Comment by arulajmani** [comment]
Looks like the new schema change portion of the test that I introduced timed out under testrace. I might be running a really long backfill, I'll try and tune this better

**Pull request merged**
