### PR TITLE
sql: load crdb_internal.jobs protobufs lazily

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, crdb_internal.jobs did two things eagerly:

1. Load all serialized rows into memory from system.jobs
2. Unmarshal all serialized rows into inflated protobuf structs

Now, crdb_internal.jobs loads all serialized rows into memory only, and
does the unmarshalling lazily, throwing away the memory for each
unmarshalled job after each row is emitted.

This should lead to somewhat less memory usage.

Release note (performance improvement): load less data into memory for
crdb_internal.jobs.

cc @joshimhoff

### CODE REVIEW

**Comment by joshimhoff** [comment]
Thanks, Jordan!

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45914#-:-M21jHV--yvSLQ5F750S:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @spaskob)

**Review by spaskob — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45914#-:-M22nFTbEUgcrc1K-rYY:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @spaskob)

**Comment by joshimhoff** [comment]
Can we backport this change?

**Comment by ajwerner** [comment]
If we drop the memory monitor part I don’t think it’s controversial.

**Comment by joshimhoff** [comment]
> If we drop the memory monitor part I don’t think it’s controversial.

I thought that was a separate PR?

**Comment by ajwerner** [comment]
Right, it is, this touches it so when backporting it we’d just need to strip that part.

**Comment by joshimhoff** [comment]
Ack. Ok. Since the plan is that CC will support the last two major versions, we'd appreciate a backport. Jordan, can we get this into 19.2.5? Not sure if it's already cut.

CC @vladdy.

**Comment by spaskob** [comment]
@jordanlewis has this been backported?

**Comment by spaskob** [comment]
Never mind, I just found https://github.com/cockroachdb/cockroach/pull/46452

**Pull request merged**
