### PR TITLE
build: remove muslc from the building process

### PR DESCRIPTION
**Pull request by otan**
This commit removes building muslc from the release process. It is
causing issues with the GEOS build, and we're not confident it is worth
spending the time to debug it.

* Delete mentions of muslc from publishing artifacts / provisional artifacts.
* Delete muslc from the Docker image.
* Remove Makefile items that are musl-c related.
* Unfortunately, I am not able to push the Docker image to
  cockroachdb/builder. I'm not sure that's important atm.

Release note (general change): Removed the publication of muslc
CockroachDB builds.

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

Glad to see this done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49685#-:-M8VRUOi42E9zXgFYDLi:b42edit)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bdarnell, @jlinder, and @otan)

___
*[c-deps/jemalloc-rebuild, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49685#-M8VR8EaBhve0rnu1cS9:-M8VR8Eb8SsJAolSN5VY:b-hmtbr0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3d086f8d098dc11dccd6eb4159bda966d288224/c-deps/jemalloc-rebuild#L4)):*
> ```
> ARTIFACT CACHING" in build/common.mk for rationale.
> 
> 6
> ```

Why was this bump necessary? I don't think you actually changed the flags to jemalloc cmake.

**Comment by otan** [comment]
___
*[c-deps/jemalloc-rebuild, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49685#-M8VR8EaBhve0rnu1cS9:-M8Vx3d3CQa-7M-076lS:b-1tb6d7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3d086f8d098dc11dccd6eb4159bda966d288224/c-deps/jemalloc-rebuild#L4)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Why was this bump necessary? I don't think you actually changed the flags to jemalloc cmake.
</blockquote></details>

haha just wanted to be sure :) removed!

**Review by bdarnell — APPROVED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49685)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jlinder, @otan, and @petermattis)

___
*[pkg/build/info.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49685#-M8VxwgYCkyyPrmf9M--:-M8VxwgYCkyyPrmf9M-0:bbze901) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3d086f8d098dc11dccd6eb4159bda966d288224/pkg/build/info.go#L37)):*
> ```Go
> 	// Distribution is changed by the CCL init-time hook in non-APL builds.
> 	Distribution = "OSS"
> 	typ          string // Type of this build: <empty>, "development", or "release[-gnu]"
> ```

Remove the `[-gnu]` here. It looks like regular release builds just identify themselves here as `release`, not `release-gnu`.

**Comment by otan** [comment]
weill merge after https://teamcity.cockroachdb.com/viewQueued.html?itemId=1978124&tab=queuedBuildOverviewTab passes

**Pull request merged**
