### PR TITLE
Only change DB in TestLogic if it differs

### PR DESCRIPTION
**Pull request by andreimatei**
Since `SET DATABASE` uses the transaction, this crashes
some tests which expect transaction retries. Often, this
does not affect tests which get checked in, but their
earlier version prior to fixing a bug.

Motivation for this issue (since fixed in #4332):

Test for transaction retry not detected in time, leading to non-repeatable read.
@tschottdorf will probably take it over

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4292)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM. I think we can merge this and file an issue, since it passes and documents the problem.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/testdata/serializable_restart_detected, line 5 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4292#-KABlAgcCadQG-F1rndf:-KABlAgcCadQG-F1rndg:-757805542) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bc8f5307322baaaf76a5266c815f4f145e42b1d/sql/testdata/serializable_restart_detected#L5)):*
nit: this is implied

---

*[sql/testdata/serializable_restart_detected, line 47 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4292#-KABlMTtQ7TonMAIQObW:-KABlMTuTm4W8VnweaZu:-1865903358) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bc8f5307322baaaf76a5266c815f4f145e42b1d/sql/testdata/serializable_restart_detected#L47)):*
grammar

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4292#-:-KABlOyjL7tqouRfDaDE:-314412946)*

**Comment by tschottdorf** [comment]
Got them on my priority queue, so I'll fix them right here.

**Comment by bdarnell** [comment]
I think we have seen something kind of like this before although I can't find the issue now. The previous issue was less obviously inconsistent (we weren't repeating the same statement twice), but still involved a read that returned bad results but there was no indication that something was wrong until the commit failed with a retry error.

**Comment by tschottdorf** [comment]
We saw these with `CPut`s but the underlying sister issue #4293 (basically same problem) is the one that's alarming me. We apparently never tested that a SNAPSHOT transaction sticks to its snapshot.

**Comment by bdarnell** [comment]
Ah, yes. That's bad.

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/testdata/serializable_restart_detected, line 14 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4292#-KADTpO8Ci1wdlWqUSNy:-KADTpO8Ci1wdlWqUSNz:509263804) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bc8f5307322baaaf76a5266c815f4f145e42b1d/sql/testdata/serializable_restart_detected#L14)):*
I thought this was the default

---

*[sql/testdata/serializable_restart_detected, line 34 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4292#-KADWBUPGVhSkC_dweej:-KADWBUQHbnAXPhMMUrb:2015774504) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bc8f5307322baaaf76a5266c815f4f145e42b1d/sql/testdata/serializable_restart_detected#L34)):*
Why is an insert going to see a read cache value? I forget how an insert of value 2 sees the read entry of 1 which was viewed through a SELECT *. Is there some kind of prefix key in the read cache which represents all keys from a table?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4292)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/testdata/serializable_restart_detected, line 14 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4292#-KADTpO8Ci1wdlWqUSNy:-KADfVLCxEddcjbBWPr-:364824571) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bc8f5307322baaaf76a5266c815f4f145e42b1d/sql/testdata/serializable_restart_detected#L14)):*
yes, but this test shouldn't change if the default does.

---

*[sql/testdata/serializable_restart_detected, line 34 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4292#-KADWBUPGVhSkC_dweej:-KADfXax1G9-Bh_6pvCP:-1121908566) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bc8f5307322baaaf76a5266c815f4f145e42b1d/sql/testdata/serializable_restart_detected#L34)):*
the insert gets moved higher in time by the read timestamp cache which was populated with a higher timestamp for all keys by the `select *`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4292)*

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/testdata/serializable_restart_detected, line 34 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4292#-KADWBUPGVhSkC_dweej:-KAGXvfGeEvuZqgbL2j7:1971384162) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bc8f5307322baaaf76a5266c815f4f145e42b1d/sql/testdata/serializable_restart_detected#L34)):*
so the timestamp cache does contain a prefix key for all keys matching all rows in the table.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4292)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/testdata/serializable_restart_detected, line 34 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4292#-KADWBUPGVhSkC_dweej:-KAG_VgjbRdKJTrJpVZu:983550848) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bc8f5307322baaaf76a5266c815f4f145e42b1d/sql/testdata/serializable_restart_detected#L34)):*
the timestamp cache will have an entry for something like `[.../Table10, /Table11)`, or whatever the endpoints of the `Scan` which carries out the `SELECT *` are.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4292)*

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/testdata/serializable_restart_detected, line 34 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4292#-KADWBUPGVhSkC_dweej:-KAGo9WogF5sM750cUr-:795446716) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bc8f5307322baaaf76a5266c815f4f145e42b1d/sql/testdata/serializable_restart_detected#L34)):*
thanks

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4292)*

**Comment by tamird** [comment]
LGTM

---

Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4292#-:-KAbUnwabGFpEk93_1I5:676834233)*

**Pull request merged**
