### PR TITLE
util/quotapool: add an allocation efficient fifo for chan struct{}

### PR DESCRIPTION
**Pull request by ajwerner**
This is especially useful in upcoming work on admission control but can also be
used in QuotaPool.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
Yet another place where generic data structures would be very nice. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38098#-:-LgmGksI0Kn4yvH1k4jx:b-llk3dm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by ajwerner** [comment]
Benchmarks when applied to the QuotaPool, that commit to follow after #37342 is merged.
```
name                                            old time/op    new time/op    delta
IntQuotaPool-8                                     973ns ±32%     772ns ±10%   -20.66%  (p=0.000 n=20+14)
ConcurrentIntQuotaPool/workers=1,quota=1-8        1.57µs ±12%    1.24µs ± 9%   -20.65%  (p=0.000 n=19+18)
ConcurrentIntQuotaPool/workers=2,quota=2-8        1.82µs ±17%    1.43µs ±11%   -21.29%  (p=0.000 n=20+17)
ConcurrentIntQuotaPool/workers=8,quota=4-8        3.67µs ±12%    3.17µs ± 5%   -13.63%  (p=0.000 n=20+20)
ConcurrentIntQuotaPool/workers=128,quota=4-8      4.15µs ±39%    3.34µs ± 7%   -19.45%  (p=0.000 n=20+19)
ConcurrentIntQuotaPool/workers=512,quota=128-8    4.53µs ±21%    3.68µs ± 5%   -18.77%  (p=0.000 n=19+20)
ConcurrentIntQuotaPool/workers=512,quota=513-8    4.48µs ±21%    3.70µs ±10%   -17.35%  (p=0.000 n=20+20)
IntQuotaPoolFunc-8                                1.46µs ±39%    1.18µs ± 7%   -19.18%  (p=0.000 n=19+20)

name                                            old alloc/op   new alloc/op   delta
IntQuotaPool-8                                     8.00B ± 0%     0.00B       -100.00%  (p=0.000 n=20+20)
ConcurrentIntQuotaPool/workers=1,quota=1-8         8.00B ± 0%     0.00B       -100.00%  (p=0.000 n=20+20)
ConcurrentIntQuotaPool/workers=2,quota=2-8         8.00B ± 0%     0.00B       -100.00%  (p=0.000 n=20+20)
ConcurrentIntQuotaPool/workers=8,quota=4-8         16.0B ± 0%      0.0B       -100.00%  (p=0.000 n=20+20)
ConcurrentIntQuotaPool/workers=128,quota=4-8       16.0B ± 0%      0.0B       -100.00%  (p=0.000 n=20+20)
ConcurrentIntQuotaPool/workers=512,quota=128-8     21.0B ± 0%      2.0B ± 0%   -90.48%  (p=0.000 n=15+16)
ConcurrentIntQuotaPool/workers=512,quota=513-8     28.8B ±25%      3.2B ±55%   -88.82%  (p=0.000 n=18+18)
IntQuotaPoolFunc-8                                 24.0B ± 0%     16.0B ± 0%   -33.33%  (p=0.000 n=20+20)

name                                            old allocs/op  new allocs/op  delta
IntQuotaPool-8                                      1.00 ± 0%      0.00       -100.00%  (p=0.000 n=20+20)
ConcurrentIntQuotaPool/workers=1,quota=1-8          1.00 ± 0%      0.00       -100.00%  (p=0.000 n=20+20)
ConcurrentIntQuotaPool/workers=2,quota=2-8          1.00 ± 0%      0.00       -100.00%  (p=0.000 n=20+20)
ConcurrentIntQuotaPool/workers=8,quota=4-8          0.00           0.00           ~     (all equal)
ConcurrentIntQuotaPool/workers=128,quota=4-8        0.00           0.00           ~     (all equal)
ConcurrentIntQuotaPool/workers=512,quota=128-8      0.00           0.00           ~     (all equal)
ConcurrentIntQuotaPool/workers=512,quota=513-8      0.00           0.00           ~     (all equal)
IntQuotaPoolFunc-8                                  2.00 ± 0%      1.00 ± 0%   -50.00%  (p=0.000 n=20+20)
```

**Review by nvb — COMMENTED** [review]
Very cool!

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38098#-:-Lgn2OiZ8Q-jlH511c5M:b-jdo7t9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/util/notifyqueue/notify_queue.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38098#-Lgn-TlA95_mWzzUB09q:-Lgn-TlBBkiOFFRbltGm:b3e34ya) ([raw file](https://github.com/cockroachdb/cockroach/blob/229b0169986a5d3b8ea430080d60d9ffcdbcb22a/pkg/util/notifyqueue/notify_queue.go#L25)):*
> ```Go
> //
> // TODO(ajwerner): Justify this further.
> // Each node is 32 + 8 * blockSize bytes so at 28 a node is 256 bytes which
> ```

This does seem like a nice number. Consider adding something like:
```
func init() {
    const expNodeSize = 256
    nodeSize := unsafe.Sizeof(node{})
    if nodeSize != expNodeSize {
        panic("...")
    }
}
```
___
*[pkg/util/notifyqueue/notify_queue.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38098#-Lgn0I54-5qQnjf-zOaR:-Lgn0I553fKi2vJqO3u6:b-vbdgji) ([raw file](https://github.com/cockroachdb/cockroach/blob/229b0169986a5d3b8ea430080d60d9ffcdbcb22a/pkg/util/notifyqueue/notify_queue.go#L50)):*
> ```Go
> }
> 
> // NotifyQueue provides an allocation efficient FIFO for chan struct{}.
> ```

s/FIFO/FIFO queue/

Note that this is not safe for concurrent use.
___
*[pkg/util/notifyqueue/notify_queue.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38098#-Lgn0aGO-1IvjOQGDY6z:-Lgn0aGO-1IvjOQGDY7-:b-wsdmb8) ([raw file](https://github.com/cockroachdb/cockroach/blob/229b0169986a5d3b8ea430080d60d9ffcdbcb22a/pkg/util/notifyqueue/notify_queue.go#L57)):*
> ```Go
> }
> 
> var defaultPool = NewPool()
> ```

When would we ever not want a global pool?
___
*[pkg/util/notifyqueue/notify_queue.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38098#-Lgn1O3qD5oONICCrDcB:-Lgn1O3qD5oONICCrDcC:b-86uarl) ([raw file](https://github.com/cockroachdb/cockroach/blob/229b0169986a5d3b8ea430080d60d9ffcdbcb22a/pkg/util/notifyqueue/notify_queue.go#L72)):*
> ```Go
> 	}
> 	if !q.head.prev.enqueue(c) {
> 		tail := q.head.prev
> ```

nit: I'd pull this up a line so that it's clear that we only even enqueue in the tail node.
___
*[pkg/util/notifyqueue/notify_queue.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38098#-Lgn1dlO-_riR14OJCL5:-Lgn1dlO-_riR14OJCL6:bryqih7) ([raw file](https://github.com/cockroachdb/cockroach/blob/229b0169986a5d3b8ea430080d60d9ffcdbcb22a/pkg/util/notifyqueue/notify_queue.go#L78)):*
> ```Go
> 		newTail.prev = tail
> 		newTail.next = q.head
> 		newTail.enqueue(c)
> ```

Maybe `if !newTail.enqueue(c) { panic() }`
___
*[pkg/util/notifyqueue/notify_queue.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38098#-Lgn12Bt3zyAWsQjoqpf:-Lgn12Bt3zyAWsQjoqpg:b-7kc15g) ([raw file](https://github.com/cockroachdb/cockroach/blob/229b0169986a5d3b8ea430080d60d9ffcdbcb22a/pkg/util/notifyqueue/notify_queue.go#L111)):*
> ```Go
> }
> 
> // Peek returns the current head of the queue or nil if the queeu is empty.
> ```

queue
___
*[pkg/util/quotapool/quotapool.go, line 122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38098#-Lgn25L63Z5KV5pjiK-A:-Lgn25L63Z5KV5pjiK-B:bs1apsb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2088f00ecf0e85bbc4880e4d061a0af8e3ddc191/pkg/util/quotapool/quotapool.go#L122)):*
> ```Go
> 		// blocking subsequent notifications to the channel by filling up the
> 		// channel buffer.
> 		q *notifyqueue.NotifyQueue
> ```

I have a minor preference for avoiding the indirection here. That's trivially possible, right?

**Review by ajwerner — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38098#-:-Lgn9dKT7iHHQeIY9Y_g:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/util/notifyqueue/notify_queue.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38098#-Lgn-TlA95_mWzzUB09q:-Lgn6uyuD_fAWbyx1OzU:b1of6of) ([raw file](https://github.com/cockroachdb/cockroach/blob/229b0169986a5d3b8ea430080d60d9ffcdbcb22a/pkg/util/notifyqueue/notify_queue.go#L25)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This does seem like a nice number. Consider adding something like:
```
func init() {
    const expNodeSize = 256
    nodeSize := unsafe.Sizeof(node{})
    if nodeSize != expNodeSize {
        panic("...")
    }
}
```
</blockquote></details>

Added a test rather than an init check. I agree it's good to validate the assumption but didn't see a good reason to link it to the real code. 
___
*[pkg/util/notifyqueue/notify_queue.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38098#-Lgn0aGO-1IvjOQGDY6z:-Lgn4crqDiWICYwqeDcR:binleqr) ([raw file](https://github.com/cockroachdb/cockroach/blob/229b0169986a5d3b8ea430080d60d9ffcdbcb22a/pkg/util/notifyqueue/notify_queue.go#L57)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

When would we ever not want a global pool?
</blockquote></details>

I guess my feeling was that global singletons are somehow evil? My "blocking queue" in the admission controller has a `Pool` to share buffers for all of its queues but I suppose you're right, no reason not to share buffers across all of them.

I've hidden the `pool`.

**Comment by ajwerner** [comment]
After typing some more admission controller code I realized I wanted something slightly different for the queuing behavior, in particular, the ability to notify whether a request was being admitted or rejected. I probably could have make it work with a `chan struct{}` and then some looking around after the blocked goroutine is unblocked but wasn't sure it was the cleanest way to implement what I wanted.

I'm moving this optimization to be unexported inside of the quotapool package.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38098)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/util/quotapool/notify_queue.go, line 67 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38098#-Lh_okVa3PowQMj_KYrr:-Lh_okVa3PowQMj_KYrs:b2szuly) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd86011e4378fa5a6aaf1139161bf4fd0c397a57/pkg/util/quotapool/notify_queue.go#L67)):*
> ```Go
> }
> 
> // dequeue removes the head of the queue and returns it and nil if the queue is
> ```

I suppose this and should be an or.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38098#-:-Lh_q_fi0jXHgwKpwi5t:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/util/quotapool/node_size_test.go, line 24 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38098#-Lh_q8nG6JwcwxoI23sd:-Lh_q8nG6JwcwxoI23se:b-d382t9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3ae728c01b8ac58eae6f5c0bef12533e086152/pkg/util/quotapool/node_size_test.go#L24)):*
I was actually expecting

> ```
> assert.Equal(t, 256, int(unsafe.Sizeof(node{})))
> ```

Thinking about this more though, maybe it's not a great idea. I think this will fail on 32-bit systems, which is pretty lame.
___
*[pkg/util/quotapool/notify_queue.go, line 67 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38098#-Lh_okVa3PowQMj_KYrr:-Lh_qaSo3_Mi4PSjGBzC:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd86011e4378fa5a6aaf1139161bf4fd0c397a57/pkg/util/quotapool/notify_queue.go#L67)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I suppose this and should be an or.
</blockquote></details>

+1

**Review by ajwerner — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38098#-:-Lha0NXzDd8aid8_IEp-:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/util/quotapool/node_size_test.go, line 24 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38098#-Lh_q8nG6JwcwxoI23sd:-Lha0G622mHDxHrt7ONI:b-ha3fz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3ae728c01b8ac58eae6f5c0bef12533e086152/pkg/util/quotapool/node_size_test.go#L24)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I was actually expecting

> ```
> assert.Equal(t, 256, int(unsafe.Sizeof(node{})))
> ```

Thinking about this more though, maybe it's not a great idea. I think this will fail on 32-bit systems, which is pretty lame.
</blockquote></details>

Changed the ints to int64 so it will work on different word size machines.

**Review by nvb — APPROVED** [review]
> Reviewed 3 of 3 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38098)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by ajwerner** [comment]
bors r=nvanbenschoten

**Pull request merged**
