### PR TITLE
sql: record sql CPU nanoseconds in statement statistics table

### PR DESCRIPTION
**Pull request by DrewKimball**
This patch adds a `cpu_nanos` field to the `crdb_internal` and `system` statement and transaction statistics tables that tracks the CPU time in nanoseconds spent during SQL execution. Note that similar to disk and memory usage, CPU time is tracked on a sampling basis. Future work will display this field in the UI.

Informs #87213

Release note (sql change): Added a `cpuNanos` field to the statistics column of the `crdb_internal.statement_statistics` and `system.statement_statistics` tables that reports the amount of CPU time in nanoseconds during SQL execution for queries that track CPU time.

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
Looks great!
You're missing some updates on `statements.spec.tsx` and `appStats.spec.ts`, and some nits to deal with the lint errors.
Otherwise :lgtm: 

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95639#-:-NMU0ucW84rPsVCd4pJW:b4kdezb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @yuzefovich)

___
*[`pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts` line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95639#-NMU1l_m7e2NdJ9wBBOb:-NMU1l_m7e2NdJ9wBBOc:bi434vq) ([raw file](https://github.com/cockroachdb/cockroach/blob/42169a6481bd1b0e006b7b2d1b0c7d81641151bc/pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts#L129)):*
> ```XML
>       countA,
>       countB,
>     )
> ```

nit: you will get a lint error if you don't add `,` here
___
*[`pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.fixture.ts` line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95639#-NMU1v6N2qcB-oCis64k:-NMU1v6N2qcB-oCis64l:b-y6fuo5) ([raw file](https://github.com/cockroachdb/cockroach/blob/42169a6481bd1b0e006b7b2d1b0c7d81641151bc/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.fixture.ts#L51)):*
> ```XML
>     mean: 80,
>     squared_diffs: 0.01,
>   }
> ```

nit: add `,` (lint error)
___
*[`pkg/ui/workspaces/cluster-ui/src/util/totalWorkload.fixture.ts` line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95639#-NMU1tUfBExZDR1QQqCd:-NMU1tUfBExZDR1QQqCe:b-y6fuo5) ([raw file](https://github.com/cockroachdb/cockroach/blob/42169a6481bd1b0e006b7b2d1b0c7d81641151bc/pkg/ui/workspaces/cluster-ui/src/util/totalWorkload.fixture.ts#L47)):*
> ```XML
>     mean: 4160407,
>     squared_diffs: 47880000000000,
>   }
> ```

nit: add `,` (lint error)

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95639#-:-NMUqldu4R7y6jZaiEyS:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95639#-NMUqB597Aq-6xHB3Irt):*
nit: these tables are not "system" but are virtual internal, right?

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95639)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95639#-NMUqB597Aq-6xHB3Irt):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: these tables are not "system" but are virtual internal, right?
</blockquote></details>

Changed "system" to "internal".
___
*[`pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts` line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95639#-NMU1l_m7e2NdJ9wBBOb:-NMVCt0D0j_weV3ILMar:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/42169a6481bd1b0e006b7b2d1b0c7d81641151bc/pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts#L129)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: you will get a lint error if you don't add `,` here
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.fixture.ts` line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95639#-NMU1v6N2qcB-oCis64k:-NMVCxff8n7IMr37F5uA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/42169a6481bd1b0e006b7b2d1b0c7d81641151bc/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.fixture.ts#L51)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: add `,` (lint error)
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/util/totalWorkload.fixture.ts` line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95639#-NMU1tUfBExZDR1QQqCd:-NMVD3iB1SJuEWkCF4qO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/42169a6481bd1b0e006b7b2d1b0c7d81641151bc/pkg/ui/workspaces/cluster-ui/src/util/totalWorkload.fixture.ts#L47)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: add `,` (lint error)
</blockquote></details>

Done.

**Review by maryliag — COMMENTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95639)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball and @yuzefovich)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95639#-NMUqB597Aq-6xHB3Irt):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Changed "system" to "internal".
</blockquote></details>

actually is both, because exists in crdb_internal and then gets flushed to system table, so users can see this data in both places.
The changes added here will affect both tables, so you can keep the description for both. (same thing for the release note)

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95639)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @maryliag and @yuzefovich)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95639#-NMUqB597Aq-6xHB3Irt):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

actually is both, because exists in crdb_internal and then gets flushed to system table, so users can see this data in both places.
The changes added here will affect both tables, so you can keep the description for both. (same thing for the release note)
</blockquote></details>

Updated the descriptions to refer to both.

**Comment by DrewKimball** [comment]
TFTRs!

bors r+

**Comment by DrewKimball** [comment]
Looks like a flake.

bors r+

**Pull request merged**
