### PR TITLE
bench/ddl_analysis: fix test for real

### LINKED ISSUE #61856: bench/ddl_analysis: TestBenchmarkExpectation failed
[(bench/ddl_analysis).TestBenchmarkExpectation failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2767705&tab=buildLog) on [master@a86cf540219a82234187db11434ab664fe335f17](https://github.com/cockroachdb/cockroach/commits/a86cf540219a82234187db11434ab664fe335f17):

```
BenchmarkRevokeRole/revoke_2_roles
BenchmarkRevokeRole/revoke_2_roles-16                                               	       1	 175696610 ns/op	        31.0 roundtrips
    ddl_analysis_bench.go:107: -- test log scope end --
BenchmarkORMQueries
    test_log_scope.go:73: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logBenchmarkORMQueries732589748
    test_log_scope.go:74: use -show-logs to present logs inline
BenchmarkORMQueries/django_table_introspection_1_table
BenchmarkORMQueries/django_table_introspection_1_table-16                           	       1	  37953698 ns/op	        10.0 roundtrips
BenchmarkORMQueries/django_table_introspection_4_tables
BenchmarkORMQueries/django_table_introspection_4_tables-16                          	       1	 114071576 ns/op	        13.0 roundtrips
BenchmarkORMQueries/django_table_introspection_8_tables
BenchmarkORMQueries/django_table_introspection_8_tables-16                          	       1	 125694843 ns/op	        17.0 roundtrips
BenchmarkORMQueries/activerecord_type_introspection_query
BenchmarkORMQueries/activerecord_type_introspection_query-16                        	       1	  33336729 ns/op	         5.00 roundtrips
    ddl_analysis_bench.go:107: -- test log scope end --
BenchmarkSystemDatabaseQueries
    test_log_scope.go:73: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logBenchmarkSystemDatabaseQueries631603339
    test_log_scope.go:74: use -show-logs to present logs inline
BenchmarkSystemDatabaseQueries/select_system.users_with_schema_name
BenchmarkSystemDatabaseQueries/select_system.users_with_schema_name-16              	       1	   3526672 ns/op	         3.00 roundtrips
BenchmarkSystemDatabaseQueries/select_system.users_without_schema_name
BenchmarkSystemDatabaseQueries/select_system.users_without_schema_name-16           	       1	  13879778 ns/op	         4.00 roundtrips
BenchmarkSystemDatabaseQueries/select_system.users_with_empty_database_name
BenchmarkSystemDatabaseQueries/select_system.users_with_empty_database_name-16      	       1	   4060221 ns/op	         3.00 roundtrips
    ddl_analysis_bench.go:107: -- test log scope end --
BenchmarkTruncate
    test_log_scope.go:73: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logBenchmarkTruncate701464068
    test_log_scope.go:74: use -show-logs to present logs inline
BenchmarkTruncate/truncate_1_column_0_rows
BenchmarkTruncate/truncate_1_column_0_rows-16                                       	       1	 169310072 ns/op	        22.0 roundtrips
BenchmarkTruncate/truncate_1_column_1_row
BenchmarkTruncate/truncate_1_column_1_row-16                                        	       1	 173882345 ns/op	        22.0 roundtrips
BenchmarkTruncate/truncate_1_column_2_rows
BenchmarkTruncate/truncate_1_column_2_rows-16                                       	       1	 199784519 ns/op	        22.0 roundtrips
BenchmarkTruncate/truncate_2_column_0_rows
BenchmarkTruncate/truncate_2_column_0_rows-16                                       	       1	 149220333 ns/op	        22.0 roundtrips
BenchmarkTruncate/truncate_2_column_1_rows
BenchmarkTruncate/truncate_2_column_1_rows-16                                       	       1	 124147490 ns/op	        22.0 roundtrips
BenchmarkTruncate/truncate_2_column_2_rows
BenchmarkTruncate/truncate_2_column_2_rows-16                                       	       1	  87393345 ns/op	        22.0 roundtrips
    ddl_analysis_bench.go:107: -- test log scope end --
BenchmarkVirtualTableQueries
    test_log_scope.go:73: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logBenchmarkVirtualTableQueries457240831
    test_log_scope.go:74: use -show-logs to present logs inline
BenchmarkVirtualTableQueries/select_crdb_internal.tables_with_1_fk
BenchmarkVirtualTableQueries/select_crdb_internal.tables_with_1_fk-16               	       1	  14032247 ns/op	         1.00 roundtrips
BenchmarkVirtualTableQueries/select_crdb_internal.invalid_objects_with_1_fk
BenchmarkVirtualTableQueries/select_crdb_internal.invalid_objects_with_1_fk-16      	       1	  15087125 ns/op	         1.00 roundtrips
    ddl_analysis_bench.go:107: -- test log scope end --
--- FAIL: TestBenchmarkExpectation (128.08s)

```

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestBenchmarkExpectation PKG=./pkg/bench/ddl_analysis TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestBenchmarkExpectation.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by ajwerner**
See individual commits. Last is the critical one. 

Fixes #61856.

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
nice find

> Reviewed 2 of 3 files at r1, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61877#-:-MVceG6k4OiCqeJdvdMG:bhpdd87)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by knz** [comment]
I think this is good to go? (after a rebase and release justification string)

**Comment by ajwerner** [comment]
> I think this is good to go? (after a rebase and release justification string)

I thought the release justification is over?

I'm working on getting it all past CI and then yes, it'll get merged. I skewed with something that changed the round-trips.

**Pull request merged**
