### PR TITLE
distsqlrun: make txn mem mon own local flow's

### LINKED ISSUE #25879: distsqlrun: hook up local distsql flows to their session monitors
Currently, distsql flows that are local to the coordinator node don't get attached to the session's memory monitor. This is a bit of an annoyance, as it makes it more difficult to understand a session's full memory usage.

Local distsql flows should be parented by their originating session, not by the root distsql monitor.

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, DistSQL flows that were local to the coordinator node used a
memory monitor that was owned by a generic distsql memory monitor. This
was misleading, as it prevented memory used by distsql local to a node
from showing up in the query's used memory.

Now, a query's transaction memory monitor is passed to the local distsql
flow created for it. The remote distsql flows still are monitored by the
generic distsql one, but this is a start at bettering the situation.

Closes #25879.

Release note: None

### CODE REVIEW

**Comment by arjunravinarayan** [comment]
:lgtm: :shipit: 

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26108#-:-LDgOonB-puBlDiuSCzA:byzm7aw)*

**Comment by asubiotto** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/sql/distsqlplan/aggregator_funcs_test.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26108#-LDgUnj3DgdlpKU_rKfR:-LDgUnj3DgdlpKU_rKfS:b6pblmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/bce546c85c7b00e2e39633ef5e3ae1618d7471c1/pkg/sql/distsqlplan/aggregator_funcs_test.go#L71)):*
> ```Go
> 	var rowBuf distsqlrun.RowBuffer
> 
> 	ctx, flow, err := distSQLSrv.SetupSyncFlow(context.TODO(), distSQLSrv.ParentMemoryMonitor, &req, &rowBuf)
> ```

It's a bit confusing that you use `ParentMemoryMonitor` in this test but `memMonitor` in `flow_registry_test`. I believe the difference is that the first one is the `root` monitor and `memMonitor` is the `distsql` monitor created in `NewServer`. I would use `memMonitor` here and add a comment to `ParentMemoryMonitor` that it should only be used when setting up a server.

---

*[pkg/sql/distsqlrun/server.go, line 406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26108#-LDgViFP6A2omXMjbGwk:-LDgViFP6A2omXMjbGwl:bh32w88) ([raw file](https://github.com/cockroachdb/cockroach/blob/bce546c85c7b00e2e39633ef5e3ae1618d7471c1/pkg/sql/distsqlrun/server.go#L406)):*
> ```Go
> // Flow.Cleanup.
> func (ds *ServerImpl) SetupSyncFlow(
> 	ctx context.Context, mon *mon.BytesMonitor, req *SetupFlowRequest, output RowReceiver,
> ```

nit: I would also call this `parentMonitor` to be clear

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26108#-:-LDgW4SnDA74cRTDHhdL:bnfp4nl)*

**Comment by jordanlewis** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlplan/aggregator_funcs_test.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26108#-LDgUnj3DgdlpKU_rKfR:-LDgYLom-EuwpUkbNUqH:b-8tdzxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/bce546c85c7b00e2e39633ef5e3ae1618d7471c1/pkg/sql/distsqlplan/aggregator_funcs_test.go#L71)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It's a bit confusing that you use `ParentMemoryMonitor` in this test but `memMonitor` in `flow_registry_test`. I believe the difference is that the first one is the `root` monitor and `memMonitor` is the `distsql` monitor created in `NewServer`. I would use `memMonitor` here and add a comment to `ParentMemoryMonitor` that it should only be used when setting up a server.
</blockquote></details>

Yeah... but this is in a different package, so you can't use the unexported `memMonitor` field :(


I'll add a comment to `ParentMemoryMonitor` though.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26108)*

**Pull request merged**
