### PR TITLE
changefeedcc: Acquire memory prior to issuing scan RPCs

### PR DESCRIPTION
**Pull request by miretskiy**
During initial scan or a backfill, changefeeds issue parallel scan RPCs to perform this operation.
Changefeed would then move events received from those RPCs into a memory accounted buffer.
However, the memory used by those RPC replies, prior to them being added to the memory buffer, was not accounted for.  This may lead to potential memory blow up, up to, and including node OOMs, particularly when running many of those requests.

This PR adds memory accounting for those RPC replies by reserving needed memory prior to issuing those RPCs.

In addition, reduce the default size of the scan reply from prior default of 16MB down to 512KB.  This change should improve overall stability.

Epic: none

Release note (enterprise change): Changefeed account for transient memory needed to perform initial scan.
Reduce the default size of scan RPC replies to improve cluster stability.

### CODE REVIEW

**Comment by miretskiy** [comment]
Informs https://github.com/cockroachlabs/support/issues/2022

**Review by jayshrivastava — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95798)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[`pkg/ccl/changefeedccl/kvevent/blocking_buffer.go` line 237 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95798#-NMntbTF9ZGaP5gYwjga:-NMntbTF9ZGaP5gYwjgb:b-to2lo) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc932b0aefac8b659f7639def224055b160e8cac/pkg/ccl/changefeedccl/kvevent/blocking_buffer.go#L237)):*
> ```Go
> 	}
> 	alloc.init(n, &b.qp)
> 	if err := func() error {
> ```

Why is this in a fcn? I see we do a similar thing elsewhere and we know it works.

Also, can you add a comment in `b.req` that it explains that we reuse the struct to save allocs. At first glance, it's confusing to see us lock the request and hold the lock while passing a ptr to it into `Acquire`. The comment might help.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95798)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava)

___
*[`pkg/ccl/changefeedccl/kvevent/blocking_buffer.go` line 237 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95798#-NMntbTF9ZGaP5gYwjga:-NMnvPyj3CO3W7tv3bw9:b-ql1ehn) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc932b0aefac8b659f7639def224055b160e8cac/pkg/ccl/changefeedccl/kvevent/blocking_buffer.go#L237)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

Why is this in a fcn? I see we do a similar thing elsewhere and we know it works.

Also, can you add a comment in `b.req` that it explains that we reuse the struct to save allocs. At first glance, it's confusing to see us lock the request and hold the lock while passing a ptr to it into `Acquire`. The comment might help.
</blockquote></details>

It is in a function to take a scoped lock and to always release it -- even when error occurs.
I don't know about comment on locking.  It's not about reusing alloc; it's about the fact
that blocking buffer Add method may be called concurrently, and we want to serialize memory acquisition -- which is what the locks are used for (so I'm not sure why we'd need to explain that).

We probably could add a comment on the Writer interface (that Add is safe to called concurrently).

**Review by jayshrivastava — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95798)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[`pkg/ccl/changefeedccl/kvevent/blocking_buffer.go` line 237 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95798#-NMntbTF9ZGaP5gYwjga:-NMnwd7L-8_H9sNqCXIy:b4e170m) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc932b0aefac8b659f7639def224055b160e8cac/pkg/ccl/changefeedccl/kvevent/blocking_buffer.go#L237)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

It is in a function to take a scoped lock and to always release it -- even when error occurs.
I don't know about comment on locking.  It's not about reusing alloc; it's about the fact
that blocking buffer Add method may be called concurrently, and we want to serialize memory acquisition -- which is what the locks are used for (so I'm not sure why we'd need to explain that).

We probably could add a comment on the Writer interface (that Add is safe to called concurrently).
</blockquote></details>

Sure. In that case, this LGTM.

**Comment by miretskiy** [comment]
blathers backport 22.2

**Pull request merged**
