### PR TITLE
util: allow for newline characters in nodes

### PR DESCRIPTION
**Pull request by madhavsuresh**
This PR treats newline characters in input strings
as a split token. Previously when a node string
had a newline character, the text after the carriage return
was not indented correctly.

Release note: None

### CODE REVIEW

**Comment by madhavsuresh** [comment]
some yak shaving here: With the child node `1.3.2\n1.3.3` do you think the output with a newline should be: 
```root
 │
 ├── 1
 │    ├── 1.1
 │    ├── 1.2
 │    │    │
 │    │    │
 │    │    ├── 1.2.1
 │    │    │
 │    │    └── 1.2.2
 │    ├── 1.3
 │    │    │
 │    │    ├── 1.3.1
 │    │    ├── 1.3.2
 │    │    └── 1.3.3
 │    │
 │    └── 1.4
 └── 2```
or 
```
```root
 │
 ├── 1
 │    ├── 1.1
 │    ├── 1.2
 │    │    │
 │    │    │
 │    │    ├── 1.2.1
 │    │    │
 │    │    └── 1.2.2
 │    ├── 1.3
 │    │    │
 │    │    ├── 1.3.1
 │    │    ├── 1.3.2
 │    │             1.3.3
 │    │
 │    └── 1.4
 └── 2```

**Review by RaduBerinde — COMMENTED** [review]
Neither, I think it should be:
```
 │
 ├── 1
 │    ├── 1.1
 │    ├── 1.2
 │    │    │
 │    │    │
 │    │    ├── 1.2.1
 │    │    │
 │    │    └── 1.2.2
 │    ├── 1.3
 │    │    │
 │    │    ├── 1.3.1
 │    │    └── 1.3.2
 │    │        1.3.3
 │    │
 │    └── 1.4
 └── 2
```

Just adding the lines as separate children is something the caller can do easily today.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30132#-:-LME0xoY0h7TuaAB6hfE:bfkn0li)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by madhavsuresh — COMMENTED** [review]
Thanks for the help offline @RaduBerinde. PTAL. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30132#-:-LMEGQSL5wx6SdIOpqIx:b-5xay6s)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30132#-:-LMELbhc5_jJkN6dqn26:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/util/treeprinter/tree_printer.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30132#-LMELNNR9-AXTtpnPwzm:-LMELNNR9-AXTtpnPwzn:b-3otuao) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ec769e98da30a676a910ff52c42ff374d400891/pkg/util/treeprinter/tree_printer.go#L42)):*
> ```Go
> //   root := n.Child("root")
> //   root.Child("child-1")
> //   root.Child("child-2").Child("grandchild").AddLine("grandchild-more-info")
> ```

[nit] change this to `Child("grandchild\ngrandchild-more-info")` since the example usage of `AddLine` is incorrect.
___
*[pkg/util/treeprinter/tree_printer.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30132#-LMELfp69n0xwhzgJXaL:-LMELfp69n0xwhzgJXaM:b-zdhl33) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ec769e98da30a676a910ff52c42ff374d400891/pkg/util/treeprinter/tree_printer.go#L81)):*
> ```Go
> }
> 
> // Child wraps ChildLine to allow for newline
> ```

This should be a description suitable for someone who wants to use this library (without caring how it works). I would just keep the previous comment, and add that multi-line strings are supported (with each line being indented appropriately).
___
*[pkg/util/treeprinter/tree_printer.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30132#-LMEJV3n60Ja_4XqFH9m:-LMEJV3n60Ja_4XqFH9n:bg268k4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ec769e98da30a676a910ff52c42ff374d400891/pkg/util/treeprinter/tree_printer.go#L83)):*
> ```Go
> // Child wraps ChildLine to allow for newline
> // characters to be treated as child nodes of the
> // given node
> ```

[nit] wrap at 80, add period at the end (same below)
___
*[pkg/util/treeprinter/tree_printer.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30132#-LMEK3UN1IIsq7as_SvM:-LMEK3UN1IIsq7as_SvN:bje9u5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ec769e98da30a676a910ff52c42ff374d400891/pkg/util/treeprinter/tree_printer.go#L85)):*
> ```Go
> // given node
> func (n Node) Child(text string) Node {
> 	splitLines := strings.Split(text, "\n")
> ```

This is probably not important, but given that this is meant as a general purpose thing, it would be nice to avoid unnecessary allocations in the common case. We could first check if we have newlines using `strings.ContainsRune` and just call ChildLine and exit early in that case.
___
*[pkg/util/treeprinter/tree_printer.go, line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30132#-LMEJZq86LogVnXQ6hod:-LMEJZq86LogVnXQ6hoe:b-zcckvn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ec769e98da30a676a910ff52c42ff374d400891/pkg/util/treeprinter/tree_printer.go#L87)):*
> ```Go
> 	splitLines := strings.Split(text, "\n")
> 	node := n.ChildLine(splitLines[0])
> 	if len(splitLines) > 1 {
> ```

[nit] this `if` is not necessary
___
*[pkg/util/treeprinter/tree_printer.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30132#-LMEKIcjDtI_W_OGfMq3:-LMEKIcjDtI_W_OGfMq4:b-6eby58) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ec769e98da30a676a910ff52c42ff374d400891/pkg/util/treeprinter/tree_printer.go#L112)):*
> ```Go
> 
> // Child adds a node as a child of the given node.
> func (n Node) ChildLine(text string) Node {
> ```

This should be a private method.

**Review by madhavsuresh — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30132#-:-LMEM1CR50iMjVEHXP4T:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by madhavsuresh — COMMENTED** [review]
yikes! I'm sorry, I completely missed the comments. All comments addressed. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30132#-:-LMEUopyDdJGoqXaeWAR:b-5uurhw)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by RaduBerinde — APPROVED** [review]
LGTM, thanks!

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30132#-:-LMEZGhd-qHB96_B00JZ:b2c0zcb)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/util/treeprinter/tree_printer.go, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30132#-LMEZEOn0c5rnxAB78wD:-LMEZEOn0c5rnxAB78wE:bk0qs4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/a25f3cf9b60bae8d588ea5e4822963cc323fa2e7/pkg/util/treeprinter/tree_printer.go#L111)):*
> ```Go
> }
> 
> // ChildLine adds a node as a child of the given node.
> ```

[nit] childLine

**Review by madhavsuresh — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30132#-:-LMEZOl00_m7jZjrJMBi:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by madhavsuresh — COMMENTED** [review]
bors r-

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30132#-:-LMEZWGl3z5FtwZfKSTI:b-ydi9aw)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by madhavsuresh — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30132#-:-LMEZrM-EOg7nOBkdnxM:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by madhavsuresh** [comment]
fixed linter errors

bors r+

**Pull request merged**
