### PR TITLE
ui: add transaction contention visualizer to Advanced Debug

### LINKED ISSUE #93512: ui: Add a transaction contention event visualizer to Advanced Debug
**Is your feature request related to a problem? Please describe.**
The `crdb_internal.transaction_contention_events` virtual table surfaces transaction contention events including information about the blocking and waiting transaction. This information lends itself well for a directed graph visualization, where the transactions are nodes and the contention events are edges in a directed graph.

**Describe the solution you'd like**
For a breather week project, we want to add a new page to the Advanced Debug page on the DB Console that visualizes transaction contention events in the form of a network graph. Additionally, the graph will be able to show the user more information about the transactions in contention as well as statement statistics.
 
**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by gtr**
Fixes #93512.

Part of a [breather week project](https://docs.google.com/document/d/1BgU8KMR4RWFgOo2qBxF6uG_i8PwTsFcP2X2D-fwGuJw) to implement txn contention visualization in db-console's advanced debug page.

Current UI:
image

Commit 1:
This commit introduces an API to get txn contention events from the
`crdb_internal.transaction_contention_events` virtual table joined with
the `crdb_internal.statement_statistics` virtual table to also get the
sql query into cluster ui.

Commit 2:
This commit adds a txn contention network graph to the Advanced
Debug page.

Release note (ui change): Added transaction contention graph to Advanced Debug page.

Commit 3:
This commit adds tests for the txn conention's redux layer by stubbing
contention events from the fakeApi.

Release note: None

Commit 4:
This commit properly adds the react-d3-graph dependency to
cluster-ui. The commit also includes some minor fixes to various
pieces of the visualizer middleware/frontend.

Release note: None

Commit 5:
This commit fixes a bug with the txn contention visualizer page link
from the advanced debug page, removes duplicate contentionNodes (from
the client side), and provides a `KeyedCAchedDAtaReducer` implementation
for `txnContentionEventReducerObj` (commented out so the UI can render
properly.

Release note (ui change): fixed txn contention visualizer page link.

### CODE REVIEW

**Review by ericharmeling — CHANGES_REQUESTED** [review]
Looking good! There are a few things we should probably change (see my comments)

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93509#-:-NJBTgDw3guOdAr1HLMD:bfbik62)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93509#-NJBQho42c2xO80rVf8q:-NJBQho42c2xO80rVf8r:b45h) ([raw file](https://github.com/cockroachdb/cockroach/blob/233c94c1f3ce89de86838008f8c2f645af142d67/pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts#L20)):*
> ```XML
> // TransactionContentionResponseColumns represents the columns returned by the 
> // txnContentionQuery.
> export type TransactionContentionResponseColumns = {
> ```





_Suggestion:_
```XML
ContentionEventResponseColumns
```
___
*[`pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93509#-NJBR2Mx9p76uQ__hVKg:-NJBR2Mx9p76uQ__hVKh:b-z5gl04) ([raw file](https://github.com/cockroachdb/cockroach/blob/233c94c1f3ce89de86838008f8c2f645af142d67/pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts#L29)):*
> ```XML
>     contending_key: string;
>     metadata: {
>         query: string;
> ```

I think we should just make this `query: string`.



_Code quote:_
```XML
    metadata: {
        query: string;
    };
```
___
*[`pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts` line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93509#-NJBR9-5EL0y99CafUGv:-NJBR9-5EL0y99CafUGw:bzci8h2) ([raw file](https://github.com/cockroachdb/cockroach/blob/233c94c1f3ce89de86838008f8c2f645af142d67/pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts#L34)):*
> ```XML
> 
> // Event represents a single transaction contention event.
> type Event = {
> ```

IMO, we should be more specific, as there are other event types out there.



_Suggestion:_
```XML
ContentionEvent
```
___
*[`pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts` line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93509#-NJBRJeX6Ajfyc2_BtbN:-NJBRJeX6Ajfyc2_BtbO:bvuhc56) ([raw file](https://github.com/cockroachdb/cockroach/blob/233c94c1f3ce89de86838008f8c2f645af142d67/pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts#L43)):*
> ```XML
> };
> 
> export type TransactionContentionEventsResponse = {
> ```

This is the name of the existing proto for the contention events status endpoint. We should name this something different.



_Suggestion:_
```XML
ContentionEventsResponse
```
___
*[`pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts` line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93509#-NJBRNfaBiK9eIondbI3:-NJBRNfaBiK9eIondbI4:b-p3xm7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/233c94c1f3ce89de86838008f8c2f645af142d67/pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts#L53)):*
> ```XML
> const txnContentionQuery = `
> SELECT collection_ts, blocking_txn_id, blocking_txn_fingerprint_id, waiting_txn_id, waiting_txn_fingerprint_id, contention_duration, contending_key, metadata
> FROM crdb_internal.transaction_contention_events
> ```

A few comments here:

- We are going to want to format this for legibility.
- We want to encode the txn fingerprint IDs, as they are in a raw `BYTES` format.
- We can directly access the `query` field of the `metadata` column.
- The transaction that we want to join on is the waiting txn, not the blocking txn.



_Suggestion:_
```XML
SELECT 
  collection_ts, 
  blocking_txn_id, 
  encode(
    blocking_txn_fingerprint_id, 'hex'
  ) AS blocking_txn_fingerprint_id, 
  waiting_txn_id, 
  encode(
    waiting_txn_fingerprint_id, 'hex'
  ) AS waiting_txn_fingerprint_id, 
  contention_duration, 
  crdb_internal.pretty_key(contending_key, 0) AS key, 
  prettify_statement(metadata ->> 'query', 108, 1, 1) AS query 
FROM 
  crdb_internal.transaction_contention_events AS tce 
  INNER JOIN crdb_internal.statement_statistics AS ss ON tce.waiting_txn_fingerprint_id = ss.transaction_fingerprint_id;
```

**Review by ericharmeling — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93509)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts` line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93509#-NJBVLADDIMHUQkMgCsf:-NJBVLADDIMHUQkMgCsg:bsi9vej) ([raw file](https://github.com/cockroachdb/cockroach/blob/233c94c1f3ce89de86838008f8c2f645af142d67/pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts#L43)):*
> ```XML
> };
> 
> export type TransactionContentionEventsResponse = {
> ```

We can probably simplify this type a bit.



_Suggestion:_
```XML
export type TransactionContentionEventsResponse = Event[]
```

**Review by ericharmeling — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93509)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93509#-NJBi82cA6WVwCTHWBAC:-NJBi82d7Q7H4eBbl0Hk:b6u935t) ([raw file](https://github.com/cockroachdb/cockroach/blob/233c94c1f3ce89de86838008f8c2f645af142d67/pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts#L36)):*
> ```XML
> type Event = {
>     waiting_txn_id: string,
>     blocking_txn_id: string,
> ```

We probably want to be more specific with some of these field names, and we should use camelCase for the purely typescript types (I think the response columns are fine, since that's what they look like in SQL).

Also, `statements` should be string array, and we should probably map the `query` response to a string array in `getTxnContentionEvents`.



_Suggestion:_
```XML
    waitingTxnExecutionID: string,
    blockingTxnExecutionID: string,
    statements?: string[],
    waitingTxnFingerprintID?: string,
    collectedAt: string,
    contentionDuration: string,
```

**Review by gtr — COMMENTED** [review]
TFTR! I also added the reducer object on the Redux layer, I'm unsure how to test it though.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93509#-:-NJBpd3u3BDK3t89vonA:b-lgw19d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93509#-NJBQho42c2xO80rVf8q:-NJBfnS29vU21MBuCiqa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/233c94c1f3ce89de86838008f8c2f645af142d67/pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts#L20)):*
> ```XML
> // TransactionContentionResponseColumns represents the columns returned by the 
> // txnContentionQuery.
> export type TransactionContentionResponseColumns = {
> ```

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93509#-NJBR2Mx9p76uQ__hVKg:-NJBiSWV-yBqzAzbAORS:bhd1dd9) ([raw file](https://github.com/cockroachdb/cockroach/blob/233c94c1f3ce89de86838008f8c2f645af142d67/pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts#L29)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

I think we should just make this `query: string`.
</blockquote></details>

I was unaware of the `->>` operator, neat. Thanks!
___
*[`pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts` line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93509#-NJBR9-5EL0y99CafUGv:-NJBfxnH0O4iIb1thzYk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/233c94c1f3ce89de86838008f8c2f645af142d67/pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts#L34)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

IMO, we should be more specific, as there are other event types out there.
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93509#-NJBi82cA6WVwCTHWBAC:-NJBp_TNAOQ2dtZjb_aU:b-o7vuhc) ([raw file](https://github.com/cockroachdb/cockroach/blob/233c94c1f3ce89de86838008f8c2f645af142d67/pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts#L36)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

We probably want to be more specific with some of these field names, and we should use camelCase for the purely typescript types (I think the response columns are fine, since that's what they look like in SQL).

Also, `statements` should be string array, and we should probably map the `query` response to a string array in `getTxnContentionEvents`.
</blockquote></details>

Good catch! Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts` line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93509#-NJBRJeX6Ajfyc2_BtbN:-NJBgTwh3F2uvMKVs03b:bbb0chy) ([raw file](https://github.com/cockroachdb/cockroach/blob/233c94c1f3ce89de86838008f8c2f645af142d67/pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts#L43)):*
> ContentionEventsResponse
Good catch, done.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts` line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93509#-NJBVLADDIMHUQkMgCsf:-NJBhKuC15Yxcp6bXO3U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/233c94c1f3ce89de86838008f8c2f645af142d67/pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts#L43)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

We can probably simplify this type a bit.
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts` line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93509#-NJBRNfaBiK9eIondbI3:-NJBiDe-C3wmw9xEHHcj:b-cugyy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/233c94c1f3ce89de86838008f8c2f645af142d67/pkg/ui/workspaces/cluster-ui/src/api/txnContentionApi.ts#L53)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

A few comments here:

- We are going to want to format this for legibility.
- We want to encode the txn fingerprint IDs, as they are in a raw `BYTES` format.
- We can directly access the `query` field of the `metadata` column.
- The transaction that we want to join on is the waiting txn, not the blocking txn.
</blockquote></details>

Yup, this is much more readable thanks!

**Pull request closed without merging**
