### PR TITLE
opt: Change Cast operator to use column type

### PR DESCRIPTION
**Pull request by andy-kimball**
opt: Change Cast optimizer expression to use column type

The Cast opt expression's target cast type is currently a datum type.
However, this means that SQL types such as VARCHAR(128) and SMALLINT
are converted to datum types that discard their width information. This
leads to incorrect behavior for queries like:

  SELECT 'hello'::VARCHAR(2)

This query should return 'he', but currently returns 'hello', because
the cast has been mapped to the STRING datum type, causing the width to
be ignored.

This commit updates the Cast optimizer expression to use a column type
rather than a datum type. The EliminateCast rule changes to only discard
the Cast if doing so will not lose type information. A new
TryCastTargetToDatumType method in the coltypes package can now be used
to determine  whether a particular Cast operation will lose type
information.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
Thanks Andy for starting the work on clarifying the relationship between DatumType and ColType.

For reference (for the other reviewers) there is a discussion ongoing to make this distinction disappear over time. We should be using just one set of types really.

That said, I am a bit confused about the goal here, the code and the commit message say two different things. Your commit message suggests the previous behavior is incorrect and this patch makes the behavior correct. 

If that is true, then:

1) I am missing the changes to `eval_test.go` which validate the new behavior
2) this commit needs a release note

If that is not true (i.e. the patch does not actually change the behavior, just the typing rules), then I would recommend rephrasing the commit message to actually explain what is going on.

Also for consistency I suspect that `AnnotateTypeExpr` needs to evolve in tandem with CastExpr.

---

Review status: 0 of 33 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25796#-:-LD6W73XCYZxy_S3DDPd:b-hxtg8n)*

**Comment by knz** [comment]
Also what's the rationale for changing `NewTypedCastExpr` and not the definition of the type field in `CastExpr`?

Also would the change in this PR inform the work needed for #22383 in any way?

**Comment by andy-kimball** [comment]
This PR is about changing the `Cast` *optimizer* expression, not the AST `CastExpr`. The `opt.Cast` *does* have a bug, which this PR fixes. There is currently no `opt` `AnnotateTypeExpr`, so no need to change that.

The `NewTypedCastExpr` method was added by the optimizer team some time back. It incorrectly used `coltypes.T` rather than `types.T`. The PR fixes that oversight. But this has no impact on the AST version of `CastExpr`, which is correct.

I've changed the PR message to clarify.

---

Review status: 0 of 33 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25796#-:-LD79sjkCu-dGX2bHVEY:bk2h5w7)*

**Comment by RaduBerinde** [comment]
:lgtm: 

@knz This change is fixing an optimizer-specific issue (the optimizer's Cast operator was losing type information). We are not changing `CastExpr` or any legacy code path. `NewTypedCastExpr` (which is only used by the optimizer) is changed so we can pass the complete type info.

---

Review status: 0 of 33 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25796#-:-LD7AojWDyOEIf93u04B:b-1ha3ch)*

**Comment by knz** [comment]
ok thanks for clarifying the commit message!

**Pull request merged**
