### PR TITLE
ui: update transaction insight details SQL query to not select from crdb_internal.ranges

### LINKED ISSUE #94445: ui: update SQL API transaction contention query to not select from `crdb_internal.ranges`
One of the SQL API queries for transaction contention insights joins on [`crdb_internal.ranges`](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L329). We should update this query to *not* select from `crdb_internal.ranges` and then backport this change to 22.2, for the following reasons:

1. Transaction insight details are now broken on master. 
  As of #93644, the problematic query selects columns that no longer exist in `crdb_internal.ranges` (in specific, `database_name`). As a result, the transaction insight details page on the console will hang/return an error for all cluster types (self-hosted, dedicated, serverless, etc).
3. 22.2 Serverless CC console transaction insight details will not work.
  https://github.com/cockroachdb/cockroach/pull/92131 was not backported to 22.2. So querying `crdb_internal.ranges` from a 22.2 tenant cluster won't work. This is a blocker for https://github.com/cockroachlabs/managed-service/pull/10854.

This issue only affects transaction insight details.

Jira issue: CRDB-22892

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes #94445.

This commit updates the SQL-over-HTTP query executed on behalf of the transaction insight details page to not select from the crdb_internal.ranges table, and instead select from other internal tables.

Loom: https://www.loom.com/share/c5f0ffc201ef44778ef724c8f53538fc

Release note: None

### CODE REVIEW

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94803)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 309 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94803#-NLM-fYr0644UW4J9T1G:-NLM-fYr0644UW4J9T1H:b-e4t0ub) ([raw file](https://github.com/cockroachdb/cockroach/blob/995ee7d5a0522246ea327a7664f3fdca4e213031/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L309)):*
> ```XML
> 
> // txnContentionDetailsQuery selects information about a specific transaction contention event.
> const txnContentionDetailsQuery = (id: string) => `
> ```

Why are we not just using the contention information from insights contention events? 
https://github.com/cockroachdb/cockroach/blob/5a42279405e6c31bc0f3ad78f96c0cc39b04e967/pkg/sql/crdb_internal.go#L6907

**Review by ericharmeling — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94803)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 309 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94803#-NLM-fYr0644UW4J9T1G:-NLM1X946VdpZQV9YNa6:b-14c47c) ([raw file](https://github.com/cockroachdb/cockroach/blob/995ee7d5a0522246ea327a7664f3fdca4e213031/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L309)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Why are we not just using the contention information from insights contention events? 
https://github.com/cockroachdb/cockroach/blob/5a42279405e6c31bc0f3ad78f96c0cc39b04e967/pkg/sql/crdb_internal.go#L6907

</blockquote></details>

For a couple reasons:

1. This change works on both 22.2 and 23.1 and, if backported, it unblocks https://github.com/cockroachlabs/managed-service/pull/10854 on 22.2. Selecting from the `contention_events` column wouldn't work on 22.2.

2. IIUC, `cluster_execution_insights` captures statement executions whose execution time crosses a specific latency threshold. There could be a transaction with cumulative contention that surpasses the same threshold, but whose individual statements do not (and would therefore not be captured in `cluster_execution_insights`). But please correct me if I'm missing something.

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94803)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 309 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94803#-NLM-fYr0644UW4J9T1G:-NLNSiRFCFg-JEf5FVdE:b-3fsxdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/995ee7d5a0522246ea327a7664f3fdca4e213031/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L309)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

For a couple reasons:

1. This change works on both 22.2 and 23.1 and, if backported, it unblocks https://github.com/cockroachlabs/managed-service/pull/10854 on 22.2. Selecting from the `contention_events` column wouldn't work on 22.2.

2. IIUC, `cluster_execution_insights` captures statement executions whose execution time crosses a specific latency threshold. There could be a transaction with cumulative contention that surpasses the same threshold, but whose individual statements do not (and would therefore not be captured in `cluster_execution_insights`). But please correct me if I'm missing something.
</blockquote></details>

1. That makes sense, but I'm a little surprised we would backport it 22.2 instead of just waiting for 23.1.
2. I thought the insights txn page was converted to pull all the information from `cluster_execution_insights`. That way it only shows query captured by the insights logic, and it's no longer a concern about the inconsistency in capture/retention policies. Since it from `cluster_execution_insights` it should already have all the contention events and not need to do an extra query.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 334 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94803#-NLNV61G2TPS5WfsfsAw:-NLNV61G2TPS5WfsfsAx:b-kcgo3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/995ee7d5a0522246ea327a7664f3fdca4e213031/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L334)):*
> ```XML
>                table_id
>         FROM
>           "".crdb_internal.tables] AS tables ON tce.contending_key BETWEEN crdb_internal.table_span(tables.table_id)[1]
> ```

What happens if the table index was dropped or changed? Should it still return the result but leave the names as "no longer exists".

**Review by j82w — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94803#-:-NLQnTCgDUFVlPS-LHje:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling)

**Review by ericharmeling — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94803)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @j82w)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 309 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94803#-NLM-fYr0644UW4J9T1G:-NLR12w2BEE1OpaS9hjO:b-46nwfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/995ee7d5a0522246ea327a7664f3fdca4e213031/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L309)):*
> I'm a little surprised we would backport it 22.2 instead of just waiting for 23.1.

@kevin-v-ngo IIUC, we do want insights on CC console for 22.2 serverless clusters, correct? If not, we might be able to simplify this query a bit using the newer 23.1 `SHOW RANGES` syntax. But I don't think we'll be able to join on `cluster_execution_insights. contention_events` for the reasons I mention below.

> I thought the insights txn page was converted to pull all the information from cluster_execution_insights

The transaction insights page currently pulls from both `cluster_execution_insights` and `transaction_contention_events`.

The [`transactionInsights` reducer](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/redux/apiReducers.ts#L415) uses the [`getTxnInsightEvents` API function](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L198) to pull from `transaction_contention_events`.

The [`executionInsights` reducer](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/redux/apiReducers.ts#L436) uses [`getClusterInsightsApi`](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L711) to pull from `cluster_execution_insights`.

Then the [`selectTransactionInsights` selector combines the `transactionInsights` and `executionInsights` slices](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/views/insights/insightsSelectors.ts#L43). Entries with the [same txn ID are merged](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/cluster-ui/src/insights/utils.ts#L308), but if there are no duplicates (e.g., there is a contention event in `transaction_contention_events` but not in `cluster_execution_insights`), then the selector will just use the information in the slice with data to populate a row (e.g., a row with a txnID from `transaction_contention_events` that doesn't exist in `cluster_execution_insights`).

I think the end goal is to have all insights pages only pull from `cluster_execution_insights`, but that isn't what is happening right now.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 334 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94803#-NLNV61G2TPS5WfsfsAw:-NLR65HDEVHbWjjY4JEn:b-waan24) ([raw file](https://github.com/cockroachdb/cockroach/blob/995ee7d5a0522246ea327a7664f3fdca4e213031/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L334)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

What happens if the table index was dropped or changed? Should it still return the result but leave the names as "no longer exists".
</blockquote></details>

Good question! I don't know of a sensical way to determine if an index existed and now doesn't. Before, there was no index for a given contention event, we just defaulted to the primary index. But this query actually does select and return the primary index. I just changed this to "index not found" to cover this case.

**Comment by j82w** [comment]
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 309 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94803#-NLM-fYr0644UW4J9T1G:-NLW2V1gEA3wA6yLkH7e:bxxxom3) ([raw file](https://github.com/cockroachdb/cockroach/blob/995ee7d5a0522246ea327a7664f3fdca4e213031/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L309)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> I'm a little surprised we would backport it 22.2 instead of just waiting for 23.1.

@kevin-v-ngo IIUC, we do want insights on CC console for 22.2 serverless clusters, correct? If not, we might be able to simplify this query a bit using the newer 23.1 `SHOW RANGES` syntax. But I don't think we'll be able to join on `cluster_execution_insights. contention_events` for the reasons I mention below.

> I thought the insights txn page was converted to pull all the information from cluster_execution_insights

The transaction insights page currently pulls from both `cluster_execution_insights` and `transaction_contention_events`.

The [`transactionInsights` reducer](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/redux/apiReducers.ts#L415) uses the [`getTxnInsightEvents` API function](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L198) to pull from `transaction_contention_events`.

The [`executionInsights` reducer](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/redux/apiReducers.ts#L436) uses [`getClusterInsightsApi`](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L711) to pull from `cluster_execution_insights`.

Then the [`selectTransactionInsights` selector combines the `transactionInsights` and `executionInsights` slices](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/views/insights/insightsSelectors.ts#L43). Entries with the [same txn ID are merged](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/cluster-ui/src/insights/utils.ts#L308), but if there are no duplicates (e.g., there is a contention event in `transaction_contention_events` but not in `cluster_execution_insights`), then the selector will just use the information in the slice with data to populate a row (e.g., a row with a txnID from `transaction_contention_events` that doesn't exist in `cluster_execution_insights`).

I think the end goal is to have all insights pages only pull from `cluster_execution_insights`, but that isn't what is happening right now.
</blockquote></details>

I'm actually changing my opinion to agree that it should just pull from the 'transaction_contention_events'. Duplicating the info in both insights and contention caches doesn't make sense. The 'transaction_contention_events' will very soon have all the waiting statement info too. LGTM

**Pull request merged**
