### PR TITLE
util/log: new output format 'crdb-v2'

### LINKED ISSUE #50166: log: log lines collected by debug.zip seem to be truncated to 65K
It seems that log entries can be arbitrarily large, but when they're collected by the debug.zip (and I assume by the UI) through [this RPC](https://github.com/cockroachdb/cockroach/blob/ef7ab9bc810fd4be7755ebf8880e36ace9453f4b/pkg/cli/zip.go#L573) something seems to truncate them to 65KB each.
This is particularly unfortunate for query traces, which are a single entry (with many lines).

### PR DESCRIPTION
**Pull request by knz**
Fixes  #50166. 

This new format intends to address all the known shortcomings with `crdb-v1` while remaining compatible with entry parsers designed for the previous version.
See the user-facing release note below for a summary of changes; and the included reference documentation for details.

Example TTY output with colors:
image

Example for a single-line unstructured entry.

Before:
```
I210116 22:17:03.736236 57 cli/start.go:681 ⋮ node startup completed:
```

After:
```
I210116 22:17:03.736236 57 cli/start.go:681 ⋮ [-] 12  node startup completed:
              tag field now always included   ^^^
          entry counter now always included       ^^^
```

Example for a multi-line unstructured entry.

Before:
```
I210116 22:15:38.105666 452 gossip/gossip.go:567 ⋮ [n1] 74  gossip status (ok, 1 node‹›)
gossip client (0/3 cur/max conns)
gossip connectivity
  n1 [sentinel];
```

(subsequent lines lack a log entry prefix; hard to determine where
entries start and end)

After:
```
I210116 22:15:38.105666 452 gossip/gossip.go:567 ⋮ [n1] 74  gossip status (ok, 1 node‹›)
I210116 22:15:38.105666 452 gossip/gossip.go:567 ⋮ [n1] 74 +gossip client (0/3 cur/max conns)
I210116 22:15:38.105666 452 gossip/gossip.go:567 ⋮ [n1] 74 +gossip connectivity
I210116 22:15:38.105666 452 gossip/gossip.go:567 ⋮ [n1] 74 +  n1 [sentinel];
  ^^^ common prefix repeated for each msg line
       same entry counter for every subsequent line    ^^^
               continuation marker "+" on susequent lines ^^
```

Example for a structured entry.

Before:
```
I210116 22:14:38.175829 469 util/log/event_log.go:32 ⋮ [n1] Structured entry: {...}
```

After:
```
I210116 22:14:38.175829 469 util/log/event_log.go:32 ⋮ [n1] 21 ={...}
                            entry counter always present    ^^
                      equal sign "=" denotes structured entry ^^
```

Release note (cli change): The default output format for `file-group`
and `stderr` sinks has been changed to `crdb-v2`.

This new format is non-ambiguous and makes it possible to reliably
parse log files. Refer to the format's documentation for
details. Additionally, it prevents single log lines from exceeding a
large size; this problem is inherent to the `crdb-v1` format and can
prevent `cockroach debug zip` from retrieving v1 log files.

The new format has also been designed so that existinglog file
analyzers for the `crdb-v1` format can read entries written the new
format. However, this conversion may be imperfect. Again, refer to
the new format's documentation for details.

In case of incompatibility, users can force the previous format by
using `format: crdb-v1` in their logging configuration.

### CODE REVIEW

**Comment by knz** [comment]
Remaining work:

- [ ] fix broken tests in util/log
- [ ] fix broken tests elsewhere
- [ ] (best effort) try to extend the existing entry parser to merge subsequent lines that have the same counter

**Comment by knz** [comment]
this is now ready for review.

**Review by itsbilal — APPROVED** [review]
:lgtm: Great work! Just one minor question, but this is looking ready to go.

> Reviewed 3 of 3 files at r1, 22 of 22 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59087#-:-MRufJCWCXdUQfUD9kuk:bj9ng7j)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @thtruo)

___
*[docs/generated/logformats.md, line 246 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59087#-MRuXYnpD_LdYKDonHQu:-MRuXYnpD_LdYKDonHQv:b-anch94) ([raw file](https://github.com/cockroachdb/cockroach/blob/c164d4a8a63c38acc6b56b9d2b90e5a381577394/docs/generated/logformats.md#L246)):*
> ```Markdown
> associated, for example header entries in file sinks, the counter position
> in the common prefix appears as a sequence of two ASCII space characters,
> which can be used to reliably identify this situation.
> ```

Can we reliably guarantee this? I'm thinking of the interpretation of this being "find the two spaces in a line to identify it as a log entry with no counter", and there being some log entry somewhere in the code that unintentionally writes two spaces as part of the message. Maybe I'm overthinking this.
___
*[pkg/util/log/logconfig/config.go, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59087#-MRuf7e79yfc8CPOwoLX:-MRuf7e79yfc8CPOwoLY:bnjzbbv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c164d4a8a63c38acc6b56b9d2b90e5a381577394/pkg/util/log/logconfig/config.go#L27)):*
> ```Go
> // DefaultFileFormat is the entry format for file sinks when not
> // specified in a configuration.
> const DefaultFileFormat = `crdb-v2`
> ```

:tada:

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59087)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @thtruo)

___
*[docs/generated/logformats.md, line 246 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59087#-MRuXYnpD_LdYKDonHQu:-MRukZsw2Ur_U5y22KWq:bsc1tgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c164d4a8a63c38acc6b56b9d2b90e5a381577394/docs/generated/logformats.md#L246)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Can we reliably guarantee this? I'm thinking of the interpretation of this being "find the two spaces in a line to identify it as a log entry with no counter", and there being some log entry somewhere in the code that unintentionally writes two spaces as part of the message. Maybe I'm overthinking this.
</blockquote></details>

Clarified the phrasing: yes, it is reliable. There's always a space before and after, so if there are two spaces in a row that means there was no counters.

**Comment by knz** [comment]
I also added a formatting test so we have side-by-side examples of entries with and without counters, to clarify.

TFYR!

bors r=itsbilal

**Pull request merged**
