### PR TITLE
parser: add non-comma separated transaction modes

### PR DESCRIPTION
**Pull request by rjnn**
Currently, we only support multiple directives in the SET TRANSACTION
statement when they are comma separated (as per the SQL
spec). However, postgres historically supported multiple directives
with no comma in between, which is used by the Go SQL driver when
explicitly setting transaction isolation levels. Add support for this
historical syntax.

### CODE REVIEW

**Review by knz — APPROVED** [review]

**Comment by knz** [comment]
huh no wait

**Review by knz — CHANGES_REQUESTED** [review]
Please add new tests in `parse_test.go` `TestParse2`

**Comment by arjunravinarayan** [comment]
Done. PTAL.

**Comment by jordanlewis** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17723#-:-KrlFyICUml0J-wIuSo5:bnfp4nl)*

**Pull request merged**
