### PR TITLE
opt: add insertion checks for unique constraints

### PR DESCRIPTION
**Pull request by rytaft**
This commit adds checks for unique constraints when planning insertions
in the optimizer. This does not yet impact anything outside of the optimizer
tests, since `UNIQUE WITHOUT INDEX` is still not supported outside of the
optimizer test catalog.

Informs #41535

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Very cool!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56777#-:-MMLtlp30o3YDCFaj-50:b-kkp8rn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/ops/mutation.opt, line 265 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56777#-MMLsO7X0iWyEDKEGZ4a:-MMLsO7X0iWyEDKEGZ4b:br5ezgv) ([raw file](https://github.com/cockroachdb/cockroach/blob/32e171ffb60383612dd682858e08abcb43ff02c8/pkg/sql/opt/ops/mutation.opt#L265)):*
> ```
> }
> 
> # UniqueChecks is a list of unique check queries, to be run after the main
> ```

[nit] uniqueness check (no need to update in other places, just felt like a good place to have both phrasings)
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 1195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56777#-MMJWUtL5D8IhofTOojC:-MMJWUtL5D8IhofTOojD:b-s83wpx) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e458ae395086e060c9b89e3305d973c9d193cc5/pkg/sql/opt/optbuilder/mutation_builder.go#L1195)):*
> ```Go
> 
> 		// If a table column is not nullable, NULLs cannot be inserted (the
> 		// mutation will fail). So for the purposes of FK checks, we can treat
> ```

[nit] remove FK
___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56777#-MMJXBwd3SlMVbkUFAjj:-MMJXBwd3SlMVbkUFAjk:bk84qpv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e458ae395086e060c9b89e3305d973c9d193cc5/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L139)):*
> ```Go
> 	f := h.mb.b.factory
> 	if notNullWithScanCols.Len() < numCols {
> 		// The columns we are inserting might have NULLs. These require special
> ```

Do we need this SELECT? The NULLs shouldn't match anything in the semi join
___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56777#-MMJXPXg50t1yhBCQZ93:-MMJXPXg50t1yhBCQZ94:b-kfacki) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e458ae395086e060c9b89e3305d973c9d193cc5/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L192)):*
> ```Go
> 		}
> 	}
> 	semiJoinFilters[len(semiJoinFilters)-1] = f.ConstructFiltersItem(pkFilter)
> ```

[nit] less error-prone if we initialize with 0 length and `append`
___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56777#-MMLtF3nBhoVxvDUq-Ze:-MMLtF3o3zo6GgcryhbF:b67sgtx) ([raw file](https://github.com/cockroachdb/cockroach/blob/32e171ffb60383612dd682858e08abcb43ff02c8/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L179)):*
> ```Go
> 	// do this by adding another filter that uses the primary keys to check if
> 	// two rows are identical:
> 	//    (new_pk1 != existing_pk1) OR (new_pk2 != existing_pk2) OR ...
> ```

Clever!

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 14 of 14 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56777#-:-MMNH6-LEeP9eQ5dxOKb:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/norm/prune_cols_funcs.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56777#-MMNGvgq8C97FD1O3DI2:-MMNGvgq8C97FD1O3DI3:b-juw4le) ([raw file](https://github.com/cockroachdb/cockroach/blob/32e171ffb60383612dd682858e08abcb43ff02c8/pkg/sql/opt/norm/prune_cols_funcs.go#L76)):*
> ```Go
> 			cols.UnionWith(withUses[private.WithID].UsedCols)
> 		}
> 		for i := range fkChecks {
> ```

[nit] add some `prune_cols` normalization tests that fail if this change wasn't made
___
*[pkg/sql/opt/ops/mutation.opt, line 284 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56777#-MMMzIoR1L3O4vIordAD:-MMMzIoR1L3O4vIordAE:b-log84o) ([raw file](https://github.com/cockroachdb/cockroach/blob/32e171ffb60383612dd682858e08abcb43ff02c8/pkg/sql/opt/ops/mutation.opt#L284)):*
> ```
> 
>     # This item checks that a new value in the table is unique.
>     CheckOrdinal int
> ```

I don't follow the description for `CheckOrdinal`. This is the ordinal of the check in the table's unique constraints, correct?
___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56777#-MMN1DryEx2-k9sLLUMp:-MMN1DryEx2-k9sLLUMq:b-7c9f88) ([raw file](https://github.com/cockroachdb/cockroach/blob/32e171ffb60383612dd682858e08abcb43ff02c8/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L48)):*
> ```Go
> 	for i, n := 0, mb.tab.UniqueCount(); i < n; i++ {
> 		if h.init(mb, i) {
> 			mb.uniqueChecks = append(mb.uniqueChecks, h.buildInsertionCheck())
> ```

[nit] It might be clearer to not call `h.init` at all if there is an index for the constraint. I got a bit confused reading this. Not a big deal though.

[nit] the first for loop above already finds the first unique check without an index. You could use the same `i` and skip straight to it in this loop.
___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 166 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56777#-MMNC4UZ93EIy1pkers9:-MMNC4U_BSPKD99E556x:b-xs48t6) ([raw file](https://github.com/cockroachdb/cockroach/blob/32e171ffb60383612dd682858e08abcb43ff02c8/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L166)):*
> ```Go
> 	// Build the join filters:
> 	//   (new_a = existing_a) AND (new_b = existing_b) AND ...
> 	semiJoinFilters := make(memo.FiltersExpr, len(h.uniqueOrdinals)+1)
> ```

[nit] explain the `+ 1` for the length
___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56777#-MMLtF3nBhoVxvDUq-Ze:-MMNELk56e5hI1gIXvI_:b-dumngm) ([raw file](https://github.com/cockroachdb/cockroach/blob/32e171ffb60383612dd682858e08abcb43ff02c8/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L179)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Clever!
</blockquote></details>

This isn't super clear to me. Do you have an example of what happens if we don't have this PK NE check?

It seems like inserting a row with an existing PK would fail due to a duplicate PK. Does this just ensure that a duplicate PK error is returned in this case, rather than a unique check error?

**Review by RaduBerinde — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56777)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andy-kimball, @mgartner, and @rytaft)

___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56777#-MMLtF3nBhoVxvDUq-Ze:-MMNSXrxArnL-0brG7eA:bmgyhpt) ([raw file](https://github.com/cockroachdb/cockroach/blob/32e171ffb60383612dd682858e08abcb43ff02c8/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L179)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This isn't super clear to me. Do you have an example of what happens if we don't have this PK NE check?

It seems like inserting a row with an existing PK would fail due to a duplicate PK. Does this just ensure that a duplicate PK error is returned in this case, rather than a unique check error?
</blockquote></details>

The scan will "see" the newly inserted rows, so without this check the query will always return at least the inserted rows

**Review by rytaft — COMMENTED** [review]
TFTRs! Updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56777#-:-MMR8EK61r5EaNI_IL_x:b-u8hs9c)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andy-kimball, @mgartner, and @RaduBerinde)

___
*[pkg/sql/opt/norm/prune_cols_funcs.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56777#-MMNGvgq8C97FD1O3DI2:-MMR1wGa8qgKJa4h3BML:bb3cwb) ([raw file](https://github.com/cockroachdb/cockroach/blob/32e171ffb60383612dd682858e08abcb43ff02c8/pkg/sql/opt/norm/prune_cols_funcs.go#L76)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] add some `prune_cols` normalization tests that fail if this change wasn't made
</blockquote></details>

I don't think this is possible until I implement `UPDATE` or `UPSERT` checks. I added a TODO in the test file.
___
*[pkg/sql/opt/ops/mutation.opt, line 265 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56777#-MMLsO7X0iWyEDKEGZ4a:-MMR2_TUEKaSsNXW3-oj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/32e171ffb60383612dd682858e08abcb43ff02c8/pkg/sql/opt/ops/mutation.opt#L265)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] uniqueness check (no need to update in other places, just felt like a good place to have both phrasings)
</blockquote></details>

Done.
___
*[pkg/sql/opt/ops/mutation.opt, line 284 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56777#-MMMzIoR1L3O4vIordAD:-MMR2cju-VPFTY1UnLRq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/32e171ffb60383612dd682858e08abcb43ff02c8/pkg/sql/opt/ops/mutation.opt#L284)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't follow the description for `CheckOrdinal`. This is the ordinal of the check in the table's unique constraints, correct?
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 1195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56777#-MMJWUtL5D8IhofTOojC:-MMR3JVE-paj479fhZAy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e458ae395086e060c9b89e3305d973c9d193cc5/pkg/sql/opt/optbuilder/mutation_builder.go#L1195)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] remove FK
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56777#-MMJXBwd3SlMVbkUFAjj:-MMR5fdV7PUBrewiR_oY:bve0fui) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e458ae395086e060c9b89e3305d973c9d193cc5/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L139)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Do we need this SELECT? The NULLs shouldn't match anything in the semi join
</blockquote></details>

You're right, I guess we don't. Seems like it could potentially reduce the cost of the join, but probably better to keep things simple. Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56777#-MMJXPXg50t1yhBCQZ93:-MMR7pER2wVUNXDvNJru:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e458ae395086e060c9b89e3305d973c9d193cc5/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L192)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] less error-prone if we initialize with 0 length and `append`
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56777#-MMN1DryEx2-k9sLLUMp:-MMR3ajiDIsD7V3OWkXp:bs7wumb) ([raw file](https://github.com/cockroachdb/cockroach/blob/32e171ffb60383612dd682858e08abcb43ff02c8/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L48)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] It might be clearer to not call `h.init` at all if there is an index for the constraint. I got a bit confused reading this. Not a big deal though.

[nit] the first for loop above already finds the first unique check without an index. You could use the same `i` and skip straight to it in this loop.
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 166 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56777#-MMNC4UZ93EIy1pkers9:-MMR7mb4EkaxKyCPt1Y-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/32e171ffb60383612dd682858e08abcb43ff02c8/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L166)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] explain the `+ 1` for the length
</blockquote></details>

Done.

**Review by mgartner — APPROVED** [review]
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56777)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andy-kimball, @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 121 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56777#-MMRjDlY4BeF9GtbCgv7:-MMRjDlY4BeF9GtbCgv8:b14tfnq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2c903c3dbd8e0afa5e2fbf94266d9f9c55794d6/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L121)):*
> ```Go
> 	}
> 
> 	// If least one unique column is getting a NULL value, unique check not needed.
> ```

[nit] "If least" => "If at least"

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56777#-:-MMS3MW93zMGpHAGA4W9:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @mgartner, and @rytaft)

**Review by rytaft — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56777#-:-MMSCI1N9CzLQfYwKZx-:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andy-kimball and @mgartner)

___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 121 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56777#-MMRjDlY4BeF9GtbCgv7:-MMSCYApBPBl50oujYF2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2c903c3dbd8e0afa5e2fbf94266d9f9c55794d6/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L121)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] "If least" => "If at least"
</blockquote></details>

Done.

**Pull request merged**
