### PR TITLE
build,cmd/roachtest: progress towards nightly Pebble benchmarking

### PR DESCRIPTION
**Pull request by petermattis**
#### build: add teamcity-nightly-pebble.sh

Release note: None

#### cmd/roachtest: add pebble/ycsb/* roachtests

Add `pebble/ycsb/size={64,1024,4096}` roachtests which run Pebble-only 
version of the ycsb A, B, C, D, and E workloads with different value sizes.

The pebble roachtests are benchmarks, not correctness tests. They are 
hidden behind the `pebble` tag and only run if `tag:pebble` is specified.

Release note: None

#### cmd/roachtest: allow disabling of the post-test checks

Allow disabling the post-test replica divergence and dead-node checks.
These checks only make sense for tests which run a cockroach cluster.

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50892)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @jbowens, and @tbg)

___
*[pkg/cmd/roachtest/test.go, line 63 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50892#-MBAZGbX5zHCtO99pDZb:-MBAZGbX5zHCtO99pDZc:b-wzrdo8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eef4ac059e0d72025c3317ea3b59aa051de4168/pkg/cmd/roachtest/test.go#L63)):*
> ```Go
> 	// Disable checks that are normally performed at the end of a test.
> 	DisableReplicaDivergenceCheck bool
> 	DisableDeadNodeCheck          bool
> ```

@andreimatei, @tbg I've only tagged you on this PR to look at the changes in the first commit. Specifically the code here and in `test_runner.go`. Is there another way to accomplish this? Am I abusing `roachtest` to use it for testing something other than Cockroach?

**Review by jbowens — APPROVED** [review]
:LGTM:

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50892#-:-MBBDEcoBDu8lCZ0GW0G:bmxilld)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @petermattis, and @tbg)

___
*[build/teamcity-nightly-pebble.sh, line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50892#-MBBA0Tp2g091ms17j00:-MBBA0Tp2g091ms17j01:bfki8us) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eef4ac059e0d72025c3317ea3b59aa051de4168/build/teamcity-nightly-pebble.sh#L33)):*
> ```Shell
> build_tag=$(git describe --abbrev=0 --tags --match=v[0-9]*)
> 
> make bin/roachprod bin/roachtest > "${artifacts}/build.txt" 2>&1 || cat "${artifacts}/build.txt"
> ```

The script will continue even if `make` fails because of the `||`, right?  Could do a `|| (cat "${artifacts}/build.txt" && exit 1)`

**Review by petermattis — COMMENTED** [review]
TFTR!

@tbg or @andreimatei will wait for one of you to weigh in on the roachtest infra change.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50892#-:-MBBKkwX2TTguxWRnr8m:b-jx19si)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @jbowens, and @tbg)

___
*[build/teamcity-nightly-pebble.sh, line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50892#-MBBA0Tp2g091ms17j00:-MBBK_jQEzLnZp1fHcir:b1sova0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eef4ac059e0d72025c3317ea3b59aa051de4168/build/teamcity-nightly-pebble.sh#L33)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

The script will continue even if `make` fails because of the `||`, right?  Could do a `|| (cat "${artifacts}/build.txt" && exit 1)`
</blockquote></details>

Yeah, that's not good. I had copied that from the `build/teamcity-nightly-roachtest.sh` script, though that script isn't actually used by the `Roachtest Nightly - {GCE,AWS}` build configs. Removed.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50892)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens and @tbg)

___
*[pkg/cmd/roachtest/test.go, line 63 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50892#-MBAZGbX5zHCtO99pDZb:-MBBG-6F1LPWVquAN8Et:b-rg7z9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eef4ac059e0d72025c3317ea3b59aa051de4168/pkg/cmd/roachtest/test.go#L63)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

@andreimatei, @tbg I've only tagged you on this PR to look at the changes in the first commit. Specifically the code here and in `test_runner.go`. Is there another way to accomplish this? Am I abusing `roachtest` to use it for testing something other than Cockroach?
</blockquote></details>

If these test take more than minutes and want a whole machine (so, you want to parallelize them across machines), I think `roachtest` is a fine tool for the job. I googled briefly what naked teamcity has to offer in the area, and didn't find anything.
But let's make sure we do whatever we're doing as cleanly as possible.

For the new knobs you've added to the test spec I'd like to understand how, for example, the Jepsen tests do without them. Those tests are also pretty funky in that I don't think they start cockroach clusters the normal way, and yet they pass somehow. I'm thinking I'd like the monitor to understand that there's nothing for it to do because no cockroach cluster was ever created, without the need for any new knobs.


I had to peak at the latter commits, and there I have some objections :)
You're sneaking in Pebble tests into the Cockroach CI. You've made your own repo (*caugh caugh*) cause our tests were too slow, but now you come to put your test into our repo, doing a `git clone` on pebble. I say, since you didn't like our repo, you set up your own playground on yours. You can `go get` roachprod and roachtest (or, at least, you should be able to). You can even use the same GCE project for both - for billing. I think that, when I look at the cockroach CI, the builds I see there should be triggered by commits on the CRDB repo, and the tested things should correspond to those commits.

I realize that tests currently have to be compiled into the `roachtest` binary, but I hope that can be relaxed - either through plugins or through `roachtest` running different test binaries. In fact, I think that should have always been the model for roachtests.

What do you say?

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50892)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens and @tbg)

___
*[pkg/cmd/roachtest/test.go, line 63 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50892#-MBAZGbX5zHCtO99pDZb:-MBBNlfWDnBiGJKPgirS:b-j1jd8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eef4ac059e0d72025c3317ea3b59aa051de4168/pkg/cmd/roachtest/test.go#L63)):*
> For the new knobs you've added to the test spec I'd like to understand how, for example, the Jepsen tests do without them. Those tests are also pretty funky in that I don't think they start cockroach clusters the normal way, and yet they pass somehow. I'm thinking I'd like the monitor to understand that there's nothing for it to do because no cockroach cluster was ever created, without the need for any new knobs.

Yeah, I don't know how those tests work either. I looked and didn't see anything that prevents the replica divergence and dead nodes checks. Ah, it looks like `--ignore-empty-nodes` is the trick. I'm actually populating `/mnt/data1/cockroach` which makes the nodes appear non-empty. I suppose I could use a different directory, though adding these knobs seems conceptually cleaner.

> You're sneaking in Pebble tests into the Cockroach CI. You've made your own repo (caugh caugh) cause our tests were too slow, but now you come to put your test into our repo, doing a git clone on pebble. I say, since you didn't like our repo, you set up your own playground on yours. You can go get roachprod and roachtest (or, at least, you should be able to). You can even use the same GCE project for both - for billing. I think that, when I look at the cockroach CI, the builds I see there should be triggered by commits on the CRDB repo, and the tested things should correspond to those commits.
> 
> I realize that tests currently have to be compiled into the roachtest binary, but I hope that can be relaxed - either through plugins or through roachtest running different test binaries. In fact, I think that should have always been the model for roachtests.

Can you elaborate on how you think this should work? As you note, in order to add a roachtest I have to compile it into the binary. Extracting roachtest infra into a library would be nice, but it isn't currently set up that way. Shall I put this effort on hold until that is done. 

Btw, I've been pondering the decision of keeping `pebble` in a separate repo. The branch management to backport changes to 20.1 is super irritating (backport to branch on Pebble then backport to vendor branch on Cockroach branch, ...). Would you feel differently about this PR if pebble were part of the main Cockroach repo?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50892)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens and @tbg)

___
*[pkg/cmd/roachtest/test.go, line 63 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50892#-MBAZGbX5zHCtO99pDZb:-MBBQVBYA8faRgyCd7Oe:b-yl6mey) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eef4ac059e0d72025c3317ea3b59aa051de4168/pkg/cmd/roachtest/test.go#L63)):*
> I suppose I could use a different directory, though adding these knobs seems conceptually cleaner.

Can the monitor know whether a cockroach cluster has ever been started through the "usual way"? A `cluster` definitely knows about `cockroach` (e.g. the `StartE()` method), so I'm thinking it can remember what nodes should have crdb running on them.
Generally, the fact that the `monitor` is disconnected from reality has been bothering me periodically. Don't remember exactly what irks me, but it's something like how after a test fails, the monitor sometimes also fails because it complains that some nodes are dead although the test stopped them on purpose.

> Btw, I've been pondering the decision of keeping pebble in a separate repo. The branch management to backport changes to 20.1 is super irritating (backport to branch on Pebble then backport to vendor branch on Cockroach branch, ...). Would you feel differently about this PR if pebble were part of the main Cockroach repo?

Of course :). Come back to the flock.
If you want Pebble to have a different release cycle than CRDB then I guess there'd still be workflow issues to settle - but maybe you don't.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50892)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens and @tbg)

___
*[pkg/cmd/roachtest/test.go, line 63 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50892#-MBAZGbX5zHCtO99pDZb:-MBBd96PCJC_PEoryFCC:b-y890kw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eef4ac059e0d72025c3317ea3b59aa051de4168/pkg/cmd/roachtest/test.go#L63)):*
> Can the monitor know whether a cockroach cluster has ever been started through the "usual way"? A cluster definitely knows about cockroach (e.g. the StartE() method), so I'm thinking it can remember what nodes should have crdb running on them.

The monitor is allocated separately from the cluster. Also be aware that a few tests do `cluster.Run("cockroach start")` to get greater control over starting a cockroach node than `roachprod start` allows.

> Generally, the fact that the monitor is disconnected from reality has been bothering me periodically. Don't remember exactly what irks me, but it's something like how after a test fails, the monitor sometimes also fails because it complains that some nodes are dead although the test stopped them on purpose.

Yep. That isn't the monitor per-se, but the fact that we're always running these post-test checks regardless of whether the test wants them or not. The change here actually addresses that exact problem.

> Of course :). Come back to the flock.
If you want Pebble to have a different release cycle than CRDB then I guess there'd still be workflow issues to settle - but maybe you don't.

My thought was to do the reverse external repo thing that the ex-Foursquare folks have mentioned. Add `internal/pebble` to the cockroach repo and limit its dependencies to the rest of CRDB and push out nightly updates to `github.com/cockroachdb/pebble`. But this idea is still in its infancy.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50892)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens and @tbg)

___
*[pkg/cmd/roachtest/test.go, line 63 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50892#-MBAZGbX5zHCtO99pDZb:-MBFfcjf9rhRyyEX_Iyg:bco5tjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eef4ac059e0d72025c3317ea3b59aa051de4168/pkg/cmd/roachtest/test.go#L63)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

> Can the monitor know whether a cockroach cluster has ever been started through the "usual way"? A cluster definitely knows about cockroach (e.g. the StartE() method), so I'm thinking it can remember what nodes should have crdb running on them.

The monitor is allocated separately from the cluster. Also be aware that a few tests do `cluster.Run("cockroach start")` to get greater control over starting a cockroach node than `roachprod start` allows.

> Generally, the fact that the monitor is disconnected from reality has been bothering me periodically. Don't remember exactly what irks me, but it's something like how after a test fails, the monitor sometimes also fails because it complains that some nodes are dead although the test stopped them on purpose.

Yep. That isn't the monitor per-se, but the fact that we're always running these post-test checks regardless of whether the test wants them or not. The change here actually addresses that exact problem.

> Of course :). Come back to the flock.
If you want Pebble to have a different release cycle than CRDB then I guess there'd still be workflow issues to settle - but maybe you don't.

My thought was to do the reverse external repo thing that the ex-Foursquare folks have mentioned. Add `internal/pebble` to the cockroach repo and limit its dependencies to the rest of CRDB and push out nightly updates to `github.com/cockroachdb/pebble`. But this idea is still in its infancy.
</blockquote></details>

I removed the first commit, replacing it with changes to the `pebble/*` tests so that they don't write to `/mnt/data1/cockroach` which avoids the problems with the replica divergence and dead node checks.

**Comment by petermattis** [comment]
TFTR!

This isn't the end of the story on this work, but it advances the ball. I'm going to merge this so that tonight's run will be able to run these benchmarks. I'll have to manually collect the output, but that is ok.

bors r+

**Comment by petermattis** [comment]
TestDockerCLI flake. Trying again.

bors r+

**Pull request merged**
