### PR TITLE
raft: send de-fortification requests with the correct term

### PR DESCRIPTION
**Pull request by arulajmani**
First 2 commits from https://github.com/cockroachdb/cockroach/pull/131668

----

Addresses a TODO, where we were plopping an incorrect term on
MsgDeFortifyLeader. A MsgDeFortifyLeader should include the leadership
term that's being de-fortified, not the currently known term to old
leader that's trying to de-fortify. To enable this, we track the term on
the FortificationTracker and ensure it's only reset when a peer steps up
to become leader again.

Informs https://github.com/cockroachdb/cockroach/issues/129098

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
Nice, this came out well. :lgtm: once the commentary does a little better job explaining why we have this somewhat surprising state tracking.

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131828#-:-O8KjeQb0J20Mb_N-Ml3:boh2lj9)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @iskettaneh)

___
*[`-- commits` line 49 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131828#-O8KiGyA42_y6rQhmzJs):*
"to the old leader"
___
*[`pkg/raft/raft.go` line 1186 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131828#-O8KiPli2xvcbQ0mte5G:-O8KiPlj6l17Eo1QWjS4:bmz3mtp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f774409f9e41f0aa7f5a3d8418eabbe8ceb11d6d/pkg/raft/raft.go#L1186)):*
nit: since this is a little surprising, consider driving the point home even further in the second sentence:
> We reset it if we ever step up to become leader again, but not when stepping down as leader and not even when learning of a new leader in a later term.
___
*[`pkg/raft/tracker/fortificationtracker.go` line 30 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131828#-O8KjMUI3E3rPtYJfZ4t:-O8KjMUI3E3rPtYJfZ4u:bszzwi5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f774409f9e41f0aa7f5a3d8418eabbe8ceb11d6d/pkg/raft/tracker/fortificationtracker.go#L30)):*
> ```Go
> 	fortification map[pb.PeerID]pb.Epoch
> 
> 	// term is the leadership term associated with fortification tracking.
> ```

This would be a good place to add a few more words around how this differs from `raft.term` and why we need it to.
___
*[`pkg/raft/tracker/fortificationtracker.go` line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131828#-O8Kk3D80b1dD7fReoxB:-O8Kk3D80b1dD7fReoxC:b-j440g1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f774409f9e41f0aa7f5a3d8418eabbe8ceb11d6d/pkg/raft/tracker/fortificationtracker.go#L31)):*
> ```Go
> 
> 	// term is the leadership term associated with fortification tracking.
> 	term uint64
> ```

tiny nit here and in `Reset`: move `term` above `fortification` to match their respective scopes. The fortification state is scoped to a single leadership term.
___
*[`pkg/raft/tracker/fortificationtracker.go` line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131828#-O8Kkbwa5pZeWoTrUqiA:-O8Kkbwa5pZeWoTrUqiB:bxtgzle) ([raw file](https://github.com/cockroachdb/cockroach/blob/f774409f9e41f0aa7f5a3d8418eabbe8ceb11d6d/pkg/raft/tracker/fortificationtracker.go#L61)):*
> ```Go
> 
> // Reset clears out any previously tracked fortification and prepares the
> // fortification tracker to be used at the supplied term.
> ```

"used by a newly elected leader"

**Review by iskettaneh — APPROVED** [review]
> Reviewed 21 of 21 files at r1, 14 of 14 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131828)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/raft/raft.go` line 854 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131828#-O8OF9dRBu-GkBDKzSbL:-O8OF9dRBu-GkBDKzSbM:biwu3p9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4b893ca97fff8b8956292fcc2d1bbb04bc57d35/pkg/raft/raft.go#L854)):*
> ```Go
> func (r *raft) sendDeFortify(to pb.PeerID) {
> 	if to == r.id {
> 		// We handle the case where the leader is trying to de-fortify itself
> ```

maybe keep the comment before the TODO just to help future readers know why we have this special case
___
*[`pkg/raft/testdata/de_fortification_basic.txt` line 985 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131828#-O8OGEjDEDGEXIxwmF4w:-O8OGEjDEDGEXIxwmF4x:bplitbj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f774409f9e41f0aa7f5a3d8418eabbe8ceb11d6d/pkg/raft/testdata/de_fortification_basic.txt#L985)):*
> ```help
> INFO 2 [logterm: 4, index: 5] sent MsgVote request to 3 at term 5
> 
> stabilize
> ```

Curious if we really need the debug level logging in this test, or can we get away with info?

**Review by arulajmani — COMMENTED** [review]
RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131828#-:-O8c4TeFA6KNT0a-jxPp:bb72pd0)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @iskettaneh)

___
*[`pkg/raft/raft.go` line 1186 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131828#-O8KiPli2xvcbQ0mte5G:-O8bujrP9Bk4Knl73JGE:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f774409f9e41f0aa7f5a3d8418eabbe8ceb11d6d/pkg/raft/raft.go#L1186)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: since this is a little surprising, consider driving the point home even further in the second sentence:
> We reset it if we ever step up to become leader again, but not when stepping down as leader and not even when learning of a new leader in a later term.
</blockquote></details>

Done. 
___
*[`pkg/raft/tracker/fortificationtracker.go` line 30 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131828#-O8KjMUI3E3rPtYJfZ4t:-O8c3N1n8k6K9XCvEVew:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f774409f9e41f0aa7f5a3d8418eabbe8ceb11d6d/pkg/raft/tracker/fortificationtracker.go#L30)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This would be a good place to add a few more words around how this differs from `raft.term` and why we need it to.
</blockquote></details>

Done. 
___
*[`pkg/raft/tracker/fortificationtracker.go` line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131828#-O8Kk3D80b1dD7fReoxB:-O8c3att6vt1-oWJ96Dk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f774409f9e41f0aa7f5a3d8418eabbe8ceb11d6d/pkg/raft/tracker/fortificationtracker.go#L31)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

tiny nit here and in `Reset`: move `term` above `fortification` to match their respective scopes. The fortification state is scoped to a single leadership term.
</blockquote></details>

Done.
___
*[`pkg/raft/testdata/de_fortification_basic.txt` line 985 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131828#-O8OGEjDEDGEXIxwmF4w:-O8c3s3C6wKU2rJOuEEI:b-brbe8x) ([raw file](https://github.com/cockroachdb/cockroach/blob/f774409f9e41f0aa7f5a3d8418eabbe8ceb11d6d/pkg/raft/testdata/de_fortification_basic.txt#L985)):*
<details><summary><i>Previously, iskettaneh wrote…</i></summary><blockquote>

Curious if we really need the debug level logging in this test, or can we get away with info?
</blockquote></details>

Not for the one we added in this patch, but some of the de-fortification related log lines from the previous PR are behind a debug log.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131828)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @iskettaneh and @nvanbenschoten)

___
*[`pkg/raft/raft.go` line 854 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131828#-O8OF9dRBu-GkBDKzSbL:-O8c5oNT2tqk_BsPMit6:b-g3uqz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4b893ca97fff8b8956292fcc2d1bbb04bc57d35/pkg/raft/raft.go#L854)):*
<details><summary><i>Previously, iskettaneh wrote…</i></summary><blockquote>

maybe keep the comment before the TODO just to help future readers know why we have this special case
</blockquote></details>

That was accidental. Fixed.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 30 of 30 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131828#-:-O8cAHxHEiGz_zDrqDA1:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @iskettaneh)

___
*[`pkg/raft/tracker/fortificationtracker.go` line 33 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/131828#-O8cA7S45S-ETfO2w5uX:-O8cA7S45S-ETfO2w5uY:b1hfoc4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a264fb0588807c029d01cec11955b4beec93276d/pkg/raft/tracker/fortificationtracker.go#L33)):*
> ```Go
> 	// The term differs from raft.term in that raft.term is the highest term known
> 	// to a peer, whereas FortificationTracker.term is the highest term a peer was
> 	// a leader at.
> ```

"was a leader at since the last time it restarted."

**Review by arulajmani — COMMENTED** [review]
TFTRs!

bors r=nvanbenschoten,iskettaneh

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131828#-:-O8gVccWCCGqhkhMHqKG:boyao5y)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @iskettaneh and @nvanbenschoten)

___
*[`pkg/raft/tracker/fortificationtracker.go` line 33 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/131828#-O8cA7S45S-ETfO2w5uX:-O8gVXK8AIZiMul4Chj5:boj1qgt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a264fb0588807c029d01cec11955b4beec93276d/pkg/raft/tracker/fortificationtracker.go#L33)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"was a leader at since the last time it restarted."
</blockquote></details>

Good catch. Done.

**Pull request merged**
