### PR TITLE
importccl: avoid double ProducerDone call

### PR DESCRIPTION
**Pull request by dt**
Previously this code was (mis)using the various layers of `EmitHelper`,
`ProcOutputHelper`, `DrainAndClose`, etc. In some cases this led to
unexpected sending after closing or closing more than once.

The import processor has no upstream sources it needs to drain, nor
fancy output filtering/projections/renderings that require those helpers
to do, so most of those helpers were not actually adding value over the
RowReceiver API, and just using it instead yields an overall simpler
flow, where it is easier to see when ProducerClosed is called i.e.
exactly once, in a defer in `Run()`.

Release note: None

An alternative, potentially better solution, might be to instead use
_more_ of the common helpers, such that things like emitting and closing
are all done for us. Specifically, one suggestion was to embed
ProcessorBase only need to implement its Next() API. However current 
implementation using a waitgroup concurrently running the various stages
does not lend itself directly to the `Next()` pattern so this would be a
more substantial change that can happen, if needed, in a followup.

### CODE REVIEW

**Review by spaskob — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39992)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by dt** [comment]
looks like an unrelated roachtest flake in gossip/restart: ` IO error: While lock file: /home/roach/local/4/data/cockroach-temp528902534/TEMP_DIR.LOCK: Resource temporarily unavailable`

bors r+

**Pull request merged**
