### PR TITLE
datadriven: touch up and add ScanArgs

### PR DESCRIPTION
**Pull request by tbg**
We should use data driven tests in more places. I have started doing so
in unpublished work and have found ScanArgs to be an extremely useful
addition as it cuts down on boilerplate code in tests.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34451)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/testutils/datadriven/datadriven.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34451#-LXZTHUZBDovKE8IDcx_:-LXZTHUZBDovKE8IDcxa:b-c2x64s) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1f5f2ec82e2a0280ef16c00fe61214194e05858/pkg/testutils/datadriven/datadriven.go#L90)):*
> ```Go
> 
> func runTestInternal(
> 	t *testing.T, optionalPath string, reader io.Reader, f func(d *TestData) string,
> ```

I'd make this required, call it `sourceName`, and pass in `"<string>"` in `RunTestFromString`.

Is the issue that you check `optionalPath` below? If so, I'd lean towards taking an optional `io.Writer` as an argument here instead.
___
*[pkg/testutils/datadriven/datadriven.go, line 230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34451#-LXZUuD71eDReCo0778V:-LXZUuD71eDReCo0778W:bpfchae) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1f5f2ec82e2a0280ef16c00fe61214194e05858/pkg/testutils/datadriven/datadriven.go#L230)):*
> ```Go
> 	var arg CmdArg
> 	for i := range td.CmdArgs {
> 		if td.CmdArgs[i].Key == key {
> ```

Do we verify that CmdArg keys are unique?
___
*[pkg/testutils/datadriven/test_data_reader.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34451#-LXZSeH9AcCPP1kisLzW:-LXZSeH9AcCPP1kisLzX:b-pbaj1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1f5f2ec82e2a0280ef16c00fe61214194e05858/pkg/testutils/datadriven/test_data_reader.go#L28)):*
> ```Go
> type testDataReader struct {
> 	sourceName string
> 	file       io.Reader
> ```

I wouldn't call this `file` if it won't always be a file. `source` would be better.
___
*[pkg/testutils/datadriven/test_data_reader.go, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34451#-LXZT3ML0BvgAHKnkmmP:-LXZT3ML0BvgAHKnkmmQ:bdsrmco) ([raw file](https://github.com/cockroachdb/cockroach/blob/442662f3f739f631be72b67bce4c4d6c4b47113e/pkg/testutils/datadriven/test_data_reader.go#L53)):*
> ```Go
> }
> 
> func (r *testDataReader) Close() error {
> ```

Yikes, looks like this was never being called.

**Review by tbg — COMMENTED** [review]
TFTR!

bors r=nvanbenschoten

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34451#-:-LX_gize4bp_G71ray8X:b-l0r5kv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/testutils/datadriven/datadriven.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34451#-LXZTHUZBDovKE8IDcx_:-LX_eV6g1y9VV1-6kVTx:b6nqvo6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1f5f2ec82e2a0280ef16c00fe61214194e05858/pkg/testutils/datadriven/datadriven.go#L90)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'd make this required, call it `sourceName`, and pass in `"<string>"` in `RunTestFromString`.

Is the issue that you check `optionalPath` below? If so, I'd lean towards taking an optional `io.Writer` as an argument here instead.
</blockquote></details>

I didn't do that exact thing because it seemed weird (passing the same file in as a reader and writer at the same time looks scary) but I did something that probably alleviates your concerns (and verified that it works).
___
*[pkg/testutils/datadriven/datadriven.go, line 230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34451#-LXZUuD71eDReCo0778V:-LX_ez3_9Wy1CeEjz4GH:b3htlnr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1f5f2ec82e2a0280ef16c00fe61214194e05858/pkg/testutils/datadriven/datadriven.go#L230)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we verify that CmdArg keys are unique?
</blockquote></details>

No, doesn't look like it, but it could be useful (for example you could have `cmd replica=1 replica=2 replica=3` to set up some test with three replicas). I don't want to change it, but at the same time I don't think the API here needs to accommodate it (the comment states that it simply uses the first one). Probably we should prevent duplicates though. Either way, I'll leave as is. (PS of course I had a bug that would actually use the last occurrence rather than the first, now fixed since I added a test).
___
*[pkg/testutils/datadriven/test_data_reader.go, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34451#-LXZT3ML0BvgAHKnkmmP:-LX_fxeD9Aeb2RvBDxxT:b-3vw66i) ([raw file](https://github.com/cockroachdb/cockroach/blob/442662f3f739f631be72b67bce4c4d6c4b47113e/pkg/testutils/datadriven/test_data_reader.go#L53)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yikes, looks like this was never being called.
</blockquote></details>

:man_shrugging: weird that none of the zero tests caught it.
To be fair, I think it also didn't matter.

**Review by tbg — COMMENTED** [review]
bors r-

Goland was too eager refactoring. Got some of the comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34451#-:-LX_h-qbDHL8QFc3oJih:bdfz3o8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by tbg — COMMENTED** [review]
bors r=nvanbenschoten

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34451#-:-LX_hHs-8BF2CWf9zfva:b-nvg7rs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Pull request merged**
