### PR TITLE
release-21.2: kvserver: don't transfer leases to draining nodes during scatters

### PR DESCRIPTION
**Pull request by aayushshah15**
Backport:
  * 3/4 commits from "kvserver: don't transfer leases to draining nodes during scatters" (#79295)
  * 1/1 commits from "kv: fix logging of leaseholder's StoreID in ShouldTransferLease" (#79581)

Please see individual PRs for details.

Release justification: bug fix.

/cc @cockroachdb/release

### CODE REVIEW

**Review by nvb — CHANGES_REQUESTED** [review]
Thanks for backporting this! Should we close https://github.com/cockroachdb/cockroach/pull/80835?

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 4 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88725#-:-ND-n77g2Fm9O-WntwkB:b7csk80)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[`pkg/kv/kvserver/replicate_queue.go` line 826 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88725#-ND-me8MA8nvWq5FvrNt:-ND-me8MA8nvWq5FvrNu:byutwc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/efe32e6065efe18f0526b9fabc2a215c3d51cd5e/pkg/kv/kvserver/replicate_queue.go#L826)):*
> ```Go
> 		conf,
> 		transferLeaseOptions{
> 			goal:   leaseCountConvergence,
> ```

I don't follow why this line was deleted. It doesn't seem to have been in #79295. I'm sure there's a good reason.
___
*[`pkg/kv/kvserver/scatter_test.go` line 60 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/88725#-ND-n3eT5jo38NTnfw_t:-ND-n3eT5jo38NTnfw_u:b-b0mg90) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4f874be962ac0aa62b7cc746e3f9b484ce91ba0/pkg/kv/kvserver/scatter_test.go#L60)):*
> ```Go
> 	client, err := tc.GetAdminClient(ctx, t, drainingServerIdx)
> 	require.NoError(t, err)
> 	drain(ctx, t, client, drainingNodeID)
> ```

Should this change have been part of the previous commit?

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88725)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/replicate_queue.go` line 826 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88725#-ND-me8MA8nvWq5FvrNt:-ND-vYxyB6ivlueZIF9I:b-8zcage) ([raw file](https://github.com/cockroachdb/cockroach/blob/efe32e6065efe18f0526b9fabc2a215c3d51cd5e/pkg/kv/kvserver/replicate_queue.go#L826)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I don't follow why this line was deleted. It doesn't seem to have been in #79295. I'm sure there's a good reason.
</blockquote></details>

`TransferLeaseTarget` did not support QPS convergence as a goal in 21.2, and `transferLeaseOptions` has no `goal` attribute in this version. 
___
*[`pkg/kv/kvserver/scatter_test.go` line 60 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/88725#-ND-n3eT5jo38NTnfw_t:-ND-w6kYBG6o8BhH31xP:b-e1zlng) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4f874be962ac0aa62b7cc746e3f9b484ce91ba0/pkg/kv/kvserver/scatter_test.go#L60)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should this change have been part of the previous commit?
</blockquote></details>

Oh, good catch.

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88725)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[`pkg/kv/kvserver/replicate_queue.go` line 826 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88725#-ND-me8MA8nvWq5FvrNt:-ND-x4hU9XvnpP-UTEh5:bxduswl) ([raw file](https://github.com/cockroachdb/cockroach/blob/efe32e6065efe18f0526b9fabc2a215c3d51cd5e/pkg/kv/kvserver/replicate_queue.go#L826)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

`TransferLeaseTarget` did not support QPS convergence as a goal in 21.2, and `transferLeaseOptions` has no `goal` attribute in this version. 
</blockquote></details>

Oh, so we added this line in one commit and removed it in the next? I think that's what confused me. Should we remove the change from the first commit to avoid the confusion?

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88725)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/replicate_queue.go` line 826 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88725#-ND-me8MA8nvWq5FvrNt:-ND46Y2X7UjyAMmyYwMG:bpypav7) ([raw file](https://github.com/cockroachdb/cockroach/blob/efe32e6065efe18f0526b9fabc2a215c3d51cd5e/pkg/kv/kvserver/replicate_queue.go#L826)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Oh, so we added this line in one commit and removed it in the next? I think that's what confused me. Should we remove the change from the first commit to avoid the confusion?
</blockquote></details>

oh, my bad on mixing this up. Fixed now.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r8, 4 of 4 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88725#-:-NDTwZJ_0TAPlCjEefc1:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)

**Pull request merged**
