### PR TITLE
cli/start: fix immediate stop upon double sigs

### LINKED ISSUE #34354: *log.safeError: start_unix.go:49: syscall.Errno: function not implemented
Sentry Issue: [COCKROACHDB-R6](https://sentry.io/cockroach-labs/cockroachdb/issues/854671961/?referrer=github_integration)

```
*log.safeError: start_unix.go:49: syscall.Errno: function not implemented
  File "github.com/cockroachdb/cockroach/pkg/cli/start.go", line 859, in runStart
  File "github.com/cockroachdb/cockroach/pkg/cli/error.go", line 70, in func1
  File "github.com/cockroachdb/cockroach/pkg/cli/error.go", line 215, in func1
  File "github.com/cockroachdb/cockroach/pkg/cli/cli.go", line 194, in Run
  File "github.com/cockroachdb/cockroach/pkg/cli/cli.go", line 70, in Main
...
(5 additional frame(s) were not displayed)

start_unix.go:49: syscall.Errno: function not implemented
```

### PR DESCRIPTION
**Pull request by knz**
Fixes #34354.

`cockroach start` uses little dance to handle signals: the first
signal is taken as a request to perform graceful shutdown; if another
signal is received during graceful shutdown it is taken as a request
to terminate immediately.

The handling of the hard shutdown signal is done on unix targets by
disabling the cockroachdb signal handler, then forwarding the signal
again to the process. We forward the signal so that any
signal-specific behavior can occur as normal; in particular SIGQUIT
should cause a goroutine dump.

However telemetry is reporting to us that `unix.Kill()` returns ENOSYS
in some cases (on `linux-amd64` targets). I suspect this is a
container which limits access to syscalls from contained
processes. Prior to this patch, such an error would cause a disorderly
shutdown with a panic.

This patch ensures that the shutdown still occurs in that case, using
log.Fatal instead of a panic.

Release note: None

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34366)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Review by tbg — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34366)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
