### PR TITLE
util/decimal: error on large arguments to pow

### LINKED ISSUE #10311: sql: panic with POW
```
SELECT pow(4.58966308373723e-06, -3.1962622854859143e+33)
```

The panic is in the inf package.

Found with RSG.

### PR DESCRIPTION
**Pull request by madelynnblue**
Fixes #10311

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10525)

### CODE REVIEW

**Comment by mjibson** [comment]
Don't review this yet. It's got some bugs.

**Comment by mjibson** [comment]
Ok PTAL.

**Comment by nvanbenschoten** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/util/decimal/decimal.go, line 429 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10525#-KW1HnSa86ZR6gaunkUe:-KW1HnSa86ZR6gaunkUf:bwt2t2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/97ee1c931c057eaa29195d916320b63e61fe8141/pkg/util/decimal/decimal.go#L429)):*
> ```Go
> )
> 
> // maxPrecision is the number of decimal digits (sum of before and after the
> ```

`s/sum of before/sum of digits before/g` or something like that. Also, I think the sentence should say something like `maxPrecision is the largest number of decimal digits before an errArgumentTooLarge is returned for any computation.`

---

*[pkg/util/decimal/decimal.go, line 430 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10525#-KW1IbBv6zrKfar0ylEF:-KW1IbBv6zrKfar0ylEG:b-jsny0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/97ee1c931c057eaa29195d916320b63e61fe8141/pkg/util/decimal/decimal.go#L430)):*
> ```Go
> 
> // maxPrecision is the number of decimal digits (sum of before and after the
> // decimal point) that should return errArgumentTooLarge for any computation.
> ```

`"for any computation"`: is this enforced elsewhere (eg. `Sqrt`)?

---

*[pkg/util/decimal/decimal.go, line 488 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10525#-KW1JFxIvy4Ke0tO2e3X:-KW1JFxIvy4Ke0tO2e3Y:b-nfsxaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/97ee1c931c057eaa29195d916320b63e61fe8141/pkg/util/decimal/decimal.go#L488)):*
> ```Go
> 	// exponent precision = s + <the number of digits before decimal point in x> * y
> 	es := s + inf.Scale(numDigits*yu)
> 	if es < 0 || es > maxPrecision {
> ```

Is `es` is negative, is this still the same error PG will return (that's assuming PG has this error)? 

---

*[pkg/util/decimal/loop.go, line 40 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10525#-KW1JR8ucLaYvCJDLLbm:-KW1JR8ucLaYvCJDLLbn:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/97ee1c931c057eaa29195d916320b63e61fe8141/pkg/util/decimal/loop.go#L40)):*
> ```Go
> }
> 
> const digitsToBitsRatio = math.Ln10 / math.Ln2
> ```

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10525)*

**Comment by mjibson** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/util/decimal/decimal.go, line 429 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10525#-KW1HnSa86ZR6gaunkUe:-KW1XCai_iB-PmsD2oK0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/97ee1c931c057eaa29195d916320b63e61fe8141/pkg/util/decimal/decimal.go#L429)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> `s/sum of before/sum of digits before/g` or something like that. Also, I think the sentence should say something like `maxPrecision is the largest number of decimal digits before an errArgumentTooLarge is returned for any computation.`
</details>
Done.

---

*[pkg/util/decimal/decimal.go, line 430 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10525#-KW1IbBv6zrKfar0ylEF:-KW1XE0F8k6FA2tLnDpM:bw8wbkd) ([raw file](https://github.com/cockroachdb/cockroach/blob/97ee1c931c057eaa29195d916320b63e61fe8141/pkg/util/decimal/decimal.go#L430)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> `"for any computation"`: is this enforced elsewhere (eg. `Sqrt`)?
</details>
Nope. My plan is to wait for RSG to find more bugs after these fixes go in. If everything still works, then no need to change sqrt.

---

*[pkg/util/decimal/decimal.go, line 488 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10525#-KW1JFxIvy4Ke0tO2e3X:-KW1XNN5ix7SBHW-vA8b:b-3lb2b1) ([raw file](https://github.com/cockroachdb/cockroach/blob/97ee1c931c057eaa29195d916320b63e61fe8141/pkg/util/decimal/decimal.go#L488)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Is `es` is negative, is this still the same error PG will return (that's assuming PG has this error)? 
</details>
Negative `es` occurs when `numDigits*yu > math.MaxInt32` and it wraps around when converted to a inf.Scale (which is just an int32).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10525)*

**Pull request merged**
