### PR TITLE
workload: improve cli ux

### PR DESCRIPTION
**Pull request by danhhz**
First, move pkg/testutils/workload/cmd/workload to pkg/cmd/workload. I was originally planning on waiting until this supported splits to move it, but enough people have been confused by why it's not in pkg/cmd/workoad that I've changed my mind.

Move operation workload flags (--concurrency, --max-ops, etc) under the subcommands; the root cmd is not executable, so it doesn't make any sense to have them there. Also add workload descriptions for the cli help. Add a package to register all known workloads, for when that's
desirable.

While I'm here, add an operation to bank, so it makes sense for it to be in the workload cli.

### CODE REVIEW

**Comment by tschottdorf** [comment]
Reviewed 4 of 4 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/cmd/workload/main.go, line 52 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21267#-L26eiSJIvEEQVkF8GBH:-L26eiSJIvEEQVkF8GBI:b-jshn4v) ([raw file](https://github.com/cockroachdb/cockroach/blob/e205c23f976cc757776e48268f2c95edbad1f8c3/pkg/cmd/workload/main.go#L52)):*
> ```Go
> }
> 
> var rootFlags = pflag.NewFlagSet(`workload`, pflag.ContinueOnError)
> ```

If the impetus here is solely that the root command isn't executable, I'm not sure I follow. Conceptually, these flags are (or rather, should be) unknown to the workloads themselves -- they belong to the driver. By leaking them into all workloads, it's unclear that the workloads themselves really shouldn't care about them, and we risk ambiguity in who does what. That, or, we make the driver not do anything with the flags, but then all the commands reimplement things over and over again, or don't implement certain things, at which point you can pass flags that don't have an effect. Both are undesirable; I thought we were going to have a small set of top-level flags that apply to *any* workload and that the workload is agnostic of.

---

*[pkg/cmd/workload/main.go, line 55 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21267#-L26dqUSWKUM7CEuxyip:-L26dqUSWKUM7CEuxyiq:bfn1o4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/e205c23f976cc757776e48268f2c95edbad1f8c3/pkg/cmd/workload/main.go#L55)):*
> ```Go
> var concurrency = rootFlags.Int(
> 	"concurrency", 2*runtime.NumCPU(), "Number of concurrent writers inserting blocks")
> var batch = rootFlags.Int("batch", 1, "Number of blocks to insert in a single SQL statement")
> ```

Does this flag make sense? If so, it needs a better comment.

---

*[pkg/testutils/workload/workload.go, line 40 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21267#-L26eANGQ3ZiFYbnGVWK:-L26eANGQ3ZiFYbnGVWL:b9c3gx5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e205c23f976cc757776e48268f2c95edbad1f8c3/pkg/testutils/workload/workload.go#L40)):*
> ```Go
> type Generator interface {
> 	// Meta returns a unique name for this generator as well as a description.
> 	Meta() (name string, description string)
> ```

I had this itch earlier already and ignored it, but now since you're making this more official: I think `GeneratorFn` should be an interface an implement `Meta()` because it's awkward that you need to make a throwaway object just to find out what the `Meta` is. Or, perhaps nicer, `Register` can take a `Meta` and a `GeneratorFn` and store them together.

---

*[pkg/testutils/workload/kv/kv.go, line 38 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21267#-L26f_Sde_k-Z3IlSu0p:-L26f_Sde_k-Z3IlSu0q:bih30lm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e205c23f976cc757776e48268f2c95edbad1f8c3/pkg/testutils/workload/kv/kv.go#L38)):*
> ```Go
> const (
> 	kvSchema      = `(k BIGINT NOT NULL PRIMARY KEY, v BYTES NOT NULL)`
> 	kvDescription = `KV reads and writes to keys spread uniformly at random` +
> ```

It's not necessarily random or uniformly, if we use `--sequential` and/or `--cycle-length`. Perhaps just add "by default" somewhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21267)*

**Comment by danhhz** [comment]
Thanks for the review! RFAL

---

Review status: 2 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/cmd/workload/main.go, line 52 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21267#-L26eiSJIvEEQVkF8GBH:-L276-CgRe49GY7eLxTi:bha9q81) ([raw file](https://github.com/cockroachdb/cockroach/blob/e205c23f976cc757776e48268f2c95edbad1f8c3/pkg/cmd/workload/main.go#L52)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

If the impetus here is solely that the root command isn't executable, I'm not sure I follow. Conceptually, these flags are (or rather, should be) unknown to the workloads themselves -- they belong to the driver. By leaking them into all workloads, it's unclear that the workloads themselves really shouldn't care about them, and we risk ambiguity in who does what. That, or, we make the driver not do anything with the flags, but then all the commands reimplement things over and over again, or don't implement certain things, at which point you can pass flags that don't have an effect. Both are undesirable; I thought we were going to have a small set of top-level flags that apply to *any* workload and that the workload is agnostic of.
</blockquote></details>

I'm a little bit confused here, because I _think_ this is doing what you're asking for, but I'm not certain enough of that to say it for sure. The `rootCmd` currently has no flags and just aggregates the subcommands, one per workload. Each workload's `cobra.Command` gets the rootFlags as well as it's own flags (so they can all be specified on the cli). However, at runtime, only the flags the workload has declared (via `(workload.Generator).Flags`) get passed to it, so they don't get anything from `rootFlags`. If that doesn't sound like what you're looking for, can you describe it again in a little more detail because I don't think I'm on the same page yet.

---

*[pkg/cmd/workload/main.go, line 55 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21267#-L26dqUSWKUM7CEuxyip:-L277MlUKctLXIcCOxly:b8r8hps) ([raw file](https://github.com/cockroachdb/cockroach/blob/e205c23f976cc757776e48268f2c95edbad1f8c3/pkg/cmd/workload/main.go#L55)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Does this flag make sense? If so, it needs a better comment.
</blockquote></details>

Whoops, this is not the only thing that still talks about blocks

batch was both here and in kv because we needed it here to compute if we've hit maxOps and we needed it in kv to actually make a batched sql statement. it's been bugging me that it breaks the abstraction, so this prompt was enough motivation for me to remove it here. this means the tool operates a _bit_ differently than `kv` now. If you specify `--batch=10 --max-ops=100`, then `kv` will affect 100 rows but `workload kv` will now affect 1000 rows. wdyt?

---

*[pkg/testutils/workload/workload.go, line 40 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21267#-L26eANGQ3ZiFYbnGVWK:-L27CiYwPJZ6cFbbL6PM:b-73nnlm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e205c23f976cc757776e48268f2c95edbad1f8c3/pkg/testutils/workload/workload.go#L40)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

I had this itch earlier already and ignored it, but now since you're making this more official: I think `GeneratorFn` should be an interface an implement `Meta()` because it's awkward that you need to make a throwaway object just to find out what the `Meta` is. Or, perhaps nicer, `Register` can take a `Meta` and a `GeneratorFn` and store them together.
</blockquote></details>

I love the Meta name. I made it a struct to cut down on per-generator boilerplate. This cleans up a lot!

---

*[pkg/testutils/workload/kv/kv.go, line 38 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21267#-L26f_Sde_k-Z3IlSu0p:-L27CyrWiLTSsttYE4gG:b6d88r7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e205c23f976cc757776e48268f2c95edbad1f8c3/pkg/testutils/workload/kv/kv.go#L38)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

It's not necessarily random or uniformly, if we use `--sequential` and/or `--cycle-length`. Perhaps just add "by default" somewhere.
</blockquote></details>

Done. (I cribbed this from the loadgen repo's README, so sounds like that's rotted)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21267#-:-L27DUU09bjQu5rBLx67:b-6sx6b6)*

**Comment by tschottdorf** [comment]
:lgtm_strong: I left some more comments, but I wouldn't be surprised if all that's missing here is reminding me of a few things.

---

Reviewed 1 of 4 files at r1, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/cmd/workload/main.go, line 52 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21267#-L26eiSJIvEEQVkF8GBH:-L27SEXwt4Nu1A87rKm3:b-rd7ka2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e205c23f976cc757776e48268f2c95edbad1f8c3/pkg/cmd/workload/main.go#L52)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I'm a little bit confused here, because I _think_ this is doing what you're asking for, but I'm not certain enough of that to say it for sure. The `rootCmd` currently has no flags and just aggregates the subcommands, one per workload. Each workload's `cobra.Command` gets the rootFlags as well as it's own flags (so they can all be specified on the cli). However, at runtime, only the flags the workload has declared (via `(workload.Generator).Flags`) get passed to it, so they don't get anything from `rootFlags`. If that doesn't sound like what you're looking for, can you describe it again in a little more detail because I don't think I'm on the same page yet.
</blockquote></details>

Oh, maybe this is working the way I want? But I don't understand why the previous state was undesirable.

```
$ go run pkg/testutils/workload/cmd/workload/*.go kv --help
```

shows all the flags prior to this PR (that's just how cobra works)

and

```
$ go run pkg/testutils/workload/cmd/workload/*.go --help
```

shows only the top-level flags, which is also fine (as they apply to any workload). The only change I can see you made is that your PR won't show them here, but I'm not convinced that makes sense (I'm also not convinced they would be missed, so no objection to leaving as is! It just seems more complicated to understand what's going on now).

---

*[pkg/cmd/workload/main.go, line 55 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21267#-L26dqUSWKUM7CEuxyip:-L27TagQct6G5JdQmB73:bq6xo1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/e205c23f976cc757776e48268f2c95edbad1f8c3/pkg/cmd/workload/main.go#L55)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Whoops, this is not the only thing that still talks about blocks

batch was both here and in kv because we needed it here to compute if we've hit maxOps and we needed it in kv to actually make a batched sql statement. it's been bugging me that it breaks the abstraction, so this prompt was enough motivation for me to remove it here. this means the tool operates a _bit_ differently than `kv` now. If you specify `--batch=10 --max-ops=100`, then `kv` will affect 100 rows but `workload kv` will now affect 1000 rows. wdyt?
</blockquote></details>

+1, I think that's better for the abstraction, we just have to be a little careful when porting any existing benchmarks over in the future.

---

*[pkg/cmd/workload/main.go, line 79 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21267#-L27UbcnX4a04MBA7GNe:-L27UbcnX4a04MBA7GNf:b-4c80v) ([raw file](https://github.com/cockroachdb/cockroach/blob/98f80137a45bd92f7733963414ac9eeb8f0774ec/pkg/cmd/workload/main.go#L79)):*
This comment is strictly optional!

Now it seems cleaner to do `meta := meta` and to update the comment, because I think you actually want to pass `meta` all the way down to `runRoot` and then drop `Meta()` from the interface (it's a little bit of a wart, being a backdoor to the `meta` you've let go too early). The new comment could say

> // Make a loop-local copy of `meta` for use in the closure. Without this
> // copy, all of the closures would end up using the `meta` from the last
> // iteration.

I'm also not clear why you need this factory pattern anyway, but there's probably an obvious reason I'm missing now. Why can't the bank one just read

```go
bankMeta := Meta{
    // ...
    Generator: &bank{ ... },
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21267#-:-L27TvBlVFjWmFcEpE9o:b-cgy58h)*

**Comment by danhhz** [comment]
Thanks v2 for the review!

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/cmd/workload/main.go, line 52 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21267#-L26eiSJIvEEQVkF8GBH:-L2LlI8o9FLDjzzVG7IN:b-f28384) ([raw file](https://github.com/cockroachdb/cockroach/blob/e205c23f976cc757776e48268f2c95edbad1f8c3/pkg/cmd/workload/main.go#L52)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Oh, maybe this is working the way I want? But I don't understand why the previous state was undesirable.

```
$ go run pkg/testutils/workload/cmd/workload/*.go kv --help
```

shows all the flags prior to this PR (that's just how cobra works)

and

```
$ go run pkg/testutils/workload/cmd/workload/*.go --help
```

shows only the top-level flags, which is also fine (as they apply to any workload). The only change I can see you made is that your PR won't show them here, but I'm not convinced that makes sense (I'm also not convinced they would be missed, so no objection to leaving as is! It just seems more complicated to understand what's going on now).
</blockquote></details>

Discussed this offline and turns out we were talking about different things. I did this because I thought @tschottdorf had asked for it in slack, but what he was actually asking for was why the flags were still very `kv` specific. Leaving this as-is since it's really a wash either way.

---

*[pkg/cmd/workload/main.go, line 79 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21267#-L27UbcnX4a04MBA7GNe:-L2LlteYXKjUUbRZZzvT:b-gi2b28) ([raw file](https://github.com/cockroachdb/cockroach/blob/98f80137a45bd92f7733963414ac9eeb8f0774ec/pkg/cmd/workload/main.go#L79)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

This comment is strictly optional!

Now it seems cleaner to do `meta := meta` and to update the comment, because I think you actually want to pass `meta` all the way down to `runRoot` and then drop `Meta()` from the interface (it's a little bit of a wart, being a backdoor to the `meta` you've let go too early). The new comment could say

> // Make a loop-local copy of `meta` for use in the closure. Without this
> // copy, all of the closures would end up using the `meta` from the last
> // iteration.

I'm also not clear why you need this factory pattern anyway, but there's probably an obvious reason I'm missing now. Why can't the bank one just read

```go
bankMeta := Meta{
    // ...
    Generator: &bank{ ... },
}
```
</blockquote></details>

Yeah, I don't think this is perfect either, but it's certainly workable and I want to move onto the more interesting bits, so I'm inclined to leave this as-is. We need the factory because (especially once this starts getting used unit tests, the magic distsql data synthesis, etc) we don't want one global copy of each

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21267#-:-L2LmblryPMTjfaf_78x:bxhmggh)*

**Pull request merged**
