### PR TITLE
sql: make the source tree more regular

### PR DESCRIPTION
**Pull request by knz**
For the purpose of facilitating the next stage of refactorings.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
LGTM

**Comment by jordanlewis** [comment]
wait please don't merge this yet i'm still reviewing it

---

Reviewed 35 of 36 files at r1, 48 of 48 files at r2.
Review status: 54 of 100 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/show_zone_config.go, line 128 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20307#-L-3ZdRCPpVDZkYae7WJ:-L-3ZdRDcUy88tMvUbao:b-bfcu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6654a2c59826528ee6bf26fe60da53af2af88a0/pkg/sql/show_zone_config.go#L128)):*
> ```Go
> 
> func (n *showZoneConfigNode) Next(runParams) (bool, error) {
> 	if !n.run.done {
> ```

Please resist the urge to make actual code changes during large refactorings! I only spotted this because I am diffing these by hand, but every code change you make during a code movement

1. makes the code harder to review
2. decreases my confidence that these changes aren't hiding sneaky functionality changes and/or mistakes

It's not necessary to rebase this change out. Just saying for next time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20307#-:-L-3a348X9YluxtLpbWs:bxq57ek)*

**Comment by jordanlewis** [comment]
:lgtm_strong: thanks for making it happen!

---

Reviewed 35 of 35 files at r3, 5 of 5 files at r4, 11 of 11 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/rename_index.go, line 94 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20307#-L-3aWKdROTgBPX3sP_i:-L-3aWKdROTgBPX3sP_j:b-pshs7e) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfde6345d72ce3808d222577e362cb12c56b33f3/pkg/sql/rename_index.go#L94)):*
> ```Go
> }
> 
> var errEmptyIndexName = errors.New("empty index name")
> ```

I find it weird to put vars at the bottom? Not going to make a fuss about it though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20307#-:-L-3fyshi08CBK88rkzV:bkes0mc)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/rename_index.go, line 94 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20307#-L-3aWKdROTgBPX3sP_i:-L-3uQOGHHNTNpmpfiL5:b-mxqnh4) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfde6345d72ce3808d222577e362cb12c56b33f3/pkg/sql/rename_index.go#L94)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I find it weird to put vars at the bottom? Not going to make a fuss about it though.
</blockquote></details>

I'll agree with you it's a little bit weird, especially since it's the only thing. Moved back up.

---

*[pkg/sql/show_zone_config.go, line 128 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20307#-L-3ZdRCPpVDZkYae7WJ:-L-3tzRT6DaqER-hAEGS:b-mfzb1n) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6654a2c59826528ee6bf26fe60da53af2af88a0/pkg/sql/show_zone_config.go#L128)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Please resist the urge to make actual code changes during large refactorings! I only spotted this because I am diffing these by hand, but every code change you make during a code movement

1. makes the code harder to review
2. decreases my confidence that these changes aren't hiding sneaky functionality changes and/or mistakes

It's not necessary to rebase this change out. Just saying for next time.
</blockquote></details>

Yes this is entirely fair. I reverted the change (and tacked it on as a separate commit at the end).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20307)*

**Comment by knz** [comment]
TFYRs!

**Pull request merged**
