### PR TITLE
cherrypick-2.0: distsql: clean up lookup join internal columns

### LINKED ISSUE #24401: sql: bug with lookup join
Version: CockroachDB CCL v2.1-alpha.00000000-1468-gb9d7e8b12

The following table and query produces an error:

```
SET experimental_force_lookup_join = true;
create database d;
use d;
CREATE TABLE players (
	game INT NOT NULL,
	mode INT NULL,
	"time" TIMESTAMP NULL,
	hero INT NULL,
	team INT NULL,
	blizzid INT NOT NULL,
	CONSTRAINT "primary" PRIMARY KEY (game ASC, blizzid ASC)
);
select p.team = games.team as sameteam, p.hero
from (
	select game, max(team) team
	from players
	group by game
) games
join players p  on games.game = p.game;
```

`pq: "$4" = "$1": unsupported comparison operator: <timestamp> = <int>`

If I remove the SET line it runs. Interestingly, if I remove pretty much any line of the CREATE it also runs. Kinda feels like an incorrect index offset somewhere.

### PR DESCRIPTION
**Pull request by pbardea**
Cherry-picks #24697 and makes a few changes from the original PR:
- passing `nil` as the flowCtx in`processorBase.init` call in joinreader.go
- the output of the `EXPLAIN (VERBOSE)` test in the `lookup_join` logic test

Fixes #24401.

The distsql physical planner was not properly forming the post processor
spec according to the internal columns of lookup joins.

For the hash and merge joiners, the internal columns depend on the
streamToColMap of its upstream nodes. However since the lookup join's
internal columns consist of the entire right side of table columns, the
planner must modify the post processor spec and various maps.

This simplifies code inside the lookup joiner.

Release note (bug fix): Fix a bug causing some lookup join queries to
report incorrect type errors.

### CODE REVIEW

**Comment by andreimatei** [comment]
LGTM

No release note?

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/distsqlrun/joinreader.go, line 95 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24825#-LAEAzfm6ROUtONVwZCu:-LAEAzfm6ROUtONVwZCv:bik378b) ([raw file](https://github.com/cockroachdb/cockroach/blob/1916593695b17a21329c340356bc131d2bc541f7/pkg/sql/distsqlrun/joinreader.go#L95)):*
> ```Go
> 		indexCols[i] = uint32(jr.index.ColumnIDs[i])
> 	}
> 	if jr.isLookupJoin() {
> ```

what's going on here? How come `joinerBase.init()` isn't always called? That's very surprising. If that needs to be the case, can we add a comment to the `joinerBase` embedding explaining when/which `init()` is to be called?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24825#-:-LAEAFz45zbtYSL_BuCT:b-2ymsya)*

**Comment by pbardea** [comment]
This is mainly a bug fix (#24401), there is no explicit new functionality exposed so no release notes came to mind.

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/distsqlrun/joinreader.go, line 95 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24825#-LAEAzfm6ROUtONVwZCu:-LAEH2M874O1V_sQ9m9m:b-v43lgw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1916593695b17a21329c340356bc131d2bc541f7/pkg/sql/distsqlrun/joinreader.go#L95)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what's going on here? How come `joinerBase.init()` isn't always called? That's very surprising. If that needs to be the case, can we add a comment to the `joinerBase` embedding explaining when/which `init()` is to be called?
</blockquote></details>

`joinerBase.init` is only called in the lookup join case because that's when the internal columns include both sides of the join. This should be changed when addressing #24698 and `joinerBase.init()` should be called every time. I will add a comment to describe when each `init` is called.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24825#-:-LAEHYVf02Ob33VnBa-1:b4tkuwe)*

**Comment by andreimatei** [comment]
well bug fixes generally get called out in patch releases

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24825#-:-LAEOLPkCFrWOK7LdKmw:b-rqv00b)*

**Comment by pbardea** [comment]
i see. updated.

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24825#-:-LAEQ_pY9-sE-dlQony8:b8gwrng)*

**Comment by andreimatei** [comment]
LGTM

Please merge soon before someone picks the 2.0.1 sha.

nit: the release notes should make sense for users. Like "bug fix: fix a bug causing some queries involving lookup joins to fail with bogus typing errors"

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24825#-:-LAEZyaLDq3DrWvLjkKL:b-gwuhu7)*

**Pull request merged**
