### PR TITLE
ui: Single Node Page / Logs Update

### LINKED ISSUE #10365: ui: Inconsistent identification of nodes between list and details pages
On the node list page ("#/nodes/overview"), we appear to use hostnames to identify nodes:

screen shot 2016-11-01 at 11 06 47 am

But once you click on one of the nodes ("#/nodes/3"), we start identifying it by its ID:

screen shot 2016-11-01 at 11 17 11 am

Is there a reason for the inconsistency between the two? When I clicked through from the list page to a particular node's details, the change made me do a double take and retrace my steps to make sure I had clicked on the correct hostname.

@maxlang @kuanluo

### LINKED ISSUE #13230: ui: Complete single-node page
The current Admin UI design includes a "single node" page which is accessible by clicking on a specific node from the nodes list page.  While the single node page already exists, it has not been updated to match the current design; both the content and the appearance need to be updated.

### LINKED ISSUE #14625: The NODES link in the console does not work
**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
  Seems not necessary.

2. Please describe the issue you observed:

- What did you do?
  1. Start a node `node-1` with nodeID 1
  2. Access the console in http://localhost:8080/#/nodes/1
  3. Click the **NODES** link at the top, which jumps to http://localhost:8080/#/nodes

- What did you expect to see?
  See all nodes information like http://localhost:8080/#/cluster/nodes.

- What did you see instead?
  See nothing.

### PR DESCRIPTION
**Pull request by mrtracy**
Brings the single node page and the node log page up to a more current design.

+ Some minor refactoring of table styling to keep style consistent
between sorted and non-sorted tables.
+ Minor refactoring of SummaryBar components to accomodate new, slightly
different use cases.
+ Nodes are referenced by ID and Address in all places.

Closes #13230
Fixes #10365
Fixes #14625

screen shot 2017-04-28 at 3 01 15 pm

screen shot 2017-04-28 at 3 01 22 pm

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:, though much of this code is unfamiliar to me, and I didn't look at the styling changes closely.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/ui/src/index.tsx, line 89 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15486#-Kiv6ye9BhqsazMmJdrO:-Kiv6ye9BhqsazMmJdrP:b-t0m6s8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ffa33f30e366889eba69c9b3ca1848862e760c7/pkg/ui/src/index.tsx#L89)):*
> ```XML
> import HelpUs from "./containers/helpus";
> import Nodes from "./containers/nodes";
> import Node from "./containers/node";
> ```

is this file still in use?

---

*[pkg/ui/src/components/summaryBar.tsx, line 85 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15486#-Kiv7_c-1ho4iFdt8coK:-Kiv7_c-1ho4iFdt8coL:b-7fn519) ([raw file](https://github.com/cockroachdb/cockroach/blob/922a3d9cb70c15de2b786a1cf4c5d504712b3873/pkg/ui/src/components/summaryBar.tsx#L85)):*
> a single formatted number.

as opposed to what?

---

*[pkg/ui/src/containers/nodeLogs.tsx, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15486#-Kiv7fRUtDWqoLutWoQh:-Kiv7fRUtDWqoLutWoQi:bpwb9nr) ([raw file](https://github.com/cockroachdb/cockroach/blob/922a3d9cb70c15de2b786a1cf4c5d504712b3873/pkg/ui/src/containers/nodeLogs.tsx#L19)):*
> ```XML
> interface LogProps {
>   logs: LogEntriesResponseMessage;
>   node: NodeStatus$Properties;
> ```

"node" doesn't feel like the right name for this field.

---

*[pkg/ui/src/containers/nodeOverview.tsx, line 51 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15486#-Kiv8DXk3Okm5qC3Lmfb:-Kiv8DXk3Okm5qC3Lmfc:bdee5og) ([raw file](https://github.com/cockroachdb/cockroach/blob/922a3d9cb70c15de2b786a1cf4c5d504712b3873/pkg/ui/src/containers/nodeOverview.tsx#L51)):*
> ```XML
>     }
> 
>     const liveness = nodesSummary.livenessStatusByNodeID[node.desc.node_id] || 0;
> ```

the type of `liveness` is an enum, is that right? Could you use the enum name instead of `0`?

---

*[pkg/ui/src/containers/nodeOverview.tsx, line 74 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15486#-Kiv8MTrxpFRnVqe-Zb-:-Kiv8MTrxpFRnVqe-Zb0:b-vtqjze) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ffa33f30e366889eba69c9b3ca1848862e760c7/pkg/ui/src/containers/nodeOverview.tsx#L74)):*
> ```XML
>               <TableRow data={node}
>                         title="GC Bytes Age"
>                         valueFn={(metrics) => metrics[MetricConstants.gcBytesAge].toString()} />
> ```

did you mean to remove this?

---

*[pkg/ui/src/containers/nodeOverview.tsx, line 83 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15486#-Kiv8P3Hzepbfav8BsUI:-Kiv8P3Hzepbfav8BsUJ:b-zgaxya) ([raw file](https://github.com/cockroachdb/cockroach/blob/922a3d9cb70c15de2b786a1cf4c5d504712b3873/pkg/ui/src/containers/nodeOverview.tsx#L83)):*
> ```XML
>                           valueFn={(metrics) => Bytes(metrics[MetricConstants.liveBytes])} />
>                 <TableRow data={node}
>                           title="&nbsp;&nbsp;Key Bytes"
> ```

how come these nbsps are necessary?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15486#-:-Kiv8m3FmBIKQg66CD4x:b7ran3t)*

**Comment by tamird** [comment]
Does this also affect the dropdown in the cluster overview graphs? See https://github.com/cockroachdb/cockroach/issues/10365#issuecomment-298276404.

**Comment by mrtracy** [comment]
Review status: 3 of 9 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/ui/src/index.tsx, line 89 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15486#-Kiv6ye9BhqsazMmJdrO:-Kj0qSBrOBq1pEYc0U4m:b-he34i9) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ffa33f30e366889eba69c9b3ca1848862e760c7/pkg/ui/src/index.tsx#L89)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is this file still in use?
</blockquote></details>

No, i'll remove it.

---

*[pkg/ui/src/components/summaryBar.tsx, line 85 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15486#-Kiv7_c-1ho4iFdt8coK:-Kj0shJeakUHXFTsPwr4:bs5ua5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/922a3d9cb70c15de2b786a1cf4c5d504712b3873/pkg/ui/src/components/summaryBar.tsx#L85)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

> a single formatted number.

as opposed to what?
</blockquote></details>

As opposed to anything else, such as a string or a compound value.  I've expanded the comment.

---

*[pkg/ui/src/containers/nodeLogs.tsx, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15486#-Kiv7fRUtDWqoLutWoQh:-Kj0t0JMV6C5urHSYS1b:bdj07bt) ([raw file](https://github.com/cockroachdb/cockroach/blob/922a3d9cb70c15de2b786a1cf4c5d504712b3873/pkg/ui/src/containers/nodeLogs.tsx#L19)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

"node" doesn't feel like the right name for this field.
</blockquote></details>

Changed to "currentNode".

---

*[pkg/ui/src/containers/nodeOverview.tsx, line 51 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15486#-Kiv8DXk3Okm5qC3Lmfb:-Kj0tLEquuNqFj9J06ZP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/922a3d9cb70c15de2b786a1cf4c5d504712b3873/pkg/ui/src/containers/nodeOverview.tsx#L51)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

the type of `liveness` is an enum, is that right? Could you use the enum name instead of `0`?
</blockquote></details>

Done.

---

*[pkg/ui/src/containers/nodeOverview.tsx, line 74 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15486#-Kiv8MTrxpFRnVqe-Zb-:-Kj0qzgLgjuB1BqWCLhi:b91lxzi) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ffa33f30e366889eba69c9b3ca1848862e760c7/pkg/ui/src/containers/nodeOverview.tsx#L74)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

did you mean to remove this?
</blockquote></details>

Hmm, probably not, was playing with formatting.  Added back.

---

*[pkg/ui/src/containers/nodeOverview.tsx, line 83 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15486#-Kiv8P3Hzepbfav8BsUI:-Kj0qoCAp9J2RnDq49SM:bo1ld03) ([raw file](https://github.com/cockroachdb/cockroach/blob/922a3d9cb70c15de2b786a1cf4c5d504712b3873/pkg/ui/src/containers/nodeOverview.tsx#L83)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

how come these nbsps are necessary?
</blockquote></details>

This is kind of a crappy way to get these to titles to be indented and appear to be a sub-component of the value above, it's from the design.  However, now that I think about, i'm not certain that these are actually sub components, i'll just remove the spacing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15486)*

**Comment by tamird** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ui/src/containers/nodeLogs.tsx, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15486#-Kiv7fRUtDWqoLutWoQh:-Kj2jF3KaDSR9ldUxi93:b-pytgat) ([raw file](https://github.com/cockroachdb/cockroach/blob/922a3d9cb70c15de2b786a1cf4c5d504712b3873/pkg/ui/src/containers/nodeLogs.tsx#L19)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

Changed to "currentNode".
</blockquote></details>

I meant that it should be "nodeStatus" or similar, since that's the type.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15486)*

**Pull request merged**
