### PR TITLE
sql: use catalog.Mutation, catalog.Column and catalog.Index where possible

### LINKED ISSUE #63755: sql: use catalog.Column and catalog.Index outside of catalog
This is a child of #56306. The `catalog.Column` and `catalog.Index` interfaces should be used whenever possible, instead of `descpb.*`.

### PR DESCRIPTION
**Pull request by postamar**
sql: use catalog.Mutation where possible
    
    This commit is a refactor which introduces catalog.Mutation wherever
    possible, in an effort to avoid using the descpb.DescriptorMutation
    type directly.
    
    Release note: None

    sql: use catalog.Column and catalog.Index where possible
    
    This commit is a refactor which introduces the catalog.Column and
    catalog.Index interfaces wherever possible. These had recently been
    added in an effort to avoid using the descpb.ColumnDescriptor and
    descpb.IndexDescriptor types directly. This commit generalizes their
    usage throughout the sql packages.
    
    Fixes #63755.
    
    Release note: None

### CODE REVIEW

**Comment by postamar** [comment]
Review guide: due to its extensive diff this PR is always going to be plagued by merge conflicts. Let it be known however that this PR passed CI at the time of this writing, so it should be considered ready for review as it is. It's broken down into two commits which both should be treated as refactors:
- the `catalog.Mutation` commit moves quite a bit of schema_changer.go/backfill.go/truncate.go logic around
- the other one consists mostly of type changes propagated throughout `sql`

The changes are therefore extensive but superficial, as such they shouldn't require too deep an understanding of the code to be reviewed. 

@fqazi would you have time to take a look at this, please? I'd rather not burden Andrew further.

**Review by fqazi — APPROVED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63785)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @miretskiy)

**Comment by postamar** [comment]
Thanks for the review! Rebasing to fix merge conflict.

**Pull request merged**
