### PR TITLE
release: fix bincheck failures

### PR DESCRIPTION
**Pull request by rail**
Previously,  the bincheck test started failing after upgrading the linux build system to a newer GLIBC and after we changed the way we stop the server.

The linux bincheck test was relying on running the cockroach binary in a qemu-based VM, using a custom kernel.

Now that, we don't use rocksdb and don't have SSE issues (see #15589), we can simplify the test and run the binary without the VM layer.

This PR also fixes the issue, where the busybox `kill` command can only handle positional arguments.

We try our best to kill the server, but in some cases the PID changes and the whole test fail. Ignore the kill exit code and let the build agent to kill the process.

Epic: none
Fixes: RE-271
Release note: None

### CODE REVIEW

**Review by celiala — APPROVED** [review]
Woo - awesome! LGTM

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94975#-:-NLPwbyk3ZJOvYJwwvZy:bc8pjed)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rail)

___
*[`build/release/bincheck/test-linux` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94975#-NLPwQZs-Or9VLM7vdRU:-NLPwQZs-Or9VLM7vdRV:b-qo6c5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0352561542c59e9d797a738c5e4ad5efc910003/build/release/bincheck/test-linux#L16)):*
> ```
> 
> download_and_extract "$COCKROACH_VERSION" "linux-amd64.tgz"
> ./bincheck ./mnt/cockroach "$COCKROACH_VERSION" "$COCKROACH_SHA"
> ```

wow. amazing that this the solution is so clean/elegant!

**Comment by rail** [comment]
bors single on

**Comment by rail** [comment]
bors single on
bors retry

**Comment by rail** [comment]
bors ping

**Comment by rail** [comment]
bors retry

**Comment by rail** [comment]
bors single on

**Pull request merged**
