### PR TITLE
roachtest: fix pgjdbc tests

### PR DESCRIPTION
**Pull request by rafiss**
The pgjdbc tests have two types of failures: one referred to as
"failures" and the other one as "errors." We were only counting the
former before. Now there are many more test failures that should be
tracked in the blacklist.

touches #39406 

Release note: None

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
:lgtm: (I didn't carefully review this, but it seems right :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39420#-:-Lln5RGT6F_0EgpQ9XQa:byhr1xt)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by rafiss** [comment]
thanks! i might have to update the blacklist again after this is merged, so i'm not closing the linked issue yet.

bors r+

**Comment by awoods187** [comment]
Have we done the work to triage the failures and errors? Do we truly think we should be failing all of them?

**Comment by rafiss** [comment]
@awoods187 yeah you are right; I do plan to do that triage work on a more long-term basis after the tests are in place. Many of the issues are caused by our lack of user-defined schema support, so it would be ideal if we could find a way around that in these tests.

**Comment by awoods187** [comment]
Makes sense--I just want to make sure we don't finalize this work till we comb the failure lists. Sounds like you are on top of it!

**Pull request merged**
