### PR TITLE
sql: use planner's lease acquisition to get tableDesc for FKs

### PR DESCRIPTION
**Pull request by dt**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7133)

### CODE REVIEW

**Comment by paperstreet** [comment]
:lgtm:

<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> #### sql: use planner&#39;s lease acquisition to get tableDesc for FKs
</details>


---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/table.go, line 226 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7133#-KJpgDcW97duxktDH-ec:-KJpgDcW97duxktDH-ed:550845463) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea23feb371fd3045506758f3308ad9a66f9aceda/sql/table.go#L226)):*
> ```Go
> }
> 
> // getTableLeaseByID
> ```

finish comment

---

*[sql/table.go, line 227 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7133#-KJpgNmSuzUwczzs3AHb:-KJpgNmSuzUwczzs3AHc:-1332174065) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea23feb371fd3045506758f3308ad9a66f9aceda/sql/table.go#L227)):*
> ```Go
> 
> // getTableLeaseByID
> func (p *planner) getTableLeaseByID(table sqlbase.ID) (*sqlbase.TableDescriptor, error) {
> ```

nit: tableID

---

*[sql/table.go, line 252 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7133#-KJpgRVcGtm2klyyVD60:-KJpgRVcGtm2klyyVD61:240367057) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea23feb371fd3045506758f3308ad9a66f9aceda/sql/table.go#L252)):*
> ```Go
> 			if err == errDescriptorNotFound {
> 				// Transform the descriptor error into an error that references the
> 				// table's name.
> ```

s/name/id/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7133#-:-KJpgYHVH-k95-7zd1K-:1417088721)*

**Comment by dt** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/table.go, line 226 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7133#-KJpgDcW97duxktDH-ec:-KJphYb8BycCAp-Mzdsz:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea23feb371fd3045506758f3308ad9a66f9aceda/sql/table.go#L226)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> finish comment
</details>
Done.

---

*[sql/table.go, line 227 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7133#-KJpgNmSuzUwczzs3AHb:-KJphYO9bVwcJybZnCst:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea23feb371fd3045506758f3308ad9a66f9aceda/sql/table.go#L227)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> nit: tableID
</details>
Done.

---

*[sql/table.go, line 252 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7133#-KJpgRVcGtm2klyyVD60:-KJphY6TTBvg4__5ZPL4:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea23feb371fd3045506758f3308ad9a66f9aceda/sql/table.go#L252)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> s/name/id/
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7133)*

**Comment by andreimatei** [comment]
:lgtm:

So how are these leases used exactly? I wonder if it's important that a transaction continues using the same lease (as opposed to some (possibly new) lease every time, under the general lease constraint that there can only be 2 versions outstanding). Because if it's not, we could use the `LeaseManager` directly to get this lease, and not do any of the caching in the planner.

<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> :lgtm:
</details>


---

Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[sql/fk.go, line 45 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7133#-KJpgNLuIcc7J3dXnUda:-KJpgNLuIcc7J3dXnUdb:-1156443252) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea23feb371fd3045506758f3308ad9a66f9aceda/sql/fk.go#L45)):*
> ```Go
> // will be needed for FK checking delete and/or insert operations on `table`.
> //
> // NB: the returned map's values are *not* set -- higher level calling code, eg
> ```

I'd say if we really want to avoid an allocation for this slice, or for the ensuing map, use a sync.Pool? And then `FillFKTableMap` could return a map.

---

*[sql/table.go, line 226 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7133#-KJpfyd14iS9T9golRCg:-KJpfyd14iS9T9golRCh:-2122526562) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea23feb371fd3045506758f3308ad9a66f9aceda/sql/table.go#L226)):*
> ```Go
> }
> 
> // getTableLeaseByID
> ```

since you started the sentence... :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7133#-:-KJphN7CWA75l3ALuj_m:-1292950171)*

**Comment by dt** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[sql/fk.go, line 45 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7133#-KJpgNLuIcc7J3dXnUda:-KJpiAnklExOy1OxXUqn:1521979178) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea23feb371fd3045506758f3308ad9a66f9aceda/sql/fk.go#L45)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> I'd say if we really want to avoid an allocation for this slice, or for the ensuing map, use a sync.Pool? And then `FillFKTableMap` could return a map.
</details>
eh, I don't want to put a map of _leased_ things in a pool.

I just didn't want to pay a runtime penalty (alloc a slice of IDs here just to throw it away immediately at the planner) purely to enforce a package separation (the FK helpers will live in sqlbase and don't directly use a planner).

---

*[sql/table.go, line 226 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7133#-KJpfyd14iS9T9golRCg:-KJpjXEIMnBencz6-K2J:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea23feb371fd3045506758f3308ad9a66f9aceda/sql/table.go#L226)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> since you started the sentence... :)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7133)*

**Comment by dt** [comment]
Leases are used to read the other tables' indexes to ensure they do (not) contain particular values that are (not) referenced by foreign keys. I think we should go through the same leasing that any normal select would so I think it makes sense to use the planner's cache.

<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> :lgtm:
> 
> So how are these leases used exactly? I wonder if it's important that a transaction continues using the same lease (as opposed to some (possibly new) lease every time, under the general lease constraint that there can only be 2 versions outstanding). Because if it's not, we could use the `LeaseManager` directly to get this lease, and not do any of the caching in the planner.
</details>


---

Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7133#-:-KJpjb6WZCTfRxeYitxE:195434601)*

**Pull request merged**
