### PR TITLE
colexec: refactor and fix the template for projection operators

### LINKED ISSUE #40915: colexec: projections do not behave correctly when nulls are present
Currently, all the projections perform the operation on full vectors of values and then set nulls. However, when nulls are present this can lead to wrong side effects. For example, if we have an expression like `1 / NULL` and the "value" (which is garbage) corresponding to the `NULL` happens to be 0, we'll get a division by zero error instead of `NULL`.

The correct approach is to always check whether the value is `NULL` upfront, and only if it is not perform the operation.

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: fix a few typos in the projection ops template**

Release justification: Category 1: Non-production code changes.

**colexec: refactor the template for projection operators**

The old version of the template for projection operators was written
before we gained more familiarity with the templates in general, so
it was a huge single string. This commit refactor that huge single
string template into a newer version.

Besides giving us a benefit of taking a step towards unifying our
templates, this will allow us to customize the behavior when nulls
are present with a lot less effort.

Release justification: Category 1: Non-production code changes.

**colexec: fix handling of NULLs by projection operators**

Previously, the projection operators would always perform its operation
on the full vectors of values, and only after the fact would set the
nulls vector. However, this is incorrect since this can trigger wrong
side effects (like division by zero when the value is actually NULL).
Now this is fixed.

Release justification: Category 2: Bug fixes and low-risk updates to
new functionality.

Fixes: #40915.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Okay, I think it is RFAL.

For the second commit (the refactor) I compared the generated files, and they were the same (other than the fact that I've split them up).

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40927)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rafiss, @solongordon, and @yuzefovich)

___
*[pkg/sql/colexec/proj_const_ops_gen_tmpl.go, line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40927#-LpEEM3Y9jYYHxBiGaek:-LpEEM3Z2mqK6Mm7kYbn:b3yw6ij) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dc9082f6dae949ca30fd4f38157a0b6318727c6/pkg/sql/colexec/proj_const_ops_gen_tmpl.go#L21)):*
> ```Go
> 
> package colexec
> ```

file-level comment -- i don't think i entirely follow what this file is doing. i think i'm getting thrown off by the filename. we don't have any other files suffixed with `_gen_tmpl.go`. so maybe a different name makes more sense? or also, why can't all of this code just be moved to proj_const_ops_tmpl.go?
___
*[pkg/sql/colexec/proj_const_ops_gen_tmpl.go, line 69 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40927#-LpEEwI8BmnnoEyAX96u:-LpEEwI9D9SeiT3bNE7T:b-d7ajmf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dc9082f6dae949ca30fd4f38157a0b6318727c6/pkg/sql/colexec/proj_const_ops_gen_tmpl.go#L69)):*
> ```Go
> // The outer range is a coltypes.T (the left type). The middle range is also a
> // coltypes.T (the right type). The inner is the overloads associated with
> // those two types.
> ```

maybe the comment should explain what projConstOp is? since it's not really defined nearby in the code
___
*[pkg/sql/colexec/proj_const_ops_tmpl.go, line 99 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40927#-LpEHwRr9yg5x17rXXyn:-LpEHwRr9yg5x17rXXyo:b-8gem5t) ([raw file](https://github.com/cockroachdb/cockroach/blob/489cbc4b6320929c11df954933366c33d842224d/pkg/sql/colexec/proj_const_ops_tmpl.go#L99)):*
> ```Go
> 	projCol := projVec._RET_TYP()
> 	if vec.Nulls().MaybeHasNulls() {
> 		_SET_PROJECTION(true)
> ```

maybe comment the argument inline
___
*[pkg/sql/colexec/proj_const_ops_tmpl.go, line 113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40927#-LpEKKVy7fvmhRsMf45v:-LpEKKVzEop28gpnZTWs:b8bqtys) ([raw file](https://github.com/cockroachdb/cockroach/blob/489cbc4b6320929c11df954933366c33d842224d/pkg/sql/colexec/proj_const_ops_tmpl.go#L113)):*
> ```Go
> 
> // {{/*
> func _SET_PROJECTION(_HAS_NULLS bool) {
> ```

i wonder why this template function includes the loop in it. in other files what i've seen is:

```
if maybeHasNulls {
  if sel != nil {
    for _, i := range sel {
      _TEMPLATE_FUNC(...)
    }
  } else {
    for execgen.RANGE(i, col) {
      _TEMPLATE_FUNC(...)
    }
  }
} else {
  if sel != nil {
    for _, i := range sel {
      _TEMPLATE_FUNC(...)
    }
  } else {
    for execgen.RANGE(i, col) {
      _TEMPLATE_FUNC(...)
    }
  }
}
```

and this approach has slightly less code duplication
___
*[pkg/sql/colexec/proj_const_ops_tmpl.go, line 127 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40927#-LpEI2fK7Y8-Xe8MXkhj:-LpEI2fK7Y8-Xe8MXkhk:b-z2kfe6) ([raw file](https://github.com/cockroachdb/cockroach/blob/489cbc4b6320929c11df954933366c33d842224d/pkg/sql/colexec/proj_const_ops_tmpl.go#L127)):*
> ```Go
> 			// {{if _HAS_NULLS}}
> 			if colNulls.NullAt(i) {
> 				projColNulls.SetNull(i)
> ```

i don't know if it will be faster, but another option is to not do anything at all if the current val is null, and then after the loop keep the old logic:

```
// {{if _HAS_NULLS}}
nulls := vec.Nulls().Copy()
projVec.SetNulls(&nulls)
// {{end}}
```

(actually i'm not sure why the old code has the call to `Copy()`)
___
*[pkg/sql/colexec/utils_test.go, line 529 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40927#-LpEKkl760sRLwGCZcnd:-LpEKkl760sRLwGCZcne:b-59ed2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/489cbc4b6320929c11df954933366c33d842224d/pkg/sql/colexec/utils_test.go#L529)):*
> ```Go
> 			if tups[j][i] == nil || s.injectAllNulls || injectRandomNull {
> 				vec.Nulls().SetNull(outputIdx)
> 				if rng.Float64() < 0.5 {
> ```

ahhh i see now! i was wondering how this wasn't caught before. nice fix here

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40927)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rafiss, @solongordon, and @yuzefovich)

___
*[pkg/sql/colexec/proj_const_ops_gen_tmpl.go, line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40927#-LpEEM3Y9jYYHxBiGaek:-LpEX6A96A2QUzEGQryy:bpcfk5d) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dc9082f6dae949ca30fd4f38157a0b6318727c6/pkg/sql/colexec/proj_const_ops_gen_tmpl.go#L21)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

file-level comment -- i don't think i entirely follow what this file is doing. i think i'm getting thrown off by the filename. we don't have any other files suffixed with `_gen_tmpl.go`. so maybe a different name makes more sense? or also, why can't all of this code just be moved to proj_const_ops_tmpl.go?
</blockquote></details>

Good point, refactored into a single file. I think I was trying to gain more familiarity with reusing templates from the other files (namely, `like_ops_gen` uses `projConstOp` template), so I thought it would be a good idea to separate it out. Then I was having some issues with duplicated structs when I was trying to actually generate the projection operators with constants. Anyway, I don't see a reason for having a separate file now.
___
*[pkg/sql/colexec/proj_const_ops_gen_tmpl.go, line 69 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40927#-LpEEwI8BmnnoEyAX96u:-LpEXcgB87jBdrCafMZ9:b54g1ch) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dc9082f6dae949ca30fd4f38157a0b6318727c6/pkg/sql/colexec/proj_const_ops_gen_tmpl.go#L69)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

maybe the comment should explain what projConstOp is? since it's not really defined nearby in the code
</blockquote></details>

I think the removal of a separate file addresses this comment.
___
*[pkg/sql/colexec/proj_const_ops_tmpl.go, line 99 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40927#-LpEHwRr9yg5x17rXXyn:-LpEYr2_2W4FUa-P19Zx:bd0tmma) ([raw file](https://github.com/cockroachdb/cockroach/blob/489cbc4b6320929c11df954933366c33d842224d/pkg/sql/colexec/proj_const_ops_tmpl.go#L99)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

maybe comment the argument inline
</blockquote></details>

Unfortunately, it's not possible to have something like `_SET_PROJECTION(true /* hasNulls */)` because this will be replaced by a template function, and the `/* hasNulls */` part will be attempted to be put as the argument in there. I could leave comment above, but I think the function is defined very close by, so it wouldn't be worth it.
___
*[pkg/sql/colexec/proj_const_ops_tmpl.go, line 113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40927#-LpEKKVy7fvmhRsMf45v:-LpEcCah2xIFnJ_F_m07:bspb7pp) ([raw file](https://github.com/cockroachdb/cockroach/blob/489cbc4b6320929c11df954933366c33d842224d/pkg/sql/colexec/proj_const_ops_tmpl.go#L113)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i wonder why this template function includes the loop in it. in other files what i've seen is:

```
if maybeHasNulls {
  if sel != nil {
    for _, i := range sel {
      _TEMPLATE_FUNC(...)
    }
  } else {
    for execgen.RANGE(i, col) {
      _TEMPLATE_FUNC(...)
    }
  }
} else {
  if sel != nil {
    for _, i := range sel {
      _TEMPLATE_FUNC(...)
    }
  } else {
    for execgen.RANGE(i, col) {
      _TEMPLATE_FUNC(...)
    }
  }
}
```

and this approach has slightly less code duplication
</blockquote></details>

Thanks! I agree, that was an opportunity to extract another function. Done.
___
*[pkg/sql/colexec/proj_const_ops_tmpl.go, line 127 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40927#-LpEI2fK7Y8-Xe8MXkhj:-LpEf8Nn0Oj7YtxlmjPu:b-alp762) ([raw file](https://github.com/cockroachdb/cockroach/blob/489cbc4b6320929c11df954933366c33d842224d/pkg/sql/colexec/proj_const_ops_tmpl.go#L127)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i don't know if it will be faster, but another option is to not do anything at all if the current val is null, and then after the loop keep the old logic:

```
// {{if _HAS_NULLS}}
nulls := vec.Nulls().Copy()
projVec.SetNulls(&nulls)
// {{end}}
```

(actually i'm not sure why the old code has the call to `Copy()`)
</blockquote></details>

Good point, I think it'll be faster, done. The reason we need to `Copy()` is that if we don't, then modification of one nulls vector will be reflected on the other one (which is actually the same memory), but it shouldn't.

**Review by rafiss — APPROVED** [review]
LGTM especially since you verified that the code is the same! (before adding the null handling)

definitely not needed for this PR, but I just thought of another case where this operator does not handle nulls correctly. i'm not sure how important it is but it is possible for the constArg to be NULL as well. e.g. `SELECT k + null FROM foo;` should return all nulls.

luckily the bug doesn't show up because the vectorized engine also is not able to plan queries like that:

```
> select k + null from kv;
pq: unable to vectorize execution plan: unable to columnarize render expression "NULL": cannot plan null type unknown
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40927#-:-LpUijV-27RM_wGhyCfs:b-swfgjd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rafiss, @solongordon, and @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
Indeed, good catch with `NULL` value. We actually don't support projection operator in such a case at all - the template assumes that `constArg` is of "Go Type", so we will need to modify the template struct a little to support `NULL` constant argument. It doesn't seem important to me right now because all such cases will be rejected, so I opened up an issue for this problem.

Thanks for the review!

bors r=rafiss

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40927#-:-LpV3eA8Ad6Cde3lS3KE:b9j4ki0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rafiss, @solongordon, and @yuzefovich)

**Pull request merged**
