### PR TITLE
sql: implement WITH RECURSIVE with UNION

### LINKED ISSUE #46642: sql: UNION variant of WITH RECURSIVE not implemented
Postgres supports two forms of RECURSIVE WITH: using either UNION or UNION ALL. Other databases (like SQL Server) only implement UNION ALL.

CockroachDB currently only implements UNION ALL. If you are a user of CockroachDB who needs to use this variant, please post in this issue and provide more details on the usecase.

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: implement WITH RECURSIVE with UNION

This change implements the UNION variant of WITH RECURSIVE, where rows
are deduplicated. We achieve this by storing all rows in a
deduplicating container and inserting in that container first,
detecting if the row is a duplicate.

Fixes #46642.

Release note (sql change): The WITH RECURSIVE variant that uses UNION
(as opposed to UNION ALL) is now supported.

#### sql: capitalize rowContainerHelper API

This change capitalizes the API of `rowContainerHelper` and
`rowContainerIterator` to make it more clear what functions are not
internal to the structure.

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
Nice work! I only have nits, so :lgtm:

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71685#-:-MmQF5rFBADy_AbTJuPH:bn994ft)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/apply_join.go, line 254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71685#-MmQCHD45MlewOf4kgu0:-MmQCHD45MlewOf4kgu1:b-2sarx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a1f644aa63dcb090867c95cd5ae8c751f4f58c2/pkg/sql/apply_join.go#L254)):*
> ```Go
> }
> 
> // runPlanInsidePlan is used to run a plan and gather the results in a row
> ```

nit: the comment should now mention the resultWriter.
___
*[pkg/sql/buffer_util.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71685#-MmQCfaJDXjTPnpDd-h2:-MmQCfaJDXjTPnpDd-h3:b-n8t4dg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a1f644aa63dcb090867c95cd5ae8c751f4f58c2/pkg/sql/buffer_util.go#L37)):*
> ```Go
> }
> 
> func (c *rowContainerHelper) init(
> ```

nit: do you think it'd be cleaner to keep the signature of `init` unchanged but to introduce `initWithDeduplication` that would take the new argument and `init` would call it passing in `false`?
___
*[pkg/sql/buffer_util.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71685#-MmQDWjV3e2vtjGoRibn:-MmQDWjV3e2vtjGoRibo:b-viv5yq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a1f644aa63dcb090867c95cd5ae8c751f4f58c2/pkg/sql/buffer_util.go#L75)):*
> ```Go
> }
> 
> // addRowWithDedup adds a given row if not already present in the container.
> ```

super nit: I think `s/a given row/the given row/`.
___
*[pkg/sql/buffer_util.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71685#-MmQELvL-BFp01aQY3Wf:-MmQELvL-BFp01aQY3Wg:b962eqr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a1f644aa63dcb090867c95cd5ae8c751f4f58c2/pkg/sql/buffer_util.go#L79)):*
> ```Go
> func (c *rowContainerHelper) addRowWithDedup(
> 	ctx context.Context, row tree.Datums,
> ) (ok bool, _ error) {
> ```

super nit: maybe do `s/ok/added/` to be more explicit about the meaning of the boolean?
___
*[pkg/sql/recursive_cte.go, line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71685#-MmQDyVl9TRzmkMzkbsN:-MmQDyVl9TRzmkMzkbsO:b-ez8nuc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a1f644aa63dcb090867c95cd5ae8c751f4f58c2/pkg/sql/recursive_cte.go#L179)):*
> ```Go
> //
> // If we are deduplicating, each row is either discarded if it has a duplicate
> // in the allRows container or added to both alRows and workingRows otherwise.
> ```

nit: `s/alRows/allRows/`.
___
*[pkg/sql/opt/exec/factory.opt, line 693 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71685#-MmQEmgk7IN6zDQ-Mbdf:-MmQEmgk7IN6zDQ-Mbdg:bz6ul0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a1f644aa63dcb090867c95cd5ae8c751f4f58c2/pkg/sql/opt/exec/factory.opt#L693)):*
> ```
> #     - the plan is executed; the results are emitted and also saved in a new
> #       buffer for the next iteration. If Deduplicate is true, only rows that
> #       haven't been returned yet are saved.
> ```

nit: maybe `s/are saved/are returned and saved/`.
___
*[pkg/sql/opt/optbuilder/with.go, line 237 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71685#-MmQEvguAhQ-yDtMXm_O:-MmQEvguAhQ-yDtMXm_P:b-hox69d) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a1f644aa63dcb090867c95cd5ae8c751f4f58c2/pkg/sql/opt/optbuilder/with.go#L237)):*
> ```Go
> 
> 	initial, recursive, isUnionAll, ok := b.splitRecursiveCTE(cte.Stmt)
> 	// We don't currently support the UNION form (only UNION ALL).
> ```

nit: needs an update.

**Review by jordanlewis — COMMENTED** [review]
Awesome!! It would be nice to include the variant in ordinary `EXPLAIN` as well, unless I'm missing something this will still just say `recursive-cte` and not include the detail about `UNION` vs `UNION ALL`.

**Review by RaduBerinde — COMMENTED** [review]
TFTRs! Added a field to EXPLAIN VERBOSE.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71685#-:-MmQdaRV-vHe1n9mpiik:bbd4am0)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @yuzefovich)

___
*[pkg/sql/buffer_util.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71685#-MmQCfaJDXjTPnpDd-h2:-MmQifFd1BMxr7_Dl_lN:b-fi87u4) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a1f644aa63dcb090867c95cd5ae8c751f4f58c2/pkg/sql/buffer_util.go#L37)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: do you think it'd be cleaner to keep the signature of `init` unchanged but to introduce `initWithDeduplication` that would take the new argument and `init` would call it passing in `false`?
</blockquote></details>

Done. I also added a commit that capitalizes the API.
___
*[pkg/sql/buffer_util.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71685#-MmQDWjV3e2vtjGoRibn:-MmQeupY6xYkIgLgYuqO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a1f644aa63dcb090867c95cd5ae8c751f4f58c2/pkg/sql/buffer_util.go#L75)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

super nit: I think `s/a given row/the given row/`.
</blockquote></details>

Done.
___
*[pkg/sql/buffer_util.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71685#-MmQELvL-BFp01aQY3Wf:-MmQewgwESxFfM6Sy-ZP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a1f644aa63dcb090867c95cd5ae8c751f4f58c2/pkg/sql/buffer_util.go#L79)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

super nit: maybe do `s/ok/added/` to be more explicit about the meaning of the boolean?
</blockquote></details>

Done.

**Review by mgartner — APPROVED** [review]
:lgtm: 

nit: the second commit is missing from the PR description

> Reviewed 7 of 15 files at r1, 10 of 10 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71685#-:-MmSwnzgB2HEeeejVCPJ:b-5856j5)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/buffer_util.go, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71685#-MmSyZS6EqDMUdd_d3di:-MmSyZS75yo9UuSZpymx:b-s85551) ([raw file](https://github.com/cockroachdb/cockroach/blob/42c009fe7c5eda483b32b8cebfb25f1f0ee7c9e9/pkg/sql/buffer_util.go#L64)):*
> ```Go
> 	}
> 	c.rows.Init(
> 		ordering, typs, &evalContext.EvalContext,
> ```

Does DoDeDuplicate require a non-empty ordering? It's unclear in the comments for DiskBackedRowContainer.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71685)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @yuzefovich)

___
*[pkg/sql/buffer_util.go, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71685#-MmSyZS6EqDMUdd_d3di:-MmU-53GBTb7brbFROnP:b-nmep12) ([raw file](https://github.com/cockroachdb/cockroach/blob/42c009fe7c5eda483b32b8cebfb25f1f0ee7c9e9/pkg/sql/buffer_util.go#L64)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Does DoDeDuplicate require a non-empty ordering? It's unclear in the comments for DiskBackedRowContainer.
</blockquote></details>

AFAICT it deduplicates on the columns in the ordering

**Review by mgartner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71685)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/buffer_util.go, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71685#-MmSyZS6EqDMUdd_d3di:-MmU0ABNE1Dt-N5lgI7V:b-5jigyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/42c009fe7c5eda483b32b8cebfb25f1f0ee7c9e9/pkg/sql/buffer_util.go#L64)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

AFAICT it deduplicates on the columns in the ordering
</blockquote></details>

I see. Maybe add a comment here to explain that?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71685)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @yuzefovich)

___
*[pkg/sql/buffer_util.go, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71685#-MmSyZS6EqDMUdd_d3di:-MmUQium8zVbieRun_oQ:b-ygdbf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/42c009fe7c5eda483b32b8cebfb25f1f0ee7c9e9/pkg/sql/buffer_util.go#L64)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I see. Maybe add a comment here to explain that?
</blockquote></details>

Done, also added to `DoDeDuplicate`.

**Review by mgartner — APPROVED** [review]
> Reviewed 8 of 8 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71685)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @yuzefovich)

___
*[pkg/sql/buffer_util.go, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71685#-MmSyZS6EqDMUdd_d3di:-MmV1iXaCLUCP_63HKE8:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/42c009fe7c5eda483b32b8cebfb25f1f0ee7c9e9/pkg/sql/buffer_util.go#L64)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Done, also added to `DoDeDuplicate`.
</blockquote></details>

Thanks!

**Pull request merged**
