### PR TITLE
kv/kvserver: use storage/fs.FS.CreateWithSync

### LINKED ISSUE #50844: storage: Have rocksdbWritableFile sync regularly when created with CreateWithSync
When a pebble File is created with `CreateWithSync`, it creates a `syncingFile` which syncs after every `bytesPerSync` bytes are written using the `sync_file_range` or similar system calls. Files created the same way using RocksDB should have the same behaviour.

Once this is done, instances of `SSTSnapshotStorageFile` can start using files created with `CreateWithSync` instead of handling syncing itself.

### PR DESCRIPTION
**Pull request by petermattis**
Replace the `SSTSnapshotStorageFile.syncSize` mechanism with
`storage/fs.FS.CreateWithSync`. The latter uses `sync_file_range` to
asynchronously perform the periodic sync on both RocksDB and Pebble.

Fixes #50844

Release note (performance improvement): Smooth out disk writes when
transferring Range snapshots in order to avoid latency spikes for other
concurrent operations.

### CODE REVIEW

**Comment by petermattis** [comment]
Turns out `RocksDB.CreateWithSync` was already doing the right thing with the `bytesPerSync` parameter.

**Review by itsbilal — APPROVED** [review]
:lgtm:

Should this be backported to 20.1? It's a more streamlined solution than the previous one.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50866#-:-MB9X6UP2Z5pa9IkHhim:b-v7cb3i)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by petermattis** [comment]
TFTR!

> Should this be backported to 20.1? It's a more streamlined solution than the previous one.

I'm not sure. There was no actual bug in the previous code. And whatever perf improvement there is from this will likely be small. I'm inclined to not backport it. @nvanbenschoten ?

bors r+

**Comment by petermattis** [comment]
CI flaked on https://github.com/cockroachdb/cockroach/issues/50386

bors r+

**Review by nvb — COMMENTED** [review]
:lgtm_strong: 

I agree about not backporting this.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50866#-:-MBA8atK1LnncitO5G-P:b-8o37o4)* status: :shipit: complete! 2 of 0 LGTMs obtained

**Pull request merged**
