### PR TITLE
rfc: algebraic data types in Go

### PR DESCRIPTION
**Pull request by eisenstatdavid**
ADTs are the underpinning of the intermediate representation that we
plan to roll out, to improve the performance of expression serialization
and to support correlated subqueries and advanced query optimizations.

### CODE REVIEW

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/algebraic_data_types.md, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16240#-KlWVUPUsMxYo9KR6HmE:-KlWVUPVtuE48ISmV9b0:b1oaws2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f4b352cfec79a3fff2372570f2e5a28510c3d3/docs/RFCS/algebraic_data_types.md#L1)):*
> ```Markdown
> RFC: Go infrastructure for algebraic data types
> ```

Please include the same header as the other RFCs. 

---

*[docs/RFCS/algebraic_data_types.md, line 17 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16240#-KlWVgdrmqStnX7HkJOX:-KlWVgdrmqStnX7HkJOY:b-z81hxt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f4b352cfec79a3fff2372570f2e5a28510c3d3/docs/RFCS/algebraic_data_types.md#L17)):*
> ```Markdown
> -------
> 
> Note: this document is a literate Go program. Here is the program
> ```

How does one run this? Move the instructions from the middle to here (or to the end and mention where to look here)

---

*[docs/RFCS/algebraic_data_types.md, line 89 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16240#-KlWW6AT629nCdOa4XPY:-KlWW6AT629nCdOa4XPZ:by7fngx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f4b352cfec79a3fff2372570f2e5a28510c3d3/docs/RFCS/algebraic_data_types.md#L89)):*
> ```Markdown
> Functions that create new ADT references will need to take the allocator
> as an explicit argument. To partially address this need, we will add an
> allocator field to the existing context.
> ```

We have a lot of types named "context". Which one is this?

---

*[docs/RFCS/algebraic_data_types.md, line 91 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16240#-KlWWJI8W-z_mDetvSQY:-KlWWJI8W-z_mDetvSQZ:b-x663qm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f4b352cfec79a3fff2372570f2e5a28510c3d3/docs/RFCS/algebraic_data_types.md#L91)):*
> ```Markdown
> allocator field to the existing context.
> 
> ADT nodes will be serializable to and deserializable from protocol
> ```

What are the version compatibility requirements for this serialization? Do we need to be able to load old serialized nodes from disk? Do we send them over the network in such a way that we need to support the formats used by adjacent versions?

---

*[docs/RFCS/algebraic_data_types.md, line 101 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16240#-KlWaLi8mvw76jFaNnBC:-KlWaLi8mvw76jFaNnBD:bu9f6bv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f4b352cfec79a3fff2372570f2e5a28510c3d3/docs/RFCS/algebraic_data_types.md#L101)):*
> ```Markdown
> algebraic data type. These Go types define several methods: access,
> mutate, walk, serialize, and format. To allow safe aliasing, the
> reference type provides no mutators. Instead, there are methods to dump
> ```

A value type that contains (say) a `[]byte` allows the slice to be mutated. Is that just a hole in the type safety that we'll have to live with?

---

*[docs/RFCS/algebraic_data_types.md, line 281 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16240#-KlWbYHq_fu3-F_mmR0C:-KlWbYHrgs4YFmSiBqNV:b-eleu6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f4b352cfec79a3fff2372570f2e5a28510c3d3/docs/RFCS/algebraic_data_types.md#L281)):*
> ```Markdown
> ### One common Go type for all ADT nodes with all possible attributes
> 
> Pro: bulk allocations. Con: space overhead (!).
> ```

Do we have any guess about how big this might get?

---

*[docs/RFCS/algebraic_data_types.md, line 347 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16240#-KlW_aMpGE4IMkwsLjo3:-KlW_aMpGE4IMkwsLjo4:b-wxzqi2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f4b352cfec79a3fff2372570f2e5a28510c3d3/docs/RFCS/algebraic_data_types.md#L347)):*
> ```Markdown
> 
> Accordingly, we allocate a slice of `unsafe.Pointer`s and another slice
> of `int64`s. We split ADT objects into pointer and non-pointer fields
> ```

Just pointers and int64s? We can fit a `double` into an `int64` but slices are trickier. Would we decompose a slice into a pointer and two ints? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16240)*

**Comment by eisenstatdavid** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/algebraic_data_types.md, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16240#-KlWVUPUsMxYo9KR6HmE:-KlZcZ5yUhBC10_lf4s4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f4b352cfec79a3fff2372570f2e5a28510c3d3/docs/RFCS/algebraic_data_types.md#L1)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Please include the same header as the other RFCs. 
</blockquote></details>

Done.

---

*[docs/RFCS/algebraic_data_types.md, line 17 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16240#-KlWVgdrmqStnX7HkJOX:-KlZcZiLd58MrecsjFJL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f4b352cfec79a3fff2372570f2e5a28510c3d3/docs/RFCS/algebraic_data_types.md#L17)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

How does one run this? Move the instructions from the middle to here (or to the end and mention where to look here)
</blockquote></details>

Done.

---

*[docs/RFCS/algebraic_data_types.md, line 89 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16240#-KlWW6AT629nCdOa4XPY:-KlZh3oAny10rvJzsc45:b3pq2yz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f4b352cfec79a3fff2372570f2e5a28510c3d3/docs/RFCS/algebraic_data_types.md#L89)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

We have a lot of types named "context". Which one is this?
</blockquote></details>

Whichever ones are single-threaded and need an ADT allocator.

---

*[docs/RFCS/algebraic_data_types.md, line 91 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16240#-KlWWJI8W-z_mDetvSQY:-KlZgCq9tpbi9_p64Jdp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f4b352cfec79a3fff2372570f2e5a28510c3d3/docs/RFCS/algebraic_data_types.md#L91)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

What are the version compatibility requirements for this serialization? Do we need to be able to load old serialized nodes from disk? Do we send them over the network in such a way that we need to support the formats used by adjacent versions?
</blockquote></details>

Done.

---

*[docs/RFCS/algebraic_data_types.md, line 101 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16240#-KlWaLi8mvw76jFaNnBC:-KlZfL5ytMTnqET2bDfM:brz632) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f4b352cfec79a3fff2372570f2e5a28510c3d3/docs/RFCS/algebraic_data_types.md#L101)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

A value type that contains (say) a `[]byte` allows the slice to be mutated. Is that just a hole in the type safety that we'll have to live with?
</blockquote></details>

Yes, there will be a hole.

---

*[docs/RFCS/algebraic_data_types.md, line 281 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16240#-KlWbYHq_fu3-F_mmR0C:-KlZfclpvRvKlzgKSm-4:b5efyds) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f4b352cfec79a3fff2372570f2e5a28510c3d3/docs/RFCS/algebraic_data_types.md#L281)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Do we have any guess about how big this might get?
</blockquote></details>

Only a SWAG of 250--300 bytes based on the current max topping out a bit below 200. The small nodes are more like 40 or 48.

---

*[docs/RFCS/algebraic_data_types.md, line 347 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16240#-KlW_aMpGE4IMkwsLjo3:-KlZfMyiQakSlYlno3PI:b-w1f43e) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f4b352cfec79a3fff2372570f2e5a28510c3d3/docs/RFCS/algebraic_data_types.md#L347)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Just pointers and int64s? We can fit a `double` into an `int64` but slices are trickier. Would we decompose a slice into a pointer and two ints? 
</blockquote></details>

For better or worse, that would be the plan.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16240)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/algebraic_data_types.md, line 256 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16240#-Kl_UcWQNljeO7eaaRZx:-Kl_UcWQNljeO7eaaRZy:bfgvid8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f4b352cfec79a3fff2372570f2e5a28510c3d3/docs/RFCS/algebraic_data_types.md#L256)):*
> ```Markdown
> 
> Pro: conventional. Con: allocation overhead – we must either allocate
> numerous slices or rely on Go’s allocator.
> ```

We could have a small family of allocators for a few common sizes (e.g. 48, 128, max_size) which allocates a slice for multiple objects at a time, no?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16240)*

**Comment by eisenstatdavid** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[docs/RFCS/algebraic_data_types.md, line 256 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16240#-Kl_UcWQNljeO7eaaRZx:-Klt2IGVFlj-Ome0dEWB:b-70m4tx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f4b352cfec79a3fff2372570f2e5a28510c3d3/docs/RFCS/algebraic_data_types.md#L256)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We could have a small family of allocators for a few common sizes (e.g. 48, 128, max_size) which allocates a slice for multiple objects at a time, no?
</blockquote></details>

We could. We won't have the data to understand the tradeoffs until we build something, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16240)*

**Pull request merged**
