### PR TITLE
sql: fix race condition on audit logging CCL hook

### LINKED ISSUE #104660: sql: TestQueryCache failed with data race
sql.TestQueryCache [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/10467697?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/10467697?buildTab=artifacts#/) on release-23.1 @ [2d33fa6b041ba0a7b362358c9b69fcabe005edba](https://github.com/cockroachdb/cockroach/commits/2d33fa6b041ba0a7b362358c9b69fcabe005edba):

```
      GOROOT/src/testing/testing.go:1493 +0x75d
  github.com/cockroachdb/cockroach/pkg/sql.TestQueryCache.func1()
      github.com/cockroachdb/cockroach/pkg/sql/plan_opt_test.go:342 +0x144
  testing.tRunner()
      GOROOT/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      GOROOT/src/testing/testing.go:1493 +0x47

Goroutine 1281579 (running) created at:
  testing.(*T).Run()
      GOROOT/src/testing/testing.go:1493 +0x75d
  github.com/cockroachdb/cockroach/pkg/sql.TestQueryCache.func1()
      github.com/cockroachdb/cockroach/pkg/sql/plan_opt_test.go:161 +0x84
  testing.tRunner()
      GOROOT/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      GOROOT/src/testing/testing.go:1493 +0x47
==================
=== RUN   TestQueryCache/group/schemachange-parallel
=== PAUSE TestQueryCache/group/schemachange-parallel
=== RUN   TestQueryCache/group/simple-prepare-with-args
=== PAUSE TestQueryCache/group/simple-prepare-with-args
=== CONT  TestQueryCache/group/simple-prepare-with-args
=== RUN   TestQueryCache/group/statschange
=== PAUSE TestQueryCache/group/statschange
=== RUN   TestQueryCache/group
=== RUN   TestQueryCache/group/multidb-prepare
=== PAUSE TestQueryCache/group/multidb-prepare
=== RUN   TestQueryCache/group/parallel
=== PAUSE TestQueryCache/group/parallel
=== CONT  TestQueryCache/group/parallel
=== RUN   TestQueryCache/group/relative-timestamp
=== PAUSE TestQueryCache/group/relative-timestamp
=== CONT  TestQueryCache/group/relative-timestamp
=== RUN   TestQueryCache/group/simple
=== PAUSE TestQueryCache/group/simple
=== RUN   TestQueryCache/group/schemachange-prepare
=== PAUSE TestQueryCache/group/schemachange-prepare
=== CONT  TestQueryCache/group/schemachange-prepare
=== RUN   TestQueryCache/group/simple-prepare
=== PAUSE TestQueryCache/group/simple-prepare
=== CONT  TestQueryCache/group/simple-prepare
=== RUN   TestQueryCache/group/exec-and-prepare
=== PAUSE TestQueryCache/group/exec-and-prepare
=== RUN   TestQueryCache/group/multidb
=== PAUSE TestQueryCache/group/multidb
=== CONT  TestQueryCache/group/multidb
=== RUN   TestQueryCache/group/parallel-prepare
=== PAUSE TestQueryCache/group/parallel-prepare
=== CONT  TestQueryCache/group/parallel-prepare
```
<p>Parameters: <code>TAGS=bazel,gss,race</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestQueryCache.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-28658

### PR DESCRIPTION
**Pull request by THardy98**
Fixes: https://github.com/cockroachdb/cockroach/issues/104660, #104838

This change fixes a race condition that can occur when multiple
SQLServers are created simultaneously, causing simultaneous writes to an
unprotected global variable used to configure a CCL audit logging
feature.

This change removes the global variable and instead invokes the hook to
check enterprise status at log time.

Release note (bug fix): This change fixes a race  condition that
can occur when multiple SQLServers are created simultaneously, causing
simultaneous writes to an unprotected global variable used to configure
a CCL audit logging feature.

### CODE REVIEW

**Review by knz — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105227)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @THardy98)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105227#-NYT2iF14ENB9d4juCaa):*
Don't forget to make the PR description reflect the release note.
___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105227#-NYT2eZj82fjSd6dAH_n):*
Something is off with your URLs and issue/epic references here. They seem totally unrelated.
___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105227#-NYT2l126EOpjIz6pG5f):*
Something very wrong happened with these release notes.
___
*[`pkg/server/server_sql.go` line 1385 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105227#-NYT32ykEfGozSe1UjPh:-NYT32ykEfGozSe1UjPi:b-ld2fea) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfa79e780d01bec203706c7c038fb06c781db88b/pkg/server/server_sql.go#L1385)):*
> ```Go
> 	initialized, _ := auditlogging.ReadEnterpriseParamsHook()
> 	if !initialized {
> 		auditlogging.WriteEnterpriseParamsHook(ctx, base.CheckEnterpriseEnabled(execCfg.Settings, cfg.ClusterIDContainer.Get(), "role-based auditing"))
> ```

This way of capturing the settings and the cluster ID container is _very_ "not OK".

The only dependency you can preserve in a global variable is a reference to the function `base.CheckEnterpriseEnabled`.  Everything else needs to be passed as argument to `validateAuditLogConfig`.

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105227)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105227#-NYT2iF14ENB9d4juCaa):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Don't forget to make the PR description reflect the release note.
</blockquote></details>

Done.
___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105227#-NYT2eZj82fjSd6dAH_n):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Something is off with your URLs and issue/epic references here. They seem totally unrelated.
</blockquote></details>

Fixed.
___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105227#-NYT2l126EOpjIz6pG5f):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Something very wrong happened with these release notes.
</blockquote></details>

Fixed.
___
*[`pkg/server/server_sql.go` line 1385 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105227#-NYT32ykEfGozSe1UjPh:-NYTJ0a05HqP7tEhaLVK:bdia7qc) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfa79e780d01bec203706c7c038fb06c781db88b/pkg/server/server_sql.go#L1385)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

This way of capturing the settings and the cluster ID container is _very_ "not OK".

The only dependency you can preserve in a global variable is a reference to the function `base.CheckEnterpriseEnabled`.  Everything else needs to be passed as argument to `validateAuditLogConfig`.
</blockquote></details>

It's difficult to pass arguments to `validateAuditLogConfig` as the cluster setting validation function has an expected signature of: `(st *settings.Values, input string) error`, and doesn't have the necessary arguments to call `CheckEnterpriseEnabled`. I'm not sure how to pass server state into a cluster setting's validation function aside from a hook like this.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105227)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @THardy98)

___
*[`pkg/server/server_sql.go` line 1385 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105227#-NYT32ykEfGozSe1UjPh:-NYTKCPE2LWH07BwKcl0:b-nt2n2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfa79e780d01bec203706c7c038fb06c781db88b/pkg/server/server_sql.go#L1385)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

It's difficult to pass arguments to `validateAuditLogConfig` as the cluster setting validation function has an expected signature of: `(st *settings.Values, input string) error`, and doesn't have the necessary arguments to call `CheckEnterpriseEnabled`. I'm not sure how to pass server state into a cluster setting's validation function aside from a hook like this.
</blockquote></details>

This should teach you that `validateAuditLogConfig` is not the right place to do an enterprise check.

Generally, we do not do license checks on cluster settings. This is undesirable anyway; what would it mean if the value is set properly, and then the enterprise license expires? We want the feature to be disabled in that case.

The proper approach wrt license check is to do it in the SQL session. Either once when the session is opened or when we actually need to do audit logging, when/if the log config is non-empty.

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105227)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/server/server_sql.go` line 1385 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105227#-NYT32ykEfGozSe1UjPh:-NYTL7WyCiIuD3FlHahR:b-jv7qbh) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfa79e780d01bec203706c7c038fb06c781db88b/pkg/server/server_sql.go#L1385)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

This should teach you that `validateAuditLogConfig` is not the right place to do an enterprise check.

Generally, we do not do license checks on cluster settings. This is undesirable anyway; what would it mean if the value is set properly, and then the enterprise license expires? We want the feature to be disabled in that case.

The proper approach wrt license check is to do it in the SQL session. Either once when the session is opened or when we actually need to do audit logging, when/if the log config is non-empty.
</blockquote></details>

I had thought about doing the enterprise check elsewhere, but doesn't it seem odd to allow users to change the cluster setting value even if they can't use its underlying feature?

**Comment by knz** [comment]
> doesn't it seem odd to allow users to change the cluster setting value even if they can't use its underlying feature?

We have precedent: using kerberos authentication in the HBA config.

**Review by knz — COMMENTED** [review]
Thanks, this is better. LGTM with nit.

> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105227#-:-NYbnD0o-72Qj42nDcoN:b-6v4q3p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @THardy98)

___
*[`pkg/sql/audit_logging.go` line 122 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/105227#-NYbn-H12KnCdJyoWCVr:-NYbn-H26k76iQO2abI3:b-rcxg13) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1afd6c845b82e5351f3514d96deedb71e05c3b/pkg/sql/audit_logging.go#L122)):*
> ```Go
> 	// Do not emit audit events for reserved users/roles. This does not omit the root user.
> 	// Do not emit audit events for internal planners.
> 	return auditlogging.UserAuditEnabled(p.execCfg.Settings, p.EvalContext().ClusterID) || p.User().IsReserved() || p.isInternalPlanner
> ```

nit: consider checking whether the audit log config is empty first and take a shortcut. The enterprise license check is comparatively more expensive.

**Comment by THardy98** [comment]
I'm having a lot of trouble trying to determine the cause of https://github.com/cockroachdb/cockroach/issues/105174.

It seems difficult to reproduce, running `./dev test pkg/sql -f TestQueryCache --stress -- --define gotags=bazel,gss,deadlock` locally and on gceworker doesn't reproduce reliably (I sometimes add `--stress-args='-p=4'` to not blow up my/gceworker machine, not sure if that has a huge impact on reproducability).

It often produces:
`0 runs so far, 0 failures, over <'x' amount of time>`
but very rarely:
`POTENTIAL DEADLOCK: ...`

even when running for over 30mins.

I've tried running the above on commits prior to the introduction of any audit logging logic (I'm not certain if the CCL commit tagged in the issue is the cause of the deadlock, I wanted to `bisect` without much success) and seem to get the same result (sometimes runs will complete, sometimes not).

As such, this PR will only address the race condition bug. I'll mention this on the deadlock issue as well.

**Comment by knz** [comment]
> I'm having a lot of trouble trying to determine the cause of https://github.com/cockroachdb/cockroach/issues/105174.

It's mildly possible that the race condition (the issue you're fixing here) is a different issue from the deadlock. So I would be OK merging this (and closing the race condition issue) while keeping the deadlock issue investigation separate.

**Comment by THardy98** [comment]
Coming across another data race:
`/dev test pkg/server -f TestAdminAPITableStats --stress --stress-args='-p=6' --race`

Stack trace:
```
==================
WARNING: DATA RACE
Write at 0x00c019613f28 by goroutine 37415:
  internal/reflectlite.Swapper.func3()
      GOROOT/src/internal/reflectlite/swapper.go:42 +0xf2
  sort.insertionSort_func()
      GOROOT/src/sort/zsortfunc.go:13 +0x94
  sort.pdqsort_func()
      GOROOT/src/sort/zsortfunc.go:73 +0x3cb
  sort.Slice()
      GOROOT/src/sort/slice.go:23 +0xc4
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvflowcontrol/kvflowhandle.(*Handle).connectStreamLocked()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle.go:238 +0x3ca
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvflowcontrol/kvflowhandle.(*Handle).ConnectStream()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle.go:228 +0x1a4
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaFlowControlIntegrationImpl).tryReconnect()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/flow_control_replica_integration.go:423 +0x518
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaFlowControlIntegrationImpl).refreshStreams()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/flow_control_replica_integration.go:289 +0x84
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaFlowControlIntegrationImpl).onRaftTicked()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/flow_control_replica_integration.go:257 +0x8b
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).updateProposalQuotaRaftMuLocked()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal_quota.go:268 +0xe7c
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1213 +0x2344
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:814 +0x20f
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:646 +0x1cf
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:418 +0x2f5
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:321 +0x9a
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:484 +0x1f6

Previous read at 0x00c019613f28 by goroutine 1882489:
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvflowcontrol/kvflowhandle.(*Handle).Admit()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle.go:110 +0x2a4
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvadmission.(*controllerImpl).AdmitKVWork()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvadmission/kvadmission.go:310 +0x5ec
  github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal()
      github.com/cockroachdb/cockroach/pkg/server/node.go:1267 +0x4ac
  github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch()
      github.com/cockroachdb/cockroach/pkg/server/node.go:1463 +0x3bd
  github.com/cockroachdb/cockroach/pkg/kv/kvpb._Internal_Batch_Handler.func1()
      github.com/cockroachdb/cockroach/pkg/kv/kvpb/bazel-out/k8-fastbuild/bin/pkg/kv/kvpb/kvpb_go_proto_/github.com/cockroachdb/cockroach/pkg/kv/kvpb/api.pb.go:10059 +0x88
  github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor.ServerInterceptor.func1()
      github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:96 +0x1d4
  google.golang.org/grpc.chainUnaryInterceptors.func1.1()
      google.golang.org/grpc/external/org_golang_google_grpc/server.go:1162 +0x125
  github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func3()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:166 +0xf8
  google.golang.org/grpc.chainUnaryInterceptors.func1.1()
      google.golang.org/grpc/external/org_golang_google_grpc/server.go:1165 +0x22a
  github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/auth.go:105 +0x322
  github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor-fm()
      <autogenerated>:1 +0xe6
  google.golang.org/grpc.chainUnaryInterceptors.func1.1()
      google.golang.org/grpc/external/org_golang_google_grpc/server.go:1165 +0x22a
  github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1.1()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:133 +0x70
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:336 +0x147
  github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:131 +0x137
  google.golang.org/grpc.chainUnaryInterceptors.func1.1()
      google.golang.org/grpc/external/org_golang_google_grpc/server.go:1165 +0x22a
  google.golang.org/grpc.chainUnaryInterceptors.func1()
      google.golang.org/grpc/external/org_golang_google_grpc/server.go:1167 +0x298
  github.com/cockroachdb/cockroach/pkg/kv/kvpb._Internal_Batch_Handler()
      github.com/cockroachdb/cockroach/pkg/kv/kvpb/bazel-out/k8-fastbuild/bin/pkg/kv/kvpb/kvpb_go_proto_/github.com/cockroachdb/cockroach/pkg/kv/kvpb/api.pb.go:10061 +0x1dd
  google.golang.org/grpc.(*Server).processUnaryRPC()
      google.golang.org/grpc/external/org_golang_google_grpc/server.go:1340 +0x15da
  google.golang.org/grpc.(*Server).handleStream()
      google.golang.org/grpc/external/org_golang_google_grpc/server.go:1713 +0xff8
  google.golang.org/grpc.(*Server).serveStreams.func1.2()
      google.golang.org/grpc/external/org_golang_google_grpc/server.go:965 +0xec

Goroutine 37415 (running) created at:
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:475 +0x619
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:313 +0x406
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRaft()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:714 +0xc4
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).Start()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store.go:2063 +0x127a
  github.com/cockroachdb/cockroach/pkg/server.(*Node).start()
      github.com/cockroachdb/cockroach/pkg/server/node.go:604 +0x1539
  github.com/cockroachdb/cockroach/pkg/server.(*Server).PreStart()
      github.com/cockroachdb/cockroach/pkg/server/server.go:1800 +0x349a
  github.com/cockroachdb/cockroach/pkg/server.(*TestServer).Start()
      github.com/cockroachdb/cockroach/pkg/server/testserver.go:622 +0x8f
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).startServer()
      github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:593 +0xd4
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).Start()
      github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:389 +0x890
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.StartTestCluster()
      github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:233 +0x9a
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.NewTestCluster()
      github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:329 +0xcec
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.NewTestCluster()
      github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:329 +0xcec
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.StartTestCluster()
      github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:232 +0x7d
  github.com/cockroachdb/cockroach/pkg/server_test.TestAdminAPITableStats()
      github.com/cockroachdb/cockroach/pkg/server_test/pkg/server/admin_cluster_test.go:86 +0x134
  testing.tRunner()
      GOROOT/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      GOROOT/src/testing/testing.go:1493 +0x47

Goroutine 1882489 (running) created at:
  google.golang.org/grpc.(*Server).serveStreams.func1()
      google.golang.org/grpc/external/org_golang_google_grpc/server.go:963 +0x4dd
  google.golang.org/grpc/internal/transport.(*http2Server).operateHeaders()
      google.golang.org/grpc/internal/transport/external/org_golang_google_grpc/internal/transport/http2_server.go:599 +0x30c9
  google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams()
      google.golang.org/grpc/internal/transport/external/org_golang_google_grpc/internal/transport/http2_server.go:644 +0x378
  google.golang.org/grpc.(*Server).serveStreams()
      google.golang.org/grpc/external/org_golang_google_grpc/server.go:949 +0x275
  google.golang.org/grpc.(*Server).handleRawConn.func1()
      google.golang.org/grpc/external/org_golang_google_grpc/server.go:891 +0x64
==================
I230627 02:06:18.994367 1 (gostd) testmain.go:534  [-] 1  Test //pkg/server:server_test exited with error code 66


ERROR: exit status 66
```

**Comment by knz** [comment]
This data race is not related to your work. O believe we have an issue for it already, and it's for the kv team. Try looking for that stack trace in the issue tracker.

**Comment by THardy98** [comment]
> This data race is not related to your work. O believe we have an issue for it already, and it's for the kv team. Try looking for that stack trace in the issue tracker.

Ah, here it is: https://github.com/cockroachdb/cockroach/issues/104837
thank you!

**Review by j82w — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105227#-:-NYxM5uT0vnGHSY3f19W:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/sql/audit_logging.go` line 122 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/105227#-NYbn-H12KnCdJyoWCVr:-NYxMA0W5Nz6KcwPRXjP:b-p6m2mg) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1afd6c845b82e5351f3514d96deedb71e05c3b/pkg/sql/audit_logging.go#L122)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: consider checking whether the audit log config is empty first and take a shortcut. The enterprise license check is comparatively more expensive.
</blockquote></details>

Doesn't it do that shortcut in the method?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105227)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @j82w)

___
*[`pkg/sql/audit_logging.go` line 122 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/105227#-NYbn-H12KnCdJyoWCVr:-NYxNkGZ6ZMkpVBolmLb:btf5nkn) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1afd6c845b82e5351f3514d96deedb71e05c3b/pkg/sql/audit_logging.go#L122)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Doesn't it do that shortcut in the method?
</blockquote></details>

The first time around I thought the call to `shouldNotRoleBasedAudit` came first. If that's not the case, please ignore my comment.

**Comment by THardy98** [comment]
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105227)_ status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @j82w)
> 
> _[`pkg/sql/audit_logging.go` line 122 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/105227#-NYbn-H12KnCdJyoWCVr:-NYxNkGZ6ZMkpVBolmLb:btf5nkn) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1afd6c845b82e5351f3514d96deedb71e05c3b/pkg/sql/audit_logging.go#L122)):_
> 
> Previously, j82w (Jake) wrote…
> > Doesn't it do that shortcut in the method?
> 
> The first time around I thought the call to `shouldNotRoleBasedAudit` came first. If that's not the case, please ignore my comment.

It did :) I made the change.

**Comment by THardy98** [comment]
@knz are there still blocking changes?

**Review by knz — APPROVED** [review]
Thanks

**Comment by THardy98** [comment]
Want to post a benchmark with these changes before merging.

`sql.log.user_audit` cluster setting is non-empty, causing checks for the enterprise license, but the enterprise license check fails so there is no overhead of actual logging. Consequently, the benchmark is just the cost of the enterprise checks:
```
Number of reads that didn't return any results: 118.
Write sequence could be resumed by passing --write-seq=R702190 to the next run.

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 1800.0s        0       13333509         7407.5      1.0      1.0      1.6      2.0     83.9  read

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 1800.0s        0         702188          390.1      1.9      1.9      2.6      3.7     79.7  write

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
 1800.0s        0       14035697         7797.6      1.0      1.0      1.8      2.4     83.9
 ```
Negligible loss (~2%) compared to results in #101658. Could be accounted for by different runs not using the same data initialization.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105227)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[`pkg/sql/audit_logging.go` line 122 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/105227#-NYbn-H12KnCdJyoWCVr:-N_oFUm34hl2KaWV3jHX:bkhs3z8) ([raw file](https://github.com/cockroachdb/cockroach/blob/da1afd6c845b82e5351f3514d96deedb71e05c3b/pkg/sql/audit_logging.go#L122)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

It did :) I made the change.
</blockquote></details>

Just wanted to callout that `p.isInternalPlanner` - confusingly - is likely to not be set to `true` when the query is run via the InternalExecutor, so there may a bug in here. It is similar to a9b83b5ee7492cdbebaf324f10edc5e092c24ab7 in nature, and I'll look into fixing this `isInternalPlanner` on master (but not might be backportable).

**Pull request merged**
