### PR TITLE
distsql: add deadlock test

### PR DESCRIPTION
**Pull request by RaduBerinde**
Adding a test that exposes the deadlock described in #17097. Separating this from the fix to make things easier to review.

### CODE REVIEW

**Comment by knz** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/cluster_test.go, line 287 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17295#-KqEyLnuLDBAKCoR8GqV:-KqEyLnvU8b9tNXOk4-d:b-1zbhuu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e093ce95086c7fe4acc1bd5fc9e7406ae1524517/pkg/sql/distsqlrun/cluster_test.go#L287)):*
> ```Go
> 
> // TestDeadlock sets up a scenario which leads to deadlock if the hash router
> // blocks whenever one of the consumers blocks (#17097).
> ```

This looks good but I'm not completely happy about the way you are committing it here (with a Skip). The issue is that the test should really check the deadlock prior to you fixing #17097, so we have positive evidence that the test is actually exercising the problem situation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17295)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/cluster_test.go, line 287 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17295#-KqEyLnuLDBAKCoR8GqV:-KqF2FpPPBwkhWXlF5WH:bhy55hw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e093ce95086c7fe4acc1bd5fc9e7406ae1524517/pkg/sql/distsqlrun/cluster_test.go#L287)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This looks good but I'm not completely happy about the way you are committing it here (with a Skip). The issue is that the test should really check the deadlock prior to you fixing #17097, so we have positive evidence that the test is actually exercising the problem situation.
</blockquote></details>

I am not sure what you suggest here. The test deadlocks so we can't turn it on without the fix. You can unskip it and verify it deadlocks (and merging this separately from the upcoming fix PR actually lets you do that..)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17295)*

**Comment by knz** [comment]
Can't the test detect the deadlock?

**Comment by RaduBerinde** [comment]
Well, not without making things a lot more complicated. What's the point? Do you want me to check in a test that *verifies* the deadlock (i.e. passes only when we have a deadlock?!

If I posted this in the same PR with the fix, nobody would bat an eyelid..

**Comment by knz** [comment]
I guess I am perhaps bothered by the fact we can't detect a deadlock when it happens. This doesn't bode well for future bugs of this kind... 

In more general terms even if the fix was in the same commit I always prefer tests that check the problem exists and then only checks the solution. In logic tests that's equivalent to when we both use an invalid statement to check an error and the valid form to check it works. In the memory test we have first a test that shows query reaching the quota and failing before testing that increasing the quota makes the query work. etc.

**Comment by knz** [comment]
Maybe here we could let it go but please then at least push for an item "deadlock detection" for our roadmap. I still think we should do it; if you think it's going to be non-trivial work it needs to be appropriately prioritized, etc. Maybe a started project or something.

**Comment by RaduBerinde** [comment]
I really don't understand your point. This is exactly like the ones you describe, the test that fails (times out) without the fix and which will pass with the fix. We never try to write tests that somehow expose a bug AND pass WITHOUT the fix.

It would help if you told me exactly what you would want from this PR if we had infinite engineering time. You would want a test that detects the deadlock and passes? And then when the fix goes in, change the test so that it passes only if there is no deadlock?

Deadlock detection as part of tests seems of limited use to me - it would just be the difference between a timeout and failure.

Having some kind of deadlock detection at runtime so we can maybe do some damage control if it happens would be nice of course, but this PR is hardly appropriate for that discussion. Feel free to file an issue.

**Comment by arjunravinarayan** [comment]
I'm out right now, and don't have time for a full review today, but I just want to clarify that the overall approach looks *very* sound. If anything, @RaduBerinde has already gone out of his way to find a very subtle test that exposes the deadlock. I do not think @knz that the "deadlock detection" you are asking for is possible in any reasonable amount of time. Lets talk about this later (with citation) on why it's inherently difficult.

**Comment by knz** [comment]
okay we can resume that conversation off this PR later (also not when it's saturday night here!)

**Comment by petermattis** [comment]
We usually rely on test timeouts to detect deadlocks. Doing anything more sophisticated sounds very fragile.

**Comment by arjunravinarayan** [comment]
Yup, that's exactly what this test does, and hence why I'm in support of the approach. Thanks for chiming in @petermattis.

**Comment by arjunravinarayan** [comment]
:lgtm: on the overall approach and the network design, but :dog: can't quite verify the `FlowSpec` does what I think it does. 

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/cluster_test.go, line 288 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17295#-KqODgWuK-oUtQgNbFjm:-KqODgWuK-oUtQgNbFjn:b-ehcnki) ([raw file](https://github.com/cockroachdb/cockroach/blob/e093ce95086c7fe4acc1bd5fc9e7406ae1524517/pkg/sql/distsqlrun/cluster_test.go#L288)):*
> ```Go
> // TestDeadlock sets up a scenario which leads to deadlock if the hash router
> // blocks whenever one of the consumers blocks (#17097).
> func TestDeadlock(t *testing.T) {
> ```

`TestRowChannelBuffers` ? `TestDeadlock` is not too descriptive.

---

*[pkg/sql/distsqlrun/cluster_test.go, line 382 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17295#-KqOEpbLoZmaJqjEdoU9:-KqOEpbML3Wj6Bb_yshU:b-dudz5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/e093ce95086c7fe4acc1bd5fc9e7406ae1524517/pkg/sql/distsqlrun/cluster_test.go#L382)):*
> ```Go
> 	)
> 
> 	req := SetupFlowRequest{
> ```

Setting up the flows manually makes it difficult to follow. Would it be much work to annotate your diagram above with the StreamIDs and processor names? That would make it a lot easier to check.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17295#-:-KqOF14v4gtN7c2tAvHY:bt22nb3)*

**Comment by RaduBerinde** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/distsqlrun/cluster_test.go, line 288 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17295#-KqODgWuK-oUtQgNbFjm:-KqOH8g8F0dQjWTNqGjy:bj1r9hf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e093ce95086c7fe4acc1bd5fc9e7406ae1524517/pkg/sql/distsqlrun/cluster_test.go#L288)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

`TestRowChannelBuffers` ? `TestDeadlock` is not too descriptive.
</blockquote></details>

Changed to `TestLimitedBufferingDeadlock`.

---

*[pkg/sql/distsqlrun/cluster_test.go, line 382 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17295#-KqOEpbLoZmaJqjEdoU9:-KqOH9xXMpCpc1-BQmHb:bgj6xej) ([raw file](https://github.com/cockroachdb/cockroach/blob/e093ce95086c7fe4acc1bd5fc9e7406ae1524517/pkg/sql/distsqlrun/cluster_test.go#L382)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Setting up the flows manually makes it difficult to follow. Would it be much work to annotate your diagram above with the StreamIDs and processor names? That would make it a lot easier to check.
</blockquote></details>

Added stream IDs and some comments for the processors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17295)*

**Comment by arjunravinarayan** [comment]
Excellent.

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsqlrun/cluster_test.go, line 382 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17295#-KqOEpbLoZmaJqjEdoU9:-KqOI4QZKNqhXAMn3OxQ:b-qlqujp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e093ce95086c7fe4acc1bd5fc9e7406ae1524517/pkg/sql/distsqlrun/cluster_test.go#L382)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Added stream IDs and some comments for the processors.
</blockquote></details>

Excellent. Thank you!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17295#-:-KqOJHK7OdmxTKEUIWvJ:b-ec019f)*

**Pull request merged**
