### PR TITLE
roachprod: guard calls to SetupSSH

### LINKED ISSUE #90092: roachprod: remove concurrency in `SetupSSH`
**Describe the problem**

`roachprod.SetupSSH` uses `gcloud compute config-ssh` which in turn writes to the host's ssh config. The underlying write is not atomic (even in not using Docker volumes) [1], so creating multiple clusters concurrently can lead to invalid SSH configurations.

We should ensure `config-ssh` calls do not run concurrently.

Roachtest failure where this behavior was observed: #89599.

```
/home/roach/.ssh/config: line 2932: Bad configuration option: ho
/home/roach/.ssh/config: terminating, 1 bad configuration options
: exit status 1
```

[1] https://github.com/google-cloud-sdk-unofficial/google-cloud-sdk/blob/master/lib/surface/compute/config_ssh.py?rgh-link-date=2022-10-15T04%3A21%3A46Z#L389

### PR DESCRIPTION
**Pull request by herkolategan**
This change ensures that calls to `SetupSSH` do not run concurrently across
processes or threads. Overlapping calls are not safe and can lead to invalid SSH
configurations. The scenario takes place when multiple clusters are created
simultaneously from the same or multiple processes.

Resolves:  #90092

Release note: None

### CODE REVIEW

**Review by smg260 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96794)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @srosenberg)

___
*[`pkg/roachprod/vm/gce/gcloud.go` line 654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96794#-NNlTeIc-tA7udGo36fg:-NNlTeIc-tA7udGo36fh:b-aai3s2) ([raw file](https://github.com/cockroachdb/cockroach/blob/74b5270fdfb293f7b6e8109f408a0b3f34dec1ac/pkg/roachprod/vm/gce/gcloud.go#L654)):*
> ```Go
> // ConfigSSH is part of the vm.Provider interface
> func (p *Provider) ConfigSSH(zones []string) error {
> 	configSSHMu.Lock()
> ```

Would this make more sense at the roachprod level? Only having locking for GCP will still result in potential write contention to the config file from other providers.  

Conceptually it makes sense to have only one process modifying ssh config. 

Also if there is ever a case where we have multiple roachtests running from the same machine (I don't think we can), this would not work.

**Review by herkolategan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96794)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @smg260 and @srosenberg)

___
*[`pkg/roachprod/vm/gce/gcloud.go` line 654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96794#-NNlTeIc-tA7udGo36fg:-NNl_-Oy2Nawf6YXNgXZ:b-4b0jje) ([raw file](https://github.com/cockroachdb/cockroach/blob/74b5270fdfb293f7b6e8109f408a0b3f34dec1ac/pkg/roachprod/vm/gce/gcloud.go#L654)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

Would this make more sense at the roachprod level? Only having locking for GCP will still result in potential write contention to the config file from other providers.  

Conceptually it makes sense to have only one process modifying ssh config. 

Also if there is ever a case where we have multiple roachtests running from the same machine (I don't think we can), this would not work. 
</blockquote></details>

I was dubious at doing it on a`roachprod` level as each provider might have different ways of providing access. AWS seems to send a key rather than modifying the `shared` local resource. But then again there might be little harm in a blanket lock one level up? It's true if you run multiple `roachprod` instances the issue would persist, I'll look into a system-wide lock (maybe a file based lock).

**Review by herkolategan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96794)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @smg260 and @srosenberg)

___
*[`pkg/roachprod/vm/gce/gcloud.go` line 654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96794#-NNlTeIc-tA7udGo36fg:-NNleqgMCMeNvJ9hndOy:bj1wul8) ([raw file](https://github.com/cockroachdb/cockroach/blob/74b5270fdfb293f7b6e8109f408a0b3f34dec1ac/pkg/roachprod/vm/gce/gcloud.go#L654)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

I was dubious at doing it on a`roachprod` level as each provider might have different ways of providing access. AWS seems to send a key rather than modifying the `shared` local resource. But then again there might be little harm in a blanket lock one level up? It's true if you run multiple `roachprod` instances the issue would persist, I'll look into a system-wide lock (maybe a file based lock).
</blockquote></details>

Right so `Sync` which ultimately calls `SetupSSH` already does a `file lock` for the sync part. I'll re-use that logic and add one for the call to `SetupSSH`.

**Review by smg260 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96794)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @srosenberg)

___
*[`pkg/roachprod/vm/gce/gcloud.go` line 654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96794#-NNlTeIc-tA7udGo36fg:-NNlkqUA1ZG6MLauaDsn:b1368sf) ([raw file](https://github.com/cockroachdb/cockroach/blob/74b5270fdfb293f7b6e8109f408a0b3f34dec1ac/pkg/roachprod/vm/gce/gcloud.go#L654)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

Right so `Sync` which ultimately calls `SetupSSH` already does a `file lock` for the sync part. I'll re-use that logic and add one for the call to `SetupSSH`.
</blockquote></details>

I think the issue this PR addresses only arises because roachtest can attempt to create multiple clusters simultaneously (via multiple roachprod calls).

**Review by herkolategan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96794)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @smg260 and @srosenberg)

___
*[`pkg/roachprod/vm/gce/gcloud.go` line 654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96794#-NNlTeIc-tA7udGo36fg:-NNllG2T83A9sErWij8a:b-rnhiwv) ([raw file](https://github.com/cockroachdb/cockroach/blob/74b5270fdfb293f7b6e8109f408a0b3f34dec1ac/pkg/roachprod/vm/gce/gcloud.go#L654)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

I think the issue this PR addresses only arises because roachtest can attempt to create multiple clusters simultaneously (via multiple roachprod calls). 
</blockquote></details>

True, but I agree with your statement around multiple processes still being at risk. In fact `CleanSSH` was already covered by the system-wide or (user user-wide rather) lock-file. Same just had to be done for SetupSSH.

**Review by renatolabs — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96794#-:-NNmfLLn4X-4cHvmy0NM:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @smg260 and @srosenberg)

**Review by smg260 — APPROVED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96794)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @srosenberg)

**Comment by herkolategan** [comment]
bors r=renatolabs,smg260

**Comment by herkolategan** [comment]
bors retry

**Pull request merged**
