### PR TITLE
opt: generate inverted joins on multi-column inverted indexes

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: check for mutations of scanIndexIter filters

It is possible for an `enumerateIndexFunc` callback to mutate a
`scanIndexIter`'s `filters` field. This is possible because the
`filters` slice is passed directly to the enumeration callbacks. This
can cause several types of bugs. For example, mutating `filters` might
prevent enumeration of a future partial index. Also, upon enumeration of
the next index, the mutated filters would be passed to the
`enumerateIndexFunc` rather than the unaltered filters.

This commit adds a crdb_test build check that panics if  filters are
mutated by an enumeration callback. This check does not run in non-test
builds to avoid the overhead of the check.

Release note: None

#### opt: generate inverted joins on multi-column inverted indexes

This commit updates `GenerateInvertedJoins` so that inverted joins are
generated on multi-column inverted indexes.

In order to perform an inverted join on a multi-column index, the
non-inverted prefix columns must be constrained. This commit introduces
a `PrefixKeyCols` field to the `InvertedJoin` expression, which is
similar to the `KeyCols` field of `LookupJoin`. `PrefixKeyCols`
describes the columns from the input of the join that can be used to
constrain the non-inverted prefix columns of a multi-column inverted
index for each lookup.

Currently, only the `ON` condition is searched to find constant values
that the non-inverted prefix columns can be constrained to. Future work
includes searching in CHECK constraints and computed column expressions,
and looking for equality conditions between the prefix columns and
columns in the input of the join.

Note that the execution engine does not currently support inverted joins
on multi-column inverted indexes. This commit only updates the optimizer
to generate these types of expressions. Future work will add support to
the inverted joiner to perform these joins.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: Very nice!

[nit] in the commit/PR message "computer column expressions" -> "computed column expressions"

> Reviewed 1 of 1 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57845#-:-MOWUQqD9UfHyrD5wA8U:b-79qdz2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @RaduBerinde, and @sumeerbhola)

___
*[pkg/sql/opt/xform/join_funcs.go, line 491 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57845#-MOWX5GU2n_30fV579U6:-MOWX5GV-grzPzLzHl0V:b8ukm79) ([raw file](https://github.com/cockroachdb/cockroach/blob/79fd189db1c8d5688f95ff79d8f32d5c24f18ec9/pkg/sql/opt/xform/join_funcs.go#L491)):*
> ```Go
> 			prefixCol := scanPrivate.Table.IndexColumnID(index, i)
> 
> 			// Try to constraint prefixCol to constant, non-ranging values.
> ```

[nit] constraint -> constrain
___
*[pkg/sql/opt/xform/join_funcs.go, line 672 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57845#-MOWYquG6mOrZIXI5XFB:-MOWYquG6mOrZIXI5XFC:batjl9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/79fd189db1c8d5688f95ff79d8f32d5c24f18ec9/pkg/sql/opt/xform/join_funcs.go#L672)):*
> ```Go
> // the input with every value in vals. The cross join will be converted into a
> // projection by inlining normalization rules if vals contains only a single
> // value. The constructed expression and the column ID of constant value column
> ```

[nit] of constant -> of the constant

**Review by RaduBerinde — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57845)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @sumeerbhola)

___
*[pkg/sql/opt/xform/scan_index_iter.go, line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57845#-MOXEjJVDr46KpZlh-Nn:-MOXEjJVDr46KpZlh-No:brmq8gp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba7f9ce96516258af1c6f16d221ec29b59ca48e6/pkg/sql/opt/xform/scan_index_iter.go#L213)):*
> ```Go
> 		}
> 
> 		filters := it.filtersCopy()
> ```

Won't this be expensive? It will happen for every index, in every rule that iterates over indexes..

An alternative here would be to add a check behind the crdb_test build tag which verifies that the filters are unchanged. Perhaps hashing the Conditions (like HashScalarExpr) or something along those lines.

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57845)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/xform/join_funcs.go, line 482 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57845#-MOXmL362eco4ifivyh6:-MOXmL362eco4ifivyh7:b-fxyqz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/79fd189db1c8d5688f95ff79d8f32d5c24f18ec9/pkg/sql/opt/xform/join_funcs.go#L482)):*
> ```Go
> 		// constrain each prefix column to non-ranging constant values. These
> 		// values are joined with the input to create key columns for the
> 		// InvertedJoin, similar to GenerateLookupJoins.
> ```

I think I may have asked a variant of this on the earlier PR for lookup joins -- what if the input already provides a subset of these prefix columns e.g. the prefix cols are c1, c2, c3, and the join predicate is `left.c1 = right.c1 and left.c3 = right.c3 and right.c2 IN (1, 2)`. Will we do a cross-join only to inject the `(1, 2)`?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57845)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft and @sumeerbhola)

___
*[pkg/sql/opt/xform/join_funcs.go, line 482 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57845#-MOXmL362eco4ifivyh6:-MOY1UoKBLdLyheUmode:b-dygysg) ([raw file](https://github.com/cockroachdb/cockroach/blob/79fd189db1c8d5688f95ff79d8f32d5c24f18ec9/pkg/sql/opt/xform/join_funcs.go#L482)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think I may have asked a variant of this on the earlier PR for lookup joins -- what if the input already provides a subset of these prefix columns e.g. the prefix cols are c1, c2, c3, and the join predicate is `left.c1 = right.c1 and left.c3 = right.c3 and right.c2 IN (1, 2)`. Will we do a cross-join only to inject the `(1, 2)`?
</blockquote></details>

Exactly! Note that this inverted join rule doesn't yet handle column equality like `left.c1 = right.c1`, but I'll be adding that very soon. Lookup joins can already handle the exact situation which you describe.
___
*[pkg/sql/opt/xform/join_funcs.go, line 491 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57845#-MOWX5GU2n_30fV579U6:-MOY1nUN95z8ijBBZnXW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79fd189db1c8d5688f95ff79d8f32d5c24f18ec9/pkg/sql/opt/xform/join_funcs.go#L491)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] constraint -> constrain
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/join_funcs.go, line 672 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57845#-MOWYquG6mOrZIXI5XFB:-MOY1xSD31P0usZ0F7gy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79fd189db1c8d5688f95ff79d8f32d5c24f18ec9/pkg/sql/opt/xform/join_funcs.go#L672)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] of constant -> of the constant
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/scan_index_iter.go, line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57845#-MOXEjJVDr46KpZlh-Nn:-MOXxOlxAGoXPmRE-aaE:b-msp0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba7f9ce96516258af1c6f16d221ec29b59ca48e6/pkg/sql/opt/xform/scan_index_iter.go#L213)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Won't this be expensive? It will happen for every index, in every rule that iterates over indexes..

An alternative here would be to add a check behind the crdb_test build tag which verifies that the filters are unchanged. Perhaps hashing the Conditions (like HashScalarExpr) or something along those lines.
</blockquote></details>

Good idea. Done. PTAL and let me know if it LGTY.

I'll note that there are quite a few places where we already copy filters (or a subset of them), like `memo.ExtractRemainingJoinFilters`, `Implicator.filtersImplyPredicateFastPath` and `Implicator.simplifyFiltersExpr`. But it doesn't hurt to reduce the copying where possible.

**Review by rytaft — COMMENTED** [review]
> Reviewed 4 of 9 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57845)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @sumeerbhola)

___
*[pkg/sql/opt/xform/join_funcs.go, line 524 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57845#-MOYEL4p4z3trUdHnvQx:-MOYEL4p4z3trUdHnvQy:bypn0xc) ([raw file](https://github.com/cockroachdb/cockroach/blob/641f3e3dabd63555dad365ad6871512584f2a1b4/pkg/sql/opt/xform/join_funcs.go#L524)):*
> ```Go
> 		onCopy := make(memo.FiltersExpr, len(on))
> 		copy(onCopy, on)
> 		on = onCopy
> ```

Seems like you could avoid making a copy if `constFilters` is empty. Alternatively, you could define a copy-on-write helper function that makes a call to `RemoveCommonFilters`.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57845)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft and @sumeerbhola)

___
*[pkg/sql/opt/xform/join_funcs.go, line 524 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57845#-MOYEL4p4z3trUdHnvQx:-MOYJhRiA2ayZThPIdfe:b-vbdpa3) ([raw file](https://github.com/cockroachdb/cockroach/blob/641f3e3dabd63555dad365ad6871512584f2a1b4/pkg/sql/opt/xform/join_funcs.go#L524)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Seems like you could avoid making a copy if `constFilters` is empty. Alternatively, you could define a copy-on-write helper function that makes a call to `RemoveCommonFilters`.
</blockquote></details>

I added a check that `constFilters` isn't empty. I don't want to overthink this too much right now because a change to this is imminent in order to support equality filters between columns on the left and right; GenerateLookupJoins always calls `memo.ExtractRemainingJoinFilters` which performs a copy.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 6 files at r5, 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57845#-:-MOYRzjL4800ZQE1Zx4j:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57845#-:-MOZYVuCDIv1EbC8RaZj:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner and @sumeerbhola)

___
*[pkg/sql/opt/memo/filters_expr_mutate_checker.go, line 20 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/57845#-MOZXqs6C1Iz-VErvk6b:-MOZXqs6C1Iz-VErvk6c:baue0pp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3184b7b061cc6c40d78538a106b4867497675f5/pkg/sql/opt/memo/filters_expr_mutate_checker.go#L20)):*
> ```Go
> // erroneously mutated. This code is called in crdb_test builds so that the
> // check is run for tests, but the overhead is not incurred for non-test builds.
> type FiltersExprMutateChecker struct {
> ```

This is :100:   I'm sure we will use it in more places over time.
___
*[pkg/sql/opt/xform/scan_index_iter.go, line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57845#-MOXEjJVDr46KpZlh-Nn:-MOZXxWYEVJJBvhOqN0L:btkfeb8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba7f9ce96516258af1c6f16d221ec29b59ca48e6/pkg/sql/opt/xform/scan_index_iter.go#L213)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Good idea. Done. PTAL and let me know if it LGTY.

I'll note that there are quite a few places where we already copy filters (or a subset of them), like `memo.ExtractRemainingJoinFilters`, `Implicator.filtersImplyPredicateFastPath` and `Implicator.simplifyFiltersExpr`. But it doesn't hurt to reduce the copying where possible.
</blockquote></details>

Looks great!! Thanks!

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
