### PR TITLE
distsqlrun: add throttling to automatic stats

### PR DESCRIPTION
**Pull request by rytaft**
This commit adds throttling to the sampler processors which perform
sampling for `CREATE STATISTICS`. This throttling works by sleeping for
a short period of time after every 10,000 rows are processed. The sleep
time is proportional to the time it took to process those 10,000 rows,
making the processor idle approximately 90% of the time. Note that
throttling is only performed when the sampler is part of an automatic
statistics refresh. Manual runs of `CREATE STATISTICS` are not throttled.

The amount of idle time is tunable by adjusting a new cluster setting
`sql.stats.experimental_automatic_collection.fraction_idle`.

Release note (sql change): Added a cluster setting to control throttling
of automatic statistics.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

Very cool!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34928#-:-LYhroSsCuWfwmbs8Rf9:btgo8jj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/distsqlpb/processors.proto, line 766 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34928#-LYhrukJ7zuyRGwfuY0T:-LYhrukJ7zuyRGwfuY0U:btvglb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9f99f1e3ada8daf90bd4c98ee5f54631b85fed0/pkg/sql/distsqlpb/processors.proto#L766)):*
> ```protobuf
> // sketch columns.
> //
> // is_auto_stats is true if this sampler is part of an automated run of
> ```

[nit] move this comment by the field (and don't mention the field name, it's different in go).
___
*[pkg/sql/distsqlrun/sampler.go, line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34928#-LYhrZsq9ZldJFMM9TAD:-LYhrZsq9ZldJFMM9TAE:b-uw51v) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9f99f1e3ada8daf90bd4c98ee5f54631b85fed0/pkg/sql/distsqlrun/sampler.go#L179)):*
> ```Go
> 	var buf []byte
> 	rowCount := 0
> 	startTime := time.Now()
> ```

[nit] the name is very generic, maybe `lastWakeupTime`
___
*[pkg/sql/distsqlrun/sampler_test.go, line 282 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34928#-LYhsI0hBnJI7TdsYLe0:-LYhsI0hBnJI7TdsYLe1:b-r1pjm1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9f99f1e3ada8daf90bd4c98ee5f54631b85fed0/pkg/sql/distsqlrun/sampler_test.go#L282)):*
> ```Go
> 	// the throttled runs is greater than the average duration of the not-throttled
> 	// runs.
> 	if durationNotThrottled > durationThrottled {
> ```

Whenever I wrote a test of this nature sooner or later someone hit a flake (even when I couldn't stress one locally). There could be significant occasional slowdown on a VM (e.g. if it's being motioned between hosts). The number of runs would need to be very high to guarantee that this won't be flaky.

I would do something like check after X runs, if not do X more runs and check again, and so on (doubling each time), up to some very high limit.

Another option would be to make this into a benchmark (with sub-benchmarks for various idleTime values), and it would be run manually if there is doubt about the mechanism. It would be cool to actually see the times.

**Review by rytaft — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34928#-:-LYi1Tti9Xry3tIgqhj-:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @RaduBerinde)

___
*[pkg/sql/distsqlpb/processors.proto, line 766 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34928#-LYhrukJ7zuyRGwfuY0T:-LYi0uu-4QTxaJOpUYxH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9f99f1e3ada8daf90bd4c98ee5f54631b85fed0/pkg/sql/distsqlpb/processors.proto#L766)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] move this comment by the field (and don't mention the field name, it's different in go).
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/sampler.go, line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34928#-LYhrZsq9ZldJFMM9TAD:-LYi0xkUESIcFQGUzCXo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9f99f1e3ada8daf90bd4c98ee5f54631b85fed0/pkg/sql/distsqlrun/sampler.go#L179)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] the name is very generic, maybe `lastWakeupTime`
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/sampler_test.go, line 282 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34928#-LYhsI0hBnJI7TdsYLe0:-LYi1-st5Y5gaev0T6c1:bu8jn6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9f99f1e3ada8daf90bd4c98ee5f54631b85fed0/pkg/sql/distsqlrun/sampler_test.go#L282)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Whenever I wrote a test of this nature sooner or later someone hit a flake (even when I couldn't stress one locally). There could be significant occasional slowdown on a VM (e.g. if it's being motioned between hosts). The number of runs would need to be very high to guarantee that this won't be flaky.

I would do something like check after X runs, if not do X more runs and check again, and so on (doubling each time), up to some very high limit.

Another option would be to make this into a benchmark (with sub-benchmarks for various idleTime values), and it would be run manually if there is doubt about the mechanism. It would be cool to actually see the times.
</blockquote></details>

Done. I basically copied what you had done in an earlier test in this file, but set `maxRuns` to 10000. Hopefully that's enough? Or do you think it should be higher?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34928)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @rytaft)

___
*[pkg/sql/distsqlrun/sampler_test.go, line 282 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34928#-LYhsI0hBnJI7TdsYLe0:-LYiCwTOBD5_ICqYMk23:b-qc5d9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9f99f1e3ada8daf90bd4c98ee5f54631b85fed0/pkg/sql/distsqlrun/sampler_test.go#L282)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Done. I basically copied what you had done in an earlier test in this file, but set `maxRuns` to 10000. Hopefully that's enough? Or do you think it should be higher?
</blockquote></details>

The way i did it was - I found the highest value where a local `make stress` would fail occasionally and multiplied that by like 10 or 100.

This needs to be small enough so that if the throttling is broken, the test fails rather than timing out. I'd comment out the `return` and see how long it would run to the end.
___
*[pkg/sql/distsqlrun/sampler_test.go, line 289 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34928#-LYiCmTj0Ibk6mzZAvzy:-LYiCmTj0Ibk6mzZAvzz:b-yn7wtr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a6921a49edf7df8bd8930064c97f3bc3c3b6c1a/pkg/sql/distsqlrun/sampler_test.go#L289)):*
> ```Go
> 		// the throttled runs is greater than the average duration of the not-throttled
> 		// runs.
> 		err = nil
> ```

[nit] `if durationNotThrottled <= durationThrottled { return }`

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34928)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @rytaft)

___
*[pkg/sql/distsqlrun/sampler.go, line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34928#-LYiQRMi6tdQqYHRGSP8:-LYiQRMi6tdQqYHRGSP9:b-r494r8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a6921a49edf7df8bd8930064c97f3bc3c3b6c1a/pkg/sql/distsqlrun/sampler.go#L75)):*
> ```Go
> // automatic stats.
> // It is mutable for testing.
> var AutoStatsIdleTime = 0.75
> ```

I think this needs to be a dynamically adjustable setting. We want our SE/Support teams to be able to have customers change this.

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34928)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball)

___
*[pkg/sql/distsqlrun/sampler.go, line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34928#-LYiQRMi6tdQqYHRGSP8:-LYm-Rre6lMvpjos72J5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a6921a49edf7df8bd8930064c97f3bc3c3b6c1a/pkg/sql/distsqlrun/sampler.go#L75)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I think this needs to be a dynamically adjustable setting. We want our SE/Support teams to be able to have customers change this.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/sampler_test.go, line 282 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34928#-LYhsI0hBnJI7TdsYLe0:-LYm3RoF0uf6svUTFxU2:b-ytlfaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9f99f1e3ada8daf90bd4c98ee5f54631b85fed0/pkg/sql/distsqlrun/sampler_test.go#L282)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The way i did it was - I found the highest value where a local `make stress` would fail occasionally and multiplied that by like 10 or 100.

This needs to be small enough so that if the throttling is broken, the test fails rather than timing out. I'd comment out the `return` and see how long it would run to the end.
</blockquote></details>

Cool, makes sense.  I changed it to 20000, since it failed occasionally with 200 but never with 400. In the worst case, the test finishes in about 5 seconds.
___
*[pkg/sql/distsqlrun/sampler_test.go, line 289 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34928#-LYiCmTj0Ibk6mzZAvzy:-LYm3KIe6h1TPuX0V7u_:bitf5u4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a6921a49edf7df8bd8930064c97f3bc3c3b6c1a/pkg/sql/distsqlrun/sampler_test.go#L289)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] `if durationNotThrottled <= durationThrottled { return }`
</blockquote></details>

Whoops! Done.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34928)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball)

___
*[pkg/sql/distsqlrun/sampler_test.go, line 282 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34928#-LYhsI0hBnJI7TdsYLe0:-LYmQI4M3g4IW40oNDpc:b2btb72) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9f99f1e3ada8daf90bd4c98ee5f54631b85fed0/pkg/sql/distsqlrun/sampler_test.go#L282)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Cool, makes sense.  I changed it to 20000, since it failed occasionally with 200 but never with 400. In the worst case, the test finishes in about 5 seconds.
</blockquote></details>

Sounds great, thanks!

**Comment by rytaft** [comment]
Did some benchmarking with TPC-C 400 warehouses on a cluster of 3 n1-standard-4 machines. Throughput and latency vary by less than 1% between the trials:

With stats enabled and throttling at 90% (default):

```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  600.0s        0         114398          190.7    855.0    486.5   2684.4  10200.5  32212.3

_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
  600.0s     4925.7  95.8%    929.6    520.1   1140.9   2684.4  11274.3  32212.3
```

With stats completely disabled:

```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  600.0s        0         114745          191.2    879.1    536.9   2550.1   8321.5  22548.6  

_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
  600.0s     4937.1  96.0%    969.1    604.0   1476.4   2684.4   9126.8  22548.6
```

**Review by andy-kimball — COMMENTED** [review]
Great results. Can you also try whatever configuration Dan H. was using to see if you can repro his original issue, and then make sure your fix takes care of it?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34928#-:-LYmfgLD-Ixppb8lWppn:b-rqo81y)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball)

**Comment by rytaft** [comment]
Ran the `tpcc/nodes=3/w=max` roachtest that Dan was using.

Results with stats disabled:
```_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
 7200.0s        0        4937547          685.8    188.7    159.4    453.0    671.1   5100.3  

_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
 7200.0s    17869.4  99.3%    218.8    192.9    419.4    503.3    704.6   3623.9
```

Results with stats enabled:
```_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
 7200.0s        0        4919259          683.2    256.5    192.9    704.6   1208.0  13421.8  

_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
 7200.0s    17806.9  98.9%    282.9    226.5    570.4    738.2   1275.1  13421.8
```

Throughput differs by less than 1%, but latency increased by 30%, and by 80% for p99. I'm seeing wide variation depending on the cluster used, so it's possible that the difference is smaller or larger.

Although 30-80% latency overhead isn't ideal, this also represents the maximum number of warehouses supported on the machines used (1400). I'm currently working on benchmarking with slightly below the max to see if that looks better.

But anyway, I'd like to merge this change since it's holding up some other work. Automatic stats are still disabled for the moment.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34928#-:-LZfga3V1h2aZiUk2OTS:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @rytaft)

___
*[pkg/sql/distsqlpb/processors.proto, line 771 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34928#-LZfbcgB9qXo9yt0v8s5:-LZfbcgB9qXo9yt0v8s6:b-51848d) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec965706f45eb7cabf507c79443f479ebe8c2be8/pkg/sql/distsqlpb/processors.proto#L771)):*
> ```protobuf
>   // This is true if this sampler is part of an automated run of
>   // CREATE STATISTICS.
>   optional bool is_auto_stats = 3 [(gogoproto.nullable) = false];
> ```

[nit] This would be better if it reflected what it actually does (maybe `enable_throttling`). The comment should explain that it looks at the cluster setting for the value. Perhaps the field should be a float and we populate that during planning instead of having the processor look at the setting.

Feel free to ignore this if you want to merge ASAP (perhaps just add to the comment explaining how it is used).

**Comment by rytaft** [comment]
___
*[pkg/sql/distsqlpb/processors.proto, line 771 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34928#-LZfbcgB9qXo9yt0v8s5:-LZfmMts9SqLIpELDtir:br6bb4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec965706f45eb7cabf507c79443f479ebe8c2be8/pkg/sql/distsqlpb/processors.proto#L771)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] This would be better if it reflected what it actually does (maybe `enable_throttling`). The comment should explain that it looks at the cluster setting for the value. Perhaps the field should be a float and we populate that during planning instead of having the processor look at the setting.

Feel free to ignore this if you want to merge ASAP (perhaps just add to the comment explaining how it is used).
</blockquote></details>

Good idea - done.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34928#-:-LZgj5ti81W1YqU_qIKu:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @rytaft)

___
*[pkg/sql/distsqlpb/processors.proto, line 771 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34928#-LZfbcgB9qXo9yt0v8s5:-LZgj4IuB2v5CsUE7jLb:b-h1hkn2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec965706f45eb7cabf507c79443f479ebe8c2be8/pkg/sql/distsqlpb/processors.proto#L771)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Good idea - done.
</blockquote></details>

Very nice, thanks!

**Comment by rytaft** [comment]
Thanks!

bors r+

**Pull request merged**
