### PR TITLE
kvserver: export latency histogram for time spent waiting for latches

### LINKED ISSUE #104682: kvserver: export latency histogram for time spent waiting for latches
This would have come in handy in numerous internal incidents.

Jira issue: CRDB-28667

Epic CRDB-34227

### PR DESCRIPTION
**Pull request by lyang24**
This commit adds a `HdrHistogram` that measures time spend waiting on latches for better observability on long latch waits. This histogram is stored in StorageMetrics and latch manager will receive a pointer to it when replica init. It will measure the time spend on wait method of spanlatch manager.

sanity check new metrics with kv workload
Screenshot 2024-02-02 at 10 54 12 AM

Fixes: #104682

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117226)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @lyang24)

___
*[`pkg/kv/kvserver/metrics.go` line 2207 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117226#-Np_ol19712EdLH0CdNe:-Np_ol19712EdLH0CdNf:b-fups62) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd8443b92dae009c7de074484ba7cbf0bfe02334/pkg/kv/kvserver/metrics.go#L2207)):*
> ```Go
> 	}
> 	metaLatchWaitDuration = metric.Metadata{
> 		Name:        "kv.concurrency.latch_wait_duration",
> ```

nit: s/duration/durations/ in the metric name and the variable names throughout the PR.
___
*[`pkg/kv/kvserver/metrics.go` line 2208 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117226#-Np_otdS7aJDofaxqoD6:-Np_otdS7aJDofaxqoD7:bjk2gp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd8443b92dae009c7de074484ba7cbf0bfe02334/pkg/kv/kvserver/metrics.go#L2208)):*
> ```Go
> 	metaLatchWaitDuration = metric.Metadata{
> 		Name:        "kv.concurrency.latch_wait_duration",
> 		Help:        "Duration(nanoseconds) spent on latch acquisition step to measure wait time on conflicts with other latches",
> ```

"Durations in nanoseconds spent on latch acquisition waiting for conflicts with other latches"
___
*[`pkg/kv/kvserver/metrics.go` line 2682 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117226#-Np_oU9r75oPAdBedXgR:-Np_oU9r75oPAdBedXgS:b-o7a907) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd8443b92dae009c7de074484ba7cbf0bfe02334/pkg/kv/kvserver/metrics.go#L2682)):*
> ```Go
> 	MaxLockWaitDurationNanos       *metric.Gauge
> 	MaxLockWaitQueueWaitersForLock *metric.Gauge
> 	LatchWaitDuration              *metric.HdrHistogram
> ```

This should use `metric.IHistogram`. Same thing in the `concurrency` package.
___
*[`pkg/kv/kvserver/metrics.go` line 3400 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117226#-Np_oaZ57aFIDwEShkEP:-Np_oaZ57aFIDwEShkEQ:b-wm4u93) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd8443b92dae009c7de074484ba7cbf0bfe02334/pkg/kv/kvserver/metrics.go#L3400)):*
> ```Go
> 		MaxLockWaitDurationNanos:       metric.NewGauge(metaConcurrencyMaxLockWaitDurationNanos),
> 		MaxLockWaitQueueWaitersForLock: metric.NewGauge(metaConcurrencyMaxLockWaitQueueWaitersForLock),
> 		LatchWaitDuration:              metric.NewHdrLatency(metaLatchWaitDuration, histogramWindow),
> ```

This should use `metric.NewHistogram`.
___
*[`pkg/kv/kvserver/spanlatch/manager.go` line 477 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117226#-Np_puymDc816bKOVjcT:-Np_puymDc816bKOVjcU:bt5xgrv) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd8443b92dae009c7de074484ba7cbf0bfe02334/pkg/kv/kvserver/spanlatch/manager.go#L477)):*
> ```Go
> 	timer := timeutil.NewTimer()
> 	timer.Reset(base.SlowRequestThreshold)
> 	tBegin := timeutil.Now()
> ```

This is currently measuring the full duration of `wait`, even if we don't end up conflicting with any other latches. I think it's probably too expensive to update a histogram even when there is no contention, and doing so might drown out any signal.

So I think we either want to:
1. push this into `waitForSignal` and update the histogram with the duration of each individual latch delay
2. plumb information out of `iterAndWait` to determine whether we ever actually called `waitForSignal`

I think option 1 is probably better because it is limited to just the duration to wait for conflicting latches and not to iterate over the snapshot.

**Review by lyang24 — COMMENTED** [review]
Thank you for reviewing, I have addressed comments. please thank another look when you have time.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117226#-:-NpfKr3lCZ9eb4ohShLF:b-qkhq8h)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/metrics.go` line 2682 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117226#-Np_oU9r75oPAdBedXgR:-NpfJuL-2-_jO0UAnViE:bbryfx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd8443b92dae009c7de074484ba7cbf0bfe02334/pkg/kv/kvserver/metrics.go#L2682)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This should use `metric.IHistogram`. Same thing in the `concurrency` package.
</blockquote></details>

nice how did i miss the interface 
___
*[`pkg/kv/kvserver/spanlatch/manager.go` line 477 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117226#-Np_puymDc816bKOVjcT:-NpfK-5d0PeAsngIBjpO:b-hg21cr) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd8443b92dae009c7de074484ba7cbf0bfe02334/pkg/kv/kvserver/spanlatch/manager.go#L477)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is currently measuring the full duration of `wait`, even if we don't end up conflicting with any other latches. I think it's probably too expensive to update a histogram even when there is no contention, and doing so might drown out any signal.

So I think we either want to:
1. push this into `waitForSignal` and update the histogram with the duration of each individual latch delay
2. plumb information out of `iterAndWait` to determine whether we ever actually called `waitForSignal`

I think option 1 is probably better because it is limited to just the duration to wait for conflicting latches and not to iterate over the snapshot.
</blockquote></details>

much agreed we should only capture latches with conflicts to get meaningfully representation of latch latency. Option 1 is the best fit semantically and easy to implement.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117226#-:-NpuS-EP1zN-6iLrVu27:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @lyang24)

**Pull request merged**
