### PR TITLE
opt: fix optsteps crash caused by constraint expressions

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: make FormatExpr easier to use

During debugging, it's sometimes useful to add a statement to print an
expression. This is fairly hard and can crash easily because the memo
or the catalog isn't set in the formatting context. In particular, it
is impossible to print a scalar expression that contains a relational
expression because `FormatExpr` only sets the memo when we print
relational expressions.

This change improves the situation by allowing the caller of
`FormatExpr` to pass the `*Memo` and by adding a convenience wrapper
method on the `Optimizer`. We also automatically unset the "fully
qualify" flag if there is no catalog (which would otherwise crash).

Release note: None

#### opt: fix optsteps crash caused by TableMeta expressions

The optbuilder creates scalar constraint and computed column
expressions and hangs them off the `TableMeta`. If a normalization
rule fires for one of these expressions, `optsteps` panics because it
can't find a path to the expression in the memo.

This change fixes the problem by adding special code in opt_steps
which effectively treats these expressions as children of Scan
expressions.

Release note: None

#### opt: show TableMeta expressions when formatting expressions

We build check constraint and computed column expressions and attach
them to `TableMeta`, to be used later by exploration rules. These are
currently invisible. This change adds them under "canonical" scans
(the normalized scan expression before any exploration rules).

Release note: None

### CODE REVIEW

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43405#-:-LwxnIVqDWYSry0d2gug:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @RaduBerinde)

___
*[pkg/sql/opt/xform/testdata/external/foo, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43405#-LwxmaLWB7JlnjelJOFy:-LwxmaLWB7JlnjelJOFz:blwt5sr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cddbdc2e803cf6f082d6f040e52a2de6a91d3b5/pkg/sql/opt/xform/testdata/external/foo#L1)):*
> ```
> exec-ddl
> ```

Did you mean to add this file to the PR?

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r1, 2 of 2 files at r2, 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43405#-:-Lx2WVCm23IRHyGoZ40G:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/opt/testutils/opttester/opt_tester.go, line 904 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43405#-Lx2UW7tDu3ZtLom5Wqf:-Lx2UW7tDu3ZtLom5Wqg:bmpuuwv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cddbdc2e803cf6f082d6f040e52a2de6a91d3b5/pkg/sql/opt/testutils/opttester/opt_tester.go#L904)):*
> ```Go
> 		}
> 
> 		next = memo.FormatExpr(os.Root(), ot.Flags.ExprFormat, os.Root().(memo.RelExpr).Memo(), ot.catalog)
> ```

why not use the convenience wrapper here and below?
___
*[pkg/sql/opt/testutils/opttester/testdata/opt_steps, line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43405#-Lx2VTgeERMveiGs4rTl:-Lx2VTgeERMveiGs4rTm:bl1q1jf) ([raw file](https://github.com/cockroachdb/cockroach/blob/218f575b5323aae1d67dfa9d17cfc79834db5479/pkg/sql/opt/testutils/opttester/testdata/opt_steps#L120)):*
> ```
> 
> exec-ddl
> CREATE TABLE customers (                        
> ```

Lots of extra spaces here and below

**Review by RaduBerinde — COMMENTED** [review]
Updated the commits to apply the same treatment to the new computed column expressions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43405#-:-Lx7QBzr6MTsWpIre0RI:b-37xykb)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andy-kimball and @rytaft)

___
*[pkg/sql/opt/testutils/opttester/opt_tester.go, line 904 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43405#-Lx2UW7tDu3ZtLom5Wqf:-Lx7KTdE3CVerFJxhVql:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cddbdc2e803cf6f082d6f040e52a2de6a91d3b5/pkg/sql/opt/testutils/opttester/opt_tester.go#L904)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

why not use the convenience wrapper here and below?
</blockquote></details>

Done.
___
*[pkg/sql/opt/testutils/opttester/testdata/opt_steps, line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43405#-Lx2VTgeERMveiGs4rTl:-Lx7LXe11aDCTjoI3DaF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/218f575b5323aae1d67dfa9d17cfc79834db5479/pkg/sql/opt/testutils/opttester/testdata/opt_steps#L120)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Lots of extra spaces here and below
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/external/foo, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43405#-LwxmaLWB7JlnjelJOFy:-Lx7LGyO-TC2DXgj-8z4:bnqizt) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cddbdc2e803cf6f082d6f040e52a2de6a91d3b5/pkg/sql/opt/xform/testdata/external/foo#L1)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Did you mean to add this file to the PR?
</blockquote></details>

Heh, no, fixed.

**Review by rytaft — APPROVED** [review]
:lgtm: It would be helpful if there were an easy way to associate the computed column expression with the column it represents (in the printed output), but I don't really have a specific idea.

> Reviewed 3 of 11 files at r4, 1 of 2 files at r5, 17 of 17 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43405#-:-Lx7kqHaC6Nyibz6aYfj:b-4u73pt)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball)

**Comment by RaduBerinde** [comment]
Interesting, we do have the colIDs, I'll try to think of something. Maybe show them as a list as the first child, like we would do on a project

**Comment by RaduBerinde** [comment]
Done, I added each computed column as the parent of its expression.

**Review by rytaft — APPROVED** [review]
Nice! This will be really helpful. :lgtm: 

> Reviewed 14 of 14 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43405#-:-Lxb4Xpx0_y5n0kCOm2N:bybdd57)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball)

**Comment by RaduBerinde** [comment]
TFTRs!

bors r+

**Pull request merged**
