### PR TITLE
changefeedccl: Do not inhibit node shutdown

### PR DESCRIPTION
**Pull request by miretskiy**
See individual commits for details:
  * Ensure running changefeed do not inhibit node shutdown (Informs #82765)
  * Treat node unavailable error as retryable.

Test not being merged as part of this PR -- see https://github.com/cockroachdb/cockroach/pull/82767

Release Notes (bug fix): Ensure running changefeeds do
not inhibit node shutdown.
Release Notes (bug fix): Treat node unavailable error as a retryable changefeed error.

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

nit: release notes: shouldn't this be a "bug fix" category?

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82768#-:-N4STQO43rPJMHCxkveg:b-tro2ae)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @miretskiy)

___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 211 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82768#-N4STJw95lhBGgTt8aZy:-N4STJw95lhBGgTt8aZz:bxl1v2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/145c9ee7c352650d2af481c93efa255369c481ad/pkg/ccl/changefeedccl/changefeed_processors.go#L211)):*
> ```Go
> // Start is part of the RowSource interface.
> func (ca *changeAggregator) Start(ctx context.Context) {
> 	// Derive a separate context so that we can shutdown the poller. Note that
> ```

nit: the second sentence is no longer applicable.
___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 220 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82768#-N4STMm4BWOcfL_VybeC:-N4STMm4BWOcfL_VybeD:b79kq3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/145c9ee7c352650d2af481c93efa255369c481ad/pkg/ccl/changefeedccl/changefeed_processors.go#L220)):*
> ```Go
> 	}
> 	ctx = ca.StartInternal(ctx, changeAggregatorProcName)
> 	ca.Ctx = ctx
> ```

nit: this line is no longer needed.

**Comment by miretskiy** [comment]
> nit: release notes: shouldn't this be a "bug fix" category?

Done.

> nit: the second sentence is no longer applicable.

removed
> nit: this line is no longer needed.
Removed.

**Comment by miretskiy** [comment]
@yuzefovich FYI: Pushed a change that explicitly tested for context.Cancel and treat it as retryable (changefeed_stmt).

**Review by yuzefovich — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82768)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @miretskiy)

___
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 1034 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82768#-N4U9Cpg9q7bJTKAgD66:-N4U9Cpg9q7bJTKAgD67:b-cv6e99) ([raw file](https://github.com/cockroachdb/cockroach/blob/dacafda9f34707f2f365c6130f7c5c8442f86e2d/pkg/ccl/changefeedccl/changefeed_stmt.go#L1034)):*
> ```Go
> 
> 		isRetryableErr := changefeedbase.IsRetryableError(err) ||
> 			(ctx.Err() == nil && errors.Is(err, context.Canceled))
> ```

nit: I think this condition would benefit from some commentary.

**Comment by miretskiy** [comment]
> nit: I think this condition would benefit from some commentary.

Done.

**Pull request merged**
