### PR TITLE
sql: Change to using a session variable instead of FORCE syntax for overriding zone configuration settings for MR databases and tables

### LINKED ISSUE #57668: sql: Only allow updates to zone configurations for multi-region tables under sql_safe_updates
Block updates to the zone configurations of multi-region tables if `sql_safe_updates` is not set.  Additionally, if the user preforms an operation which is about to overwrite a custom zone configuration, should we also require them to set sql_safe_updates?

### PR DESCRIPTION
**Pull request by ajstorm**
sql: Block zone config updates to multi-region tables

Block users from updating the zone configurations of multi-region
tables, without first having them set the session variable
`override_multi_region_zone_config` to true. We block updates to
multi-region table/partition/index zone configurations because we don't
want users to accidentally override the prescribed settings, leaving
them open to sub-optimal performance. Note that only the multi-region
fields of the zone configuration are blocked behind this variable. All
other fields (gc.ttlseconds, range_min/max_bytes, etc) can be updated
without overriding.

Release note (sql change): Block users from updating the zone
configurations of multi-region tables.

sql: Use session variable instead of FORCE to override zone configs

With #61499 we introduced new syntax (FORCE) to override setting the
zone configurations on multi-region databases. Upon further reflection,
it was decided that a session variable would be better suited to the
task. This commit pulls out the FORCE syntax and replaces it with the
use of override_multi_region_zone_config;

Release note (sql change): Revert the release notes on #61499.  We now
use a session variable (override_multi_region_zone_config) to override
the zone configuration on multi-region databases (and tables).

Resolves: #57668.

Note to reviewers: Please ignore the first commit, as it's being separately reviewed as part of #61889.  That commit was pulle out into a separate PR as it's a release blocker, and there was a need to get it in urgently.

### CODE REVIEW

**Comment by ajstorm** [comment]
Hold off on reviews.  Still resolving test case failures.

**Comment by otan** [comment]
from

```
[19:31:50][Test archive] ERROR: set-zone: runtime error: invalid memory address or nil pointer dereference
[19:31:50][Test archive] SQLSTATE: XX000
[19:31:50][Test archive] HINT: You have encountered an unexpected error.
```

looks like it's failing doing something here: https://github.com/cockroachdb/cockroach/blob/2d3c34a5a6a75be50a5b8feec4ed65d4f1cdb2a3/pkg/cli/initial_sql.go#L97

**Comment by ajstorm** [comment]
Thx.  Debugger FTW.  There was a null pointer exception.

**Comment by otan** [comment]
>  null pointer exception

this ain't java :P

**Comment by ajstorm** [comment]
gah!  I come from the land of C.  It's NULL there too.

**Comment by ajstorm** [comment]
RFAL now.  Only one testcase failure remaining, which I'm hoping to resolve in the morning.

**Review by otan — APPROVED** [review]
> Reviewed 11 of 11 files at r1, 14 of 14 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62008)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @arulajmani)

___
*[pkg/ccl/multiregionccl/regional_by_row_test.go, line 550 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62008#-MVtIyOVC1VyoAvfRxvw:-MVtIyOVC1VyoAvfRxvx:b6x5q3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c38b12aa53a8ff7f2d84c721269066b85cbd54e/pkg/ccl/multiregionccl/regional_by_row_test.go#L550)):*
> ```Go
> 	testutils.SucceedsSoon(t, func() error {
> 		_, err = sqlDB.Exec(`BEGIN;
>   SET override_multi_region_zone_config = true;
> ```

nit: indentation

**Comment by ajstorm** [comment]
TFTR!

bors r=otan

**Comment by ajstorm** [comment]
bors r-

Just noticed the bazel failure...

**Comment by ajstorm** [comment]
TFTR!

bors r=otan

**Pull request merged**
