### PR TITLE
roachpb: refine Transaction proto cloning

### LINKED ISSUE #35803: Panic in MarshalTo(0xc13312b400, 0xc1541c14ec, 0x13, 0x13, 0x15, 0x2, 0x11)
I hit this on a 7 node 36 cluster running tpc-c 10k on master v19.1.0-beta.20190304-458-g70e3468

```
* ERROR: [n4,client=172.31.31.59:43580,user=root,txn=67663fee] a panic has occurred!
*
runtime error: index out of range

goroutine 43064141 [running]:
runtime/debug.Stack(0x39db080, 0xc112e8c390, 0xc000000003)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x39db080, 0xc112e8c390, 0xc0001ab300, 0x2e831e0, 0x569d210, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:212 +0xa6
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc000372090, 0x39db080, 0xc112e8c390)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:183 +0xe4
panic(0x2e831e0, 0x569d210)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/roachpb.(*ScanRequest).MarshalTo(0xc13312b400, 0xc1541c14ec, 0x13, 0x13, 0x15, 0x2, 0x11)
	/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:10185 +0x17d
github.com/cockroachdb/cockroach/pkg/roachpb.(*RequestUnion_Scan).MarshalTo(0xc0b74b3328, 0xc1541c14ea, 0x15, 0x15, 0xf4f31e, 0xc0b74b3328, 0x17)
	/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:13287 +0xdf
github.com/cockroachdb/cockroach/pkg/roachpb.(*RequestUnion).MarshalTo(0xc153344838, 0xc1541c14ea, 0x15, 0x15, 0x17, 0xca, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:13188 +0x73
github.com/cockroachdb/cockroach/pkg/roachpb.(*BatchRequest).MarshalTo(0xc027b50f80, 0xc1541c1420, 0xdf, 0xdf, 0xdf, 0xdf, 0x323a3e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:14600 +0x246
github.com/cockroachdb/cockroach/pkg/roachpb.(*BatchRequest).Marshal(0xc027b50f80, 0x323a3e0, 0xc027b50f80, 0x7fb509a2d278, 0xc027b50f80, 0xc12d8fa301)
	/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:14575 +0x7f
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/encoding/proto.codec.Marshal(0x323a3e0, 0xc027b50f80, 0xc0d04d02e0, 0x3, 0xc0000ab470, 0xc0000ab400, 0x7fb50ab7c7f0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/encoding/proto/proto.go:70 +0x19c
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.encode(0x7fb50aa1ed38, 0x5b31a68, 0x323a3e0, 0xc027b50f80, 0xc017624870, 0x3a06e60, 0x39dbdc0, 0x6, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/rpc_util.go:487 +0x5e
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*csAttempt).sendMsg(0xc183977930, 0x323a3e0, 0xc027b50f80, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:482 +0xca
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*clientStream).SendMsg(0xc027b51000, 0x323a3e0, 0xc027b50f80, 0xc000b04600, 0x32b2f93)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:403 +0x43
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.invoke(0x39db080, 0xc112e8c390, 0x32b2f93, 0x21, 0x323a3e0, 0xc027b50f80, 0x318bfe0, 0xc04003c4d0, 0xc000b04600, 0xc0052d4400, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/call.go:75 +0xfe
github.com/cockroachdb/cockroach/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingClientInterceptor.func1(0x39db080, 0xc112e8c390, 0x32b2f93, 0x21, 0x323a3e0, 0xc027b50f80, 0x318bfe0, 0xc04003c4d0, 0xc000b04600, 0x33de350, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/client.go:47 +0xb49
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*ClientConn).Invoke(0xc000b04600, 0x39db080, 0xc112e8c390, 0x32b2f93, 0x21, 0x323a3e0, 0xc027b50f80, 0x318bfe0, 0xc04003c4d0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/call.go:35 +0x109
github.com/cockroachdb/cockroach/pkg/roachpb.(*internalClient).Batch(0xc1062bf2e0, 0x39db080, 0xc112e8c390, 0xc027b50f80, 0x0, 0x0, 0x0, 0xc112e8c390, 0x2, 0x39db080)
	/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:9324 +0xd2
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).sendBatch(0xc017624810, 0x39db080, 0xc112e8c390, 0x2, 0x39ae740, 0xc1062bf2e0, 0x0, 0x0, 0x200000002, 0x2, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:199 +0x126
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext(0xc017624810, 0x39db080, 0xc112e8c390, 0x0, 0x0, 0x200000002, 0x2, 0x7a89, 0x0, 0xc0d9a72d00, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:168 +0x130
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendToReplicas(0xc0009667e0, 0x39db080, 0xc112e8c390, 0xc000966830, 0x7a89, 0xc0e01999f0, 0x3, 0x3, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:1365 +0x2d3
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendRPC(0xc0009667e0, 0x39db080, 0xc112e8c390, 0x7a89, 0xc0e01999f0, 0x3, 0x3, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:416 +0x244
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendSingleRange(0xc0009667e0, 0x39db080, 0xc112e8c390, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0d9a72d00, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:496 +0x221
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendPartialBatch(0xc0009667e0, 0x39db080, 0xc112e8c390, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0d9a72d00, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:1141 +0x322
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendPartialBatchAsync.func1(0x39db080, 0xc112e8c390)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:1063 +0x175
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunLimitedAsyncTask.func1(0xc000372090, 0x39db080, 0xc112e8c390, 0x32bec16, 0x24, 0xc000a342a0, 0x3a10ae0, 0xc0003a7f60, 0xc0358f1960)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:385 +0x110
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunLimitedAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:379 +0x23a
```

~~I'm pretty sure it's different than https://github.com/cockroachdb/cockroach/issues/34241 because the portion after MarshalTo is different.~~

[cockroach.log](https://github.com/cockroachdb/cockroach/files/2972730/cockroach.log)

### PR DESCRIPTION
**Pull request by nvb**
Fixes #35803.

This PR includes the final two commits from #35719.

> By making Transaction.ObservedTimestamps immutable (which it almost already was), we can prohibit all interior mutability of references within Transaction, give it value semantics, and eliminate the distinction between "shallow" and "deep" object cloning. This reduces the cost of a clone to a single straightforward allocation and makes working with the object easier to think about.

cc. @tbg

### CODE REVIEW

**Review by tbg — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 30 of 30 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35762)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by tbg** [comment]
TIL of "Draft PRs". Sounds useful.

**Comment by nvanbenschoten** [comment]
Looks like a build flake. One more time.

bors r+

**Comment by nvanbenschoten** [comment]
Merge skew. Fixed.

bors r+

**Pull request merged**
