### PR TITLE
sql: add sequence option info for identity columns under information_schema

### LINKED ISSUE #82064: sql: identity information under information_schema.columns is inconsistent with postgres
**Describe the problem**
The table `information_schema.columns` should reflect the information about an identity column and the underlying sequence information.

**To Reproduce**
cockroach:
```sql
CREATE TABLE t (
  id INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 4294967296),
  PRIMARY KEY (id)
);

=> select identity_start, identity_increment, identity_maximum, identity_minimum, identity_cycle from information_schema.columns where table_name = 't' and column_name='id';
 identity_start | identity_increment | identity_maximum | identity_minimum | identity_cycle 
----------------+--------------------+------------------+------------------+----------------
                |                    |                  |                  |  
(1 row)
```
postgres:
```sql
=> CREATE TABLE t (
  id INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 4294967296),
  PRIMARY KEY (id)
);

=> select identity_start, identity_increment, identity_maximum, identity_minimum, identity_cycle from information_schema.columns where table_name = 't' and column_name='id';
 identity_start | identity_increment |  identity_maximum   | identity_minimum | identity_cycle 
----------------+--------------------+---------------------+------------------+----------------
 4294967296     | 1                  | 9223372036854775807 | 1                | NO 
(1 row)
```
**Expected behavior**
The above select statement should return the information about the sequence

**Environment:**
 - CockroachDB version: v21.2.11
 - Server OS: Linux
 - Client app: DataGrip

Jira issue: CRDB-16195
Epic CRDB-14049

### LINKED ISSUE #83208: sql: add a helper parser function for sequence options stored in a descriptor
Currently, the sequence options passed to a `GENERATED AS IDENTITY` are saved as a string in the descriptor, which makes it hard to extract the specific sequence info such as `START`, `INCREMENT` of this identity column, and hard to solve issues such as https://github.com/cockroachdb/cockroach/issues/82064. It should ~be saved as a dedicated type such as `TableDescriptor_SequenceOpts` but for `ColumnDescriptor`~ have an easy-to-use function for parsing these options.

Jira issue: CRDB-16921

### PR DESCRIPTION
**Pull request by ZhouXing19**
Previously, for a column created with the `GENERATED ... AS IDENTITY
(seq_options)` syntax, the info for the sequence option is not saved in the
information schema.

This commit is to fix it. We parse the sequence options saved as a string in the
the descriptor, so that it's much easier to extract specific options such as
sequence's start value or increment size.

To make sure that we get the same sequence option to generate
the sequence, we reuse `assignSequenceOptions()` by breaking it into several
helper functions.

fixes https://github.com/cockroachdb/cockroach/issues/82064
fixes https://github.com/cockroachdb/cockroach/issues/83208

Release note (sql): add sequence option info for identity columns under
information_schema

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84034)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)

___
*[`pkg/sql/information_schema.go` line 481 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6TiU6uD431WxCI0oA_:-N6TiU6uD431WxCI0oAa:bft3oc7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3c4e6fc1adf7355b3e48d74b1735f86d16dda54/pkg/sql/information_schema.go#L481)):*
> ```Go
> 				}
> 
> 				var identityStart, identityIncrement, identityMax, identityMin tree.DString
> ```

nit: the type here can be `*tree.DString`
___
*[`pkg/sql/information_schema.go` line 484 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6TiYJI42xT8ZUpzmWp:-N6TiYJI42xT8ZUpzmWq:b-djtk3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3c4e6fc1adf7355b3e48d74b1735f86d16dda54/pkg/sql/information_schema.go#L484)):*
> ```Go
> 				generatedAsIdentitySeqOpt := column.GetGeneratedAsIdentitySequenceOption()
> 				if generatedAsIdentitySeqOpt != nil {
> 					identityStart = *tree.NewDString(strconv.FormatInt(generatedAsIdentitySeqOpt.Start, 10))
> ```

nit: with the above comment, we won't need to dereference everything with `*`, which will avoid having to copy the string contents.
___
*[`pkg/sql/catalog/tabledesc/column.go` line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6TjZmx5bizYsx6VNHm:-N6TjZmx5bizYsx6VNHn:bi7c6fp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3c4e6fc1adf7355b3e48d74b1735f86d16dda54/pkg/sql/catalog/tabledesc/column.go#L252)):*
> ```Go
> // GetGeneratedAsIdentitySequenceOption returns the column's `GENERATED AS
> // IDENTITY` sequence option if it exists, empty string otherwise.
> func (w column) GetGeneratedAsIdentitySequenceOption() *descpb.TableDescriptor_SequenceOpts {
> ```

nit: this should return an error as a second argument, and also the comment needs to be updated

also i wonder if the `planner` needs to be passed in here
___
*[`pkg/sql/catalog/tabledesc/column.go` line 258 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6TjUhUAqcQZWZqwE-Q:-N6TjUhUAqcQZWZqwE-R:bb2qboa) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3c4e6fc1adf7355b3e48d74b1735f86d16dda54/pkg/sql/catalog/tabledesc/column.go#L258)):*
> ```Go
> 	seqOpts, err := transformStringToSeqOption(*w.desc.GeneratedAsIdentitySequenceOption)
> 	if err != nil {
> 		return nil
> ```

nit: this should return err
___
*[`pkg/sql/catalog/tabledesc/column.go` line 267 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6TkCs80KijZ3-nKnOq:-N6TkCs80KijZ3-nKnOr:b2ap7s7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3c4e6fc1adf7355b3e48d74b1735f86d16dda54/pkg/sql/catalog/tabledesc/column.go#L267)):*
> ```Go
> // We don't do extra check for the values following the keywords, since they
> // should have been checked via sql.go.
> func transformStringToSeqOption(s string) (*descpb.TableDescriptor_SequenceOpts, error) {
> ```

nit: perhaps this can be named `parseSequenceOpts` 
___
*[`pkg/sql/catalog/tabledesc/column.go` line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6TkfY84p5KSdjdWY6_:-N6TkfY84p5KSdjdWY6a:b-ujt04x) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3c4e6fc1adf7355b3e48d74b1735f86d16dda54/pkg/sql/catalog/tabledesc/column.go#L271)):*
> ```Go
> 	arr := strings.Fields(strings.ToUpper(s))
> 	i := 0
> 	for i < len(arr) {
> ```

instead of this, i wonder if we can re-use the original SQL parser.


what if we do something like `parser.ParseOne("CREATE SEQUENCE fake_name " + s)`

then use a type assertion to turn the result into `*tree.CreateSequence`

then we can use the existing `assignSequenceOptions` function. 

overall, it seems like that would be a less invasive change
___
*[`pkg/sql/types/types.go` line 2792 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6Tm-Sn7Bye8YIv6FjO:-N6Tm-So6mRTTBc3cRiJ:b-pcyorp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3c4e6fc1adf7355b3e48d74b1735f86d16dda54/pkg/sql/types/types.go#L2792)):*
> ```Go
> 	case "int2", "smallint":
> 		return Int2
> 	case "int4", "integer":
> ```

i don't think this is correct if `default_int_size` is set to `8` (which is the default)
___
*[`pkg/sql/types/types.go` line 2794 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6TlvNb1t5JcLUXez-w:-N6TlvNb1t5JcLUXez-x:b-pezggi) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3c4e6fc1adf7355b3e48d74b1735f86d16dda54/pkg/sql/types/types.go#L2794)):*
> ```Go
> 	case "int4", "integer":
> 		return Int4
> 	case "int8", "bigint", "int64":
> ```

nit: i don't think `int64` is valid here
___
*[`pkg/sql/types/types.go` line 2797 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6TmA2U-r0V7woy_SGM:-N6TmA2U-r0V7woy_SGN:b-oo1hbq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3c4e6fc1adf7355b3e48d74b1735f86d16dda54/pkg/sql/types/types.go#L2797)):*
> ```Go
> 		return Int
> 	default:
> 		panic(fmt.Sprintf("unknown string %s for conversion to integet type", s))
> ```

nit: integer is misspelled

**Review by ZhouXing19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84034)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)

___
*[`pkg/sql/information_schema.go` line 481 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6TiU6uD431WxCI0oA_:-N6xu0V45G54ZKqnZ8rk:b-5yiumw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3c4e6fc1adf7355b3e48d74b1735f86d16dda54/pkg/sql/information_schema.go#L481)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: the type here can be `*tree.DString`
</blockquote></details>

I don't think so, seems that it will cause the `nil pointer dereference` if `generatedAsIdentitySeqOpt == nil`.
___
*[`pkg/sql/catalog/tabledesc/column.go` line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6TjZmx5bizYsx6VNHm:-N6xuEol6Z00kW7ki5Hd:b-f9tt29) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3c4e6fc1adf7355b3e48d74b1735f86d16dda54/pkg/sql/catalog/tabledesc/column.go#L252)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: this should return an error as a second argument, and also the comment needs to be updated

also i wonder if the `planner` needs to be passed in here
</blockquote></details>

Updated the returned types and the comments. 
I don't think we need planner here. The planner is only used to get the sequence owner. We don't need this info in the information schema table.
___
*[`pkg/sql/catalog/tabledesc/column.go` line 258 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6TjUhUAqcQZWZqwE-Q:-N6xulnS6E9NxXOG9gN7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3c4e6fc1adf7355b3e48d74b1735f86d16dda54/pkg/sql/catalog/tabledesc/column.go#L258)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: this should return err
</blockquote></details>

Done.
___
*[`pkg/sql/catalog/tabledesc/column.go` line 267 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6TkCs80KijZ3-nKnOq:-N6xuolg7C37WzDtRQWE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3c4e6fc1adf7355b3e48d74b1735f86d16dda54/pkg/sql/catalog/tabledesc/column.go#L267)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: perhaps this can be named `parseSequenceOpts` 
</blockquote></details>

Done.
___
*[`pkg/sql/catalog/tabledesc/column.go` line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6TkfY84p5KSdjdWY6_:-N6xupQ-BwvA4-s-pR6t:b-frbtx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3c4e6fc1adf7355b3e48d74b1735f86d16dda54/pkg/sql/catalog/tabledesc/column.go#L271)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

instead of this, i wonder if we can re-use the original SQL parser.


what if we do something like `parser.ParseOne("CREATE SEQUENCE fake_name " + s)`

then use a type assertion to turn the result into `*tree.CreateSequence`

then we can use the existing `assignSequenceOptions` function. 

overall, it seems like that would be a less invasive change
</blockquote></details>

Yup good idea, changed it to `parser.ParseOne`. I incline to use the new `AssignSequenceOptions` function here because we don't need owner info, so no need to pass in the planner. 
___
*[`pkg/sql/types/types.go` line 2792 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6Tm-Sn7Bye8YIv6FjO:-N6xvJma24ZFIg4tl08y:bwmqlwt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3c4e6fc1adf7355b3e48d74b1735f86d16dda54/pkg/sql/types/types.go#L2792)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i don't think this is correct if `default_int_size` is set to `8` (which is the default)
</blockquote></details>

Deleted the whole function since we're using `parse.ParseOne()` now.

**Review by rafiss — CHANGES_REQUESTED** [review]
just had small nits

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-:-N6yYpbN2tLbeDAbHwNl:bzc6lh3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)

___
*[`pkg/sql/information_schema.go` line 481 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6TiU6uD431WxCI0oA_:-N6yT9Fw-IGcH_JZ84i1:b5uai9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3c4e6fc1adf7355b3e48d74b1735f86d16dda54/pkg/sql/information_schema.go#L481)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

I don't think so, seems that it will cause the `nil pointer dereference` if `generatedAsIdentitySeqOpt == nil`.
</blockquote></details>

hm, actually maybe this needs to be different. i think right now, this will cause these columns to default to the empty string, but they actually should default to `DNull`

so initialize them as
```
				identityStart := tree.DNull
				identityIncrement := tree.DNull
				identityMax := tree.DNull
				identityMin := tree.DNull
```

then you won't need the copy with `*tree.NewDString` and `&` below
___
*[`pkg/sql/sequence.go` line 483 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6yUbA89tSbpohhf_-Z:-N6yUbA89tSbpohhf_-_:b-vs9fot) ([raw file](https://github.com/cockroachdb/cockroach/blob/b27bb08522df58bc199be5c694de020b132e1a08/pkg/sql/sequence.go#L483)):*
> ```Go
> 	}
> 	if err := tabledesc.AssignSequenceOptions(opts, optsNode, setDefaults, existingType); err != nil {
> 		return pgerror.Wrap(err, pgcode.InvalidParameterValue, "")
> ```

nit: you shouldn't wrap with an empty string. so either use `pgerror.WithCandidateCode`, or populate the error string passed into `pgerror.Wrap`
___
*[`pkg/sql/sequence.go` line 486 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6yUlQf27-lBGAz-HEF:-N6yUlQf27-lBGAz-HEG:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/b27bb08522df58bc199be5c694de020b132e1a08/pkg/sql/sequence.go#L486)):*
> ```Go
> 	}
> 	if err := assignSequenceOwner(ctx, p, opts, optsNode, sequenceID, sequenceParentID); err != nil {
> 		return pgerror.Wrap(err, pgcode.InvalidParameterValue, "")
> ```

ditto
___
*[`pkg/sql/catalog/table_elements.go` line 376 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6yX_4s16pPDVs_4N8A:-N6yX_4s16pPDVs_4N8B:b-vqieof) ([raw file](https://github.com/cockroachdb/cockroach/blob/b27bb08522df58bc199be5c694de020b132e1a08/pkg/sql/catalog/table_elements.go#L376)):*
> ```Go
> 
> 	// GetGeneratedAsIdentitySequenceOption returns the column's `GENERATED AS
> 	// IDENTITY` sequence option if it exists, empty string otherwise.
> ```

nit it should say "or nil otherwise"
___
*[`pkg/sql/catalog/tabledesc/column.go` line 271 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6yYHA04tFfWQ3B4S79:-N6yYHA04tFfWQ3B4S7A:b-x0jp24) ([raw file](https://github.com/cockroachdb/cockroach/blob/b27bb08522df58bc199be5c694de020b132e1a08/pkg/sql/catalog/tabledesc/column.go#L271)):*
> ```Go
> // Note that this function is used to acquire the sequence option for the
> // information schema table, so it doesn't parse for the sequence owner info.
> func parseSequenceOpts(s string) (*descpb.TableDescriptor_SequenceOpts, error) {
> ```

i wonder if this parsing logic should live in the `schemaexpr` package instead. there could be a new sequence_options.go file there. what do you think makes sense?
___
*[`pkg/sql/catalog/tabledesc/column.go` line 583 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6yXjfp41oWrPAheDsI:-N6yXjfp41oWrPAheDsJ:b-9vqymm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b27bb08522df58bc199be5c694de020b132e1a08/pkg/sql/catalog/tabledesc/column.go#L583)):*
> ```Go
> 
> 	// Set the default integer type of a sequence.
> 	var integerType = types.Int
> ```

i wonder if this should be respecting `default_int_size`... well it looks like it  wasn't before, so could you just leave a `TODO (sql-exp)` comment saying that we should decide if we want to make this use default_int_size

**Review by ZhouXing19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84034)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/information_schema.go` line 481 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6TiU6uD431WxCI0oA_:-N7E3ucI4_buuVYoGRXH:b-c648x7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3c4e6fc1adf7355b3e48d74b1735f86d16dda54/pkg/sql/information_schema.go#L481)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm, actually maybe this needs to be different. i think right now, this will cause these columns to default to the empty string, but they actually should default to `DNull`

so initialize them as
```
				identityStart := tree.DNull
				identityIncrement := tree.DNull
				identityMax := tree.DNull
				identityMin := tree.DNull
```

then you won't need the copy with `*tree.NewDString` and `&` below
</blockquote></details>

Ah right, thanks for the explanation! Done.
___
*[`pkg/sql/information_schema.go` line 484 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6TiYJI42xT8ZUpzmWp:-N7E4-PFBQl8ZGmGdCAC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3c4e6fc1adf7355b3e48d74b1735f86d16dda54/pkg/sql/information_schema.go#L484)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: with the above comment, we won't need to dereference everything with `*`, which will avoid having to copy the string contents.
</blockquote></details>

Done.
___
*[`pkg/sql/sequence.go` line 483 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6yUbA89tSbpohhf_-Z:-N7E4KP68HAJ1b2So3nb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b27bb08522df58bc199be5c694de020b132e1a08/pkg/sql/sequence.go#L483)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: you shouldn't wrap with an empty string. so either use `pgerror.WithCandidateCode`, or populate the error string passed into `pgerror.Wrap`
</blockquote></details>

Done.
___
*[`pkg/sql/sequence.go` line 486 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6yUlQf27-lBGAz-HEF:-N7E4LX74_rgh6zSbUAc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b27bb08522df58bc199be5c694de020b132e1a08/pkg/sql/sequence.go#L486)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pkg/sql/catalog/table_elements.go` line 376 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6yX_4s16pPDVs_4N8A:-N7E4np0C2wvFtFTNAkL:by960dk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b27bb08522df58bc199be5c694de020b132e1a08/pkg/sql/catalog/table_elements.go#L376)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit it should say "or nil otherwise"
</blockquote></details>

Updated the comment.
___
*[`pkg/sql/catalog/tabledesc/column.go` line 271 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6yYHA04tFfWQ3B4S79:-N7E5Wv80reg9h4Upw-0:b-o8llv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b27bb08522df58bc199be5c694de020b132e1a08/pkg/sql/catalog/tabledesc/column.go#L271)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i wonder if this parsing logic should live in the `schemaexpr` package instead. there could be a new sequence_options.go file there. what do you think makes sense?
</blockquote></details>

Yeah I agree it makes more sense to move the parsing logic to `schemaexpr`. Also moved `AssignSequenceOptions` in this new `sequence_options.go` as well, to avoid dependency loop.
___
*[`pkg/sql/catalog/tabledesc/column.go` line 583 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6yXjfp41oWrPAheDsI:-N7ELM-s1FKjJPnFVXYB:b-8a2lr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b27bb08522df58bc199be5c694de020b132e1a08/pkg/sql/catalog/tabledesc/column.go#L583)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i wonder if this should be respecting `default_int_size`... well it looks like it  wasn't before, so could you just leave a `TODO (sql-exp)` comment saying that we should decide if we want to make this use default_int_size
</blockquote></details>

Yeah, nice catch! I also noticed this may be a bug for general sequences as well, so I made the issue https://github.com/cockroachdb/cockroach/issues/84554 to track. Also made a PR to fix it: https://github.com/cockroachdb/cockroach/pull/84555.

**Review by rafiss — APPROVED** [review]
nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-:-N7GvBYIEPqkm4szLmQu:b-j4xmku)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/catalog/tabledesc/column.go` line 583 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84034#-N6yXjfp41oWrPAheDsI:-N7GuFYt8-VyDXATIZ05:b-7m74ox) ([raw file](https://github.com/cockroachdb/cockroach/blob/b27bb08522df58bc199be5c694de020b132e1a08/pkg/sql/catalog/tabledesc/column.go#L583)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Yeah, nice catch! I also noticed this may be a bug for general sequences as well, so I made the issue https://github.com/cockroachdb/cockroach/issues/84554 to track. Also made a PR to fix it: https://github.com/cockroachdb/cockroach/pull/84555.  
</blockquote></details>

nice!

**Comment by ZhouXing19** [comment]
TFTR!
bors r=rafiss

**Pull request merged**
