### PR TITLE
misc cleanup on behalf of @tschottdorf

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8328)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8328#-:-KOPn0CkzxgrD3ewY7Bv:bnfp4nl)*

**Comment by arjunravinarayan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/store_test.go, line 1067 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8328#-KOPrr3EneRm2XwM_r4y:-KOPrr3EneRm2XwM_r4z:b-u35174) ([raw file](https://github.com/cockroachdb/cockroach/blob/1187dae7b01745bbdbbf925e44b57908d9cb18be/storage/store_test.go#L1067)):*
> ```Go
> 
> 	if r := store.LookupReplica(roachpb.RKey("0"), nil); r != r0 {
> 		t.Errorf("mismatched range %+v != %+v", r.Desc(), r0.Desc())
> ```

Shouldn't this set of `Desc` calls be using the inconsistent desc? Why did you change it back?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8328#-:-KOPs-Fd7t9W7spO_gN2:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[acceptance/monotonic_insert_test.go, line 69 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8328#-KOPruvha1Yw4fKLkczO:-KOPruvha1Yw4fKLkczP:b-fyprp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1187dae7b01745bbdbbf925e44b57908d9cb18be/acceptance/monotonic_insert_test.go#L69)):*
> ```Go
> 	for i, row := range r {
> 		prefix := "ok"
> 		if i > 0 && r.Less(i, i-1) {
> ```

should this be `!r.Less(i-1, i)`? (in case they are equal)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8328)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/store_test.go, line 1067 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8328#-KOPrr3EneRm2XwM_r4y:-KOQyPpv45egDuqStsx6:btt74t0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1187dae7b01745bbdbbf925e44b57908d9cb18be/storage/store_test.go#L1067)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Can you help me understand why it should be one or the other? I was just reverting the change because of an unanswered comment left on the original PR.
</details>
Even better, it should probably just use `%s` on `r` and `r1`. 

We should generally default to `Desc()` unless doing so risks a deadlock. I'd prefer to make `Replica.String()` the only caller of `InconsistentDesc()`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8328)*

**Comment by RaduBerinde** [comment]
*[acceptance/monotonic_insert_test.go, line 69 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8328#-KOPruvha1Yw4fKLkczO:-KORDhmHXHDWck0NITzx:b-z7hm2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/1187dae7b01745bbdbbf925e44b57908d9cb18be/acceptance/monotonic_insert_test.go#L69)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> This currently checks if `i` is less than `i-1`, and marks this row "bad" if it is. If they are equal, it will not be marked "bad".
</details>
The previous code marked it "bad" if they were equal. Equal rows meant `ok` was false (because `r.Less(i-1, i)` was false).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8328)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[acceptance/monotonic_insert_test.go, line 69 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8328#-KOPruvha1Yw4fKLkczO:-KORER1IUw55XamIspRG:b-jlna96) ([raw file](https://github.com/cockroachdb/cockroach/blob/1187dae7b01745bbdbbf925e44b57908d9cb18be/acceptance/monotonic_insert_test.go#L69)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> The previous code marked it "bad" if they were equal. Equal rows meant `ok` was false (because `r.Less(i-1, i)` was false).
</details>
I see. I don't think that was correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8328)*

**Comment by RaduBerinde** [comment]
*[acceptance/monotonic_insert_test.go, line 69 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8328#-KOPruvha1Yw4fKLkczO:-KOREk_-WRP22mQhnoYR:b-tzzsyz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1187dae7b01745bbdbbf925e44b57908d9cb18be/acceptance/monotonic_insert_test.go#L69)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I see. I don't think that was correct.
</details>
The test seems to be around strictly increasing stuff so I assume it expects strictly increasing rows. Anyway it looks like it explicitly verifies the number of distinct values so it should be ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8328)*

**Pull request merged**
