### PR TITLE
cli: productionize start-sql

### LINKED ISSUE #51138: cli: productionize start-sql
The SQL process started via `./cockroach mt start-sql` lacks many of the goodies the combined process has to offer, notably:

- [x] debug endpoints (pprof)
- [x] logging to files
- [ ] regular "runtime stats" output
- [x] automatic heap/goroutine dumps based on activity

Of initially lesser importance:

- [ ] signal handling (decent signal handling -> draining)

The code for all of these is there but is too `./cockroach start`-specific. We need to isolate it out one by one and provide them to both operations.

### PR DESCRIPTION
**Pull request by tbg**
Fixes #51138.

- server: prepare startSampleEnvironment for reuse
- cli: set up logging for start-sql
- server: sample environment on standalone SQL node

Release justification: see individual commits.
Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Second commit is a breaking change and is not suited for stability period.
The rest is LGTM

> Reviewed 1 of 1 files at r1, 5 of 5 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53890#-:-MGIpXg_2P2Px8dNdX10:bqphji0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/cli/start.go, line 1037 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53890#-MGIp5hs1cUXjKdEbyQN:-MGIp5hs1cUXjKdEbyQO:b-97zfny) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c8e6f88035c82caa19b7422eba775e347842fd9/pkg/cli/start.go#L1037)):*
> ```Go
> 			// If there were no stores (as is the case during `start-sql`),
> 			// use the location that would result from the default store.
> 			newDir = filepath.Join(server.DefaultStorePath, "logs")
> ```

That seems incorrect. 
Both `cockroach demo` and `cockroach start` have as a contract that they don't write stuff in directory locations outside of specified stores. If the user specifies only in-memory stores, then nothing gets written on the filesystem **unless the user passes --log-dir explicitly** (which we support and test)

Also between other things, the acceptance smoke test uses a read-only filesystem.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53890)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @nvanbenschoten)

___
*[pkg/cli/start.go, line 1037 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53890#-MGIp5hs1cUXjKdEbyQN:-MGJ4pxP6J-Q2Ajx9HhO:b-1elrki) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c8e6f88035c82caa19b7422eba775e347842fd9/pkg/cli/start.go#L1037)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

That seems incorrect. 
Both `cockroach demo` and `cockroach start` have as a contract that they don't write stuff in directory locations outside of specified stores. If the user specifies only in-memory stores, then nothing gets written on the filesystem **unless the user passes --log-dir explicitly** (which we support and test)

Also between other things, the acceptance smoke test uses a read-only filesystem.
</blockquote></details>

Good catch - the intention was not to change any behavior outside of `start-sql`. What I actually wanted was to do this only if there are *no* stores. PTAL

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53890)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @nvanbenschoten, and @tbg)

___
*[pkg/cli/start.go, line 1037 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53890#-MGIp5hs1cUXjKdEbyQN:-MGJ8fK67hfXEXKYXUka:b-d42ex1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c8e6f88035c82caa19b7422eba775e347842fd9/pkg/cli/start.go#L1037)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Good catch - the intention was not to change any behavior outside of `start-sql`. What I actually wanted was to do this only if there are *no* stores. PTAL
</blockquote></details>

The thing is `cockroach demo` explicitly sets `.Stores.Specs` to `nil` to disable logging.
See `demo_cluster.go` lines 77-81.

May I instead suggest a `if cmd == startSqlCmd` here maybe?

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53890)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @imjching, @knz, and @nvanbenschoten)

___
*[pkg/cli/start.go, line 1037 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53890#-MGIp5hs1cUXjKdEbyQN:-MGNUHbD2vKRl29Ac9oi:b-4xnd9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c8e6f88035c82caa19b7422eba775e347842fd9/pkg/cli/start.go#L1037)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

The thing is `cockroach demo` explicitly sets `.Stores.Specs` to `nil` to disable logging.
See `demo_cluster.go` lines 77-81.

May I instead suggest a `if cmd == startSqlCmd` here maybe?
</blockquote></details>

:thumbsup: actually I realized that by removing the diff here completely I got the behavior that I wanted (there was a default store). However, after talking to @imjching I decided to do what `cockroach demo` does and nil out that default spec, as it seems like a better default to log to stderr. This is because we're not initially expecting these processes to be handed storage suitable for logs.

**Review by knz — APPROVED** [review]
> Reviewed 2 of 6 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53890)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @imjching and @nvanbenschoten)

**Comment by tbg** [comment]
bors r=knz

**Pull request merged**
