### PR TITLE
kv: improve metrics descriptions

### PR DESCRIPTION
**Pull request by tbg**
See individual commits.

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
:lgtm: Very nice!

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69858#-:-Mj3IewD6K0fXOGCt7T5:b-kerl87)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/kv/kvserver/metrics.go, line 558 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69858#-Mj3FQOWB89pvfS3oFqo:-Mj3FQOWB89pvfS3oFqp:b-yg6d91) ([raw file](https://github.com/cockroachdb/cockroach/blob/f88c0d09ce7fd366ffb997cfdabb2f2cc3238a43/pkg/kv/kvserver/metrics.go#L558)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> This metric is misnamed: it measures the latency for *applying* a batch of
> committed Raft commands to a Replica state machine. This requires only
> non-durable I/O (except for replication configuration changes). Note that
> a "batch" in this context is really a sub-batch of the batch received for
> application during raft ready handling. The 'raft.process.applycommitted.latency'
> histogram may be more suitable in most cases.
> ```
</details>


I had to re-read this section, as well as the section on `applycommitted`, to understand how they differed and why this even exists. Consider clarifying this, e.g. by expanding this sentence as follows:

> The 'raft.process.applycommitted.latency' histogram may be more suitable in mose cases, as it measures the total latency across all sub-batches (i.e. the sum of `commandcommit.latency` for a complete batch).

Also, should we consider simply renaming/removing the metric, or do we try very hard not to do that? This one does seem fairly obscure.
___
*[pkg/kv/kvserver/metrics.go, line 565 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69858#-Mj3GtI52IQLtO2k6mku:-Mj3GtI52IQLtO2k6mkv:bvvoz7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f88c0d09ce7fd366ffb997cfdabb2f2cc3238a43/pkg/kv/kvserver/metrics.go#L565)):*
> ```
> 	// TODO(tbg): I think this metric skews low because we will often handle Readies
> 	// for which the result is that there is nothing to do. Do we want to change this
> 	// metric to only record ready handling when there is a Ready? That seems more
> ```

A noop datapoint is still a valid datapoint (there was a raft Ready, and it did nothing). Assuming the distinction is useful, and unless it's trivial to accurately exclude the noop values/bucket when querying, I'd add another metric specifically for ready loops that did work. It might be useful to map out what people actually use this for too, since it could e.g. be useful to adjust it for or group it by batch size or command type.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69858)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[pkg/kv/kvserver/metrics.go, line 558 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69858#-Mj3FQOWB89pvfS3oFqo:-MjUEDbs0EfX1TNq-lRF:btz3h38) ([raw file](https://github.com/cockroachdb/cockroach/blob/f88c0d09ce7fd366ffb997cfdabb2f2cc3238a43/pkg/kv/kvserver/metrics.go#L558)):*
Done.

> Also, should we consider simply renaming/removing the metric, or do we try very hard not to do that? This one does seem fairly obscure.

This is a good question. I don't think we have a good story about removing metrics. I am almost certain this one wouldn't cause any issues, but in general we always have to assume that someone out there has based their observability setup crucially on top of whatever metric we change/remove. Will leave as-is for now but generally agree that it would be good to rip metrics out.
___
*[pkg/kv/kvserver/metrics.go, line 565 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69858#-Mj3GtI52IQLtO2k6mku:-MjUEYUf4zMh9KlP8CJm:b-njyb9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f88c0d09ce7fd366ffb997cfdabb2f2cc3238a43/pkg/kv/kvserver/metrics.go#L565)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

> ```
> 	// TODO(tbg): I think this metric skews low because we will often handle Readies
> 	// for which the result is that there is nothing to do. Do we want to change this
> 	// metric to only record ready handling when there is a Ready? That seems more
> ```

A noop datapoint is still a valid datapoint (there was a raft Ready, and it did nothing). Assuming the distinction is useful, and unless it's trivial to accurately exclude the noop values/bucket when querying, I'd add another metric specifically for ready loops that did work. It might be useful to map out what people actually use this for too, since it could e.g. be useful to adjust it for or group it by batch size or command type.
</blockquote></details>

There was and there wasn't. The metric gets populated when ready handling for the replica was scheduled & is carried out. But whether there is a ready or not is only determined as part of the ready handling. Since the algorithm is roughly

```
while ready_scheduled() {
  rd, ok := checkReady()
  if !ok { break }
  if scheduleAgain := doSomething(rd); scheduleAgain { scheduleAgain() }
}
```

so we will by design *always* go into an extra ready loop at the end that then hits the `break`. If most replicas only "sporadically" do work, this means we have 50% no-op measurements. Since this is by design, I don't see find it useful to let it pollute the metrics, where it seems that we would want the latency histogram over loops that did any kind of work. And nobody ever cares about the histogram for executing a noop-ready, so having two histograms (histograms are expensive!) doesn't seem right either.

I'm going to leave this as-is for now, though.

**Review by erikgrinaker — APPROVED** [review]
> Reviewed 3 of 3 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69858)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

___
*[pkg/kv/kvserver/metrics.go, line 565 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69858#-Mj3GtI52IQLtO2k6mku:-MjUI_tJ909WXibGN5hj:baxih6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f88c0d09ce7fd366ffb997cfdabb2f2cc3238a43/pkg/kv/kvserver/metrics.go#L565)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

There was and there wasn't. The metric gets populated when ready handling for the replica was scheduled & is carried out. But whether there is a ready or not is only determined as part of the ready handling. Since the algorithm is roughly

```
while ready_scheduled() {
  rd, ok := checkReady()
  if !ok { break }
  if scheduleAgain := doSomething(rd); scheduleAgain { scheduleAgain() }
}
```

so we will by design *always* go into an extra ready loop at the end that then hits the `break`. If most replicas only "sporadically" do work, this means we have 50% no-op measurements. Since this is by design, I don't see find it useful to let it pollute the metrics, where it seems that we would want the latency histogram over loops that did any kind of work. And nobody ever cares about the histogram for executing a noop-ready, so having two histograms (histograms are expensive!) doesn't seem right either.

I'm going to leave this as-is for now, though.
</blockquote></details>

Got it, thanks for the nuance. I agree that those seem unnecessary.

**Comment by tbg** [comment]
bors r=erikgrinaker

**Pull request merged**
