### PR TITLE
kvserver: reenable splitting of snapshot sstables

### LINKED ISSUE #129026: roachtest: clearrange/checks=false failed
roachtest.clearrange/checks=false [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/16475262?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/16475262?buildTab=artifacts#/clearrange/checks=false) on master @ [575cdd4696dfcac8f311d1ea546683271102f73e](https://github.com/cockroachdb/cockroach/commits/575cdd4696dfcac8f311d1ea546683271102f73e):

```
(cluster.go:2473).Run: context canceled
(monitor.go:154).Wait: monitor failure: monitor user task failed: t.Fatal() was called
unexpected node event: n1: cockroach process for system interface died (exit code 134)
test artifacts and logs in: /artifacts/clearrange/checks=false/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=azure</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=16</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
/cc @cockroachdb/storage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*clearrange/checks=false.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-41335

### PR DESCRIPTION
**Pull request by itsbilal**
This change updates the snapshot strategy's sender side to iterate over points and ranges together, instead of only iterating on points first, then only ranges. This allows us to more efficiently split snapshot sstables on the receiver side. To avoid the need to add a version gate on the receiver side, we propagate a bool, RangeKeysInOrder, to the receiver which is a signal to it to enable sstable splits.

Fixes #129026.

Epic: none

Release note: None

### CODE REVIEW

**Review by aadityasondhi — APPROVED** [review]
lgtm but one question

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129088#-:-O4Qb9FA4tgKlhmHlL-Q:b-rmfly2)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @itsbilal)

___
*[`pkg/kv/kvserver/store_snapshot.go` line 196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129088#-O4QeDZF36XoixDkexi3:-O4QeDZF36XoixDkexi4:b-mn30tb) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c1e4e28c191e5799bdf9ab99e227fb561b66f93/pkg/kv/kvserver/store_snapshot.go#L196)):*
> ```Go
> 		skipClearForMVCCSpan: skipClearForMVCCSpan,
> 	}
> 	if !skipClearForMVCCSpan && rangeKeysInOrder {
> ```

Why is this not `!skipClearForMVCCSpan || rangeKeysInOrder`? I would think if either side is true we can do the splitting.

**Review by itsbilal — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129088#-:-O4QjV323Kpaqo-bWetP:b-814g8k)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi)

___
*[`pkg/kv/kvserver/store_snapshot.go` line 196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129088#-O4QeDZF36XoixDkexi3:-O4Qj2hI6QBwK4szi52U:blyx6id) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c1e4e28c191e5799bdf9ab99e227fb561b66f93/pkg/kv/kvserver/store_snapshot.go#L196)):*
<details><summary><i>Previously, aadityasondhi (Aaditya Sondhi) wrote…</i></summary><blockquote>

Why is this not `!skipClearForMVCCSpan || rangeKeysInOrder`? I would think if either side is true we can do the splitting.
</blockquote></details>

The reason is that `skipClearForMVCCSpan` means that we could see RangeKeyUnsets and RangeKeyDels (as well as internal RangeDels) as part of the snapshot sstable too, as that's the disaggregated storage fast-rebalance case. We don't do the hard work of fragmenting them all manually, so we just exclude that case completely from all splitting. Plus `addClearForMVCCSpan` gets messy (like the comment describes).

Not splitting for disagg is fine because those sstables are usually tiny anyway.

**Comment by itsbilal** [comment]
TFTR!

bors r=aadityasondhi

**Review by RaduBerinde — APPROVED** [review]
:lgtm:  Thanks for working on this!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129088#-:-O4RQT6a39wEYwDe-dcs:bkkumlq)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi and @itsbilal)

___
*[`pkg/kv/kvserver/store_snapshot.go` line 184 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129088#-O4RQLor9GA7dDg05s2o:-O4RQLos4657z0Ph_k8S:b-1rr1q5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef16081823d158902ac907cae52ee7d70b275c8d/pkg/kv/kvserver/store_snapshot.go#L184)):*
> ```Go
> 	sstChunkSize int64,
> 	skipClearForMVCCSpan bool,
> 	rangeKeysInOrder bool,
> ```

Consider adding a `CrdbTestBuild` assertion somewhere that verifies that range keys are really in order when the flag is true.

**Pull request merged**
