### PR TITLE
sql: reorganize and improve vectorized operator stats

### PR DESCRIPTION
**Pull request by RaduBerinde**
The current pattern with many protos implementing DistSQLSpanStats
doesn't work well if we want to add some aggregations at the logical
level (e.g. total rows scanned, max memory used across the distributed
instances of an operator).

Fortunately, the vectorized engine has a much simpler approach where
we use two protos.

This proposal moves further in that direction; it replaces the two
protos with a new one, in a new package `sql/execstats/execstatspb`.
The idea is that this single proto defines all possible stats; each
operator would populate a relevant subset.

Given this model, it's important to be able to distinguish between
zero and unset values. For integer values, a solution is to set the
proto value to (1 + the real value); to this end we introduce a type
`IntValue` that hides this annoying complication. Note that for time
values, we already have a reasonable assumption that any populated
duration is at least one nanosecond.

Going forward, my plan is to make all rowexec processors use this new
type as well, and then work with it directly in any new statistics
aggregation code.

This change also reworks the vectorized stats collectors; in
particular, we simplify the common code to allow the specific
implementation to deal with populating the right OperatorStats fields.
Also, the implementation types are no longer exported.

Release note: None

### CODE REVIEW

**Comment by asubiotto** [comment]
> This proposal moves further in that direction; it replaces the two
protos with a new one, in a new package sql/execstats/execstatspb.
The idea is that this single proto defines all possible stats; each
operator would populate a relevant subset.

What does this buy us? I'm on board with reducing the number of protos because it's unwieldy to aggregate rowexec stats, but in my opinion it's better to stop short of the extreme of putting everything in a single proto and instead do the same as vectorized and define multiple higher-level protos. For example, all operators that read from disk will output the same proto that has specific IO stats, buffering operators will output the same proto that has specific memory usage and possible temporary disk usage stats. This avoid the problem of determining which field is unset and is still manageable when aggregating statistics. What do you think?

**Review by RaduBerinde — COMMENTED** [review]
Hi Alfonso,

I think in either case it's still nice to be able to differentiate between zero and unset (e.g. error cases, maybe fast paths where we omit collecting some stats that are more expensive), and the solution here is pretty clean.

Other than that, what is the value of having multiple protos for various combinations? We would still need to handle each type and I'd venture a guess that there will be at least a handful of combinations, especially if we add more stats. If it's an efficiency concern, that's different (we could add a smaller subset that's enough for the common case if we find it necessary).

Note that the current state of vectorized is not great. We have `VectorizedStats` and `VectorizedInboxStats` which includes the former. So `VectorizedInboxStats` is basically just like the proto I'm proposing, which contains everything.

That said, I agree that there is value in grouping the types of stats into logical buckets. I am splitting all the stats up into submessages. It will take some work to update the collectors to set the correct stats for the various cases (we are currently overloading things like `Time` and `BytesRead`). This will also allows us to reconsider the single vs multi-proto decision if necessary without a ton of work.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-:-MLj0oHkBy0iSzDVn0Vb:b-teh1rp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @cathymw, and @yuzefovich)

**Comment by RaduBerinde** [comment]
Another idea would be to define a union for all groups of stats, and have the proto message contain an arbitrary number of those (a `repeated` field). That seems nice, but I'm a bit worried about the overhead of having each group be a different object in memory.

**Review by asubiotto — CHANGES_REQUESTED** [review]
OK, I like the logical separation of protobufs, which is why I was asking @cathymw to do some further refactoring of the protobufs, but I think I'm convinced to put all the stats in a single proto for easier aggregation. This probably needs a version bump, right?

Thanks for taking the time to do this. @cathymw we should probably hold off adding stat aggregations until this is in.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-:-MLlkHl5EcaKsRKtCoT9:b-skvzww)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @cathymw, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/colexec/stats.go, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLlnMu_0ygCr2T-iBU5:-MLlnMu_0ygCr2T-iBU6:b-w3t67d) ([raw file](https://github.com/cockroachdb/cockroach/blob/8451902770bacfa23b9f7d91ac569c24f3aa44d5/pkg/sql/colexec/stats.go#L151)):*
> ```Go
> 	idTagKey string,
> 	inputWatch *timeutil.StopWatch,
> 	latency int64,
> ```

The `latency` seems to be ignored now.
___
*[pkg/sql/colexec/stats.go, line 248 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLlnZf8AdwEv7dWp_Kj:-MLlnZf8AdwEv7dWp_Kk:b-dsdkty) ([raw file](https://github.com/cockroachdb/cockroach/blob/8451902770bacfa23b9f7d91ac569c24f3aa44d5/pkg/sql/colexec/stats.go#L248)):*
> ```Go
> 
> // OutputStats outputs the vectorized stats collected by nvsc into ctx.
> func (nvsc *NetworkVectorizedStatsCollector) OutputStats(
> ```

We can probably remove `NetworkVectorizedStatsCollector` since it seems to be exactly the same as the base now. cc @cathymw, what do you think?
___
*[pkg/sql/execstats/execstatspb/operator_stats.proto, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLloMEX7TCDicKyJE9C:-MLloMEX7TCDicKyJE9D:bm02jgy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8451902770bacfa23b9f7d91ac569c24f3aa44d5/pkg/sql/execstats/execstatspb/operator_stats.proto#L22)):*
> ```protobuf
> // that the particular stat is not available.
> message OperatorStats {
>   int32 operator_id = 1 [(gogoproto.customname) = "OperatorID"];
> ```

This can also be the stream ID, right?
___
*[pkg/sql/execstats/execstatspb/operator_stats.proto, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLlofGZ3fSMJwxHeSKZ:-MLlofGZ3fSMJwxHeSK_:b-k4y8yk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8451902770bacfa23b9f7d91ac569c24f3aa44d5/pkg/sql/execstats/execstatspb/operator_stats.proto#L25)):*
> ```protobuf
> 
>   // num_batches is the number of batches that this stats collector observed its
>   // operator to output.
> ```

cc @yuzefovich this is the same comment as the original proto, but it's wrong, right? Should be the same as `num_tuples` (i.e. "the number of batches that this stats collector received from its input")
___
*[pkg/sql/execstats/execstatspb/operator_stats.proto, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLlor1v4eZ5wf8y-Fmp:-MLlor1v4eZ5wf8y-Fmq:b-1q155g) ([raw file](https://github.com/cockroachdb/cockroach/blob/8451902770bacfa23b9f7d91ac569c24f3aa44d5/pkg/sql/execstats/execstatspb/operator_stats.proto#L32)):*
> ```protobuf
>   uint64 num_tuples = 3 [(gogoproto.customtype) = "IntValue", (gogoproto.nullable) = false];
> 
>   google.protobuf.Duration io_time = 4 [(gogoproto.customname) = "IOTime",
> ```

This and `exec_time` probably deserve comments.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56400)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @cathymw, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/explain_analyze_plans, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLlpJV29U17s19VP6u1:-MLlpJV29U17s19VP6u2:byyzzpf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8451902770bacfa23b9f7d91ac569c24f3aa44d5/pkg/sql/logictest/testdata/logic_test/explain_analyze_plans#L63)):*
> ```
> SELECT url FROM [EXPLAIN ANALYZE (DISTSQL) SELECT kv.k, avg(kw.k) FROM kv JOIN kw ON kv.k=kw.k GROUP BY kv.k]
> ----
> https://cockroachdb.github.io/distsqlplan/decode.html#eJzUWF1v4jgUfd9fYfmp1YQJdgKlSCPBzHZXjGjo8iFtd4SqtPFSBENYJ7RbVf3vo0CrQtL4xsRx4A1Ccs89vs45Pjzj4L85buLBRffi2xCt-Bz90e9doh8Xf1912x0HtZ129_qfC3Tye2cwHPzVPUWvt84ePs8M5D5MTmaPn2enm8dmD-h7r-Og2SPqOetb0BcU_Y7-7PdGV-jr9friGBt44XvMcX-yADd_YIINTLGBLWxgGxu4hscGXnL_jgWBz6NbntcPdLz_cbNq4OliuQqjy2MD3_mc4eYzDqfhnOEmHrq3c9Znrse4WcUG9ljoTudrmNlDa8mnP13-hA08WLqLoIkqZgTcW4VN1IraCFfLOQuQvwqX0bXo0u1TyALEmes1UQN9xQbm_uPbBYLHLwbe3L5p9K2R2yd07wb3uy20ovvHBg5Cd8Jwk7wY-zGrx5g9JpmZpFxuNJXbex2fe4wzL17nUwSc6a4PlumS8Qn77k8XjJsktgPm7N_wpEU-nX7h08n95uP7Ehktmm2VdpflnbIlM872ZMLZxA19bpJaYiUN3Nuwfp1d27m-cXrDG2fU7Z60SNT1YHR50qLRp2-9kTN8_SzdvtxU7XxTFa8DreZbh8Ho8qYTrYQVfeuzhcf4erCoRc2WlW-4tQzMV4uPuH9I2_Er_tKkscnH-qvF-rOrggbrOw2S7GJCYJk0acW0DkYoJbidZRDKkrnRVG4ahZKUKJTAOLeFsn6kQik9VUAoydEIJc3-rtIMOmRVTPtgdEiCWyODDpXMjaZy06hDtEQdAsa5rUNnR6pD0lMFdIgejQ5Z2d9VK4MO2RWzdjA6JMHtPIMOlcyNpnLTqENWiToEjHNbhxpHqkPSUwV0yDoaHbKzv6t2Bh2qVQ5GhSSY1WAVqpgEuQsPEeSH94wfjB7Z5eiRXaIeAYPd1qPzI9Uj6akCemQfjR4B_1L2WbD0FwGL_aH1ceVqtCzMm7DNMgb-it-xK-7frWE2X3vr59aJ2GNBuPmVbr50Fm8_BaG7rr1D6vXPL5nCjcyFdwSjKotDrFSgvcRKClsXSZpOUhaISGwHKrMdxIUbmQvnIxDbDlTtdgCwdZGk6SRlgWgcqLoNtItTjT9sCbu087yYiUbFWKSq7AUBgGqagKguRlQdI1u4mWI48YdrwodpfXcryihTXZEDQvTFONm9QrKwwAHVMlBod8BICvX0M0UOCHEU42T3CsnCAgdUy0Ch3QEjKdTTG0LdORc74PmeDii7QGIcgfvtY7UAmDq_EAMpdEAASB0jkjjHiyxQ8eFU5mifi6TMUb9AIAnjky6dTkLDpBSmvcT5viCzA4AUJiMxkIT7SZdOJ6FiTwCTUufqJJEHdjSK2GLLI4lTfkGeBwApjHwQUi7ZlkVTaHsQkkLfE6e3Yn1PV74DgIq1DG0ZEELKkWOhSSkkoSvkAUDFWoa2IAgh5Qiz0KQUkhAnPQJEPaIr6wFAKn1PW9IDkASet5fDast7tMS8R_fNe8Vjq4uAAJBC34OQtHGSsMFk6X3znoo9oSsCAkAKfQ9C0sZJwgaTpcV5jwJ5j-rKewCQQt-DkBT6g7asByGpzbBUZ94bv_z2KwAA__8X-OX3
> ```

These explain analyze plans shouldn't change I think, we're not adding/removing stats and it seems like this new version is missing some information (e.g. batches output)

**Comment by RaduBerinde** [comment]
TFTRs, I am working on a new version which also reworks the collectors (and I have rebased on top of #56144 and kept that functionality, so that PR can merge).

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56400)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @cathymw, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/execstats/execstatspb/operator_stats.proto, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLlofGZ3fSMJwxHeSKZ:-MLn1J8IA7x7BlEZ0XRB:b-htwhgt) ([raw file](https://github.com/cockroachdb/cockroach/blob/8451902770bacfa23b9f7d91ac569c24f3aa44d5/pkg/sql/execstats/execstatspb/operator_stats.proto#L25)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

cc @yuzefovich this is the same comment as the original proto, but it's wrong, right? Should be the same as `num_tuples` (i.e. "the number of batches that this stats collector received from its input")
</blockquote></details>

Hm, I think both comments are correct in some sense since we're wrapping each operator with the stats collector (i.e. "its operator" = "its input"). I think the wording could be clarified to make sure that "its operator" = "the operator wrapped by this stats collector".

**Review by RaduBerinde — COMMENTED** [review]
Ok, PTAL (especially at the protos).

There are some changes in the plans but they're mostly in the ordering of the stats. In some cases we were adding a manufactured "bytes read" stat even when it wouldn't have showed up outside of a test.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-:-MLnR19A7lA5lGJExGdg:b-ioqkim)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @cathymw)

___
*[pkg/sql/colexec/stats.go, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLlnMu_0ygCr2T-iBU5:-MLnA68k7oTVT0Q-GOC1:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/8451902770bacfa23b9f7d91ac569c24f3aa44d5/pkg/sql/colexec/stats.go#L151)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

The `latency` seems to be ignored now.
</blockquote></details>

Fixed.
___
*[pkg/sql/colexec/stats.go, line 248 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLlnZf8AdwEv7dWp_Kj:-MLnA6uy-2gpUQ0c6vxQ:blav163) ([raw file](https://github.com/cockroachdb/cockroach/blob/8451902770bacfa23b9f7d91ac569c24f3aa44d5/pkg/sql/colexec/stats.go#L248)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

We can probably remove `NetworkVectorizedStatsCollector` since it seems to be exactly the same as the base now. cc @cathymw, what do you think?
</blockquote></details>

I refactored it, we do need a separate one because of the inbox-specific stats.
___
*[pkg/sql/execstats/execstatspb/operator_stats.proto, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLloMEX7TCDicKyJE9C:-MLnAJpH2hAlSU1RgpUd:baxjo9s) ([raw file](https://github.com/cockroachdb/cockroach/blob/8451902770bacfa23b9f7d91ac569c24f3aa44d5/pkg/sql/execstats/execstatspb/operator_stats.proto#L22)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This can also be the stream ID, right?
</blockquote></details>

I was thinking that all falls under "operator" as far as this package is concerned.. I added a comment. Maybe there's a better name than "operator"?
___
*[pkg/sql/execstats/execstatspb/operator_stats.proto, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLlofGZ3fSMJwxHeSKZ:-MLnAYUD4EeEYrb39lHb:bw8qmx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8451902770bacfa23b9f7d91ac569c24f3aa44d5/pkg/sql/execstats/execstatspb/operator_stats.proto#L25)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Hm, I think both comments are correct in some sense since we're wrapping each operator with the stats collector (i.e. "its operator" = "its input"). I think the wording could be clarified to make sure that "its operator" = "the operator wrapped by this stats collector".
</blockquote></details>

Reworked these. There shouldn't be any mention of collectors in here.
___
*[pkg/sql/execstats/execstatspb/operator_stats.proto, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLlor1v4eZ5wf8y-Fmp:-MLnIHoe9nA0txqZbE64:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8451902770bacfa23b9f7d91ac569c24f3aa44d5/pkg/sql/execstats/execstatspb/operator_stats.proto#L32)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This and `exec_time` probably deserve comments.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/explain_analyze_plans, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLlpJV29U17s19VP6u1:-MLnIINA5TxR-eZnYVRS:b-ger4tl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8451902770bacfa23b9f7d91ac569c24f3aa44d5/pkg/sql/logictest/testdata/logic_test/explain_analyze_plans#L63)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

These explain analyze plans shouldn't change I think, we're not adding/removing stats and it seems like this new version is missing some information (e.g. batches output)
</blockquote></details>

I was clearing the non-deterministic stats. But I agree that it's important to show the exact same stats we would normally show, even if they are zeroed out. Done.

**Review by cathymw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56400)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @cathymw, @jordanlewis, and @RaduBerinde)

___
*[pkg/sql/colflow/colrpc/inbox.go, line 123 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLnYhvH4vilRpHf6A04:-MLnYhvH4vilRpHf6A05:b-ci37tg) ([raw file](https://github.com/cockroachdb/cockroach/blob/22ce3d07283ed1e04c0604ce55adfafbc9e0d06b/pkg/sql/colflow/colrpc/inbox.go#L123)):*
> ```Go
> 
> var _ colexecbase.Operator = &Inbox{}
> var _ execinfra.IOReader = &Inbox{}
> ```

I think this line can be deleted now that inbox doesn't implement `execinfra.IOReader`

**Comment by RaduBerinde** [comment]
> This probably needs a version bump, right?

As far as I can tell, an unknown proto in the span stats will be ignored, so I don't think it's necessary (we just won't get the stats in mixed-version cases).

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56400)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @cathymw, and @jordanlewis)

___
*[pkg/sql/colflow/colrpc/inbox.go, line 123 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLnYhvH4vilRpHf6A04:-MLoN0P84p7-1rcUSO8V:b-dtkds3) ([raw file](https://github.com/cockroachdb/cockroach/blob/22ce3d07283ed1e04c0604ce55adfafbc9e0d06b/pkg/sql/colflow/colrpc/inbox.go#L123)):*
<details><summary><i>Previously, cathymw wrote…</i></summary><blockquote>

I think this line can be deleted now that inbox doesn't implement `execinfra.IOReader`
</blockquote></details>

Done, thanks!

**Review by asubiotto — CHANGES_REQUESTED** [review]
This is looking really good

> Reviewed 5 of 15 files at r1, 7 of 14 files at r2, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-:-MLr689sDB9gxJKfyac3:b-ebx25g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @cathymw, @jordanlewis, and @RaduBerinde)

___
*[pkg/sql/colexec/stats.go, line 50 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLr1X3KBNG5lER7rY4q:-MLr1X3KBNG5lER7rY4r:b-gkt51q) ([raw file](https://github.com/cockroachdb/cockroach/blob/46d5605d23a38ca59212dfe3bdb880fd9abbc1a9/pkg/sql/colexec/stats.go#L50)):*
> ```Go
> }
> 
> // batchStatsCollector is a helper used by collector implementations.
> ```

nit: `s/batchStatsCollector/batchInfoCollector`
___
*[pkg/sql/execstats/execstatspb/operator_stats.go, line 67 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLr5DWCEEBPhg2Mg6Ru:-MLr5DWCEEBPhg2Mg6Rv:burbe92) ([raw file](https://github.com/cockroachdb/cockroach/blob/46d5605d23a38ca59212dfe3bdb880fd9abbc1a9/pkg/sql/execstats/execstatspb/operator_stats.go#L67)):*
> ```Go
> 	// KV stats.
> 	if s.KV.KVTime != 0 {
> 		// TODO(radu): should we rename this to "KV Time" which is more specific?
> ```

+1, I like KV time more
___
*[pkg/sql/execstats/execstatspb/operator_stats.go, line 106 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLr5vD75IR_TM56hfTn:-MLr5vD75IR_TM56hfTo:bf5cqla) ([raw file](https://github.com/cockroachdb/cockroach/blob/46d5605d23a38ca59212dfe3bdb880fd9abbc1a9/pkg/sql/execstats/execstatspb/operator_stats.go#L106)):*
> ```Go
> // collected.
> func (s *OperatorStats) MakeDeterministic() {
> ```

nit: extra line
___
*[pkg/sql/execstats/execstatspb/operator_stats.proto, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLloMEX7TCDicKyJE9C:-MLr3cI33EKSjrT00GTE:b-hiicq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8451902770bacfa23b9f7d91ac569c24f3aa44d5/pkg/sql/execstats/execstatspb/operator_stats.proto#L22)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I was thinking that all falls under "operator" as far as this package is concerned.. I added a comment. Maybe there's a better name than "operator"?
</blockquote></details>

I've used `component` in the past, what do you think? Even if `operator` is a term local to this package, it still is overloaded.
___
*[pkg/sql/execstats/execstatspb/operator_stats.proto, line 26 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLr5VaIDJlaL1P5SwkC:-MLr5VaIDJlaL1P5SwkD:b61uo73) ([raw file](https://github.com/cockroachdb/cockroach/blob/46d5605d23a38ca59212dfe3bdb880fd9abbc1a9/pkg/sql/execstats/execstatspb/operator_stats.proto#L26)):*
> ```protobuf
> // value indicates that the particular stat is not available.
> //
> // TODO(radu): consider defining a union for the various groups of stats and
> ```

I actually like this approach more than a repeated union, it seems more precise since you ensure at most one of a type of stat and it's valid to have some set and some not.
___
*[pkg/sql/execstats/execstatspb/operator_stats.proto, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLr40ui-aVJ9vCMmIuN:-MLr40ui-aVJ9vCMmIuO:bylupt9) ([raw file](https://github.com/cockroachdb/cockroach/blob/46d5605d23a38ca59212dfe3bdb880fd9abbc1a9/pkg/sql/execstats/execstatspb/operator_stats.proto#L31)):*
> ```protobuf
>   int32 operator_id = 1 [(gogoproto.customname) = "OperatorID"];
> 
>   NetworkRxStats net_rx = 2 [(gogoproto.nullable) = false];
> ```

non-nullability is a design choice, right? The idea being that we can access unset data and not worry about it affecting the aggregation? I'm wondering why this approach is different than what led us to introduce the `IntValue`, where we do care whether a field is set or not.
___
*[pkg/sql/execstats/execstatspb/operator_stats.proto, line 40 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLr4QB47N7zyXW0fKJb:-MLr4QB47N7zyXW0fKJc:b-sxejhh) ([raw file](https://github.com/cockroachdb/cockroach/blob/46d5605d23a38ca59212dfe3bdb880fd9abbc1a9/pkg/sql/execstats/execstatspb/operator_stats.proto#L40)):*
> ```protobuf
> // NetworkRxStats contains statistics for operators that receive row data
> // over the network.
> message NetworkRxStats {
> ```

I'm unfamiliar with what `Rx` and `Tx` mean, is it worth it to add a comment?
___
*[pkg/sql/execstats/execstatspb/operator_stats.proto, line 64 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLr4kYB9AVfjldB62N-:-MLr4kYB9AVfjldB62N0:b-g64hl6) ([raw file](https://github.com/cockroachdb/cockroach/blob/46d5605d23a38ca59212dfe3bdb880fd9abbc1a9/pkg/sql/execstats/execstatspb/operator_stats.proto#L64)):*
> ```protobuf
> }
> 
> // KVStats contains statistics for operators that performe KV operations.
> ```

nit: `performe`
___
*[pkg/sql/execstats/execstatspb/operator_stats.proto, line 94 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLr4pay-BIERgGDSm_3:-MLr4pay-BIERgGDSm_4:bszrl52) ([raw file](https://github.com/cockroachdb/cockroach/blob/46d5605d23a38ca59212dfe3bdb880fd9abbc1a9/pkg/sql/execstats/execstatspb/operator_stats.proto#L94)):*
> ```protobuf
> 
>   // Number of tuples produced by the operator.
>   // TODO(radu): should rename to 'rows' for consistency with other stats.
> ```

Or maybe we should rename `rows` elsewhere to `tuples`, especially if the vectorized engine will be more prominently used.

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-:-MLs_oWx443ByReFIfOs:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @cathymw, @jordanlewis, and @RaduBerinde)

___
*[pkg/sql/execstats/execstatspb/operator_stats.go, line 67 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLr5DWCEEBPhg2Mg6Ru:-MLsaJSZ7W-5zMYq6XkV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/46d5605d23a38ca59212dfe3bdb880fd9abbc1a9/pkg/sql/execstats/execstatspb/operator_stats.go#L67)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

+1, I like KV time more
</blockquote></details>

Done.
___
*[pkg/sql/execstats/execstatspb/operator_stats.proto, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLloMEX7TCDicKyJE9C:-MLsdr411LqAwPcfgC06:b-86mr6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/8451902770bacfa23b9f7d91ac569c24f3aa44d5/pkg/sql/execstats/execstatspb/operator_stats.proto#L22)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I've used `component` in the past, what do you think? Even if `operator` is a term local to this package, it still is overloaded.
</blockquote></details>

I like it, done.
___
*[pkg/sql/execstats/execstatspb/operator_stats.proto, line 26 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLr5VaIDJlaL1P5SwkC:-MLsaXLY1FYmpeHLZFcb:b-bnqu6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/46d5605d23a38ca59212dfe3bdb880fd9abbc1a9/pkg/sql/execstats/execstatspb/operator_stats.proto#L26)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I actually like this approach more than a repeated union, it seems more precise since you ensure at most one of a type of stat and it's valid to have some set and some not.
</blockquote></details>

Cool, removed.
___
*[pkg/sql/execstats/execstatspb/operator_stats.proto, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLr40ui-aVJ9vCMmIuN:-MLsaaBw-XUEvhnMOmQG:b-cisn5t) ([raw file](https://github.com/cockroachdb/cockroach/blob/46d5605d23a38ca59212dfe3bdb880fd9abbc1a9/pkg/sql/execstats/execstatspb/operator_stats.proto#L31)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

non-nullability is a design choice, right? The idea being that we can access unset data and not worry about it affecting the aggregation? I'm wondering why this approach is different than what led us to introduce the `IntValue`, where we do care whether a field is set or not.
</blockquote></details>

From a design perspective, it would have been nice from them to be nullable; unfortunately it would cause a ton of separate allocations.

Even if we had this, I still think it's nice to have the flexibility of individual fields to be either set or unset. I envision that if we want some of these stats to be automatically sampled periodically, we may want to disable individual stats that are more expensive to collect (I don't think any of the stats we have so far fall into that category, but who knows what we'll add).

If necessary, we can add some `IsSet()` methods to each of these that check if any of their members are set.
___
*[pkg/sql/execstats/execstatspb/operator_stats.proto, line 40 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLr4QB47N7zyXW0fKJb:-MLsbef44AkaTxnjqtKz:boq4s9s) ([raw file](https://github.com/cockroachdb/cockroach/blob/46d5605d23a38ca59212dfe3bdb880fd9abbc1a9/pkg/sql/execstats/execstatspb/operator_stats.proto#L40)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm unfamiliar with what `Rx` and `Tx` mean, is it worth it to add a comment?
</blockquote></details>

Sure, why not. They're standard abbreviations for Receive and Transmit in the networking world.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56400)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @cathymw, and @jordanlewis)

___
*[pkg/sql/execstats/execstatspb/operator_stats.proto, line 94 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-MLr4pay-BIERgGDSm_3:-MLseaHf6i6ioji8-Z1X:brkno94) ([raw file](https://github.com/cockroachdb/cockroach/blob/46d5605d23a38ca59212dfe3bdb880fd9abbc1a9/pkg/sql/execstats/execstatspb/operator_stats.proto#L94)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Or maybe we should rename `rows` elsewhere to `tuples`, especially if the vectorized engine will be more prominently used.
</blockquote></details>

I agree, done.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 10 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-:-MLw3adY51poDBbSL_lj:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @cathymw, and @jordanlewis)

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56400#-:-MLxGtGF1ZaSMU9sqR4Y:b-tlx7ko)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @cathymw, and @jordanlewis)

**Pull request merged**
