### PR TITLE
kvcoord: optimize usages of BatchRequest.IsReverse

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit audits all places where `BatchRequest.IsReverse` is called
and ensures that we call that only when necessary. In particular, it
avoids the call altogether when a request needs to be resumed as well as
when verifying the batch initially when key and / or bytes limits are
present.

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85697)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 974 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85697#-N8yGcEw2E7JJZ3QUo5d:-N8yGcEw2E7JJZ3QUo5e:b-de6srd) ([raw file](https://github.com/cockroachdb/cockroach/blob/57338a30040ef69c3b0f3485088568077e2d1a79/pkg/kv/kvclient/kvcoord/dist_sender.go#L974)):*
> ```Go
> 		return br, roachpb.NewError(err)
> 	}
> 	var qiIsReverse bool
> ```

`QueryIntent` requests don't have the `isReverse` flag. Since `qiBa` contains only this type of request, I think we can just say `qiIsReverse := false // QueryIntentRequest does not carry the isReverse flag`.

Similarly, if `isRevese`, then that must have come from some other request in the batch, so I don't think we need to recompute `isReverse` down below.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85697)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 974 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85697#-N8yGcEw2E7JJZ3QUo5d:-N8yTEAG-ErjeUKyxkEJ:bo3vl6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/57338a30040ef69c3b0f3485088568077e2d1a79/pkg/kv/kvclient/kvcoord/dist_sender.go#L974)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`QueryIntent` requests don't have the `isReverse` flag. Since `qiBa` contains only this type of request, I think we can just say `qiIsReverse := false // QueryIntentRequest does not carry the isReverse flag`.

Similarly, if `isRevese`, then that must have come from some other request in the batch, so I don't think we need to recompute `isReverse` down below.
</blockquote></details>

Thanks, done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85697#-:-N8yUC9h2-6trgk86O32:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
