### PR TITLE
opt: external API for index constraints

### PR DESCRIPTION
**Pull request by RaduBerinde**
Implementing an API that can be used from the sql index selection
code. Sample usage:
```go
  var ic IndexConstraints
  if err := ic.Init(filter, colInfos, evalCtx); err != nil {
    return err
  }
  spans, ok := ic.Spans()
  remainingFilter := ic.RemainingFilter(&iVarHelper)
```

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt_index_selection.go, line 517 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21098#-L1Ta82q4uUeg5Ygi_M4:-L1Ta82q4uUeg5Ygi_M5:b-co18va) ([raw file](https://github.com/cockroachdb/cockroach/blob/78970192187dba30cadab12dc3f51bb28993afc6/pkg/sql/opt_index_selection.go#L517)):*
> ```Go
> }
> 
> // TODO(radu): we will change makeIndexConstraints to use
> ```

Update this comment since you've changed the code

---

*[pkg/sql/opt/index_constraints.go, line 582 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21098#-L1Tb9nayWlG1BPKq1tE:-L1Tb9nayWlG1BPKq1tF:bljfume) ([raw file](https://github.com/cockroachdb/cockroach/blob/78970192187dba30cadab12dc3f51bb28993afc6/pkg/sql/opt/index_constraints.go#L582)):*
> ```Go
> 		} else {
> 			spans = c.mergeSpanSets(offset, spans, exprSpans)
> 			if len(spans) == 0 && spans[1].IsFullSpan() {
> ```

You're checking if the length of spans is 0 and then accessing spans[1]

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21098#-:-L1Tdm4Z96_v8AWjia9s:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt_index_selection.go, line 517 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21098#-L1Ta82q4uUeg5Ygi_M4:-L1TeXzmKePMYUQ1O2r6:baqrfr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/78970192187dba30cadab12dc3f51bb28993afc6/pkg/sql/opt_index_selection.go#L517)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Update this comment since you've changed the code
</blockquote></details>

I did, `makeIndexConstraints` refers to `indexInfo.makeIndexConstraints` in this file.

---

*[pkg/sql/opt/index_constraints.go, line 582 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21098#-L1Tb9nayWlG1BPKq1tE:-L1TeMIyc4TEyrt1GP07:b6zrrkh) ([raw file](https://github.com/cockroachdb/cockroach/blob/78970192187dba30cadab12dc3f51bb28993afc6/pkg/sql/opt/index_constraints.go#L582)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

You're checking if the length of spans is 0 and then accessing spans[1]
</blockquote></details>

Good catch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21098)*

**Comment by rytaft** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/opt_index_selection.go, line 517 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21098#-L1Ta82q4uUeg5Ygi_M4:-L1Tg6eovZN50ZTO5h5P:b-2wx16f) ([raw file](https://github.com/cockroachdb/cockroach/blob/78970192187dba30cadab12dc3f51bb28993afc6/pkg/sql/opt_index_selection.go#L517)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I did, `makeIndexConstraints` refers to `indexInfo.makeIndexConstraints` in this file.
</blockquote></details>

Ah got it - thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21098)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21098#-:-L1TqYjzcaLQSNnw2cH8:bnfp4nl)*

**Pull request merged**
