### PR TITLE
build: add roachprod-stress target

### PR DESCRIPTION
**Pull request by petermattis**
The roachprod-stress target stress a test or set of tests by running it
on a roachprod cluster. The roachprod cluster must already
exist. Invocation is similar to `make stress` with the addition of the
CLUSTER variable which is used to specify the roachprod cluster to run
the tests on.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
This PR depends on https://github.com/cockroachdb/stress/pull/11. Note that there is still a relatively heavy load on your laptop due to the invocation of `roachprod ssh <cluster>:<N>` for each test run. Perhaps I should take a different approach and push a stress binary to each node in the cluster. That would remove the need to change `stress` itself, though I'd have to have a local coordinator program for each of the stress runs. Thoughts?

**Comment by petermattis** [comment]
Hold off on looking at this. I'm going the route of a `roachprod-stress` tool that runs a `stress` process on each node. I mostly have it working and it is a lot more efficient.

**Comment by petermattis** [comment]
Ok, this seems to be working. And it no longer relies on cockroachdb/stress#11.

**Review by benesch — APPROVED** [review]
:lgtm: great idea!

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30766#-:-LNWVdlr4375jQ40pFwJ:b-37l2c8)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[Makefile, line 842 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30766#-LNWUthf-_QLzQTIsjxm:-LNWUthgESWaRplLL562:b-mnueta) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0eb9d4489f8b224e48d3c71e38e5be60022f80/Makefile#L842)):*
> ```Makefile
> 
> # TODO(peter): import the stress change that added -cluster and stop
> # hardcoding the path.
> ```

This TODO seems obsolete?
___
*[Makefile, line 846 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30766#-LNWU6VDDczgTfxYndvA:-LNWU6VDDczgTfxYndvB:b-5xs9c4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0eb9d4489f8b224e48d3c71e38e5be60022f80/Makefile#L846)):*
> ```Makefile
> roachprod-stress: bin/roachprod-stress
> 	build/builder.sh make bin/stress
> 	build/builder.sh make test GOFLAGS="-i -v -c -o $(notdir $(PKG)).test" PKG=$(PKG)
> ```

Referring to `build/builder.sh` in the Makefile is unconventional. We don't have any other targets that do so that I'm aware of. 

I think I'd prefer to extract this into a shell script like `scripts/roachprod-stress`, but I suppose that would make argument parsing hard, given that you want to be able to specify PKG, STRESSFLAGS, and CLUSTER separately. Hm. I guess just leave it as is.
___
*[pkg/cmd/roachprod-stress/main.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30766#-LNWV1cv4ydU9lFDrKtl:-LNWV1cw6CTPkpJp_yhX:b2ni1uf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0eb9d4489f8b224e48d3c71e38e5be60022f80/pkg/cmd/roachprod-stress/main.go#L98)):*
> ```Go
> 	nodes := strings.Count(string(out), "\n") - 1
> 
> 	if true {
> ```

eh?

**Comment by tschottdorf** [comment]
Don't have time to review, but I like the general idea and will use this all the time.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30766)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[Makefile, line 842 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30766#-LNWUthf-_QLzQTIsjxm:-LNWkup729LpBW-FVpPb:b1ty7pb) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0eb9d4489f8b224e48d3c71e38e5be60022f80/Makefile#L842)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This TODO seems obsolete?
</blockquote></details>

Yep. Removed.
___
*[Makefile, line 846 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30766#-LNWU6VDDczgTfxYndvA:-LNWkvf30kpsHkjdkn1K:b-ljqjg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0eb9d4489f8b224e48d3c71e38e5be60022f80/Makefile#L846)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Referring to `build/builder.sh` in the Makefile is unconventional. We don't have any other targets that do so that I'm aware of. 

I think I'd prefer to extract this into a shell script like `scripts/roachprod-stress`, but I suppose that would make argument parsing hard, given that you want to be able to specify PKG, STRESSFLAGS, and CLUSTER separately. Hm. I guess just leave it as is.
</blockquote></details>

I started with a script, and then moved to a make target to make the usage more akin to `make stress`. I think the ergonomics work well as a make target, though I agree using `build/builder.sh` in the Makefile is unconventional.
___
*[pkg/cmd/roachprod-stress/main.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30766#-LNWV1cv4ydU9lFDrKtl:-LNWlF1GCIij8Ql1CCDI:bucl6f6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0eb9d4489f8b224e48d3c71e38e5be60022f80/pkg/cmd/roachprod-stress/main.go#L98)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

eh?
</blockquote></details>

I was replacing that with `false` during development to speed up the testing cycle. Removed.

**Comment by petermattis** [comment]
bors r=benesch

**Comment by petermattis** [comment]
bors r=benesch

**Pull request merged**
