### PR TITLE
changefeedccl: update nemeses test to use the declarative schema changer

### PR DESCRIPTION
**Pull request by jayshrivastava**
### sql: only use public indexes when fingerprinting

Previously, running `SHOW EXPERIMENTAL_FINGERPRINTS` on a table
in the middle of a schema change would sometimes cause an error
due to missing indexes. The root cause of this error is that
fingerprinting attempted to read non-public indexes which exist
during the schema change:
```
1 foo_pkey
2 crdb_internal_index_2_name_placeholder
3 crdb_internal_index_3_name_placeholder
```
The fix to this change is a one line change which ensures fingerprinting
reads active indexes only. This change also adds a regression test for this
scenario. There was a test util method in `changefeedccl` which was useful
for this test. This change moves that util method to `schematestutils` so it
can be called outside of `changefeedccl`.

Epic: none

Release note: None

---

### changefeedccl: update nemeses test to use the declarative schema changer

This change updates the nemeses test, which asserts the behavior of changefeeds
under a randomized DML/DDL workload. Previously, the test would only run
with the legacy schema changer. This is not ideal because, by default, the
declarative schema changer is used in production. This change makes it so that
the declarative schema changer is used 90% of the time instead.

Informs: https://github.com/cockroachdb/cockroach/issues/106906
Epic: none

Release note: None

### CODE REVIEW

**Review by HonoreDB — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107475)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava and @miretskiy)

___
*[`pkg/sql/show_fingerprints.go` line 69 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107475#-Naqu2ZZ3tKxZlFkFI-P:-Naqu2ZZ3tKxZlFkFI-Q:b-c9spm6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2a6072bf6afd7ca36479787607eebcf4cb753e1/pkg/sql/show_fingerprints.go#L69)):*
> ```Go
> 	return &showFingerprintsNode{
> 		tableDesc: tableDesc,
> 		indexes:   tableDesc.ActiveIndexes(),
> ```

Worth running this change past someone from DR, I think. Is there a scenario where non-active indexes still need to be faithfully replicated for a backup+restore to be correct?

**Review by HonoreDB — COMMENTED** [review]
Nemesis commit LGTM.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107475#-:-Naqv5Dr2yGuHerf6P-J:b-1m1frs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava and @miretskiy)

**Review by jayshrivastava — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107475)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @miretskiy)

___
*[`pkg/sql/show_fingerprints.go` line 69 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107475#-Naqu2ZZ3tKxZlFkFI-P:-NaqvUQ-EPlSDStfnJXO:b-bkyagi) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2a6072bf6afd7ca36479787607eebcf4cb753e1/pkg/sql/show_fingerprints.go#L69)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Worth running this change past someone from DR, I think. Is there a scenario where non-active indexes still need to be faithfully replicated for a backup+restore to be correct?
</blockquote></details>

Ack. Can someone from @cockroachdb/disaster-recovery take a quick look?

**Review by msbutler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107475)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @miretskiy)

___
*[`pkg/sql/show_fingerprints.go` line 69 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107475#-Naqu2ZZ3tKxZlFkFI-P:-NaqzT28-aCT1ASiPkSV:bp1xsd1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2a6072bf6afd7ca36479787607eebcf4cb753e1/pkg/sql/show_fingerprints.go#L69)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

Ack. Can someone from @cockroachdb/disaster-recovery take a quick look?
</blockquote></details>

Yeah, we only restore active indexes (see below), so this change doesn't effect us. Aside: we also are transitioning to using crdb_internal.fingerprint instead of SHOW EXPERIMENTAL FINGERPRINT.

https://github.com/cockroachdb/cockroach/blob/fc5920459f4cc0950f195b9394c43fd07e8c9120/pkg/ccl/backupccl/restore_job.go#L682

**Review by HonoreDB — APPROVED** [review]

**Comment by jayshrivastava** [comment]
bors r=HonoreDB

TYFR!

**Comment by HonoreDB** [comment]
May have just seen a flake from this? Nemeses on cloudstorage timed out. https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11177629?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Pull request merged**
