### PR TITLE
kv: add a metric for rangefeeds waiting to perform catchup scans client-side

### LINKED ISSUE #134681: changefeedccl: add metric for when rangefeeds are blocked on the client-side catchup scan limiter
currently we have no way to tell how many rangefeed catchups are waiting to start. this is a common failure mode for changefeeds at high scale, and a metric would be useful in debugging that.

ref: https://github.com/asg0451/cockroach/blob/13b70743950f093f4b972fe4217c48b25bddabd5/pkg/kv/kvserver/replica_rangefeed.go#L284

Jira issue: CRDB-44200

### PR DESCRIPTION
**Pull request by asg0451**
Add a metric
(`distsender.rangefeed.catchup_ranges_waiting_client_side`)
that counts how many rangefeeds are waiting on the
client-side limiter to start performing catchup
scans.

Fixes: #134681

Release note (general change): Add a new metric
(`distsender.rangefeed.catchup_ranges_waiting_client_side`)
that counts how many rangefeeds are waiting on the
client-side limiter to start performing catchup
scans.

### CODE REVIEW

**Review by rharding6373 — APPROVED** [review]
:lgtm: Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136741#-:-ODJDw7V1XTlBFTjV-9B:b-g2a5fb)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @stevendanna)

**Comment by asg0451** [comment]
bors r=rharding6373

**Comment by asg0451** [comment]
blathers backport 24.2 24.1 23.2

**Comment by asg0451** [comment]
blathers backport 24.3

**Comment by stevendanna** [comment]
@asg0451 Apologies for my delay here.

I think this is a good metric, but I'm wondering if there is still a bit of a blind spot here. Namely, when you call (distSender).RangeFeed with some set of spans, we iterate those spans in a loop, calling startSingleRangeFeed on them.  Once one blocks on the client-side semaphore, it seems to be that the spans we haven't iterated yet are _also_ waiting, queued up behind the single range that is blocked on the semaphore.

Have we looked at this metric in practice to see if it gives us the values we think it should?  I'm not opposed to this metric, but I want to make sure we understand exactly what it is telling us before we back port it everywhere.

**Pull request merged**
