### PR TITLE
server: rename BinaryVersionOverride to ClusterVersionOverride

### PR DESCRIPTION
**Pull request by RaduBerinde**
This commit renames the field and updates the comment.

Epic: none
Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Forgot to mention - I tried to improve coverage of upgrades by randomly bootstrapping at an older version; unfortunately way too many tests are not equipped to handle that (e.g. expecting specific table or tenant ID, expecting a specific number of jobs, etc.). The attempt is in draft PR #126433.

**Review by renatolabs — APPROVED** [review]
LGTM!

As a minor comment, I'd probably find `ClusterVersionOverride` a better name, as "override" would then read like an adjective which is more aligned with the value passed to the field (the version which overrides the cluster version). It's also the pattern used in other override-style testing knobs.

`OverrideClusterVersion` makes "override" read like a verb IMO.

**Review by RaduBerinde — COMMENTED** [review]
TFTR! Renamed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126516#-:-O1-QKLy7jWDYp9lSQ0x:bfx3w1o)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @msbutler, @rafiss, and @srosenberg)

**Review by srosenberg — APPROVED** [review]

**Pull request merged**
