### PR TITLE
sql: add TODO / disclaimer to incomplete multinode test

### PR DESCRIPTION
**Pull request by dt**
[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4825)

### CODE REVIEW

**Comment by tamird** [comment]
Isn't it already possible for you to do the right thing here? #4783 has been merged.

**Comment by nvanbenschoten** [comment]
LGTM, but same question as @tamird.

**Comment by dt** [comment]
I think it should be, but I played with it a bit and it still wasn't reliably replicating, so I just wanted to take a TODO on there until I figured it out, since as-is, it is misleading.

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4825#-:-KDOYALB9DcOT7KZ85jd:1417088721)*

**Pull request merged**
