### PR TITLE
sql: attempt to reduce duplication in legacy schema changer txn management

### PR DESCRIPTION
**Pull request by ZhouXing19**
These functions can all be defined in terms of `txnWithExecutor`. It was
confusing that they were not.

Epic: none

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
This stuff is crufty. This seems fine, though sort of shocking how repetitive the code is around these parts. If somebody didn't know better, they might assume it was for a reason, but I don't think it is. 

What if we re-arranged things like in [this commit](https://github.com/cockroachdb/cockroach/commit/e09f785c24c237e3d21a47966728e9fc91375c80)?

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91567#-:-NGPWEST2pmCIyogEnni:b6m6kcb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ZhouXing19)

**Review by ZhouXing19 — COMMENTED** [review]
> What if we re-arranged things like in this commit?

Wow thanks for writing this up. Yeah it makes sense to have things all tracing down to `txnWithExecutor`. Do you want me to close this PR or cherry-pick your commit?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91567#-:-NGPculn4qQFYHYfp7br:bin5a41)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ZhouXing19)

**Comment by ajwerner** [comment]
No strong preferences, cherry-pick works for me.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91567#-:-NGPgTA04VinjW8TOxZH:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ZhouXing19)

**Comment by ZhouXing19** [comment]
Thanks!
bors r=ajwerner

**Pull request merged**
