### PR TITLE
authors: add Aaron Buck to authors

### PR DESCRIPTION
**Pull request by iAaronBuck**
Release note: None

Epic: none

### CODE REVIEW

**Review by zachlite — APPROVED** [review]
LGTM

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95019#-:-NLSU1W237rMzbQfm7xl:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @iAaronBuck)

**Comment by rail** [comment]
bors single on

**Pull request merged**
