### PR TITLE
sql: add assignment casts for UPSERTs

### LINKED ISSUE #67083: opt: revisit use of round_decimal_values in optbuilder
This issue tracks revisiting the use of `round_decimal_values` in optbuilder, in light of the comments in https://github.com/cockroachdb/cockroach/pull/66885#issuecomment-871447073

We believe that a cast to the target type might do the same thing, and that could be implemented in a more uniform (non-DECIMAL-specific) way (using `ReType` in the right places).

### PR DESCRIPTION
**Pull request by mgartner**
#### sql: add assignment casts for UPSERTs

Assignment casts are now added to query plans for upserts, including
`UPSERT`, `INSERT .. ON CONFLICT DO NOTHING`, and
`INSERT .. ON CONFLICT DO UPDATE ..` statements.

Assignment casts are a more general form of the logic for rounding
decimal values, so the use of `round_decimal_values` in mutations is no
longer needed. This logic has been removed.

Fixes #67083

There is no release note because the behavior of upserts should not
change with this commit.

Release note: None

#### sql: add logic tests for assignment casts of ON UPDATE expressions

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm_strong:  Nice work!

> Reviewed 11 of 12 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74763#-:-MtFPMrx6GMKuIBa2h_J:b4m8zyy)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 724 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74763#-MtFJfkG97WhRwE-clD5:-MtFJfkG97WhRwE-clD6:b-ra0xjj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4149ca74099cee7a698fcade6d8ba6891f47dfed/pkg/sql/opt/optbuilder/mutation_builder.go#L724)):*
> ```Go
> }
> 
> // roundDecimalValues wraps each DECIMAL-related column (including arrays of
> ```

:partying_face:

**Review by rytaft — APPROVED** [review]
:lgtm: Awesome!

> Reviewed 11 of 12 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74763#-:-MtIjMlj7p9wwVCeGGxa:bswp6el)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 724 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74763#-MtFJfkG97WhRwE-clD5:-MtJYoGkB-tEeeeGz-_K:bs7dxlg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4149ca74099cee7a698fcade6d8ba6891f47dfed/pkg/sql/opt/optbuilder/mutation_builder.go#L724)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

:partying_face: 
</blockquote></details>

I think @andy-kimball might be happy to see this complication now being naturally handled through assignment casts.

**Pull request merged**
