### PR TITLE
release-22.1: vendor: bump Pebble to 10f3aff6757a

### PR DESCRIPTION
**Pull request by jbowens**
```
10f3aff6 .github: install crlfmt@024b567c
287ed0f1 vfs: add SyncData,SyncTo,Preallocate to vfs.File
2c4a74ee vfs: clean up Fd functionality
```

Informs cockroachdb/pebble#2275.
Informs #94373.
Backport of #96036.
Epic: None

Release note: Fix bug whereby a stalled disk would sometimes be undetected. Now the stall is detected any time a filesystem write operation is observed to last longer than the value in the storage.max_sync_duration cluster setting.
Release justification: Fixes high severity issue of undetected disk stalls.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
The Fd change requires some minor changes, see #95704

**Comment by jbowens** [comment]
> The Fd change requires some minor changes, see https://github.com/cockroachdb/cockroach/pull/95704

I think those engineccl changes are present. (The `TestFSOpenFd` unit test didn't exist in 22.1.)

The Essential test failure like a test flake, but I'll re-run to make sure.

**Review by RaduBerinde — APPROVED** [review]

**Review by nicktrav — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96296#-:-NNDi4Bl0wjWcBhw6-aD:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @benbardin)

**Comment by jbowens** [comment]
TFTRs!

**Pull request merged**
