### PR TITLE
sql: more allocation reductions

### PR DESCRIPTION
**Pull request by jordanlewis**
See individual commits for details.

```
name                                          old time/op    new time/op    delta
FlowSetup/vectorize=true/distribute=true-24      283µs ± 9%     279µs ± 6%    ~     (p=0.316 n=29+30)
FlowSetup/vectorize=true/distribute=false-24     275µs ± 4%     273µs ± 6%    ~     (p=0.107 n=29+30)

name                                          old alloc/op   new alloc/op   delta
FlowSetup/vectorize=true/distribute=true-24     37.9kB ± 1%    37.9kB ± 1%    ~     (p=0.503 n=24+24)
FlowSetup/vectorize=true/distribute=false-24    36.1kB ± 1%    36.0kB ± 0%  -0.22%  (p=0.009 n=25+25)

name                                          old allocs/op  new allocs/op  delta
FlowSetup/vectorize=true/distribute=true-24        361 ± 0%       358 ± 0%  -0.81%  (p=0.000 n=25+26)
FlowSetup/vectorize=true/distribute=false-24       348 ± 1%       346 ± 1%  -0.84%  (p=0.000 n=28+28)
```

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57208#-:-MNM7kHp3pMH1aRaJYD2:b-8gk8uj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/conn_executor_exec.go, line 281 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/57208#-MNM6rzWEZfoWLnlvc1d:-MNM6rzWEZfoWLnlvc1e:b-f5v97l) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe14402fe0c81142f5293665f90d19378a770685/pkg/sql/conn_executor_exec.go#L281)):*
> ```Go
> 	queryDone := func(ctx context.Context, res RestrictedCommandResult) {
> 		if timeoutTicker != nil {
> 			timeoutTicker.Stop()
> ```

[nit] I'd point out that if Stop fails, the callback might still run or is in the process of running (and explain why that's ok)
___
*[pkg/sql/conn_executor_exec.go, line 1030 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/57208#-MNM7ZxZApeBuoXZscOJ:-MNM7ZxZApeBuoXZscOK:b-u01zbv) ([raw file](https://github.com/cockroachdb/cockroach/blob/892bcf8eeb45f0198a2afe22c10b02a6fa70ff0c/pkg/sql/conn_executor_exec.go#L1030)):*
> ```Go
> 
> var (
> 	eventStartImplicitTxn = fsm.Event(eventTxnStart{ImplicitTxn: fsm.True})
> ```

[nit] usually this is written as `var eventStartImplicitTxn fsm.Event = eventTxnStart{..}`
___
*[pkg/sql/opt/memo/interner.go, line 403 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/57208#-MNM5cSY5zH8eOiMtvrZ:-MNM5cSY5zH8eOiMtvr_:bagpbj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/83b700cd1ee9b7e3c188ef523a55e81edfc916ef/pkg/sql/opt/memo/interner.go#L403)):*
> ```Go
> 
> func (h *hasher) HashType(val *types.T) {
> 	// NOTE: we don't construct a perfect hash of the type, because it's
> ```

[nit] can simplify this and just say that we hash the type's OID and a few important fields, and that `IsTypeEqual` makes the final call about what types are identical.

**Review by yuzefovich — COMMENTED** [review]
I rebased this PR, modified some commits a bit, and addressed all the comments. @raduberinde PTAL.

I also dropped the commit about `rowenc: cheapen AdjustKeyForInterleave` since we're removing the interleaved code anyway. Let me know if you'd rather see it included in the PR.

> Reviewed 9 of 23 files at r24, 2 of 2 files at r26, 1 of 2 files at r27, 1 of 2 files at r28, 1 of 2 files at r29, 1 of 3 files at r30, 3 of 3 files at r31.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57208#-:-MmdFNct-ID2PB_mwH_Y:b-rpqiu6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @yuzefovich)

___
*[pkg/sql/conn_executor_exec.go, line 281 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/57208#-MNM6rzWEZfoWLnlvc1d:-Mmd7nCmE8F0Dmef-1Qe:b-o7x3sq) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe14402fe0c81142f5293665f90d19378a770685/pkg/sql/conn_executor_exec.go#L281)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I'd point out that if Stop fails, the callback might still run or is in the process of running (and explain why that's ok)
</blockquote></details>

I've thought a bit about this, and I'm not sure why that would be ok, so I reverted the change partially.
___
*[pkg/sql/conn_executor_exec.go, line 1030 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/57208#-MNM7ZxZApeBuoXZscOJ:-MmdDQPO6b_mqsxvkQG8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/892bcf8eeb45f0198a2afe22c10b02a6fa70ff0c/pkg/sql/conn_executor_exec.go#L1030)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] usually this is written as `var eventStartImplicitTxn fsm.Event = eventTxnStart{..}`
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/interner.go, line 403 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/57208#-MNM5cSY5zH8eOiMtvrZ:-MmdCjpZAk-W7XN655jz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83b700cd1ee9b7e3c188ef523a55e81edfc916ef/pkg/sql/opt/memo/interner.go#L403)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] can simplify this and just say that we hash the type's OID and a few important fields, and that `IsTypeEqual` makes the final call about what types are identical.
</blockquote></details>

Done.

**Comment by yuzefovich** [comment]
Friendly ping @RaduBerinde @cucaroach

**Review by cucaroach — APPROVED** [review]
:lgtm:

> Reviewed 23 of 23 files at r24, 1 of 1 files at r25, 2 of 2 files at r26, 2 of 2 files at r27, 2 of 2 files at r28.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57208#-:-Mnfidb69ggCU784nj_o:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

**Pull request merged**
