### PR TITLE
bazel: implement bazel "lint url's" nightly job

### LINKED ISSUE #67148: ci: add bazel "Nightlies / Lint URLs" for CI
Epic CRDB-8306

### PR DESCRIPTION
**Pull request by rickystewart**
Closes #67148.

Release note: None

### CODE REVIEW

**Comment by rickystewart** [comment]
Ignore the first commit, it's from #73396.

**Review by rail — APPROVED** [review]

**Comment by rickystewart** [comment]
bors r=rail

**Comment by rickystewart** [comment]
bors r=rail

**Comment by rickystewart** [comment]
bors r=rail

**Comment by rickystewart** [comment]
bors r=rail

**Pull request merged**
