### PR TITLE
builtins: make it easier to add builtins

### PR DESCRIPTION
**Pull request by jordanlewis**
It was very annoying to have to find new slots for new builtins, and merge conflicts were irritating because they don't actually cause merge conflicts - instead just fails CI later.

Now, we store the signatures in a sorted list. If 2 people race to make builtins, true merge conflicts will be generated which are much easier to resolve than having to wait until CI time.

Epic: None
Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
I didn't hand-audit the resultant positions, but they should be identical: I used vim to flip the order of the map, deleted whitespace, and the sorted the output with `sort -g`, from there I removed the array indexes.

**Comment by stevendanna** [comment]
My only worry here is that I was recently thinking of adding some code to track retired OIDs in case we want to remove functions over time. Not entirely clear to me how we would do that with the ordering based approach?

**Comment by jordanlewis** [comment]
> My only worry here is that I was recently thinking of adding some code to track retired OIDs in case we want to remove functions over time. Not entirely clear to me how we would do that with the ordering based approach?

It's not clear how to do it with the map approach either, is it? Either way the array now has explicit indexes in its literal, which means that skipped fields get empty string. The map is isomorphic to the array as well (and we construct it at init-time) so you should be able to use whatever approach you had in mind before, no?

**Comment by jordanlewis** [comment]
Also, as far as I know there's no known reason why the oids *actually* have to remain fixed across version - AFAICT nobody is actually persisting them anywhere. So I think in general this is a low-risk problem. Maybe @rafiss knows something I don't here though.

**Review by rafiss — APPROVED** [review]
the PG docs also do advise to not use OIDs for anything that gets persisted, and in the past, we've always changed builtins' OIDs. but i figured now that we have fixed OIDs it would be nicer for us to stop changing OIDs if we don't need to.

i think the approach now can just be to replace the list entry with an empty string, rather than deleting the list entry.

this lgtm! it's gonna clash with https://github.com/cockroachdb/cockroach/pull/93641 though

**Pull request merged**
