### PR TITLE
opt: improve the appliedRule callback

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: allow distinguishing between norm/explore rules

Release note: None

#### opt: improve the appliedRule callback

Improving the appliedRule callback to also pass the ordinal of the
expression that the rule was applied on. Cleaning up the related logic
and state in forcing_opt.

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27126#-:-LGW3bSp0w932xqjbEQG:bnfp4nl)*

**Comment by RaduBerinde** [comment]
bors r+

---







*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27126#-:-LGW77Ju3NCcDTV34JIP:b-ydi9ay)*

**Pull request merged**
