### PR TITLE
sql: more strict handling of param vals in CASE

### LINKED ISSUE #4691: sql: server panics during Walk of `UPDATE` with placeholders in CASE.
Running the bank example over pg_wire causes server to die:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x78 pc=0x4676b9e]

goroutine 92 [running]:
panic(0x501f780, 0xc8200100f0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/cockroachdb/cockroach/sql/parser.MapArgs.SetInferredType(0xc820d246c0, 0x791ecd0, 0xc8207f4d80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/david/code/go/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:745 +0x19e
github.com/cockroachdb/cockroach/sql/parser.(*CaseExpr).TypeCheck(0xc82097ae40, 0xc820d246c0, 0x0, 0x0, 0x0, 0x0)
	/Users/david/code/go/src/github.com/cockroachdb/cockroach/sql/parser/type_check.go:129 +0x6aa
github.com/cockroachdb/cockroach/sql.(*planner).Update(0xc820140000, 0xc820d51130, 0x5f331e00, 0x0, 0x0, 0xc800000001)
	/Users/david/code/go/src/github.com/cockroachdb/cockroach/sql/update.go:161 +0x1767
```

### PR DESCRIPTION
**Pull request by madelynnblue**
Fixes #4691

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4731)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/pgwire_test.go, line 221 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4731#-KBj6Ng7pNsc19NCoAPp:-KBj6Ng7pNsc19NCoAPq:1203038097) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cb62d3a1b79e86df96cff32effbd3e316e0e9dd/sql/pgwire_test.go#L221)):*
this error text should mention failed type inference

---

*[sql/parser/type_check.go, line 87 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4731#-KBj6HvlBpVNyU0NAyJC:-KBj6HvlBpVNyU0NAyJD:-376013752) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cb62d3a1b79e86df96cff32effbd3e316e0e9dd/sql/parser/type_check.go#L87)):*
probably can remove this now

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4731)*

**Comment by mjibson** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/pgwire_test.go, line 221 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4731#-KBj6Ng7pNsc19NCoAPp:-KBjA18olAVkct8sFZ3_:529926536) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cb62d3a1b79e86df96cff32effbd3e316e0e9dd/sql/pgwire_test.go#L221)):*
Do you have a suggestion? I'm not sure how to improve it.

---

*[sql/parser/type_check.go, line 87 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4731#-KBj6HvlBpVNyU0NAyJC:-KBjAqnHxkdIJRJPd-K9:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cb62d3a1b79e86df96cff32effbd3e316e0e9dd/sql/parser/type_check.go#L87)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4731)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/pgwire_test.go, line 221 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4731#-KBj6Ng7pNsc19NCoAPp:-KBjRPWYbO2JV5gkZ3jo:-2141076749) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cb62d3a1b79e86df96cff32effbd3e316e0e9dd/sql/pgwire_test.go#L221)):*
"cannot infer type for parameter $1"

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4731)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/parser/type_check.go, line 85 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4731#-KBjp_5tigPl8wKX-56F:-KBjp_5tigPl8wKX-56G:1355166862) ([raw file](https://github.com/cockroachdb/cockroach/blob/171bf6e2487c1ced881250028e9a2c1f71c7bedb/sql/parser/type_check.go#L85)):*
I've been scratching my head trying to understand the code in this function. It doesn't look right to me - whether we can infer the types depends on the order in which we process the conditions/values..

We should do this in two separate steps:
 - first look through all values and conditions; record the first known value and condition types, check that any other known types match
 - if the previous step was successful, call `SetInferredType` on everything.

This shouldn't be much more difficult than the current code, and it will make things like `WHEN TRUE THEN 1 ELSE $1` or `CASE $1 WHEN 1 THEN 2 ELSE 3` work as well.

---

*[sql/parser/type_check.go, line 88 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4731#-KBjsZoaR75rjEzBjP9a:-KBjsZoaR75rjEzBjP9b:-1593732697) ([raw file](https://github.com/cockroachdb/cockroach/blob/171bf6e2487c1ced881250028e9a2c1f71c7bedb/sql/parser/type_check.go#L88)):*
This deserves a comment: if `expr.Expr` is `nil`, then the `WHEN` clauses contain boolean expressions
```
CASE
     WHEN Boolean_expression THEN result_expression [ ...n ] 
     [ ELSE else_result_expression ] 
END
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4731)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/parser/type_check.go, line 85 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4731#-KBjp_5tigPl8wKX-56F:-KBmNLwqX8r8_DSShffM:-31394721) ([raw file](https://github.com/cockroachdb/cockroach/blob/171bf6e2487c1ced881250028e9a2c1f71c7bedb/sql/parser/type_check.go#L85)):*
I was thinking about type inference this morning as well. Seems like one of the pieces of info we're ignoring right now is the type imposed by the context the expression finds itself in. For example.

```
SELECT * FROM t WHERE CASE WHEN a THEN $1 ELSE $2 END
```

The context of the expression indicates we require a boolean output, so the types of `$1` and `$2` can be inferred as boolean. Similarly:

```
UPDATE accounts
  SET balance = CASE id WHEN $1 THEN $3 WHEN $2 THEN $4 END
  WHERE id IN ($1, $2)
```

The context of the `CASE` expression indicates we `$3` and `$4` have to have the same type as `balance`. Passing the context down to type checking and type inference feels similar to the way we determine the context in which a subquery is executed to check the number of columns allowed and whether multiple rows are allowed.

The above is not intended as feedback on this PR, just brainstorming. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4731)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/parser/type_check.go, line 85 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4731#-KBjp_5tigPl8wKX-56F:-KBk4TUA2WH3WO6O_de7:-1191594070) ([raw file](https://github.com/cockroachdb/cockroach/blob/171bf6e2487c1ced881250028e9a2c1f71c7bedb/sql/parser/type_check.go#L85)):*
FWIW, I don't think any of this should be done in this PR. This is good to keep in mind for the upcoming type system overhaul.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4731)*

**Comment by RaduBerinde** [comment]
*[sql/parser/type_check.go, line 85 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4731#-KBjp_5tigPl8wKX-56F:-KBmr1gs6S6XgtedgGvR:757790898) ([raw file](https://github.com/cockroachdb/cockroach/blob/171bf6e2487c1ced881250028e9a2c1f71c7bedb/sql/parser/type_check.go#L85)):*
What I suggested is a relatively minor code change that at least makes this function have well-defined semantics, and it allows more statements to work. Having more "positive" tests in place will help when the type overhaul comes.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4731)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/parser/type_check.go, line 85 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4731#-KBjp_5tigPl8wKX-56F:-KBmmwaMFH9tURafcIVI:-1306334802) ([raw file](https://github.com/cockroachdb/cockroach/blob/171bf6e2487c1ced881250028e9a2c1f71c7bedb/sql/parser/type_check.go#L85)):*
Radu's examples will work with Morty, as per a special rule for `CASE` that says we'll look for one branch who's type can be inferred and the type check all the others against that one known type.
Peter's examples will not. Assuming the first example should have been something like `SELECT * FROM t WHERE a = CASE WHEN 'x' THEN $1 ELSE $2 END`. There's no type information flowing down, from the `a = <case>` expr into the CASE itself. Because if you add that, then you need to reconcile it with typing information flowing up, and then you quickly (d)evolve into a constraint solver.

```
UPDATE accounts
  SET balance = CASE id WHEN $1 THEN $3 WHEN $2 THEN $4 END
  WHERE id IN ($1, $2)
```
also doesn't work, for any of the variables. If, instead, we'd have `WHERE id IN ($1, 55)`, then inference *might* work for $1 and $2, depending on the order in which typing happens to execute. If the IN is seen first, it'll work. If the CASE is seen first, it won't. Note that Morty is not an iterative process. But there's always explicit typing.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4731)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/parser/type_check.go, line 85 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4731#-KBjp_5tigPl8wKX-56F:-KBmyR43GzVHS9mM6s1T:21062454) ([raw file](https://github.com/cockroachdb/cockroach/blob/171bf6e2487c1ced881250028e9a2c1f71c7bedb/sql/parser/type_check.go#L85)):*
Why is there no typing info flowing down to the `CASE` for `a = <CASE>`? We certainly now the type of `a` in such an update statement. Regardless, let's find a better forum for discussing this. I apologize for hijacking the PR.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4731)*

**Comment by mjibson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/pgwire_test.go, line 221 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4731#-KBj6Ng7pNsc19NCoAPp:-KBnpcWQ0oOU5HCswfu8:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cb62d3a1b79e86df96cff32effbd3e316e0e9dd/sql/pgwire_test.go#L221)):*
Done.

---

*[sql/parser/type_check.go, line 88 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4731#-KBjsZoaR75rjEzBjP9a:-KBntqE37JsP-FbEUKUG:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/171bf6e2487c1ced881250028e9a2c1f71c7bedb/sql/parser/type_check.go#L88)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4731)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4731)*

**Pull request merged**
