### PR TITLE
server: use net.Pipe instead of TCP HTTP<->gRPC connections

### LINKED ISSUE #10374: server: admin UI communicates on server's default hostname only
### Steps to repro
1. Create node certificates not including server's hostname
2. Start node using `--advertise-host=<node internal IP address>`
3. Access admin UI.

### Expected Results
Admin UI loads data from cluster.

### Actual Result
Admin UI does not load data from cluster because it attempts to communicate using the server's `hostname` value as the host name.

### PR DESCRIPTION
**Pull request by tamird**
Fixes #10374.
Closes #17145.

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm:. I have a suggestion for the second commit that I think would be nice, but your change is an improvement even if you decide not to implement it (assuming it isn't flawed in the first place).

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/server/server.go, line 897 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19426#-Kx2yhPDb9yEZq5gRqOl:-Kx2yhPDb9yEZq5gRqOm:b59l4v8) ([raw file](https://github.com/cockroachdb/cockroach/blob/54f5bb9dcd0432969f22d49a20598115a8b2806c/pkg/server/server.go#L897)):*
> ```Go
> 
> 		if err := initServer.awaitBootstrap(); err != nil {
> 			return err
> ```

@bdarnell another case of https://github.com/cockroachdb/cockroach/issues/19316.

---

*[pkg/server/server.go, line 1128 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/19426#-Kx30yHHJ7HEO0y4Irw_:-Kx30yHHJ7HEO0y4Irwa:bsgn0wz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0fd2786a54d6536764a92cb302db2385c948779/pkg/server/server.go#L1128)):*
> ```Go
> 
> 	s.stopper.RunWorker(workersCtx, func(context.Context) {
> 		netutil.FatalIfUnexpected(s.grpc.Serve(&singleListener{
> ```

Right now, if for whatever reason `c2`  got closed, things would be toast. What if you changed `singleListener` to always return the same conn, and additionally you wrap `c2` in a noop close method? That way, even if a the `rpcContext` decided that the connection was dead (say there's a clock jump, or a 5s gc pause) and closed it, the connection could be reestablished.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19426#-:-Kx31ZxQx009TXvYl4Rw:bb9k0fg)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/server/server.go, line 1128 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/19426#-Kx30yHHJ7HEO0y4Irw_:-Kx31y7eIxU3vK9BxSrI:b-dmkggj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0fd2786a54d6536764a92cb302db2385c948779/pkg/server/server.go#L1128)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Right now, if for whatever reason `c2`  got closed, things would be toast. What if you changed `singleListener` to always return the same conn, and additionally you wrap `c2` in a noop close method? That way, even if a the `rpcContext` decided that the connection was dead (say there's a clock jump, or a 5s gc pause) and closed it, the connection could be reestablished.
</blockquote></details>

Hmm, I guess that wouldn't change anything because you pass `conn`  to grpc-gateway and have no interface for reconnections in the first place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19426)*

**Comment by tschottdorf** [comment]
Nice!

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/rpc/context.go, line 266 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/19426#-Kx3HyC-6Vp3CbfTXTds:-Kx3HyC0oKKXCc8gNq4u:b9gug6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8d93b7c166626cac8dc2c630c97356affecddfe/pkg/rpc/context.go#L266)):*
> ```Go
> 
> // GRPCDialOptions returns the minimal GRPC dial options appropriate for the
> // context.
> ```

It might be confusing for future readers to decide what the set of "minimal" options is. In fact, I'm not so sure myself since it's largely driven by this specific change. Seems that you specifically exclude performance settings and timeouts but include tracing and tls. Mentioning both of these is a good start.

---

*[pkg/server/server.go, line 1138 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/19426#-Kx3IklLBVdtxTnyBQQn:-Kx3IklLBVdtxTnyBQQo:b7v8cdm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8d93b7c166626cac8dc2c630c97356affecddfe/pkg/server/server.go#L1138)):*
> ```Go
> 	}
> 
> 	conn, err := grpc.DialContext(ctx, s.cfg.AdvertiseAddr, append(
> ```

Comment here why you eschew the standard way of getting a ClientConn. (Avoid unnecessary moving parts on this connection, in particular, avoid having it go unhealthy since there's no way to recover it).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19426#-:-Kx3J4ugANSaZwJ10LNy:b-83sjoh)*

**Comment by tamird** [comment]
TFTR! CI failures were due to missing decompression options (server would compress, client wouldn't know how to decompress).

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/rpc/context.go, line 266 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/19426#-Kx3HyC-6Vp3CbfTXTds:-Kx3qqOeDcxfgnDSw8Qv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8d93b7c166626cac8dc2c630c97356affecddfe/pkg/rpc/context.go#L266)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

It might be confusing for future readers to decide what the set of "minimal" options is. In fact, I'm not so sure myself since it's largely driven by this specific change. Seems that you specifically exclude performance settings and timeouts but include tracing and tls. Mentioning both of these is a good start.
</blockquote></details>

Done.

---

*[pkg/server/server.go, line 1128 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/19426#-Kx30yHHJ7HEO0y4Irw_:-Kx3qs6-ONyhc2EZEmdP:b-kx42fa) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0fd2786a54d6536764a92cb302db2385c948779/pkg/server/server.go#L1128)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Hmm, I guess that wouldn't change anything because you pass `conn`  to grpc-gateway and have no interface for reconnections in the first place.
</blockquote></details>

Yeah, nothing to do here unless we made `singleListener` into a channel and then had the dialer method below call `net.Pipe` every time. I think I prefer to never allow more than one of these in-process connections now that there should be no reason for it ever to be closed.

---

*[pkg/server/server.go, line 1138 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/19426#-Kx3IklLBVdtxTnyBQQn:-Kx3r4w_69vNE_cJz819:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8d93b7c166626cac8dc2c630c97356affecddfe/pkg/server/server.go#L1138)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Comment here why you eschew the standard way of getting a ClientConn. (Avoid unnecessary moving parts on this connection, in particular, avoid having it go unhealthy since there's no way to recover it).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19426#-:-Kx3r5opLearv6P9o8u3:b-qbym7v)*

**Comment by a-robinson** [comment]
Nice, thanks @tamird!

**Pull request merged**
