### PR TITLE
[prototype] storage: Make rebalance decisions at store-level

### PR DESCRIPTION
**Pull request by a-robinson**
As outlined in recent comments on #26059, we need to bring back some
form of stats-based rebalancing in order to perform well on TPC-C
without manual partitioning and replica placement.

This commit contains a prototype that demonstrates the effectiveness of
changing our approach to making rebalancing decisions from making them
in the replicate queue, which operates on arbitrarily ordered replicas
of the ranges on a store, to making them at a higher-level. This
prototype makes them at a cluster level by running the logic on only one
node, but my real proposal is to make them at the store level.

This change in abstraction reflects what a human would do if asked to
even out the load on a cluster given perfect information about
everything happening in the cluster:

1. First, determine which stores have the most load on them (or overfull
   -- but for the prototype I only considered the one dimension that
   affects TPC-C the most)
2. Decide whether the most loaded stores are so overloaded that action
   needs to be taken.
3. Examine the hottest replicas on the store (maybe not the absolute
   hottest in practice, since moving that one could disrupt user traffic,
   but in the prototype this seems to work fine) and attempt to move them
   to under-utilized stores.  If this can be done simply by transferring
   leases to under-utilized stores, then do so. If moving leases isn't
   enough, then also rebalance replicas from the hottest store to
   under-utilized stores.
4. Repeat periodically to handle changes in load or cluster membership.

In a real version of this code, the plan is roughly:
1. Each store will independently run their own control loop like this
   that is only responsible for moving leases/replicas off itself, not off
   other stores. This avoids needing a centralized coordinator, and will
   avoid the need to use the raft debug endpoint as long as we start
   gossiping QPS per store info, since the store already has details about
   the replicas on itself.
2. The existing replicate queue will stop making decisions motivated by
   balance. It will switch to only making decisions based on
   constraints/diversity/lease preferences, which is still needed since
   the new store-level logic will only check for store-level balance,
   not that all replicas' constraints are properly met.
3. The new code will have to avoid violating constraints/diversity/lease
   preferences.
4. The new code should consider range count, disk fullness, and maybe
   writes per second as well.
5. In order to avoid making decisions based on bad data, I'd like to
   extend lease transfers to pass along QPS data to the new leaseholder
   and preemptive snapshots to pass along WPS data to the new replica.
   This may not be strictly necessary, as shown by the success of this
   prototype, but should make for more reliable decision making.

I tested this out on TPC-C 5k on 15 nodes and am able to consistently
get 94% efficiency, which is the max I've seen using a build of the
workload generator that erroneously includes the ramp-up period in its
final stats. The first run with this code only got 85% because it took a
couple minutes to make all the lease transfers it wanted, but then all
subsequent runs got the peak efficiency while making negligibly few
lease transfers.

Note that I didn't even have to implement replica rebalancing to get
these results, which oddly contradicts my previous claims. However, I
believe that's because I did the initial split/scatter using a binary
containing #26438, so the replicas were already better scattered than by
default. I ran TPC-C on that build without these changes a couple times,
though, and didn't get better than 65% efficiency, so the scatter wasn't
the cause of the good results here.

Touches #26059, #17979

Release note: None

----------------------------------

per-node `exec.success` metric over a few runs with this change, showing the per-node KV QPS converging over time:

screen shot 2018-06-11 at 3 32 17 pm

per-node goroutine counts over the same few runs, showing the overloaded outlier node getting healthier and converging to the other nodes:

screen shot 2018-06-11 at 3 32 46 pm

I can write up a more formal RFC if folks think the write-up above (plus the success of this prototype) is insufficient as a proposal, but it's a good summary of my current plans.

@BramGruneir @nvanbenschoten @petermattis

### CODE REVIEW

**Comment by a-robinson** [comment]
Underlying the reasoning to change from the per-replica replicate queue to a new store-level construct is that the replicate queue doesn't have a great sense of how the replica it's looking at compares to the other replicas on the store. We have the 10th/25th/50th/75th/90th percentiles, but in practice those don't appear to be nearly as useful as being able to grab the top N replicas on the store and pick which of them should be moved.

And even if the replicate queue could determine that the replica it was looking at was the hottest replica, or the Nth hottest replica, it's going to be important for it to also know whether the other hot replicas are able to be moved. If the top 17 replicas are movable, maybe we don't want to move the 18th hottest replicas. But if the top 17 replicas can't be moved due to zone constraints and leaseholder preferences, then we probably do want to move the 18th hottest replica. It's going to be a lot easier (and will require breaking way fewer abstractions) to do that from something operating at the store-level than at the replica-level.

**Comment by nvanbenschoten** [comment]
Those results look really nice! Did you try performing the experiment on a 30 node cluster as well? I'm sure this will be even more helpful there.

One detail that pops out to me is that we're basing everything on qps without making a distinction between read and write qps. This is interesting because I'd expect transferring a lease for a range with high read-qps to be more impactful than transferring the lease for a range with high write-qps, which probably requires a full replica rebalance to alleviate an overloaded node. Do you think it makes sense to track these separately?

> I can write up a more formal RFC if folks think the write-up above (plus the success of this prototype) is insufficient as a proposal, but it's a good summary of my current plans.

I don't necessarily think a full RFC is necessary for any changes here (especially as you're prototyping them), but it would probably be a good idea to eventually go back and update https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20161026_leaseholder_rebalancing.md#future-directions with your new findings and plan.

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/server/prototype_allocator.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26608#-LEl81Wy-sru5FjR8GRc:-LEl81Wy-sru5FjR8GRd:bqu3v5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/61805d008f0158aa97427a2d07e9b17639c0e3e8/pkg/server/prototype_allocator.go#L29)):*
> ```Go
> )
> 
> var testQPSThreshold = settings.RegisterNonNegativeFloatSetting(
> ```

The prototype doesn't actually use this, right?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26608#-:-LEl5vRbE-6vH1ml-9H3:b-firr3)*

**Comment by a-robinson** [comment]
This appears to do the trick on tpc-c 10k, as explained in my latest commit message:

screen shot 2018-06-14 at 10 24 45 am

**Comment by nvanbenschoten** [comment]
Nice! 

> over the course of about 4 hours (the manual
partitioning approach takes many hours to move all the replicas as well,
for a point of comparison)

Was the rate of rebalancing steady throughout this entire 4 hour period?

> Range 1 is also back to getting a ton of QPS (~3k) even though I raised
> the range cache size from 1M to 50M. Looking at slow query traces shows
> a lot of range lookups, way more than I'd expect given that ranges
> weren't moving around at the time of the traces.

Did this eventually settle down? If not, I think it's worth exploring at some point. We're probably running into the issue mentioned in https://github.com/cockroachdb/cockroach/issues/18988, which will result in about 2x more range lookups than strictly necessary during heavy rebalancing scenerios. There might also be other issues lurking as well.

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26608#-:-LEzzJ883vCghpqqHm93:bjqohki)*

**Comment by a-robinson** [comment]
> Was the rate of rebalancing steady throughout this entire 4 hour period?

Not the entire time. About 2 hours were actually spent primarily doing lease transfers, which makes sense given the code but probably made the rebalancing period take longer than needed. Judging by the logs, that was because of the bug I mentioned where a replica on n1 had a ridiculously high reported QPS. Once that resolved itself, though, the rest of the time was a pretty steady stream of replica adds/removes.

> Did this eventually settle down? If not, I think it's worth exploring at some point. We're probably running into the issue mentioned in #18988, which will result in about 2x more range lookups than strictly necessary during heavy rebalancing scenerios. There might also be other issues lurking as well.

Not that I ever saw. Agree that it's worth looking getting to the bottom of.

**Comment by a-robinson** [comment]
> If not, I think it's worth exploring at some point. We're probably running into the issue mentioned in #18988, which will result in about 2x more range lookups than strictly necessary during heavy rebalancing scenerios.

That's certainly part of it. But what isn't clear is why the non-meta descriptors are being evicted. For example, check out this partial excerpt of events on an arbitrarily chosen range on one of the nodes. We keep evicting it and re-adding it to the range cache even though it isn't changing at all:

```
I180615 19:25:44.241605 903330514 kv/range_cache.go:457  [s1,r55617/4:/Table/56/1/24{30-40},n1] evict cached descriptor: key=/Table/53/1/2438/10/0 desc=r55673:/Table/53/1/24{30/0-40/0} [(n18,s19):5, (n17,s18):2, (n24,s25):4, next=6]
I180615 19:25:49.341302 903397366 kv/range_cache.go:578  [s1,n1] adding descriptor: key=/Meta2/Table/53/1/2440/0 desc=r55673:/Table/53/1/24{30/0-40/0} [(n18,s19):5, (n17,s18):2, (n24,s25):4, next=6]
I180615 19:26:07.868229 903462027 kv/range_cache.go:457  [s1,r55617/4:/Table/56/1/24{30-40},n1] evict cached descriptor: key=/Table/53/1/2431/9/0 desc=r55673:/Table/53/1/24{30/0-40/0} [(n18,s19):5, (n17,s18):2, (n24,s25):4, next=6]
I180615 19:26:13.973296 903495353 kv/range_cache.go:578  [s1,r55617/4:/Table/56/1/24{30-40},n1] adding descriptor: key=/Meta2/Table/53/1/2440/0 desc=r55673:/Table/53/1/24{30/0-40/0} [(n18,s19):5, (n17,s18):2, (n24,s25):4, next=6]
I180615 19:29:21.724366 904226264 kv/range_cache.go:457  [s1,r55617/4:/Table/56/1/24{30-40},n1] evict cached descriptor: key=/Table/53/1/2439/8/0 desc=r55673:/Table/53/1/24{30/0-40/0} [(n18,s19):5, (n17,s18):2, (n24,s25):4, next=6]
I180615 19:29:21.882479 904246100 kv/range_cache.go:578  [client=10.142.0.54:60202,user=root,txn=4f910e13,n1] adding descriptor: key=/Meta2/Table/53/1/2440/0 desc=r55673:/Table/53/1/24{30/0-40/0} [(n18,s19):5, (n17,s18):2, (n24,s25):4, next=6]
I180615 19:32:04.364989 904812433 kv/range_cache.go:457  [s1,r55617/4:/Table/56/1/24{30-40},n1] evict cached descriptor: key=/Table/53/1/2438/1/0 desc=r55673:/Table/53/1/24{30/0-40/0} [(n18,s19):5, (n17,s18):2, (n24,s25):4, next=6]
I180615 19:32:04.624679 904920683 kv/range_cache.go:578  [client=10.142.0.54:39730,user=root,txn=a79b8f61,n1] adding descriptor: key=/Meta2/Table/53/1/2440/0 desc=r55673:/Table/53/1/24{30/0-40/0} [(n18,s19):5, (n17,s18):2, (n24,s25):4, next=6]
I180615 19:32:51.906363 905107678 kv/range_cache.go:457  [s1,r55617/4:/Table/56/1/24{30-40},n1] evict cached descriptor: key=/Table/53/1/2434/1/0 desc=r55673:/Table/53/1/24{30/0-40/0} [(n18,s19):5, (n17,s18):2, (n24,s25):4, next=6]
I180615 19:32:52.032818 905120871 kv/range_cache.go:578  [client=10.142.0.54:58400,user=root,txn=7f61f484,n1] adding descriptor: key=/Meta2/Table/53/1/2440/0 desc=r55673:/Table/53/1/24{30/0-40/0} [(n18,s19):5, (n17,s18):2, (n24,s25):4, next=6]
I180615 19:33:14.223086 905210365 kv/range_cache.go:457  [s1,r55617/4:/Table/56/1/24{30-40},n1] evict cached descriptor: key=/Table/53/1/2435/2/0 desc=r55673:/Table/53/1/24{30/0-40/0} [(n18,s19):5, (n17,s18):2, (n24,s25):4, next=6]
I180615 19:33:14.299220 905210708 kv/range_cache.go:578  [s1,r55617/4:/Table/56/1/24{30-40},n1] adding descriptor: key=/Meta2/Table/53/1/2440/0 desc=r55673:/Table/53/1/24{30/0-40/0} [(n18,s19):5, (n17,s18):2, (n24,s25):4, next=6]
I180615 19:33:46.655785 905316841 kv/range_cache.go:457  [s1,r55617/4:/Table/56/1/24{30-40},n1] evict cached descriptor: key=/Table/53/1/2436/1/0 desc=r55673:/Table/53/1/24{30/0-40/0} [(n18,s19):5, (n17,s18):2, (n24,s25):4, next=6]
I180615 19:33:46.662854 905349469 kv/range_cache.go:578  [client=10.142.0.54:37896,user=root,txn=6366a404,n1] adding descriptor: key=/Meta2/Table/53/1/2440/0 desc=r55673:/Table/53/1/24{30/0-40/0} [(n18,s19):5, (n17,s18):2, (n24,s25):4, next=6]
I180615 19:34:50.580809 905608042 kv/range_cache.go:457  [s1,r55617/4:/Table/56/1/24{30-40},n1] evict cached descriptor: key=/Table/53/1/2436/10/0 desc=r55673:/Table/53/1/24{30/0-40/0} [(n18,s19):5, (n17,s18):2, (n24,s25):4, next=6]
I180615 19:34:50.622198 905608720 kv/range_cache.go:578  [s1,r55617/4:/Table/56/1/24{30-40},n1] adding descriptor: key=/Meta2/Table/53/1/2440/0 desc=r55673:/Table/53/1/24{30/0-40/0} [(n18,s19):5, (n17,s18):2, (n24,s25):4, next=6]
I180615 19:38:55.529085 906576259 kv/range_cache.go:457  [s1,r55617/4:/Table/56/1/24{30-40},n1] evict cached descriptor: key=/Table/53/1/2438/1/0 desc=r55673:/Table/53/1/24{30/0-40/0} [(n18,s19):5, (n17,s18):2, (n24,s25):4, next=6]
I180615 19:38:58.620422 906589469 kv/range_cache.go:578  [client=10.142.0.54:38534,user=root,txn=978a2b88,n1] adding descriptor: key=/Meta2/Table/53/1/2440/0 desc=r55673:/Table/53/1/24{30/0-40/0} [(n18,s19):5, (n17,s18):2, (n24,s25):4, next=6]
```

**Comment by a-robinson** [comment]
Almost all of the evictions in my current tpc-c 10k cluster are due to context cancellations for `QueryTxn` and `HeartbeatTxn` requests. We evict range cache entries whenever we get a `SendError`, which includes errors due to context cancellation. A cancelled context seems like a poor reason to invalidate a range cache entry, and a spectacularly bad reason to invalidate a meta2 range cache entry.

**Comment by a-robinson** [comment]
> Although it looks like the biggest issue is still our sending of HeartbeatTxn requests to r1, which we were supposed to have fixed in #26238, but is still happening even though my build includes that change. cc @spencerkimball

Sorry, I was mixing up `HeartbeatTxn`s and `QueryTxn`s. This was a separate problem.

I've sent out https://github.com/cockroachdb/cockroach/pull/26764 for the context cancellation problem and https://github.com/cockroachdb/cockroach/pull/26765 for all the `HeartbeatTxn` requests to r1. I'm not doing anything about the cache evictions caused by `RangeNotFound` errors on a single replica, since I can see some sense in them, even though doing so is now the primary cause of requests to r1, which is still seeing a few dozen qps (https://github.com/cockroachdb/cockroach/issues/18988 isn't helping).

**Comment by bdarnell** [comment]
> It appears as though whenever we get a RangeNotFound error from one of the replicas, we don't even bother trying the other known replicas. Is there a reason for that?

That sounds like a mistake. As the comment at `dist_sender.go:1034` says, these errors are only supposed to reach this level if we've exhausted all the replicas. 

The whole notion of range descriptor invalidation could use some reworking. Let's discuss that on #18988 instead of adding to this issue.

**Comment by a-robinson** [comment]
No need to keep this open any longer. https://github.com/cockroachdb/cockroach/pull/28340 and https://github.com/cockroachdb/cockroach/pull/28852 implement this for real.

**Pull request closed without merging**
