### PR TITLE
release-21.2: synchronously collect indux usage stats

### PR DESCRIPTION
**Pull request by Azhng**
Backport:
  * 1/1 commits from "sql, server, statusccl: synchronously collect index usage stats" (#73307)
  * 1/1 commits from "sql: implement optimistic locking for index usage stats write path " (#73179)

Please see individual PRs for details.

/cc @cockroachdb/release

---

Release Justification: Category 4: Low risk, high benefit changes to existing functionality

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74541)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @maryliag)

___
*[pkg/ccl/serverccl/statusccl/tenant_status_test.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74541#-Mt3fY49AKDALa4P1FOO:-Mt3fY49AKDALa4P1FOP:bsk0ycl) ([raw file](https://github.com/cockroachdb/cockroach/blob/24b60571e401e102fd1be704b91fa1cc30570849/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L50)):*
> ```Go
> 	ctx := context.Background()
> 
> 	knobs := tests.CreateTestingKnobs()
> ```

seems like this PR is missing a few changes from the original PR
https://github.com/cockroachdb/cockroach/pull/73307/files#diff-02b73484495c8093f91516129b1d5a39ca7b085799ed86de2390bce8b73490b0L70-L72

**Review by maryliag — COMMENTED** [review]
you're missing the release justification

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74541#-:-Mt3hQ3G66QM09SpiW4F:bey7sq8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @maryliag)

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74541)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[pkg/ccl/serverccl/statusccl/tenant_status_test.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74541#-Mt3fY49AKDALa4P1FOO:-Mt3xgTG16Z-uK-nhByM:b-pt4wd8) ([raw file](https://github.com/cockroachdb/cockroach/blob/24b60571e401e102fd1be704b91fa1cc30570849/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L50)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

seems like this PR is missing a few changes from the original PR
https://github.com/cockroachdb/cockroach/pull/73307/files#diff-02b73484495c8093f91516129b1d5a39ca7b085799ed86de2390bce8b73490b0L70-L72
</blockquote></details>

The `testTableIndexStats` is removed here on purpose. Table Index Stats endpoint is new in 22.1 and not backported to 21.2. So having `testTableIndexStats` in 21.2 branch doesn't quite make sense. 

Though that reminds me, [this PR](https://github.com/cockroachdb/cockroach/pull/74631) needs to be backported before this PR.

**Comment by maryliag** [comment]
is the Bazel failure related to any other missing PR that should also be backported?

**Comment by Azhng** [comment]
The bazel test failure seems like definitely not related to the backport of this PR. And the whole test pipeline seems quite flaky since different test fails each time the pipeline is re-run. I will check with def-inf.

**Comment by Azhng** [comment]
I've checked with Def Infra, we can safely ignore Bazel CI for backport against 21.2 or prior.

**Review by maryliag — APPROVED** [review]
sounds good
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74541#-:-Mt9nNxW8ZeWsSzAbvka:b-9gggg2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)

**Pull request merged**
