### PR TITLE
roachtest: improve and de-flake version-upgrade

### PR DESCRIPTION
**Pull request by tbg**
roachtest: automate and de-flake version-upgrade

The recent changes to this test seem to have uncovered a latent [bug],
as a result of which the test was skipped. This commit lets the test
start from v19.2 fixtures (instead of v19.1 before) which experimentally
were verified to not exhibit the bug, so the test is unskipped.

While I was there, I automated the base version discovery of this test.
On a branch at version X, the test will now use the fixtures for the
last major release preceding X. We'll occasionally have to bake new
fixtures and update the mapping in PredecessorVersion() but this is
better than having the test rot on older branches whenever we update
it for a new dev cycle.

The root cause of the bug will be fixed separately; this is tracked in
issue #44732.

[bug]: https://github.com/cockroachdb/cockroach/pull/47235#issuecomment-611419920

Release note: None

### CODE REVIEW

**Review by spaskob — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47268)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @spaskob and @tbg)

___
*[pkg/cmd/roachtest/versionupgrade.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47268#-M4TxNDhCLzcEeqOxcoC:-M4TxNDhCLzcEeqOxcoD:b-bk27g) ([raw file](https://github.com/cockroachdb/cockroach/blob/da7f7ee456ce1b99cb021191cd38ee58d19a8430/pkg/cmd/roachtest/versionupgrade.go#L107)):*
> ```Go
> 		waitForUpgradeStep(),
> 
> 		// NB: before the next step, cluster and binary version equals baseVersion,
> ```

nit: NB: at this point, cluster and binary version equal predecessorVersion,
___
*[pkg/cmd/roachtest/versionupgrade.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47268#-M4TvjCRE27sHOUaXlAI:-M4TvjCRE27sHOUaXlAJ:bfe2f4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/da7f7ee456ce1b99cb021191cd38ee58d19a8430/pkg/cmd/roachtest/versionupgrade.go#L117)):*
> ```Go
> 		preventAutoUpgradeStep(),
> 		// Roll nodes forward.
> 		binaryUpgradeStep("HEAD"),
> ```

nit: headVersion
also elsewhere in this file

What's the reason this is not followed by `waitForUpgradeStep`?
___
*[pkg/cmd/roachtest/versionupgrade.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47268#-M4TvZDUCjXxJihljcOO:-M4TvZDUCjXxJihljcOP:byycpko) ([raw file](https://github.com/cockroachdb/cockroach/blob/da7f7ee456ce1b99cb021191cd38ee58d19a8430/pkg/cmd/roachtest/versionupgrade.go#L122)):*
> ```Go
> 		// exercises this in more detail, so here we just rely on things working
> 		// as they ought to.
> 		binaryUpgradeStep("19.2.1"),
> ```

shouldn't this be predecessorVersion?
___
*[pkg/cmd/roachtest/versionupgrade.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47268#-M4Ty7eOEkpeTz72XDeE:-M4Ty7eOEkpeTz72XDeF:be0dz8v) ([raw file](https://github.com/cockroachdb/cockroach/blob/da7f7ee456ce1b99cb021191cd38ee58d19a8430/pkg/cmd/roachtest/versionupgrade.go#L129)):*
> ```Go
> 		waitForUpgradeStep(),
> 
> 		cp.createCheckpointsAndFail, // noop by default
> ```

please add a comment on why the checkpoint creation step needs to be last in the sequence
___
*[pkg/cmd/roachtest/versionupgrade.go, line 394 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47268#-M4U1anx-DJPElGKkcfv:-M4U1anx-DJPElGKkcfw:b8bqd2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/da7f7ee456ce1b99cb021191cd38ee58d19a8430/pkg/cmd/roachtest/versionupgrade.go#L394)):*
> ```Go
> // v1.0 and maintain it as a fixture for this test.
> //
> // The checkpoints will be created in the log directories. The test will fail
> ```

I tried to use this instructions yesterday and could not figure out if we have to run the roachtest locally to be able to run the shell script below.
___
*[pkg/cmd/roachtest/versionupgrade.go, line 433 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47268#-M4Tw8as4B88Q9418SYk:-M4Tw8as4B88Q9418SYl:b-7jz7p5) ([raw file](https://github.com/cockroachdb/cockroach/blob/da7f7ee456ce1b99cb021191cd38ee58d19a8430/pkg/cmd/roachtest/versionupgrade.go#L433)):*
> ```Go
> 	name := checkpointName(u.binaryVersion(ctx, t, 1).String())
> 	c.Stop(ctx, nodes)
> 	c.Run(ctx, c.All(), "./cockroach-HEAD", "debug", "rocksdb", "--db={store-dir}",
> ```

I was confused initially why the name  `./cockroach-HEAD` then I found out this is how `uploadVersion` names the binary, it may worthwhile to have this as a constant to prevent some hard to find bugs in the future if `headVerdsion` changes from `HEAD` for some reason.

**Review by tbg — COMMENTED** [review]
TFTR, PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47268#-:-M4U730u9FWuVIXflHwV:b-lhhn3c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @spaskob)

___
*[pkg/cmd/roachtest/versionupgrade.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47268#-M4TvjCRE27sHOUaXlAI:-M4U5RY71_sLJGixg_7v:b-284hwa) ([raw file](https://github.com/cockroachdb/cockroach/blob/da7f7ee456ce1b99cb021191cd38ee58d19a8430/pkg/cmd/roachtest/versionupgrade.go#L117)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

nit: headVersion
also elsewhere in this file

What's the reason this is not followed by `waitForUpgradeStep`?
</blockquote></details>

It's not upgrading - we cycled the binaries but the cluster version is not being bumped. `waitForUpgradeStep` waits for the cluster version bump.
___
*[pkg/cmd/roachtest/versionupgrade.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47268#-M4TvZDUCjXxJihljcOO:-M4U5bFwBvhLInxqJE1s:bxofazs) ([raw file](https://github.com/cockroachdb/cockroach/blob/da7f7ee456ce1b99cb021191cd38ee58d19a8430/pkg/cmd/roachtest/versionupgrade.go#L122)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

shouldn't this be predecessorVersion?
</blockquote></details>

Absolutely, thanks for catching this.
___
*[pkg/cmd/roachtest/versionupgrade.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47268#-M4Ty7eOEkpeTz72XDeE:-M4U5z0P8TnsDYfKcwge:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da7f7ee456ce1b99cb021191cd38ee58d19a8430/pkg/cmd/roachtest/versionupgrade.go#L129)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

please add a comment on why the checkpoint creation step needs to be last in the sequence
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/versionupgrade.go, line 394 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47268#-M4U1anx-DJPElGKkcfv:-M4U61Gs7eCx2kcBjDgq:bzigfiv) ([raw file](https://github.com/cockroachdb/cockroach/blob/da7f7ee456ce1b99cb021191cd38ee58d19a8430/pkg/cmd/roachtest/versionupgrade.go#L394)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

I tried to use this instructions yesterday and could not figure out if we have to run the roachtest locally to be able to run the shell script below.
</blockquote></details>

You don't, the artifacts get downloaded into the same place either way. But I've never tried it remotely.
___
*[pkg/cmd/roachtest/versionupgrade.go, line 433 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47268#-M4Tw8as4B88Q9418SYk:-M4U6xlg8sxdQO7W86-h:b41n6tl) ([raw file](https://github.com/cockroachdb/cockroach/blob/da7f7ee456ce1b99cb021191cd38ee58d19a8430/pkg/cmd/roachtest/versionupgrade.go#L433)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

I was confused initially why the name  `./cockroach-HEAD` then I found out this is how `uploadVersion` names the binary, it may worthwhile to have this as a constant to prevent some hard to find bugs in the future if `headVerdsion` changes from `HEAD` for some reason.
</blockquote></details>

I realized we could just rip out headVersion, PTAL

**Review by spaskob — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47268)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @spaskob)

**Comment by tbg** [comment]
TFTR!

bors r=spaskob

**Comment by tbg** [comment]
bors r=spaskob

Flake in distsql_automatic_stats, so not this PR.

**Pull request merged**
