### PR TITLE
storage/engine: replace RocksDB dependency to the general storage engine

### LINKED ISSUE #41740: storage/engine: audit code for usage of *engine.RocksDB
Audit code for direct usage of `*engine.RocksDB`:

```
~ git grep '\*engine.RocksDB'
ccl/cliccl/debug.go:func fillEncryptionOptionsForStore(cfg *engine.RocksDBConfig) error {
cli/debug.go:var PopulateRocksDBConfigHook func(*engine.RocksDBConfig) error
cli/debug.go:func OpenExistingStore(dir string, stopper *stop.Stopper, readOnly bool) (*engine.RocksDB, error) {
cli/debug.go:) (*engine.RocksDB, error) {
cli/debug.go:func runDebugCheckStoreDescriptors(ctx context.Context, db *engine.RocksDB) error {
cli/debug.go:func runDebugCheckStoreRaft(ctx context.Context, db *engine.RocksDB) error {
cli/syncbench/syncbench.go:     db      *engine.RocksDB
cli/syncbench/syncbench.go:func newWorker(db *engine.RocksDB) *worker {
server/node_engine_health.go:                           if rocks, ok := eng.(*engine.RocksDB); ok {
server/status.go:               if rocksdb, ok := store.Engine().(*engine.RocksDB); ok {
server/status.go:               if rocksdb, ok := store.Engine().(*engine.RocksDB); ok {
storage/compactor/compactor_test.go:    *engine.RocksDB
storage/replica_proposal.go:                            if _, ok := ingestErr.(*engine.RocksDBError); !ok || !isSeqNoErr {
storage/replica_sideload_test.go:func newRocksDB(t *testing.T) (func(), engine.RocksDBCache, *engine.RocksDB) {
storage/replica_sst_snapshot_storage.go:        ctx context.Context, sst *engine.RocksDBSstFileWriter,
storage/store.go:       if rocksdb, ok := s.engine.(*engine.RocksDB); ok {
```

### PR DESCRIPTION
**Pull request by hueypark**
Fixes: #41740

### CODE REVIEW

**Comment by hueypark** [comment]
@petermattis I found that CockroachDB does not have key manager for pebble. Is that right?

**Review by petermattis — COMMENTED** [review]
Thanks for the PR, @hueypark. Generally looks good to me, though I'd like @sumeerbhola to take a look as he's working on Pebble encryption-at-rest which overlaps with some of the bits here. I don't think there is any duplication of work here, but he'll know for sure.

> Fixes: #41740(partly)

I believe this will cause #41740 to be closed when this PR merges. To reference the issue without closing it, use `See #41740`.

> @petermattis I found that CockroachDB does not have key manager for pebble. Is that right?

@sumeerbhola is working on https://github.com/cockroachdb/cockroach/pull/41913 to do exactly that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41920#-:-Ls1vTSE7NxdXojrwFuj:bxmih0m)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by hueypark** [comment]
@petermattis Thank you for the review. I leave Pebble encryption to @sumeerbhola and I'll come back this PR with a full fix of #41740.

**Review by sumeerbhola — COMMENTED** [review]
This PR looks fine to me. I have the KeyManager and EncryptedFS implemented but no integration code -- this PR seems to help significantly with that later integration step. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41920#-:-Ls20KqADLVlx3Wtg3zZ:b-s5gpdn)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by hueypark** [comment]
@petermattis I'm back with full fix. I have created TODOs and will do them one by one. If you need to do it quickly feel free to distribute.

**Review by petermattis — COMMENTED** [review]
:lgtm: modulo some minor comments. Let's get those fixed up and get this merged as it will likely rot due to the large swath of code it touches.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41920#-:-LsD3og71IzAUlEOIKsZ:b96kbro)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @hueypark)

___
*[pkg/cli/debug.go, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41920#-LsD0gf20jNMKtCoq_p6:-LsD0gf33b1TeZ_JWuXy:b-bb6qcm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca0ca1ce616fef46c129a5c879c320ee316f2d9b/pkg/cli/debug.go#L121)):*
> ```Go
> // an empty engine might be initialized.
> func OpenEngine(dir string, stopper *stop.Stopper, opts OpenEngineOptions) (engine.Engine, error) {
> 	// TODO(hueypark): This seems to support all engines like engine.NewTempEngine.
> ```

I think it might be burdensome and error prone for the user to remember whether they specified `--storage-engine=pebble` or not during `start`. We may want to drop a breadcrumb in the store directory to indicate the engine type and have CLI debug tools automatically use the correct engine type.
___
*[pkg/server/status.go, line 274 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41920#-LsD214N2JTHXMaLRcn5:-LsD214N2JTHXMaLRcn6:bdyd0zz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca0ca1ce616fef46c129a5c879c320ee316f2d9b/pkg/server/status.go#L274)):*
> ```Go
> 			return grpcstatus.Errorf(codes.Internal, err.Error())
> 		}
> 		resp.Stats = append(
> ```

I wonder if we should extend `EngineStatsInfo` with the type of engine. I believe this RPC is only used to populate `debug.zip` and it would be good to have the engine type present there (it might be already due to command line flags, but I don't think it hurts to be repetitive here).
___
*[pkg/storage/engine/in_mem.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41920#-LsD3J55DDvgP2e4LDyT:-LsD3J55DDvgP2e4LDyU:bbkfe7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca0ca1ce616fef46c129a5c879c320ee316f2d9b/pkg/storage/engine/in_mem.go#L26)):*
> ```Go
> // FIXME(tschottdorf): make the signature similar to NewRocksDB (require a cfg).
> func NewInMem(attrs roachpb.Attributes, cacheSize int64) InMem {
> 	// TODO(hueypark): Support all engines like NewTempEngine.
> ```

I believe some tests expect `NewInMem` to create a RocksDB engine. I'm not quite clear on the right structuring here. We have tests in `storage/engine` which want to create RocksDB vs Pebble engines, and we have tests external to this package which shouldn't care.
___
*[pkg/storage/engine/pebble.go, line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41920#-LsD3dnP3VhkQgy0fhB-:-LsD3dnP3VhkQgy0fhB0:bm8bkgf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca0ca1ce616fef46c129a5c879c320ee316f2d9b/pkg/storage/engine/pebble.go#L226)):*
> ```Go
> // GetCompactionStats implements the Engine interface.
> func (p *Pebble) GetCompactionStats() string {
> 	// TODO(hueypark): Implement this.
> ```

I believe this can be `p.db.Metrics().String()`.
___
*[pkg/storage/engine/error.go, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41920#-LsD2u9jElU_YLi51k0h:-LsD2u9jElU_YLi51k0i:b-qgp08g) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca0ca1ce616fef46c129a5c879c320ee316f2d9b/pkg/storage/engine/error.go#L21)):*
> ```Go
> 
> // A StorageEngineError wraps an error returned from a RocksDB operation.
> type StorageEngineError struct {
> ```

`storage/engine.StorageEngineError` is a bit repetitive. How about just `EngineError`? Still a bit of stuttering with that. Could also go all the way to just `Error` as external from this package it will look like `engine.Error`. Though maybe it is important to distinguish `EngineError` from `MVCCError` (which doesn't exist).

**Review by hueypark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41920)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis)

___
*[pkg/cli/debug.go, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41920#-LsD0gf20jNMKtCoq_p6:-LsELwJL-bxTD7bBRXIo:b-cevl7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca0ca1ce616fef46c129a5c879c320ee316f2d9b/pkg/cli/debug.go#L121)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think it might be burdensome and error prone for the user to remember whether they specified `--storage-engine=pebble` or not during `start`. We may want to drop a breadcrumb in the store directory to indicate the engine type and have CLI debug tools automatically use the correct engine type.
</blockquote></details>

I do not know which part is burdensome. Can you explain a little bit more?
___
*[pkg/server/status.go, line 274 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41920#-LsD214N2JTHXMaLRcn5:-LsEDqHz7Y4rM6gLoO3V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca0ca1ce616fef46c129a5c879c320ee316f2d9b/pkg/server/status.go#L274)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I wonder if we should extend `EngineStatsInfo` with the type of engine. I believe this RPC is only used to populate `debug.zip` and it would be good to have the engine type present there (it might be already due to command line flags, but I don't think it hurts to be repetitive here).
</blockquote></details>

Done.
___
*[pkg/storage/engine/in_mem.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41920#-LsD3J55DDvgP2e4LDyT:-LsEJ69E4X5jurCwhxVB:b-hdpkex) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca0ca1ce616fef46c129a5c879c320ee316f2d9b/pkg/storage/engine/in_mem.go#L26)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I believe some tests expect `NewInMem` to create a RocksDB engine. I'm not quite clear on the right structuring here. We have tests in `storage/engine` which want to create RocksDB vs Pebble engines, and we have tests external to this package which shouldn't care.
</blockquote></details>

There are currently two engine testing styles in CockroachDB, each with pros and cons.

| type | pros | cons |
| --- | --- | --- |
| with env COCKROACH_TEST_STORAGE_ENGINE | Single engine testing is possible, reducing test latency. | Can not test all engines at once. |
| runWithAllEngines | Can test all the engines at once. | The testing delay is longer. |

Since the unit test time is long enough, I recommended supporting the env style(NewInMem with env). If we only need RocksDB, we should use it explicitly.
___
*[pkg/storage/engine/pebble.go, line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41920#-LsD3dnP3VhkQgy0fhB-:-LsE3Yq80d0f7hBHlrWb:b4855pb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca0ca1ce616fef46c129a5c879c320ee316f2d9b/pkg/storage/engine/pebble.go#L226)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I believe this can be `p.db.Metrics().String()`.
</blockquote></details>

Thanks! Done.
___
*[pkg/storage/engine/error.go, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41920#-LsD2u9jElU_YLi51k0h:-LsEERvxDOydOexSVqhn:b-zcoyci) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca0ca1ce616fef46c129a5c879c320ee316f2d9b/pkg/storage/engine/error.go#L21)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`storage/engine.StorageEngineError` is a bit repetitive. How about just `EngineError`? Still a bit of stuttering with that. Could also go all the way to just `Error` as external from this package it will look like `engine.Error`. Though maybe it is important to distinguish `EngineError` from `MVCCError` (which doesn't exist).
</blockquote></details>

Done. I'm satisfied with changing to engine.Error.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41920)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @hueypark)

___
*[pkg/cli/debug.go, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41920#-LsD0gf20jNMKtCoq_p6:-LsHS-cn3l5HQQdce23x:bz6m8um) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca0ca1ce616fef46c129a5c879c320ee316f2d9b/pkg/cli/debug.go#L121)):*
<details><summary><i>Previously, hueypark (Jaewan Park) wrote…</i></summary><blockquote>

I do not know which part is burdensome. Can you explain a little bit more?
</blockquote></details>

If a user selects cockroach via `cockroach start --storage-engine=pebble ...`, it would be nice for `cockroach debug check-store` (or any of the debug commands) to automatically use the `pebble` as the storage engine when opening the store. Now that I write this, it is probably desirable to have the `--storage-engine` by sticky even for `start`. Running `cockroach start --storage-engine=pebble`, and later running `cockroach start` without specifying `--storage-engine` should not switch to using RocksDB.

I don't think there is anything additional to do for this PR. This is me just thinking out loud.
___
*[pkg/storage/engine/in_mem.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41920#-LsD3J55DDvgP2e4LDyT:-LsHSeVt6GMpsgDjAtDI:b-bcbtrb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca0ca1ce616fef46c129a5c879c320ee316f2d9b/pkg/storage/engine/in_mem.go#L26)):*
<details><summary><i>Previously, hueypark (Jaewan Park) wrote…</i></summary><blockquote>

There are currently two engine testing styles in CockroachDB, each with pros and cons.

| type | pros | cons |
| --- | --- | --- |
| with env COCKROACH_TEST_STORAGE_ENGINE | Single engine testing is possible, reducing test latency. | Can not test all engines at once. |
| runWithAllEngines | Can test all the engines at once. | The testing delay is longer. |

Since the unit test time is long enough, I recommended supporting the env style(NewInMem with env). If we only need RocksDB, we should use it explicitly.
</blockquote></details>

We also have `for _, engineImpl := range mvccEngineImpls`. I think we only need to support `runWithAllEngines` and `for ... range mvccEngineImpls` in the `storage/engine` package. Other packages should use `COCKROACH_TEST_STORAGE_ENGINE`.

My point about `NewInMem` is that various tests in `storage/engine` call `NewInMem` to create a RocksDB engine. For example, `runWithAllEngines` and `setupMVCCInMemRocksDB`. Those usages need to have a new API for explicitly creating a RocksDB in-mem engine. I'd suggest adding an unexported method like `newRocksDBInMem`.

**Review by hueypark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41920)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis)

___
*[pkg/cli/debug.go, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41920#-LsD0gf20jNMKtCoq_p6:-LsHaSsrCQ2HwAWw-LUv:b-pvrxp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca0ca1ce616fef46c129a5c879c320ee316f2d9b/pkg/cli/debug.go#L121)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

If a user selects cockroach via `cockroach start --storage-engine=pebble ...`, it would be nice for `cockroach debug check-store` (or any of the debug commands) to automatically use the `pebble` as the storage engine when opening the store. Now that I write this, it is probably desirable to have the `--storage-engine` by sticky even for `start`. Running `cockroach start --storage-engine=pebble`, and later running `cockroach start` without specifying `--storage-engine` should not switch to using RocksDB.

I don't think there is anything additional to do for this PR. This is me just thinking out loud.
</blockquote></details>

I understand now. Thank you for your kind explanation.
___
*[pkg/storage/engine/in_mem.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41920#-LsD3J55DDvgP2e4LDyT:-LsHce325RGu0MsnL-XS:b-hatez1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca0ca1ce616fef46c129a5c879c320ee316f2d9b/pkg/storage/engine/in_mem.go#L26)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

We also have `for _, engineImpl := range mvccEngineImpls`. I think we only need to support `runWithAllEngines` and `for ... range mvccEngineImpls` in the `storage/engine` package. Other packages should use `COCKROACH_TEST_STORAGE_ENGINE`.

My point about `NewInMem` is that various tests in `storage/engine` call `NewInMem` to create a RocksDB engine. For example, `runWithAllEngines` and `setupMVCCInMemRocksDB`. Those usages need to have a new API for explicitly creating a RocksDB in-mem engine. I'd suggest adding an unexported method like `newRocksDBInMem`. 

</blockquote></details>

`NewInMem` is also used a lot outside of `storage/engine`. For example `server.TestClusterIDMismatch` and `storage.TestRaftSSTableSideloadingInline`. Could we keep this TODO and discuss it again in the next?

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41920)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @hueypark)

___
*[pkg/storage/engine/in_mem.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41920#-LsD3J55DDvgP2e4LDyT:-LsHgsS75ndemiU4LHCu:b-lh09o2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca0ca1ce616fef46c129a5c879c320ee316f2d9b/pkg/storage/engine/in_mem.go#L26)):*
<details><summary><i>Previously, hueypark (Jaewan Park) wrote…</i></summary><blockquote>

`NewInMem` is also used a lot outside of `storage/engine`. For example `server.TestClusterIDMismatch` and `storage.TestRaftSSTableSideloadingInline`. Could we keep this TODO and discuss it again in the next?
</blockquote></details>

Yes, the TODO is fine. Yes, `NewInMem` is used a lot outside of `storage/engine`. That is why I'm suggesting adding `newRocksDBInMem` for use within `storage/engine`. That way we can have `NewInMem` respect `COCKROACH_TEST_STORAGE_ENGINE`.

**Review by hueypark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41920)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis)

___
*[pkg/storage/engine/in_mem.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41920#-LsD3J55DDvgP2e4LDyT:-LsHpcjO--p_nlKs0MAi:b-5zl0vp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca0ca1ce616fef46c129a5c879c320ee316f2d9b/pkg/storage/engine/in_mem.go#L26)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Yes, the TODO is fine. Yes, `NewInMem` is used a lot outside of `storage/engine`. That is why I'm suggesting adding `newRocksDBInMem` for use within `storage/engine`. That way we can have `NewInMem` respect `COCKROACH_TEST_STORAGE_ENGINE`.
</blockquote></details>

Finally, I got it! I added `newRocksDBInMem` for `storage/engine`.

**Comment by hueypark** [comment]
TFTR!

bors r=petermattis

**Comment by hueypark** [comment]
>  Permission denied
> 
> Existing reviewers: [click here to make hueypark a reviewer](https://bors.crdb.io/repositories/56/add-reviewer/hueypark)

Oops, bors needs permission.

**Comment by petermattis** [comment]
Thanks again for the contribution! Let me help you with that.

bors r+

**Pull request merged**
