### PR TITLE
libroach: avoid ToDBKey'ing split keys

### LINKED ISSUE #46069: libroach: TBI fails `Inline values are unsupported by the IncrementalIterator`
In preparing to turn TBI on by default, I ran into this:

```
< init tpcc warehouses = 1 >

set cluster setting kv.bulk_io_write.experimental_incremental_export_enabled= true;
SET CLUSTER SETTING

root@:26257/defaultdb> BACKUP TO 'nodelocal://1/bar';

... run TPCC warehouses = 1

root@:26257/defaultdb> BACKUP TO 'nodelocal://1/bar';
ERROR: exporting 29 ranges: exporting /Table/61/{1-2}: Inline values are unsupported by the IncrementalIterator```

### PR DESCRIPTION
**Pull request by dt**
ToDBKey assumes its argument is an mvcc key and splits it accordingly.

If it is passed an already split user key it will fail when it tries to
split it again, either misinterpreting the suffix as a ts or detecting a
bad ts length and returning an empty DBKey. In the latter case, the
incremental iterator then interprets that as /Min and dutifully seeks
its underlying iterator there.

Fixes #46069.

Release note: none. (this code is disabled)

Release justification: low-risk, high impact bug fix.

While i'm here: have BACKUP print the span to which a failing ExportRequest was sent.

### CODE REVIEW

**Review by pbardea — APPROVED** [review]
Thanks for tracking this down!

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46068#-:-M2HNU1J0loXa72AtLlC:b-4evfnn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @pbardea)

___
*[c-deps/libroach/incremental_iterator.cc, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46068#-M2HNYHMDQRZs76xFpPA:-M2HNYHMDQRZs76xFpPB:b-gd7z5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c0aa9e8fa7ec28a462fc3e772a9c76ca9480912/c-deps/libroach/incremental_iterator.cc#L116)):*
> ```cpp
>       // due to aborted transactions and keys which have been subsumed due to
>       // range tombstones. In this case we can SeekGE() the TBI to the main iterator.
>       DBKey seek_to;
> ```

nit: `const`?

**Review by miretskiy — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46068)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @pbardea)

___
*[c-deps/libroach/incremental_iterator.cc, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46068#-M2HNYHMDQRZs76xFpPA:-M2It24I8LUemfEkIqQb:bv1k7r0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c0aa9e8fa7ec28a462fc3e772a9c76ca9480912/c-deps/libroach/incremental_iterator.cc#L116)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

nit: `const`?
</blockquote></details>

This can't be const (because we assign to seek_to.key below).  Of course you could do it via a helper or a lambda, such as:
const DBKey seek_to = [iter_key]() -> DBKey {
   DBKey k;
   k.key = ToDBSlice(iter_key);
  return k;
}();

I think it's an overkill though.

But I DO thing we need a comment here explain why we're not using ToDBKey here.

**Review by miretskiy — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46068)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

**Review by petermattis — COMMENTED** [review]
Nice catch! Did you verify that the Pebble version of incremental iterator is doing the right thing?

Is there a unit test which should have caught this?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46068#-:-M2Ivjr8DusWJLxLdIP9:b-exlknr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

**Comment by dt** [comment]
The pebble version is doing the right thing: https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/mvcc_incremental_iterator.go#L238

**Comment by dt** [comment]
@miretskiy (or @pbardea) you're still tracking coming up and writing all the new testing for the TBI edge cases, right? If so, can I defer including testing of this for that? 

(aside: I don't know what your current thinking is on how to test, but one idea I had was that it would be nice to count (maybe the iter stats already have this?) how many underlying keys the inc iter had to examine during some iteration, so we could see that number change with vs without the optional TBI, to prove the TBI did what it is supposed to. I _think_ such a test would have caught this too, since the mis-Seek to /Min would read too many keys, right?)

**Comment by dt** [comment]
TFTRs!

bors r+

**Pull request merged**
