### PR TITLE
build: misc fixes

### PR DESCRIPTION
**Pull request by benesch**
This fixes our source archives (they were luckily broken _after_ the beta was cut), drops the dependency on XZ Utils on macOS and Linux, and fixes `brew install cockroach` when jemalloc is already installed. See commit messages for details.

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[Makefile, line 272 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15235#-KiClE8mJEZzecCjlaB0:-KiClE8mJEZzecCjlaB1:b-elwqoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d79976a1116576de74edb6a915fbe6d2d15236f3/Makefile#L272)):*
> ```Makefile
> .INTERMEDIATE: $(ARCHIVE).tmp
> $(ARCHIVE).tmp: ARCHIVE_BASE = cockroach-$(shell cat .buildinfo/tag)
> $(ARCHIVE).tmp: $(C_LIBS_SRCS) $(CGO_FLAGS_FILES) $(BOOTSTRAP_TARGET) .buildinfo/tag .buildinfo/rev
> ```

don't you need the C_LIBS to be untared, at least?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15235#-:-KiClihYZCgnX40Vl_4O:bnfp4nl)*

**Comment by benesch** [comment]
Nope, the git ls-files excludes them anyway. We could make special
provisions to avoid the tarballs in tarballs, but ¯\_(ツ)_/¯. This has the
benefit of forcing all clean builds through the same pipeline.

**Comment by tamird** [comment]
Ah, right. Tarballs-in-tarballs seems good.

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15235)*

**Comment by bdarnell** [comment]
`tar` on Linux supports the `J` flag, but when it is present it calls out to `xz`, so that package must still be installed.

**Comment by jordanlewis** [comment]
Reviewed 1 of 3 files at r2, 1 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[Makefile, line 161 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/15235#-KiDPM_4PRqBp50plmYx:-KiDPM_4PRqBp50plmYy:b1110pu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bd7687204903324b520037efaa7e85bc51c2960/Makefile#L161)):*
> ```Makefile
> FIND_RELEVANT := find pkg -name node_modules -prune -o
> 
> bin/sql.test: main.go $(shell $(FIND_RELEVANT) ! -name 'zcgo_flags.go' -name '*.go')
> ```

D'oh, shoulda stuck to my guns on this I guess.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15235)*

**Comment by benesch** [comment]
@bdarnell, thanks, good catch! Updated the docs in the latest revision appropriately.

**Pull request merged**
