### PR TITLE
workload: Optimize ticking of histograms for large numbers of workers

### PR DESCRIPTION
**Pull request by a-robinson**
**workload: Avoid defer in NamedHistogram.tick**

Minor, but this was showing up on CPU profiles taking a little over 1%
of CPU. Given that the histogram ticking is CPU-bound for large tpc-c
invocations, saving 1% for basically zero effort seems worth it.

**workload: Use sync.Pool for hdr histograms**

The allocation of these histograms was taking about 20% of CPU on
locally simulated tpc-c 50k runs (not even including all the extra work
it imposed on the garbage collector). This drops newHistogram down to
7%, 6% of which is from the memory clearing done by
hdrhistogram.Reset().

This noticeably cuts down on the amount of output ticks that are skipped
by tpc-c 50k on my laptop, but doesn't totally eliminate them yet.

**workload: Paralellize ticking of different histograms**

This avoided skipped ticks when running on my laptop (with all actual
sql requests mocked out with a time.Sleep(25ms)). Before this, ticks
were only being printed every 3 or 4 seconds instead of every second.

This will also only scale so far and will probably need to be further
optimized in the future, but it appears to be good enough for 50k
warehouses, so it's good enough for now.

There's still some funniness going on at the start of runs, though, with
the first second or two being skipped and with some elevated latencies
about 10 seconds in (even though no real requests are being sent to a
database in this local testing).

**workload: Call callback without mutex held in NamedHistogram.tick**

**workload: Optimize locking in Histograms.Get**

Also avoid including locking in the timing. This has a very noticeable
effect on the tail latencies in my local 50k worker testing with the SQL
queries stubbed out.

---

Touches https://github.com/cockroachdb/cockroach/issues/30284#issuecomment-422801552

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30807#-:-LNhVxK091Sv6e5Czizq:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/workload/histogram.go, line 135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30807#-LNhVI8x6dA7j3mnG1s9:-LNhVI8x6dA7j3mnG1sA:b67506t) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a1649e6c0636360e173b625b3ab5ffb70f62e28/pkg/workload/histogram.go#L135)):*
> ```Go
> // be called periodically from one goroutine.
> func (w *HistogramRegistry) Tick(fn func(HistogramTick)) {
> 	w.mu.Lock()
> ```

Is there a reason to change the locking here? Limiting it to just the slice copy is easier to understand.

**Review by a-robinson — COMMENTED** [review]
Ah, bad timing, I just added one more change. Mind taking a second look? I'm done for now, although there's still some bad behavior at the beginning of each run, seemingly from the GC. I tried pre-allocating all the `NamedHistograms` before the workload starts, but that actually makes things worse for some reason I'm not sure of.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30807#-:-LNhXOe9DOUWkizwq206:b-xc734u)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/workload/histogram.go, line 135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30807#-LNhVI8x6dA7j3mnG1s9:-LNhW_UkCTnPastmkh-P:bh07zba) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a1649e6c0636360e173b625b3ab5ffb70f62e28/pkg/workload/histogram.go#L135)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is there a reason to change the locking here? Limiting it to just the slice copy is easier to understand.
</blockquote></details>

The goal was to parallelize the ticking for each histogram name. Storing all the histograms in a single unsorted slice makes that tough, since all the names are mixed together, so this change now stores `w.mu.registered` as a map to a separate slice for each name. Given that, there's no way to do the copy without iterating through the map, and it seemed simplest to just kick off the goroutines from within that loop than to have two loops, one which does all the copying and another which kicks off the goroutines. I can change it to the latter if you'd prefer, though.

**Review by nvb — DISMISSED** [review]
Still :lgtm: 

> Reviewed 9 of 10 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30807#-:-LNh_DY17IlZGWb_kLVh:b-dbkjmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/workload/histogram.go, line 135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30807#-LNhVI8x6dA7j3mnG1s9:-LNh_87x0lbc5ueDXPkV:bxov2p0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a1649e6c0636360e173b625b3ab5ffb70f62e28/pkg/workload/histogram.go#L135)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

The goal was to parallelize the ticking for each histogram name. Storing all the histograms in a single unsorted slice makes that tough, since all the names are mixed together, so this change now stores `w.mu.registered` as a map to a separate slice for each name. Given that, there's no way to do the copy without iterating through the map, and it seemed simplest to just kick off the goroutines from within that loop than to have two loops, one which does all the copying and another which kicks off the goroutines. I can change it to the latter if you'd prefer, though.
</blockquote></details>

Makes sense. No need to change.
___
*[pkg/workload/tpcc/worker.go, line 168 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/30807#-LNh_3zh6ZBBQH5DqYGH:-LNh_3zh6ZBBQH5DqYGI:b-5j2ch4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dabbdf2e842a16163b3add380360f85eb047eb7/pkg/workload/tpcc/worker.go#L168)):*
> ```Go
> 		// Calculate the duration before getting the histogram to prevent any lock
> 		// contention in Get() from affecting the recorded duration.
> 		dur := timeutil.Since(start)
> ```

nit: s/dur/elapsed/ for consistency

**Review by a-robinson — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30807#-:-LNhboL75ilu1IUOXbbJ:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/workload/histogram.go, line 135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30807#-LNhVI8x6dA7j3mnG1s9:-LNhblR4Boh5C-UYTfC1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a1649e6c0636360e173b625b3ab5ffb70f62e28/pkg/workload/histogram.go#L135)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Makes sense. No need to change.
</blockquote></details>

Done.
___
*[pkg/workload/tpcc/worker.go, line 168 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/30807#-LNh_3zh6ZBBQH5DqYGH:-LNhbmkf2Ukokm9IfcF_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dabbdf2e842a16163b3add380360f85eb047eb7/pkg/workload/tpcc/worker.go#L168)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: s/dur/elapsed/ for consistency
</blockquote></details>

Done.

**Pull request merged**
