### PR TITLE
kv: retry AdminSplit on LeaseTransferRejectedBecauseTargetMayNeedSnapshot

### LINKED ISSUE #83174: roachtest: kv95/enc=false/nodes=4/ssds=8 failed
roachtest.kv95/enc=false/nodes=4/ssds=8 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/5527687?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/5527687?buildTab=artifacts#/kv95/enc=false/nodes=4/ssds=8) on master @ [13cb2f6c40e3146fed8d931f65f89da9b42ce2c1](https://github.com/cockroachdb/cockroach/commits/13cb2f6c40e3146fed8d931f65f89da9b42ce2c1):

```
		  | 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:74
		  | runtime.goexit
		  | 	GOROOT/src/runtime/asm_amd64.s:1581
		Wraps: (2) output in run_123246.507421504_n5_workload_run_kv
		Wraps: (3) ./workload run kv --init --histograms=perf/stats.json --concurrency=256 --splits=1000 --duration=30m0s --read-percent=95 {pgurl:1-4} returned
		  | stderr:
		  | I220622 12:32:47.683261 1 workload/cli/run.go:386  [-] 1  DEPRECATION: the --init flag on "workload run" will no longer be supported after 19.2
		  | I220622 12:32:47.735496 1 workload/workloadsql/workloadsql.go:136  [-] 2  starting 1000 splits
		  | Error: executing ALTER TABLE kv SPLIT AT VALUES (-7030402461658535936): pq: change replicas of r95 failed: descriptor changed: [expected] r95:/Table/106/1/-{7177828987722147840-6901404251352873984} [(n4,s31):1VOTER_DEMOTING_LEARNER, (n2,s12):2, (n3,s23):3, (n4,s29):4VOTER_INCOMING, next=5, gen=28, sticky=9223372036.854775807,2147483647] != [actual] r95:/Table/106/1/-{7177828987722147840-6901404251352873984} [(n4,s29):4, (n2,s12):2VOTER_DEMOTING_LEARNER, (n3,s23):3, (n2,s16):5VOTER_INCOMING, next=6, gen=32, sticky=9223372036.854775807,2147483647]
		  |
		  | stdout:
		Wraps: (4) COMMAND_PROBLEM
		Wraps: (5) Node 5. Command with error:
		  | ``````
		  | ./workload run kv --init --histograms=perf/stats.json --concurrency=256 --splits=1000 --duration=30m0s --read-percent=95 {pgurl:1-4}
		  | ``````
		Wraps: (6) exit status 1
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *cluster.WithCommandDetails (4) errors.Cmd (5) *hintdetail.withDetail (6) *exec.ExitError

	monitor.go:127,kv.go:159,kv.go:289,test_runner.go:896: monitor failure: monitor task failed: t.Fatal() was called
		(1) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).WaitE
		  | 	main/pkg/cmd/roachtest/monitor.go:115
		  | main.(*monitorImpl).Wait
		  | 	main/pkg/cmd/roachtest/monitor.go:123
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerKV.func2
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/kv.go:159
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerKV.func3
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/kv.go:289
		  | main.(*testRunner).runTest.func2
		  | 	main/pkg/cmd/roachtest/test_runner.go:896
		Wraps: (2) monitor failure
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).wait.func2
		  | 	main/pkg/cmd/roachtest/monitor.go:171
		Wraps: (4) monitor task failed
		Wraps: (5) attached stack trace
		  -- stack trace:
		  | main.init
		  | 	main/pkg/cmd/roachtest/monitor.go:80
		  | runtime.doInit
		  | 	GOROOT/src/runtime/proc.go:6498
		  | runtime.main
		  | 	GOROOT/src/runtime/proc.go:238
		  | runtime.goexit
		  | 	GOROOT/src/runtime/asm_amd64.s:1581
		Wraps: (6) t.Fatal() was called
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.leafError
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=8</code>
, <code>ROACHTEST_ssd=8</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*kv95/enc=false/nodes=4/ssds=8.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-16899

Epic CRDB-19172

### LINKED ISSUE #85449: roachtest: schemachange/during/kv failed
roachtest.schemachange/during/kv [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/5940811?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/5940811?buildTab=artifacts#/schemachange/during/kv) on master @ [748b89a3fbef294f4b0f930c9dbdf88294b3deeb](https://github.com/cockroachdb/cockroach/commits/748b89a3fbef294f4b0f930c9dbdf88294b3deeb):

```
test artifacts and logs in: /artifacts/schemachange/during/kv/run_1
	schemachange.go:49,monitor.go:105,errgroup.go:74: pq: importing 688 ranges: splitting key /Table/111/1/31834467: change replicas of r105 failed: descriptor changed: [expected] r105:/Table/111/1/{26192423-47979489} [(n2,s2):1VOTER_DEMOTING_LEARNER, (n5,s5):2, (n4,s4):3, (n3,s3):4VOTER_INCOMING, next=5, gen=18, sticky=1659433859.194661639,0] != [actual] r105:/Table/111/1/2{6192423-7379106} [(n3,s3):4VOTER_DEMOTING_LEARNER, (n5,s5):2, (n4,s4):3, (n1,s1):5VOTER_INCOMING, next=6, gen=23, sticky=1659433859.194661639,0]

	monitor.go:127,schemachange.go:53,test_runner.go:896: monitor failure: monitor task failed: t.Fatal() was called
		(1) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).WaitE
		  | 	main/pkg/cmd/roachtest/monitor.go:115
		  | main.(*monitorImpl).Wait
		  | 	main/pkg/cmd/roachtest/monitor.go:123
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerSchemaChangeDuringKV.func1
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/schemachange.go:53
		  | main.(*testRunner).runTest.func2
		  | 	main/pkg/cmd/roachtest/test_runner.go:896
		Wraps: (2) monitor failure
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).wait.func2
		  | 	main/pkg/cmd/roachtest/monitor.go:171
		Wraps: (4) monitor task failed
		Wraps: (5) attached stack trace
		  -- stack trace:
		  | main.init
		  | 	main/pkg/cmd/roachtest/monitor.go:80
		  | runtime.doInit
		  | 	GOROOT/src/runtime/proc.go:6222
		  | runtime.main
		  | 	GOROOT/src/runtime/proc.go:233
		  | runtime.goexit
		  | 	GOROOT/src/runtime/asm_amd64.s:1571
		Wraps: (6) t.Fatal() was called
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.leafError
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-schema
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/during/kv.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by nvb**
Informs #84635.
Informs #84162.
Fixes #85449.
Fixes #83174.

This commit considers the `LeaseTransferRejectedBecauseTargetMayNeedSnapshot`
status to be a form of a retriable replication change error. It then hooks
`Replica.executeAdminCommandWithDescriptor` up to consult this status in its
retry loop.

This avoids spurious errors when a split gets blocked behind a lateral replica
move like we see in the following situation:
1. issue AdminSplit
2. range in joint config, first needs to leave (maybeLeaveAtomicChangeReplicas)
3. to leave, needs to transfer lease from voter_outgoing to voter_incoming
4. can’t transfer lease because doing so is deemed to be potentially unsafe

Release note: None

Release justification: Low risk, resolves flaky test.

### CODE REVIEW

**Review by shralex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85405)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @shralex)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85405#-N8PRpG4Cm6eCaTrElbY):*
Could be nice to have a test of this scenario or perhaps a simpler one (but I'll leave it to you to decide if one is needed)
___
*[`pkg/kv/kvserver/replica_command.go` line 564 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85405#-N8PROk0BymzJCQwv8aG:-N8PROk0BymzJCQwv8aH:b-gn8qua) ([raw file](https://github.com/cockroachdb/cockroach/blob/db2d653cc31d33b0077ad4bd99284ad469a6b4f5/pkg/kv/kvserver/replica_command.go#L564)):*
> ```Go
> 		// On seeing a retryable replication change or an AmbiguousResultError,
> 		// retry the command with the updated descriptor.
> 		if !IsRetriableReplicationChangeError(lastErr) &&
> ```

Just wanted to double check whether the change for ConditionFailedError is safe to do here ? is it a retriable error ?



_Code quote:_
```Go
On seeing a ConditionFailedError or an AmbiguousResultError
```

**Comment by msbutler** [comment]
friendly ping on this! Any reason not to merge this before the 22.2 branchcut and backport to 22.1?

**Review by nvb — COMMENTED** [review]
@shralex I added a unit test here, along with a second commit that adds some improved testing through kvnemesis.

I also found that this resolves #85449 and #83174.

Please take another look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85405#-:-NAjyr6zBANmc7Z4Bhoj:b-1sfo4p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @shralex)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85405#-N8PRpG4Cm6eCaTrElbY):*
<details><summary><i>Previously, shralex wrote…</i></summary><blockquote>

Could be nice to have a test of this scenario or perhaps a simpler one (but I'll leave it to you to decide if one is needed)
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/replica_command.go` line 564 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85405#-N8PROk0BymzJCQwv8aG:-NAjz3Dk7eE4dpQ4xLo6:b-9i2dks) ([raw file](https://github.com/cockroachdb/cockroach/blob/db2d653cc31d33b0077ad4bd99284ad469a6b4f5/pkg/kv/kvserver/replica_command.go#L564)):*
<details><summary><i>Previously, shralex wrote…</i></summary><blockquote>

Just wanted to double check whether the change for ConditionFailedError is safe to do here ? is it a retriable error ?
</blockquote></details>

The ConditionFailedError case is now considered by `IsRetriableReplicationChangeError`. So this has the same effect for those types of errors.

**Review by shralex — APPROVED** [review]
Thanks for adding the test, a cool use of filters!

> Reviewed 1 of 2 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85405#-:-NAoa2r0474HYab4RxqW:b-2g3lmf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @shralex)

___
*[`pkg/kv/kvnemesis/validator.go` line 498 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85405#-NAo_gRe048Vp2qIuJrm:-NAo_gRe048Vp2qIuJrn:b-ocn6jr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7778dd8102a6fe309f8ecec995a2650d8736869a/pkg/kv/kvnemesis/validator.go#L498)):*
> ```Go
> 		if err := errorFromResult(t.Result); err != nil {
> 			ignore = kvserver.IsLeaseTransferRejectedBecauseTargetMayNeedSnapshotError(err) ||
> 				// Only VOTER_FULL replicas can currently hold a range lease.
> ```

This explanation seems no longer correct.

**Review by nvb — COMMENTED** [review]
TFTR!

bors r=shralex

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85405#-:-NAouISdAe0qIJor-yka:bfx4uy2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @shralex)

___
*[`pkg/kv/kvnemesis/validator.go` line 498 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85405#-NAo_gRe048Vp2qIuJrm:-NAouKXm0PyYL18bSFHh:boj1qgt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7778dd8102a6fe309f8ecec995a2650d8736869a/pkg/kv/kvnemesis/validator.go#L498)):*
<details><summary><i>Previously, shralex wrote…</i></summary><blockquote>

This explanation seems no longer correct. 
</blockquote></details>

Good catch. Done.

**Comment by msbutler** [comment]
@nvanbenschoten thanks for this! Any chance this can be backported to 22.1? It would fix https://github.com/cockroachdb/cockroach/issues/84635

**Pull request merged**
