### PR TITLE
changefeedccl: add prototype of EXPERIMENTAL_CHANGEFEED

### PR DESCRIPTION
**Pull request by danhhz**
This implementation is a prototype that will be used to get early
feedback from users about whether the way we structure kafka
topics/partitions/encodings work for them.

It works by polling at a configurable interval (default 1 second). Each
poll picks a new highwater timestamp and sends a kv ExportRequest per
covered span. These requests are configured to return (inline in the
response) any kvs that were written between the previous highwater mark
and the new one. These responses are fed to a RowFetcher for conversion
to sql rows.

There is a 1:1 mapping between tables and which kafka topic they're
emitted to. The topic name is some prefix (an option in the sql command)
plus the table name. Each row is emitted as an kafka entry with key
unset and a json value mapping table field names to corresponding
datums. This format will almost certainly be tweaked in followup PRs but
this is sufficient to get everything working end-to-end with kafka
feeding into elasticsearch. Changed rows are emitted "at least once" and
may be duplicated if there are failures or restarts.

Changefeeds are kept as jobs and can be paused, resumed, and cancelled.

Current limitations:
- All changes are fed through a single node, limiting scalability and
  creating a hotspot on that node
- DELETEs don't work
- Schema changes are ignored
- Interleaved tables create duplicate entries
- Job progress is always 0% (bad ux)

Release note: None

@nvanbenschoten @tschottdorf I tried to start with a digestible chunk for this first prototype, hopefully I've succeeded. I feel pretty good about the balance of hacky-ness, with the exception of fetching the TableDescs once and saving them forever (violating our table leases). Thoughts on whether that's worth fixing in this first prototype and if so, how?

### CODE REVIEW

**Comment by bdarnell** [comment]
This looks great for a first prototype. 

---

Reviewed 5 of 5 files at r1, 5 of 5 files at r2, 11 of 11 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[Gopkg.lock, line 12 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24482#-L9LCVNfCJJFTwEn4eUP:-L9LCVNfCJJFTwEn4eUQ:b-2q48ef) ([raw file](https://github.com/cockroachdb/cockroach/blob/0048ea56e09d8096656a7cbf43f03dad32a792a9/Gopkg.lock#L12)):*
> ```
>     "internal/optional",
>     "internal/version",
>     "storage",
> ```

Are you using a different version of `dep` from our vendored version? It looks like it made a bunch of irrelevant changes. 

---

*[pkg/sql/jobs/jobs.proto, line 86 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24482#-L9LD-625NjR0kwRfONx:-L9LD-625NjR0kwRfONy:bqe32s2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffa13e2b6562a874626c221c77f9f9b287e3715c/pkg/sql/jobs/jobs.proto#L86)):*
> ```protobuf
>     int64 sst_size = 12 [(gogoproto.customname) = "SSTSize"];
>     int64 walltime = 13;
>     bool local = 14;
> ```

Un-reserving this doesn't feel right (even though it was also called `local` before).

---

*[pkg/sql/parser/sql.y, line 1756 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24482#-L9LCC4o9zGR1M08Rjos:-L9LCC4o9zGR1M08Rjot:b-9efef6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffa13e2b6562a874626c221c77f9f9b287e3715c/pkg/sql/parser/sql.y#L1756)):*
> ```Yacc
> 
> create_changefeed_stmt:
>   CREATE EXPERIMENTAL_CHANGEFEED EMIT targets TO KAFKA opt_as_of_clause opt_with_options
> ```

We shouldn't make `KAFKA` a keyword here (even an unreserved one; we don't have `BACKUP TO S3`). This would be better as a string.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24482#-:-L9LF4wlB4WkFRdxXLSH:b-1c6lam)*

**Comment by danhhz** [comment]
I switched from the official driver to the shopify one because the official driver delegates everything to librdkafka and I didn't feel like dealing with it for the prototype. It seems to be used by enough big names that I'm not so worried about the stability, but this will definitely be revisited in 2.1.

---

Review status: 1 of 20 files reviewed at latest revision, 3 unresolved discussions.

---

*[Gopkg.lock, line 12 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24482#-L9LCVNfCJJFTwEn4eUP:-L9LUqa_C1cCYn-ChxNY:bjsrhku) ([raw file](https://github.com/cockroachdb/cockroach/blob/0048ea56e09d8096656a7cbf43f03dad32a792a9/Gopkg.lock#L12)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Are you using a different version of `dep` from our vendored version? It looks like it made a bunch of irrelevant changes. 
</blockquote></details>

yeah, I forgot to use ./bin/dep when i did this

---

*[pkg/sql/jobs/jobs.proto, line 86 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24482#-L9LD-625NjR0kwRfONx:-L9LW4_lCx3lTEuN1IfO:b-1lu03s) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffa13e2b6562a874626c221c77f9f9b287e3715c/pkg/sql/jobs/jobs.proto#L86)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Un-reserving this doesn't feel right (even though it was also called `local` before).
</blockquote></details>

oops, bad rebase! good eye, fixed

---

*[pkg/sql/parser/sql.y, line 1756 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24482#-L9LCC4o9zGR1M08Rjos:-L9LZrPu3EiLYnIiluWt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffa13e2b6562a874626c221c77f9f9b287e3715c/pkg/sql/parser/sql.y#L1756)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

We shouldn't make `KAFKA` a keyword here (even an unreserved one; we don't have `BACKUP TO S3`). This would be better as a string.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24482#-:-L9LZztADqAG0ZH-2iF4:bcwojfa)*

**Comment by nvanbenschoten** [comment]
Reviewed 1 of 5 files at r1, 20 of 20 files at r4, 5 of 5 files at r5, 10 of 10 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/changefeedccl/changefeed.go, line 47 at r6](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24482#-L9LqcqV2DU0ZjqnC07b:-L9LqcqV2DU0ZjqnC07c:brs9zqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4454d3729cc2e6d7c64a445a99ef15c17e3710bb/pkg/ccl/changefeedccl/changefeed.go#L47)):*
> ```Go
> 	"changefeed.experimental_poll_interval",
> 	"polling interval for the prototype changefeed implementation",
> 	time.Second,
> ```

super nit: `1 * time.Second`

---

*[pkg/ccl/changefeedccl/changefeed.go, line 255 at r6](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24482#-L9LtYw3Bmog2PzoBjCa:-L9LtYw3Bmog2PzoBjCb:b-g19e1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/4454d3729cc2e6d7c64a445a99ef15c17e3710bb/pkg/ccl/changefeedccl/changefeed.go#L255)):*
> ```Go
> 		}
> 		for _, file := range res.(*roachpb.ExportResponse).Files {
> 			sst := engine.MakeRocksDBSstFileReader()
> ```

You might want to put this in a closure so that `sst.Close` is called immediately after you're done with each file and you don't hold all of these RocksDBSstFileReaders open at the same time.

---

*[pkg/sql/parser/parse_test.go, line 945 at r4](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24482#-L9Ln2LE7LebLe2FOWd6:-L9Ln2LE7LebLe2FOWd7:bylo5zo) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac0feae3771ac45322d3764c567e2153aa6e1154/pkg/sql/parser/parse_test.go#L945)):*
> ```Go
> 
> 		{`CREATE EXPERIMENTAL_CHANGEFEED EMIT foo TO kafka`},
> 		{`CREATE EXPERIMENTAL_CHANGEFEED EMIT foo TO kafka WITH topic_prefix = 'bar'`},
> ```

Add one more case: 
```
{`CREATE EXPERIMENTAL_CHANGEFEED EMIT TABLE foo TO kafka`},
```

---

*[pkg/sql/sem/tree/stmt.go, line 236 at r4](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24482#-L9LneDyCiBKLXzSSrE8:-L9LneDyCiBKLXzSSrE9:b-m0cmqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac0feae3771ac45322d3764c567e2153aa6e1154/pkg/sql/sem/tree/stmt.go#L236)):*
> ```Go
> 
> // StatementType implements the Statement interface.
> func (*CreateChangefeed) StatementType() StatementType { return Rows }
> ```

What rows does this return?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24482)*

**Comment by danhhz** [comment]
Responded to comments and added some tests (and fixed some bugs the tests found)

---

Review status: 17 of 20 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/changefeedccl/changefeed.go, line 47 at r6](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24482#-L9LqcqV2DU0ZjqnC07b:-L9M9GRL3t3lpWa7uccz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4454d3729cc2e6d7c64a445a99ef15c17e3710bb/pkg/ccl/changefeedccl/changefeed.go#L47)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

super nit: `1 * time.Second`
</blockquote></details>

Done.

---

*[pkg/ccl/changefeedccl/changefeed.go, line 255 at r6](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24482#-L9LtYw3Bmog2PzoBjCa:-L9M8rrSBzIZVou8VmKG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4454d3729cc2e6d7c64a445a99ef15c17e3710bb/pkg/ccl/changefeedccl/changefeed.go#L255)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

You might want to put this in a closure so that `sst.Close` is called immediately after you're done with each file and you don't hold all of these RocksDBSstFileReaders open at the same time.
</blockquote></details>

Done.

---

*[pkg/sql/parser/parse_test.go, line 945 at r4](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24482#-L9Ln2LE7LebLe2FOWd6:-L9M97gG42F76zvaE2hK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac0feae3771ac45322d3764c567e2153aa6e1154/pkg/sql/parser/parse_test.go#L945)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Add one more case: 
```
{`CREATE EXPERIMENTAL_CHANGEFEED EMIT TABLE foo TO kafka`},
```
</blockquote></details>

Done.

---

*[pkg/sql/sem/tree/stmt.go, line 236 at r4](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24482#-L9LneDyCiBKLXzSSrE8:-L9M99IH3zmMzt5rRhrT:bj8d7uw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac0feae3771ac45322d3764c567e2153aa6e1154/pkg/sql/sem/tree/stmt.go#L236)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What rows does this return?
</blockquote></details>

The jobID so you can stash it somewhere and pause/cancel later.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24482#-:-L9MXaaP63bAjt6NoSJ0:b-b9dgdf)*

**Comment by danhhz** [comment]
TFTR! Besides the teamcity stress failures (which haven't yet reproduced locally), I think this is ready to go. Anyone wanna give an lgtm?

FYI, I ran this against tpcc-100 on a 3 node roachprod cluster and it seemed to keep up okay. Batches of changes were showing up in kafka every 8-10 seconds or so (instead of 1 second), which I've got to investigate, but it seemed stable for the ~30m that I ran it. I accidentally set every thing up on the wrong machine type for tpcc-1000 and it takes a while to set up, so I didn't get a chance to see where it breaks down.

> Looks really good. For the table leases, I'm not familiar with how difficult it would be to do the "right thing", but likely it's harder to figure out the "right thing" in the first place.

> How do we want a change feed to handle schema changes? If you add a new column and there's a pre-existing changefeed, I suppose it makes sense if the changefeed remains active and omits the column. Dropping a column that is part of an ongoing changefeed seems like something that should catch an error, though maybe one you should be able to override? And there are many more types of schema changes.

> Making the interaction of changefeeds with online schema changes predictable and smooth is going to be important. I think it's fine to punt on this for now as long as we work on getting an idea of what we ultimately want it to be.

Yeah, I forgot to mention this, but I'd more or less convinced myself over the last day that switching to table leases is fine as a followup. The Confluent Platform has already thought about schema evolution a bit. They have a schema registry and the various connectors have different levels of support for schema changes. Elasticsearch, for example, supports just about everything while hdfs+hive has to be more restrictive. I have more research to do here.

---

Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24482#-:-L9MrIbM-eg0N5Z4S7IS:b-yaljg9)*

**Comment by danhhz** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/changefeedccl/changefeed.go, line 357 at r7](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24482#-L9MdMPU3DXU9EAl1-b_:-L9Mu8m-9AHfXvUw0E09:b-lj6sbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a83b2ee605a1bff80335bb808188ee0c70924ce/pkg/ccl/changefeedccl/changefeed.go#L357)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Probably want to measure the number of messages sent or something like that. Perhaps the notion of "progress" can be generalized so that it's (morally) an `enum { PERCENTAGE, AMOUNT }`.
</blockquote></details>

Yeah, number of messages is a nice idea!

---

*[pkg/ccl/changefeedccl/changefeed_test.go, line 74 at r7](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24482#-L9MdsOA5btpab7F7MCH:-L9MuEchE7__dHWj8_rx:bopr0r9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a83b2ee605a1bff80335bb808188ee0c70924ce/pkg/ccl/changefeedccl/changefeed_test.go#L74)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

What's this for?
</blockquote></details>

Heh, the R in CRUD. I was wondering if that'd be confusing, I'll remove this and update the test name.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24482)*

**Comment by tschottdorf** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24482#-:-L9MvtNEATsQxepwl6QN:bnfp4nl)*

**Comment by danhhz** [comment]
Thanks for the reviews, all!

**Pull request merged**
