### PR TITLE
storage: expose additional engine metrics

### LINKED ISSUE #43965: storage/engine: expose more engine metrics
See also #41265

We should add various compaction related metrics. Bytes flushed. Bytes compacted. Bytes ingested. Estimated compaction debt. The latter, in particular, can indicate compactions falling behind.

### PR DESCRIPTION
**Pull request by jbowens**
Release justification: low-risk update to new functionality

Fixes #43965

Release note: none

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
This looks very much like what I was expecting. I have a few small comments below. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46558#-:-M3ID3AoEZjAN5k8io41:b-9l8hps)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @jbowens)

___
*[pkg/kv/kvserver/metrics.go, line 354 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46558#-M3HcZbe1_hahJ-MyLog:-M3HcZbe1_hahJ-MyLoh:b-oy0ahs) ([raw file](https://github.com/cockroachdb/cockroach/blob/e047c02b80137a599ca89d8cf29db571a94b1ae5/pkg/kv/kvserver/metrics.go#L354)):*
> ```Go
> 	}
> 	metaRdbCompactionBytesIngested = metric.Metadata{
> 		Name:        "rocksdb.compaction.bytes-ingested",
> ```

Ingested and compaction are separate concepts. Ingested bytes are not compacted. Compacted bytes are not ingested. I think this should be named `rocksdb.ingested-bytes` instead. The `Help` text will also need adjustment. It might be worthwhile chatting with myself or @itsbilal about the difference between ingestion and compaction.
___
*[pkg/storage/engine.go, line 486 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46558#-M3HdHCK4L0AGD3lmeqz:-M3HdHCK4L0AGD3lmer-:b-gqrve8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e047c02b80137a599ca89d8cf29db571a94b1ae5/pkg/storage/engine.go#L486)):*
> ```Go
> 	MemtableTotalSize              int64
> 	Flushes                        int64
> 	FlushBytes                     int64
> ```

Nit: Let's consistently use past tense. This would become `FlushedBytes`.
___
*[pkg/storage/engine.go, line 488 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46558#-M3HdAoeBVNxnPGUQiVf:-M3HdAof9Gx_OVtqemwR:b9ae3u8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e047c02b80137a599ca89d8cf29db571a94b1ae5/pkg/storage/engine.go#L488)):*
> ```Go
> 	FlushBytes                     int64
> 	Compactions                    int64
> 	CompactionBytesIngested        int64 // (Pebble only)
> ```

Similar to other comment, this should be `IngestedBytes`.
___
*[pkg/storage/engine.go, line 490 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46558#-M3HdOcU9Ae1Lk16Wmo0:-M3HdOcU9Ae1Lk16Wmo1:b-vdp1mq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e047c02b80137a599ca89d8cf29db571a94b1ae5/pkg/storage/engine.go#L490)):*
> ```Go
> 	CompactionBytesIngested        int64 // (Pebble only)
> 	CompactionBytesRead            int64
> 	CompactionBytesWritten         int64
> ```

Nit: per above: `CompactedBytesRead` and `CompactedBytesWritten`.
___
*[pkg/ts/catalog/chart_catalog.go, line 1838 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46558#-M3ICmmr8XBA1KIEjN0S:-M3ICmmr8XBA1KIEjN0T:b-thbpeh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e047c02b80137a599ca89d8cf29db571a94b1ae5/pkg/ts/catalog/chart_catalog.go#L1838)):*
> ```Go
> 			},
> 			{
> 				Title:   "Flushed Bytes",
> ```

How do these `sectionDescriptions` show up in the admin UI? Compaction and flushing are related, so I could see a combined `Flush and Compaction` section instead of having them separate.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46558)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

___
*[pkg/kv/kvserver/metrics.go, line 354 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46558#-M3HcZbe1_hahJ-MyLog:-M3MFiOC3XO7Wfi4yh9x:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e047c02b80137a599ca89d8cf29db571a94b1ae5/pkg/kv/kvserver/metrics.go#L354)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ingested and compaction are separate concepts. Ingested bytes are not compacted. Compacted bytes are not ingested. I think this should be named `rocksdb.ingested-bytes` instead. The `Help` text will also need adjustment. It might be worthwhile chatting with myself or @itsbilal about the difference between ingestion and compaction.
</blockquote></details>

Done.
___
*[pkg/storage/engine.go, line 488 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46558#-M3HdAoeBVNxnPGUQiVf:-M3MJFtY1wyyNP91dMwp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e047c02b80137a599ca89d8cf29db571a94b1ae5/pkg/storage/engine.go#L488)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Similar to other comment, this should be `IngestedBytes`.
</blockquote></details>

Done.
___
*[pkg/ts/catalog/chart_catalog.go, line 1838 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46558#-M3ICmmr8XBA1KIEjN0S:-M3MJkjm-TkpPQf3noYk:b10f333) ([raw file](https://github.com/cockroachdb/cockroach/blob/e047c02b80137a599ca89d8cf29db571a94b1ae5/pkg/ts/catalog/chart_catalog.go#L1838)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

How do these `sectionDescriptions` show up in the admin UI? Compaction and flushing are related, so I could see a combined `Flush and Compaction` section instead of having them separate.
</blockquote></details>

As far as I can tell, these sectionDescriptions are unused. They're surfaced by the /_admin/v1/chartcatalog endpoint, but I wasn't unable to find any consumers of that endpoint. The structure of the graphs under the metrics tab looks like it is specified within the Admin UI's JSX ([dashboards/storage.tsx](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/storage.tsx)).

There is still [a unit test](https://github.com/cockroachdb/cockroach/blob/master/pkg/server/status_test.go#L812-L854) requiring that every metric appear in the chart catalog, which is why I added these here. I'm not sure if that's just a vestige from an older iteration of the Admin UI? The custom chart endpoint also appears to get its list of metrics through a separate /_admin/v1/metricmetadata endpoint, which pulls its data right from the registry, not the catalog.

**Review by petermattis — APPROVED** [review]
:lgtm: modulo one final nit to resolve

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46558#-:-M3MUL_1-FCgZK4347Az:bh707cd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @jbowens)

___
*[pkg/kv/kvserver/metrics.go, line 360 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46558#-M3MTleA1yznDZ1DqyCe:-M3MTleA1yznDZ1DqyCf:br0l9rs) ([raw file](https://github.com/cockroachdb/cockroach/blob/489fb144f29850dc080b4f00438bce34fdaa72a6/pkg/kv/kvserver/metrics.go#L360)):*
> ```Go
> 	}
> 	metaRdbCompactedBytesRead = metric.Metadata{
> 		Name:        "rocksdb.compaction.bytes-read",
> ```

Nit: should this be `rocksdb.compacted-bytes-read`? That would be more consistent with the variable names and the `rocksdb.{flushed,ingested}-bytes` metrics. I don't believe the dots signify anything particularly important other than grouping. And not all of the existing compaction metrics have the `rocksdb.compaction` prefix (e.g. `rocksdb.estimated-pending-compaction`). 
___
*[pkg/ts/catalog/chart_catalog.go, line 1838 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46558#-M3ICmmr8XBA1KIEjN0S:-M3MTfx86iwppukhAbFJ:bsbhsks) ([raw file](https://github.com/cockroachdb/cockroach/blob/e047c02b80137a599ca89d8cf29db571a94b1ae5/pkg/ts/catalog/chart_catalog.go#L1838)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

As far as I can tell, these sectionDescriptions are unused. They're surfaced by the /_admin/v1/chartcatalog endpoint, but I wasn't unable to find any consumers of that endpoint. The structure of the graphs under the metrics tab looks like it is specified within the Admin UI's JSX ([dashboards/storage.tsx](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/storage.tsx)).

There is still [a unit test](https://github.com/cockroachdb/cockroach/blob/master/pkg/server/status_test.go#L812-L854) requiring that every metric appear in the chart catalog, which is why I added these here. I'm not sure if that's just a vestige from an older iteration of the Admin UI? The custom chart endpoint also appears to get its list of metrics through a separate /_admin/v1/metricmetadata endpoint, which pulls its data right from the registry, not the catalog.
</blockquote></details>

Ack. Thanks for taking a look.

**Review by itsbilal — APPROVED** [review]
:LGTM: aside from what Peter said

I imagine we'd have to ditch the `rocksdb.` prefix for all metrics at some point too, but that can wait for some point in 20.2. 

> Reviewed 1 of 8 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46558#-:-M3MXTRc5K7RjxQEJLfA:bjvvb4z)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @jbowens)

**Pull request merged**
