### PR TITLE
bench/ddl_analysis: fix subtests

### PR DESCRIPTION
**Pull request by ajwerner**
Before this commit, we'd call `g.Done()` inside the subtest but if the --run
flag did include all subtests, then we'd hang forever. This is solved by
dealing with the wait group above the subtest.

Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62038)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/bench/ddl_analysis/validate_benchmark_data_test.go, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62038#-MVrpVtS26G05lypp2Wn:-MVrpVtT7G8fWs2NQ3of:b-n5s4vw) ([raw file](https://github.com/cockroachdb/cockroach/blob/afc5903afa182ef042026d07104ce8d2c022c3d3/pkg/bench/ddl_analysis/validate_benchmark_data_test.go#L128)):*
> ```Go
> 		}
> 		g.Add(1)
> 		go func() {
> ```

would it be simpler to write with `errgroup.Go` so the function completion is recorded automatically? https://pkg.go.dev/golang.org/x/sync/errgroup#Group.Go

i'll leave it up to you; change lgtm

**Comment by ajwerner** [comment]
The errgroup thing didn't do much for me for that case. I did fix some other things in the meantime.

**Comment by ajwerner** [comment]
I'm borsing this so I can get the backports going to get https://github.com/cockroachdb/cockroach/pull/61820 backported. Feel free to provide retrospective feedback. 

bors r+

**Comment by rafiss** [comment]
lgtm!

**Pull request merged**
