### PR TITLE
sql: remove three KV lookups from pg_catalog queries

### PR DESCRIPTION
**Pull request by rafiss**
Use the descriptors that have already been fetched, instead of
re-getting them.

Release note: None

### CODE REVIEW

**Comment by rafiss** [comment]
i heard @ajwerner may find this interesting, but even if you don't, i am once again thanking you for sprucing up the benchmark thingy

**Review by ajwerner — APPROVED** [review]
:lgtm: 

I would prefer you use the methods on the internalLookupCtx.

Also, while I hear you like hearing about plans, the days of the internalLookupCtx are numbered. I'm going to pull it entirely underneath the descs.Collection. 

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62216#-:-MW6Ig9s1J-SxIK3Ad2h:b-14lr7d)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by rafiss** [comment]
Awesome! yeah @arulajmani had mentioned to me that you're working on `internalLookupCtx` which is why I thought you might be interested.

**Review by arulajmani — APPROVED** [review]
Good stuff!  :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62216#-:-MWBGJ_D3XfqeKoXOmLL:b-j4vcn)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

**Comment by rafiss** [comment]
i found one more to get rid of here: https://github.com/cockroachdb/cockroach/blob/a5bea8c7fbb979de7e0014bc7ced35a34a209dfc/pkg/sql/information_schema.go#L1856

And to bring all pg_catalog queries down to one lookup, the last one is here: https://github.com/cockroachdb/cockroach/blob/a5bea8c7fbb979de7e0014bc7ced35a34a209dfc/pkg/sql/opt_catalog.go#L1740

I'll have one more commit to fix the first one. I'll keep thinking through how to improve the second one, unless @RaduBerinde has an idea already.

**Comment by rafiss** [comment]
Oh, though actually, the lookup in `opt_catalog.go` actually is from fetching the DB descriptor, which maybe is unavoidable at that point...

**Review by arulajmani — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62216)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @arulajmani and @rafiss)

___
*[pkg/sql/information_schema.go, line 1857 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62216#-MWBVryFBbKDssfeuqNq:-MWBVryFBbKDssfeuqNr:b-ilpffu) ([raw file](https://github.com/cockroachdb/cockroach/blob/88783388bbfd126d02abca80130a2183273cb2d0/pkg/sql/information_schema.go#L1857)):*
> ```Go
> 		// with privileges from kv.
> 		found, fetchedDbDesc, err := p.Descriptors().GetImmutableDatabaseByID(
> 			ctx, p.txn, dbContext.GetID(), tree.DatabaseLookupFlags{Required: true, AvoidCached: p.avoidCachedDescriptors},
> ```

I have a few questions about this -- what is the value of `p.avoidCachedDescriptors` here? Can it ever be false? If it is false, are we certain a leased descriptor would suffice?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62216)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @arulajmani)

___
*[pkg/sql/information_schema.go, line 1857 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62216#-MWBVryFBbKDssfeuqNq:-MWBWLaD3wh4SmGYwojm:bh99v25) ([raw file](https://github.com/cockroachdb/cockroach/blob/88783388bbfd126d02abca80130a2183273cb2d0/pkg/sql/information_schema.go#L1857)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I have a few questions about this -- what is the value of `p.avoidCachedDescriptors` here? Can it ever be false? If it is false, are we certain a leased descriptor would suffice?
</blockquote></details>

good questions. i think it usually is false in fact.

i'll dig in a bit more. i think the comment about privileges missing on `dbContext` might be outdated and we can just go ahead and use that.

**Review by arulajmani — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62216)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @arulajmani and @rafiss)

___
*[pkg/sql/information_schema.go, line 1857 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62216#-MWBVryFBbKDssfeuqNq:-MWBkJoh-U5q8ioA50_q:bofpwa9) ([raw file](https://github.com/cockroachdb/cockroach/blob/88783388bbfd126d02abca80130a2183273cb2d0/pkg/sql/information_schema.go#L1857)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

good questions. i think it usually is false in fact.

i'll dig in a bit more. i think the comment about privileges missing on `dbContext` might be outdated and we can just go ahead and use that.
</blockquote></details>

Now that I'm looking at this again, I don't think using dbContext and reading possibly stale privileges off it here is safe. 

One optimization I see is we could move the `requiresPrivileges` check before this lookup is made. Another thing you could do is remove the catalogkv call and replace it with a call to the descriptor collection much like you have here, except pass in `AvoidCached` explicitly as true. Maybe we've cached this thing further up the stack and we may still prevent a roundtrip?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62216)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @arulajmani)

___
*[pkg/sql/information_schema.go, line 1857 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62216#-MWBVryFBbKDssfeuqNq:-MWC-PVE9AvzuDk2fizK:b5wrqr9) ([raw file](https://github.com/cockroachdb/cockroach/blob/88783388bbfd126d02abca80130a2183273cb2d0/pkg/sql/information_schema.go#L1857)):*
what makes you feel that the `dbContext` would have stale privileges? virtual tables are generated on-demand so the `dbDesc` here should be the same as the one that we'd fetch again

> pass in AvoidCached explicitly as true. Maybe we've cached this thing further up the stack and we may still prevent a roundtrip?

i don't understand. if we set `AvoidCached=true` then we will not use whichever thing has been cached previously, right?


btw, the dbDesc was fetched here:

https://github.com/cockroachdb/cockroach/blob/3d19b2cf6b290a152b23722fc32e995eed3b437b/pkg/sql/virtual_schema.go#L470-L490

**Review by arulajmani — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62216)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @arulajmani and @rafiss)

___
*[pkg/sql/information_schema.go, line 1857 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62216#-MWBVryFBbKDssfeuqNq:-MWF3pfbA1Mk00jLaTsG:b60dhzz) ([raw file](https://github.com/cockroachdb/cockroach/blob/88783388bbfd126d02abca80130a2183273cb2d0/pkg/sql/information_schema.go#L1857)):*
> what makes you feel that the dbContext would have stale privileges?

dbContext is an Immutable db desc, so as such, it can either be a leased descriptor or one that was read from the store. Having a leased descriptor here could be problematic if:
- The version is at v -1 
- The bump to version v was caused because of a privilege change. 

We care about this right? Unless we make a special exception for virtual tables that Im not aware of?

>  don't understand. if we set AvoidCached=true then we will not use whichever thing has been cached previously, right?

There's a few levels of caching here, so let me expand. Setting AvoidCached means that we go to the store and don't return a leased descriptor. Once we've been to the store, the descriptor is cached in `uncommittedDescriptors`-- every subsequent access in the same (SQL) transaction first checks uncommittedDescriptors before going to the store, regardless of the `AvoidCached` flag. So in your case you're guaranteed one and exactly one store access. 

> btw, the dbDesc was fetched here:

I think it cane be stale then, if p.avoidCachedDescriptors is false there.

**Comment by rafiss** [comment]
@arulajmani PTAL

summarizing our discussion here for anyone else reading

the “normal” privilege checks for tables happen here https://github.com/cockroachdb/cockroach/blob/9dcbddc77a64022c7b135d6e176709dd4026733e/pkg/sql/opt/optbuilder/util.go#L579

the descriptor that is fetched there also may be a leased one so there's no harm in using the same descriptor here

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62216#-:-MWfFMj-3MX6o0rLjlT0:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani and @rafiss)

**Comment by rafiss** [comment]
tftrs!

bors r=ajwerner,arulajmani

**Pull request merged**
