### PR TITLE
util/mon: introduce `MonitorName` and reduce allocations

### LINKED ISSUE #136628: sql: reduce allocations in `distsql.(*ServerImpl).setupFlow` (~1% allocs)
image

image

Jira issue: CRDB-45174

### PR DESCRIPTION
**Pull request by mgartner**
#### util/uuid: add `Short` type and `(UUID).Short` method

The `uuid.Short` type and `(UUID).Short` method have been added. These
allow for shortened UUIDs to be represented in 4 bytes without
allocating a string.

Release note: None

#### util/mon: remove `BytesMonitor` size assertion under race

The size of `BytesMonitor` in race builds is not really a concern for
us. We are only concerned with its size in production builds. This
commit removes this unneeded assertion.

Release note: None

#### util/mon: introduce `MonitorName`

The `MonitorName` type is now used for naming memory monitors. This type
includes an optional short UUID, helping reduce allocations in a hot
path that added the first 8 bytes of a UUID to the monitor name. Now,
the short UUID is included in `MonitorName` allocation free. Allocations
to combine the short UUID with the name's prefix in a contiguous string
are only incurred if expensive logging is enabled.

Fixes #136628

Release note: None

#### util/mon: use `redact.SafeString` for monitor names

Monitor names are now created with `redact.SafeString`s instead of
`redact.RedactableString`s. The `redact.SafeString` type is a better fit
because monitor names should never contain sensitive information. The
type system now forces callers to confirm that the given name is safe.

Release note: None

#### sql: remove username from internal planner monitor name

The username is not necessary for this monitor name. The op name should
be sufficient in tracking down the source of this planner and monitor.

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
Some benchmark results:

```
name                                     old time/op    new time/op    delta
EndToEnd/kv-read/vectorize=on/Simple        193µs ± 2%     193µs ± 2%    ~     (p=0.690 n=5+5)
EndToEnd/kv-read/vectorize=on/Prepared      132µs ± 1%     131µs ± 1%    ~     (p=0.421 n=5+5)
EndToEnd/kv-read/vectorize=off/Simple       192µs ± 1%     193µs ± 1%    ~     (p=0.548 n=5+5)
EndToEnd/kv-read/vectorize=off/Prepared     128µs ± 1%     128µs ± 7%    ~     (p=0.151 n=5+5)

name                                     old alloc/op   new alloc/op   delta
EndToEnd/kv-read/vectorize=on/Simple       36.5kB ± 6%    36.4kB ± 6%    ~     (p=0.548 n=5+5)
EndToEnd/kv-read/vectorize=on/Prepared     25.3kB ± 8%    24.5kB ± 0%    ~     (p=0.206 n=5+4)
EndToEnd/kv-read/vectorize=off/Simple      36.8kB ± 0%    36.7kB ± 0%    ~     (p=0.714 n=5+4)
EndToEnd/kv-read/vectorize=off/Prepared    26.6kB ± 6%    26.2kB ± 4%    ~     (p=0.421 n=5+5)

name                                     old allocs/op  new allocs/op  delta
EndToEnd/kv-read/vectorize=on/Simple          312 ± 4%       310 ± 4%    ~     (p=0.278 n=5+5)
EndToEnd/kv-read/vectorize=on/Prepared        225 ± 7%       218 ± 0%  -2.91%  (p=0.000 n=5+4)
EndToEnd/kv-read/vectorize=off/Simple         300 ± 0%       298 ± 0%  -0.83%  (p=0.029 n=4+4)
EndToEnd/kv-read/vectorize=off/Prepared       212 ± 0%       211 ± 0%  -0.71%  (p=0.029 n=4+4)
```

```
name                                        old time/op    new time/op    delta
FlowSetup/vectorize=true/distribute=true      80.5µs ± 1%    81.2µs ± 1%  +0.92%  (p=0.032 n=5+5)
FlowSetup/vectorize=true/distribute=false     72.8µs ± 1%    72.9µs ± 2%    ~     (p=0.841 n=5+5)
FlowSetup/vectorize=false/distribute=true     73.8µs ± 2%    74.9µs ± 3%    ~     (p=0.310 n=5+5)
FlowSetup/vectorize=false/distribute=false    66.5µs ± 1%    67.1µs ± 2%    ~     (p=0.421 n=5+5)

name                                        old alloc/op   new alloc/op   delta
FlowSetup/vectorize=true/distribute=true      18.8kB ± 1%    18.8kB ± 1%    ~     (p=0.690 n=5+5)
FlowSetup/vectorize=true/distribute=false     15.6kB ± 0%    15.6kB ± 1%    ~     (p=0.548 n=5+5)
FlowSetup/vectorize=false/distribute=true     25.8kB ± 4%    25.4kB ± 0%  -1.24%  (p=0.040 n=5+5)
FlowSetup/vectorize=false/distribute=false    22.9kB ± 5%    22.9kB ± 6%    ~     (p=0.508 n=5+5)

name                                        old allocs/op  new allocs/op  delta
FlowSetup/vectorize=true/distribute=true         188 ± 0%       186 ± 0%  -1.06%  (p=0.029 n=4+4)
FlowSetup/vectorize=true/distribute=false        163 ± 0%       161 ± 0%  -1.23%  (p=0.000 n=5+4)
FlowSetup/vectorize=false/distribute=true        189 ± 3%       184 ± 0%  -2.44%  (p=0.008 n=5+5)
FlowSetup/vectorize=false/distribute=false       161 ± 0%       159 ± 0%  -1.24%  (p=0.029 n=4+4)
```

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136636#-:-ODE22sZ44c__ddQwcTE:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @asg0451, @dhartunian, @jeffswenson, and @michae2)

**Review by yuzefovich — COMMENTED** [review]
Nice! I have some questions about redaction to consider.

> Reviewed 72 of 72 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136636#-:-ODE5gXlD2vmTyd5sDY-:b646hn)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @asg0451, @dhartunian, @jeffswenson, @mgartner, and @michae2)

___
*[`pkg/util/mon/bytes_usage.go` line 301 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136636#-ODE48z478MByJ3E9jGW:-ODE48z5DhRDJ6-mtIGn:bv8ybsp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f48230dbb971fbe7f522bf739fe59ed20cc72a7e/pkg/util/mon/bytes_usage.go#L301)):*
> ```Go
> 	var nullBytes [8]byte
> 	if mn.suffix != nullBytes {
> 		return string(mn.name.Redact()) + string(mn.suffix[:])
> ```

Hm, in a couple of places we used to do `string(mm.name)` which is different from calling `mm.name.Redact()`. All monitor names should not contain any unsafe bits, so perhaps the end result is the same, but I'm curious whether switching to `Redact()` was a deliberate choice on your part.
___
*[`pkg/util/mon/bytes_usage.go` line 309 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136636#-ODE2itiAxxOtYHMarDM:-ODE2itjDLNbNtrvOlXa:b-b7vq6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/f48230dbb971fbe7f522bf739fe59ed20cc72a7e/pkg/util/mon/bytes_usage.go#L309)):*
> ```Go
> 	// Consult with SQL Queries before increasing these values.
> 	expectedMonitorSize     = 168
> 	expectedMonitorSizeRace = 168
> ```

This also needs a bump of 8 bytes.
___
*[`pkg/util/mon/bytes_usage.go` line 551 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136636#-ODE53pYE2YKN-8-2Dpu:-ODE53pYE2YKN-8-2Dpv:b-cnrne0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f48230dbb971fbe7f522bf739fe59ed20cc72a7e/pkg/util/mon/bytes_usage.go#L551)):*
> ```Go
> 	mm.reserved = reserved
> 	if log.V(2) {
> 		poolname := "(none)"
> ```

Hm, I think this way `poolname` becomes `string` type, so it should be fully redacted in the logs which seems undesirable.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136636)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asg0451, @dhartunian, @jeffswenson, @michae2, and @yuzefovich)

___
*[`pkg/util/mon/bytes_usage.go` line 301 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136636#-ODE48z478MByJ3E9jGW:-ODMXD_t6EAqEuT7EFWF:bnxwxai) ([raw file](https://github.com/cockroachdb/cockroach/blob/f48230dbb971fbe7f522bf739fe59ed20cc72a7e/pkg/util/mon/bytes_usage.go#L301)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, in a couple of places we used to do `string(mm.name)` which is different from calling `mm.name.Redact()`. All monitor names should not contain any unsafe bits, so perhaps the end result is the same, but I'm curious whether switching to `Redact()` was a deliberate choice on your part.
</blockquote></details>

Good catch. I've changed the implementation here—PTAL.
___
*[`pkg/util/mon/bytes_usage.go` line 309 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136636#-ODE2itiAxxOtYHMarDM:-ODMYDDO8VaaWP3zGQHg:b-b3012b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f48230dbb971fbe7f522bf739fe59ed20cc72a7e/pkg/util/mon/bytes_usage.go#L309)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

This also needs a bump of 8 bytes.
</blockquote></details>

I've removed the assertion under race builds.
___
*[`pkg/util/mon/bytes_usage.go` line 551 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136636#-ODE53pYE2YKN-8-2Dpu:-ODMYm1C2lUIK2PQ5yAe:b61nsnu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f48230dbb971fbe7f522bf739fe59ed20cc72a7e/pkg/util/mon/bytes_usage.go#L551)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, I think this way `poolname` becomes `string` type, so it should be fully redacted in the logs which seems undesirable.
</blockquote></details>

Changed it to `redact.SafeString`.

**Review by yuzefovich — APPROVED** [review]
Nice cleanup! :lgtm:

> Reviewed 77 of 77 files at r3, 1 of 1 files at r4, 71 of 71 files at r5, 14 of 14 files at r6, 15 of 15 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136636#-:-ODNO5A0DWcnNttNDA3c:b-jy7zf3)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @asg0451, @dhartunian, @jeffswenson, @mgartner, and @michae2)

___
*[`pkg/util/mon/bytes_usage.go` line 294 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/136636#-ODNKgo51jXQc6jEm0gb:-ODNKgo51jXQc6jEm0gc:b72c7dn) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f5803a457e931edd393f11f7c71944f3f7f358c/pkg/util/mon/bytes_usage.go#L294)):*
> ```Go
> }
> 
> // MakeMonitorNameWithID constructs a MonitorName with the given name and
> ```

nit: the comment needs an adjustment.
___
*[`pkg/sql/planner.go` line 408 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/136636#-ODNMQHJ7qJ_QqIVWfO7:-ODNMQHKCCMlnjqspQft:b-2h0scp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e6d3f53d750cf88a7b9ae5ffe9cccc741b9dda4/pkg/sql/planner.go#L408)):*
> ```Go
> 		Name: mon.MakeMonitorName(
> 			"internal-planner." +
> 				redact.SafeString(user.Normalized()) + "." +
> ```

Hm, I'm still a bit concerned about this. I think I found at least one case where non-internal user can be passed here - in CDC queries in `withPlanner` we create an internal planner with - AFAICT - a user that is equal to the session's user. It seems like jobs issues on behalf of the user might also use the session's user.

I'd probably lean on the safe side here and treat the username as unsafe since I doubt having the username unredacted will be important in this case.
___
*[`pkg/util/uuid/uuid_wrapper.go` line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/136636#-ODNJubi3QBhnMGPBoQL:-ODNJubi3QBhnMGPBoQM:b12pao0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3db6352180157b69f839e219d147ea20e4c0a8ae/pkg/util/uuid/uuid_wrapper.go#L27)):*
> ```Go
> }
> 
> // String returns the 8-character hexidemical representation of the abbreviated
> ```

nit: `s/hexidemical/hexadecimal/`.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136636)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asg0451, @dhartunian, @jeffswenson, @michae2, and @yuzefovich)

___
*[`pkg/sql/planner.go` line 408 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/136636#-ODNMQHJ7qJ_QqIVWfO7:-ODOHha65Xk-_dyB7RV3:b-xf9s54) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e6d3f53d750cf88a7b9ae5ffe9cccc741b9dda4/pkg/sql/planner.go#L408)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, I'm still a bit concerned about this. I think I found at least one case where non-internal user can be passed here - in CDC queries in `withPlanner` we create an internal planner with - AFAICT - a user that is equal to the session's user. It seems like jobs issues on behalf of the user might also use the session's user.

I'd probably lean on the safe side here and treat the username as unsafe since I doubt having the username unredacted will be important in this case.
</blockquote></details>

If we want to treat the username as unsafe, then I see only two options:

1. Drop the last commit and leave the name as a `redact.RedactableString`, or
2. Remove the username from this monitor name.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 65 of 70 files at r11, 15 of 15 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136636)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asg0451, @dhartunian, @jeffswenson, @mgartner, and @michae2)

___
*[`pkg/sql/planner.go` line 408 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/136636#-ODNMQHJ7qJ_QqIVWfO7:-ODONecmA0aTwCxUVTvb:bbfa8ws) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e6d3f53d750cf88a7b9ae5ffe9cccc741b9dda4/pkg/sql/planner.go#L408)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

If we want to treat the username as unsafe, then I see only two options:

1. Drop the last commit and leave the name as a `redact.RedactableString`, or
2. Remove the username from this monitor name.
</blockquote></details>

Yeah, let's remove the user name altogether - I think `opName` is far more important here, and from that we could determine the call site (which most likely will allow us to determine the user name as well).

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136636)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asg0451, @dhartunian, @jeffswenson, @michae2, and @yuzefovich)

___
*[`pkg/sql/planner.go` line 408 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/136636#-ODNMQHJ7qJ_QqIVWfO7:-ODRbAw021s8Maxd31Oo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e6d3f53d750cf88a7b9ae5ffe9cccc741b9dda4/pkg/sql/planner.go#L408)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Yeah, let's remove the user name altogether - I think `opName` is far more important here, and from that we could determine the call site (which most likely will allow us to determine the user name as well).
</blockquote></details>

Done.
___
*[`pkg/util/mon/bytes_usage.go` line 294 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/136636#-ODNKgo51jXQc6jEm0gb:-ODRZO4BApYh7Ju_gS1K:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f5803a457e931edd393f11f7c71944f3f7f358c/pkg/util/mon/bytes_usage.go#L294)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: the comment needs an adjustment.
</blockquote></details>

Done.
___
*[`pkg/util/uuid/uuid_wrapper.go` line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/136636#-ODNJubi3QBhnMGPBoQL:-ODRb5smAPWw-jMvi11W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3db6352180157b69f839e219d147ea20e4c0a8ae/pkg/util/uuid/uuid_wrapper.go#L27)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `s/hexidemical/hexadecimal/`.
</blockquote></details>

Done.

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
