### PR TITLE
opt/memo: extend OutputCols with VirtualCols in statistics builder

### PR DESCRIPTION
**Pull request by michae2**
**opt: add props.Statistics.VirtualCols**

As of #118241 we now collect table statistics on virtual computed
columns, but do not yet use them in statistics builder. The difficulty
with using these stats in statistics builder is that virtual computed
columns are synthesized by various non-Scan expressions (Project,
Select, etc). When calculating stats for these non-Scan expressions, we
need to find the virtual column stats even though the virtual columns
are not produced by the input to these expressions.

To solve this, we add a VirtualCols set to props.Statistics which holds
all of the virtual columns that could be produced by the input to a
group. Expressions that could synthesize virtual columns will look in
this set to discover whether there are statistics for any of the scalar
expressions they render. If there are, they will call colStatXXX using
the virtual column ID as if the virtual column had originated from
their input.

This commit adds VirtualCols but does not yet use it.

Note that we cannot currently pass VirtualCols up through set operations
or with-scans, due to the column ID translation they use.

Informs: #68254

Epic: CRDB-8949

Release note: None

---

**sql: add optimizer_use_virtual_computed_column_stats session variable**

Informs: #68254

Epic: CRDB-8949

Release note (sql): Add new session variable
`optimizer_use_virtual_computed_column_stats`. When this variable is
enabled, the optimizer will make use of table statistics on virtual
computed columns.

---

**opt/memo: extend OutputCols with VirtualCols in statistics builder**

Throughout statistics builder we use OutputCols to determine which
columns come from the input to an expression. We then typically call
colStatXXX with those columns as part of statistics calculation.

In order to use statistics on virtual computed columns, we need to call
colStatXXX on any virtual columns that could come from our input, even
if they are not passed upward through OutputCols. To do this we extend
OutputCols with the VirtualCols set we built in a previous commit. This
commit replaces almost all usages of OutputCols in statistics builder
with a call to helper function colStatCols, which returns a union of
OutputCols and VirtualCols.

This is enough to get the optimizer to use statistics on virtual
computed columns in some simple plans. More complex plans will require
matching the virtual column scalar expressions, which will be in the
next PR. I've left some TODOs marking spots where this next PR will
touch.

Informs: #68254

Epic: CRDB-8949

Release note: None

### CODE REVIEW

**Review by DrewKimball — COMMENTED** [review]
> Reviewed 13 of 13 files at r1, 11 of 11 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120668)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @rytaft)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 1766 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120668#-NtKw2TS8EkO8PhYX2iK:-NtKw2TS8EkO8PhYX2iL:bm3hxju) ([raw file](https://github.com/cockroachdb/cockroach/blob/715187db1e1dafd0feb38a6c8a63b4d4bc6d64e1/pkg/sql/opt/memo/statistics_builder.go#L1766)):*
> ```Go
> 
> 	s.RowCount = inputStats.RowCount
> 	s.VirtualCols.UnionWith(inputStats.VirtualCols)
> ```

Does it make sense to include columns from the input, since the index join can't pass them through? (Does that even matter?)
___
*[`pkg/sql/opt/memo/statistics_builder.go` line 2682 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120668#-NtKxUzYCH54cann9oX1:-NtKxUzYCH54cann9oX2:bqsgl5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/715187db1e1dafd0feb38a6c8a63b4d4bc6d64e1/pkg/sql/opt/memo/statistics_builder.go#L2682)):*
> ```Go
> 	s.Available = bindingProps.Statistics().Available
> 	s.RowCount = bindingProps.Statistics().RowCount
> 	s.VirtualCols.UnionWith(bindingProps.Statistics().VirtualCols)
> ```

I think these columns will be keyed to the bound expression, rather than the `WithScan` output columns.
___
*[`pkg/sql/opt/memo/statistics_builder.go` line 256 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/120668#-NtKzFeEC3VmUcBK47W3:-NtKzFeEC3VmUcBK47W4:b-7cjtbz) ([raw file](https://github.com/cockroachdb/cockroach/blob/05dabeda308ecc8b0795b67cb0f6b656271b33b6/pkg/sql/opt/memo/statistics_builder.go#L256)):*
> ```Go
> // computed columns we have statistics on that are in scope.
> func (sb *statisticsBuilder) colStatCols(props *props.Relational) opt.ColSet {
> 	if sb.evalCtx.SessionData().OptimizerUseVirtualComputedColumnStats {
> ```

[nit] Since we've seen some stats code show up in profiles recently, could we do something like this?
```
if sb.evalCtx.SessionData().OptimizerUseVirtualComputedColumnStats && !props.Statistics().VirtualCols.Empty() {
```

**Review by mgartner — APPROVED** [review]
:lgtm: Cool!

> Reviewed 13 of 13 files at r1, 11 of 11 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120668#-:-NtX-Wlp8MvVHEUp4wmO:b-8mhwdz)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, and @rytaft)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 671 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120668#-NtWvrVr7pE0NXhlGnQM:-NtWvrVr7pE0NXhlGnQN:bhvnteh) ([raw file](https://github.com/cockroachdb/cockroach/blob/715187db1e1dafd0feb38a6c8a63b4d4bc6d64e1/pkg/sql/opt/memo/statistics_builder.go#L671)):*
> ```Go
> 					// in higher groups we can decide whether to look up statistics on
> 					// virtual columns or on the columns used in their defining
> 					// expressions.
> ```

nit: This comment seems out-of-date.
___
*[`pkg/sql/opt/memo/statistics_builder.go` line 1766 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120668#-NtKw2TS8EkO8PhYX2iK:-NtWwKiJAoymQnx-_-jZ:b-xndd9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/715187db1e1dafd0feb38a6c8a63b4d4bc6d64e1/pkg/sql/opt/memo/statistics_builder.go#L1766)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Does it make sense to include columns from the input, since the index join can't pass them through? (Does that even matter?)
</blockquote></details>

What do you mean by an "index join can't pass [input columns] through"? What about something like:

```
  select
   ├── columns: a:1 b:2 c:3
   ├── stats: [rows=0.9108108, distinct(2)=0.910811, null(2)=0, distinct(3)=0.910811, null(3)=0, distinct(2,3)=0.910811, null(2,3)=0]
   ├── key: (1)
   ├── fd: ()-->(2,3)
   ├── prune: (1)
   ├── index-join t
   │    ├── columns: a:1 b:2 c:3
   │    ├── stats: [rows=10]
   │    ├── key: (1)
   │    ├── fd: ()-->(2), (1)-->(3)
   │    └── scan t@t_b_idx
   │         ├── columns: a:1 b:2
   │         ├── constraint: /2/1: [/1 - /1]
   │         ├── stats: [rows=10, distinct(2)=1, null(2)=0]
   │         ├── key: (1)
   │         ├── fd: ()-->(2)
   └── filters
        └── c:3 = 2 [outer=(3), constraints=(/3: [/2 - /2]; tight), fd=()-->(3)]
```

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120668)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @rytaft)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 1766 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120668#-NtKw2TS8EkO8PhYX2iK:-NtX92n8AFf5Ap4W6fbc:b-i4ng9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/715187db1e1dafd0feb38a6c8a63b4d4bc6d64e1/pkg/sql/opt/memo/statistics_builder.go#L1766)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

What do you mean by an "index join can't pass [input columns] through"? What about something like:

```
  select
   ├── columns: a:1 b:2 c:3
   ├── stats: [rows=0.9108108, distinct(2)=0.910811, null(2)=0, distinct(3)=0.910811, null(3)=0, distinct(2,3)=0.910811, null(2,3)=0]
   ├── key: (1)
   ├── fd: ()-->(2,3)
   ├── prune: (1)
   ├── index-join t
   │    ├── columns: a:1 b:2 c:3
   │    ├── stats: [rows=10]
   │    ├── key: (1)
   │    ├── fd: ()-->(2), (1)-->(3)
   │    └── scan t@t_b_idx
   │         ├── columns: a:1 b:2
   │         ├── constraint: /2/1: [/1 - /1]
   │         ├── stats: [rows=10, distinct(2)=1, null(2)=0]
   │         ├── key: (1)
   │         ├── fd: ()-->(2)
   └── filters
        └── c:3 = 2 [outer=(3), constraints=(/3: [/2 - /2]; tight), fd=()-->(3)]
```
</blockquote></details>

Good point. I confused the optimizer representation with what happens during execution. I think this is probably fine, then.

**Review by michae2 — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120668#-:-NtYLh9v2GHJ2AtqEbsx:bz5mair)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @mgartner, and @rytaft)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 671 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120668#-NtWvrVr7pE0NXhlGnQM:-NtYKcwa2lymlY-286f5:b-cs1wjg) ([raw file](https://github.com/cockroachdb/cockroach/blob/715187db1e1dafd0feb38a6c8a63b4d4bc6d64e1/pkg/sql/opt/memo/statistics_builder.go#L671)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: This comment seems out-of-date.
</blockquote></details>

This is from the first commit, and it's still true: we only add virtual columns when we have stats for them. I wanted to document it because it's a little subtle, not sure if this is the best spot.
___
*[`pkg/sql/opt/memo/statistics_builder.go` line 1766 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120668#-NtKw2TS8EkO8PhYX2iK:-NtYKrVB0Nl5lfUZCnz-:bbozmzq) ([raw file](https://github.com/cockroachdb/cockroach/blob/715187db1e1dafd0feb38a6c8a63b4d4bc6d64e1/pkg/sql/opt/memo/statistics_builder.go#L1766)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Good point. I confused the optimizer representation with what happens during execution. I think this is probably fine, then.
</blockquote></details>

Yes, we do want to do this for index join. I added an index join testcase, and you can see the `virtcolstats: (2)` going up through the index join.
___
*[`pkg/sql/opt/memo/statistics_builder.go` line 2682 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120668#-NtKxUzYCH54cann9oX1:-NtYL73b6gULaUQa5Qzo:b-v8sqz7) ([raw file](https://github.com/cockroachdb/cockroach/blob/715187db1e1dafd0feb38a6c8a63b4d4bc6d64e1/pkg/sql/opt/memo/statistics_builder.go#L2682)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I think these columns will be keyed to the bound expression, rather than the `WithScan` output columns.
</blockquote></details>

Oh! Great catch! This actually caused a panic when combined with my next PR.

I removed this (so now both set operations and with-scans are barriers for VirtualCols).

I also added a testcase for this that shows we don't panic (but the stats are inaccurate).
___
*[`pkg/sql/opt/memo/statistics_builder.go` line 256 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/120668#-NtKzFeEC3VmUcBK47W3:-NtYK_RN2_f6KVARBY70:b2v9nzy) ([raw file](https://github.com/cockroachdb/cockroach/blob/05dabeda308ecc8b0795b67cb0f6b656271b33b6/pkg/sql/opt/memo/statistics_builder.go#L256)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Since we've seen some stats code show up in profiles recently, could we do something like this?
```
if sb.evalCtx.SessionData().OptimizerUseVirtualComputedColumnStats && !props.Statistics().VirtualCols.Empty() {
```
</blockquote></details>

Oh, good call! Done.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Great work!

> Reviewed 11 of 11 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120668#-:-NtZKV5A-OKbhCkNhxQ5:bolbkdq)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

**Comment by michae2** [comment]
Thanks Drew!

bors r=DrewKimball,mgartner

**Comment by mgartner** [comment]
*[`pkg/sql/opt/memo/statistics_builder.go` line 671 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120668#-NtWvrVr7pE0NXhlGnQM:-NtbbhVR8F-jmQfZoAH7:b4v70wu) ([raw file](https://github.com/cockroachdb/cockroach/blob/715187db1e1dafd0feb38a6c8a63b4d4bc6d64e1/pkg/sql/opt/memo/statistics_builder.go#L671)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

This is from the first commit, and it's still true: we only add virtual columns when we have stats for them. I wanted to document it because it's a little subtle, not sure if this is the best spot.
</blockquote></details>

Oh sorry, I misunderstood the code here.

**Pull request merged**
