### PR TITLE
kvclient: don't retry against down leaseholders

### PR DESCRIPTION
**Pull request by andrewbaptist**
Only the last commit on this PR is unique and needs to be reviewed as part of this PR.

If the leaseholder returns a ReplicaUnavailableError or a gRPC error, we should assume that retries are futile and move on to a different replica.

Epic: none

Release note: None

### CODE REVIEW

**Comment by andrewbaptist** [comment]
Only the last commit in this PR is unique in this PR and needs to be reviewed. Specifically this change simplifies the handling of the RUE to set the `leaseholderUnavailable` to true when we hit an RUE against the leaseholder and remove the "late" computation of it. We also set this to true if we are unable to dial the leaseholder.

**Comment by andrewbaptist** [comment]
Only the last commit on this PR is unique and needs to be reviewed here. This is a little subtle since we are adding a new "global" variable to this already complex method. The primary goal is to have the same replica unavailable behavior if either the circuit breaker is tripped OR the network connection to the leaseholder if broken. Specifically we don't want to retry the leaseholder multiple times with backoff if we don't have a connection to it, but the other replicas are returning a NLHE.

**Review by erikgrinaker — COMMENTED** [review]
The direction here seems reasonable. However, don't we have to reset `leaseholderUnavailable = false` when we find a new leaseholder, such that we don't incorrectly omit backoffs when the old leaseholder was unreachable, but the new one isn't?

**Review by erikgrinaker — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119791)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @arulajmani)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 2571 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/119791#-NsrNSz49KKr3q1wD9up:-NsrNSz49KKr3q1wD9uq:b-v33fpn) ([raw file](https://github.com/cockroachdb/cockroach/blob/034dbab82ad40d27c034aedd728053d5ba4d1fc7/pkg/kv/kvclient/kvcoord/dist_sender.go#L2571)):*
> ```Go
> 				// fails otherwise. That test is expecting us to retry against
> 				// the leaseholder after we received a gRPC error to validate
> 				// that it now returns a WriteTooOld error. Once the proxy code
> ```

Why does the test fail with this change? Didn't you say that `sendPartialBatch` would keep retrying in this case? Why does it matter whether `sendToReplicas` does the retries or `sendPartialBatch`? Does that imply that we're losing necessary information by bumping the retries up the stack?

**Review by andrewbaptist — COMMENTED** [review]
Good catch - I added this reset.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119791#-:-NsrlMSjDONzhX_2UXXg:b-m8kfbg)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @erikgrinaker)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 2571 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/119791#-NsrNSz49KKr3q1wD9up:-NsrlPF995JYt3drV7Au:b-t4cmmb) ([raw file](https://github.com/cockroachdb/cockroach/blob/034dbab82ad40d27c034aedd728053d5ba4d1fc7/pkg/kv/kvclient/kvcoord/dist_sender.go#L2571)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Why does the test fail with this change? Didn't you say that `sendPartialBatch` would keep retrying in this case? Why does it matter whether `sendToReplicas` does the retries or `sendPartialBatch`? Does that imply that we're losing necessary information by bumping the retries up the stack?
</blockquote></details>

The retry in `sendPartialBatch` only occurs if `sendToReplicas` returns a `sendError`. Most send errors result in a `sendError` but specifically excluded are the `ambigiousErr` and `replicaUnavailableErr`. In those cases we stop retrying in the outer `sendPartialBatch` loop after we have tried all replicas once.

The flow in this test before was the following (store 1 is the leaseholder):
1) Send to store 1 - get a gRPC error - treat as an `ambiguousError` and set the `AmbiguousReplayProtection` on the request
2) Send to store 2 - get a NLHE pointing back to store 1
3) Send to store 1 again - succeed in processing, but return a `WriteTooOld` ambiguous error - return this out to the client.

After the change (without this additional branch) the flow is
1) Send to store 1 - get an gRPC error - treat as an `ambiguousError`, add replay protection, also mark `leaseholderUnavailable`
2) Send to store 2 - get a NLHE pointing back to store 1 - since `leaseholderUnavailable` is set, return the error from store 1 in `sendToRepilca`

With the proxy code changes the flow is now:
1) Send to store 1 - get an gRPC error - treat as an `ambiguousError`, add replay protection, also mark `leaseholderUnavailable`
2) Send to store 2 requesting a proxy to store 1 
   - get a NLHE on evaluation pointing back to store 1 
   - proxy the request to store 1
   - store 1 returns a `WriteTooOld ambiguousError` to store 2
   - return the `WriteTooOld ambiguousError` to the client

So the test again passes without this special casing, although it is now following a different flow.

This case is pretty unusual (returning a gRPC error on the first attempt, but immediately evaluating and returning a different result), so the test was a little flawed, but I didn't see an easy way to make this test pass otherwise without a lot of work. Since I was able to remove the condition after the proxy code, it actually was much more realistic, and if fact proxying makes it more likely would have hit this problem had it not already been fixed.

**Review by erikgrinaker — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119791)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @arulajmani)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 2571 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/119791#-NsrNSz49KKr3q1wD9up:-Nss0P54CFH3e5nQ54oJ:bjq7qyz) ([raw file](https://github.com/cockroachdb/cockroach/blob/034dbab82ad40d27c034aedd728053d5ba4d1fc7/pkg/kv/kvclient/kvcoord/dist_sender.go#L2571)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

The retry in `sendPartialBatch` only occurs if `sendToReplicas` returns a `sendError`. Most send errors result in a `sendError` but specifically excluded are the `ambigiousErr` and `replicaUnavailableErr`. In those cases we stop retrying in the outer `sendPartialBatch` loop after we have tried all replicas once.

The flow in this test before was the following (store 1 is the leaseholder):
1) Send to store 1 - get a gRPC error - treat as an `ambiguousError` and set the `AmbiguousReplayProtection` on the request
2) Send to store 2 - get a NLHE pointing back to store 1
3) Send to store 1 again - succeed in processing, but return a `WriteTooOld` ambiguous error - return this out to the client.

After the change (without this additional branch) the flow is
1) Send to store 1 - get an gRPC error - treat as an `ambiguousError`, add replay protection, also mark `leaseholderUnavailable`
2) Send to store 2 - get a NLHE pointing back to store 1 - since `leaseholderUnavailable` is set, return the error from store 1 in `sendToRepilca

With the proxy code changes the flow is now:
1) Send to store 1 - get an gRPC error - treat as an `ambiguousError`, add replay protection, also mark `leaseholderUnavailable`
2) Send to store 2 requesting a proxy to store 1 
   - get a NLHE on evaluation pointing back to store 1 
   - proxy the request to store 1
   - store 1 returns a `WriteTooOld ambiguousError` to store 2
   - return the `WriteTooOld ambiguousError` to the client

So the test again passes without this special casing, although it is now following a different flow.

This case is pretty unusual (returning a gRPC error on the first attempt, but immediately evaluating and returning a different result), so the test was a little flawed, but I didn't see an easy way to make this test pass otherwise without a lot of work. Since I was able to remove the condition after the proxy code, it actually was much more realistic, and if fact proxying makes it more likely would have hit this problem had it not already been fixed.
</blockquote></details>

I see. The fact that follower routing "fixes" the test is incidental, and I imagine we'll see a fair bit of similar test fallout where failures now succeed by proxying. But I suppose it's still testing the thing we care about.

I'm not familiar with the ambiguous replay protection thing, someone who is should probably give this a second look to make sure this still makes sense -- but I think it does.

**Comment by andrewbaptist** [comment]
bors r=erikgrinaker

TFTR. The underlying handling of ambiguous commits is still preserved by this and its good that this case is still handled. We should look at this longer term to try and figure out if there are alternatives to the current handling, but for now its OK.

**Pull request merged**
