### PR TITLE
importccl: fix bug when mixing old and new tables during import

### LINKED ISSUE #50733: bulkio/import: bug when mixing existing and new tables?
I was casually skimming over the code trying to understand #50731 and stumbled upon this block of code:

https://github.com/cockroachdb/cockroach/blob/8f768ad14cfb3f514db6d40465b2dd60ee1f2890/pkg/ccl/importccl/import_stmt.go#L1011-L1023

I couldn't make sense of it, and I now think it's a bug. Specifically, I think the indexing is wrong here, as it doesn't handle the case where `len(newTableDescs) < len(importDetails.Tables)` correctly. Looking up, we see an unused map `newTableDescToIdx`, which is exactly what we want here. So I think we're just forgetting to use this map. I think we want something like `i := newTableDescToIdx[i]` in the loop over `res`.

I don't know if this is actually possible to hit as a user, as I believe IMPORT only allows new tables and IMPORT INTO only allows existing tables.

### PR DESCRIPTION
**Pull request by adityamaru**
There was an indexing bug which would have been triggered if the
resolution of new and old table descriptors was ever mixed within the
same import. This situation has not hit any users because an IMPORT only
allows writing to new tables, while an IMPORT INTO only allows writing
to existing (old) tables, thereby never mixing the two.

This change fixes that bug.

Closes #50733

Release note: None

### CODE REVIEW

**Review by miretskiy — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50851)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @nvanbenschoten, and @pbardea)

___
*[pkg/ccl/importccl/import_stmt.go, line 1018 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50851#-MB9ccBZ2iXzEgwYvN43:-MB9ccBZ2iXzEgwYvN44:b-alwh5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a82124d167f6b2e442250cf15c15f34bb75de44/pkg/ccl/importccl/import_stmt.go#L1018)):*
> ```Go
> 			}
> 			for _, table := range res {
> 				i := newTableDescToIdx[table]
> ```

do we want to add a test for this?  (just asking)

**Review by pbardea — APPROVED** [review]
LGTM - I'm not sure if we need a release note if we are sure that users won't run into this bug though (as it may confuse them that we fixed a bug that they cannot see). But if it is possible for the users to see this bug, then I think a test would be useful.

**Review by adityamaru — COMMENTED** [review]
Ack. As I mentioned in the response to Yevgeniy below, I don't think this is a case we can get into. I have removed the release note.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50851#-:-MB9gjjpE82JWJwqPe1B:b-vrjde)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @nvanbenschoten)

___
*[pkg/ccl/importccl/import_stmt.go, line 1018 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50851#-MB9ccBZ2iXzEgwYvN43:-MB9gCvh-H1toK9msKk8:b-feaj9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a82124d167f6b2e442250cf15c15f34bb75de44/pkg/ccl/importccl/import_stmt.go#L1018)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

do we want to add a test for this?  (just asking)
</blockquote></details>

I don't think this is possible to test because we have an if..else branch which either populates the ImportJob.Tables with a n existing table descriptor (in the case of IMPORT INTO), or appends a series of new table descriptors (in the case of IMPORT). Either way, we cannot run into a situation where ImportJob.Tables has a mix of new and already existing descriptors that need to be resolved.

**Review by nvb — COMMENTED** [review]
Thanks for the fix!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50851#-:-MBA833_5L2ZnTKELsra:b-p1kr18)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @miretskiy)

___
*[pkg/ccl/importccl/import_stmt.go, line 981 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50851#-MBA7UwWDvX8qexutQNq:-MBA7UwWDvX8qexutQNr:bl8c7k9) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff70be7fe0d07f9a32ad90f9d0ea8b248433e68/pkg/ccl/importccl/import_stmt.go#L981)):*
> ```Go
> 		importDetails.Tables = make([]jobspb.ImportDetails_Table, len(details.Tables))
> 
> 		newTableDescToIdx := make(map[*sqlbase.TableDescriptor]int, len(importDetails.Tables))
> ```

The use of a pointer key seems fragile here. It only works because `prepareNewTableDescsForIngestion` returns pointers into the `newTableDescs` slice that was passed in. If the function was to start constructing new descriptors (which it's name implies that it easily could), it would break.

Is there a reason we can't key the map on `TableDescriptor.ID`?
___
*[pkg/ccl/importccl/import_stmt.go, line 1019 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50851#-MBA79rhC1i8nIxG8jUZ:-MBA79ri6v-XgXq1YiPt:bpp9ys2) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff70be7fe0d07f9a32ad90f9d0ea8b248433e68/pkg/ccl/importccl/import_stmt.go#L1019)):*
> ```Go
> 			for _, table := range res {
> 				i := newTableDescToIdx[table]
> 				importDetails.Tables[i] = jobspb.ImportDetails_Table{Desc: table,
> ```

This would be easier to read if it more closely aligned with the code above. To get there, I think we'd want to make the following two changes:
1. rename `table` to `desc`
2. pull out a `table := details.Tables[i]` variable above this line

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50851)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @nvanbenschoten)

___
*[pkg/ccl/importccl/import_stmt.go, line 981 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50851#-MBA7UwWDvX8qexutQNq:-MBCHvjk2X0Q-1Q_cqRt:b-5jckij) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff70be7fe0d07f9a32ad90f9d0ea8b248433e68/pkg/ccl/importccl/import_stmt.go#L981)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The use of a pointer key seems fragile here. It only works because `prepareNewTableDescsForIngestion` returns pointers into the `newTableDescs` slice that was passed in. If the function was to start constructing new descriptors (which it's name implies that it easily could), it would break.

Is there a reason we can't key the map on `TableDescriptor.ID`?
</blockquote></details>

I don't think we can key on the ID because in `prepareNewTableDescsForIngestion` we generate and assign new IDs to each of the descriptors via `RewriteTableDescs`. I believe we could key on `desc.Name` because that remains unchanged. before and after preparation. 
Alternatively, I could rename the method because I believe it was written to imply that we are preparing descriptors for "new tables" (as compared to existing ones), rather than preparing new descriptors. Maybe `prepareDescsForNewTables` or `prepareDescsForIngestingIntoNewTables`?
___
*[pkg/ccl/importccl/import_stmt.go, line 1019 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50851#-MBA79rhC1i8nIxG8jUZ:-MBCHuh5Cg4ao-LjJtGv:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff70be7fe0d07f9a32ad90f9d0ea8b248433e68/pkg/ccl/importccl/import_stmt.go#L1019)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This would be easier to read if it more closely aligned with the code above. To get there, I think we'd want to make the following two changes:
1. rename `table` to `desc`
2. pull out a `table := details.Tables[i]` variable above this line
</blockquote></details>

done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50851#-:-MBdzdZfD3gfNDzRUohI:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru and @miretskiy)

___
*[pkg/ccl/importccl/import_stmt.go, line 981 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50851#-MBA7UwWDvX8qexutQNq:-MBdxeQk3bVO3pKs6s1k:b-uyay9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff70be7fe0d07f9a32ad90f9d0ea8b248433e68/pkg/ccl/importccl/import_stmt.go#L981)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

I don't think we can key on the ID because in `prepareNewTableDescsForIngestion` we generate and assign new IDs to each of the descriptors via `RewriteTableDescs`. I believe we could key on `desc.Name` because that remains unchanged. before and after preparation. 
Alternatively, I could rename the method because I believe it was written to imply that we are preparing descriptors for "new tables" (as compared to existing ones), rather than preparing new descriptors. Maybe `prepareDescsForNewTables` or `prepareDescsForIngestingIntoNewTables`?
</blockquote></details>

I don't know the code well enough to make a meaningful suggestion here, other than to say that the function should make it clear how the input it accepts maps to the output it produces. If it did then I think our answer to this problem would fall right out. For instance, if the contract was "the returned slice is in the same order as the input tables slice" then it would be easier to make sense of this by indexing into each slice.

I'll defer to you on all of this though. Feel free to merge the fix without this refactor.

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50851)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @miretskiy and @nvanbenschoten)

___
*[pkg/ccl/importccl/import_stmt.go, line 981 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50851#-MBA7UwWDvX8qexutQNq:-MBipuFs7_qsBD4bd-W5:bpt6xk) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff70be7fe0d07f9a32ad90f9d0ea8b248433e68/pkg/ccl/importccl/import_stmt.go#L981)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I don't know the code well enough to make a meaningful suggestion here, other than to say that the function should make it clear how the input it accepts maps to the output it produces. If it did then I think our answer to this problem would fall right out. For instance, if the contract was "the returned slice is in the same order as the input tables slice" then it would be easier to make sense of this by indexing into each slice.

I'll defer to you on all of this though. Feel free to merge the fix without this refactor.
</blockquote></details>

Ack, I incorporated the suggestion of indexing both slices during initialization to make the relationship clearer. @miretskiy could I get a quick sign off on the change, please?

**Review by miretskiy — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50851)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @miretskiy and @nvanbenschoten)

**Comment by adityamaru** [comment]
TFTRs!

bors r+

**Pull request merged**
