### PR TITLE
sqlsmith: add some basic schema change statements

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36130#-:-LauH0I6Ef35Wsa0TC5g:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj and @mjibson)

___
*[pkg/internal/sqlsmith/alter.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36130#-LauEGJ24yWGVXqIlTtg:-LauEGJ32pAqtt2TZ701:bxs370d) ([raw file](https://github.com/cockroachdb/cockroach/blob/754a37a7e3bfc8ce30f31cd95226c429abd5304a/pkg/internal/sqlsmith/alter.go#L55)):*
> ```Go
> 		// sync the change from the last alter before trying the
> 		// next one. This is instead of running ReloadSchemas right
> 		// after thet alter succeeds (which doesn't always pick
> ```

nit: thet
___
*[pkg/internal/sqlsmith/alter.go, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36130#-LauEmP-2-JoUKx96OtP:-LauEmP-2-JoUKx96OtQ:b-dg0hng) ([raw file](https://github.com/cockroachdb/cockroach/blob/754a37a7e3bfc8ce30f31cd95226c429abd5304a/pkg/internal/sqlsmith/alter.go#L156)):*
> ```Go
> 		col.Computed.Computed = true
> 		col.Computed.Expr = &tree.ParenExpr{Expr: makeScalar(s, t, colRefs)}
> 	}
> ```

`CHECK` constraints shouldn't be to tricky to add, I think, and should give some benefit. As an added bonus we could run periodic checks that they're not violated.
___
*[pkg/internal/sqlsmith/relational.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36130#-LauHRr6BpzN8WF63PDR:-LauHRr6BpzN8WF63PDS:b-2pf9yb) ([raw file](https://github.com/cockroachdb/cockroach/blob/754a37a7e3bfc8ce30f31cd95226c429abd5304a/pkg/internal/sqlsmith/relational.go#L89)):*
> ```Go
> 		{1, makeDelete},
> 		{1, makeUpdate},
> 		{1, makeAlter},
> ```

my gut says the weight for this should be lower than the others, but not for any strong reason ¯\\\_(ツ)\_/¯
___
*[pkg/internal/sqlsmith/sqlsmith.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36130#-LauFx7G56ukpQXs4MG_:-LauFx7G56ukpQXs4MGa:b-hubgtw) ([raw file](https://github.com/cockroachdb/cockroach/blob/754a37a7e3bfc8ce30f31cd95226c429abd5304a/pkg/internal/sqlsmith/sqlsmith.go#L62)):*
> ```Go
> 	rnd                     *rand.Rand
> 	db                      *gosql.DB
> 	lock                    syncutil.Mutex
> ```

probably not that important but this could be an `RWMutex` since a lot of accessors only read from it.

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36130)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj)

___
*[pkg/internal/sqlsmith/alter.go, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36130#-LauEmP-2-JoUKx96OtP:-Lav5k2k8WG8AL0VPnWO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/754a37a7e3bfc8ce30f31cd95226c429abd5304a/pkg/internal/sqlsmith/alter.go#L156)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

`CHECK` constraints shouldn't be to tricky to add, I think, and should give some benefit. As an added bonus we could run periodic checks that they're not violated.
</blockquote></details>

Done.
___
*[pkg/internal/sqlsmith/relational.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36130#-LauHRr6BpzN8WF63PDR:-Lav5kgPDvaTXTbcNHWu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/754a37a7e3bfc8ce30f31cd95226c429abd5304a/pkg/internal/sqlsmith/relational.go#L89)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

my gut says the weight for this should be lower than the others, but not for any strong reason ¯\\\_(ツ)\_/¯
</blockquote></details>

Done.
___
*[pkg/internal/sqlsmith/sqlsmith.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36130#-LauFx7G56ukpQXs4MG_:-Lav6zHQC_ivrvWj3ahJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/754a37a7e3bfc8ce30f31cd95226c429abd5304a/pkg/internal/sqlsmith/sqlsmith.go#L62)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

probably not that important but this could be an `RWMutex` since a lot of accessors only read from it.
</blockquote></details>

Done.

**Pull request merged**
