### PR TITLE
deps: update bufbuild/buf

### LINKED ISSUE #67216: build: cockroachdb build is broken on `master`
cc @bufdev  @dt 

I can't build CockroachDB any more since #66913 went in.

```
github.com/bufbuild/buf/internal/pkg/interrupt
# github.com/bufbuild/buf/internal/pkg/interrupt
vendor/github.com/bufbuild/buf/internal/pkg/interrupt/interrupt.go:40:25: undefined: signals
```

I'm going to send a PR upstream (the `+build` directive in there is bogus) but if it doesn't get merged quick, I'll revert #66913.

### PR DESCRIPTION
**Pull request by knz**
First commit from #74510.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
Note: this PR is currently failing on Bazel CI with the following error:

```ERROR: /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/io_bazel_rules_nogo/BUILD.bazel:3:6: in alias rule @io_bazel_rules_nogo//:nogo: cycle in dependency graph:
    //pkg/cmd/generate-test-suites:generate-test-suites
    @io_bazel_rules_go//:go_context_data
.-> @io_bazel_rules_nogo//:nogo
|   @io_bazel_rules_go//:default_nogo
|   @io_bazel_rules_go//go/tools/builders:nogo_srcs
|   @org_golang_x_tools//go/analysis:go_tool_library
|   @org_golang_x_tools//internal/analysisinternal:go_tool_library
|   @org_golang_x_tools//go/ast/astutil:go_tool_library
|   @org_golang_x_tools//internal/typeparams:typeparams
|   @io_bazel_rules_go//:go_context_data
`-- @io_bazel_rules_nogo//:nogo
ERROR: Analysis of target '//pkg/cmd/generate-test-suites:generate-test-suites' failed; build aborted
```

This is because it upgrades x/tools and that tickles this bug in gazelle. https://github.com/bazelbuild/rules_go/issues/2479

Same issue as in #66880 and  #66993

**Comment by knz** [comment]
This is now ready for review.

**Comment by rickystewart** [comment]
Looks like CI is failing and you need to `make vendor-rebuild`?

**Comment by knz** [comment]
This is again ready for review, PTAL

**Review by rickystewart — APPROVED** [review]

**Comment by knz** [comment]
TFYR!

bors r=rickystewart

**Pull request merged**
