### PR TITLE
kv: handle future-time operations for conflict resolution requests

### PR DESCRIPTION
**Pull request by nvb**
Relates to #57688.

This PR updates the following four requests types to properly handle future-time operations:
- `PushTxnRequest`
- `QueryTxnRequest`
- `QueryIntentRequest`
- `RecoverTxnRequest`

It also updates the request evaluation code to properly check that all timestamp cache updates are safe, based on the batch header timestamps of the requests. This is coupled with a stricter, more comprehensive assertion when updating the timestamp cache that all updates are performed below the expiration time of the active lease. This ensures that timestamp cache updates are not lost during non-cooperative lease change.

In doing so, the PR also updates the replica lease check to test against the batch's read or write timestamp, whichever is later. This addresses the concerns raised in https://github.com/cockroachdb/cockroach/pull/58904#pullrequestreview-572482570.

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59693)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/roachpb/batch.go, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59693#-MTIPt-i8ylUt_aJ4qQ4:-MTIPt-j-OgnuSafrI6p:b-th0nd6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fb64bff05ace364b31bc0fd7a321cf9fdf6f679/pkg/roachpb/batch.go#L28)):*
> ```Go
> //go:generate go run -tags gen-batch gen_batch.go
> 
> // WriteTimestamp returns the timestamps at which this request is writing. For
> ```

Did you intent to add this to the Header, given that it's also defined below on the `BatchRequest`?

**Review by andreimatei — APPROVED** [review]
:LGTM:

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59693#-:-MTMMveeEkg0-3k1Bd22:bmxilld)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica.go, line 1233 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59693#-MTM5hXm6_0zguZGg0OH:-MTM5hXm6_0zguZGg0OI:bx7iymq) ([raw file](https://github.com/cockroachdb/cockroach/blob/207d6f1497e5173bfbdffa7df2d9bb083f506845/pkg/kv/kvserver/replica.go#L1233)):*
> ```Go
> 		// If the request is a write or a consistent read, it requires the
> 		// replica serving it to hold the range lease.
> 		st, shouldExtend, err = r.leaseGoodToGoRLocked(ctx, now, ba.WriteTimestamp())
> ```

put a comment nodding to the fact that the max offset is accounted for inside the lease check
___
*[pkg/kv/kvserver/replica_tscache.go, line 57 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59693#-MTMMl0D-yN11GPQjAA5:-MTMMl0D-yN11GPQjAA6:bmi8ppe) ([raw file](https://github.com/cockroachdb/cockroach/blob/59d535833d64e82847911add2fc42573af1ff487/pkg/kv/kvserver/replica_tscache.go#L57)):*
> ```Go
> 	// and is acquired by a new replica that begins serving writes immediately
> 	// to the same keys at the next lease's start time.
> 	if exp := st.Expiration(); exp.LessEq(ts) {
> ```

:100: 
___
*[pkg/kv/kvserver/batcheval/cmd_push_txn.go, line 119 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59693#-MTM9UPwDIsKYIFiHHDE:-MTM9UPwDIsKYIFiHHDF:b-ai7an4) ([raw file](https://github.com/cockroachdb/cockroach/blob/207d6f1497e5173bfbdffa7df2d9bb083f506845/pkg/kv/kvserver/batcheval/cmd_push_txn.go#L119)):*
> ```Go
> 		// push the transaction to. Transactions should not be pushed into the
> 		// future past the leaseholder's lease expiration or their effect may
> 		// not be fully reflected in a future leaseholder's timestamp cache.
> ```

nit: make this comment more clear about the fact that we don't expect the client to send such a request (right?). Or actually make it an `AssertionFailedError`
___
*[pkg/kv/kvserver/batcheval/cmd_push_txn.go, line 123 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59693#-MTMA2pr4ESB4iDXjNwG:-MTMA2pr4ESB4iDXjNwH:b-f7g564) ([raw file](https://github.com/cockroachdb/cockroach/blob/207d6f1497e5173bfbdffa7df2d9bb083f506845/pkg/kv/kvserver/batcheval/cmd_push_txn.go#L123)):*
> ```Go
> 			h.Timestamp, args.PushTo)
> 	}
> 	if h.WriteTimestamp().Less(args.PusheeTxn.MinTimestamp) {
> ```

what's this condition about? This also feels like an assertion, right? Hitting it would mean that someone tried to push a txn
___
*[pkg/kv/kvserver/batcheval/cmd_query_intent.go, line 62 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59693#-MTMGhvs9u5nmPPUE9Jo:-MTMGhvs9u5nmPPUE9Jp:bys6i2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/207d6f1497e5173bfbdffa7df2d9bb083f506845/pkg/kv/kvserver/batcheval/cmd_query_intent.go#L62)):*
> ```Go
> 			ownTxn = true
> 		} else {
> 			return result.Result{}, ErrTransactionUnsupported
> ```

consider making a note of this on `QueryIntentRequest` - that if the request is made inside a txn, it must be the intent's txn.
___
*[pkg/kv/kvserver/batcheval/cmd_query_intent.go, line 66 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59693#-MTMIsn6EMawZ_Yf4DwC:-MTMIsn6EMawZ_Yf4DwD:bqllmla) ([raw file](https://github.com/cockroachdb/cockroach/blob/207d6f1497e5173bfbdffa7df2d9bb083f506845/pkg/kv/kvserver/batcheval/cmd_query_intent.go#L66)):*
> ```Go
> 	}
> 	if h.WriteTimestamp().Less(args.Txn.WriteTimestamp) {
> 		// This condition must hold for the timestamp cache update to be safe.
> ```

pls say a few more words here - hint that the ts cache update in question is the one done in case we fail to find the intent, and it's done @ args.Txn.WriteTimestamp

And this is also an assertion, isn't it?
___
*[pkg/kv/kvserver/batcheval/cmd_query_txn.go, line 54 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59693#-MTMJD5w4oKMSL6ndc64:-MTMJD5w4oKMSL6ndc65:b-a5lzwj) ([raw file](https://github.com/cockroachdb/cockroach/blob/207d6f1497e5173bfbdffa7df2d9bb083f506845/pkg/kv/kvserver/batcheval/cmd_query_txn.go#L54)):*
> ```Go
> 	}
> 	if h.WriteTimestamp().Less(args.Txn.MinTimestamp) {
> 		// This condition must hold for the timestamp cache access to be safe.
> ```

similar to above, consider clarifying this ts cache "access" more

**Review by nvb — COMMENTED** [review]
TFTR!

I'll try to get this merged today to unblock https://github.com/cockroachdb/cockroach/pull/59566.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59693#-:-MTNBBvL5qm00csnTsFG:bzc981f)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei)

___
*[pkg/kv/kvserver/replica.go, line 1233 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59693#-MTM5hXm6_0zguZGg0OH:-MTN1pd68E0ChNild1Jg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/207d6f1497e5173bfbdffa7df2d9bb083f506845/pkg/kv/kvserver/replica.go#L1233)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

put a comment nodding to the fact that the max offset is accounted for inside the lease check
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/batcheval/cmd_push_txn.go, line 119 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59693#-MTM9UPwDIsKYIFiHHDE:-MTN4OXm3Z4ALlbI-a5k:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/207d6f1497e5173bfbdffa7df2d9bb083f506845/pkg/kv/kvserver/batcheval/cmd_push_txn.go#L119)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: make this comment more clear about the fact that we don't expect the client to send such a request (right?). Or actually make it an `AssertionFailedError`
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/batcheval/cmd_push_txn.go, line 123 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59693#-MTMA2pr4ESB4iDXjNwG:-MTN4Q2m83Qk57OE7Nya:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/207d6f1497e5173bfbdffa7df2d9bb083f506845/pkg/kv/kvserver/batcheval/cmd_push_txn.go#L123)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what's this condition about? This also feels like an assertion, right? Hitting it would mean that someone tried to push a txn
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/batcheval/cmd_query_intent.go, line 62 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59693#-MTMGhvs9u5nmPPUE9Jo:-MTN9Ww_1o6r5F6TY7Js:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/207d6f1497e5173bfbdffa7df2d9bb083f506845/pkg/kv/kvserver/batcheval/cmd_query_intent.go#L62)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

consider making a note of this on `QueryIntentRequest` - that if the request is made inside a txn, it must be the intent's txn.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/batcheval/cmd_query_intent.go, line 66 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59693#-MTMIsn6EMawZ_Yf4DwC:-MTN6xwr0oL39vZNR8DJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/207d6f1497e5173bfbdffa7df2d9bb083f506845/pkg/kv/kvserver/batcheval/cmd_query_intent.go#L66)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls say a few more words here - hint that the ts cache update in question is the one done in case we fail to find the intent, and it's done @ args.Txn.WriteTimestamp

And this is also an assertion, isn't it?
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/batcheval/cmd_query_txn.go, line 54 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59693#-MTMJD5w4oKMSL6ndc64:-MTN56eA7RoLxVOFVjoo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/207d6f1497e5173bfbdffa7df2d9bb083f506845/pkg/kv/kvserver/batcheval/cmd_query_txn.go#L54)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

similar to above, consider clarifying this ts cache "access" more
</blockquote></details>

Done.
___
*[pkg/roachpb/batch.go, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59693#-MTIPt-i8ylUt_aJ4qQ4:-MTN6m9GDZUxgEzQ_F6Z:bkzu1hn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fb64bff05ace364b31bc0fd7a321cf9fdf6f679/pkg/roachpb/batch.go#L28)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Did you intent to add this to the Header, given that it's also defined below on the `BatchRequest`?
</blockquote></details>

Yes, because we don't have access to a `BatchRequest` in during request evaluation, just the `BatchRequest.Header`.

**Review by andreimatei — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59693)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/roachpb/batch.go, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59693#-MTIPt-i8ylUt_aJ4qQ4:-MTNE2b_AWJlJZGN1ZSe:bawipot) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fb64bff05ace364b31bc0fd7a321cf9fdf6f679/pkg/roachpb/batch.go#L28)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yes, because we don't have access to a `BatchRequest` in during request evaluation, just the `BatchRequest.Header`.
</blockquote></details>

can you make the other one use this one?

**Review by nvb — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59693#-:-MTNKpSr7UxRl05G5hJC:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei)

___
*[pkg/roachpb/batch.go, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59693#-MTIPt-i8ylUt_aJ4qQ4:-MTNG507-aMUvz5PS2_-:bfo7lxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fb64bff05ace364b31bc0fd7a321cf9fdf6f679/pkg/roachpb/batch.go#L28)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can you make the other one use this one?
</blockquote></details>

Done. I didn't realize I had pulled the other one in during a rebase. `Header` is embedded, so I just deleted the method on `BatchRequest`.

**Comment by nvanbenschoten** [comment]
Unrelated flake in `TestTenantLogic`. https://github.com/cockroachdb/cockroach/pull/60506 also hit this, so it seems unrelated. Trying again.

bors r+

**Pull request merged**
