### PR TITLE
libroach: make CryptoPP build with runtime AES-NI detection.

### LINKED ISSUE #26383: libroach: ensure CryptoPP is built with hardware detection enabled
As seen in #26261 the `release-linux-gnu` build seems to have hardware detection turned off, so CryptoPP doesn't even try to see if the AES instruction set is supported. We should make sure we build it correctly.

### PR DESCRIPTION
**Pull request by mberhault**
Fixes #26383

Set appropriate `-m` flags for cryptopp to enable AES runtime detection
checks (without those, it does not even try).

Add a `UsesAESNI()` function in CryptoPP which returns true iff:
* AES-NI runtime detection is compiled in
* AES-NI instruction is available

Add a warning to stdout (normal logging requires `vmodule=rocksdb=3`) if
encryption is requested but AES-NI is not available.

Add a test to make sure our builds always have AES-NI enabled.

Release note (core): build release binaries with runtime AES detection.

### CODE REVIEW

**Comment by mberhault** [comment]
I probably won't leave that test in. I'm going to check it with bincheck first.

**Comment by bdarnell** [comment]
:lgtm: as long as bincheck passes.

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[c-deps/libroach/ccl/crypto_utils_test.cc, line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26649#-LEpLCHN3QngZDl2lfAl:-LEpLCHN3QngZDl2lfAm:b-eajptb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e86b5b7b64d4f1948a4d1d0aba6785d450f5a9a2/c-deps/libroach/ccl/crypto_utils_test.cc#L12)):*
> ```cpp
> #include "crypto_utils.h"
> 
> TEST(CryptoUtils, HasAESNI) { EXPECT_TRUE(UsesAESNI()); }
> ```

So we expect this test to fail if run on a CPU that doesn't have AESNI? Or is this just checking whether AESNI was compiled in?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26649#-:-LEpLJDK1fOrZT-X6Z2u:b3cggqh)*

**Comment by mberhault** [comment]
I'm also not sure whether TC passes. Ultimately, that one function is more about information when encryption is enabled (show a big warning to the user, maybe even ask for a special flag to allow encryption without AES-NI).

**Comment by mberhault** [comment]
Added a loud warning on stdout (normal logging requires `vmodule=rocksdb=3` which is as good a invisible) when encryption is enabled and we the AES instruction set is not available.

This also passes on bincheck's `test-linux`. It triggers the warning about lack of AES-NI but proceeds correctly. I'll tweak bincheck to 1) add encryption for appropriate versions and probably 2) support running against edge binaries.

**Comment by mberhault** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[c-deps/libroach/ccl/crypto_utils_test.cc, line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26649#-LEpLCHN3QngZDl2lfAl:-LEpcZBL0hHAefTNoDkC:bv0cpb5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e86b5b7b64d4f1948a4d1d0aba6785d450f5a9a2/c-deps/libroach/ccl/crypto_utils_test.cc#L12)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

So we expect this test to fail if run on a CPU that doesn't have AESNI? Or is this just checking whether AESNI was compiled in?
</blockquote></details>

This checks for both. The function I added to cryptopp returns the value of `HasAESNI()` (which performs the runtime cpu check) but inside a  `#if CRYPTOPP_BOOL_AESNI_INTRINSICS_AVAILABLE` which is the big compile-time wrapper for all of these. This is the same thing the encrypt/decrypt steps do.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26649)*

**Comment by mberhault** [comment]
I've tested this on a variety of qemu processor features including with/without sse4.2, aes, pclmul, ssse3. All are happy and the warning only shows up if aes is disabled (pclmul and ssse3 are only used for GCM and are still guarded by runtime checks).

**Comment by mberhault** [comment]
I've run bincheck against a manual test release build (using https://github.com/cockroachdb/bincheck/pull/50). Surprisingly, it even works on windows. I'm almost shocked.

**Comment by benesch** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1, 1 of 1 files at r2.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

---

*[c-deps/libroach/ccl/crypto_utils_test.cc, line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26649#-LEpLCHN3QngZDl2lfAl:-LEz2s9e30ktoa1sFpW6:b7m0d48) ([raw file](https://github.com/cockroachdb/cockroach/blob/e86b5b7b64d4f1948a4d1d0aba6785d450f5a9a2/c-deps/libroach/ccl/crypto_utils_test.cc#L12)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

This checks for both. The function I added to cryptopp returns the value of `HasAESNI()` (which performs the runtime cpu check) but inside a  `#if CRYPTOPP_BOOL_AESNI_INTRINSICS_AVAILABLE` which is the big compile-time wrapper for all of these. This is the same thing the encrypt/decrypt steps do.
</blockquote></details>

Yeah, this seems like a weird thing to put into a test. Doesn't seem like tests should fail if hardware support isn't available. Maybe just test HasAESNI instead? Don't feel strongly though.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26649#-:-LEz39Ed2gNQUtm5euQu:bnfp4nl)*

**Comment by mberhault** [comment]
Review status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

---

*[c-deps/libroach/ccl/crypto_utils_test.cc, line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26649#-LEpLCHN3QngZDl2lfAl:-LEzBZ-l3RcTFvZN4R0f:bxvryd1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e86b5b7b64d4f1948a4d1d0aba6785d450f5a9a2/c-deps/libroach/ccl/crypto_utils_test.cc#L12)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Yeah, this seems like a weird thing to put into a test. Doesn't seem like tests should fail if hardware support isn't available. Maybe just test HasAESNI instead? Don't feel strongly though.
</blockquote></details>

Ok, I've changed it to check `HasAESNI` vs `UsesAESNI` along with a longish comment explaining the success/failure conditions. Basically, this will now only fail if the build disables hardware-accelerated AES and the instruction set is available.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26649)*

**Pull request merged**
