### PR TITLE
sql: add support for extra session vars for pg compatibility

### LINKED ISSUE #35109: Request Postgres compatibility to support Flowable Engine:  Set commands
support for following Commands

```
SET synchronize_seqscans TO off; 
SET lock_timeout = 0; 
SET idle_in_transaction_session_timeout = 0; 
SET row_security = off;
```

```
root@:26257/defaultdb> SET synchronize_seqscans TO off;                                                                                                                              SET statement_timeout = 0;                                                                                                                                                           SET lock_timeout = 0;                                                                                                                                                                SET idle_in_transaction_session_timeout = 0;                                                                                                                                         SET row_security = off;
pq: the configuration setting "synchronize_seqscans" is not supported
HINT: This feature is not yet implemented in CockroachDB.

Please check https://github.com/cockroachdb/cockroach/issues to check
whether this feature is already tracked. If you cannot find it there,
please report this error with reproduction steps at:

    https://github.com/cockroachdb/cockroach/issues/new/choose

If you would rather not post publicly, please contact us directly at:

    support@cockroachlabs.com

The Cockroach Labs team appreciates your feedback.


pq: the configuration setting "lock_timeout" is not supported
HINT: This feature is not yet implemented in CockroachDB.

Please check https://github.com/cockroachdb/cockroach/issues to check
whether this feature is already tracked. If you cannot find it there,
please report this error with reproduction steps at:

    https://github.com/cockroachdb/cockroach/issues/new/choose

If you would rather not post publicly, please contact us directly at:

    support@cockroachlabs.com

The Cockroach Labs team appreciates your feedback.

pq: the configuration setting "idle_in_transaction_session_timeout" is not supported
HINT: This feature is not yet implemented in CockroachDB.

Please check https://github.com/cockroachdb/cockroach/issues to check
whether this feature is already tracked. If you cannot find it there,
please report this error with reproduction steps at:

    https://github.com/cockroachdb/cockroach/issues/new/choose

If you would rather not post publicly, please contact us directly at:

    support@cockroachlabs.com

The Cockroach Labs team appreciates your feedback.

pq: the configuration setting "row_security" is not supported
HINT: This feature is not yet implemented in CockroachDB.

Please check https://github.com/cockroachdb/cockroach/issues to check
whether this feature is already tracked. If you cannot find it there,
please report this error with reproduction steps at:

    https://github.com/cockroachdb/cockroach/issues/new/choose

If you would rather not post publicly, please contact us directly at:

    support@cockroachlabs.com

The Cockroach Labs team appreciates your feedback.


cockroach version
Build Tag:    v2.2.0-alpha.20190211
Build Time:   2019/02/07 23:44:57
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.11.4
C Compiler:   gcc 6.3.0
Build SHA-1:  4bdf0ad7b3190e1836e311d2b05478e8cda0bfe6
Build Type:   release

```

Also track under

https://github.com/cockroachdb/cockroach/issues/20296
https://github.com/cockroachdb/cockroach/issues/5924

https://github.com/flowable/flowable-engine

### PR DESCRIPTION
**Pull request by knz**
Fixes #35109.

This adds compatibility support for the following variables, with only
the default values that make sense in CockroachDB:

- `row_security`
- `synchronize_seqscans`,
- `lock_timeout`,
- `idle_in_transaction_session_timeout`

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
ping

**Review by jordanlewis — APPROVED** [review]
This seems wrong. You seem to be adding session variables 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35116#-:-LZ_O00lE5Wny-KWywMU:bqh4jkg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @jordanlewis, @knz, and @mjibson)

___
*[pkg/sql/logictest/testdata/planner_test/explain, line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35116#-LZ_Nguh7wsEWUo1tPBk:-LZ_Ngui9h5cJIibX9wS:bwxgqx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f84f461b6c9cf6c9aae8a9b552e324baf1aa522/pkg/sql/logictest/testdata/planner_test/explain#L203)):*
> ```
> 
> query TTT
> EXPLAIN SHOW TIME ZONE
> ```

Let's delete these explain tests. They are not testing anything anymore, and produce irritating diffs every time a variable is changed.

**Comment by knz** [comment]
> This seems wrong. You seem to be adding session variables

More words please? What's wrong about it?

**Comment by jordanlewis** [comment]
Oops! I'm very sorry - that was a draft comment that I meant to delete. I thought that these were client config variables that weren't exposed as session variables, but then I tested it and discovered otherwise.

**Comment by knz** [comment]
Oh thanks for clarifying. np

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35116)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @jordanlewis, and @mjibson)

___
*[pkg/sql/logictest/testdata/planner_test/explain, line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35116#-LZ_Nguh7wsEWUo1tPBk:-LZ_ZOLU25_rqYmHt-fJ:b3okj40) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f84f461b6c9cf6c9aae8a9b552e324baf1aa522/pkg/sql/logictest/testdata/planner_test/explain#L203)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Let's delete these explain tests. They are not testing anything anymore, and produce irritating diffs every time a variable is changed.
</blockquote></details>

Done. good idea!

**Comment by knz** [comment]
TFYR

bors r+

**Pull request merged**
