### PR TITLE
changefeedccl: Freeze table name to the (optionally fully qualified) statement time name

### LINKED ISSUE #57290: changefeedccl: fully qualified table name in output
I might have two tables named "users" in different databases. If I create two changefeeds (or one with those two tables) to the same sink, we automatically create topics based on table name. This will create problems.

** Deliverables **
- A `with` option where changefeed output uses fully qualified name (database.schema.table)
- Existing behavior if that option is not included

### PR DESCRIPTION
**Pull request by HonoreDB**
Previously, Kafka topics and top-level keys were always derived from the
table name in changefeeds. If the table name changed, the feed
eventually failed, and if the table name was non-unique across
databases, collisions were unavoidable. This PR adds a WITH
full_table_name option to changefeeds, and honors it by serializing
movr.public.drivers as the statement time name and relying on that.

There are probably more things that need to change downstream.

Release note (sql change): Added "WITH full_table_name" option to create
a changefeed on "movr.public.drivers" instead of
"drivers".

### CODE REVIEW

**Review by miretskiy — CHANGES_REQUESTED** [review]
> Reviewed 11 of 12 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59258)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @HonoreDB)

___
*[pkg/ccl/changefeedccl/avro.go, line 392 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59258#-MSDq9331EAGamVXZ0B6:-MSDq9331EAGamVXZ0B7:b-kh9yiu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5060f29055618593be0dd8c7f59c013eff2adbaa/pkg/ccl/changefeedccl/avro.go#L392)):*
> ```Go
> // record schema. The fields are kept in the same order as columns in the index.
> func indexToAvroSchema(
> 	tableDesc catalog.TableDescriptor, indexDesc *descpb.IndexDescriptor, name string,
> ```

Could you either rename `name` to something more descriptive (e.g. `statementTimeTableName`), or at least
add a comment to that effect.
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 203 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59258#-MSDt9DyC5n5tjIFQDaX:-MSDt9DyC5n5tjIFQDaY:b-rhz8gu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a89a937372467223765da2698af953189fc1131/pkg/ccl/changefeedccl/changefeed_stmt.go#L203)):*
> ```Go
> 			if table, isTable := desc.(catalog.TableDescriptor); isTable {
> 				_, qualified := opts[changefeedbase.OptFullTableName]
> 				name, err := getMaybeQualifiedTableName(ctx, table, *p.ExecCfg(), p.Txn(), qualified)
> ```

nit: would something like `getChangefeedTargetName` be a better name?
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 687 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59258#-MSDtN09-eYRXZtqeut5:-MSDtN09-eYRXZtqeut6:bcnbw34) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a89a937372467223765da2698af953189fc1131/pkg/ccl/changefeedccl/changefeed_stmt.go#L687)):*
> ```
> // or view represented by the provided descriptor. It is a sort of
> // reverse of the Resolve() functions.
> ```

nit: I would drop "it's sort of ..." part
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 717 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59258#-MSDtXa720H3S5xxjboC:-MSDtXa720H3S5xxjboD:ba3nztv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a89a937372467223765da2698af953189fc1131/pkg/ccl/changefeedccl/changefeed_stmt.go#L717)):*
> ```Go
> ) (string, error) {
> 	if qualified {
> 		tbl, err := getQualifiedTableName(ctx, execCfg, txn, desc)
> ```

Perhaps change getQualifiedTableName signature to return "string, error" so that you can make this if block
`return getQualifiedTableName(....)`
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59258#-MSDqVapCZV97wbvv2Hv:-MSDqVapCZV97wbvv2Hw:b-7ca2cx) ([raw file](https://github.com/cockroachdb/cockroach/blob/5060f29055618593be0dd8c7f59c013eff2adbaa/pkg/ccl/changefeedccl/changefeed_test.go#L214)):*
> ```Go
> 	}
> 	//TODO(zinger): No reason in principle this shouldn't be honored here
> 	//t.Run(`sinkless`, sinklessTest(testFn))
> ```

why doesn't this work? 
nit: Also, if possible phrase todos as action items.
___
*[pkg/ccl/changefeedccl/encoder.go, line 277 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59258#-MSDqroK8LMzTcBHZxp9:-MSDqroK8LMzTcBHZxpA:b7f8w5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/5060f29055618593be0dd8c7f59c013eff2adbaa/pkg/ccl/changefeedccl/encoder.go#L277)):*
> ```Go
> type confluentAvroEncoder struct {
> 	registryURL                                       string
> 	updatedField, beforeField, keyOnly, fullTableName bool
> ```

nit: maybe rename to `useFullTableName`?
___
*[pkg/ccl/changefeedccl/encoder.go, line 329 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59258#-MSDs9ST-9TPzdngfzz7:-MSDs9ST-9TPzdngfzz8:bizgowz) ([raw file](https://github.com/cockroachdb/cockroach/blob/5060f29055618593be0dd8c7f59c013eff2adbaa/pkg/ccl/changefeedccl/encoder.go#L329)):*
> ```Go
> 			changefeedbase.OptKeyInValue, changefeedbase.OptFormat, changefeedbase.OptFormatAvro)
> 	}
> 	_, e.fullTableName = opts[changefeedbase.OptFullTableName]
> ```

I'm having hard time finding the uses of this boolean field.  Shouldn't we pass a different name
when calling indexToAvroSchema if this option is true (in the EncodeKey)?
___
*[pkg/ccl/changefeedccl/encoder_test.go, line 444 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59258#-MSDuOHr5yOsdN7xM0nJ:-MSDuOHs4oDwJPcCJPvC:b1yxjho) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a89a937372467223765da2698af953189fc1131/pkg/ccl/changefeedccl/encoder_test.go#L444)):*
> ```Go
> 	}
> 
> 	//t.Run(`sinkless`, sinklessTest(testFn))
> ```

drop comment?
___
*[pkg/ccl/changefeedccl/encoder_test.go, line 445 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59258#-MSDuAGu-BsX0a7J_Y1e:-MSDuAGu-BsX0a7J_Y1f:b-j6rd9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a89a937372467223765da2698af953189fc1131/pkg/ccl/changefeedccl/encoder_test.go#L445)):*
> ```Go
> 
> 	//t.Run(`sinkless`, sinklessTest(testFn))
> 	t.Run(`enterprise`, enterpriseTest(testFn))
> ```

nice test.
___
*[pkg/ccl/changefeedccl/sink.go, line 334 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59258#-MSDuijd7ilbMZTnRb6D:-MSDuijd7ilbMZTnRb6E:b-3g5nj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a89a937372467223765da2698af953189fc1131/pkg/ccl/changefeedccl/sink.go#L334)):*
> ```Go
> }
> 
> func (s *kafkaSink) setTargets(targets jobspb.ChangefeedTargets) {
> ```

nit: perhaps `setTargetNames`?

On the other hand: the sql sink initializes similar things directly inside makeSqlSink.
I wonder if it's better to do the same thing here.  If anything, this may seem like it's
okay to call setTargets multiple times, which probably isn't true.

**Comment by HonoreDB** [comment]
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 717 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59258#-MSDtXa720H3S5xxjboC:-MSEeYus0kVejd0v6IwW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a89a937372467223765da2698af953189fc1131/pkg/ccl/changefeedccl/changefeed_stmt.go#L717)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Perhaps change getQualifiedTableName signature to return "string, error" so that you can make this if block
`return getQualifiedTableName(....)`
</blockquote></details>

Done.

**Comment by HonoreDB** [comment]
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59258#-MSDqVapCZV97wbvv2Hv:-MSEecia6BX3OSOWxKo7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5060f29055618593be0dd8c7f59c013eff2adbaa/pkg/ccl/changefeedccl/changefeed_test.go#L214)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

why doesn't this work? 
nit: Also, if possible phrase todos as action items.
</blockquote></details>

Done.

**Comment by HonoreDB** [comment]
___
*[pkg/ccl/changefeedccl/encoder.go, line 329 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59258#-MSDs9ST-9TPzdngfzz7:-MSEeh024I4VXAxAI0DA:bmxnjae) ([raw file](https://github.com/cockroachdb/cockroach/blob/5060f29055618593be0dd8c7f59c013eff2adbaa/pkg/ccl/changefeedccl/encoder.go#L329)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I'm having hard time finding the uses of this boolean field.  Shouldn't we pass a different name
when calling indexToAvroSchema if this option is true (in the EncodeKey)?
</blockquote></details>

Thanks for this catch, I'd forgotten this part wasn't done (and doesn't get tested because we don't have real Kafka testing). Need to make sure locally that this actually works now.

**Comment by HonoreDB** [comment]
___
*[pkg/ccl/changefeedccl/encoder_test.go, line 444 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59258#-MSDuOHr5yOsdN7xM0nJ:-MSEf3XK5yUDhoOop0Ji:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a89a937372467223765da2698af953189fc1131/pkg/ccl/changefeedccl/encoder_test.go#L444)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

drop comment?
</blockquote></details>

Done.

**Comment by HonoreDB** [comment]
___
*[pkg/ccl/changefeedccl/sink.go, line 334 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59258#-MSDuijd7ilbMZTnRb6D:-MSEfCvjChp7RvR4K5-B:b-d5dc00) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a89a937372467223765da2698af953189fc1131/pkg/ccl/changefeedccl/sink.go#L334)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

nit: perhaps `setTargetNames`?

On the other hand: the sql sink initializes similar things directly inside makeSqlSink.
I wonder if it's better to do the same thing here.  If anything, this may seem like it's
okay to call setTargets multiple times, which probably isn't true.
</blockquote></details>

Yeah, this refactor is awkward and more for testing. This is doing a little more than setting names, the descriptor IDs in the keys are also used.

**Review by HonoreDB — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59258)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @HonoreDB, and @miretskiy)

___
*[pkg/ccl/changefeedccl/avro.go, line 392 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59258#-MSDq9331EAGamVXZ0B6:-MSEeQgcC80dJqykP6pV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5060f29055618593be0dd8c7f59c013eff2adbaa/pkg/ccl/changefeedccl/avro.go#L392)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Could you either rename `name` to something more descriptive (e.g. `statementTimeTableName`), or at least
add a comment to that effect.
</blockquote></details>

Done.

**Review by miretskiy — APPROVED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59258)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @HonoreDB)

**Comment by HonoreDB** [comment]
bors r=[miretskiy]

**Pull request merged**
