### PR TITLE
coldata: fix recent terrible inefficiency in Vec.Append

### LINKED ISSUE #44140: colexec: regression on TPCH Q1 with vectorize on
On recent runs of `tpchvec` roachtest (e.g. https://teamcity.cockroachdb.com/viewLog.html?buildId=1699769&buildTypeId=Cockroach_Nightlies_WorkloadNightly&tab=artifacts#%2Ftpchvec) I noticed this:
```
09:04:38 tpchvec.go:163: [q1] vec OFF was faster by 643.28%: 52.55s ON vs 7.07s OFF --- WARNING
```
This is a pretty bad regression that was introduced recently. I found the root cause be #43720 - the way we make sure that the destination slice has enough capacity for non-bytes types when selection vector is present. This should be fixed.

### PR DESCRIPTION
**Pull request by yuzefovich**
**coldata: move RandomVec into coldata**

Release note: None

**coldata: fix recent terrible inefficiency in Vec.Append**

We recently we merged a change to Vec.Append for non-Bytes types when
selection vector is present to make sure that the destination has enough
capacity to be appended to (preallocating new memory region and copying
over the previous values if necessary). Vec.Append is often called in
a loop when a vector is constantly getting appended to (for example,
when loading batches to create a hash table). With that recent change we
will allocate and copy over memory on *every* call to Append. This is
terrible, but the fix is quite simple - letting Golang itself handle
allocations.

Before:
```
BenchmarkAppend/Int64/AppendSimple/NullProbability=0.0-16                  73368             21306 ns/op         384.50 MB/s
BenchmarkAppend/Int64/AppendWithSel/NullProbability=0.0-16                 10000           4721281 ns/op           1.74 MB/s
BenchmarkAppend/Int64/AppendSimple/NullProbability=0.2-16                 188781             15617 ns/op         524.54 MB/s
BenchmarkAppend/Int64/AppendWithSel/NullProbability=0.2-16                 10000           4761916 ns/op           1.72 MB/s
```

After:
```
BenchmarkAppend/Int64/AppendSimple/NullProbability=0.0-16                  64724             18003 ns/op         455.04 MB/s
BenchmarkAppend/Int64/AppendWithSel/NullProbability=0.0-16                157728             12431 ns/op         659.01 MB/s
BenchmarkAppend/Int64/AppendSimple/NullProbability=0.2-16                 181083             13894 ns/op         589.59 MB/s
BenchmarkAppend/Int64/AppendWithSel/NullProbability=0.2-16                177037              6785 ns/op        1207.33 MB/s
```

A similar problem existed with Decimal type for a long time, and it has
been fixed by allocating at least twice the previous size of the
destination.

Fixes: #44140.

Release note: None

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44141)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/col/coldata/vec_test.go, line 549 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44141#-Lz7Wq8r--5GOTjGuQoq:-Lz7Wq8r--5GOTjGuQor:b-flal8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/18182f617d65a2d39bfbfb6a0ceaa1eb349b907d/pkg/col/coldata/vec_test.go#L549)):*
> ```Go
> 						dest.Copy(bc.args)
> 						if typ == coltypes.Bytes {
> 							dest.Bytes().Reset()
> ```

This will include the time to zero out the bytes so I don't think we should do this in the `b.N` loop. It should be fine to just elide it, right?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44141)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/col/coldata/vec_test.go, line 549 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44141#-Lz7Wq8r--5GOTjGuQoq:-Lz8H19mCOk135gpHWUt:b-1g6m0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/18182f617d65a2d39bfbfb6a0ceaa1eb349b907d/pkg/col/coldata/vec_test.go#L549)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This will include the time to zero out the bytes so I don't think we should do this in the `b.N` loop. It should be fine to just elide it, right?
</blockquote></details>

Yes, it'll include to zero out `offsets`, but we do need to reset flat bytes (it'll panic if `maxSetIndex` is not zero when trying to copy on the second iteration). Refactored to do the "reset" manually.  It is not that big of a difference, so I'm not sure which way is better (using `Reset` directly or inlining most of its code).

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44141#-:-Lz8nDXWCSqHfXLqNpKg:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/col/coldata/vec_test.go, line 549 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44141#-Lz7Wq8r--5GOTjGuQoq:-Lz8n4qD3cw34MqIUEjJ:bq7np8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/18182f617d65a2d39bfbfb6a0ceaa1eb349b907d/pkg/col/coldata/vec_test.go#L549)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Yes, it'll include to zero out `offsets`, but we do need to reset flat bytes (it'll panic if `maxSetIndex` is not zero when trying to copy on the second iteration). Refactored to do the "reset" manually.  It is not that big of a difference, so I'm not sure which way is better (using `Reset` directly or inlining most of its code).
</blockquote></details>

I would just keep it as `Reset` then.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44141#-:-Lz92VNt-yv1n5mP1iMh:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/col/coldata/vec_test.go, line 549 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44141#-Lz7Wq8r--5GOTjGuQoq:-Lz92Rdj6r-z9mKt6U42:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/18182f617d65a2d39bfbfb6a0ceaa1eb349b907d/pkg/col/coldata/vec_test.go#L549)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I would just keep it as `Reset` then.
</blockquote></details>

Done.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44141)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/col/coltypes/types.go, line 243 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44141#-LzF_Sim98oKv7l-z2mY:-LzF_Sim98oKv7l-z2mZ:b-z9hzdu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f1fb122d93772bb2101f4143d77cc2fbd8ce8d0/pkg/col/coltypes/types.go#L243)):*
> ```Go
>   	{{.Tgt}} = {{.Tgt}}[:__desiredCap]
>   } else {
>     __prevCap := cap({{.Tgt}})
> ```

I wonder whether we should backport this performance improvement onto 19.2. It could be killing the performance in some cases. @asubiotto thoughts?

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44141)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @yuzefovich)

___
*[pkg/col/coltypes/types.go, line 243 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44141#-LzF_Sim98oKv7l-z2mY:-LzHmHxtB8RWj4Akc1u2:bddcrhf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f1fb122d93772bb2101f4143d77cc2fbd8ce8d0/pkg/col/coltypes/types.go#L243)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I wonder whether we should backport this performance improvement onto 19.2. It could be killing the performance in some cases. @asubiotto thoughts?
</blockquote></details>

Hmm, I'm not sure we should be backporting every performance improvement unless it's seriously tanking performance. This is limited to single-node clusters, so I would lean towards not backporting it unless we hear about this from users.

**Pull request merged**
