### PR TITLE
cli: port `./cockroach examples-data` to be `workload.Generator`s

### PR DESCRIPTION
**Pull request by danhhz**
Rewrite the command to work with any registered workload.Generator.

We're starting to accumulate workloads that don't need all of the
various methods in Generator, so this also pulls it apart into separate
interfaces for flags, hooks, etc.

It'd be easy to add support for outputting CSVs instead of SQL, but
that's left for a followup.

Release note: None

### CODE REVIEW

**Comment by danhhz** [comment]
@benesch The naming of the interfaces could use some work, but thoughts on doing this in the first place?

**Review by benesch — APPROVED** [review]
LGTM, and the naming doesn't bug me.

I am somewhat confused by your decision to split out multiple interfaces, though. I thought you didn't like that pattern? Hence the `Hooks` method/struct. Seems doubly strange to use both, but I don't feel that strongly.

**Comment by danhhz** [comment]
> I am somewhat confused by your decision to split out multiple interfaces, though. I thought you didn't like that pattern? Hence the Hooks method/struct. Seems doubly strange to use both, but I don't feel that strongly.

Good point. I think we need this interface pattern so simple workloads like these don't need to even worry about flags, hooks, or ops. I'm happy to revisit the way hooks work.

**Comment by danhhz** [comment]
I'm going to merge this to get the refactor in, but let's revisit the hooks stuff offline. TFTR!

**Pull request merged**
