### PR TITLE
opt: Add array and tuple constant folding rules

### PR DESCRIPTION
**Pull request by andy-kimball**
Add FoldIndirection and FoldColumnAccess rules to fold expressions
like this:

  ARRAY[i, i+1][1]
  ARRAY[1, 2, 3][2]
  (((i, i+1) as foo, bar)).foo
  (((1, 2) as foo, bar)).bar

Release note: None

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37404#-:-LeO14iP2jMWMBC1MQX4:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, and @rytaft)

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37404#-:-LeO3oJD1VgTSUmkQybD:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, and @rytaft)

___
*[pkg/sql/opt/norm/testdata/rules/fold_constants, line 839 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37404#-LeO324e8BEOYi14fmY2:-LeO324fEPqB32NDImA_:bb648xk) ([raw file](https://github.com/cockroachdb/cockroach/blob/214ac831bd037dfc00f612ba2dfa2dc9e6817631/pkg/sql/opt/norm/testdata/rules/fold_constants#L839)):*
> ```
> # NOTE: Use constant array access to avoid triggering ColumnAccess::TypeCheck
> #       constant tuple folding.
> opt
> ```

[nit] expect=FoldColumnAccess ?
___
*[pkg/sql/opt/norm/testdata/rules/fold_constants, line 868 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37404#-LeO3RxJ4A7VuqQyKNjK:-LeO3RxJ4A7VuqQyKNjL:b-3x3v85) ([raw file](https://github.com/cockroachdb/cockroach/blob/214ac831bd037dfc00f612ba2dfa2dc9e6817631/pkg/sql/opt/norm/testdata/rules/fold_constants#L868)):*
> ```
>  ├── key: ()
>  ├── fd: ()-->(1)
>  └── ('foo',) [type=tuple{string}]
> ```

Maybe add a test case where we get an evaluation error? (argument could be `crdb_internal.force_error('', 'some-error')`)

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37404#-:-LeO8DME7qeVHmraVB_X:bnfp4nl)* status: :shipit: complete! 3 of 0 LGTMs obtained (waiting on @andy-kimball)

___
*[pkg/sql/opt/norm/fold_constants.go, line 276 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37404#-LeO6AJRAIxXeLuFdcG2:-LeO6AJRAIxXeLuFdcG3:brjqnde) ([raw file](https://github.com/cockroachdb/cockroach/blob/214ac831bd037dfc00f612ba2dfa2dc9e6817631/pkg/sql/opt/norm/fold_constants.go#L276)):*
> ```Go
> 	// Case 1: The input is a static tuple constructor.
> 	if tup, ok := input.(*memo.TupleExpr); ok {
> 		return tup.Elems[idx]
> ```

What if `idx` is outside the bounds of the tuple (similar to the array case above)? Is that even possible? 
___
*[pkg/sql/opt/norm/fold_constants.go, line 283 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37404#-LeO6OG85wErPA8U8KC7:-LeO6OG85wErPA8U8KC8:b-2guby3) ([raw file](https://github.com/cockroachdb/cockroach/blob/214ac831bd037dfc00f612ba2dfa2dc9e6817631/pkg/sql/opt/norm/fold_constants.go#L283)):*
> ```Go
> 		datum := memo.ExtractConstDatum(input)
> 
> 		colName := input.DataType().TupleLabels()[idx]
> ```

same here
___
*[pkg/sql/opt/norm/testdata/rules/fold_constants, line 847 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37404#-LeO8Vzw41_99YV8erh_:-LeO7wWKD3TfE00QaHXJ:b-u3ihs) ([raw file](https://github.com/cockroachdb/cockroach/blob/214ac831bd037dfc00f612ba2dfa2dc9e6817631/pkg/sql/opt/norm/testdata/rules/fold_constants#L847)):*
> ```
>  ├── scan a
>  └── projections
>       └── const: 'foo' [type=string]
> ```

It seems odd that this results in a scalar while the query below results in a tuple... Is that expected?

**Comment by rytaft** [comment]
___
*[pkg/sql/opt/norm/testdata/rules/fold_constants, line 847 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37404#-LeO8Vzw41_99YV8erh_:-LeOA_RZAJwQI_OnIrp3:boitfyn) ([raw file](https://github.com/cockroachdb/cockroach/blob/214ac831bd037dfc00f612ba2dfa2dc9e6817631/pkg/sql/opt/norm/testdata/rules/fold_constants#L847)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

It seems odd that this results in a scalar while the query below results in a tuple... Is that expected?
</blockquote></details>

Never mind I see why

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37404)* status: :shipit: complete! 3 of 0 LGTMs obtained (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/norm/fold_constants.go, line 276 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37404#-LeO6AJRAIxXeLuFdcG2:-LeOAutJC76THjuyyFvz:b-ak806r) ([raw file](https://github.com/cockroachdb/cockroach/blob/214ac831bd037dfc00f612ba2dfa2dc9e6817631/pkg/sql/opt/norm/fold_constants.go#L276)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

What if `idx` is outside the bounds of the tuple (similar to the array case above)? Is that even possible? 
</blockquote></details>

It's not possible, because the index is derived during type checking according to the static tuple type.
___
*[pkg/sql/opt/norm/testdata/rules/fold_constants, line 868 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37404#-LeO3RxJ4A7VuqQyKNjK:-LeOBfSS6324G-S77m9k:b-hlmk3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/214ac831bd037dfc00f612ba2dfa2dc9e6817631/pkg/sql/opt/norm/testdata/rules/fold_constants#L868)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Maybe add a test case where we get an evaluation error? (argument could be `crdb_internal.force_error('', 'some-error')`)
</blockquote></details>

The evaluation only happens for `DTuple`. It should never fail, but I put the error check there for completeness. Adding `force_error` forces "Case 1", where the input is a static tuple constructor (and we don't eval the tuple field exprs).

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/norm/testdata/rules/fold_constants, line 868 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37404#-LeO3RxJ4A7VuqQyKNjK:-LeONYHbAZLELPVCcXmR:b-govnux) ([raw file](https://github.com/cockroachdb/cockroach/blob/214ac831bd037dfc00f612ba2dfa2dc9e6817631/pkg/sql/opt/norm/testdata/rules/fold_constants#L868)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

The evaluation only happens for `DTuple`. It should never fail, but I put the error check there for completeness. Adding `force_error` forces "Case 1", where the input is a static tuple constructor (and we don't eval the tuple field exprs).
</blockquote></details>

Ah, thanks, that makes sense.

**Pull request merged**
