### PR TITLE
sqltelemetry: add telemetry for multi-region related operations

### PR DESCRIPTION
**Pull request by otan**
see individual commits for details.

Release justification: low risk fix for new functionality

### CODE REVIEW

**Review by ajstorm — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, 10 of 10 files at r2, 8 of 8 files at r3, 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61168)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @otan)

___
*[pkg/ccl/telemetryccl/testdata/telemetry/multiregion, line 76 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61168#-MUiQUdzEnYCrrvrqYTg:-MUiQUe-AIStJqqJ6Roo:b-ftbtd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4068f7062d2a92fd0bdc01a665843a0262b3df0/pkg/ccl/telemetryccl/testdata/telemetry/multiregion#L76)):*
> ```
> CREATE TABLE t3 () LOCALITY REGIONAL BY TABLE IN "ap-southeast-2"
> ----
> sql.multiregion.create_table.locality.regional_by_table_in
> ```

Nit: Do we want something to capture the explicit `REGIONAL BY TABLE IN PRIMARY REGION`?
___
*[pkg/ccl/telemetryccl/testdata/telemetry/multiregion, line 96 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61168#-MUiQgDe6q17xb17j625:-MUiQgDe6q17xb17j626:b-jel4gn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4068f7062d2a92fd0bdc01a665843a0262b3df0/pkg/ccl/telemetryccl/testdata/telemetry/multiregion#L96)):*
> ```
> ALTER TABLE t1 SET LOCALITY REGIONAL BY ROW
> ----
> sql.multiregion.alter_table.locality.regional_by_table.regional_by_row
> ```

Nit: Why only test alter to RBR?  Should we not test all of the permutations?
___
*[pkg/sql/alter_database.go, line 608 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61168#-MUiNlnH1Bp9GGYaffRp:-MUiNlnH1Bp9GGYaffRq:b-t7z26f) ([raw file](https://github.com/cockroachdb/cockroach/blob/c630f82caab7fe5ff6820d4e27def72dfe871a79/pkg/sql/alter_database.go#L608)):*
> ```Go
> // is already a multi-region database.
> func (n *alterDatabasePrimaryRegionNode) setInitialPrimaryRegion(params runParams) error {
> 	telemetry.Inc(sqltelemetry.NewMultiRegionDatabaseUsingAlterCounter)
> ```

Nit: Is there a reason you didn't go with `SetInitialPrimaryRegionCounter` here?  Might be easiest if all of these map as close as possible to their function names.
___
*[pkg/sql/create_table.go, line 2268 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61168#-MUiRKFa9eL8OBnclr_p:-MUiRKFa9eL8OBnclr_q:b2jo0hm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4068f7062d2a92fd0bdc01a665843a0262b3df0/pkg/sql/create_table.go#L2268)):*
> ```Go
> 
> 	if regionEnumID != descpb.InvalidID || n.Locality != nil {
> 		localityTelemetryName := "unspecified"
> ```

"unspecified" might be a bit misleading here, as (I think) the only way you can get down this path is if you're in a non-multi-region database.  Should we maybe articulate that clearly here?  Or, better yet, for the database work clearly specify which databases aren't created as multi-region and then move the locality counter below into the if branch so that it only shows up for mulit-region enabled databases.
___
*[pkg/sql/sqltelemetry/multiregion.go, line 79 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61168#-MUiT0sCCCOiFnA-K6Sv:-MUiT0sCCCOiFnA-K6Sw:b-t285td) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4068f7062d2a92fd0bdc01a665843a0262b3df0/pkg/sql/sqltelemetry/multiregion.go#L79)):*
> ```
> fmt.Sprintf("sql.multiregion.alter_table.locality.%s.%s", from, to)
> ```

`fmt.Sprintf("sql.multiregion.alter_table.locality.from.%s.to.%s", from, to)`?
___
*[pkg/sql/catalog/descpb/multiregion.go, line 54 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61168#-MUiRmk81-1XedbUV7ba:-MUiRmk81-1XedbUV7bb:bhdva1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4068f7062d2a92fd0bdc01a665843a0262b3df0/pkg/sql/catalog/descpb/multiregion.go#L54)):*
> ```Go
> }
> 
> // TelemetryName returns the name to use for telemetry for this configuration.
> ```

Nit: "...for the given table locality"?
___
*[pkg/sql/catalog/descpb/multiregion.go, line 61 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61168#-MUiSIjsC9n00Alstgxa:-MUiSIjsC9n00Alstgxb:b5eempb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4068f7062d2a92fd0bdc01a665843a0262b3df0/pkg/sql/catalog/descpb/multiregion.go#L61)):*
> ```Go
> 	case *TableDescriptor_LocalityConfig_RegionalByTable_:
> 		if l.RegionalByTable.Region != nil {
> 			return tree.TelemetryNameRegionalByTableIn
> ```

Do we need to differentiate between a specified region and the `PRIMARY REGION`?
___
*[pkg/sql/catalog/descpb/multiregion.go, line 70 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61168#-MUiS15A6qocug8792Mb:-MUiS15A6qocug8792Mc:b-fmo1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4068f7062d2a92fd0bdc01a665843a0262b3df0/pkg/sql/catalog/descpb/multiregion.go#L70)):*
> ```Go
> 		return tree.TelemetryNameRegionalByRow
> 	}
> 	panic(errors.AssertionFailedf("unknown locality: %#v", *cfg))
> ```

Why the panic here?  Would it not be better to have this function return an error and pass the assertion failure up the stack?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61168)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @dt)

___
*[pkg/ccl/telemetryccl/testdata/telemetry/multiregion, line 76 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61168#-MUiQUdzEnYCrrvrqYTg:-MUj2yyQ5YKCjNDos1sS:b-2gkmp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4068f7062d2a92fd0bdc01a665843a0262b3df0/pkg/ccl/telemetryccl/testdata/telemetry/multiregion#L76)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Do we want something to capture the explicit `REGIONAL BY TABLE IN PRIMARY REGION`?
</blockquote></details>

do we want to put this info into the tree.Locality node? we also don't encode this information in descpb.LocalityConfig, which means this is always going to be missing.
i'm not sure it matters, but if you feel strongly ya.
___
*[pkg/ccl/telemetryccl/testdata/telemetry/multiregion, line 96 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61168#-MUiQgDe6q17xb17j625:-MUj3HbD37WPhHgd1vXw:bkmp6vo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4068f7062d2a92fd0bdc01a665843a0262b3df0/pkg/ccl/telemetryccl/testdata/telemetry/multiregion#L96)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Why only test alter to RBR?  Should we not test all of the permutations?
</blockquote></details>

if only i had for loops.
seriously though, we have 25 combinations that are possible, and i'm not sure it's useful. the other combinations / other code test the other code paths.
oh well here they are
___
*[pkg/sql/create_table.go, line 2268 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61168#-MUiRKFa9eL8OBnclr_p:-MUj5D3hB2K5gAYKPPGs:b-sqfrsf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4068f7062d2a92fd0bdc01a665843a0262b3df0/pkg/sql/create_table.go#L2268)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

"unspecified" might be a bit misleading here, as (I think) the only way you can get down this path is if you're in a non-multi-region database.  Should we maybe articulate that clearly here?  Or, better yet, for the database work clearly specify which databases aren't created as multi-region and then move the locality counter below into the if branch so that it only shows up for mulit-region enabled databases.
</blockquote></details>

not quite; it's if you define `CREATE TABLE` with no locality
___
*[pkg/sql/sqltelemetry/multiregion.go, line 79 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61168#-MUiT0sCCCOiFnA-K6Sv:-MUjAUnx2M0WXA92AR_d:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4068f7062d2a92fd0bdc01a665843a0262b3df0/pkg/sql/sqltelemetry/multiregion.go#L79)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

> ```
> fmt.Sprintf("sql.multiregion.alter_table.locality.%s.%s", from, to)
> ```

`fmt.Sprintf("sql.multiregion.alter_table.locality.from.%s.to.%s", from, to)`?
</blockquote></details>

Done.
___
*[pkg/sql/catalog/descpb/multiregion.go, line 61 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61168#-MUiSIjsC9n00Alstgxa:-MUj9ai08sxqBXJ4lkIk:b-wd6zv0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4068f7062d2a92fd0bdc01a665843a0262b3df0/pkg/sql/catalog/descpb/multiregion.go#L61)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Do we need to differentiate between a specified region and the `PRIMARY REGION`?
</blockquote></details>

We can't, we don't encode that info in the locality config.
___
*[pkg/sql/catalog/descpb/multiregion.go, line 70 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61168#-MUiS15A6qocug8792Mb:-MUj3UPc1ovwwL2WxTAF:b-z7aivi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4068f7062d2a92fd0bdc01a665843a0262b3df0/pkg/sql/catalog/descpb/multiregion.go#L70)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Why the panic here?  Would it not be better to have this function return an error and pass the assertion failure up the stack?
</blockquote></details>

a) i don't think this should ever be valid state. it similar to how we panic in String() on certain tree elems using case.
b) errors make the code more annoying to handle and everything pass up :P, especially for something that should return an identifying string.

given (a) alone i think panicking is fine given the "risk", but passing error through TelemetryName() errors has cascading effects on other functions which don't look like they should return errors. depends how strong you feel basically.

**Review by ajstorm — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61168)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @dt, and @otan)

___
*[pkg/ccl/telemetryccl/testdata/telemetry/multiregion, line 76 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61168#-MUiQUdzEnYCrrvrqYTg:-MUjEUj1CVfU1qmovwZY:b43qyb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4068f7062d2a92fd0bdc01a665843a0262b3df0/pkg/ccl/telemetryccl/testdata/telemetry/multiregion#L76)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

do we want to put this info into the tree.Locality node? we also don't encode this information in descpb.LocalityConfig, which means this is always going to be missing.
i'm not sure it matters, but if you feel strongly ya.

</blockquote></details>

I don't think it's necessary for now, but maybe open an issue?
___
*[pkg/ccl/telemetryccl/testdata/telemetry/multiregion, line 96 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61168#-MUiQgDe6q17xb17j625:-MUjFfuc4Wy1OSyklkyw:bnnon6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4068f7062d2a92fd0bdc01a665843a0262b3df0/pkg/ccl/telemetryccl/testdata/telemetry/multiregion#L96)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

if only i had for loops.
seriously though, we have 25 combinations that are possible, and i'm not sure it's useful. the other combinations / other code test the other code paths.
oh well here they are
</blockquote></details>

I guess I got what I deserved on that one ;-) 
___
*[pkg/sql/catalog/descpb/multiregion.go, line 70 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61168#-MUiS15A6qocug8792Mb:-MUjGW349eaeILJTYEem:b6cdckv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4068f7062d2a92fd0bdc01a665843a0262b3df0/pkg/sql/catalog/descpb/multiregion.go#L70)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

a) i don't think this should ever be valid state. it similar to how we panic in String() on certain tree elems using case.
b) errors make the code more annoying to handle and everything pass up :P, especially for something that should return an identifying string.

given (a) alone i think panicking is fine given the "risk", but passing error through TelemetryName() errors has cascading effects on other functions which don't look like they should return errors. depends how strong you feel basically.
</blockquote></details>

I tend to agree that the risk here is low, as this should be caught on the first merge of a PR which adds a new locality, but at the same time, there's this: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/181371303/Go+Golang+coding+guidelines#Go(Golang)codingguidelines-Don'tPanic.  

Since this is coming from a DDL operation, which when it fails will leave the node up, I'm inclined to change things so that the error percolates up, as opposed to panicking.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61168)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @dt)

___
*[pkg/ccl/telemetryccl/testdata/telemetry/multiregion, line 76 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61168#-MUiQUdzEnYCrrvrqYTg:-MUjRQfx3GPpgCfCPSzx:bcx5vln) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4068f7062d2a92fd0bdc01a665843a0262b3df0/pkg/ccl/telemetryccl/testdata/telemetry/multiregion#L76)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

I don't think it's necessary for now, but maybe open an issue?
</blockquote></details>

are we going to action it in any way? if not, not sure it's worth an issue :P 
___
*[pkg/sql/catalog/descpb/multiregion.go, line 70 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61168#-MUiS15A6qocug8792Mb:-MUjUTjR8GOkWCSaD_U_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4068f7062d2a92fd0bdc01a665843a0262b3df0/pkg/sql/catalog/descpb/multiregion.go#L70)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

I tend to agree that the risk here is low, as this should be caught on the first merge of a PR which adds a new locality, but at the same time, there's this: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/181371303/Go+Golang+coding+guidelines#Go(Golang)codingguidelines-Don'tPanic.  

Since this is coming from a DDL operation, which when it fails will leave the node up, I'm inclined to change things so that the error percolates up, as opposed to panicking.
</blockquote></details>

Done.

**Review by ajstorm — COMMENTED** [review]
Nit: "Low-rish"? :joy: 

> Reviewed 17 of 17 files at r6, 10 of 10 files at r7, 8 of 8 files at r8, 8 of 8 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61168#-:-MUnAHeP9YRV8KgDsBc8:b-bwlfmy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @dt, and @otan)

___
*[pkg/ccl/telemetryccl/testdata/telemetry/multiregion, line 76 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61168#-MUiQUdzEnYCrrvrqYTg:-MUnDQ6J88Prkrw95BDq:bz34v6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4068f7062d2a92fd0bdc01a665843a0262b3df0/pkg/ccl/telemetryccl/testdata/telemetry/multiregion#L76)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

are we going to action it in any way? if not, not sure it's worth an issue :P 
</blockquote></details>

I could see the distinction between REGIONAL BY TABLE and REGIONAL BY TABLE IN PRIMARY REGION being valuable from a telemetry perspective, but I'm not sure we'd invest in making that change.  Maybe it's a reasonable starter project?
___
*[pkg/sql/create_table.go, line 2268 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61168#-MUiRKFa9eL8OBnclr_p:-MUnJXzN5XLw_P6v0S7h:bduno3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4068f7062d2a92fd0bdc01a665843a0262b3df0/pkg/sql/create_table.go#L2268)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

not quite; it's if you define `CREATE TABLE` with no locality
</blockquote></details>

Right, not sure how I missed that the first time through.
___
*[pkg/sql/catalog/descpb/multiregion.go, line 70 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61168#-MUiS15A6qocug8792Mb:-MUnKdZK7R3P16rSd_Sk:b-83sjo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4068f7062d2a92fd0bdc01a665843a0262b3df0/pkg/sql/catalog/descpb/multiregion.go#L70)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice.

**Review by ajstorm — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61168)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @otan)

**Comment by awoods187** [comment]
I looked through this list and it seems comprehensive for DDL. I didn't see a few entries (but may have missed them) for other functionality, can we also capture the list below?

- [ ] How often we use the SQL gateway for inserts
- [ ] How often the CBO plans locally vs. fans out 
- [ ] Import into multi-region

**Comment by otan** [comment]
> I looked through this list and it seems comprehensive for DDL. I didn't see a few entries (but may have missed them) for other functionality, can we also capture the list below?

can you file issues for each?

**Comment by otan** [comment]
bors r=ajstorm

**Pull request merged**
