### PR TITLE
sampledataccl: add an abstraction for ccl testdata

### PR DESCRIPTION
**Pull request by danhhz**
Data is a representation of a sql table, used for creating test data in
various forms (sql rows, kvs, enterprise backup).

We only have one for the moment (a bank table with an id, balance, and
payload for padding row-size), but the indirection of the interface
didn't really add any complexity.

This also moves over a number of our existing tests & benchmarks and adds a new benchmark for the Import command.

### CODE REVIEW

**Comment by dt** [comment]
bikeshed: I think I'd call it something like `testingdata`, `testschema`, or `dummydata` -- "data" is pretty broad.

**Comment by dt** [comment]
I haven't finished throughly reviewing yet, but submitting a couple initial thoughts before I log off for the day.

---

Reviewed 9 of 13 files at r1.
Review status: 9 of 13 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/utilccl/dataccl/bankdata.go, line 36 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16541#-Kmhjtsw6XQRAcuwZ1BO:-KmhjtsxvbCYNDF9Yk7J:b-w4qgrk) ([raw file](https://github.com/cockroachdb/cockroach/blob/68a989d54cc585ff8d1cc35cf9a90129bc8a84bc/pkg/ccl/utilccl/dataccl/bankdata.go#L36)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/util/hlc"
> 	"github.com/cockroachdb/cockroach/pkg/util/randutil"
> 	"github.com/pkg/errors"
> ```

nit: should sort above.

---

*[pkg/ccl/utilccl/dataccl/bankdata.go, line 97 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16541#-KmhlsjcxuT_vqUAIL1T:-KmhlsjcxuT_vqUAIL1U:bel85f7) ([raw file](https://github.com/cockroachdb/cockroach/blob/68a989d54cc585ff8d1cc35cf9a90129bc8a84bc/pkg/ccl/utilccl/dataccl/bankdata.go#L97)):*
> ```Go
> }
> 
> // Split creates the configured number of ranges in a created version of the
> ```

nit: *already created* version of ...

---

*[pkg/ccl/utilccl/dataccl/bankdata.go, line 147 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16541#-Kmhm6WhJ0SczH_6YzYL:-Kmhm6WhJ0SczH_6YzYM:bl64xnz) ([raw file](https://github.com/cockroachdb/cockroach/blob/68a989d54cc585ff8d1cc35cf9a90129bc8a84bc/pkg/ccl/utilccl/dataccl/bankdata.go#L147)):*
> ```Go
> 	defer dirCleanupFn()
> 
> 	// TODO(dan): Get rid of the `t testing.TB` parameter and this `TestServer`.
> ```

yeah, the `testing` import means this package is unusable outside tests (e.g. if you wanted to subsume the cli's example data) thanks to their flag registration if it is linked.

also, more generally, frequently when we start by passing around a *testing.T, we often later end up refactoring to avoid that (passing errors or whatever instead), usually because we accidentally Fatal across goroutines.

If possible, I'd encourage attempting to avoid passing it now, potentially at the expense of a little less DRY, but maybe that's not that easy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16541#-:-KmhmdO5s5X5akEdXavv:b-6rj0qc)*

**Comment by danhhz** [comment]
`testdata` nicely parallels our `testutil` convention, so went with `testdataccl`. RFAL

---

Review status: 1 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/ccl/utilccl/dataccl/bankdata.go, line 36 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16541#-Kmhjtsw6XQRAcuwZ1BO:-KmlY3o5aT39WFsI6XEq:bbbiexi) ([raw file](https://github.com/cockroachdb/cockroach/blob/68a989d54cc585ff8d1cc35cf9a90129bc8a84bc/pkg/ccl/utilccl/dataccl/bankdata.go#L36)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

nit: should sort above.
</blockquote></details>

Done. Though in general I'd like to push back on this particular comment. If goimports is happy, we should be too

---

*[pkg/ccl/utilccl/dataccl/bankdata.go, line 97 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16541#-KmhlsjcxuT_vqUAIL1T:-KmlY1J2OEhcAil-R1oX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/68a989d54cc585ff8d1cc35cf9a90129bc8a84bc/pkg/ccl/utilccl/dataccl/bankdata.go#L97)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

nit: *already created* version of ...
</blockquote></details>

Done.

---

*[pkg/ccl/utilccl/dataccl/bankdata.go, line 147 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16541#-Kmhm6WhJ0SczH_6YzYL:-KmlX5AGUwHAh-nOHYwx:b-h415q3) ([raw file](https://github.com/cockroachdb/cockroach/blob/68a989d54cc585ff8d1cc35cf9a90129bc8a84bc/pkg/ccl/utilccl/dataccl/bankdata.go#L147)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

yeah, the `testing` import means this package is unusable outside tests (e.g. if you wanted to subsume the cli's example data) thanks to their flag registration if it is linked.

also, more generally, frequently when we start by passing around a *testing.T, we often later end up refactoring to avoid that (passing errors or whatever instead), usually because we accidentally Fatal across goroutines.

If possible, I'd encourage attempting to avoid passing it now, potentially at the expense of a little less DRY, but maybe that's not that easy.
</blockquote></details>

going to leave this as a todo, it's only necessary for the testserver, which could go away with a little work in Load (it's only used to fetch a database descriptor). that change definitely deserves its own pr though

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16541#-:-KmlSkQoxOyITBc3XF0E:btzaogx)*

**Comment by dt** [comment]
hm, that works, if only thanks to the "ccl" suffix. That said, it might be a little bit confusing since this is actually an importable, buildable package? I guess we can revisit if/when we ever try to move this out of ccl and the reserved name becomes a real issue.

---

Review status: 1 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/utilccl/testdataccl/bankdata.go, line 36 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16541#-Kmhjtsw6XQRAcuwZ1BO:-KmledUgwtqI7csWG1NU:b-t03cjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/68a989d54cc585ff8d1cc35cf9a90129bc8a84bc/pkg/ccl/utilccl/testdataccl/bankdata.go#L36)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Done. Though in general I'd like to push back on this particular comment. If goimports is happy, we should be too
</blockquote></details>

Fair. That used to be my motto too, until a few cases where`goimports` generated some really bad lists -- several single line sections of effectively unsorted stdlib imports -- made me start taking a quick glance at them in my diffs.

---

*[pkg/ccl/utilccl/testdataccl/bankdata.go, line 147 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16541#-Kmhm6WhJ0SczH_6YzYL:-KmlgM2SSAzldYFmpQZh:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/68a989d54cc585ff8d1cc35cf9a90129bc8a84bc/pkg/ccl/utilccl/testdataccl/bankdata.go#L147)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

going to leave this as a todo, it's only necessary for the testserver, which could go away with a little work in Load (it's only used to fetch a database descriptor). that change definitely deserves its own pr though
</blockquote></details>

:thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16541#-:-KmldU8ky3it5WyrvxUd:b9aps0w)*

**Comment by danhhz** [comment]
After discussion offline, switched to sampledata

**Comment by benesch** [comment]
This is :thumbsup: in principle and at a high-level, but still haven't found time to do an in-depth review. Hopeful I'll have time on the plane today. Don't let me hold this up though if it LG to someone else.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16541#-:-Kn-pPBJMM66iBpRrwAL:b5ijt2p)*

**Comment by dt** [comment]
:lgtm: don't forget PR title

---

Reviewed 6 of 18 files at r2, 1 of 3 files at r3, 4 of 7 files at r4.
Review status: 4 of 13 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16541#-:-Kn-vszILofpDzHRkRgR:b-hzwvle)*

**Comment by danhhz** [comment]
good call on the PR title (I was so pleased that I caught the commit message)

TFTR! @benesch I'm planning a few followup PRs to this, so please do take a look and I'll address any feedback you have

**Pull request merged**
