### PR TITLE
 sqlbase: generalize IMPORTING state to OFFLINE

### PR DESCRIPTION
**Pull request by dt**
This renames the IMPORTING TableDescriptor state to OFFLINE for reuse outside IMPORT,
and adds a free-form string field OfflineReason in which the process that marked the
table as OFFFLINE can record the reason to surface in user-visible error messages.

### CODE REVIEW

**Review by adityamaru27 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39723)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @lucy-zhang)

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39723)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @jordanlewis)

___
*[pkg/sql/sqlbase/structured.proto, line 556 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39723#-LmeL0YY9QaxiSnzi0w7:-LmeL0YY9QaxiSnzi0w8:b9vt1ft) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ccb300ecf002f4aa61a8de614e2da463e332b1/pkg/sql/sqlbase/structured.proto#L556)):*
> ```protobuf
>   }
>   optional State state = 19 [(gogoproto.nullable) = false];
>   optional string offline_reason = 38 [(gogoproto.nullable) = false];
> ```

Do you think this should be an enum instead, in case we ever want to match on specific reasons?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39723)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @lucy-zhang)

___
*[pkg/sql/sqlbase/structured.proto, line 556 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39723#-LmeL0YY9QaxiSnzi0w7:-LmeLwrgBkgign5g-qF3:bvxglyp) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ccb300ecf002f4aa61a8de614e2da463e332b1/pkg/sql/sqlbase/structured.proto#L556)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Do you think this should be an enum instead, in case we ever want to match on specific reasons?
</blockquote></details>

I thought about an enum but I ended up figuring if you need to match a specific reason and handle it differently, the table state enum already gets you that -- the value of `Offline` is that you _don't_ need to modify the proto and all the switch statements if you want to take a table offline for a different reason.

**Review by thoszhang — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39723)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @jordanlewis)

___
*[pkg/sql/sqlbase/structured.proto, line 556 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39723#-LmeL0YY9QaxiSnzi0w7:-LmeN13P25ijGCP3FWFR:busrgv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ccb300ecf002f4aa61a8de614e2da463e332b1/pkg/sql/sqlbase/structured.proto#L556)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I thought about an enum but I ended up figuring if you need to match a specific reason and handle it differently, the table state enum already gets you that -- the value of `Offline` is that you _don't_ need to modify the proto and all the switch statements if you want to take a table offline for a different reason.
</blockquote></details>

I was thinking `offline_reason` would be a separate enum, so that adding new values wouldn't affect the switch statements, etc. on `state`. I guess if there's a new reason for taking the table offline whose behavior is different enough from the existing `State`s, then we would add a new `State` anyway. I think the string is fine.

**Pull request merged**
