### PR TITLE
sql: convert mem_limit logic test into a unit test

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit converts the `mem_limit` logic test into a corresponding
unit test and expands it. It is written under the assumption that the
Streamer API has already been implemented to support the index joins, so
there are now two test cases. The index join will soon be powered by the
Streamer and requires some concurrency to hit the memory limit whereas
the new case that is doing a simple read (and will not be powered by the
Streamer) can get away with no concurrency.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73126)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola and @yuzefovich)

___
*[pkg/sql/mem_limit_test.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73126#-MpIaGnI7Wjykg0L7KVg:-MpIaGnJ14M3I7tq5WEP:b-8sfcr0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2451b0041d71352a9ffd5a5d1d52ab07c83e96a/pkg/sql/mem_limit_test.go#L41)):*
> ```Go
> 
> 	// We'll use a small value for --max-sql-memory startup argument but will
> 	// not modify the distsql_workmem variable (which is 64MiB by default).
> ```

so that it doesn't spill to disk and spoil the test?

expanding the code comment would help.
___
*[pkg/sql/mem_limit_test.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73126#-MpIaRmAAKDJvqq-Lu_B:-MpIaRmAAKDJvqq-Lu_C:b4vkv71) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2451b0041d71352a9ffd5a5d1d52ab07c83e96a/pkg/sql/mem_limit_test.go#L70)):*
> ```Go
> 			wg.Add(numGoroutines)
> 			errCh := make(chan error, numGoroutines)
> 			for i := 0; i < numGoroutines; i++ {
> ```

is the concurrent execution the thing that causes the memory to be exceeded?
would it be always fail with a single query if there were more rows in the table?

**Review by yuzefovich — COMMENTED** [review]
I expanded the test so that in at least one case the memory error is hit when evaluating MVCC requests (what previous `mem_limit` logic test asserted).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73126#-:-MpJ1WlZ-n4nlifjz62_:b-1i0ow8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/sql/mem_limit_test.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73126#-MpIaGnI7Wjykg0L7KVg:-MpIvjNS95rO2lRxGFxf:budu4ua) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2451b0041d71352a9ffd5a5d1d52ab07c83e96a/pkg/sql/mem_limit_test.go#L41)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

so that it doesn't spill to disk and spoil the test?

expanding the code comment would help.
</blockquote></details>

I dropped the part about `distsql_workmem` since it's not that important and expanded the comment to indicate what's expected depending on whether the new Streamer API is used.
___
*[pkg/sql/mem_limit_test.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73126#-MpIaRmAAKDJvqq-Lu_B:-MpJ1O1DCHqbCWhQwmjD:b-282dwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2451b0041d71352a9ffd5a5d1d52ab07c83e96a/pkg/sql/mem_limit_test.go#L70)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is the concurrent execution the thing that causes the memory to be exceeded?
would it be always fail with a single query if there were more rows in the table?
</blockquote></details>

Hopefully the expanded comment above answers these questions.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73126#-:-MpgQRSc0TPl-otcSTal:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola and @yuzefovich)

___
*[pkg/sql/mem_limit_test.go, line 40 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73126#-MpgPyVt5-Okp3LkTxOr:-MpgPyVt5-Okp3LkTxOs:b-j6d7qv) ([raw file](https://github.com/cockroachdb/cockroach/blob/da2cf76fd4a9800eb1f061272a3b009254921ef1/pkg/sql/mem_limit_test.go#L40)):*
> ```Go
> 	//
> 	// When the Streamer API is not used, then SQL creates a single BatchRequest
> 	// for both blobs without setting TargetBytes, so the pebble is happy to get
> ```

nit:
... so the storage layer is happy ...

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73126#-:-MpgdKiA2Mp1Z32CHryt:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @sumeerbhola)

**Pull request merged**
