### PR TITLE
Avoid named returns [NFC]

### PR DESCRIPTION
**Pull request by tamird**
@MBerhault this seems nicer, especially when looking at your pending PR. Thoughts?

### CODE REVIEW

**Comment by MBerhault** [comment]
maybe, although I get the point of named returns when there are a lot of them. At some point, it boils down to personal preference.
In the mentioned PR, I prefer to stick to the changes I'm making rather than confuse things by refactoring at the same time.

**Comment by tschottdorf** [comment]
I'm also in favor of avoiding named returns except in rare circumstances. They make it harder for me to follow along, especially in larger blocks of code. The code [review comments](https://github.com/golang/go/wiki/CodeReviewComments#named-result-parameters) aren't as strict though, so while I'd personally like to see only few of them, I can't really base that on some community rule.

**Comment by tamird** [comment]
Rebased

**Comment by MBerhault** [comment]
This seems like exactly the kind of function where using named returns is convenient. 4 return parameters gets a little much on return statements.

**Comment by mrtracy** [comment]
Named return parameters are mostly needed when there is ambiguity between return parameters - for example, if there were multiple return parameters with the same type (e.g. returning multiple integers resulting from a computation, or returning an "old" and "new" version of some structure).  That's the situation where named return params shine.

They are also useful in combination with `defer()`, if you need to inspect a returned value before actually returning it.

**Comment by tamird** [comment]
@mrtracy :8ball:

**Pull request merged**
