### PR TITLE
server: serve all traffic on a single port

### PR DESCRIPTION
**Pull request by tamird**
The last three commits are the meat of this change:
- the first introduces cmux
- the second implements pg connection muxing
- the third cleans up extraneous plumbing and is largely mechanical

Tests pass on all three, though I think I'd like to squash the last two before merging.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4536)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Pretty sweet. I'm a bit lost with all the different pathways - there's no `http2.(*Server).ServeConn` in the non-tls case because unencrypted http2 isn't an option? When running `--insecure`, which connections will be what (i.e. where's gRPC when non-TLS)? That diagram in one commit message is good, but maybe add your explanation to it.

---

Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 5 of 5 files at r3, 19 of 19 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/server.go, line 240 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-KAzr0sLpsmzSwwzONDq:-KAzr0sLpsmzSwwzONDr:-469765787) ([raw file](https://github.com/cockroachdb/cockroach/blob/526c21b53c5c7114f880c47b37ab6f985d0e8286/server/server.go#L240)):*
ditto

---

*[util/net.go, line 38 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-KAzm9qlvZLtBmolg4Tg:-KAzm9qlvZLtBmolg4Th:-1266290527) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9999eb5ee4dca349b8e42b36b9220228bc850bd/util/net.go#L38)):*
```go
if err != nil {
  return ln, err
}
```

saves a lot of indentation and is imo clearer.

---

*[util/net.go, line 41 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-KAzmLeyAz0_Q4fzgFGW:-KAzmLeyAz0_Q4fzgFGX:474356024) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9999eb5ee4dca349b8e42b36b9220228bc850bd/util/net.go#L41)):*
I'm assuming it's not trivial to hunt those down and fix them?

---

*[util/net.go, line 52 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-KAznr8PfhqkgW4b4D8P:-KAznr8PfhqkgW4b4D8Q:1791123986) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9999eb5ee4dca349b8e42b36b9220228bc850bd/util/net.go#L52)):*
Could you sprinkle some comments from here down?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-:-KAzsEEPyZiWSUWVzu_E:-1540554385)*

**Comment by tamird** [comment]
>  there's no `http2.(*Server).ServeConn` in the non-tls case

There's actually no `http2.(*Server).ServeConn` in the with-tls case, and that's because `http.(*Server).Serve` takes care of it.

There's no difference between tls/non-tls connections.

---

Review status: 24 of 25 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/server.go, line 240 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-KAzr0sLpsmzSwwzONDq:-KAzvaNgGN080X9qTUrJ:-1892223920) ([raw file](https://github.com/cockroachdb/cockroach/blob/526c21b53c5c7114f880c47b37ab6f985d0e8286/server/server.go#L240)):*
This one can be removed. Done.

---

*[util/net.go, line 41 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-KAzmLeyAz0_Q4fzgFGW:-KAzuk_k9KxJL4y0j4VQ:993932769) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9999eb5ee4dca349b8e42b36b9220228bc850bd/util/net.go#L41)):*
That wouldn't really be "fixing" - they're shutting down the listener because they're simulating one side of a connection shutting down. Also note that this is code movement.

---

*[util/net.go, line 52 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-KAznr8PfhqkgW4b4D8P:-KAzxXOtoWzH-8w4F_3A:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9999eb5ee4dca349b8e42b36b9220228bc850bd/util/net.go#L52)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-:-KAzvCcG-I1rn32675Ro:1269959801)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[util/net.go, line 53 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-KB-08mldZPLzIhDS0IX:-KB-08mldZPLzIhDS0IY:-112774426) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ee349f181089dfc65cf4c2f332eede767725933/util/net.go#L53)):*
s/h2c/h2c (HTTP2 Clear Text)/

---

*[util/net.go, line 56 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-KB-0WE5HXM1Gt5C-rht:-KB-0WE5HXM1Gt5C-rhu:-640858786) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ee349f181089dfc65cf4c2f332eede767725933/util/net.go#L56)):*
what actually happens behind the scenes? The connection starts with a HTTP/1.1 request with an `Upgrade` header, right? Does that already hit the h2L listener or does it get served through `anyL`? And if so, why is the correct upgrade performed still?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[util/net.go, line 38 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-KAzm9qlvZLtBmolg4Tg:-KB-2NfK2fV1udutJIUE:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9999eb5ee4dca349b8e42b36b9220228bc850bd/util/net.go#L38)):*
Done.

---

*[util/net.go, line 53 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-KB-08mldZPLzIhDS0IX:-KB-1keRFaZ6IVKl-JZE:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ee349f181089dfc65cf4c2f332eede767725933/util/net.go#L53)):*
Done.

---

*[util/net.go, line 56 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-KB-0WE5HXM1Gt5C-rht:-KB-1YONJN-3Qfz2ES94:297793393) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ee349f181089dfc65cf4c2f332eede767725933/util/net.go#L56)):*
There is no `Upgrade` header. The connection starts with `http.ClientPreface`, which is how `h2L` can match it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536)*

**Comment by petermattis** [comment]
I need to take a look at this again when I'm fresher, but so far it looks good. Those ascii diagrams in the commit message deserve to be comments in the code.

---

Review status: 24 of 25 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[GLOCKFILE, line 64 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-KB0JSJJT2vqar-ndQzn:-KB0JSJJT2vqar-ndQzo:-1864382414) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9b3c12f16f0f8f8ea31a9a903903f9519d1e80b/GLOCKFILE#L64)):*
Any reason you forked `cmux` to `tamird/cmux`? Our pattern so far has to been to make a repo in the `cockroachdb` organization. Not sure that it matters, just wondering if there was some non-obvious motivation here.

Looks like you made a number of enhancements to `tamird/cmux`. Should those get reviewed?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-:-KB0Lcasl80ZxU1wpbHP:788782354)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536)*

**Comment by tamird** [comment]
Done.

---

Review status: 23 of 25 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[GLOCKFILE, line 64 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-KB0JSJJT2vqar-ndQzn:-KB1dOES9tGCcJXDSyRU:-695478226) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9b3c12f16f0f8f8ea31a9a903903f9519d1e80b/GLOCKFILE#L64)):*
No strong reason. I forked it to tamird when I expected to put all my changes upstream. I'll bring it into cockroachdb if that doesn't work out.

Yeah, they probably should be. Let me see if I can get that stuff upstream; if not, I'll fork to cockroachdb and open a PR.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-:-KB1bPLgceyTghJKN8SW:-499146009)*

**Comment by tamird** [comment]
@bdarnell I'd appreciate your eyes on this.

**Comment by bdarnell** [comment]
LGTM as long as your `cmux` changes are either merged upstream or the fork is moved to `cockroachdb/cmux`

---

Review status: 22 of 28 files reviewed at latest revision, 3 unresolved discussions.

---

*[util/net.go, line 34 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-KB5hdmWXYETRZVMJ9rO:-KB5hdmWXYETRZVMJ9rP:-636723936) ([raw file](https://github.com/cockroachdb/cockroach/blob/c51db0fddeaca659e9990e797a6741acf0ce591c/util/net.go#L34)):*
Is this only used in tests now? Probably worth a comment that the "real" server uses its own implementation of this pattern in `server/server.go`.

---

*[util/net.go, line 155 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-KB5gfsA59cMhCAPRHDg:-KB5gfsA59cMhCAPRHDh:-405258905) ([raw file](https://github.com/cockroachdb/cockroach/blob/c51db0fddeaca659e9990e797a6741acf0ce591c/util/net.go#L155)):*
What does this comment mean?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-:-KB5i9qK5LpXnyY8Wixq:711932669)*

**Comment by tamird** [comment]
Review status: 22 of 28 files reviewed at latest revision, 3 unresolved discussions.

---

*[util/net.go, line 34 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-KB5hdmWXYETRZVMJ9rO:-KB5ixUWPNLbcZ5spvkH:1373578803) ([raw file](https://github.com/cockroachdb/cockroach/blob/c51db0fddeaca659e9990e797a6741acf0ce591c/util/net.go#L34)):*
That comment exists in server/server.go

---

*[util/net.go, line 155 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-KB5gfsA59cMhCAPRHDg:-KB5j29XF3sdG1pfHzaM:1310079488) ([raw file](https://github.com/cockroachdb/cockroach/blob/c51db0fddeaca659e9990e797a6741acf0ce591c/util/net.go#L155)):*
Damned if I know. I copied this code from the standard library and tried to modify it as little as possible.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536)*

**Comment by bdarnell** [comment]
Have you run any benchmarks with this? Does the `cmux` connection wrapper add any noticeable overhead?

---

Review status: 22 of 28 files reviewed at latest revision, 2 unresolved discussions.

---

*[util/net.go, line 34 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-KB5hdmWXYETRZVMJ9rO:-KB5jk66yFsgx9136ej7:524488763) ([raw file](https://github.com/cockroachdb/cockroach/blob/c51db0fddeaca659e9990e797a6741acf0ce591c/util/net.go#L34)):*
Yeah, I just think it would be good to mention it here too because someone who finds this file may not even realize that there is another copy of this logic somewhere else.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-:-KB5jzMCcI8k4DkcJrcf:-1750120868)*

**Comment by tamird** [comment]
I haven't. I'll run the SQL benchmarks tomorrow - I doubt the change will be noticeable (cmux will read and buffer at most 24 bytes per connection).

---

Review status: 22 of 27 files reviewed at latest revision, 2 unresolved discussions.

---

*[util/net.go, line 34 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-KB5hdmWXYETRZVMJ9rO:-KB5mip6YrWT2I1_XozM:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/c51db0fddeaca659e9990e797a6741acf0ce591c/util/net.go#L34)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-:-KB5mkPwJWRrqFU8mcjh:1489608869)*

**Comment by vivekmenezes** [comment]
Can you change the PR description to, "One port to rule them all"?

---

Review status: 22 of 27 files reviewed at latest revision, 5 unresolved discussions.

---

*[base/context.go, line 41 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-KB8VBn-75EX-mhsWVx7:-KB8VBn-75EX-mhsWVx8:1481540393) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee9573b5b56b769e2c9c756e06c2182ea89e5eff/base/context.go#L41)):*
https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=cockroachdb

Add a note that this is the IANA port.

---

*[server/server.go, line 245 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-KB8VpQZPs-sn_7hLwrq:-KB8VpQZPs-sn_7hLwrr:-1718554796) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee9573b5b56b769e2c9c756e06c2182ea89e5eff/server/server.go#L245)):*
Nice documentation and awesome job man!

---

*[util/net.go, line 145 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-KB8Y1PecamESAk_4XkL:-KB8Y1PfyZfTcSgThycx:-2035704577) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee9573b5b56b769e2c9c756e06c2182ea89e5eff/util/net.go#L145)):*
might as well move this into the else above where you multiple by 2

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-:-KB8WgDdIx-sbsd4eOU1:302130660)*

**Comment by tamird** [comment]
That's the branch name!

Added benchmarks to the main commit message.

---

Review status: 21 of 27 files reviewed at latest revision, 5 unresolved discussions.

---

*[base/context.go, line 41 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-KB8VBn-75EX-mhsWVx7:-KB8YwdGuoR-FETkMi5N:2125924728) ([raw file](https://github.com/cockroachdb/cockroach/blob/45ef5c891b15a787d1cf79b54550823c98c91215/base/context.go#L41)):*
Good idea! Done.

---

*[util/net.go, line 145 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-KB8Y1PecamESAk_4XkL:-KB8Z2JaW-6sS8OrLFEe:695993016) ([raw file](https://github.com/cockroachdb/cockroach/blob/45ef5c891b15a787d1cf79b54550823c98c91215/util/net.go#L145)):*
This code is copied from the standard library, so I'd prefer to modify it as little as possible.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-:-KB8Yqfx7JgI8OsIRZeM:1653774050)*

**Comment by tschottdorf** [comment]
Reviewed 3 of 3 files at r10.
Review status: 14 of 25 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536)*

**Comment by tschottdorf** [comment]
Kind of unrelated GLOCKFILE updates in your cmux bump, but they're probably cool.
LGTM!

**Comment by tamird** [comment]
Gotta stay current brah.

OK, everything's been merged upstream and this is green. Merging.

---

Review status: 14 of 25 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4536#-:-KBGWeixTS-DxoZo7tAw:-292721400)*

**Pull request merged**
