### PR TITLE
sql/sem: fix interaction between framing and peers in window functions

### LINKED ISSUE #38901: sql: some aggregates as window functions erroneously return the same result for peers
I noticed an unexpected behavior of `array_agg`:
```
root@127.0.0.1:64602/defaultdb> create table ttt (a int primary key);
CREATE TABLE

Time: 2.571ms

root@127.0.0.1:64602/defaultdb> insert into ttt values (1), (2), (3);
INSERT 3

Time: 2.945ms

root@127.0.0.1:64602/defaultdb> select array_agg(a) over (rows 1 preceding) from ttt;
  array_agg  
+-----------+
  {1}        
  {1}        
  {1}        
(3 rows)

Time: 855µs
```
and confirmed that with Postgres:
```
yahoryuzefovich=# create table ttt (a int primary key);
CREATE TABLE
yahoryuzefovich=# insert into ttt values (1), (2), (3);
INSERT 0 3
yahoryuzefovich=# select array_agg(a) over (rows 1 preceding) from ttt;
 array_agg 
-----------
 {1}
 {1,2}
 {2,3}
(3 rows)
```
The problem here is that an ORDER BY clause is omitted, so all rows are considered "peers"; however, this concept should not apply in this case (also `concat_agg` and possibly other functions).

### LINKED ISSUE #42935: Wrong implementation of WINDOW ROWS clause
**Describe the problem**

It seems that the `WINDOW` function `ROWS` clause is implemented incorrectly. It seems to behave like `RANGE`

**To Reproduce**

Run this query:

```sql
select 
  a,
  b,
  count(*) over (order by b) as "no frame", 
  count(*) over (order by b range between unbounded preceding and current row) as "range frame", 
  count(*) over (order by b rows between unbounded preceding and current row) as "rows frame"
from (values (1, 1), (2, 1), (3, 2), (4, 2)) t (a, b)
order by a, b; 
```

The result is:

|a|b|no frame|range frame|rows frame|
|-|-|--------|-----------|----------|
|1|1|2|2|2|
|2|1|2|2|2|
|3|2|4|4|4|
|4|2|4|4|4|

(Observe the `rows frame` column)

In PostgreSQL and most other RDBMS, the result is:

```sql
|a|b|no frame|range frame|rows frame|
|-|-|--------|-----------|----------|
|1|1|2|2|1|
|2|1|2|2|2|
|3|2|4|4|3|
|4|2|4|4|4|
```

If possible, provide steps to reproduce the behavior:

**Environment:**
 - CockroachDB version: `CockroachDB CCL v19.2.1 (x86_64-unknown-linux-gnu, built 2019/11/18 23:23:55, go1.12.12)`
 - Server OS: Linux on Docker on Windows
 - Client app: JDBC

### PR DESCRIPTION
**Pull request by yuzefovich**
**rowexec: minor refactor of partitionPeerGrouper**

This commit removes allPeers peerGroupChecker and refactors
partitionPeerGrouper to support the case of omitted ORDER BY clause.

Release note: None

**sql/sem: fix interaction between framing and peers in window functions**

Previously, whenever we had a result of a window function already
computed for a peer of the row, we would return that result. However,
the concept of window framing takes precedence over the concept of peers
(i.e. if the window frame over which we computed the result for a peer
is different from the window frame of the current row, we need to
recompute the result). Now this is fixed by tracking the boundaries of
the window frame over which peerRes is computed and recomputing the
latter when needed.

There was also a bug in IsDefaultFrame where we forgot to check whether
the mode of framing is RANGE. This caused incorrect results in some
cases when ROWS or GROUPS modes of framing were used.

Fixes: #38901.
Fixes: #42935.

Release note (bug fix): CockroachDB previously was returning incorrect
results for some aggregate functions when used as window functions with
non-default window frame. Now this is fixed. Note that MIN, MAX, SUM,
AVG as well as "pure" window functions (i.e. non-aggregates) were not
affected.

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
LGTM, we should aggregate all these weird semantic oddities into a doc somewhere, they're pretty nasty.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39308#-:-LlXse2wCrBh6j6mDCh8:bbxzlk4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @justinj, and @yuzefovich)

___
*[pkg/sql/distsqlrun/windower.go, line 589 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39308#-LlXpj4P0bjQ0r4XqmUZ:-LlXpj4P0bjQ0r4XqmU_:b-vnn39a) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3e844f835d402a3215c8ddf58a4bea6c47734ca/pkg/sql/distsqlrun/windower.go#L589)):*
> ```Go
> 				// for "pure" window functions as well as for all modes of framing
> 				// except for ROWS.
> 				peerGrouper = allPeers{}
> ```

Haven't really looked at this code before—is there a reason this is a special case, and doesn't just have an empty ordering with the regular `partitionPeerGrouper`?
___
*[pkg/sql/logictest/testdata/logic_test/window, line 3342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39308#-LlXrrCL9tEqLJCl1aqA:-LlXrrCL9tEqLJCl1aqB:b-tibo4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3e844f835d402a3215c8ddf58a4bea6c47734ca/pkg/sql/logictest/testdata/logic_test/window#L3342)):*
> ```
> 4  10  2  0  4
> 
> # Regression test verifying that ROWS mode of framing takes precedence over the
> ```

Can you add a test including an example of this _not_ happening for non-aggregate functions?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39308)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @justinj)

___
*[pkg/sql/distsqlrun/windower.go, line 589 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39308#-LlXpj4P0bjQ0r4XqmUZ:-LlbtQRoBHwH_yGz7DB9:bx9vzl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3e844f835d402a3215c8ddf58a4bea6c47734ca/pkg/sql/distsqlrun/windower.go#L589)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Haven't really looked at this code before—is there a reason this is a special case, and doesn't just have an empty ordering with the regular `partitionPeerGrouper`?
</blockquote></details>

Thanks for pointing this out! Your intuition is correct - with an empty ordering, `partitionPeerGrouper` will behave exactly like `allPeers` but, at the moment, will be slower due to extra indirections and a copy. I will refactor this and remove `allPeers`.
___
*[pkg/sql/logictest/testdata/logic_test/window, line 3342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39308#-LlXrrCL9tEqLJCl1aqA:-Llbtu6JEixCz6mPnwyJ:b5paqzz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3e844f835d402a3215c8ddf58a4bea6c47734ca/pkg/sql/logictest/testdata/logic_test/window#L3342)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Can you add a test including an example of this _not_ happening for non-aggregate functions?
</blockquote></details>

Again, thanks for this suggestion! It actually made me realize that my "fix" was not a real fix. The real issue is that with aggregates we first check whether a current row is the first peer in its peer group, and if not, we return `agg.peerRes`. However, if the window frame is such that the first peer is not in the frame, that is an incorrect behavior. I will need to do more thinking about this and will postpone this PR for a little bit. These semantics are, indeed, very nasty :/

**Review by yuzefovich — COMMENTED** [review]
I guess when I get back to working on this, I should start writing the doc you mentioned.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39308#-:-Llbu_M59SX1lc5bi4rc:b1632gv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @justinj)

**Comment by yuzefovich** [comment]
@justinj @jordanlewis I pushed an updated fix. This code seems too fragile in general :/

**Comment by yuzefovich** [comment]
Friendly ping @justinj.

**Review by justinj — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39308#-:-LyAW2UuB_jWortkx4nu:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @justinj)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
