### PR TITLE
sql: use ImmutableTableDesc when resolving uncached immutable table

### PR DESCRIPTION
**Pull request by eriktrinh**

### CODE REVIEW

**Review by vivekmenezes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32801)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/schema_accessors.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32801#-LSpkmd08uD6LrXQEwvF:-LSpkmd08uD6LrXQEwvG:bucqwrk) ([raw file](https://github.com/cockroachdb/cockroach/blob/75bba104747571081b168d2cfde7ddbccd1b7d98/pkg/sql/schema_accessors.go#L57)):*
> ```Go
> 	// interface definitions below more intuitive.
> 	// It is an immutable descriptor read from the store.
> 	UncachedTableDescriptor = sqlbase.ImmutableTableDescriptor
> ```

How about we get rid of this type alias completely? Cached/Uncached is delivering no real meaning now.

**Review by eriktrinh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32801)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/schema_accessors.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32801#-LSpkmd08uD6LrXQEwvF:-LSptIzn5OWOAFh2q2HY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/75bba104747571081b168d2cfde7ddbccd1b7d98/pkg/sql/schema_accessors.go#L57)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

How about we get rid of this type alias completely? Cached/Uncached is delivering no real meaning now.
</blockquote></details>

Done.

**Review by vivekmenezes — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32801)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
