### PR TITLE
ttljob: add a regression test for TTL plan

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit uses recently added builtin function to verify that the plans for TTL queries are as expected for the recently fixed issue. It sets up a data-driven test that verifies that both the query itself and the query plan is as expected (for queries produced by the TTL query builders).

Informs: #118129.
Epic: None

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
@rafiss @mgartner curious about your thoughts on the second commit here - does this type of testing seem useful to merge? Possible downside of doing something like this is whenever the output of EXPLAIN changes, this would be yet another place to manually update.

**Comment by mgartner** [comment]
I think it's reasonable. We could replace the new TTL test with a new file in an `execbuilder` logic test that simulates the TTL query with the new builtin. That'll make updating less painful if `EXPLAIN` output changes. And add a `NOTE` or `WARNING` comment to the place where the TTL query is constructed to point out that the `execbuilder` test should be updated if the query is updated.

**Comment by yuzefovich** [comment]
I agree that it'd be very nice if we could make it an execbuilder test, but I think we'll lose test coverage if we do so. In particular, I'm afraid that we'll have a drift between the builtins you mention and the actual query texts produced by the builders. I refactored my approach to use the data-driven framework that should allow for simpler updating of the EXPLAIN output in case we change the format. I also extended the test to verify that the query text is as expected.

PTAL.

**Review by rafiss — APPROVED** [review]
nice, thank you for adding this! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118518#-:-Nw5HV-q30GCWQyRDL29:b7616g)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
