### PR TITLE
roachtest: remove `autoupgrade` test

### PR DESCRIPTION
**Pull request by renatolabs**
It performed a very basic upgrade test and no longer serves a purpose.

Epic: none

Release note: None

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]

**Comment by renatolabs** [comment]
TFTR!

bors r=srosenberg

**Comment by renatolabs** [comment]
bors cancel

**Comment by rickystewart** [comment]
bors ping

**Comment by rickystewart** [comment]
bors r=srosenberg

**Pull request merged**
