### PR TITLE
sql: add notice for interleaved tables

### LINKED ISSUE #56579: sql: add notice for interleaved tables
We should add a SQL notice when someone tried to create an interleaved table to signal our intention to remove.

### PR DESCRIPTION
**Pull request by postamar**
This patch adds a deprecation notice when the user attempts to create an
interleaved table by executing a CREATE TABLE ... INTERLEAVE IN PARENT
statement.

Fixes #56579.

Release note (sql change): Added deprecation notice to CREATE TABLE ...
INTERLEAVE IN PARENT statements.

### CODE REVIEW

**Comment by postamar** [comment]
Did I do this right? At this point I'm wondering if it's possible to test against notices. I saw it show up when I ran `cockroach demo` and I'm not sure whether that's good enough:
```
demo@127.0.0.1:26257/movr> CREATE TABLE public.barf ( id UUID NOT NULL, city VARCHAR NOT NULL, PRIMARY KEY (city, id) ) INTERLEAVE IN PARENT users (city, id);
NOTICE: interleaved tables are deprecated
CREATE TABLE

Time: 44ms total (execution 20ms / network 24ms)
```

**Comment by ajwerner** [comment]
I'd write a logic test. You can express `NOTICE` expectations in them with the `noticetrace` option. See https://github.com/cockroachdb/cockroach/blob/b03a7f8dad420f53bb9618cba835f21ff9a673ff/pkg/sql/logictest/testdata/logic_test/notice#L2. Probably this belongs in the `interleaved` logic test file.

**Review by jordanlewis — CHANGES_REQUESTED** [review]
Nice!

You should add tests to a "logic test".

Logic tests are data driven tests that live in files in `pkg/sql/logictest/testdata/logic_test`. Grep that directory for `noticetrace`, and you'll see a bunch of tests that assert notices.

You can run an individual logic test file like this:

`make testbaselogic FILES=yourfile`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56874#-:-MMSl5z21C5oP9uIX4Q5:b2mpqea)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar and @rafiss)

___
*[pkg/sql/create_table.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56874#-MMSkCBV7fGybbZTmtDi:-MMSkCBV7fGybbZTmtDj:bf9g94m) ([raw file](https://github.com/cockroachdb/cockroach/blob/b71d70adecfb179e9ec696b6fd754be9f9682f31/pkg/sql/create_table.go#L225)):*
> ```Go
> 		params.p.BufferClientNotice(
> 			params.ctx,
> 			pgnotice.Newf("interleaved tables are deprecated"),
> ```

I think we should say: 

```
interleaved tables will be deprecated in 21.1, and removed in 21.2
```

And, in a hint (see `errors.WithHintf`), say:

```
see https://github.com/cockroachdb/cockroach/issues/52009 for more details.
```

It's possible that we want to bikeshed this wording a bit (cc @vy-ton)

**Review by jordanlewis — COMMENTED** [review]
Oops, sorry for the double feedback from myself and Andrew, saying the same thing in both messages.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56874#-:-MMSlRuY06SFL_J8dCOi:b2au271)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar and @rafiss)

**Review by jordanlewis — COMMENTED** [review]
There are a few more places we need to add this notice to, as well.

- ALTER PRIMARY KEY, which can make a table interleaved
- CREATE INDEX, which can make an index interleaved

Example:

```
alter table a alter primary key using columns (a, b) interleave in parent(a)
create index foo on b(a) interleave in parent a(a)
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56874#-:-MMSoRVd1BoCBd-7AYzW:b-grbxyq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar and @rafiss)

**Review by postamar — COMMENTED** [review]
(edit: sorry still getting familiar with Reviewable)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56874)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @rafiss, and @vy-ton)

___
*[pkg/sql/create_table.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56874#-MMSkCBV7fGybbZTmtDi:-MMXbMHl-zUS7432hPf-:b-z5fwg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b71d70adecfb179e9ec696b6fd754be9f9682f31/pkg/sql/create_table.go#L225)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think we should say: 

```
interleaved tables will be deprecated in 21.1, and removed in 21.2
```

And, in a hint (see `errors.WithHintf`), say:

```
see https://github.com/cockroachdb/cockroach/issues/52009 for more details.
```

It's possible that we want to bikeshed this wording a bit (cc @vy-ton)
</blockquote></details>

I took the liberty of rewording it to "interleaved tables and indexes will..." after discussion with @ajwerner

**Review by vy-ton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56874)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rafiss)

___
*[pkg/sql/create_table.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56874#-MMSkCBV7fGybbZTmtDi:-MMXtuZu9vfzrPnGW6vb:b57zev5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b71d70adecfb179e9ec696b6fd754be9f9682f31/pkg/sql/create_table.go#L225)):*
> will be deprecated in 21.1

Are we backporting the notice to 20.2? If so, I would prefer `interleaved tables and indexes are deprecated in 20.2 and will be removed in 21.2`

**Comment by postamar** [comment]
Looks like I forgot some test cases in `pkg/cli`, that was careless of me. For some reason I was unable to run those locally with `make test PKG=./pkg/cli`, I keep getting seemingly errors, is this expected?

**Comment by ajwerner** [comment]
What are the errors? One trick is to use the builder docker container: `./build/builder.sh make test ...`. That thing is handy.

**Review by postamar — COMMENTED** [review]
They were errors which I wasn't able to reproduce after trying the docker build, the conclusion I'm taking from this is I need to better understand the build process, pronto. In any case I was able to run the tests locally today.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56874#-:-MM_vkzz9v1UMFsacHMF:b24wsiy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rafiss)

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56874)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @postamar, and @rafiss)

___
*[pkg/sql/alter_primary_key.go, line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56874#-MMa8PRuAzJLr8LBIYfU:-MMa8PRuAzJLr8LBIYfV:bun3p87) ([raw file](https://github.com/cockroachdb/cockroach/blob/93c6957781b2055abefda2c7074ca485aec05f8f/pkg/sql/alter_primary_key.go#L38)):*
> ```Go
> 			errors.WithHint(
> 				pgnotice.Newf("interleaved tables and indexes are deprecated in 20.2 and will be removed in 21.2"),
> 				"See https://github.com/cockroachdb/cockroach/issues/52009 for more details.",
> ```

Can you please use the facility `unimplemented.MakeURL()` 
(you may want to move that function from package "unimplemented" to something with a more generic name)

As we want to have proper telemetry on URL usage
___
*[pkg/sql/create_index.go, line 400 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56874#-MMa8cMW8CHVBmXbvhhI:-MMa8cMXByPn7m-kEzzY:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/93c6957781b2055abefda2c7074ca485aec05f8f/pkg/sql/create_index.go#L400)):*
> ```Go
> 			errors.WithHint(
> 				pgnotice.Newf("interleaved tables and indexes are deprecated in 20.2 and will be removed in 21.2"),
> 				"See https://github.com/cockroachdb/cockroach/issues/52009 for more details.",
> ```

ditto
___
*[pkg/sql/create_table.go, line 227 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56874#-MMa8dPeDIMMh_E2kPyu:-MMa8dPeDIMMh_E2kPyv:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/93c6957781b2055abefda2c7074ca485aec05f8f/pkg/sql/create_table.go#L227)):*
> ```Go
> 			errors.WithHint(
> 				pgnotice.Newf("interleaved tables and indexes are deprecated in 20.2 and will be removed in 21.2"),
> 				"See https://github.com/cockroachdb/cockroach/issues/52009 for more details.",
> ```

ditto

**Review by postamar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56874)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @knz, @postamar, and @rafiss)

___
*[pkg/sql/alter_primary_key.go, line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56874#-MMa8PRuAzJLr8LBIYfU:-MMaWHYL-A8uKMsBf-0p:b-uolf51) ([raw file](https://github.com/cockroachdb/cockroach/blob/93c6957781b2055abefda2c7074ca485aec05f8f/pkg/sql/alter_primary_key.go#L38)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you please use the facility `unimplemented.MakeURL()` 
(you may want to move that function from package "unimplemented" to something with a more generic name)

As we want to have proper telemetry on URL usage
</blockquote></details>

I looked into this and found out about `errors.WithIssueLink` which seems the way to go. Anyway I noticed that `MakeURL` puts the version prefix in the url string and my understanding is this will break CI tests when building a real version: assertions on `See: https://go.crdb.dev/issue-v/52009/dev` (in pkg/sql) or `See: https://go.crdb.dev/issue-v/52009/v999.0` (in pkg/cli) will fail. 
Perhaps for the SQL logic tests I could expand `statement` to assert on `notice` instead of just `ok` or `error`,  to do assertions on notices in a similar way to `statement error` which seems to cope well in this case (see https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/temp_table#L4 ) but I'm not sure how to do it right for CLI tests. I'm looking into it.

**Review by knz — COMMENTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56874)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @postamar, and @rafiss)

___
*[pkg/sql/alter_primary_key.go, line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56874#-MMa8PRuAzJLr8LBIYfU:-MMaguFk9TUrlCMP7Y4m:b3xri8g) ([raw file](https://github.com/cockroachdb/cockroach/blob/93c6957781b2055abefda2c7074ca485aec05f8f/pkg/sql/alter_primary_key.go#L38)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I looked into this and found out about `errors.WithIssueLink` which seems the way to go. Anyway I noticed that `MakeURL` puts the version prefix in the url string and my understanding is this will break CI tests when building a real version: assertions on `See: https://go.crdb.dev/issue-v/52009/dev` (in pkg/sql) or `See: https://go.crdb.dev/issue-v/52009/v999.0` (in pkg/cli) will fail. 
Perhaps for the SQL logic tests I could expand `statement` to assert on `notice` instead of just `ok` or `error`,  to do assertions on notices in a similar way to `statement error` which seems to cope well in this case (see https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/temp_table#L4 ) but I'm not sure how to do it right for CLI tests. I'm looking into it.

</blockquote></details>

So yes you found that our automated logic tests are not able to deal with this properly. This is a limitation in the test framework, not an indication that you should do the implementation differently (my idiom for this is "don't let the tail wag the dog")

These special URLs generated by `MakeURL` achieve multiple things:

- they tell our product team when people click the links.
- they tell our product team which version the user is encountering the link in.
- they enable us to redirect the URLs to something else than github if/when we migrate from github issues to something else.

Overall we're moving away from raw github URLs. That's what I'm pointing out here.

**Review by postamar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56874)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @knz, @postamar, and @rafiss)

___
*[pkg/sql/alter_primary_key.go, line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56874#-MMa8PRuAzJLr8LBIYfU:-MMbgxCxD6QG47dHXx9K:b-dyepdl) ([raw file](https://github.com/cockroachdb/cockroach/blob/93c6957781b2055abefda2c7074ca485aec05f8f/pkg/sql/alter_primary_key.go#L38)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

So yes you found that our automated logic tests are not able to deal with this properly. This is a limitation in the test framework, not an indication that you should do the implementation differently (my idiom for this is "don't let the tail wag the dog")

These special URLs generated by `MakeURL` achieve multiple things:

- they tell our product team when people click the links.
- they tell our product team which version the user is encountering the link in.
- they enable us to redirect the URLs to something else than github if/when we migrate from github issues to something else.

Overall we're moving away from raw github URLs. That's what I'm pointing out here.
</blockquote></details>

Thanks for confirming and for explaining. 

I published a new revision which extends the test framework in a way I'm hoping you'll all find reasonable and not too out of scope. This does place a higher burden on the reviewers though. FWIW I cursorily checked the new feature's correctness by falsifying the expected notice patterns and making sure the assertions correspondingly failed. 

I found a workaround for the `pkg/cli` tests, checking for the notice there is redundant anyway.

**Review by knz — APPROVED** [review]
:lgtm: very nice :100: 

> Reviewed 18 of 18 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56874#-:-MMpTH9n7-zy6jrgGtqv:b28ceit)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @postamar, and @rafiss)

**Review by vy-ton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56874)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @postamar, and @rafiss)

___
*[pkg/sql/alter_primary_key.go, line 38 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56874#-MMpq9jn5atNB5Vg3a4A:-MMpq9jn5atNB5Vg3a4B:bgudbt1) ([raw file](https://github.com/cockroachdb/cockroach/blob/93a32aedd3976dda88cf26c6bd422255d3d6c024/pkg/sql/alter_primary_key.go#L38)):*
> ```Go
> 			ctx,
> 			errors.WithIssueLink(
> 				pgnotice.Newf("interleaved tables and indexes are deprecated in 20.2 and will be removed in 21.2"),
> ```

@jordanlewis @lucy-zhang Are we ok with this deprecation being backported to 20.2?

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56874)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @jordanlewis, @postamar, and @rafiss)

___
*[pkg/sql/alter_primary_key.go, line 38 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56874#-MMpq9jn5atNB5Vg3a4A:-MMpsbQq6pG_RymZASz_:b-dy9gri) ([raw file](https://github.com/cockroachdb/cockroach/blob/93a32aedd3976dda88cf26c6bd422255d3d6c024/pkg/sql/alter_primary_key.go#L38)):*
<details><summary><i>Previously, vy-ton (Vy Ton) wrote…</i></summary><blockquote>

@jordanlewis @lucy-zhang Are we ok with this deprecation being backported to 20.2?
</blockquote></details>

We're documenting the feature as deprecated in 20.2, right? I think that's fine.

**Review by vy-ton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56874)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @jordanlewis, @postamar, and @rafiss)

___
*[pkg/sql/alter_primary_key.go, line 38 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56874#-MMpq9jn5atNB5Vg3a4A:-MMpuGwj6U-hoPq2pann:b-x7gms8) ([raw file](https://github.com/cockroachdb/cockroach/blob/93a32aedd3976dda88cf26c6bd422255d3d6c024/pkg/sql/alter_primary_key.go#L38)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

We're documenting the feature as deprecated in 20.2, right? I think that's fine.
</blockquote></details>

Yes I filed https://github.com/cockroachdb/docs/issues/8891to be done after this notice is added

**Review by jordanlewis — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56874#-:-MMqUk24BhuWeFALPmNL:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ajwerner, @jordanlewis, @postamar, and @rafiss)

**Pull request merged**
