### PR TITLE
sql,server: remove crdb_internal.has_role_option

### PR DESCRIPTION
**Pull request by rafiss**
None of the endpoints require role options now, and in general we want to move away from using role options in favor of system privileges. As such, we should just remove this code.

Epic: None
Release note: None

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114645)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @miretskiy, @msbutler, and @rafiss)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114645#-NjhUBSs4wndZKLqWXsM):*
shouldn't this have a release note? In case users are using the built-in they need to know is no longer available and what to use instead

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114645)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @maryliag, @miretskiy, and @msbutler)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114645#-NjhUBSs4wndZKLqWXsM):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

shouldn't this have a release note? In case users are using the built-in they need to know is no longer available and what to use instead
</blockquote></details>

crdb_internal functions are meant for internal usage only and don't have API stability guarantees

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114645)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @miretskiy, @msbutler, and @rafiss)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114645#-NjhUBSs4wndZKLqWXsM):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

crdb_internal functions are meant for internal usage only and don't have API stability guarantees
</blockquote></details>

But we're showing now on our docs and needs to be removed: https://www.cockroachlabs.com/docs/v23.1/functions-and-operators

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114645)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @maryliag, @miretskiy, and @msbutler)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114645#-NjhUBSs4wndZKLqWXsM):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

But we're showing now on our docs and needs to be removed: https://www.cockroachlabs.com/docs/v23.1/functions-and-operators


</blockquote></details>

Those are 23.1 docs - but note that in 23.2 docs all crdb_internal functions do not appear any more: https://www.cockroachlabs.com/docs/v23.2/functions-and-operators

(and this PR i'm making will not be released until 24.1)

**Review by maryliag — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114645)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian, @miretskiy, @msbutler, and @rafiss)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114645#-NjhUBSs4wndZKLqWXsM):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

Those are 23.1 docs - but note that in 23.2 docs all crdb_internal functions do not appear any more: https://www.cockroachlabs.com/docs/v23.2/functions-and-operators

(and this PR i'm making will not be released until 24.1)
</blockquote></details>

Ah okay! Thank you for clarifying! 

:lgtm:

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
