### PR TITLE
sql: detect invalid * in functions

### LINKED ISSUE #7727: sql: * in function other than COUNT causes server to panic
```
SELECT COUN(*) FROM foo
```

(for any table foo)

causes
```
panic: star qnames should really not be reaching this point!

goroutine 1218 [running]:
panic(0x15a1fc0, 0xc8204a7d80)
        /mnt/kena/go1.6.2/src/runtime/panic.go:481 +0x3e6
github.com/cockroachdb/cockroach/sql.multiSourceInfo.findColumn(0xc8200d4220, 0x1, 0x1, 0xc82076a280, 0x0, 0x1, 0x0, 0x0)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/sql/data_source.go:395 +0x119
github.com/cockroachdb/cockroach/sql.(*qnameVisitor).VisitPre(0xc82024fef8, 0x7fddbd355688, 0xc82076a280, 0x7fddbd355688, 0x0, 0x0)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/sql/select_qvalue.go:147 +0x18f
github.com/cockroachdb/cockroach/sql/parser.WalkExpr(0x7fddbd28af60, 0xc82024fef8, 0x7fddbd355688, 0xc82076a280, 0x0, 0x0, 0x1)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:415 +0x56
github.com/cockroachdb/cockroach/sql/parser.(*FuncExpr).Walk(0xc8203a6400, 0x7fddbd28af60, 0xc82024fef8, 0x0, 0x0)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:204 +0xe6
github.com/cockroachdb/cockroach/sql/parser.WalkExpr(0x7fddbd28af60, 0xc82024fef8, 0x7fddbd28a5a0, 0xc8203a6400, 0x7fddbd28a5a0, 0xc8203a6400, 0x0)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:418 +0x98
github.com/cockroachdb/cockroach/sql.resolveQNames(0x7fddbd28a5a0, 0xc8203a6400, 0xc8200d4220, 0x1, 0x1, 0xc82075e3c0, 0xc82024fef8, 0x0, 0x0, 0x0, ...)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/sql/select_qvalue.go:219 +0x17d
github.com/cockroachdb/cockroach/sql.(*planner).analyzeExpr(0xc82024f890, 0x7fddbd28a5a0, 0xc8203a6400, 0xc8200d4220, 0x1, 0x1, 0xc82075e3c0, 0x0, 0x0, 0x0, ...)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/sql/analyze.go:1633 +0x15d
github.com/cockroachdb/cockroach/sql.(*selectNode).addRender(0xc8201a0000, 0x7fddbd28a5a0, 0xc8203a6400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/sql/select.go:541 +0x57c
github.com/cockroachdb/cockroach/sql.(*selectNode).initTargets(0xc8201a0000, 0xc8203b8340, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
```

### PR DESCRIPTION
**Pull request by madelynnblue**
Fixes #7727

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7751)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/testdata/builtin_function, line 1070 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7751#-KMQpZqQSmYpeCe4ooP5:-KMQpZqQSmYpeCe4ooP6:-1521497851) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6dca8048a577ce91923fdf54e2bc03e45ddddc/sql/testdata/builtin_function#L1070)):*
> ```
> # Don't panic during incorrect use of * (#7727)
> query error pq: unexpected star: COS\(\*\)
> SELECT COS(*) FROM system.namespace
> ```

can we give a better error? postgres gives:

```
test=# SELECT random(*) FROM kv;
ERROR:  random(*) specified, but random is not an aggregate function
LINE 1: SELECT random(*) FROM kv;
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7751)*

**Comment by tamird** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/testdata/builtin_function, line 1070 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7751#-KMQpZqQSmYpeCe4ooP5:-KMQpuYae8njnGD91dQl:-349620629) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6dca8048a577ce91923fdf54e2bc03e45ddddc/sql/testdata/builtin_function#L1070)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can we give a better error? postgres gives:
> 
> ```
> test=# SELECT random(*) FROM kv;
> ERROR:  random(*) specified, but random is not an aggregate function
> LINE 1: SELECT random(*) FROM kv;
> ```
</details>
Other functions (that are aggregates but aren't COUNT) yield:
```
test=# SELECT sum(*) FROM kv;
ERROR:  function sum() does not exist
LINE 1: SELECT sum(*) FROM kv;
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7751)*

**Comment by mjibson** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/testdata/builtin_function, line 1070 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7751#-KMQpZqQSmYpeCe4ooP5:-KMQyxh4BggCaYuz28cH:-881606153) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6dca8048a577ce91923fdf54e2bc03e45ddddc/sql/testdata/builtin_function#L1070)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Other functions (that are aggregates but aren't COUNT) yield:
> ```
> test=# SELECT sum(*) FROM kv;
> ERROR:  function sum() does not exist
> LINE 1: SELECT sum(*) FROM kv;
>                ^
> HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
> ```
</details>
I disagree that the error I have is worse than the Postgres errors. The "X(*) specified, but X is not an aggregate function" error implies that * is valid for aggregate functions. It isn't: it's only valid for COUNT, which happens to be an aggregate function. The second error "X() does not exist" is just weird since X with 1 argument does exist, just not when that argument type is *.

Overall it seems to me that "unexpected star" is specific, clear, and fixing the query is obvious.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7751)*

**Comment by knz** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/select_qvalue.go, line 159 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7751#-KMR1_vkrQh-xn9X3tyo:-KMR1_vkrQh-xn9X3typ:-269886706) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6dca8048a577ce91923fdf54e2bc03e45ddddc/sql/select_qvalue.go#L159)):*
> ```Go
> 		// columns. A * is invalid elsewhere.
> 		isCount := len(t.Name.Indirect) == 0 && strings.EqualFold(string(t.Name.Base), "count")
> 		for i, e := range t.Exprs {
> ```

You do not need a loop here. If there is a star, the function necessarily takes just 1 argument (see the grammar for func_application in sql.y).

---

*[sql/testdata/builtin_function, line 1070 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7751#-KMQpZqQSmYpeCe4ooP5:-KMR1oEisIzvQCkopcjX:-1212047798) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6dca8048a577ce91923fdf54e2bc03e45ddddc/sql/testdata/builtin_function#L1070)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> I disagree that the error I have is worse than the Postgres errors. The "X(*) specified, but X is not an aggregate function" error implies that * is valid for aggregate functions. It isn't: it's only valid for COUNT, which happens to be an aggregate function. The second error "X() does not exist" is just weird since X with 1 argument does exist, just not when that argument type is *.
> 
> Overall it seems to me that "unexpected star" is specific, clear, and fixing the query is obvious.
</details>
I'd go for "cannot use '*' with <function name>" instead. People may not know the SQL star under the name "star".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7751)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/testdata/builtin_function, line 1070 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7751#-KMQpZqQSmYpeCe4ooP5:-KMR1yCshM5m4tSINXej:55281011) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6dca8048a577ce91923fdf54e2bc03e45ddddc/sql/testdata/builtin_function#L1070)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> I'd go for "cannot use '*' with <function name>" instead. People may not know the SQL star under the name "star".
</details>
`"cannot use '*' with <function name>"` sorry

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7751)*

**Comment by mjibson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/select_qvalue.go, line 159 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7751#-KMR1_vkrQh-xn9X3tyo:-KMSYSqYLbTTEU-Tmsu4:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6dca8048a577ce91923fdf54e2bc03e45ddddc/sql/select_qvalue.go#L159)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> You do not need a loop here. If there is a star, the function necessarily takes just 1 argument (see the grammar for func_application in sql.y).
</details>
Done.

---

*[sql/testdata/builtin_function, line 1070 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7751#-KMQpZqQSmYpeCe4ooP5:-KMSZ40SKMHi9fI9tR9L:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d6dca8048a577ce91923fdf54e2bc03e45ddddc/sql/testdata/builtin_function#L1070)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> `"cannot use '*' with <function name>"` sorry
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7751)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7751#-:-KMT8VWe0Lj3zXJDTDUr:1417088721)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7751)*

**Pull request merged**
