### PR TITLE
sql: de-pErr-ify SelectNode and a few friends

### PR DESCRIPTION
**Pull request by andreimatei**
the change is mechanical

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6512)

### CODE REVIEW

**Comment by andreimatei** [comment]
@knz you can ignore the first commit; it's part of another PR

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6512#-:-KGxpY5XT4yJ-arKkdlS:-1800436592)*

**Comment by knz** [comment]
Ok this is straightforward indeed, and thanks for tackling this before I start working on splitting SelectClause in prepare/execute phases!

A general question though: any reason to keep planNode.Start()  returning roachpb.Error?

---

Reviewed 15 of 15 files at r2.
Review status: 15 of 19 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6512#-:-KGxrIOjFTLE0ZTMrJPf:162292989)*

**Comment by andreimatei** [comment]
no reason, everything in that interface will move to `error`. I just haven't done it yet because there's still a bunch of nodes that use `pErr`. Tomorrow probably.

---

Review status: 15 of 19 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6512#-:-KGxtoGLEtCHDnh84s9N:424884155)*

**Comment by knz** [comment]
LGTM then

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 15 of 19 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/select.go, line 562 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6512#-KH-rVGjI2qaPL4dzP1f:-KH-rVGkLjfPBSBbI5gj:1432079104) ([raw file](https://github.com/cockroachdb/cockroach/blob/a101a271205d949e15fed4a68b06ec8bbf4b1a60/sql/select.go#L562)):*
leftover debug stuf?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6512#-:-KH-r_BiVq8GgMD95hOh:1417088721)*

**Comment by andreimatei** [comment]
Review status: 0 of 19 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/select.go, line 562 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6512#-KH-rVGjI2qaPL4dzP1f:-KH0W2ywLdCtlH_Z1bRC:829676839) ([raw file](https://github.com/cockroachdb/cockroach/blob/a101a271205d949e15fed4a68b06ec8bbf4b1a60/sql/select.go#L562)):*
oops, thanks
I do usually grep before merging, fwiw

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6512)*

**Pull request merged**
