### PR TITLE
sql: Clean up the test case literals for TestQueryCounts

### PR DESCRIPTION
**Pull request by a-robinson**
As suggested in #12480

@tamird @arjunravinarayan 

I know the first test case could just be left completely empty, but I like the consistency of always including the query field.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12484)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM. Consider adding a comment on the `ddlCount` explaining that it is never set in the test case slice.

**Comment by arjunravinarayan** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12484#-:-KZNpuKod1nbRnEBEjR0:bnfp4nl)*

**Comment by a-robinson** [comment]
> LGTM. Consider adding a comment on the ddlCount explaining that it is never set in the test case slice.

Huh? You mean txnRollbackCount?

**Comment by tamird** [comment]
No? https://github.com/cockroachdb/cockroach/pull/12480/files#diff-66e66f4543c299ad74b06231fa22ef2eR75

**Comment by tamird** [comment]
If you were feeling particularly ambitious, you could have an "accumulator" type which embeds the testcase type, which would avoid having never-populated fields in the test case slice.

**Comment by arjunravinarayan** [comment]
But `ddlCount` is set in 4 different statements (Create Table, Create Database, Update Table, and Drop Table).

**Comment by a-robinson** [comment]
^What @arjunravinarayan said.

**Comment by tamird** [comment]
Oh, I see what's happening. How about removing the first "testcase" and the special case around it and writing `accum := queryCount{ddl: ...}`?

**Comment by a-robinson** [comment]
Works for me, although I've kept the first test case around as a sanity check that the metrics (other than ddlCount) are starting at 0.

**Comment by a-robinson** [comment]
@tamird has helpfully pointed out offline that cases with an empty query don't get run, so I've just gotten rid of it (and that unnecessary condition)

**Comment by tamird** [comment]
LGTM! Thanks for the follow-up.

**Pull request merged**
