### PR TITLE
ccl,kv: delete unused imports in protos

### PR DESCRIPTION
**Pull request by rickystewart**
Release note: None

### CODE REVIEW

**Review by irfansharif — APPROVED** [review]

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74170#-:-MrUbkfo4PaJ_ObNaXPc:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Comment by tbg** [comment]
Nice, how did you lint those out? Is that something we want to automate at some point?

**Comment by irfansharif** [comment]
Bazel warnings I assume (never noticed until now):
```
$ dev build short --hoist-generated-code
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
INFO: Build options --define, --run_under, --test_env, and 3 more have changed, discarding analysis cache.
INFO: Analyzed target //pkg/cmd/cockroach-short:cockroach-short (283 packages loaded, 20530 targets configured).
INFO: Found 1 target...
INFO: From Generating Descriptor Set proto_library //pkg/ccl/streamingccl/streampb:streampb_proto:
ccl/streamingccl/streampb/stream.proto:16:1: warning: Import roachpb/api.proto but not used.
ccl/streamingccl/streampb/stream.proto:15:1: warning: Import jobs/jobspb/jobs.proto but not used.
```

**Comment by rickystewart** [comment]
Yeah, the Bazel build warns you about the unused imports.

bors r=ajwerner,irfansharif

**Pull request merged**
