### PR TITLE
sql: Add information_schema routines and parameters tables

### LINKED ISSUE #24759: sql: support vtables information_schema.{routines,parameters}
requested by @awoods187 , Navicat needs this

```sql
FROM information_schema.routines AS r 
LEFT JOIN information_schema.parameters AS p ON r.specific_name = p.specific_name GROUP BY p.specific_name, r.routine_schema, r.routine_name 
ORDER BY r.routine_schema
```

The vtables should be visible to clients (and contain no data initially) even though #17511 is not solved.

### PR DESCRIPTION
**Pull request by emsal0**
Release note (sql change): Added placeholder information_schema.routines and
information_schema.parameters for compatibility with Navicat, PGAdmin
and other clients that require them.

closes #24759

### CODE REVIEW

**Comment by emsal1863** [comment]
Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[pkg/sql/logictest/testdata/logic_test/information_schema, line 1703 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26327#-LDwiPzs3y256ii0mTAZ:-LDwiPzs3y256ii0mTA_:bp37clo) ([raw file](https://github.com/cockroachdb/cockroach/blob/856aa456bd39523ad7477a55eb0acdbec59c3144/pkg/sql/logictest/testdata/logic_test/information_schema#L1703)):*
> ```
> result_cast_dtd_identifier           STRING                    true  NULL     {}
> 
> query TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT colnames
> ```

This is kinda humongous (80 columns) so I don't really know if we should keep this in

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26327)*

**Comment by knz** [comment]
Very nice! Thank you!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/information_schema.go, line 475 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26327#-LE8lC107IFhBE0zxPv0:-LE8lC107IFhBE0zxPv1:b-6ocoxe) ([raw file](https://github.com/cockroachdb/cockroach/blob/856aa456bd39523ad7477a55eb0acdbec59c3144/pkg/sql/information_schema.go#L475)):*
> ```Go
> var informationSchemaParametersTable = virtualSchemaTable{
> 	schema: `
> CREATE TABLE information_schema.parameters (
> ```

for consistency with the other definitions please capitalize the column names.

---

*[pkg/sql/logictest/testdata/logic_test/information_schema, line 1703 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26327#-LDwiPzs3y256ii0mTAZ:-LE8lLBE9kDlRsIiegxh:b-m2fxpr) ([raw file](https://github.com/cockroachdb/cockroach/blob/856aa456bd39523ad7477a55eb0acdbec59c3144/pkg/sql/logictest/testdata/logic_test/information_schema#L1703)):*
<details><summary><i>Previously, emsal1863 (Emmanuel Sales) wrote…</i></summary><blockquote>

This is kinda humongous (80 columns) so I don't really know if we should keep this in
</blockquote></details>

I don't mind it *but* it is currently incorrect: the `int` columns should use `I` in the string.

---

*[pkg/sql/logictest/testdata/logic_test/information_schema, line 1746 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26327#-LE8lWhE0wmcSWRu6BQ3:-LE8lWhE0wmcSWRu6BQ4:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/856aa456bd39523ad7477a55eb0acdbec59c3144/pkg/sql/logictest/testdata/logic_test/information_schema#L1746)):*
> ```
> parameter_default         STRING  true  NULL     {}
> 
> query TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT colnames
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26327#-:-LE8lbyc8tdIKjA1HTIz:b-cbyh0n)*

**Comment by emsal1863** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/information_schema.go, line 475 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26327#-LE8lC107IFhBE0zxPv0:-LE9vPh1DTh2MF8UQ5MJ:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/856aa456bd39523ad7477a55eb0acdbec59c3144/pkg/sql/information_schema.go#L475)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

for consistency with the other definitions please capitalize the column names.
</blockquote></details>

Done

---

*[pkg/sql/logictest/testdata/logic_test/information_schema, line 1703 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26327#-LDwiPzs3y256ii0mTAZ:-LE9vRvY24NXGW-jQ7LR:bckw2ka) ([raw file](https://github.com/cockroachdb/cockroach/blob/856aa456bd39523ad7477a55eb0acdbec59c3144/pkg/sql/logictest/testdata/logic_test/information_schema#L1703)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't mind it *but* it is currently incorrect: the `int` columns should use `I` in the string.
</blockquote></details>

Is there a way to autogen this?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26327)*

**Comment by emsal1863** [comment]
@knz good to go?

**Comment by knz** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/information_schema, line 1703 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26327#-LDwiPzs3y256ii0mTAZ:-LEAfycs7MJu4f4qMeJ7:b-l6u4xm) ([raw file](https://github.com/cockroachdb/cockroach/blob/856aa456bd39523ad7477a55eb0acdbec59c3144/pkg/sql/logictest/testdata/logic_test/information_schema#L1703)):*
<details><summary><i>Previously, emsal1863 (Emmanuel Sales) wrote…</i></summary><blockquote>

I ended up finishing this by hand (Done) but if there is a way to autogen this it'd be good to know for future reference
</blockquote></details>

There is no mechanism to auto-generate yet and this would be a good Friday project to add to the logic test machinery.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26327#-:-LEAg4LQADJjfSWBsRS9:bnfp4nl)*

**Pull request merged**
