### PR TITLE
server, tenant: gate process debugging behind capability

### LINKED ISSUE #97946: server: gate pprof and vmodule endpoints behind tenant capabilities
Epic: CRDB-12100

Jira issue: CRDB-24979

### PR DESCRIPTION
**Pull request by dhartunian**
Previously, all tenant servers were started with a debug server
that granted process-manipulating power via pprof and vmodule HTTP
endpoints.

This implementation is fine when servers serve just 1 tenant in
a given process; that tenant then legitimately has access to all
process-level control. However, it becomes a problem in shared-process
multitenancy, when the same process is shared by multiple tenants. In
that case, it is undesirable for 1 tenant to have access to & control
process properties, as it could influence the well-functioning of
other tenants or potentially leak data across tenant boundaries.

This commit gates access to the debug server behind a capability
**only with shared process multitenancy**. Tenant servers running
within their own process will contain a debug server with no
capability gating since they own their process.

The gating is implemented via a tenant authorizer function backed
by the capability store that is injected into the debug server
upon startup. Shared process tenants are provided this authorizer,
while separate process tenants and the system tenant use the no-op
authorizer.

Epic: CRDB-12100
Resolves: https://github.com/cockroachdb/cockroach/issues/97946

Release note: None

### CODE REVIEW

**Review by abarganier — APPROVED** [review]
:lgtm: modulo some tiny nits. Nice work on this - easy to reason about!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-:-NUXDRmjD1sfQzVtp7tE:bbk4uz2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian, @renatolabs, and @smg260)

___
*[`-- commits` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NUX0az7-JZSub8j_g32):*
nit: is this the right issue ref?
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go` line 399 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NUX71hMDk6TJM5iywuv:-NUX71hMDk6TJM5iywuw:br1olwf) ([raw file](https://github.com/cockroachdb/cockroach/blob/21c30cd0e431c7195ad87f889a78b045920851e3/pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go#L399)):*
> ```Go
> 	}
> 	errFn := func() error {
> 		return errors.New("client tenant does not have capability to debug the process")
> ```

nit: Maybe I'm missing something, but why do we need an error function? 
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go` line 404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NUX6q001IFZf4W2oMG-:-NUX6q001IFZf4W2oMG0:bm1wvsi) ([raw file](https://github.com/cockroachdb/cockroach/blob/21c30cd0e431c7195ad87f889a78b045920851e3/pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go#L404)):*
> ```Go
> 	switch mode {
> 	case authorizerModeOn:
> 		break // fallthrough to the next check.
> ```

nit: `fallthrough` is a bit of an overloaded term here when used in a switch statement. Can we re-word this a bit?

**Review by knz — COMMENTED** [review]
Generally OK with the architecture proposed. I have a suggestion for a simplification. Also a few comments about the wording.

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-:-NVZj4hy07DPXhmNq-PA:bslcm77)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, @renatolabs, and @smg260)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NVZh6Fq8OKzeNm4VmDd):*
"all tenant processes" -> "all tenant servers"
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NVZhC_e55bbP97V05tH):*
Add:
"""
This implementation is fine when servers serve just 1 tenant in a given process; that tenant then legitimately has access to all process-level control.
However, it becomes a problem in shared-process multitenancy, when the same process is shared by multiple tenants. In that case, it is undesirable for 1 tenant to have access to & control process properties, as it could influence the well-functioning of other tenants or potentially leak data across tenant boundaries.
"""
___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NVZhZoo6VGfJdBPDxnD):*
"This commit gates access _to the debug server_ behind"...
___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NVZhbng6HU973utZEUv):*
"only with shared-process multitenancy"
___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NVZhi0M3OFjV29fneC9):*
"Tenant servers running within..."
___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NVZhkCN10KGu2Oifmr5):*
remove "on the in-process tenant".
___
*[`-- commits` line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NVZhnc94aUwLIi34E5l):*
What is "parent process" in this sentence? IMHO this is not a thing. Did you mean "HTTP server for the system tenant"?
___
*[`-- commits` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NUX0az7-JZSub8j_g32):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: is this the right issue ref?
</blockquote></details>

yep I think it's not the right issue.
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go` line 399 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NUX71hMDk6TJM5iywuv:-NVZi1uu3bYCfl4COJ_t:bf9xhy9) ([raw file](https://github.com/cockroachdb/cockroach/blob/21c30cd0e431c7195ad87f889a78b045920851e3/pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go#L399)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: Maybe I'm missing something, but why do we need an error function? 
</blockquote></details>

because it's used in 2 places below.
___
*[`pkg/server/config.go` line 533 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NVZiAP412hFsTL-dKqi:-NVZiAP412hFsTL-dKqj:b-yif6b6) ([raw file](https://github.com/cockroachdb/cockroach/blob/21c30cd0e431c7195ad87f889a78b045920851e3/pkg/server/config.go#L533)):*
> ```Go
> 
> 	// SystemDebugServer is set if the sql configuration will be running in a shared
> 	// process model, allowing for parent process debugging if granted by a tenant
> ```

"parent process" is not a thing.
___
*[`pkg/server/config.go` line 534 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NVZi8fn4LBgS-BPGXEE:-NVZi8fo4230YrxV0bnD:b-97p7pq) ([raw file](https://github.com/cockroachdb/cockroach/blob/21c30cd0e431c7195ad87f889a78b045920851e3/pkg/server/config.go#L534)):*
> ```Go
> 	// SystemDebugServer is set if the sql configuration will be running in a shared
> 	// process model, allowing for parent process debugging if granted by a tenant
> 	// capabitlity.
> ```

nit: capability
___
*[`pkg/server/tenant.go` line 417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NVZiwd7EEP7WaPii8ft:-NVZiwd7EEP7WaPii8fu:b-gn8993) ([raw file](https://github.com/cockroachdb/cockroach/blob/21c30cd0e431c7195ad87f889a78b045920851e3/pkg/server/tenant.go#L417)):*
> ```Go
> 
> 	if _, isSharedProcess := deps.instanceIDContainer.OptionalNodeID(); isSharedProcess {
> 		debugServer = debug.NewTenantDelegatingServer(
> ```

Could you not instantiate `TenantDelegatingServer` in _every_ case (including system tenant) so we have just 1 code path?

Presumably, the system tenant has the capability so the cap check would succeed.
___
*[`pkg/server/testserver.go` line 924 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NVZih8uCgmjyZP4BDsU:-NVZih8vEtPVgAOe1Vmd:bl8nooz) ([raw file](https://github.com/cockroachdb/cockroach/blob/21c30cd0e431c7195ad87f889a78b045920851e3/pkg/server/testserver.go#L924)):*
> ```Go
> 	hts.t.authentication = sqlServerWrapper.authentication
> 	hts.t.sqlServer = sqlServer
> 	hts.t.tenantName = args.TenantName
> ```

Why is this change needed?

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102635)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @knz, @renatolabs, and @smg260)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NVZh6Fq8OKzeNm4VmDd):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

"all tenant processes" -> "all tenant servers"
</blockquote></details>

Done.
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NVZhC_e55bbP97V05tH):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Add:
"""
This implementation is fine when servers serve just 1 tenant in a given process; that tenant then legitimately has access to all process-level control.
However, it becomes a problem in shared-process multitenancy, when the same process is shared by multiple tenants. In that case, it is undesirable for 1 tenant to have access to & control process properties, as it could influence the well-functioning of other tenants or potentially leak data across tenant boundaries.
"""
</blockquote></details>

Done.
___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NVZhZoo6VGfJdBPDxnD):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

"This commit gates access _to the debug server_ behind"...
</blockquote></details>

Done.
___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NVZhbng6HU973utZEUv):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

"only with shared-process multitenancy"
</blockquote></details>

Done.
___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NVZhi0M3OFjV29fneC9):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

"Tenant servers running within..."
</blockquote></details>

Done.
___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NVZhkCN10KGu2Oifmr5):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

remove "on the in-process tenant".
</blockquote></details>

Done.
___
*[`-- commits` line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NVZhnc94aUwLIi34E5l):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

What is "parent process" in this sentence? IMHO this is not a thing. Did you mean "HTTP server for the system tenant"?
</blockquote></details>

clarified to say system tenant, but it does delegate to a separate debug server in this case, not the HTTP server.
___
*[`-- commits` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NUX0az7-JZSub8j_g32):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

yep I think it's not the right issue.
</blockquote></details>

ty. fixed.
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go` line 404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NUX6q001IFZf4W2oMG-:-NVf6XRm5i04gHHGRwDo:btlsor9) ([raw file](https://github.com/cockroachdb/cockroach/blob/21c30cd0e431c7195ad87f889a78b045920851e3/pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go#L404)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: `fallthrough` is a bit of an overloaded term here when used in a switch statement. Can we re-word this a bit?
</blockquote></details>

copied from other functions in this file so I'm gonna keep for consistency.
___
*[`pkg/server/config.go` line 533 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NVZiAP412hFsTL-dKqi:-NVf6gmJDzFeZa2blzRt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/21c30cd0e431c7195ad87f889a78b045920851e3/pkg/server/config.go#L533)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

"parent process" is not a thing.
</blockquote></details>

Done.
___
*[`pkg/server/config.go` line 534 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NVZi8fn4LBgS-BPGXEE:-NVf6gH5Af5Q86zAUrrL:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/21c30cd0e431c7195ad87f889a78b045920851e3/pkg/server/config.go#L534)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: capability
</blockquote></details>

Done
___
*[`pkg/server/tenant.go` line 417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NVZiwd7EEP7WaPii8ft:-NXlAkJT2W8BAXMRBD4B:bl3faez) ([raw file](https://github.com/cockroachdb/cockroach/blob/21c30cd0e431c7195ad87f889a78b045920851e3/pkg/server/tenant.go#L417)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Could you not instantiate `TenantDelegatingServer` in _every_ case (including system tenant) so we have just 1 code path?

Presumably, the system tenant has the capability so the cap check would succeed.
</blockquote></details>

All cases now use the delegating server although it doesn't eliminate this particular conditional. not sure if that's possible.

**Review by knz — CHANGES_REQUESTED** [review]
I have dug into this PR (and tried it out) in more details. 

I would like to walk back my previous assent on the general architecture proposed; I think this approach is not going to work. (But I have suggestions - keep on reading.)

What this PR effectively does is re-route the handling of the traffic for, say, tenant 123 to the instance of debug.Server that was created for the system tenant.

This approach would only be approximately OK if a debug server **only** served endpoints that inspect the process's state -- or things that are obviously "across tenant boundaries". But that is not the case. For example, the display of HBA rules is tenant specific. With your current code, if i ask the debug server for tenant 123 its HBA rules, I get the HBA rules of the system tenant. This is not what we want.

Additionally, the epic is about giving secondary tenants access to process-scope inspection, for example pprof. It should not include things that are extremely well scoped to the KV/storage layer. For example, the LSM and closed timestamp inspection do not fall under "can inspect process state". (We could discuss adding a separate capability for that, but as a rule of thumb, if the debug endpoint wouldn't work on a separate-process deployment, it shouldn't be included under the "process debug" capability.)

Here is what we can do to make this PR work:

- keep all the capability code you've already modified - this is OK
- revert the code to instantiate `debug.Server` anew for each tenant server, like previously.
- new direction: inject a capability authorizer function (from the server args) into the debug server of secondary tenants.

Here's my proposal: https://github.com/dhartunian/cockroach/pull/7

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-:-NYNYhRL04L16gWxCsVu:b-9t01mn)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @dhartunian, @renatolabs, and @smg260)

___
*[`-- commits` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NUX0az7-JZSub8j_g32):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

ty. fixed.
</blockquote></details>

don't forget to update the issue ref in the PR description too.
___
*[`pkg/server/tenant.go` line 417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-NVZiwd7EEP7WaPii8ft:-NYNYYLX1kqT8zrFJeeu:bohxra8) ([raw file](https://github.com/cockroachdb/cockroach/blob/21c30cd0e431c7195ad87f889a78b045920851e3/pkg/server/tenant.go#L417)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

All cases now use the delegating server although it doesn't eliminate this particular conditional. not sure if that's possible.
</blockquote></details>

I see what you have done here. I don't dislike it, but I think you could have been much simpler. I think you forgot about the existence of `http.HandlerFunc`.

See here for a suggestion: https://github.com/dhartunian/cockroach/pull/6

(but also note this is not the direction we should go to, see my comment at top)

**Review by dhartunian — COMMENTED** [review]
took your advice and commits @knz. I like this approach much better, thank you.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-:-NYtVXun9IKKgNagIMak:b-4ew4mv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @knz, @renatolabs, and @smg260)

**Review by knz — APPROVED** [review]
Can you also modify `configprofiles/profiles.go` and add the new capability on line 105 thanks.

(We'll modify this logic to make it less manual later)

> Reviewed 39 of 40 files at r3, 18 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102635#-:-NYwWZ18016TkbXVfBfr:b-jprhqo)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @dhartunian, @renatolabs, and @smg260)

**Comment by knz** [comment]
> Can you also modify configprofiles/profiles.go and add the new capability on line 105 thanks.

Alternatively you can ignore my request -- I have #105609 queued.

**Comment by dhartunian** [comment]
TFTRs

bors r=knz,abarganier

**Pull request merged**
