### PR TITLE
build: remove deps.sh

### LINKED ISSUE #2058: ci: bake npm and related ui dependencies into builder image
Every CI build reinstalls mocha, stylus, tslint, typescript, chai and probably some other items. It should be possible bake these deps into the builder image. See [build/builder.sh init](https://github.com/cockroachdb/cockroach/blob/master/build/builder.sh#L7). The old `deps-docker.sh` script accomplished this for the `cockroachdb/cockroach-dev` image, but I think the technique will have to be modified for `build/builder.sh init`. Or maybe not, I haven't looked in depth.

### PR DESCRIPTION
**Pull request by tamird**
`go generate` will `npm install` if needed, so this script doesn't really buy us anything other than installing `glock` and `go vet`.

### CODE REVIEW

**Comment by petermattis** [comment]
LGTM

**Comment by bdarnell** [comment]
The npm modules are used in CI for the `go generate` test. Since this branch passes CI, it looks like something is ignoring the exit status of commands in `go generate`.

**Comment by tamird** [comment]
This branch hasn't actually passed CI yet. I'm looking into it a bit more.

**Comment by tamird** [comment]
Ah, `go generate` will `npm install` if needed.

**Comment by bdarnell** [comment]
Weird, it was showing up as green when I wrote that comment.

**Comment by tamird** [comment]
OK, this doesn't actually close #2058. I've removed that from the description and will address that issue in a separate PR.

**Comment by petermattis** [comment]
Hmm, as long as the `npm install` is still being done, it seems preferable to get rid of `deps.sh`.

**Comment by bdarnell** [comment]
Don't we still need `deps.sh` to bootstrap a new developer environment? With this change `make` will fail unless the user has manually installed `glock`.

**Comment by tamird** [comment]
Yes, that's the only regression. I'll push this logic to the makefile like we do for protos (i.e. `.bootstrap` will depend on the `glock` binary and install it if it's missing).

**Comment by tamird** [comment]
@bdarnell PTAL

**Comment by bdarnell** [comment]
LGTM. We're no longer installing `go vet`, but I can't remember when that's necessary anyway.

**Pull request merged**
