### PR TITLE
build: turn on more optimizations and debug info

### PR DESCRIPTION
**Pull request by benesch**
See individual commits for details.

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm: but you may want to wait for @bdarnell. Can't wait for all those symbols!

---

Reviewed 5 of 5 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24199#-:-L8XmtdCDGiNo8LISZTz:bz39q1q)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 6 of 8 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24199#-:-L8Y6XazDW9vx3F6gkPW:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: 6 of 8 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[Makefile, line 598 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24199#-L8Y6cDr27QTctgVrdil:-L8Y6cDr27QTctgVrdim:b-xv0a3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e25dfaa6d10186b03bacc38dc1ba57234cd2bbc/Makefile#L598)):*
> ```Makefile
> 	@# NOTE: If you change the CMake flags below, bump the version in
> 	@# $(C_DEPS_DIR)/rocksdb-rebuild. See above for rationale.
> 	cd $(ROCKSDB_DIR) && CFLAGS+=" $(sse)" && CXXFLAGS+=" $(sse)" cmake $(XCMAKE_FLAGS) $(ROCKSDB_SRC_DIR) \
> ```

Is the `&&` necessary there and does it do the right thing? I thought you could pass multiple env vars to a command via: `CFLAGS="..." CXXFLAGS="..." cmake`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24199)*

**Comment by petermattis** [comment]
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[Makefile, line 598 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24199#-L8Y6cDr27QTctgVrdil:-L8Y70UNC6uCYETj9sE1:b-nycjjk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e25dfaa6d10186b03bacc38dc1ba57234cd2bbc/Makefile#L598)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is the `&&` necessary there and does it do the right thing? I thought you could pass multiple env vars to a command via: `CFLAGS="..." CXXFLAGS="..." cmake`.
</blockquote></details>

```
~ CFLAGS=foo CXXFLAGS=bar env | grep CFLAGS
CFLAGS=foo
~ CFLAGS=foo && CXXFLAGS=bar env | grep CFLAGS
~
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24199)*

**Comment by benesch** [comment]
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Makefile, line 598 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24199#-L8Y6cDr27QTctgVrdil:-L8YCLeZD8DKWtKFbFXz:b-6dk156) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e25dfaa6d10186b03bacc38dc1ba57234cd2bbc/Makefile#L598)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

```
~ CFLAGS=foo CXXFLAGS=bar env | grep CFLAGS
CFLAGS=foo
~ CFLAGS=foo && CXXFLAGS=bar env | grep CFLAGS
~
```
</blockquote></details>

That only works if you're willing to wholesale overwrite the variable, but we need to append. This (very confusingly) just sets `FOO=BAR`:

```
FOO=garbage
FOO+=BAR
```

The code here does work (at least once you incorporate my typo in r4); Your second example just needs to export the variables first:

```
export CFLAGS CXXFLAGS; CFLAGS=foo && CXXFLAGS=bar env | grep CFLAGS
```

Open to less confusing ways of accomplishing this. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24199)*

**Comment by petermattis** [comment]
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Makefile, line 598 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24199#-L8Y6cDr27QTctgVrdil:-L8YDgH93WF-dVlvgNgj:b-euveme) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e25dfaa6d10186b03bacc38dc1ba57234cd2bbc/Makefile#L598)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

That only works if you're willing to wholesale overwrite the variable, but we need to append. This (very confusingly) just sets `FOO=BAR`:

```
FOO=garbage
FOO+=BAR
```

The code here does work (at least once you incorporate my typo in r4); Your second example just needs to export the variables first:

```
export CFLAGS CXXFLAGS; CFLAGS=foo && CXXFLAGS=bar env | grep CFLAGS
```

Open to less confusing ways of accomplishing this. 
</blockquote></details>

Ok, my second example doesn't work for appending to a flag, but does your existing code work? If it does, I'm fine with it as-is. Another option would be something like: `CFLAGS="$(CFLAGS) $(sse)" CXXFLAGS="$(CXXFLAGS) $(sse)" cmake ...`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24199)*

**Comment by benesch** [comment]
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Makefile, line 598 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24199#-L8Y6cDr27QTctgVrdil:-L8YESID9oHMJRrgig77:b6ictch) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e25dfaa6d10186b03bacc38dc1ba57234cd2bbc/Makefile#L598)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ok, my second example doesn't work for appending to a flag, but does your existing code work? If it does, I'm fine with it as-is. Another option would be something like: `CFLAGS="$(CFLAGS) $(sse)" CXXFLAGS="$(CXXFLAGS) $(sse)" cmake ...`.
</blockquote></details>

Yup, it works!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24199)*

**Pull request merged**
