### PR TITLE
distsql: distribute index joins

### PR DESCRIPTION
**Pull request by RaduBerinde**
Use a join reader on each node rather than just one. Hoping it will speed up
TPC-H queries.

### CODE REVIEW

**Comment by andreimatei** [comment]
:lgtm: nice

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 85 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14918#-KhhLPVpLLNCkZee6sOz:-KhhLPVpLLNCkZee6sP-:bs65dce) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec4f8bbc9c11c6e47ad52e4c567160c53ef6389c/pkg/sql/distsql_physical_planner.go#L85)):*
> ```Go
> // If true, for index joins  we instantiate a join reader on every node that
> // has a stream (usually from a table reader). If false, there is a single join
> // reader on the gateway node.
> ```

the "on the gateway node" part is not necessarily true, right? I'd just remove it.

---

*[pkg/sql/distsql_physical_planner.go, line 1061 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14918#-KhhKtLrjVuEpYcr649R:-KhhKtLrjVuEpYcr649S:b-puc7r6) ([raw file](https://github.com/cockroachdb/cockroach/blob/04ee3b00444ad2d2c6de9424b330382f89cb0f66/pkg/sql/distsql_physical_planner.go#L1061)):*
> ```Go
> 
> 	// TODO(radu): we currently use a single JoinReader. We could have multiple.
> 	// Note that in that case, if the index ordering is used, we must make sure
> ```

So the ordering part of this TODO will work because we pass the desired ordering to `AddNoGroupingStage`? And that's tested by the test with `Here we care about ordering by v, but v is not otherwise used.`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14918#-:-KhhLahxYZ6jWI14f7Ci:bb76hxo)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsql_physical_planner.go, line 85 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14918#-KhhLPVpLLNCkZee6sOz:-KhhMeUPcRBpUhsSw03A:b-15g5zb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec4f8bbc9c11c6e47ad52e4c567160c53ef6389c/pkg/sql/distsql_physical_planner.go#L85)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

the "on the gateway node" part is not necessarily true, right? I'd just remove it.
</blockquote></details>

right, removed.

---

*[pkg/sql/distsql_physical_planner.go, line 1061 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14918#-KhhKtLrjVuEpYcr649R:-KhhMLJfmB-zi89iIWGm:b-9brprv) ([raw file](https://github.com/cockroachdb/cockroach/blob/04ee3b00444ad2d2c6de9424b330382f89cb0f66/pkg/sql/distsql_physical_planner.go#L1061)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

So the ordering part of this TODO will work because we pass the desired ordering to `AddNoGroupingStage`? And that's tested by the test with `Here we care about ordering by v, but v is not otherwise used.`?
</blockquote></details>

Yeah, it's tested by that.

The situation I had in mind for that TODO isn't actually happening - I thought that in this case, the `indexJoinNode` would not even emit `v` but that's not the case - it emits `v`, its `Ordering` reflects the ordering by `v` and later a sortNode removes it. Plumbing the column is the only way the sort node can figure out it doesn't need sorting.

```
root@:26257/test> EXPLAIN (VERBOSE) SELECT w FROM t WHERE v > 100 ORDER BY v;
+-------+------------+----------+-------------+-----------------------------+----------+
| Level |    Type    |  Field   | Description |           Columns           | Ordering |
+-------+------------+----------+-------------+-----------------------------+----------+
|     0 | nosort     |          |             | (w)                         |          |
|     0 |            | order    | +v          |                             |          |
|     1 | render     |          |             | (w, v)                      | +v       |
|     1 |            | render 0 | test.t.w    |                             |          |
|     1 |            | render 1 | test.t.v    |                             |          |
|     2 | index-join |          |             | (k[omitted], v, w)          | +v       |
|     3 | scan       |          |             | (k, v[omitted], w[omitted]) | +v       |
|     3 |            | table    | t@v         |                             |          |
|     3 |            | spans    | /101-       |                             |          |
|     3 | scan       |          |             | (k[omitted], v, w)          |          |
|     3 |            | table    | t@primary   |                             |          |
+-------+------------+----------+-------------+-----------------------------+----------+
```

Compare with the same query without order by, notice v is `[omitted]`:
```
root@:26257/test> EXPLAIN (VERBOSE) SELECT w FROM t WHERE v > 100;
+-------+------------+----------+-------------+-----------------------------+----------+
| Level |    Type    |  Field   | Description |           Columns           | Ordering |
+-------+------------+----------+-------------+-----------------------------+----------+
|     0 | render     |          |             | (w)                         |          |
|     0 |            | render 0 | test.t.w    |                             |          |
|     1 | index-join |          |             | (k[omitted], v[omitted], w) |          |
|     2 | scan       |          |             | (k, v[omitted], w[omitted]) |          |
|     2 |            | table    | t@v         |                             |          |
|     2 |            | spans    | /101-       |                             |          |
|     2 | scan       |          |             | (k[omitted], v[omitted], w) |          |
|     2 |            | table    | t@primary   |                             |          |
+-------+------------+----------+-------------+-----------------------------+----------+
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14918)*

**Comment by arjunravinarayan** [comment]
Nice work.

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 86 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14918#-KhiBA8Z3f8qqiJj11yc:-KhiBA8Z3f8qqiJj11yd:bjudzsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2c0159b517d803742b1e1be7531d30d37170c42/pkg/sql/distsql_physical_planner.go#L86)):*
> ```Go
> // has a stream (usually from a table reader). If false, there is a single join
> // reader.
> var distributeIndexJoin = envutil.EnvOrDefaultBool("COCKROACH_DISTSQL_DISTRIBUTE_INDEX_JOIN", true)
> ```

Not sure this is necessary, I imagine you put this here for a/b testing this change, but that can be done with just checking out the previous commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14918#-:-KhiAxGh5lT2k_owIIsl:bdtx8rj)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/distsql_physical_planner.go, line 86 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14918#-KhiBA8Z3f8qqiJj11yc:-KhiZrH4aHgr184sbXZu:b-b5r5bn) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2c0159b517d803742b1e1be7531d30d37170c42/pkg/sql/distsql_physical_planner.go#L86)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Not sure this is necessary, I imagine you put this here for a/b testing this change, but that can be done with just checking out the previous commit.
</blockquote></details>

It's harder to redeploy the binary. I also want to have it just in case a customer runs into an issue - in large clusters spreading out the index join might be less efficient if every node only looks up a small number of rows.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14918)*

**Pull request merged**
