### PR TITLE
sqlccl: add table size to SHOW BACKUP

### PR DESCRIPTION
**Pull request by danhhz**

### CODE REVIEW

**Comment by dt** [comment]
:lgtm: (once linter likes the spelling)

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17261#-:-Kq4gMcUGA5P7j8zMrBA:b-8vzjpq)*

**Comment by danhhz** [comment]
PTAL at the timestamp changes we discussed offline.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17261#-:-KqTCSJZB6_1GBvNtV5r:b7kjo87)*

**Review by dt — APPROVED** [review]

**Comment by danhhz** [comment]
TFTR!

**Comment by dianasaur323** [comment]
Quick question - if we are showing table size on the show backup command, should we surface that in the jobs table in the admin UI? cc @benesch @kuanluo

**Comment by kuanluo** [comment]
@dianasaur323 Good question! I'm leaning towards no, but it'd be helpful to understand more context re: table size. Why people need it? When is it important?

**Comment by benesch** [comment]
AIUI we eventually want to build a backup management tool into the admin UI. That's where I think information like backup size, tables contained, table size, etc. would be helpful. The jobs table doesn't really lend itself to showing the tables contained within a backup, though.

We might want to consider showing the return value of backups/restores (total number of rows and bytes, plus a few similar stats) into the jobs table, though, which gives operators a rough sense of how long a backup/restore of a given size will take when planning future backups/restores.

**Comment by dianasaur323** [comment]
Since we are eventually going to do scheduling, I don't feel strongly either way. I think it would be helpful in terms of capacity planning etc as you described, but it's not really the best solution for that at the end of the day. Your call @benesch

**Comment by kuanluo** [comment]
> We might want to consider showing the return value of backups/restores (that's total number of rows and bytes, plus a few similar stats) into the jobs table, though, which gives operators a rough sense of how long a backup/restore of a given size will take when planning future backups/restores.

@benesch Good point. Surfacing the total value in the CLI seems useful, but perhaps hold off on showing it in the table in the UI front. With @dianasaur323 on this, not strong either way.

**Comment by dianasaur323** [comment]
Hmmm.. the one benefit I could see is that if you ran a couple backups, and now want to go back and run a restore on a given backup, you may want to know how many rows / bytes you are trying to restore. Based on that thought, we should either include it in the jobs table, or just add a tooltip mentioning that there is a CLI command to pull that information.

**Comment by kuanluo** [comment]
Sounds good. It would be so helpful to have metrics soon, haha. I'd leave it up to you and @benesch to decide then.

**Comment by benesch** [comment]
The proposed design in #17658 would include this information, but not for 1.1.

**Pull request merged**
