### PR TITLE
roachpb: Rename RetryUsingTransactionError to TransactionRetryWithProtoRefreshError

### PR DESCRIPTION
**Pull request by knz**
The name of retry errors types is embedded in the error message
returned to SQL clients. When a human sees the name
"RetryUsingTransactionError" coming from their SQL client as a result
of sending a standalone statement, they are likely to get the wrong
impression that they should re-send their statement enclosed by BEGIN
and COMMIT, which is the incorrect course of action.

The name "TransactionRetryWithProtoRefreshError" is equally intuitive
for the CockroachDB developer and does not carry the risk to confuse
SQL users.

Release note: None

### CODE REVIEW

**Review by bobvawter — APPROVED** [review]
LGTM.  I agree that we should make this error message meaningful to cockroach devs, but not necessarily to the user.  Perhaps, we should figure out instead or in addition how to keep this error, whatever it's named, from being visible to user code.

**Comment by knz** [comment]
I agree that kv-level errors should be encapsulated away to not leak to the client (or maybe be populated in the pgerror "detail" field instead). Do you want to file an issue on this and add it to the error cleanup work?

**Pull request merged**
