### PR TITLE
pgwire: fix decimal decoding with trailing zeroes

### LINKED ISSUE #25460: sql: binary protocol bug with decimal
I am trying to store some decimal values using Elixir / Ecto and it seems CRDB is not decoding the passed value properly:

The `discount` field is defined as DECIMAL(13,4) in the table.

On Elixir/Ecto side
```
INSERT INTO "passes" ("discount", ...) VALUES ($1, ...) [#Decimal<15>, ...]
```

On CRDB side:
```
"INSERT INTO passes(discount, ...) VALUES ($1, ...)" {$1:"1500000.0000", ...} 1.047 1 ""
```

CRDB info:
```
❯ cockroach version
Build Tag:    v2.0.1
Build Time:   2018/04/23 19:18:28
Distribution: CCL
Platform:     darwin amd64 (x86_64-apple-darwin17.5.0)
Go Version:   go1.10.1
C Compiler:   4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)
Build SHA-1:  c92bc6e912880c28c0784d3208583fb27f482f76
Build Type:   development
```

### PR DESCRIPTION
**Pull request by otan**
Resolves https://github.com/cockroachdb/cockroach/issues/25460

In addition to the release note, I have also modified the docker runfile
to support elixir tests, and also updated the elixir tests to be run.

Release note (bug fix): In previous PRs, drivers that do not truncate
trailing zeroes for decimals in the binary format end up having
inaccuracies of up to 10^4 during the decode step. In this PR, we fix
the error by truncating the trailing zeroes as appropriate. This fixes
known incorrect decoding cases with Postgrex in Elixir.

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
:lgtm: thanks - our Elixir users will be shouting your name from the rooftops!

cc @rafiss for visibility.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45613#-:-M1TfzvcCK7fqR-dFzuN:b-fcz59r)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @otan)

___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 515 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45613#-M1TgLct6g7mITtnISW8:-M1TgLct6g7mITtnISW9:bjpmn39) ([raw file](https://github.com/cockroachdb/cockroach/blob/8157235514e07afeabd1b85e89af795f42049108/pkg/sql/pgwire/pgwirebase/encoding.go#L515)):*
> ```Go
> 				// to cut it back to "0012,3456,0000,0" for this to be correct.
> 				if alloc.i16 == 0 && (alloc.pgNum.Weight+1) < alloc.pgNum.Ndigits {
> 					decDigits = decDigits[:len(decDigits)-int(PGDecDigits-(alloc.pgNum.Dscale%PGDecDigits))]
> ```

Scale matters! Wow...
___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 528 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45613#-M1TgPr4DwK2uAyE0plv:-M1TgPr4DwK2uAyE0plw:beqe5rv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8157235514e07afeabd1b85e89af795f42049108/pkg/sql/pgwire/pgwirebase/encoding.go#L528)):*
> ```Go
> 					decDigits = strconv.AppendUint(decDigits, uint64(alloc.i16), 10)
> 				}
> 				if len(decDigits) > 0 {
> ```

care to comment on this block too?

**Review by otan — COMMENTED** [review]
Ok! I reworked it a little if you want to take another look (had a *massive* showerthought about making this easier to read, comment salad added). 
I will merge this after I get access to dockerhub so I can add the acceptance tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45613#-:-M1Tz-R85NycV-KhxOfq:blag2md)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis)

___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 515 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45613#-M1TgLct6g7mITtnISW8:-M1TyYjdBC0AHMZhxxtd:b-hbv9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/8157235514e07afeabd1b85e89af795f42049108/pkg/sql/pgwire/pgwirebase/encoding.go#L515)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Scale matters! Wow...
</blockquote></details>

I had a massive showerthought and reworked this to be even better and handle more edges!
___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 528 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45613#-M1TgPr4DwK2uAyE0plv:-M1Tk76R3C3-Q1AcPmuL:b-by52w6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8157235514e07afeabd1b85e89af795f42049108/pkg/sql/pgwire/pgwirebase/encoding.go#L528)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

care to comment on this block too?
</blockquote></details>

turns out i don't need this if statement, since there should always be one char!

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45613)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @otan)

___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 464 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45613#-M1WkXAa4Q0qgkm7KPJN:-M1WkXAa4Q0qgkm7KPJO:b94vlaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e199ae9a8637550e91f65d001f7a5f2e95bb5724/pkg/sql/pgwire/pgwirebase/encoding.go#L464)):*
> ```Go
> 					// * "1234" stays "1234"
> 					// * "123" becomes "0123"
> 					// * "12" becomes "12"
> ```

Sorry just doing a pass by here, why does "12" become "12"?

**Comment by otan** [comment]
___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 464 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45613#-M1WkXAa4Q0qgkm7KPJN:-M1WuscP-AyE03AQgz3v:b-xbb138) ([raw file](https://github.com/cockroachdb/cockroach/blob/e199ae9a8637550e91f65d001f7a5f2e95bb5724/pkg/sql/pgwire/pgwirebase/encoding.go#L464)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Sorry just doing a pass by here, why does "12" become "12"?
</blockquote></details>

because i probably did undo when writing this comment and am a klutz. thanks for catching it!

**Comment by otan** [comment]
bors r=jordanlewis

**Pull request merged**
