### PR TITLE
changefeedccl: refactor the poller and table_history into subpackages

### PR DESCRIPTION
**Pull request by ajwerner**
While this change is a major overhaul of the package, the changes are wholly cosmetic and do not change any behavior. No tests were harmed, some tests were added, more should be.
This refactor will make it easy to address #44265 and more generally should make it easier to test and iterate on changefeed code.

This commit creates a new subpackage of changefeedccl called `tablefeed`.
A table feed tracks events on tables. The client has the option to filter
out certain table events which it is not interested in.

A tablefeed provides a queue to which the caller can pass a timestamp.
The queue promises to return all events which occurred at or before
the caller's timestamp. If that timestamp has not yet been proven,
the call will block until it has been.

The introduction of this abstraction provides points to improve efficiency
by sharing polling between changefeeds. Ideally we'd only ever have a single
goroutine for all changefeeds fetching table descriptors. It also provides
an interface behind which to hide table descriptor locking in order to
reduce the latency of changefeed event emission.

This package is used by the kvfeed package to perform logical backfill
at the appropriate moment and to ensure that higher levels will be able to
properly interpret any kv-pair sent up to it.

The commit moves the `*poller` abstraction to a new package called
kvfeed. The poller has not actually performed polling outside of the
table descriptors in several releases. The entrypoint to the
functionality it used to expose is now `kvfeed.Run`. In addition
to the exported method, this refactor introduces several internal
abstractions to aid in testing and readability.

This change also introduces a changefeedbase package to export options
used in subpackages.

### CODE REVIEW

**Comment by ajwerner** [comment]
Alright @danhhz this is RFAL.

cc @nvanbenschoten you may be interested. We talked about this on Friday. Zero pressure to actually review.

**Review by danhhz — COMMENTED** [review]
:lgtm_strong: :clap:

I'd love it if we could make some of the diffs more obvious. Both because this was difficult to review and also to help git keep history. I want to encourage you to add a prefix commit to the PR that does only the file moves (even leave pkgs the same etc, nothing will compile, make it way obvious) and then do the cleanups in the second commit. The tricky bit here is something like TableFeed which replaces both Poller and TableHistory. Maybe for that one, just pick one or the other as the source file?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-:-M0-96U57V39WOc7GvT2:b-hnoern)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @danhhz)

___
*[pkg/ccl/changefeedccl/bench_test.go, line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M-u3M5q4m-9wPh9c-1b:-M-u3M5r2lMAa77eCBRY:bscxi5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8cedbef84157adbeb4de7e3d587b2f3211e27d/pkg/ccl/changefeedccl/bench_test.go#L211)):*
> ```Go
> 		nil /* curCount */, nil /* maxHist */, math.MaxInt64, settings,
> 	)
> 	needsInitialScan := initialHighWater == (hlc.Timestamp{})
> ```

nit: while you're in here, consider replacing the == hlc.Timestamp{} checks with IsEmpty()
___
*[pkg/ccl/changefeedccl/changefeed.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M-u3_zu283noSAlMBlN:-M-u3_zu283noSAlMBlO:b-vif5f9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8cedbef84157adbeb4de7e3d587b2f3211e27d/pkg/ccl/changefeedccl/changefeed.go#L202)):*
> ```Go
> 					return nil, err
> 				}
> 			} else {
> ```

leave the same structure but add an `if input.IsResolved() to mirror the IsKV()`?
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M-u4B7L4MOpYrGa1fma:-M-u4B7L4MOpYrGa1fmb:b-w7z2jz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8cedbef84157adbeb4de7e3d587b2f3211e27d/pkg/ccl/changefeedccl/changefeed_processors.go#L38)):*
> ```Go
> )
> 
> type changeAggregator struct {
> ```

I have a branch I've never had time to merge that pulls all of the logic out of the distsql processors and make them thin wrappers. It's so hard to reason (for me at least) about the start/stop semantics as currently written. Just an FYI, nothing for you to do in this PR. https://github.com/cockroachdb/cockroach/compare/master...danhhz:cdc_processor_cleanup?expand=1
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M-u43zG7otJDcMxinjC:-M-u43zG7otJDcMxinjD:bww5kr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b28515785549a2c8b94be9f82f6ff5e28db8a64/pkg/ccl/changefeedccl/changefeed_processors.go#L236)):*
> ```Go
> 		err := ca.poller.RunUsingRangefeeds(ctx)
> 
> 		// Trying to call MoveToDraining here is racy (`MoveToDraining called in
> ```

I think you lost half a comment?
___
*[pkg/ccl/changefeedccl/kvfeed/backfill_policy_test.go, line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M0-0FKBCBgWjnQHgRdR:-M0-0FKBCBgWjnQHgRdS:b-4y0z3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8cedbef84157adbeb4de7e3d587b2f3211e27d/pkg/ccl/changefeedccl/kvfeed/backfill_policy_test.go#L87)):*
> ```Go
> 		ID:          id,
> 		Type:        *types.Bool,
> 		DefaultExpr: &truth,
> ```

proto.String("true")
___
*[pkg/ccl/changefeedccl/kvfeed/kv_feed.go, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M0-4k7YEB_9khTbxTuX:-M0-4k7YEB_9khTbxTuY:brwhcpx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8cedbef84157adbeb4de7e3d587b2f3211e27d/pkg/ccl/changefeedccl/kvfeed/kv_feed.go#L65)):*
> ```Go
> 	{
> 		rawTF := tablefeed.New(makeTablefeedConfig(cfg))
> 		// Start polling tablehistory, which must be done concurrently with
> ```

missed a tablehistory
___
*[pkg/ccl/changefeedccl/kvfeed/kv_feed_test.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M0-6li70LH2dOiT9ucs:-M0-6li70LH2dOiT9uct:bh4el9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8cedbef84157adbeb4de7e3d587b2f3211e27d/pkg/ccl/changefeedccl/kvfeed/kv_feed_test.go#L117)):*
> ```Go
> 			for expScans := tc.expScans; len(expScans) > 0; expScans = expScans[1:] {
> 				scan := <-scans
> 				require.Equal(t, expScans[0], scan.Timestamp)
> ```

this is not allowed to be called from goroutines
___
*[pkg/ccl/changefeedccl/tablefeed/table_feed.go, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M-uvb1ICgzpVN5yCzgR:-M-uvb1ICgzpVN5yCzgS:b-qq49dk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8cedbef84157adbeb4de7e3d587b2f3211e27d/pkg/ccl/changefeedccl/tablefeed/table_feed.go#L65)):*
> ```Go
> 	// InitialHighWater is the timestamp after which events should occur.
> 	//
> 	// NB: When clients want to create a changefeed which has a resolve timestamp
> ```

nit: resolved timestamp
___
*[pkg/ccl/changefeedccl/tablefeed/table_feed.go, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M0-7Of2EwI1yHWb8Aqw:-M0-7Of2EwI1yHWb8Aqx:b-mlxuh9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8cedbef84157adbeb4de7e3d587b2f3211e27d/pkg/ccl/changefeedccl/tablefeed/table_feed.go#L91)):*
> ```Go
> // invariant (via `validateFn`). An error timestamp is also kept, which is the
> // lowest timestamp where at least one table doesn't meet the invariant.
> type TableFeed struct {
> ```

TableFeed makes me think of some sort of feed of/from a single table, not of a feed of changes to metadata of all tables. TableDescFeed?
___
*[pkg/ccl/changefeedccl/tablefeed/table_feed.go, line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M-uw0AxATxqtfaiS5-j:-M-uw0AxATxqtfaiS5-k:bijil45) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8cedbef84157adbeb4de7e3d587b2f3211e27d/pkg/ccl/changefeedccl/tablefeed/table_feed.go#L158)):*
> ```Go
> }
> 
> // Start will start the tablefeed. It will run asynchronously in the passed
> ```

Is there some reason we can't make the signature of this function `func(context.Context) error` and have the caller pass it to g.GoCtx? Passing ctxgroup.Group in is kind of awkward
___
*[pkg/ccl/changefeedccl/kvfeed/buffer.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M-uotS1DLRL8EWzo8SN:-M-uotS1DLRL8EWzo8SO:b-r64yk6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8cedbef84157adbeb4de7e3d587b2f3211e27d/pkg/ccl/changefeedccl/kvfeed/buffer.go#L58)):*
> ```Go
> 
> // IsKV returns true if this corresponds to a KV event. If it returns
> // false, this entry corresponds to a resolved event.
> ```

This gives Event a sort of boolean semantics: either a kv or a resolved. I prefer more of an enum approach: IsKV() returning false doesn't imply IsResolved, you have to check. Feels more obvious/less subtle
___
*[pkg/ccl/changefeedccl/kvfeed/buffer.go, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M-upDhT5zuSDSEZWGGN:-M-upDhT5zuSDSEZWGGO:boablb6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8cedbef84157adbeb4de7e3d587b2f3211e27d/pkg/ccl/changefeedccl/kvfeed/buffer.go#L68)):*
> ```Go
> }
> 
> // PrevValue returns the previous values for this event. PrevValue is non-zero
> ```

nit: previous value
___
*[pkg/ccl/changefeedccl/kvfeed/buffer.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M-up_LK3n6pEl18lkuf:-M-up_LLB9WM4YcEFsQq:bm95bkc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8cedbef84157adbeb4de7e3d587b2f3211e27d/pkg/ccl/changefeedccl/kvfeed/buffer.go#L110)):*
> ```Go
> }
> 
> // buffer mediates between the changed data KVFeed and the rest of the
> ```

nit: chanBuffer
___
*[pkg/ccl/changefeedccl/kvfeed/buffer.go, line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M-uph8R3n8CI3r7S8ry:-M-uph8R3n8CI3r7S8rz:brgtyyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8cedbef84157adbeb4de7e3d587b2f3211e27d/pkg/ccl/changefeedccl/kvfeed/buffer.go#L120)):*
> ```Go
> // TODO(ajwerner): Consider adding a buffer here. We know performance of the
> // backfill is terrible. Probably some of that is due to every KV being sent
> // on a channel. This should all get benchmarked and tuned.
> ```

Agreed on benchmarking, tho I'd be surprised if the channel was our bottleneck. It's probably something even dumber than that. There's a unit-y benchmark but it was too clever for its own good and it's been broken since we switched away from poller
___
*[pkg/ccl/changefeedccl/kvfeed/buffer.go, line 223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M0-4bhRBkeYzwkjmcmq:-M0-4bhRBkeYzwkjmcmr:b-6zqkay) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8cedbef84157adbeb4de7e3d587b2f3211e27d/pkg/ccl/changefeedccl/kvfeed/buffer.go#L223)):*
> ```Go
> // increasing mvcc order.
> func (b *memBuffer) AddKV(
> 	ctx context.Context, kv roachpb.KeyValue, prevVal roachpb.Value, backfillTimestamp hlc.Timestamp,
> ```

why is this passed in but unused?

**Review by ajwerner — COMMENTED** [review]
TFTR! Should be RFAL. 

> I'd love it if we could make some of the diffs more obvious. Both because this was difficult to review and also to help git keep history. 

It started as two commits but I didn't know how to make it sane and compile. I made the change into 4 commits:

1) Add `changfeedbase`.
2) Add `schemafeed` (formerly `tablefeed`)
3) Add `kvfeed` but don't adopt it.
4) Adopt `kvfeed` and delete `poller`/`tableHistory`.

> even leave pkgs the same etc, nothing will compile, make it way obvious)

I'm opposed to this -- commits which don't compile make `git bisect` a nightmare! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-:-M0-eHtdAaNfNDaYfE7S:b-ebvrz7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @danhhz)

___
*[pkg/ccl/changefeedccl/bench_test.go, line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M-u3M5q4m-9wPh9c-1b:-M045WLQ6eXCzbJPDQh6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8cedbef84157adbeb4de7e3d587b2f3211e27d/pkg/ccl/changefeedccl/bench_test.go#L211)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: while you're in here, consider replacing the == hlc.Timestamp{} checks with IsEmpty()
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/changefeed.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M-u3_zu283noSAlMBlN:-M04Mbx1ApQiqAEl9Mti:b-f13zdd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8cedbef84157adbeb4de7e3d587b2f3211e27d/pkg/ccl/changefeedccl/changefeed.go#L202)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

leave the same structure but add an `if input.IsResolved() to mirror the IsKV()`?
</blockquote></details>

Made this a switch
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M-u43zG7otJDcMxinjC:-M04MMzc1pmGcyL_2T7l:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b28515785549a2c8b94be9f82f6ff5e28db8a64/pkg/ccl/changefeedccl/changefeed_processors.go#L236)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I think you lost half a comment?
</blockquote></details>

Done. 
___
*[pkg/ccl/changefeedccl/kvfeed/backfill_policy_test.go, line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M0-0FKBCBgWjnQHgRdR:-M04J0Ue6eE2Ekj8i95c:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8cedbef84157adbeb4de7e3d587b2f3211e27d/pkg/ccl/changefeedccl/kvfeed/backfill_policy_test.go#L87)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

proto.String("true")
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/kvfeed/kv_feed.go, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M0-4k7YEB_9khTbxTuX:-M04JXYd5ackbrY49JlO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8cedbef84157adbeb4de7e3d587b2f3211e27d/pkg/ccl/changefeedccl/kvfeed/kv_feed.go#L65)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

missed a tablehistory
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/kvfeed/kv_feed_test.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M0-6li70LH2dOiT9ucs:-M04JtiY4mVgiYv9MEDf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8cedbef84157adbeb4de7e3d587b2f3211e27d/pkg/ccl/changefeedccl/kvfeed/kv_feed_test.go#L117)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

this is not allowed to be called from goroutines
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/tablefeed/table_feed.go, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M-uvb1ICgzpVN5yCzgR:-M046iHw0OZIyvaWd7iE:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8cedbef84157adbeb4de7e3d587b2f3211e27d/pkg/ccl/changefeedccl/tablefeed/table_feed.go#L65)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: resolved timestamp
</blockquote></details>

Done
___
*[pkg/ccl/changefeedccl/tablefeed/table_feed.go, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M0-7Of2EwI1yHWb8Aqw:-M046jPk4apS5hCChnnC:b-f7fh7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8cedbef84157adbeb4de7e3d587b2f3211e27d/pkg/ccl/changefeedccl/tablefeed/table_feed.go#L91)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

TableFeed makes me think of some sort of feed of/from a single table, not of a feed of changes to metadata of all tables. TableDescFeed?
</blockquote></details>

I've turned it into a `SchemaFeed`. How does that make you feel?
___
*[pkg/ccl/changefeedccl/tablefeed/table_feed.go, line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M-uw0AxATxqtfaiS5-j:-M046opV6x9maiedI92m:brkd2mi) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8cedbef84157adbeb4de7e3d587b2f3211e27d/pkg/ccl/changefeedccl/tablefeed/table_feed.go#L158)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Is there some reason we can't make the signature of this function `func(context.Context) error` and have the caller pass it to g.GoCtx? Passing ctxgroup.Group in is kind of awkward
</blockquote></details>

The thought did occur. Done.
___
*[pkg/ccl/changefeedccl/kvfeed/buffer.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M-uotS1DLRL8EWzo8SN:-M046OCu7hztRA_VW69i:bk5j7i3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8cedbef84157adbeb4de7e3d587b2f3211e27d/pkg/ccl/changefeedccl/kvfeed/buffer.go#L58)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

This gives Event a sort of boolean semantics: either a kv or a resolved. I prefer more of an enum approach: IsKV() returning false doesn't imply IsResolved, you have to check. Feels more obvious/less subtle
</blockquote></details>

made it an enum and turned the conditions into switches. 
___
*[pkg/ccl/changefeedccl/kvfeed/buffer.go, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M-upDhT5zuSDSEZWGGN:-M04J5wP3aEGkMxGRqSl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8cedbef84157adbeb4de7e3d587b2f3211e27d/pkg/ccl/changefeedccl/kvfeed/buffer.go#L68)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: previous value
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/kvfeed/buffer.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M-up_LK3n6pEl18lkuf:-M04JBto20QNikGKwWpQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8cedbef84157adbeb4de7e3d587b2f3211e27d/pkg/ccl/changefeedccl/kvfeed/buffer.go#L110)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: chanBuffer
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/kvfeed/buffer.go, line 223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44907#-M0-4bhRBkeYzwkjmcmq:-M04JEi5AsJCZzossJ0f:bijt4jg) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a8cedbef84157adbeb4de7e3d587b2f3211e27d/pkg/ccl/changefeedccl/kvfeed/buffer.go#L223)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

why is this passed in but unused?
</blockquote></details>

To implement the interface for `Buffer`.

**Comment by danhhz** [comment]
I'm not going to get a chance to look again today, so feel free to merge without another pass. Anyway Reviewable is hanging for me right now and it sounds like you did everything I asked. I love SchemaFeed, that's better than whatever I suggested.

> I'm opposed to this -- commits which don't compile make git bisect a nightmare!

Commits are for humans! PRs are for git bisect! : - D

**Comment by ajwerner** [comment]
TFTR!

bors r=danhhz

**Pull request merged**
