### PR TITLE
cli/demo: misc fixes

### LINKED ISSUE #94308: cli/demo: avoid logging in anew everytime `cockroach demo` is restarted
Currently every `demo` session uses a separate HTTP URL (with separate credentials / web sessions).

This makes it impossible to restart `demo` while keeping the web browser open.
We want instead a way to preserve the web session across `demo` invocations.

Epic: CRDB-22814

Jira issue: CRDB-22819

### LINKED ISSUE #94835: cli/demo: the web UI URL should mention the target tenant
When using the server controller in `cockroach demo` to route HTTP traffic to a secondary tenant, the URLs printed on startup should also include a tenant routing key.

Epic: CRDB-22814

Jira issue: CRDB-23173

### PR DESCRIPTION
**Pull request by knz**
Fixes #94308.
Fixes #94835.
Epic: CRDB-22814

See the individual commits for details.

### CODE REVIEW

**Comment by knz** [comment]
@dhartunian this is following the conversation we had last Wednesday.

I chose to do it this way, instead of trying to modify the "demologin" endpoint, because during a restart, the web browser has already navigated away from "demologin" to one of the UI pages.

This approach also ensures that we preserve all concurrent web sessions (e.g. in multiple web browsers / across multiple SQL users).

**Comment by knz** [comment]
This is now ready with tests.

**Review by dhartunian — APPROVED** [review]
:lgtm: Nice! There's a slight possibility between the demo cluster starting and the sessions being loaded that a 401 unauthorized error will be returned. I can help with this but I think the UI needs to be less aggressive about logging you out automatically whenever it hits one of these errors. I don't think we want to delay starting the HTTP server.

> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94455#-:-NL3L7P84jQQKXl3dWoZ:b7n32q2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by knz** [comment]
> There's a slight possibility between the demo cluster starting and the sessions being loaded that a 401 unauthorized error will be returned. I can help with this but I think the UI needs to be less aggressive about logging you out automatically whenever it hits one of these errors. I don't think we want to delay starting the HTTP server.

Yes I saw this but it was not frequent. Let's see what experience tells us before we invest more in this direction.

**Comment by knz** [comment]
bors r=dhartunian

**Pull request merged**
