### PR TITLE
backupccl: extend decryption parameter support to SHOW BACKUP

### PR DESCRIPTION
**Pull request by dt**
Since this required syntax changes it wasn't included in first PR, but is
essentially just extending that change so that the same encryption_passphrase
parameter also applies to SHOW BACKUP.

Release note: none.

### CODE REVIEW

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44838)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @pbardea)

___
*[pkg/ccl/backupccl/backup_test.go, line 2659 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44838#-M-RhpLM8Tu4YbEB13GH:-M-RhpLM8Tu4YbEB13GI:bsdzftm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d16d6c396165a22b19d93b3ec7ccfdf4d4900224/pkg/ccl/backupccl/backup_test.go#L2659)):*
> ```Go
> 
> 	sqlDB.Exec(t, `SHOW BACKUP $1 WITH encryption_passphrase='abcdefg'`, backupLoc1)
> ```

Might be worthwhile to add a test that passes encryption options to a non-encrypted backup to make sure that we get the expected error.

**Review by miretskiy — COMMENTED** [review]
> Reviewed 5 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44838)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @pbardea)

___
*[pkg/ccl/backupccl/backup_test.go, line 2659 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44838#-M-RhpLM8Tu4YbEB13GH:-M-S3wcl6M8At1GC286q:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/d16d6c396165a22b19d93b3ec7ccfdf4d4900224/pkg/ccl/backupccl/backup_test.go#L2659)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Might be worthwhile to add a test that passes encryption options to a non-encrypted backup to make sure that we get the expected error.
</blockquote></details>

+1

**Review by pbardea — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44838)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

**Review by miretskiy — APPROVED** [review]

**Review by dt — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44838#-:-M-VFlOd7SSZwIro3_yl:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

___
*[pkg/ccl/backupccl/backup_test.go, line 2659 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44838#-M-RhpLM8Tu4YbEB13GH:-M-VAr202QlOQLFYzS_B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d16d6c396165a22b19d93b3ec7ccfdf4d4900224/pkg/ccl/backupccl/backup_test.go#L2659)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Pull request merged**
