### PR TITLE
build: add go runtime patch to bound non-preemptible work

### PR DESCRIPTION
**Pull request by nicktrav**
There are two commits in this patch set, and are best reviewed individually.

---

The first is a purely mechanical change to reapply our existing Go runtime patches to the upstream, and then port the diff back into Cockroach. This shuffles around the ordering of the various patches, making subsequent patching simpler.

The second patch is cribbed from golang/go#64417, and is the material change, touching #115192.

Epic: None.

### CODE REVIEW

**Review by rickystewart — APPROVED** [review]

**Comment by nicktrav** [comment]
Also probably a good idea to get someone from security to take a look at the second commit that has the crypto package changes.

**Comment by nicktrav** [comment]
Test failure is #118520. I'll rebase.

**Comment by dt** [comment]
> get someone from security to take a look

Filed https://cockroachlabs.atlassian.net/browse/SECSERV-28

**Review by rsevinsky-cr — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118605)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt, @nvanbenschoten, and @sumeerbhola)

**Review by rsevinsky-cr — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118605)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt, @nvanbenschoten, and @sumeerbhola)

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118605#-:-Nqi3OBMArIfjflxcuuF:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nicktrav, @rsevinsky-cr, and @sumeerbhola)

___
*[`build/teamcity/internal/release/build-and-publish-patched-go/diff.patch` line 177 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118605#-Nqi1pwl7snhEqgJ42lV:-Nqi1pwl7snhEqgJ42lW:b-7whvr3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b018b1ba8328911f15fc126ea10a678a0c9ca2a9/build/teamcity/internal/release/build-and-publish-patched-go/diff.patch#L177)):*
> ```Diff
>  	if len(p) >= chunk {
>  		n := len(p) &^ (chunk - 1)
> +		for n > maxAsmSize {
> ```

Without any new testing, we won't have any test coverage for the sha256 version of this logic. I've gone ahead and pushed a new commit to this PR to add testing for sha256. Since this is just testing, I won't rebuild the custom go sdk.

**Comment by dt** [comment]
CI failure appears to just be that merge base is too old to have https://github.com/cockroachdb/cockroach/pull/118665

**Comment by dt** [comment]
bors r=nvanbenschoten,rickystewart,rsevinsky-cr

**Comment by dt** [comment]
blathers backport 23.2

**Comment by dt** [comment]
Yeah, figured that was going to be its answer :(

**Comment by irfansharif** [comment]
Cool!

**Pull request merged**
