### PR TITLE
storage: add comment about worker loop

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10898)

### CODE REVIEW

**Comment by tamird** [comment]
But...why isn't it equivalent to not having that loop?

**Comment by petermattis** [comment]
It is equivalent. The comment even suggests that.

**Comment by tamird** [comment]
Right, but then why not write the simpler code?

**Comment by petermattis** [comment]
Adjusted the comment. The inner for-loop is less subtle.

**Comment by tamird** [comment]
I disagree, and I don't think we use this pattern elsewhere. Perhaps someone else is more amenable to your opinion on this.

**Comment by bdarnell** [comment]
I think the for-loop is fine as-is with no comment, but code with a comment that calls out its own unnecessaryness is kind of silly, unless we anticipate some change that might make the "unnecessary" code more correct than the alternative (and I don't think we do here). So I vote for either doing nothing or removing the loop instead of adding this comment.

**Comment by petermattis** [comment]
I'm going to close this PR and leave the code as is.

**Pull request closed without merging**
