### PR TITLE
sql: place index selection into full responsibility of scanNode.

### PR DESCRIPTION
**Pull request by knz**
Prior to this patch, the index selection logic in expandPlan() would
pause at renderNode and reason as follows: "hmm, is my direct source a
scanNode? If so, let's see how to improve it with index selection."
In other words index selection was under the responsibility of
renderNode.

This is a problem in every context where there is no renderNode, for
example for scan operands to joins.

This patch corrects the issue by pushing the responsibility for index
selection to scanNode expansion, which now can operate in any position
where a scanNode is valid.

This way joins can use indices too!

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13149)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Nice!! :lgtm_strong: 

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/expand_plan.go, line 369 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13149#-KbMX9tPXD_JcZpoJoW1:-KbMX9tPXD_JcZpoJoW2:b-bbujam) ([raw file](https://github.com/cockroachdb/cockroach/blob/f89e266b239bf1c321f492bc1c3532108a5d2e8b/pkg/sql/expand_plan.go#L369)):*
> ```Go
> }
> 
> // translateOrdering modifies the desired (downstream) ordering given
> ```

Should try to avoid upstream/downstream (In distsql, upstream/downstream refers to the data flow between the processors so up and down are reversed).

Could use parent/child, or since this is always for a render node, could just say "modifies a desired ordering on the output of the renderNode to a desired ordering on its its input".

---

*[pkg/sql/expand_plan.go, line 378 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13149#-KbMY-lntN6yJ_aX7lOS:-KbMY-lntN6yJ_aX7lOT:bo7haub) ([raw file](https://github.com/cockroachdb/cockroach/blob/f89e266b239bf1c321f492bc1c3532108a5d2e8b/pkg/sql/expand_plan.go#L378)):*
> ```Go
> 	var desiredUp sqlbase.ColumnOrdering
> 
> 	for _, colOrder := range desiredDown {
> ```

If we are rendering the same thing twice (eg `SELECT * FROM (SELECT x, y, x FROM ..) AS t(a,b,c) ORDER BY a,b,c`), we will have a duplicate column in the resulting ordering. I am not sure that is supported with `ColumnOrdering`. We could detect and skip any duplicates as they are ineffectual (order by `x,y,x` is the same as order by `x,y`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13149#-:-KbMjaFbPn3vVV7ZZyU3:b3cs2cs)*

**Comment by knz** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/expand_plan.go, line 369 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13149#-KbMX9tPXD_JcZpoJoW1:-KbQF5Io6VIBvAPGps00:b6sjmop) ([raw file](https://github.com/cockroachdb/cockroach/blob/f89e266b239bf1c321f492bc1c3532108a5d2e8b/pkg/sql/expand_plan.go#L369)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Should try to avoid upstream/downstream (In distsql, upstream/downstream refers to the data flow between the processors so up and down are reversed).

Could use parent/child, or since this is always for a render node, could just say "modifies a desired ordering on the output of the renderNode to a desired ordering on its its input".
</blockquote></details>

I think the usage here is compatible with distSQL. "Upstream" is where the data comes from, "Downstream" where the data goes to.
Nevertheless I used your phrasing which is simpler.

---

*[pkg/sql/expand_plan.go, line 378 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13149#-KbMY-lntN6yJ_aX7lOS:-KbQFHMhz_MxWTQo4POn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f89e266b239bf1c321f492bc1c3532108a5d2e8b/pkg/sql/expand_plan.go#L378)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

If we are rendering the same thing twice (eg `SELECT * FROM (SELECT x, y, x FROM ..) AS t(a,b,c) ORDER BY a,b,c`), we will have a duplicate column in the resulting ordering. I am not sure that is supported with `ColumnOrdering`. We could detect and skip any duplicates as they are ineffectual (order by `x,y,x` is the same as order by `x,y`).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13149)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/expand_plan.go, line 369 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13149#-KbMX9tPXD_JcZpoJoW1:-KbQWtTggZmqkjXIuZ5O:b-r1loi) ([raw file](https://github.com/cockroachdb/cockroach/blob/f89e266b239bf1c321f492bc1c3532108a5d2e8b/pkg/sql/expand_plan.go#L369)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think the usage here is compatible with distSQL. "Upstream" is where the data comes from, "Downstream" where the data goes to.
Nevertheless I used your phrasing which is simpler.
</blockquote></details>

Ah, right, I confused myself.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13149#-:-KbQWym6paORiNMvMUT8:bnfp4nl)*

**Comment by knz** [comment]
TFYR!

**Pull request merged**
