### PR TITLE
storage: prevent recording events into closed tracing spans

### LINKED ISSUE #39188: storage: proposal quota assertion failure
A cluster deployed from 92fef12128c997233d985d1c19e11faac005073f hit the assertion added in #39135. The cluster had just been deployed and was running the kv50 workload in the following way on a 5 node cluster:

```
workload run kv --init --concurrency 64 --tolerate-errors --min-block-bytes=8 --max-block-bytes=128 --read-percent=50
```

https://github.com/cockroachdb/cockroach/blob/92fef12128c997233d985d1c19e11faac005073f/pkg/storage/replica_proposal_quota.go#L240-L250  

```
F190731 10:16:28.126181 158 storage/replica_proposal_quota.go:246  [n2,s2,r21/3:/Table/53{-/1/-4314…}] proposalQuotaBaseIndex (44321) + quotaReleaseQueueLen (52) = 44373 must equal the applied index (44321)
```

An observation here is that the applied index exactly equal the `proposalQuotaBaseIndex`. In theory we should only append to the `quotaReleaseQueue` when the applied index increases. How did entries make it into the quotaReleaseQueue without incrementing the applied index?

The raft log for range 21 on n2 shows entries up to `44379` and a commit index of `44373` but the `RangeAppliedState` (below) indicates that entries only up to 44321 have been applied. This however might be taken with a grain of salt as the applied state is not durably synced.
The machine did not die so my assumption would be that the write would at least make it to the WAL when the process exits and thus the current reading would reflect the last call to `Commit(false)` but I'm not all that confident in that. 

```
0.000000000,0 /Local/RangeID/21/r/RangeAppliedState (0x01699d727261736b00): raft_applied_index:44321 lease_applied_index:44243 range_stats:<last_update_nanos:1564568187766302979 gc_bytes_age:27521006 live_bytes:521113 live_count:5282 key_bytes:353414 key_count:5282 val_bytes:1761302 val_count:23729 sys_bytes:588 sys_count:4 > 
```

### LINKED ISSUE #39190: roachtest: kv/contention/nodes=4 failed
SHA: https://github.com/cockroachdb/cockroach/commits/92fef12128c997233d985d1c19e11faac005073f

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=kv/contention/nodes=4 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1413388&tab=buildLog

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/20190731-1413388/kv/contention/nodes=4/run_1
	cluster.go:1726,kv.go:197,cluster.go:2069,errgroup.go:57: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1564553448-32-n5cpu4:5 -- ./workload run kv --init --secondary-index --duration=1h0m0s --cycle-length=512 --concurrency=128 --batch=4 --splits=4 {pgurl:1-4} returned:
		stderr:
		
		stdout:
		 write
		     58s        0          802.6          306.2     13.6   1342.2   9663.7  20401.1 write
		     59s        0          464.1          308.9      8.9    570.4   1342.2  12884.9 write
		    1m0s        0          164.0          306.5      6.3   1476.4   1811.9  36507.2 write
		_elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
		    1m1s        0           76.0          302.7      7.9   3087.0  15032.4  34359.7 write
		    1m2s        0          172.0          300.6      7.3   2550.1   3489.7  45097.2 write
		    1m3s        0          383.9          301.9      7.9   3087.0   4563.4  60129.5 write
		    1m4s        0          208.1          300.5      9.4   3892.3   6442.5  18253.6 write
		    1m5s        0          535.8          304.1      7.9   2013.3   3489.7   6174.0 write
		    1m6s        0          152.0          301.8      6.6   2281.7   6174.0   7516.2 write
		    1m7s        0           68.0          298.3      7.3   2415.9   5368.7  20401.1 write
		Error: EOF
		Error:  exit status 1
		: exit status 1
	cluster.go:2090,kv.go:207,test_runner.go:691: unexpected node event: 1: dead

```

### PR DESCRIPTION
**Pull request by ajwerner**
In #39188 we saw a surprising assertion failure due to a panic not being captured in a deferred function, the second commit deals with this obfuscation. The first commit adds a useful testing knobs utilized by the third commit. The third commit ensures that the if a command is reproposed more than one time at different MaxLeaseIndex values in such a way that the reproposals fail that the latter, not the earlier failure will report to the client. This prevents the panics seen in #39188. The fourth commit deals with cases where the same command is reproposed more than once at the same MaxLeaseIndex. 

The motivation for all of this is the logging of events into a closed recording trace span. In order to test such reuse the tests enable the [`trace.DebugUseAfterFinish`](https://github.com/golang/net/blob/ca1201d0de80cfde86cb01aea620983605dfe99b/trace/trace.go#L85-L87) and then read the logs to determine if the debugging code detected a use after finish. The code also adds an assertion that commands are finished at the highest MaxLeaseIndex at which they have been proposed. 

Fixes #39188.
Fixes #39190.

### CODE REVIEW

**Comment by ajwerner** [comment]
Writing a test to exercise the fourth commit now.

**Review by nvb — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39203)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/storage/replica_application.go, line 173 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39203#-LlAbnk19CaFvODlzJQt:-LlAbnk2C8qu8744r-nA:b9gxaim) ([raw file](https://github.com/cockroachdb/cockroach/blob/27eb92a8dc7e95f1d7f3f664b82106a7f72ed33e/pkg/storage/replica_application.go#L173)):*
> ```Go
> 			// tryReproposeWithNewLeaseIndex). In that case, there's a newer
> 			// version of the proposal in the pipeline, so don't consider this
> 			// entry to have been proposed locally. We entry must necessarily be
> ```

s/We/The/
___
*[pkg/storage/replica_application.go, line 132 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39203#-LlAdk7W77DZSozWrgzR:-LlAdk7XAsJoBJ6k_SVj:bjuea9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/a298e87e609f6735465e0103c884cf5cb794cec7/pkg/storage/replica_application.go#L132)):*
> ```Go
> 		for ok := it.init(&b.cmdBuf); ok; ok = it.next() {
> 			cmd := it.cur()
> 			// Reset the context for already applied commands to ensure that
> ```

I see why the other case is necessary, but why here? Nothing in this batch has applied yet.
___
*[pkg/storage/replica_application.go, line 881 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39203#-LlAdqMP67QORrX5UXyj:-LlAdqMP67QORrX5UXyk:b3ustxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/a298e87e609f6735465e0103c884cf5cb794cec7/pkg/storage/replica_application.go#L881)):*
> ```Go
> 	for ok := it.init(&b.cmdBuf); ok; ok = it.next() {
> 		cmd := it.cur()
> 		// Reset the context for already applied commands to ensure that
> ```

Nice job spotting this issue! It seems like it would also cause problems. I'm fine with this going in without a test for now.

Interestingly, the refactor I'm working on splits applying the side effects of each command in a batch from acknowledging the commands in a batch, so it wouldn't run into this kind of issue. The need for this logic further justifies performing the steps in that order.
___
*[pkg/storage/replica_test.go, line 11561 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39203#-LlAcFirCNBloVMZL22U:-LlAcFit4d3rn12H8v43:b-zasrap) ([raw file](https://github.com/cockroachdb/cockroach/blob/27eb92a8dc7e95f1d7f3f664b82106a7f72ed33e/pkg/storage/replica_test.go#L11561)):*
> ```
> TestReproposalAtLaterIndexDoesNotShareContextWithEarlierReproposal
> ```

Looks like the name changed.
___
*[pkg/storage/replica_test.go, line 11581 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39203#-LlAcYwf4Kx9Qh4RJSqV:-LlAcYwf4Kx9Qh4RJSqW:b2nic71) ([raw file](https://github.com/cockroachdb/cockroach/blob/27eb92a8dc7e95f1d7f3f664b82106a7f72ed33e/pkg/storage/replica_test.go#L11581)):*
> ```Go
> 	tc.manualClock = hlc.NewManualClock(123)
> 	cfg := TestStoreConfig(hlc.NewClock(tc.manualClock.UnixNano, time.Nanosecond))
> 	// Below we saet txnID to the value of the transaction we're going to force to
> ```

set
___
*[pkg/storage/replica_test.go, line 11604 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39203#-LlAd0-k2j7lQQT9pz_g:-LlAd0-lB59yc1IN6fue:bv9lobv) ([raw file](https://github.com/cockroachdb/cockroach/blob/27eb92a8dc7e95f1d7f3f664b82106a7f72ed33e/pkg/storage/replica_test.go#L11604)):*
> ```Go
> 		// Detect the application of the
> 		TestingApplyFilter: func(args storagebase.ApplyFilterArgs) (retry int, pErr *roachpb.Error) {
> 			if !seen && args.CmdID != cmdID {
> ```

Should this be `if seen || args.CmdID != cmdID`?
___
*[pkg/storage/replica_test.go, line 11617 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39203#-LlAd9rG5Sw8BBKTOB97:-LlAd9rG5Sw8BBKTOB98:bddsgw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/27eb92a8dc7e95f1d7f3f664b82106a7f72ed33e/pkg/storage/replica_test.go#L11617)):*
> ```Go
> 			tc.repl.mu.proposalBuf.flushLocked()
> 			// Increase the lease sequence so that future reproposals will fail with
> 			// NotLeaseHolderError.
> ```

"This mimics the outcome of a leaseholder change slipping in between the application of the first proposal and the reproposals."
___
*[pkg/storage/replica_test.go, line 11621 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39203#-LlAdSrLCAoSO1N6KMTG:-LlAdSrMCzt2tjc1YI1F:bmgvehz) ([raw file](https://github.com/cockroachdb/cockroach/blob/27eb92a8dc7e95f1d7f3f664b82106a7f72ed33e/pkg/storage/replica_test.go#L11621)):*
> ```Go
> 			// This return value will force another retry which will carry a yet
> 			// higher MaxLeaseIndex and will trigger our invariant violation.
> 			return 1, roachpb.NewErrorf("forced error that can be reproposed at a higher index")
> ```

`s/1/proposalIllegalLeaseIndex/`?

**Review by ajwerner — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39203#-:-LlC9S569EYAhqu-CTAd:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/replica_application.go, line 132 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39203#-LlAdk7W77DZSozWrgzR:-LlAnrHA9C4eZOQcqVFA:bgidlpt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a298e87e609f6735465e0103c884cf5cb794cec7/pkg/storage/replica_application.go#L132)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I see why the other case is necessary, but why here? Nothing in this batch has applied yet.
</blockquote></details>

Totally isn't.
___
*[pkg/storage/replica_application.go, line 881 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39203#-LlAdqMP67QORrX5UXyj:-LlAwx5T9itX44kDxpXc:b-7gclag) ([raw file](https://github.com/cockroachdb/cockroach/blob/a298e87e609f6735465e0103c884cf5cb794cec7/pkg/storage/replica_application.go#L881)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Nice job spotting this issue! It seems like it would also cause problems. I'm fine with this going in without a test for now.

Interestingly, the refactor I'm working on splits applying the side effects of each command in a batch from acknowledging the commands in a batch, so it wouldn't run into this kind of issue. The need for this logic further justifies performing the steps in that order.
</blockquote></details>

Added a test.

**Comment by ajwerner** [comment]
This is somehow failing
```
*storagepb.RaftCommand: missing fixture! Please adjust belowRaftGoldenProtos if necessary
*storagepb.RaftCommandFooter: missing fixture! Please adjust belowRaftGoldenProtos if necessary
```
but I don't think this PR touches any of the methods where protos are tracked.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r5, 1 of 1 files at r6, 4 of 4 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39203#-:-LlCsqc4AAQhVcD6Oydd:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/storage/replica_raft.go, line 759 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39203#-LlCs0ugD-Q3lGIuFhkH:-LlCs0ugD-Q3lGIuFhkI:b-19l65e) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5465ca1ce898e03a8d5b680c132cfdcc600e9df/pkg/storage/replica_raft.go#L759)):*
> ```
> due to errors
> ```

which are considered fatal.
___
*[pkg/storage/replica_raft.go, line 267 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39203#-LlCsKQR1kc4cklKmE6a:-LlCsKQR1kc4cklKmE6b:bq87vd9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d20f41b6c6b1f1be51ba717dd5af8477d3c29f8/pkg/storage/replica_raft.go#L267)):*
> ```Go
> 	// If an error occurs reset the command's MaxLeaseIndex to its initial value.
> 	// Failure to propose will propagate to the client. An invariant of this
> 	// package is that proposals which are finished carry raft command with a
> ```

commands

**Comment by ajwerner** [comment]
TFTR!

bors r=nvanbenschoten

**Pull request merged**
