### PR TITLE
docs: update import-into diagram

### PR DESCRIPTION
**Pull request by gemma-shay**
Release note: None

### CODE REVIEW

**Comment by gemma-shay** [comment]
@pbardea Do you know what the teamcity error means?

**Comment by pbardea** [comment]
@gemma-shay It looks like the bazel build is failing. It looks like this branch is forked off master from a few months ago. I would suggest to try pulling the latest version of mater and rebasing with:
```
git checkout master
git pull
git checkout import-into-diagram
git rebase master
```

and then pushing the changes again

**Review by pbardea — APPROVED** [review]
The changes LGTM!

Hmm, it looks like the failure is still there after the rebase. I don't think it should be blocking bors, I would try running `bors r+` to see if that merges... I can take another look if bors rejects the change

**Comment by gemma-shay** [comment]
@pbardea Thanks for your help! Will try it.
@lnhsingh for awareness

**Comment by gemma-shay** [comment]
bors r=pbardea

**Pull request merged**
