### PR TITLE
 distsql: initial Sampler implementation

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sqlbase: reservoir sampling implementation

Implementation of reservoir sampling using random sort for EncDatumRows.

#### distsql: initial Sampler implementation

Initial implementation of the Sampler processor. Currently it only samples rows
and does not support any sketches.

See the SQL statistics RFC.

@petermattis / @vivekmenezes  - I'm not sure who should review stats code going forward.

### CODE REVIEW

**Comment by knz** [comment]
Reviewed 2 of 2 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/sampler_test.go, line 83 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/19926#-KyVydlkeUns18KMREY0:-KyVydlkeUns18KMREY1:b-59xi41) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f9454760c61fd29cf415bd85cbbc9c8b3a4267a/pkg/sql/distsqlrun/sampler_test.go#L83)):*
> ```Go
> 		n++
> 	}
> 	if n != k {
> ```

I would suggest a smoke test that the selection is indeed (semi) uniform, e.g. by using a sample size of 3, streaming 100 rows through it, and checking after (say) 10 runs that no single row is selected significantly more or less than 30% of the time, with less than 10% deviation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19926)*

**Comment by knz** [comment]
:lgtm: - but see my comment on the test below.

I'll be willing to review these PRs for the time being, only invoking help from a 3rd person when the concepts truly escape my comprehension.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19926#-:-KyVzGtEO8idYfkmBDgS:b-rquvtw)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/sampler_test.go, line 83 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/19926#-KyVydlkeUns18KMREY0:-KyW5BGXSLfgKmtf_xmD:bq7vqzs) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f9454760c61fd29cf415bd85cbbc9c8b3a4267a/pkg/sql/distsqlrun/sampler_test.go#L83)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I would suggest a smoke test that the selection is indeed (semi) uniform, e.g. by using a sample size of 3, streaming 100 rows through it, and checking after (say) 10 runs that no single row is selected significantly more or less than 30% of the time, with less than 10% deviation.
</blockquote></details>

TFTR! I'll try to work on that. I wanted to do something like that but was afraid it would be flaky. I need to look into a Chernoff bound :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19926)*

**Comment by petermattis** [comment]
:lgtm: for the `SampleReservoir` stuff. I've never looked at distsql processors so it is difficult for me to judge if anything is missing or not idiomatic, though I assume you would know.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19926#-:-KyWFWHHHphIO6k6FHbO:b-ibfn1y)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/distsqlrun/sampler_test.go, line 83 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/19926#-KyVydlkeUns18KMREY0:-KyX0S0Nzjs0r5ptjmLK:bwnu6ok) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f9454760c61fd29cf415bd85cbbc9c8b3a4267a/pkg/sql/distsqlrun/sampler_test.go#L83)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

TFTR! I'll try to work on that. I wanted to do something like that but was afraid it would be flaky. I need to look into a Chernoff bound :)
</blockquote></details>

Done, PTAL. The test seems stable (a few hundred runs) with `numRuns=800`, it should be rock solid with `1000`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19926)*

**Comment by knz** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/distsqlrun/sampler_test.go, line 112 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/19926#-KyX4FOjcfh7aNw95xjK:-KyX4FOkS8FeK-bQnsNB:b-hf8l2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/523e3a52db607e4b2d95be6d3420dfaeb0655dce/pkg/sql/distsqlrun/sampler_test.go#L112)):*
> ```Go
> 	// Verify that no frequency is outside of the range (f / (1+delta), f * (1+delta));
> 	// the probability of a given row violating this is subject to the Chernoff
> 	// bound which decreases exponentially (with exponent f).
> ```

Yeah, very nice. :beers: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19926#-:-KyX4Hn9reXj3waP6lEq:b-uwkowd)*

**Comment by knz** [comment]
Reviewed 7 of 7 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19926)*

**Pull request merged**
