### PR TITLE
workload,storageccl: add a read-only ExportStorage impl for workload

### PR DESCRIPTION
**Pull request by danhhz**
Initially, we built fixtures by writing CSVs to cloud storage and
running IMPORT. Then mjibson had the brilliant idea of writing an http
server (`./workload csv-server`) and using it with IMPORT's http
support. Now that workload is part of the cockroach binary, we can go
one step further and eliminate the http server.

BACKUP, RESTORE, and IMPORT use an abstraction over the storage of
various cloud providers, called ExportStorage. It also supports http,
which is how the above `./workload csv-server` worked. This commit adds
a new read-only ExportStorage implementation that wraps workload.

Each "file" is a part of a table in a workload generator. The paths look
like:

    experimental-workload:///csv/<generator>/<table>?params

The params include any flags for the specific generator as well as
"row-start", "row-end", and "version". If "row-start" or "row-end" are
omitted, they default to the beginning or end of the table. This is all
identical to the paths served by `workload csv-server`.

"version" would be more natural as part of the path, but it is a param
so that this is a drop in replacement for csv-server. It is checked by
each instance of the ExportStorage against the local copy of the
requested generator. This prevents a rolling cockroach upgrade from
creating inconsistent data if the fixture's implementation has changed.

Benchmark for the io.Reader powering the ExportStorage:

    name             time/op
    CSVRowsReader-8   15.1µs ± 1%

    name             speed
    CSVRowsReader-8  103MB/s ± 8%

    name             alloc/op
    CSVRowsReader-8   6.96kB ± 0%

    name             allocs/op
    CSVRowsReader-8     45.0 ± 0%

This is fast enough that for small fixtures it's faster than restoring a
precomptued fixture (because the download dominates). This is especially
pronounced over slow connections.

Some top level performance numbers. "fixtures import" runs a full IMPORT
with experimental-workload. "fixtures load" simply RESTORES a
precomputed backup. Run on 3 n1-standard-8 nodes. (Note: the "fixtures
import" numbers are probably similar with "workload csv-server", but
this is dramatically simpler operationally.)

    fixtures import tpcc --warehouses=100  5m48s
    fixtures load   tpcc --warehouses=100  7m41s
    fixtures import tpcc --warehouses=1000 62m
    fixtures load   tpcc --warehouses=1000 51m-56m

So it seems that for larger fixtures, the overhead of IMPORT (converting
the data twice to sample, distributed sort) dominates, but at tpcc-1000
it's still within ~10%. Doesn't look like we can entirely retire
fixtures just yet.

Once we're comfortable with this, we could delete csv server entirely
(and maybe clean up the paths a bit). We almost certainly can't backport
this into 2.1, so we may need to keep it around for a bit in case we
need to create 2.1 fixtures. Additionally, we could use it instead of
`workload.Setup` to implement `workload init` and `workload run --init`.

Release note: None

### CODE REVIEW

**Review by benesch — APPROVED** [review]
:lgtm_strong:

It occurs to me that we still have a kind of silly overhead of converting a bunch of datums to CSV just to convert them right back to datums. Oh well. That seems kind of hard to fix. Maybe one day we'll have a binary format for IMPORT that avoids most of the overhead.

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31899#-:-LQ-L6EY24N5yxIVvaDD:bappn8c)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/ccl/storageccl/export_storage.go, line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31899#-LQ-JbTI9E9i0_zonJVx:-LQ-JbTI9E9i0_zonJVy:b2aav9s) ([raw file](https://github.com/cockroachdb/cockroach/blob/727c7a8f9065fce468f07595deeb4f6e2ef35779/pkg/ccl/storageccl/export_storage.go#L214)):*
> ```Go
> 				"experimental-workload requires all nodes to be upgraded to %s",
> 				cluster.VersionByKey(cluster.VersionExportStorageWorkload))
> 		}
> ```

I think you can use `if err := settings.Version.CheckVersion(cluster.VersionExportStorageWorkload, "experimental-workload"); err != nil { return err }` to avoid reinventing the error message.
___
*[pkg/ccl/storageccl/export_storage.go, line 861 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31899#-LQ-KK4s302YClz5x5dj:-LQ-KK4s302YClz5x5dk:b-dpx1yd) ([raw file](https://github.com/cockroachdb/cockroach/blob/727c7a8f9065fce468f07595deeb4f6e2ef35779/pkg/ccl/storageccl/export_storage.go#L861)):*
> ```Go
> 	q := uri.Query()
> 	c.Version = q.Get(`version`)
> 	q.Del(`version`)
> ```

Is it safe for c.Version to be the empty string?
___
*[pkg/settings/cluster/cockroach_versions.go, line 306 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31899#-LQ-Io6Y1iManHqmbhh1:-LQ-Io6Y1iManHqmbhh2:b-4pfqqw) ([raw file](https://github.com/cockroachdb/cockroach/blob/727c7a8f9065fce468f07595deeb4f6e2ef35779/pkg/settings/cluster/cockroach_versions.go#L306)):*
> ```Go
> 	},
> 	{
> 		// VersionExportStorageWorkload is WIP.
> ```

Looks like you meant to fill in this comment.
___
*[pkg/workload/bank/bank.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31899#-LQ-J6cQ6SaOhZU1j0nD:-LQ-J6cQ6SaOhZU1j0nE:b4tyao) ([raw file](https://github.com/cockroachdb/cockroach/blob/b720b8b3b95bb562021cab7ecb471a4f56dd2d0a/pkg/workload/bank/bank.go#L88)):*
> ```Go
> 	}
> 	b := bankMeta.New().(*bank)
> 	b.seed = timeutil.Now().UnixNano()
> ```

Assuming this is to remove some randomness that was making tests flaky? Are there other callers that are going to be affected by this?

**Review by danhhz — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31899#-:-LQ-hm3x5b0C_39AryH-:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/ccl/storageccl/export_storage.go, line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31899#-LQ-JbTI9E9i0_zonJVx:-LQ-aIsrAWtnR10DnwRY:bdr0ka8) ([raw file](https://github.com/cockroachdb/cockroach/blob/727c7a8f9065fce468f07595deeb4f6e2ef35779/pkg/ccl/storageccl/export_storage.go#L214)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I think you can use `if err := settings.Version.CheckVersion(cluster.VersionExportStorageWorkload, "experimental-workload"); err != nil { return err }` to avoid reinventing the error message.
</blockquote></details>

TIL Done
___
*[pkg/ccl/storageccl/export_storage.go, line 861 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31899#-LQ-KK4s302YClz5x5dj:-LQ-c8uLBj7bG8fNa4P1:bs5mi1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/727c7a8f9065fce468f07595deeb4f6e2ef35779/pkg/ccl/storageccl/export_storage.go#L861)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Is it safe for c.Version to be the empty string?
</blockquote></details>

I went back and forth on this. If we disallow the empty string, then workloads with no version set are impossible to use with this. We really shouldn't have any those, but it seems overly restrictive to break them. Decided to error if the parameter is unset, but allow it to be set to empty string.

Update: this caught a bug in csvServerPaths :clap:
___
*[pkg/settings/cluster/cockroach_versions.go, line 306 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31899#-LQ-Io6Y1iManHqmbhh1:-LQ-bID1DLW3IfPPbAge:b-qm8v83) ([raw file](https://github.com/cockroachdb/cockroach/blob/727c7a8f9065fce468f07595deeb4f6e2ef35779/pkg/settings/cluster/cockroach_versions.go#L306)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Looks like you meant to fill in this comment.
</blockquote></details>

Ah, thanks. Didn't have a PR number until I pushed and forgot to update.
___
*[pkg/workload/bank/bank.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31899#-LQ-J6cQ6SaOhZU1j0nD:-LQ-bOTP7NAVhACShKbZ:b-kr64v0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b720b8b3b95bb562021cab7ecb471a4f56dd2d0a/pkg/workload/bank/bank.go#L88)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Assuming this is to remove some randomness that was making tests flaky? Are there other callers that are going to be affected by this?
</blockquote></details>

The initial data for workloads is supposed to be deterministic given an initial set of flags (otherwise basically any distributed way of making fixtures doesn't work). There's a test that checks each registered workload, but FromConfig and FromRows are special snowflakes. I probably should rewrite them to just take flags, but I'll leave that for later.

**Comment by danhhz** [comment]
bors r=benesch

**Comment by nvanbenschoten** [comment]
Awesome job with this @danhhz! Are you planning on backporting to 2.1.1?

**Comment by danhhz** [comment]
I'd love to, but can I? It has a cluster setting and is definitely a new feature, so dunno if it fits the backport criteria.

**Comment by benesch** [comment]
Yeah, definitely can't backport something with a cluster setting. (We could
make it work if we really, really had to, but we're trying really hard to
not ever cross that bridge.)

**Pull request merged**
