### PR TITLE
UI: add "rocksdb.estimate-table-readers-mem" to graphs.

### PR DESCRIPTION
**Pull request by mberhault**
This metric increases with the number of keys in rocksdb and can become
a sizeable chunk of the allocated memory (eg: ~50% of cgo memory in
the beta cluster)

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7228)

### CODE REVIEW

**Comment by mberhault** [comment]
circleci will probably fail on differing embedded.go again.

**Comment by mberhault** [comment]
Ok, while I'm trying to figure out exactly what went wrong, I grabbed the `embedded.go` generated by circleci. The only differences are the locations in the file of the `woff` stuff.

**Comment by mrtracy** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7228#-:-KKJjGq5-uSrCLJWu04v:1417088721)*

**Comment by tamird** [comment]
LGTM

**Pull request merged**
