### PR TITLE
rpc,server: simplify the constructor for the internal client adapter

### PR DESCRIPTION
**Pull request by knz**
Only the last commit belongs to this PR. The others are from #96153.
Epic: CRDB-14537

The rpc.Context already knows its client tenant ID. We can use that
instead of an extra argument to `SetLocalInternalServer()`

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96494)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/rpc/context.go` line 748 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96494#-NNN4sjw2pygsGDEXp7T:-NNN4sjw2pygsGDEXp7U:bv4iyej) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb108ee19bb0d58aa577c4fd05a610394a1bbca3/pkg/rpc/context.go#L748)):*
> ```Go
> 	server roachpb.InternalServer,
> 	clientTenantID roachpb.TenantID,
> 	separateTracers bool,
> ```

do we really need the caller to figure out this `separateTracers` business? I don't think it makes much sense to the caller. Can the `InternalClientAdapter` figure it out internally?
___
*[`pkg/rpc/context.go` line 1475 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96494#-NNN3zvQ7wb4ZV-AHFtC:-NNN3zvQ7wb4ZV-AHFtD:b-753vtd) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb108ee19bb0d58aa577c4fd05a610394a1bbca3/pkg/rpc/context.go#L1475)):*
> ```Go
> 	clientTenantID := rpcCtx.TenantID
> 	separateTracers := false
> 	if rpcCtx.TenantID.IsSet() && !rpcCtx.TenantID.IsSystem() {
> ```

is the difference between `TenantID.IsSet()` and `!IsSet()` meaningful? Can we make it such that the tenant ID is always set (by setting it to the system tenant here, if the caller cannot do it)? I think it'd be good to eliminate this ambiguity.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96494)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[`pkg/rpc/context.go` line 748 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96494#-NNN4sjw2pygsGDEXp7T:-NNN5bkXDPYUczkmJu9A:bdrctg7) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb108ee19bb0d58aa577c4fd05a610394a1bbca3/pkg/rpc/context.go#L748)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

do we really need the caller to figure out this `separateTracers` business? I don't think it makes much sense to the caller. Can the `InternalClientAdapter` figure it out internally?
</blockquote></details>

I've decided as follows:
- the internal client adapter struct (and this constructor) remain dumb and need to be told
- SetLocalInternalServer is where we make a choice
- nothing else needs to know
___
*[`pkg/rpc/context.go` line 1475 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96494#-NNN3zvQ7wb4ZV-AHFtC:-NNN5ky3-4sI3xj2RQMb:b-kl4gxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb108ee19bb0d58aa577c4fd05a610394a1bbca3/pkg/rpc/context.go#L1475)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

is the difference between `TenantID.IsSet()` and `!IsSet()` meaningful? Can we make it such that the tenant ID is always set (by setting it to the system tenant here, if the caller cannot do it)? I think it'd be good to eliminate this ambiguity.
</blockquote></details>

Yes! I agree. Unfortunately, there's quite a few refactors to get there (we have several code paths elsewhere that _require_ rpcCtx.TenantID to not be set to mean "system tenant") so I would prefer to do this in a separate PR.

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96494#-:-NNN9Z4v89BsSAQrdAef:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by knz** [comment]
TFYR!

bors r=andreimatei

**Pull request merged**
