### PR TITLE
log: add crash reporting to panic handler

### PR DESCRIPTION
**Pull request by dt**

### CODE REVIEW

**Comment by petermattis** [comment]
Only skimmed the change, but I'm very happy to see this going in.

**Comment by dt** [comment]
https://github.com/cockroachlabs/registration/pull/42 should probably get merged and deployed before this goes in (I already pointed errors.cockroachdb.com at it).

**Comment by dt** [comment]
Ugh, looks like either need to fork raven and fix its stacks collector to not import go/build, or relax that linter for now.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15393#-:-KijosT_i0B9LPr48lPn:bt1m10j)*

**Comment by dt** [comment]
@tamird: how strongly do you feel about the ban on go/build? This crash reporter library is incorrectly uses it to strip GOPATH prefix from stack frames. Obviously ideal in the longer term would be to fix it upstream, similar to how we do it, but is it worth getting _something_ in now, even if it doesn't tidy up stacks the way we want? Are there other runtime concerns with having go/build linked?

**Comment by tamird** [comment]
I don't remember the original reason for excluding `go/build`. If the fix
upstream is trivial, I'd suggest you fork for now - it's a bit cumbersome
but I'm uneasy about allowing other regressions in the name of (a few
hours') expedience here.

If the fix upstream isn't trivial, go ahead and remove the ban.

**Comment by bdarnell** [comment]
LGTM

Removing the ban is fine with me; I think the only reason for it was vague concern about binary size. (We were accidentally linking `go/build` into release binaries when we were only using it for testing)

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/util/log/stderr_redirect.go, line 94 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15393#-Kik24r-YtDYrE-GapRL:-Kik24r-YtDYrE-GapRM:b-3ije0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/5edab174c734cd5223d6cb827aa6b4e4c6260e1e/pkg/util/log/stderr_redirect.go#L94)):*
> ```Go
> 
> var crashReports = settings.RegisterBoolSetting(
> 	"diagnostics.crash_reports.enabled",
> ```

Users shouldn't have to track a potentially-changing set of settings to disable reporting. There should be one setting that disables everything that phones home (and then maybe other settings for different kinds of reporting, but I'm not sure if we even need that right now). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15393#-:-Kik2KfJ9n6GyqgXgSbb:b-phtugo)*

**Comment by benesch** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/server/updates.go, line 241 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15393#-KijePD4fGGs3ual97ur:-KijePD4fGGs3ual97us:b-82ig6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/43991d305ceb7b2950b25e9da71d0ac7b02edea2/pkg/server/updates.go#L241)):*
> ```Go
> 		s.reportDiagnostics()
> 	}
> ```

Unintentional?

---

*[pkg/util/log/stderr_redirect.go, line 109 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15393#-KijefmYb02VJBPuPcsR:-KijefmYb02VJBPuPcsS:by0amr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5edab174c734cd5223d6cb827aa6b4e4c6260e1e/pkg/util/log/stderr_redirect.go#L109)):*
> ```Go
> 
> 	if cmd == "start" {
> 		cmd = "server"
> ```

This is just preference, right?

---

*[pkg/util/log/stderr_redirect.go, line 113 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15393#-Kijir_q4KjEqMCxggVX:-Kijir_q4KjEqMCxggVY:b-52wlf2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5edab174c734cd5223d6cb827aa6b4e4c6260e1e/pkg/util/log/stderr_redirect.go#L113)):*
> ```Go
> 	info := build.GetInfo()
> 	raven.SetRelease(info.Tag)
> 	raven.SetEnvironment(cmd)
> ```

I feel like this should be a tag, since environment in Sentry-land usually means `staging`, `production`, `development`, etc. Unless there's something specific about the UI that makes this useful?

---

*[pkg/util/log/stderr_redirect.go, line 130 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15393#-Kik6HBTMPIQPp-8XjxF:-Kik6HBTMPIQPp-8XjxG:b-orfx86) ([raw file](https://github.com/cockroachdb/cockroach/blob/5edab174c734cd5223d6cb827aa6b4e4c6260e1e/pkg/util/log/stderr_redirect.go#L130)):*
> ```Go
> 		Shout(ctx, Severity_ERROR, "Reported as error "+id)
> 	}
> }
> ```

This feels like it should live somewhere other than `stderr_redirect.go`, but don't let that hold up the PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15393)*

**Comment by dt** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/util/log/stderr_redirect.go, line 94 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15393#-Kik24r-YtDYrE-GapRL:-Kik78oPxRuxL21oikle:b-kvas1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/5edab174c734cd5223d6cb827aa6b4e4c6260e1e/pkg/util/log/stderr_redirect.go#L94)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Users shouldn't have to track a potentially-changing set of settings to disable reporting. There should be one setting that disables everything that phones home (and then maybe other settings for different kinds of reporting, but I'm not sure if we even need that right now). 
</blockquote></details>

I was thinking that crash reports were different from our periodic collection and upload diagnostics info?

At least I'd expect some users will object to the collection of usage info but might be okay with crash reports.

---

*[pkg/util/log/stderr_redirect.go, line 109 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15393#-KijefmYb02VJBPuPcsR:-Kik7EUy378L3lkGdqo8:b-eqtu0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/5edab174c734cd5223d6cb827aa6b4e4c6260e1e/pkg/util/log/stderr_redirect.go#L109)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This is just preference, right?
</blockquote></details>

Yep. Don't like it?

---

*[pkg/util/log/stderr_redirect.go, line 113 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15393#-Kijir_q4KjEqMCxggVX:-Kik7QRqeXLjzd_hMMP7:bs7wumb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5edab174c734cd5223d6cb827aa6b4e4c6260e1e/pkg/util/log/stderr_redirect.go#L113)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I feel like this should be a tag, since environment in Sentry-land usually means `staging`, `production`, `development`, etc. Unless there's something specific about the UI that makes this useful?
</blockquote></details>

Done.

---

*[pkg/util/log/stderr_redirect.go, line 130 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15393#-Kik6HBTMPIQPp-8XjxF:-KikPtiTWKY1OLYb32Qb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5edab174c734cd5223d6cb827aa6b4e4c6260e1e/pkg/util/log/stderr_redirect.go#L130)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This feels like it should live somewhere other than `stderr_redirect.go`, but don't let that hold up the PR.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15393)*

**Comment by dt** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/server/updates.go, line 241 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15393#-KijePD4fGGs3ual97ur:-KikSKcYtOaHPUqruzCv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/43991d305ceb7b2950b25e9da71d0ac7b02edea2/pkg/server/updates.go#L241)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Unintentional?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15393)*

**Comment by benesch** [comment]
Reviewed 2 of 6 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/util/log/stderr_redirect.go, line 109 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15393#-KijefmYb02VJBPuPcsR:-KikVvmvAf0UGXcqiD5L:bjirr6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/5edab174c734cd5223d6cb827aa6b4e4c6260e1e/pkg/util/log/stderr_redirect.go#L109)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Yep. Don't like it?
</blockquote></details>

No opinion! Just checking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15393)*

**Comment by knz** [comment]
+1 on the use of raven.

But panics leak SQL query details. This must be taken care of before this merges.

---

Reviewed 2 of 6 files at r1, 5 of 6 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/util/log/stderr_redirect.go, line 94 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15393#-Kik24r-YtDYrE-GapRL:-Kil1HZz_jPq6HP9ROj5:b-kzbwmi) ([raw file](https://github.com/cockroachdb/cockroach/blob/5edab174c734cd5223d6cb827aa6b4e4c6260e1e/pkg/util/log/stderr_redirect.go#L94)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I was thinking that crash reports were different from our periodic collection and upload diagnostics info?

At least I'd expect some users will object to the collection of usage info but might be okay with crash reports.
</blockquote></details>

First of all in the same way you did `if log.DiagnosticsReportingEnabled.Get() && diagnosticsMetricsEnabled.Get() {` above I would strongly suggest `if DiagnosticsReportingEnabled.Get() && panicReportingEnabled.Get()` here. 

As the code now is, I think it is more likely that users will share their metrics with us than their panic details.

Here's why: panics in SQL world currently leak the full text of the query that caused the panic.
I'm ok with a separate setting but we must absolutely document both in the same place and highlight that both may leak query data to us. I suspect some users will be more eager to disable this one  than the metrics one.
Alternatively we could define a way to scrub the SQL query text away from the panic details sent to our reg server. Not exactly sure how to get about that but I suspect some combination with #15392 is possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15393#-:-Kil2Y593VRV4yIUVtUO:bm4hlee)*

**Comment by dt** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/util/log/stderr_redirect.go, line 94 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15393#-Kik24r-YtDYrE-GapRL:-KilD7O2IfN1BLbbtgDp:bf6cbxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5edab174c734cd5223d6cb827aa6b4e4c6260e1e/pkg/util/log/stderr_redirect.go#L94)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

First of all in the same way you did `if log.DiagnosticsReportingEnabled.Get() && diagnosticsMetricsEnabled.Get() {` above I would strongly suggest `if DiagnosticsReportingEnabled.Get() && panicReportingEnabled.Get()` here. 

As the code now is, I think it is more likely that users will share their metrics with us than their panic details.

Here's why: panics in SQL world currently leak the full text of the query that caused the panic.
I'm ok with a separate setting but we must absolutely document both in the same place and highlight that both may leak query data to us. I suspect some users will be more eager to disable this one  than the metrics one.
Alternatively we could define a way to scrub the SQL query text away from the panic details sent to our reg server. Not exactly sure how to get about that but I suspect some combination with #15392 is possible.


</blockquote></details>

Where is 'here' ? reviewable is not making it clear.
I'd love to scrub them -- I'll default it to false here until we do though. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15393)*

**Comment by knz** [comment]
:lgtm: if the crash report default is false until it's coupled with #15392 or similar.

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/util/log/stderr_redirect.go, line 94 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15393#-Kik24r-YtDYrE-GapRL:-KilF2mAo8wlDF3kIlAT:b96d43h) ([raw file](https://github.com/cockroachdb/cockroach/blob/5edab174c734cd5223d6cb827aa6b4e4c6260e1e/pkg/util/log/stderr_redirect.go#L94)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Where is 'here' ? reviewable is not making it clear.
I'd love to scrub them -- I'll default it to false here until we do though. 
</blockquote></details>

This was the intended context: `if DiagnosticsReportingEnabled.Get() && crashReports.Get() {`
But now I'm pasting it I see there are already two settings, so just ignore that part of my comment.

+1 on the default.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15393#-:-KilFBGKI26uHS2J3Bkr:biqzog)*

**Comment by dt** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/util/log/stderr_redirect.go, line 94 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15393#-Kik24r-YtDYrE-GapRL:-KilFxCp7PyXtiTH2gOH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5edab174c734cd5223d6cb827aa6b4e4c6260e1e/pkg/util/log/stderr_redirect.go#L94)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This was the intended context: `if DiagnosticsReportingEnabled.Get() && crashReports.Get() {`
But now I'm pasting it I see there are already two settings, so just ignore that part of my comment.

+1 on the default.

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15393)*

**Comment by dt** [comment]
Okay, default flipped, `Fatal` hooked up, race in raven commented out, and RFAL.
Also, reg-server deployed with the proxy, so this is good to merge when people are happy.

---

Review status: 6 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15393#-:-KilTlCSeRnWWBJj7LPS:bzfgas4)*

**Comment by knz** [comment]
:lgtm: 

---

Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15393#-:-KilUTRxqz_1--CSRSIs:bg7igkv)*

**Pull request merged**
