### PR TITLE
sql: Improve casting behavior for arrays

### LINKED ISSUE #21590: sql: typing of null arrays seems off
Not sure what's going on here, but it doesn't seem right.

```
root@:26257/firehose> select array[NULL]::string[];
pq: invalid cast: NULL[] -> STRING[]
root@:26257/firehose> select nullif(array_agg(a), '{NULL}'::string[]) from foo;
pq: NULLIF("$0", ARRAY[NULL]): incompatible NULLIF expressions: expected ARRAY[NULL] to be of type string[], found type NULL[]
```

Postgres:

```
benesch=# select array[NULL]::text[];
 array  
--------
 {NULL}
(1 row)

benesch=# select nullif(array_agg(a), '{NULL}') from foo;
 nullif 
--------
 
(1 row)

benesch=# select nullif(array_agg(a), '{NULL}'::text[]) from foo;
 nullif 
--------
 
(1 row)
```

### PR DESCRIPTION
**Pull request by abhimadan**
Previously, casting an array to another array type would only work if
the pre-cast and post-cast param types were the same; for example,
ARRAY[1]::INT[] would work, and ARRAY[NULL]::INT[] would fail.

To fix this, we now cast each individual element in the array to the
post-cast param type.

Fixes #21590.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
Nice change!

But you're much underselling the work here. This change allows *any* cast from any item type to any other item type? 

There are a couple things that attract my attention:

1) this needs many more tests: it's not just `array[null]::string[]` that works; it's also `array[1,2,3]::string[]`, `array['1','2','3']::int[], etc. These need to be exercised as well.

2) whether a cast is valid or not should not be tested during Eval, but during `TypeCheck` instead. The `TypeCheck` method for `CastExpr` must be extended to verify that a cast from one element type to the other is indeed valid.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/sem/tree/eval.go, line 2553 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22338#-L4NN1xpHomrQPLO8yNb:-L4NN1xpHomrQPLO8yNc:b-7wilk8) ([raw file](https://github.com/cockroachdb/cockroach/blob/541493f697d8e12e78fe9c9b861de6f8949e4678/pkg/sql/sem/tree/eval.go#L2553)):*
> ```Go
> 			res = &v.DInt
> 		}
> 		if res != nil {
> ```

Curious: What is this change? Which test exercises it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22338#-:-L4NLkfyjK60g0zAJiLO:bi5s20y)*

**Comment by knz** [comment]
Also this commits needs a release note!!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22338#-:-L4NNUvzj3MN0uGwqoyG:bverq5b)*

**Comment by abhimadan** [comment]
TFTR @knz! I've improved the type checking for `CastExpr` to handle arrays better, and added some more tests. I felt that adding more logic tests was redundant in this case, but it might be good to add some tests to `type_check_test.go` -- I'm currently looking into that.

I also added a release note. The comment I removed from the logic test implies that the original behaviour was an intentional stopgap, so I'm not marking it as a bug fix (though it's probably not a big deal either way).

---

Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/sem/tree/eval.go, line 2553 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22338#-L4NN1xpHomrQPLO8yNb:-L4NfwEK4WOS__UbpS4G:b-m93fph) ([raw file](https://github.com/cockroachdb/cockroach/blob/541493f697d8e12e78fe9c9b861de6f8949e4678/pkg/sql/sem/tree/eval.go#L2553)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Curious: What is this change? Which test exercises it?
</blockquote></details>

There was a test that tried a`int[] -> inet[]` cast, and verified that it didn't work. This error was originally caught by the array branch in `performCast` (so it didn't stop at type checking), but after recursively calling `performCast`, the `inet` went through all int cases without hitting any of them, which left `res == nil`.

This error never came up before since it would have been caught by type checking if one tried, for instance, a `int -> inet` cast. After the type checking improvements I added, this branch is no longer hit, but I think it's probably better to have this check here regardless.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22338#-:-L4NfcP8EXLrvXLjaa3H:b-aks6gz)*

**Comment by abhimadan** [comment]
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/sem/tree/eval.go, line 2553 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22338#-L4NN1xpHomrQPLO8yNb:-L4NmGwV4EADIKp2xr8B:bqiwafy) ([raw file](https://github.com/cockroachdb/cockroach/blob/541493f697d8e12e78fe9c9b861de6f8949e4678/pkg/sql/sem/tree/eval.go#L2553)):*
<details><summary><i>Previously, abhimadan (Abhishek Madan) wrote…</i></summary><blockquote>

There was a test that tried a`int[] -> inet[]` cast, and verified that it didn't work. This error was originally caught by the array branch in `performCast` (so it didn't stop at type checking), but after recursively calling `performCast`, the `inet` went through all int cases without hitting any of them, which left `res == nil`.

This error never came up before since it would have been caught by type checking if one tried, for instance, a `int -> inet` cast. After the type checking improvements I added, this branch is no longer hit, but I think it's probably better to have this check here regardless.
</blockquote></details>

To elaborate a bit more: the array casting case (and AFAICT, anything that calls this function) expects `res` to be non-nil, so having both `res` and `err` be nil ended up adding nil elements to the newly created `DArray` (in the array casting eval code). Accessing these elements later caused a nil pointer dereference.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22338)*

**Comment by knz** [comment]
Thanks for the change.

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/sem/tree/eval.go, line 2553 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22338#-L4NN1xpHomrQPLO8yNb:-L4NrDLHEYzlMjeP9sjE:b-csimwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/541493f697d8e12e78fe9c9b861de6f8949e4678/pkg/sql/sem/tree/eval.go#L2553)):*
<details><summary><i>Previously, abhimadan (Abhishek Madan) wrote…</i></summary><blockquote>

To elaborate a bit more: the array casting case (and AFAICT, anything that calls this function) expects `res` to be non-nil, so having both `res` and `err` be nil ended up adding nil elements to the newly created `DArray` (in the array casting eval code). Accessing these elements later caused a nil pointer dereference.
</blockquote></details>

If you revert this specific change, leaving your other changes in place (especially the type checking code), what tests would break?

---

*[pkg/sql/sem/tree/eval.go, line 2843 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22338#-L4NrQ6ACaOdKslhlGfM:-L4NrQ6BCTlwNV59IWY9:b5wobzo) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fff7b981ddb3c73e6ea362ab2094fba69d2063b/pkg/sql/sem/tree/eval.go#L2843)):*
> ```Go
> 			paramType := coltypes.CastTargetToDatumType(typ.ParamType)
> 			if v.ParamTyp == paramType {
> 				return d, nil
> ```

This optimization should be done during type checking: the cast should be elided entirely.

---

*[pkg/sql/sem/tree/expr.go, line 1296 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22338#-L4NreV43v_ludNXVDHi:-L4NreV43v_ludNXVDHj:b-5swl9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fff7b981ddb3c73e6ea362ab2094fba69d2063b/pkg/sql/sem/tree/expr.go#L1296)):*
> ```Go
> 			return stringCastTypes
> 		} else if t.FamilyEqual(types.FamArray) {
> 			paramCastTypes := validCastTypes(t.(types.TArray).Typ)
> ```

I'm not fond of this expansion. See below

---

*[pkg/sql/sem/tree/type_check.go, line 314 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22338#-L4Nrssg4fYnx0C228vE:-L4Nrssg4fYnx0C228vF:bcehpeg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fff7b981ddb3c73e6ea362ab2094fba69d2063b/pkg/sql/sem/tree/type_check.go#L314)):*
> ```Go
> 	castFrom := typedSubExpr.ResolvedType()
> 
> 	for _, t := range validCastTypes(returnType) {
> ```

Change this loop so that there is just 1 call to `isCastDeepValid` and `validCastTypes` is only called for non-array "leaf" types.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22338#-:-L4Ns0zb7biITrcnnzVu:b-fpbdoa)*

**Comment by abhimadan** [comment]
Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/sql/sem/tree/eval.go, line 2553 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22338#-L4NN1xpHomrQPLO8yNb:-L4ODMK96_2oMDkA5UvR:bt1cb8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/541493f697d8e12e78fe9c9b861de6f8949e4678/pkg/sql/sem/tree/eval.go#L2553)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

If you revert this specific change, leaving your other changes in place (especially the type checking code), what tests would break?
</blockquote></details>

Nothing fails if I remove this. However, I think that it's useful to have this check, because if someone else makes the same mistake I did of inadvertently adding `DInt`s containing nil values to a `DArray`, the bug will manifest as an non-nil error rather than a far-removed nil pointer dereference. I removed it from this PR since it's no longer relevant to the rest of the work in this PR, but I'm planning on adding it in a separate PR.

---

*[pkg/sql/sem/tree/eval.go, line 2843 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22338#-L4NrQ6ACaOdKslhlGfM:-L4OEDuH3-1gtd9_nBSn:baaeaks) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fff7b981ddb3c73e6ea362ab2094fba69d2063b/pkg/sql/sem/tree/eval.go#L2843)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This optimization should be done during type checking: the cast should be elided entirely.
</blockquote></details>

I found it suspicious that an optimization like this wasn't already in `CastExpr.TypeCheck` for other cast types (for example, we have tests like `(1.2::decimal)::decimal` where the expected result is `1.2:::decimal::decimal::decimal` instead of just `1.2:::decimal`), and it turns out this check is incorrect. For example, `ARRAY['hello','world']::char(2)[]` returns `ARRAY['hello','world']` instead of `ARRAY['he','wo']`. I didn't look too deeply, but it seems like `char(n)` is aliased to the `String` type internally, which doesn't have a length parameter, and as a result, attempting to elide this cast during type checking can elide the truncation.

I've removed the check and added a unit test for the example I gave above.

---

*[pkg/sql/sem/tree/expr.go, line 1296 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22338#-L4NreV43v_ludNXVDHi:-L4OFvaqECMiCjmBnJuP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fff7b981ddb3c73e6ea362ab2094fba69d2063b/pkg/sql/sem/tree/expr.go#L1296)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'm not fond of this expansion. See below
</blockquote></details>

Done.

---

*[pkg/sql/sem/tree/type_check.go, line 314 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22338#-L4Nrssg4fYnx0C228vE:-L4OFzF1DqPHLqptqvZr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fff7b981ddb3c73e6ea362ab2094fba69d2063b/pkg/sql/sem/tree/type_check.go#L314)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Change this loop so that there is just 1 call to `isCastDeepValid` and `validCastTypes` is only called for non-array "leaf" types.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22338)*

**Comment by knz** [comment]
:lgtm: but you can add your little additional check as an extra commit if you want.

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/sem/tree/eval.go, line 2553 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22338#-L4NN1xpHomrQPLO8yNb:-L4RZAAU6jv0YtbyZw4v:b-865ja0) ([raw file](https://github.com/cockroachdb/cockroach/blob/541493f697d8e12e78fe9c9b861de6f8949e4678/pkg/sql/sem/tree/eval.go#L2553)):*
<details><summary><i>Previously, abhimadan (Abhishek Madan) wrote…</i></summary><blockquote>

Nothing fails if I remove this. However, I think that it's useful to have this check, because if someone else makes the same mistake I did of inadvertently adding `DInt`s containing nil values to a `DArray`, the bug will manifest as an non-nil error rather than a far-removed nil pointer dereference. I removed it from this PR since it's no longer relevant to the rest of the work in this PR, but I'm planning on adding it in a separate PR.
</blockquote></details>

A separate commit in this PR would be fine by me.

---

*[pkg/sql/sem/tree/eval.go, line 2843 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22338#-L4NrQ6ACaOdKslhlGfM:-L4RZEte6G7zQhj8M6tx:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fff7b981ddb3c73e6ea362ab2094fba69d2063b/pkg/sql/sem/tree/eval.go#L2843)):*
<details><summary><i>Previously, abhimadan (Abhishek Madan) wrote…</i></summary><blockquote>

I found it suspicious that an optimization like this wasn't already in `CastExpr.TypeCheck` for other cast types (for example, we have tests like `(1.2::decimal)::decimal` where the expected result is `1.2:::decimal::decimal::decimal` instead of just `1.2:::decimal`), and it turns out this check is incorrect. For example, `ARRAY['hello','world']::char(2)[]` returns `ARRAY['hello','world']` instead of `ARRAY['he','wo']`. I didn't look too deeply, but it seems like `char(n)` is aliased to the `String` type internally, which doesn't have a length parameter, and as a result, attempting to elide this cast during type checking can elide the truncation.

I've removed the check and added a unit test for the example I gave above.
</blockquote></details>

Thanks!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22338#-:-L4RZU6qDAcXsbKzlWvb:bcjkwe0)*

**Pull request merged**
