### PR TITLE
protobuf: upgrade to 3.6.0

### PR DESCRIPTION
**Pull request by mberhault**
Changelog is at https://github.com/google/protobuf/releases/tag/v3.6.0

Rename `ValueType::NULL` enum value to `NULL_`. The 3.6 cpp generator
stopped rewriting `NULL` as `NULL_`.

Release note (build change): upgrade protobuf to 3.6.0

### CODE REVIEW

**Comment by mberhault** [comment]
We probably don't have to re-add `NULL` as an exception. The only field breaking this is `roachpb/data.proto:ValueType:NULL`: https://github.com/cockroachdb/cockroach/blob/master/pkg/roachpb/data.proto#L50

I tried reverting the protobuf change and renaming the field in data.proto to `NULL_`, and things seem happy (seem being the operative word).

@danhhz: you added the `NULL` `ValueType` enum value in https://github.com/cockroachdb/cockroach/commit/865ced98030709ee1927c01dabeff39a7bbbb32c
I can't seem to find any use of it though.

**Comment by mberhault** [comment]
Github passes with the `NULL -> NULL_` field rename. AFAICT, we use field values in the `tag` field of the `Value` and don't use the field names anywhere, meaning this change should not cause any problems. I would really appreciate confirmation though.

**Comment by danhhz** [comment]
> @danhhz: you added the NULL ValueType enum value in 865ced9 I can't seem to find any use of it though.

Dunno why I added that. This constant is for the pre column family encoding (which is still used in some circumstances), but that encoding omits any NULL columns. I have no objection to making it reserved, it that works on enums.

**Comment by benesch** [comment]
Ok great let's mark it as reserved and then this LGTM. Please push 20f5237 to crl-release-3.6 before you merge!

**Comment by mberhault** [comment]
I would prefer using the rename to `NULL_` as shown in the last commit,
that's one less patch to keep around. Any objections other than the odd
name?

**Comment by benesch** [comment]
I'm confused. The problem is that NULL is now a reserved keyword in Protobuf 3.6, right? But it sounds like we don't actually use that enum value anywhere, so can't we just delete it, mark its number as reserved, and avoid the rename?

**Comment by mberhault** [comment]
Sorry, I didn't mean reserved as in we don't get to use it in `.proto` files. Protobuf 3.6 went full C++11 and removed `NULL` from the list of keywords that are changed to `<keyword>_` in the generated code. This means that it now ends up generating C++ code with a field named `NULL`, wreaking havoc. Two of the ways around that are:
- put it back in the "special keywords" list in protobuf's `cpp_helpers.cc` (the first commit which includes this patch: https://github.com/cockroachdb/protobuf/commit/80e580b9daa220eac5b91e81ea5dff57d67fabda)
- rename the data.proto `NULL` field to `NULL_` (the second commit).

I'm happy with either but would prefer not adding another patch to protobuf especially given how trivial our change is.

**Comment by benesch** [comment]
Right, I'm advocating for this patch

```diff
diff --git a/pkg/roachpb/data.proto b/pkg/roachpb/data.proto
index d4be6d05e..7cbb13891 100644
--- a/pkg/roachpb/data.proto
+++ b/pkg/roachpb/data.proto
@@ -47,7 +47,6 @@ enum ValueType {
   // storage for various types. The DELIMITED_foo entries each represent a foo
   // variant that self-delimits length.
   UNKNOWN = 0;
-  NULL = 7;
   INT = 1;
   FLOAT = 2;
   BYTES = 3;
@@ -56,6 +55,7 @@ enum ValueType {
   DECIMAL = 5;
   DELIMITED_DECIMAL = 9;
   DURATION = 6;
+  reserved 7;
 
   // TUPLE represents a DTuple, encoded as repeated pairs of varint field number
   // followed by a value encoded Datum.
```

instead of the rename you currently have. Doesn't seem worth keeping the field around if no one uses it.

**Comment by benesch** [comment]
Also, pretty sure it's a bug that they removed `NULL` from that special keywords list. It's not like C++11 removed the `NULL` keyword; it just introduced the `nullptr` keyword. Seems like it probably got mistakenly caught by a find/replace.

**Comment by mberhault** [comment]
Works for me. I'll do it once I'm back to actual work mode (Thursday). We missed the alpha cutoff anyway so no rush.

**Comment by mberhault** [comment]
Moved the field to reserved, and merged the patches to `crl-release.3.6`.

As for upstream, they pulled that change and a bunch of others from their internal repo. Whether it's a mistake or not, I don't think they'll be too happy with making it diverge.

**Comment by mberhault** [comment]
Great. This is breaking in some js everytime, and (almost) each time in new and interesting ways.
I could get it to fail sometimes in my local build, sometimes after just touching the proto and running make, sometimes after a `ui-maintainer-clean`, and sometimes not at all.

protobufjs is supposed to handle reserved enum values just fine, but it seems to be causing some bad state in the parser.

**Comment by benesch** [comment]
In fact, if it's a nondeterministic failure, it's almost certainly that bug. Very frustrating.

**Comment by benesch** [comment]
Yep, here's the error:

```
Error: illegal token '7', '=' expected (line 46)
    at illegal (/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/tokenize.js:81:16)
    at skip (/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/tokenize.js:243:19)
    at parseEnumValue (/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/parse.js:512:9)
    at parseEnum_block (/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/parse.js:501:17)
    at ifBlock (/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/parse.js:290:17)
    at parseEnum (/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/parse.js:496:9)
    at parseCommon (/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/parse.js:267:17)
    at parse (/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/parse.js:721:21)
    at process (/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/root.js:106:30)
    at fetch (/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/src/root.js:165:13)
```

And indeed, support for reserved enum fields was added in 6.8.1 but we're using 6.7. 🤦‍♂️ Looks like we'll need to bump pbjs too.

**Comment by benesch** [comment]
I'm hopeful this is fixed by https://github.com/cockroachdb/cockroach/pull/27070.

**Comment by benesch** [comment]
Ugh, sorry, @mberhault. Want to just stick with your NULL -> NULL_ rename and leave the cleanup for another day?

**Comment by mberhault** [comment]
Yeah, let's do that, it seems enough has changed that we may not want to deal with it so close to release cutoff. It's fun when C++ ends up being the easiest change :)

**Comment by mberhault** [comment]
Switched back to `NULL_`. TC is happy at last!

**Comment by benesch** [comment]
:shipit:

**Comment by mberhault** [comment]
bors r+

Thanks!

**Pull request merged**
