### PR TITLE
docs: new RFC on logging modernization

### PR DESCRIPTION
**Pull request by knz**
Text of RFC here:
https://github.com/knz/cockroach/blob/20200728-rfc-log/docs/RFCS/20200728_log_modernization.md

Release note: None

### CODE REVIEW

**Comment by thtruo** [comment]
Thanks @knz. This might be out of scope for this RFC, but what is the job of the `system.event_log` in the grand scheme of this new logging infrastructure? Do we have any guidance around what should be tracked in `system.event_log` vs other (future) logging channels? 

For example, today customers request getting access to DDL events in their audit logs. However, DDL events are not recorded in audit logs so customers workaround that by querying `system.event_log`.

**Comment by knz** [comment]
I don't have an opinion about keeping `system.event_log` or not once its contents are also copied to the OPS, USER_ADMIN and SENSITIVE_ACCESS logging channels.

There are arguments either way. 
The same discussion also applies to `system.range_log`.

**Comment by knz** [comment]
Merging this as "completed" since the work was, in fact, completed.

bors r+

**Comment by knz** [comment]
(Split all the eventlog-related changes into a different RFC, see #58374)

**Pull request merged**
