### PR TITLE
testutils/gossiputil: DRY

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7490)

### CODE REVIEW

**Comment by tamird** [comment]
cc @vivekmenezes for the first commit.

**Comment by BramGruneir** [comment]
2nd commit LGTM

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7490#-:-KLILYIApJqkvjoVi9KK:1898630176)*

**Comment by vivekmenezes** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[Makefile, line 196 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7490#-KLINElDBn7HVM8TrUu2:-KLINElEMKb7S34fEIJA:-1029288160) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c5e9e63e9df967f2cadffa614ef7c71a7fad02c/Makefile#L196)):*
> ```Makefile
> 	# compile everything; go vet sometimes reports incorrect errors if
> 	# the build artifacts are stale.
> 	$(GO) test -i ./...
> ```

does check: testbuild solve the problem?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7490#-:-KLINLAOa6P_39nmJpjP:1417088721)*

**Comment by tamird** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[Makefile, line 196 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7490#-KLINElDBn7HVM8TrUu2:-KLINhjJeDic8onNNfg9:-320155440) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c5e9e63e9df967f2cadffa614ef7c71a7fad02c/Makefile#L196)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> does check: testbuild solve the problem?
</details>
testbuild is overkill; it builds a test binary for every package

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7490)*

**Comment by vivekmenezes** [comment]
Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7490)*

**Pull request merged**
