### PR TITLE
backupccl: enforce that system tables opt into cluster backup

### LINKED ISSUE #43781: backupccl: make system tables decide if they want to be included in a full cluster backup
Currently, full cluster backup maintains a list of system tables to include in the backup. It may be nicer to have a model where system tables need to opt-in or out of being included in a full cluster backup. When adding a system table today it is not obvious that it will not be included in the full cluster backup.

### PR DESCRIPTION
**Pull request by pbardea**
This commit enforces that all system tables specify a backup
configuration that explicitly lists whether the system table should be
included in a cluster backup or not.

Fixes #43781.

Release note: None

### CODE REVIEW

**Comment by pbardea** [comment]
Note, I outlined a few options in this doc: https://docs.google.com/document/d/1v9gcyWMoYxiWvnd8iXbuvbg6mjG2aYav_aNssckTLa0/edit#heading=h.wb1tx34wps5x and it looked like this was the simplest way that worked well. Any feedback or ideas for different approaches would be appreciated!

**Review by miretskiy — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55749)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @pbardea)

___
*[pkg/ccl/backupccl/system_schema.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55749#-MK780mVAY2odL2Qp12V:-MK780mVAY2odL2Qp12W:b-29mueb) ([raw file](https://github.com/cockroachdb/cockroach/blob/00d72c8dfd20ec44538910e21c94c452e2ef3633/pkg/ccl/backupccl/system_schema.go#L44)):*
> ```Go
> // backup. Every system table should have a specification defined here, enforced
> // by TestAllSystemTablesHaveBackupConfig.
> var systemTableBackupConfiguration = map[string]systemBackupConfiguration{
> ```

Do you want to add a comment to system.go to indicate that new tables should also be added here?
Do you think this map ought to be keyed by ID instead of name?

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55749)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[pkg/ccl/backupccl/system_schema.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55749#-MK780mVAY2odL2Qp12V:-MK794EO1CjDasuszZ-h:bme3wj7) ([raw file](https://github.com/cockroachdb/cockroach/blob/00d72c8dfd20ec44538910e21c94c452e2ef3633/pkg/ccl/backupccl/system_schema.go#L44)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Do you want to add a comment to system.go to indicate that new tables should also be added here?
Do you think this map ought to be keyed by ID instead of name? 
</blockquote></details>

A comment would serve well. I keyed on the table name here in hopes that we soon move to no longer requiring system tables to occupy fixed IDs. In such a world I think that the table name will be the identifier of the system tables.

**Review by miretskiy — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55749)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @pbardea)

___
*[pkg/ccl/backupccl/system_schema.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55749#-MK780mVAY2odL2Qp12V:-MK79awBBpg4BBTWMFO2:b-2owngx) ([raw file](https://github.com/cockroachdb/cockroach/blob/00d72c8dfd20ec44538910e21c94c452e2ef3633/pkg/ccl/backupccl/system_schema.go#L44)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

A comment would serve well. I keyed on the table name here in hopes that we soon move to no longer requiring system tables to occupy fixed IDs. In such a world I think that the table name will be the identifier of the system tables.
</blockquote></details>

Do we not worry about possibly same named table residing in different schemas?

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55749)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[pkg/ccl/backupccl/system_schema.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55749#-MK780mVAY2odL2Qp12V:-MKFpmMcARxstdKMQ-Wu:b-tcuitt) ([raw file](https://github.com/cockroachdb/cockroach/blob/00d72c8dfd20ec44538910e21c94c452e2ef3633/pkg/ccl/backupccl/system_schema.go#L44)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Do we not worry about possibly same named table residing in different schemas?
</blockquote></details>

Yep, that is certainly a concern I have -- but I think I have similar concerns about migrations in general (renames being the relevant example of a migration that might cause problems here). I think that we want to handle these migrations during restore before actually bringing the the data. I would like a better story here with regards to supporting migrations, especially when restoring in from old versions. I will write up some thoughts on how to better support the migration story in an issue.

**Review by miretskiy — APPROVED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55749)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

**Comment by pbardea** [comment]
cc @dt I'm curious if you have any thoughts on this approach versus others before going ahead with this approach since we've briefly chatted about ways to solve this in the past.

**Comment by dt** [comment]
I'm 👍 on this as a basic replacement of what we had before (hand-maintained list).

Long term though, I think opt-in vs out is still too simplistic and we (bulk-io) will still be playing catch-up when we restore something that opts in only to discover it is invalid post-restore. I think our end-goal should be a way to express both "ignore me during cluster backup" and "restore me row-for-row during cluster restore" but also "restore me with this function run on each row during restore: fn(row)...". That'd be something schema could use during restoring of schema change job rows, or while restoring descriptors to ensure migrations have run, etc.

**Comment by pbardea** [comment]
Thanks for taking a look!

> but also "restore me with this function run on each row during restore: fn(row)..."

Agreed, and I think we can almost be there by expanding `systemBackupConfiguration` to take that mapping function and defaulting to identity. We could potentially also string together several of these functions (e.g. one for migration purposes, one for rekeying), but I think it's best to add that when needed.

**Comment by pbardea** [comment]
Thanks for the review!
bors r=miretskiy

**Pull request merged**
