### PR TITLE
kvserver: check that a snapshot is sane before sending it

### PR DESCRIPTION
**Pull request by andreimatei**
The recipient has the check that a snapshot includes it as a replica,
and rejects the snapshot with an assertion error if it doesn't. This
patch adds a less-panicked check on the sender side, as it turns out
that the situation is possible.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56596)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @andreimatei, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/replica_command.go, line 1348 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56596#-MMUy3Kw8vi7Cw5GB6NY:-MMUy3Kw8vi7Cw5GB6NZ:b1vvwoi) ([raw file](https://github.com/cockroachdb/cockroach/blob/490aaac52815aa50564a1b3d3e2349ea8e5bc923/pkg/kv/kvserver/replica_command.go#L1348)):*
> ```Go
> 	// replicas, and those snapshots would be invalid if our stale descriptor
> 	// doesn't contain the respective replicas.
> 	for {
> ```

Can you limit the waiting here to up to, say, 10s? Artificially holding up a replication change can back up the replication queue.

**Review by tbg — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56596)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @andreimatei, and @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56596)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/replica_command.go, line 1348 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56596#-MMUy3Kw8vi7Cw5GB6NY:-MNUV1WiBmVW3K6PyA0M:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/490aaac52815aa50564a1b3d3e2349ea8e5bc923/pkg/kv/kvserver/replica_command.go#L1348)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Can you limit the waiting here to up to, say, 10s? Artificially holding up a replication change can back up the replication queue.
</blockquote></details>

done

**Review by ajwerner — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56596)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @andreimatei, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/replica_command.go, line 1360 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56596#-MNU__5_6Rt_XsVZoWiU:-MNU__5_6Rt_XsVZoWiV:b-urckyn) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ec911c9ab6b5c453aa0ecc8b142805ebfe5b80f/pkg/kv/kvserver/replica_command.go#L1360)):*
> ```
> 		// TODO(andrei): Find a better way to wait for replication. If we knew the
> 		// LAI of the respective command, we could use waitForApplication().
> 		time.Sleep(time.Second)
> ```
Can you instead use a retry thing with a max wait. That way it'll pay attention to context cancellation which very much does happen.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56596#-:-MNUqlRx959l7u0au-Bg:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/replica_command.go, line 1360 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56596#-MNU__5_6Rt_XsVZoWiU:-MNUqcj43pQmfykIwV8N:b-3bzydz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ec911c9ab6b5c453aa0ecc8b142805ebfe5b80f/pkg/kv/kvserver/replica_command.go#L1360)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 		// TODO(andrei): Find a better way to wait for replication. If we knew the
> 		// LAI of the respective command, we could use waitForApplication().
> 		time.Sleep(time.Second)
> ```
Can you instead use a retry thing with a max wait. That way it'll pay attention to context cancellation which very much does happen.
</blockquote></details>

Gracias

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56596)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/replica_command.go, line 1360 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56596#-MNU__5_6Rt_XsVZoWiU:-MNUoj0K8MejbPrb0720:bpmv7dr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ec911c9ab6b5c453aa0ecc8b142805ebfe5b80f/pkg/kv/kvserver/replica_command.go#L1360)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 		// TODO(andrei): Find a better way to wait for replication. If we knew the
> 		// LAI of the respective command, we could use waitForApplication().
> 		time.Sleep(time.Second)
> ```
Can you instead use a retry thing with a max wait. That way it'll pay attention to context cancellation which very much does happen.
</blockquote></details>

done, good idea

**Pull request merged**
