### PR TITLE
[wip,dnm]: roachtest: use toxiproxy for network testing

### PR DESCRIPTION
**Pull request by tbg**
[toxiproxy] is a TCP proxy which exports an HTTP API that allows
introducing various anomalous network conditions for resilience testing.

Among the interesting things one can simulate are latency and bandwidth
restrictions. This is done programmatically and thus lends itself to the
kind of testing we'd like to do; in particular, it should allow testing
locally a good approximation of geo-replicated clusters and various
network partitions.

This is a WIP because it doesn't work in general (the test passes in
`--local` mode but then errors on teardown) and makes lots of
assumptions about the ports. It suggests that the `roachtest` API needs
to be brushed up some.

Updates #21680.
Updates #14768.

[toxiproxy]: https://github.com/Shopify/toxiproxy

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cmd/roachtest/network.go, line 112 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23141#-L6LvDYT5gZ_Uwigkq-3:-L6LvDYT5gZ_Uwigkq-4:bleykys) ([raw file](https://github.com/cockroachdb/cockroach/blob/02ee315ce6ad856202b02807b1cacb9ce2ebcd49/pkg/cmd/roachtest/network.go#L112)):*
> ```Go
> 			// killed at the end of the test. However, when it gets killed, it actually
> 			// *fails* the test, which is unfortunate and I see no way to avoid that
> 			// with the current API.
> ```

Why does the test fail when this gets killed? Is it the exit code? If yes, perhaps append `|| true` to the command line. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23141)*

**Comment by tschottdorf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cmd/roachtest/network.go, line 112 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23141#-L6LvDYT5gZ_Uwigkq-3:-L6N4PK3bPze_xR6EPmf:br8w5tx) ([raw file](https://github.com/cockroachdb/cockroach/blob/02ee315ce6ad856202b02807b1cacb9ce2ebcd49/pkg/cmd/roachtest/network.go#L112)):*
That doesn't help, we're spawning a shell here and that gets `kill -9`ed when we stop the cluster (consequently nothing that gets done in the shell can prevent it):

```
> roachprod ssh local:1 -- ./cockroach sql --insecure -e "SELECT 1"
1
1
> roachprod get local logs artifacts/network/latency/nodes=3/logs
local: getting logs artifacts/network/latency/nodes=3/logs

   1: done
   2: done
   3: done
> roachprod destroy local
local: stopping
local: wiping
OK
--- FAIL: network/latency/nodes=3 (17.38s)
        cluster.go:504,cluster.go:489: roachprod ssh local:3 -- mkdir -p logs && ./toxiproxy-server --port 8477 2>&1 > logs/toxiproxy.out: signal: killed
        cluster.go:504,cluster.go:489: roachprod ssh local:1 -- mkdir -p logs && ./toxiproxy-server --port 8475 2>&1 > logs/toxiproxy.out: signal: killed
        cluster.go:504,cluster.go:489: roachprod ssh local:2 -- mkdir -p logs && ./toxiproxy-server --port 8476 2>&1 > logs/toxiproxy.out: signal: killed
FAIL
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23141)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cmd/roachtest/network.go, line 112 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23141#-L6LvDYT5gZ_Uwigkq-3:-L6Ow11CUjCU5dKUvl4J:bwa5uve) ([raw file](https://github.com/cockroachdb/cockroach/blob/02ee315ce6ad856202b02807b1cacb9ce2ebcd49/pkg/cmd/roachtest/network.go#L112)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

That doesn't help, we're spawning a shell here and that gets `kill -9`ed when we stop the cluster (consequently nothing that gets done in the shell can prevent it):

```
> roachprod ssh local:1 -- ./cockroach sql --insecure -e "SELECT 1"
1
1
> roachprod get local logs artifacts/network/latency/nodes=3/logs
local: getting logs artifacts/network/latency/nodes=3/logs

   1: done
   2: done
   3: done
> roachprod destroy local
local: stopping
local: wiping
OK
--- FAIL: network/latency/nodes=3 (17.38s)
        cluster.go:504,cluster.go:489: roachprod ssh local:3 -- mkdir -p logs && ./toxiproxy-server --port 8477 2>&1 > logs/toxiproxy.out: signal: killed
        cluster.go:504,cluster.go:489: roachprod ssh local:1 -- mkdir -p logs && ./toxiproxy-server --port 8475 2>&1 > logs/toxiproxy.out: signal: killed
        cluster.go:504,cluster.go:489: roachprod ssh local:2 -- mkdir -p logs && ./toxiproxy-server --port 8476 2>&1 > logs/toxiproxy.out: signal: killed
FAIL
```
</blockquote></details>

That's a good point. I don't have a good answer right now. Can we background `toxiproxy-server` and rely on `c.{Destroy,Stop,Wipe}()` killing it? Or perhaps we have a version of `Run` where we ignore the exit code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23141)*

**Comment by tschottdorf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cmd/roachtest/network.go, line 112 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23141#-L6LvDYT5gZ_Uwigkq-3:-L6PrGM9slwz6oGeVtyc:b-3to2c4) ([raw file](https://github.com/cockroachdb/cockroach/blob/02ee315ce6ad856202b02807b1cacb9ce2ebcd49/pkg/cmd/roachtest/network.go#L112)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

That's a good point. I don't have a good answer right now. Can we background `toxiproxy-server` and rely on `c.{Destroy,Stop,Wipe}()` killing it? Or perhaps we have a version of `Run` where we ignore the exit code.
</blockquote></details>

We should have a version of `Run` that returns an error. There are two competing patterns in this framework so far: you have the `*testing.T`-style stuff where the operation fails the test instead of returning an error (as much as I roll my eyes at the neverending `if err := ...` blocks, I find that a worse pattern) and proper error handling in the monitor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23141)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cmd/roachtest/network.go, line 112 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23141#-L6LvDYT5gZ_Uwigkq-3:-L6RgrDh98pcQax-Bs6b:bqu5tym) ([raw file](https://github.com/cockroachdb/cockroach/blob/02ee315ce6ad856202b02807b1cacb9ce2ebcd49/pkg/cmd/roachtest/network.go#L112)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

We should have a version of `Run` that returns an error. There are two competing patterns in this framework so far: you have the `*testing.T`-style stuff where the operation fails the test instead of returning an error (as much as I roll my eyes at the neverending `if err := ...` blocks, I find that a worse pattern) and proper error handling in the monitor.
</blockquote></details>

How about `RunE` which returns an error? `RunL` can then be built on `RunE` and calls `c.t.Fatal` if an error occurs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23141)*

**Comment by tbg** [comment]
@petermattis this is the test I could use help with. I have a little bit of stuff in the pipeline that may prevent me from getting to it for another week or two.

**Comment by petermattis** [comment]
> @petermattis this is the test I could use help with. I have a little bit of stuff in the pipeline that may prevent me from getting to it for another week or two.

Ack.

**Pull request closed without merging**
