### PR TITLE
opt: add array flatten operator

### PR DESCRIPTION
**Pull request by justinj**
This change introduces an explicit ArrayFlatten operator. Before, we
would always build an ArrayFlatten as an array_agg, but this doesn't
work for types which array_agg doesn't support (and ArrayFlatten does).
In the interest of replicating all the functionality of the heuristic
planner, ArrayFlattens are now handled like this:

* They are built as an explicit ArrayFlatten operator. If the subquery
  is correlated *and* the type is one which ArrayAgg doesn't support,
  an error is raised.
* If the subquery is correlated, a new norm rule
  `NormalizeArrayFlattenToAgg` is triggered, which converts the
  ArrayFlatten to an array_agg.

Thus, the resulting compatibility looks like this:
```
                   | Correlated | Uncorrelated
----------------------------------------------
array_agg-able     |    yes     |      yes
not array_agg-able |    no      |      yes
```

Which is fine, as far as support for features supported by the heuristic
planner goes, because it only supports the "Uncorrelated" column,
anyway.  In order to support the bottom-left quadrant,
frontend/execution need to support array_agg for all types (like
tuples).

There's also another significant change in this commit, which is
required for ArrayFlatten to function properly.

Previously, any subquery could always be optimized with the minimum
physical props, because a single row subquery, or an any, or exists
subquery didn't rely on any kind of ordering. This is no longer true
with ArrayFlatten, since it can require an ordering of its input. So
this commit also makes a handful of changes to the optimization
machinery to support requiring an ordering of a child of a scalar.

Release note: None

### CODE REVIEW

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32322)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/rules/scalar.opt, line 312 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRNhiip5Svn856cIJ_q:-LRNhiip5Svn856cIJ_r:b-os8poj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5279298f49d79a0d9730144a1f1460b5deb9421/pkg/sql/opt/norm/rules/scalar.opt#L312)):*
> ```
> )
> =>
> (MakeCoalesce2
> ```

I'd do something more like below. I try to keep as much structure as I can in Optgen, as it makes it easier to quickly get a gist of what the transformation is about.
```
[NormalizeArrayFlattenToAgg, Normalize]
(Any
  $input:(HasOuterCols $input)
  $subquery:*
)
=>
(Coalesce [
    (Subquery
        (Max1Row
			(ScalarGroupBy
			    $input
				[
				    (AggregationsItem
				        (ArrayAgg (Variable (FirstCol $input)))
				        (MakeArrayAggCol (ArrayType $input))
				    )
				]
				(MakeOrderedGrouping (MakeEmptyColSet) (SubqueryOrdering $subquery))
			)
	    )
        (MakeUnorderedSubquery)
    )
    (Array [] (ArrayType $input))
])
```
___
*[pkg/sql/opt/ops/scalar.opt, line 592 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRNokMvCZGG1zkKYWf0:-LRNokMvCZGG1zkKYWf1:bs4zfwi) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5279298f49d79a0d9730144a1f1460b5deb9421/pkg/sql/opt/ops/scalar.opt#L592)):*
> ```
> }
> 
> # ArrayFlatten is an ARRAY(<subquery>) expression.
> ```

Add more details here, like that it expects subquery input to have single column, constructs an array of that column's type, array contains one item for each row in subquery, ordering of array items reflects any ordering of subquery, any null-handling oddities, etc.
___
*[pkg/sql/opt/optbuilder/scalar.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRNpcH10gyi2JUUz3df:-LRNpcH10gyi2JUUz3dg:b-letw2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5279298f49d79a0d9730144a1f1460b5deb9421/pkg/sql/opt/optbuilder/scalar.go#L129)):*
> ```Go
> 		}
> 
> 		b.checkSubqueryOuterCols(s.outerCols, inGroupingContext, inScope, colRefs)
> ```

How come you dropped the comment from the existing code?
___
*[pkg/sql/opt/xform/physical_props.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRNqSMqEJMqcWTkcydl:-LRNqSMqEJMqcWTkcydm:b-3ij9lt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5279298f49d79a0d9730144a1f1460b5deb9421/pkg/sql/opt/xform/physical_props.go#L73)):*
> ```Go
> func (o *Optimizer) buildChildPhysicalPropsScalar(parent opt.Expr, nth int) *props.Physical {
> 	var childProps props.Physical
> 	if parent.Op() == opt.ArrayFlattenOp {
> ```

Make this into a switch so that the pattern is established. In the `default` case, `return physical.MinRequired` rather than falling through to `InternPhysicalProps`, since it's such an important case for perf.

**Review by rytaft — CHANGES_REQUESTED** [review]
> Reviewed 21 of 21 files at r1, 1 of 22 files at r2, 21 of 21 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32322)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/subquery_correlated, line 945 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRN7VgwCDc4NBfy5M9n:-LRN7VgwCDc4NBfy5M9o:b-bx955n) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5279298f49d79a0d9730144a1f1460b5deb9421/pkg/sql/logictest/testdata/logic_test/subquery_correlated#L945)):*
> ```
> # We can't decorrelate cases which don't use a scalar type in the
> # ARRAY(...) operator.
> statement error can't do a correlated ARRAY\(...\) over tuple\{int, string\}
> ```

[nit] Instead of "can't do", maybe say "can't execute"?
___
*[pkg/sql/opt/exec/execbuilder/scalar_builder.go, line 412 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRN8seR4K65zFIDZ1SP:-LRN8seR4K65zFIDZ1SQ:bsd1tva) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5279298f49d79a0d9730144a1f1460b5deb9421/pkg/sql/opt/exec/execbuilder/scalar_builder.go#L412)):*
> ```Go
> 
> 	// The subquery here should always be uncorrelated: if it were not, we would
> 	// have converted it to an aggregation.
> ```

Do you want to add a panic here or something if it is correlated?
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1296 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRNiJnL--HQlhTWTxSp:-LRNiJnMBaulYy2-HNIu:b-hsopih) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5279298f49d79a0d9730144a1f1460b5deb9421/pkg/sql/opt/norm/custom_funcs.go#L1296)):*
> ```Go
> }
> 
> // MakeCoalesce2 creates a Coalesce expression with two inputs.
> ```

This is all under the "Constant Folding Rules" section. Maybe add a new section to contain this stuff?
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1304 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRNj10v5iqeGFvzfNVA:-LRNj10v5iqeGFvzfNVB:b3ku5t2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5279298f49d79a0d9730144a1f1460b5deb9421/pkg/sql/opt/norm/custom_funcs.go#L1304)):*
> ```Go
> func (c *CustomFuncs) MakeEmptyArray(in memo.RelExpr) opt.ScalarExpr {
> 	col, _ := c.OutputCols(in).Next(0)
> 	return c.f.ConstructArray(memo.EmptyScalarListExpr, types.TArray{Typ: c.f.Metadata().ColumnType(opt.ColumnID(col))})
> ```

line should be <= 100 chars
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1307 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRNj43S8iYhuHCMvoS5:-LRNj43S8iYhuHCMvoS6:b-cfzbuq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5279298f49d79a0d9730144a1f1460b5deb9421/pkg/sql/opt/norm/custom_funcs.go#L1307)):*
> ```Go
> }
> 
> // MakeSubquery returns a subquery returning the given relational expression with a Max1Row operator.
> ```

comment should be <= 80 chars
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRNjUzu8NZIV_7mRwS7:-LRNjUzu8NZIV_7mRwS8:boz26m5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5279298f49d79a0d9730144a1f1460b5deb9421/pkg/sql/opt/norm/custom_funcs.go#L1308)):*
> ```Go
> 
> // MakeSubquery returns a subquery returning the given relational expression with a Max1Row operator.
> func (c *CustomFuncs) MakeSubquery(in memo.RelExpr) opt.ScalarExpr {
> ```

Can this function and the two above it just be replaced with optgen syntax? These functions seem like something optgen already supports.

Edit: just saw Andy's comment below -- looks like that't the gist of his comment as well
___
*[pkg/sql/opt/optbuilder/scope.go, line 796 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRNvBME0hM55FBIFD98:-LRNvBME0hM55FBIFD99:b-yqygpl) ([raw file](https://github.com/cockroachdb/cockroach/blob/613b149dc19739ec030b7caf71d18d2c2f5f40eb/pkg/sql/opt/optbuilder/scope.go#L796)):*
> ```Go
> 	case *tree.ArrayFlatten:
> 		if s.builder.AllowUnsupportedExpr {
> 			// TODO(rytaft): Temporary fix for #24171 and #24170.
> ```

Are you sure this isn't necessary anymore?

**Review by justinj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32322)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/subquery_correlated, line 945 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRN7VgwCDc4NBfy5M9n:-LRO3WYe7nGalUPnlgBv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5279298f49d79a0d9730144a1f1460b5deb9421/pkg/sql/logictest/testdata/logic_test/subquery_correlated#L945)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] Instead of "can't do", maybe say "can't execute"?
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/scalar_builder.go, line 412 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRN8seR4K65zFIDZ1SP:-LRO3YGqBeVqMTex1MRB:b-6732hc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5279298f49d79a0d9730144a1f1460b5deb9421/pkg/sql/opt/exec/execbuilder/scalar_builder.go#L412)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Do you want to add a panic here or something if it is correlated?
</blockquote></details>

Yeah, probably a good idea. Done.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1296 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRNiJnL--HQlhTWTxSp:-LRO4lim7Otd12cpfG-v:bq4n1bt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5279298f49d79a0d9730144a1f1460b5deb9421/pkg/sql/opt/norm/custom_funcs.go#L1296)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This is all under the "Constant Folding Rules" section. Maybe add a new section to contain this stuff?
</blockquote></details>

Added it to the scalar section.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1304 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRNj10v5iqeGFvzfNVA:-LRO56_GEhqopW6OJ6yC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5279298f49d79a0d9730144a1f1460b5deb9421/pkg/sql/opt/norm/custom_funcs.go#L1304)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

line should be <= 100 chars
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1307 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRNj43S8iYhuHCMvoS5:-LRO57G--eL-uTGqI09K:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5279298f49d79a0d9730144a1f1460b5deb9421/pkg/sql/opt/norm/custom_funcs.go#L1307)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

comment should be <= 80 chars
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRNjUzu8NZIV_7mRwS7:-LRhLIFSA_2gEzd4Y5k7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5279298f49d79a0d9730144a1f1460b5deb9421/pkg/sql/opt/norm/custom_funcs.go#L1308)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Can this function and the two above it just be replaced with optgen syntax? These functions seem like something optgen already supports.

Edit: just saw Andy's comment below -- looks like that't the gist of his comment as well
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rules/scalar.opt, line 312 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRNhiip5Svn856cIJ_q:-LRhLZOS1mVN2LNEcDGE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5279298f49d79a0d9730144a1f1460b5deb9421/pkg/sql/opt/norm/rules/scalar.opt#L312)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I'd do something more like below. I try to keep as much structure as I can in Optgen, as it makes it easier to quickly get a gist of what the transformation is about.
```
[NormalizeArrayFlattenToAgg, Normalize]
(Any
  $input:(HasOuterCols $input)
  $subquery:*
)
=>
(Coalesce [
    (Subquery
        (Max1Row
			(ScalarGroupBy
			    $input
				[
				    (AggregationsItem
				        (ArrayAgg (Variable (FirstCol $input)))
				        (MakeArrayAggCol (ArrayType $input))
				    )
				]
				(MakeOrderedGrouping (MakeEmptyColSet) (SubqueryOrdering $subquery))
			)
	    )
        (MakeUnorderedSubquery)
    )
    (Array [] (ArrayType $input))
])
```
</blockquote></details>

Done.
___
*[pkg/sql/opt/ops/scalar.opt, line 592 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRNokMvCZGG1zkKYWf0:-LRhMMPx2QWjGIVolnvE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5279298f49d79a0d9730144a1f1460b5deb9421/pkg/sql/opt/ops/scalar.opt#L592)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Add more details here, like that it expects subquery input to have single column, constructs an array of that column's type, array contains one item for each row in subquery, ordering of array items reflects any ordering of subquery, any null-handling oddities, etc.
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/scalar.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRNpcH10gyi2JUUz3df:-LRhMUTtEBMdD3gctC4O:b-6zbgfa) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5279298f49d79a0d9730144a1f1460b5deb9421/pkg/sql/opt/optbuilder/scalar.go#L129)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

How come you dropped the comment from the existing code?
</blockquote></details>

Was an accident of moving stuff around - put it back.
___
*[pkg/sql/opt/optbuilder/scope.go, line 796 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRNvBME0hM55FBIFD98:-LRhMY7y8YeuAndL4UHC:b4e9fem) ([raw file](https://github.com/cockroachdb/cockroach/blob/613b149dc19739ec030b7caf71d18d2c2f5f40eb/pkg/sql/opt/optbuilder/scope.go#L796)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Are you sure this isn't necessary anymore?
</blockquote></details>

I thought I was but I am no longer! Put back as we discussed offline.
___
*[pkg/sql/opt/xform/physical_props.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRNqSMqEJMqcWTkcydl:-LRhNUuv5qM2CORd_5zc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5279298f49d79a0d9730144a1f1460b5deb9421/pkg/sql/opt/xform/physical_props.go#L73)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Make this into a switch so that the pattern is established. In the `default` case, `return physical.MinRequired` rather than falling through to `InternPhysicalProps`, since it's such an important case for perf.
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm: nice!

> Reviewed 22 of 22 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-:-LRlwyktE4t7dajFaupg:b-7yytuz)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/custom_funcs.go, line 1106 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRluWPA-eUr9TXHeD_z:-LRluWPA-eUr9TXHeDa-:b-hbvzq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/df685a462f8e87ac64902a2f3676b8db3a004cb8/pkg/sql/opt/norm/custom_funcs.go#L1106)):*
> ```Go
> 
> // MakeEmptyArray returns an empty array with the same element type as the input.
> func (c *CustomFuncs) MakeEmptyArray(in memo.RelExpr) opt.ScalarExpr {
> ```

Do you still need this?
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1134 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRlvCqc3FrwTqQvEpVs:-LRlvCqd1bPT7F5flkuo:b-3kbmxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/df685a462f8e87ac64902a2f3676b8db3a004cb8/pkg/sql/opt/norm/custom_funcs.go#L1134)):*
> ```Go
> }
> 
> // MakeArrayAggCol returns a SubqueryPrivate that specifies no ordering.
> ```

fix comment
___
*[pkg/sql/opt/ops/scalar.opt, line 641 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRlvqa4E1kI2YC0FPwl:-LRlvqa4E1kI2YC0FPwm:b-i866cs) ([raw file](https://github.com/cockroachdb/cockroach/blob/df685a462f8e87ac64902a2f3676b8db3a004cb8/pkg/sql/opt/ops/scalar.opt#L641)):*
> ```
> }
> 
> # ArrayFlatten is an ARRAY(<subquery>) expression. ArrayFlatten takes an input
> ```

[nit] an -> as

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-:-LRm1re20w5AsRFGJ2RC:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/custom_funcs.go, line 1121 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRm0Ew8E7qbWW6dHoD4:-LRm-nFu4Fa_oFPCfB58:b8q4j86) ([raw file](https://github.com/cockroachdb/cockroach/blob/df685a462f8e87ac64902a2f3676b8db3a004cb8/pkg/sql/opt/norm/custom_funcs.go#L1121)):*
> ```Go
> // ArrayType returns the type of the first output column wrapped
> // in an array.
> func (c *CustomFuncs) ArrayType(in memo.RelExpr) types.T {
> ```

This should go up with the other typing helpers.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1148 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRm0P7lEpzUdLd12rJE:-LRm0P7lEpzUdLd12rJF:b-ataw7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/df685a462f8e87ac64902a2f3676b8db3a004cb8/pkg/sql/opt/norm/custom_funcs.go#L1148)):*
> ```Go
> 
> // SubqueryOrdering returns the ordering property on a SubqueryPrivate.
> func (c *CustomFuncs) SubqueryOrdering(sub *memo.SubqueryPrivate) physical.OrderingChoice {
> ```

NIT: put this alongside the `MakeUnorderedSubquery` method.

**Review by rytaft — CHANGES_REQUESTED** [review]
> Reviewed 1 of 23 files at r6, 23 of 23 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32322)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/logictest/testdata/logic_test/array, line 0 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LSz4Fpz2J2KLCzN9CTh:-LSz4Fpz2J2KLCzN9CTi:bm3gawb) ([raw file](https://github.com/cockroachdb/cockroach/blob/01097dbe7ee908efb60ad6b3591cb2342e6312a1/pkg/sql/logictest/testdata/logic_test/array#L0)):*
Why does GitHub think this file is binary?
___
*[pkg/sql/opt/ops/scalar.opt, line 44 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LSz5LS57HSi8qGmfEoX:-LSz5LS57HSi8qGmfEoY:bifqfoj) ([raw file](https://github.com/cockroachdb/cockroach/blob/01097dbe7ee908efb60ad6b3591cb2342e6312a1/pkg/sql/opt/ops/scalar.opt#L44)):*
> ```
> 
>   # RequestedCol is set if there could possibly be other columns in the input
>   # (say, if there was an ordering that must be respected) than the one that will
> ```

[nit] than the one -> besides the one
___
*[pkg/sql/opt/optbuilder/scalar.go, line 125 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LSz5Ymf4d5f0hf0O6od:-LSz5Ymf4d5f0hf0O6oe:bsgljhq) ([raw file](https://github.com/cockroachdb/cockroach/blob/01097dbe7ee908efb60ad6b3591cb2342e6312a1/pkg/sql/opt/optbuilder/scalar.go#L125)):*
> ```Go
> 		// We cannot array_agg over some types, but we can only decorrelate via array_agg.
> 		// Thus, we reject a query that is correlated and over a type that we can't array_agg.
> 		//inCol, _ := s.node.Relational().OutputCols.Next(0)
> ```

Stale comment. Also looks like maybe you don't need `inCol` anymore
___
*[pkg/sql/opt/xform/physical_props.go, line 82 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LSz65W6C_1k91p34ZcM:-LSz65W6C_1k91p34ZcN:b-tnnn93) ([raw file](https://github.com/cockroachdb/cockroach/blob/01097dbe7ee908efb60ad6b3591cb2342e6312a1/pkg/sql/opt/xform/physical_props.go#L82)):*
> ```Go
> 			childProps.Presentation = physical.Presentation{
> 				opt.LabeledColumn{
> 					Label: "input",
> ```

I think it would be good to only use this label if the requested column doesn't already have a label. I'd also pick something a bit less generic -- maybe `array_input` or something like that?

**Review by justinj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32322)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/logictest/testdata/logic_test/array, line  at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LSz4Fpz2J2KLCzN9CTh:-LSzALs66ZCS8Yg4rmPO:b-dojoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/01097dbe7ee908efb60ad6b3591cb2342e6312a1/pkg/sql/logictest/testdata/logic_test/array#L)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why does GitHub think this file is binary?
</blockquote></details>

Looks like the culprit is this line: https://github.com/cockroachdb/cockroach/blob/5e42b01f387080dfb0c8c609d3c060123302c9ea/pkg/sql/logictest/testdata/logic_test/array#L188

which I guess was a problem before this PR as well. I'll make a note to look into it but I think it was already a problem.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1106 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRluWPA-eUr9TXHeD_z:-LRmAyFw1u2yW-Fn-iqX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/df685a462f8e87ac64902a2f3676b8db3a004cb8/pkg/sql/opt/norm/custom_funcs.go#L1106)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Do you still need this?
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1121 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRm0Ew8E7qbWW6dHoD4:-LRmB2u71QbfRaJ3RAe6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/df685a462f8e87ac64902a2f3676b8db3a004cb8/pkg/sql/opt/norm/custom_funcs.go#L1121)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This should go up with the other typing helpers.
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1134 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRlvCqc3FrwTqQvEpVs:-LRmBQ37-_0ycn5ZqXdP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/df685a462f8e87ac64902a2f3676b8db3a004cb8/pkg/sql/opt/norm/custom_funcs.go#L1134)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

fix comment
</blockquote></details>

Done.
___
*[pkg/sql/opt/ops/scalar.opt, line 641 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LRlvqa4E1kI2YC0FPwl:-LRmBfdkBt6T9diB0lj3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/df685a462f8e87ac64902a2f3676b8db3a004cb8/pkg/sql/opt/ops/scalar.opt#L641)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] an -> as
</blockquote></details>

Done.
___
*[pkg/sql/opt/ops/scalar.opt, line 44 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LSz5LS57HSi8qGmfEoX:-LSzAgKp4SCHRfaSUYwJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/01097dbe7ee908efb60ad6b3591cb2342e6312a1/pkg/sql/opt/ops/scalar.opt#L44)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] than the one -> besides the one
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/scalar.go, line 125 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LSz5Ymf4d5f0hf0O6od:-LSzArSlCWJ-0jVG2IeK:b1svyq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/01097dbe7ee908efb60ad6b3591cb2342e6312a1/pkg/sql/opt/optbuilder/scalar.go#L125)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Stale comment. Also looks like maybe you don't need `inCol` anymore
</blockquote></details>

Done, kept it since it was referenced below.
___
*[pkg/sql/opt/xform/physical_props.go, line 82 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-LSz65W6C_1k91p34ZcM:-LSzHlmP7QRmrtWi2QF0:b-jwshff) ([raw file](https://github.com/cockroachdb/cockroach/blob/01097dbe7ee908efb60ad6b3591cb2342e6312a1/pkg/sql/opt/xform/physical_props.go#L82)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think it would be good to only use this label if the requested column doesn't already have a label. I'd also pick something a bit less generic -- maybe `array_input` or something like that?
</blockquote></details>

Done, I just reused whatever label there already was.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32322#-:-LSzJYo64WAWmR4ahima:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Comment by justinj** [comment]
TFTR!

bors r+

**Pull request merged**
