### PR TITLE
backport-19.1: storage: fix checksum version check

### PR DESCRIPTION
**Pull request by tbg**
Backport 2/3 commits from #37868.

/cc @cockroachdb/release

---

The check was sitting at evaluation time, where it is useless. It needs to
sit in the below-Raft code that actually computes the checksums.

This flew under the radar for quite some time, but was found in:

https://github.com/cockroachdb/cockroach/issues/37737#issuecomment-496026918

thanks to the aggressive consistency checks we run in
version/mixed/nodes=3.

Release note (bug fix): Fixed a potential source of (faux) replica
inconsistencies that can be reported while running a mixed v19.1 / v2.1
cluster. This error (in that situation only) is benign and can be
resolved by upgrading to the latest v19.1 patch release. Every time this
error occurs a "checkpoint" is created which will occupy a large amount
of disk space and which needs to be removed manually (see /auxiliary/checkpoints).

### CODE REVIEW

**Comment by andreimatei** [comment]
Lgtm

**Comment by bdarnell** [comment]
This should have a release note. (It's very rare for a backported non-test change to need "Release note: None").

**Comment by tbg** [comment]
@bdarnell I could basically duplicate the release note from https://github.com/cockroachdb/cockroach/pull/37722 here -- let me know if I should, I'll hold off on merging this for now.

**Comment by bdarnell** [comment]
Yeah, something like the note in #37722 is fine.

**Comment by tbg** [comment]
Done, TFTRs!

**Pull request merged**
