### PR TITLE
sql: fix exec+audit logs for BEGIN, COMMIT, SET stmts

### PR DESCRIPTION
**Pull request by rafiss**
Epic: None
Release note (bug fix): Fixed a bug where BEGIN, COMMIT, SET, ROLLBACK, and SAVEPOINT statements would not be written to the execution or audit logs.

### CODE REVIEW

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107912)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107912#-NalfsfF5wyIRJuRaU-W):*
Does the audit log capture queries that fail from syntax issues?
___
*[`pkg/sql/conn_executor_exec.go` line 755 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107912#-NaliS3bAhyx268ZqnN8:-NaliS3bAhyx268ZqnN9:bdltwto) ([raw file](https://github.com/cockroachdb/cockroach/blob/42794ec84fe920ee4873e1f15a603b6c4a0e18ad/pkg/sql/conn_executor_exec.go#L755)):*
> ```Go
> 	// If adminAuditLogging is enabled, we want to check for HasAdminRole
> 	// before maybeLogStatement.
> 	// We must check prior to execution in the case the txn is aborted due to
> ```

Is there any way to keep all this logic in the same place or have a flag on the request?
___
*[`pkg/sql/conn_executor_exec.go` line 757 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107912#-NalifHF99P9YSrJerfm:-NalifHF99P9YSrJerfn:bwskllh) ([raw file](https://github.com/cockroachdb/cockroach/blob/42794ec84fe920ee4873e1f15a603b6c4a0e18ad/pkg/sql/conn_executor_exec.go#L757)):*
> ```Go
> 	// We must check prior to execution in the case the txn is aborted due to
> 	// an error. HasAdminRole can only be checked in a valid txn.
> 	if adminAuditLog := adminAuditLogEnabled.Get(
> ```

Should the `ex.extraTxnState.hasAdminRoleCache.IsSet` be checked and skip this logic if it's already set?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107912)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107912#-NalfsfF5wyIRJuRaU-W):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Does the audit log capture queries that fail from syntax issues?
</blockquote></details>

i don't believe it does, but if we want it to, i think that should be handled as a separate issue, since it sounds more like a feature request
___
*[`pkg/sql/conn_executor_exec.go` line 755 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107912#-NaliS3bAhyx268ZqnN8:-NaxB2ni31klN4eabHgX:bxj2mrg) ([raw file](https://github.com/cockroachdb/cockroach/blob/42794ec84fe920ee4873e1f15a603b6c4a0e18ad/pkg/sql/conn_executor_exec.go#L755)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Is there any way to keep all this logic in the same place or have a flag on the request?
</blockquote></details>

just to clarify, which logic do you refer to? and same place as what other logic?
___
*[`pkg/sql/conn_executor_exec.go` line 757 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107912#-NalifHF99P9YSrJerfm:-NaxAxVBDLuXnaHUt4xW:bi0rrl) ([raw file](https://github.com/cockroachdb/cockroach/blob/42794ec84fe920ee4873e1f15a603b6c4a0e18ad/pkg/sql/conn_executor_exec.go#L757)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Should the `ex.extraTxnState.hasAdminRoleCache.IsSet` be checked and skip this logic if it's already set?
</blockquote></details>

the code is already doing that (3 lines below this one)

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107912)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107912#-NalfsfF5wyIRJuRaU-W):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i don't believe it does, but if we want it to, i think that should be handled as a separate issue, since it sounds more like a feature request
</blockquote></details>

we do log all syntax errors in the exec log though:

https://github.com/cockroachdb/cockroach/blob/dc28e1932b9b01907203374005d450cfda2a562a/pkg/sql/pgwire/conn.go#L349

https://github.com/cockroachdb/cockroach/blob/dc28e1932b9b01907203374005d450cfda2a562a/pkg/sql/pgwire/conn.go#L485C6-L485C6

**Review by j82w — APPROVED** [review]
Please add a test. Other than that it LGTM.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107912#-:-Nay5eSfA1byJjY6mmD0:b-5bmptq)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by rafiss** [comment]
tftr!

bors r=j82w

**Pull request merged**
