### PR TITLE
execstats: use ExtractStatsFromSpans in TraceAnalyzer

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### execstats: add component type for a flow

Add a FLOW type for ComponentID, which contains stats that pertain to
the entire flow on a node. Each node would emit stats for its own
flow; the ID of the node should be part of the component but that is
left as a TODO since that information is not used right now.

Release note: None

#### execstats: use ExtractStatsFromSpans in TraceAnalyzer

Simplify the TraceAnalyzer code to use the information in the
ComponentStats, rather than using tags.

As of this change, there is no remaining code that consults the
FlowIDTagKey/StreamIDTagKey/ProcessorIDTagKey span tags. In addition,
we could potentially allow multiple ComponentStats in a single tracing
span (currently the vectorized code creates multiple spans for the
sole purpose of associating stats).

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
This is based on #58179.

**Review by tbg — APPROVED** [review]

**Review by cathymw — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58185#-:-MPB2dNZ-5NrbsdzzCKH:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @cathymw, and @RaduBerinde)

___
*[pkg/sql/execinfrapb/component_stats.proto, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58185#-MPB1ejUE74DfZZzxaHz:-MPB1ejUE74DfZZzxaI-:bbqrhzo) ([raw file](https://github.com/cockroachdb/cockroach/blob/c71843a35af384707335ab14a737fbbdbbca05c2/pkg/sql/execinfrapb/component_stats.proto#L30)):*
> ```protobuf
>     PROCESSOR = 1;
> 
>     // The component is a tream; the id corresponds to a stream ID in the plan.
> ```

tiny nit: missing "s" on stream

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58185#-:-MPBG9qr-Yk74Y2V-8az:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @cathymw)

___
*[pkg/sql/execinfrapb/component_stats.proto, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58185#-MPB1ejUE74DfZZzxaHz:-MPBGBcn0S5Z91qtEqhR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c71843a35af384707335ab14a737fbbdbbca05c2/pkg/sql/execinfrapb/component_stats.proto#L30)):*
<details><summary><i>Previously, cathymw wrote…</i></summary><blockquote>

tiny nit: missing "s" on stream
</blockquote></details>

Done.

**Comment by RaduBerinde** [comment]
TestBackupRestoreWithConcurrentWrites flake.

bors r+

**Pull request merged**
