### PR TITLE
ui: finish short-term enhancements to cluster overview

### PR DESCRIPTION
**Pull request by couchand**
This fixes everything from #19512, leaving #20540 and #19945 for future work.

screen shot 2017-12-12 at 6 47 07 pm

### CODE REVIEW

**Comment by vilterp** [comment]
:lgtm: with a minor nit

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/ui/src/views/cluster/containers/clusterOverview/index.tsx, line 17 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20669#-L0CjFuKrMghU-iDaqQ5:-L0CjFuKrMghU-iDaqQ6:b-y17jlt) ([raw file](https://github.com/cockroachdb/cockroach/blob/148869944c32f9f63e5e7e773e4d6dcf33afd74c/pkg/ui/src/views/cluster/containers/clusterOverview/index.tsx#L17)):*
> ```XML
> 
> // tslint:disable-next-line:no-var-requires
> const spinner = require<string>("assets/spinner.gif");
> ```

does `import spinner from "assets/spinner.gif"` work?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20669#-:-L0CjNSxiOgwCGB-SjU6:b-5l970c)*

**Comment by couchand** [comment]
Well look at that, your nit made me learn something.

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/ui/src/views/cluster/containers/clusterOverview/index.tsx, line 17 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20669#-L0CjFuKrMghU-iDaqQ5:-L0FQZ7aWQwyINLGmjf9:bc1hxza) ([raw file](https://github.com/cockroachdb/cockroach/blob/148869944c32f9f63e5e7e773e4d6dcf33afd74c/pkg/ui/src/views/cluster/containers/clusterOverview/index.tsx#L17)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

does `import spinner from "assets/spinner.gif"` work?
</blockquote></details>

TBH I just cargo-culted that 😳.

Tried it out.  Builds fine (Webpack gets it), but tslint (and maybe tsc) doesn't get it:
`Cannot find module 'assets/spinner.gif'.`

...

UPDATE: after reading through Microsoft/TypeScript#2709 I've found a solution!

I'm not exactly clear on how the `import "*.styl"` was already working, but perhaps because it was just imported for the side-effect, TS doesn't bother checking for it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20669#-:-L0FUtjBShpE1cx4dHEd:b-ppmt6b)*

**Comment by vilterp** [comment]
Nice 👍  LGTM

**Comment by couchand** [comment]
whoops, missed the file with the important part

**Comment by mrtracy** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/ui/src/views/cluster/containers/clusterOverview/index.tsx, line 17 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20669#-L0CjFuKrMghU-iDaqQ5:-L0GDCCQhzVbmPeB08xl:b-maya02) ([raw file](https://github.com/cockroachdb/cockroach/blob/148869944c32f9f63e5e7e773e4d6dcf33afd74c/pkg/ui/src/views/cluster/containers/clusterOverview/index.tsx#L17)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

TBH I just cargo-culted that 😳.

Tried it out.  Builds fine (Webpack gets it), but tslint (and maybe tsc) doesn't get it:
`Cannot find module 'assets/spinner.gif'.`

...

UPDATE: after reading through Microsoft/TypeScript#2709 I've found a solution!

I'm not exactly clear on how the `import "*.styl"` was already working, but perhaps because it was just imported for the side-effect, TS doesn't bother checking for it?
</blockquote></details>

RE: Side effect imports, yes, that is correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20669)*

**Comment by mrtracy** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20669#-:-L0GDna9yfjIQzzFMm5y:bnfp4nl)*

**Pull request merged**
