### PR TITLE
storage/mvcc: extract mvcc subpackage to break dependency on pebble

### PR DESCRIPTION
**Pull request by ajwerner**
We have some rules about which packages are allowed to import which package. In particular, there's some assumptions that some bulk io code not directly import `storage`. That code relies on some definitions of things like `MVCCSimplerIterator` and `MVCCKeyValue`. These two commits pull some symbols out of `storage` and into `storage/mvcc` and then renames prefixes of symbols to remove the leading `MVCC`. All of this code was generated using the automated refactorings in GoLand. No logic was changed. 

Part of #64450.

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
This one is likely controversial. @dt says he doesn't care about the storage dep from bulk io so I'm going to nix this.

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 8 of 134 files at r1, 12 of 101 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64468)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/engine.go, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64468#-MZY1EaD2pwUbSVK5eBX:-MZY1EaD2pwUbSVK5eBY:b-3i4dis) ([raw file](https://github.com/cockroachdb/cockroach/blob/97c016f6071ab8a94c0c14500840a4111cb353f7/pkg/storage/engine.go#L58)):*
> ```Go
> 	// iteration. After this call, valid will be true if the iterator was not
> 	// originally positioned at the last key. Note that unlike
> 	// Iterator.NextKey, this method does not skip other versions with the
> ```

mvcc.Iterator.NextKey
___
*[pkg/storage/engine.go, line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64468#-MZY1NLb71W1JawV4bPL:-MZY1NLb71W1JawV4bPM:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/97c016f6071ab8a94c0c14500840a4111cb353f7/pkg/storage/engine.go#L60)):*
> ```Go
> 	// Iterator.NextKey, this method does not skip other versions with the
> 	// same EngineKey.Key.
> 	// TODO(sumeer): change Iterator.Next() to match the
> ```

ditto
___
*[pkg/storage/engine.go, line 130 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64468#-MZY1O_EBdaMo7PArkpP:-MZY1O_EBdaMo7PArkpQ:biunj19) ([raw file](https://github.com/cockroachdb/cockroach/blob/97c016f6071ab8a94c0c14500840a4111cb353f7/pkg/storage/engine.go#L130)):*
> ```Go
> 	//
> 	// These fields are only relevant for MVCCIterators. Additionally, an
> 	// Iterator with timestamp hints will not see separated intents, and may
> ```

ditto.
also can you search for plurals like `MVCCIterators`, since they don't get fixed automatically.
___
*[pkg/storage/engine_test.go, line 161 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64468#-MZY1lAq1mEp5VMI-J2k:-MZY1lAq1mEp5VMI-J2l:biivdlz) ([raw file](https://github.com/cockroachdb/cockroach/blob/97c016f6071ab8a94c0c14500840a4111cb353f7/pkg/storage/engine_test.go#L161)):*
> ```Go
> 				}
> 
> 				// Iterator should not reuse its cached result.
> ```

mvcc.Iterator

Similarly in other files, like intent_interleaving_iter.go
___
*[pkg/storage/mvcc/doc.go, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64468#-MZY-QblAp26O3makdn7:-MZY-QblAp26O3makdn8:b-sm641u) ([raw file](https://github.com/cockroachdb/cockroach/blob/0505354bf684b2dab921d39c466633edb9c242be/pkg/storage/mvcc/doc.go#L11)):*
> ```Go
> // licenses/APL.txt.
> 
> // Package mvcc exports interfaces for interacting with mvcc storage.
> ```

Could you add a bit more context here, like what is said in the PR description about dependencies. Otherwise someone may imagine that all interfaces for interacting with mvcc storage belong here, while in practice what is here is a (smallish) subset, and it may create confusion on where to place future additions.

**Comment by sumeerbhola** [comment]
never mind, now that this is closed

**Comment by ajwerner** [comment]
Thanks for giving it a look. Sorry for the noise!

**Pull request closed without merging**
