### PR TITLE
admission: carve out some new files

### PR DESCRIPTION
**Pull request by irfansharif**
Pure code movement. Trying to see what components in this package could be
reasoned about independently to readers less familiar with this package.
Some of these may benefit from being pulled into sub-packages, but for now
separate files are sufficient. We're hurting some git history tracking
with this PR, but hopefully they lead to more understandability with future
work. It's also better to do it now before the release branch is cut to
make backports easier. If we pull them into sub packages next, git tracking
will then come for free.

```
admission: move ioLoadListener into its own file
admission: move GrantCoordinator into its own file
admission: move kvSlotAdjuster into its own file
admission: move sqlNodeCPUOverloadIndicator into its own file
admission: move tokensLinearModel into its own file
admission: add top-level admission.go
admission: move store{AdmissionStats,RequestEstimates}..
admission: segment test files by central type
```

I'm not breaking things up into subpackages in this PR, but this paves the
way for that. The structure I'm imagining is roughly:

    pkg/util/admission/
    ├── admission.go
    ├── admissionpb/
    ├── diskbandwidthlimiter/
    ├── diskloadwatcher/
    ├── grantcoordinator/
    ├── granter/
    ├── ioloadlistener/
    ├── kvslotadjuster/
    ├── sqlcpuoverloadindicator/
    ├── storeworkqueue/
    └── tokenlinearmodel/

Where the sub-packages house concrete implementations of interfaces
defined in admission.go, corresponding tests, and constructors for those
types. They depend on the base level pkg/util/admission package and talk
to the other subpackages through interfaces. The existing interfaces are
already written in a manner to make this happen. For other examples of
this pattern, look at pkg/{upgrade,spanconfig}.

Release justification: low-risk / high-benefit (pure code movement, will make backports easier)

### CODE REVIEW

**Comment by irfansharif** [comment]
I'm also adding @andrewbaptist since he's looking to better understand admission control going forward. In the near future we're hoping to use some of the disk bandwidth modelling we introduced in #85722 for snapshot admission as part of #80607.

**Comment by tbg** [comment]
Going to bow out of the review; between Andrew and Sumeer you should be covered. Thanks for splitting things apart, good idea.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 4 of 4 files at r2, 3 of 3 files at r3, 3 of 3 files at r4, 3 of 3 files at r5, 5 of 5 files at r6, 2 of 2 files at r7, 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86065)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @irfansharif)

___
*[`pkg/util/admission/grant_coordinator_test.go` line 30 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/86065#-N9bByNI2Oj6S1STX4m8:-N9bByNI2Oj6S1STX4m9:b-c3qb2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/58c8e8e8d2fe07c44600e03291c3b2a5fd91293c/pkg/util/admission/grant_coordinator_test.go#L30)):*
> ```Go
> 
> // TestStoreCoordinators tests only the setup of GrantCoordinators per store.
> // Testing of IO load functionality happens in TestIOLoadListener.
> ```

I am not sure about this separation. granter_test.go contains TestGranterBasic, which is also a GrantCoordinator test. We can keep this small test in that file. They also share `testMetricsProvider`.
___
*[`pkg/util/admission/work_queue.go` line 1560 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86065#-N9bB2VeAFX3z0CjEsTY:-N9bB2VeAFX3z0CjEsTZ:bxaxccp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e7460dc3a100e075a34876f42f8b6dc301bc889/pkg/util/admission/work_queue.go#L1560)):*
> ```Go
> }
> 
> // storeAdmissionStats are stats maintained by a storeRequester. The non-test
> ```

These two structs should go into admission.go since these are part of the contract defined by the interfaces there.
work_queue.go has implementers of the interfaces.

**Review by irfansharif — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86065#-:-N9qUp0I2QuXtO3_stBj:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @sumeerbhola)

___
*[`pkg/util/admission/grant_coordinator_test.go` line 30 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/86065#-N9bByNI2Oj6S1STX4m8:-N9qT2a_9HFaX_xi70rg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/58c8e8e8d2fe07c44600e03291c3b2a5fd91293c/pkg/util/admission/grant_coordinator_test.go#L30)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I am not sure about this separation. granter_test.go contains TestGranterBasic, which is also a GrantCoordinator test. We can keep this small test in that file. They also share `testMetricsProvider`.
</blockquote></details>

Done.
___
*[`pkg/util/admission/work_queue.go` line 1560 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86065#-N9bB2VeAFX3z0CjEsTY:-N9qRdFm9mfI8mCpFCpB:b-57s3sz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e7460dc3a100e075a34876f42f8b6dc301bc889/pkg/util/admission/work_queue.go#L1560)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

These two structs should go into admission.go since these are part of the contract defined by the interfaces there.
work_queue.go has implementers of the interfaces.
</blockquote></details>

Done, added a commit.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 8 files at r9, 7 of 7 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86065#-:-N9qwdgq1YF7Plrr_DlZ:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist and @sumeerbhola)

**Pull request merged**
