### PR TITLE
cli: remove --log-dir default value help text

### LINKED ISSUE #4816: fix help text for --log-dir flag
Current help text is: 

```
--log-dir    if non-empty, write log files in this directory (default "/var/folders/5t/1rt6nzr17sjg87mz5n0fw15c0000gn/T/")
```

We should change this to:

```
--log-dir    write log files in this directory (default <first-store-directory>/logs, or for an in-memory store, $TMPDIR)
```

@bdarnell, @petermattis, @BramGruneir

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #4816.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4817)

### CODE REVIEW

**Comment by petermattis** [comment]
@jseldess Does this work for you? I think the longer help text you suggested in #4816 could be overwhelming.

**Comment by jseldess** [comment]
I personally find the expression `non-empty` a bit tricky (double negative). And wouldn't we want to state the default? What about the shorter?

`write log files in this directory (default <first-store-dir>/log)`

**Comment by petermattis** [comment]
The default is only correct for the `start` command. Isn't the `non-empty` bit only a single negative? Or are you saying that is a double-negative within a single word?

**Comment by petermattis** [comment]
Btw, I'd prefer to leave the `if non-empty` text alone. That text comes from the [`glog` package](https://github.com/golang/glog/blob/master/glog_file.go#L41) which our logging package is derived from.

**Comment by jseldess** [comment]
Oh, right. I guess it's not a double-negative grammatically, but "empty" feels negative. Maybe this flag would benefit from custom texts per command. But if we don't want to do that, would this be too long? It's still a few characters shorter than what's there now...

```
write log files in this directory (default "<first-store-dir>/logs" for start or $TMPDIR for other commands)
```

**Comment by jseldess** [comment]
OK, just saw your last comment. Then I'm fine leaving it `if non-empty, write log files to this directory`, and in the docs I can be more explicit.

**Comment by jseldess** [comment]
Added to docs with https://github.com/cockroachdb/docs/pull/88

**Pull request merged**
