### PR TITLE
jobs: adopt more jobs per loop

### PR DESCRIPTION
**Pull request by dt**
Previously the adopt loop would break after adopting one job. This changes that to
ten. The previous limit intended to 'allow other nodes their fair share' of the
remaining jobs. However in practice, we've seen that adopting and 'running' a job
typically only means running a coordinator that then distributes work across the
cluster, so having many coordinators on a single node often does not significantly
change where teh actual work is executed.

Release note: none.

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
` where teh actual work is executed.`

I don't have a lot of strong feelings here. Are we having problems where jobs are not being adopted? Let's set out to do something altogether better for the next release. For now this seems okay. In general I hate constants and would prefer a private cluster setting to just hard-coding 10. 

Other than that suggestion :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45702#-:-M1_jWlOAgD-P7ImFgx2:b-9ip9t0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @spaskob)

___
*[pkg/jobs/registry.go, line 939 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45702#-M1_k2mRAiUy4ro6CrFj:-M1_k2mRAiUy4ro6CrFk:boirna0) ([raw file](https://github.com/cockroachdb/cockroach/blob/be45766a7318f249344263e42cb4f687ef5562ae/pkg/jobs/registry.go#L939)):*
> ```Go
> 
> 	var adopted int
> 	for _, row := range rows {
> ```

nit: can you move the condition checking up here?

**Review by spaskob — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45702)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @spaskob)

___
*[pkg/jobs/registry.go, line 939 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45702#-M1_k2mRAiUy4ro6CrFj:-M1a1GUI2v-r-QrVULnh:b-m3y36l) ([raw file](https://github.com/cockroachdb/cockroach/blob/be45766a7318f249344263e42cb4f687ef5562ae/pkg/jobs/registry.go#L939)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: can you move the condition checking up here?
</blockquote></details>

+1 setting the cluster setting to 0 will effectively allow us to stop adoption of jobs in this case.

**Review by dt — COMMENTED** [review]
@ajwerner it was an observation made in https://github.com/cockroachdb/cockroach/pull/44391 that in a single node cluster, when schema changes queued up a bunch of jobs, it could be blocked for a long time before getting to the later ones, since you'd only start one per 30s.

@spaskob and I talked about doing something better in 20.2, but for now it seemed like just a simple bump might be a good idea.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45702#-:-M1a2nPP0MDcrXdgzf4w:bn3q5xj)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/jobs/registry.go, line 939 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45702#-M1_k2mRAiUy4ro6CrFj:-M1a2e7O3g8OKLSiKASt:b-tnw3tf) ([raw file](https://github.com/cockroachdb/cockroach/blob/be45766a7318f249344263e42cb4f687ef5562ae/pkg/jobs/registry.go#L939)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

+1 setting the cluster setting to 0 will effectively allow us to stop adoption of jobs in this case.
</blockquote></details>

eh, i think that'd be more confusing, since spawned jobs would still be adopted, just not orphaned ones.

**Review by spaskob — APPROVED** [review]
God point but potentially this gives us a finer grained tool to control job adoption - orphaned jobs are probably the ones that are misbehaving in a cluster so it may be nice to be able to stop orphaned jobs from being re-adopted but keeping the possibility to start new  jobs that may help an operator clean up. Just a thought in favor of making 10 a cluster setting but I don't feel strongly about it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45702#-:-M1a7ArQDfqiRPcKmBpR:b-qyo22g)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45702)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/jobs/registry.go, line 939 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45702#-M1_k2mRAiUy4ro6CrFj:-M1aLjo60JZINpEpwQQJ:b-bs647d) ([raw file](https://github.com/cockroachdb/cockroach/blob/be45766a7318f249344263e42cb4f687ef5562ae/pkg/jobs/registry.go#L939)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

eh, i think that'd be more confusing, since spawned jobs would still be adopted, just not orphaned ones.
</blockquote></details>

moved it. 

does env var assuage concerns about hard-coded constant?

**Review by spaskob — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45702#-:-M1aRoZYBnjNTxUALIbV:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
