### PR TITLE
upgrades: make the schema telemetry job setup permanent

### PR DESCRIPTION
**Pull request by ajwerner**
This migration should run for every cluster.

Epic: none

Informs: https://github.com/cockroachdb/cockroach/issues/96763

Release note: None

### CODE REVIEW

**Review by chengxiong-ruan — APPROVED** [review]
LGTM

**Comment by rafiss** [comment]
bors r+

🤞

**Comment by rafiss** [comment]
flakes were https://github.com/cockroachdb/cockroach/pull/98554#discussion_r1154876846 https://github.com/cockroachdb/cockroach/issues/100369 https://github.com/cockroachdb/cockroach/issues/100356

bors r+

**Comment by ajwerner** [comment]
bors r- 

I think this needs another rewrite

**Comment by ajwerner** [comment]
Updated, will bors assuming CI passes

**Pull request merged**
