### PR TITLE
sql: add last_updated column to crdb_internal.kv_protected_ts_records

### PR DESCRIPTION
**Pull request by jayshrivastava**
This change adds a `last_updated` column to the protected timestamps virtual table. This column contains the mvcc timestamp of the row. Having this column present in this table, which is included in debug zips, improves observability when debugging issues.

Informs: https://github.com/cockroachdb/cockroach/issues/104161
Release note: None
Epic: None

### CODE REVIEW

**Comment by jayshrivastava** [comment]
This virtual table was added to `master` only, so we don't have to worry about version gates or anything like that.

**Review by ericharmeling — APPROVED** [review]
LGTM, but you might want to get @cockroachdb/cluster-observability approval as well.

**Review by THardy98 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108845#-:-NcOnPOq5LoDI5HQsRYh:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
