### PR TITLE
release-20.1: vendor: bump pebble to e6f57fcc8db7016fec64e59bd5aa9b64d050ee4e

### PR DESCRIPTION
**Pull request by petermattis**
* internal/cache: fix double-free of cache entries
* sstable: support NeedCompact method for property collectors

Release note (bug fix): Fix a nil pointer dereference in Pebble's block
cache due to a rare "double free" of a block.

Release note (bug fix): Fix Pebble to properly mark sstables for
compaction which contain range tombstones. This matches the behavior
when using RocksDB and ensures that space used for temporary storage is
reclaimed quickly.

### CODE REVIEW

**Comment by petermattis** [comment]
Huh, that vendor bump seems to have pulled in more than I expected. Let me see what is going on.

**Comment by petermattis** [comment]
Oh, I think I forgot to update my `release-20.1` branch before rebuilding vendor. Hold on, I need to redo this.

**Comment by petermattis** [comment]
Ok, got everything ship-shape again. This is ready for a look.

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48346#-:-M6VZ6f016J9OBjFLAkT:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Comment by petermattis** [comment]
TFTR!

**Pull request merged**
