### PR TITLE
roachprod: add Grafana and Prometheus inbound firewall rules for Azure

### PR DESCRIPTION
**Pull request by srosenberg**
When provisioning in Azure, roachprod will typically use an existing network security group, for a given region. However, the firewall rules for that network security group will be overwritten according to what's currently in the code.

Since grafana and prometheus can now be optionally provisioned via roachprod, we add the missing firewall rules to allow inbound traffic on ports 3000 and 9090, respectively.

Epic: none

Release note: None

### CODE REVIEW

**Comment by dbist** [comment]
LGTM

**Review by herkolategan — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93212)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dbist and @smg260)

**Comment by srosenberg** [comment]
TFTR!

**Comment by srosenberg** [comment]
bors r=herkolategan

**Pull request merged**
