### PR TITLE
[WIP] sql: support iso_8601 interval style session setting

### PR DESCRIPTION
**Pull request by mneverov**
sql: support iso_8601 interval style session setting

Related to #61167

Release note (sql change): support iso_8601 interval style session setting

### CODE REVIEW

**Review by mneverov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62313)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/62313#-MWV-xVE4ISyFuv2Y9hs:-MWV-xVE4ISyFuv2Y9ht:b-6le5c6) (no related file):*
A couple of notes/questions:
1. Parsing postgres_verbose interval style [is not supported](https://github.com/cockroachdb/cockroach/blob/6dba216f60ecb9f44f33afea76eea106a42b7546/pkg/sql/sem/tree/datum.go#L2630), I didn't add it either. 
2. Setting up the interval style should probably affect parsing interval too. Currently, there are assumptions in the `parseDInterval` method made based on the interval string itself. [One exception](https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-INTERVAL-INPUT) should be added:
```
According to the SQL standard all fields of an interval value must have the same sign, so a leading negative sign applies to all fields
```
To test run the following in PG:
```
postgres=# set intervalstyle = 'postgres';
SET
postgres=# select interval '-10 year 22 months';
     interval
------------------
 -8 years -2 mons
(1 row)

postgres=# set intervalstyle = 'sql_standard';
SET
postgres=# select interval '-10 year 22 months';
 interval
----------
 -11-10
(1 row)
```

3. I added output tests to duration_test, please let me know if it is better to move them to `logic_test/interval`.
4. Currently, CRDB comply with PG, but PG has [a bug](https://www.postgresql.org/message-id/20210323160336.GE579%40momjian.us) about printing plural time units when singular names should be printed instead. Should I address this?
5. Finally, I could not find how to plug in the session variables into fmt context, or where fmt context should be modified.

@rafiss could you please help me out with this?

---

**Comment by rafiss** [comment]
@mneverov thanks for taking this on! sorry i haven't had a chance to look at this. I will work on it this week.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62313)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mneverov)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/62313#-MWV-xVE4ISyFuv2Y9hs:-MXsGlRUEiNtfchIOoWY:bmqvvl6) (no related file):*
<details><summary><i>Previously, mneverov (Max Neverov) wrote…</i></summary><blockquote>

A couple of notes/questions:
1. Parsing postgres_verbose interval style [is not supported](https://github.com/cockroachdb/cockroach/blob/6dba216f60ecb9f44f33afea76eea106a42b7546/pkg/sql/sem/tree/datum.go#L2630), I didn't add it either. 
2. Setting up the interval style should probably affect parsing interval too. Currently, there are assumptions in the `parseDInterval` method made based on the interval string itself. [One exception](https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-INTERVAL-INPUT) should be added:
```
According to the SQL standard all fields of an interval value must have the same sign, so a leading negative sign applies to all fields
```
To test run the following in PG:
```
postgres=# set intervalstyle = 'postgres';
SET
postgres=# select interval '-10 year 22 months';
     interval
------------------
 -8 years -2 mons
(1 row)

postgres=# set intervalstyle = 'sql_standard';
SET
postgres=# select interval '-10 year 22 months';
 interval
----------
 -11-10
(1 row)
```

3. I added output tests to duration_test, please let me know if it is better to move them to `logic_test/interval`.
4. Currently, CRDB comply with PG, but PG has [a bug](https://www.postgresql.org/message-id/20210323160336.GE579%40momjian.us) about printing plural time units when singular names should be printed instead. Should I address this?
5. Finally, I could not find how to plug in the session variables into fmt context, or where fmt context should be modified.

@rafiss could you please help me out with this?
</blockquote></details>

@mneverov sorry for the delay in reviewing!

1. Excluding `postgres_verbose` sounds fine for now
2. I think IntervalStyle is only supposed to change the output format. It shouldn't affect the parsing logic. Does Postgres behave that way
3. Yes, can you please also add logic tests. They don't need to be as exhaustive; we should keep duration_test as well. That's a great test! (Also, I think adding logic tests is blocked on (5) below.)
4. Nice find! Yes, let's use singular in the correct way.
5. This is a great question. I actually don't know right now. I've spent some time thinking about it, but will need to consult with my team to figure out how we could approach this.

---
___
*[pkg/sql/exec_util.go, line 466 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62313#-MXsEpZz3_Cf2FFqCA1h:-MXsEp_-DEhcYv-i74q-:b-yhzcuy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8476c7ae5d8d37eb2521a067995ea2567b6d2baf/pkg/sql/exec_util.go#L466)):*
> ```Go
> 		int64(sessiondata.SQLStandard): "sql_standard",
> 	},
> )
> ```

can you add `.WithPublic()` so it gets documented?
___
*[pkg/util/duration/duration.go, line 387 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62313#-MXsIE2Y4MdZMNiglqBV:-MXsIE2Y4MdZMNiglqBW:b-8s0ryr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8476c7ae5d8d37eb2521a067995ea2567b6d2baf/pkg/util/duration/duration.go#L387)):*
> ```Go
> func (d Duration) FormatWithStyle(buf *bytes.Buffer, style string) {
> 	switch style {
> 	case "postgres":
> ```

would it be possible to introduce constants for these string values, and also use enums for this function?

then the enums and constants can be referenced here, and also in the session/cluster settings code. 
___
*[pkg/util/duration/duration_test.go, line 731 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62313#-MXsIdNDALnncKq_FrEU:-MXsIdNDALnncKq_FrEV:b-a0u94z) ([raw file](https://github.com/cockroachdb/cockroach/blob/8476c7ae5d8d37eb2521a067995ea2567b6d2baf/pkg/util/duration/duration_test.go#L731)):*
> ```Go
> 	}
> 
> 	for _, tt := range tests {
> ```

it would be good to add a step that makes sure we can re-parse each output, and we get the same value

actually, maybe there could also be a randomized/fuzz test that checks the format/parse roundtrip to make sure the logic is correct

**Review by mneverov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62313)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/62313#-MWV-xVE4ISyFuv2Y9hs:-MXuYbKi9meqTLrXM68h:b-2pgvoo) (no related file):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

@mneverov sorry for the delay in reviewing!

1. Excluding `postgres_verbose` sounds fine for now
2. I think IntervalStyle is only supposed to change the output format. It shouldn't affect the parsing logic. Does Postgres behave that way
3. Yes, can you please also add logic tests. They don't need to be as exhaustive; we should keep duration_test as well. That's a great test! (Also, I think adding logic tests is blocked on (5) below.)
4. Nice find! Yes, let's use singular in the correct way.
5. This is a great question. I actually don't know right now. I've spent some time thinking about it, but will need to consult with my team to figure out how we could approach this.
</blockquote></details>

Hi Rafi, no problem!

1. Ack.
2. Yes, PG changes the parsing logic, in the example above the interval is the same `select interval '-10 year 22 months';`, but the result is different `-8 years -2 mons` and `-11-10`. This is due to the SQL standard "rule": `According to the SQL standard all fields of an interval value must have the same sign, so a leading negative sign applies to all fields`. So, when invervalstyle `sql_standard` is used -10 years sum up with -22 months, and gives -11 years 10 months. In other styles the result will be -10 years +22 months = - 8 years - 2 months.
3. You're right, it's blocked by 5, will add it later.
4. Ok.
5. Got it.

As a side note a user's settings shouldn't probably affect how CRDB stores duration for internal needs.
I'm happy to continue with this, but, if you think that's more involved than expected and should be done by core maintainers - also fine with me.

---
___
*[pkg/sql/exec_util.go, line 466 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62313#-MXsEpZz3_Cf2FFqCA1h:-MY6ADG44M43yJOLM6L1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8476c7ae5d8d37eb2521a067995ea2567b6d2baf/pkg/sql/exec_util.go#L466)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can you add `.WithPublic()` so it gets documented?
</blockquote></details>

Done.
___
*[pkg/util/duration/duration.go, line 387 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62313#-MXsIE2Y4MdZMNiglqBV:-MY6AFn5CBOrImrUVZ4E:b-kkzwj6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8476c7ae5d8d37eb2521a067995ea2567b6d2baf/pkg/util/duration/duration.go#L387)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

would it be possible to introduce constants for these string values, and also use enums for this function?

then the enums and constants can be referenced here, and also in the session/cluster settings code. 
</blockquote></details>

For sure this should be changed (i should have added a note). 
I was going to define the enum, but I think it is also blocked by "how to present interval style in the fmt context". Currently, I see only 2 possible ways: as flags, then the enum should probably be defined in the context, or as a callback. If you think that the enum should be defined here and it should have simple string type - let me know I'll add it.
___
*[pkg/util/duration/duration_test.go, line 731 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62313#-MXsIdNDALnncKq_FrEU:-MY67Qw_7oxqDDIG9Ky5:b-hph1u0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8476c7ae5d8d37eb2521a067995ea2567b6d2baf/pkg/util/duration/duration_test.go#L731)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it would be good to add a step that makes sure we can re-parse each output, and we get the same value

actually, maybe there could also be a randomized/fuzz test that checks the format/parse roundtrip to make sure the logic is correct
</blockquote></details>

Nice idea about fuzzing, but we need to clarify questions 2 and 5 for that.

**Comment by otan** [comment]
this was extremely fiddly to plumb, but i have taken some of your commit and made it into #67000, so you should still have credit for it!

**Pull request closed without merging**
