### PR TITLE
vendor: bump panicparse

### PR DESCRIPTION
**Pull request by tbg**
This picks up https://github.com/maruel/panicparse/pull/74.
Without this commit, the `pkg/kv/kvserver/concurrency` datadriven
tests are flaky on Mac M1s since those tests rely on panicparse
to parse strack traces for goroutine monitoring.

Release note: None

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]

**Comment by tbg** [comment]
Huh for some reason it's not picking up the new code:

```
# github.com/maruel/panicparse/v2 v2.2.1 => github.com/cockroachdb/panicparse/v2 v2.0.0-20211103220158-604c82a44f1e
```

but v2.2.1 is https://github.com/maruel/panicparse/commit/c579e892e7ae4819228bda83a78e2526eb7c1434.

**Comment by tbg** [comment]
Ah we have a replace at the bottom of the file. I hope nothing breaks when I remove it!

**Review by nvb — APPROVED** [review]

**Comment by tbg** [comment]
bors r=erikgrinaker,nvanbenschoten

Flake is in TestLogic.

**Comment by tbg** [comment]
TestLogic/fakedist/distsql_event_log

bors r=erikgrinaker,nvanbenschoten

**Pull request merged**
