### PR TITLE
sql,pgwire: fix a host of pgwire/sql interaction bugs

### LINKED ISSUE #30692: pgwire: status parameter discrepancies
When a SQL client connects the server sends a initial batch of "status parameters" which reports configuration settings valid at session initialization.

Currently CockroachDB sends constant strings for this.

This is not correct however, because the parameters should reflect any overrides made via the client own configuration parameters that were sent initially. For example `application_name` must pick up the value provided by the client.

### LINKED ISSUE #30693: pgwire: missing status parameters
The server fails to report "TimeZone", "is_superuser" and "session_authorization" (the user name). This must be added for compatibility.

### LINKED ISSUE #30697: pgwire,sql: invalid/incomplete handling of DateStyle
The DateStyle session var / pgwire status parameter has two fields in postgres: the general format and the handling of day/month/year positions. 

The default in pg is "ISO, MDY". CockroachDB defaults to "ISO" instead.

Also a pg-compatible server should accept a composite setting with the two parts specified.

Currently CockroachDB errors out if anything else than "ISO" (without a 2nd part is specified).

### LINKED ISSUE #30698: pgwire,sql: extra_float_digits is not propagated properly from client settings
When a pgwire client sets up the connection they can provide initial client parameters like application_name.

Most clients, including lib/pq and psql, expect to be able to specify extra_float_digits because they consider the default (0) to be an unsuitable default.

Currently CockroachDB drops this configuration on the floor and defaults to 0 always. This is incorrect on its face, and can also cause clients to start reporting invalid/unexpected float values to clients.

### LINKED ISSUE #30701: sql: pg_catalog and RESET do not use defaults properly
The columns `pg_settings.boot_val` and `reset_val` are meant to report the global server defaults and session default, respectively.

In particular the column `reset_val` must report the result of using RESET.

Currently both columns report the current value of the variable, not the defaults. This is incorrect.

### LINKED ISSUE #30703: sql: incomplete support for variable `transaction_isolation`
The special value "default" means whatever the server considers default. This is currently unrecognized by CockroachDB.

### PR DESCRIPTION
**Pull request by knz**
First commit from #30691.

Fixes #30701.
Fixes #30692.
Fixes #30693.
Fixes #30697.
Fixes #30698.
Fixes #30703.
Informs #30717.

With special thanks to @benesch for asking me to poke at this.

### CODE REVIEW

**Review by benesch — APPROVED** [review]
:lgtm_strong: that review was challenging—there's a lot crammed into the last commit—but I so appreciate you doing this. Note however that I didn't review the first commit, since Andrei appears to be already reviewing that in https://github.com/cockroachdb/cockroach/pull/30691.

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, 29 of 29 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30702#-:-LNR3OcQCNPRf6ZrrXZg:bsikz8i)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/internal.go, line 265 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30702#-LNR0n7SCNFZLBAE6N8o:-LNR0n7SCNFZLBAE6N8p:b-2s63ya) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb17cd47f11032d6256f8cf9047c2caf7ad7490/pkg/sql/internal.go#L265)):*
> ```Go
> 	opName string,
> 	txn *client.Txn,
> 	sargs *SessionArgs,
> ```

Seems like this should maybe just take the username as a `string` argument? Perhaps I'm missing something.
___
*[pkg/sql/logictest/logic.go, line 918 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30702#-LNR-YXeCRWoLugnibCW:-LNR-YXeCRWoLugnibCX:b-wq8jfr) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb17cd47f11032d6256f8cf9047c2caf7ad7490/pkg/sql/logictest/logic.go#L918)):*
> ```Go
> 	if _, err := db.Exec("SET extra_float_digits = 0"); err != nil {
> 		t.Fatal(err)
> 	}
> ```

:man_facepalming: this can't have been fun to track down
___
*[pkg/sql/pgwire/conn.go, line 271 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30702#-LNR2XnL647Bg6UJjv6v:-LNR2WMqEaIkBq3Dlg5S:b-ejdjdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb17cd47f11032d6256f8cf9047c2caf7ad7490/pkg/sql/pgwire/conn.go#L271)):*
> ```Go
> 				return err
> 			}
> 		}
> ```

Is this enough of a performance win to be worth it? I don't love the idea of having a slightly-differently-configured client in unit tests than in production.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30702)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/internal.go, line 265 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30702#-LNR0n7SCNFZLBAE6N8o:-LNtGBWYCzvHT2JNICLb:b-9fmn3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb17cd47f11032d6256f8cf9047c2caf7ad7490/pkg/sql/internal.go#L265)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Seems like this should maybe just take the username as a `string` argument? Perhaps I'm missing something.
</blockquote></details>

Good suggestion. Done.
___
*[pkg/sql/logictest/logic.go, line 918 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30702#-LNR-YXeCRWoLugnibCW:-LNt8Jmf-et0TfkcPI_E:b-pi02df) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb17cd47f11032d6256f8cf9047c2caf7ad7490/pkg/sql/logictest/logic.go#L918)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

:man_facepalming: this can't have been fun to track down
</blockquote></details>

Of the two this was the simplest: we print out the list of session vars, their current value and their defautls in the "pg_catalog" logic test, and this was showing up as "2" where I was expecting "0". I then verified that "psql" leaves the default at 0 where "cockroach sql" turned it into "2" so I knew the problem was lib/pq.


The "not fun" one was the timestamp stuff -- that Go will format the timezone differently depending on whether it is "named" or not was a learning experience, to say the least.
___
*[pkg/sql/pgwire/conn.go, line 271 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30702#-LNR2XnL647Bg6UJjv6v:-LNt8lkX3z7xAy9LNmXk:b-9jdo63) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb17cd47f11032d6256f8cf9047c2caf7ad7490/pkg/sql/pgwire/conn.go#L271)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Is this enough of a performance win to be worth it? I don't love the idea of having a slightly-differently-configured client in unit tests than in production.
</blockquote></details>

This is because the test here needs to "plug in" its own query handler to intercept queries in lieu of the conn executor.

**Review by benesch — APPROVED** [review]
> Reviewed 32 of 32 files at r5, 1 of 1 files at r6, 2 of 4 files at r7, 29 of 29 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30702)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
