### PR TITLE
changefeedccl: Add a null sink.

### PR DESCRIPTION
**Pull request by miretskiy**
Add a "/dev/null" sink implementation -- a sink that discards its data.
Useful for testing.

Release Notes: None

### CODE REVIEW

**Review by stevendanna — APPROVED** [review]
:lgtm: This will be useful for testing.

One thought was whether we want to guard some of the log statements with `if log.V(2)` just to protect us against future of additional logging arguments that are more expensive to construct than the current log lines.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61526#-:-MX1L4lyDoFf2cYyi2b6:by16z38)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru)

**Review by miretskiy — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61526#-:-MX2P_bD2G__HNWAsSRx:bb6un1j)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru)

**Comment by stevendanna** [comment]
I think this is going to need to be rebased to pass CI.

**Pull request merged**
