### PR TITLE
sql: preliminary work for BatchReceiver introduction

### PR DESCRIPTION
**Pull request by yuzefovich**
See individual commits for details.

This PR extracts the preliminary work for the introduction of
`BatchReceiver` in #65289.

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
I had a couple of questions, but :lgtm:

> Reviewed 8 of 8 files at r1, 6 of 6 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, 7 of 7 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65497#-:-MaBIZMV1rNz5he8Dcsh:bkljv83)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/col/coldata/batch.go, line 349 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65497#-MaB6RfxEllUqasjUjn8:-MaB6RfyBkaZ17IxfXAH:b-vcasuy) ([raw file](https://github.com/cockroachdb/cockroach/blob/33006d5f81fd74935edee2fb23deeef22aa811a8/pkg/col/coldata/batch.go#L349)):*
> ```
> // The implementation lives in colconv package and is injected during the
> // initialization.
> var VecsToStringWithRowPrefix func(vecs []Vec, length int, sel []int, prefix string) []string
> ```

Is this done to prevent a circular dependency?
___
*[pkg/sql/colconv/batch.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65497#-MaB4ngK7NaM-N2Wb0wp:-MaB4ngK7NaM-N2Wb0wq:baownsp) ([raw file](https://github.com/cockroachdb/cockroach/blob/33006d5f81fd74935edee2fb23deeef22aa811a8/pkg/sql/colconv/batch.go#L45)):*
<details><summary><i alt="summary">Quoted 14 lines of code…</i></summary>

> ```
> 	for i := 0; i < length; i++ {
> 		builder.Reset()
> 		rowIdx := i
> 		if sel != nil {
> 			rowIdx = sel[i]
> 		}
> 		builder.WriteString(prefix + "[")
> 		for colIdx := 0; colIdx < len(vecs); colIdx++ {
> 			strs[colIdx] = converter.GetDatumColumn(colIdx)[rowIdx].String()
> 		}
> 		builder.WriteString(strings.Join(strs, " "))
> 		builder.WriteString("]")
> 		result[i] = builder.String()
> 	}
> ```
</details>


I'm not sure how much it matters, or even if it would be good, but if you wanted to you could vectorize this part even further by using `builders := make([]strings.Builder, length)` instead of a single builder and then calling `WriteString` column-wise instead of row-wise.
___
*[pkg/sql/pgwire/types.go, line 482 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65497#-MaBGrqw4QJxqSBG0f9j:-MaBGrqx8h6NnTYs3pnR:b77vjsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/10e252faf63578534d84c8394cde53a2a2b7ee24/pkg/sql/pgwire/types.go#L482)):*
<details><summary><i alt="summary">Quoted 30 lines of code…</i></summary>

> ```
> 	case *tree.DBitArray:
> 		words, lastBitsUsed := v.EncodingParts()
> 		if len(words) == 0 {
> 			b.putInt32(4)
> 		} else {
> 			// Encode the length of the output bytes. It is computed here so we don't
> 			// have to keep a buffer.
> 			// 4: the int32 of the bitLen.
> 			// 8*(len(words)-1): number of 8-byte words except the last one since it's
> 			//   partial.
> 			// (lastBitsUsed+7)/8: number of bytes that will be written in the last
> 			//   partial word. The /8 rounds down, such that the +7 will cause 1-or-more
> 			//   bits to use a byte, but 0 will not.
> 			b.putInt32(4 + int32(8*(len(words)-1)) + int32((lastBitsUsed+7)/8))
> 		}
> 		bitLen := v.BitLen()
> 		b.putInt32(int32(bitLen))
> 		var byteBuf [8]byte
> 		for i := 0; i < len(words)-1; i++ {
> 			w := words[i]
> 			binary.BigEndian.PutUint64(byteBuf[:], w)
> 			b.write(byteBuf[:])
> 		}
> 		if len(words) > 0 {
> 			w := words[len(words)-1]
> 			for i := uint(0); i < uint(lastBitsUsed); i += 8 {
> 				c := byte(w >> (56 - i))
> 				b.writeByte(c)
> 			}
> 		}
> ```
</details>


nit: Why is this case not broken out, too?

**Review by yuzefovich — COMMENTED** [review]
TFTR!

I see that Becca and Jordan might have left some comments (without pushing), so I'll hold off on merging for now and will kick it off tomorrow.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65497#-:-MaBXJBEBwzc9SxF3eh2:b-yox1rg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @michae2)

___
*[pkg/col/coldata/batch.go, line 349 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65497#-MaB6RfxEllUqasjUjn8:-MaBTYFyCgtYL4aa1ZbB:bqzcqos) ([raw file](https://github.com/cockroachdb/cockroach/blob/33006d5f81fd74935edee2fb23deeef22aa811a8/pkg/col/coldata/batch.go#L349)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

> ```
> // The implementation lives in colconv package and is injected during the
> // initialization.
> var VecsToStringWithRowPrefix func(vecs []Vec, length int, sel []int, prefix string) []string
> ```

Is this done to prevent a circular dependency?
</blockquote></details>

Yeah, exactly. We want to have the method be available in `coldata`, but it is easy to implement in `colconv`; however, the latter depends on the former, so we define a global variable in `coldata` and add `func init()` method to `colconv` to inject the implementation into the global exported variable whenever `colconv` package is loaded. It is possible that `coldata` package is loaded but `colconv` isn't, and it will lead to a NPE. However, those cases should only happen in tests, and I added a hint to the panic (during `Batch.String`).

We use this trick occasionally, one example is injecting the constructor methods for `NewProcessor`: https://github.com/cockroachdb/cockroach/blob/0553b2501af8022b5afee929c85e6dce25bf053f/pkg/sql/rowexec/processors.go#L372-L397
___
*[pkg/sql/colconv/batch.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65497#-MaB4ngK7NaM-N2Wb0wp:-MaBUSUJEtdawhWN3O1J:b-emntg4) ([raw file](https://github.com/cockroachdb/cockroach/blob/33006d5f81fd74935edee2fb23deeef22aa811a8/pkg/sql/colconv/batch.go#L45)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

> ```
> 	for i := 0; i < length; i++ {
> 		builder.Reset()
> 		rowIdx := i
> 		if sel != nil {
> 			rowIdx = sel[i]
> 		}
> 		builder.WriteString(prefix + "[")
> 		for colIdx := 0; colIdx < len(vecs); colIdx++ {
> 			strs[colIdx] = converter.GetDatumColumn(colIdx)[rowIdx].String()
> 		}
> 		builder.WriteString(strings.Join(strs, " "))
> 		builder.WriteString("]")
> 		result[i] = builder.String()
> 	}
> ```

I'm not sure how much it matters, or even if it would be good, but if you wanted to you could vectorize this part even further by using `builders := make([]strings.Builder, length)` instead of a single builder and then calling `WriteString` column-wise instead of row-wise.
</blockquote></details>

Yeah, it's possible, but my feeling is that it would be slightly worse. If we're calling this method, then we must not be on the hot path, so I would worry more about the increase in allocations which will occur because we wouldn't be reusing any of the memory allocated by the builders. I say that we're not on the hot path because I think we usually call `Batch.String()` only for debugging purposes and `VecsToStringWithRowPrefix` will only be used by tracing, which is also implies slow path.
___
*[pkg/sql/pgwire/types.go, line 482 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65497#-MaBGrqw4QJxqSBG0f9j:-MaBWzq74JfMfgSknCkQ:b-doysv9) ([raw file](https://github.com/cockroachdb/cockroach/blob/10e252faf63578534d84c8394cde53a2a2b7ee24/pkg/sql/pgwire/types.go#L482)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

> ```
> 	case *tree.DBitArray:
> 		words, lastBitsUsed := v.EncodingParts()
> 		if len(words) == 0 {
> 			b.putInt32(4)
> 		} else {
> 			// Encode the length of the output bytes. It is computed here so we don't
> 			// have to keep a buffer.
> 			// 4: the int32 of the bitLen.
> 			// 8*(len(words)-1): number of 8-byte words except the last one since it's
> 			//   partial.
> 			// (lastBitsUsed+7)/8: number of bytes that will be written in the last
> 			//   partial word. The /8 rounds down, such that the +7 will cause 1-or-more
> 			//   bits to use a byte, but 0 will not.
> 			b.putInt32(4 + int32(8*(len(words)-1)) + int32((lastBitsUsed+7)/8))
> 		}
> 		bitLen := v.BitLen()
> 		b.putInt32(int32(bitLen))
> 		var byteBuf [8]byte
> 		for i := 0; i < len(words)-1; i++ {
> 			w := words[i]
> 			binary.BigEndian.PutUint64(byteBuf[:], w)
> 			b.write(byteBuf[:])
> 		}
> 		if len(words) > 0 {
> 			w := words[len(words)-1]
> 			for i := uint(0); i < uint(lastBitsUsed); i += 8 {
> 				c := byte(w >> (56 - i))
> 				b.writeByte(c)
> 			}
> 		}
> ```

nit: Why is this case not broken out, too?
</blockquote></details>

I broke out only the cases for which we have native representation in the vectorized engine (i.e. those that are not supported via the datum vector). Over time, whenever we add native representation for a new type, we'll need to break that type out too.

**Review by michae2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65497)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/col/coldata/batch.go, line 349 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65497#-MaB6RfxEllUqasjUjn8:-MaEnFtf4S9CKjpIa09F:bpykp6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/33006d5f81fd74935edee2fb23deeef22aa811a8/pkg/col/coldata/batch.go#L349)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Yeah, exactly. We want to have the method be available in `coldata`, but it is easy to implement in `colconv`; however, the latter depends on the former, so we define a global variable in `coldata` and add `func init()` method to `colconv` to inject the implementation into the global exported variable whenever `colconv` package is loaded. It is possible that `coldata` package is loaded but `colconv` isn't, and it will lead to a NPE. However, those cases should only happen in tests, and I added a hint to the panic (during `Batch.String`).

We use this trick occasionally, one example is injecting the constructor methods for `NewProcessor`: https://github.com/cockroachdb/cockroach/blob/0553b2501af8022b5afee929c85e6dce25bf053f/pkg/sql/rowexec/processors.go#L372-L397
</blockquote></details>

Interesting! Thank you!
___
*[pkg/sql/colconv/batch.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65497#-MaB4ngK7NaM-N2Wb0wp:-MaEnMRaEHBHRfFI5Wzo:b-dxcbu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/33006d5f81fd74935edee2fb23deeef22aa811a8/pkg/sql/colconv/batch.go#L45)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Yeah, it's possible, but my feeling is that it would be slightly worse. If we're calling this method, then we must not be on the hot path, so I would worry more about the increase in allocations which will occur because we wouldn't be reusing any of the memory allocated by the builders. I say that we're not on the hot path because I think we usually call `Batch.String()` only for debugging purposes and `VecsToStringWithRowPrefix` will only be used by tracing, which is also implies slow path.
</blockquote></details>

Makes sense!
___
*[pkg/sql/pgwire/types.go, line 482 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65497#-MaBGrqw4QJxqSBG0f9j:-MaEnPRN3hmmGvwhJKn2:b-qpv3gk) ([raw file](https://github.com/cockroachdb/cockroach/blob/10e252faf63578534d84c8394cde53a2a2b7ee24/pkg/sql/pgwire/types.go#L482)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I broke out only the cases for which we have native representation in the vectorized engine (i.e. those that are not supported via the datum vector). Over time, whenever we add native representation for a new type, we'll need to break that type out too.
</blockquote></details>

OK, that's fine.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
