### PR TITLE
sql: in schema changer, wait for leases of referenced descriptors to update

### LINKED ISSUE #40200: sql: flaky drop_constraint_in_txn schema change logic test
I've seen `schema_change_in_txn/drop_constraint_in_txn` fail intermittently on my PRs that should have nothing to do with the test. Here is the test output:
```
------- Stdout: -------
--- progress: testdata/logic_test/fk_opt: 517 statements/queries
--- done: testdata/logic_test/parallel_stmts_compat with config local: 93 tests, 0 failures
--- done: testdata/logic_test/union with config local: 48 tests, 0 failures
=== CONT  TestLogic/local/zero
=== CONT  TestLogic/local/with-opt
--- done: testdata/logic_test/zone_config with config local: 17 tests, 0 failures
--- total progress: 6842 statements/queries
=== CONT  TestLogic/local/with
                logic.go:1864: 
                    
                    testdata/logic_test/schema_change_in_txn:1688: 
                    expected success, but found
                    (40001) restart transaction: TransactionRetryWithProtoRefreshError: cannot publish new versions for tables: [{t2 116 5} {t 115 11}], old versions still in use
                logic.go:1278: 
                     pq: restart transaction: TransactionRetryWithProtoRefreshError: cannot publish new versions for tables: [{t2 116 5} {t 115 11}], old versions still in use
```
And the link to the build https://teamcity.cockroachdb.com/viewLog.html?buildId=1452932&buildTypeId=Cockroach_UnitTests.

### LINKED ISSUE #52539: sql: failure to COMMIT schema changes with expressions with UDTs
**Error:**

The following error occurs sporadically when creating a computed column with a UDT in the expression in a transaction.

```
(40001) restart transaction: TransactionRetryWithProtoRefreshError: cannot publish new versions for descriptors: [{enum 53 3} {_enum 54 3}], old versions still in use
```

Could this be related to https://github.com/cockroachdb/cockroach/issues/40200?

**To Reproduce**

The failure should reproduce within a few minutes of stressing.

Run:

```
 make stress PKG='./pkg/sql/logictest' TESTS='TestLogic/fakedist/__test'
```

With the contents of `__test` as:

```
statement ok
SET experimental_partial_indexes = true;
SET experimental_enable_enums = true;

statement ok
CREATE TYPE enum AS ENUM ('foo', 'bar', 'baz')

statement ok
CREATE TABLE s (a enum)

statement ok
INSERT INTO s VALUES ('foo'), ('bar')

statement ok
ALTER TABLE s ADD COLUMN b enum AS (a) STORED;

query TT rowsort
SELECT * FROM s
----
foo  foo
bar  bar

statement ok
BEGIN

statement ok
CREATE TABLE t (a enum)

statement ok
INSERT INTO t VALUES ('foo'), ('bar')

statement ok
ALTER TABLE t ADD COLUMN b enum AS (a) STORED;

statement ok
COMMIT

query TT rowsort
SELECT * FROM t
----
foo  foo
bar  bar
```

It also reproduces when backfilling partial indexes in #52213, with the below test:

```
statement ok
SET experimental_partial_indexes = true;
SET experimental_enable_enums = true;

statement ok
CREATE TYPE enum AS ENUM ('foo', 'bar', 'baz')

statement ok
CREATE TABLE h (a INT, b enum)

statement ok
INSERT INTO h VALUES (1, 'foo'), (2, 'bar')

statement ok
CREATE INDEX a_b_foo_idx ON h (a) WHERE b = 'foo'

query IT rowsort
SELECT * FROM h@a_b_foo_idx WHERE b = 'foo'
----
1  foo

statement ok
BEGIN

statement ok
CREATE TABLE t (a INT, b enum)

statement ok
INSERT INTO t VALUES (1, 'foo'), (2, 'bar')

# CREATE INDEX i ON t (a) WHERE b = 'foo'
statement ok
CREATE INDEX i ON t (a) WHERE b = 'foo'

statement ok
COMMIT

query IT rowsort
SELECT * FROM t@i WHERE b = 'foo'
----
1  foo
```

**Environment:**

```
Build Tag:        v20.2.0-alpha.1-1917-g09804ffcfb
Build Time:       2020/08/08 16:04:17
Distribution:     CCL
Platform:         darwin amd64 (x86_64-apple-darwin19.6.0)
Go Version:       go1.14.4
C Compiler:       4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)
Build Commit ID:  09804ffcfbd511d2ce8d745a5eca2586bc6c96de
Build Type:       development
```

### PR DESCRIPTION
**Pull request by ajwerner**
In 20.1 we moved the schema changer over to utilize the jobs infrastructure.
Prior to that change, after committing a sql transaction we'd kick off the
schema changer to run for the relevant mutations and then we'd wait for all
modified descriptors to have just one version (after the schema change). In
20.1 we decided for descriptors referenced in schema changes to also create
schema change jobs that have an InvalidMutationID which leads to the job
merely waiting for one version for that descriptor. Unfortunately, that
solution doesn't generally work. In particular, it doesn't work in cases
where we are add an fk constraint that we need to mark validated at the
end and it doesn't work in cases where we want to remove a type back
reference after dropping a column or when adding a type reference.

Realistically, when the schema change job ends up touching multiple
descriptors, we need to make sure we wait for the leases to update
for all of them.

You might think that this could lead directly to eliminating the
InvalidMutationID schema change jobs, but I'm not convinced that
that always follows and so I'm leaving that for later.

It turns out that I don't think the type portions of this represent
correctness problems as the type references just used for type DDLs but
I do think for tables it might be worse. At the very least it might mean
that query plans a tad longer to reflect fk relationships.

Fixes #52539.
Fixes #40200.

Release note (bug fix): Fixed a bug which allowed statements after a
schema change to fail to observe side-effects of that change on referenced
tables.

### CODE REVIEW

**Review by thoszhang — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54434)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by ajwerner** [comment]
TFTR!

bors r=lucy-zhang

**Comment by lucy-zhang** [comment]
I don't think bors picked this up.

bors r+

**Comment by ajwerner** [comment]
docker infra flake:

`[18:39:50]docker: error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/f1/f1bf4a707d2dbeeaa650a18eef13c05dc5a5f4009bf1500de2a487b8c9189d50/data?verify=1600284580-HSvsdz47%2F2RQz5j5p1GH%2BZaZnLI%3D: net/http: TLS handshake timeout.`

bors r+

**Pull request merged**
