### PR TITLE
settings,*: use the option pattern with the setting register functions

### LINKED ISSUE #109011: settings: use the function option passing style for the register function
We have too many variants of the `Register` functions with combinations of argument types.

The validation and visibility for example could be specified by options in a variable-length argument list.

see: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/1881669848/Go+function+argument+patterns

Epic: CRDB-28893

Jira issue: CRDB-30739

### PR DESCRIPTION
**Pull request by knz**
First commit from  #108902.
Fixes #109011.
Informs #109046.

TLDR: this patch introduces the "functional option style" in the
settings API.

For example, this call:
```go
var s = func() *settings.BoolSetting {
  s := settings.RegisterBoolSetting(...).WithPublic()
  s.SetReportable(true)
}()
```

can now be written as:
```go
var s = settings.RegisterBoolSetting(...,
  settings.WithPublic,
  settings.WithReportable(true),
)
```

Internally, the register function now take a last argument of type
`...SettingOption`.
The following options are defined:

```go
var Retired SettingOption
var WithPublic SettingOption
func WithReportable(reportable bool) SettingOption
func WithVisibility(v Visibility) SettingOption

func WithValidateDuration(fn func(time.Duration) error) SettingOption // NEW
var NonNegativeDuration SettingOption
var PositiveDuration SettingOption
func NonNegativeDurationWithMaximum(maxValue time.Duration) SettingOption
func DurationWithMinimum(minValue time.Duration) SettingOption // RENAMED
func DurationWithMinimumOrZeroDisable(minValue time.Duration) SettingOption // NEW
func DurationInRange(minVal, maxVal int64) SettingOption // NEW

func WithValidateFloat(fn func(float64) error) SettingOption // NEW
var NonNegativeFloat SettingOption
var PositiveFloat SettingOption
func NonNegativeFloatWithMaximum(maxValue float64) SettingOption
func FloatWithMinimum(minValue float64) SettingOption // NEW
func FloatWithMinimumOrZeroDisable(minValue float64) SettingOption // NEW
var NonZeroFloat SettingOption // NEW
var Fraction SettingOption // NEW
var FractionUpperExclusive SettingOption // NEW
func FloatInRange(minVal, maxVal float64) SettingOption // NEW
func FloatInRangeUpperExclusive(minVal, maxVal float64) SettingOption // NEW

func WithValidateInt(fn func(int64) error) SettingOption // NEW
var NonNegativeInt SettingOption
var PositiveInt SettingOption
func NonNegativeIntWithMaximum(maxValue int64) SettingOption
func IntWithMinimum(minValue int64) SettingOption // NEW
func IntInRange(minVal, maxVal int64) SettingOption // NEW
func IntInRangeOrZeroDisable(minVal, maxVal int64) SettingOption // NEW

func WithValidateProto(fn func(*Values, protoutil.Message) error) SettingOption // NEW

func WithValidateString(fn func(*Values, string) error) SettingOption // NEW

func ByteSizeWithMinimum(minVal int64) SettingOption // NEW
```

Release note: None
Epic: CRDB-28893

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 159 of 159 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109012)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @stevendanna)

___
*[`-- commits` line 98 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109012#-Nc8ur5MCzsL23RSMzb8):*
Should we modify "NonNegative...WithMinimum" to be "...WithMinimum"? It seems somewhat redundant to have both "non-negative" (which implies "with minimum zero") and "with minimum". It seems like we always have the minimum value greater than zero, so it's non-negative by definition.
___
*[`pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go` line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109012#-Nc8otBS0_8jlfSAGurd:-Nc8otBS0_8jlfSAGure:b-neb37y) ([raw file](https://github.com/cockroachdb/cockroach/blob/efa3cfa5574d67640ad58d8437a259edd61dbf40/pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go#L104)):*
> ```Go
> 
> // checkDurationInRange returns a function used to validate duration cluster
> // settings. Because these values are currently settable by the tenant, we need
> ```

nit: perhaps preserve the second sentence as the comments on where `settings.DurationInRange` is now used.
___
*[`pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go` line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109012#-Nc8pAua6CquFU6dx9M3:-Nc8pAua6CquFU6dx9M4:bnxovkr) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd64e290f7c31c045e18c9b34f646dd55dc36617/pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go#L56)):*
> ```Go
> 	"the minimum timestamp between flushes; flushes may still occur if internal buffers fill up",
> 	5*time.Second,
> 	settings.WithPublic,
> ```

This wasn't public, was this change intentional?
___
*[`pkg/settings/byte_size.go` line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109012#-Nc8sHUX6nzi_weKlXn_:-Nc8sHUX6nzi_weKlXna:bbwvm9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd64e290f7c31c045e18c9b34f646dd55dc36617/pkg/settings/byte_size.go#L54)):*
> ```Go
> 		hasExplicitValidationFn := false
> 		for _, opt := range opts {
> 			if opt.validateProtoFn != nil ||
> ```

nit: should we flip these checks from "blocklist" to "allowlist"? I.e. we'd only allow `commonOpt` (which is skipped over) and `validateInt64Fn` (which is called) to be non-nil, and we would panic in all other cases. This seems more bullet-proof in case new validation options are added (and a bit less verbose too).
___
*[`pkg/settings/float.go` line 220 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109012#-Nc8tEln-EKDCtfsa2YY:-Nc8tEln-EKDCtfsa2YZ:bgtxre2) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd64e290f7c31c045e18c9b34f646dd55dc36617/pkg/settings/float.go#L220)):*
> ```Go
> 
> // FractionUpperExclusive requires the setting to be in the interval
> // [0, 1]. It can be passed to RegisterFloatSetting.
> ```

nit: I think we usually highlight "upper exclusive" as `[0, 1)` interval.
___
*[`pkg/settings/options.go` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109012#-Nc8vPtP7fsWNPFv0pa8:-Nc8vPtQEtZekOPNl27t:btj0ctq) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd64e290f7c31c045e18c9b34f646dd55dc36617/pkg/settings/options.go#L1)):*
> ```Go
> // Copyright 2021 The Cockroach Authors.
> ```

nit: `s/2021/2023/`.
___
*[`pkg/settings/options.go` line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109012#-Nc8vZ6l13xTAl1Hppfv:-Nc8vZ6l13xTAl1Hppfw:b-wf8bdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd64e290f7c31c045e18c9b34f646dd55dc36617/pkg/settings/options.go#L52)):*
> ```Go
> // retiredSettings map (in settings/registry.go). The Retired option
> // exists for cases where there is a need to maintain compatibility
> // with autommation.
> ```

nit: `s/autommation/automation/`.
___
*[`pkg/sql/storageparam/tablestorageparam/table_storage_param.go` line 553 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109012#-Nc8x8Om8FWYauk03y17:-Nc8x8Om8FWYauk03y18:b-drcbzg) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd64e290f7c31c045e18c9b34f646dd55dc36617/pkg/sql/storageparam/tablestorageparam/table_storage_param.go#L553)):*
> ```Go
> 	return func(intVal int64) error {
> 		if intVal < 0 {
> 			return errors.Newf("cannot be set to a negative interger: %d", intVal)
> ```

nit: `s/interger/integer/`.
___
*[`pkg/util/admission/scheduler_latency_listener.go` line 223 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109012#-Nc8xGN85hHjjquTzsAt:-Nc8xGN85hHjjquTzsAu:bve8rf4) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd64e290f7c31c045e18c9b34f646dd55dc36617/pkg/util/admission/scheduler_latency_listener.go#L223)):*
> ```Go
> 		"sets the floor on per-node elastic work CPU % utilization",
> 		0.05, // 5%
> 		settings.FloatInRange(0.05, 1.0),
> ```

Here minimum used to 0.01.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109012)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna and @yuzefovich)

___
*[`-- commits` line 98 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109012#-Nc8ur5MCzsL23RSMzb8):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Should we modify "NonNegative...WithMinimum" to be "...WithMinimum"? It seems somewhat redundant to have both "non-negative" (which implies "with minimum zero") and "with minimum". It seems like we always have the minimum value greater than zero, so it's non-negative by definition.
</blockquote></details>

There's a lot of uses of the other NonNegative functions already. I felt the patch was already big enough as it is.

If you insist, I can do this - it's a simple search-and-replace.
___
*[`pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go` line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109012#-Nc8otBS0_8jlfSAGurd:-Nc9S-GW3q9jUVBO05EM:bucbf28) ([raw file](https://github.com/cockroachdb/cockroach/blob/efa3cfa5574d67640ad58d8437a259edd61dbf40/pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go#L104)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: perhaps preserve the second sentence as the comments on where `settings.DurationInRange` is now used.
</blockquote></details>

It was inaccurate - since this was written the class was changed to TenantReadOnly.
___
*[`pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go` line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109012#-Nc8pAua6CquFU6dx9M3:-Nc9S7hm6i6LU5OD5Ob7:bndflpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd64e290f7c31c045e18c9b34f646dd55dc36617/pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go#L56)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

This wasn't public, was this change intentional?
</blockquote></details>

It was public (`RegisterPublicDurationSetting...` in the original call)
___
*[`pkg/settings/byte_size.go` line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109012#-Nc8sHUX6nzi_weKlXn_:-Nc9SEnO-1hmmYKW0IQc:b-ddvxap) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd64e290f7c31c045e18c9b34f646dd55dc36617/pkg/settings/byte_size.go#L54)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: should we flip these checks from "blocklist" to "allowlist"? I.e. we'd only allow `commonOpt` (which is skipped over) and `validateInt64Fn` (which is called) to be non-nil, and we would panic in all other cases. This seems more bullet-proof in case new validation options are added (and a bit less verbose too).
</blockquote></details>

Can you show me how you would write that? I don't see it.
___
*[`pkg/settings/float.go` line 220 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109012#-Nc8tEln-EKDCtfsa2YY:-Nc9SKQ235IQxq8i2_Ss:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd64e290f7c31c045e18c9b34f646dd55dc36617/pkg/settings/float.go#L220)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I think we usually highlight "upper exclusive" as `[0, 1)` interval.
</blockquote></details>

Done.
___
*[`pkg/settings/options.go` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109012#-Nc8vPtP7fsWNPFv0pa8:-Nc9SMqQ7-fyGJ8UISdh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd64e290f7c31c045e18c9b34f646dd55dc36617/pkg/settings/options.go#L1)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `s/2021/2023/`.
</blockquote></details>

Done.
___
*[`pkg/settings/options.go` line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109012#-Nc8vZ6l13xTAl1Hppfv:-Nc9SRjsCWkdaaiHlzpN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd64e290f7c31c045e18c9b34f646dd55dc36617/pkg/settings/options.go#L52)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `s/autommation/automation/`.
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109012)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna and @yuzefovich)

___
*[`pkg/sql/storageparam/tablestorageparam/table_storage_param.go` line 553 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109012#-Nc8x8Om8FWYauk03y17:-Nc9WfeT0yfaTVpyQvx8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd64e290f7c31c045e18c9b34f646dd55dc36617/pkg/sql/storageparam/tablestorageparam/table_storage_param.go#L553)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `s/interger/integer/`.
</blockquote></details>

Done.
___
*[`pkg/util/admission/scheduler_latency_listener.go` line 223 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109012#-Nc8xGN85hHjjquTzsAt:-Nc9Wgoz0tDf7XHMoCPC:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd64e290f7c31c045e18c9b34f646dd55dc36617/pkg/util/admission/scheduler_latency_listener.go#L223)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Here minimum used to 0.01.
</blockquote></details>

Done

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 4 of 163 files at r3, 161 of 161 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109012#-:-Nc9aGkp3pUE8Uy63L6M:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @stevendanna)

___
*[`-- commits` line 98 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109012#-Nc8ur5MCzsL23RSMzb8):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

There's a lot of uses of the other NonNegative functions already. I felt the patch was already big enough as it is.

If you insist, I can do this - it's a simple search-and-replace.
</blockquote></details>

In other use cases "non-negative" prefix makes sense since it's complimentary to the other constraint imposed by the validation function (or it's the only constraint), but "non-negative with minimum" is a bit redundant. I don't feel strongly about this to insist, so I'll leave it up to you.
___
*[`pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go` line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109012#-Nc8otBS0_8jlfSAGurd:-Nc9ZypT6Gn3bxP-0VYh:b50gq43) ([raw file](https://github.com/cockroachdb/cockroach/blob/efa3cfa5574d67640ad58d8437a259edd61dbf40/pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go#L104)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

It was inaccurate - since this was written the class was changed to TenantReadOnly.
</blockquote></details>

Ack, makes sense.
___
*[`pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go` line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109012#-Nc8pAua6CquFU6dx9M3:-Nc9_1ua6c-tfGYAgaP7:b-fcflxe) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd64e290f7c31c045e18c9b34f646dd55dc36617/pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go#L56)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

It was public (`RegisterPublicDurationSetting...` in the original call)
</blockquote></details>

Right, missed that, nvm.
___
*[`pkg/settings/byte_size.go` line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109012#-Nc8sHUX6nzi_weKlXn_:-Nc9_GVMBaGMmphLWlXB:b74zcdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd64e290f7c31c045e18c9b34f646dd55dc36617/pkg/settings/byte_size.go#L54)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Can you show me how you would write that? I don't see it.
</blockquote></details>

I was thinking something like
```
switch {
  case opt.commonOpt != nil:
    // not a validation option, skip it
  case opt.validateInt64Fn != nil:
    hasExplicitValidationFn = true
    ... fn(v)
  default:
    panic(errors.AssertionFailedf("wrong validator type"))
}
```

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109012)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @stevendanna and @yuzefovich)

___
*[`-- commits` line 98 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109012#-Nc8ur5MCzsL23RSMzb8):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

In other use cases "non-negative" prefix makes sense since it's complimentary to the other constraint imposed by the validation function (or it's the only constraint), but "non-negative with minimum" is a bit redundant. I don't feel strongly about this to insist, so I'll leave it up to you.
</blockquote></details>

Done.
___
*[`pkg/settings/byte_size.go` line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109012#-Nc8sHUX6nzi_weKlXn_:-NcBlo-p1ItI0JApD5jH:b-3fc7uw) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd64e290f7c31c045e18c9b34f646dd55dc36617/pkg/settings/byte_size.go#L54)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I was thinking something like
```
switch {
  case opt.commonOpt != nil:
    // not a validation option, skip it
  case opt.validateInt64Fn != nil:
    hasExplicitValidationFn = true
    ... fn(v)
  default:
    panic(errors.AssertionFailedf("wrong validator type"))
}
```
</blockquote></details>

nice. Done.

**Comment by knz** [comment]
TFYR!

bors r=yuzefovich

**Comment by knz** [comment]
bors r=yuzefovich

**Pull request merged**
