### PR TITLE
[WIP] opt: create infrastructure for testing logical props and stats

### LINKED ISSUE #30273: design and implement infrastructure for testing logical props and especially stats
Currently, the only way to "unit" test logical props and statistics is to come up with an expression that exercises whatever is being tested and figure out a SQL query for which the optimal plan is the desired expression. Both of these steps are non-trivial, and they are also fragile: a change in costing or statistics can easily invalidate existing tests.

We need to come up with a better framework; one in which we can build an single operator and specify logical props and stats for its children. Ideally it would be something that supports `-rewrite`.

CC @rytaft @andy-kimball

### PR DESCRIPTION
**Pull request by rytaft**
This commit prototypes a new framework for testing logical properties
and statistics for relational expressions. It allows users to specify
the logical properties and stats of input expressions as well as
privates with a simple YAML interface, and checks that the output
properties and stats match expectation.

For example, the following test checks that the ScanExpr properties
are being built correctly, given attributes in the ScanPrivate:
```
props operator=scan
table: a
cols: [1, 2]
constraint: "/1: [/1 - /2]"
----
scan a
 ├── columns: x:1(int!null) y:2(int)
 ├── constraint: /1: [/1 - /2]
 ├── key: (1)
 └── fd: (1)-->(2)
```
This interface is easier to use for testing properties than the current
infrastructure, which requires constructing a SQL query that has the
desired properties.

The only downside with the new framework is that it requires custom code
for each operator to parse the YAML and build the relational expression.
I have prototyped two operators, Scan and Project, but more work needs
to be done to support other operators. It seems likely that optgen can be
used for this purpose, but before I spend time writing optgen code I
wanted to get some feedback about the interface and overall design.

Fixes #30273

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Nice work! I like the test format very much. This definitely makes it easier to write targeted tests.

The way I see this working with optgen is to generate:
 - the type definitions for the specs, using a map that helps it figure out the type inside the spec (usually a string) based on the type of the op field.
 -  code to convert a filled-out spec to the corresponding `Expr`, which uses `parse<TypeName>` functions that we define in testutils (e.g. `parseColSet`, `parseTableID` etc. - I think the collection of types referenced in the op definitions is fairly small).

It's not clear to me whether getting code generation to work is worth it though - we're really only interested in the relational operators and there aren't that many of them..

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32103#-:-LQFl5tV1N69JjQlOv6b:bg5tjzk)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by vivekmenezes** [comment]
@rytaft are you planning to move forward with this PR?

**Comment by RaduBerinde** [comment]
I could look at taking it over as part of my QA rotation.

**Comment by rytaft** [comment]
I haven't had time to work on it since the QA rotation. Radu, if you are on QA rotation soon and want to take it over please be my guest! Otherwise I can try to get to it once the release work is done...

**Pull request closed without merging**
