### PR TITLE
sql: add support for NOT VALID Foreign Key constraints

### PR DESCRIPTION
**Pull request by tyler314**
Implemented the support of not validating an ALTER TABLE foreign key constraint to a table. Within alter_table.go we set the validity of the foreign key reference to be unvalidated, and within shema_changer.go we then check the case where the foreign key being added is unvalidated and do not check its validity.

This allows users to create a reference between two non-empty tables who's entries don't comply with the constraint when it's first added.

### CODE REVIEW

**Review by thoszhang — COMMENTED** [review]
Your commit doesn't seem to have a message beyond the first line (?). You can use what you have in the PR description and amend your PR (and add a release note). The last line should be something like `This allows users to create a FK reference between two tables whose rows don't comply with the constraint when it's first added` (no need for "non-empty".)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-:-LjHH39_4tcfsXXsh1bq:bvz5nnc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @Tyler314)

___
*[pkg/sql/create_table.go, line 441 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjHDcMQ2lifss28Om5X:-LjHDcMQ2lifss28Om5Y:b8tsxkg) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb16f9f44e03099a80bf449125d25e1512694c8a/pkg/sql/create_table.go#L441)):*
> ```Go
> // The passed Txn is used to lookup databases to qualify names in error messages
> // but if nil, will result in unqualified names in those errors.
> func ResolveFK(
> ```

Can you add to the doc comment explaining the `validationState` parameter? I'd also rename it to `validationBehavior`.
___
*[pkg/sql/schema_changer.go, line 1306 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjHDsXl5ECK3p4yvhDT:-LjHDsXl5ECK3p4yvhDU:b-3vm6wr) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb16f9f44e03099a80bf449125d25e1512694c8a/pkg/sql/schema_changer.go#L1306)):*
> ```Go
> 	now := timeutil.Now().UnixNano()
> 
> 	// Get the other tables whose foreign key backreferences need to be removed.
> ```

Can you add a brief comment to explain that we need to call `PublishMultiple()` to potentially add foreign key backreferences?
___
*[pkg/sql/schema_changer.go, line 1384 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjHDAwV2_2QffHU3nGD:-LjHDAwV2_2QffHU3nGE:bgl7sn7) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb16f9f44e03099a80bf449125d25e1512694c8a/pkg/sql/schema_changer.go#L1384)):*
> ```Go
> 					return err
> 				}
> 				// TODO (tyler): Consider case where a retry is done and this method is called again
> ```

This isn't necessary
___
*[pkg/sql/logictest/testdata/logic_test/fk, line 1393 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjHEZH3AeOpAMI77XpB:-LjHEZH3AeOpAMI77XpC:bsd6yvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb16f9f44e03099a80bf449125d25e1512694c8a/pkg/sql/logictest/testdata/logic_test/fk#L1393)):*
> ```
> # currently don't support adding a validated FK in the same transaction as
> # CREATE TABLE
> # TODO (lucy): Once this is no longer true (and we support adding NOT VALID
> ```

This test should be updated now, per the TODO. I think it should be sufficient to remove the BEGIN and COMMIT, and add a NOT VALID to the ALTER TABLE statement.

There's also another test that needs to be updated in the same way, in pkg/sql/opt/exec/execbuilder/testdata/fk.
___
*[pkg/sql/logictest/testdata/logic_test/fk, line 1438 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjHGRmFDY6Cqs6fUUmg:-LjHGRmFDY6Cqs6fUUmh:b7m1oyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb16f9f44e03099a80bf449125d25e1512694c8a/pkg/sql/logictest/testdata/logic_test/fk#L1438)):*
> ```
> DROP TABLE a, b
> 
> subtest Composite_Simple
> ```

Ideally we'd also want to bring back all the logic tests that test the behavior of VALIDATE CONSTRAINT (I originally took them all out in #37433, which started validating all added FKs), now that we can create unvalidated FK constraints. It doesn't have to be in this PR, so you can either put them back in now (you can just copy them from that PR diff and add NOT VALID everywhere) or add a TODO to do it later.
___
*[pkg/sql/logictest/testdata/logic_test/fk, line 2105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjHFNRoEOMnZWKyHIn6:-LjHFNRoEOMnZWKyHIn7:b4kttwv) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb16f9f44e03099a80bf449125d25e1512694c8a/pkg/sql/logictest/testdata/logic_test/fk#L2105)):*
> ```
> DROP TABLE t2, t2 CASCADE
> 
> statement ok
> ```

can you make this a subtest (and drop all the tables at the end)?
___
*[pkg/sql/sqlbase/structured.go, line 2377 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjHBYka3Vrwvof5mV60:-LjHBYka3Vrwvof5mV61:brga475) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb16f9f44e03099a80bf449125d25e1512694c8a/pkg/sql/sqlbase/structured.go#L2377)):*
> ```Go
> 
> // MakeMutationComplete updates the descriptor upon completion of a mutation.
> func (desc *MutableTableDescriptor) MakeMutationComplete(m DescriptorMutation) error {
> ```

Can you add to the doc comment to indicate
1. the difference in behavior between validating vs. unvalidated constraints (i.e., validating constraints are assumed to have been added earlier and just need to be marked as validated, whereas unvalidated constraints have not been added earlier and need to be added); and
2. the fact that this method can't add backreferences for foreign keys, and that those need to be added separately by the caller as needed?

I'd also add a TODO to somehow refactor this so that the FK reference and backreference are added in the same place (maybe by passing in a closure to this method?), since this situation isn't ideal.
___
*[pkg/sql/sqlbase/structured.go, line 2389 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjHCyo42PIDbNwjuAHT:-LjHCyo42PIDbNwjuAHU:bagcrls) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb16f9f44e03099a80bf449125d25e1512694c8a/pkg/sql/sqlbase/structured.go#L2389)):*
> ```Go
> 			}
> 
> 		case *DescriptorMutation_Constraint:
> ```

It'd be good to also add some inline comments to explain why we need all these cases.

**Review by tyler314 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38663)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/sql/create_table.go, line 441 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjHDcMQ2lifss28Om5X:-LjH_fbs1iKPX-VS8RYH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb16f9f44e03099a80bf449125d25e1512694c8a/pkg/sql/create_table.go#L441)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Can you add to the doc comment explaining the `validationState` parameter? I'd also rename it to `validationBehavior`.
</blockquote></details>

Done.
___
*[pkg/sql/schema_changer.go, line 1306 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjHDsXl5ECK3p4yvhDT:-LjHcET73Q0XBuxTY5N9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb16f9f44e03099a80bf449125d25e1512694c8a/pkg/sql/schema_changer.go#L1306)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Can you add a brief comment to explain that we need to call `PublishMultiple()` to potentially add foreign key backreferences?
</blockquote></details>

Done.
___
*[pkg/sql/schema_changer.go, line 1384 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjHDAwV2_2QffHU3nGD:-LjHcMvaC5Ljb6z_7fCN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb16f9f44e03099a80bf449125d25e1512694c8a/pkg/sql/schema_changer.go#L1384)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

This isn't necessary
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/fk, line 1393 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjHEZH3AeOpAMI77XpB:-LjHnOT7-vMA56H8p9xW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb16f9f44e03099a80bf449125d25e1512694c8a/pkg/sql/logictest/testdata/logic_test/fk#L1393)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

This test should be updated now, per the TODO. I think it should be sufficient to remove the BEGIN and COMMIT, and add a NOT VALID to the ALTER TABLE statement.

There's also another test that needs to be updated in the same way, in pkg/sql/opt/exec/execbuilder/testdata/fk.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/fk, line 1438 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjHGRmFDY6Cqs6fUUmg:-LjI1Lus-8YSF7YuBbCU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb16f9f44e03099a80bf449125d25e1512694c8a/pkg/sql/logictest/testdata/logic_test/fk#L1438)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Ideally we'd also want to bring back all the logic tests that test the behavior of VALIDATE CONSTRAINT (I originally took them all out in #37433, which started validating all added FKs), now that we can create unvalidated FK constraints. It doesn't have to be in this PR, so you can either put them back in now (you can just copy them from that PR diff and add NOT VALID everywhere) or add a TODO to do it later.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/fk, line 2105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjHFNRoEOMnZWKyHIn6:-LjI1Kv0CAH9FVQCx0A3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb16f9f44e03099a80bf449125d25e1512694c8a/pkg/sql/logictest/testdata/logic_test/fk#L2105)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

can you make this a subtest (and drop all the tables at the end)?
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.go, line 2377 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjHBYka3Vrwvof5mV60:-LjIHJDi42oorZPjOpX1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb16f9f44e03099a80bf449125d25e1512694c8a/pkg/sql/sqlbase/structured.go#L2377)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Can you add to the doc comment to indicate
1. the difference in behavior between validating vs. unvalidated constraints (i.e., validating constraints are assumed to have been added earlier and just need to be marked as validated, whereas unvalidated constraints have not been added earlier and need to be added); and
2. the fact that this method can't add backreferences for foreign keys, and that those need to be added separately by the caller as needed?

I'd also add a TODO to somehow refactor this so that the FK reference and backreference are added in the same place (maybe by passing in a closure to this method?), since this situation isn't ideal.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.go, line 2389 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjHCyo42PIDbNwjuAHT:-LjIHK5f49rT16IKoesQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb16f9f44e03099a80bf449125d25e1512694c8a/pkg/sql/sqlbase/structured.go#L2389)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

It'd be good to also add some inline comments to explain why we need all these cases.  
</blockquote></details>

Done.

**Review by thoszhang — COMMENTED** [review]
There are some test failures - when I ran the tests on my laptop, something was hung and hit the test timeout (which is presumably why a lot of the tests in CI failed with "test ended in panic." We need to figure out what the problem is.

Also, could you add a release note, since this is a new user-facing feature/change in behavior? (And copy the new commit message into the PR message.)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-:-LjN3-oXBfD1ArYevKRs:brtyi3c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @Tyler314)

___
*[pkg/sql/create_table.go, line 443 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjMqLt_3UQ1RvFeZguI:-LjMqLt_3UQ1RvFeZguJ:bz0xnsh) ([raw file](https://github.com/cockroachdb/cockroach/blob/033595d8396c6cf85e77cd524f5b216737c0174e/pkg/sql/create_table.go#L443)):*
> ```Go
> //
> // The passed validationBehavior is used to determine whether or not preexisting
> // entries in the backref table need to be validated against the foreign key
> ```

Remove `backref`. Also, this should probably mention that this argument only applies for existing tables, not new tables.
___
*[pkg/sql/schema_changer.go, line 1306 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjHDsXl5ECK3p4yvhDT:-LjMqzWA5T67mfdXD8Jg:b-bkgthf) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb16f9f44e03099a80bf449125d25e1512694c8a/pkg/sql/schema_changer.go#L1306)):*
<details><summary><i>Previously, Tyler314 (Tyler Roberts) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: I'd prefer to put the added comment here, instead of when `PublishMultiple` is called, since we start constructing the arguments to `PublishMultiple` here.

**Review by tyler314 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-:-LjRj3kP6Pbl0cmTm3PD:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/sql/create_table.go, line 443 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjMqLt_3UQ1RvFeZguI:-LjNIHai-hlHBGY4mjJi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/033595d8396c6cf85e77cd524f5b216737c0174e/pkg/sql/create_table.go#L443)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Remove `backref`. Also, this should probably mention that this argument only applies for existing tables, not new tables.
</blockquote></details>

Done.

**Review by tyler314 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38663)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/sql/schema_changer.go, line 1306 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjHDsXl5ECK3p4yvhDT:-LjWX5Si6wt3Mh9R5YAE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb16f9f44e03099a80bf449125d25e1512694c8a/pkg/sql/schema_changer.go#L1306)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

nit: I'd prefer to put the added comment here, instead of when `PublishMultiple` is called, since we start constructing the arguments to `PublishMultiple` here.
</blockquote></details>

Done.

**Review by tyler314 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-:-LjNIolP5i-w9oB2oASa:bg7igk9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lucy-zhang)

**Review by thoszhang — APPROVED** [review]
lgtm except for minor comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-:-LjWnA0r2A_-0TaxppgC:bst1a7q)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lucy-zhang and @Tyler314)

___
*[pkg/sql/schema_changer.go, line 1217 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjWjVc01Y4LGFVDqz31:-LjWjVc19-Gzsf8jjvU4:b-obkv3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/81f1036667c15df4becb090cc01d77f150e9d7de/pkg/sql/schema_changer.go#L1217)):*
> ```Go
> 	// Get the other tables whose foreign key backreferences need to be removed.
> 	// We make a call to PublishMultiple to handle the situation to add Foreign Key backreferences.
> 	// We begin to construct the arguments of the method here, which includes:
> ```

I don't think these 3 lines are really necessary
___
*[pkg/sql/logictest/testdata/logic_test/schema_change_in_txn, line 943 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjWk8VP7H5ccBpp6WCM:-LjWk8VP7H5ccBpp6WCN:b-lufue4) ([raw file](https://github.com/cockroachdb/cockroach/blob/81f1036667c15df4becb090cc01d77f150e9d7de/pkg/sql/logictest/testdata/logic_test/schema_change_in_txn#L943)):*
> ```
> 
> statement ok
> ALTER TABLE check_table ADD CONSTRAINT d_0 CHECK (d > 0) NOT VALID
> ```

I'm fine with adding NOT VALID to these, but can you just add it for one constraint and not the other (so we can test both cases)? I'd also remove the `VALIDATE CONSTRAINT` statements below so we can check using `SHOW CONSTRAINTS` that it's actually unvalidated.
___
*[pkg/sql/opt/exec/execbuilder/testdata/fk, line 6 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjWk_VtBsycMfMeHbV9:-LjWk_VtBsycMfMeHbVA:bvkjd0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/81f1036667c15df4becb090cc01d77f150e9d7de/pkg/sql/opt/exec/execbuilder/testdata/fk#L6)):*
> ```
> # currently don't support adding a validated FK in the same transaction as
> # CREATE TABLE
> statement ok
> ```

As mentioned before, can you update this test in the same way as the other logic test? i.e., remove the BEGIN/COMMIT, add a NOT VALID to the constraint
___
*[pkg/sql/sqlbase/structured.go, line 2377 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjWlJoJ-9Repd_k1eoJ:-LjWlJoJ-9Repd_k1eoK:b-9vb3sr) ([raw file](https://github.com/cockroachdb/cockroach/blob/81f1036667c15df4becb090cc01d77f150e9d7de/pkg/sql/sqlbase/structured.go#L2377)):*
> ```Go
> 
> // MakeMutationComplete updates the descriptor upon completion of a mutation.
> // There are three Validity types for the mutations:
> ```

I find these comments confusing. I think the important thing to explain (both here and inline) is the difference between the behavior for Validating and Unvalidated constraints: Validating constraints have already been added and need to be marked as Validated, whereas Unvalidated constraints needed to be added (for the first time). (And it's not even possible for Validated constraints to enter this function, hence the assertion error.)
___
*[pkg/sql/sqlbase/structured.go, line 2398 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjWm0Q693p3vx6f6esp:-LjWm0Q693p3vx6f6esq:b7iu7yd) ([raw file](https://github.com/cockroachdb/cockroach/blob/81f1036667c15df4becb090cc01d77f150e9d7de/pkg/sql/sqlbase/structured.go#L2398)):*
> ```Go
> 				switch t.Constraint.Check.Validity {
> 				case ConstraintValidity_Unvalidated:
> 					// add the constraint to a slice of constraints to be checked
> ```

This should be something like "add the constraint to the list of check constraints on the table descriptor"
___
*[pkg/sql/sqlbase/structured.go, line 2422 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjWmBHZD_vp0UKIj7gV:-LjWmBH_-C7rovuif0kD:bsc9uyj) ([raw file](https://github.com/cockroachdb/cockroach/blob/81f1036667c15df4becb090cc01d77f150e9d7de/pkg/sql/sqlbase/structured.go#L2422)):*
> ```Go
> 				case ConstraintValidity_Validating:
> 					idx.ForeignKey.Validity = ConstraintValidity_Validated
> 				case ConstraintValidity_Unvalidated:
> ```

it's a little confusing that the ordering for the validity cases don't match between the FK case and the check case - can you reorder them?

**Review by tyler314 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38663)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/sql/schema_changer.go, line 1217 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjWjVc01Y4LGFVDqz31:-LjXF5JDBvLGhQdzAuWA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/81f1036667c15df4becb090cc01d77f150e9d7de/pkg/sql/schema_changer.go#L1217)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I don't think these 3 lines are really necessary
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/schema_change_in_txn, line 943 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjWk8VP7H5ccBpp6WCM:-LjXHCi-DdXXhz3pwpsG:b-6g6ty1) ([raw file](https://github.com/cockroachdb/cockroach/blob/81f1036667c15df4becb090cc01d77f150e9d7de/pkg/sql/logictest/testdata/logic_test/schema_change_in_txn#L943)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I'm fine with adding NOT VALID to these, but can you just add it for one constraint and not the other (so we can test both cases)? I'd also remove the `VALIDATE CONSTRAINT` statements below so we can check using `SHOW CONSTRAINTS` that it's actually unvalidated.
</blockquote></details>

Yes, this makes sense.
___
*[pkg/sql/opt/exec/execbuilder/testdata/fk, line 6 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjWk_VtBsycMfMeHbV9:-LjXHolqCVR41414Q1jB:b-8o52sq) ([raw file](https://github.com/cockroachdb/cockroach/blob/81f1036667c15df4becb090cc01d77f150e9d7de/pkg/sql/opt/exec/execbuilder/testdata/fk#L6)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

As mentioned before, can you update this test in the same way as the other logic test? i.e., remove the BEGIN/COMMIT, add a NOT VALID to the constraint
</blockquote></details>

yes, I think I just misunderstand when we discussed changing this test the other day.
___
*[pkg/sql/sqlbase/structured.go, line 2377 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjWlJoJ-9Repd_k1eoJ:-LjXOiRv2N5A67fGITs5:b389yw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/81f1036667c15df4becb090cc01d77f150e9d7de/pkg/sql/sqlbase/structured.go#L2377)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I find these comments confusing. I think the important thing to explain (both here and inline) is the difference between the behavior for Validating and Unvalidated constraints: Validating constraints have already been added and need to be marked as Validated, whereas Unvalidated constraints needed to be added (for the first time). (And it's not even possible for Validated constraints to enter this function, hence the assertion error.)
</blockquote></details>

Updated the function comments, and added a few inline ones as well.
___
*[pkg/sql/sqlbase/structured.go, line 2398 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjWm0Q693p3vx6f6esp:-LjXQTtC6163gcQdV58P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/81f1036667c15df4becb090cc01d77f150e9d7de/pkg/sql/sqlbase/structured.go#L2398)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

This should be something like "add the constraint to the list of check constraints on the table descriptor"
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.go, line 2422 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38663#-LjWmBHZD_vp0UKIj7gV:-LjXQWKECVilfbJF_t3i:bb77uf3) ([raw file](https://github.com/cockroachdb/cockroach/blob/81f1036667c15df4becb090cc01d77f150e9d7de/pkg/sql/sqlbase/structured.go#L2422)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

it's a little confusing that the ordering for the validity cases don't match between the FK case and the check case - can you reorder them?
</blockquote></details>

Yes!

**Pull request merged**
