### PR TITLE
sql: move primary region and survival goal to the type descriptor region config

### PR DESCRIPTION
**Pull request by arulajmani**
See individual commits for details.

### CODE REVIEW

**Review by otan — COMMENTED** [review]
I'm for the first commit, but still on the fence on the second one (will let @ajstorm give the final stamp).

If you use the second commit, you'll need to add a release note that dictates if you used multiregion in the beta you'll have to wipe your database.

> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62727#-:-MWzY4xG3VS07UEuxqr4:bh7ckf3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, and @otan)

**Review by ajstorm — CHANGES_REQUESTED** [review]
I think the change in the first commit makes sense, but one thing that slightly worries me about it is that it goes against the directive in the functional specification (and all the conversations we had about it - see closed issue "What data type should we use for the region column...").  @arulajmani do you remember all of the details about that conversation?  If so, what has changed between now and then to motivate this change in course?  Is it that we realized that this is not as awkward to implement?  Is it the difficulty in constantly validating data in two places?  Something else?  At the very least, we should update the FS to indicate what's changed and why.

I'm with @otan on being a bit uncomfortable with the second commit.  It makes a lot of sense to have the regions only present on the type descriptor.  The primary region follows from the regions being there.  The survival goal however, isn't directly related to the regions (aside from the number of them) and so keeping it on the database descriptor makes more sense to me.  

> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62727#-:-MX2CsGq6gkF4kX_bG0G:b-32748i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/alter_database.go, line 313 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62727#-MX2AfTE4QSSdZhhGXmT:-MX2AfTE4QSSdZhhGXmU:bislawe) ([raw file](https://github.com/cockroachdb/cockroach/blob/e777dd32fd527c750adbad8b687b77402981905b/pkg/sql/alter_database.go#L313)):*
> ```Go
> 	var toDrop []*typedesc.Mutable
> 
> 	// Ensure survivability goal and number of regions after the drop jive.
> ```

Nit: I'm all in favour of cheeky comments, but I worry that a few years from now, people will wonder what the "drop jive" is.  Can we keep the lightheartedness of "drop jive" while adding in parentheses what we mean by it?  I know, I'm taking the fun out it :disappointed: 
___
*[pkg/sql/alter_database.go, line 318 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62727#-MX29zBF1BGo7K2a-tt0:-MX29zBF1BGo7K2a-tt1:bd1jh5t) ([raw file](https://github.com/cockroachdb/cockroach/blob/e777dd32fd527c750adbad8b687b77402981905b/pkg/sql/alter_database.go#L318)):*
> ```Go
> 		return nil, err
> 	}
> 	if err := multiregion.CanDropRegion(regionConfig); err != nil {
> ```

Not sure if I looked at the review which introduced `CanDropRegion`, but when I looked at the function just now, I'd assumed that it would be checking not only the survival goal, but whether or not the region was the primary region (of a database with more than one region).  Does it make sense to either expand `CanDropRegion` so that it covers both cases?  Or, alternatively, change its name to `SurvivalGoalAllowsForDropRegion` (or something like that)?  Expanding the context might also help clean up the code below a bit.
___
*[pkg/sql/create_type.go, line 280 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62727#-MX2EJE9EMtWoF_FnHFo:-MX2EJE9EMtWoF_FnHFp:b-bnzy1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e777dd32fd527c750adbad8b687b77402981905b/pkg/sql/create_type.go#L280)):*
> ```Go
> 	}
> 	return params.p.createEnumWithID(
> 		params, id, n.n.EnumLabels, n.dbDesc, n.typeName, nil,
> ```

Nit: `\* multiregionConfig *\`
___
*[pkg/sql/create_type.go, line 290 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62727#-MX2E_cl09eFkzrv5E_h:-MX2E_cl09eFkzrv5E_i:b-4aowfo) ([raw file](https://github.com/cockroachdb/cockroach/blob/e777dd32fd527c750adbad8b687b77402981905b/pkg/sql/create_type.go#L290)):*
> ```Go
> 	dbDesc catalog.DatabaseDescriptor,
> 	typeName *tree.TypeName,
> 	multiregionConfig *multiregion.RegionConfig,
> ```

Nit: Should this be multiRegionConfig?  Or maybe just regionConfig?
___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62727#-MX2GOiO7-H_nsFqdpTE:-MX2GOiO7-H_nsFqdpTF:b-beqo7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/e777dd32fd527c750adbad8b687b77402981905b/pkg/sql/catalog/dbdesc/database_desc.go#L196)):*
> ```Go
> 	if desc.RegionConfig.RegionEnumID == descpb.InvalidID {
> 		vea.Report(errors.AssertionFailedf(
> 			"invalid region enum ID on a multi-region db %d", desc.GetID()))
> ```

Nit: Does it make sense to call the type descriptor validation here as well?  Seems like this change is removing some of the validation we had in the past.  I'm wondering if this was deliberate.

**Review by arulajmani — COMMENTED** [review]
> do you remember all of the details about that conversation?  If so, what has changed between now and then to motivate this change in course?

I'll cover both the survival goal and primary region under this. The spec says that we considered putting all region config data on the type descriptor, but chose the hybrid approach of denormalizing regions/primary region on the database descriptor as "it feels clunky and it feels like a complicated lookup to know what regions exist for a given database". Even though the spec doesn't say so, this approach also allowed us iterate quickly as the multi-region enum work wasn't complete when we added these fields to the database descriptor. 

Since then, we've learned that duplicating regions was harder than we'd initially envisioned and we went back on that decision. At this point, none of our initial reasons to pick the hybrid approach apply. So let's revisit it. 

Primary Region:
At no point in the code are we reading the primary region off the database descriptor where the type descriptor isn't also available to us. As is, it only adds extra validation burden and a gotcha in the code when switching/setting the primary region. I think we should get rid of it.

Survival Goal:
This one might be a slightly tricker sell, but I hope I can persuade you that this is a positive change. I think it's cleaner to store all multi-region metadata in a single place, as opposed to constructing it from two descriptors. If we view the type descriptor as a "multi-region enum" (which it is) and remember that we only have one such special enum per database, viewing it as the sole source of truth for multi-region metadata is an easier pill to swallow. 

Other than that, I think theres some value in being able to validate the number of regions <-> survival goal constraint without having to fetch for cross-references. Also, probably not for this release, but making this change now will allow us to clean up some code around regenerating RegionConfigs every time a field is mutated. 

It basically comes down to would we pick the hybrid approach today knowing what we've learned about the pitfalls there. I don't think so -- option 2, from the functional spec, is a much easier mental model and cleaner in code.  Should we not change course to option 2, while we can? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62727#-:-MX2QzGY2gr95ohVQlei:b33asdi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, @arulajmani, and @otan)

**Review by ajstorm — COMMENTED** [review]
What you mentioned above makes sense.  As part of this PR, can you make some changes to the Functional Specification to reflect the updated thinking.

All that being said, I'm still not sold on the Survival Goal change.  I do see the type descriptor as the "multi-region enum" but I still find it a bit strange that it stores the survival goal which is only peripherally related to the regions in the enum.  I'm of the opinion that we should be logically grouping things together based on their scope.  Since the survivability goal isn't tightly coupled to the number of regions, we shouldn't introduce that coupling.  Also, since in most instances in the code, the enum is found from the database descriptor, I don't see the impact in having to cross reference the two when validating the survival goal (which should hopefully only be required on add/drop region, and not on all of the other operations).

Happy to continue this debate in Slack, or in a call, if my argument above hasn't convinced you :smile: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62727#-:-MX3btelEimkjZecx-5s:b-kgm4ln)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, @arulajmani, and @otan)

**Review by arulajmani — COMMENTED** [review]
Offline, we discussed this and were slightly leaning towards keeping both the commits. But, considering this would break betas that have been shipped, we decided that we will discard the second commit and keep the survival goal on the database descriptor. I've addressed all comments on here, but I'm gonna open a new PR with just the first commit on it. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62727#-:-MXDLgXJ5J3PsN37037I:bqvd4bs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, and @otan)

___
*[pkg/sql/alter_database.go, line 318 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62727#-MX29zBF1BGo7K2a-tt0:-MXDKkNC2vBxRGJzCuIN:b-7nej6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/e777dd32fd527c750adbad8b687b77402981905b/pkg/sql/alter_database.go#L318)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Not sure if I looked at the review which introduced `CanDropRegion`, but when I looked at the function just now, I'd assumed that it would be checking not only the survival goal, but whether or not the region was the primary region (of a database with more than one region).  Does it make sense to either expand `CanDropRegion` so that it covers both cases?  Or, alternatively, change its name to `SurvivalGoalAllowsForDropRegion` (or something like that)?  Expanding the context might also help clean up the code below a bit.
</blockquote></details>

Im gonna opt for `SurvivalGoalAllowsForDropRegion` just because pushing the primary region logic down to the region config is kinda tricky. Concretely, teaching the region config "primary region can only be dropped if there are no regions on the type descriptor including transitioning regions" is not worth the complexity imo. 
___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62727#-MX2GOiO7-H_nsFqdpTE:-MXDJN_E3Cj7iFZ1y84-:b-pptxgo) ([raw file](https://github.com/cockroachdb/cockroach/blob/e777dd32fd527c750adbad8b687b77402981905b/pkg/sql/catalog/dbdesc/database_desc.go#L196)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Does it make sense to call the type descriptor validation here as well?  Seems like this change is removing some of the validation we had in the past.  I'm wondering if this was deliberate.
</blockquote></details>

This function is called from `ValidateSelf`. The type descriptor validation happens in the `ValidateCrossReferences` function.

**Pull request closed without merging**
