### PR TITLE
sql: bark at unused CTEs containing mutations

### LINKED ISSUE #24307: sql: unused CTEs containing mutations must be executed no matter what
The semantics of CTEs is that all mutations in CTEs take place whether or not all the result rows are used.

The recently introduced spool operator ensures this is true when e.g. LIMIT is applied.

However, the following query will still drop the mutations on the floor silently and incorrectly:

```sql
WITH a AS (INSERT INTO kv VALUES (1), (2), (3) RETURNING v)
  SELECT 1
```

i.e. when the CTE is not used *at all*.

cc @jordanlewis

### PR DESCRIPTION
**Pull request by knz**
Informs #24307.

The SQL standard (and pg) specifies that CTEs containing mutations are
executed no matter how / how many times they are used in the remainder
of the query.

Meanwhile the heuristic planner + execution machinery is currently
unable to force the execution of CTEs containing mutations if they are
not otherwise used in the rest of the query.

However meanwhile they are also accepted silently -- i.e. CockroachDB
silently fails to do what the semantics require.

This patch changes the behavior to instead report an error "feature
not supported".

Release note (bug fix): CockroachDB now reports an unimplemented error
when a common table expression containing INSERT/UPDATE/UPSERT/DELETE
is not otherwise used in the remainder of the query.

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
LGTM though I wonder if the implementation could be done a little DRYer

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31003#-:-LO5BhR95Iviw8iV31Xg:bn7figp)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/delete.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31003#-LO59fI-0qcccKSdyKMs:-LO59fI-0qcccKSdyKMt:b-nhyvcw) ([raw file](https://github.com/cockroachdb/cockroach/blob/76f4748158f5f1f518344b2093c497fbbb676190/pkg/sql/delete.go#L71)):*
> ```Go
> 			cteErr := resetter(p)
> 			if cteErr != nil && err == nil {
> 				err = cteErr
> ```

This is  confusing - I think it works because you've used named arguments? But I'd  consider putting a comment here ( maybe `// Set the return values of Delete if we encounter an error during the ending defer`, or something? I dunno.) , unless it's a Go idiom that I just haven't seen.
___
*[pkg/sql/render.go, line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31003#-LO5AB3b6pTnxWuti8uG:-LO5AB3b6pTnxWuti8uH:b4qnq2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/76f4748158f5f1f518344b2093c497fbbb676190/pkg/sql/render.go#L201)):*
> ```Go
> 				err = cteErr
> 				result = nil
> 			}
> ```

Sad that this has to be repeated in every clause. Can we find a way to factor it into the resetter somehow, or is that impossible?

**Review by knz — COMMENTED** [review]
Thanks for your review.

> I wonder if the implementation could be done a little DRYer
 
this is go, what do you expect...

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31003#-:-LOCTt_P4PGy0uezmw6A:b-m9zuxy)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/delete.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31003#-LO59fI-0qcccKSdyKMs:-LOCSbuoEhh_0jjgGpND:b-iagyon) ([raw file](https://github.com/cockroachdb/cockroach/blob/76f4748158f5f1f518344b2093c497fbbb676190/pkg/sql/delete.go#L71)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This is  confusing - I think it works because you've used named arguments? But I'd  consider putting a comment here ( maybe `// Set the return values of Delete if we encounter an error during the ending defer`, or something? I dunno.) , unless it's a Go idiom that I just haven't seen.
</blockquote></details>

Yes indeed it works because I have used named arguments. I agree it is slightly confusing, so I renamed `err` to `resultErr` for better clarity. Added the comment too.
___
*[pkg/sql/render.go, line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31003#-LO5AB3b6pTnxWuti8uG:-LOCT55P0OYA0fpu4sQq:b-f56r45) ([raw file](https://github.com/cockroachdb/cockroach/blob/76f4748158f5f1f518344b2093c497fbbb676190/pkg/sql/render.go#L201)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Sad that this has to be repeated in every clause. Can we find a way to factor it into the resetter somehow, or is that impossible?
</blockquote></details>

I found it impossible because it needs to capture the named results `result` and `resultErr` by reference. Obviously we can't have them move to the heap so the full defer closure must be listed every time.

**Pull request merged**
