### PR TITLE
opt, sql: disallow multi-column-family checks in updates under read committed

### LINKED ISSUE #114605: sql: disallow multi-column-family checks during updates under read committed isolation
Until https://github.com/cockroachdb/cockroach/issues/112488 is fixed we need to disallow multi-column-family checks under read committed isolation.

Jira issue: CRDB-33592

### PR DESCRIPTION
**Pull request by rytaft**
**opt, sql: add support for getting columns from cat.CheckConstraint**

This commit adds support for getting the columns referenced by a
`cat.CheckConstraint`. In order to make this possible, the struct has
been converted to an interface, and implementations have been added to
the `optCatalog` as well as the test catalog.

This feature will be needed in a following commit.

Release note: None

**opt: disallow multi-column-family checks in updates under read committed**

This commit adds logic to disallow `UPDATE`, `UPSERT`, and `INSERT ON CONFLICT`
queries in some cases when the mutated table has a check constraint with
columns from multiple column families. This is needed until we add logic
to take shared locks on unmodified column families in the constraint.

Specifically, these queries are disallowed when:
 - The check constraint involves a column family that is updated
   (otherwise we don't need to do anything to maintain this constraint)
 - And the check constraint involves a column family that is *not*
   updated, but *is* read. In this case we don't have an intent, so
   we need a lock. But we're not currently taking that lock.

Fixes https://github.com/cockroachdb/cockroach/issues/114605
Informs https://github.com/cockroachdb/cockroach/issues/112488

Release note (bug fix): `UPDATE`, `UPSERT`, and `INSERT ON CONFLICT` queries
are now disallowed under read committed isolation when the table contains
a check constraint involving a column family that is updated, and the
check constraint also involves a column family that is *not* updated,
but *is* read. This is a temporary fix to prevent possible violation of
the check constraint, and the restriction will be lifted in the future.

Co-authored-by: Michael Erickson <michae2@cockroachlabs.com>

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
:lgtm: Thank you for taking this on! Nice tests!

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116335#-:-NlZjrvQ-jo8o9skASYP:b-33dh4u)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Review by mgartner — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116335)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @rytaft)

___
*[`pkg/sql/opt_catalog.go` line 1080 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116335#-NlZugy-1yH__zu1My44:-NlZugy-1yH__zu1My45:bigp9a6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9560ae58e9d5b9c56fbbc46c2922958aa8e026c6/pkg/sql/opt_catalog.go#L1080)):*
> ```Go
> 			columnCount: len(activeChecks[i].CheckDesc().ColumnIDs),
> 			lookupColumnOrdinal: func(j int) (int, error) {
> 				return ot.lookupColumnOrdinal(activeChecks[i].CheckDesc().ColumnIDs[j])
> ```

I think this is a bug, similar the the one I fixed in https://github.com/cockroachdb/cockroach/pull/115654. Closing over the `i` means that `i` will always be `len(activeChecks)-1` after this loop finishes. A test with multiple check constraints should catch it, I think.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116335)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @rytaft)

___
*[`-- commits` line 24 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/116335#-NlZw55C9PVaBASaPF0g):*
nit: "And" to start this would make it more clear that both conditions are necessary. Or change the top sentence to "Specifically, these queries are disallow when both of the follow are true:".
___
*[`pkg/sql/opt_catalog.go` line 1080 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116335#-NlZugy-1yH__zu1My44:-NlZwQWK6hmubDBG3mcH:buq0ibl) ([raw file](https://github.com/cockroachdb/cockroach/blob/9560ae58e9d5b9c56fbbc46c2922958aa8e026c6/pkg/sql/opt_catalog.go#L1080)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think this is a bug, similar the the one I fixed in https://github.com/cockroachdb/cockroach/pull/115654. Closing over the `i` means that `i` will always be `len(activeChecks)-1` after this loop finishes. A test with multiple check constraints should catch it, I think.
</blockquote></details>

Unit tests might be able to easily catch this, though I don't know how easy it is to write a unit test for opt_catalog since you need to pull in a full server, AFAIK.
___
*[`pkg/sql/opt/optbuilder/mutation_builder.go` line 837 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/116335#-NlZwlGaDeJOcGkzgQUb:-NlZwlGaDeJOcGkzgQUc:bhk4z1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/00f462b0086fa465a297b5b2e48011a2f02275fb/pkg/sql/opt/optbuilder/mutation_builder.go#L837)):*
> ```Go
> 				// - The check constraint involves a column family that is updated
> 				//   (otherwise we don't need to do anything to maintain this constraint)
> 				// - The check constraint involves a column family that is *not*
> ```

nit: ditto: "And the check constraints involves..."
___
*[`pkg/sql/opt/optbuilder/mutation_builder.go` line 874 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/116335#-NlZxETv5oh5f7VAYces:-NlZxETv5oh5f7VAYcet:b-sljlxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/00f462b0086fa465a297b5b2e48011a2f02275fb/pkg/sql/opt/optbuilder/mutation_builder.go#L874)):*
> ```Go
> 
> // getColumnFamilySet gets the set of column families represented in colOrdinals.
> func getColumnFamilySet(colOrdinals *intsets.Fast, tab cat.Table) intsets.Fast {
> ```

nit: functions typically take `intsets.Fast` instead of `*intsets.Fast`, and I don't see any reason we need `*intsets.Fast` here. Using `*intsets.Fast` risks an unnecessary heap allocation if Go's escape analysis can't determine that the set can be allocated on the stack in this case.

**Review by rytaft — COMMENTED** [review]
TFTRs! Updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116335#-:-Nl_7ay62q5KO12_7Ryx:b-u8hs9c)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @michae2)

___
*[`-- commits` line 24 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/116335#-NlZw55C9PVaBASaPF0g):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: "And" to start this would make it more clear that both conditions are necessary. Or change the top sentence to "Specifically, these queries are disallow when both of the follow are true:".
</blockquote></details>

Done.
___
*[`pkg/sql/opt_catalog.go` line 1080 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116335#-NlZugy-1yH__zu1My44:-Nl_BYrYC7XjfF9yecZi:biptp8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/9560ae58e9d5b9c56fbbc46c2922958aa8e026c6/pkg/sql/opt_catalog.go#L1080)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Unit tests might be able to easily catch this, though I don't know how easy it is to write a unit test for opt_catalog since you need to pull in a full server, AFAIK.
</blockquote></details>

Great catch! I updated some of the tests to include multiple constraints, and I confirmed that they caught this bug.

Agreed that a unit test would be nice, but it doesn't seem like any of the opt_catalog stuff is unit-tested, and it would be quite a bit of work to add at this point. Hopefully the test coverage I added here is enough for now.
___
*[`pkg/sql/opt/optbuilder/mutation_builder.go` line 837 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/116335#-NlZwlGaDeJOcGkzgQUb:-Nl_7TPZ2G8oigqHdx_r:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00f462b0086fa465a297b5b2e48011a2f02275fb/pkg/sql/opt/optbuilder/mutation_builder.go#L837)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: ditto: "And the check constraints involves..."
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/mutation_builder.go` line 874 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/116335#-NlZxETv5oh5f7VAYces:-Nl_7YqF2Xo78l1D_gc8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00f462b0086fa465a297b5b2e48011a2f02275fb/pkg/sql/opt/optbuilder/mutation_builder.go#L874)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: functions typically take `intsets.Fast` instead of `*intsets.Fast`, and I don't see any reason we need `*intsets.Fast` here. Using `*intsets.Fast` risks an unnecessary heap allocation if Go's escape analysis can't determine that the set can be allocated on the stack in this case.
</blockquote></details>

Done.

**Review by mgartner — APPROVED** [review]
:lgtm: Nicely done!

> Reviewed 7 of 7 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116335#-:-Nl_Z5MU4IVhROtZC_gA:b-msncp4)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2)

___
*[`pkg/sql/opt_catalog.go` line 1080 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116335#-NlZugy-1yH__zu1My44:-Nl_YYt29f-1XWocNopl:b-w8xxhk) ([raw file](https://github.com/cockroachdb/cockroach/blob/9560ae58e9d5b9c56fbbc46c2922958aa8e026c6/pkg/sql/opt_catalog.go#L1080)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Great catch! I updated some of the tests to include multiple constraints, and I confirmed that they caught this bug.

Agreed that a unit test would be nice, but it doesn't seem like any of the opt_catalog stuff is unit-tested, and it would be quite a bit of work to add at this point. Hopefully the test coverage I added here is enough for now.
</blockquote></details>

The tests look great! I agree adding unit tests it outside the scope here.

**Review by rytaft — COMMENTED** [review]
Thanks!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116335#-:-NlaUMEAC1IV_JBKewyT:b-voiyyw)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2)

**Pull request merged**
