### PR TITLE
server: fix a bug in a test

### PR DESCRIPTION
**Pull request by andreimatei**
An int was being inserted in a table instead of the string
representation of an enum, which is what the respective col is supposed
to contain. The bug was benign; it only manifests itself if the admin
endpoints try to read the rangelog. But it was bad and it should feel
bad.

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
stamp a bro

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32863#-:-LTNr9zM7WbCmTHc80H_:b69mqla)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by tbg** [comment]
Sorry, totally missed this!

bors r+

**Comment by tbg** [comment]
Looks like you gotta sign the CLA again or force-push the branch. I did do the recheck PRs dance but no dice.

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32863#-:-LTTq42X8z9v3DXo8FtH:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
