### PR TITLE
sql: add p99 computed column and index to system.statement_statistics, system.transaction_statistics

### PR DESCRIPTION
**Pull request by ericharmeling**
Part of https://github.com/cockroachdb/cockroach/issues/98624.
Follows https://github.com/cockroachdb/cockroach/pull/99042.

This commit adds a new computed column (p99_latency) and partial
index (p99_latency_idx) to the system.statement_statistics and
system.transaction_statistics tables.

Epic: none

Release note: None

### CODE REVIEW

**Comment by ericharmeling** [comment]
Here's some benchmark results: [BenchmarkSqlStatsPersistedresults.txt](https://github.com/cockroachdb/cockroach/files/11033735/BenchmarkSqlStatsPersistedresults.txt)

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 18 of 18 files at r1, 9 of 9 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99148#-:-NR59WuVC-TsnLuza5SO:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling)

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99148#-:-NR5RrWlDzepfKqxVOQe:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag)

**Pull request merged**
