### PR TITLE
opt: very basic support for inverted indexes

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: support contains and containedBy operators

These are the JSONB `@>` and `<@` operators.

Release note: None

#### opt: very basic support for inverted indexes

Adding basic support for inverted indexes. We currently support only a
single "contains" (`@>`) condition. Note that supporting conjunctions
or disjunctions is very tricky with inverted indexes (because a PK can
be represented in multiple index entries).

### CODE REVIEW

**Comment by petermattis** [comment]
Reviewed 2 of 2 files at r1, 4 of 4 files at r2.
Review status: 4 of 10 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/index_constraints_spans.go, line 170 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21330#-L2Ndyi7Jwo3uHy9XO1R:-L2Ndyi7Jwo3uHy9XO1S:b-emk0jt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c01665b969e24b5096e81d254f82cc81292a5b49/pkg/sql/opt/index_constraints_spans.go#L170)):*
> ```Go
> 	// isInverted indicates if the index is an inverted index (e.g. JSONB).
> 	// An inverted index behaves differently than a normal index because a PK
> 	// can appear in multiple index entries.
> ```

Can you elaborate on this? The PK is appended to index-keys for non-unique indexes which sounds like it could be the same thing, but I don't think it is. 

---

*[pkg/sql/opt/testdata/index-constraints, line 1119 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21330#-L2NedxKty8IPYOH6Jfc:-L2NedxKty8IPYOH6Jfd:b4hoviz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c01665b969e24b5096e81d254f82cc81292a5b49/pkg/sql/opt/testdata/index-constraints#L1119)):*
> ```
> [/1/2 - /1/2]
> 
> build-scalar,index-constraints vars=(jsonb) inverted-index=@1
> ```

Probably worthwhile to add a negative test for an interesting case that isn't supported.

---

*[pkg/sql/opt/testdata/index-constraints, line 1130 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21330#-L2NeJWxuOCFxTP4IZJA:-L2NeJWxuOCFxTP4IZJB:bv5zai8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c01665b969e24b5096e81d254f82cc81292a5b49/pkg/sql/opt/testdata/index-constraints#L1130)):*
> ```
> ----
> [ - ]
> Remaining filter: (@1 @> '{"a":1}') AND (@1 @> '{"b":1}')
> ```

You appear to be missing a newline.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21330)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/index_constraints_spans.go, line 170 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21330#-L2Ndyi7Jwo3uHy9XO1R:-L2NmDxKHRJCPks2LPqJ:b-buzlbp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c01665b969e24b5096e81d254f82cc81292a5b49/pkg/sql/opt/index_constraints_spans.go#L170)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can you elaborate on this? The PK is appended to index-keys for non-unique indexes which sounds like it could be the same thing, but I don't think it is. 
</blockquote></details>

In a regular secondary index, each PK shows up once. `a = 1 AND a = 2` is a contradiction. In an inverted index, each PK shows up in potentially many index entries. `a @> 'foo' AND a @> 'bar'` is not a contradiction. So an AND is no longer an intersection of spans.

A query like this could be run in two ways I can think of: generate the spans for just one of the conditions and evaluate the other condition on each result (this is doable in the index constraints code); or do two separate scans and semi-join the results (the inverted indexes RFC mentions the latter).

Similarly if you have`a @> 'foo' OR b @> 'bar'` you can't simply merge the spans and scan, because you will get duplicate results (each row that satisfies both shows up twice). We would need a distinct operator on top to deduplicate.

Implementing these more complex plans require higher-level support in the planner/optimizer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21330)*

**Comment by jordanlewis** [comment]
+1 on your first suggestion for a first cut. It's easy to do at least in the old index selection architecture. I suggested the same approach on Masha's implementation.

**Comment by RaduBerinde** [comment]
Review status: 4 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/testdata/index-constraints, line 1119 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21330#-L2NedxKty8IPYOH6Jfc:-L2QNX4sErPGQMS4CwnJ:b5xytyn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c01665b969e24b5096e81d254f82cc81292a5b49/pkg/sql/opt/testdata/index-constraints#L1119)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Probably worthwhile to add a negative test for an interesting case that isn't supported.
</blockquote></details>

The one below is a case that is not supported (not supported = we don't generate spans).

---

*[pkg/sql/opt/testdata/index-constraints, line 1130 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21330#-L2NeJWxuOCFxTP4IZJA:-L2QNvbW3IfClT1bnL6h:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/c01665b969e24b5096e81d254f82cc81292a5b49/pkg/sql/opt/testdata/index-constraints#L1130)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You appear to be missing a newline.
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21330)*

**Pull request merged**
