### PR TITLE
backport-19.2: terminate nodes in minority on consistency failure

### PR DESCRIPTION
**Pull request by tbg**
Backport:
  * 1/1 commits from "storage: compute minority in failed consistency check" (#41893)
  * 1/1 commits from "storage: terminate nodes in minority on stats mismatch" (#41902)

Please see individual PRs for details.

/cc @cockroachdb/release

### CODE REVIEW

**Comment by bdarnell** [comment]
If stats mismatches aren't severe (which has been our stance so far), I don't think we want to backport changes to crash on them. We can backport the fix for the known issue #42148 (although it'll go into 19.2.1 now), but I'd let stats mismatches continue without aborting in case we've missed some causes.

**Comment by tbg** [comment]
@bdarnell the PR is mislabeled. You need to `s/stats mismatch/consistency failure/`. Sorry, I hadn't noticed this until you pointed it out.

**Comment by bdarnell** [comment]
OK. If it's for data mismatches instead of stats mismatches then I don't object as much, but this is still a significant change to a little-exercised code path and I don't think it's a great candidate for backporting. I'd personally leave this for 20.1

**Comment by tbg** [comment]
Yeah, this isn't a slam dunk for backporting. There is a certain risk in this backport but also the current code tends to spread inconsistencies around the cluster, something that really bit us in the past. I'll bring this up in the weekly tomorrow.

**Comment by tbg** [comment]
@bdarnell when are you OK with merging this backport? Note that I'm planning to merge https://github.com/cockroachdb/cockroach/pull/42264 only a) after the 19.2 release or b) after this backport has landed, whichever happens earlier. This is because otherwise we'll get spurious test failures because we can't skip the roachtest on only one of the branches right now.

**Comment by bdarnell** [comment]
Let's wait a few days after 19.2 is out to see if there is going to be a quick 19.2.1.

**Comment by tbg** [comment]
Cherry-picked  #42401 into this branch. Looks like we're holding off on the merge for a bit longer, too.

**Review by bdarnell — COMMENTED** [review]
We can go ahead and merge now that the commit has been picked for 19.2.1.

**Pull request merged**
