### PR TITLE
opt: implement ON UPDATE cascades for Update

### PR DESCRIPTION
**Pull request by RaduBerinde**
Implement ON UPDATE cascade handling for Update. Note that Upsert also needs
handling of these cascades; that will be worked on separately.

Release note: None

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
Nice work!

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49416#-:-M8G6Ws81ggdBd0bgHsi:bdtx8r6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/fk_cascade.go, line 374 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49416#-M7yaD5Y3mMWZVs7iFTS:-M7yaD5Z3wfbnjAnIFhT:b-8iwwqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c4a16abbfd2e13f3edfa3b1b2cf062f72f86cb7/pkg/sql/opt/optbuilder/fk_cascade.go#L374)):*
> ```Go
> //
> // Note that NULL "old" values in the mutation input don't require any special
> // handling - they will be effectively ignored by the semi-join.
> ```

there's no semi join in the plan above....
___
*[pkg/sql/opt/optbuilder/fk_cascade.go, line 386 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49416#-M7yafe37y21o1pRH8kZ:-M7yafe37y21o1pRH8k_:b-gerdvv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c4a16abbfd2e13f3edfa3b1b2cf062f72f86cb7/pkg/sql/opt/optbuilder/fk_cascade.go#L386)):*
> ```Go
> 
> 	// action is either SetNull or SetDefault.
> 	action tree.ReferenceAction
> ```

what about cascade?
___
*[pkg/sql/opt/optbuilder/fk_cascade.go, line 430 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49416#-M7ybEgR02zAXATwyqQm:-M7yb0jZ6fhniSR7vN2d:b-nrta25) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c4a16abbfd2e13f3edfa3b1b2cf062f72f86cb7/pkg/sql/opt/optbuilder/fk_cascade.go#L430)):*
> ```Go
> 
> 	dep := opt.DepByID(fk.OriginTableID())
> 	b.checkPrivilege(dep, cb.childTable, privilege.DELETE)
> ```

why do we need delete privilege?
___
*[pkg/sql/opt/optbuilder/fk_cascade.go, line 448 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49416#-M7yc6ir1XXC9gtlxV2t:-M7yc6ir1XXC9gtlxV2u:b-ha2zud) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c4a16abbfd2e13f3edfa3b1b2cf062f72f86cb7/pkg/sql/opt/optbuilder/fk_cascade.go#L448)):*
> ```Go
> 
> 	// Set list of columns that will be fetched by the input expression.
> 	// Note that the columns were populated by the scan, but the semi-join returns
> ```

semi -> inner?
___
*[pkg/sql/opt/optbuilder/fk_cascade.go, line 564 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49416#-M8FzhJjCL4gRQJBhKim:-M8FzhJjCL4gRQJBhKin:b-bb0zml) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c4a16abbfd2e13f3edfa3b1b2cf062f72f86cb7/pkg/sql/opt/optbuilder/fk_cascade.go#L564)):*
> ```Go
> 	})
> 
> 	// Filter out rows where the new values are the same with the old values. This
> ```

[nit] same with -> same as
___
*[pkg/sql/opt/optbuilder/fk_cascade.go, line 573 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49416#-M8G-UB423K_x-w18aeh:-M8G-UB423K_x-w18aei:b-ccqn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c4a16abbfd2e13f3edfa3b1b2cf062f72f86cb7/pkg/sql/opt/optbuilder/fk_cascade.go#L573)):*
> ```Go
> 	//
> 	// TODO(radu): IsNot (i.e. IS DISTINCT FROM) is not quite right for composite
> 	// types. See the following example in postgres:
> ```

This example is kind of crazy... is this really something we want to replicate?? And it's considered correct behavior in Postgres?

How would the code you've written below handle this example?
___
*[pkg/sql/opt/optbuilder/fk_cascade.go, line 587 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49416#-M8G-wNF61AhyoN4NryU:-M8G-wNF61AhyoN4NryV:b-4bsnil) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c4a16abbfd2e13f3edfa3b1b2cf062f72f86cb7/pkg/sql/opt/optbuilder/fk_cascade.go#L587)):*
> ```Go
> 	//   (1 row)
> 	//
> 	//   UPDATE parent SET p = 1.00;
> ```

What if this was `UPDATE parent SET p = 1.0`? Would the action take place? That seems so wrong...
___
*[pkg/sql/opt/optbuilder/fk_cascade.go, line 596 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49416#-M8G27rYE9fwnnuvJFDg:-M8G27rYE9fwnnuvJFDh:bjswi5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c4a16abbfd2e13f3edfa3b1b2cf062f72f86cb7/pkg/sql/opt/optbuilder/fk_cascade.go#L596)):*
> ```Go
> 	var condition opt.ScalarExpr
> 	for i := 0; i < numFKCols; i++ {
> 		isNot := f.ConstructIsNot(
> ```

It would help to add a comment to explain/remind why you're using IsNot instead of Not + Eq. Are NULL values the only difference here?
___
*[pkg/sql/opt/optbuilder/testdata/fk-on-update-cascade, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49416#-M8G67il9G-_QVy9j-1i:-M8G67il9G-_QVy9j-1j:b7492v5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c4a16abbfd2e13f3edfa3b1b2cf062f72f86cb7/pkg/sql/opt/optbuilder/testdata/fk-on-update-cascade#L53)):*
> ```
>            │    └── filters
>            │         └── child.p:7 = p:8
>            └── f-k-checks
> ```

Do we still need the checks after a cascade? Isn't this check redundant?
___
*[pkg/sql/opt/optbuilder/testdata/fk-on-update-set-default, line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49416#-M8G5dcW6BMAVZeU5AnO:-M8G5dcW6BMAVZeU5AnP:bhzjljk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c4a16abbfd2e13f3edfa3b1b2cf062f72f86cb7/pkg/sql/opt/optbuilder/testdata/fk-on-update-set-default#L236)):*
> ```
>   g INT PRIMARY KEY,
>   c INT, q INT,
>   CONSTRAINT fk2 FOREIGN KEY (c, q) REFERENCES child_multi(c, q) ON UPDATE CASCADE
> ```

Did you want to test `SET DEFAULT` instead of `CASCADE`? It's not a bad idea to test the combination of both, but not sure if that's what you were intending....

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49416#-:-M8Mgx7z8KoNsXCfZRQp:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @rytaft)

___
*[pkg/sql/opt/optbuilder/fk_cascade.go, line 374 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49416#-M7yaD5Y3mMWZVs7iFTS:-M8Mbvi29nC7xpFx9F_6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c4a16abbfd2e13f3edfa3b1b2cf062f72f86cb7/pkg/sql/opt/optbuilder/fk_cascade.go#L374)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

there's no semi join in the plan above....
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/fk_cascade.go, line 386 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49416#-M7yafe37y21o1pRH8kZ:-M8MbxiK4IRz1o9EKUkR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c4a16abbfd2e13f3edfa3b1b2cf062f72f86cb7/pkg/sql/opt/optbuilder/fk_cascade.go#L386)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

what about cascade?
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/fk_cascade.go, line 430 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49416#-M7ybEgR02zAXATwyqQm:-M8Mc7g8DC_HXSgozCVV:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c4a16abbfd2e13f3edfa3b1b2cf062f72f86cb7/pkg/sql/opt/optbuilder/fk_cascade.go#L430)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

why do we need delete privilege?
</blockquote></details>

Fixed.
___
*[pkg/sql/opt/optbuilder/fk_cascade.go, line 448 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49416#-M7yc6ir1XXC9gtlxV2t:-M8McidI3qP3Dx5xYaYG:b9p949z) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c4a16abbfd2e13f3edfa3b1b2cf062f72f86cb7/pkg/sql/opt/optbuilder/fk_cascade.go#L448)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

semi -> inner?
</blockquote></details>

I removed this comment, it no longer makes sense after we moved out the logic of building the input.
___
*[pkg/sql/opt/optbuilder/fk_cascade.go, line 564 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49416#-M8FzhJjCL4gRQJBhKim:-M8McqXy6XAsIrIFSxGF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c4a16abbfd2e13f3edfa3b1b2cf062f72f86cb7/pkg/sql/opt/optbuilder/fk_cascade.go#L564)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] same with -> same as
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/fk_cascade.go, line 573 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49416#-M8G-UB423K_x-w18aeh:-M8McxXC5Ue4KJbt3ubA:b7z9bw7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c4a16abbfd2e13f3edfa3b1b2cf062f72f86cb7/pkg/sql/opt/optbuilder/fk_cascade.go#L573)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This example is kind of crazy... is this really something we want to replicate?? And it's considered correct behavior in Postgres?

How would the code you've written below handle this example?
</blockquote></details>

I don't think we need to replicate it, but I wanted to leave a note about it (there may be cases where it makes more sense, perhaps with collated strings). I removed the TODO marker but left the example.

To replicate this we would need another operator that is like `IsNot` but is more strict than just checking equality. Added this info in the comment.
___
*[pkg/sql/opt/optbuilder/fk_cascade.go, line 587 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49416#-M8G-wNF61AhyoN4NryU:-M8MeSgfBSp1B2FpiDVB:b-x0paxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c4a16abbfd2e13f3edfa3b1b2cf062f72f86cb7/pkg/sql/opt/optbuilder/fk_cascade.go#L587)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

What if this was `UPDATE parent SET p = 1.0`? Would the action take place? That seems so wrong...
</blockquote></details>

Yes :)
___
*[pkg/sql/opt/optbuilder/fk_cascade.go, line 596 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49416#-M8G27rYE9fwnnuvJFDg:-M8MfC7_Eu6JCKgr07rM:b60r506) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c4a16abbfd2e13f3edfa3b1b2cf062f72f86cb7/pkg/sql/opt/optbuilder/fk_cascade.go#L596)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

It would help to add a comment to explain/remind why you're using IsNot instead of Not + Eq. Are NULL values the only difference here?
</blockquote></details>

Yes, done.
___
*[pkg/sql/opt/optbuilder/testdata/fk-on-update-cascade, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49416#-M8G67il9G-_QVy9j-1i:-M8MfIQV8Gd50Kd6SDhZ:basn8e6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c4a16abbfd2e13f3edfa3b1b2cf062f72f86cb7/pkg/sql/opt/optbuilder/testdata/fk-on-update-cascade#L53)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Do we still need the checks after a cascade? Isn't this check redundant?
</blockquote></details>

Yeah, I have a TODO about it somewhere. I am not convinced it is redundant in all cases (if there are cyclical cascades, in principle maybe there could be other cascades which execute before this one which mess with the parent table). I won't spend time on this until I see a case or workload where the performance of ON UPDATE cascades is important.
___
*[pkg/sql/opt/optbuilder/testdata/fk-on-update-set-default, line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49416#-M8G5dcW6BMAVZeU5AnO:-M8MgZPQD7JLxE2BpZMS:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c4a16abbfd2e13f3edfa3b1b2cf062f72f86cb7/pkg/sql/opt/optbuilder/testdata/fk-on-update-set-default#L236)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Did you want to test `SET DEFAULT` instead of `CASCADE`? It's not a bad idea to test the combination of both, but not sure if that's what you were intending....
</blockquote></details>

Fixed.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49416#-:-M8Mq9njCeiGWGp0mBEp:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/fk_cascade.go, line 573 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49416#-M8G-UB423K_x-w18aeh:-M8MoeGV2TNqf5JzWv78:brxp9sq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c4a16abbfd2e13f3edfa3b1b2cf062f72f86cb7/pkg/sql/opt/optbuilder/fk_cascade.go#L573)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't think we need to replicate it, but I wanted to leave a note about it (there may be cases where it makes more sense, perhaps with collated strings). I removed the TODO marker but left the example.

To replicate this we would need another operator that is like `IsNot` but is more strict than just checking equality. Added this info in the comment.
</blockquote></details>

Sounds good.
___
*[pkg/sql/opt/optbuilder/fk_cascade.go, line 569 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49416#-M8MpO9rC20_yobWsZyl:-M8MpO9sDhb5Fv8mgbno:b-e66vd1) ([raw file](https://github.com/cockroachdb/cockroach/blob/559f2920cc4d4df07eadb1d88493802bdf5f7da2/pkg/sql/opt/optbuilder/fk_cascade.go#L569)):*
> ```Go
> 	//   UPDATE SELF SET a = 1 WHERE true;
> 	//
> 	// We use IsNot because we want the action to take place when the old value is
> ```

[nit] this comment now feels a bit out of nowhere. Maybe say, "In order to perform the filtering, we use IsNot to compare the old and new values because..."

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49416)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @rytaft)

___
*[pkg/sql/opt/optbuilder/fk_cascade.go, line 569 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49416#-M8MpO9rC20_yobWsZyl:-M8Mr-jfEGFn0Nsp3M8P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/559f2920cc4d4df07eadb1d88493802bdf5f7da2/pkg/sql/opt/optbuilder/fk_cascade.go#L569)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] this comment now feels a bit out of nowhere. Maybe say, "In order to perform the filtering, we use IsNot to compare the old and new values because..."
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49416)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball)

**Pull request merged**
