### PR TITLE
iterutil: add sentinel error to stop iteration

### LINKED ISSUE #48709: kvserver: use unambiguous return value in iter callback
See https://github.com/cockroachdb/cockroach/pull/48681 for context.

We have APIs in various places in which we iterate by calling a closure for each item. The closure gets to decide when it is "done" by returning a boolean.

It has always been hard to remember which is which (is `true` "done" or "more")? In this particular case, it looks like we should just remove the boolean - the iteration stops when an error is returned.

There are a few more iterators with a similar api, for example here:

https://github.com/cockroachdb/cockroach/blob/2e77621302dd5d94706ba0e35a076d481b0f87ae/pkg/kv/kvserver/store.go#L1223

We should take a look at them as well.

### PR DESCRIPTION
**Pull request by vrongmeal**
This commit reverts the changes made earlier in the iterutil package 69752bd and a332e9b (revert commits 0d14352 and 454bb4a respectively).

5b3fe98 fixes an issue where iteration should have been continued but was stopped.

Other changes include introducing the sentinel error in iterutil package and refactoring iterators to use it.

Resolves: #48709

Release note: None

### CODE REVIEW

**Comment by vrongmeal** [comment]
@tbg If this is okay to go, I'll refactor other iterators as well.

**Comment by vrongmeal** [comment]
> @tbg If this is okay to go, I'll refactor other iterators as well.

@tbg tagging again in case this was missed

**Review by tbg — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53152)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @vrongmeal)

___
*[pkg/util/iterutil/iterutil.go, line 17 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/53152#-MFZnjJQCuvDmHcNXN8P:-MFZnjJQCuvDmHcNXN8Q:bu3gppc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c167b092e5757fb2ce1c83e6d55fb7ed0a59978/pkg/util/iterutil/iterutil.go#L17)):*
> ```Go
> // ErrStopIteration is a sentinel error that indicates stopping the iteration.
> //
> // This error should not be propogated further, i.e., if a closure returns
> ```

propagated
___
*[pkg/util/iterutil/iterutil.go, line 29 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/53152#-MFZnvzH5hmO56_7hdbf:-MFZnvzH5hmO56_7hdbg:b9bhtzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c167b092e5757fb2ce1c83e6d55fb7ed0a59978/pkg/util/iterutil/iterutil.go#L29)):*
> ```Go
> // 	for i := range slice {
> // 		if err := f(i); err != nil {
> // 			if errors.Is(err, iterutil.ErrStopIteration) {
> ```

Use `Done()` here since you have it.
___
*[pkg/util/iterutil/iterutil.go, line 37 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/53152#-MFZo0XR1VvlycXG39tD:-MFZo0XR1VvlycXG39tE:b-eqkoyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c167b092e5757fb2ce1c83e6d55fb7ed0a59978/pkg/util/iterutil/iterutil.go#L37)):*
> ```Go
> // 	}
> //
> var ErrStopIteration = errors.New("stop iteration")
> ```

it might be better to do

```go

var errStopIteration = errors.New("stop iteration")

func ErrStopIteration() error { return errStopIteration
```

just to disallow changing `ErrStopIteration`.

**Review by tbg — APPROVED** [review]
:lgtm_strong: thank you! Sorry this took so long again. We are starting to prepare the 20.2 release and are holding off on merging anything nonessential to master for a few weeks.
You can consider this PR merged - I will be in charge of returning to it and getting it in when the time comes.

> Reviewed 5 of 5 files at r6, 2 of 2 files at r7, 2 of 2 files at r8, 1 of 1 files at r9, 14 of 14 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53152#-:-MGNgGZsEL50Fg3AnaP7:b-j4nxsm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @vrongmeal)

___
*[pkg/kv/kvserver/store.go, line 1340 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/53152#-MGNfncL3klnag4dXx5k:-MGNfncM3IvXEOR9XhCH:b-6ntnk3) ([raw file](https://github.com/cockroachdb/cockroach/blob/fea4ccf2ab172e87dc14bffee01a2f7d3cb0cffc/pkg/kv/kvserver/store.go#L1340)):*
> ```Go
> 		}
> 		matchCount++
> 		if err := fn(desc); err != nil {
> ```

doesn't this all simplify to

```go
if err := fn(desc); iterutil.Done(err) { return iterutil.StopIteration() }
return err
```

**Review by vrongmeal — COMMENTED** [review]
Great! I'll make the last small change and update the PR

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53152#-:-MGPYUTwBrTWLF0eoinV:b-v1u3hw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @tbg)

___
*[pkg/kv/kvserver/store.go, line 1340 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/53152#-MGNfncL3klnag4dXx5k:-MGPYHr9D3QhjejrVP2l:bt5urvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/fea4ccf2ab172e87dc14bffee01a2f7d3cb0cffc/pkg/kv/kvserver/store.go#L1340)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

doesn't this all simplify to

```go
if err := fn(desc); iterutil.Done(err) { return iterutil.StopIteration() }
return err
```
</blockquote></details>

Oh yeah it does! I'll make this change.

**Comment by tbg** [comment]
Ready to merge this now but there's one merge conflict - want to do the honors, @vrongmeal? Otherwise I will tomorrow.

**Comment by vrongmeal** [comment]
> Ready to merge this now but there's one merge conflict - want to do the honors, @vrongmeal? Otherwise I will tomorrow.

I'll fix it right away :)

**Pull request merged**
