### PR TITLE
sql: switch to our forked yacc to prevent NTYPES error

### PR DESCRIPTION
**Pull request by madelynnblue**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8623)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Thanks for taking care of this!

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/parser/sql_union.sh, line 15 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8623#-KPPRvDfEiAZ0RlhoCqw:-KPPRvDfEiAZ0RlhoCqx:b-8bh2b4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3abbebd61e6e669bf70429e4d78358646958c37e/sql/parser/sql_union.sh#L15)):*
> ```Shell
> # compiler does not type check Go code.
> function type_check() {
>     ! $YACC -o /dev/null -p sql sql.y | grep -F 'conflicts'
> ```

Can we fix these lines so the whole thing fails if the yacc command fails? (you can test with the old yacc..)
Could check that `${PIPESTATUS[0]}` is 0, or yacc to a temporary file and then grep.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8623#-:-KPPRtVbgKj9_oEtIBfb:btrfu2e)*

**Comment by mjibson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/parser/sql_union.sh, line 15 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8623#-KPPRvDfEiAZ0RlhoCqw:-KPR-JYH6CIECLg1DjDz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3abbebd61e6e669bf70429e4d78358646958c37e/sql/parser/sql_union.sh#L15)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Can we fix these lines so the whole thing fails if the yacc command fails? (you can test with the old yacc..)
> Could check that `${PIPESTATUS[0]}` is 0, or yacc to a temporary file and then grep.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8623)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/parser/sql_union.sh, line 15 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8623#-KPPRvDfEiAZ0RlhoCqw:-KPSLItYUN1aYqEXoNDi:bvjh3sf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3abbebd61e6e669bf70429e4d78358646958c37e/sql/parser/sql_union.sh#L15)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Done.
</details>
The new line is obscuring the return code of the previous line. If we replace the yacc cmd with "echo conflicts", this still succeeds.. I believe if we add an `|| exit 1` it would work.

This was an existing problem in the other case (inside compile). I think it was relying on `set -e` but that doesn't actually exit when `!` is used. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8623)*

**Comment by tamird** [comment]
`goyacc` was moved out to github.com/golang/tools today. I've just submitted https://go-review.googlesource.com/#/c/27350/ which will remove the need for our fork.

**Comment by mjibson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/parser/sql_union.sh, line 15 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8623#-KPPRvDfEiAZ0RlhoCqw:-KPTi5Qws8HkuFloJNcx:b-2nr6rp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3abbebd61e6e669bf70429e4d78358646958c37e/sql/parser/sql_union.sh#L15)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> The new line is obscuring the return code of the previous line. If we replace the yacc cmd with "echo conflicts", this still succeeds.. I believe if we add an `|| exit 1` it would work.
> 
> This was an existing problem in the other case (inside compile). I think it was relying on `set -e` but that doesn't actually exit when `!` is used. 
</details>
Ugh. Bash really not my thing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8623)*

**Comment by RaduBerinde** [comment]
LGTM (modulo Tamir's comment to use `golang/tools`)

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8623#-:-KPTrBVFw2ctPP3EAbeE:bj0zw2q)*

**Comment by mjibson** [comment]
I'll make another PR once the yacc stuff is merged upstream.

**Pull request merged**
