### PR TITLE
sql: add randomized test for plan-gist logic

### LINKED ISSUE #117634: sql: add randomized testing for gist decoding
**Is your feature request related to a problem? Please describe.**
We have found that there are cases where decoding a gist can cause panics when the encoded format doesn't exactly match what is expected by the code. For example, see https://github.com/cockroachdb/cockroach/issues/113900. This is especially likely when decoding a gist that was encoded by a different version of CockroachDB.

The DB console performs gist decoding of sampled queries, making it likely that a customer might run into this issue in production.

**Describe the solution you'd like**
We'd like to discover cases where gist decoding can cause panics so they can be fixed *before* customers run into them in production. One idea is to randomly generate queries using sqlsmith, encode them as a gist, and then make sure they can be decoded without a panic. We could also write this as a mixed version roach test.

Jira issue: CRDB-35283

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit adds a randomized test for plan-gist logic. It utilizes sqlsmith to generate random stmts, then runs EXPLAIN (GIST) for it to retrieve the gist followed by decoding that gist, and ensures that no internal errors occur. All generated stmts are also executed with a short timeout to allow for DB state to evolve. Additionally, all gists are accumulated and decoded against an empty DB.

The test is placed in the ccl package to exercise features gated behind CCL license.

The test quickly discovered bug fixed in 1315dda2d60f6064ff112c4d169cfdb8a1ce224c (when the corresponding fix is reverted) but haven't found anything new for plan-gist logic (but did hit a few issues elsewhere which are currently ignored in the test).

Fixes: #117634.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Actually, hold off on reviewing this - it seems like this test is uncovering some issues (not directly related to plan gist though).

**Comment by yuzefovich** [comment]
It's RFAL.

**Comment by yuzefovich** [comment]
Friendly ping @mgartner

**Review by mgartner — APPROVED** [review]
Nice! :lgtm: just a few questions

> Reviewed 1 of 3 files at r3, 2 of 2 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122864#-:-Nxy6Zhi3wF-jNVpBE-s:beb0lwl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/ccl/testccl/sqlccl/explain_test.go` line 235 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/122864#-Nxy5mqn-BcPDAKbLZG_:-Nxy5mqn-BcPDAKbLZGa:bjiqju3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a073ee1cc58fd87d01e962a858085c188f7bbe33/pkg/ccl/testccl/sqlccl/explain_test.go#L235)):*
> ```Go
> 				}
> 				// Short statement timeout might exceed planning time. Let's
> 				// retry this statement with longer timeout.
> ```

What's the purpose of the lower timeout set above if we're just going to retry here anyway?
___
*[`pkg/ccl/testccl/sqlccl/explain_test.go` line 287 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/122864#-Nxy6Vdi2aZOW00e_HBZ:-Nxy6Vdi2aZOW00e_HB_:b-efbcru) ([raw file](https://github.com/cockroachdb/cockroach/blob/a073ee1cc58fd87d01e962a858085c188f7bbe33/pkg/ccl/testccl/sqlccl/explain_test.go#L287)):*
> ```Go
> 			// Execute the stmt with short timeout so that the table schema is
> 			// modified. We do so in a separate goroutine to ensure that we fail
> 			// the test if the stmt doesn't respect the timeout.
> ```

I don't understand this, can you clarify?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122864)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[`pkg/ccl/testccl/sqlccl/explain_test.go` line 235 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/122864#-Nxy5mqn-BcPDAKbLZG_:-Nxz6GLm9ThJeJFon4Yu:b7jcldo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a073ee1cc58fd87d01e962a858085c188f7bbe33/pkg/ccl/testccl/sqlccl/explain_test.go#L235)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

What's the purpose of the lower timeout set above if we're just going to retry here anyway?
</blockquote></details>

My thinking was as follows: we want to evolve the state of the DB over time so that different plans could be generated, and we do by attempting to execute each statement that is generated on a best effort basis - if the statement takes longer than 0.1s, then it should be canceled. However, we do really want to execute `EXPLAIN (GIST)` statement successfully, and in some edge cases the planning time might exceed 0.1s, so we allow only `EXPLAIN (GIST)` variant to be re-run with 1s timeout (if it still fails, then we fail the test - 1s planning time seems too high).

In other words, we execute three flavors of statements:
- `EXPLAIN (GIST)`
- `decode_plan_gist`
- randomly generated by sqlsmith stmt .

We want to try decoding as many plan gists as possible, so we use a short timeout of 0.1s. However, `EXPLAIN (GIST)` gets an exception in case the planning time exceeds 0.1s - it is retried with 1s timeout.

Thoughts on this approach?
___
*[`pkg/ccl/testccl/sqlccl/explain_test.go` line 287 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/122864#-Nxy6Vdi2aZOW00e_HBZ:-Nxz7loI71aeD0n1xoyi:b-oxxxc0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a073ee1cc58fd87d01e962a858085c188f7bbe33/pkg/ccl/testccl/sqlccl/explain_test.go#L287)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't understand this, can you clarify?
</blockquote></details>

The idea is that if we execute a stmt within main test goroutine and it doesn't respect the statement timeout, then the test will get stuck until the stmt completes or eventually gets canceled (possibly taking minutes to do so), or the test run times out. Using a separate goroutine allows us to effectively enforce that all statements are canceled with 1m when statement timeout is 0.1s, and to fail the test cleanly - if we relied on the test run timing out, it would be a little bit less pretty of a failure mode. I extended the comment a bit. Does this sound reasonable?

**Review by mgartner — COMMENTED** [review]
> Reviewed 2 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122864)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[`pkg/ccl/testccl/sqlccl/explain_test.go` line 235 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/122864#-Nxy5mqn-BcPDAKbLZG_:-NyLXHBo1JkWp7YqBwz7:b-y9yutt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a073ee1cc58fd87d01e962a858085c188f7bbe33/pkg/ccl/testccl/sqlccl/explain_test.go#L235)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

My thinking was as follows: we want to evolve the state of the DB over time so that different plans could be generated, and we do by attempting to execute each statement that is generated on a best effort basis - if the statement takes longer than 0.1s, then it should be canceled. However, we do really want to execute `EXPLAIN (GIST)` statement successfully, and in some edge cases the planning time might exceed 0.1s, so we allow only `EXPLAIN (GIST)` variant to be re-run with 1s timeout (if it still fails, then we fail the test - 1s planning time seems too high).

In other words, we execute three flavors of statements:
- `EXPLAIN (GIST)`
- `decode_plan_gist`
- randomly generated by sqlsmith stmt .

We want to try decoding as many plan gists as possible, so we use a short timeout of 0.1s. However, `EXPLAIN (GIST)` gets an exception in case the planning time exceeds 0.1s - it is retried with 1s timeout.

Thoughts on this approach?
</blockquote></details>

Why not always run `SET statement_timeout = '1s'` before running `EXPLAIN (GIST)` and remove the retry logic?

Also, I don't think that the statement timeout is reset to `0.1s` after an `EXPLAIN` times-out.
___
*[`pkg/ccl/testccl/sqlccl/explain_test.go` line 287 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/122864#-Nxy6Vdi2aZOW00e_HBZ:-NyLWFUJ84kzNNGAaK9R:b-ce2xx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a073ee1cc58fd87d01e962a858085c188f7bbe33/pkg/ccl/testccl/sqlccl/explain_test.go#L287)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

The idea is that if we execute a stmt within main test goroutine and it doesn't respect the statement timeout, then the test will get stuck until the stmt completes or eventually gets canceled (possibly taking minutes to do so), or the test run times out. Using a separate goroutine allows us to effectively enforce that all statements are canceled with 1m when statement timeout is 0.1s, and to fail the test cleanly - if we relied on the test run timing out, it would be a little bit less pretty of a failure mode. I extended the comment a bit. Does this sound reasonable?
</blockquote></details>

Yes, looks good. Thanks for clarifying!

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122864)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[`pkg/ccl/testccl/sqlccl/explain_test.go` line 235 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/122864#-Nxy5mqn-BcPDAKbLZG_:-NyLqr0DB0vlKkhpBCPf:b-psops2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a073ee1cc58fd87d01e962a858085c188f7bbe33/pkg/ccl/testccl/sqlccl/explain_test.go#L235)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Why not always run `SET statement_timeout = '1s'` before running `EXPLAIN (GIST)` and remove the retry logic?

Also, I don't think that the statement timeout is reset to `0.1s` after an `EXPLAIN` times-out.
</blockquote></details>

Having `1s` timeout could make the test noticeably longer for no good reason. Currently, it runs 500 statements, so in the worst case (assuming stmt timeout cancellation is respected) it could take on the order of 10 minutes, with `0.1s` timeout it'd be just 1 minute. The main goal of the test is exercising as many plans as possible and modifying the DB state is a nice-to-have for that, but the number of generated statements is more important (in other words, I think it's beneficial to have more statements with short timeout than fewer statements for the longer timeout - assuming we're keeping the test runtime the same).

The statement timeout is reset in the defer:
```
					runner.Exec(t, "SET statement_timeout = '1s'")
					defer runner.Exec(t, timeoutStmt)
```

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122864)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[`pkg/ccl/testccl/sqlccl/explain_test.go` line 235 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/122864#-Nxy5mqn-BcPDAKbLZG_:-NyMsHir4pZ4DR9aTKkF:bs7tlkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a073ee1cc58fd87d01e962a858085c188f7bbe33/pkg/ccl/testccl/sqlccl/explain_test.go#L235)):*
> with `0.1s` timeout it'd be just 1 minute.

Something must be going right over my head. Isn't the worst case`500 * (0.1s + 1s)` currently?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122864)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[`pkg/ccl/testccl/sqlccl/explain_test.go` line 235 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/122864#-Nxy5mqn-BcPDAKbLZG_:-NyMvuRiD4mCNGau6Fbh:b-341zkz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a073ee1cc58fd87d01e962a858085c188f7bbe33/pkg/ccl/testccl/sqlccl/explain_test.go#L235)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

> with `0.1s` timeout it'd be just 1 minute.

Something must be going right over my head. Isn't the worst case`500 * (0.1s + 1s)` currently?
</blockquote></details>

You're right. In the strictest sense this is the worst case; however, under optimistic assumption that `EXPLAIN (GIST)` takes trivial time and can be ignored (as well as ignoring time it takes to execute `SET statement_timeout = ...`) I'm estimating `500 * 0.1s`.

**Review by mgartner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122864#-:-NyN1oXN5ytnv_0FI384:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
Thanks for the review!

bors r+

**Comment by rickystewart** [comment]
Looks like you need to `dev gen bazel`, please check the CI results before `bors`'ing.

**Comment by yuzefovich** [comment]
Indeed, my bad.

**Pull request merged**
