### PR TITLE
sqlproxyccl: use addr.SplitHostPort for IPv6 support

### PR DESCRIPTION
**Pull request by chrisseto**
Previously, the sqlproxy would parse incoming and outgoing addresses
    using golang's net.SplitHostPort function. This was inadequate
    because net.SplitHostPort does not know how to correctly parse IPv6
    addresses. This commit correctly uses addr.SplitHostPort to ensure
    that both IPv4 and IPv6 are supported.
    This commit also includes an updated release note for #69959.

Release note (bug fix, security update): cockroach mt start-proxy now
appropriately sets the .ServerName member of outgoing TLS connections.
This allows the proxy to function appropriately when the --insecure and
--skip-verify CLI flags are ommitted.

Release justification: Having a verified TLS connection betweeen the
SQLProxy and SQL Pods in Cockroach Serverless is a requirement for the
beta release. This code change enables that secure connection without
making any changes to CockroachDB, itself.

### CODE REVIEW

**Review by chrisseto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70323)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/ccl/sqlproxyccl/proxy_handler_test.go, line 1081 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70323#-Mjjbr2U3dtZPf630zfE:-Mjjbr2U3dtZPf630zfF:b-fv653f) ([raw file](https://github.com/cockroachdb/cockroach/blob/61396342178393a02bdb5ddd516017867719b1cf/pkg/ccl/sqlproxyccl/proxy_handler_test.go#L1081)):*
> ```Go
> 	require.NoError(t, err)
> 
> 	// If routing rule is not specified, default to something that will
> ```

This block was removed because `addr.SplitHostPort` can handle addresses without ports.

**Review by knz — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70323)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chrisseto)

**Comment by chrisseto** [comment]
TFTR!

**Comment by chrisseto** [comment]
bors r=knz

**Pull request merged**
