### PR TITLE
leaktest, stop: don't recover from panics

### PR DESCRIPTION
**Pull request by andreimatei**
See individual commits.

Epic: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]

**Review by andreimatei — COMMENTED** [review]
@knz do I have your blessing too?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92627#-:-NI8bLKC2Eil8JlXOOLF:b-6kp789)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Comment by knz** [comment]
This one I don't have an opinion on. It's all yours (and tobi's).

**Review by andreimatei — COMMENTED** [review]
I've tweaked this so that `leaktest` does a `t.Log(<recovered panic>)` so that it looks better in TeamCity. With this, the experience on panic on TC is good - the panicking test is identified, and you see the panic in the snippet, etc.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92627#-:-NIIm8BGCcVduPV9dFHf:b-4l7dt4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92627#-:-NIJQtxl88JDwLn21BAr:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Pull request merged**
