### PR TITLE
storage: Add support for TargetBytes for resolve intent + range cmd

### PR DESCRIPTION
**Pull request by KaiSun314**
Informs: #77228

Intent resolution batches are sequenced on raft and each batch can consist of 100-200 intents. If an intent key or even value in some cases are large, it is possible that resolving all intents in the batch would result in a raft command size exceeding the max raft command size kv.raft.command.max_size.
    
To address this, we add support for TargetBytes in resolve intent and resolve intent range commands, allowing us to stop resolving intents in the batch as soon as we exceed the TargetBytes max bytes limit.
    
Adding support for byte size pagination for intent resolver and RequestBatcher is added in PR https://github.com/cockroachdb/cockroach/pull/92268.
    
Release note (ops change): Added support for a byte limit on resolve intent and resolve intent range raft commands to prevent such commands from exceeding the max raft command size.

### CODE REVIEW

**Comment by KaiSun314** [comment]
The second commit "storage: Add support for TargetBytes for resolve intent + range cmd" is rebased on top of the first commit "intentresolver: Add max timeout to RequestBatcher and IntentResolver". Please only review the second commit. Thank you so much in advance!

**Review by nvb — COMMENTED** [review]
@itsbilal do you mind giving the changes to `pkg/storage` a review? I want to make sure that you're bought into this expansion of the `Writer` API.

> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-:-NI3dWkw2sz93SQhOwDE:bl5mp8q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @KaiSun314)

___
*[`pkg/storage/engine.go` line 602 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NI3d-LD4jE5zE1hw6PM:-NI3d-LD4jE5zE1hw6PN:bc45xdd) ([raw file](https://github.com/cockroachdb/cockroach/blob/868b652a27e76ad973225a33d93e4ea9b3eec404/pkg/storage/engine.go#L602)):*
> ```Go
> 	PinEngineStateForIterators() error
> 
> 	Len() int
> ```

This should live on `Writer`, not `Reader`.

We'll want to give it a comment that explains the semantics of the method both when the `Writer` implementation is "buffered" and when it is not. That may drive us to rename the method to something more specific, like `BufferredSize` or something along those lines.
___
*[`pkg/storage/mvcc.go` line 3971 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NI3b_YT8Hg7JSZJq6LK:-NI3b_YT8Hg7JSZJq6LL:bowqgxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/868b652a27e76ad973225a33d93e4ea9b3eec404/pkg/storage/mvcc.go#L3971)):*
> ```Go
> }
> 
> // MVCCResolveWriteIntentWithMaxBytes is MVCCResolveWriteIntent but with
> ```

Pushing the byte limiting and accounting into the mvcc stack is symmetrical with `MVCCResolveWriteIntentRange`, but not with `MVCCGet`. See:
https://github.com/cockroachdb/cockroach/blob/2fe7b94f759eead45742dad1ba88407618b7cf47/pkg/kv/kvserver/batcheval/cmd_get.go#L35-L50

I think either approach works, but we should try to be consistent. One argument for lifting it out of mvcc and into batch evaluation is that point intent resolution should also be handling key limits (it currently is not). So if we push byte limits into mvcc, we would also want to push key limits into mvcc.

I'm curious if @erikgrinaker has thoughts about this.
___
*[`pkg/storage/mvcc.go` line 3982 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NI3aLpl7gvuci69aZ60:-NI3aLpl7gvuci69aZ61:b-tf6we4) ([raw file](https://github.com/cockroachdb/cockroach/blob/868b652a27e76ad973225a33d93e4ea9b3eec404/pkg/storage/mvcc.go#L3982)):*
> ```Go
> 	intent roachpb.LockUpdate,
> 	maxBytes int64,
> ) (bool, int64, *roachpb.Span, error) {
> ```

Let's name these return values: `) (ok bool, numBytes int64, resumeSpan *roachpb.Span, err error) {`
___
*[`pkg/storage/mvcc.go` line 3989 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NI3aAAa85Pw8BgeCmfz:-NI3aAAa85Pw8BgeCmg-:b-vgd0ej) ([raw file](https://github.com/cockroachdb/cockroach/blob/868b652a27e76ad973225a33d93e4ea9b3eec404/pkg/storage/mvcc.go#L3989)):*
> ```Go
> 		return false, 0, nil, errors.Errorf("can't resolve range intent as point intent")
> 	}
> ```

style nit: remove this empty line for consistency.
___
*[`pkg/storage/mvcc.go` line 4763 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NI3auE2DyHdNgkaMT-h:-NI3auE2DyHdNgkaMT-i:bhqwn6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/868b652a27e76ad973225a33d93e4ea9b3eec404/pkg/storage/mvcc.go#L4763)):*
> ```Go
> 	maxKeys int64,
> ) (int64, *roachpb.Span, error) {
> 	numKeys, _, resumeSpan, _, err := MVCCResolveWriteIntentRangeWithMaxBytes(ctx, rw, ms, intent, maxKeys, 0)
> ```

It's up to you, but we may not even want to add these `WithMaxBytes(` variants. We could just add the new param to each existing function.

If we do want them split though, it's odd that this takes a `maxKeys` but not a `maxBytes`. Perhaps this should move the `maxKeys` param to live only on the second function.
___
*[`pkg/storage/mvcc.go` line 4767 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NI3dzn2BWwvsbr1Zq5q:-NI3dzn2BWwvsbr1Zq5r:b-shkp40) ([raw file](https://github.com/cockroachdb/cockroach/blob/868b652a27e76ad973225a33d93e4ea9b3eec404/pkg/storage/mvcc.go#L4767)):*
> ```Go
> }
> 
> // MVCCResolveWriteIntentRangeWithMaxBytes is MVCCResolveWriteIntentRange but
> ```

We should add testing for this new form of intent resolution pagination to `TestMVCCHistories`. We might as well also extend that form of testing to support key pagination while we're here.

We can also extend/duplicate `TestMVCCResolveTxnRangeResume` to work with size pagination.
___
*[`pkg/storage/mvcc.go` line 4780 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NI3aeRB2yHeX31MUm_O:-NI3aeRB2yHeX31MUm_P:b-p7mjqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/868b652a27e76ad973225a33d93e4ea9b3eec404/pkg/storage/mvcc.go#L4780)):*
> ```Go
> 	intent roachpb.LockUpdate,
> 	maxKeys, maxBytes int64,
> ) (int64, int64, *roachpb.Span, roachpb.ResumeReason, error) {
> ```

Let's name these return values as well.

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 7 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92267)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @itsbilal, @KaiSun314, and @nvanbenschoten)

___
*[`pkg/roachpb/api.proto` line 2426 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NI3n7v10KAJlWne6K9t:-NI3n7v10KAJlWne6K9u:b7j1woq) ([raw file](https://github.com/cockroachdb/cockroach/blob/868b652a27e76ad973225a33d93e4ea9b3eec404/pkg/roachpb/api.proto#L2426)):*
> ```protobuf
>   // We will resolve intents until the number of bytes added to the write batch
>   // by intent resolution exceeds the TargetBytes limit. A suitable resume span
>   // will be returned.
> ```

What about synchronous intent resolution which is presumably not going through this limiting path (there is no change to cmd_end_transaction.go).
___
*[`pkg/storage/engine.go` line 602 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NI3d-LD4jE5zE1hw6PM:-NI3oEdk-NWHx6xAuEcb:b-o275kv) ([raw file](https://github.com/cockroachdb/cockroach/blob/868b652a27e76ad973225a33d93e4ea9b3eec404/pkg/storage/engine.go#L602)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This should live on `Writer`, not `Reader`.

We'll want to give it a comment that explains the semantics of the method both when the `Writer` implementation is "buffered" and when it is not. That may drive us to rename the method to something more specific, like `BufferredSize` or something along those lines.
</blockquote></details>

I like `BufferedSize`.
___
*[`pkg/storage/mvcc.go` line 3971 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NI3b_YT8Hg7JSZJq6LK:-NI3pozb7v2-D1FgpwuH:b-jw4yr4) ([raw file](https://github.com/cockroachdb/cockroach/blob/868b652a27e76ad973225a33d93e4ea9b3eec404/pkg/storage/mvcc.go#L3971)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Pushing the byte limiting and accounting into the mvcc stack is symmetrical with `MVCCResolveWriteIntentRange`, but not with `MVCCGet`. See:
https://github.com/cockroachdb/cockroach/blob/2fe7b94f759eead45742dad1ba88407618b7cf47/pkg/kv/kvserver/batcheval/cmd_get.go#L35-L50

I think either approach works, but we should try to be consistent. One argument for lifting it out of mvcc and into batch evaluation is that point intent resolution should also be handling key limits (it currently is not). So if we push byte limits into mvcc, we would also want to push key limits into mvcc.

I'm curious if @erikgrinaker has thoughts about this.
</blockquote></details>

I don't have a real opinion on this, but by lifting the enforcement logic outside mvcc.go, we would be having similar enforcement logic in cmd_end_transaction.go (which already has `resolveAllowance`) and in cmd_resolve_intent.go.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92267)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @KaiSun314, @nvanbenschoten, and @sumeerbhola)

___
*[`pkg/storage/mvcc.go` line 3971 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NI3b_YT8Hg7JSZJq6LK:-NI3zPz82ZrTrIowSxmo:b-6goik7) ([raw file](https://github.com/cockroachdb/cockroach/blob/868b652a27e76ad973225a33d93e4ea9b3eec404/pkg/storage/mvcc.go#L3971)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't have a real opinion on this, but by lifting the enforcement logic outside mvcc.go, we would be having similar enforcement logic in cmd_end_transaction.go (which already has `resolveAllowance`) and in cmd_resolve_intent.go.
</blockquote></details>

I suspect the reason it hasn't been moved down into `MVCCGet` is that it's sort of odd to have a `MVCCGetOptions.MaxKeys` parameter which will only ever be set to -1 to disable the limit or left unset (effectively defaults to 1), and `TargetBytes` would previously always allow overflow which meant it also only made sense to set it to -1 or leave it unset. With `TargetBytes` now being strict with `AllowEmpty` I think it makes more sense to push it down into `MVCCGet`. It may be somewhat odd, but I think the consistency is worthwhile, and would also allow better parameter testing down in the storage package where we can leverage e.g. data-driven tests (`TestMVCCHistories`).

**Review by KaiSun314 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92267)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @itsbilal, @nvanbenschoten, and @sumeerbhola)

___
*[`pkg/roachpb/api.proto` line 2426 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NI3n7v10KAJlWne6K9t:-NJ8asg_07n0pAouPD_V:b-mye9c9) ([raw file](https://github.com/cockroachdb/cockroach/blob/868b652a27e76ad973225a33d93e4ea9b3eec404/pkg/roachpb/api.proto#L2426)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

What about synchronous intent resolution which is presumably not going through this limiting path (there is no change to cmd_end_transaction.go).
</blockquote></details>

Added byte pagination for `EndTxn` as well
___
*[`pkg/storage/engine.go` line 602 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NI3d-LD4jE5zE1hw6PM:-NJ8cB-200DWnEUC-8Ki:b9qhvwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/868b652a27e76ad973225a33d93e4ea9b3eec404/pkg/storage/engine.go#L602)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I like `BufferedSize`.
</blockquote></details>

Moved to `Writer`, changed name to `BufferedSize`, and added comment.
___
*[`pkg/storage/mvcc.go` line 3971 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NI3b_YT8Hg7JSZJq6LK:-NJ8bKXf1yun6_Xf4qsq:b-oky38c) ([raw file](https://github.com/cockroachdb/cockroach/blob/868b652a27e76ad973225a33d93e4ea9b3eec404/pkg/storage/mvcc.go#L3971)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I suspect the reason it hasn't been moved down into `MVCCGet` is that it's sort of odd to have a `MVCCGetOptions.MaxKeys` parameter which will only ever be set to -1 to disable the limit or left unset (effectively defaults to 1), and `TargetBytes` would previously always allow overflow which meant it also only made sense to set it to -1 or leave it unset. With `TargetBytes` now being strict with `AllowEmpty` I think it makes more sense to push it down into `MVCCGet`. It may be somewhat odd, but I think the consistency is worthwhile, and would also allow better parameter testing down in the storage package where we can leverage e.g. data-driven tests (`TestMVCCHistories`).
</blockquote></details>

It seems most of the commands have all pushed pagination into MVCC, so to keep consistency, I have pushed pagination for `Get` and `EndTxn` into MVCC and kept `ResolveIntent` and `ResolveIntentRange` in MVCC.
___
*[`pkg/storage/mvcc.go` line 4763 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NI3auE2DyHdNgkaMT-h:-NJ8bjwUAJx4rVtaxKfD:b-89e4qb) ([raw file](https://github.com/cockroachdb/cockroach/blob/868b652a27e76ad973225a33d93e4ea9b3eec404/pkg/storage/mvcc.go#L4763)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's up to you, but we may not even want to add these `WithMaxBytes(` variants. We could just add the new param to each existing function.

If we do want them split though, it's odd that this takes a `maxKeys` but not a `maxBytes`. Perhaps this should move the `maxKeys` param to live only on the second function.
</blockquote></details>

Made param into an Options type similar to what MVCCGet / MVCCScan have, this param contains the MaxKeys and MaxBytes.
___
*[`pkg/storage/mvcc.go` line 4767 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NI3dzn2BWwvsbr1Zq5q:-NJ8bv4z1LOMD6AEMsnM:bja88ad) ([raw file](https://github.com/cockroachdb/cockroach/blob/868b652a27e76ad973225a33d93e4ea9b3eec404/pkg/storage/mvcc.go#L4767)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We should add testing for this new form of intent resolution pagination to `TestMVCCHistories`. We might as well also extend that form of testing to support key pagination while we're here.

We can also extend/duplicate `TestMVCCResolveTxnRangeResume` to work with size pagination.
</blockquote></details>

Added a test for byte and key pagination to `TestMVCCHistories`, added byte pagination to `TestMVCCResolveTxnRangeResume`

**Review by itsbilal — COMMENTED** [review]
Storage package changes mostly looking good! Thanks for the ping @nvanbenschoten and sorry for the delay.

> Reviewed 7 of 27 files at r7, 1 of 16 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-:-NJRA5a259rIVdpIwRj7:bdtedd2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @KaiSun314, @nvanbenschoten, and @sumeerbhola)

___
*[`pkg/storage/engine.go` line 822 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NJRAfVwDtBxgPxQ75dl:-NJRAfVwDtBxgPxQ75dm:b-msblag) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f222dc615dcee340068b6bfbb257d1060393a2f/pkg/storage/engine.go#L822)):*
> ```Go
> 	// BufferedSize returns the size of the underlying buffered writes if the
> 	// Writer implementation is buffered, and 0 if the Writer implementation is
> 	// not buffered.
> ```

Probably worth mentioning here that buffered writers are expected to always give a monotonically increasing size, as your use relies on that aspect of it.
___
*[`pkg/storage/mvcc.go` line 4057 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NJQsnWL7V3waO7M1Ugk:-NJQsnWL7V3waO7M1Ugl:b-ds9k4a) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f222dc615dcee340068b6bfbb257d1060393a2f/pkg/storage/mvcc.go#L4057)):*
> ```Go
> 	ctx context.Context,
> 	maxKeys, targetBytes int64,
> 	done func() bool,
> ```

Passing in two closures that somehow have a cross-dependency on one another seems a bit convoluted when you can add an `ok bool` return value to `f` that also denotes if you want to continue or not, right?

Alternatively you could use a nil `resumeSpan` to mean there's no more resumption to be done, and remove the assertion check for that down below.
___
*[`pkg/storage/mvcc.go` line 4060 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NJQqjWN4ciZYJ90rub-:-NJQqjWN4ciZYJ90rub0:btk7qgz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f222dc615dcee340068b6bfbb257d1060393a2f/pkg/storage/mvcc.go#L4060)):*
> ```Go
> 	f func(maxKeys, targetBytes int64) (numKeys, numBytes int64, resumeSpan *roachpb.Span, err error),
> ) (numKeys, numBytes int64, resumeReason roachpb.ResumeReason, err error) {
> 	for {
> ```

nit:
```
for !done() {
...
}
```
___
*[`pkg/storage/mvcc.go` line 4066 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NJR9F57EBNGMi_AaVn-:-NJR9F57EBNGMi_AaVn0:bz2rn3m) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f222dc615dcee340068b6bfbb257d1060393a2f/pkg/storage/mvcc.go#L4066)):*
> ```Go
> 		if maxKeys < 0 {
> 			resumeReason = roachpb.RESUME_KEY_LIMIT
> 			return
> ```

We have a convention on avoiding implicit return vars, so this would preferably be:

` return numKeys, numBytes, roachpb.RESUME_KEY_LIMIT, nil`

and same with the cases below.

**Review by KaiSun314 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92267)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @itsbilal, @nvanbenschoten, and @sumeerbhola)

___
*[`pkg/storage/engine.go` line 822 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NJRAfVwDtBxgPxQ75dl:-NJT_HiU2oDmOZUpstmi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f222dc615dcee340068b6bfbb257d1060393a2f/pkg/storage/engine.go#L822)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Probably worth mentioning here that buffered writers are expected to always give a monotonically increasing size, as your use relies on that aspect of it.
</blockquote></details>

Done.
___
*[`pkg/storage/mvcc.go` line 4066 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NJR9F57EBNGMi_AaVn-:-NJT_NUtAzn9LBlE8sZW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f222dc615dcee340068b6bfbb257d1060393a2f/pkg/storage/mvcc.go#L4066)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

We have a convention on avoiding implicit return vars, so this would preferably be:

` return numKeys, numBytes, roachpb.RESUME_KEY_LIMIT, nil`

and same with the cases below.
</blockquote></details>

Done.

**Review by KaiSun314 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92267)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @itsbilal, @nvanbenschoten, and @sumeerbhola)

___
*[`pkg/storage/mvcc.go` line 4057 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NJQsnWL7V3waO7M1Ugk:-NJlGc-o3rdHq2AvhafJ:bu5qrq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f222dc615dcee340068b6bfbb257d1060393a2f/pkg/storage/mvcc.go#L4057)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Passing in two closures that somehow have a cross-dependency on one another seems a bit convoluted when you can add an `ok bool` return value to `f` that also denotes if you want to continue or not, right?

Alternatively you could use a nil `resumeSpan` to mean there's no more resumption to be done, and remove the assertion check for that down below.
</blockquote></details>

The original code looked like
```
for _, span := range args.LockSpans {
  if resolveAllowance == 0 {
    // check key / byte limits
  }
  // do normal execution i.e. f()
}
```
I feel that we should have these two closures, one that executes before we check the key / byte limits (i.e. `done()`) and one that executes after (i.e. `f()`) in order to ensure behavior stays the same. If we didn't have the `done()` closure and moved checking `done()` into `f()`, then it is possible that we finished iterating through everything but because we check the key / byte limits first, we could still return that we hit the key / byte limit despite iterating through everything. This could result in confusion / edge cases when determining whether we should return a resume span.

**Review by nvb — COMMENTED** [review]
The changes here seem quite positive! But this is also becoming a large PR that combines the original change with multiple semi-related refactors. That increases the risk that a bug might fall through the cracks, that we're not sufficiently testing part of the changes, and that we'll have a difficult time bisecting any issues after the fact. We'll need to split these refactors out into multiple PRs which each individually ensure sufficient testing. I'd suggest pulling out at least:
1. the refactor to push `cmd_get.go` pagination handling into MVCC (with associated mvcc history testing).
2. the introduction of the new `MVCCPagination` function and then (in a separate commit) its integration into `resolveLocalLocks`.
3. (maybe) the new `MVCCResolveWriteIntentOptions` and `MVCCResolveWriteIntentRangeOptions` structs. Or at least pull that into a separate commit in this PR so that the code movement is split from the logic changes.

> Reviewed 11 of 27 files at r7, 3 of 16 files at r8, 1 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-:-NJqF4AlABjstgTOwACq:blinidz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @KaiSun314, and @sumeerbhola)

___
*[`pkg/kv/kvserver/batcheval/cmd_end_transaction.go` line 503 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NJqBP6t-yulDTY-zCRJ:-NJqBP6t-yulDTY-zCRK:bzaoxp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b10bc5f50e6edeba249eee6d9311347d429ee63c/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L503)):*
> ```Go
> 
> const lockResolutionBatchSize = 500
> const lockResolutionBatchByteSize = 4 << 20
> ```

`// 4MB`
___
*[`pkg/kv/kvserver/batcheval/cmd_end_transaction.go` line 524 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NJqBa419w-EvkLLO95R:-NJqBa419w-EvkLLO95S:b-9ev4dp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b10bc5f50e6edeba249eee6d9311347d429ee63c/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L524)):*
> ```Go
> 	var targetBytes int64 = lockResolutionBatchByteSize
> 	if args.InternalCommitTrigger != nil {
> 		// If this is a system transaction (such as a split or merge), don't enforce the resolve allowance.
> ```

nit: wrap this comment at 80 chars.
___
*[`pkg/kv/kvserver/batcheval/cmd_end_transaction.go` line 552 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NJqC9hK1j-T5UHrKit5:-NJqC9hK1j-T5UHrKit6:b-myz0lg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b10bc5f50e6edeba249eee6d9311347d429ee63c/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L552)):*
> ```Go
> 
> 	i := 0
> 	done := func() bool {
> ```

Instead of passing a `done` function to `MVCCPagination`, it would be more natural to have functions return `iterutil.StopIteration()` when they have reached their limit and then have `MVCCPagination` catch this error and return. This would then more closely mirror the behavior or `storage.MVCCIterate`.
___
*[`pkg/kv/kvserver/batcheval/cmd_end_transaction.go` line 558 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NJqDobX1r9Ut72rOQwr:-NJqDobX1r9Ut72rOQws:b7runaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b10bc5f50e6edeba249eee6d9311347d429ee63c/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L558)):*
> ```Go
> 		span := args.LockSpans[i]
> 		i++
> 		if err := func() error {
> ```

Do we still need this inner closure? Can we lift the error wrapping outside the call to `MVCCPagination`?
___
*[`pkg/kv/kvserver/batcheval/cmd_end_transaction.go` line 589 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NJqDEyTAVLyyFHyTzhN:-NJqDEyTAVLyyFHyTzhO:b-nps46u) ([raw file](https://github.com/cockroachdb/cockroach/blob/b10bc5f50e6edeba249eee6d9311347d429ee63c/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L589)):*
> ```Go
> 					resolvedLocks = append(resolvedLocks, update)
> 					// If requested, replace point tombstones with range tombstones.
> 					if ok && evalCtx.EvalKnobs().UseRangeTombstonesForPointDeletes {
> ```

Should we move this into the `ok` branch above? It doesn't seem directly related to the resumeSpan condition.
___
*[`pkg/kv/kvserver/batcheval/cmd_end_transaction.go` line 618 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NJqECRgBIIufrhtiiO6:-NJqECRgBIIufrhtiiO7:b8cb3d) ([raw file](https://github.com/cockroachdb/cockroach/blob/b10bc5f50e6edeba249eee6d9311347d429ee63c/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L618)):*
> ```Go
> 					externalLocks = append(externalLocks, *resumeSpan)
> 				}
> 				if !update.Key.Equal(update.EndKey) {
> ```

Why do we now have this branch? Why didn't we before?
___
*[`pkg/kv/kvserver/batcheval/cmd_end_transaction.go` line 642 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NJqCeZ87tlwXh8Yfcjw:-NJqCeZ87tlwXh8Yfcjx:brm8vq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b10bc5f50e6edeba249eee6d9311347d429ee63c/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L642)):*
> ```Go
> 	}
> 
> 	for ; i < len(args.LockSpans); i++ {
> ```

Can we replace this with `externalLocks = append(externalLocks, args.LockSpans[i:]...)`?
___
*[`pkg/kv/kvserver/batcheval/cmd_get.go` line 35 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/92267#-NJqEJUz3Aa0kKCR2wRJ:-NJqEJUz3Aa0kKCR2wRK:bdppgl8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d792e60b96da02eb5ee19f29f92c21343bd2ddd/pkg/kv/kvserver/batcheval/cmd_get.go#L35)):*
> ```Go
> 	reply := resp.(*roachpb.GetResponse)
> 
> 	if h.MaxSpanRequestKeys < 0 || h.TargetBytes < 0 {
> ```

This seems like a reasonable change, but let's pull it out into a separate commit and a separate PR.

**Comment by nvanbenschoten** [comment]
@KaiSun314 do we want to keep this PR open, or is the plan to merge everything it contains through smaller PRs?

**Comment by KaiSun314** [comment]
Sorry about that, forgot to close this PR. The plan is to merge everything it contains through smaller PRs.

https://github.com/cockroachdb/cockroach/pull/92268: Integrating byte pagination into the IntentResolver / RequestBatcher (asynchronous intent resolution)
https://github.com/cockroachdb/cockroach/pull/94939: Synchronous intent resolution refactoring (pushing into MVCC layer)
https://github.com/cockroachdb/cockroach/pull/95141: Adding byte pagination for synchronous intent resolution

**Pull request closed without merging**
