### PR TITLE
testserver: do not verify enterprise license

### LINKED ISSUE #104500: testserver: racy access to `DisableDefaultTestTenant`
**Describe the problem**

This code in `(ts *TestServer) maybeStartDefaultTestTenant`:
```go
  if err := base.CheckEnterpriseEnabled(ts.st, clusterID(), "SQL servers"); err != nil {
    ts.cfg.DisableDefaultTestTenant = true   // <- HERE
    return nil
  }
```

possibly races with the following code in `(s *Server) makeSharedProcessTenantConfig`:

```go
  parentCfg := s.cfg   // <- HERE
```

The race is triggered when the following conditions hold simultaneously:

- `ccl.TestingEnableEnterprise()` has not been called
- a test server is started via `serverutils.StartServer`
- concurrently, the test makes the server controller internally start a tenant server (eg as side effect of `alter tenant start service shared`)

These conditions are rather unlikely and currently only happen in `configprofiles.TestDataDriven` (this is the root cause of test failures #102800 and #102408.)

**Expected behavior**

I don't think it's safe/reasonable for the code in `(ts *TestServer) maybeStartDefaultTestTenant` to _write_ to its `ts.cfg`. 

I also don't think it's even necessary for this logic.

Jira issue: CRDB-28566
Epic: CRDB-18499

### LINKED ISSUE #108761: testutils: do not require CCL import or enterprise license to test with secondary tenants
(Discussed with @yuzefovich)

Prior to this patch, for test tenant servers to be automatically used two conditions needed to hold:

- the CCL package(s) needed to be imported.
- an enterprise license needed to be set (usually via `ccl.TestingEnableEnterprise()`)

While we want these conditions to hold to start separate-process SQL servers in production, they do not need to be verified in unit tests. Also ever since #98203 was merged, the CCL import is not necessary at all.

Epic: CRDB-18499

Jira issue: CRDB-30626

### PR DESCRIPTION
**Pull request by knz**
Prior to this patch, for test tenant servers to be automatically used
two conditions needed to hold:

- the CCL package(s) needed to be imported.
- an enterprise license needed to be set (usually via `ccl.TestingEnableEnterprise()`)

While we want these conditions to hold to start separate-process SQL
servers in production, they do not need to be verified in unit tests.

NB: as a result of merging this PR, a lot of (recently introduced)
calls to `ccl.TestingEnableEnterprise()` in various `main_test.go`
files are now unnecessary. Cleaning them up can be pushed to a later
phase.

Release note: None

Epic: CRDB-18499
Fixes #104500.
Fixes #108761.
Informs #76378

### CODE REVIEW

**Review by stevendanna — COMMENTED** [review]
Will be interesting to see what CI says about this!

**Comment by knz** [comment]
It's bad but not catastrophic.
Here's what it says:
image

**Comment by knz** [comment]
I have added the list to the issue #76378.

**Comment by yuzefovich** [comment]
Just wanted to point out that the actual number of tests that require fixing is larger than what the screenshot shows. This is because some of the failures result in crashes, so the whole package counts as a single failure (although there might be more lurking).

**Comment by knz** [comment]
yes, that is true, but at least the list of packages is complete (and it was longer than in the screenshot, the screenshot was taken when the CI run wasn't complete yet)

**Comment by yuzefovich** [comment]
@knz I added three commits to this PR, two of them are extracted into #109386 and can be merged separately, the last commit depends on the package-wide skip. I think I looked over everything in `pkg/sql/...`.

**Pull request merged**
