### PR TITLE
kv: send TxnCoordMeta from Root to Leaf transactions

### PR DESCRIPTION
**Pull request by nvb**
This change adjusts the handling of TxnCoordMeta so that it is sent both from Leaf to Root TxnCoordSenders and from Root to Leaf TxnCoordSenders. This is important for cases where a Root txn needs to pass extra information to Leaf nodes in DistSQL flows.

This will be important for transactional pipelining because it will allow Root coordinators to inform Leaf coordinators of all in-flight writes.

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
@RaduBerinde Andrei's out for at least the next week and this is a blocker for #26599. Do you mind if I assign you for the review?

**Comment by RaduBerinde** [comment]
🐶 but I'll do my best

**Review by RaduBerinde — APPROVED** [review]
:lgtm: just some minor comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27066#-:-LHDxAqc85zCWlY3sqay:b-zfyzg8)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/internal/client/sender.go, line 90 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27066#-LHDtb3Y8Q3ca023QmA_:-LHDtb3Y8Q3ca023QmAa:bykzdfk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3b017cc85dd5161cd566bfb4d3e3f567c63354d/pkg/internal/client/sender.go#L90)):*
> ```Go
> 	// child "leaf" nodes in a tree of transaction objects, as is created during a
> 	// DistSQL flow.
> 	// meta is the TxnCoordMeta which contains the transaction whose requests
> ```

nit: coordMeta
___
*[pkg/internal/client/txn.go, line 173 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27066#-LHDv5wx8G2t2EtruO3w:-LHDv5wx8G2t2EtruO3x:b1dhq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3b017cc85dd5161cd566bfb4d3e3f567c63354d/pkg/internal/client/txn.go#L173)):*
> ```Go
> 	db *DB, gatewayNodeID roachpb.NodeID, typ TxnType, proto roachpb.Transaction,
> ) *Txn {
> 	meta := roachpb.TxnCoordMeta{Txn: proto, DeprecatedRefreshValid: true}
> ```

[nit] Consider putting this into a `MakeTxnCoordMeta(txn)` function (if nothing else, to minimize the "surface" of the deprecated flag).

Also, given that we always initialize `Txn`, I'm not convinced of the usefulness of the new "inverted" flag.. This code will be a tad cleaner when we remove the deprecated flag, but it's a pretty minor difference.
___
*[pkg/kv/txn_interceptor_intent_collector.go, line 136 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27066#-LHDvOq72UVcKVhLDV49:-LHDvOq72UVcKVhLDV4A:b-flf1uz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3b017cc85dd5161cd566bfb4d3e3f567c63354d/pkg/kv/txn_interceptor_intent_collector.go#L136)):*
> ```Go
> 	// Do not modify existing intent slices when copying.
> 	ic.intents, _ = roachpb.MergeSpans(
> 		append(append([]roachpb.Span(nil), ic.intents...), meta.Intents...),
> ```

not this change but this should use `make` and `copy` so it doesn't allocate twice
___
*[pkg/sql/distsql_running.go, line 169 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27066#-LHDvnzBABsh8TWuuwyB:-LHDvnzBABsh8TWuuwyC:ba7o82b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3b017cc85dd5161cd566bfb4d3e3f567c63354d/pkg/sql/distsql_running.go#L169)):*
> ```Go
> 	// TODO(nvanbenschoten): remove in 2.2.
> 	if !dsp.st.Version.IsActive(cluster.VersionTxnCoordMetaInvalidField) {
> 		setupReq.DeprecatedTxn = &txnCoordMeta.Txn
> ```

Just from looking at the code, it looks like `txnCoordMeta` could be `nil` here?

Also, maybe we only want to set `TxnCoordMeta` in an `else` case here so they're not both sent unnecessarily

**Review by nvb — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27066#-:-LHF-qrP2GOarJSfuHya:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/internal/client/sender.go, line 90 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27066#-LHDtb3Y8Q3ca023QmA_:-LHEp9ECBqlNPIhyJkJl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3b017cc85dd5161cd566bfb4d3e3f567c63354d/pkg/internal/client/sender.go#L90)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

nit: coordMeta
</blockquote></details>

Done.
___
*[pkg/internal/client/txn.go, line 173 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27066#-LHDv5wx8G2t2EtruO3w:-LHEyYlm1j5HDKhxDrXc:bgmwlsd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3b017cc85dd5161cd566bfb4d3e3f567c63354d/pkg/internal/client/txn.go#L173)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Consider putting this into a `MakeTxnCoordMeta(txn)` function (if nothing else, to minimize the "surface" of the deprecated flag).

Also, given that we always initialize `Txn`, I'm not convinced of the usefulness of the new "inverted" flag.. This code will be a tad cleaner when we remove the deprecated flag, but it's a pretty minor difference.
</blockquote></details>

Done.

I'm going to keep the inversion though because it also helps clean up code in `txnSpanRefresher`.
___
*[pkg/kv/txn_interceptor_intent_collector.go, line 136 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27066#-LHDvOq72UVcKVhLDV49:-LHEpzV3Bmwf0pGJywPf:b-yh16l6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3b017cc85dd5161cd566bfb4d3e3f567c63354d/pkg/kv/txn_interceptor_intent_collector.go#L136)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

not this change but this should use `make` and `copy` so it doesn't allocate twice
</blockquote></details>

Done. Good call.
___
*[pkg/sql/distsql_running.go, line 169 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27066#-LHDvnzBABsh8TWuuwyB:-LHEqSLk-q9rYnopFvDq:b-o41r7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3b017cc85dd5161cd566bfb4d3e3f567c63354d/pkg/sql/distsql_running.go#L169)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Just from looking at the code, it looks like `txnCoordMeta` could be `nil` here?

Also, maybe we only want to set `TxnCoordMeta` in an `else` case here so they're not both sent unnecessarily
</blockquote></details>

Done for both.

**Review by RaduBerinde — APPROVED** [review]
> Reviewed 9 of 10 files at r1, 11 of 17 files at r2, 5 of 14 files at r3, 10 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27066)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27066)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/internal/client/txn.go, line 1211 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/27066#-LHIGM4q4Bqig7Pax14p:-LHIGM4q4Bqig7Pax14q:bj5ldc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ee86f0a1add572eed1c14616845460504c06da9/pkg/internal/client/txn.go#L1211)):*
> ```Go
> }
> 
> // GetStrippedTxnCoordMeta is like GetTxnCoordMeta, but it strips out all
> ```

Looking at this method that currently doesn't leave anything "unstripped" makes me think that maybe we'd be better of not sending a `TxnCoordMeta` from root to leaves, but a `Transaction` + inflight writes (or whatever is coming up for your future changes).
I forgot how I felt before; sorry if I flip-floped. How do you feel after making this change?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27066)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/internal/client/txn.go, line 1211 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/27066#-LHIGM4q4Bqig7Pax14p:-LHIHbaDECjUWB8TMn3T:b-enxl55) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ee86f0a1add572eed1c14616845460504c06da9/pkg/internal/client/txn.go#L1211)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Looking at this method that currently doesn't leave anything "unstripped" makes me think that maybe we'd be better of not sending a `TxnCoordMeta` from root to leaves, but a `Transaction` + inflight writes (or whatever is coming up for your future changes).
I forgot how I felt before; sorry if I flip-floped. How do you feel after making this change?
</blockquote></details>

Btw, it also seems to me that `TxnCoordMeta` has been defined as a proto mostly by accident. This is the change that's enshrining that into law.

**Pull request merged**
