### PR TITLE
tracing: add automatic background tracer snapshot support

### LINKED ISSUE #98299: tracing: allow nodes to take automatic trace snapshots
Add a cluster setting that if set to a positive duration, will cause the tracer to automatically capture a tracer snapshot at the configured frequency. Automatic snapshots should be stored in a separate ring buffer from manually captured snapshots so that they do not evict manual snapshots. Capturing automatic snapshots will give us a way to trace interesting events over a time interval without human intervention. These can be consumed after-the-fact to investigate stalled queries or jobs.

Epic: CRDB-8964

Jira issue: CRDB-25178

### PR DESCRIPTION
**Pull request by dt**
This adds the setting trace.snapshot.rate. If set to a positive duration, this will cause the tracer to automatically capture a tracer snapshot at the configured frequency.

Automatic snapshots are stored in a separate ring buffer from manually captured snapshots so that they do not evict manual snapshots. They are exposed in the API with negative snapshot IDs to distinguish them from manual snapshots.

By default these automatic snapshots are not enabled at this time until the overhead of enabling them is better understood.
Screenshot 2023-03-01 at 9 06 57 PM

Fixes: #98299

Release note: none.
Epic: none.

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 2 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97829)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @andreimatei, and @dt)

___
*[`pkg/util/tracing/tracer_snapshots.go` line 167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97829#-NPrpkCw5KIzY5xFD9hS:-NPrpkCw5KIzY5xFD9hT:b-6b3p1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fc19101f343e4440ea85bf7c03c954e5f70e25a/pkg/util/tracing/tracer_snapshots.go#L167)):*
> ```Go
> 		s := autoSnapshots.Get(i)
> 		res[i] = SnapshotInfo{
> 			ID:         s.ID * -1,
> ```

I'd like to avoid the proliferation of `* -1` throughout the code. Feels error-prone and confusing. Can we add an `Automatic bool` to the `snapshotWithID` struct?

If we insist on keeping the negative IDs for now, ideally we just set it in one place inside the `adminServer` RPC handlers.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97829)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dhartunian, and @dt)

___
*[`pkg/util/tracing/tracer_snapshots.go` line 167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97829#-NPrpkCw5KIzY5xFD9hS:-NPrslH65jd4Fw8aTbTZ:brgaov6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fc19101f343e4440ea85bf7c03c954e5f70e25a/pkg/util/tracing/tracer_snapshots.go#L167)):*
Resuming the conversation from https://reviewable.io/reviews/cockroachdb/cockroach/97895#-NPYz_J5EI3PrgznscQH - I was also confused about who deals with negative IDs. 

> I'm almost tempted to just make "ID" captured-at nanos instead of a separate field, and have Get() do a linear search of both rings for a match, but figured someone wouldn't like that, and just went with this (under commented but I think not to complicated) scheme?

We could use the clock, although it is nice to deal with small IDs when these automatic snapshots are not enabled.
How about we make the ID negative for automatic snapshots when the ID is allocated, and keep the ID negative in the respective ring buffer, so that nobody needs to convert from positive to negative?
___
*[`pkg/util/tracing/tracer_snapshots.go` line 243 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97829#-NPrvA6z8YVmjAm8Pt-7:-NPrvA6z8YVmjAm8Pt-8:b-9tocnd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fc19101f343e4440ea85bf7c03c954e5f70e25a/pkg/util/tracing/tracer_snapshots.go#L243)):*
> ```Go
> 		t.autoSnapRateChange = make(chan struct{}, 1)
> 	} else if !buildutil.CrdbTestBuild {
> 		panic("this tracer already started periodic snapshots")
> ```

Continuing from https://reviewable.io/reviews/cockroachdb/cockroach/97895#-NPYxTad6lAbFjqHtVBA
Now that I see that this is only for production, I like the assertion even less :P
It's not all that clear to me what the test that mucks with this channel is really testing. I think a test that sets the setting to 1ms and then checks that there's a snapshot soon after, and then sets the setting off and verifies that there's no new snapshots after 5ms would be sufficient, and then this channel can be internal to this function and not a struct field.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97829)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @andreimatei, and @dhartunian)

___
*[`pkg/util/tracing/tracer_snapshots.go` line 167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97829#-NPrpkCw5KIzY5xFD9hS:-NPu5bR7AGaasjYGONUM:b-t3gl1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fc19101f343e4440ea85bf7c03c954e5f70e25a/pkg/util/tracing/tracer_snapshots.go#L167)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Resuming the conversation from https://reviewable.io/reviews/cockroachdb/cockroach/97895#-NPYz_J5EI3PrgznscQH - I was also confused about who deals with negative IDs. 

> I'm almost tempted to just make "ID" captured-at nanos instead of a separate field, and have Get() do a linear search of both rings for a match, but figured someone wouldn't like that, and just went with this (under commented but I think not to complicated) scheme?

We could use the clock, although it is nice to deal with small IDs when these automatic snapshots are not enabled.
How about we make the ID negative for automatic snapshots when the ID is allocated, and keep the ID negative in the respective ring buffer, so that nobody needs to convert from positive to negative?
</blockquote></details>

I gave @dhartunian's suggestion a try: Wholly separate APIs on tracer for getting and listing manual vs automatic snapshots, each of which speak only in terms of positive int IDs. Only in the admin server endpoints do I do any ID sign flip, in just the two spots: when adding the automatic snaps to the list result and when deciding which api to call to get a given ID. I think I like this better, WDYT?
___
*[`pkg/util/tracing/tracer_snapshots.go` line 243 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97829#-NPrvA6z8YVmjAm8Pt-7:-NPu5LpG--1wB9IdYb1u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fc19101f343e4440ea85bf7c03c954e5f70e25a/pkg/util/tracing/tracer_snapshots.go#L243)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Continuing from https://reviewable.io/reviews/cockroachdb/cockroach/97895#-NPYxTad6lAbFjqHtVBA
Now that I see that this is only for production, I like the assertion even less :P
It's not all that clear to me what the test that mucks with this channel is really testing. I think a test that sets the setting to 1ms and then checks that there's a snapshot soon after, and then sets the setting off and verifies that there's no new snapshots after 5ms would be sufficient, and then this channel can be internal to this function and not a struct field.
</blockquote></details>

Done.

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97829#-:-NPx0MOWB4RqojQjVWmM:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @dhartunian, and @dt)

___
*[`pkg/server/admin.go` line 4106 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97829#-NPx09PW4hX2sMNaWoff:-NPx09PW4hX2sMNaWofg:b-pdfrr7) ([raw file](https://github.com/cockroachdb/cockroach/blob/876c804ae7349202bef700133c39f3f5af7a3b62/pkg/server/admin.go#L4106)):*
> ```Go
> 		si := autoSnapshotInfo[i]
> 		snapshots = append(snapshots, &serverpb.SnapshotInfo{
> 			SnapshotID: int64(si.ID * -1),
> ```

consider highlighting the negative ID here with a comment
___
*[`pkg/server/admin.go` line 4172 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97829#-NPx-mLKCPkSp-PNZy9N:-NPx-mLL0VL5itFC6YLh:b4z0f2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/876c804ae7349202bef700133c39f3f5af7a3b62/pkg/server/admin.go#L4172)):*
> ```Go
> 	}
> 
> 	id := tracing.SnapshotID(req.SnapshotId)
> ```

Please put a comment on `req.SnapshotId` explaining the deal with negative IDs. And if you're there, give is a `customname` of `SnapshotID`.
___
*[`pkg/util/tracing/tracer_snapshots.go` line 167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97829#-NPrpkCw5KIzY5xFD9hS:-NPx0FAjEw8yQOUHSyzT:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fc19101f343e4440ea85bf7c03c954e5f70e25a/pkg/util/tracing/tracer_snapshots.go#L167)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I gave @dhartunian's suggestion a try: Wholly separate APIs on tracer for getting and listing manual vs automatic snapshots, each of which speak only in terms of positive int IDs. Only in the admin server endpoints do I do any ID sign flip, in just the two spots: when adding the automatic snaps to the list result and when deciding which api to call to get a given ID. I think I like this better, WDYT?
</blockquote></details>

:thumbsup:

**Review by dt — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97829#-:-NPyQ8vUEchP2eprGvMY:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @andreimatei, and @dhartunian)

___
*[`pkg/server/admin.go` line 4106 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97829#-NPx09PW4hX2sMNaWoff:-NPxye-sCoBHeRzCivjd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/876c804ae7349202bef700133c39f3f5af7a3b62/pkg/server/admin.go#L4106)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

consider highlighting the negative ID here with a comment
</blockquote></details>

Done.
___
*[`pkg/server/admin.go` line 4172 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97829#-NPx-mLKCPkSp-PNZy9N:-NPyPTsAEb6gkquU0bjU:bvjlcps) ([raw file](https://github.com/cockroachdb/cockroach/blob/876c804ae7349202bef700133c39f3f5af7a3b62/pkg/server/admin.go#L4172)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Please put a comment on `req.SnapshotId` explaining the deal with negative IDs. And if you're there, give is a `customname` of `SnapshotID`.
</blockquote></details>

Done (the comment, but`customname`is not happening with grpc-gateway. I tried and poked around a bit but couldn't get it to work and has exceed my "while I'm here" appetite)
___
*[`pkg/util/tracing/tracer_snapshots.go` line 167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97829#-NPrpkCw5KIzY5xFD9hS:-NPyPzKtDkl5QHiKy4-k:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fc19101f343e4440ea85bf7c03c954e5f70e25a/pkg/util/tracing/tracer_snapshots.go#L167)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

:thumbsup: 
</blockquote></details>

Done.

**Comment by dt** [comment]
blathers backport 22.2

**Pull request merged**
