### PR TITLE
kvserver: prevent the StoreRebalancer from downreplicating a range

### LINKED ISSUE #64064: kvserver: unxpected replication change from 3 to 2 voters
**Describe the problem**

When @aliher1911 and I looked into unhappy restore2TB runs in the context of https://github.com/cockroachdb/cockroach/issues/61396, we noticed unexpected replication changes. From a three-voter configuration, for some reason we're demoting a voter:

> [n7,s7,r39158/4:x] change replicas (add ‹[]› remove ‹[(n5,s5):1VOTER_DEMOTING_LEARNER]›): existing descriptor r39158:‹/Table/54/1/52061454{-/0}› [(n5,s5):1, (n7,s7):4, (n10,s10):3, next=5, gen=744, sticky=1617706884.328040814,0]

At that point, in the [full snippet](https://gist.github.com/aliher1911/2c421e67d9519d5c83abd62cb2ef6ced), the range goes unavailable because one of the two remaining voters (s10) is waiting for a snapshot.

**To Reproduce**

Run the `restore2TB/nodes=10` roachtest.

This *should* reproduce on any SHA preceding #64060, such as
d85d49dd00a3485aed74b0160e408a4e325f6fae, when running restore2TB.
It may not always happen but we saw it frequently, at least in
"unhappy" runs (as characterized by large pending snapshot counts).

**Expected behavior**

With 10 live nodes and atomic replication changes, there should never be a
reason to move from a three-voter to a two-voter configuration.o The only
explanation I have is that n5 might have been considered dead for 5 minutes
which would possibly trigger this issue (?!) but this is esssentially ruled out
by the full snippet, which indicates that n5 was live a minute after the
botched replication change (and it is thus unlikely to have been non-live for
the preceding minutes).

@aliher1911 if you have full logs from any of these experiments, mind going
through them to see if you have other examples of such replication changes,
and if so, posting the complete log directory (Google Drive).

**Additional data / screenshots**

**Environment:**

**Additional context**

cc @cockroachdb/kv

### PR DESCRIPTION
**Pull request by aayushshah15**
This PR contains 2 commits:

**kvserver: add safeguard against spurious calls to AdminRelocateRange**

This commit adds checks inside of `AdminRelocateRange` to fail if the
lists of relocation targets passed in by the caller contain duplicates.
This is supposed to act as a safeguard against catastrophic outcomes
like a range getting spuriously downreplicated due to malformed input.

Release note: None

**kvserver: prevent the StoreRebalancer from downreplicating a range**

Prior to this commit, we had a bug inside one of the methods used by the
`StoreRebalancer` where we had two variables referring to a slice that
was subsequently being appended to.

The code was making the implicit assumption that both of these slices
would point to the same underlying array, which is not true since any of
the additions mentioned above could result in the underlying array for
one of the slices being resized.

This commit fixes this bug.

Resolves #64064

Release note (bug fix): A bug in previous 21.1 betas allowed the store
rebalancer to spuriously downreplicate a range during normal operation.
This bug is now fixed.

### CODE REVIEW

**Comment by aayushshah15** [comment]
I'm trying to figure out if I can write a sort of randomized test for the store rebalancer, but so far I've had a hard time thinking of anything that wouldn't be super invasive. If I cannot cleanly add a randomized test, I will add a more targeted unit test. 

The PR should be ready for a look aside from this.

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64170)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[pkg/kv/kvserver/replica_command.go, line 3115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64170#-MZBur7ODwHorMgw_BG6:-MZBur7ODwHorMgw_BG7:b6yrewi) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e7649c155899942d48ce7ce9cbe2f8babc08aac/pkg/kv/kvserver/replica_command.go#L3115)):*
> ```Go
> 	for i := range targets {
> 		for j := i + 1; j < len(targets); j++ {
> 			if targets[i].StoreID == targets[j].StoreID && targets[i].NodeID == targets[j].NodeID {
> ```

Isn't this just `targets[i] == targets[j]`?
___
*[pkg/kv/kvserver/store_rebalancer.go, line 756 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64170#-MZBwZiH-8ZucgGd_MZF:-MZBwZiH-8ZucgGd_MZG:brg48wf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aaccf73c9abc4bc5457ff2d4b8be8847d2e05c3/pkg/kv/kvserver/store_rebalancer.go#L756)):*
> ```Go
> 	targetType targetReplicaType,
> ) []roachpb.ReplicaDescriptor {
> 	var finalTargetsForType *[]roachpb.ReplicaDescriptor
> ```

Give this a comment that mentions why we need the indirection. It wasn't immediately clear to me that the idea was for the call to `allocateTargetFromList` in the loop down below to observe the `append` call below.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64170)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_command.go, line 3115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64170#-MZBur7ODwHorMgw_BG6:-MZFCUTAD3ujC5JKUI9b:bmt12uf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e7649c155899942d48ce7ce9cbe2f8babc08aac/pkg/kv/kvserver/replica_command.go#L3115)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Isn't this just `targets[i] == targets[j]`?
</blockquote></details>

Fixed, didn't realize I was just comparing `ReplicationTarget`s and not `ReplicaDescriptor`s
___
*[pkg/kv/kvserver/store_rebalancer.go, line 756 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64170#-MZBwZiH-8ZucgGd_MZF:-MZFCc4QEly6c1WC8WOO:b-jhqtbp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aaccf73c9abc4bc5457ff2d4b8be8847d2e05c3/pkg/kv/kvserver/store_rebalancer.go#L756)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Give this a comment that mentions why we need the indirection. It wasn't immediately clear to me that the idea was for the call to `allocateTargetFromList` in the loop down below to observe the `append` call below.
</blockquote></details>

Done, lmk if you think it is lacking.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64170#-:-MZFLqhp6bd3WT3c-Kx3:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/store_rebalancer.go, line 756 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64170#-MZBwZiH-8ZucgGd_MZF:-MZFLcnr4Q0EkYJISBqp:ba501ic) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aaccf73c9abc4bc5457ff2d4b8be8847d2e05c3/pkg/kv/kvserver/store_rebalancer.go#L756)):*
> ```
> we want the result of subsequent calls
> ```

Isn't this "we want subsequent calls"?

Also, let's explicitly mention the append when we say "the result of previous calls", because `allocateTargetFromList` isn't what mutates the slice, it's the call to `append` below it.

**Review by aayushshah15 — COMMENTED** [review]
TFTR

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64170#-:-MZGWD3X4eMOacrej20D:b-4as1hm)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/store_rebalancer.go, line 756 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64170#-MZBwZiH-8ZucgGd_MZF:-MZGWW_G8w2fz0jDFeXa:b-2io8ve) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aaccf73c9abc4bc5457ff2d4b8be8847d2e05c3/pkg/kv/kvserver/store_rebalancer.go#L756)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> we want the result of subsequent calls
> ```

Isn't this "we want subsequent calls"?

Also, let's explicitly mention the append when we say "the result of previous calls", because `allocateTargetFromList` isn't what mutates the slice, it's the call to `append` below it.
</blockquote></details>

argh thanks for catching that. fixed and done.

**Pull request merged**
