### PR TITLE
stats: add a histogram version number

### PR DESCRIPTION
**Pull request by rytaft**
This commit adds a histogram version number to the `HistogramData`
proto. This will allow us to identify what logic was used to construct
a particular histogram and possibly debug future issues.

Release note: None

Release justification: Low risk, high benefit change to existing
functionality.

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69944#-:-MjAIncOE1guExtrdSwr:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/stats/histogram.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69944#-MjAHoMpCElykguHyHko:-MjAHoMpCElykguHyHkp:bufucq) ([raw file](https://github.com/cockroachdb/cockroach/blob/466b854a8d6815e5c300bc5a693d50d6b722c2fc/pkg/sql/stats/histogram.go#L39)):*
> ```Go
> // ATTENTION: When updating this field, add a brief description of what
> // changed to the version history below.
> const HistVersion HistogramVersion = 1
> ```

Does this need to be exported?
___
*[pkg/sql/stats/histogram.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69944#-MjAHK6500yr3gXHLZqO:-MjAHK66DcvHGuVRHWuN:bdiprmj) ([raw file](https://github.com/cockroachdb/cockroach/blob/466b854a8d6815e5c300bc5a693d50d6b722c2fc/pkg/sql/stats/histogram.go#L52)):*
> ```Go
> 
> - Version: 0
> - Initial histogram implementation.
> ```

Should we note here that Version 0 histograms won't have a version field?

**Review by rytaft — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69944#-:-MjBJBhF91Wpp5Gn94pF:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/stats/histogram.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69944#-MjAHoMpCElykguHyHko:-MjBIjwE6rvbb_cmKbVn:b-6i1ca6) ([raw file](https://github.com/cockroachdb/cockroach/blob/466b854a8d6815e5c300bc5a693d50d6b722c2fc/pkg/sql/stats/histogram.go#L39)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Does this need to be exported?
</blockquote></details>

Nope! Done.
___
*[pkg/sql/stats/histogram.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69944#-MjAHK6500yr3gXHLZqO:-MjBJ8aQ2M0_ZcfrLeZr:bs7wumb) ([raw file](https://github.com/cockroachdb/cockroach/blob/466b854a8d6815e5c300bc5a693d50d6b722c2fc/pkg/sql/stats/histogram.go#L52)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Should we note here that Version 0 histograms won't have a version field?
</blockquote></details>

Done.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69944)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/stats/histogram.go, line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69944#-MjBW4aC95if37tUZkji:-MjBW4aD4yslPwFNZ1Xx:b5hkip2) ([raw file](https://github.com/cockroachdb/cockroach/blob/78191f277aa4020cf14f0090ba53a2a9fb5367ca/pkg/sql/stats/histogram.go#L54)):*
> ```Go
> 
> - Version: 0
> - Initial histogram implementation. The version field is omitted on Version 0
> ```

[nit] I would say histogram implementations up to and including 21.1.x.

**Review by rytaft — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69944#-:-MjCYgex0eAUlU6oSypw:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[pkg/sql/stats/histogram.go, line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69944#-MjBW4aC95if37tUZkji:-MjCYbVK6xvlg-kmgs6U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78191f277aa4020cf14f0090ba53a2a9fb5367ca/pkg/sql/stats/histogram.go#L54)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I would say histogram implementations up to and including 21.1.x.
</blockquote></details>

Done.

**Pull request merged**
