### PR TITLE
security: add a cache to store client cert expirations for users

### LINKED ISSUE #100699: Surface a metric to enable users to alert on when a client's cert age is close to expiring
This issue tracks adding a metric that allows users to alert when client's cert age is close to expiring. 

Per Sean-

Hypothetically, a server-side VerifyConnection function such as https://pkg.go.dev/crypto/tls#example-Config-VerifyConnection will allow us to poke at the [peer's ConnectionState](https://pkg.go.dev/crypto/tls#ConnectionState), which has the [NotAfter](https://pkg.go.dev/crypto/x509#Certificate) attribute, and we can use time.Now().Sub(crt.NotAfter) to emit an aggregate time.Duration that can be polled via a prom endpoint that customers can alert on now that this information has been exposed._

Related issue: https://github.com/cockroachdb/cockroach/issues/99422

Jira issue: CRDB-26585

### PR DESCRIPTION
**Pull request by cameronnunez**
Fixes https://github.com/cockroachdb/cockroach/issues/100699.

This change introduces a new node-level, FIFO cache for storing the minimum time-until-expiration of the set of client certs seen (per user). 

Entries in the cache are username-gauge pairs, where the gauges contain the expiration values. Periodically, gauges with 
expiration values that are not in the future will be cleared from the cache. The purging process triggers hourly. 

The gauges in the cache are children of an aggregate gauge `ClientExpiration`, so the aggregated value for that metric 
is not meaningful and only serves as a link to the children. `ClientExpiration` (`security.certificate.expiration.client`)
is exported as a metric and the children gauges are labeled by SQL user.

Release note (security update): There is a new `server.client_cert_expiration_cache.capacity` setting which, when set to a non-zero number, makes it so that the minimum time-until-expiration of the set of client certificates seen is stored (for every user). This setting can be used to ensure client cert expirations are exported as a metric (if set to zero, the metric `security.certificate.expiration.client` will have a value of zero).

### CODE REVIEW

**Review by knz — COMMENTED** [review]
One thing that stands out to me here is that if say, a cert expires on Jan 10, then a new cert is issued with a new expiry on March 10, and no other cert is ever used (i.e. capacity is never exceeded) the crdb cluster will retain  Jan 10 as the minimum value.

This is undesirable UX - after the expiry date of a cert has been reached in real time (or shortly afterwards), we should not keep it in the gauge any more and instead report all the certs with an expiry in the _future_ in the metric.

> Reviewed 8 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103592#-:-NVoKVeF5jMSKwB9yszi:b-kx7x4k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez)

___
*[`pkg/security/cert_expiry_cache.go` line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103592#-NVoJlMZ-G3lDtS8kY0E:-NVoJlMZ-G3lDtS8kY0F:bjmxqb0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9aeb6751430c2aa3999ad51ea3691d2e13aadd2/pkg/security/cert_expiry_cache.go#L110)):*
> ```Go
> 		gauge.Update(newExpiry)
> 		c.mu.cache.Add(key, gauge)
> 		if err := c.mu.acc.Grow(ctx, int64(unsafe.Sizeof(*gauge))); err != nil {
> ```

the purpose of Grow is to verify that the allocation is possible _before_ it is effectively performed. This call should be pulled up to before the call to `parentGauge.AddChild`.

**Review by sean- — COMMENTED** [review]
I share @knz's concern.

Instead of caching just the expiration value of the cert, can we cache a struct that has the value and a per-entry TTL?  I dry-coded a hypothetical below for consideration.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103592#-:-NW9lZlz2mRgu9IG2MJq:b8m0u5m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez and @knz)

___
*[`pkg/security/cert_expiry_cache.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103592#-NW9jAck0eez1sL1L32T:-NW9jAcl1oUzTO1UGDh7:b-b6sfoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9aeb6751430c2aa3999ad51ea3691d2e13aadd2/pkg/security/cert_expiry_cache.go#L27)):*
> ```Go
> 
> // TODO(cameron): best to update this after understanding performance more
> const CacheCapacityMax = 1500
> ```

```
const CacheEntryTTL time.Duration = 8 * time.Hour
```
___
*[`pkg/security/cert_expiry_cache.go` line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103592#-NW9gW0y35megbIAQOBP:-NW9gW0y35megbIAQOBQ:bb9kj7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9aeb6751430c2aa3999ad51ea3691d2e13aadd2/pkg/security/cert_expiry_cache.go#L91)):*
> ```Go
> 	if !ok {
> 		return 0, ok
> 	}
> ```

```
type ExpirableTTL stuct {
  CertTTL int64 // seconds until this cert expires
  ValueTTL int64 // seconds until this cached entry expires
}

// in Get(), add a check so that on-access we expire the cached values in advance of the FIFO queue being exhausted
if time.Now().After(time.Unix(value.CertTTL, 0)) {
  c.mu.cache.Del(key)
  return 0, false
}
```

Many environments will only have half-a-dozen entries in this cache.
___
*[`pkg/security/cert_expiry_cache.go` line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103592#-NW9jbDb2D8yB_2duA4D:-NW9jbDb2D8yB_2duA4E:b-ohy5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9aeb6751430c2aa3999ad51ea3691d2e13aadd2/pkg/security/cert_expiry_cache.go#L109)):*
> ```Go
> 		gauge := parentGauge.AddChild(key)
> 		gauge.Update(newExpiry)
> 		c.mu.cache.Add(key, gauge)
> ```

```
expiringGauge := ExpirableTTL{
  CertTTL: time.Now().Add(CacheEntryTTL).Unix(),
  ValueTTL: gauge,
}
c.mu.cache.Add(key, expiringGauge)
```
___
*[`pkg/security/cert_expiry_cache.go` line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103592#-NW9kD95A760UzkalNaq:-NW9kD95A760UzkalNar:bsg4976) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9aeb6751430c2aa3999ad51ea3691d2e13aadd2/pkg/security/cert_expiry_cache.go#L115)):*
> ```Go
> 	} else {
> 		if gauge := value.(*aggmetric.Gauge); newExpiry < gauge.Value() || gauge.Value() == 0 {
> 			gauge.Update(newExpiry)
> ```

This also needs to be updated to have an `ExpirableTTL` value that matches the convention in `Get()` above.

**Review by cameronnunez — COMMENTED** [review]
I have opted for an approach that involves periodically cleaning up the cache. This approach also avoids any ambiguity surrounding the use of the term "expiration", but let me know if there is a preference for the approach Sean has pitched 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103592#-:-NWDan3_3q8rxDJigp19:b-psexl4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @sean-)

___
*[`pkg/security/cert_expiry_cache.go` line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103592#-NVoJlMZ-G3lDtS8kY0E:-NWDbOsgCLDIT7MjW-RA:b8gj3mz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9aeb6751430c2aa3999ad51ea3691d2e13aadd2/pkg/security/cert_expiry_cache.go#L110)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

the purpose of Grow is to verify that the allocation is possible _before_ it is effectively performed. This call should be pulled up to before the call to `parentGauge.AddChild`.
</blockquote></details>

Good catch, fixed.

**Review by sean- — APPROVED** [review]
I like your approach more; it's memory efficient and works since we're only talking about <1500 values atm (though I suspect it'll only be ~20 in the common case, and ~1k in the case of dyn usernames).

> Reviewed 1 of 12 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103592#-:-NWDl1SJ3GkuYuFQ5Rnm:b-kbye8v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/security/cert_expiry_cache.go` line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103592#-NWDlU9aEt3OhYJUM36a:-NWDlU9aEt3OhYJUM36b:b3raxp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8851caeb169b094a99cf1adc4c9cbf73fbfb6dcb/pkg/security/cert_expiry_cache.go#L31)):*
> ```Go
> 
> // TODO(cameron): best to update this after understanding performance more
> const CacheCapacityMax = 1500
> ```

Maybe just set this to something "obscenely" high, like 65K or 256K, but prevent it from being an unlimited value.  Argument: if someone has 65K certs, they should expect to spend a bit of RAM on this.  Environments that use dynamically generated TLS certs could, conceivably, use more than 1500 usernames in the normal course of operation.
___
*[`pkg/security/cert_expiry_cache.go` line 202 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103592#-NWDm8qv0gr86GzPpIT4:-NWDm8qv0gr86GzPpIT5:brkli4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/8851caeb169b094a99cf1adc4c9cbf73fbfb6dcb/pkg/security/cert_expiry_cache.go#L202)):*
> ```Go
> 			case <-ctx.Done():
> 				return
> 			}
> ```

Can we throw in a:

```
const expirationSmearing = 5 * time.Second
time.Sleep(time.Duration(int(expirationSmearing) / CacheCapacityMax))
```

to smear the expiration over a 5s period of time (i.e., sleep 5ms between expiring values)?

**Review by cameronnunez — COMMENTED** [review]
Updated the max capacity 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103592#-:-NWEteCd9rfJTUnnA4sP:bae5235)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/security/cert_expiry_cache.go` line 202 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103592#-NWDm8qv0gr86GzPpIT4:-NWEsvN53Ff4hQchgJpk:b-65aa7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/8851caeb169b094a99cf1adc4c9cbf73fbfb6dcb/pkg/security/cert_expiry_cache.go#L202)):*
<details><summary><i>Previously, sean- (Sean Chittenden) wrote…</i></summary><blockquote>

Can we throw in a:

```
const expirationSmearing = 5 * time.Second
time.Sleep(time.Duration(int(expirationSmearing) / CacheCapacityMax))
```

to smear the expiration over a 5s period of time (i.e., sleep 5ms between expiring values)?
</blockquote></details>

Did you mean that we should add that amount to the current period here (an hour)? The purging process is set to fire every hour (after an initial jittered duration)

**Review by knz — COMMENTED** [review]
LGTM with nits - but please update commit message + PR description with the new behavior.

> Reviewed 1 of 12 files at r1, 3 of 7 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103592#-:-NWh-ulU-T56DZ_E0j81:bk1o4xw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez)

___
*[`pkg/security/cert_expiry_cache.go` line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103592#-NW9gW0y35megbIAQOBP:-NWh-VAD8mp_FOjuAfXr:bcwmu60) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9aeb6751430c2aa3999ad51ea3691d2e13aadd2/pkg/security/cert_expiry_cache.go#L91)):*
<details><summary><i>Previously, sean- (Sean Chittenden) wrote…</i></summary><blockquote>

```
type ExpirableTTL stuct {
  CertTTL int64 // seconds until this cert expires
  ValueTTL int64 // seconds until this cached entry expires
}

// in Get(), add a check so that on-access we expire the cached values in advance of the FIFO queue being exhausted
if time.Now().After(time.Unix(value.CertTTL, 0)) {
  c.mu.cache.Del(key)
  return 0, false
}
```

Many environments will only have half-a-dozen entries in this cache.

</blockquote></details>

This change should be communicated in the commit message and the PR description as well.
___
*[`pkg/security/cert_expiry_cache.go` line 59 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103592#-NWh-J4lC8LUESQRC_zX:-NWh-J4lC8LUESQRC_zY:b9x3zlv) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6933ba91c8442dac7d2400a259f09a971cfe6f8/pkg/security/cert_expiry_cache.go#L59)):*
> ```Go
> }
> 
> func NewClientCertExpirationCache(
> ```

nit: exported functions should get a docstring.
___
*[`pkg/security/cert_expiry_cache.go` line 214 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103592#-NWh-kXx3QASBMwwMs2o:-NWh-kXx3QASBMwwMs2p:b-rjpj5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6933ba91c8442dac7d2400a259f09a971cfe6f8/pkg/security/cert_expiry_cache.go#L214)):*
> ```Go
> 	c.mu.cache.Do(func(entry *cache.Entry) {
> 		gauge := entry.Value.(*aggmetric.Gauge)
> 		if gauge.Value() <= c.timeNow() {
> ```

nit: compute `c.timeNow()` only once for the entire loop.

**Review by cameronnunez — COMMENTED** [review]
Updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103592#-:-NWhGW1_A7QZdkASeQHF:b-bw8e14)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/security/cert_expiry_cache.go` line 59 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103592#-NWh-J4lC8LUESQRC_zX:-NWhGgqUEzAy1lkw_cD6:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6933ba91c8442dac7d2400a259f09a971cfe6f8/pkg/security/cert_expiry_cache.go#L59)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: exported functions should get a docstring.
</blockquote></details>

Fixed.
___
*[`pkg/security/cert_expiry_cache.go` line 214 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103592#-NWh-kXx3QASBMwwMs2o:-NWhGjzlCTwpTOAj8FL6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6933ba91c8442dac7d2400a259f09a971cfe6f8/pkg/security/cert_expiry_cache.go#L214)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: compute `c.timeNow()` only once for the entire loop.
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103592)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez)

**Comment by cameronnunez** [comment]
TFTRs!

**Comment by cameronnunez** [comment]
bors r=sean-,knz

**Comment by cameronnunez** [comment]
bors r=sean-,knz

**Comment by cameronnunez** [comment]
blathers backport 22.2

**Pull request merged**
