### PR TITLE
acceptance: remove Farmer.Nodes()

### PR DESCRIPTION
**Pull request by vivekmenezes**
also remove dead code from Farmer.CollectLogs

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12315)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/acceptance/allocator_test.go, line 211 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12315#-KYsrMKKywVBGlMCeKvX:-KYsrMKLwikPJIcg-8Eg:bhp2dr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7fd875a7520f91ccb85df54d9d543589061c0fc/pkg/acceptance/allocator_test.go#L211)):*
> ```Go
> 
> func (at *allocatorTest) stdDev() (float64, error) {
> 	host := at.f.FirstInstance()
> ```

honestly, I would sooner remove `FirstInstance`; that function seems not to provide any value.

---

*[pkg/acceptance/terrafarm/farmer.go, line 167 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12315#-KYsrjBAEhjzQ2oeeOaQ:-KYsrjBAEhjzQ2oeeOaR:b50ioak) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7fd875a7520f91ccb85df54d9d543589061c0fc/pkg/acceptance/terrafarm/farmer.go#L167)):*
> ```Go
> 	}
> 	const src = "logs"
> 	for i, node := range f.nodes {
> ```

how come this is safe? I would imagine that you'd want to call `Hostname` below to ensure that initNodes was called.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12315)*

**Comment by tamird** [comment]
You should probably rename `initNodes` to `Nodes` in this change, which would simplify it quite a bit.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12315#-:-KYssX1pHPfpd8weEdqQ:b4yiaju)*

**Comment by vivekmenezes** [comment]
I've left initNodes as is because I don't want to have to export Nodes() 

---

Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/acceptance/allocator_test.go, line 211 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12315#-KYsrMKKywVBGlMCeKvX:-KYv67TBsMt0jvA2r51n:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7fd875a7520f91ccb85df54d9d543589061c0fc/pkg/acceptance/allocator_test.go#L211)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

honestly, I would sooner remove `FirstInstance`; that function seems not to provide any value.
</blockquote></details>

Done.

---

*[pkg/acceptance/terrafarm/farmer.go, line 167 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12315#-KYsrjBAEhjzQ2oeeOaQ:-KYv6oma8_63IsuuUtn3:b-1ke6lc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7fd875a7520f91ccb85df54d9d543589061c0fc/pkg/acceptance/terrafarm/farmer.go#L167)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

how come this is safe? I would imagine that you'd want to call `Hostname` below to ensure that initNodes was called.
</blockquote></details>

It's not. CollectLogs is always called at the end which makes it so, but why risk that. Changed it to use initNodes()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12315#-:-KYv6zLglPuI2-9WuSXk:b-xfgvjv)*

**Comment by tamird** [comment]
OK. Perhaps you could give it a better name without exporting it, though.

:lgtm:

---

Reviewed 1 of 1 files at r3, 1 of 1 files at r4, 3 of 3 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12315#-:-KYzRNzMGmyS_-dhTt2D:b3p1u9e)*

**Comment by cuongdo** [comment]
:lgtm:

+1 on @tamird's comment though

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12315#-:-KZ-73EykzFDFfWbekx-:b-93a0ib)*

**Comment by vivekmenezes** [comment]
I'm suffering from a failure of imagination :-( so I've just removed initNodes

---

Review status: 1 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12315#-:-KZ28C7TK89yKSyNQ5u0:b-mbg8ji)*

**Comment by tamird** [comment]
:lgtm: :ship: 

---

Reviewed 3 of 3 files at r6, 1 of 1 files at r7, 3 of 3 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/acceptance/terrafarm/farmer.go, line 162 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/12315#-KZ2OggUuIqXGoXvAxPi:-KZ2OggUuIqXGoXvAxPj:b-5kfvgp) ([raw file](https://github.com/cockroachdb/cockroach/blob/379bccafb9a15871e6080474723ea68ce86cfdb4/pkg/acceptance/terrafarm/farmer.go#L162)):*
> ```Go
> 	const src = "logs"
> 	for i := 0; i < f.NumNodes(); i++ {
> 		if err := f.scp(f.nodes[i].hostname, f.defaultKeyFile(), src,
> ```

extract local and use `Hostname`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12315#-:-KZ2OjvMUYWewSyPjJcb:bxtc2j1)*

**Pull request merged**
