### PR TITLE
spanconfig: verify migration for rangefeed enablement

### PR DESCRIPTION
**Pull request by irfansharif**
\#74555 starts using the span configs infrastructure to control whether
rangefeeds are enabled over a given range. Before dynamic system table
IDs (#76003), we used the range's key boundaries to determine whether
the range in question was for a system table ID. In mixed-version
clusters, it's possible to have both forms of this check. To ensure
things work in this form (something we suspected in #76331), we add a
test.

NB: The reason things still work is because in #74555 we modified the
system config span to hard code the relevant config fields for constant
system table IDs -- behaving identically to previous version nodes.

Release note: None

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76466)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @irfansharif)

___
*[pkg/migration/migrations/migrate_span_configs_test.go, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76466#-Mvt2e2L2Aph9Hi8XyMj:-Mvt2e2L2Aph9Hi8XyMk:b-yhqa4o) ([raw file](https://github.com/cockroachdb/cockroach/blob/045d95523da5c49b0012a8f5b17ac9a66cc751f2/pkg/migration/migrations/migrate_span_configs_test.go#L73)):*
> ```Go
> 	noopCheckpointDuration := 100 * time.Millisecond
> 	sqlWatcher := spanconfigsqlwatcher.New(
> 		keys.SystemSQLCodec,
> ```

I think we should extend this test for a secondary tenant as well. When we last looked over this code briefly together, we weren't sure if things just worked for secondary tenants -- it would be nice to validate with a test.

**Comment by arulajmani** [comment]
@irfansharif friendly ping on this one, came up in the context of a GA blocker in todays meeting.

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76466)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @arulajmani)

___
*[pkg/migration/migrations/migrate_span_configs_test.go, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76466#-Mvt2e2L2Aph9Hi8XyMj:-MzLYqH_49ExNAYtm1Mu:b-titlg4) ([raw file](https://github.com/cockroachdb/cockroach/blob/045d95523da5c49b0012a8f5b17ac9a66cc751f2/pkg/migration/migrations/migrate_span_configs_test.go#L73)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I think we should extend this test for a secondary tenant as well. When we last looked over this code briefly together, we weren't sure if things just worked for secondary tenants -- it would be nice to validate with a test. 
</blockquote></details>

We can add a test for secondary tenants in a follow up PR -- the machinery under question here doesn't differ between tenants so I don't expect it to catch anything. Given this PR also squashes a real data race (I assume that's where the GA blocker discussion came up?), can I get a rubber stamp? Rebased.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76466)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @irfansharif)

___
*[pkg/migration/migrations/migrate_span_configs_test.go, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76466#-Mvt2e2L2Aph9Hi8XyMj:-MzLnrXYDkQ_79aPDVvT:b-wzesqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/045d95523da5c49b0012a8f5b17ac9a66cc751f2/pkg/migration/migrations/migrate_span_configs_test.go#L73)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

We can add a test for secondary tenants in a follow up PR -- the machinery under question here doesn't differ between tenants so I don't expect it to catch anything. Given this PR also squashes a real data race (I assume that's where the GA blocker discussion came up?), can I get a rubber stamp? Rebased.
</blockquote></details>

Considering the data-race is already in its own commit, you could always pull it out into its own PR if we want to address the GA blocker. 

I think there's real value in adding a tenant version of this test even if you don't expect it to catch anything. Mixed version states where tenants haven't been upgraded to use span configurations but the host has is an interesting case. I'd strongly encourage you to add this, or at least open an issue for it, lest it drop off our plate.

**Comment by irfansharif** [comment]
Added to https://github.com/cockroachdb/cockroach/issues/73874.

**Review by arulajmani — APPROVED** [review]

**Pull request merged**
