### PR TITLE
release: enable bincheck for tag pushes

### PR DESCRIPTION
**Pull request by rail**
Previously, in order to run `bincheck` as part of the release process,
we would need to follow hands-on instructions at
https://github.com/cockroachdb/bincheck/blob/master/README.md.

This process requires some time and error prone.

This patch enables GitHub actions on tag push events and automates the
task.

Release note: None

### CODE REVIEW

**Comment by rail** [comment]
https://github.com/rail/cockroach/actions/runs/1896886582 is an example run with hardcoded version and sha

**Review by jlinder — APPROVED** [review]
I like this as an incremental step to remove the manual run step. Looking forward to when we can run this as part of CI. In fact, we could do that now for the Linux binaries in TeamCity by making a new build config for running the linux one and make it depend on the output of the linux binary build config.

Maybe also put the bincheck directory under `pkg/testutils`?

Either way, LGTM.

**Comment by rail** [comment]
> I like this as an incremental step to remove the manual run step. Looking forward to when we can run this as part of CI. In fact, we could do that now for the Linux binaries in TeamCity by making a new build config for running the linux one and make it depend on the output of the linux binary build config.

Yes! Let's make some baby steps first :)

> Maybe also put the bincheck directory under `pkg/testutils`?

I thought about that too, but we have zero Go files here... 🤔 

> Either way, LGTM.

TFTR!

I'm thinking about backporting this too!

**Review by celiala — APPROVED** [review]
:lgtm: - reviewed at a high-level - everything makes sense to me.

Nice to see all the incremental improvements to the Week 1 tasks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77038#-:-MwlwmKP50En-FVmy2Jg:b-vs29zw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rail)

___
*[build/release/bincheck/buildroot.patch, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77038#-MwlwFmzCSRAeRPONjuq:-MwlwFmzCSRAeRPONjur:bt1p3km) ([raw file](https://github.com/cockroachdb/cockroach/blob/763611f49047716c651ea48cfae9ec0dcba895fe/build/release/bincheck/buildroot.patch#L2)):*
> ```Diff
> diff --git a/package/ncurses/Config.in b/package/ncurses/Config.in
> index 92be164..b3333f1 100644
> ```

did you mean to include this .patch file?

**Review by rail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77038)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @celiala and @rail)

___
*[build/release/bincheck/buildroot.patch, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77038#-MwlwFmzCSRAeRPONjuq:-Mwn4ctv7l8ekIeOmBAW:b-bi43tu) ([raw file](https://github.com/cockroachdb/cockroach/blob/763611f49047716c651ea48cfae9ec0dcba895fe/build/release/bincheck/buildroot.patch#L2)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

did you mean to include this .patch file?
</blockquote></details>

Yeah, we need it if we want to recreate the image.

**Comment by rail** [comment]
I have to merge this manually, bors cannot merge GitHub Actions files.

**Comment by rail** [comment]
blathers backport release-21.1 release-21.2

**Pull request merged**
