### PR TITLE
all: migrate to proto3 where possible

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5891)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 42 files reviewed at latest revision, 1 unresolved discussion.

---

*[roachpb/internal_raft.pb.go, line 94 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5891#-KEgbIL4gtL4YuvHB7Rw:-KEgbIL4gtL4YuvHB7Rx:1101073336) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b7697b3b94f90478275d23aedb3c96aeda30842/roachpb/internal_raft.pb.go#L94)):*
These changes in the generated code are concerning. How is this PR not causing differences in the bytes encoded by protobufs? I agree that the protos will logically be the same, but raft requires byte identical encoding (AFAIU).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5891)*

**Comment by tamird** [comment]
Review status: 0 of 42 files reviewed at latest revision, 1 unresolved discussion.

---

*[roachpb/internal_raft.pb.go, line 94 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5891#-KEgbIL4gtL4YuvHB7Rw:-KEgbxKoEX97RLpm6V7y:-412626308) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b7697b3b94f90478275d23aedb3c96aeda30842/roachpb/internal_raft.pb.go#L94)):*
Good point - this one is not safe. Removed this commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5891)*

**Comment by petermattis** [comment]
This change is a bit scary to me now that we're trying to maintain on-disk compatibility between versions. Wondering what we can do to reassure ourselves that this isn't mucking things up with protos encoded "below" raft.

---

Review status: 0 of 40 files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/store.go, line 94 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5891#-KEgi4RpltMrS44htGP-:-KEgi4RpltMrS44htGP0:681248808) ([raw file](https://github.com/cockroachdb/cockroach/blob/c51cb45f19afc91abfb065d8562e3ced3bab8020/storage/store.go#L94)):*
Why was this change needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5891#-:-KEgiV_tYXII824viUB9:1404257750)*

**Comment by bdarnell** [comment]
What do we gain by making this change?

**Comment by tamird** [comment]
Review status: 0 of 40 files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/store.go, line 94 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5891#-KEgi4RpltMrS44htGP-:-KEhSpXCiOg2UfMnGw-Q:-414003636) ([raw file](https://github.com/cockroachdb/cockroach/blob/c51cb45f19afc91abfb065d8562e3ced3bab8020/storage/store.go#L94)):*
https://github.com/coreos/etcd/pull/4929 changed an integer comparison from `>` to `>=`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5891)*

**Comment by petermattis** [comment]
I'd like to see a test which fails if a something changes in a proto marshaled by raft. Here is one idea that doesn't seem robust enough, but hopefully gets the brainstorming started: enumerate the protos that are marshaled "below" raft. For each proto, initialize the fields, marshal the proto, compute a sha and compare to a golden value.

---

Review status: 0 of 40 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5891#-:-KEi7D7NRhx5mPJnOXOM:-688271392)*

**Comment by tamird** [comment]
Good idea. We can use https://github.com/gogo/protobuf/blob/master/plugin/populate/populate.go to generate useful code for this, which together with deliberate [`rand.Seed`](https://godoc.org/math/rand#Seed)ing gives us most of this for free.

The tricky part is enumerating the protos which are "below" raft.

If we can't do that programmatically, we likely want a whitelist of "above" raft protos. We'd still need a way to programmatically enumerate all proto.Message implementations to avoid regressions in the test - these are tracked in the `proto` package, but not exposed as a collection; probably easy enough to work around this with additional code generation.

Thoughts?

---

Review status: 0 of 40 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5891#-:-KEi8wzIulL0ZfkUfoDp:1450602557)*

**Comment by petermattis** [comment]
There aren't that many calls to `proto.Marshal` in the `storage` package. You'd also have to look for calls to `roachpb.Value.SetProto` and `MVCCPutProto`, but that doesn't seem too onerous. I wonder if `guru` (a.k.a. `go oracle`) could tell us. 

---

Review status: 0 of 40 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5891#-:-KEkyBpxmweEEj-U3gpm:-1471659985)*

**Comment by bdarnell** [comment]
Review status: 0 of 40 files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/store.go, line 94 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5891#-KEgi4RpltMrS44htGP-:-KEm5QOGlofV-23gT_QN:-1584854001) ([raw file](https://github.com/cockroachdb/cockroach/blob/c51cb45f19afc91abfb065d8562e3ced3bab8020/storage/store.go#L94)):*
Please do things like this (i.e. update dependencies and make any changes required by those updates) in a separate PR. The PR subject line should be an accurate reflection of what's in the PR so potential reviewers can decide whether or not to pay attention to it.

---

*[roachpb/internal_raft.pb.go, line 94 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5891#-KEgbIL4gtL4YuvHB7Rw:-KEm5bTH0-q6K6mjFlls:-1237178883) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b7697b3b94f90478275d23aedb3c96aeda30842/roachpb/internal_raft.pb.go#L94)):*
I think it would have been fine, actually. `RaftTruncatedState` is the only one of the protos in this file that is written downstream of raft, and it only ever contains non-zero values. But this is subtle and it's probably safer to leave this out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5891)*

**Comment by tamird** [comment]
Review status: 0 of 40 files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/store.go, line 94 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5891#-KEgi4RpltMrS44htGP-:-KEmZ2N078F7Zei8LQ0I:-64281313) ([raw file](https://github.com/cockroachdb/cockroach/blob/c51cb45f19afc91abfb065d8562e3ced3bab8020/storage/store.go#L94)):*
Updating dependencies was necessary to pick up a proto3 bug fix in gogo/protobuf. I've opened two new PRs with the parts of this that are ready to go now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5891)*

**Comment by tamird** [comment]
Rebased to pick up the machinery discussed here. PTAL

---

Review status: 0 of 25 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[roachpb/internal_raft.pb.go, line 94 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5891#-KEgbIL4gtL4YuvHB7Rw:-KFPMo4s8olrMh9XLdaz:-718711853) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b7697b3b94f90478275d23aedb3c96aeda30842/roachpb/internal_raft.pb.go#L94)):*
Restored.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5891#-:-KFPMe5z8ih1NCuVtK5Z:-1069431655)*

**Comment by bdarnell** [comment]
I repeat my earlier question: what do we gain by making this change? The new tests guarantee that it won't cause consistency failures but there are still downsides: we'll be locked in to a mixed proto2/proto3 world for the foreseeable future and if we decide to enable unrecognized field preservation we'll just have to (partially) undo this change (we declined to do so in #5694 but in #5845 we discovered a case in which this feature would have lessened our migration pain) 

---

Reviewed 1 of 28 files at r3, 2 of 2 files at r4, 3 of 3 files at r5, 6 of 6 files at r6, 2 of 2 files at r7, 2 of 2 files at r8, 2 of 2 files at r9, 2 of 2 files at r10, 2 of 2 files at r11, 3 of 3 files at r12.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5891#-:-KFQQhk_i4mYAS7yQCWk:-1529337043)*

**Comment by tamird** [comment]
We're already in a mixed proto2/proto3 world, so I don't think that's true downside of this PR.

Regarding unrecognized field preservation - I wasn't aware of that discovery in #5845; could you elaborate or link to a specific comment or discussion? In any case, the proto files involved in #5845 are not modified in this PR.

I admit that the upsides here aren't very meaningful; namely they are:
- proto3 encoding is marginally more efficient because it omits empty fields
- we probably want to use proto3 in the future, so we should set the precedent as much as possible

The precedent feels like the bigger win to me.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5891#-:-KFRavJeTzAEdv_HTbUH:-1244341139)*

**Comment by bdarnell** [comment]
> We're already in a mixed proto2/proto3 world, so I don't think that's true downside of this PR.

We only have a few proto3 files; we could change those back to proto2 and standardize on that version. I think I'd rather do that than have half our proto files in proto3 with no viable path to get to 100% proto3.

In [this comment in #5845](https://reviewable.io/reviews/cockroachdb/cockroach/5845#-KEgr7yB57lhywxWKC1q:-KEmZBe9s1otm6wMjt6S:-1900728413), I pointed out that we cannot add new fields to `roachpb.Lease` in an online upgrade because of the way that proto is unmarshaled from the command and remarshaled to disk downstream of raft. Unrecognized field preservation would have kept all replicas in sync (at least for the addition of the new field; there are still other aspects of the change that could have caused migration problems).

> proto3 encoding is marginally more efficient because it omits empty fields

So does proto2; the inefficiency is in gogoproto's non-nullable option. A gogoproto "omitempty" option seems like a reasonable addition if we care about this (and we might, not for encoding efficiency but for the ability to add new fields to downstream-of-raft protos without the allocations implied by nullable fields).

> we probably want to use proto3 in the future, so we should set the precedent as much as possible

I'm not sure I agree with this premise. Proto3 dropped features that we use (the zero-versus empty distinction) or could use (unrecognized field preservation), in favor of things that we don't care as much about (a simpler data model that is closer to the lowest common denominator across many languages). Proto2 looks like it might be a better fit for us even in the long term.

**Comment by tamird** [comment]
> So does proto2; the inefficiency is in gogoproto's non-nullable option.

Not true; proto2 omits unset fields, not empty ones.

> A gogoproto "omitempty" option seems like a reasonable addition if we care about this (and we might, not for encoding efficiency but for the ability to add new fields to downstream-of-raft protos without the allocations implied by nullable fields).

Good point, but how is using that option any different than using proto3 for a given message?

> Proto2 looks like it might be a better fit for us even in the long term.

An exception to this is proto3's canonical JSON mapping https://developers.google.com/protocol-buffers/docs/proto3#json.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5891#-:-KFdaxmr2oABnwPK3Vt_:1738340677)*

**Comment by bdarnell** [comment]
> > So does proto2; the inefficiency is in gogoproto's non-nullable option.
> Not true; proto2 omits unset fields, not empty ones.

If you don't care about the unset vs zero distinction (and you don't if proto3 is an option), you could clear the field when you would otherwise set it to zero and get the same space savings. (the generated getters make this transparent on the reading side)

> Good point, but how is using that option any different than using proto3 for a given message?

It could be set on a smaller scope than a whole file, and it is compatible with features that are not present in proto3 like unrecognized field preservation.

> An exception to this is proto3's canonical JSON mapping https://developers.google.com/protocol-buffers/docs/proto3#json.

Yeah, when/if we have a public-facing proto-based API we may want to use proto3 there. But internally we don't really care about alternative encodings of protos.

**Comment by tamird** [comment]
> If you don't care about the unset vs zero distinction (and you don't if proto3 is an option), you could clear the field when you would otherwise set it to zero and get the same space savings. (the generated getters make this transparent on the reading side)

Agreed. The main advantage of proto3 in this regard (for now) is that it saves us from having to do the `omitempty` work in gogo/protobuf.

> Yeah, when/if we have a public-facing proto-based API we may want to use proto3 there. But internally we don't really care about alternative encodings of protos.

We sort of already do in the admin API; I think we want to keep all those protos in proto3 permanently.

**Comment by tamird** [comment]
Turns out the canonical JSON representation is a more compelling reason to use proto3 than previously thought - @mrtracy ran into an issue where Go's native JSON marshalling encodes int64s as numbers rather than strings, which doesn't comply with proto3 (and is the reason for the existence of the package `jsonpb`).

That issue might be fixed in #6587, but might also require parts of this PR.

**Comment by tamird** [comment]
Rebased this again; I'd like to get it in, if nothing else then to reduce the decision points for future additions.

**Comment by petermattis** [comment]
@tamird Can you re-summarize the pros and cons of switching to proto3?

**Comment by tamird** [comment]
Pros:
- "blessed" (???)
- requires fewer options in common cases (i.e. no need to non-nullable scalar types)
- well-defined JSON representation (though this is available for proto2 as well in practice)

Cons:
- less featureful

**Comment by petermattis** [comment]
I think we should hold off on this change for a while longer. Moving to proto3 looks reasonable, yet I'm anxious about unexpected problems this might cause. With the current focus on stability, I don't see any upside to pushing this in now, only downside due to unexpected problems.

**Pull request closed without merging**
