### PR TITLE
sql: add inverted indexing for tsvector and acceleration for @@ queries

### PR DESCRIPTION
**Pull request by jordanlewis**
Updates #41288 

This PR adds the ability to create an inverted index on a tsvector column, and adds inverted index acceleration for expressions that evaluate a tsquery against a tsvector using the `@@` operator.

Epic: CRDB-22357

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
Nice! Would it be possible to add some randomized tests similar to the ones we have for array / json / trigram?

> Reviewed 8 of 8 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93769#-:-NL8BgZI9se3dcJWojit:bulxo8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[`pkg/sql/opt/invertedidx/tsearch.go` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93769#-NL8CDdz2G7McWyJRvrd:-NL8CDdz2G7McWyJRvre:b1x8vm9) ([raw file](https://github.com/cockroachdb/cockroach/blob/50871a3a302675ebfe25486b58cc1118c811462b/pkg/sql/opt/invertedidx/tsearch.go#L1)):*
> ```Go
> // Copyright 2022 The Cockroach Authors.
> ```

Can you add a unit test for this similar to `trigram_test.go`?
___
*[`pkg/sql/sem/builtins/builtins.go` line 5928 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93769#-NL87ZIR2Exkad4LufAM:-NL87ZIR2Exkad4LufAN:b-ooe4bn) ([raw file](https://github.com/cockroachdb/cockroach/blob/50871a3a302675ebfe25486b58cc1118c811462b/pkg/sql/sem/builtins/builtins.go#L5928)):*
> ```Go
> 			Types: tree.ParamTypes{
> 				{Name: "val", Typ: types.TSVector},
> 				{Name: "version", Typ: types.Int},
> ```

nit: this change should go with the first commit
___
*[`pkg/util/tsearch/encoding.go` line 470 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93769#-NL85sUQDBbIo5-8vteQ:-NL85sUQDBbIo5-8vteR:bdnnz8f) ([raw file](https://github.com/cockroachdb/cockroach/blob/90de576be7c04d873850af1ee090b4a50994f6ad/pkg/util/tsearch/encoding.go#L470)):*
> ```Go
> 		outKeys = append(outKeys, newKey)
> 	}
> 	return outKeys, nil
> ```

Can you guarantee that all terms are unique?
___
*[`pkg/util/tsearch/tsquery.go` line 184 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93769#-NL89tAc4iQH5LSkWaQw:-NL89tAc4iQH5LSkWaQx:bqvcg3o) ([raw file](https://github.com/cockroachdb/cockroach/blob/50871a3a302675ebfe25486b58cc1118c811462b/pkg/util/tsearch/tsquery.go#L184)):*
> ```Go
> 		key := EncodeInvertedIndexKey(nil /* inKey */, n.term.lexeme)
> 		span := inverted.MakeSingleValSpan(key)
> 		return inverted.ExprForSpan(span, true), nil
> ```

nit: true /* tight */

Also, should we set `Unique = true` on this span expression?
___
*[`pkg/util/tsearch/tsquery.go` line 186 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93769#-NL8BOlb6a_mbLY5VpFd:-NL8BOlb6a_mbLY5VpFe:bvwwd67) ([raw file](https://github.com/cockroachdb/cockroach/blob/50871a3a302675ebfe25486b58cc1118c811462b/pkg/util/tsearch/tsquery.go#L186)):*
> ```Go
> 		return inverted.ExprForSpan(span, true), nil
> 	case followedby:
> 		fallthrough
> ```

should we do `SetNotTight()` in this case?
___
*[`pkg/sql/opt/exec/execbuilder/testdata/tsvector_index` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93769#-NL8C1pn32SWWX-g4-xs:-NL8C1pn32SWWX-g4-xt:bun3ac7) ([raw file](https://github.com/cockroachdb/cockroach/blob/50871a3a302675ebfe25486b58cc1118c811462b/pkg/sql/opt/exec/execbuilder/testdata/tsvector_index#L1)):*
> ```
> # LogicTest: local
> ```

it would be good to add a similar file in `logictests` to check that the query output is as expected.

**Review by jordanlewis — COMMENTED** [review]
Thanks for the review, responded to all inline comments. I'll add some randomized encoded span containment tests as well, I forgot about those. The amount of places we need the same kinds of test cases for the inverted expressions is a little bit annoying (we'd like the same test cases in logic tests, execbuilder tests, eval tests, encoded span containment tests, and probably more), but I'm not really sure if it's possible to factor them out well. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93769#-:-NLJiweK3Wnx6TAyuhDl:bd74ef2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`pkg/sql/opt/invertedidx/tsearch.go` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93769#-NL8CDdz2G7McWyJRvrd:-NLJbkk42BXkzdz0iqBS:bv00ugk) ([raw file](https://github.com/cockroachdb/cockroach/blob/50871a3a302675ebfe25486b58cc1118c811462b/pkg/sql/opt/invertedidx/tsearch.go#L1)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Can you add a unit test for this similar to `trigram_test.go`?
</blockquote></details>

:facepalm: not sure why I didn't do this in the first place, thanks for the nudge. Added a suite.
___
*[`pkg/util/tsearch/encoding.go` line 470 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93769#-NL85sUQDBbIo5-8vteQ:-NLJHiSsBrhldTncqKl6:b-bjwonx) ([raw file](https://github.com/cockroachdb/cockroach/blob/90de576be7c04d873850af1ee090b4a50994f6ad/pkg/util/tsearch/encoding.go#L470)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Can you guarantee that all terms are unique?
</blockquote></details>

Yes, TSVector is guaranteed to be sorted and contain unique terms only - that's part of its contract. It's enforced during TSVector construction time. Added a comment to help motivate.
___
*[`pkg/util/tsearch/tsquery.go` line 184 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93769#-NL89tAc4iQH5LSkWaQw:-NLJIzFEC9iYFPCaZXV3:bqi2e66) ([raw file](https://github.com/cockroachdb/cockroach/blob/50871a3a302675ebfe25486b58cc1118c811462b/pkg/util/tsearch/tsquery.go#L184)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: true /* tight */

Also, should we set `Unique = true` on this span expression?
</blockquote></details>

There were some difference in behavior here I overlooked when I made this change, until the changes in #94431. Added commentary and updated behavior (to deal with prefix matches and weight matches).
___
*[`pkg/util/tsearch/tsquery.go` line 186 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93769#-NL8BOlb6a_mbLY5VpFd:-NLJNqM-59MzujWZjk2K:b-ub7kdu) ([raw file](https://github.com/cockroachdb/cockroach/blob/50871a3a302675ebfe25486b58cc1118c811462b/pkg/util/tsearch/tsquery.go#L186)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

should we do `SetNotTight()` in this case?
</blockquote></details>

Yes, good point. Done. A few changes were necessary, PTAL.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/tsvector_index` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93769#-NL8C1pn32SWWX-g4-xs:-NLJhjoF9W1I-c9PE-xU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/50871a3a302675ebfe25486b58cc1118c811462b/pkg/sql/opt/exec/execbuilder/testdata/tsvector_index#L1)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

it would be good to add a similar file in `logictests` to check that the query output is as expected.
</blockquote></details>

Done.

**Review by rytaft — COMMENTED** [review]
> The amount of places we need the same kinds of test cases for the inverted expressions is a little bit annoying 

I agree, although these things have also been notoriously full of bugs, so I think it's better to err on the side of over-testing rather than under-testing. But let me know if you have ideas...

> Reviewed 14 of 14 files at r3, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93769#-:-NLN1-g136gyLm-sjUxa:b-p60xfy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[`pkg/util/tsearch/encoding.go` line 463 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93769#-NLN1aQp1a34ov0Nq5Tz:-NLN1aQp1a34ov0Nq5U-:b-r84v9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/693df3c1586145b2163a1ea0e11b63156f12245c/pkg/util/tsearch/encoding.go#L463)):*
> ```Go
> func EncodeInvertedIndexKeys(inKey []byte, vector TSVector) ([][]byte, error) {
> 	outKeys := make([][]byte, 0, len(vector))
> 	// Note that by construction, TSVector contains only unique term, so we don't
> ```

nit: term -> terms
___
*[`pkg/util/tsearch/tsquery.go` line 192 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93769#-NLN1sUc7kBlcJfnlkeq:-NLN1sUc7kBlcJfnlker:bh0jsll) ([raw file](https://github.com/cockroachdb/cockroach/blob/693df3c1586145b2163a1ea0e11b63156f12245c/pkg/util/tsearch/tsquery.go#L192)):*
> ```Go
> 		// 3. Weighted match.
> 		//    In this case, we make the match non-tight, because we don't store the
> 		//    weights of the lexemes in the index, and are forced to re-check the
> ```

nit: trailing "the"
___
*[`pkg/util/tsearch/tsquery.go` line 252 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93769#-NLN32Zq2ofZy0AfMhNR:-NLN32Zq2ofZy0AfMhNS:b-9xjijp) ([raw file](https://github.com/cockroachdb/cockroach/blob/693df3c1586145b2163a1ea0e11b63156f12245c/pkg/util/tsearch/tsquery.go#L252)):*
> ```Go
> 		// We never have a unique match when combining terms, since a single primary
> 		// key could be represented in both terms.
> 		expr.(*inverted.SpanExpression).Unique = false
> ```

I don't think this is needed. The comment for `Unique` says "it holds when unique SpanExpressions are combined with And". The code in `expression.go` should already be doing the right thing.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93769)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`pkg/util/tsearch/tsquery.go` line 252 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93769#-NLN32Zq2ofZy0AfMhNR:-NLqO36eCwmqlI25Vg6o:b-de5yba) ([raw file](https://github.com/cockroachdb/cockroach/blob/693df3c1586145b2163a1ea0e11b63156f12245c/pkg/util/tsearch/tsquery.go#L252)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I don't think this is needed. The comment for `Unique` says "it holds when unique SpanExpressions are combined with And". The code in `expression.go` should already be doing the right thing.
</blockquote></details>

It does seem to be required, unless I'm using the API wrong. The following test case fails without this line of code:

```
    tsearch_test.go:94: test case: {t @@ 'a & b' true true false}
    tsearch_test.go:122: For (t @@ 'a & b'), expected unique=false, but got true
```

Reading the code of `And`, it seems like `Unique` is populated like this:

```
		Unique: left.Unique && right.Unique,
```

Which seems wrong to me in this case? Or am I missing something and the test case is wrong?

The trigram inverted filter builder also does this - it assumes that Unique should be false if you're combining 2 spans with And. I guess there are fixes to make over there as well.

Is the idea that we can still assume they're Unique after And because the rows will be intersected during execution?

Then again, I've read the code that reads the Unique field and it appears like nobody ever uses the Unique property of an expression that isn't a leaf, so I think all of this is immaterial. Perhaps we could teach the optimizer to not plan an inverted filter if the operator is AND and the expression is Unique, at least in some cases? But that's not done today.

**Comment by jordanlewis** [comment]
Nevermind, you still of course need the inverted filter - that's the thing that's doing the intersection. I still think there could be some duplicate work being performed in the inverted filterer - can't we avoid checking each span for containment within the inverted expression's span, since we know by construction that each returned key is in fact contained in the search spans? But I don't really understand that code very well so I could be wrong.

**Review by rytaft — COMMENTED** [review]
> Nevermind, you still of course need the inverted filter...

I think we discussed this offline, but let me know if you're still unsure about anything.

> Reviewed 13 of 13 files at r5, 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93769#-:-NM9UAZT9c4342OkQH-A:bw2g4c1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[`pkg/util/tsearch/tsquery.go` line 252 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93769#-NLN32Zq2ofZy0AfMhNR:-NM9TSg07pcSLFdZxwRj:b-jhxpc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/693df3c1586145b2163a1ea0e11b63156f12245c/pkg/util/tsearch/tsquery.go#L252)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

It does seem to be required, unless I'm using the API wrong. The following test case fails without this line of code:

```
    tsearch_test.go:94: test case: {t @@ 'a & b' true true false}
    tsearch_test.go:122: For (t @@ 'a & b'), expected unique=false, but got true
```

Reading the code of `And`, it seems like `Unique` is populated like this:

```
		Unique: left.Unique && right.Unique,
```

Which seems wrong to me in this case? Or am I missing something and the test case is wrong?

The trigram inverted filter builder also does this - it assumes that Unique should be false if you're combining 2 spans with And. I guess there are fixes to make over there as well.

Is the idea that we can still assume they're Unique after And because the rows will be intersected during execution?

Then again, I've read the code that reads the Unique field and it appears like nobody ever uses the Unique property of an expression that isn't a leaf, so I think all of this is immaterial. Perhaps we could teach the optimizer to not plan an inverted filter if the operator is AND and the expression is Unique, at least in some cases? But that's not done today.
</blockquote></details>

We discussed this offline -- I think based on that discussion my original comment stands? Let me know if you still disagree.

**Comment by jordanlewis** [comment]
I went ahead and added an index span containment suite with randomization like we do with JSON and Array inverted indexes. I think this is what you were thinking of - PTAL!

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93769)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`pkg/util/tsearch/tsquery.go` line 252 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93769#-NLN32Zq2ofZy0AfMhNR:-NMGB0uB37nydoHJY8of:b-y5pc9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/693df3c1586145b2163a1ea0e11b63156f12245c/pkg/util/tsearch/tsquery.go#L252)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

We discussed this offline -- I think based on that discussion my original comment stands? Let me know if you still disagree.
</blockquote></details>

Yup, agreed, this is now corrected.

**Review by rytaft — APPROVED** [review]
:lgtm: thanks!

> Reviewed 15 of 15 files at r7, 12 of 14 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93769#-:-NMGkg6dDusUtrpfwdPg:brfqlux)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[`pkg/sql/inverted/expression.go` line 303 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/93769#-NMGejz69_vg73oaJvo5:-NMGejz69_vg73oaJvo6:bew8aoi) ([raw file](https://github.com/cockroachdb/cockroach/blob/22f65532948316e8ea9221632c66e3de64691cea/pkg/sql/inverted/expression.go#L303)):*
> ```Go
> 	Tight bool
> 
> 	// Unique is true if the spans are guaranteed not to produce duplicate
> ```

maybe this should be "the spans in FactoredUnionSpans"
___
*[`pkg/sql/inverted/expression.go` line 311 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/93769#-NMGcKyZ74orZ8XrdUmG:-NMGcKyZ74orZ8XrdUmH:bnl2z89) ([raw file](https://github.com/cockroachdb/cockroach/blob/22f65532948316e8ea9221632c66e3de64691cea/pkg/sql/inverted/expression.go#L311)):*
> ```Go
> 	// Note that the uniqueness property represented here holds for the *output*
> 	// of the invertedFilter operator that executes the And/Or, not the raw, input
> 	// spans of data.
> ```

Technically the invertedFilter *always* returns unique keys. How about something like this:
```
// Once a SpanExpression is built, this field is relevant if the root SpanExpression
// has no children (i.e., Operator is None). In this case, Unique is used to determine
// whether an invertedFilter is needed on top of the inverted index scan to deduplicate
// keys (an invertedFilter is always necessary if Operator is not None).
```

**Review by jordanlewis — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93769#-:-NMJXvn_0xrhO-x1Y3kk:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`pkg/sql/inverted/expression.go` line 303 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/93769#-NMGejz69_vg73oaJvo5:-NMJXdDaD_aCj6FSe2KI:bx9nit9) ([raw file](https://github.com/cockroachdb/cockroach/blob/22f65532948316e8ea9221632c66e3de64691cea/pkg/sql/inverted/expression.go#L303)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

maybe this should be "the spans in FactoredUnionSpans"
</blockquote></details>

Done, I agree that helps matters.
___
*[`pkg/sql/inverted/expression.go` line 311 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/93769#-NMGcKyZ74orZ8XrdUmG:-NMJXXPz0XV5I9wbbH1U:been511) ([raw file](https://github.com/cockroachdb/cockroach/blob/22f65532948316e8ea9221632c66e3de64691cea/pkg/sql/inverted/expression.go#L311)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Technically the invertedFilter *always* returns unique keys. How about something like this:
```
// Once a SpanExpression is built, this field is relevant if the root SpanExpression
// has no children (i.e., Operator is None). In this case, Unique is used to determine
// whether an invertedFilter is needed on top of the inverted index scan to deduplicate
// keys (an invertedFilter is always necessary if Operator is not None).
```
</blockquote></details>

This sounds better, thanks!

**Pull request merged**
