### PR TITLE
sql: allow changing the number of histogram samples and buckets

### PR DESCRIPTION
**Pull request by rytaft**
Informs #72418
Informs #97701

Release note (sql change): Added two new cluster settings that enable users to change the number of histogram samples and buckets collected when building histograms as part of table statistics collection: `sql.stats.histogram_samples.count` and `sql.stats.histogram_buckets.count`. While the default values should work for most cases, it may be beneficial to increase the number of samples and buckets for very large tables to avoid creating a histogram that misses important values.

### CODE REVIEW

**Comment by rytaft** [comment]
I'm going to open another PR to add table-specific settings, but those won't be backportable beyond 23.1.

**Comment by rytaft** [comment]
> I'm going to open another PR to add table-specific settings, but those won't be backportable beyond 23.1.

#100479

**Review by michae2 — APPROVED** [review]
:lgtm: Nice!

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100357#-:-NS8-sJ7A-JIwUOCprKi:b-8gk8uj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)

**Comment by rytaft** [comment]
TFTR!

bors r+

**Comment by rytaft** [comment]
Removing the backport-22.1.x label since it's more trouble than it's worth.

**Pull request merged**
