### PR TITLE
server: Use node liveness for the admin health check

### LINKED ISSUE #8852: server: Health check endpoint returns healthy when main serving port is unresponsive
This makes the health check endpoint (`$HOST:8080/_admin/v1/health`) not particularly useful. When I say the "main serving port is unresponsive", I'm specifically referring to the condition in #8784, where the 26257 port won't respond to requests and processing seems to be stuck on a deadlock in rocksdb.

My initial attempt at setting up health checks in our example Kubernetes deployment was to use this endpoint. I could instead set up a health check in our Kubernetes config that actually runs a SQL command, but it seems like this fixing this endpoint would be more useful to more people.

Related to #3726.

Example of what the health endpoint returns when on a deadlocked instance:

```
# curl -i localhost:8080/_admin/v1/health
HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Type: application/json
Date: Fri, 26 Aug 2016 15:43:53 GMT
Content-Length: 4

{

}
```

### PR DESCRIPTION
**Pull request by a-robinson**
Fixes #8852

@spencerkimball @tamird @maxlang

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12287)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm: - how about a test?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12287#-:-KYoGXmqfvta2nsDdG3V:bnh2tjd)*

**Review by petermattis — APPROVED** [review]
LGTM

**Comment by a-robinson** [comment]
Sure, added a test.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12287#-:-KYoQ-llAxBwM6gweUYY:b139dfz)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12287)*

**Comment by a-robinson** [comment]
Added a `testutils.SucceedsSoon` call to the first test request. It didn't flake at all locally, but apparently the timing of things on the teamcity builders is a bit different.

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12287)*

**Review by spencerkimball — COMMENTED** [review]
Lgtm

**Pull request merged**
