### PR TITLE
storage: Push pagination for EndTxn into the MVCC layer

### PR DESCRIPTION
**Pull request by KaiSun314**
Informs: https://github.com/cockroachdb/cockroach/issues/77228

This PR consists of two parts: adding `MVCCPagination` and integrating `MVCCPagination` to push pagination of `EndTxn` into the MVCC layer.

Part 1: Add `MVCCPagination`

Implement MVCCPagination which calls a user-inputted function f() until
it returns an error (note that the iterutil.StopIteration() error means
we have iterated through all elements), or until the number of keys hits
the maxKeys limit or the number of bytes hits the targetBytes limit.

MVCCPagination is a general framework that enables key and byte
pagination.

Part 2: Integrate `MVCCPagination` to Push Pagination of `EndTxn` Into The MVCC Layer

In this PR, we push key pagination for EndTxn (currently located in
cmd_end_transaction.go) into the MVCC layer (mvcc.go) by integrating
MVCCPagination from the previous commit into EndTxn.

Release note: None

### CODE REVIEW

**Comment by KaiSun314** [comment]
**Please only review the third commit `storage: Add MVCCPagination to allow general key and byte pagination` and fourth commit `storage: Push pagination for EndTxn into the MVCC layer`**. The first commit `storage: Refactor resolve write intent options` is #94764 and the second commit `storage: Add support for TargetBytes for resolve intent + range cmd` is #94814. Thank you so much in advance!

**Review by nvb — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94939)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @KaiSun314)

___
*[`pkg/kv/kvserver/batcheval/cmd_end_transaction.go` line 557 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94939#-NOwhezUBu_ML3Cxi0QJ:-NOwhezUBu_ML3Cxi0QK:bdzb226) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b0d350c71c9d9039e97b44b945be74b1bc5afe7/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L557)):*
> ```Go
> 		span := args.LockSpans[i]
> 		i++
> 		if err := func() error {
> ```

This anonymous function was used to group the error-handling path so we could wrap all errors with "resolving lock at ..". Now that we're calling `storage.MVCCPagination`, I don't think we need it. Instead, we can just perform the error wrapping on the error return path after the call to `storage.MVCCPagination`.
___
*[`pkg/kv/kvserver/batcheval/cmd_end_transaction.go` line 574 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94939#-NOwhMQsEmKBcLPzkabT:-NOwhMQsEmKBcLPzkabU:b-gtvdxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b0d350c71c9d9039e97b44b945be74b1bc5afe7/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L574)):*
> ```Go
> 				// Note that the underlying pebbleIterator will still be reused
> 				// since readWriter is a pebbleBatch in the typical case.
> 				ok, _, _, err := storage.MVCCResolveWriteIntent(ctx, readWriter, ms, update,
> ```

`MVCCResolveWriteIntent` returns a resume span. Should we be consulting it?
___
*[`pkg/kv/kvserver/batcheval/cmd_end_transaction.go` line 635 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94939#-NOwiCFZ9KmZZz2E8HEB:-NOwiCFZ9KmZZz2E8HEC:b-rn1279) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b0d350c71c9d9039e97b44b945be74b1bc5afe7/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L635)):*
> ```Go
> 	}
> 
> 	externalLocks = append(externalLocks, args.LockSpans[i:]...)
> ```

Instead of maintaining `i` separately and reaching into `args.LockSpans` multiple times, what do you think about something like:
```go
remainingLockSpans := args.LockSpans
f := func(maxKeys, targetBytes int64) (numKeys int64, numBytes int64, resumeSpan *roachpb.Span, err error) {
    if len(remainingLockSpans) == 0 {
        return 0, 0, nil, iterutil.StopIteration()
    }
    span := remainingLockSpans[0]
    remainingLockSpans = remainingLockSpans[1:]
    ...
    if ... {
        externalLocks = append(externalLocks, span)
    }
    ...
}

externalLocks = append(externalLocks, remainingLockSpans...)
```
___
*[`pkg/storage/mvcc.go` line 4089 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94939#-NOwdOfi3dcy4hw-9wUS:-NOwdOfi3dcy4hw-9wUT:bjywhou) ([raw file](https://github.com/cockroachdb/cockroach/blob/36d75d53f24efaf5d2af9ee82a02327ba87c20ae/pkg/storage/mvcc.go#L4089)):*
> ```Go
> }
> 
> // MVCCPagination invokes f() until it returns done (i.e. we have iterated
> ```

The functions in this package are typically verbs (`MVCCScan`, `MVCCIterate`, etc.), so to match, we'll want to name this `MVCCPaginate`.
___
*[`pkg/storage/mvcc.go` line 4090 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94939#-NOwezpa6wZzWRiGFwLf:-NOwezpa6wZzWRiGFwLg:b3j9sh4) ([raw file](https://github.com/cockroachdb/cockroach/blob/36d75d53f24efaf5d2af9ee82a02327ba87c20ae/pkg/storage/mvcc.go#L4090)):*
> ```Go
> 
> // MVCCPagination invokes f() until it returns done (i.e. we have iterated
> // through all elements) or an error, or until the number of keys hits the
> ```

We should include some of the commentary from `MVCCIterate` about `iterutil.StopIteration`.

EDIT: it looks like you added some of this in the second commit. We'll want to move that back to the first.
___
*[`pkg/storage/mvcc.go` line 4091 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94939#-NOwdiqE4l6ZxrOnnUKV:-NOwdiqE4l6ZxrOnnUKW:b-jez31i) ([raw file](https://github.com/cockroachdb/cockroach/blob/36d75d53f24efaf5d2af9ee82a02327ba87c20ae/pkg/storage/mvcc.go#L4091)):*
> ```Go
> // MVCCPagination invokes f() until it returns done (i.e. we have iterated
> // through all elements) or an error, or until the number of keys hits the
> // maxKeys limit or the number of bytes hits the targetBytes limit.
> ```

It would be worthwhile calling out that it's up to `f()` whether it wants to allow the `numBytes` to exceed `targetBytes` by up to one entry or whether it wants to terminate iteration before `numBytes` exceeds `targetBytes`. See the `AllowEmpty` option.

Having written that out, I wonder how that choice interacts with the resumeSpan assertion that you added.
___
*[`pkg/storage/mvcc.go` line 4105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94939#-NOweRhIE_IuTsHV8jcB:-NOweRhIE_IuTsHV8jcC:b-h4owg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/36d75d53f24efaf5d2af9ee82a02327ba87c20ae/pkg/storage/mvcc.go#L4105)):*
> ```Go
> 		}
> 		addedKeys, addedBytes, resumeSpan, err := f(maxKeys, targetBytes)
> 		if err != nil {
> ```

Is the assumption that `addedKeys`, `addedBytes`, and `resumeSpan` are all empty in this case? If so, should we assert that?
___
*[`pkg/storage/mvcc.go` line 4127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94939#-NOwfHrHBtqT2zPwHqzb:-NOwfHrHBtqT2zPwHqzc:bzff76l) ([raw file](https://github.com/cockroachdb/cockroach/blob/36d75d53f24efaf5d2af9ee82a02327ba87c20ae/pkg/storage/mvcc.go#L4127)):*
> ```Go
> 			}
> 		}
> 		if resumeSpan != nil {
> ```

I think we had talked about returning the `resumeSpan` in the past. It's definitely better than nothing because it allows for the assertion, but if we're just going to drop it after the assertion, I wonder whether we should return the `resumeReason` instead. If we do that, we can tighten up the assertion further. There's also something nice about returning an integer instead of a pointer.

**Review by KaiSun314 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94939)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/batcheval/cmd_end_transaction.go` line 574 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94939#-NOwhMQsEmKBcLPzkabT:-NP-g9yl-D4B6F1BIpHe:b-51b6yv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b0d350c71c9d9039e97b44b945be74b1bc5afe7/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L574)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`MVCCResolveWriteIntent` returns a resume span. Should we be consulting it?
</blockquote></details>

`MVCCResolveWriteIntent` will only return a resume span with byte pagination, not key pagination. Byte pagination will be added in #95141, and this PR's goal is to just do refactoring with no behaviour changes
___
*[`pkg/kv/kvserver/batcheval/cmd_end_transaction.go` line 635 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94939#-NOwiCFZ9KmZZz2E8HEB:-NP-gXiGDXYBefHUHwKV:b-kwx38z) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b0d350c71c9d9039e97b44b945be74b1bc5afe7/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L635)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Instead of maintaining `i` separately and reaching into `args.LockSpans` multiple times, what do you think about something like:
```go
remainingLockSpans := args.LockSpans
f := func(maxKeys, targetBytes int64) (numKeys int64, numBytes int64, resumeSpan *roachpb.Span, err error) {
    if len(remainingLockSpans) == 0 {
        return 0, 0, nil, iterutil.StopIteration()
    }
    span := remainingLockSpans[0]
    remainingLockSpans = remainingLockSpans[1:]
    ...
    if ... {
        externalLocks = append(externalLocks, span)
    }
    ...
}

externalLocks = append(externalLocks, remainingLockSpans...)
```
</blockquote></details>

Done. Agreed, that is cleaner!
___
*[`pkg/storage/mvcc.go` line 4091 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94939#-NOwdiqE4l6ZxrOnnUKV:-NP-gjDR4EZn669rtWwx:b-kr3kko) ([raw file](https://github.com/cockroachdb/cockroach/blob/36d75d53f24efaf5d2af9ee82a02327ba87c20ae/pkg/storage/mvcc.go#L4091)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It would be worthwhile calling out that it's up to `f()` whether it wants to allow the `numBytes` to exceed `targetBytes` by up to one entry or whether it wants to terminate iteration before `numBytes` exceeds `targetBytes`. See the `AllowEmpty` option.

Having written that out, I wonder how that choice interacts with the resumeSpan assertion that you added.
</blockquote></details>

Hmm that's true. I have implemented one possible solution: `MVCCPaginate` will take in an `allowEmpty` parameter. If `allowEmpty` is true, then the `resumeReason` assertion will not be checked for the `targetBytes` limit (the `maxKeys` limit will still be checked regardless of `allowEmpty`). I was wondering if this would be okay?
___
*[`pkg/storage/mvcc.go` line 4127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94939#-NOwfHrHBtqT2zPwHqzb:-NP-hNUp0FKpNW7-fkon:b-uqhi17) ([raw file](https://github.com/cockroachdb/cockroach/blob/36d75d53f24efaf5d2af9ee82a02327ba87c20ae/pkg/storage/mvcc.go#L4127)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think we had talked about returning the `resumeSpan` in the past. It's definitely better than nothing because it allows for the assertion, but if we're just going to drop it after the assertion, I wonder whether we should return the `resumeReason` instead. If we do that, we can tighten up the assertion further. There's also something nice about returning an integer instead of a pointer.
</blockquote></details>

Done. Agreed, changed to `resumeReason`, which also works perfectly with the above design to resolve the `resumeReason` assertion conflicting with the user wishing to terminate iteration before numBytes exceeds targetBytes.

**Review by nvb — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94939)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @KaiSun314)

___
*[`pkg/kv/kvserver/batcheval/cmd_end_transaction.go` line 573 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/94939#-NP37XRuAXcF-nQszm-m:-NP37XRuAXcF-nQszm-n:bwzhnau) ([raw file](https://github.com/cockroachdb/cockroach/blob/f426a48ebd3f11dbd191938762cf8c466a44d7e4/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L573)):*
> ```Go
> 
> 	remainingLockSpans := args.LockSpans
> 	var span roachpb.Span
> ```

Why declare `span` with this scope? It doesn't seem to be used outside of `f`, unless I'm missing something.

EDIT: I see that we're using this for the error wrapping. If that's the case, then I think we should just push the `errors.Wrapf` into the closure. There are only 4 error-handling paths. This gives us the opportunity to specialize the error text for each.
___
*[`pkg/kv/kvserver/batcheval/cmd_end_transaction.go` line 648 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/94939#-NP3aWzD6KpbeA6cCglr:-NP3aWzD6KpbeA6cCgls:b-23pztb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f426a48ebd3f11dbd191938762cf8c466a44d7e4/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L648)):*
> ```Go
> 	}
> 
> 	numKeys, _, _, err := storage.MVCCPaginate(ctx, maxKeys, 0, false, f)
> ```

Could you add `/* <param name> */` comments for the literal values passed in here?
___
*[`pkg/storage/mvcc.go` line 4091 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94939#-NOwdiqE4l6ZxrOnnUKV:-NP3aSIi-otAi-2bQ-GN:bkd8r3j) ([raw file](https://github.com/cockroachdb/cockroach/blob/36d75d53f24efaf5d2af9ee82a02327ba87c20ae/pkg/storage/mvcc.go#L4091)):*
<details><summary><i>Previously, KaiSun314 (Kai Sun) wrote…</i></summary><blockquote>

Hmm that's true. I have implemented one possible solution: `MVCCPaginate` will take in an `allowEmpty` parameter. If `allowEmpty` is true, then the `resumeReason` assertion will not be checked for the `targetBytes` limit (the `maxKeys` limit will still be checked regardless of `allowEmpty`). I was wondering if this would be okay?
</blockquote></details>

This seems reasonable to me.
___
*[`pkg/storage/mvcc.go` line 4148 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/94939#-NP371YFC5U3LIrXCcKE:-NP371YFC5U3LIrXCcKF:b5l1iut) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba839035a5a9358c0d37ef8495381be635a19513/pkg/storage/mvcc.go#L4148)):*
> ```Go
> 			}
> 		}
> 		if resumeReason == kvpb.RESUME_KEY_LIMIT {
> ```

Consider changing this to a switch-case statement so that you can exhaustively test all of the handled resume reasons (`RESUME_KEY_LIMIT`, `RESUME_BYTE_LIMIT`, `0`) and then assert against the unhandled reasons.

**Review by nvb — APPROVED** [review]
:lgtm: thanks Kai!

bors r=nvanbenschoten

> Reviewed 3 of 3 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94939#-:-NPEIpKFC_naaeHgUZgc:bpgtnyv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @KaiSun314)

**Comment by KaiSun314** [comment]
Thank you so much for the review and for merging, Nathan!

**Pull request merged**
