### PR TITLE
metamorphic: Increase test surface area, run many more operations

### PR DESCRIPTION
**Pull request by itsbilal**
This PR contains the following major changes (all in separate commits):

1) A move from on-disk to memFS and a move from 1,000 operations per run to 100,000 to take advantage of the faster performance of memFS
2) Addition of savepoints and txn aborts
3) A move from 2 standard 1 random configs to 18 standard and 10 random configs

Implements a large part of #70935, but not all of it. Remaining changes will be
in a future PR.

Fallout of discussion in #69891.

Release notes: None.

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
I'm trying to remember why this metamorphic test is not often broken due to the fact that there is no mutual exclusion due to latching -- iirc, there can be multiple concurrent batches with Puts for the same key. Perhaps it is because the latest one to do a `batch_commit` wins, but that should not work with separated intents since we'll end up with multiple intents.

> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-:-MlohT4l7bb6q5wxHTaY:b-2my0u2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[pkg/storage/metamorphic/operands.go, line 274 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-MloclHB8qiydVEQnLdJ:-MloclHB8qiydVEQnLdK:bfoshqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a330435cc88b466a6a589ddfa133e3e4bdeb8fc7/pkg/storage/metamorphic/operands.go#L274)):*
> ```Go
> func (s *savepointGenerator) get(args []string) string {
> 	id := txnID(args[len(args)-1])
> 	n := s.rng.Intn(s.txnGenerator.openSavepoints[id])
> ```

is it guaranteed that `openSavepoints` has an entry for `id`? What does this int value represent -- the number of open savepoints? A code comment would help.
___
*[pkg/storage/metamorphic/operations.go, line 458 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-Mlofxi4CxphARwXMHJ6:-Mlofxi4CxphARwXMHJ7:b-qmq666) ([raw file](https://github.com/cockroachdb/cockroach/blob/a330435cc88b466a6a589ddfa133e3e4bdeb8fc7/pkg/storage/metamorphic/operations.go#L458)):*
> ```Go
> 	m         *metaTestRunner
> 	id        txnID
> 	savepoint int
> ```

What does this `savepoint` field represent, given that `run` is trying to generate a savepoint based on `txn.Sequence`? The index into t.m.openSavepoints?
___
*[pkg/storage/metamorphic/operations.go, line 815 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-Mlo_c9GD3ZmQACiSXEE:-Mlo_c9GD3ZmQACiSXEF:b-nrza0n) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d752a1ecac82d6f44ddb0a3b199f94a6ff85d76/pkg/storage/metamorphic/operations.go#L815)):*
> ```Go
> 			}
> 		},
> 		dependentOps: func(m *metaTestRunner, args ...string) (results []opReference) {
> ```

was this always unnecessary? same question below.

**Review by itsbilal — COMMENTED** [review]
TFTR!

I added a `txnKeyGenerator` to generate keys unused by other writers for this txn. In the long run we need a key manager, but this sticks to the existing operand generator semantics so I added it. Thanks! This test reliably passes now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-:-Mlzn4vh92VfaGy7FjeI:b-jypbpf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @sumeerbhola)

___
*[pkg/storage/metamorphic/operands.go, line 274 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-MloclHB8qiydVEQnLdJ:-Mlznl7R0dJb5nwx5Xxu:bx7w1ee) ([raw file](https://github.com/cockroachdb/cockroach/blob/9874d4a8ee452a34ea506696e8f9cd90fc632f4f/pkg/storage/metamorphic/operands.go#L274)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is it guaranteed that `openSavepoints` has an entry for `id`? What does this int value represent -- the number of open savepoints? A code comment would help.
</blockquote></details>

Added a comment. Basically, the `get` method only gets called when the `count` for this type of operand is `> 0`. 
___
*[pkg/storage/metamorphic/operations.go, line 458 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-Mlofxi4CxphARwXMHJ6:-MlznyW94uOp8zvYLLIq:bmtp1ay) ([raw file](https://github.com/cockroachdb/cockroach/blob/9874d4a8ee452a34ea506696e8f9cd90fc632f4f/pkg/storage/metamorphic/operations.go#L458)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

What does this `savepoint` field represent, given that `run` is trying to generate a savepoint based on `txn.Sequence`? The index into t.m.openSavepoints?
</blockquote></details>

Yes, the index into `t.m.openSavepoints`. 
___
*[pkg/storage/metamorphic/operations.go, line 815 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-Mlo_c9GD3ZmQACiSXEE:-Mlzr6qY-2NVJk9mruTb:b5n9xlt) ([raw file](https://github.com/cockroachdb/cockroach/blob/acc7306d86eaf315111843a2a4d6c5aa4a98e055/pkg/storage/metamorphic/operations.go#L815)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

was this always unnecessary? same question below.
</blockquote></details>

Yeah, as we weren't using that variable. Should I go around cleaning this up?

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r5, 1 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71290)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[pkg/storage/metamorphic/operands.go, line 315 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-MmJvmnsB9ATAEGnpbr1:-MmJvmnsB9ATAEGnpbr2:b-wwwpgz) ([raw file](https://github.com/cockroachdb/cockroach/blob/fee2a21e53baa079f9bcbe4c287a7a514f190f1f/pkg/storage/metamorphic/operands.go#L315)):*
> ```Go
> 	}
> 
> 	openKeys := t.inUseKeys[txn]
> ```

why are we looking only at in use keys for the txn passed as parameter. Don't we need to look across all txns?
And do we need to bar the full set of in-use keys or only the ones for which we have open batches? If its the latter, could you add a TODO to generalize?

I suspect some of my questions would be answered with more code comments, including more field-level comments in structs like `txnGenerator`.
___
*[pkg/storage/metamorphic/operands.go, line 341 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-MmJxPr36_H-sVEAHLs_:-MmJxPr36_H-sVEAHLsa:b-x8098i) ([raw file](https://github.com/cockroachdb/cockroach/blob/fee2a21e53baa079f9bcbe4c287a7a514f190f1f/pkg/storage/metamorphic/operands.go#L341)):*
> ```Go
> 		span.EndKey = endKey
> 	}
> 	writtenKeys := t.inUseKeys[txn]
> ```

Do we really need the complexity of the following code for performance or could we just append the new key and call sort.
___
*[pkg/storage/metamorphic/operations.go, line 458 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-Mlofxi4CxphARwXMHJ6:-MmJxjYrE0uKlRdghYka:b72c90w) ([raw file](https://github.com/cockroachdb/cockroach/blob/9874d4a8ee452a34ea506696e8f9cd90fc632f4f/pkg/storage/metamorphic/operations.go#L458)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Yes, the index into `t.m.openSavepoints`. 
</blockquote></details>

Can you add a code comment. Similarly txnRollbackSavepointOp.savepoint could use a field-level comment.

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71290)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[pkg/storage/metamorphic/operands.go, line 315 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-MmJvmnsB9ATAEGnpbr1:-MmOCxkBAR7VQB8NJUUY:b-k06353) ([raw file](https://github.com/cockroachdb/cockroach/blob/fee2a21e53baa079f9bcbe4c287a7a514f190f1f/pkg/storage/metamorphic/operands.go#L315)):*
It would be closer to latching if we barred across all txns. But since different txns write different intents under separated intents, this gets us deterministic behaviour with weaker constraints. I'm okay with implementing either.

> And do we need to bar the full set of in-use keys or only the ones for which we have open batches? If its the latter, could you add a TODO to generalize?

We actually bar writes on all writers, not just batches, so it's already general. Maybe the name `trackWriteOnBatch` is confusing as it is only partially gated on the writer being a batch. I renamed it to `trackTransactionalWrite` now.
___
*[pkg/storage/metamorphic/operands.go, line 341 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-MmJxPr36_H-sVEAHLs_:-MmODVyMBFIJubYWnmwv:bgx0jyb) ([raw file](https://github.com/cockroachdb/cockroach/blob/fee2a21e53baa079f9bcbe4c287a7a514f190f1f/pkg/storage/metamorphic/operands.go#L341)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Do we really need the complexity of the following code for performance or could we just append the new key and call sort.
</blockquote></details>

Done. No we didn't need it, I just optimized it without realizing.

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71290)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @sumeerbhola)

___
*[pkg/storage/metamorphic/operands.go, line 341 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-MmJxPr36_H-sVEAHLs_:-MmODi6c6qd4XZqL6nJb:b-poimmf) ([raw file](https://github.com/cockroachdb/cockroach/blob/fee2a21e53baa079f9bcbe4c287a7a514f190f1f/pkg/storage/metamorphic/operands.go#L341)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Done. No we didn't need it, I just optimized it without realizing.
</blockquote></details>

Scratch that - submitted too soon. I think it's still worth having as we will still need the ability to merge spans. We could do a sort + dedup/merge step, but I like the current code as it's clearer on what's being replaced and by what.
___
*[pkg/storage/metamorphic/operations.go, line 458 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-Mlofxi4CxphARwXMHJ6:-MmOFBYSBK0CHxQPCyYz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9874d4a8ee452a34ea506696e8f9cd90fc632f4f/pkg/storage/metamorphic/operations.go#L458)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add a code comment. Similarly txnRollbackSavepointOp.savepoint could use a field-level comment.
</blockquote></details>

Done.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71290)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[pkg/storage/metamorphic/operands.go, line 315 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-MmJvmnsB9ATAEGnpbr1:-Mmu4G3pAiRoOs-lcdIf:b-ctsjv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/fee2a21e53baa079f9bcbe4c287a7a514f190f1f/pkg/storage/metamorphic/operands.go#L315)):*
> But since different txns write different intents under separated intents, this gets us deterministic behaviour with weaker constraints. 

Do you mean this is allowing two intents to be present for a key? If yes, have you seen any tests where such a sequence is generated -- I am curious what error is returned, if any?
___
*[pkg/storage/metamorphic/operands.go, line 237 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-Mmu5s5PCvDvr24yjTgH:-Mmu5s5PCvDvr24yjTgI:b-jy3xi0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f06d9fb0714a91859f5bd62ab6115003836859e/pkg/storage/metamorphic/operands.go#L237)):*
> ```Go
> type txnID string
> 
> type writtenKey struct {
> ```

writtenKeySpan?
___
*[pkg/storage/metamorphic/operands.go, line 340 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-Mmu5xr43t8r06jl9LVt:-Mmu5xr43t8r06jl9LVu:bf59jjl) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f06d9fb0714a91859f5bd62ab6115003836859e/pkg/storage/metamorphic/operands.go#L340)):*
> ```Go
> }
> 
> func (t *txnGenerator) addWrittenKey(
> ```

addWrittenKeySpan?
___
*[pkg/storage/metamorphic/operands.go, line 348 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-Mmu6ZGXCRn2H6Lr7gUn:-Mmu6ZGXCRn2H6Lr7gUo:bqsmuvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f06d9fb0714a91859f5bd62ab6115003836859e/pkg/storage/metamorphic/operands.go#L348)):*
> ```Go
> 		span.EndKey = endKey
> 	}
> 	writtenKeys := t.inUseKeys[txn]
> ```

// start is the earliest span that either contains key, or if there is no such span is the first span beyond key. end is the earliest span that is beyond endKey.  
___
*[pkg/storage/metamorphic/operands.go, line 363 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-Mmu737d2WJAWVkZAZ7r:-Mmu737d2WJAWVkZAZ7s:bxe04ig) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f06d9fb0714a91859f5bd62ab6115003836859e/pkg/storage/metamorphic/operands.go#L363)):*
> ```Go
> 		t.inUseKeys[txn] = writtenKeys
> 		return
> 	}
> ```

// start == end implies that the span cannot contain start, and by definition it is beyond end. So [key, endKey) does not overlap with an existing span and needs to be placed before start.
___
*[pkg/storage/metamorphic/operands.go, line 376 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-Mmu7WYQE9b2HYTFpyDQ:-Mmu7WYQE9b2HYTFpyDR:bcn0x7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f06d9fb0714a91859f5bd62ab6115003836859e/pkg/storage/metamorphic/operands.go#L376)):*
> ```Go
> 	} else if start > end {
> 		panic(fmt.Sprintf("written keys not in sorted order: %d > %d", start, end))
> 	}
> ```

// INVARIANT: start < end. The start span may or may not contain key. And we know end > 0.
// We will be merging existing spans, and need to compute which spans to merge and what keys to use for the resulting span.
___
*[pkg/storage/metamorphic/operands.go, line 377 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-Mmu7oyW3CygbnMPAX_d:-Mmu7oyW3CygbnMPAX_e:bh1ugds) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f06d9fb0714a91859f5bd62ab6115003836859e/pkg/storage/metamorphic/operands.go#L377)):*
> ```Go
> 		panic(fmt.Sprintf("written keys not in sorted order: %d > %d", start, end))
> 	}
> 	if writtenKeys[start].key.Key.Compare(key) < 0 {
> ```

// The start span contains key. So use the start key of the start span since it will result in the wider span.
___
*[pkg/storage/metamorphic/operands.go, line 379 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-Mmu9DLRDJ0D9TYsuZyq:-Mmu9DLRDJ0D9TYsuZyr:b4bk8iy) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f06d9fb0714a91859f5bd62ab6115003836859e/pkg/storage/metamorphic/operands.go#L379)):*
> ```Go
> 	if writtenKeys[start].key.Key.Compare(key) < 0 {
> 		span.Key = writtenKeys[start].key.Key
> 	}
> ```

// Else, span.Key is equal to key which is the wider span. Note that no span overlaps with key so we are not extending this into the span at start-1.

Comment before start of next if-block
// The span at end-1 may end at a key less or greater than endKey.
___
*[pkg/storage/metamorphic/operands.go, line 380 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-Mmu9mUuAXUz8QPdfSxu:-Mmu9mUv7jkHypPom9DL:b-yhhirs) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f06d9fb0714a91859f5bd62ab6115003836859e/pkg/storage/metamorphic/operands.go#L380)):*
> ```Go
> 		span.Key = writtenKeys[start].key.Key
> 	}
> 	if writtenKeys[end-1].key.EndKey.Compare(endKey) > 0 {
> ```

// ends at a key greater than endKey, so construct the wider span.
___
*[pkg/storage/metamorphic/operands.go, line 385 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-Mmu9sCKBGb3U3KRVNn9:-Mmu9sCKBGb3U3KRVNnA:bi60zox) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f06d9fb0714a91859f5bd62ab6115003836859e/pkg/storage/metamorphic/operands.go#L385)):*
> ```Go
> 	writtenKeys[start] = writtenKey{
> 		key:    span,
> 		writer: w,
> ```

where do we check that we are not replacing a different writer when merging these spans?
___
*[pkg/storage/metamorphic/operations.go, line 210 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-MmuAJB54TL7J9UnAlnz:-MmuAJB54TL7J9UnAlo-:b-maukdk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f06d9fb0714a91859f5bd62ab6115003836859e/pkg/storage/metamorphic/operations.go#L210)):*
> ```Go
> 		Key: m.key,
> 	})
> 	txn.LockSpans, _ = roachpb.MergeSpans(&newLockSpans)
> ```

can you replace these sequence of 4 statements that end with MergeSpans with a function call. It seems to repeat many times.

**Review by itsbilal — COMMENTED** [review]
TFTR! Added the missing comments. Also added a 5th commit that uses the global seed, for consistency with other cockroach tests.

> Dismissed @sumeerbhola from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-:-MmyMehs2OoDO9lk--rj:b-fjhs3c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @sumeerbhola)

___
*[pkg/storage/metamorphic/operands.go, line 315 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-MmJvmnsB9ATAEGnpbr1:-MmxRrNkETKp38WeCRem:b-l95iv0) ([raw file](https://github.com/cockroachdb/cockroach/blob/fee2a21e53baa079f9bcbe4c287a7a514f190f1f/pkg/storage/metamorphic/operands.go#L315)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> But since different txns write different intents under separated intents, this gets us deterministic behaviour with weaker constraints. 

Do you mean this is allowing two intents to be present for a key? If yes, have you seen any tests where such a sequence is generated -- I am curious what error is returned, if any?
</blockquote></details>

Took a look, the second `mvcc_put` returns a conflicting intent error:


```
mvcc_init_put(engine, t56, "ikhvclnlsskegs"/106, lfgvr) -> ok
... // t56 remains open, t59 opens
mvcc_put(engine, t59, "ikhvclnlsskegs"/106, yxstwkix) -> error: conflicting intents on "ikhvclnlsskegs"
```
___
*[pkg/storage/metamorphic/operands.go, line 237 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-Mmu5s5PCvDvr24yjTgH:-MmxLl9AD5G1ohen4-z9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f06d9fb0714a91859f5bd62ab6115003836859e/pkg/storage/metamorphic/operands.go#L237)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

writtenKeySpan?
</blockquote></details>

Done.
___
*[pkg/storage/metamorphic/operands.go, line 340 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-Mmu5xr43t8r06jl9LVt:-MmxLmWW7UERl3zR8kaF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f06d9fb0714a91859f5bd62ab6115003836859e/pkg/storage/metamorphic/operands.go#L340)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

addWrittenKeySpan?
</blockquote></details>

Done.
___
*[pkg/storage/metamorphic/operands.go, line 348 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-Mmu6ZGXCRn2H6Lr7gUn:-MmxW69cEIiUs6aqImPV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f06d9fb0714a91859f5bd62ab6115003836859e/pkg/storage/metamorphic/operands.go#L348)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

// start is the earliest span that either contains key, or if there is no such span is the first span beyond key. end is the earliest span that is beyond endKey.  
</blockquote></details>

Done.
___
*[pkg/storage/metamorphic/operands.go, line 363 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-Mmu737d2WJAWVkZAZ7r:-MmxXOHH6zfNimCvfFZy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f06d9fb0714a91859f5bd62ab6115003836859e/pkg/storage/metamorphic/operands.go#L363)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

// start == end implies that the span cannot contain start, and by definition it is beyond end. So [key, endKey) does not overlap with an existing span and needs to be placed before start.
</blockquote></details>

Done.
___
*[pkg/storage/metamorphic/operands.go, line 376 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-Mmu7WYQE9b2HYTFpyDQ:-MmxWO_06ODaZcy59PcJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f06d9fb0714a91859f5bd62ab6115003836859e/pkg/storage/metamorphic/operands.go#L376)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

// INVARIANT: start < end. The start span may or may not contain key. And we know end > 0.
// We will be merging existing spans, and need to compute which spans to merge and what keys to use for the resulting span.
</blockquote></details>

Done.
___
*[pkg/storage/metamorphic/operands.go, line 377 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-Mmu7oyW3CygbnMPAX_d:-MmxXEMoEuKrHawnP77a:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f06d9fb0714a91859f5bd62ab6115003836859e/pkg/storage/metamorphic/operands.go#L377)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

// The start span contains key. So use the start key of the start span since it will result in the wider span.
</blockquote></details>

Done.
___
*[pkg/storage/metamorphic/operands.go, line 379 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-Mmu9DLRDJ0D9TYsuZyq:-MmxXDzlCNqfq8OVWmPJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f06d9fb0714a91859f5bd62ab6115003836859e/pkg/storage/metamorphic/operands.go#L379)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

// Else, span.Key is equal to key which is the wider span. Note that no span overlaps with key so we are not extending this into the span at start-1.

Comment before start of next if-block
// The span at end-1 may end at a key less or greater than endKey.
</blockquote></details>

Done.
___
*[pkg/storage/metamorphic/operands.go, line 380 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-Mmu9mUuAXUz8QPdfSxu:-MmxXDi2C_xZgEQFdNy4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f06d9fb0714a91859f5bd62ab6115003836859e/pkg/storage/metamorphic/operands.go#L380)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

// ends at a key greater than endKey, so construct the wider span.
</blockquote></details>

Done.
___
*[pkg/storage/metamorphic/operands.go, line 385 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-Mmu9sCKBGb3U3KRVNn9:-MmxWc0A47zkDPUyLHM-:b-bob30f) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f06d9fb0714a91859f5bd62ab6115003836859e/pkg/storage/metamorphic/operands.go#L385)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

where do we check that we are not replacing a different writer when merging these spans?
</blockquote></details>

This is a calling/generating time contract. This method just blindly overwrites whatever was passed in. Conflicting operations are supposed to check `inUseKeys` before an operation is even generated, and once it's generated (assuming no conflict), we call this function. I'll clarify that here.
___
*[pkg/storage/metamorphic/operations.go, line 210 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-MmuAJB54TL7J9UnAlnz:-MmyMda0CRmz5rVmzRB7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f06d9fb0714a91859f5bd62ab6115003836859e/pkg/storage/metamorphic/operations.go#L210)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you replace these sequence of 4 statements that end with MergeSpans with a function call. It seems to repeat many times.
</blockquote></details>

Done.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 5 files at r18, 3 of 3 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71290#-:-Mn1hlfX9BtAhC5Fat5F:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens and @sumeerbhola)

**Pull request merged**
