### PR TITLE
docs: new RFC to propose an observability server

### PR DESCRIPTION
**Pull request by knz**
Link to the formatted RFC: 
https://github.com/knz/cockroach/blob/20210222-rfc-obs-server/docs/RFCS/20210222_observability_server.md

### CODE REVIEW

**Comment by knz** [comment]
NB: I have integrated all the prompts for further discussions from @tbg, @andy-kimball , @lunevalex and @irfansharif in the draft. The discussions remain open.

**Review by petermattis — COMMENTED** [review]
Glad to see this getting fleshed out. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65141#-:-M_g9Mc46rihJY7YhSKF:b-orp4a4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[docs/RFCS/20210222_observability_server.md, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65141#-M_g8CGH9QgLSMGQ_PdC:-M_g8CGH9QgLSMGQ_PdD:b8zdxmd) ([raw file](https://github.com/cockroachdb/cockroach/blob/287f5ed55ed2a2979a97b984df95879106b70bf0/docs/RFCS/20210222_observability_server.md#L23)):*
> ```Markdown
> *This proposal solves an ancestral misdesign in
> CockroachDB: the monitoring APIs and dashboards should never have been
> built within the db nodes. A monitoring system is worthless if it is
> ```

Worthless is a bit of an overstatement. Certainly there are deficiencies with the current structure, and I'm thumbs-up on a separate observability server, but the current system is better than nothing which is what worthless implies.
___
*[docs/RFCS/20210222_observability_server.md, line 161 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65141#-M_g9XOS3lGhu0zWsA7o:-M_g9XOS3lGhu0zWsA7p:b-nz0id6) ([raw file](https://github.com/cockroachdb/cockroach/blob/287f5ed55ed2a2979a97b984df95879106b70bf0/docs/RFCS/20210222_observability_server.md#L161)):*
> ```Markdown
>   - Log files (until we remove log file retrieval from DB APIs)
> 
> - Whenever local data is unavailable, they forward the HTTP API request
> ```

How does the observability server know when local data is unavailable? For example, the "hot ranges" info changes over time. What if the observability server has that data as of a minute ago? Is that fresh enough to serve, or does it need to contact the DB nodes? Perhaps this is discussed elsewhere and I just didn't notice.
___
*[docs/RFCS/20210222_observability_server.md, line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65141#-M_gAAZZCpDH24MFSsYO:-M_gAAZZCpDH24MFSsYP:b-l90lyp) ([raw file](https://github.com/cockroachdb/cockroach/blob/287f5ed55ed2a2979a97b984df95879106b70bf0/docs/RFCS/20210222_observability_server.md#L169)):*
> ```Markdown
> 
> Additionally, **the data on disk is partitioned with the cluster ID and
> tenant ID as partitioning key**. This makes it possible to use a single
> ```

How are you thinking the local data will be stored? For log files there is an obvious format. What about for SQL statement storage, hot ranges, etc? Would you want to use Pebble for storage?

**Review by abarganier — COMMENTED** [review]
Thanks for the writeup, I like the proposal. I have a few thoughts/questions, but overall lgtm. I'm looking forward to making this a reality!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65141#-:-M_gVaho4vGHdWrRZapH:bhsoou4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[docs/RFCS/20210222_observability_server.md, line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65141#-M_gNQBs6xLhmHhPZII6:-M_gNQBs6xLhmHhPZII7:bla059r) ([raw file](https://github.com/cockroachdb/cockroach/blob/287f5ed55ed2a2979a97b984df95879106b70bf0/docs/RFCS/20210222_observability_server.md#L103)):*
> ```
> The observability data would be stored locally to the new server and
> would not be stored in the cluster being monitored. Because the
> ```
Is this to say that if CRDB is running with the obs. server turned on, it'd free up the space on the node used to store this data after its deemed that a successful pull of the data has occurred/it's safe to do so? 

We should probably note somewhere in the RFC some "worst case scenarios" and their potential impact if the obs. server fails, considering things won't be replicated. 
___
*[docs/RFCS/20210222_observability_server.md, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65141#-M_gU5YL6q2axfFzgcOS:-M_gU5YM21DIhoiN_1LQ:bcmqimy) ([raw file](https://github.com/cockroachdb/cockroach/blob/287f5ed55ed2a2979a97b984df95879106b70bf0/docs/RFCS/20210222_observability_server.md#L110)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> (NB: each instance pulls data to itself, independently from any other
> intents. We do not need coordination. We do not care much about the
> copies being out of sync because the data is still going to be useful
> for troubleshooting anyway—as long as they maintain a timestamp of
> their most recent successful sync.)
> ```
</details>

Any thoughts on how the monitoring flow for the obs. servers themselves would work? I assume they'll still provide metrics of their own.
___
*[docs/RFCS/20210222_observability_server.md, line 268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65141#-M_gW0TY3abpNPiX6RxN:-M_gW0TY3abpNPiX6RxO:b-jk5jtj) ([raw file](https://github.com/cockroachdb/cockroach/blob/287f5ed55ed2a2979a97b984df95879106b70bf0/docs/RFCS/20210222_observability_server.md#L268)):*
> ```
> (Irfan) What if a cluster needs help but did not run an obs server?
> ```
I assume we'll maintain the existing facilities as well? Or will it eventually be a requirement to run an obs. server to gain access to the full suite of debug features?
___
*[docs/RFCS/20210222_observability_server.md, line 286 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65141#-M_gRtYb7IMHBfdCjgsP:-M_gRtYb7IMHBfdCjgsQ:b-h3hepc) ([raw file](https://github.com/cockroachdb/cockroach/blob/287f5ed55ed2a2979a97b984df95879106b70bf0/docs/RFCS/20210222_observability_server.md#L286)):*
> ```
> The CC intrusion software must evolve to start observability servers
> alongside CockroachDB nodes and configure the `--join` flag and TLS
> certificates.
> ```
How do you imagine looking to customers? Something like an option in CC to include an additional node to run the obs. server on, which would cost extra?

Daydreaming here, but could it be possible some day for an observability server to be "multi-tenant" to help offset this cost on customers? Multiple dedicated customers could share access to a single obs. server (per-region for locality) which enforces what's visible depending on who the client is.

**Review by tbg — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65141)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @petermattis)

___
*[docs/RFCS/20210222_observability_server.md, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65141#-M_tA2Ag1tN4hi3g0CjE:-M_tA2Ag1tN4hi3g0CjF:bw3lshx) ([raw file](https://github.com/cockroachdb/cockroach/blob/287f5ed55ed2a2979a97b984df95879106b70bf0/docs/RFCS/20210222_observability_server.md#L137)):*
> ```Markdown
> service, see section "Deployment recommendations" below).
> 
> It accepts the same `--join` flag as `cockroach start` to learn about
> ```

The join flag is just an entry point. Does this mean that the obs server discovers all nodes through the nodes it can reach through the join flag? I assume this just means hitting the `Nodes` endpoint. The KV layer does not know the SQL pod processes though. You say below that from the credentials attached to a request to the obs server it will figure out where the tenant is, and I don't see how this will work without additional ingredients that I haven't seen mentioned here.
___
*[docs/RFCS/20210222_observability_server.md, line 161 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65141#-M_g9XOS3lGhu0zWsA7o:-M_tAWGq4XAnUr7BUdky:bn3iw5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/287f5ed55ed2a2979a97b984df95879106b70bf0/docs/RFCS/20210222_observability_server.md#L161)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

How does the observability server know when local data is unavailable? For example, the "hot ranges" info changes over time. What if the observability server has that data as of a minute ago? Is that fresh enough to serve, or does it need to contact the DB nodes? Perhaps this is discussed elsewhere and I just didn't notice.
</blockquote></details>

Had the same thought. I think it will have to be some mix of setting a reasonable staleness policy (10 minutes?), showing prominently when the data was taken, and making it easy to bypass the cache.
___
*[docs/RFCS/20210222_observability_server.md, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65141#-M_tAg8j12w1KmgLhXdw:-M_tAg8j12w1KmgLhXdx:b-2gvjrv) ([raw file](https://github.com/cockroachdb/cockroach/blob/287f5ed55ed2a2979a97b984df95879106b70bf0/docs/RFCS/20210222_observability_server.md#L163)):*
> ```Markdown
> - Whenever local data is unavailable, they forward the HTTP API request
>   to one of the DB nodes, chosen randomly (see note below). This is used e.g. to
>   enable/disable CPU profiling cluster-wide, enable the "logspy", etc.
> ```

(nevermind, this is already in "discussions")

Logspy is per-node, as are other endpoints (stacks etc), so it will be necessary to target a node specifically, ideally by providing the nodeID to pass through to. This was a major pain yesterday in an incident on CC where we ended up having to open 20 browser tabs in the hope of the round-robin balancer hitting the right backend :sweat_smile: 
In certain scenarios (network partition, unhealthy nodes) it will also be helpful to pin the node even if the output of the endpoint "should be" cluster-wide.
___
*[docs/RFCS/20210222_observability_server.md, line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65141#-M_gAAZZCpDH24MFSsYO:-M_tBMkE9CYgB1mBHhif:b5ccrxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/287f5ed55ed2a2979a97b984df95879106b70bf0/docs/RFCS/20210222_observability_server.md#L169)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

How are you thinking the local data will be stored? For log files there is an obvious format. What about for SQL statement storage, hot ranges, etc? Would you want to use Pebble for storage?
</blockquote></details>

An interesting observation that I continue to make with `debug.zip` is that it is really unfortunate that we are pulling things out of SQL tables and saving only the cli output, which makes further processing of the data very cumbersome, but this is often what you need to do (yesterday, given `crdb_internal.cluster_queries`, I needed to parse out certain fields that postceded the query string - not fun). To the extent that it is reasonable, we should strive to preserve the ability to interact with SQL data programmatically. In my dream land, the obs server serves SQL and has copies of the relevant tables / views of the original cluster. I realize that this will be too much to ask for at first, but it's worth writing a paragraph or two about how things that *don't* come from an RPC get served from the obs server. I understand that when CRDB hands out JSON, we hand out JSON from the obs server. But how do I look at `crdb_internal.cluster_queries` and siblings from the obs server?
___
*[docs/RFCS/20210222_observability_server.md, line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65141#-M_tCkbe7edVA9u2sGOK:-M_tCkbf4ljKH2OK6pKh:b-iafbei) ([raw file](https://github.com/cockroachdb/cockroach/blob/287f5ed55ed2a2979a97b984df95879106b70bf0/docs/RFCS/20210222_observability_server.md#L201)):*
> ```Markdown
>   quite useful in debug.zip powered debugging, yet I think it might be
>   quite expensive to be retrieving this state periodically in the
>   background.
> ```

Coming back to this, I think it's also fair to not pull everything on the face of the earth periodically, at least at first. We can start with the essentials and build up from there, and everything else will be pulled when it's needed (&then cached)
___
*[docs/RFCS/20210222_observability_server.md, line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65141#-M_tD2uT6XL_LkweI3QD:-M_tD2uT6XL_LkweI3QE:bx31imt) ([raw file](https://github.com/cockroachdb/cockroach/blob/287f5ed55ed2a2979a97b984df95879106b70bf0/docs/RFCS/20210222_observability_server.md#L218)):*
> ```Markdown
> 
>   (knz) think we want the list of nodes to be passed explicitly and
>   not use any auto-discovery. The particular reason why I care is
> ```

Isn't that making on-prem deployments a non-starter? Is that out of scope anyway? Given any entry point into the cluster, we can use the `Nodes` RPC (though we shold probably use a gossip-based cousin) to pull the full list, so not sure what we're getting out of this requirement to supply the full list.

Note also my other comment above about discovering tenants, which I think is currently not possible. The KV keyspace has a list of tenants, but it cannot locate tenants and in particularly we have an invariant about KV never reaching out to tenants (not that you'd need it, just mentioning it).
___
*[docs/RFCS/20210222_observability_server.md, line 266 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65141#-M_tDqR7-ib02_UZcWtv:-M_tDqR7-ib02_UZcWtw:boglfsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/287f5ed55ed2a2979a97b984df95879106b70bf0/docs/RFCS/20210222_observability_server.md#L266)):*
> ```Markdown
> 1. (Irfan) For large clusters, this could still be data in the order
>    of gigabytes which makes transferring things to us over
>    call/tickets painfully slow and error prone. How to deal with this?
> ```

Probably same as today, we allow options to limit what is included.

**Comment by knz** [comment]
@andreimatei what's the PR number for the RFC for the new thing? Or do you want to take over this PR?

**Comment by knz** [comment]
Closing in favor of the new thing, which will get its public doc in time.

**Pull request closed without merging**
