### PR TITLE
sql: lift duplicate param name check in UDFs into optbuilder

### PR DESCRIPTION
**Pull request by yuzefovich**
The opt build step is the right place to do this verification (this will also make it easier to extend the check for plpgsql in the follow up work).

Additionally, this commit removes the redundant duplicate param name check from the schemachanger code.

Epic: None

Release note: None

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119742#-:-NrlNq4k2Ke7s7c1tONp:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119742#-:-NrlSzKdBQfYBVHrSGBR:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Review by mgartner — COMMENTED** [review]
Thanks for cleaning this up! 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119742#-:-NsAgt5rEdPUoPGZutxG:bl5754u)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained

**Pull request merged**
