### PR TITLE
cmd/skipped-tests: utility to post skipped tests to slack

### PR DESCRIPTION
**Pull request by petermattis**
Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
This will need to be hooked up to a nightly TeamCity run. Need to pass the `--slack-token` flag, but we can just use the token already configured for various roachtest nightly runs. I don't feel strongly about the formatting, so feel free to bikeshed, though I'd also be happy to simply hand this off.

**Review by jordanlewis — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51770)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by petermattis** [comment]
TFTR! We can iterate on improvements in subsequent PRs.

bors r+

**Comment by yuzefovich** [comment]
bors crashed, so here is a courtesy ping.

bors r+

**Pull request merged**
