### PR TITLE
distsql: transition distsql physical planner to use SQLInstanceIDs instead of NodeIDs

### LINKED ISSUE #49596: distsql: transition distsql physical planner to use SQLInstanceIDs instead of NodeIDs
The distsql physical planner currently uses `roachpb.NodeID`s to identify nodes. With multitenancy work, use of `roachpb.NodeID` is slowly being phased out in favor of a `SQLInstanceID` (https://github.com/cockroachdb/cockroach/issues/48009). The distsql physical planner should be changed to use `SQLInstanceID`s.

This work is not urgent since for phase 2, tenants will only be executing single-node queries and `SQLInstanceID`s can be cast to `NodeID`s for the time being, but it is cleanup that should be done after that phase.

### PR DESCRIPTION
**Pull request by rharding6373**
Refactors DistSQL and some related functions to use `SQLInstanceID`
instead of `NodeID` for multi-tenant support.

Fixes: #49596

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Great work, that was fast!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75259#-:-MtuqtSN8rgCxCovvbOc:b-heyy8e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rharding6373, and @stevendanna)

___
*[pkg/base/node_id.go, line 237 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75259#-Mtun2Gf7e7aYTeJVwiM:-Mtun2Gf7e7aYTeJVwiN:bobvk9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/17cd6eaa9eb1e730a77f7ddb294f11ebfc750ac5/pkg/base/node_id.go#L237)):*
> ```Go
> // Otherwise, returns zero and false.
> func (c *SQLIDContainer) OptionalSQLInstanceID() (SQLInstanceID, bool) {
> 	if (*NodeIDContainer)(c).sqlInstance {
> ```

Should this be `!sqlInstance`?
___
*[pkg/base/node_id.go, line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75259#-MtunYCtBp8LdvlJBUYY:-MtunYCtBp8LdvlJBUYZ:b7d2cbz) ([raw file](https://github.com/cockroachdb/cockroach/blob/17cd6eaa9eb1e730a77f7ddb294f11ebfc750ac5/pkg/base/node_id.go#L246)):*
> ```Go
> // the optionally supplied GitHub issues) if the ID is not present.
> func (c *SQLIDContainer) OptionalSQLInstanceIDErr(issue int) (SQLInstanceID, error) {
> 	if (*NodeIDContainer)(c).sqlInstance {
> ```

ditto, or better yet use `c.OptionalSQLInstanceID()`
___
*[pkg/sql/distsql_physical_planner.go, line 881 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75259#-MtuoWHq7Sn2YalaGCGT:-MtuoWHq7Sn2YalaGCGU:b-nhcpzn) ([raw file](https://github.com/cockroachdb/cockroach/blob/17cd6eaa9eb1e730a77f7ddb294f11ebfc750ac5/pkg/sql/distsql_physical_planner.go#L881)):*
> ```Go
> }
> 
> // SpanPartition is the intersection between a set of spans for a certain
> ```

We could make this a bit more general: "SpanPartition associates a subset of spans with a specific SQL instance, chosen to have the most efficient access to those spans. In the single-tenant case, the instance is the one running on the same node as the leaseholder for those spans".
___
*[pkg/sql/distsql_physical_planner.go, line 885 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75259#-MtuoT7p32vPKRl9y3Le:-MtuoT7p32vPKRl9y3Lf:bd5467s) ([raw file](https://github.com/cockroachdb/cockroach/blob/17cd6eaa9eb1e730a77f7ddb294f11ebfc750ac5/pkg/sql/distsql_physical_planner.go#L885)):*
> ```Go
> // instance.
> type SpanPartition struct {
> 	SqlInstanceID base.SQLInstanceID
> ```

[nit] SQLInstanceID
___
*[pkg/sql/execstats/traceanalyzer.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75259#-Mtupbzs2XvAAAEqmeqR:-Mtupbzs2XvAAAEqmeqS:bzgzpso) ([raw file](https://github.com/cockroachdb/cockroach/blob/17cd6eaa9eb1e730a77f7ddb294f11ebfc750ac5/pkg/sql/execstats/traceanalyzer.go#L25)):*
> ```Go
> )
> 
> type processorStats struct {
> ```

[nit] maybe we can get rid of this now and just use `ComponentStats` directly
___
*[pkg/sql/physicalplan/physical_plan.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75259#-Mtuqh1R3tYah22BtjJa:-Mtuqh1R3tYah22BtjJb:bd5467s) ([raw file](https://github.com/cockroachdb/cockroach/blob/17cd6eaa9eb1e730a77f7ddb294f11ebfc750ac5/pkg/sql/physicalplan/physical_plan.go#L34)):*
> ```Go
> type Processor struct {
> 	// Node where the processor must be instantiated.
> 	SqlInstanceID base.SQLInstanceID
> ```

[nit] SQLInstanceID

**Review by knz — COMMENTED** [review]
This is very nice, thanks

> Reviewed 11 of 40 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75259#-:-MtxPiG38Ecn57iX_5Vu:br5iowb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373 and @stevendanna)

___
*[pkg/sql/execinfrapb/api.proto, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75259#-MtxP_w-0jHkSOsd6won:-MtxP_w-0jHkSOsd6woo:buhulm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/17cd6eaa9eb1e730a77f7ddb294f11ebfc750ac5/pkg/sql/execinfrapb/api.proto#L69)):*
> ```protobuf
> message FlowSpec {
>   optional bytes flow_id = 1 [(gogoproto.nullable) = false,
>     (gogoproto.customname) = "FlowID",
> ```

nit: why did you de-indent this and the below?
___
*[pkg/sql/execinfrapb/data.proto, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75259#-MtxPd5O94ciBJY3ewYN:-MtxPd5O94ciBJY3ewYO:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/17cd6eaa9eb1e730a77f7ddb294f11ebfc750ac5/pkg/sql/execinfrapb/data.proto#L106)):*
> ```protobuf
>   // For SYNC_RESPONSE streams, the ID is unused.
>   optional int32 stream_id = 2 [(gogoproto.nullable) = false,
>     (gogoproto.customname) = "StreamID",
> ```

ditto

**Review by rharding6373 — COMMENTED** [review]
TFTRs! I fixed some of the issues brought up by the comments and some issues found in CI.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75259#-:-Mty61xV9SnqNfAdZ6Q5:b-59mlyu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @RaduBerinde, and @stevendanna)

___
*[pkg/sql/distsql_physical_planner.go, line 881 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75259#-MtuoWHq7Sn2YalaGCGT:-Mtxlqrw2emuS_qWksJw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/17cd6eaa9eb1e730a77f7ddb294f11ebfc750ac5/pkg/sql/distsql_physical_planner.go#L881)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We could make this a bit more general: "SpanPartition associates a subset of spans with a specific SQL instance, chosen to have the most efficient access to those spans. In the single-tenant case, the instance is the one running on the same node as the leaseholder for those spans".
</blockquote></details>

Done.
___
*[pkg/sql/distsql_physical_planner.go, line 885 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75259#-MtuoT7p32vPKRl9y3Le:-Mtxm0P14Mt7vH-JGD7L:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/17cd6eaa9eb1e730a77f7ddb294f11ebfc750ac5/pkg/sql/distsql_physical_planner.go#L885)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] SQLInstanceID
</blockquote></details>

Done.
___
*[pkg/sql/execinfrapb/api.proto, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75259#-MtxP_w-0jHkSOsd6won:-MtxmKuiCnTGF5GzsJwO:b-f4l371) ([raw file](https://github.com/cockroachdb/cockroach/blob/17cd6eaa9eb1e730a77f7ddb294f11ebfc750ac5/pkg/sql/execinfrapb/api.proto#L69)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: why did you de-indent this and the below?
</blockquote></details>

Apparently this is what the auto formatter wants. Note that the other protos in this file are formatted this way, too. 
___
*[pkg/sql/execinfrapb/data.proto, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75259#-MtxPd5O94ciBJY3ewYN:-MtxmtwGBvWs7Mx8tG6s:b-q64pkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/17cd6eaa9eb1e730a77f7ddb294f11ebfc750ac5/pkg/sql/execinfrapb/data.proto#L106)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

See above.
___
*[pkg/sql/execstats/traceanalyzer.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75259#-Mtupbzs2XvAAAEqmeqR:-MtxoUoU2ow2Z0IU6tdJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/17cd6eaa9eb1e730a77f7ddb294f11ebfc750ac5/pkg/sql/execstats/traceanalyzer.go#L25)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] maybe we can get rid of this now and just use `ComponentStats` directly
</blockquote></details>

Done.
___
*[pkg/sql/physicalplan/physical_plan.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75259#-Mtuqh1R3tYah22BtjJa:-MtxneqlBU44irFxpyFv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/17cd6eaa9eb1e730a77f7ddb294f11ebfc750ac5/pkg/sql/physicalplan/physical_plan.go#L34)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] SQLInstanceID
</blockquote></details>

Done.
___
*[pkg/base/node_id.go, line 237 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75259#-Mtun2Gf7e7aYTeJVwiM:-Mtxl25s4Pv6mB3CfB7G:b-ingpxk) ([raw file](https://github.com/cockroachdb/cockroach/blob/17cd6eaa9eb1e730a77f7ddb294f11ebfc750ac5/pkg/base/node_id.go#L237)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Should this be `!sqlInstance`?
</blockquote></details>

Ah, actually I did make a copy paste mistake, but the other way. I was really trying to make a wrapper around `OptionalNodeID` that returned the node id cast as a `SQLInstanceID`. I reverted this and did casting at the relevant call sites instead in `server.go` so it's a true refactor.

We may need to add something like this back in later.
___
*[pkg/base/node_id.go, line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75259#-MtunYCtBp8LdvlJBUYY:-MtxlWIj9YWrt6_TV50k:b-aemgpi) ([raw file](https://github.com/cockroachdb/cockroach/blob/17cd6eaa9eb1e730a77f7ddb294f11ebfc750ac5/pkg/base/node_id.go#L246)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

ditto, or better yet use `c.OptionalSQLInstanceID()`
</blockquote></details>

Removed after revision.

**Review by RaduBerinde — APPROVED** [review]
:lgtm: once the TestTraceAnalyzer tests are happy

> Reviewed 21 of 40 files at r1, 30 of 30 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75259#-:-Mu2dFzA659zN2e5um8d:b-ab7bzl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @stevendanna)

**Review by RaduBerinde — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75259)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz, @rharding6373, and @stevendanna)

___
*[pkg/sql/execstats/traceanalyzer.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75259#-Mu2eGK84htl8Q_EY1pj:-Mu2eGK84htl8Q_EY1pk:bc82q6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c04e8c4fe573fd3c4f16052610e49d45d369514/pkg/sql/execstats/traceanalyzer.go#L33)):*
> ```Go
> type streamStats struct {
> 	// TODO(radu): this field redundant with stats.Component.SQLInstanceID.
> 	originNodeID      roachpb.NodeID
> ```

Maybe it's cleaner to keep this here and remove the TODO. Which one is reflected in the ComponentStats is really a matter of implementation (specifically whether the origin or the destination is emitting the stats).
___
*[pkg/sql/execstats/traceanalyzer.go, line 88 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75259#-Mu2e00dEK8u3hiG_FRi:-Mu2e00dEK8u3hiG_FRj:buiuutj) ([raw file](https://github.com/cockroachdb/cockroach/blob/62863f7dbf22dd517461dfb2267de3c4a2958a0f/pkg/sql/execstats/traceanalyzer.go#L88)):*
> ```Go
> 						stats:             &execinfrapb.ComponentStats{},
> 					}
> 					a.streamStats[stream.StreamID].stats.Component.SQLInstanceID = sqlInstanceID
> ```

`stats` gets set in `AddTrace`, I don't think this ends up doing anything.

**Review by stevendanna — APPROVED** [review]
LGTM!

**Comment by rharding6373** [comment]
TFTRs!

bors r+

**Pull request merged**
