### PR TITLE
opt: add TPC-E tests to xform

### PR DESCRIPTION
**Pull request by DrewKimball**
This patch adds the TPC-E queries to the xform tests. Every TPC-E
query is included with the exception of duplicates. The queries
are organized into 12 transactions, as in the official TPC-E docs.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50396#-:-MAl_w7N-e_iazg0kbSC:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[pkg/sql/opt/xform/testdata/external/tpce-no-stats, line 850 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50396#-MAlYvAd0Zj4pgKUxO7A:-MAlYvAd0Zj4pgKUxO7B:b-70e7kb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c678aca182507f4c02c965fdbfaccd82220da7f6/pkg/sql/opt/xform/testdata/external/tpce-no-stats#L850)):*
> ```
> 
> 
> # Q1 Version 2
> ```

Is this a manually optimized version? If so, maybe add a comment and mention the execution times of each one.
___
*[pkg/sql/opt/xform/testdata/external/tpce-no-stats, line 1981 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50396#-MAlZifG5-nwOjvu1khh:-MAlZifG5-nwOjvu1khi:b-8bgwg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c678aca182507f4c02c965fdbfaccd82220da7f6/pkg/sql/opt/xform/testdata/external/tpce-no-stats#L1981)):*
> ```
>                 └── filters (true)
> 
> # Q19
> ```

repeat of Q19
___
*[pkg/sql/opt/xform/testdata/external/tpce-no-stats, line 2624 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50396#-MAlZx1z1_jJfpU6kHUG:-MAlZx1z1_jJfpU6kHUH:bao0f9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/c678aca182507f4c02c965fdbfaccd82220da7f6/pkg/sql/opt/xform/testdata/external/tpce-no-stats#L2624)):*
> ```
>            └── hs_qty:6 + 10 [as=hs_qty_new:7, outer=(6), immutable]
> 
> # Q17
> ```

skipped Q16?
___
*[pkg/sql/opt/xform/testdata/external/tpce-no-stats, line 3216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50396#-MAl_9Ki0Zntk6u6TXXn:-MAl_9KjA7F6EepVjnJw:b-5r9zcx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c678aca182507f4c02c965fdbfaccd82220da7f6/pkg/sql/opt/xform/testdata/external/tpce-no-stats#L3216)):*
> ```
>            └── trade.t_chrg:12::FLOAT8 [as=t_chrg:45, outer=(12), immutable]
> 
> # Q1 Version 2
> ```

Ditto above -- add a comment
___
*[pkg/sql/opt/xform/testdata/external/tpce-no-stats, line 3707 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50396#-MAl_Le2A3pwUzXz5FRK:-MAl_Le2A3pwUzXz5FRL:b-89a4l7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c678aca182507f4c02c965fdbfaccd82220da7f6/pkg/sql/opt/xform/testdata/external/tpce-no-stats#L3707)):*
> ```
>       └── trade.t_trade_price:11::FLOAT8 [as=t_trade_price:36, outer=(11), immutable]
> 
> # Q10 Version 2
> ```

Ditto
___
*[pkg/sql/opt/xform/testdata/external/tpce-no-stats, line 3836 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50396#-MAl_SM42Q7l5cJoSpZ3:-MAl_SM42Q7l5cJoSpZ4:b-5dwtez) ([raw file](https://github.com/cockroachdb/cockroach/blob/c678aca182507f4c02c965fdbfaccd82220da7f6/pkg/sql/opt/xform/testdata/external/tpce-no-stats#L3836)):*
> ```
> opt
> SELECT
> 	ap_acl
> ```

[nit] remove the tabs here and below

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50396)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/opt/xform/testdata/external/tpce-no-stats, line 850 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50396#-MAlYvAd0Zj4pgKUxO7A:-MBKztUU3NJCDMGhTGBm:b48r9gj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c678aca182507f4c02c965fdbfaccd82220da7f6/pkg/sql/opt/xform/testdata/external/tpce-no-stats#L850)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Is this a manually optimized version? If so, maybe add a comment and mention the execution times of each one.
</blockquote></details>

I've been having some trouble getting tpce to run on my matching, but I'll add execution times once I figure it out.
___
*[pkg/sql/opt/xform/testdata/external/tpce-no-stats, line 1981 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50396#-MAlZifG5-nwOjvu1khh:-MBKz9GI9X2gyCpM96bD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c678aca182507f4c02c965fdbfaccd82220da7f6/pkg/sql/opt/xform/testdata/external/tpce-no-stats#L1981)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

repeat of Q19
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/external/tpce-no-stats, line 2624 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50396#-MAlZx1z1_jJfpU6kHUG:-MBKzTPMC-0oPaJKUSxC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c678aca182507f4c02c965fdbfaccd82220da7f6/pkg/sql/opt/xform/testdata/external/tpce-no-stats#L2624)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

skipped Q16?
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/external/tpce-no-stats, line 3216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50396#-MAl_9Ki0Zntk6u6TXXn:-MBL-IhXBLM4q7Gsyoks:bb3zxql) ([raw file](https://github.com/cockroachdb/cockroach/blob/c678aca182507f4c02c965fdbfaccd82220da7f6/pkg/sql/opt/xform/testdata/external/tpce-no-stats#L3216)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Ditto above -- add a comment
</blockquote></details>

Comment done. As with the other one, I'll add execution times when I can.
___
*[pkg/sql/opt/xform/testdata/external/tpce-no-stats, line 3707 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50396#-MAl_Le2A3pwUzXz5FRK:-MBL-Yh-3mZOWEiFVKf4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c678aca182507f4c02c965fdbfaccd82220da7f6/pkg/sql/opt/xform/testdata/external/tpce-no-stats#L3707)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/external/tpce-no-stats, line 3836 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50396#-MAl_SM42Q7l5cJoSpZ3:-MBKzgjNBpe_zdqgwMbv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c678aca182507f4c02c965fdbfaccd82220da7f6/pkg/sql/opt/xform/testdata/external/tpce-no-stats#L3836)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] remove the tabs here and below
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm: I think you can go ahead and merge this. You can add the times later once you get it running.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50396#-:-MBLIgDa1IQYt8B8iR-L:bjvxdei)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
