### PR TITLE
settings: switch to only sync/atomic updates

### LINKED ISSUE #15200: settings: remove the cache
Off a comment from @dt on #15190: if all the settings use async updates
(and we can make string settings do to via `atomic.Value`) then the settings cache can be removed.

### PR DESCRIPTION
**Pull request by dt**
this does away with the layered maps and the rwmutex and instead just updates values in place.

Fixes #15200.

### CODE REVIEW

**Comment by knz** [comment]
Many elegance. Such deletions. Wow. Amaze.

:lgtm_strong: 

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15218#-:-KiBaDkU1_57Cgps1L3j:bxgxv9l)*

**Comment by dt** [comment]
I'd also like to rename `accessors.go` back to `registry.go` but that made reviewable sad, so I'll hold off on that for now.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15218#-:-KiBaPuGL2yuOXaxExy-:b2qbde3)*

**Comment by tamird** [comment]
Go for it.

---

Reviewed 9 of 11 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15218#-:-KiBciaujY-S21QU0byF:b-x2mi87)*

**Comment by dt** [comment]
Done.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15218#-:-KiBd26ivVYWLebWAa9i:b-896fix)*

**Comment by knz** [comment]
Merging myself since dt is helping with logistics.

**Pull request merged**
