### PR TITLE
sql: add more info to advanceInfo

### PR DESCRIPTION
**Pull request by andreimatei**
advanceInfo is the structure produced by the connection state machine
when processing events. Its main purpose is to tell the connExecutor
what statement to execute next (the next one, the same one again, jump
to the next batch). This patch add another nugget of information - a
"transaction event" telling the connEx if a couple of things happened to
the SQL transaction as a result of the state machine event that was just
processed. The idea is that these txn events will be used to know if we
should run or clear transactional state maintained by the connEx, such
as the schema changes. The txn events can be seen as a much-distilled
version of the state machine events, much more suitable for consumption
by the connEx.

Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
extracted from #22277

**Comment by knz** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22367#-:-L4c2sJSAh6-nJGLbapB:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
The code here LGTM, but I'm still not sure why we're setting txnState on advanceInfo. What decisions is the state going to help inform? 

---

Reviewed 2 of 5 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22367#-:-L4c389Td5565dAHyWxZ:b-eq0tk6)*

**Comment by andreimatei** [comment]
I believe I got a verbal LGTM for the N-man. Merging.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22367#-:-L4nOySg4g_Tu5T0yuDc:bihvkfs)*

**Pull request merged**
