### PR TITLE
storage,kv: rationalize the NewUnIndexedBatch interface and implement…

### PR DESCRIPTION
**Pull request by sumeerbhola**
…ation

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
Nit: `unindexed` is one word according to Google. So `s/UnIndexed/Unindexed/g` and `s/unIndexed/unindexed/g`. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59541#-:-MS8glXE8jfBzjNBdpn7:b-mew5tn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @nvanbenschoten)

**Review by nvb — APPROVED** [review]
> So s/UnIndexed/Unindexed/g and s/unIndexed/unindexed/g

+1, I had been thinking the same thing.

:lgtm: This all looks great. Thanks for the follow-up PR.

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59541#-:-MS8o1Lq3Y5WdCg9Vb3P:bx3kdiv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal)

**Review by sumeerbhola — COMMENTED** [review]
Fixed all the un-indexed and UnIndexed. Goland underlining what it thinks are camel case violations often trips me up.

TFTRs!  

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59541#-:-MS8woID14ctsFU-S-sr:b-ljgahd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal)

**Pull request merged**
