### PR TITLE
pick up cmux memory corruption fix

### LINKED ISSUE #4501: circleci: failed tests (13026): TestSSLEnforcement
The following test appears to have failed:

[#13026](https://circleci.com/gh/cockroachdb/cockroach/13026):

```
I0219 00:14:43.056491 398 server.go:2161  http: TLS handshake error from 127.0.0.1:37769: tls: first record does not look like a TLS handshake
I0219 00:14:43.137235 398 server.go:2161  http: TLS handshake error from 127.0.0.1:37775: tls: first record does not look like a TLS handshake
I0219 00:14:43.175861 398 server.go:2161  http: TLS handshake error from 127.0.0.1:37778: tls: first record does not look like a TLS handshake
I0219 00:14:43.211279 398 server.go:2161  http: TLS handshake error from 127.0.0.1:37779: tls: first record does not look like a TLS handshake
I0219 00:14:43.241915 398 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- FAIL: TestSSLEnforcement (1.06s)
	authentication_test.go:149: [28]: expected success=true, got err=Post https://127.0.0.1:38866/sql/Execute: stream error: stream ID 13; STREAM_CLOSED
=== RUN   TestParseStores
I0219 00:14:43.251055 398 server/context.go:156  can't read available memory from cgroups (open /sys/fs/cgroup/memory/memory.limit_in_bytes: no such file or directory), setting default rocksdb cache size to 30193MB (half of system memory)
I0219 00:14:43.252844 398 server/context.go:156  can't read available memory from cgroups (open /sys/fs/cgroup/memory/memory.limit_in_bytes: no such file or directory), setting default rocksdb cache size to 30193MB (half of system memory)
I0219 00:14:43.253174 398 server/context.go:226  1 storage engine(s) specified
I0219 00:14:43.253637 398 server/context.go:156  can't read available memory from cgroups (open /sys/fs/cgroup/memory/memory.limit_in_bytes: no such file or directory), setting default rocksdb cache size to 30193MB (half of system memory)
I0219 00:14:43.253802 398 server/context.go:226  2 storage engine(s) specified
I0219 00:14:43.254353 398 server/context.go:156  can't read available memory from cgroups (open /sys/fs/cgroup/memory/memory.limit_in_bytes: no such file or directory), setting default rocksdb cache size to 30193MB (half of system memory)
I0219 00:14:43.254957 398 server/context.go:226  1 storage engine(s) specified
I0219 00:14:43.255016 398 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--
W0219 00:15:00.926073 398 kv/send.go:200  error reply: server/node.go:559: node 1 stopped
I0219 00:15:00.926367 398 client/db.go:485  failed batch: failed to send RPC: too many errors encountered (1 of 1 total): server/node.go:559: node 1 stopped
W0219 00:15:00.926467 398 ts/db.go:96  error writing time series data: failed to send RPC: too many errors encountered (1 of 1 total): server/node.go:559: node 1 stopped
I0219 00:15:00.927796 398 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestMetricsRecording (2.17s)
FAIL
FAIL	github.com/cockroachdb/cockroach/server	21.159s
=== RUN   TestNodeStatusMonitor
--- PASS: TestNodeStatusMonitor (0.02s)
=== RUN   TestNodeStatusRecorder
--- PASS: TestNodeStatusRecorder (0.05s)
=== RUN   TestRuntimeStatRecorder
I0219 00:14:57.245969 424 server/status/runtime.go:137  runtime stats: 4 goroutines, 3.38MiB active, 50000000.00cgo/sec, 899340.00/374720.00 %(u/s)time, 287973.69 %gc (3x)
--- PASS: TestRuntimeStatRecorder (0.00s)
=== RUN   TestNodeEventFeed
--- PASS: TestNodeEventFeed (0.01s)
=== RUN   TestServerNodeEventFeed

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by tamird**
The fix was submitted in soheilhy/cmux#17.

Fixes #4501.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4648)

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM

**Comment by RaduBerinde** [comment]
LGTM!

**Comment by bdarnell** [comment]
LGTM, although I'd have put the other commits in separate PRs.

We had protobuf decoding errors in raft prior to introducing `cmux`. Could our previous custom solution have had the same problem or was this unique to `cmux`?

**Comment by tamird** [comment]
This problem is unique to cmux - our custom solution didn't implement anything this low-level.

I had forgotten that we observed those issues prior to the introduction of cmux, and thought that this was the culprit. I'll investigate it further.

**Pull request merged**
