### PR TITLE
changefeedccl: run CHANGEFEEDs via distsql

### PR DESCRIPTION
**Pull request by danhhz**
One or more ChangeAggregator processors watch table data for changes. These
transform the changed kvs into changed rows and either emit them to a sink
(such as kafka) or, if there is no sink, forward them in columns 1,2,3 (where
they will be eventually returned directly via pgwire). In either case,
periodically a span will become resolved as of some timestamp, meaning that
no new rows will ever be emitted at or below that timestamp. These span-level
resolved timestamps are emitted as a marshalled `jobspb.ResolvedSpan` proto
in column 0.

The flow will always have exactly one ChangeFrontier processor which all the
ChangeAggregators feed into. It collects all span-level resolved timestamps
and aggregates them into a changefeed-level resolved timestamp, which is the
minimum of the span-level resolved timestamps. This changefeed-level resolved
timestamp is emitted into the changefeed sink (or returned to the gateway if
there is no sink) whenever it advances. ChangeFrontier also updates the
progress of the changefeed's corresponding system job.

@arjunravinarayan and/or @jordanlewis I tried to keep all the changes that weren't strictly distsql-related to a minimum in this PR. There is a bit of churn in sink.go that was hard to avoid, but I'll have @nvanbenschoten take a general pass so y'all can stay focused on the distributed flow. The first two commits are #28319 and you can ignore them entirely.

### CODE REVIEW

**Review by rjnn — CHANGES_REQUESTED** [review]
Reviewing commits one by one, please bear with the series of updates.

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-:-LJt03TQ0tBh7JZLZ6VL:b-cmu8ab)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/changefeedccl/span_frontier.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-LJsu3OF0cnZxPaHQbJg:-LJsu3OF0cnZxPaHQbJh:bnui2y2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fa14eee4d5d996e5dab5a82d64c2ea7ccfba33b/pkg/ccl/changefeedccl/span_frontier.go#L52)):*
> ```Go
> // Entries are sorted based on their timestamp such that the oldest will rise to
> // the top of the heap.
> type spanFrontierHeap []*spanFrontierEntry
> ```

I'm confused by your heap implementation. Doesn't `Push` and `Pop` need to do additional work to bubble up the next highest element into the top position?

Also from my reading you need a `Fix()` implementation, but you don't have one. If you don't actually need a `heap.Interface`, then you could just avoid the `interface{}` conversations entirely and specify it to only take `spanFrontier`s.
___
*[pkg/ccl/changefeedccl/span_frontier.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-LJsxX9lAdSbpwNjH1if:-LJsxX9lAdSbpwNjH1ig:b-b9sz1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fa14eee4d5d996e5dab5a82d64c2ea7ccfba33b/pkg/ccl/changefeedccl/span_frontier.go#L117)):*
> ```Go
> 		s.idAlloc++
> 		if err := s.tree.Insert(e, true /* fast */); err != nil {
> 			panic(err)
> ```

A `todo` to refactor this panic away would be nice.
___
*[pkg/ccl/changefeedccl/span_frontier_test.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-LJsxvXWC0cocvvKx_H2:-LJsxvXWC0cocvvKx_H3:bscuur7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fa14eee4d5d996e5dab5a82d64c2ea7ccfba33b/pkg/ccl/changefeedccl/span_frontier_test.go#L32)):*
> ```Go
> 	return buf.String()
> }
> ```

You might want to test the heap separately as well. I don't think your heap maintains itself correctly.

**Review by rjnn — CHANGES_REQUESTED** [review]
Reviewed r3. A healthy amount of :dog: :man_scientist: in my reviews, but all the distsql stuff looks correct.

> Reviewed 3 of 6 files at r2, 22 of 22 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-:-LJt2e_X8fJ7cKhxAf9C:b-64zzze)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/changefeedccl/changefeed_dist.go, line 107 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-LJt3Hf-CbknQT10ba4M:-LJt3Hf-CbknQT10ba4N:b-ncq4e2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3421b16605606449c9cfde00b8cf93a0b9a8a465/pkg/ccl/changefeedccl/changefeed_dist.go#L107)):*
> ```Go
> 
> 	gatewayNodeID := execCfg.NodeID.Get()
> 	changeAggregatorProcs := []distsqlplan.Processor{{
> ```

why is there only one `changeAggregatorProc`? I would have thought you'd want one per span (and perhaps split the spans if they cross range boundaries, akin to what `createTableReaders` does.
___
*[pkg/ccl/changefeedccl/changefeed_dist.go, line 180 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-LJt3WrT7NjwdA4Vz-6f:-LJt3WrT7NjwdA4Vz-6g:b-k1vuop) ([raw file](https://github.com/cockroachdb/cockroach/blob/3421b16605606449c9cfde00b8cf93a0b9a8a465/pkg/ccl/changefeedccl/changefeed_dist.go#L180)):*
> ```Go
> }
> 
> type changeAggregator struct {
> ```

I'd split the processors into their own file, if only because planning code and processor implementations are just so different
___
*[pkg/ccl/changefeedccl/changefeed_dist.go, line 206 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-LJt1IOsBI2q3bSrI2Xn:-LJt1IOsBI2q3bSrI2Xo:b7qg11b) ([raw file](https://github.com/cockroachdb/cockroach/blob/3421b16605606449c9cfde00b8cf93a0b9a8a465/pkg/ccl/changefeedccl/changefeed_dist.go#L206)):*
> ```Go
> 	resolvedSpanBuf encDatumRowBuffer
> }
> ```

It would be great if you add all the interface assertions that this struct obeys, since it's outside the package structure that makes it clear. i.e.
`var _ Processor = &changeAggregator{}`
`var _ RowSource = &changeAggregator{}`
___
*[pkg/ccl/changefeedccl/changefeed_dist.go, line 288 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-LJt1exNEPHwgo0n3Gp_:-LJt1exNEPHwgo0n3Gpa:b-w5dqxz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3421b16605606449c9cfde00b8cf93a0b9a8a465/pkg/ccl/changefeedccl/changefeed_dist.go#L288)):*
> ```Go
> func (ca *changeAggregator) close() {
> 	// Wait for the poller to finish shutting down.
> 	<-ca.pollerErrCh
> ```

check the error channel for `nil` to indicate graceful shutdown?
___
*[pkg/ccl/changefeedccl/changefeed_dist.go, line 337 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-LJt1yavEQYdJeXG3XJs:-LJt1yavEQYdJeXG3XJt:b6c3fov) ([raw file](https://github.com/cockroachdb/cockroach/blob/3421b16605606449c9cfde00b8cf93a0b9a8a465/pkg/ccl/changefeedccl/changefeed_dist.go#L337)):*
> ```Go
> 			return err
> 		}
> 		ca.resolvedSpanBuf.Push(sqlbase.EncDatumRow{
> ```

I don't know what contract this set of datums is satisfying, so a comment would be very helpful here.
___
*[pkg/ccl/changefeedccl/changefeed_dist.go, line 482 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-LJt2Dv13ybecujrVERi:-LJt2Dv13ybecujrVERj:b-aywao7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3421b16605606449c9cfde00b8cf93a0b9a8a465/pkg/ccl/changefeedccl/changefeed_dist.go#L482)):*
> ```Go
> 			// core changefeed, which returns changed rows directly via pgwire,
> 			// a row with a null resolved_span field is a changed row that needs
> 			// to be forwared to the gateway.
> ```

typo 'forwared'
___
*[pkg/sql/distsqlrun/processors.proto, line 952 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-LJt0n5x1GmOEUOXoNUt:-LJt0n5x1GmOEUOXoNUu:b-t1m1o4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3421b16605606449c9cfde00b8cf93a0b9a8a465/pkg/sql/distsqlrun/processors.proto#L952)):*
> ```protobuf
> 
> // ChangeFrontierSpec is the specification for a processor that receives
> // span-level
> ```

incomplete comment.

**Comment by danhhz** [comment]
I've been thinking since I sent this that things would be cleaner if ChangeAggregator had two outputs, one for rows and one for resolved spans. We could hook the first directly to the gateway and the other to the ChangeFrontier (eliminating the awkward forwarding it has). Thoughts? Anything I should know about the two output stuff?

**Comment by danhhz** [comment]
> I've been thinking since I sent this that things would be cleaner if ChangeAggregator had two outputs, one for rows and one for resolved spans. We could hook the first directly to the gateway and the other to the ChangeFrontier (eliminating the awkward forwarding it has). Thoughts? Anything I should know about the two output stuff?

Scratch that. I was misunderstanding some distsql things. I'm told that I could do something similar by routing the stream to two different places with a custom hash router, but I think I'll leave that for a followup.

**Review by danhhz — COMMENTED** [review]
Thanks for the review! RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-:-LK2mX130IuBCmCMKG1X:b-6sx6b6)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/changefeedccl/changefeed_dist.go, line 107 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-LJt3Hf-CbknQT10ba4M:-LK2hVZw7L0ftTezfd5V:bn3n59d) ([raw file](https://github.com/cockroachdb/cockroach/blob/3421b16605606449c9cfde00b8cf93a0b9a8a465/pkg/ccl/changefeedccl/changefeed_dist.go#L107)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

why is there only one `changeAggregatorProc`? I would have thought you'd want one per span (and perhaps split the spans if they cross range boundaries, akin to what `createTableReaders` does.
</blockquote></details>

Yeah, that's exactly what we'll do for enterprise changefeeds. Leaving it for a followup. This is the logic we'll use for the non-enterprise ones. See the TODO in the godoc for distChangefeedFlow
___
*[pkg/ccl/changefeedccl/changefeed_dist.go, line 180 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-LJt3WrT7NjwdA4Vz-6f:-LK2hV9DE8nvFfDRd4QZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3421b16605606449c9cfde00b8cf93a0b9a8a465/pkg/ccl/changefeedccl/changefeed_dist.go#L180)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

I'd split the processors into their own file, if only because planning code and processor implementations are just so different
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/changefeed_dist.go, line 206 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-LJt1IOsBI2q3bSrI2Xn:-LK2hyRiARImpqefCSBq:b-o6c63k) ([raw file](https://github.com/cockroachdb/cockroach/blob/3421b16605606449c9cfde00b8cf93a0b9a8a465/pkg/ccl/changefeedccl/changefeed_dist.go#L206)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

It would be great if you add all the interface assertions that this struct obeys, since it's outside the package structure that makes it clear. i.e.
`var _ Processor = &changeAggregator{}`
`var _ RowSource = &changeAggregator{}`
</blockquote></details>

I did, actually : - ). Moved them up here since that's clearly where you're expecting them
___
*[pkg/ccl/changefeedccl/changefeed_dist.go, line 288 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-LJt1exNEPHwgo0n3Gp_:-LK2iKdgDcg80s8qYYA7:bhzxigy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3421b16605606449c9cfde00b8cf93a0b9a8a465/pkg/ccl/changefeedccl/changefeed_dist.go#L288)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

check the error channel for `nil` to indicate graceful shutdown?
</blockquote></details>

It'll be context cancelled. Added a comment
___
*[pkg/ccl/changefeedccl/changefeed_dist.go, line 337 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-LJt1yavEQYdJeXG3XJs:-LK2mAJA65Q-ZiJB_N9a:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3421b16605606449c9cfde00b8cf93a0b9a8a465/pkg/ccl/changefeedccl/changefeed_dist.go#L337)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

I don't know what contract this set of datums is satisfying, so a comment would be very helpful here.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/changefeed_dist.go, line 482 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-LJt2Dv13ybecujrVERi:-LK2io_tEh0gN3kFn1e-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3421b16605606449c9cfde00b8cf93a0b9a8a465/pkg/ccl/changefeedccl/changefeed_dist.go#L482)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

typo 'forwared'
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/processors.proto, line 952 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-LJt0n5x1GmOEUOXoNUt:-LK2j20pCjuBylkPBqVk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3421b16605606449c9cfde00b8cf93a0b9a8a465/pkg/sql/distsqlrun/processors.proto#L952)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

incomplete comment.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/span_frontier.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-LJsu3OF0cnZxPaHQbJg:-LK2j2yaDNoE-GL74e-y:b-9y5ihx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fa14eee4d5d996e5dab5a82d64c2ea7ccfba33b/pkg/ccl/changefeedccl/span_frontier.go#L52)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

I'm confused by your heap implementation. Doesn't `Push` and `Pop` need to do additional work to bubble up the next highest element into the top position?

Also from my reading you need a `Fix()` implementation, but you don't have one. If you don't actually need a `heap.Interface`, then you could just avoid the `interface{}` conversations entirely and specify it to only take `spanFrontier`s.
</blockquote></details>

Addressed in #28319
___
*[pkg/ccl/changefeedccl/span_frontier.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-LJsxX9lAdSbpwNjH1if:-LK2jAKN10EKfR_eWA7c:b-9y5ihx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fa14eee4d5d996e5dab5a82d64c2ea7ccfba33b/pkg/ccl/changefeedccl/span_frontier.go#L117)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

A `todo` to refactor this panic away would be nice.
</blockquote></details>

Addressed in #28319
___
*[pkg/ccl/changefeedccl/span_frontier_test.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-LJsxvXWC0cocvvKx_H2:-LK2jCvu0E3PaJENpwd5:b-9y5ihx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fa14eee4d5d996e5dab5a82d64c2ea7ccfba33b/pkg/ccl/changefeedccl/span_frontier_test.go#L32)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

You might want to test the heap separately as well. I don't think your heap maintains itself correctly.
</blockquote></details>

Addressed in #28319

**Comment by danhhz** [comment]
Hey @arjunravinarayan @jordanlewis I hate to ask, but any chance y'all could take another pass at this today? I was hoping to get it merged before the release branch is cut

**Comment by jordanlewis** [comment]
👍

**Review by jordanlewis — COMMENTED** [review]
Okay, I took a look, but this is a pretty big change that I have almost no context on.  I'd say :lgtm: based on the fact that you seem to have followed the DistSQL contract properly, but honestly I didn't have the time today to really give this a thorough review.  Perhaps somebody more familiar with change feeds should review this?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-:-LK8jCbkBt10Nd5CjuU7:ba8xqtq)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by rjnn — DISMISSED** [review]
:lgtm_strong: Looks like it's ready for merging! @jordanlewis r1 and r2 are from another PR, it's just r3 here.

> Reviewed 17 of 17 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-:-LK9QP2RBw718KL0tTHG:b-dhajnu)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/ccl/changefeedccl/changefeed_dist.go, line 107 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-LJt3Hf-CbknQT10ba4M:-LK3GSGPCM4SmckAXtRy:b-70xr3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/3421b16605606449c9cfde00b8cf93a0b9a8a465/pkg/ccl/changefeedccl/changefeed_dist.go#L107)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Yeah, that's exactly what we'll do for enterprise changefeeds. Leaving it for a followup. This is the logic we'll use for the non-enterprise ones. See the TODO in the godoc for distChangefeedFlow
</blockquote></details>

:+1: Sounds good to me.
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-LK9QomT48RalSpHsTKC:-LK9QomT48RalSpHsTKD:b-pw08u3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4eb180476899b006aab6a750feacd4aa315d0b3/pkg/ccl/changefeedccl/changefeed_processors.go#L1)):*
> ```Go
> // Copyright 2018 The Cockroach Authors.
> ```

I didn't take close look at the changes between r3 and r4 since the code movement makes it difficult to look at diffs, but I'm trusting you that there isn't much different between the revisions besides what we explicitly talked about. Otherwise holler with comments and I'll take closer looks there.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28555)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28555#-LK9QomT48RalSpHsTKC:-LK9ct_B5SjBrGf5xvVV:b-lj84cx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4eb180476899b006aab6a750feacd4aa315d0b3/pkg/ccl/changefeedccl/changefeed_processors.go#L1)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

I didn't take close look at the changes between r3 and r4 since the code movement makes it difficult to look at diffs, but I'm trusting you that there isn't much different between the revisions besides what we explicitly talked about. Otherwise holler with comments and I'll take closer looks there.
</blockquote></details>

I moved the bufferSink special case to the constructor, which cleaned it up a bit.

I also had to deal with a merge conflict with the monitoring stuff. Since TrailingMetaCallback doesn't seem to always be called, I had to do some gross stuff with a goroutine to guarantee that the processor always deregisters itself from `cf.metrics.mu.resolved`. There's almost certainly something better to be done here than what I did, but it's not coming to mind (and this is probably good enough to merge and deal with later)

**Pull request merged**
