### PR TITLE
kvserver: observe lease transfer interval in considerRebalance

### PR DESCRIPTION
**Pull request by ajwerner**
This commit plumbs the lease transfer rate limit into the lease transfer which
occurs as a part of rebalancing decision making. The decision about whether a
node should remove itself for the purpose of rebalancing happens at a much
higher rate than the the actual rebalancing. This can lead to massive
oscillations of leaseholders as the calculation on which replica should be
removed in the face of node addition changes dramatically. We utilize
a rate limit in lease transfer decisions to smooth this decision making
elsewhere. This limit however is not utilized currently when deciding to
transfer a lease for the purpose of rebalancing data. This change has
shown very positive impact mitigating these lease transfer storms. See
the commentary on #51867.

Release note (bug fix): Made lease transfers during rebalancing adhere
to the rate limit utilized in other lease transfer cases which eliminates
unexpected lease oscillations when adding a new node.

### CODE REVIEW

**Review by darinpp — APPROVED** [review]
Looks good.

**Comment by ajwerner** [comment]
TFTR!

bors r=darinpp

**Pull request merged**
