### PR TITLE
stats: deep-copy datums during sampling to allow GC of kv batch

### LINKED ISSUE #42331: OOMs on Idle Cluster running rc3
Cluster running rc3, on 6x n1-standard-16 nodes is regularly OOMing on each node, despite the cluster being idle and not under load.

Notes on how to access the cluster and logs from a single node can be found here: https://cockroachdb.zendesk.com/agent/tickets/4057

We're working on collecting a debug zip and profiles as a next step, but it'll likely wait till Monday.

Some graphs below that seemed interesting - low CPU utilization, rapidly increasing memory utilization. No SQL queries or connections. No service latency recorded, but we do see regular multi-second spikes in execution latency. p99 KV transaction duration is multiple seconds, and we do see some lengthy queue processing times (specifically in the replication and raft log queues).

Screen Shot 2019-11-08 at 6 12 38 PM
Screen Shot 2019-11-08 at 6 12 00 PM
Screen Shot 2019-11-08 at 6 09 09 PM
Screen Shot 2019-11-08 at 6 08 57 PM
Screen Shot 2019-11-08 at 6 08 43 PM
Screen Shot 2019-11-08 at 6 08 34 PM
Screen Shot 2019-11-08 at 6 05 03 PM
Screen Shot 2019-11-08 at 6 04 44 PM
Screen Shot 2019-11-08 at 6 04 09 PM

### PR DESCRIPTION
**Pull request by rytaft**
Previously, the `SampleReservoir` would call `EnsureDecoded` on each `EncDatum` from
an input row, and then copy only the `Datum` to a new `EncDatumRow` to remove the
reference to the encoded data from the kv batch. It turns out this was not
enough to fully remove all references to the kv batch, however. For certain
data types (sepecifically key-encoded strings and collated strings), it was
possible that the decoded `Datum` referenced the original encoded kv batch, thus
preventing the garbage collector from deleting it.

This commit fixes the problem by performing a deep copy for certain key-encoded
datums such as `DString` to remove any references to the kv batch and allow the
batch to be garbage collected.

Informs #42331 
Informs #33660

Release note (bug fix): Fixed an out-of-memory error that could occur when
collecting statistics on tables with a string index column.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
I don't know that we confirmed this is the underlying cause for #42331? (although it's definitely the only hypothesis right now). Maybe we should see if they can tr


This might fix #33660 right?

**Comment by RaduBerinde** [comment]
LGTM

I don't know that we confirmed this is the underlying cause for #42331? (although it's definitely the only hypothesis right now). Maybe we should see if they are interested in trying to turn them back on with a custom build.

Do you think this is also the reason for the continued OOMs in #33660? (or it's just the batch size itself)

**Comment by rytaft** [comment]
TFTR! Yea, I'm not 100% sure this will fix it. Changed the message to say "informs" instead. I don't think this is necessarily the fix to #33660, since kv doesn't have a string in the schema, but hopefully #42357 will reduce the flakes there...

**Comment by rytaft** [comment]
Added an explicit check for the encoding so we only copy for key-encoded datums.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42372#-:-LtQrdh8CJozZkSi5NNj:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/stats/row_sampling.go, line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42372#-LtQrPx87RLEsEO69yFJ:-LtQrPx96t9ImZpIq5l2:b-camub4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bc8085aa675159e6e2d688031314812c393f87b/pkg/sql/stats/row_sampling.go#L246)):*
> ```Go
> // deepCopyDatum performs a deep copy for datums such as DString to remove any
> // references to the kv batch and allow the batch to be garbage collected.
> func deepCopyDatum(evalCtx *tree.EvalContext, d tree.Datum) tree.Datum {
> ```

[nit] Add a note here that it's only called for key encodings, in case someone adds another type in the future (which might be need deep-copy with value encoding)

**Review by rytaft — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42372#-:-LtR4u-cE9yFsWtciAYW:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj)

___
*[pkg/sql/stats/row_sampling.go, line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42372#-LtQrPx87RLEsEO69yFJ:-LtR4pCsCHXQtJKTS87s:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bc8085aa675159e6e2d688031314812c393f87b/pkg/sql/stats/row_sampling.go#L246)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Add a note here that it's only called for key encodings, in case someone adds another type in the future (which might be need deep-copy with value encoding)
</blockquote></details>

Done.

**Pull request merged**
