### PR TITLE
roachpb/sql/ui: add mean rows written to Statement Details page

### LINKED ISSUE #67084: Surface the number affected rows in the DB console for statement statistics
Today we have "Rows Read" and we received feedback to also surface the number of "Rows Affected" in the DB console for DML. We should add it to the Statements details page as "Mean rows written" under Mean rows/bytes read. 

Ideally, this row is hidden for SELECT statements and added as a column selector option on the Statement overview page. This column is not shown by default on the Statements overview page but the user can add it via the column selector. 

image
 

Epic: CRDB-9867

### PR DESCRIPTION
**Pull request by lindseyjin**
Resolves #67084

Previously, the Statement Details page did not show the mean rows
written to. We received feedback to surface rows affected.

To address this, we are adding "mean rows written" to non-SELECT
statements. This has been added as a row on the Statement Details
Overview page and on the Execution Stats "Other Execution Stats" table.
A future PR will also add this new metric to the column selector on
the Statements Overview page.

image

image

Release note (ui change): add mean rows written to statement details page

### CODE REVIEW

**Comment by lindseyjin** [comment]
hi! sorry y'all, I somehow closed my [last PR](https://github.com/cockroachdb/cockroach/pull/70321) when I was trying to rebase on upstream. I couldn't figure out how to recover that, so I've created a new one (although let me know if you have any tips if I run into this issue in the future!)

**Review by Azhng — COMMENTED** [review]
> Reviewed 1 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70377)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lindseyjin)

___
*[pkg/roachpb/app_stats.proto, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70377#-Mk2uavT5EavnHwfZDF0:-Mk2uavT5EavnHwfZDF1:boalzrl) ([raw file](https://github.com/cockroachdb/cockroach/blob/c769f07b5db2721baccf0af02215dfdbe0304de9/pkg/roachpb/app_stats.proto#L90)):*
> ```protobuf
>   optional NumericStat rows_read = 16 [(gogoproto.nullable) = false];
> 
>   // RowsWritten collects the number of rows read from disk.
> ```

`s/rows read from/rows written to/`
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 506 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70377#-Mk2v5NPE1usK9X12OoG:-Mk2v5NPE1usK9X12OoH:bpcwos8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c769f07b5db2721baccf0af02215dfdbe0304de9/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L506)):*
> ```XML
>       );
>     const summary = summarize(statement);
>     const notSelectStatement = summary.statement !== "select";
> ```

Reading the function of `summarize()`, I think this would also include statements like `SET CLUSTER SETTINGS ...` even though those statements does not always change stored data on disk.

Also, I feel this `summarize()` function doesn't capture the full picture. We also have `UPSERT` statements that does conditional update/insert operations. 

Additionally, user can do `PREPARE insert_stmt AS INSERT INTO table VALUES ($1)` and then `EXECUTE insert_stmt(...)`, the subsequent `EXECUTE` would also have `mean rows written` stats. 

cc @maryliag  any thoughts on handling these special cases ?

**Review by lindseyjin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70377)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lindseyjin and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 506 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70377#-Mk2v5NPE1usK9X12OoG:-Mk31Nse5bgtI1ptkJiT:b-3pocjj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c769f07b5db2721baccf0af02215dfdbe0304de9/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L506)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Reading the function of `summarize()`, I think this would also include statements like `SET CLUSTER SETTINGS ...` even though those statements does not always change stored data on disk.

Also, I feel this `summarize()` function doesn't capture the full picture. We also have `UPSERT` statements that does conditional update/insert operations. 

Additionally, user can do `PREPARE insert_stmt AS INSERT INTO table VALUES ($1)` and then `EXECUTE insert_stmt(...)`, the subsequent `EXECUTE` would also have `mean rows written` stats. 

cc @maryliag  any thoughts on handling these special cases ?
</blockquote></details>

Hmm, currently the ticket only mentions hiding this metric for SELECT statements. Is the problem that we don't want to show "mean rows written" for any statements that aren't able to modify rows?

**Review by lindseyjin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70377)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @maryliag)

___
*[pkg/roachpb/app_stats.proto, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70377#-Mk2uavT5EavnHwfZDF0:-Mk31nx43iIjy0Vkhqmq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c769f07b5db2721baccf0af02215dfdbe0304de9/pkg/roachpb/app_stats.proto#L90)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

`s/rows read from/rows written to/`
</blockquote></details>

Done.

**Review by maryliag — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70377)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 506 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70377#-Mk2v5NPE1usK9X12OoG:-Mk34lMp2DW8hfwsGCCz:befs1sp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c769f07b5db2721baccf0af02215dfdbe0304de9/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L506)):*
<details><summary><i>Previously, lindseyjin (Lindsey Jin) wrote…</i></summary><blockquote>

Hmm, currently the ticket only mentions hiding this metric for SELECT statements. Is the problem that we don't want to show "mean rows written" for any statements that aren't able to modify rows? 
</blockquote></details>

I had left a previous comment on the other PR, for this here you need to checks: only show if statement type is DML, and if it is DML hide if is select type.
So I would change the `notSelectStatement` const to `showRowsWritten` and its value would be something like this (not sure the right parameter name for SQL Type)
`const showRowsWritten = statement.sqltype === 'DML' and summary.statement !== 'statement'`

and then below you can show `{showRowsWritten && (...`

**Review by lindseyjin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70377)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 506 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70377#-Mk2v5NPE1usK9X12OoG:-Mk3Cxai9E-tWK4Ut4Vs:b-hyzunv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c769f07b5db2721baccf0af02215dfdbe0304de9/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L506)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I had left a previous comment on the other PR, for this here you need to checks: only show if statement type is DML, and if it is DML hide if is select type.
So I would change the `notSelectStatement` const to `showRowsWritten` and its value would be something like this (not sure the right parameter name for SQL Type)
`const showRowsWritten = statement.sqltype === 'DML' and summary.statement !== 'statement'`

and then below you can show `{showRowsWritten && (...`
</blockquote></details>

Done!

Couldn't find if there was an existing enum for sql types, but let me know if one exists!

**Review by maryliag — CHANGES_REQUESTED** [review]
> Reviewed 10 of 14 files at r1, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70377)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @lindseyjin, and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 581 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70377#-Mk7tH1F5ZzLub1QeVcZ:-Mk7tH1F5ZzLub1QeVc_:b-9vvov1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd309c90ee6caf3283a7de62bbc21d379d18a5ed/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L581)):*
> ```XML
>                         <Text>
>                           {formatNumberForDisplay(
>                             stats.rows_written.mean,
> ```

nit: to account for cluster with version where this parameter might not exist, change this to `stats.rows_written?.mean`
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.fixture.ts, line 92 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70377#-Mk7tUAiBq49X7ludWe4:-Mk7tUAiBq49X7ludWe5:bfo5ks1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd309c90ee6caf3283a7de62bbc21d379d18a5ed/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.fixture.ts#L92)):*
> ```XML
>   },
>   rows_written: {
>     mean: 10,
> ```

nit: use a different value from rows read, because during tests we want different values to make sure we're not using a value from a different parameter for example
___
*[pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.fixture.ts, line 208 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70377#-Mk7teL4DY8qrYRbd6nF:-Mk7teL4DY8qrYRbd6nG:btbs4jb) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd309c90ee6caf3283a7de62bbc21d379d18a5ed/pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.fixture.ts#L208)):*
> ```XML
>         squared_diffs: 3.8399999999999994,
>       },
>       rows_written: {
> ```

nit: same as the other comment, change the values of rows written to some other random value different from rows read
___
*[pkg/ui/workspaces/db-console/src/util/appStats.ts, line 85 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70377#-Mk7tnZ9DDNeS4YiGwCm:-Mk7tnZ9DDNeS4YiGwCn:b-jcrnjo) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd309c90ee6caf3283a7de62bbc21d379d18a5ed/pkg/ui/workspaces/db-console/src/util/appStats.ts#L85)):*
> ```XML
>     bytes_read: addNumericStats(a.bytes_read, b.bytes_read, countA, countB),
>     rows_read: addNumericStats(a.rows_read, b.rows_read, countA, countB),
>     rows_written: addNumericStats(a.rows_read, b.rows_read, countA, countB),
> ```

this is suppose to be rows_written, you forgot to change the values inside the function

**Review by lindseyjin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70377)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @maryliag)

___
*[pkg/ui/workspaces/db-console/src/util/appStats.ts, line 85 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70377#-Mk7tnZ9DDNeS4YiGwCm:-Mk83bID5cp9wH4hM0rO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd309c90ee6caf3283a7de62bbc21d379d18a5ed/pkg/ui/workspaces/db-console/src/util/appStats.ts#L85)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

this is suppose to be rows_written, you forgot to change the values inside the function
</blockquote></details>

Done.

**Review by maryliag — APPROVED** [review]
Great work!
:lgtm: 

> Reviewed 1 of 14 files at r1, 2 of 4 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70377#-:-Mk9KGjN-e4g55-XDWxJ:b9dv3vm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

**Review by maryliag — CHANGES_REQUESTED** [review]
Just realized that this metric should also be added to the Execution Stats Tab of the Statement Details. Can you add it there? Just below the read row on the "Other Execution Statistics". table 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70377#-:-Mk9OlRiEFR_--hPBgko:b-8g0jcb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

**Review by lindseyjin — COMMENTED** [review]
got it! do I just need to add this into the "Other Execution Stats" table, or also the "Stats By Node" table?\

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70377#-:-Mk9Pk1b3pTU3LPb2Q_S:bobl2bx)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng and @maryliag)

**Review by maryliag — COMMENTED** [review]
That stats by node is based on the same statement table from the main page, so once you add there on your following task, it will get added on this table too. So don't worry about it on this PR, but on your next one make sure you test on this page

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70377#-:-Mk9QBuL-bWTUJrgD_9u:bqiqfrc)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng and @maryliag)

**Review by lindseyjin — COMMENTED** [review]
Ok, sounds good!
Also, done!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70377#-:-Mk9TCH12iMyAeTXHHQe:b-y8b7k9)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng and @maryliag)

**Review by Azhng — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70377#-:-Mk9xEWj3joN7Zbe0p2Y:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng and @maryliag)

**Review by maryliag — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70377#-:-MkCf_2LAE7rijiMZlAu:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @maryliag)

**Comment by lindseyjin** [comment]
^^ Pushing to resolve merge conflicts

**Pull request merged**
