### PR TITLE
colexec: add comprehensive benchmark of projection operators

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit updates the benchmark of projection operators to run all
interesting combinations of type pairs and binary or comparison
operators. It also extracts the arguments of `RandomVec` test utility
function into a struct and adds a few knobs to that struct as well.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I looked into adding a benchmark for "one-arg-constant" projection variants, but it is quite difficult to trigger those in mixed-type scenarios. I left it as TODO.

**Review by asubiotto — COMMENTED** [review]
> Reviewed 9 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48357)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/projection_ops_test.go, line 493 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48357#-M6_1NPw3OGR3gyMIV38:-M6_1NPw3OGR3gyMIV39:b-wehv3m) ([raw file](https://github.com/cockroachdb/cockroach/blob/51b6c4890cdd279ef099415175df7fefc995b913/pkg/sql/colexec/projection_ops_test.go#L493)):*
> ```Go
> 									)
> 									if err := colexecerror.CatchVectorizedRuntimeError(func() {
> 										projOp, err = createTestProjectingOperator(
> ```

It's confusing to me that this can both panic and return an error. Maybe `createTestProjectingOperator` should panic as well instead of returning an error?
___
*[pkg/sql/colexec/execgen/supported_operators.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48357#-M6_28O56nFBvcPm9W8I:-M6_28O56nFBvcPm9W8J:bjry7g9) ([raw file](https://github.com/cockroachdb/cockroach/blob/51b6c4890cdd279ef099415175df7fefc995b913/pkg/sql/colexec/execgen/supported_operators.go#L1)):*
> ```Go
> // Copyright 2020 The Cockroach Authors.
> ```

Operators is an overloaded term, is there another name we can use for this file?
___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48357#-M6_1goNAXWXE4R4KPMS:-M6_1goNAXWXE4R4KPMT:b-7at9xe) ([raw file](https://github.com/cockroachdb/cockroach/blob/51b6c4890cdd279ef099415175df7fefc995b913/pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go#L18)):*
> ```Go
> 	"text/template"
> 
> 	execgenbase "github.com/cockroachdb/cockroach/pkg/sql/colexec/execgen"
> ```

How come we have this package alias?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48357)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/projection_ops_test.go, line 493 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48357#-M6_1NPw3OGR3gyMIV38:-M6b5Ak_BtAeERzZTR7w:bw1x6hh) ([raw file](https://github.com/cockroachdb/cockroach/blob/51b6c4890cdd279ef099415175df7fefc995b913/pkg/sql/colexec/projection_ops_test.go#L493)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It's confusing to me that this can both panic and return an error. Maybe `createTestProjectingOperator` should panic as well instead of returning an error?
</blockquote></details>

There are two kinds of errors here in play. I added an extensive comment to describe the situation, please let me know if that makes sense.
___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48357#-M6_1goNAXWXE4R4KPMS:-M6b0ENl0LK6qCbJc7We:b8w9743) ([raw file](https://github.com/cockroachdb/cockroach/blob/51b6c4890cdd279ef099415175df7fefc995b913/pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go#L18)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

How come we have this package alias?
</blockquote></details>

Initially I thought that it was because we're in `execgen` folder (but `main` package), but the problem was that we have `execgen` struct defined in this package. Renamed the struct to `execgenTool` and removed the alias.
___
*[pkg/sql/colexec/execgen/supported_operators.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48357#-M6_28O56nFBvcPm9W8I:-M6b039g7vBmdjjNzlJU:b-elbaql) ([raw file](https://github.com/cockroachdb/cockroach/blob/51b6c4890cdd279ef099415175df7fefc995b913/pkg/sql/colexec/execgen/supported_operators.go#L1)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Operators is an overloaded term, is there another name we can use for this file?
</blockquote></details>

Nothing better comes to my mind than `supported_bin_cmp_ops`, renamed.

**Review by asubiotto — APPROVED** [review]
:lgtm: minus the `processorConstructor` comment. I think we can simplify that.

> Reviewed 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48357#-:-M6dIZAcBkokDzaIl7kw:bhh1awm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/projection_ops_test.go, line 507 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48357#-M6dIDeyErzOkRNrUiks:-M6dIDez38dcMfZs76F7:b-al07v5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0c9587fc27d228dbba53b4f6e433f2e4d0c21d6/pkg/sql/colexec/projection_ops_test.go#L507)):*
> ```Go
> 									//    to prohibit the fallback. As a result, a nil-pointer
> 									//    exception will occur, but we will catch it and return as
> 									//    an error for such configuration to be skipped.
> ```

How about instead of wrapping this in a panic catcher to catch the specific nil panic we just use a mock `processorConstructor` implementation that returns an error?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48357)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/colexec/projection_ops_test.go, line 507 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48357#-M6dIDeyErzOkRNrUiks:-M6eXLkE6qMzxZhWMkpL:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0c9587fc27d228dbba53b4f6e433f2e4d0c21d6/pkg/sql/colexec/projection_ops_test.go#L507)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

How about instead of wrapping this in a panic catcher to catch the specific nil panic we just use a mock `processorConstructor` implementation that returns an error?
</blockquote></details>

Good idea, done.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48357#-:-M6efQi-67evkILAEoab:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
