### PR TITLE
rangefeed: de-flake TestUnrecoverableErrors

### LINKED ISSUE #99096: kv/kvclient/rangefeed: TestUnrecoverableErrors failed
kv/kvclient/rangefeed.TestUnrecoverableErrors [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9163467?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9163467?buildTab=artifacts#/) on master @ [b89fa2cc4bc1fb9447ab1009b34b6f354f9618f0](https://github.com/cockroachdb/cockroach/commits/b89fa2cc4bc1fb9447ab1009b34b6f354f9618f0):

```
I230321 07:08:43.109842 3636474 13@kv/kvserver/replicate_queue.go:842  [T1,n1,replicate,s1,r36/1:/Table/3{4-5}] 1866  error processing replica: 0 of 1 live stores are able to take a new replica for the range (1 already has a voter, 0 already have a non-voter); likely not enough nodes in cluster
I230321 07:08:43.757693 2516882 testutils/soon.go:41  [-] 1867  SucceedsSoon: expected internal error
I230321 07:08:43.841709 2541406 jobs/adopt.go:112  [T1,n1] 1868  claimed 2 jobs
I230321 07:08:43.863828 3662753 jobs/adopt.go:261  [T1,n1] 1869  job 102: resuming execution
I230321 07:08:43.863886 3662751 jobs/adopt.go:261  [T1,n1] 1870  job 100: resuming execution
I230321 07:08:43.864392 3662752 jobs/adopt.go:261  [T1,n1] 1871  job 101: resuming execution
E230321 07:08:43.898730 3662753 jobs/adopt.go:225  [T1,n1] 1872  could not run claimed job 102: no resumer is available for AUTO CONFIG RUNNER
I230321 07:08:43.954611 3667907 jobs/registry.go:1494  [T1,n1] 1873  POLL JOBS STATS job 101: stepping through state running
I230321 07:08:43.963774 3668375 jobs/registry.go:1494  [T1,n1] 1874  KEY VISUALIZER job 100: stepping through state running
I230321 07:08:44.108369 3683472 13@kv/kvserver/replicate_queue.go:842  [T1,n1,replicate,s1,r57/1:/Table/5{6-7}] 1875  error processing replica: 0 of 1 live stores are able to take a new replica for the range (1 already has a voter, 0 already have a non-voter); likely not enough nodes in cluster
I230321 07:08:44.758398 2516882 testutils/soon.go:41  [-] 1876  SucceedsSoon: expected internal error
I230321 07:08:45.109292 3716057 13@kv/kvserver/replicate_queue.go:842  [T1,n1,replicate,s1,r20/1:/Table/1{8-9}] 1877  error processing replica: 0 of 1 live stores are able to take a new replica for the range (1 already has a voter, 0 already have a non-voter); likely not enough nodes in cluster
I230321 07:08:45.759213 2516882 testutils/soon.go:41  [-] 1878  SucceedsSoon: expected internal error
I230321 07:08:46.760375 2516882 testutils/soon.go:41  [-] 1879  SucceedsSoon: expected internal error
I230321 07:08:47.113128 3773482 13@kv/kvserver/replicate_queue.go:842  [T1,n1,replicate,s1,r21/1:/Table/{19-20}] 1880  error processing replica: 0 of 1 live stores are able to take a new replica for the range (1 already has a voter, 0 already have a non-voter); likely not enough nodes in cluster
I230321 07:08:47.357576 2523786 kv/kvserver/replica_rangefeed.go:703  [T1,n1,s1,r34/1:/Table/3{2-3}] 1881  RangeFeed closed timestamp 1679382526.664259796,0 is behind by 693.299357ms
I230321 07:08:47.760615 2516882 testutils/soon.go:41  [-] 1882  SucceedsSoon: expected internal error
I230321 07:08:48.113674 3798625 13@kv/kvserver/replicate_queue.go:842  [T1,n1,replicate,s1,r3/1:/System/{NodeLive…-tsd}] 1883  error processing replica: 0 of 1 live stores are able to take a new replica for the range (1 already has a voter, 0 already have a non-voter); likely not enough nodes in cluster
I230321 07:08:48.761617 2516882 testutils/soon.go:41  [-] 1884  SucceedsSoon: expected internal error
I230321 07:08:49.085757 2524347 2@util/log/event_log.go:32  [T1,n1] 1885 ={"Timestamp":1679382529085753139,"EventType":"runtime_stats","MemRSSBytes":343293952,"GoroutineCount":371,"MemStackSysBytes":6455296,"GoAllocBytes":118848824,"GoTotalBytes":233693528,"GoStatsStaleness":0.001443705,"HeapFragmentBytes":75195080,"HeapReservedBytes":163840,"HeapReleasedBytes":185212928,"CGoAllocBytes":9595936,"CGoTotalBytes":28246016,"CGoCallRate":0.19998817,"CPUUserPercent":56.99663,"CPUSysPercent":3.8997695,"GCPausePercent":0.00540516,"GCRunCount":71,"NetHostRecvBytes":104390,"NetHostSendBytes":104390}
I230321 07:08:49.086035 2524347 2@server/status/runtime_log.go:47  [T1,n1] 1886  runtime stats: 327 MiB RSS, 371 goroutines (stacks: 6.2 MiB), 113 MiB/223 MiB Go alloc/total(stale) (heap fragmentation: 72 MiB, heap reserved: 160 KiB, heap released: 177 MiB), 9.2 MiB/27 MiB CGO alloc/total (0.2 CGO/sec), 57.0/3.9 %(u/s)time, 0.0 %gc (71x), 102 KiB/102 KiB (r/w)net
I230321 07:08:49.115881 3826158 13@kv/kvserver/replicate_queue.go:842  [T1,n1,replicate,s1,r59/1:/Table/5{8-9}] 1887  error processing replica: 0 of 1 live stores are able to take a new replica for the range (1 already has a voter, 0 already have a non-voter); likely not enough nodes in cluster
I230321 07:08:49.150564 3829294 13@kv/kvserver/replicate_queue.go:842  [T1,n1,replicate,s1,r18/1:/Table/1{6-7}] 1888  error processing replica: 0 of 1 live stores are able to take a new replica for the range (1 already has a voter, 0 already have a non-voter); likely not enough nodes in cluster
I230321 07:08:49.761796 2516882 testutils/soon.go:41  [-] 1889  SucceedsSoon: expected internal error
I230321 07:08:50.117210 3855942 13@kv/kvserver/replicate_queue.go:842  [T1,n1,replicate,s1,r56/1:/Table/5{5-6}] 1890  error processing replica: 0 of 1 live stores are able to take a new replica for the range (1 already has a voter, 0 already have a non-voter); likely not enough nodes in cluster
I230321 07:08:50.762632 2516882 testutils/soon.go:41  [-] 1891  SucceedsSoon: expected internal error
I230321 07:08:51.762901 2516882 testutils/soon.go:41  [-] 1892  SucceedsSoon: expected internal error
I230321 07:08:52.127093 3911366 13@kv/kvserver/replicate_queue.go:842  [T1,n1,replicate,s1,r27/1:/Table/2{5-6}] 1893  error processing replica: 0 of 1 live stores are able to take a new replica for the range (1 already has a voter, 0 already have a non-voter); likely not enough nodes in cluster
I230321 07:08:52.763041 2516882 testutils/soon.go:41  [-] 1894  SucceedsSoon: expected internal error
I230321 07:08:53.619271 2523786 kv/kvserver/replica_rangefeed.go:703  [T1,n1,s1,r34/1:/Table/3{2-3}] 1895  RangeFeed closed timestamp 1679382533.117193795,0 is behind by 502.055495ms
I230321 07:08:53.763698 2516882 testutils/soon.go:41  [-] 1896  SucceedsSoon: expected internal error
I230321 07:08:54.126417 3965677 13@kv/kvserver/replicate_queue.go:842  [T1,n1,replicate,s1,r10/1:/Table/{6-7}] 1897  error processing replica: 0 of 1 live stores are able to take a new replica for the range (1 already has a voter, 0 already have a non-voter); likely not enough nodes in cluster
I230321 07:08:54.763856 2516882 testutils/soon.go:41  [-] 1898  SucceedsSoon: expected internal error
I230321 07:08:55.764720 2516882 testutils/soon.go:41  [-] 1899  SucceedsSoon: expected internal error
I230321 07:08:56.131800 4016976 13@kv/kvserver/replicate_queue.go:842  [T1,n1,replicate,s1,r47/1:/Table/4{5-6}] 1900  error processing replica: 0 of 1 live stores are able to take a new replica for the range (1 already has a voter, 0 already have a non-voter); likely not enough nodes in cluster
I230321 07:08:56.765184 2516882 testutils/soon.go:41  [-] 1901  SucceedsSoon: expected internal error
I230321 07:08:57.765855 2516882 testutils/testcluster/testcluster.go:144  [-] 1902  TestCluster quiescing nodes
    rangefeed_external_test.go:906: condition failed to evaluate within 45s: expected internal error
I230321 07:08:57.766794 2521136 server/start_listen.go:103  [T1,n1] 1903  server shutting down: instructing cmux to stop accepting
W230321 07:08:57.767681 2541396 jobs/registry.go:1052  [T1,n1] 1905  canceling all adopted jobs due to stopper quiescing
I230321 07:08:57.767882 3668375 jobs/registry.go:1494  [T1,n1] 1906  KEY VISUALIZER job 100: stepping through state succeeded
I230321 07:08:57.768623 2628359 rpc/context.go:2257  [T1,n1,rnode=1,raddr=127.0.0.1:44403,class=default,rpc] 1907  connection heartbeat loop ended with err: <nil>
W230321 07:08:57.767609 2536853 sql/sqlliveness/slinstance/slinstance.go:312  [n1] 1904  exiting heartbeat loop
W230321 07:08:57.768921 2536853 sql/sqlliveness/slinstance/slinstance.go:297  [n1] 1908  exiting heartbeat loop
I230321 07:08:57.768265 2541139 sql/stats/automatic_stats.go:507  [T1,n1] 1909  quiescing auto stats refresher
E230321 07:08:57.769017 2536853 server/server_sql.go:493  [n1] 1910  failed to run update of instance with new session ID: node unavailable; try another peer
E230321 07:08:57.769863 3667907 jobs/registry.go:924  [T1,n1] 1911  error getting live session: node unavailable; try another peer
I230321 07:08:57.770692 2566852 jobs/registry.go:1494  [T1,n1] 1912  AUTO SPAN CONFIG RECONCILIATION job 849713853864673281: stepping through state succeeded
W230321 07:08:57.780338 3668375 jobs/adopt.go:511  [T1,n1] 1913  could not clear job claim: clear-job-claim: failed to send RPC: sending to all replicas failed; last error: ba: Scan [/Table/15/1/100,/Table/15/1/101), [txn: 1db1448f], [can-forward-ts] RPC error: node unavailable; try another peer
--- FAIL: TestUnrecoverableErrors (48.91s)
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/replication
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestUnrecoverableErrors.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-25700

### PR DESCRIPTION
**Pull request by tbg**
Closes https://github.com/cockroachdb/cockroach/issues/99096.

```
655857 runs so far, 0 failures, over 12h38m45s
^C
tobias@gceworker-tobias:~/go/src/github.com/cockroachdb/cockroach$ ./dev test --stress ./pkg/kv/kvserver --filter TestUnrecoverableErrors -- --define gotags=bazel,gss,deadlock 2>&1 | tee stress.log
```

on b89fa2cc4bc1fb9447ab1009b34b6f354f9618f0

Epic: none
Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
Sometimes, we just don't get the internal error. I put in a bunch of logging. On failure, we get:

```
I230322 14:18:18.082539 329344 kv/kvserver/replica.go:1812  [-] 187  XXX impliedThreshold=1679480297.838364952,0 ts=0.000000001,0
I230322 14:18:18.082695 329344 server/node.go:1524  [-] 188  XXX rangefeed sending error batch timestamp 0.000000001,0 must be after replica GC threshold 1679480297.838364952,0

```

and then nothing until the test's `SucceedsSoon` times out and tears down.

On success, we get 

```
I230322 15:51:43.844770 1832 kv/kvserver/replica.go:1812  [-] 185  XXX impliedThreshold=1679485903.740956000,0 ts=0.000000001,0
I230322 15:51:43.844803 1832 server/node.go:1524  [-] 186  XXX rangefeed sending error batch timestamp 0.000000001,0 must be after replica GC threshold 1679485903.740956000,0
I230322 15:51:43.844845 1831 kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:400  [T1,rangefeed=test,n1,mux_n=1,gen=2] 187  RangeFeedError: batch timestamp 0.000000001,0 must be after replica GC threshold 1679485903.740956000,0
I230322 15:51:43.844893 1831 kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:446  [T1,rangefeed=test,n1,mux_n=1,gen=2] 188  RangeFeed {/Table/Max-\xfb?}@0.000000001,0 disconnected with last checkpoint 466527h51m43.844893s ago: batch timestamp 0.000000001,0 must be after replica GC threshold 1679485903.740956000,0
I230322 15:51:43.844942 1831 kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:323  [T1,rangefeed=test,n1,mux_n=1,gen=2] 189  XXX client MuxRangeFeed recvErr: batch timestamp 0.000000001,0 must be after replica GC threshold 1679485903.740956000,0
I230322 15:51:43.844970 1665 kv/kvclient/rangefeed/rangefeed.go:322  [rangefeed=test] 190  XXX exiting rangefeed due to internal error: rangefeed impl *rangefeed.dbAdapter: batch timestamp 0.000000001,0 must be after replica GC threshold 1679485903.740956000,0
```

These are both using the mux rangefeed (I hard-coded the metamorphic variable).

This is intriguing, since maybe it has to do with https://github.com/cockroachdb/cockroach/issues/86818, so I will keep pulling.

**Comment by miretskiy** [comment]
Mux definitely can be the culprit; I recently fixed some of the test failures  (as a fallout from mux rewrite); more issues might be lurking there.

**Comment by tbg** [comment]
We should find out soon, I'll keep looking. Shouldn't be too long until I know.

**Comment by tbg** [comment]
Btw my repro on GCE worker is this:

```
gh pr checkout -f 99112
./dev test --stress ./pkg/kv/kvclient/rangefeed/ --filter TestUnrecoverableErrors --stress-args '-p 24' -- --define gotags=bazel,gss,deadlock 2>&1 | tee stress.log
```

Usually <15 minutes (often much less).

**Comment by miretskiy** [comment]
@tbg I think https://github.com/cockroachdb/cockroach/pull/99289 fixes things.
Enough of fancy intmaps, locked map works fine.

**Pull request closed without merging**
