### PR TITLE
build: use `env` to set environment variables in docker run.

### PR DESCRIPTION
**Pull request by knz**
No functional change.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12670)

### CODE REVIEW

**Comment by tamird** [comment]
Are you sure this does what you think? I think `make FOO=bar` sets FOO in the environment.

**Comment by tamird** [comment]
I don't think this is correct. Here's how I tested:
```diff
diff --git a/Makefile b/Makefile
index e102951f7..8a15f30e8 100644
--- a/Makefile
+++ b/Makefile
@@ -70,6 +70,10 @@ ifeq ($(STATIC),1)
 LDFLAGS += -extldflags "-static-libgcc -static-libstdc++"
 endif
 
+.PHONY: foo
+foo:
+	env
+
 .PHONY: all
 all: build test check
 
```
```
$ make FOO=bar | grep FOO
FOO=bar
MAKEFLAGS=FOO=bar
```

So...it seems that you're reading the docs too literally? Variables specified on the command line seem to "override" the makefile even if a particular variable is not specified in the makefile nor is present in the environment.

**Comment by bdarnell** [comment]
> What this does not say is "a make variable set in the argument list of make will become an environment variable in sub-processes".

I think the next paragraph says that:

> When make runs a recipe, variables defined in the makefile are placed into the environment of each shell.

I think "variables defined in the makefile" should be read as "make variables", which includes both those defined in the Makefile and those passed on the command line.

**Comment by knz** [comment]
This behavior has most probably changed in recent(ish) make versions, because I 100% remember fighting with make until I understood there was a problem as late as 2009.

**Comment by knz** [comment]
May I still suggest merging this PR for the sake of clarity in the shell script: these things are intended to be env vars not make vars so the `env` invocation would make this consistent with its other previous uses.

**Comment by knz** [comment]
sorry I misclicked

**Comment by tamird** [comment]
OK, but please amend the commit message to indicate that this is a matter of style, and not a functional change.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[build/teamcity-test.sh, line 6 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12670#-K_jF_rs80gWQDEh5kGu:-K_jF_rs80gWQDEh5kGv:b-xiaup4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4e780048bbdfbb8a7b6c488f3d5d9c9ee5c0d5/build/teamcity-test.sh#L6)):*
> ```Shell
> mkdir -p artifacts
> 
> build/builder.sh env COCKROACH_PROPOSER_EVALUATED_KV="${COCKROACH_PROPOSER_EVALUATED_KV:-false}" make test TESTFLAGS='-v' 2>&1 | tee artifacts/test.log | go-test-teamcity
> ```

what is this `:-false`?

Care to wrap this like you did teamcity-stress.sh while you're here?

---

*[build/teamcity-testrace.sh, line 6 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12670#-K_jFh4z7shE6J9VhFLH:-K_jFh4z7shE6J9VhFLI:b-ivbh7t) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4e780048bbdfbb8a7b6c488f3d5d9c9ee5c0d5/build/teamcity-testrace.sh#L6)):*
> ```Shell
> mkdir -p artifacts
> 
> build/builder.sh env COCKROACH_PROPOSER_EVALUATED_KV="${COCKROACH_PROPOSER_EVALUATED_KV-false}" make testrace TESTFLAGS='-v' 2>&1 | tee artifacts/testrace.log | go-test-teamcity
> ```

ditto wrapping

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12670#-:-K_jFj97XkN0T3_q18VA:b-etj9sp)*

**Comment by knz** [comment]
Commit message is amended.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[build/teamcity-test.sh, line 6 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12670#-K_jF_rs80gWQDEh5kGu:-K_kW5iKSGho2vmOMfYh:bn3huq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4e780048bbdfbb8a7b6c488f3d5d9c9ee5c0d5/build/teamcity-test.sh#L6)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

what is this `:-false`?

Care to wrap this like you did teamcity-stress.sh while you're here?
</blockquote></details>

this `:-false` is to avoid `util/envutil/env.go:169  error parsing COCKROACH_PROPOSER_EVALUATED_KV: strconv.ParseBool: parsing "": invalid syntax`

scripts wrapped as requested.

---

*[build/teamcity-testrace.sh, line 6 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12670#-K_jFh4z7shE6J9VhFLH:-K_kW_L-26tIBQKgYRaj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4e780048bbdfbb8a7b6c488f3d5d9c9ee5c0d5/build/teamcity-testrace.sh#L6)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

ditto wrapping
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12670#-:-K_kWwwJNevO4U1_VvDs:b-7nagav)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[build/teamcity-test.sh, line 6 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12670#-K_jF_rs80gWQDEh5kGu:-K_kXZK0prVzhncyUI7l:b-pbh4t6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4e780048bbdfbb8a7b6c488f3d5d9c9ee5c0d5/build/teamcity-test.sh#L6)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

this `:-false` is to avoid `util/envutil/env.go:169  error parsing COCKROACH_PROPOSER_EVALUATED_KV: strconv.ParseBool: parsing "": invalid syntax`

scripts wrapped as requested.
</blockquote></details>

my question was "why is there a colon here?" but i see now that you've added colons everywhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12670#-:-K_kXs_zHwoQg69pLC2N:bnfp4nl)*

**Comment by knz** [comment]
TFYR!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12670#-:-K_kb9Qxi8dvAV-AKJJt:b-814cj3)*

**Pull request merged**
