### PR TITLE
concurrency: add ConcurrencyManager test for lock promotion deadlocks

### LINKED ISSUE #109634: concurrency: add concurrency manager tests for shared locks
**Describe the problem**

Currently, shared locks are only tested at the level of the lock table. Once https://github.com/cockroachdb/cockroach/pull/109633 lands, we'll have all the pieces required to test shared locks from the concurrency manager level, by extending `TestConcurrencyManagerBasic`. Doing so allows us to test things such as deadlock detection / transaction pushes end to end.

### PR DESCRIPTION
**Pull request by arulajmani**
Closes https://github.com/cockroachdb/cockroach/issues/109634

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123209#-:-NwfThy2866xpX2Si576:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/concurrency/testdata/concurrency_manager/shared_locks` line 1425 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123209#-NwfTkj91PZW-ul1rHdx:-NwfTkj91PZW-ul1rHdy:bjinwsy) ([raw file](https://github.com/cockroachdb/cockroach/blob/30248f610e2afe462c12ff3acaaac0172bf31cb2/pkg/kv/kvserver/concurrency/testdata/concurrency_manager/shared_locks#L1425)):*
> ```
> [4] sequence req4: dependency cycle detected 00000002->00000001->00000002
> 
> # We can't break the deadlock and get deterministic behaviour unfortunately.
> ```

Can we at least `reset` after this point so that we can add more test cases to this file?

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123209)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/testdata/concurrency_manager/shared_locks` line 1425 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123209#-NwfTkj91PZW-ul1rHdx:-Nwi12555u2hQ4SSeQg7:bjgv6cl) ([raw file](https://github.com/cockroachdb/cockroach/blob/30248f610e2afe462c12ff3acaaac0172bf31cb2/pkg/kv/kvserver/concurrency/testdata/concurrency_manager/shared_locks#L1425)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we at least `reset` after this point so that we can add more test cases to this file?
</blockquote></details>

Unfortunately we can't because req3 and req4 are still in-flight. How do you feel about moving this to its own file instead?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123209)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/concurrency/testdata/concurrency_manager/shared_locks` line 1425 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123209#-NwfTkj91PZW-ul1rHdx:-NwjDzoEDkBG-v0CEtgY:b3iblqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/30248f610e2afe462c12ff3acaaac0172bf31cb2/pkg/kv/kvserver/concurrency/testdata/concurrency_manager/shared_locks#L1425)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Unfortunately we can't because req3 and req4 are still in-flight. How do you feel about moving this to its own file instead?
</blockquote></details>

Moving to its own file SGTM.

**Review by arulajmani — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123209#-:-NxwLTM4CNehSyCBgSIw:b-oduykh)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/testdata/concurrency_manager/shared_locks` line 1425 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123209#-NwfTkj91PZW-ul1rHdx:-NxwL0yy-5Hs6Yh-QRW0:b-wr1rt4) ([raw file](https://github.com/cockroachdb/cockroach/blob/30248f610e2afe462c12ff3acaaac0172bf31cb2/pkg/kv/kvserver/concurrency/testdata/concurrency_manager/shared_locks#L1425)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Moving to its own file SGTM.
</blockquote></details>

Not sure how I only caught this just now, but the test was failing because of these leaked in-flight goroutines. To get around this, I had to add a "force" modifier to cancel the context on these inflight goroutines instead. With that, we can keep these in this file.

**Pull request merged**
