### PR TITLE
sql,security: create a password hash abstraction  (scram 4/10)

### PR DESCRIPTION
**Pull request by knz**
(PR peeled away from #74301; previous PR in series #74843; next PR in series: #74845)
Epic CRDB-5349

Prior to this commit, password hashes loaded from storage
were simply represented as byte arrays.

The in-RAM credential cache was then simply storing these byte arrays.

Keeping this simple encoding is unfortunate for the SCRAM
authentication format, because it forces the password check code to
re-parse the 4 parameters of the SCRAM credentials upon every
authentication event.

Instead, we want to pre-parse the parameters once, and store them
pre-parsed in the credential cache.

To achieve this, this commit introduces a new `security.PasswordHash`
to replace `[]byte` to represent password hashes in memory.
A stored byte array can be converted to a `security.PasswordHash`
using the new `security.LoadPasswordHash()` function.

Additionally, this commit performs the following cleanups:

- it renames `security.CompareHashAndPassword` to
  `CompareHashAndCleartextPassword` to clarify the format
  the password is expected in.
- it makes `CompareHashAndCleartextPassword()` return
  a boolean alongside the error. The function does not
  return an error any more if the hash is valid but the
  credentials don't match. Callers are now expected to
  propagate the returned error, if any.
- it un-exports `security.ErrPasswordUserAuthFailed`, which
  was a formatting string, and replaces it by a new
  error constructor `NewErrPasswordUserAuthFailed` (this
  was meant to be used to construct errors originally).

NB: this commit merely adds a new abstraction in the APIs.
SCRAM hashes are still not used for authentication.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
@rafiss this is the part you were already reviewing in #74301, extracted here as a single commit for your reviewing convenience.

cc @catj-cockroach , this is what I told you about.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74844)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[pkg/security/password.go, line 349 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74844#-MtPaNLl-FYOiZq0B5ju:-MtPaNLo-tBBJNs1xiAw:b-bg5btq) ([raw file](https://github.com/cockroachdb/cockroach/blob/db869c03c142c6f2eacbd43eb53830108f66c318/pkg/security/password.go#L349)):*
> ```Go
> }
> 
> func makeSCRAMHash(storedHash []byte, parts [][]byte, invalidHash PasswordHash) PasswordHash {
> ```

can this function document the order of the `parts` slice? would it be too cumbersome to make it accept 4 different `[]byte` params or a struct, so that it's self-documenting instead?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74844)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @JeffSwenson and @rafiss)

___
*[pkg/security/password.go, line 349 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74844#-MtPaNLl-FYOiZq0B5ju:-MtSdgIZ254vElOT0T-w:bq2zvrm) ([raw file](https://github.com/cockroachdb/cockroach/blob/db869c03c142c6f2eacbd43eb53830108f66c318/pkg/security/password.go#L349)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can this function document the order of the `parts` slice? would it be too cumbersome to make it accept 4 different `[]byte` params or a struct, so that it's self-documenting instead?
</blockquote></details>

Changed the data type to hide the details. This is not meant to be used without isSCRAMHash().
(I split the two upon a suggestion by @jeffswenson in [this comment](https://github.com/cockroachdb/cockroach/pull/74301#pullrequestreview-852337243)  but the latter is not meant to be used standalone)

**Comment by knz** [comment]
@rafiss anything else you'd like to happen here?

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74844)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @JeffSwenson, @knz, and @rafiss)

___
*[pkg/security/password.go, line 331 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74844#-MtnORl--ha7mGhcbqRG:-MtnORl01o29szsApvyr:b1xr43i) ([raw file](https://github.com/cockroachdb/cockroach/blob/3542a888babf5c86b5e499ad03378e7c7c0fdc0f/pkg/security/password.go#L331)):*
> ```Go
> // isSCRAMHash() to makeSCRAMHash(), so that the latter cannot be
> // legitimately used without the former.
> type scramParts [][]byte
> ```

what do you think about making this

```
type scramParts [5][]byte
```
___
*[pkg/security/password.go, line 335 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74844#-MtnOW8lBwj4OuS8XUyU:-MtnOW8lBwj4OuS8XUyV:b-dqmh6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/3542a888babf5c86b5e499ad03378e7c7c0fdc0f/pkg/security/password.go#L335)):*
> ```Go
> func isSCRAMHash(inputPassword []byte) (bool, scramParts) {
> 	parts := scramHashRe.FindSubmatch(inputPassword)
> 	return parts != nil, scramParts(parts)
> ```

and then here we can convert the parts with
```
if len(parts) != 5 {
  return false, scramParts{}
}
return true, *(*scramParts)(parts)
```

(new in go 1.17 https://tip.golang.org/ref/spec#Conversions_from_slice_to_array_pointer)
___
*[pkg/security/password.go, line 357 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74844#-MtnReFqADVtg8hyOdPX:-MtnReFrD92_uv429-dT:b1y8w8j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3542a888babf5c86b5e499ad03378e7c7c0fdc0f/pkg/security/password.go#L357)):*
> ```Go
> // previous call to isSCRAMHash().
> func makeSCRAMHash(storedHash []byte, parts scramParts, invalidHash PasswordHash) PasswordHash {
> 	iters, err := strconv.Atoi(string(parts[1]))
> ```

could we add a few functions on the `scramParts` type?

```
func (sp scramParts) getIters (int, error) {
  return strconv.Atoi(string(sp[1]))
}

func (sp scramParts) getSalt (string, error) {
  return base64.StdEncoding.DecodeString(string(sp[2]))
}

func (sp scramParts) getStoredKey (string, error) {
  return base64.StdEncoding.DecodeString(string(sp[3]))
}

func (sp scramParts) getServerKey (string, error) {
  return base64.StdEncoding.DecodeString(string(sp[4]))
}
```

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74844)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @JeffSwenson and @rafiss)

___
*[pkg/security/password.go, line 331 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74844#-MtnORl--ha7mGhcbqRG:-MtrPgMC-_QgFg6Q0jhM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3542a888babf5c86b5e499ad03378e7c7c0fdc0f/pkg/security/password.go#L331)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

what do you think about making this

```
type scramParts [5][]byte
```
</blockquote></details>

Done.
___
*[pkg/security/password.go, line 335 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74844#-MtnOW8lBwj4OuS8XUyU:-MtrPfzz0cARQ-7sYGA8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3542a888babf5c86b5e499ad03378e7c7c0fdc0f/pkg/security/password.go#L335)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

and then here we can convert the parts with
```
if len(parts) != 5 {
  return false, scramParts{}
}
return true, *(*scramParts)(parts)
```

(new in go 1.17 https://tip.golang.org/ref/spec#Conversions_from_slice_to_array_pointer)
</blockquote></details>

Done.
___
*[pkg/security/password.go, line 357 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74844#-MtnReFqADVtg8hyOdPX:-MtrPh2o-8cujpyPDtpE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3542a888babf5c86b5e499ad03378e7c7c0fdc0f/pkg/security/password.go#L357)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could we add a few functions on the `scramParts` type?

```
func (sp scramParts) getIters (int, error) {
  return strconv.Atoi(string(sp[1]))
}

func (sp scramParts) getSalt (string, error) {
  return base64.StdEncoding.DecodeString(string(sp[2]))
}

func (sp scramParts) getStoredKey (string, error) {
  return base64.StdEncoding.DecodeString(string(sp[3]))
}

func (sp scramParts) getServerKey (string, error) {
  return base64.StdEncoding.DecodeString(string(sp[4]))
}
```
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
looks great!

> Reviewed 5 of 11 files at r1, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74844#-:-Mts5ylt2oTu624jDC48:b6lqmcl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @JeffSwenson and @rafiss)

**Review by jeffswenson — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74844#-:-Mts7xN78J5UrURRTVXm:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @JeffSwenson and @rafiss)

**Comment by knz** [comment]
NB: I'm holding off merging this PR until all the PRs in the sequence are ready (otherwise, the entire chain will be auto-closed by github).

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74844)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @JeffSwenson and @rafiss)

___
*[pkg/security/password.go, line 335 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74844#-MtnOW8lBwj4OuS8XUyU:-MtsEp4UCjz6umWKSt9_:b18e3in) ([raw file](https://github.com/cockroachdb/cockroach/blob/3542a888babf5c86b5e499ad03378e7c7c0fdc0f/pkg/security/password.go#L335)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

FYI: it works in the code, but the linter hates it
```
    lint_test.go:1740: err=exit status 2, stderr=panic: in github.com/cockroachdb/cockroach/pkg/security.isSCRAMHash: cannot convert Load <[][]byte> t0 ([][]byte) to *github.com/cockroachdb/cockroach/pkg/security.scramParts
        goroutine 5661 [running]:
        honnef.co/go/tools/go/ir.emitConv(0xc0a64a30e0, {0x974b68, 0xc0ab54e300}, {0x9656e0, 0xc03bb74c70}, {0x964e20, 0xc009336000})
          /go/src/github.com/cockroachdb/cockroach/vendor/honnef.co/go/tools/go/ir/emit.go:261 +0xb25
        honnef.co/go/tools/go/ir.(*builder).expr0(0xc0aa34db00, 0xc0a64a30e0, {0x966a00, 0xc009336000}, {0x7, {0x9656e0, 0xc03bb74c70}, {0x0, 0x0}})
          /go/src/github.com/cockroachdb/cockroach/vendor/honnef.co/go/tools/go/ir/builder.go:544 +0xa77
```

**Pull request merged**
