### PR TITLE
storage: allow multiple concurrent snapshots

### PR DESCRIPTION
**Pull request by tamird**
@cuongdo this is on top of #7299 - I bet the degradation we saw with this change originally was the result of that issue. Can you test it?

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7307)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/store.go, line 673 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7307#-KKTU8ymDMESuALCX16i:-KKTU8ymDMESuALCX16j:-1847816491) ([raw file](https://github.com/cockroachdb/cockroach/blob/acfccc1074a4161075dd8fa38c1551eaff527262/storage/store.go#L673)):*
> ```Go
> 
> 	raftElectionTimeout := time.Duration(sc.RaftElectionTimeoutTicks) * sc.RaftTickInterval
> 	sc.concurrentSnapshotLimit = 5
> ```

Per my earlier comment, let's default this to `1` and perhaps allow an env var to override. I'd like to see concrete numbers showing there is a benefit to raising the number of concurrent snapshots. I worry about allowing multiple concurrent snapshots while we have the existing memory issues with snapshots. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7307)*

**Comment by tamird** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/store.go, line 673 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7307#-KKTU8ymDMESuALCX16i:-KKTWDeIUXRWHISY-HYw:1085483994) ([raw file](https://github.com/cockroachdb/cockroach/blob/acfccc1074a4161075dd8fa38c1551eaff527262/storage/store.go#L673)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Per my earlier comment, let's default this to `1` and perhaps allow an env var to override. I'd like to see concrete numbers showing there is a benefit to raising the number of concurrent snapshots. I worry about allowing multiple concurrent snapshots while we have the existing memory issues with snapshots. 
</details>
Will do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7307)*

**Comment by bdarnell** [comment]
I'd rather hold off on this change until we demonstrate stability with the current version, especially since I agree with Peter that it is unlikely that allowing more snapshots will make sense until we can move to streaming snapshots.

**Comment by cuongdo** [comment]
Agreed. Let's let the dust settle from the recent Raft transport and
reservations changes first.

**Comment by tamird** [comment]
Sure. I've rebased this, so it should be good to go whenever we're ready to start experimenting with it again.

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7307#-:-KKUGbfzYhXxbKW6sVFu:1519513642)*

**Comment by tamird** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/store.go, line 673 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7307#-KKTU8ymDMESuALCX16i:-KKUGhm0FRMUU6p4dV0X:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/acfccc1074a4161075dd8fa38c1551eaff527262/storage/store.go#L673)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Will do.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7307)*

**Comment by tamird** [comment]
Rebased on top of streaming snapshots, much simpler now.

**Comment by jordanlewis** [comment]
Is there any way that we can test this change with more than 1 concurrent snapshot before merging? I see that the default is 1, but I'm nervous that we'll see problems with snapshots when we adjust that configuration. I think it would be nice to try to catch potential problems with concurrent snapshots with a test before we merge this.

The code :lgtm:, though.

---

Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7307#-:-KSax9uUzg7LFRyLVNye:b-ll74bw)*

**Comment by petermattis** [comment]
I like getting rid of the use of `atomic` here. It would be nice to have evidence that we'll ever set this value larger than 1.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7307#-:-KSay-MLigpj106Zjoff:b-bra6bp)*

**Comment by tamird** [comment]
@jordanlewis updated the default to 2 -- I guess it doesn't make much sense to merge this before the default is changed. The tests still pass (though maybe you had some specific tests in mind).

@petermattis indeed -- hard to say if or when we will. Perhaps the chaos monkeys will tell. On the other hand, it may be good to expose concurrency bugs while the streaming snapshots change is fresh in everyone's minds.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7307#-:-KSb1W8D69d6YBnGsK_e:b-y3jcsf)*

**Comment by petermattis** [comment]
Can't we show via some local workload that a value larger than `1` is worthwhile?

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7307#-:-KSbD87XbGyjPuqZGDOM:b7lf08x)*

**Comment by bdarnell** [comment]
The code change LGTM, but I'd rather keep the default at 1 until we can show that this is both safe and beneficial.

**Comment by tamird** [comment]
OK, updated the default to 1.

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/store.go, line 778 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/7307#-KY54R4mm4YGZorlEnmf:-KY54R4mm4YGZorlEnmg:bh4m89q) ([raw file](https://github.com/cockroachdb/cockroach/blob/1857fe3f1d50729fdc0967b64aa95be4145c33d4/pkg/storage/store.go#L778)):*
> ```Go
> 	}
> 	if sc.concurrentSnapshotLimit == 0 {
> 		sc.concurrentSnapshotLimit = envutil.EnvOrDefaultInt("COCKROACH_CONCURRENT_SNAPSHOT_LIMIT", 1)
> ```

Can you mind adding a small comment here: `NB: be careful about setting this value higher than 1 as it will degrade client throughput.`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7307#-:-KY54gfMK1L81GsKfILL:bnfp4nl)*

**Comment by tamird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/store.go, line 778 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/7307#-KY54R4mm4YGZorlEnmf:-KY5gj6o5Cg9i7_bdc75:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1857fe3f1d50729fdc0967b64aa95be4145c33d4/pkg/storage/store.go#L778)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can you mind adding a small comment here: `NB: be careful about setting this value higher than 1 as it will degrade client throughput.`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7307)*

**Pull request merged**
