### PR TITLE
go.mod: bump Pebble to b77606f72b19

### PR DESCRIPTION
**Pull request by bananabrick**
b77606f7 db: Zero out bounds for key type not present in ScanInternal
73b9c4d8 ci: add build for OpenBSD
0a26a7f4 vfs: Add support for OpenBSD
ea9e7b8a metamorphic: Batch close operation to `g.BatchClose`
876b2e76 ingest: Call Extend{Point,Range}KeyBounds in excise
d900c432 compaction: Call logUnlock on errored compactions
06034ff0 lint: add linter for raw atomic operations
c2164213 db: use atomic.Pointer for keySpanFrags
a0e702e7 objstorage: support custom object names
db69f4e6 vfs: update DiskSlowInfo Stringer implementation
f583cc14 db: use atomic.Pointer for commit queue
87b36355 db: use atomic wrappers in tests
5f909161 vfs: use atomic wrappers
b69a460a replay: use atomic wrappers
9e74e573 record: use atomic wrappers
f4efcacd randvar: use atomic.Uint64 for Uniform.max
84bb5f33 pacertoy: use atomic wrappers
bc1fc1fe manifest: use atomic.Int32 for Version.refs
c4daad91 manifest: use atomic.Int32 for leafNode.ref
6f17c1c6 errorfs: use atomic.Int32 for InjectIndex.index
e10a6b91 cache: use atomic wrappers
8460a25e arenaskl: use atomic wrappers
0ad5a7ab ackseq: use atomic.Uint64 for next
e7bbdd56 cmd/pebble: use atomic.Uint64 for ycsb.numOps
32b9c781 db: use atomic.Uint32 for keySpanCache count
613c832b db: use atomic.Int32 for readState.refcnt
71775aab db: use atomic.Int32 for flushableEntry.readerRefs
5e3de5ec db: Add IngestShared test to exercise shared ingestion
6746f411 db: support concurrency in TestIngestValidation
1a7fe39c sstable: propagate error if decompression fails
88775ba7 db: don't require holding d.mu to read format major version

Release note: None
Epic: none

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]

**Review by jbowens — APPROVED** [review]
lgtm

**Comment by bananabrick** [comment]
Closing in favor of https://github.com/cockroachdb/cockroach/pull/105473

**Comment by bananabrick** [comment]
Gonna give this another try.

bors r+

**Comment by jbowens** [comment]
Whew! Thanks @bananabrick

**Pull request merged**
