### PR TITLE
 opt: pass through merge join ordering

### PR DESCRIPTION
**Pull request by RaduBerinde**
A MergeJoin can provide the ordering on the equality columns. This
helps cases where we can "chain" multiple merge joins.

Release note: None

### CODE REVIEW

**Review by andy-kimball — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27850#-:-LI7-tHtAa8jlziA1lo7:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by RaduBerinde** [comment]
My change was missing setting an ordering in `props` so that the distsql planner preserves it. It was also incorrect to say that we can provide the left-side ordering on a right join (and vice-versa). These were caught by some logic tests.

I also revived a set of planner tests that use merge joins. The distsql plans look the same, except for the non-simplified ON condition (known issue).

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 3 files at r1, 5 of 5 files at r2, 7 of 7 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27850#-:-LIBn6NmC_L82M8DJG-b:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Pull request merged**
