### PR TITLE
server/status: improve memory detection from inside of container

### LINKED ISSUE #44211: Read current process's cgroup to determine available memory in a way that works correctly in k8s
We attempted a fix here: https://github.com/cockroachdb/cockroach/pull/43137. The change does not work correctly in the k8s environment. We need a fix that works in the k8s environment. @ajwerner has an approach in mind that should work correctly in the k8s environment.

We hope to release this as part of 19.2.4.

Thanks, @ajwerner!

cc @vladdy @DuskEagle

### PR DESCRIPTION
**Pull request by vladdy**
Fixes https://github.com/cockroachdb/cockroach/issues/44211.

This improves memory detection from inside of the container, where I used both cgroup v1 and v2 based containers as an example to ensure that we have generic approach to getting the valid limits. Unfortunately, the documentation around the both versions is sparse, so I'm still not 100% confident if any container solution would be properly supported, but we should support the main use case of OCI based runtimes here. This hopefully creates a foundation for further extension as the ecosystem evolves.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
Took a first pass and had some questions. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-:-LzwSxA59-kXnjeAT_Xv:b-vdkwmr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @vladdy)

___
*[pkg/util/cgroups/cgroups.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-LzwRRRgAXtNdCNkiGIt:-LzwRRRgAXtNdCNkiGIu:b-23ucey) ([raw file](https://github.com/cockroachdb/cockroach/blob/92f77c4a6cc031573f668953540bc229aa288be7/pkg/util/cgroups/cgroups.go#L40)):*
> ```Go
> // process
> func GetMemoryLimit() (limit int64, warnings string, err error) {
> 	return getCgroupMem2("/")
> ```

Why `2`? It's a common pattern to have an exported function and then an unexported function with same name less the first character that has a different signature. 
___
*[pkg/util/cgroups/cgroups.go, line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-LzwRuEs37H3Sp6ZO_ni:-LzwRuEs37H3Sp6ZO_nj:b-eh834l) ([raw file](https://github.com/cockroachdb/cockroach/blob/92f77c4a6cc031573f668953540bc229aa288be7/pkg/util/cgroups/cgroups.go#L139)):*
> ```Go
> 	for scanner.Scan() {
> 		fields := bytes.Split(scanner.Bytes(), []byte{':'})
> 		if len(fields) == 3 {
> ```

`len(fields)` should always be 3, there's something fishy going on if it's not. Maybe don't do anything about that (I didn't) but please leave a comment explaining that it's not a normal situation.

The nit to go with this comment is it's probably better for understandability to continue the loop in the extraordinary case than to put the logic under an if for the common case.  
___
*[pkg/util/cgroups/cgroups.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-LzwU0zM-1plHip_mN48:-LzwU0zM-1plHip_mN49:ba2j8pu) ([raw file](https://github.com/cockroachdb/cockroach/blob/300985df0d2e7a916739cdfff2744b34da36a109/pkg/util/cgroups/cgroups.go#L106)):*
> ```Go
> }
> 
> // Finds memory limit for cgroup V2 via looking into [controller mount path]/[leaf path]/memory.max
> ```

Does just looking at the leaf work in v2? It certainly doesn't in v1. 
___
*[pkg/util/cgroups/cgroups.go, line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-LzwTgyj7eZBY2sRwx7U:-LzwTgyj7eZBY2sRwx7V:b-7yxo65) ([raw file](https://github.com/cockroachdb/cockroach/blob/300985df0d2e7a916739cdfff2744b34da36a109/pkg/util/cgroups/cgroups.go#L141)):*
> ```Go
> 		if len(fields) == 3 {
> 			f1, f2 := string(fields[0]), string(fields[1])
> 			if f2 == "memory" || (f1 == "0" && f2 == "") {
> ```

I think there's a bug here in the case that you have the memory subsystem mounted as v1 but you also have a v2 hierarchy mounted and it shows up in this file before the memory controller. 
___
*[pkg/util/cgroups/cgroups.go, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-LzwT9nUExHqAxOuNHB6:-LzwT9nUExHqAxOuNHB7:bn75uh7) ([raw file](https://github.com/cockroachdb/cockroach/blob/300985df0d2e7a916739cdfff2744b34da36a109/pkg/util/cgroups/cgroups.go#L150)):*
> ```Go
> }
> 
> // Reads /proc/[pid]/mountinfo for cgoup or cgroup2 mount which defines the used version.
> ```

Why the change from /proc/self/mounts to /proc/self/mountinfo?

**Review by vladdy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44549)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @vladdy)

___
*[pkg/util/cgroups/cgroups.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-LzwRRRgAXtNdCNkiGIt:-Lzyimmx6zI1BzGrI3vW:b-fszb5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/92f77c4a6cc031573f668953540bc229aa288be7/pkg/util/cgroups/cgroups.go#L40)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Why `2`? It's a common pattern to have an exported function and then an unexported function with same name less the first character that has a different signature. 
</blockquote></details>

This was just me who forgot to remove the number.
___
*[pkg/util/cgroups/cgroups.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-LzwU0zM-1plHip_mN48:-Lzyj3z02GLZTCxyCqwc:b9zqsmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/300985df0d2e7a916739cdfff2744b34da36a109/pkg/util/cgroups/cgroups.go#L106)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Does just looking at the leaf work in v2? It certainly doesn't in v1. 
</blockquote></details>

Definitely. Cgroup v2 introduced a rule that processes may reside only in leaf nodes.
___
*[pkg/util/cgroups/cgroups.go, line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-LzwTgyj7eZBY2sRwx7U:-LzymbKD7BWNpAqE4Rq8:bb7v8t5) ([raw file](https://github.com/cockroachdb/cockroach/blob/300985df0d2e7a916739cdfff2744b34da36a109/pkg/util/cgroups/cgroups.go#L141)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think there's a bug here in the case that you have the memory subsystem mounted as v1 but you also have a v2 hierarchy mounted and it shows up in this file before the memory controller. 
</blockquote></details>

I guess this also deserves a comment, but I don't think we need to support the hybrid mode as I'm unaware of any container solutions using it. If we find such a user who runs the db in such mode, we could think about supporting it, but I chosen simplicity for now.
___
*[pkg/util/cgroups/cgroups.go, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-LzwT9nUExHqAxOuNHB6:-Lzyoojp4lGDUy_yi3C1:b-dxxh0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/300985df0d2e7a916739cdfff2744b34da36a109/pkg/util/cgroups/cgroups.go#L150)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Why the change from /proc/self/mounts to /proc/self/mountinfo?
</blockquote></details>

`mountinfo` is considered as the most authoritative source of mounts for process in Linux as for cases like namespace mounts, they will be missed from `mounts`

**Review by vladdy — COMMENTED** [review]
Pushed an update to this PR to address the feedback.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-:-LzypO0IBhmLS1UB2WiT:b-oebljw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @vladdy)

**Review by ajwerner — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44549)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @vladdy)

___
*[pkg/util/cgroups/cgroups.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-LzwU0zM-1plHip_mN48:-M-BP-zN0y5Q8hP2qoAM:b-4rwyyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/300985df0d2e7a916739cdfff2744b34da36a109/pkg/util/cgroups/cgroups.go#L106)):*
<details><summary><i>Previously, vladdy (Vlad Artamonov) wrote…</i></summary><blockquote>

Definitely. Cgroup v2 introduced a rule that processes may reside only in leaf nodes.
</blockquote></details>

Hmm, I want to test this. While I do understand that that's the case. Setting exist in parent nodes and apply to the leaves and can be lower than the leaves. 
___
*[pkg/util/cgroups/cgroups.go, line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-LzwTgyj7eZBY2sRwx7U:-M-BP9Yw86Xen3XPiS7T:bvfjq4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/300985df0d2e7a916739cdfff2744b34da36a109/pkg/util/cgroups/cgroups.go#L141)):*
<details><summary><i>Previously, vladdy (Vlad Artamonov) wrote…</i></summary><blockquote>

I guess this also deserves a comment, but I don't think we need to support the hybrid mode as I'm unaware of any container solutions using it. If we find such a user who runs the db in such mode, we could think about supporting it, but I chosen simplicity for now.
</blockquote></details>

I think it's silly to not fix this. It is extremely common to mount cgroup2 without any subsystems. I saw that as the default with systemd in ubuntu 19.10. 
___
*[pkg/util/cgroups/cgroups.go, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-LzwT9nUExHqAxOuNHB6:-M-BRbWY0CzvMtS5fRsN:bsmscq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/300985df0d2e7a916739cdfff2744b34da36a109/pkg/util/cgroups/cgroups.go#L150)):*
<details><summary><i>Previously, vladdy (Vlad Artamonov) wrote…</i></summary><blockquote>

`mountinfo` is considered as the most authoritative source of mounts for process in Linux as for cases like namespace mounts, they will be missed from `mounts`
</blockquote></details>

While I agree that mountinfo has more information, I'm not sure I understand what you mean. What I'm really curious about is whether you ran in to a specific issue that motivated the change or whether it was just theoretical.

 I perused the http://man7.org/linux/man-pages/man7/mount_namespaces.7.html page a bit and didn't really follow ways in which namespaces change the existences of mounts.

```
       The views provided by the /proc/[pid]/mounts, /proc/[pid]/mountinfo,
       and /proc/[pid]/mountstats files (all described in proc(5))
       correspond to the mount namespace in which the process with the PID
       [pid] resides.  (All of the processes that reside in the same mount
       namespace will see the same view in these files.)
```

I'm not curious than anything though I find the parsing logic you added to be a bit more bespoke and fragile I don't feel that strongly about it. I just really want to understand the motivating nuance. 
___
*[pkg/util/cgroups/cgroups.go, line 81 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-M-BQ-JA6Mmi9kCCZQ_X:-M-BQ-JA6Mmi9kCCZQ_Y:b-o6nqy3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ccae4334ff296229f24a0f9c0c796d1cd092b58/pkg/util/cgroups/cgroups.go#L81)):*
> ```Go
> 	stat, err := os.Open(statFilePath)
> 	if err != nil {
> 		return
> ```

sort of nit: naked returns are against our style guide. Please explicitly return the return values. 
___
*[pkg/util/cgroups/cgroups.go, line 90 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-M-BPxuZ0at0xfnpvzPF:-M-BPxu_A_DDfJneqZiu:bgjys9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ccae4334ff296229f24a0f9c0c796d1cd092b58/pkg/util/cgroups/cgroups.go#L90)):*
> ```Go
> 	for scanner.Scan() {
> 		fields := bytes.Fields(scanner.Bytes())
> 		if len(fields) == 2 {
> ```

nit-picking but I'd rather see this as:

```
if len(fields) != 2 || string(fields[0]) != "hierarchical_memory_limit" {
    continue
}
...
```

___
*[pkg/util/cgroups/cgroups.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-M-BQ5007a4bo744qnsc:-M-BQ5007a4bo744qnsd:b-o6nqy3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ccae4334ff296229f24a0f9c0c796d1cd092b58/pkg/util/cgroups/cgroups.go#L98)):*
> ```Go
> 				}
> 
> 				return
> ```

sort of nit: naked returns are against our style guide. Please explicitly return the return values. 
___
*[pkg/util/cgroups/cgroups.go, line 181 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-M-BQLcuD9jD_uYUr3Yl:-M-BQLcv-XVosAFjDnA-:b-qjzp10) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ccae4334ff296229f24a0f9c0c796d1cd092b58/pkg/util/cgroups/cgroups.go#L181)):*
> ```Go
> }
> 
> // Return version of cgroup mount for memory controller or `unknown`
> ```

nit: just also return an error here and get rid of all of the plumbing of the `unknown` symbol.

**Review by vladdy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44549)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @vladdy)

___
*[pkg/util/cgroups/cgroups.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-LzwU0zM-1plHip_mN48:-M-H3j2X8VO9k0W00Cf6:bk61yvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/300985df0d2e7a916739cdfff2744b34da36a109/pkg/util/cgroups/cgroups.go#L106)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Hmm, I want to test this. While I do understand that that's the case. Setting exist in parent nodes and apply to the leaves and can be lower than the leaves. 
</blockquote></details>

Well, it is my understanding after reading https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html#no-internal-process-constraint. Let me know if you still want me to test it.
___
*[pkg/util/cgroups/cgroups.go, line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-LzwTgyj7eZBY2sRwx7U:-M-H42IU78eIvJmWOiQR:b6757f5) ([raw file](https://github.com/cockroachdb/cockroach/blob/300985df0d2e7a916739cdfff2744b34da36a109/pkg/util/cgroups/cgroups.go#L141)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think it's silly to not fix this. It is extremely common to mount cgroup2 without any subsystems. I saw that as the default with systemd in ubuntu 19.10. 
</blockquote></details>

I guess the comment I added to the code was not clear. I'm unaware of containerization which would support the both methods at the same time. As the result, I would expect that a container running in a system with hybrid cgroup mode will use either v1 or v2 groups but not both. Also even systemd does not recommend using anything but pure v2 (https://github.com/systemd/systemd/blob/master/docs/CGROUP_DELEGATION.md):

```
To say this clearly, legacy and hybrid modes have no future. 
If you develop software today and don't focus on the unified mode, 
then you are writing software for yesterday, not tomorrow. 
They are primarily supported for compatibility reasons and 
will not receive new features. Sorry.
```

Probably, if we try not to support the hybrid mode (if it works for containers at all), we would encourage people to not use it.

I'm open to do a research about running a container with both cgroup versions if you still think its worth it.
___
*[pkg/util/cgroups/cgroups.go, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-LzwT9nUExHqAxOuNHB6:-M-H67eG0Q8w5VOYFgdz:bpsjiea) ([raw file](https://github.com/cockroachdb/cockroach/blob/300985df0d2e7a916739cdfff2744b34da36a109/pkg/util/cgroups/cgroups.go#L150)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

While I agree that mountinfo has more information, I'm not sure I understand what you mean. What I'm really curious about is whether you ran in to a specific issue that motivated the change or whether it was just theoretical.

 I perused the http://man7.org/linux/man-pages/man7/mount_namespaces.7.html page a bit and didn't really follow ways in which namespaces change the existences of mounts.

```
       The views provided by the /proc/[pid]/mounts, /proc/[pid]/mountinfo,
       and /proc/[pid]/mountstats files (all described in proc(5))
       correspond to the mount namespace in which the process with the PID
       [pid] resides.  (All of the processes that reside in the same mount
       namespace will see the same view in these files.)
```

I'm not curious than anything though I find the parsing logic you added to be a bit more bespoke and fragile I don't feel that strongly about it. I just really want to understand the motivating nuance. 
</blockquote></details>

No, you bring a valid question and I would prefer to avoid adding the parsing for `mountinfo`. Here is why I chosen to go the harder way (from http://man7.org/linux/man-pages/man5/proc.5.html): 

```
              This file contains information about mount points in the
              process's mount namespace (see mount_namespaces(7)).  It sup‐
              plies various information (e.g., propagation state, root of
              mount for bind mounts, identifier for each mount and its par‐
              ent) that is missing from the (older) /proc/[pid]/mounts file,
              and fixes various other problems with that file (e.g., nonex‐
              tensibility, failure to distinguish per-mount versus per-
              superblock options).
```

and I used the information about root of mount to find where cgroup is mounted which appears to be a better way to locate it. Overall, Linux community considers mounts to be non-extensible legacy, although I believe it will be around for years still. Let me know if you still want me to switch back to `/proc/[pid]/mounts`
___
*[pkg/util/cgroups/cgroups.go, line 81 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-M-BQ-JA6Mmi9kCCZQ_X:-M-H2IiK0Ffc6fjsao1O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ccae4334ff296229f24a0f9c0c796d1cd092b58/pkg/util/cgroups/cgroups.go#L81)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

sort of nit: naked returns are against our style guide. Please explicitly return the return values. 
</blockquote></details>

Done.
___
*[pkg/util/cgroups/cgroups.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-M-BQ5007a4bo744qnsc:-M-H2s1L5XsMj_ouHcPj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ccae4334ff296229f24a0f9c0c796d1cd092b58/pkg/util/cgroups/cgroups.go#L98)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

sort of nit: naked returns are against our style guide. Please explicitly return the return values. 
</blockquote></details>

Done.
___
*[pkg/util/cgroups/cgroups.go, line 181 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-M-BQLcuD9jD_uYUr3Yl:-M-Kzy-l1rLe_EKdmrrd:b-jl2ow0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ccae4334ff296229f24a0f9c0c796d1cd092b58/pkg/util/cgroups/cgroups.go#L181)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: just also return an error here and get rid of all of the plumbing of the `unknown` symbol. 
</blockquote></details>

Good idea! However, I changed it to use a bool variable instead of error to make things simpler.

**Review by ajwerner — COMMENTED** [review]
Very close. Thanks for all the research you put into this. 

> Reviewed 2 of 4 files at r1, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-:-M-LH3h15qQS33gNu9LA:b-69aw28)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @vladdy)

___
*[pkg/util/cgroups/cgroups.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-LzwU0zM-1plHip_mN48:-M-LFI79DQ4ipajFZbjm:bonco2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/300985df0d2e7a916739cdfff2744b34da36a109/pkg/util/cgroups/cgroups.go#L106)):*
<details><summary><i>Previously, vladdy (Vlad Artamonov) wrote…</i></summary><blockquote>

Well, it is my understanding after reading https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html#no-internal-process-constraint. Let me know if you still want me to test it.
</blockquote></details>

I did test sort of. Unfortunately when you set a parent limit it does not propagate to the child and it seems like there's no way to read it from just the leaf as far as I can tell. On the other hand, it seems like no containerization engines currently actually support v2 (I tried!). Let's leave a TODO noting this possibility.

```
ubuntu@ajwerner-test-0001:~$ cat  /sys/fs/cgroup/user.slice/user-1000.slice/session-3.scope/memory.max                                                                                                                                                                         
max
ubuntu@ajwerner-test-0001:~$ cat  /sys/fs/cgroup/user.slice/user-1000.slice/memory.max                                                                                                                                                                                         
999997440
ubuntu@ajwerner-test-0001:~$ cat /dev/urandom | base64 -w 0 | head -c 1000000000 | sort                                                                                                                                                                                        
Killed
```
___
*[pkg/util/cgroups/cgroups.go, line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-LzwTgyj7eZBY2sRwx7U:-M-L5zTs6yJ378cC94-H:b-24hiob) ([raw file](https://github.com/cockroachdb/cockroach/blob/300985df0d2e7a916739cdfff2744b34da36a109/pkg/util/cgroups/cgroups.go#L141)):*
<details><summary><i>Previously, vladdy (Vlad Artamonov) wrote…</i></summary><blockquote>

I guess the comment I added to the code was not clear. I'm unaware of containerization which would support the both methods at the same time. As the result, I would expect that a container running in a system with hybrid cgroup mode will use either v1 or v2 groups but not both. Also even systemd does not recommend using anything but pure v2 (https://github.com/systemd/systemd/blob/master/docs/CGROUP_DELEGATION.md):

```
To say this clearly, legacy and hybrid modes have no future. 
If you develop software today and don't focus on the unified mode, 
then you are writing software for yesterday, not tomorrow. 
They are primarily supported for compatibility reasons and 
will not receive new features. Sorry.
```

Probably, if we try not to support the hybrid mode (if it works for containers at all), we would encourage people to not use it.

I'm open to do a research about running a container with both cgroup versions if you still think its worth it.
</blockquote></details>

Thanks! that clears that up for me. I do see by default in 19.04 LTS boots in this hybrid mode and systemd knows how to use it. We're getting saved by the order of the subsystems in the file and it just seems a little bit better to be explicit about the fact that they can (and sometimes in the wild do) both exist in the file. 
```
12:freezer:/
11:pids:/
10:perf_event:/
9:hugetlb:/
8:blkio:/
7:cpu,cpuacct:/
6:net_cls,net_prio:/
5:memory:/
4:rdma:/
3:cpuset:/
2:devices:/
1:name=systemd:/
0::/
```
___
*[pkg/util/cgroups/cgroups.go, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-LzwT9nUExHqAxOuNHB6:-M-L7DSo-cvbyhRudtBk:b39bpo0) ([raw file](https://github.com/cockroachdb/cockroach/blob/300985df0d2e7a916739cdfff2744b34da36a109/pkg/util/cgroups/cgroups.go#L150)):*
<details><summary><i>Previously, vladdy (Vlad Artamonov) wrote…</i></summary><blockquote>

No, you bring a valid question and I would prefer to avoid adding the parsing for `mountinfo`. Here is why I chosen to go the harder way (from http://man7.org/linux/man-pages/man5/proc.5.html): 

```
              This file contains information about mount points in the
              process's mount namespace (see mount_namespaces(7)).  It sup‐
              plies various information (e.g., propagation state, root of
              mount for bind mounts, identifier for each mount and its par‐
              ent) that is missing from the (older) /proc/[pid]/mounts file,
              and fixes various other problems with that file (e.g., nonex‐
              tensibility, failure to distinguish per-mount versus per-
              superblock options).
```

and I used the information about root of mount to find where cgroup is mounted which appears to be a better way to locate it. Overall, Linux community considers mounts to be non-extensible legacy, although I believe it will be around for years still. Let me know if you still want me to switch back to `/proc/[pid]/mounts`
</blockquote></details>

Works for me. Thanks for the lesson!

**Review by vladdy — COMMENTED** [review]
Thank you for all the feedback! Just need to understand what is your view on making the hybrid cgroup file parsing more explicit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-:-M-RFBNc4BUQ9P2_hXtv:bq2i3k0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/util/cgroups/cgroups.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-LzwU0zM-1plHip_mN48:-M-RC0kB0DO5KdQbiXkO:b-2nkq5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/300985df0d2e7a916739cdfff2744b34da36a109/pkg/util/cgroups/cgroups.go#L106)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I did test sort of. Unfortunately when you set a parent limit it does not propagate to the child and it seems like there's no way to read it from just the leaf as far as I can tell. On the other hand, it seems like no containerization engines currently actually support v2 (I tried!). Let's leave a TODO noting this possibility.

```
ubuntu@ajwerner-test-0001:~$ cat  /sys/fs/cgroup/user.slice/user-1000.slice/session-3.scope/memory.max                                                                                                                                                                         
max
ubuntu@ajwerner-test-0001:~$ cat  /sys/fs/cgroup/user.slice/user-1000.slice/memory.max                                                                                                                                                                                         
999997440
ubuntu@ajwerner-test-0001:~$ cat /dev/urandom | base64 -w 0 | head -c 1000000000 | sort                                                                                                                                                                                        
Killed
```
</blockquote></details>

I think session slices are not the real slices but I think we can stop further investigations and wait for containers to adopt for v2 before reviewing. If it matters, I was able to get podman+criu containers working and that's where the test file contents for v2 were copied from. I'll leave a TODO explaining that the detection is not ideal and can be improved.
___
*[pkg/util/cgroups/cgroups.go, line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-LzwTgyj7eZBY2sRwx7U:-M-REJIDBtmBWS0X1Xe5:b10r5sh) ([raw file](https://github.com/cockroachdb/cockroach/blob/300985df0d2e7a916739cdfff2744b34da36a109/pkg/util/cgroups/cgroups.go#L141)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Thanks! that clears that up for me. I do see by default in 19.04 LTS boots in this hybrid mode and systemd knows how to use it. We're getting saved by the order of the subsystems in the file and it just seems a little bit better to be explicit about the fact that they can (and sometimes in the wild do) both exist in the file. 
```
12:freezer:/
11:pids:/
10:perf_event:/
9:hugetlb:/
8:blkio:/
7:cpu,cpuacct:/
6:net_cls,net_prio:/
5:memory:/
4:rdma:/
3:cpuset:/
2:devices:/
1:name=systemd:/
0::/
```
</blockquote></details>

I like being explicit! How do you see it to be done in that way?

**Review by ajwerner — APPROVED** [review]
Mod the nits :lgtm: 

> Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-:-M-We6hd1sBNIgXjei1-:b-x44jeo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @vladdy)

___
*[pkg/util/cgroups/cgroups.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-LzwU0zM-1plHip_mN48:-M-WeA6J4mJ68CyP4MLX:b-k1lnri) ([raw file](https://github.com/cockroachdb/cockroach/blob/300985df0d2e7a916739cdfff2744b34da36a109/pkg/util/cgroups/cgroups.go#L106)):*
<details><summary><i>Previously, vladdy (Vlad Artamonov) wrote…</i></summary><blockquote>

I think session slices are not the real slices but I think we can stop further investigations and wait for containers to adopt for v2 before reviewing. If it matters, I was able to get podman+criu containers working and that's where the test file contents for v2 were copied from. I'll leave a TODO explaining that the detection is not ideal and can be improved.
</blockquote></details>

I have no idea what `session slices are not the real slices` means but I'm :thumbsup: on the comment and we can move on. 
___
*[pkg/util/cgroups/cgroups.go, line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44549#-LzwTgyj7eZBY2sRwx7U:-M-WcYpICvKdZs4xQXJe:b-oqkuev) ([raw file](https://github.com/cockroachdb/cockroach/blob/300985df0d2e7a916739cdfff2744b34da36a109/pkg/util/cgroups/cgroups.go#L141)):*
<details><summary><i>Previously, vladdy (Vlad Artamonov) wrote…</i></summary><blockquote>

I like being explicit! How do you see it to be done in that way?
</blockquote></details>

I was envisioning doing it the way it was done before. If you find the unified path, put it in a var. If you find the memory path, return it. When you finish parsing, if you found the unified path return it. 

Essentially:

```
var unifiedPathIfFound string
for scanner.Scan() {
    ...
        if  (f1 == "0" && f2 == "") {
            unifiedPathIfFound = string(fields[2])
        } else if f2 == "memory" {
            return string(fields[2]), nil
       }
   }
}
return unifiedPathIfFound, nil
```

-----

Another nit: please call `fields[0]` `f0`. Having an `f2` and then having it mean something different from `fields[2]` sort of makes my head explode. And lastly, I still prefer:

```
if len(fields) != 3 {
    // The lines should always have three fields, there's something fishy here.
    continue
}
...
```
to putting the normal logic under the conditional.

**Pull request merged**
