### PR TITLE
raft: add ability to determine whether we can safely de-fortify

### PR DESCRIPTION
**Pull request by arulajmani**
This patch starts saving a leaderMaxSupported timestamp on the
FortificationTracker, which corresponds to the largest timestamp that's
ever been returned to callers of LeadSupportUntil. Consequently, this is
then serves as an upper bound of a leader lease for a given term.

We then use this to ensure we don't regress a lease's expiration when
we cease to become the leader. In particular, we use it to compute
whether we can de-fortify or not. This then ensures we don't vote for
another peer when we shouldn't (as we aren't de-fortified), we don't
call an election when we shouldn't (which would be quite bad given
it de-fortifies the entire raft group), and we don't broadcast a
MsgDefortifyLeader to the entire raft group.

Informs https://github.com/cockroachdb/cockroach/issues/129098

Release note: None

### CODE REVIEW

**Comment by arulajmani** [comment]
@nvanbenschoten please ignore the diffs to the check quorum data driven test files for now. They're doing the right thing by not allowing a leader to step down because of check quorum because the leader has previously returned `hlc.MaxTimestamp` to a caller of `LeadSupportUntil` previously, but they're breaking the essence of these tests. 

While I think a bit more on getting that essence back, everything else should be good for a second pass (thanks for the quick first pass on Slack earlier today). If this was an internal google doc, I'd say we've gone from a 30% to a 60% :)

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132108)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`-- commits` line 20 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132108#-O8d3aGx2C-ftemrxbWL):*
"this is then serves"
___
*[`-- commits` line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132108#-O8d3srSCBFcGGz4cpzt):*
"MsgDeFortifyLeader"
___
*[`pkg/raft/tracker/fortificationtracker.go` line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132108#-O8d5RL499svMVDSF7tP:-O8d5RL499svMVDSF7tQ:b-pdm6qy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6166bf2448d4d2b09c6a27c58a2e913b7b6c29f/pkg/raft/tracker/fortificationtracker.go#L158)):*
> ```Go
> // LeadSupportUntil for the term being tracked does not advance any longer, now
> // that the leadership term has ended.
> func (ft *FortificationTracker) OnLeaderStepDown() {
> ```

In Slack, it sounds like we're leaning towards getting rid of this method and `isLeadSupportUntilFrozen` and just plumbing in `r.state` where needed.
___
*[`pkg/raft/tracker/fortificationtracker.go` line 217 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132108#-O8d51Em1i-086Zs1eOW:-O8d51Em1i-086Zs1eOX:b3lg9p4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6166bf2448d4d2b09c6a27c58a2e913b7b6c29f/pkg/raft/tracker/fortificationtracker.go#L217)):*
> ```Go
> // atomicTimestamp is a thin wrapper to provide atomic access to a timestamp.
> type atomicTimestamp struct {
> 	syncutil.Mutex
> ```

I don't see a reason to embed the mutex and inherit all of its methods.
___
*[`pkg/raft/tracker/fortificationtracker.go` line 239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132108#-O8d59p09mukxTyXpyTP:-O8d59p09mukxTyXpyTQ:bt4r4nn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6166bf2448d4d2b09c6a27c58a2e913b7b6c29f/pkg/raft/tracker/fortificationtracker.go#L239)):*
> ```Go
> 	a.Lock()
> 	defer a.Unlock()
> 	a.ts = hlc.MinTimestamp
> ```

`hlc.Timestamp{}` is probably what we want.

**Review by iskettaneh — COMMENTED** [review]
> Reviewed 7 of 7 files at r3, 1 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132108)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/raft/status.go` line 135 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132108#-O8xGTSpDkcMMlUimWWz:-O8xGTSpDkcMMlUimWX-:b-dtapjs) ([raw file](https://github.com/cockroachdb/cockroach/blob/20863c885c9628e1a3468b662ba292de50cc71f9/pkg/raft/status.go#L135)):*
> ```Go
> 	// StateLeader. The replica may have been the leader and stepped down to a
> 	// follower before its lead support ran out.
> 	s.LeadSupportUntil = r.fortificationTracker.LeadSupportUntil(pb.StateLeader)
> ```

Why are we always assuming that the state is leader?
___
*[`pkg/raft/tracker/fortificationtracker.go` line 74 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132108#-O8xGnGlAEnNhHMYfScX:-O8xGnGlAEnNhHMYfScY:b-obr5gh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f28a8179af4e50014bee9f7d8ae61bd21b7f9a31/pkg/raft/tracker/fortificationtracker.go#L74)):*
> ```Go
> 	clear(ft.fortification)
> 	// TODO(arul): when we introduce ft.LeadSupportUntil we need to make sure it
> 	// isn't reset here, because we don't want it to regress when a leader steps
> ```

The todo said that we need to make sure it isn't reset here. Just making sure that resetting here is actually intended
___
*[`pkg/raft/tracker/fortificationtracker.go` line 166 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132108#-O8xH4TE6DEmCDMASqGN:-O8xH4TE6DEmCDMASqGO:b2ni78k) ([raw file](https://github.com/cockroachdb/cockroach/blob/20863c885c9628e1a3468b662ba292de50cc71f9/pkg/raft/tracker/fortificationtracker.go#L166)):*
> ```Go
> 		// If leaderMaxSupported is empty, it means that we've never returned any
> 		// timestamps to the layers above in calls to LeadSupportUntil. We should be
> 		// able to de-fortify. If a tree falls in a forrest ...
> ```

lol
___
*[`pkg/raft/tracker/fortificationtracker.go` line 207 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132108#-O8xCEjGEVZIG8LJib87:-O8xCEjGEVZIG8LJib88:b60ppro) ([raw file](https://github.com/cockroachdb/cockroach/blob/20863c885c9628e1a3468b662ba292de50cc71f9/pkg/raft/tracker/fortificationtracker.go#L207)):*
> ```Go
> 
> // atomicTimestamp is a thin wrapper to provide atomic access to a timestamp.
> type atomicTimestamp struct {
> ```

Do we need to add this to a more shared directory just incase someone else wants to use it?

**Review by arulajmani — COMMENTED** [review]
TFTR; RFAL 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132108#-:-O8xJ9nz7snDWgdHYgiz:b-jopna1)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @iskettaneh and @nvanbenschoten)

___
*[`pkg/raft/status.go` line 135 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132108#-O8xGTSpDkcMMlUimWWz:-O8xHmnU2P26d2w3_oXs:b-789wbp) ([raw file](https://github.com/cockroachdb/cockroach/blob/20863c885c9628e1a3468b662ba292de50cc71f9/pkg/raft/status.go#L135)):*
<details><summary><i>Previously, iskettaneh wrote…</i></summary><blockquote>

Why are we always assuming that the state is leader?
</blockquote></details>

Nice catch. Unintentional. Fixed.
___
*[`pkg/raft/tracker/fortificationtracker.go` line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132108#-O8d5RL499svMVDSF7tP:-O8wzH_M26f4zXv23vZE:bot6wbx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6166bf2448d4d2b09c6a27c58a2e913b7b6c29f/pkg/raft/tracker/fortificationtracker.go#L158)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

In Slack, it sounds like we're leaning towards getting rid of this method and `isLeadSupportUntilFrozen` and just plumbing in `r.state` where needed.
</blockquote></details>

Done and removed this method.
___
*[`pkg/raft/tracker/fortificationtracker.go` line 217 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132108#-O8d51Em1i-086Zs1eOW:-O8gfzKW1ry3yBrijslU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6166bf2448d4d2b09c6a27c58a2e913b7b6c29f/pkg/raft/tracker/fortificationtracker.go#L217)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I don't see a reason to embed the mutex and inherit all of its methods.
</blockquote></details>

Done.
___
*[`pkg/raft/tracker/fortificationtracker.go` line 239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132108#-O8d59p09mukxTyXpyTP:-O8gfyaP6ewSlWWB7ndk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6166bf2448d4d2b09c6a27c58a2e913b7b6c29f/pkg/raft/tracker/fortificationtracker.go#L239)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`hlc.Timestamp{}` is probably what we want.
</blockquote></details>

Done.
___
*[`pkg/raft/tracker/fortificationtracker.go` line 74 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132108#-O8xGnGlAEnNhHMYfScX:-O8xHx6oBr8zo2eVIbuI:b-muk7w2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f28a8179af4e50014bee9f7d8ae61bd21b7f9a31/pkg/raft/tracker/fortificationtracker.go#L74)):*
<details><summary><i>Previously, iskettaneh wrote…</i></summary><blockquote>

The todo said that we need to make sure it isn't reset here. Just making sure that resetting here is actually intended
</blockquote></details>

Yeah, this is intentional. We've since decided that we'll not `Reset` the fortification tracker every time we call `raft.reset()` -- instead, we `Reset` only in `becomeLeader`. As a result, this state is going to be kept around even when a leader steps down to a follower, until it steps up again to become a leader. At that point, it shouldn't be possible to regress the `LeadSupportUntil`, as the leader will only campaign once it's de-fortified itself (which will happen once `LeadSupportUntil` is in the past).
___
*[`pkg/raft/tracker/fortificationtracker.go` line 166 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132108#-O8xH4TE6DEmCDMASqGN:-O8xIhNq7Hdcv7SYv22R:bt1323n) ([raw file](https://github.com/cockroachdb/cockroach/blob/20863c885c9628e1a3468b662ba292de50cc71f9/pkg/raft/tracker/fortificationtracker.go#L166)):*
<details><summary><i>Previously, iskettaneh wrote…</i></summary><blockquote>

lol
</blockquote></details>

Heh I forgot I left this in. 
___
*[`pkg/raft/tracker/fortificationtracker.go` line 207 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132108#-O8xCEjGEVZIG8LJib87:-O8xIpox-pBa3OeqP4GE:bi6qv1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/20863c885c9628e1a3468b662ba292de50cc71f9/pkg/raft/tracker/fortificationtracker.go#L207)):*
<details><summary><i>Previously, iskettaneh wrote…</i></summary><blockquote>

Do we need to add this to a more shared directory just incase someone else wants to use it?
</blockquote></details>

IMO it's fine here for now -- it's pretty specific to our use case (e.g. the `Forward` call returns a timestamp instead of a boolean like `hlc.Timestamp.Forward()` does).

**Review by iskettaneh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132108)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by arulajmani** [comment]
Thanks!

bors r=iskettaneh

**Pull request merged**
