### PR TITLE
importccl: add userfile import tests and import benchmark

### PR DESCRIPTION
**Pull request by adityamaru**
This change adds simple unit tests to ensure we can import from the new
userfile ExternalStorage. It also adds a benchmark to compare the
performance of importing from nodelocal against importing from userfile
storage.

Informs: #51222

### CODE REVIEW

**Comment by adityamaru** [comment]
I will rebase once #50981 is merged in. I just wanted to sanity check that import works as expected, I am not sure to what degree we want to test the different kinds of IMPORT from UserFileTableStorage, considering the individual pieces of the ExternalStorage have their own tests and IMPORT itself is tested extensively against nodelocal.

**Review by miretskiy — CHANGES_REQUESTED** [review]
> Reviewed 6 of 12 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51077)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @miretskiy)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 2861 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51077#-MBeqLQ5EnkV6oxNQw5-:-MBeqLQ5EnkV6oxNQw50:b-9ncs83) ([raw file](https://github.com/cockroachdb/cockroach/blob/55bc4013ee2c05774be89bcc39231a38ab410fbc/pkg/ccl/importccl/import_stmt_test.go#L2861)):*
> ```
> 000000
> ```

This benchmark, as well as the benchmark you have copied it from, are completely
broken, and don't really report anything.

1. This benchmark runs only once, trying to co-opt b.N parameter into some
function of bytes. 
2. These benchmarks use `makeCSVData(b, numFiles, b.N*100, nodes, 16)` files.  It *seems* that these files are large, ... but they are not.  You need to run the benchmark with COCKROACH_REWRITE_CSV_TESTDATA=true environment variable to tell this method to regenerate data.  Otherwise, you're importing few KBs.  Even with this env variable,
the file is still tiny (only 87K).  Particularly important for your benchmark, userfile storage
chunks files into 4MB chunks (if I recall correctly).  I'd say your import file should reflect that.
I would just generate brand new file and use that instead;  Generate it in a temp directory.
Make it large enough 10?50MB? something like that.
3.  Finally, you need to call b.SetBytes() to set the number of bytes processed by operation.
Since you run the import only once, you should set it to the size of the input file.
This will report throughput.

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51077)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 2861 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51077#-MBeqLQ5EnkV6oxNQw5-:-MBgdutl9w5uoN2dtKcK:b-xeofor) ([raw file](https://github.com/cockroachdb/cockroach/blob/55bc4013ee2c05774be89bcc39231a38ab410fbc/pkg/ccl/importccl/import_stmt_test.go#L2861)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> ```
> 000000
> ```

This benchmark, as well as the benchmark you have copied it from, are completely
broken, and don't really report anything.

1. This benchmark runs only once, trying to co-opt b.N parameter into some
function of bytes. 
2. These benchmarks use `makeCSVData(b, numFiles, b.N*100, nodes, 16)` files.  It *seems* that these files are large, ... but they are not.  You need to run the benchmark with COCKROACH_REWRITE_CSV_TESTDATA=true environment variable to tell this method to regenerate data.  Otherwise, you're importing few KBs.  Even with this env variable,
the file is still tiny (only 87K).  Particularly important for your benchmark, userfile storage
chunks files into 4MB chunks (if I recall correctly).  I'd say your import file should reflect that.
I would just generate brand new file and use that instead;  Generate it in a temp directory.
Make it large enough 10?50MB? something like that.
3.  Finally, you need to call b.SetBytes() to set the number of bytes processed by operation.
Since you run the import only once, you should set it to the size of the input file.
This will report throughput.


</blockquote></details>

Thanks for pointing this out. I have fixed the benchmarks to generate a single file ~50Mib and then import it either from a nodelocal or usefile storage source. The throughputs for both the imports seem comparable assuming the benchmarks are correctly setup.

**Review by miretskiy — CHANGES_REQUESTED** [review]
Let me know when the other PR merges -- i'd like to take a look after.

> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51077#-:-MBiWXDiDE3D2DUdG1pQ:b-tyb1fo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @miretskiy)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 2853 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51077#-MBiSrs1-j99VY6b64to:-MBiSrs1-j99VY6b64tp:b-nqb681) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4de7796db1d143eb90a0e0795a7204ee7881a5a/pkg/ccl/importccl/import_stmt_test.go#L2853)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
> 	// Set up a directory for the data files.
> 	err := os.Mkdir(filepath.Join(baseDir, "test"), 0777)
> 	require.NoError(b, err)
> 	// Write the test data into a file.
> 	r, err := csvGen.Open()
> 	defer r.Close()
> 	content, err := ioutil.ReadAll(r)
> 	require.NoError(b, err)
> 	err = ioutil.WriteFile(filepath.Join(baseDir, "test", "data"), content, 0666)
> 	require.NoError(b, err)
> ```
</details>


I would do it slightly differently:
f, err := ioutil.TempFile(baseDir, "test_file")
require.NoError(t, err)
numBytes, err := io.Copy(f, r)
require.NoError(t, err)
b.SetBytes(numBytes)
___
*[pkg/ccl/importccl/import_stmt_test.go, line 2859 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51077#-MBiSpAm2zBRnjw3wjgy:-MBiRjeo-oEzyL1pTqrb:bqfvaa6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4de7796db1d143eb90a0e0795a7204ee7881a5a/pkg/ccl/importccl/import_stmt_test.go#L2859)):*
> ```Go
> 	// tweaked.
> 	require.GreaterOrEqual(b, len(content), 50*1024*1024)
> 	require.LessOrEqual(b, len(content), 55*1024*1024)
> ```

I'd say that it's probably a bit too much -- it really doesn't matter how exactly what the size is.
you're still reporting correct throughput.  I'd drop those 2 checks and a comment.
___
*[pkg/ccl/importccl/import_stmt_test.go, line 2869 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51077#-MBiVQih2xHaTaLg4neV:-MBiVQih2xHaTaLg4neW:b11oy9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4de7796db1d143eb90a0e0795a7204ee7881a5a/pkg/ccl/importccl/import_stmt_test.go#L2869)):*
> ```Go
> 			CSV DATA ('%s')`,
> 			"nodelocal://0/test/data",
> 		))
> ```

I think it makes sense to refactor this entire benchmark into helper -- the exact code is repeated in the userfile upload benchmark below:

func benchUserUpload(b *testing.B, uploadBaseURI string) {
  ....
  sqlDB.Exec(b,
		fmt.Sprintf(
			`IMPORT TABLE t (a INT8 PRIMARY KEY, b STRING, INDEX (b), INDEX (a, b))
			CSV DATA ('%s/test_file')`,
			uploadBaseURI
		))
}

Invoke this as:
 benchUserUpload(b, "nodelocal://0")
and
 benchUserUpload(b, "userfile://defaultdb.public.root")

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51077)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 2853 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51077#-MBiSrs1-j99VY6b64to:-MBig6KuB1wSVwLB2Yit:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4de7796db1d143eb90a0e0795a7204ee7881a5a/pkg/ccl/importccl/import_stmt_test.go#L2853)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> ```
> 	// Set up a directory for the data files.
> 	err := os.Mkdir(filepath.Join(baseDir, "test"), 0777)
> 	require.NoError(b, err)
> 	// Write the test data into a file.
> 	r, err := csvGen.Open()
> 	defer r.Close()
> 	content, err := ioutil.ReadAll(r)
> 	require.NoError(b, err)
> 	err = ioutil.WriteFile(filepath.Join(baseDir, "test", "data"), content, 0666)
> 	require.NoError(b, err)
> ```

I would do it slightly differently:
f, err := ioutil.TempFile(baseDir, "test_file")
require.NoError(t, err)
numBytes, err := io.Copy(f, r)
require.NoError(t, err)
b.SetBytes(numBytes)
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/import_stmt_test.go, line 2859 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51077#-MBiSpAm2zBRnjw3wjgy:-MBif93xAZOtb0-QKoxf:b-hrfpdf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4de7796db1d143eb90a0e0795a7204ee7881a5a/pkg/ccl/importccl/import_stmt_test.go#L2859)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I'd say that it's probably a bit too much -- it really doesn't matter how exactly what the size is.
you're still reporting correct throughput.  I'd drop those 2 checks and a comment.
</blockquote></details>

Done. Dropped the file size to 25MiB.
___
*[pkg/ccl/importccl/import_stmt_test.go, line 2869 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51077#-MBiVQih2xHaTaLg4neV:-MBif6Q3AkTCo2zwje-A:b-cizd6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4de7796db1d143eb90a0e0795a7204ee7881a5a/pkg/ccl/importccl/import_stmt_test.go#L2869)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I think it makes sense to refactor this entire benchmark into helper -- the exact code is repeated in the userfile upload benchmark below:

func benchUserUpload(b *testing.B, uploadBaseURI string) {
  ....
  sqlDB.Exec(b,
		fmt.Sprintf(
			`IMPORT TABLE t (a INT8 PRIMARY KEY, b STRING, INDEX (b), INDEX (a, b))
			CSV DATA ('%s/test_file')`,
			uploadBaseURI
		))
}

Invoke this as:
 benchUserUpload(b, "nodelocal://0")
and
 benchUserUpload(b, "userfile://defaultdb.public.root")
</blockquote></details>

Done. nodelocal requires writing to a file, while userfile requires writing to the ExternalStorage, but apart from that all the logic is shared.

**Comment by adityamaru** [comment]
@miretskiy RFAL!

**Review by miretskiy — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51077)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

**Pull request merged**
