### PR TITLE
opt: fold unary minus operations

### PR DESCRIPTION
**Pull request by justinj**
This commit introduces a new rule, FoldUnaryMinus, which transforms
constant expressions of the form (UnaryMinus x) to -x.

There were some cases around this which would result in us not correctly
recognizing expressions like -1:::FLOAT as constant, causing us to
perform a full table scan instead of a point lookup.

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/norm/custom_funcs.go, line 766 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26926#-LFblzag4C9hb1XaPwbo:-LFblzag4C9hb1XaPwbp:b10mdiy) ([raw file](https://github.com/cockroachdb/cockroach/blob/582b4f45ce28c19c0dbf42e6fda744ba7e8c1ca1/pkg/sql/opt/norm/custom_funcs.go#L766)):*
> ```Go
> 
> // NegateNumeric applies a unary minus to a numeric value.
> func (c *CustomFuncs) NegateNumeric(input memo.GroupID) memo.GroupID {
> ```

I don't think we should duplicate this logic. We should be using the logic in `eval.go`, for example in `UnaryOps[UnaryMinus]`.

---

*[pkg/sql/opt/norm/custom_funcs.go, line 777 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26926#-LFbnheL-EmotJoLbVzA:-LFbnheL-EmotJoLbVzB:b-vgyuqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/582b4f45ce28c19c0dbf42e6fda744ba7e8c1ca1/pkg/sql/opt/norm/custom_funcs.go#L777)):*
> ```Go
> 		id = c.f.InternDatum(tree.NewDFloat(-*t))
> 	case *tree.DInt:
> 		id = c.f.InternDatum(tree.NewDInt(-*t))
> ```

What if the existing value is -MIN_INT, so there's no way to negate it without overflow?

I think you need: `CanFoldUnaryMinus` and `FoldUnaryMinus` helper functions. We'll want function pairs like this for all the constant folding cases (Plus, Minus, Multiple, etc.). Our other option is to define an `Error` operator that will trigger a run-time error. That would cut down on needing lots of `Can` functions, since we could generate one of those when we detect overflow.

@radu, what do you think the best approach would be?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26926)*

**Comment by justinj** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/norm/custom_funcs.go, line 766 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26926#-LFblzag4C9hb1XaPwbo:-LFcyVHM0iVLBcw4ir0U:byscoyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/582b4f45ce28c19c0dbf42e6fda744ba7e8c1ca1/pkg/sql/opt/norm/custom_funcs.go#L766)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I don't think we should duplicate this logic. We should be using the logic in `eval.go`, for example in `UnaryOps[UnaryMinus]`.
</blockquote></details>

Pulled it out into functions.

---

*[pkg/sql/opt/norm/custom_funcs.go, line 777 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26926#-LFbnheL-EmotJoLbVzA:-LFcyaLz3G0EkejyiO6w:bdc58rl) ([raw file](https://github.com/cockroachdb/cockroach/blob/582b4f45ce28c19c0dbf42e6fda744ba7e8c1ca1/pkg/sql/opt/norm/custom_funcs.go#L777)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

What if the existing value is -MIN_INT, so there's no way to negate it without overflow?

I think you need: `CanFoldUnaryMinus` and `FoldUnaryMinus` helper functions. We'll want function pairs like this for all the constant folding cases (Plus, Minus, Multiple, etc.). Our other option is to define an `Error` operator that will trigger a run-time error. That would cut down on needing lots of `Can` functions, since we could generate one of those when we detect overflow.

@radu, what do you think the best approach would be?
</blockquote></details>

Done, I did the `CanFoldUnaryMinus` approach for now since there are CCL tests which require this change before turning on the optimizer by default, we can revisit the `Error` approach afterwards, if need be.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26926)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 7 of 7 files at r2.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/norm/testdata/rules/combo, line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26926#-LFi9aK36Bg0b43Y_J5X:-LFi9aK36Bg0b43Y_J5Y:bd7rhmd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d96b43412de3c0c4aad292c77b863ea382548564/pkg/sql/opt/norm/testdata/rules/combo#L138)):*
> ```
>   +           └── a.k = xy.x [type=bool, outer=(1,6), constraints=(/1: (/NULL - ]; /6: (/NULL - ])]
> ================================================================================
> PruneJoinRightCols
> ```

Did you run `make generate PKG=./pkg/sql/opt...`? I think these diffs are here because `pkg/sql/opt/rule_name_string.go` needs to be updated

---

*[pkg/sql/sem/tree/eval.go, line 67 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26926#-LFiAV6G-M2gt8OzZACz:-LFiAV6G-M2gt8OzZAD-:bj72gv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d96b43412de3c0c4aad292c77b863ea382548564/pkg/sql/sem/tree/eval.go#L67)):*
> ```Go
> const SecondsInDay = 24 * 60 * 60
> 
> // Negate returns the negative of a non-math.MinInt64 DInt.
> ```

Maybe say "should not be called with math.MinInt64, since that will cause integer overflow" or something like that... 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26926#-:-LFiAyqXCZf0jvDp_A4L:bnfp4nl)*

**Comment by rytaft** [comment]
Reviewed 5 of 5 files at r3.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/memo/typing.go, line 353 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26926#-LFs-d-E0i1XIaHO8KSZ:-LFs-d-E0i1XIaHO8KS_:bvz6ocp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d25e44b7aa15a10fa811831a1ba157f69ee43fca/pkg/sql/opt/memo/typing.go#L353)):*
> ```Go
> // a datum referring to the evaluated result. If an appropriate overload is not
> // found, EvalUnaryOp returns an error.
> func EvalUnaryOp(evalCtx *tree.EvalContext, op opt.Operator, ev ExprView) (tree.Datum, error) {
> ```

I'm not convinced this is the right place for this function. Why not just put it in `norm/custom_funcs.go` where it's called?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26926)*

**Comment by andy-kimball** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/memo/typing.go, line 353 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26926#-LFs-d-E0i1XIaHO8KSZ:-LFs18xyBy3q3Ld5JsWu:btpqqbb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d25e44b7aa15a10fa811831a1ba157f69ee43fca/pkg/sql/opt/memo/typing.go#L353)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I'm not convinced this is the right place for this function. Why not just put it in `norm/custom_funcs.go` where it's called?
</blockquote></details>

This function doesn't really fit perfectly in either place. We shouldn't be searching for overloads in `norm` (that logic needs to be in a single place). But we shouldn't be evaluating functions in `typing.go`.  Probably we should have a `FindUnaryOverload` function in `typing.go`, and then the `EvalUnaryOp` function in `norm`. But I don't think we should do that right now, so I'm OK with the function living in either place until we can factor it better.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26926)*

**Comment by rytaft** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/memo/typing.go, line 353 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26926#-LFs-d-E0i1XIaHO8KSZ:-LFsC70t7tmTeSiDfVhZ:b-15825i) ([raw file](https://github.com/cockroachdb/cockroach/blob/d25e44b7aa15a10fa811831a1ba157f69ee43fca/pkg/sql/opt/memo/typing.go#L353)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This function doesn't really fit perfectly in either place. We shouldn't be searching for overloads in `norm` (that logic needs to be in a single place). But we shouldn't be evaluating functions in `typing.go`.  Probably we should have a `FindUnaryOverload` function in `typing.go`, and then the `EvalUnaryOp` function in `norm`. But I don't think we should do that right now, so I'm OK with the function living in either place until we can factor it better.
</blockquote></details>

ok sounds good

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26926)*

**Comment by justinj** [comment]
TFTRs, going to rebase+merge this

**Pull request merged**
