### PR TITLE
sqlccl: include runnable, `trasform_only` IMPORT stmt in jobs text

### PR DESCRIPTION
**Pull request by dt**
while the original stmt doesn’t make sense as it also runs a RESTORE that already has its own job, if we add `transform_only`, we should have an essentially runnable stmt that corresponds to the job’s actual tracked work (storage URI sanitation notwithstanding).

it’s still a bit wonky having two jobs with one that looks very similar, but its the best we can do for now.

### CODE REVIEW

**Review by madelynnblue — APPROVED** [review]
Oh this is not pretty, but I can't think of a better way.

**Comment by dianasaur323** [comment]
Thanks @dt for coming up with a workaround here!

**Comment by dianasaur323** [comment]
Thanks for figuring out a workaround for this! Although it's awkward to have two jobs, I think this approach seems fine for now. The new description text looks great to me. 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18157#-:-KsylCciXAyqFzRVlF0Q:bcqxtn)*

**Comment by benesch** [comment]
Merging at @dt's request!

**Pull request merged**
