### PR TITLE
deps: update `cockroachdb/gostdlib` to pull in code from go1.18

### PR DESCRIPTION
**Pull request by rickystewart**
Release note: None

### CODE REVIEW

**Review by rail — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85322#-:-N89nY6ZDd-trBTTU2r2:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart)

**Comment by yuzefovich** [comment]
@rickystewart do we still want to merge this?

**Comment by rickystewart** [comment]
It's been long enough that I forgot the context on this. Definitely it cannot be merged as-is due to many conflicts. Give me a bit to review.

**Comment by rickystewart** [comment]
Looks unnecessary given that [this PR](https://github.com/cockroachdb/cockroach/pull/87651/files) for 1.19 was merged.

**Pull request closed without merging**
