### PR TITLE
sql: add max1row planNode

### PR DESCRIPTION
**Pull request by jordanlewis**
This planNode replaces the custom logic that max-1-row subqueries had at
the end, that returns an error if the subquery returned more than 1 row.
The heuristic planner and the optimizer both now plan the new node on
top of the appropriate subqueries, and the custom logic is removed.

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
Pushing this early since the opt team is depending on it, but it's still missing the distsql processor equivalent, though the planNode wrapping code should ensure that everything works in both a distributed and local context.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32753#-:-LSe14tf4mgIg9YQ0FDS:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/max_one_row.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32753#-LSe0gq50aZ-jm51CgtQ:-LSe0gq50aZ-jm51CgtR:b-7a8z1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/511342ac566c20e75570450f49a70fb6bea4c445/pkg/sql/max_one_row.go#L51)):*
> ```Go
> 	}
> 	if ok {
> 		m.values = make(tree.Datums, len(m.plan.Values()))
> ```

Why can't we error out on the second `Next` call instead? We wouldn't need to copy and store `values`

**Comment by jordanlewis** [comment]
> Why can't we error out on the second Next call instead? We wouldn't need to copy and store values

Because this has to fail even if the consumer only calls `Next` a single time and is satisfied.

**Comment by RaduBerinde** [comment]
Oh I see! Can you add that in a comment?

**Comment by jordanlewis** [comment]
Added a comment, and fixed another missing type switch. Hopefully good to go now.

**Comment by jordanlewis** [comment]
Finally good to go... @RaduBerinde can you PTAL at the second commit that fixes the stuff with EXPLAIN ANALYZE we were discussing?

**Review by RaduBerinde — COMMENTED** [review]
:lgtm_strong:  Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32753#-:-LT38F2w70tUvXE9J8QW:b4m8zyy)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/explain_distsql.go, line 100 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32753#-LT37wdN5NJHyr4b43VK:-LT37wdN5NJHyr4b43VL:b-y98bl6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f30460a9c5bec90ad8ea22712c37652894a752f/pkg/sql/explain_distsql.go#L100)):*
> ```Go
> 
> 		if n.optimizeSubqueries {
> ```

[nit] extra blank line
___
*[pkg/sql/explain_distsql.go, line 101 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32753#-LT381ngCsDTmvVoY-NQ:-LT381ngCsDTmvVoY-NR:b-8hspj2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f30460a9c5bec90ad8ea22712c37652894a752f/pkg/sql/explain_distsql.go#L101)):*
> ```Go
> 		if n.optimizeSubqueries {
> 
> 			// The sub-plan's subqueries have been captured local to the EXPLAIN
> ```

[nit] have been captured into the explainDistSQLNode

**Comment by jordanlewis** [comment]
Done. TFTR! 

bors r+

**Comment by andy-kimball** [comment]
Thanks for getting this done, @jordanlewis. I just rebased on it, and it seems to work well.

**Pull request merged**
