### PR TITLE
kvserver: fix comment about protectedts/ptcache/cache.go

### PR DESCRIPTION
**Pull request by SGZW**

### CODE REVIEW

**Comment by SGZW** [comment]
@knz please check this comment fix, thanks

**Comment by knz** [comment]
@SGZW you're missing a release note thanks

**Comment by knz** [comment]
"Release note: None" would do in this case

**Comment by SGZW** [comment]
> "Release note: None" would do in this case

ok, thanks, i will add this

**Comment by SGZW** [comment]
> "Release note: None" would do in this case

please check again, thanks

**Comment by knz** [comment]
@SGZW I'm curious, why did you not read the explanatory comment by blathers-crl [the first time around](https://github.com/cockroachdb/cockroach/pull/67736#issuecomment-881994550) and again [this time](https://github.com/cockroachdb/cockroach/pull/67803#issuecomment-883398262)?

These messages have a purpose. Your comments that tagged many different people before you actually heeded the advice provided by the bot causes notifications to be sent. This interrupted the work of multiple people to look at your stuff before it was ready, and there was nothing these people could do but to repeat what the bot was already telling you.

The idea was for you to read the bot's recommendations and perfect your work *before* you would go and interrupt people.

**Comment by SGZW** [comment]
> @SGZW I'm curious, why did you not read the explanatory comment by blathers-crl [the first time around](https://github.com/cockroachdb/cockroach/pull/67736#issuecomment-881994550) and again [this time](https://github.com/cockroachdb/cockroach/pull/67803#issuecomment-883398262)?
> 
> These messages have a purpose. Your comments that tagged many different people before you actually heeded the advice provided by the bot causes notifications to be sent. This interrupted the work of multiple people to look at your stuff before it was ready, and there was nothing these people could do but to repeat what the bot was already telling you.
> 
> The idea was for you to read the bot's recommendations and perfect your work _before_ you would go and interrupt people.

sorry for interrupted your team，i will read the commit guide in detail again....

**Comment by knz** [comment]
thank you

also, thank you for your contribution!

bors r+

**Pull request merged**
