### PR TITLE
sql: remove SimplifyExpr

### LINKED ISSUE #22722: sql: remove SimplifyExpr
SimplifyExpr was used by the old index constraints code which is gone. The code for SimplifyExpr is pretty complicated and likely has bugs (e.g. I'm not sure it handles NULLs in tuples correctly). My goal is to remove it.

I am filing this PR to investigate the remaining use of SimplifyExpr, in partitioning code:
https://github.com/cockroachdb/cockroach/blob/c02d5061f8623b716a14016ea4a90d0dbb245691/pkg/ccl/partitionccl/partition.go#L263

We should write down exactly what this code is achieving with SimplifyExpr: what kind of expressions does it pass and what kind of simplification is expected? We should be able to implement what is needed separately (perhaps as normalization rules).

CC @danhhz, @dt

### PR DESCRIPTION
**Pull request by knz**
Fixes #22722.

This is dead code now.

The only remaining use in `partitionccl` was purely cosmetic (I talked to @benesch, @danhhz feel free to chime in if you think otherwise).

Release note: None

### CODE REVIEW

**Comment by danhhz** [comment]
Fine by me to remove its use in partitionccl

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Great!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27889#-:-LIE4JnG8XM_edMbLHJo:bioon7n)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by BramGruneir** [comment]
Does splitAndExpr need a test?  LGTM otherwise.

**Comment by knz** [comment]
@BramGruneir the test is in `opt_decompose_test.go`.

Thanks!

bors r+

**Pull request merged**
