### PR TITLE
internal/rsg: use the common rand datum creator instead of our own

### PR DESCRIPTION
**Pull request by madelynnblue**
This will allow for a single place to improve this. We should, for
example, have some list of hard coded interesting values for each type
and return those with some frequency.

Release note: None

### CODE REVIEW

**Review by danhhz — APPROVED** [review]
:lgtm:

> We should, for example, have some list of hard coded interesting values for each type and return those with some frequency.

Yes!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34282#-:-LXKHeke1-aoGxq29LUp:b-wozj0c)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj and @mjibson)

___
*[pkg/internal/rsg/rsg.go, line 245 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34282#-LXKGoJU6LKEdLnt8J6Y:-LXKGoJU6LKEdLnt8J6Z:b-89y8gs) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3db9ebabd15fcc37054695114dce23eb9098362/pkg/internal/rsg/rsg.go#L245)):*
> ```Go
> 	r.lock.Unlock()
> 
> 	return fmt.Sprintf("%s::%s", datum, typ.String())
> ```

I think you want`tree.Serialize(datum)` for this, which uses the `FmtParsable` flags

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34282)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @danhhz and @justinj)

___
*[pkg/internal/rsg/rsg.go, line 245 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34282#-LXKGoJU6LKEdLnt8J6Y:-LXKd_GV0OMd5LgkWMS4:b8df9t3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3db9ebabd15fcc37054695114dce23eb9098362/pkg/internal/rsg/rsg.go#L245)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I think you want`tree.Serialize(datum)` for this, which uses the `FmtParsable` flags
</blockquote></details>

TIL! That's a useful function.

**Pull request merged**
