### PR TITLE
issues: tell folks how to stress failed tests

### PR DESCRIPTION
**Pull request by tbg**
I imagine this will make it much more pleasant to get started on a test
flake.

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28915)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/internal/issues/issues.go, line 256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28915#-LKSz_ly6dPgMprYz2u9:-LKSz_ly6dPgMprYz2uA:bomunry) ([raw file](https://github.com/cockroachdb/cockroach/blob/1992a52294f26bbc3f56ac1575f9442f40257783/pkg/cmd/internal/issues/issues.go#L256)):*
> ```Go
> 
>     ./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
>     cd ~/go/src/github.com/cockroachdb/cockroach && \
> ```

Should there be a `git checkout <sha>` command?
___
*[pkg/cmd/internal/issues/issues.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28915#-LKSzQPw5FWhGaKZTr_1:-LKSzQPw5FWhGaKZTr_2:bln1sfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1992a52294f26bbc3f56ac1575f9442f40257783/pkg/cmd/internal/issues/issues.go#L257)):*
> ```Go
>     ./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
>     cd ~/go/src/github.com/cockroachdb/cockroach && \
>       make stressrace TESTS=%[5]s PKG=%[4]s TESTTIMEOUT=5m STRESSFLAGS='-stderr=false -maxtime 20m -timeout 10m'
> ```

Is it always `stressrace`? I thought that depended on the tags.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28915)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/internal/issues/issues.go, line 256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28915#-LKSz_ly6dPgMprYz2u9:-LKT3aho7nb7eZcuAEVi:bbwldc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1992a52294f26bbc3f56ac1575f9442f40257783/pkg/cmd/internal/issues/issues.go#L256)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Should there be a `git checkout <sha>` command?
</blockquote></details>

I think that's already too prescriptive. For example, I'll usually try to repro on a recent master to avoid churning my build cache. Besides, checkout leaves your local changes around, and I don't want to throw a hard reset into this script. I added some verbiage.
___
*[pkg/cmd/internal/issues/issues.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28915#-LKSzQPw5FWhGaKZTr_1:-LKT3jo_54FfYrV4S6EE:bc1k1fu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1992a52294f26bbc3f56ac1575f9442f40257783/pkg/cmd/internal/issues/issues.go#L257)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is it always `stressrace`? I thought that depended on the tags.
</blockquote></details>

Similarly I think it's understood that folks will have to adapt this incantation sometimes. I'm changing this to always start with `stress` because it's better to get the failure there if it fails in both. Added some verbiage.

**Review by a-robinson — DISMISSED** [review]
:lgtm: nice idea!

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28915#-:-LKT6MKr8xegxtOOzbou:b-kjv2kq)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/internal/issues/issues.go, line 262 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28915#-LKT5qoA3IIbWFGurxlQ:-LKT5qoBBnh-HvdeN7aa:bcdu2bu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e83cbc5518c7ab2b5bb058852fc8dacb6abb8bd3/pkg/cmd/internal/issues/issues.go#L262)):*
> ```Go
> ./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
> cd ~/go/src/github.com/cockroachdb/cockroach && \
> make stress TESTS=%[5]s PKG=%[4]s TESTTIMEOUT=5m STRESSFLAGS='-stderr=false -maxtime 20m -timeout 10m'
> ```

For what it's worth, my personal preference is to just run with `-maxfails 1` instead of `-maxtime 20m -timeout 10m`, that way I can set it and forget it for a while rather than having to come back after a set amount of time.

**Review by benesch — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28915#-:-LKTBe4o32VxceSwizNw:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/internal/issues/issues.go, line 260 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28915#-LKTAn9O91-Gpnmmsupa:-LKTAn9O91-Gpnmmsupb:bvtbyyv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e83cbc5518c7ab2b5bb058852fc8dacb6abb8bd3/pkg/cmd/internal/issues/issues.go#L260)):*
> ```Go
> # using stressrace instead of stress and passing the '-p' stressflag which
> # controls concurrency.
> ./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
> ```

Boo mosh! No scrollback!
___
*[pkg/cmd/internal/issues/issues.go, line 262 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28915#-LKT5qoA3IIbWFGurxlQ:-LKTAcaQ94AAXlTWxqob:b4bcmqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e83cbc5518c7ab2b5bb058852fc8dacb6abb8bd3/pkg/cmd/internal/issues/issues.go#L262)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

For what it's worth, my personal preference is to just run with `-maxfails 1` instead of `-maxtime 20m -timeout 10m`, that way I can set it and forget it for a while rather than having to come back after a set amount of time.
</blockquote></details>

Yeah, that's the default. I usually just run `make stress PKG=./pkg/foo TESTS=TestBar` and don't muck with the defaults at all.

**Review by tbg — COMMENTED** [review]
TFTRs!

I'm going to merge as is and we can iterate on the invocation as we get used to it. I don't think we're ever going to find one that works for everyone, but just having something reasonable to start with is 85% of the work already.
I'm also tempted to build stuff like this into the gceworker script.or to use some roachprod-based tooling to cut down on reproducability. May not be necessary though.

bors r=a-robinson,benesch

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28915#-:-LKTHZao0TRPgNtFZVFO:b-4wdajg)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/cmd/internal/issues/issues.go, line 260 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28915#-LKTAn9O91-Gpnmmsupa:-LKTFHRL2X1-Ybv_YdvQ:b-m1fa78) ([raw file](https://github.com/cockroachdb/cockroach/blob/e83cbc5518c7ab2b5bb058852fc8dacb6abb8bd3/pkg/cmd/internal/issues/issues.go#L260)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Boo mosh! No scrollback!
</blockquote></details>

But `-stderr=false`... I'm toast without mosh.
___
*[pkg/cmd/internal/issues/issues.go, line 262 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28915#-LKT5qoA3IIbWFGurxlQ:-LKTFPDN9CGDDJkNpirc:b-rvs6e9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e83cbc5518c7ab2b5bb058852fc8dacb6abb8bd3/pkg/cmd/internal/issues/issues.go#L262)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Yeah, that's the default. I usually just run `make stress PKG=./pkg/foo TESTS=TestBar` and don't muck with the defaults at all.
</blockquote></details>

My concern is that there's little guidance on when to give up. If something doesn't repro within 20m, it's usually an indication that you need to try something else. I'd like to give this a try.
I also specifically tweaked the timeout parameters so that when a test deadlocks a) you get decent "semacquire: n minutes" indicators in the traces but you don't have to wait for some ungodly amount, while at the same time sidestepping the problem that stress passes if it expires without completing a single run.

**Review by tbg — COMMENTED** [review]
bors r=a-robinson,benesch

> Dismissed @petermattis from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28915#-:-LKTI5Y5ETS53qt-wl4f:b44df60)* status: :shipit: complete! 2 of 0 LGTMs obtained

**Comment by tschottdorf** [comment]
bors r=a-robinson,benesch

**Review by benesch — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28915)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/cmd/internal/issues/issues.go, line 262 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28915#-LKT5qoA3IIbWFGurxlQ:-LKTJckX6etnBMkfZjOJ:b-oyvrlh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e83cbc5518c7ab2b5bb058852fc8dacb6abb8bd3/pkg/cmd/internal/issues/issues.go#L262)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

My concern is that there's little guidance on when to give up. If something doesn't repro within 20m, it's usually an indication that you need to try something else. I'd like to give this a try.
I also specifically tweaked the timeout parameters so that when a test deadlocks a) you get decent "semacquire: n minutes" indicators in the traces but you don't have to wait for some ungodly amount, while at the same time sidestepping the problem that stress passes if it expires without completing a single run.
</blockquote></details>

Yeah, I'm on board with all of that! Preference would be to make those the defaults for `make stress` itself so that the issue hint can just say "go run `make stress`". We already override all the stress options in CI so changing the defaults isn't too big a deal. 

Although I think I'd set that default to 45m; some things are REALLY hard to repro and it super sucks when your stress run times out early.

**Pull request merged**
