### PR TITLE
kvcoord: subject refresh spans to the limit when importing from leaves

### PR DESCRIPTION
**Pull request by yuzefovich**
Whenever we're importing the refresh spans from the LeafTxnFinalState,
we're inserting those refresh spans into the refresh footprint set and
attempt to condense the set to stay under the maximum (determined by
a setting). However, the condensing is performed on a best-effort basis,
so previously it was possible to significantly over-shoot the limit.
Furthermore, this refresh footprint is not accounted for. This commit
improves things a bit by giving up on the ability to refresh (i.e.
invalidating the refresh footprint) once the limit is exceeded when
importing the refresh spans from the leaves - it is similar to what we
do after `Send`ing the BatchRequest.

Addresses: #64906.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I don't have concrete data to support this patch, rather only a theoretical thinking, and it seems sane to me to do this, but curious to hear your thoughts.

IIUC the impact of invalidating the refresh footprint is that the queries that read a lot of spans (so that the footprint is large) across many ranges (so that condensing is not enough) would get more retries when the refresh on the server side is required. Is that concerning?

**Review by nvb — COMMENTED** [review]
This is a good catch. We were already doing essentially the same thing that you're doing here after serving a read (see `tryCondenseRefreshSpans` and its caller `txnSpanRefresher.SendLocked`). So we would never let any single root or leaf txn serve more than the limit. However, we weren't enforcing the limit across all leafs after they were imported back into the root if no single leaf exceeded the limit. I guess we would invalidate the set if the root ever served another read, but that's insufficient.

I think what you have here is good, but maybe we can unify it further with `tryCondenseRefreshSpans` and its existing caller so that the invalidation logic lives in a single place. What do you think?

I also don't think you need the multiple of 10. We shouldn't be allowing the set to exceed the limit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85286#-:-N8OnrEt9akwTGp0-3Tt:bj86ziw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

**Review by yuzefovich — COMMENTED** [review]
Good point, implemented your suggestion.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85286#-:-N8W6NT_Amv9hNrRXc0c:b-b9jggv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85286#-:-N8WppWb2pGggTq-TSVu:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85286#-:-N8WqY9O1MU0E8MUX0p2:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Pull request merged**
