### PR TITLE
*: avoid using background ctx in stopper.Run{Async,}Task{Ex,}

### LINKED ISSUE #73911: goroutines spawned via stopped without annotated context
**Describe the problem**

We have plenty of calls to `stopper.RunTask`, `RunAsyncTask` etc with `context.Background()` or `context.TODO()`, which miss a tracer and log tags.

**Expected behavior**

Using annotated contexts instead.

### PR DESCRIPTION
**Pull request by knz**
Fixes #73911.

See the individual commits for details. The first 7 of these are fixing what could arguably be described as observability bugs.

### CODE REVIEW

**Comment by andreimatei** [comment]
I'm gonna wait for the base PR to merge if you don't mind cause there's way too many commits in here and I'm failing to get reviewable to show them to me one by one.

**Comment by knz** [comment]
Actually, I could rebase this on top of `master`. So it's ready for review now.

**Review by tbg — APPROVED** [review]
Please update PR message, as it will be picked up by the merge commit.

I'm not really happy with the linter, for two reasons:

- It seems overly strict to apply it to test code. What's the benefit of that? In some of the commits you write code that we wouldn't necessarily write that way just to bypass the linter. It's already hard to get stuff through CI, if we make it harder there has to be a very good reason.
- it's very easily gamed, even by accident, so what does the linter achieve? If we absolutely must assure that we statically never pass `context.(Background|TODO)` to the stopper, can this be (to a useful degree) be done by a vet pass? I assume this is difficult/impossible. As an alternative solution, during testing, perhaps we can have the stopper fatal if it sees a `Background` or `TODO` (which means the cosmetic bypass that some of the commits here employ wouldn't work, but we could allow it if the caller is in a `_test.go` file?)

I'm fine merging everything but the linter, I think we should talk the linter through separately.

> Reviewed 2 of 83 files at r1, 81 of 81 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, 3 of 3 files at r7, 1 of 1 files at r8, 2 of 2 files at r9, 9 of 9 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73915#-:-MrWxG_Q4JQkhAXtn-aS:bnobjdi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @dt, and @knz)

___
*[pkg/ccl/sqlproxyccl/tenantdirsvr/test_directory_svr.go, line 57 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/73915#-MrWzFza7tlZkvke5RnA:-MrWzFza7tlZkvke5RnB:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9643950b008c058fcf4765646dbbea111eb66abe/pkg/ccl/sqlproxyccl/tenantdirsvr/test_directory_svr.go#L57)):*
> ```Go
> 		defer mu.Unlock()
> 		if subStopper == nil {
> 			subStopper = stop.NewStopper(stop.WithTracer(parentStopper.Tracer()))
> ```

:thumbsup: 
___
*[pkg/kv/kvserver/queue.go, line 575 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73915#-MrWxwBT5jGVU-XF4OU8:-MrWxwBT5jGVU-XF4OU9:b-6kcs8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/eeabf8a363a7f34a11e6d90fe190ffaeb1064227/pkg/kv/kvserver/queue.go#L575)):*
> ```Go
> 	bgCtx := bq.AnnotateCtx(context.Background())
> 	// TODO(knz): Do we want to propagate context tags from the parent
> 	// ctx to the bgCtx? This may contain details about the replica, etc.
> ```

That makes sense, but also I happen to know that these closures here don't do much work, they just add to the queue, so their tags aren't expected to be relevant.
___
*[pkg/ccl/backupccl/backup_test.go, line 3793 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/73915#-MrWySsx1vePZsfuZmRZ:-MrWySsx1vePZsfuZmR_:b-mr90y2) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfa7661eff330c1bc3cf9dba3471afe08849cab5/pkg/ccl/backupccl/backup_test.go#L3793)):*
> ```Go
> 	const numBackgroundTasks = MultiNode
> 
> 	ctx, tc, sqlDB, _, cleanupFn := BackupRestoreTestSetup(t, MultiNode, rows, InitManualReplication)
> ```

So `ctx` is annotated with the first server's ambientctx, which is weird (or at least I'm not sure what the reasoning here would be). Am I reading correctly that prior to this PR the returned context equals `context.Background()`? It seems better to drop this return value altogether and let the callers use `context.Background()` (or `tc.Server(x).AmbientCtx.AnnotateCtx(context.Background)` if they really want to) directly.
___
*[pkg/kv/kvserver/replica_test.go, line 2100 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/73915#-MrWziWH-3ft7stTcZzp:-MrWz_vx7fp6u7759iVf:bnt2isd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9643950b008c058fcf4765646dbbea111eb66abe/pkg/kv/kvserver/replica_test.go#L2100)):*
> ```Go
> 		pErrCh := make(chan *roachpb.Error, num)
> 		for i := 0; i < num; i++ {
> 			bgCtx := context.Background()
> ```

Don't see why changes like this make sense. What's the point in introducing a local variable? Looks like you're just golfing with the linter. Make that explicit on each occasion then.
___
*[pkg/testutils/lint/lint_test.go, line 570 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/73915#-MrX-8Xq5s-96GSDk8wT:-MrX-8Xq5s-96GSDk8wU:b-jt9por) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a284104fa65773dd7183cc00d886c0ecfe449d7/pkg/testutils/lint/lint_test.go#L570)):*
> ```Go
> 		if err := stream.ForEach(filter, func(s string) {
> 			t.Errorf("\n%s <- forbidden; use an annotated context using AmbientContext when possible, otherwise propagate log tags manually\n"+
> 				"For details or more information, see the context tech note.", s)
> ```

Path to would be helpful.

**Review by knz — COMMENTED** [review]
I have removed the linter.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73915#-:-MrXHgF-5WxdbIhpVBSi:btwzljn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @dt, and @tbg)

___
*[pkg/kv/kvserver/queue.go, line 575 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73915#-MrWxwBT5jGVU-XF4OU8:-MrXCVGNBMX2a0ofoGVY:buwybp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/eeabf8a363a7f34a11e6d90fe190ffaeb1064227/pkg/kv/kvserver/queue.go#L575)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

That makes sense, but also I happen to know that these closures here don't do much work, they just add to the queue, so their tags aren't expected to be relevant.
</blockquote></details>

Thanks for explaining. Removed comment.
___
*[pkg/ccl/backupccl/backup_test.go, line 3793 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/73915#-MrWySsx1vePZsfuZmRZ:-MrXHLOC8BNVpUohif7O:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfa7661eff330c1bc3cf9dba3471afe08849cab5/pkg/ccl/backupccl/backup_test.go#L3793)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

So `ctx` is annotated with the first server's ambientctx, which is weird (or at least I'm not sure what the reasoning here would be). Am I reading correctly that prior to this PR the returned context equals `context.Background()`? It seems better to drop this return value altogether and let the callers use `context.Background()` (or `tc.Server(x).AmbientCtx.AnnotateCtx(context.Background)` if they really want to) directly.
</blockquote></details>

Good idea. Done.
___
*[pkg/kv/kvserver/replica_test.go, line 2100 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/73915#-MrWziWH-3ft7stTcZzp:-MrXHXwUElxpbS93_l3t:bp3aow6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9643950b008c058fcf4765646dbbea111eb66abe/pkg/kv/kvserver/replica_test.go#L2100)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Don't see why changes like this make sense. What's the point in introducing a local variable? Looks like you're just golfing with the linter. Make that explicit on each occasion then.
</blockquote></details>

Reverted.
___
*[pkg/testutils/lint/lint_test.go, line 570 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/73915#-MrX-8Xq5s-96GSDk8wT:-MrXHSPp2h-5Dz_UW3pw:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a284104fa65773dd7183cc00d886c0ecfe449d7/pkg/testutils/lint/lint_test.go#L570)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Path to would be helpful.
</blockquote></details>

Removed.

**Comment by knz** [comment]
TFYR

bors r=tbg

**Pull request merged**
