### PR TITLE
pgwire: skip TestAuthenticationAndHBARules due to repeated failures

### PR DESCRIPTION
**Pull request by adityamaru**
Informs: #52026

### CODE REVIEW

**Review by irfansharif — APPROVED** [review]

**Comment by adityamaru** [comment]
TFTR!

bors r=irfansharif

**Review by otan — APPROVED** [review]

**Comment by irfansharif** [comment]
bors r_

**Comment by irfansharif** [comment]
```

[01:29:12][Ensure generated code is up-to-date] 
[01:29:12][Ensure generated code is up-to-date] Changes not staged for commit:
[01:29:12][Ensure generated code is up-to-date]   (use "git add <file>..." to update what will be committed)
[01:29:12][Ensure generated code is up-to-date]   (use "git restore <file>..." to discard changes in working directory)
[01:29:12][Ensure generated code is up-to-date] 	modified:   pkg/sql/pgwire/auth_test.go
[01:29:12][Ensure generated code is up-to-date] 
[01:29:12][Ensure generated code is up-to-date] no changes added to commit (use "git add" and/or "git commit -a")
[01:29:12][Ensure generated code is up-to-date] diff --git a/pkg/sql/pgwire/auth_test.go b/pkg/sql/pgwire/auth_test.go
[01:29:12][Ensure generated code is up-to-date] index 1b1b63891b..5ed26feaf9 100644
[01:29:12][Ensure generated code is up-to-date] --- a/pkg/sql/pgwire/auth_test.go
[01:29:12][Ensure generated code is up-to-date] +++ b/pkg/sql/pgwire/auth_test.go
[01:29:12][Ensure generated code is up-to-date] @@ -105,6 +105,7 @@ import (
[01:29:12][Ensure generated code is up-to-date]  // alongside the "ok" or "ERROR" message.
[01:29:12][Ensure generated code is up-to-date]  //
[01:29:12][Ensure generated code is up-to-date]  func TestAuthenticationAndHBARules(t *testing.T) {
[01:29:12][Ensure generated code is up-to-date] +	defer leaktest.AfterTest(t)()
[01:29:12][Ensure generated code is up-to-date]  	skip.WithIssue(t, 52026, "temporarily skip due to repeated failures")
[01:29:12][Ensure generated code is up-to-date]  	defer leaktest.AfterTest(t)()
[01:29:12][Ensure generated code is up-to-date]  
[01:29:12][Ensure generated code is up-to-date] Process exited with code 1
```

**Comment by adityamaru** [comment]
Flaked - `Failed to publish files: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/multitenant/run_1/run_030315.215_n1_cockroach_mt.log (No such file or directory) `

**Pull request merged**
