### PR TITLE
admission: don't read tenantInfo.id after releasing the mutex

### LINKED ISSUE #135169: admission: WARNING: DATA RACE between releaseTenantInfo and granted
Only seen once, couldn't reproduce with:

```bash
dev test pkg/kv/kvserver -v --vmodule='replica_raft=1,kvflowcontroller=2,replica_proposal_buf=1,raft_transport=2,kvflowdispatch=1,kvadmission=1,kvflowhandle=1,work_queue=1,replica_flow_control=1,tracker=1,client_raft_helpers_test=1,raft=1,admission=1,replica_flow_control=1,work_queue=1,replica_raft=1,replica_proposal_buf=1,raft_transport=2,kvadmission=1,work_queue=1,replica_flow_control=1,client_raft_helpers_test=1,range_controller=2,token_counter=2,token_tracker=2,processor=2,kvflowhandle=1' -f  TestFlowControlSendQueue --show-logs --stress --race --cpus=8
```

```
WARNING: DATA RACE
Write at 0x00c001f47e00 by goroutine 11026:
  github.com/cockroachdb/cockroach/pkg/util/admission.releaseTenantInfo()
      pkg/util/admission/work_queue.go:1396 +0x188
  github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).gcTenantsAndResetUsed()
      pkg/util/admission/work_queue.go:961 +0x1d4
  github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue.func2()
      pkg/util/admission/work_queue.go:426 +0x4c

Previous read at 0x00c001f47e00 by goroutine 11031:
  github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).granted()
      pkg/util/admission/work_queue.go:925 +0x3dc
  github.com/cockroachdb/cockroach/pkg/util/admission.(*kvStoreTokenGranter).tryGrantLocked()
      pkg/util/admission/granter.go:565 +0xf0
  github.com/cockroachdb/cockroach/pkg/util/admission.(*GrantCoordinator).tryGrantLocked()
      pkg/util/admission/grant_coordinator.go:939 +0x2b0
  github.com/cockroachdb/cockroach/pkg/util/admission.(*GrantCoordinator).allocateIOTokensTick()
      pkg/util/admission/grant_coordinator.go:706 +0xb0
  github.com/cockroachdb/cockroach/pkg/util/admission.(*StoreGrantCoordinators).SetPebbleMetricsProvider.func1.1()
      pkg/util/admission/grant_coordinator.go:139 +0x34
  github.com/cockroachdb/cockroach/pkg/util/syncutil.(*Map[go.shape.int32,go.shape.5c61f9b02243fc61e559aef49279a8bc1f64396f6c1bd8885c4a9863f430018d]).Range()
      pkg/util/syncutil/map.go:391 +0x19c
  github.com/cockroachdb/cockroach/pkg/util/admission.(*StoreGrantCoordinators).SetPebbleMetricsProvider.func1()
      pkg/util/admission/grant_coordinator.go:138 +0x470

Goroutine 11026 (running) created at:
  github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue()
      pkg/util/admission/work_queue.go:421 +0x4dc
  github.com/cockroachdb/cockroach/pkg/util/admission.makeStoreWorkQueue()
      pkg/util/admission/work_queue.go:2275 +0x450
  github.com/cockroachdb/cockroach/pkg/util/admission.(*StoreGrantCoordinators).initGrantCoordinator()
      pkg/util/admission/grant_coordinator.go:195 +0x714
  github.com/cockroachdb/cockroach/pkg/util/admission.(*StoreGrantCoordinators).SetPebbleMetricsProvider()
      pkg/util/admission/grant_coordinator.go:87 +0x1c4
  github.com/cockroachdb/cockroach/pkg/server.(*topLevelServer).PreStart()
      server.go:1965 +0x30fc
  github.com/cockroachdb/cockroach/pkg/server.(*testServer).PreStart()
      testserver.go:793 +0xac
  github.com/cockroachdb/cockroach/pkg/server.(*testServer).Start()
      testserver.go:871 +0x94
  github.com/cockroachdb/cockroach/pkg/testutils/serverutils.(*wrap).Start()
      bazel-out/darwin_arm64-fastbuild/bin/pkg/testutils/serverutils/ts_control_forwarder_generated.go:14 +0x74
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).RestartServerWithInspect.func1()
      pkg/testutils/testcluster/testcluster.go:1770 +0x74
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).RestartServerWithInspect()
      pkg/testutils/testcluster/testcluster.go:1780 +0x458
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).RestartServer()
      pkg/testutils/testcluster/testcluster.go:1694 +0x1d8c
  github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestFlowControlSendQueue()
      pkg/kv/kvserver/flow_control_integration_test.go:4793 +0x1d90
  testing.tRunner()
      GOROOT/src/testing/testing.go:1689 +0x180
  testing.(*T).Run.gowrap1()
      GOROOT/src/testing/testing.go:1742 +0x40

Goroutine 11031 (running) created at:
  github.com/cockroachdb/cockroach/pkg/util/admission.(*StoreGrantCoordinators).SetPebbleMetricsProvider()
      pkg/util/admission/grant_coordinator.go:104 +0x380
  github.com/cockroachdb/cockroach/pkg/server.(*topLevelServer).PreStart()
      server.go:1965 +0x30fc
  github.com/cockroachdb/cockroach/pkg/server.(*testServer).PreStart()
      testserver.go:793 +0xac
  github.com/cockroachdb/cockroach/pkg/server.(*testServer).Start()
      testserver.go:871 +0x94
  github.com/cockroachdb/cockroach/pkg/testutils/serverutils.(*wrap).Start()
      bazel-out/darwin_arm64-fastbuild/bin/pkg/testutils/serverutils/ts_control_forwarder_generated.go:14 +0x74
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).RestartServerWithInspect.func1()
      pkg/testutils/testcluster/testcluster.go:1770 +0x74
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).RestartServerWithInspect()
      pkg/testutils/testcluster/testcluster.go:1780 +0x458
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).RestartServer()
      pkg/testutils/testcluster/testcluster.go:1694 +0x1d8c
  github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestFlowControlSendQueue()
      pkg/kv/kvserver/flow_control_integration_test.go:4793 +0x1d90
  testing.tRunner()
      GOROOT/src/testing/testing.go:1689 +0x180
  testing.(*T).Run.gowrap1()
      GOROOT/src/testing/testing.go:1742 +0x40
```

Jira issue: CRDB-44387

### PR DESCRIPTION
**Pull request by sumeerbhola**
Fixes #135169

Epic: none

Release note: None

### CODE REVIEW

**Review by aadityasondhi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135742#-:-OC59PAz2uO5cI0xsXbn:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained

**Comment by sumeerbhola** [comment]
TFTR!

**Comment by sumeerbhola** [comment]
bors r=aadityasondhi

**Comment by sumeerbhola** [comment]
bors retry

**Pull request merged**
