### PR TITLE
sql: don't allow StatementSources to commit the txn 

### LINKED ISSUE #18806: sql: erroneous auto-commit for sub-query
Found while experimenting with @robert-s-lee 

```sql
CREATE TABLE x (id1 INT, id2 INT, id3 serial);
create table y (x int, y int, z int, s string);
INSERT INTO y SELECT * FROM [INSERT INTO x VALUES (1, 1), (2, 2), (3, 3) RETURNING id1, id2, id3] AS a, (values('a')) AS b;
```

the INSERT fails with:

```
pq: internal/client/txn.go:856: attempting to use transaction with wrong status or finalized: COMMITTED true
```

cc @andreimatei - can you point in which direction we should be looking at to solve this?

### PR DESCRIPTION
**Pull request by andreimatei**
Fixes #18806

Before this patch, each planNode would independently decide whether it's
allowed to auto-commit or not regardless of parts of the query that were
not under the node in question. This was no bueno - the transaction
could be committed before others might want to use or while a query
could still generate errors (in which case one would expect the txn to
be rolled back, not committed).
Concretely, something like SELECT * FROM [INSERT ... RETURNING ...] was
quite broken.

This patch makes it so that only the top-level node is allowed to
auto-commit.
I have gone a different path for a while, thinking that the node that
can auto-commit could be any node that is an ancestor of all other nodes
that perform KV addresses, but that's not true because of the error
handling semantics: the txn can only be committed once nothing returns
an error any more. Hence the somewhat brutal fix in this patch.

As a consequence, in SHOW TRACE FOR <stmt>, <stmt> can no longer do
auto-commit. I tried to do something special for SHOW TRACE FOR
(although supporting it was dubious because, if the STF was inside of
another SELECT, we again generally do not want the auto-commit), but
it's complicated because STF changes the plan and inserts several nodes
at the top of the tree (a sort, etc), and it's not very clear how to
handle them.
Queries traced under SHOW TRACE FOR SESSION still do 1PC normally.

The changes to the logic tests are caused by 1PC not being used for SHOW
TRACE FOR <stmt> statements any more - which caused one log line to
change.

Release note (bug fix): INSERT/UPDATE/DELETE ... RETURNING  ...
statments used with the "statement data source" syntax (e.g. SELECT *
FROM  [INSERT INTO ... RETURNING ...]) no longer ever commit the
transaction, causing errors for the higher-level query.

### CODE REVIEW

**Comment by andreimatei** [comment]
cc @jseldess as this introduces a limitation to `SHOW TRACE FOR <stmt>` that we might want to document.

**Comment by andreimatei** [comment]
Friendly ping. I can probably find someone else to review this one Rafa if you'd like.

**Comment by knz** [comment]
Oh I'm sorry this slipped under the radar. On it.

**Comment by knz** [comment]
:lgtm:

Although please add a session trace example that illustrates how the 1PC thing does work in a trace.

---

Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 12 of 12 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20847#-:-L2UmH9CMxsbJ1cAU-Aj:b-5p4mfr)*

**Comment by knz** [comment]
I meant a logic test using `show session trace`.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20847#-:-L2UmPtRRRaxi2ZFZE0r:b-elca3a)*

**Comment by andreimatei** [comment]
TFTR

I've added the logic test you wanted.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20847#-:-L2gC6qnI0aXt8mrPPyk:b-ajd935)*

**Pull request merged**
