### PR TITLE
schemachanger,scpb,catalog: move schema changer state into descriptors

### PR DESCRIPTION
**Pull request by ajwerner**
This work is in support of https://github.com/cockroachdb/cockroach/issues/73071. The first two commit breaks dependencies so descpb can import scpb. Then we add the state to the descriptor protos. Finally we adopt for use. This does not yet test or synthesize the job.

### CODE REVIEW

**Comment by ajwerner** [comment]
@postamar this is RFAL

**Review by postamar — CHANGES_REQUESTED** [review]
This is a good change. Aside from the trivial stuff my only substantial ask is for a bit more descriptor validation around the schema changer state, to go from "non existent" to "bare-bones".

:bone: 

> Reviewed 79 of 79 files at r1, 2 of 19 files at r2, 77 of 77 files at r5, 19 of 19 files at r6, 34 of 34 files at r7, 29 of 29 files at r8, 11 of 11 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-:-MvTR6Qj8yy9M9-YaofM:b-ei4tg9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @stevendanna)

___
*[-- commits, line 21 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTEXCX3R3o6hEZzyJp):*
nit: typo: s/scpc/scpb/
___
*[-- commits, line 48 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTQgTo5c1QiYkmS3-c):*
I understand your concerns. I think what you did is fine and will last us until we refactor the catalog API.
___
*[pkg/jobs/jobspb/jobs.proto, line 479 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTKNMa6XtpfU3aUhk6:-MvTKNMa6XtpfU3aUhk7:b-3wmxba) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a63942673a99e391d33c1451a2c2e85816311aa/pkg/jobs/jobspb/jobs.proto#L479)):*
> ```protobuf
>   repeated BackfillProgress backfill_progress = 4 [(gogoproto.nullable) = false];
> 
>   repeated uint32 descriptors = 6 [(gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb.ID"];
> ```

Aren't these already in the job record though?

Assuming it actually needs to exist, consider naming the field `descriptor_ids`?
___
*[pkg/jobs/jobspb/jobs.proto, line 523 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTKhg_4_kJnnWCCNQD:-MvTKhg_4_kJnnWCCNQE:b-g6jx3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a63942673a99e391d33c1451a2c2e85816311aa/pkg/jobs/jobspb/jobs.proto#L523)):*
> ```protobuf
> // NewSchemaChangeProgress is the persisted progress for the new schema change job.
> message NewSchemaChangeProgress {
>   reserved 1;
> ```

FWIW I don't think we need to be so conservative here in reserving fields. The probability of there being clusters out with declarative schema change jobs in flight is zero.
___
*[pkg/sql/catalog/catpb/job_id.go, line 16 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTE-qhAYmR2BA2hwpa:-MvTE-qhAYmR2BA2hwpb:b-hhdqv0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a29cd762e7518e2d7a1bf9bb29855cd9b64a27d/pkg/sql/catalog/catpb/job_id.go#L16)):*
> ```Go
> // jobs are referenced in descriptors and also jobs reference parts of
> // descriptors. This avoids any dependency cycles.
> type JobID int64
> ```

Shouldn't it be in `catid` instead?
___
*[pkg/sql/catalog/tabledesc/validate.go, line 595 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTH2e51HcpbrH0ErxC:-MvTH2e68r_l2T5VN-SG:b-e5kamg) ([raw file](https://github.com/cockroachdb/cockroach/blob/26fd3ec3f30a415ffcd467ec564347469e75ca84/pkg/sql/catalog/tabledesc/validate.go#L595)):*
> ```Go
> 	// still be running after the schema change is complete from the point of view
> 	// of the descriptor, in both the new and old schema change jobs.)
> 	if dscs := desc.DeclarativeSchemaChangerState; dscs != nil && len(desc.MutationJobs) > 0 {
> ```

Adding full validation for the declarative schema changer state is out of scope for this change, but I'm sad that this is the only place where the declarative schema changer state ever shows up in validation. Could you please:
- add some skeleton of a validation function for each `Descriptor` implementation that perhaps checks that the job ID is non-zero and the element descriptor IDs are correct or something super basic like that, 
- exercise this basic functionality in some unit tests
- add TODOs in the validation function skeletons to indicate we need to beef these up a bit
- file an issue reminding us of this, with a mention that we should cross-reference the job when validating with doctor or with `crdb_internal.invalid_objects`.

I'm hopeful that the work I'm doing right now will make the beefing-up rather straightforward so there's no point in over-investing in this right now.
___
*[pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go, line 169 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTMH620ZmyD0862B1-:-MvTMH620ZmyD0862B10:blit3um) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a63942673a99e391d33c1451a2c2e85816311aa/pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go#L169)):*
> ```Go
> 			existingJobID, op.DescriptorID, op.JobID,
> 		)
> 	}
> ```

nit: I find this a bit contrived, perhaps split the test into two? One for existence of `existing` and another for invalid job ID? That would make for nicer error messages, unlikely as they may be.
___
*[pkg/sql/schemachanger/scpb/scpb.proto, line 42 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTIhHSBXYPa7AT1qA8:-MvTIhHSBXYPa7AT1qA9:bq8ar0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/26fd3ec3f30a415ffcd467ec564347469e75ca84/pkg/sql/schemachanger/scpb/scpb.proto#L42)):*
> ```protobuf
> // schema changer State.
> message TargetMetadata {
>   option (gogoproto.equal) = true;
> ```

Isn't this redundant now that you have `equal_all = true` at the top level?
___
*[pkg/sql/schemachanger/scpb/scpb.proto, line 59 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTIor6A-2zeZgGPESq:-MvTIor6A-2zeZgGPESr:bylgsxg) ([raw file](https://github.com/cockroachdb/cockroach/blob/26fd3ec3f30a415ffcd467ec564347469e75ca84/pkg/sql/schemachanger/scpb/scpb.proto#L59)):*
> ```protobuf
>   // TODO(ajwerner): Potentially multiple statements in a transaction affect
>   // the same target. We'll need to retain a set of ids to deal with that case.
>   // Consider a
> ```

nit: typo: truncated comment text
___
*[pkg/sql/schemachanger/scpb/scpb.proto, line 80 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTItaM0BXQWch6Roqo:-MvTItaM0BXQWch6Roqp:bz0jrz5) ([raw file](https://github.com/cockroachdb/cockroach/blob/26fd3ec3f30a415ffcd467ec564347469e75ca84/pkg/sql/schemachanger/scpb/scpb.proto#L80)):*
> ```protobuf
> }
> 
> // DescriptorTargetsState contains the portion of a schema change state
> ```

nit: typo: bad message name in comment
___
*[pkg/sql/schemachanger/scpb/scpb.proto, line 107 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTNI3x6nmx85x1ctPy:-MvTNI3x6nmx85x1ctPz:bgf9j5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a63942673a99e391d33c1451a2c2e85816311aa/pkg/sql/schemachanger/scpb/scpb.proto#L107)):*
> ```protobuf
>   // RelevantStatements is the set of statements which are relevant to any of
>   // the targets.
>   map<uint32, Statement> relevant_statements = 2  [(gogoproto.nullable) = false];
> ```

Since we're concerned about determinism, perhaps make this a list of key-value message pairs instead of a map?
___
*[pkg/sql/schemachanger/scplan/internal/scstage/build.go, line 380 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTNlTe5HwIoDRwpjk0:-MvTNlTe5HwIoDRwpjk1:b-83sjo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a63942673a99e391d33c1451a2c2e85816311aa/pkg/sql/schemachanger/scplan/internal/scstage/build.go#L380)):*
> ```Go
> 		s.EdgeOps = append(s.EdgeOps, e.Op()...)
> 	}
> 	jobOps := sb.computeExtraJobOps(s, after)
> ```

Nice.
___
*[pkg/sql/schemachanger/scplan/internal/scstage/build.go, line 425 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTNprgEQXP31rRXiOr:-MvTNprgEQXP31rRXiOs:b-drrrdp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a63942673a99e391d33c1451a2c2e85816311aa/pkg/sql/schemachanger/scplan/internal/scstage/build.go#L425)):*
> ```Go
> 		// we need to emit this op. Also, this is buggy, we need to mark the job
> 		// as non-cancelable *before* we start to execute the first NonRevertible
> 		// phase.
> ```

File a follow-up issue and mark it as a release blocker, please.
___
*[pkg/sql/schemachanger/scrun/scrun.go, line 179 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTQRdVA4GZDLaPEMek:-MvTQRdVA4GZDLaPEMel:b-461l3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/d53f4ae1e82ea7e5534622a69cafe7487f28f1c0/pkg/sql/schemachanger/scrun/scrun.go#L179)):*
> ```Go
> 		stmts = make(map[uint32]scpb.Statement)
> 
> 		// TODO(ajwerner): This would be a great place for a batched read.
> ```

nit: Remove TODO
___
*[pkg/sql/schemachanger/scrun/scrun.go, line 182 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTQUr53dfDF3LOjYR4:-MvTQUr53dfDF3LOjYR5:b8rer5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/d53f4ae1e82ea7e5534622a69cafe7487f28f1c0/pkg/sql/schemachanger/scrun/scrun.go#L182)):*
> ```Go
> 		descs, err := txnDeps.Catalog().MustReadImmutableDescriptors(ctx, descriptorIDs...)
> 		if err != nil {
> 			// TODO(ajwerner): It seems possible that a descriptor could be deletted
> ```

nit: typo: s/deletted/deleted
___
*[pkg/sql/schemachanger/testdata/alter_table_add_column, line 28 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTOpX2DyWvqv6QfO3P:-MvTOpX2DyWvqv6QfO3Q:b435xfg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a63942673a99e391d33c1451a2c2e85816311aa/pkg/sql/schemachanger/testdata/alter_table_add_column#L28)):*
> ```
>   +  declarativeSchemaChangerState:
>   +    authorization:
>   +      appName: "\x10�N0\x028\b@\x02`\x01h\x01p\x01�\x01\x01�\x01\x01�\x01\x01�\x01\x01�\x01\x01�\x02\x01�\x02��\x01�\x02\x01�\x03\x01�\x03\0\0\0\0\0@�@�\x03\x01�\x03\x01"
> ```

Perhaps we should redact the declarative schema changer state in these outputs? Or at least parts of it like the app name? Don't bother if it's too much trouble.

**Review by ajwerner — COMMENTED** [review]
I added validation that's more than bare-bones I'd like to think. Sorry for the delays. Mod further skew with master, I think this is RFAL. I'll tend to any CI failures when they pop up. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-:-MvdpEs921klDrjn7GU9:b-lvpl84)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar and @stevendanna)

___
*[-- commits, line 48 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTQgTo5c1QiYkmS3-c):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I understand your concerns. I think what you did is fine and will last us until we refactor the catalog API.
</blockquote></details>

Done.
___
*[pkg/jobs/jobspb/jobs.proto, line 479 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTKNMa6XtpfU3aUhk6:-Mva_zfbC0MDK8s6TcXw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a63942673a99e391d33c1451a2c2e85816311aa/pkg/jobs/jobspb/jobs.proto#L479)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Aren't these already in the job record though?

Assuming it actually needs to exist, consider naming the field `descriptor_ids`?
</blockquote></details>

Done.
___
*[pkg/jobs/jobspb/jobs.proto, line 523 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTKhg_4_kJnnWCCNQD:-Mvaa1pP4iwWAF43gR7R:b-6ymeeh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a63942673a99e391d33c1451a2c2e85816311aa/pkg/jobs/jobspb/jobs.proto#L523)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

FWIW I don't think we need to be so conservative here in reserving fields. The probability of there being clusters out with declarative schema change jobs in flight is zero.
</blockquote></details>

The cost of reserving this is ~zero. I'd rather have the history reflect a hygienic treatment of protobuf fields. 
___
*[pkg/sql/catalog/catpb/job_id.go, line 16 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTE-qhAYmR2BA2hwpa:-MvaaRNc38uehO8HszGi:b-dws4et) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a29cd762e7518e2d7a1bf9bb29855cd9b64a27d/pkg/sql/catalog/catpb/job_id.go#L16)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Shouldn't it be in `catid` instead?
</blockquote></details>

:shrug: it certainly could be. I don't need to import it into `tree` anytime soon, so I'm inclined to leave it here for now. 
___
*[pkg/sql/catalog/tabledesc/validate.go, line 595 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTH2e51HcpbrH0ErxC:-MvdnoBjCJEpO7DEXKKJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26fd3ec3f30a415ffcd467ec564347469e75ca84/pkg/sql/catalog/tabledesc/validate.go#L595)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Adding full validation for the declarative schema changer state is out of scope for this change, but I'm sad that this is the only place where the declarative schema changer state ever shows up in validation. Could you please:
- add some skeleton of a validation function for each `Descriptor` implementation that perhaps checks that the job ID is non-zero and the element descriptor IDs are correct or something super basic like that, 
- exercise this basic functionality in some unit tests
- add TODOs in the validation function skeletons to indicate we need to beef these up a bit
- file an issue reminding us of this, with a mention that we should cross-reference the job when validating with doctor or with `crdb_internal.invalid_objects`.

I'm hopeful that the work I'm doing right now will make the beefing-up rather straightforward so there's no point in over-investing in this right now.
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go, line 169 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTMH620ZmyD0862B1-:-MvdoHsKEt4PWVO_syKW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a63942673a99e391d33c1451a2c2e85816311aa/pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go#L169)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

nit: I find this a bit contrived, perhaps split the test into two? One for existence of `existing` and another for invalid job ID? That would make for nicer error messages, unlikely as they may be.
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scpb/scpb.proto, line 42 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTIhHSBXYPa7AT1qA8:-MvdovLBEwEEjMtlPg97:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26fd3ec3f30a415ffcd467ec564347469e75ca84/pkg/sql/schemachanger/scpb/scpb.proto#L42)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Isn't this redundant now that you have `equal_all = true` at the top level?
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scpb/scpb.proto, line 59 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTIor6A-2zeZgGPESq:-Mvdougj3bR8Fv0wtbH9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26fd3ec3f30a415ffcd467ec564347469e75ca84/pkg/sql/schemachanger/scpb/scpb.proto#L59)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

nit: typo: truncated comment text
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scpb/scpb.proto, line 80 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTItaM0BXQWch6Roqo:-MvdoKZu83zwCUAeTFSO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26fd3ec3f30a415ffcd467ec564347469e75ca84/pkg/sql/schemachanger/scpb/scpb.proto#L80)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

nit: typo: bad message name in comment
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scpb/scpb.proto, line 107 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTNI3x6nmx85x1ctPy:-MvdoLDX84GyuxUpscH0:bfxhnna) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a63942673a99e391d33c1451a2c2e85816311aa/pkg/sql/schemachanger/scpb/scpb.proto#L107)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Since we're concerned about determinism, perhaps make this a list of key-value message pairs instead of a map?
</blockquote></details>

Done. Reworked all of this. 
___
*[pkg/sql/schemachanger/scplan/internal/scstage/build.go, line 380 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTNlTe5HwIoDRwpjk0:-MvdoNDx64Rbsa1s5QNu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a63942673a99e391d33c1451a2c2e85816311aa/pkg/sql/schemachanger/scplan/internal/scstage/build.go#L380)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Nice.
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scplan/internal/scstage/build.go, line 425 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTNprgEQXP31rRXiOr:-MvdoNsH3QO2FRgLa9Xw:bfxj3ms) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a63942673a99e391d33c1451a2c2e85816311aa/pkg/sql/schemachanger/scplan/internal/scstage/build.go#L425)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

File a follow-up issue and mark it as a release blocker, please.
</blockquote></details>

Done. https://github.com/cockroachdb/cockroach/issues/76441
___
*[pkg/sql/schemachanger/testdata/alter_table_add_column, line 28 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-MvTOpX2DyWvqv6QfO3P:-MvayBpkAyXskRmtqlY7:b-ysxf9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a63942673a99e391d33c1451a2c2e85816311aa/pkg/sql/schemachanger/testdata/alter_table_add_column#L28)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Perhaps we should redact the declarative schema changer state in these outputs? Or at least parts of it like the app name? Don't bother if it's too much trouble.
</blockquote></details>

handled.

**Review by postamar — APPROVED** [review]
:lgtm_strong: 

:ship: :it: 

> Reviewed 99 of 99 files at r10, 19 of 19 files at r11, 40 of 40 files at r12, 30 of 30 files at r13, 11 of 11 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76116#-:-MveO9-q6McTgYKbJKQp:b-fz38bi)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @stevendanna)

**Comment by ajwerner** [comment]
TFTR

bors r+

**Pull request merged**
