### PR TITLE
comments to #1598

### PR DESCRIPTION
**Pull request by tbg**
- randhelper->randutil as per @petermattis's preference
- use `fakeflags` only where `log` can't be force-imported, and explain why in a comment.

### CODE REVIEW

**Comment by bdarnell** [comment]
Can't you use an `_test` package for the `encoding` and `proto` packages? Just change the package statement in each package's `main_test.go` and you should be able to import `util/log` without a cycle.

**Comment by tschottdorf** [comment]
wow, I was able to remove them all. `fakeflags` is gone.

**Comment by tamird** [comment]
LGTM

**Comment by bdarnell** [comment]
LGTM

**Pull request merged**
