### PR TITLE
*: Add Rafi to AUTHORS

### PR DESCRIPTION
**Pull request by rafiss**
This is part of onboarding

### CODE REVIEW

**Review by asubiotto — APPROVED** [review]
LGTM. Usually the commit message titles start with a lowercase letter although I'm not sure we have strict guidelines here.

**Comment by rafiss** [comment]
bors r=asubiotto

**Comment by rafiss** [comment]
bors r=asubiotto

**Comment by rafiss** [comment]
bors r=asubiotto

**Pull request merged**
