### PR TITLE
settings,server,sql: rationalize StateMachineSetting

### PR DESCRIPTION
**Pull request by andreimatei**
Before this patch, a StateMachineSetting was driven mostly by a
TransformerFn - a function with a mesmerizing mostly undocumented
interface and with code that I can't read. Depending on the arguments
and the current state of... I can't say what exactly... that function
somehow served all the needs of a cluster version setting - it performed
validation for upgrades, it performed deserialization into multiple
formats of the "current value", etc. For validation I think it also
dealt with two different types of updates - some coming from a user with
tentative values, some coming from gossip with values we can't refuse.

This patch tries to make code saner by more clearly splitting
StateMachineSetting code into a Setting implementation that's agnostic
of what the setting is exactly and deals with state saving and loading
mostly, and an implementation that deals with parsing and validation.
The implementation now mostly replaces the TransformerFn and is now
represented by a StateMachineSettingImpl interface which contains
multiple methods for specific purposes.

This patch also reduces the footprint of the ExposedClusterVersion. It
used to contain MinSupportedVersion and ServerVersion which were used
for validating new versions, but also for other purposes like
ExposedClusterVersion.BootstrapVersion(). These fields go away. Instead,
for version validation purposes, the Settings object now gets the
binary's supported versions. I think they belong better there, as now
the StateMachineSettingImpl doesn't need to reach into a particular
Setting any more, it just needs to reach into the Settings object. And
other uses of the fields go away by the Server generally being more
explicit about what versions it wants to use for different things rather
than getting them from the ExposedClusterVersion.

Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
r1 and r2 are #34156

@tbg I've been toiling in here and struggling like a flipped cockroach. This PR is not ready at all, but I'd appreciate it if you could look it over a bit and tell me if the direction looks promising to you.

**Review by tbg — COMMENTED** [review]
I like the interface you introduced. Are you running into any tricky problems yet?

> Reviewed 3 of 3 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34160#-:-LWogvaQ3wSPrjArOzAi:b-urqgng)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/settings/statemachine.go, line 39 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34160#-LWoelIf5k-VskS91K9b:-LWoelIf5k-VskS91K9c:biddpim) ([raw file](https://github.com/cockroachdb/cockroach/blob/d30d7ab0a6795f93e66e82f8162dec03db9cff2c/pkg/settings/statemachine.go#L39)):*
> ```Go
> 	DecodeToString(val []byte) (string, error)
> 
> 	// ValidateLogical checks whether an update is permitted. It takes in the old
> ```

I'd say that this is validating a state machine transition desired by the user, whereas ValidateLogical can check whether the current node is incompatible with the value the state machine setting holds, and provides an opportunity to bail out.
___
*[pkg/settings/cluster/settings.go, line 296 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34160#-LWoeEJw03WsWxJnit4d:-LWoeEJw03WsWxJnit4e:by50tz) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf3268433f0337afe92de172eea0752906c04fe8/pkg/settings/cluster/settings.go#L296)):*
> CLUSTE

also, you want `SET CLUSTER SETTING`? Though `SHOW CLUSTER SETTING` also needs to call this somehow and it would be worth pointing out how.
___
*[pkg/sql/show_cluster_setting.go, line 75 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34160#-LWogay94IJQA0zgww1P:-LWogay94IJQA0zgww1Q:bm16php) ([raw file](https://github.com/cockroachdb/cockroach/blob/d30d7ab0a6795f93e66e82f8162dec03db9cff2c/pkg/sql/show_cluster_setting.go#L75)):*
> ```Go
> 
> 			// !!!
> 			// // Note that if no entry is found, we pretend that an entry
> ```

You may want to `blame` this change, I think without it there might be some flakiness (where `SET CLUSTER SETTING version` fails until this migration has run).

**Comment by tbg** [comment]
PS first two comments are LGTM for their respective PRs

**Comment by andreimatei** [comment]
this was merged elsewhere

**Pull request closed without merging**
