### PR TITLE
colexecsel: optimize null handling a bit

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexecsel: clean up and extend benchmarks**

This commit refactors the benchmarks of the selection operators to
extract common code. It also adds `Bytes LT Bytes` benchmark.

Release note: None

**colexecsel: optimize null handling a bit**

Previously, in selection operators we would always perform the
comparison (to see whether a value is "selected"), but if the output
vector might have nulls we would also do the null check. The value would
only be included if it is non-null and was selected. Since we need to do
the null check anyway, we can short-circuit if the value is null and
skip the comparison.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
The microbenchmarks are a bit surprising:
```
name                                                   old time/op    new time/op    delta
SelLTInt64Int64ConstOp/useSel=true,hasNulls=true-24      2.97µs ± 1%    3.00µs ± 4%   +1.03%  (p=0.046 n=9+10)
SelLTInt64Int64ConstOp/useSel=true,hasNulls=false-24     2.04µs ± 1%    1.85µs ± 1%   -9.17%  (p=0.000 n=9+8)
SelLTInt64Int64ConstOp/useSel=false,hasNulls=true-24     2.56µs ± 1%    3.37µs ± 2%  +31.85%  (p=0.000 n=9+10)
SelLTInt64Int64ConstOp/useSel=false,hasNulls=false-24    1.76µs ± 1%    1.56µs ± 0%  -11.65%  (p=0.000 n=10+9)
SelLTInt64Int64Op/useSel=true,hasNulls=true-24           4.15µs ± 0%    3.92µs ± 1%   -5.63%  (p=0.000 n=10+10)
SelLTInt64Int64Op/useSel=true,hasNulls=false-24          2.43µs ± 1%    2.58µs ± 0%   +6.16%  (p=0.000 n=10+9)
SelLTInt64Int64Op/useSel=false,hasNulls=true-24          3.46µs ± 1%    4.15µs ± 1%  +20.05%  (p=0.000 n=10+9)
SelLTInt64Int64Op/useSel=false,hasNulls=false-24         2.06µs ± 1%    1.99µs ± 1%   -3.46%  (p=0.000 n=10+10)

name                                                   old speed      new speed      delta
SelLTInt64Int64ConstOp/useSel=true,hasNulls=true-24    2.76GB/s ± 1%  2.73GB/s ± 5%     ~     (p=0.053 n=9+10)
SelLTInt64Int64ConstOp/useSel=true,hasNulls=false-24   4.01GB/s ± 0%  4.42GB/s ± 1%  +10.18%  (p=0.000 n=8+8)
SelLTInt64Int64ConstOp/useSel=false,hasNulls=true-24   3.21GB/s ± 1%  2.43GB/s ± 2%  -24.15%  (p=0.000 n=9+10)
SelLTInt64Int64ConstOp/useSel=false,hasNulls=false-24  4.65GB/s ± 1%  5.27GB/s ± 0%  +13.17%  (p=0.000 n=10+9)
SelLTInt64Int64Op/useSel=true,hasNulls=true-24         3.95GB/s ± 0%  4.18GB/s ± 1%   +5.97%  (p=0.000 n=10+10)
SelLTInt64Int64Op/useSel=true,hasNulls=false-24        6.74GB/s ± 1%  6.35GB/s ± 0%   -5.80%  (p=0.000 n=10+9)
SelLTInt64Int64Op/useSel=false,hasNulls=true-24        4.74GB/s ± 1%  3.93GB/s ± 3%  -16.96%  (p=0.000 n=10+10)
SelLTInt64Int64Op/useSel=false,hasNulls=false-24       7.96GB/s ± 1%  8.24GB/s ± 1%   +3.59%  (p=0.000 n=10+10)
```
However, these are only on int64, and I bet on other types we'll see an improvement, will add another commit with such a benchmark.

**Comment by jordanlewis** [comment]
I'm not sure that it's surprising in this case that we're worse, because I believe the commit adds an extra conditional where before there was just 1. The CPU is happier with fewer conditionals, so in the integer case, we are trading off an extra conditional for the fixed and very cheap cost of an integer compare. I agree for more expensive Compare methods that the pre-check would be better.

**Comment by yuzefovich** [comment]
Ok, yeah, it makes sense. I think, given that very high speed of integer selection operators and - expected - much lower speed of other comparisons, it'll be a beneficial change overall. We could optimize the template to be a bit different based on type, but I'm not sure whether it'll be worth it in this case.

**Comment by yuzefovich** [comment]
I added another commit that refactored the benchmarks a bit and added Bytes LT Bytes benchmark. The number of the first commits are [here](https://gist.github.com/yuzefovich/fc3b434730183ee523e5d2d98f97a645) (I wanted to see whether there is any noticeable difference because of the benchmark refactor; it shows that there is a bit, so I'll backport only the first commit to 21.1 branch so that benchmark comparison between 21.1 and 21.2 was fair in the future).

Here are the numbers of the second commit:
```
name                                                   old time/op    new time/op    delta
SelLTInt64Int64ConstOp/useSel=true,hasNulls=true-24      2.97µs ± 0%    2.80µs ± 1%   -5.90%  (p=0.000 n=10+10)
SelLTInt64Int64ConstOp/useSel=true,hasNulls=false-24     2.00µs ± 1%    2.17µs ± 2%   +8.41%  (p=0.000 n=10+10)
SelLTInt64Int64ConstOp/useSel=false,hasNulls=true-24     2.57µs ± 0%    2.92µs ± 0%  +13.74%  (p=0.000 n=10+10)
SelLTInt64Int64ConstOp/useSel=false,hasNulls=false-24    2.11µs ± 1%    1.58µs ± 1%  -25.27%  (p=0.000 n=10+10)
SelLTInt64Int64Op/useSel=true,hasNulls=true-24           4.10µs ± 0%    3.89µs ± 0%   -5.13%  (p=0.000 n=10+8)
SelLTInt64Int64Op/useSel=true,hasNulls=false-24          2.63µs ± 1%    2.51µs ± 1%   -4.63%  (p=0.000 n=10+9)
SelLTInt64Int64Op/useSel=false,hasNulls=true-24          3.49µs ± 1%    3.70µs ± 1%   +6.18%  (p=0.000 n=10+10)
SelLTInt64Int64Op/useSel=false,hasNulls=false-24         2.03µs ± 0%    2.42µs ± 1%  +18.75%  (p=0.000 n=9+10)
SelLTBytesBytesOp/useSel=true,hasNulls=true-24           24.1µs ± 0%    16.6µs ± 1%  -30.94%  (p=0.000 n=10+10)
SelLTBytesBytesOp/useSel=true,hasNulls=false-24          21.6µs ± 0%    21.7µs ± 0%   +0.42%  (p=0.000 n=9+10)
SelLTBytesBytesOp/useSel=false,hasNulls=true-24          24.2µs ± 0%    17.9µs ± 0%  -26.32%  (p=0.000 n=10+10)
SelLTBytesBytesOp/useSel=false,hasNulls=false-24         20.7µs ± 0%    20.2µs ± 0%   -2.32%  (p=0.000 n=10+7)

name                                                   old speed      new speed      delta
SelLTInt64Int64ConstOp/useSel=true,hasNulls=true-24    2.76GB/s ± 0%  2.93GB/s ± 1%   +6.28%  (p=0.000 n=10+10)
SelLTInt64Int64ConstOp/useSel=true,hasNulls=false-24   4.10GB/s ± 1%  3.78GB/s ± 2%   -7.74%  (p=0.000 n=10+10)
SelLTInt64Int64ConstOp/useSel=false,hasNulls=true-24   3.19GB/s ± 0%  2.80GB/s ± 0%  -12.08%  (p=0.000 n=10+10)
SelLTInt64Int64ConstOp/useSel=false,hasNulls=false-24  3.87GB/s ± 1%  5.18GB/s ± 1%  +33.82%  (p=0.000 n=10+10)
SelLTInt64Int64Op/useSel=true,hasNulls=true-24         4.00GB/s ± 0%  4.22GB/s ± 0%   +5.45%  (p=0.000 n=10+9)
SelLTInt64Int64Op/useSel=true,hasNulls=false-24        6.24GB/s ± 1%  6.54GB/s ± 1%   +4.77%  (p=0.000 n=10+8)
SelLTInt64Int64Op/useSel=false,hasNulls=true-24        4.70GB/s ± 1%  4.43GB/s ± 1%   -5.82%  (p=0.000 n=10+10)
SelLTInt64Int64Op/useSel=false,hasNulls=false-24       8.06GB/s ± 0%  6.78GB/s ± 1%  -15.80%  (p=0.000 n=9+10)
SelLTBytesBytesOp/useSel=true,hasNulls=true-24          680MB/s ± 0%   984MB/s ± 1%  +44.80%  (p=0.000 n=10+10)
SelLTBytesBytesOp/useSel=true,hasNulls=false-24         759MB/s ± 0%   756MB/s ± 0%   -0.42%  (p=0.000 n=9+10)
SelLTBytesBytesOp/useSel=false,hasNulls=true-24         676MB/s ± 0%   917MB/s ± 0%  +35.72%  (p=0.000 n=10+10)
SelLTBytesBytesOp/useSel=false,hasNulls=false-24        790MB/s ± 0%   809MB/s ± 0%   +2.38%  (p=0.000 n=10+7)
```
Note that the bytes values are of length 8 here, so IMO it is a clear win in general. @jordanlewis let me know if you think that introducing a bit more trickery into the template so that in order to not regress on ints and floats is worth it (like we'll have some more template conditional). I don't think it is though given that the absolute speeds are just so high anyway.

**Comment by yuzefovich** [comment]
Huh, just noticed
```
SelLTInt64Int64ConstOp/useSel=false,hasNulls=false-24  3.87GB/s ± 1%  5.18GB/s ± 1%  +33.82%  (p=0.000 n=10+10)
```
so the second commit made the benchmark when nulls are definitely not present faster for ints 🤔  This makes me want to ignore any differences once the throughput is over a couple of GBs per second.

**Review by michae2 — APPROVED** [review]
:lgtm:

Yes, I agree, the tinier the action the more likely to be influenced by transient systematic error during measurement (e.g. CPU using turboboost one run and not the next, or hot cache one run and not the next, or landing on the same core as Slack doing some Electron bullshit one run and not the next...). Or even the observer effect (maybe the limit of `go bench` precision is roughly 2 µs) though I suppose doing many iterations reduces this.

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64224#-:-MZUw6FQ0aVgW0_LhyGG:be5utjo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
(`./scripts/bench` runs things 10 times and uses `benchstat` to remove outliers. Also, note that I usually run the benchmarks on the gceworker (`./scripts/gceworker.sh`), so there is nothing else influencing the numbers - the numbers on the local mac are very susceptible to noise.)

TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64224#-:-MZV2fuU5Kucc1i5pRAg:bm4dayq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Pull request merged**
