### PR TITLE
storage/cloud: return relative paths for explicit patterns, preserve URI params

### PR DESCRIPTION
**Pull request by dt**
This changes the results returned by `ListFiles` to be relative paths when a relative pattern is used for listing.

Specifically, when `ListFiles` is invoked with an explicit pattern argument (as opposed to when the entire base-path for the storage connection is itself the pattern), the paths returned in the results are the relative paths of each match, relative to the connection's configured base path, rather than individually fully-qualified URIs (which are what it returns when not passed a relative pattern as an argument).

The reason for this is that a storage connection instance can be used two ways: 1) initialized with a single, full path to some file or globs pattern as its "base" path and used once, to perform the intended operation on that file and then closed, or 2) initialized with some common base path in which it can then be reused to read, write and list different files, passing their relative path within that prefix each time, without having to recreate the client on every operation. When `ListFiles` is used in the later case, returning relative results when queried for files matching a pattern and means it can then be asked to open those files it returned, e.g:
```
x := cloud.NewFoo('somebucket', 'some/path/prefix')
for _, i := range x.ListFiles('*.csv') {
  f := x.ReadFile(i)
...
```

Note: For now, this also imposes the restriction that all matched results are within the base path (i.e. that the pattern wasn't `../../*.csv`) for simplicity of calculating its relative paths (via simple prefix removal). For more  fundamental reasons, the base path cannot itself contain patterns since a) that would make it hard to define what the relative path is and b) in the intended usage of re-using a single long-lived connection object to also read/write, that doesn't make sense.

Release note: none.

While I'm here:
These fully qualified URIs did not previously include provider-specific query parameters, so even if
the correct access keys / tokens were provided to do the initial listing connection, after expansion,
the result file URIs would encounter missing permission errors if the implementation required them (e.g. s3).

Release note: none.

While I'm here: we should be using `path` instead of `filepath` throughout.

### CODE REVIEW

**Review by miretskiy — APPROVED** [review]
> Reviewed 10 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44954)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, and @miretskiy)

___
*[pkg/storage/cloud/nodelocal_storage.go, line 114 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44954#-M-oeKnV9ikKLAAWLVA5:-M-oeKnV9ikKLAAWLVA6:b-xf1l5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa48c3a4a56e2d5b4e93cdfb2dd1b6630162077e/pkg/storage/cloud/nodelocal_storage.go#L114)):*
> ```Go
> 			if !strings.HasPrefix(fileName, l.base) {
> 				// TODO(dt): return a nice rel-path instead of erroring out.
> 				return nil, errors.New("pattern matched file outside of path")
> ```

"outside of base path"? maybe include l.base in the err?

**Review by ajwerner — APPROVED** [review]
:lgtm: mod the need to document the interface behavior. 

> Reviewed 3 of 3 files at r1, 4 of 4 files at r2, 5 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44954#-:-M-ooAqs8AGzRX6vG3gC:brepg7c)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/storage/cloud/external_storage.go, line 119 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44954#-M-oo2Kk5oquM5I30fYR:-M-oo2Kl4HgAPYw4cYBH:b9jx2kx) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa48c3a4a56e2d5b4e93cdfb2dd1b6630162077e/pkg/storage/cloud/external_storage.go#L119)):*
> ```Go
> 	// ListFiles should treat the ExternalStorage URI plus the passed suffix as a
> 	// glob pattern, and return a list of files that match the pattern.
> 	ListFiles(ctx context.Context, patternSuffix string) ([]string, error)
> ```

Can you please update this comment to reflect the new behavior.
___
*[pkg/storage/cloud/s3_storage.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44954#-M-ohXdq1XjWNw3QB3DN:-M-ohXdr6_DFK8ybjXLx:b-y579tu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b20768fab17e111c54c6d58df3a67c093632a01/pkg/storage/cloud/s3_storage.go#L150)):*
> ```Go
> }
> 
> func getBucketBeforeWildcard(path string) string {
> ```

It’s fixed later but this commit won’t build because you need to rename the param to p. Can you fix the history so a bisect doesn’t later barf here?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44954)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @miretskiy)

___
*[pkg/storage/cloud/external_storage.go, line 119 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44954#-M-oo2Kk5oquM5I30fYR:-M-p9PzyD3j9Wx_shgj9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa48c3a4a56e2d5b4e93cdfb2dd1b6630162077e/pkg/storage/cloud/external_storage.go#L119)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can you please update this comment to reflect the new behavior.
</blockquote></details>

Done.
___
*[pkg/storage/cloud/nodelocal_storage.go, line 114 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44954#-M-oeKnV9ikKLAAWLVA5:-M-p9_z0EhSiqo8Qtfp_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa48c3a4a56e2d5b4e93cdfb2dd1b6630162077e/pkg/storage/cloud/nodelocal_storage.go#L114)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

"outside of base path"? maybe include l.base in the err?
</blockquote></details>

Done.
___
*[pkg/storage/cloud/s3_storage.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44954#-M-ohXdq1XjWNw3QB3DN:-M-ooSY86KGv6Pj9mjcq:b-9fb2ua) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b20768fab17e111c54c6d58df3a67c093632a01/pkg/storage/cloud/s3_storage.go#L150)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

It’s fixed later but this commit won’t build because you need to rename the param to p. Can you fix the history so a bisect doesn’t later barf here?
</blockquote></details>

nice catch! 
Done.

**Pull request merged**
