### PR TITLE
workload/tpcc: make partitioning support multiple partitions per client

### PR DESCRIPTION
**Pull request by ajwerner**
The tricky bit here is that the partitioning scheme in the partitioner
make assumptions about how partitions are handed out to clients and then
how pgurls map to partitions. The approach in this PR makes basic
assumptions which may lead to problems in the future.

One alternative would be to provide another flag to make the mapping
mapping between urls and partitions more explicit. The current PR
was designed to not break anything that currently exists.

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41659)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/workload/tpcc/tpcc.go, line 650 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41659#-LsObLD95h59JmWg5G-h:-LsObLDA4cwk6cEuMePc:b-9020b0) ([raw file](https://github.com/cockroachdb/cockroach/blob/50d4345ed01c054f6f015525202423a4455a8126/pkg/workload/tpcc/tpcc.go#L650)):*
> ```Go
> 	// partitions.
> 	isMyPart := func(p int) bool {
> 		for _, ap := range w.affinityPartitions {
> ```

What if `w.affinityPartitions == nil`? Won't this always return false?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41659)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/workload/tpcc/tpcc.go, line 650 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41659#-LsObLD95h59JmWg5G-h:-LsOe1Lk257XilDPfXBG:b-rt6gju) ([raw file](https://github.com/cockroachdb/cockroach/blob/50d4345ed01c054f6f015525202423a4455a8126/pkg/workload/tpcc/tpcc.go#L650)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What if `w.affinityPartitions == nil`? Won't this always return false?
</blockquote></details>

derp.

**Review by nvb — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41659#-:-LsOfsxf6cevhWday0JP:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by ajwerner** [comment]
TFTR!

bors r=nvanbenschoten

**Pull request merged**
