### PR TITLE
opt: Remove correlated Subquery operators from expression tree

### PR DESCRIPTION
**Pull request by andy-kimball**
This PR contains multiple commits that work together to remove correlated Subquery operators from the expression tree.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Great stuff. Still mulling over the last commit.

---

Review status: 0 of 39 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/opt/memo/logical_props_builder_test.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25124#-LB8Gs-dCfcq0uaGTDCc:-LB8Gs-dCfcq0uaGTDCd:bus2999) ([raw file](https://github.com/cockroachdb/cockroach/blob/2feed6a88a8bf71553edde2cbb3f218772c882a9/pkg/sql/opt/memo/logical_props_builder_test.go#L54)):*
> ```Go
> 	}
> 
> 	test("SELECT y FROM a WHERE 1=1", false /* expected */)
> ```

[nit] It's preferable to put the test data in a []struct, it usually requires less refactoring if something changes. Just mentioning it for the future, no need to rewrite this one.

```
testCases := []struct{
  sql string
  expected bool
} {
  { sql: "SELECT ..", expected: false },
  ...
}

for _, tc := range testCases {
  tester := ...
}
```

---

*[pkg/sql/opt/norm/decorrelate.go, line 32 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25124#-LB8xqa09jqopOvbPtEd:-LB8xqa09jqopOvbPtEe:b-nyysv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b84b7c1d0d67e6a91259bab253334f1511dcb99c/pkg/sql/opt/norm/decorrelate.go#L32)):*
> ```Go
> //   (Project
> //     (Select
> //       (LeftJoinApply $input <hoisted-subquery> (True))
> ```

In this rule, it looks like an InnerJoinApply would make more sense (why return rows for which the subquery returned no rows?). Are there cases I'm not seeing where LeftJoinApply is required?

---

*[pkg/sql/opt/norm/rules/decorrelate.opt, line 120 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25124#-LB8v0_Z4zJuOlQoHCXA:-LB8v0_Z4zJuOlQoHCXB:bjy8vlz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b84b7c1d0d67e6a91259bab253334f1511dcb99c/pkg/sql/opt/norm/rules/decorrelate.opt#L120)):*
> ```
> # NOTE: Keep this ordered after the HoistSelectExists and HoistSelectNotExists
> #       rules. This rule will hoist any existential subqueries using
> #       InnerJoinApply, which is equivalent to, but not as efficient as, using
> ```

hoistSelectSubquery uses LeftJoinApply

---

*[pkg/sql/opt/norm/rules/decorrelate.opt, line 121 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25124#-LB8ummd8uHeYk7JzeRG:-LB8uj4M9mOdwd8dJ8ks:bl24luy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b84b7c1d0d67e6a91259bab253334f1511dcb99c/pkg/sql/opt/norm/rules/decorrelate.opt#L121)):*
> ```
> #       rules. This rule will hoist any existential subqueries using
> #       InnerJoinApply, which is equivalent to, but not as efficient as, using
> #       SemiJoinApply and SemiJoinApply.
> ```

SemiJoinApply and AntiJoinApply

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25124#-:-LBBVzJQ77-GE_Xxt8re:bq411r0)*

**Comment by andy-kimball** [comment]
Review status: 0 of 39 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/memo/logical_props_builder_test.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25124#-LB8Gs-dCfcq0uaGTDCc:-LBB_aSz5onI0N_CI5cO:byhzppa) ([raw file](https://github.com/cockroachdb/cockroach/blob/2feed6a88a8bf71553edde2cbb3f218772c882a9/pkg/sql/opt/memo/logical_props_builder_test.go#L54)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] It's preferable to put the test data in a []struct, it usually requires less refactoring if something changes. Just mentioning it for the future, no need to rewrite this one.

```
testCases := []struct{
  sql string
  expected bool
} {
  { sql: "SELECT ..", expected: false },
  ...
}

for _, tc := range testCases {
  tester := ...
}
```
</blockquote></details>

I went ahead and made this change. It's nice I don't have to use `/* expected */`.

---

*[pkg/sql/opt/norm/decorrelate.go, line 32 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25124#-LB8xqa09jqopOvbPtEd:-LBBXg3U8FsLO59V--0r:b219j95) ([raw file](https://github.com/cockroachdb/cockroach/blob/b84b7c1d0d67e6a91259bab253334f1511dcb99c/pkg/sql/opt/norm/decorrelate.go#L32)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

In this rule, it looks like an InnerJoinApply would make more sense (why return rows for which the subquery returned no rows?). Are there cases I'm not seeing where LeftJoinApply is required?
</blockquote></details>

Here's an example:

`SELECT * FROM xy WHERE (SELECT u FROM uv WHERE u=x LIMIT 1) = 5`

that will be rewritten as:

`SELECT * FROM xy LEFT JOIN  (SELECT u FROM uv WHERE u=x LIMIT 1) ON True WHERE u = 5`

If the subquery returns zero rows, then `u` needs to be bound to `NULL`, which is why we need the left join.

I'm going to switch these comments to use SQL examples, to make it easier to show the before/after.

---

*[pkg/sql/opt/norm/rules/decorrelate.opt, line 120 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25124#-LB8v0_Z4zJuOlQoHCXA:-LBBZ90p5QS2SPf6Hxof:b-wgow9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/b84b7c1d0d67e6a91259bab253334f1511dcb99c/pkg/sql/opt/norm/rules/decorrelate.opt#L120)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

hoistSelectSubquery uses LeftJoinApply
</blockquote></details>

That comment is looking ahead towards my next PR, which will indeed use `InnerJoinApply` to hoist existential subqueries that can't be hoisted using `SemiJoinApply`. Existential subqueries are compiled using scalar `GroupBy` which always has cardinality one, and so we can use `InnerJoinApply`. In this PR, I'm not yet hoisting existential subqueries using this code, so this comment is premature, but I didn't want to forget to add it later.

---

*[pkg/sql/opt/norm/rules/decorrelate.opt, line 121 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25124#-LB8ummd8uHeYk7JzeRG:-LBBZmgADEVNw8VWWQB_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b84b7c1d0d67e6a91259bab253334f1511dcb99c/pkg/sql/opt/norm/rules/decorrelate.opt#L121)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

SemiJoinApply and AntiJoinApply
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25124)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/norm/decorrelate.go, line 32 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25124#-LB8xqa09jqopOvbPtEd:-LBBxncA-rHgvbfrGGev:btbuyj0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b84b7c1d0d67e6a91259bab253334f1511dcb99c/pkg/sql/opt/norm/decorrelate.go#L32)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Here's an example:

`SELECT * FROM xy WHERE (SELECT u FROM uv WHERE u=x LIMIT 1) = 5`

that will be rewritten as:

`SELECT * FROM xy LEFT JOIN  (SELECT u FROM uv WHERE u=x LIMIT 1) ON True WHERE u = 5`

If the subquery returns zero rows, then `u` needs to be bound to `NULL`, which is why we need the left join.

I'm going to switch these comments to use SQL examples, to make it easier to show the before/after.
</blockquote></details>

INNER JOIN would work there too.. But I guess that's just because the filter never passes with `NULL` . I guess something like `WHERE (SELECT u FROM uv WHERE u=x LIMIT 1) IS NULL` does require left join.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25124)*

**Comment by andy-kimball** [comment]
Review status: 0 of 40 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/opt/norm/decorrelate.go, line 32 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25124#-LB8xqa09jqopOvbPtEd:-LBC-sH09cC-joA6HyZ0:b-er756u) ([raw file](https://github.com/cockroachdb/cockroach/blob/b84b7c1d0d67e6a91259bab253334f1511dcb99c/pkg/sql/opt/norm/decorrelate.go#L32)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

INNER JOIN would work there too.. But I guess that's just because the filter never passes with `NULL` . I guess something like `WHERE (SELECT u FROM uv WHERE u=x LIMIT 1) IS NULL` does require left join.
</blockquote></details>

True, at higher scope you can rewrite INNER JOIN => LEFT JOIN. That would be a different rule that would detect and rewrite that case.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25124)*

**Comment by andy-kimball** [comment]
Review status: 0 of 40 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/opt/norm/decorrelate.go, line 32 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25124#-LB8xqa09jqopOvbPtEd:-LBC0DG77_oyePikqsie:b-bh0ls9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b84b7c1d0d67e6a91259bab253334f1511dcb99c/pkg/sql/opt/norm/decorrelate.go#L32)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

True, at higher scope you can rewrite INNER JOIN => LEFT JOIN. That would be a different rule that would detect and rewrite that case.
</blockquote></details>

I mean LEFT JOIN => INNER JOIN.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25124)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 40 files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/opt/norm/decorrelate.go, line 28 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/25124#-LBMC5k85-zEc0vRPty5:-LBMC5k92zXoc-9wemHu:b-uzf8fu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c4064c8a8a0dc0f4f164369ce8f6c83e1b9fb96/pkg/sql/opt/norm/decorrelate.go#L28)):*
> ```Go
> // subqueries. Any found queries are hoisted into LeftJoinApply operators:
> //
> //   SELECT * FROM xy WHERE (SELECT u FROM uv WHERE u=x LIMIT 1) IS NULL
> ```

These new comments that use SQL are much more helpful, thanks!

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25124#-:-LBMDHKaCJ5vBc9HXMO7:bnfp4nl)*

**Pull request merged**
