### PR TITLE
roachprod-microbench: export metrics

### PR DESCRIPTION
**Pull request by herkolategan**
This PR contains a few commits related to adding support for exporting metrics in open metrics format.
The first two commits replace deprecated golang perf dependencies, and the final commit introduces the export command.

Epic: [CRDB-20903](https://cockroachlabs.atlassian.net/browse/CRDB-20903)
Release note: None

### CODE REVIEW

**Review by renatolabs — COMMENTED** [review]
Looks great!

> Reviewed 4 of 4 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104300#-:-NXuAiQn5OfJwY03aHLD:b9bkkp1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachprod-microbench/export.go` line 93 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104300#-NXu8HbM0TljnTcRjdXL:-NXu8HbM0TljnTcRjdXM:b-e6lf73) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f82c0108cba6b809a521757d9e8c99ee040df81/pkg/cmd/roachprod-microbench/export.go#L93)):*
> ```Go
> func sanitize(input string) string {
> 	if len(input) == 0 {
> 		return "_"
> ```

Is this logic relied on somewhere? Not sure I understand the significance of an empty input.
___
*[`pkg/cmd/roachprod-microbench/export.go` line 107 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104300#-NXu8TYY-xEFG1ZJR9SA:-NXu8TYY-xEFG1ZJR9SB:b-b2c167) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f82c0108cba6b809a521757d9e8c99ee040df81/pkg/cmd/roachprod-microbench/export.go#L107)):*
> ```Go
> 		builder.WriteRune(b)
> 	}
> 	return builder.String()
> ```

Looks like something more concisely done with a regular expression.
___
*[`pkg/cmd/roachprod-microbench/google/service.go` line 196 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104300#-NXu7B2UE7zwsC5NVFUJ:-NXu7B2VD6jdufXDz-Ru:b43ucnb) ([raw file](https://github.com/cockroachdb/cockroach/blob/923dd53e305b9b537be1a57a1e07bfc78076c47d/pkg/cmd/roachprod-microbench/google/service.go#L196)):*
> ```Go
> 	// Sort comparisons by delta, or the benchmark name if no delta is available.
> 	keys := maps.Keys(comparisons)
> 	sort.SliceStable(keys, func(i, j int) bool {
> ```

Given that the return value of `maps.Keys` is non-deterministic, it doesn't make sense to use stable sorting.
___
*[`pkg/cmd/roachprod-microbench/model/builder.go` line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104300#-NXtxjuQC0b0GONMt5ke:-NXtxjuQC0b0GONMt5kf:b-cj84bq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fdd0d0dabea9e0e8f0f4940b80062b62441b3b0/pkg/cmd/roachprod-microbench/model/builder.go#L49)):*
> ```Go
> // benchmark name for all benchmarks. The id is used to identify the source of
> // the metrics, e.g. the run the metrics came from.
> func (b *Builder) AddMetrics(id string, prefix string, reader *benchfmt.Reader) error {
> ```

I could swear there was a linter that would force you to write `id, prefix string` but I guess not since CI is green. :thinking: 
___
*[`pkg/cmd/roachprod-microbench/model/builder.go` line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104300#-NXtyDvf3ZDqOTCbPRzn:-NXtyDvgD2QntuBDAphS:b-6fa1ym) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fdd0d0dabea9e0e8f0f4940b80062b62441b3b0/pkg/cmd/roachprod-microbench/model/builder.go#L51)):*
> ```Go
> func (b *Builder) AddMetrics(id string, prefix string, reader *benchfmt.Reader) error {
> 	for reader.Scan() {
> 		switch res := reader.Result(); rec := res.(type) {
> ```

Nit: `switch rec := reader.Result().(type)`?
___
*[`pkg/cmd/roachprod-microbench/model/builder.go` line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104300#-NXtySFF6BWRPrLkoQOo:-NXtySFF6BWRPrLkoQOp:bkhkvum) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fdd0d0dabea9e0e8f0f4940b80062b62441b3b0/pkg/cmd/roachprod-microbench/model/builder.go#L53)):*
> ```Go
> 		switch res := reader.Result(); rec := res.(type) {
> 		case *benchfmt.SyntaxError:
> 			return fmt.Errorf("syntax error: %v", rec)
> ```

Is there a situation where this can legitimately happen? If so, worth adding a comment.
___
*[`pkg/cmd/roachprod-microbench/model/builder.go` line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104300#-NXu2J2p98iOOyhlThel:-NXu2J2p98iOOyhlThem:b-381l7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fdd0d0dabea9e0e8f0f4940b80062b62441b3b0/pkg/cmd/roachprod-microbench/model/builder.go#L60)):*
> ```Go
> 				entry := metric.resolveEntry(benchmarkName)
> 				values := entry.resolveValues(id)
> 				*values = append(*values, value.Value)
> ```

I now see why the `Values` field is a pointer to slice. This seems like a surprising API to me though, where callers change the underlying value of a struct field from the outside. How about having `entry.addValue(value.Value)` instead?
___
*[`pkg/cmd/roachprod-microbench/model/builder.go` line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104300#-NXu3bF3EI5FHAWqT6iA:-NXu3bF3EI5FHAWqT6iB:bqfb0o6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fdd0d0dabea9e0e8f0f4940b80062b62441b3b0/pkg/cmd/roachprod-microbench/model/builder.go#L94)):*
> ```Go
> func (m *Metric) ComputeComparison(benchmarkName, oldID, newID string) *Comparison {
> 	benchmarkEntry := m.BenchmarkEntries[benchmarkName]
> 	if benchmarkEntry == nil {
> ```

So passing an invalid benchmarkName is an expected situation?
___
*[`pkg/cmd/roachprod-microbench/model/builder.go` line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104300#-NXu3m2rBw9qKPGCxODn:-NXu3m2rBw9qKPGCxODo:bxefq0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fdd0d0dabea9e0e8f0f4940b80062b62441b3b0/pkg/cmd/roachprod-microbench/model/builder.go#L99)):*
> ```Go
> 	for _, run := range []string{oldID, newID} {
> 		if benchmarkEntry.Samples[run] == nil || benchmarkEntry.Summaries[run] == nil {
> 			return nil
> ```

Is this dealing with the case where a benchmark was added or removed between the two runs? Worth spelling it out either way.
___
*[`pkg/cmd/roachprod-microbench/model/builder.go` line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104300#-NXu4Bw_DBQdIwVGHm_p:-NXu4Bw_DBQdIwVGHm_q:b-mej6n3) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fdd0d0dabea9e0e8f0f4940b80062b62441b3b0/pkg/cmd/roachprod-microbench/model/builder.go#L111)):*
> ```Go
> 		comparison.Delta = 0.0
> 	} else {
> 		comparison.Delta = ((newSummary.Center / oldSummary.Center) - 1.0) / 100
> ```

It might be because I'm a noob, but I don't understand this formula, heh.
___
*[`pkg/cmd/roachprod-microbench/model/metric.go` line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104300#-NXu1sn0B2fcw-BAIIrs:-NXu1sn0B2fcw-BAIIrt:buhowxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fdd0d0dabea9e0e8f0f4940b80062b62441b3b0/pkg/cmd/roachprod-microbench/model/metric.go#L40)):*
> ```Go
> // microbenchmark(s), e.g. the run the microbenchmark(s) came from.
> type BenchmarkEntry struct {
> 	Values    map[string]*[]float64
> ```

Why do we need a pointer to slice?

**Review by herkolategan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104300)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachprod-microbench/export.go` line 93 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104300#-NXu8HbM0TljnTcRjdXL:-NYSZ2czDZdh4WtuXk-v:b9ehi3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f82c0108cba6b809a521757d9e8c99ee040df81/pkg/cmd/roachprod-microbench/export.go#L93)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Is this logic relied on somewhere? Not sure I understand the significance of an empty input.
</blockquote></details>

Not entirely, unless a user decides to pass an empty string as part of the labels argument in the `cli`. Prometheus doesn't allow empty labels or values. We could also outright fail if an empty label or label value is supplied.
___
*[`pkg/cmd/roachprod-microbench/export.go` line 107 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104300#-NXu8TYY-xEFG1ZJR9SA:-NYSZPRQDIhCtaqg0RH8:b-yqi9w9) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f82c0108cba6b809a521757d9e8c99ee040df81/pkg/cmd/roachprod-microbench/export.go#L107)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Looks like something more concisely done with a regular expression.
</blockquote></details>

It can, I reckoned explicit code makes it a bit clearer than a regular expression as to what exactly `sanitize` does, especially since there is the limitation of the first character requirements.
But I don't mind swapping it out.
___
*[`pkg/cmd/roachprod-microbench/google/service.go` line 196 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104300#-NXu7B2UE7zwsC5NVFUJ:-NYS_4W7-Txl_u5TCIgZ:b-t05kpa) ([raw file](https://github.com/cockroachdb/cockroach/blob/923dd53e305b9b537be1a57a1e07bfc78076c47d/pkg/cmd/roachprod-microbench/google/service.go#L196)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Given that the return value of `maps.Keys` is non-deterministic, it doesn't make sense to use stable sorting.
</blockquote></details>

Good catch, this was a remnant of a previous local iteration, I'll change it to a more appropriate sort.
___
*[`pkg/cmd/roachprod-microbench/model/builder.go` line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104300#-NXtxjuQC0b0GONMt5ke:-NYS_Err1CUz7GWm5alU:bxshkgo) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fdd0d0dabea9e0e8f0f4940b80062b62441b3b0/pkg/cmd/roachprod-microbench/model/builder.go#L49)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

I could swear there was a linter that would force you to write `id, prefix string` but I guess not since CI is green. :thinking: 
</blockquote></details>

This one keeps getting me :) I'll update. I need that linter to start working!
___
*[`pkg/cmd/roachprod-microbench/model/builder.go` line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104300#-NXtyDvf3ZDqOTCbPRzn:-NYSkWfC2FwRe7jcYs8o:b-axhojg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fdd0d0dabea9e0e8f0f4940b80062b62441b3b0/pkg/cmd/roachprod-microbench/model/builder.go#L51)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Nit: `switch rec := reader.Result().(type)`?
</blockquote></details>

Good catch, updated.
___
*[`pkg/cmd/roachprod-microbench/model/builder.go` line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104300#-NXtySFF6BWRPrLkoQOo:-NYS_oiKAcc17yxKJK05:b-6lr186) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fdd0d0dabea9e0e8f0f4940b80062b62441b3b0/pkg/cmd/roachprod-microbench/model/builder.go#L53)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Is there a situation where this can legitimately happen? If so, worth adding a comment.
</blockquote></details>

I guess if the benchmark log was corrupted somehow this could happen, or if someone passes in a wrong log from the `cli`. I'll add a comment.
___
*[`pkg/cmd/roachprod-microbench/model/builder.go` line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104300#-NXu2J2p98iOOyhlThel:-NYSaGui-GM5M6w-DcTr:bmqd4iv) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fdd0d0dabea9e0e8f0f4940b80062b62441b3b0/pkg/cmd/roachprod-microbench/model/builder.go#L60)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

I now see why the `Values` field is a pointer to slice. This seems like a surprising API to me though, where callers change the underlying value of a struct field from the outside. How about having `entry.addValue(value.Value)` instead?
</blockquote></details>

Good point, this doesn't make sense. I'll improve the API here.
___
*[`pkg/cmd/roachprod-microbench/model/builder.go` line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104300#-NXu3bF3EI5FHAWqT6iA:-NYSaOaN73MwOs6m6M-M:b-vh4hxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fdd0d0dabea9e0e8f0f4940b80062b62441b3b0/pkg/cmd/roachprod-microbench/model/builder.go#L94)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

So passing an invalid benchmarkName is an expected situation?
</blockquote></details>

Not entirely, we're expecting at least one present out of the two runs, and thus this entry should technically always exist if queried with the information it was used to create this. Hence, this is a bit of an unnecessary safeguard. I might move the computations of all comparisons into a function to shield the API a bit more or update the func doc to reflect the behaviour. 
___
*[`pkg/cmd/roachprod-microbench/model/builder.go` line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104300#-NXu3m2rBw9qKPGCxODn:-NYSaoCDEilkfO9y20UW:b-x8vxlb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fdd0d0dabea9e0e8f0f4940b80062b62441b3b0/pkg/cmd/roachprod-microbench/model/builder.go#L99)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Is this dealing with the case where a benchmark was added or removed between the two runs? Worth spelling it out either way.
</blockquote></details>

Yes, I'll add a comment to the areas where we handle the case of a microbenchmark not being present in both runs.
___
*[`pkg/cmd/roachprod-microbench/model/builder.go` line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104300#-NXu4Bw_DBQdIwVGHm_p:-NYSfRZb63vbAjjOyGC_:b-3lqhoj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fdd0d0dabea9e0e8f0f4940b80062b62441b3b0/pkg/cmd/roachprod-microbench/model/builder.go#L111)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

It might be because I'm a noob, but I don't understand this formula, heh.
</blockquote></details>

Good you asked since there is a small mistake. It should be `* 100` not `/ 100`, Oops!
It's only used for sorting currently, so the division mistake didn't cause any bugs by chance.

As for the formula, it's to get the percentage of change between two values. The `minus 1` is a result of simplifying the equation `(new - old) / old`.
It's the same formula used here to calculate the delta: https://github.com/golang/perf/blob/master/benchmath/sample.go#L194.
___
*[`pkg/cmd/roachprod-microbench/model/metric.go` line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104300#-NXu1sn0B2fcw-BAIIrs:-NYSdHPG4lzf3IgbnKwB:bjo2cd5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fdd0d0dabea9e0e8f0f4940b80062b62441b3b0/pkg/cmd/roachprod-microbench/model/metric.go#L40)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Why do we need a pointer to slice?
</blockquote></details>

Noted the above argument, I'll update.

**Review by renatolabs — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104300#-:-NYYWewn8bdulH4GEsJU:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachprod-microbench/model/builder.go` line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104300#-NXtySFF6BWRPrLkoQOo:-NYYVHceE-l9q46AO6-y:b-osmwwv) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fdd0d0dabea9e0e8f0f4940b80062b62441b3b0/pkg/cmd/roachprod-microbench/model/builder.go#L53)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

I guess if the benchmark log was corrupted somehow this could happen, or if someone passes in a wrong log from the `cli`. I'll add a comment.
</blockquote></details>

Interestingly, it seems that the latest `benchfmt` (`20230427`) changed this API to `Next()` + `Err()` (an API similar to `bufio.Scanner`), avoiding the need to do a type switch in the loop [1]. Are we using this older version intentionally for some reason?

[1] https://pkg.go.dev/golang.org/x/perf/storage/benchfmt#Reader

**Comment by herkolategan** [comment]
TFTR!
bors r=renatolabs

**Pull request merged**
