### PR TITLE
storage: Turn load-based lease rebalancing on by default

### LINKED ISSUE #13232: storage: Keep leaseholders close to where their requests are coming from ("Leaseholders follow the sun")
This is a feature request explained by the last paragraph of the [motivation section of the leaseholder rebalancing RFC](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/leaseholder_rebalancing.md#motivation). Excerpt copied below:

```
The last goal is to place the leaseholder for a range near the gateway node that is accessing the range in order to minimize network RTT. As an obvious example: it is preferable for the leaseholder to be in the same datacenter as the gateway node. Note that there is usually more than one gateway node accessing a range and there will common workloads where the traffic from gateway nodes is not coming from a single locality making it impossible to satisfy this goal. In general, we'd like to minimize the aggregate RTT for accessing the range which makes the mixture of reads and writes important (reads only need a round-trip from the gateway to the leaseholder while writes need a round-trip to the leaseholder and from the leaseholder to a quorom of followers). Also, this goal is at odds with the second goal of distributing load throughout a cluster and we'll need to be careful with heuristics here. It may be beneficial to place the leaseholder in the same datacenter as the gateways accessing the range, but doing so can lower total throughput depending on the workload and if the latencies between datacenters are small.
```

### PR DESCRIPTION
**Pull request by a-robinson**
@BramGruneir 

Fixes #13232

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14268)

### CODE REVIEW

**Comment by tamird** [comment]
Do we want this in this week's beta?

**Comment by a-robinson** [comment]
That was the plan, yes.

**Comment by tamird** [comment]
Hm, OK. LGTM then.

**Comment by a-robinson** [comment]
@mberhault @bdarnell for confirmation, but my understanding is that enabling this was the plan.

**Comment by mberhault** [comment]
If we're satisfied that none of the issues encountered since enabling it are related, then sure.

**Review by bdarnell — APPROVED** [review]

**Comment by a-robinson** [comment]
I'll hold off on merging until we have some idea what's going on in #14250.

**Pull request merged**
