### PR TITLE
server: add httpAddress to node info payloads

### PR DESCRIPTION
**Pull request by dhartunian**
Currently, there's no easy way to access all the HTTP ports in the cluster.
Customers must either know the address and port ahead of time or do some
legwork to figure it out when they need to access the Admin UI on a specific
node.

This work will make it easier to expose links to each node's UI from every
other node in the cluster.

An `http_address/HTTPAddress` field is added to the `DetailsReponse` which
is part of the `NodeStatus` payload in `status.proto`. This data is sent to the
Admin UI which will now be able to link to each node's instance of the UI
server.

An `http_address/HTTPAddress` field is added to the `NodeDescriptor` payload
in `metadata.proto`. This information is used to gossip information between
nodes and will allow every node to report on the cluster's HTTP endpoints.

Generally, I followed the existing pattern of the `sql_address/SQLAddress`
field when adding this functionality.

This work is part of #31564.
A separate UI PR #44544 will add this information the Admin UI.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
This has been discussed before (IIRC there may even be a PR open already - #39483 if I'm not mistaken)

The main issue with this, together with #39942, is that we don't have a full story yet about what it means to have an "advertised address". In contrast to the node-to-node "advertised address" (for RPC) which gets tested/verified by heartbeats, there is no guardrail against misconfiguring the advertised http addr.

Moreover, the default value for the field is the private address of the node, whereas it's likely in most deployments that there will be a separate public ip address. Mandating a custom opt-in extra config (adding the `--http-advertise-addr` which is not default) to get sane/useful UX runs counter to "make data easy".

What do you think about this?

I am not fundamentally opposed to letting this PR go through, but we need clear answers to the point above. Then, once we have these answers, it's probably time to revive #39483 and perhaps #39942 to provide uniform UX.

**Comment by dhartunian** [comment]
> Mandating a custom opt-in extra config (adding the --http-advertise-addr which is not default) to get sane/useful UX runs counter to "make data easy".

I agree with this 👍. 

Thanks for detailed context @knz! Appreciate it. I will discuss with @piyush-singh and see what we want to do here.

**Comment by dhartunian** [comment]
After discussion with @piyush-singh we've decided to move forward with this as-is because this functionality is targeting internal users more than database customers.

Solving the more generic node-linking problem is difficult but this functionality would have an immediate benefit for those interacting with roachprod-deployed clusters.

Let me know what you think @knz.

**Comment by knz** [comment]
I'm ok with that thanks for the heads up. I'll review when I get back on Monday.
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Pull request closed without merging**
