### PR TITLE
go.mod: bump Pebble to fffe02a195e3

### PR DESCRIPTION
**Pull request by raggar**
fffe02a1 db: simplify ScanInternal()
df7e2ae1 vfs: deflake TestDiskHealthChecking_Filesystem ff5c929a Rate Limit Scan Statistics
af8c5f27 internal/cache: mark panic messages as redaction-safe

Epic: none
Release note: none

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108370#-:-NbLArG30XzbBLZ6UGN9:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by itsbilal** [comment]
#108369 is already open 😛 but you can go ahead with this one instead

**Comment by RahulAggarwal1016** [comment]
> https://github.com/cockroachdb/cockroach/pull/108369 is already open 😛 but you can go ahead with this one instead

oh mb didn't see that, yeah I'll just go ahead with this one

**Comment by RahulAggarwal1016** [comment]
bors retry

**Comment by RahulAggarwal1016** [comment]
bors retry

**Pull request merged**
