### PR TITLE
sql/sem/tree: run TestEval with vectorize=experimental_on

### LINKED ISSUE #40635: exec: run all logic/eval tests that support vectorized with the vectorized engine
Some of these might be on already. Make sure they actually use the vectorized engine (e.g., turning the setting on isn't enough, the query must pass the estimated row count threshold too).

### PR DESCRIPTION
**Pull request by asubiotto**
Release note: None

Release justification: Category 1 non-production code change to increase
test coverage of the vectorized execution engine.

Close #40635

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
nice! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40790#-:-Lovgn-20QNq43MRu6l-:b-n0svi7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

**Review by jordanlewis — COMMENTED** [review]
This looks good, but unfortunately I'm fairly convinced (maybe 70% confident?) that this doesn't add much or any coverage to the vectorized engine. The reason is that all of the tests use constants only, but none of the vectorized engine's operators can operate on only constants - we just didn't make operators for those.

For example, if you had an eval test that said:

```
eval
2+2
----
4
```

This would attempt to make a query like `select 2+2`, I think. Since the tests explicitly disable constant folding, this will make a renderNode with the scalar expression 2+2, which will then... hm, I guess I don't know what it would do. Maybe it would actually work in the end - would we plan two "Datum" operators and add them all?

@asubiotto could you please check to see if any vectorized plans actually get created from the eval tests?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40790#-:-Lovi5ZW1px98wpGKADf:bylzrkw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

**Review by rafiss — COMMENTED** [review]
In #40674 I noticed that adding two constant integers ended up being done in a `projPlusInt64ConstInt64Op` (there was one batch where every row just had a constant value), but I stopped working on that for now so I didn't figure out why. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40790#-:-LovoDy_59dzVX4Jyd1l:bvlyc5u)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by jordanlewis — COMMENTED** [review]
Oh cool! Well in that case I guess I have no objections here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40790#-:-LovwDlI7XviRBEUMIZQ:b-x9csc0)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by asubiotto** [comment]
OK, I think I was a bit naive in assuming this would just work. I did a little more investigation to ensure this runs through the vectorized engine. The current integration test works by issuing the expression through `QueryRow` and comparing that result to the expected result. This does do constant folding (I got confused with a comment about constant folding that just serves to resolve the type of the `QueryRow` result). Therefore, enabling vectorized execution doesn't add any test coverage.

I'll think of something and update the PR accordingly.

**Comment by asubiotto** [comment]
Updated to explicitly create a `NewColOperator` with the unmodified expression as the post process spec. The test currently fails with an interface conversion error which I have yet to investigate.

**Comment by asubiotto** [comment]
Investigated the failing test but unsure how to fix this properly. The failing test is:
```
        --- FAIL: TestEval/vectorized/bit_array (0.00s)
            eval_test.go:53:
                testdata/eval/bit_array:176: B'11111111111111111111111110000101'::int4
                expected:
                -123

                found:
                unexpected error from the vectorized runtime: interface conversion: coldata.column is []int64, not []int32
```
This is caused because we type check the expression (which returns `int32`) to create the materializer, but the expression result comes back as an `int64`. What seems to happen here is that type information is getting lost when calling `helper.Init` in `NewColOperator`. The expression helper correctly type checks the expression type to an `int32` here: 
https://github.com/cockroachdb/cockroach/blob/4abcf22f7e24bb977f86e1bd7550045dfbdb4e01/pkg/sql/execinfra/expr.go#L75
But then returns the constant result (`-123`) cast to a `tree.TypedExpr`:
https://github.com/cockroachdb/cockroach/blob/4abcf22f7e24bb977f86e1bd7550045dfbdb4e01/pkg/sql/execinfra/expr.go#L92
The vectorized flow creator then calls `ResolvedType()` on this expression, which returns an `int64`:
https://github.com/cockroachdb/cockroach/blob/4abcf22f7e24bb977f86e1bd7550045dfbdb4e01/pkg/sql/colexec/execplan.go#L1041
The root cause seems to be that we don't retain proper type information in `processExpression` because of the call to `WalkExpr` with a `TypedExpr` then cast to a `TypedExpr`:
https://github.com/cockroachdb/cockroach/blob/4abcf22f7e24bb977f86e1bd7550045dfbdb4e01/pkg/sql/execinfra/expr.go#L81-L92
@solongordon, could you advise on the best way to fix this?

**Comment by asubiotto** [comment]
Skipped that test as it is a limitation of our type system that the width gets lost when evaluating an expression. RFAL.

**Comment by asubiotto** [comment]
Friendly ping

**Review by jordanlewis — APPROVED** [review]
LGTM! This is pretty cool.

**Comment by asubiotto** [comment]
TFTR

bors r=jordanlewis,rafiss

**Pull request merged**
