### PR TITLE
builtins: hide crdb_internal.probe_ranges from docs

### LINKED ISSUE #84758: Fix style of crdb_internal.probe_ranges generated function documentation
**Describe the problem**

The definition for `crdb_internal.probe_ranges` added in https://github.com/cockroachdb/cockroach/pull/79546/ should follow the documentation style (that is, a 1 line definition) used by other functions.  This does not conform to the style of the other definitions:

https://www.cockroachlabs.com/docs/stable/functions-and-operators.html#tuple-int-as-range_id-string-as-error-int-as-end_to_end_latency_ms-string-as-verbose_trace-functions

The heading over the table should not include the function signature, but should be TUPLE Functions.

If more detailed documentation is required it should be added in a separate documentation page, not the function reference.

Jira issue: CRDB-17848

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/84758

Release note: None

Release justification: docs only change

### CODE REVIEW

**Comment by rafiss** [comment]
i will backport to 21.2 if https://github.com/cockroachdb/cockroach/pull/84292 gets merged

**Review by Santamaura — APPROVED** [review]
:lgtm: once CI passes

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87318#-:-NBNsr3i-uMRzUPEO-MD:bay28y1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

**Review by e-mbrown — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87318)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rafiss)

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
