### PR TITLE
copysets: remove

### PR DESCRIPTION
**Pull request by tbg**
This is dead code.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
👋

**Comment by tbg** [comment]
bors r=nvanbenschoten

**Comment by tbg** [comment]
Segmentation fault (core dumped) in make lint 🤷‍♂ 

bors r=nvanbenschoten

**Comment by tbg** [comment]
bors r=nvanbenschoten

acceptance/bank/cluster-recovery hung weirdly, nothing interesting in the logs
Feels like I've seen this before. Going to take a look next week.

**Pull request merged**
