### PR TITLE
Skip new group of flaky tests

### PR DESCRIPTION
**Pull request by fantapop**
Refs: #86763

Reason: flaky test

Release justification: non-production code changes

Release note: None

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]

**Comment by gh-casper** [comment]
It will probably hit this error: https://github.com/cockroachdb/cockroach/issues/86640. If so, please skip it as well. I have a fix for that https://github.com/cockroachdb/cockroach/pull/86769 but merging it depends on this one.

**Comment by fantapop** [comment]
@gh-casper I'm going to close this one since tests it was skipping are now green

**Pull request closed without merging**
