### PR TITLE
opt: disallow using inverted joins with semi- and anti-joins

### PR DESCRIPTION
**Pull request by rytaft**
Prior to this commit, using a semi- or anti-join with a geospatial join
condition caused an internal error. This was because the inverted join
produced false positives that needed to be removed with a geospatial
function call, but the relevant columns were no longer available after
the semi/anti join.

In the future we may consider adding support for using inverted joins
with semi- and anti-joins by converting the inverted join to use an
inner/left join. In this case, we will need to wrap it with a `DISTINCT
ON` the key of the left side, and project away the unneeded columns.

Informs #48223

Release note (bug fix): Fixed an internal error that could occur when
using an index-accelerated geospatial function inside an EXISTS or
NOT EXISTS correlated subquery.

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52942#-:-MF0nkxr-H2zcg7Hdebm:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Comment by rytaft** [comment]
TFTR!

bors r+

**Pull request merged**
