### PR TITLE
sql: adjust more tests to work with the test tenant

### PR DESCRIPTION
**Pull request by yuzefovich**
Informs: #76378.
Epic: CRDB-18499.

### CODE REVIEW

**Comment by yuzefovich** [comment]
This should be green, RFAL.

**Review by knz — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 5 of 5 files at r2, 29 of 59 files at r6, 4 of 5 files at r7, 26 of 26 files at r8, 9 of 9 files at r9, 21 of 21 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107228)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna and @yuzefovich)

___
*[`pkg/sql/backfill_num_ranges_in_span_test.go` line 91 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/107228#-N_touGy6LwHwTF_muUV:-N_touGy6LwHwTF_muUW:bqipvvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f0268eea2d624225da51b1e5119ad537a46e215/pkg/sql/backfill_num_ranges_in_span_test.go#L91)):*
> ```Go
> 		// "scratch" part of the key space, which is outside of test tenant's
> 		// boundaries.
> 		DefaultTestTenant: base.TestIsSpecificToStorageLayerAndNeedsASystemTenant,
> ```

We need to extend this test to work on secondary tenants too. Is there a way to add a tenant prefix to those KV writes?

Otherwise file an issue and link it here.
___
*[`pkg/sql/multitenant_admin_function_test.go` line 256 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/107228#-N_tpcDz51CnVthpvS4O:-N_tpcDz51CnVthpvS4P:b-5ljnny) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca4c671692450b4a0f71c168cc6c75a1e3e0f501/pkg/sql/multitenant_admin_function_test.go#L256)):*
> ```Go
> 	systemDB := serverutils.OpenDBConn(
> 		t,
> 		testServer.ServingSQLAddr(),
> ```

how did this even work before?... :facepalm:

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107228#-:-N_tu0Mo1JVkXKOhGC1s:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @stevendanna)

___
*[`pkg/sql/backfill_num_ranges_in_span_test.go` line 91 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/107228#-N_touGy6LwHwTF_muUV:-N_trZQ48xBbAAQMBi_Q:b1h7i7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f0268eea2d624225da51b1e5119ad537a46e215/pkg/sql/backfill_num_ranges_in_span_test.go#L91)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

We need to extend this test to work on secondary tenants too. Is there a way to add a tenant prefix to those KV writes?

Otherwise file an issue and link it here.
</blockquote></details>

The difficulty is that the test uses `ScratchRange` which uses key space between `TableDataMax` and `TenantPrefix`. It seems that we'll need to think through whether we can carve out such a scratch space within tenant key space. I filled an issue for now.
___
*[`pkg/sql/multitenant_admin_function_test.go` line 256 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/107228#-N_tpcDz51CnVthpvS4O:-N_ttWl30psji9fq2Fhj:b-dilryn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca4c671692450b4a0f71c168cc6c75a1e3e0f501/pkg/sql/multitenant_admin_function_test.go#L256)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

how did this even work before?... :facepalm: 
</blockquote></details>

`ccl` license wasn't enabled, so it didn't :/

**Comment by yuzefovich** [comment]
Seems like a flake.

bors r+

**Pull request merged**
