### PR TITLE
changefeedccl: add changefeed range distribution strategies

### PR DESCRIPTION
**Pull request by jayshrivastava**
### changefeedccl: add changefeed range distribution strategies 

This commit introduces several changes.

It makes `replicaoracle.BinPackingChoice` the explicit default for changefeeds.
Previously, we would use `physicalplan.DefaultReplicaChooser`, which would point
to the bin packing oracle. This change is better since it gives the changefeed package more control over its dependencies.

A new cluster setting `changefeed.default_range_distribution_strategy` is added to
 specify how changefeeds should distribute work. In the default case,
`none`, we defer to distsql to select nodes and distribute work among them. This
is the same behavior as running a changefeed today.

In the other case, `balanced_simple`, we still let distsql choose nodes for us, but we attempt
to evently distribute ranges over them. This case is exactly the same as setting
`changefeed.balance_range_distribution.enable = true`, but it is allowed to be used
outside of initial scans (`changefeed.balance_range_distribution.enable` was only allowed
with `initial_scan=only`.

This change also deprecates `changefeed.balance_range_distribution.enable` in favor of
`changefeed.default_range_distribution_strategy` because the latter can be expanded
in the future to add more functionality.

This change also moves changefeed distribution tests to a dedicated file:
`changefeed_dist_test.go`. This file contains a tester which can be used to
start a cluster with a given topology and range distribution. Changefeed tests
can use the tester to perform various load balancing strategies. Right now, the new
tests assert how ranges are distributed after planning changefeeds, which implicitly tests
code outside of the changefeedccl package (ie. `dsp.PartitionSpans()`). However,
this is important since changefeeds rely on the behavior of this black box to perform well.
In the future, cdc will implement more distribution strategies and likely implement its
own partitioning logic. Tests for these strategies can be added in this file. Over time,
cdc can move away from distsql planning.

Informs: https://github.com/cockroachdb/cockroach/issues/113898
Epic: None

Release note (enterprise change): `changefeed.balance_range_distribution.enable` is now deprecated.
Users should use a new cluster setting `changefeed.default_range_distribution_strategy`
instead. `changefeed.default_range_distribution_strategy='balanced_simple'` has the same
effect as setting `changefeed.balance_range_distribution.enable=true`. It does not require
`initial_scan='only'`, which was required by the old setting.

### roachtest/cdc: metamorphically determine range distribution strategy

This change adds a new metamorphic flag in cdc roachtests which choses
a distribution strategy randomly.

Release note: None

### CODE REVIEW

**Review by miretskiy — COMMENTED** [review]
> Reviewed 6 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115166)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @jayshrivastava, @michae2, and @srosenberg)

___
*[`pkg/ccl/changefeedccl/changefeed_dist.go` line 328 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115166#-NkRx91K3of6hsfk0CIb:-NkRx91K3of6hsfk0CIc:b-jzfeuw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1571d7fa352dfc232f676cda753323b33ccc2d4/pkg/ccl/changefeedccl/changefeed_dist.go#L328)):*
> ```Go
> 	// set of nodes to distribute work to. However, changefeeds will try to
> 	// distribute work evenly across this set of nodes.
> 	DISTRIBUTION_STRATEGY_BALANCED_SIMPLE
> ```

it's a bit more idiomatic to have `type rangeDistributionStrategy int`
and then define distributionBlah constants.
(All caps is only used in proto enums, afaik)
___
*[`pkg/ccl/changefeedccl/changefeed_dist.go` line 341 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115166#-NkRxHz9CqJxNkFjV1O_:-NkRxHz9CqJxNkFjV1Oa:bfu0kaq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1571d7fa352dfc232f676cda753323b33ccc2d4/pkg/ccl/changefeedccl/changefeed_dist.go#L341)):*
> ```Go
> 	"none",
> 	map[int64]string{
> 		int64(DISTRIBUTION_STRATEGY_NONE):            "none",
> ```

maybe better name would be just "default" -- none reads like "no distribution at all".
___
*[`pkg/ccl/changefeedccl/changefeed_dist.go` line 333 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115166#-NkpeETZEhzIzw9cyyGN:-NkpeETZEhzIzw9cyyGO:b-ied3ep) ([raw file](https://github.com/cockroachdb/cockroach/blob/861c9e858ec55ef03e6cea3f07c50b695aa7d431/pkg/ccl/changefeedccl/changefeed_dist.go#L333)):*
> ```Go
> )
> 
> var rangeDistributionStrategy = settings.RegisterEnumSetting(
> ```

// Let's add a todo to deprecate this setting in favor of explicit option.
___
*[`pkg/ccl/changefeedccl/changefeed_dist.go` line 406 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115166#-NkpgCCl9BiKDY97BTd7:-NkpgCCl9BiKDY97BTd8:b-tbwh9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/861c9e858ec55ef03e6cea3f07c50b695aa7d431/pkg/ccl/changefeedccl/changefeed_dist.go#L406)):*
> ```Go
> 		}
> 
> 		if knobs, ok := maybeCfKnobs.(*TestingKnobs); ok && knobs != nil &&
> ```

why not (.TestingKnobs) abouve (maybeCfKnobs initialization)?

**Review by jayshrivastava — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115166)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @michae2, @miretskiy, and @srosenberg)

___
*[`pkg/ccl/changefeedccl/changefeed_dist.go` line 328 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115166#-NkRx91K3of6hsfk0CIb:-NlTwsV6269sgm0fFk3P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1571d7fa352dfc232f676cda753323b33ccc2d4/pkg/ccl/changefeedccl/changefeed_dist.go#L328)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

it's a bit more idiomatic to have `type rangeDistributionStrategy int`
and then define distributionBlah constants.
(All caps is only used in proto enums, afaik)
</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/changefeed_dist.go` line 341 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115166#-NkRxHz9CqJxNkFjV1O_:-NlTwuZG3OAZIYK6ODP7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1571d7fa352dfc232f676cda753323b33ccc2d4/pkg/ccl/changefeedccl/changefeed_dist.go#L341)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

maybe better name would be just "default" -- none reads like "no distribution at all".
</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/changefeed_dist.go` line 333 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115166#-NkpeETZEhzIzw9cyyGN:-NlTwsjjD_-lfAoC7-q3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/861c9e858ec55ef03e6cea3f07c50b695aa7d431/pkg/ccl/changefeedccl/changefeed_dist.go#L333)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

// Let's add a todo to deprecate this setting in favor of explicit option.
</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/changefeed_dist.go` line 406 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115166#-NkpgCCl9BiKDY97BTd7:-NlTwvCQ2l_ziTiWR4ap:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/861c9e858ec55ef03e6cea3f07c50b695aa7d431/pkg/ccl/changefeedccl/changefeed_dist.go#L406)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

why not (.TestingKnobs) abouve (maybeCfKnobs initialization)?
</blockquote></details>

Done.

**Review by miretskiy — COMMENTED** [review]
> Reviewed 2 of 10 files at r1, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115166)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @jayshrivastava, @michae2, and @srosenberg)

___
*[`pkg/ccl/changefeedccl/changefeed_dist.go` line 394 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/115166#-NlUG0kSCSD6nGn-Vj25:-NlUG0kSCSD6nGn-Vj26:ba77qzg) ([raw file](https://github.com/cockroachdb/cockroach/blob/63121a7d7f10c198b942a9a0ddf89bde190f722a/pkg/ccl/changefeedccl/changefeed_dist.go#L394)):*
> ```Go
> 			planCtx = dsp.NewPlanningCtxWithOracle(ctx, execCtx.ExtendedEvalContext(), nil, /* planner */
> 				blankTxn, sql.DistributionType(distMode), oracle, locFilter)
> 			spanPartitions, err = dsp.PartitionSpans(ctx, planCtx, trackedSpans)
> ```

unless I'm misreading, looks like planCtx construction and dsp.PartitionSpans calls are identical between
this and the above case.  Does it make sense to pull it out?  Construct planCtx, and get the spans regardless of the rangeDistribution; and then just do rebalancing bit?
___
*[`pkg/ccl/changefeedccl/changefeed_dist.go` line 407 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/115166#-NlUB3c-AInVYVMp6W7T:-NlUB3c08jrmBjRy3JJt:b-z6su2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/63121a7d7f10c198b942a9a0ddf89bde190f722a/pkg/ccl/changefeedccl/changefeed_dist.go#L407)):*
> ```Go
> 			}
> 		default:
> 			return nil, nil, errors.AssertionFailedf("could not reconcile dist strategy %d and dist mode %d",
> ```

nit: not sure about reconcile part... perhaps just return "unsupported distribution strategy XXX"
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 641 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/115166#-NlUGOyA6rApXDKLv43f:-NlUGOyA6rApXDKLv43g:b-ppxmt1) ([raw file](https://github.com/cockroachdb/cockroach/blob/63121a7d7f10c198b942a9a0ddf89bde190f722a/pkg/cmd/roachtest/tests/cdc.go#L641)):*
> ```Go
> 	settings.ClusterSettings["changefeed.slow_span_log_threshold"] = "30s"
> 	settings.ClusterSettings["server.child_metrics.enabled"] = "true"
> 	settings.ClusterSettings["changefeed.range_distribution_strategy"] = "balanced_simple"
> ```

do you want to add some metamorphic goodness, add cdcFeatureFlags and change  the strategy in the applySettings function instead ?
___
*[`pkg/ccl/changefeedccl/changefeed_dist_test.go` line 94 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/115166#-NlUH-ae91g2O_0AWqKV:-NlUH-ae91g2O_0AWqKW:b-gzp6sq) ([raw file](https://github.com/cockroachdb/cockroach/blob/63121a7d7f10c198b942a9a0ddf89bde190f722a/pkg/ccl/changefeedccl/changefeed_dist_test.go#L94)):*
> ```Go
> 			input: partitions(
> 				mkPart(1, mkSpan("a", "c"), mkSpan("e", "p"), mkSpan("r", "z")),
> 				mkPart(2),
> ```

I'm not even sure sql planning could return a span partition w/out spans.
I'm actually not sure it can ; and thus this test case is probably unrealistic.
When you implement "balance_full" mode and you get "all nodes", then I think this would make sense.

It's probably okay to keep this test case -- but I just want to point out potential issue.
(And... I realize it's a code move)
___
*[`pkg/ccl/changefeedccl/changefeed_dist_test.go` line 108 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/115166#-NlUI3AL6tsab0ltRWK9:-NlUI3AL6tsab0ltRWKA:bw7hn0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/63121a7d7f10c198b942a9a0ddf89bde190f722a/pkg/ccl/changefeedccl/changefeed_dist_test.go#L108)):*
> ```Go
> 				mkPart(3, mkSpan("c", "e"), mkSpan("p", "r")),
> 			),
> 		},
> ```

I realize this is a code move fromt he previous test, but... no good deed goes unpunished.
Would love to see more test cases.  

Quick snippet to generate span consisting of a single letter:
```
for r := 'A'; r <= 'Z'\-1; r++ {  
  var sp roachpb.Span  
  sp.Key = append(sp.Key, byte(r))  
  sp.EndKey = append(sp.EndKey, byte(r+1))
  ...
```

So, perhaps test cases such as:
   * bunch of ranges on a single node (say A-B, B-C, ... W-X), each letter), and like 1 on the other nodes.
   * A test case with just 1 node.  Basically, idempotency test.
   * A test case with 5 nodes.
   * A test case with ... like 25 nodes -- all nodes having 1 range (you'll need a helper to generate that).
   * Perhaps a 25 node test, but with imbalance.
   * A test case where the span list is not sorted alphabetically (I know that sql will return sorted spans; but I want to make sure we don't depend on that).
___
*[`pkg/ccl/changefeedccl/changefeed_dist_test.go` line 150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/115166#-NlUKS1VA2Igql4ECdqk:-NlUKS1VA2Igql4ECdql:b7a2tzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/63121a7d7f10c198b942a9a0ddf89bde190f722a/pkg/ccl/changefeedccl/changefeed_dist_test.go#L150)):*
> ```Go
> // nodes using the supplied localities. It creates a table 'x' with 64 ranges
> // and distributes the leaseholders across the first 6 nodes using an
> // exponential distribution.
> ```

can you specify what "exponential" distribution means here (I guess I'm just
looking for explicit "[]int{2, 2, 4, 8, 16, 32, 0, 0})"  counts.
___
*[`pkg/ccl/changefeedccl/changefeed_dist_test.go` line 230 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/115166#-NlUKAp29u8HpN4zazZY:-NlUKAp29u8HpN4zazZZ:br7uxpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/63121a7d7f10c198b942a9a0ddf89bde190f722a/pkg/ccl/changefeedccl/changefeed_dist_test.go#L230)):*
> ```Go
> 
> // countRanges returns an array where each index i stores the ranges assigned to node i.
> func (rdt *rangeDistributionTester) countRanges(partitions []sql.SpanPartition) []int {
> ```

nit: countNodeRanges? Or countRangesPerNode?
___
*[`pkg/ccl/changefeedccl/changefeed_dist_test.go` line 258 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/115166#-NlUM-Qp4X8uHXNv0gJQ:-NlUM-Qp4X8uHXNv0gJR:batb9zt) ([raw file](https://github.com/cockroachdb/cockroach/blob/63121a7d7f10c198b942a9a0ddf89bde190f722a/pkg/ccl/changefeedccl/changefeed_dist_test.go#L258)):*
> ```Go
> }
> 
> func TestChangefeedDistributionStrategy(t *testing.T) {
> ```

this is so nice!

**Review by jayshrivastava — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115166)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @michae2, @miretskiy, and @srosenberg)

___
*[`pkg/ccl/changefeedccl/changefeed_dist.go` line 394 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/115166#-NlUG0kSCSD6nGn-Vj25:-NlUVgzxDwXbjvOQwS4j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/63121a7d7f10c198b942a9a0ddf89bde190f722a/pkg/ccl/changefeedccl/changefeed_dist.go#L394)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

unless I'm misreading, looks like planCtx construction and dsp.PartitionSpans calls are identical between
this and the above case.  Does it make sense to pull it out?  Construct planCtx, and get the spans regardless of the rangeDistribution; and then just do rebalancing bit?
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 641 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/115166#-NlUGOyA6rApXDKLv43f:-NlUVi1t3tDDcFnwp8WX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/63121a7d7f10c198b942a9a0ddf89bde190f722a/pkg/cmd/roachtest/tests/cdc.go#L641)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

do you want to add some metamorphic goodness, add cdcFeatureFlags and change  the strategy in the applySettings function instead ?
</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/changefeed_dist_test.go` line 94 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/115166#-NlUH-ae91g2O_0AWqKV:-NlV9UwD6Hi8HnrCOQRr:b-vhkrhk) ([raw file](https://github.com/cockroachdb/cockroach/blob/63121a7d7f10c198b942a9a0ddf89bde190f722a/pkg/ccl/changefeedccl/changefeed_dist_test.go#L94)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I'm not even sure sql planning could return a span partition w/out spans.
I'm actually not sure it can ; and thus this test case is probably unrealistic.
When you implement "balance_full" mode and you get "all nodes", then I think this would make sense.

It's probably okay to keep this test case -- but I just want to point out potential issue.
(And... I realize it's a code move)
</blockquote></details>

I'll keep it here :) 
___
*[`pkg/ccl/changefeedccl/changefeed_dist_test.go` line 108 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/115166#-NlUI3AL6tsab0ltRWK9:-NlV9WZh7eGEJI4QDMrD:b19emj8) ([raw file](https://github.com/cockroachdb/cockroach/blob/63121a7d7f10c198b942a9a0ddf89bde190f722a/pkg/ccl/changefeedccl/changefeed_dist_test.go#L108)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I realize this is a code move fromt he previous test, but... no good deed goes unpunished.
Would love to see more test cases.  

Quick snippet to generate span consisting of a single letter:
```
for r := 'A'; r <= 'Z'\-1; r++ {  
  var sp roachpb.Span  
  sp.Key = append(sp.Key, byte(r))  
  sp.EndKey = append(sp.EndKey, byte(r+1))
  ...
```

So, perhaps test cases such as:
   * bunch of ranges on a single node (say A-B, B-C, ... W-X), each letter), and like 1 on the other nodes.
   * A test case with just 1 node.  Basically, idempotency test.
   * A test case with 5 nodes.
   * A test case with ... like 25 nodes -- all nodes having 1 range (you'll need a helper to generate that).
   * Perhaps a 25 node test, but with imbalance.
   * A test case where the span list is not sorted alphabetically (I know that sql will return sorted spans; but I want to make sure we don't depend on that).
</blockquote></details>

Done. Added these cases!
___
*[`pkg/ccl/changefeedccl/changefeed_dist_test.go` line 150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/115166#-NlUKS1VA2Igql4ECdqk:-NlUVjHP-0iFkJJTlvuz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/63121a7d7f10c198b942a9a0ddf89bde190f722a/pkg/ccl/changefeedccl/changefeed_dist_test.go#L150)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

can you specify what "exponential" distribution means here (I guess I'm just
looking for explicit "[]int{2, 2, 4, 8, 16, 32, 0, 0})"  counts.
</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/changefeed_dist_test.go` line 258 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/115166#-NlUM-Qp4X8uHXNv0gJQ:-NlUVjtJD5mzEaIqS3zY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/63121a7d7f10c198b942a9a0ddf89bde190f722a/pkg/ccl/changefeedccl/changefeed_dist_test.go#L258)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

this is so nice!
</blockquote></details>

Done.

**Review by miretskiy — APPROVED** [review]
> Reviewed 2 of 5 files at r4, 1 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115166)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @michae2, and @srosenberg)

**Pull request merged**
