### PR TITLE
cli: Added the cli commands `exit` and `quit` to quit the cli.

### LINKED ISSUE #31878: cli/sql: Add the cli commands `exit` and `quit` to quit the cli.
With the release of postgres 11, they've finally added the ability to quit the cli with the new keywords `exit` and `quit`.

We should do the same.

see: https://www.postgresql.org/about/news/1894/

> The inclusion of the keywords "quit" and "exit" in the PostgreSQL command-line interface to help make it easier to leave the command-line tool

### PR DESCRIPTION
**Pull request by M-srivatsa**
Fixes #31878.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Hello, and thank you for your contribution!

This is very good, also very useful. 

1) Any chance you could add a test for this alongside the others in `pkg/cli/interactive_tests/test_local_cmds.tcl`?

2) Please extend the commit message with a release note, as explained in the contributor guide and the comment that pops up when you run `git commit`. Use `git log` to see examples of past release notes.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31915#-:-LPkncHo5WuIqhrdBf3B:b-pc5t7h)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/sql.go, line 196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31915#-LPknO3l0gEns9fP0lRe:-LPknO3m1KKhm1x6PfbO:bi7y32z) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d6a9ef66885eafbb9db32c1be32d0eb3e29d30a/pkg/cli/sql.go#L196)):*
> ```Go
> 	fmt.Printf(`You are using 'cockroach sql', CockroachDB's lightweight SQL client.
> Type:
>   "\q" or "quit" or "exit" to exit        (Ctrl+C/Ctrl+D also supported)
> ```

Change this to:

```
\q, quit, exit       exit the shell (Ctrl+C/Ctrl+D also supported)
```
___
*[pkg/cli/sql.go, line 980 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31915#-LPknXq35LgI-uEe3SOn:-LPknXq35LgI-uEe3SOo:b30qm94) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d6a9ef66885eafbb9db32c1be32d0eb3e29d30a/pkg/cli/sql.go#L980)):*
> ```Go
> 
> func (c *cliState) doHandleCliCmd(loopState, nextState cliStateEnum) cliStateEnum {
> ```

nit: we usually do not place an empty line at the beginning of function bodies.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31915)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/sql.go, line 980 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31915#-LPknXq35LgI-uEe3SOn:-LPkoc36092pAUvbGWan:b7jd7v8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d6a9ef66885eafbb9db32c1be32d0eb3e29d30a/pkg/cli/sql.go#L980)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: we usually do not place an empty line at the beginning of function bodies.
</blockquote></details>

Please also add a period at the end of the sentence in the comment.

Also please run `gofmt` on your sources upon save in your text editor.

**Comment by M-srivatsa** [comment]
hey can you help me resolve the linting error in am facing while running 'make lintshort'

attrached the error log

[error.log](https://github.com/cockroachdb/cockroach/files/2521476/error.log)

**Comment by M-srivatsa** [comment]
Changes made & added test's.
Please check it out

**Review by knz — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31915)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
