### PR TITLE
storage/tscache: move TimestampCache to its own package

### PR DESCRIPTION
**Pull request by nvb**
Part of #18779.

This change is broken into a series of small steps for reviewability. It moves the
`TimestampCache` into its own package, performs some cleanup, consolidates
the structure's external facing API, and pulls the structure behind an interface.
All of these code changes, along with some improved documentation, should 
help the `TimestampCache` (now `tscache.Cache`) stand on its own.

This refactoring (and specifically the new `Cache` interface) is also the first step
towards creating an implementation of the `TimestampCache` in C++ (see #16796).

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm_strong: 

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19301#-:-KwgPsuDkuUUYoE_qnVv:b-uwkowd)*

**Comment by petermattis** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/tscache/cache.go, line 69 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/19301#-KwguiVBZVT9EWujKANL:-KwguiVBZVT9EWujKANM:b-5lcoiy) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b3c84875a9fa317ab9de77fca531f7c1a7eaa93/pkg/storage/tscache/cache.go#L69)):*
> ```Go
> 	GetMaxWrite(start, end roachpb.Key) (hlc.Timestamp, uuid.UUID, bool)
> 
> 	// The following methods are used for testing within this package:
> ```

Feels weird that you'd need to add these to the interface. Can't you test directly against `cacheImpl` in order to get access to these methods?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19301)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/tscache/cache.go, line 69 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/19301#-KwguiVBZVT9EWujKANL:-Kwh5hx0FYQov7LZ0pWA:bngii5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b3c84875a9fa317ab9de77fca531f7c1a7eaa93/pkg/storage/tscache/cache.go#L69)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Feels weird that you'd need to add these to the interface. Can't you test directly against `cacheImpl` in order to get access to these methods?
</blockquote></details>

I split the tests up into `cache_test.go` and `cache_impl_test.go`. The former is testing the external interface of each `Cache` implementation (only one at the moment) while the latter is testing `cacheImpl` implementation details. The idea here was that all tests in `cache_test.go` should pass regardless of the `Cache` implementation used. 

I found that these methods were still pretty useful even in testing the external interface of `Cache`. Since they're pretty general and not related to the implementation of the interface, I figured they could be unexported but added to the interface. I may reconsider each one when we add another `Cache` implementation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19301)*

**Comment by tschottdorf** [comment]
Haven't had a chance to review just yet but I'm curious, are we landing refactors now?

**Comment by bdarnell** [comment]
Yeah, I think we can start landing refactors now.

**Comment by tschottdorf** [comment]
Nice!  :lgtm_strong: and pleasure to review, thanks for splitting up the commits.

---

Reviewed 10 of 12 files at r1, 2 of 3 files at r2, 6 of 8 files at r3, 3 of 5 files at r4, 4 of 6 files at r5, 5 of 7 files at r6, 4 of 4 files at r7.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19301#-:-Kwk52Y1S-ZXANYcXVrf:bllu0t0)*

**Pull request merged**
