### PR TITLE
testutils/reduce: improvements

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Comment by mjibson** [comment]
ping @justinj (I can also ask someone else if you don't have time)

**Review by justinj — APPROVED** [review]
:lgtm_strong: sorry this took so long!

> Reviewed 1 of 1 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39344#-:-LmGEcdp6b4fctGGrZ52:bjo1pi6)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
