### PR TITLE
sql: change Acquire() to acquire a lease on the latest version

### PR DESCRIPTION
**Pull request by vivekmenezes**
This PR is only for the last commit. The other commits are in another PR.

### CODE REVIEW

**Comment by vivekmenezes** [comment]
@andreimatei  I rebased this. It's ready for review

**Comment by tamird** [comment]
This doesn't seem simpler to me, but perhaps I'm missing the bigger picture; AFAICT, this replaces "pass zero to get latest" with a new method; I think it'd be just as clear with a constant named `latestTableVersion` with a value of zero.

Either way, I don't feel strongly, so LGTM with nits fixed.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/lease.go, line 546 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-Ko9pYvQ5akcI50l9Qyd:-Ko9pYvQ5akcI50l9Qye:b-75azvz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c561b449d5ccd1e81c2762fcaf31e16195e07bc/pkg/sql/lease.go#L546)):*
> ```Go
> 
> // acquire returns the latest version of a table. The table will have its
> // refcount incremented, so the caller is responsible to call release() on it.
> ```

while you're here: s/to call/for calling/

---

*[pkg/sql/lease.go, line 547 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-Ko9pG6CI_-B4MswuuD9:-Ko9pG6CI_-B4MswuuDA:buio9t3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c561b449d5ccd1e81c2762fcaf31e16195e07bc/pkg/sql/lease.go#L547)):*
> ```Go
> // acquire returns the latest version of a table. The table will have its
> // refcount incremented, so the caller is responsible to call release() on it.
> func (t *tableState) acquire(
> ```

perhaps `acquireLatest` and `acquireVersion` would be better names for these methods?

---

*[pkg/sql/lease.go, line 555 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-Ko9petRUF53FNcjiQT2:-Ko9petS9zXOzSD5qCLN:b-mxzzmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c561b449d5ccd1e81c2762fcaf31e16195e07bc/pkg/sql/lease.go#L555)):*
> ```Go
> 	for {
> 		s := t.active.findNewest()
> 		if s != nil && s.hasSomeLifeLeft(m.clock) {
> ```

nit: `if s := ...; s != nil && .. {` since `s` isn't used outside this scope.

---

*[pkg/sql/lease.go, line 568 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-Ko9pma00aUHdwZoeVht:-Ko9pma00aUHdwZoeVhu:buc8elo) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c561b449d5ccd1e81c2762fcaf31e16195e07bc/pkg/sql/lease.go#L568)):*
> ```Go
> 
> // acquireMinVersion returns the latest version >= minVersion. The table
> // will have its refcount incremented, so the caller is responsible to
> ```

ditto grammar

---

*[pkg/sql/lease.go, line 577 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-Ko9pokMT8czCZCoe1f7:-Ko9pokMT8czCZCoe1f8:bvxsfan) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c561b449d5ccd1e81c2762fcaf31e16195e07bc/pkg/sql/lease.go#L577)):*
> ```Go
> 
> 	for {
> 		s := t.active.findNewest()
> ```

ditto reduce scope of `s`

---

*[pkg/sql/lease_test.go, line 250 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-Ko9p9MiVnmSAB1mH_G0:-Ko9p9MjTnKL9c7YS0oE:b1qxqbb) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdfc68af81c962831033098551de3846e409cec1/pkg/sql/lease_test.go#L250)):*
> ```Go
> 	t.expectLeases(descID, "/2/1")
> 
> 	// It is an error to acquire a lease for an old version once a new version
> ```

is this no longer the case?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-:-Ko9q0Dir-i8xF_7tTNC:b5s2t78)*

**Comment by vivekmenezes** [comment]
I've renamed acquireMinVersion to updateLatestVersion to clarify that we're updating the latest lease to the said version and have updated the commit comment

---

Review status: 4 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/sql/lease.go, line 546 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-Ko9pYvQ5akcI50l9Qyd:-Koh9MXIcnhPThjAOAk_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c561b449d5ccd1e81c2762fcaf31e16195e07bc/pkg/sql/lease.go#L546)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

while you're here: s/to call/for calling/
</blockquote></details>

Done.

---

*[pkg/sql/lease.go, line 547 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-Ko9pG6CI_-B4MswuuD9:-Koh9PcBDXJrM9C2hAy6:b-n3hfw9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c561b449d5ccd1e81c2762fcaf31e16195e07bc/pkg/sql/lease.go#L547)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

perhaps `acquireLatest` and `acquireVersion` would be better names for these methods?
</blockquote></details>

I've removed acquireMinVersion from the API

---

*[pkg/sql/lease.go, line 555 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-Ko9petRUF53FNcjiQT2:-KohADy_Z7uSwSL4IU9w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c561b449d5ccd1e81c2762fcaf31e16195e07bc/pkg/sql/lease.go#L555)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: `if s := ...; s != nil && .. {` since `s` isn't used outside this scope.
</blockquote></details>

Done.

---

*[pkg/sql/lease.go, line 568 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-Ko9pma00aUHdwZoeVht:-KohAPwZOtIoKXF_5wE0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c561b449d5ccd1e81c2762fcaf31e16195e07bc/pkg/sql/lease.go#L568)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

ditto grammar
</blockquote></details>

Done.

---

*[pkg/sql/lease.go, line 577 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-Ko9pokMT8czCZCoe1f7:-KohAWdbxZw1WT2zVeWU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c561b449d5ccd1e81c2762fcaf31e16195e07bc/pkg/sql/lease.go#L577)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

ditto reduce scope of `s`
</blockquote></details>

Done.

---

*[pkg/sql/lease_test.go, line 250 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-Ko9p9MiVnmSAB1mH_G0:-KohAepg5gQzKcakUtC1:b-2sq0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdfc68af81c962831033098551de3846e409cec1/pkg/sql/lease_test.go#L250)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is this no longer the case?
</blockquote></details>

This error has been removed and it is impossible via the API to ask for a specific version.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-:-KohAoewl8zKQLtarz1_:b-jwcohv)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/helpers_test.go, line 117 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-Koi5J9vqgUcQTjVz99Y:-Koi5J9vqgUcQTjVz99Z:b-gvfvfm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e412a0725006ae353bc10f575ebfa459eb1d2bd5/pkg/sql/helpers_test.go#L117)):*
> ```Go
> // A transaction is allowed to use the table descriptor as long as the txn
> // timestamp < expiration time.
> // TODO(andrei): move the tests that use this to the sql package and un-export
> ```

I think you can remove this TODO now that this is test-only code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751)*

**Comment by vivekmenezes** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/helpers_test.go, line 117 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-Koi5J9vqgUcQTjVz99Y:-KojB1cQFFavjqOUxPrp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e412a0725006ae353bc10f575ebfa459eb1d2bd5/pkg/sql/helpers_test.go#L117)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I think you can remove this TODO now that this is test-only code.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751)*

**Comment by vivekmenezes** [comment]
@andreimatei I've rebased this and it's waiting on your review when you return. Thanks

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 1 of 6 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/sql/helpers_test.go, line 113 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-KpoyFeZidkDACdFYvWo:-KpoyFeZidkDACdFYvWp:bhz8206) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c7b05d1b8f638459ee1688fbf8fa6feac9fd4ee/pkg/sql/helpers_test.go#L113)):*
> ```Go
> 
> // AcquireMinVersion acquires a read lease for the specified table ID.
> // the lease is grabbed on the latest version if >= specified version.
> ```

s/the lease/The lease

---

*[pkg/sql/helpers_test.go, line 113 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-KpoybOtjudVtRl1qfbY:-KpoybOtjudVtRl1qfbZ:b-o996vc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c7b05d1b8f638459ee1688fbf8fa6feac9fd4ee/pkg/sql/helpers_test.go#L113)):*
> ```Go
> 
> // AcquireMinVersion acquires a read lease for the specified table ID.
> // the lease is grabbed on the latest version if >= specified version.
> ```

I find this comment a bit confusing: the lease is always acquired on the latest version. I'd call this `AcquireAndAssertMinVersion()`?

---

*[pkg/sql/lease.go, line 566 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-KpotXwK2jv5jclLJwGA:-KpotXwK2jv5jclLJwGB:be74gcy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c7b05d1b8f638459ee1688fbf8fa6feac9fd4ee/pkg/sql/lease.go#L566)):*
> ```Go
> }
> 
> // updateLatestVersion ensures that the latest version >= minVersion.
> ```

please expand this comment explaining what the method does - acquires a new lease (but doesn't increase the refcount on it) if the current leased versions are not enough. The current comment sounds to me like this will just perform an assertion.
And carry over the comment from `acquireFromStoreLocked` about errors if the version doesn't exist.

---

*[pkg/sql/lease.go, line 567 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-KpotD3vnH1en8aN8lgH:-KpotD3wHowofIz9VMMn:bxxzju3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c7b05d1b8f638459ee1688fbf8fa6feac9fd4ee/pkg/sql/lease.go#L567)):*
> ```Go
> 
> // updateLatestVersion ensures that the latest version >= minVersion.
> func (t *tableState) updateLatestVersion(
> ```

I'd suggest naming this something with `ensure` - `ensureVersion()`.

---

*[pkg/sql/lease.go, line 585 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-KposyZ5O5gEHm6-9xA7:-KposyZ5O5gEHm6-9xA8:b-moesck) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c7b05d1b8f638459ee1688fbf8fa6feac9fd4ee/pkg/sql/lease.go#L585)):*
> ```Go
> 			return err
> 		}
> 		// A new lease was added, so loop and perform the lookup again.
> ```

It looks to me like we never loop - this point is unreachable (which is a good thing, as I was wondering when I read this why we need to loop). Right? The loop should be removed.

---

*[pkg/sql/lease.go, line 590 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-KpovRlu_XsGhbJufOnb:-KpovRlu_XsGhbJufOnc:b-nmbs3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c7b05d1b8f638459ee1688fbf8fa6feac9fd4ee/pkg/sql/lease.go#L590)):*
> ```Go
> 
> // acquireFromStoreLocked acquires a new lease from the store and inserts it
> // into the active set. t.mu must be locked. If the store version is less than
> ```

I don't like the "store version" syntagm (and I hope we don't use it elsewhere). I'd say "if the table (or descriptor) version doesn't exist".

---

*[pkg/sql/lease.go, line 846 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-KpowW0Q9I36iFhyaeyz:-KpowW0Q9I36iFhyaez-:b-10zodk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c7b05d1b8f638459ee1688fbf8fa6feac9fd4ee/pkg/sql/lease.go#L846)):*
> ```Go
> 	}
> 
> 	// Acquire a lease on the table on the latest version to maintain an
> ```

not your code, but is this right? We take a lease on the latest descriptor version... Who releases this lease? I hope somebody does, because otherwise draining the `LeaseMgr` wouldn't do what it's supposed to do - release all the leases.
cc @asubiotto 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-:-KpozAZJ3mn599R8nYT0:bnfp4nl)*

**Comment by vivekmenezes** [comment]
Review status: 1 of 6 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/sql/helpers_test.go, line 113 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-KpoyFeZidkDACdFYvWo:-Kpp02Qao-b1Ln7prpnp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c7b05d1b8f638459ee1688fbf8fa6feac9fd4ee/pkg/sql/helpers_test.go#L113)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/the lease/The lease
</blockquote></details>

Done.

---

*[pkg/sql/helpers_test.go, line 113 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-KpoybOtjudVtRl1qfbY:-Kpp02wIBROE-v-O5h4g:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c7b05d1b8f638459ee1688fbf8fa6feac9fd4ee/pkg/sql/helpers_test.go#L113)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I find this comment a bit confusing: the lease is always acquired on the latest version. I'd call this `AcquireAndAssertMinVersion()`?
</blockquote></details>

Done.

---

*[pkg/sql/lease.go, line 566 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-KpotXwK2jv5jclLJwGA:-Kpp4r_vWHzccvkT9QQC:b-izfx7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c7b05d1b8f638459ee1688fbf8fa6feac9fd4ee/pkg/sql/lease.go#L566)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please expand this comment explaining what the method does - acquires a new lease (but doesn't increase the refcount on it) if the current leased versions are not enough. The current comment sounds to me like this will just perform an assertion.
And carry over the comment from `acquireFromStoreLocked` about errors if the version doesn't exist.
</blockquote></details>

Expanded the comments here.

---

*[pkg/sql/lease.go, line 567 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-KpotD3vnH1en8aN8lgH:-Kpp1R-SaE8f__hGMMrn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c7b05d1b8f638459ee1688fbf8fa6feac9fd4ee/pkg/sql/lease.go#L567)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'd suggest naming this something with `ensure` - `ensureVersion()`.
</blockquote></details>

Done.

---

*[pkg/sql/lease.go, line 585 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-KposyZ5O5gEHm6-9xA7:-Kpp1bDP666NlSlsh5CU:bdcv6kv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c7b05d1b8f638459ee1688fbf8fa6feac9fd4ee/pkg/sql/lease.go#L585)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

It looks to me like we never loop - this point is unreachable (which is a good thing, as I was wondering when I read this why we need to loop). Right? The loop should be removed.
</blockquote></details>

Good point!

---

*[pkg/sql/lease.go, line 590 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-KpovRlu_XsGhbJufOnb:-Kpp2RD-_zmbDv06Eg0T:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c7b05d1b8f638459ee1688fbf8fa6feac9fd4ee/pkg/sql/lease.go#L590)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't like the "store version" syntagm (and I hope we don't use it elsewhere). I'd say "if the table (or descriptor) version doesn't exist".
</blockquote></details>

Done.

---

*[pkg/sql/lease.go, line 846 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751#-KpowW0Q9I36iFhyaeyz:-Kpp5MZrAmAvk3COw8cH:b-mcxedx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c7b05d1b8f638459ee1688fbf8fa6feac9fd4ee/pkg/sql/lease.go#L846)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

not your code, but is this right? We take a lease on the latest descriptor version... Who releases this lease? I hope somebody does, because otherwise draining the `LeaseMgr` wouldn't do what it's supposed to do - release all the leases.
cc @asubiotto 
</blockquote></details>

The lease is released below. Added a comment to document that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16751)*

**Pull request merged**
