### PR TITLE
concurrency: correctly defer to higher lock strength during dup access

### PR DESCRIPTION
**Pull request by arulajmani**
Burns down a TODO which only did so for lock.None lock strength. This was left over from a time when the lock table only expected lock.None and lock.Exclusive lock strengths.

When a key is being accessed with more than one lock strengths in a batch, we want to defer conflict resolution to the higher lock strength, as the lower lock strength access has sufficient protection from it. This means that if a lock table scan is resumed somewhere in the middle, and we've already checked for conflicts at the key before, we can simply ignore it and move on. Note that it doesn't matter if there is a conflict at the key -- we won't proceed to evaluation before coming back to this key, while holding latches and restarting our scan from the begining, so it'll be caught then.

Epic: none

Release note: None

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
There's no easy way to test this, but I verified that a diff like:

```go
--- a/pkg/kv/kvserver/concurrency/lock_table.go
+++ b/pkg/kv/kvserver/concurrency/lock_table.go
@@ -2533,7 +2533,7 @@ func (kl *keyLocks) conflictsWithLockHolders(g *lockTableGuardImpl) bool {
                g.mu.Lock()
                str, present := g.mu.locks[kl]
                g.mu.Unlock()
-               alsoLocksWithHigherStrength := present && str > g.curStrength()
+               alsoLocksWithHigherStrength := present && str >= g.curStrength()
                if alsoLocksWithHigherStrength {
                        // If the request already has this lock in its locks map, it must also be
                        // trying to acquire this lock at a higher strength. For it to be here, it
```

breaks our existing coverage. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110389#-:-Ne5EGsT-pvXuIPUhNVR:b5zgxya)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110389)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 815 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110389#-Ne5NciMEQpsX8Oi_ca8:-Ne5NciMEQpsX8Oi_ca9:bj3lbfq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2e703d14c705c16c8be4313353baeb101b7015a/pkg/kv/kvserver/concurrency/lock_table.go#L815)):*
> ```Go
> }
> 
> // makeLockMode constructs and returns a lock mode.
> ```

nit: move this above `maybeAddToLocksMap`.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2533 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110389#-Ne5NA6V4e5cpHxProH_:-Ne5NA6V4e5cpHxProHa:b-shyszq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2e703d14c705c16c8be4313353baeb101b7015a/pkg/kv/kvserver/concurrency/lock_table.go#L2533)):*
> ```Go
> 		}
> 
> 		g.mu.Lock()
> ```

Should this be moved outside of (above) the `kl.holders` loop?
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 3009 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110389#-Ne5NQwK-fSIpsf8cD2Q:-Ne5NQwK-fSIpsf8cD2R:b-ja7tci) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2e703d14c705c16c8be4313353baeb101b7015a/pkg/kv/kvserver/concurrency/lock_table.go#L3009)):*
> ```Go
> 		// NB: this inactive waiter can be non-transactional.
> 		g.mu.Lock()
> 		_, presentHere := g.mu.locks[kl]
> ```

Isn't `maybeAddToLocksMap` doing this now?

**Review by arulajmani — COMMENTED** [review]
TFTR, RFAL! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110389#-:-Ne8SQO_Am5xZYY9_JU2:bmu8o4n)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2533 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110389#-Ne5NA6V4e5cpHxProH_:-Ne8PW0o0Mxu0T8F6MpW:bxr8uxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2e703d14c705c16c8be4313353baeb101b7015a/pkg/kv/kvserver/concurrency/lock_table.go#L2533)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should this be moved outside of (above) the `kl.holders` loop?
</blockquote></details>

Yeah, good call. Done.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 3009 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110389#-Ne5NQwK-fSIpsf8cD2Q:-Ne8QaqX5Qyl-R11q3Hl:b-2fkgjd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2e703d14c705c16c8be4313353baeb101b7015a/pkg/kv/kvserver/concurrency/lock_table.go#L3009)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Isn't `maybeAddToLocksMap` doing this now?
</blockquote></details>

It is; fixed.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110389#-:-Ne8bsrN7qMwl0GT-8Wi:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by arulajmani** [comment]
Thanks!

bors r=nvanbenschoten

**Comment by arulajmani** [comment]
Ran into some status error. Force push + re-bors. 

bors r=nvanbenschoten

**Pull request merged**
