### PR TITLE
ui: hide statement diagnostics when role VIEWACTIVITYREDACTED

### LINKED ISSUE #74817: Hide Diagnostics Bundle info on console for sql user with role VIEWACTIVITYREDACTED
Follow up from https://github.com/cockroachdb/cockroach/issues/74716

When the sql user logged in to the Console (DB/CC) has role `VIEWACTIVITYREDACTED`, hide:
- Statements overview page - Diagnostics column
- Statements Details - Diagnostics tab
- Advanced Debug - Statement diagnostics history

Epic: CRDB-12103

### PR DESCRIPTION
**Pull request by maryliag**
When the sql user has the role VIEWACTIVITYREDACTED, all the information
about Statement Diagnostics Bundle will be hidden.
That happens on:
Statement - diagnostics column
Statement Details - diagnostics tab
Advanced Debug - diagnostics history

Fixes #74817

Note: Can only be merged after #75271 and #75273

Release note (ui change): If the user has the role VIEWACTIVITYREDACTED,
we hide the Statement Diagnostics bundle info on Statement page
(diagnostics column), Statement Details page (diagnostics tab) and
Advanced Debug page (diagnostics history).

### CODE REVIEW

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75274)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @maryliag)

___
*[pkg/ui/workspaces/db-console/src/redux/statements/statementsSagas.ts, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75274#-MtxzqBrExiiqMQU3z6a:-MtxzqBrExiiqMQU3z6b:b837sv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7baa94ace6b233d7fe1bbc5c751312f74251df60/pkg/ui/workspaces/db-console/src/redux/statements/statementsSagas.ts#L90)):*
> ```XML
>   yield put(refreshStatements(req) as any);
>   yield put(invalidateUserSQLRoles());
>   yield put(refreshUserSQLRoles() as any);
> ```

Hmm, do we have to recheck user's SQL Roles every time we change the time scale ? 
___
*[pkg/ui/workspaces/db-console/src/redux/user/userSagas.ts, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75274#-Mty-4Yj83_zn97f975J:-Mty-4Yj83_zn97f975K:b-7eq21h) ([raw file](https://github.com/cockroachdb/cockroach/blob/7baa94ace6b233d7fe1bbc5c751312f74251df60/pkg/ui/workspaces/db-console/src/redux/user/userSagas.ts#L21)):*
> ```XML
>     if (cachedData.userSQLRoles.valid) {
>       const roles = cachedData.userSQLRoles.data?.roles;
>       return roles.indexOf("VIEWACTIVITYREDACTED") > -1;
> ```

nit: perhaps using `roles.includes()` would be more fitting here? 
___
*[pkg/ui/workspaces/db-console/src/redux/user/userSagas.ts, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75274#-Mty-SQUDtQxZ-FC_Vow:-Mty-SQUDtQxZ-FC_Vox:bffne52) ([raw file](https://github.com/cockroachdb/cockroach/blob/7baa94ace6b233d7fe1bbc5c751312f74251df60/pkg/ui/workspaces/db-console/src/redux/user/userSagas.ts#L28)):*
> ```XML
> 
> export function* userSQLRolesSaga() {
>   yield all([]);
> ```

Hmm, why is `userSQLRolesSaga()` empty here? :thinking: Seems like we are directly using the reducers's refresh method to refresh the SQL Roles, do we still need to define an noop sagas here?

**Review by jocrl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75274)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.reducer.ts, line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75274#-MtyQnuvCBbyHWuP2dM6:-MtyQnuvCBbyHWuP2dM7:b-jfzoso) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f5df878e64d0c7b73269d37fb410ebec239d189/pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.reducer.ts#L21)):*
> ```XML
> export type UIConfigState = {
>   isTenant: boolean;
>   userSQLRoles: string;
> ```

nit: Would this make more sense as a string array? As things are, I'm not sure if this is space separated, comma separated, or something else
___
*[pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.reducer.ts, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75274#-MtyQloKAc7GQ39DwYgX:-MtyQloKAc7GQ39DwYgY:b-5rq4dt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f5df878e64d0c7b73269d37fb410ebec239d189/pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.reducer.ts#L39)):*
> ```XML
> const initialState: UIConfigState = {
>   isTenant: false,
>   userSQLRoles: "",
> ```

I'm assuming that the backend endpoints have access control to prevent users with this role from accessing the statement diagnostics bundle? Even if the user were to set this field
___
*[pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTable.stories.tsx, line 36 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75274#-MtyRLy06o33A4GasOF4:-MtyRLy06o33A4GasOF5:b-7aknau) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f5df878e64d0c7b73269d37fb410ebec239d189/pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTable.stories.tsx#L36)):*
> ```XML
>         "statement",
>         false,
>         false,
> ```

I think there's a question of how much we want to use storybook? If we do want to use storybook, it could be helpful if you added stories where hasViewActivityRedactedRole is true. That way we know that's one possibility, and future features could use the story to make sure that it works both ways.

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75274)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.reducer.ts, line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75274#-MtyQnuvCBbyHWuP2dM6:-MtyX0kvCSu1oDiEjbnI:btpwq2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f5df878e64d0c7b73269d37fb410ebec239d189/pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.reducer.ts#L21)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

nit: Would this make more sense as a string array? As things are, I'm not sure if this is space separated, comma separated, or something else
</blockquote></details>

Changed. I had made the change to use string[] on the api, just forgot to update here! 
___
*[pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.reducer.ts, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75274#-MtyQloKAc7GQ39DwYgX:-MtyXC2N3qAG4lWx1ANV:b561o42) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f5df878e64d0c7b73269d37fb410ebec239d189/pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.reducer.ts#L39)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

I'm assuming that the backend endpoints have access control to prevent users with this role from accessing the statement diagnostics bundle? Even if the user were to set this field
</blockquote></details>

That is correct, this is mostly to hide things from the ui, since they would get an error anyway
___
*[pkg/ui/workspaces/db-console/src/redux/user/userSagas.ts, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75274#-Mty-4Yj83_zn97f975J:-MtyXMp90eV9RVzFOio-:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7baa94ace6b233d7fe1bbc5c751312f74251df60/pkg/ui/workspaces/db-console/src/redux/user/userSagas.ts#L21)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: perhaps using `roles.includes()` would be more fitting here? 
</blockquote></details>

done
___
*[pkg/ui/workspaces/db-console/src/redux/user/userSagas.ts, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75274#-Mty-SQUDtQxZ-FC_Vow:-MtyXSQi346t7ygHmnKJ:ba3dfob) ([raw file](https://github.com/cockroachdb/cockroach/blob/7baa94ace6b233d7fe1bbc5c751312f74251df60/pkg/ui/workspaces/db-console/src/redux/user/userSagas.ts#L28)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm, why is `userSQLRolesSaga()` empty here? :thinking: Seems like we are directly using the reducers's refresh method to refresh the SQL Roles, do we still need to define an noop sagas here?
</blockquote></details>

Removed
___
*[pkg/ui/workspaces/db-console/src/redux/statements/statementsSagas.ts, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75274#-MtxzqBrExiiqMQU3z6a:-MtyXa7lEYNFPUJt4AEQ:ba3dfob) ([raw file](https://github.com/cockroachdb/cockroach/blob/7baa94ace6b233d7fe1bbc5c751312f74251df60/pkg/ui/workspaces/db-console/src/redux/statements/statementsSagas.ts#L90)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm, do we have to recheck user's SQL Roles every time we change the time scale ? 
</blockquote></details>

Removed

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75274)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @jocrl)

___
*[pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTable.stories.tsx, line 36 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75274#-MtyRLy06o33A4GasOF4:-MtybPa5BuB4ajy7cXkc:b5g2hix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f5df878e64d0c7b73269d37fb410ebec239d189/pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTable.stories.tsx#L36)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

I think there's a question of how much we want to use storybook? If we do want to use storybook, it could be helpful if you added stories where hasViewActivityRedactedRole is true. That way we know that's one possibility, and future features could use the story to make sure that it works both ways.
</blockquote></details>

New stories added (both bottle StatementTable and Statements Details page)

**Review by jocrl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75274)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @maryliag)

___
*[pkg/sql/roleoption/role_option.go, line 168 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75274#-MuBj3YN9HpWHGr-RLGQ:-MuBj3YODHWogntOEX1p:bfo4hak) ([raw file](https://github.com/cockroachdb/cockroach/blob/27fd407f7f42101329e35c9d20abdec359dd6aca/pkg/sql/roleoption/role_option.go#L168)):*
> ```Go
> // ToString returns the role in string format.
> // It should be used instead of roleOption.String() to accommodate the cases
> // with space on the role (e.g. `VALID UNTIL`).
> ```

Just out of curiosity, why does "VALID UNTIL" have a space in the role, but not the other ones?



_Code quote:_
```Go
// It should be used instead of roleOption.String() to accommodate the cases
// with space on the role (e.g. `VALID UNTIL`).
```
___
*[pkg/ui/workspaces/db-console/src/redux/apiReducers.ts, line 303 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75274#-MuBn_Mt4tyk8dtZt3nh:-MuBn_Mt4tyk8dtZt3ni:br8jf7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/27fd407f7f42101329e35c9d20abdec359dd6aca/pkg/ui/workspaces/db-console/src/redux/apiReducers.ts#L303)):*
> ```XML
> export const refreshStatements = queriesReducerObj.refresh;
> 
> const userSQLRolesReducerObj = new CachedDataReducer(
> ```

Just to clarify my understanding of `CachedDataReducer` - this doesn't cache across browser soft refreshes, correct? It just caches across calls to `.refresh()`.



_Suggestion:_
```XML
new CachedDataReducer
```
___
*[pkg/ui/workspaces/db-console/src/redux/user/userSagas.ts, line 17 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75274#-MuBow_14npjHaLomaGD:-MuBow_14npjHaLomaGE:b3amwgp) ([raw file](https://github.com/cockroachdb/cockroach/blob/27fd407f7f42101329e35c9d20abdec359dd6aca/pkg/ui/workspaces/db-console/src/redux/user/userSagas.ts#L17)):*
> ```XML
>   (state: AdminUIState) => state.cachedData,
>   cachedData => {
>     if (cachedData.userSQLRoles.valid) {
> ```

Just curious if it's intentional that`userSQLRoles.valid` is checked here, but not in the cluster-ui selector?



_Code quote:_
```XML
userSQLRoles.valid
```
___
*[pkg/ui/workspaces/db-console/src/views/reports/containers/debug/index.tsx, line 165 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75274#-MuBrjte6wBIR-WuPd0z:-MuBrjte6wBIR-WuPd1-:b-6nuhze) ([raw file](https://github.com/cockroachdb/cockroach/blob/27fd407f7f42101329e35c9d20abdec359dd6aca/pkg/ui/workspaces/db-console/src/views/reports/containers/debug/index.tsx#L165)):*
> ```XML
>   useEffect(() => {
>     refreshUserSQLRoles();
>   }, [props, refreshUserSQLRoles]);
> ```

I'd say that you don't want/need `props` here? `refreshUserSQLRoles` is already in the dependency array, and it generally doesn't make sense to put the whole props object in the dependency array since it's a shallow comparison.



_Suggestion:_
```XML
props
```

**Review by jocrl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75274)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @maryliag)

___
*[pkg/ui/workspaces/db-console/src/views/reports/containers/debug/index.tsx, line 165 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75274#-MuBrjte6wBIR-WuPd0z:-MuBsg5H--hs5xz7oRuT:b-ehqd1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/27fd407f7f42101329e35c9d20abdec359dd6aca/pkg/ui/workspaces/db-console/src/views/reports/containers/debug/index.tsx#L165)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

I'd say that you don't want/need `props` here? `refreshUserSQLRoles` is already in the dependency array, and it generally doesn't make sense to put the whole props object in the dependency array since it's a shallow comparison.
</blockquote></details>

edit: ignore the reviewable suggestion thing, idk what I clicked 😅

**Review by matthewtodd — COMMENTED** [review]
> Reviewed 25 of 25 files at r3, 2 of 2 files at r4, 18 of 20 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75274)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, @maryliag, and @matthewtodd)

___
*[pkg/ui/workspaces/db-console/src/redux/apiReducers.ts, line 303 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75274#-MuBn_Mt4tyk8dtZt3nh:-MuByKdcAbvKpri7zSyD:b-h7ya62) ([raw file](https://github.com/cockroachdb/cockroach/blob/27fd407f7f42101329e35c9d20abdec359dd6aca/pkg/ui/workspaces/db-console/src/redux/apiReducers.ts#L303)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

Just to clarify my understanding of `CachedDataReducer` - this doesn't cache across browser soft refreshes, correct? It just caches across calls to `.refresh()`.
</blockquote></details>

Yes, I believe that's right.
___
*[pkg/ui/workspaces/db-console/src/views/reports/containers/debug/index.tsx, line 168 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75274#-MuBzcxr5O1RNnZ-yRY9:-MuBzcxr5O1RNnZ-yRYA:b-oezazt) ([raw file](https://github.com/cockroachdb/cockroach/blob/27fd407f7f42101329e35c9d20abdec359dd6aca/pkg/ui/workspaces/db-console/src/views/reports/containers/debug/index.tsx#L168)):*
> ```XML
> 
>   return (
>     !hasViewActivityRedactedRole && (
> ```

I wonder if there's some value in having these components not know about the role names. Like, what if this was instead called `canSeeDebugPanelLink`. WDYT?

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75274)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @matthewtodd)

___
*[pkg/sql/roleoption/role_option.go, line 168 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75274#-MuBj3YN9HpWHGr-RLGQ:-MuBzux5CemAbOL_KYDg:bn48ltl) ([raw file](https://github.com/cockroachdb/cockroach/blob/27fd407f7f42101329e35c9d20abdec359dd6aca/pkg/sql/roleoption/role_option.go#L168)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

Just out of curiosity, why does "VALID UNTIL" have a space in the role, but not the other ones?
</blockquote></details>

`VALID UNTIL` is a common role used, so I assumed we wanted to keep compatible. Why we don't have other with space, I don't really know
___
*[pkg/ui/workspaces/db-console/src/redux/user/userSagas.ts, line 17 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75274#-MuBow_14npjHaLomaGD:-MuC7VxICsNDFtU4kf5w:b-5hddrp) ([raw file](https://github.com/cockroachdb/cockroach/blob/27fd407f7f42101329e35c9d20abdec359dd6aca/pkg/ui/workspaces/db-console/src/redux/user/userSagas.ts#L17)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

Just curious if it's intentional that`userSQLRoles.valid` is checked here, but not in the cluster-ui selector?
</blockquote></details>

I don't know why initially this was giving me an error without this. I checked again and it works as expected without this check, so I'm removing this here (since we don't really need it)
___
*[pkg/ui/workspaces/db-console/src/views/reports/containers/debug/index.tsx, line 165 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75274#-MuBrjte6wBIR-WuPd0z:-MuC7g4vCjUmwNRg-Yzl:ba3dfob) ([raw file](https://github.com/cockroachdb/cockroach/blob/27fd407f7f42101329e35c9d20abdec359dd6aca/pkg/ui/workspaces/db-console/src/views/reports/containers/debug/index.tsx#L165)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

edit: ignore the reviewable suggestion thing, idk what I clicked 😅
</blockquote></details>

Removed
___
*[pkg/ui/workspaces/db-console/src/views/reports/containers/debug/index.tsx, line 168 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75274#-MuBzcxr5O1RNnZ-yRY9:-MuC6pO9-yiq7KPKK9B2:b6mw68h) ([raw file](https://github.com/cockroachdb/cockroach/blob/27fd407f7f42101329e35c9d20abdec359dd6aca/pkg/ui/workspaces/db-console/src/views/reports/containers/debug/index.tsx#L168)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

I wonder if there's some value in having these components not know about the role names. Like, what if this was instead called `canSeeDebugPanelLink`. WDYT?
</blockquote></details>

The reason why I chose to use the role name is because we might use the same role to hide other things, so using the role name all pages can use the same selector, instead of focusing on the feature, which would cause us to create several selectors. For this page this will be the only thing we will hide, so I change to use your suggestions, for all other pages, I'll keep the name

**Review by jocrl — APPROVED** [review]
:lgtm: 😊

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75274#-:-MuD92SyA2TacoggL7Ql:bkt6k9o)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @matthewtodd)

**Review by matthewtodd — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75274#-:-MuGlJDEEhS9hPNf49QO:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @matthewtodd)

___
*[pkg/ui/workspaces/db-console/src/views/reports/containers/debug/index.tsx, line 168 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75274#-MuBzcxr5O1RNnZ-yRY9:-MuGkhjh50d540l4dPn_:bjk1h0) ([raw file](https://github.com/cockroachdb/cockroach/blob/27fd407f7f42101329e35c9d20abdec359dd6aca/pkg/ui/workspaces/db-console/src/views/reports/containers/debug/index.tsx#L168)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

The reason why I chose to use the role name is because we might use the same role to hide other things, so using the role name all pages can use the same selector, instead of focusing on the feature, which would cause us to create several selectors. For this page this will be the only thing we will hide, so I change to use your suggestions, for all other pages, I'll keep the name
</blockquote></details>

Makes sense. And I guess I was asking the question more as philosophical musing rather than as direct feedback for something I thought you should change -- sorry not to have been clear about that! I think this LGTM.

**Pull request merged**
