### PR TITLE
sql: properly qualify the names of dropped views

### LINKED ISSUE #57735: sql: event log entries for DROP TABLE,INDEX CASCADE + ALTER TABLE do not properly include the fully qualified names for dropped views
See in system.eventlog:

```
 drop_table          |       55 |           1 | {"TableName":"defaultdb.public.x","Statement":"DROP TABLE x CASCADE","User":"demo","CascadeDroppedViews":["y"]}

 drop_index           |       59 |           1 | {"TableName":"defaultdb.public.u","IndexName":"u_x_key","Statement":"DROP INDEX defaultdb.public.u@u_x_key CASCADE","User":"demo","MutationID":1,"CascadeDroppedViews":["v"]}
```

The `CascadeDroppedViews` field is populated with the "short" names of the views; this makes it impossible to determine from which logical schema or database they were dropped from.

Note: there is also a "dropped view" payload for `ALTER TABLE`, but I was not able to construct the example. The code path is the same though so it has the same bug.

### PR DESCRIPTION
**Pull request by the-ericwang35**
Fixes https://github.com/cockroachdb/cockroach/issues/57735.

Previously, event logs were not capturing the
fully qualified names of dropped views.
This PR changes the event logs to use the fully
qualified view names.
Tests were also updated to reflect this change.

Release note (bug fix): add qualification prefix for dropped views.

### CODE REVIEW

**Review by thoszhang — COMMENTED** [review]
> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59058)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @the-ericwang35)

___
*[pkg/sql/resolver.go, line 405 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59058#-MRg4m1yAx_MSE2sFJ5z:-MRg4m1z38CNZmfGNjt1:b-2xu3nk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ed7e7e9dfb34b9842f22c100749b378ec49d6f3/pkg/sql/resolver.go#L405)):*
> ```Go
> // reverse of the Resolve() functions.
> func (p *planner) getQualifiedTableName(
> 	ctx context.Context, desc catalog.TableDescriptor, flags tree.DatabaseLookupFlags,
> ```

I think we should just always set `IncludeOffline` and `IncludeDropped` to true and assume that the caller is fine with resolving a name for something dropped earlier in the transaction, instead of allowing callers to pass in flags. (NB: the `GetImmutable` methods try to resolve a leased descriptor unless `AvoidCached` is set. But dropped and offline descriptors can't be leased, so we just end up resolving the descriptor from the store every time. But that's fine.)

**Review by the-ericwang35 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59058)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/sql/resolver.go, line 405 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59058#-MRg4m1yAx_MSE2sFJ5z:-MRqOLGW8OK_E0IaavQV:b-tpuq2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ed7e7e9dfb34b9842f22c100749b378ec49d6f3/pkg/sql/resolver.go#L405)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I think we should just always set `IncludeOffline` and `IncludeDropped` to true and assume that the caller is fine with resolving a name for something dropped earlier in the transaction, instead of allowing callers to pass in flags. (NB: the `GetImmutable` methods try to resolve a leased descriptor unless `AvoidCached` is set. But dropped and offline descriptors can't be leased, so we just end up resolving the descriptor from the store every time. But that's fine.)
</blockquote></details>

Sure sounds good, I've changed it to always set `IncludeOffline` and `IncludeDropped` to be true

**Review by thoszhang — APPROVED** [review]
> Reviewed 16 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59058)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by the-ericwang35** [comment]
TFTR!

bors r+

**Pull request merged**
