### PR TITLE
Add info field to rangelog table

### PR DESCRIPTION
**Pull request by mrtracy**
Adds a generic string 'info' field to the range log table, which can contain
information specific to a single event. Information strings are JSON encoded;
the schema of the individual messages is not something that should be strictly
enforced, JSON is only used to assist cockroach users in processing these
messages themselves.

For the 'split' event type, the info are just the updated and new descriptors of
the split event.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4000)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[storage/log.go, line 48 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4000#-K94XV7o2ZoY6KgP2BTb:-K94XV7o2ZoY6KgP2BTc:-60613859) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc47a18f2360d826d3cffe154b7ff7408d96cca/storage/log.go#L48)):*
why rearrange this?

---

*[storage/log.go, line 119 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4000#-K94XgAC6_waa2UO1lDK:-K94XgAC6_waa2UO1lDL:-55867089) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc47a18f2360d826d3cffe154b7ff7408d96cca/storage/log.go#L119)):*
can you change `new` to something else? `new` is a keyword.

---

*[storage/log_test.go, line 100 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4000#-K94Y0H0pUITnZbiEan2:-K94Y0H0pUITnZbiEan3:2072898724) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc47a18f2360d826d3cffe154b7ff7408d96cca/storage/log_test.go#L100)):*
for consistency: `infoStr`?

---

*[storage/log_test.go, line 117 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4000#-K94Y3sxZ4L9kXfIxrR3:-K94Y3sxZ4L9kXfIxrR4:-1360679421) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc47a18f2360d826d3cffe154b7ff7408d96cca/storage/log_test.go#L117)):*
include the error?

---

*[storage/log_test.go, line 121 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4000#-K94Y9aD6e8-Qmcdwayj:-K94Y9aD6e8-Qmcdwayk:1130811710) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc47a18f2360d826d3cffe154b7ff7408d96cca/storage/log_test.go#L121)):*
no need to call String

---

*[storage/log_test.go, line 130 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4000#-K94YB55HPPfy5bfEOSm:-K94YB55HPPfy5bfEOSn:677916264) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc47a18f2360d826d3cffe154b7ff7408d96cca/storage/log_test.go#L130)):*
oops

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4000)*

**Comment by mrtracy** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[storage/log.go, line 48 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4000#-K94XV7o2ZoY6KgP2BTb:-K94a3moRqLn5pnvwLEJ:1940330716) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc47a18f2360d826d3cffe154b7ff7408d96cca/storage/log.go#L48)):*
Just felt more natural to me at the moment, I dunno.

---

*[storage/log.go, line 119 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4000#-K94XgAC6_waa2UO1lDK:-K94aG7PGGoFKfNUkQ2u:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc47a18f2360d826d3cffe154b7ff7408d96cca/storage/log.go#L119)):*
Done.

---

*[storage/log_test.go, line 100 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4000#-K94Y0H0pUITnZbiEan2:-K94aP7G4ZG4IvCjjFX5:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc47a18f2360d826d3cffe154b7ff7408d96cca/storage/log_test.go#L100)):*
Done.

---

*[storage/log_test.go, line 117 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4000#-K94Y3sxZ4L9kXfIxrR3:-K94aXmn5WOKM7shIvgZ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc47a18f2360d826d3cffe154b7ff7408d96cca/storage/log_test.go#L117)):*
Done.

---

*[storage/log_test.go, line 121 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4000#-K94Y9aD6e8-Qmcdwayj:-K94aabx-f9hfXTwFNLz:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc47a18f2360d826d3cffe154b7ff7408d96cca/storage/log_test.go#L121)):*
Done.

---

*[storage/log_test.go, line 130 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4000#-K94YB55HPPfy5bfEOSm:-K94acCgL4Ua-CpnZig4:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc47a18f2360d826d3cffe154b7ff7408d96cca/storage/log_test.go#L130)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4000)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[storage/log.go, line 48 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4000#-K94XV7o2ZoY6KgP2BTb:-K94bAkTthhWu9lW8qEh:1986240696) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc47a18f2360d826d3cffe154b7ff7408d96cca/storage/log.go#L48)):*
can you either switch it back or similarly rearrange the matching go struct?

huh, I thought I posted this yesterday. Sorry for duplicating @petermattis' comment.

---

*[storage/log_test.go, line 115 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4000#-K94b3BX3KjHtZw0HK-p:-K94b3BX3KjHtZw0HK-q:-937109909) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc47a18f2360d826d3cffe154b7ff7408d96cca/storage/log_test.go#L115)):*
again for consistency: `info`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4000)*

**Comment by mrtracy** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[storage/log.go, line 48 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4000#-K94XV7o2ZoY6KgP2BTb:-K98ZsUL5fBf5TuVqtmZ:124627956) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc47a18f2360d826d3cffe154b7ff7408d96cca/storage/log.go#L48)):*
Done, struct and table match.

---

*[storage/log.go, line 78 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4000#-K953myBJ0T0qAAEMNM6:-K98_7N23jDb8h8Y_hCa:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/a648bcec7595b3e02754f1e359071140af44f064/storage/log.go#L78)):*
Done.

---

*[storage/log.go, line 105 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4000#-K954G_fdxhEXRFxCZEY:-K98_2UtwLb-YC4znG9g:486394995) ([raw file](https://github.com/cockroachdb/cockroach/blob/a648bcec7595b3e02754f1e359071140af44f064/storage/log.go#L105)):*
Hah, I was already doing that in my next WIP PR to log rebalances. Done.

---

*[storage/log_test.go, line 115 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4000#-K94b3BX3KjHtZw0HK-p:-K98_WznzG0GZhbr2J0H:-591348538) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc47a18f2360d826d3cffe154b7ff7408d96cca/storage/log_test.go#L115)):*
Done.   Also used peter's above suggestion of an inline struct here as well.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4000)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4000)*

**Pull request merged**
