### PR TITLE
vendor: bump pebble to cc68c2ee776ff95baf302e7ad1b989507a76d8a5

### PR DESCRIPTION
**Pull request by petermattis**
* internal/cache: avoid SetFinalizer in race builds
* internal/record: rework the handling of LogWriter free blocks

Release note: None

### CODE REVIEW

**Review by itsbilal — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50031#-:-M9UJEviBKMWvM_cbCec:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @jbowens)

**Comment by petermattis** [comment]
`TestSQLAlchemy` failure in Examples-ORMs. Nothing obviously related to this PR.

bors r+

**Comment by petermattis** [comment]
Hmm, exact same `TestSQLAlchemy` failure. The logs aren't telling me much, but I'm taking a look. Seems unlikely to be related to this PR, though.

bors r+

**Comment by petermattis** [comment]
> Hmm, exact same TestSQLAlchemy failure. The logs aren't telling me much, but I'm taking a look. Seems unlikely to be related to this PR, though.

This failure is also happening on master builds. Filed #50084.

**Pull request merged**
