### PR TITLE
sqlbase: document how ColumnType works

### PR DESCRIPTION
**Pull request by knz**
Needed for #28690 and #28776.

I was trying to understand this and had to reverse-engineer it from
the code. Here's an explanatory comment.

I do not endorse the design but I think the comment will be useful to
discuss further improvements. For example any future changes will also
have to update the explanatory comment, and the diff on that comment
may constitute a good summary of the changes under consideration.

Release note: None

### CODE REVIEW

**Review by BramGruneir — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28792)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/structured.proto, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28792#-LKMif_02NFx1z0O-Ef5:-LKMif_02NFx1z0O-Ef6:bj65dsh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1abaa5046556805a9fed2d12ddedb8598c9e6b9c/pkg/sql/sqlbase/structured.proto#L66)):*
> ```protobuf
> // | DOUBLE PRECISION,DOUBLE,FLOAT8 | FLOAT          | DOUBLE PRECISION | 0         | 0     | Incorrect, #28776 |
> // |                                |                |                  |           |       |                   |
> // | INT                            | INT            | NONE             | 0         | 0     | Dubious, #28690   |
> ```

Dubious seems a bit harsh here.  And also insn't 28690 replaced by all of the smaller changes you been sending?  I guess it is a good summary.

I'm not sure if this is the correct location to put this note, but I do agree that having it is important.

**Review by rjnn — APPROVED** [review]
:lgtm: thanks for adding this documentation!

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28792#-:-LKMxjh7DMT6RwLtEghV:b7ndavd)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28792)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sqlbase/structured.proto, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28792#-LKMif_02NFx1z0O-Ef5:-LKNS_y86th9FpoxFbJd:b39pb6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/1abaa5046556805a9fed2d12ddedb8598c9e6b9c/pkg/sql/sqlbase/structured.proto#L66)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Dubious seems a bit harsh here.  And also insn't 28690 replaced by all of the smaller changes you been sending?  I guess it is a good summary.

I'm not sure if this is the correct location to put this note, but I do agree that having it is important.
</blockquote></details>

I have kept the note but removed the word "dubious".

The PR #28690 has been trimmed down but I will make sure it still contains the INT changes, so the reference stays valid.

**Review by BramGruneir — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28792)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sqlbase/structured.proto, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28792#-LKMif_02NFx1z0O-Ef5:-LKNT-2D8q62nbb8vS4B:bb73djm) ([raw file](https://github.com/cockroachdb/cockroach/blob/1abaa5046556805a9fed2d12ddedb8598c9e6b9c/pkg/sql/sqlbase/structured.proto#L66)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I have kept the note but removed the word "dubious".

The PR #28690 has been trimmed down but I will make sure it still contains the INT changes, so the reference stays valid.
</blockquote></details>

SGTM

**Review by BramGruneir — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28792#-:-LKNT3dCBvIL6BNuz_2x:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Pull request merged**
