### PR TITLE
roachpb: replace observed_timestamps representation from map to slice 

### LINKED ISSUE #5090: storage: RangeStatsKey is not being replicated properly
When I filter out the stats key from the replica checksum computation and turn on the checksum verification  panic all the acceptance tests pass.

```diff
diff --git a/storage/replica_command.go b/storage/replica_command.go
index 423ce06..ff8c390 100644
--- a/storage/replica_command.go
+++ b/storage/replica_command.go
@@ -1422,10 +1422,18 @@ func (r *Replica) sha512(desc roachpb.RangeDescriptor, snap engine.Engine) ([]by
        hasher := sha512.New()
        // Iterate over all the data in the range.
        iter := newReplicaDataIterator(&desc, snap, true /* replicatedOnly */)
+       // stats key to be ignored for now.
+       statsKey := keys.RangeStatsKey(r.Desc().RangeID)
        defer iter.Close()
        for ; iter.Valid(); iter.Next() {
                key := iter.Key()
                value := iter.Value()
+
+               // Ignore the stats key because it's not replicated.
+               if bytes.Equal(key.Key, statsKey) {
+                       continue
+               }
+
                // Encode the length of the key and value.
                if err := binary.Write(hasher, binary.LittleEndian, int64(len(key.Key))); err != nil {
                        return nil, err
@@ -1494,7 +1502,7 @@ func (r *Replica) VerifyChecksum(batch engine.Engine, ms *engine.MVCCStats, h ro
                                        p()
                                } else {
                                        // TODO(.*): see #5051.
-                                       log.Errorf("checksums: e = %v, v = %v", args.Checksum, c.checksum)
+                                       panic(fmt.Sprintf("checksums: e = %v, v = %v", args.Checksum, c.checksum))
                                }
                        }
                } else {
```

### PR DESCRIPTION
**Pull request by vivekmenezes**
closes #5090

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5283)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Come to think of it - probably fine to not do the ordering. That way we have a nice way of tracking the order in which the nodes were visited, the code is simpler and it's not clear that the other option is even a performance win (definitely not allocation-wise). Sorry for pushing you in the other direction earlier.
:LGTM:

---

Reviewed 7 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[kv/dist_sender_test.go, line 386 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5283#-KCxJfWyNwUqgeXqJbx7:-KCxJfWyNwUqgeXqJbx8:-783379915) ([raw file](https://github.com/cockroachdb/cockroach/blob/71aa0f0688bedffa708b8c108903840f6cc16e06/kv/dist_sender_test.go#L386)):*
nit: `var act []roachpb.Transaction_ObservedTimestamp`

---

*[roachpb/data.go, line 619 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5283#-KCxJsHprGV6h5_EvmDl:-KCxJsHprGV6h5_EvmDm:1774888946) ([raw file](https://github.com/cockroachdb/cockroach/blob/71aa0f0688bedffa708b8c108903840f6cc16e06/roachpb/data.go#L619)):*
this does the wrong thing, you want `make(..., 0, len(..))`

If it's not failing tests, add this into the unit test for this method.

BTW, much more concise:
`t.ObservedTimestamps = append([]Transaction_ObservedTimestamp(nil), mt...)`

---

*[roachpb/data.proto, line 311 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5283#-KCxKT10qqS5JQ714Q07:-KCxKT11SyoQMrOpnYM7:-1196261588) ([raw file](https://github.com/cockroachdb/cockroach/blob/71aa0f0688bedffa708b8c108903840f6cc16e06/roachpb/data.proto#L311)):*
whitespace.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5283#-:-KCxKl0bsvAatljHj8yW:-1707437315)*

**Comment by tamird** [comment]
I'm :-1: on this; are we really going to stop using maps because they don't marshal predictably?

---

Reviewed 7 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[roachpb/data.go, line 621 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5283#-KCxK4zRbNGuHHOqnTbS:-KCxK4zSoQUTss_ZMomh:382720072) ([raw file](https://github.com/cockroachdb/cockroach/blob/71aa0f0688bedffa708b8c108903840f6cc16e06/roachpb/data.go#L621)):*
this is incorrect - this slice will have `len(mt)` zero-valued entries.

---

*[roachpb/data.go, line 840 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5283#-KCxKcqRrqCVg6mK_Gnl:-KCxKcqRrqCVg6mK_Gnm:1866723608) ([raw file](https://github.com/cockroachdb/cockroach/blob/838eef7ff1b89a13e12dfe240ae9b23c695b7236/roachpb/data.go#L840)):*
why not binary search here too?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5283#-:-KCxKsRZ2IGmUZqB00g7:2069638911)*

**Comment by tschottdorf** [comment]
> I'm :-1: on this; are we really going to stop using maps because they don't marshal predictably?

If you're going to be :-1: you hopefully also have a better idea? The map issue seems like a major drawback (the only alternative I can see is custom marshaling code which sorts the keys before each marshal - a lot of senseless work).

**Comment by vivekmenezes** [comment]
Review status: 4 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[kv/dist_sender_test.go, line 386 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5283#-KCxJfWyNwUqgeXqJbx7:-KCxRwNB-7TT-4cdclFE:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/71aa0f0688bedffa708b8c108903840f6cc16e06/kv/dist_sender_test.go#L386)):*
done

---

*[roachpb/data.go, line 619 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5283#-KCxJsHprGV6h5_EvmDl:-KCxTVrVTr1kpGx3TcOX:-85986195) ([raw file](https://github.com/cockroachdb/cockroach/blob/71aa0f0688bedffa708b8c108903840f6cc16e06/roachpb/data.go#L619)):*
Oops! Fixed and added a test

---

*[roachpb/data.go, line 621 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5283#-KCxK4zRbNGuHHOqnTbS:-KCxTkehy-JjMOjCuJqB:-1549918397) ([raw file](https://github.com/cockroachdb/cockroach/blob/71aa0f0688bedffa708b8c108903840f6cc16e06/roachpb/data.go#L621)):*
Fixed and added a test.

---

*[roachpb/data.go, line 840 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5283#-KCxKcqRrqCVg6mK_Gnl:-KCxTaC_YdB7IVShPeJf:-337026618) ([raw file](https://github.com/cockroachdb/cockroach/blob/838eef7ff1b89a13e12dfe240ae9b23c695b7236/roachpb/data.go#L840)):*
Removed the sorted implementation completely. It's a lot safer this way.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5283)*

**Comment by vivekmenezes** [comment]
I think we can continue using the maps in gossip.proto. I see another map in span.proto which I think I will take out. Do comment on that PR.

---

Review status: 4 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[roachpb/data.proto, line 311 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5283#-KCxKT10qqS5JQ714Q07:-KCxVWfJ4H4E0VVZU4rF:107542053) ([raw file](https://github.com/cockroachdb/cockroach/blob/71aa0f0688bedffa708b8c108903840f6cc16e06/roachpb/data.proto#L311)):*
weird. I actual don't see it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5283#-:-KCxVdQQLe_ZpM3HASaD:-1654855915)*

**Comment by tschottdorf** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[roachpb/data.go, line 619 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5283#-KCxJsHprGV6h5_EvmDl:-KCxWq5TXn94MIv6xdiM:-695630092) ([raw file](https://github.com/cockroachdb/cockroach/blob/71aa0f0688bedffa708b8c108903840f6cc16e06/roachpb/data.go#L619)):*
You don't want to use the more concise code?

---

*[roachpb/data.proto, line 311 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5283#-KCxKT10qqS5JQ714Q07:-KCxWaLnesqbBQ6XDxke:-1945890496) ([raw file](https://github.com/cockroachdb/cockroach/blob/71aa0f0688bedffa708b8c108903840f6cc16e06/roachpb/data.proto#L311)):*
oh, you removed the newline at the end of the file. I think that's fine then.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5283)*

**Comment by vivekmenezes** [comment]
Review status: 4 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[roachpb/data.go, line 619 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5283#-KCxJsHprGV6h5_EvmDl:-KCxYK0qUrf_2bnwhVQ9:-238423021) ([raw file](https://github.com/cockroachdb/cockroach/blob/71aa0f0688bedffa708b8c108903840f6cc16e06/roachpb/data.go#L619)):*
Adopted your suggestion.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5283)*

**Comment by tamird** [comment]
I don't have another suggestion right now, but it's also midnight. The discussion in this thread suggests that you intend to to merge this now. What's the hurry? It'd be nice to have a chance to consider this during daylight hours.

---

Reviewed 3 of 3 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[roachpb/data.proto, line 311 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5283#-KCxKT10qqS5JQ714Q07:-KCxacMHENQoMOW7AUsv:-1235676514) ([raw file](https://github.com/cockroachdb/cockroach/blob/71aa0f0688bedffa708b8c108903840f6cc16e06/roachpb/data.proto#L311)):*
should bring that back - pretty standard convention to leave a trailing newline.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5283#-:-KCxag5t36-Pkk67S6CO:1573411917)*

**Comment by vivekmenezes** [comment]
I don't have a problem waiting on this PR

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5283#-:-KCxbkMP2CtO1kvug6Mw:1991383170)*

**Comment by vivekmenezes** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[roachpb/data.proto, line 311 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5283#-KCxKT10qqS5JQ714Q07:-KCxcURMPh-6yFsERovO:-467915377) ([raw file](https://github.com/cockroachdb/cockroach/blob/71aa0f0688bedffa708b8c108903840f6cc16e06/roachpb/data.proto#L311)):*
fixed

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5283)*

**Comment by tschottdorf** [comment]
Waiting doesn't buy us anything but it delays finding out about additional inconsistencies on our cluster (since this one currently always trips it up). If you have any insights tomorrow (would be surprised if you did, but I'm obviously going to hope you do), it's easy enough to send a better fix, no? We've both looked at this, the code looks ok, so it's not a poorly reviewed rushed merge.

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5283#-:-KCxccZb4wdaZcipt7u6:-1559439627)*

**Comment by petermattis** [comment]
Stability of the marshaling is important and protobufs have historically guaranteed this. I'm surprised that the addition of maps removed this feature. Is it possible that this is a gogoprotobuf-only issue?

**Comment by vivekmenezes** [comment]
This is what the standard says:

Wire format ordering and map iteration ordering of map values is undefined, so you cannot rely on your map items being in a particular order.

**Comment by vivekmenezes** [comment]
The two other places where we use maps is in the gossip proto and in the Span message used in util/tracing. I'm inclined to want to change the one used in Span, but the leave the gossip one as is. I'm also going to added a check to "make check" to restrict the use of map.

**Comment by petermattis** [comment]
@vivekmenezes Thanks for tracking that down. Certainly surprising.

I'm curious about something, why is the `Transaction` being marshaled multiple times and having a checksum computed? When storing a `Transaction` I would think it is marshaled once and the checksum computed and then on read we verify the checksum and unmarshal.

**Comment by vivekmenezes** [comment]
There is no problem with the checksum stored with the value, and used locally to verify the value stored. What I reported in our meeting was a red herring.

The current issue is when comparing values stored across nodes. The consistency checker assumes that the value stores is byte for byte consistent, and uses its own checksum to verify that.

**Comment by vivekmenezes** [comment]
@tamird has an idea that would allow us to add a gogoproto extension specifying that the map is predictably serialized. He is working on that separately. I'm going to merge this in for now so that we can see if we have any more consistency issues.

**Pull request merged**
