### PR TITLE
colexec: fix projections of joiners

### LINKED ISSUE #40621: sql: panic: flow: unexpected 204800 leftover bytes
On the TPCH SF1 dataset:

```
set vectorize=experimental_on;

SELECT
	c_name,
	c_custkey,
	o_orderkey,
	o_orderdate,
	o_totalprice,
	sum(l_quantity)
FROM
	customer,
	orders,
	lineitem
WHERE
	o_orderkey IN (
		SELECT
			l_orderkey
		FROM
			lineitem
		GROUP BY
			l_orderkey HAVING
				sum(l_quantity) > -9223372036854775807
	)
	AND c_custkey = o_custkey
	AND o_orderkey = l_orderkey
GROUP BY
	c_name,
	c_custkey,
	o_orderkey,
	o_orderdate,
	o_totalprice
ORDER BY
	o_totalprice DESC,
	o_orderdate
LIMIT 100;
```

```
* ERROR: [n1,client=[::1]:56946,user=root] a SQL panic has occurred while executing "SELECT c_name, c_custkey, o_orderkey, o_orderdate, o_totalprice, sum(l_quantity) FROM customer, orders, lineitem WHERE ((o_orderkey IN (SELECT l_orderkey FROM lineitem GROUP BY l_orderkey HAVING sum(l_quantity) > $1::INT8)) AND (c_custkey = o_custkey)) AND (o_orderkey = l_orderkey) GROUP BY c_name, c_custkey, o_orderkey, o_orderdate, o_totalprice ORDER BY o_totalprice DESC, o_orderdate LIMIT 100": flow: unexpected 204800 leftover bytes

runtime/debug.Stack(0x4f50c00, 0xc00fce68c0, 0x3)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x4f50c00, 0xc00fce68c0, 0xc000858000, 0x43b7400, 0xc00a1dc9c0, 0x1)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:217 +0xb6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc008264000, 0x4f50c00, 0xc00fce68c0, 0x3f4f640, 0xc0072e98e0)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:723 +0x2a0
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc008264000, 0x4f50c00, 0xc00fce68c0)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:442 +0x61
panic(0x3f4f640, 0xc0072e98e0)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/cockroachdb/cockroach/pkg/util/log.ReportOrPanic(0x4f50cc0, 0xc007718f00, 0xc000858000, 0xc000028630, 0x26, 0x0, 0x0, 0x0)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:554 +0x226
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).doStop(0xc007c48820, 0x4f50cc0, 0xc007718f00, 0x30d9301)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:397 +0x291
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).Stop(...)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:384
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*EvalContext).Stop(...)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:2780
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Cleanup(0xc007433c20, 0x4f50cc0, 0xc007718f00)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:630 +0x87
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run.func5()
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:354 +0xc0
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc008264000, 0x4f50cc0, 0xc00094b170, 0xc008264358, 0x3, 0x7f74cc9722a8, 0xc000720f68, 0xc00ad3a901, 0x0, 0x0, ...)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:823 +0x4c1
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc008264000, 0x4f50cc0, 0xc00094b170, 0xc008264358, 0x7f74cc9722a8, 0xc000720f68, 0x0, 0x0)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:708 +0x6de
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc008264000, 0x4f50cc0, 0xc00094b170, 0x4f75880, 0xc00f93ae00, 0xc0082987f7, 0x1af, 0x1, 0x4, 0xc00b1df080, ...)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:417 +0xc2f
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc008264000, 0x4f50cc0, 0xc00094b170, 0x4f75880, 0xc00f93ae00, 0xc0082987f7, 0x1af, 0x1, 0x4, 0xc00b1df080, ...)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:98 +0x4ec
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc008264000, 0x4f50c00, 0xc000e19f80, 0x0, 0x0)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1300 +0xed6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc008264000, 0x4f50c00, 0xc00fce68c0, 0xc000b78340, 0x5400, 0x15000, 0xc000b783d8, 0xc00f718230, 0x0, 0x0)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1167 +0x1a3
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc000826000, 0x4f50c00, 0xc00fce68c0, 0xc008264000, 0x5400, 0x15000, 0xc000b783d8, 0xc00f718230, 0x0, 0x0)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:444 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc01b818079, 0xc0004b4120, 0x4f50c00, 0xc00fce68c0, 0xc00f718230, 0xc000826000, 0xc000720900, 0x4f73e00, 0xc0004b4100, 0xc01cb71b00, ...)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:584 +0x21c
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:513 +0x17b
```

This is tpch query 18 with a randomized argument for the HAVING clause. I'm not able to repro this, so it's possible it's due to multiple executions happening at once (which is what my test was doing). Also possibly due to the connection getting its context canceled, and maybe somewhere something isn't cleaning up correctly. Marking this as `C-investigation` until we can repro it.

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: fix projections of joiners**

Hash and merge joiners handle the projection themselves for efficiency
reason. However, previously, they didn't do it correctly in all cases -
when in the requested projection some columns from the right come before
some columns from the left side, the output would not be correct because
the joiners always output all the columns from the left side first. Now
this is fixed.

Fixes: #40621.
Addresses: #38994.

Release justification: Category 2: Bug fixes and low-risk updates
to new functionality.

**colexec: fix remapping of IVars during filter planning**

Previously, the remapping could be done incorrectly. Consider a
case when we have `@2 = @4` with idxVarMap = {-1, 0, -1, 1}. After
we replaced `@4` with `@2`, we would have `@2 = @2` with no way to
distinguish between the original and the already replaced ordinals.
Now this is fixed by inserting a special symbol `#` inside of the
newly replaced ordinal with a second step of removing it later.

Release justification: Category 2: Bug fixes and low-risk updates
to new functionality.

**colexec: refactor creation of hash and merge joiners**

A lot of the code in "planning" of the hash and merge joiners is
the same, so this commit extracts it out in a single function that
is used when creating both joiners.

Release justification: Category 1: Non-production code changes.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
This PR contains two commits, and I think it'll be easier to review them one at a time (the second one is merely a refactor with no changes to the planning logic).

**Comment by yuzefovich** [comment]
I need to fix one more bug here as well as refactor the code a little bit more, so please hold off on the reviews for now.

**Comment by yuzefovich** [comment]
This PR is now RFAL.

**Comment by yuzefovich** [comment]
Testing that would catch the bug that is fixed in the second commit here is added in a different PR.

**Review by asubiotto — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40995)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/colexec/execplan.go, line 116 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40995#-Lpd-OtO5gXXvLk2cNpG:-Lpd-OtO5gXXvLk2cNpH:b-822vi) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c922a85e59f1f0766278564537840dc533d2f19/pkg/sql/colexec/execplan.go#L116)):*
> ```Go
> // createJoiner adds a new hash or merge join with the argument function
> // createJoinOpWithOnExprPlanning distinguishing between the two.
> func (r *NewColOperatorResult) createJoiner(
> ```

It feels a bit awkward to make this a method of `NewColOperatorResult`. Could this maybe be a function that takes one as an argument?
___
*[pkg/sql/colexec/hashjoiner_test.go, line 933 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40995#-LpczFt23RsVBU6xGtRs:-LpczFt30OYhavwZAbfX:b9e2plw) ([raw file](https://github.com/cockroachdb/cockroach/blob/971e0cd921fb2a4758e6e3f633b504605a99614c/pkg/sql/colexec/hashjoiner_test.go#L933)):*
> ```Go
> 			// The "core" of the test - we ask for a projection in which the columns
> 			// from the left and from the right are intertwined.
> 			OutputColumns: []uint32{3, 1, 0, 5, 4, 2},
> ```

The test comment seems to imply that the projections will be random (due to the word arbitrary). Maybe that's something you could do here? If it doesn't seem like it'll add too much, don't worry about it, but maybe update the comment.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40995)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/colexec/execplan.go, line 116 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40995#-Lpd-OtO5gXXvLk2cNpG:-Lpd2y3C1yJnS071thCI:b-2x3svd) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c922a85e59f1f0766278564537840dc533d2f19/pkg/sql/colexec/execplan.go#L116)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It feels a bit awkward to make this a method of `NewColOperatorResult`. Could this maybe be a function that takes one as an argument?
</blockquote></details>

I see your point, done. I was concerned that this function takes in too many arguments (one of those is another function that takes many arguments and returns many things as well), so I thought of using a receiver to reduce the "argument burden" a little. I don't see a reasonable way to refactor `createJoiner` function (like no "coherent" struct stands out to me), but maybe it is fine as is since this function should be called only within `execplan.go` file from two places.
___
*[pkg/sql/colexec/hashjoiner_test.go, line 933 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40995#-LpczFt23RsVBU6xGtRs:-Lpd3dM80afHO4UoHTo8:bvy3ja8) ([raw file](https://github.com/cockroachdb/cockroach/blob/971e0cd921fb2a4758e6e3f633b504605a99614c/pkg/sql/colexec/hashjoiner_test.go#L933)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

The test comment seems to imply that the projections will be random (due to the word arbitrary). Maybe that's something you could do here? If it doesn't seem like it'll add too much, don't worry about it, but maybe update the comment.
</blockquote></details>

I updated the comment. It would be too much code to handle a truly random projection because we need to keep calls to `b.ColVec(i).TYPE` in sync with it, and I agree with you that it wouldn't add much to the coverage. The particular projection that I hardcoded seems sufficient.

**Review by asubiotto — APPROVED** [review]
LGTM

**Comment by yuzefovich** [comment]
TFTR!

bors r=asubiotto

**Pull request merged**
