### PR TITLE
colexecwindow: fix the benchmark

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, the window functions benchmark could have generated an
invalid input data set because we used the finite chunks source with
`matchLen == 1` which assumes that the first column is already ordered.
However, this is not the case, and we could get negative numbers on the
batches after the first one. I think we don't want to use that source,
so this commit switches to populating the whole input data set manually.

Release note: None

Release justification: testing only change.

### CODE REVIEW

**Comment by yuzefovich** [comment]
This fixes a panic as seen [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=3376059&buildTypeId=Cockroach_Ci_Tests_Bench&tab=buildLog&_focus=24743#_state=261,24743).

**Comment by yuzefovich** [comment]
@cockroachdb/sql-queries anyone care for a quick review? :)

**Review by cucaroach — COMMENTED** [review]
Not really familiar with this code but :LGTM:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69587#-:-MiTmYyT2SBSWHTNu_zS:b60iue6)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
That's ok - this is test only change :)

TFTR!

bors r+

**Pull request merged**
