### PR TITLE
opt: add exploration rule for constraining scans

### PR DESCRIPTION
**Pull request by RaduBerinde**
New "constrain scan" explore rule tries to push filters into scans,
as constraints. The result is either just the constrained scan (if the
filter was fully converted into a constraint), or a select on top of
the constrained scan.

Along with the rule, we needed some minor changes on the execution
side to support scan constraints.

Other fixes that were necessary:

 - optgen: the generated code for explore rules was adding expressions
   to the wrong group (because of shadowing of the original `_eid`).

 - idxconstraint support for `FiltersOp`.

 - move the idxconstraint test to `idxconstraint_test` package to avoid
   import loop.

 - test catalog fix: the primary index was returning the wrong ordinal
   value.

 - adding some cost to the select operator, to prefer a constrained
   scan with no remaining filter (vs a constrained scan with a
   remaining filter).

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
:lgtm:
Very nice, mostly nits from me.
It's exciting to see our 2nd exploration rule come online, especially with as big of an impact as this rule will have.

---

Review status: 0 of 39 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/sql/opt/exec/execbuilder/testdata/select, line 11 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pAnj76OCPvulrsDjg:-L8pAnj76OCPvulrsDjh:b-j9eyy8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/exec/execbuilder/testdata/select#L11)):*
> ```
> 
> exec-explain
> SELECT * FROM t.a WHERE x > 1
> ```

I think it'd be good to have a few exec tests that are testing data types other than int, just to make sure they're working end-to-end.

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 669 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pAyTm5X9R8pFfIo0_:-L8pAyTm5X9R8pFfIo0a:b-9baeqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/idxconstraint/index_constraints.go#L669)):*
> ```Go
> }
> 
> // makeSpansForAndcalculates spans for an AndOp or FiltersOp.
> ```

NIT: need space before "calculates"

---

*[pkg/sql/opt/norm/testdata/bool, line 201 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pCA03BSKHhJDh6dK1:-L8pCA03BSKHhJDh6dK2:b9nkfo3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/norm/testdata/bool#L201)):*
> ```
> SELECT * FROM a WHERE false OR false
> ----
> scan a,constrained
> ```

It seems redundant to show "constrained" here when the constraint is also shown below.

---

*[pkg/sql/opt/optgen/cmd/optgen/explorer_gen.go, line 88 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pCpN21JxKqhIpSWze:-L8pCpN21JxKqhIpSWzf:bm5llme) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/optgen/cmd/optgen/explorer_gen.go#L88)):*
> ```Go
> // explore rule defined. The code is similar to this:
> //
> //   func (_e *explorer) exploreScan(_state *exploreState, _root memo.ExprID) (_fullyExplored bool) {
> ```

NIT: It'd be more consistent if we also renamed `_state` to `_rootState`, and `_scanExpr` to `_rootExpr`.

---

*[pkg/sql/opt/xform/explorer.go, line 198 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pE8u36Ww90dgI8sIB:-L8pE8u36Ww90dgI8sIC:buxnaro) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/xform/explorer.go#L198)):*
> ```Go
> }
> 
> //func (e *explorer) exploreSelect(selectState *exploreState, sel memo.ExprID) (fullyExplored bool) {
> ```

You can delete this, since you got Optgen generating the code correctly...

---

*[pkg/sql/opt/xform/explorer.go, line 288 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pFGHX-pLhp-xZpwTB:-L8pFGHX-pLhp-xZpwTC:bg0f719) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/xform/explorer.go#L288)):*
> ```Go
> // ----------------------------------------------------------------------
> 
> func (e *explorer) isUnconstrainedScan(def memo.PrivateID) bool {
> ```

NIT: could use a header comment

---

*[pkg/sql/opt/xform/explorer.go, line 293 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pFC7V4HHKK0fX0Ajg:-L8pFC7V4HHKK0fX0Ajh:b5mc4wm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/xform/explorer.go#L293)):*
> ```Go
> }
> 
> func (e *explorer) constrainScan(filterGroup memo.GroupID, scanDef memo.PrivateID) []memo.Expr {
> ```

NIT: could use a header comment that gives overview of what's going on in this logic

---

*[pkg/sql/opt/xform/explorer.go, line 298 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pFvm44401BsKBw3Uw:-L8pFvm44401BsKBw3Ux:b-phs5ij) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/xform/explorer.go#L298)):*
> ```Go
> 	scanOpDef := e.mem.LookupPrivate(scanDef).(*memo.ScanOpDef)
> 
> 	md := e.mem.Metadata()
> ```

NIT: I'd add a comment at the top of this block: `// Fill out data structures needed to initialize the idxconstraint library.`

---

*[pkg/sql/opt/xform/rules/select.opt, line 10 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pEw1wCsI6ErUyKLa7:-L8pEw1wCsI6ErUyKLa8:bnldy5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/xform/rules/select.opt#L10)):*
> ```
> # constrained Scan.
> [ConstrainScan, Explore]
> (Select (Scan $def:* & (IsUnconstrainedScan $def)) $filter:*)
> ```

NIT: I usually put ops with multiple args on multiple lines, just so they're easier to read:
```
(Select
  (Scan $def:* & (IsUnconstrainedScan $def))
  $filter:*
)
```

---

*[pkg/sql/opt/xform/testdata/physprops/ordering, line 72 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pGxB92uTZ0kWkXz_v:-L8pGxB92uTZ0kWkXz_w:b2ko212) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/xform/testdata/physprops/ordering#L72)):*
> ```
> # --------------------------------------------------
> 
> # Pass through ordering to scan operator that can support it.
> ```

These tests need to be updated so that the `SELECT` doesn't get pushed into the scan, since their purpose is to make sure we pass ordering through a SELECT op. Maybe update condition to something like `x=y` that won't get pushed down.

---

*[pkg/sql/opt/xform/testdata/physprops/ordering, line 151 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pHFDR0CpV7OAUSAgw:-L8pHFDR0CpV7OAUSAgx:b-l770lt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/xform/testdata/physprops/ordering#L151)):*
> ```
> # --------------------------------------------------
> 
> # Pass through ordering to scan operator that can support it.
> ```

Same goes with these tests.

---

*[pkg/sql/opt/xform/testdata/physprops/presentation, line 31 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pHJD7962sWgvRXGcL:-L8pHJD7962sWgvRXGcM:b4fi8kc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/xform/testdata/physprops/presentation#L31)):*
> ```
> SELECT a.y, a.x, a.y y2 FROM a WHERE x=1
> ----
> scan a,constrained
> ```

And these tests as well.

---

*[pkg/sql/opt/xform/testdata/rules/scan, line 135 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pHemmDHqdJI4H1ebD:-L8pHemmDHqdJI4H1ebE:b-lg0kex) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/xform/testdata/rules/scan#L135)):*
> ```
>  └── 1: (scan a)
> 
> optsteps
> ```

NIT: I've generally avoided checking in `optsteps` output, just because it's going to be very "fragile", meaning that almost any change will cause a diff, which is painful. I've tried to keep a few `optsteps` tests in "combo" for that reason, where I combine a bunch of operators and rules in just a few larger queries. I'm thinking we can have an interesting query there that pushes down Project, Select, and Limit into scans.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-:-L8pIeqY3_7XIiBB-aYO:b-72itnx)*

**Comment by andy-kimball** [comment]
Review status: 0 of 39 files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/memo/private_storage.go, line 179 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pT3w646C8DjH6Koo8:-L8pT3w646C8DjH6Koo9:b3dsps1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/memo/private_storage.go#L179)):*
> ```Go
> 	if def.Constraint != nil {
> 		// Use a delimiter since the col set is variable-length.
> 		ps.keyBuf.writeUvarint(0)
> ```

Why not write this value before `writeColSet`? If the pointer is nil, the uint64 will be 0, which will take up just 1 byte. We'll also eventually have HardLimit/SoftLimit fields, and I don't think we want to worry about trying to combine multiple optional fields. Let's just write them all to the buffer each time.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355)*

**Comment by petermattis** [comment]
Review status: 0 of 39 files reviewed at latest revision, 14 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/xform/testdata/rules/select, line 38 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8rEW9p8EdId13th-El:-L8rEW9p8EdId13th-Em:bp6xcza) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/xform/testdata/rules/select#L38)):*
> ```
> SELECT k FROM a WHERE k = 1
> ----
> [9: "p:k:1"]
> ```

Drive-by comment: it took me a while to track down what these lines were indicating. Can the root of the memo be indicated inline below? For example, `├── 9*: ...`. Or perhaps `* ├── 9: ...`, though you'd have to indent all of the memo lines then. The required props could then be output as `required: "..."`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/xform/testdata/rules/select, line 38 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8rEW9p8EdId13th-El:-L8rI1mm2TsAFc13gxEU:bb5382p) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/xform/testdata/rules/select#L38)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Drive-by comment: it took me a while to track down what these lines were indicating. Can the root of the memo be indicated inline below? For example, `├── 9*: ...`. Or perhaps `* ├── 9: ...`, though you'd have to indent all of the memo lines then. The required props could then be output as `required: "..."`.
</blockquote></details>

I think that for display purposes, we should topologically sort the memo and hide orphan groups (like 10 here). I agree the physical prop strings could be less cryptic too. I will explore these improvements in a separate PR.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/norm/testdata/bool, line 201 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pCA03BSKHhJDh6dK1:-L8rJ_sx7pyEMArHo6_y:b94wh9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/norm/testdata/bool#L201)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

It seems redundant to show "constrained" here when the constraint is also shown below.
</blockquote></details>

Right, but it's definitely needed in the `memo` view to distinguish from the unconstrained versions.. Should I add a flag for `formatPrivate`?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355)*

**Comment by petermattis** [comment]
Review status: 0 of 39 files reviewed at latest revision, 15 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/xform/testdata/rules/select, line 38 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8rEW9p8EdId13th-El:-L8rKBdx0CwEjWdqAMaA:b-eo3ds5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/xform/testdata/rules/select#L38)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think that for display purposes, we should topologically sort the memo and hide orphan groups (like 10 here). I agree the physical prop strings could be less cryptic too. I will explore these improvements in a separate PR.
</blockquote></details>

Ack. Definitely not for this PR.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355)*

**Comment by andy-kimball** [comment]
Review status: 0 of 39 files reviewed at latest revision, 15 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/norm/testdata/bool, line 201 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pCA03BSKHhJDh6dK1:-L8s9nZnAjndQkey3Nme:boot65g) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/norm/testdata/bool#L201)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Right, but it's definitely needed in the `memo` view to distinguish from the unconstrained versions.. Should I add a flag for `formatPrivate`?
</blockquote></details>

Hm, I see. Let's leave as-is for now, and see how we like it, or if we have other ideas later.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355)*

**Comment by RaduBerinde** [comment]
TFTR! Updated.

---

Review status: 0 of 39 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/exec/execbuilder/testdata/select, line 11 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pAnj76OCPvulrsDjg:-L8sDu3z-GuPd2uncLn7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/exec/execbuilder/testdata/select#L11)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I think it'd be good to have a few exec tests that are testing data types other than int, just to make sure they're working end-to-end.
</blockquote></details>

Done.

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 669 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pAyTm5X9R8pFfIo0_:-L8sDybn8wruKHtWvvTO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/idxconstraint/index_constraints.go#L669)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: need space before "calculates"
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/private_storage.go, line 179 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pT3w646C8DjH6Koo8:-L8sEAeS5fIsNNBRMeUi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/memo/private_storage.go#L179)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Why not write this value before `writeColSet`? If the pointer is nil, the uint64 will be 0, which will take up just 1 byte. We'll also eventually have HardLimit/SoftLimit fields, and I don't think we want to worry about trying to combine multiple optional fields. Let's just write them all to the buffer each time.
</blockquote></details>

Done.

---

*[pkg/sql/opt/optgen/cmd/optgen/explorer_gen.go, line 88 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pCpN21JxKqhIpSWze:-L8sdxbo2EkVrUCnarh5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/optgen/cmd/optgen/explorer_gen.go#L88)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: It'd be more consistent if we also renamed `_state` to `_rootState`, and `_scanExpr` to `_rootExpr`.
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/explorer.go, line 198 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pE8u36Ww90dgI8sIB:-L8sdyllCQjKrZaLmDoQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/xform/explorer.go#L198)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

You can delete this, since you got Optgen generating the code correctly...
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/explorer.go, line 288 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pFGHX-pLhp-xZpwTB:-L8seJaaCX5OkVXwjMda:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/xform/explorer.go#L288)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: could use a header comment
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/explorer.go, line 293 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pFC7V4HHKK0fX0Ajg:-L8sfXVo1OuxUZwNBJff:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/xform/explorer.go#L293)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: could use a header comment that gives overview of what's going on in this logic
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/explorer.go, line 298 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pFvm44401BsKBw3Uw:-L8sfkdX0TCuUVIUgH0q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/xform/explorer.go#L298)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: I'd add a comment at the top of this block: `// Fill out data structures needed to initialize the idxconstraint library.`
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/rules/select.opt, line 10 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pEw1wCsI6ErUyKLa7:-L8sfpWp49viYmM-DYi2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/xform/rules/select.opt#L10)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: I usually put ops with multiple args on multiple lines, just so they're easier to read:
```
(Select
  (Scan $def:* & (IsUnconstrainedScan $def))
  $filter:*
)
```
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/testdata/physprops/ordering, line 72 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pGxB92uTZ0kWkXz_v:-L8sgkfW5u_ggxy_EGUe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/xform/testdata/physprops/ordering#L72)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

These tests need to be updated so that the `SELECT` doesn't get pushed into the scan, since their purpose is to make sure we pass ordering through a SELECT op. Maybe update condition to something like `x=y` that won't get pushed down.
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/testdata/physprops/ordering, line 151 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pHFDR0CpV7OAUSAgw:-L8sgkB100k9nMyxb42K:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/xform/testdata/physprops/ordering#L151)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Same goes with these tests.
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/testdata/physprops/presentation, line 31 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pHJD7962sWgvRXGcL:-L8sgv-iEKuC4tDwYJPq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/xform/testdata/physprops/presentation#L31)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

And these tests as well.
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/testdata/rules/scan, line 135 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pHemmDHqdJI4H1ebD:-L8shWeW0rsDNb2_L2sr:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/xform/testdata/rules/scan#L135)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: I've generally avoided checking in `optsteps` output, just because it's going to be very "fragile", meaning that almost any change will cause a diff, which is painful. I've tried to keep a few `optsteps` tests in "combo" for that reason, where I combine a bunch of operators and rules in just a few larger queries. I'm thinking we can have an interesting query there that pushes down Project, Select, and Limit into scans.
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-:-L8sjVXF9MKycULwmjN3:b-p0fj95)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/xform/testdata/rules/select, line 44 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8srBFl-qWkt31ymAt2:-L8svWl42H3LiEDpZfC-:bjm1usr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e88949a6784b3e454348b889fdc3e34e860db46a/pkg/sql/opt/xform/testdata/rules/select#L44)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Probably a dumb question: Why is a new group created for (scan a) when group 1 already exists?
</blockquote></details>

We don't show the "needed columns" in the memo, but if we did, you'd see that the needed cols for group #8 are different than group #1. Changing the output columns changes the logical equivalence of the expression, so it has to go into a different group.

We do need work on the `memo` output format to try and make this and other things more clear. It's challenging to balance completeness with clarity, though.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355)*

**Comment by rytaft** [comment]
*[pkg/sql/opt/xform/testdata/rules/select, line 44 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8srBFl-qWkt31ymAt2:-L8swfBqADu-Rh8ldZLo:b39erxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e88949a6784b3e454348b889fdc3e34e860db46a/pkg/sql/opt/xform/testdata/rules/select#L44)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

We don't show the "needed columns" in the memo, but if we did, you'd see that the needed cols for group #8 are different than group #1. Changing the output columns changes the logical equivalence of the expression, so it has to go into a different group.

We do need work on the `memo` output format to try and make this and other things more clear. It's challenging to balance completeness with clarity, though.
</blockquote></details>

Got it - thanks for the explanation!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/xform/testdata/rules/scan, line 135 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355#-L8pHemmDHqdJI4H1ebD:-L8sxul2Aw9JgSRr_auw:bfj80th) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bebf897b6cddec29e08d219ff70a7bc5176ec2/pkg/sql/opt/xform/testdata/rules/scan#L135)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Removed.
</blockquote></details>

It's fine to leave this as an `opt` test, if you were trying to test something here.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24355)*

**Pull request merged**
