### PR TITLE
sql: backfills mark start/finish in system.jobs

### PR DESCRIPTION
**Pull request by jordanlewis**
This PR adds rudimentary start/finish tracking to distributed schema change backfills. Out for early review for comments on the approach - there are no tests yet, and backfill failures don't fail the corresponding system job.

This works by adding a job id to a mutation proto when its backfill begins.

### CODE REVIEW

**Comment by jordanlewis** [comment]
Example output in `crdb_internal.jobs`:

```
+--------------------+--------------+----------------------------------------------------------+----------+----------------+-----------+----------------------------------+---------+----------------------------------+----------------------------------+--------------------+-------+
|         id         |     type     |                       description                        | username | descriptor_ids |  status   |             created              | started |             finished             |             modified             | fraction_completed | error |
+--------------------+--------------+----------------------------------------------------------+----------+----------------+-----------+----------------------------------+---------+----------------------------------+----------------------------------+--------------------+-------+
| 245133730152546304 | ALTER TABLE  | ALTER TABLE change ADD COLUMN j INT NULL DEFAULT 1:::INT |          | {53}           | succeeded | 2017-05-15 20:14:37.609272+00:00 | NULL    | 2017-05-15 20:14:37.619996+00:00 | 2017-05-15 20:14:37.619996+00:00 |                  1 |       |
| 245151894257893376 | CREATE INDEX | CREATE UNIQUE INDEX ON change change_b_key (b ASC)       |          | {53}           | succeeded | 2017-05-15 21:47:00.853338+00:00 | NULL    | 2017-05-15 21:47:00.866374+00:00 | 2017-05-15 21:47:00.866374+00:00 |                  1 |       |
| 245151940451205120 | CREATE INDEX | CREATE INDEX ON change change_c_idx (c DESC)             |          | {53}           | succeeded | 2017-05-15 21:47:14.951321+00:00 | NULL    | 2017-05-15 21:47:14.960985+00:00 | 2017-05-15 21:47:14.960985+00:00 |                  1 |       |

**Comment by vivekmenezes** [comment]
Thanks for making this change. It's a great start! I like the way you've compiled the descriptions for the schema changes
and shown them clearly to the user in the jobs table. Awesome!

I think the main change I'd make is to create the job entry as soon as the mutation is created and add it to the SchemaChanger object. The main reason for doing it this way is because under varying circumstances the backfill
for the schema change can take minutes to run (a node is holding on to a lease) and if the job table entry for the schema
change is empty during the execution of the schema change state machine prior to the backfill, it will look odd. Besides, we could also later update the jobs table entry with the state of the schema change (not in this PR)  if that adds more information for the user.

Thanks!

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/sqlbase/structured.go, line 290 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-KkDyckGqDE9gZ6ZNy1R:-KkDyckHf0nmwqoqN1lf:b-75b0eg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e86288f51d0222e272117915d2e63e66dda39146/pkg/sql/sqlbase/structured.go#L290)):*
> ```Go
> 		}
> 		fmt.Fprintf(&buf, "%s %s", parser.Name(name), desc.ColumnDirections[i])
> 	}
> ```

probably better to use https://golang.org/pkg/strings/#Join here. You would need to create a slice of strings before calling join()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-:-KkE2oag3x7OIU0HU7sZ:b-anjqc8)*

**Comment by benesch** [comment]
Job stuff all looks right to me! Love the description. I probably should have called that column `query`. Oh well. :woman_scientist: :dog: on the rest.

---

Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 2 of 2 files at r3.
Review status: 2 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/backfill.go, line 412 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-KkSzyA8UqIQYSmK7wXm:-KkSzyA8UqIQYSmK7wXn:be77nap) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2f6f375cde99d613f830305efb658cedf61bbe2/pkg/sql/backfill.go#L412)):*
> ```Go
> 				mutation.JobID = jobLogger.jobID
> 				fmt.Println(mutation)
> 				fmt.Println(tableDesc)
> ```

These look like debug `Printlns` to me!

---

*[pkg/sql/backfill.go, line 523 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-KkSzrU_gIvIXMoyrPLC:-KkSzrU_gIvIXMoyrPLD:bqw9hpz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2f6f375cde99d613f830305efb658cedf61bbe2/pkg/sql/backfill.go#L523)):*
> ```Go
> 				jobLogger.JobID(), err)
> 		}
> 	}
> ```

Is `jobID` only nil in the case that someone started a schema change on an older version of Cockroach?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-:-KkT-I-_5gEUQRyzQDXU:b2ythlv)*

**Comment by benesch** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936)*

**Comment by jordanlewis** [comment]
@vivekmenezes, PTAL. I've moved the the job ids out of the mutation proto into a new MutationGroup proto on the table descriptor. Jobs are marked created as soon as the schema change statements are processed. They're marked started when the state machine begins to run, and progress an arbitrary 10% after the state machine is finished. They're marked complete when the backfill finishes.

If a backfill fails, the job is marked failed and a new "ROLL BACK" job is created and treated the same way as I described above.

To make this PR complete I'll need to thread the client transaction into the jobs executor and write some tests.

**Comment by vivekmenezes** [comment]
This is looking really great! thanks for putting this progress framework in. In terms of testing, I think you can add
some job table looks ups in some of the tests in schema_changer_test.go and check for expected jobs and states of jobs. I don't believe you will need any new tests. You can also modify the "purge" test to ensure that the rollback job gets added correctly and is marked completed.

Great stuff!

---

Review status: 0 of 15 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/create.go, line 206 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-Kkw9F2WEoG9caPYHh83:-Kkw9F2XM11bXpQR4M9h:b-3l74g) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0f599348e7e7cc139832b769cb4e4ced6aff11b/pkg/sql/create.go#L206)):*
> ```Go
> 	if err := n.p.createSchemaChangeJob(ctx, n.tableDesc, mutationID, parser.AsString(n.n)); err != nil {
> 		return err
> 	}
> ```

Can we create a method that calls both
```
 n.tableDesc.FinalizeMutation()
if err := n.p.createSchemaChangeJob(ctx, n.tableDesc, mutationID, parser.AsString(n.n)); err != nil {
		return err
	}
```

so that we're sure we're calling both of them, or perhaps we should call FinalizeMutation() within createSchemaChangejob()

---

*[pkg/sql/schema_changer.go, line 371 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-Kkx3UbdVo3ealqmrOvo:-Kkx3UbeOPSOyn9OIN7p:b-ob2f1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0f599348e7e7cc139832b769cb4e4ced6aff11b/pkg/sql/schema_changer.go#L371)):*
> ```Go
> 		// We are starting or resuming a schema change that never got a job for some
> 		// reason. Create a job - we don't have a good description for it at this
> 		// point, but that's okay as this should be a rare situation.
> ```

I think this schema change should just be rolled back. There isn't a reason why a job was not allocated, or a job was deleted by anther system resulting in the schema change getting into an inconsistent state. Better to just roll back.

---

*[pkg/sql/schema_changer.go, line 390 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-Kkx2y7wenzyWlX-9jvA:-Kkx2y7xU5HdYKjv-sYC:b-tbf2x3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0f599348e7e7cc139832b769cb4e4ced6aff11b/pkg/sql/schema_changer.go#L390)):*
> ```Go
> 	if err := sc.jobLogger.Started(ctx); err != nil {
> 		log.Warningf(ctx, "Failed to mark job %v as started: %v", sc.jobLogger.JobID(), err)
> 	}
> ```

Can you move the above code to a separate function

---

*[pkg/sql/schema_changer.go, line 664 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-Kkx4PS1R43m3BdOYz2h:-Kkx4PS1R43m3BdOYz2i:b-7m74ox) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0f599348e7e7cc139832b769cb4e4ced6aff11b/pkg/sql/schema_changer.go#L664)):*
> ```Go
> 				break
> 			}
> 		}
> ```

nice!

---

*[pkg/sql/sqlbase/structured.proto, line 536 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-KkwBYu5PCK65hC5c2do:-KkwBYu5PCK65hC5c2dp:b-z7kl81) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0f599348e7e7cc139832b769cb4e4ced6aff11b/pkg/sql/sqlbase/structured.proto#L536)):*
> ```protobuf
>   message MutationGroup {
>     // The mutation id of this mutation group.
>     optional uint32 mutation_id = 1 [(gogoproto.nullable) = false,
> ```

We might want to later run multiple mutations in the same job. Wanna make this a repeated field?

Actually perhaps we can rename this to Job rather than MutationGroup and then Job can hold a list of mutations, job checkpoints, job id etc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-:-Kkx4TYIqZAzw0z05PtC:b-ryuorw)*

**Comment by jordanlewis** [comment]
Review status: 0 of 15 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/backfill.go, line 412 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-KkSzyA8UqIQYSmK7wXm:-KkxjvA2Tc9FDhMg6S-h:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2f6f375cde99d613f830305efb658cedf61bbe2/pkg/sql/backfill.go#L412)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

These look like debug `Printlns` to me!
</blockquote></details>

Done.

---

*[pkg/sql/schema_changer.go, line 371 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-Kkx3UbdVo3ealqmrOvo:-KkxVs23ZMdwqGYZQ2Ia:bjxwfyq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0f599348e7e7cc139832b769cb4e4ced6aff11b/pkg/sql/schema_changer.go#L371)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I think this schema change should just be rolled back. There isn't a reason why a job was not allocated, or a job was deleted by anther system resulting in the schema change getting into an inconsistent state. Better to just roll back.
</blockquote></details>

There's (at least) one possible scenario that would cause this condition: if a schema change was occurring while we were upgrading to this new version of the code, and the coordinator was shut down or died.

Perhaps we should just include that in the version notes? e.g. Don't apply a schema change while upgrading to this version.

---

*[pkg/sql/sqlbase/structured.proto, line 536 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-KkwBYu5PCK65hC5c2do:-KkxWZo1EtxQ3BJlk8gx:b-71hpax) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0f599348e7e7cc139832b769cb4e4ced6aff11b/pkg/sql/sqlbase/structured.proto#L536)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

We might want to later run multiple mutations in the same job. Wanna make this a repeated field?

Actually perhaps we can rename this to Job rather than MutationGroup and then Job can hold a list of mutations, job checkpoints, job id etc
</blockquote></details>

I was hoping to keep this proto managing only a single mutation for now, since the bookkeeping is much simpler that way. The first step to coalescing backfills is to do both of the backfills *for a single mutation id* at once - for instance, doing both of the backfills for adding a column with a default *and* adding an index on that column. I don't think coalescing backfills across schema change boundaries is something that we're ready to do any time soon. Thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 15 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/schema_changer.go, line 371 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-Kkx3UbdVo3ealqmrOvo:-Kkztd_0tiXF06-8HOc5:b-6zt0oo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0f599348e7e7cc139832b769cb4e4ced6aff11b/pkg/sql/schema_changer.go#L371)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

There's (at least) one possible scenario that would cause this condition: if a schema change was occurring while we were upgrading to this new version of the code, and the coordinator was shut down or died.

Perhaps we should just include that in the version notes? e.g. Don't apply a schema change while upgrading to this version.
</blockquote></details>

yes we should add that to the release notes and not add this code. Besides we are rolling back the schema change so it's not that bad.

---

*[pkg/sql/sqlbase/structured.proto, line 536 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-KkwBYu5PCK65hC5c2do:-KkztKfKYbYZG_O2j2Hf:b-ezjo6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0f599348e7e7cc139832b769cb4e4ced6aff11b/pkg/sql/sqlbase/structured.proto#L536)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I was hoping to keep this proto managing only a single mutation for now, since the bookkeeping is much simpler that way. The first step to coalescing backfills is to do both of the backfills *for a single mutation id* at once - for instance, doing both of the backfills for adding a column with a default *and* adding an index on that column. I don't think coalescing backfills across schema change boundaries is something that we're ready to do any time soon. Thoughts?
</blockquote></details>

That's fine but I'd be happier if this were renamed Job because that's what it's holding

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936)*

**Comment by jordanlewis** [comment]
Review status: 0 of 17 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/create.go, line 206 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-Kkw9F2WEoG9caPYHh83:-Kl1gq_jqYSsNH5q7m6j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0f599348e7e7cc139832b769cb4e4ced6aff11b/pkg/sql/create.go#L206)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Can we create a method that calls both
```
 n.tableDesc.FinalizeMutation()
if err := n.p.createSchemaChangeJob(ctx, n.tableDesc, mutationID, parser.AsString(n.n)); err != nil {
		return err
	}
```

so that we're sure we're calling both of them, or perhaps we should call FinalizeMutation() within createSchemaChangejob()

</blockquote></details>

Done.

---

*[pkg/sql/schema_changer.go, line 371 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-Kkx3UbdVo3ealqmrOvo:-KlRPXTylXZcfpEiJWb6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0f599348e7e7cc139832b769cb4e4ced6aff11b/pkg/sql/schema_changer.go#L371)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

yes we should add that to the release notes and not add this code. Besides we are rolling back the schema change so it's not that bad.
</blockquote></details>

Done.

---

*[pkg/sql/sqlbase/structured.proto, line 536 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-KkwBYu5PCK65hC5c2do:-Kl1hHR1BcYtHYoe_-Hu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0f599348e7e7cc139832b769cb4e4ced6aff11b/pkg/sql/sqlbase/structured.proto#L536)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

That's fine but I'd be happier if this were renamed Job because that's what it's holding
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936)*

**Comment by jordanlewis** [comment]
@vivekmenezes PTAL - I wrote some tests via the logic framework instead of messing with the schema change tests.

**Comment by vivekmenezes** [comment]
Nice work on this PR! I like the way you've used logic tests to test this. My main comment is that I'd like us to 
transition the job table API to have a txn passed in so that we don't create jobs on failed higher level transactions

Thanks! Getting close to being merged.

---

Review status: 0 of 16 files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

*[pkg/sql/jobs.go, line 101 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-KlpwCOOxcW5KMbCQRHG:-KlpwCOPWOrUWhjvs7Mb:b-3uhwpo) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dec7e85a1f3d3e2ec8d05c13511376f1c06124f/pkg/sql/jobs.go#L101)):*
> ```Go
> 		jl.Job.Username = payload.Username
> 		jl.Job.DescriptorIDs = payload.DescriptorIDs
> 		jl.Job.Details = payload.Details
> ```

Can you get rid of this assignment by running the switch on payload.Details?

---

*[pkg/sql/jobs.go, line 250 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-Klpwj4h3r3DB8_nmhjw:-Klpwj4h3r3DB8_nmhjx:b-8wrh7o) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dec7e85a1f3d3e2ec8d05c13511376f1c06124f/pkg/sql/jobs.go#L250)):*
> ```Go
> 		return nil, err
> 	}
> ```

we expect 1 row right? How about checking that

---

*[pkg/sql/schema_changer.go, line 365 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-KlpxTRQo6QQtG71RqwK:-KlpxTRQo6QQtG71RqwL:b-m3hmue) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dec7e85a1f3d3e2ec8d05c13511376f1c06124f/pkg/sql/schema_changer.go#L365)):*
> ```Go
> 			break
> 		}
> 		mgIdx++
> ```

get rid of this?

---

*[pkg/sql/schema_changer.go, line 546 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-KlpyX-6bL7ldXNCGaxM:-KlpyX-6bL7ldXNCGaxN:b-jsjcwq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dec7e85a1f3d3e2ec8d05c13511376f1c06124f/pkg/sql/schema_changer.go#L546)):*
> ```Go
> 		}
> 		// Trim the executed mutation group from the descriptor.
> 		desc.MutationJobs = append(desc.MutationJobs[:i], desc.MutationJobs[i+1:]...)
> ```

move this to where the for loop  breaks above because it protects us from a situation where the job isn't found; also make the index i local

---

*[pkg/sql/schema_changer.go, line 549 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-KlpzC1L9uKfu2stBenJ:-KlpzC1L9uKfu2stBenK:b-bn50cs) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dec7e85a1f3d3e2ec8d05c13511376f1c06124f/pkg/sql/schema_changer.go#L549)):*
> ```Go
> 		return nil
> 	}, func(txn *client.Txn) error {
> 		if err := sc.jobLogger.Succeeded(ctx); err != nil {
> ```

I wish this took the txn the same way the EventLogger below takes the txn. That way they all succeed or fail together (atomic).

---

*[pkg/sql/schema_changer.go, line 657 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-Klq-DgJ5tg7PrF-bewP:-Klq-DgJ5tg7PrF-bewQ:b-wteb5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dec7e85a1f3d3e2ec8d05c13511376f1c06124f/pkg/sql/schema_changer.go#L657)):*
> ```Go
> 				if err := jobLogger.Started(ctx); err != nil {
> 					return err
> 				}
> ```

here again, the joblogger api would benefit from having a txn passed in. For example if this works and the higher layer transaction keeps failing we'll end up creating many jobs right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-:-Klq0QWorxfGWTVCoPzL:bip9ce3)*

**Comment by benesch** [comment]
Reviewed 15 of 15 files at r10.
Review status: 0 of 16 files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

*[pkg/sql/schema_changer.go, line 549 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-KlpzC1L9uKfu2stBenJ:-KlsqqCjiLbATZXRJR4D:b-3lrq0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dec7e85a1f3d3e2ec8d05c13511376f1c06124f/pkg/sql/schema_changer.go#L549)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I wish this took the txn the same way the EventLogger below takes the txn. That way they all succeed or fail together (atomic).
</blockquote></details>

I'm :+1: on this, but I think you'll have to create two versions of the API (`Created` and `CreatedInTxn`, or similar) to avoid littering `db.Txn`s all over the sqlccl codebase. :/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936)*

**Comment by jordanlewis** [comment]
Review status: 0 of 16 files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

*[pkg/sql/jobs.go, line 101 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-KlpwCOOxcW5KMbCQRHG:-KlstJrf8Kigfc9h_6Un:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dec7e85a1f3d3e2ec8d05c13511376f1c06124f/pkg/sql/jobs.go#L101)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Can you get rid of this assignment by running the switch on payload.Details?
</blockquote></details>

Done.

---

*[pkg/sql/jobs.go, line 250 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-Klpwj4h3r3DB8_nmhjw:-KlssqGy9QlFJdWPYM28:b-f2gauk) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dec7e85a1f3d3e2ec8d05c13511376f1c06124f/pkg/sql/jobs.go#L250)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

we expect 1 row right? How about checking that
</blockquote></details>

I'll do this in the upcoming PR to add txns to the job logger.

---

*[pkg/sql/schema_changer.go, line 365 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-KlpxTRQo6QQtG71RqwK:-Klsr6Gl5hcUxyBt_Pv8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dec7e85a1f3d3e2ec8d05c13511376f1c06124f/pkg/sql/schema_changer.go#L365)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

get rid of this?
</blockquote></details>

Done.

---

*[pkg/sql/schema_changer.go, line 546 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-KlpyX-6bL7ldXNCGaxM:-KlssZthSZKAs2naRJDp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dec7e85a1f3d3e2ec8d05c13511376f1c06124f/pkg/sql/schema_changer.go#L546)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

move this to where the for loop  breaks above because it protects us from a situation where the job isn't found; also make the index i local
</blockquote></details>

Done.

---

*[pkg/sql/schema_changer.go, line 549 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-KlpzC1L9uKfu2stBenJ:-Klsr9M-iVNB9gAJonG7:bjhqd89) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dec7e85a1f3d3e2ec8d05c13511376f1c06124f/pkg/sql/schema_changer.go#L549)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I'm :+1: on this, but I think you'll have to create two versions of the API (`Created` and `CreatedInTxn`, or similar) to avoid littering `db.Txn`s all over the sqlccl codebase. :/
</blockquote></details>

Yeah - I have a TODO about that. I'd prefer to merge this and then add the txn threading to job logger in a separate PR since this one is getting large!

---

*[pkg/sql/schema_changer.go, line 657 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-Klq-DgJ5tg7PrF-bewP:-KlsrDkVAjxzv1nbTgyw:b-7xtei2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dec7e85a1f3d3e2ec8d05c13511376f1c06124f/pkg/sql/schema_changer.go#L657)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

here again, the joblogger api would benefit from having a txn passed in. For example if this works and the higher layer transaction keeps failing we'll end up creating many jobs right?
</blockquote></details>

Yeah.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936)*

**Comment by vivekmenezes** [comment]
I'm cool with not adding txn to the job logger interface in this PR, but please create an issue so that we don't miss it. Thanks!

**Comment by vivekmenezes** [comment]
LGTM

**Comment by jordanlewis** [comment]
TFTRs! I've already got a PR for the job logger interface update, I'll just submit that in the morning.

**Comment by jordanlewis** [comment]
On second thought, I don't think that it's that useful here to have control over the transaction that the jobs API uses. That's because, most of the time, schema changes don't have a well-defined transaction that they're in - schema changes occur over many disparate transactions, so the progress reporting does as well.

There's one circumstance where we do have a relevant transaction,

---

Review status: 0 of 16 files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

*[pkg/sql/jobs.go, line 250 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-Klpwj4h3r3DB8_nmhjw:-KlyKbuBzgEt3qDobkDP:blnrn64) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dec7e85a1f3d3e2ec8d05c13511376f1c06124f/pkg/sql/jobs.go#L250)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I'll do this in the upcoming PR to add txns to the job logger.
</blockquote></details>

Actually, this is already done because we use the QueryRow API which returns an error if there's more than one row.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-:-KluPEizf6i7Uf8q6qul:b-ni3j7q)*

**Comment by benesch** [comment]
Yeah, that's where we landed on `BACKUP`/`RESTORE`, which are similarly split over many transactions.

Is the one circumstance with a relevant transaction the place where you might end up creating multiple jobs if the txn needs to be retried?

---

Review status: 0 of 16 files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-:-KlyV4RjdPW5LZK1tPCr:b-5q3khq)*

**Comment by jordanlewis** [comment]
Er. Yes. Apparently I clicked submit before finishing my thought.

---

Review status: 0 of 16 files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15936#-:-Klz8WGKtDWMeK2JKbFS:b-yxahg6)*

**Pull request merged**
