### PR TITLE
ui: add average number of runnable goroutines to the runtime graphs

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### util: introduce goschedstats

This commit adds an util package which sets up a background job which
monitors the average number of runnable goroutines per CPU. It exposes
functions to retrieve a cumulative sum and a recent moving average of
the value.

Release note: None

#### ui: add average number of runnable goroutines to the runtime graphs

Release note (UI change): a new metric for the average number of
runnable goroutines per CPU is now present in the runtime graphs.

----

I ran tpccbench a bunch of times to make sure there is no regression due to the overhead of maintaining this stat. I saw no difference in the max warehouses with and without this change.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
___
*[pkg/util/goschedstats/runnable.go, line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64149#-MZ-QXRV3rBof9iNtz22:-MZ-QXRV3rBof9iNtz23:bhi4bhi) ([raw file](https://github.com/cockroachdb/cockroach/blob/014cc42f7c69d5698bd590ce09c987183641eba3/pkg/util/goschedstats/runnable.go#L43)):*
> ```Go
> // calculated once per second. This function returns an exponentially weighted
> // moving average of these values.
> func RecentNormalizedRunnableGoroutines() float64 {
> ```

@sumeerbhola this is intended to be used directly as an overload signal. What do you think?

**Review by ajwerner — COMMENTED** [review]
My initial reaction to this is that it's very static in terms of both the sampling rate, the reporting interval, and the moving average decay config. I feel like this could be abstracted out a bit more to use some of our more standard machinery like cluster settings. Perhaps that would imply making this too dynamic and re-working the rates while running could be painful. Another option is environment variables.

> Reviewed 1 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64149#-:-MZ-DvkPBGbRAwu9bari:b4pu03y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
Nice!

> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 3 of 8 files at r4, 3 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64149#-:-MZEu0GS96dso4UioBfy:bwuv9u3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @RaduBerinde)

___
*[pkg/util/goschedstats/runnable.go, line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64149#-MZ-QXRV3rBof9iNtz22:-MZEn2kW4Sh9CdTprkUG:b-4aq4v1) ([raw file](https://github.com/cockroachdb/cockroach/blob/014cc42f7c69d5698bd590ce09c987183641eba3/pkg/util/goschedstats/runnable.go#L43)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

@sumeerbhola this is intended to be used directly as an overload signal. What do you think?
</blockquote></details>

I'm inclined towards the slot adjustment logic consuming the per-ms-tick signal directly, via registering a handler that is called with `(runnable int, maxProcs int)` -- that is what I used in my experiments. It is possible that the smoothed signal works well enough with CockroachDB -- I didn't try it because experience from a past life had shown that it was too slow to adjust and would overshoot more in either direction.
It's fine if you want to leave it like this for now. I can later collect some data to see it this works as well as the raw signal.
 
___
*[pkg/util/goschedstats/runnable.go, line 52 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64149#-MZEJAkMBHnUwLzBqf15:-MZEJAkMBHnUwLzBqf16:b-anffsy) ([raw file](https://github.com/cockroachdb/cockroach/blob/731d9db20f246269ca01e7fc8d2cd3969bba1140/pkg/util/goschedstats/runnable.go#L52)):*
> ```Go
> // and averaging over GOMAXPROCS.
> func normalize(rawValue uint64) float64 {
> 	procs := runtime.GOMAXPROCS(0)
> ```

I am assuming GOMAXPROCS can change, say due to vertical auto-scaling. If so, we should be normalizing early. I think we could sample it with every tick (see comment in `runtime_go1.15.go`) and keep a running scaled sum that we could divide by here. Any maybe then instead of 3 atomics we can just use a mutex which will ensure consistency of `totalRunnable` and `totalMaxProcs`.
___
*[pkg/util/goschedstats/runnable.go, line 69 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64149#-MZEjp5805barnjcKrA0:-MZEjp5805barnjcKrA1:b-9kysck) ([raw file](https://github.com/cockroachdb/cockroach/blob/731d9db20f246269ca01e7fc8d2cd3969bba1140/pkg/util/goschedstats/runnable.go#L69)):*
> ```Go
> const reportingPeriod = time.Second
> 
> const scale = 1000
> ```

could this be more clearly stated as `const scale = time.Second/time.Millisecond`?
___
*[pkg/util/goschedstats/runnable.go, line 93 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64149#-MZEkcP38XRIg8h3UclJ:-MZEkcP38XRIg8h3UclK:blzs3wj) ([raw file](https://github.com/cockroachdb/cockroach/blob/731d9db20f246269ca01e7fc8d2cd3969bba1140/pkg/util/goschedstats/runnable.go#L93)):*
> ```Go
> 		for {
> 			t := <-ticker.C
> 			if t.Sub(lastTime) > reportingPeriod || t.Before(lastTime) {
> ```

I didn't understand the `t.Before(lastTime)` part? Is this for a non-monotonic clock? If yes, it could use a code comment.
___
*[pkg/util/goschedstats/runnable.go, line 95 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64149#-MZElElBApGYaj59_pam:-MZElElBApGYaj59_pan:b-y97bno) ([raw file](https://github.com/cockroachdb/cockroach/blob/731d9db20f246269ca01e7fc8d2cd3969bba1140/pkg/util/goschedstats/runnable.go#L95)):*
> ```Go
> 			if t.Sub(lastTime) > reportingPeriod || t.Before(lastTime) {
> 				if numSamples > 0 {
> 					lastVal := uint64(sum * scale / numSamples)
> ```

I think it would be useful to have a code comment here to explain why we don't simply do `lastVal := sum`. Something like: `(sum/numSamples)` is the mean across the samples, and the number of samples is going to typically be close to `scale`. We explicitly multiply by `scale` so that we minimize the effect of rounding caused by storing in an int, and to equally weight the contributions across reporting periods (`sum` is weighted by `numSamples` which can vary across reporting periods). 
___
*[pkg/util/goschedstats/runtime_go1.15.go, line 138 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64149#-MZEssql6Ym6PSy3tlZn:-MZEssql6Ym6PSy3tlZo:bcnqjhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/731d9db20f246269ca01e7fc8d2cd3969bba1140/pkg/util/goschedstats/runtime_go1.15.go#L138)):*
> ```Go
> 
> func numRunnableGoroutines() int {
> 	lock(&sched.lock)
> ```

since we are holding the `sched.lock` here, it seems a good place to grab `len(allp)` which is documented as being the same as `runtime.gomaxprocs`

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64149)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @sumeerbhola)

___
*[pkg/util/goschedstats/runnable.go, line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64149#-MZ-QXRV3rBof9iNtz22:-MZF6h7R1z7jS4IoSMaq:blmkich) ([raw file](https://github.com/cockroachdb/cockroach/blob/014cc42f7c69d5698bd590ce09c987183641eba3/pkg/util/goschedstats/runnable.go#L43)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'm inclined towards the slot adjustment logic consuming the per-ms-tick signal directly, via registering a handler that is called with `(runnable int, maxProcs int)` -- that is what I used in my experiments. It is possible that the smoothed signal works well enough with CockroachDB -- I didn't try it because experience from a past life had shown that it was too slow to adjust and would overshoot more in either direction.
It's fine if you want to leave it like this for now. I can later collect some data to see it this works as well as the raw signal.
 
</blockquote></details>

See this [comment](https://github.com/golang/go/issues/15490#issuecomment-471818523). Given that there are reports that the signal can fluctuate dramatically even under normal load, I do think we should be smoothing it.

I don't think sub-second reaction times is an important goal.
___
*[pkg/util/goschedstats/runnable.go, line 52 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64149#-MZEJAkMBHnUwLzBqf15:-MZF7kZ52ip2fCZXODX1:b9isomq) ([raw file](https://github.com/cockroachdb/cockroach/blob/731d9db20f246269ca01e7fc8d2cd3969bba1140/pkg/util/goschedstats/runnable.go#L52)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I am assuming GOMAXPROCS can change, say due to vertical auto-scaling. If so, we should be normalizing early. I think we could sample it with every tick (see comment in `runtime_go1.15.go`) and keep a running scaled sum that we could divide by here. Any maybe then instead of 3 atomics we can just use a mutex which will ensure consistency of `totalRunnable` and `totalMaxProcs`.
</blockquote></details>

I think we change it at most once during server startup. But I'll try your suggestion, we could just divide  by it on every sample.
___
*[pkg/util/goschedstats/runnable.go, line 69 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64149#-MZEjp5805barnjcKrA0:-MZF7wGl-tKR5uAdKwJ6:bh6739k) ([raw file](https://github.com/cockroachdb/cockroach/blob/731d9db20f246269ca01e7fc8d2cd3969bba1140/pkg/util/goschedstats/runnable.go#L69)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

could this be more clearly stated as `const scale = time.Second/time.Millisecond`?
</blockquote></details>

I don't think it has anything to do with that, it could be 100 or 10000 just the same, it's just how many decimals of precision we want. I don't think we care too much about more than one digit or two.

**Comment by RaduBerinde** [comment]
I don't think making things configurable from the get-go is worthwhile work. I don't expect the specific settings to matter too much. We can add some knobs if/when necessary.

**Review by RaduBerinde — COMMENTED** [review]
TFTRs! Updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64149#-:-MZGihic9-etzB0deii3:b-u8hs9c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/util/goschedstats/runnable.go, line 93 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64149#-MZEkcP38XRIg8h3UclJ:-MZGdGlR8oPE1Y9tFyZQ:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/731d9db20f246269ca01e7fc8d2cd3969bba1140/pkg/util/goschedstats/runnable.go#L93)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I didn't understand the `t.Before(lastTime)` part? Is this for a non-monotonic clock? If yes, it could use a code comment.
</blockquote></details>

Removed.
___
*[pkg/util/goschedstats/runnable.go, line 95 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64149#-MZElElBApGYaj59_pam:-MZGgc7xCiFavIDfH8hG:bnmq5wb) ([raw file](https://github.com/cockroachdb/cockroach/blob/731d9db20f246269ca01e7fc8d2cd3969bba1140/pkg/util/goschedstats/runnable.go#L95)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think it would be useful to have a code comment here to explain why we don't simply do `lastVal := sum`. Something like: `(sum/numSamples)` is the mean across the samples, and the number of samples is going to typically be close to `scale`. We explicitly multiply by `scale` so that we minimize the effect of rounding caused by storing in an int, and to equally weight the contributions across reporting periods (`sum` is weighted by `numSamples` which can vary across reporting periods). 
</blockquote></details>

Update the code a bit and added a comment.
___
*[pkg/util/goschedstats/runtime_go1.15.go, line 138 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64149#-MZEssql6Ym6PSy3tlZn:-MZGgj-U2QwO9A8aR8Lp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/731d9db20f246269ca01e7fc8d2cd3969bba1140/pkg/util/goschedstats/runtime_go1.15.go#L138)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

since we are holding the `sched.lock` here, it seems a good place to grab `len(allp)` which is documented as being the same as `runtime.gomaxprocs`
</blockquote></details>

Done.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 8 files at r6, 5 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64149#-:-MZNqHN06Q4yXugspAwr:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @sumeerbhola)

___
*[pkg/util/goschedstats/runnable.go, line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64149#-MZ-QXRV3rBof9iNtz22:-MZNjCiY8JYe0VOrgGlO:bwhl51r) ([raw file](https://github.com/cockroachdb/cockroach/blob/014cc42f7c69d5698bd590ce09c987183641eba3/pkg/util/goschedstats/runnable.go#L43)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

See this [comment](https://github.com/golang/go/issues/15490#issuecomment-471818523). Given that there are reports that the signal can fluctuate dramatically even under normal load, I do think we should be smoothing it.

I don't think sub-second reaction times is an important goal.
</blockquote></details>

Thanks for the link. The phrasing there is interesting
"it seemed that since goroutines are so cheap (compared to, say, using runnable threads as a load indicator), the runnable goroutine count often fluctuated dramatically, even when the system was under normal load. It was common to see a huge number of goroutines newly started or woken that would exit or sleep almost immediately once run."

It suggests that runnable threads have been successfully used as a load indicator in some settings. I suspect success of this approach depends on the system architecture and workload of the system implemented in golang, and not something inherent in golang. My (incomplete) understanding is that we are doing a goroutine per request, which is not unlike a thread (drawn from a threadpool, which is usually sized fairly large) per request model.
___
*[pkg/util/goschedstats/runnable.go, line 69 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64149#-MZEjp5805barnjcKrA0:-MZNmNel4NByuY0H155t:bcx1g94) ([raw file](https://github.com/cockroachdb/cockroach/blob/731d9db20f246269ca01e7fc8d2cd3969bba1140/pkg/util/goschedstats/runnable.go#L69)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't think it has anything to do with that, it could be 100 or 10000 just the same, it's just how many decimals of precision we want. I don't think we care too much about more than one digit or two.
</blockquote></details>

Ack. I was guessing you didn't want to lose any precision, since `scale` happened to be the same as the number of samples in a second.
___
*[pkg/util/goschedstats/runnable.go, line 69 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/64149#-MZNmp878ziQyLyyi2nh:-MZNmp878ziQyLyyi2ni:b-spqlgv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b073a5ef53934f70e36011e174880ff1c8fb10a9/pkg/util/goschedstats/runnable.go#L69)):*
> ```Go
> 
> // total accumulates the sum of the average number of runnable goroutines per
> // CPU, multiplied by toFixedPoint.
> ```

Perhaps the comment should also say that the average is computed per reporting period.
Same below for `ewma`.

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64149#-:-MZPQtovA7dszcPksFIm:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @sumeerbhola)

___
*[pkg/util/goschedstats/runnable.go, line 69 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/64149#-MZNmp878ziQyLyyi2nh:-MZPQt4i4x18H0B42iOo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b073a5ef53934f70e36011e174880ff1c8fb10a9/pkg/util/goschedstats/runnable.go#L69)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Perhaps the comment should also say that the average is computed per reporting period.
Same below for `ewma`.
</blockquote></details>

Done.

**Pull request merged**
