### PR TITLE
logstore: pool allocations for logAppend

### PR DESCRIPTION
**Pull request by tbg**
This adds a benchmark appending a preallocated single 256kb entry to the log, and then optimizes it.

    $ benchdiff ./pkg/kv/kvserver/logstore --count 5 --old ... --post-checkout './dev gen go'
    name                                    old time/op    new time/op    delta
    LogStore_StoreEntries/bytes=256_KiB-24     140µs ± 8%      49µs ± 2%   -64.96%  (p=0.008 n=5+5)
    LogStore_StoreEntries/bytes=512_KiB-24     295µs ± 5%     137µs ± 2%   -53.44%  (p=0.008 n=5+5)
    LogStore_StoreEntries/bytes=1.0_KiB-24    2.35µs ± 2%    1.71µs ± 1%   -27.31%  (p=0.008 n=5+5)
    LogStore_StoreEntries/bytes=2.0_MiB-24    3.49ms ± 5%    2.68ms ± 5%   -23.08%  (p=0.008 n=5+5)
    LogStore_StoreEntries/bytes=1.0_MiB-24    1.43ms ± 5%    1.15ms ± 5%   -19.80%  (p=0.008 n=5+5)

    name                                    old alloc/op   new alloc/op   delta
    LogStore_StoreEntries/bytes=256_KiB-24     274kB ± 0%       0kB ±22%   -99.91%  (p=0.008 n=5+5)
    LogStore_StoreEntries/bytes=512_KiB-24     555kB ± 0%       1kB ± 6%   -99.87%  (p=0.008 n=5+5)
    LogStore_StoreEntries/bytes=1.0_KiB-24    1.31kB ± 0%    0.16kB ± 0%   -88.05%  (p=0.008 n=5+5)
    LogStore_StoreEntries/bytes=1.0_MiB-24    3.50MB ± 1%    2.23MB ± 1%   -36.26%  (p=0.008 n=5+5)
    LogStore_StoreEntries/bytes=2.0_MiB-24    6.97MB ± 1%    4.64MB ± 1%   -33.45%  (p=0.008 n=5+5)

    name                                    old allocs/op  new allocs/op  delta
    LogStore_StoreEntries/bytes=1.0_KiB-24      1.00 ± 0%      0.00       -100.00%  (p=0.008 n=5+5)
    LogStore_StoreEntries/bytes=256_KiB-24      1.00 ± 0%      0.00       -100.00%  (p=0.008 n=5+5)
    LogStore_StoreEntries/bytes=512_KiB-24      1.00 ± 0%      0.00       -100.00%  (p=0.008 n=5+5)
    LogStore_StoreEntries/bytes=1.0_MiB-24      5.00 ± 0%      4.00 ± 0%   -20.00%  (p=0.008 n=5+5)
    LogStore_StoreEntries/bytes=2.0_MiB-24      6.00 ± 0%      5.00 ± 0%      ~     (p=0.079 n=4+5)

Epic: none
Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93495#-:-NJBK65c5H569kvvQQT2:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @pavelkalinnikov and @tbg)

___
*[`pkg/kv/kvserver/logstore/logstore.go` line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93495#-NJBC3yy3bVR1ypW5foV:-NJBC3yy3bVR1ypW5foW:bee4aho) ([raw file](https://github.com/cockroachdb/cockroach/blob/77b96ab122a0153abd17836c83f59324b7b24c45/pkg/kv/kvserver/logstore/logstore.go#L108)):*
> ```Go
> 	// TODO(pavelkalinnikov): Doesn't this comment contradict the code?
> 	// Use a more efficient write-only batch because we don't need to do any
> 	// reads from the batch. Any reads are performed on the underlying DB.
> ```

This is creating an unindexed, read-write batch. It shouldn't be any less efficient than an unindexed write-only batch. The indexing of writes added to the batch is the part that adds work to each write.
___
*[`pkg/kv/kvserver/logstore/logstore.go` line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93495#-NJBCsvy83zmE4gXmxHT:-NJBCsvy83zmE4gXmxHU:bnvwgt8) ([raw file](https://github.com/cockroachdb/cockroach/blob/77b96ab122a0153abd17836c83f59324b7b24c45/pkg/kv/kvserver/logstore/logstore.go#L123)):*
> ```Go
> }
> 
> type batchI interface {
> ```

This is nearly all of the `storage.Batch` interface and its implementations each implement all of `storage.Batch`. Why split it out instead of using `storage.Batch` directly?
___
*[`pkg/kv/kvserver/logstore/logstore.go` line 253 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93495#-NJBJESTD2ryJPlypRTs:-NJBJESUCivYQZaFMaqu:b-5iyfx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3eab61de5658b766edd4b88c2f464aadf691519/pkg/kv/kvserver/logstore/logstore.go#L253)):*
> ```Go
> 	}
> 	var diff enginepb.MVCCStats
> 	// At the time of writing, `var value roachpb.Value` moves to the heap
> ```

This was when you were trying to pool the RawBytes slice? Are you sure `value` was escaping, and not the 24-byte slice header when sticking it inside of an interface? If you wanted to go that route, you might have needed to pool a `*[]byte`.

What you have here is easier to reason about, so let's keep it. But maybe resolve the uncertainty in the comment so that it doesn't calcify and dissuade future engineers from improving things further.
___
*[`pkg/kv/kvserver/logstore/logstore_bench_test.go` line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93495#-NJBLeH21XHG1JJWJUob:-NJBLeH21XHG1JJWJUoc:bjw8fs6) ([raw file](https://github.com/cockroachdb/cockroach/blob/77b96ab122a0153abd17836c83f59324b7b24c45/pkg/kv/kvserver/logstore/logstore_bench_test.go#L61)):*
> ```Go
> 	}
> 	var ents []raftpb.Entry
> 	data := make([]byte, 256*1024)
> ```

Consider adding a few variants of this benchmark with different sizes. You should see an additional heap allocation once the entry size exceeds Pebble's `batchMaxRetainedSize` of 1MB.

**Comment by pavelkalinnikov** [comment]
Since this path interacts with storage, how significant is this optimization on a relative scale?

**Review by tbg — COMMENTED** [review]
> Since this path interacts with storage, how significant is this optimization on a relative scale?

This kind of stuff tends to show up end-to-end because these are allocations in the hot path whose size is also determined by the input data.

See https://github.com/cockroachdb/cockroach/pull/91930 for comparable improvements where some allocations were removed.

These benchmarks tend not to capture a second-order improvement, which is that there is less GC.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93495#-:-NJRf-XwBs1gYO3swBmg:bypoyny)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten and @pavelkalinnikov)

___
*[`pkg/kv/kvserver/logstore/logstore.go` line 253 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93495#-NJBJESTD2ryJPlypRTs:-NJRbpt-1zDI-Tc6bmn-:b9iap5d) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3eab61de5658b766edd4b88c2f464aadf691519/pkg/kv/kvserver/logstore/logstore.go#L253)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This was when you were trying to pool the RawBytes slice? Are you sure `value` was escaping, and not the 24-byte slice header when sticking it inside of an interface? If you wanted to go that route, you might have needed to pool a `*[]byte`.

What you have here is easier to reason about, so let's keep it. But maybe resolve the uncertainty in the comment so that it doesn't calcify and dissuade future engineers from improving things further.
</blockquote></details>

Ah you're right. Removing comment.
___
*[`pkg/kv/kvserver/logstore/logstore_bench_test.go` line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93495#-NJBLeH21XHG1JJWJUob:-NJRcKMe5NXH5JQOmkO8:b-q6drav) ([raw file](https://github.com/cockroachdb/cockroach/blob/77b96ab122a0153abd17836c83f59324b7b24c45/pkg/kv/kvserver/logstore/logstore_bench_test.go#L61)):*
Done.

```
BenchmarkLogStore_StoreEntries/bytes=1.0_KiB-10         	 1226732	       979.4 ns/op	     157 B/op	       0 allocs/op
BenchmarkLogStore_StoreEntries/bytes=256_KiB-10         	   25400	     48469 ns/op	     181 B/op	       0 allocs/op
BenchmarkLogStore_StoreEntries/bytes=512_KiB-10         	   12883	     93272 ns/op	     456 B/op	       0 allocs/op
BenchmarkLogStore_StoreEntries/bytes=1.0_MiB-10         	    4563	    252330 ns/op	 2236958 B/op	       3 allocs/op
BenchmarkLogStore_StoreEntries/bytes=2.0_MiB-10         	    2458	    477234 ns/op	 4463532 B/op	       4 allocs/op
```

The extra allocs are interesting, didn't know about this path in `sync.Pool` if interrupted by GC.



> batchMaxRetainedSize

I've noticed this one in other work. Is this reasonable? A sync.Pool is discarded on each GC, isn't it? The comments around this limit speak of a fear of holding large allocations alive forever, but this wouldn't be the case. I supposed it hypothetically could be, if it's pulled out of the pool before each GC and only put back after.

**Comment by tbg** [comment]
bors r=nvanbenschoten

**Comment by tbg** [comment]
bors r=nvanbenschoten

**Pull request merged**
