### PR TITLE
ui: Cypress testing library integration

### LINKED ISSUE #46315: ui: add cypress testing library to Admin UI and test decommissioned nodes list
We've seen that the cypress testing library can be a great tool for e2e testing of the database.

This issue is for exploring the ability of cypress test scripts to also run a local cockroach cluster and test complex functionality like decommissioning nodes in a large cluster.

The goal is to have a single cypress test script that, when run, spins up a cluster with, say, 6 nodes, verifies that all nodes show up as "Live" on the overview page, then decommissions a few nodes, one at a time, and confirms that they get labeled properly on the overview page as "decommissioned"

### PR DESCRIPTION
**Pull request by koorosh**
Depends on: https://github.com/cockroachdb/yarn-vendored/pull/18
Resolves: #46315

How to start tests: `yarn run cypress open`

- Add cypress library
- First e2e test on decommissioning node
and how Node overview list updates its state.

Integration of cypress library requires to setup
webpack, typescript and pre processing plugin to
make it work. All of this routine is isolated in
./cypress directory.

To interact with `roachprod`, Makefile is added as
abstraction level and a pool of available commands.
`./cypress/support/commands.ts` has custom Cypress
functions which execute make commands.

Cypress.get function is extended with custom logic
to provide custom log messages in Cypress logging
panel instead of logging CSS selectors.

And one more mention about test case, here is
main logic it validates:
- starts cluster with 4 nodes
- validates that all nodes are live
- decommission one node, and stop it
- check that 3 live and 1 node is Decommissioning
- wait while unavailable node is become decommissioned
- check that decommissioned node is shown in
Decommissioned nodes table

Release note: None

Release justification: non-production code changes

### CODE REVIEW

**Review by dhartunian — CHANGES_REQUESTED** [review]
Looks great, I think we're almost there. Just want to clarify how we can tie the locally running app to proxy the roachprod cluster. Maybe I'm missing something here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46688#-:-M4Vryn13-aMZs2TxOhg:b-ki0sgg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh)

___
*[pkg/ui/cypress.json, line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46688#-M4VkoezBRGOSSC2xjDK:-M4Vkof-8f2LbnVYY0jR:bb3tid) ([raw file](https://github.com/cockroachdb/cockroach/blob/12da6685fb721f9ab479f941914dbe3683a2900a/pkg/ui/cypress.json#L3)):*
> ```JSON
> {
>   "supportFile": "cypress/support/index.ts",
>   "baseUrl": "http://localhost:3000"
> ```

This is not running against the roachprod cluster, right? I'm not sure where the proxying to the roachprod cluster is happening.

**Comment by koorosh** [comment]
> Looks great, I think we're almost there. Just want to clarify how we can tie the locally running app to proxy the roachprod cluster. Maybe I'm missing something here.
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46688#-:-M4Vryn13-aMZs2TxOhg:b-ki0sgg)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh)
> 
> _[pkg/ui/cypress.json, line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46688#-M4VkoezBRGOSSC2xjDK:-M4Vkof-8f2LbnVYY0jR:bb3tid) ([raw file](https://github.com/cockroachdb/cockroach/blob/12da6685fb721f9ab479f941914dbe3683a2900a/pkg/ui/cypress.json#L3)):_
> 
> > ```json
> > {
> >   "supportFile": "cypress/support/index.ts",
> >   "baseUrl": "http://localhost:3000"
> > ```
> 
> This is not running against the roachprod cluster, right? I'm not sure where the proxying to the roachprod cluster is happening.

It relies on roachprod as a server side, but it interacts with client started for local development (with `ui-watch` for example which is proxied to `roachprod`).

**Review by dhartunian — APPROVED** [review]
> Reviewed 1 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46688)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

**Pull request merged**
