### PR TITLE
sql: extend DROP DATABASE with an optional RESTRICT/CASCADE

### PR DESCRIPTION
**Pull request by knz**
Prior to this patch, `DROP DATABASE` would always imply `CASCADE`.
This patch makes `RESTRICT` the default, and allows the user
to override this default.

This change also removes DROP DATABASE from the list of statements protected with `sql_safe_updates`.

Initially suggested by @a-robinson in https://github.com/cockroachdb/cockroach/issues/3943#issuecomment-253023121
Additionally motivated in https://github.com/cockroachdb/cockroach/pull/17889#issuecomment-324661760

cc @bdarnell

### CODE REVIEW

**Comment by a-robinson** [comment]
:lgtm:

---

Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/database, line 102 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17926#-Ks_4HBsmmws0yEbg2sH:-Ks_4HBsmmws0yEbg2sI:bulq4w1) ([raw file](https://github.com/cockroachdb/cockroach/blob/566f2ccc79be5ea11fbb703fffe4997a8c50e124/pkg/sql/logictest/testdata/logic_test/database#L102)):*
> ```
> 
> statement error database "b" is not empty
> DROP DATABASE b
> ```

Minor, but I'd also include a case somewhere that explicitly specifies RESTRICT.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17926#-:-Ks_4pOpddpJEXk-lJKJ:bnfp4nl)*

**Comment by knz** [comment]
Thanks; done.

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 17 of 18 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17926#-:-KsdYNOa6_QAoDWrnxyV:bnfp4nl)*

**Comment by knz** [comment]
TFYR!

**Pull request merged**
