### PR TITLE
rfc: node names

### PR DESCRIPTION
**Pull request by couchand**
An RFC to create explicit node names, which should be the
preferred way to identify nodes in all user interfaces.  The small
numbers of node ids have a way of colliding with identifiers of
other systems.

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Thanks Andrew for tackling this. I already have a few comments below; the main one is that I'd like to see more examples of what it looks like on a toy cluster after all is said and done (maybe you spelling out what I'd be expected to see in different places as a result, with examples).

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33715#-:-LWCgMmo4bAVXTboKKc4:b-difgpd)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[docs/RFCS/20190114_node_names.md, line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33715#-LWCdzI8-6BHkQQHyyvv:-LWCdzI9B3KoY9XRxDQm:b7uf9rd) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed126a60b567f9348a16f4e7daaff185f9fee94/docs/RFCS/20190114_node_names.md#L14)):*
> ```Markdown
> contexts, it may be helpful to add host name as well, but we should
> avoid using the cluster-assigned id for that purpose.  Set the name
> with a flag to the `node start` command.
> ```

The RFC would do well to identify two audiences for the node identities:

- humans who look at UI tools (CLI or web)
- automation. In particular we have introspections in SQL tables that like to be joined together. For the sake of performance we should keep numeric IDs there.

Note that this is similar to what the github API does. All github objects have "names" and this is what shows up in the UI, but the API calls use numeric "IDs" everywhere.
___
*[docs/RFCS/20190114_node_names.md, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33715#-LWCeK0K1RziR5hG-tJ1:-LWCeK0K1RziR5hG-tJ2:b-w7f3gs) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed126a60b567f9348a16f4e7daaff185f9fee94/docs/RFCS/20190114_node_names.md#L18)):*
> ```Markdown
> # Motivation
> 
> The cluster-assigned id is a small sequential number.  On it's own, it
> ```

nit: its own
___
*[docs/RFCS/20190114_node_names.md, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33715#-LWCeMln9TxE9r-sqZMr:-LWCeMln9TxE9r-sqZMs:b-30hfc5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed126a60b567f9348a16f4e7daaff185f9fee94/docs/RFCS/20190114_node_names.md#L22)):*
> ```Markdown
> run on hardware provisioned by computers.  This hardware frequently uses
> small sequential numbers for identifiers.  In the happy case, these are
> the same.  In any other case, it is a persistent source of confusion.
> ```

You can give an example of a confusion you had to resolve recently, that will strengthen the case.
___
*[docs/RFCS/20190114_node_names.md, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33715#-LWCeVRL9SlS_C0LwYLM:-LWCeVRL9SlS_C0LwYLN:b-4rpc9r) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed126a60b567f9348a16f4e7daaff185f9fee94/docs/RFCS/20190114_node_names.md#L40)):*
> ```Markdown
> # Guide-level explanation
> 
> Set the node name by adding the `--name` flag to the `start` command.
> ```

:-1: on manually defined names. I think this will open questions we'd rather not answer, like what to do when the same name is specified in multiple places.

I prefer auto-generated names with a dictionary always (without giving the user a choice). If you have strong reasons not to do that they should be discussed in the alternative section below.
___
*[docs/RFCS/20190114_node_names.md, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33715#-LWCel6f9IzjN5-jGZWV:-LWCel6f9IzjN5-jGZWW:bxovfl7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed126a60b567f9348a16f4e7daaff185f9fee94/docs/RFCS/20190114_node_names.md#L45)):*
> ```Markdown
> 
> Any node started without `--name` flag will be assigned a default name,
> a short, readable and random phrase like `uncertain-ocelot-1337`.
> ```

Explain what the number stands for in this section. (I think we can do away with the number.)
___
*[docs/RFCS/20190114_node_names.md, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33715#-LWCetjq1J0US5uNkf_B:-LWCetjrBJggajfFzptJ:b-pskc56) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed126a60b567f9348a16f4e7daaff185f9fee94/docs/RFCS/20190114_node_names.md#L68)):*
> ```Markdown
> - node id (minimum possible change)
> - advertise-addr
> - advertise-addr, but remove the port number
> ```

IMHO advertise-addr is a bad choice because it reveals information that's relevant at a low level of the network stack, to people at a higher level. could be convinced otherwise though
___
*[docs/RFCS/20190114_node_names.md, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33715#-LWCf5uV6KwGnMpKf_5t:-LWCf5uV6KwGnMpKf_5u:bjg3jmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed126a60b567f9348a16f4e7daaff185f9fee94/docs/RFCS/20190114_node_names.md#L69)):*
> ```Markdown
> - advertise-addr
> - advertise-addr, but remove the port number
> - some random short name (e.g. `uncertain-ocelot-1337`)
> ```

IMHO the short name should be derived algorithmically from the node ID using a (suitably compressed) fixed dictionary that can encode all the possible node ID values, perhaps with a salt derived from a cluster invariant (eg the cluster ID).

This way it's possible to auto-rederive the node name from the node ID from other places (e.g. from another node) without having to *store* these node names anywhere (and synchronize them across nodes).
___
*[docs/RFCS/20190114_node_names.md, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33715#-LWCfY6-CwD_Zlsg8VcY:-LWCfY6-CwD_Zlsg8VcZ:b-27l8kf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed126a60b567f9348a16f4e7daaff185f9fee94/docs/RFCS/20190114_node_names.md#L81)):*
> ```Markdown
> we implemented it only as the default name it would be broken from the
> start: any later change to the node's address would not be reflected in
> the name.
> ```

yeah that's a pretty compelling argument against the advertise addr.
___
*[docs/RFCS/20190114_node_names.md, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33715#-LWCfdGV246R63byoa9a:-LWCfdGWEE6dl_TNnlBO:bk18b31) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed126a60b567f9348a16f4e7daaff185f9fee94/docs/RFCS/20190114_node_names.md#L94)):*
> ```Markdown
> 
> The specific form of the id needs to be determined.  In the general sense,
> we need to be able to support up to 64-bits of information.  But real
> ```

node ID are 64 bits? I thought they were 32 bits.
___
*[docs/RFCS/20190114_node_names.md, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33715#-LWCfk7b-gmmgg7Bopv_:-LWCfk7b-gmmgg7Bopva:b88p9kg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed126a60b567f9348a16f4e7daaff185f9fee94/docs/RFCS/20190114_node_names.md#L121)):*
> ```Markdown
> though it is persistently problematic.
> 
> Another alternative would be to try to identify a few more specific
> ```

I think this paragraph is confused: what is the alternative really?

- I am :+1: on *researching* what other projects have done in the past or doing today. What naming algorithms exist and are advertised in the wild.
- I am :-1: on *implementing* all of them to get a feel of what they can do. I think we can educate ourselves pretty well from external sources directly.

I personally think that this RFC would benefit from some additional research in what others have been doing, and perhaps an experiment to demonstrate *one* of them (preferably a simple one, that does not require storing the node name anywhere).
___
*[docs/RFCS/20190114_node_names.md, line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33715#-LWCg9GG5MLwUgPcn6dY:-LWCg9GG5MLwUgPcn6dZ:birauw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed126a60b567f9348a16f4e7daaff185f9fee94/docs/RFCS/20190114_node_names.md#L131)):*
> ```Markdown
> name we can make sure to avoid confusion.  This might also catch a
> particular class of user error, where a user tries to "restart" a dead
> node without providing that node's store directory.
> ```

This is not a paragraph for the "alternative" section but rather for "unanswered questions" below. Also, the existence of this paragraph can be construed as one more argument against both 1) letting users choose the name and 2) having the name stored as opposed to auto-computed.

**Comment by couchand** [comment]
Thanks for your quick feedback, @knz!  There are definitely a few areas that need more detail, particularly the usage examples and the particulars of the name generation.

Regarding manual names: for the most part I agree with you.  Though the ability to configure names to match other infrastructure does seem compelling, it's not needed to address the primary concerns motivating this RFC.

**Review by couchand — COMMENTED** [review]
Updated, but still incomplete.  Feel free to take a look to see if it's going in the right direction.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33715#-:-LWIPPywCLkDo8YKk5Ry:b-dzmq4c)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[docs/RFCS/20190114_node_names.md, line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33715#-LWCdzI8-6BHkQQHyyvv:-LWIOUG_EOetMfO5rJXN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed126a60b567f9348a16f4e7daaff185f9fee94/docs/RFCS/20190114_node_names.md#L14)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

The RFC would do well to identify two audiences for the node identities:

- humans who look at UI tools (CLI or web)
- automation. In particular we have introspections in SQL tables that like to be joined together. For the sake of performance we should keep numeric IDs there.

Note that this is similar to what the github API does. All github objects have "names" and this is what shows up in the UI, but the API calls use numeric "IDs" everywhere.
</blockquote></details>

Done.
___
*[docs/RFCS/20190114_node_names.md, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33715#-LWCeK0K1RziR5hG-tJ1:-LWIOW0H2yejEgAcyLTD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed126a60b567f9348a16f4e7daaff185f9fee94/docs/RFCS/20190114_node_names.md#L18)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: its own
</blockquote></details>

Done.
___
*[docs/RFCS/20190114_node_names.md, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33715#-LWCeMln9TxE9r-sqZMr:-LWIOWeKBsM1BTq4CdvM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed126a60b567f9348a16f4e7daaff185f9fee94/docs/RFCS/20190114_node_names.md#L22)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You can give an example of a confusion you had to resolve recently, that will strengthen the case.
</blockquote></details>

Done.
___
*[docs/RFCS/20190114_node_names.md, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33715#-LWCeVRL9SlS_C0LwYLM:-LWIOXNTDNorsalJhLHU:b-87j1qu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed126a60b567f9348a16f4e7daaff185f9fee94/docs/RFCS/20190114_node_names.md#L40)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

:-1: on manually defined names. I think this will open questions we'd rather not answer, like what to do when the same name is specified in multiple places.

I prefer auto-generated names with a dictionary always (without giving the user a choice). If you have strong reasons not to do that they should be discussed in the alternative section below.
</blockquote></details>

Gone.
___
*[docs/RFCS/20190114_node_names.md, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33715#-LWCel6f9IzjN5-jGZWV:-LWIOYdl568XYAFVhO4O:b-87j1qu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed126a60b567f9348a16f4e7daaff185f9fee94/docs/RFCS/20190114_node_names.md#L45)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Explain what the number stands for in this section. (I think we can do away with the number.)
</blockquote></details>

Gone.
___
*[docs/RFCS/20190114_node_names.md, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33715#-LWCetjq1J0US5uNkf_B:-LWIO_dv1WeOF318vawH:b-87j1qu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed126a60b567f9348a16f4e7daaff185f9fee94/docs/RFCS/20190114_node_names.md#L68)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

IMHO advertise-addr is a bad choice because it reveals information that's relevant at a low level of the network stack, to people at a higher level. could be convinced otherwise though
</blockquote></details>

Gone.
___
*[docs/RFCS/20190114_node_names.md, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33715#-LWCf5uV6KwGnMpKf_5t:-LWIOgcqCVWK2PSoKgBH:b-c8dc16) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed126a60b567f9348a16f4e7daaff185f9fee94/docs/RFCS/20190114_node_names.md#L69)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

IMHO the short name should be derived algorithmically from the node ID using a (suitably compressed) fixed dictionary that can encode all the possible node ID values, perhaps with a salt derived from a cluster invariant (eg the cluster ID).

This way it's possible to auto-rederive the node name from the node ID from other places (e.g. from another node) without having to *store* these node names anywhere (and synchronize them across nodes).
</blockquote></details>

That's the general form, now to figure out the specifics I guess.
___
*[docs/RFCS/20190114_node_names.md, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33715#-LWCfY6-CwD_Zlsg8VcY:-LWIOuHY26GkQ-VXOS8U:bb77ucv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed126a60b567f9348a16f4e7daaff185f9fee94/docs/RFCS/20190114_node_names.md#L81)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

yeah that's a pretty compelling argument against the advertise addr.
</blockquote></details>

Yep.
___
*[docs/RFCS/20190114_node_names.md, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33715#-LWCfdGV246R63byoa9a:-LWIOx-H33AJdn4abS82:bq4ld9s) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed126a60b567f9348a16f4e7daaff185f9fee94/docs/RFCS/20190114_node_names.md#L94)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

node ID are 64 bits? I thought they were 32 bits.
</blockquote></details>

Whoops my mistake!
___
*[docs/RFCS/20190114_node_names.md, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33715#-LWCfk7b-gmmgg7Bopv_:-LWIP0Im4-3bNMosOxxc:b7hfrxb) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed126a60b567f9348a16f4e7daaff185f9fee94/docs/RFCS/20190114_node_names.md#L121)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think this paragraph is confused: what is the alternative really?

- I am :+1: on *researching* what other projects have done in the past or doing today. What naming algorithms exist and are advertised in the wild.
- I am :-1: on *implementing* all of them to get a feel of what they can do. I think we can educate ourselves pretty well from external sources directly.

I personally think that this RFC would benefit from some additional research in what others have been doing, and perhaps an experiment to demonstrate *one* of them (preferably a simple one, that does not require storing the node name anywhere).
</blockquote></details>

I'm not really sure what I was talking about there.  Any way, it's gone.

I'm open to doing some research on how this is addressed elsewhere.  A few minutes thinking about it and searching around I didn't come up with any good leads for comparable stuff, so I'd welcome and tips you might have there.
___
*[docs/RFCS/20190114_node_names.md, line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33715#-LWCg9GG5MLwUgPcn6dY:-LWIPMsUCo_HgH7sL7Vd:b-87j1qu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed126a60b567f9348a16f4e7daaff185f9fee94/docs/RFCS/20190114_node_names.md#L131)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This is not a paragraph for the "alternative" section but rather for "unanswered questions" below. Also, the existence of this paragraph can be construed as one more argument against both 1) letting users choose the name and 2) having the name stored as opposed to auto-computed.
</blockquote></details>

Gone.

**Review by bdarnell — COMMENTED** [review]
I actually think manual user-assigned names are a good idea, while I'm not sure that autogenerated ones are worth the trouble (they're still meaningless, they just don't look like small integers). I'd call the manual names "display names" to set appropriate expectations about what kinds of validation is done (i.e. none; if you configure things with duplicates you're only confusing yourself).

We already avoid displaying node IDs in isolation in most cases in the UI; they're usually combined with the node's address. I see the user-defined display names as a solution for environments where addresses are hard to read (raw IP addresses, for example). 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33715#-:-LWMC5rz1pY6zBDZjVpO:b-qnns5m)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request closed without merging**
