### PR TITLE
sql: replace JOIN ON with equality operations

### LINKED ISSUE #10631: sql: replace JOIN ... ON with equality operations to JOIN with an equalityPredicate
After  #10630 is addressed, queries of the form `a JOIN b ON a.x = b.y` must be replaced by `a JOIN b ON EQUALS(x, y)`

This must detect cases where the ON predicate, after normalization to disjunctive normal form, has a single conjunction and only contains equality test between left and right columns, and replace these cases only. Other cases can remain as `onPredicate`.

### PR DESCRIPTION
**Pull request by a6802739**
Fixes #10631.

cc @knz.

I use a bool `isUsingExpr` to identify if it's `USING` or `ON` expr, I think it's not a good way to do that thing, maybe a enum `equalityType` is better.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10755)

### CODE REVIEW

**Comment by knz** [comment]
Thanks for working on this.
Can you rebase on the latest master? Irfan has made a few changes to the join code.

**Comment by a6802739** [comment]
@knz, thanks.

I have doen as you say.

**Comment by knz** [comment]
Hi songhao. Thanks for tackling this.

There was one mistake in your patch: if the query used `a JOIN b ON a.x=a.y` (same table on both sides of the equality) this would be incorrectly handled.

To fix this and also improve a few other things I propose some improvements here: https://github.com/a6802739/cockroach/pull/1

If you accept these changes, then they will show up in this PR automatically. 

After this, I would invite you to add more tests. The following are needed:
- a EXPLAIN test that show that HASH JOIN is used properly.
- a test that uses the same table on both sides of the equality e.g. `ON a.x = a.y`
- a test that uses a table and a constant e.g. `ON a.x = 13`
- a test that uses column names between parentheses, e.g. `ON ((a.x))=(((b.y)))`

**Comment by a6802739** [comment]
@knz, thanks for your modification.

I have add all the test you say in `pkg/sql/testdata/join` now.

**Comment by knz** [comment]
This looks good, thanks!

However note that thanks to your optimization, some joins in the test file have become non-deterministic (hash join can produce results in different orders each time).
For example in the TC results [here](https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=54423#_focus=16730) you can see one test has failed:
```
[12:18:53][Step 2/2]     	logic_test.go:683: testdata/join:239: 
[12:18:53][Step 2/2]     		expected:
[12:18:53][Step 2/2]     		    x    y
[12:18:53][Step 2/2]     		    NULL 44
[12:18:53][Step 2/2]     		    NULL NULL
[12:18:53][Step 2/2]     		    NULL 42
[12:18:53][Step 2/2]     		    
[12:18:53][Step 2/2]     		but found:
[12:18:53][Step 2/2]     		    x     y     
[12:18:53][Step 2/2]     		    NULL  NULL  
[12:18:53][Step 2/2]     		    NULL  42    
[12:18:53][Step 2/2]     		    NULL  44    
```

This is because it is missing an ORDER BY clause.

Please check all the tests without ORDER BY and find which are those that your optimization have influenced (that are now running as hash joins).

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/testdata/join, line 281 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10755#-KX8Pe80tkV6lAhjBbZF:-KX8Pe80tkV6lAhjBbZG:bcwj720) ([raw file](https://github.com/cockroachdb/cockroach/blob/b324fe5ad05efcef55119c66a224aee1c1010803/pkg/sql/testdata/join#L281)):*
> ```
> 1  scan  twocolumn@primary
> 
> # Check EXPLAIN.
> ```

I am missing a test with `ON a.x = a.y` or something like that (two sides of the equality on the same table).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10755#-:-KX8Pn0iKB_dzOvAXzQd:b-xta2bv)*

**Comment by a6802739** [comment]
@knz, thanks for your review again.

**Comment by knz** [comment]
Thank you so much!

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/testdata/join, line 271 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10755#-KXAEYDij4HDcdNFPgu5:-KXAEYDij4HDcdNFPgu6:b-b9lk75) ([raw file](https://github.com/cockroachdb/cockroach/blob/e09b047115b96be9a92fbcef52b66cee7081e86b/pkg/sql/testdata/join#L271)):*
> ```
> 
> query IIII 
> SELECT * FROM twocolumn AS a JOIN twocolumn AS b ON a.x = b.y
> ```

This is not what I meant. I meant `SELECT * FROM twocolumn AS as JOIN ... AS b ON a.x = a.y`
i.e. both sides of the equality refer to the same *side* of the join.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10755#-:-KXAEkfbS4xknxWu1Us6:b-fudnmc)*

**Comment by a6802739** [comment]
Thanks.

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/testdata/join, line 271 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10755#-KXAEYDij4HDcdNFPgu5:-KXAjSJ1uPwDmLd9f_vP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e09b047115b96be9a92fbcef52b66cee7081e86b/pkg/sql/testdata/join#L271)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> This is not what I meant. I meant `SELECT * FROM twocolumn AS as JOIN ... AS b ON a.x = a.y`
> i.e. both sides of the equality refer to the same *side* of the join.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10755#-:-KXAjLRIV-sIM3lcyk4O:b-ucfkn4)*

**Comment by knz** [comment]
:lgtm_strong: :confetti_ball: :fireworks: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10755#-:-KXAriKfk3x0cq6V1hMv:b-iogtoz)*

**Comment by a6802739** [comment]
@knz, could I merge this now?

**Comment by knz** [comment]
yes absolutely.

**Pull request merged**
