### PR TITLE
sql: allow admins to use streaming replication

### LINKED ISSUE #107196: roachtest: pgjdbc failed [need REPLICATION privilege]
roachtest.pgjdbc [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10967169?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10967169?buildTab=artifacts#/pgjdbc) on master @ [06b5ba7888339ed53477ff73f9f3ae77a708ee17](https://github.com/cockroachdb/cockroach/commits/06b5ba7888339ed53477ff73f9f3ae77a708ee17):

```
(orm_helpers.go:212).summarizeFailed: 
Tests run on Cockroach v23.2.0-alpha.00000000-dev-06b5ba7888339ed53477ff73f9f3ae77a708ee17
Tests run against pgjdbc REL42.3.3
5789 Total Tests Run
5055 tests passed
734 tests failed
70 tests skipped
183 tests ignored
0 tests passed unexpectedly
5 tests failed unexpectedly
0 tests expected failed but skipped
0 tests expected failed but not run
---
--- FAIL: org.postgresql.replication.ReplicationSlotTest.testCreateTemporaryLogicalSlotPgLowerThan10 - unknown (unexpected)
--- FAIL: org.postgresql.replication.ReplicationSlotTest.testNotAvailableCreatePhysicalSlotWithoutSlotName - unknown (unexpected)
--- FAIL: org.postgresql.replication.ReplicationSlotTest.testCreateTemporaryPhysicalSlotPgLowerThan10 - unknown (unexpected)
--- FAIL: org.postgresql.replication.ReplicationSlotTest.testNotAvailableCreateLogicalSlotWithoutSlotName - unknown (unexpected)
--- FAIL: org.postgresql.replication.ReplicationSlotTest.testNotAvailableCreateLogicalSlotWithoutOutputPlugin - unknown (unexpected)
For a full summary look at the pgjdbc artifacts 
An updated blocklist (pgjdbcBlocklist) is available in the artifacts' pgjdbc log
test artifacts and logs in: /artifacts/pgjdbc/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*pgjdbc.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-29942

### LINKED ISSUE #107258: roachtest: pgjdbc failed
roachtest.pgjdbc [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10983916?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10983916?buildTab=artifacts#/pgjdbc) on master @ [c6f4c0ed6e39ec4795755b8b477e6cac0abf818f](https://github.com/cockroachdb/cockroach/commits/c6f4c0ed6e39ec4795755b8b477e6cac0abf818f):

```
(orm_helpers.go:212).summarizeFailed: 
Tests run on Cockroach v23.2.0-alpha.00000000-dev-c6f4c0ed6e39ec4795755b8b477e6cac0abf818f
Tests run against pgjdbc REL42.3.3
5789 Total Tests Run
5055 tests passed
734 tests failed
70 tests skipped
183 tests ignored
0 tests passed unexpectedly
5 tests failed unexpectedly
0 tests expected failed but skipped
0 tests expected failed but not run
---
--- FAIL: org.postgresql.replication.ReplicationSlotTest.testCreateTemporaryLogicalSlotPgLowerThan10 - unknown (unexpected)
--- FAIL: org.postgresql.replication.ReplicationSlotTest.testNotAvailableCreatePhysicalSlotWithoutSlotName - unknown (unexpected)
--- FAIL: org.postgresql.replication.ReplicationSlotTest.testCreateTemporaryPhysicalSlotPgLowerThan10 - unknown (unexpected)
--- FAIL: org.postgresql.replication.ReplicationSlotTest.testNotAvailableCreateLogicalSlotWithoutOutputPlugin - unknown (unexpected)
--- FAIL: org.postgresql.replication.ReplicationSlotTest.testNotAvailableCreateLogicalSlotWithoutSlotName - unknown (unexpected)
For a full summary look at the pgjdbc artifacts 
An updated blocklist (pgjdbcBlocklist) is available in the artifacts' pgjdbc log
test artifacts and logs in: /artifacts/pgjdbc/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*pgjdbc.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-29968

### PR DESCRIPTION
**Pull request by otan**
Release note: None

Resolves #107196
Resolves #107258

### CODE REVIEW

**Comment by knz** [comment]
Cc @stevendanna

**Review by rafiss — APPROVED** [review]

**Comment by rafiss** [comment]
might need to rebase to fix the test flake

**Comment by otan** [comment]
bors r=rafiss

let bors do the rebase >:D TFTR

**Comment by yuzefovich** [comment]
bors r-

I think it's introducing a flake in `TestVerifyPassword/some_admin_with_empty_password_should_fail`

**Comment by otan** [comment]
If that were true I'd have expected bors to post a failing run here.

**Comment by yuzefovich** [comment]
It did post it twice as well as the CI is red on this PR with the same failure.

**Comment by otan** [comment]
lol i can't read :D

**Comment by otan** [comment]
thanks for noticing, sorry for the trouble
missed updating a test value (thought it was a flake) + made all the fields named instead of implicit

bors r=rafiss

**Pull request merged**
