### PR TITLE
storage: fix intent resolution edge case, document write timestamps

### PR DESCRIPTION
**Pull request by tbg**
Went with @petermattis' fix from #7680 and added a test plus commentary along the way. Let me know if there are any additional comments that I can add.

Closes #7680.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7744)

### CODE REVIEW

**Comment by petermattis** [comment]
I think you're referencing the wrong bug to close there.

**Comment by tschottdorf** [comment]
You're right, fixed.

**Comment by petermattis** [comment]
Does this fix #7654? If so, mark in the commit message.

**Comment by petermattis** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[roachpb/data.proto, line 221 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7744#-KMQ1pjRvgIZY1Obxaqv:-KMQ1pjRvgIZY1Obxaqw:1188459342) ([raw file](https://github.com/cockroachdb/cockroach/blob/95df9dc22669f554e12813d311aea8e1d1ead669/roachpb/data.proto#L221)):*
> ```protobuf
>   // The original timestamp at which the transaction started. For serializable
>   // transactions, if the timestamp drifts from the original timestamp, the
>   // transaction will retry.
> ```

We generally put blank comment lines between paragraphs in comments for readability.

---

*[storage/replica.go, line 1018 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7744#-KMQ2mC0fa2jxfzs0ICe:-KMQ2mC0fa2jxfzs0ICf:1208718806) ([raw file](https://github.com/cockroachdb/cockroach/blob/95df9dc22669f554e12813d311aea8e1d1ead669/storage/replica.go#L1018)):*
> ```Go
> // code paths, I wonder how it works if not for data races or some brittle
> // code path a stack frame higher up. Should really address that previous
> // TODO.
> ```

Might want to file issues about these TODOs.

---

*[storage/engine/mvcc_test.go, line 2000 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7744#-KMQ0lI8vKSXCJyw86U1:-KMQ0lI9n3BVlCXuBeUE:1372038613) ([raw file](https://github.com/cockroachdb/cockroach/blob/012b29d3b590e7ae2c672a0a68b59c88a937f26d/storage/engine/mvcc_test.go#L2000)):*
> ```Go
> 		}
> 	}
> ```

Spurious blank line (I've noticed you like these at the end of functions).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7744)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7744#-:-KMQ2rhX55O0U115fg84:1417088721)*

**Comment by petermattis** [comment]
#7654 looks like the same issue as #6025.

**Comment by tschottdorf** [comment]
Good point. Added both to (your) commit message (stress ran for ~9min and 6k iters without trouble).

**Comment by tschottdorf** [comment]
Review status: 1 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[roachpb/data.proto, line 221 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7744#-KMQ1pjRvgIZY1Obxaqv:-KMQ4Wf_O9Bwp90bW_Bn:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/95df9dc22669f554e12813d311aea8e1d1ead669/roachpb/data.proto#L221)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> We generally put blank comment lines between paragraphs in comments for readability.
</details>
Done.

---

*[storage/replica.go, line 1018 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7744#-KMQ2mC0fa2jxfzs0ICe:-KMQ4tlNLypxDSkihnMy:-2009083130) ([raw file](https://github.com/cockroachdb/cockroach/blob/95df9dc22669f554e12813d311aea8e1d1ead669/storage/replica.go#L1018)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Might want to file issues about these TODOs.
</details>
filed #7746.

---

*[storage/engine/mvcc_test.go, line 2000 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7744#-KMQ0lI8vKSXCJyw86U1:-KMQ55Y0otsCmN7K-g4M:1596603992) ([raw file](https://github.com/cockroachdb/cockroach/blob/012b29d3b590e7ae2c672a0a68b59c88a937f26d/storage/engine/mvcc_test.go#L2000)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Spurious blank line (I've noticed you like these at the end of functions).
</details>
Everyone's gotta have their Kryptonite. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7744)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 1 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7744#-:-KMQIgElO_WlEW9FVj6b:1417088721)*

**Comment by tamird** [comment]
:lgtm: though first two commits should be squashed.

---

Reviewed 1 of 1 files at r1, 5 of 5 files at r9, 1 of 1 files at r10, 4 of 4 files at r11.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7744#-:-KMQmEdHu0z94i-4xPZr:251802754)*

**Pull request merged**
