### PR TITLE
ui, server: update the problem ranges report

### PR DESCRIPTION
**Pull request by BramGruneir**
This changes the endpoint from returning a single aggregated list of problem ranges to returning per-node problem lists. Which allows us to get information for each individual call to all the other nodes.  This also now ignores the liveness "alive" flag and tries to call all nodes, similar to the change made to the range report.

This also changes the url for individual node's list of range problems from `#\reports\problemranges?node_id=[node_id]` to `#\reports\problemranges\[node_id]`.

As this is a re-write of the page, I also cleaned up the style a lot.

Original:
screen shot 2017-08-24 at 16 48 52

Updated:
screen shot 2017-08-24 at 16 22 33

### CODE REVIEW

**Comment by mrtracy** [comment]
Review status: 0 of 13 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/server/serverpb/status.proto, line 391 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17913#-KsQPPQQZY3yTtbXtevd:-KsQPPQQZY3yTtbXteve:b-bb1ble) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fab1907c0f461b9be6c503e25f144953371f6c3/pkg/server/serverpb/status.proto#L391)):*
> ```protobuf
> }
> 
> message ProblemRangesResponse {
> ```

Has this response message type been part of a CockroachDB release yet?  You are re-using a number for a different field type, this would not be safe to upgrade.

---

*[pkg/ui/src/views/reports/containers/problemRanges/connectionsTable.tsx, line 16 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17913#-KsQUPZO4jzdRNyzKH6M:-KsQUPZO4jzdRNyzKH6N:b-dpipo6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fab1907c0f461b9be6c503e25f144953371f6c3/pkg/ui/src/views/reports/containers/problemRanges/connectionsTable.tsx#L16)):*
> ```XML
> }) {
>   const { nodeID, problems } = props;
>   let rowClassName = "connections-table__row";
> ```

For this kind of thing, try using the "classnames" package that we already depend on.  You can do something like:

```typescript
const rowClassName = classnames({
  "connections-table__row": true,
  "connections-table__row--warning": !_.isEmpty(props.problems.error_message),
})
```

It doesn't save much for one optional class, but its better for >1 optional class so I think we should establish the pattern where possible.

---

*[pkg/ui/src/views/reports/containers/problemRanges/connectionsTable.tsx, line 59 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17913#-KsQV5fVOjjmA3UFrp3q:-KsQV5fVOjjmA3UFrp3r:bh7yhxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fab1907c0f461b9be6c503e25f144953371f6c3/pkg/ui/src/views/reports/containers/problemRanges/connectionsTable.tsx#L59)):*
> ```XML
>         <tbody>
>           <tr className="connections-table__row connections-table__row--header">
>             <th className="connections-table__cell connections-table__cell--header">Node</th>
> ```

I do really think you should investigate the way that tables are constructed in sortedTable and sortableTable.  The issue I have is that you have essentially created parallel lists here:  As you have it, these headers *must* match the order and number of the cells created in ConnectionTableRow, and if you wanted to add, remove or re-order columns later it could be frustrating. You've also missed an opportunity to remove quite a bit of boilerplate.

I won't make this a condition of the PR though, since this does work and you've already demonstrated a commitment to improving these in subsequent PRs.  Just something to consider!

---

*[pkg/ui/src/views/reports/containers/problemRanges/index.tsx, line 39 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17913#-KsQ_z737DUbzRJ6RIWY:-KsQ_z737DUbzRJ6RIWZ:b-17m2yk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fab1907c0f461b9be6c503e25f144953371f6c3/pkg/ui/src/views/reports/containers/problemRanges/index.tsx#L39)):*
> ```XML
>   name: string,
>   problems: protos.cockroach.server.serverpb.ProblemRangesResponse.NodeProblems$Properties[],
>   extract: (p: protos.cockroach.server.serverpb.ProblemRangesResponse.NodeProblems$Properties) => Long[],
> ```

Consider creating a type alias to get rid of that huge namespace throughout the code:

```typescript
type ProblemRangesResponse = protos.cockroach.server.serverpb.ProblemRangesResponse

type NodeProblems = ProblemRangesResponse.NodeProblems
```

---

*[pkg/ui/src/views/reports/containers/problemRanges/index.tsx, line 52 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17913#-KsQY6QPyGBWdoxj2f50:-KsQY6QPyGBWdoxj2f51:bo5pf79) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fab1907c0f461b9be6c503e25f144953371f6c3/pkg/ui/src/views/reports/containers/problemRanges/index.tsx#L52)):*
> ```XML
>   return (
>     <div>
>       <h2>{props.name}</h2>
> ```

I don't think this needs to be a table, or that it *should* be a table; there is exactly one cell.

---

*[pkg/ui/src/views/reports/containers/problemRanges/index.tsx, line 64 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17913#-KsQTbIUf699z6JjbOTK:-KsQTbIUf699z6JjbOTL:b-ah8uey) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fab1907c0f461b9be6c503e25f144953371f6c3/pkg/ui/src/views/reports/containers/problemRanges/index.tsx#L64)):*
> ```XML
> }
> 
> function extractRangeIDsByType(value: string) {
> ```

I really don't like the usage of `_.get` unless there is no alternative, it loses type safety.  There are a couple of ways to mitigate this.

In this particular case, I think the check for the empty error message and the default empty value should be hoisted into the problem ranges render method.  Then the extractors should be of the form:

```typescript
<ProblemTable 
          name="No Raft Leader"
          problems={problems}
          extract={(p) => p.no_raft_leader_range_ids}
        />
```

That's type safe.

Another more general approach, if you are forced to use `_.get` for some reason, would be to use Typescript's `keyof` to create a more specific type than `string`.

For example, in this case you could use`keyof ProblemRangesResponse.NodeProblems$Properties`. That would give a measure of type safety even though you are ultimately using `_.get()`.

---

*[pkg/ui/src/views/reports/containers/problemRanges/index.tsx, line 76 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17913#-KsQXGdP8q37bPyCJpNc:-KsQXGdP8q37bPyCJpNd:br1zru8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fab1907c0f461b9be6c503e25f144953371f6c3/pkg/ui/src/views/reports/containers/problemRanges/index.tsx#L76)):*
> ```XML
>  * Renders the Problem Ranges page.
>  */
> class ProblemRanges extends React.Component<ProblemRangesProps, {}> {
> ```

These are debug pages so we can assume an expert developer in many cases; however, I did find it a little hard to figure out exactly what was going on here. The key is the "flatmaps": we're now getting problem information per-node, but then we flatten that information and display problem information for the cluster (or for all of the nodes queried, at least).  This took me a few reads to figure out, but that's the reason the "extract" function is even necessary.

Maybe a comment outlining the strategy here would be helpful.  Actually, in a lot of cases these debug pages have had a computation process that was difficult to follow; I don't think they are always self-explanatory.

---

*[pkg/ui/src/views/reports/containers/problemRanges/index.tsx, line 139 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17913#-KsQWyfq0BQemURZCVBk:-KsQWyfq0BQemURZCVBl:bbvssqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fab1907c0f461b9be6c503e25f144953371f6c3/pkg/ui/src/views/reports/containers/problemRanges/index.tsx#L139)):*
> ```XML
>       <div className="section">
>         <h1>{titleText}</h1>
>         <ProblemTable name="Unavailable"
> ```

Still not being linted, but the "name" attribute should be on the next line according to the style guide.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17913)*

**Comment by BramGruneir** [comment]
Review status: 0 of 13 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/server/serverpb/status.proto, line 391 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17913#-KsQPPQQZY3yTtbXtevd:-KsdRc-CyNAMMy8xQIeG:b-opduw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fab1907c0f461b9be6c503e25f144953371f6c3/pkg/server/serverpb/status.proto#L391)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

Has this response message type been part of a CockroachDB release yet?  You are re-using a number for a different field type, this would not be safe to upgrade.
</blockquote></details>

It has, but it is not used for inter-node communication, only between the admin ui and the server it sits on, I thought this was ok.  

But I can bump the number if you think that's wise.

---

*[pkg/ui/src/views/reports/containers/problemRanges/connectionsTable.tsx, line 16 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17913#-KsQUPZO4jzdRNyzKH6M:-KsdRzAVo3NLlkaqETCH:b-k9raew) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fab1907c0f461b9be6c503e25f144953371f6c3/pkg/ui/src/views/reports/containers/problemRanges/connectionsTable.tsx#L16)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

For this kind of thing, try using the "classnames" package that we already depend on.  You can do something like:

```typescript
const rowClassName = classnames({
  "connections-table__row": true,
  "connections-table__row--warning": !_.isEmpty(props.problems.error_message),
})
```

It doesn't save much for one optional class, but its better for >1 optional class so I think we should establish the pattern where possible.
</blockquote></details>

Wow.  I didn't know that existed.  This is great.  I might just issue another PR later today moving most of my classname code to this.

---

*[pkg/ui/src/views/reports/containers/problemRanges/connectionsTable.tsx, line 59 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17913#-KsQV5fVOjjmA3UFrp3q:-KsdtCUd5HUwhsw1XMYK:b-lj2560) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fab1907c0f461b9be6c503e25f144953371f6c3/pkg/ui/src/views/reports/containers/problemRanges/connectionsTable.tsx#L59)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

I do really think you should investigate the way that tables are constructed in sortedTable and sortableTable.  The issue I have is that you have essentially created parallel lists here:  As you have it, these headers *must* match the order and number of the cells created in ConnectionTableRow, and if you wanted to add, remove or re-order columns later it could be frustrating. You've also missed an opportunity to remove quite a bit of boilerplate.

I won't make this a condition of the PR though, since this does work and you've already demonstrated a commitment to improving these in subsequent PRs.  Just something to consider!
</blockquote></details>

Let chat offline.  I'd love to restructure this, but I'm not sure exactly how.  Looking at sorted/sortable table didn't really give me any insight.

---

*[pkg/ui/src/views/reports/containers/problemRanges/index.tsx, line 39 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17913#-KsQ_z737DUbzRJ6RIWY:-Ksdgx0g0NT9JD_cUsmH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fab1907c0f461b9be6c503e25f144953371f6c3/pkg/ui/src/views/reports/containers/problemRanges/index.tsx#L39)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

Consider creating a type alias to get rid of that huge namespace throughout the code:

```typescript
type ProblemRangesResponse = protos.cockroach.server.serverpb.ProblemRangesResponse

type NodeProblems = ProblemRangesResponse.NodeProblems
```
</blockquote></details>

Done.

---

*[pkg/ui/src/views/reports/containers/problemRanges/index.tsx, line 52 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17913#-KsQY6QPyGBWdoxj2f50:-Ksdl1PvwIUi-nCO04Dn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fab1907c0f461b9be6c503e25f144953371f6c3/pkg/ui/src/views/reports/containers/problemRanges/index.tsx#L52)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

I don't think this needs to be a table, or that it *should* be a table; there is exactly one cell.
</blockquote></details>

Done.

---

*[pkg/ui/src/views/reports/containers/problemRanges/index.tsx, line 64 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17913#-KsQTbIUf699z6JjbOTK:-KsdnkgaVzO5NqXsmAfn:b1chov3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fab1907c0f461b9be6c503e25f144953371f6c3/pkg/ui/src/views/reports/containers/problemRanges/index.tsx#L64)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

I really don't like the usage of `_.get` unless there is no alternative, it loses type safety.  There are a couple of ways to mitigate this.

In this particular case, I think the check for the empty error message and the default empty value should be hoisted into the problem ranges render method.  Then the extractors should be of the form:

```typescript
<ProblemTable 
          name="No Raft Leader"
          problems={problems}
          extract={(p) => p.no_raft_leader_range_ids}
        />
```

That's type safe.

Another more general approach, if you are forced to use `_.get` for some reason, would be to use Typescript's `keyof` to create a more specific type than `string`.

For example, in this case you could use`keyof ProblemRangesResponse.NodeProblems$Properties`. That would give a measure of type safety even though you are ultimately using `_.get()`.


</blockquote></details>

Much cleaner, I like it.  Done.

---

*[pkg/ui/src/views/reports/containers/problemRanges/index.tsx, line 76 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17913#-KsQXGdP8q37bPyCJpNc:-KsdsuiiexoT2eimmwOW:bh2pqsh) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fab1907c0f461b9be6c503e25f144953371f6c3/pkg/ui/src/views/reports/containers/problemRanges/index.tsx#L76)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

These are debug pages so we can assume an expert developer in many cases; however, I did find it a little hard to figure out exactly what was going on here. The key is the "flatmaps": we're now getting problem information per-node, but then we flatten that information and display problem information for the cluster (or for all of the nodes queried, at least).  This took me a few reads to figure out, but that's the reason the "extract" function is even necessary.

Maybe a comment outlining the strategy here would be helpful.  Actually, in a lot of cases these debug pages have had a computation process that was difficult to follow; I don't think they are always self-explanatory.
</blockquote></details>

I added a little  comment, but I also re-wrote the logic so it should be much clearer.

---

*[pkg/ui/src/views/reports/containers/problemRanges/index.tsx, line 139 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17913#-KsQWyfq0BQemURZCVBk:-Ksdt9mRDj6XqCarAzeU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fab1907c0f461b9be6c503e25f144953371f6c3/pkg/ui/src/views/reports/containers/problemRanges/index.tsx#L139)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

Still not being linted, but the "name" attribute should be on the next line according to the style guide.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17913)*

**Comment by mrtracy** [comment]
Everything is LGTM except for the version numbers on the protocol buffers; I think i'd like you to bump and reserve, instead of replace.  If we run into a situation where someone does have a mismatched UI version / cluster version, I think the resulting error message would be much easier to understand (and might not even produce an error at all).

---

Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/server/serverpb/status.proto, line 391 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17913#-KsQPPQQZY3yTtbXtevd:-KseX23x6WL-Lf7-ywwJ:bycdaix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fab1907c0f461b9be6c503e25f144953371f6c3/pkg/server/serverpb/status.proto#L391)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

It has, but it is not used for inter-node communication, only between the admin ui and the server it sits on, I thought this was ok.  

But I can bump the number if you think that's wise.

</blockquote></details>

The Admin UI can still be open in a browser through an upgrade; you could also have a situation with a rolling upgrade, where different nodes are at different versions.

It's probably not worth the fuss, but I think bumping instead of replacing would set a good precedent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17913#-:-KseYFjcI0i0ci8OeQqR:b-dyc68t)*

**Comment by BramGruneir** [comment]
Update this and it now includes the changes we made while pairing.  
Can you take one last look?

---

Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/server/serverpb/status.proto, line 391 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17913#-KsQPPQQZY3yTtbXtevd:-Ksiv0DAG3xMwYh-Y3xJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fab1907c0f461b9be6c503e25f144953371f6c3/pkg/server/serverpb/status.proto#L391)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

The Admin UI can still be open in a browser through an upgrade; you could also have a situation with a rolling upgrade, where different nodes are at different versions.

It's probably not worth the fuss, but I think bumping instead of replacing would set a good precedent.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17913#-:-KsiuuIwQ-VOx4-drAAn:b-2l0f61)*

**Comment by mrtracy** [comment]
:lgtm:

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17913#-:-KsoEWE8YETfCw9ABjde:bnfp4nl)*

**Pull request merged**
