### PR TITLE
sql: change REGIONAL BY ROW's default expression to be insertable from anywhere

### LINKED ISSUE #59665: sql: determine what happens if gateway_region does not exist in current database

### PR DESCRIPTION
**Pull request by otan**
Resolves #59665

### CODE REVIEW

**Review by ajstorm — COMMENTED** [review]
This was a pleasant surprise - didn't realize you were working on this yet.

> falling back to the primary key if not.

Nit: falling back to primary region if not?

I'm somewhat torn on the naming, especially if we're going to expose this function name to customers in SHOW CREATE TABLE, as I'd imagine we will.  `valid_region` seems a bit misleading, as the region could still be "valid", just not added to the given database.  Maybe `database_region_or_primary_region`?  Or just `validated_gateway_region()` which calls `gateway_region()` under the covers?   TBH, I'm not in love with any of them.  @nvanbenschoten, @awoods187, either of you have an opinion on naming (begin :bike: shedding).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59836#-:-MSwszoU0ERQXSM6lTBR:b-hgn88s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[docs/generated/sql/functions.md, line 873 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59836#-MSwv7gX1rhKBYWw4GkC:-MSwv7gX1rhKBYWw4GkD:b-aoiflw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2342024dc77905ee21a290b1cd430dd179351313/docs/generated/sql/functions.md#L873)):*
> ```Markdown
> the locality flag on node startup. Returns an error if no region is set.</p>
> </span></td></tr>
> <tr><td><a name="valid_region_or_primary_region"></a><code>valid_region_or_primary_region(val: <a href="string.html">string</a>) &rarr; <a href="string.html">string</a></code></td><td><span class="funcdesc"><p>Returns the given region if the region is affiliated with the current database.
> ```

Nit: "...if the region has been added to the current database."
___
*[pkg/sql/sem/builtins/builtins.go, line 4764 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59836#-MSww9bI6P4c-F2IODei:-MSww9bI6P4c-F2IODej:bcjwpfm) ([raw file](https://github.com/cockroachdb/cockroach/blob/2342024dc77905ee21a290b1cd430dd179351313/pkg/sql/sem/builtins/builtins.go#L4764)):*
> ```Go
> 					return nil, pgerror.Newf(
> 						pgcode.InvalidDatabaseDefinition,
> 						"current database %s does not exist",
> ```

Nit: Can we add a test case for this?
___
*[pkg/sql/sem/builtins/builtins.go, line 4768 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59836#-MSwwK6_5JPXKCUhHur-:-MSwwK6_5JPXKCUhHur0:b-q672jq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2342024dc77905ee21a290b1cd430dd179351313/pkg/sql/sem/builtins/builtins.go#L4768)):*
> ```Go
> 					)
> 				}
> 				// If regions is defined on the database, return it.
> ```

Super nit: "region has been added to the database:
___
*[pkg/sql/sem/builtins/builtins.go, line 4772 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59836#-MSwxURBA9UwKf3GkTCK:-MSwxURBA9UwKf3GkTCL:b-2ks1zl) ([raw file](https://github.com/cockroachdb/cockroach/blob/2342024dc77905ee21a290b1cd430dd179351313/pkg/sql/sem/builtins/builtins.go#L4772)):*
> ```Go
> 					return tree.NewDString(s), nil
> 				}
> 				// Otherwise, return the primary region.
> ```

This comment seems to refer to the return line below, not this if branch.  Can you move it down?  Or add a `!= nil` branch up here for the returning primary region case?
___
*[pkg/sql/sem/builtins/builtins.go, line 4776 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59836#-MSwwDKM8-0twwaiFZG6:-MSwwDKM8-0twwaiFZG7:bcjwpfm) ([raw file](https://github.com/cockroachdb/cockroach/blob/2342024dc77905ee21a290b1cd430dd179351313/pkg/sql/sem/builtins/builtins.go#L4776)):*
> ```Go
> 					return nil, pgerror.Newf(
> 						pgcode.InvalidDatabaseDefinition,
> 						"current database %s is not multi-region enabled",
> ```

Nit: Can we add a test case for this?
___
*[pkg/sql/sem/builtins/builtins.go, line 4783 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59836#-MSwwca8A-rO_W89oR-A:-MSwwca93VcPaYtHvH9P:b-sp94ks) ([raw file](https://github.com/cockroachdb/cockroach/blob/2342024dc77905ee21a290b1cd430dd179351313/pkg/sql/sem/builtins/builtins.go#L4783)):*
> ```Go
> 			},
> 			types.String,
> 			`Returns the given region if the region is affiliated with the current database.
> ```

Nit: "...has been added to the current database"

**Review by otan — COMMENTED** [review]
> This was a pleasant surprise - didn't realize you were working on this yet.

waiting for reviews :P 

> I'm somewhat torn on the naming, especially if we're going to expose this function name to customers in SHOW CREATE TABLE, as I'd imagine we will.

maybe `default_to_primary_region`? don't have a good naming scheme either.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59836#-:-MSyizXmCEY2hGqH9QYq:b-qzws8i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59836#-MSydOqV3W-FdaGW5l8c:-MSydOqV3W-FdaGW5l8d:b-1ly8ze) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e2837f78bec8e12033f0cf09e9e7a02f8a15459/pkg/sql/logictest/testdata/logic_test/multiregion#L28)):*
> ```
> CREATE DATABASE multi_region_test_explicit_primary_region_db PRIMARY REGION "ap-southeast-2" REGIONS "ap-southeast-2", "ca-central-1", "us-east-1" SURVIVE REGION FAILURE
> 
> statement error current database test is not multi-region enabled
> ```

reference (1)
___
*[pkg/sql/sem/builtins/builtins.go, line 4764 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59836#-MSww9bI6P4c-F2IODei:-MSyihaf2PsZTjAzE6nH:bhapouf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2342024dc77905ee21a290b1cd430dd179351313/pkg/sql/sem/builtins/builtins.go#L4764)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Can we add a test case for this?
</blockquote></details>

it's tricky because the current database always exists. i've tried to add one that was similar but it catches on something earlier :) 
___
*[pkg/sql/sem/builtins/builtins.go, line 4776 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59836#-MSwwDKM8-0twwaiFZG6:-MSydRop18CgCkkTfwwp:b6mg395) ([raw file](https://github.com/cockroachdb/cockroach/blob/2342024dc77905ee21a290b1cd430dd179351313/pkg/sql/sem/builtins/builtins.go#L4776)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Can we add a test case for this?
</blockquote></details>

see reference (1)

**Review by ajstorm — APPROVED** [review]
`default_to_database_primary_region()`?  Super long, but at least it tells the whole story.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59836#-:-MT0nQHCACr0vNDXbXMf:b-1wbjxe)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/sem/builtins/builtins.go, line 4776 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59836#-MSwwDKM8-0twwaiFZG6:-MT0mulRES8JRoMLiHho:b-k385ml) ([raw file](https://github.com/cockroachdb/cockroach/blob/2342024dc77905ee21a290b1cd430dd179351313/pkg/sql/sem/builtins/builtins.go#L4776)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

see reference (1)
</blockquote></details>

I like this new reference system.  Thanks!

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59836)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/sql/sem/builtins/builtins.go, line 4776 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59836#-MSwwDKM8-0twwaiFZG6:-MT3Oxc98WoHT0bd5F-s:b-2wljmh) ([raw file](https://github.com/cockroachdb/cockroach/blob/2342024dc77905ee21a290b1cd430dd179351313/pkg/sql/sem/builtins/builtins.go#L4776)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

I like this new reference system.  Thanks!
</blockquote></details>

couldn't figure out how to link line numbers in reviewable. praise github reviews.

**Comment by otan** [comment]
thanksss

bors r=ajstorm

**Comment by otan** [comment]
bors r=ajstorm

**Comment by otan** [comment]
bors r-

something i want to change!

**Comment by otan** [comment]
this is unfortunately blocked until #60310 is in -- otherwise certain backfills fail :(

**Comment by otan** [comment]
bors r=ajstorm

**Comment by otan** [comment]
bors r=ajstorm

**Pull request merged**
