### PR TITLE
sql: ensure index usage stats reset time is same across nodes

### LINKED ISSUE #77451: index usage stats: return cluster wide index usage stats instead of node-local
Currently, our `TableIndexStatsResponse` is expected to provide cluster-wide index usage statistics but its `LastReset` field returns the last reset time of the node-local index usage stats in-memory container. This causes a discrepancy as we use this field to reset the cluster's index usage statistics table.

We expect this field to instead return the last time the cluster's index usage statistics table was reset.

This issue can be mitigated by adding a `lastReset` column to the cluster's index usage statistics table, where we can retrieve the cluster's last index usage statistics rest

### PR DESCRIPTION
**Pull request by THardy98**
Resolves: https://github.com/cockroachdb/cockroach/issues/77451

Previously, the last reset time surfaced by our index usage stats was
node-local. Consequently, the last reset time surfaced to the UI could
change depending on the connected node. This change sets the reset time
across all nodes to the time at which the reset request was received,
ensuring the same reset time across nodes.

Loom video of changes to index usage stats reset tooltips: https://www.loom.com/share/3755a2f658444216b3d60e15c22a9baf

Release note: None

### CODE REVIEW

**Review by j82w — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87962)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @THardy98)

___
*[`pkg/server/index_usage_stats.go` line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87962#-NC0G9AaAPdJxGO7uQfU:-NC0G9AaAPdJxGO7uQfV:b11vgwi) ([raw file](https://github.com/cockroachdb/cockroach/blob/4702c6030a9922140a8483ea0e9474d50a758d46/pkg/server/index_usage_stats.go#L144)):*
> ```Go
> 	// The propagated reset time represents the time at which the reset was
> 	// requested.
> 	if req.ResetTime.Equal(time.Time{}) {
> ```

Would using https://pkg.go.dev/time#Time.IsZero be better?
___
*[`pkg/sql/idxusage/local_idx_usage_stats.go` line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87962#-NC0GdNV2aM6z7nsDFB5:-NC0GdNV2aM6z7nsDFB6:by7cxm1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4702c6030a9922140a8483ea0e9474d50a758d46/pkg/sql/idxusage/local_idx_usage_stats.go#L226)):*
> ```Go
> 
> 	for _, tableStats := range s.mu.usageStats {
> 		tableStats.clear()
> ```

Should this pass in the time so it only clear's values before the passed in time?

**Comment by j82w** [comment]
*[`pkg/sql/idxusage/local_idx_usage_stats.go` line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87962#-NC0GdNV2aM6z7nsDFB5:-NC0GrJWEs7He4NQSEuD:bnthw1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4702c6030a9922140a8483ea0e9474d50a758d46/pkg/sql/idxusage/local_idx_usage_stats.go#L226)):*
<details><summary><i>Previously, j82w wrote…</i></summary><blockquote>

Should this pass in the time so it only clear's values before the passed in time?
</blockquote></details>

My concern is that if there is a thousand nodes or some networking issue it could take several minutes for the clear to be called on the node. The reset time will say 1:00pm, but the current time is 1:05pm. In this example it would be missing 5 minutes of data.

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87962)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @THardy98)

___
*[`pkg/sql/idxusage/local_idx_usage_stats.go` line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87962#-NC0GdNV2aM6z7nsDFB5:-NC0Uo0Q1mflg6SNGDD3:b41lh1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/4702c6030a9922140a8483ea0e9474d50a758d46/pkg/sql/idxusage/local_idx_usage_stats.go#L226)):*
<details><summary><i>Previously, j82w wrote…</i></summary><blockquote>

My concern is that if there is a thousand nodes or some networking issue it could take several minutes for the clear to be called on the node. The reset time will say 1:00pm, but the current time is 1:05pm. In this example it would be missing 5 minutes of data.
</blockquote></details>

This brings some complexity. What we could do, is compare to the `LastRead` value of an index. If the `LastRead` value is < the passed in time, reset the index's statistics. However, in the 1:05pm scenario we could have a read that occurred between the 1:00-1:05pm window. At which point, we'd choose not to reset the statistic when we'd really like to reset the index's statistics, but keep the number of reads that have occurred since 1:00pm. Currently, we don't have a way to track the number of reads from a particular point in time, only the number of reads since the last reset.

An alternative approach could be to use the reset time from the last node, at which point we know the reset has completed for all nodes. In this scenario, we have the reverse issue wherein the reset time will say 1:05pm, but some nodes will carry statistics prior to that timestamp.

Not sure what the "better" approach is here. Is it more intuitive for a user to see statistics they would expect to be cleared, or to not see statistics they perhaps expect to see?

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87962)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @THardy98)

___
*[`pkg/sql/idxusage/local_idx_usage_stats.go` line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87962#-NC0GdNV2aM6z7nsDFB5:-NC0g3NpEXrslLTeJX5C:blx97j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4702c6030a9922140a8483ea0e9474d50a758d46/pkg/sql/idxusage/local_idx_usage_stats.go#L226)):*
<details><summary><i>Previously, j82w wrote…</i></summary><blockquote>

I think returning a precise time is misleading and will cause confusion for users. Why not return the start and end time instead of a precise timestamp?  That way it is clear the reset is distributed and does not occur at the exact time across all nodes.
</blockquote></details>

That seems like the most appropriate approach, I'll get on that.

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87962)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`pkg/server/index_usage_stats.go` line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87962#-NC0G9AaAPdJxGO7uQfU:-NCLzoAl8lqZU_3Zt35q:b-6xqbyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4702c6030a9922140a8483ea0e9474d50a758d46/pkg/server/index_usage_stats.go#L144)):*
<details><summary><i>Previously, j82w wrote…</i></summary><blockquote>

Would using https://pkg.go.dev/time#Time.IsZero be better?
</blockquote></details>

Yup, done :)
___
*[`pkg/sql/idxusage/local_idx_usage_stats.go` line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87962#-NC0GdNV2aM6z7nsDFB5:-NCM-jwA3qTJ_xCI0WJ6:b-1twk3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/4702c6030a9922140a8483ea0e9474d50a758d46/pkg/sql/idxusage/local_idx_usage_stats.go#L226)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

That seems like the most appropriate approach, I'll get on that.
</blockquote></details>

After some discussion with @j82w, we decided the only providing start time (as is) would be sufficient considering other options to implement an `end_time` for the latest reset.

**Comment by THardy98** [comment]
I've added a short note of the displayed last reset time on the corresponding UI pages for transparency. Any thoughts on different wording/phrasing? @maryliag

**Review by maryliag — COMMENTED** [review]
can you add the image of how this looks like on the UI?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87962#-:-NCM41B3Eb2r9_PDkNT-:bjj2r9i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

**Review by THardy98 — COMMENTED** [review]
Loom video of changes to index usage stats reset tooltips: https://www.loom.com/share/3755a2f658444216b3d60e15c22a9baf

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87962#-:-NCMCLgCEH0-52PuEbmG:bsz09wl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

**Review by maryliag — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87962)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @THardy98)

___
*[`pkg/ui/workspaces/cluster-ui/src/databaseTablePage/databaseTablePage.tsx` line 252 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87962#-NCMGvHRAG4-SzU5-h82:-NCMGvHRAG4-SzU5-h83:bw53vsy) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f60636a09b803701d06e0765a8102aab815f233/pkg/ui/workspaces/cluster-ui/src/databaseTablePage/databaseTablePage.tsx#L252)):*
> ```XML
>     return (
>       resetString +
>       ". Note the last reset time is the timestamp at which the reset was last requested."
> ```

nit: "Last reset is the..."
___
*[`pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.tsx` line 135 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87962#-NCMHDvB6ys45hitfVHw:-NCMHDvB6ys45hitfVHx:b-pxumku) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f60636a09b803701d06e0765a8102aab815f233/pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.tsx#L135)):*
> ```XML
>     return (
>       resetString +
>       ". Note the last reset time is the timestamp at which the reset was last requested."
> ```

nit: Last reset is the...

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87962#-:-NCNQ34C07eXUtdiK7R5:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @j82w and @THardy98)

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87962)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @j82w)

___
*[`pkg/ui/workspaces/cluster-ui/src/databaseTablePage/databaseTablePage.tsx` line 252 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87962#-NCMGvHRAG4-SzU5-h82:-NCQ7AhX-GrMDZkagH1g:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f60636a09b803701d06e0765a8102aab815f233/pkg/ui/workspaces/cluster-ui/src/databaseTablePage/databaseTablePage.tsx#L252)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: "Last reset is the..."
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.tsx` line 135 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87962#-NCMHDvB6ys45hitfVHw:-NCQ7BYj9uy0e2j7ofUg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f60636a09b803701d06e0765a8102aab815f233/pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.tsx#L135)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: Last reset is the...
</blockquote></details>

Done.

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87962)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @THardy98)

___
*[`pkg/server/index_usage_stats.go` line 152 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/87962#-NCQHV4WAzTnxkfNktdV:-NCQHV4WAzTnxkfNktdW:b-p65wfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b550f128e3f89ef0210f9b58c1b35fb78be55f94/pkg/server/index_usage_stats.go#L152)):*
> ```Go
> 	localReq := &serverpb.ResetIndexUsageStatsRequest{
> 		NodeID:    "local",
> 		ResetTime: resetTime,
> ```

Can this be renamed from resetTime to clusterResetStartTime or something similar to clarify what the value actually is?
___
*[`pkg/sql/idxusage/local_idx_usage_stats.go` line 228 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/87962#-NCQHzCu5EeAVc7I5tVC:-NCQHzCu5EeAVc7I5tVD:b8n1d7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/b550f128e3f89ef0210f9b58c1b35fb78be55f94/pkg/sql/idxusage/local_idx_usage_stats.go#L228)):*
> ```Go
> 		tableStats.clear()
> 	}
> 	s.mu.lastReset = t
> ```

Should it track both the cluster reset start time and this specific nodes reset time?

**Review by j82w — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87962)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @THardy98)

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87962)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @j82w and @maryliag)

___
*[`pkg/server/index_usage_stats.go` line 152 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/87962#-NCQHV4WAzTnxkfNktdV:-NCQ_o8G9yZn6THx-WZH:bt1b19p) ([raw file](https://github.com/cockroachdb/cockroach/blob/b550f128e3f89ef0210f9b58c1b35fb78be55f94/pkg/server/index_usage_stats.go#L152)):*
<details><summary><i>Previously, j82w wrote…</i></summary><blockquote>

Can this be renamed from resetTime to clusterResetStartTime or something similar to clarify what the value actually is?
</blockquote></details>

Renamed.
___
*[`pkg/sql/idxusage/local_idx_usage_stats.go` line 228 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/87962#-NCQHzCu5EeAVc7I5tVC:-NCQ_pDn8Mdu62OSybbf:b-x3her7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b550f128e3f89ef0210f9b58c1b35fb78be55f94/pkg/sql/idxusage/local_idx_usage_stats.go#L228)):*
<details><summary><i>Previously, j82w wrote…</i></summary><blockquote>

Should it track both the cluster reset start time and this specific nodes reset time?
</blockquote></details>

Changed to track both node-local and cluster-wide reset times.

Local RPC calls return the node-local reset time, cluster-wide fan-outs will return the cluster-wide reset time.
The API response for a table's index usage stats will return the cluster-wide reset time.

**Comment by j82w** [comment]
*[`pkg/server/serverpb/status.proto` line 1799 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/87962#-NCQdVcgAXoQh2R1S_at:-NCQdVch1ECtfUJhWZqE:b-25i49w) ([raw file](https://github.com/cockroachdb/cockroach/blob/b550f128e3f89ef0210f9b58c1b35fb78be55f94/pkg/server/serverpb/status.proto#L1799)):*
> ```protobuf
>   string node_id = 1 [(gogoproto.customname) = "NodeID"];
>   // Timestamp of the latest reset index usage statistics request.
>   google.protobuf.Timestamp reset_time = 3 [(gogoproto.nullable) = false, (gogoproto.stdtime) = true];
> ```

Should this be renamed?

**Review by matthewtodd — APPROVED** [review]

**Pull request merged**
