### PR TITLE
kv: unset CanForwardReadTimestamp flag on batches that spans ranges

### LINKED ISSUE #50202: kv: CanForwardReadTimestamp not unset for multi-range batch
`CanForwardReadTimestamp` is described as:

https://github.com/cockroachdb/cockroach/blob/9a38931424b4b84116da606820d3cde699c90879/pkg/roachpb/api.proto#L1942-L1951

Like `EndTxn.CanCommitAtHigherTimestamp`, we unset the flag in `DistSender` if we notice a batch that is split into multiple sub-batches due to request type incompatibility:
https://github.com/cockroachdb/cockroach/blob/9a38931424b4b84116da606820d3cde699c90879/pkg/kv/kvclient/kvcoord/dist_sender.go#L575

However, we don't unset the flag in `DistSender` if a we notice a batch that is split into multiple sub-batches due to range boundaries in `divideAndSendBatchToRanges`. This was likely missed because doing so was not necessary for `EndTxn.CanCommitAtHigherTimestamp`. I think this is because non-parallel commit `EndTxn`s are prevented from splitting on range boundaries by [this check](https://github.com/cockroachdb/cockroach/blob/9a38931424b4b84116da606820d3cde699c90879/pkg/kv/kvclient/kvcoord/dist_sender.go#L1045-L1047) and parallel commit `EndTxn`s are [never issued](https://github.com/cockroachdb/cockroach/pull/44608) for batches with reads in them (i.e. for batches where any of the requests `NeedsRefresh`).

This doesn't affect the vast majority of workloads, but can lead to serializability violations for those that are affected. The conditions for being effected are:
1. the first operation that the transaction performs is a batch of locking read requests (due to implicit or explicit SFU)
2. this batch of locking reads spans multiple ranges
3. this batch of locking reads is issued in parallel by the `DistSender`
4. this locking read hits contention and is bumped on at least one of the ranges due to a WriteTooOld error

It turns out that the `kv/contention` roachtest meets these requirements perfectly when implicit SFU support is added to `UPSERT` statements: https://github.com/cockroachdb/cockroach/issues/50180. It creates a tremendous amount of contention and issues a batch of locking `ScanRequests` during a LookupJoin as its first operation. This materializes as ConditionFailedErrors (which should be impossible) in the `CPut`s that the `UPSERT` issues to maintain the table's secondary index.

### PR DESCRIPTION
**Pull request by nvb**
Fixes #50202.

In #50202, we saw that we would accidentally allow batches to be split on range boundaries and continue to carry the `CanForwardReadTimestamp` flag. This can lead to serializability violations under very specific conditions:
1. the first operation that the transaction performs is a batch of locking read requests (due to implicit or explicit SFU)
2. this batch of locking reads spans multiple ranges
3. this batch of locking reads is issued in parallel by the DistSender
4. this locking read hits contention and is bumped on at least one of the ranges due to a WriteTooOld error
5. an unreplicated lock from one of the non-refreshed sub-batches is lost during a lease transfer.

It turns out that the `kv/contention` roachtest meets these requirements perfectly when implicit SFU support is added to UPSERT statements: #50180. It creates a tremendous amount of contention and issues a batch of locking ScanRequests during a LookupJoin as its first operation. This materializes as ConditionFailedErrors (which should be impossible) in the CPuts that the UPSERT issues to maintain the table's secondary index.

This PR fixes this bug by ensuring that if a batch is going to be split across ranges and any of its requests would need to refresh on read timestamp bumps, it does not have its CanForwardReadTimestamp flag set. It would be incorrect to allow part of a batch to perform a server-side refresh if another part of the batch might have returned a different result at the higher timestamp, which is a fancy way of saying that it needs to refresh because it is using optimistic locking. Such behavior could cause a transaction to observe an inconsistent snapshot and violate serializability.

It then adds support for locking scans to kvnemesis, which would have caught to bug fairly easily.

Finally, it fixes a KV API UX issue around locking scans and retry errors. Before this change, it was possible for a non-transactional locking scan (which itself doesn't make much sense) to hit a WriteTooOld  retry error. This was caused by eager propagation of WriteTooOld errors from MVCC when FailOnMoreRecent was enabled for an MVCCScan. I'd appreciate if @itsbilal could give that last commit a review.

Release note (bug fix): fix a rare bug where a multi-Range SELECT FOR UPDATE statement containing an IN clause could fail to observe a consistent snapshot and violate serializability.

### CODE REVIEW

**Review by itsbilal — COMMENTED** [review]
Last commit looks good, save for some minor suggestions.

> Reviewed 4 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50633#-:-MAgZ_Gz2LrN8Zclb_Di:b-u30uhv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @itsbilal, and @nvanbenschoten)

___
*[c-deps/libroach/mvcc.h, line 156 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50633#-MAgZRE46YwPcasEfNgM:-MAgZRE5-wERh6fnZXOo:b-rhgek0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f604cb9d8dac006abd136a59648a0d6c15dcb62d/c-deps/libroach/mvcc.h#L156)):*
> ```objc
>  private:
>   const DBScanResults& fillResults() {
>     maybeFailOnMoreRecent();
> ```

We try to keep code between the pebble nad rocksdb versions of the scanner as identical (line-by-line) as possible. Any reason to put this here as opposed to after the getAndAdvance() loop/call ?
___
*[pkg/storage/pebble_mvcc_scanner.go, line 299 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50633#-MAgYriz0hVJpm0ngfhf:-MAgYriz0hVJpm0ngfhg:b17g5bq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f604cb9d8dac006abd136a59648a0d6c15dcb62d/pkg/storage/pebble_mvcc_scanner.go#L299)):*
> ```Go
> 			// we've seen so we know to return an error, but then keep
> 			// scanning so that we can return the largest possible time.
> 			p.mostRecentTS.Forward(p.curKey.Timestamp)
> ```

I assume we don't need a case like this around case 6 below because the intent (if one exists) always has the newest timestamp, right?

**Review by andreimatei — APPROVED** [review]
LGTM

> Before this change, it was possible for a non-transactional locking scan (which itself doesn't make much sense) to hit a WriteTooOld retry error.

Can't we just disallow this kind of scan? The issuer is surely confused, no? Or do these occur naturally in non-txn batches than read and then write the same key?

I don't really understand the commit preamble with the locking scenario. Clearly leaving this flag set when batches are split is bad. Having locking in there, if anything, makes it less bad...

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50633#-:-MAl9gW_2yq9XEExqlxl:b-rketo3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 629 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50633#-MAlBhNz6t2iVwOJZ1Uy:-MAlBhNz6t2iVwOJZ1Uz:btn10y1) ([raw file](https://github.com/cockroachdb/cockroach/blob/34765910c49466faac0595adacbc19ec3aaa46de/pkg/kv/kvclient/kvcoord/dist_sender.go#L629)):*
nit: this sentence is running away a bit, and I found it kinda confusing to read. Maybe just
> // It would be incorrect to allow part of a batch to perform a server-side
  // refresh if another part of the batch needs to perform a client-side refresh
 // Such behavior would cause ...
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 639 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50633#-MAlCerm0_fRkwZgg6Og:-MAlCerm0_fRkwZgg6Oh:b-9csozc) ([raw file](https://github.com/cockroachdb/cockroach/blob/34765910c49466faac0595adacbc19ec3aaa46de/pkg/kv/kvclient/kvcoord/dist_sender.go#L639)):*
> ```Go
> 	}
> 	for _, req := range ba.Requests {
> 		if roachpb.NeedsRefresh(req.GetInner()) {
> ```

`NeedsRefresh()` is not affected by unreplicated locking, right?
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 652 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50633#-MAlAeQm0L-b91M4csJv:-MAlAeQm0L-b91M4csJw:b-acbanp) ([raw file](https://github.com/cockroachdb/cockroach/blob/34765910c49466faac0595adacbc19ec3aaa46de/pkg/kv/kvclient/kvcoord/dist_sender.go#L652)):*
> ```Go
> 			if _, ok := ba.GetArg(roachpb.EndTxn); ok {
> 				log.Fatalf(ctx, "batch unexpected contained requests "+
> 					"that need to refresh and an EndTxn request: %v", ba)
> ```

nit: `%v` seems unusual. Why not `%s`?
___
*[pkg/kv/kvclient/kvcoord/dist_sender_server_test.go, line 2384 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50633#-MAlDc-WAp8yRD38DU3l:-MAlDc-WAp8yRD38DU3m:b-cunpmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/34765910c49466faac0595adacbc19ec3aaa46de/pkg/kv/kvclient/kvcoord/dist_sender_server_test.go#L2384)):*
> ```Go
> 		},
> 		{
> 			name: "write too old with multi-range locking read (err on first range)",
> ```

how about a test without locking reads, just with regular reads?

**Review by andreimatei — COMMENTED** [review]
can we take the opportunity to get rid of EndTxn.CanFwdWhatever ?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50633#-:-MAlF-L25gYsXJu7IMI-:b-7apjh8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by nvb — COMMENTED** [review]
TFTR!

> Can't we just disallow this kind of scan? The issuer is surely confused, no? Or do these occur naturally in non-txn batches than read and then write the same key?

We might be able to disable this kind of scan, but I don't think that's the solution here. The issue fixed by the last commit also affected transactional locking scans.

> I don't really understand the commit preamble with the locking scenario. Clearly leaving this flag set when batches are split is bad. Having locking in there, if anything, makes it less bad...

Locking scans will never be a part of a parallel commit preamble because we don't allow operations that need to refresh to be in flight in parallel with a commit. I'm not sure if that helps.

> can we take the opportunity to get rid of EndTxn.CanFwdWhatever ?

This needs to be backported, so I'm still going to save that for later.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50633#-:-MB17MR4CU2-tLxOP1A6:b-ga25eg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @itsbilal)

___
*[c-deps/libroach/mvcc.h, line 156 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50633#-MAgZRE46YwPcasEfNgM:-MB18xfW64-mzJ27fPlP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f604cb9d8dac006abd136a59648a0d6c15dcb62d/c-deps/libroach/mvcc.h#L156)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

We try to keep code between the pebble nad rocksdb versions of the scanner as identical (line-by-line) as possible. Any reason to put this here as opposed to after the getAndAdvance() loop/call ?
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 629 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50633#-MAlBhNz6t2iVwOJZ1Uy:-MB1BVaWDMFi7HUXBl3p:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/34765910c49466faac0595adacbc19ec3aaa46de/pkg/kv/kvclient/kvcoord/dist_sender.go#L629)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: this sentence is running away a bit, and I found it kinda confusing to read. Maybe just
> // It would be incorrect to allow part of a batch to perform a server-side
  // refresh if another part of the batch needs to perform a client-side refresh
 // Such behavior would cause ...

</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 639 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50633#-MAlCerm0_fRkwZgg6Og:-MB19Or-CUWNS--OFl6D:b-bp5uat) ([raw file](https://github.com/cockroachdb/cockroach/blob/34765910c49466faac0595adacbc19ec3aaa46de/pkg/kv/kvclient/kvcoord/dist_sender.go#L639)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

`NeedsRefresh()` is not affected by unreplicated locking, right?
</blockquote></details>

Nope, because it's best effort and also because unreplicated locking doesn't acquire gap locks.
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 652 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50633#-MAlAeQm0L-b91M4csJv:-MB1BYfCBdHOnUPu5zhu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/34765910c49466faac0595adacbc19ec3aaa46de/pkg/kv/kvclient/kvcoord/dist_sender.go#L652)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: `%v` seems unusual. Why not `%s`?
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvcoord/dist_sender_server_test.go, line 2384 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50633#-MAlDc-WAp8yRD38DU3l:-MB1Bh0YB9eNRwM41UFo:bmmsmz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/34765910c49466faac0595adacbc19ec3aaa46de/pkg/kv/kvclient/kvcoord/dist_sender_server_test.go#L2384)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

how about a test without locking reads, just with regular reads?
</blockquote></details>

A regular read won't hit a WTO error, so there's not much to test.
___
*[pkg/storage/pebble_mvcc_scanner.go, line 299 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50633#-MAgYriz0hVJpm0ngfhf:-MB19l4mCpTckTr1cKnt:btih660) ([raw file](https://github.com/cockroachdb/cockroach/blob/f604cb9d8dac006abd136a59648a0d6c15dcb62d/pkg/storage/pebble_mvcc_scanner.go#L299)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I assume we don't need a case like this around case 6 below because the intent (if one exists) always has the newest timestamp, right?
</blockquote></details>

Yes, exactly.

**Comment by nvanbenschoten** [comment]
Flaked on `pq: no inbound stream connection` in `acceptance/version-upgrade`.

bors r+

**Pull request merged**
