### PR TITLE
sql: new built-in force_internal_error for debugging purposes

### PR DESCRIPTION
**Pull request by knz**
Two salient patches:

###  sql: gate 'sensitive' internal built-ins behind a privilege check

Some built-in functions may have sensitive impact on the overall
behavior of the server; this patch introduces a new built-in
flag 'privileged' which causes type checking to fail on the built-in
if the user is not 'root'

### sql: new built-in for debugging purposes

This patch adds a new built-in `crdb_internal.force_internal_error(<string>)` which
by default simply causes a SQL error.

This built-in is privileged: only the 'root' user can use it.

It also introduces a new cluster setting
`sql.builtin.force_internal_error.panic` which, when true, causes the
aforementioned built-in to trigger a panic on the node. (The setting
is disabled by default.)

### CODE REVIEW

**Comment by bdarnell** [comment]
Reviewed 2 of 3 files at r1, 4 of 6 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/builtins.go, line 214 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15357#-KifNsbpV4N8GY1BRKu2:-KifNsbpV4N8GY1BRKu3:b-1600rg) ([raw file](https://github.com/cockroachdb/cockroach/blob/08bfcdefe187a76a9978978458f5b9141bb65426/pkg/sql/parser/builtins.go#L214)):*
> ```Go
> // panicOnSoftInternalError causes `force_internal_error()` to trigger a panic
> // instead of a regular SQL error.
> var panicOnSoftInternalError = settings.RegisterBoolSetting(
> ```

I think it would be better to have two functions instead of one function whose behavior is controlled by a setting.

---

*[pkg/sql/parser/type_check.go, line 455 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15357#-KifOAqEJNXNoXE-E4NN:-KifOAqEJNXNoXE-E4NO:b7vbyun) ([raw file](https://github.com/cockroachdb/cockroach/blob/08bfcdefe187a76a9978978458f5b9141bb65426/pkg/sql/parser/type_check.go#L455)):*
> ```Go
> 	}
> 
> 	if builtin.privileged && !ctx.privileged {
> ```

Doing this in TypeCheck feels wrong, but I defer to you about whether there is a better place for it. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15357)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/builtins.go, line 214 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15357#-KifNsbpV4N8GY1BRKu2:-KifOzxMcL-u6tLRn4B7:b-a7nv6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/08bfcdefe187a76a9978978458f5b9141bb65426/pkg/sql/parser/builtins.go#L214)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I think it would be better to have two functions instead of one function whose behavior is controlled by a setting.
</blockquote></details>

ok, I'll change that. I don't feel strongly either way.

---

*[pkg/sql/parser/type_check.go, line 455 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15357#-KifOAqEJNXNoXE-E4NN:-KifP5k-jqvpknHbWYsb:bvwiowd) ([raw file](https://github.com/cockroachdb/cockroach/blob/08bfcdefe187a76a9978978458f5b9141bb65426/pkg/sql/parser/type_check.go#L455)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Doing this in TypeCheck feels wrong, but I defer to you about whether there is a better place for it. 
</blockquote></details>

There are two places, either during type checking or during evaluation.
Since expressions are type checked once and may be evaluated many times, I chose to put the overhead of privilege checking in the phase that's just done once.

Can you clarify why you feel it's wrong?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15357)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/type_check.go, line 455 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15357#-KifOAqEJNXNoXE-E4NN:-KifPigMjT-ygGjceitl:b-4ruu84) ([raw file](https://github.com/cockroachdb/cockroach/blob/08bfcdefe187a76a9978978458f5b9141bb65426/pkg/sql/parser/type_check.go#L455)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

There are two places, either during type checking or during evaluation.
Since expressions are type checked once and may be evaluated many times, I chose to put the overhead of privilege checking in the phase that's just done once.

Can you clarify why you feel it's wrong?
</blockquote></details>

Because it has nothing to do with types.

Where do we do table permission checks? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15357)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/builtins.go, line 214 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15357#-KifNsbpV4N8GY1BRKu2:-KifPCeu8SpvYVo8VPcV:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/08bfcdefe187a76a9978978458f5b9141bb65426/pkg/sql/parser/builtins.go#L214)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I think it would be better to have two functions instead of one function whose behavior is controlled by a setting.
</blockquote></details>

+1

---

*[pkg/sql/parser/type_check.go, line 455 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15357#-KifOAqEJNXNoXE-E4NN:-KifQPiuJZwLRuhJ0656:b-9zkgw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/08bfcdefe187a76a9978978458f5b9141bb65426/pkg/sql/parser/type_check.go#L455)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Because it has nothing to do with types.

Where do we do table permission checks? 
</blockquote></details>

the overhead is probably fine in the functions that actually need the check (they're for testing, not calling in a tight loop to backfill an index), so i'd probably have skipped adding another field to `Builtin` and just tested the value in the context directly in the `fn` body.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15357)*

**Comment by knz** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/parser/builtins.go, line 214 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15357#-KifNsbpV4N8GY1BRKu2:-KifRr0_l3I5K1lR9fGX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/08bfcdefe187a76a9978978458f5b9141bb65426/pkg/sql/parser/builtins.go#L214)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

---

*[pkg/sql/parser/type_check.go, line 455 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15357#-KifOAqEJNXNoXE-E4NN:-KifS4Dh2CZDrULZzA3U:b-j3ncms) ([raw file](https://github.com/cockroachdb/cockroach/blob/08bfcdefe187a76a9978978458f5b9141bb65426/pkg/sql/parser/type_check.go#L455)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

the overhead is probably fine in the functions that actually need the check (they're for testing, not calling in a tight loop to backfill an index), so i'd probably have skipped adding another field to `Builtin` and just tested the value in the context directly in the `fn` body.
</blockquote></details>

So I tried to do this and I am running into an annoying issue:  #15363 - this prevents me from performing the check in the EvalContext until I have fixed that other issue.
I would prefer to let it sit in this current place for now; I added a TODO in the relevant places to outline what needs to be done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15357)*

**Comment by dt** [comment]
:lgtm:

---

Review status: 5 of 8 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15357#-:-KifUyyELc3qwkJuU0wM:bnfp4nl)*

**Pull request merged**
