### PR TITLE
server: use rocksdb::GetApproximateSizes for table stats

### PR DESCRIPTION
**Pull request by tbg**
Needs a test. I think I could set up a server with on-disk storage and write to
it until I see a nonzero number from the API endpoint (to check that all the
plumbing was done correctly), but I'll hold off to see if there's something
better that should be done.

Touches https://github.com/cockroachdb/cockroach/issues/18667.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
This approach looks fine to me. We'll need to do some verification as to the accuracy and performance of `GetApproximateSize`. 

---

Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[c-deps/libroach/db.cc, line 1746 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-L06JMcz6um6UmOd-8Ae:-L06JMd-1I1pKkaBaE94:bly084n) ([raw file](https://github.com/cockroachdb/cockroach/blob/664a3a37257614ae6af56cd2fdc75fb7d983cf97/c-deps/libroach/db.cc#L1746)):*
> ```cpp
> 
> DBStatus DBApproximateSize(DBEngine* db, DBKey start, DBKey end, uint64_t *size) {
>   std::string start_key(EncodeKey(start));
> ```

In C++, it is common to const-all-the-variables. `s/std::string/const std::string/g`. `s/rocksdb::Range/const rocksdb::Range/g`. `s/uint8_t flags/const uint8_t flags/g`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-:-L06JpMLAcr-HTmYzAzj:b-m7ahb6)*

**Comment by tschottdorf** [comment]
First trivial test isn't too bad. Ran `tpcc -load` and approximate size comes back as 102MB,



```
$ du -sch cockroach-data
148M	cockroach-data
```

while

```
          this.size = stats.stats.key_bytes // note that key_bytes is omitted in real code right now
                        .add(stats.stats.val_bytes)
                        .add(stats.stats.sys_bytes)
                        .toNumber();
```

results in (unfortunately more accurate) 127.3MB.

We definitely need to understand the characteristics of the approximation better, in particular with the data sets we've seen the logical bytes diverge from.

---

Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[c-deps/libroach/db.cc, line 1746 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-L06JMcz6um6UmOd-8Ae:-L06KhSqK9PKYUDt0guM:b-drhsja) ([raw file](https://github.com/cockroachdb/cockroach/blob/664a3a37257614ae6af56cd2fdc75fb7d983cf97/c-deps/libroach/db.cc#L1746)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

In C++, it is common to const-all-the-variables. `s/std::string/const std::string/g`. `s/rocksdb::Range/const rocksdb::Range/g`. `s/uint8_t flags/const uint8_t flags/g`.
</blockquote></details>

Thanks, done. I const believe you spelled all of them out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-:-L06SN1U7qOm2AtoEttN:b-7upya2)*

**Comment by tschottdorf** [comment]
Ran a compaction, now it looks more accurate:

```
$ du -sch cockroach-data
 89M	cockroach-data
```

approximation is now 85MB (so very close) and logical (obviously) remains at 127.

---

Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-:-L06TMH_QnbUCFmAqpX_:b-eo6lbw)*

**Comment by petermattis** [comment]
Nice! Can we verify that `GetApproximateSize` doesn't perform an disk IO?

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-:-L06TqB-hMET-TM9wdYW:b-895400)*

**Comment by petermattis** [comment]
I suppose another bit to verify is if you have two or more tables. You can use `kv --table=kv1 ...`, `kv --table=kv2` and then write different numbers of entries into the tables (using `--max-ops`).

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-:-L06U-UKBBHx3aAE0vCx:bnq7krq)*

**Comment by tschottdorf** [comment]
```
kv --table kvsmall --max-ops 100000 --min-block-bytes=32 --max-block-bytes=256
kv --table kvlarge --max-ops 1000000 --min-block-bytes=32 --max-block-bytes=256
```

163.7 MiB for `kvlarge`, 17.3 MiB for `kvsmall`. This is encouraging since one is 10x the other.

```
317M	cockroach-data
```

85MB (tpcc) plus 164mb + 18mb = 267mb, so we're undercounting somewhat. After a compaction, the approximate stats remained the comparable, but the directory shrank to 279MB so it's now really close.

It'll be useful to test against heavily compactable datasets. As a sanity check, I dropped the `tpcc` and `kvtest` databases, set a 30s TTL via

```
./cockroach zone set .default --insecure -f -<<EOF
gc:
  ttlseconds: 30
EOF
```

and will report back when the data has been deleted (at which point I expect the storage dir to remain large). I suspect that the approximate stats in that case will be off as well which is unfortunate, but if we want a cheap check then I'm not sure how RocksDB could do better.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-:-L06XhurJwJ0lYgEFCwJ:blyu7ld)*

**Comment by tschottdorf** [comment]
Had my brain switched off for that last part. It's not unfortunate that the approximate size is (expected to be) similar to the disk size. That was what we're after.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-:-L06_YzzWxL54J3funyD:b-ct0suh)*

**Comment by petermattis** [comment]
These numbers are looking fairly good. 

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-:-L06aQ-RAW4EZlqbBgBC:bycx9rx)*

**Comment by tschottdorf** [comment]
Hrm, second part of the experiment didn't go well (mainly because I screwed it up). There's no straightforward way to query the data from the UI after the table is deleted, and by the time I had added some output to `debug compact`, I got ~3MB before and after the compaction. It's also possible that the approximation returned 3MB even though on-disk was ~217 at the time. I didn't check, unfortunately.

@petermattis re: disk i/o, wanna peruse the code below that does the heavy lifting? I *think* this will do disk i/o in the common case. Which may be OK, but something to watch out for. I also think that eventually we'll need some caching in the UI; it's far from snappy even on my idle single-node cluster.

https://github.com/facebook/rocksdb/blob/master/db/version_set.cc#L3537

late addendum: repeated the experiment (dropped a tpcc table). When I switched back to the terminal, the data directory had shrunk to ~55MB from originally ~120MB. I then saw this:

```
approximate database size before compaction: 30 MiB
approximate database size after compaction): 3.1 MiB
```

Seems reasonable enough.

Take all these experiments with a grain of salt, though. We really need to test this (and automate the tests) on larger datasets.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-:-L06inWP2XNkp5Kqbeez:bg8rex1)*

**Comment by tschottdorf** [comment]
@vilterp could you look at the second commit?

**Comment by vilterp** [comment]
Reviewed 11 of 12 files at r1, 2 of 2 files at r2, 2 of 4 files at r3.
Review status: 13 of 17 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/ui/src/views/databases/containers/tableDetails/index.tsx, line 121 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-L06vQUBIFn1ogUuxVPI:-L06vQUBIFn1ogUuxVPJ:bq19t3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1847c141ec57be608c4e2741c04c3302b1ee1de/pkg/ui/src/views/databases/containers/tableDetails/index.tsx#L121)):*
> ```XML
>                 <SummaryHeadlineStat
>                   title="Size"
>                   /* TODO (tschottdorf): where is this tooltip shown? Can't find it. */
> ```

Good catch… Sadly, it appears that the `tooltip` argument is thrown away by the `SummaryHeadlineStat` component: https://github.com/cockroachdb/cockroach/blob/07e2b77d390874e057ec99758c33167f410144c7/pkg/ui/src/views/shared/components/summaryBar/index.tsx#L162-L169

Filed #20638

---

*[pkg/ui/src/views/databases/containers/tableDetails/index.tsx, line 128 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-L06wEsrOQntKNQ4jqiV:-L06wEsrOQntKNQ4jqiW:bdu39qj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1847c141ec57be608c4e2741c04c3302b1ee1de/pkg/ui/src/views/databases/containers/tableDetails/index.tsx#L128)):*
> ```XML
>                   title="Ranges"
>                   /* TODO (tschottdorf): where is this tooltip shown? Can't find it. */
>                   tooltip="The total count of replicas in this database across all replicas."
> ```

Is this really the count of replicas, not ranges? Is the "ranges" column in the table also replicas? If so, either change it to be a count of ranges or also change the `title` here and the label of the column.

Also, I think you meant "The total count of replicas in this database" without the "across all replicas".

---

*[pkg/ui/src/views/databases/data/tableInfo.tsx, line 32 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-L06tEqDPywFgF3z5FXW:-L06tEqDPywFgF3z5FXX:b-jusr8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1847c141ec57be608c4e2741c04c3302b1ee1de/pkg/ui/src/views/databases/data/tableInfo.tsx#L32)):*
> ```XML
>           this.mvcc_stats = stats.stats;
>           this.physical_size = FixLong(stats.approximate_disk_bytes).toNumber();
>           if (!this.physical_size) {
> ```

the only falsey value here should be zero (since `toNumber` should always return a number, not `null` or `undefined`), so let's say `if (this.physical_size === 0)` here to be more explicit.

Also why say 1kb and not just 0? If RocksDB always has a certain overhead, why isn't that returned by its stats function or if not, always added here to `physical_size`?

---

*[pkg/ui/src/views/databases/data/tableInfo.tsx, line 33 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-L06sx8hTga_WSj22w-i:-L06sx8hTga_WSj22w-j:b-ocmecu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1847c141ec57be608c4e2741c04c3302b1ee1de/pkg/ui/src/views/databases/data/tableInfo.tsx#L33)):*
> ```XML
>           this.physical_size = FixLong(stats.approximate_disk_bytes).toNumber();
>           if (!this.physical_size) {
>             this.physical_size = Number(1024); // 1kb
> ```

`Number` constructor unnecessary; just `1024` is fine

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627)*

**Comment by petermattis** [comment]
> I think this will do disk i/o in the common case. Which may be OK, but something to watch out for. I also think that eventually we'll need some caching in the UI; it's far from snappy even on my idle single-node cluster.

I perused the RocksDB code and I'm not seeing I/O in the common case. The one place I see I/O possibly occurring is in retrieving the sstable handle from the cache, but I expect that will almost always be a cache hit. Is there a particular bit of code you expect to be causing I/O there? It looks like most of `VersionSet::ApproximateSize' is operating on in memory structures. `TableReader::ApproximateOffsetOf` will use the cached index data. Very possible I'm missing something.

---

Review status: 13 of 17 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-:-L0A6ssROdlsG-W44QqL:b-jkekce)*

**Comment by tschottdorf** [comment]
Quite likely you're right. I mostly saw that it was using the table readers and wasn't sure whether that would usually be a cache hit. Do you think I should do some more due diligence here, and if so what?

---

Review status: 13 of 17 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-:-L0AloO7c-Qdj_fQ7T01:b-qvvh3w)*

**Comment by petermattis** [comment]
> Do you think I should do some more due diligence here, and if so what?

I'm comfortable with the diligence done so far. Doing something additional would be fairly onerous (i.e. adding an Env wrapper to see if any file I/O is being performed). Or perhaps using strace/truss.

**Comment by bdarnell** [comment]
If we set the rocksdb option [`pin_l0_filter_and_index_blocks_in_cache`](https://github.com/facebook/rocksdb/blob/a9c8d4ef15ed22196260ecf6326a5d3b5a5cbbe8/include/rocksdb/table.h#L74-L78), we should be able to guarantee that it won't go to disk. Without that, we may see cache misses (in my experience the analogous bigtable option was usually a good idea, even though it was expensive in terms of ram)

**Comment by petermattis** [comment]
@bdarnell I believe we specify `cache_index_and_filter_blocks = false` which has the effect of pinning all filter and index blocks in memory:

>   // Indicating if we'd put index/filter blocks to the block cache.
  // If not specified, each "table reader" object will pre-load index/filter
  // block during table initialization.
  bool cache_index_and_filter_blocks = false;

**Comment by couchand** [comment]
Thanks @tschottdorf, this does seem like an improvement.  I'm not sure about just replacing the value, though.  Per the discussion on #20638, maybe we want to surface both?

---

Review status: 13 of 17 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/ui/src/views/databases/data/tableInfo.tsx, line 32 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-L06tEqDPywFgF3z5FXW:-L0B3K4c5k1q-JY0NRSE:b-eat1t6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1847c141ec57be608c4e2741c04c3302b1ee1de/pkg/ui/src/views/databases/data/tableInfo.tsx#L32)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

the only falsey value here should be zero (since `toNumber` should always return a number, not `null` or `undefined`), so let's say `if (this.physical_size === 0)` here to be more explicit.

Also why say 1kb and not just 0? If RocksDB always has a certain overhead, why isn't that returned by its stats function or if not, always added here to `physical_size`?
</blockquote></details>

Yes, I'm not sure I agree with the comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-:-L0B3qsb7GFsdxzK0Nmh:b-7qfmh4)*

**Comment by tschottdorf** [comment]
@couchand noted, and by no means do I want this PR to set anything in stone (note that the MVCC stats are still available in their entirety where they were previously used). I still think it's better to switch from `(meaningless+undocumented+unintuitive)` to `(meaningful+undocumented+intuitive)` in an ad-hoc way now and to discuss the rest in #20638.

For example, it's not clear to me how to expose both while keeping things simple (I'm not much of a UI expert), and also I know for a fact that there are approximately three people in the company that without reading up can give you an almost correct description about what's in which MVCCStats field. If you want actually correct, the number is surely zero. Thus, to correctly describe the semantics of an MVCCStats-derived quantity, I think we'll need a very large tooltip. Both of these are hopefully out of scope here. :smiley: 

@petermattis SGTM. I'll need a review/LGTM of the non-ui code from either you or @bdarnell.

---

Review status: 13 of 17 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-:-L0BVtMnvzH9lf25KqGP:bodhzh6)*

**Comment by couchand** [comment]
Roger, LGTM.  Please do comment over there with your thoughts!

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-:-L0BfDz73mOAIE--EGkK:b3rrteo)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[c-deps/libroach/db.cc, line 1748 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-L0FEZXUnDjHNPyNYkyA:-L0FEZXUnDjHNPyNYkyB:bxfc13y) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4580fed6fcb6d8cc92f83cbba2d44dcb5f976d0/c-deps/libroach/db.cc#L1748)):*
> ```cpp
>   const std::string start_key(EncodeKey(start));
>   const std::string end_key(EncodeKey(end));
>   const rocksdb::Range r((rocksdb::Slice(start_key)), (rocksdb::Slice(end_key)));
> ```

You've got some excessive parentheses here. And I don't think you need to explicitly construct the `rocksdb::Slices`. This should work:


```
const rocksdb::Range r(start_key, end_key);
```

---

*[c-deps/libroach/include/libroach.h, line 116 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-L0FF3yyiiMjEY-0aoy4:-L0FF3yyiiMjEY-0aoy5:bqnwgt2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4580fed6fcb6d8cc92f83cbba2d44dcb5f976d0/c-deps/libroach/include/libroach.h#L116)):*
> ```objc
> 
> // Store the approximate on-disk size of the given key range into the
> // supplied uint64. Does not take into account the memtables.
> ```

Perhaps this function should be named `DBApproximateDiskSize` and then you could get rid of the mention of memtables from this comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-:-L0FFlDJsdf9Xuw-A_Pg:bnfp4nl)*

**Comment by tschottdorf** [comment]
Added a test. From what I can tell, the stats in this simple case (writing ~1MB each time and flushing) are spot on.

---

Review status: 4 of 18 files reviewed at latest revision, 5 unresolved discussions.

---

*[c-deps/libroach/db.cc, line 1748 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-L0FEZXUnDjHNPyNYkyA:-L0FgnK4cY-C5KF2qpll:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4580fed6fcb6d8cc92f83cbba2d44dcb5f976d0/c-deps/libroach/db.cc#L1748)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You've got some excessive parentheses here. And I don't think you need to explicitly construct the `rocksdb::Slices`. This should work:


```
const rocksdb::Range r(start_key, end_key);
```
</blockquote></details>

Done.

---

*[c-deps/libroach/include/libroach.h, line 116 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-L0FF3yyiiMjEY-0aoy4:-L0FeWIYw526mqhWkkAA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4580fed6fcb6d8cc92f83cbba2d44dcb5f976d0/c-deps/libroach/include/libroach.h#L116)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Perhaps this function should be named `DBApproximateDiskSize` and then you could get rid of the mention of memtables from this comment.
</blockquote></details>

Done.

---

*[pkg/ui/src/views/databases/containers/tableDetails/index.tsx, line 128 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-L06wEsrOQntKNQ4jqiV:-L0FhUcx7DH1dw9hqTM6:bh2ze56) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1847c141ec57be608c4e2741c04c3302b1ee1de/pkg/ui/src/views/databases/containers/tableDetails/index.tsx#L128)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

Is this really the count of replicas, not ranges? Is the "ranges" column in the table also replicas? If so, either change it to be a count of ranges or also change the `title` here and the label of the column.

Also, I think you meant "The total count of replicas in this database" without the "across all replicas".
</blockquote></details>

Good point. I got confused: this number is actually `Ranges`. Made the change.

---

*[pkg/ui/src/views/databases/data/tableInfo.tsx, line 32 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-L06tEqDPywFgF3z5FXW:-L0FehY43NPtRNY-Md8a:b-6n4rg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1847c141ec57be608c4e2741c04c3302b1ee1de/pkg/ui/src/views/databases/data/tableInfo.tsx#L32)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

Yes, I'm not sure I agree with the comment.
</blockquote></details>

I don't trust the zeroes I see in the UI (I always assume it's some exception or missing data) and this would've allowed me to distinguish that, but I think two UI team members weigh more than my intuition here.

---

*[pkg/ui/src/views/databases/data/tableInfo.tsx, line 33 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-L06sx8hTga_WSj22w-i:-L0Ff7zx0silht5U-zYq:b-b3jbv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1847c141ec57be608c4e2741c04c3302b1ee1de/pkg/ui/src/views/databases/data/tableInfo.tsx#L33)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

`Number` constructor unnecessary; just `1024` is fine
</blockquote></details>

Obsolete.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-:-L0GP1JCiSk38sDJwI8p:b-yo36sy)*

**Comment by petermattis** [comment]
Review status: 4 of 18 files reviewed at latest revision, 4 unresolved discussions.

---

*[c-deps/libroach/db.cc, line 1748 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-L0FEZXUnDjHNPyNYkyA:-L0GSdcg1vtVO7VqGV3V:b6cbo1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4580fed6fcb6d8cc92f83cbba2d44dcb5f976d0/c-deps/libroach/db.cc#L1748)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:thumbsup: We'll make a C++ programmer out of you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627)*

**Comment by couchand** [comment]
Review status: 4 of 18 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/ui/src/views/databases/data/tableInfo.tsx, line 32 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-L06tEqDPywFgF3z5FXW:-L0GjUlQMV9Qx4etPQO4:bmjblkr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1847c141ec57be608c4e2741c04c3302b1ee1de/pkg/ui/src/views/databases/data/tableInfo.tsx#L32)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

I don't trust the zeroes I see in the UI (I always assume it's some exception or missing data) and this would've allowed me to distinguish that, but I think two UI team members weigh more than my intuition here.
</blockquote></details>

I agree that you shouldn't trust zero (particularly on the size of a database!).  But making it something else just hides the issue, right?

In general, we should definitely do a better job of making it clear when there's missing data vs. zero (the time series charts are particularly guilty on this point).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627)*

**Comment by tschottdorf** [comment]
Review status: 4 of 18 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/ui/src/views/databases/data/tableInfo.tsx, line 32 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627#-L06tEqDPywFgF3z5FXW:-L0GlLOqiXwrQOCUN98K:bb7jk7t) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1847c141ec57be608c4e2741c04c3302b1ee1de/pkg/ui/src/views/databases/data/tableInfo.tsx#L32)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

I agree that you shouldn't trust zero (particularly on the size of a database!).  But making it something else just hides the issue, right?

In general, we should definitely do a better job of making it clear when there's missing data vs. zero (the time series charts are particularly guilty on this point).
</blockquote></details>

Yep, I had filed https://github.com/cockroachdb/cockroach/issues/20691 earlier. Assigned you, but that's just for a lack of better assignee. Feel free to reassign.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20627)*

**Comment by tschottdorf** [comment]
TFTRs!

**Pull request merged**
