### PR TITLE
kv: remove race about finishing a Transport.SendNext() span 

### PR DESCRIPTION
**Pull request by andreimatei**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13467)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/kv/transport.go, line 176 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13467#-KcPLph0XxSSy1C_QoLF:-KcPLph0XxSSy1C_QoLG:bh05a5q) ([raw file](https://github.com/cockroachdb/cockroach/blob/cec0a031ebc32049f8d6dda01280a3036ef3a25e/pkg/kv/transport.go#L176)):*
> ```Go
> 	spanFinished := true
> 	go func() {
> 		defer func() {
> ```

why do we need this defer? we don't have any early return paths (we're enclosing the code below in a `func` just for that)
if we need to keep it, spanFinished should be declared inside `go func` not outside

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13467)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/util/tracing/tracer.go, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13467#-KcPNb6VA7SNSNPakYui:-KcPNb6VA7SNSNPakYuj:b-5c94ri) ([raw file](https://github.com/cockroachdb/cockroach/blob/c730cc1f494e47985ae759ce5d8f730514e8324a/pkg/util/tracing/tracer.go#L50)):*
> ```Go
> func (cr CallbackRecorder) RecordSpan(sp basictracer.RawSpan) {
> 	if cr == nil {
> 		return
> ```

wouldn't it be simpler to write `if cr != nil { cr(sp) }`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13467)*

**Comment by andreimatei** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/kv/transport.go, line 176 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13467#-KcPLph0XxSSy1C_QoLF:-KcPRKGHk5P_RFur7PbI:bjomz2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/cec0a031ebc32049f8d6dda01280a3036ef3a25e/pkg/kv/transport.go#L176)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

why do we need this defer? we don't have any early return paths (we're enclosing the code below in a `func` just for that)
if we need to keep it, spanFinished should be declared inside `go func` not outside
</blockquote></details>

ah I missed the anonymous `func` below. Done, thanks.

---

*[pkg/util/tracing/tracer.go, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13467#-KcPNb6VA7SNSNPakYui:-KcPSr5Rl0AkxWFAUno8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c730cc1f494e47985ae759ce5d8f730514e8324a/pkg/util/tracing/tracer.go#L50)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

wouldn't it be simpler to write `if cr != nil { cr(sp) }`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13467)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13467#-:-KcPULHx_08tzpy_PK7H:bnfp4nl)*

**Pull request merged**
