### PR TITLE
sql: improve OID type representation

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, the Postgres OID type was represented as a `DOidTypeWrapper` around a `DInt`. This was a shortcut implementation that satisfied the basic requirements of OIDs and their cast behaviors, but was missing a critical piece: representation as either an integer, the underlying OID, or a string, the name of the entity that the OID represents.

The `OIDTypeWrapper` OID implementation is now removed. It's replaced by a fully-fledged OID datum, `DOid`, which carries the underlying OID integer, the type of the OID (`regproc`, `regclass`, `regtype`, etc), and the optional entity name that it is resolved to.

This opens the door to having OID columns in `pg_catalog` tables appear as strings when selected but still properly join against other OID columns.

The `typinput` field of `pg_type` is updated to take advantage of this new property, and now displays as a string.

Additionally, several builtins that used to accept integers now properly accept OIDs, and numeric constants are now resolvable to OIDs as they should be.

Updates #13567 

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13896)

### CODE REVIEW

**Comment by knz** [comment]
This is very good work.
As you'd expect I have to voice here my mandatory complaint that we're adopting a pg wart by doing this, nevertheless to its defense the integration is rather clean. 

Some nits remaining, nothing major.

---

Reviewed 18 of 18 files at r1.
Review status: 15 of 18 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/datum.go, line 2013 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13896#-KeZVMnISVBiuCwmA4qS:-KeZVMnISVBiuCwmA4qT:b-rrma9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/97932d70a96bb5b3cb124719fc2d3a235075caa2/pkg/sql/parser/datum.go#L2013)):*
> ```Go
> type DOid struct {
> 	// Oid is the underlying integer for this OID datum.
> 	Oid *DInt
> ```

I suggest dropping the pointer indirection here (= embed the `DInt`)

---

*[pkg/sql/parser/datum.go, line 2227 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13896#-KeZVlZf6WsurGb0cfA3:-KeZVlZf6WsurGb0cfA4:b-rvyjvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/97932d70a96bb5b3cb124719fc2d3a235075caa2/pkg/sql/parser/datum.go#L2227)):*
> ```Go
> // NewDOidFromDInt is a helper routine to create a *DOid (implemented as
> // a *DOidWrapper) initialized from an existing *DInt.
> func NewDOidFromDInt(d *DInt) Datum {
> ```

Once you remove the pointer indirection, change this function's interface to take a plain `int` (perhaps `int64`) here instead and change the callers accordingly.

---

*[pkg/sql/parser/eval.go, line 1988 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13896#-KeZWSAvnqSPnoYcD-0s:-KeZWSAwHgBcDPUGMq1R:bgfjt66) ([raw file](https://github.com/cockroachdb/cockroach/blob/97932d70a96bb5b3cb124719fc2d3a235075caa2/pkg/sql/parser/eval.go#L1988)):*
> ```Go
> 		}
> 
> 	case *IntColType:
> ```

I think casting to int from oid is allowed, right? Then there should be an entry for it in this `case`.
(And add a corresponding cast test)

Next to this please also add a test to ensure that an integer literal is typed as `oid` with the suitable type annotation (`select pg_typeof(1:::oid)` returns "oid")

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13896#-:-KeZXV6wWigPZAsgOJCF:bpp8iao)*

**Comment by jordanlewis** [comment]
TFTR!

---

Review status: 8 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/parser/datum.go, line 2013 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13896#-KeZVMnISVBiuCwmA4qS:-KeZlRsZ5VJc6zoTdDWn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/97932d70a96bb5b3cb124719fc2d3a235075caa2/pkg/sql/parser/datum.go#L2013)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I suggest dropping the pointer indirection here (= embed the `DInt`)
</blockquote></details>

Done.

---

*[pkg/sql/parser/datum.go, line 2227 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13896#-KeZVlZf6WsurGb0cfA3:-KeZlEmdWAhEy793vPI6:b1ggox8) ([raw file](https://github.com/cockroachdb/cockroach/blob/97932d70a96bb5b3cb124719fc2d3a235075caa2/pkg/sql/parser/datum.go#L2227)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Once you remove the pointer indirection, change this function's interface to take a plain `int` (perhaps `int64`) here instead and change the callers accordingly.
</blockquote></details>

Done. Changed this to take a `DInt` instead because it requires less tweaks to appease the compiler.

---

*[pkg/sql/parser/eval.go, line 1988 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13896#-KeZWSAvnqSPnoYcD-0s:-KeZlQlpj-0JI-aq_cHU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/97932d70a96bb5b3cb124719fc2d3a235075caa2/pkg/sql/parser/eval.go#L1988)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think casting to int from oid is allowed, right? Then there should be an entry for it in this `case`.
(And add a corresponding cast test)

Next to this please also add a test to ensure that an integer literal is typed as `oid` with the suitable type annotation (`select pg_typeof(1:::oid)` returns "oid")
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13896#-:-KeZlTDVtxczz0lPtMSK:b-814g8k)*

**Comment by knz** [comment]
LGTM with a minor optimization question

---

Reviewed 8 of 9 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/eval.go, line 2035 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13896#-Ke_6_BxTTCi73kpEof4:-Ke_6_BxTTCi73kpEof5:b-li7wep) ([raw file](https://github.com/cockroachdb/cockroach/blob/44a4092ede9c2c441e70dae960fcc6c56da425b7/pkg/sql/parser/eval.go#L2035)):*
> ```Go
> 			res = NewDInt(DInt(v.Nanos / 1000000000))
> 		case *DOid:
> 			res = NewDInt(v.DInt)
> ```

Since our datums are immutable, I think it would be safe to return `&v.DInt` here. What do you think? (I'm not 100% sure)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13896#-:-Ke_77djvPx9-PNrt68B:bb5mpj0)*

**Comment by jordanlewis** [comment]
Review status: 15 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/parser/eval.go, line 2035 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13896#-Ke_6_BxTTCi73kpEof4:-Ke_8vm9ChtKf3vDwawA:bd70dw3) ([raw file](https://github.com/cockroachdb/cockroach/blob/44a4092ede9c2c441e70dae960fcc6c56da425b7/pkg/sql/parser/eval.go#L2035)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Since our datums are immutable, I think it would be safe to return `&v.DInt` here. What do you think? (I'm not 100% sure)
</blockquote></details>

Seems correct to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13896)*

**Comment by knz** [comment]
Reviewed 1 of 4 files at r4, 3 of 3 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13896)*

**Comment by nvanbenschoten** [comment]
:lgtm: Nice!

---

Reviewed 8 of 18 files at r1, 7 of 9 files at r2, 2 of 4 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/datum.go, line 2225 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13896#-Kea47KsjqLIAhHQ5Vms:-Kea47KsjqLIAhHQ5Vmt:b-r20665) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b30f05c6715472bcb127ac833c97345b2f18c3d/pkg/sql/parser/datum.go#L2225)):*
> ```Go
> }
> 
> // NewDOid is a helper routine to create a *DOid initialized from a DInt.
> ```

nit: This can be moved up in the file to where it should be now that it's not related to the `DOidWrapper` type.

---

*[pkg/sql/parser/type.go, line 562 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13896#-Kea4Y90DHeJZEVa34h-:-Kea4Y91MWCin3VM57rY:b-ud3f2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b30f05c6715472bcb127ac833c97345b2f18c3d/pkg/sql/parser/type.go#L562)):*
> ```Go
> 	return UnwrapType(other) == TypeOid || other == TypeAny
> }
> ```

nit: strange spacing here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13896#-:-Kea6551ogZu2BVY5HqJ:b-8gk8uj)*

**Comment by jordanlewis** [comment]
TFYR

---

Review status: 15 of 19 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/parser/datum.go, line 2225 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13896#-Kea47KsjqLIAhHQ5Vms:-KeaN7did5OX3gOYHR1O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b30f05c6715472bcb127ac833c97345b2f18c3d/pkg/sql/parser/datum.go#L2225)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: This can be moved up in the file to where it should be now that it's not related to the `DOidWrapper` type.
</blockquote></details>

Done.

---

*[pkg/sql/parser/type.go, line 562 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13896#-Kea4Y90DHeJZEVa34h-:-KeaN6LO_vm4sMjKJhD8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b30f05c6715472bcb127ac833c97345b2f18c3d/pkg/sql/parser/type.go#L562)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: strange spacing here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13896#-:-KeaN9I9vungyxIL78TF:bb73zww)*

**Pull request merged**
