### PR TITLE
roachtest: make failure recovery independent

### LINKED ISSUE #119085: roachtest: failover/chaos/read-write failed
roachtest.failover/chaos/read-write [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13958022?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13958022?buildTab=artifacts#/failover/chaos/read-write) on master @ [b2e31876366324c2ebe5c2ad8bbd644997e90864](https://github.com/cockroachdb/cockroach/commits/b2e31876366324c2ebe5c2ad8bbd644997e90864):

```
(test_runner.go:1149).runTest: test timed out (1h0m0s)
test artifacts and logs in: /artifacts/failover/chaos/read-write/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=2</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-13958022/failover-chaos-read-write/1707751001167/1707754759195)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*failover/chaos/read-write.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-36030

### LINKED ISSUE #119347: roachtest: failover/chaos/read-only/lease=expiration failed
roachtest.failover/chaos/read-only/lease=expiration [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14049702?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14049702?buildTab=artifacts#/failover/chaos/read-only/lease=expiration) on master @ [e39dafe6d8c153301ff43ed2b3ed3e13af9ec72a](https://github.com/cockroachdb/cockroach/commits/e39dafe6d8c153301ff43ed2b3ed3e13af9ec72a):

```
(test_runner.go:1153).runTest: test timed out (1h0m0s)
test artifacts and logs in: /artifacts/failover/chaos/read-only/lease=expiration/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=2</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-14049702/failover-chaos-read-only-lease-expiration/1708265062907/1708268818838)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #119334 roachtest: failover/chaos/read-only/lease=expiration failed [C-test-failure O-roachtest O-robot T-kv branch-release-23.2.1-rc release-blocker]
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*failover/chaos/read-only/lease=expiration.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-36161

### LINKED ISSUE #119361: roachtest: failover/chaos/read-write/lease=expiration failed
roachtest.failover/chaos/read-write/lease=expiration [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14059812?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14059812?buildTab=artifacts#/failover/chaos/read-write/lease=expiration) on master @ [e39dafe6d8c153301ff43ed2b3ed3e13af9ec72a](https://github.com/cockroachdb/cockroach/commits/e39dafe6d8c153301ff43ed2b3ed3e13af9ec72a):

```
(test_runner.go:1153).runTest: test timed out (1h0m0s)
test artifacts and logs in: /artifacts/failover/chaos/read-write/lease=expiration/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=2</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-14059812/failover-chaos-read-write-lease-expiration/1708351315123/1708355357227)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*failover/chaos/read-write/lease=expiration.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #119454: roachtest: failover/chaos/read-only failed
roachtest.failover/chaos/read-only [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14090142?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14090142?buildTab=artifacts#/failover/chaos/read-only) on master @ [e50b0ec4d3a53f81e26f3776ae3f3be55d435a9a](https://github.com/cockroachdb/cockroach/commits/e50b0ec4d3a53f81e26f3776ae3f3be55d435a9a):

```
(test_runner.go:1153).runTest: test timed out (1h0m0s)
test artifacts and logs in: /artifacts/failover/chaos/read-only/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=2</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-14090142/failover-chaos-read-only/1708521747284/1708525505854)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*failover/chaos/read-only.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-36206

### PR DESCRIPTION
**Pull request by andrewbaptist**
Previously, the multiple failures were started and finished
independently. This caused a problem if the ability to recover from one
failure depended on a different failure recovering first. To mitigate
this, recover each failure in a separate goroutine. This will allow the
"most important" failure to recover first so that the others can recover
if they depend on each other.

This is more important today while we don't recover from all the failure
modes that chaos implements. Specifically we don't handle partial
partitions fully with epoch leases.

Epic: none
Fixes: #119085
Fixes: #119347
Fixes: #119361
Fixes: #119454

Release note: None

### CODE REVIEW

**Review by erikgrinaker — COMMENTED** [review]
Thanks for picking this up. I suppose this can still be sensitive to races, but probably not enough to really matter.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119650#-:-Ns9MSfhC5Uz1pQmt9Yt:biyjx7v)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @DarrylWong, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/failover.go` line 332 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119650#-Ns9Ln01AQqJXeRPjlj8:-Ns9Ln01AQqJXeRPjlj9:bxshemp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0bef636ed23ce39bcfeed8826180d303df928a/pkg/cmd/roachtest/tests/failover.go#L332)):*
> ```Go
> 				failer := failer
> 				wg.Add(1)
> 				m.Go(func(ctx context.Context) error {
> ```

Might be better to just run the recoveries in goroutines so they execute at the same time. Otherwise, we can get timing issues where one goroutine recovers much earlier than another, causing similar recovery failures.
___
*[`pkg/cmd/roachtest/tests/failover.go` line 350 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119650#-Ns9KWoB2zmyD5XMiOJu:-Ns9KWoB2zmyD5XMiOJv:b-2pg5o4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0bef636ed23ce39bcfeed8826180d303df928a/pkg/cmd/roachtest/tests/failover.go#L350)):*
> ```Go
> 
> 					// Maintain the failure for up to 90 seconds before recovering.
> 					sleepFor(ctx, t, randutil.RandDuration(rng, 90*time.Second))
> ```

We should keep this at a fixed 60 seconds. This is used to signify "does not recover" across all failover tests, and if we make it random there is no way for us to distinguish a slow recovery from no recovery in graphs. In particular, a random value below 10 seconds will make it look like we recovered within the lease interval when we actually didn't.

**Review by andrewbaptist — COMMENTED** [review]
Sorry for the delay in getting this done, hopefully it closes out all the chaos failures.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119650#-:-NvIF-dY1dekc8GAv9RQ:b-r2utvt)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @erikgrinaker, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/failover.go` line 332 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119650#-Ns9Ln01AQqJXeRPjlj8:-NvIExuv0YPGSfaBBx9Z:bp1nusi) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0bef636ed23ce39bcfeed8826180d303df928a/pkg/cmd/roachtest/tests/failover.go#L332)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Might be better to just run the recoveries in goroutines so they execute at the same time. Otherwise, we can get timing issues where one goroutine recovers much earlier than another, causing similar recovery failures.
</blockquote></details>

Agreed - I just moved this to recovery.
___
*[`pkg/cmd/roachtest/tests/failover.go` line 350 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119650#-Ns9KWoB2zmyD5XMiOJu:-NvICWUGAw9o54T3X-ae:b6ke4jg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0bef636ed23ce39bcfeed8826180d303df928a/pkg/cmd/roachtest/tests/failover.go#L350)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

We should keep this at a fixed 60 seconds. This is used to signify "does not recover" across all failover tests, and if we make it random there is no way for us to distinguish a slow recovery from no recovery in graphs. In particular, a random value below 10 seconds will make it look like we recovered within the lease interval when we actually didn't.
</blockquote></details>

Changed back to 60s

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119650#-:-NvIVNm61C7T4NLl-xrU:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @erikgrinaker, and @renatolabs)

**Comment by andrewbaptist** [comment]
TFTR!

bors r=nvanbenschoten

**Comment by kvoli** [comment]
blathers backport 23.2

**Pull request merged**
