### PR TITLE
mutations: fix partial index and FK constraint bug

### PR DESCRIPTION
**Pull request by rafiss**
Do not mutate an index to become a partial index if that index is used
to satisfy a foreign key constraint.

This caused the failure in https://github.com/cockroachdb/cockroach/issues/56845#issuecomment-804621735 

Release note: None

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
Thanks for fixing! LGTM

**Comment by mgartner** [comment]
Hmm, is this comment is no longer applicable: https://github.com/cockroachdb/cockroach/blob/964d890b30c5976e139063a1d28055324cc2aef7/pkg/internal/sqlsmith/setup.go#L73-L78

**Comment by rafiss** [comment]
oh cool! i suppose i can remove that comment then.. i made this change because the order was not respected here: https://github.com/cockroachdb/cockroach/blob/964d890b30c5976e139063a1d28055324cc2aef7/pkg/compose/compare/compare/compare_test.go#L91-L97

**Review by mgartner — APPROVED** [review]
Nice!

**Comment by rafiss** [comment]
tftr!

bors r=mgartner

**Pull request merged**
