### PR TITLE
storage: add single delete callbacks to crash, or increment metrics

### PR DESCRIPTION
**Pull request by sumeerbhola**
Handlers are added for SingleDeleteInvariantViolationCallback and IneffectualSingleDeleteCallback options in Pebble. By default, they crash the process. If crashing is turned off, they increment metrics, storage.single-delete.invariant-violation and
storage.single-delete.ineffectual.

Informs #115881
Informs #114421

Epic: none

Release note (ops change): The cluster settings
storage.single_delete.crash_on_invariant_violation.enabled and storage.single_delete.crash_on_ineffectual.enabled default to true since these can be indicative of a serious bug that could corrupt data.

### CODE REVIEW

**Review by jbowens — APPROVED** [review]
Nice, code :lgtm: 

Looks like the MVCC metamorphic test doesn't like something; maybe we violate something in that test?

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116544#-:-NliKV8A9qXtcjlqM2KD:b-oyrwxe)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> Looks like the MVCC metamorphic test doesn't like something; maybe we violate something in that test?

I've not been able to figure out why the ineffectual callback is firing. Very likely something we are violating in the test. It doesn't seem to be related to https://github.com/cockroachdb/cockroach/issues/96290. delete_range is the most obvious candidate, but in the reproductions I have looked at, I can't spot the problem. I'll keep looking, but I don't want to hold off merging and backporting, so I've overridden the callback in the test. Also there is a tiny change in the metamorphic test to print the operation number in the output. PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116544#-:-Nlj9KzR2805euCvaDI6:b75cevr)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens)

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116544#-:-NljCnvn7B3sp5GqVeyr:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by sumeerbhola** [comment]
bors r=jbowens

**Comment by nicktrav** [comment]
Slick. Fingers crossed this finds something!

**Pull request merged**
