### PR TITLE
bulkio, storageccl: Support implicit credentials for S3

### LINKED ISSUE #31611: bulkio: enable EC2 instance-based temporary credentials for S3 access
In much the same way that GCE instances can be given implicit credentials for access to Google cloud storage, AWS EC2 instances can be associated with an IAM role; in this case, applications on the EC2 instance can retrieve and use temporary credentials associated with the role. The AWS documentation for this functionality is [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html); in the Go SDK, I believe this is in the `ec2rolecreds` package.

We should implement this implicit authentication method, and ensure that the user interface for it matches what we do for implict GCE instance auth (see #31602).

### PR DESCRIPTION
**Pull request by g3orgia**
Currently, when specifying an s3 bucket for bulk IO, we
enforce that you provide access keys. We would like to
support implicit authentication with AWS, which can be
achieved by simply omitting the access keys, provided
they have other credentials setup locally. This is
especially useful when used on an EC2 machine.

This change adds an `auth` parameter (similar to GCS),
when set to `auth=implicit`, allows the user to omit
the access keys and therefore use the configured IAM
role on the local machine.

Fixes: #31611

Release note (enterprise change): when listing s3 files
for bulk IO, users are no longer required to provide
access keys, if `auth=implicit`.

Release justification: This unblocks a high-value customer's
workflow. It is a low-risk change that does not change current
behavior when added parameter is unused.

### CODE REVIEW

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40836)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @g3orgia and @lucy-zhang)

___
*[pkg/ccl/storageccl/export_storage.go, line 589 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40836#-Lp4yyRnCNsyOjoXJAla:-Lp4yyRnCNsyOjoXJAlb:b-ujannr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d23f3139673b2ccb6272a7d6d7ce2160238e89af/pkg/ccl/storageccl/export_storage.go#L589)):*
> ```Go
> 	}
> 
> 	// "specified": use keys in settings; error if not present.
> ```

`settings` implies we're getting the key from the cluster settings. I would say something like `use the credentials in the URI params`.
___
*[pkg/ccl/storageccl/export_storage.go, line 592 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40836#-Lp4unQQ9ouJkqaoJJ9s:-Lp4unQQ9ouJkqaoJJ9t:bvahmae) ([raw file](https://github.com/cockroachdb/cockroach/blob/d23f3139673b2ccb6272a7d6d7ce2160238e89af/pkg/ccl/storageccl/export_storage.go#L592)):*
> ```Go
> 	// "implicit": enable SharedConfig, which loads in credentials from environment.
> 	//             Detailed in https://docs.aws.amazon.com/sdk-for-go/api/aws/session/
> 	// "default" or "": same as specified.
> ```

Do we want to have a `"default"` option at all? For GCS this means getting the credentials from the cluster settings and returning an error if it's not set, which we don't support for S3. I think only supporting `"specified"`, `"implicit"`, and `""` should be fine.
___
*[pkg/ccl/storageccl/export_storage_test.go, line 438 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40836#-Lp55c2E7ryf-1-4Gqws:-Lp50t4kADRoLnKfQ6nU:b-mimfs5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d23f3139673b2ccb6272a7d6d7ce2160238e89af/pkg/ccl/storageccl/export_storage_test.go#L438)):*
> ```Go
> 	})
> 
> 	testExportStore(t,
> ```

Can this be wrapped in its own subtest too?

**Review by g3orgia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40836)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/ccl/storageccl/export_storage.go, line 589 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40836#-Lp4yyRnCNsyOjoXJAla:-Lp59ddi7Ed82z23_SL_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d23f3139673b2ccb6272a7d6d7ce2160238e89af/pkg/ccl/storageccl/export_storage.go#L589)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

`settings` implies we're getting the key from the cluster settings. I would say something like `use the credentials in the URI params`.
</blockquote></details>

Done.
___
*[pkg/ccl/storageccl/export_storage.go, line 592 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40836#-Lp4unQQ9ouJkqaoJJ9s:-Lp59fUF6dSMscT9bCpO:b-ofpv4h) ([raw file](https://github.com/cockroachdb/cockroach/blob/d23f3139673b2ccb6272a7d6d7ce2160238e89af/pkg/ccl/storageccl/export_storage.go#L592)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Do we want to have a `"default"` option at all? For GCS this means getting the credentials from the cluster settings and returning an error if it's not set, which we don't support for S3. I think only supporting `"specified"`, `"implicit"`, and `""` should be fine.
</blockquote></details>

Hmm I agree, will remove the `default` option.
___
*[pkg/ccl/storageccl/export_storage_test.go, line 438 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40836#-Lp55c2E7ryf-1-4Gqws:-Lp5AMMN0bzWltWcepS8:b-3qk5us) ([raw file](https://github.com/cockroachdb/cockroach/blob/d23f3139673b2ccb6272a7d6d7ce2160238e89af/pkg/ccl/storageccl/export_storage_test.go#L438)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Can this be wrapped in its own subtest too?
</blockquote></details>

Done. Naming it `auth-specified`, similar to `TestPutGoogleCloud`.

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40836)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @g3orgia and @lucy-zhang)

___
*[pkg/ccl/storageccl/export_storage.go, line 597 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40836#-LpZiZh88WnJLmZQkQMb:-LpZiZh88WnJLmZQkQMc:b-yl76ot) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8a55eecf797684ee68c0a81c83d9c47511f1693/pkg/ccl/storageccl/export_storage.go#L597)):*
> ```Go
> 	case "", authParamSpecified:
> 		if conf.AccessKey == "" {
> 			return nil, errors.Errorf("s3 uri missing %q parameter, auth=%q", S3AccessKeyParam, conf.Auth)
> ```

I might make this error message slightly less terse. The GCS equivalent has this:
```
			return nil, errors.Errorf(
				"%s is set to '%s', but %s is not set",
				AuthParam,
				authParamSpecified,
				CredentialsParam,
			)
```
___
*[pkg/ccl/storageccl/export_storage_test.go, line 405 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40836#-LpZhAVUDe_cvQWQVUD9:-LpZhAVUDe_cvQWQVUDA:b49mjyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8a55eecf797684ee68c0a81c83d9c47511f1693/pkg/ccl/storageccl/export_storage_test.go#L405)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 
> 	creds, err := credentials.NewEnvCredentials().Get()
> ```

Should this go in the `auth-specified` subtest as well?
___
*[pkg/ccl/storageccl/export_storage_test.go, line 421 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40836#-LpZhIlMBywipUJNkmVi:-LpZhIlMBywipUJNkmVj:bzemgul) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8a55eecf797684ee68c0a81c83d9c47511f1693/pkg/ccl/storageccl/export_storage_test.go#L421)):*
> ```Go
> 	t.Run("auth-implicit", func(t *testing.T) {
> 		// Only test if default role exists
> 		credentialsProvider := credentials.SharedCredentialsProvider{}
> ```

Is there any additional configuration (setting env vars, etc.) that needs to be done to run this subtest locally? I'm not sure how to set implicit credentials on my own computer. If there are any additional steps, it would be good to have a comment documenting them.

**Review by g3orgia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40836)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/ccl/storageccl/export_storage.go, line 597 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40836#-LpZiZh88WnJLmZQkQMb:-Lpd6LPoDI_76HZjrhRv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8a55eecf797684ee68c0a81c83d9c47511f1693/pkg/ccl/storageccl/export_storage.go#L597)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I might make this error message slightly less terse. The GCS equivalent has this:
```
			return nil, errors.Errorf(
				"%s is set to '%s', but %s is not set",
				AuthParam,
				authParamSpecified,
				CredentialsParam,
			)
```
</blockquote></details>

Done.
___
*[pkg/ccl/storageccl/export_storage_test.go, line 405 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40836#-LpZhAVUDe_cvQWQVUD9:-Lpd6r9b1OOetDYQnSH1:b-eus855) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8a55eecf797684ee68c0a81c83d9c47511f1693/pkg/ccl/storageccl/export_storage_test.go#L405)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Should this go in the `auth-specified` subtest as well?
</blockquote></details>

Nope, this is the initial check to see if we have any credentials setup (through the symlinked file). If those credentials are not there, we should skip all S3 related tests.
___
*[pkg/ccl/storageccl/export_storage_test.go, line 421 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40836#-LpZhIlMBywipUJNkmVi:-Lpd7BOfD-qDDUwJs1aV:b-hcn3a8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8a55eecf797684ee68c0a81c83d9c47511f1693/pkg/ccl/storageccl/export_storage_test.go#L421)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Is there any additional configuration (setting env vars, etc.) that needs to be done to run this subtest locally? I'm not sure how to set implicit credentials on my own computer. If there are any additional steps, it would be good to have a comment documenting them.
</blockquote></details>

Ah yes, you'd have to set up an IAM role locally. Will add link to documentation about setting that up.

**Review by thoszhang — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40836)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @g3orgia and @lucy-zhang)

___
*[pkg/ccl/storageccl/export_storage_test.go, line 405 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40836#-LpdcVaR8WvvOQkGN--E:-LpdcVaS5laqKiuLuvZ3:b9ev0wv) ([raw file](https://github.com/cockroachdb/cockroach/blob/113c181212a793d7f90f98d1ac3e206cc70188f7/pkg/ccl/storageccl/export_storage_test.go#L405)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 
> 	// If environment credential are not present, we want to
> ```

`credentials`

**Pull request merged**
