### PR TITLE
storage/concurrency: test and bugfix for clearing the locks when the

### PR DESCRIPTION
**Pull request by sumeerbhola**
size limit of the lockTable is exceeded

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45080#-:-M-zNcES34kmi1zFoPRO:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/storage/concurrency/lock_table.go, line 1497 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45080#-M-zI-jZD5pfXPKMmt-Z:-M-zI-j_BY124SAS7j0X:b3fpg7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/521f0426903cc772db11e9e53137568bda4f9407/pkg/storage/concurrency/lock_table.go#L1497)):*
> ```Go
> 		tree := &t.locks[i]
> 		tree.mu.Lock()
> 		var locksToClear []*lockState
> ```

Heh, I noticed this over in https://github.com/cockroachdb/cockroach/pull/45062/commits/3f987df56d7215b5e39d1bb025a8e74b46621695 as well.
___
*[pkg/storage/concurrency/testdata/lock_table/size_limit_exceeded, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45080#-M-zMYDN603854jBqkKR:-M-zMYDN603854jBqkKS:b-gcef0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/521f0426903cc772db11e9e53137568bda4f9407/pkg/storage/concurrency/testdata/lock_table/size_limit_exceeded#L52)):*
> ```
> local: num=0
> 
> acquire r=req1 k=c durability=r
> ```

Add a comment that we don't expect this to add a lock to the table and that we should remove this step entirely when we eventually immediately add replicated locks to the lock table.
___
*[pkg/storage/concurrency/testdata/lock_table/size_limit_exceeded, line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45080#-M-zN-es6YFvOxAG_QdR:-M-zN-es6YFvOxAG_QdS:b7gypn) ([raw file](https://github.com/cockroachdb/cockroach/blob/521f0426903cc772db11e9e53137568bda4f9407/pkg/storage/concurrency/testdata/lock_table/size_limit_exceeded#L87)):*
> ```
> ----
> start-waiting: true
> ```

Could you add a `print` right here?
___
*[pkg/storage/concurrency/testdata/lock_table/size_limit_exceeded, line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45080#-M-zNFr_7Vu_ABlSkjVC:-M-zNFra7T9mFPLfNkRf:b-dk8kec) ([raw file](https://github.com/cockroachdb/cockroach/blob/521f0426903cc772db11e9e53137568bda4f9407/pkg/storage/concurrency/testdata/lock_table/size_limit_exceeded#L190)):*
> ```
> start-waiting: false
> 
> acquire r=req8 k=e durability=u
> ```

Add a comment that this is whether the lock table hits its size limit and evicts everything except the discovered lock without a reservation.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45080)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten and @sumeerbhola)

___
*[pkg/storage/concurrency/testdata/lock_table/size_limit_exceeded, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45080#-M-zMYDN603854jBqkKR:-M-zSBay3FR634jZvmKc:bbb93oy) ([raw file](https://github.com/cockroachdb/cockroach/blob/521f0426903cc772db11e9e53137568bda4f9407/pkg/storage/concurrency/testdata/lock_table/size_limit_exceeded#L52)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Add a comment that we don't expect this to add a lock to the table and that we should remove this step entirely when we eventually immediately add replicated locks to the lock table.
</blockquote></details>

Added a slightly different comment. We won't need the unreplicated lock acquisition.
___
*[pkg/storage/concurrency/testdata/lock_table/size_limit_exceeded, line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45080#-M-zN-es6YFvOxAG_QdR:-M-zSS3r3MHfcU8Cj1a6:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/521f0426903cc772db11e9e53137568bda4f9407/pkg/storage/concurrency/testdata/lock_table/size_limit_exceeded#L87)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you add a `print` right here?
</blockquote></details>

Done
___
*[pkg/storage/concurrency/testdata/lock_table/size_limit_exceeded, line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45080#-M-zNFr_7Vu_ABlSkjVC:-M-zSglx1cwsIqUswwfc:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/521f0426903cc772db11e9e53137568bda4f9407/pkg/storage/concurrency/testdata/lock_table/size_limit_exceeded#L190)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Add a comment that this is whether the lock table hits its size limit and evicts everything except the discovered lock without a reservation.
</blockquote></details>

Done

**Review by nvb — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45080)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @sumeerbhola)

**Pull request merged**
