### PR TITLE
geo: make GEOS output EWKB and handle EWKT parsing

### PR DESCRIPTION
**Pull request by otan**
* Make the WKBWriter from GEOS output SRIDs, confirming to the EWKB
standard. Furthermore, set SRIDs on the GEOM object if available.
* Extend the ParseGeo* functions to parse EWKT. EWKT is WKT with an
`SRID=int;` attached at the front.
* Default SRIDs for Geography types to 4326, as PostGIS always does.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47352)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/geo/parse.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47352#-M4orNJLBuL7EywQpq_9:-M4orNJLBuL7EywQpq_A:bdqudsf) ([raw file](https://github.com/cockroachdb/cockroach/blob/355901081166cc933296cd06dc5b1256fe333403/pkg/geo/parse.go#L95)):*
> ```Go
> 		end := strings.Index(str[sridPrefixLen:], ";")
> 		if end != -1 {
> 			sridInt64, err := strconv.ParseInt(str[sridPrefixLen:sridPrefixLen+end], 10, 64)
> ```

why is this not `... 10, 32)` given that SRIDs are `int32`?
and are SRIDs allowed to be negative?
___
*[pkg/geo/parse.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47352#-M4orjCd7A0ZQa2qR0LV:-M4orjCd7A0ZQa2qR0LW:bty8mna) ([raw file](https://github.com/cockroachdb/cockroach/blob/355901081166cc933296cd06dc5b1256fe333403/pkg/geo/parse.go#L100)):*
> ```Go
> 			}
> 			if sridInt64 != 0 {
> 				srid = geopb.SRID(sridInt64)
> ```

why can't the `defaultSRID` be overridden by a 0 SRID?
___
*[pkg/geo/parse_test.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47352#-M4osHLZ6URUwwIDs6t0:-M4osHLZ6URUwwIDs6t1:b1uaiym) ([raw file](https://github.com/cockroachdb/cockroach/blob/355901081166cc933296cd06dc5b1256fe333403/pkg/geo/parse_test.go#L20)):*
> ```Go
> )
> 
> func TestParseGeometry(t *testing.T) {
> ```

datadriven tests are easier to extend with new cases -- how about turning these into datadriven tests?
___
*[pkg/geo/geos/geos_unix.cc, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47352#-M4ot5M96Oki0i4MkPZS:-M4ot5M96Oki0i4MkPZT:bxo47cb) ([raw file](https://github.com/cockroachdb/cockroach/blob/355901081166cc933296cd06dc5b1256fe333403/pkg/geo/geos/geos_unix.cc#L55)):*
> ```cpp
>                                            size_t*);
> typedef void (*CR_GEOS_WKBWriter_setByteOrder_r)(CR_GEOS_Handle, CR_GEOS_WKBWriter, int);
> typedef void (*CR_GEOS_WKBWriter_setByteOrder_r)(CR_GEOS_Handle, CR_GEOS_WKBWriter, int);
> ```

is this a duplicated typedef?
___
*[pkg/geo/geos/geos_unix.cc, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47352#-M4otaFS7NThMqH0YGr_:-M4otaFS7NThMqH0YGra:b-qbzhg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/355901081166cc933296cd06dc5b1256fe333403/pkg/geo/geos/geos_unix.cc#L75)):*
> ```cpp
>   CR_GEOS_Context_setErrorMessageHandler_r GEOSContext_setErrorMessageHandler_r;
> 
>   CR_GEOS_GEOSSetSRID_r GEOSSetSRID_r;
> ```

can this be CR_GEOS_SetSRID_r? We've done similar simplifications in the previously introduced types.
Same question about CT_GEOS_WKBWriter_setIncludedSRID_r.
___
*[pkg/geo/geos/geos_unix.cc, line 220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47352#-M4ouFGPAHBaNJWep1Eu:-M4ouFGPAHBaNJWep1Ev:bli0ils) ([raw file](https://github.com/cockroachdb/cockroach/blob/355901081166cc933296cd06dc5b1256fe333403/pkg/geo/geos/geos_unix.cc#L220)):*
> ```cpp
>     if (clippedGeom != nullptr) {
>       auto wkbWriter = lib->GEOSWKBWriter_create_r(handle);
>       lib->GEOSWKBWriter_setByteOrder_r(handle, wkbWriter, 1);
> ```

do we need to do the `SetSRID_r` and `WKBWriter_setIncludeSRID_r` dance here?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47352)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/geo/parse.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47352#-M4orNJLBuL7EywQpq_9:-M4p12WS-eluuPe_SDPQ:b-rfz3gk) ([raw file](https://github.com/cockroachdb/cockroach/blob/355901081166cc933296cd06dc5b1256fe333403/pkg/geo/parse.go#L95)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why is this not `... 10, 32)` given that SRIDs are `int32`?
and are SRIDs allowed to be negative?
</blockquote></details>

Ah, force of habit.
And no, but we should check SRID validity outside of this function (since we have to do a lookup anyway). I have left TODOs to check for this.
___
*[pkg/geo/parse.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47352#-M4orjCd7A0ZQa2qR0LV:-M4p1FST4q5MWENc66tC:b-yqkwhn) ([raw file](https://github.com/cockroachdb/cockroach/blob/355901081166cc933296cd06dc5b1256fe333403/pkg/geo/parse.go#L100)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why can't the `defaultSRID` be overridden by a 0 SRID?
</blockquote></details>

0 always seem to take less priority in postgis.
in particular, when casting to geography, having `SRID=0` in front will still leave the SRID as 4326:
```
otan=# select 'SRID=0;POINT(1.0 1.0)'::geography;
                     geography
----------------------------------------------------
 0101000020E6100000000000000000F03F000000000000F03F
(1 row)

otan=# select ST_SRID('SRID=0;POINT(1.0 1.0)'::geography);
 st_srid
---------
    4326
(1 row)
```
___
*[pkg/geo/parse_test.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47352#-M4osHLZ6URUwwIDs6t0:-M4p0f4n6OSpuO79vCXi:blln3mx) ([raw file](https://github.com/cockroachdb/cockroach/blob/355901081166cc933296cd06dc5b1256fe333403/pkg/geo/parse_test.go#L20)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

datadriven tests are easier to extend with new cases -- how about turning these into datadriven tests?
</blockquote></details>

Hmm, I think it's easier here in this case (at least for now).  Maybe later if we have too many types (although one could argue to put this in the sql eval datadriven tests, but i'm trying to keep geo concepts separate)
___
*[pkg/geo/geos/geos_unix.cc, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47352#-M4ot5M96Oki0i4MkPZS:-M4p1yENAwMDPx-zdpRh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/355901081166cc933296cd06dc5b1256fe333403/pkg/geo/geos/geos_unix.cc#L55)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is this a duplicated typedef?
</blockquote></details>

Done.
___
*[pkg/geo/geos/geos_unix.cc, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47352#-M4otaFS7NThMqH0YGr_:-M4p1ncA8ce0KRDMNa3l:bb3fwfo) ([raw file](https://github.com/cockroachdb/cockroach/blob/355901081166cc933296cd06dc5b1256fe333403/pkg/geo/geos/geos_unix.cc#L75)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can this be CR_GEOS_SetSRID_r? We've done similar simplifications in the previously introduced types.
Same question about CT_GEOS_WKBWriter_setIncludedSRID_r.
</blockquote></details>

Ah I was copying the GEOS name. this is fine too - changed.
___
*[pkg/geo/geos/geos_unix.cc, line 220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47352#-M4ouFGPAHBaNJWep1Eu:-M4p404XDJ_BXDEyAeng:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/355901081166cc933296cd06dc5b1256fe333403/pkg/geo/geos/geos_unix.cc#L220)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

do we need to do the `SetSRID_r` and `WKBWriter_setIncludeSRID_r` dance here?
</blockquote></details>

Done.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47352#-:-M4p9DT8CzIqbgMJnSso:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/parse.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47352#-M4orjCd7A0ZQa2qR0LV:-M4p8E6G9Hznr9O-jIC2:bvdx5hv) ([raw file](https://github.com/cockroachdb/cockroach/blob/355901081166cc933296cd06dc5b1256fe333403/pkg/geo/parse.go#L100)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

0 always seem to take less priority in postgis.
in particular, when casting to geography, having `SRID=0` in front will still leave the SRID as 4326:
```
otan=# select 'SRID=0;POINT(1.0 1.0)'::geography;
                     geography
----------------------------------------------------
 0101000020E6100000000000000000F03F000000000000F03F
(1 row)

otan=# select ST_SRID('SRID=0;POINT(1.0 1.0)'::geography);
 st_srid
---------
    4326
(1 row)
```
</blockquote></details>

please add a code comment.
___
*[pkg/geo/parse_test.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47352#-M4osHLZ6URUwwIDs6t0:-M4p8O5WE-bsQKEieRPf:b32wtd) ([raw file](https://github.com/cockroachdb/cockroach/blob/355901081166cc933296cd06dc5b1256fe333403/pkg/geo/parse_test.go#L20)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Hmm, I think it's easier here in this case (at least for now).  Maybe later if we have too many types (although one could argue to put this in the sql eval datadriven tests, but i'm trying to keep geo concepts separate)
</blockquote></details>

ok
___
*[pkg/geo/geos/geos_unix.cc, line 220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47352#-M4ouFGPAHBaNJWep1Eu:-M4p957I4LjEefwea3d1:b75ltg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/355901081166cc933296cd06dc5b1256fe333403/pkg/geo/geos/geos_unix.cc#L220)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

can you add a test case to the `clip` file that exercises this new code.

**Comment by otan** [comment]
bors r=sumeerbhola

**Comment by otan** [comment]
bors r=sumeerbhola

**Pull request merged**
