### PR TITLE
release-22.2: roachtest: replace gs://cockroach-fixtures with gs://cockroach-fixtures-us-east1

### PR DESCRIPTION
**Pull request by msbutler**
Informs #111371

Release note: none

Release justification: test infra change

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]
Thanks!

**Comment by msbutler** [comment]
gce roachtest run: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel?buildTypeTab=overview&branch=117319&mode=builds

**Comment by msbutler** [comment]
aws run https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel?branch=117319&buildTypeTab=overview&mode=builds#all-projects

**Comment by celiala** [comment]
blathers backport staging-v22.2.18

**Pull request merged**
