### PR TITLE
opt: make uniqueness checks for partial unique indexes on virtual columns efficient

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: add GenerateLookupJoinWithVirtualColsAndFilter

The GenerateLookupJoinWithVirtualColsAndFilter exploration rule has been
added to the optimizer. It is like GenerateLookupJoinWithVirtualCols but
it matches joins where the right side has the pattern
`(Project (Select (Scan)))`. The Select filter is merged with the ON
condition.

This rule is necessary in order to generate lookup joins on indexes with
virtual columns when a non-virtual column filter has been pushed down to
the right side of the join. This is also necessary for generating lookup
joins on partial indexes with virtual columns.

Informs #68132

Release note (performance improvement): Lookup joins on partial indexes
with virtual columns are no considered by the optimizer, resulting in
more efficient query plans in some cases.

#### opt: add DeduplicateSelectFilters normalization rule

DeduplicateSelectFilters removes duplicate filters in a Select.
Duplicate filters are usually eliminated by a combination of
filter-simplifying rules, like InlineConstVar, SimplifySelectFilters,
and ConsolidateSelectFilters. However, duplicate filters can be
generated by the interaction of the normalization rules
PushFilterIntoJoinLeftAndRight and PushSelectIntoInlinableProject when a
table has a virtual column.

This rule is low priority. All other Select rules should run first to
avoid trying to deduplicate filters multiple times during normalization.

This rule is necessary in order to generate lookup joins on partial
indexes on virtual columns. Without this rule, duplicate filters will
prevent GenerateLookupJoinsWithVirtualColsAndFilter from firing during
exploration.

Release note: None

#### sql: add tests for partial virtual uniqueness checks on RBR tables

This commit adds tests to ensure that partial virtual index uniqueness
checks for `REGIONAL BY ROW` tables are efficient and behave correctly.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: Nice!

> Reviewed 3 of 3 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68568#-:-MggqagbEBItoneIjUMQ:b-8gk8uj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/norm/testdata/rules/select, line 536 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68568#-Mggq6pO38E_W5TIu_Li:-Mggq6pO38E_W5TIu_Lj:b1orvdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e485d27c8f88195558f4b18f35c7062b0c34bbd/pkg/sql/opt/norm/testdata/rules/select#L536)):*
> ```
>     [
>         (Or (Eq (Var "u") (Const 10 "int")) (Eq (Var "u") (Const 20 "int")))
>         (Or (Eq (Var "v") (Const 20 "int")) (Eq (Var "u") (Const 10 "int")))
> ```

did you mean to make this `u`?
___
*[pkg/sql/opt/xform/testdata/rules/join, line 5079 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68568#-MggooNPEDBsGeWWly8C:-MggooNPEDBsGeWWly8D:bxldpxh) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca1a1f0761528c3aed8df3f1d6baf897cdfe567/pkg/sql/opt/xform/testdata/rules/join#L5079)):*
> ```
>  │    └── filters (true)
>  └── filters (true)
> ```

what about adding a test case for partial index predicate + remaining filter?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68568)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/norm/testdata/rules/select, line 536 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68568#-Mggq6pO38E_W5TIu_Li:-MgmUi3ZCV0fJ5abJyNg:bt0cpu0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e485d27c8f88195558f4b18f35c7062b0c34bbd/pkg/sql/opt/norm/testdata/rules/select#L536)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

did you mean to make this `u`?
</blockquote></details>

I meant the line above to have a `v`. Good catch! Fixed.
___
*[pkg/sql/opt/xform/testdata/rules/join, line 5079 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68568#-MggooNPEDBsGeWWly8C:-MgmdPd27WAb1zSLyRsj:b-uisda4) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca1a1f0761528c3aed8df3f1d6baf897cdfe567/pkg/sql/opt/xform/testdata/rules/join#L5079)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

what about adding a test case for partial index predicate + remaining filter?
</blockquote></details>

Good idea, added. We handle some of these cases already, but I left TODOs in cases that we don't handle. They are similar to other unhandled cases above that have TODOs.

**Review by rytaft — APPROVED** [review]
> Reviewed 5 of 5 files at r4, 4 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68568)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Comment by mgartner** [comment]
TFTR!

bors r+

**Comment by mgartner** [comment]
blathers backport 21.1

**Comment by RaduBerinde** [comment]
:lgtm: Nice work!

**Pull request merged**
