### PR TITLE
sqlccl: option to skip restoring transformed csv data

### PR DESCRIPTION
**Pull request by dt**
This is expected to be useful in deployments where operators may want to use non-production machines to do the
transform process and then only need to restore in production, or for a one-time transform of some testdata
(e.g. TPC-H) that can then be loaded repeatedly via RESTORE.

### CODE REVIEW

**Comment by mjibson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/csv_test.go, line 418 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17961#-Ksdyby3_r6nt7TSfXWc:-Ksdyby3_r6nt7TSfXWd:b-5xziup) ([raw file](https://github.com/cockroachdb/cockroach/blob/72af4ac050cb17257115be17ad7338dfcac29287/pkg/ccl/sqlccl/csv_test.go#L418)):*
> ```Go
> 		{
> 			"schema-in-query-skip-load",
> 			`IMPORT TABLE t (a int primary key, b string, index (b), index (a, b)) CSV DATA (%s) WITH temp = $1, distributed, comma = '|', comment = '#', nullif='', skip_load`,
> ```

skip_load -> transform_only

---

*[pkg/ccl/sqlccl/csv_test.go, line 464 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17961#-KsdyXoFtxWGL5l9xnvq:-KsdyXoFtxWGL5l9xnvr:b-cckuj) ([raw file](https://github.com/cockroachdb/cockroach/blob/72af4ac050cb17257115be17ad7338dfcac29287/pkg/ccl/sqlccl/csv_test.go#L464)):*
> ```Go
> 			}
> 
> 			if strings.Contains(tc.query, "transform_only") {
> ```

I think this needs to be !strings.Contains...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17961)*

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/csv_test.go, line 418 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17961#-Ksdyby3_r6nt7TSfXWc:-Ksdz9D4l-mOfIQvyK0W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/72af4ac050cb17257115be17ad7338dfcac29287/pkg/ccl/sqlccl/csv_test.go#L418)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

skip_load -> transform_only
</blockquote></details>

Done.

---

*[pkg/ccl/sqlccl/csv_test.go, line 464 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17961#-KsdyXoFtxWGL5l9xnvq:-Ksdyq3X_1LbKbsncoaM:b958s4z) ([raw file](https://github.com/cockroachdb/cockroach/blob/72af4ac050cb17257115be17ad7338dfcac29287/pkg/ccl/sqlccl/csv_test.go#L464)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I think this needs to be !strings.Contains...
</blockquote></details>

er... if the option isn't present, then we already restored and don't need to run it here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17961)*

**Comment by mjibson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/sqlccl/csv_test.go, line 464 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17961#-KsdyXoFtxWGL5l9xnvq:-KsdzdZ_w20NXRtql9w8:b-gz7xbx) ([raw file](https://github.com/cockroachdb/cockroach/blob/72af4ac050cb17257115be17ad7338dfcac29287/pkg/ccl/sqlccl/csv_test.go#L464)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

er... if the option isn't present, then we already restored and don't need to run it here?
</blockquote></details>

Oh oh. Yes you're correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17961)*

**Comment by mjibson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/sqlccl/csv_test.go, line 418 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17961#-Ksdyby3_r6nt7TSfXWc:-Ksdzv_bZuiXkwm-292d:bmvw006) ([raw file](https://github.com/cockroachdb/cockroach/blob/72af4ac050cb17257115be17ad7338dfcac29287/pkg/ccl/sqlccl/csv_test.go#L418)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant in the SQL statement, not the title.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17961)*

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/sqlccl/csv_test.go, line 418 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17961#-Ksdyby3_r6nt7TSfXWc:-Kse0nqay66Xf9QyDCK0:b-jgyz2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/72af4ac050cb17257115be17ad7338dfcac29287/pkg/ccl/sqlccl/csv_test.go#L418)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I meant in the SQL statement, not the title.
</blockquote></details>

doh. thanks. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17961)*

**Comment by dt** [comment]
added a bit more to the test, to assert that it actually skipped loading, rather than just that the `RESTORE` doesn't fail.

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17961#-:-KseORt12XCwnDf8eXzs:bnfp4nl)*

**Pull request merged**
