### PR TITLE
ui: use local favicon

### LINKED ISSUE #7279: ui: use embedded favicon
The admin UI seems to be using the favicon from `http://www.cockroachlabs.com/wp-content/themes/cockroach-labs/images/favicon.ico`, which (beyond being a crazy thing to do) throws a mixed-content warning when running in secure mode.

### PR DESCRIPTION
**Pull request by tamird**
Fixes #7279.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7285)

### CODE REVIEW

**Comment by mberhault** [comment]
LGTM. probably. We should also make sure we don't do anything like this anywhere else.

**Comment by maxlang** [comment]
We should change this in ui/next as well.

**Comment by tamird** [comment]
It's already correct in ui/next.

**Comment by maxlang** [comment]
Whoops I was looking in the wrong place

**Comment by maxlang** [comment]
(LGTM)

**Pull request merged**
