### PR TITLE
sql: remove/hide support for TIMETZ

### LINKED ISSUE #25224: qa: timetz
this issue tracks the qa for the timetz type available in the next alpha

https://github.com/cockroachdb/cockroach/issues/20944

@andreimatei you have been picked randomly to qa this feature

### PR DESCRIPTION
**Pull request by knz**
Fixes #25224.

This patch removes the support for TIMETZ that was previously
introduced in the 2.1 branch.

The protobuf ID for table schemas remains reserved, however any
attempt to access a TIMETZ column in existing tables will cause a node
to panic. Tables containing TIMETZ columns must be completely dropped,
they cannot be recovered.

Release note (backward-incompatible change): Support for PostgreSQL's
TIMETZ data type is removed because it was incomplete/incorrect. This
was a feature only available in previous 2.1-alpha releases but not
any stable release, and thus was experimental anyways. Tables
previously created with the TIMETZ data type must be dropped entirely
-- it is not possible to convert the data or drop a single TIMETZ
column.

cc @awoods187

### CODE REVIEW

**Comment by knz** [comment]
cc @rmloveland

**Review by jordanlewis — APPROVED** [review]

**Comment by knz** [comment]
@petermattis just suggested an alternate approach which I will try shortly.

**Comment by knz** [comment]
So the attempt was to keep the datum type but remove the table encoding (which was blatantly wrong)

However the datum type was also wrong actually -- the package `timeofday` has subtle flaws that make TIMETZ very wrong, namely that the times should be converted relative to the current date, not January 1 1970. This is a rather non-trivial fix and I think the implementation of TIMETZ (and, actually, also TIME) is currently irredeemable.

So I have opted for a full removal. We can always consider a revert later if we want to restore the functionality, e.g. on the `master` branch after 2.1. has been cut.

**Pull request merged**
