### PR TITLE
kvserver: don't unquiesce on liveness changes of up-to-date replicas

### PR DESCRIPTION
**Pull request by nvb**
Mitigates the runtime regression in #50865.
Implements the proposal from https://github.com/cockroachdb/cockroach/issues/50865#issuecomment-662308501.

In #26911, we introduced the ability to quiesce ranges with dead replicas that were behind on the Raft log. This was a big win, as it prevented a node failure from stopping any range with a replica on that node from quiescing, even if the range was dormant. However, in order to ensure that the replica was caught up quickly once its node being brought back on-line, we began aggressively unquiescing when nodes moved from not-live to live.

This turns out to be a destabilizing behavior. In scenarios like #50865 where nodes contain large numbers of replicas (i.e. O(100k)), suddenly unquiescing all replicas on a node due to a transient liveness blip can bring a cluster to its knees. Like #51888 and #45013, this is another case where we add work to the system when it gets sufficiently loaded, causing stability to be divergent instead of convergent and resulting in an unstable system.

This fix removes the need to unquiesce ranges that have up-to-date replicas on nodes that undergo liveness changes. It does so by socializing the liveness state of lagging replicas during Range quiescence. In dong so through a new `lagging_quiescence` set attached to quiescence requests, it allows all quiesced replicas to agree on which node liveness events would need to result in the range being unquiesced and which ones can be ignored.

This allows us to continue to provide the guarantee that:

> If at least one up-to-date replica in a Raft group is alive, the
> Raft group will catch up any lagging replicas that are also alive.

For a pseudo-proof of this guarantee, see https://github.com/cockroachdb/cockroach/issues/50865#issuecomment-662308501.

A secondary effect of this change is that it fixes a bug in quiescence as it exists today. Before this change, we did not provide this guarantee in the case that a leader was behind on its node liveness information, broadcasted a quiescence notification, and then crashed. In that case, a node that was brought back online might not be caught up for minutes because the range wouldn't unquiesce until the lagging replica reached out to it. Interestingly, this may be a semi-common occurrence during rolling restart scenarios.

This is a large improvement on top of the existing behavior because it reduces the set of ranges with a replica on a given dead node that unquiesce when that node becomes live to only those ranges that had write activity after the node went down. This is typically only a small fraction of the total number of ranges on each node (operating on the usual assumption that in an average large cluster, most data is write-cold), especially when the outage is short. However, if all ranges had write activity and subsequently quiesced before the outage resolved, we would still have to unquiesce all ranges upon the node coming back up. For this reason, the change is primarily targeted towards reducing the impact of node liveness blips and not reducing the impact of bringing nodes back up after sustained node outages. This is intentional, as the former category of outage is the one more likely to be caused by overload due to unquiescence traffic itself (as we see in #50865), so it is the category we choose to focus on here.

Release note (performance improvement): transient node liveness blips no longer cause up-to-date Ranges to unquiesce, which makes these events less destabilizing.

@petermattis I'm adding you as a reviewer because you've done more thinking about Range quiescence than anyone else. But I can find a new second reviewer if you don't have time to take a look at this.

### CODE REVIEW

**Comment by petermattis** [comment]
I can take a look at this, but it won't be for another day or two. I'm also a bit out of date with respect to this code, so probably a good idea to get a secondary reviewer.

**Review by tbg — COMMENTED** [review]
My review isn't in-depth enough to give an LGTM, but the approach and migration look good. You could mention in the commit message *why* this is a large improvement: previously, all replicas would unquiesce on a liveness change, but now only those in ranges that had write activity after the node went down will do so, and this is typically only a small fraction (operating on the usual assumption that in an average large cluster, most data is write-cold), especially when the outage is short. However, if *all* ranges had write activity and subsequently quiesced before the outage resolved, we would be back to square one-and-a-half, in the sense that all ranges would unquiesce, though it would likely be less of a death spiral since an overload that caused extra heartbeat failures would possibly not self-reinforce as much (is this right)?

> Reviewed 4 of 4 files at r1, 12 of 12 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51894#-:-MDKEtQvB5fMzX_DuHdt:bubo5oo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, and @petermattis)

___
*[pkg/kv/kvserver/raft.proto, line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51894#-MDKCwxM57OmVgPZNm74:-MDKCwxM57OmVgPZNm75:bmcibha) ([raw file](https://github.com/cockroachdb/cockroach/blob/c82a320d5d763cdd10436489070b7409097ec5c4/pkg/kv/kvserver/raft.proto#L65)):*
> ```protobuf
>   // the sender.
>   bool quiesce = 5;
>   // If quiesce is true, this set contains liveness information about
> ```

lagging_quiesce
___
*[pkg/kv/kvserver/raft.proto, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51894#-MDKEFNZ21y3Ihv7KdSv:-MDKEFN_ALNxQ8pZ43qn:bm4glxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/199595e0860ad8191322256bb60b7e1eebeedd1d/pkg/kv/kvserver/raft.proto#L80)):*
> ```protobuf
>   // v21.1: Keep sending. Stop consulting.
>   // v21.2: Remove field.
>   bool lagging_quiescence_accurate = 10;
> ```

Explain that this field helps migrate the `lagging_quiescence` field.

**Review by nvb — COMMENTED** [review]
TFTR!

I added the following paragraph to the PR and commit message:

> This is a large improvement on top of the existing behavior because it reduces the set of ranges with a replica on a given dead node that unquiesce when that node becomes live to only those ranges that had write activity after the node went down. This is typically only a small fraction of the total number of ranges on each node (operating on the usual assumption that in an average large cluster, most data is write-cold), especially when the outage is short. However, if all ranges had write activity and subsequently quiesced before the outage resolved, we would still have to unquiesce all ranges upon the node coming back up. For this reason, the change is primarily targeted towards reducing the impact of node liveness blips and not reducing the impact of bringing nodes back up after sustained node outages. This is intentional, as the former category of outage is the one more likely to be caused by overload due to unquiescence traffic itself (as we see in #50865), so it is the category we choose to focus on here.

@aayushshah15 do you have any interest in giving this a pass as well? It touches some code that you might be interested in getting familiar with, given the intersection of replica lifecycles and Raft replication that you've been working on.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51894#-:-ME9TzIu9Et3mQPrlwGd:b-chkp5m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @petermattis, and @tbg)

___
*[pkg/kv/kvserver/raft.proto, line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51894#-MDKCwxM57OmVgPZNm74:-ME9P5ME4QQqJHeWDXNv:b-16wssw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c82a320d5d763cdd10436489070b7409097ec5c4/pkg/kv/kvserver/raft.proto#L65)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

lagging_quiesce
</blockquote></details>

This is pointing to the field above, saying that the set contains liveness about quiescence, if the RaftMessageRequest is telling a follower to quiesce.
___
*[pkg/kv/kvserver/raft.proto, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51894#-MDKEFNZ21y3Ihv7KdSv:-ME9Psgw-BjFFKK739SU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/199595e0860ad8191322256bb60b7e1eebeedd1d/pkg/kv/kvserver/raft.proto#L80)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Explain that this field helps migrate the `lagging_quiescence` field.
</blockquote></details>

Done.

**Review by aayushshah15 — COMMENTED** [review]
Sorry for the delay (and thanks for reminding me)!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51894#-:-MEONc_z6EWnIiRcf3a-:bjttkfv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten, @petermattis, and @tbg)

___
*[pkg/kv/kvserver/raft.proto, line 73 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/51894#-MEOKkJf-rTuVnpxMgHa:-MEOKkJf-rTuVnpxMgHb:b-7s3l5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/56a3383d734b4f496ce89991c50c27f22ddb12bf/pkg/kv/kvserver/raft.proto#L73)):*
> ```protobuf
>   // become live, it should unquiesce the range so that the replica can
>   // be caught back up.
>   repeated storagepb.Liveness lagging_quiescence = 9 [(gogoproto.nullable) = false];
> ```

How do you feel about renaming this field to something like `{Dead | Lagging}FollowersOnQuiesce`?
___
*[pkg/kv/kvserver/store_raft.go, line 547 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/51894#-MEOLO1F1wtrBDj7bVlG:-MEOLO1F1wtrBDj7bVlH:b-laym0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/56a3383d734b4f496ce89991c50c27f22ddb12bf/pkg/kv/kvserver/store_raft.go#L547)):*
Should we include your proof here? It would be nice to have this paragraph of yours: 
>This means that we can make some kind of statement about the live, quiesced replicas of a quiescent Raft group at any given point in time. These live, quiesced replicas fall into three groups: the leader, up-to-date followers, and not up-to-date followers. a) The leader must either have full knowledge of the Raft group or must have been replaced, in which case it no longer matters and it's as good as dead. b) The up-to-date followers must have received their quiescence notifications from the leader at a time when the set of not up-to-date replicas was a superset of the current set of not up-to-date replicas. We can't say the sets are equivalent because the range could have unquiesced, caught a lagging follower up, and then re-quiesced without appending to its log and without informing the follower, but we can say that the superset relation holds. This is because nothing can be added to this set without the range having been unquiesced and its index moved forward. c) The not up-to-date followers must have been not live at some point and therefore must have triggered nodeIsLiveCallback on at least one of the up-to-date replicas (leader or follower) as long as there exists at least one up-to-date node that is live.

and then point to the check inside `shouldFollowerQuiesceOnNotify` to show that part (c) is being upheld. What do you think?

**Comment by aayushshah15** [comment]
___
*[pkg/kv/kvserver/raft.proto, line 73 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/51894#-MEOKkJf-rTuVnpxMgHa:-MEOO5bhBp0qzjBkqJYw:b-41m9se) ([raw file](https://github.com/cockroachdb/cockroach/blob/56a3383d734b4f496ce89991c50c27f22ddb12bf/pkg/kv/kvserver/raft.proto#L73)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

How do you feel about renaming this field to something like `{Dead | Lagging}FollowersOnQuiesce`?
</blockquote></details>

On second thought: `LaggingFollowersOnQuiesce` and what we currently have seem like misnomers because those followers must necessarily be dead in order for us to continue to quiesce.

**Review by nvb — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51894#-:-MF2UP1d1QfYUEqGSKVr:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @petermattis, and @tbg)

___
*[pkg/kv/kvserver/raft.proto, line 73 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/51894#-MEOKkJf-rTuVnpxMgHa:-MF2KXIw101pL44IKFT8:b-gbf84o) ([raw file](https://github.com/cockroachdb/cockroach/blob/56a3383d734b4f496ce89991c50c27f22ddb12bf/pkg/kv/kvserver/raft.proto#L73)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

On second thought: `LaggingFollowersOnQuiesce` and what we currently have seem like misnomers because those followers must necessarily be dead in order for us to continue to quiesce. 
</blockquote></details>

Discussed on slack. Decided to go with `LaggingFollowersOnQuiesce`.
___
*[pkg/kv/kvserver/store_raft.go, line 547 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/51894#-MEOLO1F1wtrBDj7bVlG:-MF2TrYw5xbeT8YftDBt:be38fqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/56a3383d734b4f496ce89991c50c27f22ddb12bf/pkg/kv/kvserver/store_raft.go#L547)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Should we include your proof here? It would be nice to have this paragraph of yours: 
>This means that we can make some kind of statement about the live, quiesced replicas of a quiescent Raft group at any given point in time. These live, quiesced replicas fall into three groups: the leader, up-to-date followers, and not up-to-date followers. a) The leader must either have full knowledge of the Raft group or must have been replaced, in which case it no longer matters and it's as good as dead. b) The up-to-date followers must have received their quiescence notifications from the leader at a time when the set of not up-to-date replicas was a superset of the current set of not up-to-date replicas. We can't say the sets are equivalent because the range could have unquiesced, caught a lagging follower up, and then re-quiesced without appending to its log and without informing the follower, but we can say that the superset relation holds. This is because nothing can be added to this set without the range having been unquiesced and its index moved forward. c) The not up-to-date followers must have been not live at some point and therefore must have triggered nodeIsLiveCallback on at least one of the up-to-date replicas (leader or follower) as long as there exists at least one up-to-date node that is live.

and then point to the check inside `shouldFollowerQuiesceOnNotify` to show that part (c) is being upheld. What do you think?
</blockquote></details>

Done. I didn't include the full proof in there because it's difficult to follow, but I added some words about the guarantee we're providing and a link to the other comment in shouldFollowerQuiesceOnNotify.

**Review by aayushshah15 — APPROVED** [review]
LGTM (although unfortunately, I don't have a deep grasp of this area). Should we perhaps get this baking on master sooner than later, and see if our nightly roachtest runs tell us anything interesting?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51894#-:-MF6T88y08xwltg_GHID:b-zac124)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, @petermattis, and @tbg)

___
*[pkg/kv/kvserver/store_raft.go, line 537 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/51894#-MF6XepG34tC5hyH1L5d:-MF6XepG34tC5hyH1L5e:bt36jrl) ([raw file](https://github.com/cockroachdb/cockroach/blob/50e6ce3e318543caf9a63b867b9b5d0028eb4125/pkg/kv/kvserver/store_raft.go#L537)):*
> ```Go
> // functions combine to provide the guarantee that:
> //
> //   If at quorum of replica in a Raft group is alive and at least
> ```

a* quorum

**Review by nvb — COMMENTED** [review]
> Should we perhaps get this baking on master sooner than later, and see if our nightly roachtest runs tell us anything interesting?

Yes, let's get this baking. It's the kind of change that might have unintended fallout.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51894#-:-MF7FQqiAv_3rYHkZN3Z:bc4mec6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @petermattis, and @tbg)

___
*[pkg/kv/kvserver/store_raft.go, line 537 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/51894#-MF6XepG34tC5hyH1L5d:-MF7FWzVDzmdgBsShoP3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/50e6ce3e318543caf9a63b867b9b5d0028eb4125/pkg/kv/kvserver/store_raft.go#L537)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

a* quorum
</blockquote></details>

Done.

**Comment by aayushshah15** [comment]
Hey @nvanbenschoten, we were seeing the issue fixed by this PR pop up on a customer issue running 20.1.8. It's a big change but I was wondering if you had any opinions about if this is feasible to backport.

**Comment by nvanbenschoten** [comment]
Unfortunately, I don't think it's a potential backport candidate. As you point out, it's large. Additionally, it also has fairly subtle interactions with existing nodes in the cluster, so there are migration concerns. So at this point, I don't think we should backport it to `release-20.1` unless it's absolutely necessary.

I don't know the full context of why you're asking, but we did land https://github.com/cockroachdb/cockroach/pull/57009 in v20.1.10, which may help avoid liveness failures in the first place.

**Comment by aayushshah15** [comment]
cc @ricardocrdb

**Pull request merged**
