### PR TITLE
release-22.1: cloud,bulk: include external IO requests in tenant usage

### PR DESCRIPTION
**Pull request by stevendanna**
Backport 1/1 commits from #76495.

/cc @cockroachdb/release

---

This adds basic accounting to ExternalStorage writes. The measured
bytes written is almost surely inaccurate as it doesn't account for

- retries inside client libraries,
- protocol metadata such as HTTP headers, or
- transport level compression.

Thus, instead of measuring "bytes sent over the network" it is
measuring something closer to "bytes stored on external storage
services"

Release justification: Low risk (off by default) feature for multi-tenant
cost accounting.

Release note: Tenant usage now includes bytes written to external data
storage services such as Google Compute Storage or Amazon S3.

### CODE REVIEW

**Comment by stevendanna** [comment]
cc @livlobo to confirm that this feature is worth backporting becuase of its priority for serverless.

**Comment by stevendanna** [comment]
@andy-kimball has asked we hold off backporting this as he has some other changes in flight he wants to land together.

**Comment by stevendanna** [comment]
@andy-kimball I wonder if you had a sense of when the other work you were looking at might land. If we don't merge this shortly, it is unlikely to make it in for 22.1.1.

**Comment by andy-kimball** [comment]
[My changes](https://github.com/cockroachdb/cockroach/pull/81275) won't be ready for 21.1.1. I've added you to that PR so you can take a look at the changes I ended up making to the External I/O related code.

If you back-ported this change, then it should not have any effect b/c it's "off" by default, correct? If I merged my change in 21.1.2, and flipped your code "on" by default, would that immediately take effect when we rolled out 21.1.2? I'm not totally sure how tenant cluster settings work. I want to avoid having to run `SET CLUSTER SETTING` on our production host clusters - it's quite a bit of work.

**Review by livlobo — COMMENTED** [review]
LGTM

**Comment by stevendanna** [comment]
@andy-kimball Now that https://github.com/cockroachdb/cockroach/pull/81275 has merged, should we just fold this into the backport of that?

**Review by dt — APPROVED** [review]

**Pull request merged**
