### PR TITLE
tracing,server,distsql: optimize RPC trace creating for common RPCs

### PR DESCRIPTION
**Pull request by andreimatei**
Before this patch, tracing across RPC boundaries is implemented by gRPC
interceptors that marshall the trace info from the client to the server
as gRPC metadata, and transparently open client and server spans.
Unfortunately, sending this metadata around the actual request is quite
expensive: it takes 10 allocations per RPC on the client and some on the
server. Some of these allocations can be optimized, but not all due to
the gRPC interfaces; this metadata is just not thought out to be
efficient. Additionally, back in the day, this metadata was measured to
produce a very significant increase in network packets (#17177). At the
time, this was reason enough to avoid this producing this metadata when
tracing is not enabled. I have not measured this again, nor was this
effect measured beyond the network packets metric, but I hope to enable
tracing enough such that, unless we do something else, this metadata
would again be always produced.

This patch optimizes tracing for the 3 most common RPCs in the system:
- Internal.Batch
- DistSQL.SetupFlow, DistSQL.FlowStream.

In the case of FlowStream, we simply do away with tracing. FlowStream is
a streaming RPC used by an Outbox to send its data to another node. The
outbox has its own span; the RPC's span did not have any information.
In fact I'm fairly sure we were not even collecting the RPC's stream in
the trace recordings.

For the other two, the respective clients and servers take on the
responsibility of marshalling the tracing information and creating
server-side spans. The client's trace info gets put into the request
protos - which dirties the respective protos with this concern. In the
case of Batch, the code and the protos were already concerned with
tracing because they dealt with returning the recording; that part was
never abstracted inside the interceptors. In fact, the tracing code for
that RPC gets cleaner: before, setupSpanForIncomingRPC() was collecting
the recording of a *parent* span; this practice is very unusual and
results in a span that shows up as "_unfinished" in the recording.

BenchmarkTracing shows a significant reduction in allocations, and also
latency, for the 3-node tracing-on cases:

name                               old time/op    new time/op    delta
Tracing/3node/scan/trace=on-24        883µs ± 2%     847µs ± 1%  -4.11%  (p=0.008 n=5+5)
Tracing/3node/insert/trace=on-24     1.08ms ± 3%    1.04ms ± 3%  -3.94%  (p=0.016 n=5+5)

name                               old allocs/op  new allocs/op  delta
Tracing/3node/scan/trace=on-24          868 ± 0%       840 ± 0%  -3.20%  (p=0.008 n=5+5)
Tracing/3node/insert/trace=on-24        803 ± 0%       788 ± 0%  -1.89%  (p=0.008 n=5+5)

kv95/enc=false/nodes=3 shows a good increase in throughput (2% on this
set of 10 runs, but I think it's actually a bit higher). This is a big
chunk of the current throughput penalty for enabling a minimal level of
tracing.

name                    old ops/s    new ops/s    delta
kv95/enc=false/nodes=3   31.9k ± 3%   32.6k ± 4%  +2.16%  (p=0.027 n=8+9)

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
awesome.

**Review by dhartunian — COMMENTED** [review]
Cool stuff! I have a few nits and questions mostly.

> Reviewed 19 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-:-MqH8Cai70_w-gvQ8kDK:bg9vk0z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @abarganier, and @andreimatei)

___
*[pkg/roachpb/api.go, line 1691 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-MqH6O9N71SCEZT6U86I:-MqH6O9OBnfZ3jBKVLVW:b-sn5wup) ([raw file](https://github.com/cockroachdb/cockroach/blob/6039a4a490f3c5b8b776882dd640c01d1f721016/pkg/roachpb/api.go#L1691)):*
> ```Go
> }
> 
> type TracingInternalClient struct {
> ```

nit: docstring
___
*[pkg/server/node.go, line 1067 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-MqH6kyg5ihniVLA7pzI:-MqH6kyg5ihniVLA7pzJ:bw9u7pf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca800e2c72ccfa54b7f6f707bda5dfd59e148c1f/pkg/server/node.go#L1067)):*
> ```Go
> 			ctx, newSpan = tr.StartSpanCtx(ctx, opName)
> 		} else {
> 			parentSpan.SetTag("node", attribute.IntValue(int(n.Descriptor.NodeID)))
> ```

does this tag need to be preserved? I saw it gets set in `context.go` 
___
*[pkg/server/node.go, line 1106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-MqH3UZEC5_HsDU2xnGX:-MqH3UZEC5_HsDU2xnGY:b-4w1n59) ([raw file](https://github.com/cockroachdb/cockroach/blob/6039a4a490f3c5b8b776882dd640c01d1f721016/pkg/server/node.go#L1106)):*
> ```Go
> 
> 		if needRecordingCollection {
> 			if rec != nil {
> ```

nit: is it worth just combining the three `if`s above for readability?
___
*[pkg/sql/execinfrapb/api.proto, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-MqGV1Ot3vxwA2RAhjJ6:-MqGV1Ot3vxwA2RAhjJ7:b603zrx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6039a4a490f3c5b8b776882dd640c01d1f721016/pkg/sql/execinfrapb/api.proto#L147)):*
> ```protobuf
>   // computation) on the receiving node.
>   rpc SetupFlow(
>     SetupFlowRequest) returns (SimpleResponse) {}
> ```

nit: erroneous linebreak
___
*[pkg/util/tracing/grpc_interceptor.go, line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-MqGVwJI7KscOrRQzvq7:-MqGVwJI7KscOrRQzvq8:b-7sjkpw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6039a4a490f3c5b8b776882dd640c01d1f721016/pkg/util/tracing/grpc_interceptor.go#L174)):*
> ```Go
> func StreamServerInterceptor(tracer *Tracer) grpc.StreamServerInterceptor {
> 	return func(srv interface{}, ss grpc.ServerStream, info *grpc.StreamServerInfo, handler grpc.StreamHandler) error {
> 		if methodExcludedFromTracing(info.FullMethod) {
> ```

Do we need `compatibilityMode` check here?
___
*[pkg/util/tracing/grpc_interceptor.go, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-MqH68Q565SiXknBOiNJ:-MqH68Q565SiXknBOiNK:b-dzao0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/6039a4a490f3c5b8b776882dd640c01d1f721016/pkg/util/tracing/grpc_interceptor.go#L199)):*
> ```Go
> 		if err != nil {
> 			setGRPCErrorTag(serverSpan, err)
> 			serverSpan.Recordf("error: %s", err)
> ```

should these two post-error calls above be preserved on the methods we exclude from tracing?
___
*[pkg/util/tracing/grpc_interceptor.go, line 238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-MqGV9YD0rGDkSiDKu6s:-MqGV9YD0rGDkSiDKu6t:b-r1vjcu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6039a4a490f3c5b8b776882dd640c01d1f721016/pkg/util/tracing/grpc_interceptor.go#L238)):*
> ```Go
> }
> 
> type InjectorsMap map[string]func(clientSpan SpanMeta, req interface{})
> ```

What's this used for?
___
*[pkg/util/tracing/tracingpb/tracing.proto, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-MqH6IrC-rix87nlpq4Z:-MqH6IrC-rix87nlpq4_:b-sn5wup) ([raw file](https://github.com/cockroachdb/cockroach/blob/6039a4a490f3c5b8b776882dd640c01d1f721016/pkg/util/tracing/tracingpb/tracing.proto#L17)):*
> ```protobuf
> import "gogoproto/gogo.proto";
> 
> message TraceInfo {
> ```

nit: docstring
___
*[pkg/util/tracing/tracingpb/tracing.proto, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-MqGSGaS9lWZX2I7k0L0:-MqGSGaS9lWZX2I7k0L1:b-xqleuj) ([raw file](https://github.com/cockroachdb/cockroach/blob/6039a4a490f3c5b8b776882dd640c01d1f721016/pkg/util/tracing/tracingpb/tracing.proto#L31)):*
> ```protobuf
>   message OtelInfo {
>     // trace_id will have exactly 16 bytes.
>     bytes trace_id = 1 [(gogoproto.customname) = "TraceID"];
> ```

Just for my understanding, is this trace_id different from the `uint64` above? If so, do we want to unify them at some point, or no?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73404)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @abarganier, and @dhartunian)

___
*[pkg/roachpb/api.go, line 1691 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-MqH6O9N71SCEZT6U86I:-MqLScVO6NNpz0nkZtXe:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6039a4a490f3c5b8b776882dd640c01d1f721016/pkg/roachpb/api.go#L1691)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: docstring
</blockquote></details>

done
___
*[pkg/server/node.go, line 1067 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-MqH6kyg5ihniVLA7pzI:-MqLcZsi-JIeU6u9vNqK:b-z3qvyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca800e2c72ccfa54b7f6f707bda5dfd59e148c1f/pkg/server/node.go#L1067)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

does this tag need to be preserved? I saw it gets set in `context.go` 
</blockquote></details>

No, it doesn't. 
But the code was confused and confusing, sorry. In a mixed-version cluster, I had both the `ServerInterceptor` open an RPC span, and this `setupSpanForIncomingRPC`. That was not right. I think I had oscillated, trying to decide who's in a better position to do it when backwards-compatibility is at play, and I had ended up nowhere.
Now, the `ServerInterceptor` is out of the business of opening spans  for incoming `Batch` RPCs, regardless of the cluster version. It falls on `setupSpanForIncomingRPC` to deal with it. And so, for `setupSpanForIncomingRPC`, it becomes unexpected to find a span in ctx in the remote-call case. It still handles the case out of politeness, but it wouldn't make any sense to assume that the parent span (which, again, is not supposed to exist), needs the "node" tag. If there is a parent span, it probably has gotten a node tag in the ways that most spans do. Before, the `parentSpan` was special because it was opened by the ServerInterceptor and, for reasons I'm not entirely sure of, that guy was not hooked up to provide this "node" tag.
___
*[pkg/server/node.go, line 1106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-MqH3UZEC5_HsDU2xnGX:-MqLfIhq5KnHTgKn01k9:bmwxkt4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6039a4a490f3c5b8b776882dd640c01d1f721016/pkg/server/node.go#L1106)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: is it worth just combining the three `if`s above for readability?
</blockquote></details>

please see now
___
*[pkg/sql/execinfrapb/api.proto, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-MqGV1Ot3vxwA2RAhjJ6:-MqLfSgn3hLcsn-VfBOu:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6039a4a490f3c5b8b776882dd640c01d1f721016/pkg/sql/execinfrapb/api.proto#L147)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: erroneous linebreak
</blockquote></details>

done
___
*[pkg/util/tracing/grpc_interceptor.go, line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-MqGVwJI7KscOrRQzvq7:-MqLfUg48axFT8Z9Ci_F:b-2dyp07) ([raw file](https://github.com/cockroachdb/cockroach/blob/6039a4a490f3c5b8b776882dd640c01d1f721016/pkg/util/tracing/grpc_interceptor.go#L174)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Do we need `compatibilityMode` check here?
</blockquote></details>

no; in fact I've remove `compatibilityMode` from the `ServerInterceptor` too. Dealing with compatibility is now only a concern for client interceptors; on the server side it is a concern of the `setupSpanForIncomingRPC` functions.
___
*[pkg/util/tracing/grpc_interceptor.go, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-MqH68Q565SiXknBOiNJ:-MqLgyB_7BLBpasVEfru:b-szeusz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6039a4a490f3c5b8b776882dd640c01d1f721016/pkg/util/tracing/grpc_interceptor.go#L199)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

should these two post-error calls above be preserved on the methods we exclude from tracing?
</blockquote></details>

Well they can't simply be preserved because they want to operate on a span that doesn't exist in the `methodExcludedFromTracing` case. The equivalent would be code in the `finish` callback returned by the `setupSpanForIncomingRPC` methods. But I don't think it's worth it.
___
*[pkg/util/tracing/grpc_interceptor.go, line 238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-MqGV9YD0rGDkSiDKu6s:-MqLhpwc-2En9f4OB8We:bty3eas) ([raw file](https://github.com/cockroachdb/cockroach/blob/6039a4a490f3c5b8b776882dd640c01d1f721016/pkg/util/tracing/grpc_interceptor.go#L238)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

What's this used for?
</blockquote></details>

Detritus from trying out some other scheme. Removed, thanks. 
___
*[pkg/util/tracing/tracingpb/tracing.proto, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-MqH6IrC-rix87nlpq4Z:-MqLild1-yUA_ydi6-0L:b-t3yp3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/6039a4a490f3c5b8b776882dd640c01d1f721016/pkg/util/tracing/tracingpb/tracing.proto#L17)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: docstring
</blockquote></details>

done. I've considered having this proto  replace `SpanMeta`, but I'll leave it for another day.
___
*[pkg/util/tracing/tracingpb/tracing.proto, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-MqGSGaS9lWZX2I7k0L0:-MqLj3cg0ioooXOujSOw:bntjh7k) ([raw file](https://github.com/cockroachdb/cockroach/blob/6039a4a490f3c5b8b776882dd640c01d1f721016/pkg/util/tracing/tracingpb/tracing.proto#L31)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Just for my understanding, is this trace_id different from the `uint64` above? If so, do we want to unify them at some point, or no?
</blockquote></details>

Yeah, they're different. I guess mostly because otel ids are 16 bytes, so they're more awkward to work with. It's not clear to me that there'd be any benefit to unifying them; the otel integration is pretty well encapsulated.

**Review by dhartunian — APPROVED** [review]
:lgtm: 

> Reviewed 21 of 21 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-:-MqaEw0355aGDJrrMpS9:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @abarganier, and @andreimatei)

___
*[pkg/server/node.go, line 1067 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-MqH6kyg5ihniVLA7pzI:-MqPaJ_u8w3rLAEms1sM:b8ffpnc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca800e2c72ccfa54b7f6f707bda5dfd59e148c1f/pkg/server/node.go#L1067)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

No, it doesn't. 
But the code was confused and confusing, sorry. In a mixed-version cluster, I had both the `ServerInterceptor` open an RPC span, and this `setupSpanForIncomingRPC`. That was not right. I think I had oscillated, trying to decide who's in a better position to do it when backwards-compatibility is at play, and I had ended up nowhere.
Now, the `ServerInterceptor` is out of the business of opening spans  for incoming `Batch` RPCs, regardless of the cluster version. It falls on `setupSpanForIncomingRPC` to deal with it. And so, for `setupSpanForIncomingRPC`, it becomes unexpected to find a span in ctx in the remote-call case. It still handles the case out of politeness, but it wouldn't make any sense to assume that the parent span (which, again, is not supposed to exist), needs the "node" tag. If there is a parent span, it probably has gotten a node tag in the ways that most spans do. Before, the `parentSpan` was special because it was opened by the ServerInterceptor and, for reasons I'm not entirely sure of, that guy was not hooked up to provide this "node" tag.
</blockquote></details>

Thx for the historical context :thumbsup: 
___
*[pkg/server/node.go, line 1106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-MqH3UZEC5_HsDU2xnGX:-MqPaT4t4D0pRdnWW_17:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6039a4a490f3c5b8b776882dd640c01d1f721016/pkg/server/node.go#L1106)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please see now
</blockquote></details>

:thumbsup: 
___
*[pkg/sql/distsql/server.go, line 577 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-Mqa9maV6mynrLwf-uv7:-Mqa9maW6snH_bJoS2OD:bqo5a6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/9df915cebb43e17be3a808f49aee3f2b9155dbac/pkg/sql/distsql/server.go#L577)):*
> ```Go
> func (ds *ServerImpl) setupSpanForIncomingRPC(
> 	ctx context.Context, req *execinfrapb.SetupFlowRequest,
> ) (context.Context, *tracing.Span) {
> ```

is it worth sharing code in here w/ the other `setupSpanForIncomingRPC` impl? Maybe two cases isn't worth it.
___
*[pkg/sql/distsql/server.go, line 583 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-MqPag9k0mnnmrJttZOw:-MqPag9k0mnnmrJttZOx:b75seiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9df915cebb43e17be3a808f49aee3f2b9155dbac/pkg/sql/distsql/server.go#L583)):*
> ```Go
> 		// It's not expected to have a span in the context since the gRPC server
> 		// interceptor that generally opens spans exempts this particular RPC. Note
> 		// that this method is not called when for flows local to the gateway.
> ```

nit: remove "when"
___
*[pkg/util/tracing/grpc_interceptor.go, line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-MqGVwJI7KscOrRQzvq7:-MqPg5oEAGLN4-d5OOdv:bf95ae) ([raw file](https://github.com/cockroachdb/cockroach/blob/6039a4a490f3c5b8b776882dd640c01d1f721016/pkg/util/tracing/grpc_interceptor.go#L174)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

no; in fact I've remove `compatibilityMode` from the `ServerInterceptor` too. Dealing with compatibility is now only a concern for client interceptors; on the server side it is a concern of the `setupSpanForIncomingRPC` functions.
</blockquote></details>

nice, that clarifies things.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73404)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @abarganier, @andreimatei, and @dhartunian)

___
*[pkg/sql/distsql/server.go, line 577 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-Mqa9maV6mynrLwf-uv7:-MqaZV-0CMcW2kkH2ZXU:b-3nj0hp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9df915cebb43e17be3a808f49aee3f2b9155dbac/pkg/sql/distsql/server.go#L577)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

is it worth sharing code in here w/ the other `setupSpanForIncomingRPC` impl? Maybe two cases isn't worth it.
</blockquote></details>

I thought about it, but the other one is a bit different. It deals with the case when the request is local, it deals with the recording... I don't think it's worth trying to factor out anything in common, to be honest. I don't think we'll end up with something better. But if we give more RPCs this treatment, the majority would probably be pretty similar to this one here, so there probably would be code sharing.
___
*[pkg/sql/distsql/server.go, line 583 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-MqPag9k0mnnmrJttZOw:-MqaZCb89wXUSrVVw9-g:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9df915cebb43e17be3a808f49aee3f2b9155dbac/pkg/sql/distsql/server.go#L583)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: remove "when"
</blockquote></details>

done

**Review by andreimatei — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73404#-:-MqooWqa33imtdq9kt9u:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @abarganier, @andreimatei, and @dhartunian)

**Pull request merged**
