### PR TITLE
*: misc cleanup

### PR DESCRIPTION
**Pull request by tamird**
Addressing my own comments from #9504.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10215)

### CODE REVIEW

**Comment by andreimatei** [comment]
LGTM but I don't like the 2nd commit.

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/storage/store.go, line 919 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10215#-KUyqX4oW6AgEdsbdBO7:-KUyqX4oW6AgEdsbdBO8:bonwxld) ([raw file](https://github.com/cockroachdb/cockroach/blob/55544698a7c247345f6df38bff5165f87f0281fe/pkg/storage/store.go#L919)):*
> ```Go
> // It returns *NotBootstrappedError if the ident is missing (meaning that the
> // store needs to be bootstrapped).
> func ReadStoreIdent(ctx context.Context, eng engine.Engine, ident *roachpb.StoreIdent) error {
> ```

can you add a comment specifying that `ident` can be nil, and what that means

---

*[pkg/storage/store.go, line 919 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10215#-KUyr-Cf2KXj0j-GpkrR:-KUyr-Cf2KXj0j-GpkrS:bo3ia5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/55544698a7c247345f6df38bff5165f87f0281fe/pkg/storage/store.go#L919)):*
> ```Go
> // It returns *NotBootstrappedError if the ident is missing (meaning that the
> // store needs to be bootstrapped).
> func ReadStoreIdent(ctx context.Context, eng engine.Engine, ident *roachpb.StoreIdent) error {
> ```

I prefer the old signature... That seems like the natural one.
Besides the question of why would you take a pointer as argument when you just want to return a value, also now I need to go through at least 2 levels of calls to see what happens to that pointer in case of an error, you have to document that the pointer can be nil, and you introduce confusion about whether this is an input, output or input-output argument.
The fact that this saves a line for 2 callers is far from worth it, IMHO.

---

*[pkg/storage/store.go, line 927 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10215#-KUyqd0iVsSDmCgukuPZ:-KUyqd0iVsSDmCgukuP_:btk4ci5) ([raw file](https://github.com/cockroachdb/cockroach/blob/55544698a7c247345f6df38bff5165f87f0281fe/pkg/storage/store.go#L927)):*
> ```Go
> 		msg = ident
> 	}
> 	ok, err := engine.MVCCGetProto(ctx, eng, keys.StoreIdentKey(), hlc.ZeroTimestamp, true, nil, msg)
> ```

Mind adding a comment to `MVCCGetProto` that `msg` can be nil? That's really surprising.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10215#-:-KUysfjm4AoWh4MiftdM:b-j8zne4)*

**Comment by tschottdorf** [comment]
:lgtm: and I share @andrei's view about the second commit. 

---

Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10215#-:-KUzreO7K16NhYmeU9QU:b-k1sd4z)*

**Comment by tamird** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/storage/store.go, line 919 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10215#-KUyr-Cf2KXj0j-GpkrR:-KV0K-BHz6bn2P8UPRmv:bj2snj5) ([raw file](https://github.com/cockroachdb/cockroach/blob/55544698a7c247345f6df38bff5165f87f0281fe/pkg/storage/store.go#L919)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> I prefer the old signature... That seems like the natural one.
> Besides the question of why would you take a pointer as argument when you just want to return a value, also now I need to go through at least 2 levels of calls to see what happens to that pointer in case of an error, you have to document that the pointer can be nil, and you introduce confusion about whether this is an input, output or input-output argument.
> The fact that this saves a line for 2 callers is far from worth it, IMHO.
</details>
It's not about the line savings.

I don't think this introduces confusion about the parameter; the method is called ReadStoreIdent and it only has one argument or return value of type`*roachpb.StoreIdent` or `roachp.StoreIdent`.

Unfortunately, we have conflicting precedent for this stuff in various places.

- `engine.MVCCGetRangeStats` uses a pointer argument (though it is not nil-safe)
- all the replica state methods return a value or pointer

I've gone the other direction and made `engine.MVCCGetRangeStats` return a value. PTAL.

---

*[pkg/storage/store.go, line 919 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10215#-KUyqX4oW6AgEdsbdBO7:-KV0eH5Tr7NqucRaCeYk:b-2isjz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/55544698a7c247345f6df38bff5165f87f0281fe/pkg/storage/store.go#L919)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> can you add a comment specifying that `ident` can be nil, and what that means
</details>
Done (by reverting this change).

---

*[pkg/storage/store.go, line 927 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10215#-KUyqd0iVsSDmCgukuPZ:-KV0L3mkfPaIzK42eKPb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/55544698a7c247345f6df38bff5165f87f0281fe/pkg/storage/store.go#L927)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> Mind adding a comment to `MVCCGetProto` that `msg` can be nil? That's really surprising.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10215)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 3 files at r3, 6 of 8 files at r5, 5 of 6 files at r6, 3 of 3 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica_state.go, line 286 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/10215#-KV0gbWXxWDXBZvLoK8J:-KV0gbWXxWDXBZvLoK8K:b-f2gws6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0593ef49590277cb9df9f4465bee734d3b8773ee/pkg/storage/replica_state.go#L286)):*
> ```Go
> }
> 
> func loadMVCCStats(
> ```

Please don't remove this method, even if it's a thin passthrough. The code to load and persist state should be symmetrical for all of its components.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10215)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica_state.go, line 286 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/10215#-KV0gbWXxWDXBZvLoK8J:-KV0hcc7paW6qrPyJw3m:b-bvwhm5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0593ef49590277cb9df9f4465bee734d3b8773ee/pkg/storage/replica_state.go#L286)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Please don't remove this method, even if it's a thin passthrough. The code to load and persist state should be symmetrical for all of its components.
</details>
Restored.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10215)*

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 2 of 17 files at r8, 1 of 1 files at r9, 4 of 6 files at r11, 2 of 3 files at r12, 8 of 8 files at r13.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10215#-:-KV1F1Tw-rxqrJ8RIWHV:bnfp4nl)*

**Comment by andreimatei** [comment]
A commit from Radu snuck in here? Maybe you rebased on the wrong thing?

LGTM, now I like everything.
But what about `MVCCGetProto()`. Tamir, be a man! :)

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10215#-:-KV1F6lDnHLuV7zOCpVW:b1lax12)*

**Comment by RaduBerinde** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r9, 3 of 6 files at r16, 2 of 3 files at r17, 8 of 8 files at r18, 1 of 1 files at r19, 1 of 1 files at r20, 4 of 4 files at r21, 1 of 2 files at r22, 1 of 1 files at r23.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10215#-:-KV1XhOrdwxJ1Ve5wkDl:b-uwkowd)*

**Comment by tamird** [comment]
TFTR!

**Pull request merged**
