### PR TITLE
sql: make `SET TIME ZONE` equivalent to `SET "time zone"`

### LINKED ISSUE #16457: sql: make SET accept quoted identififers correctly
While working on https://github.com/cockroachdb/docs/pull/1107 I noticed that SHOW supports quoted variable identifiers (e.g. `SHOW "time zone"`) but SET doesn't. We need to rectify this inconsistency to make the docs simpler.

More specifically, SET does accept quoted identifiers but does something strange with them.

### PR DESCRIPTION
**Pull request by knz**
While working on docs I realized that `SET "time zone"` ought to work
but didn't. The cause was that SET was assuming that `String()` on the
variable name would return the variable name unchanged, which is only
true for identifiers that do not contain special characters. This
limitation is now lifted by introducing a special pretty-printer for
SET (FmtBareIdentifiers).

Incidentally, this
Fixes #16457.

I also used the opportunity to subsume SET TIME ZONE under the generic
SET mechanism, which simplifies the code.

Also `RESET "time zone"` is now supported.

### CODE REVIEW

**Comment by jordanlewis** [comment]
Happy day! Nice unification. :lgtm: mod comments

---

Review status: 0 of 17 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/parser/encode.go, line 54 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16459#-KmR_IsMYuybqyelo4r6:-KmR_IsMYuybqyelo4r7:b-ob3y75) ([raw file](https://github.com/cockroachdb/cockroach/blob/a448cf804cfd81a5da447340ecd2f9fc14900c3c/pkg/sql/parser/encode.go#L54)):*
> ```Go
> // non-printable characters are escaped. FmtFlags controls the output format:
> // if f.bareStrings is true, the output string will not be wrapped in quotes
> // if the strings contains no special characters.
> ```

A little lost here. The docs reference f.bareStrings, but you're modifying the behavior w.r.t. bareIdentifiers.

---

*[pkg/sql/parser/encode.go, line 126 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16459#-KmR_P05i9J1NSgQjSnh:-KmR_P05i9J1NSgQjSni:b-ttwv62) ([raw file](https://github.com/cockroachdb/cockroach/blob/a448cf804cfd81a5da447340ecd2f9fc14900c3c/pkg/sql/parser/encode.go#L126)):*
> ```Go
> 	// The only character that requires escaping is a double quote.
> 	if !f.bareIdentifiers {
> 		buf.WriteString(`"`)
> ```

Is there a test that should be added/extended here? Changes to this function make me a little nervous as it's so widespread.

---

*[pkg/sql/parser/format.go, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16459#-KmR__nn-BL-dOsezxGj:-KmR__nn-BL-dOsezxGk:b-5vk6rr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a448cf804cfd81a5da447340ecd2f9fc14900c3c/pkg/sql/parser/format.go#L75)):*
> ```Go
> // FmtBareIdentifiers instructs the pretty-printer to print
> // identifiers without wrapping quotes in any case.
> var FmtBareIdentifiers FmtFlags = &fmtFlags{bareIdentifiers: true}
> ```

Oh I see, I missed that you were adding a new format style. I guess we don't have precedent for testing all of these, but... we really should. Would you care to at least add a test for your new format style?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16459#-:-KmR_jZZvw4Q0V_ianXt:bxzmvzw)*

**Comment by knz** [comment]
Added many tests. PTAL.

---

Review status: 0 of 19 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/parser/encode.go, line 54 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16459#-KmR_IsMYuybqyelo4r6:-KmWcDWS7Y1SPDWgOl5g:b-x2vqni) ([raw file](https://github.com/cockroachdb/cockroach/blob/a448cf804cfd81a5da447340ecd2f9fc14900c3c/pkg/sql/parser/encode.go#L54)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

A little lost here. The docs reference f.bareStrings, but you're modifying the behavior w.r.t. bareIdentifiers.
</blockquote></details>

This is a side-car. Here I am polishing a bit the comments I had been reading to understand what needs to be changed. The patch does not look at bareStrings, but the comment for this was just incomplete/confusing.

---

*[pkg/sql/parser/encode.go, line 126 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16459#-KmR_P05i9J1NSgQjSnh:-KmWzoq2NEBbYg1dRA2X:b-7gclag) ([raw file](https://github.com/cockroachdb/cockroach/blob/a448cf804cfd81a5da447340ecd2f9fc14900c3c/pkg/sql/parser/encode.go#L126)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Is there a test that should be added/extended here? Changes to this function make me a little nervous as it's so widespread.
</blockquote></details>

Added a test.

---

*[pkg/sql/parser/format.go, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16459#-KmR__nn-BL-dOsezxGj:-KmWzk1DhHAgh3bBfUUO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a448cf804cfd81a5da447340ecd2f9fc14900c3c/pkg/sql/parser/format.go#L75)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Oh I see, I missed that you were adding a new format style. I guess we don't have precedent for testing all of these, but... we really should. Would you care to at least add a test for your new format style?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16459#-:-KmWzyaX4hX1zPqPAslo:bea2nvs)*

**Comment by knz** [comment]
I just reviewed one of your PRs, now you do mine :)

**Comment by jordanlewis** [comment]
:lgtm: :thumbsup: :rocket: 

---

Reviewed 19 of 19 files at r2, 18 of 18 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16459#-:-KmYiA9n2GRC41kuJ4OM:b3d6f0r)*

**Comment by knz** [comment]
TFYR :sparkling_heart:

**Pull request merged**
