### PR TITLE
sql: add more logging to troubleshoot #7881

### PR DESCRIPTION
**Pull request by knz**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7962)

### CODE REVIEW

**Comment by paperstreet** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7962#-:-KNDWXgNJ5iggzGPuELt:1417088721)*

**Comment by knz** [comment]
@mberhault I know this is not kosher but is there anything we can get this particular patch to gamma already this week instead of waiting for next week's release?

**Comment by mberhault** [comment]
@knz: it's definitely kosher, we just need to wait for it to be merged and built by circle-ci.
We're not restricting ourselves to beta releases, except for the day or so before the release to qualify it. We also avoid temporary patches, but anything merged into master is considered a valid candidate for beta/gamma/rho.

**Comment by BramGruneir** [comment]
@knz, the beta release is done, so feel free to take over gamma.

**Comment by bdarnell** [comment]
This can be reverted now, right? It's very noisy on the beta clusters.

**Comment by paperstreet** [comment]
That or improve the check. I'll send a PR

**Comment by knz** [comment]
At least collect some examples so that we can investigate this later.

**Comment by paperstreet** [comment]
@bdarnell It's only the first one that's noisy, right?

**Comment by bdarnell** [comment]
```
E160727 00:47:08.843953 sql/executor.go:500  txnState not cleared while txn == nil: &{txn:<nil> State:CommitWait retrying:false retryIntent:true autoRetry:false commitSeen:false schemaChangers:{curGroupNum:12 curStatementIdx:0 schemaChangers:[]} tr:0xc824cedd40 sqlTimestamp:{sec:63605177226 nsec:228761993 loc:0x271bee0}}, execOpt {AutoRetry:false AutoCommit:false MinInitialTimestamp:0.000000000,0}, stmts RELEASE SAVEPOINT cockroach_restart, remaining 
E160727 00:47:08.901698 sql/executor.go:500  txnState not cleared while txn == nil: &{txn:<nil> State:CommitWait retrying:false retryIntent:true autoRetry:false commitSeen:false schemaChangers:{curGroupNum:8 curStatementIdx:0 schemaChangers:[]} tr:0xc824cedd40 sqlTimestamp:{sec:63605177228 nsec:845323919 loc:0x271bee0}}, execOpt {AutoRetry:false AutoCommit:false MinInitialTimestamp:0.000000000,0}, stmts RELEASE SAVEPOINT cockroach_restart, remaining 
E160727 00:47:09.058036 sql/executor.go:500  txnState not cleared while txn == nil: &{txn:<nil> State:CommitWait retrying:false retryIntent:true autoRetry:false commitSeen:false schemaChangers:{curGroupNum:6 curStatementIdx:0 schemaChangers:[]} tr:0xc824cedd40 sqlTimestamp:{sec:63605177228 nsec:902392291 loc:0x271bee0}}, execOpt {AutoRetry:false AutoCommit:false MinInitialTimestamp:0.000000000,0}, stmts RELEASE SAVEPOINT cockroach_restart, remaining 
E160727 00:47:09.092967 sql/executor.go:500  txnState not cleared while txn == nil: &{txn:<nil> State:CommitWait retrying:false retryIntent:true autoRetry:false commitSeen:false schemaChangers:{curGroupNum:8 curStatementIdx:0 schemaChangers:[]} tr:0xc824cedd40 sqlTimestamp:{sec:63605177229 nsec:58687183 loc:0x271bee0}}, execOpt {AutoRetry:false AutoCommit:false MinInitialTimestamp:0.000000000,0}, stmts RELEASE SAVEPOINT cockroach_restart, remaining 
```

**Pull request merged**
