### PR TITLE
sql: add KV rows/bytes read to EXPLAIN ANALYZE (PLAN)

### PR DESCRIPTION
**Pull request by RaduBerinde**
Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57310)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/instrumentation.go, line 428 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57310#-MNUU-ixBE44gLB0A-3M:-MNUU-ixBE44gLB0A-3N:bs9x08s) ([raw file](https://github.com/cockroachdb/cockroach/blob/3385062489eeb967d52d7148b9408a28b282e81f/pkg/sql/instrumentation.go#L428)):*
> ```Go
> // explain.Nodes with execution stats.
> func (m execNodeTraceMetadata) annotateExplain(plan *explain.Plan) {
> 	var walk func(n *explain.Node)
> ```

I was tempted to also aggregate these KV stats at the top-level here, but I realized that would overlap with your code.. I think we should try to come up with a single API to get all the top-level stats from the analyzer and we can use them for both annotating the explain and for the statement stats.

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 6 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57310#-:-MNV5JiGBrvFIO6zXil0:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57310#-:-MNXlYTp8u1W_Hf_x_ji:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/instrumentation.go, line 428 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57310#-MNUU-ixBE44gLB0A-3M:-MNXkTBQAqG7JjtGxoTX:b-1zn5rg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3385062489eeb967d52d7148b9408a28b282e81f/pkg/sql/instrumentation.go#L428)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I was tempted to also aggregate these KV stats at the top-level here, but I realized that would overlap with your code.. I think we should try to come up with a single API to get all the top-level stats from the analyzer and we can use them for both annotating the explain and for the statement stats.
</blockquote></details>

+1 I was thinking we'd use the `TraceAnalyzer` for this as well. What do you need? Some way to provide stats without a physical plan? We could maybe add an `OnlyFromTrace(trace) TraceOnlyAnalyzer` where top-level stats calculations are clearly described in that interface. The big difference with the other mode is that we wouldn't be able to offer any specific aggregations (i.e. by node as network bytes are currently returned). It's possible we don't even want per-node aggregations?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57310)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/instrumentation.go, line 428 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57310#-MNUU-ixBE44gLB0A-3M:-MNZoW9SAGgPaNJdVrdj:b7zi7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/3385062489eeb967d52d7148b9408a28b282e81f/pkg/sql/instrumentation.go#L428)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

+1 I was thinking we'd use the `TraceAnalyzer` for this as well. What do you need? Some way to provide stats without a physical plan? We could maybe add an `OnlyFromTrace(trace) TraceOnlyAnalyzer` where top-level stats calculations are clearly described in that interface. The big difference with the other mode is that we wouldn't be able to offer any specific aggregations (i.e. by node as network bytes are currently returned). It's possible we don't even want per-node aggregations?
</blockquote></details>

I'll keep thinking about it. I think maybe we would want the trace analyzer to do the per-node aggregations too, so that we do all stat aggregations in there. Anyway, the code will be easy to move around once we decide.

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57310#-:-MNZou6L25frRrpyOvzy:b-tlx7ko)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by RaduBerinde** [comment]
Can't figure out what failed, trying again.

bors r+

**Pull request merged**
