### PR TITLE
opt: make placeholder fast path conditional on the estimated row count

### LINKED ISSUE #64214: opt: performance regression on April 21st
roachperf graphs are showing a performance regression across the board on April 21st, e.g.:

<a href="https://roachperf.crdb.dev/?filter=&view=kv95%2Fenc%3Dfalse%2Fnodes%3D1%2Fcpu%3D32&tab=gce">Screenshot 2021-04-26 at 17 09 15</a>

Verified this to be caused by #63807, benchmarks of 22e4d644 (old) vs df67aa97 (new):

```
name                           old ops/sec  new ops/sec  delta
kv95/enc=false/nodes=1/cpu=32   73.1k ± 3%   61.1k ± 3%  -16.30%  (p=0.000 n=9+8)

name                           old p50      new p50      delta
kv95/enc=false/nodes=1/cpu=32    0.70 ± 0%    0.70 ± 0%     ~     (all equal)

name                           old p95      new p95      delta
kv95/enc=false/nodes=1/cpu=32    1.80 ± 0%    2.91 ± 6%  +61.81%  (p=0.000 n=8+8)

name                           old p99      new p99      delta
kv95/enc=false/nodes=1/cpu=32    4.70 ± 0%    6.82 ± 4%  +45.21%  (p=0.000 n=8+8)
```

Notice how the new April 21st graph shows a clear improvement from the start, but then slows down after about a minute to a level significantly below the old April 19th baseline. Statistics collection would be a likely cause for the abrupt change.

Screenshot 2021-04-26 at 17 05 14

Screenshot 2021-04-26 at 17 05 24

/cc @cockroachdb/test-eng

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: show statistics in placeholder-fast-path tests

This highlights a problem with the fast path: we use statistics that
are derived using placeholders, which are usually terrible.

Release note: None

#### opt: mark columns as constant for equality with placeholder

This commit improves the FD generation for Select when we have filters
like `x = $1`. Because these filters have placeholders, they do not
generate constraints (which is the normal mechanism for detecting
constant columns).

This improves the cardinality property and row count estimate. The
estimate will be used for the placeholder fast path.

Release note: None

#### opt: make placeholder fast path conditional on the estimated row count

This change is best explained by this comment:

```
// We are dealing with a memo that still contains placeholders. The statistics
// for such a memo can be wildly overestimated. Even if our plan is correct,
// the estimated row count for a scan is passed to the execution engine which
// uses it to make sizing decisions. Passing a very high count can affect
// performance significantly (see #64214). So we only use the fast path if the
// estimated row count is small; typically this will happen when we constrain
// columns that form a key and we know there will be at most one row.
```

Fixes #64214.

Release note (bug fix): fixed a performance regression for very simple
queries.

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, 5 of 5 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64225#-:-MZEtZjq-zQF9XovPIoK:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/memo/logical_props_builder.go, line 1485 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64225#-MZEdYZ7BBRKvjMPA2rV:-MZEdYZ7BBRKvjMPA2rW:b-774cak) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb68dd1c96c14ab4978a23c7254e374d28168388/pkg/sql/opt/memo/logical_props_builder.go#L1485)):*
> ```Go
> 
> 	// No need to add not null columns, because they are only relevant if there
> 	// are lax FDs that can be made strict.
> ```

nit: You've duplicated this comment a few lines above.

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64225#-:-MZFSTg18cACI2937BhG:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

**Review by mgartner — APPROVED** [review]
> Reviewed 3 of 3 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64225)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

**Comment by erikgrinaker** [comment]
Nice work! 🚀

Screenshot 2021-05-01 at 16 05 02

**Pull request merged**
