### PR TITLE
storage: retry adding a replica on preemptive snapshot failure

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10749)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_raft_test.go, line 2728 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10749#-KWjHLEFyWjCX7OPyVe1:-KWjHLEFyWjCX7OPyVe2:b8odnvv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a08cff54608810ae2b3f364309db70772a20d2a/pkg/storage/client_raft_test.go#L2728)):*
> ```Go
> 		t.Fatalf("expected %s; got %v", expErr, err)
> 	} else if !storage.IsPreemptiveSnapshotFailed(err) {
> 		t.Fatalf("expected preemptive snapshot failed error; got %T", err)
> ```

should %v the error as well as %T-ing it

---

*[pkg/storage/replica_command.go, line 3027 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10749#-KWjGKAkcw9gO-Fw8TC5:-KWjGKAkcw9gO-Fw8TC6:b5xt0vj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a08cff54608810ae2b3f364309db70772a20d2a/pkg/storage/replica_command.go#L3027)):*
> ```Go
> }
> 
> type preemptiveSnapshotFailed struct {
> ```

name should begin with `err`. See https://godoc.org/os#pkg-variables and https://godoc.org/os#IsNotExist

---

*[pkg/storage/replicate_queue.go, line 192 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10749#-KWjGbzht1AU4_XAYGmX:-KWjGbzht1AU4_XAYGmY:b-t9igpk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a08cff54608810ae2b3f364309db70772a20d2a/pkg/storage/replicate_queue.go#L192)):*
> ```Go
> 
> 		log.VEventf(ctx, 1, "adding replica to %+v due to under-replication", newReplica)
> 		if err = rq.addReplica(ctx, repl, newReplica, desc); err != nil {
> ```

while you're here: `=` -> `:=`

---

*[pkg/storage/replicate_queue.go, line 234 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10749#-KWjGcJdzOMQ4pIAZUyo:-KWjGcJdzOMQ4pIAZUyp:b-t9igpk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a08cff54608810ae2b3f364309db70772a20d2a/pkg/storage/replicate_queue.go#L234)):*
> ```Go
> 		} else {
> 			log.VEventf(ctx, 1, "removing replica %+v due to over-replication", removeReplica)
> 			if err = rq.removeReplica(ctx, repl, removeReplica, desc); err != nil {
> ```

while you're here: `=` -> `:=`

---

*[pkg/storage/replicate_queue.go, line 291 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10749#-KWjG_2suDU7uZxyJkqG:-KWjG_2suDU7uZxyJkqH:b-t9igpk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a08cff54608810ae2b3f364309db70772a20d2a/pkg/storage/replicate_queue.go#L291)):*
> ```Go
> 		}
> 		log.VEventf(ctx, 1, "rebalancing to %+v", rebalanceReplica)
> 		if err = rq.addReplica(ctx, repl, rebalanceReplica, desc); err != nil {
> ```

while you're here: `=` -> `:=`

---

*[pkg/storage/replicate_queue.go, line 308 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10749#-KWjH7vkP0tnwSF14zND:-KWjH7vkP0tnwSF14zNE:b-kno2dd) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a08cff54608810ae2b3f364309db70772a20d2a/pkg/storage/replicate_queue.go#L308)):*
> ```Go
> ) error {
> 	err := repl.ChangeReplicas(ctx, roachpb.ADD_REPLICA, repDesc, desc)
> 	if err == nil || IsPreemptiveSnapshotFailed(err) {
> ```

isn't this the same without the `err == nil` check?

---

*[pkg/storage/replicate_queue.go, line 310 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10749#-KWjHGTj7yzB4vqJ6CQU:-KWjHGTkmtcsV2tw7KoT:b-h3dkw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a08cff54608810ae2b3f364309db70772a20d2a/pkg/storage/replicate_queue.go#L310)):*
> ```Go
> 	if err == nil || IsPreemptiveSnapshotFailed(err) {
> 		// If the ChangeReplicas failed because the preemptive snapshot failed, we
> 		// log the error but then return success indicating we should retry the
> ```

how does returning success indicate that a retry is necessary?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10749)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_raft_test.go, line 2728 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10749#-KWjHLEFyWjCX7OPyVe1:-KWjniCiRr7e2Ri-pb77:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a08cff54608810ae2b3f364309db70772a20d2a/pkg/storage/client_raft_test.go#L2728)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> should %v the error as well as %T-ing it
</details>
Done.

---

*[pkg/storage/replica_command.go, line 3027 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10749#-KWjGKAkcw9gO-Fw8TC5:-KWjnqRFsDKIh7lrWxdY:b-pxeba) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a08cff54608810ae2b3f364309db70772a20d2a/pkg/storage/replica_command.go#L3027)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> name should begin with `err`. See https://godoc.org/os#pkg-variables and https://godoc.org/os#IsNotExist
</details>
I'm pretty sure that guidance applies to variables, not types. In the go runtime, error types have names like `NetError`, `PathError`, etc.

---

*[pkg/storage/replicate_queue.go, line 192 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10749#-KWjGbzht1AU4_XAYGmX:-KWjoG7cK-OkOuvMarvN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a08cff54608810ae2b3f364309db70772a20d2a/pkg/storage/replicate_queue.go#L192)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> while you're here: `=` -> `:=`
</details>
Done.

---

*[pkg/storage/replicate_queue.go, line 234 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10749#-KWjGcJdzOMQ4pIAZUyo:-KWjoKrzZRkmZHR8IudI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a08cff54608810ae2b3f364309db70772a20d2a/pkg/storage/replicate_queue.go#L234)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> while you're here: `=` -> `:=`
</details>
Done.

---

*[pkg/storage/replicate_queue.go, line 291 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10749#-KWjG_2suDU7uZxyJkqG:-KWjoLREGY71cyhPy9lp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a08cff54608810ae2b3f364309db70772a20d2a/pkg/storage/replicate_queue.go#L291)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> while you're here: `=` -> `:=`
</details>
Done.

---

*[pkg/storage/replicate_queue.go, line 308 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10749#-KWjH7vkP0tnwSF14zND:-KWjoPuBVLn_4P8ZD-lp:b-kll35c) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a08cff54608810ae2b3f364309db70772a20d2a/pkg/storage/replicate_queue.go#L308)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> isn't this the same without the `err == nil` check?
</details>
Good point, simplified.

---

*[pkg/storage/replicate_queue.go, line 310 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10749#-KWjHGTj7yzB4vqJ6CQU:-KWjoQr6hJu5C5jYyUfl:bqakzgu) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a08cff54608810ae2b3f364309db70772a20d2a/pkg/storage/replicate_queue.go#L310)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> how does returning success indicate that a retry is necessary?
</details>
The caller re-adds the replica to the queue on success, but not on error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10749)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica_command.go, line 3027 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10749#-KWjGKAkcw9gO-Fw8TC5:-KWjyQNDMc9Gc9daTnX3:bdras6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a08cff54608810ae2b3f364309db70772a20d2a/pkg/storage/replica_command.go#L3027)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I'm pretty sure that guidance applies to variables, not types. In the go runtime, error types have names like `NetError`, `PathError`, etc.
</details>
Shouldn't this end with Error then?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10749)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica_command.go, line 3027 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10749#-KWjGKAkcw9gO-Fw8TC5:-KWk08wyCXLAHj9X6xQY:b-ji7r2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a08cff54608810ae2b3f364309db70772a20d2a/pkg/storage/replica_command.go#L3027)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Shouldn't this end with Error then?
</details>
I'm not aware of any guidance on the naming of error types. I don't mind changing the name, but I question whether worrying about this is improving the code. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10749)*

**Comment by tamird** [comment]
Your call, our convention to date has been pretty consistent.

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica_command.go, line 3027 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10749#-KWjGKAkcw9gO-Fw8TC5:-KWl6Gn0srCp-SflHfU9:b-dnkf6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a08cff54608810ae2b3f364309db70772a20d2a/pkg/storage/replica_command.go#L3027)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I'm not aware of any guidance on the naming of error types. I don't mind changing the name, but I question whether worrying about this is improving the code. 
</details>
I like the suffix `Error` for this; we seem to follow it pretty consistently. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10749#-:-KWl7OFp45XoXpGsn2p1:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/replica_command.go, line 3027 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10749#-KWjGKAkcw9gO-Fw8TC5:-KWmSdCA9rkFp5waaZ4o:bi8b638) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a08cff54608810ae2b3f364309db70772a20d2a/pkg/storage/replica_command.go#L3027)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> I like the suffix `Error` for this; we seem to follow it pretty consistently. 
</details>
Done. Though not 100%: 

```
~ git grep -E 'func .* Error\(\) string' | awk -F'[()]' '{print $2}' | awk -F '[ *]' '{print $NF}' | grep -v 'Error$'
errUglifyUnsupported
descriptorAlreadyExistsErr
ErrRetry
ErrTransactionAborted
ErrTransactionCommitted
ErrNonNullViolation
ErrUniquenessConstraintViolation
ErrUndefinedDatabase
ErrUndefinedTable
ErrDatabaseAlreadyExists
ErrRelationAlreadyExists
ErrWrongObjectType
ErrSyntax
ErrDependentObject
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10749)*

**Pull request merged**
