### PR TITLE
storage: Remove illegal updates of MVCCStats

### LINKED ISSUE #5090: storage: RangeStatsKey is not being replicated properly
When I filter out the stats key from the replica checksum computation and turn on the checksum verification  panic all the acceptance tests pass.

```diff
diff --git a/storage/replica_command.go b/storage/replica_command.go
index 423ce06..ff8c390 100644
--- a/storage/replica_command.go
+++ b/storage/replica_command.go
@@ -1422,10 +1422,18 @@ func (r *Replica) sha512(desc roachpb.RangeDescriptor, snap engine.Engine) ([]by
        hasher := sha512.New()
        // Iterate over all the data in the range.
        iter := newReplicaDataIterator(&desc, snap, true /* replicatedOnly */)
+       // stats key to be ignored for now.
+       statsKey := keys.RangeStatsKey(r.Desc().RangeID)
        defer iter.Close()
        for ; iter.Valid(); iter.Next() {
                key := iter.Key()
                value := iter.Value()
+
+               // Ignore the stats key because it's not replicated.
+               if bytes.Equal(key.Key, statsKey) {
+                       continue
+               }
+
                // Encode the length of the key and value.
                if err := binary.Write(hasher, binary.LittleEndian, int64(len(key.Key))); err != nil {
                        return nil, err
@@ -1494,7 +1502,7 @@ func (r *Replica) VerifyChecksum(batch engine.Engine, ms *engine.MVCCStats, h ro
                                        p()
                                } else {
                                        // TODO(.*): see #5051.
-                                       log.Errorf("checksums: e = %v, v = %v", args.Checksum, c.checksum)
+                                       panic(fmt.Sprintf("checksums: e = %v, v = %v", args.Checksum, c.checksum))
                                }
                        }
                } else {
```

### PR DESCRIPTION
**Pull request by vivekmenezes**
closes #5090

---

This change is [Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5133)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
:lgtm: I'm pleasantly surprised that this is all we needed to do to fix that issue. Do you mind adding a quick description in the commit/PR message about what the illegal update of MVCCStats was here and how it was causing issues?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/stats.go, line 113 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5133#-KCZawn7IA5e3zptJz7J:-KCZawn7IA5e3zptJz7K:-1915310206) ([raw file](https://github.com/cockroachdb/cockroach/blob/93880698e8258e0aa9abedc8b1215ac7b0fd0ef8/storage/stats.go#L113)):*
These two lines can just be written as `cp := rs.MVCCStats`

---

*[storage/stats.go, line 128 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5133#-KCZbAoQHvxGkc8bqQVz:-KCZbAoQHvxGkc8bqQW-:1662569705) ([raw file](https://github.com/cockroachdb/cockroach/blob/93880698e8258e0aa9abedc8b1215ac7b0fd0ef8/storage/stats.go#L128)):*
Same here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5133#-:-KCZbJ9c8J7YThrz0S_N:-426234824)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[storage/stats.go, line 111 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5133#-KCa0GojnZyA8I2M-RCT:-KCa0Gokra_8XEAHuUFI:-1771391604) ([raw file](https://github.com/cockroachdb/cockroach/blob/93880698e8258e0aa9abedc8b1215ac7b0fd0ef8/storage/stats.go#L111)):*
Why is updating `rs.MVCCStats` problematic? I imagine it has to do with `MVCCStats.LastUpdateNanos` changing differently on each replica while normally `LastUpdateNanos` is based on a transaction timestamp. If yes, please call that out in the comment. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5133#-:-KCa0v01Lm8-cxXtOe0_:1417088721)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[storage/stats.go, line 111 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5133#-KCa0GojnZyA8I2M-RCT:-KCaAEH1OxWAdhH3Puc2:-1266323813) ([raw file](https://github.com/cockroachdb/cockroach/blob/93880698e8258e0aa9abedc8b1215ac7b0fd0ef8/storage/stats.go#L111)):*
Added this comment to the commit:

There are two issues here:
    1. All updates done to the cache need to be reflected into
    the underlying kv store.
    2. All updates need to be done through raft and through
    r.stats.MergeMVCCStats(). In this case these two functions
    were called through the GC process with no consensus on these
    changes, so when an actual r.stats.MergeMVCCStats() was called
    through raft, LastUpdateNanos in the kv store was updated
    to the value changed through the GC process resulting in an
    inconsistent value.

---

*[storage/stats.go, line 113 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5133#-KCZawn7IA5e3zptJz7J:-KCa5GeAk-Nb9YrCacdD:190559596) ([raw file](https://github.com/cockroachdb/cockroach/blob/93880698e8258e0aa9abedc8b1215ac7b0fd0ef8/storage/stats.go#L113)):*
changed to `var cp engine.MVCCStats = rs.MVCCStats`

---

*[storage/stats.go, line 128 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5133#-KCZbAoQHvxGkc8bqQVz:-KCa5QS85_-fdfFQ4Yaz:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/93880698e8258e0aa9abedc8b1215ac7b0fd0ef8/storage/stats.go#L128)):*
done

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5133)*

**Comment by tschottdorf** [comment]
LGTM

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[storage/stats.go, line 111 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5133#-KCa0GojnZyA8I2M-RCT:-KCaAn8oa10c9ZzGL4Nv:272397546) ([raw file](https://github.com/cockroachdb/cockroach/blob/93880698e8258e0aa9abedc8b1215ac7b0fd0ef8/storage/stats.go#L111)):*
I think this deserves to be commented in the code: `Make a copy so that rs.MVCCStats is not updated. Changes to rs.MVCCStats need to be performed via raft commands.`

---

*[storage/stats.go, line 113 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5133#-KCZawn7IA5e3zptJz7J:-KCaAap1OO4R54a0Ca2M:2135104400) ([raw file](https://github.com/cockroachdb/cockroach/blob/93880698e8258e0aa9abedc8b1215ac7b0fd0ef8/storage/stats.go#L113)):*
What was wrong with Nathan's suggestion? The `:=` operator exists so that you don't have to stutter.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5133)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[storage/stats.go, line 113 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5133#-KCZawn7IA5e3zptJz7J:-KCaKx8m1UuIFzQDEUwz:-1847096967) ([raw file](https://github.com/cockroachdb/cockroach/blob/93880698e8258e0aa9abedc8b1215ac7b0fd0ef8/storage/stats.go#L113)):*
nevermind

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5133)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[storage/stats.go, line 111 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5133#-KCa0GojnZyA8I2M-RCT:-KCaUHiVHSU-akl9sf_0:1269600066) ([raw file](https://github.com/cockroachdb/cockroach/blob/93880698e8258e0aa9abedc8b1215ac7b0fd0ef8/storage/stats.go#L111)):*
+1 on this. Why not add this comment?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5133)*

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[storage/stats.go, line 111 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5133#-KCa0GojnZyA8I2M-RCT:-KCaY-Dy2SkgqZSzRAEH:-969469107) ([raw file](https://github.com/cockroachdb/cockroach/blob/93880698e8258e0aa9abedc8b1215ac7b0fd0ef8/storage/stats.go#L111)):*
missed this. I've added it to another PR. Thanks

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5133)*

**Pull request merged**
