### PR TITLE
engine: Handle put when all writes are ignored and there are no committed values

### PR DESCRIPTION
**Pull request by knz**
(This is really an issue, filed as a PR because it contains a test case in the right place)

The following sequence currently triggers an assertion error inside
`mvcc.go`, where it should succeed without error instead:

1. start txn
2. put at seq = 10
3. ignore seqs 5-15
4. put at seq = 20

The error is: `previous intent of the transaction with the same epoch
not found for ...` (mvcc.go:1650)

See the enclosed test case.

Release note: none

### CODE REVIEW

**Comment by knz** [comment]
@itsbilal @nvanbenschoten your input/opinion would be appreciated

**Comment by nvanbenschoten** [comment]
This is falling into roughly the same situation as
https://github.com/cockroachdb/cockroach/blob/52249186a90c3ce328164e318105237c53861c5e/pkg/storage/engine/mvcc.go#L1593-L1596

To see this, let's remember the partial equivalence between a transaction restart (increasing its epoch) and a transaction rollback (adding to its IgnoredSeqNums).

Here, we have a txn overwriting a key that it has previously written. However, the previous value is now ignored, so it doesn't want to move the existing value into its intent history. In the txn restart case, we wipe the entire sequence history, because we know it's all now ignored. In this case, we don't necessarily want to wipe the entire sequence history, but we should avoid adding the existing value to the sequence history when we overwrite it.

So the change we want is basically just (though it should be cleaned up):
```go
diff --git a/pkg/storage/engine/mvcc.go b/pkg/storage/engine/mvcc.go
index 595b51ad3e..325aaa2ef1 100644
--- a/pkg/storage/engine/mvcc.go
+++ b/pkg/storage/engine/mvcc.go
@@ -1642,15 +1642,9 @@ func mvccPutInternal(
                        // If the epoch of the transaction doesn't match the epoch of the
                        // intent, blow away the intent history.
                        if txn.Epoch == meta.Txn.Epoch {
-                               if existingVal == nil {
-                                       // This case shouldn't pop up, but it is worth asserting
-                                       // that it doesn't. We shouldn't write invalid intents
-                                       // to the history.
-                                       return errors.Errorf(
-                                               "previous intent of the transaction with the same epoch not found for %s (%+v)",
-                                               metaKey, txn)
+                               if existingVal != nil {
+                                       buf.newMeta.AddToIntentHistory(prevIntentSequence, prevIntentValBytes)
                                }
-                               buf.newMeta.AddToIntentHistory(prevIntentSequence, prevIntentValBytes)
                        } else {
                                buf.newMeta.IntentHistory = nil
                        }
```

**Comment by knz** [comment]
Thanks Nathan for the early analysis. @itsbilal what do you think?

Also Nathan what do you mean with "it needs to be cleaned up"?

**Comment by itsbilal** [comment]
Nathan's overview makes sense to me - we shouldn't be throwing an error in this case, instead just not writing the existing value in the intent history. If I'm reading correctly, we should also be safe to just blow up the intent history just like we do with txn restarts; the only case where we'll have `txn.Epoch == meta.Txn.Epoch` and `existingVal == nil` is when all writes are ignored: 

https://github.com/cockroachdb/cockroach/blob/52249186a90c3ce328164e318105237c53861c5e/pkg/storage/engine/mvcc.go#L1542-1564

I'm assuming, by "cleanup", Nathan is referring to updating comments in `mvccPutInternal` about the cases that can cause `existingVal` to be nil, but I'll wait for him to expand on that before I add to this PR.

**Comment by nvanbenschoten** [comment]
Yes, by cleanup I just meant that the comment will need to be updated. There might also be a better way to structure the code after this change. I'll leave that for you to decide.

**Comment by knz** [comment]
Ok thanks for the insights. Just this discussion is sufficient to unblock other parts of my work, but I'd prefer if @itsbilal could own this PR and bring it to completion with a fix.

(And maybe extend the test suite to include other types of MVCC operations than Puts to check we have all paths covered)

**Comment by itsbilal** [comment]
The second commit fixes the issue and updates the test that Raphael wrote. This is ready for a review.

**Review by knz — COMMENTED** [review]
LGTM but don't take my word for it

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44697#-:-M-LEJEk78oJkG5-zLXn:bvypcav)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/testdata/mvcc_histories/put_after_rollback, line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44697#-M-LEBY10QSm0H1r7XEu:-M-LEBY256mxIOLYfPtW:b9kasj) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e3e489e93659c012f42b4b0b0d80a4844f4091/pkg/storage/engine/testdata/mvcc_histories/put_after_rollback#L26)):*
> ```
>   txn_ignore_seqs seqs=(5-35)
>   txn_step  seq=40
>   del       v=b
> ```

I'd like to see more tests with other op types (cput at least)

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44697)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/mvcc.go, line 1542 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44697#-M-LFDL-7Kzrgg54UyD1:-M-LFDL-7Kzrgg54UyD2:b-uz02rh) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e3e489e93659c012f42b4b0b0d80a4844f4091/pkg/storage/engine/mvcc.go#L1542)):*
> ```
> been rolled back, either due to transaction retries or transaction savepoint rollbacks.
> ```
___
*[pkg/storage/engine/mvcc.go, line 1639 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44697#-M-LFY0qA9oq_Y2Jtsyi:-M-LFY0qA9oq_Y2Jtsyj:ba6h210) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e3e489e93659c012f42b4b0b0d80a4844f4091/pkg/storage/engine/mvcc.go#L1639)):*
> ```Go
> 				writeTimestamp = metaTimestamp
> 			}
> 			// Since an intent with a smaller sequence number exists for the
> ```

Is there a reason why this logic is split from the `// It's possible that the existing value is nil if the intent on the key` logic? That's part of what made this unclear.

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44697)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @nvanbenschoten, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/mvcc.go, line 1542 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44697#-M-LFDL-7Kzrgg54UyD1:-M-LIp919Ka1WaVI2X5P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e3e489e93659c012f42b4b0b0d80a4844f4091/pkg/storage/engine/mvcc.go#L1542)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> been rolled back, either due to transaction retries or transaction savepoint rollbacks.
> ```

</blockquote></details>

Done.
___
*[pkg/storage/engine/mvcc.go, line 1639 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44697#-M-LFY0qA9oq_Y2Jtsyi:-M-LNO225FVVPRJMStWP:b-adafmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e3e489e93659c012f42b4b0b0d80a4844f4091/pkg/storage/engine/mvcc.go#L1639)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is there a reason why this logic is split from the `// It's possible that the existing value is nil if the intent on the key` logic? That's part of what made this unclear.
</blockquote></details>

No reason really. Good point; I'll move that down as well.
___
*[pkg/storage/engine/testdata/mvcc_histories/put_after_rollback, line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44697#-M-LEBY10QSm0H1r7XEu:-M-LOPPK4dmHr1K8Fudn:b-xxkkvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e3e489e93659c012f42b4b0b0d80a4844f4091/pkg/storage/engine/testdata/mvcc_histories/put_after_rollback#L26)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'd like to see more tests with other op types (cput at least)
</blockquote></details>

Done. Added cput test. They all use `mvccPutInternal` in the end so it shouldn't change too much.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44697)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/mvcc.go, line 1542 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44697#-M-LFDL-7Kzrgg54UyD1:-M-LR-p6-VR48Sm0eKzf:b69df1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e3e489e93659c012f42b4b0b0d80a4844f4091/pkg/storage/engine/mvcc.go#L1542)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks. While you're here, do you mind wrapping this entire comment to 80 chars?
___
*[pkg/storage/engine/mvcc.go, line 1644 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44697#-M-LRbg7DCLxDzMg1nMG:-M-LRbg7DCLxDzMg1nMH:beia58i) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb03aa121b204e5df6a6112787e7a94627eefde/pkg/storage/engine/mvcc.go#L1644)):*
> ```Go
> 			// transaction are ignored, and there are no past committed values at this
> 			// key.
> 			if txn.Epoch == meta.Txn.Epoch && existingVal != nil {
> ```

I just realized that this isn't equivalent to what we had in https://github.com/cockroachdb/cockroach/pull/44697#issuecomment-582043328. Specifically, we're now going to wipe the intent history if the `existingVal` is nil.

That reveals something I think we have wrong here in both attempts. `existingVal` isn't the existing provisional value. Instead, it's the latest non-reverted value in the entire sequence history. It doesn't make sense that we'd be adding something from the sequence history back into the sequence history. We only want to add something here if the current provisional value is not ignored. So the semantics we want are something like:
```go
curProvVal := ... // not existingVal
if txn.Epoch == meta.Txn.Epoch {
    if !enginepb.TxnSeqIsIgnored(meta.Txn.Sequence, txn.IgnoredSeqNums) {
        buf.newMeta.AddToIntentHistory(meta.Txn.Sequence, curProvVal)
    }
} else {
   buf.newMeta.IntentHistory = nil
}
```

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44697)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @nvanbenschoten, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/mvcc.go, line 1542 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44697#-M-LFDL-7Kzrgg54UyD1:-M-Lq4drCt9fFfJ8qO3g:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e3e489e93659c012f42b4b0b0d80a4844f4091/pkg/storage/engine/mvcc.go#L1542)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Thanks. While you're here, do you mind wrapping this entire comment to 80 chars?
</blockquote></details>

Done.
___
*[pkg/storage/engine/mvcc.go, line 1644 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44697#-M-LRbg7DCLxDzMg1nMG:-M-Lo_L6-j-Rb05ZhU2C:b-wjnu4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb03aa121b204e5df6a6112787e7a94627eefde/pkg/storage/engine/mvcc.go#L1644)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I just realized that this isn't equivalent to what we had in https://github.com/cockroachdb/cockroach/pull/44697#issuecomment-582043328. Specifically, we're now going to wipe the intent history if the `existingVal` is nil.

That reveals something I think we have wrong here in both attempts. `existingVal` isn't the existing provisional value. Instead, it's the latest non-reverted value in the entire sequence history. It doesn't make sense that we'd be adding something from the sequence history back into the sequence history. We only want to add something here if the current provisional value is not ignored. So the semantics we want are something like:
```go
curProvVal := ... // not existingVal
if txn.Epoch == meta.Txn.Epoch {
    if !enginepb.TxnSeqIsIgnored(meta.Txn.Sequence, txn.IgnoredSeqNums) {
        buf.newMeta.AddToIntentHistory(meta.Txn.Sequence, curProvVal)
    }
} else {
   buf.newMeta.IntentHistory = nil
}
```
</blockquote></details>

Yes, that difference from your comment is intentional, and something I observed and expanded on in my comment. Basically, if all provisional writes are ignored including the current one, we should be blowing up the intent history. We don't have to do it, but it's a minor performance win. This is the epochs-matching but `existingVal == nil`.

I've copied the semantics in the example you provided - thanks for that! Only difference is I still retained the `existingValue != nil` in the conditional. PTAL!

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44697)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @knz, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/mvcc.go, line 1644 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44697#-M-LRbg7DCLxDzMg1nMG:-M-LzjPC68OO60pyuPn1:bbqbggq) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb03aa121b204e5df6a6112787e7a94627eefde/pkg/storage/engine/mvcc.go#L1644)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Yes, that difference from your comment is intentional, and something I observed and expanded on in my comment. Basically, if all provisional writes are ignored including the current one, we should be blowing up the intent history. We don't have to do it, but it's a minor performance win. This is the epochs-matching but `existingVal == nil`.

I've copied the semantics in the example you provided - thanks for that! Only difference is I still retained the `existingValue != nil` in the conditional. PTAL!
</blockquote></details>

Thanks! Can you construct a test case where the previous bug would have resulted in incorrect behavior? Mind adding that to a `mvcc_histories` test?
___
*[pkg/storage/engine/mvcc.go, line 1551 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44697#-M-LzNIN9gZnKvo0vrnC:-M-LzNIN9gZnKvo0vrnD:b-cq8vem) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0c0cdc463a623d38c4318b665d6c21e80f4d32b/pkg/storage/engine/mvcc.go#L1551)):*
> ```Go
> 			// Aliases existingVal when the current provisional value is readable
> 			// and not rolled back (due to a savepoint rollback or txn restart).
> 			var curProvVal *roachpb.Value
> ```

nit: consider changing this to a bool (`currentProvisionalNotIgnored` or something less verbose but with the same meaning) and using `existingVal` below when this is `true`.

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44697)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @nvanbenschoten, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/mvcc.go, line 1644 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44697#-M-LRbg7DCLxDzMg1nMG:-M-MD-h510c3AvDLtT2H:bofkwk6) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb03aa121b204e5df6a6112787e7a94627eefde/pkg/storage/engine/mvcc.go#L1644)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Thanks! Can you construct a test case where the previous bug would have resulted in incorrect behavior? Mind adding that to a `mvcc_histories` test?
</blockquote></details>

Done. I couldn't think of an example where it causes a genuine correctness issue (assuming the set of ignored sequence numbers can only increase), but I wrote one case where it was adding repeated values as well as already-committed values to the ignore list. 

There were no correctness issues because any erroneous additions to the ignore list were happening when the current write was already ignored, so `meta.Txn.Sequence` was on the ignore list. That value would never have surfaced unless that sequence number got un-ignored.
___
*[pkg/storage/engine/mvcc.go, line 1551 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44697#-M-LzNIN9gZnKvo0vrnC:-M-MDc2FE850PQrLrl2s:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0c0cdc463a623d38c4318b665d6c21e80f4d32b/pkg/storage/engine/mvcc.go#L1551)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: consider changing this to a bool (`currentProvisionalNotIgnored` or something less verbose but with the same meaning) and using `existingVal` below when this is `true`.
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44697)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/mvcc.go, line 1644 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44697#-M-LRbg7DCLxDzMg1nMG:-M-NbGXN6wZbJspgN1bG:b2moqzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb03aa121b204e5df6a6112787e7a94627eefde/pkg/storage/engine/mvcc.go#L1644)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Done. I couldn't think of an example where it causes a genuine correctness issue (assuming the set of ignored sequence numbers can only increase), but I wrote one case where it was adding repeated values as well as already-committed values to the ignore list. 

There were no correctness issues because any erroneous additions to the ignore list were happening when the current write was already ignored, so `meta.Txn.Sequence` was on the ignore list. That value would never have surfaced unless that sequence number got un-ignored.
</blockquote></details>

Thanks. You can take or leave this last suggestion - either way this LGTM. I'm realizing that clearing that intent history now depends on whether there are any other versions from other txns picked up in the `if existingVal == nil {` branch above. That's pretty strange, even if it won't actually cause any correctness issues.

This whole decision of what to do with the intent history is difficult because we're poking at it from so far away. It might just be easier to move the `AddToHistory` up to where you currently have `curProvNotIgnored = true` and the `IntentHistory = nil` up to exactly where you want it; an else branch of `if txn.Epoch == meta.Txn.Epoch /* last write inside txn */ {` and an else branch of `if prevValueWritten {`. That will make this all much more explicit.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44697)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @petermattis)

___
*[pkg/storage/engine/mvcc.go, line 1540 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44697#-M-Q-UVpD8sLgE4Ltn-A:-M-Q-UVpD8sLgE4Ltn-B:b-zb224r) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c217359ed6829ef980a807250a8ffd4e2dbb6c2/pkg/storage/engine/mvcc.go#L1540)):*
> ```
> last write outside txn
> ```

what does this phrase mean? Is it synonymous with different epoch since the metadata we found had the same txn ID?

I find this function very confusing, and have a very basic question:
- we have read an intent MVCCMetadata for this transaction
- is it correct to say that meta.Timestamp is guaranteed to refer to the provisional value, so we can just read it (why the complicated call to mvccGetInternal())?
- so first decide whether we need to (a) read it or not, and do the read if needed (b) delete it or not (not if the new provisional value will be at the same timestamp).
- then construct the new MVCCMetadata based on the old MVCCMetadata, new write, ignoredSeqNums and the read value. This could be a separate function -- it doesn't need an iterator.
- in a batch: write the new MVCCMetadata; write the provisional value delete if needed; write the new provisional value.

I don't claim the above is simpler, but mainly wanting to figure out what nuances I am missing.

**Review by itsbilal — COMMENTED** [review]
Thanks for the reviews!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44697#-:-M-QRI4C5GvK32eDU8BO:bctxt4d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/mvcc.go, line 1644 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44697#-M-LRbg7DCLxDzMg1nMG:-M-QNYEM9Atp6Cjs4k6T:b-7yke1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb03aa121b204e5df6a6112787e7a94627eefde/pkg/storage/engine/mvcc.go#L1644)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Thanks. You can take or leave this last suggestion - either way this LGTM. I'm realizing that clearing that intent history now depends on whether there are any other versions from other txns picked up in the `if existingVal == nil {` branch above. That's pretty strange, even if it won't actually cause any correctness issues.

This whole decision of what to do with the intent history is difficult because we're poking at it from so far away. It might just be easier to move the `AddToHistory` up to where you currently have `curProvNotIgnored = true` and the `IntentHistory = nil` up to exactly where you want it; an else branch of `if txn.Epoch == meta.Txn.Epoch /* last write inside txn */ {` and an else branch of `if prevValueWritten {`. That will make this all much more explicit.
</blockquote></details>

I also find it weird that `existingVal == nil` is being used to denote blowing up the intent history, but it is correct, and the comments should make it easier to understand.

My only issue with making the moves you suggested would be that it'd move the intent history change before the `valueFn` execution, and the comments around that call specifically state that `valueFn` should be called before the provisional value is moved around. If I do move the AddToIntentHistory call up, and `valueFn` returns an error, there's a chance we could have the provisional value lying both in the intent history as well as in the mvcc keyspace. I'll leave it as-is. Thanks for the review!
___
*[pkg/storage/engine/mvcc.go, line 1540 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44697#-M-Q-UVpD8sLgE4Ltn-A:-M-QOu_4DqCJpG7JoZtz:b-kw8fyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c217359ed6829ef980a807250a8ffd4e2dbb6c2/pkg/storage/engine/mvcc.go#L1540)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> ```
> last write outside txn
> ```

what does this phrase mean? Is it synonymous with different epoch since the metadata we found had the same txn ID?

I find this function very confusing, and have a very basic question:
- we have read an intent MVCCMetadata for this transaction
- is it correct to say that meta.Timestamp is guaranteed to refer to the provisional value, so we can just read it (why the complicated call to mvccGetInternal())?
- so first decide whether we need to (a) read it or not, and do the read if needed (b) delete it or not (not if the new provisional value will be at the same timestamp).
- then construct the new MVCCMetadata based on the old MVCCMetadata, new write, ignoredSeqNums and the read value. This could be a separate function -- it doesn't need an iterator.
- in a batch: write the new MVCCMetadata; write the provisional value delete if needed; write the new provisional value.

I don't claim the above is simpler, but mainly wanting to figure out what nuances I am missing.
</blockquote></details>

That's a very good question, and something that also tripped me up at first. Basically, `mvccGetInternal`, unlike the full scanner backed `MVCCGet()`, is not aware of sequence numbers at all. If we just issue the `mvccGetInternal` read rightaway, we might get a value that has now been rolled back. That's why the call to that function is complicated, and could happen multiple times in the same method.

The MVCCMetadata construction is currently wound up in the `buf *putBuffer` for efficiency, if you want to take a look.

All of this should already be happening in a batch in practice. The actual management of batches happens in KV land , and the Put Raft command only accepts a "ReadWriter" as its input, so while it could also be an engine, we should probably not be doing batch management at this level.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44697)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @knz, and @petermattis)

___
*[pkg/storage/engine/mvcc.go, line 1540 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44697#-M-Q-UVpD8sLgE4Ltn-A:-M-QfBh2D_2FgnLsbJUN:b-fy0502) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c217359ed6829ef980a807250a8ffd4e2dbb6c2/pkg/storage/engine/mvcc.go#L1540)):*
> Basically, mvccGetInternal, unlike the full scanner backed MVCCGet(), is not aware of sequence numbers at all. If we just issue the mvccGetInternal read rightaway, we might get a value that has now been rolled back. That's why the call to that function is complicated, and could happen multiple times in the same method.

Sorry about being slow here, but I still don't understand. If we have an intent it must point to the provisional value, so we can do a `Get()` for a specific key.

> The MVCCMetadata construction is currently wound up in the buf *putBuffer for efficiency, if you want to take a look.
> All of this should already be happening in a batch in practice. The actual management of batches happens in KV land , and the Put Raft command only accepts a "ReadWriter" as its input, so while it could also be an engine, we should probably not be doing batch management at this level.

I should not have said "batch" since I didn't mean the code-level abstraction -- just substitute `Writer.Put()` for what I said.

My original comment was asking whether one could restructure the code that has found an intent to something like:
```
var existingValue *roachpb.Value
if needToPlaceExistingValueInHistory(meta, txn) {
  existingValue = iter.GetValue(MakeKey(key, meta.Timestamp)) // assuming a simple GetValue() method that gets the value at a particular MVCCKey
}
overwrite := meta.Timestamp == writeTimestamp
if !overwrite {
  writer.Clear(MakeKey(key, meta.Timestamp)
}
if existingValue != nil {
   meta = fixHistory(meta, txn, existingValue)
}
meta = updateMetaForLatestWrite(meta, txn) // updates Txn, Timestamp, KeyBytes, ValueBytes.
writer.Put(MakeKey(key, 0), meta)
writer.Put(MakeKey(key, writeTimestamp), value)
```

I am overlooking the complexity introduced by MVCCStats, but longer term is it possible to simplify? I am not suggesting doing that soon, and just trying to understand the possibilities -- we will make changes when we introduce the segregated lock table so that could be a good time to do extensive refactoring.

**Comment by itsbilal** [comment]
___
*[pkg/storage/engine/mvcc.go, line 1540 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44697#-M-Q-UVpD8sLgE4Ltn-A:-M-QuAjJ2PeyZpVFCKGR:b-r7zrpz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c217359ed6829ef980a807250a8ffd4e2dbb6c2/pkg/storage/engine/mvcc.go#L1540)):*
Also realized I didn't respond to your "last write outside txn" question earlier - it just refers to the last readable write being before the start of this transaction in the MVCC keyspace, so we do a historic read using an inconsistent mvccGetInternal.

> Sorry about being slow here, but I still don't understand. If we have an intent it must point to the provisional value, so we can do a Get() for a specific key.

The rollback sequence numbers are specified in `txn.IgnoredSeqNums`, and can be (and usually is) newer data than what's in the MVCC keyspace. So the write the intent is pointing to may be considered rolled back, and if it is, the right way to read it is to call `GetPrevIntentSeq` and go through the intent history in the intent metadata itself instead of `mvccGetInternal`. Now this would be unnecessary if `mvccGetInternal` took the ignore list into account and looked into the intent history as necessary, but it doesn't do that, unlike the pebble and rocksdb mvcc scanners.

Your simplified overview seems to make sense to me, and is something we can consider down the line for sure. I'll have to compare that side-by-side with the current long-winded implementation to see if it's missing anything. There's definitely some historic cruft in the current implementation, but given how critical this code is, we've all been hesitant to refactor it significantly lest it breaks something. And this PR is a perfect example of how we've tried to shoehorn new functionality into existing paradigms instead of completely rethinking this code.

**Pull request merged**
