### PR TITLE
cmd/roachtest: add TPCC for sqlsmith

### PR DESCRIPTION
**Pull request by madelynnblue**
Also fix TPCH while here. Tables must be in the defaultdb database.

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42465#-:-Ltb3zic98fO6Nb4ZN3-:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/cmd/roachtest/sqlsmith.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42465#-Ltb37cuAzWVeK2kDci0:-Ltb37cv3cIUWVdO7kVu:b-l7xd4u) ([raw file](https://github.com/cockroachdb/cockroach/blob/976202985fb0995a62860cbf29236738834a8d2e/pkg/cmd/roachtest/sqlsmith.go#L48)):*
> ```Go
> 				"warehouse",
> 			} {
> 				fmt.Fprintf(&sb, "RESTORE TABLE tpcc.%s FROM 'gs://cockroach-fixtures/workload/tpcc/%[2]s/%[1]s' WITH into_db = 'defaultdb';\n", t, version)
> ```

How can someone check which fixtures are available? I tried looking through Google Cloud Storage browser, but I don't see `cockroach-fixtures` bucket (maybe I don't have the permissions).

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42465)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/cmd/roachtest/sqlsmith.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42465#-Ltb37cuAzWVeK2kDci0:-Ltb4OI93PHpfo1KX2uP:b-tebjvo) ([raw file](https://github.com/cockroachdb/cockroach/blob/976202985fb0995a62860cbf29236738834a8d2e/pkg/cmd/roachtest/sqlsmith.go#L48)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

How can someone check which fixtures are available? I tried looking through Google Cloud Storage browser, but I don't see `cockroach-fixtures` bucket (maybe I don't have the permissions).
</blockquote></details>

They are under the `cockroach-shared` project.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42465)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/cmd/roachtest/sqlsmith.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42465#-Ltb37cuAzWVeK2kDci0:-Ltb4tM60kKQP8MMxFwz:b-kufkxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/976202985fb0995a62860cbf29236738834a8d2e/pkg/cmd/roachtest/sqlsmith.go#L48)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

They are under the `cockroach-shared` project.
</blockquote></details>

I see, thanks!

**Comment by yuzefovich** [comment]
Looks like TPCH fix doesn't work https://github.com/cockroachdb/cockroach/issues/42212#issuecomment-553775945

Maybe all tables need to be explicitly restored if we're using `into_db` option (similar to what is done for TPCC in this PR)?

**Pull request merged**
