### PR TITLE
rpc: replace with gRPC

### LINKED ISSUE #1521: rpc: remove the need to deal with `rpc.Client` directly
Previously, we had backoff logic for this in rpc/client; this was removed in #1285 and then refined in #1394. The result is that each raft message will spawn a new rpc client and attempt to connect. This is a lot of log, goroutine, and network thrash.

### LINKED ISSUE #1633: rpc/client: clock updates should be done one level higher
The `rpc` package is cockroach's wrapper around `net/rpc`. Within it, `client` currently:
- caches rpc clients such that there is at most one per outbound address (in a single global variable)
- periodically heartbeats the remote side, and updates a clock which is passed by reference into the `NewClient` factory method

The users of `rpc/client` are `multiraft`, `gossip`, and `kv` (namely `DistSender`). As far as I can tell, only `kv` relies on the clock synchronization to do its work; `gossip` and `multiraft` don't care. Furthermore, it has been suggested in #1283 that having just one `net/rpc.Client` per remote address is not ideal.

I suggest we dismantle `rpc/client` and move its responsibilities to `rpc/send` (the interface used by `kv.DistSender`). The only thing we should keep there is the current use of `rpc/codec`.

`gossip` and `multiraft` don't even need `rpc/codec`, since they are used _only_ between cockroach nodes, and would work just fine using Go's default `gob`-based codec. They should use the regular `net/rpc` facilities.

### LINKED ISSUE #2642: rpc: make retry options configurable per-client
This is currently global. See #2641.

### LINKED ISSUE #3942: circleci: failed tests (11756): TestClientNotReady
The following test appears to have failed:

[#11756](https://circleci.com/gh/cockroachdb/cockroach/11756):

```
--- PASS: TestUnretryableError (0.02s)
=== RUN   TestClientNotReady
W0121 17:30:38.424616 289 rpc/send.go:200  Heartbeat.Ping: error reply: rpc/send.go:249: rpc to Heartbeat.Ping: client not ready after 100ns
W0121 17:30:38.448307 289 rpc/client.go:328  client is closed
W0121 17:30:38.558877 289 rpc/client.go:328  client is closed
--- FAIL: TestClientNotReady (0.14s)
	send_test.go:265: rpc/send_test.go:248: expected error when client is closed
=== RUN   TestComplexScenarios
W0121 17:30:38.562952 289 rpc/send.go:200  Heartbeat.Ping: error reply: failed to send RPC: test
W0121 17:30:38.563193 289 rpc/send.go:200  Heartbeat.Ping: error reply: failed to send RPC: test
W0121 17:30:38.563238 289 rpc/send.go:200  Heartbeat.Ping: error reply: failed to send RPC: test
W0121 17:30:38.563283 289 rpc/send.go:200  Heartbeat.Ping: error reply: failed to send RPC: test
W0121 17:30:38.563330 289 rpc/send.go:200  Heartbeat.Ping: error reply: failed to send RPC: test
W0121 17:30:38.565147 289 rpc/send.go:200  Heartbeat.Ping: error reply: failed to send RPC: test
W0121 17:30:38.565208 289 rpc/send.go:200  Heartbeat.Ping: error reply: failed to send RPC: test
W0121 17:30:38.565502 289 rpc/send.go:200  Heartbeat.Ping: error reply: failed to send RPC: test
--
	leaktest.go:110: prior leak detected, leaktest disabled
=== RUN   TestUnregisteredMethod
W0121 17:30:38.668932 289 rpc/send.go:200  Foo.Bar: error reply: rpc/server.go:247: rpc: couldn't find method: Foo.Bar
--- PASS: TestUnregisteredMethod (0.08s)
	leaktest.go:110: prior leak detected, leaktest disabled
FAIL
FAIL	github.com/cockroachdb/cockroach/rpc	1.106s
=== RUN   TestAll
I0121 17:30:42.748530 362 rpc/codec/rpc_test.go:48  Arith.Add(1, 2): 3
I0121 17:30:42.749463 362 rpc/codec/rpc_test.go:48  Arith.Add(1, 2): 3
--- PASS: TestAll (0.00s)
PASS
ok  	github.com/cockroachdb/cockroach/rpc/codec	0.010s
?   	github.com/cockroachdb/cockroach/rpc/codec/message	[no test files]
?   	github.com/cockroachdb/cockroach/rpc/codec/wire	[no test files]
=== RUN   TestGetCertificateUser
--- PASS: TestGetCertificateUser (0.00s)

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by tamird**
The first commit unhooks our old RPC-based SQL driver just enough that it no longer depends on cockroach/rpc (and no longer works). Someone should do that work for real, but until then, focus your review on the last commit.

This completely removes the old "cockroach RPC", and replaces it with a
very thin wrapper around gRPC. Notable omissions:
- Heartbeats are no longer used for health checking, and no replacement
  is provided. gRPC has a similar mechanism, but it is not currently
  used.
- gRPC client connections are never closed. This was not exactly
  implemented in the old code, but we probably should implement it so
  that clusters do not attempt to connect to downed nodes indefinitely.
- The local call optimization introduced in 27bbf1c and enabled by
  default in c979503 has been removed.

Fixes #1521.
Closes #1633.
Closes #2642.
Fixes #3942.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4750)

### CODE REVIEW

**Comment by tamird** [comment]
Oh, this also removes the local calls optimization that went in in #4046.

**Comment by tamird** [comment]
Alright, this is green, PTAL. I'm looking at you @petermattis!

**Comment by petermattis** [comment]
Looks good. What has this done to the top-level SQL benchmarks? You should compare against master with `ENABLE_LOCAL_CALL=0`.

---

Reviewed 4 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 3 of 3 files at r5, 86 of 86 files at r6.
Review status: 72 of 90 files reviewed at latest revision, 6 unresolved discussions.

---

*[kv/db.go, line 68 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBouCcNAfCREmLmb86P:-KBouCcOqSbojZviA345:-213035653) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c8116dab7d4aa92bc48c4b4e8a269a39abe11ac/kv/db.go#L68)):*
While this is fresh in your mind, can you expand on how grpc's authentication model does not fit with the current security package design? And maybe pull this out into an issue as well.

---

*[kv/send.go, line 224 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBourToIlPCcyTXZ6Xn:-KBourToIlPCcyTXZ6Xo:-1585243019) ([raw file](https://github.com/cockroachdb/cockroach/blob/56cb56a79da9c11ed538dd799f66872f6d262f9a/kv/send.go#L224)):*
Is there a reason this is being removed? It still seems useful and I don't see why it is incompatible with gRPC.

---

*[kv/send.go, line 242 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBovbEoRCzWgKWqdDSu:-KBovbEoRCzWgKWqdDSv:1492357071) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c8116dab7d4aa92bc48c4b4e8a269a39abe11ac/kv/send.go#L242)):*
We should be passing this as a parameter down from `DistSender`. Add a TODO or file an issue (or both).

---

*[roachpb/api.proto, line 668 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBnyG6kOF-JYzbMHh-L:-KBnyG6kOF-JYzbMHh-M:-1447224118) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c8116dab7d4aa92bc48c4b4e8a269a39abe11ac/roachpb/api.proto#L668)):*
Should comment why we have two identical services.

---

*[server/server.go, line 165 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBox0MyJBSdW9Q5rNO5:-KBox0MzfWTfCYcZwlc0:253610391) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c8116dab7d4aa92bc48c4b4e8a269a39abe11ac/server/server.go#L165)):*
`RegisterServerServer` is an unfortunate name.

---

*[sql/testdata/privileges_table, line 2 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBoxFD4OQ-4okTZj-rk:-KBoxFD5iiYBrJsTNW5V:1265847975) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c8116dab7d4aa92bc48c4b4e8a269a39abe11ac/sql/testdata/privileges_table#L2)):*
I don't feel these changes are adding anything. It's not like we're going to change the value of `security.RootUser` and if we did it would be easy to `s/"root"/"newroot"/g`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-:-KBoyehTfJ2V_WNRjq9A:635453054)*

**Comment by tamird** [comment]
Well, they got quite a bit worse in some cases - see the last commit message.

---

Review status: 65 of 90 files reviewed at latest revision, 6 unresolved discussions.

---

*[kv/db.go, line 68 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBouCcNAfCREmLmb86P:-KBr9buUIuorDe52Omxj:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c8116dab7d4aa92bc48c4b4e8a269a39abe11ac/kv/db.go#L68)):*
Done.

---

*[kv/send.go, line 224 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBourToIlPCcyTXZ6Xn:-KBr9eCRm9YrYcX7D7qS:-1847016477) ([raw file](https://github.com/cockroachdb/cockroach/blob/56cb56a79da9c11ed538dd799f66872f6d262f9a/kv/send.go#L224)):*
It's not incompatible, but we don't have access to the method registration in grpc like we did with this home-grown server. It's certainly possible to add this back per RPC method, but I didn't want to burden this PR with that. Perhaps I should?

---

*[kv/send.go, line 242 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBovbEoRCzWgKWqdDSu:-KBrAKRrhuTJMJiciTkg:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c8116dab7d4aa92bc48c4b4e8a269a39abe11ac/kv/send.go#L242)):*
Done.

---

*[roachpb/api.proto, line 668 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBnyG6kOF-JYzbMHh-L:-KBrAi_Jm5p12crxqhQo:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c8116dab7d4aa92bc48c4b4e8a269a39abe11ac/roachpb/api.proto#L668)):*
Done.

---

*[server/server.go, line 165 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBox0MyJBSdW9Q5rNO5:-KBrAk-j7gP_6jgLO70u:-970613249) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c8116dab7d4aa92bc48c4b4e8a269a39abe11ac/server/server.go#L165)):*
Yep. Open to suggestions.

---

*[sql/testdata/privileges_table, line 2 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBoxFD4OQ-4okTZj-rk:-KBrAmNf4x383zuxVjPy:2081472521) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c8116dab7d4aa92bc48c4b4e8a269a39abe11ac/sql/testdata/privileges_table#L2)):*
I was hunting for a bug in one of the permission tests and found it harder to grep for "literal" than security.FooUser, so I went ahead and made this change. I can back it out if you feel strongly, but I still think it's a net positive.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-:-KBrLtXcRTMiF4ZH4qiN:1687520120)*

**Comment by petermattis** [comment]
That's quite a performance regression. I don't think we can merge this until we figure out what is going on. Just to confirm, you benchmarked master with `ENABLE_LOCAL_CALLS=0`, right? One quick thing to try: set `grpc.EnableTracing = false`.

---

Review status: 65 of 90 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[kv/send.go, line 224 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBourToIlPCcyTXZ6Xn:-KBrUfqa4hj3HMW29aKb:227188411) ([raw file](https://github.com/cockroachdb/cockroach/blob/56cb56a79da9c11ed538dd799f66872f6d262f9a/kv/send.go#L224)):*
I think it is fine to re-add the local-call optimization in a follow-on PR, but it appeared it was being removed for good. Perhaps re-add the variable and a TODO indicating what needs to be done to re-enable.

---

*[roachpb/api.proto, line 673 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBrV29T32bVt4ofOlrL:-KBrV29T32bVt4ofOlrM:-1059454167) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef422b2cd33347f953a13568b3f5463724783de0/roachpb/api.proto#L673)):*
Perhaps rename: `s/Server/External/g`, `s/Node/Internal/g`. That would make the usage clearer as well as get rid of the `ServerServer` oddity. 

---

*[server/server.go, line 165 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBox0MyJBSdW9Q5rNO5:-KBrVB8FQu8V_IRDXYFh:-603549257) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c8116dab7d4aa92bc48c4b4e8a269a39abe11ac/server/server.go#L165)):*
See other comment about the `Server` service.

---

*[sql/testdata/privileges_table, line 2 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBoxFD4OQ-4okTZj-rk:-KBrVERGoWydvj-Vkbu-:-1485267115) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c8116dab7d4aa92bc48c4b4e8a269a39abe11ac/sql/testdata/privileges_table#L2)):*
My opinion is that it isn't worth it, though I'm open to other folks feeling differently. Can you pull out these changes into a separate PR? They aren't related to gRPC AFAICT.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-:-KBrVQsEJwJejfmxJWiG:165044855)*

**Comment by tamird** [comment]
Done; updated the commit message. Things are a bit better, but still not great.

---

Review status: 2 of 90 files reviewed at latest revision, 6 unresolved discussions.

---

*[roachpb/api.proto, line 673 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBrV29T32bVt4ofOlrL:-KBrYIe_2MpE3EqU4umK:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef422b2cd33347f953a13568b3f5463724783de0/roachpb/api.proto#L673)):*
Done.

---

*[sql/testdata/privileges_table, line 2 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBoxFD4OQ-4okTZj-rk:-KBrbUUZzm5IjrR8w0rE:1085483994) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c8116dab7d4aa92bc48c4b4e8a269a39abe11ac/sql/testdata/privileges_table#L2)):*
Will do.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-:-KBrb8RuAJiEq8wJZPei:1083146290)*

**Comment by tschottdorf** [comment]
Reviewed 4 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 2 files at r4, 3 of 3 files at r5, 86 of 86 files at r6, 1 of 1 files at r7, 8 of 8 files at r8, 14 of 14 files at r9, 3 of 3 files at r10, 5 of 5 files at r11, 4 of 4 files at r12, 87 of 87 files at r13, 87 of 87 files at r14.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750)*

**Comment by tamird** [comment]
Review status: 71 of 77 files reviewed at latest revision, 3 unresolved discussions.

---

*[kv/send.go, line 224 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBourToIlPCcyTXZ6Xn:-KBrnhXVKCm0O1kSAWmC:1786437642) ([raw file](https://github.com/cockroachdb/cockroach/blob/56cb56a79da9c11ed538dd799f66872f6d262f9a/kv/send.go#L224)):*
Went ahead and brought this back and posted new benchmarks. Looks like this took up nearly all the slack in the local call case.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750)*

**Comment by petermattis** [comment]
Review status: 71 of 77 files reviewed at latest revision, 3 unresolved discussions.

---

*[kv/send.go, line 224 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBourToIlPCcyTXZ6Xn:-KBrznBXVKfJDqFL4IpN:-1828333827) ([raw file](https://github.com/cockroachdb/cockroach/blob/56cb56a79da9c11ed538dd799f66872f6d262f9a/kv/send.go#L224)):*
Yeah, I would have predicted that, but we still need to figure out how to gain back some of the performance on non-local RPCs. The `Scan1` benchmark is a good one to investigate as it does very little other than RPC work.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750)*

**Comment by tschottdorf** [comment]
Reviewed 11 of 11 files at r15.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: 74 of 78 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[kv/send.go, line 172 \[r16\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBuEr93TJgeJ8W464Wl:-KBuEr93TJgeJ8W464Wm:-1119953809) ([raw file](https://github.com/cockroachdb/cockroach/blob/78cd17f3e1ed394a401a8539734b81f81ef1b289/kv/send.go#L172)):*
Did this `Verify` call move somewhere or was it just removed? (I'm not seeing it but I could be missing something) This looks like the only call to `resp.Verify` so we should either add it back somewhere or remove the methods from the various proto types.

---

*[kv/send.go, line 255 \[r16\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBuFSxSOX1DiXoCfN8h:-KBuFSxTfG_2ffoh6SFo:-778629828) ([raw file](https://github.com/cockroachdb/cockroach/blob/34211f3251298711f5c96c9e8cbc860446cdb593/kv/send.go#L255)):*
Wrap this line at 100 chars

---

*[kv/send_test.go, line 107 \[r16\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBuGGOlanC1vUMtFJsQ:-KBuGGOlanC1vUMtFJsR:1221339474) ([raw file](https://github.com/cockroachdb/cockroach/blob/34211f3251298711f5c96c9e8cbc860446cdb593/kv/send_test.go#L107)):*
Does this mean that these tests will fail if run with local calls disabled?  The point of the opt-out for local calls is so that we can optionally run the tests without them and make sure that we're not relying on in-memory modification of request objects. If the tests don't pass without local calls then we should just get rid of the option.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-:-KBuJD_ObBlyeC3Gr-Nh:676834233)*

**Comment by tamird** [comment]
Review status: 74 of 78 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[kv/send.go, line 172 \[r16\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBuEr93TJgeJ8W464Wl:-KBuLBNdWduhtiimkO3m:-426151036) ([raw file](https://github.com/cockroachdb/cockroach/blob/78cd17f3e1ed394a401a8539734b81f81ef1b289/kv/send.go#L172)):*
This was dead code. `Batch{Request,Response}` do not implement `roachpb.{Request,Response}`, so these type assertions never did anything.

---

*[kv/send.go, line 255 \[r16\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBuFSxSOX1DiXoCfN8h:-KBuKIpoLGXhINKolx9f:1563028894) ([raw file](https://github.com/cockroachdb/cockroach/blob/34211f3251298711f5c96c9e8cbc860446cdb593/kv/send.go#L255)):*
Got it down to 102.

---

*[kv/send_test.go, line 107 \[r16\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBuGGOlanC1vUMtFJsQ:-KBuKMxQxp18H8u5P_VC:491778485) ([raw file](https://github.com/cockroachdb/cockroach/blob/34211f3251298711f5c96c9e8cbc860446cdb593/kv/send_test.go#L107)):*
Why would it mean that? This line is necessary to make tests pass with local calls enabled, but doesn't prevent them from passing with local calls disabled.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750)*

**Comment by bdarnell** [comment]
Review status: 70 of 77 files reviewed at latest revision, 4 unresolved discussions.

---

*[kv/send.go, line 172 \[r16\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBuEr93TJgeJ8W464Wl:-KBuMPeBFKCnk3MmidGr:-53095349) ([raw file](https://github.com/cockroachdb/cockroach/blob/78cd17f3e1ed394a401a8539734b81f81ef1b289/kv/send.go#L172)):*
OK, filed #4799 to hook these back up or remove them.

---

*[kv/send_test.go, line 107 \[r16\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBuGGOlanC1vUMtFJsQ:-KBuMSpHVmwLDyKkCvHs:679457188) ([raw file](https://github.com/cockroachdb/cockroach/blob/34211f3251298711f5c96c9e8cbc860446cdb593/kv/send_test.go#L107)):*
My first sentence was a sincere question. As long as the tests pass with local calls disabled I'm happy; I just wasn't sure whether that was the case or not.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750)*

**Comment by tamird** [comment]
Review status: 70 of 77 files reviewed at latest revision, 3 unresolved discussions.

---

*[kv/send_test.go, line 107 \[r16\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KBuGGOlanC1vUMtFJsQ:-KBuMpwMUW5eff0pU811:110210207) ([raw file](https://github.com/cockroachdb/cockroach/blob/34211f3251298711f5c96c9e8cbc860446cdb593/kv/send_test.go#L107)):*
Ah, yes, I just checked: the tests pass with or without local calls.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750)*

**Comment by petermattis** [comment]
Any progress on the perf issue?

**Comment by tamird** [comment]
Some: https://github.com/grpc/grpc-go/pulls/tamird

The maintainers have other plans, it seems.

**Comment by tamird** [comment]
OK, latest commit implements cmux hackery that makes the performance hit much less painful. PTAL

**Comment by petermattis** [comment]
LGTM

---

Review status: 49 of 75 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-:-KCQnT6TesvU-2fVXxJQ:676834233)*

**Comment by bdarnell** [comment]
Review status: 49 of 75 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/server.go, line 304 \[r19\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KCRf1k05olOKPW3gA4c:-KCRf1k05olOKPW3gA4d:2079524886) ([raw file](https://github.com/cockroachdb/cockroach/blob/70df7525a7d9b1c6ab706c87f504a501d1a00597/server/server.go#L304)):*
Why did these move out of the stopper?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750)*

**Comment by tamird** [comment]
Review status: 49 of 75 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/server.go, line 304 \[r19\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750#-KCRf1k05olOKPW3gA4c:-KCRgItsG0iYLsp76Xg5:-1639900115) ([raw file](https://github.com/cockroachdb/cockroach/blob/70df7525a7d9b1c6ab706c87f504a501d1a00597/server/server.go#L304)):*
Good question - they refused to shut down otherwise. Seems we've had at least one related test failure. I'm looking into this now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4750)*

**Pull request merged**
