### PR TITLE
[DO NOT MERGE] storage: check destroy status inside requestCanProceed

### LINKED ISSUE #32268: perf: push Replica destroy checks into requestCanProceed
`Replica.requestCanProceed` grabs a read lock and verifies that a request is permissible to run on the Replica's current state. Separately, we grab a read lock and check the `destroyStatus` of the Replica in similar code paths. We should push the `destroyStatus` checks into `requestCanProceed` to avoid repeat read locking. It also seems appropriate for the destroy check to live in `requestCanProceed`.

This was observed in c737c973c84bdd380b112c6491ab7f4118b5ebac. We can address the two TODOs dropped in there.

### PR DESCRIPTION
**Pull request by ajwerner**
Avoids additional locking in replica request processing by checking replica
status in Replica.requestCanProceed.

Fixes #32268

Release note (performance improvement): elide locking for checking replica status when determining request status.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Part of #32268 was verifying that this change was safe and the desired behavior for all callers of `requestCanProceed` (although that's not clear from the issue description alone!). Did you take a look at whether this all checks out?

**Comment by ajwerner** [comment]
It needs more work. I just did a cursory read through and then tried the obvious fix, doesn't seem like it was enough. I'll dig more into it soon.

**Review by nvb — COMMENTED** [review]
I got around to giving this another look. Here's what I'd suggest:
1. make a clear contract in `destroyStatus` that `err == nil` when `reason == destroyReasonAlive` and `err != nil` when `reason != destroyReasonAlive`. I just audited every call to `destroyStatus.Set` and this is the case, but it would be nice to have that guarantee. We could change the `DestroyReason` enum to an ADT-like interface for a static guarantee, but comments or assertions are probably fine too. Once we do that, `IsAlive` and `err == nil` will be synonymous.
2. next, I'd make `requestCanProceed` simply grab the `destroyErr` under lock.
3. we can then check if this is nil after releasing the lock and return if not.
4. after that, we'll need to either ensure that all callers of `processRaftCommand` want the destroy check or allow certain callers to skip it. The two places where we would be introducing it would be in `executeAdminBatch` and `processRaftCommand`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32314#-:-LUMAPTP4drbbmlfaaCO:b8jrbn1)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
Superseded by cb61cb3.

**Pull request closed without merging**
