### PR TITLE
[cli] estimate-gc with custom TTL

### PR DESCRIPTION
**Pull request by neeral**
Release note:
`cockroach debug estimate-gc` now allows user to specify TTL period,
with a default of 24 hours.

### CODE REVIEW

**Comment by neeral** [comment]
See https://github.com/cockroachlabs/rubrik/issues/25

**Review by nvb — CHANGES_REQUESTED** [review]
Thanks @neeral!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31402#-:-LOtPJ4k3FBfpj2mwKL8:bdrf2jo)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/debug.go, line 460 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31402#-LOtOgri13gmMzFgbZ0W:-LOtOgri13gmMzFgbZ0X:boqa7kz) ([raw file](https://github.com/cockroachdb/cockroach/blob/762e15f44232a7fcf4bafc834404120a445bcc0e/pkg/cli/debug.go#L460)):*
> ```Go
> ranges individually.
> 
> Uses a hard-coded GC policy, with a default 24 hour TTL, for old versions.
> ```

This is no longer true, right? It now only uses the default TTL is one isn't provided.
___
*[pkg/cli/debug.go, line 471 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31402#-LOtPEwd-_3rtzpAJuTm:-LOtPEwd-_3rtzpAJuTn:b-2ywxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/762e15f44232a7fcf4bafc834404120a445bcc0e/pkg/cli/debug.go#L471)):*
> ```Go
> 
> 	var rangeID roachpb.RangeID
> 	var gcTtlInSeconds int32 = 24 * 60 * 60 /* 1 day */
> ```

nit: `(24 * time.Hour).Seconds()` reads a little better.
___
*[pkg/cli/debug.go, line 476 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31402#-LOtOy4B3mEP5X9nnE7x:-LOtOy4B3mEP5X9nnE7y:b-g91kh4) ([raw file](https://github.com/cockroachdb/cockroach/blob/762e15f44232a7fcf4bafc834404120a445bcc0e/pkg/cli/debug.go#L476)):*
> ```Go
> 		var err error
> 		if rangeID, err = parseRangeID(args[1]); err != nil {
> 			return err
> ```

Wrap these errors to give them some context.

**Review by neeral — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31402)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/debug.go, line 460 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31402#-LOtOgri13gmMzFgbZ0W:-LOux5zZ5kta5wymIM_q:b3mz82y) ([raw file](https://github.com/cockroachdb/cockroach/blob/762e15f44232a7fcf4bafc834404120a445bcc0e/pkg/cli/debug.go#L460)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is no longer true, right? It now only uses the default TTL is one isn't provided.
</blockquote></details>

A GC policy is defined by zones. We still have a hard-coded policy of a single zone. What's changed is the TTL for that zone.
___
*[pkg/cli/debug.go, line 476 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31402#-LOtOy4B3mEP5X9nnE7x:-LOzdfvsEWTeioHlnpF8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/762e15f44232a7fcf4bafc834404120a445bcc0e/pkg/cli/debug.go#L476)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Wrap these errors to give them some context.
</blockquote></details>

Done.

**Review by nvb — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31402)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/debug.go, line 460 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31402#-LOtOgri13gmMzFgbZ0W:-LP2Pz3eCwb_bMWuZLzW:bv3r5jk) ([raw file](https://github.com/cockroachdb/cockroach/blob/762e15f44232a7fcf4bafc834404120a445bcc0e/pkg/cli/debug.go#L460)):*
<details><summary><i>Previously, neeral (Neeral Dodhia) wrote…</i></summary><blockquote>

A GC policy is defined by zones. We still have a hard-coded policy of a single zone. What's changed is the TTL for that zone.
</blockquote></details>

My issue is with the term "hard-coded". I'd say "configurable".
___
*[pkg/cli/debug.go, line 479 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31402#-LP2PqqS455q8Jo4_WEO:-LP2PqqS455q8Jo4_WEP:b-nnev4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/e505f0d07d5062b9ef893784f2dcdc84381f04f6/pkg/cli/debug.go#L479)):*
> ```Go
> 		}
> 		var gcTTLInSecondRangeID roachpb.RangeID
> 		if gcTTLInSecondRangeID, err = parseRangeID(args[2]); err != nil {
> ```

Why are we using `parseRangeID` for this? Let's just use `strconv.ParseInt` directly.

**Review by neeral — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31402)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/debug.go, line 460 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31402#-LOtOgri13gmMzFgbZ0W:-LP3Vv_cAgZagOQDzDQG:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/762e15f44232a7fcf4bafc834404120a445bcc0e/pkg/cli/debug.go#L460)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

My issue is with the term "hard-coded". I'd say "configurable".
</blockquote></details>

Fixed.
___
*[pkg/cli/debug.go, line 479 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31402#-LP2PqqS455q8Jo4_WEO:-LP3Vtd17dhFZ_gVmVTy:by4jdqy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e505f0d07d5062b9ef893784f2dcdc84381f04f6/pkg/cli/debug.go#L479)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why are we using `parseRangeID` for this? Let's just use `strconv.ParseInt` directly.
</blockquote></details>

I wanted to keep the logic for checking errors from `strconv.ParseInt` and whether int is positive. I've put this into a helper function.

**Review by nvb — COMMENTED** [review]
:lgtm: thanks @neeral!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31402#-:-LP3an7WD8jvTTRe9AJc:bc1klbl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by nvb — APPROVED** [review]

**Pull request merged**
