### PR TITLE
clusterversion: bump min supported version to 23.1

### PR DESCRIPTION
**Pull request by RaduBerinde**
This commit changes the minimum supported version to 23.1. It is
intended to be backported to release-23.2.

Tests that had to be modified mostly fall in one of two categories:
 - tests that verify a release-specific behavior involving 22.2 or
   in-development versions of 23.1; these tests were deleted.
 - tests that verify general version handling logic but used specific
   versions; I tried to make these use the min supported version or a
   new `VCurrent_Start` constant.

The logic tests required a bunch of work because we were missing a
`local-mixed-23.1` config, which should have been added early in the
23.2 cycle. Without this config, all test directives related to 23.2
features were conditioned on `local-mixed-22.2-23.1` (i.e. lumped in
with 23.1 features). I added the new config and let the test failures
guide me; most of the cases that needed to be conditioned on
`local-mixed-23.1` where around the bigger 23.2 features (isolation
levels, procedures). In subsequent release cycles, we will create the
new config as soon as possible.

This commit does not remove the obsolete in-development 23.1 version
keys and related code; that will be done separately.

Informs: #111760
Epic: REL-506
Release note: None

### CODE REVIEW

**Review by rail — APPROVED** [review]
Thank you for this HUGE PR!

> Reviewed 130 of 130 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112122#-:-NgZtx5R3qRX8-zqWRl8:b-uwozs7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @celiala, @DarrylWong, @dt, @herkolategan, @jbowens, and @mgartner)

**Review by jbowens — COMMENTED** [review]
I only looked at the pkg/storage changes, but they look good to me.

> Reviewed 3 of 130 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112122#-:-Ng_A24_25O8UGrA1gaD:buw24b3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @celiala, @DarrylWong, @dt, @herkolategan, and @mgartner)

**Review by yuzefovich — APPROVED** [review]
Thanks! :lgtm:

> Reviewed 130 of 130 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112122#-:-Ng_BNID2pYQsNWjZLOI:b-ftzx47)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @celiala, @DarrylWong, @dt, @herkolategan, @mgartner, and @RaduBerinde)

___
*[`pkg/sql/logictest/testdata/logic_test/drop_owned_by` line 648 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112122#-Ng_8knK6kzPyzEbgzPS:-Ng_8knK6kzPyzEbgzPT:b-tv93pz) ([raw file](https://github.com/cockroachdb/cockroach/blob/abb6a593669c00b708afbbfa3c286bfab81d18ec/pkg/sql/logictest/testdata/logic_test/drop_owned_by#L648)):*
> ```
> ALTER FUNCTION f_drop_udf OWNER TO u_drop_udf;
> 
> # TODO(chengxiong): DROP function was only enabled in 23.1. This skip can be
> ```

nit: a couple of TODOs should now be removed.
___
*[`pkg/sql/logictest/testdata/logic_test/gc_job_mixed` line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112122#-Ng_9-wn-w_7J8RK8mMM:-Ng_9-wn-w_7J8RK8mMN:b-fgldjh) ([raw file](https://github.com/cockroachdb/cockroach/blob/abb6a593669c00b708afbbfa3c286bfab81d18ec/pkg/sql/logictest/testdata/logic_test/gc_job_mixed#L23)):*
> ```
> DROP DATABASE db
> 
> # GC jobs in a non-mixed-version cluster, 23.1+ style.
> ```

nit: perhaps remove this comment too?

**Review by rafiss — APPROVED** [review]

**Review by celiala — APPROVED** [review]
Thank you! Reviewed at a pretty-high level - changes LGTM

> Reviewed 130 of 130 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112122#-:-Ng_FO0I08W1LhZz5mp2:b-jlbnmb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @dt, @herkolategan, @mgartner, and @RaduBerinde)

___
*[`pkg/clusterversion/cockroach_versions.go` line 536 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112122#-Ng_BmIA8UMeOS4Zq6sk:-Ng_BmIA8UMeOS4Zq6sl:bcjfssn) ([raw file](https://github.com/cockroachdb/cockroach/blob/abb6a593669c00b708afbbfa3c286bfab81d18ec/pkg/clusterversion/cockroach_versions.go#L536)):*
> ```Go
> // version of the release in development). Tests should use this constant so
> // they don't need to be updated when the versions change.
> const VCurrent_Start = V23_2Start
> ```

+1 to the practice of using `VCurrent_Start` as an alias for the last Start version key!

I'm wondering how best to communicate this out? 
(i.e. will the team know to use `VCurrent_Start`, or will they continue using `V23_2Start` because they don't know about this..).
___
*[`pkg/sql/tenant_creation.go` line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112122#-Ng_CV3w6kElvL4KlJl8:-Ng_CV3w6kElvL4KlJl9:b-k4ugqp) ([raw file](https://github.com/cockroachdb/cockroach/blob/abb6a593669c00b708afbbfa3c286bfab81d18ec/pkg/sql/tenant_creation.go#L50)):*
> ```Go
> 
> const (
> 	tenantCreationMinSupportedVersionKey = clusterversion.BinaryMinSupportedVersionKey
> ```

(I don't know enough about how `tenantCreationMinSupportedVersionKey` differs from `BinaryMinSupportedVersionKey`)

but I'm guessing someone on the multi-tenant team has / can weigh-in on this?
___
*[`pkg/sql/logictest/logictestbase/logictestbase.go` line 270 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112122#-Ng_DAMDBC7rrxIBWCy9:-Ng_DAME7M0RqE2fVOhP:b-c6zrg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/abb6a593669c00b708afbbfa3c286bfab81d18ec/pkg/sql/logictest/logictestbase/logictestbase.go#L270)):*
> ```Go
> // See DefaultConfigNames for the list of default configs.
> //
> // Note: If you add a new config, you should run `./dev gen testlogic`.
> ```

(thank you for adding this note!)x
___
*[`pkg/ccl/serverccl/server_startup_guardrails_test.go` line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112122#-Ng_EmwA5p3B9jwBQjUj:-Ng_EmwA5p3B9jwBQjUk:b5k9ggp) ([raw file](https://github.com/cockroachdb/cockroach/blob/abb6a593669c00b708afbbfa3c286bfab81d18ec/pkg/ccl/serverccl/server_startup_guardrails_test.go#L65)):*
> ```Go
> 		// version is not too low for the tenant logical version.
> 		{
> 			storageBinaryVersion:             logicalVersion,
> ```

nice! thank you!

**Review by RaduBerinde — COMMENTED** [review]
TFTR!!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112122#-:-Ng_jK-f3m3WUQ38dApu:bz5m8k5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @celiala, @DarrylWong, @dt, @herkolategan, and @mgartner)

___
*[`pkg/clusterversion/cockroach_versions.go` line 536 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112122#-Ng_BmIA8UMeOS4Zq6sk:-Ng_jLA2DkGif_FulwuJ:b-scu4ub) ([raw file](https://github.com/cockroachdb/cockroach/blob/abb6a593669c00b708afbbfa3c286bfab81d18ec/pkg/clusterversion/cockroach_versions.go#L536)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

+1 to the practice of using `VCurrent_Start` as an alias for the last Start version key!

I'm wondering how best to communicate this out? 
(i.e. will the team know to use `VCurrent_Start`, or will they continue using `V23_2Start` because they don't know about this..).
</blockquote></details>

I plan to consider this when doing more work on this stuff on master - one option is to unexport `V23_2Start` and similar if they have no uses that can't be better served by `VCurrent_Start`; another is a linter, or just a comment above every `Start` key explaining `VCurrent` should be preferred.
___
*[`pkg/sql/tenant_creation.go` line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112122#-Ng_CV3w6kElvL4KlJl8:-Ng_k3nG143oNRHSu-Z7:b-3h9w3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/abb6a593669c00b708afbbfa3c286bfab81d18ec/pkg/sql/tenant_creation.go#L50)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

(I don't know enough about how `tenantCreationMinSupportedVersionKey` differs from `BinaryMinSupportedVersionKey`)

but I'm guessing someone on the multi-tenant team has / can weigh-in on this?
</blockquote></details>

I had asked on Slack, this is the discussion https://cockroachlabs.slack.com/archives/C02J7BTSRK2/p1696979372260889

**Pull request merged**
