### PR TITLE
storage: fix compactor-disabled test

### LINKED ISSUE #25459: storage/compactor: TestCompactorDisabled failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/835cc098da0698ea9a12271d4e2998fad69a8e4a

Parameters:
```
TAGS=
GOFLAGS=
```

Stress build found a failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=656006&tab=buildLog

```
	compactor_test.go:690: condition failed to evaluate within 45s: expected skipped bytes 805306365; got 1342177275
		goroutine 86 [running]:
		runtime/debug.Stack(0xa7a358200, 0xc4204fef78, 0x15bebe0)
			/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
		github.com/cockroachdb/cockroach/pkg/testutils.SucceedsSoon(0x15d7d80, 0xc4203700f0, 0xc4204fef78)
			/go/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:38 +0x7d
		github.com/cockroachdb/cockroach/pkg/storage/compactor.TestCompactorDisabled(0xc4203700f0)
			/go/src/github.com/cockroachdb/cockroach/pkg/storage/compactor/compactor_test.go:690 +0x1b7
		testing.tRunner(0xc4203700f0, 0x1523bc8)
			/usr/local/go/src/testing/testing.go:777 +0xd0
		created by testing.(*T).Run
			/usr/local/go/src/testing/testing.go:824 +0x2e0


ERROR: exit status 1

3555 runs completed, 1 failures, over 1m29s
context canceled
Makefile:869: recipe for target 'stress' failed
make: *** [stress] Error 1
```

### PR DESCRIPTION
**Pull request by tbg**
The test was queuing suggestions worthy of a compaction before disabling
the compactor.

Fixes #25459.

Release note: None

### CODE REVIEW

**Comment by tschottdorf** [comment]
Still flaky though less so.. let me take another look.

**Comment by tschottdorf** [comment]
PTAL

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25463#-:-LCU_n1k529W6JXgAcjz:bnfp4nl)*

**Comment by tschottdorf** [comment]
TFTR!

bors r=bdarnell

**Pull request merged**
