### PR TITLE
sql: correct the usage of UDF terms "arguments" and "parameters"

### PR DESCRIPTION
**Pull request by mgartner**
#### sql: correct the usage of UDF terms "arguments" and "parameters"

A _parameter_ is a variable in a function definition. An _argument_ is
an expression passed to a function when the function is invoked.
UDF-related code was not using this nomenclature correctly, creating
confusion. This commit fixes up our usage of these terms within SQL
optimization and execution. I know this is a pedantic change, but it is
motivated by my struggles in writing clear code and comments with the
previously overloading of the term _argument_.

Epic: CRDB-20370

Release note: None

#### sql: correct the usage of terms "arguments" and "parameters" in descriptors

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
The first commit is mostly SQL Queries related code and the second commit is mostly SQL Schema related code plus the parser changes.

**Review by chengxiong-ruan — APPROVED** [review]
LGTM. Thanks for doing this. This is very important!

**Review by DrewKimball — APPROVED** [review]
:lgtm: Left a bunch of minor comments, but feel free to pick and choose whichever ones you think matter for clarity.

> Reviewed 11 of 11 files at r1, 21 of 21 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-:-NICWwXPBisyJ3dOEWsN:btrt1f1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/create_function.go` line 231 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICULZ45OhWBr6r2KR7:-NICULZ45OhWBr6r2KR8:bberrso) ([raw file](https://github.com/cockroachdb/cockroach/blob/898eb4bfb83efa314dd551f6bc1fdb858789c1c9/pkg/sql/create_function.go#L231)):*
> ```Go
> ) (fnDesc *funcdesc.Mutable, isNew bool, err error) {
> 	// Resolve argument types.
> 	argTypes := make([]*types.T, len(n.cf.Params))
> ```

`argTypes`->`paramTypes`?
___
*[`pkg/sql/create_function.go` line 244 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICUUfZ5gtsW3ecdweI:-NICUUfZ5gtsW3ecdweJ:b-lqf0mz) ([raw file](https://github.com/cockroachdb/cockroach/blob/898eb4bfb83efa314dd551f6bc1fdb858789c1c9/pkg/sql/create_function.go#L244)):*
> ```Go
> 			argNameSeen[param.Name] = struct{}{}
> 		}
> 		pbArg, err := makeFunctionArg(params.ctx, param, params.p)
> ```

`pbArg`->`pbParam`

`makeFunctionArg` is only used here, so it could be renamed too.
___
*[`pkg/sql/create_function.go` line 454 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICVNYlD8Ngd1H23xmX:-NICVNYm-xcfVgVQThDb:b-wyc93z) ([raw file](https://github.com/cockroachdb/cockroach/blob/898eb4bfb83efa314dd551f6bc1fdb858789c1c9/pkg/sql/create_function.go#L454)):*
> ```Go
> 
> func makeFunctionArg(
> 	ctx context.Context, arg tree.FuncParam, typeResolver tree.TypeReferenceResolver,
> ```

[nit] could rename `arg` to `param`
___
*[`pkg/sql/create_function.go` line 460 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICUm7p76ybuk5ikDYc:-NICUm7p76ybuk5ikDYd:b-bo8jl3) ([raw file](https://github.com/cockroachdb/cockroach/blob/898eb4bfb83efa314dd551f6bc1fdb858789c1c9/pkg/sql/create_function.go#L460)):*
> ```Go
> 	}
> 	var err error
> 	pbParam.Class, err = funcdesc.ArgClassToProto(arg.Class)
> ```

`ArgClassToProto` is only used here, could rename it.
___
*[`pkg/sql/pg_catalog.go` line 2424 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICV-2oE3dJtQp4b4FG:-NICV-2oE3dJtQp4b4FH:b-4xxuau) ([raw file](https://github.com/cockroachdb/cockroach/blob/898eb4bfb83efa314dd551f6bc1fdb858789c1c9/pkg/sql/pg_catalog.go#L2424)):*
> ```Go
> 						isStrict := fnDesc.GetNullInputBehavior() != catpb.Function_CALLED_ON_NULL_INPUT
> 						argTypes := tree.NewDArray(types.Oid)
> 						argModes := tree.NewDArray(types.String)
> ```

A couple more places here where we're using arg instead of param:
`argTypes`->`paramTypes`
`argModes`->`paramModes`
`argNames`->`paramNames`
`argNamesArray`->`paramNamesArray`
`foundAnyArgNames`->`foundAnyParamNames`
___
*[`pkg/sql/catalog/funcdesc/func_desc.go` line 555 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICVc9wBMHJdm6C-hsD:-NICVc9wBMHJdm6C-hsE:bca22s3) ([raw file](https://github.com/cockroachdb/cockroach/blob/898eb4bfb83efa314dd551f6bc1fdb858789c1c9/pkg/sql/catalog/funcdesc/func_desc.go#L555)):*
> ```Go
> 	}
> 
> 	argTypes := make(tree.ArgTypes, 0, len(desc.Params))
> ```

`argTypes`->`paramTypes`
We could even change `tree.ArgTypes` since it only seems to be used here and one other place for functions, though that might be too far.
___
*[`pkg/sql/catalog/funcdesc/func_desc.go` line 676 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICW3Q_B_eI7o379iC1:-NICW3Q_B_eI7o379iC2:bc0i1rk) ([raw file](https://github.com/cockroachdb/cockroach/blob/898eb4bfb83efa314dd551f6bc1fdb858789c1c9/pkg/sql/catalog/funcdesc/func_desc.go#L676)):*
> ```Go
> }
> 
> func toTreeNodeArgClass(class catpb.Function_Param_Class) tree.FuncParamClass {
> ```

This is only used in one place, so it's name can be easily changed.
___
*[`pkg/sql/delegate/show_grants.go` line 261 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICWJpP5cXavZVy2lok:-NICWJpP5cXavZVy2lol:b-gl85sq) ([raw file](https://github.com/cockroachdb/cockroach/blob/898eb4bfb83efa314dd551f6bc1fdb858789c1c9/pkg/sql/delegate/show_grants.go#L261)):*
> ```Go
> 				return nil, err
> 			}
> 			argTypes, err := fn.ParamTypes(d.ctx, d.catalog)
> ```

[nit] `argTypes` -> `paramTypes`
___
*[`pkg/sql/opt/exec/execbuilder/scalar.go` line 677 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICRemu2GbURjGqennL:-NICRemu2GbURjGqennM:b4oh5yl) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e2c4344415f8a44e1f67ea19c994affd426f833/pkg/sql/opt/exec/execbuilder/scalar.go#L677)):*
> ```Go
> 	// represents. If the column does not represent an argument, then ok=false
> 	// is returned.
> 	argOrd := func(col opt.ColumnID) (ord int, ok bool) {
> ```

Does it make sense to say that the column ID represents an argument, rather than a parameter?
___
*[`pkg/sql/opt/exec/execbuilder/scalar.go` line 703 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICRmMjCXjgtzfCgv2y:-NICRmMjCXjgtzfCgv2z:b4jy4t3) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e2c4344415f8a44e1f67ea19c994affd426f833/pkg/sql/opt/exec/execbuilder/scalar.go#L703)):*
> ```Go
> 		stmt := udf.Body[stmtIdx]
> 
> 		// Copy the expression into a new memo. Replace argument references with
> ```

Should it be 'parameter references' rather than 'argument references'? The idea is to replace parameter references within the function body with resolved arguments, right?
___
*[`pkg/sql/opt/optbuilder/scalar.go` line 632 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICSvyY7iZVYatlNPJG:-NICSvyY7iZVYatlNPJH:br74585) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e2c4344415f8a44e1f67ea19c994affd426f833/pkg/sql/opt/optbuilder/scalar.go#L632)):*
> ```Go
> 	// start with an empty scope because a statement in the function body cannot
> 	// refer to anything from the outer expression. If there are function
> 	// arguments, we add them as columns to the scope so that references to them
> ```

[nit] 'function arguments' -> 'function parameters'
___
*[`pkg/sql/opt/optbuilder/scope_column.go` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICTRLQ7lFGRVs3Yng1:-NICTRLQ7lFGRVs3Yng2:b-1jqf3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e2c4344415f8a44e1f67ea19c994affd426f833/pkg/sql/opt/optbuilder/scope_column.go#L122)):*
> ```Go
> const maxFuncParams = 100
> 
> // funcParamOrd is a 1-based ordinal of a function parameters.
> ```

[nit] `parameters`->`parameter`
___
*[`pkg/sql/opt/optbuilder/scope_column.go` line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICTeR6-hhhmdNEHI4z:-NICTeR6-hhhmdNEHI5-:bgu4oxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e2c4344415f8a44e1f67ea19c994affd426f833/pkg/sql/opt/optbuilder/scope_column.go#L138)):*
> ```Go
> }
> 
> // funcParamReferencedBy returns true if the scopeColumn is a function argument
> ```

`argument`->`parameter`
___
*[`pkg/sql/opt/testutils/testcat/function.go` line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICWfou04DZDwimplCt:-NICWfou04DZDwimplCu:b-hyndjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/898eb4bfb83efa314dd551f6bc1fdb858789c1c9/pkg/sql/opt/testutils/testcat/function.go#L72)):*
> ```Go
> 
> 	// Resolve the parameter names and types.
> 	argTypes := make(tree.ArgTypes, len(c.Params))
> ```

`argTypes`->`paramTypes`

**Review by mgartner — COMMENTED** [review]
Thanks for the thorough review! I made a bunch of changes, so please take another look. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-:-NIDAzsi2ViaJgSzlF6F:bbmlk9h)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @benbardin, @DrewKimball, and @HonoreDB)

___
*[`pkg/sql/create_function.go` line 231 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICULZ45OhWBr6r2KR7:-NIDBaPnBaj88QpAGidX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/898eb4bfb83efa314dd551f6bc1fdb858789c1c9/pkg/sql/create_function.go#L231)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

`argTypes`->`paramTypes`?
</blockquote></details>

Done.
___
*[`pkg/sql/create_function.go` line 244 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICUUfZ5gtsW3ecdweI:-NIDBaBb1i1D1kx01xey:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/898eb4bfb83efa314dd551f6bc1fdb858789c1c9/pkg/sql/create_function.go#L244)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

`pbArg`->`pbParam`

`makeFunctionArg` is only used here, so it could be renamed too.
</blockquote></details>

Done.
___
*[`pkg/sql/create_function.go` line 454 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICVNYlD8Ngd1H23xmX:-NIDBd9HB0lepXy0Z8MP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/898eb4bfb83efa314dd551f6bc1fdb858789c1c9/pkg/sql/create_function.go#L454)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] could rename `arg` to `param`
</blockquote></details>

Done.
___
*[`pkg/sql/create_function.go` line 460 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICUm7p76ybuk5ikDYc:-NIDBkFDBL6mIvFTMTnO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/898eb4bfb83efa314dd551f6bc1fdb858789c1c9/pkg/sql/create_function.go#L460)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

`ArgClassToProto` is only used here, could rename it.
</blockquote></details>

Done.
___
*[`pkg/sql/pg_catalog.go` line 2424 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICV-2oE3dJtQp4b4FG:-NIDBseT1gHZsszDb3sb:b83p3ep) ([raw file](https://github.com/cockroachdb/cockroach/blob/898eb4bfb83efa314dd551f6bc1fdb858789c1c9/pkg/sql/pg_catalog.go#L2424)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

A couple more places here where we're using arg instead of param:
`argTypes`->`paramTypes`
`argModes`->`paramModes`
`argNames`->`paramNames`
`argNamesArray`->`paramNamesArray`
`foundAnyArgNames`->`foundAnyParamNames`
</blockquote></details>

I'm inclined to keep these as-is because they map to similarly named columns below, like `proargtypes` and `proargmodes`. It's unfortunate that PG isn't super consistent with the terms "arguments" and "parameters" - they'll likely always be some cases where we are also inconsistent to match PG.
___
*[`pkg/sql/catalog/funcdesc/func_desc.go` line 555 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICVc9wBMHJdm6C-hsD:-NID84KE9O19k-KbqZQV:b-8xbfll) ([raw file](https://github.com/cockroachdb/cockroach/blob/898eb4bfb83efa314dd551f6bc1fdb858789c1c9/pkg/sql/catalog/funcdesc/func_desc.go#L555)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

`argTypes`->`paramTypes`
We could even change `tree.ArgTypes` since it only seems to be used here and one other place for functions, though that might be too far.
</blockquote></details>

`tree.ArgTypes` was the main reason I left a lot of the "args" that you pointed out. I've updated the second commit which renames `tree.ArgType[s]` to `tree.ParamType[s]` and addresses your comments.
___
*[`pkg/sql/catalog/funcdesc/func_desc.go` line 676 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICW3Q_B_eI7o379iC1:-NID8NRv8IUkvvvr-Sgl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/898eb4bfb83efa314dd551f6bc1fdb858789c1c9/pkg/sql/catalog/funcdesc/func_desc.go#L676)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

This is only used in one place, so it's name can be easily changed.
</blockquote></details>

Done.
___
*[`pkg/sql/delegate/show_grants.go` line 261 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICWJpP5cXavZVy2lok:-NID8TOcAbVMXMGCFuey:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/898eb4bfb83efa314dd551f6bc1fdb858789c1c9/pkg/sql/delegate/show_grants.go#L261)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] `argTypes` -> `paramTypes`
</blockquote></details>

Done.
___
*[`pkg/sql/opt/exec/execbuilder/scalar.go` line 677 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICRemu2GbURjGqennL:-NIDAL992dBsQaQPkZoZ:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e2c4344415f8a44e1f67ea19c994affd426f833/pkg/sql/opt/exec/execbuilder/scalar.go#L677)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Does it make sense to say that the column ID represents an argument, rather than a parameter?
</blockquote></details>

Fixed.
___
*[`pkg/sql/opt/exec/execbuilder/scalar.go` line 703 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICRmMjCXjgtzfCgv2y:-NIDAUmf7LmrzMpXuTrJ:bidyb93) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e2c4344415f8a44e1f67ea19c994affd426f833/pkg/sql/opt/exec/execbuilder/scalar.go#L703)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Should it be 'parameter references' rather than 'argument references'? The idea is to replace parameter references within the function body with resolved arguments, right?
</blockquote></details>

Yes good catch! Done.
___
*[`pkg/sql/opt/optbuilder/scalar.go` line 632 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICSvyY7iZVYatlNPJG:-NIDAbgD0XvlTM75JneB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e2c4344415f8a44e1f67ea19c994affd426f833/pkg/sql/opt/optbuilder/scalar.go#L632)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] 'function arguments' -> 'function parameters'
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/scope_column.go` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICTRLQ7lFGRVs3Yng1:-NIDAprlD7RleYgMsjoI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e2c4344415f8a44e1f67ea19c994affd426f833/pkg/sql/opt/optbuilder/scope_column.go#L122)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] `parameters`->`parameter`
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/scope_column.go` line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICTeR6-hhhmdNEHI4z:-NIDAsuH2wYd59lEy8Gi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e2c4344415f8a44e1f67ea19c994affd426f833/pkg/sql/opt/optbuilder/scope_column.go#L138)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

`argument`->`parameter`
</blockquote></details>

Done.
___
*[`pkg/sql/opt/testutils/testcat/function.go` line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-NICWfou04DZDwimplCt:-NIDAxP7AM0jj5HVM8YU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/898eb4bfb83efa314dd551f6bc1fdb858789c1c9/pkg/sql/opt/testutils/testcat/function.go#L72)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

`argTypes`->`paramTypes`
</blockquote></details>

Done.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Looks great! Thanks for taking this on!

> Reviewed 47 of 47 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92758#-:-NIEigEhB7Tgvh-AkAO1:bofp7b3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @benbardin and @HonoreDB)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
