### PR TITLE
colexecdisk: make sure to release resources in all cases

### LINKED ISSUE #81413: sql/colcontainer: TestExternalDistinct leaks Queues, file descriptors
In #81389, I originally moved where Pebble's disk-health checking is layered onto the filesystem. Disk-health checking monitors for excessively slow writes, crashing the process if writes appear to be stalled in the kernel. The changes in #81389 caused disk-health checking to be used in `TestExternalDistinct`. `TestExternalDistinct` began to fail with leaked goroutines in the disk-health checking. I dug into it a bit, and traced it to a `diskQueue` that is never `Close`d, causing its `writeFile` to never be closed.

For now I should be able to refactor #81389 to continue omitting disk-health checking in this code path and unblock the vendor bump, so this isn't a blocker for me.

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, it was possible to not release some resources when external
distinct or external hash aggregator short circuit their execution
(either because of an error or because of the LIMIT on the query) in
some cases (namely, when a sort is planned on top of the external
operation to restore the desired ordering). This was the case because
the hash-based partitioner (which abstracts away the disk-backed
algorithm) wasn't added to `OpWithMetaInfo.ToClose` slice since there is
a sort on top of it nor was it closed by that sort.

Here is an example diagram for all the infra that is set up for the
disk-backed distinct when ordering needs to be maintained:
```
         diskSpillerBase (disk-backed distinct)
           |                      |
UnorderedDistinct     diskSpillerBase [1] (disk-backed sort)
                      |              |                  |
                in-mem sorter   external sorter   hash-based partitioner [2]
```
In this diagram, `hash-based partitioner [2]` is the external distinct
that is the input to the `diskSpillerBase [1]`. In the happy path (when
`[2]` is exhausted), it is `Close`d automatically. However, if its
execution is short-circuited, `[2]` will never be closed because:
- due to the way the infra was created, it was never added to the
`ToClose` slice (so it will not be closed on the flow cleanup)
- `diskSpillerBase [1]` doesn't close its inputs
- `external sorter` nor the in-memory sorter end up closing `[2]` either
because there are other utility operators that don't implement
`Closer` interface between the sorters and `[2]`.

As a result of not closing `[2]`, some disk resources might be leaked.
This commit fixes the issue by making `diskSpillerBase` close all of its
inputs (which is a single input in the case of the disk-backed distinct
and disk-backed hash aggregator). `Close` is allowed to be called
multiple time, so it is ok if there happen to be other codepaths
calling it.

Fixes: #81413.

Release note: None

### CODE REVIEW

**Review by jbowens — APPROVED** [review]
:lgtm:

Thanks for the quick follow up!

> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81419#-:-N2MVcXN1RJcERK3FW_-:b-a0hcju)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Review by michae2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81419)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[`pkg/sql/colexec/colexecdisk/disk_spiller.go` line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81419#-N2NBCfd6xvH80ZXwoqG:-N2NBCfd6xvH80ZXwoqH:b3semps) ([raw file](https://github.com/cockroachdb/cockroach/blob/7710cb4f9537bbb28be704afd7b9cca31e35d257/pkg/sql/colexec/colexecdisk/disk_spiller.go#L246)):*
> ```Go
> 		if c, ok := input.(colexecop.Closer); ok {
> 			if err := c.Close(ctx); err != nil {
> 				retErr = err
> ```

Why not use use `errors.CombineErrors` here? (And in the other Close methods.)

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81419)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @michae2)

___
*[`pkg/sql/colexec/colexecdisk/disk_spiller.go` line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81419#-N2NBCfd6xvH80ZXwoqG:-N2NUAgrE3Jrl2FtN1Js:bx8x40k) ([raw file](https://github.com/cockroachdb/cockroach/blob/7710cb4f9537bbb28be704afd7b9cca31e35d257/pkg/sql/colexec/colexecdisk/disk_spiller.go#L246)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Why not use use `errors.CombineErrors` here? (And in the other Close methods.)
</blockquote></details>

Probably for no strong reason - this error is eventually just logged (see `CloseAndLogOnErr` in `colexecop/operator.go`), the errors here are extremely unlikely to occur in the first place, maybe the method was introduced when `errors.CombineErrors` was not used widely.

Still, since I want this to be backported, I'm inclined to keep returning the last error for consistency with other implementations.

**Review by michae2 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81419#-:-N2O6Yvt3TieAUVet_8E:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @cucaroach)

___
*[`pkg/sql/colexec/colexecdisk/disk_spiller.go` line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81419#-N2NBCfd6xvH80ZXwoqG:-N2O6UhW9pENvdGryBE_:b-a89jqc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7710cb4f9537bbb28be704afd7b9cca31e35d257/pkg/sql/colexec/colexecdisk/disk_spiller.go#L246)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Probably for no strong reason - this error is eventually just logged (see `CloseAndLogOnErr` in `colexecop/operator.go`), the errors here are extremely unlikely to occur in the first place, maybe the method was introduced when `errors.CombineErrors` was not used widely.

Still, since I want this to be backported, I'm inclined to keep returning the last error for consistency with other implementations.
</blockquote></details>

Ok, that's fine.

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81419#-:-N2OAH624mUEi_qvz1ol:b-tlx7ko)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @cucaroach)

**Pull request merged**
