### PR TITLE
build: add a new linter that checks that quoted URLs are live

### PR DESCRIPTION
**Pull request by benesch**
This extracts @knz's lovely URL checker from #15751 into a standalone `urlcheck` command and an associated TC script.

### CODE REVIEW

**Comment by benesch** [comment]
Sample nightly output here: https://teamcity.cockroachdb.com/viewLog.html?buildId=247585&buildTypeId=Cockroach_Nightlies_URLCheck&tab=buildLog#_focus=120&state=120

Two of those failures are spurious (timeouts). The last is almost certainly a stale URL in our Jepsen terraform scripts. Ignoring that one, because I think we're ditching terraform for those tests anyway.

**Comment by knz** [comment]
Ack.

**Review by dt — APPROVED** [review]

**Comment by tamird** [comment]
Haven't had a chance to finish reviewing yet, will do so this morning.

**Comment by benesch** [comment]
As of the latest rebase, our URLs are all clean! https://teamcity.cockroachdb.com/viewLog.html?buildId=248054&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_URLCheck

**Comment by tamird** [comment]
Thanks for picking this up, mostly looks good except for the racy bit.

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: 2 of 10 files reviewed at latest revision, 16 unresolved discussions, all commit checks successful.

---

*[pkg/cmd/urlcheck/main.go, line 84 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-KjvXvINRqN_qvYgJmo3:-KjvXvINRqN_qvYgJmo4:blvf43t) ([raw file](https://github.com/cockroachdb/cockroach/blob/06648cbaf2ab5ac6d5b2a7d50c9508061aeb6fef/pkg/cmd/urlcheck/main.go#L84)):*
> ```Go
> }
> 
> func fatalf(format string, args ...interface{}) {
> ```

could you use `log.Fatalf` everywhere instead? There's no restriction on importing "log" in commands.

---

*[pkg/cmd/urlcheck/main.go, line 117 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-KjvYEoHlRcJgIQJ_0kq:-KjvYEoHlRcJgIQJ_0kr:bs5b0mj) ([raw file](https://github.com/cockroachdb/cockroach/blob/06648cbaf2ab5ac6d5b2a7d50c9508061aeb6fef/pkg/cmd/urlcheck/main.go#L117)):*
> ```Go
> 	cmd := exec.Command("git", "grep", "-nE", urlRE)
> 	stdout, err := cmd.StdoutPipe()
> 	filter := stream.ReadLines(stdout)
> ```

shouldn't the error check precede this?

---

*[pkg/cmd/urlcheck/main.go, line 148 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-KjvYV5gkCeMalKKGuwg:-KjvYV5gkCeMalKKGuwh:bomllof) ([raw file](https://github.com/cockroachdb/cockroach/blob/06648cbaf2ab5ac6d5b2a7d50c9508061aeb6fef/pkg/cmd/urlcheck/main.go#L148)):*
> ```Go
> 			}
> 			l = append(l, s)
> 			uniqueURLs[match] = l
> ```

could this be `uniqueURLs[match] = append(uniqueURLs[match], s)`?

---

*[pkg/cmd/urlcheck/main.go, line 36 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-Kjy-IRMC3FA_oLXVq1K:-Kjy-IRNIigcqZodlFVq:b-g4bqcf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b813cb9c96e9d55ee81cbe50123333124914c810/pkg/cmd/urlcheck/main.go#L36)):*
> ```Go
> )
> 
> // Number of concurrent HTTP requests during the test
> ```

periods at the end of comments, please.

---

*[pkg/cmd/urlcheck/main.go, line 124 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-Kjy-a-yJrvMBYulpyzA:-Kjy-a-zbcD4IFRfX1BM:bu0rmc7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b813cb9c96e9d55ee81cbe50123333124914c810/pkg/cmd/urlcheck/main.go#L124)):*
Is this actually needed? I thought closing was body was enough (I know @dt left a comment in the previous PR suggesting this was needed). [The documentation](https://godoc.org/net/http#Response) reads:

>  // ... The default HTTP client's Transport does not
    // attempt to reuse HTTP/1.0 or HTTP/1.1 TCP connections
    // ("keep-alive") unless the Body is read to completion and is
    // closed.

So it seems to have an effect on connection reuse, but not much else. Anyway, consider this comment optional.

---

*[pkg/cmd/urlcheck/main.go, line 127 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-Kjy0CRkl-3mjjSm1DQa:-Kjy0CRkl-3mjjSm1DQb:b-lmc8yf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b813cb9c96e9d55ee81cbe50123333124914c810/pkg/cmd/urlcheck/main.go#L127)):*
> ```Go
> 		fatalf("fatal: %s\n", err)
> 	}
> 	resp.Body.Close()
> ```

no error check?

---

*[pkg/cmd/urlcheck/main.go, line 139 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-Kjy0JYIwmXK2IsWOF6v:-Kjy0JYIwmXK2IsWOF6w:b-a8jhmd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b813cb9c96e9d55ee81cbe50123333124914c810/pkg/cmd/urlcheck/main.go#L139)):*
> ```Go
> 		// several misconfigured S3 buckets that return 403 Forbidden for HEAD
> 		// requests but not for GET requests.
> 		resp, err = client.Get(url)
> ```

consider using `:=` here and returning `errors.New(resp.Status)` explicitly from this block rather than overwriting the outer value. The current code feels fragile to me, though I could be convinced that it's paranoia.

---

*[pkg/cmd/urlcheck/main.go, line 146 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-Kjy0LfJR4bxp_lXm4Bl:-Kjy0LfJR4bxp_lXm4Bm:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/b813cb9c96e9d55ee81cbe50123333124914c810/pkg/cmd/urlcheck/main.go#L146)):*
> ```Go
> 			fatalf("fatal: %s\n", err)
> 		}
> 		resp.Body.Close()
> ```

ditto

---

*[pkg/cmd/urlcheck/main.go, line 177 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-Kjy0pxdIMnxQSMHtfC9:-Kjy0pxdIMnxQSMHtfCA:b-m4n3ei) ([raw file](https://github.com/cockroachdb/cockroach/blob/b813cb9c96e9d55ee81cbe50123333124914c810/pkg/cmd/urlcheck/main.go#L177)):*
> ```Go
> 			match = chompUnbalanced('(', ')', match)
> 			match = chompUnbalanced('[', ']', match)
> 			// Remove punctuation after the URL
> ```

period

---

*[pkg/cmd/urlcheck/main.go, line 198 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-Kjy0s7C9hEnVaBoqRNw:-Kjy0s7C9hEnVaBoqRNx:b-qattvb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b813cb9c96e9d55ee81cbe50123333124914c810/pkg/cmd/urlcheck/main.go#L198)):*
> ```Go
> 	if err := cmd.Wait(); err != nil {
> 		if out := stderr.String(); len(out) > 0 {
> 			fatalf("err=%s, stderr=%s", err, out)
> ```

this looks wrong; you only consider it an error if there's something on stderr? Also, I think you can just avoid giving stderr a buffer and use the return value of [`Wait()`](https://godoc.org/os/exec#Cmd.Wait) which includes stderr.

---

*[pkg/cmd/urlcheck/main.go, line 203 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-Kjy1BkZ8wP4UW2RkGAe:-Kjy1BkZ8wP4UW2RkGAf:b-6oxzv9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b813cb9c96e9d55ee81cbe50123333124914c810/pkg/cmd/urlcheck/main.go#L203)):*
> ```Go
> 
> 	var wg sync.WaitGroup
> 	var sem = make(chan struct{}, concurrentRequests)
> ```

why the unusual style? `:=` would be more typical.

---

*[pkg/cmd/urlcheck/main.go, line 206 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-Kjy1FJJ1zA7YfLsb2HU:-Kjy1FJJ1zA7YfLsb2HV:b-137q63) ([raw file](https://github.com/cockroachdb/cockroach/blob/b813cb9c96e9d55ee81cbe50123333124914c810/pkg/cmd/urlcheck/main.go#L206)):*
> ```Go
> 
> 	// This test doesn't care that https certificates are invalid.
> 	tr := &http.Transport{
> ```

nit: No need for this local

---

*[pkg/cmd/urlcheck/main.go, line 218 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-Kjy1KbEDIu4GDYeejm9:-Kjy1KbEDIu4GDYeejmA:b-3yc37r) ([raw file](https://github.com/cockroachdb/cockroach/blob/b813cb9c96e9d55ee81cbe50123333124914c810/pkg/cmd/urlcheck/main.go#L218)):*
> ```Go
> 		for _, i := range ignored {
> 			if strings.HasPrefix(url, i) {
> 				ignore = true
> ```

consider a loop label on the outer loop and a `continue outer` here rather than this boolean

---

*[pkg/cmd/urlcheck/main.go, line 228 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-Kjy2IYf-gfa_wVenMKG:-Kjy2IYf-gfa_wVenMKH:b-k97wg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b813cb9c96e9d55ee81cbe50123333124914c810/pkg/cmd/urlcheck/main.go#L228)):*
> ```Go
> 		sem <- struct{}{}
> 		wg.Add(1)
> 		go func(url string, locs []string) {
> ```

this pattern is racy, each call to `errorf` appends to a shared buffer, with no synchronization. You could avoid all these complications by replacing the wait group with a buffered error channel of known size (you'd have to iterate over URLs twice, but that seems OK).

That change would also all you to avoid the global `errorMessages`, which is kind of uncomfortable.

---

*[pkg/cmd/urlcheck/main.go, line 231 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-Kjy1VakLjk2AAupZ57g:-Kjy1VakLjk2AAupZ57h:b-knla2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/b813cb9c96e9d55ee81cbe50123333124914c810/pkg/cmd/urlcheck/main.go#L231)):*
> ```Go
> 			defer func() { wg.Done(); <-sem }()
> 
> 			fmt.Fprintf(os.Stderr, "Checking %s...\n", url)
> ```

consider `log.Printf` here (no need for the trailing newline if you use that)

---

*[pkg/cmd/urlcheck/main.go, line 244 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-Kjy1guVT-LE6z-jijP9:-Kjy1guVT-LE6z-jijPA:bdl6kk2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b813cb9c96e9d55ee81cbe50123333124914c810/pkg/cmd/urlcheck/main.go#L244)):*
> ```Go
> 			for i := uint(0); i < timeoutRetries; i++ {
> 				err := checkURL(client, url)
> 				if netErr, ok := err.(net.Error); !(ok && netErr.Timeout()) {
> ```

This might read better (because it avoids the awkward `netErr` name:
```
if err, ok := err.(net.Error); ok && net.Timeout() {
  time.Sleep((1 << i) * time.Second)
  continue
}
if err != nil {
  urlError(err)
}
return
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-:-Kjy2kc8kEXObJbMnM5Q:baqp28v)*

**Comment by benesch** [comment]
Review status: 1 of 10 files reviewed at latest revision, 16 unresolved discussions.

---

*[pkg/cmd/urlcheck/main.go, line 84 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-KjvXvINRqN_qvYgJmo3:-KjyA2Ho5ZqsV8e70y7p:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/06648cbaf2ab5ac6d5b2a7d50c9508061aeb6fef/pkg/cmd/urlcheck/main.go#L84)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

could you use `log.Fatalf` everywhere instead? There's no restriction on importing "log" in commands.
</blockquote></details>

Done.

---

*[pkg/cmd/urlcheck/main.go, line 117 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-KjvYEoHlRcJgIQJ_0kq:-KjyAhD6kzk1bTje9axi:b-qu6n94) ([raw file](https://github.com/cockroachdb/cockroach/blob/06648cbaf2ab5ac6d5b2a7d50c9508061aeb6fef/pkg/cmd/urlcheck/main.go#L117)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

shouldn't the error check precede this?
</blockquote></details>

Good point. Done.

---

*[pkg/cmd/urlcheck/main.go, line 148 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-KjvYV5gkCeMalKKGuwg:-KjyAsT9ZibCiKZiRE6e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/06648cbaf2ab5ac6d5b2a7d50c9508061aeb6fef/pkg/cmd/urlcheck/main.go#L148)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

could this be `uniqueURLs[match] = append(uniqueURLs[match], s)`?
</blockquote></details>

Done.

---

*[pkg/cmd/urlcheck/main.go, line 36 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-Kjy-IRMC3FA_oLXVq1K:-KjyDibeSMalH_OTlexK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b813cb9c96e9d55ee81cbe50123333124914c810/pkg/cmd/urlcheck/main.go#L36)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

periods at the end of comments, please.
</blockquote></details>

Done.

---

*[pkg/cmd/urlcheck/main.go, line 124 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-Kjy-a-yJrvMBYulpyzA:-KjyAA3NVvy2L04EcINM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b813cb9c96e9d55ee81cbe50123333124914c810/pkg/cmd/urlcheck/main.go#L124)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Is this actually needed? I thought closing was body was enough (I know @dt left a comment in the previous PR suggesting this was needed). [The documentation](https://godoc.org/net/http#Response) reads:

>  // ... The default HTTP client's Transport does not
    // attempt to reuse HTTP/1.0 or HTTP/1.1 TCP connections
    // ("keep-alive") unless the Body is read to completion and is
    // closed.

So it seems to have an effect on connection reuse, but not much else. Anyway, consider this comment optional.
</blockquote></details>

Done.

---

*[pkg/cmd/urlcheck/main.go, line 127 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-Kjy0CRkl-3mjjSm1DQa:-KjyA_u-JDZ0pxFACXOV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b813cb9c96e9d55ee81cbe50123333124914c810/pkg/cmd/urlcheck/main.go#L127)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

no error check?
</blockquote></details>

Done.

---

*[pkg/cmd/urlcheck/main.go, line 139 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-Kjy0JYIwmXK2IsWOF6v:-KjyE2SRmOgH5cHP18C4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b813cb9c96e9d55ee81cbe50123333124914c810/pkg/cmd/urlcheck/main.go#L139)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

consider using `:=` here and returning `errors.New(resp.Status)` explicitly from this block rather than overwriting the outer value. The current code feels fragile to me, though I could be convinced that it's paranoia.
</blockquote></details>

Done.

---

*[pkg/cmd/urlcheck/main.go, line 146 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-Kjy0LfJR4bxp_lXm4Bl:-KjyAe-apFT_E7uD305b:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b813cb9c96e9d55ee81cbe50123333124914c810/pkg/cmd/urlcheck/main.go#L146)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

---

*[pkg/cmd/urlcheck/main.go, line 177 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-Kjy0pxdIMnxQSMHtfC9:-KjyE4SGOcPeST8sSdlx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b813cb9c96e9d55ee81cbe50123333124914c810/pkg/cmd/urlcheck/main.go#L177)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

period
</blockquote></details>

Done.

---

*[pkg/cmd/urlcheck/main.go, line 198 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-Kjy0s7C9hEnVaBoqRNw:-KjyODivHkL8P7Afmgnk:bn1alp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b813cb9c96e9d55ee81cbe50123333124914c810/pkg/cmd/urlcheck/main.go#L198)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this looks wrong; you only consider it an error if there's something on stderr? Also, I think you can just avoid giving stderr a buffer and use the return value of [`Wait()`](https://godoc.org/os/exec#Cmd.Wait) which includes stderr.
</blockquote></details>

Good catch. Fixed. Tried your suggestion, but sadly `ExitErr.Stderr` is only populated if you call `Output`. ¯\_(ツ)_/¯  

---

*[pkg/cmd/urlcheck/main.go, line 203 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-Kjy1BkZ8wP4UW2RkGAe:-KjyAyOR9-tT7vL6nmkM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b813cb9c96e9d55ee81cbe50123333124914c810/pkg/cmd/urlcheck/main.go#L203)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why the unusual style? `:=` would be more typical.
</blockquote></details>

Done.

---

*[pkg/cmd/urlcheck/main.go, line 206 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-Kjy1FJJ1zA7YfLsb2HU:-KjyB2Wp16zwqqE8IIU5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b813cb9c96e9d55ee81cbe50123333124914c810/pkg/cmd/urlcheck/main.go#L206)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: No need for this local
</blockquote></details>

Done.

---

*[pkg/cmd/urlcheck/main.go, line 218 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-Kjy1KbEDIu4GDYeejm9:-KjyBAztAS8EnchGJQls:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b813cb9c96e9d55ee81cbe50123333124914c810/pkg/cmd/urlcheck/main.go#L218)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

consider a loop label on the outer loop and a `continue outer` here rather than this boolean
</blockquote></details>

Done.

---

*[pkg/cmd/urlcheck/main.go, line 228 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-Kjy2IYf-gfa_wVenMKG:-KjyPmr7ckDp0FwKW0X0:b-g9uo2y) ([raw file](https://github.com/cockroachdb/cockroach/blob/b813cb9c96e9d55ee81cbe50123333124914c810/pkg/cmd/urlcheck/main.go#L228)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this pattern is racy, each call to `errorf` appends to a shared buffer, with no synchronization. You could avoid all these complications by replacing the wait group with a buffered error channel of known size (you'd have to iterate over URLs twice, but that seems OK).

That change would also all you to avoid the global `errorMessages`, which is kind of uncomfortable.
</blockquote></details>

Eep. Good call. 

---

*[pkg/cmd/urlcheck/main.go, line 231 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-Kjy1VakLjk2AAupZ57g:-KjyBG3vfCbPLjTpaicJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b813cb9c96e9d55ee81cbe50123333124914c810/pkg/cmd/urlcheck/main.go#L231)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

consider `log.Printf` here (no need for the trailing newline if you use that)
</blockquote></details>

Done.

---

*[pkg/cmd/urlcheck/main.go, line 244 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-Kjy1guVT-LE6z-jijP9:-KjyBYMFBIQe9R_KCte4:b-7kyx3g) ([raw file](https://github.com/cockroachdb/cockroach/blob/b813cb9c96e9d55ee81cbe50123333124914c810/pkg/cmd/urlcheck/main.go#L244)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

This might read better (because it avoids the awkward `netErr` name:
```
if err, ok := err.(net.Error); ok && net.Timeout() {
  time.Sleep((1 << i) * time.Second)
  continue
}
if err != nil {
  urlError(err)
}
return
```

</blockquote></details>

Done. See `checkURLWithRetries`. This control flow is complicated enough that I think it really benefits from the extra helper.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886)*

**Comment by tamird** [comment]
:lgtm_strong: thanks!

I'd be OK with squashing these commits so that everything passes tests atomically.

---

Reviewed 9 of 9 files at r5, 8 of 8 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/cmd/urlcheck/main.go, line 198 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-Kjy0s7C9hEnVaBoqRNw:-KjyZcGLtdGE-JvUqgin:b-24ypp2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b813cb9c96e9d55ee81cbe50123333124914c810/pkg/cmd/urlcheck/main.go#L198)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Good catch. Fixed. Tried your suggestion, but sadly `ExitErr.Stderr` is only populated if you call `Output`. ¯\_(ツ)_/¯  
</blockquote></details>

Bummer! Thanks for checking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15886#-:-Kjy_B1LQ5TXMTIWB9aL:ba99f2p)*

**Comment by benesch** [comment]
Going to leave unsquashed because the test only runs nightly and so will never prevent stale URLs from making it onto master.

**Comment by benesch** [comment]
TFTRs!

**Pull request merged**
