### PR TITLE
sql: add statement fingerprint ID to sampled query

### PR DESCRIPTION
**Pull request by THardy98**
Partially addresses: #71328

This change adds the statement fingerprint ID to the sampled query log,
allowing us to measure the uniqueness of a workload.

Release note (sql change): Sampled query telemetry log now includes the
statement's fingerprint ID.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 4 of 5 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84182)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @THardy98)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84182#-N6npura15-6ANPhClpM):*
nit: this commit should follow the guidelines too :)
___
*[`-- commits` line 10 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84182#-N6nq3fX0wUrUrgh4dew):*
nit: is this user-visible change? In other words, do CRDB users care about this? Or only CRDB staff? If it's the latter, then we should not add a release note for it.
___
*[`pkg/sql/conn_executor.go` line 1371 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84182#-N6nrWnv5vOd55ln-sPG:-N6nrWnv5vOd55ln-sPH:b64mi3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/d710737ab1789d68a63a0df9cf57602e5e0ce94f/pkg/sql/conn_executor.go#L1371)):*
> ```Go
> 		// currentStatementFingerprintID is the statement fingerprint ID of the last statement
> 		// dispatched to the execution engine.
> 		currentStatementFingerprintID roachpb.StmtFingerprintID
> ```

I think I would move it outside of `extraTxnState` since the field is not updated in the scope of the transaction. Currently, it seems like it's just a placeholder to pass the stmt fingerprint ID from `recordStatementSummary` to `maybeLogStatement`, and we don't modify it in other methods like `onTxnRestart`.

How about not storing it explicitly at all? Something like this:
```
diff --git a/pkg/sql/conn_executor_exec.go b/pkg/sql/conn_executor_exec.go
index 98878f46f3..f76d427c0a 100644
--- a/pkg/sql/conn_executor_exec.go
+++ b/pkg/sql/conn_executor_exec.go
@@ -1060,6 +1060,7 @@ func (ex *connExecutor) dispatchToExecutionEngine(
                res.DisableBuffering()
        }
 
+       var stmtFingerprintID roachpb.StmtFingerprintID
        defer func() {
                planner.maybeLogStatement(
                        ctx,
@@ -1071,6 +1072,7 @@ func (ex *connExecutor) dispatchToExecutionEngine(
                        ex.statsCollector.PhaseTimes().GetSessionPhaseTime(sessionphase.SessionQueryReceived),
                        &ex.extraTxnState.hasAdminRoleCache,
                        ex.server.TelemetryLoggingMetrics,
+                       stmtFingerprintID,
                )
        }()
 
@@ -1184,7 +1186,7 @@ func (ex *connExecutor) dispatchToExecutionEngine(
 
        // Record the statement summary. This also closes the plan if the
        // plan has not been closed earlier.
-       ex.recordStatementSummary(
+       stmtFingerprintID = ex.recordStatementSummary(
                ctx, planner,
                int(ex.state.mu.autoRetryCounter), res.RowsAffected(), res.Err(), stats,
        )
diff --git a/pkg/sql/executor_statement_metrics.go b/pkg/sql/executor_statement_metrics.go
index c44dc589c7..27dd659502 100644
--- a/pkg/sql/executor_statement_metrics.go
+++ b/pkg/sql/executor_statement_metrics.go
@@ -116,7 +116,7 @@ func (ex *connExecutor) recordStatementSummary(
        rowsAffected int,
        stmtErr error,
        stats topLevelQueryStats,
-) {
+) roachpb.StmtFingerprintID {
        phaseTimes := ex.statsCollector.PhaseTimes()
 
        // Collect the statistics.
@@ -235,6 +235,8 @@ func (ex *connExecutor) recordStatementSummary(
                        sessionAge,
                )
        }
+
+       return stmtFingerprintID
 }
 
 func (ex *connExecutor) updateOptCounters(planFlags planFlags) {
```
___
*[`pkg/sql/exec_log.go` line 17 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84182#-N6nqGPKDKmBkZ8Mq7kj:-N6nqGPLAFUcmXFTxLES:b-w0w5el) ([raw file](https://github.com/cockroachdb/cockroach/blob/d710737ab1789d68a63a0df9cf57602e5e0ce94f/pkg/sql/exec_log.go#L17)):*
> ```Go
> 	"context"
> 	"fmt"
> 	"github.com/cockroachdb/cockroach/pkg/roachpb"
> ```

nit: ordering is off.
___
*[`pkg/util/log/eventpb/telemetry.proto` line 63 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84182#-N6nqid52hYoe3aIFoq0:-N6nqid52hYoe3aIFoq1:brrrqem) ([raw file](https://github.com/cockroachdb/cockroach/blob/d710737ab1789d68a63a0df9cf57602e5e0ce94f/pkg/util/log/eventpb/telemetry.proto#L63)):*
> ```protobuf
> 
>   // Statement fingerprint ID of the query.
>   uint64 statement_fingerprint_id = 12 [(gogoproto.customname) = "StatementFingerprintID", (gogoproto.jsontag) = ',omitempty'];
> ```

nit: we probably could use `roachpb.StatementFingerprintID` type here too, not sure if it's important enough, up to you.

nit: is this sensitive? Should this be marked as `"redact:\"nonsensitive\""`?

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84182)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @THardy98)

___
*[`pkg/sql/exec_log.go` line 389 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84182#-N6nzB1C2GzFPp1PUO2g:-N6nzB1C2GzFPp1PUO2h:bqwolg0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d710737ab1789d68a63a0df9cf57602e5e0ce94f/pkg/sql/exec_log.go#L389)):*
> ```Go
> 		}
> 		if telemetryMetrics.maybeUpdateLastEmittedTime(telemetryMetrics.timeNow(), requiredTimeElapsed) {
> 			database := p.CurrentDatabase()
> ```

nit: is this change to assign `p.CurrentDatabase()`  to an intermediate variable necessary, if it's only used in a single place? 



_Code quote:_
```Go
database := p.CurrentDatabase()
```

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84182)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @THardy98, and @yuzefovich)

___
*[`-- commits` line 10 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84182#-N6nq3fX0wUrUrgh4dew):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: is this user-visible change? In other words, do CRDB users care about this? Or only CRDB staff? If it's the latter, then we should not add a release note for it.
</blockquote></details>

I'd say yes, users ingesting telemetry logs will see this new field.
___
*[`pkg/sql/conn_executor.go` line 1371 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84182#-N6nrWnv5vOd55ln-sPG:-N6o-BP6CvHKgYxBfN_H:b-vkzhay) ([raw file](https://github.com/cockroachdb/cockroach/blob/d710737ab1789d68a63a0df9cf57602e5e0ce94f/pkg/sql/conn_executor.go#L1371)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think I would move it outside of `extraTxnState` since the field is not updated in the scope of the transaction. Currently, it seems like it's just a placeholder to pass the stmt fingerprint ID from `recordStatementSummary` to `maybeLogStatement`, and we don't modify it in other methods like `onTxnRestart`.

How about not storing it explicitly at all? Something like this:
```
diff --git a/pkg/sql/conn_executor_exec.go b/pkg/sql/conn_executor_exec.go
index 98878f46f3..f76d427c0a 100644
--- a/pkg/sql/conn_executor_exec.go
+++ b/pkg/sql/conn_executor_exec.go
@@ -1060,6 +1060,7 @@ func (ex *connExecutor) dispatchToExecutionEngine(
                res.DisableBuffering()
        }
 
+       var stmtFingerprintID roachpb.StmtFingerprintID
        defer func() {
                planner.maybeLogStatement(
                        ctx,
@@ -1071,6 +1072,7 @@ func (ex *connExecutor) dispatchToExecutionEngine(
                        ex.statsCollector.PhaseTimes().GetSessionPhaseTime(sessionphase.SessionQueryReceived),
                        &ex.extraTxnState.hasAdminRoleCache,
                        ex.server.TelemetryLoggingMetrics,
+                       stmtFingerprintID,
                )
        }()
 
@@ -1184,7 +1186,7 @@ func (ex *connExecutor) dispatchToExecutionEngine(
 
        // Record the statement summary. This also closes the plan if the
        // plan has not been closed earlier.
-       ex.recordStatementSummary(
+       stmtFingerprintID = ex.recordStatementSummary(
                ctx, planner,
                int(ex.state.mu.autoRetryCounter), res.RowsAffected(), res.Err(), stats,
        )
diff --git a/pkg/sql/executor_statement_metrics.go b/pkg/sql/executor_statement_metrics.go
index c44dc589c7..27dd659502 100644
--- a/pkg/sql/executor_statement_metrics.go
+++ b/pkg/sql/executor_statement_metrics.go
@@ -116,7 +116,7 @@ func (ex *connExecutor) recordStatementSummary(
        rowsAffected int,
        stmtErr error,
        stats topLevelQueryStats,
-) {
+) roachpb.StmtFingerprintID {
        phaseTimes := ex.statsCollector.PhaseTimes()
 
        // Collect the statistics.
@@ -235,6 +235,8 @@ func (ex *connExecutor) recordStatementSummary(
                        sessionAge,
                )
        }
+
+       return stmtFingerprintID
 }
 
 func (ex *connExecutor) updateOptCounters(planFlags planFlags) {
```
</blockquote></details>

Yea, that's a better idea. Changed to return from `recordStatementSummary` instead.
___
*[`pkg/sql/exec_log.go` line 389 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84182#-N6nzB1C2GzFPp1PUO2g:-N6o-STd6W-jZUK1j0eo:b-t4wkdq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d710737ab1789d68a63a0df9cf57602e5e0ce94f/pkg/sql/exec_log.go#L389)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: is this change to assign `p.CurrentDatabase()`  to an intermediate variable necessary, if it's only used in a single place? 
</blockquote></details>

Nope, moving it to the log field.
___
*[`pkg/util/log/eventpb/telemetry.proto` line 63 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84182#-N6nqid52hYoe3aIFoq0:-N6o-a4O1HaXWW5-JtMC:b-j3kycl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d710737ab1789d68a63a0df9cf57602e5e0ce94f/pkg/util/log/eventpb/telemetry.proto#L63)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: we probably could use `roachpb.StatementFingerprintID` type here too, not sure if it's important enough, up to you.

nit: is this sensitive? Should this be marked as `"redact:\"nonsensitive\""`?
</blockquote></details>

I tried to use `roachpb.StatementFingerprintID` earlier, but there's an import cycle. We don't lose any information using `uint64`, seems fine.

By default, numbers aren't marked for redaction.

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84182)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @THardy98, and @yuzefovich)

___
*[`pkg/sql/exec_log.go` line 17 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84182#-N6nqGPKDKmBkZ8Mq7kj:-N6o0HiZ8TPpDTGWetA3:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/d710737ab1789d68a63a0df9cf57602e5e0ce94f/pkg/sql/exec_log.go#L17)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: ordering is off.
</blockquote></details>

Fixed.

**Review by yuzefovich — APPROVED** [review]
:lgtm: Thanks!

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84182#-:-N6o4BH41eTIMAr4Tqqt:b-g2a5fb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier and @THardy98)

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84182)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier and @yuzefovich)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84182#-N6npura15-6ANPhClpM):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this commit should follow the guidelines too :)
</blockquote></details>

Oh, didn't know that, fixed.

**Review by THardy98 — COMMENTED** [review]
Awesome TYFR :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84182#-:-N6o5sxY1xCeU0U3ZzVi:b-hdt42s)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier and @yuzefovich)

**Review by xinhaoz — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, 7 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84182#-:-N6o9GoDDEabbxUKuoBG:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier and @yuzefovich)

**Comment by THardy98** [comment]
Rebased, fixed some merge conflicts

**Review by abarganier — APPROVED** [review]
:lgtm: thank you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84182#-:-N6rqjCiCoiFx0w9hGPw:bro3093)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @xinhaoz and @yuzefovich)

**Comment by THardy98** [comment]
blathers backport 22.1 21.2

**Pull request merged**
