### PR TITLE
util/metric: change preset buckets from NetworkLatencyBuckets to IOLatencyBuckets

### LINKED ISSUE #104017: util/metric: `NetworkLatencyBuckets` ceiling too low
The `NetworkLatencyBuckets` histogram buckets max out at 1 second. This is too low for most of the current users, where latencies can easily be several seconds when clusters are struggling, and we'd want to see the actual latencies -- in particular:

* `liveness.heartbeatlatency`
* `leases.requests.latency`
* `kv.prober.read.latency`
* `kv.prober.write.latency`

@dhartunian What would you recommend for these? Should we change them to `IOLatencyBuckets`, or increase the range on `NetworkLatencyBuckets` to 10 seconds? Is it safe to do so from a backwards compatibility perspective?

Jira issue: CRDB-28314

### PR DESCRIPTION
**Pull request by ericharmeling**
This commit replaces NetworkLatencyBuckets with IOLatencyBuckets as the preset buckets used for the following metrics' histograms:
- `liveness.heartbeatlatency`
- `leases.requests.latency`
- `kv.prober.read.latency`
- `kv.prober.write.latency`
- `proxy.conn_migration.attempted.latency`

The upper limit on NetworkLatencyBuckets (1s) is too low for these metrics. Bucket size for all preset buckets increases logarithmically (see `prometheus.ExponentialBucketsRange`), retaining fidelity at the lower-end of buckets.

Fixes #104017.

Release note: None

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
Thanks! Seems like these buckets were introduced in #86671, so we'll probably need a 23.1 backport as well.

Should we just remove `NetworkLatencyBuckets` outright? They can be pretty misleading and shouldn't be used (unless we increase the upper bound).

**Comment by ericharmeling** [comment]
> Should we just remove NetworkLatencyBuckets outright? They can be pretty misleading and shouldn't be used (unless we increase the upper bound).

SGTM!

**Review by Santamaura — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106193)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier)

**Comment by erikgrinaker** [comment]
Can we make sure this is backported please?

**Pull request merged**
