### PR TITLE
release-23.1: cli: fix debug pebble commands on encrypted stores

### PR DESCRIPTION
**Pull request by RaduBerinde**
Backport 1/1 commits from #110150.

/cc @cockroachdb/release

Release justification: improves usability of tool used for customer support.

---

Currently the debug pebble commands only work correctly on an
encrypted store if the encrypted store's path is `cockroach-data` or
the store directory is passed using `--store` (in addition to being
passed to the pebble subcommand itself). What's worse, knowledge of
this subtle fact was lost among team members.

The root cause is that we are trying to resolve encryption options
using the server config.  The difficulty is that there are a bunch of
different commands and there is no unified way to obtain the store
directory of interest

To fix this, we create `autoDecryptFS`. This is a `vfs.FS`
implementation which is able to automatically detect encrypted paths
and use the correct unencrypted FS. It does this by having a list of
known encrypted stores (the ones in the `--enterprise-encryption`
flag), and looking for any of these paths as ancestors of any path in
an operation. This new implementation replaces `swappableFS` and
`absoluteFS`.

We also improve the error message when we try to open an encrypted
store without setting up the key correctly.

Fixes: #110121

Release note (bug fix): `cockroach debug pebble` commands now work
correctly with encrypted stores which don't use the default
`cockroach-data` path without having to also pass `--store`.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Oops, the merge wasn't right, I'll fix.

**Comment by RaduBerinde** [comment]
Fixed.

**Comment by RaduBerinde** [comment]
Friendly ping.

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110507#-:-NePDnWi-evNbLSUYumD:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Pull request merged**
