### PR TITLE
catalog/migration: add system.database_role_settings

### PR DESCRIPTION
**Pull request by rafiss**
This table will be used to hold per-database and per-role defaults for
session variables. It is analogous and similar in structure to the
Postgres pg_db_role_setting table. There is no release note since the
table is empty and unused right now.

Release note: None

### CODE REVIEW

**Review by RichardJCai — APPROVED** [review]
> Reviewed 35 of 35 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67861)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Comment by rafiss** [comment]
tftr!

bors r=RichardJCai

**Comment by knz** [comment]
This is guaranteed to fail as-is, CI is unhappy

image

bors r-

**Comment by rafiss** [comment]
sorry for the noise earlier. fixed

bors r=RichardJCai

**Pull request merged**
