### PR TITLE
lint: add a linter for the cockroach-sql imports

### PR DESCRIPTION
**Pull request by knz**
This linter prevents the re-addition of unwanted dependencies.

### CODE REVIEW

**Comment by knz** [comment]
Continuing the discussion from [this comment](https://github.com/cockroachdb/cockroach/pull/67738#discussion_r672232086)

> @otan i'd prefer bazel visibility rules to enforce this (docs.bazel.build/versions/main/visibility.html), but up to you. 

Thanks for the idea. I have a few questions about this:

1) What would be the syntax to make this work? (I am still very uneducated about bazel features)

2) I'm welcoming the idea, assuming that a bazel-enforced constraint is guaranteed to run during CI. Would it be?

3) I am using `go list -deps` because this is guaranteed to print out all the recursive dependencies, not just the immediate package imports. Is that an analysis mode supported by bazel visibility rules?

Maybe these are questions more for @rickystewart ?

**Comment by knz** [comment]
Another thing I'd like to achieve in this PR is a CI-time assertion that the generated binary is below a certain size. @rickystewart where would be the best place to add such an assertion?

I was thinking of `build/teamcity-acceptance.sh` but maybe you have a better idea.

**Comment by otan** [comment]
> What would be the syntax to make this work? (I am still very uneducated about bazel features)

The basic idea is that certain packages are only visibile to certain packages, e.g.

if pkg/sql had:
```
visibility = [
  "//pkg/ccl:__subpackages__",
  "//pkg/cli/cliexecsql:__pkg__",
]
```

only ccl and any subpackages, and the cliexecsql package can read it.

> I'm welcoming the idea, assuming that a bazel-enforced constraint is guaranteed to run during CI. Would it be?

We do have a bazel build CI target here: https://teamcity.cockroachdb.com/viewLog.html?buildId=3201851&tab=buildResultsDiv&buildTypeId=Cockroach_ScratchProjectPutTcExperimentsInHere_BazelBuild, it may only build the CRDB binary but we can add other things.

> I am using go list -deps because this is guaranteed to print out all the recursive dependencies, not just the immediate package imports. Is that an analysis mode supported by bazel visibility rules?

If it's recursive then I guess not. [you can use `bazel query allrdeps` to achieve the same thing though.
](https://docs.bazel.build/versions/main/query.html)

**Comment by otan** [comment]
(this LGTM, if you're ok using go list, it works for me too)

**Comment by knz** [comment]
Let's wait to see what @rickystewart thinks.

**Comment by rickystewart** [comment]
Whoops, sorry, I missed the tag :) Feel free to ping me on Slack if I'm ever making you wait too long.

Yeah, you can accomplish this same thing with Bazel visibility rules. It'll take more lines of code though, since visibility is based on allow-listing rather than deny-listing (as the lint here does). Basically you would need to restrict the visibility of the packages in question to only the packages that are currently using them. For example, wrt `github.com/cockroachdb/cockroach/pkg/cli`, you can find all the packages that depend on them like this:

```
cockroach$ rg '"//pkg/cli"'
pkg/cli/clisqlclient/BUILD.bazel
44:        "//pkg/cli",

pkg/cli/clierror/BUILD.bazel
36:        "//pkg/cli",

pkg/cli/clisqlshell/BUILD.bazel
45:        "//pkg/cli",

pkg/cli/clisqlexec/BUILD.bazel
44:        "//pkg/cli",

pkg/ccl/cliccl/BUILD.bazel
24:        "//pkg/cli",
75:        "//pkg/cli",

pkg/cmd/cockroach/BUILD.bazel
11:        "//pkg/cli",

pkg/cmd/cockroach-oss/BUILD.bazel
9:        "//pkg/cli",

pkg/cmd/cockroach-short/BUILD.bazel
10:        "//pkg/cli",

pkg/cmd/roachtest/tests/BUILD.bazel
137:        "//pkg/cli",

pkg/cmd/allocsim/BUILD.bazel
11:        "//pkg/cli",
```

(You can probably get the same list with an appropriate `bazel query`, but `rg` is faster.) So now we have the list of packages that have valid dependencies on `//pkg/cli`, we can make the visibility list:

```
cockroach$ rg '"//pkg/cli"' | cut -d: -f1 | rev | cut -d/ -f2- | rev | sed 's|^|"//|g' | sed 's|$|:__pkg__",|g'
"//pkg/cli/clisqlclient:__pkg__",
"//pkg/cli/clierror:__pkg__",
"//pkg/cli/clisqlshell:__pkg__",
"//pkg/cli/clisqlexec:__pkg__",
"//pkg/ccl/cliccl:__pkg__",
"//pkg/ccl/cliccl:__pkg__",
"//pkg/cmd/cockroach-oss:__pkg__",
"//pkg/cmd/cockroach:__pkg__",
"//pkg/cmd/cockroach-short:__pkg__",
"//pkg/cmd/allocsim:__pkg__",
"//pkg/cmd/roachtest/tests:__pkg__",
```

Replace the "//visibility:public" in `pkg/cli/BUILD.bazel` with that list and job done. Rinse and repeat with the other targets. Then if anyone tries to add a dependency on `//pkg/cli` from `pkg/cmd/cockroach-sql` at any point, the build will fail.

We don't currently build `cockroach-sql` in CI via Bazel, but we could. Add `//pkg/cmd/cockroach-sql` to the list of targets in `build/bazelutil/bazelbuild.sh`. The build will fail if any of the visibility constraints are violated, no need to even involve the linter.

RE: asserting the binary isn't bigger than a given size, `build/teamcity-acceptance.sh` is a fine place for that. If you start building it with Bazel, you can also add an assertion to `build/teamcity-bazel.sh` (That build already has various assertions/validations about the build results, we can easily add one more.)

**Review by otan — APPROVED** [review]
this is good to me either way!

**Comment by knz** [comment]
So I tried the bazel way and I ran into the following problem:

> Replace the "//visibility:public" in pkg/cli/BUILD.bazel with that list and job done. Rinse and repeat with the other targets. Then if anyone tries to add a dependency on //pkg/cli from pkg/cmd/cockroach-sql at any point, the build will fail.

When I do this, I am noticing that if I ever want to create a new, unrelated package that depends on one of the restricted-visibility packages, I will need to update the visibility rules manually.

That won't do - it's too much friction. 

We want a solution that lints for cockroach-sql, without creating friction for folk who want to use the common packages for unrelated work.

I'll stick to a linter for now.

**Comment by knz** [comment]
bors r=otan

**Pull request merged**
