### PR TITLE
kvstreamer: remove a memory leak

### LINKED ISSUE #76471: sql: possible memory leak in Streamer
In each call to `NewStreamer`, we register an OnChange handler on the `streamerConcurrencyLimit`:
https://github.com/cockroachdb/cockroach/blob/2bc16c3150b6e38ba9323c0986fc68610c1c4c63/pkg/kv/kvclient/kvstreamer/streamer.go#L338-L340

This handler captures the `Streamer` object `s`. The handler is then never unregistered. I believe this leaks the `Streamer` object and all references. This is a problem because, unlike most static objects that are leaked due to calls to `SetOnChange`, we create a new `Streamer` for each SQL query that uses one.

Two ways to address this are to:
1. unregister the OnChange handler when tearing down the `Streamer`. We don't currently have a way to unregister an OnChange handler, but adding one should not be difficult.
2. skip the OnChange handler. Do we need a single instance of a Streamer to react dynamically to cluster setting changes? Is it enough for new instances to use the new limit?

Note: I haven't actually confirmed that this leaks memory, so determining whether it's real would be the first step here.

### PR DESCRIPTION
**Pull request by yuzefovich**
At the moment, we have a memory leak of `Streamer` objects (although
nil-ed out) because of `SetOnChange` handler of the streamer concurrency
limit cluster setting and passing in a closure into `Stopper.AddCloser`.
This was copied over from the `DistSender` code, but a crucial difference
wasn't appreciated - we have a single global `DistSender` that lives
throughout the uptime of the server whereas each `Streamer` object lives
only during the query execution.

We don't need to dynamically react to changes in the streamer concurrency
limits, so this commit removes the handler. The closure has been
refactored too.

Fixes: #76471.

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76480)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373 and @yuzefovich)

___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 338 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76480#-MvpFnDz0Ru3jzdY4NZj:-MvpFnDz0Ru3jzdY4NZk:b-gagjua) ([raw file](https://github.com/cockroachdb/cockroach/blob/e268b1b3f6ae953ee9e001758551dce61349758e/pkg/kv/kvclient/kvstreamer/streamer.go#L338)):*
Do we have the same kind of issue here? `Stopper.AddCloser` says:
> WARNING: memory resources acquired by this method will stay around for the lifetime of the Stopper. Use with care to avoid leaking memory.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76480)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rharding6373)

___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 338 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76480#-MvpFnDz0Ru3jzdY4NZj:-Mvt7dowCQFSOyJuTw_7:bs2izip) ([raw file](https://github.com/cockroachdb/cockroach/blob/e268b1b3f6ae953ee9e001758551dce61349758e/pkg/kv/kvclient/kvstreamer/streamer.go#L338)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we have the same kind of issue here? `Stopper.AddCloser` says:
> WARNING: memory resources acquired by this method will stay around for the lifetime of the Stopper. Use with care to avoid leaking memory.
</blockquote></details>

Indeed, thanks! Fixed. Clearly I haven't used these APIs much :)

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76480#-:-MvtR6ttDUvIdZf0c6eB:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rharding6373)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
