### PR TITLE
sql: add system.jobs table to track progress of long-running jobs

### PR DESCRIPTION
**Pull request by benesch**
Add a migration to inject a system.jobs table into both new and existing
clusters. This table will track the status (pending, running, succeeded,
failed) and completion percentage of long-running jobs. Work to a) log
job status to the table, and b) expose this job status via the admin UI
and SQL console is forthcoming.

The specification of this table is more-completely described in the
System Jobs RFC, docs/RFCS/system_jobs.md.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13995)

### CODE REVIEW

**Comment by danhhz** [comment]
@a-robinson do you remember where we ended up on new system tables being added always via migration vs though the normal mechanism on new clusters and via migration only on existing ones?

Also, this could definitely take a second pair of eyes. Mind taking a look?

**Comment by benesch** [comment]
@danhhz I believe this is the discussion you're referring to? https://reviewable.io/reviews/cockroachdb/cockroach/12228#-KYnu7YzOPUiIvrJU1qd

**Comment by danhhz** [comment]
Yup! Okay sounds like you did what the result of that discussion was. Great!

You've got some failing tests in teamcity and I think it's worth writing a test somewhere just to verify that this table exists

**Comment by benesch** [comment]
Oh my god—how did I miss the forty logic tests that query `information_schema` and expect no jobs table? I'm kind of shocked TeamCity didn't report `TestLogic` as failing. In any case, we should be covered on the testing front.

**Comment by jordanlewis** [comment]
If a package test panics halfway through, the rest of the tests won't get executed - that's why `go test` (and TeamCity) didn't report a failing TestLogic.

**Comment by danhhz** [comment]
:lgtm_strong: let's wait for one more pair of eyes (@a-robinson?) before merging, though

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-:-Kejbs9t71o3wuL-6oGZ:b-p3fbpv)*

**Comment by benesch** [comment]
FWIW these commits are actually ordered db1c50c, 5816ad, f2bc173. GitHub seems to be confused by my force-pushing. 

@danhhz this is ready for your re-review! The changes are mostly confined to the last commit (f2bc173).

**Comment by a-robinson** [comment]
LGTM! Just a few small comments.

---

Reviewed 1 of 1 files at r1, 3 of 9 files at r2, 9 of 9 files at r3, 10 of 10 files at r4, 11 of 11 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/migrations/migrations.go, line 52 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-Kekc7Q2jjPlIpLZBgHL:-Kekc7Q2jjPlIpLZBgHM:b-16jv2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/5816ad2148a7ba6e7daa996fe2620ccadf927c57/pkg/migrations/migrations.go#L52)):*
> ```Go
> 	},
> 	{
> 		name:   "create system.jobs table to track progress of long-running jobs",
> ```

"create system.jobs table" seems sufficiently descriptive. It's super minor, but we do pass this key around and process it every time a cockroachdb node starts so we may as well not make it longer than needed.

---

*[pkg/migrations/migrations.go, line 122 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-KekeH7YOcFcuy7GnDP-:-KekeH7YOcFcuy7GnDP0:b-2sh65x) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2bc173d870344f189b2296d4732d4b7f1576ce2/pkg/migrations/migrations.go#L122)):*
> ```Go
> // AdditionalInitialDescriptors returns the number of system descriptors that
> // have been added by migrations. This is needed for certain tests, which check
> // the number of ranges at node startup. NOTE: This value may be out-of-date if
> ```

Style nit: it's conventional to put the note on its own line to make it more visible to folks whose text editors don't highlight it.

---

*[pkg/migrations/migrations_test.go, line 233 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-Kekej6jeLxvPRWED-bE:-Kekej6kZdxJJN9Jvdwq:bny4jhf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2bc173d870344f189b2296d4732d4b7f1576ce2/pkg/migrations/migrations_test.go#L233)):*
> ```Go
> 			preDescriptors, err := AdditionalInitialDescriptors(context.Background(), mgr.db)
> 			if err != nil {
> 				t.Fatalf("unexpected error %v", err)
> ```

`t.Fatal(err)`

---

*[pkg/migrations/migrations_test.go, line 250 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-Keket0SSO_o2tP22oOW:-Keket0SSO_o2tP22oOX:bny4jhf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2bc173d870344f189b2296d4732d4b7f1576ce2/pkg/migrations/migrations_test.go#L250)):*
> ```Go
> 			postDescriptors, err := AdditionalInitialDescriptors(context.Background(), mgr.db)
> 			if err != nil {
> 				t.Fatalf("unexpected error %v", err)
> ```

`t.Fatal(err)`

---

*[pkg/server/testserver.go, line 327 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-Kekf3-KnW2Z3UMuQfsD:-Kekf3-KnW2Z3UMuQfsE:bv65503) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2bc173d870344f189b2296d4732d4b7f1576ce2/pkg/server/testserver.go#L327)):*
> ```Go
> 	// XXX: This assumes that the number of descriptors added by migrations is equal
> 	// to the number of ranges added, which may not be true in the future.
> 	migrationRangeCount, err := migrations.AdditionalInitialDescriptors(context.TODO(), db)
> ```

context.Background() is preferred in places where we don't ever intend to plumb a real context. If we just use TODO() everywhere it can be tough to find the places where we still want to plumb a context to.

---

*[pkg/sql/sqlbase/system.go, line 462 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-KekdMZDRMIFI58KWF5L:-KekdMZDRMIFI58KWF5M:bou8f4z) ([raw file](https://github.com/cockroachdb/cockroach/blob/5816ad2148a7ba6e7daa996fe2620ccadf927c57/pkg/sql/sqlbase/system.go#L462)):*
> ```Go
> 			{
> 				Name:        "fam_0_id_status_created_payload",
> 				ID:          0,
> ```

This may be a dumb question, but does ID 0 have any special semantics, e.g. assumptions that it only contains the primary key columns? It seems a bit weird to me that columns and indexes start with ID 1 but families start with ID 0.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-:-KekfbGYZ1s6evhPprOZ:b-6xc9ya)*

**Comment by vivekmenezes** [comment]
Nice!

Are you sure this is not going to result in flaky tests. When I first made this change I remember there was some amount of flakiness around splits. Depending on how things ran (race) occasionally the range splitting would happen before the migration, and then post migration the new table addition would not result in a split for a long time.

If you do see this happening, then I suppose you will need to add the jobs table in for all the tests (not make it a migration by default), and add a test that creates a pre migration cluster and adds the jobs table.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-:-Keklg5JKFvW3TH6xBqf:b-nj299w)*

**Comment by vivekmenezes** [comment]
In particular I believe the code that starts the node

```
err = s.node.start(
		ctx,
		unresolvedAdvertAddr,
		s.engines,
		s.cfg.NodeAttributes,
		s.cfg.Locality,
	)
```

runs before the migration code and that starts all the store scanners that run asynchronously. If a store scanner runs by chance before we get to run the migration, it will split what it sees (pre migration table set) which will result in 
WaitForInitialSplits() hanging.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-:-KekpaqLpRoCz6DczAfE:b-d84311)*

**Comment by benesch** [comment]
Review status: 16 of 19 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/migrations/migrations.go, line 52 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-Kekc7Q2jjPlIpLZBgHL:-Kel02ymKz3D7eoZpx_9:b-r86j08) ([raw file](https://github.com/cockroachdb/cockroach/blob/5816ad2148a7ba6e7daa996fe2620ccadf927c57/pkg/migrations/migrations.go#L52)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

"create system.jobs table" seems sufficiently descriptive. It's super minor, but we do pass this key around and process it every time a cockroachdb node starts so we may as well not make it longer than needed.
</blockquote></details>

No problem! Done.

---

*[pkg/migrations/migrations.go, line 122 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-KekeH7YOcFcuy7GnDP-:-Kel02Qqay0BQNdmP5wE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2bc173d870344f189b2296d4732d4b7f1576ce2/pkg/migrations/migrations.go#L122)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Style nit: it's conventional to put the note on its own line to make it more visible to folks whose text editors don't highlight it.
</blockquote></details>

Done.

---

*[pkg/migrations/migrations_test.go, line 233 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-Kekej6jeLxvPRWED-bE:-Kel01t9OkIQ81Br_5JW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2bc173d870344f189b2296d4732d4b7f1576ce2/pkg/migrations/migrations_test.go#L233)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

`t.Fatal(err)`
</blockquote></details>

Done.

---

*[pkg/migrations/migrations_test.go, line 250 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-Keket0SSO_o2tP22oOW:-Kel01VxgRzYcSAxG9nF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2bc173d870344f189b2296d4732d4b7f1576ce2/pkg/migrations/migrations_test.go#L250)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

`t.Fatal(err)`
</blockquote></details>

Done.

---

*[pkg/server/testserver.go, line 327 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-Kekf3-KnW2Z3UMuQfsD:-Kel00o0KyLTC1cKaKin:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2bc173d870344f189b2296d4732d4b7f1576ce2/pkg/server/testserver.go#L327)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

context.Background() is preferred in places where we don't ever intend to plumb a real context. If we just use TODO() everywhere it can be tough to find the places where we still want to plumb a context to.
</blockquote></details>

Done.

---

*[pkg/sql/sqlbase/system.go, line 462 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-KekdMZDRMIFI58KWF5L:-KekzlA153_WAQAQ9Mm2:belkxom) ([raw file](https://github.com/cockroachdb/cockroach/blob/5816ad2148a7ba6e7daa996fe2620ccadf927c57/pkg/sql/sqlbase/system.go#L462)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

This may be a dumb question, but does ID 0 have any special semantics, e.g. assumptions that it only contains the primary key columns? It seems a bit weird to me that columns and indexes start with ID 1 but families start with ID 0.
</blockquote></details>

Not sure! This descriptor has to match what `CREATE TABLE` hands back, and `CREATE TABLE` hands it back like this. I did some spelunking in structured.go and this does seem intentional. I'll bet @danhhz knows more.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995)*

**Comment by danhhz** [comment]
Review status: 16 of 19 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/sqlbase/system.go, line 462 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-KekdMZDRMIFI58KWF5L:-KengPJokStXKk3-zsRM:b-j4bkt4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5816ad2148a7ba6e7daa996fe2620ccadf927c57/pkg/sql/sqlbase/system.go#L462)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Not sure! This descriptor has to match what `CREATE TABLE` hands back, and `CREATE TABLE` hands it back like this. I did some spelunking in structured.go and this does seem intentional. I'll bet @danhhz knows more.
</blockquote></details>

Yup, 0 is right. 0 has to contain all the primary key columns, but it can also contain other columns. 1 vs 0 is for backward compatibility

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995)*

**Comment by tamird** [comment]
Reviewed 9 of 9 files at r3, 10 of 10 files at r4, 3 of 11 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[pkg/migrations/migrations.go, line 52 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-Kekc7Q2jjPlIpLZBgHL:-KeoHk40vRxvV0S9b86D:bmdyjnf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5816ad2148a7ba6e7daa996fe2620ccadf927c57/pkg/migrations/migrations.go#L52)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

No problem! Done.
</blockquote></details>

Did you fix this in the wrong commit? I think you might have. To avoid this mistake, consider reordering "server: compute expected initial ranges based on completed migrations" before "sql: add system.jobs table to track progress of long-running jobs ".

---

*[pkg/migrations/migrations.go, line 67 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-KeoJQhRcismv6wldGh-:-KeoJQhRcismv6wldGh0:b-dpe3wq) ([raw file](https://github.com/cockroachdb/cockroach/blob/11d62410bc8aeb255dc0b229068f6357902ca2d1/pkg/migrations/migrations.go#L67)):*
> ```Go
> 	// while running it.
> 	workFn func(context.Context, runner) error
> 	// newDescriptors counts the number of additional descriptors that would be
> ```

s/counts/returns/

---

*[pkg/migrations/migrations_test.go, line 119 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-KeoI4J7c9TBWIFEiuES:-KeoI4J7c9TBWIFEiuET:b-jvoeyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5816ad2148a7ba6e7daa996fe2620ccadf927c57/pkg/migrations/migrations_test.go#L119)):*
> ```Go
> 
> func (f *fakeDB) Txn(context.Context, func(txn *client.Txn) error) error {
> 	return errors.New("unimplemented")
> ```

and this is fine? Doesn't that mean it's not exercised?

---

*[pkg/server/testserver.go, line 330 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-KeoJ2NJU7Pw0jSGJCS3:-KeoJ2NJU7Pw0jSGJCS4:b-l8940l) ([raw file](https://github.com/cockroachdb/cockroach/blob/11d62410bc8aeb255dc0b229068f6357902ca2d1/pkg/server/testserver.go#L330)):*
> ```Go
> 		context.Background(), db)
> 	if err != nil {
> 		panic("failed to retrieve number of ranges added by migrations")
> ```

why not include the error in this message? why not return an error from this function? `return errors.Wrap(err, ...)`?

---

*[pkg/sql/sqlbase/system.go, line 149 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-KeoIQSWoeWo3asnYaw3:-KeoIQSWoeWo3asnYaw4:b1tq2kt) ([raw file](https://github.com/cockroachdb/cockroach/blob/5816ad2148a7ba6e7daa996fe2620ccadf927c57/pkg/sql/sqlbase/system.go#L149)):*
> ```Go
> // reasons only!
> //
> // If we supported backwards-incompatible migrations, pruning allowed privileges
> ```

consider relocating this comment such that it guards exactly the relevant tables below; this is more likely to prevent future mistakes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995)*

**Comment by tamird** [comment]
Reviewed 5 of 11 files at r5.
Review status: all files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995)*

**Comment by benesch** [comment]
After further digging I don't think this will be a problem. Since 7750433, table splits will complete in under a second, even for newly-added tables. (I verified this locally; the split after the jobs table is added takes a few hundred ms.) Since `WaitForInitialSplits()` waits for up to 10s after migrations have completed we should be safe.

---

Review status: 0 of 19 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[pkg/migrations/migrations.go, line 52 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-Kekc7Q2jjPlIpLZBgHL:-Keoa2XXpju33YKxiTLy:b-62wlb7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5816ad2148a7ba6e7daa996fe2620ccadf927c57/pkg/migrations/migrations.go#L52)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Did you fix this in the wrong commit? I think you might have. To avoid this mistake, consider reordering "server: compute expected initial ranges based on completed migrations" before "sql: add system.jobs table to track progress of long-running jobs ".
</blockquote></details>

Wow, good catch. Thank you.

---

*[pkg/migrations/migrations.go, line 67 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-KeoJQhRcismv6wldGh-:-KeobuVtiAdSb-i0gXa8:bdga2bk) ([raw file](https://github.com/cockroachdb/cockroach/blob/11d62410bc8aeb255dc0b229068f6357902ca2d1/pkg/migrations/migrations.go#L67)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

s/counts/returns/
</blockquote></details>

It's a struct field, so returns is a little wonky. How about "is"?

---

*[pkg/migrations/migrations_test.go, line 119 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-KeoI4J7c9TBWIFEiuES:-Keoc21igjVdRX17OczI:bdw0jfv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5816ad2148a7ba6e7daa996fe2620ccadf927c57/pkg/migrations/migrations_test.go#L119)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

and this is fine? Doesn't that mean it's not exercised?
</blockquote></details>

`fakeDB` is an implementation of `migrations.DB` that uses an in-memory map to service `Put` and `Get`. This means we can test that the migration manager properly reads and writes completed-migration state without booting up a test server. The migration manager itself, however, never uses `db.Txn`, so `fakeDB` doesn't need a real implementation.

(Since I added a migration which needs `db.Txn`, I had to add that method to the `migrations.DB` interface. The migration `workFn` is only ever executed with a real `client.DB`, where `Txn` is properly implemented. I suppose I could also perform a `.(client.DB)` type assertion within the migration, if you think that's cleaner. Then the test code wouldn't need to declare a dummy `Txn` method.)

---

*[pkg/server/testserver.go, line 330 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-KeoJ2NJU7Pw0jSGJCS3:-Keog80FLRJb2DKRgAC5:b7lxuzo) ([raw file](https://github.com/cockroachdb/cockroach/blob/11d62410bc8aeb255dc0b229068f6357902ca2d1/pkg/server/testserver.go#L330)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why not include the error in this message? why not return an error from this function? `return errors.Wrap(err, ...)`?
</blockquote></details>

Because plumbing the error is a huge PITA. Done, though!

---

*[pkg/sql/sqlbase/system.go, line 149 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-KeoIQSWoeWo3asnYaw3:-KeofFx2M6L3Tp9rVcPJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5816ad2148a7ba6e7daa996fe2620ccadf927c57/pkg/sql/sqlbase/system.go#L149)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

consider relocating this comment such that it guards exactly the relevant tables below; this is more likely to prevent future mistakes.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-:-KeooL17LhD2S9x1Ca1c:b-er1k27)*

**Comment by vivekmenezes** [comment]
:lgtm:

---

Review status: 0 of 19 files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-:-KeosDf0lOtAs3Bx-ApM:bnfp4nl)*

**Comment by benesch** [comment]
Review status: 8 of 19 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/migrations/migrations.go, line 52 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995#-Kekc7Q2jjPlIpLZBgHL:-KeoymQjyYHJM6oCA317:bso86ij) ([raw file](https://github.com/cockroachdb/cockroach/blob/5816ad2148a7ba6e7daa996fe2620ccadf927c57/pkg/migrations/migrations.go#L52)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Any reason you decided not to reverse the two commits?
</blockquote></details>

I was amending both commits equally, such that it wasn't any more convenient to reorder them. You're right, though: the history is cleaner if I put the "server: compute initial expected ranges" commit first. So updated!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995)*

**Comment by tamird** [comment]
Reviewed 1 of 11 files at r10, 10 of 10 files at r12.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13995)*

**Comment by benesch** [comment]
TFTRs!

**Pull request merged**
