### PR TITLE
release-24.1: go.mod: bump Pebble to 888a1185f73a

### PR DESCRIPTION
**Pull request by RaduBerinde**
CC @cockroachdb/release 
Release justification: includes fix for https://github.com/cockroachdb/pebble/issues/3459 which blocks Online Restore.

Changes:

 * [`888a1185`](https://github.com/cockroachdb/pebble/commit/888a1185) metamorphic: fix TestLoadPrecedingKeys
 * [`eae0efc2`](https://github.com/cockroachdb/pebble/commit/eae0efc2) db: trigger flushable ingest in TestDeterminism
 * [`cc5b658d`](https://github.com/cockroachdb/pebble/commit/cc5b658d) db: minor jobID cleanup
 * [`295c0099`](https://github.com/cockroachdb/pebble/commit/295c0099) db: cancel compactions that overlap with flushable ingest+excise
 * [`a306d7e0`](https://github.com/cockroachdb/pebble/commit/a306d7e0) db: add TestDeterminism
 * [`d3f89bff`](https://github.com/cockroachdb/pebble/commit/d3f89bff) manifest: cleaner implementation of assertNotL0Cmp
 * [`1c7bcd1c`](https://github.com/cockroachdb/pebble/commit/1c7bcd1c) manifest: add a helper for iterating through all levels
 * [`a9087af9`](https://github.com/cockroachdb/pebble/commit/a9087af9) manifest: assert that we don't use Seek on L0 LevelMetadata
 * [`4f4be429`](https://github.com/cockroachdb/pebble/commit/4f4be429) metamorphic: disable download op
 * [`e9624315`](https://github.com/cockroachdb/pebble/commit/e9624315) base: add AssertionFailedf wrapper
 * [`016ef889`](https://github.com/cockroachdb/pebble/commit/016ef889) metamorphic: run the level checker less frequently
 * [`1dc54dfd`](https://github.com/cockroachdb/pebble/commit/1dc54dfd) metamorphic: add timestamps to logs
 * [`34502438`](https://github.com/cockroachdb/pebble/commit/34502438) db: label download compactions logs
 * [`e28836ed`](https://github.com/cockroachdb/pebble/commit/e28836ed) sstable: handle synthetic suffix when using CopySpan
 * [`b6e563f6`](https://github.com/cockroachdb/pebble/commit/b6e563f6) wal: synchronously verify secondary is writable

Release note: none.
Epic: none.

### CODE REVIEW

**Review by msbutler — APPROVED** [review]

**Review by itsbilal — APPROVED** [review]
LGTM

Another release justification: Fixes #121263 which is a release blocker.

**Comment by msbutler** [comment]
Steven's on pto, so I can be the sub DR TL

**Review by jbowens — APPROVED** [review]
lgtm

**Comment by RaduBerinde** [comment]
Thanks for the approvals!!

bors r+

**Pull request merged**
