### PR TITLE
cli: remove the "debug kv" commands

### LINKED ISSUE #14842: What does it mean by start key must be greater than LocalMax?
**QUESTION**

I got this error below, when I runs internal client command `cockroach kv scan "" "2"`.
"Error: start key in [/Min,/System/tsd/cr.store.replicas.commandqueue.combinedqueuesize/1/10s/2017-04-10T08:00:00Z) must be greater than LocalMax"

It seems empty start key is not allowed, what's LocalMax?

### PR DESCRIPTION
**Pull request by petermattis**
Removed the use of `debug kv scan` from the reference tests. Those scans
were not doing what the author thought they were doing as `kv scan` with
no arguments only scans the "user data
span" (i.e. [/System/Max,/Table/Min]).

Fixes #14842

### CODE REVIEW

**Comment by mberhault** [comment]
LGTM. nice!

**Comment by a-robinson** [comment]
Reviewed 7 of 9 files at r1.
Review status: 7 of 9 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/acceptance/reference_test.go, line 166 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14857#-KhYsEm6utb2ZtJ7pTsV:-KhYsEm7lHoFf5j3882J:bhvl409) ([raw file](https://github.com/cockroachdb/cockroach/blob/11dc0eb2ba30a4d99c68f5efe5617e44f87703f8/pkg/acceptance/reference_test.go#L166)):*
> ```Go
> export COCKROACH_SKIP_UPDATE_CHECK=1
> $bin start --alsologtostderr=INFO --background --store=/cockroach-data-reference-7429 &> out
> $bin debug kv scan
> ```

We should probably replace this with some other command that verifies the cluster is working. A basic SQL query would be better than nothing

---

*[pkg/cli/cli_test.go, line 356 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14857#-KhYsg9XZqJr-aqnzwD1:-KhYsg9XZqJr-aqnzwD2:b-wmd754) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bfdc332653df9598cccfd7e08e979204fd5efc9/pkg/cli/cli_test.go#L356)):*
> ```Go
> }
> 
> // func Example_ranges() {
> ```

What are all the commented-out tests being kept around for? For someone to fix after 1.0 or something? A TODO would help clarify.

---

*[pkg/cli/context.go, line 204 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14857#-KhYt4XO1Cu7QARSXp1F:-KhYt4XO1Cu7QARSXp1G:b-pc9va3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bfdc332653df9598cccfd7e08e979204fd5efc9/pkg/cli/context.go#L204)):*
> ```Go
> 		return "", errors.Wrapf(err, "invalid argument %q", arg)
> 	}
> 	if disallowSystem && strings.HasPrefix(s, "\x00") {
> ```

This check doesn't really seem like it belongs here. Why should an `unquoteArg` method care about whether it's been provided with a system key?

---

*[pkg/cli/flags.go, line 418 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14857#-KhYtGB8xkEySpPGaCa0:-KhYtGB8xkEySpPGaCa1:blsxqwe) ([raw file](https://github.com/cockroachdb/cockroach/blob/11dc0eb2ba30a4d99c68f5efe5617e44f87703f8/pkg/cli/flags.go#L418)):*
> ```Go
> 
> 	// Max results flag for scan, reverse scan, and range list.
> 	for _, cmd := range []*cobra.Command{scanCmd, reverseScanCmd, lsRangesCmd} {
> ```

You can simplify this loop now (if you're gonna have to go through another CI run anyway)

---

*[pkg/cli/start.go, line 586 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14857#-KhYtc7aC_DUK5ZHrr68:-KhYtc7aC_DUK5ZHrr69:bac5w2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bfdc332653df9598cccfd7e08e979204fd5efc9/pkg/cli/start.go#L586)):*
> ```Go
> }
> 
> func addrWithDefaultHost(addr string) (string, error) {
> ```

This isn't being used by anything. What's it for? I'm concerned about it potentially getting out of sync with logic elsewhere, like in `getClientGRPCConn` below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14857)*

**Comment by petermattis** [comment]
Review status: 6 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/acceptance/reference_test.go, line 166 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14857#-KhYsEm6utb2ZtJ7pTsV:-KhZ2gEpEDelOl2iQsP-:b-5pwc2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/11dc0eb2ba30a4d99c68f5efe5617e44f87703f8/pkg/acceptance/reference_test.go#L166)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

We should probably replace this with some other command that verifies the cluster is working. A basic SQL query would be better than nothing
</blockquote></details>

Yeah, let me add something. Notice that the previous command was essentially a no-op (it never returned any data), but at least it did something.

---

*[pkg/cli/cli_test.go, line 356 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14857#-KhYsg9XZqJr-aqnzwD1:-KhZ2tp6ioVwnOVPZTqx:b-lzkesd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bfdc332653df9598cccfd7e08e979204fd5efc9/pkg/cli/cli_test.go#L356)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

What are all the commented-out tests being kept around for? For someone to fix after 1.0 or something? A TODO would help clarify.
</blockquote></details>

Oops, I meant to fix this up. Because we're removing the `debug kv` commands I need to create data in a different way. I'll ping this PR again when I get this fixed up.

---

*[pkg/cli/context.go, line 204 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14857#-KhYt4XO1Cu7QARSXp1F:-KhZ3RzAtpalWlEUP1jH:b-88pxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bfdc332653df9598cccfd7e08e979204fd5efc9/pkg/cli/context.go#L204)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

This check doesn't really seem like it belongs here. Why should an `unquoteArg` method care about whether it's been provided with a system key?
</blockquote></details>

We never even pass in `disallowSystem == true`. Removed.

---

*[pkg/cli/flags.go, line 418 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14857#-KhYtGB8xkEySpPGaCa0:-KhZ3j11Sv-16--Q5qZ-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/11dc0eb2ba30a4d99c68f5efe5617e44f87703f8/pkg/cli/flags.go#L418)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

You can simplify this loop now (if you're gonna have to go through another CI run anyway)
</blockquote></details>

Done.

---

*[pkg/cli/start.go, line 586 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14857#-KhYtc7aC_DUK5ZHrr68:-KhZ2YeZJx2zConHnaZO:b-j0cnxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bfdc332653df9598cccfd7e08e979204fd5efc9/pkg/cli/start.go#L586)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

This isn't being used by anything. What's it for? I'm concerned about it potentially getting out of sync with logic elsewhere, like in `getClientGRPCConn` below
</blockquote></details>

This is used by `getClientGRPCConn`. I moved it here for precisely that reason. Am I misunderstanding your comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14857)*

**Comment by a-robinson** [comment]
Reviewed 1 of 9 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/cli/start.go, line 586 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14857#-KhYtc7aC_DUK5ZHrr68:-KhZ6p5Q_6d1HA6TOTkF:bqtf978) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bfdc332653df9598cccfd7e08e979204fd5efc9/pkg/cli/start.go#L586)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This is used by `getClientGRPCConn`. I moved it here for precisely that reason. Am I misunderstanding your comment?
</blockquote></details>

Ah LGTM. I thought this was being newly added, I didn't see it was being moved from kv.go

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14857)*

**Comment by petermattis** [comment]
Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/cli/cli_test.go, line 356 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14857#-KhYsg9XZqJr-aqnzwD1:-KhZIHLwI37rwCfh8B9j:bncgqri) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bfdc332653df9598cccfd7e08e979204fd5efc9/pkg/cli/cli_test.go#L356)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Oops, I meant to fix this up. Because we're removing the `debug kv` commands I need to create data in a different way. I'll ping this PR again when I get this fixed up.
</blockquote></details>

This has been fixed. I just needed to remove the usage of the `debug kv` commands.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14857)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14857#-:-Kh_7vfVlqgDRQcc2M7J:bnfp4nl)*

**Pull request merged**
