### PR TITLE
storage: cherry pick changes from develop

### PR DESCRIPTION
**Pull request by tamird**
These are the big items that have gone into develop, which are currently conflicting with the master -> develop merge.

Scrutiny is needed here. @cockroachdb/stability

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9334)

### CODE REVIEW

**Comment by eisenstatdavid** [comment]
LGTM

LGTM for my consistency on frozen ranges commit.

---

Review status: 0 of 18 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[roachpb/batch.go, line 65 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9334#-KR_--saxZavxxDg0Vx_:-KR_--sb-ZwEurNgSrW3:b-hisl8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddad90d5d85a28389dac3b9f76acd568b8a57f0c/roachpb/batch.go#L65)):*
> ```Go
> 
> // IsConsistencyRelated returns whether the batch consists of a single
> // ComputeChecksum or VerifyChecksum or CheckConsistency request.
> ```

s/VerifyChecksum or //

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9334#-:-KR_-5ZCTPsXWiIu8SoU:b-vb1bsy)*

**Comment by andreimatei** [comment]
LGTM

---

Review status: 0 of 18 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9334#-:-KR_0NfG59YeqACkaV9D:bb6ywmx)*

**Comment by tamird** [comment]
Review status: 0 of 18 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[roachpb/batch.go, line 65 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9334#-KR_--saxZavxxDg0Vx_:-KR_1jUVJUeIx9itzDdI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddad90d5d85a28389dac3b9f76acd568b8a57f0c/roachpb/batch.go#L65)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary>
> s/VerifyChecksum or //
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9334)*

**Comment by petermattis** [comment]
:lgtm: though can we hold off on merging until tomorrow? We've had several other changes (likely riskier than these) merge today and I'd like to see if there is any fallout from them first. 

Also, @tschottdorf should take a look.

---

Review status: 0 of 18 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9334#-:-KR_IYHc_fX1mvfirHJR:b-ebvmua)*

**Comment by bdarnell** [comment]
Reviewed 16 of 18 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 710 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9334#-KRb2QoFc3qhnyMktZi7:-KRb2QoG0EqURTif5-5w:b-95kl37) ([raw file](https://github.com/cockroachdb/cockroach/blob/33f2c086e14cc21a6c24033bccce88d1ebc78623/storage/replica.go#L710)):*
> ```Go
> func newNotLeaseHolderErrorWithGuess(
> 	rangeID roachpb.RangeID,
> 	origin roachpb.ReplicaDescriptor,
> ```

`origin` is unused. 

---

*[storage/replica.go, line 906 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9334#-KRb1lc34sd8zEXn_TD-:-KRb1lc34sd8zEXn_TD0:b-ug50vh) ([raw file](https://github.com/cockroachdb/cockroach/blob/33f2c086e14cc21a6c24033bccce88d1ebc78623/storage/replica.go#L906)):*
> ```Go
> 	if r.mu.replicaID == 0 {
> 		panic("the replica's raft group has not yet been configured (i.e. the replica " +
> 			"was created from a preemptive snapshot)")
> ```

Since #9020, this could either be a preemptive snapshot or a replica which is awaiting GC.

---

*[storage/store.go, line 2115 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9334#-KRb1yb509WpBT3hQji0:-KRb1yb509WpBT3hQji1:b-ft8pd6) ([raw file](https://github.com/cockroachdb/cockroach/blob/33f2c086e14cc21a6c24033bccce88d1ebc78623/storage/store.go#L2115)):*
> ```Go
> 					// The replica must have a ReplicaID, even though it's uninitialized.
> 					// Otherwise, it would mean that it's not part of a Raft group which
> 					// would mean that we wouldn't have routed a request to it.
> ```

Untrue after #9020: a replica awaiting GC could have had a request routed to it thanks to stale information in various caches. This needs to have proper error handling instead of panicking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9334)*

**Comment by tamird** [comment]
Review status: 16 of 18 files reviewed at latest revision, 3 unresolved discussions.

---

*[storage/replica.go, line 710 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9334#-KRb2QoFc3qhnyMktZi7:-KRbJ6S1cN0rkz9tHeSf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/33f2c086e14cc21a6c24033bccce88d1ebc78623/storage/replica.go#L710)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> `origin` is unused. 
</details>
Done.

---

*[storage/replica.go, line 906 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9334#-KRb1lc34sd8zEXn_TD-:-KRbLQK8F8Mz2zeU5Hlr:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/33f2c086e14cc21a6c24033bccce88d1ebc78623/storage/replica.go#L906)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Since #9020, this could either be a preemptive snapshot or a replica which is awaiting GC.
</details>
Removed.

---

*[storage/store.go, line 2115 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9334#-KRb1yb509WpBT3hQji0:-KRbLKojW4gR7IRXjGdx:bmpcmn8) ([raw file](https://github.com/cockroachdb/cockroach/blob/33f2c086e14cc21a6c24033bccce88d1ebc78623/storage/store.go#L2115)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Untrue after #9020: a replica awaiting GC could have had a request routed to it thanks to stale information in various caches. This needs to have proper error handling instead of panicking.
</details>
Doesn't actually seem to matter - this is only used for the error's string representation. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9334)*

**Comment by bdarnell** [comment]
LGTM

**Comment by tschottdorf** [comment]
Review status: 16 of 18 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[storage/replica.go, line 1455 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/9334#-KRd6x_Hw81_LJzmwAfe:-KRd6x_ICQ322yuDPcTB:b-amun8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcf71d3300a87ec5ea1b56bb8b449a9cfda6db85/storage/replica.go#L1455)):*
> ```Go
> 	ctx context.Context, ba roachpb.BatchRequest,
> ) (br *roachpb.BatchResponse, pErr *roachpb.Error) {
> 	isNonKV := ba.IsSingleNonKVRequest()
> ```

All of these random single-use intricacies make me sad.

---

*[storage/replica.go, line 1475 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/9334#-KRd70aPO42neqGxJuAP:-KRd70aPO42neqGxJuAQ:b2mvwtj) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcf71d3300a87ec5ea1b56bb8b449a9cfda6db85/storage/replica.go#L1475)):*
> ```Go
> 	}
> 
> 	if !ba.IsSingleSkipLeaseCheckRequest() {
> ```

This one too. Well, the damage is done.

---

*[storage/replica_command.go, line 3302 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/9334#-KRd8k4nl320ah7gWlbd:-KRd8k4nl320ah7gWlbe:b-bpt2d7) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcf71d3300a87ec5ea1b56bb8b449a9cfda6db85/storage/replica_command.go#L3302)):*
> ```Go
> // If there's no active lease (or at least this replica is not yet aware of
> // one), the replica tries to acquire the lease.
> func (r *Replica) LeaseInfo(
> ```

This is a "read-only command" which is apparently only ever used inconsistently, but it should still have some basic respect for the state machine and not use `r.store.Clock()`. But it also issues a Raft command (`redirectOnOrAcquireLease`) so it's clearly not a read-only command but some weird mutant. I don't understand how this got merged in its current form.
I suggest reverting this and reworking the PR that introduced it. In particular, it seems that LeaseInfo could easily be an AdminRequest which would obviate the need for `isNonKV` and (perhaps) `leaseCheck`. If there are pressing reasons for which all of this bulldozing through concepts and abstractions is necessary, I didn't see them discussed in the origin PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9334)*

**Comment by tamird** [comment]
@tschottdorf your comments apply to changes introduced in both #8310 and #8752. I haven't reviewed these changes myself, but I would prefer to revert them than to blindly cherry pick them in or attempt to address your comments here.

@cockroachdb/stability anyone care to weigh in?

---

Review status: 16 of 18 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9334#-:-KRdC7hAPyo6VyvbJvWU:b-rulc6z)*

**Comment by tschottdorf** [comment]
My quarrels are primarily with #8752 (though #8310 also seems half-baked).

---

Review status: 16 of 18 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9334#-:-KRdFwR6BMWu-dawf91A:b-wtm3zq)*

**Comment by tschottdorf** [comment]
We're waiting for a commit to `develop` which addresses the concerns which can then be included here.

---

Review status: 16 of 18 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9334#-:-KRdiz9cPHJ4dTUqTpI6:bfsmcp5)*

**Comment by andreimatei** [comment]
that commit is https://github.com/cockroachdb/cockroach/pull/9367

---

Review status: 16 of 18 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[storage/replica_command.go, line 3302 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/9334#-KRd8k4nl320ah7gWlbd:-KRe4hrOKGJptFtSQYzs:bwr7tlp) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcf71d3300a87ec5ea1b56bb8b449a9cfda6db85/storage/replica_command.go#L3302)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> This is a "read-only command" which is apparently only ever used inconsistently, but it should still have some basic respect for the state machine and not use `r.store.Clock()`. But it also issues a Raft command (`redirectOnOrAcquireLease`) so it's clearly not a read-only command but some weird mutant. I don't understand how this got merged in its current form.
> I suggest reverting this and reworking the PR that introduced it. In particular, it seems that LeaseInfo could easily be an AdminRequest which would obviate the need for `isNonKV` and (perhaps) `leaseCheck`. If there are pressing reasons for which all of this bulldozing through concepts and abstractions is necessary, I didn't see them discussed in the origin PR.
</details>
removed the acquiring of the lease part of the command in another PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9334#-:-KRe4wI4KygpemKqbc2K:b-bw0iqi)*

**Comment by tamird** [comment]
Updated, PTAL.

**Comment by tschottdorf** [comment]
:lgtm: for the code. For merging cc @petermattis, is this good to go or any reason to hold off?

---

Reviewed 10 of 18 files at r1, 5 of 9 files at r5, 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9334#-:-KReHnHVJeDMf455Uw_j:b-8a6vb)*

**Comment by petermattis** [comment]
I didn't review, but no reason to hold off now.

**Pull request merged**
