### PR TITLE
upgrades: remove unused struct field

### PR DESCRIPTION
**Pull request by stevendanna**
Epic: None

Release note: None

### CODE REVIEW

**Comment by postamar** [comment]
I don't know about this. I think this release is the exception more than the rule; we have upgrade steps which perform descriptor migrations more often than not.

**Comment by stevendanna** [comment]
@postamar Ah, that makes sense.  I was thinking that most things that interact with descriptors would be using `descs.TxnManager` which is also on this struct, but that is probably just my ignorance.

**Review by ajwerner — APPROVED** [review]
:lgtm: this is right. I think @postamar missed the `descs.TxnManager` refactor which merged yesterday

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89257#-:-NDZonTFBLCY91IAY156:b-5r9ynz)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by postamar** [comment]
TIL!

**Pull request merged**
