### PR TITLE
storage: Consider recently-added replicas healthy when rebalancing

### LINKED ISSUE #17879: storage: replicate queue has tendency to remove just-added replicas
1. After the replicate queue adds a new replica as part of a rebalance, it immediately re-queues the replica for processing so that it can choose to remove a replica.
2. As part of choosing which replica to remove, we [filter from consideration any replicas that are necessary for the range's quorum](https://github.com/cockroachdb/cockroach/blob/0bd7166888aedecab40a1f6f4f1c8385c2e11c97/pkg/storage/replicate_queue.go#L341). This filtering compares the raft commit index from each replica to the quorum commit index, considering any replicas even a single commit behind not part of the quorum.

Both of these actions are reasonable, but they interact poorly in high-latency clusters or any cluster where one of the previously existing replicas was lagging behind. The problem is that in many cases, the newly added replica won't have finished receiving/applying its snapshot and catching up (or at least the leaseholder isn't yet aware that it has done so), and so if any of the other replicas is also behind (as can easily happen on indigo where the nodes are different distances apart) then those two behind replicas are the only ones we'll consider removing. The other two replicas are considered necessary for the quorum since they're the only two that are up-to-date.

This unfortunate behavior can easily lead to thrashing if the replica that the allocator wanted to rebalance away from is one of the two that can't be removed. This affects both stats-based rebalancing and the range-count form of rebalancing, although its effect is more severe for stats-based rebalancing. It happens very reliably whenever running indigo with no data other than the timeseries ranges.

We could fix it in a few different ways, but we might not want to so close to 1.1. If we don't fix it, we'll definitely have to disable stats-based rebalancing by default (https://github.com/cockroachdb/cockroach/issues/17645).

The first approaches to fixing that come to mind:

1. Wait before re-queueing after doing a rebalance. We could just wait for a set amount of time on the order of seconds, or for a dynamic time estimated based on how long the snapshot should take, or we could poll the range state until the new replica gets caught up. These approaches would all be susceptible to the Scanner re-adding the replica to the replicate queue, circumventing the wait.
1. Be less harsh in `filterUnremovableReplicas`. If a replica is less than N commits behind, don't rule it out. If we did this, then even if an existing replica is behind by a commit or two there will still be 3 valid replicas, meaning any replica can be behind even if the new replica hasn't caught up.

I like 2, but may be forgetting a reason why we can't loosen that up. I thought we used to allow a cushion here, but we clearly don't right now. @petermattis

### PR DESCRIPTION
**Pull request by a-robinson**
Fixes #17879 

For what it's worth, this is running on indigo in the exact same configuration as before and I'm no longer seeing the problem.

### CODE REVIEW

**Comment by BramGruneir** [comment]
So if we add 2 or more replicas quickly, this will only consider the last one to be "new".  
What about just keeping a list of the recently added replicas and a timestamp, so we can just filter out the older ones? 

What happens if there's a leadership change right after a replica is added.  This (tiny) history won't be persisted right?

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/storage/replicate_queue.go, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930#-KsPpcDMnllSqG7C35yf:-KsPpcDMnllSqG7C35yg:b-ezn4ha) ([raw file](https://github.com/cockroachdb/cockroach/blob/39ea3684f3f2c64474603b54c3c9250dbfb4748a/pkg/storage/replicate_queue.go#L50)):*
> ```Go
> 	// replica's raft state to catch up to the leader's before we start
> 	// considering it to be behind for the sake of rebalancing.
> 	newReplicaGracePeriod = 5 * time.Minute
> ```

This is quite long.  Perhaps 1 min?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930#-:-KsPpxaU7xYfY8Eav06e:bf9fl1r)*

**Comment by a-robinson** [comment]
Is it worth the extra complexity? There aren't very many situations in which we add two or more replicas in quick succession. It certainly shouldn't be the case in the steady state once a cluster has finished up-replicating, which is what we need to protect to avoid thrashing.

A leadership change shouldn't affect anything. All replicas update their descriptor through this code path, not just the leader, so they'll all know that the new replica is new.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/storage/replicate_queue.go, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930#-KsPpcDMnllSqG7C35yf:-KsPu9-6OwRfF56rwWDf:bhc7hby) ([raw file](https://github.com/cockroachdb/cockroach/blob/39ea3684f3f2c64474603b54c3c9250dbfb4748a/pkg/storage/replicate_queue.go#L50)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This is quite long.  Perhaps 1 min?
</blockquote></details>

It is quite long, but snapshots can take quite long in high latency clusters, where this is most likely to be needed. And I don't feel like making this a little longer than usually needed is dangerous, given that it only applies when the new replica's commit index is 0.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930#-:-KsPtf1RXsY2lanQ3ZwZ:b-361jec)*

**Comment by BramGruneir** [comment]
LGTM

Can you amend your comment to mention that this is specifically designed to address rebalance thrashing in high latency scenarios?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930#-:-KsPvCJggp9vSaBTMqFZ:b-qndidv)*

**Comment by BramGruneir** [comment]
The comments in the code that is.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930#-:-KsPvcXLSWxOXJdlhxZg:b6x278s)*

**Comment by a-robinson** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930#-KsPyZEG31rV8GZaHIfi:-KsPyZEG31rV8GZaHIfj:b-896fix) (no related file):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930)*

**Comment by petermattis** [comment]
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/storage/allocator.go, line 851 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930#-KsQ0qF6bdoKsCoaTGcU:-KsQ0qF6bdoKsCoaTGcV:brvl3ah) ([raw file](https://github.com/cockroachdb/cockroach/blob/acb45de53df9cc62a9b3b1b34a1d6035dd285139/pkg/storage/allocator.go#L851)):*
> ```Go
> // slice. A "behind" replica is one which is not at or past the quorum commit
> // index. We forgive brandNewReplicaID for being at commit index 0, indicating
> // that it's so new it hasn't finished initialized yet.
> ```

`s/initialized/initializing/g`

---

*[pkg/storage/allocator.go, line 874 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930#-KsQ1DyBiKNl3ITC9HcQ:-KsQ1DyBiKNl3ITC9HcR:b-xt7f05) ([raw file](https://github.com/cockroachdb/cockroach/blob/acb45de53df9cc62a9b3b1b34a1d6035dd285139/pkg/storage/allocator.go#L874)):*
> ```Go
> 				(progress.State == raft.ProgressStateReplicate &&
> 					progress.Match >= raftStatus.Commit) ||
> 				(progress.Match == 0 && r.ReplicaID == brandNewReplicaID) {
> ```

I'm surprised the `progress.Match == 0` check is sufficient. Even after the snapshot the replica might be behind as it undergoes replaying the portion of the Raft log that was created since the snapshot was created. I was imagining this would consider the brand new replica up to date but that we'd clear the `lastReplicaAdded` time when that replica did catch up (which will usually happen much faster than 5min).

---

*[pkg/storage/allocator.go, line 886 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930#-KsQ14hzXXpIXB_LVgue:-KsQ14hzXXpIXB_LVguf:brvl3ah) ([raw file](https://github.com/cockroachdb/cockroach/blob/acb45de53df9cc62a9b3b1b34a1d6035dd285139/pkg/storage/allocator.go#L886)):*
> ```Go
> // quorum that will result from removing 1 replica. We forgive brandNewReplicaID
> // for being at commit index 0, indicating that it's so new it hasn't finished
> // initialized yet. This is important when we've just added a replica in order
> ```

`s/initialized/initializing/g`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930)*

**Comment by a-robinson** [comment]
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/storage/allocator.go, line 851 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930#-KsQ0qF6bdoKsCoaTGcU:-KsQ7-5FeYYCYhNJToRf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/acb45de53df9cc62a9b3b1b34a1d6035dd285139/pkg/storage/allocator.go#L851)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/initialized/initializing/g`
</blockquote></details>

Done.

---

*[pkg/storage/allocator.go, line 874 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930#-KsQ1DyBiKNl3ITC9HcQ:-KsQ70UMNG3HQlFFsje-:b3kt5tk) ([raw file](https://github.com/cockroachdb/cockroach/blob/acb45de53df9cc62a9b3b1b34a1d6035dd285139/pkg/storage/allocator.go#L874)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm surprised the `progress.Match == 0` check is sufficient. Even after the snapshot the replica might be behind as it undergoes replaying the portion of the Raft log that was created since the snapshot was created. I was imagining this would consider the brand new replica up to date but that we'd clear the `lastReplicaAdded` time when that replica did catch up (which will usually happen much faster than 5min).
</blockquote></details>

It may be because the write load on the cluster I tested on was very low, so keeping up wasn't an issue. Where would we put the logic for clearing `lastReplicaAdded`? Tracking when a replica has caught up happens pretty deep within raft, but the replicate queue doesn't run frequently enough to really know whether the replica has ever caught up (unless it gets lucky with its timing).

We could shrink the grace period down to something like 1 minute and just allow the replica to be behind regardless of its current `Match`. That may work better on heavily loaded ranges.

There's also still the idea of being forgiving of being a few commits behind in the general case, but I understand that's a little riskier.

---

*[pkg/storage/allocator.go, line 886 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930#-KsQ14hzXXpIXB_LVgue:-KsQ7-abv2RyPMM6aFNY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/acb45de53df9cc62a9b3b1b34a1d6035dd285139/pkg/storage/allocator.go#L886)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/initialized/initializing/g`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930)*

**Comment by petermattis** [comment]
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/storage/allocator.go, line 874 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930#-KsQ1DyBiKNl3ITC9HcQ:-KsQ90wo6LRbqfhWavrB:b-hortsb) ([raw file](https://github.com/cockroachdb/cockroach/blob/acb45de53df9cc62a9b3b1b34a1d6035dd285139/pkg/storage/allocator.go#L874)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

It may be because the write load on the cluster I tested on was very low, so keeping up wasn't an issue. Where would we put the logic for clearing `lastReplicaAdded`? Tracking when a replica has caught up happens pretty deep within raft, but the replicate queue doesn't run frequently enough to really know whether the replica has ever caught up (unless it gets lucky with its timing).

We could shrink the grace period down to something like 1 minute and just allow the replica to be behind regardless of its current `Match`. That may work better on heavily loaded ranges.

There's also still the idea of being forgiving of being a few commits behind in the general case, but I understand that's a little riskier.
</blockquote></details>

The Raft quota pool code has to periodically check the progress of all replicas in order to release quota. See `Replica.updateProposalQuotaRaftMuLocked`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930)*

**Comment by a-robinson** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/storage/allocator.go, line 874 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930#-KsQ1DyBiKNl3ITC9HcQ:-Ks_H06S59zGlyfIdEmd:bp93lc7) ([raw file](https://github.com/cockroachdb/cockroach/blob/acb45de53df9cc62a9b3b1b34a1d6035dd285139/pkg/storage/allocator.go#L874)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The Raft quota pool code has to periodically check the progress of all replicas in order to release quota. See `Replica.updateProposalQuotaRaftMuLocked`.
</blockquote></details>

Thanks, done. I'm a little worried about the maintainability of this relative to just always being a forgiving about replicas added in the last minute, but it's not terrible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/storage/allocator.go, line 851 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930#-KsQ0qF6bdoKsCoaTGcU:-Ks_XkdwG2FyuT9z9Vsu:b-9mz4vp) ([raw file](https://github.com/cockroachdb/cockroach/blob/acb45de53df9cc62a9b3b1b34a1d6035dd285139/pkg/storage/allocator.go#L851)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The comment about `being at commit index 0` is now incorrect. Ditto the similar comment on `filterUnremovableReplicas`. 

---

*[pkg/storage/replica.go, line 1004 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930#-Ks_YnitXqXW_ZmldWWf:-Ks_YnitXqXW_ZmldWWg:b-cfg1os) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a386a68944fb9f876282cce7c0e42375fb3de37/pkg/storage/replica.go#L1004)):*
> ```Go
> 			// our state that was tracking it. This is unrelated to managing proposal
> 			// quota, but this is a convenient place to do so.
> 			if rep.ReplicaID == r.mu.lastReplicaAdded && progress.Match > status.Commit {
> ```

Should that be `progress.Match >= status.Commit`? That's the condition that is used in `filterBehindReplicas`. 

---

*[pkg/storage/replicate_queue.go, line 547 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930#-Ks_YG7C6YOnXqZdMuMx:-Ks_YG7C6YOnXqZdMuMy:b-yvuoyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a386a68944fb9f876282cce7c0e42375fb3de37/pkg/storage/replicate_queue.go#L547)):*
> ```Go
> 	checkCandidateFullness bool,
> ) (bool, error) {
> 	candidates := filterBehindReplicas(repl.RaftStatus(), desc.Replicas, 0 /* lastAddedRepl */)
> ```

`s/lastAddedRepl/brandNewReplicaID/g`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930#-:-Ks_Z9sF868i9oYDBF1f:bnfp4nl)*

**Comment by a-robinson** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/storage/allocator.go, line 851 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930#-KsQ0qF6bdoKsCoaTGcU:-KsdBZwKTJwllAcw6spO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/acb45de53df9cc62a9b3b1b34a1d6035dd285139/pkg/storage/allocator.go#L851)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The comment about `being at commit index 0` is now incorrect. Ditto the similar comment on `filterUnremovableReplicas`. 
</blockquote></details>

Done.

---

*[pkg/storage/replica.go, line 1004 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930#-Ks_YnitXqXW_ZmldWWf:-KsdBgIfGhEl6CNK4LOc:b-k614gu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a386a68944fb9f876282cce7c0e42375fb3de37/pkg/storage/replica.go#L1004)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Should that be `progress.Match >= status.Commit`? That's the condition that is used in `filterBehindReplicas`. 
</blockquote></details>

Yes, thanks!

---

*[pkg/storage/replicate_queue.go, line 547 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930#-Ks_YG7C6YOnXqZdMuMx:-KsdBnvQGo2SaZT6Vu8a:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a386a68944fb9f876282cce7c0e42375fb3de37/pkg/storage/replicate_queue.go#L547)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/lastAddedRepl/brandNewReplicaID/g`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17930)*

**Pull request merged**
