### PR TITLE
sql: enable setting of zone config extension

### PR DESCRIPTION
**Pull request by ZhouXing19**
Release note (sql change): This change introduces the `ALTER DATABASE database_name ALTER LOCALITY {GLOBAL|REGIONAL|REGIONAL IN} set_zone_config` syntax which allows setting the zone config extension. 
The zone config extension, introduced by #78044, "_represents per-locality zone configurations that 
influence the zone configurations derived for corresponding objects. A locality type's associated extension 
acts as a targeted set of rewrite rules for its associated objects' (database, table, partition) derived zone 
configurations._"

### CODE REVIEW

**Comment by knz** [comment]
> Release Node (SQL): enable setting for zone config extension

could you perhaps populate a [more comprehensive release note](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/186548364/Release+notes)?

**Comment by ZhouXing19** [comment]
> > Release Node (SQL): enable setting for zone config extension
> 
> could you perhaps populate a [more comprehensive release note](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/186548364/Release+notes)?

Thanks, updated, will this be more informative now?

**Comment by ZhouXing19** [comment]
Note that there're a couple of questions unsolved:
1.  Do we need to inherit zone configuration information from the parent zones?
2. To log this setting event, it should be of type `AlterDatabasePlacement` or `SetZoneConfig`?
3. Do we need to check that the extra protection partial zone configs would require changes made to parent zones?

**Comment by knz** [comment]
Regarding the release note:

1. the release note(s) should be in the individual commit messages, not the top level PR description
2. the 1st and 2nd commits in the PR do not need a release note: at this point, there is no user-facing change yet. Also the release note category "sql" is invalid.
3. point 1 above notwithstanding, the text you have written at the beginning of the PR description *is already a very good release note*
image

So I could recommend using it as-is, as follows, *in the text of the 3rd commit in the chain*:

```
Release note (sql change): This change the `ALTER DATABASE database_name ALTER LOCALITY {GLOBAL|REGIONAL|REGIONAL IN} set_zone_config` syntax which allows setting the zone config extension. 
The zone config extension, introduced by #78044, "_represents per-locality zone configurations that 
influence the zone configurations derived for corresponding objects. A locality type's associated extension 
acts as a targeted set of rewrite rules for its associated objects' (database, table, partition) derived zone 
configurations._"
```

then you do not need anything else.

**Comment by knz** [comment]
For the benefit of the docs writer, you may then need to extend the release note with the answers to your first questions:
1. indicate whether the zcfg gets inherited
2. indicate what type of structured logging event reports the change

**Comment by ZhouXing19** [comment]
Thanks! Updated the release notes for commits.
Will re-update them when the questions above are solved.

**Review by RichardJCai — APPROVED** [review]
Nice work! I'd update the commit message with some more examples though so it's more clear for docs.

**Review by nvb — COMMENTED** [review]
Great job @zhouxing19!

> Reviewed 3 of 8 files at r1, 1 of 8 files at r9, 11 of 11 files at r10, 4 of 4 files at r11, 6 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-:-N7P1QQN8EBasFmFI5Wj:b-3h85be)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @ZhouXing19)

___
*[`-- commits` line 2 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N7OwuOv4OF4UPJU4vzA):*
s/syntext/syntax/
___
*[`-- commits` line 6 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N7Ox1Ez89uUxBVVBAhn):*
s/implemente/implemented/
___
*[`-- commits` line 21 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N7OyQ3c50h1jsgyrGVr):*
Nice!
___
*[`pkg/sql/alter_database.go` line 1739 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N7P-VA92VxQoLsWIdWi:-N7P-VA92VxQoLsWIdWj:brumtvd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fe6beed405c458719d6c6fac8f0c435b8d8acf8/pkg/sql/alter_database.go#L1739)):*
> ```Go
> 
> 	//TODO(janexing): do we need to inherit zone configuration information
> 	//from parent?
> ```

Which parent are you referring to?
___
*[`pkg/sql/alter_database.go` line 1840 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N7P1d9oBJvzxTe_ct_P:-N7P1d9oBJvzxTe_ct_Q:b8jzcgy) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fe6beed405c458719d6c6fac8f0c435b8d8acf8/pkg/sql/alter_database.go#L1840)):*
> ```Go
> 		if err := validateZoneAttrsAndLocalities(params.ctx, params.p.ExecCfg(), newZone); err != nil {
> 			return err
> 		}
> ```

We had talked about validating that zone config extensions weren't undermining the meaning of the multi-region primitives, to prevent users from shooting themselves in the foot. We can't be exhaustive here, but a set of simple checks could go a long way. For instance, we could validate that:
1. REGIONAL extensions don't set leaseholder_preferences
2. REGIONAL IN extensions don't set leaseholder_preferences that disagree with their home region
3. REGIONAL IN extensions don't set replica constraints or voter contains that disagree with their home region 
4. Extensions can't break a database's survivability goal

We don't need to add this all in in the first pass and maybe we don't want to add any of this here, but do we have a plan to add the framework for such validation?
___
*[`pkg/sql/alter_database.go` line 1848 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N7P0Ip62sTKpvFIxq0p:-N7P0Ip62sTKpvFIxq0q:bv406ck) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fe6beed405c458719d6c6fac8f0c435b8d8acf8/pkg/sql/alter_database.go#L1848)):*
> ```Go
> 
> 		// WIP: (nvanbenschoten) do we want to do this?
> 		// (janexing): I don't think so, since the newZone here is not the final
> ```

I think you are correct, because we should hit any zone config validation error down below when we call `refreshZoneConfigsForTables`. Does this mean we can also get rid of the call to `newZone.Validate()`?
___
*[`pkg/sql/alter_database.go` line 1926 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N7P1A0XDLkaBCqN1nZC:-N7P1A0XDLkaBCqN1nZD:b6t61yw) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fe6beed405c458719d6c6fac8f0c435b8d8acf8/pkg/sql/alter_database.go#L1926)):*
> ```Go
> 	} else {
> 		// TODO(janexin): it should be AlterDatabasePlacement or SetZoneConfig?
> 		// or we should make a new event type for it?
> ```

I think we should make a new event type for it.
___
*[`pkg/sql/sem/tree/alter_database.go` line 193 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N7Oxr3R4F5ajYf6cl2P:-N7Oxr3R4F5ajYf6cl2Q:b12z2d3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a3a0144beeb3f9f531041ceb60642821f5beedc/pkg/sql/sem/tree/alter_database.go#L193)):*
> ```Go
> 	RegionName    Name
> 	// CONFIGURE ZONE ...
> 	SetDefault bool
> ```

It may make sense to unify these three fields and their corresponding formatting logic with those in `SetZoneConfig` to avoid duplication. What do you think?
___
*[`pkg/sql/sem/tree/alter_database.go` line 211 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N7OykyK0jqZ-WGFr0wa:-N7OykyK0jqZ-WGFr0wb:b-o6ki5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfa02f89f3eadd1b67457315f3881ba69b5b26f9/pkg/sql/sem/tree/alter_database.go#L211)):*
> ```Go
> 
> // ZoneConfigSettings contains methods for zone config setting statement.
> type ZoneConfigSettings interface {
> ```

Depending on whether or not we want to pull out a separate struct to hold the three zone configuration-related fields (see the comment above), we might not need this interface.

For instance, an option would be:
```go
type ZoneConfigSettings struct {
	SetDefault bool
	YAMLConfig Expr
	Options    KVOptions
}

type SetZoneConfig struct {
	ZoneSpecifier
	// AllIndexes indicates that the zone configuration should be applied across
	// all of a tables indexes. (ALTER PARTITION ... OF INDEX <tablename>@*)
	AllIndexes bool
	ZoneConfigSettings
}

type AlterDatabaseSetZoneConfigExtension struct {
	// ALTER DATABASE ...
	DatabaseName Name
	// ALTER LOCALITY ...
	LocalityLevel LocalityLevel
	RegionName    Name
	// CONFIGURE ZONE ...
	ZoneConfigSettings
}
```

EDIT: I think that's actually what you started to do with `ZoneConfigAndOptions`, but it doesn't look like it went all the way.
___
*[`pkg/ui/yarn-vendor` line 1 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N7OyAYv7YV9M3mIltl5:-N7OyAYv7YV9M3mIltl6:b-qhkf32) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a3a0144beeb3f9f531041ceb60642821f5beedc/pkg/ui/yarn-vendor#L1)):*
> ```
> Subproject commit d90a7808831f2a1aaa87b14e211fb8970303577e
> ```

Did you mean to change this?

**Review by ZhouXing19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83605)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`-- commits` line 2 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N7OwuOv4OF4UPJU4vzA):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

s/syntext/syntax/
</blockquote></details>

Done.
___
*[`-- commits` line 6 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N7Ox1Ez89uUxBVVBAhn):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

s/implemente/implemented/
</blockquote></details>

Done.
___
*[`pkg/sql/alter_database.go` line 1739 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N7P-VA92VxQoLsWIdWi:-N7WPBlt2aEBcT1kOFAj:b-k03s7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fe6beed405c458719d6c6fac8f0c435b8d8acf8/pkg/sql/alter_database.go#L1739)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Which parent are you referring to?
</blockquote></details>

The second returned value of `evaluateZoneOptions(n.options, params)` is a list of options to copy from parents. It's constructed by checking the zone config options from the `options` map, and collecting those with `inheritValue == true`. This `copyFromParentList` is used when setting a zone config, but I don't think we want to use it for zone config extension, because  IIUC`inheritValue` is set true only when the value of the option is `nil`. I don't think it makes sense if we allow a `nil` zone config expression in the `ALTER DATABASE ... ALTER LOCALITY...` statement. What do you think?
___
*[`pkg/sql/alter_database.go` line 1840 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N7P1d9oBJvzxTe_ct_P:-N7XVWJoD117Z9THOvBn:b-pv0kz4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fe6beed405c458719d6c6fac8f0c435b8d8acf8/pkg/sql/alter_database.go#L1840)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We had talked about validating that zone config extensions weren't undermining the meaning of the multi-region primitives, to prevent users from shooting themselves in the foot. We can't be exhaustive here, but a set of simple checks could go a long way. For instance, we could validate that:
1. REGIONAL extensions don't set leaseholder_preferences
2. REGIONAL IN extensions don't set leaseholder_preferences that disagree with their home region
3. REGIONAL IN extensions don't set replica constraints or voter contains that disagree with their home region 
4. Extensions can't break a database's survivability goal

We don't need to add this all in in the first pass and maybe we don't want to add any of this here, but do we have a plan to add the framework for such validation?
</blockquote></details>

Yes I agree that such validation is needed, but I think maybe we should put it after we built a new a zone config based on the RegionConfig information? Put the TODO in `func zoneConfigForMultiRegionDatabase()` and made issue https://github.com/cockroachdb/cockroach/issues/85015.
___
*[`pkg/sql/alter_database.go` line 1848 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N7P0Ip62sTKpvFIxq0p:-N8AMDcV0s0e77csGD_P:behsb6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fe6beed405c458719d6c6fac8f0c435b8d8acf8/pkg/sql/alter_database.go#L1848)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think you are correct, because we should hit any zone config validation error down below when we call `refreshZoneConfigsForTables`. Does this mean we can also get rid of the call to `newZone.Validate()`?
</blockquote></details>

Yes, the new zone config will be validated when we call `refreshZoneConfigsForTables` (more precisely, in `prepareZoneConfigForMultiRegionTable()`), but I think maybe we still want to call `Validate()` before applying it to the database. So I added `dbZoneConfig.Validate()` in`ApplyZoneConfigFromDatabaseRegionConfig()` to validate the newly built zone config.
___
*[`pkg/sql/alter_database.go` line 1926 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N7P1A0XDLkaBCqN1nZC:-N8ANniw1y_EI3Xxp_Z1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fe6beed405c458719d6c6fac8f0c435b8d8acf8/pkg/sql/alter_database.go#L1926)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think we should make a new event type for it.
</blockquote></details>

Done.
___
*[`pkg/sql/sem/tree/alter_database.go` line 193 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N7Oxr3R4F5ajYf6cl2P:-N8ANowe8Q7olV2ujVxm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a3a0144beeb3f9f531041ceb60642821f5beedc/pkg/sql/sem/tree/alter_database.go#L193)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It may make sense to unify these three fields and their corresponding formatting logic with those in `SetZoneConfig` to avoid duplication. What do you think?
</blockquote></details>

Done.
___
*[`pkg/sql/sem/tree/alter_database.go` line 211 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N7OykyK0jqZ-WGFr0wa:-N8ANrCg4Iou9aCPHUtK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfa02f89f3eadd1b67457315f3881ba69b5b26f9/pkg/sql/sem/tree/alter_database.go#L211)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Depending on whether or not we want to pull out a separate struct to hold the three zone configuration-related fields (see the comment above), we might not need this interface.

For instance, an option would be:
```go
type ZoneConfigSettings struct {
	SetDefault bool
	YAMLConfig Expr
	Options    KVOptions
}

type SetZoneConfig struct {
	ZoneSpecifier
	// AllIndexes indicates that the zone configuration should be applied across
	// all of a tables indexes. (ALTER PARTITION ... OF INDEX <tablename>@*)
	AllIndexes bool
	ZoneConfigSettings
}

type AlterDatabaseSetZoneConfigExtension struct {
	// ALTER DATABASE ...
	DatabaseName Name
	// ALTER LOCALITY ...
	LocalityLevel LocalityLevel
	RegionName    Name
	// CONFIGURE ZONE ...
	ZoneConfigSettings
}
```

EDIT: I think that's actually what you started to do with `ZoneConfigAndOptions`, but it doesn't look like it went all the way.
</blockquote></details>

Done.
___
*[`pkg/ui/yarn-vendor` line 1 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N7OyAYv7YV9M3mIltl5:-N8ANs2g2rd8dKxbSYc0:b-pi54ks) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a3a0144beeb3f9f531041ceb60642821f5beedc/pkg/ui/yarn-vendor#L1)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did you mean to change this?
</blockquote></details>

That was a mistake, shouldn't have changed it. Thanks for pointing this out!

**Review by nvb — COMMENTED** [review]
> Reviewed 7 of 15 files at r13, 5 of 7 files at r14, 10 of 11 files at r15, 3 of 3 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83605)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @ZhouXing19)

___
*[`pkg/sql/alter_database.go` line 1739 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N7P-VA92VxQoLsWIdWi:-N8OzsuREyeU10wfMkwQ:b-yx6h4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fe6beed405c458719d6c6fac8f0c435b8d8acf8/pkg/sql/alter_database.go#L1739)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

The second returned value of `evaluateZoneOptions(n.options, params)` is a list of options to copy from parents. It's constructed by checking the zone config options from the `options` map, and collecting those with `inheritValue == true`. This `copyFromParentList` is used when setting a zone config, but I don't think we want to use it for zone config extension, because  IIUC`inheritValue` is set true only when the value of the option is `nil`. I don't think it makes sense if we allow a `nil` zone config expression in the `ALTER DATABASE ... ALTER LOCALITY...` statement. What do you think?
</blockquote></details>

Yes, I agree. So I think we can remove this TODO and replace it with a comment explaining why we're ignoring the `copyFromParentList` return value.
___
*[`pkg/sql/alter_database.go` line 1840 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N7P1d9oBJvzxTe_ct_P:-N8Oz7BY3VojB30vbu5C:breeaef) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fe6beed405c458719d6c6fac8f0c435b8d8acf8/pkg/sql/alter_database.go#L1840)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Yes I agree that such validation is needed, but I think maybe we should put it after we built a new a zone config based on the RegionConfig information? Put the TODO in `func zoneConfigForMultiRegionDatabase()` and made issue https://github.com/cockroachdb/cockroach/issues/85015.
</blockquote></details>

:thumbsup: thanks for opening the issue.
___
*[`pkg/sql/sem/tree/alter_database.go` line 193 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N8OxH-T72mIq-d6Uvis:-N8OxH-T72mIq-d6Uvit:b-8zm2xf) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d1a0c2e08bbe11de3baa826ac17ca2cf33f28e/pkg/sql/sem/tree/alter_database.go#L193)):*
> ```Go
> 	RegionName    Name
> 	// CONFIGURE ZONE ...
> 	ZoneConfigSettings *ZoneConfigSettings
> ```

Does this need to be a pointer to a `ZoneConfigSettings`? It's not optional, so I think it would be better to be a value. In fact, it's probably cleanest to embed the struct so that users don't need to know about the indirection (e.g. `stmt.Options` will work).
___
*[`pkg/sql/sem/tree/walk.go` line 1516 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N8Oy1Fx7A-zKfOFmhYK:-N8Oy1Fx7A-zKfOFmhYL:b-pd8mii) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d1a0c2e08bbe11de3baa826ac17ca2cf33f28e/pkg/sql/sem/tree/walk.go#L1516)):*
> ```Go
> func (stmt *SetZoneConfig) walkStmt(v Visitor) Statement {
> 	ret := stmt
> 	if stmt.ZoneConfigSettings != nil {
> ```

See my comment above about making this an embedded value field. Unless `stmt.ZoneConfigSettings == nil` is a valid state, it doesn't seem valuable to allow it to be expressed.

Also, if you embed the field, you won't need any of the `stmt.ZoneConfigSettings.XYZ` changes below.
___
*[`pkg/sql/sem/tree/zone.go` line 157 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N8OyRXnDFxxwvf4W8T9:-N8OyRXnDFxxwvf4W8TA:b-5dkhcy) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d1a0c2e08bbe11de3baa826ac17ca2cf33f28e/pkg/sql/sem/tree/zone.go#L157)):*
> ```Go
> 
> // GetOptions returns the zone config options stored in SetZoneConfig.
> func (node *SetZoneConfig) GetOptions() KVOptions {
> ```

This can also go away if we embed a value field.
___
*[`pkg/sql/sem/tree/zone.go` line 164 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N8OyUgHEXCpMUlIj8ce:-N8OyUgHEXCpMUlIj8cf:bau5jun) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d1a0c2e08bbe11de3baa826ac17ca2cf33f28e/pkg/sql/sem/tree/zone.go#L164)):*
> ```Go
> }
> 
> // Format implements the NodeFormatter interface.
> ```

We should move this above `ZoneConfigSettings.Format` so that the types and methods are defined in the same order.
___
*[`pkg/util/log/eventpb/zone_events.proto` line 66 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N8OzKwq082NUMlZqitj:-N8OzKwq082NUMlZqitk:b-ql9733) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d1a0c2e08bbe11de3baa826ac17ca2cf33f28e/pkg/util/log/eventpb/zone_events.proto#L66)):*
> ```protobuf
> }
> 
> // SetZoneConfigExtension is recorded when a zone config extension is changed.
> ```

Should this be called `AlterDatabaseSetZoneConfigExtension` and be moved to `ddl_events.proto`?

**Review by ZhouXing19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83605)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/sql/alter_database.go` line 1739 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N7P-VA92VxQoLsWIdWi:-N8PA2e98tuhXScq6oqi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fe6beed405c458719d6c6fac8f0c435b8d8acf8/pkg/sql/alter_database.go#L1739)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yes, I agree. So I think we can remove this TODO and replace it with a comment explaining why we're ignoring the `copyFromParentList` return value.
</blockquote></details>

Done.
___
*[`pkg/sql/sem/tree/alter_database.go` line 193 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N8OxH-T72mIq-d6Uvis:-N8PC5-j6eDM-a2YVppu:b-s9n837) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d1a0c2e08bbe11de3baa826ac17ca2cf33f28e/pkg/sql/sem/tree/alter_database.go#L193)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does this need to be a pointer to a `ZoneConfigSettings`? It's not optional, so I think it would be better to be a value. In fact, it's probably cleanest to embed the struct so that users don't need to know about the indirection (e.g. `stmt.Options` will work).
</blockquote></details>

Yes, great idea! Done.
___
*[`pkg/sql/sem/tree/zone.go` line 157 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N8OyRXnDFxxwvf4W8T9:-N8PorLl6iBU0nIE1NEo:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d1a0c2e08bbe11de3baa826ac17ca2cf33f28e/pkg/sql/sem/tree/zone.go#L157)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This can also go away if we embed a value field.
</blockquote></details>

Removed.
___
*[`pkg/sql/sem/tree/zone.go` line 164 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N8OyUgHEXCpMUlIj8ce:-N8PL1B-2oVV-LU3ZOog:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d1a0c2e08bbe11de3baa826ac17ca2cf33f28e/pkg/sql/sem/tree/zone.go#L164)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We should move this above `ZoneConfigSettings.Format` so that the types and methods are defined in the same order.
</blockquote></details>

Done.
___
*[`pkg/sql/sem/tree/walk.go` line 1516 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N8Oy1Fx7A-zKfOFmhYK:-N8PovAZ-I-2cGxqlILx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d1a0c2e08bbe11de3baa826ac17ca2cf33f28e/pkg/sql/sem/tree/walk.go#L1516)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

See my comment above about making this an embedded value field. Unless `stmt.ZoneConfigSettings == nil` is a valid state, it doesn't seem valuable to allow it to be expressed.

Also, if you embed the field, you won't need any of the `stmt.ZoneConfigSettings.XYZ` changes below.
</blockquote></details>

Done.
___
*[`pkg/util/log/eventpb/zone_events.proto` line 66 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-N8OzKwq082NUMlZqitj:-N8PoxnU2nuYY4mmebPv:b-d75u0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/99d1a0c2e08bbe11de3baa826ac17ca2cf33f28e/pkg/util/log/eventpb/zone_events.proto#L66)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should this be called `AlterDatabaseSetZoneConfigExtension` and be moved to `ddl_events.proto`?
</blockquote></details>

Moved to `ddl_events.proto`. But note that if we want to use `CommonZoneConfigDetails` in `ddl_events.proto`, we need to put `zone_events.proto` ahead of `ddl_events.proto` in `EVENTPB_PROTOS` in `PROTOS.bzl`. See https://cockroachlabs.slack.com/archives/C01CNRP6TSN/p1659379101616359?thread_ts=1659378403.639769&cid=C01CNRP6TSN

**Comment by ZhouXing19** [comment]
Passed the CI, RFAL, thanks!

**Review by nvb — APPROVED** [review]
:lgtm: nice job with this!

> Reviewed 8 of 27 files at r17, 1 of 7 files at r18, 5 of 19 files at r19, 1 of 15 files at r20, 15 of 15 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83605#-:-N8ejbPZ1sDNlwgpOWzO:b9jmjuo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by ZhouXing19** [comment]
Thanks for reviewing!
bors r=nvanbenschoten

**Comment by yuzefovich** [comment]
This needs a rebase.

bors r-

**Comment by ZhouXing19** [comment]
bors r=nvanbenschoten

**Pull request merged**
