### PR TITLE
Some refactoring of the descriptor_mutation_test

### PR DESCRIPTION
**Pull request by vivekmenezes**
[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3159)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[sql/descriptor_mutation_test.go, line 50 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3159#-K3Q0K1It3WZKEoUGkkm:-K3Q0K1It3WZKEoUGkkn:890258360) ([raw file](https://github.com/cockroachdb/cockroach/blob/564223fdd6c7b5e8182268dddde71ae1312b7255/sql/descriptor_mutation_test.go#L50)):_
What is the justification for not calling `t.Fatal` here? Looks like you are just pushing that work to the caller. If you want the full stack trace, you could add a new `mutationTest.Fatal` method which outputs the stacktrace as well (calling `runtime/debug.Stack()`).

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3159)_

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[sql/descriptor_mutation_test.go, line 50 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3159#-K3Q0K1It3WZKEoUGkkm:-K3Q4f1NXLwCbJqhqY_r:-1608931149) ([raw file](https://github.com/cockroachdb/cockroach/blob/564223fdd6c7b5e8182268dddde71ae1312b7255/sql/descriptor_mutation_test.go#L50)):_
I suppose we could do that, but it feels better to push the error up to the test so that the test can print the error. These helper functions are like any other functions
that do some work and can return errors when they can't accomplish what they set out to do. 

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3159)_

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[sql/descriptor_mutation_test.go, line 50 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3159#-K3Q0K1It3WZKEoUGkkm:-K3Q6qwngbXBiUNYV2eB:1938669825) ([raw file](https://github.com/cockroachdb/cockroach/blob/564223fdd6c7b5e8182268dddde71ae1312b7255/sql/descriptor_mutation_test.go#L50)):_
`testing.Fatal` exits the current goroutine. It is designed to be used from outside of the test function. I don't see a reason to shackle ourselves to calling `testing.Fatal` only from the test function.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3159)_

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[sql/descriptor_mutation_test.go, line 50 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3159#-K3Q0K1It3WZKEoUGkkm:-K3QP4kW2oPbax-ax218:-226709476) ([raw file](https://github.com/cockroachdb/cockroach/blob/564223fdd6c7b5e8182268dddde71ae1312b7255/sql/descriptor_mutation_test.go#L50)):_
I'll cool with unwinding this change. I agree that we are adding an inconvenience to deal with another inconvenience which in the first place is not really a big deal. I'm not going to create the special Fatal() function that spits out the stack trace.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3159)_

**Comment by vivekmenezes** [comment]
Can you take a look? I'd like to merge this in and rebase on it.

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

_[sql/descriptor_mutation_test.go, line 36 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3159#-K3RZBGSyfTITUzyzOC7:-K3S5ijgju_OmBmqcH4d:2035048499) ([raw file](https://github.com/cockroachdb/cockroach/blob/e033b6540a0727bba3af0b0dd1fefb273eff56e3/sql/descriptor_mutation_test.go#L36)):_
Good move. Fixed

---

_[sql/descriptor_mutation_test.go, line 103 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3159#-K3RZf8-mYKZ7A6V8pC9:-K3S5sfWdWDK06Ya0R7a:-467915377) ([raw file](https://github.com/cockroachdb/cockroach/blob/e033b6540a0727bba3af0b0dd1fefb273eff56e3/sql/descriptor_mutation_test.go#L103)):_
fixed

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3159)_

**Pull request merged**
