### PR TITLE
colexec: support LEFT ANTI join by the hash joiner

### LINKED ISSUE #39134: exec: LEFT ANTI is not supported by Hash Joiner
As title.

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: extract hashTable into a separate file**

This commit moves hashTable out of hashjoiner file since the former is
used by other operators as well now. Also, make minor stylistic changes.

Release note: None

**colexec: refactor hash joiner code**

This commit removes hashJoinBuilder and moves its logic onto the
hashTable. This allows us to remove references to hash join utility
structs from hashGrouper.

Also, this commit removes the "planning" logic out of the hash joiner -
previously, we would decide which side to use as the build side
depending on whether either of the sides is "distinct" (i.e. equality
columns form a key). However, this decision comes from the optimizer,
and it always sets up the join so that the right side has smaller
cardinality and should be used to build the hash table on. Now execution
follows this arrangement.

Release note: None

**colexec: support LEFT ANTI join by the hash joiner**

This commit adds support for LEFT ANTI join into the hash joiner. The
implementation is pretty simple: we build the hash table on the right
side, then we consume left source one batch at a time looking for
matches with the hash table and only including the tuples that didn't
match into the output.

LEFT ANTI join required a different initialization of probing (to
explicitly exclude tuples that hashed to such buckets that have no
tuples in the hash table). Such tuples with no hash matches are
definitely a part of the output and are handled somewhat separately.

There is no release note since users cannot request LEFT ANTI joins
themselves (these can only be planned internally).

Fixes: #39134.

Release note: None

**colexec: refactor merge joiner unit tests to be used by hash joiner**

There are a lot of unit tests for merge joiner, and now those tests are
run by the hash joiner as well. This required extracting the tests
outside of the function, but it's just a code movement, and then
unifying the helper struct that both files use.

This actually seems to have discovered an issue with LEFT OUTER and
FULL OUTER join. I haven't looked into the root cause, so we will skip
the merge join tests with those join types for now.

Release note: None

**colexec: fix outer hash join**

Previously, when populating output from the "previous batch" (in case
when we have more rows to output that can fit into a single output
batch) we would not store the index of the row to resume the collection
of output from. This could lead to returning an unmatched row (in case
of an outer join on the probe side) multiple times. I think (but I'm not
sure) that non-outer on the probe side joins were not susceptible to
this problem because we're updating headIDs for the rows as we populate
output. headID indicates whether a probe row has a match, so if we
included all matching build rows for a particular probe row into the
output, headID of the probe row is reset to 0, and so on the next
iteration that probe row is omitted.

This change additionally should give us a minor performance improvement
because now we can skip all probe rows that the output for which has
been already emitted (instead of checking headIDs which would be
zeroes).

There is no release note since this could occur only on
`experimental_on` vectorize setting.

Release note: None

### CODE REVIEW

**Review by asubiotto — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, 6 of 6 files at r2, 8 of 8 files at r3, 3 of 3 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44384)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/hashjoiner.go, line 601 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44384#-LzcAAgA9xP53dR53_Iv:-LzcAAgA9xP53dR53_Iw:b-2sj1d8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6422b55fee50223be3d1e5c59cc9087da446ec/pkg/sql/colexec/hashjoiner.go#L601)):*
> ```Go
> ) (Operator, error) {
> 	var leftOuter, rightOuter bool
> 	buildRightSide := rightDistinct
> ```

This `buildRightSide` variable seems a bit fishy to me but perhaps I don't understand it. Isn't it very important that we choose what build side to use based on the estimated cardinality (i.e. shouldn't that be plumbed down by the optimizer)? I'm not sure what `rightDistinct` has to do with it. In the case of a left anti join, you would assert that it's always the right side that is built.
___
*[pkg/sql/colexec/hashjoiner_test.go, line 951 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44384#-LzcCHzzAw-LEdH4SnJm:-LzcCHzzAw-LEdH4SnJn:b-jxkfk6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d21198c5ac13191ccd439e25f9f3a6a87b17808/pkg/sql/colexec/hashjoiner_test.go#L951)):*
> ```Go
> 			continue
> 		}
> 		for _, tcs := range []interface{}{hjTestCases, mjTestCases} {
> ```

Could you extract commonalities into a `joinerBaseTestCase` and embed that into both the `hj` and `mj` test cases?
___
*[pkg/sql/colexec/utils_test.go, line 1159 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44384#-LzcFM1r9EFRO4GzDkBZ:-LzcFM1r9EFRO4GzDkB_:bre2twf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d21198c5ac13191ccd439e25f9f3a6a87b17808/pkg/sql/colexec/utils_test.go#L1159)):*
> ```Go
> // interfaceToSlice is a helper function that converts an interface{} into a
> // slice of interface{}. It will panic if the argument is not a slice.
> func interfaceToSlice(slice interface{}) []interface{} {
> ```

I'd prefer to avoid adding this if we can

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44384)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/hashjoiner.go, line 601 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44384#-LzcAAgA9xP53dR53_Iv:-LzcHmOT5YS2q5XDHKdz:b-70g03m) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6422b55fee50223be3d1e5c59cc9087da446ec/pkg/sql/colexec/hashjoiner.go#L601)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This `buildRightSide` variable seems a bit fishy to me but perhaps I don't understand it. Isn't it very important that we choose what build side to use based on the estimated cardinality (i.e. shouldn't that be plumbed down by the optimizer)? I'm not sure what `rightDistinct` has to do with it. In the case of a left anti join, you would assert that it's always the right side that is built.
</blockquote></details>

~Yes, ideally, we would choose which side to build on using the cardinality estimates, but currently we don't, and this PR doesn't change anything here. As the code written right now, we only take advantage of knowing whether one of the inputs has rows "distinct" on equality columns, this allows us to use an optimized way of probing (i.e. avoids following the linked lists of the values that hashed to the same buckets). I agree that this behavior should be improved, but it's out of scope for this PR.~

As discussed in person, the behavior of choosing which side to build the hash table on was wrong and is now removed.
___
*[pkg/sql/colexec/hashjoiner_test.go, line 951 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44384#-LzcCHzzAw-LEdH4SnJm:-LzcIbbYAsRWKp5hL8jB:b-1hidfk) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d21198c5ac13191ccd439e25f9f3a6a87b17808/pkg/sql/colexec/hashjoiner_test.go#L951)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Could you extract commonalities into a `joinerBaseTestCase` and embed that into both the `hj` and `mj` test cases?
</blockquote></details>

~I had the same idea and started doing that, but it was extremely daunting - merge joiner has like a 100 unit test cases, so adjusting them manually is a terrible idea. Coming up with a regex that would replace things automatically seemed also hard because in many unit test cases some fields are omitted, the order of fields is slightly different, and they span multiple lines. Anyway, regexes are not my strength.~

~And in the end, it doesn't seem to give us much benefit other than stylistic "beauty."~

The idea of "embedding" was beautiful but cumbersome, and simply extracting all fields into a shared struct does the job.
___
*[pkg/sql/colexec/utils_test.go, line 1159 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44384#-LzcFM1r9EFRO4GzDkBZ:-LzcL86n75OFgExwIf79:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d21198c5ac13191ccd439e25f9f3a6a87b17808/pkg/sql/colexec/utils_test.go#L1159)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'd prefer to avoid adding this if we can
</blockquote></details>

Done.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 13 of 13 files at r6, 8 of 8 files at r7, 8 of 8 files at r8, 3 of 3 files at r9, 3 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44384#-:-LzgeTNY5UAOx6RFcczk:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
