### PR TITLE
opt: Add skeleton cost model and use it in the optimizer

### PR DESCRIPTION
**Pull request by andy-kimball**
This PR contains 3 commits. One fixes a bug I found while testing. The next adds formatting flags to ExprView. And the 3rd adds a skeleton cost model and uses it in the optimizer.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm:

Very cool!  I wondered a bit how the cost does anything right now (with no exploration xforms), but we are "exploring" the placement of enforcers.

Thanks for the separate commits, they helped a lot!

---

Review status: 0 of 52 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/memo/cost.go, line 30 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/24052#-L82aHmLkBncvDA0SP24:-L82aHmLkBncvDA0SP25:b-e5f7u4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca552621fc4a02d4688eaa75bec22d94e8fc935a/pkg/sql/opt/memo/cost.go#L30)):*
> ```Go
> 	// starting value of an uninitialized best expression, so that any other
> 	// expression will have a lower cost.
> 	MaxCost Cost = math.MaxFloat64
> ```

why not `math.Inf(+1)`

---

*[pkg/sql/opt/xform/physical_props_factory.go, line 108 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24052#-L82XiTfabkl4OFpf9WU:-L82XiTfabkl4OFpf9WV:bwk9hde) ([raw file](https://github.com/cockroachdb/cockroach/blob/be7a1943e4cc25f8403c5b9c47f03ac7b419a337/pkg/sql/opt/xform/physical_props_factory.go#L108)):*
> ```Go
> 
> 		// If there are more required columns than the primary index has, then
> 		// primary index cannot provide the required ordering.
> ```

Hm, a primary key is a key, ordering on `k, v` is the same as an ordering on `k`. I think it would be correct to just do the loop below up to the minimum length of the two. Though we will have general handling for keys at some point anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24052#-:-L82dR1WuZvAgC3_sEXO:br9mrhx)*

**Comment by rytaft** [comment]
:lgtm_strong: 

---

Reviewed 6 of 6 files at r1, 15 of 15 files at r2, 42 of 42 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/memo/best_expr.go, line 113 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/24052#-L82x5sphFb0YlCDvL0Y:-L82x5sqzXc7RrqrHE2b:bm08iw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca552621fc4a02d4688eaa75bec22d94e8fc935a/pkg/sql/opt/memo/best_expr.go#L113)):*
> ```Go
> 	}
> 
> 	// Remainder slice is only used if there are more than opt.MaxOperands.
> ```

`// Remainder slice is only used if there are more operands than opt.MaxOperands.`

---

*[pkg/sql/opt/memo/cost.go, line 38 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/24052#-L82xfvEZ2HK1aDjDZza:-L82xfvEZ2HK1aDjDZzb:b-4n6fij) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca552621fc4a02d4688eaa75bec22d94e8fc935a/pkg/sql/opt/memo/cost.go#L38)):*
> ```Go
> }
> 
> // Sub returns the difference between this cost and the given cost.
> ```

Maybe call it `Diff` instead of `Sub`?

---

*[pkg/sql/opt/memo/expr_view.go, line 220 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/24052#-L82ppn0SuqhBKT9VRSp:-L82ppn0SuqhBKT9VRSq:b3vsnx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8e4f9f95a106d099b7a7cea839883fe746770b8/pkg/sql/opt/memo/expr_view.go#L220)):*
> ```Go
> }
> 
> // String returns a string representation of this expression for testing and
> ```

String -> format

---

*[pkg/sql/opt/memo/expr_view.go, line 336 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/24052#-L82qF6H2GYXShl_rEqO:-L82qF6H2GYXShl_rEqP:b-y98bl6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8e4f9f95a106d099b7a7cea839883fe746770b8/pkg/sql/opt/memo/expr_view.go#L336)):*
> ```Go
> 			}
> 			buf.WriteString("]")
> ```

[nit] extra blank line

---

*[pkg/sql/opt/memo/logical_props.go, line 94 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/24052#-L82yjBnkMjS0ETbVhqz:-L82yjBnkMjS0ETbVhr-:b-49vnh5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca552621fc4a02d4688eaa75bec22d94e8fc935a/pkg/sql/opt/memo/logical_props.go#L94)):*
> ```Go
> type Statistics struct {
> 	// RowCount is the estimated number of rows returned by the expression.
> 	RowCount uint64
> ```

Maybe also include `UniqueRowCount`? Or is that for a future PR?

---

*[pkg/sql/opt/memo/logical_props_factory.go, line 97 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/24052#-L82z3Yk7L3U0SQ6yg6x:-L82z3Yk7L3U0SQ6yg6y:b-f6dytx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca552621fc4a02d4688eaa75bec22d94e8fc935a/pkg/sql/opt/memo/logical_props_factory.go#L97)):*
> ```Go
> 	}
> 
> 	// TODO: Need actual number of rows.
> ```

[nit] usually TODO has a name associated with it - i.e. TODO(andyk)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24052#-:-L839g4IuzyRXatmS9Ql:b-uwkowd)*

**Comment by rytaft** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/memo/best_expr.go, line 113 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/24052#-L82x5sphFb0YlCDvL0Y:-L846RO5EmHhd36njXVQ:b-uscb8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca552621fc4a02d4688eaa75bec22d94e8fc935a/pkg/sql/opt/memo/best_expr.go#L113)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see the change...

---

*[pkg/sql/opt/memo/cost.go, line 38 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/24052#-L82xfvEZ2HK1aDjDZza:-L846YtVdvGyN9qd7nkA:b-alxjnr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca552621fc4a02d4688eaa75bec22d94e8fc935a/pkg/sql/opt/memo/cost.go#L38)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Hmm, I think I'll change the comment, because difference sounds like it'd be the absolute value of the difference. How about this:
`// Sub subtracts the other cost from this cost and returns the result.`
</blockquote></details>

Sounds good, but looks like you haven't pushed the changes yet

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24052)*

**Comment by andy-kimball** [comment]
Review status: 46 of 53 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/sql/opt/memo/cost.go, line 38 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24052#-L82xfvEZ2HK1aDjDZza:-L847lhh4fXQdDzbf4jf:b-jiywa5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca552621fc4a02d4688eaa75bec22d94e8fc935a/pkg/sql/opt/memo/cost.go#L38)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Sounds good, but looks like you haven't pushed the changes yet
</blockquote></details>

Whoops, pushed it now.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24052)*

**Comment by rytaft** [comment]
Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/opt/memo/logical_props_factory.go, line 97 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24052#-L82z3Yk7L3U0SQ6yg6x:-L848BoO7kYKtrV6wyPK:bsq7wb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca552621fc4a02d4688eaa75bec22d94e8fc935a/pkg/sql/opt/memo/logical_props_factory.go#L97)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I didn't know who to assign to this - it will be you or Radu, but wasn't sure which...
</blockquote></details>

Feel free to assign to me. Not that it really matters in this case since I assume Radu or I will be fixing them soon, but just so someone is held accountable....

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24052)*

**Pull request merged**
