### PR TITLE
spanconfigkvsubscriber: fix missing system span configs

### PR DESCRIPTION
**Pull request by adityamaru**
Previously, if a range did not have an overlapping span config then `ForEachOverlappingSpanConfig` would not apply the relevant system span configs that may still apply to that range. One situation in which we could end up with such a range when a table is dropped and all of its data (including the range deletion tombstone installed by the drop) is GC'ed, the associated schema change GC job will delete the table's span config. In this case, we will not find any overlapping span configs for the table's span, but a system span config, such as a cluster wide protection policy, may still be applicable to the replica with the empty table span. A scan of that span AOST the timestamp at which we wrote the protection policy could result in a BatchTimestampBeforeGCError.

This change fixes the above bug by applying a fallback config to the span with no overlapping span configs, and combining the system span configs that apply to the span. The change adds a red-green test to exercise this logic.

Informs: #113867
Release note (bug fix): an empty range corresponding to a drop table did not respect system level span configurations such as protected timestamps, potentially causing reads above the protected timestamp to fail

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
This is a really good find! Thanks for investigating and sending out a fix. 

> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114050#-:-Nik6ESWAJzzIvOc_KBW:b-i3omkt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @stevendanna)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114050#-Nik4DC6BXEMWfJUSO-O):*
For my understanding, is this only possible if the empty range is not merged away before the GC queue picks it up again? 
___
*[`pkg/spanconfig/spanconfigstore/store.go` line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114050#-Nik4zkpANnsDg06TW27:-Nik4zkpANnsDg06TW28:b-s33r5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/72904e191c14fb138c2767ac7c6395decfc15aa5/pkg/spanconfig/spanconfigstore/store.go#L224)):*
> ```Go
> 	// system span config, such as a cluster wide protection policy, may still be
> 	// applicable to the replica with the empty table span.
> 	if !foundOverlapping {
> ```

Do we expect this to be a temporary state? This is what prompted my question above about the range being merged. 

If this is a temporary state, and we know the merge queue will merge our range away soon such that there's at least 1 overlapping span configuration for it, could we pull this `foundOverlapping` logic in `KVSubscriber.GetProtectionTimestamps` instead? One way to do it would be to detect this case and return `hlc.MinTimestamp` for `asOf`. 

Doing ^ allows us to keep PTS logic inside of `GetProtectionTimestamps`, instead of adding special case handling to this generically named `ForEachOverlapping` method.

**Comment by adityamaru** [comment]
> Do we expect this to be a temporary state? 

I _think_ so but I'm going to have to lean on your guidance here 😅 . Is there anything I can try to verify this? Maybe manually enqueue the range in the merge queue in the test? It sounds like an empty range should eventually get merged away and thereby have an overlapping span config. In the test cluster the two "broken" ranges we saw were there for several hours fwiw.

> could we pull this foundOverlapping logic in KVSubscriber.GetProtectionTimestamps instead?

We could do this, but part of me feels like its more correct to return the fallback config for such spans with no overlap from this method, instead of no config? This also unifies this methods behaviour with what we've always been doing in `GetSpanConfigForKey` - https://github.com/cockroachdb/cockroach/blob/124aaa3b00349f4240c3a078301686c2d8883eda/pkg/spanconfig/spanconfigstore/store.go#L124. The datadriven test output feels more correct to me with this change, but curious to hear your thoughts.

**Review by arulajmani — COMMENTED** [review]
> Is there anything I can try to verify this? Maybe manually enqueue the range in the merge queue in the test? It sounds like an empty range should eventually get merged away and thereby have an overlapping span config.

Yeah, manually enqueueing the range should do it. Do you remember if the broken ranges had been merged in your test? I would expect the merge queue to pick them up in 10 minutes, so if they hadn't, maybe there's more to the story here. We can look at it together if its readily reproducible. 

> We could do this, but part of me feels like its more correct to return the fallback config for such spans with no overlap from this method, instead of no config?

I can see an argument for this, yeah. Let's document this behavior in a comment in that case so it's explicit?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114050#-:-NiuVYqU7HeIYEt1K63_:b-9ka4qx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @stevendanna)

**Comment by stevendanna** [comment]
> I would expect the merge queue to pick them up in 10 minutes, so if they hadn't, maybe there's more to the story here. We can look at it together if its readily reproducible.

I think this cluster has a large number of long-lived manual splits so they won't be merged.  _Eventually_ perhaps the replicaGC queue would have gotten to it perhaps?

**Comment by arulajmani** [comment]
> I think this cluster has a large number of long-lived manual splits so they won't be merged.

That checks out.

**Comment by adityamaru** [comment]
ill add a comment and pick this up today, sorry got busy with online restore

**Review by stevendanna — APPROVED** [review]

**Comment by adityamaru** [comment]
TFTR!

bors r=stevendanna

**Comment by adityamaru** [comment]
@arulajmani ill wait for your stamp on the backports so if you have any remaining comments on this PR I can address them before that.

**Pull request merged**
