### PR TITLE
storage: improve consistency checker diff, add debug decode-key

### PR DESCRIPTION
**Pull request by tbg**
Avoid spilling non-printable characters and generally garbage into the
logs.

Release note: None

### CODE REVIEW

**Review by a-robinson — APPROVED** [review]

**Comment by tschottdorf** [comment]
bors r=a-robinson
TFTR!

**Comment by tschottdorf** [comment]
Ended up adding some stuff, PTAL.

**Comment by tschottdorf** [comment]
(I stopped shy of pretty-printing the values, but I'll do that in a follow-up)

**Review by a-robinson — DISMISSED** [review]
Very useful!

> Reviewed 4 of 4 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29012#-:-LKcnSybDGKlH5BYtEEu:b-w2mrju)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/cli_debug_test.go, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29012#-LKcllXQ6RjEwF2gg1Me:-LKcllXQ6RjEwF2gg1Mf:b-o2dorv) ([raw file](https://github.com/cockroachdb/cockroach/blob/996f6d1e46eaef9e5b6763eb81c44c0ce80b3e01/pkg/cli/cli_debug_test.go#L23)):*
> ```Go
> 	// debug decode-value 016b12bd8980c0b6c2e211ba5182000172647363 884d186d03089b09120bbd8980c0b6c2e211ba51821a0bbd8980c0b9e7c5c610e99622060801100118012206080410041802220608021002180428053004
> 	// unable to decode key: invalid encoded mvcc key: 016b12bd8980c0b6c2e211ba5182000172647363, attempting fallback;
> 	// if the result below like garbage, then it likely is:
> ```

s/below like/below looks like/
___
*[pkg/cli/debug.go, line 154 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29012#-LKcmObB1x8etAPIfKl6:-LKcmObB1x8etAPIfKl7:b-y7jyuz) ([raw file](https://github.com/cockroachdb/cockroach/blob/996f6d1e46eaef9e5b6763eb81c44c0ce80b3e01/pkg/cli/debug.go#L154)):*
> ```Go
> 	if debugCtx.values {
> 		printer = func(kv engine.MVCCKeyValue) (bool, error) {
> 			debug.PrintKeyValue(kv, debugCtx.sizes)
> ```

A comment explaining why we're ignoring the errors would be nice. I think you'll also need a `_ = ...` to make the linter happy.
___
*[pkg/cli/debug.go, line 380 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29012#-LKcm2Zl6j2gY0TssmOX:-LKcm2Zl6j2gY0TssmOY:b-o2dorv) ([raw file](https://github.com/cockroachdb/cockroach/blob/996f6d1e46eaef9e5b6763eb81c44c0ce80b3e01/pkg/cli/debug.go#L380)):*
> ```Go
> 			// is already a roachpb.Key, so make a half-assed attempt to support both.
> 			fmt.Printf("unable to decode key: %v, assuming it's a roachpb.Key with fake timestamp;\n"+
> 				"if the result below like garbage, then it likely is:\n\n", err)
> ```

s/below like/below looks like/
___
*[pkg/cli/debug/print.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29012#-LKcm9Nj1d3ypfLEVWKN:-LKcm9Nj1d3ypfLEVWKO:blpxalr) ([raw file](https://github.com/cockroachdb/cockroach/blob/996f6d1e46eaef9e5b6763eb81c44c0ce80b3e01/pkg/cli/debug/print.go#L1)):*
> ```Go
> // Copyright 2018 The Cockroach Authors.
> ```

This is all just code movement, right? I didn't read through it carefully.
___
*[pkg/storage/consistency_queue_test.go, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29012#-LKclC56C0xSWvgLlSJ0:-LKclC56C0xSWvgLlSJ1:bh8w6vq) ([raw file](https://github.com/cockroachdb/cockroach/blob/200fea64c4c7c86b2bfb5a1f1ee7a39e487c9fd4/pkg/storage/consistency_queue_test.go#L133)):*
> ```Go
> 
> 			diffS := diff.String()
> 			t.Log(diffS)
> ```

Why always log it vs only printing it on failure?

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29012)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/cli_debug_test.go, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29012#-LKcllXQ6RjEwF2gg1Me:-LKeKmBs9FhHq8bizf2h:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/996f6d1e46eaef9e5b6763eb81c44c0ce80b3e01/pkg/cli/cli_debug_test.go#L23)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

s/below like/below looks like/
</blockquote></details>

Done.
___
*[pkg/cli/debug.go, line 154 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29012#-LKcmObB1x8etAPIfKl6:-LKeKnXLAPxOVxGkfWCM:brddmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/996f6d1e46eaef9e5b6763eb81c44c0ce80b3e01/pkg/cli/debug.go#L154)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

A comment explaining why we're ignoring the errors would be nice. I think you'll also need a `_ = ...` to make the linter happy.
</blockquote></details>

Done. (Removed the error return).
___
*[pkg/cli/debug.go, line 380 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29012#-LKcm2Zl6j2gY0TssmOX:-LKeKqeX8p554RUbqPie:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/996f6d1e46eaef9e5b6763eb81c44c0ce80b3e01/pkg/cli/debug.go#L380)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

s/below like/below looks like/
</blockquote></details>

Done.
___
*[pkg/cli/debug/print.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29012#-LKcm9Nj1d3ypfLEVWKN:-LKeKr_49rlnvIp7nDh0:b-1e3pmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/996f6d1e46eaef9e5b6763eb81c44c0ce80b3e01/pkg/cli/debug/print.go#L1)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

This is all just code movement, right? I didn't read through it carefully.
</blockquote></details>

Yeah, with some juggling around. Nothing noteworthy.
___
*[pkg/storage/consistency_queue_test.go, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29012#-LKclC56C0xSWvgLlSJ0:-LKeTKH108w2SsEJtJ0G:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/200fea64c4c7c86b2bfb5a1f1ee7a39e487c9fd4/pkg/storage/consistency_queue_test.go#L133)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Why always log it vs only printing it on failure?
</blockquote></details>

Done.

**Comment by tschottdorf** [comment]
bors r=a-robinson
TFTR!

**Comment by tschottdorf** [comment]
Flaked on new issue https://github.com/cockroachdb/cockroach/issues/29031

bors r=a-robinson

**Pull request merged**
