### PR TITLE
workload: fix performance regresion from accessing query execution mode

### LINKED ISSUE #101494: roachperf: regression in tpcc on 2023/04/11
Our performance dropped on `tpccbench/nodes=3/cpu=16` across aws and gcp on 2023/04/11. We should understand why and resolve the regression.

Screenshot 2023-04-13 at 4 52 31 PM

Jira issue: CRDB-26971

### PR DESCRIPTION
**Pull request by sean-**
sync.RWMutex RLock() became a hot path for essentially a read-only value.  The
execution mode of a pool and query doesn't change after program initialization.

Release note: None
Fixes: #101494

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]
:lgtm:

I am doing another full run as a sanity check.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102193#-:-NTtHp_5ABieTZBYHYfX:b-ps185d)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @smg260)

**Review by sean- — COMMENTED** [review]
Thank you.  I'm tempted to make the pgx logger's presence conditional behind yet-another-connection-flag, but am not sure the juice is worth the squeeze to do that vs just removing it outright atm since I've never seen any actual log output flow through the logger or tracer interface.  LMK.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102193#-:-NTtfjdo6VJYy90kM1CL:b-7fjarf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @smg260)

**Comment by srosenberg** [comment]
> I'm tempted to make the pgx logger's presence conditional behind yet-another-connection-flag, but am not sure the juice is worth the squeeze to do that vs just removing it outright atm since I've never seen any actual log output flow through the logger or tracer interface. LMK.

Let's leave that for a follow-up story. I would also like to add a prometheus exporter (e.g., [1]) to get more insights into the connection pool. Both changes seem trivial but they need to take performance into consideration.

[1] https://github.com/IBM/pgxpoolprometheus

**Comment by srosenberg** [comment]
First run looks good modulo a blip ~13:15,
 
kv95_workload_run_1

Second run should be finishing up: https://grafana.testeng.crdb.io/d/I2_Fu704k/kv95?orgId=1&from=now-1h&to=now&viewPanel=4

Please update the commit to mention that it `Resolves: https://github.com/cockroachdb/cockroach/issues/101494`, and we're good to merge!

**Comment by yuzefovich** [comment]
This PR needs `./dev gen bazel`.

bors r-

**Comment by srosenberg** [comment]
> This PR needs `./dev gen bazel`.
> 
> bors r-

Thanks @yuzefovich and sorry! I should have verified CI passed.

**Pull request merged**
