### PR TITLE
sql/parser: Capture REFERENCES constraints in parsed CREATE TABLE stmt

### PR DESCRIPTION
**Pull request by dt**
Nothing actually uses these yet.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6801)

### CODE REVIEW

**Comment by mjibson** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/parser/sql.y, line 1455 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6801#-KI9F7M32PhYt7PvpoH2:-KI9F7M32PhYt7PvpoH3:-2125910955) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa0ffd346e2dd0fd5666c05e7cca9f3f1555892a/sql/parser/sql.y#L1455)):*
> ```Yacc
>     $$.val = &ColumnDefault{Expr: $2.expr()}
>   }
> | REFERENCES qualified_name opt_name_parens key_match key_actions
> ```

Why change from opt_column_list? With just one name FKs will be restricted to single-column indexes. See https://dev.mysql.com/doc/refman/5.6/en/create-table-foreign-keys.html for an example of a multi-column REFERENCE.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6801)*

**Comment by dt** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/parser/sql.y, line 1455 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6801#-KI9F7M32PhYt7PvpoH2:-KI9G7SAnwYqcn9rxjVj:1281896673) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa0ffd346e2dd0fd5666c05e7cca9f3f1555892a/sql/parser/sql.y#L1455)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Why change from opt_column_list? With just one name FKs will be restricted to single-column indexes. See https://dev.mysql.com/doc/refman/5.6/en/create-table-foreign-keys.html for an example of a multi-column REFERENCE.
</details>
These are _column level_ constraints -- they can only reference a single other column (unlike table constraints, which i think is what you are thinking of)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6801)*

**Comment by dt** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/parser/sql.y, line 1455 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6801#-KI9F7M32PhYt7PvpoH2:-KI9GXeOzzPLCxtc6kJL:-828798728) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa0ffd346e2dd0fd5666c05e7cca9f3f1555892a/sql/parser/sql.y#L1455)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> These are _column level_ constraints -- they can only reference a single other column (unlike table constraints, which i think is what you are thinking of)
</details>
if you look at http://www.postgresql.org/docs/current/static/sql-createtable.html, the column constraint looks like ` REFERENCES reftable [ ( refcolumn ) ]`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6801)*

**Comment by mjibson** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/parser/sql.y, line 1455 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6801#-KI9F7M32PhYt7PvpoH2:-KI9LFVZcNQdz5mLsS24:-1167628203) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa0ffd346e2dd0fd5666c05e7cca9f3f1555892a/sql/parser/sql.y#L1455)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> if you look at http://www.postgresql.org/docs/current/static/sql-createtable.html, the column constraint looks like ` REFERENCES reftable [ ( refcolumn ) ]`
</details>
Ah, yes. That stuff LGTM then.

However if this is merged then this REFERENCES stuff will start to show up in our SQL diagrams, which I'd like to prevent. If you include a comment like `// unimplemented` in this block it'll trigger removal by the diagram generator.

Second problem is that although it won't show up in the diagrams, it'll be parsed without error but won't do anything, confusing users. Are we ok with that for now? I might prefer to have a check somewhere that throws an error if this if present.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6801)*

**Comment by dt** [comment]
There are more PRs coming right after this one -- just wanted to split it up for review.
I'm not too worried about people finding a new, undocumented feature and complaining when it isn't done .

**Comment by mjibson** [comment]
:lgtm: as long as it's either working or you add `// unimplemented` to the logic block before next week's release.

<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> There are more PRs coming right after this one -- just wanted to split it up for review.
> 
> I'm not too worried about people finding a new, undocumented feature and complaining when it isn't done .
</details>


---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6801#-:-KI9XKR4kSEqaLZmbk0s:-922627256)*

**Pull request merged**
