### PR TITLE
storage: Avoid adding all replicas at once in RelocateRange

### LINKED ISSUE #29130: storage: RelocateRange doesn't handle edge cases properly
https://github.com/cockroachdb/cockroach/blob/3c6c71db227f6a844b929136935811f13df7d99c/pkg/storage/merge_queue.go#L267-L272

https://github.com/cockroachdb/cockroach/blob/2f2467cd61743c3b40b20c49d9d10eff05c36ff3/pkg/storage/replica_command.go#L956-L957

### PR DESCRIPTION
**Pull request by a-robinson**
Does a more gradual process of adding one replica then removing one
until all the desired changes have been made, using the existing
allocator code to do so in a reasonable order.

Fixes #29130

Release note: None

-------------------

This is still a work-in-progress in the sense that it isn't really usable from the SQL code yet, since I just implemented it as a method on `Store`. If the approach looks reasonable, though, it can be converted it into an Admin API method.

### CODE REVIEW

**Review by benesch — COMMENTED** [review]
This basically LGTM. Let's make it an admin request and call it a day! :tada: :tada: :tada:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29684#-:-LM3OgHHDOC__EptcIQ-:b-fkxu06)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by a-robinson** [comment]
This is ready for final review now, @benesch. Thanks in advance!

**Review by benesch — APPROVED** [review]
Awesome! :lgtm: 

> Reviewed 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29684#-:-LM_JWFu2pu-bBlPqXWX:b-i581jd)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by a-robinson** [comment]
Ugh, a sql logictest is now getting really finicky because the order of the replicas as specified in the `RelocateRange` command is no longer guaranteed to be the same as the order in the `ReplicaDescriptor` afterwards. I'm not sure it's even deterministic, so I may have to tweak that test somewhat meaningfully. Working on it.

**Comment by a-robinson** [comment]
@jordanlewis can you take a quick look at the new first commit? Commit message copied here for convenience:

---

sql: Sort replicas in crdb_internal.ranges table by store ID

This matches the behavior of `SHOW RANGES`, and is the only way for the
replicas to be meaningfully ordered in a consistent way. It's odd that
the order doesn't even match the order in which the replicas are added.
For example, I could see this sequence in the logs for a range:

Starting replicas: [s4]
Adding s1 results in: [s4,s1]
Adding s2 results in: [s4,s1,s2]
Removing s4 results in: [s2,s1]

Release note (sql change): The entries in the replicas array column of
the crdb_internal.ranges virtual table are now always sorted by store
ID.

**Review by benesch — APPROVED** [review]
If you'll accept my review in place of @jordanlewis's: LGTM!

**Review by jordanlewis — APPROVED** [review]

**Comment by a-robinson** [comment]
That's a new one to me:

> [Resolving artifact dependencies] Failed to resolve artifact dependency <Cockroach / Unit Tests / Build Test Binary, build #31334 [id 917058]>: No files matched for patterns "cockroach" from <Cockroach / Unit Tests / Build Test Binary, build #31334 [id 917058]> (jetbrains.buildServer.artifacts.impl.SourcePathAwareResolvingFailedException)

bors r+

**Comment by a-robinson** [comment]
Ah, it's from the recent go-test-teamcity update (https://github.com/cockroachdb/go-test-teamcity/pull/9). I'll wait until that's resolved (https://github.com/cockroachdb/go-test-teamcity/pull/10).

**Comment by a-robinson** [comment]
Retrying after merging https://github.com/cockroachdb/go-test-teamcity/pull/10

bors r+

**Pull request merged**
