### PR TITLE
release-23.1: catalog/lease: optimize lease count query

### PR DESCRIPTION
**Pull request by fqazi**
backport of 4f7e3944acae753b8b3a23283aadf247556eb7d9

Previously, the query to count leases would end up scanning the entire system.leases table because of the addition of crdb_region as the first column on 23.1. This meant that scans not specifying a region would always be forced to scan the entire table. To address this, this patch will update the count query to specify the default region when working on single region system databases.

Fixes: #119456

Release note (bug fix): Schema changes with a large number of descriptors could end up doing full table scans on system.leases.

Release justification: a low risk fix that optimizes the leasing query for non-multi-region clusters, which was causing a regression for customers.

### CODE REVIEW

**Review by rimadeodhar — CHANGES_REQUESTED** [review]
LG. Similar to the other backport, can we add a unit test? Also, curious if we have any existing E2E test suite for this? I tried taking a look but couldn't find anything that seemed to test leasing for MR.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119466#-:-NrM4m6n-lwcV50ejb69:b5ri2hg)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

**Review by rimadeodhar — APPROVED** [review]
Same comment as https://github.com/cockroachdb/cockroach/pull/119464. We should add this to the backports channel. Thanks for the fix.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119466#-:-NraprAy2WhRzIkUInrL:b6nhhjj)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

**Review by mgartner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119466)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @rimadeodhar)

___
*[`pkg/sql/catalog/lease/count.go` line 53 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119466#-Nrf7In-1cH1NHyrfu0Q:-Nrf7In-1cH1NHyrfu0R:b-973cbc) ([raw file](https://github.com/cockroachdb/cockroach/blob/48469156e715ef115d2ff9a238612813a4233899/pkg/sql/catalog/lease/count.go#L53)):*
> ```Go
> 	var whereClauses []string
> 	for _, t := range versions {
> 		whereClauses = append(whereClauses,
> ```

These allocations are unnecessary for appending to the `[]string` aren't necessary. Consider using a string builder and building these filters directly into it in the future.
___
*[`pkg/sql/catalog/lease/count.go` line 63 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119466#-Nrf3Q2H25GHU4Bz4CkV:-Nrf3Q2H25GHU4Bz4CkW:b-b65u0) ([raw file](https://github.com/cockroachdb/cockroach/blob/48469156e715ef115d2ff9a238612813a4233899/pkg/sql/catalog/lease/count.go#L63)):*
> ```Go
> 		at.AsOfSystemTime()) +
> 		strings.Join(whereClauses, " OR ") +
> 		singleRegionClause
> ```

I think the order of operations is incorrect here. `AND`s take precedence over `OR`s in SQL:

```
defaultdb> select true or false and false;
  ?column?
------------
     t
(1 row)

defaultdb> select (true or false) and false;
  ?column?
------------
     f
(1 row)
```

Don't you want `crdb_region = $2` to be required for the entire output, and not grouped with only the last of `whereClauses`? Can you think of a test case that would have caught this?

It's very hard to reason about what the final query will be in all possible cases here. Building the entire query from one template or using a string builder would make this less error prone I believe. A string builder would also be more efficient - is this a performance critical code path?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119466)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rimadeodhar)

___
*[`pkg/sql/catalog/lease/count.go` line 53 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119466#-Nrf7In-1cH1NHyrfu0Q:-NrfCpru9NNcygCezTla:bk0zywc) ([raw file](https://github.com/cockroachdb/cockroach/blob/48469156e715ef115d2ff9a238612813a4233899/pkg/sql/catalog/lease/count.go#L53)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

These allocations are unnecessary for appending to the `[]string` aren't necessary. Consider using a string builder and building these filters directly into it in the future.
</blockquote></details>

Done.

Good point, switched this over to using StringBuilder. I'll forward fit this later
___
*[`pkg/sql/catalog/lease/count.go` line 63 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119466#-Nrf3Q2H25GHU4Bz4CkV:-NrfLI164mevZ89PuTYz:b-hc38c0) ([raw file](https://github.com/cockroachdb/cockroach/blob/48469156e715ef115d2ff9a238612813a4233899/pkg/sql/catalog/lease/count.go#L63)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think the order of operations is incorrect here. `AND`s take precedence over `OR`s in SQL:

```
defaultdb> select true or false and false;
  ?column?
------------
     t
(1 row)

defaultdb> select (true or false) and false;
  ?column?
------------
     f
(1 row)
```

Don't you want `crdb_region = $2` to be required for the entire output, and not grouped with only the last of `whereClauses`? Can you think of a test case that would have caught this?

It's very hard to reason about what the final query will be in all possible cases here. Building the entire query from one template or using a string builder would make this less error prone I believe. A string builder would also be more efficient - is this a performance critical code path?
</blockquote></details>

Done.

Good find and I have updated the test to include this scenario. I think most of our tests focus on a single descriptor in the subsystem.
___
*[`pkg/ccl/multiregionccl/lease_test.go` line 49 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/119466#-NrfLU0pDK4C5yRrV8j4:-NrfLU0pDK4C5yRrV8j5:bv5rfsj) ([raw file](https://github.com/cockroachdb/cockroach/blob/471f7893d26494f68d14391ce55fdb161c917841/pkg/ccl/multiregionccl/lease_test.go#L49)):*
> ```Go
> 	}
> 
> 	for i, testMode := range []string{"multi-region system database", "single-region system database"} {
> ```

Updated this test to cover both single and multi-region since I think the existing tests were missing scenario the Marcus noticed.

**Review by mgartner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119466#-:-NrgCpx6D-yJrL60Jn6w:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rimadeodhar)

___
*[`pkg/sql/catalog/lease/count.go` line 53 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119466#-Nrf7In-1cH1NHyrfu0Q:-NrgCGi7Bj4D_c8bGqnp:b-uojmbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/48469156e715ef115d2ff9a238612813a4233899/pkg/sql/catalog/lease/count.go#L53)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Done.

Good point, switched this over to using StringBuilder. I'll forward fit this later
</blockquote></details>

I wasn't clear, but I was suggesting a string builder for the whole query. Not a big deal though.

**Comment by fqazi** [comment]
@mgartner @rimadeodhar TFTR!

**Pull request merged**
