### PR TITLE
build: misc `make check` improvements

### PR DESCRIPTION
**Pull request by tbg**
See individual commits.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9902)

### CODE REVIEW

**Comment by tschottdorf** [comment]
I'm open to leaving `TestCrlfmt` failing and instead running only that as a pre-push hook.

**Comment by tamird** [comment]
:lgtm:. running crlfmt as a pre-push hook sgtm (better than disabling it)

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[build/style_test.go, line 438 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9902#-KTsetjIVbEfI1GvALEa:-KTsetjIVbEfI1GvALEb:bnay2mz) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e0a11dd359356d4d87c0ab5d23a3c78995d5687/build/style_test.go#L438)):*
> ```Go
> 
> 		if err := stream.ForEach(filter, func(s string) {
> 			t.Log(s) // don't fail, only log
> ```

:cry: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9902#-:-KTsfE33A3UQUMRAQume:bcttkwt)*

**Comment by tschottdorf** [comment]
PTAL

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[build/style_test.go, line 429 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/9902#-KTsleevIvlALzTXELEB:-KTsleevIvlALzTXELEC:b-tirpka) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad2e041ae5b31841cd6b2266185977937ec7936/build/style_test.go#L429)):*
rather than doing all this, you can use `cmd.Args` below. From the docs:

> Args holds command line arguments, including the command as Args[0].

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9902#-:-KTslriAcuOXIkKKphGd:bnfp4nl)*

**Comment by tschottdorf** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[build/style_test.go, line 429 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/9902#-KTsleevIvlALzTXELEB:-KTt11JPjO7Gwvf_yR6B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad2e041ae5b31841cd6b2266185977937ec7936/build/style_test.go#L429)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> rather than doing all this, you can use `cmd.Args` below. From the docs:
> 
> > Args holds command line arguments, including the command as Args[0].
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9902)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r8, 1 of 1 files at r9.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9902)*

**Comment by tschottdorf** [comment]
Posted a PSA: https://forum.cockroachlabs.com/t/psa-a-pre-push-hook-for-formatting-checks-has-been-added/303/1

**Pull request merged**
