### PR TITLE
sql: Keep spaces when using unaccent

### LINKED ISSUE #100407: `unaccent()` function strips spaces
**Describe the problem**

The `unaccent()` function seems to be [discarding space characters](https://github.com/cockroachdb/cockroach/blob/1e27c65fb5a3810a5e2285cf07b45d95d401cca6/pkg/util/unaccent/unaccent.go#L431), which as far as I can tell is not the expected behavior in PostgreSQL.

**To Reproduce**

Run the following query:

```sql
SELECT unaccent('Héllô Wõrld!');
```

**Expected behavior**

```
Hello World!
```

**Observed behavior**

```
HelloWorld!
```

**Environment:**
- CockroachDB CCL v22.2.7 (x86_64-pc-linux-gnu, built 2023/03/28 19:47:29, go1.19.6)
- `cockroach sql`, macOS 13.2.1, version details:
  - Build Tag:        v22.2.6
  - Build Time:       2023/03/03 19:41:42
  - Distribution:     CCL
  - Platform:         darwin amd64 (x86_64-apple-darwin19)
  - Go Version:       go1.19.4
  - C Compiler:       Clang 10.0.0 
  - Build Commit ID:  d5a076f2953c0712193b8cbe08bbb682563c5675
  - Build Type:       release

Jira issue: CRDB-26415

### PR DESCRIPTION
**Pull request by aeekayy**
The previous behavior of unaccent removed spaces, but that is not
compatible with the PG implementation.

Fixes #100407 

Release note (bug fix): The unaccent builtin function no longer removes
spaces.

## Operation
```
SELECT unaccent('Héllô Wõrld!');
```

## Expected behavior
```
Hello World!
```

## Old behavior
```
HelloWorld!
```

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
thanks for your contribution! i will merge this

**Review by rafiss — CHANGES_REQUESTED** [review]
please update your commit message. i tried making this change, but i don't have permission to push to your fork
```
builtins: update unaccent to leave spaces alone

The previous behavior of unaccent removed spaces, but that is not
compatible with the PG implementation.

Release note (bug fix): The unaccent builtin function no longer removes
spaces.
```

**Review by rafiss — CHANGES_REQUESTED** [review]
the commit message still needs to be updated

**Review by rafiss — APPROVED** [review]
thank you!

bors r+

**Comment by aeekayy** [comment]
@rafiss I pushed the updated commit message

**Pull request merged**
