### PR TITLE
liveness: split liveness cache out

### PR DESCRIPTION
**Pull request by andrewbaptist**
Move the liveness caching methods to a new file.

Only look at the last 2 commits - I will rebase on master once those are merged.

Epic: none

Release note: None

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
Thanks, LGTM!

`nodeDescMap` is new, and doesn't appear to be used at all in this commit -- should this have been part of a different commit?

> Reviewed 20 of 20 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103948#-:-NWSEqCp5Ir8dErMmCxy:b-sipo64)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist)

___
*[`pkg/kv/kvserver/liveness/cache.go` line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103948#-NWS9TIwE---SUVdWyW9:-NWS9TIwE---SUVdWyWA:b-2tms53) ([raw file](https://github.com/cockroachdb/cockroach/blob/9611b1715307cc2a34c2ac7142ae2a6b8ec0686f/pkg/kv/kvserver/liveness/cache.go#L40)):*
> ```Go
> 	mu                    struct {
> 		syncutil.RWMutex
> 		// Stores timestamps of StoreDescriptor updates in Gossip
> ```

nit: in Go, doc comments [usually](https://tip.golang.org/doc/comment) start with the subject name, e.g. "nodeDescMap stores". I won't keep nitpicking on this, but seemed worth mentioning it once.
___
*[`pkg/kv/kvserver/liveness/cache.go` line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103948#-NWSDbBn2WV16673htIo:-NWSDbBn2WV16673htIp:bt3g24w) ([raw file](https://github.com/cockroachdb/cockroach/blob/9611b1715307cc2a34c2ac7142ae2a6b8ec0686f/pkg/kv/kvserver/liveness/cache.go#L52)):*
> ```Go
> 	c.notifyLivenessChanged = notifyLivenessChanged
> 	c.mu.nodes = make(map[roachpb.NodeID]Record)
> 	c.mu.nodeDescMap = make(map[roachpb.NodeID]hlc.Timestamp)
> ```

nit: this stuff seems like it belongs in a `newCache()` constructor.
___
*[`pkg/kv/kvserver/liveness/cache.go` line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103948#-NWSJXwa2yaP3L0Bq3Fx:-NWSJXwa2yaP3L0Bq3Fy:b-d23sag) ([raw file](https://github.com/cockroachdb/cockroach/blob/9611b1715307cc2a34c2ac7142ae2a6b8ec0686f/pkg/kv/kvserver/liveness/cache.go#L71)):*
> ```Go
> // myNodeID returns the ID for this node according to Gossip. This will be 0
> // until the node has joined the cluster.
> func (c *cache) myNodeID() roachpb.NodeID {
> ```

nit: consider `selfID()` for consistency.
___
*[`pkg/kv/kvserver/liveness/liveness.go` line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103948#-NWS7s9D7dvVPfGoEbRS:-NWS7s9D7dvVPfGoEbRT:b-yrdmr) ([raw file](https://github.com/cockroachdb/cockroach/blob/cea9049b0aef91d01888d47db6764ec85d6845c4/pkg/kv/kvserver/liveness/liveness.go#L54)):*
> ```Go
> 	TestTimeUntilStoreDeadOff = 24 * time.Hour
> )
> const timeUntilStoreDeadSettingName = "server.time_until_store_dead"
> ```

nit: let's pull this into the `const()` block above.
___
*[`pkg/kv/kvserver/liveness/liveness.go` line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103948#-NWS7fJxBJ10aRB0IYQq:-NWS7fJy2hukMDKe36Yg:b-vids06) ([raw file](https://github.com/cockroachdb/cockroach/blob/cea9049b0aef91d01888d47db6764ec85d6845c4/pkg/kv/kvserver/liveness/liveness.go#L59)):*
> ```Go
> var TimeUntilStoreDead = func() *settings.DurationSetting {
> 	s := settings.RegisterDurationSetting(
> 		settings.TenantWritable,
> ```

Unrelated to this change, is it problematic that this is `TenantWritable`? Consider a follow-up PR.
___
*[`pkg/kv/kvserver/liveness/liveness.go` line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103948#-NWS7bab7GnTUh8XG5K-:-NWS7bab7GnTUh8XG5K0:buy7o5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/cea9049b0aef91d01888d47db6764ec85d6845c4/pkg/kv/kvserver/liveness/liveness.go#L76)):*
> ```Go
> 		},
> 	)
> 	s.SetVisibility(settings.Public)
> ```

nit: while we're here, this can be simplified as `.WithPublic()`, which allows removing the anonymous function.
___
*[`pkg/kv/kvserver/liveness/liveness.go` line 292 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103948#-NWSATiSCalgapND09ud:-NWSATiSCalgapND09ue:by0mjg0) ([raw file](https://github.com/cockroachdb/cockroach/blob/cea9049b0aef91d01888d47db6764ec85d6845c4/pkg/kv/kvserver/liveness/liveness.go#L292)):*
> ```Go
> 		//
> 		// Now that we're always guaranteed to have a liveness records present,
> 		// we should change this out to be a look-through cache instead (it can
> ```

Are we planning to make this look-through, or only populate this from gossip and separate liveness concerns (gossip/cache) from membership concerns (KV)? In that case, the former wouldn't be a cache as much as a view of the gossip state, since it'd presumably only be updated from gossip. Would we need a membership cache in that case? The overall plan and outcome here isn't entirely clear to me, it would be good if you could outline this.
___
*[`pkg/kv/kvserver/liveness/liveness.go` line 1220 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103948#-NWSKgkm0e1k9-bf8sYZ:-NWSKgkm0e1k9-bf8sY_:b-9ajec4) ([raw file](https://github.com/cockroachdb/cockroach/blob/9611b1715307cc2a34c2ac7142ae2a6b8ec0686f/pkg/kv/kvserver/liveness/liveness.go#L1220)):*
> ```Go
> // GetNodeCount returns a count of the number of nodes in the cluster,
> // including dead nodes, but excluding decommissioning or decommissioned nodes.
> // TODO(baptist): remove this method. There are better alternatives.
> ```

nit: In the meanwhile, should we dispatch this and the below method to `cache`? It seems a bit iffy that `NodeLiveness` reaches into `cache` internals.

**Comment by andrewbaptist** [comment]
@erikgrinaker can you take one more look at this. I added another two commits 
[The first one](https://github.com/cockroachdb/cockroach/pull/103948/commits/374b30b699fa5bf9d4126e9f1eeb9fd9d387e49a) is just splitting the original commit to make clear that it is an addition to the cache
[The second one](https://github.com/cockroachdb/cockroach/pull/103948/commits/aaa040501e2f10901013dc0927f11fecd2936b9a) adds a retry loop for a test that hit a rare failure (1/1000) during node restart. By checking for quiesces.

**Review by erikgrinaker — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103948)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist)

___
*[`pkg/kv/kvserver/liveness/cache.go` line 41 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103948#-NWln7xn4ITfhJH26mKk:-NWln7xo03-2LBNrZTnd:b-tw6vqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/374b30b699fa5bf9d4126e9f1eeb9fd9d387e49a/pkg/kv/kvserver/liveness/cache.go#L41)):*
> ```Go
> 		syncutil.RWMutex
> 		// nodeDescMap stores timestamps of StoreDescriptor updates in Gossip
> 		nodeDescMap map[roachpb.NodeID]hlc.Timestamp
> ```

nit: Can we give this a clearer name? Something like `lastStoreUpdate` or whatever.
___
*[`pkg/kv/kvserver/liveness/liveness.go` line 1114 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/103948#-NWlo9Tr-Zcn2AmZpUyx:-NWlo9Tr-Zcn2AmZpUyy:b-a6korc) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaa040501e2f10901013dc0927f11fecd2936b9a/pkg/kv/kvserver/liveness/liveness.go#L1114)):*
> ```Go
> 	}
> 	retryOpts := base.DefaultRetryOptions()
> 	retryOpts.Closer = nl.stopper.ShouldQuiesce()
> ```

Nice catch. This wouldn't just cause test flakes, but actually hold up node shutdown.

**Comment by andrewbaptist** [comment]
bors r=erikgrinaker

**Pull request merged**
