### PR TITLE
kv: log slow requests on replica level in addition to range level

### LINKED ISSUE #114431: kv: log slow client requests with replica information
We currently log slow/hanging requests from the client at the level of a range, but not at the level of a replica:
https://github.com/cockroachdb/cockroach/blob/ce3f78b16d2224bac35baf95a263d5102afdca72/pkg/kv/kvclient/kvcoord/dist_sender.go#L1922-L1941

As a result, it can be difficult to determine which replica a request was executing on when it got stuck. Ex. https://github.com/cockroachdb/cockroach/issues/112373#issuecomment-1806527131.

We should push similar logging into `DistSender.sendToReplicas`, surrounding the call to `transport.SendNext`.

Jira issue: CRDB-33510

Epic CRDB-34227

### PR DESCRIPTION
**Pull request by shralex**
Previously, slow requests were only logged at the range level, but the logs did not indicate which replica is slow. Moreover, the SlowRPC metric attempted to represent the number of requests currently being retried, however it was done on the range level and therefore missed a second level of replica-level retries being done underneath.

This PR adds logging on the replica level, removes a confusing log line, and changes the metric to count the number of slow requests in a simpler manner.

Epic: https://cockroachlabs.atlassian.net/browse/CRDB-33510
Fixes: https://github.com/cockroachdb/cockroach/issues/114431

### CODE REVIEW

**Review by andrewbaptist — CHANGES_REQUESTED** [review]
See the comments inline. I'm concerned if we ONLY count individual requests and not the retries we won't correctly detect problems with requests that are retried for a long time before completing and could actually lose observability. It would also be nice to separate out requests so that we can use a shorter timeout like you do here (of 3s) without triggering it too often.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117117#-:-NnFfuKq2UPS4SJkiu5-:b-3ekdn4)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @shralex)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 312 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117117#-NnFZw8k8WcVlux9P7k9:-NnFZw8k8WcVlux9P7kA:bh8rvth) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecc1a9912454984c4d6bb14bc8a6c178c940cb7c/pkg/kv/kvclient/kvcoord/dist_sender.go#L312)):*
> ```Go
> 	InLeaseTransferBackoffs            *metric.Counter
> 	RangeLookups                       *metric.Counter
> 	SlowRPCs                           *metric.Counter
> ```

I don't think it is generally safe to convert from `Gauge` to `Counter`. At a minimum spin up a mixed mode cluster and verify that both the AdminUI and Grafana can handle when it is running in this mode. 

As this is fundamentally changing the meaning, from current number which is a gauge, to total ever which is a counter, it makes sense to rename this. and deprecate the old gauge.

Looking at the other changes, I think it is best to create `distsender.slow.replica` and `distsender.slow.batch`.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 1921 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117117#-NnFan185ERppO5UbyCL:-NnFan185ERppO5UbyCM:b-8cwc6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecc1a9912454984c4d6bb14bc8a6c178c940cb7c/pkg/kv/kvclient/kvcoord/dist_sender.go#L1921)):*
> ```Go
> 		prevTok = routingTok
> 		reply, err = ds.sendToReplicas(ctx, ba, routingTok, withCommit)
> 		if dur := timeutil.Since(tBegin); dur > slowDistSenderRangeThreshold && !tBegin.IsZero() {
> ```

I'm confused why you aren't incrementing the metric here anymore. If you create the second metric then it should just be incremented when this longer timeout is hit. Maybe this is intentional since you don't care how long it takes for the entire request, but then you will miss counting requests that retry for a long period of time. 
___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 2189 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117117#-NnFb50E20hADI2w85qo:-NnFb50E20hADI2w85qp:b-fpyiyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecc1a9912454984c4d6bb14bc8a6c178c940cb7c/pkg/kv/kvclient/kvcoord/dist_sender.go#L2189)):*
> ```Go
> // slowDistSenderRangeThreshold is a latency threshold for logging slow requests to a range,
> // potentially involving RPCs to multiple replicas of the range.
> const slowDistSenderRangeThreshold = time.Minute
> ```

nit: I would rename these to `slowDistSenderBatchTimeout` and `slowDistSenderReplicaTimeout`

When I first read this I thought this was referring to `Scan` vs `Point` requests. 
___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 2419 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117117#-NnFc5RO7ZVZH68RvRRE:-NnFc5RO7ZVZH68RvRRF:b-bifhv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecc1a9912454984c4d6bb14bc8a6c178c940cb7c/pkg/kv/kvclient/kvcoord/dist_sender.go#L2419)):*
> ```Go
> 			var s redact.StringBuilder
> 			// Note that these RPC may or may not have succeeded. Errors are counted separately below.
> 			ds.metrics.SlowRPCs.Inc(1)
> ```

nit: some requests (for instance `ExportRequest`) often take a long time to return. I think we will trigger the SlowRPC here a lot if we include all requests.  There are alternatives to consider:
1) Create a static map of `RequestType` to `SlowThreshold`.
1) Exclude requests that have an `AdmissionHeader` lower than `NormalPriority`
2) Create separate stats and timeouts based on the admission header priority.
3) (most complex) - track "expected time" for each type of request and for Batches with multiple requests, track the time of the "slowest" request in the batch. When it logs/warns, it could print both the expected and actual time. This could be hard to get right and I'm not sure if its worth the effort.

**Review by shralex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117117)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 312 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117117#-NnFZw8k8WcVlux9P7k9:-NnL5m455v-IWXzfBwUn:b4jxfpk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecc1a9912454984c4d6bb14bc8a6c178c940cb7c/pkg/kv/kvclient/kvcoord/dist_sender.go#L312)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

I don't think it is generally safe to convert from `Gauge` to `Counter`. At a minimum spin up a mixed mode cluster and verify that both the AdminUI and Grafana can handle when it is running in this mode. 

As this is fundamentally changing the meaning, from current number which is a gauge, to total ever which is a counter, it makes sense to rename this. and deprecate the old gauge.

Looking at the other changes, I think it is best to create `distsender.slow.replica` and `distsender.slow.batch`.
</blockquote></details>

Ack. I added a new metric, and kept the previous one unchanged. Regarding replica vs batch, this might not be the right distinction since my understanding is that we send to individual replicas is also request batches.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 1921 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117117#-NnFan185ERppO5UbyCL:-NnL6SmHBQNWQS2NkSGh:b-li2p02) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecc1a9912454984c4d6bb14bc8a6c178c940cb7c/pkg/kv/kvclient/kvcoord/dist_sender.go#L1921)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

I'm confused why you aren't incrementing the metric here anymore. If you create the second metric then it should just be incremented when this longer timeout is hit. Maybe this is intentional since you don't care how long it takes for the entire request, but then you will miss counting requests that retry for a long period of time.
</blockquote></details>

I reverted my changes here.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 2189 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117117#-NnFb50E20hADI2w85qo:-NnL6b-4E6Vrj3TSXqUW:bb5zov8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecc1a9912454984c4d6bb14bc8a6c178c940cb7c/pkg/kv/kvclient/kvcoord/dist_sender.go#L2189)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: I would rename these to `slowDistSenderBatchTimeout` and `slowDistSenderReplicaTimeout`

When I first read this I thought this was referring to `Scan` vs `Point` requests.
</blockquote></details>

As mentioned above,  batch versus replica might not be the right distinction. We can discuss offline.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 2419 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117117#-NnFc5RO7ZVZH68RvRRE:-NnL6jdc2olPKUI6afWF:b-s1s2i9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecc1a9912454984c4d6bb14bc8a6c178c940cb7c/pkg/kv/kvclient/kvcoord/dist_sender.go#L2419)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: some requests (for instance `ExportRequest`) often take a long time to return. I think we will trigger the SlowRPC here a lot if we include all requests.  There are alternatives to consider:
1) Create a static map of `RequestType` to `SlowThreshold`.
1) Exclude requests that have an `AdmissionHeader` lower than `NormalPriority`
2) Create separate stats and timeouts based on the admission header priority.
3) (most complex) - track "expected time" for each type of request and for Batches with multiple requests, track the time of the "slowest" request in the batch. When it logs/warns, it could print both the expected and actual time. This could be hard to get right and I'm not sure if its worth the effort.
</blockquote></details>

Thanks for these suggestions! I did (2).

**Review by andrewbaptist — APPROVED** [review]
:lgtm:

Thanks for the changes!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117117#-:-NpBg2XVDqRqcBb3vZEX:blyazfu)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117117)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist and @shralex)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 163 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117117#-Np_HGiV7fIQnr3Sn-rp:-Np_HGiV7fIQnr3Sn-rq:b-tcba52) ([raw file](https://github.com/cockroachdb/cockroach/blob/88d10632cabdb629e0ce2b3307e1041a62ab8f00/pkg/kv/kvclient/kvcoord/dist_sender.go#L163)):*
> ```Go
> 	metaDistSenderSlowRPCs = metric.Metadata{
> 		Name: "requests.slow.distsender",
> 		Help: `Number of replica-bound RPCs currently stuck or retrying for a long time.
> ```

s/replica/range/
___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 2221 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117117#-Np_TQWO3wQ-UqSO7oQ8:-Np_TQWO3wQ-UqSO7oQ9:bpm0bll) ([raw file](https://github.com/cockroachdb/cockroach/blob/88d10632cabdb629e0ce2b3307e1041a62ab8f00/pkg/kv/kvclient/kvcoord/dist_sender.go#L2221)):*
> ```Go
> const slowDistSenderRangeThreshold = time.Minute
> 
> // slowDistSenderReplicaThreshold is a latency threshold for logging a slow RPC to a single replica.
> ```

nit: wrap at 80 chars?
___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 2446 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117117#-Np_U1p-A1LML7tYtBtV:-Np_U1p-A1LML7tYtBtW:b-3s5aic) ([raw file](https://github.com/cockroachdb/cockroach/blob/88d10632cabdb629e0ce2b3307e1041a62ab8f00/pkg/kv/kvclient/kvcoord/dist_sender.go#L2446)):*
> ```Go
> 		tBegin := timeutil.Now() // for slow log message
> 		br, err = transport.SendNext(ctx, ba)
> 		if admissionpb.WorkPriority(ba.AdmissionHeader.Priority) >= admissionpb.NormalPri {
> ```

Instead of gating this entire check on the admission control priority, should we instead just adjust where we log and whether or not we increment the metric? For example, we could skip the metric and `log.Eventf` for `admissionpb.WorkPriority(ba.AdmissionHeader.Priority) < admissionpb.NormalPri` so that the message will at least make it into any traces.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 2447 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117117#-Np_TySu9S9X7nToaITp:-Np_TySu9S9X7nToaITq:bsbrjb6) ([raw file](https://github.com/cockroachdb/cockroach/blob/88d10632cabdb629e0ce2b3307e1041a62ab8f00/pkg/kv/kvclient/kvcoord/dist_sender.go#L2447)):*
> ```Go
> 		br, err = transport.SendNext(ctx, ba)
> 		if admissionpb.WorkPriority(ba.AdmissionHeader.Priority) >= admissionpb.NormalPri {
> 			if dur := timeutil.Since(tBegin); dur > slowDistSenderReplicaThreshold && !tBegin.IsZero() {
> ```

When will `tBegin` be zero?
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_test.go` line 4453 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117117#-Np_UThq9oe7kYMu3W3g:-Np_UThq9oe7kYMu3W3h:b-ozyzz5) ([raw file](https://github.com/cockroachdb/cockroach/blob/53e4efd389167110d687e5dea8bf915fe2582a25/pkg/kv/kvclient/kvcoord/dist_sender_test.go#L4453)):*
> ```Go
> 		exp := `slow RPC finished after 8.16s (120 attempts)`
> 		var s redact.StringBuilder
> 		slowRangeRPCReturnWarningStr(&s, dur, attempts)
> ```

Are we losing test coverage for `slowRangeRPCReturnWarningStr`?

**Review by shralex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117117)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist and @nvanbenschoten)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 163 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117117#-Np_HGiV7fIQnr3Sn-rp:-NpmXgTM6h8ivHqsNGAS:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/88d10632cabdb629e0ce2b3307e1041a62ab8f00/pkg/kv/kvclient/kvcoord/dist_sender.go#L163)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

s/replica/range/
</blockquote></details>

Done
___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 2221 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117117#-Np_TQWO3wQ-UqSO7oQ8:-NpmXU66ERkQLArzYC8V:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/88d10632cabdb629e0ce2b3307e1041a62ab8f00/pkg/kv/kvclient/kvcoord/dist_sender.go#L2221)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: wrap at 80 chars?
</blockquote></details>

Done
___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 2446 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117117#-Np_U1p-A1LML7tYtBtV:-NpmXW849Z-GoZRLvcIo:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/88d10632cabdb629e0ce2b3307e1041a62ab8f00/pkg/kv/kvclient/kvcoord/dist_sender.go#L2446)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Instead of gating this entire check on the admission control priority, should we instead just adjust where we log and whether or not we increment the metric? For example, we could skip the metric and `log.Eventf` for `admissionpb.WorkPriority(ba.AdmissionHeader.Priority) < admissionpb.NormalPri` so that the message will at least make it into any traces.
</blockquote></details>

Done
___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 2447 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117117#-Np_TySu9S9X7nToaITp:-NpmXYen5L9xF7IaJ5j8:ba3dfob) ([raw file](https://github.com/cockroachdb/cockroach/blob/88d10632cabdb629e0ce2b3307e1041a62ab8f00/pkg/kv/kvclient/kvcoord/dist_sender.go#L2447)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

When will `tBegin` be zero?
</blockquote></details>

Removed
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_test.go` line 4453 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117117#-Np_UThq9oe7kYMu3W3g:-NpmX_zG16bHFyoVaQD-:b6e4t5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/53e4efd389167110d687e5dea8bf915fe2582a25/pkg/kv/kvclient/kvcoord/dist_sender_test.go#L4453)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Are we losing test coverage for `slowRangeRPCReturnWarningStr`?
</blockquote></details>

Added it back

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117117#-:-NprIV_OERgFmezqPlVK:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist and @shralex)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 2224 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117117#-NprI0zQDrb48sz3efra:-NprI0zQDrb48sz3efrb:b19nsao) ([raw file](https://github.com/cockroachdb/cockroach/blob/c515cb7a0c90b2e0a645847cd798f788e6ee320a/pkg/kv/kvclient/kvcoord/dist_sender.go#L2224)):*
> ```Go
> // slowDistSenderReplicaThreshold is a latency threshold for logging a slow RPC
> // to a single replica.
> const slowDistSenderReplicaThreshold = 3 * time.Second
> ```

3 seconds feels a little low to me. If we're going to make this a constant, then should we bump this to something a little less prone to triggering under normal conditions for expensive requests? Maybe 10 seconds?

**Review by shralex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117117)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andrewbaptist and @nvanbenschoten)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 2224 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117117#-NprI0zQDrb48sz3efra:-Nps8J999ZQ6L83z-ixF:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c515cb7a0c90b2e0a645847cd798f788e6ee320a/pkg/kv/kvclient/kvcoord/dist_sender.go#L2224)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

3 seconds feels a little low to me. If we're going to make this a constant, then should we bump this to something a little less prone to triggering under normal conditions for expensive requests? Maybe 10 seconds?
</blockquote></details>

Done

**Pull request merged**
