### PR TITLE
copy: fix extra flush loop causing test to flake

### LINKED ISSUE #101610: pkg/sql/copy/copy_test: TestLargeDynamicRows failed
pkg/sql/copy/copy_test.TestLargeDynamicRows [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9632591?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9632591?buildTab=artifacts#/) on release-23.1 @ [6cce6c746150307a9ecf3b529dfd633a6985c110](https://github.com/cockroachdb/cockroach/commits/6cce6c746150307a9ecf3b529dfd633a6985c110):

```
=== RUN   TestLargeDynamicRows
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/53491fdf16955d5896449a680358dad1/logTestLargeDynamicRows358695454
    test_log_scope.go:79: use -show-logs to present logs inline
    copy_test.go:594: 
        	Error Trace:	pkg/sql/copy/copy_test/pkg/sql/copy/copy_test.go:594
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 2
        	Test:       	TestLargeDynamicRows
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/53491fdf16955d5896449a680358dad1/logTestLargeDynamicRows358695454
--- FAIL: TestLargeDynamicRows (1.81s)
```
<p>Parameters: <code>TAGS=bazel,gss</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLargeDynamicRows.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-27058

### PR DESCRIPTION
**Pull request by cucaroach**
Release note: None
Epic: None
Fixes: #101610

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101792#-:-NTPc_PoB8xVUfciHLQj:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach)

**Comment by cucaroach** [comment]
bors retry

**Comment by cucaroach** [comment]
bors retry

**Comment by cucaroach** [comment]
bors retry

**Pull request merged**
