### PR TITLE
opt: Add rule to rewrite ANY to EXISTS in Select filter

### PR DESCRIPTION
**Pull request by andy-kimball**
If the Any operator is a conjunct in a Select filter, it can be rewritten
as an Exists operator. The Exists can in turn be hoisted as a SemiJoin
operator.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Nice!  :lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/opt/norm/factory.go, line 195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25130#-LB7pI6B1bWZ_2NSsWJl:-LB7pI6B1bWZ_2NSsWJm:b-2oir6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c35c599c0dae0d6fb56e6af1c4b8f5be0a2c68c/pkg/sql/opt/norm/factory.go#L195)):*
> ```Go
> }
> 
> // ReplaceListItem returns a new list that is a copy of the given list, except
> ```

[nit] replaceListItem

---

*[pkg/sql/opt/norm/factory.go, line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25130#-LB7voidEKn1B6dxAcrP:-LB7voidEKn1B6dxAcrQ:bmohcee) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c35c599c0dae0d6fb56e6af1c4b8f5be0a2c68c/pkg/sql/opt/norm/factory.go#L197)):*
> ```Go
> // ReplaceListItem returns a new list that is a copy of the given list, except
> // that the given search item has been replaced by the given replace item. If
> // the list contains the search item multiple times, then only the first
> ```

it looks like it replaces all instances

---

*[pkg/sql/opt/norm/testdata/select, line 875 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25130#-LB7wUh3DRnlYtrh_S8W:-LB7wUh3DRnlYtrh_S8X:bl6h1p0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c35c599c0dae0d6fb56e6af1c4b8f5be0a2c68c/pkg/sql/opt/norm/testdata/select#L875)):*
> ```
>            └── variable: b.y [type=int, outer=(7)]
> 
> # Don't hoist uncorrelated ANY (but rewrite it to EXISTS).
> ```

This query is deceiving, we should add some comments to clarify that `y` is not a column in `b`, and the inner query returns the outer value, repeated as many times as there are rows in `b`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25130#-:-LB7wqvwEwF_YeCIrmms:b-ypbbbp)*

**Comment by andy-kimball** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/opt/norm/factory.go, line 195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25130#-LB7pI6B1bWZ_2NSsWJl:-LBBfJ7u-etwy2PFvPO7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c35c599c0dae0d6fb56e6af1c4b8f5be0a2c68c/pkg/sql/opt/norm/factory.go#L195)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] replaceListItem
</blockquote></details>

Done.

---

*[pkg/sql/opt/norm/factory.go, line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25130#-LB7voidEKn1B6dxAcrP:-LBBgyu31HmNvnXqfyp0:b-k2rwtz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c35c599c0dae0d6fb56e6af1c4b8f5be0a2c68c/pkg/sql/opt/norm/factory.go#L197)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

it looks like it replaces all instances
</blockquote></details>

Good catch. Fixed.

---

*[pkg/sql/opt/norm/testdata/select, line 875 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25130#-LB7wUh3DRnlYtrh_S8W:-LBBh4XT1y0xb2zBfb6I:bbhx5ko) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c35c599c0dae0d6fb56e6af1c4b8f5be0a2c68c/pkg/sql/opt/norm/testdata/select#L875)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This query is deceiving, we should add some comments to clarify that `y` is not a column in `b`, and the inner query returns the outer value, repeated as many times as there are rows in `b`.
</blockquote></details>

`y` is a column in `b`. I went ahead and renamed `b` to `xy` to eliminate this source of confusion.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25130)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25130#-:-LBI8xPjAxtEkmoT6VRK:bnfp4nl)*

**Pull request merged**
