### PR TITLE
sctest: Make DML Injection Testing Framework More Readable

### PR DESCRIPTION
**Pull request by Xiang-Gu**
This commit tries to make the DML injection testing framework more readable and maintainable. 
It mostly added comments and reorganized some code. No function is changed.

Epic: None
Release note: None

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103813)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Xiang-Gu)

___
*[`pkg/sql/schemachanger/sctest/cumulative.go` line 465 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103813#-NWD2pDv0PF3M-EDWs2Y:-NWD2pDw0C-DzWOFmDqK:b5mwjx5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cc4319c0255bd9be8cbb4a8a7b81fb9613df6d2/pkg/sql/schemachanger/sctest/cumulative.go#L465)):*
> ```Go
> 			_, err := runner.DB.ExecContext(context.Background(), boundSQL)
> 			if (e.expectedOutput == "" ||
> 				idx != len(e.stmts)-1) && err != nil {
> ```

Think we still need the checking that only the last statement is allowed to create an error.
___
*[`pkg/sql/schemachanger/sctest/cumulative.go` line 873 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103813#-NWD3XHo378T_xbvijzX:-NWD3XHo378T_xbvijzY:b3gtt6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ccef9dd4107fb80dccdd43968fe485596ceaf6e/pkg/sql/schemachanger/sctest/cumulative.go#L873)):*
> ```Go
> 		_, db, cleanup := newCluster(t, &scexec.TestingKnobs{
> 			BeforeStage: func(p scplan.Plan, stageIdx int) error {
> 				if !clusterCreated {
> ```

Make this safer by using an atomic

**Review by Xiang-Gu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103813)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/schemachanger/sctest/cumulative.go` line 465 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103813#-NWD2pDv0PF3M-EDWs2Y:-NWDLo1K9vU0AxYWv-ft:b-6s6lvm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cc4319c0255bd9be8cbb4a8a7b81fb9613df6d2/pkg/sql/schemachanger/sctest/cumulative.go#L465)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Think we still need the checking that only the last statement is allowed to create an error.
</blockquote></details>

This does not really make much sense to me. I understood what you want to do if there are >1 stmts to execute in one DML injection block: 
1. Run each one in its own transaction ("runner.DB.ExecContext") 
2. If it's not the last stmt, and it encounters an error, we then either fail the test (if !rewrite) or record the error (if rewrite)
3. If it's the last stmt, and it encounters an error, we then either fail the test (if !rewrite) or record the error (if rewrite)

I expect the user (who is writing those DML injection blocks in the test file) to have only 1 stmt in a DML injection block if they expect the that DML returns an error.

Such a restriction is also somewhat artificial. Instead, I think we should execute all the stmts specified in one block at once in one transaction (i.e., treat them as one line with multiple stmts separated by semi-colons). That will require slightly more changes to the code (e.g. `stageExecStmt.stmts []string` will change to `stageExecStmt.stmt string` and it will be the literal string specified in the block, strip the "\n", and join them with ";"). I am not keen to make this change in this PR though.
___
*[`pkg/sql/schemachanger/sctest/cumulative.go` line 873 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103813#-NWD3XHo378T_xbvijzX:-NWDKXhQAsZvR0H3Z3sA:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ccef9dd4107fb80dccdd43968fe485596ceaf6e/pkg/sql/schemachanger/sctest/cumulative.go#L873)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Make this safer by using an atomic
</blockquote></details>

done

**Comment by Xiang-Gu** [comment]
TFTR!

bors r+

**Comment by fqazi** [comment]
> This does not really make much sense to me. I understood what you want to do if there are >1 stmts to execute in one DML injection block:
> 
> 1. Run each one in its own transaction ("runner.DB.ExecContext")
> 2. If it's not the last stmt, and it encounters an error, we then either fail the test (if !rewrite) or record the error (if rewrite)
> 3. If it's the last stmt, and it encounters an error, we then either fail the test (if !rewrite) or record the error (if rewrite)
> 
> I expect the user (who is writing those DML injection blocks in the test file) to have only 1 stmt in a DML injection block if they expect the that DML returns an error.
> 
> Such a restriction is also somewhat artificial. Instead, I think we should execute all the stmts specified in one block at once in one transaction (i.e., treat them as one line with multiple stmts separated by semi-colons). That will require slightly more changes to the code (e.g. `stageExecStmt.stmts []string` will change to `stageExecStmt.stmt string` and it will be the literal string specified in the block, strip the "\n", and join them with ";"). I am not keen to make this change in this PR though.

Thats the existing behaviour here, so I'm afraid we are going to have regressions that will get missed (i.e. if the first insert returns an error vs the second):
```
add_column_default_unique:stage-exec phase=PostCommitPhase stage=5:14 schemaChangeExecError=(.*duplicate key value violates unique constraint.*)
add_column_default_unique-INSERT INTO db.public.tbl VALUES($stageKey);
add_column_default_unique-INSERT INTO db.public.tbl VALUES($stageKey + 1);
```

**Review by fqazi — APPROVED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103813)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by Xiang-Gu** [comment]
TFTR!

bors r+

**Pull request merged**
