### PR TITLE
clusterversion: prep 23.1 release branch and initialize 23.2 development

### PR DESCRIPTION
**Pull request by celiala**
As part of the 23.1 stability period tasks, this PR preps the 23.1 release branch and initializes 23.2 development, as per this release runbook: [Prep Release and Define Start of Development for Next Release](https://cockroachlabs.atlassian.net/wiki/spaces/RE/pages/2924740768/Prep+Release+and+Define+Start+of+Development+for+Next+Release).

This PR will contain 4 commits:

|commit|backported when|
|-|-|
|1. Set developmentBranch to false|soon after branch cut / before selecting beta.1 candidate|
|2. Update version.txt to alpha.8 (next release)|soon after branch cut / before selecting ~beta.1~ this week's alpha.8 candidate|
|3. Mint the previous release|should be final backport before the final RC / before selecting final RC candidate|
|4. Define the start of 23.2 development and placeholder key|_(not backported)_|

Release note: none.
Epic: REL-283

### CODE REVIEW

**Review by dt — APPROVED** [review]

**Comment by celiala** [comment]
For 22.2 we did this a bit incrementally. Looking at the pieces, I think this is what should be done for 23.1.

Some open questions to still address:

1. what to set for `pkg/build/version.txt`: for master? to backport to the release-23.1 branch?
2. what should we be doing here for [BinaryVersionKey](https://github.com/cockroachdb/cockroach/blob/master/pkg/clusterversion/cockroach_versions.go#L958) (if anything)? maybe @healthy-pod 

For 1, I think maybe this should happen:
* for `release-23.1` branch: [pkg/build/version.txt](https://github.com/cockroachdb/cockroach/blob/master/pkg/build/version.txt) value becomes beta.1 (although if we still have release blockers then this should be alpha.8)
* for `master` branch: we won't be able to add the `v23.2-alpha.00000000` tag onto master until we've [initialized tests for 23.2 development](https://cockroachlabs.atlassian.net/wiki/spaces/RE/pages/2925166894/Initialize+Tests+for+Development+for+Next+Release). however, since we don't plan to release from master after the branch cut, maybe it's okay to keep version.txt as-is until the `v23.2-alpha.00000000` tag is in place

**Comment by healthy-pod** [comment]
> what should we be doing here for [BinaryVersionKey](https://github.com/cockroachdb/cockroach/blob/master/pkg/clusterversion/cockroach_versions.go#L958) (if anything)? maybe @healthy-pod

I think we should change this to `V23_2` but I will let someone else confirm. cc @dt 

I don't think we will bump min supported version but it might help to update `tenantCreationMinSupportedVersionKey` so we don't have to bump it every time min supported version changes (doesn't need to be in this PR). cc @ajstorm 

```
diff --git a/pkg/sql/tenant_creation.go b/pkg/sql/tenant_creation.go
index f3d41fa8690..44c193400e1 100644
--- a/pkg/sql/tenant_creation.go
+++ b/pkg/sql/tenant_creation.go
@@ -43,10 +43,6 @@ import (
 	"github.com/cockroachdb/redact"
 )
 
-const (
-	tenantCreationMinSupportedVersionKey = clusterversion.V22_2
-)
-
 // CreateTenant implements the tree.TenantOperator interface.
 func (p *planner) CreateTenant(
 	ctx context.Context, parameters string,
@@ -159,8 +155,8 @@ func (p *planner) createTenantInternal(
 		// Use the previous major version to create the tenant and bootstrap it
 		// just like the previous major version binary would, using hardcoded
 		// initial values.
-		tenantVersion.Version = clusterversion.ByKey(tenantCreationMinSupportedVersionKey)
-		bootstrapVersionOverride = tenantCreationMinSupportedVersionKey
+		tenantVersion.Version = clusterversion.ByKey(clusterversion.BinaryMinSupportedVersionKey)
+		bootstrapVersionOverride = clusterversion.BinaryMinSupportedVersionKey
 	} else {
 		// The cluster is running the latest version.
 		// Use this version to create the tenant and bootstrap it using the host

```

**Comment by celiala** [comment]
> I think we should change this to V23_2 but I will let someone else confirm. cc @dt

This makes sense to me. I'll advance [BinaryVersionKey](https://github.com/cockroachdb/cockroach/blob/master/pkg/clusterversion/cockroach_versions.go?rgh-link-date=2023-03-21T19%3A22%3A17Z#L958) to `V23_2`, as part of this commit: `clusterverion: start 23.2 dev versions`

> for [pkg/build/version.txt](https://github.com/cockroachdb/cockroach/blob/master/pkg/build/version.txt?rgh-link-date=2023-03-21T19%3A22%3A17Z)

For version.txt, I'll set this to `v23.1.0-alpha.8`:
* We have enough release blockers (https://go.crdb.dev/23-1-blockers) where an alpha feels more realistic than a beta for this week.
* I think this master version.txt can stay at `v23.1.0-alpha.8` until we've initialized tests and tagged master with `v23.2-alpha.00000000`


> it might help to update tenantCreationMinSupportedVersionKey ...(doesn't need to be in this PR).

ack :)

**Review by rail — APPROVED** [review]

**Comment by renatolabs** [comment]
> although if we still have release blockers then this should be alpha.8

Just to confirm if I understand it right: do we release another alpha (off of `release-23.1`) depending on the status/amount of release blockers?

> I think this master version.txt can stay at v23.1.0-alpha.8 until we've initialized tests and tagged master with v23.2-alpha.00000000

Makes sense to me. At that point, we'd update `version.txt` to be `23.2-alpha.00000000` as well, yes?

**Comment by celiala** [comment]
> Just to confirm if I understand it right: do we release another alpha (off of release-23.1) depending on the status/amount of release blockers?

Correct/exactly, i.e.:
 
* once we cut the release branch, we should no longer select 23.1 candidate SHAs off of master
* what we end up calling the 23.1 candidate SHA depends on blocker status (if we still have release-blockers, we should all it an alpha. but still select the SHA from `release-23.1`)

**Comment by celiala** [comment]
flake - Bazel Essential CI (Cockroach) UnusedLint: "Error in fail: generate_build_file.ts failed". retriggering.

**Comment by celiala** [comment]
bors r=dt,rail

**Pull request merged**
