### PR TITLE
ccl/oidcccl: TestOIDCEnabled failed under stress

### LINKED ISSUE #130637: ccl/oidcccl: TestOIDCEnabled failed
ccl/oidcccl.TestOIDCEnabled [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/16868508?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/16868508?buildTab=artifacts#/) on release-23.2 @ [a1a1bf97dd897f3f93b08ac8382bca2af2fd04d7](https://github.com/cockroachdb/cockroach/commits/a1a1bf97dd897f3f93b08ac8382bca2af2fd04d7):

```
=== RUN   TestOIDCEnabled
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/3ed8b395931fde05baf66bd2e4d88d97/logTestOIDCEnabled197546267
    test_log_scope.go:81: use -show-logs to present logs inline
    test_server_shim.go:159: automatically injected an external process virtual cluster under test; see comment at top of test_server_shim.go for details.
    authentication_oidc_test.go:209: expected to be redirected to root
    panic.go:523: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/3ed8b395931fde05baf66bd2e4d88d97/logTestOIDCEnabled197546267
--- FAIL: TestOIDCEnabled (13.83s)
```

Parameters:
 - <code>TAGS=bazel,gss,deadlock</code>
 - <code>stress=true</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/obs-prs
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestOIDCEnabled.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-42150

### PR DESCRIPTION
**Pull request by pritesh-lahoti**
TestOIDCEnabled used to update the OIDC related cluster settings via SQL. This takes time to get reflected within the application handler and flakes the test under stress.

Updated the unit test to directly override cluster setting values within the application.

Fixes: #130637

Release note: None

### CODE REVIEW

**Review by souravcrl — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131180#-:-O7TV9dh1tMYhVFJy23H:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pritesh-lahoti)

**Review by sanchit-CRL — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131180)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pritesh-lahoti)

**Comment by pritesh-lahoti** [comment]
bors merge

**Comment by pritesh-lahoti** [comment]
blathers backport 24.2

**Pull request merged**
