### PR TITLE
cli: fix TestFlagUsage

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9686)

### CODE REVIEW

**Comment by tamird** [comment]
This test depends on flags passed to it, and in CI, we pass `--verbosity` and `--vmodule`, so this won't pass CI.

**Comment by petermattis** [comment]
Ah, that's why this is only failing locally for me. Any suggestion on how to fix? I suppose I could clear the `--verbosity` and `--vmodule` flags in the test.

**Comment by tamird** [comment]
That's one way. Another way is to send a PR upstream to always print the
defaults, regardless of the flag being set.

**Comment by petermattis** [comment]
@tamird Care to do the upstream change?

**Comment by petermattis** [comment]
Changed the fix so we ignore the `--vmodule` and `--verbosity` lines.

**Comment by tamird** [comment]
OK, LGTM.

**Pull request merged**
