### PR TITLE
cli: add debug doctor command

### LINKED ISSUE #52077: sql: schema verification tool over debug.zip
Add a `cockroach debug` command that runs a full schema verification over the schemas present in a `debug.zip`.

### PR DESCRIPTION
**Pull request by spaskob**
This PR introduces two new debug commands:
`/cockroach debug doctor cluster --url=<cluster_conn_string>`
and
`/cockroach debug doctor zipdir <debug-dir>`

which will validate the descriptors of a live cluster or from an unzipped debug
directory respectfully. The commands print out all descriptor ids that were inspected
and the problems with specific ids if found.

Fixes #52077.
Informs #51153.

Release note: none.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52622)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @spaskob)

___
*[pkg/sql/sqlbase/descriptor.go, line 221 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52622#-MESNLfg1YbX4Rwmuhzt:-MESNLfg1YbX4Rwmuhzu:bg38f6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/d42479a756fe78d416c9a0e0f24a67bcec08c94c/pkg/sql/sqlbase/descriptor.go#L221)):*
> ```Go
> 		// CreateAsOfTime that it is now set.
> 		if t.Table.Adding() && t.Table.IsAs() && t.Table.CreateAsOfTime.IsEmpty() {
> 			log.Fatalf(context.TODO(), "table descriptor for %q (%d.%d) is in the "+
> ```

I wonder if it would make sense to error out with an assertion error instead of stopping the server in this condition.
___
*[pkg/sql/sqlbase/descriptor.go, line 238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52622#-MESLvbl1acyPDvGlmUg:-MESLvbm0nOq_NBiWQeB:b-f6r0p7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d42479a756fe78d416c9a0e0f24a67bcec08c94c/pkg/sql/sqlbase/descriptor.go#L238)):*
> ```Go
> 		// are rendered in some other downstream setting we expect the timestamp to
> 		// be read. This is a hack we shouldn't need to do.
> 		log.Errorf(context.TODO(), "read table descriptor for %q (%d) without ModificationTime "+
> ```

I think the behavior (error vs fatal) should be dependent on a boolean. In a running server, this error should ensure the caller does not get a chance to use the descriptor. See my comment above.

**Review by spaskob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52622)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @knz, and @spaskob)

___
*[pkg/sql/sqlbase/descriptor.go, line 221 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52622#-MESNLfg1YbX4Rwmuhzt:-MEbIWPMEEwrr0coMKBX:bnl89w6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d42479a756fe78d416c9a0e0f24a67bcec08c94c/pkg/sql/sqlbase/descriptor.go#L221)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I wonder if it would make sense to error out with an assertion error instead of stopping the server in this condition.
</blockquote></details>

@ajwerner  suggested an approach to read the ts from crdb
_intenal and for debug.zip setting any non-zero ts makes the error go away. We could look into dumping the timestamp in debug.zip as well.

**Review by knz — COMMENTED** [review]
A few general thoughts:
- you don't need to invest too much into polish since this is a debug command.
- however, you probably do want some tests. So I recommend some tests that injects invalid descriptors and verifies that the function finds the errors
- the commit message (and PR description) should be scoped down to what this PR actually does. It's OK to talk about "future plans" in an *issue* (which is not filed yet as far as I can see, *so you should file it* and refer to it from the PR). It's not OK to talk about future plans in the commit message. The commit message should describe objectively what's contained in the commit.
- the release note is IMHO premature since the work is not complete yet. If you do keep it, you need to start the release note with a description of what tool was introduced. Remember, the release note is pasted into docs without any reference to the PR or any title.

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52622#-:-MEbnhieCp-saTSrP-0o:bgt0l02)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @spaskob)

___
*[pkg/sql/sqlbase/descriptor.go, line 221 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52622#-MESNLfg1YbX4Rwmuhzt:-MEbnZ7-1Bdl7jys359H:b52ebps) ([raw file](https://github.com/cockroachdb/cockroach/blob/d42479a756fe78d416c9a0e0f24a67bcec08c94c/pkg/sql/sqlbase/descriptor.go#L221)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

@ajwerner  suggested an approach to read the ts from crdb
_intenal and for debug.zip setting any non-zero ts makes the error go away. We could look into dumping the timestamp in debug.zip as well.
</blockquote></details>

The mvcc timestamp is now available from SQL, thanks to the changes by Rohan. Perhaps you can pick that up.
___
*[pkg/sql/sqlbase/descriptor.go, line 238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52622#-MESLvbl1acyPDvGlmUg:-MEbneCf48Vpng9e2ts-:bqoiqxh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d42479a756fe78d416c9a0e0f24a67bcec08c94c/pkg/sql/sqlbase/descriptor.go#L238)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think the behavior (error vs fatal) should be dependent on a boolean. In a running server, this error should ensure the caller does not get a chance to use the descriptor. See my comment above.
</blockquote></details>

I still stand by this point.

**Review by spaskob — COMMENTED** [review]
Thanks for the general remarks! I updated the PR description and linked 2 relevant issues. I will be adding the tests shortly.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52622#-:-MEfeG1G2qoieLh8O5Qc:byw1tx0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @knz)

___
*[pkg/sql/sqlbase/descriptor.go, line 221 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52622#-MESNLfg1YbX4Rwmuhzt:-MEfduaCA_0UlrdGT7oD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d42479a756fe78d416c9a0e0f24a67bcec08c94c/pkg/sql/sqlbase/descriptor.go#L221)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

The mvcc timestamp is now available from SQL, thanks to the changes by Rohan. Perhaps you can pick that up.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/descriptor.go, line 238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52622#-MESLvbl1acyPDvGlmUg:-MEfdyQF4IUGDSzfWsYS:byo6ccu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d42479a756fe78d416c9a0e0f24a67bcec08c94c/pkg/sql/sqlbase/descriptor.go#L238)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I still stand by this point.
</blockquote></details>

This is unrelated to this PR anymore so I'd leave it to @ajwerner to decide if we need to file an issue to change this function prototype.

**Review by knz — COMMENTED** [review]
This is pretty good for a MVP!
I just have a small suggestion below as to API.

I'd also like to renew my suggestion to unit test the Examine function in addition to the command-line test you already have, to test a larger variety of problem cases, and show the diversity of output messages that can be encountered.

I also recommend you rebase to recover from the flaky test that blocks your CI. 

> Reviewed 2 of 6 files at r1, 5 of 5 files at r3, 1 of 1 files at r4, 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52622#-:-MF0XB4e9qeZ8KzodKKR:b-idxbsc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @spaskob)

___
*[pkg/sql/doctor/doctor.go, line 72 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52622#-MF0W1qF8vxX5qIwsMKG:-MF0W1qF8vxX5qIwsMKH:b9a2np3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dd2fc7e8eee9baca48dc704cb4f363a6ca18ba1/pkg/sql/doctor/doctor.go#L72)):*
> ```Go
> 		table := sqlbase.NewImmutableTableDescriptor(*sqlbase.TableFromDescriptor(desc, ts))
> 		if int64(table.ID) != row.ID {
> 			fmt.Printf("Table %3d: different id in the descriptor: %d", row.ID, table.ID)
> ```

I recommend you replace the `fmt.Printf` by `fmt.Fprintf` and pass an `io.Writer` as argument to the function.

This will make your testing easier, as this way you can redirect the output to e.g. a bytes.Buffer and compare strings directly.

**Comment by spaskob** [comment]
PTAL, tests for `doctor.Examine` added.

**Review by knz — COMMENTED** [review]
Cool, just a few nits and this is good to go.

> Reviewed 3 of 8 files at r6, 3 of 5 files at r8, 4 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52622#-:-MF4g38K7CE-iJSl8-zv:b-xcbeu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @knz, and @spaskob)

___
*[pkg/cli/doctor.go, line 81 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/52622#-MF4dvGwDloUoLQ7UCU1:-MF4dvGwDloUoLQ7UCU2:b-h40b3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d86accc8c7a50fc8b9f8c3d0eca332ce867f697/pkg/cli/doctor.go#L81)):*
> ```Go
> }
> 
> // RunClusterDoctor runs the doctors tool reading data from a live cluster.
> ```

nit: if you don't use the functions in a different package, then also un-export them.
___
*[pkg/cli/doctor.go, line 138 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/52622#-MF4e-Xf1V1wtOvotm1z:-MF4e-Xf1V1wtOvotm2-:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d86accc8c7a50fc8b9f8c3d0eca332ce867f697/pkg/cli/doctor.go#L138)):*
> ```Go
> 
> // RunZipDirDoctor runs the doctors tool reading data from a debug zip dir.
> func RunZipDirDoctor(cmd *cobra.Command, args []string) (retErr error) {
> ```

ditto
___
*[pkg/sql/doctor/doctor.go, line 56 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/52622#-MF4eLS4A-I-F25hg4MC:-MF4eLS4A-I-F25hg4MD:b-9u8o6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d86accc8c7a50fc8b9f8c3d0eca332ce867f697/pkg/sql/doctor/doctor.go#L56)):*
> ```Go
> 
> // Examine runs a suite of consistency checks over the descriptor table.
> func Examine(descTable []DescriptorTableRow, verbose bool, stdout io.Writer) (bool, error) {
> ```

Our style recommendation is to name the return values when it's not clear what they mean.
Generally, if a function returns a bool and it's not a predicate (ie a function named "IsXXXX" where the bool clearly says yes/no), then it's unclear what the bool is about.

So the "bool" return here should probably be named "ok".
___
*[pkg/sql/doctor/doctor.go, line 67 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/52622#-MF4eg_V5veoE-Z2UkKe:-MF4eg_V5veoE-Z2UkKf:b-g3wv9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d86accc8c7a50fc8b9f8c3d0eca332ce867f697/pkg/sql/doctor/doctor.go#L67)):*
> ```Go
> 		t := sqlbase.TableFromDescriptor(desc, hlc.Timestamp{})
> 		if t == nil {
> 			continue
> ```

I recommend a comment here to explain what it means to ignore the table descriptor.
___
*[pkg/sql/doctor/doctor.go, line 79 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/52622#-MF4enOs5icT-U3-lZxD:-MF4enOs5icT-U3-lZxE:b-1z61g3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d86accc8c7a50fc8b9f8c3d0eca332ce867f697/pkg/sql/doctor/doctor.go#L79)):*
> ```Go
> 		if err := table.Validate(context.Background(), protoGetter, keys.SystemSQLCodec); err != nil {
> 			problemsFound = true
> 			fmt.Fprintf(stdout, "Table %3d: %s\n", table.ID, err.Error())
> ```

You don't need to call `.Error()` on `err`. Printf does it for you already.
___
*[pkg/sql/sqlbase/descriptor.go, line 239 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/52622#-MF4eyE5COreBxuIteC_:-MF4eyE5COreBxuIteCa:bmu2z9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d86accc8c7a50fc8b9f8c3d0eca332ce867f697/pkg/sql/sqlbase/descriptor.go#L239)):*
> ```Go
> 		// be read. This is a hack we shouldn't need to do.
> 		log.Fatalf(context.TODO(), "read table descriptor for %q (%d) without ModificationTime "+
> 			"with zero MVCC timestamp; full descriptor:\n%s", GetDescriptorName(desc), GetDescriptorID(desc), desc.String())
> ```

FYI, printf-style formatting already calls `.String()` on objects.

The only reason why we sometimes call `.String()` explicitly is to avoid the object escaping to the heap, *if it wasn't on the heap already*. 

In this particular case, you're receiving `desc` by reference, so it's already on the heap, so no need to call `.String()`.

**Review by spaskob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52622)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @knz)

___
*[pkg/cli/doctor.go, line 138 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/52622#-MF4e-Xf1V1wtOvotm1z:-MF4i4iz9q73FaidXaal:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d86accc8c7a50fc8b9f8c3d0eca332ce867f697/pkg/cli/doctor.go#L138)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/doctor/doctor.go, line 56 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/52622#-MF4eLS4A-I-F25hg4MC:-MF4iN0d4UEjpqvR9nKP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d86accc8c7a50fc8b9f8c3d0eca332ce867f697/pkg/sql/doctor/doctor.go#L56)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Our style recommendation is to name the return values when it's not clear what they mean.
Generally, if a function returns a bool and it's not a predicate (ie a function named "IsXXXX" where the bool clearly says yes/no), then it's unclear what the bool is about.

So the "bool" return here should probably be named "ok".


</blockquote></details>

Done.
___
*[pkg/sql/doctor/doctor.go, line 67 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/52622#-MF4eg_V5veoE-Z2UkKe:-MF4iYny0Z1DKlz0DUf_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d86accc8c7a50fc8b9f8c3d0eca332ce867f697/pkg/sql/doctor/doctor.go#L67)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I recommend a comment here to explain what it means to ignore the table descriptor.
</blockquote></details>

Done.
___
*[pkg/sql/doctor/doctor.go, line 79 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/52622#-MF4enOs5icT-U3-lZxD:-MF4ijEe0Er4kHS61-mq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d86accc8c7a50fc8b9f8c3d0eca332ce867f697/pkg/sql/doctor/doctor.go#L79)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You don't need to call `.Error()` on `err`. Printf does it for you already.
</blockquote></details>

Done.

**Review by spaskob — COMMENTED** [review]
PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52622#-:-MF4k7wf4Bz9JK7KqbkA:bb71pro)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @knz)

**Review by knz — APPROVED** [review]
:lgtm: nice :)

> Reviewed 1 of 5 files at r12, 1 of 5 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52622#-:-MF4uh688OOcwL-sYHLH:b-h8s8wp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @knz)

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 9 files at r10, 1 of 5 files at r12, 3 of 5 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52622#-:-MF68-aoEexebPrIMLTf:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ajwerner, @knz, and @spaskob)

___
*[pkg/sql/doctor/doctor.go, line 11 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/52622#-MF67msD8MKSksPJ5k_A:-MF67msD8MKSksPJ5k_B:bloc74e) ([raw file](https://github.com/cockroachdb/cockroach/blob/1559ff2089516125ebd6cf89dc9bdcd3cca63b8f/pkg/sql/doctor/doctor.go#L11)):*
> ```Go
> // licenses/APL.txt.
> 
> package doctor
> ```

nit: can you add a doc comment

**Pull request merged**
