### PR TITLE
sql/distsql: improve APIs to allow the gateway to run flows directly

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6943)

### CODE REVIEW

**Comment by andreimatei** [comment]
:lgtm:

<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> #### sql/distsql: improve APIs to allow the gateway to run flows directly
</details>


---

Review status: 0 of 6 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[sql/distsql/base.go, line 48 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6943#-KIn-iXKTN_omw2zct_x:-KIn-iXKTN_omw2zct_y:-722029957) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4828ef8eda9f5d71b2566483daa2242ad03aade/sql/distsql/base.go#L48)):*
> ```Go
> }
> 
> // RowChannel is a thin layer over a StreamMsg channel
> ```

but this comment doesn't say what the point is.

---

*[sql/distsql/base.go, line 72 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6943#-KIn1vk9kDXPxraRbP0q:-KIn1vk9kDXPxraRbP0r:294794141) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4828ef8eda9f5d71b2566483daa2242ad03aade/sql/distsql/base.go#L72)):*
> ```Go
> func (rc *RowChannel) PushRow(row sqlbase.EncDatumRow) bool {
> 	if atomic.LoadUint32(&rc.noMoreRows) == 1 {
> 		return false
> ```

can we `panic` here instead, and not return anything?

---

*[sql/distsql/base.go, line 80 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6943#-KIn1hGoGPFfL2bXswdv:-KIn1hGoGPFfL2bXswdw:-474811455) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4828ef8eda9f5d71b2566483daa2242ad03aade/sql/distsql/base.go#L80)):*
> ```Go
> 
> // Close is part of the rowReceiver interface.
> func (rc *RowChannel) Close(err error) {
> ```

I found having both `Close` and `NoMoreRows` confusing. Maybe we can call one `CloseReader` and the other `CloseWriter`?

---

*[sql/distsql/base.go, line 41 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6943#-KIn29ifVmWoWtH9W5R4:-KIn29ifVmWoWtH9W5R5:1817439149) ([raw file](https://github.com/cockroachdb/cockroach/blob/64a7c26b6d76005703cc23b2831623675d5e671c/sql/distsql/base.go#L41)):*
> ```Go
> }
> 
> type processor interface {
> ```

this deserves a comment :)

---

*[sql/distsql/base.go, line 65 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6943#-KIn3WcpcsuvcbrXsJCg:-KIn3WcpcsuvcbrXsJCh:-462508293) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0c4eaa1816ebb0da1f792d3f589e065fc08b122/sql/distsql/base.go#L65)):*
> ```Go
> 	noMoreRows uint32
> 
> 	rowBuf []sqlbase.EncDatum
> ```

how about `datumBuf`?

---

*[sql/distsql/base.go, line 77 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6943#-KIn4TCOz4FfxaZTj--B:-KIn4TCOz4FfxaZTj--C:1977830828) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0c4eaa1816ebb0da1f792d3f589e065fc08b122/sql/distsql/base.go#L77)):*
> ```Go
> 
> // PushRow is part of the rowReceiver interface.
> func (rc *RowChannel) PushRow(row sqlbase.EncDatumRow) bool {
> ```

comment that `PushRow` makes a copy of the slice, so the arg can be reused

---

*[sql/distsql/base.go, line 81 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6943#-KIn3ni90iqNd5iohZ7Q:-KIn3ni90iqNd5iohZ7R:1766009680) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0c4eaa1816ebb0da1f792d3f589e065fc08b122/sql/distsql/base.go#L81)):*
> ```Go
> 		return false
> 	}
> 	num := len(row)
> ```

nit: num->cols

---

*[sql/distsql/base.go, line 91 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6943#-KIn4k9rp-p1VN-bNxWE:-KIn4k9rp-p1VN-bNxWF:-1920491654) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0c4eaa1816ebb0da1f792d3f589e065fc08b122/sql/distsql/base.go#L91)):*
> ```Go
> 	rowCopy := sqlbase.EncDatumRow(rc.rowBuf[:num:num])
> 	rc.rowBuf = rc.rowBuf[len(row):]
> 	copy(rowCopy, row)
> ```

I don't really get it - why does the buffer need to live in `RowChannel`? Can't it live in `RowChannel`'s client? Is it because you think there'll be many clients?
Another option is to write a `DatumSlab` and have clients share that if they want efficient allocation.

It's also fine as it is. I dunno, just seemed a bit weird that this class would always do this copy and allocation, even if the client doesn't need it.

---

*[sql/distsql/flow.go, line 31 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6943#-KIn2ST5Db4C8W-dDouA:-KIn2ST5Db4C8W-dDouB:642344717) ([raw file](https://github.com/cockroachdb/cockroach/blob/64a7c26b6d76005703cc23b2831623675d5e671c/sql/distsql/flow.go#L31)):*
> ```Go
> 	evalCtx          parser.EvalContext
> 	txn              *client.Txn
> 	simpleFlowOutput rowReceiver
> ```

how about `simpleFlowConsumer`?

---

*[sql/distsql/tablereader.go, line 182 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6943#-KIn2zHUhLwyvr1eOIBY:-KIn2zHVaoXEwibNfZpX:932726063) ([raw file](https://github.com/cockroachdb/cockroach/blob/64a7c26b6d76005703cc23b2831623675d5e671c/sql/distsql/tablereader.go#L182)):*
> ```Go
> 
> // Run is the "main loop".
> func (tr *tableReader) Run(wg *sync.WaitGroup) {
> ```

comment that `wg` can be `nil`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6943#-:-KIn7_O7qesq30VFCwyH:1417088721)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 6 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[sql/distsql/base.go, line 72 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6943#-KIn1vk9kDXPxraRbP0q:-KInBeYLGLJgosIFws7K:-1268438344) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4828ef8eda9f5d71b2566483daa2242ad03aade/sql/distsql/base.go#L72)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> can we `panic` here instead, and not return anything?
</details>
We can't panic, this is a legitimate case that happens when the receiver decides they're done.

---

*[sql/distsql/base.go, line 80 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6943#-KIn1hGoGPFfL2bXswdv:-KInC071kkZttQIhXmKA:-1366255720) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4828ef8eda9f5d71b2566483daa2242ad03aade/sql/distsql/base.go#L80)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> I found having both `Close` and `NoMoreRows` confusing. Maybe we can call one `CloseReader` and the other `CloseWriter`?
</details>
Note that `NoMoreRows` is not part of the `rowReceiver` interface so it's somewhat separate from `PushRow` and `Close`.

I am for better names but not sold on `CloseReader` and `CloseWriter`.  I'm not even sure which is which - is `CloseReader` a function that the writer calls to "close the reader" or is it the close called from the reader side?

Maybe `NoMoreRows`->`StopPushRow`?

---

*[sql/distsql/base.go, line 91 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6943#-KIn4k9rp-p1VN-bNxWE:-KInBZGp4Dqmo63p83Ni:-295663989) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0c4eaa1816ebb0da1f792d3f589e065fc08b122/sql/distsql/base.go#L91)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> I don't really get it - why does the buffer need to live in `RowChannel`? Can't it live in `RowChannel`'s client? Is it because you think there'll be many clients?
> Another option is to write a `DatumSlab` and have clients share that if they want efficient allocation.
> 
> It's also fine as it is. I dunno, just seemed a bit weird that this class would always do this copy and allocation, even if the client doesn't need it.
> 
</details>
Fair point, I will move this logic to a separate helper that clients can use as needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6943)*

**Comment by RaduBerinde** [comment]
Updated, r4-r6.

<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> :lgtm:
</details>


---

Review status: 0 of 7 files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6943#-:-KInPr10hpE0P5gG82RH:465162441)*

**Comment by RaduBerinde** [comment]
Added a test for EncDatumRowAlloc in r7 (part of the same commit with r6).

<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Updated, r4-r6.
</details>


---

Review status: 0 of 8 files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6943#-:-KInXsBLSJp-QOEkejJV:-216827408)*

**Comment by tschottdorf** [comment]
Reviewed 3 of 3 files at r1, 6 of 6 files at r2, 2 of 2 files at r3, 6 of 6 files at r4, 6 of 6 files at r5, 3 of 3 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

*[sql/distsql/base.go, line 84 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6943#-KJ6SblnvoqbSDdbX8Oq:-KJ6SblnvoqbSDdbX8Or:1249711714) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0c4eaa1816ebb0da1f792d3f589e065fc08b122/sql/distsql/base.go#L84)):*
> ```Go
> 	if len(rc.rowBuf) < num {
> 		// Allocate for a bunch of rows at once to amortize the cost.
> 		rc.rowBuf = make([]sqlbase.EncDatum, num*16)
> ```

magic 16?

---

*[sql/distsql/tablereader.go, line 148 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6943#-KJ6SvP9ka1SPFU-wWrx:-KJ6SvP9ka1SPFU-wWry:-326086212) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0c4eaa1816ebb0da1f792d3f589e065fc08b122/sql/distsql/tablereader.go#L148)):*
> ```Go
> // populates outRow with the values for outputCols.
> // Returns false when there are no more rows.
> func (tr *tableReader) nextRow(outRow sqlbase.EncDatumRow) (bool, error) {
> ```

Have you considered returning `io.EOF` when there are no more rows? Just curious.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6943)*

**Pull request merged**
