### PR TITLE
sql/schemachanger: enable declarative CREATE SEQUENCE

### PR DESCRIPTION
**Pull request by fqazi**
Previously, we did fully implement CREATE SEQUENCE in the declarative schema changer but had it disabled by default since we were missing this PR will do the following:

- Enable CREATE SEQUENCE by default in the declarative schema changer
- Add tests for transactionally creating / dropping sequences to confirm that the rules are sound
- Address bugs with transactional creation / drops of relations, since we previously did not create data elements
- Add tests for transactionally adding and using a sequence as a column
- Skip back up and restore tests for newly created objects, since intermediate states are not backed up today (if we do CREATE SEQUENCE and ADD COLUMN in a single txn, we will intentionally not backup the sequence during the job phase)

Informs: #117648
Epic: [CRDB-31282](https://cockroachlabs.atlassian.net/browse/CRDB-31282)

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
nice work! just had tiny nits

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117793#-:-NoVK1Jj23Dct7vlc5QX:b-vwj4ht)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`-- commits` line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117793#-NoVIsRRCj1cLDSt2hl1):*
are the next two commits after this examples of things that would have failed before?
___
*[`pkg/sql/schemachanger/scplan/internal/rules/current/helpers.go` line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117793#-NoVIUuW1qQUOmYLs7nr:-NoVIUuW1qQUOmYLs7ns:b2tlujb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b4fbd4c1b28c27cd85971cada2c0170c2992096/pkg/sql/schemachanger/scplan/internal/rules/current/helpers.go#L48)):*
> ```Go
> 
> // descriptorDataIsBeingAdded indicates that descriptor data is being
> // added and was not public earlier. This is mainly used to detect if an
> ```

this could lead to confusion. the comment has "descriptorDataIsBeingAdded indicates that descriptor data is being added" but the function is named `descriptorDataIsNotBeingAdded`. it looks like `descriptorDataIsNotBeingAdded` is correct.
___
*[`pkg/sql/schemachanger/sctest/backup.go` line 117 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117793#-NoVJuccCdJsCG4iMPdp:-NoVJuccCdJsCG4iMPdq:b99paf5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba41c2298670d43ad7ba41210c188497b921aea6/pkg/sql/schemachanger/sctest/backup.go#L117)):*
> ```Go
> func backupSuccess(t *testing.T, factory TestServerFactory, cs CumulativeTestCaseSpec) {
> 	maybeRandomlySkip(t)
> 	// Skip comparing outputs, if there are any newly created objects.
> ```

why only for these objects? what about functions, schemas, types, and databases?
___
*[`pkg/sql/schemachanger/sctest/backup.go` line 482 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117793#-NoVJhnh7aNKQRc3Ul0X:-NoVJhnh7aNKQRc3Ul0Y:b7lloqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba41c2298670d43ad7ba41210c188497b921aea6/pkg/sql/schemachanger/sctest/backup.go#L482)):*
> ```Go
> 					sqlutils.MatrixToStr(backupContents), pe.GetExplain())
> 			} else {
> 				t.Log("Skipping comparison of SQL afterward's as requested.")
> ```

super nit: "afterwards"

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117793)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`-- commits` line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117793#-NoVIsRRCj1cLDSt2hl1):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

are the next two commits after this examples of things that would have failed before?
</blockquote></details>

Yes, and I re-ordered the commits to make enabling last.
___
*[`pkg/sql/schemachanger/scplan/internal/rules/current/helpers.go` line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117793#-NoVIUuW1qQUOmYLs7nr:-Noodlv_EElEjmS0tLjD:b-p30ga8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b4fbd4c1b28c27cd85971cada2c0170c2992096/pkg/sql/schemachanger/scplan/internal/rules/current/helpers.go#L48)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this could lead to confusion. the comment has "descriptorDataIsBeingAdded indicates that descriptor data is being added" but the function is named `descriptorDataIsNotBeingAdded`. it looks like `descriptorDataIsNotBeingAdded` is correct.
</blockquote></details>

Done.

Good point, and reworded this to:

// descriptorDataIsNotBeingAdded indicates if we are operating on a descriptor
// that already exists and was not created in the current transaction. This is  
// determined by detecting if the data element is public, and not going from  
// absent to public which newly created descriptors will.
___
*[`pkg/sql/schemachanger/sctest/backup.go` line 117 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117793#-NoVJuccCdJsCG4iMPdp:-NoqpyVJ1GWAPmpCLXZD:b-4arbfy) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba41c2298670d43ad7ba41210c188497b921aea6/pkg/sql/schemachanger/sctest/backup.go#L117)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

why only for these objects? what about functions, schemas, types, and databases?
</blockquote></details>

Good point add all other object types here.
___
*[`pkg/sql/schemachanger/sctest/backup.go` line 482 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117793#-NoVJhnh7aNKQRc3Ul0X:-NooeFCM2ym4AmVaHpKW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba41c2298670d43ad7ba41210c188497b921aea6/pkg/sql/schemachanger/sctest/backup.go#L482)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

super nit: "afterwards"
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117793#-:-NpWKFJABf_crO4IqefJ:b-7nbn20)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained

**Comment by fqazi** [comment]
@rafiss TFTR!

bors r+

**Pull request merged**
