### PR TITLE
SQL support for PREPARE and EXECUTE

### LINKED ISSUE #7568: sql: support PREPARE/EXECUTE
Similar to #7367.

### PR DESCRIPTION
**Pull request by jordanlewis**
Add support for the `PREPARE` and `EXECUTE` statements in SQL. Previously, `PREPARE` and `EXECUTE` functionality was only available via the wire protocol.

This is a straightforward implementation that's on par with the current implementation of pgwire prepared statements. Significantly, it only caches the text of the query in the session, not the parsed query or the plan.

Fixes #7568.

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/sql/executor.go, line 1218 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256#-KiHJc6U9-bXU_t3nrOF:-KiHJc6U9-bXU_t3nrOG:b-4n5fbc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a24d7ed29e6febcf351df96c610fc896fc995ed0/pkg/sql/executor.go#L1218)):*
> ```Go
> 				"prepared statement %q already exists", name)
> 		}
> 		typeHints := make(parser.PlaceholderTypes, len(s.Types))
> ```

is it possible to share this code with the pgwire machinery?

---

*[pkg/sql/executor.go, line 1223 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256#-KiHJGmoni9JM3fwJb-X:-KiHJGmoni9JM3fwJb-Y:bnxnalo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a24d7ed29e6febcf351df96c610fc896fc995ed0/pkg/sql/executor.go#L1223)):*
> ```Go
> 		}
> 		_, err := session.PreparedStatements.New(e, name, s.Statement.String(), typeHints)
> 		if err != nil {
> ```

unnecessary condition

---

*[pkg/sql/executor.go, line 1257 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256#-KiHJUCgyqFx6TQUwi9z:-KiHJUCgyqFx6TQUwiA-:b-k0jv10) ([raw file](https://github.com/cockroachdb/cockroach/blob/a24d7ed29e6febcf351df96c610fc896fc995ed0/pkg/sql/executor.go#L1257)):*
> ```Go
> 		}
> 		if len(results.ResultList) > 1 {
> 			return Result{}, errors.Errorf("invalid prepared statement had %d statements, expected 1", len(results.ResultList))
> ```

can't we reject this at preparation time? do we already do so?

---

*[pkg/sql/pgwire/pgwire_test.go, line 954 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256#-KiHJxGsVgwIxuAhgM0b:-KiHJxGsVgwIxuAhgM0c:bzeq75f) ([raw file](https://github.com/cockroachdb/cockroach/blob/a24d7ed29e6febcf351df96c610fc896fc995ed0/pkg/sql/pgwire/pgwire_test.go#L954)):*
> ```Go
> 			var executeStmt string
> 			if len(args) == 0 {
> 				executeStmt = fmt.Sprintf("EXECUTE \"%d\"", i)
> ```

I think you can avoid the `else`?
```
executeStmt := fmt.Sprintf(`EXECUTE "%d"`, i)
if len(args) > 0 {
 ....
 executeStmt += "("+strings.Join(...)+")"
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256#-:-KiHKTfBGmUFnSAi3vyr:bnfp4nl)*

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor.go, line 1218 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256#-KiHJc6U9-bXU_t3nrOF:-KiHLw_QXM1zqhyBDpBU:b-p9729m) ([raw file](https://github.com/cockroachdb/cockroach/blob/a24d7ed29e6febcf351df96c610fc896fc995ed0/pkg/sql/executor.go#L1218)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is it possible to share this code with the pgwire machinery?
</blockquote></details>

Not without more contortion than its worth, I think - the type-types are all different so it would be a pain to get it right.

---

*[pkg/sql/executor.go, line 1223 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256#-KiHJGmoni9JM3fwJb-X:-KiHLUiYDQb9JBEC4GDG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a24d7ed29e6febcf351df96c610fc896fc995ed0/pkg/sql/executor.go#L1223)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

unnecessary condition
</blockquote></details>

Done.

---

*[pkg/sql/executor.go, line 1257 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256#-KiHJUCgyqFx6TQUwi9z:-KiHKwztvmUgSR2U4yQr:b-alud3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/a24d7ed29e6febcf351df96c610fc896fc995ed0/pkg/sql/executor.go#L1257)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can't we reject this at preparation time? do we already do so?
</blockquote></details>

We already do - this should be an impossible condition, as I don't think the parser allows prepared statements with more than one statement inside. I'd make this a panic but I wouldn't want it to crash the server if I'm wrong. I made the message better.

---

*[pkg/sql/pgwire/pgwire_test.go, line 954 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256#-KiHJxGsVgwIxuAhgM0b:-KiHLFf370JE6bQH64Zp:b-kg55le) ([raw file](https://github.com/cockroachdb/cockroach/blob/a24d7ed29e6febcf351df96c610fc896fc995ed0/pkg/sql/pgwire/pgwire_test.go#L954)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I think you can avoid the `else`?
```
executeStmt := fmt.Sprintf(`EXECUTE "%d"`, i)
if len(args) > 0 {
 ....
 executeStmt += "("+strings.Join(...)+")"
}
```
</blockquote></details>

I didn't mean to commit this part of the change in the first place, as getting it to work within this framework was impossible without major changes to this test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/executor.go, line 1218 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256#-KiHJc6U9-bXU_t3nrOF:-KiHNEO13fDsjclYyRZG:bhbpkq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a24d7ed29e6febcf351df96c610fc896fc995ed0/pkg/sql/executor.go#L1218)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Not without more contortion than its worth, I think - the type-types are all different so it would be a pain to get it right.
</blockquote></details>

Perhaps a TODO is worth it, though?

---

*[pkg/sql/executor.go, line 1227 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256#-KiHNSS2GrMzQloZJUV_:-KiHNSS2GrMzQloZJUVa:b-o8shoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a43338103c857b09157696992378a54522d06160/pkg/sql/executor.go#L1227)):*
> ```Go
> 		name := s.Name.String()
> 		prepared, ok := session.PreparedStatements.Get(name)
> 		if err != nil {
> ```

what's going on here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256)*

**Comment by jordanlewis** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/executor.go, line 1218 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256#-KiHJc6U9-bXU_t3nrOF:-KiHNkAwiBVbyRnOaQv5:b-5ectz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a24d7ed29e6febcf351df96c610fc896fc995ed0/pkg/sql/executor.go#L1218)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Perhaps a TODO is worth it, though?
</blockquote></details>

Eh... I don't think the TODO will ever get acted on, so I'd rather not make it seem like there's really something to be done here.

---

*[pkg/sql/executor.go, line 1227 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256#-KiHNSS2GrMzQloZJUV_:-KiHNmQK_SDnxgXERJZi:b-olstar) ([raw file](https://github.com/cockroachdb/cockroach/blob/a43338103c857b09157696992378a54522d06160/pkg/sql/executor.go#L1227)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

what's going on here?
</blockquote></details>

Did something weird when pushing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256)*

**Comment by knz** [comment]
I love this; I am both surprised and delighted by how short the implementation ended up.

Some nits remaining.

---

Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 2 of 4 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor.go, line 1219 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256#-KiKNMpFh_picyK38eKN:-KiKNMpFh_picyK38eKO:b-or1dtl) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb20ffa54558039111ba37d256c667081828811f/pkg/sql/executor.go#L1219)):*
> ```Go
> 		}
> 		typeHints := make(parser.PlaceholderTypes, len(s.Types))
> 		for i, t := range s.Types {
> ```

Please add a logic test using the syntax `PREPARE xxx(types...) AS ...` otherwise this code path is not exercised.

---

*[pkg/sql/executor.go, line 1239 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256#-KiKOWKzIe-4rNlDzOUp:-KiKOWL-Gy1VcnmuVAFu:blg72u1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb20ffa54558039111ba37d256c667081828811f/pkg/sql/executor.go#L1239)):*
> ```Go
> 		for i, e := range s.Params {
> 			idx := strconv.Itoa(i + 1)
> 			typedExpr, err := sqlbase.SanitizeVarFreeExpr(e, prepared.SQLTypes[idx], "EXECUTE parameter", session.SearchPath)
> ```

Can you file a follow-up issue here to remember that the semantics are probably incorrect if the search path change between prepare and execute.
We should fully qualify the table names in the AST during prepare and reuse that durng execute, so that only the search path active during prepare is considered.

---

*[pkg/sql/executor.go, line 1243 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256#-KiKP5Lzwb-e_TEdBcUX:-KiKP5Lzwb-e_TEdBcUY:b-gmqac4) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb20ffa54558039111ba37d256c667081828811f/pkg/sql/executor.go#L1243)):*
> ```Go
> 				return Result{}, pgerror.NewError(pgerror.CodeFeatureNotSupportedError, err.Error())
> 			}
> 			var p parser.Parser
> ```

Please file a follow-up clean-up issue to extract these methods away from the `Parser` type. This is weird :)

---

*[pkg/sql/executor.go, line 1254 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256#-KiKQT9zuyRIGD4Fqqdu:-KiKQT9zuyRIGD4Fqqdv:b-o8rv55) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb20ffa54558039111ba37d256c667081828811f/pkg/sql/executor.go#L1254)):*
> ```Go
> 		}
> 		if len(results.ResultList) > 1 {
> 			return Result{}, errors.Errorf("unexpected error: prepared statement %q had %d statements, expected 1", s.Name, len(results.ResultList))
> ```

Ensure this the same error message as in (*Executor).Prepare() - you can pick either of the two but make a function to generate the error message.
Also make both use pgerror.CodeInvalidPreparedStatementDefinitionError.

---

*[pkg/sql/parser/aggregate_builtins.go, line 1021 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256#-KiKRKltchfElvTmQJ-g:-KiKRKltchfElvTmQJ-h:b3o261g) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb20ffa54558039111ba37d256c667081828811f/pkg/sql/parser/aggregate_builtins.go#L1021)):*
> ```Go
> func (p *Parser) AssertNoAggregationOrWindowing(expr Expr, op string, searchPath SearchPath) error {
> 	if p.AggregateInExpr(expr, searchPath) {
> 		return pgerror.NewErrorf(pgerror.CodeGroupingError, "aggregate functions are not allowed in %s", op)
> ```

While you're at it you could perhaps sprinkle these two codes through `window.go` and `group.go`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256#-:-KiKRQQ9Qc1-PQ4NV3hB:b-7cmwms)*

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor.go, line 1219 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256#-KiKNMpFh_picyK38eKN:-KiKyhXvZIUp55Ta1wYJ:b-xexooc) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb20ffa54558039111ba37d256c667081828811f/pkg/sql/executor.go#L1219)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please add a logic test using the syntax `PREPARE xxx(types...) AS ...` otherwise this code path is not exercised.
</blockquote></details>

I did already, but there's just one of them. Added some more.

---

*[pkg/sql/executor.go, line 1239 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256#-KiKOWKzIe-4rNlDzOUp:-KiKz1boxlSuEqruFaiy:boochey) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb20ffa54558039111ba37d256c667081828811f/pkg/sql/executor.go#L1239)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you file a follow-up issue here to remember that the semantics are probably incorrect if the search path change between prepare and execute.
We should fully qualify the table names in the AST during prepare and reuse that durng execute, so that only the search path active during prepare is considered.
</blockquote></details>

To be consistent with Postgres I think we'd keep the current implementation:

```
Although the main point of a prepared statement is to avoid repeated parse analysis and planning of the statement, PostgreSQL will force re-analysis and re-planning of the statement before using it whenever database objects used in the statement have undergone definitional (DDL) changes since the previous use of the prepared statement. Also, if the value of search_path changes from one use to the next, the statement will be re-parsed using the new search_path.
```

From https://www.postgresql.org/docs/9.6/static/sql-prepare.html

---

*[pkg/sql/executor.go, line 1243 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256#-KiKP5Lzwb-e_TEdBcUX:-KiKzI2ZaIJ1WJVldrgN:b-4evs8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb20ffa54558039111ba37d256c667081828811f/pkg/sql/executor.go#L1243)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please file a follow-up clean-up issue to extract these methods away from the `Parser` type. This is weird :)
</blockquote></details>

Yeah... I copied this pattern from elsewhere in the code. Agreed that it's weird. #15268

---

*[pkg/sql/executor.go, line 1254 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256#-KiKQT9zuyRIGD4Fqqdu:-KiL7vAACdoUtFbTue9b:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb20ffa54558039111ba37d256c667081828811f/pkg/sql/executor.go#L1254)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Ensure this the same error message as in (*Executor).Prepare() - you can pick either of the two but make a function to generate the error message.
Also make both use pgerror.CodeInvalidPreparedStatementDefinitionError.

</blockquote></details>

Done.

---

*[pkg/sql/parser/aggregate_builtins.go, line 1021 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256#-KiKRKltchfElvTmQJ-g:-KiL7wb7dpIN4M7io5PL:bmf8dqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb20ffa54558039111ba37d256c667081828811f/pkg/sql/parser/aggregate_builtins.go#L1021)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

While you're at it you could perhaps sprinkle these two codes through `window.go` and `group.go`
</blockquote></details>

I'll do this in a different PR - some effort is required to find the correct codes for all of the different error cases, which are not always the ones listed here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256)*

**Comment by jordanlewis** [comment]
TFTR!

---

Review status: 5 of 7 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256#-:-KiLFJ7cE08wqxCkUDnH:b-814g8k)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/executor.go, line 1239 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256#-KiKOWKzIe-4rNlDzOUp:-KiU-w6EoxcZqDC70Jh6:b2nhb2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb20ffa54558039111ba37d256c667081828811f/pkg/sql/executor.go#L1239)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

To be consistent with Postgres I think we'd keep the current implementation:

```
Although the main point of a prepared statement is to avoid repeated parse analysis and planning of the statement, PostgreSQL will force re-analysis and re-planning of the statement before using it whenever database objects used in the statement have undergone definitional (DDL) changes since the previous use of the prepared statement. Also, if the value of search_path changes from one use to the next, the statement will be re-parsed using the new search_path.
```

From https://www.postgresql.org/docs/9.6/static/sql-prepare.html
</blockquote></details>

Ack

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15256#-:-KiU044TKCHv1GxqPar9:bnfp4nl)*

**Pull request merged**
