### PR TITLE
storage: use Replica.String as prefix for raft log messages

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8300)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm_strong: 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/raft.go, line 149 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8300#-KOGfHDR8QjlXXB9tJXi:-KOGfHDR8QjlXXB9tJXj:1901522120) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee4b09f9df2a5bb5c9488594ffa0bd8e019eb4c3/storage/raft.go#L149)):*
> ```Go
> 		}
> 
> 		// Globally synchronize to avoid interleaving different sets of logs in tests.
> ```

in tests? seems like this a thing in real life as well, since each replica has a logger.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8300#-:-KOGfQRaO4mWMcuZ1LTW:-1868698381)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/raft.go, line 149 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8300#-KOGfHDR8QjlXXB9tJXi:-KOGh3uG-n0hDHnEt8YW:-457635061) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee4b09f9df2a5bb5c9488594ffa0bd8e019eb4c3/storage/raft.go#L149)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> in tests? seems like this a thing in real life as well, since each replica has a logger.
</details>
I just moved this from above. @bdarnell?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8300)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/raft.go, line 124 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8300#-KOGrGhD-K9JEB38bTcR:-KOGrGhD-K9JEB38bTcS:1478678628) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee4b09f9df2a5bb5c9488594ffa0bd8e019eb4c3/storage/raft.go#L124)):*
> ```Go
> var logRaftReadyMu syncutil.Mutex
> 
> func logRaftReady(prefix fmt.Stringer, ready raft.Ready) {
> ```

While you're changing the signature of this method pass the `Context` down from `handleRaftReady`.

---

*[storage/raft.go, line 149 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8300#-KOGfHDR8QjlXXB9tJXi:-KOGqbuDzAZd-I4y9Z84:1763121778) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee4b09f9df2a5bb5c9488594ffa0bd8e019eb4c3/storage/raft.go#L149)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I just moved this from above. @bdarnell?
</details>
Yeah, it's not just for tests any more (since the change to parallelize `handleRaftReady`) However, it was only necessary when we were doing multiple `log.Info` calls; now that it's one multi-line log message `logRaftReadyMu` can be removed completely.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8300#-:-KOGrWQgHTd_1PT33SsT:1417088721)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/raft.go, line 124 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8300#-KOGrGhD-K9JEB38bTcR:-KOGsg48plsXLkn6SuF7:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee4b09f9df2a5bb5c9488594ffa0bd8e019eb4c3/storage/raft.go#L124)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> While you're changing the signature of this method pass the `Context` down from `handleRaftReady`.
</details>
Done.

---

*[storage/raft.go, line 149 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8300#-KOGfHDR8QjlXXB9tJXi:-KOGsh0Zw1j_yTLuWqde:1740281843) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee4b09f9df2a5bb5c9488594ffa0bd8e019eb4c3/storage/raft.go#L149)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Yeah, it's not just for tests any more (since the change to parallelize `handleRaftReady`) However, it was only necessary when we were doing multiple `log.Info` calls; now that it's one multi-line log message `logRaftReadyMu` can be removed completely.
</details>
Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8300)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8300)*

**Pull request merged**
