### PR TITLE
storage: create tracing span when requesting range leases

### PR DESCRIPTION
**Pull request by nvb**
Previously, tracing was not picking up range lease requests because we
were inheriting directly from `context.Background()`. We now add a span
to the context before handing it to the async task.

Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica_range_lease.go, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22855#-L5szo69mNVOgQ4PGivd:-L5szo6AI6Z94FObJRwD:bknzr3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee30a1e9f3fce3550b4a60ad9da8f598d4b1f55e/pkg/storage/replica_range_lease.go#L62)):*
> ```Go
> 		if len(h.p.llHandles) == 0 {
> 			h.p.cancel()
> 			h.p.cleanupAfterReq()
> ```

isn't this the wrong place to do that? Shouldn't we leave it to the async request (which presumably observes the cancelation somehow)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22855)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/replica_range_lease.go, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22855#-L5szo69mNVOgQ4PGivd:-L5vzXw6KAnHyBLQT83x:b-c0rn85) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee30a1e9f3fce3550b4a60ad9da8f598d4b1f55e/pkg/storage/replica_range_lease.go#L62)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

isn't this the wrong place to do that? Shouldn't we leave it to the async request (which presumably observes the cancelation somehow)?
</blockquote></details>

Good point. I changed this around a little bit to make cancellation more clear and to ensure that we always call the cancellation function returned by `context.WithCancel`.

On that topic, I did some digging into why I've never actually seen goroutines that were leaked by not calling `cancel`. It looks like `context.WithCancel` will only ever launch a goroutine if the parent context is a custom implementation of `context.Context` that implements its own form of cancellation. If the parent context is a [standard `Context` implementation](https://github.com/golang/go/blob/f4c3072cf53889b2f11c97ee0bca53925b791f5f/src/context/context.go#L269), the stdlib is able to avoid the goroutine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22855)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22855#-:-L5y_wbshmFwG9Oq_dS9:bnfp4nl)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica_range_lease.go, line 98 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22855#-L6Id0YCt1h04A7q4ams:-L6Id0YDDiSFlubURcf5:b9roeoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/e703ff2254f7c9ac43f6c164ce9f91647137ab12/pkg/storage/replica_range_lease.go#L98)):*
> ```Go
> 	// cancel is the context cancellation function for the async lease
> 	// request, if one exists. If nil, then no request is in progress.
> 	// repl.mu to be exclusively locked to call the function.
> ```

nit: name it `cancelLocked()` then.
And also expand the comment saying that this will be called in multiple situations.

---

*[pkg/storage/replica_range_lease.go, line 229 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22855#-L6IdCqlqJAr9BGYtEyc:-L6IdCqlqJAr9BGYtEyd:b-u7kmj0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e703ff2254f7c9ac43f6c164ce9f91647137ab12/pkg/storage/replica_range_lease.go#L229)):*
> ```Go
> // specified replica. The request is sent in an async task.
> func (p *pendingLeaseRequest) requestLeaseAsync(
> 	parentCtx context.Context,
> ```

s/parentCtx/ctx

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22855#-:-L6IdZU3chxTqCufudZw:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/replica_range_lease.go, line 98 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22855#-L6Id0YCt1h04A7q4ams:-L6IpMKxbKdO80awvCr0:b-qu6n94) ([raw file](https://github.com/cockroachdb/cockroach/blob/e703ff2254f7c9ac43f6c164ce9f91647137ab12/pkg/storage/replica_range_lease.go#L98)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: name it `cancelLocked()` then.
And also expand the comment saying that this will be called in multiple situations.
</blockquote></details>

Good point. Done.

---

*[pkg/storage/replica_range_lease.go, line 229 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22855#-L6IdCqlqJAr9BGYtEyc:-L6IfPT6C-ZaW51oJggl:b-aa0mym) ([raw file](https://github.com/cockroachdb/cockroach/blob/e703ff2254f7c9ac43f6c164ce9f91647137ab12/pkg/storage/replica_range_lease.go#L229)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/parentCtx/ctx
</blockquote></details>

I called this `parentCtx` to make it clear that it was not actually used to make the lease request.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22855)*

**Comment by andreimatei** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica_range_lease.go, line 229 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22855#-L6IdCqlqJAr9BGYtEyc:-L6IqwwMA3usaoJ8MjBN:bf7bmmd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e703ff2254f7c9ac43f6c164ce9f91647137ab12/pkg/storage/replica_range_lease.go#L229)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I called this `parentCtx` to make it clear that it was not actually used to make the lease request.
</blockquote></details>

I understand but that's unusual. When a method has Async in the name, one assumes that it takes care of what context it uses for the async part.

But I'm actually confused - in what situation can the lease request outlive the parent? Isn't the  parent blocked on it?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22855)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica_range_lease.go, line 229 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22855#-L6IdCqlqJAr9BGYtEyc:-L6IulcDAom1R0ajMz5u:bfrz0s0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e703ff2254f7c9ac43f6c164ce9f91647137ab12/pkg/storage/replica_range_lease.go#L229)):*
> But I'm actually confused - in what situation can the lease request outlive the parent? Isn't the parent blocked on it?

The reason why I don't want to call it `ctx` is exactly for this reason. The lease request can outlive its parent. This is explained in the comment:

```
Create a new context *without* a timeout. Instead, we multiplex
the cancellation of all contexts onto this new one, only canceling
it if all coalesced requests timeout/cancel.
```

What do you think about removing the `context` argument entirely here and taking in `parentSpan` directly to make this even more clear?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22855)*

**Comment by andreimatei** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica_range_lease.go, line 229 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22855#-L6IdCqlqJAr9BGYtEyc:-L6JJS0O58c7NbQkIS0q:bf509sc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e703ff2254f7c9ac43f6c164ce9f91647137ab12/pkg/storage/replica_range_lease.go#L229)):*
So the request can outlive the caller if the caller is canceled or has set a timeout, right? Would you mind making that more explicit somewhere - like in the comment about `FollowsFrom` below?

> What do you think about removing the context argument entirely here and taking in parentSpan directly to make this even more clear?

I... don't like it :P
In my opinion, this method should take a `ctx` like any other. That would be no indication about what context an internal async operation will use and about the different life spans involved.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22855)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/replica_range_lease.go, line 229 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22855#-L6IdCqlqJAr9BGYtEyc:-L6JMhifDWstS17_C5nt:b6m0986) ([raw file](https://github.com/cockroachdb/cockroach/blob/e703ff2254f7c9ac43f6c164ce9f91647137ab12/pkg/storage/replica_range_lease.go#L229)):*
> So the request can outlive the caller if the caller is canceled or has set a timeout, right? 

Yeah, exactly.

> Would you mind making that more explicit somewhere - like in the comment about FollowsFrom below?

Done.

> In my opinion, this method should take a ctx like any other.

I made this change because I didn't think it was a big deal but I've actually reverted it after reading over the new code. The fact that we use a different context to launch the lease request so that we don't inherit from the parent context's deadline is really important here, but even with the bolded comment this is subtle. Shadowing the `ctx` variable when we create the new `context` makes this even less clear. The more I think about this, the more I want the argument to stick out like a sore thumb, which is why I suggested narrowing it to just the `parentSpan`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22855)*

**Comment by andreimatei** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/replica_range_lease.go, line 229 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22855#-L6IdCqlqJAr9BGYtEyc:-L6JQcSe2zQUHZsu9Tkg:b-r2maya) ([raw file](https://github.com/cockroachdb/cockroach/blob/e703ff2254f7c9ac43f6c164ce9f91647137ab12/pkg/storage/replica_range_lease.go#L229)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> So the request can outlive the caller if the caller is canceled or has set a timeout, right? 

Yeah, exactly.

> Would you mind making that more explicit somewhere - like in the comment about FollowsFrom below?

Done.

> In my opinion, this method should take a ctx like any other.

I made this change because I didn't think it was a big deal but I've actually reverted it after reading over the new code. The fact that we use a different context to launch the lease request so that we don't inherit from the parent context's deadline is really important here, but even with the bolded comment this is subtle. Shadowing the `ctx` variable when we create the new `context` makes this even less clear. The more I think about this, the more I want the argument to stick out like a sore thumb, which is why I suggested narrowing it to just the `parentSpan`.
</blockquote></details>

As you wish, but I'm pretty sure there's millions of examples where we pass `ctx`s that we override later.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22855)*

**Pull request merged**
