### PR TITLE
Fixed linting issue.

### PR DESCRIPTION
**Pull request by imumesh18**
This issue just fixes linting issue with cockroach/docs/generated/sql/doc.go
file. Making the result of go_lint to 100% in goreport.

P.S This my first pr. I know it's small in terms of contribution. I was just going through the code this thing catched my eyes so created a pull to fix this.

### CODE REVIEW

**Comment by benesch** [comment]
@dungeonmaster18, thanks for making your first contribution! Much appreciated.

I don't think this is quite the right fix, though! The error I'm seeing from `golint` is:

```
docs/generated/sql/doc.go:15:1: package comment should be of the form "Package sql ..."
```

Your proposed fix makes the comment in question no longer a "package comment" by introducing a blank line between the comment and the `package sql` declaration, but that comment _is_ supposed to be a package comment. I propose we instead adjust the wording to follow `golint`'s advice. Perhaps something like:

```diff
diff --git a/docs/generated/sql/doc.go b/docs/generated/sql/doc.go
index 240825479..4260ca368 100644
--- a/docs/generated/sql/doc.go
+++ b/docs/generated/sql/doc.go
@@ -13,8 +13,8 @@
 // permissions and limitations under the License.
 
 /*
-This dummy package contains documentation generated from sources in
-`pkg/sql/parser` using `docgen`.
+Package sql is a dummy package that contains documentation generated from
+sources in `pkg/sql/parser` using `docgen`.
 
 These files are copied to the `docs` repository where they are included in pages
 that document SQL. This happens periodically to ensure they stay up-to-date, for
```

Would you mind to update the PR?

**Comment by dungeonmaster18** [comment]
Sure will to do that. Thanks for suggestions.

**Comment by dungeonmaster18** [comment]
Want me to squash these commits. @benesch

**Comment by benesch** [comment]
Yes, if you wouldn't mind terribly! Our usual commit message for something like this would read "docs/generated: fix lint error in package comment".

**Comment by dungeonmaster18** [comment]
Sure I will do that.

**Comment by dungeonmaster18** [comment]
Hey @benesch just squshed my commits please fill free to merge it whenever you are free and thanks for the review. Hope to collaborate with you. I am gonna stay long over here:wink:

**Comment by benesch** [comment]
Thanks for the speedy turnaround @dungeonmaster18! Would love to get more contributions from you.

**Pull request merged**
