### PR TITLE
colexecagg: reduce the size of hash aggregates

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: fix a recent bug with aggTypes**

When we introduced the hash aggregation with partial order support, we
mistakenly removed the ordered aggregation from `aggTypes` slice that is
used in some tests as well as in the benchmarks. This is now fixed.

Release note: None

**colexecagg: replace concrete slices with native type aliases**

This commit replaces concrete slices (like `[]int64`) with the
corresponding native type aliases (like `coldata.Int64s`). This allows
us to use inlined `Set` methods.

Release note: None

**colexecagg: remove some redundant COPYVAL calls**

This commit removes several `execgen.COPYVAL` calls that were redundant
because the first and the second argument are the same. These calls are
redundant because we already performed the same call right after
calling `Get` from the original vector and we will perform a deep copy
when calling `Set` next.

Release note: None

**colexecagg: reduce the size of hash aggregates**

This commit reduces the size of the hash aggregates by removing the
reference to the well-typed column (i.e. a concrete unwrapped
`coldata.Vec`, something like `[]int64`). This is possible because the
hash aggregates only access the concrete column once, in `Flush`, so
there is no point in storing the concrete column as we do for the
ordered aggregates. We still perform the interface dispatch call only
once - previously it was in `SetOutput`, now it is in `Flush`. This
should be a non-trivial improvement since the hash aggregation uses
a separate aggregation function object for each bucket.

This change also allows us to remove the overriding of `SetOutput`
method implementation provided by the base struct from the hash and
window aggregates.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
As expected, this [shows](https://gist.github.com/yuzefovich/d30cd1a0662733855ae8c9d8217ae603) small improvement.

**Comment by yuzefovich** [comment]
Found a recent minor bug with `aggTypes`. RFAL.

**Review by rharding6373 — APPROVED** [review]
Thanks for fixing the bug! Nice work. :lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74437#-:-MsfVNAJ9UkO3rxN5ZWP:b-ylc9i0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[-- commits, line 35 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74437#-MsfPguW3Y9JHmnKTnYO):*
nit: s/implimentation/implementation
___
*[pkg/sql/colexec/execgen/cmd/execgen/sum_agg_gen.go, line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74437#-MsfQVOP0ieynSz-PTDI:-MsfQVOP0ieynSz-PTDJ:b32c2m1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa4d235a80e56340077688727e7f037a28f33f0d/pkg/sql/colexec/execgen/cmd/execgen/sum_agg_gen.go#L31)):*
> ```Go
> 	InputVecMethod string
> 	RetGoType      string
> 	RetGoTypeSlice string
> ```

Should the changes in this file be in the third commit?

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74437#-:-MsfnVPE4TA2rkWoPIHy:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rharding6373 and @rytaft)

___
*[pkg/sql/colexec/execgen/cmd/execgen/sum_agg_gen.go, line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74437#-MsfQVOP0ieynSz-PTDI:-MsfmWOJDn-eXWwH9cWB:bl3moj) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa4d235a80e56340077688727e7f037a28f33f0d/pkg/sql/colexec/execgen/cmd/execgen/sum_agg_gen.go#L31)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Should the changes in this file be in the third commit?
</blockquote></details>

The idea behind these changes was to allow the usage of `Set` methods from the native type aliases in order to make the work in #74469 easier, and it didn't belong to any of the existing commits well, so I extracted a new separate commit for it.

**Pull request merged**
