### PR TITLE
build: adding missing bin/.bootstrap order-only dependency

### PR DESCRIPTION
**Pull request by petermattis**
Any rule which uses `gofmt` or `goimports` needs to have an order-only
dependency on `bin/.bootstrap`, otherwise the `bin/.bootstrap` rule can
run in parallel causing a race between `bin/gofmt` getting created and
it being used by the rule. This would result in rare "text file busy"
errors when running a partially written `bin/gofmt`.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
Cc @andreimatei, @tbg

**Comment by petermattis** [comment]
@bobvawter Do you know make well enough to review this?

**Review by bobvawter — APPROVED** [review]
I'll pretend that I know more about make than I ought to :-) . I assume that you've grepped for all rules that invoke `gofmt` and tweaked them?

:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38857#-:-LjpsMJbDFrMwavBijOQ:bbwh036)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by petermattis — COMMENTED** [review]
> I assume that you've grepped for all rules that invoke gofmt and tweaked them?

Yep. And `goimports` as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38857#-:-LjpuTnsBp-iFFPrcNX6:br6mpd4)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by petermattis** [comment]
TFTR! Unrelated roachtest failure.

bors r=bobvawter

**Pull request merged**
