### PR TITLE
add generate_series for timestampTZ values

### LINKED ISSUE #64850: sql: implement generate_series for timestamps
Looks like postgres supports `generate_series(timestamptz, timestamptz, interval)` (and with `timestamp`), we should add these too.

You can follow the examples for `generate_series` generators already in place [here](https://github.com/cockroachdb/cockroach/blob/d54b3cb1eda81e8c080a97f7dee954cfb3aa99ef/pkg/sql/sem/builtins/generator_builtins.go#L112), then add a test for the builtins [at the end of this file here](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/builtin_function) (regenerate output with `make testbaselogic FILES='builtin_function' TESTFLAGS='-rewrite'`)

### PR DESCRIPTION
**Pull request by oeph**
This change adds `generate_series(timestamptz, timestamptz, interval)` as it is also supported by postgres

Fixes #64850

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Thanks for the contribution!

If you can, it would be great to also add a `(timestamp, timestamp, interval)` version, so we don't have to come back to it later.

Could you add a test like the one below (inspired from #64722)?

```
set timezone='Europe/Bucharest';
select '2020-10-25 00:00'::TIMESTAMPTZ + (i::text || ' hour')::interval from generate_series(0, 24) AS g(i);
select t from generate_series('2020-10-25 00:00'::TIMESTAMPTZ, '2020-10-26 00:00'::TIMESTAMPTZ, '1 hour');
```
These two statements should return the same results (might need to adjust the end time so they return the same number of rows).

**Comment by oeph** [comment]
sure, will do!

**Comment by oeph** [comment]
@RaduBerinde isn't the `(timestamp, timestamp, interval)` one already supported? (https://github.com/cockroachdb/cockroach/blob/fcb7d81a26a8be25cf28219a148f87ead3742109/pkg/sql/sem/builtins/generator_builtins.go#L128)

**Comment by oeph** [comment]
I added the test case that you suggested

**Review by RaduBerinde — COMMENTED** [review]
Ah, sorry, I guess it is already implemented.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64887#-:-M_7gaV-AoJgcvlpg-AF:b-ri8z4q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @oeph, @otan, and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/builtin_function, line 3021 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64887#-M_7goEXA-DUN-ggSzUN:-M_7goEXA-DUN-ggSzUO:b-rd7j10) ([raw file](https://github.com/cockroachdb/cockroach/blob/42144c532fbf3d146b4653a4d49a67ef95855331/pkg/sql/logictest/testdata/logic_test/builtin_function#L3021)):*
> ```
> SET TIME ZONE +0
> 
> statement ok
> ```

This only tests that we don't crash.. We should use `query` to see the output so we can confirm that the two are equivalent.

**Comment by oeph** [comment]
@RaduBerinde is there a way to automatically compare the outputs of both query to match? I can't find any for the sqllogictest - can you maybe give me a hint? Or should I just add these both queries as standalone queries?

**Comment by RaduBerinde** [comment]
Ah, it's not necessary, we can just visually compare. We can leave a comment saying that the results should be the same if they ever were to change. We review any changes to these files.

**Comment by oeph** [comment]
@RaduBerinde I added a comment for this

**Review by RaduBerinde — COMMENTED** [review]
Thank you! :lgtm: 

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64887#-:-M_DKt469tK7-FopyNUq:b-f25ydi)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @oeph, @otan, and @yuzefovich)

**Review by otan — COMMENTED** [review]
thanks @oeph !

**Pull request merged**
