### PR TITLE
ui next: MetricsDataProvider

### PR DESCRIPTION
**Pull request by mrtracy**
Commit creates the MetricsDataProvider component, which is used to provide time
series query data to arbitrary components.

MetricsDataProvider is designed to contain graph-like components, which in term
should contain "Selectors". Each Selector describes a time series that should be
queried over a given time span (currently a constant timespan, but will be
converted to a "global" moving timespan shared by all graphs).

When MetricsDataProvider detects that currently cached data does not match
either the time span or the contained selectors, it refreshes the
query by dispatching an appropriate redux event.

When cached data is available, MetricsDataProvider passes that data to its
contained graph through its "data" prop.

GO PROTOS CHANGE:

This commit also modifies the timeseries.proto message to return a format
compatible with the frontend's protocol buffer library (proto2js). Specifically,
we instruct gogoproto to encode a few int64s as strings instead of numbers.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6603)

### CODE REVIEW

**Comment by maxlang** [comment]
You should probably make issues for the proto stuff you've encountered, or at least for the most severe.

:lgtm: 

<details><summary><i>Previously, mrtracy wrote…</i></summary>
> #### ui next: MetricsDataProvider
> 
> Commit creates the MetricsDataProvider component, which is used to provide time
> 
> series query data to arbitrary components.
> 
> 
> 
> MetricsDataProvider is designed to contain graph-like components, which in term
> 
> should contain "Selectors". Each Selector describes a time series that should be
> 
> queried over a given time span (currently a constant timespan, but will be
> 
> converted to a "global" moving timespan shared by all graphs).
> 
> 
> 
> When MetricsDataProvider detects that currently cached data does not match
> 
> either the time span or the contained selectors, it refreshes the
> 
> query by dispatching an appropriate redux event.
> 
> 
> 
> When cached data is available, MetricsDataProvider passes that data to its
> 
> contained graph through its "data" prop.
> 
> 
> 
> GO PROTOS CHANGE:
> 
> 
> 
> This commit also modifies the timeseries.proto message to return a format
> 
> compatible with the frontend's protocol buffer library (proto2js). Specifically,
> 
> we instruct gogoproto to encode a few int64s as strings instead of numbers.
> 
> 
> </details>


---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[ui/next/app/components/graphs.tsx, line 60 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHORHOHm3-ncbiB5Qas:-KHORHOIA-jcCDJ7MFDv:673963975) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/components/graphs.tsx#L60)):*
> ```XML
>   render() {
>     return <div>{
>       this.props.data && this.props.data.results ? this.props.data.results.join(":").toString() : ""
> ```

Consider use parens to make the order of operations clear/readable

---

*[ui/next/app/containers/metricsDataProvider.spec.tsx, line 19 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHQ5VwaWXlcxISRIcLk:-KHQ5VwaWXlcxISRIcLl:-1744968158) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/containers/metricsDataProvider.spec.tsx#L19)):*
> ```XML
>                           timeSpan: Long[],
>                           queryMetrics: (id: string, request: TSRequest) => void) {
>   return shallow(<MetricsDataProvider id={id} metrics={metrics} timeSpan={timeSpan} queryMetrics={queryMetrics}>
> ```

Out of curiosity, how does timeSpan prevent from getting overridden by the redux connect?

---

*[ui/next/app/containers/metricsDataProvider.tsx, line 133 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHPyraPDyJDDaHSa_VV:-KHPyraPDyJDDaHSa_VW:-44405008) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/containers/metricsDataProvider.tsx#L133)):*
> ```XML
>     (props: {children?: any}) => props.children,
>     (children) => {
>       // Perform a simple DFS to find all children which are Selector objects.
> ```

I wonder if someone's written a library that allows you to use jQuery selectors like `find` on react components, since that's all you really want here.

In the future let's pull out this code into a `findChildren(<child predicate>)` util function, since it isn't really related to the metricsDataProvider.

Personally I like this pattern (since the selector lives where it's used, and the parent pulls all the data together) but we might want to revisit it once we have a deeper understanding of react/redux.

---

*[ui/next/app/containers/metricsDataProvider.tsx, line 137 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHPynaytcpHkBdHLjyp:-KHPynaytcpHkBdHLjyq:-779020360) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/containers/metricsDataProvider.tsx#L137)):*
> ```XML
>       let remainingChildren = React.Children.toArray(children);
>       while (remainingChildren.length > 0) {
>         let child = remainingChildren.splice(0, 1)[0] as React.ReactElement<any>;
> ```

You can just use `unshift` instead of `remainingChildren.splice(0, 1)[0]` or `pop` to take from the end depending on if you want BFS or DFS.

---

*[ui/next/app/containers/metricsDataProvider.tsx, line 138 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHQ0_Lbg6wWcsaD4zej:-KHQ0_Lbg6wWcsaD4zek:-1504700745) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/containers/metricsDataProvider.tsx#L138)):*
> ```XML
>       while (remainingChildren.length > 0) {
>         let child = remainingChildren.splice(0, 1)[0] as React.ReactElement<any>;
>         if (child.type === Selector) {
> ```

Let's not change anything for now, but since we're using `reselect`, `Selector` feels overloaded.

---

*[ui/next/app/containers/metricsDataProvider.tsx, line 158 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHQ0xkaBm1A1wxewfDu:-KHQ0xkaBm1A1wxewfDv:1695527961) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/containers/metricsDataProvider.tsx#L158)):*
> ```XML
>     let { metrics, timeSpan, queryMetrics, id } = props;
>     if (!metrics || !metrics.request ||
>         !timeSpanMatch(metrics.request, timeSpan)) {
> ```

Any chance `timeSpan` could be `null`? I wonder if the non-nullable-type stuff from Typescript will help with stuff like this.

---

*[ui/next/app/redux/metrics.ts, line 283 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHOPlC2IfEAVoTydXrI:-KHOPlC3hA_Sc9PVnOzR:-875988373) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/redux/metrics.ts#L283)):*
> ```XML
>               "Accept": "application/json",
>               "Content-Type": "application/json",
>             },
> ```

Are we just making this explicit? Isn't this the default?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-:-KHOPzWZHAZ0bAT4dNqy:657222137)*

**Comment by tamird** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[ui/next/app/components/graphs.tsx, line 60 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHORHOHm3-ncbiB5Qas:-KHQEQ7f5PFMYEMaMYnc:-303006503) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/components/graphs.tsx#L60)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Consider use parens to make the order of operations clear/readable</details>
does join(":") not already return a string?

---

*[ui/next/app/containers/metricsDataProvider.spec.tsx, line 13 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHQEYpXJRnLr0rW3oQm:-KHQEYpXJRnLr0rW3oQn:147960557) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/containers/metricsDataProvider.spec.tsx#L13)):*
> ```XML
> import { MetricsQuery } from "../redux/metrics";
> 
> type TSRequest = cockroach.ts.TimeSeriesQueryRequestMessage;
> ```

i believe you called this TSRequestMessage elsewhere

---

*[ui/next/app/containers/metricsDataProvider.tsx, line 13 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHQEdWJ0GHZQ4mPSW7z:-KHQEdWJ0GHZQ4mPSW8-:-923774516) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/containers/metricsDataProvider.tsx#L13)):*
> ```XML
> import { SelectorProps, Selector, MetricsDataComponentProps } from "../components/graphs";
> 
> type TSQuery = cockroach.ts.QueryMessage;
> ```

ditto re Message suffix (don't care which one you use, just be consistent)

---

*[ui/next/app/containers/metricsDataProvider.tsx, line 40 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHQEyuCL8YRgMn93UMg:-KHQEyuD0Cd5z-lutp-Q:1706293903) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/containers/metricsDataProvider.tsx#L40)):*
> ```XML
>  * current basic strategy), while the Proto2Typescript generated file would need
>  * to be changed dramatically; specifically, it would need generate an
>  * importable module format (rather than its current design of declaring ambient
> ```

Please file an issue upstream and link to it here.

---

*[ui/next/app/containers/nodes.tsx, line 1 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHQD6SC5vJD2nXhOna_:-KHQD6SC5vJD2nXhOnaa:218577139) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/containers/nodes.tsx#L1)):*
> ```XML
> /// <reference path="../../typings/main.d.ts" />
> ```

throughout: how come this was needed now?

---

*[ui/next/app/redux/metrics.ts, line 283 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHOPlC2IfEAVoTydXrI:-KHQD-PgF3LNQiOxjIIs:-34351758) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/redux/metrics.ts#L283)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Are we just making this explicit? Isn't this the default?</details>
+1 to making it explicit - this might want to be overridden when we support protobuf-over-http.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603)*

**Comment by mrtracy** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[ui/next/app/components/graphs.tsx, line 60 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHORHOHm3-ncbiB5Qas:-KHQJ0yqZlviQGulXQJg:1181029734) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/components/graphs.tsx#L60)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> does join(":") not already return a string?</details>
Fixed both of these.

---

*[ui/next/app/containers/metricsDataProvider.spec.tsx, line 13 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHQEYpXJRnLr0rW3oQm:-KHQJscTI5RIHwcqkV3X:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/containers/metricsDataProvider.spec.tsx#L13)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> i believe you called this TSRequestMessage elsewhere</details>
Done.

---

*[ui/next/app/containers/metricsDataProvider.spec.tsx, line 19 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHQ5VwaWXlcxISRIcLk:-KHQJt6I_hhWn6qqyVkK:1709925839) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/containers/metricsDataProvider.spec.tsx#L19)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Out of curiosity, how does timeSpan prevent from getting overridden by the redux connect?</details>
"MetricsDataProvider" here is the _unconnected_ version, as you can see in the import statement.  It takes all of its properties explicitly.

---

*[ui/next/app/containers/metricsDataProvider.tsx, line 13 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHQEdWJ0GHZQ4mPSW7z:-KHQKR2R1UGYE9mAsFM5:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/containers/metricsDataProvider.tsx#L13)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> ditto re Message suffix (don't care which one you use, just be consistent)</details>
Done.

---

*[ui/next/app/containers/metricsDataProvider.tsx, line 40 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHQEyuCL8YRgMn93UMg:-KHQOH1hRWE1WhX86KkP:-1372137183) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/containers/metricsDataProvider.tsx#L40)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Please file an issue upstream and link to it here.</details>
I'm not sure whose issue this actually is. The behavior of plugin-typescript is more exotic in this case (if not actually incorrect), yet it is also more intractable. I think i'm going to log it to Proto2Typescript as a suggestion; I will circle back and add the note here.

---

*[ui/next/app/containers/metricsDataProvider.tsx, line 133 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHPyraPDyJDDaHSa_VV:-KHQN1tPY-P3LKKeUcep:-2112964122) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/containers/metricsDataProvider.tsx#L133)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> I wonder if someone's written a library that allows you to use jQuery selectors like `find` on react components, since that's all you really want here.
> 
> In the future let's pull out this code into a `findChildren(<child predicate>)` util function, since it isn't really related to the metricsDataProvider.
> 
> Personally I like this pattern (since the selector lives where it's used, and the parent pulls all the data together) but we might want to revisit it once we have a deeper understanding of react/redux.</details>
I'm not sure if there is an existing library, but it was simple enough to write here. Yes, i'll pull it out into a utility if I need to do something like this again.

---

*[ui/next/app/containers/metricsDataProvider.tsx, line 137 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHPynaytcpHkBdHLjyp:-KHQMydygvyMH1FiOrDW:944428009) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/containers/metricsDataProvider.tsx#L137)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> You can just use `unshift` instead of `remainingChildren.splice(0, 1)[0]` or `pop` to take from the end depending on if you want BFS or DFS.</details>
It's `shift` actually, but you are right, changed.

---

*[ui/next/app/containers/metricsDataProvider.tsx, line 158 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHQ0xkaBm1A1wxewfDu:-KHQNK2IADUF_mx4dGRR:-643616101) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/containers/metricsDataProvider.tsx#L158)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Any chance `timeSpan` could be `null`? I wonder if the non-nullable-type stuff from Typescript will help with stuff like this.</details>
In a subsequent PR which actually introduces the global timespan element, this is likely going to be a more complicated structure than a simple array. This is essentially just a placeholder for that element.

---

*[ui/next/app/containers/nodes.tsx, line 1 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHQD6SC5vJD2nXhOna_:-KHQMQFT7VVdLcaNkJ2E:1004726842) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/containers/nodes.tsx#L1)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> throughout: how come this was needed now?</details>
I kept getting the errors in the browser, it was extremely annoying.

---

*[ui/next/app/redux/metrics.ts, line 283 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHOPlC2IfEAVoTydXrI:-KHQMJAioThJk6ZId6K9:2142594889) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/redux/metrics.ts#L283)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> +1 to making it explicit - this might want to be overridden when we support protobuf-over-http.</details>
It is also not the default, the default in whatwg-fetch is plain text apparently.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

*[ui/next/app/containers/metricsDataProvider.tsx, line 40 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHQEyuCL8YRgMn93UMg:-KHQc9Gmxo6dApTsOvA5:595387078) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/containers/metricsDataProvider.tsx#L40)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> I'm not sure whose issue this actually is. The behavior of plugin-typescript is more exotic in this case (if not actually incorrect), yet it is also more intractable. I think i'm going to log it to Proto2Typescript as a suggestion; I will circle back and add the note here.</details>
Yeah, in my mind this issue belongs to Proto2Typescript.

---

*[ui/next/app/containers/nodes.tsx, line 1 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHQD6SC5vJD2nXhOna_:-KHQcTrn8aSLiCkHxaMO:66155084) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/containers/nodes.tsx#L1)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> I kept getting the errors in the browser, it was extremely annoying.</details>
which errors?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603)*

**Comment by mrtracy** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[ui/next/app/containers/nodes.tsx, line 1 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHQD6SC5vJD2nXhOna_:-KHQgkChvCPN8CaclYFW:1774096257) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/containers/nodes.tsx#L1)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> which errors?</details>
There appears to be some sort of race condition related to the order files are loaded, I think https://github.com/frankwallis/plugin-typescript/issues/124 is related. The same spew of typing errors (e.g. "cannot find react") randomly occur in the browser console window.

Adding explicit references to main.d.ts in the various files seems to help.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603)*

**Comment by tamird** [comment]
:lgtm:

<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> You should probably make issues for the proto stuff you've encountered, or at least for the most severe.
> 
> :lgtm: </details>


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

*[ui/next/app/containers/nodes.tsx, line 1 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHQD6SC5vJD2nXhOna_:-KHQk7Crbutj09tVHr8a:-1372544868) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/containers/nodes.tsx#L1)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> There appears to be some sort of race condition related to the order files are loaded, I think https://github.com/frankwallis/plugin-typescript/issues/124 is related. The same spew of typing errors (e.g. "cannot find react") randomly occur in the browser console window.
> 
> Adding explicit references to main.d.ts in the various files seems to help.</details>
Interesting. Does this addition fix bundling, btw?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-:-KHQkAm3glia_9hbBQsn:1417088721)*

**Comment by mrtracy** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[ui/next/app/containers/nodes.tsx, line 1 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603#-KHQD6SC5vJD2nXhOna_:-KHQqV0Sxrr9NeTK23Z1:-753716796) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c21d4f86ba661c8ca0ff8dc1f87e3c4ebce1fa/ui/next/app/containers/nodes.tsx#L1)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Interesting. Does this addition fix bundling, btw?</details>
I actually think it will.  I will confirm this, it would allow us to switch over to ui/next officially without depending on that upstream fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6603)*

**Pull request merged**
