### PR TITLE
backupccl: pull remote sst sending into standalone worker

### PR DESCRIPTION
**Pull request by dt**
Release note: none.
Epic: none.

### CODE REVIEW

**Review by msbutler — APPROVED** [review]
Could you rebase and add:

- https://github.com/cockroachdb/cockroach/pull/114326/commits/154a6e64db42d7becb22aae99d039cde426fb332
- https://github.com/cockroachdb/cockroach/pull/114357/commits/784db64b0e67d04405f87f781290b6632c8b3f38

**Comment by dt** [comment]
I picked up https://github.com/cockroachdb/cockroach/commit/154a6e64db42d7becb22aae99d039cde426fb332.

The tracing one I have questions about (if we should be grabbing recordings and logging vs point it at a collector and/or using profiler), so I'd rather rebase it on this once those are sorted out.

**Comment by dt** [comment]
TFTR!

bors r+

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
