### PR TITLE
roachtest: fix one flake in acceptance/version-upgrade

### LINKED ISSUE #32479: teamcity: failed test: version-upgrade
The following tests appear to have failed on master (roachtest): acceptance/version-upgrade

You may want to check [for open issues](https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+is%3Aopen+version-upgrade).

[#1018742](https://teamcity.cockroachdb.com/viewLog.html?buildId=1018742):

```
acceptance/version-upgrade
--- FAIL: roachtest/acceptance/version-upgrade (76.323s)
	test.go:645,upgrade.go:393,upgrade.go:395,upgrade.go:546,acceptance.go:65: dial tcp 127.0.0.1:26259: connect: connection refused





```

Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by tbg**
Use more recent versions of past releases. Also actually upgrade to the
latest cluster version at the end.

Assuming
https://github.com/cockroachdb/cockroach/issues/32479#issuecomment-440347078
holds true, this:

Fixes #32479.

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32535#-:-LRql5Ns33-jd3OqjFUJ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by petermattis — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32535)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/upgrade.go, line 376 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32535#-LRqy1XD3VxmyAR1F5aR:-LRqy1XD3VxmyAR1F5aS:b-xn8pzl) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b42c63040b56813cbb9fbe7097fd4ec9a6186f6/pkg/cmd/roachtest/upgrade.go#L376)):*
> ```Go
> 						t.Fatal(err)
> 					}
> 				}()
> ```

Oh, is this necessary or desirable now that we have automatic version upgrades?

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32535)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/upgrade.go, line 376 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32535#-LRqy1XD3VxmyAR1F5aR:-LRr0-iF4IH6mHbPZWZe:b-2p6hu7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b42c63040b56813cbb9fbe7097fd4ec9a6186f6/pkg/cmd/roachtest/upgrade.go#L376)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Oh, is this necessary or desirable now that we have automatic version upgrades?
</blockquote></details>

This is only used to verify that the update took place (note that `manual` is false for the case that uses this).

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32535)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by tbg** [comment]
bors r=petermattis
TFTR!

**Pull request merged**
