### PR TITLE
kv, storage: Enforce size limits on transactions and raft commands

### LINKED ISSUE #13424: stability: node crashing and not able to recover after running out of memory
### Dev machine specs:

8 GB memory
2 vCPU
20 GB disk

### DB

2 million~ rows

Columns look like this: 

``
id SERIAL PRIMARY KEY, 
col1 string(1500), 
col2 string(100), 
col3 string(50), 
col4 string(500), 
col5 int, 
col6 string(100), 
col7 string(30), 
col8 int,
col9 int
``

# The problem

So I inserted 2 million feeds into cockroachdb this will take like 1.5 gig of memoy usage.

Now we forgot to insert the value for col5, and it says NULL. So i'll do
``
update table set col5 = 30
``

Now after a while it will lose connection to the DB and according to the log files CockroachDB ran out of memory.

When restarting CockroachDB it will continue on doing something big using 50-80% CPU and 8 GB of ram + 4 GB off swap this will continue for like an hour, than suddenly it will take the remaining 4 GB swap space and crash again.

### PR DESCRIPTION
**Pull request by bdarnell**
Fixes #13424

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/kv/txn_coord_sender_test.go, line 1593 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15350#-KieCHVgNbRNPIxW9rWr:-KieCHVgNbRNPIxW9rWs:b-npys30) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eb8b7582b2a44285e06eb860c261f2b51177a6c/pkg/kv/txn_coord_sender_test.go#L1593)):*
> ```Go
> 		maxIntents = s
> 	}(maxIntents)
> 	maxIntents = settings.TestingIntSetting(3)
> ```

@dt I wonder if `TestingXSetting` should take a `**XSetting` parameter and return a `func()` which resets it. Something like:


```
func TestingIntSetting(s **IntSetting, v int64) func() {
  saved := *s
  *s = &IntSetting{defaultValue: v}
  s.setToDefault()
  return func() {
    *s = saved
  }
}
```

The usage would then look like:

```
defer settings.TestingIntSetting(&maxIntents, 3)()
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15350#-:-KieDDMt8vSmo5oOIKO7:bnfp4nl)*

**Comment by andreimatei** [comment]
Are txns that have accumulated over max_intents be clean

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/kv/txn_coord_sender.go, line 402 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15350#-KiefeDVhV7dkDXjwTv2:-KiefeDVhV7dkDXjwTv3:b-lyhsww) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eb8b7582b2a44285e06eb860c261f2b51177a6c/pkg/kv/txn_coord_sender.go#L402)):*
> ```Go
> 				return roachpb.NewErrorf("cannot commit a read-only transaction")
> 			}
> 			if int64(len(et.IntentSpans)) > maxIntents.Get() {
> ```

won't this prevent us from rolling back transactions that have gotten into this state?

On the other hand, is it even possible to fail this check given the other check in `updateState()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15350#-:-KiefBqdv1-Dnti1xlaa:b-s7uekn)*

**Comment by bdarnell** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/kv/txn_coord_sender.go, line 402 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15350#-KiefeDVhV7dkDXjwTv2:-KiejENmCPcJUDP_tLwx:b-ixavyn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eb8b7582b2a44285e06eb860c261f2b51177a6c/pkg/kv/txn_coord_sender.go#L402)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

won't this prevent us from rolling back transactions that have gotten into this state?

On the other hand, is it even possible to fail this check given the other check in `updateState()`?
</blockquote></details>

Yes, it's possible to fail this check - it runs *before* the one in updateState for the last batch of a transaction. 

And yes, this prevents us from rolling back transactions that have gotten into this state on this path. They'll be cleaned up on the slow path later on. The goal here is to avoid getting the server into a death loop by writing huge commands into the logs; we can work on handling this failure more gracefully post-1.0.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15350)*

**Comment by andreimatei** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/kv/txn_coord_sender.go, line 402 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15350#-KiefeDVhV7dkDXjwTv2:-KiemOkk4oqamubQ74q9:b-tqjqsm) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eb8b7582b2a44285e06eb860c261f2b51177a6c/pkg/kv/txn_coord_sender.go#L402)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Yes, it's possible to fail this check - it runs *before* the one in updateState for the last batch of a transaction. 

And yes, this prevents us from rolling back transactions that have gotten into this state on this path. They'll be cleaned up on the slow path later on. The goal here is to avoid getting the server into a death loop by writing huge commands into the logs; we can work on handling this failure more gracefully post-1.0.
</blockquote></details>

OK. I've filed https://github.com/cockroachdb/cockroach/issues/15353 so we don't forget. Seems bad to me too leave such huge numbers of intents around to be cleaned up one at a time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15350)*

**Comment by dt** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/kv/txn_coord_sender_test.go, line 1593 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15350#-KieCHVgNbRNPIxW9rWr:-KiehXReJVFYKYIZIbcY:b-n24u94) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eb8b7582b2a44285e06eb860c261f2b51177a6c/pkg/kv/txn_coord_sender_test.go#L1593)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

@dt I wonder if `TestingXSetting` should take a `**XSetting` parameter and return a `func()` which resets it. Something like:


```
func TestingIntSetting(s **IntSetting, v int64) func() {
  saved := *s
  *s = &IntSetting{defaultValue: v}
  s.setToDefault()
  return func() {
    *s = saved
  }
}
```

The usage would then look like:

```
defer settings.TestingIntSetting(&maxIntents, 3)()
```
</blockquote></details>

Agreed. #15361.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15350)*

**Pull request merged**
