### PR TITLE
sql,cli: misc statement bundle fixes

### LINKED ISSUE #83546: cli: crash with \statement-diag list in demo
If I spin up a demo on e19d98d6a602ddefe557da12ab08263d4d48b853, and do this:
```
SELECT crdb_internal.request_statement_bundle('SELECT _', 0::FLOAT, 0::INTERVAL, 0::INTERVAL);
SELECT 1;
```
so that a single stmt bundle is collected and then try to see the available bundles with `\statement-diag list`, the CLI crashes:
```
*
* ERROR: a panic has occurred!
* interface conversion: driver.Value is string, not int64
* (1) attached stack trace
*   -- stack trace:
*   | github.com/cockroachdb/cockroach/pkg/cli/clisqlclient.stmtDiagListBundlesInternal
*   | 	github.com/cockroachdb/cockroach/pkg/cli/clisqlclient/statement_diag.go:64
*   | github.com/cockroachdb/cockroach/pkg/cli/clisqlclient.StmtDiagListBundles
*   | 	github.com/cockroachdb/cockroach/pkg/cli/clisqlclient/statement_diag.go:36
*   | github.com/cockroachdb/cockroach/pkg/cli/clisqlshell.(*cliState).statementDiagList
*   | 	github.com/cockroachdb/cockroach/pkg/cli/clisqlshell/statement_diag.go:80
*   | github.com/cockroachdb/cockroach/pkg/cli/clisqlshell.(*cliState).handleStatementDiag
*   | 	github.com/cockroachdb/cockroach/pkg/cli/clisqlshell/statement_diag.go:40
```

Jira issue: CRDB-17135

### LINKED ISSUE #86472: sql: EXPLAIN ANALYZE generates invalid bundles
If the query being analyzed does not use tables, the resulting bundle is missing schema.sql.

It makes it impossible to load the bundle afterwards.

### PR DESCRIPTION
**Pull request by knz**
Fixes #86472.
Fixes https://github.com/cockroachdb/cockroach/issues/83546.

Replaces #86303.

Release justification: bug fixes

### CODE REVIEW

**Review by cucaroach — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86484)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @yuzefovich)

___
*[`-- commits` line 11 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86484#-NA4p4igDb381ZW7p9Uv):*
s/statement-diag/statement-bundle/
___
*[`-- commits` line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86484#-NA4pU0f5Wcf98lu8JWC):*
s/statement-diag/statement-bundle/
___
*[`-- commits` line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86484#-NA4pbvi5tHbhh1E6eiJ):*
s/statement-diag/statement-bundle/

**Review by yuzefovich — COMMENTED** [review]
Thanks!

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86484#-:-NA5_njH0IAvwUqa0KEW:b-ucfknh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`-- commits` line 56 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86484#-NA5_Jqg09WC-HlJdPyr):*
This commit seems to fix #83546. Is the bug present on older branches? (I thought it was only on 22.2, so the release note shouldn't be necessary.)

**Review by knz — COMMENTED** [review]
I have added the missing tests. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86484#-:-NBCzVHwAetmCD8ixxPH:bkyytn5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[`-- commits` line 11 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86484#-NA4p4igDb381ZW7p9Uv):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

s/statement-diag/statement-bundle/
</blockquote></details>

Done.
___
*[`-- commits` line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86484#-NA4pU0f5Wcf98lu8JWC):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

s/statement-diag/statement-bundle/
</blockquote></details>

Done.
___
*[`-- commits` line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86484#-NA4pbvi5tHbhh1E6eiJ):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

s/statement-diag/statement-bundle/
</blockquote></details>

Done.
___
*[`-- commits` line 56 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86484#-NA5_Jqg09WC-HlJdPyr):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

This commit seems to fix #83546. Is the bug present on older branches? (I thought it was only on 22.2, so the release note shouldn't be necessary.)
</blockquote></details>

It was 22.2-only (due to the migration from lib/pq to pgx).

**Review by yuzefovich — APPROVED** [review]
:lgtm: Thanks!

> Reviewed 8 of 8 files at r5, 2 of 2 files at r6, 3 of 3 files at r7, 3 of 3 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86484#-:-NBJrSnVCxXpm82awZi_:b-g2a5fb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @knz)

___
*[`-- commits` line 56 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86484#-NA5_Jqg09WC-HlJdPyr):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

It was 22.2-only (due to the migration from lib/pq to pgx).
</blockquote></details>

So we don't need a release note, right?
___
*[`pkg/sql/tests/monotonic_insert_test.go` line 95 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/86484#-NBJpw5NEI5EoMca-kOQ:-NBJpw5NEI5EoMca-kOR:bjngjhf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f89b151203b2317b20cc717185c0e525ac5fe803/pkg/sql/tests/monotonic_insert_test.go#L95)):*
> ```Go
> 
> 	skip.UnderShort(t)
> 	skip.UnderRace(t) // Too slow under race.
> ```

First commit seems out of place.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86484)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[`-- commits` line 56 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86484#-NA5_Jqg09WC-HlJdPyr):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

So we don't need a release note, right?
</blockquote></details>

You're right. Removed
___
*[`pkg/sql/tests/monotonic_insert_test.go` line 95 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/86484#-NBJpw5NEI5EoMca-kOQ:-NBMPKkREfzqKK4K8bQm:ba3dfob) ([raw file](https://github.com/cockroachdb/cockroach/blob/f89b151203b2317b20cc717185c0e525ac5fe803/pkg/sql/tests/monotonic_insert_test.go#L95)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

First commit seems out of place.
</blockquote></details>

Removed

**Comment by knz** [comment]
TFYR!

bors r=yuzefovich,cucaroach

**Comment by knz** [comment]
bors r=yuzefovich,cucaroach

**Comment by knz** [comment]
unrelated flake

bors r=yuzefovich,cucaroach

**Pull request merged**
