### PR TITLE
sql: implement `GENERATED ... AS IDENTITY` functionality for `INSERT/UPDATE/UPSERT`

### PR DESCRIPTION
**Pull request by ZhouXing19**
This commit is to implement the functionality of
GENERATED {ALWAYS | BY DEFAULT} AS IDENTITY
for INSERT/UPDATE/UPSERT statement.

In PostgreSQL, if a column is created with
GENERATED ALWAYS AS IDENTITY token,

  1. it can only be updated to DEFAULT;
  2. when executing INSERT on this column, the conflict
  cannot be resolved by `ON CONFLICT` statement;
  3. it cannot be written explicitly; (i.e. cannot INSERT/UPSERT
  without the OVERRIDING SYSTEM VALUE token);
  4. it is implicitly NOT NULL, but we must INSERT/UPSERT
  without specifying the value for it.

If a column is created with
`GENERATED BY DEFAULT AS IDENTITY` token,
the above restrictions do not apply to it.

Tests for optbuilder support is added in
pkg/sql/opt/optbuilder/testdata.

This commit also adds a type restriction for
GENERATED {ALWAYS | BY DEFAULT} AS IDENTITY
syntax under CREATE TABLE -- this column can only be of smallint,
integer, or bigint type.

This matches the PostgreSQL syntax:
https://www.postgresql.org/docs/current/sql-createtable.html

Release note: None

Release justification: although this supports a new feature,
the changes are high-benefit and have been under scrutiny for many weeks now,
so after discussing with other leads we feel fine about merging this during
stability period.

### CODE REVIEW

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69043)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)

___
*[pkg/sql/update.go, line 426 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhPd4mwBhCcqYaeorm_:-MhPd4mwBhCcqYaeorma:bwkt9s2) ([raw file](https://github.com/cockroachdb/cockroach/blob/43f53a15b515b3b2f09cc7f950470636b427f9dd/pkg/sql/update.go#L426)):*
> ```Go
> 			if col.IsGeneratedAsIdentity() {
> 				continue
> 			}
> ```

This check should just be temporary until you add the default expression for `GENERATE ... IDENTITY` columns to column descriptors, correct? It might be simpler to make that change before this PR? If not, you should leave a TODO here that this is only necessary temporarily.
___
*[pkg/sql/opt/optbuilder/testdata/insert, line 1313 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhPaxjO2c3-YwYVH2Cd:-MhPaxjO2c3-YwYVH2Ce:b-rifwnl) ([raw file](https://github.com/cockroachdb/cockroach/blob/43f53a15b515b3b2f09cc7f950470636b427f9dd/pkg/sql/opt/optbuilder/testdata/insert#L1313)):*
> ```
>       │    └── (1, 10)
>       └── projections
>            ├── NULL::INT8 [as=b_default:9]
> ```

nit: you could leave a TODO for all the optbuilder tests that are projecting `NULL` when they should be something like `nextval(...)`? You'll need to update the test catalog for these columns when you update the column descriptors to have a default expression, so that they match.
___
*[pkg/sql/opt/optbuilder/testdata/update, line 1658 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhPV9JOAui1C3NrjRoG:-MhPV9JOAui1C3NrjRoH:bkzr6li) ([raw file](https://github.com/cockroachdb/cockroach/blob/43f53a15b515b3b2f09cc7f950470636b427f9dd/pkg/sql/opt/optbuilder/testdata/update#L1658)):*
> ```
> 
> build
> INSERT INTO generated_as_identity (a) VALUES (10), (11), (12);
> ```

nit: There's not need for an `INSERT` test here. opt tests don't actually execute statements, they only output the query plan for a statement. So there's no need to `INSERT` any rows to test `UPDATE`s in these tests.

**Comment by ZhouXing19** [comment]
___
*[pkg/sql/update.go, line 426 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhPd4mwBhCcqYaeorm_:-MhPhOhPDsQ4LqCT-Uw5:b-6lc8a3) ([raw file](https://github.com/cockroachdb/cockroach/blob/43f53a15b515b3b2f09cc7f950470636b427f9dd/pkg/sql/update.go#L426)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This check should just be temporary until you add the default expression for `GENERATE ... IDENTITY` columns to column descriptors, correct? It might be simpler to make that change before this PR? If not, you should leave a TODO here that this is only necessary temporarily.
</blockquote></details>

Hmm it's not temporary -- the idea is that if we have table `t` with `(a INT, b INT GENERATED {ALWAYS | BY DEFAULT} AS IDENTITY)`, we allow `INSERT INTO t (a) VALUES (10)`, though `b` should be implicitly `NOT NULL`.

**Review by ZhouXing19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69043)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rafiss)

___
*[pkg/sql/opt/optbuilder/testdata/insert, line 1313 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhPaxjO2c3-YwYVH2Cd:-MhPnL114Rkcgq22z1XB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/43f53a15b515b3b2f09cc7f950470636b427f9dd/pkg/sql/opt/optbuilder/testdata/insert#L1313)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: you could leave a TODO for all the optbuilder tests that are projecting `NULL` when they should be something like `nextval(...)`? You'll need to update the test catalog for these columns when you update the column descriptors to have a default expression, so that they match.
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/testdata/update, line 1658 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhPV9JOAui1C3NrjRoG:-MhPnQNs4EVLuRagTsOL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/43f53a15b515b3b2f09cc7f950470636b427f9dd/pkg/sql/opt/optbuilder/testdata/update#L1658)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: There's not need for an `INSERT` test here. opt tests don't actually execute statements, they only output the query plan for a statement. So there's no need to `INSERT` any rows to test `UPDATE`s in these tests.
</blockquote></details>

Done.

**Review by rafiss — COMMENTED** [review]
lgtm!

**Review by rytaft — COMMENTED** [review]
> Reviewed 2 of 32 files at r5, 32 of 32 files at r10, 18 of 18 files at r11, 15 of 15 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69043)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @ZhouXing19)

___
*[pkg/sql/update.go, line 426 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhPd4mwBhCcqYaeorm_:-MhVQ5He6v7wjZOUIWxI:bgksfac) ([raw file](https://github.com/cockroachdb/cockroach/blob/43f53a15b515b3b2f09cc7f950470636b427f9dd/pkg/sql/update.go#L426)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Hmm it's not temporary -- the idea is that if we have table `t` with `(a INT, b INT GENERATED {ALWAYS | BY DEFAULT} AS IDENTITY)`, we allow `INSERT INTO t (a) VALUES (10)`, though `b` should be implicitly `NOT NULL`.
</blockquote></details>

I think @mgartner is right -- we should have already set the value by this point in the code, probably to `unique_rowid()` (see my comments in one of the opt test files)
___
*[pkg/sql/logictest/testdata/logic_test/upsert, line 1306 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhVQmyC1VYmx3G6yi5H:-MhVQmyC1VYmx3G6yi5I:bm9wv27) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8224f6b5c2f6a7eed6c229296d123279414c535/pkg/sql/logictest/testdata/logic_test/upsert#L1306)):*
> ```
> 
> statement error pq: cannot insert into column "b"\nDETAIL: Column "b" is an identity column defined as GENERATED ALWAYS.
> INSERT INTO generated_as_id_t (a, b) VALUES (1, 10) ON CONFLICT (a) DO UPDATE SET b=DEFAULT;
> ```

how about adding a test like:
```
INSERT INTO generated_as_id_t (a) VALUES (1) ON CONFLICT (a) DO UPDATE SET b=DEFAULT;
``` 
___
*[pkg/sql/opt/optbuilder/insert.go, line 618 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhVR6S4-Dw-MD6t2SnX:-MhVR6S4-Dw-MD6t2SnY:bks8pfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8224f6b5c2f6a7eed6c229296d123279414c535/pkg/sql/opt/optbuilder/insert.go#L618)):*
> ```Go
> 
> 		// Check if the input column is created with `GENERATED ALWAYS AS IDENTITY`
> 		// token. If yes, and users does not specify the `OVERRIDING SYSTEM VALUE` token
> ```

nit: users does not -> the user does not
___
*[pkg/sql/opt/optbuilder/insert.go, line 620 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhVREWcDtwb21zVUlNJ:-MhVREWcDtwb21zVUlNK:b-ex22xl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8224f6b5c2f6a7eed6c229296d123279414c535/pkg/sql/opt/optbuilder/insert.go#L620)):*
> ```Go
> 		// token. If yes, and users does not specify the `OVERRIDING SYSTEM VALUE` token
> 		// in the `INSERT` statement, checkColumnIsNotGeneratedAlwaysAsIdentity
> 		// will return error.
> ```

nit: maybe say "raise an error" since technically it's not returned
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 1339 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhVRhJfDBXXS2HgEDkh:-MhVRhJfDBXXS2HgEDki:b-gjwul4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8224f6b5c2f6a7eed6c229296d123279414c535/pkg/sql/opt/optbuilder/mutation_builder.go#L1339)):*
> ```Go
> // check also https://github.com/cockroachdb/cockroach/issues/68201.
> //
> // This function is used in codes for UPDATE, INSERT and UPSERT statement.
> ```

nit: codes -> code
___
*[pkg/sql/opt/optbuilder/update.go, line 200 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhVScyA0nxeQfk6nJFx:-MhVScyA0nxeQfk6nJFy:b-thp5ys) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8224f6b5c2f6a7eed6c229296d123279414c535/pkg/sql/opt/optbuilder/update.go#L200)):*
> ```Go
> 
> 		for _, expr := range exprs {
> 			// Compatability check the input expression against the corresponding table column.
> ```

nit: columns should be <= 80 columns wide
___
*[pkg/sql/opt/optbuilder/testdata/insert, line 1274 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhVXjIlCM03y_hrMKf1:-MhVXPxrBHgMoT_PgyQI:bqfa89e) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8224f6b5c2f6a7eed6c229296d123279414c535/pkg/sql/opt/optbuilder/testdata/insert#L1274)):*
> ```
> # With GENERATED AS IDENTITY syntax
> # It is ok that all GENERATED ... AS IDENTITY columns are projected to be NULL,
> # which is consistent with the case with a SERIAL column (check below).
> ```

As I mentioned below, I don't think this is actually how SERIAL works in CRDB, just in the opt test catalog.

So instead of projecting NULL, I think it would be better to set a real default value (perhaps when the column is first created) that can be used here instead. If you want to match the behavior of SERIAL, that default should probably be `unique_rowid()`.
___
*[pkg/sql/opt/optbuilder/testdata/insert, line 1297 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhVTDNr-4IWp5KxVqeU:-MhVTDNr-4IWp5KxVqeV:beg6cq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8224f6b5c2f6a7eed6c229296d123279414c535/pkg/sql/opt/optbuilder/testdata/insert#L1297)):*
> ```
> ON CONFLICT (b) DO UPDATE b = (1+1)
> ----
> error (42601): at or near "b": syntax error
> ```

did you mean to test something else here?
___
*[pkg/sql/opt/optbuilder/testdata/insert, line 1339 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhVWQJz8qUPhTVSPwiM:-MhVWQJz8qUPhTVSPwiN:bz75g94) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8224f6b5c2f6a7eed6c229296d123279414c535/pkg/sql/opt/optbuilder/testdata/insert#L1339)):*
> ```
> 
> exec-ddl
> CREATE TABLE serial_t (
> ```

I don't think this is actually how SERIAL behaves in the real DB. If you try running this in `cockroach demo`, I think you'll see that it automatically gets converted to `INT8 NOT NULL DEFAULT unique_rowid()`. Looks like we just didn't implement that logic in the optimizer test catalog.
___
*[pkg/sql/sqlerrors/errors.go, line 55 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhVTsjs0EDFoVLxo-jv:-MhVTsjs0EDFoVLxo-jw:b-5r817j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8224f6b5c2f6a7eed6c229296d123279414c535/pkg/sql/sqlerrors/errors.go#L55)):*
> ```Go
> // created with `GENERATED ALWAYS AS IDENTITY` token.
> // TODO(janexing): Should add a HINT with "Use OVERRIDING SYSTEM VALUE to override." once issue #68201 is resolved.
> // Check also: https://github.com/cockroachdb/cockroach/issues/68201
> ```

nit: comments should be <= 80 columns wide
___
*[pkg/sql/sqlerrors/errors.go, line 60 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhVUcKD2ZMuhkNjwc8S:-MhVUcKD2ZMuhkNjwc8T:bpnf5w1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8224f6b5c2f6a7eed6c229296d123279414c535/pkg/sql/sqlerrors/errors.go#L60)):*
> ```Go
> 		pgerror.Newf(pgcode.GeneratedAlways, "cannot insert into column %q", columnName),
> 		"Column %q is an identity column defined as GENERATED ALWAYS", columnName,
> 	)
> ```

Can you also add the hint "Use OVERRIDING SYSTEM VALUE to override." like Postgres does?

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69043)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @ZhouXing19)

___
*[pkg/sql/update.go, line 426 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhPd4mwBhCcqYaeorm_:-MhVfYguDuzCcBSjloAM:b77lkmx) ([raw file](https://github.com/cockroachdb/cockroach/blob/43f53a15b515b3b2f09cc7f950470636b427f9dd/pkg/sql/update.go#L426)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think @mgartner is right -- we should have already set the value by this point in the code, probably to `unique_rowid()` (see my comments in one of the opt test files)
</blockquote></details>

Edit: I see that you added the default expression in https://github.com/cockroachdb/cockroach/pull/69107, so you should be able to remove this check in that PR.
___
*[pkg/sql/opt/optbuilder/testdata/insert, line 1274 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhVXjIlCM03y_hrMKf1:-MhVgTtw7CStOvat8F0A:bqstlgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8224f6b5c2f6a7eed6c229296d123279414c535/pkg/sql/opt/optbuilder/testdata/insert#L1274)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

As I mentioned below, I don't think this is actually how SERIAL works in CRDB, just in the opt test catalog.

So instead of projecting NULL, I think it would be better to set a real default value (perhaps when the column is first created) that can be used here instead. If you want to match the behavior of SERIAL, that default should probably be `unique_rowid()`.
</blockquote></details>

Edit: I see that you added the default in https://github.com/cockroachdb/cockroach/pull/69107, so you'll probably want to implement a simpler version of that in the opt test catalog.
___
*[pkg/sql/opt/optbuilder/testdata/insert, line 1339 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhVWQJz8qUPhTVSPwiM:-MhVgqzn9PGPU7a33txe:b-xtieu) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8224f6b5c2f6a7eed6c229296d123279414c535/pkg/sql/opt/optbuilder/testdata/insert#L1339)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I don't think this is actually how SERIAL behaves in the real DB. If you try running this in `cockroach demo`, I think you'll see that it automatically gets converted to `INT8 NOT NULL DEFAULT unique_rowid()`. Looks like we just didn't implement that logic in the optimizer test catalog.
</blockquote></details>

(After looking at the docs, I see that the default depends on the `serial_normalization` session var. But it's still never NULL).

**Comment by ZhouXing19** [comment]
___
*[pkg/sql/sqlerrors/errors.go, line 60 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhVUcKD2ZMuhkNjwc8S:-Mh_oMk6CQXWZnis8lMw:bxpfpoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8224f6b5c2f6a7eed6c229296d123279414c535/pkg/sql/sqlerrors/errors.go#L60)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Can you also add the hint "Use OVERRIDING SYSTEM VALUE to override." like Postgres does?
</blockquote></details>

Not sure if we should add it, because we haven't implement `OVERRIDING SYSTEM VALUE` for `INSERT/UPSERT/UPDATE` statement yet. Related issue is raised [here](https://github.com/cockroachdb/cockroach/issues/68201).

**Review by ZhouXing19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69043)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @rytaft, and @ZhouXing19)

___
*[pkg/sql/logictest/testdata/logic_test/upsert, line 1306 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhVQmyC1VYmx3G6yi5H:-Mh_tV6b20VifZeRGlG-:b-a8y1vp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8224f6b5c2f6a7eed6c229296d123279414c535/pkg/sql/logictest/testdata/logic_test/upsert#L1306)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

how about adding a test like:
```
INSERT INTO generated_as_id_t (a) VALUES (1) ON CONFLICT (a) DO UPDATE SET b=DEFAULT;
``` 
</blockquote></details>

This query provides different output from PostgreSQL due to the inconsistency of the `SERIAL` syntax between CRDB and PostgreSQL. [A related issue](https://github.com/cockroachdb/cockroach/issues/69208) is raised.

**Review by ZhouXing19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69043)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/update.go, line 426 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhPd4mwBhCcqYaeorm_:-MhnnyHn65L12xZ87NwB:b-dhyf4g) ([raw file](https://github.com/cockroachdb/cockroach/blob/43f53a15b515b3b2f09cc7f950470636b427f9dd/pkg/sql/update.go#L426)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Edit: I see that you added the default expression in https://github.com/cockroachdb/cockroach/pull/69107, so you should be able to remove this check in that PR.
</blockquote></details>

Done, made the change in #69107. Check [here](https://github.com/cockroachdb/cockroach/pull/69107/commits/1db94f5a21f78341b5aa438101205487bbf30f97#diff-686f710b9449d6982a19bcfa8c7af5be145a33ceecf2ded0ead6852739d5f4bb).
___
*[pkg/sql/opt/optbuilder/insert.go, line 618 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhVR6S4-Dw-MD6t2SnX:-Mhno4WwD0fDnr-MUCmD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8224f6b5c2f6a7eed6c229296d123279414c535/pkg/sql/opt/optbuilder/insert.go#L618)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: users does not -> the user does not
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/insert.go, line 620 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhVREWcDtwb21zVUlNJ:-Mhno5ZZEnGzrRA2jj3-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8224f6b5c2f6a7eed6c229296d123279414c535/pkg/sql/opt/optbuilder/insert.go#L620)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: maybe say "raise an error" since technically it's not returned
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 1339 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhVRhJfDBXXS2HgEDkh:-Mhno75f6DBagWoqmPiM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8224f6b5c2f6a7eed6c229296d123279414c535/pkg/sql/opt/optbuilder/mutation_builder.go#L1339)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: codes -> code
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/update.go, line 200 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhVScyA0nxeQfk6nJFx:-Mhno87MA1kBQV1j2Z9g:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8224f6b5c2f6a7eed6c229296d123279414c535/pkg/sql/opt/optbuilder/update.go#L200)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: columns should be <= 80 columns wide
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/testdata/insert, line 1274 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhVXjIlCM03y_hrMKf1:-Mhnr6Qf1ZwcVuFTrx-A:bwj5f6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8224f6b5c2f6a7eed6c229296d123279414c535/pkg/sql/opt/optbuilder/testdata/insert#L1274)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Edit: I see that you added the default in https://github.com/cockroachdb/cockroach/pull/69107, so you'll probably want to implement a simpler version of that in the opt test catalog.
</blockquote></details>

@rytaft Made the change in #69107 , check [here](https://github.com/cockroachdb/cockroach/pull/69107/commits/64cb71f8faa40dde3e0ad8adf0052547f79bcf6f#diff-789f254a6c1149bcb3e3d9b15c092e768acea4e396aea364f06c6316971925cb) for `insert` and [here](https://github.com/cockroachdb/cockroach/pull/69107/commits/64cb71f8faa40dde3e0ad8adf0052547f79bcf6f) for `upsert`. Also added similar projection for `SERIAL` columns.
___
*[pkg/sql/opt/optbuilder/testdata/insert, line 1297 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhVTDNr-4IWp5KxVqeU:-MhnqPyR1Xj4EPPpDztQ:b-serus5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8224f6b5c2f6a7eed6c229296d123279414c535/pkg/sql/opt/optbuilder/testdata/insert#L1297)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

did you mean to test something else here?
</blockquote></details>

Yes I missed the `SET` after the `UPDATE`. Thanks for pointing it out!
___
*[pkg/sql/opt/optbuilder/testdata/insert, line 1339 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhVWQJz8qUPhTVSPwiM:-MhnqVHqAtAHJS3FH4WY:brxoo7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8224f6b5c2f6a7eed6c229296d123279414c535/pkg/sql/opt/optbuilder/testdata/insert#L1339)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

(After looking at the docs, I see that the default depends on the `serial_normalization` session var. But it's still never NULL).
</blockquote></details>

Thanks! Made the change in #69107 , check [here](https://github.com/cockroachdb/cockroach/pull/69107/commits/64cb71f8faa40dde3e0ad8adf0052547f79bcf6f#diff-789f254a6c1149bcb3e3d9b15c092e768acea4e396aea364f06c6316971925cb) for `insert` and [here](https://github.com/cockroachdb/cockroach/pull/69107/commits/64cb71f8faa40dde3e0ad8adf0052547f79bcf6f) for `upsert`. Also added similar projection for `SERIAL` columns.
___
*[pkg/sql/sqlerrors/errors.go, line 55 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhVTsjs0EDFoVLxo-jv:-MhnqJV-AFqp0xtxGRK3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8224f6b5c2f6a7eed6c229296d123279414c535/pkg/sql/sqlerrors/errors.go#L55)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: comments should be <= 80 columns wide
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 2 of 31 files at r13, 19 of 22 files at r14, 1 of 16 files at r16, 15 of 15 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-:-MhoQbJb37rzetj5n-9i:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @ZhouXing19)

___
*[-- commits, line 52 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhoQIUy25XGlEbusq8b:-MhoQIUy25XGlEbusq8c:ba6yqhf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d49f2800d3db87baa0455947d84e1d794a34ae99/-- commits#L52)):*
I think you'll need to fill this in
___
*[pkg/clusterversion/cockroach_versions.go, line 305 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhoQMzO77ceINZutPKX:-MhoQMzO77ceINZutPKY:ba0v9m8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d49f2800d3db87baa0455947d84e1d794a34ae99/pkg/clusterversion/cockroach_versions.go#L305)):*
> ```Go
> 	UseKeyEncodeForHashShardedIndexes
> 	// GeneratedAsIdentity is the syntax support for `GENERATED {ALWAYS | BY
> 	//DEFAULT} AS IDENTITY` under `CREATE TABLE` syntax.
> ```

nit: add a space between // and GENERATED
___
*[pkg/sql/sqlerrors/errors.go, line 60 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69043#-MhVUcKD2ZMuhkNjwc8S:-MhoQDXV3ysNXrIAOTND:brxp9sq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8224f6b5c2f6a7eed6c229296d123279414c535/pkg/sql/sqlerrors/errors.go#L60)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Not sure if we should add it, because we haven't implement `OVERRIDING SYSTEM VALUE` for `INSERT/UPSERT/UPDATE` statement yet. Related issue is raised [here](https://github.com/cockroachdb/cockroach/issues/68201).
</blockquote></details>

Sounds good.

**Review by rafiss — APPROVED** [review]

**Pull request merged**
