### PR TITLE
delegate: implement SHOW REGION FROM DATABASE

### PR DESCRIPTION
**Pull request by otan**
Looks like SHOW REGION FROM DATABASE has an optional db argument
throughout the spec, so why not implement both it ways.

Release note (sql change): Implement SHOW REGION FROM DATABASE and SHOW
REGION FROM DATABASE db, which shows all regions for the given database,
as well as whether that region is the primary region.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57106)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/delegate/show_regions.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57106#-MN0CwiVDxPe-0Tk58W5:-MN0CwiVDxPe-0Tk58W6:b4z9qu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fcd50c4536e6fdc2c6592eaf577e0e7fe594221/pkg/sql/delegate/show_regions.go#L56)):*
> ```Go
> 		query := fmt.Sprintf(
> 			`
> WITH zones_table(region, zones) AS (%s)
> ```

Do we want `SHOW REGIONS FROM DATABASE` to be impacted by the available nodes in the database? I thought we decided that we didn't?

I guess the idea is that we want to show the zones associated with each database region but the zones themselves aren't a static property of the database. This is nice, but we should also make sure that it doesn't lead to one of a database's regions disappearing when all nodes in the region are decommissioned. Maybe that just means that we should use a LEFT JOIN below and coalesce `zones_table.zones` with an empty array.
___
*[pkg/sql/sem/tree/show.go, line 283 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57106#-MN0EG0ZCuFM5NpHnEGs:-MN0EG0ZCuFM5NpHnEGt:b-58s9dc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fcd50c4536e6fdc2c6592eaf577e0e7fe594221/pkg/sql/sem/tree/show.go#L283)):*
> ```Go
> // ShowRegions represents a SHOW REGIONS statement
> type ShowRegions struct {
> 	Database        Name
> ```

nit: the mutual exclusion between these two fields is kind of strange. Would it be more natural to express like the following? 
```
type ShowRegions struct {
        FromDatabase  bool
	DatabaseName  Name
}
```
This would simplify the `if n.Database != "" || n.CurrentDatabase {` disjunction in `delegateShowRegions`.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57106)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @nvanbenschoten)

___
*[pkg/sql/delegate/show_regions.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57106#-MN0CwiVDxPe-0Tk58W5:-MN0ZLvZD7bGHeBPt16C:b-62ghhg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fcd50c4536e6fdc2c6592eaf577e0e7fe594221/pkg/sql/delegate/show_regions.go#L56)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we want `SHOW REGIONS FROM DATABASE` to be impacted by the available nodes in the database? I thought we decided that we didn't?

I guess the idea is that we want to show the zones associated with each database region but the zones themselves aren't a static property of the database. This is nice, but we should also make sure that it doesn't lead to one of a database's regions disappearing when all nodes in the region are decommissioned. Maybe that just means that we should use a LEFT JOIN below and coalesce `zones_table.zones` with an empty array.
</blockquote></details>

ah yeah, LEFT JOIN works for me! nice catch

**Review by nvb — APPROVED** [review]
:lgtm: but let's give @ajstorm a chance to take a look as well.

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57106#-:-MN0gXzRDK4i7jzhVX5B:b-n6xcqd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm)

**Review by ajstorm — APPROVED** [review]
:lgtm:  too.  One very minor nit below.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57106#-:-MN3sxsI7xtlfWxfJe-i:b-vhi5yk)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/delegate/show_regions.go, line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57106#-MN3qsNR4MBP-VZzCG7D:-MN3qsNS3rP7sIFjezB1:b-e82gio) ([raw file](https://github.com/cockroachdb/cockroach/blob/8508d65d623b29d68f8db546a4523b8f99971379/pkg/sql/delegate/show_regions.go#L60)):*
> ```Go
> 	r.region as "region",
> 	r.region = r.primary_region AS "primary",
> 	COALESCE(zones_table.zones, '{}'::string[])
> ```

Nit: Might make more sense to move this COALESCE up to the zones_table select statement.  Seems weird that we've got a multi-parameter COALESCE up there and another one down here to clean things up.

**Comment by otan** [comment]
___
*[pkg/sql/delegate/show_regions.go, line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57106#-MN3qsNR4MBP-VZzCG7D:-MN5CsYm8yXkWj9zIfBc:bg6yop9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8508d65d623b29d68f8db546a4523b8f99971379/pkg/sql/delegate/show_regions.go#L60)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Nit: Might make more sense to move this COALESCE up to the zones_table select statement.  Seems weird that we've got a multi-parameter COALESCE up there and another one down here to clean things up.
</blockquote></details>

i think moving the coalesce up would defeat the point of the left join -- namely, if the zone is not alive on `kv_node_status`, but is set on a database, the zones would display NULL

**Comment by otan** [comment]
as discussed with @ajstorm, we also added an `is_region_active` column that denotes whether the region is alive in kv_node_status. seem useful @nvanbenschoten / @awoods187 ?

**Comment by otan** [comment]
(going to merge for now, can remove later if we decide it's not great)

bors r=ajstorm

**Pull request merged**
