### PR TITLE
row: reduce allocations in kv fetchers

### PR DESCRIPTION
**Pull request by jordanlewis**
Pool allocations of txnKVFetcher and reuse a bunch of slice memory.

Also, remove a pointless closure allocation.

```
name                                           old time/op    new time/op    delta
FlowSetup/vectorize=false/distribute=false-24    14.0µs ± 5%    14.2µs ± 4%    ~     (p=0.243 n=9+10)

name                                           old alloc/op   new alloc/op   delta
FlowSetup/vectorize=false/distribute=false-24    29.8kB ± 0%    29.4kB ± 0%  -1.41%  (p=0.000 n=9+9)

name                                           old allocs/op  new allocs/op  delta
FlowSetup/vectorize=false/distribute=false-24       215 ± 0%       208 ± 0%  -3.26%  (p=0.000 n=10+10)
```

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
@andreimatei is it actually true that `Sender.Send` doesn't keep any of the `BatchRequest` memory after `Send` returns, like its Go doc claims?

This PR (which pools a bunch of request memory for re-use) encounters a data race that indicates that it is not true, but there's also this "race transport" that is in the mix, so not sure what is going on exactly.

```
WARNING: DATA RACE
Write at 0x00c000f6e190 by goroutine 346:
  github.com/cockroachdb/cockroach/pkg/roachpb.(*RequestHeader).SetSpan()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/api.go:508 +0x1b45
  github.com/cockroachdb/cockroach/pkg/sql/row.(*txnKVFetcher).fetch()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/kv_batch_fetcher.go:381 +0x1a0a
  github.com/cockroachdb/cockroach/pkg/sql/row.(*txnKVFetcher).nextBatch()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/kv_batch_fetcher.go:524 +0x328
  github.com/cockroachdb/cockroach/pkg/sql/row.(*KVFetcher).NextKV()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/kv_fetcher.go:115 +0x1fc
  github.com/cockroachdb/cockroach/pkg/sql/row.(*Fetcher).NextKey()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/fetcher.go:672 +0xe4
  github.com/cockroachdb/cockroach/pkg/sql/row.(*Fetcher).StartScanFrom()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/fetcher.go:662 +0x17b
  github.com/cockroachdb/cockroach/pkg/sql/row.(*Fetcher).StartScan()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/fetcher.go:554 +0x213
  github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*tableReader).Start()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/tablereader.go:188 +0x3b5
  github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*hashJoiner).Start()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/hashjoiner.go:162 +0xc2
  github.com/cockroachdb/cockroach/pkg/sql.(*rowSourceToPlanNode).startExec()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/row_source_to_plan_node.go:69 +0x64
  github.com/cockroachdb/cockroach/pkg/sql.startExec.func2()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:506 +0xf5
  github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:119 +0x99
  github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:296 +0x145
  github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:86 +0x104
  github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:194 +0x1c4
  github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitConcrete()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:99 +0xae
  github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:212 +0xa8a
  github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:86 +0x104
  github.com/cockroachdb/cockroach/pkg/sql.walkPlan()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:50 +0x174
  github.com/cockroachdb/cockroach/pkg/sql.startExec()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:509 +0x189
  github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:120 +0x1cd
  github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBase).Run()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:790 +0x8e
  github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Run()
      <autogenerated>:1 +0x57
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:392 +0x445
  github.com/cockroachdb/cockroach/pkg/sql/rowflow.(*rowBasedFlow).Run()
      <autogenerated>:1 +0x84
  github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:382 +0x6d2
  github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:954 +0x290
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:978 +0x83b
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:856 +0xb79
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:622 +0x139b
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:119 +0xf53
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1444 +0x3a7
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1446 +0x198c
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1371 +0x40c
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).initConnEx.func1()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:177 +0x8e

Previous read at 0x00c000f6e190 by goroutine 288:
  reflect.Value.IsNil()
      /usr/local/go/src/reflect/value.go:1084 +0x59e
  encoding/json.encodeByteSlice()
      /usr/local/go/src/encoding/json/encode.go:821 +0x88
  encoding/json.structEncoder.encode()
      /usr/local/go/src/encoding/json/encode.go:759 +0x3c4
  encoding/json.structEncoder.encode-fm()
      /usr/local/go/src/encoding/json/encode.go:730 +0xa4
  encoding/json.structEncoder.encode()
      /usr/local/go/src/encoding/json/encode.go:759 +0x3c4
  encoding/json.structEncoder.encode-fm()
      /usr/local/go/src/encoding/json/encode.go:730 +0xa4
  encoding/json.ptrEncoder.encode()
      /usr/local/go/src/encoding/json/encode.go:915 +0x1c4
  encoding/json.ptrEncoder.encode-fm()
      /usr/local/go/src/encoding/json/encode.go:900 +0x84
  encoding/json.structEncoder.encode()
      /usr/local/go/src/encoding/json/encode.go:759 +0x3c4
  encoding/json.structEncoder.encode-fm()
      /usr/local/go/src/encoding/json/encode.go:730 +0xa4
  encoding/json.ptrEncoder.encode()
      /usr/local/go/src/encoding/json/encode.go:915 +0x1c4
  encoding/json.ptrEncoder.encode-fm()
      /usr/local/go/src/encoding/json/encode.go:900 +0x84
  encoding/json.(*encodeState).reflectValue()
      /usr/local/go/src/encoding/json/encode.go:358 +0x93
  encoding/json.interfaceEncoder()
      /usr/local/go/src/encoding/json/encode.go:714 +0xfb
  encoding/json.structEncoder.encode()
      /usr/local/go/src/encoding/json/encode.go:759 +0x3c4
  encoding/json.structEncoder.encode-fm()
      /usr/local/go/src/encoding/json/encode.go:730 +0xa4
  encoding/json.arrayEncoder.encode()
      /usr/local/go/src/encoding/json/encode.go:886 +0xe4
  encoding/json.arrayEncoder.encode-fm()
      /usr/local/go/src/encoding/json/encode.go:879 +0x84
  encoding/json.sliceEncoder.encode()
      /usr/local/go/src/encoding/json/encode.go:860 +0xde
  encoding/json.sliceEncoder.encode-fm()
      /usr/local/go/src/encoding/json/encode.go:855 +0x84
  encoding/json.structEncoder.encode()
      /usr/local/go/src/encoding/json/encode.go:759 +0x3c4
  encoding/json.structEncoder.encode-fm()
      /usr/local/go/src/encoding/json/encode.go:730 +0xa4
  encoding/json.ptrEncoder.encode()
      /usr/local/go/src/encoding/json/encode.go:915 +0x1c4
  encoding/json.ptrEncoder.encode-fm()
      /usr/local/go/src/encoding/json/encode.go:900 +0x84
  encoding/json.(*encodeState).reflectValue()
      /usr/local/go/src/encoding/json/encode.go:358 +0x93
  encoding/json.(*encodeState).marshal()
      /usr/local/go/src/encoding/json/encode.go:330 +0xd2
  encoding/json.(*Encoder).Encode()
      /usr/local/go/src/encoding/json/stream.go:206 +0xdd
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.GRPCTransportFactory.func1()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/transport_race.go:124 +0x1e4
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:346 +0x169

Goroutine 346 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).initConnEx()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:176 +0x5f7
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).execInternal()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:451 +0x786
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).ExecEx()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:314 +0x154
  github.com/cockroachdb/cockroach/pkg/sqlmigrations.runner.execAsRoot()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sqlmigrations/migrations.go:421 +0x14e
  github.com/cockroachdb/cockroach/pkg/sqlmigrations.retireOldTsPurgeIntervalSettings()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sqlmigrations/migrations.go:1250 +0x177
  github.com/cockroachdb/cockroach/pkg/sqlmigrations.(*Manager).EnsureMigrations()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sqlmigrations/migrations.go:668 +0x100c
  github.com/cockroachdb/cockroach/pkg/server.(*sqlServer).preStart()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/server/server_sql.go:796 +0xe36
  github.com/cockroachdb/cockroach/pkg/server.(*Server).PreStart()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1737 +0x5048
  github.com/cockroachdb/cockroach/pkg/server.(*Server).Start()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1048 +0x50
  github.com/cockroachdb/cockroach/pkg/server.(*TestServer).Start()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/server/testserver.go:410 +0x92
  github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartServer()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:251 +0xbd
  github.com/cockroachdb/cockroach/pkg/sql/row.TestNextRowSingle()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/fetcher_test.go:119 +0x117
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1123 +0x202

Goroutine 288 (running) created at:
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:341 +0x138
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.GRPCTransportFactory()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/transport_race.go:102 +0x2c7
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).sendToReplicas()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1808 +0x4cb
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).sendPartialBatch()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1495 +0x3e9
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).divideAndSendBatchToRanges()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1133 +0x1c3e
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).divideAndSendBatchToRanges()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1127 +0x178
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).Send()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:772 +0x73d
  github.com/cockroachdb/cockroach/pkg/kv.lookupRangeFwdScan()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/kv/range_lookup.go:312 +0x4f4
  github.com/cockroachdb/cockroach/pkg/kv.RangeLookup()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/kv/range_lookup.go:197 +0x9e5
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).RangeLookup()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:448 +0x124
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*RangeDescriptorCache).performRangeLookup()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/range_cache.go:817 +0x232
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*RangeDescriptorCache).tryLookup.func1.1.1()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/range_cache.go:671 +0xb2
  github.com/cockroachdb/cockroach/pkg/util/contextutil.RunWithTimeout()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/contextutil/context.go:140 +0xe2
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*RangeDescriptorCache).tryLookup.func1.1()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/range_cache.go:668 +0x353
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:325 +0x161
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*RangeDescriptorCache).tryLookup.func1()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/range_cache.go:656 +0x157
  github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).doCall()
      /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:128 +0x51
```

**Comment by jordanlewis** [comment]
Oh, my mistake, this exact scenario is discussed in the race transport:

```
// NOTE(andrei): We don't like this transport very much. It's slow, preventing
// us from running clusters with race binaries and, the way it's written, it
// prevents both the client and the server from mutating the BatchRequest. But
// only the server is prohibited (according to the client.Sender interface). In
// fact, we'd like to have the client reuse these requests and mutate them.
// Instead of this transport, we should find other mechanisms ensuring that:
// a) the server doesn't hold on to any memory, and
// b) the server doesn't mutate the request
```

Well, what should we do? I would like to reuse this memory if I can.

**Comment by jordanlewis** [comment]
cc @tbg, seems you understand this race transport well judging by #56899. any thoughts on this?

**Comment by tbg** [comment]
I looked into this a bit and I think we might consider getting rid of this race transport now.

In the past (when the race transport was introduced), DistSender had bad goroutine hygiene and so when a result came out it wasn't unreasonable for it to "leak" a goroutine still sending the same batch to some replica.

I took a quick look and it seems like we're in a much better place now. For example, the main source of concurrency is here:

https://github.com/cockroachdb/cockroach/blob/2900c476442155b0f97cbcf58ea1f799850c13e8/pkg/kv/kvclient/kvcoord/dist_sender.go#L1191-L1196

and also in parallel commits:

https://github.com/cockroachdb/cockroach/blob/2900c476442155b0f97cbcf58ea1f799850c13e8/pkg/kv/kvclient/kvcoord/dist_sender.go#L944-L950

Both of these wait for everything to return before returning a result (or error).

I still think it is possible that there are real data races here in errors on general. For example, a context cancellation error from an RPC and subsequent reuse of the batch might race with some goroutine deep inside of gRPC that hasn't processed the context cancellation yet. It's hard to rule out! Similar things might be true for the heartbeat loop in txnCoordSender (not saying I suspect it, but this is one more place where data from the incoming request is used in a goroutine).

We should probably start by reusing memory only when there weren't any errors. I expect there's little to be gained by trying to reuse on error as well. We should be able to get some more coverage of possible data races here by teaching kvnemesis to aggressively reuse memory and running it under race.

I'd like to hear from @nvanbenschoten too, but I think at this point we could disable the grpc transport (not delete it yet, in case we need to backtrack).

**Review by nvb — COMMENTED** [review]
Like others, I really like the idea of pushing for more on memory re-use around the Sender interface. We've wanted to do this [for a while](https://github.com/cockroachdb/cockroach/pull/30485#pullrequestreview-157637422), but have had limited success (see https://github.com/cockroachdb/cockroach/commit/06c1adf483fbbfcd82b28a6346b62da5b0e5ca0d and later https://github.com/cockroachdb/cockroach/pull/30773).

I don't think we're quite ready for this today, though. The `Sender` interface claims that "the callee is not allowed to hold on to any parts of [the BatchRequest] after it returns from the call", but in practice, this is far too optimistic, and we don't even uphold a more pessimistic version of this claim. To start, I don't know that we're ever going to get to a point where absolutely no memory is retained after a call through the interface. For instance, memory used for `roachpb.Key`s is considered to be immutable and ends up being retained all over the place – from the `lockTable` to errors to reference-counted chunks of the latchManager's copy-on-write btree. Taming the lifetimes of this memory would be no easy task and would likely lead to many defensive mem copies, which would almost certainly negate any savings we get from it.

Ignoring `roachpb.Keys`, the claim gets a lot more reasonable. But unfortunately, I still don't think we're currently in compliance. Off the top of my head, I can think of two violations, both having to do with request memory retained in Raft after a client has been allowed to return. The first is pretty blatant – we hold on to the `*BatchRequest` in the `ProposalData` struct when proposing [async consensus writes](https://github.com/cockroachdb/cockroach/blob/ddee2d4269488a3a351ea2a412135d9ca8d5c701/pkg/kv/kvserver/replica_raft.go#L115). The second is more subtle – we allow a sync consensus write to return as soon as it has achieved consensus, even [before it has been applied to the leaseholder's local state machine](https://github.com/cockroachdb/cockroach/blob/ddee2d4269488a3a351ea2a412135d9ca8d5c701/pkg/kv/kvserver/replica_application_cmd.go#L151). Interestingly, in both of these cases, we do make a copy of the batch _response_ memory, so it shouldn't be too much of a stretch to copy part or all of the batch _request_'s memory as well.

Tobi also brings up good points about memory re-use in the presence of errors. I don't think we should make any claim about ownership when an error is returned, as it's too easy to return eagerly on a context cancellation when other async work is still in flight.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56994#-:-MNRqmEQBjd3j5bkdniX:b-pn5r3u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @nvanbenschoten)

___
*[pkg/sql/row/kv_batch_fetcher.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56994#-MNRpvbk4Y5525dcTStH:-MNRpvbk4Y5525dcTStI:b-8i3q2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b7f3f65036d4cdbd47e8178831ccab691896397/pkg/sql/row/kv_batch_fetcher.go#L202)):*
> ```Go
> 	mon *mon.BytesMonitor,
> ) (txnKVFetcher, error) {
> 	wrapper := sendingTxn{txn: txn}
> ```

Does this really avoid the heap allocation? Doesn't the `sendingTxn` object get forced onto the heap?

An alternative to this would be to allow callers to provide either a `sendFunc` or a `*kv.Txn` and then use whichever was provided down in the one user in `txnKVFetcher.fetch`.

Or we could switch to the real `kv.Sender` interface, which `*kv.Txn` implements.

**Comment by andreimatei** [comment]
One thing we know is that when an RPC goes to a remote node, there's clearly no memory sharing. So if (no part of an) RPC is sent to the local client (e.g. always in multi-tenant cluster), the caller can reuse whatever it wants.
I'd be curious to measure is the impact of avoiding the marshalling - unmarshalling when using the local client. Perhaps it's negligible and we can just always make deep copies of requests.

**Pull request closed without merging**
