### PR TITLE
workload: miscellaneous cleanups to histogram tracking

### PR DESCRIPTION
**Pull request by petermattis**
Removed `HistogramTick.{Ops,LastOps}` due to the following identities:

  `HistogramTick.Ops = HistogramTick.Cumulative.TotalCount()`
  `HistogramTick.Ops-HistogramTick.LastOps = HistogramTick.Hist.TotalCount()`

Removed `HistogramTick.start` by keeping track of the previous tick time in
the `HistogramRegistry.prevTick` map.

Release note: None

### CODE REVIEW

**Comment by danhhz** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[pkg/workload/histogram.go, line 127 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25763#-LD2vWOsE77fwopQXvW_:-LD2vWOsE77fwopQXvWa:b-bjut52) ([raw file](https://github.com/cockroachdb/cockroach/blob/14236e0225a7ac420c563a6e794b022a619adc15/pkg/workload/histogram.go#L127)):*
> ```Go
> 	for _, hist := range registered {
> 		hist.tick(func(numOps int64, h *hdrhistogram.Histogram) {
> 			// TODO(dan): It really seems like we should be able to use
> ```

Seems like I've tried this fix myself and couldn't get the numbers to line up. Was the MergedHistogram stuff you removed indeed the problem as this comment seems to suspect?

---

*[pkg/workload/histogram.go, line 202 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25763#-LD2vSGE1Un6pH03UrRL:-LD2vSGE1Un6pH03UrRM:b-68tc5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/041129b7e9fa979b5bfd466b2930d03bae0286dd/pkg/workload/histogram.go#L202)):*
> ```Go
> 	// Elapsed is the amount of time since the last tick.
> 	Elapsed time.Duration
> 	// Now is the time at which the tick was gathered. It coves the period
> ```

nit: covers

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25763#-:-LD2vi1I67lpqOZful9E:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/workload/histogram.go, line 127 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25763#-LD2vWOsE77fwopQXvW_:-LD2wOaRASxsTwuebdhp:b-rg3dbk) ([raw file](https://github.com/cockroachdb/cockroach/blob/14236e0225a7ac420c563a6e794b022a619adc15/pkg/workload/histogram.go#L127)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Seems like I've tried this fix myself and couldn't get the numbers to line up. Was the MergedHistogram stuff you removed indeed the problem as this comment seems to suspect?
</blockquote></details>

I'm not sure what problem you encountered exactly, though I did do some investigation and added assertions that `numOps` was equal to `TotalCount()`. One thing that initially tripped me up was that `TotalCount()` is reset every time the windowed histogram is rotated. After accounting for that the two values were identical. I also added another assertion (since removed) that `HistogramTick.Ops == HistogramTick.Cumulative.TotalCount()`. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25763)*

**Comment by danhhz** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/workload/histogram.go, line 127 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25763#-LD2vWOsE77fwopQXvW_:-LD2xGL87bSvRxABohze:b-e7ornh) ([raw file](https://github.com/cockroachdb/cockroach/blob/14236e0225a7ac420c563a6e794b022a619adc15/pkg/workload/histogram.go#L127)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm not sure what problem you encountered exactly, though I did do some investigation and added assertions that `numOps` was equal to `TotalCount()`. One thing that initially tripped me up was that `TotalCount()` is reset every time the windowed histogram is rotated. After accounting for that the two values were identical. I also added another assertion (since removed) that `HistogramTick.Ops == HistogramTick.Cumulative.TotalCount()`. 
</blockquote></details>

Oh, maybe the reset on rotation was it, cool. (The issue I was seeing was that I was seeing pretty different numbers in the output when using numOps vs TotalCount)

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25763)*

**Comment by petermattis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/workload/histogram.go, line 127 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25763#-LD2vWOsE77fwopQXvW_:-LD2zR_EACMEPX_YSBPt:b-9i1e0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/14236e0225a7ac420c563a6e794b022a619adc15/pkg/workload/histogram.go#L127)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Oh, maybe the reset on rotation was it, cool. (The issue I was seeing was that I was seeing pretty different numbers in the output when using numOps vs TotalCount)
</blockquote></details>

Yep, the numbers were way off before I accounted for `TotalCount` getting reset. I was reasonably paranoid when making this change. :crossed_fingers: I didn't mess anything up.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25763)*

**Comment by petermattis** [comment]
bors r=danhhz

**Pull request merged**
