### PR TITLE
builtins: add Geography builtins

### LINKED ISSUE #48367: geo/geogfn: implement ST_Area({geography,bool})
Implement `ST_Area` on arguments {geography,bool}, which should follow the [PostGIS implementation](https://postgis.net/docs/ST_Area.html).

For Geography builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geogfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geogfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go).
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output manually. Tests here should just ensure the builtin is linked end to end.
* Ensure the documentation is regenerated by calling `make buildshort`.
* Submit your PR - make sure to follow [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

The following guidance has been issued on implementing this function:

Call S2/GeographicLib Area functions.

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-05-05T06:25:47Z. Changes to titles, body and labels may be overwritten.</sub>

### LINKED ISSUE #48393: geo/geogfn: implement ST_CoveredBy({geography,geography})
Implement `ST_CoveredBy` on arguments {geography,geography}, which should follow the [PostGIS implementation](https://postgis.net/docs/ST_CoveredBy.html).

For Geography builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geogfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geogfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go).
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output manually. Tests here should just ensure the builtin is linked end to end.
* Ensure the documentation is regenerated by calling `make buildshort`.
* Submit your PR - make sure to follow [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-05-05T06:25:47Z. Changes to titles, body and labels may be overwritten.</sub>

### LINKED ISSUE #48394: geo/geogfn: implement ST_Covers({geography,geography})
Implement `ST_Covers` on arguments {geography,geography}, which should follow the [PostGIS implementation](https://postgis.net/docs/ST_Covers.html).

For Geography builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geogfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geogfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go).
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output manually. Tests here should just ensure the builtin is linked end to end.
* Ensure the documentation is regenerated by calling `make buildshort`.
* Submit your PR - make sure to follow [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-05-05T06:25:47Z. Changes to titles, body and labels may be overwritten.</sub>

### LINKED ISSUE #48395: geo/geogfn: implement ST_Distance({geography,geography,bool})
Implement `ST_Distance` on arguments {geography,geography,bool}, which should follow the [PostGIS implementation](https://postgis.net/docs/ST_Distance.html).

For Geography builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geogfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geogfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go).
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output manually. Tests here should just ensure the builtin is linked end to end.
* Ensure the documentation is regenerated by calling `make buildshort`.
* Submit your PR - make sure to follow [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-05-05T06:25:47Z. Changes to titles, body and labels may be overwritten.</sub>

### LINKED ISSUE #48396: geo/geogfn: implement ST_DWithin({geography,geography,float8,bool})
Implement `ST_DWithin` on arguments {geography,geography,float8,bool}, which should follow the [PostGIS implementation](https://postgis.net/docs/ST_DWithin.html).

For Geography builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geogfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geogfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go).
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output manually. Tests here should just ensure the builtin is linked end to end.
* Ensure the documentation is regenerated by calling `make buildshort`.
* Submit your PR - make sure to follow [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-05-05T06:25:47Z. Changes to titles, body and labels may be overwritten.</sub>

### LINKED ISSUE #48399: geo/geogfn: implement ST_Intersects({geography,geography})
Implement `ST_Intersects` on arguments {geography,geography}, which should follow the [PostGIS implementation](https://postgis.net/docs/ST_Intersects.html).

For Geography builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geogfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geogfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go).
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output manually. Tests here should just ensure the builtin is linked end to end.
* Ensure the documentation is regenerated by calling `make buildshort`.
* Submit your PR - make sure to follow [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-05-05T06:25:47Z. Changes to titles, body and labels may be overwritten.</sub>

### LINKED ISSUE #48400: geo/geogfn: implement ST_Length({geography,bool})
Implement `ST_Length` on arguments {geography,bool}, which should follow the [PostGIS implementation](https://postgis.net/docs/ST_Length.html).

For Geography builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geogfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geogfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go).
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output manually. Tests here should just ensure the builtin is linked end to end.
* Ensure the documentation is regenerated by calling `make buildshort`.
* Submit your PR - make sure to follow [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-05-05T06:25:47Z. Changes to titles, body and labels may be overwritten.</sub>

### LINKED ISSUE #48401: geo/geogfn: implement ST_Perimeter({bool,geography})
Implement `ST_Perimeter` on arguments {bool,geography}, which should follow the [PostGIS implementation](https://postgis.net/docs/ST_Perimeter.html).

For Geography builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geogfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geogfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go).
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output manually. Tests here should just ensure the builtin is linked end to end.
* Ensure the documentation is regenerated by calling `make buildshort`.
* Submit your PR - make sure to follow [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-05-05T06:25:47Z. Changes to titles, body and labels may be overwritten.</sub>

### PR DESCRIPTION
**Pull request by otan**
Fruits of labour be released to the public!

Added some more helpers for InfoBuilder to include the source library in
which our calculations are done.

Resolves #48367
Resolves #48393
Resolves #48394
Resolves #48395
Resolves #48396
Resolves #48399
Resolves #48400
Resolves #48401

Release note (sql change): We introduce the following newly implemented
functions that work on GEOGRAPHY types:
* ST_Covers
* ST_CoveredBy
* ST_Intersects
* ST_Distance
* ST_DWithin
* ST_Perimeter
* ST_Area
* ST_Length

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48529)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[docs/generated/sql/functions.md, line 668 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48529#-M6oPkBb46HNwktVq5UG:-M6oPkBb46HNwktVq5UH:b-3pok1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/8488eccb9b0ad6dda6b7121ef3a7725d3618674a/docs/generated/sql/functions.md#L668)):*
> ```Markdown
> <tbody>
> <tr><td><a name="st_area"></a><code>st_area(geography: geography) &rarr; <a href="float.html">float</a></code></td><td><span class="funcdesc"><p>Returns the area of the given geography in meters^2. Uses a spheroid to perform the operation.</p>
> <p>This function utilizes the S2 library for spherical calculations.</p>
> ```

shouldn't this say "utilizes the GeographicLib library for spheroid calculations"?
___
*[docs/generated/sql/functions.md, line 748 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48529#-M6oQJv-3jj9Ej-QGga7:-M6oQJv-3jj9Ej-QGga8:bj6gm5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/8488eccb9b0ad6dda6b7121ef3a7725d3618674a/docs/generated/sql/functions.md#L748)):*
> ```Markdown
> <tr><td><a name="st_dwithin"></a><code>st_dwithin(geography_a: geography, geography_b: geography, distance: <a href="float.html">float</a>) &rarr; <a href="bool.html">bool</a></code></td><td><span class="funcdesc"><p>Returns true if any of geography_a is within distance meters of geography_b. Uses a spheroid to perform the operation.</p>
> <p>The calculations performed are have a precision of 1cm.</p>
> <p>This function utilizes the GeographicLib library for spheroid calculations.</p>
> ```

this should also say that it uses S2 for finding the closest points on the sphere.
___
*[docs/generated/sql/functions.md, line 820 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48529#-M6oQlwS-EiKAPgrKKrO:-M6oQlwS-EiKAPgrKKrP:b-h7o1z8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8488eccb9b0ad6dda6b7121ef3a7725d3618674a/docs/generated/sql/functions.md#L820)):*
> ```Markdown
> </span></td></tr>
> <tr><td><a name="st_length"></a><code>st_length(geography: geography) &rarr; <a href="float.html">float</a></code></td><td><span class="funcdesc"><p>Returns the length of the given geography in meters. Uses a spheroid to perform the operation.</p>
> <p>This function utilizes the S2 library for spherical calculations.</p>
> ```

shouldn't this be "utilizes the GeographicLib library for spheroid calculations"
___
*[docs/generated/sql/functions.md, line 915 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48529#-M6oQqp33ov7wGNoqiqf:-M6oQqp33ov7wGNoqiqg:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/8488eccb9b0ad6dda6b7121ef3a7725d3618674a/docs/generated/sql/functions.md#L915)):*
> ```Markdown
> </span></td></tr>
> <tr><td><a name="st_perimeter"></a><code>st_perimeter(geography: geography) &rarr; <a href="float.html">float</a></code></td><td><span class="funcdesc"><p>Returns the perimeter of the given geography in meters. Uses a spheroid to perform the operation.</p>
> <p>This function utilizes the S2 library for spherical calculations.</p>
> ```

ditto
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48529#-M6oS2Qw9b2WINoMwDk_:-M6oS2Qw9b2WINoMwDka:b-y2zhiu) ([raw file](https://github.com/cockroachdb/cockroach/blob/8488eccb9b0ad6dda6b7121ef3a7725d3618674a/pkg/sql/sem/builtins/geo_builtins.go#L53)):*
> ```
> ib.libraryUsage&usesGEOS
> ```

Does `go fmt` remove the space around the `&`? If not, I'd prefer to have that space since it makes it easier to spot the operator.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48529)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[docs/generated/sql/functions.md, line 668 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48529#-M6oPkBb46HNwktVq5UG:-M6ojaNU8WNbdAlscNOR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8488eccb9b0ad6dda6b7121ef3a7725d3618674a/docs/generated/sql/functions.md#L668)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

shouldn't this say "utilizes the GeographicLib library for spheroid calculations"?
</blockquote></details>

Done.
___
*[docs/generated/sql/functions.md, line 748 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48529#-M6oQJv-3jj9Ej-QGga7:-M6ol5wu8w3DObGeppJo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8488eccb9b0ad6dda6b7121ef3a7725d3618674a/docs/generated/sql/functions.md#L748)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this should also say that it uses S2 for finding the closest points on the sphere.
</blockquote></details>

Done.
___
*[docs/generated/sql/functions.md, line 820 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48529#-M6oQlwS-EiKAPgrKKrO:-M6ojXkC9vmqWPm2xQ65:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8488eccb9b0ad6dda6b7121ef3a7725d3618674a/docs/generated/sql/functions.md#L820)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

shouldn't this be "utilizes the GeographicLib library for spheroid calculations"
</blockquote></details>

Done.
___
*[docs/generated/sql/functions.md, line 915 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48529#-M6oQqp33ov7wGNoqiqf:-M6ojYjo4sH6uLgvyCpU:b5u0s93) ([raw file](https://github.com/cockroachdb/cockroach/blob/8488eccb9b0ad6dda6b7121ef3a7725d3618674a/docs/generated/sql/functions.md#L915)):*
> Done.
Done.
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48529#-M6oS2Qw9b2WINoMwDk_:-M6oit9bA4fiTgl4fRBD:b68xopi) ([raw file](https://github.com/cockroachdb/cockroach/blob/8488eccb9b0ad6dda6b7121ef3a7725d3618674a/pkg/sql/sem/builtins/geo_builtins.go#L53)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> ```
> ib.libraryUsage&usesGEOS
> ```

Does `go fmt` remove the space around the `&`? If not, I'd prefer to have that space since it makes it easier to spot the operator.
</blockquote></details>

yeah this is a gofmt thing.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48529#-:-M78iIwS-Z5WJm4EbLd1:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/sql/sem/builtins/geo_builtins.go, line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48529#-M78i3X1COqGcrgkS13h:-M78i3X1COqGcrgkS13i:b-y1xil9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bd92dc3e122ee758d4f6e859d07b4422c04fd14/pkg/sql/sem/builtins/geo_builtins.go#L38)):*
> ```Go
> const usesSpheroidMessage = " Uses a spheroid to perform the operation."
> const spheroidDistanceMessage = `"\n\nWhen operating on a spheroid, this function will use the sphere to calculate ` +
> 	`the closest two points using S2. The spheroid distance is calculated of these two points using GeographicLib. ` +
> ```

nit: The spheroid distance between these two points is calculated using GeographicLib

(simpler sentence structure)

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48529)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @sumeerbhola)

___
*[pkg/sql/sem/builtins/geo_builtins.go, line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48529#-M78i3X1COqGcrgkS13h:-M7AtOg9A17aOR716fo3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bd92dc3e122ee758d4f6e859d07b4422c04fd14/pkg/sql/sem/builtins/geo_builtins.go#L38)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: The spheroid distance between these two points is calculated using GeographicLib

(simpler sentence structure)
</blockquote></details>

Done.

**Comment by otan** [comment]
bors r=sumeerbhola

**Comment by otan** [comment]
bors r=sumeerbhola

**Pull request merged**
