### PR TITLE
colexec: handle panics in Init gracefully by the materializer

### LINKED ISSUE #61588: roachtest: sqlsmith nil context
[(roachtest).sqlsmith/setup=rand-tables/setting=no-mutations failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2751365&tab=buildLog) on [master@15a185606d5e80b47d9fdd0ed4f54cfe29c527c6](https://github.com/cockroachdb/cockroach/commits/15a185606d5e80b47d9fdd0ed4f54cfe29c527c6):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/sqlsmith/setup=rand-tables/setting=no-mutations/run_1
	cluster.go:1667,context.go:140,cluster.go:1656,test_runner.go:848: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-2751365-1615015616-07-n4cpu4 --oneshot --ignore-empty-nodes: exit status 1 1: 7036
		3: 6447
		4: dead
		2: dead
		Error: UNCLASSIFIED_PROBLEM: 4: dead
		(1) UNCLASSIFIED_PROBLEM
		Wraps: (2) secondary error attachment
		  | 2: dead
		  | (1) attached stack trace
		  |   -- stack trace:
		  |   | main.glob..func14
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1147
		  |   | main.wrap.func1
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:271
		  |   | github.com/spf13/cobra.(*Command).execute
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:830
		  |   | github.com/spf13/cobra.(*Command).ExecuteC
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:914
		  |   | github.com/spf13/cobra.(*Command).Execute
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:864
		  |   | main.main
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1852
		  |   | runtime.main
		  |   | 	/usr/local/go/src/runtime/proc.go:204
		  |   | runtime.goexit
		  |   | 	/usr/local/go/src/runtime/asm_amd64.s:1374
		  | Wraps: (2) 2: dead
		  | Error types: (1) *withstack.withStack (2) *errutil.leafError
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | main.glob..func14
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1147
		  | main.wrap.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:271
		  | github.com/spf13/cobra.(*Command).execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:830
		  | github.com/spf13/cobra.(*Command).ExecuteC
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:914
		  | github.com/spf13/cobra.(*Command).Execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:864
		  | main.main
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1852
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:204
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1374
		Wraps: (4) 4: dead
		Error types: (1) errors.Unclassified (2) *secondary.withSecondaryError (3) *withstack.withStack (4) *errutil.leafError

```

<details><summary>More</summary><p>

Artifacts: [/sqlsmith/setup=rand-tables/setting=no-mutations](https://teamcity.cockroachdb.com/viewLog.html?buildId=2751365&tab=artifacts#/sqlsmith/setup=rand-tables/setting=no-mutations)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Asqlsmith%2Fsetup%3Drand-tables%2Fsetting%3Dno-mutations.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #62061: roachtest: sqlsmith/setup=rand-tables/setting=no-ddl failed
[(roachtest).sqlsmith/setup=rand-tables/setting=no-ddl failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2780761&tab=buildLog) on [release-21.1@4a47e0e305cbdabf963f896c1cb571a28b34e63d](https://github.com/cockroachdb/cockroach/commits/4a47e0e305cbdabf963f896c1cb571a28b34e63d):

```
The test failed on branch=release-21.1, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/sqlsmith/setup=rand-tables/setting=no-ddl/run_1
	cluster.go:1667,context.go:140,cluster.go:1656,test_runner.go:848: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-2780761-1615874220-04-n4cpu4 --oneshot --ignore-empty-nodes: exit status 1 3: 5657
		2: 5813
		1: 6406
		4: dead
		Error: UNCLASSIFIED_PROBLEM: 4: dead
		(1) UNCLASSIFIED_PROBLEM
		Wraps: (2) attached stack trace
		  -- stack trace:
		  | main.glob..func14
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1147
		  | main.wrap.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:271
		  | github.com/spf13/cobra.(*Command).execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:830
		  | github.com/spf13/cobra.(*Command).ExecuteC
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:914
		  | github.com/spf13/cobra.(*Command).Execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:864
		  | main.main
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1852
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:204
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1374
		Wraps: (3) 4: dead
		Error types: (1) errors.Unclassified (2) *withstack.withStack (3) *errutil.leafError

```

<details><summary>More</summary><p>

Artifacts: [/sqlsmith/setup=rand-tables/setting=no-ddl](https://teamcity.cockroachdb.com/viewLog.html?buildId=2780761&tab=artifacts#/sqlsmith/setup=rand-tables/setting=no-ddl)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Asqlsmith%2Fsetup%3Drand-tables%2Fsetting%3Dno-ddl.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by yuzefovich**
**colbuilder: pass metadata sources to materializers when wrapping procs**

Throughout the vectorized flows we have several components that are
responsible for draining the metadata sources: root materializer,
outboxes, hash routers, and input synchronizers. However, there is
another case which could easily support - the materializers created when
wrapping row-execution processors, and this commit adds the
corresponding plumbing.

To provide the motivation behind this change, consider the following
plan:
```
└ *colexec.Materializer (1)
  └ *colflow.panicInjector
    └ *colexec.Columnarizer
      └ *rowexec.joinReader
        └ *colexec.Materializer (2)
          └ *colflow.panicInjector (3)
            └ *colexec.limitOp
              └ *colexecbase.simpleProjectOp
                └ *colexecutils.CancelChecker
                  └ *colfetcher.ColBatchScan
```
In this plan we have 2 metadata sources: `ColBatchScan` and `Columnarizer`.
Previously, we would accumulate both and pass them to the root
materializer (1). Now imagine that `panicInjector (3)` emits a panic in
`Init`. It will be caught by the materializer (2) which will proceed to
draining; however, from the perspective of the root materializer (1) the
execution of the flow is successful and it will attempt to drain both
sources. The ColBatchScan is uninitialized, so when draining it, we
would be breaking the assumption that `Init` is called before
`DrainMeta`. With this change we pass the responsibility of draining of
ColBatchScan to the materializer (2) while leaving the root materializer
(1) responsible for draining the columnarizer. Such setup makes more
sense in general, but also it paves the way for follow-up commit to
handle panics in `Init` by the materializers gracefully.

Release note: None

**colexec: handle panics in Init gracefully by the materializer**

The materializer wraps the call to `Init` on its input with
a panic-catcher. Previously, if an error is encountered, the
materializer would transition into draining state which would later
drain all of the metadata sources given to it in the constructor.
However, because of a panic in `Init`, those sources might have not been
properly initialized, so draining them might be an unsafe operation.
Instead, we want the materializer to return the error it caught and shut
down the flow. We can achieve this by tweaking the drain helper a bit so
that it drains the inputs only if no error was encountered by the
materializer.

Fixes: #61588.
Fixes: #62061.

Release note: None (no stable release with the bug that could lead to
crashes because of this issue)

### CODE REVIEW

**Review by asubiotto — APPROVED** [review]
I'm not sure I fully understand the motivation for the first commit, but I don't think it's a bad thing. If we fixed the `Init` thing, materializer (1) will would've returned the panic error in materializer (2) as metadata, right?

:lgtm: 

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62126#-:-MW-uh0n-_y-hd5gD7v3:bkzbpv6)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
I adjusted the first commit to separate out metadata sources from different inputs (when there are 2 inputs like for joins). PTAL.

With the second commit in isolation, when I ran the binary with testing assertions enabled, I still saw `DrainMeta` being called when `Init` wasn't, so I added the first commit.

> If we fixed the `Init` thing, materializer (1) will would've returned the panic error in materializer (2) as metadata, right?

Yes, exactly. That panic error is the only metadata produced by all of the tree nodes below `materializer (2)`.

**Comment by yuzefovich** [comment]
Ok, RFAL (I was fighting some bazel issues).

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62126#-:-MW54TiW1SFEpweFl5OO:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
Seems like an unrelated flake.

bors r+

**Comment by yuzefovich** [comment]
Seems like another flake.

bors r+

**Pull request merged**
