### PR TITLE
lint: enable MapToBool linter

### PR DESCRIPTION
**Pull request by yuzefovich**
This PR replaces `map[...]bool` with `map[...]struct{}` where
possible since the latter is more efficient. The corresponding linter is
now enabled on almost the whole codebase.

Release justification: low-risk improvement.

Release note: None

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: Thanks for doing this!

> Reviewed 1 of 1 files at r1, 13 of 13 files at r2, 9 of 9 files at r3, 10 of 10 files at r4, 3 of 3 files at r5, 5 of 5 files at r6, 4 of 4 files at r7, 24 of 24 files at r8, 7 of 7 files at r9, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86467#-:-NABQWDs7RoShqA0gUd5:b-pt8m11)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
Thanks for the review Marcus!

----

For folks who have been notified by this PR.

It enables a recently introduced MapToBool [linter](#85689) which prohibits the usage of `map[...]bool` in favor of `map[...]struct{}` (since the latter is more efficient) on almost the whole codebase. All the changes in this PR are mechanical. The replacement is not equivalent in cases when both `false` and `true` values want to be used (rather than simply whether a key is present in the map), so those cases are excluded from the linter. Some might argue that using the `bool` value is more readable, but on SQL Queries we decided it wasn't a big issue and using `map[...]struct{}` is a more natural way of implementing a "set" in Go. If anyone disagrees, please share your concerns and comments. If there are no objections, I'll merge this tomorrow.

**Review by michae2 — APPROVED** [review]
:lgtm:

> Reviewed 11 of 13 files at r2, 2 of 61 files at r11, 9 of 10 files at r12, 10 of 11 files at r13, 3 of 4 files at r14, 5 of 6 files at r15, 4 of 5 files at r16, 24 of 25 files at r17, 7 of 8 files at r18, 4 of 5 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86467#-:-NAGgVaD57q8k74IoiDH:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @dt, @herkolategan, and @mgartner)

**Review by renatolabs — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86467#-:-NAHHxHt1Z0m8A_x16zI:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @dt, @herkolategan, and @mgartner)

**Review by herkolategan — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r19.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86467#-:-NAJACz_6JH40peiQM-d:bnfp4nl)* status: :shipit: complete! 3 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @dt)

**Review by herkolategan — APPROVED** [review]
> Reviewed 11 of 13 files at r2, 61 of 61 files at r11, 10 of 10 files at r12, 11 of 11 files at r13, 4 of 4 files at r14, 6 of 6 files at r15, 5 of 5 files at r16, 25 of 25 files at r17, 8 of 8 files at r18, 4 of 5 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86467)* status: :shipit: complete! 3 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @dt)

**Comment by andreimatei** [comment]
> Some might argue that using the bool value is more readable, but on SQL Queries we decided it wasn't a big issue and using map[...]struct{} is a more natural way of implementing a "set" in Go. If anyone disagrees, please share your concerns and comments. If there are no objections, I'll merge this tomorrow.

The bool version lets you test for presence in the set in a broader expression. With the `struct{}` version, you need to use the two-return-value indexing operation, which is more awkward to use in an expression - it can only be used in the variable-declaration part of statements.
How much more efficient is the `struct{}`?

**Comment by yuzefovich** [comment]
> How much more efficient is the `struct{}`?

The linter was prompted by [this article](https://www.ribice.ba/golang-memory-savings/), and they are claiming that "writes were 3.2% faster and 10% less memory was allocated using the empty struct map".

**Comment by andreimatei** [comment]
In my opinion, these numbers are very far from justifying imposing a coding preference on all crdb authors.
Let's hope that in the future we'll get a generic set, making this discussion moot.

**Comment by yuzefovich** [comment]
There is another argument in favor of using `struct{}` when you want a "set" behavior - if you have `m := map[...]bool` and do `if present := m[key]; present { ...`, if the `key` is not present in `m`, then it works due to an implicit behavior that the default value of `bool` is `false`. Personally, I find this behavior [confusing](https://cockroachlabs.slack.com/archives/C9TGBJB44/p1660927839043609).

Generally speaking, I believe Go is designed in such a way that the smaller number of ways there are to do something, the better; in this case, I'm arguing that `map[...]struct{}` is _the_ Go way of implementing sets right now, so it should be favored. At the same time, the linter does provide an escape hatch when 1. you do need "three values" behavior (since determining this would require making the linter much more sophisticated), and 2. you insist on using a map to bool for the set behavior (for personal aesthetics reasons).

**Comment by andreimatei** [comment]
I think there should be a very high bar for introducing a new linter. Linters always have unintended consequences. And also, it's a very bold statement to say "I know better than the programmer", it shouldn't be done lightly.
In my opinion, "I found this code to be confusing, therefore nobody should write code like this" is rarely a defensible statement. If we all start introducing blanket disallowing of patters we don't like, this will quickly become a codebase in which it's unbearable to work.
Consider adding recommendations to the style guide, rather than a linter barking at people. And ultimately err on trusting the programmer.

> if you have m := map[...]bool and do if present := m[key]; present { ..., if the key is not present in m, then it works due to an implicit behavior that the default value of bool is false. Personally, I find this behavior [confusing](https://cockroachlabs.slack.com/archives/C9TGBJB44/p1660927839043609).

A map returning the zero value for missing keys is a well-known go thing. I think the code you point to is indeed confusing, but not exactly because of how the set was implemented, but more because it was maintaining the inverse set from what it really wanted. Your fix to the code was not to change the details of the set implementation, but to change the meaning of the set. So I wouldn't use this particular example for your case.

**Comment by mgartner** [comment]
> I think there should be a very high bar for introducing a new linter. Linters always have unintended consequences. And also, it's a very bold statement to say "I know better than the programmer", it shouldn't be done lightly.
In my opinion, "I found this code to be confusing, therefore nobody should write code like this" is rarely a defensible statement. If we all start introducing blanket disallowing of patters we don't like, this will quickly become a codebase in which it's unbearable to work.
Consider adding recommendations to the style guide, rather than a linter barking at people. And ultimately err on trusting the programmer.

The number of mis-typed maps in this PR are already proof that the linter succeeds when a human programmer and reviewer, limited with a finite attention span, have failed (albeit without a style guide entry). Do you have examples of unintended consequences that new linters cause?

**Review by andreimatei — COMMENTED** [review]
> The number of mis-typed maps in this PR are already proof that the linter succeeds when a human programmer and reviewer, limited with a finite attention span, have failed (albeit without a style guide entry). 

Where can I look to see an example of something bad that this linter caught? A comment says "All the changes in this PR are mechanical". So, what exactly do you mean by "mis-typed"?

> Do you have examples of unintended consequences that new linters cause?

The last example that comes to mind was the recent linter that disallowed loop variable capture by other goroutines. It happened to also flag captures by anonymous functions that ran on the same goroutine as the loop. 
It has happened to me over and over for my code to be flagged by some linter for a reason I don't quite understand. I then need to see why other seemingly similar code is not flagged. I then have to figure out the easiest work-around (or contemplate quitting, which I do every time). Linters are either very dumb, in which case they get in the way of fine code, or they try to be smart but fail, at which point you have to be extra smart to understand when it fires and when it doesn't.

Perhaps this linter is so simple that it's consequences are clear - I guess it has a blanket disallow for `map[T]bool`. A comment about an "escape hatch" misled me into thinking that it tries to be smart and look at whether the bool values are used or something. Such a blanket disallow is preposterous, in my opinion. You may want to map to a `bool`; it's not a rare thing. I shouldn't have to add some pragma to get my map.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86467#-:-NAfDW-p15mC94qM16c9:b-pb3ww1)* status: :shipit: complete! 3 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @dt)

**Comment by mgartner** [comment]
> So, what exactly do you mean by "mis-typed"?

By mis-typed I mean that the map had the wrong type - it should have been `map[T]struct{}` instead of `map[T]bool`. You could argue that `map[T]bool` isn't wrong in those cases because it works fine. Although with that reasoning, `map[T]Elephant` would also be acceptable.

> You may want to map to a bool; it's not a rare thing. I shouldn't have to add some pragma to get my map.

The number of `//nolint:maptobool`s added in the PR prove it is indeed not so rare. If the sentiment toward this linter is that it doesn't provide enough value to offset the extra effort to add `//nolint:maptobool` when necessary, then it's not something we should impose on the whole codebase.

**Comment by andreimatei** [comment]
> By mis-typed I mean that the map had the wrong type - it should have been map[T]struct{} instead of map[T]bool. You could argue that map[T]bool isn't wrong in those cases because it works fine. Although with that reasoning, map[T]Elephant would also be acceptable.

In a previous message I gave some thoughts about why `map[T]bool` can be more ergonomic than `map[T]struct` at times. And also more ergonomic than `map[T]Elephant`. `bool` is special because it can be used naturally in expressions. So `map[T]Elephant` is generally not acceptable (but please don't go write a linter against it).

> The bool version lets you test for presence in the set in a broader expression. With the struct{} version, you need to use the two-return-value indexing operation, which is more awkward to use in an expression - it can only be used in the variable-declaration part of statements.

Also, keep in mind that the status quo is bound to change with the advent of generics. We'll surely get a proper set implementation before too long; let's just continue to wait for that. At that point, someone will write a linter prohibiting `map[T]struct{}` that I'll have to fight against.

**Comment by postamar** [comment]
I completely agree with @andreimatei on all points. This strikes me as heavy-handed, which quite honestly would be fine if there existed a good performance justification, but until we run some semblance of a benchmark there isn't any.

One has to be very, very careful with taking claims like "we saw a speed-up" at face value, even if the claimant's good faith is absolutely not in question.

To be clear, I'm not against this, I don't care enough even though I'm one of those `map[...]bool` people. I'm using this as an opportunity to caution against changes made for performance reasons at the expense of code legibility which aren't supported by actual data.

**Comment by srosenberg** [comment]
Like @postamar , I don't have a stylistic preference. As much as I cringe at `struct{}{}`, if it does indeed offer a significant memory or cpu advantage, I'm ok with the ugly syntax. In fact, it seems that both styles might be sufficiently idiomatic.

Both @andreimatei  and @andreimatei raise valid points regarding ergonomics. Firstly, we want to ensure that a new linter doesn't have a negative impact in terms of (a) false positives, (b) running time. Neither seems to be the issue with this linter. Secondly, we want to ensure that a new linter provides a "substantial" lift. This part is often _subjective_. Therefore, I would implore everyone to be as objective as possible. Let's also be respectful of both the user and the implementer. Bad linters can harm users but so is the lack of good linters.

With respect to the stylist choice, there isn't an authority as far as I understand. E.g., from the "Go Programming Language" [1],

map_empt_struct

With respect to space saving, it appears to be negligible [2] ,

> On a 64-bit system, a map[string]struct{} bucket is 144 bytes and a map[string]bool bucket is 152 bytes. So on a 32-bit system you'd save 9.5% of the bucket footprint, and on a 64-bit system you'd save 5.3%. It's not a lot, especially compared to the fact that the implementation tries to keep the map buckets at most 81.25% full. The savings from bool->struct{} are mostly noise.

Could we run all of our existing microbenches before and after this change? If the cpu speed up is non-negligible, perhaps we have a tie-breaker.

[1] Donovan, Alan AA, and Brian W. Kernighan. The Go programming language. Addison-Wesley Professional, 2015.
[2] https://groups.google.com/g/golang-nuts/c/_qilWYJS81Y/m/yxC-cjH3DgAJ

**Comment by yuzefovich** [comment]
> I guess it has a blanket disallow for `map[T]bool`

Indeed, that's the case.

> Could we run all of our existing microbenches before and after this change? If the cpu speed up is non-negligible, perhaps we have a tie-breaker.

I don't think any of the maps that are being replaced as part of this PR are on the hot path so that they would meaningfully show up on some micro-benchmarks. As I mentioned [earlier](https://github.com/cockroachdb/cockroach/pull/86467#issuecomment-1227469302), in isolation "writes were 3.2% faster and 10% less memory was allocated using the empty struct map", but this difference is likely to be just a noise on all of our existing micro- and macro-benchmarks.

----

I see arguments for both sides of the question (of whether this linter should be enabled on the whole codebase), but it seems that the "against" camp's opinion is stronger, especially so given the absence of noticeable perf improvement. I'm ok with not enforcing this linter on the whole codebase, so I'll close this PR. At the same time, several folks on my team seemed happy to merge it, so I think we'll consider enforcing it only on the part of the codebase that we own.

Thanks everyone for the input!

**Pull request closed without merging**
