### PR TITLE
backupccl: allow restoration of empty db

### LINKED ISSUE #41962: Can not restore empty database (but backup works)
**Describe the problem**

Currently, our enterprise backup will backup an empty database to an s3 bucket, but will run into an error when trying to restore.

For example if you backup defaultdb: 
```
pq: no tables found: DATABASE defaultdb
```

this presents a problem for those running a script that runs a show databases command and then backs up all of them, and at a certain point in time then restores all of those backed up.

As we are aware, the backup/restore works on a database level so one can cherry-pick those that they know are not empty, but this is not a strong solution. Setting up exclusions for `defaultdb` and `postgres` databases will also not suffice as we've seen a use case from one of our customers where there are multiple other user-created databases that are just left empty.

**To Reproduce**

Try to backup an empty database to s3 and then restore it. 

**Expected behavior**
potentially an empty database to be created and the script running this not to halt.

**Additional context**
Client restore script is halting.

### PR DESCRIPTION
**Pull request by pbardea**
Previously, RESTORE did not support restoring empty databases. However,
there are use cases in which scripts perform the backup and restore
process and they have run into issues since when they go to RESTORE all
of their databases, if any are empty the script will fail.

Since BACKUP supports the backing up of empty databases, it makes sense
to allow RESTORE to restore those databases that were backed up.

Fixes #41962.

Release note (enterprise change): RESTORE now supports the restoration
of empty databases.

### CODE REVIEW

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42005)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @pbardea)

___
*[pkg/ccl/backupccl/restore.go, line 1746 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42005#-LsOH87T2-KJhUczwEN3:-LsOH87T2-KJhUczwEN4:b-udodvx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9d0b5292492d41fe25c4d155dd38fca566466db/pkg/ccl/backupccl/restore.go#L1746)):*
> ```Go
> 		// Since we have already created any new databases that we needed,
> 		// we can return without importing any data.
> 		return nil
> ```

I think we should log a warning in this case.

**Comment by pbardea** [comment]
@lucy-zhang whoops. this fell off my radar. RFAL.

**Review by thoszhang — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42005)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

**Comment by lucy-zhang** [comment]
This will be backported to 19.2, right?

**Comment by pbardea** [comment]
TFTR! bors r+

**Pull request merged**
