### PR TITLE
roachtest: add acceptance/gossip/*

### LINKED ISSUE #29115: gossip: rework and improve gossip acceptance tests as roachtests
`TestGossipPeerings`, `TestGossipRestart`, and `TestGossipRestartFirstNodeNeedsIncoming` overlap what they test with the new `gossip/nodes=9` roachtest. These gossip acceptance tests are automatically suspect in what they test because they haven't caught any of the recent gossip problems (i.e. gossip partitions). Part of the reason is that they have a simplistic criteria for success: that connecting to the gossip cluster allows a node to see all of the expected `node:*` keys, but those keys have a 2h TTL. The new `gossip-clients:*` keys and the gossip connectivity map more directly show the effect of a gossip partition, but that is already tested by `gossip/nodes=9`. We need to go through the gossip acceptance tests and migrate any other useful test scenarios to the gossip roachtest.

### PR DESCRIPTION
**Pull request by petermattis**
Move the gossip acceptance tests to roachtests.

See #29151
Fixes #29115

### CODE REVIEW

**Comment by petermattis** [comment]
The first 7 commits are #29449.

**Comment by petermattis** [comment]
@benesch The last commit fixes a deterministic failure in `acceptance/cli/node-status` caused when I switched the acceptance tests to use a 4-node cluster. Every merge-to-master CI run will fail (and so will bleeding edge). If you want, I can pull that commit out into a separate PR. Or just give this whole PR an LGTM. (Feel free to bors this PR. Not sure if I'll be back online tonight.)

**Review by benesch — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 4 of 4 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29465)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by benesch** [comment]
Nope, definitely don't bother pulling that out! I'll bors this right up. OOC how did you manage to land that breaking change in the first place?

bors r+

**Comment by petermattis** [comment]
> Nope, definitely don't bother pulling that out! I'll bors this right up. OOC how did you manage to land that breaking change in the first place?

We don't appear to run these tests in CI until after they are merged to master. Seems like the bors CI run should run them as well.

**Comment by benesch** [comment]
Oh, that is problematic. Changed it so that they're run on everything: PRs,
bors runs, and merge to master.

**Pull request merged**
