### PR TITLE
go.mod: bump Pebble to a80169845786

### PR DESCRIPTION
**Pull request by jbowens**
```
a8016984 internal/keyspan: modify FragmentIterator seek semantics
e0c46386 db: fix lazy-combined iteration bug
dadb7bd9 metamorphic: vary UseL6Filters for iterators
53ce2f93 metamorphic: randomize bloom filter setting b9d2fce1 .github: use Go 1.19
1aefe7fe db: Qualify fatal commit error message
8944925a *: apply Go 1.19 gofmt
e35292f9 internal/manifest: fix out-of-bounds b-tree access
fd755a68 bloom: reduce memory allocations in table bloom filter
e2fd5daa bloom: add a table bloom filter benchmark
65ff304d sstable: skip two known test flakes on windows
bc6b7180 internal/manifest: add invariant checks for exhausted LevelIterator
32daf1c5 internal/manifest: refactor LevelIterator key type filtering
3a2a79f9 *: prettify maximal sequence number as #inf
bec1aa20 replay: fix data race
1941c9fb sstable: use bytealloc.A in reader, writer, suffix rewriter
```

Epic: None
Release note: None

### CODE REVIEW

**Review by nicktrav — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95000#-:-NLRG1RyEGafgUKpTLvu:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Review by rickystewart — APPROVED** [review]

**Comment by jbowens** [comment]
TFTRs!

bors r+

**Comment by jbowens** [comment]
bors retry

**Comment by rail** [comment]
bors r-
We have temporarily disabled bors for merges. Please merge the PR manually when all required checks pass.

**Pull request merged**
