### PR TITLE
release-21.1: roachprod: improve the way cockroach is run

### PR DESCRIPTION
**Pull request by tbg**
To be merged only post-21.1.0.

Closes https://github.com/cockroachdb/cockroach/issues/64967.

----

Backport:
  * 1/1 commits from "roachprod: improve the way cockroach is run" (#64177)
  * 1/1 commits from "roachprod: upgrade AWS VM" (#64436)
  * 1/1 commits from "install: fix limits for cockroach process" (#64560)

Please see individual PRs for details.

/cc @cockroachdb/release

### CODE REVIEW

**Comment by tbg** [comment]
@RaduBerinde @nvanbenschoten @andreimatei are we are with any problems caused by the systemd setup? I would like to merge this next week after spot checking the health of the `master` runs again (it's been quiet... maybe too quiet).

**Comment by RaduBerinde** [comment]
I'm not aware of any new problems.

**Comment by nvanbenschoten** [comment]
Neither am I.

**Review by otan — APPROVED** [review]

**Review by RaduBerinde — APPROVED** [review]

**Comment by tbg** [comment]
YOLO it is then. I'll keep an eye out.

**Pull request merged**
