### PR TITLE
storage: include range and lease counts in snapshot responses

### PR DESCRIPTION
**Pull request by tamird**
@spencerkimball @petermattis I went down the rabbit hole, so here it is.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/11690)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11690#-:-KXlbFk_IFjonCP7vmZt:bnfp4nl)*

**Comment by spencerkimball** [comment]
@petermattis this is a flawed mechanism. It doesn't account for splits adding ranges or lease rebalancings. It doesn't spread the new capacity numbers to other interested nodes. It doesn't solve the problem of needing a very tight gossip interval, which is expensive to compute and busy to send for large clusters. Further, when I start a local cluster with this snapshot response "fixed", it doesn't actually fix it, because rebalancings are still busy and take too long to find equilibrium.

**Comment by petermattis** [comment]
> this is a flawed mechanism.

Perhaps, but this is the mechanism that was previously present and then broken. Fixing the brokenness seems worthwhile. On the other hand, I don't particularly want to merge this until #11591 is fixed because I think this PR will hide the problem seen there.

**Comment by bdarnell** [comment]
LGTM

**Pull request closed without merging**
