### PR TITLE
coldata: fix Bytes invariant in some cases

### LINKED ISSUE #57297: colexec: v20.2.2: index out of bounds when Getting from Bytes vector
This issue was autofiled by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry link: https://sentry.io/organizations/cockroach-labs/issues/2066108371/?referrer=webhooks_plugin

Panic message:

>error.go:90: unexpected error from the vectorized engine: ×
--
*barriers.barrierError
*errutil.withPrefix: unexpected error from the vectorized engine (1)
error.go:90: *withstack.withStack (top exception)
*assert.withAssertionFailure
*contexttags.withContext: n2 (2)
*contexttags.withContext: n1 (3)
*colexecerror.notInternalError
inbox.go:248: *withstack.withStack (4)
(check the extra data payloads)

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

https://github.com/cockroachdb/cockroach/blob/92d94952060fd24400906dc06e392d7a7419b392/pkg/sql/colflow/colrpc/inbox.go#L247-L249 in pkg/sql/colflow/colrpc.(*Inbox).Next.func1
/usr/local/go/src/runtime/panic.go#L678-L680 in runtime.gopanic
https://github.com/cockroachdb/cockroach/blob/92d94952060fd24400906dc06e392d7a7419b392/pkg/sql/colexecbase/colexecerror/error.go#L185-L187 in pkg/sql/colexecbase/colexecerror.ExpectedError
https://github.com/cockroachdb/cockroach/blob/92d94952060fd24400906dc06e392d7a7419b392/pkg/sql/colflow/colrpc/inbox.go#L288-L290 in pkg/sql/colflow/colrpc.(*Inbox).Next
https://github.com/cockroachdb/cockroach/blob/92d94952060fd24400906dc06e392d7a7419b392/pkg/sql/colexec/operator.go#L237-L239 in pkg/sql/colexec.(*noopOperator).Next
https://github.com/cockroachdb/cockroach/blob/92d94952060fd24400906dc06e392d7a7419b392/pkg/sql/colexec/materializer.go#L221-L223 in pkg/sql/colexec.(*Materializer).next
https://github.com/cockroachdb/cockroach/blob/92d94952060fd24400906dc06e392d7a7419b392/pkg/sql/colexec/materializer.go#L246-L248 in pkg/sql/colexec.(*Materializer).nextAdapter
https://github.com/cockroachdb/cockroach/blob/92d94952060fd24400906dc06e392d7a7419b392/pkg/sql/colexecbase/colexecerror/error.go#L92-L94 in pkg/sql/colexecbase/colexecerror.CatchVectorizedRuntimeError
https://github.com/cockroachdb/cockroach/blob/92d94952060fd24400906dc06e392d7a7419b392/pkg/sql/colexec/materializer.go#L252-L254 in pkg/sql/colexec.(*Materializer).Next
https://github.com/cockroachdb/cockroach/blob/92d94952060fd24400906dc06e392d7a7419b392/pkg/sql/execinfra/base.go#L169-L171 in pkg/sql/execinfra.Run
https://github.com/cockroachdb/cockroach/blob/92d94952060fd24400906dc06e392d7a7419b392/pkg/sql/execinfra/processorsbase.go#L774-L776 in pkg/sql/execinfra.(*ProcessorBase).Run
https://github.com/cockroachdb/cockroach/blob/92d94952060fd24400906dc06e392d7a7419b392/pkg/sql/flowinfra/flow.go#L391-L393 in pkg/sql/flowinfra.(*FlowBase).Run
https://github.com/cockroachdb/cockroach/blob/92d94952060fd24400906dc06e392d7a7419b392/pkg/sql/distsql_running.go#L421-L423 in pkg/sql.(*DistSQLPlanner).Run
https://github.com/cockroachdb/cockroach/blob/92d94952060fd24400906dc06e392d7a7419b392/pkg/sql/distsql_running.go#L1001-L1003 in pkg/sql.(*DistSQLPlanner).PlanAndRun
https://github.com/cockroachdb/cockroach/blob/92d94952060fd24400906dc06e392d7a7419b392/pkg/sql/conn_executor_exec.go#L1000-L1002 in pkg/sql.(*connExecutor).execWithDistSQLEngine
https://github.com/cockroachdb/cockroach/blob/92d94952060fd24400906dc06e392d7a7419b392/pkg/sql/conn_executor_exec.go#L871-L873 in pkg/sql.(*connExecutor).dispatchToExecutionEngine
https://github.com/cockroachdb/cockroach/blob/92d94952060fd24400906dc06e392d7a7419b392/pkg/sql/conn_executor_exec.go#L638-L640 in pkg/sql.(*connExecutor).execStmtInOpenState
https://github.com/cockroachdb/cockroach/blob/92d94952060fd24400906dc06e392d7a7419b392/pkg/sql/conn_executor_exec.go#L113-L115 in pkg/sql.(*connExecutor).execStmt
https://github.com/cockroachdb/cockroach/blob/92d94952060fd24400906dc06e392d7a7419b392/pkg/sql/conn_executor_exec.go#L202-L204 in pkg/sql.(*connExecutor).execPortal
https://github.com/cockroachdb/cockroach/blob/92d94952060fd24400906dc06e392d7a7419b392/pkg/sql/conn_executor.go#L1532-L1534 in pkg/sql.(*connExecutor).execCmd.func2
https://github.com/cockroachdb/cockroach/blob/92d94952060fd24400906dc06e392d7a7419b392/pkg/sql/conn_executor.go#L1534-L1536 in pkg/sql.(*connExecutor).execCmd
https://github.com/cockroachdb/cockroach/blob/92d94952060fd24400906dc06e392d7a7419b392/pkg/sql/conn_executor.go#L1390-L1392 in pkg/sql.(*connExecutor).run
https://github.com/cockroachdb/cockroach/blob/92d94952060fd24400906dc06e392d7a7419b392/pkg/sql/conn_executor.go#L507-L509 in pkg/sql.(*Server).ServeConn
https://github.com/cockroachdb/cockroach/blob/92d94952060fd24400906dc06e392d7a7419b392/pkg/sql/pgwire/conn.go#L625-L627 in pkg/sql/pgwire.(*conn).processCommandsAsync.func1
/usr/local/go/src/runtime/asm_amd64.s#L1356-L1358 in runtime.goexit
</details>

```
pkg/sql/colflow/colrpc/inbox.go in pkg/sql/colflow/colrpc.(*Inbox).Next.func1 at line 248
/usr/local/go/src/runtime/panic.go in runtime.gopanic at line 679
pkg/sql/colexecbase/colexecerror/error.go in pkg/sql/colexecbase/colexecerror.ExpectedError at line 186
pkg/sql/colflow/colrpc/inbox.go in pkg/sql/colflow/colrpc.(*Inbox).Next at line 289
pkg/sql/colexec/operator.go in pkg/sql/colexec.(*noopOperator).Next at line 238
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).next at line 222
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).nextAdapter at line 247
pkg/sql/colexecbase/colexecerror/error.go in pkg/sql/colexecbase/colexecerror.CatchVectorizedRuntimeError at line 93
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).Next at line 253
pkg/sql/execinfra/base.go in pkg/sql/execinfra.Run at line 170
pkg/sql/execinfra/processorsbase.go in pkg/sql/execinfra.(*ProcessorBase).Run at line 775
pkg/sql/flowinfra/flow.go in pkg/sql/flowinfra.(*FlowBase).Run at line 392
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 422
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 1002
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 1001
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 872
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 639
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 114
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execPortal at line 203
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func2 at line 1533
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 1535
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 1391
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 508
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 626
/usr/local/go/src/runtime/asm_amd64.s in runtime.goexit at line 1357
```

| Tag | Value |
|---|---|
| Cockroach Release | `v20.2.2` |
| Cockroach SHA: | 92d94952060fd24400906dc06e392d7a7419b392 |
| Platform | linux amd64 |
| Distribution | CCL |
| Environment | v20.2.2 |
| Command | server |
| Go Version | ``|
| # of CPUs ||
| # of Goroutines ||

### PR DESCRIPTION
**Pull request by yuzefovich**
**execgen: remove SLICE method**

`execgen.SLICE` directive is used only in one place, and we can use
`execgen.WINDOW` there instead (which will have the same effect).

Release note: None

**coldata: fix updating offsets of bytes in Batch.SetLength**

In `SetLength` method we are maintaining the invariant of `Bytes`
vectors that the offsets are non-decreasing sequences. Previously, this
was done incorrectly when a selection vector is present on the batch
which could lead to out of bounds errors (caught by our panic-catcher)
some time later. This is now fixed by correctly paying attention to the
selection vector.

I neither can easily come up with an example query that would trigger
this condition nor can I prove that it won't occur, but I think we have
seen a single sentry report that could be explained by this bug, so I
think it's worth backporting.

Additionally, this commit uses the assumption that the selection vectors
are increasing sequences in order to calculate the largest index
accessed by the batch.

Fixes: #57297.

Release note (bug fix): Previously, CockroachDB could encounter an
internal error when executing queries with BYTES or STRING types via the
vectorized engine in rare circumstances, and now this is fixed.

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
You were not able to reproduce this? I assume the unit test is a very specific reproduction, though, right?

> Reviewed 4 of 4 files at r1, 4 of 4 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59028#-:-MR6DdLk8tINB6_q5Zxf:bbs7z38)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/col/coldata/vec_tmpl.go, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59028#-MR6DuNI33vSIR5iG2fS:-MR6DuNI33vSIR5iG2fT:b-3643nk) ([raw file](https://github.com/cockroachdb/cockroach/blob/46f5cca714258676a2d698a127c98f5ee159d15b/pkg/col/coldata/vec_tmpl.go#L81)):*
> ```Go
> 				// Note that here we rely on the fact that selection vectors are
> 				// increasing sequences.
> 				fromCol.UpdateOffsetsToBeNonDecreasing(sel[len(sel)-1] + 1)
> ```

Can we have a non-nil zero-length selection vector? Maybe it makes sense to update the earlier if case to `len(args.Sel) == 0`
___
*[pkg/sql/colexec/spilling_queue.go, line 242 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59028#-MR6ECoe-02L3RTWttOr:-MR6ECoe-02L3RTWttOs:bs9cvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9be814e0eb50cf5e7e9273ce5edb86554f201adc/pkg/sql/colexec/spilling_queue.go#L242)):*
> ```Go
> 	if q.numInMemoryItems > 0 {
> 		// If we have already enqueued at least one batch, let's try to copy
> 		// as many tuples into it as it has the capacity for.
> ```

Could you add a unit test that would tickle this bug for regression purposes?

**Review by yuzefovich — COMMENTED** [review]
Yes, I'm not able to find a repro for the bytes invariant problem (I think it could happen during `Vec.Copy` with `SelOnDest` set to `true` which is used only by the CASE operator, but we don't support CASE with Bytes output type).

Still I cannot persuade myself that the scenario mentioned in the unit test will never occur in the production, and updating the offsets up to the largest index mentioned in the selection vector has always been the intention in `SetLength` (as evidenced by the similar code in `Append` when `Sel` is non-nil), so I believe it is worth merging the fix and - possibly - backporting to previous releases.

Update: actually, this issue might be the root cause of #57297, so I'm even more convinced that we should merge and backport the fix.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59028#-:-MR75E9YCE-bHZkBxQYF:b-vkhfvu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/col/coldata/vec_tmpl.go, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59028#-MR6DuNI33vSIR5iG2fS:-MR6nDW9BnIDQ5AXm21i:b6n6lj2) ([raw file](https://github.com/cockroachdb/cockroach/blob/46f5cca714258676a2d698a127c98f5ee159d15b/pkg/col/coldata/vec_tmpl.go#L81)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Can we have a non-nil zero-length selection vector? Maybe it makes sense to update the earlier if case to `len(args.Sel) == 0`
</blockquote></details>

Good point. This currently can never occur because we never attempt to append 0 values. I've updated the contract of `Append` and left some comments in other places to highlight that.

I slightly prefer doing it this way (other than checking for the case whether we are trying to append 0 values and having some custom behavior there) since it would show up as an internal error to indicate that the assumptions are violated elsewhere. Let me know if you would prefer to be on the safe side.
___
*[pkg/sql/colexec/spilling_queue.go, line 242 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59028#-MR6ECoe-02L3RTWttOr:-MR8GkrD9c-Yx8N1NHRX:b-llwuct) ([raw file](https://github.com/cockroachdb/cockroach/blob/9be814e0eb50cf5e7e9273ce5edb86554f201adc/pkg/sql/colexec/spilling_queue.go#L242)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Could you add a unit test that would tickle this bug for regression purposes?
</blockquote></details>

Opened #59077.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59028#-:-MROvP5h88Hx_iAk0PCb:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
