### PR TITLE
opt: update cost of index join and statistics of array contains operation

### PR DESCRIPTION
**Pull request by rytaft**
**opt: update statistics of array contains operation to match json contains**

Prior to this commit, the selectivity of `j @> '{"a": "b"}'::json` was calculated
as `1/9`, while the selectivity of `a @> array[1]` was calculated as `1/3`. Both of
these predicates essentially represent one "path" that can be queried in an
inverted index, so they should have the same selectivity. Furthermore, multiple
paths should be more selective, so in the same way that the predicate
`j @> '{"a": "b", "c": "d"}'::json` has selectivity `(1/9 * 1/9)`, `a @> array[1,2]`
should similarly have selectivity `(1/9 * 1/9)`. This commit updates the logic
in the statistics builder so that this is the case.

Release note (performance improvement): Improved the selectivity estimate for
array contains predicates (e.g., `arr @> ARRAY[1]`) in the optimizer. This
improves the optimizer's cardinality estimation for queries containing these
predicates, and may result in better query plans in some cases.

**opt: update cost of index join to match cost of lookup join**

Prior to this commit, the cost of an index join was much less than the cost
of an equivalent lookup join. Since index joins have the same implementation
as lookup joins when the lookup columns form a key in the lookup table, the
two operators should have the same cost. This commit updates the coster so
that this is the case.

Informs #46677

Release note (performance improvement): Updated the cost model in the optimizer
to make index joins more expensive and better reflect the reality of their
cost. As a result, the optimizer will choose index joins less frequently,
generally resulting in more efficient query plans.

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
Fighting the good fight with statistics and the coster. This is elegant. You make it look easy.

I suppose this will motivate us further to reducing unnecessary IndexJoins!

:lgtm: 

> Reviewed 3 of 3 files at r1, 15 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54768#-:-MI1Kor33oEWFFoF6F7j:b-4qhy0m)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/testdata/stats/partial-index-scan, line 489 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54768#-MI1Ja-a-w6RAbdTL0lJ:-MI1Ja-a-w6RAbdTL0lK:bjou7lb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9eabebfbf49a9cf640c883fdbd3617292a135a5/pkg/sql/opt/memo/testdata/stats/partial-index-scan#L489)):*
> ```
>  │    └── scan hist@idx,partial
>  │         ├── columns: k:1(int!null) s:3(string)
>  │         ├── stats: [rows=90.9090909, distinct(2)=6.45454545, null(2)=0]
> ```

There's a TODO above explaining that the `distinct(2)` stat is off here by 1. This change makes it a bit harder to tell, but I think the correct value for `distinct(2)` is now `5.454545`. Can you update the comment to keep it in sync with these numbers? Alternatively, you can change the histogram boundaries/values to prevent changing the distinct count here (but that's quite an endeavor, I know).

I hope to have a fix for this TODO soon!

**Review by rytaft — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54768#-:-MI4Lmhi9NDFMbUkexfE:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/memo/testdata/stats/partial-index-scan, line 489 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54768#-MI1Ja-a-w6RAbdTL0lJ:-MI4Kr1E-oQ4u79cq0-3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9eabebfbf49a9cf640c883fdbd3617292a135a5/pkg/sql/opt/memo/testdata/stats/partial-index-scan#L489)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

There's a TODO above explaining that the `distinct(2)` stat is off here by 1. This change makes it a bit harder to tell, but I think the correct value for `distinct(2)` is now `5.454545`. Can you update the comment to keep it in sync with these numbers? Alternatively, you can change the histogram boundaries/values to prevent changing the distinct count here (but that's quite an endeavor, I know).

I hope to have a fix for this TODO soon!
</blockquote></details>

Done.

**Comment by rytaft** [comment]
Flake from https://github.com/cockroachdb/cockroach/issues/54775

bors r+

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Nice fixes!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54768#-:-MI5H9VTC6mpDPnVxg61:bsf7v3m)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @RaduBerinde)

**Comment by rytaft** [comment]
TFTR!

Another Flake from #54775

bors r+

**Pull request merged**
