### PR TITLE
log: make symlinks best-effort

### LINKED ISSUE #15814: log: Symlink privilege issue with Windows
**QUESTION**

In Windows 7 64-bit, I am getting:

```
C:\temp>cockroach.exe start
I170509 11:30:09.103935 1 cli/start.go:575  
CockroachDB OSS v1.0-rc.2 (windows amd64, built 2017/05/05 13:59:27, go1.8.1)
log: exiting because of error: log: 
cannot create log: symlink cockroachexe.xxxxxx.2017-05-09T11_30_09-07_00.001068.log 
C:\temp\cockroach-data\logs\cockroachexe.log: A required privilege is not held by the client.
```

My expectation is that  non-privileged Windows user will be able to run crdb? Is there anyway to avoid this symlink creation?

### PR DESCRIPTION
**Pull request by tamird**
On Windows, symlink creation requires special privileges[0]. To avoid
unexpected and unnecessary failures there, make our symlink creation
failures log to stderr instead of taking down the process.

Fixes #15814.

[0] https://docs.microsoft.com/en-us/windows/device-security/security-policy-settings/create-symbolic-links

PR addendum: this is possibly a little spammy. Does anyone feel strongly?

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/util/log/file.go, line 240 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15867#-KjoYQp8rWBvYRVmf6-7:-KjoYQp8rWBvYRVmf6-8:b4j8zqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c435326c18eefef672a68c978a9632f814a6e37/pkg/util/log/file.go#L240)):*
> ```Go
> 		// Symlinks are best-effort.
> 
> 		if err := os.Remove(symlink); err != nil {
> ```

Does `os.Remove` return an error if the given path doesn't exist? I think we want to at least filter out `os.IsNotExist()` errors. 

---

*[pkg/util/log/file.go, line 244 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15867#-KjoYfo2L4Z8tbjsMBqR:-KjoYfo2L4Z8tbjsMBqS:b-paglek) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c435326c18eefef672a68c978a9632f814a6e37/pkg/util/log/file.go#L244)):*
> ```Go
> 		}
> 		if err := os.Symlink(filepath.Base(fname), symlink); err != nil {
> 			fmt.Fprintf(OrigStderr, "log: failed to create symlink %s: %s", symlink, err)
> ```

On windows, this will be the common case (for many deployments). I'd suppress the logging completely at least if `GOOS` is windows. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15867#-:-KjoYwcfd0P-Ho70qfh-:bnfp4nl)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/util/log/file.go, line 240 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15867#-KjoYQp8rWBvYRVmf6-7:-Kjoh0R-CziZQtUcmmLx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c435326c18eefef672a68c978a9632f814a6e37/pkg/util/log/file.go#L240)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Does `os.Remove` return an error if the given path doesn't exist? I think we want to at least filter out `os.IsNotExist()` errors. 
</blockquote></details>

Done.

---

*[pkg/util/log/file.go, line 244 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15867#-KjoYfo2L4Z8tbjsMBqR:-Kjoh0tsg5uwPjtJpMti:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c435326c18eefef672a68c978a9632f814a6e37/pkg/util/log/file.go#L244)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

On windows, this will be the common case (for many deployments). I'd suppress the logging completely at least if `GOOS` is windows. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15867)*

**Comment by BramGruneir** [comment]
Perhaps a candidate for 1.0.1?

**Comment by tamird** [comment]
Yep, nominating.

**Pull request merged**
