### PR TITLE
sql: refactor Executor.execStmtInParallel

### PR DESCRIPTION
**Pull request by andreimatei**
... to not take in a StatementResult.

Before this patch, Executor.execStmtInParallel() was taking in a
StatementResult and writing mocked results to it. I've lifted the
mocking to the parent, since this matches an important concept -
parallel statements don't return results, so it was unnatural for
execStmtInParallel() to look like it's returning them.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/executor.go, line 2200 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19539#-KxKYlFPVPdAHuyLkIbw:-KxKYlFPVPdAHuyLkIbx:b-eievnz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a94ae5cac88cb02e6946580ca012f0b48b064551/pkg/sql/executor.go#L2200)):*
> ```Go
> // the query's plan which can be used by the caller to return mocked results
> // with the right schema to the client. Note that planning needs to be done
> // synchronously because it's needed by the query dependency analysis.
> ```

Maybe make a mention to the `planNode` we're returning.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19539)*

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19539#-:-KxKYvS-rStQwE30ceU5:bnfp4nl)*

**Comment by andreimatei** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/executor.go, line 2200 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19539#-KxKYlFPVPdAHuyLkIbw:-L0BgLegIhcA-yQfJnH1:b-7vl112) ([raw file](https://github.com/cockroachdb/cockroach/blob/a94ae5cac88cb02e6946580ca012f0b48b064551/pkg/sql/executor.go#L2200)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Maybe make a mention to the `planNode` we're returning.
</blockquote></details>

replaced the returned plan node with the list of cols, as discussed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19539)*

**Comment by nvanbenschoten** [comment]
:lgtm:er

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19539#-:-L0Bh7dEMGBcYH4VRiDj:b593xvi)*

**Pull request merged**
