### PR TITLE
storage: move io limiter to store

### PR DESCRIPTION
**Pull request by dt**
Move the bulk io limiter from the global cluster settings object to individual stores.
This is both cleaner (not having some package-specific object in a shared, base package) and
has the runtime benefit of limiting stores separately, which matches the intention that they
are separate devices with, presumably, separate IO budgets.

Release note (enterprise change): Bulk IO rate limiting is done per-store rather than per-node.

cc @RaduBerinde for the first commit (the settings `SetOnChange` hook registration).

### CODE REVIEW

**Comment by mjibson** [comment]
Review status: 0 of 9 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/settings/setting.go, line 34 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22729#-L5PxYET3dlDZEDp3-J_:-L5PxYET3dlDZEDp3-Ja:b-f610uv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ed5b6d539368295b27a68c828b84142963402c2/pkg/settings/setting.go#L34)):*
> ```Go
> 	genericVals [maxSettings]atomic.Value
> 
> 	changeMu syncutil.Mutex
> ```

Use the `changeMu struct {
  syncutil.Mutex
  onChange ...
}` pattern here so it's obvious exactly what the mutex protects.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22729)*

**Comment by RaduBerinde** [comment]
:lgtm_strong: 

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/settings/setting.go, line 85 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22729#-L5Pzt56C4_ubS4L7ayV:-L5Pzt56C4_ubS4L7ayW:bfil7jj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f95475ee932c6e76266b0e08c3562af9436d510/pkg/settings/setting.go#L85)):*
> ```Go
> func (sv *Values) settingChanged(slotIdx int) {
> 	sv.changeMu.Lock()
> 	funcs := sv.onChange[slotIdx]
> ```

[nit] Add a note here saying that we assume the slice cannot be changed in-place (which might stop being the case later if we add a RemoveOnChange).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22729#-:-L5Q1BsTBrnRtDIo3tkI:b-uwkowd)*

**Comment by dt** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/settings/setting.go, line 85 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22729#-L5Pzt56C4_ubS4L7ayV:-L5Q9n65w0ngrahzy1Y8:blwlgnp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f95475ee932c6e76266b0e08c3562af9436d510/pkg/settings/setting.go#L85)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Add a note here saying that we assume the slice cannot be changed in-place (which might stop being the case later if we add a RemoveOnChange).
</blockquote></details>

put the comment on the mu about what it's covering.

---

*[pkg/settings/setting.go, line 34 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22729#-L5PxYET3dlDZEDp3-J_:-L5Q9r7-h3nkDawCPQnA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ed5b6d539368295b27a68c828b84142963402c2/pkg/settings/setting.go#L34)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Use the `changeMu struct {
  syncutil.Mutex
  onChange ...
}` pattern here so it's obvious exactly what the mutex protects.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22729)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22729#-:-L5QDICCCODLRAFQDpsR:bnfp4nl)*

**Pull request merged**
