### PR TITLE
ui: use protobuf instead of json for logs api call

### PR DESCRIPTION
**Pull request by maxlang**
cc @tamird

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8622)

### CODE REVIEW

**Comment by tamird** [comment]
Did you mean to also remove https://github.com/cockroachdb/cockroach/pull/8572/files#diff-8037a9e1203e2919f5f6259f0d97518aR47 ?

**Comment by maxlang** [comment]
@tamird wrong issue number, but it's still an issue. We don't get the enum from the proto file.

**Comment by tamird** [comment]
OK, please update the comments.

**Comment by maxlang** [comment]
done

**Comment by mrtracy** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[ui/app/containers/nodeLogs.tsx, line 39 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8622#-KPPVmemySoHdCraBX0R:-KPPVmemySoHdCraBX0S:b-vto2ab) ([raw file](https://github.com/cockroachdb/cockroach/blob/b978ffc9a97d550dd7d5057931c0fa5eecbb23d6/ui/app/containers/nodeLogs.tsx#L39)):*
> ```XML
>         {
>           title: "Severity",
>           cell: (index: number) => FormatSeverity(logEntries[index].severity ? logEntries[index].severity.toNumber() : 0),
> ```

Is it even possible for this to be null or undefined?  Is there a logEntries[index].getSeverity() that could be used instead? 

---

*[ui/app/util/format.ts, line 47 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8622#-KPPW9fgE9eYfM5x11ri:-KPPW9fgE9eYfM5x11rj:b-hlwq4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/7596d63f1d45c9cedbfed74f0ad3cbdbe18f20ee/ui/app/util/format.ts#L47)):*
> ```XML
> }
> 
> // TODO: generate this automatically from the protos - #8567
> ```

Moving this to protos is going to involve the same bug as the metrics enumerations (described in metricsDataProvider.tsx).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8622)*

**Comment by mrtracy** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[ui/app/util/format.ts, line 47 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8622#-KPPW9fgE9eYfM5x11ri:-KPPWxxM0X5btDp05ZbG:bxnucnd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7596d63f1d45c9cedbfed74f0ad3cbdbe18f20ee/ui/app/util/format.ts#L47)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> Moving this to protos is going to involve the same bug as the metrics enumerations (described in metricsDataProvider.tsx).
</details>
Just suggesting that you update this TODO with that information.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8622)*

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[ui/app/util/format.ts, line 47 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8622#-KPPW9fgE9eYfM5x11ri:-KPPb6itordxD3MAY9RZ:btb1qzk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7596d63f1d45c9cedbfed74f0ad3cbdbe18f20ee/ui/app/util/format.ts#L47)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> Just suggesting that you update this TODO with that information.
</details>
also https://github.com/cockroachdb/cockroach/pull/8626

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8622)*

**Comment by maxlang** [comment]
Review status: 1 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[ui/app/containers/nodeLogs.tsx, line 39 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8622#-KPPVmemySoHdCraBX0R:-KPUXDG_ADYkaennjbsg:b5ugwo6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b978ffc9a97d550dd7d5057931c0fa5eecbb23d6/ui/app/containers/nodeLogs.tsx#L39)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> Is it even possible for this to be null or undefined?  Is there a logEntries[index].getSeverity() that could be used instead? 
</details>
It can be `undefined`. I don't exactly understand why, but when it's 0 it's omitted and I couldn't fix the proto to have the right behavior. @tamird seemed to indicate it was proto3 vs proto2 issue? I'm not sure why we couldn't use the same solution we've used elsewhere.

---

*[ui/app/util/format.ts, line 47 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8622#-KPPW9fgE9eYfM5x11ri:-KPUXnvohNYfkXxeWe0e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7596d63f1d45c9cedbfed74f0ad3cbdbe18f20ee/ui/app/util/format.ts#L47)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> also https://github.com/cockroachdb/cockroach/pull/8626
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8622)*

**Comment by tamird** [comment]
ugh, this is going to interact poorly with changes that are on master. i'll merge dev to master now.

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[ui/app/containers/nodeLogs.tsx, line 39 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8622#-KPPVmemySoHdCraBX0R:-KPUY6BRDBh79ylWkFMH:bwfagfx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b978ffc9a97d550dd7d5057931c0fa5eecbb23d6/ui/app/containers/nodeLogs.tsx#L39)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> It can be `undefined`. I don't exactly understand why, but when it's 0 it's omitted and I couldn't fix the proto to have the right behavior. @tamird seemed to indicate it was proto3 vs proto2 issue? I'm not sure why we couldn't use the same solution we've used elsewhere.
</details>
You should remove this default. I've changed this so `0` is now UNKNOWN, which is a variant that will never come over the wire, so this field will always be set.

---

*[ui/app/util/format.ts, line 53 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8622#-KPUYDU2znG5edxWCoU7:-KPUYDU2znG5edxWCoU8:b-szj7bu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4978ce8cb0c5f80a9842576e3ee828f1ef545fc7/ui/app/util/format.ts#L53)):*
> ```XML
>  * representation.
>  */
> export function FormatSeverity(severity: number): string {
> ```

remove this function, it's called from one place.

---

*[ui/app/util/protoEnums.ts, line 4 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8622#-KPUYLSdZlXI8PFj81e6:-KPUYLSdZlXI8PFj81e7:b-c5axvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4978ce8cb0c5f80a9842576e3ee828f1ef545fc7/ui/app/util/protoEnums.ts#L4)):*
> ```XML
>  * HACK
>  *
>  * This enumeration is copied due to an incompatibility between two tools in our
> ```

these

give this whole thing a once-over.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8622#-:-KPUYTlApJZuG05nS2A7:b9j9ru4)*

**Comment by maxlang** [comment]
@tamird is it ok to merge?

---

Review status: 3 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[ui/app/containers/nodeLogs.tsx, line 39 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8622#-KPPVmemySoHdCraBX0R:-KPZ4EPgkyE3xG6Tzbhh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b978ffc9a97d550dd7d5057931c0fa5eecbb23d6/ui/app/containers/nodeLogs.tsx#L39)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> You should remove this default. I've changed this so `0` is now UNKNOWN, which is a variant that will never come over the wire, so this field will always be set.
</details>
Done.

---

*[ui/app/util/protoEnums.ts, line 4 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8622#-KPUYLSdZlXI8PFj81e6:-KPZ4GDonHYIVDs3IWFX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fd954e9ff10af077165f22b213c404d473b327/ui/app/util/protoEnums.ts#L4)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> these
> 
> give this whole thing a once-over.
</details>
Done.

---

*[ui/app/util/format.ts, line 53 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8622#-KPUYDU2znG5edxWCoU7:-KPZ4FU7LlK-fqrG9ZJ8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fd954e9ff10af077165f22b213c404d473b327/ui/app/util/format.ts#L53)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> remove this function, it's called from one place.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8622#-:-KPUYgw1TCHOa0ZsrP7O:b-3zvjf3)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8622#-:-KPZXU94cThyCRbQ7oZq:bnfp4nl)*

**Pull request merged**
