### PR TITLE
cli/doctor, doctor: use right jobs table, skip dropped descs

### LINKED ISSUE #122675: cli,jobs: debug doctor reads jobs table incorrectly
**Describe the problem**

Debug doctor creates an in-memory representation of the jobs table using system.jobs.txt.  When doing so, it elides any jobs that don't have a payload set to account for redacted bundles:

https://github.com/cockroachdb/cockroach/blob/fe33dc1c4af9f044c839c1d256b5cfe13e7aa192/pkg/cli/doctor.go#L525-L528

In recent versions of cockroach however, this field will be NULL even in unredacted bundles because the progress is now stored in system.job_info.txt.

As a result, we may see erroneous errors during descriptor validation, such as 

```
  ParentID 104, ParentSchemaID 105: relation "table_name" (185): mutation job 958848289758347265: job 958848289758347265 not found
```

Jira issue: CRDB-38020

Epic CRDB-37763

### LINKED ISSUE #122956: roachtest: schemachange/mixed-versions failed [debug doctor validation failed with "job not found"]
roachtest.schemachange/mixed-versions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14960054?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14960054?buildTab=artifacts#/schemachange/mixed-versions) on master @ [0fbef53e48c2a3784631a09a42236e1d0636a5a7](https://github.com/cockroachdb/cockroach/commits/0fbef53e48c2a3784631a09a42236e1d0636a5a7):

```
(mixedversion.go:592).Run: mixed-version test failure while running step 16 (run "run schemachange workload and validation in mixed version"): full command output in run_062906.654333798_n4_cockroach-debug-doct.log: COMMAND_PROBLEM: exit status 125
test artifacts and logs in: /artifacts/schemachange/mixed-versions/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-14960054/schemachange-mixed-versions/1713939864497/1713940427427)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #122955 roachtest: schemachange/mixed-versions failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-release-23.2.5-rc release-blocker]
- #122350 roachtest: schemachange/mixed-versions failed [descriptor ID generator unavailable, migration in progress] [C-test-failure O-roachtest O-robot T-sql-foundations branch-release-23.1]
- #122274 roachtest: schemachange/mixed-versions failed [attempting to append refresh spans after the tracked timestamp has moved forward] [C-test-failure O-roachtest O-robot T-kv branch-release-23.2 release-blocker]
- #121411 roachtest: schemachange/mixed-versions failed [enum removal not yet in 23.2 release] [C-test-failure O-roachtest O-robot P-1 T-sql-foundations branch-release-24.1]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/mixed-versions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-38136

### LINKED ISSUE #123477: doctor: examine should ignore dropped descriptors
**Describe the problem**
Debug doctor examine does not skip over dropped descriptors. This leads to false-positives as seen in https://github.com/cockroachdb/cockroach/issues/122956 -- where the descriptor that was detected to have a dangling job reference was already dropped (as seen by `"dropTime": "1713940113794672911"`), making the actual jobmutation on the descriptor a no-op.

We should just skip over descriptors with a `dropTime` in our validation.

Jira issue: CRDB-38368

Epic CRDB-37763

### PR DESCRIPTION
**Pull request by annrpom**
### cli/doctor: doctor should read from the right jobs table
In https://github.com/cockroachdb/cockroach/issues/97762, we started writing a job's payload (and progress)
information to the `system.jobs_info` table. As a result, we
had to change the parts of our code that relied on the `system.jobs`
table to use `crdb_internal.system_jobs` instead (since that table
would inaccurately report that some `payload`s were `NULL`).
This change did not occur for the in-memory representation of the jobs
table created by debug doctor -- which can result in missing job
false-positives. This patch updates debug doctor's representation of
the jobs table by referring to `crdb_internal.system_jobs` instead.

Epic: none
Fixes: https://github.com/cockroachdb/cockroach/issues/122675

Release note: None

---

### doctor: skip validation for dropped descriptors
In some cases, dropped descriptors appear in our `system.descriptors`
table with dangling job mutations without an associated job.
This patch teaches debug doctor examine to skip validation
on such dropped descriptors.

Epic: none

Fixes: https://github.com/cockroachdb/cockroach/issues/123477
Fixes: https://github.com/cockroachdb/cockroach/issues/122956

Release note: none

### CODE REVIEW

**Review by fqazi — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123298)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom)

___
*[`pkg/cli/doctor.go` line 558 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123298#-NxDc2kr7KLM62ZEJvAV:-NxDc2ks4sKi_3byG-D3:boewtqv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416ff0fdb47edd9df12276f4b84d4990d298bff/pkg/cli/doctor.go#L558)):*
> ```Go
> 		}, 0)
> 		// TODO(before merge): when does this happen?
> 		if err := parseJSONFile(zipDirPath, "system.jobs.json", &jobsTableJSON); err != nil {
> ```

On master / 24.1 a debug zip will format tables as JSON, so we need to account for that
___
*[`pkg/cli/doctor_test.go` line 214 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123298#-NxDchqP2_RS2egJ1wda:-NxDchqP2_RS2egJ1wdb:br272a8) ([raw file](https://github.com/cockroachdb/cockroach/blob/483722d44b0c2f7b8e2f9d2865070d104a79d356/pkg/cli/doctor_test.go#L214)):*
> ```Go
> 
> // TestDoctorClusterDropped tests that debug doctor examine will avoid validating dropped descriptors.
> func TestDoctorClusterDropped(t *testing.T) {
> ```

Could we just combine it with the one above? I think it will be a bit cleaner since it will be a different path and toggling between the two flag states.

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123298)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/cli/doctor.go` line 558 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123298#-NxDc2kr7KLM62ZEJvAV:-NxJrAN_960GQkFF23jd:b-xcl1s2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416ff0fdb47edd9df12276f4b84d4990d298bff/pkg/cli/doctor.go#L558)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

On master / 24.1 a debug zip will format tables as JSON, so we need to account for that
</blockquote></details>

faizan and i had a talk offline and found out that the original PR that changed debug zip output to JSON format was partially reverted(https://github.com/cockroachdb/cockroach/commit/38cf825a3f385f326d1c88bf4478bcaf531c38e6) so that the format is still the beloved tsv that we see today -- with an option to specify JSON formatting by doing:
```
cockroach debug zip debug-json.zip --format=json
```

just did a little update to ensure that JSON formatting is supported properly
___
*[`pkg/cli/doctor_test.go` line 214 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123298#-NxDchqP2_RS2egJ1wda:-NxJsFuW35gRF8LDChYR:b-fnzx9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/483722d44b0c2f7b8e2f9d2865070d104a79d356/pkg/cli/doctor_test.go#L214)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Could we just combine it with the one above? I think it will be a bit cleaner since it will be a different path and toggling between the two flag states.
</blockquote></details>

I tried seeing how this one would pan out, but it's not looking too hot https://github.com/annrpom/cockroach/commit/9eb1aecbf0192cbbd1bc833b9ba8586510b72a80

I think we could merge these two tests together if we did something like
```
// setup for 1st one:
create table
unsafe upsert
run debug doctor examine

// followed by setup for 2nd one:
unsafe upsert -- adding dropped fields
run debug doctor examine
```

However, I am getting the error linked in the commit above when I try this; also, would https://github.com/cockroachdb/cockroach/blob/48ebfd19349624e70a658437af4e597be7e75c06/pkg/sql/repair.go#L101-L104 not block me in any way? I am probably missing something here, wdyt :bow: ?

**Review by fqazi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123298#-:-NxOgewt7bGvDgfJL_IQ:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @annrpom)

___
*[`pkg/cli/doctor_test.go` line 214 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123298#-NxDchqP2_RS2egJ1wda:-NxOgRMp2j98hClUyOur:b2r8vpf) ([raw file](https://github.com/cockroachdb/cockroach/blob/483722d44b0c2f7b8e2f9d2865070d104a79d356/pkg/cli/doctor_test.go#L214)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

I tried seeing how this one would pan out, but it's not looking too hot https://github.com/annrpom/cockroach/commit/9eb1aecbf0192cbbd1bc833b9ba8586510b72a80

I think we could merge these two tests together if we did something like
```
// setup for 1st one:
create table
unsafe upsert
run debug doctor examine

// followed by setup for 2nd one:
unsafe upsert -- adding dropped fields
run debug doctor examine
```

However, I am getting the error linked in the commit above when I try this; also, would https://github.com/cockroachdb/cockroach/blob/48ebfd19349624e70a658437af4e597be7e75c06/pkg/sql/repair.go#L101-L104 not block me in any way? I am probably missing something here, wdyt :bow: ?
</blockquote></details>

Yeah, its okay to leave it separate then.

**Comment by rafiss** [comment]
nice work! looks like there's one issue in the new test.
```
=== RUN   TestDoctorClusterDropped/examine
[debug --host=127.0.0.1:39133 --insecure=false --certs-dir=/var/lib/engflow/worker/work/0/exec/_tmp/1855398a359288315eef18ccd1f2c1dd/cli-test2994948257 doctor examine cluster]
    datadriven.go:144: 
        /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/cli/cli_test_/cli_test.runfiles/com_github_cockroachdb_cockroach/pkg/cli/testdata/doctor/test_examine_cluster_dropped:1:
         
        expected:
        debug doctor examine cluster
        Examining 57 descriptors and 58 namespace entries...
        Examining 2 jobs...
        No problems found!
        
        found:
        debug doctor examine cluster
        Examining 62 descriptors and 63 namespace entries...
          ParentID 100, ParentSchemaID 101: namespace entry "foo" (104): descriptor is being dropped
        Examining 7 jobs...
        ERROR: validation failed
```

also, could you take care of adding the correct backport labels? (is it just 24.1 or 23.2 as well?)

**Comment by annrpom** [comment]
TFTR! ('-')7

backporting all the way back to 23.1 because that looks like when we stopped writing payload/progress to system.jobs https://github.com/cockroachdb/cockroach/pull/99458

bors r=fqazi

**Pull request merged**
