### PR TITLE
sql: remove non-localized TIMESTAMP type

### PR DESCRIPTION
**Pull request by dt**
This removes one of our two timestamp types, leaving only the one formerly called TIMESTAMPTZ, which
respects the session offset when rendered and when parsed if as explicit offset is not provided. This
change removes the `TIMESTAMP WITHOUT TIME ZONE' type, and changes the shorthand 'TIMESTAMP' to point
to the 'WITH TIME ZONE' instead. This breaks with the definition in the SQL spec but hopefully proves
more intuitive to users.

The 'WITHOUT TIME ZONE' behavior has proven confusing and unintuitive in our own usage and seems likely
to confuse our users as well. Additionally, most advice for postgres users is to generally alway use the
'WITH TIME ZONE' type to avoid confusing semantics where some timestamps respect non-zero session offsets
while others do not.

For example, intuitively 'current_date()' should respect the session offset and 'current_time()::date'
should return the same value as 'current_date()', together implying that 'current_time' should also return
a timestamp that respects the session offset. Mixing two different types of timestamps quickly becomes
tidious, with ambigious overloads, casting and unexpected errors.

This may end up needed to be reversed in the event we find an ORM or user who absolutely requires
the WITHOUT TIME ZONE behavior specified in the SQL spec, despite its confusing semantics, but it will
be much easier to add the second type back later if we discover it is required compared to trying to
remove it after some users have started to use it unknowningly.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10529)

### CODE REVIEW

**Comment by bdarnell** [comment]
Sqlalchemy's postgres backend [always sends](https://github.com/zzzeek/sqlalchemy/blob/942c2429c033255979b6a55de836b9b26370673e/lib/sqlalchemy/dialects/postgresql/base.py#L1735) the `{WITH,WITHOUT} TIME ZONE` modifier, and [defaults](http://docs.sqlalchemy.org/en/latest/core/type_basics.html#sqlalchemy.types.TIMESTAMP) to `WITHOUT`. 

Even though the standard semantics for `WITHOUT TIME ZONE` are confusing, they're standard, and I worry that dropping this support conflicts with our goal of ORM compatibility.

**Comment by mjibson** [comment]
Reviewed 13 of 29 files at r1.
Review status: 13 of 29 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/builtins.go, line 714 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10529#-KW1LFyVADfkoH5l9hSe:-KW1LFyVADfkoH5l9hSf:b5dnox1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c41e005cbecf24afa79f350cd381f751e530e7d/pkg/sql/parser/builtins.go#L714)):*
> ```Go
> 			Types:             ArgTypes{},
> 			ReturnType:        TypeTimestamp,
> 			preferredOverload: true,
> ```

Does this still need to be here?

---

*[pkg/sql/parser/builtins.go, line 1220 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10529#-KW1LJzKrentpqPe0j3w:-KW1LJzKrentpqPe0j3x:b-816h6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c41e005cbecf24afa79f350cd381f751e530e7d/pkg/sql/parser/builtins.go#L1220)):*
> ```Go
> 		Types:             ArgTypes{},
> 		ReturnType:        TypeTimestamp,
> 		preferredOverload: true,
> ```

Same.

---

*[pkg/sql/parser/col_types_test.go, line 51 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10529#-KW1LQlL5-y7XPdWhxvq:-KW1LQlL5-y7XPdWhxvr:b-lqw7k7) ([raw file](https://github.com/cockroachdb/cockroach/blob/551dc8944e63ee6ffd034b553cbe324824646dbd/pkg/sql/parser/col_types_test.go#L51)):*
> ```Go
> 		{"DATE", &DateColType{}},
> 		{"TIMESTAMP", &TimestampColType{}},
> 		{"TIMESTAMP WITH TIME ZONE", &TimestampTZColType{}},
> ```

Can this stay?

---

*[pkg/sql/parser/sql.y, line 3254 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10529#-KW1JHJnPUCSa8fy4oeK:-KW1JHJo6rmsAZsc-whT:b-hnv7l5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c41e005cbecf24afa79f350cd381f751e530e7d/pkg/sql/parser/sql.y#L3254)):*
> ```Yacc
>     $$.val = timestampColTypeTimestamp
>   }
> | TIMESTAMP WITHOUT TIME ZONE  { return unimplemented(sqllex) }
> ```

I thought we were just going to lie since we're already breaking with the spec for the default.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10529)*

**Comment by dt** [comment]
@bdarnell Indeed, ORM compat seems to be the most likely to cause us to undo this change down the road, but it is still _possible_ to remove it now, before "production ready" and increased concern about what existing users started relying on. We might need to add it back later, if we find an ORM or user that absolutely needs it, but if not we dodge supporting the increased complexity and confusion long-term.

It sounds like we we'll want to parse and ignore all `WITH(OUT) TIME ZONE` modifiers, rather than than erring, since sqlalchemy and potentially others generate them by default -- the big question will just be whether the orms/pgwire drivers respect the OIDs and parse the offset suffix when reading them. We can also recommend zero session offsets as that means the semantics are the same.

**Comment by a-robinson** [comment]
How long would it take to test sqlalchemy on top of such a behavior change? It seems worth trying as soon as possible rather than having hypothetical discussions about it if it isn't tons of work.

**Comment by bdarnell** [comment]
I haven't touched this repo in months but you should be able to run the tests in https://github.com/cockroachdb/cockroachdb-python by cloning the repo, running `bootstrap.sh` and then `make test`. It implements a few customizations for cockroachdb so it's not the pure postgres mode (we can remove some of these now), but I think timestamp stuff is using the defaults. It runs against a cockroachdb server running on localhost on the default port.

**Comment by dt** [comment]
it looks like sqlalchemy's tests read a timestamp back from the db and compare it to a literal in the test. The literal has no offset set, while the one coming out of the driver has an explicit offset of 0, making the two uncomparable.

I'm not sure this would actually come up in practice, where you'd just use explicit 0 offsets if that's what you want, but that test won't doesn't like the offset being there.

**Comment by cuongdo** [comment]
@nvanbenschoten any thoughts here?

**Comment by dt** [comment]
Side note on changing default for shorthand vs totally removing second type: We've discussed and generally favored switching the default for the `TIMESTAMP` shorthand to be the offset-respecting `WITH TIME ZONE` variant, rather than the `WITHOUT TIME ZONE` one, since the `WITHOUT` one can be confusing.  There was a mild assumption that switching the default for the shorthand would be a smaller, less invasive change than this one.
However I think we'll see similar compatibility challenges doing that, since we'll we'll be returning offsets in some places pg didn't, so we may as well go all the way if we're going to do it at all.

**Comment by nvanbenschoten** [comment]
Based on our discussion earlier today, it sounds like the two primary benefits of this change are that it:
- allows us to clean up code which right now has to deal with two distinct timestamp types
- simplifies the timestamp story in CockroachDB so that multiple timestamp types don't confuse users

I believe the duplicate types issue is something that would be solved with improved support for type parametrization in the `sql/parser` package. This improvement has already been deemed necessary for us to effectively support collated strings, and it's my understanding that @eisenstatdavid is actively working on this. If so, I think we should at least wait until progress has been made in that direction before making this change.

With respect to the second benefit, I'm not sold that this won't come with hidden costs to users. It seems to me that users will come in two categories: those familiar with SQL timestamps and those new to SQL timestamps. I'd assume the first group would prefer for our timestamp implementation to come with as few surprises to them as possible. If they have already used timestamps before, they'll know the difference between `Timestamp` and `TimestampTZ`, and when to use each. On the other hand, those new to SQL timestamps will learn by looking at our documentation, where we can control what to present. A large **When in doubt, use TimestampTZ** message in our docs should do the trick of discouraging `Timestamp`'s use. This is probably a large oversimplification, but I forsee a deviation from the SQL spec causing just as much confusion as supporting a problematic part of that spec.

**Comment by dt** [comment]
Closing for now -- we can reopen and test when we have a little more ORM compat in place or if type family / related work turns out differently.

**Pull request closed without merging**
