### PR TITLE
build: fix issue posting script

### LINKED ISSUE #23447: build: broken `master` builds don't post issues any more
https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_UnitTests&branch_Cockroach=%3Cdefault%3E&tab=buildTypeStatusDiv

### PR DESCRIPTION
**Pull request by tbg**
Fixes #23447.

Or so I hope.

Release note: None

### CODE REVIEW

**Comment by tschottdorf** [comment]
@benesch not sure if there's something I can run to test this. Also, `master` is broken until https://github.com/cockroachdb/cockroach/pull/23446 merges (maybe that can be used for a test).

**Comment by tschottdorf** [comment]
I guess I need to use `json.loads` instead of `load`. Should I be using something like `json.load(res, 'utf8')` instead? My Python is weak.

**Comment by benesch** [comment]
We could also just upgrade to Python 3.6, which is why this worked for me locally: https://docs.python.org/3/whatsnew/3.6.html#json

🤦‍♂️

**Comment by tschottdorf** [comment]
Well, I'm happy to do whatever you prefer or to outright hand this PR over to you. Just let me know!

**Comment by benesch** [comment]
> json.load(res, 'utf8')

^ Is that a thing?

Anyway, I'd just go with the solution you have, modulo switching to `loads`! Or you can use something like this, according to StackOverflow:

```
decoder = codecs.getreader("utf-8")
obj = json.load(decoder(response))
```

FWIW it's probably fine to assume UTF-8.

**Comment by benesch** [comment]
Anyway, to test this locally I was manually filling in the env vars to point at at broken build. See the many TestInitialPartitioning issues I filed today: https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+author%3Abenesch+is%3Aclosed

Let me know if you want me to run the tests; unfortunately the command is in my work laptop bash_history so I won't be any faster than you.

**Comment by tschottdorf** [comment]
OK, added in the missing `s`. How about I merge this and you check it tomorrow, with your `.bash_history` at hand? I'll leave the issue open.

**Comment by tschottdorf** [comment]
> ^ Is that a thing?

In Python2 it is 🤦‍♂️

**Comment by benesch** [comment]
What on earth. For the life of me I cannot reproduce this bug. I've tried with Python 3.5 on my local machine; I've tried on an actual TeamCity agent. But it's clearly real.

Given that this patch _also_ works on my machine, it's worth a shot. Godmerging.

**Comment by benesch** [comment]
It worked!

**Comment by benesch** [comment]
https://github.com/cockroachdb/cockroach/issues/23457

**Pull request merged**
