### PR TITLE
admission: add l0 control metrics

### PR DESCRIPTION
**Pull request by irfansharif**
Part of #82743.

We introduce metrics for l0 compacted bytes, generated l0 tokens, and l0 tokens returned.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109640)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @bananabrick, and @irfansharif)

___
*[`pkg/util/admission/grant_coordinator.go` line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109640#-Nd6FSbf2vR9wmRHl9s1:-Nd6FSbf2vR9wmRHl9s2:b-loukbh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c2ec63e8c5205c51d0aa587efcd6868c3d1b3c8/pkg/util/admission/grant_coordinator.go#L57)):*
> ```Go
> 	kvIOTokensAvailable             *metric.Gauge
> 	kvElasticIOTokensAvailable      *metric.Gauge
> 	kvIOTokensTookWithoutPermission *metric.Counter
> ```

Both the total tokens-taken and the tokens-without-permission metric are already quite broken
- The without permission case is not interesting, if one looks at the callers. We are granting 1 token in `tryGrant` and then using the return value to subtract the remaining. The latter is counted as took without permission, but not interesting, since we are subtracting immediately. What is more interesting is the `bypassed` case in `updateStoreStatsAfterWorkDone`, which could be captured in a metric but currently only in the logs. I think we should delete this metric.
- The total tokens taken is broken in that there are many callers to `subtractTokensLocked` that don't add or subtract from it. This is probably worth fixing. Is the reason for existence of the tokens-returned metric that we need to make each `metric.Counter` monotonic?
___
*[`pkg/util/admission/granter.go` line 468 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109640#-Nd6HTSq5NQtmu1lJiFo:-Nd6HTSq5NQtmu1lJiFp:b-pn06z7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c2ec63e8c5205c51d0aa587efcd6868c3d1b3c8/pkg/util/admission/granter.go#L468)):*
> ```Go
> 	sg.coordMu.availableElasticIOTokens -= elasticCount
> 	// Only update when not unlimited. Keep it whatever it was last otherwise.
> 	if sg.coordMu.availableIOTokens != unlimitedTokens {
> ```

- As mentioned earlier, and as you noticed, the instrumentation for tokens-taken was broken. Doing it in `subtractTokensLocked` is the right idea, except when the caller is `setAvailableTokens`.
- I don't understand this `unlimitedTokens` logic. I don't think it is going to work since even when there are `unlimitedTokens` for a 15s interval, we don't have `unlimitedTokens` for every tick, or for 250ms (since 250ms is what we use for computing the burst tokens). And I don't think it is needed since even if the available tokens is huge, here we are trying to count deductions and returns from the real work that is consuming tokens.
___
*[`pkg/util/admission/io_load_listener.go` line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109640#-Nd6Irnm3B6daXVPgwGp:-Nd6Irnm3B6daXVPgwGq:b-4r4ijs) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c2ec63e8c5205c51d0aa587efcd6868c3d1b3c8/pkg/util/admission/io_load_listener.go#L113)):*
> ```Go
> 
> // L0CompactionAlpha is the exponential smoothing term used when measuring L0
> // compactions, which in turn is used to generate IO tokens.
> ```

I'm not keen to make either of these cluster settings. What existing experimental evidence do we have for tweaking these?
Can we make this PR only about new metrics?
___
*[`pkg/util/admission/io_load_listener.go` line 1076 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109640#-Nd6K9bz3JRfLotF4gVU:-Nd6K9bz3JRfLotF4gVV:b-fgulc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c2ec63e8c5205c51d0aa587efcd6868c3d1b3c8/pkg/util/admission/io_load_listener.go#L1076)):*
> ```Go
> 			ib(m/adjustmentInterval))
> 		switch res.aux.tokenKind {
> 		case compactionTokenKind:
> ```

when `tokenKind` is `compactionTokenKind`, the value of `smoothedCompactionByteTokens` is the same as `totalNumByteTokens`, which we already print above.

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109640)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @bananabrick, and @sumeerbhola)

___
*[`pkg/util/admission/grant_coordinator.go` line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109640#-Nd6FSbf2vR9wmRHl9s1:-NdGq_86CISvO4jz7jVs:b2e0z4u) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c2ec63e8c5205c51d0aa587efcd6868c3d1b3c8/pkg/util/admission/grant_coordinator.go#L57)):*
> The without permission case is not interesting,

Agreed, removed. I've not been using it for the reasons you mentioned (+cc @bananabrick).

> Is the reason for existence of the tokens-returned metric that we need to make each `metric.Counter` monotonic? 

Yes.

> The total tokens taken is broken in that there are many callers to `subtractTokensLocked` that don't add or subtract from it.

I don't follow. I'm looking at the callers for subtractTokensLocked, and in each case, it seems valid to me to either increment the tokens-deducted metric (if subtracting a +ve amount, i.e. actually deducting) or the tokens-returned metric (when subtracting a -ve amount, i.e. returning).

Edit: Ah, you mean the use in setAvailableTokens. I was actually reading the usage wrong, so missed it. Fixed.
___
*[`pkg/util/admission/granter.go` line 468 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109640#-Nd6HTSq5NQtmu1lJiFo:-NdHIk1Z9rwDMzbvC3lI:b7nhxh1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c2ec63e8c5205c51d0aa587efcd6868c3d1b3c8/pkg/util/admission/granter.go#L468)):*
> Doing it in `subtractTokensLocked` is the right idea, except when the caller is `setAvailableTokens`.

Fixed, though awkwardly. But also not much more awkwardly than before.

> I don't understand this `unlimitedTokens` logic.

Hm, I don't know what I was thinking either, I must have been tired. I've removed it. It's annoying to use this metric since the scalar value can be so high, but in grafana you can just filter out datapoints less than some value, and it works well enough. I'll leave it unchanged.
___
*[`pkg/util/admission/io_load_listener.go` line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109640#-Nd6Irnm3B6daXVPgwGp:-NdHKXbF8PVCLmZFYuPG:b96d4nb) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c2ec63e8c5205c51d0aa587efcd6868c3d1b3c8/pkg/util/admission/io_load_listener.go#L113)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'm not keen to make either of these cluster settings. What existing experimental evidence do we have for tweaking these?
Can we make this PR only about new metrics?
</blockquote></details>

These were very handy in the MVCC GC experiments where we were running close to what we were able to compact out of the LSM pre MVCC GC and post MVCC GC we had enough compaction variability to affect foreground load. I can't find the experimental links to prove what I'm saying, but I've used this a lot. I'm inclined to keep it since these are private settings and I'm not changing the defaults. It does help in experiments when wanting to smooth over token calculations to paper over the current L0 compaction variability issues.
___
*[`pkg/util/admission/io_load_listener.go` line 1076 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109640#-Nd6K9bz3JRfLotF4gVU:-NdHUyiB150QHgWlji9R:bgzfug5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c2ec63e8c5205c51d0aa587efcd6868c3d1b3c8/pkg/util/admission/io_load_listener.go#L1076)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

when `tokenKind` is `compactionTokenKind`, the value of `smoothedCompactionByteTokens` is the same as `totalNumByteTokens`, which we already print above.
</blockquote></details>

Ack, removed but added a comment.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: modulo the comment about the settings.

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109640#-:-NdRfBTu6z3-_RnVHHHJ:bh11ida)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi, @bananabrick, and @irfansharif)

___
*[`pkg/util/admission/granter.go` line 378 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109640#-NdRc0Q5BI0vhP6Knlge:-NdRc0Q5BI0vhP6Knlgf:bmvb8ow) ([raw file](https://github.com/cockroachdb/cockroach/blob/99350f977eabd150ca2865e61d385255a7971778/pkg/util/admission/granter.go#L378)):*
> ```Go
> 	// granter was previously exhausted but is no longer so, we're allowed to
> 	// admit other waiting requests.
> 	additionalTokensTaken := cg.parent.storeReplicatedWorkAdmittedLocked(
> ```

nit: this change can be undone
___
*[`pkg/util/admission/granter.go` line 470 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109640#-NdRcL0qC_NT2Ey-U-2_:-NdRcL0qC_NT2Ey-U-2a:b-fj9hef) ([raw file](https://github.com/cockroachdb/cockroach/blob/99350f977eabd150ca2865e61d385255a7971778/pkg/util/admission/granter.go#L470)):*
> ```Go
> 			sg.tokensTakenMetric.Inc(count)
> 		} else {
> 			sg.tokensReturnedMetric.Inc(count)
> ```

shouldn't this be `-count`?
___
*[`pkg/util/admission/io_load_listener.go` line 902 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109640#-NdRdT0A7bu0ksj0CJ_1:-NdRdT0A7bu0ksj0CJ_2:bys0fcr) ([raw file](https://github.com/cockroachdb/cockroach/blob/99350f977eabd150ca2865e61d385255a7971778/pkg/util/admission/io_load_listener.go#L902)):*
> ```Go
> 	// Let C be smoothedIntL0CompactedBytes.
> 	//
> 	// Underload: Score is less than 0.5, which means sublevels is less than 5.
> ```

The commentary here and in the if-else blocks is based on these being constants, and would need updating.
I very much prefer taking out the settings change from this PR since it is ready to merge with the metrics changes, and I'm not quite convinced we need to make these configurable yet.
___
*[`pkg/util/admission/io_load_listener.go` line 1078 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109640#-NdReLcT5MlUqu9uD29X:-NdReLcT5MlUqu9uD29Y:b-pwmwyv) ([raw file](https://github.com/cockroachdb/cockroach/blob/99350f977eabd150ca2865e61d385255a7971778/pkg/util/admission/io_load_listener.go#L1078)):*
> ```Go
> 		case compactionTokenKind:
> 			// NB: res.smoothedCompactionByteTokens (printed above) is the same
> 			// as res.ioLoadListenerState.totalNumByteTokens when
> ```

nit: what we are printing above is `res.ioLoadListenerState.totalNumByteTokens`.
___
*[`pkg/util/admission/testdata/io_load_listener` line 665 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109640#-NdRedKF7KdEge14TuKr:-NdRedKF7KdEge14TuKs:b-bdxozd) ([raw file](https://github.com/cockroachdb/cockroach/blob/99350f977eabd150ca2865e61d385255a7971778/pkg/util/admission/testdata/io_load_listener#L665)):*
> ```
> ----
> compaction score 1.000 (10 ssts, 20 sub-levels), L0 growth 0 B (write 0 B ingest 0 B ignored 0 B): requests 0 (0 bypassed) with 0 B acc-write (0 B bypassed) + 0 B acc-ingest (0 B bypassed) + write-model 0.00x+0 B (smoothed 1.75x+1 B) + ingested-model 0.00x+0 B (smoothed 0.75x+1 B) + at-admission-tokens 1 B, compacted 0 B [≈30 KiB], flushed 0 B [≈0 B]; admitting 65 KiB (rate 4.3 KiB/s) (elastic 1 B rate 0 B/s) due to L0 growth (used total: 0 B elastic 0 B); write stalls 0
> {ioLoadListenerState:{cumL0AddedBytes:501000 curL0Bytes:10000 cumWriteStallCount:0 cumFlushWriteThroughput:{Bytes:0 WorkDuration:0 IdleDuration:0} diskBW:{bytesRead:0 bytesWritten:0 incomingLSMBytes:501000} smoothedIntL0CompactedBytes:31250 smoothedCompactionByteTokens:66406.375 smoothedNumFlushTokens:0 flushUtilTargetFraction:1.5 totalNumByteTokens:66406 byteTokensAllocated:0 byteTokensUsed:0 byteTokensUsedByElasticWork:0 totalNumElasticByteTokens:1 elasticByteTokensAllocated:0 elasticDiskBWTokens:9223372036854775807 elasticDiskBWTokensAllocated:0} requestEstimates:{writeTokens:1} l0WriteLM:{multiplier:1.75 constant:1} l0IngestLM:{multiplier:0.7505 constant:1} ingestLM:{multiplier:1 constant:1} aux:{intL0AddedBytes:0 intL0CompactedBytes:0 intFlushTokens:0 intFlushUtilization:0 intWriteStalls:0 prevTokensUsed:0 prevTokensUsedByElasticWork:0 tokenKind:0 perWorkTokensAux:{intWorkCount:0 intL0WriteBytes:0 intL0IngestedBytes:0 intLSMIngestedBytes:0 intL0WriteAccountedBytes:0 intIngestedAccountedBytes:0 intL0WriteLinearModel:{multiplier:0 constant:0} intL0IngestedLinearModel:{multiplier:0 constant:0} intIngestedLinearModel:{multiplier:0 constant:0} intBypassedWorkCount:0 intL0WriteBypassedAccountedBytes:0 intIngestedBypassedAccountedBytes:0 intL0IgnoredIngestedBytes:0} doLogFlush:true diskBW:{intervalDiskLoadInfo:{readBandwidth:0 writeBandwidth:0 provisionedBandwidth:0} intervalLSMInfo:{incomingBytes:0 regularTokensUsed:0 elasticTokensUsed:0}}} ioThreshold:<nil>}
> ```

did something about the switch from const 0.5 to a float64 caused these diffs?

**Review by irfansharif — COMMENTED** [review]
Yanked the cluster settings diffs out.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109640#-:-NdaNOet4SKpJ7fo63oe:bbhxxu0)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aadityasondhi, @bananabrick, and @sumeerbhola)

___
*[`pkg/util/admission/granter.go` line 470 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109640#-NdRcL0qC_NT2Ey-U-2_:-NdaLJkTEnDN9WFDziLk:bw10jn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/99350f977eabd150ca2865e61d385255a7971778/pkg/util/admission/granter.go#L470)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

shouldn't this be `-count`?
</blockquote></details>

Oops, done.
___
*[`pkg/util/admission/io_load_listener.go` line 902 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109640#-NdRdT0A7bu0ksj0CJ_1:-NdaMEpr2X6KetgV5rlP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/99350f977eabd150ca2865e61d385255a7971778/pkg/util/admission/io_load_listener.go#L902)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The commentary here and in the if-else blocks is based on these being constants, and would need updating.
I very much prefer taking out the settings change from this PR since it is ready to merge with the metrics changes, and I'm not quite convinced we need to make these configurable yet.
</blockquote></details>

Done.
___
*[`pkg/util/admission/testdata/io_load_listener` line 665 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109640#-NdRedKF7KdEge14TuKr:-NdaMG1k-y9N779Rkjxn:b-ts7w3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/99350f977eabd150ca2865e61d385255a7971778/pkg/util/admission/testdata/io_load_listener#L665)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

did something about the switch from const 0.5 to a float64 caused these diffs?
</blockquote></details>

Yes, but it's reverted now that I've pulled those changes out.

**Pull request merged**
