### PR TITLE
changefeedccl,jobspb: select initial scan timestamp on gateway

### PR DESCRIPTION
**Pull request by danhhz**
Fixes a buglet introduced in #28984 where each node in a distsql
changefeed flow would pick its own timestamp to do the initial scan at.

I thought I got all the backward-incompatible changes out of the way
with #27996 but I didn't forsee this one. While I'm making a
backward-incompatible change, switch targets from a `id->string` map to
an `id->proto` map for future expansion. Row and partition watches, for
example, will need this.

Release note (backward-incompatible change): CHANGEFEEDs created with
previous betas and alphas will not work with this version.

### CODE REVIEW

**Comment by danhhz** [comment]
paging @mrtracy

**Review by mrtracy — COMMENTED** [review]
I'm actually thinking that this won't just cause old CHANGEFEEDS to stop working, it might actually cause process crashes or panics because a proto message has been changed in a backwards incompatible way.  Is that acceptable for a beta release?  I'm not totally sure all of the places that particular message gets decoded, so maybe it's contained?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29402#-:-LL_b4d4BqnOKezc35Zn:b-2w81pm)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by danhhz — COMMENTED** [review]
That's not what I intended. What's backward incompatible? Not that I changed the field numbers

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29402#-:-LL_fm1TAlYLCyWGnYvj:b-88e0fs)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by danhhz — COMMENTED** [review]
*Note that

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29402#-:-LL_fvO4ETlv1xSkXPnn:b-rdrtww)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by mrtracy — COMMENTED** [review]
Crap, my bad, glossed right over that. This is LGTM then.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29402#-:-LL_h_Wu16jNz3Wknu3I:b-i560xl)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by mrtracy — APPROVED** [review]

**Review by danhhz — COMMENTED** [review]
You scared me, so I double checked what happens if someone makes a job entry on 2.0 and runs it on 2.1. Looks like `details.StatementTime` will be the zero value, which will return an error when fetching descriptors. The other way, targets will be empty (which is probably bad if we ever somehow see it, I'll make a note to add a check for it in validateDetails in a followup).

TFTR!

bors r=mrtracy

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29402#-:-LL_iheH0U0fStgC3Mm6:bi6g9z7)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by danhhz** [comment]
bors r=mrtracy

**Comment by danhhz** [comment]
resolved the merge conflict

bors r=mrtracy

**Pull request merged**
