### PR TITLE
storage: eager GC for replicas blocking snapshots

### LINKED ISSUE #8942: stability: investigate stale ranges and potential anomalies
Node4 of the rho cluster has a lot of ranges in the following states (shown here are 7 and 8):

screen shot 2016-08-30 at 10 01 53 am

(https://104.196.164.29:8080/#/raft/ranges?_k=k8qesb)

For both of them, Node4 is behind (in ReplicaID), indicating that these Replicas _should_ be GC'ed but aren't.

For the second line, the node4 replica is dormant, which explains why it's just sitting there (the GC queue is not very proactive about this sort of thing).

The logs have _a lot_ of refused snapshots, which makes sense if old ranges aren't getting GC'ed. We should (if we don't already) queue ranges which cause a snapshot to be refused more aggressively. Range 7 is definitely blocking incoming snapshots:

> cockroach@cockroach-rho-4:~$ grep 'intersects existing range' logs/cockroach.stderr | grep 'intersects existing range store=4:4 range=7 ' | wc -l
> 17345

It's entirely possible that there are more problems here, but they would likely get drowned out by the noise, so the above is a good first step to capture any more persistent issues here.

For RangeID=7, the situation appears that the last replica has moved to Node3 a while ago (which doesn't have it, but this could again be due to blocked snapshots).

### PR DESCRIPTION
**Pull request by petermattis**
Consider the following situation on a Range X:

- the range lives on nodes 1,2,3
- gets rebalanced to nodes 1,2,4 while node 3 is down
- node 3 restarts, but the (now removed) replica remains
- quiescent
- the range splits
- the right hand side of the split gets rebalanced to
- nodes 1,2,3.

In order to receive a snapshot for in the last step, node 3 needs to
have garbage-collected its old pre-split replica. If it weren't for node
3's downtime this would normally happen eagerly as its peers will inform
it of its fate. In this scenario however, one would have to wait until
a) a client request creates the Raft group (which is unlikely as it
isn't being addressed any more) or b) a queue picks it up (which can
take a long time).

Instead, when returning an overlap and the overlap appears to be
inactive, we add to the GC queue (which in turn activates the
replica). For the situation above, we could also hope to only create the
Raft group (as that would likely, but not necessarily, bring it into
contact with its ex-peers). However, none of the old members may still
be around in larger clusters, so going for the GC queue directly is the
better option.

Closes #8942

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10426)

### CODE REVIEW

**Comment by petermattis** [comment]
This is a based on @tschottdorf #8944 with the primary difference being the addition of a test exercising the scenario described in the commit message.

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/storage/client_raft_test.go, line 687 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10426#-KVc-RPirIUJdLVLevb4:-KVc-RPirIUJdLVLevb5:b-93wen1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f66401984cb61ce9fd647f98b8f70b65cf86641/pkg/storage/client_raft_test.go#L687)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 
> 	sc := storage.TestStoreConfig()
> ```

this needs a rebase

---

*[pkg/storage/client_raft_test.go, line 688 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10426#-KVc-yiMJnihrinijcDG:-KVc-yiMJnihrinijcDH:b-hxz6d2) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f66401984cb61ce9fd647f98b8f70b65cf86641/pkg/storage/client_raft_test.go#L688)):*
> ```Go
> 
> 	sc := storage.TestStoreConfig()
> 	sc.TestingKnobs.DisableReplicaGCQueue = true
> ```

deserves a comment

---

*[pkg/storage/client_raft_test.go, line 692 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10426#-KVc-UgULNl2c3iYF5Yp:-KVc-UgULNl2c3iYF5Yq:bmbjcon) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f66401984cb61ce9fd647f98b8f70b65cf86641/pkg/storage/client_raft_test.go#L692)):*
> ```Go
> 	mtc.Start(t, 3)
> 	defer mtc.Stop()
> 	rng1, err := mtc.stores[0].GetReplica(1)
> ```

s/rng/rep/

---

*[pkg/storage/client_raft_test.go, line 745 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10426#-KVc002sAx0UUovPe_eM:-KVc002tz62bUOKbBBW_:btqd6ew) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f66401984cb61ce9fd647f98b8f70b65cf86641/pkg/storage/client_raft_test.go#L745)):*
> ```Go
> 	expected := "snapshot intersects existing range"
> 	if err := replicateRange2(); !testutils.IsError(err, expected) {
> 		t.Fatalf("expected error, but found %v", err)
> ```

"unexpected error %v"?

---

*[pkg/storage/client_raft_test.go, line 747 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10426#-KVc04P0BDpENTvodFCs:-KVc04P0BDpENTvodFCt:bq8afnp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f66401984cb61ce9fd647f98b8f70b65cf86641/pkg/storage/client_raft_test.go#L747)):*
> ```Go
> 		t.Fatalf("expected error, but found %v", err)
> 	}
> 	mtc.stores[2].SetReplicaGCQueueActive(true)
> ```

comment?

---

*[pkg/storage/store.go, line 3516 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10426#-KVc-EFxSZC1vBLnIdBi:-KVc-EFxSZC1vBLnIdBj:blja7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f66401984cb61ce9fd647f98b8f70b65cf86641/pkg/storage/store.go#L3516)):*
> ```Go
> 					log.Errorf(ctx, "%s: unable to add replica to GC queue: %s", exReplica, err)
> 				} else {
> 					msg += "; initiated GC: "
> ```

remove space after the colon

---

*[pkg/storage/store.go, line 3520 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10426#-KVc-HITobuINo2SE3Rz:-KVc-HITobuINo2SE3S-:b-cr41gd) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f66401984cb61ce9fd647f98b8f70b65cf86641/pkg/storage/store.go#L3520)):*
> ```Go
> 			}
> 		}
> 		return nil, errors.Errorf("%s %v", msg, exReplica) // exReplica can be nil
> ```

verb for exReplica shouldn't have changed, should be %s still as it is elsewhere

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10426)*

**Comment by bdarnell** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10426#-:-KVdLjCPuIjIQyqv8BqN:bg7igkv)*

**Comment by tschottdorf** [comment]
I think you should make this close #8942.
:LGTM:

---

Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/storage/client_raft_test.go, line 684 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10426#-KVdtcFMtiYe_gOgkXAt:-KVdtcFMtiYe_gOgkXAu:b-dce9nu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f66401984cb61ce9fd647f98b8f70b65cf86641/pkg/storage/client_raft_test.go#L684)):*
> ```Go
> }
> 
> func TestReplicateAfterRemoveAndSplit(t *testing.T) {
> ```

Brief synopsis of the test would be good.

---

*[pkg/storage/client_raft_test.go, line 715 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10426#-KVdtS5BOVqbcOA3MK8e:-KVdtS5BOVqbcOA3MK8f:bm422lm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f66401984cb61ce9fd647f98b8f70b65cf86641/pkg/storage/client_raft_test.go#L715)):*
> ```Go
> 	mtc.restartStore(2)
> 
> 	replicateRange2 := func() error {
> ```

Shouldn't you look up the right hand side of the split's `RangeID` instead of making the assumption that it is going to be `2`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10426#-:-KVdsZBTYVJvFORvz9e5:bdziasw)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 9 unresolved discussions.

---

*[pkg/storage/client_raft_test.go, line 684 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10426#-KVdtcFMtiYe_gOgkXAt:-KVeBYsp-dLPHpuRJqqL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f66401984cb61ce9fd647f98b8f70b65cf86641/pkg/storage/client_raft_test.go#L684)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Brief synopsis of the test would be good.
</details>
Done.

---

*[pkg/storage/client_raft_test.go, line 687 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10426#-KVc-RPirIUJdLVLevb4:-KVeAEGbxdLxijXMlgif:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f66401984cb61ce9fd647f98b8f70b65cf86641/pkg/storage/client_raft_test.go#L687)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this needs a rebase
</details>
Done.

---

*[pkg/storage/client_raft_test.go, line 688 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10426#-KVc-yiMJnihrinijcDG:-KVeADvsZOW2mwxZH_vK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f66401984cb61ce9fd647f98b8f70b65cf86641/pkg/storage/client_raft_test.go#L688)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> deserves a comment
</details>
Done.

---

*[pkg/storage/client_raft_test.go, line 692 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10426#-KVc-UgULNl2c3iYF5Yp:-KVeADGMCKMxfmdbdTfC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f66401984cb61ce9fd647f98b8f70b65cf86641/pkg/storage/client_raft_test.go#L692)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/rng/rep/
</details>
Done.

---

*[pkg/storage/client_raft_test.go, line 715 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10426#-KVdtS5BOVqbcOA3MK8e:-KVeAFAXj9pz4Q9birda:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f66401984cb61ce9fd647f98b8f70b65cf86641/pkg/storage/client_raft_test.go#L715)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Shouldn't you look up the right hand side of the split's `RangeID` instead of making the assumption that it is going to be `2`?
</details>
Done.

---

*[pkg/storage/client_raft_test.go, line 745 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10426#-KVc002sAx0UUovPe_eM:-KVeAZZ5MyO1XT9vNym7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f66401984cb61ce9fd647f98b8f70b65cf86641/pkg/storage/client_raft_test.go#L745)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> "unexpected error %v"?
</details>
Done.

---

*[pkg/storage/client_raft_test.go, line 747 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10426#-KVc04P0BDpENTvodFCs:-KVeAiK0WW2-agkHQT_3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f66401984cb61ce9fd647f98b8f70b65cf86641/pkg/storage/client_raft_test.go#L747)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> comment?
</details>
Done.

---

*[pkg/storage/store.go, line 3516 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10426#-KVc-EFxSZC1vBLnIdBi:-KVeAojWnhyLq190BqjA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f66401984cb61ce9fd647f98b8f70b65cf86641/pkg/storage/store.go#L3516)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> remove space after the colon
</details>
Done.

---

*[pkg/storage/store.go, line 3520 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10426#-KVc-HITobuINo2SE3Rz:-KVeArKLsdg7dfjn-FGJ:b-auivpd) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f66401984cb61ce9fd647f98b8f70b65cf86641/pkg/storage/store.go#L3520)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> verb for exReplica shouldn't have changed, should be %s still as it is elsewhere
</details>
As the comment explains, `exReplica` can be `nil` which means we should use `%v`, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10426)*

**Comment by tschottdorf** [comment]
Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[pkg/storage/store.go, line 3520 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10426#-KVc-HITobuINo2SE3Rz:-KVeCAgWXBCQ10hn5MlV:bwvb7ie) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f66401984cb61ce9fd647f98b8f70b65cf86641/pkg/storage/store.go#L3520)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> As the comment explains, `exReplica` can be `nil` which means we should use `%v`, right?
</details>
Looks right to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10426)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/store.go, line 3520 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10426#-KVc-HITobuINo2SE3Rz:-KVecz-XN2SlLtdsWxPv:b-evu6k3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f66401984cb61ce9fd647f98b8f70b65cf86641/pkg/storage/store.go#L3520)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Looks right to me.
</details>
Duh. Sorry about that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10426#-:-KVed63gtSajvKa-xQ4T:bnfp4nl)*

**Pull request merged**
