### PR TITLE
sql: add support for COPY CSV

### LINKED ISSUE #51891: sql: add COPY ... CSV support
See comments in #8585

### PR DESCRIPTION
**Pull request by rafiss**
fixes #51891 
(Note from Rafi: I have resurrected Matt Jibson's old PR #52236) 

While here, add DELIMITER and NULL support to TEXT format as well. Test
all of this with some pgtests. We cannot use lib/pq or pgx because
neither of those support CSV. This also allows us to much more easily
compare error and other behavior against postgres.

Release note (sql change): add support for COPY CSV.

Release note (sql change): support specifying NULL and DELIMITER in COPY.

### CODE REVIEW

**Review by arulajmani — APPROVED** [review]
Thanks for resurrecting this.  

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59790#-:-MSiMPw90_2l-HIpKebw:bqaghve)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by rafiss** [comment]
tftr!

bors r=arulajmani

**Comment by ericharmeling** [comment]
@rafiss Does this fix https://github.com/cockroachdb/cockroach/issues/16407 too?

**Comment by rafiss** [comment]
Yes, DELIMITER and NULL were added too. I'll close that other issue.

**Pull request merged**
