### PR TITLE
tree: fix internal error in SOME, ANY, ALL expressions with the > operator

### LINKED ISSUE #85390: opt: internal error: lookup for ComparisonExpr
**Describe the problem**

Unexpected internal error.

**To Reproduce**

```sql
CREATE TABLE t0 (c0 INT);
SELECT * FROM t0 WHERE (ARRAY[] :::TIMETZ[] > SOME (NULLIF(ARRAY[TIMETZ '1969-12-29T21:20:13'], ARRAY[]), ARRAY[NULL])); -- internal error: lookup for ComparisonExpr ((ARRAY[])[string[]] > ANY (((ARRAY[('21:20:13+00:00:00')[timetz]])[timetz[]], (ARRAY[(NULL)[unknown]])[string[]]))[tuple{timetz[], string[]}])[bool]'s CmpOp failed
```

**Expected behavior**
No error.

**Additional data / screenshots**
```
ERROR: internal error: lookup for ComparisonExpr ((ARRAY[])[string[]] > ANY (((ARRAY[('21:20:13+00:00:00')[timetz]])[timetz[]], (ARRAY[(NULL)[unknown]])[string[]]))[tuple{timetz[], string[]}])[bool]'s CmpOp failed
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/expr.go:488: MemoizeComparisonExprOp()
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/expr.go:407: NewTypedComparisonExprWithSubOp()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar.go:442: buildAnyScalar()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar.go:98: buildScalar()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar.go:199: buildBoolean()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar.go:98: buildScalar()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar.go:168: buildBoolean()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar.go:98: buildScalar()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar.go:108: buildScalarWithMap()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:775: buildSelect()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:203: buildRelational()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go:253: build()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go:193: Build()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:632: runExecBuilder()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:293: makeOptimizerPlan()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1363: makeExecPlan()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1045: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:690: execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:145: execStmt()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1911: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1915: execCmd()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1837: run()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:778: ServeConn()
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:727: func1()
GOROOT/src/runtime/asm_amd64.s:1581: goexit()

HINT: You have encountered an unexpected error.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback.
```

**Environment:**
 - CockroachDB version [6374bd83f192bd509e50313acb431690b9c3f8ae]
 - Server OS: [Ubuntu 20.04]
 - Client app [`cockroach sql`]

**Additional context**
What was the impact?

Jira issue: CRDB-18223

### PR DESCRIPTION
**Pull request by msirek**
tree: fix asymmetric typing of > and < expressions
----
The expression `SELECT ARRAY[]::TIMESTAMPTZ[] < ARRAY[NULL];` returns
true, while `SELECT ARRAY[]::TIMESTAMPTZ[] > ARRAY[NULL];` errors with
"unsupported comparison operator: <timestamptz[]> > <string[]>".
This is due to asymmetric behavior in the overload type checker which
prefers to coerce expressions 2,3,4,etc. to the type of the first
expression. When the `>` expression is folded, it's converted to a
`<` expression with the inputs swapped, and type coercion is attempted
in the opposite direction.

The solution is to detect when type coercion in one direction succeeds
when the other direction fails, by calling `typeCheckSameTypedExprs` on
both orders, and initialize the overload type checker with the order which
succeeds.

Release note (bug fix): This patch fixes asymmetric typing of > and <
expressions which may cause erroring of expressions which are legal.

tree: fix internal error in SOME, ANY, ALL expressions with the > operator
----
An expression of the form `leftExpr > SOME(expr1, expr2, expr3...)`
may error out with an internal error while a similar expression,
`leftExpr < SOME(expr1, expr2, expr3...)` does not error out or returns
a sane, non-internal error message. The reason is that the overload type
checker is not symmetrical for type checking comparison expressions
involving tuples. `typeCheckTupleComparison` compares the left expression
with each tuple element, one-at-a-time. For each (left expression, tuple
element) pair, `typeCheckOverloadedExprs` is called to determine the common
type between them. If there is no type for the first expression passed as
a parameter to `typeCheckTupleComparison`, for example for expression `ARRAY[NULL]`,
we apply a desired type of `types.Any` to the expression here:
https://github.com/cockroachdb/cockroach/blob/ddb8efbca439de5698896e941bf96f139fa45849/pkg/sql/sem/tree/overload.go#L781

In this case, the resulting data type is STRING[]. This is no problem if the left
expression is typed first, but in the case of the `>` operation, when folding the
expression it is converted to a `<` operation, and the left and right expressions
are switched, causing the right expression to be typed before the left.

The solution is to specify via a parameter to `typeCheckComparisonOp` whether
the left and right expressions passed to `getOverloadTypeChecker` may be switched.
For SOME, ANY and ALL comparisons with a tuple on the right, switching is
disallowed, forcing the original left expression to be typed first.

Fixes #85390

Release note (bug fix): This patch fixes possible internal errors in SOME,
ANY and ALL expressions of the form: expr > SOME(expr1, expr2, expr3...)

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: 

Unfortunately, type-checking expressions of type tuple by deconstructing `tree.Tuple` expressions doesn't work when the expressions aren't `tree.Tuple`s. For example, this won't fix cases when the expression is a `CASE` expr of type tuple. We should still merge this, but we won't have complete fixes for all these tuple-typing issues until we rewrite the type-checking code to be independent of the `tree` AST types.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97022#-:-NOB1JO35Ku0xxNqImOV:b-9eh9ib)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Review by msirek — COMMENTED** [review]
Thanks for reviewing. Yeah, with the long history of changes, it seems like the code may be a bit fragile. I was looking for type checking interfaces that didn't modify the original expressions, because I was nervous about breaking things, but couldn't find any.

I've had to modify the fix slightly to handle, for example, tests like this:
```
build
SELECT 1 = ANY (1, 2, 3.3)
----
```
This would error out incorrectly because the code was requiring all tuple element types to be equivalent, and the decimal 3.3 is not equivalent.  The fix is to instead ensure the first expression argument to getOverloadTypeChecker is always the original left expression for ANY, ALL, SOME predicates (or any comparison expression with tuple elements on the right).

I had to also swap the order of the commits because now this changed fix builds upon the first commit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97022#-:-NOE-YDuCEI1gH5yakHl:b2efqw1)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2)

**Review by msirek — COMMENTED** [review]
TFTR!
bors r=mgartner

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97022#-:-NOGHkSl8-xoGbcJmfoU:b-psr8j3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2)

**Comment by yuzefovich** [comment]
Is this PR introducing a [flake](https://teamcity.cockroachdb.com/viewLog.html?buildId=8706158&buildTypeId=Cockroach_BazelEssentialCi) in `opt/memo/TestTyping`?
```
        -      └── (ARRAY['1969-12-29 21:20:13+01:00'], ARRAY[]) > (ARRAY['1969-12-29 21:20:13+01:00'], ARRAY[NULL]) [as="?column?":1, type=bool]
        +      └── (ARRAY['1969-12-29 21:20:13+01'], ARRAY[]) > (ARRAY['1969-12-29 21:20:13+01'], ARRAY[NULL]) [as="?column?":1, type=bool]
```

**Comment by msirek** [comment]
> Is this PR introducing a [flake](https://teamcity.cockroachdb.com/viewLog.html?buildId=8706158&buildTypeId=Cockroach_BazelEssentialCi) in `opt/memo/TestTyping`?

Thanks, I'll check it out. How did you notice the flake? Do you get e-mails from teamcity? Sometimes these are invisible to me.

**Comment by yuzefovich** [comment]
CI run on staging branch failed, and I had a PR in the bors batch, so I got an email about [this](https://github.com/cockroachdb/cockroach/pull/97125#issuecomment-1430303924).

**Comment by msirek** [comment]
bors r=mgartner

**Pull request merged**
