### PR TITLE
sql: distribute the plan for inverted filtering when possible

### PR DESCRIPTION
**Pull request by sumeerbhola**
The testing of this change is inadequate, since we can't use SPLIT AT
on an inverted index key.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50835)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_dist, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-MB5bfsF5g7LUMm5mnqM:-MB5bfsG7MRASV6MZw4I:brnvhky) ([raw file](https://github.com/cockroachdb/cockroach/blob/e286b3c027f1436228786c1525a917e3c71114f8/pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_dist#L27)):*
> ```
> # TODO(sumeer): this SPLIT point is bogus, since the first column in the inverted index
> # is a cellid (int). But we currently can't provide an int here since it gives us an
> # error: SPLIT AT data column 1 (geom) must be of type geometry, not type int.
> ```

Should I be trying to extend SPLIT AT and EXPERIMENTAL RELOCATE, and where is the relevant code?

Or is there a way to bypass the SQL layer and do some KV commands here to accomplish the same?

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50835)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @nvanbenschoten, @rytaft, and @sumeerbhola)

___
*[pkg/sql/distsql_physical_planner.go, line 2106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-MB5obWsDq258OefS64a:-MB5obWsDq258OefS64b:bzgbov) ([raw file](https://github.com/cockroachdb/cockroach/blob/e286b3c027f1436228786c1525a917e3c71114f8/pkg/sql/distsql_physical_planner.go#L2106)):*
> ```Go
> 
> 	distribute := false
> 	if n.expression.Left == nil && n.expression.Right == nil {
> ```

Can you expand on why we need to have this condition satisfied in order to allow for distribution? It'd be helpful have that commented in the code.
___
*[pkg/sql/distsql_physical_planner.go, line 2108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-MB5oFXz3uLoOcwOTDpe:-MB5oFY-Et60ghdLiZkH:bj62ats) ([raw file](https://github.com/cockroachdb/cockroach/blob/e286b3c027f1436228786c1525a917e3c71114f8/pkg/sql/distsql_physical_planner.go#L2108)):*
> ```Go
> 	if n.expression.Left == nil && n.expression.Right == nil {
> 		// Check if the previous stage is on multiple nodes.
> 		prevStageNode := plan.Processors[plan.ResultRouters[0]].Node
> ```

You can use `physicalplan.PhysicalPlan.IsLastStageDistributed` method for this.
___
*[pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_dist, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-MB5bfsF5g7LUMm5mnqM:-MB5pNZy-Ldoq4XiKb8F:b-fn4ta6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e286b3c027f1436228786c1525a917e3c71114f8/pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_dist#L27)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Should I be trying to extend SPLIT AT and EXPERIMENTAL RELOCATE, and where is the relevant code?

Or is there a way to bypass the SQL layer and do some KV commands here to accomplish the same?
</blockquote></details>

I think the relevant code is in `sql/split.go`, but this is the first time I'm looking at it, so I can't provide much help. Maybe @nvanbenschoten or @jordanlewis could share some knowledge here.
___
*[pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_dist, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-MB5py-F2LdjzPlN5vnX:-MB5py-F2LdjzPlN5vnY:br2wqp6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e286b3c027f1436228786c1525a917e3c71114f8/pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_dist#L55)):*
> ```
> 6
> 
> # If we change the code to make createPlanForInvertedFilter() take the distribute=true
> ```

We don't need to "force" to take the certain code path. We should have a noop processor on the gateway only if there is at least one processor in the input stage that is planned on a remote node.

**Review by rytaft — COMMENTED** [review]
I'm not familiar with this code but looks reasonable to me once you make the changes suggested by @yuzefovich 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-:-MB6UYYJ96xQ2PterpZN:b-5vgwsh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @nvanbenschoten, and @sumeerbhola)

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50835)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/sql/distsql_physical_planner.go, line 2105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-MB7SZ7g87DENjem6_CG:-MB7SZ7g87DENjem6_CH:b-z96254) ([raw file](https://github.com/cockroachdb/cockroach/blob/e286b3c027f1436228786c1525a917e3c71114f8/pkg/sql/distsql_physical_planner.go#L2105)):*
> ```Go
> 	}
> 
> 	distribute := false
> ```

We also actually need to change `checkSupportForPlanNode` accordingly.

**Review by sumeerbhola — COMMENTED** [review]
TFTR!
I've addressed the comments and also improved the distribution logic.

There are now two main issues:
- the decoding of the inverted column as geometry has come up again (see the comments in the testdata file): This is because the TableReader is being placed in two nodes and the invertedFilterer in one of those nodes (when the filterer is not distributable). If I change `checkSupportForPlanNode` to return `cannotDistribute` this goes away as the TableReader gets placed on the gateway node too. But even for non-distributable filterers, where the TableReader is on a single remote node (I think this will be common when the spans are narrow or the index is small), I do want to push the filterer to that remote node. Setting `cannotDistribute` seems to close of  that option by placing the TableReader at the gateway node. So is there a way I can prevent TableReaders from being remote only when the filterer is non-distributable and the TableReader spans include multiple nodes? Otherwise I think we need to fix the decoding problem.
- We need to de-dup the PKs for the distributed filtering, and not the Noop processor. How do I do that?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-:-MBA-rcLAcW1hEok6PSk:b-fcq3r8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @nvanbenschoten, @rytaft, and @yuzefovich)

___
*[pkg/sql/distsql_physical_planner.go, line 2105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-MB7SZ7g87DENjem6_CG:-MB9i9RM6sMwPVC2U90E:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e286b3c027f1436228786c1525a917e3c71114f8/pkg/sql/distsql_physical_planner.go#L2105)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

We also actually need to change `checkSupportForPlanNode` accordingly.
</blockquote></details>

Done
___
*[pkg/sql/distsql_physical_planner.go, line 2106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-MB5obWsDq258OefS64a:-MB9qOBy25J2erf1shjH:bsa6g98) ([raw file](https://github.com/cockroachdb/cockroach/blob/e286b3c027f1436228786c1525a917e3c71114f8/pkg/sql/distsql_physical_planner.go#L2106)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Can you expand on why we need to have this condition satisfied in order to allow for distribution? It'd be helpful have that commented in the code.
</blockquote></details>

Added a comment with cases and refined the placement logic (if the previous stage was on a single remote node, we should have been filtering there).
___
*[pkg/sql/distsql_physical_planner.go, line 2108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-MB5oFXz3uLoOcwOTDpe:-MB9nvBd6sNoaOqgXjpg:br6ociv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e286b3c027f1436228786c1525a917e3c71114f8/pkg/sql/distsql_physical_planner.go#L2108)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

You can use `physicalplan.PhysicalPlan.IsLastStageDistributed` method for this.
</blockquote></details>

That logic is slightly different since it is true if the number of processors > 1 or the single processor is not the gateway node.
Are there cases where there can be multiple processors but all at the same node? The updated logic handles that case by placing the filtering at that node.
___
*[pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_dist, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-MB5bfsF5g7LUMm5mnqM:-MB9r31nDlZtS-SeOr0x:b-kwzupu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e286b3c027f1436228786c1525a917e3c71114f8/pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_dist#L27)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think the relevant code is in `sql/split.go`, but this is the first time I'm looking at it, so I can't provide much help. Maybe @nvanbenschoten or @jordanlewis could share some knowledge here.
</blockquote></details>

Thanks. That turned out to be too late since the datums had already been validated, but it allowed me to find the relevant optimizer code. I've changed that to accept an int datum for geospatial inverted indexes and left a TODO for arrays.
___
*[pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_dist, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-MB5py-F2LdjzPlN5vnX:-MB9rVOx7W2xqjCFfQTB:b-mjlnfu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e286b3c027f1436228786c1525a917e3c71114f8/pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_dist#L55)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

We don't need to "force" to take the certain code path. We should have a noop processor on the gateway only if there is at least one processor in the input stage that is planned on a remote node.
</blockquote></details>

Ack. This comment was phrased unclearly -- removed.

**Review by yuzefovich — COMMENTED** [review]
> So is there a way I can prevent TableReaders from being remote only when the filterer is non-distributable and the TableReader spans include multiple nodes?

Yes, that decision can be made in `checkSupportForPlanNode`, I left a comment there as well. Rough outline of the physical process is that we first run `checkSupportForPlanNode` on the whole plan that returns a recommendation about plan's distribution, and then based on that recommendation we actually perform the physical planning. So, in that first check, if we encounter an intertedFilterNode that cannot be distributed for some reason, then the whole plan is not distributed and everything is planned on the gateway.

> We need to de-dup the PKs for the distributed filtering, and not the Noop processor. How do I do that?

Hm, one approach is to plan an existing `rowexec.distinct` processor. It would be scheduled on the gateway, and its input would be an unordered synchronizer that merges streams from all nodes. The downside of using distinct processor is that internally it uses a `map` which is not backed by a disk-spilling row container, so if we think that encoded primary key columns will be taking up a lot of space, this might be not ideal because we could hit a memory budget error (or even crash). However, it is a limitation of the processor, and I don't think we should be concerned about.

Another approach could be adding another "deduper" processor that would perform the de-duplication using the deduping disk-backed row container internally.

Maybe actually improving distinct processor to somehow fallback to using deduping row container would be a good thing to do.

Anyway, I think we should just plan a distinct processor for now.

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-:-MBAtHFo1nsJ-m4YL5a9:b-sylf8b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/sql/distsql_physical_planner.go, line 2108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-MB5oFXz3uLoOcwOTDpe:-MBAfFvh2xlzNzxotRfq:b-k1ruh7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e286b3c027f1436228786c1525a917e3c71114f8/pkg/sql/distsql_physical_planner.go#L2108)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

That logic is slightly different since it is true if the number of processors > 1 or the single processor is not the gateway node.
Are there cases where there can be multiple processors but all at the same node? The updated logic handles that case by placing the filtering at that node.
</blockquote></details>

Hm, I'm not sure whether we ever plan multiple processors that are part of the same stage on the same node, so I think this case is redundant, but let me ask around. Or maybe you've seen an example of such behavior?
___
*[pkg/sql/distsql_physical_planner.go, line 356 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-MBAd_By6cGvaHURqbT9:-MBAd_By6cGvaHURqbTA:bmp9ive) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a17f0f385afb33de7902cdcd868d839fdfdbedf/pkg/sql/distsql_physical_planner.go#L356)):*
> ```Go
> 
> 	case *invertedFilterNode:
> 		return shouldDistribute, nil
> ```

We need to call `checkSupportForPlanNode(n.input)` and compose the returned recommendation with `shouldDistribute` (similar to what we have in `groupNode` case above).
___
*[pkg/sql/distsql_physical_planner.go, line 2109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-MBAfjbSDBAxkBHsR2JN:-MBAfjbSDBAxkBHsR2JO:b-2yzmvk) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a17f0f385afb33de7902cdcd868d839fdfdbedf/pkg/sql/distsql_physical_planner.go#L2109)):*
> ```Go
> 	// - Last stage has multiple processors that are on different nodes:
> 	//   - Filtering is distributable: Distributable is true when the filtering
> 	//     is a union of inverted spans. Place an inverted filterer on each node,
> ```

nit: it is "a union of inverted spans" if `n.expression.Left == nil && n.expression.Right == nil`? If so, I'd mention it explicitly in the comment. Also, I see that there is `n.expression.SetOp`, can that be checked instead?
___
*[pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_dist, line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-MBAgQs_CCG-xhoFxn7d:-MBAgQs_CCG-xhoFxn7e:b6xyz9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a17f0f385afb33de7902cdcd868d839fdfdbedf/pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_dist#L19)):*
> ```
>   (6, 'POLYGON((1.0 1.0, 5.0 1.0, 5.0 5.0, 1.0 5.0, 1.0 1.0))')
> ```

nit: seems like an extra newline.
___
*[pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_dist, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-MBAhBOE-PibNiZzK8dJ:-MBAhBOE-PibNiZzK8dK:b-5j3mxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a17f0f385afb33de7902cdcd868d839fdfdbedf/pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_dist#L111)):*
> ```
> # also moves to node 2.
> statement ok
> ALTER INDEX geo_table@geom_index SPLIT AT VALUES (1)
> ```

Why do you add another split point? I think we could just relocate the first range, no? (By the way, IIUC you can use any key that belongs to the range in order to relocate it, so `ALTER INDEX geo_table@geom_index EXPERIMENTAL_RELOCATE VALUES (ARRAY[2], 1)` should still work without this split.)
___
*[pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_explain, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-MBAi-32DhlTb3eJ2s4I:-MBAi-32DhlTb3eJ2s4J:bm2jqji) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a17f0f385afb33de7902cdcd868d839fdfdbedf/pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_explain#L1)):*
> ```
> # LogicTest: local local-vec-off
> ```

nit: I'd probably add `_local` suffix to the filename.

**Review by sumeerbhola — COMMENTED** [review]
I've added a distinct processor (and changed the test so that it would produce a duplicate key prior to this fix).

Regarding the decision to distribute in `checkSupportForPlanNode`, it seems we are conflating placement with distribution/sharding. I may not be able to run the `InvertedFilterer` at every node, because it is not a union expression, but I would like to be able to place the `InvertedFilterer` at a remote node if there is a single `TableReader` at a remote node (likely to be common for small indexes or narrow spans). But the placement of the TableReaders is not known until later, when `planTableReaders` gets called. Which if why I am always setting `shouldDistribute`. And this would have worked if not for the inverted column decoding problem.

Are there other examples you are aware of where operators can't be distributed but placing them not on the gateway would be better? 

And related to this, if a planNode subtree was not distributable, does it condemn the whole query to run on the gateway? Say we executed a non-distributable inverted filter on one small table and a distributable aggregation on a huge table, and then joined the result, would the whole tree, including the aggregation, become non-distributable and run on the gateway?
       

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-:-MBGEkDj8iSu5mnkjZRO:b5lyed)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @nvanbenschoten, and @yuzefovich)

___
*[pkg/sql/distsql_physical_planner.go, line 2108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-MB5oFXz3uLoOcwOTDpe:-MBEpUNaBU27pG00OxoQ:b-dkqag7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e286b3c027f1436228786c1525a917e3c71114f8/pkg/sql/distsql_physical_planner.go#L2108)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Hm, I'm not sure whether we ever plan multiple processors that are part of the same stage on the same node, so I think this case is redundant, but let me ask around. Or maybe you've seen an example of such behavior?
</blockquote></details>

I've not seen an example, but there is similar logic in `planAggregators` https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/distsql_physical_planner.go#L1375-L1382
___
*[pkg/sql/distsql_physical_planner.go, line 356 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-MBAd_By6cGvaHURqbT9:-MBG9VKh7wAvBOvI7683:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a17f0f385afb33de7902cdcd868d839fdfdbedf/pkg/sql/distsql_physical_planner.go#L356)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

We need to call `checkSupportForPlanNode(n.input)` and compose the returned recommendation with `shouldDistribute` (similar to what we have in `groupNode` case above).
</blockquote></details>

Done.
___
*[pkg/sql/distsql_physical_planner.go, line 2109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-MBAfjbSDBAxkBHsR2JN:-MBGAC-hEOQ2ZxzaJ7jQ:b-gaklek) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a17f0f385afb33de7902cdcd868d839fdfdbedf/pkg/sql/distsql_physical_planner.go#L2109)):*
> nit: it is "a union of inverted spans" if n.expression.Left == nil && n.expression.Right == nil?

Correct

> If so, I'd mention it explicitly in the comment.

Good point -- I've added a comment below where `distributable` is computed.

> Also, I see that there is n.expression.SetOp, can that be checked instead?

That is only used when the `Left` and `Right` are not `nil`.
___
*[pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_dist, line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-MBAgQs_CCG-xhoFxn7d:-MBGA_MZ69v2UfOztu61:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a17f0f385afb33de7902cdcd868d839fdfdbedf/pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_dist#L19)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: seems like an extra newline.
</blockquote></details>

Done
___
*[pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_dist, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-MBAhBOE-PibNiZzK8dJ:-MBGBHf065U6bhdLs8bt:b-nx44lu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a17f0f385afb33de7902cdcd868d839fdfdbedf/pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_dist#L111)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Why do you add another split point? I think we could just relocate the first range, no? (By the way, IIUC you can use any key that belongs to the range in order to relocate it, so `ALTER INDEX geo_table@geom_index EXPERIMENTAL_RELOCATE VALUES (ARRAY[2], 1)` should still work without this split.)
</blockquote></details>

Ah, I thought it was only the start key, and using `NULL` did not do anything. Thanks. Fixed.
___
*[pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_explain, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-MBAi-32DhlTb3eJ2s4I:-MBG93ZF20-l6FBZM-dq:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a17f0f385afb33de7902cdcd868d839fdfdbedf/pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_explain#L1)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: I'd probably add `_local` suffix to the filename.
</blockquote></details>

Done

**Review by yuzefovich — COMMENTED** [review]
> it seems we are conflating placement with distribution/sharding

Yeah, good point. The thing is that with the old `execFactory` + distsql physical planner we only have two possibilities: either the whole plan is "distributable" (which means that all of the stages of the processors can be distributed, and for every stage we make an independent "smart" decision about the placement of the processors), or is "local" (meaning that at least one stage of the processors cannot be distributed). If the plan is local, then everything is scheduled on the gateway.

> I would like to be able to place the InvertedFilterer at a remote node if there is a single `TableReader` at a remote node.

Ack, however, with the old factory we cannot express such a physical plan. So I think the correct way to proceed for now is to return `cannotDistribute` in `checkSupportForPlanNode` when the inverted filterer cannot be distributed and leave a TODO to be addressed once we implement the corresponding methods in the new `distSQLSpecExecFactory`.

With your example of a single remote table reader I think the expected physical plan for now is to actually have a single table reader on the gateway that will be receiving the unencoded data from the remote node (down at the KV level) and then pushing the data to the local inverted filterer. This should go around the encoding problem, I think.

> Are there other examples you are aware of where operators can't be distributed but placing them not on the gateway would be better?

I don't think we have any precedent for such case yet due to the limitations of `execFactory` + distsql physical planner I alluded to above.

> And related to this, if a planNode subtree was not distributable, does it condemn the whole query to run on the gateway?  Say we executed a non-distributable inverted filter on one small table and a distributable aggregation on a huge table, and then joined the result, would the whole tree, including the aggregation, become non-distributable and run on the gateway?

With the old `execFactory` (the one in which you've implemented the corresponding `Construct*` methods), yes to both questions. But with the new `distSQLSpecExecFactory` I'm currently working on, the answer is no.

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-:-MBKug9K3JTgOwcOXx2D:b-svgxuh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/sql/distsql_physical_planner.go, line 2108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-MB5oFXz3uLoOcwOTDpe:-MBKo_THA4GbdVSSeMLY:b-bxa13l) ([raw file](https://github.com/cockroachdb/cockroach/blob/e286b3c027f1436228786c1525a917e3c71114f8/pkg/sql/distsql_physical_planner.go#L2108)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I've not seen an example, but there is similar logic in `planAggregators` https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/distsql_physical_planner.go#L1375-L1382
</blockquote></details>

I think the planning logic in `planAggregators` was written in the very early days of our distributed SQL execution, and it was probably thought that we would be planning multiple processors for the same stage on the same node in order to get the benefits of the parallelization. However, we don't actually do that currently, so I would not add the logic for handling such case here. If one day this changes, the whole file will need to be updated accordingly.

**Review by sumeerbhola — COMMENTED** [review]
Thanks for the detailed explanation. I've changed the code accordingly and added a TODO.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-:-MBZ4-1gElwbb7wg41kp:b-kcwvnt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @nvanbenschoten, and @yuzefovich)

___
*[pkg/sql/distsql_physical_planner.go, line 2108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-MB5oFXz3uLoOcwOTDpe:-MBZ6Dy18jnHfxvWMwPH:bc78xff) ([raw file](https://github.com/cockroachdb/cockroach/blob/e286b3c027f1436228786c1525a917e3c71114f8/pkg/sql/distsql_physical_planner.go#L2108)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think the planning logic in `planAggregators` was written in the very early days of our distributed SQL execution, and it was probably thought that we would be planning multiple processors for the same stage on the same node in order to get the benefits of the parallelization. However, we don't actually do that currently, so I would not add the logic for handling such case here. If one day this changes, the whole file will need to be updated accordingly.
</blockquote></details>

This is very helpful. I've simplified the logic here.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-:-MBZsQBx7gOCXJ7XODZC:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/sql/distsql_physical_planner.go, line 2287 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-MBZryFaE1eVIi_nYjdL:-MBZryFaE1eVIi_nYjdM:bgxdl6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d2fd292f8ab69b6f3d9fc24f391369ba7b83371/pkg/sql/distsql_physical_planner.go#L2287)):*
> ```Go
> 		return plan, nil
> 	}
> 	// Must be distributable
> ```

nit: missing period.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50835)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @nvanbenschoten, and @yuzefovich)

___
*[pkg/sql/distsql_physical_planner.go, line 2287 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50835#-MBZryFaE1eVIi_nYjdL:-MB_MzzwD7u54fiEWIz3:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d2fd292f8ab69b6f3d9fc24f391369ba7b83371/pkg/sql/distsql_physical_planner.go#L2287)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: missing period.
</blockquote></details>

Done

**Pull request merged**
