### PR TITLE
sql: move some logic to newly created packages

### PR DESCRIPTION
**Pull request by ZhouXing19**
This commit creates 
1. a new package `sql/clustermode` to store cluster mode related info.
2. a new package `sql/sessiondatautil` to store the original `sql.NewFakeSessionData()` function.
3. a new package `jobs/jobrecords` to store interfaces for `jobs.Record`. They are created only to avoid cyclic dependency in future usages.

### CODE REVIEW

**Comment by ajwerner** [comment]
I'm rather negative on this approach. I don't think you need it. Not everything touching the `InternalExecutor` needs to be represented in `sqlutil`. Indeed, it'd be better if the construction mechanisms didn't exist anywhere except `sql` and `descs` as we last discussed.

**Comment by ZhouXing19** [comment]
> I don't think you need this. Not everything touching the `InternalExecutor` needs to be represented in `sqlutil`. Let's see if we can work it such that the relevant mechanisms didn't exist anywhere except `sql` and `descs`. As in, the planner can create its associated `InternalExecutor` and the `descs.CollectionFactory` gets built with the dependency it needs to create one as well. These constructors or factories or whatever we call them don't need to appear in the `sqlutil` package anywhere, do they?

Not sure if I understood it correctly but do you mean that we should move the declaration of internal executor factories (I.e. `type InternalExecutorFactory func(...)`) to only under `sql` (for planner) or `descs` (for CollectionFactory) packages? I feel nervous about that because the field declaration using `sqlutil.InternalExecutorFactory` are in multiple packages (e.g. `jobs`, `server`, `descmetadata` , `execinfra`, `schemachanger` and etc.).  And I'm afraid that importing `sql` or `descs` in these packages will bring cyclic dependency.

**Comment by ZhouXing19** [comment]
Also, another risk is that if we replace `sqlutil.InternalExecutorFactory` now with a new `descs.InternalExecutorFactoryWithTxn`, we will have to deprecate a large number of usages of internal executor. It makes me nervous that this will lead to an unclear timeline for this project, given the time we have spent on it.

**Comment by ZhouXing19** [comment]
This PR is no longer needed.

**Pull request closed without merging**
