### PR TITLE
roachtest: add `UploadCockroach` and `UploadWorkload` APIs

### LINKED ISSUE #114518: roachtest: provide higher level API to upload different versions of `workload` binary
Currently, if a test (especially an upgrade one) wants to use a `workload` binary built on a different release branch, it needs to manually compute the corresponding release branch name and call `c.Stage`. Ideally, it would also download the file in a separate directory to avoid overwriting any existing `./workload` binaries in the VMs.

There is already a function that does all of this for `cockroach` releases: `clusterupgrade.UploadVersion` [1]. We can either update this function or create a new one so that it will also work for `workload`.

Fixing this issue would also involve updating the `schemachange/mixed-versions` roachtest (see #113890) so that we are able to stage different `workload` binaries while running the schemachange workload, thus removing the `MaxUpgrades(1)` option from that test. `acceptance/version-upgrade` would also use this change.

[1] https://github.com/cockroachdb/cockroach/blob/bab4335ba1c1d948f08c1e993a7407b23c6d4021/pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go#L126-L136

Jira issue: CRDB-33540

### PR DESCRIPTION
**Pull request by renatolabs**
**roachtest: add `UploadCockroach` and `UploadWorkload` APIs**

This commit updates the `clusterupgrade` package to provide functions to allow tests to upload arbitrary versions of `cockroach` and `workload` binaries.

Previously, the `UploadVersion` function was focused only on cockroach binaries. With recent focus in upgrade testing, we would like to be able to stage different versions of the `workload` binary during tests as well. This will be especially useful for the `schemachange` workload, since it only supports interactions between the current and the previous version.

Fixes: #114518.

Release note: None

**roachtest: use UploadWorkload API in acceptance/version-upgrade**

This commit makes use of the recently introduced `UploadWorkload` API
to upload a `workload` binary for a specific version. In this test, we
use a version that should be compatible with the upgrade currently
being performed.

Epic: none

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
Mixed-version tests on this branch:
https://teamcity.cockroachdb.com/viewLog.html?buildId=12831217&tab=queuedBuildOverviewTab

Also ran `acceptance/version-upgrade` 10 times on my gceworker.

**Review by DarrylWong — APPROVED** [review]
Left one small suggestion that's up to you if you if you think is any cleaner + one question for myself, but otherwise LGTM!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115061#-:-NkW-2Ye37_6OUpsf4kE:b59zdt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

___
*[`pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go` line 179 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/115061#-NkVxzUx8V_IQ1ZSKwav:-NkVxzUx8V_IQ1ZSKwaw:b-kmk8q3) ([raw file](https://github.com/cockroachdb/cockroach/blob/637c0dd0e0ba80a37ff8d332c8dc33da36ad9494/pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go#L179)):*
> ```Go
> 
> 	overrideBinary, isOverriden := t.VersionsBinaryOverride()[v.String()]
> 	isOverriden = isOverriden && binary == "cockroach"
> ```

I think it's fine as is, but if you wanted to get rid of this line you could just move the `isOverriden` logic to the switch case above. Would maybe make it more clear it's a cockroach binary only thing too?

i.e. something like:



_Code snippet:_
```Go
switch binary {
	case "cockroach":
		overrideBinary, isOverriden := t.VersionsBinaryOverride()[v.String()]
		if isOverriden {
			l.Printf("using cockroach binary override for version %s: %s", v, overrideBinary)
			if err := c.PutE(ctx, l, overrideBinary, dstBinary, nodes); err != nil {
				return "", err
			}
			return dstBinary, nil
		}

		// Run with standard binary as older versions retrieved through roachprod stage
		// are not currently available with crdb_test enabled.
		// TODO(DarrylWong): Compile older versions with crdb_test flag.
		defaultBinary = t.StandardCockroach()
```
___
*[`pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go` line 193 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/115061#-NkW-rnC2DSEnMlsOwnC:-NkW-rnD1HJ_CRYko4py:b38udb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/637c0dd0e0ba80a37ff8d332c8dc33da36ad9494/pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go#L193)):*
> ```Go
> 		// Avoid staging the binary if it already exists.
> 		if err := c.RunE(ctx, nodes, "test -e", dstBinary); err == nil {
> 			return dstBinary, nil
> ```

Looks like before we were erroring out in this case. I think this change should be okay but I'm curious if there is a test that ever expects to upload the same binaryPath twice? If no then I'm wondering if we would rather it just fail fast here. 

Or maybe I'm just misunderstanding what the old `"test -e %s || mkdir -p %s"` command did :thinking:

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115061)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong and @herkolategan)

___
*[`pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go` line 179 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/115061#-NkVxzUx8V_IQ1ZSKwav:-NkX4VGF-QKQ3qgYHFUW:bfay97h) ([raw file](https://github.com/cockroachdb/cockroach/blob/637c0dd0e0ba80a37ff8d332c8dc33da36ad9494/pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go#L179)):*
<details><summary><i>Previously, DarrylWong wrote…</i></summary><blockquote>

I think it's fine as is, but if you wanted to get rid of this line you could just move the `isOverriden` logic to the switch case above. Would maybe make it more clear it's a cockroach binary only thing too?

i.e. something like:
</blockquote></details>

Good suggestion, I like the idea of computing the override binary in the switch, done.

Note that I wasn't a huge fan of putting `PutE` there as well -- it's nice to have the switch purely computing paths, and having the `PutE` after (at least it reads a little better in my opinion).
___
*[`pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go` line 193 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/115061#-NkW-rnC2DSEnMlsOwnC:-NkX4rwCCVaPUqCjSLNh:b-fpebge) ([raw file](https://github.com/cockroachdb/cockroach/blob/637c0dd0e0ba80a37ff8d332c8dc33da36ad9494/pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go#L193)):*
> Looks like before we were erroring out in this case

I don't think so, no error would be returned if the binary existed previously. What would happen is that we would re-upload the same binary again. The change in this PR is that we don't re-upload if the file already exists.

> curious if there is a test that ever expects to upload the same binaryPath twice?

I hope not, and runs of mixed-version tests on this branch I have done so far have succeeded. If there _was_ a test that relied on this, we should probably update the test instead. IMO, there's a somewhat strong expectation (that is pretty valid) that `./cockroach` is the current cockroach binary, built on the SHA being tested. It also makes sense that `vXX.X.X/cockroach` is exactly the cockroach binary for that version; it would be confusing if it were anything else.

**Review by DarrylWong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115061)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

___
*[`pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go` line 179 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/115061#-NkVxzUx8V_IQ1ZSKwav:-NkX73rG2zVxLG5oWkjl:bn3a1rq) ([raw file](https://github.com/cockroachdb/cockroach/blob/637c0dd0e0ba80a37ff8d332c8dc33da36ad9494/pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go#L179)):*
>it's nice to have the switch purely computing paths

Seems like sound logic to me, i'm convinced :thumbsup: 
___
*[`pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go` line 193 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/115061#-NkW-rnC2DSEnMlsOwnC:-NkX8Zxk1F44OPUUIKCV:b-cm4z8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/637c0dd0e0ba80a37ff8d332c8dc33da36ad9494/pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go#L193)):*
> no error would be returned if the binary existed previously

Ahh okay nevermind, I reread it a couple of times and got it now. I had the return value of test flipped in my mind :smile: 

> If no then I'm wondering if we would rather it just fail fast here.

Responding to myself here, but I see now that we wouldn't want to do this because `./cockroach` is already staged. Given that I think you can disregard my original comment, thanks for clarifying though!

**Comment by renatolabs** [comment]
TFTR!

bors r=DarrylWong

**Pull request merged**
