### PR TITLE
storage: split up store.go

### PR DESCRIPTION
**Pull request by ajwerner**
store.go is getting quite large and can benefit from some logical decomposition.
This PR is just code movement. It creates 6 new files in the storage package
from store.go:

    store_create_replica.go - deals with creating replicas, especially
        getOrCreateReplica().
    store_remove_replica.go - deals with removing replicas.
    store_raft.go - deals with the events from the scheduler and the raft
        transport.
    store_split.go - deals with the splitting ranges.
    store_merge.go - deals with merging ranges.
    store_send.go - Store.Send() and its helpers.

I'm also not particularly committed to splitting it up exactly
like this, just wanted to do something.

Release justification: Just code movement, better to do it before the release
for the sake of future backports.

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
@tbg @nvanbenschoten @bdarnell store.go was getting a bit too big for my liking so I typed this up. Take it or leave it.

**Comment by tbg** [comment]
Yeah, it seems wise to do this right now. We always have trouble finding a good point in time do to such pervasive low-risk refactors. I'm in favor.

PS you need to goimports some new files:

```
pkg/storage/store_create_replica.go:38:10: undefined: errors
pkg/storage/store_create_replica.go:41:10: undefined: errors
pkg/storage/store_create_replica.go:69:16: undefined: errors
pkg/storage/store_create_replica.go:226:29: undefined: errors
pkg/storage/store_merge.go:33:10: undefined: errors
pkg/storage/store_merge.go:74:10: undefined: errors
pkg/storage/store_raft.go:34:30: undefined: raftpb
pkg/storage/store_raft.go:51:7: undefined: raftpb
pkg/storage/store_raft.go:62:10: undefined: raftpb
pkg/storage/store_raft.go:107:74: undefined: raftpb
pkg/storage/store_raft.go:107:74: too many errors
```

**Comment by bdarnell** [comment]
Splitting up a file but keeping the pieces within the same package seems safe enough to me, so I'm OK with this going in as soon as your other big store.go PR lands. Probably better to get it in before the branch for ease of backporting. 

One thing to watch out for is we have a few similarly-named packages and goimports sometimes picks up the wrong one (especially for `errors` and `log`). We should verify that the imports of each new file are a subset of the imports of the original store.go.

**Comment by nvanbenschoten** [comment]
I'm on board with this as well.

**Comment by ajwerner** [comment]
> One thing to watch out for is we have a few similarly-named packages and goimports sometimes picks up the wrong one (especially for errors and log). We should verify that the imports of each new file are a subset of the imports of the original store.go.

Yep, this time around I copied the entire import block from store.go into the new files before letting goimports run.

**Comment by tbg** [comment]
PRs that touch storage are about to merge -- I'm going to take the liberty to get this in, once you start having to rebase this PR our confidence that it's just pure code movement will vanish.

bors r+

**Comment by tbg** [comment]
```
panic: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.0.53:53: read udp 127.0.0.1:58936->127.0.0.53:53: read: connection refused [recovered]
```

bors r+

**Comment by ajwerner** [comment]
> PRs that touch storage are about to merge -- I'm going to take the liberty to get this in, once you start having to rebase this PR our confidence that it's just pure code movement will vanish.


Thank you

**Pull request merged**
