### PR TITLE
storage/engine: centralize specification of pebble.Options

### LINKED ISSUE #41860: storage/engine: centralize specification of pebble.Options
The `pebble.Options` used by CRDB are currently specified in two places: `server/config.go` and `storage/engine/bench_pebble_test.go`. The former is used by the cockroach process and the latter by benchmarks. We also specify the comparer and merger in `storage/engine/pebble.go`. And #41854 adds support for specifying the table property collectors. As cleanup, we should centralize where the Pebble options are specified to `storage/engine/pebble.go` to ensure we're using the same options everywhere.

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #41860

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
Only look at the last commit. The first 2 commits are from #41839.

**Review by petermattis — COMMENTED** [review]
Ping. This is a straightforward PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41901#-:-LsMdAl0C0gfwuV1K9SA:bep41nf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @sumeerbhola)

**Review by sumeerbhola — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41901)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/server/config.go, line 514 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41901#-LsMjO-Q64Irp2A86NQm:-LsMjO-Q64Irp2A86NQn:b-swnsuy) ([raw file](https://github.com/cockroachdb/cockroach/blob/a57647381a4714b48f6ec6dec0bf766eaa6746dd/pkg/server/config.go#L514)):*
> ```Go
> 							BlockSize: 32 << 10,
> 						}},
> 					},
> ```

there are multiple configuration values we pass to RocksDB but not to Pebble -- ignoring the `ExtraOptions` and `FileRegistry` which are encryption related I see `sizeInBytes`, `spec.Attributes`,  `cfs.Settings`. Why the difference?

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41901)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @sumeerbhola)

___
*[pkg/server/config.go, line 514 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41901#-LsMjO-Q64Irp2A86NQm:-LsMkgPk00z8TEdPTQit:b-gac9hc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a57647381a4714b48f6ec6dec0bf766eaa6746dd/pkg/server/config.go#L514)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

there are multiple configuration values we pass to RocksDB but not to Pebble -- ignoring the `ExtraOptions` and `FileRegistry` which are encryption related I see `sizeInBytes`, `spec.Attributes`,  `cfs.Settings`. Why the difference?
</blockquote></details>

`ExtraOptions` are encryption-at-rest options which you'll be implementing shortly. We do pass `spec.Attributes` and `Settings` (the latest commit is passing them in `engine.StorageConfig`. I'm not sure about `sizeInBytes`. Let me investigate.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41901)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @sumeerbhola)

___
*[pkg/server/config.go, line 514 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41901#-LsMjO-Q64Irp2A86NQm:-LsMlIBd87FHQ0WoNASA:b-nvkied) ([raw file](https://github.com/cockroachdb/cockroach/blob/a57647381a4714b48f6ec6dec0bf766eaa6746dd/pkg/server/config.go#L514)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`ExtraOptions` are encryption-at-rest options which you'll be implementing shortly. We do pass `spec.Attributes` and `Settings` (the latest commit is passing them in `engine.StorageConfig`. I'm not sure about `sizeInBytes`. Let me investigate.
</blockquote></details>

`sizeInBytes` seems to be an oversight. I've added another commit which plumbs it through, as well as does as small bit of cleanup for `StorageConfig`. PTAL.

**Review by sumeerbhola — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41901)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/pebble.go, line 409 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41901#-LsN29fr0LfKR0rtg2Ha:-LsN29fsDykqsONGmQvZ:bjjcert) ([raw file](https://github.com/cockroachdb/cockroach/blob/f31ecd323eb86f36e35ffd82b69164f244da6fc2/pkg/storage/engine/pebble.go#L409)):*
> ```Go
> func (p *Pebble) Capacity() (roachpb.StoreCapacity, error) {
> 	// Pebble doesn't have a capacity limiting parameter, so pass 0 for
> 	// maxSizeBytes to denote no limit.
> ```

comment is stale

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41901)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @sumeerbhola)

___
*[pkg/storage/engine/pebble.go, line 409 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41901#-LsN29fr0LfKR0rtg2Ha:-LsN3Y0w1O4_mcqTnb6q:b9cql6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/f31ecd323eb86f36e35ffd82b69164f244da6fc2/pkg/storage/engine/pebble.go#L409)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

comment is stale
</blockquote></details>

Thanks. Fixed.

**Comment by petermattis** [comment]
TFTR!

bors r+

**Pull request merged**
