### PR TITLE
docs: add volatility to built-in functions table

### PR DESCRIPTION
**Pull request by mgartner**
#### sql: make "leakproof" one word

In Postgres's documentation "leakproof" is one, non-hyphenated word.
This commit updates all occurrences of the word to a single word.

Release note: None

#### docs: add volatility to built-in functions table

Release note: None

### CODE REVIEW

**Comment by stbof** [comment]
I recommend adding a section to the functions and operators page and link the headings to that. I do wonder a little about the naming of the volatility values. Leakproof makes sense from an engineering POV, but may not be the best name to expose publicly.  I see 26 matches.  If you keep it I recommend spelling it w/out the hyphen.I notice that Postgres doesn't support that value...

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83331#-:-N5Lsp_06oNbjOFD7D43:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @stbof)

**Comment by mgartner** [comment]
@stbof updated "leakproof" to be one word, and I titled cased the volatilities in the table. Let me know what you think.

**Review by ghost — APPROVED** [review]

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
