### PR TITLE
builder: upgrade to go1.10.7

### LINKED ISSUE #33169: build: Update to Go 1.10.6
The newly released go 1.10.6 has a fix for quadratic behavior in certificate validation. This is a potential DoS vector for CRDB clusters exposed to hostile networks. We should use this version of go in our next patch releases.

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #33169

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
The images is still being pushed to dockerhub, but it should be there soon. I'll hold off on merging this until after Monday. We'll need to backport this to the 2.1 release branch. Was 2.0 built with 1.10?

**Comment by petermattis** [comment]
Ha, I just saw the announcement about 1.10.7. Probably not important for our builder image, but I might as well switch to it.

**Comment by petermattis** [comment]
We should also consider bumping to go1.11.4 for master. Nikhil's fix for the race detector is in that release, so I believe there is nothing prohibiting us from upgrading now.

**Review by benesch — APPROVED** [review]
LGTM!

**Review by bdarnell — APPROVED** [review]

**Comment by petermattis** [comment]
bors r=bdarnell,benesch

**Pull request merged**
