### PR TITLE
deps: rename/upgrade xdg/scram -> xdg-go/scram

### PR DESCRIPTION
**Pull request by knz**
Prereq for #74301

Release note: None

### CODE REVIEW

**Review by shermanCRL — APPROVED** [review]
Anything interesting here @HonoreDB?

**Comment by knz** [comment]
Thanks matt.
If my reading is right, nothing changed in the upstream package besides the naming.

bors r=shermanCRL

**Review by rafiss — APPROVED** [review]
lgtm; but merge conflicts already cropped up

**Comment by knz** [comment]
thanks!

bors r=rafiss,shermanCRL

**Comment by rickystewart** [comment]
Pretty weird to me there are no changes to `DEPS.bzl` from this change, did you `dev generate bazel --mirror`?

**Comment by knz** [comment]
> Pretty weird to me there are no changes to DEPS.bzl from this change, did you dev generate bazel --mirror?

The new dependency was already mirrored somehow. I wasn't able to understand why, but it's there.

**Comment by knz** [comment]
@rickystewart that reminds me, old/now-unused dependencies do not get removed from DEPS.bzl, is that expected?

**Pull request merged**
