### PR TITLE
txnwait: do not require vmodule to log deadlocks in a workload

### PR DESCRIPTION
**Pull request by arulajmani**
Deadlocks in a workload are rare (and bad) enough that they should be logged at the level of Info, instead of under vmodule.

Epic: none

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99315)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/txnwait/queue.go` line 722 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99315#-NRDxuIUCSsoYhmqX7bL:-NRDxuIUCSsoYhmqX7bM:b1e2srj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b2b4b8169e0d9ebb35b3c0fb5ba6d1d5e56d07d/pkg/kv/kvserver/txnwait/queue.go#L722)):*
> ```Go
> 				p1, p2 := pusheePriority, pusherPriority
> 				if p1 < p2 || (p1 == p2 && bytes.Compare(req.PusheeTxn.ID.GetBytes(), req.PusherTxn.ID.GetBytes()) < 0) {
> 					log.Infof(
> ```

Do you think we should wrap this in an EveryN? Maybe only log it once a second, and otherwise retain the `log.VEventf`? I _think_ you can continue to use `log.VEventf` and then use `level=0` for the analogous call to `log.Infof`, but please double-check if you decide to write this like that.

**Comment by nvanbenschoten** [comment]
This still seems like a good idea. I imagine we'll thank ourselves for adding in this logging at some point in the future.

**Review by arulajmani — COMMENTED** [review]
Better late than never I guess :sweat_smile: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99315#-:-O-wlXkJ5aVWuaETiHJw:b4zn6p9)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/txnwait/queue.go` line 722 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99315#-NRDxuIUCSsoYhmqX7bL:-O-wlR4W17TJu608SslG:b-zf0eb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b2b4b8169e0d9ebb35b3c0fb5ba6d1d5e56d07d/pkg/kv/kvserver/txnwait/queue.go#L722)):*
> I _think_ you can continue to use `log.VEventf` and then use `level=0` for the analogous call to `log.Infof`, but please double-check if you decide to write this like that.

You're correct; verified that this is indeed how it works.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99315#-:-O0FbJzgCSMy9P18e1mk:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by arulajmani** [comment]
Thanks!

bors r=nvanbenschoten

**Pull request merged**
