### PR TITLE
roachtest: remove interesting whitespace characters in random SQL test logs

### PR DESCRIPTION
**Pull request by mgartner**
In #102038 we started writing statements to the query log in SQL
comments. The change removes newline characters in the statement to
ensure that the statement will be on one line all within the comment.
However, we still see test logs where the comments are broken onto
multiple lines, as in #118273, which makes the file invalid
syntactically. This makes reproducing the test failure more difficult
because the comments have to be manually fixed so that the log file can
be successfully parsed.

I was able to determine that the line breaks are coming from other
"interesting" whitespace characters. The `xxd` output from the log file
in #118273 shows the carriage return character, `0d` being used in the
middle of a column name:

    00000090: 2041 5320 2263 6f0d 6c33 3830 2246 524f   AS "co.l380"FRO

This commit strips all interesting whitespace characters from the
statement to prevent the comment from being broken on multiple lines.

Epic: None

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
Note that if you download the log files this isn't a problem. But if you're copy/pasting the logs around, editors may do some questionable things to the bytes, like changing carriage returns to newlines. This change will prevent this from causing any problems. So it's just an ergonomic improvement.

**Review by michae2 — APPROVED** [review]
:lgtm: Thank you! I think form feed has been messing me up the most.

Might be worth doing this in TLP and sqlsmith as well?

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118312#-:-Np0i0az-yUGmOwBpUWF:b1w2bx0)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @mgartner, @srosenberg, and @yuzefovich)

___
*[`pkg/cmd/roachtest/tests/query_comparison_util.go` line 442 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118312#-Np0hWPs8ktf4oUbQaM7:-Np0hWPs8ktf4oUbQaM8:b-jr2vpx) ([raw file](https://github.com/cockroachdb/cockroach/blob/273db8ff0de272c664d08c18f0ae1ecbf38262af/pkg/cmd/roachtest/tests/query_comparison_util.go#L442)):*
> ```Go
> // stmtReplacer removes interesting white space characters that may be in
> // a column or table name. See nameGenerator.GenerateOne.
> var stmtReplacer = strings.NewReplacer("\n", "", "\r", "", "\f", "", "\v", "")
> ```

Nice! Not sure if other control characters are generated, but it might be worth removing all `unicode.IsControl` runes.

**Review by yuzefovich — APPROVED** [review]
:lgtm: Thanks!

> Might be worth doing this in TLP and sqlsmith as well?

Do you mean modifying the queries that get executed? This change modifies the commented out parts that were added as part of logging, and I don't think we do the same additional logging in TLP nor sqlsmith.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118312#-:-Np2IeC5A1XoHmHZff6H:bginil2)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @DarrylWong, @mgartner, and @srosenberg)

**Review by michae2 — APPROVED** [review]
Oh, thank you for correcting me. Yes, I meant the queries that get executed as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118312#-:-Np2PRFiAwYPSUCQMR6Q:b-1dr6sm)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @DarrylWong, @mgartner, and @srosenberg)

**Review by mgartner — COMMENTED** [review]
>Yes, I meant the queries that get executed as well.

I don't understand. The newlines only cause issues in the comments, AFAIK.

FWIW, I don't think there's a ton of value in having all the crazy characters we have in generated names now, at least for randomized logic tests. I think there is value for SQLSmith probably. We could tone down the craziness of names generated for these tests. But I'll leave that as future work.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118312#-:-Np6kCBwCiilMqs6qlSk:b1l2lyo)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DarrylWong, @michae2, @srosenberg, and @yuzefovich)

___
*[`pkg/cmd/roachtest/tests/query_comparison_util.go` line 442 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118312#-Np0hWPs8ktf4oUbQaM7:-Np6kAE32aG2WqlvEy_a:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/273db8ff0de272c664d08c18f0ae1ecbf38262af/pkg/cmd/roachtest/tests/query_comparison_util.go#L442)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Nice! Not sure if other control characters are generated, but it might be worth removing all `unicode.IsControl` runes.
</blockquote></details>

Done.

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
