### PR TITLE
release-22.1: backupccl: reduce over-splitting during RESTORE

### PR DESCRIPTION
**Pull request by adityamaru**
Backport 2/2 commits from #86496.

/cc @cockroachdb/release

---

When constructing the spans to restore, we can produce fewer, wider spans
that each contain more files to avoid splitting as much.

Previously we split at the bounds of every file in the base backup, then
added incremental layer files to any span they overlapped. This changes
that slightly to keep appending files that would create a new span at the
right-hand-side of the span covering to instead extend current rightmost
entry in the covering if the total size of what has been added to it is
still below our target size per span (384mb).

Release justification: bug fix.

Release note (bug fix):  reduce the amount that RESTORE over-splits ranges. The
behavior is enabled by default.

### CODE REVIEW

**Comment by adityamaru** [comment]
Letting CI shake out any issues, because this was not a clean backport.

**Comment by adityamaru** [comment]
I'm now going to run some roachtest/restores with this diff to ensure it works as expected.

**Review by msbutler — APPROVED** [review]
looks great! 

Either in this PR or elsewhere, we should add a roachtest that restores from TPCCInc from a random incremental layer ,with target span size set to 384. This will provide extra coverage that this setting performs well on a variety of restore span configurations.

**Comment by msbutler** [comment]
^i'm also considering adding a backportable roachtest to master that starts a workload,  creates backup chain, takes a fingerprint at some random system time, and restores at the fingerprint time and verifies things look the same.

**Review by dt — APPROVED** [review]

**Comment by adityamaru** [comment]
`TestComposeGSS` failures are known/skipped.

**Pull request merged**
