### PR TITLE
storage: document split complexities

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7704)

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[storage/replica_command.go, line 2212 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAfHUsuqBU-1a0q3wA:-KMAfHUtiCab0phKUkc5:1373522927) ([raw file](https://github.com/cockroachdb/cockroach/blob/db78a36b14ac1b9aee05436efdba1c7fe425d0c7/storage/replica_command.go#L2212)):*
> ```Go
> // recomputes stats for both the existing, updated range and the new range. For
> // performance it only computes the stats for the updated range and infers the
> // rest by subtracting from the original stats.
> ```

Might mention here that it matters that we compute the LHS since we make sure during split key computation to not create large left-hand sides (while the RHS could be ginormous).

---

*[storage/replica_command.go, line 2216 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAfS3pzS0_4zeQbPJr:-KMAfS3pzS0_4zeQbPJs:-1334030781) ([raw file](https://github.com/cockroachdb/cockroach/blob/db78a36b14ac1b9aee05436efdba1c7fe425d0c7/storage/replica_command.go#L2216)):*
> ```Go
> // Splits are complicated. A split is initiated when a replica receives an
> // AdminSplit request. This request is only executed on the replica
> // leader-lease and the request is redirected to the leader if the recipient is
> ```

This sounds a bit confusing. Maybe point out that `AdminSplit` really isn't a Raft command but simply lets the replica act as the client behind the distributed transaction which orchestrates the split.

---

*[storage/replica_command.go, line 2219 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAftKpDxwwFWaLKGTM:-KMAftKpDxwwFWaLKGTN:219944530) ([raw file](https://github.com/cockroachdb/cockroach/blob/db78a36b14ac1b9aee05436efdba1c7fe425d0c7/storage/replica_command.go#L2219)):*
> ```Go
> // a follower. The processing of splits is divided into two phases. The first
> // phase occurs in Replica.AdminSplit. In that phase, the split-point is
> // computed, the old and new (updated) range descriptors are adjusted/created
> ```

That sounds like something is written before the transaction. Make sure to point out that all of this is inside the same transaction.

---

*[storage/replica_command.go, line 2300 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAgKMBNckluNoFecWe:-KMAgKMC1nSd4lUnEDZ9:-1638244415) ([raw file](https://github.com/cockroachdb/cockroach/blob/db78a36b14ac1b9aee05436efdba1c7fe425d0c7/storage/replica_command.go#L2300)):*
> ```Go
> // performance perspective. Likely we will have to add a mutex to Replica to
> // protect handleRaftReady and to grab that mutex below when marking the
> // uninitialized Replica as "destroyed".
> ```

And that mutex should hopefully replace `processRaftMu`.

---

*[storage/replica_command.go, line 2309 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAgb2Vb8lUVPpAvY4Y:-KMAgb2Vb8lUVPpAvY4Z:-472231882) ([raw file](https://github.com/cockroachdb/cockroach/blob/db78a36b14ac1b9aee05436efdba1c7fe425d0c7/storage/replica_command.go#L2309)):*
> ```Go
> // SplitTrigger. Why?  Because A will be campaigning at a term and commit index
> // that are in advance of what B and C know about and thus won't be able to get
> // a quorum in order to be elected. [@bdarnell: Is this accurate?]
> ```

I think this is correct in spirit. If B receives MsgVote for Term 6, it will bump its term up to 6, and vote for A. But it'll discard snapshots, so no progress is possible even though Raft thinks it has a quorum.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-:-KMAh9THsDzFipZXb1L3:1417088721)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[storage/replica_command.go, line 2212 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAfHUsuqBU-1a0q3wA:-KMAiDrRixuQxjUQJreD:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/db78a36b14ac1b9aee05436efdba1c7fe425d0c7/storage/replica_command.go#L2212)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Might mention here that it matters that we compute the LHS since we make sure during split key computation to not create large left-hand sides (while the RHS could be ginormous).
</details>
Done.

---

*[storage/replica_command.go, line 2216 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAfS3pzS0_4zeQbPJr:-KMAhir-PBWkLbaTfydj:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/db78a36b14ac1b9aee05436efdba1c7fe425d0c7/storage/replica_command.go#L2216)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> This sounds a bit confusing. Maybe point out that `AdminSplit` really isn't a Raft command but simply lets the replica act as the client behind the distributed transaction which orchestrates the split.
</details>
Done.

---

*[storage/replica_command.go, line 2219 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAftKpDxwwFWaLKGTM:-KMAinyR8chLUPUA6gEn:1125654049) ([raw file](https://github.com/cockroachdb/cockroach/blob/db78a36b14ac1b9aee05436efdba1c7fe425d0c7/storage/replica_command.go#L2219)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> That sounds like something is written before the transaction. Make sure to point out that all of this is inside the same transaction.
</details>
I've reworked the sentence to make that clearer.

---

*[storage/replica_command.go, line 2300 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAgKMBNckluNoFecWe:-KMAixcYKUi_MLIkX7Aj:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/db78a36b14ac1b9aee05436efdba1c7fe425d0c7/storage/replica_command.go#L2300)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> And that mutex should hopefully replace `processRaftMu`.
</details>
Done.

---

*[storage/replica_command.go, line 2309 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAgb2Vb8lUVPpAvY4Y:-KMAj0Wkc5oRdZhg6d28:-116777940) ([raw file](https://github.com/cockroachdb/cockroach/blob/db78a36b14ac1b9aee05436efdba1c7fe425d0c7/storage/replica_command.go#L2309)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> I think this is correct in spirit. If B receives MsgVote for Term 6, it will bump its term up to 6, and vote for A. But it'll discard snapshots, so no progress is possible even though Raft thinks it has a quorum.
</details>
Ok. I'll wait for Ben to chime in as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[storage/replica_command.go, line 2211 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAjg8gfgmXpz4cGm38:-KMAjg8gfgmXpz4cGm39:-230965581) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7189148768329c4c7b33196d345cddabebb9c99/storage/replica_command.go#L2211)):*
> ```Go
> // AdminSplit operation. It copies the abort cache for the new range and
> // recomputes stats for both the existing, updated range and the new range. For
> // performance it only computes the stats for the new range (the
> ```

wait, isn't the right-hand-side the `new range`?

---

*[storage/replica_command.go, line 2218 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAjnY0VgFt_xkgL-fa:-KMAjnY0VgFt_xkgL-fb:82085642) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7189148768329c4c7b33196d345cddabebb9c99/storage/replica_command.go#L2218)):*
> ```Go
> // Splits are complicated. A split is initiated when a replica receives an
> // AdminSplit request. Note that this request (and other "admin" requests)
> // differ from normal requests in that it doesn't go through Raft but instead
> ```

s/differ/differs/

---

*[storage/replica_command.go, line 2227 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAkGHu2yjzLro2UaF_:-KMAkGHu2yjzLro2UaFa:-1513570152) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7189148768329c4c7b33196d345cddabebb9c99/storage/replica_command.go#L2227)):*
> ```Go
> // in Replica.AdminSplit. In that phase, the split-point is computed, and a
> // transaction is started which updates both the LHS and RHS range descriptors
> // and the meta2 range addressing information. That transaction includes a
> ```

s/meta2/meta/?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[storage/replica_command.go, line 2211 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAjg8gfgmXpz4cGm38:-KMAl6h3M02tPaDT5pGD:1808475760) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7189148768329c4c7b33196d345cddabebb9c99/storage/replica_command.go#L2211)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> wait, isn't the right-hand-side the `new range`?
</details>
Yes, I meant `old range`.

---

*[storage/replica_command.go, line 2218 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAjnY0VgFt_xkgL-fa:-KMAlDUT8BjVbXXzjqKI:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7189148768329c4c7b33196d345cddabebb9c99/storage/replica_command.go#L2218)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> s/differ/differs/
</details>
Done.

---

*[storage/replica_command.go, line 2227 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAkGHu2yjzLro2UaF_:-KMAlUcoaoBP4tuY9_A8:-906883446) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7189148768329c4c7b33196d345cddabebb9c99/storage/replica_command.go#L2227)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> s/meta2/meta/?
</details>
Yeah, maybe. We only update meta1 keys if the range we're splitting contains meta2 keys. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/replica_command.go, line 2227 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAkGHu2yjzLro2UaF_:-KMAv4oE752f-lyFmVz_:-521067653) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7189148768329c4c7b33196d345cddabebb9c99/storage/replica_command.go#L2227)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Yeah, maybe. We only update meta1 keys if the range we're splitting contains meta2 keys. 
</details>
Doesn't hurt to mention that interesting case, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[storage/replica_command.go, line 2221 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAoolvaWKgY96qe805:-KMAoolvaWKgY96qe806:1828324284) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7189148768329c4c7b33196d345cddabebb9c99/storage/replica_command.go#L2221)):*
> ```Go
> // allows the leader Replica to act as the orchestrator for the distributed
> // transaction that performs the split. As such, this request is only executed
> // on the replica leader-lease and the request is redirected to the leader if
> ```

Splits do not require the lease for correctness (which is good, because we only check that the lease is held at the beginning of the operation, and have no way to ensure that it is continually held until the end). Followers could perform splits too, and the only downside would be that if two splits were attempted concurrently (or a split and a ChangeReplicas), one would fail. The leader lease is used to designate one replica for this role and avoid wasting time on splits that may fail.

---

*[storage/replica_command.go, line 2293 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAq4-0atvqdA9ATh6n:-KMAq4-1_SuifJXCY8lu:1917722569) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7189148768329c4c7b33196d345cddabebb9c99/storage/replica_command.go#L2293)):*
> ```Go
> // will have participated in the Raft elections. When we're creating the new
> // Replica below we take control of this uninitialized Replica and stop it from
> // responding to Raft messages by marking it "destroyed".
> ```

Note that we use the `destroyed` field for this, but we don't do everything that `Replica.Destroy` does (so we should probably rename that field in light of its new uses). In particular we don't touch any data on disk or leave a tombstone. This is especially important because leaving a tombstone would prevent the legitimate recreation of this replica. 

---

*[storage/replica_command.go, line 2316 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAqVD9HNXXe1Cz0FqO:-KMAqVDA-7AZhH2tkDwH:-284224823) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7189148768329c4c7b33196d345cddabebb9c99/storage/replica_command.go#L2316)):*
> ```Go
> // SplitTrigger. Why?  Because A will be campaigning at a term and commit index
> // that are in advance of what B and C know about and thus won't be able to get
> // a quorum in order to be elected. [@bdarnell: Is this accurate?]
> ```

No. The act of campaigning informs nodes B and C about the new term and commit index, so B and C will vote for A even before they process the splitTrigger. This is why it is important to preserve their HardStates, so that the splitTrigger does not erase the record of a vote they had previously cast. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-:-KMAuU3CYd6_5PfWtS1C:1417088721)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[storage/replica_command.go, line 2221 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAoWMHflausmvxSrF1:-KMAoWMHflausmvxSrF2:-1469528993) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7189148768329c4c7b33196d345cddabebb9c99/storage/replica_command.go#L2221)):*
> ```Go
> // allows the leader Replica to act as the orchestrator for the distributed
> // transaction that performs the split. As such, this request is only executed
> // on the replica leader-lease and the request is redirected to the leader if
> ```

nit: I hear we've been saying "lease holder replica" more recently, I hear we don't like "leader" since it's confusing with raft leadership

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[storage/replica_command.go, line 2221 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAoWMHflausmvxSrF1:-KMB35wAerqH6ujzZVfe:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7189148768329c4c7b33196d345cddabebb9c99/storage/replica_command.go#L2221)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> nit: I hear we've been saying "lease holder replica" more recently, I hear we don't like "leader" since it's confusing with raft leadership
</details>
Done.

---

*[storage/replica_command.go, line 2221 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAoolvaWKgY96qe805:-KMB36HkFFZNIPF5Y1qb:-338029685) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7189148768329c4c7b33196d345cddabebb9c99/storage/replica_command.go#L2221)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Splits do not require the lease for correctness (which is good, because we only check that the lease is held at the beginning of the operation, and have no way to ensure that it is continually held until the end). Followers could perform splits too, and the only downside would be that if two splits were attempted concurrently (or a split and a ChangeReplicas), one would fail. The leader lease is used to designate one replica for this role and avoid wasting time on splits that may fail.
</details>
Copied your verbiage verbatim

---

*[storage/replica_command.go, line 2227 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAkGHu2yjzLro2UaF_:-KMB3_-zUpXObptpVchM:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7189148768329c4c7b33196d345cddabebb9c99/storage/replica_command.go#L2227)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Doesn't hurt to mention that interesting case, though.
</details>
Done.

---

*[storage/replica_command.go, line 2293 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAq4-0atvqdA9ATh6n:-KMB3ivVeUdDMvUBti58:-2095125118) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7189148768329c4c7b33196d345cddabebb9c99/storage/replica_command.go#L2293)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Note that we use the `destroyed` field for this, but we don't do everything that `Replica.Destroy` does (so we should probably rename that field in light of its new uses). In particular we don't touch any data on disk or leave a tombstone. This is especially important because leaving a tombstone would prevent the legitimate recreation of this replica. 
</details>
Added that clarification. 

---

*[storage/replica_command.go, line 2316 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAqVD9HNXXe1Cz0FqO:-KMB3vTibX7oOYV9CD-J:-541321713) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7189148768329c4c7b33196d345cddabebb9c99/storage/replica_command.go#L2316)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> No. The act of campaigning informs nodes B and C about the new term and commit index, so B and C will vote for A even before they process the splitTrigger. This is why it is important to preserve their HardStates, so that the splitTrigger does not erase the record of a vote they had previously cast. 
</details>
Ok. What applies B and C from applying raft-log entries sent from A? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704)*

**Comment by tschottdorf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[storage/replica_command.go, line 2221 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMB4ZH2KR8wcVbXYOPJ:-KMB4ZH2KR8wcVbXYOPK:-375559014) ([raw file](https://github.com/cockroachdb/cockroach/blob/15986ab6b12c2c425e9f881f423f850cd1573245/storage/replica_command.go#L2221)):*
> ```Go
> // allows the lease holder Replica to act as the orchestrator for the
> // distributed transaction that performs the split. As such, this request is
> // only executed on the leader holder replica and the request is redirected to
> ```

s/leader/lease/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[storage/replica_command.go, line 2221 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMB4ZH2KR8wcVbXYOPJ:-KMB5AM22diEdIV-rPEp:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/15986ab6b12c2c425e9f881f423f850cd1573245/storage/replica_command.go#L2221)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> s/leader/lease/
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704)*

**Comment by tschottdorf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[storage/replica_command.go, line 2316 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAqVD9HNXXe1Cz0FqO:-KMB4vyRUMC32hTZH0IP:830998052) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7189148768329c4c7b33196d345cddabebb9c99/storage/replica_command.go#L2316)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Ok. What applies B and C from applying raft-log entries sent from A? 
</details>
B and C will have to receive a snapshot (remember that the new range starts at index 10, but B and C are at 0) and we don't allow that snapshot through, so they will only participate on paper until they've been split triggered.

---

*[storage/replica_command.go, line 2229 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMB4e4Ceo_ErFwX5278:-KMB4e4Ceo_ErFwX5279:1924158373) ([raw file](https://github.com/cockroachdb/cockroach/blob/15986ab6b12c2c425e9f881f423f850cd1573245/storage/replica_command.go#L2229)):*
> ```Go
> // could perform splits too, and the only downside would be that if two splits
> // were attempted concurrently (or a split and a ChangeReplicas), one would
> // fail. The leader lease is used to designate one replica for this role and
> ```

s/leader// or s/leader/range/ (@bdarnell's preferred one).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[storage/replica_command.go, line 2316 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAqVD9HNXXe1Cz0FqO:-KMB5MX6Va8iYhWIUlZa:268150926) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7189148768329c4c7b33196d345cddabebb9c99/storage/replica_command.go#L2316)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> B and C will have to receive a snapshot (remember that the new range starts at index 10, but B and C are at 0) and we don't allow that snapshot through, so they will only participate on paper until they've been split triggered.
</details>
No, I didn't remember that new ranges start at index 10. Let me add some more commentary explaining this.

---

*[storage/replica_command.go, line 2229 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMB4e4Ceo_ErFwX5278:-KMB6ffzef7ksBf1Zud7:1709702631) ([raw file](https://github.com/cockroachdb/cockroach/blob/15986ab6b12c2c425e9f881f423f850cd1573245/storage/replica_command.go#L2229)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> s/leader// or s/leader/range/ (@bdarnell's preferred one).
</details>
Someone should do a `s/leader lease/range lease/g` in the code. The term `leader lease` is used frequently. I'm going to leave this as-is for now as it is the common usage.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[storage/replica_command.go, line 2229 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMB4e4Ceo_ErFwX5278:-KMB8bZdtdeo1rFEbwqf:1482701881) ([raw file](https://github.com/cockroachdb/cockroach/blob/15986ab6b12c2c425e9f881f423f850cd1573245/storage/replica_command.go#L2229)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Someone should do a `s/leader lease/range lease/g` in the code. The term `leader lease` is used frequently. I'm going to leave this as-is for now as it is the common usage.
</details>
sgtm. Might do it on the airplane.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[storage/replica_command.go, line 2316 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAqVD9HNXXe1Cz0FqO:-KMB5QG8m-gkz0SL1zrY:-555014419) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7189148768329c4c7b33196d345cddabebb9c99/storage/replica_command.go#L2316)):*
> participate on paper

They're real participants; their vote counts. They will reject all log entries, and so even though A wins the election it won't be able to commit anything until one of B or C has applied a snapshot and is able to accept log entries.

Why do new ranges start at 10? There's already data on disk for the RHS of a split, but that data never appeared in the new range's log. To prevent raft from attempting to replay a log from the beginning, we create a gap at the beginning of the log. Entries 1-9 never existed, so the only way to catch up is by either applying the split trigger if you have the data, or applying a full snapshot if you do not. (the choice of 10 is arbitrary. I wasn't sure whether the minimum value that would have this effect was 1 or 2, so I just went higher to be sure)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[storage/replica_command.go, line 2316 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMAqVD9HNXXe1Cz0FqO:-KMB9_Pk6JaDoM5NFQOB:1342032009) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7189148768329c4c7b33196d345cddabebb9c99/storage/replica_command.go#L2316)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> > participate on paper
> 
> They're real participants; their vote counts. They will reject all log entries, and so even though A wins the election it won't be able to commit anything until one of B or C has applied a snapshot and is able to accept log entries.
> 
> Why do new ranges start at 10? There's already data on disk for the RHS of a split, but that data never appeared in the new range's log. To prevent raft from attempting to replay a log from the beginning, we create a gap at the beginning of the log. Entries 1-9 never existed, so the only way to catch up is by either applying the split trigger if you have the data, or applying a full snapshot if you do not. (the choice of 10 is arbitrary. I wasn't sure whether the minimum value that would have this effect was 1 or 2, so I just went higher to be sure)
</details>
I updated this section. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704)*

**Comment by petermattis** [comment]
@jess-edwards Expanded and with pretty diagrams, this could be a blog post.

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[storage/replica_command.go, line 2332 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMBAm7FHOhGdEkE2NIJ:-KMBAm7FHOhGdEkE2NIK:1029851820) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2e76a01d4f2bb26557c523c305b0c3ffee9607f/storage/replica_command.go#L2332)):*
> ```Go
> // send a snapshot to B and C and we'll fall into the situation above where a
> // snapshot is received for a range before it has finished splitting from its
> // sibling. An interesting subtlety here: A will send a snapshot to B and C
> ```

s/sibling/sibling and is thus rejected./

---

*[storage/replica_command.go, line 2334 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMBArpjrZcjo63y5K7F:-KMBArpjrZcjo63y5K7G:-728805843) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2e76a01d4f2bb26557c523c305b0c3ffee9607f/storage/replica_command.go#L2334)):*
> ```Go
> // sibling. An interesting subtlety here: A will send a snapshot to B and C
> // because when range 2 is initialized it starts at Raft log index 10. This
> // causes Raft to believe that there is a discarded prefix to the log and will
> ```

This sounds like that's some kind of implementation artifact but it's the crucial part. Mind making that explicit? We can't just start at zero because zero is by definition a replica which has nothing (but the RHS has something).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[storage/replica_command.go, line 2332 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMBAm7FHOhGdEkE2NIJ:-KMBCvO1Ok7cOjpHsnUi:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2e76a01d4f2bb26557c523c305b0c3ffee9607f/storage/replica_command.go#L2332)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> s/sibling/sibling and is thus rejected./
</details>
Done.

---

*[storage/replica_command.go, line 2334 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704#-KMBArpjrZcjo63y5K7F:-KMBCvoRTdt2bXid0aFd:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2e76a01d4f2bb26557c523c305b0c3ffee9607f/storage/replica_command.go#L2334)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> This sounds like that's some kind of implementation artifact but it's the crucial part. Mind making that explicit? We can't just start at zero because zero is by definition a replica which has nothing (but the RHS has something).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7704)*

**Pull request merged**
