### PR TITLE
tree: redact name in DEALLOCATE in FmtHideConstants

### PR DESCRIPTION
**Pull request by rafiss**
This will make it so that all DEALLOCATE statements show up in one row
in the SQL Statements UI and in the internal stats data structures.

Recently, a workload was updated (accidentally) to start creating more
DEALLOCATE statements, and it made the UI unusable because there were so
many DEALLOCATE statement keys.

The second commit is a rename to stop implying that statements with
redacted constants are "anonymized" -- they still have names+identifiers.
This also renames the name of a field in a response payload.

Created while working on https://github.com/cockroachdb/cockroach/issues/69317 but doesn't fix it. 

Release justification: fix a high-priority bugs with a low-risk change.
Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm_strong: 

Any interest in a test that issues some prepare and deallocate and then queries the statement stats? 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69375#-:-MhyPG1d5QdMVqKPIn7m:bpy7s7k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Review by ajwerner — COMMENTED** [review]
My slight preference is for symmetry with `PREPARE`. I imagine part of the problem with prepare is that it has the query in it so they'd be different unless we hid the query in which case they'd be useless. I'd support metrics for the number of prepares and deallocates. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69375#-:-Mi6w8tX8JazwzKGyvac:b-ymdy6z)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @jordanlewis)

**Review by maryliag — APPROVED** [review]
We will be making the decision on which way to proceed (make DEALLOCATE similar to PREPARE or change PREPARE so that stats are collected) on the issue Archer created.
Regarding this particular PR :lgtm: 

> Reviewed 3 of 3 files at r2, 16 of 16 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69375#-:-Mi7rVrA5DKH6-6teIF-:box73jr)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by rafiss** [comment]
bors r=ajwerner,maryliag

**Pull request merged**
