### PR TITLE
storage: add tracing to changeReplicas

### PR DESCRIPTION
**Pull request by BramGruneir**
Part of the investigation into #7489

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7802)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/replica_command.go, line 2868 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7802#-KMaM7k95XLz_oqXw4RF:-KMaM7k95XLz_oqXw4RG:1549216372) ([raw file](https://github.com/cockroachdb/cockroach/blob/468ee7fe867e82f49b5ea86556853c5cfc57599a/storage/replica_command.go#L2868)):*
> ```Go
> 		}
> 
> 		log.Trace(ctx, "requesting reservation")
> ```

throughout: do we need to say that we're in a change replicas here? what does this look like in practice?

---

*[storage/replica_command.go, line 2879 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7802#-KMaLwGoQtR-9ndORnHZ:-KMaLwGph_tSvCk54-gg:23764052) ([raw file](https://github.com/cockroachdb/cockroach/blob/468ee7fe867e82f49b5ea86556853c5cfc57599a/storage/replica_command.go#L2879)):*
> ```Go
> 			return errors.Wrapf(err, "change replicas of range %d failed", rangeID)
> 		}
> 		log.Trace(ctx, "received reservation")
> ```

"received" is an odd word

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7802)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7802#-:-KMb_mXrJkOehglyPgYA:1417088721)*

**Comment by BramGruneir** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/replica_command.go, line 2868 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7802#-KMaM7k95XLz_oqXw4RF:-KMdjHkrMalsWO0jDdxD:1345655088) ([raw file](https://github.com/cockroachdb/cockroach/blob/468ee7fe867e82f49b5ea86556853c5cfc57599a/storage/replica_command.go#L2868)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> throughout: do we need to say that we're in a change replicas here? what does this look like in practice?
</details>
```

2016/07/13 17:14:55.608935	0.679540	replicate:5
17:14:55.608940	 .     5	... got range lease
17:14:55.608953	 .    13	... adding a new replica
17:14:55.608965	 .    13	... adding replica to {NodeID:2 StoreID:2 ReplicaID:0} due to under-replication
17:14:55.608967	 .     2	... requesting reservation
17:14:55.610454	 .  1487	... received reservation
17:14:55.610655	 .   201	... generated snapshot
17:14:55.610657	 .     3	... starting txn
17:14:56.288432	 .677774	... txn complete
17:14:56.288474	 .    43	... done
```

---

*[storage/replica_command.go, line 2879 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7802#-KMaLwGoQtR-9ndORnHZ:-KMdk7QtQh4dxzCk0Pge:2080944327) ([raw file](https://github.com/cockroachdb/cockroach/blob/468ee7fe867e82f49b5ea86556853c5cfc57599a/storage/replica_command.go#L2879)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> "received" is an odd word
</details>
changed to granted

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7802)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7802)*

**Pull request merged**
