### PR TITLE
storage/engine: add basic FS interface

### PR DESCRIPTION
**Pull request by sumeerbhola**
The interface is not identical to Pebble's vfs.FS and missing
some of the functionality due to the need to implement this also
via the RocksDB Env. But it does include File.ReadAt that is
mentioned in #42034.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
This lacks testa and is mostly boilerplate c++ code. Just looking for feedback on the `FS` interface in `engine.go`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-:-LvMDkUi1VGRH0IMFiwD:b4gaw20)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @petermattis)

**Review by petermattis — COMMENTED** [review]
I was thinking that we'll want to change `Engine` to not implement `FS` at some point, and instead provide an `FS()` accessor:

```
type Engine interface {
  ...
  // Returns the FS backing the engine.
  FS() FS
}
```

That can come in a follow-on PR, though. As a first step this looks good.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-:-LvMFQI91dpClodyfNN1:b-btcbel)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[c-deps/libroach/engine.cc, line 473 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-LvMFG5u-cajQulZKH3V:-LvMFG5u-cajQulZKH3W:b-lpqlv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a7aba324e294caecb132bdbc23368f705562795/c-deps/libroach/engine.cc#L473)):*
> ```cpp
>   size_t max_bytes_to_read = buffer.len;
>   char* scratch = buffer.data;
>   rocksdb::Slice result = ToSlice(buffer);
> ```

Is the `ToSlice` necessary? Looks to me like `file->Read` is reading into `scratch` and then populating `result` using `scratch`.
___
*[pkg/storage/engine/engine.go, line 406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-LvMEgIG532VIzsJUaSP:-LvMEgIHDGPmK3ooheq3:bwv3yg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a7aba324e294caecb132bdbc23368f705562795/pkg/storage/engine/engine.go#L406)):*
> ```Go
> 	// OpenFile opens a DBFile with the given filename. The file should be created
> 	// if it doesn't exist already, and should be writable.
> 	OpenFile(filename string) (DBFile, error)
> ```

You can remove all of this `*File` methods, and instead embed `FS` here. Something like:

```
type Engine interface {
  ...
  FS
}
```
___
*[pkg/storage/engine/engine.go, line 468 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-LvME2iw1Ca9D1_jB8Sl:-LvME2ix466k_5f-Z-ja:ba8kkm9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a7aba324e294caecb132bdbc23368f705562795/pkg/storage/engine/engine.go#L468)):*
> ```Go
> 
> // File and FS are a partial attempt at offering the Pebble vfs.FS interface. Given the constraints
> // of the Rocksdb Env interface we've chosen to only include what is easy to implement. Additionally,
> ```

Nit: `s/Rocksdb/RocksDB/g`
___
*[pkg/storage/engine/engine.go, line 471 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-LvMESf5Bx29UoZfjQiG:-LvMESf5Bx29UoZfjQiH:b-qvk1p5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a7aba324e294caecb132bdbc23368f705562795/pkg/storage/engine/engine.go#L471)):*
> ```Go
> // it does not try to subsume all the file related functionality already in the Engine interface.
> // It seems preferable to do a final cleanup only when the implementation can simply use Pebble's
> // implementation of vfs.FS. At that point the following interface will become a superset of vfs.FS.
> ```

So the plan is to introduce this interface, and then in a later PR separate out the implementation from `Engine`? That works for me.
___
*[pkg/storage/engine/engine.go, line 490 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-LvMEqbdBYXJhGn4BS8O:-LvMEqbdBYXJhGn4BS8P:b-uvkuyn) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a7aba324e294caecb132bdbc23368f705562795/pkg/storage/engine/engine.go#L490)):*
> ```Go
> 
> 	// Open opens the named file for reading.
> 	// TODO: OpenFile() but already used that name in Engine for creation (super confusing). Change
> ```

Nit: `s/TODO/TODO(sumeer)/g`

**Review by itsbilal — COMMENTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42995)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr and @sumeerbhola)

___
*[pkg/storage/engine/engine.go, line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-LvMI8p0CDhJ6V1yfJIW:-LvMI8p19RbAZoO7Fd5h:b2ic026) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a7aba324e294caecb132bdbc23368f705562795/pkg/storage/engine/engine.go#L474)):*
> ```Go
> type File interface {
> 	io.Closer
> 	io.Reader
> ```

Nit: Three of these can be merged with `io.ReadWriteCloser`
___
*[pkg/storage/engine/rocksdb.go, line 3288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-LvMLI6C6BqW7mZ15MrQ:-LvMLI6C6BqW7mZ15MrR:brkrreu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a7aba324e294caecb132bdbc23368f705562795/pkg/storage/engine/rocksdb.go#L3288)):*
> ```Go
> 
> // DBFile is an interface for interacting with DBWritableFile in RocksDB.
> type DBFile interface {
> ```

Might be worthwhile adding a TODO to replace all uses of this with `File`?  Will be easiest to do when `Engine` loses its FS methods.

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42995)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/engine.go, line 406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-LvMEgIG532VIzsJUaSP:-LvMPqc_EuxCOERv6rFS:bwxzqlc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a7aba324e294caecb132bdbc23368f705562795/pkg/storage/engine/engine.go#L406)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You can remove all of this `*File` methods, and instead embed `FS` here. Something like:

```
type Engine interface {
  ...
  FS
}
```
</blockquote></details>

If you're incorporating this change, you should be able to delete `DBFile` rightaway, I think.

**Review by sumeerbhola — COMMENTED** [review]
TFTR! I still owe tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-:-Lvbhnep9W4b1YnKLdjj:b-e6abgt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @petermattis)

___
*[c-deps/libroach/engine.cc, line 473 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-LvMFG5u-cajQulZKH3V:-LvcVsJh6NZS60SBUSmJ:bbrevoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a7aba324e294caecb132bdbc23368f705562795/c-deps/libroach/engine.cc#L473)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is the `ToSlice` necessary? Looks to me like `file->Read` is reading into `scratch` and then populating `result` using `scratch`.
</blockquote></details>

You are right that it is not necessary. I misunderstood what the `Read()` interface was saying.
___
*[pkg/storage/engine/engine.go, line 406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-LvMEgIG532VIzsJUaSP:-LvcM7AhCsUVGnSUjam6:b-iz2w0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a7aba324e294caecb132bdbc23368f705562795/pkg/storage/engine/engine.go#L406)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

If you're incorporating this change, you should be able to delete `DBFile` rightaway, I think.
</blockquote></details>

Both done.
___
*[pkg/storage/engine/engine.go, line 468 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-LvME2iw1Ca9D1_jB8Sl:-LvcKKby7Etvvhlsm9kZ:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a7aba324e294caecb132bdbc23368f705562795/pkg/storage/engine/engine.go#L468)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: `s/Rocksdb/RocksDB/g`
</blockquote></details>

Done
___
*[pkg/storage/engine/engine.go, line 471 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-LvMESf5Bx29UoZfjQiG:-LvcK4kT7gd9rQvbxnjg:b-lo129p) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a7aba324e294caecb132bdbc23368f705562795/pkg/storage/engine/engine.go#L471)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

So the plan is to introduce this interface, and then in a later PR separate out the implementation from `Engine`? That works for me.
</blockquote></details>

Yes, that is the plan.
___
*[pkg/storage/engine/engine.go, line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-LvMI8p0CDhJ6V1yfJIW:-LvcK3Lz0ZUaBBX9xB6P:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a7aba324e294caecb132bdbc23368f705562795/pkg/storage/engine/engine.go#L474)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Nit: Three of these can be merged with `io.ReadWriteCloser`
</blockquote></details>

Done
___
*[pkg/storage/engine/engine.go, line 490 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-LvMEqbdBYXJhGn4BS8O:-LvcMD4b8-22MZGBWyAs:b-gz7v1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a7aba324e294caecb132bdbc23368f705562795/pkg/storage/engine/engine.go#L490)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: `s/TODO/TODO(sumeer)/g`
</blockquote></details>

TODO removed
___
*[pkg/storage/engine/rocksdb.go, line 3288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-LvMLI6C6BqW7mZ15MrQ:-LvcMIFU4awGysxdvToc:bgvryna) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a7aba324e294caecb132bdbc23368f705562795/pkg/storage/engine/rocksdb.go#L3288)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Might be worthwhile adding a TODO to replace all uses of this with `File`?  Will be easiest to do when `Engine` loses its FS methods.
</blockquote></details>

I've removed DBFile.

**Review by sumeerbhola — COMMENTED** [review]
Added tests. This is ready for a proper review.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-:-LvhjwDg8LytVXz3rMgT:bf0s2m3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @petermattis)

___
*[pkg/storage/engine/engine_test.go, line 1120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-LvhjZmg2__cjYM427do:-LvhjZmg2__cjYM427dp:b-hez62b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4c67bf61a8e5d9c8b94d94c886f393fed3af729/pkg/storage/engine/engine_test.go#L1120)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 
> 	for _, engineImpl := range mvccEngineImpls {
> ```

This includes testing of existing functionality (writable file, DeleteFile, LinkFile) which were not tested.
___
*[pkg/storage/engine/engine_test.go, line 1290 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-Lvhj03O49nZ1_YbFti1:-Lvhj03P3s222rd32nbx:b16vuo7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4c67bf61a8e5d9c8b94d94c886f393fed3af729/pkg/storage/engine/engine_test.go#L1290)):*
> ```Go
> }
> 
> func TestEngineFSFileNotFoundError(t *testing.T) {
> ```

this is a generalization of the test in rocksdb_test.go (which I deleted) and now covers both engine implementations.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-:-Lvk7c7h2DM-mzyOup_l:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[c-deps/libroach/engine.h, line 59 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-Lvk6hpZ6GVG8_Fu5lZz:-Lvk6hpZ6GVG8_Fu5l_-:bbafj59) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4c67bf61a8e5d9c8b94d94c886f393fed3af729/c-deps/libroach/engine.h#L59)):*
> ```objc
>   virtual DBStatus EnvSyncDirectory(rocksdb::Directory* file) = 0;
>   virtual DBStatus EnvCloseDirectory(rocksdb::Directory* file) = 0;
>   virtual DBStatus EnvRenameFile(DBSlice oldname, DBSlice newname) = 0;
> ```

I think this could be simplified by providing an `env()` accessor method. AFAICT, that is all these methods need for implementation. This would reduce some of the boilerplate from this PR. Not a correctness issue, so feel free to leave this to a follow-on PR if you'd like.
___
*[c-deps/libroach/include/libroach.h, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-Lvk6xn9AtAU0Y3Nbv1D:-Lvk6xn9AtAU0Y3Nbv1E:b5qypgc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4c67bf61a8e5d9c8b94d94c886f393fed3af729/c-deps/libroach/include/libroach.h#L71)):*
> ```objc
> typedef void* DBWritableFile;
> typedef void* DBReadableFile;
> typedef void* DBDirectory;  
> ```

Nit: `reviewable` is claiming there is trailing whitespace on this line.
___
*[c-deps/libroach/include/libroach.h, line 552 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-Lvk6PRr-wKnZtmB5VWm:-Lvk6PRr-wKnZtmB5VWn:b-r2q2f9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4c67bf61a8e5d9c8b94d94c886f393fed3af729/c-deps/libroach/include/libroach.h#L552)):*
> ```objc
> // DBEnvReadAtFile reads from the DBReadableFile into buffer, at the given offset,
> // and returns the bytes read in n.
> DBStatus DBEnvReadAtFile(DBEngine* db, DBReadableFile file, DBSlice buffer, int64_t offset, int* n);
> ```

Is the `db` parameter needed here? Ditto for some of the other methods below.
___
*[pkg/storage/engine/tee.go, line 548 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-Lvk7NN9EbkHA7AgYpGq:-Lvk7NN9EbkHA7AgYpGr:bv1yoh8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4c67bf61a8e5d9c8b94d94c886f393fed3af729/pkg/storage/engine/tee.go#L548)):*
> ```Go
> // ReadAt implements the File interface.
> func (t *TeeEngineFile) ReadAt(p []byte, off int64) (n int, err error) {
> 	p2 := append([]byte(nil), p...)
> ```

The copy is unnecessary. You just need a slice that is the same size as `p`:

```
  p2 := make([]byte, len(p))
```

Same comment applies to `TeeEngineFile.Read`.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42995)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, and @petermattis)

___
*[c-deps/libroach/engine.h, line 59 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-Lvk6hpZ6GVG8_Fu5lZz:-LvkGN7b7Z3WjSRpA1Vi:b-d3paib) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4c67bf61a8e5d9c8b94d94c886f393fed3af729/c-deps/libroach/engine.h#L59)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think this could be simplified by providing an `env()` accessor method. AFAICT, that is all these methods need for implementation. This would reduce some of the boilerplate from this PR. Not a correctness issue, so feel free to leave this to a follow-on PR if you'd like.
</blockquote></details>

That is a good point. I'll leave it to a follow-on.
___
*[c-deps/libroach/include/libroach.h, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-Lvk6xn9AtAU0Y3Nbv1D:-LvkGdM99j8pLBUczSQx:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4c67bf61a8e5d9c8b94d94c886f393fed3af729/c-deps/libroach/include/libroach.h#L71)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: `reviewable` is claiming there is trailing whitespace on this line.
</blockquote></details>

Done
___
*[c-deps/libroach/include/libroach.h, line 552 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-Lvk6PRr-wKnZtmB5VWm:-LvkH2a-5_X8VTPIbnwi:blwz19m) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4c67bf61a8e5d9c8b94d94c886f393fed3af729/c-deps/libroach/include/libroach.h#L552)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is the `db` parameter needed here? Ditto for some of the other methods below.
</blockquote></details>

It is because all these are implemented by forwarding to the `DBEngine`, which has multiple implementations. If we changed the DBEngine to just return the `Env` as you suggested, we would still have these methods taking the `DBEngine` parameter but the worse boilerplate in the `DBEngine` interface and its implementations would go away. 
___
*[pkg/storage/engine/tee.go, line 548 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42995#-Lvk7NN9EbkHA7AgYpGq:-LvkJu2z-bYx31XiMFEE:b4dvwf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4c67bf61a8e5d9c8b94d94c886f393fed3af729/pkg/storage/engine/tee.go#L548)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The copy is unnecessary. You just need a slice that is the same size as `p`:

```
  p2 := make([]byte, len(p))
```

Same comment applies to `TeeEngineFile.Read`.
</blockquote></details>

This interface permits `ReadAt` to return a `n < len(p)`. I don't think the interface is making any promise to leave the the unwritten bytes unchanged in the slice. So what I did was insufficient. I've changed to only compare equality for the n bytes.

**Pull request merged**
