### PR TITLE
storageccl: remove non-ReturnSST ExportRequest

### PR DESCRIPTION
**Pull request by dt**
Release justification: bug fix in new functionality.

Release note: none.

### CODE REVIEW

**Review by aliher1911 — APPROVED** [review]
:lgtm_strong: 

What happens during upgrades if caller is unaware? It would fail until it is upgraded and then it would not retry with ReturnSST = true?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69044#-:-MhXeJtx84Ql3MithYKv:bb4y842)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nihalpednekar)

**Comment by dt** [comment]
During upgrade we _typically_ plan the sql procs that send export requests on the same nodes as the leaseholders so they send to themselves. Only if we somehow get a leaseholder move mid backup across versions so we expect a mismatch. In that case if they have set the old always proxy writes setting their old nodes will ask for ReturnSST and should be fine. If they haven’t, their backup might fail and they would need to enable that setting to try again (or finish rolling out the new binary)

**Comment by dt** [comment]
I just realized i never backported #66540. Hm.

**Comment by dt** [comment]
Fixing a (potential) bug while I'm here and adding an extra check that the caller didn't ask for/expect the file to be encrypted, which is a potential if an older tenant pod asked mid-upgrade. Think I'll land this and get a 66540 backport going.

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
