### PR TITLE
ui: various glue fixes

### PR DESCRIPTION
**Pull request by benesch**
This PR restores the "no UI installed" message in short binaries:

image

I came across a few minor nits that seemed worth fixing too.

### CODE REVIEW

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29692)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/server/authentication.go, line 365 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/29692#-LLm1OxtDqZOGw04zriq:-LLm1OxtDqZOGw04zrir:bkjkzxe) ([raw file](https://github.com/cockroachdb/cockroach/blob/922422c4ef72fd0f48510953105afab2901c4894/pkg/server/authentication.go#L365)):*
> ```Go
> 	}
> 
> 	newCtx := context.WithValue(req.Context(), webSessionUserKey{}, username)
> ```

This would install a username of `""` if `getSession` returned an error. This seemed wrong and required a special case in `serveUIAssets` to convert `""` usernames to `nil`.
___
*[pkg/server/server.go, line 1240 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/29692#-LLm2G6a6aXJBkoadkKo:-LLm2G6a6aXJBkoadkKp:b-tri396) ([raw file](https://github.com/cockroachdb/cockroach/blob/b498b9c7a6aa778dc8fc5a6d33b2c91688862aff/pkg/server/server.go#L1240)):*
> ```Go
> 			LoginEnabled:         s.cfg.RequireWebSession(),
> 			GetUser: func(ctx context.Context) *string {
> 				if u, ok := ctx.Value(webSessionUserKey{}).(string); ok {
> ```

See the comment on the gzip response writer for why we no longer need to check for empty username.
___
*[pkg/server/server.go, line 1923 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/29692#-LLm1b1X2s7QOolxAiil:-LLm1b1YEs6mrZdlMFwC:b-ow1lbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b498b9c7a6aa778dc8fc5a6d33b2c91688862aff/pkg/server/server.go#L1923)):*
> ```Go
> 	if w.Header().Get("Content-Type") == "" {
> 		w.Header().Set("Content-Type", http.DetectContentType(b))
> 	}
> ```

This garbage was requiring us to explicitly specify`Content-Type: text/html` when rendering the template, because it was otherwise getting detected as `application/gzip`. (And gosh that's a garbage MIME type. How is that ever useful?)
___
*[pkg/ui/ui.go, line 141 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/29692#-LLm1x4J3mEvKfKJAKA9:-LLm1x4K25qw5_ZEerFm:b-vt4rwd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b498b9c7a6aa778dc8fc5a6d33b2c91688862aff/pkg/ui/ui.go#L141)):*
> ```Go
> 			Tag:                  buildInfo.Tag,
> 			Version:              build.VersionPrefix(),
> 		}); err != nil {
> ```

Note the lack of `template.JS` here. We actually want to be escaping this JSON. Otherwise I think you could XSS yourself by creating a username with special JS chars in it. Not very useful because only root can create users, but still silly.

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29692)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ui/ui.go, line 141 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/29692#-LLm1x4J3mEvKfKJAKA9:-LLoO4pOBg6fkyXDXlZw:b-wfg0io) ([raw file](https://github.com/cockroachdb/cockroach/blob/b498b9c7a6aa778dc8fc5a6d33b2c91688862aff/pkg/ui/ui.go#L141)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Note the lack of `template.JS` here. We actually want to be escaping this JSON. Otherwise I think you could XSS yourself by creating a username with special JS chars in it. Not very useful because only root can create users, but still silly.
</blockquote></details>

Er scratch that, the old code was calling `template.JS(json.Marshal(indexHTMLArgs{...}))`, which is exactly equivalent to and equally safe as passing `indexHTMLArgs{...}` directly.

**Comment by benesch** [comment]
Bump!

**Review by vilterp — APPROVED** [review]
Thanks!

**Review by couchand — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r8, 4 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29692)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/server/server.go, line 1239 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/29692#-LMIeObu-_jShCtvdsNL:-LMIeObu-_jShCtvdsNM:b-usljdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/35f0d426e7dd18ba24e7d0c04c4ec4378b48c8f1/pkg/server/server.go#L1239)):*
> ```Go
> 	maybeAuthMux := newAuthenticationMuxAllowAnonymous(
> 		s.authentication, ui.Handler(ui.Config{
> 			ExperimentalUseLogin: s.cfg.EnableWebSessionAuthentication,
> ```

why not just pass over the `Config` and let `ui` decide what it needs?
___
*[pkg/server/server.go, line 1241 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/29692#-LMIdav0By3ktx2WHw4l:-LMIdav0By3ktx2WHw4m:bbu2rmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/35f0d426e7dd18ba24e7d0c04c4ec4378b48c8f1/pkg/server/server.go#L1241)):*
> ```Go
> 			ExperimentalUseLogin: s.cfg.EnableWebSessionAuthentication,
> 			LoginEnabled:         s.cfg.RequireWebSession(),
> 			GetUser: func(ctx context.Context) *string {
> ```

regardless of the above, why not just inline this in `ui.Handler`?
___
*[pkg/server/server.go, line 1897 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/29692#-LMI_ozb4fZZSXCCUzEL:-LMI_ozb4fZZSXCCUzEM:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/35f0d426e7dd18ba24e7d0c04c4ec4378b48c8f1/pkg/server/server.go#L1897)):*
> ```Go
> }
> 
> // TODO(benesch): Use https://github.com/NYTimes/gziphandler instead.
> ```

:+1: 
___
*[pkg/server/server_test.go, line 867 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/29692#-LMIcFQHBiU1_OkNQPeq:-LMIcFQHBiU1_OkNQPer:b-66vu6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/35f0d426e7dd18ba24e7d0c04c4ec4378b48c8f1/pkg/server/server_test.go#L867)):*
> ```Go
> 		ui.AssetDir = func(name string) (_ []string, _ error) { return }
> 		ui.AssetInfo = func(name string) (_ os.FileInfo, _ error) { return }
> 		return func() {
> ```

I think this would be clearer as two distinct functions, so the usage is just:

```
linkInFakeUI()
defer unlinkFakeUI()
```
___
*[pkg/server/server_test.go, line 890 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/29692#-LMIcWP25HY1iO1zSjJf:-LMIcWP25HY1iO1zSjJg:bimf7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/35f0d426e7dd18ba24e7d0c04c4ec4378b48c8f1/pkg/server/server_test.go#L890)):*
> ```Go
> 		}
> 
> 		t.Run("short build", func(t *testing.T) {
> ```

yay a test!

**Review by benesch — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29692#-:-LMIs03A5KwbVsdp9dzW:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/server/server.go, line 1239 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/29692#-LMIeObu-_jShCtvdsNL:-LMIpZRG5znMILsD2G4t:b-ahc61j) ([raw file](https://github.com/cockroachdb/cockroach/blob/35f0d426e7dd18ba24e7d0c04c4ec4378b48c8f1/pkg/server/server.go#L1239)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

why not just pass over the `Config` and let `ui` decide what it needs?
</blockquote></details>

That would create a dependency cycle (server -> ui -> server), which is verboten in Go. We could extract a `serverconfig` package, but doesn't seem worth it for just this one struct.
___
*[pkg/server/server.go, line 1241 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/29692#-LMIdav0By3ktx2WHw4l:-LMIpd4zDTOPaZ85AjMP:bnlse4o) ([raw file](https://github.com/cockroachdb/cockroach/blob/35f0d426e7dd18ba24e7d0c04c4ec4378b48c8f1/pkg/server/server.go#L1241)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

regardless of the above, why not just inline this in `ui.Handler`?
</blockquote></details>

Same problem: accessing `webSessionUserKey{}` from `ui` would cause a dependency cycle. 
___
*[pkg/server/server_test.go, line 867 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/29692#-LMIcFQHBiU1_OkNQPeq:-LMIqdQwESLsbjk1gUPW:b-e3yv53) ([raw file](https://github.com/cockroachdb/cockroach/blob/35f0d426e7dd18ba24e7d0c04c4ec4378b48c8f1/pkg/server/server_test.go#L867)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

I think this would be clearer as two distinct functions, so the usage is just:

```
linkInFakeUI()
defer unlinkFakeUI()
```
</blockquote></details>

Done. FYI returning a cleanup closure is a Cockroach-ism (and maybe a Go-ism?) that we use all over the place:

  * https://github.com/cockroachdb/cockroach/blob/f565ab1fe170864bf71359358d61539902f999d5/pkg/server/server_test.go#L76
  * https://github.com/cockroachdb/cockroach/blob/f565ab1fe170864bf71359358d61539902f999d5/pkg/storage/replica.go#L5300-L5320
  * https://github.com/cockroachdb/cockroach/blob/f565ab1fe170864bf71359358d61539902f999d5/pkg/ccl/backupccl/backup_test.go#L209-L210
  * https://github.com/cockroachdb/cockroach/blob/5a013c1a85157daaef3b947e3c85a164dfffa94c/pkg/storage/engine/temp_engine_test.go#L29-L30

I also find this pattern kind of gross, so happy to defer to you here, but I've learned to live with it.

**Review by couchand — CHANGES_REQUESTED** [review]
LGTM

> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29692#-:-LMIutIkBQRbmvpmwjD-:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/server/server.go, line 1239 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/29692#-LMIeObu-_jShCtvdsNL:-LMIuJxC48ITi63-joUH:b6jvrat) ([raw file](https://github.com/cockroachdb/cockroach/blob/35f0d426e7dd18ba24e7d0c04c4ec4378b48c8f1/pkg/server/server.go#L1239)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

That would create a dependency cycle (server -> ui -> server), which is verboten in Go. We could extract a `serverconfig` package, but doesn't seem worth it for just this one struct.
</blockquote></details>

Oh I was thinking that was in `config`.  Okay.
___
*[pkg/server/server.go, line 1241 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/29692#-LMIdav0By3ktx2WHw4l:-LMIuLhp2g6AbJeTunBG:b-faj4cf) ([raw file](https://github.com/cockroachdb/cockroach/blob/35f0d426e7dd18ba24e7d0c04c4ec4378b48c8f1/pkg/server/server.go#L1241)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Same problem: accessing `webSessionUserKey{}` from `ui` would cause a dependency cycle. 
</blockquote></details>

that's unpleasant.
___
*[pkg/server/server_test.go, line 867 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/29692#-LMIcFQHBiU1_OkNQPeq:-LMIu68P47LRcNj-MXPY:b-qk7ri) ([raw file](https://github.com/cockroachdb/cockroach/blob/35f0d426e7dd18ba24e7d0c04c4ec4378b48c8f1/pkg/server/server_test.go#L867)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Done. FYI returning a cleanup closure is a Cockroach-ism (and maybe a Go-ism?) that we use all over the place:

  * https://github.com/cockroachdb/cockroach/blob/f565ab1fe170864bf71359358d61539902f999d5/pkg/server/server_test.go#L76
  * https://github.com/cockroachdb/cockroach/blob/f565ab1fe170864bf71359358d61539902f999d5/pkg/storage/replica.go#L5300-L5320
  * https://github.com/cockroachdb/cockroach/blob/f565ab1fe170864bf71359358d61539902f999d5/pkg/ccl/backupccl/backup_test.go#L209-L210
  * https://github.com/cockroachdb/cockroach/blob/5a013c1a85157daaef3b947e3c85a164dfffa94c/pkg/storage/engine/temp_engine_test.go#L29-L30

I also find this pattern kind of gross, so happy to defer to you here, but I've learned to live with it.
</blockquote></details>

oh gross.  it's at least less gross to name the return value.

**Review by benesch — COMMENTED** [review]
Thanks!

bors r=vilterp,couchand

> Dismissed @couchand from 5 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29692#-:-LMJ0ypr4DPzEMTED5Bp:b-owifvt)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/server/server_test.go, line 867 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/29692#-LMIcFQHBiU1_OkNQPeq:-LMJ0qHM9270kdfvacd1:b-nyox6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/35f0d426e7dd18ba24e7d0c04c4ec4378b48c8f1/pkg/server/server_test.go#L867)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

oh gross.  it's at least less gross to name the return value.
</blockquote></details>

Yep, though having `defer leaktest.AfterTest(t)()` at the top of every test really makes you numb to the non-named pattern.

**Comment by benesch** [comment]
Seems like a spurious roachtest failure.

bors r=vilterp,couchand

**Comment by couchand** [comment]
@benesch seems like we should backport this, no?

**Pull request merged**
