### PR TITLE
server: add size stats to database details

### PR DESCRIPTION
**Pull request by matthewtodd**
As we begin to build a new UI for viewing databases in the db console,
offering size information in the DatabaseDetails endpoint will save
the browser from making a TableStats call for every table in every
database.

Release note (api change): A Stats message was added to the admin
DatabaseDetails response, providing RangeCount and
ApproximateDiskBytes in support of upcoming UI changes to the db
console.

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
Looks good!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67986#-:-MfXxcGEC6y8gDEgxRhT:b-vs1prh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)

___
*[pkg/server/admin.go, line 555 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67986#-MfXwQJA6h9LTV36qyR6:-MfXwQJA6h9LTV36qyR7:bfac51d) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2a1501d2e82b0fe279989985e59e5d5c9980a71/pkg/server/admin.go#L555)):*
> ```Go
> 			})
> 
> 		if err != nil {
> ```

very minor style nit: you can/should collapse this with the previous call:

```
if err := s.server.stopper.RunAsyncTask(
...
}); err != nil {
   return nil, err
}
```
___
*[pkg/server/admin_cluster_test.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67986#-MfXw8zl7cUgGrm9YLAm:-MfXw8zl7cUgGrm9YLAn:b538s3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2a1501d2e82b0fe279989985e59e5d5c9980a71/pkg/server/admin_cluster_test.go#L56)):*
> ```Go
> 		t.Fatal(err)
> 	}
> 	client.Timeout = time.Hour // basically no timeout
> ```

Maybe decrease this to prevent accidental long test timeouts?
___
*[pkg/server/serverpb/admin.proto, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67986#-MfNkDfq4u9ioLLauDnB:-MfNkDfq4u9ioLLauDnC:b-wtrpwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2a1501d2e82b0fe279989985e59e5d5c9980a71/pkg/server/serverpb/admin.proto#L54)):*
> ```protobuf
> message DatabaseDetailsRequest {
>   // database is the name of the database we are querying.
>   string database = 1;
> ```

Thoughts on adding some kind of boolean `RequestStats` to this message? I'm not sure if every `DatabaseDetails` call needs the stats, but it would be nice to provide the option to skip loading the stats as they're still fairly expensive.

**Review by Azhng — COMMENTED** [review]
:heart_eyes_cat: 

> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67986#-:-MfYAzNmDxUof7-7zPGx:b-uuy62b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)

___
*[pkg/server/admin.go, line 516 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67986#-MfY1KhgCTD6M_9dK8BG:-MfY1KhgCTD6M_9dK8BH:bokz5dj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2a1501d2e82b0fe279989985e59e5d5c9980a71/pkg/server/admin.go#L516)):*
> ```Go
> 
> 	for _, tableName := range tableNames {
> 		escQualTable, err := getFullyQualifiedTableName(dbName, tableName)
> ```

nit: what does `escQualTable` mean exactly? 
___
*[pkg/server/admin_cluster_test.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67986#-MfYAB9B8uxKaRAcSi0L:-MfYAB9B8uxKaRAcSi0M:b-3mb6zz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2a1501d2e82b0fe279989985e59e5d5c9980a71/pkg/server/admin_cluster_test.go#L39)):*
> ```Go
> 
> 	db := tc.ServerConn(0)
> 	if _, err := db.Exec("CREATE DATABASE test"); err != nil {
> ```

nit: `require.NoError()` can be used here to remove some `err` check 
___
*[pkg/server/admin_cluster_test.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67986#-MfYAXqs2vW91ouhtV9H:-MfYAXqs2vW91ouhtV9I:b-izp7ke) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2a1501d2e82b0fe279989985e59e5d5c9980a71/pkg/server/admin_cluster_test.go#L52)):*
> ```Go
> 
> 	server0 := tc.Server(0)
> 	client, err := server0.GetAdminAuthenticatedHTTPClient()
> ```

nit: maybe we can use `getAdminJSONProto()` helper here?

**Review by matthewtodd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67986)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/server/admin.go, line 516 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67986#-MfY1KhgCTD6M_9dK8BG:-MfYNlfaAAYYsP4DLpJH:b5uh72c) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2a1501d2e82b0fe279989985e59e5d5c9980a71/pkg/server/admin.go#L516)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: what does `escQualTable` mean exactly? 
</blockquote></details>

Good point! I had lifted this code from somewhere else, but I didn't like the name either. Adjusted to `fullyQualifiedTableName`.
___
*[pkg/server/admin.go, line 555 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67986#-MfXwQJA6h9LTV36qyR6:-MfYO71M37UqH5Qa6ePH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2a1501d2e82b0fe279989985e59e5d5c9980a71/pkg/server/admin.go#L555)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

very minor style nit: you can/should collapse this with the previous call:

```
if err := s.server.stopper.RunAsyncTask(
...
}); err != nil {
   return nil, err
}
```
</blockquote></details>

Done.
___
*[pkg/server/admin_cluster_test.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67986#-MfYAB9B8uxKaRAcSi0L:-MfYO9OcAn_nJFLWAzVD:bpbn0zd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2a1501d2e82b0fe279989985e59e5d5c9980a71/pkg/server/admin_cluster_test.go#L39)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: `require.NoError()` can be used here to remove some `err` check 
</blockquote></details>

Thanks, looks much better.
___
*[pkg/server/admin_cluster_test.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67986#-MfYAXqs2vW91ouhtV9H:-MfYODhK5utOtvM6IeK6:b31usuz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2a1501d2e82b0fe279989985e59e5d5c9980a71/pkg/server/admin_cluster_test.go#L52)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: maybe we can use `getAdminJSONProto()` helper here? 
</blockquote></details>

Ooh, yes, found `serverutils.GetJSONProto()`. (`getAdminJSONProto` looks like it does the same thing but isn't visible here.)
___
*[pkg/server/admin_cluster_test.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67986#-MfXw8zl7cUgGrm9YLAm:-MfYOnFQB_39SfTBnF5x:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2a1501d2e82b0fe279989985e59e5d5c9980a71/pkg/server/admin_cluster_test.go#L56)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Maybe decrease this to prevent accidental long test timeouts?
</blockquote></details>

Done.
___
*[pkg/server/serverpb/admin.proto, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67986#-MfNkDfq4u9ioLLauDnB:-MfYOrq64l14RQtmNnh4:b-o5rere) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2a1501d2e82b0fe279989985e59e5d5c9980a71/pkg/server/serverpb/admin.proto#L54)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Thoughts on adding some kind of boolean `RequestStats` to this message? I'm not sure if every `DatabaseDetails` call needs the stats, but it would be nice to provide the option to skip loading the stats as they're still fairly expensive.
</blockquote></details>

Done, wdyt about `IncludeStats`?

**Review by jordanlewis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67986#-:-MfYqgAo8om8J98zByun:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

**Review by Azhng — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67986)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

**Pull request merged**
