### PR TITLE
opt: adjust cost of scan with unbounded cardinality to avoid bad plans

### LINKED ISSUE #68556: opt: unbounded max cardinality penalty makes number of index columns dominate scan cost
In #66979 we introduced an `unboundedMaxCardinalityScanRowCountPenalty` to constrained scans that have an unbounded cardinality. This increased the likelihood that, with stale table statistics, the optimizer would choose a plan with a scan on a primary index or unique secondary index with a bounded number of potential rows scanned over a scan on a non-unique secondary index with an unbounded number of potential rows scanned.

This change had a negative side-effect. With stale table statistics that make a query look extremely selective (e.g., filtering for a value greater than the maximum histogram upper-bound), the number of columns in an index dominates the cost of a scan. This causes the optimizer to favor a scan over a few columns over a scan with more columns, even if the former requires an addition filter and/or index join after the scan. 

The test below shows that the index with fewer columns is chosen even though an extra select is needed. See the [`optstepsweb` output](https://raduberinde.github.io/optsteps.html?eJzkmNlu2zgUhu_nKc7oKh6ZtigvSQQE8CBxZgJkMmlcoBexEcgyDTCVKUNi2hRFgSDP4Ms-XZ6k0L6R8pLFDuorWUdc9PN8_yH1XRl8OFcMZdA_7x9_hL_g9Or__4DDp3_7V30w4Qgwhr8vTmAcXCp15cJxZyd0OlUMBSEEZvOMUU5Ne8hUVYVx-rfXA4RBxXXcgV5vyNS569wSiw-ZCk-Ln0-Lh6fFA1iOfTdjngGfDfwnu7NtMA09vBgbrfDCMtr5Rh43uWfAtet89Y4wQdrhqNirxw3AGGt6t6FFrRdxa2JH0wh-a88FLHcyvqGME5eZ9s3si2XdcDojHjdnc6MD3BzbxKEToysYozz1Okyoxymz-J5ei2_5Y_l_tUy0lY-28lG9XogHN7SR8D2z6rREs7RMBlmJHldQyhdpY30eq2TS_F_mXXHtqBW9JS6oUPOfluuXxITqhcNI1ItmuCiIqAUi4syD8RNTanPiekmkEN7zJfOhqgWA7fnqBX-HLARrQGdzm06_DYJ8PU16CzCTBAPofOJ87roBd5Bwt0Gu5xsJuUPLuBMHO2HXRSjhDaAsjbEFKNH6UJbELb9HhC28NrayAXYH2-IMpdiWuEywRetim-c81iR-XuYDcQcx9pfuHSMh1seOnQBfuh2h3t0J1DtC1LVDTe80uhLUBQi8fv1dQ4ydN4m23CQi5atMAm2rtlcO8B68pajc8i2B-EHtIFikShOCJZ4CK3lK36YzykxOLpM9eGAq5fs5V9EDV0Hpxj2t0hsQhTawl9RB0As6iKDlDtGdslue5XPYlTd7N2ilxKAVy3aZGHFZT4mpPmi-wWmtIiFU4Rlt3TQQtNidDFBXWHy14pRVsfESrbZSV_r3c9txSe6jxj-EEdfk5IxNyP3AMlmyDxNFItPUM6YJz7LKLTvTElMS52D-Xs8cW2FH61b_Hc7N1Uq5vIpXFHB57Y4T7thhHndNyshEmJDleDYtwwMCSr59FVfpWd_jrHhobkBTb7aa2IDrJsZNjAFBeDHaelbLtxeSrEYbFNgdzl60UlmVV9SKYiqro4Vx2o2DF07r-OD7nt127bwUbBHajW7bX_P9fJT6RQrdOjT6LPTb5fPSrQ5B2v5IsomKldUzyhYGjGzUd9EkuvRMUjZScbuMqSaWGvrpSN6s_HrlFN3PSC3oqkRtN9BfVtw2tYdCKG2l_PjjVwAAAP__jNMo0w==) too.

```
exec-ddl
CREATE TABLE t (
  k INT PRIMARY KEY,
  a INT,
  b INT,
  c INT,
  INDEX abc (a, b) STORING (c),
  INDEX bc (b) STORING (c)
)
----

# Inject stats for 100k rows where the upper bound of both a and b is 10.
exec-ddl
ALTER TABLE t INJECT STATISTICS '[
    {
        "columns": [
            "k"
        ],
        "created_at": "2021-06-28 14:20:18.273949",
        "distinct_count": 3,
        "histo_col_type": "INT8",
        "null_count": 0,
        "row_count": 100000
    },
    {
        "columns": [
            "a"
        ],
        "created_at": "2021-06-28 14:20:18.273949",
        "distinct_count": 100,
        "histo_buckets": [
            {"distinct_range": 0, "num_eq": 0, "num_range": 0, "upper_bound": "0"},
            {"distinct_range": 100, "num_eq": 0, "num_range": 100000, "upper_bound": "10"}
        ],
        "histo_col_type": "INT8",
        "null_count": 0,
        "row_count": 100000
    },
    {
        "columns": [
            "b"
        ],
        "created_at": "2021-06-28 14:20:18.273949",
        "distinct_count": 100,
        "histo_buckets": [
            {"distinct_range": 0, "num_eq": 0, "num_range": 0, "upper_bound": "0"},
            {"distinct_range": 100, "num_eq": 0, "num_range": 100000, "upper_bound": "10"}
        ],
        "histo_col_type": "INT8",
        "null_count": 0,
        "row_count": 100000
    }
]'
----

# Query for values of a and b that are outside the histogram buckets.
# A scan on the bc index with an additional filter and index join is chosen over
# a scan on the abc index with no additional filter and no index join.
opt format=(show-cost,show-stats)
SELECT * FROM t WHERE a = 11 AND b = 11
----
select
 ├── columns: k:1!null a:2!null b:3!null c:4
 ├── stats: [rows=1e-09, distinct(2)=1e-09, null(2)=0, distinct(3)=1e-09, null(3)=0, distinct(2,3)=1e-09, null(2,3)=0]
 ├── cost: 14.6400007
 ├── index-join t
 │    ├── columns: k:1!null a:2 b:3 c:4
 │    ├── stats: [rows=1e-07]
 │    ├── cost: 14.6200007
 │    └── scan t@bc
 │         ├── columns: k:1!null b:3!null c:4
 │         ├── constraint: /3/1: [/11 - /11]
 │         ├── stats: [rows=1e-07, distinct(3)=1e-07, null(3)=0]
 │         └── cost: 14.6100001
 └── filters
      └── a:2 = 11
```

### PR DESCRIPTION
**Pull request by rytaft**
This commit tweaks the application of the unbounded cardinality penalty
in the coster to add it directly to the cost of scans and zigzag joins
rather than to the row count. This helps prevent an issue in which the
number of index columns could dominate the scan cost and result in
suboptimal plans.

Fixes #68556

Release note (bug fix): Fixed a regression in the optimizer's cost model
that could cause it to choose suboptimal plans when choosing between two
non-unique index scans with different numbers of columns per index.

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
Nice! :lgtm: 

> Reviewed 40 of 40 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68676#-:-MgmGuSP-fIrkQDYwyvL:bfd61qr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @rytaft)

___
*[pkg/sql/opt/xform/coster.go, line 663 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68676#-MgmGMF21N7snOuP5ken:-MgmGMF21N7snOuP5keo:b-4f4w75) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab1ebda945068cb812c2599e9e855cfa74decdcd/pkg/sql/opt/xform/coster.go#L663)):*
> ```Go
> 	// number of index columns does not have an outsized effect on the cost of
> 	// the scan. See issue #68556.
> 	baseCost += memo.Cost(c.largeCardinalityCostPenalty(scan.Relational().Cardinality, rowCount))
> ```

nit: if `c.LargeCardinalityCostPenalty()` returns a `memo.Cost` instead of a `float64`, this line is simplified.
___
*[pkg/sql/opt/xform/coster.go, line 1069 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68676#-MgmGU5y2nCzeS-G19Hs:-MgmGU5y2nCzeS-G19Ht:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab1ebda945068cb812c2599e9e855cfa74decdcd/pkg/sql/opt/xform/coster.go#L1069)):*
> ```Go
> 	// the number of index columns does not have an outsized effect on the cost of
> 	// the zigzag join. See issue #68556.
> 	cost += memo.Cost(c.largeCardinalityCostPenalty(join.Relational().Cardinality, rowCount))
> ```

ditto

**Review by rytaft — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68676#-:-MgmImRa0tZSWGZIe0uf:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @michae2)

___
*[pkg/sql/opt/xform/coster.go, line 663 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68676#-MgmGMF21N7snOuP5ken:-MgmIfNCC6W1ypBDqibn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab1ebda945068cb812c2599e9e855cfa74decdcd/pkg/sql/opt/xform/coster.go#L663)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: if `c.LargeCardinalityCostPenalty()` returns a `memo.Cost` instead of a `float64`, this line is simplified.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/coster.go, line 1069 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68676#-MgmGU5y2nCzeS-G19Hs:-MgmIgKM9C9WKCBlDaGp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab1ebda945068cb812c2599e9e855cfa74decdcd/pkg/sql/opt/xform/coster.go#L1069)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by mgartner — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68676)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2)

**Pull request merged**
