### PR TITLE
cmd/roachtest: refactor nightly tests into roachtest tool

### PR DESCRIPTION
**Pull request by petermattis**
This converts the tests in the `nightly` package to a new `roachtest`
tool. At this point, the functionality is equivalent, leaving little
reason to prefer one approach over the other. Future work is to improve
the control over parallelism and provide better control of test output.

Release note: None

### CODE REVIEW

**Comment by benesch** [comment]
:lgtm_strong: 

Are you intentionally leaving pkg/nightly around for now?

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/cmd/roachtest/main.go, line 54 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5APP61lS9jcuOMrJvB:-L5APP61lS9jcuOMrJvC:bkz4eej) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7bcfca3f12566a8d382269571e0083de811854d/pkg/cmd/roachtest/main.go#L54)):*
> ```Go
> 
> 	runCmd.Flags().BoolVarP(
> 		&dryrun, "dryrun", "n", dryrun, "dry run (don't run tests)")
> ```

really nitty nit: since these are POSIX flags now, not Go flags, I like `--dry-run` better.

---

*[pkg/cmd/roachtest/main.go, line 66 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5APTrEMDU8_rsgdklb:-L5APTrEMDU8_rsgdklc:b-rq9k2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7bcfca3f12566a8d382269571e0083de811854d/pkg/cmd/roachtest/main.go#L66)):*
> ```Go
> 		&workload, "workload", "", "path to workload binary to use")
> 	runCmd.Flags().StringVar(
> 		&clusterID, "clusterid", "", "an identifier to use in the test cluster's name")
> ```

Likewise, `--cluster-id` reads better to me here.

---

*[pkg/cmd/roachtest/test.go, line 98 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5ARVzf8iATtxHBWS1t:-L5ARVzf8iATtxHBWS1u:by9t2ki) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7bcfca3f12566a8d382269571e0083de811854d/pkg/cmd/roachtest/test.go#L98)):*
> ```Go
> 		for _, t := range tests {
> 			sem <- struct{}{}
> 			fmt.Printf("=== RUN: %s\n", t.name)
> ```

This isn't quite `go test` compatible.

```
"=== RUN   %s\n"
```

---

*[pkg/cmd/roachtest/test.go, line 218 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5ARhru9qcvTLlKyhLh:-L5ARhru9qcvTLlKyhLi:bch58fi) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7bcfca3f12566a8d382269571e0083de811854d/pkg/cmd/roachtest/test.go#L218)):*
> ```Go
> 					fmt.Printf("--- %s: FAIL\n%s", t.name, t.mu.output)
> 				} else {
> 					fmt.Printf("--- %s: PASS\n", t.name)
> ```

Likewise, for `go test` compatibility, these should be `--- PASS: %s\n` and `--- FAIL: %s\n`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-:-L5APGhruYkNYL0Lv0n9:bb6xo19)*

**Comment by petermattis** [comment]
> Are you intentionally leaving pkg/nightly around for now?

No strong reason. I'll get rid of it before merging this PR.

---

Review status: 2 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/cmd/roachtest/main.go, line 54 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5APP61lS9jcuOMrJvB:-L5AToD6unoRwYwLsNS3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7bcfca3f12566a8d382269571e0083de811854d/pkg/cmd/roachtest/main.go#L54)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

really nitty nit: since these are POSIX flags now, not Go flags, I like `--dry-run` better.
</blockquote></details>

Done.

---

*[pkg/cmd/roachtest/main.go, line 66 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5APTrEMDU8_rsgdklb:-L5AToYe8EilkCsBd2qS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7bcfca3f12566a8d382269571e0083de811854d/pkg/cmd/roachtest/main.go#L66)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Likewise, `--cluster-id` reads better to me here.
</blockquote></details>

Done.

---

*[pkg/cmd/roachtest/test.go, line 98 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5ARVzf8iATtxHBWS1t:-L5ATpsj_gmi7M2slhjm:bw10jn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7bcfca3f12566a8d382269571e0083de811854d/pkg/cmd/roachtest/test.go#L98)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This isn't quite `go test` compatible.

```
"=== RUN   %s\n"
```
</blockquote></details>

Oops, done.

---

*[pkg/cmd/roachtest/test.go, line 218 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5ARhru9qcvTLlKyhLh:-L5ATqlVNCVym8krQFMm:b578l02) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7bcfca3f12566a8d382269571e0083de811854d/pkg/cmd/roachtest/test.go#L218)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Likewise, for `go test` compatibility, these should be `--- PASS: %s\n` and `--- FAIL: %s\n`.
</blockquote></details>

Oops, done. I also want to include the duration ala `go test`. Will add shortly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-:-L5ATxSYVOF1FDFgTYa1:b-a69v98)*

**Comment by benesch** [comment]
Reviewed 6 of 6 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593)*

**Comment by petermattis** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[build/nightly-workload.sh, line 34 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5Ab4Z50XA4GzCTR9Cy:-L5Ab4Z50XA4GzCTR9Cz:bwqldfz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4a020337f336ab71b4becb5e484dd9498846090/build/nightly-workload.sh#L34)):*
> ```Shell
> make bin/roachtest bin/workload
> 
> bin/roachtest run \
> ```

@benesch How do I tell teamcity to run this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593)*

**Comment by danhhz** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[build/nightly-workload.sh, line 34 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5Ab4Z50XA4GzCTR9Cy:-L5AbcJ56atW_iXIGSSi:befpw67) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4a020337f336ab71b4becb5e484dd9498846090/build/nightly-workload.sh#L34)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

@benesch How do I tell teamcity to run this?
</blockquote></details>

https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_Nightlies_WorkloadNightly&branch_Cockroach_Nightlies=22593&tab=buildTypeStatusDiv

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593)*

**Comment by benesch** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[build/nightly-workload.sh, line 34 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5Ab4Z50XA4GzCTR9Cy:-L5AbiE9I1HGlWjE92Dk:b-n6wmak) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4a020337f336ab71b4becb5e484dd9498846090/build/nightly-workload.sh#L34)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_Nightlies_WorkloadNightly&branch_Cockroach_Nightlies=22593&tab=buildTypeStatusDiv
</blockquote></details>

Click run here: https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_Nightlies_WorkloadNightly&branch_Cockroach_Nightlies=22593&tab=buildTypeStatusDiv 

In general, you can use the branch selector to pull up any PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593)*

**Comment by danhhz** [comment]
approach lgtm. i likely won't get a chance to review before tomorrow, but benesch's lgtm is good enough for me if you want to merge today

---

Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-:-L5Aprm_IuLWuHftOlba:bxm8894)*

**Comment by petermattis** [comment]
@benesch I added an initial commit which moved the files from `nightly` to `cmd/roachtest`. Hopefully this will maintain some of the git history.

---

Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-:-L5B4kxR-Pd5Hpsqy8Ag:bo37ji7)*

**Comment by benesch** [comment]
Reviewed 4 of 15 files at r4, 8 of 10 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593)*

**Comment by petermattis** [comment]
@benesch Do you see what is going on with the testrace failure on teamcity? https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=518494&_focus=799

Seems like "Determine changed packages" isn't happy. Perhaps something to do with the `nightly` package being removed.

**Comment by tschottdorf** [comment]
I thought `testing` would bleed around less now, but it looks the same. You're using this mostly to eagerly terminate tests, right?

> Seems like "Determine changed packages" isn't happy. Perhaps something to do with the nightly package being removed.

Yeah, there's a bug there that I also ran into once. My solution then was a shameful god merge.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/cmd/roachtest/cluster.go, line 283 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5Ce-NvQFZ5dTEAF-fr:-L5Ce-NwG0iIwYr4mehD:b-nmzaur) ([raw file](https://github.com/cockroachdb/cockroach/blob/90fe865886c55926ca0e1bef11d250c327c7c67b/pkg/cmd/roachtest/cluster.go#L283)):*
> ```Go
> }
> 
> func newMonitor(ctx context.Context, c *cluster) *monitor {
> ```

This looks pretty good, but it's unfortunate that this gets passed the whole `*cluster`.

---

*[pkg/cmd/roachtest/cluster.go, line 296 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5CjgkjD2GVoOoPO3EO:-L5CjgkjD2GVoOoPO3EP:b-m747fa) ([raw file](https://github.com/cockroachdb/cockroach/blob/90fe865886c55926ca0e1bef11d250c327c7c67b/pkg/cmd/roachtest/cluster.go#L296)):*
> ```Go
> }
> 
> func (m *monitor) Wait(t *testing.T, nodes ...int) {
> ```

wait, how is `*testing.T` a thing here?

---

*[pkg/cmd/roachtest/cluster.go, line 310 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5CeHyMiFUTqSyUIk55:-L5CeHyMiFUTqSyUIk56:biss87m) ([raw file](https://github.com/cockroachdb/cockroach/blob/90fe865886c55926ca0e1bef11d250c327c7c67b/pkg/cmd/roachtest/cluster.go#L310)):*
> ```Go
> }
> 
> func (m *monitor) wait(t *testing.T, nodes []int, args ...string) error {
> ```

Have you considered polling instead here? That is, processes are spawned asynchronously; we periodically check that they're still there; and they record their exit code somewhere (artifacts under a `<binname>.<pid>` probably). This may seem a little clunky at first, but it frees us from the requirement that the test runner be present all the time. If we're running multi-day or even weeks of testing it's hard to keep the test runner alive, and as written it's hard to say "set me up this cluster with this benchmark workload running basically forever". Instead, the test runner just sets things in motion and then periodically checks on them (and if it dies, the test continues, it's just not monitored in the same way).
It'd also help avoid random test failures when on bad connections.

---

*[pkg/cmd/roachtest/cluster.go, line 322 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5CmMOPmdIdq8Fuv2zE:-L5CmMOPmdIdq8Fuv2zF:b-o5j7xn) ([raw file](https://github.com/cockroachdb/cockroach/blob/90fe865886c55926ca0e1bef11d250c327c7c67b/pkg/cmd/roachtest/cluster.go#L322)):*
> ```Go
> 	//   g, _ := errgroup.WithContext(m.ctx)
> 	//   g.Go(func(context.Context) error {
> 	//     defer m.cancel()
> ```

Removing this line here, wouldn't spawning a goroutine in the main thread that calls `g.Wait` followed by `m.cancel` do the right thing? You want to make sure the context is cancelled after the errgroup is spent, and your problem is that you're cancelling the context before the errgroup is spent. This seems too obvious, so probably missing something.

---

*[pkg/cmd/roachtest/roachmart.go, line 89 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5ChDsVz1phWv31p21v:-L5ChDsW_iBiRuuoPgV9:b-vshnmp) ([raw file](https://github.com/cockroachdb/cockroach/blob/90fe865886c55926ca0e1bef11d250c327c7c67b/pkg/cmd/roachtest/roachmart.go#L89)):*
> ```Go
> }
> 
> func TestRoachmart(t *testing.T) {
> ```

These tests still look good (mod the opacity around `start`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-:-L5CgkNXmTKpYtppJXCX:bgmlybm)*

**Comment by petermattis** [comment]
> I thought testing would bleed around less now, but it looks the same. You're using this mostly to eagerly terminate tests, right?

Yep.

> > Seems like "Determine changed packages" isn't happy. Perhaps something to do with the nightly package being removed.
> 
> Yeah, there's a bug there that I also ran into once. My solution then was a shameful god merge.

@benesch Help! (Or should I god-mode merge this).

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/cmd/roachtest/cluster.go, line 283 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5Ce-NvQFZ5dTEAF-fr:-L5EKVKAiqr0Ejc4pFvx:b-dx5yj4) ([raw file](https://github.com/cockroachdb/cockroach/blob/90fe865886c55926ca0e1bef11d250c327c7c67b/pkg/cmd/roachtest/cluster.go#L283)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

This looks pretty good, but it's unfortunate that this gets passed the whole `*cluster`.
</blockquote></details>

The cluster is used for two purposes: access to `cluster.t` for fatal errors and `cluster.selector` for node selection. I think I could pass in the node selection to the constructor (I want to rework node selection to make it a bit more general) and then I could pass in a `*test` instead of a `*cluster`. Future PR work.

---

*[pkg/cmd/roachtest/cluster.go, line 296 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5CjgkjD2GVoOoPO3EO:-L5EKoRwZMxHUsFKGkbN:bb71nsf) ([raw file](https://github.com/cockroachdb/cockroach/blob/90fe865886c55926ca0e1bef11d250c327c7c67b/pkg/cmd/roachtest/cluster.go#L296)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

wait, how is `*testing.T` a thing here?
</blockquote></details>

This was just the initial fork from the `nightly` package. The next commit gets rid of usage of `testing.T`.

---

*[pkg/cmd/roachtest/cluster.go, line 310 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5CeHyMiFUTqSyUIk55:-L5EL35b1Rbn3Z38ArGS:b-b5xi0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/90fe865886c55926ca0e1bef11d250c327c7c67b/pkg/cmd/roachtest/cluster.go#L310)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Have you considered polling instead here? That is, processes are spawned asynchronously; we periodically check that they're still there; and they record their exit code somewhere (artifacts under a `<binname>.<pid>` probably). This may seem a little clunky at first, but it frees us from the requirement that the test runner be present all the time. If we're running multi-day or even weeks of testing it's hard to keep the test runner alive, and as written it's hard to say "set me up this cluster with this benchmark workload running basically forever". Instead, the test runner just sets things in motion and then periodically checks on them (and if it dies, the test continues, it's just not monitored in the same way).
It'd also help avoid random test failures when on bad connections.
</blockquote></details>

That's more or less what `roachprod monitor` does internally (it uses `nc` to avoid polling unless there is a change in the network endpoint). Enhancing this so that you can reconnect to the monitor is something that we could investigate. I agree that it is a bit irritating to require `roachtest` to continuously run while the test is in progress. I definitely want to figure out a way to get rid of that. `roachperf test` allowed restarting tests, but only in a very limited fashion. 

---

*[pkg/cmd/roachtest/cluster.go, line 322 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5CmMOPmdIdq8Fuv2zE:-L5ELaUB6QbPvN1c3mQb:b-j2i4il) ([raw file](https://github.com/cockroachdb/cockroach/blob/90fe865886c55926ca0e1bef11d250c327c7c67b/pkg/cmd/roachtest/cluster.go#L322)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Removing this line here, wouldn't spawning a goroutine in the main thread that calls `g.Wait` followed by `m.cancel` do the right thing? You want to make sure the context is cancelled after the errgroup is spent, and your problem is that you're cancelling the context before the errgroup is spent. This seems too obvious, so probably missing something.
</blockquote></details>

You need to `cancel` to unblock the other worker goroutines. And you need to unblock the other worker goroutines so that the monitor itself exits. I'm not particularly thrilled with the complexity here, but it works. `make stress PKG=./cmd/roachtest TESTS=TestClusterMonitor` uncovered lots of interactions here. 

---

*[pkg/cmd/roachtest/roachmart.go, line 89 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5ChDsVz1phWv31p21v:-L5ELwLBGiA7Vwv9x2lt:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/90fe865886c55926ca0e1bef11d250c327c7c67b/pkg/cmd/roachtest/roachmart.go#L89)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

These tests still look good (mod the opacity around `start`).
</blockquote></details>

Ack.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-:-L5EKErtEoeG4rP3dyLR:blbs4wi)*

**Comment by benesch** [comment]
Looking now!

**Comment by benesch** [comment]
Ugh, sorry. Can you sidecar this diff into this PR?

```diff
diff --git a/build/teamcity-support.sh b/build/teamcity-support.sh
index f385e9faf..793fa551f 100644
--- a/build/teamcity-support.sh
+++ b/build/teamcity-support.sh
@@ -26,7 +26,7 @@ changed_go_pkgs() {
   git diff --name-only origin/master... -- "pkg/**/*.go" \
     | xargs -rn1 dirname \
     | sort -u \
-    | { while read path; do ls "$path"/*.go &>/dev/null && echo -n "./$path "; done; }
+    | { while read path; do if ls "$path"/*.go &>/dev/null; then echo -n "./$path "; fi; done; }
 }
 
 tc_release_branch() {
```

**Comment by danhhz** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/cmd/roachtest/kv.go, line 99 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5ElNNV59CXVrjU9Oa_:-L5ElNNV59CXVrjU9Oaa:b3a6rxt) ([raw file](https://github.com/cockroachdb/cockroach/blob/df40d1dd4fcb515e8968e506eb1a5f5476be9c85/pkg/cmd/roachtest/kv.go#L99)):*
> ```Go
> 		if !local {
> 			var wg sync.WaitGroup
> 			wg.Add(6)
> ```

why 6? can this be a named constant instead

---

*[pkg/cmd/roachtest/kv.go, line 115 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5ElUUBINYS6xM2x0vX:-L5ElUUBINYS6xM2x0vY:b-tl655z) ([raw file](https://github.com/cockroachdb/cockroach/blob/df40d1dd4fcb515e8968e506eb1a5f5476be9c85/pkg/cmd/roachtest/kv.go#L115)):*
> ```Go
> 		c.Put(ctx, workload, "<workload>")
> 
> 		for i := nodes; i <= nodes*64; i += nodes {
> ```

ditto 64

---

*[pkg/cmd/roachtest/main.go, line 60 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5Em-nPp_6VhqGsrS9d:-L5Em-nPp_6VhqGsrS9e:bbp3p1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/df40d1dd4fcb515e8968e506eb1a5f5476be9c85/pkg/cmd/roachtest/main.go#L60)):*
> ```Go
> 		&parallelism, "parallelism", "p", parallelism, "number of tests to run in parallel")
> 	runCmd.Flags().StringVar(
> 		&artifacts, "artifacts", "", "path to artifacts direcdtory")
> ```

nit: directory

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-:-L5EnZqHE3eSV9gwYrxo:bnfp4nl)*

**Comment by petermattis** [comment]
@benesch ok, trying that out.

---

Review status: 13 of 14 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-:-L5ErMkOmF1TCHbdr5ZQ:bsz0zwt)*

**Comment by tschottdorf** [comment]
Review status: 13 of 14 files reviewed at latest revision, 10 unresolved discussions.

---

*[pkg/cmd/roachtest/cluster.go, line 285 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5Eq0-xmQrVluFOL_NX:-L5Eq0-xmQrVluFOL_NY:b-v5cfc5) ([raw file](https://github.com/cockroachdb/cockroach/blob/90fe865886c55926ca0e1bef11d250c327c7c67b/pkg/cmd/roachtest/cluster.go#L285)):*
> ```Go
> func newMonitor(ctx context.Context, c *cluster) *monitor {
> 	m := &monitor{c: c}
> 	m.ctx, m.cancel = context.WithCancel(ctx)
> ```

Sorry for barking up this tree again, but https://godoc.org/golang.org/x/sync/errgroup#WithContext says that `m.ctx` is cancelled when `m.g` sees the first non-nil error (or everything finishes). This seems like it should be able to avoid the errgroup cancellation dance you're doing below (and also not require an explicit cancel). I think that maybe you want to create your top-level errgroup `g` here, and make its context a parent of `m.g`s. That way, when `g` sees an error, `m.g` will tear down since its parent context cancels. Similarly, if `m.g` observes an error, all of its other tasks will see their context cancelled, and so `g` will see `Wait` return with the correct error, and then correctly propagates that (since its context isn't cancelled yet). I'm happy to take a stab at that myself once this is merged as to avoid distracting you further.

```go
m := &monitor{c: c}
var g errgroup.Group
g, ctx = errgroup.WithContext(ctx)
m.g, ctx = errgroup.WithContext(ctx)

m.g.Go(...)
m.g.Go(...)
m.g.Go(...)

g.Go(func() error { return m.g.Wait() })
g.Go(func() error { return monitorSomethingElse() }) // if this errors, m.g's ctx will cancel immediately, causing m.g.Wait to return soon
```

---

*[pkg/cmd/roachtest/cluster.go, line 322 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5CmMOPmdIdq8Fuv2zE:-L5EnVZtsybZET0LBg77:bo5twdb) ([raw file](https://github.com/cockroachdb/cockroach/blob/90fe865886c55926ca0e1bef11d250c327c7c67b/pkg/cmd/roachtest/cluster.go#L322)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You need to `cancel` to unblock the other worker goroutines. And you need to unblock the other worker goroutines so that the monitor itself exits. I'm not particularly thrilled with the complexity here, but it works. `make stress PKG=./cmd/roachtest TESTS=TestClusterMonitor` uncovered lots of interactions here. 
</blockquote></details>

Ah, I misremembered how `Wait` works. I thought it would return eagerly on first error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593)*

**Comment by petermattis** [comment]
Review status: 4 of 14 files reviewed at latest revision, 10 unresolved discussions.

---

*[pkg/cmd/roachtest/cluster.go, line 285 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5Eq0-xmQrVluFOL_NX:-L5EsTldxSNCdzCmd3Mn:b-edsrt6) ([raw file](https://github.com/cockroachdb/cockroach/blob/90fe865886c55926ca0e1bef11d250c327c7c67b/pkg/cmd/roachtest/cluster.go#L285)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Sorry for barking up this tree again, but https://godoc.org/golang.org/x/sync/errgroup#WithContext says that `m.ctx` is cancelled when `m.g` sees the first non-nil error (or everything finishes). This seems like it should be able to avoid the errgroup cancellation dance you're doing below (and also not require an explicit cancel). I think that maybe you want to create your top-level errgroup `g` here, and make its context a parent of `m.g`s. That way, when `g` sees an error, `m.g` will tear down since its parent context cancels. Similarly, if `m.g` observes an error, all of its other tasks will see their context cancelled, and so `g` will see `Wait` return with the correct error, and then correctly propagates that (since its context isn't cancelled yet). I'm happy to take a stab at that myself once this is merged as to avoid distracting you further.

```go
m := &monitor{c: c}
var g errgroup.Group
g, ctx = errgroup.WithContext(ctx)
m.g, ctx = errgroup.WithContext(ctx)

m.g.Go(...)
m.g.Go(...)
m.g.Go(...)

g.Go(func() error { return m.g.Wait() })
g.Go(func() error { return monitorSomethingElse() }) // if this errors, m.g's ctx will cancel immediately, causing m.g.Wait to return soon
```
</blockquote></details>

Ack. I await your PR.

---

*[pkg/cmd/roachtest/kv.go, line 99 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5ElNNV59CXVrjU9Oa_:-L5ErZxRVoFhRl4Nyedc:bkzhza9) ([raw file](https://github.com/cockroachdb/cockroach/blob/df40d1dd4fcb515e8968e506eb1a5f5476be9c85/pkg/cmd/roachtest/kv.go#L99)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

why 6? can this be a named constant instead
</blockquote></details>

That sould be `nodes`. Fixed.

---

*[pkg/cmd/roachtest/kv.go, line 115 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5ElUUBINYS6xM2x0vX:-L5Ergo_ognf4dz-mMdJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/df40d1dd4fcb515e8968e506eb1a5f5476be9c85/pkg/cmd/roachtest/kv.go#L115)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

ditto 64
</blockquote></details>

Done.

---

*[pkg/cmd/roachtest/main.go, line 60 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593#-L5Em-nPp_6VhqGsrS9d:-L5Es6ff-N0WxbgSF8SB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/df40d1dd4fcb515e8968e506eb1a5f5476be9c85/pkg/cmd/roachtest/main.go#L60)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: directory
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22593)*

**Pull request merged**
