### PR TITLE
server: optionally serve http traffic when forwarded from https

### LINKED ISSUE #228: server,ui: infinite HTTP redirect when accessing UI for secure cluster behind nginx-ingress in k8s
**Describe the problem**
I am getting  `too many redirects` when trying to access secure cockroachdb cluster behind ingress-nginx using [helm chart](https://hub.helm.sh/charts/stable/cockroachdb).

Please describe the issue you observed, and any steps we can take to reproduce it:

It is happening because tls.enabled == secure cluster with tls termination.
Same thing i got with [argo cd](https://github.com/argoproj/argo-cd/issues/2953#issuecomment-602898868) and solved using --insecure flag (Insecure - just about tls termination)
So i have to use insecure cluster behind ingress (losing auth screen, users with passwords etc) or secure cluster without ingress inside k8s (And i have to manage certificates, use not 80 and 443 ports, it's painful)

**To Reproduce**

1. Setup basic k8s cluster
2. Setup nginx-ingress, cert-manager
3. Setup secure cockroachdb cluster
4. Create k8s Ingress for cockroachdb service
5. Try to access admin panel

**Expected behavior**
I can disable tls termination in web ui, but don't lose security cluster benefits

**Additional data / screenshots**
- I am using helm charts:
  - https://hub.helm.sh/charts/stable/cockroachdb
  - https://hub.helm.sh/charts/stable/nginx-ingress
  - https://hub.helm.sh/charts/jetstack/cert-manager

**Environment:**
 - CockroachDB version 20.1
 - Server OS: Debian 10

Jira issue: CRDB-4219

### PR DESCRIPTION
**Pull request by dhartunian**
Note: Please ignore the first commit in this PR, I used it as a base since it has a test file already, it will be merged separately here: #77244

Could potentially resolve: https://github.com/cockroachdb/helm-charts/issues/228

----

This change allows CRDB to serve HTTP traffic with the
`server.accept_https_forwarded.enabled` cluster setting is enabled
*and* the request contains an `X-Forwarded-Proto` header with the value
`https`, or a `Forwarded` header containing the directive:
`proto=https`.

The aim is to enable easier use of the DB Console behind load balancers.

Release justification: opt-in feature that unblocks customers with load
balancers using DB Console

Release note (ops change, security update, ui change): When an operator
configures CRDB to serve HTTP traffic behind a load balancer, often they
would like to terminate TLS at the load balancer and have the load
balancer use HTTP to talk to the DB since that traffic will sit within
their private network instead of the public internet. Enabling the
`server.accept_http_forwarded.enabled` cluster setting will instruct
CRDB to inspect the `X-Forwarded-Proto` or `Forwarded` headers and allow
traffic over HTTP when the protocol is `https`.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
The first commit LGTM and a PR containing only this can be merged right away.

The 2nd commit deserves more attention and IMHO should be pulled into a separate PR. I think we need additional interlocks for it and that deserves a bit more discussion.

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77343#-:-MxGopR02JHw23-mdxHs:b-9l7r38)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @udnay)

___
*[pkg/server/server_http.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77343#-MxGoKvI4nQlA6qD1jip:-MxGoKvI4nQlA6qD1jiq:bmyh9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6e55503f8864190188ac25f6e973a946b5629d3/pkg/server/server_http.go#L81)):*
> ```Go
> // of 1 year that the browser should remember to only use HTTPS for
> // this site.
> const hstsHeaderValue = "max-age=31536000"
> ```

was there a particular reason to use exactly 1 year? is there any need to make this configurable?

**Review by dhartunian — COMMENTED** [review]
This PR is just for the second commit, I just worked on the two together.

What additional interlocks do you have in mind here? Should I circulate a short doc w/ security and server teams perhaps?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77343#-:-Mxg1CEj68ra0NnpbS97:b-kmvs7r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @udnay)

**Comment by knz** [comment]
The issue I currently have with the 2nd commit is that it's not so clear we want to compromise our security model for what is, arguably, an edge case. Note that once this feature is activated, an attacker with access to the HTTP port can bypass HTTPS by providing the new header. We should have a reflection on this and, at a minimum, a security release note that would explain to the operator how to best secure such a setup.

But even before then, I don't fully understand why that forwarded http traffic could not forward _also_ over https (while ignoring the server cert on the proxy-server side of the communication). What's so bad about having the back-end of a proxy using https too? If anything, I'd like a review of alternatives.

Also, this is a feature-add, not a bug fix, and thus IMHO does not befits stability period.

**Comment by dhartunian** [comment]
Thanks for the guidance @knz, upon further reflection I agree with your reasoning here. Perhaps what we really need is a working nginx example for folks to use.

I'll close this for now and see if it comes up as a problem again.

**Pull request closed without merging**
