### PR TITLE
changefeedccl: fix data race in tests

### LINKED ISSUE #132537: ccl/changefeedccl: TestTableNameCollision failed
ccl/changefeedccl.TestTableNameCollision [failed](https://tanzanite.cluster.engflow.com/invocations/default/472253a9-1ec8-4a59-9720-1020c5e3ae2c?testReportRun=1&testReportShard=5&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on release-24.2.4-rc @ [8140b8e294fb16a293d0aae662bcf5c1d488c852](https://github.com/cockroachdb/cockroach/commits/8140b8e294fb16a293d0aae662bcf5c1d488c852):

```
      github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_dist.go:328 +0x7bc
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup.GoAndWait.Group.GoCtx.func1()
      github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:168 +0x46
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:78 +0x91

Goroutine 72657 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:1133 +0xa4f
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:897 +0xe24
  github.com/cockroachdb/cockroach/pkg/server.(*SQLServerWrapper).serveConn()
      github.com/cockroachdb/cockroach/pkg/server/tenant.go:949 +0x42b
  github.com/cockroachdb/cockroach/pkg/server.(*SQLServerWrapper).serveConn-fm()
      <autogenerated>:1 +0xc4
  github.com/cockroachdb/cockroach/pkg/server.startServeSQL.func1.1()
      github.com/cockroachdb/cockroach/pkg/server/server_sql.go:1981 +0x3f5
  github.com/cockroachdb/cockroach/pkg/util/netutil.(*TCPServer).ServeWith.func1()
      github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:191 +0x1c6
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:485 +0x262

Goroutine 74374 (running) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75 +0x124
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx()
      github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:167 +0x184
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup.GoAndWait()
      github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:189 +0x18f
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.startDistChangefeed()
      github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_dist.go:332 +0x9e4
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.distChangefeedFlow()
      github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_dist.go:137 +0x544
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changefeedResumer).resumeWithRetries()
      github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_stmt.go:1281 +0x66a
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changefeedResumer).Resume()
      github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_stmt.go:1112 +0x3ec
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*reportErrorResumer).Resume()
      github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/testfeed_test.go:365 +0x65
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func2()
      github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1632 +0x172
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine()
      github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1633 +0x109e
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob()
      github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:451 +0x811
  github.com/cockroachdb/cockroach/pkg/jobs.(*StartableJob).Start.func2()
      github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:831 +0x27b
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:485 +0x262
==================
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=1</code>
 - <code>shard=5</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #131067 ccl/changefeedccl: TestTableNameCollision failed [A-cdc C-test-failure O-robot T-cdc X-duplicate branch-release-23.2.12-rc]
- #130465 ccl/changefeedccl: TestTableNameCollision failed [A-cdc C-test-failure O-robot T-cdc X-duplicate branch-release-23.2.11-rc]
- #129212 ccl/changefeedccl: TestTableNameCollision failed [A-cdc C-test-failure O-robot P-2 T-cdc branch-release-23.2.10-rc release-blocker]
- #128868 ccl/changefeedccl: TestTableNameCollision failed [A-cdc C-test-failure O-robot P-2 T-cdc branch-release-23.2 release-blocker]
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTableNameCollision.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-43126

### PR DESCRIPTION
**Pull request by asg0451**
Fix data race in unit tests caused by mutating testing knobs.

Fixes: #132537

Release note: none

### CODE REVIEW

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133112)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @asg0451)

___
*[`pkg/ccl/changefeedccl/sink_external_connection.go` line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133112#-O9ka0_p6yLMpxC2GYic:-O9ka0_p6yLMpxC2GYid:b-p8xw9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eb415ce86b4b99e8818664bed6434feb0310a39/pkg/ccl/changefeedccl/sink_external_connection.go#L70)):*
> ```Go
> 		wrapSink := knobs.WrapSink
> 		knobs.WrapSink = nil
> 		defer func() { knobs.WrapSink = wrapSink }()
> ```

It seems like the old code restores the previous value of `WrapSink`. Should the new code do that too?

**Review by asg0451 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133112)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andyyang890)

___
*[`pkg/ccl/changefeedccl/sink_external_connection.go` line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133112#-O9ka0_p6yLMpxC2GYic:-O9kdGCn8b6pNYMdKyYy:bwl64xk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eb415ce86b4b99e8818664bed6434feb0310a39/pkg/ccl/changefeedccl/sink_external_connection.go#L70)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

It seems like the old code restores the previous value of `WrapSink`. Should the new code do that too?
</blockquote></details>

my thought was no but it looks like yes but actually this fails ci for other reasons. let me have another go at it :upside_down_face:

**Review by andyyang890 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133112)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @asg0451)

**Comment by asg0451** [comment]
bors r=andyyang890

**Comment by asg0451** [comment]
blathers backport 23.2 24.1 24.2 24.3

**Pull request merged**
