### PR TITLE
cherrypick 2.0:  sql: implement session tracing for the connExecutor

### PR DESCRIPTION
**Pull request by andreimatei**
Cherry-pick #22990, pulling along #22988 and part of #22946

### CODE REVIEW

**Comment by jordanlewis** [comment]
Why didn't you include the heartbeat rename as well out of curiosity?

**Comment by andreimatei** [comment]
I can if you want. I just cherry-picked what I needed so that my commit applies cleanly. How do you do it to cherrypick all the commits from a PR - `git cherry-pick -m 2` or such?

**Comment by jordanlewis** [comment]
Gotcha - I actually don't know how to do that. Don't worry about it - I'll cherrypick it along with a few other tracing changes I have cooking.

**Comment by jordanlewis** [comment]
LGTM

**Pull request merged**
