### PR TITLE
opt: change rule for anti joins using inverted index

### PR DESCRIPTION
**Pull request by sumeerbhola**
These are now converted into paired joins consisting of
a left outer inverted join followed by an left anti
lookup join. This is more efficient than the previous
approach that involved two left outer joins and removal
of the matching rows using a select.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm:  nice clean change!

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55742#-:-MKF5H2N3B9G8NEvDUQQ:b-8kh9qw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/sql/opt/xform/rules/join.opt, line 149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55742#-MKF4qP7AJ8cNeIxVmv9:-MKF4qP7AJ8cNeIxVmvA:b5wdvgc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa845f37e8a21758ccc1f502499f2386f88dd60/pkg/sql/opt/xform/rules/join.opt#L149)):*
> ```
> # custom function for more details.
> # TODO(rytaft): Add support for SemiJoin. Currently it is supported by first
> # converting them to InnerJoin using the rule ConvertSemiToInnerJoin.
> ```

[nit] them -> it
___
*[pkg/sql/opt/xform/testdata/rules/join, line 4126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55742#-MKF5-v1EqOxR5OE-_I6:-MKF5-v1EqOxR5OE-_I7:bs55twv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa845f37e8a21758ccc1f502499f2386f88dd60/pkg/sql/opt/xform/testdata/rules/join#L4126)):*
> ```
> # Anti-join in which the right-hand side is a Scan.
> # In this test, all columns from the subquery (right hand side of the anti-join)
> # are pruned during normalization, so ConvertAntiToLeftJoin has to add back a
> ```

update this comment
___
*[pkg/sql/opt/xform/testdata/rules/join, line 4159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55742#-MKF58wr6QectozGwVlQ:-MKF58wr6QectozGwVlR:bs55twv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa845f37e8a21758ccc1f502499f2386f88dd60/pkg/sql/opt/xform/testdata/rules/join#L4159)):*
> ```
> # In this test, the nyc_neighborhoods.name column is needed for the predicate.
> # Since n.name LIKE 'Upper%' is a null-rejecting predicate, there is no need to
> # add another not-null column to the right-hand side (so EnsureNotNullCol is a
> ```

update this comment

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55742#-:-MKFcgZ40izBBk4XG1sF:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/xform/rules/join.opt, line 149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55742#-MKF4qP7AJ8cNeIxVmv9:-MKFbC0r8HHzD6MbVRLW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa845f37e8a21758ccc1f502499f2386f88dd60/pkg/sql/opt/xform/rules/join.opt#L149)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] them -> it
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/rules/join, line 4126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55742#-MKF5-v1EqOxR5OE-_I6:-MKFbUUw6DSYIHAR8j6Q:b8l5vu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa845f37e8a21758ccc1f502499f2386f88dd60/pkg/sql/opt/xform/testdata/rules/join#L4126)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

update this comment
</blockquote></details>

Deleted the sentence.
___
*[pkg/sql/opt/xform/testdata/rules/join, line 4159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55742#-MKF58wr6QectozGwVlQ:-MKFc4W3EskwRqOVVBtL:b75fofy) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa845f37e8a21758ccc1f502499f2386f88dd60/pkg/sql/opt/xform/testdata/rules/join#L4159)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

update this comment
</blockquote></details>

Deleted the sentence

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55742#-:-MKFf3IX2kvGDw9IOkgv:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
