### PR TITLE
acceptance: misc fixes

### PR DESCRIPTION
**Pull request by BramGruneir**
1 - change the allocator test's prefix to include seconds so more can be launched in quicker succession
2 - add a flag to keep the cluster around if the test fails - a good follow up to this will be instead copying the data off to storage somewhere and then dumping it.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7523)

### CODE REVIEW

**Comment by cuongdo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7523#-:-KLS8ZymOt7awCgPS0om:1417088721)*

**Comment by tamird** [comment]
in the second commit message s/fidelity/precision./
in the third commit message s/fail/failure./

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[acceptance/allocator_test.go, line 108 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7523#-KLS9BXI5BxeZqBp0XWU:-KLS9BXI5BxeZqBp0XWV:-1272632023) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad1ae518e7c848a74b3a05f2339a9883e7447ca6/acceptance/allocator_test.go#L108)):*
> ```Go
> 		}
> 		if t.Failed() && at.f.KeepClusterAfterFail {
> 			t.Logf("test has failed, not destroying")
> ```

s/Logf/Log/

does this want to log additional information?

---

*[acceptance/util_test.go, line 59 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7523#-KLS9MA__L0nEpEvngQd:-KLS9MA__L0nEpEvngQe:1474542978) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad1ae518e7c848a74b3a05f2339a9883e7447ca6/acceptance/util_test.go#L59)):*
> ```Go
> 	"run containers in privileged mode (required for nemesis tests")
> var flagTFKeepCluster = flag.Bool("tf.keep-cluster", false, "do not destroy Terraform cluster after test finishes, has precedence over flagTFKeepClusterFail")
> var flagTFKeepClusterFail = flag.Bool("tf.keep-cluster-on-fail", false, "do not destroy Terraform cluster after test finishes only if the cluster has failed")
> ```

the name doesn't include "On", but the flag does. pick one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7523#-:-KLS8qhoxeVktjZ4xjpV:934272210)*

**Comment by BramGruneir** [comment]
done

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[acceptance/allocator_test.go, line 108 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7523#-KLS9BXI5BxeZqBp0XWU:-KLSDHJ9doatiCpqrnse:1164914693) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad1ae518e7c848a74b3a05f2339a9883e7447ca6/acceptance/allocator_test.go#L108)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/Logf/Log/
> 
> does this want to log additional information?
</details>
done, and not really, it's all already in the test output

---

*[acceptance/util_test.go, line 59 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7523#-KLS9MA__L0nEpEvngQd:-KLSDNh20FPHCD8t8HpL:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad1ae518e7c848a74b3a05f2339a9883e7447ca6/acceptance/util_test.go#L59)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> the name doesn't include "On", but the flag does. pick one.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7523#-:-KLSDvXBO_APqfnX4Fj_:677588487)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[acceptance/util_test.go, line 59 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7523#-KLSFE5aZ9BBkGvypJ7f:-KLSFE5aZ9BBkGvypJ7g:-684479188) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef42a1bbe28aca99249beb0ecbdbe8dc29cafc41/acceptance/util_test.go#L59)):*
> ```Go
> 	"run containers in privileged mode (required for nemesis tests")
> var flagTFKeepCluster = flag.Bool("tf.keep-cluster", false, "do not destroy Terraform cluster after test finishes, has precedence over tf.keep-cluster-fail")
> var flagTFKeepClusterFail = flag.Bool("tf.keep-cluster-fail", false, "do not destroy Terraform cluster after test finishes only if the cluster has failed")
> ```

test has failed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7523#-:-KLSFHx-0eI8VGyJ3Mdq:1417088721)*

**Comment by BramGruneir** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[acceptance/util_test.go, line 59 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7523#-KLSFE5aZ9BBkGvypJ7f:-KLSFigtBPoAF4HG-bKR:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef42a1bbe28aca99249beb0ecbdbe8dc29cafc41/acceptance/util_test.go#L59)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> test has failed
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7523)*

**Pull request merged**
