### PR TITLE
gossip: infoStore.mostDistant should never return the local node-id

### LINKED ISSUE #28517: gossip: tight loop of loopback connections opened to tighten network graph
Seen in the logs for #28179. This is a 15 node cluster and for this node (srv-8) at startup Gossip decided to tighten the network graph. The node has 14 join flags, but unfortunately one of them is itself (so it's missing some other node instead). I don't think that matters, but I noticed it.

So Gossip decides that the own node is too far away (already absurd) and tries to connect to it directly (also absurd). This happens in a tight loop for ~4 minutes and appears to block startup of the node (perhaps by not letting it connect to more useful peers; not sure).

```
I180801 21:35:13.775866 39 gossip/client.go:129  [n27] started gossip client to 10.64.2.17:26257
I180801 21:35:13.845016 39 gossip/client.go:134  [n27] closing client to node 13 (10.64.2.17:26257): stopping outgoing client to node 13 (10.64.2.17:26257); already have incoming
I180801 21:35:13.845140 119 gossip/gossip.go:1257  [n27] starting client to distant node 27 (7 > 5) to tighten network graph
I180801 21:35:13.845194 119 gossip/gossip.go:1307  [n27] node has connected to cluster via gossip
I180801 21:35:13.846048 126 gossip/client.go:129  [n27] started gossip client to 10.64.4.25:26257
I180801 21:35:13.846493 126 gossip/client.go:134  [n27] closing client to node 27 (10.64.4.25:26257): stopping outgoing client to node 27 (10.64.4.25:26257); loopback connection
I180801 21:35:13.846669 119 gossip/gossip.go:1257  [n27] starting client to distant node 27 (7 > 5) to tighten network graph
I180801 21:35:13.846734 128 gossip/client.go:129  [n27] started gossip client to 10.64.4.25:26257
I180801 21:35:13.847268 128 gossip/client.go:134  [n27] closing client to node 27 (10.64.4.25:26257): stopping outgoing client to node 27 (10.64.4.25:26257); loopback connection
I180801 21:35:13.847447 119 gossip/gossip.go:1257  [n27] starting client to distant node 27 (7 > 5) to tighten network graph
I180801 21:35:13.847562 470 gossip/client.go:129  [n27] started gossip client to 10.64.4.25:26257
I180801 21:35:13.848084 470 gossip/client.go:134  [n27] closing client to node 27 (10.64.4.25:26257): stopping outgoing client to node 27 (10.64.4.25:26257); loopback connection
I180801 21:35:13.848271 119 gossip/gossip.go:1257  [n27] starting client to distant node 27 (7 > 5) to tighten network graph
I180801 21:35:13.848401 285 gossip/client.go:129  [n27] started gossip client to 10.64.4.25:26257
I180801 21:35:13.849032 285 gossip/client.go:134  [n27] closing client to node 27 (10.64.4.25:26257): stopping outgoing client to node 27 (10.64.4.25:26257); loopback connection
I180801 21:35:13.849142 119 gossip/gossip.go:1257  [n27] starting client to distant node 27 (7 > 5) to tighten network graph
I180801 21:35:13.849245 138 gossip/client.go:129  [n27] started gossip client to 10.64.4.25:26257
I180801 21:35:13.849827 138 gossip/client.go:134  [n27] closing client to node 27 (10.64.4.25:26257): stopping outgoing client to node 27 (10.64.4.25:26257); loopback connection
I180801 21:35:13.849917 119 gossip/gossip.go:1257  [n27] starting client to distant node 27 (7 > 5) to tighten network graph
I180801 21:35:13.849980 719 gossip/client.go:129  [n27] started gossip client to 10.64.4.25:26257
I180801 21:35:13.850370 719 gossip/client.go:134  [n27] closing client to node 27 (10.64.4.25:26257): stopping outgoing client to node 27 (10.64.4.25:26257); loopback connection
I180801 21:35:13.850596 119 gossip/gossip.go:1257  [n27] starting client to distant node 27 (7 > 5) to tighten network graph
I180801 21:35:13.850670 569 gossip/client.go:129  [n27] started gossip client to 10.64.4.25:26257
I180801 21:35:13.851254 569 gossip/client.go:134  [n27] closing client to node 27 (10.64.4.25:26257): stopping outgoing client to node 27 (10.64.4.25:26257); loopback connection
I180801 21:35:13.851530 119 gossip/gossip.go:1257  [n27] starting client to distant node 27 (7 > 5) to tighten network graph
I180801 21:35:13.851604 1000 gossip/client.go:129  [n27] started gossip client to 10.64.4.25:26257
I180801 21:35:13.851987 1000 gossip/client.go:134  [n27] closing client to node 27 (10.64.4.25:26257): stopping outgoing client to node 27 (10.64.4.25:26257); loopback connection
I180801 21:35:13.852255 119 gossip/gossip.go:1257  [n27] starting client to distant node 27 (7 > 5) to tighten network graph
I180801 21:35:13.852354 947 gossip/client.go:129  [n27] started gossip client to 10.64.4.25:26257
I180801 21:35:13.852797 947 gossip/client.go:134  [n27] closing client to node 27 (10.64.4.25:26257): stopping outgoing client to node 27 (10.64.4.25:26257); loopback connection
I180801 21:35:13.852997 119 gossip/gossip.go:1257  [n27] starting client to distant node 27 (7 > 5) to tighten network graph
I180801 21:35:13.853057 1123 gossip/client.go:129  [n27] started gossip client to 10.64.4.25:26257
I180801 21:35:13.853497 1123 gossip/client.go:134  [n27] closing client to node 27 (10.64.4.25:26257): stopping outgoing client to node 27 (10.64.4.25:26257); loopback connection
I180801 21:35:13.853644 119 gossip/gossip.go:1257  [n27] starting client to distant node 27 (7 > 5) to tighten network graph
I180801 21:35:13.853743 252 gossip/client.go:129  [n27] started gossip client to 10.64.4.25:26257
I180801 21:35:13.854004 252 gossip/client.go:134  [n27] closing client to node 27 (10.64.4.25:26257): stopping outgoing client to node 27 (10.64.4.25:26257); loopback connection
I180801 21:35:13.854188 119 gossip/gossip.go:1257  [n27] starting client to distant node 27 (7 > 5) to tighten network graph
I180801 21:35:13.854244 876 gossip/client.go:129  [n27] started gossip client to 10.64.4.25:26257
I180801 21:35:13.854606 876 gossip/client.go:134  [n27] closing client to node 27 (10.64.4.25:26257): stopping outgoing client to node 27 (10.64.4.25:26257); loopback connection
I180801 21:35:13.854870 119 gossip/gossip.go:1257  [n27] starting client to distant node 27 (7 > 5) to tighten network graph
I180801 21:35:13.854951 1492 gossip/client.go:129  [n27] started gossip client to 10.64.4.25:26257
I180801 21:35:13.855389 1492 gossip/client.go:134  [n27] closing client to node 27 (10.64.4.25:26257): stopping outgoing client to node 27 (10.64.4.25:26257); loopback connection
I180801 21:35:13.855604 119 gossip/gossip.go:1257  [n27] starting client to distant node 27 (7 > 5) to tighten network graph
I180801 21:35:13.855660 1618 gossip/client.go:129  [n27] started gossip client to 10.64.4.25:26257
I180801 21:35:13.856032 1618 gossip/client.go:134  [n27] closing client to node 27 (10.64.4.25:26257): stopping outgoing client to node 27 (10.64.4.25:26257); loopback connection
I180801 21:35:13.856203 119 gossip/gossip.go:1257  [n27] starting client to distant node 27 (7 > 5) to tighten network graph
I180801 21:35:13.856262 1615 gossip/client.go:129  [n27] started gossip client to 10.64.4.25:26257
```

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #28517

Release note: None

### CODE REVIEW

**Review by a-robinson — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29398#-:-LLBry0I6WXirANbYbIB:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/gossip/infostore_test.go, line 299 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29398#-LLBrsbw2oo5WfTJFK2-:-LLBrsbw2oo5WfTJFK20:b43qt4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f38850ce56e94025f739cba6d1ceed5504cdca5/pkg/gossip/infostore_test.go#L299)):*
> ```Go
> 		}
> 		if expectedHops != hops {
> 			t.Errorf("%d: expected node %d; got %d", i, expectedHops, hops)
> ```

If you feel like cleaning up, this error message is wrong. Not necessary though.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29398)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/gossip/infostore_test.go, line 299 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29398#-LLBrsbw2oo5WfTJFK2-:-LLC6KeiEXvXV3QtA4iA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f38850ce56e94025f739cba6d1ceed5504cdca5/pkg/gossip/infostore_test.go#L299)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

If you feel like cleaning up, this error message is wrong. Not necessary though.
</blockquote></details>

Done.

**Comment by petermattis** [comment]
bors r=a-robinson

**Review by bdarnell — COMMENTED** [review]
The second commit here (no loopback) worries me. If the previous incarnation of this node gossiped something that the new incarnation does not re-gossip, we'll have a situation where the rest of the cluster has some state in gossip that we don't (until it expires or we re-gossip it). I think I'd rather allow loopback gossip (encouraging convergence across the nodes) but special-case its harmful effects. (`mostDistant` and the timestamp assertion in #20986 are the only two that come to mind)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29398#-:-LM-Us9H2tsrPvjudBFA:b-hw45jd)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by petermattis — COMMENTED** [review]
@bdarnell Do you recall if it was intentional to allow loopback gossip info? I see your point that it allows divergence of the gossip state on the local node from the rest of the cluster, but I'm struggling to see where that is a problem. The node-id and store-id gossip info will be generated by the local node quickly. And the sentinel key and first-range descriptor will be gossiped by a new node in the cluster soon. I'm conflicted as to what to do here. We've seen several bugs due to allowing loopback gossip info. On the other hand, I see sanity in having each node have the same gossip state.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29398#-:-LM-dVjiDf-kXN8wDFWF:b-a0boj8)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by bdarnell** [comment]
I don't know whether it was considered or not. For the gossip keys you've mentioned, it's harmless to drop loopback gossip. Is that true for all keys (and will it always be true)? Gossip is used in pkg/sql/stats and pkg/sql/distsqlrun too, for example. I think that anything that would fail if we dropped loopback gossip would be flaky anyway, but allowing gossip to diverge between nodes would lead to very hard-to-debug failures. I think I'd rather err on the side of convergence.

**Pull request merged**
