### PR TITLE
kvstreamer: support lookup joins with ordering

### PR DESCRIPTION
**Pull request by yuzefovich**
**kvstreamer: introduce SingleRowLookup hint**

This commit introduces `SingleRowLookup` hint to the Streamer which
indicates that a single request can result in at most a single SQL row
lookup. This is obviously true and not very interesting for all
GetRequests, but it's quite helpful for the ScanRequests that can span
ranges IFF multiple rows might get scanned. The hint is `true` for index
joins and for lookup joins when lookup columns form a key.

When the hint is `true`, then the Streamer can avoid some extra
bookkeeping about how many sub-requests have already been responded to
for a particular original Scan request. In this commit, the
simplification is relatively minor, but the follow-up commit for
supporting InOrder mode for lookup joins will introduce much more
bookkeeping that this hint allows us to avoid.

Release note: None

**kvstreamer: fully support InOrder mode**

This commit extends the Streamer library to support Scan requests that
can span multiple ranges in the InOrder mode which allows us to use the
Streamer for the lookup joins when ordering needs to be maintained. As
with the lookup joins w/o ordering, this is a "poor man's" support which
relies on the de-duplication of requests in the join reader's span
generators as well as doesn't remove the disk-backed row container that
buffers all looked up rows in the join reader ordering strategy. Those
caveats will be addressed in the follow-up commits.

The contribution of this commit is such that the in-order results buffer
can now correctly return the results when a single original Scan request
touches multiple ranges as well as when each sub-request (against
a single range) can get an arbitrary number of partial responses.

Previously, we only had one axis for ordering the results - `Position`
values which identify the original request that a particular Result is
a response to. This was sufficient for index joins (as well as lookup
joins when `SingleRowLookup` hint is `true`); however, when a Scan
request can touch multiple ranges, that single axis is no longer
sufficient since the results buffer could order two Results for a single
Scan request arbitrarily. We go around this limitation by introducing
a second dimension for ordering - "sub-request index" which is the
ordinal of a particular single-range request within the multi-range Scan
request.

Consider the following example: original Scan request is `Scan(b, f)`,
and we have three ranges: `[a, c)`, `[c, e)`, `[e, g)`. In
`Streamer.Enqueue`, the original Scan is broken down into three
single-range Scan requests:
```
  singleRangeReq[0]:
    reqs          = [Scan(b, c)]
    positions     = [0]
    subRequestIdx = [0]
  singleRangeReq[1]:
    reqs          = [Scan(c, e)]
    positions     = [0]
    subRequestIdx = [1]
  singleRangeReq[2]:
    reqs          = [Scan(e, f)]
    positions     = [0]
    subRequestIdx = [2]
```
Note that `positions` values are the same (indicating that each
single-range request is a part of the same original multi-range request),
but values of `subRequestIdx` are different - they will allow us to order
the responses to these single-range requests (which might come back in
any order) correctly when returning the results. This information is
plumbed into the requests as well as the results.

There is yet another complication though - what if a single-range Scan
request results in multiple partial responses? To make sure that these
partial results are ordered correctly, we need yet another dimension,
but at least that dimension can be fully hidden inside of the in-order
results buffer. This is possible due to the fact that partial response
for the same single-range Scan request will be added into the buffer at
different times, so we'll assign the results "add epochs".

Consider the following example: we have the original Scan request as
`Scan(a, c)` which goes to a single range `[a, c)` containing keys `a`
and `b`. Imagine that the Scan response can only contain a single key,
so we first get a partial `ScanResponse('a')` with `ResumeSpan(b, c)`,
and then we get a partial `ScanResponse('b')` with an empty `ResumeSpan`.
The first response will be added to the buffer when during the first
`add` call, so its "epoch" is 0 whereas the second response is added
during "epoch" 1 - thus, we can correctly return `a` before `b`
although the `Position` and sub-request values of two `Result`s are the
same.

Addresses: #54680.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Only the last two commits belong to this PR.

**Review by rharding6373 — CHANGES_REQUESTED** [review]
Very cool to see the streamer capabilities expanding! This was a partial review, will continue reviewing later.

> Reviewed 3 of 3 files at r4, 1 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80749#-:-N0qYoGvCNc9QCvxNZLi:b-wwqyfv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373 and @yuzefovich)

___
*[`pkg/kv/kvclient/kvstreamer/requests_provider.go` line 45 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/80749#-N0qKdx87xkbYdzvdu3I:-N0qKdx87xkbYdzvdu3J:b-vccgc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/930469592a552f1ae8f3595b95e40da9bb9aa630/pkg/kv/kvclient/kvstreamer/requests_provider.go#L45)):*
> ```Go
> 	// range. If reqs[i] is a Get request, then subRequestIdx[i] is 0.
> 	//
> 	// Consider the following example: original Scan request is Scan(b, f), and
> ```

nit: request i?

Ultimately I think I'm confused as to what `i` refers to in the example, and the significance of 0, 1, and 2 (do they get assigned and overwrite the same position in `subRequestIdx`?)

Also, in the comment for `Result.subRequestIdx`, it says that only non-0 `subRequestIdx` are valid. It would be great if the examples/comments were consistent.
___
*[`pkg/kv/kvclient/kvstreamer/requests_provider.go` line 280 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/80749#-N0qN7xr7ACwf6GWi_mj:-N0qN7xr7ACwf6GWi_mk:b9qdc1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/930469592a552f1ae8f3595b95e40da9bb9aa630/pkg/kv/kvclient/kvstreamer/requests_provider.go#L280)):*
> ```Go
> 	priI, priJ := p.requests[i].priority, p.requests[j].priority
> 	var subI, subJ int
> 	if priI == priJ && p.requests[i].subRequestIdx != nil {
> ```

I think we should also check p.requests[j].subRequestIdx here so we avoid seg faults in production if something happens to go wrong.
___
*[`pkg/kv/kvclient/kvstreamer/requests_provider.go` line 285 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/80749#-N0qMqKL0KWaPw9x5hRz:-N0qMqKL0KWaPw9x5hS-:behdqvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/930469592a552f1ae8f3595b95e40da9bb9aa630/pkg/kv/kvclient/kvstreamer/requests_provider.go#L285)):*
> ```Go
> 		// spans multiple ranges. We want to make sure to order these parts
> 		// according to sub-request ordinals.
> 		subI = p.requests[i].subRequestIdx[0]
> ```

Why only sub request 0? What if the sub requests at 0 are equal, should we then compare subsequent sub requests?
___
*[`pkg/kv/kvclient/kvstreamer/requests_provider.go` line 292 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/80749#-N0qNh2VBBjfdUDJfnp0:-N0qNh2VBBjfdUDJfnp1:b-yfnda1) ([raw file](https://github.com/cockroachdb/cockroach/blob/930469592a552f1ae8f3595b95e40da9bb9aa630/pkg/kv/kvclient/kvstreamer/requests_provider.go#L292)):*
> ```Go
> 
> func (p *inOrderRequestsProvider) Swap(i, j int) {
> 	p.requests[i], p.requests[j] = p.requests[j], p.requests[i]
> ```

Don't we also need to swap subRequestIdx?
___
*[`pkg/kv/kvclient/kvstreamer/results_buffer.go` line 217 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/80749#-N0qQt8CAXkATm4KAUjA:-N0qQt8CAXkATm4KAUjB:bcit2hy) ([raw file](https://github.com/cockroachdb/cockroach/blob/930469592a552f1ae8f3595b95e40da9bb9aa630/pkg/kv/kvclient/kvstreamer/results_buffer.go#L217)):*
> ```Go
> 		}
> 		result += fmt.Sprintf("%d", r.Position)
> 		if printSubRequestIdx {
> ```

Could we just print out the subRequestIdx if non-0?
___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 1419 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/80749#-N0qH9FC7Jb6FWVz_14C:-N0qH9FC7Jb6FWVz_14D:b-ptz5rf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2c56baaeec7f172a48841ad92585c2649cdd768/pkg/kv/kvclient/kvstreamer/streamer.go#L1419)):*
> ```Go
> // finalizeSingleRangeResults "finalizes" the results of evaluation of a
> // singleRangeBatch. By "finalization" we mean setting Complete field of
> // ScanResp to correct value for all scan responses (when Hints.SingleRowLookup
> ```

major nit: s/Hints/hints

I think this makes a little more sense here than in the other places where Hints.SingleRowLookup is used in comments (namely struct field comments), but because of that this is bike shedding, so do what you like.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80749)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373)

___
*[`pkg/kv/kvclient/kvstreamer/requests_provider.go` line 45 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/80749#-N0qKdx87xkbYdzvdu3I:-N0qvEIW1fHK5B9lgKJa:b-au1atf) ([raw file](https://github.com/cockroachdb/cockroach/blob/930469592a552f1ae8f3595b95e40da9bb9aa630/pkg/kv/kvclient/kvstreamer/requests_provider.go#L45)):*
Reworded the example, please let me know if it makes sense.

> do they get assigned and overwrite the same position in `subRequestIdx`?

Three single-range scans will go into separate `singleRangeBatch` objects with each object having separate `subRequestIdx` slice, so they won't overwrite each other.

> Also, in the comment for `Result.subRequestIdx`, it says that only non-0 `subRequestIdx` are valid. It would be great if the examples/comments were consistent.

It says that `subRequestIdx` can be non-zero only in some circumstances implying that in all other circumstances it is left as zero. Added an explicit callout there.
___
*[`pkg/kv/kvclient/kvstreamer/requests_provider.go` line 280 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/80749#-N0qN7xr7ACwf6GWi_mj:-N0r-M-D-gzLaCcZJQ-Z:bxseoql) ([raw file](https://github.com/cockroachdb/cockroach/blob/930469592a552f1ae8f3595b95e40da9bb9aa630/pkg/kv/kvclient/kvstreamer/requests_provider.go#L280)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I think we should also check p.requests[j].subRequestIdx here so we avoid seg faults in production if something happens to go wrong.
</blockquote></details>

This has been refactored, and now we'll have a check.
___
*[`pkg/kv/kvclient/kvstreamer/requests_provider.go` line 285 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/80749#-N0qMqKL0KWaPw9x5hRz:-N0qzF1n31pjXtmTgt_F:b-qfyvor) ([raw file](https://github.com/cockroachdb/cockroach/blob/930469592a552f1ae8f3595b95e40da9bb9aa630/pkg/kv/kvclient/kvstreamer/requests_provider.go#L285)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Why only sub request 0? What if the sub requests at 0 are equal, should we then compare subsequent sub requests?
</blockquote></details>

The priority of the whole single-range batch is determined solely based on the priority of its first request. That first request's position is stored in `positions[0]`, and we currently also store it in `priority` field to make it more explicit, when priorities are the same, then we want to compare sub-priorities stored in `subRequestIdx[0]`. For the purposes of ordering `singleRangeBatch`es we only compare "head-of-the-line" requests within each single-range batch, so looking at `[0]` is sufficient. By construction of these single-range batches, the current head-of-the-line request within that batch is always the zeroth.

However, I agree that it is not that obvious, so I refactored the code to instead provide a couple of helper methods and removed `priority` field altogether. I think it should more clear now.
___
*[`pkg/kv/kvclient/kvstreamer/requests_provider.go` line 292 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/80749#-N0qNh2VBBjfdUDJfnp0:-N0r-Wr1DPzzw1SD7fOR:bbglzcn) ([raw file](https://github.com/cockroachdb/cockroach/blob/930469592a552f1ae8f3595b95e40da9bb9aa630/pkg/kv/kvclient/kvstreamer/requests_provider.go#L292)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Don't we also need to swap subRequestIdx?
</blockquote></details>

This is swapping the whole `singleRangeBatch` objects, so it does swap `subRequestIdx` slices too.
___
*[`pkg/kv/kvclient/kvstreamer/results_buffer.go` line 217 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/80749#-N0qQt8CAXkATm4KAUjA:-N0r-cH57W4dKzsbJybt:bnfswr5) ([raw file](https://github.com/cockroachdb/cockroach/blob/930469592a552f1ae8f3595b95e40da9bb9aa630/pkg/kv/kvclient/kvstreamer/results_buffer.go#L217)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Could we just print out the subRequestIdx if non-0?
</blockquote></details>

0 is a valid value - the first part of a large Scan request spanning multiple batches will have a sub-request index of 0. Also, allowing zeroes allows us to not have some conditionals in the in-order results buffer for cases when Get requests are used or SingleRowLookup hint is true, which makes the code overall cleaner I think.
___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 1419 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/80749#-N0qH9FC7Jb6FWVz_14C:-N0qtyX15lipK-5t3CB0:bk12ovk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2c56baaeec7f172a48841ad92585c2649cdd768/pkg/kv/kvclient/kvstreamer/streamer.go#L1419)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

major nit: s/Hints/hints

I think this makes a little more sense here than in the other places where Hints.SingleRowLookup is used in comments (namely struct field comments), but because of that this is bike shedding, so do what you like.
</blockquote></details>

This is a conscious choice on my part to use specifically `Hints.SingleRowLookup` because then GoLand highlights it, and it is possible to jump to the definition of this field straight from the comment which makes the code navigation, at least in GoLand, easier.

**Review by rharding6373 — APPROVED** [review]
:lgtm: Nice work!

> Reviewed 8 of 13 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80749#-:-N1FReAF0xVfMQ3-vILw:bcmw7ss)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rharding6373 and @yuzefovich)

___
*[`pkg/kv/kvclient/kvstreamer/requests_provider.go` line 45 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/80749#-N0qKdx87xkbYdzvdu3I:-N1F3ScQBWpzwfPfCQNK:brmeyjh) ([raw file](https://github.com/cockroachdb/cockroach/blob/930469592a552f1ae8f3595b95e40da9bb9aa630/pkg/kv/kvclient/kvstreamer/requests_provider.go#L45)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Reworded the example, please let me know if it makes sense.

> do they get assigned and overwrite the same position in `subRequestIdx`?

Three single-range scans will go into separate `singleRangeBatch` objects with each object having separate `subRequestIdx` slice, so they won't overwrite each other.

> Also, in the comment for `Result.subRequestIdx`, it says that only non-0 `subRequestIdx` are valid. It would be great if the examples/comments were consistent.

It says that `subRequestIdx` can be non-zero only in some circumstances implying that in all other circumstances it is left as zero. Added an explicit callout there.
</blockquote></details>

Thanks, this seems a bit more clear now.
___
*[`pkg/kv/kvclient/kvstreamer/requests_provider.go` line 54 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/80749#-N1FBNWJ48EUbrAi59gP:-N1FBNWJ48EUbrAi59gQ:b-itgs1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93e1a450bffa1d0d396b17e15a772771b472d57/pkg/kv/kvclient/kvstreamer/requests_provider.go#L54)):*
> ```Go
> 	// we have three ranges: [a, c), [c, e), [e, g). In Streamer.Enqueue, the
> 	// original Scan is broken down into three single-range Scan requests:
> 	// Scan(b, c), Scan(c, e), Scan(e, f), and each will get included into a
> ```

I think the example would be more clear if it showed more explicit assignments.
```
// Enqueue reqs[0] = Scan(b, f)
// reqs[0] = Scan(b, c),  pos[0] = 0, subRequestIdx[0] = 0
// reqs[1] = Scan(c, e),  pos[1] = 0, subRequestIdx[1] = 1
// reqs[2] = Scan(e, f),   pos[2] = 0, subRequestIdx[2] = 2
```
Or, perhaps this would be more readable in a table format:
```
// If Streamer.Enqueue reqs[0] is Scan(b,f), then the singleRangeBatch will be populated as:
// index  | reqs           |  pos| subRequestIdx
// ---------|----------------|-------|--------------------
// 0         | Scan(b, c)  | 0      | 0
// 1         | Scan(c, e)  | 0      | 1
// 2         | Scan(e, g)  | 0      | 2
```

And of course if I misinterpreted any of that, let me know :-)
___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 262 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/80749#-N1FRQnFDeJ9LmiARkjm:-N1FRQnFDeJ9LmiARkjn:b1spf1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93e1a450bffa1d0d396b17e15a772771b472d57/pkg/kv/kvclient/kvstreamer/streamer.go#L262)):*
> ```Go
> 		//
> 		// In InOrder mode, it tracks how many ranges a particular originally
> 		// enqueued ScanRequest touch. In other words, it contains how many
> ```

nit: s/touch/touches

**Comment by rytaft** [comment]
Added @michae2 as a reviewer so he can start getting familiar with this code

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r8, 11 of 11 files at r10, 13 of 13 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80749#-:-N1FpIcF8l1KfDP2074o:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @michae2, @rharding6373, and @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

I'm merging this to not let this PR get stale, but the Streamer is currently disabled for lookup joins (both with and without ordering). I'll be looking into stabilizing the streamer next.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80749#-:-N2mGFrtEudubxTUn5Yb:bjq2km3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @michae2, @rharding6373, and @rytaft)

___
*[`pkg/kv/kvclient/kvstreamer/requests_provider.go` line 54 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/80749#-N1FBNWJ48EUbrAi59gP:-N2mEleF929OWz-doSda:b4jwxuu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93e1a450bffa1d0d396b17e15a772771b472d57/pkg/kv/kvclient/kvstreamer/requests_provider.go#L54)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I think the example would be more clear if it showed more explicit assignments.
```
// Enqueue reqs[0] = Scan(b, f)
// reqs[0] = Scan(b, c),  pos[0] = 0, subRequestIdx[0] = 0
// reqs[1] = Scan(c, e),  pos[1] = 0, subRequestIdx[1] = 1
// reqs[2] = Scan(e, f),   pos[2] = 0, subRequestIdx[2] = 2
```
Or, perhaps this would be more readable in a table format:
```
// If Streamer.Enqueue reqs[0] is Scan(b,f), then the singleRangeBatch will be populated as:
// index  | reqs           |  pos| subRequestIdx
// ---------|----------------|-------|--------------------
// 0         | Scan(b, c)  | 0      | 0
// 1         | Scan(c, e)  | 0      | 1
// 2         | Scan(e, g)  | 0      | 2
```

And of course if I misinterpreted any of that, let me know :-)
</blockquote></details>

Good point, added an explicit assignment. I went with your first format with some fix-ups for correctness :)

**Pull request merged**
