### PR TITLE
storage/engine: add TestCheckpoint

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7296)

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/engine/rocksdb_test.go, line 232 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7296#-KKQ4bHuPcevcdlAy1Nh:-KKQ4bHuPcevcdlAy1Ni:-1801365266) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4739a6b5d3103dd479c33fb89e9a3d254a431ff/storage/engine/rocksdb_test.go#L232)):*
> ```Go
> 
> 	rocksdb := NewRocksDB(roachpb.Attributes{}, dir, 0, minMemtableBudget, 0, stopper)
> 	defer rocksdb.Close()
> ```

lol wat

---

*[storage/engine/rocksdb_test.go, line 262 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7296#-KKQ4lT7JmrgSfx51GIg:-KKQ4lT7JmrgSfx51GIh:-1201218129) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbdca9db96f000e6c2a0021790558d5bc1a81a55/storage/engine/rocksdb_test.go#L262)):*
> ```Go
> 
> 		// Add 20 keys, creating a checkpoint after the 10th key is added.
> 		for i := 0; i < 20; i++ {
> ```

nit: i feel like this'd be cleaner as two loops

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7296#-:-KKQ4qVBtyqfHwM7UZxb:1417088721)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/engine/rocksdb_test.go, line 232 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7296#-KKQ4bHuPcevcdlAy1Nh:-KKQ9OS9wGmquHv6Clkc:-1478540733) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4739a6b5d3103dd479c33fb89e9a3d254a431ff/storage/engine/rocksdb_test.go#L232)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> lol wat
</details>
The `stopper.Close` above causes the `RocksDB` to close. The close I'm deleting here was causing a double close and a log warning.

---

*[storage/engine/rocksdb_test.go, line 262 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7296#-KKQ4lT7JmrgSfx51GIg:-KKQ9YzIbs_s1UIS6T3g:-515258320) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbdca9db96f000e6c2a0021790558d5bc1a81a55/storage/engine/rocksdb_test.go#L262)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: i feel like this'd be cleaner as two loops
</details>
Heh, that's what I originally did and I switched to a single loop for clarity. I'm going to leave as-is for now. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7296)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/engine/rocksdb_test.go, line 232 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7296#-KKQ4bHuPcevcdlAy1Nh:-KKQAoNiwLNTMFdGoTzN:481232146) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4739a6b5d3103dd479c33fb89e9a3d254a431ff/storage/engine/rocksdb_test.go#L232)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> The `stopper.Close` above causes the `RocksDB` to close. The close I'm deleting here was causing a double close and a log warning.
</details>
Yeah, I was just commenting on the existence of this code in the first place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7296)*

**Pull request merged**
