### PR TITLE
distsql: Add INTERSECT ALL to MergeJoiner

### PR DESCRIPTION
**Pull request by abhimadan**
To leverage join planning and processor code for set operations in
distsql, a new join type is required. This commit adds an
INTERSECT_ALL_JOIN type, which will be used for INTERSECT ALL and
INTERSECT operations.

Part of #21661.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
That's a smaller change than I was imagining!

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/mergejoiner.go, line 209 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21681#-L3V1nbSMqsAQXdRJHXb:-L3V1nbSMqsAQXdRJHXc:b-yttw1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f7e3e0e5020e92683bb074b43056f4edf791287/pkg/sql/distsqlrun/mergejoiner.go#L209)):*
> ```Go
> 			// that min(len(m.leftRows), len(m.rightRows)) are emitted. Therefore, we
> 			// only consider rows where m.leftIdx <= m.rightIdx, and short-circuit the
> 			// inner loop when a match is found (see above).
> ```

I had to stare at this comment for far too long to understand it and the code. I visualize this code as advancing through the left and right rows in parallel whenever a match is found. I'm having a bit of trouble thinking through what the code will do if there is a join condition that isn't on the entire row. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21681#-:-L3VXZdONiXn5rW535FN:bqsija6)*

**Comment by RaduBerinde** [comment]
CC @arjunravinarayan - could you review this? (I'll be OOO in the coming days)

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/mergejoiner.go, line 209 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21681#-L3V1nbSMqsAQXdRJHXb:-L3VjTaGoj1fAGmbnXir:b-gasqey) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f7e3e0e5020e92683bb074b43056f4edf791287/pkg/sql/distsqlrun/mergejoiner.go#L209)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I had to stare at this comment for far too long to understand it and the code. I visualize this code as advancing through the left and right rows in parallel whenever a match is found. I'm having a bit of trouble thinking through what the code will do if there is a join condition that isn't on the entire row. 
</blockquote></details>

If we assume that there is no "on" condition for this type of join, this should be documented in the proto and it should be checked when the processor is created.

---

*[pkg/sql/distsqlrun/processors.proto, line 243 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21681#-L3Vj8y1fund75al0gx-:-L3Vj8y1fund75al0gx0:b-qhx87b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b92c60ffb0e954962675bde1ed5949fc59511224/pkg/sql/distsqlrun/processors.proto#L243)):*
> ```protobuf
>   LEFT_SEMI = 4;
>   LEFT_ANTI = 5;
>   INTERSECT_ALL = 6;
> ```

this could use a comment explaining what it is and why it is different than 

---

*[pkg/sql/distsqlrun/processors.proto, line 243 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21681#-L3VjCbxlACc5SHsL3JK:-L3VjCbxlACc5SHsL3JL:b-5t5jtw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b92c60ffb0e954962675bde1ed5949fc59511224/pkg/sql/distsqlrun/processors.proto#L243)):*
> ```protobuf
>   LEFT_SEMI = 4;
>   LEFT_ANTI = 5;
>   INTERSECT_ALL = 6;
> ```

this could use a comment explaining the semantics (and any implications for the specs)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21681#-:-L3Vk0pi1CqHUZfPc_8P:b-g9ilv2)*

**Comment by arjunravinarayan** [comment]
This generally looks good to me and very elegantly done, however, the comments are difficult to understand. It would be better if they were simpler, more imperative comments.

---

Reviewed 1 of 6 files at r1, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/mergejoiner.go, line 209 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21681#-L3V1nbSMqsAQXdRJHXb:-L3YgcU6EEyXxEJdwl03:bsaww7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f7e3e0e5020e92683bb074b43056f4edf791287/pkg/sql/distsqlrun/mergejoiner.go#L209)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

If we assume that there is no "on" condition for this type of join, this should be documented in the proto and it should be checked when the processor is created.
</blockquote></details>

This comment needs rewriting. Try and write imperative sentences, rather than "should X", that might make it cleaner.

---

*[pkg/sql/distsqlrun/processors.proto, line 243 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21681#-L3Vj8y1fund75al0gx-:-L3YjFQWAjJ6fe105B2R:b-lp0yi7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b92c60ffb0e954962675bde1ed5949fc59511224/pkg/sql/distsqlrun/processors.proto#L243)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

this could use a comment explaining what it is and why it is different than 
</blockquote></details>

This looks done to me. @abhimadan did you push updates to address the comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21681#-:-L3YhukmRWT3kCC0YfdA:bqh8zye)*

**Comment by abhimadan** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/processors.proto, line 243 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21681#-L3Vj8y1fund75al0gx-:-L3Yjdtbibq9FsPunQOp:b3fw8cz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b92c60ffb0e954962675bde1ed5949fc59511224/pkg/sql/distsqlrun/processors.proto#L243)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

This looks done to me. @abhimadan did you push updates to address the comment?
</blockquote></details>

Yeah I addressed this comment but forgot to reply. Sorry about that.

---

*[pkg/sql/distsqlrun/processors.proto, line 243 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21681#-L3VjCbxlACc5SHsL3JK:-L3YjoOCtTjy2NoKZ2Q4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b92c60ffb0e954962675bde1ed5949fc59511224/pkg/sql/distsqlrun/processors.proto#L243)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

this could use a comment explaining the semantics (and any implications for the specs)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21681)*

**Comment by abhimadan** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsqlrun/mergejoiner.go, line 209 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21681#-L3V1nbSMqsAQXdRJHXb:-L3YojQfbWAuwJsZHqiw:b-erq5rv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f7e3e0e5020e92683bb074b43056f4edf791287/pkg/sql/distsqlrun/mergejoiner.go#L209)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

This comment needs rewriting. Try and write imperative sentences, rather than "should X", that might make it cleaner.
</blockquote></details>

I've updated the comment -- hopefully it's better now.

@petermattis: if the join condition isn't on the entire row, then each left row will be matched with only one right row. This depends on the order of the batched right-side rows, so there's no guarantee on what left-side and right-side rows will be joined together. Since those results are arbitrary, I added a check to make sure that every column on the left and right side is an equality column (though this has resulted in some test failures, which I'm investigating).

@RaduBerinde: Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21681)*

**Comment by abhimadan** [comment]
Tests are failing because the mergeJoiner constructor passes `nil` to the joinerBase constructor for the equality columns, and the INTERSECT ALL-specific checks rely on those being non-nil. I sent out #21707 to address it, so that needs to be merged before this PR.

---

Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21681#-:-L3Z6TgtNJHxuXtv-NxB:byk1n11)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21681#-:-L3Z8lu5TynyuRkB5YhP:bnfp4nl)*

**Pull request merged**
