### PR TITLE
release-21.2: group statement statistics based on its transaction fingerprintID

### PR DESCRIPTION
**Pull request by Azhng**
Backport:
  * 1/1 commits from "roachpb,sql.ui: remove Opt field from StatementStatisticsKey" (#69597)
  * 1/1 commits from "sql: restructure sqlstats public writer API" (#69710)
  * 3/3 commits from "sql: group statement statistics based on its transaction fingerprintID" (#70261)
  * 1/1 commits from "sql: consistent aggregated timestamp when flushing sql stats" (#71731)
  * 3/3 commits from "sql/server/ui: add end interval time to statements and transaction pages" (#71538)
  * 1/1 commits from "server,ui: transactionDetail page now shows statement stats scoped by transaction fingerprint ID" (#71967)
  * 1/1 commits from " sql: clear (rather than emptying) bound account" (#71280)
  * 1/1 commits from " sql: remove diagnostics.sql_stat_reset.interval" (#71597)

Please see individual PRs for details.

/cc @cockroachdb/release

Release justification: Category 4: Low risk, high benefit changes to existing functionality

### CODE REVIEW

**Comment by stevendanna** [comment]
@Azhng mind throwing this https://github.com/cockroachdb/cockroach/pull/71280 into the backport as well?

**Comment by maryliag** [comment]
Don't forget to add a Release Justification :)

**Comment by Azhng** [comment]
Added #71280 to the backport, and added release justification in the PR description.

**Comment by maryliag** [comment]
Can you also update your PR description to include the 2 new commits you just added?

**Comment by Azhng** [comment]
PR Description updated!

**Review by maryliag — APPROVED** [review]

**Pull request merged**
