### PR TITLE
roachtest: miscellaneous improvements

### PR DESCRIPTION
**Pull request by petermattis**

### CODE REVIEW

**Review by benesch — APPROVED** [review]

**Comment by petermattis** [comment]
bors r=benesch

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30372)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/test.go, line 803 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30372#-LNpvYKaA8uKB0_RKmcA:-LNpvYKaA8uKB0_RKmcB:b9wnaet) ([raw file](https://github.com/cockroachdb/cockroach/blob/00517375ed3de8569d6c2f877848c22886b37d8a/pkg/cmd/roachtest/test.go#L803)):*
> ```Go
> 							// forward running another test or subtest, just exit
> 							// immediately.
> 							os.Exit(1)
> ```

what if we're running multiple tests, or a single test with `--count` - don't we want those clusters to be properly destroyed?
Isn't this too brutal?

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30372)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/test.go, line 803 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30372#-LNpvYKaA8uKB0_RKmcA:-LNpyZs348mukbp2groJ:bxcvbtg) ([raw file](https://github.com/cockroachdb/cockroach/blob/00517375ed3de8569d6c2f877848c22886b37d8a/pkg/cmd/roachtest/test.go#L803)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what if we're running multiple tests, or a single test with `--count` - don't we want those clusters to be properly destroyed?
Isn't this too brutal?
</blockquote></details>

The `--debug` flag intentionally does not destroy the cluster so that it can be debugged. Perhaps I'm misunderstanding your concern here.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30372)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/test.go, line 803 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30372#-LNpvYKaA8uKB0_RKmcA:-LNq-GWJDxarmY6hwdxo:b2bn07m) ([raw file](https://github.com/cockroachdb/cockroach/blob/00517375ed3de8569d6c2f877848c22886b37d8a/pkg/cmd/roachtest/test.go#L803)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The `--debug` flag intentionally does not destroy the cluster so that it can be debugged. Perhaps I'm misunderstanding your concern here.
</blockquote></details>

But I'm saying what if there's many many clusters around cause `--parallelism` (which is also the default). All but one (or rather, all except the failures) should be cleaned up.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30372)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/test.go, line 803 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30372#-LNpvYKaA8uKB0_RKmcA:-LNq35E2-3w4gDs3KZux:b4aazmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/00517375ed3de8569d6c2f877848c22886b37d8a/pkg/cmd/roachtest/test.go#L803)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

But I'm saying what if there's many many clusters around cause `--parallelism` (which is also the default). All but one (or rather, all except the failures) should be cleaned up.
</blockquote></details>

Ah, that's a good point. I've never used `--debug` when running multiple tests. I suppose that is sensical. Do you care to fix this? If not, file an issue for me.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30372)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/test.go, line 803 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30372#-LNpvYKaA8uKB0_RKmcA:-LNq3yX50k0CZ42harnM:bwdr00v) ([raw file](https://github.com/cockroachdb/cockroach/blob/00517375ed3de8569d6c2f877848c22886b37d8a/pkg/cmd/roachtest/test.go#L803)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ah, that's a good point. I've never used `--debug` when running multiple tests. I suppose that is sensical. Do you care to fix this? If not, file an issue for me.
</blockquote></details>

I think it should be common with `--count` when you're trying to repro something.
I might do various things for getting a roachtest stress workflow in better shape for the jepsen issue (including #30146), so I might do something.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30372)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/test.go, line 803 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30372#-LNpvYKaA8uKB0_RKmcA:-LNq55df2gv36clebmim:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/00517375ed3de8569d6c2f877848c22886b37d8a/pkg/cmd/roachtest/test.go#L803)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think it should be common with `--count` when you're trying to repro something.
I might do various things for getting a roachtest stress workflow in better shape for the jepsen issue (including #30146), so I might do something.
</blockquote></details>

:thumbsup:

**Pull request merged**
