### PR TITLE
Hide on conflict where clause

### PR DESCRIPTION
**Pull request by jseldess**
Previously, we included the WHERE clause in generated SQL
diagrams for ON CONFLICT, despite WHERE being [unimplemented](https://github.com/cockroachdb/cockroach/issues/32557)
for that case. This patch removes the clause from relevant diagrams.

Initial response to https://github.com/cockroachdb/docs/issues/6659.

Release note: None

### CODE REVIEW

**Comment by jseldess** [comment]
@knz, in this PR, you'll see that I've taken the approach of manually hiding the where clause in the generated on conflict bnf. I'd like your help understanding if, instead, we could use `/* SKIP DOC */` directly in `sql.y` to tell cockroach to not include this (and other) unimplemented syntax in all relevant bnfs. All the current examples of skip doc seem to skip an entire case, and so it's not obvious how to use skip doc in this particular case: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/parser/sql.y#L5901.

Ultimately, it'd be best to do this directly in the grammar for *all* unimplemented features. If that's not possible, we'll have to manually identify all generated bnfs that contain unimplemented syntax and manually adjust `diagrams.go` for each of them. For the current case, for example, in principle, I should also adjust the full sql grammar bnf to hide the on conflict where clause.

**Comment by knz** [comment]
> Ultimately, it'd be best to do this directly in the grammar for all unimplemented features. 

I think that's possible, based on how Matt implemented "SKIP DOC".

**Review by knz — APPROVED** [review]
LGTM for this particular change.

You could file an issue to extend the docgen program to recognize "unimplemented' alongside "SKIP DOC" as a marker to ignore rules.

**Comment by jseldess** [comment]
TFTR, @knz. Also opened https://github.com/cockroachdb/cockroach/issues/45464.

**Pull request merged**
