### PR TITLE
sql: collect transaction execution statistics

### LINKED ISSUE #59652: sql: add execution stats to txnStats
Execution stats are recorded at the statement level in `instrumentationHelper`, but we need to find a way to aggregate these stats across multiples statements in a transaction and store them in `txnStats` to be sent up to the DB Console. One idea is to add them to `extraTxnState` and recorded when a txn is finished. Some more investigation probably needs to go into this.

### PR DESCRIPTION
**Pull request by asubiotto**
See individual commits for details. These are the big changes:
- The intstrumentation helper no longer decides to sample a statement. This is instead done at the transaction level. As a result, the cluster setting name has been changed.
- The conn executor accumulates statement statistics in `extraTxnState` and records these when recording the usual transaction stats.
- The TransactionStatistics protobuf has been updated with execution statistics fields to be used in the DB Console (although this PR doesn't touch the UI, this will be done in the future).

Release note: None

Closes #59652

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59761#-:-MSdUnoH3DHV2D1QdsQu:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/roachpb/app_stats.proto, line 142 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59761#-MSdUkiI9Cr0_07IcWIS:-MSdUkiI9Cr0_07IcWIT:bxumwrb) ([raw file](https://github.com/cockroachdb/cockroach/blob/82ac89209a36ecf38b9e6b348729949840bce1c2/pkg/roachpb/app_stats.proto#L142)):*
> ```protobuf
> 
>   // RowsRead collects the number of rows read from disk.
>   optional NumericStat rows_read = 8 [(gogoproto.nullable) = false];
> ```

How come these aren't in ExecStats?

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, 3 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59761#-:-MSeRd0lBFjPlOlgeRBK:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/roachpb/app_stats.proto, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59761#-MSckbr85zjhyqIACfUp:-MSckbr85zjhyqIACfUq:bw591io) ([raw file](https://github.com/cockroachdb/cockroach/blob/82ac89209a36ecf38b9e6b348729949840bce1c2/pkg/roachpb/app_stats.proto#L145)):*
> ```protobuf
> 
>   // ExecStats are the execution statistics for this transaction, i.e. an
>   // aggregation of all its statement's execution statistics. These statistics
> ```

super nit: I think `s/statement's/statements'/`.

**Review by asubiotto — COMMENTED** [review]
TFTRs, also added a test.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59761#-:-MSgoVz85mzV0VvScTN-:b-75b1e2)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @RaduBerinde and @yuzefovich)

___
*[pkg/roachpb/app_stats.proto, line 142 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59761#-MSdUkiI9Cr0_07IcWIS:-MSgo7uZ25Y-KP6QP5Kx:b65zpge) ([raw file](https://github.com/cockroachdb/cockroach/blob/82ac89209a36ecf38b9e6b348729949840bce1c2/pkg/roachpb/app_stats.proto#L142)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

How come these aren't in ExecStats?
</blockquote></details>

Because these stats are not sampled (they use a different mechanism due to historical reasons). I'm hoping that we won't see this divide in the future if we remove the sampling and always collect stats, but for the time being I think it's a better user experience to keep these as they are for this info to be displayed even when not sampling.
___
*[pkg/roachpb/app_stats.proto, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59761#-MSckbr85zjhyqIACfUp:-MSgoAJQ-r90OkSnDjaK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/82ac89209a36ecf38b9e6b348729949840bce1c2/pkg/roachpb/app_stats.proto#L145)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

super nit: I think `s/statement's/statements'/`.
</blockquote></details>

Done.

**Comment by asubiotto** [comment]
bors r=yuzefovich,RaduBerinde

**Comment by asubiotto** [comment]
These look like flakes

bors r=yuzefovich,RaduBerinde

**Pull request merged**
