### PR TITLE
distsql: fix memory accounting in StreamGroupAccumulator

### LINKED ISSUE #30050: sql: SQL20 query fails due to memory budget exceeded error
REPRO:

1. Start Cockroach DB on a GCE machine `(24 vCPUs, 32 GB memory)`, using default options.
2. Load TPCH data using the instructions in `2.1-sql-20`
3. Run the following query in the SQL console:
```
SELECT count(*) FROM lineitem JOIN supplier ON l_suppkey = s_suppkey
```

EXPECTED: This gets planned by the cost-based optimizer using a merge join, and should not exceed the memory budget, since both sides should be streamed.

ACTUAL: The query fails with an error:
```
Error: pq: root: memory budget exceeded: 10240 bytes requested, 134215680 currently allocated, 134217728 bytes in budget
```

Note that the heuristic planner chooses a hash join for this query, and that does *not* run out of memory.

### PR DESCRIPTION
**Pull request by rjnn**
StreamGroupAccumulator was never clearing its memory accounting when
clearing its group, so its used memory appears to always grow until it
is OOM-killed by the execution engine.

Closes #30050. Empirically verified to fix the issue reported therein.

Release note (bug fix): fix a bug where certain queries, like merge
joins, would fail due to appearing to run out of memory due to
incorrect memory accounting.

### CODE REVIEW

**Review by asubiotto — APPROVED** [review]

**Comment by arjunravinarayan** [comment]
bors r=asubiotto

**Comment by RaduBerinde** [comment]
LGTM. Thanks for the quick fix! Happy this was found and fixed before the release.

**Review by jordanlewis — APPROVED** [review]
:lgtm: - it's worth noting here that this isn't precise - the account Clear happens as we hand the group back up to the higher level merger, not after the memory is actually finished being used. To be more precise, we'd have to Clear the account outside of this accumulator once we actually send all of its rows back.

But there's tons of places in the code where we're not precise with memory accounts, so I'm not particularly concerned. Just something to note.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30085#-:-LM945FV6UOfRL64R4Wy:bcc4588)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by petermattis** [comment]
Doesn't this bug deserve the addition of a test to prevent regression?

**Comment by arjunravinarayan** [comment]
err I switched discussion prematurely to the cherrypicked branch, my apologies to all. @asubiotto PTAL for a change to an `EXPLAIN ANALYZE` logic test.

**Review by asubiotto — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30085#-:-LMDzUBsEr8KWllq-Fjy:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/logictest/testdata/logic_test/explain_analyze_plans, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30085#-LMDV7_VA3B2eBDPH3DW:-LMDV7_W9f1UGqG0dy7E:b-l2qqjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/44a8f0a05fbef3c217d01ac43606a8bf5997b660/pkg/sql/logictest/testdata/logic_test/explain_analyze_plans#L43)):*
> ```
> SELECT url FROM [EXPLAIN ANALYZE (DISTSQL) SELECT kv.k, avg(kw.k) FROM kv JOIN kw ON kv.k=kw.k GROUP BY kv.k]
> ----
>   https://cockroachdb.github.io/distsqlplan/decode.html#eJzcWNFu2zYUfd9XCPepQzlYpGTHETDA3Z6yNfaQJg_DYARKxDlCbcug5LVBkX8fJHmLLSW8okyTbN5kWdQ9PLw8OjzfYJ0lfBqveA7RX0CBAAMCARAIgcAQ5gQ2IrvneZ6J8pF6wEXyFSKfQLrebIvy9pzAfSY4RN-gSIslhwiu47slv-JxwsXABwIJL-J0WZXZiHQVi8fJ53-AgMi-5J7gcRJ5Zfm8iJdLr0hXPPL8HAjMtkXkTSjMnwhk22JX8LnO3aP3EOcPhxWq5-fV2xYcIvpE-gEfvQL8iyHg7FXgz-_JRMIFT5rveV8W7vTUCxxccrHgv2XpmosBbazekv9dvJvQ9z_-LNLFQ30JpLrtNTip7rWIqYY1H61vtp5dxV-9FV9l4tHb5jyJPOZ7v6e_PNNLJqzB8DN7gcqyf1gsBF_ERSYGdNhaFAKzmsBqSQl8mP55O51d305vPn58N6ElAZ9uLt9NWHn16-xmer27xrqkNUFaT_CYrgmP6xo5Ocw_jpxPN5e3FyU9wTH0ELji64SLqgW8CRtMglfbYNiBju36JUJe5GKa_ZRtBmzYePLl2qOD2rS78lCnJFMB-JlTkkntSCbtJZl-d8n0FSTT93rpJbLm-3o5Oole-p0EoZydPrFU7hdELOmJxLI7N_2VknXf9MwptVIAPnZKrZgdtWJvQK2QNd9Xq7M3o1bK_YKoFfuO1SrovukDp9RKAfi5U2oV2FGroJdahd3VKlRQK9r7OIos-75gjU8iWKGd46hy1yCaFZxIs5To6S9bYffdHzolWwrAh07JVmhHtsI3YLKQNd_XrPM3Y7KU-wURrPA7NllIhnrF8022znmnaMwvieLJgtfE5tlW3PM_RHZflal_zqpx1bE84XlR_8vqHxfr__7Ki7h6946NbFvwHR_t6e9uJmn--f9b1RbvXn-suz6Bu8eC517O10UPPDRwDVBHhqgpQMw8Q1ShhdkJWlhef6y7_pF8NFrYAUAdGdLYwkjHmGeINQH5-4AO8fjNwYF0NqFugWiBl9envnFBQAANHQPEXGOImWcolG6ABp7m4KF0MBsdbp8TfAFGZk0UyqYcj3ZTpVjfgolCAJk3UUjHmGfozKyJOhKPdlOlWN-CiUIAmTdRSMeYZ2gs_Qycy03UuQ4TpXEycjz6TZUqAPMWQQ7IgolCAJlniLaO5jIXtQcIe6_KCdvIRFWO3A4A0u94lBGYtzhY11gIilrHbMsmBwFkITqSA9Jve5QRWAiLkK6xkKe1ju8HOk9DudWhrcO2Za-DALKQIGGItH_bVRFYsDsYIgt-Rx789Pc7ruU5CCALfse5hAdDpN3_KHeNBU5cC3UQQBb8jnMxD4ZIu_9R7hoLnMiTHYpEO9S1bAcBZMPvOJf2IIi6-p_wiH3gXL7DTpTvMC35jsYjFwLIvN9BAFnwOxgi5zjS73_aCLTkOzr72LV8BwFkwe9giJzjSL__aSOQ5zsMyXeYa_kOAsiC38EQWfi2O5f3YIhOn4ExXfnO_OmHfwMAAP__XVthYQ==
> ```

Talked offline. It's weird that mergeJoiner/10 still uses 20KiB but that shouldn't hold up this merge

**Comment by arjunravinarayan** [comment]
bors r=raduberinde,asubiotto,jordanlewis

**Review by andreimatei — COMMENTED** [review]
It seems to me that there is some memory that the accumulator never releases (not even when it's `close()`d) - and that's the memory of `s.curGroup`. `s.curGroup`'s capacity only grows - it is assigned and resliced to `s.curGroup[:0]` which doesn't modify the capacity. So, the memory used by that slice stays proportional to the size of the largest group ever seen. Assigning `s.curGroup = s.curGroup[:0:0]` would release memory (I think) , but then we'd reallocate the next time we append.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30085#-:-LNlSBak8EBqO7e8xjJ4:b-q6xjqh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
