### PR TITLE
sql: add last error code to statements statistics tables

### PR DESCRIPTION
**Pull request by gtr**
Part of: #94381.

This commit adds the `last_error_code` column to the
`crdb_internal.node_statements_statistics` table, which keeps track of
the error code for failed statement executions.

Tests in `pkg/sql/logictest/testdata/logic_test/statement_statistics_errors`.

Querying from systems table:
```sql
SELECT * FROM (
    SELECT
        encode(fingerprint_id, 'hex') AS fingerprint_id,
        metadata ->> 'querySummary' as querySummary,
        statistics -> 'statistics' ->> 'lastError' as lastError,
        statistics -> 'statistics' ->> 'errorCode' as errorCode,
        statistics -> 'statistics' ->> 'lastExecAt' as lastExecAt
    FROM system.statement_statistics
    ORDER BY statistics -> 'statistics' ->> 'lastExecAt'
) WHERE querySummary = 'SELECT _ / _';
```
Result:
```
  fingerprint_id  | querysummary |    lasterror     | errorcode |         lastexecat
------------------+--------------+------------------+-----------+------------------------------
 e030b633313c1280 | SELECT _ / _ | division by zero | 22012     | 2023-02-06T00:23:27.807099Z
```

Querying from cluster table:
```sql
SELECT * FROM (
    SELECT
        encode(fingerprint_id, 'hex') AS fingerprint_id,
        metadata ->> 'querySummary' as querySummary,
        statistics -> 'statistics' ->> 'lastError' as lastError,
        statistics -> 'statistics' ->> 'errorCode' as errorCode,
        statistics -> 'statistics' ->> 'lastExecAt' as lastExecAt
    FROM crdb_internal.statement_statistics
    ORDER BY statistics -> 'statistics' ->> 'lastExecAt'
) WHERE lastError != 'NULL' AND lastError != '';
```
Result:
```
  fingerprint_id  | querysummary |    lasterror     | errorcode |         lastexecat
------------------+--------------+------------------+-----------+------------------------------
 e030b633313c1280 | SELECT _ / _ | division by zero | 22012     | 2023-02-06T00:23:27.807099Z
```

Release note (sql change): Adds `last_error_code` column to the
`crdb_internal.node_statements_statistics` table. Adds `last_error_code`
field to the `statistics` JSON blob in the
`crdb_internal.statement_statistics` and `system.statement_statistics`
tables.

### CODE REVIEW

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96436)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96436#-NNIZHdHDNckb6tmbN6p):*
Would it be better to make it a metric by error code? That way user could see what percentage of queries are failing with that error, and can better understand the impact.

**Comment by gtr** [comment]
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96436)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr)
> 
> _[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96436#-NNIZHdHDNckb6tmbN6p):_ Would it be better to make it a metric by error code? That way user could see what percentage of queries are failing with that error, and can better understand the impact.

This could be a good metric, but could this information perhaps be gathered via a SQL query using already-existing column data? For example taking the percentage of a failure code / the number of total failures. What do you think @kevin-v-ngo ?

**Comment by kevin-v-ngo** [comment]
> 

Great feedback - https://github.com/cockroachdb/cockroach/issues/96690

**Review by maryliag — CHANGES_REQUESTED** [review]
Just a nit on the name. Otherwise :lgtm: 

> Reviewed 6 of 23 files at r1, 19 of 20 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96436#-:-NNg1pel3i8FRzEJG7DX:b32llyo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @gtr and @j82w)

___
*[`-- commits` line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96436#-NNg0Wxu12FGju2CtiCA):*
make sure you update the commit message with the same changes you added on the PR description.
___
*[`pkg/sql/appstatspb/app_stats.proto` line 124 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96436#-NNg1CeSC7rWWOWrzpHP:-NNg1CeSC7rWWOWrzpHQ:bolfoz5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9809df48197591ffb67bd1a1a560af34dd9b027b/pkg/sql/appstatspb/app_stats.proto#L124)):*
> ```protobuf
> 
>   // error_code is the error code for a failed statement, if it exists.
>   optional string error_code = 31 [(gogoproto.nullable) = false];
> ```

nit: use last_error_code to make it clear and consistent with last_error_message
___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding.go` line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96436#-NNg1OpdAVuXUEHr3Py4:-NNg1OpdAVuXUEHr3Py5:b-fjr1dc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9809df48197591ffb67bd1a1a560af34dd9b027b/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding.go#L118)):*
> ```Go
> //	        "indexes":           { "type": "indexes" },
> //	        "errorCode":         { "type": "string" },
> //	        "errorMsg":          { "type": "string" },
> ```

this is suppose to be the same name of your properties, so use `lastErrorCode` and `lastError`
___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_impl.go` line 328 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96436#-NNg3BbDDM1a8u6zNpxu:-NNg3BbDDM1a8u6zNpxv:bcdg4ir) ([raw file](https://github.com/cockroachdb/cockroach/blob/9809df48197591ffb67bd1a1a560af34dd9b027b/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_impl.go#L328)):*
> ```Go
> 		{"firstAttemptCnt", (*jsonInt)(&s.FirstAttemptCount)},
> 		{"maxRetries", (*jsonInt)(&s.MaxRetries)},
> 		{"lastError", (*jsonString)(&s.SensitiveInfo.LastErr)},
> ```

This information (as the name says) is sensitive and can contain private info, so you can't save as is to the table. You will need to find generic messages to use instead.
___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_impl.go` line 343 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96436#-NNg1WSG3kDWcXcmrI4j:-NNg1WSG3kDWcXcmrI4k:bcr6afr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9809df48197591ffb67bd1a1a560af34dd9b027b/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_impl.go#L343)):*
> ```Go
> 		{"planGists", (*stringArray)(&s.PlanGists)},
> 		{"indexes", (*stringArray)(&s.Indexes)},
> 		{"errorCode", (*jsonString)(&s.ErrorCode)},
> ```

nit: use  `last`

**Review by gtr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96436)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @j82w and @maryliag)

___
*[`-- commits` line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96436#-NNg0Wxu12FGju2CtiCA):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

make sure you update the commit message with the same changes you added on the PR description.
</blockquote></details>

Done.
___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding.go` line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96436#-NNg1OpdAVuXUEHr3Py4:-NNgY0-61-POt0ZqeBC6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9809df48197591ffb67bd1a1a560af34dd9b027b/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding.go#L118)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

this is suppose to be the same name of your properties, so use `lastErrorCode` and `lastError`
</blockquote></details>

Done.
___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_impl.go` line 328 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96436#-NNg3BbDDM1a8u6zNpxu:-NNh1G4BATKyeb7UH5oz:b46o49k) ([raw file](https://github.com/cockroachdb/cockroach/blob/9809df48197591ffb67bd1a1a560af34dd9b027b/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_impl.go#L328)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

This information (as the name says) is sensitive and can contain private info, so you can't save as is to the table. You will need to find generic messages to use instead.
</blockquote></details>

As discussed on the team slack channel, I removed the `lastError` field for now and I am only adding the `lastErrorCode` field.
___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_impl.go` line 343 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96436#-NNg1WSG3kDWcXcmrI4j:-NNh1PlJEmv_ws7tuWvM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9809df48197591ffb67bd1a1a560af34dd9b027b/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_impl.go#L343)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: use  `last`
</blockquote></details>

Done.

**Comment by j82w** [comment]
*[`-- commits` line 10 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96436#-NNhg9lZ-Ip6tEBAfG4b):*
Is there a way to record the error type or some way to figure out which 40001 error the user hit?

**Review by gtr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96436)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @j82w and @maryliag)

___
*[`-- commits` line 10 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96436#-NNhg9lZ-Ip6tEBAfG4b):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Is there a way to record the error type or some way to figure out which 40001 error the user hit? 
</blockquote></details>

That information can be found in the `last_error` column of the `crdb_internal.{node|cluster}_statement_statistics` table for a statement with a 40001 error code. However, this column may contain sensitive information so it needs to be redacted before we can surface it.

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96436)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @gtr, @j82w, and @xinhaoz)

___
*[`-- commits` line 10 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96436#-NNhg9lZ-Ip6tEBAfG4b):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

That information can be found in the `last_error` column of the `crdb_internal.{node|cluster}_statement_statistics` table for a statement with a 40001 error code. However, this column may contain sensitive information so it needs to be redacted before we can surface it.
</blockquote></details>

We don't have much info about which 40001 error the user hit. That is the task @xinhaoz is working on.

**Review by maryliag — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r3, 22 of 22 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96436)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @gtr and @xinhaoz)

___
*[`pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go` line 288 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96436#-NNmfnnc02s3wvG-C2go:-NNmfnnc02s3wvG-C2gp:b-vki239) ([raw file](https://github.com/cockroachdb/cockroach/blob/be9b6d9b3d72d0c681dfc9dd32efb1015e07b355/pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go#L288)):*
> ```Go
> 		}
> 
> 		if stmtStats.mu.data.LastErrorCode == "" && key.failed {
> ```

why the current value needs to be empty string for this to be updated? did you mean to check `statistics[i].Stats.LastErrorCode` ? 
___
*[`pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go` line 478 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96436#-NNmg-II68N6szyl-_kM:-NNmg-II68N6szyl-_kN:bmsmkvo) ([raw file](https://github.com/cockroachdb/cockroach/blob/be9b6d9b3d72d0c681dfc9dd32efb1015e07b355/pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go#L478)):*
> ```Go
> 	}
> 
> 	if s.mu.data.LastErrorCode == "" && statistics.Key.Failed {
> ```

same question as above
___
*[`pkg/sql/logictest/testdata/logic_test/statement_statistics_errors` line 26 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96436#-NNmgKzJ8bfZGYCoRSbZ:-NNmgKzJ8bfZGYCoRSb_:bjp5zfn) ([raw file](https://github.com/cockroachdb/cockroach/blob/be9b6d9b3d72d0c681dfc9dd32efb1015e07b355/pkg/sql/logictest/testdata/logic_test/statement_statistics_errors#L26)):*
> ```
> 
> query T
> SELECT last_error_code FROM crdb_internal.node_statement_statistics WHERE last_error_code!='NULL';
> ```

use a `order by` to guarantee the order of results, otherwise you might create a flaky test
___
*[`pkg/sql/logictest/testdata/logic_test/statement_statistics_errors` line 36 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96436#-NNmgWD14wSBsFJhCAOo:-NNmgWD14wSBsFJhCAOp:bnj7hl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/be9b6d9b3d72d0c681dfc9dd32efb1015e07b355/pkg/sql/logictest/testdata/logic_test/statement_statistics_errors#L36)):*
> ```
> 
> query T
> SELECT last_error_code FROM crdb_internal.node_statement_statistics WHERE last_error_code!='NULL';
> ```

same as above

**Review by gtr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96436)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @xinhaoz)

___
*[`-- commits` line 10 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96436#-NNhg9lZ-Ip6tEBAfG4b):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

We don't have much info about which 40001 error the user hit. That is the task @xinhaoz is working on.
</blockquote></details>

Apologies for the misleading comment, I was looking at [this](https://github.com/cockroachdb/cockroach/issues/85256#issuecomment-1366857399) comment that said we've already got the error message but I see that those messages aren't being surfaced yet.

**Review by gtr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96436)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag and @xinhaoz)

___
*[`pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go` line 288 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96436#-NNmfnnc02s3wvG-C2go:-NNnChcE611FebBeHROm:b-ok0dfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/be9b6d9b3d72d0c681dfc9dd32efb1015e07b355/pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go#L288)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

why the current value needs to be empty string for this to be updated? did you mean to check `statistics[i].Stats.LastErrorCode` ? 
</blockquote></details>

Yes, I left this over from a previous iteration. The check is already done in the `StatementStatistics.Add()` function which is called above. Good catch, removing.
___
*[`pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go` line 478 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96436#-NNmg-II68N6szyl-_kM:-NNnCuE52Y35-0XKVtQw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/be9b6d9b3d72d0c681dfc9dd32efb1015e07b355/pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go#L478)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

same question as above
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/statement_statistics_errors` line 26 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96436#-NNmgKzJ8bfZGYCoRSbZ:-NNnCvF4CyhCkh7N5Vgm:b9nkcgw) ([raw file](https://github.com/cockroachdb/cockroach/blob/be9b6d9b3d72d0c681dfc9dd32efb1015e07b355/pkg/sql/logictest/testdata/logic_test/statement_statistics_errors#L26)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

use a `order by` to guarantee the order of results, otherwise you might create a flaky test
</blockquote></details>

Updated the queries to order by `last_error_code`.
___
*[`pkg/sql/logictest/testdata/logic_test/statement_statistics_errors` line 36 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96436#-NNmgWD14wSBsFJhCAOo:-NNnD26v3r0w7hDRzLw9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/be9b6d9b3d72d0c681dfc9dd32efb1015e07b355/pkg/sql/logictest/testdata/logic_test/statement_statistics_errors#L36)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.

**Review by maryliag — APPROVED** [review]
:lgtm: as long as tests are passing

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96436#-:-NNnH294Dae4gm2JS4eO:b-x7082r)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @gtr and @xinhaoz)

**Comment by gtr** [comment]
TFTR!
bors r+

**Pull request merged**
