### PR TITLE
github: update codeowners

### PR DESCRIPTION
**Pull request by nicktrav**
Update all instances of `repl-prs` to `kv-prs`.

Release note: None.

Epic: None.

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
:lgtm: 

Do we also want to remove other usages of `repl-prs` from CODEOWNERS? 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126692#-:-O0tjDOW1asQmv38vD6o:b-cw7mfe)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv)

**Comment by nicktrav** [comment]
Woops, you're right. Let me fix this up to do a bulk replace.

**Review by arulajmani — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126692#-:-O0tm3PjCeuKDqabVJRs:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jlinder and @pav-kv)

**Review by pav-kv — APPROVED** [review]

**Comment by nicktrav** [comment]
TFTRs!

bors r+

**Pull request merged**
