### PR TITLE
sql: name the transaction settings like PG does

### LINKED ISSUE #18506: pgwire: ODBC error: "unknown variable: transaction_isolation" with crdb 1.1
While initially opening an ODBC connection to a crdb cluster, using the official PG driver, I get error: "unknown variable: transaction_isolation".

### PR DESCRIPTION
**Pull request by knz**
Fixes #18506.

In PostgreSQL, the transaction isolation level is reported by the
session variable `transaction_isolation` (two words separated by an
underscore), not `transaction isolation level` (three words separated
by spaces). Also the iso level is reported in lowercase.

Clients actually care about this stuff.

This patch makes CockroachDB behave more like PG.

This also aligns `transaction_priority` and `transaction_status`
(CockroachDB extension) with `transaction_isolation` (PG standard
setting), for more consistency in UX.

----

Release note (sql): the session settings `transaction isolation
level`, `transaction priority` and `transaction status` are now called
`transaction_isolation`, `transaction_priority` and
`transaction_status` for better compatibility with PostgreSQL.

### CODE REVIEW

**Comment by knz** [comment]
Might want to cherry-pick to 1.1, what do you think?

**Comment by knz** [comment]
@jordanlewis please let the first commit here inform your change in #20274.

**Comment by jordanlewis** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 11 of 11 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/vars.go, line 243 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20264#-KzySl07kzdLK-gp4PzM:-KzySl07kzdLK-gp4PzN:b-zeg8gs) ([raw file](https://github.com/cockroachdb/cockroach/blob/f18199d8c75df4aae68d13a06c44ce002ba9ca34/pkg/sql/vars.go#L243)):*
> ```Go
> 	},
> 
> 	// CockroachDB extension (inspired from MySQL).
> ```

nit that's not worth another round of CI: inspired *by*, not from

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20264#-:-KzyTS5SN5Kuk1Fxonzk:bnfp4nl)*

**Comment by knz** [comment]
TFYR

**Comment by knz** [comment]
Perhaps you can fix the grammar in your #20274 patch?

**Comment by BrianSullivan1956** [comment]
New to the whole github thing. 
How do I find the build this is in?

CCL v1.1.3 @ 2017/11/27 13:59:10 (go1.8.3)  
o show transaction_isolation
returns
o pq: unknown variable: "transaction_isolation"

**Comment by benesch** [comment]
Afraid it's not in any release yet, but it'll be in the next 1.2 alpha release scheduled for December 4: https://github.com/cockroachdb/cockroach/issues/20272

**Comment by knz** [comment]
@jordanlewis do you reckon we should cherry pick this onto 1.1?

**Comment by jordanlewis** [comment]
@knz yes. There is some danger because the casing of the settings changed, but if anyone was using those we would likely have heard complaints about the PG incompatibility already.

**Pull request merged**
