### PR TITLE
storage: Renumber proposer-evaluated KV RaftCommand fields

### LINKED ISSUE #10723: stability: cyan crashing after on disk/memory state diverged
cyan nodes started crashing after an upgrade to 981b8aa at 20161116-04:00 UTC.
The previous build on cyan was 85f80d9 at 20161115-23:00 UTC.

Nodes crashed within a minute with:
```
F161116 04:00:56.433545 107 storage/replica.go:1113  [n1,s1,r3974/4:/Table/51/1/908{59106…-81657…}] on-disk and in-memory state diverged:
[Lease.StartStasis.WallTime: 1479268833127627548 != 1479268840607062711 Lease.Expiration.WallTime: 1479268833377627548 != 1479268840857062711 Lease.ProposedTS.WallTime: 1479268824127630948 != 1479268831607066111]
```

### PR DESCRIPTION
**Pull request by bdarnell**
Older versions were writing non-nil but empty values into these fields,
leading to problems on upgrade. Since there is no non-experimental use
of these fields yet, renumber them to discard all old data.

Fixes #10723

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10724)

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
LGTM

**Comment by mberhault** [comment]
I know we generally shy away from this, but I'll merge this for Ben and see if it fixes cyan.

**Comment by petermattis** [comment]
I think Cyan will have to be wiped. You'll have to ask Ben to be sure.

**Comment by mberhault** [comment]
He said the following in slack/production: `merging that and deploying it to cyan should fix things (with no need to wipe the cluster)` so I'll give a plain restart a shot

**Pull request merged**
