### PR TITLE
spanconfig/kvaccessor: re-work validation query

### PR DESCRIPTION
**Pull request by irfansharif**
The previous validation query used point scans for each span being
upserted, and ended up being very memory intensive. This PR changes the
validation query to instead validate a single large span straddling all
the individual spans being upserted. The benchmark added in the previous
commit demonstrates the speed up:
```
   dev bench pkg/spanconfig/spanconfigkvaccessor
    -f=BenchmarkKVAccessorUpdate -v --bench-time=20x
```
Before:
```
  BenchmarkKVAccessorUpdate/batch-size=100-10       20     61.55 ms/batch     1.625 records/ms
  BenchmarkKVAccessorUpdate/batch-size=1000-10      20      1645 ms/batch     0.6078 records/ms
  BenchmarkKVAccessorUpdate/batch-size=10000-10     ran into memory bound account errors
```
After:
```
  BenchmarkKVAccessorUpdate/batch-size=100-10      200     11.25 ms/batch     8.889 records/ms
  BenchmarkKVAccessorUpdate/batch-size=1000-10     200     48.40 ms/batch     20.66 records/ms
  BenchmarkKVAccessorUpdate/batch-size=10000-10    200     222.6 ms/batch     44.92 records/ms
```
We want to validate that upserting spans does not break the invariant
that spans in the table are non-overlapping. We only need to validate
the spans that are being upserted, and can use a query similar to what
we do in GetSpanConfigRecords. For a single upserted span, we want
effectively validate using:
```sql
  -- verify only a single span overlaps with [$start, $end)
  SELECT count(*) = 1 FROM system.span_configurations
   WHERE start_key < $end AND end_key > $start
```
With the naive form above that translates to an unbounded index scan on
followed by a filter. Since start_key < end_key, and that spans are
non-overlapping, we can instead do the following:
```sql
  SELECT bool_and(valid) FROM (
   SELECT bool_and(prev_end_key IS NULL OR start_key >= prev_end_key) AS valid FROM (
    SELECT start_key, lag(end_key, 1) OVER (ORDER BY start_key) AS prev_end_key FROM span_configurations
    WHERE start_key >= $start AND start_key < $end
   )
   UNION ALL
   SELECT * FROM (
    SELECT $start >= end_key FROM span_configurations
    WHERE start_key < $start ORDER BY start_key DESC LIMIT 1
   )
  )
```
The idea is to first find all spans that start within the span being
upserted[^1], compare each start key to the preceding end key[^2] (if any)
and ensure that they're non-overlapping[^3]. We also verify the span with
the start key immediately preceding the span being upserted[^4]; ensuring
that our upserted span does not overlap with it[^5].

When multiple spans are being upserted, we validate instead the span
straddling all the individual spans being upserted, i.e.
[$smallest-start-key, $largest-end-key).

[^1]: WHERE start_key >= $start AND start_key < $end
[^2]: lag(end_key, 1) OVER (ORDER BY start_key) AS prev_end_key
[^3]: start_key >= prev_end_key
[^4]: WHERE start_key < $start ORDER BY start_key DESC LIMIT 1
[^5]: $start >= end_key

Release note: None
Release justification: low risk, high benefit change

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
Nice find! :100: 

The change makes sense, but I noticed that we don't have much testing that exercises this code. There only seems to be one test case in `parial_overlap` -- would you mind sprucing up this PR with more tests, while we're here?

> Reviewed 2 of 2 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78160#-:-MyhCmiXEm8E3g4eodtq:b-vag3h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @irfansharif)

___
*[pkg/spanconfig/spanconfigkvaccessor/kvaccessor.go, line 397 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78160#-MyhFAbY8wY5eAP31nEo:-MyhFAbY8wY5eAP31nEp:b-i8d309) ([raw file](https://github.com/cockroachdb/cockroach/blob/79785ea74937acbac70ae3faf0419b62f40c51d3/pkg/spanconfig/spanconfigkvaccessor/kvaccessor.go#L397)):*
> ```Go
> 	validationQueryArgs := make([]interface{}, 2)
> 	validationQueryArgs[0] = targetsToUpsert[0].Encode().Key
> 	validationQueryArgs[1] = targetsToUpsert[len(targetsToUpsert)-1].Encode().EndKey
> ```

nit: Let's add a comment here that explains why this is indeed the largest end key (it's because of the validation we do before, right?)

**Review by ajwerner — COMMENTED** [review]
Query change :lgtm:, and I agree that more correctness testing around these parts would not hurt. Also you've got some `timeutil` linter complaints 

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78160#-:-MyjOQTzBtupHBzs1WM6:brnsvn4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif)

**Review by ajwerner — COMMENTED** [review]
Do we have any metrics on the kvaccessor methods? might be good to have number of invocations, number of spans, how long they take (even if just a counter of total duration). 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78160#-:-MyjOt1MC85YZlEODJE7:b9eu243)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif)

**Review by irfansharif — COMMENTED** [review]
Added a bunch of tests and the linter change, PTAL. Metrics for the KVAccessor seems like a good idea, added to https://github.com/cockroachdb/cockroach/issues/73874.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78160#-:-MynezU46qRFd4R7lmWm:b2ghhn4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, and @irfansharif)

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78160)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @arulajmani)

___
*[pkg/spanconfig/spanconfigkvaccessor/kvaccessor.go, line 397 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78160#-MyhFAbY8wY5eAP31nEo:-MyngBol5xUbJ9mBDFQ-:b-6ik8yl) ([raw file](https://github.com/cockroachdb/cockroach/blob/79785ea74937acbac70ae3faf0419b62f40c51d3/pkg/spanconfig/spanconfigkvaccessor/kvaccessor.go#L397)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: Let's add a comment here that explains why this is indeed the largest end key (it's because of the validation we do before, right?)
</blockquote></details>

+ because we're sorting above, based on start keys, and yes, validation validation that ensures spans are non-overlapping. Done.

**Review by arulajmani — APPROVED** [review]
Thanks for adding these testcases. The diagrams are a solid quality of life addition! :100: 

> Reviewed 7 of 7 files at r6, 2 of 2 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78160#-:-MynvuciDcZkGBOCuH2N:bd84wad)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif)

___
*[pkg/spanconfig/spanconfigkvaccessor/kvaccessor.go, line 397 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78160#-MyhFAbY8wY5eAP31nEo:-MynuB7_0V6lnMQKtF0Y:b-ioswn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/79785ea74937acbac70ae3faf0419b62f40c51d3/pkg/spanconfig/spanconfigkvaccessor/kvaccessor.go#L397)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

+ because we're sorting above, based on start keys, and yes, validation validation that ensures spans are non-overlapping. Done.
</blockquote></details>

nit: s/upser/upsert/
___
*[pkg/spanconfig/spanconfigkvaccessor/testdata/validation_overlapping, line 79 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/78160#-MynvOXB360v5gQ7uWhQ:-MynvOXB360v5gQ7uWhR:bvmnjbq) ([raw file](https://github.com/cockroachdb/cockroach/blob/915bf842c9029d8e9a492d84f1ee0aa254d8edfc/pkg/spanconfig/spanconfigkvaccessor/testdata/validation_overlapping#L79)):*
> ```
> 
> # keys    a  b  c  d  e  f  g  h  i  j
> # state      [-----X--------)
> ```

Can we add two more test cases here, very similar to this, one with just `upsert [d,e):B` and another with just `upsert [f,g):C`? You already have one for just A as your first test case.

**Review by irfansharif — COMMENTED** [review]
Thanks!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78160#-:-Myo9wCg5m0NcgbazIHp:b-voiyyw)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani)

___
*[pkg/spanconfig/spanconfigkvaccessor/testdata/validation_overlapping, line 79 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/78160#-MynvOXB360v5gQ7uWhQ:-Myo9vGk8l47JSx7HYHQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/915bf842c9029d8e9a492d84f1ee0aa254d8edfc/pkg/spanconfig/spanconfigkvaccessor/testdata/validation_overlapping#L79)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Can we add two more test cases here, very similar to this, one with just `upsert [d,e):B` and another with just `upsert [f,g):C`? You already have one for just A as your first test case.
</blockquote></details>

Done.

**Pull request merged**
