### PR TITLE
ui: link to logspy on debug page

### PR DESCRIPTION
**Pull request by tbg**

### CODE REVIEW

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18341#-:-KtSwVsRHLi8PWgul5ue:bnfp4nl)*

**Comment by BramGruneir** [comment]
Reviewed 1 of 1 files at r1, 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/ui/src/views/reports/containers/debug/index.tsx, line 106 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18341#-KtSwUWhP-n-9SOtJFqr:-KtSwUWhP-n-9SOtJFqs:b-i3nq6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/10c87466469420ba783a979aa26f0e734456daac/pkg/ui/src/views/reports/containers/debug/index.tsx#L106)):*
> ```XML
>           <DebugTableLink name="Requests" url="/debug/requests" />
>           <DebugTableLink name="Events" url="/debug/events" />
>           <DebugTableLink name="Logs" url="/debug/logspy?count=1&amp;duration=10s&amp;grep=." />
> ```

Please add a `note`, on how to construct the url by hand.  See the other for examples.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18341)*

**Comment by BramGruneir** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18341)*

**Comment by tschottdorf** [comment]
TFTRs!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/ui/src/views/reports/containers/debug/index.tsx, line 106 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18341#-KtSwUWhP-n-9SOtJFqr:-KtSxpkXyMWZNnZY0DFk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/10c87466469420ba783a979aa26f0e734456daac/pkg/ui/src/views/reports/containers/debug/index.tsx#L106)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Please add a `note`, on how to construct the url by hand.  See the other for examples.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18341#-:-KtT-tKPSkfZrLP-60A8:bz5mair)*

**Comment by BramGruneir** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18341#-:-KtT2I49rAgjGRD750Wp:bnfp4nl)*

**Comment by BramGruneir** [comment]
Reviewed 1 of 3 files at r5.
Review status: 2 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18341)*

**Comment by BramGruneir** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18341)*

**Pull request merged**
