### PR TITLE
gceworker: change cron job to ignore /.active after 2 days

### PR DESCRIPTION
**Pull request by ajwerner**
It's easy to forget that you've left your gceworker running when you touch /.active. This leads to lots of wasted resources. Here we change the definition of /.active to only count it if the mod time is less than two days ago. This may prove to be frustrating for some folks, but those folks can set the mod time to something in the future or set something else in their enviroment to regularly touch the file. Also, it's easy enough for anybody who is so inclined to change the script to meet their needs on their own gceworker. This should be a more sane default.

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
Note that this won't affect existing gceworkers, but we can roll it out easily enough if we're happy with it.

**Review by yuzefovich — COMMENTED** [review]
Big +1 on the change, but I'll defer to someone else to properly review it since I'm a complete noob in this stuff.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89412#-:-NDdeNLx5-3_yWm6fb2R:buvhb3h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by jlinder — APPROVED** [review]
Noice.

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Pull request merged**
