### PR TITLE
release-20.2: sql: pre-scan index spans with SQL

### PR DESCRIPTION
**Pull request by dt**
Back in 17956af30 we fixed a bug where an index SST could slip a
kv between an existing kv and its intent, causing horrible problems,
by scanning the 'empty' span at the ts we would write at, to ensure
there were no intents at that time and populate the tscache to
prevent any new ones.

We did this with a kv scan paginated into 10k batches. However if
a large backfill is _resumed_ then the span is not empty, and this
scan could take a very long time since limited batches are not
not parallelized. If it takes longer than the GC TTL, it may
never complete at all, and end up stuck retrying forever.

In one recent example, a 140B row table had a new index backfill
attempt to resume when 65% complete, needing to scan 92B rows.
With the speed at which it was processing 10k batches, this was
expected to take 92 days.

For forward indexes, we can count their entries using SQL. This
will in turn make use of distsql to parallelize across many
tablereaders, use vectorized execution, and any other optimizations
that the sql execution engine includes.

Sadly there is no SQL-accessible way to count an inverted index,
but at least for forward indexes this optimization could prove
to be a win for resuming large index backfills.

This optimization is kept behind a setting for now though, but can
be enabled by toggling `schemachanger.bulk_index_backfill.pre_scan_via_sql`.

Release note: none.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63704)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @jordanlewis, and @nvanbenschoten)

___
*[pkg/sql/backfill.go, line 977 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63704#-MYKkW4ZDpWAFF6OAIua:-MYKkW4ZDpWAFF6OAIub:b-cpv4o4) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a258a6931c531ed816bc71834fa498d9861ba6/pkg/sql/backfill.go#L977)):*
> ```Go
> 						return err
> 					}
> 					ie := sc.ieFactory(ctx, newFakeSessionData()).(*InternalExecutor)
> ```

There are public APIs here that you are expected to use:

1) use the factory or use the internal executor on the `execCfg`
2) use `WithSyntheticDescriptors`

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63704)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jordanlewis, and @nvanbenschoten)

___
*[pkg/sql/backfill.go, line 977 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63704#-MYKkW4ZDpWAFF6OAIua:-MYKml8AEj1v9JG_owxh:b-gyb3wg) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a258a6931c531ed816bc71834fa498d9861ba6/pkg/sql/backfill.go#L977)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

There are public APIs here that you are expected to use:

1) use the factory or use the internal executor on the `execCfg`
2) use `WithSyntheticDescriptors`
</blockquote></details>

1. Which factory (if not this one) / what evalCtx? 
2. I don't think `WithSyntheticDescriptors` existed back here.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63704)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @jordanlewis, and @nvanbenschoten)

___
*[pkg/sql/backfill.go, line 977 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63704#-MYKkW4ZDpWAFF6OAIua:-MYL032ODRVdTPnKd8q7:b-659hc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a258a6931c531ed816bc71834fa498d9861ba6/pkg/sql/backfill.go#L977)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

1. Which factory (if not this one) / what evalCtx? 
2. I don't think `WithSyntheticDescriptors` existed back here.

</blockquote></details>

1. I mean call it, don't type assert it
2. Can you label this PR with `release-20.2` I thought this was against master, hence the comment. Probably if we make this change we should make it against master and then do the backports (which may not be perfectly clean).

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63704)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jordanlewis, and @nvanbenschoten)

___
*[pkg/sql/backfill.go, line 977 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63704#-MYKkW4ZDpWAFF6OAIua:-MYL0oU4-b8aqNRAcotg:baksjiy) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a258a6931c531ed816bc71834fa498d9861ba6/pkg/sql/backfill.go#L977)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

1. I mean call it, don't type assert it
2. Can you label this PR with `release-20.2` I thought this was against master, hence the comment. Probably if we make this change we should make it against master and then do the backports (which may not be perfectly clean). 
</blockquote></details>

1. I still don't understand. I am calling it? but I also have to cast to the concrete type (the way we do below as well) to get to the tcModifier -- the function sig returns the interface type.
2. labeled. I'd rather get it working on 20.2 and forward-port, since like you say, the rebases around anything touching descs/catalog/etc are a mess and customer is waiting on 20.2 nightly for a fix, so I'd rather start here then get it to master.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63704#-:-MYL6Okh1TF_rtMGY54B:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @jordanlewis, and @nvanbenschoten)

___
*[pkg/sql/backfill.go, line 977 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63704#-MYKkW4ZDpWAFF6OAIua:-MYL6CIHAGKoSGepmoLp:b-glwcub) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a258a6931c531ed816bc71834fa498d9861ba6/pkg/sql/backfill.go#L977)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

1. I still don't understand. I am calling it? but I also have to cast to the concrete type (the way we do below as well) to get to the tcModifier -- the function sig returns the interface type.
2. labeled. I'd rather get it working on 20.2 and forward-port, since like you say, the rebases around anything touching descs/catalog/etc are a mess and customer is waiting on 20.2 nightly for a fix, so I'd rather start here then get it to master.
</blockquote></details>

Whoops, my bad, sorry. 
___
*[pkg/sql/backfill.go, line 1586 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63704#-MYL6HvX-1ssASI52u6I:-MYL6HvX-1ssASI52u6J:b-myc58q) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a258a6931c531ed816bc71834fa498d9861ba6/pkg/sql/backfill.go#L1586)):*
> ```Go
> 	if err := sc.distBackfill(
> 		ctx, version, columnBackfill, columnTruncateAndBackfillChunkSize,
> 		backfill.ColumnMutationFilter, nil, nil); err != nil {
> ```

Nit: comment the nil args

**Comment by jordanlewis** [comment]
Did you test this on a real cluster? I think it will fail to do what you want because internal executor queries don't use distsql. You will need to take patch 2 from https://github.com/cockroachdb/cockroach/pull/63654, which feels like it could be risky in its own right...

**Review by dt — COMMENTED** [review]
Gah. I tested it but only on a small, local node. That limitation certainly throws a wrench in this. But also, even if it were distributed, on re-examination, I'm not sure that'd be enough for the table sizes that motivated this. I'm going to let this sit until next week to see if we want to just do something else instead.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63704#-:-MYLQ2RP1HHXC60mlOeN:b-1xbxb9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @jordanlewis, and @nvanbenschoten)

**Comment by dt** [comment]
I'll probably close this in favor of backporting #63945

**Pull request closed without merging**
