### PR TITLE
sqlsmith: add trigrams and other missing cmpops

### LINKED ISSUE #83933: sql: add trigram generators for sqlsmith and TLP
We should ensure that sqlsmith and TLP are testing trigram inverted indexes.

Epic: CRDB-15016

Jira issue: CRDB-17361

### PR DESCRIPTION
**Pull request by jordanlewis**
Resolves #83933.

Previously, sqlsmith and randgen were missing some important expression
types:

1. Trigram inverted indexes. Now, they're generated sometimes when a
   string column is the last column in an index.
2. The string % string, inet << inet and inet >> inet "comparison"
   operators. These are listed under the binary operator list, so they
   weren't getting automatically included when picking a random
   comparison operator. This is now corrected.
3. Several less common cmp ops were missing, such as LIKE, ILIKE, @>,
   <@, ?, ?|, ?&, IN, SIMILAR TO, ~, ~*, &&, IS DISTINCT FROM. These are
   now included.

Release note: None

### CODE REVIEW

**Review by msirek — COMMENTED** [review]
Nice extension to test coverage!

> Reviewed 3 of 3 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84094#-:-N6sGX4q52QXt7B0NR4v:bzglp69)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @mgartner)

___
*[`pkg/internal/sqlsmith/scalar.go` line 287 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84094#-N6sC51oE_9k5rrojQtv:-N6sC51oE_9k5rrojQtw:b-7zpocj) ([raw file](https://github.com/cockroachdb/cockroach/blob/26084faccb006fa33a87e546126e51f045ed1560/pkg/internal/sqlsmith/scalar.go#L287)):*
> ```Go
> func init() {
> 	for op := range tree.CmpOps {
> 		compareOps = append(compareOps, op)
> ```

The `tree.CmpOps` map doesn't include the following ops (because rules for `EQ` cover `NE`, `LE` covers `GE`, etc.):
```
NE, NotIn, GE, GT, IsDistinctFrom, NotRegMatch, NotRegIMatch, NotLike, NotILike, NotSimilarTo
```
Maybe they can be manually added here.
There are also these Ops which aren't in the map:
```
	Any
	Some
	All
	NumComparisonOperatorSymbols
```
I'm wondering if SQLSmith would generate them correctly if we added them here too. One way to add these would be to iterate from `EQ` up to the last op, `NumComparisonOperatorSymbols`.
___
*[`pkg/sql/randgen/expr.go` line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84094#-N6sFDrBDScwZJolrUGt:-N6sFDrBDScwZJolrUGu:b-n4g5um) ([raw file](https://github.com/cockroachdb/cockroach/blob/26084faccb006fa33a87e546126e51f045ed1560/pkg/sql/randgen/expr.go#L89)):*
> ```Go
> 
> // TODO(jordan): should we be including more comparison operators here?
> var cmpOps = []treecmp.ComparisonOperatorSymbol{treecmp.EQ, treecmp.NE, treecmp.LT, treecmp.LE, treecmp.GE, treecmp.GT}
> ```

I added a note in #83611 to also add more comparison operators in this location.



_Code quote:_
```Go
var cmpOps = []treecmp.ComparisonOperatorSymbol{treecmp.EQ, treecmp.NE, treecmp.LT, treecmp.LE, treecmp.GE, treecmp.
```

**Review by mgartner — APPROVED** [review]
:lgtm: Thanks!

> Reviewed 3 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84094#-:-N6suWmB3Du9lz1WLHCE:b-g2a5fb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[`pkg/sql/show_test.go` line 288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84094#-N6sqlUD8_rnbzdc_QN6:-N6sqlUE1K1gsVHAQBCp:bkj1za0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6baf57874fa78e37ddbcfd86a889ff25839b7ce5/pkg/sql/show_test.go#L288)):*
> ```Go
> 	a STRING NULL,
> 	CONSTRAINT %[1]s_pkey PRIMARY KEY (id ASC),
> 	INVERTED INDEX %[1]s_a_idx (a gin_trgm_ops ASC)
> ```

TIL you can change the direction of inverted indexes. And now I'll lose sleep thinking about all the possible bugs lurking there...

Interestingly, the direction doesn't round-trip for other INVERTED indexes. I can fix that in another commit:

```
demo@127.0.0.1:26257/defaultdb> create table t (k int primary key, j json, inverted index (j desc));
CREATE TABLE

demo@127.0.0.1:26257/defaultdb> show create table t;
  table_name |              create_statement
-------------+---------------------------------------------
  t          | CREATE TABLE public.t (
             |     k INT8 NOT NULL,
             |     j JSONB NULL,
             |     CONSTRAINT t_pkey PRIMARY KEY (k ASC),
             |     INVERTED INDEX t_j_idx (j)
             | )
(1 row)

demo@127.0.0.1:26257/defaultdb> show indexes from t;
  table_name | index_name | non_unique | seq_in_index | column_name | direction | storing | implicit
-------------+------------+------------+--------------+-------------+-----------+---------+-----------
  t          | t_j_idx    |    true    |            1 | j           | DESC      |  false  |  false
  t          | t_j_idx    |    true    |            2 | k           | ASC       |  false  |   true
  t          | t_pkey     |   false    |            1 | k           | ASC       |  false  |  false
  t          | t_pkey     |   false    |            2 | j           | N/A       |  true   |  false
(4 rows)
```

**Comment by jordanlewis** [comment]
> TIL you can change the direction of inverted indexes. And now I'll lose sleep thinking about all the possible bugs lurking there...

I think it might be a lie - we might eat the keywords and then ignore them. I hope. And maybe that's why it doesn't roundtrip.

**Comment by mgartner** [comment]
The `SHOW INDEXES` output I included shows `DESC` though.

**Comment by jordanlewis** [comment]
😱

**Comment by mgartner** [comment]
Created an issue for that here: https://github.com/cockroachdb/cockroach/issues/84388

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84094)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @mgartner, and @msirek)

___
*[`pkg/internal/sqlsmith/scalar.go` line 287 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84094#-N6sC51oE_9k5rrojQtv:-N6u2gir1dkiKsyZ5MYR:b-j4tev) ([raw file](https://github.com/cockroachdb/cockroach/blob/26084faccb006fa33a87e546126e51f045ed1560/pkg/internal/sqlsmith/scalar.go#L287)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

The `tree.CmpOps` map doesn't include the following ops (because rules for `EQ` cover `NE`, `LE` covers `GE`, etc.):
```
NE, NotIn, GE, GT, IsDistinctFrom, NotRegMatch, NotRegIMatch, NotLike, NotILike, NotSimilarTo
```
Maybe they can be manually added here.
There are also these Ops which aren't in the map:
```
	Any
	Some
	All
	NumComparisonOperatorSymbols
```
I'm wondering if SQLSmith would generate them correctly if we added them here too. One way to add these would be to iterate from `EQ` up to the last op, `NumComparisonOperatorSymbols`.
</blockquote></details>

Good point, I took your second suggestion. For now, we have to skip ANY/SOME/ALL because they do require "sub operators" e.g. `WHERE x = ANY(...)`.

**Review by msirek — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84094#-:-N6u4yGS3vYt7fs0lrKs:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis)

___
*[`pkg/internal/sqlsmith/scalar.go` line 287 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84094#-N6sC51oE_9k5rrojQtv:-N6u4tli1ttH7qB0CTGO:b32w0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/26084faccb006fa33a87e546126e51f045ed1560/pkg/internal/sqlsmith/scalar.go#L287)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Good point, I took your second suggestion. For now, we have to skip ANY/SOME/ALL because they do require "sub operators" e.g. `WHERE x = ANY(...)`.
</blockquote></details>

OK



_Code quote:_
```Go
NumComparisonOperatorSymbols
```

**Pull request merged**
