### PR TITLE
ui: gate node map behind license

### PR DESCRIPTION
**Pull request by vilterp**
When you don't have a license and go to the node map, you'll see this:

image

Once you add your license key, you'll see the map.

TODO:
- [ ] review copy.

Related: defaulting to node list vs node map in different states (#23871)
Also related: instructions box (#23516)

Release note (admin ui change): Hides the node map if you don't have a valid enterprise license.

### CODE REVIEW

**Comment by couchand** [comment]
as i mentioned in meatspace getting activity on that screenshot would be nice, otherwise :lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: 6 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/needEnterpriseLicense.tsx, line 23 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23852#-L7eqPgoj9Cw2bCkmolA:-L7eqPgoj9Cw2bCkmolB:bj2atlj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a498e1760f9cf2a405a2809f70bafa5e340e364/pkg/ui/ccl/src/views/clusterviz/containers/map/needEnterpriseLicense.tsx#L23)):*
> ```XML
>             <h1 className="need-license-blurb__header">Get a Clearer View of Your Cluster</h1>
>             <p className="need-license-blurb__text">
>               The Node Map shows your nodes on a map, grouped by locality.{" "}
> ```

Does React really collapse away the space between `.` and `The` if you don't include this?  :man_facepalming:

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/needEnterpriseLicense.tsx, line 28 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23852#-L7epKyPfD7AhYpvegGV:-L7epKyPfD7AhYpvegGW:b-23vxcw) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a498e1760f9cf2a405a2809f70bafa5e340e364/pkg/ui/ccl/src/views/clusterviz/containers/map/needEnterpriseLicense.tsx#L28)):*
> ```XML
>             </p>
>           </div>
>           <a href={TRIAL_LICENSE_URL} className="need-license-blurb__trial_link">
> ```

not sure how pedantic to be here (the answer is obviously less than this), but that last underscore looks weird.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/needEnterpriseLicense.tsx, line 33 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23852#-L7eqgMir4NaOmFmK0hH:-L7eqgMjAo32DDq01wRp:b10x7pa) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a498e1760f9cf2a405a2809f70bafa5e340e364/pkg/ui/ccl/src/views/clusterviz/containers/map/needEnterpriseLicense.tsx#L33)):*
> ```XML
>         </div>
>         <div className="need-license-steps">
>           <Step num={1} text={"Get a trial license delivered straight to your inbox."} img={step1} />
> ```

the text doesn't need curlies

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/needEnterpriseLicense.tsx, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23852#-L7eqnYx-ETFixcCeLzS:-L7eqnYx-ETFixcCeLzT:bb7bipv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a498e1760f9cf2a405a2809f70bafa5e340e364/pkg/ui/ccl/src/views/clusterviz/containers/map/needEnterpriseLicense.tsx#L42)):*
> ```XML
> }
> 
> function Step(props: { num: number, text: string, img?: string }) {
> ```

`?`?

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/needEnterpriseLicense.tsx, line 46 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23852#-L7erteetkVnhAvBuxVC:-L7erteetkVnhAvBuxVD:b8c778e) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a498e1760f9cf2a405a2809f70bafa5e340e364/pkg/ui/ccl/src/views/clusterviz/containers/map/needEnterpriseLicense.tsx#L46)):*
> ```XML
>     <div className="license-step">
>       <div className="license-step__image">
>         
> ```

maybe put the width in the stylesheet?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23852#-:-L7es4B0sE6fAq9nwsig:bjqpw1x)*

**Comment by vilterp** [comment]
Got some activity on the screenshot (thx @dianasaur323)

---

Review status: 6 of 9 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/needEnterpriseLicense.tsx, line 23 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23852#-L7eqPgoj9Cw2bCkmolA:-L7ewBKA6xXOpjDipENL:b6ez654) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a498e1760f9cf2a405a2809f70bafa5e340e364/pkg/ui/ccl/src/views/clusterviz/containers/map/needEnterpriseLicense.tsx#L23)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

Does React really collapse away the space between `.` and `The` if you don't include this?  :man_facepalming:
</blockquote></details>

Done. You're right; wasn't necessary.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/needEnterpriseLicense.tsx, line 28 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23852#-L7epKyPfD7AhYpvegGV:-L7ewg4Q6B_eK3GWBtnh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a498e1760f9cf2a405a2809f70bafa5e340e364/pkg/ui/ccl/src/views/clusterviz/containers/map/needEnterpriseLicense.tsx#L28)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

not sure how pedantic to be here (the answer is obviously less than this), but that last underscore looks weird.
</blockquote></details>

Done.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/needEnterpriseLicense.tsx, line 33 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23852#-L7eqgMir4NaOmFmK0hH:-L7ewgy-0sQbeLvOUEqY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a498e1760f9cf2a405a2809f70bafa5e340e364/pkg/ui/ccl/src/views/clusterviz/containers/map/needEnterpriseLicense.tsx#L33)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

the text doesn't need curlies
</blockquote></details>

Done.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/needEnterpriseLicense.tsx, line 42 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23852#-L7eqnYx-ETFixcCeLzS:-L7ewhN-C7t7J9YG3dr9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a498e1760f9cf2a405a2809f70bafa5e340e364/pkg/ui/ccl/src/views/clusterviz/containers/map/needEnterpriseLicense.tsx#L42)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

`?`?
</blockquote></details>

Done.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/needEnterpriseLicense.tsx, line 46 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23852#-L7erteetkVnhAvBuxVC:-L7ewkt4AOtJBv6NSmPn:bp75epb) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a498e1760f9cf2a405a2809f70bafa5e340e364/pkg/ui/ccl/src/views/clusterviz/containers/map/needEnterpriseLicense.tsx#L46)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

maybe put the width in the stylesheet?
</blockquote></details>

Stylesheet also has a width. They both seem to be necessary.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23852#-:-L7exCPkEJ5wbV_jRjAC:b-9pon5h)*

**Comment by couchand** [comment]
Reviewed 3 of 3 files at r2.
Review status: 6 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/needEnterpriseLicense.tsx, line 46 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23852#-L7erteetkVnhAvBuxVC:-L7f6U10d2DgtT6xkSAY:bj6h1tg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a498e1760f9cf2a405a2809f70bafa5e340e364/pkg/ui/ccl/src/views/clusterviz/containers/map/needEnterpriseLicense.tsx#L46)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

Stylesheet also has a width. They both seem to be necessary.
</blockquote></details>

I'm not seeing the width in a stylesheet here, is it not in this diff?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23852)*

**Comment by vilterp** [comment]
Review status: 4 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/needEnterpriseLicense.tsx, line 46 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23852#-L7erteetkVnhAvBuxVC:-L7f7j-XvHVgvcok3VBJ:boanen) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a498e1760f9cf2a405a2809f70bafa5e340e364/pkg/ui/ccl/src/views/clusterviz/containers/map/needEnterpriseLicense.tsx#L46)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

I'm not seeing the width in a stylesheet here, is it not in this diff?
</blockquote></details>

Whoops yeah I had removed it. Ok, in the stylesheet now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23852)*

**Comment by vilterp** [comment]
Design notes:
- drop "free" from button
- link to enterprise license page from blurb
- add horizontal rule above steps
- use lato-bold to bold stuff

**Comment by couchand** [comment]
Reviewed 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 2 of 5 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/needEnterpriseLicense.tsx, line 24 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/23852#-L7j5EdBTZURpA5PqQ5Q:-L7j5EdC98HJmWzAFOzt:b-9a304f) ([raw file](https://github.com/cockroachdb/cockroach/blob/733c3ec84a7f2935b7a83cd6d9087602dbb3ab19/pkg/ui/ccl/src/views/clusterviz/containers/map/needEnterpriseLicense.tsx#L24)):*
> ```XML
>             <h1 className="need-license-blurb__header">Get a Clearer View of Your Cluster</h1>
>             <p className="need-license-blurb__text">
>               The Node Map shows your nodes on a map, grouped by locality.
> ```

Now that I read this again is seems kind of weird: "the node map shows your nodes on a map".  Looks like you've still got a TODO item to review the copy, that's one thing I'd look at in particular.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23852)*

**Comment by vilterp** [comment]
Agreed; will come up with something better.

**Pull request merged**
