### PR TITLE
opt: refactor custom_funcs to make reusable functions easier to find

### PR DESCRIPTION
**Pull request by DrewKimball**
Previously, most custom functions for normalization rules were held
in the custom_funcs file, which meant it had >2000 lines of code. This
made it difficult to find functions for reuse.

This patch moves functions which are only or nearly only used in a single
normalization rule to the file corresponding to that rule. General-purpose
functions which are likely to be reused are left in custom_funcs, which
has been renamed to general_funcs. The hope is that this refactoring will
make reusable functions easier to find.

To make backports easier, these changes will be backported to previous
releases.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
:lgtm: Very nice, thanks for doing this! (and especially for committing to backport!)

Would be good to document the file naming in a `norm/README.md` file. Mainly that there is a 1-1-1 correspondence between .opt files, _func.go files, and testdata files; and that functions used by more than one .opt file are in general_rules

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49151#-:-M7TWlR71RoqAiLcho7i:b-h20798)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by andy-kimball** [comment]
I bors'd this since it's so difficult to rebase it, so best to get it in as soon as possible. But if there are other review comments, don't hesitate to add them; Drew can do a follow-on PR to incorporate them.

**Comment by mgartner** [comment]
@DrewKimball This is amazing! A Herculean task. Thank you!

**Pull request merged**
