### PR TITLE
rowexec: zero out mem/disk alloc in stats if DeterministicStats is set

### PR DESCRIPTION
**Pull request by Azhng**
Follow up to #46316

Release justification: bug fixes and low-risk updates to new functionality.
Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
nit: I would change release category to "non-production code changes" since this behavior will occur only in tests.

Also, for the sake of completeness, we probably should zero out number of "bytes read" statistic by `tableReader` and memory and disk usage in `routerBase`. The latter will require a little bit of plumbing.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46656#-:-M3OWKYl45arr-6sjetu:bto2k7p)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by asubiotto — COMMENTED** [review]
I'm missing a bit of context on this one. Why do we want to do this? (this explanation should be in your commit message)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46656#-:-M3RdL1U0gN50Wy0yOtu:bva6udx)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
I believe that having this zeroing out of variable stats was the original intention behind `DeterministicStats` flag in order to have "stable" `EXPLAIN ANALYZE` plans in tests. In my opinion, it is a "bug fix" to testing contract.

**Comment by asubiotto** [comment]
The intention behind it was not zeroing out all stats, only to zero out stats that didn't have deterministic output between runs on the same sha (mostly stall times, execution times etc...). I think memory use is something we want to keep non-zeroed as that tests that we do collect some memory stats. That shouldn't change from run to run.

**Comment by Azhng** [comment]
I think we already zero out the disk/mem alloc in the colexec, do we want to revert that and keep the rowexec as is ?

**Comment by asubiotto** [comment]
I think that's my vote: not zeroing out mem/disk stats when `DeterministicStats` is true but not displaying labels when `mem/disk` stats are zero.

**Comment by Azhng** [comment]
Closing this PR since we have decided offline this should be the expected behaviour for rowexec

**Pull request closed without merging**
