### PR TITLE
sqlproxyccl/acl: fix the TestParsingErrorHandling flake

### LINKED ISSUE #98838: ccl/sqlproxyccl/acl: TestParsingErrorHandling failed
ccl/sqlproxyccl/acl.TestParsingErrorHandling [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/9113225?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/9113225?buildTab=artifacts#/) on master @ [11fbbca584e3bd774ebee3ee94c49ca30a096b26](https://github.com/cockroachdb/cockroach/commits/11fbbca584e3bd774ebee3ee94c49ca30a096b26):

```
=== RUN   TestParsingErrorHandling
--- FAIL: TestParsingErrorHandling (0.82s)
=== RUN   TestParsingErrorHandling/error_after_update
E230317 06:40:49.045938 115 ccl/sqlproxyccl/acl/file.go:71  [-] 13  error updating access control list from file /artifacts/tmp/_tmp/72c09b96526627cf742479f65b1af982/TestParsingErrorHandling3321990234/001/error_file.idk modified at 2023-03-17 06:40:49.042765008 +0000 UTC: yaml: unmarshal errors:
E230317 06:40:49.045938 115 ccl/sqlproxyccl/acl/file.go:71  [-] 13 +  line 1: cannot unmarshal !!str ``not yaml`` into acl.AllowlistFile
    file_test.go:499: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl/acl/file_test.go:499
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 0
        	Test:       	TestParsingErrorHandling/error_after_update
E230317 06:40:49.863088 117 ccl/sqlproxyccl/acl/file.go:71  [-] 14  error updating access control list from file /artifacts/tmp/_tmp/72c09b96526627cf742479f65b1af982/TestParsingErrorHandling3321990234/001/allowlist.yaml modified at 2023-03-17 06:40:49.042765008 +0000 UTC: yaml: unmarshal errors:
E230317 06:40:49.863088 117 ccl/sqlproxyccl/acl/file.go:71  [-] 14 +  line 1: cannot unmarshal !!str ``no long...`` into acl.AllowlistFile
E230317 06:40:49.863232 117 ccl/sqlproxyccl/acl/file.go:110  [-] 15  Could not read file /artifacts/tmp/_tmp/72c09b96526627cf742479f65b1af982/TestParsingErrorHandling3321990234/001/allowlist.yaml for *acl.Allowlist: yaml: unmarshal errors:
E230317 06:40:49.863232 117 ccl/sqlproxyccl/acl/file.go:110  [-] 15 +  line 1: cannot unmarshal !!str ``no long...`` into acl.AllowlistFile
E230317 06:40:49.863289 117 ccl/sqlproxyccl/acl/file.go:100  [-] 16  WatchList daemon stopped: context canceled
    --- FAIL: TestParsingErrorHandling/error_after_update (0.20s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-sessions @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestParsingErrorHandling.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-25540

### PR DESCRIPTION
**Pull request by pjtatlow**
This is attempt number two to fix this test flake. This time, rather
than waiting a fixed amount of time before checking the metric, we
check it every 100ms until some fixed timeout, currently 10 seconds.
It shouldn't take anywhere near that long, but it allows us to continue
to check until the metric gets updated.

Fixes #98838.

### CODE REVIEW

**Comment by rafiss** [comment]
I'm not too familiar with how the test works or what is being tested, but I will read about it this afternoon to see if I can think of anything.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99385)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pjtatlow)

___
*[`pkg/ccl/sqlproxyccl/acl/file_test.go` line 499 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99385#-NRE7gSB8i-BsHejexjU:-NRE7gSCALNk-68E66GY:b-pvhndm) ([raw file](https://github.com/cockroachdb/cockroach/blob/752de5b313ad72802d13558f0c30a092a3e1939c/pkg/ccl/sqlproxyccl/acl/file_test.go#L499)):*
> ```Go
> 		timeout := time.After(maxWaitTime)
> 	loop:
> 		for {
> ```

this seems like a good use case for `testutils.SucceedsSoon` or `testutils.SucceedsWithin`

**Review by pjtatlow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99385)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/ccl/sqlproxyccl/acl/file_test.go` line 499 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99385#-NRE7gSB8i-BsHejexjU:-NREeh6m4MtzvQzNF5RK:b-k0hx3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/752de5b313ad72802d13558f0c30a092a3e1939c/pkg/ccl/sqlproxyccl/acl/file_test.go#L499)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this seems like a good use case for `testutils.SucceedsSoon` or `testutils.SucceedsWithin`
</blockquote></details>

That's pretty much exactly what I was hoping for haha. Done.

**Review by jeffswenson — APPROVED** [review]
LGTM

**Comment by pjtatlow** [comment]
@rafiss I'm going to merge this because I think that `testutils.SucceedsSoon` will fix the flake, but I'm open to other changes too.

bors r=jeffswenson

**Comment by pjtatlow** [comment]
blathers backport 23.1

**Pull request merged**
