### PR TITLE
opt: normalization rule to remove not null filter

### PR DESCRIPTION
**Pull request by madhavsuresh**
New normalization rule to remove a "IS NOT NULL" filter when
    the column the filter refers to is NOT NULL. For example,
    consider a single column table data, with a as a primary key.
    The query: "SELECT * FROM data WHERE data.a IS NOT NULL"
    need not include the filter node in the logical plan.

    Along with the rule, additional custom functions were required:
    -Determine if a given column has the NotNull property

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/norm/rules/select.opt, line 212 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-LFwpY4G7bCFaqfzMCIB:-LFwpY4G7bCFaqfzMCIC:bct7pel) ([raw file](https://github.com/cockroachdb/cockroach/blob/9123fb42a4b606bae270dd7ad4b59ae772e713fc/pkg/sql/opt/norm/rules/select.opt#L212)):*
> ```
>     $input:*
>     (Filters
>         [ ... (IsNot (Variable $col:*) (Null)) &(IsColNotNull $col $input) ... ]
> ```

I think we can move the `& (IsColNotNull ..)` right after `$col:*`

---

*[pkg/sql/opt/norm/rules/select.opt, line 216 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-LFwpI3QAd2dU7hPVV5U:-LFwpI3R2WMbwJtOHizT:b-2oc4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/9123fb42a4b606bae270dd7ad4b59ae772e713fc/pkg/sql/opt/norm/rules/select.opt#L216)):*
> ```
> )
> =>
> $input
> ```

You are throwing away the entire filter here. If we have `WHERE a=b AND c IS NOT NULL` we still need to keep `a=b`. We will need a custom func to extract the unnecessary conjuncts (see `ExtractBoundConditions` for an example).

---

*[pkg/sql/opt/norm/testdata/rules/select, line 904 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-LFwpst4AAWi2qk1x-OB:-LFwpst4AAWi2qk1x-OC:be63hlb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9123fb42a4b606bae270dd7ad4b59ae772e713fc/pkg/sql/opt/norm/testdata/rules/select#L904)):*
> ```
> # --------------------------------------------------
> opt
> select k from a where k is not null
> ```

[nit[ try to stay consistent with how the rest of the tests are written, we use caps for keywords `SELECT k FROM a WHERE k IS NOT NULL`

---

*[pkg/sql/opt/norm/testdata/rules/select, line 911 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-LFwqCIu9HeJY0uFW17Y:-LFwqCIu9HeJY0uFW17Z:b-zdp3bb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9123fb42a4b606bae270dd7ad4b59ae772e713fc/pkg/sql/opt/norm/testdata/rules/select#L911)):*
> ```
> 
> opt
> select k from a where k is not null and k > 4
> ```

This is broken. I would also add some tests where we have multiple `IS NOT NULL` clauses that we can remove (along with other clauses).

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26982)*

**Comment by rytaft** [comment]
[super nit] Add a period to the last sentence of the first paragraph in the commit message.

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/norm/rules/select.opt, line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-LFwo_kR-F_SWfF67SKX:-LFwo_kR-F_SWfF67SKY:bmc35c8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9123fb42a4b606bae270dd7ad4b59ae772e713fc/pkg/sql/opt/norm/rules/select.opt#L206)):*
> ```
> )
> 
> # RemoveNotNullPredicateOnNotNullColumns removes a filter with an IS NOT NULL condition
> ```

RemoveNotNullPredicateOnNotNullColumns -> RemoveNotNullOnNotNullCol

(I'd change the rule name to be singular, since this rule is only updating the NOT NULL filter for a single column at a time)

---

*[pkg/sql/opt/norm/rules/select.opt, line 216 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-LFwpI3QAd2dU7hPVV5U:-LFwqYz886S4gAwwVv9W:bqi2vzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9123fb42a4b606bae270dd7ad4b59ae772e713fc/pkg/sql/opt/norm/rules/select.opt#L216)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

You are throwing away the entire filter here. If we have `WHERE a=b AND c IS NOT NULL` we still need to keep `a=b`. We will need a custom func to extract the unnecessary conjuncts (see `ExtractBoundConditions` for an example).
</blockquote></details>

I don't think you need a new function - RemoveListItem already does this. Something like:

```
(Select
    $input:*
    (Filters
        $list:[ ... $condition:(IsNot (Variable $col:*) (Null)) & (IsColNotNull $col $input) ... ]
    )
)
=>
(Select
    $input
    (Filters
        (RemoveListItem $list $condition)
    )
)
```

---

*[pkg/sql/opt/norm/testdata/rules/select, line 933 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-LFwq6JWCpYkvtegDl2U:-LFwq6JWCpYkvtegDl2V:b9pi7wu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9123fb42a4b606bae270dd7ad4b59ae772e713fc/pkg/sql/opt/norm/testdata/rules/select#L933)):*
> ```
>  └── key: (1)
> 
> opt
> ```

Add a comment here noting that the rule is *not* applied in this case

---

*[pkg/sql/opt/xfunc/custom_funcs.go, line 263 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-LFwqKvbEmYCRoReZG6Q:-LFwqKvc1wXCyTVzWNiR:bqrpfgv) ([raw file](https://github.com/cockroachdb/cockroach/blob/9123fb42a4b606bae270dd7ad4b59ae772e713fc/pkg/sql/opt/xfunc/custom_funcs.go#L263)):*
> ```Go
> }
> 
> // IsColNotNull returns true if the given column has the NotNull property
> ```

end comment with a period

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-:-LFwmf2r9QDaWzwDkaih:bx5ocih)*

**Comment by andy-kimball** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/norm/rules/select.opt, line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-LFwo_kR-F_SWfF67SKX:-LFwwhS5BLw4YqUSHoBk:bellpm0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9123fb42a4b606bae270dd7ad4b59ae772e713fc/pkg/sql/opt/norm/rules/select.opt#L206)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

RemoveNotNullPredicateOnNotNullColumns -> RemoveNotNullOnNotNullCol

(I'd change the rule name to be singular, since this rule is only updating the NOT NULL filter for a single column at a time)

</blockquote></details>

I'd just go with the simpler `RemoveNotNullCondition`, which fits better with our other naming. The comment is sufficient to describe in what cases that's possible.

---

*[pkg/sql/opt/norm/rules/select.opt, line 212 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-LFwwuBA4Xr3jCJIIivV:-LFwwuBA4Xr3jCJIIivW:be0xidy) ([raw file](https://github.com/cockroachdb/cockroach/blob/9123fb42a4b606bae270dd7ad4b59ae772e713fc/pkg/sql/opt/norm/rules/select.opt#L212)):*
> ```
>     $input:*
>     (Filters
>         [ ... (IsNot (Variable $col:*) (Null)) &(IsColNotNull $col $input) ... ]
> ```

NIT: add space after `&` to follow our style

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26982)*

**Comment by madhavsuresh** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/norm/rules/select.opt, line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-LFwo_kR-F_SWfF67SKX:-LFx2zVi3QOwWszvyh-m:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9123fb42a4b606bae270dd7ad4b59ae772e713fc/pkg/sql/opt/norm/rules/select.opt#L206)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I'd just go with the simpler `RemoveNotNullCondition`, which fits better with our other naming. The comment is sufficient to describe in what cases that's possible.
</blockquote></details>

Done.

---

*[pkg/sql/opt/norm/rules/select.opt, line 212 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-LFwpY4G7bCFaqfzMCIB:-LFx3-nfBavRVcd9mWqj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9123fb42a4b606bae270dd7ad4b59ae772e713fc/pkg/sql/opt/norm/rules/select.opt#L212)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think we can move the `& (IsColNotNull ..)` right after `$col:*`
</blockquote></details>

Done.

---

*[pkg/sql/opt/norm/rules/select.opt, line 216 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-LFwpI3QAd2dU7hPVV5U:-LFx6wNRBVMgLvowDzi_:b2hs3fa) ([raw file](https://github.com/cockroachdb/cockroach/blob/9123fb42a4b606bae270dd7ad4b59ae772e713fc/pkg/sql/opt/norm/rules/select.opt#L216)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I don't think you need a new function - RemoveListItem already does this. Something like:

```
(Select
    $input:*
    (Filters
        $list:[ ... $condition:(IsNot (Variable $col:*) (Null)) & (IsColNotNull $col $input) ... ]
    )
)
=>
(Select
    $input
    (Filters
        (RemoveListItem $list $condition)
    )
)
```
</blockquote></details>

Thanks for catching this. Should be fixed now. RemoveListItem did the trick. 

---

*[pkg/sql/opt/norm/testdata/rules/select, line 904 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-LFwpst4AAWi2qk1x-OB:-LFx32oE0EsAXxr-20nU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9123fb42a4b606bae270dd7ad4b59ae772e713fc/pkg/sql/opt/norm/testdata/rules/select#L904)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit[ try to stay consistent with how the rest of the tests are written, we use caps for keywords `SELECT k FROM a WHERE k IS NOT NULL`
</blockquote></details>

Done.

---

*[pkg/sql/opt/norm/testdata/rules/select, line 911 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-LFwqCIu9HeJY0uFW17Y:-LFx6ixUEKGsMU-MvlTD:b-6mgyb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9123fb42a4b606bae270dd7ad4b59ae772e713fc/pkg/sql/opt/norm/testdata/rules/select#L911)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is broken. I would also add some tests where we have multiple `IS NOT NULL` clauses that we can remove (along with other clauses).
</blockquote></details>

Fixed with the keeping the remaining filter predicates (see above comment)

---

*[pkg/sql/opt/norm/testdata/rules/select, line 933 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-LFwq6JWCpYkvtegDl2U:-LFx33p0Da7rBpBY4LWn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9123fb42a4b606bae270dd7ad4b59ae772e713fc/pkg/sql/opt/norm/testdata/rules/select#L933)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Add a comment here noting that the rule is *not* applied in this case
</blockquote></details>

Done.

---

*[pkg/sql/opt/xfunc/custom_funcs.go, line 263 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-LFwqKvbEmYCRoReZG6Q:-LFx6SEj442l7DOXxS-J:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9123fb42a4b606bae270dd7ad4b59ae772e713fc/pkg/sql/opt/xfunc/custom_funcs.go#L263)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

end comment with a period
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26982)*

**Comment by RaduBerinde** [comment]
Very nice! :lgtm_strong: 

---

Review status: :shipit: complete! 1 of 0 LGTMs obtained

---

*[pkg/sql/opt/norm/testdata/rules/select, line 901 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-LFxA-HV6-HKNRCbjftJ:-LFxA-HV6-HKNRCbjftK:b-jn0391) ([raw file](https://github.com/cockroachdb/cockroach/blob/86c55174b1833806fc9d2c839fac158d2fe34e57/pkg/sql/opt/norm/testdata/rules/select#L901)):*
> ```
> 
> # --------------------------------------------------
> # RemoveNotNullOnNotNullCols
> ```

[nit] RemoveNotNullCondition

---

*[pkg/sql/opt/norm/testdata/rules/select, line 955 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-LFx9usTBTLf8LlSInPX:-LFx9usTBTLf8LlSInPY:b-u120fb) ([raw file](https://github.com/cockroachdb/cockroach/blob/86c55174b1833806fc9d2c839fac158d2fe34e57/pkg/sql/opt/norm/testdata/rules/select#L955)):*
> ```
>  └── fd: (1)-->(4)
> 
> #RemoveNotNullCondition partially applied
> ```

[nit] space after `#`

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-:-LFxAKG_9M92XH_sbNLY:b-il1ii9)*

**Comment by madhavsuresh** [comment]
Review status: :shipit: complete! 1 of 0 LGTMs obtained

---

*[pkg/sql/opt/norm/testdata/rules/select, line 901 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-LFxA-HV6-HKNRCbjftJ:-LFxAqEN7Z2G1rsaPRcJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/86c55174b1833806fc9d2c839fac158d2fe34e57/pkg/sql/opt/norm/testdata/rules/select#L901)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] RemoveNotNullCondition
</blockquote></details>

Done.

---

*[pkg/sql/opt/norm/testdata/rules/select, line 955 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-LFx9usTBTLf8LlSInPX:-LFxAr1REiJLSdhSW0GJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/86c55174b1833806fc9d2c839fac158d2fe34e57/pkg/sql/opt/norm/testdata/rules/select#L955)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] space after `#`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26982)*

**Comment by rytaft** [comment]
:lgtm: Awesome!

---

Review status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/norm/testdata/rules/select, line 981 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-LFxD2gp7hiMoH218qi5:-LFxD2gp7hiMoH218qi6:bc5x667) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3ff85ccecea8dfc829bc3e75de308b5a93d80ca/pkg/sql/opt/norm/testdata/rules/select#L981)):*
> ```
>       └── b.i IS NOT NULL [type=bool, outer=(2), constraints=(/2: (/NULL - ]; tight)]
> 
> #RemoveNotNullCondition rule is not applied
> ```

[nit] space after #

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-:-LFxDER069jCVTpolbbS:bswp6el)*

**Comment by madhavsuresh** [comment]
Review status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/norm/testdata/rules/select, line 981 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-LFxD2gp7hiMoH218qi5:-LFxFQwmDG17osMkS8k-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b16b90fd0a9570e9068999cafe5d2453070f314/pkg/sql/opt/norm/testdata/rules/select#L981)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] space after #
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26982)*

**Comment by rytaft** [comment]
Review status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/norm/testdata/rules/select, line 901 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-LFxA-HV6-HKNRCbjftJ:-LFxFkrH4S20t4a6nDHk:b-a8a6gw) ([raw file](https://github.com/cockroachdb/cockroach/blob/86c55174b1833806fc9d2c839fac158d2fe34e57/pkg/sql/opt/norm/testdata/rules/select#L901)):*
<details><summary><i>Previously, madhavsuresh wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks like you didn't push that change...

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26982)*

**Comment by madhavsuresh** [comment]
*[pkg/sql/opt/norm/testdata/rules/select, line 901 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26982#-LFxA-HV6-HKNRCbjftJ:-LFxHTyiEaUrAQwMfvwm:bu9gah8) ([raw file](https://github.com/cockroachdb/cockroach/blob/86c55174b1833806fc9d2c839fac158d2fe34e57/pkg/sql/opt/norm/testdata/rules/select#L901)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Looks like you didn't push that change...
</blockquote></details>

Done. Thanks for catching this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26982)*

**Pull request merged**
