### PR TITLE
acceptance: allow cluster restarts in localcluster

### PR DESCRIPTION
**Pull request by tbg**
Use that nodes (now) write their gossip address early in the startup
sequence to allow for cluster-wide restarts.

Extend the mixed version harness test slightly to demonstrate that this
works even in a cluster that contains a v1.0 binary (that does *not* write
the gossip address early).

Use `RunLocal` for `TestGossipRestart`, which was previously not possible.

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1, 6 of 6 files at r2, 7 of 7 files at r3, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks pending.

---

*[pkg/acceptance/mixed_version_test.go, line 101 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-Ksjq910BnPb68i2CG3A:-Ksjq911fl5nA5YiN17a:bfgn9dn) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/mixed_version_test.go#L101)):*
> ```Go
> 	var chs []<-chan error
> 	// Restart the nodes asynchronously and in a way that doesn't start the
> 	// first node (at v1.0.5 first) (this is due to technical limitations in
> ```

huh.

what limitations? seems likely that some future test might hit this as well, so extra verbosity seems warranted.

---

*[pkg/acceptance/mixed_version_test.go, line 117 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsjqQmTUpi76wTB-lAV:-KsjqQmTUpi76wTB-lAW:b-68tsgm) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/mixed_version_test.go#L117)):*
> ```Go
> 		t.Fatal(err)
> 	}
> 	var cnt int
> ```

nit: count?

---

*[pkg/acceptance/mixed_version_test.go, line 118 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsjqOMgLDtKNBKyEF2Z:-KsjqOMgLDtKNBKyEF2_:b9ujub6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/mixed_version_test.go#L118)):*
> ```Go
> 	}
> 	var cnt int
> 	if err := db.QueryRow("SELECT COUNT(*) FROM system.settings WHERE name = 'version';").Scan(&cnt); err != nil {
> ```

nit: `COUNT DISTINCT`?

---

*[pkg/acceptance/mixed_version_test.go, line 125 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsjqWKt7Yn5abiWVEui:-KsjqWKt7Yn5abiWVEuj:b9svni4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/mixed_version_test.go#L125)):*
> ```Go
> 	// the version setting should have run.
> 	//
> 	// NB: we could do this check before the restart as well. The new nodes
> ```

why not do that, then?

---

*[pkg/acceptance/localcluster/cluster.go, line 168 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-Ksjqfl6AQq7yqq4hKCA:-Ksjqfl6AQq7yqq4hKCB:babevcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/localcluster/cluster.go#L168)):*
> ```Go
> 		cfg.ExtraArgs = append(append([]string(nil), c.cfg.AllNodeArgs...), cfg.ExtraArgs...)
> 		var node *Node
> 		node, chs[i] = c.makeNode(i, cfg)
> ```

nit: preallocate `c.Nodes = make([]*Node, c.cfg.NumNodes)` next to where you create the slice of channels? then you could `c.Nodes[i], ch[i] = ...` here.

---

*[pkg/acceptance/localcluster/cluster.go, line 235 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsjquoeQlil0FO_cFcL:-KsjquoeQlil0FO_cFcM:b-pgmd8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/localcluster/cluster.go#L235)):*
> ```Go
> 
> func (c *Cluster) makeNode(nodeIdx int, cfg NodeConfig) (*Node, <-chan error) {
> ```

random newline

---

*[pkg/acceptance/localcluster/cluster.go, line 240 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsjqyQ-fFk1O44RZ7Nr:-KsjqyQ-fFk1O44RZ7Ns:b-ta9ckk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/localcluster/cluster.go#L240)):*
> ```Go
> 		Insecure: true,
> 	}
> 	rpcCtx := rpc.NewContext(log.AmbientContext{Tracer: tracing.NewTracer()}, baseCtx,
> ```

hm, is there a reason it's better to have a separate rpc context for each node?

---

*[pkg/acceptance/localcluster/cluster.go, line 504 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsjrOJNficqAHh0pqLi:-KsjrOJNficqAHh0pqLj:b-mkc9vg) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/localcluster/cluster.go#L504)):*
> ```Go
> 
> // Start starts a node.
> func (n *Node) Start(joins ...string) {
> ```

nit: i believe callers of this and StartAsync already have contexts to hand in, might be nice to plumb them while you're here.

---

*[pkg/acceptance/localcluster/cluster.go, line 537 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsjreoQjwo55i-2jGHU:-KsjreoQjwo55i-2jGHV:br9arp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/localcluster/cluster.go#L537)):*
> ```Go
> 	n.setNotRunningLocked()
> 
> 	args := append([]string(nil), n.cfg.ExtraArgs[1:]...)
> ```

might be better to write `args := n.cfg.ExtraArgs[1:len(n.cfg.ExtraArgs):len(n.cfg.ExtraArgs)]` so that appends don't mutate the original

---

*[pkg/acceptance/localcluster/cluster.go, line 637 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsjsJ5LE25VMbsClIzj:-KsjsJ5LE25VMbsClIzk:bz31aem) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/localcluster/cluster.go#L637)):*
> ```Go
> 			_, port, err := net.SplitHostPort(gossipAddr)
> 			if err != nil {
> 				continue
> ```

log, or something? but actually, if gossipAddr is non-empty and this error is non-nil, i think something bad has happened.

---

*[pkg/acceptance/localcluster/cluster.go, line 645 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsjsUidxOaUBYF-kDk7:-KsjsUidxOaUBYF-kDk8:b5bdre7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/localcluster/cluster.go#L645)):*
> ```Go
> 		select {
> 		case <-isServing:
> 			n.Lock()
> ```

what's going on with the locking, here? why not defer the Lock?

---

*[pkg/server/server.go, line 742 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-Ksjow5uWC3tFhofHSm6:-Ksjow5uWC3tFhofHSm7:br0j7y0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e0458b0c21eed44075f823a89920fa1a17b034a/pkg/server/server.go#L742)):*
> ```Go
> 	log.Event(ctx, "started gossip")
> 
> 	statusFiles := [][2]string{
> ```

should this be a map? seems like uniqueness here is a thing

---

*[pkg/server/server.go, line 743 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsjpGokY3BrM37anYhA:-KsjpGokY3BrM37anYhB:br5um2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e0458b0c21eed44075f823a89920fa1a17b034a/pkg/server/server.go#L743)):*
> ```Go
> 
> 	statusFiles := [][2]string{
> 		{".advertise-addr", unresolvedAdvertAddr.String()},
> ```

these addresses are all unresolved, which seems like a bit of a sharp edge, which at the very least deserves some tests that demonstrate the behaviour.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

*[pkg/acceptance/mixed_version_test.go, line 101 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-Ksjq910BnPb68i2CG3A:-KsjtZbDKxj2AQ0HQ7BS:bobrs96) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/mixed_version_test.go#L101)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

huh.

what limitations? seems likely that some future test might hit this as well, so extra verbosity seems warranted.
</blockquote></details>

Added a pointer to `StartAsync`.

---

*[pkg/acceptance/mixed_version_test.go, line 117 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsjqQmTUpi76wTB-lAV:-Ksjto_BbV3o0MAKguG7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/mixed_version_test.go#L117)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: count?
</blockquote></details>

Done.

---

*[pkg/acceptance/mixed_version_test.go, line 118 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsjqOMgLDtKNBKyEF2Z:-Ksjtg6TKowYxMy1iqhf:btx6nkc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/mixed_version_test.go#L118)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: `COUNT DISTINCT`?
</blockquote></details>

There's only one entry, or we're really screwed.

---

*[pkg/acceptance/mixed_version_test.go, line 125 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsjqWKt7Yn5abiWVEui:-KsjtorDzmmHE_ztFL10:b-wpgsl1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/mixed_version_test.go#L125)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why not do that, then?
</blockquote></details>

Expanded comment (want to check the cluster works after restart).

---

*[pkg/acceptance/localcluster/cluster.go, line 168 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-Ksjqfl6AQq7yqq4hKCA:-KsjtrWYkrCVTezTKBee:b-yh0t7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/localcluster/cluster.go#L168)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: preallocate `c.Nodes = make([]*Node, c.cfg.NumNodes)` next to where you create the slice of channels? then you could `c.Nodes[i], ch[i] = ...` here.
</blockquote></details>

No, we can't have a trivial/nil `*Node` in `c.Nodes` because `makeNode` calls various things that looks at all existing nodes.

---

*[pkg/acceptance/localcluster/cluster.go, line 235 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsjquoeQlil0FO_cFcL:-Ksju2taV4j5jGV1N6Mo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/localcluster/cluster.go#L235)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

random newline
</blockquote></details>

Done.

---

*[pkg/acceptance/localcluster/cluster.go, line 240 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsjqyQ-fFk1O44RZ7Nr:-Ksju3PtuyaK8CImS8iA:bc4f8ga) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/localcluster/cluster.go#L240)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

hm, is there a reason it's better to have a separate rpc context for each node?
</blockquote></details>

It's what you expect in an acceptance test. Besides, otherwise we'll have to pass it down from the cluster and so not much is won.

---

*[pkg/acceptance/localcluster/cluster.go, line 504 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsjrOJNficqAHh0pqLi:-KsjuvphKtQeYj5qAihE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/localcluster/cluster.go#L504)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: i believe callers of this and StartAsync already have contexts to hand in, might be nice to plumb them while you're here.
</blockquote></details>

Done.

---

*[pkg/acceptance/localcluster/cluster.go, line 537 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsjreoQjwo55i-2jGHU:-Ksjv3JSdAb3hfC03tw9:bqffmj1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/localcluster/cluster.go#L537)):*
Am I looking a the wrong thing? I'm copying it on this line already.

> args := append([]string(nil), n.cfg.ExtraArgs[1:]...)

---

*[pkg/acceptance/localcluster/cluster.go, line 637 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsjsJ5LE25VMbsClIzj:-KsjvVM1h7AMkIkkWXcE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/localcluster/cluster.go#L637)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

log, or something? but actually, if gossipAddr is non-empty and this error is non-nil, i think something bad has happened.
</blockquote></details>

Done.

---

*[pkg/acceptance/localcluster/cluster.go, line 645 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsjsUidxOaUBYF-kDk7:-KsjvXTwXLCkdjpTEd8n:b-5m4wf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/localcluster/cluster.go#L645)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

what's going on with the locking, here? why not defer the Lock?
</blockquote></details>

I agree that this pattern is unusual, but defer'ing a `Lock()` just looks like someone messed something up. I should just break up the giant `defer n.Unlock()` at the very top.

---

*[pkg/server/server.go, line 742 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-Ksjow5uWC3tFhofHSm6:-KsjvuHfoalqDwCse5fb:bnrtbu1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e0458b0c21eed44075f823a89920fa1a17b034a/pkg/server/server.go#L742)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

should this be a map? seems like uniqueness here is a thing
</blockquote></details>

I don't want to deal with reorderings.

---

*[pkg/server/server.go, line 743 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsjpGokY3BrM37anYhA:-KsjvwoqH47fLuZqm5_O:b-ib1bbu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e0458b0c21eed44075f823a89920fa1a17b034a/pkg/server/server.go#L743)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

these addresses are all unresolved, which seems like a bit of a sharp edge, which at the very least deserves some tests that demonstrate the behaviour.
</blockquote></details>

Which sharp edge? They should be exactly what we print to stdout in the node message below. Agreed that a test wouldn't hurt.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007)*

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/acceptance/localcluster/cluster.go, line 168 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-Ksjqfl6AQq7yqq4hKCA:-Ksjx07ACL97ys4cCzGa:btdsfzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/localcluster/cluster.go#L168)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

No, we can't have a trivial/nil `*Node` in `c.Nodes` because `makeNode` calls various things that looks at all existing nodes.
</blockquote></details>

I see.

---

*[pkg/acceptance/localcluster/cluster.go, line 240 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsjqyQ-fFk1O44RZ7Nr:-Ksjx40yhHEflbAmMWoI:bsiai3k) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/localcluster/cluster.go#L240)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

It's what you expect in an acceptance test. Besides, otherwise we'll have to pass it down from the cluster and so not much is won.
</blockquote></details>

Heh, okay.

---

*[pkg/acceptance/localcluster/cluster.go, line 537 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsjreoQjwo55i-2jGHU:-Ksjx8yUjnUM_uWiKzed:b-85imwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/localcluster/cluster.go#L537)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Am I looking a the wrong thing? I'm copying it on this line already.

> args := append([]string(nil), n.cfg.ExtraArgs[1:]...)
</blockquote></details>

You're looking at the right thing - I'm just saying that copying is not strictly necessary. It's a nit, so ignore it if you don't eat more CI.

---

*[pkg/acceptance/localcluster/cluster.go, line 645 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsjsUidxOaUBYF-kDk7:-KsjxcT2Ublf0FT4tqFn:b2nhktp) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/localcluster/cluster.go#L645)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

I agree that this pattern is unusual, but defer'ing a `Lock()` just looks like someone messed something up. I should just break up the giant `defer n.Unlock()` at the very top.
</blockquote></details>

OK.

---

*[pkg/server/server.go, line 742 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-Ksjow5uWC3tFhofHSm6:-KsjxgEo8N4ubNEDR-bf:b9ye4s5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e0458b0c21eed44075f823a89920fa1a17b034a/pkg/server/server.go#L742)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

I don't want to deal with reorderings.
</blockquote></details>

Wah? Order matters here?

---

*[pkg/server/server.go, line 743 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsjpGokY3BrM37anYhA:-KsjxjeCGgUqYV5wNpzt:b-513os1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e0458b0c21eed44075f823a89920fa1a17b034a/pkg/server/server.go#L743)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Which sharp edge? They should be exactly what we print to stdout in the node message below. Agreed that a test wouldn't hurt.
</blockquote></details>

Are you sure? The unresolved address might have a port of zero, for instance, which I believe is not what goes to stdout. (I can't see the entire file, so if you're certain, OK.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007)*

**Comment by tschottdorf** [comment]
Still pending a test for the first commit.

---

Review status: 7 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/acceptance/localcluster/cluster.go, line 537 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsjreoQjwo55i-2jGHU:-KsjzlTaGsXijFJxSZGS:b-ppyemi) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/localcluster/cluster.go#L537)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

You're looking at the right thing - I'm just saying that copying is not strictly necessary. It's a nit, so ignore it if you don't eat more CI.
</blockquote></details>

Ah, I see. I'll keep this simple. The copy does not matter.

---

*[pkg/acceptance/localcluster/cluster.go, line 645 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsjsUidxOaUBYF-kDk7:-KskBtuxQhlrHm83_DEI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b3dc8c2971ed688f409b86e4f035a46caed8569/pkg/acceptance/localcluster/cluster.go#L645)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

OK.
</blockquote></details>

Done.

---

*[pkg/server/server.go, line 742 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-Ksjow5uWC3tFhofHSm6:-Ksjyeo1UGaTNPb2b6pS:b-y308me) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e0458b0c21eed44075f823a89920fa1a17b034a/pkg/server/server.go#L742)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Wah? Order matters here?
</blockquote></details>

It shouldn't, but I still prefer things happening in a fixed order. If we want to avoid duplicates, a map doesn't help - `./foo` is equal to `foo` etc. I think it's a non-concern (admittedly like my ordering concerns).

---

*[pkg/server/server.go, line 743 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsjpGokY3BrM37anYhA:-Ksjyx1nrsClXcxgzcZ5:bhaxzhl) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e0458b0c21eed44075f823a89920fa1a17b034a/pkg/server/server.go#L743)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Are you sure? The unresolved address might have a port of zero, for instance, which I believe is not what goes to stdout. (I can't see the entire file, so if you're certain, OK.)
</blockquote></details>

Relatively sure (also it wouldn't work otherwise):

```
	unresolvedListenAddr, err := officialAddr(ctx, s.cfg.Addr, ln.Addr(), os.Hostname)
	if err != nil {
		return err
	}
```

We'll know for sure when I add the test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-:-KskC_L0uPSlK3Wi8Wx4:bkhm3so)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-:-KslQ6WOrkBXJrxI1Ild:bnfp4nl)*

**Comment by tamird** [comment]
Yikes! Smells like a bug that deserves investigation. LGTM.

---

Reviewed 11 of 11 files at r7, 7 of 7 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-:-Ksnf2HJSMGkVDldz5PI:b1mw1lz)*

**Comment by tschottdorf** [comment]
Absolutely, I filed https://github.com/cockroachdb/cockroach/issues/18027.

**Comment by bdarnell** [comment]
:lgtm:

The first commit is fine with me, but it could use some commentary about the difference between these address files (always written early) and `--listening-url-file` (optionally written to signal server readiness)

---

Reviewed 4 of 11 files at r7, 6 of 7 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/acceptance/mixed_version_test.go, line 44 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-Ksnv9NNO8Zb6DFJNa35:-Ksnv9NNO8Zb6DFJNa36:bq778be) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0d4ca9d2c5249910773e3f381f97ba99b68fab5/pkg/acceptance/mixed_version_test.go#L44)):*
> ```Go
> 	// I'm not 100% sure why, but the node started first may sometimes not be
> 	// able to connect to Gossip. That node is special in that it gets started
> 	// without join flags, but even though it is passed as a peer to all of the
> ```

What if you use the init command instead of omitting the join flag?

---

*[pkg/server/server.go, line 525 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsnwIviPh9o1dK92IiP:-KsnwIviPh9o1dK92IiQ:bj092s4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0d4ca9d2c5249910773e3f381f97ba99b68fab5/pkg/server/server.go#L525)):*
> ```Go
> func (li listenerInfo) Iter() map[string]string {
> 	return map[string]string{
> 		".advertise-addr": li.advertise,
> ```

Prefix these names with "cockroach" instead of hiding them (If it's important enough to be in a dotfile, it's important enough not to be in a dotfile)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-:-Ksnx1vD-QHPdF9jhV5T:bdctf0r)*

**Comment by tschottdorf** [comment]
TFTRs! Added commentary.

---

Review status: 2 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/acceptance/mixed_version_test.go, line 44 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-Ksnv9NNO8Zb6DFJNa35:-KsoDePPqFNatMdmdx9U:b-2g62s9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0d4ca9d2c5249910773e3f381f97ba99b68fab5/pkg/acceptance/mixed_version_test.go#L44)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

What if you use the init command instead of omitting the join flag?
</blockquote></details>

The problem occurs after restarting the whole cluster, so I don't think changing the init mode can help. If I'm missing something, let's discuss further in #18027.

---

*[pkg/server/server.go, line 525 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-KsnwIviPh9o1dK92IiP:-KsoDpWep8Sj4vIExFwy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0d4ca9d2c5249910773e3f381f97ba99b68fab5/pkg/server/server.go#L525)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Prefix these names with "cockroach" instead of hiding them (If it's important enough to be in a dotfile, it's important enough not to be in a dotfile)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-:-KsoDqHyuLc-gLBd0d32:bidg4eg)*

**Comment by tschottdorf** [comment]
Some more stuff to review, unfortunately.

---

Review status: 2 of 11 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007#-:-KsokxXoUkHOHFnCM9Tt:b-z9j8nn)*

**Comment by tamird** [comment]
Reviewed 9 of 9 files at r10, 7 of 7 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, 1 of 1 files at r14.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18007)*

**Pull request merged**
