### PR TITLE
attempt at refactoring storage/range

### PR DESCRIPTION
**Pull request by tbg**
- raftstorage.go -> range_raftstorage.go
- admin stuff -> range_admin.go
- standard commands (Get, Put, ...) -> range_command.go
- adding, executing, applying commands -> range_execute.go
- leases -> range_lease.go

if that seems like a good idea, i'll move around
a few things according to comments and rebase-merge.

this is all moves, no actual code changes (i may
have added one-liner comments in a place or two).

### CODE REVIEW

**Comment by vivekmenezes** [comment]
Hey is it worth creating a new directory storage/range/ for all range related code?

**Comment by tschottdorf** [comment]
If you're talking about pulling out range into its own package, that would probably be a good thing structurally but would really require major major refactoring of a lot of tests. Just moving it out of the way to another folder isn't really solving anything (plus may not even be possible with Go's package system (?))

**Comment by vivekmenezes** [comment]
I get your point about needing to refactor the tests. So perhaps the right
thing for now is to do what you are doing and move it into different files
for now.

**Comment by tschottdorf** [comment]
as discussed will

- have all the commands and the execute multiplexer in range_commands
- move the "core" stuff into the main file (including leases and the execute and admin file)

**Comment by tschottdorf** [comment]
PTAL. Want to merge this quickly as any rebase means that I might slip in some changes.

**Comment by bdarnell** [comment]
LGTM

**Comment by spencerkimball** [comment]
Keep the triggers and ChangeReplicas stuff in the commands file.

**Pull request merged**
