### PR TITLE
build: speed it up

### PR DESCRIPTION
**Pull request by benesch**
Employ some tricks to speed Make up. Especially noticeable on noop or nearly-noop builds.

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 7 of 8 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[Makefile, line 631 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26187#-LDlFUzo-58uQVcxNCHN:-LDlFUzp9zijYyeWaFPd:b-e62sqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d95b2f99bcf11237a585b74c2321556f93f08f3b/Makefile#L631)):*
> ```Makefile
> 
> $(PROTOC): $(PROTOC_DIR)/Makefile bin/uptodate .ALWAYS_REBUILD | libprotobuf
> 	@uptodate $(PROTOC) $(PROTOBUF_SRC_DIR) \
> ```

This feels like it is duplicating functionality built into `make`. Is it too onerous to recursively list all of the files in `PROTOBUF_SRC_DIR` and add them as a prerequisite? Or perhaps I don't understand what this is doing.

---

*[Makefile, line 395 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26187#-LDlI9D61qoUK8dl73IU:-LDlI9D61qoUK8dl73IV:b-tlb76e) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fcf5f9ce406d5bc4603f6cec40307d3ea336d1d/Makefile#L395)):*
> ```Makefile
> build/defs.mk.sig: sig = $(PATH):$(CURDIR):$(GO):$(GOPATH):$(CC):$(CXX):$(TYPE):$(IGNORE_GOVERS)
> build/defs.mk.sig: .ALWAYS_REBUILD
> 	@echo '$(sig)' | cmp -s - $@ || echo '$(sig)' > $@
> ```

Is this worth it? I don't notice this startup time myself. 

---

*[Makefile, line 769 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26187#-LDlIWHt8GTFgsrQypTM:-LDlIWHt8GTFgsrQypTN:b-sh62he) ([raw file](https://github.com/cockroachdb/cockroach/blob/e336dbe46436c17ec4ac387ef5b2931a87528874/Makefile#L769)):*
> ```Makefile
> # every rebuild.
> $(COCKROACH) build buildoss buildshort go-install: override LINKFLAGS += \
> 	-X "github.com/cockroachdb/cockroach/pkg/build.utcTime=$(shell date -u '+%Y/%m/%d %H:%M:%S')"
> ```

Nice catch. Do we need any of the `-X` lines for test targets?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26187)*

**Comment by jordanlewis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[Makefile, line 631 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26187#-LDlFUzo-58uQVcxNCHN:-LDlyoR86PRuRxfSMomn:bhjwrs) ([raw file](https://github.com/cockroachdb/cockroach/blob/d95b2f99bcf11237a585b74c2321556f93f08f3b/Makefile#L631)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

It's just much, much faster than Make in the noop case:

```
$ time make protoc -j8

real	0m0.614s
user	0m0.395s
sys	0m0.163s

$ time bin/outdated ~/go/native/x86_64-apple-darwin16.7.0/protobuf/protoc c-deps/protobuf

real	0m0.017s
user	0m0.013s
sys	0m0.039s
```

The goal is to implement the stupidest prerequisite tracking possible; as soon as we see just one out-of-date file we hand the reins back to Make and so it can do its fine-grained prerequisite tracking.
</blockquote></details>

I think this is fine. It does make the Makefile a lot less intuitive, though. Please write a little stanza above all of these that explains what @uptodate is and how it's used - that might help future maintainers figure out what's going on and how to update it if necessary.

---

*[Makefile, line 395 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26187#-LDlI9D61qoUK8dl73IU:-LDm-KcP0lJ_0vwzzhHm:b-u052v5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fcf5f9ce406d5bc4603f6cec40307d3ea336d1d/Makefile#L395)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Don't you go out of your way to run `go test` directly instead of `make test`?

But yeah, this is the least defensible change in this PR.
</blockquote></details>

Worth it!

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26187#-:-LDm-geN4O_cqxeR0aeu:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[Makefile, line 631 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26187#-LDlFUzo-58uQVcxNCHN:-LDm2Hmx5CtN3x5vAgQV:bmmvpnt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d95b2f99bcf11237a585b74c2321556f93f08f3b/Makefile#L631)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think this is fine. It does make the Makefile a lot less intuitive, though. Please write a little stanza above all of these that explains what @uptodate is and how it's used - that might help future maintainers figure out what's going on and how to update it if necessary.
</blockquote></details>

Well that's a significant win. I'm surprised `outdated` is so much faster. I thought `make` internally was simply comparing mod times for the target with its dependencies. And your timing comparison wasn't apples-to-apples. My suggestion was to do something like:

```
$(PROTOC): $(list-recursive $(PROTOBUF_SRC_DIR))
```

`list-recursive` would have to be implemented, but I'm imagining something like `find $(PROTOBUF_SRC_DIR) -type f`.

---

*[Makefile, line 395 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26187#-LDlI9D61qoUK8dl73IU:-LDm2BNYERH_Mo8WbOoL:bm3tpog) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fcf5f9ce406d5bc4603f6cec40307d3ea336d1d/Makefile#L395)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Worth it!
</blockquote></details>

Ok, I'm overruled. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26187)*

**Comment by benesch** [comment]
Review status: 3 of 8 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[Makefile, line 631 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26187#-LDlFUzo-58uQVcxNCHN:-LDwkXq47riqoESSoO7g:bc06j86) ([raw file](https://github.com/cockroachdb/cockroach/blob/d95b2f99bcf11237a585b74c2321556f93f08f3b/Makefile#L631)):*
> I thought make internally was simply comparing mod times for the target with its dependencies.

Yes, it is. It's just slower than I am.

Here's a diff that does what you suggest, adding `$(find c-deps/protobuf)`to the prerequisites for libprotobuf and protoc: https://gist.github.com/benesch/aa4b9df4dc5547e40990c9d3d918fd36

It's just as slow:

```
$ time make protoc
Running make with -j8
GOPATH set to /Users/benesch/go
make: Nothing to be done for `protoc'.

real	0m0.674s
user	0m0.572s
sys	0m0.092s
```

For a totally apples-to-apples comparison:

```
$ echo protoc: $(find c-deps/protobuf) ';' > time.mk
$ touch protoc
$ time make -f time.mk
make: `protoc' is up to date.

real	0m0.536s
user	0m0.508s
sys	0m0.026s

$ time bin/uptodate protoc c-deps/protobuf

real	0m0.013s
```

Anyway, I added a big comment that explains all this up above.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26187)*

**Comment by petermattis** [comment]
Review status: 3 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[Makefile, line 631 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26187#-LDlFUzo-58uQVcxNCHN:-LDwztlrDl7DMdwXaRqB:bmdn7rw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d95b2f99bcf11237a585b74c2321556f93f08f3b/Makefile#L631)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

> I thought make internally was simply comparing mod times for the target with its dependencies.

Yes, it is. It's just slower than I am.

Here's a diff that does what you suggest, adding `$(find c-deps/protobuf)`to the prerequisites for libprotobuf and protoc: https://gist.github.com/benesch/aa4b9df4dc5547e40990c9d3d918fd36

It's just as slow:

```
$ time make protoc
Running make with -j8
GOPATH set to /Users/benesch/go
make: Nothing to be done for `protoc'.

real	0m0.674s
user	0m0.572s
sys	0m0.092s
```

For a totally apples-to-apples comparison:

```
$ echo protoc: $(find c-deps/protobuf) ';' > time.mk
$ touch protoc
$ time make -f time.mk
make: `protoc' is up to date.

real	0m0.536s
user	0m0.508s
sys	0m0.026s

$ time bin/uptodate protoc c-deps/protobuf

real	0m0.013s
```

Anyway, I added a big comment that explains all this up above.
</blockquote></details>

Ack. Thanks for the explanation.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26187)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 3 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26187#-:-LDwzwVXBfmHIAnabKKf:bnfp4nl)*

**Comment by benesch** [comment]
Thanks for the reviews!

bors r=petermattis,jordanlewis

**Pull request merged**
