### PR TITLE
sql: ensure spans get anonymized in plan collection

### LINKED ISSUE #34889: sql: sampled query plans do not have attributes anonymized
When talking to @jordanlewis about https://github.com/cockroachdb/cockroach/issues/34426, he made a good point that we shouldn't even be pretty printing key spans to begin with. We started digging and found that they aren't being anonymized correctly.

For instance:

screen shot 2019-02-13 at 8 18 24 pm

@knz @celiala

### PR DESCRIPTION
**Pull request by knz**
Fixes #34889.

Release note (bug fix): The logical plans collected for display in the
web UI now also hide the details of which key ranges are scanned in
table lookups.

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34902)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @celiala, @jordanlewis, and @knz)

___
*[pkg/sql/explain_tree.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34902#-LYg9BaM9mhYimSPmAtx:-LYg9BaM9mhYimSPmAty:b-80pwbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/e513c08d5dfd16c20275e3d28af2e8343d8e09ea/pkg/sql/explain_tree.go#L77)):*
> ```Go
> 		},
> 		spans: func(nodeName, fieldName string, index *sqlbase.IndexDescriptor, spans []roachpb.Span) {
> 			spanss := sqlbase.PrettySpans(index, spans, 2)
> ```

The performance trouble here was that it's expensive to serialize long span strings. It's unfortunate that we're still calling `PrettySpans`, just to check to see whether the output is `-` or not. Can you introduce a function `spans.FullScan` or something that returns a boolean instead?

Now that I look, it's not trivial to write that function, so if you don't feel like it, maybe add a TODO or file an issue.
___
*[pkg/sql/walk.go, line 523 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34902#-LYg8LBv-vHRVLOPgEo1:-LYg8LBv-vHRVLOPgEo2:b2ovxcb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e513c08d5dfd16c20275e3d28af2e8343d8e09ea/pkg/sql/walk.go#L523)):*
> ```Go
> 		if v.observer.attr != nil {
> 			v.observer.attr(name, "from", n.desc.Name)
> 			spans := sqlbase.PrettySpans(&n.desc.PrimaryIndex, n.spans, 2)
> ```

There is also a call to PrettySpans here.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34902)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @celiala and @jordanlewis)

___
*[pkg/sql/explain_tree.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34902#-LYg9BaM9mhYimSPmAtx:-LZ_FgQo1zvWU4skkgo6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e513c08d5dfd16c20275e3d28af2e8343d8e09ea/pkg/sql/explain_tree.go#L77)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

The performance trouble here was that it's expensive to serialize long span strings. It's unfortunate that we're still calling `PrettySpans`, just to check to see whether the output is `-` or not. Can you introduce a function `spans.FullScan` or something that returns a boolean instead?

Now that I look, it's not trivial to write that function, so if you don't feel like it, maybe add a TODO or file an issue.
</blockquote></details>

Done.
___
*[pkg/sql/walk.go, line 523 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34902#-LYg8LBv-vHRVLOPgEo1:-LZ_FtsnAeZkPhnXpuDM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e513c08d5dfd16c20275e3d28af2e8343d8e09ea/pkg/sql/walk.go#L523)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

There is also a call to PrettySpans here.
</blockquote></details>

Done.

**Comment by knz** [comment]
TFYR!

bors r+

**Pull request merged**
