### PR TITLE
go.mod: update goavro from v2.8.1 to v2.9.8

### PR DESCRIPTION
**Pull request by pbardea**
Release note: None

### CODE REVIEW

**Comment by pbardea** [comment]
Hm, interesting. A test is failing because of differing timestamps.

```
1684-10-05T17:51:40.795101Z -> 2269-04-26T17:26:14.504652Z
1690-05-19T13:29:46.145044Z -> 2274-12-08T13:04:19.854595Z
1706-02-05T02:38:08.15195Z -> 2290-08-26T02:12:41.861501Z
```

cc @HonoreDB , does anything jump out to you? This diff does have some changes with respect to timestamps in https://github.com/cockroachdb/vendored/compare/26b10b3041ed0fb4fca39907a91f5010bdc56b81...44b3b8ef8ae985f59604c34b7b4e917ba86ca9e4#diff-550eddbb7dbace83d97dbfb9e67c78aa144f8182e29be6a890050319fc0b848f on line 157. Is it possible that the new version is actually what we want here?

**Comment by HonoreDB** [comment]
> Hm, interesting. A test is failing because of differing timestamps.
> 
> ```
> 1684-10-05T17:51:40.795101Z -> 2269-04-26T17:26:14.504652Z
> 1690-05-19T13:29:46.145044Z -> 2274-12-08T13:04:19.854595Z
> 1706-02-05T02:38:08.15195Z -> 2290-08-26T02:12:41.861501Z
> ```
> 
> cc @HonoreDB , does anything jump out to you? This diff does have some changes with respect to timestamps in [cockroachdb/vendored@26b10b3...44b3b8ediff-550eddbb7dbace83d97dbfb9e67c78aa144f8182e29be6a890050319fc0b848f](https://github.com/cockroachdb/vendored/compare/26b10b3041ed0fb4fca39907a91f5010bdc56b81...44b3b8ef8ae985f59604c34b7b4e917ba86ca9e4diff-550eddbb7dbace83d97dbfb9e67c78aa144f8182e29be6a890050319fc0b848f) on line 157. Is it possible that the new version is actually what we want here?

Yikes, yes. The timestamp actually created in the database for that first row is `2269-04-26 17:26:14.504652`, so I'm guessing the assertions in the test are a result of someone copying the results of an integer overflow bug that is fixed in this update. Good thing you caught this before 2038!

**Comment by pbardea** [comment]
Thanks for confirming! I'll update the tests along with the SDK bump.

**Review by HonoreDB — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59745)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

**Comment by pbardea** [comment]
TFTR!
bors r+

**Pull request merged**
