### PR TITLE
ui: Filter by columns for Hot Ranges page

### LINKED ISSUE #76159: Filter by attributes in hot ranges page
When displaying a table of hot ranges (v1), currently users can sort by column headers. We also want to provide the ability for a user to filter for specific attributes, namely: node, store, database, table, and index

Jira issue: CRDB-13003

Epic CRDB-2323

### PR DESCRIPTION
**Pull request by koorosh**
Current change implements filtering by column
on Hot Ranges page. It allows users to filter
hot ranges by one or many fields to narrow
down results.

In addition, filter parameters are preserved
in URL path so filter params are restored after
page is reloaded.

Release note (ui change): Filtering by column is
added to Hot Ranges page.

Resolves: #76159

Screen Shot 2022-03-31 at 16 06 05

### CODE REVIEW

**Review by Santamaura — COMMENTED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79038)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @Santamaura, and @zachlite)

___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79038#-MzVVsl-9BCYfKkwJK_u):*
I kinda feel like this should be a separate PR as it has nothing todo with the main context of the task this PR resolves. That being said it's a small change so maybe it's ok?
___
*[pkg/ui/workspaces/cluster-ui/src/filter/filterCheckboxOption.tsx, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79038#-MzVWkHm8InsPu_oU1hh:-MzVWkHm8InsPu_oU1hi:b-j2vfrt) ([raw file](https://github.com/cockroachdb/cockroach/blob/91a313ea27a16718df52096521ac709bbd79356b/pkg/ui/workspaces/cluster-ui/src/filter/filterCheckboxOption.tsx#L62)):*
> ```XML
>     menu: provided => ({
>       ...provided,
>       zIndex: 3,
> ```

I'm assuming the dashboard components have a `zIndex` of 2 which is why this is necessary?
___
*[pkg/ui/workspaces/cluster-ui/src/filter/filterDropdown.tsx, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79038#-MzVZCOZ9y0j3WzLlkk5:-MzVZCOZ9y0j3WzLlkk6:b3bf79k) ([raw file](https://github.com/cockroachdb/cockroach/blob/91a313ea27a16718df52096521ac709bbd79356b/pkg/ui/workspaces/cluster-ui/src/filter/filterDropdown.tsx#L30)):*
> ```XML
> export const FilterDropdown = ({
>   className,
>   items,
> ```

I think items is too generic of a name here..maybe `filterComponents` or I see many other places simply use `children`
___
*[pkg/ui/workspaces/db-console/src/views/hotRanges/hotRangesFilter.tsx, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79038#-MzVcyUo6m7pD2IoL7HM:-MzVcyUo6m7pD2IoL7HN:b-wkuqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/91a313ea27a16718df52096521ac709bbd79356b/pkg/ui/workspaces/db-console/src/views/hotRanges/hotRangesFilter.tsx#L42)):*
> ```XML
>   // nodeIdsOptions is a list of uniq node IDs that are available in
>   // provided list of hot ranges.
>   const nodeIdsOptions = Array.from(new Set(hotRanges.map(r => `${r.node_id}`)))
> ```

Should this, `databaseOptions` and `localitiesOptions` be selectors instead so that we don't have all this array manipulation in the component?

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79038)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Santamaura and @zachlite)

___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79038#-MzVVsl-9BCYfKkwJK_u):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

I kinda feel like this should be a separate PR as it has nothing todo with the main context of the task this PR resolves. That being said it's a small change so maybe it's ok?
</blockquote></details>

Agree, will move to separate PR.
___
*[pkg/ui/workspaces/cluster-ui/src/filter/filterCheckboxOption.tsx, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79038#-MzVWkHm8InsPu_oU1hh:-MzWLPD44fwQtZVZLdiH:b-iars4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/91a313ea27a16718df52096521ac709bbd79356b/pkg/ui/workspaces/cluster-ui/src/filter/filterCheckboxOption.tsx#L62)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

I'm assuming the dashboard components have a `zIndex` of 2 which is why this is necessary?
</blockquote></details>

Correct, many `antd` components has `z-index` set to `2`. So that's why I had to specify higher index here.
___
*[pkg/ui/workspaces/cluster-ui/src/filter/filterDropdown.tsx, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79038#-MzVZCOZ9y0j3WzLlkk5:-MzWMsLB4mc0zWaQIXHB:bcg43nd) ([raw file](https://github.com/cockroachdb/cockroach/blob/91a313ea27a16718df52096521ac709bbd79356b/pkg/ui/workspaces/cluster-ui/src/filter/filterDropdown.tsx#L30)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

I think items is too generic of a name here..maybe `filterComponents` or I see many other places simply use `children`
</blockquote></details>

Agree, `children` props is a way better! Thanks! Will change.
___
*[pkg/ui/workspaces/db-console/src/views/hotRanges/hotRangesFilter.tsx, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79038#-MzVcyUo6m7pD2IoL7HM:-MzWPkQq6ImZKwg1YZXt:b20a7nm) ([raw file](https://github.com/cockroachdb/cockroach/blob/91a313ea27a16718df52096521ac709bbd79356b/pkg/ui/workspaces/db-console/src/views/hotRanges/hotRangesFilter.tsx#L42)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

Should this, `databaseOptions` and `localitiesOptions` be selectors instead so that we don't have all this array manipulation in the component?
</blockquote></details>

Makes sense! Will do.

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79038)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Santamaura and @zachlite)

___
*[pkg/ui/workspaces/db-console/src/views/hotRanges/hotRangesFilter.tsx, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79038#-MzVcyUo6m7pD2IoL7HM:-MzZN4hf4-9nyUeWgNJ1:b-s1vpds) ([raw file](https://github.com/cockroachdb/cockroach/blob/91a313ea27a16718df52096521ac709bbd79356b/pkg/ui/workspaces/db-console/src/views/hotRanges/hotRangesFilter.tsx#L42)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Makes sense! Will do.
</blockquote></details>

Just realized that using selectors doesn't work here because all of these data depend on component's props. Instead of this, `useMemo` can be used to effectively cache this computation that's based on local data.

**Review by zachlite — COMMENTED** [review]
looks great!

> Reviewed 5 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79038#-:-MzzCA5G4_f1lpLkpT7G:b6lqmcl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @Santamaura, and @zachlite)

___
*[pkg/ui/workspaces/cluster-ui/src/filter/filterCheckboxOption.tsx, line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79038#-MzzCKd6680xUJnSWo-M:-MzzCKd6680xUJnSWo-N:b-cqby9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/cefc0004de59a381d4ea1c1f60da418053ca24ac/pkg/ui/workspaces/cluster-ui/src/filter/filterCheckboxOption.tsx#L45)):*
> ```XML
>       ...provided,
>       backgroundColor: state.isSelected ? "#DEEBFF" : provided.backgroundColor,
>       color: "#394455",
> ```

Nit - are these brand colors?  In db console, do we have an easy way to specify these as global constants and import them from somewhere?

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79038)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Santamaura and @zachlite)

___
*[pkg/ui/workspaces/cluster-ui/src/filter/filterCheckboxOption.tsx, line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79038#-MzzCKd6680xUJnSWo-M:-MzzGrzq0Yk_eRdsGpvE:b-2i7gpm) ([raw file](https://github.com/cockroachdb/cockroach/blob/cefc0004de59a381d4ea1c1f60da418053ca24ac/pkg/ui/workspaces/cluster-ui/src/filter/filterCheckboxOption.tsx#L45)):*
<details><summary><i>Previously, zachlite wrote…</i></summary><blockquote>

Nit - are these brand colors?  In db console, do we have an easy way to specify these as global constants and import them from somewhere?
</blockquote></details>

We don't have an easy way to consume brand colors, that are defined in SCSS files and cannot be referenced in JS files.

**Review by Santamaura — APPROVED** [review]
I think it :lgtm: :shipit: 

> Reviewed 1 of 1 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79038#-:-N--IUfi4E0wnIyntrr7:b-p6h6ea)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @zachlite)

**Pull request merged**
