### PR TITLE
release-20.1: storage: backport encrypted FS fixes

### PR DESCRIPTION
**Pull request by jbowens**
Backport of #47987 and #48151

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm: though let's hold off on merging until 20.1.0 is out the door.

PS Are you aware of the `backport` tool?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47995#-:-M5dN0KSAPasbqAEPRXo:b-uwgja2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

**Comment by petermattis** [comment]
@jbowens Can you add on a commit which backports #48151? That PR depends on this one for a clean backport.

**Comment by jbowens** [comment]
@petermattis for sure, added 8946f9d

**Comment by petermattis** [comment]
> @petermattis for sure, added 8946f9d

Thanks. LGTM.

**Comment by jbowens** [comment]
@petermattis just double checking, this and #48018 are good to merge now?

**Comment by petermattis** [comment]
> @petermattis just double checking, this and #48018 are good to merge now?

Yes.

**Pull request merged**
