### PR TITLE
opt: allow IN subquery to be converted to lookup join

### LINKED ISSUE #43198: opt: tuple IN (subquery) cannot be converted to lookup semi-join
See example below. Best plan is a lookup join, but we don't get that with the semi-join. The reason is that each side is projecting a tuple, and we are constraining those to be equal. A rule that detects this projection and converts to multiple equalities should fix this.

```
exec-ddl
CREATE TABLE ab (
  a INT,
  b INT,
  PRIMARY KEY (a,b)
)
----


exec-ddl
CREATE TABLE cd (
  c INT,
  d INT
)
----

exec-ddl
ALTER TABLE cd INJECT STATISTICS '[
    {
        "columns": [ "c" ],
        "created_at": "2019-12-13 16:17:43.033228+00:00",
        "distinct_count": 4,
        "row_count": 4
    }
]'
----

opt
SELECT * FROM ab, cd WHERE a=c AND b=d
----
inner-join (lookup ab)
 ├── columns: a:1(int!null) b:2(int!null) c:3(int!null) d:4(int!null)
 ├── key columns: [3 4] = [1 2]
 ├── lookup columns are key
 ├── fd: (1)==(3), (3)==(1), (2)==(4), (4)==(2)
 ├── scan cd
 │    └── columns: c:3(int) d:4(int)
 └── filters (true)

opt
SELECT * FROM ab WHERE (a, b) IN (SELECT c, d FROM cd)
----
project
 ├── columns: a:1(int!null) b:2(int!null)
 ├── key: (1,2)
 └── semi-join (hash)
      ├── columns: a:1(int!null) b:2(int!null) column7:7(tuple{int, int})
      ├── key: (1,2)
      ├── fd: (1,2)-->(7)
      ├── project
      │    ├── columns: column7:7(tuple{int, int}) a:1(int!null) b:2(int!null)
      │    ├── key: (1,2)
      │    ├── fd: (1,2)-->(7)
      │    ├── scan ab
      │    │    ├── columns: a:1(int!null) b:2(int!null)
      │    │    └── key: (1,2)
      │    └── projections
      │         └── (a, b) [type=tuple{int, int}, outer=(1,2)]
      ├── project
      │    ├── columns: column6:6(tuple{int, int})
      │    ├── scan cd
      │    │    └── columns: c:3(int) d:4(int)
      │    └── projections
      │         └── (c, d) [type=tuple{int, int}, outer=(3,4)]
      └── filters
           └── column7 = column6 [type=bool, outer=(6,7), constraints=(/6: (/NULL - ]; /7: (/NULL - ]), fd=(6)==(7), (7)==(6)]
```

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: add opttester facility to test placeholder assignment

We like to assume that the result of building a memo with placeholders
followed by AssignPlaceholders is equivalent to building the query
with the values directly. This is not necessarily the case - it is
possible that some normalization rules act on a higher part of the
tree in a way that would not happen if we had fully normalized a lower
part of the tree.

This commit adds two new opttester directives:
`assign-placeholders-norm` and `assign-placeholders-opt`. These take a
query that has placeholders and simulates the prepared query planning
path.

We use these facilities to add some tests that reproduce a customer
issue.

Release note: None

#### opt: allow IN subquery to be converted to lookup join

This change adds a rule that handles a case which prevents Exists
subqueries from becoming lookup joins.

Fixes #43198.

Release note (performance improvement): certain queries containing
`<tuple> IN (<subquery>)` conditions may run significantly faster.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63780#-:-MYenU8XDdiFueLUkR6e:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @mgartner, and @RaduBerinde)

___
*[pkg/sql/opt/norm/scalar_funcs.go, line 322 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63780#-MYekYmYDveV6iG6gupi:-MYekYmYDveV6iG6gupj:b-q6oup0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a0130820f118b345b92550f34739a37987314ab/pkg/sql/opt/norm/scalar_funcs.go#L322)):*
> ```Go
> // SplitTupleEq splits an equality condition between two tuples into multiple
> // equalities, one for each tuple column.
> func (c *CustomFuncs) SplitTupleEq(tuple, rhs *memo.TupleExpr) memo.FiltersExpr {
> ```

nit: why not make these names parallel? e.g., left, right or lhs, rhs
___
*[pkg/sql/opt/norm/rules/scalar.opt, line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63780#-MYekvfqDLdt-WwAtFnZ:-MYekvfr5yRS0BLFlgXw:b-wgb86h) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a0130820f118b345b92550f34739a37987314ab/pkg/sql/opt/norm/rules/scalar.opt#L133)):*
> ```
> # projected.
> #
> # We are specifically handling the case when this is under an Exist because
> ```

nit: Exist -> Exists?
___
*[pkg/sql/opt/norm/testdata/rules/assign_placeholders, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63780#-MYemDuDD3mPuSSGrJWO:-MYemDuEBqdrhmt5-bYn:b-6q1fi8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a0130820f118b345b92550f34739a37987314ab/pkg/sql/opt/norm/testdata/rules/assign_placeholders#L45)):*
> ```
> 
> # This is what we ideally want to obtain after assigning placeholders in the
> # test below.
> ```

Do you also want to show the `opt` version to be sure that we build a constrained scan? (if we don't build one, maybe open an issue? Doesn't need to block this PR)

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r1, 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63780#-:-MYer2Eo0obeCOkUobrF:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andy-kimball and @RaduBerinde)

___
*[pkg/sql/opt/norm/rules/scalar.opt, line 137 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63780#-MYeq8yr6oW6qje13gOm:-MYeq8yr6oW6qje13gOn:b-dbr5fu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a0130820f118b345b92550f34739a37987314ab/pkg/sql/opt/norm/rules/scalar.opt#L137)):*
> ```
> # this case because it is produced for an IN subquery:
> #
> #   SELECT * FROM ab WHERE (a, b) IN (SELECT c, d FROM cd)
> ```

nit: explain that this rule allows a lookup join to be planned for a query like this.
___
*[pkg/sql/opt/norm/testdata/rules/assign_placeholders, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63780#-MYen0bF4cVMWo1VccDM:-MYen0bF4cVMWo1VccDN:buevm6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/815abe2c74bc3cce3fc5e600ed0705b61826ae82/pkg/sql/opt/norm/testdata/rules/assign_placeholders#L101)):*
> ```
>            └── column9:9 = column8:8 [outer=(8,9), immutable, constraints=(/8: (/NULL - ]; /9: (/NULL - ]), fd=(8)==(9), (9)==(8)]
> 
> # TODO(radu): tHe end result involves a full table scan.
> ```

nit: "tHe" => "The"
___
*[pkg/sql/opt/norm/testdata/rules/scalar, line 560 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63780#-MYeqppg8iSZT6qisRFT:-MYeqppg8iSZT6qisRFU:b-bblvw6) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a0130820f118b345b92550f34739a37987314ab/pkg/sql/opt/norm/testdata/rules/scalar#L560)):*
> ```
>       └── y:8 = b:2 [outer=(2,8), constraints=(/2: (/NULL - ]; /8: (/NULL - ]), fd=(2)==(8), (8)==(2)]
> 
> # Make sure we check that the left-hand side is the right tuple; the result
> ```

nit: "right" => "correct" to avoid confusion with "right-hand side"
___
*[pkg/sql/opt/testutils/opttester/memo_groups.go, line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63780#-MYenGCiBQAny6AmI_ey:-MYenGCiBQAny6AmI_ez:bsatloo) ([raw file](https://github.com/cockroachdb/cockroach/blob/815abe2c74bc3cce3fc5e600ed0705b61826ae82/pkg/sql/opt/testutils/opttester/memo_groups.go#L113)):*
> ```Go
> 
> 	// There are various scalars that won't be registered as groups (e.g.
> 	// singletons). Ignore them (rather than panicing in firstInGroup).
> ```

nit: "panicing" => "panicking"
___
*[pkg/sql/opt/testutils/opttester/opt_tester.go, line 286 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63780#-MYeo1r9Dmkm8h94Pqap:-MYeo1r9Dmkm8h94Pqaq:b-7sqyvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/815abe2c74bc3cce3fc5e600ed0705b61826ae82/pkg/sql/opt/testutils/opttester/opt_tester.go#L286)):*
> ```Go
> //
> //    Builds a query that has placeholders (with normalization enabled), then
> //    assigns placeholders to the given query arguments.
> ```

nit: make it clear that normalization rules run again after placeholders have been assigned.

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63780#-:-MYf30wSB3yHdw_sVznj:bz5mair)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andy-kimball and @rytaft)

___
*[pkg/sql/opt/norm/testdata/rules/assign_placeholders, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63780#-MYemDuDD3mPuSSGrJWO:-MYf224q1Gt_2AV-x0js:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a0130820f118b345b92550f34739a37987314ab/pkg/sql/opt/norm/testdata/rules/assign_placeholders#L45)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Do you also want to show the `opt` version to be sure that we build a constrained scan? (if we don't build one, maybe open an issue? Doesn't need to block this PR)
</blockquote></details>

Done.

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 7 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63780#-:-MYf7wtm4rAGV4JylAmi:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @rytaft)

**Review by rytaft — APPROVED** [review]
> Reviewed 2 of 7 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63780)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball)

**Pull request merged**
