### PR TITLE
build: make build and tracing able to build cgo-free

### PR DESCRIPTION
**Pull request by dt**
Release note: none.

### CODE REVIEW

**Comment by dt** [comment]
cc @lopezator

**Review by lopezator — COMMENTED** [review]
:lgtm_strong: 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31467#-:-LOxTrIoDwYCYi8uN3AR:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by dt** [comment]
@lopezator I still hit an issue building CGO_ENABLED=0 due to the `strptime` SQL builtin -- I submitted https://github.com/knz/strtime/pull/1 to get that one.

**Review by benesch — APPROVED** [review]

**Pull request merged**
