### PR TITLE
go.mod: bump Pebble to c109764a96e7

### PR DESCRIPTION
**Pull request by jbowens**
Changes:

 * [`c109764a`](https://github.com/cockroachdb/pebble/commit/c109764a) ingest: use StartKey/EndKey pair rather than bounds in ExternalFile
 * [`b55a958a`](https://github.com/cockroachdb/pebble/commit/b55a958a) ingest: expose inclusive bounds for ExternalFile end keys
 * [`729ba624`](https://github.com/cockroachdb/pebble/commit/729ba624) db: add support for checkpointing with remote files
 * [`d4f54566`](https://github.com/cockroachdb/pebble/commit/d4f54566) sstable: better corrupt index entry errors
 * [`fa6da330`](https://github.com/cockroachdb/pebble/commit/fa6da330) db: add virtual backings protection mechanism
 * [`0eccafb7`](https://github.com/cockroachdb/pebble/commit/0eccafb7) wal: adjust FailoverOptions defaults
 * [`34530267`](https://github.com/cockroachdb/pebble/commit/34530267) objstorageprovider: fix atomicfs.Marker leak
 * [`10b079ec`](https://github.com/cockroachdb/pebble/commit/10b079ec) sstable: never apply synthetic suffix in place

Release note: none.
Epic: none.

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120667#-:-NtI51ir5fvi-9lRYHvn:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi)

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120667)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aadityasondhi and @stevendanna)

___
*[`pkg/kv/kvserver/replica_proposal.go` line 671 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120667#-NtJLTsS14gZjHzhd7ht:-NtJLTsS14gZjHzhd7hu:b33bk20) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae99fe4c9459805cdf0c0108f99474a50e526e10/pkg/kv/kvserver/replica_proposal.go#L671)):*
> ```Go
> 			end = storage.EngineKey{Key: sst.Span.EndKey}
> 			endInclusive = false
> 		}
> ```

@stevendanna — mind looking at the changes in this file to accommodate cockroachdb/pebble#3412?

I'm not sure if the `sst.Span.EndKey == nil` case is actually possible here, but it's a part of the `roachpb.Span` documentation so seems prudent to handle it?

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120667)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aadityasondhi and @jbowens)

___
*[`pkg/kv/kvserver/replica_proposal.go` line 671 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120667#-NtJLTsS14gZjHzhd7ht:-NtKp-Iw5FTTiKfZ0XIh:b1la9bw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae99fe4c9459805cdf0c0108f99474a50e526e10/pkg/kv/kvserver/replica_proposal.go#L671)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

@stevendanna — mind looking at the changes in this file to accommodate cockroachdb/pebble#3412?

I'm not sure if the `sst.Span.EndKey == nil` case is actually possible here, but it's a part of the `roachpb.Span` documentation so seems prudent to handle it?
</blockquote></details>

I'd rather turn this case into an error. Inside CRDB, no one should currently be sending us AddSSTable requests with empty end keys.

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120667)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aadityasondhi and @jbowens)

___
*[`pkg/kv/kvserver/replica_proposal.go` line 671 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120667#-NtJLTsS14gZjHzhd7ht:-NtLMx8a6panAbzBkpLO:b-edt11m) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae99fe4c9459805cdf0c0108f99474a50e526e10/pkg/kv/kvserver/replica_proposal.go#L671)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I'd rather turn this case into an error. Inside CRDB, no one should currently be sending us AddSSTable requests with empty end keys.
</blockquote></details>

That said, I think your code here is fine and the error should probably happen before we've allowed it to get this far.  I might consider reversing the condition so that the non-conditional code is the happy path, but it doesn't matter.

**Review by jbowens — COMMENTED** [review]
TFTRs!

bors r=sumeerbhola

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120667#-:-NtMGNXRDxYatXqrhCSD:b-jcaktf)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aadityasondhi and @stevendanna)

___
*[`pkg/kv/kvserver/replica_proposal.go` line 671 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120667#-NtJLTsS14gZjHzhd7ht:-NtMFinf0dx8dfTtA4oy:b-zhdiea) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae99fe4c9459805cdf0c0108f99474a50e526e10/pkg/kv/kvserver/replica_proposal.go#L671)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

That said, I think your code here is fine and the error should probably happen before we've allowed it to get this far.  I might consider reversing the condition so that the non-conditional code is the happy path, but it doesn't matter.
</blockquote></details>

I don't think this can be reversed because `sst.Span.EndKey` may be nil.

**Pull request merged**
