### PR TITLE
cli: make cockroach demo start in insecure mode by default

### PR DESCRIPTION
**Pull request by rohany**
Release note (cli change): This change makes cockroach demo
start in insecure mode by default.

### CODE REVIEW

**Review by knz — APPROVED** [review]
:lgtm: thank you :) @awoods187 will be happy

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46969#-:-M4-a6zP7O0z9oNVJIlD:bodiuav)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by knz — CHANGES_REQUESTED** [review]
oh wait no

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46969#-:-M4-aEiU2x2zNI0sO_a5:b4ucvd6)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by knz** [comment]
this PR should be issued against the `release-20.1` branch not `master`

**Comment by rohany** [comment]
Oh woops, let me update.

**Pull request closed without merging**
