### PR TITLE
schemachanger: tests and rules cleanup

### PR DESCRIPTION
**Pull request by postamar**
This PR is a quality-of-life change which cleans up the declarative schema changer tests and rule definitions without functionally changing much. It's best reviewed commit-by-commit.

### CODE REVIEW

**Comment by postamar** [comment]
This came about because I want to make sense of the index and column dependency rules a bit, and I need this to make sense of the definitions I'm about to change. This in turn is motivated by wanting to express a column's nullability in a constraint element, separate from `scpb.ColumnType`.

**Review by ajwerner — APPROVED** [review]
:lgtm: thank you!

> Reviewed 12 of 12 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, 3 of 3 files at r4, 5 of 5 files at r5, 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85262#-:-N85bLtNBsdlMpLAYobB:bro3093)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by postamar** [comment]
Thanks for the speedy review!

**Pull request merged**
