### PR TITLE
sql: prevent DROP SCHEMA CASCADE from droping types with references

### LINKED ISSUE #59021: sql: DROP SCHEMA CASCADE breaks cross-schema TypeDescriptor references
**Describe the problem**

Currently, CRDB does not support `DROP TYPE CASCADE`, but we don't check for dependencies when the type is being dropped as part of a `DROP SCHEMA CASCADE`. This is problematic when the type is involved in a cross schema reference.

**To Reproduce**

```
demo@127.0.0.1:26257/movr> create schema sc;
CREATE SCHEMA

Time: 31ms total (execution 9ms / network 22ms)

demo@127.0.0.1:26257/movr> create type sc.abc as enum ('a', 'b', 'c');
CREATE TYPE

Time: 8ms total (execution 8ms / network 0ms)

demo@127.0.0.1:26257/movr> create table t(k INT PRIMARY KEY, a sc.abc);
CREATE TABLE

Time: 59ms total (execution 8ms / network 52ms)

demo@127.0.0.1:26257/movr> DROP SCHEMA sc;
ERROR: schema "sc" is not empty and CASCADE was not specified
SQLSTATE: 2BP01
demo@127.0.0.1:26257/movr> DROP SCHEMA sc CASCADE;
DROP SCHEMA

Time: 34ms total (execution 11ms / network 23ms)

demo@127.0.0.1:26257/movr> Insert into t values(1, 'a');
ERROR: type with ID 60 does not exist
SQLSTATE: 42704
```

**Expected behavior**
Similar to `DROP TYPE CASCADE`, the column that uses the enum being dropped should be dropped.

**Additional data / screenshots**
In the short term, when dropping a schema which contains types, we should ascertain that none of the types have cross schema references. If they exist, we should fail the `DROP SCHEMA CASCADE`, until the user manually removes the columns that use that type. 
In the long term, we should really be supporting `DROP TYPE CASCADE` : https://github.com/cockroachdb/cockroach/issues/51480

Related to: https://github.com/cockroachdb/cockroach/issues/51889

### PR DESCRIPTION
**Pull request by ajwerner**
Before this patch, a DROP SCHEMA CASCADE could cause database corruption
by dropping types which were referenced by other tables. This would lead to
bad errors like:

```
ERROR: object already exists: desc 687: type ID 685 in descriptor not found: descriptor not found
SQLSTATE: 42710
```

And doctor errors like:
```
   Table 687: ParentID  50, ParentSchemaID 29, Name 't': type ID 685 in descriptor not found: descriptor not found
```

Fixes #59021.

Release note (bug fix): Fixed a bug where `DROP SCHEMA ... CASCADE` could
result in types which are referenced being dropped.

### CODE REVIEW

**Comment by ajwerner** [comment]
This doesn't quite work for subtle reasons. We need to filter out any dependencies which are already dropped.

**Review by arulajmani — APPROVED** [review]
Change looks good. Maybe I'm missing something here, but if the dependency is already dropped, then wouldn't that mean the reference is removed from the type descriptor as well?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59281#-:-MRfvlzk3LKrpv30LC75:b-ily2aj)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by ajwerner — COMMENTED** [review]
The root of the problem is in https://github.com/cockroachdb/cockroach/blob/a106e2fce003332be39a0a63c5381e2e3d9b12fa/pkg/sql/drop_table.go#L360-L367

It turns out this thing is actually totally bogus. 


```
CREATE SCHEMA sc1;
CREATE SCHEMA sc2;
CREATE TYPE sc2.typ AS ENUM ('a');
CREATE TABLE sc1.tab (k sc2.typ);
DROP SCHEMA sc1 CASCADE;
DROP TYPE sc2.typ;
```

`ERROR: type "typ" has dependent objects: descriptor not found`

:grimacing: 

I'll add another commit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59281#-:-MRgXvLzD-t3TWXlv06x:b-a27ol2)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by ajwerner** [comment]
Okay, added another commit to deal with the drop cascade problem. I removes an optimization that occurs during `DROP DATABASE CASCADE` but I don't think I care. The main reason I don't think I care is that we should optimize it away separately by not writing the descriptors directly during statement execution but rather accumulate them in the descriptor collection and then write them in a batch at the end. The whole idea that we just point update all of the descriptor potentially many times during execution is madness. The optimization there was a half-measure.

**Review by thoszhang — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59281)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/resolver.go, line 407 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59281#-MSEYtnF2KRGkHVuftcR:-MSEYtnF2KRGkHVuftcS:b4fhcig) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae4ddea4b2245264859601cc5c24fa5ca42303a9/pkg/sql/resolver.go#L407)):*
> ```Go
> ) (fullyQualifiedNames []*tree.TableName, _ error) {
> 	for _, id := range ids {
> 		desc, err := p.Descriptors().GetMutableTableVersionByID(ctx, id, p.txn)
> ```

Ideally we'd use `GetImmutableTableByID` with `AvoidCached: true, IncludeDropped: true, IncludeOffline: true` here. It is clunky and I do wonder whether we should just include dropped/offline descriptors by default when resolving by ID, but that's a separate topic.
___
*[pkg/sql/logictest/testdata/logic_test/drop_type, line 369 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59281#-MSEZofZAke6B-JU2j8D:-MSEZofZAke6B-JU2j8E:b-7bcvh2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae4ddea4b2245264859601cc5c24fa5ca42303a9/pkg/sql/logictest/testdata/logic_test/drop_type#L369)):*
> ```
> DROP SCHEMA schema_to_drop CASCADE;
> ```

nit: extra newline
___
*[pkg/sql/logictest/testdata/logic_test/drop_type, line 371 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59281#-MSE_oTI0rzpuK6jLbNe:-MSE_oTI0rzpuK6jLbNf:b-jiycma) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae4ddea4b2245264859601cc5c24fa5ca42303a9/pkg/sql/logictest/testdata/logic_test/drop_type#L371)):*
> ```
> # We also want to test that it's not a problem when dropping tables which are
> # being deleted but show up as a dependency
> ```

Can you clarify this comment to say that we're testing that `DROP SCHEMA CASCADE` correctly removes backreferences on types in a different schema?
___
*[pkg/sql/logictest/testdata/logic_test/drop_type, line 385 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59281#-MSE_rSE2r8BYxBlqlw-:-MSE_rSE2r8BYxBlqlw0:b-9m86dk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae4ddea4b2245264859601cc5c24fa5ca42303a9/pkg/sql/logictest/testdata/logic_test/drop_type#L385)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> statement ok
> DROP TABLE t;
> statement ok
> DROP SCHEMA schema_to_drop CASCADE;
> ```
</details>


Don't you want these to go with the previous set of statements?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59281)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/sql/resolver.go, line 407 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59281#-MSEYtnF2KRGkHVuftcR:-MSRRGiX96ql7qJacKqI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae4ddea4b2245264859601cc5c24fa5ca42303a9/pkg/sql/resolver.go#L407)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Ideally we'd use `GetImmutableTableByID` with `AvoidCached: true, IncludeDropped: true, IncludeOffline: true` here. It is clunky and I do wonder whether we should just include dropped/offline descriptors by default when resolving by ID, but that's a separate topic.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/drop_type, line 371 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59281#-MSE_oTI0rzpuK6jLbNe:-MSRTUmWDswGHhcPl3j4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae4ddea4b2245264859601cc5c24fa5ca42303a9/pkg/sql/logictest/testdata/logic_test/drop_type#L371)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

> ```
> # We also want to test that it's not a problem when dropping tables which are
> # being deleted but show up as a dependency
> ```

Can you clarify this comment to say that we're testing that `DROP SCHEMA CASCADE` correctly removes backreferences on types in a different schema?
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/drop_type, line 385 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59281#-MSE_rSE2r8BYxBlqlw-:-MSRTTAY09MV5jwuUDs-:b-2525ev) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae4ddea4b2245264859601cc5c24fa5ca42303a9/pkg/sql/logictest/testdata/logic_test/drop_type#L385)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

> ```
> statement ok
> DROP TABLE t;
> statement ok
> DROP SCHEMA schema_to_drop CASCADE;
> ```

Don't you want these to go with the previous set of statements?
</blockquote></details>

very much yes

**Review by thoszhang — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59281)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/resolver.go, line 407 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59281#-MSEYtnF2KRGkHVuftcR:-MST8DsFDPCt1b019EGr:b9os9cx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae4ddea4b2245264859601cc5c24fa5ca42303a9/pkg/sql/resolver.go#L407)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Done.
</blockquote></details>

FWIW `Required` doesn't do anything when looking up descriptors by ID. You'll always get an error if it doesn't exist.
___
*[pkg/sql/logictest/testdata/logic_test/drop_type, line 387 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59281#-MST8x868dG4T6VI_B1p:-MST8x868dG4T6VI_B1q:bjwah7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/29b7664ddc52dc224bc374b8dee6efa1f734f019/pkg/sql/logictest/testdata/logic_test/drop_type#L387)):*
> ```
> 
> statement ok
> DROP SCHEMA sc2 CASCADE;
> ```

Does the success of this statement alone indicate that removing the backreferences worked?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59281)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/sql/resolver.go, line 407 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59281#-MSEYtnF2KRGkHVuftcR:-MSTK_gc-lJrTNkegwj3:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae4ddea4b2245264859601cc5c24fa5ca42303a9/pkg/sql/resolver.go#L407)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

FWIW `Required` doesn't do anything when looking up descriptors by ID. You'll always get an error if it doesn't exist.
</blockquote></details>

Removed.
___
*[pkg/sql/logictest/testdata/logic_test/drop_type, line 387 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59281#-MST8x868dG4T6VI_B1p:-MSTK0TCCk7ThLVErkV7:b-9kzgtx) ([raw file](https://github.com/cockroachdb/cockroach/blob/29b7664ddc52dc224bc374b8dee6efa1f734f019/pkg/sql/logictest/testdata/logic_test/drop_type#L387)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Does the success of this statement alone indicate that removing the backreferences worked?
</blockquote></details>

It's actually the the `DROP TYPE sc2.typ` which indicates that removing the backreferences worked. I split it out and added a comment.

**Review by thoszhang — APPROVED** [review]
> Reviewed 3 of 3 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59281)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Pull request merged**
