### PR TITLE
acceptance: avoid runaway loop RunInitCommand

### PR DESCRIPTION
**Pull request by tbg**
The retry loop @bdarnell was nervous about in review of the code that
previously touched this turned out to wreak havoc due to matching the
wrong context error (`Canceled` instead of `DeadlineExceeded`). Make
this code generally safer and also more fun to look at.

### CODE REVIEW

**Comment by tschottdorf** [comment]
Rewritten after I found out what was really going on.

**Comment by tschottdorf** [comment]
Hmm, this also doesn't work because the error matching doesn't ever fire (the returned error is just "exit code 1" and the interesting part just ends up going to stderr directly).

Guess I'll have to rewrite this again.

**Comment by tschottdorf** [comment]
Ok, rewritten again.

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19796#-:-KyELHMsjB_JsPIwS6ql:bnfp4nl)*

**Pull request merged**
