### PR TITLE
changefeedccl: add execution_locality option

### LINKED ISSUE #84969: changefeedccl: support a region allowlist for emitter nodes
Proposed spec: `WITH emit_from_regions='comma,separated,list'` causes the changefeed to only create changefeed aggregator* processes on nodes from those regions. If any range doesn't have a replica in any of the regions, the changefeed fails.

This is a more useful primitive now than it used to be. Combining this with changefeed predicates that are pushed into the optimizer, you can create fully region-pinned changefeeds for efficiency/data domiciling. Combining this with super regions, you can create a "replica region" for each region consisting only of non-voting replicas, and restrict a changefeed to those regions to ensure that changefeeds can't interfere with foreground traffic.

We may want to do a timeboxed investigation of whether this is easy enough to be worth doing (versus implementing smarter versions of those two use cases directly). It looks easy to me, just implement a [Replica Oracle](https://github.com/cockroachdb/cockroach/blob/0050edb74f6c57ac389e7d02e72eadeebcf16f5d/pkg/sql/physicalplan/replicaoracle/oracle.go) that passes a filtered-by-region slice of candidates to a BinPackingOracle.

*Ideally the other changefeed processes would be pinned the same way, but that might be extra complexity for not so much benefit.

 

Jira issue: CRDB-17977

Epic CRDB-21737

### PR DESCRIPTION
**Pull request by dt**
Release note (enterprise change): CREATE CHANGEFEED now accepts an 'execution_locality' option to restrict execution of the changefeed to nodes within the specified locality filter.
Epic: CRDB-21737.
Fixes #84969

### CODE REVIEW

**Review by miretskiy — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99358)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99358#-NRDltWr1JQPUjf6-k1V):*
Can you expand commit message/release note to indicate that this option is *only* applicable
to the placement of changefeed coordinator and aggregators.  In particular, that IF the target
spans reside outside of the execute_locality, that data will be still be read/processed.
Also, would be nice to give an example of create changefeed, to demonstrate how
that filter can be used (and I believe the filter itself is a coma separated list -- so multiple
localities may be set)
___
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 1072 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99358#-NRDlAyg1HMuCahq9sGd:-NRDlAyhAhq4vvrQJrJL:b-5e7jyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/68f86ee28eef7957db4de0204075a45a84aa01fa/pkg/ccl/changefeedccl/changefeed_stmt.go#L1072)):*
> ```Go
> 
> // TODO(dt): remove this copy pasta from backupResumer in favor of a shared func
> // somewhere in pkg/jobs or the job registry.
> ```

Can we do it now?
___
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 1115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99358#-NRDoAAm2mVfG43snoy9:-NRDoAAm2mVfG43snoyA:buwh4md) ([raw file](https://github.com/cockroachdb/cockroach/blob/68f86ee28eef7957db4de0204075a45a84aa01fa/pkg/ccl/changefeedccl/changefeed_stmt.go#L1115)):*
> ```Go
> ) error {
> 	// Execution relocations just get returned so another node can take over.
> 	if jobs.IsLeaseRelocationError(changefeedErr) {
> ```

I think this check needs to happen inside resumeWithRetries method -- because that
one will retry this error.
Perhaps alter changefeedbase.AsTerminalError method to treat this error as non-retryable.

**Review by miretskiy — COMMENTED** [review]
This looks great! Thank you so much for taking this.
Please let us know if you would like somebody to take over this PR to add the test(s), or if you intend on doing them yourself.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99358#-:-NRDoQc79r1g2VCa1HSR:b-y1jtvr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99358)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 1115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99358#-NRDoAAm2mVfG43snoy9:-NRDwjC32b64c_6OUWBk:bjv5vmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/68f86ee28eef7957db4de0204075a45a84aa01fa/pkg/ccl/changefeedccl/changefeed_stmt.go#L1115)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I think this check needs to happen inside resumeWithRetries method -- because that
one will retry this error.
Perhaps alter changefeedbase.AsTerminalError method to treat this error as non-retryable.
</blockquote></details>

But we don't want to retry this error? the whole point of this error is that it isn't really an error _of the job_ but just of this execution; it indicates "lease has been relocated; stop what you're doing here _right now_ since it is now running elsewhere"

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99358)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 1115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99358#-NRDoAAm2mVfG43snoy9:-NRDxS47ETEeGjJf2MZ4:ba5q8wb) ([raw file](https://github.com/cockroachdb/cockroach/blob/68f86ee28eef7957db4de0204075a45a84aa01fa/pkg/ccl/changefeedccl/changefeed_stmt.go#L1115)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

But we don't want to retry this error? the whole point of this error is that it isn't really an error _of the job_ but just of this execution; it indicates "lease has been relocated; stop what you're doing here _right now_ since it is now running elsewhere"
</blockquote></details>

It also isn't terminal _for the job_ -- it just needs to returned to the registry as quickly as possible.

**Comment by miretskiy** [comment]
> But we don't want to retry this error?

right; what I'm saying is that we treat *all* errors, unless otherwise marked, as retryable. And the check needs to happen inside resumeWithRetries

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99358)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 1072 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99358#-NRDlAyg1HMuCahq9sGd:-NRDxg_Q27-R_CnRvwmK:b1vy6hb) ([raw file](https://github.com/cockroachdb/cockroach/blob/68f86ee28eef7957db4de0204075a45a84aa01fa/pkg/ccl/changefeedccl/changefeed_stmt.go#L1072)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Can we do it now?
</blockquote></details>

Need to move some stuff around to get a DSP into registry and there are some dependency edges that made it slightly annoying when I spent 10 seconds trying, that made me think it'd be less backport-friendly if I tried it. I was going to do it for master-only in a follow-up

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99358)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 1115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99358#-NRDoAAm2mVfG43snoy9:-NRDze02EYwZAIIp3k_O:ba2neoz) ([raw file](https://github.com/cockroachdb/cockroach/blob/68f86ee28eef7957db4de0204075a45a84aa01fa/pkg/ccl/changefeedccl/changefeed_stmt.go#L1115)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

It also isn't terminal _for the job_ -- it just needs to returned to the registry as quickly as possible.
</blockquote></details>

I'm still not following: the `maybeRelocate` call in resumeWithRetries isn't in the loop, so it'd just pop right out and then into this check?

**Comment by miretskiy** [comment]
> 

doh... Cool.

**Review by dt — COMMENTED** [review]
Added a test.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99358#-:-NRIlND41BMBu9Dbq525:b-7gclag)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99358#-NRDltWr1JQPUjf6-k1V):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Can you expand commit message/release note to indicate that this option is *only* applicable
to the placement of changefeed coordinator and aggregators.  In particular, that IF the target
spans reside outside of the execute_locality, that data will be still be read/processed.
Also, would be nice to give an example of create changefeed, to demonstrate how
that filter can be used (and I believe the filter itself is a coma separated list -- so multiple
localities may be set)
</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 1115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99358#-NRDoAAm2mVfG43snoy9:-NRIlKCn0cHv87m1jVMv:b-ybtf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/68f86ee28eef7957db4de0204075a45a84aa01fa/pkg/ccl/changefeedccl/changefeed_stmt.go#L1115)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I'm still not following: the `maybeRelocate` call in resumeWithRetries isn't in the loop, so it'd just pop right out and then into this check?
</blockquote></details>

Added some comments.

**Review by miretskiy — APPROVED** [review]

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
