### PR TITLE
cherrypick: log: Fix EntryDecoder to handle multi-line log messages

### LINKED ISSUE #15944: Log entry decoder used by status endpoint doesn't handle multi-line log messages
This causes the logs in the admin UI and all log files included in the output of `cockroach debug zip` to not include anything other than the first line of multi-line log messages.

This means for example, that

```
I170515 22:36:08.791058 247 storage/allocator.go:401  [replicate,n3,s3,r5/3:/Table/{0-11}] rebalance candidates: [
s4, valid:true, con:1.00, ranges:3, details:(diversity=0.00, preferred=0, converge=1.00)]
existing replicas: [
s3, valid:true, con:1.00, ranges:8, details:(diversity=0.00, preferred=0, converge=1.00)
s2, valid:true, con:0.00, ranges:9, details:(diversity=0.00, preferred=0, converge=0.00)
s1, valid:true, con:0.00, ranges:10, details:(diversity=0.00, preferred=0, converge=0.00)]
```

becomes

```
I170515 22:36:08.791058 247 storage/allocator.go:401  [replicate,n3,s3,r5/3:/Table/{0-11}] rebalance candidates: [
```

### PR DESCRIPTION
**Pull request by mberhault**
Fixes #15944

### CODE REVIEW

**Review by a-robinson — COMMENTED** [review]
I did some extra testing of this to see how safe it was, and I don't think we're going to want to include it as is. It was a somewhat artificial test since I was using a log file generated with `--verbosity=5`, but I was able to trigger a `bufio.Scanner: token too long` error, which currently fails the entire log decoding process.

**Comment by mberhault** [comment]
ok, shall I close this and we circle back later to see if we want to pull it in? possible with another PR?

**Comment by a-robinson** [comment]
Well, my testing wasn't the best example, since it breaks the old code too because the large log was all on a single line. Give me a little longer to investigate and decide.

**Comment by a-robinson** [comment]
I have a fix, but it's a little messy to try pulling in on short notice, and I've confirmed that the performance after #15964 is considerably worse than before. I'd close this and punt on cherry-picking it for now.

**Comment by mberhault** [comment]
ok. Feel free to take `1.0.1` off your original PR (#15949). It's fine if you don't, I won't cherrypick without checking first.

**Pull request closed without merging**
