### PR TITLE
storage: CheckSSTConflicts performance fixes

### LINKED ISSUE #88702: storage: severe `CheckSSTConflicts` performance regressions slowing down import retries
[Microbenchmark comparisons](https://docs.google.com/spreadsheets/d/1XW2e2AambrbTIv4Otg6bMHLlISizPk5L7LQNZslo5OE/edit#gid=5) between 22.1 and 22.2 are showing severe performance regressions in `CheckSSTConflicts`. The `overlap=false/prefixSeek=true` cases have an 1800% regression, while the `overlap=false/prefixSeek=false` cases have 60-100% regressions. The former also have 12000% more allocations, which probably has something to do with it.

Upon closer look, there are multiple missing optimizations in `CheckSSTConflicts`. Without those optimizations, a TPC-H import retry with range tombstones enabled fails to succeed if the gc ttl is low, as each `AddSSTable` spends an increasingly longer amount of time (sometimes even over a minute) on the `CheckSSTConflicts` call. This issue covers both the microbenchmark optimizations and the more user-visible import retry wedging issue.

Jira issue: CRDB-19841

Epic CRDB-2624

### PR DESCRIPTION
**Pull request by itsbilal**
storage: Use range key masking in CheckSSTConflicts

This change uses range key masking in case of import
cancellation/restart inside CheckSSTConflicts. This prevents
point keys shadowed by range tombstones from appearing to
CheckSSTConflicts, significantly speeding up its runtime
and allowing import restarts to succeed without getting wedged.

Unblocks https://github.com/cockroachdb/cockroach/pull/87309.

Release note: None.

---

storage: Move no-overlap fast path up in CheckSSTConflicts

This change moves up the fast path in CheckSSTConflicts where we
check for any engine keys within the overlapping SST keys. If no
engine keys are found, we can return from the function immediately.
Previously we'd open a range-key sst iterator before doing this check,
which has a pretty significant construction cost.

Fixes https://github.com/cockroachdb/cockroach/issues/88702.

Release note: None

### CODE REVIEW

**Review by erikgrinaker — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89003)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @jbowens)

___
*[`pkg/storage/sst.go` line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89003#-ND8yEvh8bNBXKEZ-Wk1:-ND8yEvh8bNBXKEZ-Wk2:b-232kwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c21c6a577450535d521fb583e7466b7365ed80d2/pkg/storage/sst.go#L55)):*
> ```Go
> 	disallowShadowing bool,
> 	disallowShadowingBelow hlc.Timestamp,
> 	sstToReqTimestamp hlc.Timestamp,
> ```

nit: maybe call this `rangeKeyMaskingBelow` or something, since `sstToReqTimestamp` doesn't really make sense outside of AddSStable.
___
*[`pkg/storage/sst.go` line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89003#-ND8yNdBEMEuI2_q-phA:-ND8yNdBEMEuI2_q-phB:b-jw4cib) ([raw file](https://github.com/cockroachdb/cockroach/blob/c21c6a577450535d521fb583e7466b7365ed80d2/pkg/storage/sst.go#L137)):*
> ```Go
> 		LowerBound:           leftPeekBound,
> 		UpperBound:           rightPeekBound,
> 		RangeKeyMaskingBelow: sstToReqTimestamp,
> ```

There's an unfortunate wrinkle here. Consider a case where a point key is covered by a range tombstone, and the SST contains a newer version of that point key. `CheckSSTConflicts` then needs to know about that point key in order to correctly update `GCBytesAge` -- the key contribution to `GCBytesAge` starts accumulating from the deletion timestamp of the previous version, and we need to undo this contribution since the key contribution will no longer be GCable (it's prevented by the newer existing key). If we enable range key masking then there's no way for us to handle this.

If the performance gains here are as large as I think they are then that's probably a worthwhile tradeoff, but we can no longer claim that the stats are correct. At the very least we'll need to mark them as estimates, which will incur additional stats computations down the line and also disable many stats-based heuristics. I can't really think of a great solution here.

Btw, if the current tests didn't fail on this then that indicates a gap in our test coverage that we should try to address.
___
*[`pkg/storage/sst.go` line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89003#-ND90-yY1M9MbIcwGAer:-ND90-yY1M9MbIcwGAes:bvo5n6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/43363c10b01265e8f2f9dfb27d520b9d16f5669a/pkg/storage/sst.go#L82)):*
> ```Go
> 		// and end keys. We use a non-prefix iterator for this search, and reopen a
> 		// prefix one if there are engine keys in the span.
> 		nonPrefixIter := reader.NewMVCCIterator(MVCCKeyAndIntentsIterKind, IterOptions{UpperBound: end.Key})
> ```

Does this need to check for range keys too? Otherwise, I think it can bypass conflict checks, e.g. if someone wrote a range tombstone at a higher timestamp than the AddSStable writer.

You can consider using `MVCCIsSpanEmpty()` too, which does the same thing.

**Review by itsbilal — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89003#-:-NDA6q9a6miSSGSB7IHf:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @jbowens)

___
*[`pkg/storage/sst.go` line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89003#-ND8yEvh8bNBXKEZ-Wk1:-NDA2nvQ7MEfhfFGqTkX:blc66rt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c21c6a577450535d521fb583e7466b7365ed80d2/pkg/storage/sst.go#L55)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

nit: maybe call this `rangeKeyMaskingBelow` or something, since `sstToReqTimestamp` doesn't really make sense outside of AddSStable.
</blockquote></details>

I renamed it to sstTimestamp as that's both descriptive and also because it's used as such in the function now.
___
*[`pkg/storage/sst.go` line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89003#-ND8yNdBEMEuI2_q-phA:-NDA28Tp0vY-4JqCnWFj:b-xpxb02) ([raw file](https://github.com/cockroachdb/cockroach/blob/c21c6a577450535d521fb583e7466b7365ed80d2/pkg/storage/sst.go#L137)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

There's an unfortunate wrinkle here. Consider a case where a point key is covered by a range tombstone, and the SST contains a newer version of that point key. `CheckSSTConflicts` then needs to know about that point key in order to correctly update `GCBytesAge` -- the key contribution to `GCBytesAge` starts accumulating from the deletion timestamp of the previous version, and we need to undo this contribution since the key contribution will no longer be GCable (it's prevented by the newer existing key). If we enable range key masking then there's no way for us to handle this.

If the performance gains here are as large as I think they are then that's probably a worthwhile tradeoff, but we can no longer claim that the stats are correct. At the very least we'll need to mark them as estimates, which will incur additional stats computations down the line and also disable many stats-based heuristics. I can't really think of a great solution here.

Btw, if the current tests didn't fail on this then that indicates a gap in our test coverage that we should try to address.
</blockquote></details>

We don't need to flip `ContainsEstimates` for a GCBytesAge mismatch, right? Though I'm not aware of the cost of recomputation so if it makes sense to flip that then we should.

Also the tests aren't failing because we don't pass in sstToReqTimestamp in any of the tests yet. That's easy to fix, but I'd rather not expand this PR to include a more sophisticated testing case yet as I'd rather unblock the roachtest (and with the latest changes it looks like it does unblock it).
___
*[`pkg/storage/sst.go` line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89003#-ND90-yY1M9MbIcwGAer:-NDA2vd-DoUKNbO2PaXV:b-78ostc) ([raw file](https://github.com/cockroachdb/cockroach/blob/43363c10b01265e8f2f9dfb27d520b9d16f5669a/pkg/storage/sst.go#L82)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Does this need to check for range keys too? Otherwise, I think it can bypass conflict checks, e.g. if someone wrote a range tombstone at a higher timestamp than the AddSStable writer.

You can consider using `MVCCIsSpanEmpty()` too, which does the same thing.
</blockquote></details>

Yep it does now, it's something I had forgotten to `git add`. in the commit initially.

**Review by erikgrinaker — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89003)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @jbowens)

___
*[`-- commits` line 35 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89003#-NDRxMVh-n8fdQqSTOKV):*
Very nice.
___
*[`pkg/storage/sst.go` line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89003#-ND8yEvh8bNBXKEZ-Wk1:-NDRy2MnBNlS3g6UlF1l:bysptp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c21c6a577450535d521fb583e7466b7365ed80d2/pkg/storage/sst.go#L55)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I renamed it to sstTimestamp as that's both descriptive and also because it's used as such in the function now.
</blockquote></details>

That's better, thanks. Let's add a quick description to the function comment as well.
___
*[`pkg/storage/sst.go` line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89003#-ND8yNdBEMEuI2_q-phA:-NDRyiHt1PLqytzv4TUs:b-kwf7in) ([raw file](https://github.com/cockroachdb/cockroach/blob/c21c6a577450535d521fb583e7466b7365ed80d2/pkg/storage/sst.go#L137)):*
>We don't need to flip `ContainsEstimates` for a `GCBytesAge` mismatch, right? 

Without `ContainsEstimates`, we expect the stats to be correct and identical to the `ComputeStats` result. Various heuristics rely on this, and the consistency checker will also report errors otherwise. We're planning to expand MVCC stats coverage in tests, e.g. roachtests and kvnemesis, which will then fail on such stats mismatches.

Just to make sure, the performance benefit here for import retries is very significant right?

Considering how we previously didn't even try to compute `GCBytesAge` for `AddSSTable`, and the mismatch in this case is likely to be negligible, I suppose this is a strict improvement over 22.1. For the sake of 22.2 performance stability, let's avoid any ContainsEstimates-related regressions and punt this for now. But let's add an NB about it, and write up an issue to do something about it later (either set ContainsEstimates or actually compute correct stats).

>I'm not aware of the cost of recomputation so if it makes sense to flip that then we should.

It's O(100ms), which will be paid on the next range split/merge or consistency check.

> I'd rather not expand this PR to include a more sophisticated testing case yet as I'd rather unblock the roachtest (and with the latest changes it looks like it does unblock it).

Makes sense, but let's add some tests afterwards.
___
*[`pkg/storage/sst.go` line 726 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89003#-NDS1f5-BNJFE28jLJa-:-NDS1f5-BNJFE28jLJa0:b2uqxbi) ([raw file](https://github.com/cockroachdb/cockroach/blob/84609822790b2ce5585e165df68cb78778fa40e6/pkg/storage/sst.go#L726)):*
> ```Go
> 				// Seeks on the engine are expensive. Try Next()ing if we're very close
> 				// to the sst key (which we might be).
> 				nextsUntilSeek := 5
> ```

nit: consider adding a constant for this.
___
*[`pkg/storage/sst.go` line 729 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89003#-NDS1wKVD2yBQZt74rdd:-NDS1wKVD2yBQZt74rde:b-yb5h42) ([raw file](https://github.com/cockroachdb/cockroach/blob/84609822790b2ce5585e165df68cb78778fa40e6/pkg/storage/sst.go#L729)):*
> ```Go
> 				for extOK && extIter.UnsafeKey().Key.Compare(sstIter.UnsafeKey().Key) < 0 {
> 					extIter.NextKey()
> 					extOK, _ = extIter.Valid()
> ```

Shouldn't we check for errors here?

**Review by itsbilal — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89003#-:-NDTdFTfCoysltBFVuJc:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @jbowens)

___
*[`pkg/storage/sst.go` line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89003#-ND8yEvh8bNBXKEZ-Wk1:-NDTZ2Zh5apANVxB2kGP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c21c6a577450535d521fb583e7466b7365ed80d2/pkg/storage/sst.go#L55)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

That's better, thanks. Let's add a quick description to the function comment as well.
</blockquote></details>

Done.
___
*[`pkg/storage/sst.go` line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89003#-ND8yNdBEMEuI2_q-phA:-NDTa0BbAO4HB3TMAWf3:b67e5tp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c21c6a577450535d521fb583e7466b7365ed80d2/pkg/storage/sst.go#L137)):*
> Without ContainsEstimates, we expect the stats to be correct and identical to the ComputeStats result. Various heuristics rely on this, and the consistency checker will also report errors otherwise.

But this isn't the case in 22.1; we neither flip ConstainsEstimates nor do we see consistency checker errors due to the wrong GCBytesAge?

> Just to make sure, the performance benefit here for import retries is very significant right?

Yes - very. Jackson's `import-cancellation` roachtest actually has a successful import now, instead of the ones that were taking 1+ min per run of `CheckSSTCollisions` and then failing. The try-seek-using-next stuff as well as the range key masking was both necessary to realize that benefit.

Added the comment about the mismatch, and I'll file an issue for the testing and bytes age gap. Thanks!
___
*[`pkg/storage/sst.go` line 726 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89003#-NDS1f5-BNJFE28jLJa-:-NDTaw7u6RqLVda9JKHj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/84609822790b2ce5585e165df68cb78778fa40e6/pkg/storage/sst.go#L726)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

nit: consider adding a constant for this.
</blockquote></details>

Done.
___
*[`pkg/storage/sst.go` line 729 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89003#-NDS1wKVD2yBQZt74rdd:-NDTak-cEyoGn4boG3QF:b9i5ock) ([raw file](https://github.com/cockroachdb/cockroach/blob/84609822790b2ce5585e165df68cb78778fa40e6/pkg/storage/sst.go#L729)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Shouldn't we check for errors here?
</blockquote></details>

We already do; if there's an error, extOK will be false, we'd exit out of the loop and fall down to `extOK, extErr = extIter.Valid()`, exit out of the outer loop, and then go into the error conditional there.

**Review by erikgrinaker — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89003)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @jbowens)

___
*[`pkg/storage/sst.go` line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89003#-ND8yNdBEMEuI2_q-phA:-NDTh89R1Nbi3bdHgrtU:b-me0a0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/c21c6a577450535d521fb583e7466b7365ed80d2/pkg/storage/sst.go#L137)):*
> But this isn't the case in 22.1; we neither flip ConstainsEstimates nor do we see consistency checker errors due to the wrong GCBytesAge?

Yep, it's already the case for 22.1. I expect we see consistency checker errors on 22.1, but these aren't fatal (we only fatal in certain tests where we've explicitly enabled it) -- it'll just recompute stats and go on with its day. Still unfortunate though.
___
*[`pkg/storage/sst.go` line 729 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89003#-NDS1wKVD2yBQZt74rdd:-NDThQUm3i_q4EsIrlWT:b-1ngpxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/84609822790b2ce5585e165df68cb78778fa40e6/pkg/storage/sst.go#L729)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

We already do; if there's an error, extOK will be false, we'd exit out of the loop and fall down to `extOK, extErr = extIter.Valid()`, exit out of the outer loop, and then go into the error conditional there.
</blockquote></details>

Ah, got it, thanks.

**Comment by itsbilal** [comment]
With this fix, the import-cancellation roachtest from #87309 sees imports succeed after a cancel+retry. There's no observed slowdown in import speed as the db gets more populated, unlike what was observed earlier.

Screen Shot 2022-10-03 at 2 09 13 PM

**Comment by erikgrinaker** [comment]
> There's no observed slowdown in import speed as the db gets more populated

Is this with a single cancel + retry at 15:55? Looks like the slope isn't as steep afterwards, but it does recover very quickly. Will play around with the roachtest once this lands. Certainly a dramatic improvement over the existing state, thanks for pulling at this!

**Comment by itsbilal** [comment]
@erikgrinaker Yep, the cancel and retry is around then, all ordered. However each table gets cancelled and retried individually, and most tables are relatively small while one is massive (`lineitem`). So the slope becomes flatter because the smaller, more concurrent imports finish quickly and then the rest of the runtime is just waiting for `lineitem` to finish importing.

**Pull request merged**
