### PR TITLE
cloud,acceptance: remove dependence on .LATEST content 

### PR DESCRIPTION
**Pull request by tamird**
download_binary.sh copied from cockroachlabs/production#391.

### CODE REVIEW

**Comment by cuongdo** [comment]
Thanks for the quick fix.

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/acceptance/terraform/azure/variables.tf, line 77 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15668#-KjF0JTYJfsWNaO_-goL:-KjF0JTYJfsWNaO_-goM:bay1fgp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0349273f7ecc10c5f95acbc2d629f9fd176f27a0/pkg/acceptance/terraform/azure/variables.tf#L77)):*
> ```HCL
> 
> # SHA of the cockroach binary to pull down. If none, the latest is fetched.
> variable "cockroach_sha" {
> ```

Can you reinstate these variables? Being able to specify `cockroach` SHAs has proven useful at least 3 times in the past when performing a `git bisect` for issues that didn't readily reproduce locally.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15668#-:-KjF0G5vWgnco1RyiiYs:b-e69qws)*

**Comment by tamird** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/acceptance/terraform/azure/variables.tf, line 77 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15668#-KjF0JTYJfsWNaO_-goL:-KjF1iKO7xvGN_A9pEBm:b-o0g0jh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0349273f7ecc10c5f95acbc2d629f9fd176f27a0/pkg/acceptance/terraform/azure/variables.tf#L77)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

Can you reinstate these variables? Being able to specify `cockroach` SHAs has proven useful at least 3 times in the past when performing a `git bisect` for issues that didn't readily reproduce locally.
</blockquote></details>

Done, though please have another look at this. My main concern is how the empty SHA variable will be treated - we need the shell to interpret it is as a present empty string, but depending on terraform's interpolation behaviour, it may drop the argument completely.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15668)*

**Comment by cuongdo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[cloud/aws/main.tf, line 67 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15668#-KjF6dwU6reftGdHrl3V:-KjF6dwV1qW4tSuDenlH:b-i2uash) ([raw file](https://github.com/cockroachdb/cockroach/blob/7438e37d0c115ead3ebfdca4f00a052e4b93ff8c/cloud/aws/main.tf#L67)):*
> ```HCL
>       "mkdir -p logs",
>       "chmod 755 cockroach",
>       "[ $(stat --format=%s cockroach) -ne 0 ] || bash download_binary.sh cockroach/cockroach.linux-gnu-amd64 ${var.cockroach_sha} cockroach",
> ```

this doesn't work with an empty SHA, but this does:

```
      "[ $(stat --format=%s cockroach) -ne 0 ] || bash download_binary.sh cockroach/cockroach.linux-gnu-amd64 ${coalesce(var.cockroach_sha, "LATEST")} cockroach",
```

---

*[pkg/acceptance/terraform/azure/variables.tf, line 77 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15668#-KjF0JTYJfsWNaO_-goL:-KjF78tbfzre0FABwu-e:barigj7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0349273f7ecc10c5f95acbc2d629f9fd176f27a0/pkg/acceptance/terraform/azure/variables.tf#L77)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Done, though please have another look at this. My main concern is how the empty SHA variable will be treated - we need the shell to interpret it is as a present empty string, but depending on terraform's interpolation behaviour, it may drop the argument completely.
</blockquote></details>

Yes, you're right. I've verified this. See my other comment for a fix.

---

*[pkg/acceptance/terraform/azure/variables.tf, line 78 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15668#-KjF7HIs4ew40SH1CLqR:-KjF7HIs4ew40SH1CLqS:b-e2sm8e) ([raw file](https://github.com/cockroachdb/cockroach/blob/7438e37d0c115ead3ebfdca4f00a052e4b93ff8c/pkg/acceptance/terraform/azure/variables.tf#L78)):*
> ```HCL
> # SHA of the cockroach binary to pull down. If none, the latest is fetched.
> variable "cockroach_sha" {
>   default = ""
> ```

Set this default to `LATEST`, and the default case works fine. (Remember to update the corresponding comment.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15668)*

**Comment by cuongdo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[cloud/aws/main.tf, line 67 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15668#-KjF6dwU6reftGdHrl3V:-KjF8WRb4zRRd9XY-8U2:bcyjjf3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7438e37d0c115ead3ebfdca4f00a052e4b93ff8c/cloud/aws/main.tf#L67)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

this doesn't work with an empty SHA, but this does:

```
      "[ $(stat --format=%s cockroach) -ne 0 ] || bash download_binary.sh cockroach/cockroach.linux-gnu-amd64 ${coalesce(var.cockroach_sha, "LATEST")} cockroach",
```
</blockquote></details>

actually, disregard this comment... I typed it before finding a simpler solution below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15668)*

**Comment by tamird** [comment]
Review status: 0 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/acceptance/terraform/azure/variables.tf, line 78 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15668#-KjF7HIs4ew40SH1CLqR:-KjF9DLKM--LkjgxxnLF:b4855pb) ([raw file](https://github.com/cockroachdb/cockroach/blob/7438e37d0c115ead3ebfdca4f00a052e4b93ff8c/pkg/acceptance/terraform/azure/variables.tf#L78)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

Set this default to `LATEST`, and the default case works fine. (Remember to update the corresponding comment.)
</blockquote></details>

Thanks! Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15668)*

**Comment by cuongdo** [comment]
:lgtm:

---

Review status: 0 of 11 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15668#-:-KjFC9P8Ovlc7cRvV2BL:bnfp4nl)*

**Pull request merged**
