### PR TITLE
ui: Statement Details page using new details endpoint

### PR DESCRIPTION
**Pull request by maryliag**
Previously, the Statement Details page was being populated
by the value saved on cache, where we would filter the
existing statement and retrieve the correct one.
With a new endpoint `_status/stmtdetails/{fingerprint_id}`
we can collect more information about the statement.
This first commit changes the source of information of
the Statement Details page to the value retrieved from
the new endpoint. No changes are noticeable from the user's
perspective.
Following commits will add the new information based on the
extra information retrieved by the endpoint.

Partially addresses #72129

NoteFor Reviewers: Cluster-ui selector are still being addressed

Release note: None
Release Justification: Low risk, high benefit change

### CODE REVIEW

**Review by Azhng — COMMENTED** [review]
Hmm is it intentional that the db-console sagas is not added in this commit? 

> Reviewed 25 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-:-MxAlt3i3Ox5MrAVWk1w:bdjhcig)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 416 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxAhApE3RLAIfj2jtAK:-MxAhApE3RLAIfj2jtAL:bh1dqln) ([raw file](https://github.com/cockroachdb/cockroach/blob/110fa102b78b8e5cf792fbe37df80923a8fd9680/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L416)):*
> ```XML
>           <Loading
>             loading={_.isNil(
>               this.props.completeStatementDetails?.statement?.key_data?.query,
> ```

would it be sufficient to just check `this.props.completeStatementDetails` is nil here? 
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxAhX35-m7hVV4soT_K:-MxAhX35-m7hVV4soT_L:b-a8c9e0) ([raw file](https://github.com/cockroachdb/cockroach/blob/110fa102b78b8e5cf792fbe37df80923a8fd9680/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L451)):*
> ```XML
>     if (!this.props.completeStatementDetails?.statement) {
>       return null;
>     }
> ```

Hmm, since `renderContent` is wrapped in the `Loading` component, is this check still necessary? 
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 980 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxAi7Ml-DyMd8i4vVPv:-MxAi7Mm0Hn_JztArkDW:bfhnzbb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eb279af465b85badd8e3ddb175f60b922f6992d/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L980)):*
> ```XML
>               />
>             </SummaryCard>
>           )}
> ```

Nice! This is finally gone :D 
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetailsConnected.ts, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxAihcK3205IgXnLc4b:-MxAihcK3205IgXnLc4c:bpgcf0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/110fa102b78b8e5cf792fbe37df80923a8fd9680/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetailsConnected.ts#L54)):*
> ```XML
> // For tenant cases, we don't show information about node, regions and
> // diagnostics.
> const mapStateToProps = (state: AppState, props: RouteComponentProps) => {
> ```

Hmm, what does this change do ?
___
*[pkg/ui/workspaces/db-console/src/redux/apiReducers.ts, line 318 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxAf66m81V1VBGQl4Vq:-MxAf66m81V1VBGQl4Vr:bi3jejx) ([raw file](https://github.com/cockroachdb/cockroach/blob/110fa102b78b8e5cf792fbe37df80923a8fd9680/pkg/ui/workspaces/db-console/src/redux/apiReducers.ts#L318)):*
> ```XML
>   if (
>     appNames &&
>     (appNames.indexOf("$ internal") >= 0 || appNames.indexOf("unset") >= 0)
> ```

nit: `appNames.includes()` might be clearer than `indexOf() >= 0`

**Review by maryliag — COMMENTED** [review]
The sagas on db-console side are used for actions such as reset, create/cancel diagnostic bundle, etc. I didn't added any new action, so no new sagas were required.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-:-MxB9FcW-N9UAOI7xkEs:b-kdxz5x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 416 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxAhApE3RLAIfj2jtAK:-MxBEQ1c-WQa1UiHhObN:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/110fa102b78b8e5cf792fbe37df80923a8fd9680/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L416)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

would it be sufficient to just check `this.props.completeStatementDetails` is nil here? 
</blockquote></details>

Done
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxAhX35-m7hVV4soT_K:-MxBERAz6n4aBi64Nclh:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/110fa102b78b8e5cf792fbe37df80923a8fd9680/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L451)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm, since `renderContent` is wrapped in the `Loading` component, is this check still necessary? 
</blockquote></details>

Done
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 980 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxAi7Ml-DyMd8i4vVPv:-MxBEUqV9M9t3BGMfpKP:b-ve3yvb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eb279af465b85badd8e3ddb175f60b922f6992d/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L980)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Nice! This is finally gone :D 
</blockquote></details>

:smile: 
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetailsConnected.ts, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxAihcK3205IgXnLc4b:-MxBEiK200izVp0-zfD3:b-6c7545) ([raw file](https://github.com/cockroachdb/cockroach/blob/110fa102b78b8e5cf792fbe37df80923a8fd9680/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetailsConnected.ts#L54)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm, what does this change do ?
</blockquote></details>

I'll use things from location and match, so needed to change to route. Nothing from StatementDetailsProps needed here.
___
*[pkg/ui/workspaces/db-console/src/redux/apiReducers.ts, line 318 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxAf66m81V1VBGQl4Vq:-MxBFvi6EJ2USIPP2ReI:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/110fa102b78b8e5cf792fbe37df80923a8fd9680/pkg/ui/workspaces/db-console/src/redux/apiReducers.ts#L318)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: `appNames.includes()` might be clearer than `indexOf() >= 0`
</blockquote></details>

Done

**Review by jocrl — CHANGES_REQUESTED** [review]
🎉

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-:-MxBpLBE5Asm4Phc08i3:b44uc2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @maryliag)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxBcM5UCiZGPTxn-uUj):*
nit: The new endpoint respond is still being saved on the keyed cache, correct? Maybe `s/populated by the value saved on cache/populated by the data for the statements table`, to not give the impression that the cache part is changing.



_Suggestion:_
```
  Previously, the Statement Details page was being populated
  by the value saved on cache,
```
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 144 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxBdukmD1XHEm1LBu31:-MxBdukmD1XHEm1LBu32:b-v4vs4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ad359837ef937eb5188861a2632a47a344c657f/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L144)):*
> ```XML
> 
> export interface StatementDetailsStateProps {
>   completeStatementDetails: CompleteStatementDetails;
> ```

nit: `s/completeStatementDetails/statementDetails`? I feel like `statementDetails` would suffice, in that a single record from the statements table is a `statement` and your endpoint response is a `statementDetails`. Unless there is a difference between a `completeStatementDetails` and a `statementDetails`?



_Code quote:_
```XML
completeStatementDetails
```
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 461 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxBgW302pPezLpojMc3:-MxBgW302pPezLpojMc4:bynm6p4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ad359837ef937eb5188861a2632a47a344c657f/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L461)):*
> ```XML
>     } = this.props.completeStatementDetails.statement.key_data;
> 
>     if (Number(stats.count) == 0) {
> ```

For my understanding, do you know what was the prior use case for this if block and error message? This block used to be for when `this.props.statement` is present and `stats` is absent, but in terms of use cases I don't know when that happens.

I know that previously, if a time range was selected that did not have the statement, this.props.statement` would be absent so we wouldn't even get here.

For adding the time picker it might help to distinguish the two cases to provide appropriate error messages. But I don't currently understand what this block is for 🤔.
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx, line 509 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxBj98t2Em_gxq-wDy9:-MxBj98u4UAIF2vnsZ1B:bjrf2h6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ad359837ef937eb5188861a2632a47a344c657f/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L509)):*
> ```XML
>     const columns = makeStatementsColumns(
>       statements,
>       filters.app.split(","),
> ```

nit: I'm realizing that I'm late since the endpoint is already merged, but I feel like a useful future improvement would be to return the `app_names` as an array. The comma delimitation is very implicit; one generally wouldn't expect to need to split the string, and even then it's unclear what the delimiter is and whether a particular variable with a string type still needs to be split.
___
*[pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTable.tsx, line 240 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxBlKEG4-K2fviglXgd:-MxBlKEG4-K2fviglXge:b-4u5qrq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ad359837ef937eb5188861a2632a47a344c657f/pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTable.tsx#L240)):*
> ```XML
> export function makeStatementFingerprintColumn(
>   statType: StatisticType,
>   selectedApp: string[],
> ```

nit: could these be plural-ized to `s/selectedApp/selectedApps`?



_Code quote:_
```XML
selectedApp: string[],
```

**Review by Azhng — COMMENTED** [review]
Hmm, I think `resetSQLStats`'s sagas on the DB Console side (probably means cluster-ui side also need update :thinking: ) need to be updated to also invalidate the keyed cache reducer storing the statement details. 

> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-:-MxBqPNMCIzRJrM9DzRK:b-ih9wcc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx, line 509 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxBj98t2Em_gxq-wDy9:-MxBqG4-2MOH67bNkP-o:bnhf3kw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ad359837ef937eb5188861a2632a47a344c657f/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L509)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

nit: I'm realizing that I'm late since the endpoint is already merged, but I feel like a useful future improvement would be to return the `app_names` as an array. The comma delimitation is very implicit; one generally wouldn't expect to need to split the string, and even then it's unclear what the delimiter is and whether a particular variable with a string type still needs to be split.
</blockquote></details>

Hmm I think the API has the `app_names` returned as an array, this line looks like is coming from the filter.

**Review by maryliag — COMMENTED** [review]
Invalidation during resetSQLStats added

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-:-MxF5iTe6qsp312HLHwx:b-cy4bc2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @jocrl)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxBcM5UCiZGPTxn-uUj):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

nit: The new endpoint respond is still being saved on the keyed cache, correct? Maybe `s/populated by the value saved on cache/populated by the data for the statements table`, to not give the impression that the cache part is changing.
</blockquote></details>

Done
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 144 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxBdukmD1XHEm1LBu31:-MxF6woLCGwZXCHKyE_o:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ad359837ef937eb5188861a2632a47a344c657f/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L144)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

nit: `s/completeStatementDetails/statementDetails`? I feel like `statementDetails` would suffice, in that a single record from the statements table is a `statement` and your endpoint response is a `statementDetails`. Unless there is a difference between a `completeStatementDetails` and a `statementDetails`?
</blockquote></details>

Done
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 461 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxBgW302pPezLpojMc3:-MxF73tJA1U8zhR2jjOR:b2hpofs) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ad359837ef937eb5188861a2632a47a344c657f/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L461)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

For my understanding, do you know what was the prior use case for this if block and error message? This block used to be for when `this.props.statement` is present and `stats` is absent, but in terms of use cases I don't know when that happens.

I know that previously, if a time range was selected that did not have the statement, this.props.statement` would be absent so we wouldn't even get here.

For adding the time picker it might help to distinguish the two cases to provide appropriate error messages. But I don't currently understand what this block is for 🤔.
</blockquote></details>

Imagine you're on the overview page and you see a statement there, then someone else reset the data for example, just when you're about to click on any of the statements to see the details, which means when the details page opens there isn't a statement anymore, so this place is to handle those cases, and we just show the message of we couldn't find the statement anymore.
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx, line 509 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxBj98t2Em_gxq-wDy9:-MxF7YUhEnKJ7UHiIkco:b7g1tkk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ad359837ef937eb5188861a2632a47a344c657f/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L509)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm I think the API has the `app_names` returned as an array, this line looks like is coming from the filter.
</blockquote></details>

Archer is correct, this line is not about the api, is already existing code that gets the app names from the filter selected. The api uses array :) 
___
*[pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTable.tsx, line 240 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxBlKEG4-K2fviglXgd:-MxF88Lr4Wi8ytqT14Th:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ad359837ef937eb5188861a2632a47a344c657f/pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTable.tsx#L240)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

nit: could these be plural-ized to `s/selectedApp/selectedApps`?
</blockquote></details>

Done

**Review by jocrl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77215)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 461 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxBgW302pPezLpojMc3:-MxFIaN_7tJwZHSAbYNt:b3g49v5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ad359837ef937eb5188861a2632a47a344c657f/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L461)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Imagine you're on the overview page and you see a statement there, then someone else reset the data for example, just when you're about to click on any of the statements to see the details, which means when the details page opens there isn't a statement anymore, so this place is to handle those cases, and we just show the message of we couldn't find the statement anymore.
</blockquote></details>

Hmmm. And that would end up hitting this block, instead of this above block?
```
    if (!this.props.statement) {
      return null;
    }
```
I'm trying to test this on master, but reset sql stats (button or CLI) isn't working for me on the table page for some reason.
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx, line 509 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxBj98t2Em_gxq-wDy9:-MxFMUfzE2cL8whBHOPN:bevfb46) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ad359837ef937eb5188861a2632a47a344c657f/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L509)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Archer is correct, this line is not about the api, is already existing code that gets the app names from the filter selected. The api uses array :) 
</blockquote></details>

Ah, I see, it's [this](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/cluster-ui/src/queryFilter/filter.tsx#L59) and in the code below. That's still unfortunate then, but understandably not in in the scope of this pr.

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77215)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @jocrl)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 461 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxBgW302pPezLpojMc3:-MxFQn0WDFMcpJL095Oo:b-6qg1yl) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ad359837ef937eb5188861a2632a47a344c657f/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L461)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

Hmmm. And that would end up hitting this block, instead of this above block?
```
    if (!this.props.statement) {
      return null;
    }
```
I'm trying to test this on master, but reset sql stats (button or CLI) isn't working for me on the table page for some reason.
</blockquote></details>

I remove the block you're mentioning.

**Comment by jocrl** [comment]
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 461 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxBgW302pPezLpojMc3:-MxFiNGh-q7IAz5j9t1G:bnl6tqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ad359837ef937eb5188861a2632a47a344c657f/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L461)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I remove the block you're mentioning.
</blockquote></details>

Right, I'm aware; my previous comment was referring to old behavior before the changes in this PR. What I'm saying is that there used to be two separate paths, and I had the uncertain impression that the first now-deleted block was what used to be hit in the scenario that you described. And if so, that I don't know when the second block is hit.

Not sure if you know the distinction in prior code behavior?

If not, don't worry and I'll figure this out after fixing reset sql stats.

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77215)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @jocrl)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 461 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxBgW302pPezLpojMc3:-MxFpcoqDIxrlcEWuKui:bxfaru1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ad359837ef937eb5188861a2632a47a344c657f/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L461)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

Right, I'm aware; my previous comment was referring to old behavior before the changes in this PR. What I'm saying is that there used to be two separate paths, and I had the uncertain impression that the first now-deleted block was what used to be hit in the scenario that you described. And if so, that I don't know when the second block is hit.

Not sure if you know the distinction in prior code behavior?

If not, don't worry and I'll figure this out after fixing reset sql stats.
</blockquote></details>

Previously, we would pass a statement on the props to the details page (statement here means the query itself). From that we would search for the exec stats on the cache.
Since we were always passing the query we could display it on the black box, and search for the exec to show below the box.

If the query itself was empty (I can't imagine the scenario, but I imagine it was added because of some bug), the search for the exec would probably break, so that check was added for "if you don't have the value to search, don't even try, go back". Then the second block is "okay, I have the statement, let's show on the box, but look for exec stats" and if that failed we would show the message that the stats were not found.

The difference now is that we don't pass the query itself anymore, just the fingerprint id on the url, so or we will have the query and the exec stats or nothing.

**Comment by jocrl** [comment]
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 461 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxBgW302pPezLpojMc3:-MxFx-v50Jb9hL-WgtsX:b-n2acty) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ad359837ef937eb5188861a2632a47a344c657f/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L461)):*
> statement on the props to the details page (statement here means the query itself)

The `this.props.statement` is the statement object, not the query itself. It's then destructured to `stats`, so that `stats` is actually `this.props.statement`. In the old code, the query itself is `this.props.statement.statement`.

I'm unclear about the use cases in the old code where `this.props.statement` is null, vs when `this.props.statement` is present but `this.props.statement.stats` is not.

**Review by Azhng — COMMENTED** [review]
> Reviewed 1 of 30 files at r1, 1 of 4 files at r2, 7 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77215)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/store/statementDetails/statementDetails.reducer.ts, line 54 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxGkvxG2BtkLAy5-SBX:-MxGkvxG2BtkLAy5-SBY:bs2adlt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b29fa03ca4706c897e19692d4548e7ee0b23806/pkg/ui/workspaces/cluster-ui/src/store/statementDetails/statementDetails.reducer.ts#L54)):*
> ```XML
>     },
>     invalidated: (state, action: PayloadAction<{ key: string }>) => {
>       if (action.payload.key) {
> ```

Hmm, I presume that adding the `if` check here is to handle two cases:
1. invalidate specifically for a key, (where a key is specified)
2. invalidate when reset SQL Stats is clicked, (where the key is not specified

Correct me if I misunderstood this, but it seems like when it's been invalidated in the second case, the `state` actually doesn't get reset?

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77215)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/store/statementDetails/statementDetails.reducer.ts, line 54 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-MxGkvxG2BtkLAy5-SBX:-MxHMFrn6KhNYYFzJyZ7:b-92lind) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b29fa03ca4706c897e19692d4548e7ee0b23806/pkg/ui/workspaces/cluster-ui/src/store/statementDetails/statementDetails.reducer.ts#L54)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm, I presume that adding the `if` check here is to handle two cases:
1. invalidate specifically for a key, (where a key is specified)
2. invalidate when reset SQL Stats is clicked, (where the key is not specified

Correct me if I misunderstood this, but it seems like when it's been invalidated in the second case, the `state` actually doesn't get reset? 
</blockquote></details>

I wasn't able to test the reset of the code since the reset wasn't working, so I didn't wanted to add to this PR until I had tested. I added the if part, just so it wouldn't crash for the invalidate. I added the remaining code now.

**Review by Azhng — APPROVED** [review]
:lgtm:

> Reviewed 1 of 10 files at r3, 1 of 2 files at r4, 7 of 7 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-:-Mxegozr3MYpKo3gO8jI:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/store/statementDetails/statementDetails.reducer.ts, line 67 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-Mxeg6Hf6xZtXM3Lj5Do:-Mxeg6Hf6xZtXM3Lj5Dp:bg0que) ([raw file](https://github.com/cockroachdb/cockroach/blob/6378d634c3587c75ebc4c3f95453992bd351e448/pkg/ui/workspaces/cluster-ui/src/store/statementDetails/statementDetails.reducer.ts#L67)):*
> ```XML
>             valid: false,
>             lastError: null,
>           };
> ```

Hmm, should we just delete the content of the key here instead e.g. `delete state[key]` ?

**Review by maryliag — COMMENTED** [review]
Working on DB and CC Console :tada: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-:-MxfvmO-Ajd9noOvnx9f:b-txcty9)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng, @jocrl, and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/store/statementDetails/statementDetails.reducer.ts, line 67 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77215#-Mxeg6Hf6xZtXM3Lj5Do:-MxfvkBa5zN2bJ1GH3Gi:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/6378d634c3587c75ebc4c3f95453992bd351e448/pkg/ui/workspaces/cluster-ui/src/store/statementDetails/statementDetails.reducer.ts#L67)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm, should we just delete the content of the key here instead e.g. `delete state[key]` ? 
</blockquote></details>

Done

**Comment by maryliag** [comment]
TFTR!
bors r+

**Pull request merged**
