### PR TITLE
backupccl: retry send errors

### PR DESCRIPTION
**Pull request by dt**
Release note: none.
Epic: none.

### CODE REVIEW

**Comment by dt** [comment]
`./dev test --stress ./pkg/ccl/backupccl -f TestBackupWorkerFailure` was failing in 30-100 runs before this and has done 800 runs so far with it

**Review by msbutler — COMMENTED** [review]
Should we only retry on `NotLeaseHolderError` as you write in [slack](https://cockroachlabs.slack.com/archives/C03JCUUSCD6/p1701108999164949sl), instead of anything that matches with "failed to send RPC"?

Also, could you add a bit more context to the commit message?

**Comment by dt** [comment]
> Should we only retry on NotLeaseHolderError..., instead of anything that matches with "failed to send RPC"?

"failed to send RPC" indicates a "sendError", which means distsender wasn't able to send the request (as opposed to sending it and getting an error back as a reply). 

`NotLeaseHolderError` is the one I saw this time but I could imagine there are maybe other ways that a transient error (gossip hiccup or something?) means you are unable to send a request, but these seem rare enough and usually related to transient issues that they seem worth retrying a few times to me before we give up, unlike most error replies which are often saying you aren't authorized or are asking for wrong span or something that won't go away on retry unless it is marked as retryable.

**Review by msbutler — APPROVED** [review]
LGTM, modulo more context in commit msg.

**Pull request closed without merging**
