### PR TITLE
pgwire, cli/sql: support tables with no columns properly

### LINKED ISSUE #13769: cli: results with no columns are rendered incorrectly
Our CLI renders results of a select with no columns by just printing `OK`, which doesn't make too much sense.

Us:
```
root@:26257/jordan> SELECT * FROM empty;
OK
```
psql:
```
$ psql -p 26257 -h localhost
psql (9.6.2, server 9.5.0)
Type "help" for help.

jordan=> select * from empty;
--
(0 rows)
```

Found after fixing #13725.

### PR DESCRIPTION
**Pull request by knz**
Fixes #13769.
Supersedes #14973.

### CODE REVIEW

**Comment by knz** [comment]
I made a mistake by closing this PR. Actually I need this patch to fix #18447. Jordan could you have a look again?

**Comment by knz** [comment]
Rebased; PTAL

**Comment by knz** [comment]
Note to self: extend to fix csv/tsv for #18329 too.

**Comment by jordanlewis** [comment]
Taking a look at this today.

**Comment by knz** [comment]
Added a commit to stream results for csv/tsv.

**Comment by jordanlewis** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 8 of 8 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17816#-:-Ku6E_Ti5MJR6d-hlD3A:bnfp4nl)*

**Comment by knz** [comment]
TFYR!

**Pull request merged**
