### PR TITLE
kvserver: improve TestClosedTimestampInactiveAfterSubsumption

### LINKED ISSUE #52585: kv/kvserver: TestClosedTimestampInactiveAfterSubsumption failed
[(kv/kvserver).TestClosedTimestampInactiveAfterSubsumption failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2166180&tab=buildLog) on [master@e4d5f351156bc3f0a3a268a63833a91c1f508c39](https://github.com/cockroachdb/cockroach/commits/e4d5f351156bc3f0a3a268a63833a91c1f508c39):

Fatal error:
```
panic: test timed out after 45m0s

```

Stack:
```
goroutine 452767 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1377 +0x11c
created by time.goFunc
	/usr/local/go/src/time/sleep.go:168 +0x52

```

<details><summary>Log preceding fatal error</summary><p>

```
I200810 16:33:24.587337 379362 server/status/runtime.go:504  [n2] runtime stats: 11 GiB RSS, 855 goroutines, 1.3 GiB/387 MiB/1.6 GiB GO alloc/idle/total, 256 MiB/290 MiB CGO alloc/total, 128.3 CGO/sec, 123.2/11.8 %(u/s)time, 0.0 %gc (0x), 1.0 MiB/1.0 MiB (r/w)net
I200810 16:33:24.970931 379690 gossip/gossip.go:568  [n3] gossip status (ok, 3 nodes)
gossip client (1/3 cur/max conns)
  1: 127.0.0.1:37705 (34m0s: infos 4465/19161 sent/received, bytes 726680B/2639597B sent/received)
gossip server (0/3 cur/max conns, infos 4465/19161 sent/received, bytes 726680B/2639597B sent/received)
I200810 16:33:25.068459 379694 server/status/runtime.go:504  [n3] runtime stats: 11 GiB RSS, 855 goroutines, 1.3 GiB/370 MiB/1.6 GiB GO alloc/idle/total, 256 MiB/290 MiB CGO alloc/total, 128.0 CGO/sec, 118.8/11.3 %(u/s)time, 0.0 %gc (0x), 1013 KiB/1013 KiB (r/w)net
E200810 16:33:31.865897 379400 jobs/registry.go:531  error while adopting jobs: trying to adopt jobs on node 2 which is not live
I200810 16:33:33.246848 378277 server/status/runtime.go:504  [n1] runtime stats: 11 GiB RSS, 853 goroutines, 905 MiB/808 MiB/1.6 GiB GO alloc/idle/total, 256 MiB/290 MiB CGO alloc/total, 191.9 CGO/sec, 137.3/13.6 %(u/s)time, 0.0 %gc (1x), 800 KiB/800 KiB (r/w)net
I200810 16:33:34.588825 379362 server/status/runtime.go:504  [n2] runtime stats: 11 GiB RSS, 854 goroutines, 968 MiB/749 MiB/1.6 GiB GO alloc/idle/total, 256 MiB/290 MiB CGO alloc/total, 192.7 CGO/sec, 146.0/14.8 %(u/s)time, 0.0 %gc (1x), 981 KiB/981 KiB (r/w)net
W200810 16:33:34.764673 378247 kv/kvserver/store_rebalancer.go:223  [n1,s1,store-rebalancer] StorePool missing descriptor for local store
I200810 16:33:35.068973 379694 server/status/runtime.go:504  [n3] runtime stats: 11 GiB RSS, 854 goroutines, 989 MiB/730 MiB/1.6 GiB GO alloc/idle/total, 256 MiB/290 MiB CGO alloc/total, 187.9 CGO/sec, 149.8/15.2 %(u/s)time, 0.0 %gc (1x), 973 KiB/973 KiB (r/w)net
I200810 16:33:43.246651 378277 server/status/runtime.go:504  [n1] runtime stats: 11 GiB RSS, 853 goroutines, 1.2 GiB/544 MiB/1.6 GiB GO alloc/idle/total, 256 MiB/290 MiB CGO alloc/total, 120.7 CGO/sec, 139.3/13.4 %(u/s)time, 0.0 %gc (0x), 956 KiB/956 KiB (r/w)net
I200810 16:33:44.588991 379362 server/status/runtime.go:504  [n2] runtime stats: 11 GiB RSS, 853 goroutines, 1.2 GiB/514 MiB/1.6 GiB GO alloc/idle/total, 256 MiB/290 MiB CGO alloc/total, 119.5 CGO/sec, 135.0/12.5 %(u/s)time, 0.0 %gc (0x), 833 KiB/833 KiB (r/w)net
I200810 16:33:45.068253 379694 server/status/runtime.go:504  [n3] runtime stats: 11 GiB RSS, 854 goroutines, 1.2 GiB/494 MiB/1.6 GiB GO alloc/idle/total, 256 MiB/290 MiB CGO alloc/total, 124.7 CGO/sec, 136.0/12.5 %(u/s)time, 0.0 %gc (0x), 843 KiB/843 KiB (r/w)net
I200810 16:33:53.248252 378277 server/status/runtime.go:504  [n1] runtime stats: 11 GiB RSS, 853 goroutines, 1.4 GiB/311 MiB/1.6 GiB GO alloc/idle/total, 256 MiB/290 MiB CGO alloc/total, 123.9 CGO/sec, 129.6/11.6 %(u/s)time, 0.0 %gc (0x), 743 KiB/743 KiB (r/w)net
W200810 16:33:53.707258 379200 kv/kvserver/closedts/provider/provider.go:155  [ct-closer] unable to move closed timestamp forward: not live
(1) attached stack trace
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.init
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/node_liveness.go:60
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5228
  | runtime.doInit
  | 	/usr/local/go/src/runtime/proc.go:5223
  | runtime.main
  | 	/usr/local/go/src/runtime/proc.go:190
  | runtime.goexit
  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
Wraps: (2) not live
Error types: (1) *withstack.withStack (2) *errors.errorString
I200810 16:33:54.589663 379362 server/status/runtime.go:504  [n2] runtime stats: 11 GiB RSS, 853 goroutines, 760 MiB/940 MiB/1.6 GiB GO alloc/idle/total, 256 MiB/290 MiB CGO alloc/total, 126.3 CGO/sec, 136.2/12.3 %(u/s)time, 0.0 %gc (1x), 707 KiB/707 KiB (r/w)net
I200810 16:33:55.069212 379694 server/status/runtime.go:504  [n3] runtime stats: 11 GiB RSS, 855 goroutines, 779 MiB/924 MiB/1.6 GiB GO alloc/idle/total, 256 MiB/290 MiB CGO alloc/total, 123.1 CGO/sec, 133.8/12.1 %(u/s)time, 0.0 %gc (1x), 703 KiB/703 KiB (r/w)net
E200810 16:34:01.979050 379400 jobs/registry.go:531  error while adopting jobs: trying to adopt jobs on node 2 which is not live
W200810 16:34:02.894279 379331 kv/kvserver/store_rebalancer.go:223  [n2,s2,store-rebalancer] StorePool missing descriptor for local store
I200810 16:34:03.247081 378277 server/status/runtime.go:504  [n1] runtime stats: 11 GiB RSS, 856 goroutines, 979 MiB/739 MiB/1.6 GiB GO alloc/idle/total, 256 MiB/290 MiB CGO alloc/total, 186.7 CGO/sec, 127.8/12.0 %(u/s)time, 0.0 %gc (1x), 624 KiB/624 KiB (r/w)net
I200810 16:34:04.589417 379362 server/status/runtime.go:504  [n2] runtime stats: 11 GiB RSS, 856 goroutines, 1022 MiB/699 MiB/1.6 GiB GO alloc/idle/total, 256 MiB/290 MiB CGO alloc/total, 185.5 CGO/sec, 126.8/11.6 %(u/s)time, 0.0 %gc (0x), 603 KiB/603 KiB (r/w)net
I200810 16:34:05.069980 379694 server/status/runtime.go:504  [n3] runtime stats: 11 GiB RSS, 856 goroutines, 1.0 GiB/685 MiB/1.6 GiB GO alloc/idle/total, 256 MiB/290 MiB CGO alloc/total, 183.5 CGO/sec, 124.6/11.5 %(u/s)time, 0.0 %gc (0x), 596 KiB/596 KiB (r/w)net
I200810 16:34:13.248178 378277 server/status/runtime.go:504  [n1] runtime stats: 11 GiB RSS, 855 goroutines, 1.2 GiB/516 MiB/1.6 GiB GO alloc/idle/total, 256 MiB/290 MiB CGO alloc/total, 122.3 CGO/sec, 131.8/11.1 %(u/s)time, 0.0 %gc (0x), 601 KiB/601 KiB (r/w)net
I200810 16:34:14.590338 379362 server/status/runtime.go:504  [n2] runtime stats: 11 GiB RSS, 855 goroutines, 1.2 GiB/474 MiB/1.6 GiB GO alloc/idle/total, 256 MiB/290 MiB CGO alloc/total, 118.3 CGO/sec, 132.6/11.1 %(u/s)time, 0.0 %gc (0x), 602 KiB/602 KiB (r/w)net
I200810 16:34:15.069646 379694 server/status/runtime.go:504  [n3] runtime stats: 11 GiB RSS, 856 goroutines, 1.2 GiB/460 MiB/1.6 GiB GO alloc/idle/total, 256 MiB/290 MiB CGO alloc/total, 126.3 CGO/sec, 133.1/11.2 %(u/s)time, 0.0 %gc (0x), 701 KiB/701 KiB (r/w)net
I200810 16:34:23.247553 378277 server/status/runtime.go:504  [n1] runtime stats: 11 GiB RSS, 855 goroutines, 775 MiB/925 MiB/1.6 GiB GO alloc/idle/total, 256 MiB/290 MiB CGO alloc/total, 125.9 CGO/sec, 131.9/11.2 %(u/s)time, 0.0 %gc (1x), 1000 KiB/1000 KiB (r/w)net
I200810 16:34:24.517294 379054 gossip/gossip.go:568  [n2] gossip status (ok, 3 nodes)
gossip client (1/3 cur/max conns)
  1: 127.0.0.1:37705 (35m0s: infos 4593/19719 sent/received, bytes 746578B/2704297B sent/received)
gossip server (0/3 cur/max conns, infos 4593/19719 sent/received, bytes 746578B/2704297B sent/received)
I200810 16:34:24.589547 379362 server/status/runtime.go:504  [n2] runtime stats: 11 GiB RSS, 855 goroutines, 816 MiB/888 MiB/1.6 GiB GO alloc/idle/total, 256 MiB/290 MiB CGO alloc/total, 129.5 CGO/sec, 129.3/11.1 %(u/s)time, 0.0 %gc (1x), 996 KiB/996 KiB (r/w)net
I200810 16:34:24.971815 379690 gossip/gossip.go:568  [n3] gossip status (ok, 3 nodes)
gossip client (1/3 cur/max conns)
  1: 127.0.0.1:37705 (35m0s: infos 4596/19722 sent/received, bytes 747810B/2713335B sent/received)
gossip server (0/3 cur/max conns, infos 4596/19722 sent/received, bytes 747810B/2713335B sent/received)
I200810 16:34:25.071148 379694 server/status/runtime.go:504  [n3] runtime stats: 11 GiB RSS, 855 goroutines, 839 MiB/868 MiB/1.6 GiB GO alloc/idle/total, 256 MiB/290 MiB CGO alloc/total, 125.5 CGO/sec, 133.5/11.2 %(u/s)time, 0.0 %gc (1x), 918 KiB/918 KiB (r/w)net

```

</p></details>

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestClosedTimestampInactiveAfterSubsumption PKG=./pkg/kv/kvserver TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestClosedTimestampInactiveAfterSubsumption.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by aayushshah15**
Lately, we've seen flakes on this because it expects range merges to not
be internally retried by the co-ordinating node. The initial reasoning
to error out whenever the merge retried was misguided. This commit
improves the test by making it resilient to such retries in addition to
only installing the merge request filter right before the merge txn was
actually launched by the test, instead of at the beginning.

Fixes #52585

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52949)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @andreimatei)

___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 520 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52949#-MFGY2VhEN0xXZIG0p2-:-MFGY2VhEN0xXZIG0p20:bsp3w3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/79144e11a9abab9939b56b3be6bf3b9a46d341db/pkg/kv/kvserver/closed_timestamp_test.go#L520)):*
> ```Go
> 			// here because we want to avoid blocking the merge txn if it retries for
> 			// any reason.
> 			blockMergeTrigger: make(chan hlc.Timestamp, 10),
> ```

mmm I dunno about this. It seems to me that what we want out of the `TestingRequestFilter` that we install is to notify us of the first merge txn, and block all of them. I'd add code to the  `mergeFilterState`  do exactly that - add a `FirstMerge() <-chan timestamp` method that arms the filter, and then have the implementation disarm itself once the first notification has been sent. You can also keep the current semantics with a `AllMerges()` method, but given that the filter is not configured to report back which range is getting merged, I doubt it would be useful.

To make that filter more sane, I'd have it remember which range's merge is blocked, and I'd have only subsequent merges of the same range block on the `finishMergeTxn` chan.
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 623 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52949#-MFGXWGb8jIq_vG7vuvQ:-MFGXWGc6lHZzuptgZ-1:ban2y6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/79144e11a9abab9939b56b3be6bf3b9a46d341db/pkg/kv/kvserver/closed_timestamp_test.go#L623)):*
> ```Go
> 		case err := <-mergeErrCh:
> 			t.Fatal(err)
> 		case <-time.After(15 * time.Minute):
> ```

15 minutes!?! Not seconds?
FWIW, all the `SucceedsSoon` everywhere succeed in 45s.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52949)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 520 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52949#-MFGY2VhEN0xXZIG0p2-:-MFK_W9QEik72d9qhx5D:b-zbkoan) ([raw file](https://github.com/cockroachdb/cockroach/blob/79144e11a9abab9939b56b3be6bf3b9a46d341db/pkg/kv/kvserver/closed_timestamp_test.go#L520)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

mmm I dunno about this. It seems to me that what we want out of the `TestingRequestFilter` that we install is to notify us of the first merge txn, and block all of them. I'd add code to the  `mergeFilterState`  do exactly that - add a `FirstMerge() <-chan timestamp` method that arms the filter, and then have the implementation disarm itself once the first notification has been sent. You can also keep the current semantics with a `AllMerges()` method, but given that the filter is not configured to report back which range is getting merged, I doubt it would be useful.

To make that filter more sane, I'd have it remember which range's merge is blocked, and I'd have only subsequent merges of the same range block on the `finishMergeTxn` chan.
</blockquote></details>

That's way cleaner, done.

However, note that once the merge filter has unblocked a range-merge, we simply want the test to finish and we do _not_ want to block future retries of the merge commit on the blocked range, so we simply need to disarm the merge filter once it has blocked the first merge trigger it sees. 
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 623 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52949#-MFGXWGb8jIq_vG7vuvQ:-MFKaS1xBs3hPNSGzwCD:biuc35w) ([raw file](https://github.com/cockroachdb/cockroach/blob/79144e11a9abab9939b56b3be6bf3b9a46d341db/pkg/kv/kvserver/closed_timestamp_test.go#L623)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

15 minutes!?! Not seconds?
FWIW, all the `SucceedsSoon` everywhere succeed in 45s.
</blockquote></details>

Fixed, I had meant `15s`, but I'm worried that this is too low for CI machines under load so I set it to 45s.

**Review by andreimatei — COMMENTED** [review]
I think the implementation has a race where the 45s expire, `UnblockMerge()` is called, but then the merge txn is gets blocked because nobody is reading from `blockMergeTrigger`. This might be currently benign since a server can probably stop even though a request is blocked, but it's still not great.

Other than that this looks good, but I've added another commit which tries to clarify that merge filter a bit. It's here; if you like it take it and squash it in.
https://github.com/cockroachdb/cockroach/compare/master...andreimatei:pr/52949?expand=1
What bothered me is that the `filterState` was mixing concerns about trapping one particular merge (e.g. the `finishMergeTxn` chan) with concerns about whether the filter is active or not. It was unclear whether `BlockNextMerge()` can be called multiple times (the name suggests that it can, but I think that didn't actually work) and when it can be called. The commit fixes that race too.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52949#-:-MFWP9BK8Lo9w1puu8U7:bopr68)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

**Review by aayushshah15 — COMMENTED** [review]
Thanks, I added your change in. RFAL. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52949#-:-MFXJqILChFl1OZOn-_5:bdwzqn8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

**Comment by aayushshah15** [comment]
@nvanbenschoten, I added you since Andrei is out this week. 

Note that I've currently skipped this test under race because we're seeing flakes due to slowdowns on `TestCluster`'s operations. I `bisect`ed this slowdown to #51087. I saw frequent node liveness failures in the logs and, in general, things just being really slow on `TestCluster` with that change in. That being said, my bisection process wasn't very scientific (I just ran it with a 5m timeout under `stressrace`, since the first set of runs on the commit that introduced this test took ~2-3minutes). I want to revisit this at a later date.

**Review by nvb — APPROVED** [review]
:lgtm: thanks for deflaking this.

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52949#-:-MFYM3tV9el0S3rVIui4:b-cvy1j2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Comment by aayushshah15** [comment]
TFTR! 

bors r+

**Pull request merged**
