### PR TITLE
 changefeedccl: use the async kafka producer

### PR DESCRIPTION
**Pull request by danhhz**
Release note (enterprise change): CHANGEFEEDs now use an asynchronous
Kafka producer, increasing throughput.

### CODE REVIEW

**Comment by danhhz** [comment]
There's a few things I don't like about this approach, but I wanted to get this out for early review for some second opinions. Feel free to keep comments to a high-level until the approach is figured out.

**Review by nvb — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 5 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27421)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/changefeedccl/sink.go, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27421#-LHEgZ9dAoni8L3HESEi:-LHEgZ9dAoni8L3HESEj:b2davgq) ([raw file](https://github.com/cockroachdb/cockroach/blob/0357ad93c4b94c833218ad57d14ed6341181e414/pkg/ccl/changefeedccl/sink.go#L49)):*
> ```Go
> 	// to add a new c dep for the prototype. Revisit before 2.1 and check
> 	// stability, performance, etc.
> 	inputCh     chan<- *sarama.ProducerMessage
> ```

Why pull out these channels? It makes it less clear that they are used exclusively to interact with the `sarama.AsyncProducer`.

EDIT: Are you using this so that you can mock out the channels in the test? `sarama. AsyncProducer` is already an interface, so I'd lean towards giving it a different implementation in tests.
___
*[pkg/ccl/changefeedccl/sink.go, line 215 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27421#-LHEfBkr7WWo04Gz-zJl:-LHEfBksEiKhPxYGpe7t:bvj71mv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0357ad93c4b94c833218ad57d14ed6341181e414/pkg/ccl/changefeedccl/sink.go#L215)):*
> ```Go
> 
> func (s *kafkaSink) emitMessage(ctx context.Context, msg *sarama.ProducerMessage) error {
> 	s.mu.Lock()
> ```

The locking is a little surprising here. Does this need to be threadsafe? Are all methods now threadsafe? It seems like a lot of this logic would be more simple if we stuck with the single-threaded approach we had before.
___
*[pkg/ccl/changefeedccl/sink.go, line 227 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27421#-LHEfmzJCe1_cHzwdDrM:-LHEfmzJCe1_cHzwdDrN:btg0xed) ([raw file](https://github.com/cockroachdb/cockroach/blob/0357ad93c4b94c833218ad57d14ed6341181e414/pkg/ccl/changefeedccl/sink.go#L227)):*
> ```Go
> 	// message, but this has led to quite a bit of complexity and fragility.
> 	// Having a goroutine handle all of the reads from the success and error
> 	// channels is almost certainly more straightforward.
> ```

Yeah, the interactions here are strange and it's not immediately clear why we need to read from the `errorsCh` or the `successesCh` without diving into the `sarama` documentation. I personally find the `Example (Goroutines)` easier to understand than the `Example (Select)`. Curious what your thoughts are.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27421)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/changefeedccl/sink.go, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27421#-LHEgZ9dAoni8L3HESEi:-LH_4LEz0BMbwJ6RFxq-:bt4cfmo) ([raw file](https://github.com/cockroachdb/cockroach/blob/0357ad93c4b94c833218ad57d14ed6341181e414/pkg/ccl/changefeedccl/sink.go#L49)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why pull out these channels? It makes it less clear that they are used exclusively to interact with the `sarama.AsyncProducer`.

EDIT: Are you using this so that you can mock out the channels in the test? `sarama. AsyncProducer` is already an interface, so I'd lean towards giving it a different implementation in tests.
</blockquote></details>

Done. (No good reason. I was thinking of ctx.Done(), but the issue with that one is the locking, not the probably-inlined function call.)
___
*[pkg/ccl/changefeedccl/sink.go, line 215 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27421#-LHEfBkr7WWo04Gz-zJl:-LH_47uTEN5RyxWha48C:b8khdvk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0357ad93c4b94c833218ad57d14ed6341181e414/pkg/ccl/changefeedccl/sink.go#L215)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The locking is a little surprising here. Does this need to be threadsafe? Are all methods now threadsafe? It seems like a lot of this logic would be more simple if we stuck with the single-threaded approach we had before.
</blockquote></details>

The previous impl happened to be threadsafe, but it wasn't needed. Good point. Simplified this to be the minimum thing we need.
___
*[pkg/ccl/changefeedccl/sink.go, line 227 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27421#-LHEfmzJCe1_cHzwdDrM:-LH_4HdZA8wI-hWhyHJ1:bs4q9op) ([raw file](https://github.com/cockroachdb/cockroach/blob/0357ad93c4b94c833218ad57d14ed6341181e414/pkg/ccl/changefeedccl/sink.go#L227)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, the interactions here are strange and it's not immediately clear why we need to read from the `errorsCh` or the `successesCh` without diving into the `sarama` documentation. I personally find the `Example (Goroutines)` easier to understand than the `Example (Select)`. Curious what your thoughts are.
</blockquote></details>

Ditto.

**Review by nvb — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27421#-:-LHiAnbyBhsnpvAsXz9C:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/ccl/changefeedccl/sink.go, line 58 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27421#-LHi88Y58cyoAbrLTMR0:-LHi88Y58cyoAbrLTMR1:b-i3zbxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac43ecf2b2032adb3bc93980f07f034baaa6d176/pkg/ccl/changefeedccl/sink.go#L58)):*
> ```Go
> 	worker       sync.WaitGroup
> 
> 	mu struct {
> ```

Leave a note that these fields are only synchronized between the client gouroutine and the worker goroutine.
___
*[pkg/ccl/changefeedccl/sink.go, line 98 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27421#-LHi7fV00LZ1Nrb3X--7:-LHi7fV00LZ1Nrb3X--8:b-8xsyr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac43ecf2b2032adb3bc93980f07f034baaa6d176/pkg/ccl/changefeedccl/sink.go#L98)):*
> ```Go
> // Close implements the Sink interface.
> func (s *kafkaSink) Close() error {
> 	s.stopWorkerCh <- struct{}{}
> ```

The more idiomatic approach to this would be to close the channel.
___
*[pkg/ccl/changefeedccl/sink.go, line 101 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27421#-LHi7oyH4UeetAhJhFXy:-LHi7oyH4UeetAhJhFXz:b8ivxtn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac43ecf2b2032adb3bc93980f07f034baaa6d176/pkg/ccl/changefeedccl/sink.go#L101)):*
> ```Go
> 	s.worker.Wait()
> 
> 	if s.producer != nil {
> ```

When would this equal nil? Seems like this case would panic later in this method anyway.
___
*[pkg/ccl/changefeedccl/sink.go, line 109 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27421#-LHi7yyVCc6v_HjfcplT:-LHi7yyVCc6v_HjfcplU:b-akvd5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac43ecf2b2032adb3bc93980f07f034baaa6d176/pkg/ccl/changefeedccl/sink.go#L109)):*
> ```Go
> 	for range s.producer.Successes() {
> 	}
> 	if s.client != nil {
> ```

Same question, when would this be nil?

**Review by danhhz — COMMENTED** [review]
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27421#-:-LHiQ1xM2eXDDniAyq9i:b-9qdoz3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/ccl/changefeedccl/sink.go, line 58 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27421#-LHi88Y58cyoAbrLTMR0:-LHiNzhN1UBG3XNhg7aL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac43ecf2b2032adb3bc93980f07f034baaa6d176/pkg/ccl/changefeedccl/sink.go#L58)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Leave a note that these fields are only synchronized between the client gouroutine and the worker goroutine.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink.go, line 98 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27421#-LHi7fV00LZ1Nrb3X--7:-LHiO5ja9CLmkft99Xq-:b64vtpi) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac43ecf2b2032adb3bc93980f07f034baaa6d176/pkg/ccl/changefeedccl/sink.go#L98)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The more idiomatic approach to this would be to close the channel.
</blockquote></details>

TIL. Done
___
*[pkg/ccl/changefeedccl/sink.go, line 101 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27421#-LHi7oyH4UeetAhJhFXy:-LHiO9067h5H2t3QZFzM:b-4d4gi5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac43ecf2b2032adb3bc93980f07f034baaa6d176/pkg/ccl/changefeedccl/sink.go#L101)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

When would this equal nil? Seems like this case would panic later in this method anyway.
</blockquote></details>

Whoops left over from before.
___
*[pkg/ccl/changefeedccl/sink.go, line 109 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27421#-LHi7yyVCc6v_HjfcplT:-LHiOAVC26BJdVozS1Ke:b7h5ryk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac43ecf2b2032adb3bc93980f07f034baaa6d176/pkg/ccl/changefeedccl/sink.go#L109)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Same question, when would this be nil?
</blockquote></details>

This one is because the test doesn't set a client (and it's got tens of methods, so it's pretty obnoxious to mock out).

**Comment by danhhz** [comment]
bors r=nvanbenschoten

**Pull request merged**
