### PR TITLE
sql: delete descriptor when function is dropped

### LINKED ISSUE #95364: sql: DROP FUNCTION does not delete function descriptor
**Describe the problem**

Currently when we drop a function through the legacy schema changer, we only removed it from the schema descriptor and set it to `DROPPED`. This leaves behind an idle descriptor not touched by anything (not one can see it because there is no way to resolve this function). 

**Expected behavior**
We should properly delete function descriptor after `DROP`

Jira issue: CRDB-23483

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
Fixes: #95364

**sql: delete descriptor when function is dropped**

Previously, in legacy schema changer, descriptor stayed as
a orphan recrod in system.descriptor when a function is dropped.
While this is not a big issue, we should keep data clean.
This PR adds schema change job logic to handle the deletions.

**upgrades: add upgrade to delete dropped function descriptors**

This commit adds an upgrade to delete orphan descriptors of
functions dropped through legacy schema changer before 23.1.

### CODE REVIEW

**Comment by chengxiong-ruan** [comment]
hmm.. looks like the `TestDeleteDescriptorsOfDroppedFunctions` test is flaky for some reason.

**Review by fqazi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96385)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @chengxiong-ruan)

___
*[`pkg/jobs/jobspb/jobs.proto` line 808 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96385#-NNHdNeuBKc09XXdEYHS:-NNHdNeuBKc09XXdEYHT:bp7hohu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f0199b3aab5ff240258629e2954e31c13ad297d/pkg/jobs/jobspb/jobs.proto#L808)):*
> ```protobuf
>     (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb.ID"
>   ];
>   repeated uint32 dropped_functions = 12 [(gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb.ID"];
> ```

Nit: Maybe a comment here
___
*[`pkg/upgrade/upgrades/delete_descriptors_of_dropped_functions.go` line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96385#-NNHenOE-xXdoETvlJPU:-NNHenOE-xXdoETvlJPV:b-nv70j1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bd725a770aaa739412a32b4a436195442ad6e5b/pkg/upgrade/upgrades/delete_descriptors_of_dropped_functions.go#L66)):*
> ```Go
> 		const batchSize = 50
> 
> 		for curID := 1; curID <= maxID; curID += batchSize {
> ```

What does the batching buy is here or what are we trying to avoid by doing it?

**Comment by chengxiong-ruan** [comment]
*[`pkg/upgrade/upgrades/delete_descriptors_of_dropped_functions.go` line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96385#-NNHenOE-xXdoETvlJPU:-NNHghub30eQIwtT7aLq:b-tuuzah) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bd725a770aaa739412a32b4a436195442ad6e5b/pkg/upgrade/upgrades/delete_descriptors_of_dropped_functions.go#L66)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

What does the batching buy is here or what are we trying to avoid by doing it?
</blockquote></details>

I think this is just in case there're too many descriptors which is rare though. But I think it's just nicer to do small batch to avoid one heavy operation.

**Comment by chengxiong-ruan** [comment]
*[`pkg/jobs/jobspb/jobs.proto` line 808 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96385#-NNHdNeuBKc09XXdEYHS:-NNHhLYDAwkJ7fqVH_ZC:b-d7bhn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f0199b3aab5ff240258629e2954e31c13ad297d/pkg/jobs/jobspb/jobs.proto#L808)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Nit: Maybe a comment here
</blockquote></details>

will do

**Comment by chengxiong-ruan** [comment]
*[`pkg/jobs/jobspb/jobs.proto` line 808 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96385#-NNHdNeuBKc09XXdEYHS:-NNHjuhF-hZihz8-jCMO:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f0199b3aab5ff240258629e2954e31c13ad297d/pkg/jobs/jobspb/jobs.proto#L808)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

will do
</blockquote></details>

done

**Review by fqazi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96385)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @chengxiong-ruan)

___
*[`pkg/upgrade/upgrades/delete_descriptors_of_dropped_functions.go` line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96385#-NNHenOE-xXdoETvlJPU:-NNHlpGs5iZbe9gqvPex:bhi7arp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bd725a770aaa739412a32b4a436195442ad6e5b/pkg/upgrade/upgrades/delete_descriptors_of_dropped_functions.go#L66)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

I think this is just in case there're too many descriptors which is rare though. But I think it's just nicer to do small batch to avoid one heavy operation.
</blockquote></details>

I think implicitly each delete will get its own KV batch, so this might not be necessary. Thinking the SQL layer would handle the select side nicely, but I'm okay with it.

**Comment by chengxiong-ruan** [comment]
TFTR!
bors r+

**Pull request merged**
