### PR TITLE
sql/sem/tree: get rid of sql/sem/tests

### PR DESCRIPTION
**Pull request by petermattis**
Integrate the tests in sql/sem/tests into sql/sem/tree by placing them
in the `tree_test` package.

Release note: None

### CODE REVIEW

**Comment by benesch** [comment]
Should sql/tests be given the same treatment?

**Comment by knz** [comment]
@jordanlewis I think you have the better judgment about this.

**Comment by petermattis** [comment]
> Should sql/tests be given the same treatment?

I think so.

**Comment by petermattis** [comment]
@jordanlewis Ping.

**Comment by jordanlewis** [comment]
LGTM.

**Pull request merged**
