### PR TITLE
tree: make FmtPgwireText more accurate

### PR DESCRIPTION
**Pull request by otan**
FmtPgwireText today currently does not actually match the pgwire text format for every type. This is now resolved.

spinoff from #94408

Release note: None

Epic: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
thanks for the cleanup!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96583#-:-NNgMztVAkjMP6HdZjHj:bj9u4r9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[`pkg/sql/sem/tree/datum.go` line 983 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96583#-NNgLwb04I3rN6nabLsO:-NNgLwb04I3rN6nabLsP:bcs6ubs) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d15057006d42a00426039940e119d67684c3814/pkg/sql/sem/tree/datum.go#L983)):*
> ```Go
> 
> 	// TODO(#sql-sessions): formatting float4s are broken here as we cannot
> 	// differentiate float4 vs float8. #73743 and #41689 are partially related.
> ```

could https://github.com/cockroachdb/cockroach/issues/84326 be added to this comment too?
___
*[`pkg/sql/sem/tree/datum.go` line 984 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96583#-NNgKtoOEKGN4KpeqUpl:-NNgKtoOEKGN4KpeqUpm:b-tkhpwm) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d15057006d42a00426039940e119d67684c3814/pkg/sql/sem/tree/datum.go#L984)):*
> ```Go
> 	// TODO(#sql-sessions): formatting float4s are broken here as we cannot
> 	// differentiate float4 vs float8. #73743 and #41689 are partially related.
> 	if ctx.HasFlags(FmtPgwireText) {
> ```

should this say `ctx.HasFlags(fmtPgwireFormat)` instead?

related: do we need both 
___
*[`pkg/sql/sem/tree/datum.go` line 1321 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96583#-NNgL737DHbqey9krTrn:-NNgL737DHbqey9krTro:b-31cnlc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d15057006d42a00426039940e119d67684c3814/pkg/sql/sem/tree/datum.go#L1321)):*
> ```Go
> func (d *DString) Format(ctx *FmtCtx) {
> 	buf, f := &ctx.Buffer, ctx.flags
> 	if f.HasFlags(fmtRawStrings) || f.HasFlags(fmtPgwireFormat) {
> ```

do we really need to check `fmtPgwireFormat` here?  given that `FmtPgwireText` is defined as `FmtPgwireText FmtFlags = fmtPgwireFormat | FmtFlags(lexbase.EncBareStrings)`, doesn't that mean that whenever it's used, the `EncBareStrings` flag is used in the `else` case below?
___
*[`pkg/sql/sem/tree/pgwire_encode.go` line 305 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96583#-NNgMjWX96F3Xsec24ya:-NNgMjWX96F3Xsec24yb:b-7dslbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d15057006d42a00426039940e119d67684c3814/pkg/sql/sem/tree/pgwire_encode.go#L305)):*
> ```Go
> // provided tmp buffer and reallocating if needed. The function will then return
> // the resulting buffer.
> // TODO(#sql-sessions): merge implementation with DTime.Format.
> ```

why can't they be merged now? i.e., have DTime.Format call this function
___
*[`pkg/sql/sem/tree/pgwire_encode.go` line 337 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96583#-NNgM2DsCrEqH_4X0irf:-NNgM2DsCrEqH_4X0irg:b-3e8t56) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d15057006d42a00426039940e119d67684c3814/pkg/sql/sem/tree/pgwire_encode.go#L337)):*
> ```Go
> }
> 
> // PGWireFormatTimestamp formats t into a format lib/pq understands.
> ```

could you mention that this is also used for TIMESTAMPTZ?
___
*[`pkg/sql/logictest/testdata/logic_test/timetz` line 491 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96583#-NNgKCyMBuj-Oem2bRvq:-NNgKCyMBuj-Oem2bRvr:b-occo6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d15057006d42a00426039940e119d67684c3814/pkg/sql/logictest/testdata/logic_test/timetz#L491)):*
> ```
> 
> query T rowsort
> SELECT * FROM tzarrays
> ```

this change in timetz formatting should appear in a release note (as a bug fix, since we now match postgres's encoding)

does this commit also change the minute offset for timestamptz in pgwire? if it does, can you add a test for that?

https://github.com/cockroachdb/cockroach/issues/41563 is related, but that one is about casts, so i think it's still unresolved.
___
*[`pkg/sql/pgwire/types_test.go` line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96583#-NNgKklT45oQFzsdi8D5:-NNgKklT45oQFzsdi8D6:b-f1lrwf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d15057006d42a00426039940e119d67684c3814/pkg/sql/pgwire/types_test.go#L46)):*
> ```Go
> // TestWriteTextDatumMatchesFmtPgwireText confirms tree.FmtPgwireText matches
> // the output of writeTextDatum. It is required so long as writeTextDatum
> // has a separate implementation to tree.FmtPgwireText
> ```

what's hard about unifying the implementations now? is it because of how we have to add the length headers?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96583)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/sem/tree/datum.go` line 984 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96583#-NNgKtoOEKGN4KpeqUpl:-NNiTJs51elLWbhqzgkP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d15057006d42a00426039940e119d67684c3814/pkg/sql/sem/tree/datum.go#L984)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should this say `ctx.HasFlags(fmtPgwireFormat)` instead?

related: do we need both 
</blockquote></details>

Done.
___
*[`pkg/sql/sem/tree/datum.go` line 1321 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96583#-NNgL737DHbqey9krTrn:-NNiTKX06UD8t6EnUJOR:b-f91oko) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d15057006d42a00426039940e119d67684c3814/pkg/sql/sem/tree/datum.go#L1321)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

do we really need to check `fmtPgwireFormat` here?  given that `FmtPgwireText` is defined as `FmtPgwireText FmtFlags = fmtPgwireFormat | FmtFlags(lexbase.EncBareStrings)`, doesn't that mean that whenever it's used, the `EncBareStrings` flag is used in the `else` case below?
</blockquote></details>

hmm, without it a bunch of tests failed .
`FmtBareStrings` != `fmtRawStrings` so it is needed.
___
*[`pkg/sql/sem/tree/pgwire_encode.go` line 305 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96583#-NNgMjWX96F3Xsec24ya:-NNiTtFQCYcxGFuaB4Ov:bdc0wc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d15057006d42a00426039940e119d67684c3814/pkg/sql/sem/tree/pgwire_encode.go#L305)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

why can't they be merged now? i.e., have DTime.Format call this function
</blockquote></details>

i can do it for this and timetz, but changing it for timestamptz/timestamp is a bigger change i'll do separately.
___
*[`pkg/sql/sem/tree/pgwire_encode.go` line 337 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96583#-NNgM2DsCrEqH_4X0irf:-NNiV-zsDHgUfGJkz-w-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d15057006d42a00426039940e119d67684c3814/pkg/sql/sem/tree/pgwire_encode.go#L337)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could you mention that this is also used for TIMESTAMPTZ?
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/timetz` line 491 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96583#-NNgKCyMBuj-Oem2bRvq:-NNiV3Q33USdSWawZLJw:b-6i0ijo) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d15057006d42a00426039940e119d67684c3814/pkg/sql/logictest/testdata/logic_test/timetz#L491)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this change in timetz formatting should appear in a release note (as a bug fix, since we now match postgres's encoding)

does this commit also change the minute offset for timestamptz in pgwire? if it does, can you add a test for that?

https://github.com/cockroachdb/cockroach/issues/41563 is related, but that one is about casts, so i think it's still unresolved.
</blockquote></details>

it only changes timetz, i'll add a fix for timestamp/timestamptz later (it's been on my TODOs for a while)
___
*[`pkg/sql/pgwire/types_test.go` line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96583#-NNgKklT45oQFzsdi8D5:-NNiVAmR7QMcDIhA0b7o:b5on4pw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d15057006d42a00426039940e119d67684c3814/pkg/sql/pgwire/types_test.go#L46)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

what's hard about unifying the implementations now? is it because of how we have to add the length headers?
</blockquote></details>

yeah the length headers + perf i was worried about.

**Comment by otan** [comment]
*[`pkg/sql/sem/tree/datum.go` line 983 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96583#-NNgLwb04I3rN6nabLsO:-NNiVs6AC6yfwQJ0EuYR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d15057006d42a00426039940e119d67684c3814/pkg/sql/sem/tree/datum.go#L983)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could https://github.com/cockroachdb/cockroach/issues/84326 be added to this comment too?
</blockquote></details>

Done.

**Review by otan — COMMENTED** [review]
> Dismissed @rafiss from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96583)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/sem/tree/pgwire_encode.go` line 305 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96583#-NNgMjWX96F3Xsec24ya:-NNmtyTx9Lj8crS-xHjJ:b-68xg2w) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d15057006d42a00426039940e119d67684c3814/pkg/sql/sem/tree/pgwire_encode.go#L305)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i can do it for this and timetz, but changing it for timestamptz/timestamp is a bigger change i'll do separately.
</blockquote></details>

hm, actually, it's a bigger lift than i expected. i'll do it in a follow up.

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96583)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[`pkg/sql/logictest/testdata/logic_test/timetz` line 491 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96583#-NNgKCyMBuj-Oem2bRvq:-NNn8cji94UHzMi255OF:b-8eqf7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d15057006d42a00426039940e119d67684c3814/pkg/sql/logictest/testdata/logic_test/timetz#L491)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

it only changes timetz, i'll add a fix for timestamp/timestamptz later (it's been on my TODOs for a while)
</blockquote></details>

cool, fine to do TIMESTAMPTZ later, but if TIMETZ is changing now, it still should be in the release note

**Comment by otan** [comment]
bors r=rafiss

**Pull request merged**
