### PR TITLE
storage: delete all "raft log as part of snapshots" code

### PR DESCRIPTION
**Pull request by irfansharif**
Raft log entries are no longer sent along with snapshots as of v19.2
(more specifically, #35701), we can/should delete all code around the
sending/handling of log entries in snapshots before v20.1 is cut. This
simplifies a few snapshot related protos and naturally obviates the need
to handle sideloaded proposals within snapshots.

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm: yay deleting code

> Reviewed 5 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44567#-:-LzwRFaL4BIRxu4Puvlu:bxvqxrb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @irfansharif, @nvanbenschoten, and @tbg)

___
*[pkg/storage/replica_raftstorage.go, line 443 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44567#-LzwQvpxA6UHrUZs5kcf:-LzwQvpxA6UHrUZs5kcg:bwl225i) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d2f75e472cfabae80ee4749413e4761043a38d9/pkg/storage/replica_raftstorage.go#L443)):*
> ```Go
> 	Iter *rditer.ReplicaDataIterator
> 	// The replica state within the snapshot.
> 	State storagepb.ReplicaState
> ```

This needs a newline or a gofmt. 
___
*[pkg/storage/replica_raftstorage.go, line 1057 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44567#-LzwR9z-B9J2VRXz9pMu:-LzwR9z-B9J2VRXz9pMv:b-ljv4aa) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d2f75e472cfabae80ee4749413e4761043a38d9/pkg/storage/replica_raftstorage.go#L1057)):*
> ```Go
> }
> 
> // extractRangeFromEntries returns a string representation of the range of
> ```

This is no longer used
___
*[pkg/storage/store_snapshot.go, line 762 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44567#-LzwQSQG8N20Z5z2l6cs:-LzwQSQG8N20Z5z2l6ct:btr6nk0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d2f75e472cfabae80ee4749413e4761043a38d9/pkg/storage/store_snapshot.go#L762)):*
> ```Go
> }
> 
> type errMustRetrySnapshotDueToTruncation struct {
> ```

This is no longer used.

**Review by nvb — APPROVED** [review]
:lgtm: this is another one I'd let @tbg sign off on as well before merging. 

> yay deleting code

keep going! What else can we delete?

> Reviewed 5 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44567#-:-LzwTYZQDKmykZNcbtNA:b-rr7ss6)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @irfansharif and @tbg)

___
*[pkg/storage/replica_raftstorage.go, line 795 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44567#-LzwSzcECONwdJ3IkrI8:-LzwSzcECONwdJ3IkrI9:b-6iwqm2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d2f75e472cfabae80ee4749413e4761043a38d9/pkg/storage/replica_raftstorage.go#L795)):*
> ```Go
> 	}
> 
> 	// Update Raft entries.
> ```

Could you add a comment here explaining what now happens with the recipient's Raft log?
___
*[pkg/storage/store_snapshot.go, line 288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44567#-LzwTL7p2aRl_HWaZM-M:-LzwTL7q1H35DvVvHlvi:bmmhah) ([raw file](https://github.com/cockroachdb/cockroach/blob/c434a8dfaf98dee56e00d5f9acaa1b45e78291e2/pkg/storage/store_snapshot.go#L288)):*
> ```Go
> 			}
> 
> 			expLen := inSnap.State.RaftAppliedIndex - inSnap.State.TruncatedState.Index
> ```

Is it worth asserting that this is always 0 so that we know we were never given any log entries from old versions of CRDB?

**Review by irfansharif — COMMENTED** [review]
TFTRs, I'll wait for Tobi to chime in. 

> What else can we delete?

I'm only really familiar with the more recent deprecations, you folks might know better. But very naively grepping for `19.{1,2}` in code comments (I'm very likely wrong here, didn't dig in deeper) I see:
1. `ChangeReplicasTrigger` has a few deprecated fields we should no longer be using, could strip out a bit. Also [this](https://github.com/cockroachdb/cockroach/blob/1a3c23278a981cc4123e71f389953a7a76b03f81/pkg/storage/replica_command.go#L2231-L2235) and [this](https://github.com/cockroachdb/cockroach/blob/1a3c23278a981cc4123e71f389953a7a76b03f81/pkg/storage/replica_command.go#L2145-L2146)
2. There's a bit of cleanup around unsplit command [code](https://github.com/cockroachdb/cockroach/blob/1a3c23278a981cc4123e71f389953a7a76b03f81/pkg/storage/replica_command.go#L468-L472)
3. Minor cleanup around sorting behavior of `InternalReplicas` [here](https://github.com/cockroachdb/cockroach/blob/1a3c23278a981cc4123e71f389953a7a76b03f81/pkg/storage/replica_command.go#L2033-L2042)
4. Some stats handling [here](https://github.com/cockroachdb/cockroach/blob/1a3c23278a981cc4123e71f389953a7a76b03f81/pkg/storage/replica_application_state_machine.go#L746-L760)
5. Leftover TODOs around intent handling [here](https://github.com/cockroachdb/cockroach/blob/1a3c23278a981cc4123e71f389953a7a76b03f81/pkg/storage/batcheval/transaction.go#L197-L203)
6. Code around checking if replicated eval result side effects are [trivial](https://github.com/cockroachdb/cockroach/blob/1a3c23278a981cc4123e71f389953a7a76b03f81/pkg/storage/replica_application_result.go#L55-L59)
7. Can probably remove this stats inconsistency panic [hatch](https://github.com/cockroachdb/cockroach/blob/1a3c23278a981cc4123e71f389953a7a76b03f81/pkg/storage/replica_consistency.go#L58)

Other than this, I can only think of stuff to clean up post #39182. Pre-emptive snapshots would be a nice one to strip out. RaftTruncatedStateLegacyKey is another, which IIUC would let us delete `cmd_truncate_log.go` + `handleTruncatedStateBelowRaft` in its entirety. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44567#-:-Lzwi7M_3QaKPPvHvpS-:b-pnk6a6)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ajwerner, @nvanbenschoten, and @tbg)

___
*[pkg/storage/replica_raftstorage.go, line 443 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44567#-LzwQvpxA6UHrUZs5kcf:-LzwaJGo46FxjmzhpluR:b-505hy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d2f75e472cfabae80ee4749413e4761043a38d9/pkg/storage/replica_raftstorage.go#L443)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This needs a newline or a gofmt. 
</blockquote></details>

Ugh, for some reason my goland filewatchers keep resetting. I should figure out what's happening.
___
*[pkg/storage/replica_raftstorage.go, line 795 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44567#-LzwSzcECONwdJ3IkrI8:-Lzwi3423EfvWC8AGguV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d2f75e472cfabae80ee4749413e4761043a38d9/pkg/storage/replica_raftstorage.go#L795)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you add a comment here explaining what now happens with the recipient's Raft log?
</blockquote></details>

Done.
___
*[pkg/storage/replica_raftstorage.go, line 1057 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44567#-LzwR9z-B9J2VRXz9pMu:-Lzwb-5P5t-s8SVU-vWr:b-i2jdpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d2f75e472cfabae80ee4749413e4761043a38d9/pkg/storage/replica_raftstorage.go#L1057)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This is no longer used
</blockquote></details>

Done (was leaning on CI lint checks).
___
*[pkg/storage/store_snapshot.go, line 288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44567#-LzwTL7p2aRl_HWaZM-M:-Lzwnv0UCIiGZ7oPNL0Y:b-xm8gf3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c434a8dfaf98dee56e00d5f9acaa1b45e78291e2/pkg/storage/store_snapshot.go#L288)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is it worth asserting that this is always 0 so that we know we were never given any log entries from old versions of CRDB?
</blockquote></details>

Assert what to zero? Not sure I follow. (I have to clean up the code block below this comment, but stepping out for a bit.)
___
*[pkg/storage/store_snapshot.go, line 762 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44567#-LzwQSQG8N20Z5z2l6cs:-Lzwa_-g94dVlRvJkS-s:b-i2jdpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d2f75e472cfabae80ee4749413e4761043a38d9/pkg/storage/store_snapshot.go#L762)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This is no longer used. 
</blockquote></details>

Done (was leaning on CI lint checks).

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44567)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ajwerner, @nvanbenschoten, and @tbg)

___
*[pkg/storage/store_snapshot.go, line 288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44567#-LzwTL7p2aRl_HWaZM-M:-LzxGhsC80smYAKngDEF:b-19kpcm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c434a8dfaf98dee56e00d5f9acaa1b45e78291e2/pkg/storage/store_snapshot.go#L288)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Assert what to zero? Not sure I follow. (I have to clean up the code block below this comment, but stepping out for a bit.)
</blockquote></details>

Oh, reviewable was not rendering the diff for some reason prior. I saw an isolated comment in the middle of no where. Done.

**Comment by tbg** [comment]
Hmm, it's late here and maybe I'm asleep at the wheel, but ranges that still use the legacy replicated truncated state must include the raft log. I don't think it's safe to remove this until we have #42822 and have migrated across it?

**Comment by irfansharif** [comment]
You're right. Going to let this sit for now.

**Comment by irfansharif** [comment]
> I don't think it's safe to remove this until we have #42822 and have migrated across it?

This was done in #58088, which means this PR will only be applicable in the v21.2 cycle, which is forever away. Closing it out.

**Pull request closed without merging**
