### PR TITLE
rules: suppress a dep-rule in special case

### LINKED ISSUE #86672: sql/schemachanger: drop jobs from 22.1 can fail trying to plan on RowLevelTTL
Any job generated with a RowLevelTTL element generated on 22.1 and resumed on 22.2 can fail. With the following error: `failed to satisfy [[Table:{DescID: 130}, ABSENT], DROPPED] -dep-SameStagePrecedence-> [[RowLevelTTL:{DescID: 130}, ABSENT], ABSENT] rule "descriptor drop right before dependent element removal"`

A simple repro is to pull down a 22.1 corpus: `gsutil cp gs://cockroach-corpus/corpus-86575/corpus . `, then run `./cockroach debug declarative-corpus-validate corpus`

### PR DESCRIPTION
**Pull request by Xiang-Gu**
Commit 1: very minor comment, function location, code changes;
Commit 2: suppress a dep-rule that causes forward incompatibility
for dropping a table with rowLevelTTL in the mixed version state.

Previously, in a mixed version state (v22.1 and v22.2), if a old node
    drops a rowLevelTTL table and the new shcema changer job was adopted
    by a new node, then there is a dep rule that cannot satisfied and hence
    causes forward incompatibility. This PR fixes this by suppressing this
    dep rule if this particular case happens (namely, it suppress the rule
    if `from` is Table element, `to` is a RowLevelTTL element, and there is
    no `PUBLIC` status of the table element anywhere in the graph).

Fixes: #86672

Release note: None

Release justification: fixed a release blocker bug.

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm: the CI failure is a flake

> Reviewed 3 of 3 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87196#-:-NBITNiy4r21or3nG-MK:bwimnyq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @Xiang-Gu)

___
*[`pkg/sql/schemachanger/scplan/internal/rules/dep_drop_object.go` line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87196#-NBITDF0-XDAjt5DRZVj:-NBITDF0-XDAjt5DRZVk:brpd0zv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c112476c6dfb5c7bf2d7674d5111571c733740c9/pkg/sql/schemachanger/scplan/internal/rules/dep_drop_object.go#L86)):*
> ```Go
> 									public.Eq(scpb.Status_PUBLIC),
> 									n.AttrEqVar(screl.CurrentStatus, public),
> 								}
> ```

Can you statically define this rules in `helpers`? Also, can you make these rule names not have spaces?



_Code quote:_
```Go
							screl.Schema.DefNotJoin1("node does not have a PUBLIC status", "n", func(n rel.Var) rel.Clauses {
								public := rel.Var("public")
								return rel.Clauses{
									public.Eq(scpb.Status_PUBLIC),
									n.AttrEqVar(screl.CurrentStatus, public),
								}
							})(n),
```

**Review by Xiang-Gu — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87196#-:-NBNRcQq99QXwBIM76FB:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

___
*[`pkg/sql/schemachanger/scplan/internal/rules/dep_drop_object.go` line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87196#-NBITDF0-XDAjt5DRZVj:-NBNRaxN3Hn-wOsUndS3:b-7rl0jq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c112476c6dfb5c7bf2d7674d5111571c733740c9/pkg/sql/schemachanger/scplan/internal/rules/dep_drop_object.go#L86)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can you statically define this rules in `helpers`? Also, can you make these rule names not have spaces?
</blockquote></details>

done!

**Comment by Xiang-Gu** [comment]
blathers backport 22.2

**Pull request merged**
