### PR TITLE
*: Add Spas to AUTHORS

### PR DESCRIPTION
**Pull request by spaskob**
This is part of onboarding

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38886#-:-Ljrd_BJDMNgDRiNoo23:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj)

**Review by spaskob — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38886#-:-LjvFScD9TnPc9Aw9zrC:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by spaskob** [comment]
testing if I can make random comments

**Pull request merged**
