### PR TITLE
storage: prevent concurrent proposals and lease transfers

### PR DESCRIPTION
**Pull request by ajwerner**
Before this PR we would not fail proposals when we learned about a lease
transfer. Instead we waited for a raft election before attempting to repropose.
Furthermore we generally just waited for those proposals to be committed but
fail to apply before notifying clients. This lazy failure detection is
problematic when the proposing replica is removed before the entries are
committed as it can lead to an ambiguous result.

Informs #37815.

Release justification: low risk, high benefit changes to existing functionality.

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
I've now typed the latching code and I think it is just simpler and better than the first commit.

**Review by nvb — COMMENTED** [review]
I agree with your preference for the second commit. However, I think the first commit does still serve a purpose. By placing the failure code in leasePostApply, we also avoid ambiguous errors on non-cooperative leaseholder changes. Weren't you were seeing a case where a leaseholder had its lease revoked without it immediately knowing (due to a disjoint raft leader) and only later finding this out when it applied the raft entry with the new lease?

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41473#-:-LrA8FXHDFBRRD_I3KKs:b-vb22qp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/storage/client_replica_test.go, line 2824 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41473#-LrA70sP0l1j-v5RTZum:-LrA70sP0l1j-v5RTZun:b-cry72m) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c8c053efac38d1d3ab7eac890ff8ec557c4b6ad/pkg/storage/client_replica_test.go#L2824)):*
> ```Go
> //      but it potentially still has pending commands which it thinks might
> //      have been proposed. This can occur if there are commands which are
> //      proposed after lease transfer has been proposed but before the lease
> ```

"a lease transfer" or "the lease transfer"
___
*[pkg/storage/batcheval/cmd_lease_transfer.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41473#-LrA652l6CPLvHL3xaio:-LrA652l6CPLvHL3xaip:b1abtsq) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c8c053efac38d1d3ab7eac890ff8ec557c4b6ad/pkg/storage/batcheval/cmd_lease_transfer.go#L33)):*
> ```Go
> 	// current range descriptor (desc) but it could potentially change due to an
> 	// as of yet unapplied merge.
> 	spans.Add(spanset.SpanReadOnly, roachpb.Span{Key: keys.LocalMax, EndKey: keys.MaxKey})
> ```

This will play well with https://github.com/cockroachdb/cockroach/pull/39765. With that change, you could declare this span as non-MVCC so that it will interfere with writes at a higher timestamp.

**Review by ajwerner — COMMENTED** [review]
This is RFAL

cc @irfansharif 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41473#-:-Lsw8qgA5mSWcqwda4Lx:b8ht7d7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/batcheval/cmd_lease_transfer.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41473#-LrA652l6CPLvHL3xaio:-Lsw8fgc7hGseRnP3o_1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c8c053efac38d1d3ab7eac890ff8ec557c4b6ad/pkg/storage/batcheval/cmd_lease_transfer.go#L33)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This will play well with https://github.com/cockroachdb/cockroach/pull/39765. With that change, you could declare this span as non-MVCC so that it will interfere with writes at a higher timestamp.
</blockquote></details>

Done.

**Review by irfansharif — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41473#-:-Lsx216s6sfcYsBsrG6Z:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by irfansharif — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41473)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/storage/client_replica_test.go, line 2824 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41473#-Lsx2WL76Pzo4ZQECsdt:-Lsx2WL76Pzo4ZQECsdu:b9i6j9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/52e7747a5e7739f6b924221c82192bc877d3e6c1/pkg/storage/client_replica_test.go#L2824)):*
> ```Go
> //      but it potentially still has pending commands which it thinks might
> //      have been proposed. This can occur if there are commands which are
> //      proposed after thje lease transfer has been proposed but before the lease
> ```

"thje" -> "the".

**Review by ajwerner — COMMENTED** [review]
@nvanbenschoten do you agree that this commit should not be backported? How do you feel about backporting the logic in the old first commit?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41473#-:-LsxSwyk-iQheymgiWSh:b-n8nrbr)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif)

___
*[pkg/storage/client_replica_test.go, line 2824 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41473#-Lsx2WL76Pzo4ZQECsdt:-LsxSwTH7QreIKmTc3Ba:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/52e7747a5e7739f6b924221c82192bc877d3e6c1/pkg/storage/client_replica_test.go#L2824)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

"thje" -> "the".
</blockquote></details>

Done.

**Review by irfansharif — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41473)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by nvb — APPROVED** [review]
:lgtm:

> do you agree that this commit should not be backported? How do you feel about backporting the logic in the old first commit?

I don't think we should backport any of this. The potential for stalls or other fallout seems too high to me and this isn't addressing a new issue.

> Reviewed 1 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41473#-:-Lt0VqHe81HN3D4Na8rR:bj4xr3n)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Pull request merged**
