### PR TITLE
release-24.1: sql: implement generic query plans

### PR DESCRIPTION
**Pull request by mgartner**
Backport:
  * 1/1 commits from "sql: add plan_cache_mode session setting" (#125708)
  * 2/2 commits from "opt: add ConvertSelectWithPlaceholdersToJoin exploration rule" (#125795)
  * 2/2 commits from "opt: improve stats for filters with placeholder equalities" (#125808)
  * 1/1 commits from "opt: add generic query plan tests with partial indexes" (#125871)
  * 3/3 commits from "sql: implement plan_cache_mode=force_generic_plan" (#126528)
  * 1/2 commits from "sql: implement plan_cache_mode=auto" (#126863)
  * 2/2 commits from "opt: optimize generic query plans with stable expressions" (#125814)
  * 1/1 commits from "sql: require an enterprise license to use generic query plans" (#127214)
  * 1/1 commits from "sql: add telemetry counters for generic query plans" (#127897)

Please see individual PRs for details.

/cc @cockroachdb/release

---

Release justification: New feature gated behind session setting.

### CODE REVIEW

**Comment by mgartner** [comment]
I know this PR was big. I thought backporting everything in bulk would be nice, but I'm happy to backport one PR at a time if that's easier on everyone else.

**Comment by rytaft** [comment]
Great work!! I didn't review all the code in detail since I think the original PR was reviewed carefully, but I did add a couple suggestions for things that might need a setting.

**Comment by mgartner** [comment]
@rytaft I don't see your suggestions. Did you forget to publish them?

**Review by rytaft — COMMENTED** [review]
Oops yes -- published now

> Reviewed 8 of 8 files at r1, 7 of 7 files at r2, 5 of 5 files at r3, 1 of 1 files at r4, 6 of 6 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, 23 of 23 files at r9, 7 of 7 files at r10, 1 of 1 files at r11, 5 of 5 files at r12, 17 of 17 files at r13, 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128085#-:-O3Z7uJD4iwubZDAjy0U:b-nycu97)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @xinhaoz)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 3401 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/128085#-O3YEWR1CzXSyysnwfk_:-O3YEWR21k8tLdGQLHLX:b-71cljn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d656601966c7b445f5fd3811aa58768025aad5fb/pkg/sql/opt/memo/statistics_builder.go#L3401)):*
> ```Go
> 
> 	// Special case: a placeholder equality filter.
> 	if col, ok := isPlaceholderEqualityFilter(filter.Condition); ok {
> ```

Although this looks like a big improvement, I'm always hesitant to backport any sort of stats change without a setting
___
*[`pkg/sql/opt/xform/generic_funcs.go` line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128085#-O3Y2WJ4BjMtcRM9yt9a:-O3Y2WJ4BjMtcRM9yt9b:b-3rnysy) ([raw file](https://github.com/cockroachdb/cockroach/blob/29631885161c63b6ab75d62a9c487c8a7b0e866a/pkg/sql/opt/xform/generic_funcs.go#L38)):*
> ```Go
> 	filters memo.FiltersExpr,
> ) (values memo.RelExpr, newFilters memo.FiltersExpr, ok bool) {
> 	// Collect all the placeholders in the filters.
> ```

should we add a check here that returns false if we are forcing custom plans?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128085)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2, @rytaft, and @xinhaoz)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 3401 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/128085#-O3YEWR1CzXSyysnwfk_:-O3ZAVDRANvSkBE3AbL1:b-jpuznd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d656601966c7b445f5fd3811aa58768025aad5fb/pkg/sql/opt/memo/statistics_builder.go#L3401)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Although this looks like a big improvement, I'm always hesitant to backport any sort of stats change without a setting
</blockquote></details>

I thought about that, but this stats code should never encounter a placeholder unless a generic query plan is being explored. With the default `plan_cache_mode=force_custom_plan`, all placeholders should be replaced with constant expressions before exploration. So `plan_cache_mode` is effectively gating this change (besides the code in `isPlaceholderEqualityFilter`, but that's fairly simple). Does that change your mind on this?
___
*[`pkg/sql/opt/xform/generic_funcs.go` line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128085#-O3Y2WJ4BjMtcRM9yt9a:-O3ZBbLS9O2q9c4fwjqP:b-bpubr3) ([raw file](https://github.com/cockroachdb/cockroach/blob/29631885161c63b6ab75d62a9c487c8a7b0e866a/pkg/sql/opt/xform/generic_funcs.go#L38)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

should we add a check here that returns false if we are forcing custom plans?
</blockquote></details>

I don't think it's necessary for filters with placeholders - we should never encounter those in non-generic plan exploration (see my other comment). But we might encounter those in stable expressions. I'll work on a PR and tack it on here.

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128085)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @xinhaoz)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 3401 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/128085#-O3YEWR1CzXSyysnwfk_:-O3ZQqTi4CWCSeitEcRe:b-1311q4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d656601966c7b445f5fd3811aa58768025aad5fb/pkg/sql/opt/memo/statistics_builder.go#L3401)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I thought about that, but this stats code should never encounter a placeholder unless a generic query plan is being explored. With the default `plan_cache_mode=force_custom_plan`, all placeholders should be replaced with constant expressions before exploration. So `plan_cache_mode` is effectively gating this change (besides the code in `isPlaceholderEqualityFilter`, but that's fairly simple). Does that change your mind on this?
</blockquote></details>

Sounds good, thanks for the explanation
___
*[`pkg/sql/opt/xform/generic_funcs.go` line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128085#-O3Y2WJ4BjMtcRM9yt9a:-O3ZQvlh5M97lI0lE7CK:b-ngc8og) ([raw file](https://github.com/cockroachdb/cockroach/blob/29631885161c63b6ab75d62a9c487c8a7b0e866a/pkg/sql/opt/xform/generic_funcs.go#L38)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't think it's necessary for filters with placeholders - we should never encounter those in non-generic plan exploration (see my other comment). But we might encounter those in stable expressions. I'll work on a PR and tack it on here.
</blockquote></details>

sounds good, thanks!

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice work! This is a pretty heroic backport. Just one question that occurred to me this time around.

> Reviewed 8 of 8 files at r1, 7 of 7 files at r2, 5 of 5 files at r3, 1 of 1 files at r4, 6 of 6 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, 23 of 23 files at r9, 7 of 7 files at r10, 1 of 1 files at r11, 5 of 5 files at r12, 17 of 17 files at r13, 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128085#-:-O5MfXqW2Fe2fFB0WU5B:b-dv21sk)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

___
*[`pkg/sql/plan_opt.go` line 575 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/128085#-O5Mbo1j2xc-SCA8yuog:-O5Mbo1j2xc-SCA8yuoh:b56p8q5) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdf5da19db4d2a87afcc8da9c836f132c6b72a93/pkg/sql/plan_opt.go#L575)):*
> ```Go
> 		if err != nil {
> 			return nil, err
> 		} else if !isStale {
> ```

Would it ever be possible to have a stale fully optimized plan and non-stale generic plan? Or similar for a generic plan and a normalized plan.

**Comment by mgartner** [comment]
I've added one of the commits from #129050.

**Comment by mgartner** [comment]
*[`pkg/sql/plan_opt.go` line 575 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/128085#-O5Mbo1j2xc-SCA8yuog:-O5Pee2c4YF3hKnTPZ2b:b-csqac8) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdf5da19db4d2a87afcc8da9c836f132c6b72a93/pkg/sql/plan_opt.go#L575)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Would it ever be possible to have a stale fully optimized plan and non-stale generic plan? Or similar for a generic plan and a normalized plan.
</blockquote></details>

Yes, I think both are possible. I intended to handle these cases with this logic. Is there something wrong you see?

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128085#-:-O5Piwku3fuCieX53zfy:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @michae2)

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128085)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner, @michae2, and @rytaft)

___
*[`pkg/sql/plan_opt.go` line 575 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/128085#-O5Mbo1j2xc-SCA8yuog:-O5V1EMCEoXVLdcS9WNM:b-cbd5fx) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdf5da19db4d2a87afcc8da9c836f132c6b72a93/pkg/sql/plan_opt.go#L575)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Yes, I think both are possible. I intended to handle these cases with this logic. Is there something wrong you see?
</blockquote></details>

Well if we do have a stale fully-optimized plan, shouldn't we return nil and build a new one, rather than resorting to a generic memo?

**Comment by mgartner** [comment]
*[`pkg/sql/plan_opt.go` line 575 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/128085#-O5Mbo1j2xc-SCA8yuog:-O5Zmc8N5fN6SzNG6D99:b-oi9jhb) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdf5da19db4d2a87afcc8da9c836f132c6b72a93/pkg/sql/plan_opt.go#L575)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Well if we do have a stale fully-optimized plan, shouldn't we return nil and build a new one, rather than resorting to a generic memo?
</blockquote></details>

That should never be possible. If the query has no placeholders or stable functions, then we'll never generate a generic memo, so it'll always be `nil`.

I think a lot of this confusion will be cleared up as I refactor this logic such that all fully-optimized plans are "generic", and the other cached plan is "normalized" or a "base" memo that still needs to be optimized. The main reason I didn't structure things like that form the get-go is because it would have made these backports more risky.

**Comment by mgartner** [comment]
TFTRs!

**Pull request merged**
