### PR TITLE
storage, server: Add a debug page that shows problem ranges

### PR DESCRIPTION
**Pull request by BramGruneir**
- export ReplicaMetrics so it can be used in server
- add a RangeProblems proto and add it to RangeInfo
- add a new endpoint that lists problem ranges

### CODE REVIEW

**Comment by BramGruneir** [comment]
It's quite ugly, but functional.  The goal with this PR is to get it working, next step is to clean it up a bit.

screen shot 2017-04-24 at 11 15 37

**Comment by petermattis** [comment]
:lgtm:

Let's file a follow-on issue to identify more problem ranges:
* No Raft Leader
* No lease
* Under-replicated

---

Review status: 0 of 14 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/server/debug.go, line 134 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15291#-KiVoMiLgCbBIRf5aWTo:-KiVoMiLgCbBIRf5aWTp:b-tkv7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ebbf80dcf43d4d01fbd199ddfa5a8783c8c9372/pkg/server/debug.go#L134)):*
> ```Go
>         <td>problem ranges</td>
>         <td><a href="/debug/problemranges">on the cluster</a></td>
>         <td><a href="/debug/problemranges?id=1">on a specific node (faster)</a></td>
> ```

I'd get rid of ` (faster)`. That's not a distinction I think it is important to highlight. 

---

*[pkg/server/problem_ranges.go, line 69 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15291#-KiVq9CFOGKajcTeBd0L:-KiVq9CFOGKajcTeBd0M:b-chn9sr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ebbf80dcf43d4d01fbd199ddfa5a8783c8c9372/pkg/server/problem_ranges.go#L69)):*
> ```Go
> 	}
> 
> 	aliveNodes := len(isLiveMap)
> ```

`s/aliveNodes/numNodes/g` as you don't actually know whether the node is alive or not. 

---

*[pkg/server/problem_ranges.go, line 138 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15291#-KiVqdpXhrP20jpQEL9m:-KiVqdpXhrP20jpQEL9n:bq2wo3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ebbf80dcf43d4d01fbd199ddfa5a8783c8c9372/pkg/server/problem_ranges.go#L138)):*
> ```Go
> 		data.Title = fmt.Sprintf("Problem Ranges for Node n%d", *data.NodeID)
> 	} else {
> 		data.Title = "Problem Ranges for the cluster"
> ```

`s/cluster/Cluster/g`

---

*[pkg/server/status.go, line 675 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15291#-KiVr5nUePpgagTJqLJB:-KiVr5nUePpgagTJqLJC:b-meuv6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ebbf80dcf43d4d01fbd199ddfa5a8783c8c9372/pkg/server/status.go#L675)):*
> ```Go
> 								Unavailable:          metrics.RangeCounter && metrics.Unavailable,
> 								LeaderNotLeaseHolder: metrics.Leader && metrics.LeaseValid && !metrics.Leaseholder,
> 							},
> ```

You could call `rep.Metrics` inside `constructRangeInfo` and remove a bit of duplication.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15291#-:-KiVrIX2EjrGZS0vojsE:b-9ohr6y)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/server/problem_ranges.go, line 37 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15291#-KiWP61bzD7fv15qrQFT:-KiWP61bzD7fv15qrQFU:b-n6y0w3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ebbf80dcf43d4d01fbd199ddfa5a8783c8c9372/pkg/server/problem_ranges.go#L37)):*
> ```Go
> 	ctx := s.AnnotateCtx(r.Context())
> 	w.Header().Add("Content-type", "text/html")
> 	nodeIDString := r.URL.Query().Get("id")
> ```

Name this parameter `node_id` to be clear what kind of `id` it is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15291#-:-KiWPXHpkkwJBwdMtxnQ:bnfp4nl)*

**Comment by BramGruneir** [comment]
Add the other types of problems to #14671

---

Review status: 2 of 14 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/server/debug.go, line 134 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15291#-KiVoMiLgCbBIRf5aWTo:-KiWbRp2XWkavlbCEDzw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ebbf80dcf43d4d01fbd199ddfa5a8783c8c9372/pkg/server/debug.go#L134)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'd get rid of ` (faster)`. That's not a distinction I think it is important to highlight. 
</blockquote></details>

Done.

---

*[pkg/server/problem_ranges.go, line 37 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15291#-KiWP61bzD7fv15qrQFT:-KiWbYq5o1Yz_R_IjrTU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ebbf80dcf43d4d01fbd199ddfa5a8783c8c9372/pkg/server/problem_ranges.go#L37)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Name this parameter `node_id` to be clear what kind of `id` it is.
</blockquote></details>

Done.

---

*[pkg/server/problem_ranges.go, line 69 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15291#-KiVq9CFOGKajcTeBd0L:-KiWbhVTQp389uSRLQwO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ebbf80dcf43d4d01fbd199ddfa5a8783c8c9372/pkg/server/problem_ranges.go#L69)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/aliveNodes/numNodes/g` as you don't actually know whether the node is alive or not. 
</blockquote></details>

Done.

---

*[pkg/server/problem_ranges.go, line 138 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15291#-KiVqdpXhrP20jpQEL9m:-KiWbkIhlnfOycw4jAGF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ebbf80dcf43d4d01fbd199ddfa5a8783c8c9372/pkg/server/problem_ranges.go#L138)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/cluster/Cluster/g`
</blockquote></details>

Done.

---

*[pkg/server/status.go, line 675 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15291#-KiVr5nUePpgagTJqLJB:-KiWcvEogWDjYZd1SzsQ:boso70e) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ebbf80dcf43d4d01fbd199ddfa5a8783c8c9372/pkg/server/status.go#L675)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You could call `rep.Metrics` inside `constructRangeInfo` and remove a bit of duplication.
</blockquote></details>

I moved the parsing of the metrics into constructRangeInfo. Moving the call to metrics in requires dealing with possibly passing other variables in as well.  Also this doesn't add any expensive calls within  the construct function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15291#-:-KiWbJpt0rseHAkj1cs1:b-hzh3q6)*

**Pull request merged**
