### PR TITLE
release-23.1: sql: improve how tracing of processors is done on the gateway node

### PR DESCRIPTION
**Pull request by yuzefovich**
Backport:
  * 1/1 commits from "sql: do not propagate contention events as processor metadata" (#98827)
  * 5/5 commits from "sql: improve how tracing of processors is done on the gateway node" (#98831)
  * 1/1 commits from "util/bulk: fix locking order in TracingAggregator" (#100667)
  * 1/1 commits from "util/bulk: remove now redundant mutex from TracingAggregator" (#100714)

Please see individual PRs for details.

/cc @cockroachdb/release

Release justification: low-risk observability improvement.

### CODE REVIEW

**Comment by yuzefovich** [comment]
Will wait for 23.1.1.

**Review by andreimatei — APPROVED** [review]
These patches actually fix a bug, right?

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100534#-:-NSCi__gDMcutj-FGbR8:b398e30)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Comment by yuzefovich** [comment]
> These patches actually fix a bug, right?

If by a "bug" you mean "losing the tracing spans hierarchy", then yes. But it doesn't seem like it's fixing a GA-blocker issue, so I'll hold this off for 23.1.0 (there is also #100562 which is likely to be introduced in this change that I have yet to look into).

**Comment by yuzefovich** [comment]
Note to self: include #100667 and #100714.

**Comment by yuzefovich** [comment]
This is RFAL. I guess Andrei's LGTM was invalidated since I added a couple more commits. @michae2 can you take a look please when you get a chance (not urgent).

**Comment by yuzefovich** [comment]
Friendly ping @michae2

**Comment by yuzefovich** [comment]
Friendly ping @michae2. Perhaps @DrewKimball you could take a look too? (I did get an approval from Andrei, but then three more commits were included, so that approval was discarded.)

**Review by DrewKimball — APPROVED** [review]
:lgtm:

Does this mean that the structured events for things like scan stats and RUs no longer have to be recorded in the trace? (except once when joinreaders etc. close). I've been worried about the overhead of passing these stats on every call into KV, and I really like the solution of using event listeners to consume events.

> Reviewed 3 of 12 files at r1, 67 of 67 files at r15, 4 of 4 files at r16, 41 of 41 files at r17, 15 of 15 files at r18, 11 of 11 files at r19, 8 of 8 files at r20, 2 of 2 files at r21, 2 of 2 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100534#-:-NWxcVSi5cw5Se5LQZ1U:b4o0tpo)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2)

**Comment by yuzefovich** [comment]
No, these events are still recorded as "structured events" and are included into the trace, this PR only changes how those events are processed for the purpose of the execution stats. Before this PR we would "analyze" the trace (namely, we'd iterate over all structured events, try to unmarshal each to the type that we're interested in, and then accumulate if unmarshaling succeeds), this is done after the trace is fully recorded; now we are analyzing each event at the moment when it's added to the trace (each listener checks whether the event is of its own type and accumulates it if so).

What you're saying though seems like a good idea to explore - if we don't need these events (like ScanStats and ConsumedRUs) be included in the trace (e.g. in the stmt bundle), then we could adjust the tracing infra to not include them into the trace as long as at least one EventListener consumed it. For ScanStats the overhead should be relatively minor as of #97442, so perhaps it's ConsumedRUs case we need to think about, and there we probably would be ok to drop those from the trace.

**Comment by michae2** [comment]
I'm sorry I have neglected this so long. Will try to get to it this weekend!

**Comment by yuzefovich** [comment]
Michael, no worries! No need to spend your weekend time on this :) Drew already gave an approval, and I don't think this change needs extra scrutiny (it has been sufficiently reviewed on master).

**Review by fqazi — APPROVED** [review]
Approving for the expectations file change

**Comment by yuzefovich** [comment]
Thanks all!

**Pull request merged**
