### PR TITLE
go.mod: bump pgx/v5 to 5.4.2

### PR DESCRIPTION
**Pull request by sean-**
Upgrade pgx from [v5.3.1 to v5.4.2](https://github.com/jackc/pgx/compare/v5.3.1...v5.4.2#files_bucket).

> Replace platform specific syscalls for non-blocking IO with more traditional goroutines and deadlines. This returns to the v4 approach with some additional improvements and fixes. This restores the ability to use a pgx.Conn over an ssh.Conn as well as other non-TCP or Unix socket connections. In addition, it is a significantly simpler implementation that is less likely to have cross platform issues.

Release note: none
Epic: none

### CODE REVIEW

**Comment by srosenberg** [comment]
What's the reason for the bump? Was there an observed issue with the current version?

**Comment by sean-** [comment]
Two principal reasons:

1. This change may reduce the amount of sys time
2. Bumping a non-`workload` workload generator's use of pgx from `v5.3.1` to `v5.4.2` reduced the frequency of `connection reset by peer` errors seen by client application code.

The `nbio` code is "new" to `pgx` ([`v5.0.0`](https://github.com/jackc/pgx/blob/master/CHANGELOG.md#v500-september-17-2022)) but present in the version that we've pinned ([`v5.3.1`](https://github.com/jackc/pgx/blob/master/CHANGELOG.md#540-june-14-2023)).  Given that `pgx` has moved back to the same code and mode of operation in the `v4` branch, this will reduce the likelihood of us chasing bugs in test results originating in client code (vs. being bugs in the product).

**Comment by srosenberg** [comment]
> 1. This change may reduce the amount of sys time
> 2. Bumping a non-`workload` workload generator's use of pgx from `v5.3.1` to `v5.4.2` reduced the frequency of `connection reset by peer` errors seen by client application code.

Thanks. Both changes seem like an improvement. I've triggered a smoke run with `SELECT_PROBABILITY=0.3` [1]. Assuming it checks out, we should be good to merge. Would you mind creating an annotation PR in [roachperf](https://github.com/cockroachdb/roachperf/)?

[1] https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11042109?buildTab=log&focusLine=2323&logView=linear

**Comment by sean-** [comment]
PR for annotation created in https://github.com/cockroachdb/roachperf/pull/138

**Comment by nicktrav** [comment]
Approving as a proxy for Stan, given his smoke test ran, and completed without issue.

**Review by nicktrav — APPROVED** [review]

**Pull request merged**
