### PR TITLE
server: switch to opt-out stats reporting

### PR DESCRIPTION
**Pull request by dt**
(still working out exactly how we want this to work, so this is a rough sketch for discussion)

Specifically, it’s opt-out of auto-out-in reporting: the setting defaults to false but, unless the user opts-out, we flip it to true during cluster creation.

If they want to, they can flip it to false at any time, just like any other setting.

Doing it this way (instead of just setting default to true) avoids the potential for a node to errantly use a default when it it hasn’t read settings for some reason (starting up, error cases) and then report. This might be an excess of caution, but we want to err on the side of respecting the user’s preference.

### CODE REVIEW

**Comment by dianasaur323** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14901#-:-KhcIlVIkbjgK0MZXDBc:bnfp4nl)*

**Comment by bdarnell** [comment]
LGTM

---

Reviewed 1 of 2 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/migrations/migrations.go, line 374 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14901#-Khrt6kELZfTVlMTFRbJ:-Khrt6kELZfTVlMTFRbK:b4xjbe4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef2ce5f6ede147765c06863d3b3e72d63b0c4e24/pkg/migrations/migrations.go#L374)):*
> ```Go
> 	}
> 
> 	// System tables can only be modified by a privileged internal user.
> ```

In a lot of our permission checks we give `node` and `root` equivalent permissions. We might want to do this for settings too so this could continue to be `node`. We want to avoid having nodes pretend to be the `root` client. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14901#-:-KhrtLhkJxlewJRDbvfj:bb6ywmx)*

**Comment by dt** [comment]
RFAL.

A simpler alternative here would be to stick with a (per-node) env var -- it would be more annoying to change it (you'd need to roll your nodes to apply the env var) but unlike some settings where we think using default might be okay when the value isn't available, this might be a case where cumbersome-but-predictable makes sense? It also seems unlikely someone would want to flip this on and off frequently.

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/migrations/migrations.go, line 374 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14901#-Khrt6kELZfTVlMTFRbJ:-KhxMiR9BcN0fnFSahEW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef2ce5f6ede147765c06863d3b3e72d63b0c4e24/pkg/migrations/migrations.go#L374)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

In a lot of our permission checks we give `node` and `root` equivalent permissions. We might want to do this for settings too so this could continue to be `node`. We want to avoid having nodes pretend to be the `root` client. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14901#-:-KhxMkGM-Jm3m_PnvUrR:bwwccf0)*

**Comment by dt** [comment]
Sketched out the simpler alternative in #15009.

**Comment by bdarnell** [comment]
LGTM.

I'd be OK with just using the env var too, but now that this is written I think it's good to keep it. You won't be turning it on and off frequently, but it may often be easier to set a setting than an env var across all nodes.

---

Reviewed 1 of 5 files at r4, 1 of 2 files at r5, 6 of 6 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14901#-:-Khy-c_oJWtS9pcXKFmJ:b-8d3ubb)*

**Comment by dt** [comment]
I have a slight preference for going with the simpler approach in #15009 and then coming back to this branch later, after some related pieces (like integrating verification of reported data into beta qualification, a non-flaky way to write tests that use gossiped settings, etc), but I could also see just going with this now to avoid having to communicate more than one change (though if the `migration` obeyed same env var, it would be a transparent transition). Either way works for me.

**Comment by bdarnell** [comment]
We're going to ask our users to tweak their configurations a lot with the next beta or two; I don't want to give instructions that will change a week later. We shouldn't flip the default to true until we have the opt-out interface that we will use for 1.0 in place.

**Comment by dt** [comment]
Since we're starting to accumulate some in-memory diagnostics data (e.g. the SQL timings) that this will soon be handling too, I switched this to a simpler loop variable for tracking when to report, rather than reading/writing report times to KV.

Also standardized on referring to this as "diagnostic reporting" everywhere, per discussion with @dianasaur323 .

**Comment by knz** [comment]
Reviewed 2 of 7 files at r7, 4 of 9 files at r8, 1 of 1 files at r9.
Review status: 6 of 10 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/migrations/migrations.go, line 366 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/14901#-Ki71FUSIatMS1dMxl1I:-Ki71FUSIatMS1dMxl1J:bwyc22) ([raw file](https://github.com/cockroachdb/cockroach/blob/d74f8d1bb3d39499d95c1f6ba770c6c96d64a3e3/pkg/migrations/migrations.go#L366)):*
> ```Go
> }
> 
> var reportingOptOut = envutil.EnvOrDefaultBool("COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING", false)
> ```

This dance with the env var and the migration feels too complicated to me.

What about:

1. the default value for the setting in the registry becomes `true`.
2. there is no migration.
3. there is no env var.
4. when upgrading, users can opt out explicitly prior to re-starting the node with the new version, namely `cockroach sql -e 'set cluster setting diagnostics.reporting = false'`

---

*[pkg/server/admin.go, line 62 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/14901#-Ki7-N0_Q8a-xPFOWRSD:-Ki7-N0_Q8a-xPFOWRSE:b-9pfrjx) ([raw file](https://github.com/cockroachdb/cockroach/blob/cebdb6464364f19a4ea2d6c522b28d04e4c4bed0/pkg/server/admin.go#L62)):*
> ```Go
> 	// serverUIDataKeyPrefix must precede all UIData keys that are read from the
> 	// server.
> 	serverUIDataKeyPrefix = "server."
> ```

Is this a base commit change? Otherwise it doesn't belong.

---

*[pkg/sql/authorization.go, line 64 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/14901#-Ki7-IhibzEGR1AHG4zB:-Ki7-Ihj12NOTh1t9aUM:b-dgqvb7) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ac54921c3e8ad41171fc484b8b2806b46b5bb9/pkg/sql/authorization.go#L64)):*
> ```Go
> // RequireSuperUser implements the AuthorizationAccessor interface.
> func (p *planner) RequireSuperUser(action string) error {
> 	if p.session.User != security.RootUser && p.session.User != security.NodeUser {
> ```

Please add a comment to clarify why you are doing this.

Also there is a typo in the title of the commit message.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14901)*

**Comment by dt** [comment]
Review status: 6 of 10 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/migrations/migrations.go, line 366 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/14901#-Ki71FUSIatMS1dMxl1I:-Ki721tlFVrWHfKfUWNS:b-32rbw3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d74f8d1bb3d39499d95c1f6ba770c6c96d64a3e3/pkg/migrations/migrations.go#L366)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This dance with the env var and the migration feels too complicated to me.

What about:

1. the default value for the setting in the registry becomes `true`.
2. there is no migration.
3. there is no env var.
4. when upgrading, users can opt out explicitly prior to re-starting the node with the new version, namely `cockroach sql -e 'set cluster setting diagnostics.reporting = false'`
</blockquote></details>

nope: remember, a node uses default values until it gets a gossip update, and will fall back to them if it can't read gossiped values for any reason. a default of false fails safe (don't violate user's trust) but a default of true doesn't.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14901)*

**Comment by knz** [comment]
Reviewed 1 of 5 files at r4, 1 of 7 files at r7, 4 of 9 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/migrations/migrations.go, line 366 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/14901#-Ki71FUSIatMS1dMxl1I:-Ki72sP5GR2t3xCk2rNf:bo73nkf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d74f8d1bb3d39499d95c1f6ba770c6c96d64a3e3/pkg/migrations/migrations.go#L366)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

nope: remember, a node uses default values until it gets a gossip update, and will fall back to them if it can't read gossiped values for any reason. a default of false fails safe (don't violate user's trust) but a default of true doesn't.
</blockquote></details>

Hmm I see, then please add a comment in `settings/doc.go` that explains the general design pattern (I suspect we'll be doing that a few times more, and I'd expect this explanation to be reusable.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14901)*

**Comment by dt** [comment]
Review status: 1 of 11 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/server/admin.go, line 62 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/14901#-Ki7-N0_Q8a-xPFOWRSD:-Ki7300JwRF7c0wzisWt:bk5upfk) ([raw file](https://github.com/cockroachdb/cockroach/blob/cebdb6464364f19a4ea2d6c522b28d04e4c4bed0/pkg/server/admin.go#L62)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Is this a base commit change? Otherwise it doesn't belong.
</blockquote></details>

`serverUIDataKeyPrefix` is unused after I deleted the code that used it.

---

*[pkg/sql/authorization.go, line 64 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/14901#-Ki7-IhibzEGR1AHG4zB:-Ki7788zEKwHm5uk7zE1:b-oqvdek) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ac54921c3e8ad41171fc484b8b2806b46b5bb9/pkg/sql/authorization.go#L64)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please add a comment to clarify why you are doing this.

Also there is a typo in the title of the commit message.
</blockquote></details>

what did you want clarified? not sure what to say other than "node and root are super the users" ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14901)*

**Comment by dt** [comment]
Review status: 1 of 11 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/migrations/migrations.go, line 366 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/14901#-Ki71FUSIatMS1dMxl1I:-Ki78AOq7OuLyv6W2J74:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d74f8d1bb3d39499d95c1f6ba770c6c96d64a3e3/pkg/migrations/migrations.go#L366)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Hmm I see, then please add a comment in `settings/doc.go` that explains the general design pattern (I suspect we'll be doing that a few times more, and I'd expect this explanation to be reusable.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14901)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/authorization.go, line 64 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/14901#-Ki7-IhibzEGR1AHG4zB:-Ki78_Vgi6kdrhgIn5pS:buzjn63) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ac54921c3e8ad41171fc484b8b2806b46b5bb9/pkg/sql/authorization.go#L64)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

what did you want clarified? not sure what to say other than "node and root are super the users" ?
</blockquote></details>

Ok, on second read it's easier to understand. I'm fine as-is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14901#-:-Ki78k6ub5RusF1Bir9r:bnfp4nl)*

**Pull request merged**
