### PR TITLE
release: update roachtest predecessor_version to 22.1.19

### PR DESCRIPTION
**Pull request by THardy98**
Part of: REL-327
Release note: None

### CODE REVIEW

**Review by rail — APPROVED** [review]

**Comment by THardy98** [comment]
@rail `TestBackupTenantImportingTable` seems to keep failing on Bazel Essential CI. Not related to this change, but wondering if this is of concern (generally)?

**Comment by rail** [comment]
Let me rerun it again. Doesn't look related, probably a flake...

**Comment by THardy98** [comment]
looks like it passed this time, sweet.
TYFR :)

**Pull request merged**
