### PR TITLE
distsql: implement distributed DISTINCT

### PR DESCRIPTION
**Pull request by irfansharif**
Implementation of the `Distinct` processor core type, pretty trivial. Can't think of a verb form for `distinct`, `distinguisher` seems off but no strong opinions here. Sent this PR out now for early review, now writing out the optimizations for pre-existing ordering in the input rows taking advantage of the fact that the `seen` set can be reset whenever we find consecutive rows differing on a `prefix` comprised of ordered columns.

Part of #7587.
cc @RaduBerinde, @andreimatei

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10034)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/distsql/distinct.go, line 125 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10034#-KUJjk_FdjPUcd1YR2Ba:-KUJjk_GkFrvAX8r_7zW:bmtuuxv) ([raw file](https://github.com/cockroachdb/cockroach/blob/008d3ceb35a3c1092b643eb9d6572ff1d678bb37/pkg/sql/distsql/distinct.go#L125)):*
> ```Go
> 	}
> 
> 	return sqlbase.EncodeDTuple(b, d.tuple)
> ```

`EncDatum` has an `Encode` function. Using that instead of going to a `Tuple` and `EncodeDTuple` can be more efficient - the desired encoding matches the one we already have, we can avoid decoding and reencoding.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10034#-:-KUJkqlYAWGbG-rkGAGt:bnfp4nl)*

**Comment by irfansharif** [comment]
TFTR, pulling it in now.

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsql/distinct.go, line 125 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10034#-KUJjk_FdjPUcd1YR2Ba:-KUNjcuweYjfLQdeY7Sq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/008d3ceb35a3c1092b643eb9d6572ff1d678bb37/pkg/sql/distsql/distinct.go#L125)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> `EncDatum` has an `Encode` function. Using that instead of going to a `Tuple` and `EncodeDTuple` can be more efficient - the desired encoding matches the one we already have, we can avoid decoding and reencoding.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10034#-:-KUNjeXfkN7eY4HXmGV7:b-f3gf9y)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/distsql/distinct.go, line 118 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10034#-KUNwifFdDSvfsO2ROsF:-KUNwifFdDSvfsO2ROsG:b-qo6a6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/83d715f3b97ad67c994440c24b1502d7735ed293/pkg/sql/distsql/distinct.go#L118)):*
> ```Go
> 		enc, ok := row[col].Encoding()
> 		if !ok {
> 			return nil, errors.Errorf("encoding not available for %s", row[col])
> ```

We need to fix an encoding for each column and always use that. Different rows may come with different encodings, e.g. if they come from different streams that were merged. Then the encodings won't match. Also, this no-encoding case is legitimate - e.g. a new result from an Evaluator will have a Datum but no encoding.

It's ok for now to just always choose `DatumEncoding_VALUE` with a TODO to maybe check the first row for what encodings are already available.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10034)*

**Comment by irfansharif** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql/distinct.go, line 118 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10034#-KUNwifFdDSvfsO2ROsF:-KUNy-Y9ipax7RmL5tZZ:b-na16q7) ([raw file](https://github.com/cockroachdb/cockroach/blob/83d715f3b97ad67c994440c24b1502d7735ed293/pkg/sql/distsql/distinct.go#L118)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> We need to fix an encoding for each column and always use that. Different rows may come with different encodings, e.g. if they come from different streams that were merged. Then the encodings won't match. Also, this no-encoding case is legitimate - e.g. a new result from an Evaluator will have a Datum but no encoding.
> 
> It's ok for now to just always choose `DatumEncoding_VALUE` with a TODO to maybe check the first row for what encodings are already available.
> 
</details>
will update this with the partial ordering optimization PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10034)*

**Pull request merged**
