### PR TITLE
kv: don't gossip node liveness on lease extensions

### PR DESCRIPTION
**Pull request by nvb**
Informs: #97966

Before this change, we would gossip the entire node liveness range on each liveness lease extension (every few seconds). In cases where the liveness range is full of garbage, we have seen that this can be expensive.

This change updates the post-lease change hook to only gossip all liveness records on lease changes, never on lease extensions. This is possible because there is no risk of lost incremental liveness updates on lease extensions.

Release note: None

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
Thanks! Doesn't seem great that we were spawning these tasks for every lease acquisition either.

**Comment by nvanbenschoten** [comment]
bors r=erikgrinaker

**Review by andrewbaptist — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98150)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/replica_proposal.go` line 439 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98150#-NQ0opcU6IGjLhkKymK8:-NQ0opcU6IGjLhkKymK9:bqjv2bp) ([raw file](https://github.com/cockroachdb/cockroach/blob/17110284751a94a7dd4b2f986c1d649994c6baad/pkg/kv/kvserver/replica_proposal.go#L439)):*
> ```Go
> 	// the latest view of node liveness ends up in gossip.
> 	nls := keys.NodeLivenessSpan
> 	if leaseChangingHands && iAmTheLeaseHolder && kvserverbase.ContainsKeyRange(r.descRLocked(), nls.Key, nls.EndKey) {
> ```

nit: Does this assume that the liveness key range is never split? I don't think we will change this, but it seems overly strict. Should we instead use `IntersectSpan`? If the range is split I think we would want to do this for any parts we are the leaseholder for.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98150)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[`pkg/kv/kvserver/replica_proposal.go` line 439 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98150#-NQ0opcU6IGjLhkKymK8:-NQ14CWBEPz78AKQtATv:b-7pjqa0) ([raw file](https://github.com/cockroachdb/cockroach/blob/17110284751a94a7dd4b2f986c1d649994c6baad/pkg/kv/kvserver/replica_proposal.go#L439)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: Does this assume that the liveness key range is never split? I don't think we will change this, but it seems overly strict. Should we instead use `IntersectSpan`? If the range is split I think we would want to do this for any parts we are the leaseholder for.
</blockquote></details>

That's a good point, this is overly strict. We have the same check in `MaybeGossipNodeLivenessRaftMuLocked`, so I'll leave this as is for now, but we should consider switching both over to something less strict. If we do though, we need to make sure that we only gossip keys in the span that's part of the local replica.

**Pull request merged**
