### PR TITLE
server: one way to get a TestServer to rule them all

### PR DESCRIPTION
**Pull request by andreimatei**
See the individual commits.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7614)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Reviewed first commit. Nice! Just one comment.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7614#-:-KM6GGePKdaoy8U917q_:18800676)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 65 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/testingshim/test_server_shim.go, line 132 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7614#-KM6EPrCyC1Fd-szHJiX:-KM6EPrCyC1Fd-szHJiY:-1638287840) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf5aeb3c8c064fa976ed5c5a6331078dee84c6c8/server/testingshim/test_server_shim.go#L132)):*
> ```Go
> // Generally sqlutils.SetupServer() should be used. However this function can be
> // used directly when opening a connection to the server is not desired.
> func StartServerRaw(params TestServerParams) (TestServerInterface, error) {
> ```

I think this functionality should also be provided by a wrapper in sqlutils, maybe `sqlutils.SetupServerNoConn()`. The wrapper could return a `*server.TestServer` directly.

That way we can document that this function should never be used directly, which would be great (reduced usage of `testingshim`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7614)*

**Comment by RaduBerinde** [comment]
*[server/testingshim/test_server_shim.go, line 132 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7614#-KM6EPrCyC1Fd-szHJiX:-KM6HlFS11WSnzfZZO-u:-1132033043) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf5aeb3c8c064fa976ed5c5a6331078dee84c6c8/server/testingshim/test_server_shim.go#L132)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I think this functionality should also be provided by a wrapper in sqlutils, maybe `sqlutils.SetupServerNoConn()`. The wrapper could return a `*server.TestServer` directly.
> 
> That way we can document that this function should never be used directly, which would be great (reduced usage of `testingshim`).
</details>
Ah - I see that in the second commit we actually move `StartServer` here. So disregard the above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7614)*

**Comment by RaduBerinde** [comment]
Awesome!  :lgtm_strong: 

---

Review status: 0 of 65 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/testingshim/test_server_shim.go, line 138 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7614#-KM6MCnqKoPOWzgeutlf:-KM6MCnqKoPOWzgeutlg:1127043789) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf5aeb3c8c064fa976ed5c5a6331078dee84c6c8/server/testingshim/test_server_shim.go#L138)):*
> ```Go
> 	}
> 	server := serviceImpl.New(params)
> 	return server, server.Start(params)
> ```

Maybe check the error and return `nil, err` instead of "leaking out" an unstarted server in the error case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7614#-:-KM6LC886rcMLalfLjZ5:-241110287)*

**Comment by andreimatei** [comment]
Review status: 0 of 65 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/testingshim/test_server_shim.go, line 138 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7614#-KM6MCnqKoPOWzgeutlf:-KMAKVZMf6CQv_K-w9H0:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf5aeb3c8c064fa976ed5c5a6331078dee84c6c8/server/testingshim/test_server_shim.go#L138)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Maybe check the error and return `nil, err` instead of "leaking out" an unstarted server in the error case.
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7614)*

**Pull request merged**
