### PR TITLE
rac2: increase test coverage for constructRaftEventForReplica

### PR DESCRIPTION
**Pull request by sumeerbhola**
Informs #130433

Epic: CRDB-37515

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
added these after editing range_controller.go to break apart the long expression in
```
				// First disjunct is true if there is a regression or forward jump in
				// the send-queue.
				if existingSendStreamState.indexToSend != msgAppFirstIndex ||
					// Unclear if the following can ever occur, but we are being
					// defensive.
					latestReplicaStateInfo.Next != msgAppUBIndex ||
					msgAppFirstIndex > raftEventAppendState.rewoundNextRaftIndex ||
					msgAppUBIndex > lastNewEntryIndex {
					createSendStream = true
				}
```
and looking at test coverage.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131591#-:-O82BklfCSw7UsOAhQ3r:b-cnhp6q)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131591#-:-O82D479BmW1rsqEKT8v:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv)

**Comment by sumeerbhola** [comment]
TFTR!

**Comment by sumeerbhola** [comment]
bors r=kvoli

**Pull request merged**
