### PR TITLE
opt: fix partial index implication for prepared statements

### LINKED ISSUE #66465: Partial indexes doesn't work well with prepared statements
**Describe the problem**

When partial index hinted to be used within prepared `UPDATE` statement query refuses to be executed with error: `<index_name> is a partial index that does not contain all the rows needed to execute this query` while the same query without preparation works well.

**To Reproduce**

*1. Create table with partial index*

```sql
CREATE TABLE partial_index_test (
  id      UUID NOT NULL PRIMARY KEY,
  meta    JSONB NOT NULL default '{}',
  flag    BOOL NOT NULL,
  at      TIMESTAMPTZ NOT NULL
);

CREATE INDEX my_partial_idx ON partial_index_test (at) WHERE (meta -> 'test') = '1'
```

*2. Try to run query without preparation*
```sql
UPDATE partial_index_test@my_partial_idx
SET meta = jsonb_set(
  meta,
  ARRAY['partial_index'],
  '"working"'::JSONB
)
WHERE (meta -> 'test') = '1'
AND at >= now();
```
```sql
UPDATE partial_index_test@my_partial_idx
SET flag = true
WHERE (meta -> 'test') = '1'
AND at >= now();
```
```sql
SELECT id FROM partial_index_test@my_partial_idx
WHERE (meta -> 'test') = '1'
AND at <= now();
```

And all of them just work.

*3. But if this queries are prepared*
```sql
PREPARE prep1 AS UPDATE partial_index_test@my_partial_idx
SET meta = jsonb_set(
  meta,
  ARRAY['partial_index'],
  '"working"'::JSONB
)
WHERE (meta -> 'test') = '1'
AND at >= now();

EXECUTE prep1
```

```sql
PREPARE prep2 AS UPDATE partial_index_test@my_partial_idx
SET flag = true
WHERE (meta -> 'test') = '1'
AND at >= now();

EXECUTE prep2
```

```sql
PREPARE prep3 AS SELECT id FROM partial_index_test@my_partial_idx
WHERE (meta -> 'test') = '1'
AND at <= now();

EXECUTE prep3;
```

Error: `my_partial_idx is a partial index that does not contain all the rows needed to execute this query` is thrown.

**Expected behavior**

Prepared and not prepared statements behave identically.

**Environment:**
 - CockroachDB version: 21.1.1

**Additional context**
`SELECT` also partially affected by this issue but in some cases it just works, I'll extend this issue with `SELECT` example after find one. 

P.S. Extended with `SELECT` example, and tested more statements, prepared statements working well with hinted partial index while it contains only constant values. For example this works fine:
```sql
PREPARE prep9 AS 
SELECT id FROM partial_index_test@my_partial_idx
WHERE (meta -> 'test') = '1'
AND at::bigint <= 100000;

EXECUTE prep9;
```

### PR DESCRIPTION
**Pull request by mgartner**
To prove that a filter implies a partial index predicate, the partial
index implicator relies on the assumption that equivalent scalar
expressions have the same memory address. Normally, this invariant is
guaranteed by the interner. However, it was being violated for some
prepared statements.

When preparing a statement with a placeholder, or a stable function or
cast, the optimizer performs normalization but not exploration. The
normalized memo is cached along with metadata that contains the partial
index predicate scalar expressions. The interner is not cached.

When the prepared statement is executed, the cached memo's root
expression and metadata are copied and exploration is performed.
Previously, the scalar expressions in the metadata (constraints,
computed column expressions, and partial index predicates) were reused,
not copied. So while the scalar expressions copied from the memo's root
expression had new memory addresses allocated by the new interner, the
scalar expressions in the metadata had memory addresses allocated by the
old interner during the `PREPARE` phase. This violated the invariant and
prevented the partial index implicator from proving that a partial index
could be used to satisfy a query during the `EXECUTE` phase.

This commit fixes the issue by copying the scalar expressions in the
metadata using the new interner, rather than reusing the expressions
that were built during the `PREPARE` phase. The memory addresses of
equivalent scalar expressions in the memo's metadata and root expression
are now guaranteed to be the same because the same interner is used to
copy both.

Fixes #66465

Release note (bug fix): A bug has been fixed which prevented the
optimizer from producing plans with partial indexes when executing some
prepared statements that contained placeholders, or stable functions or
casts. This bug was present since partial indexes were added in version
20.2.0.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: nice find!

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66571#-:-McPRPOH3sB81Gaf4yLZ:b-klf2oc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @mgartner, and @RaduBerinde)

___
*[pkg/sql/opt/metadata.go, line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66571#-McPPppN0a8PuCeAZYPD:-McPPppN0a8PuCeAZYPE:b-x3uhs0) ([raw file](https://github.com/cockroachdb/cockroach/blob/689018872a9aba9ae031cbb8290f6de627b27bd2/pkg/sql/opt/metadata.go#L203)):*
> ```Go
> // copyScalar must be a function that returns a copy of the given scalar
> // expression.
> func (md *Metadata) CopyFrom(from *Metadata, copyScalar func(Expr) Expr) {
> ```

Is this ever called with a function other than `CopyScalarWithoutPlaceholders`? If not, I guess you probably did this to avoid dependency cycles? Another way to handle this that might be better is to define a callback function and assign it with `init()`, like we did here: https://github.com/cockroachdb/cockroach/blob/bc95d8f5e79576e38208b89af65a2050ab52b982/pkg/sql/opt/memo/expr_format.go#L1348 and here: https://github.com/cockroachdb/cockroach/blob/e0499335c7330e2453ffdee72bda07988eb1d486/pkg/sql/opt/ordering/scan.go#L157.
___
*[pkg/sql/opt/table_meta.go, line 180 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66571#-McPOVkr3QyW_V6ok5Lj:-McPOVksCE6ioTRGZXo-:balhn4b) ([raw file](https://github.com/cockroachdb/cockroach/blob/689018872a9aba9ae031cbb8290f6de627b27bd2/pkg/sql/opt/table_meta.go#L180)):*
> ```Go
> 
> // copyScalars replaces all scalar expressions in the table metadata with a copy
> // that is generated by the scalarCopy function. This is used when copying a
> ```

nit: scalarCopy -> copyScalar

**Review by RaduBerinde — APPROVED** [review]
:lgtm: This came out pretty clean.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66571#-:-McPuVPZB9AfPMWHSKhy:b-44gcl6)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andy-kimball and @mgartner)

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66571)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andy-kimball and @rytaft)

___
*[pkg/sql/opt/metadata.go, line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66571#-McPPppN0a8PuCeAZYPD:-McQ49MH7weZHKs9XcTU:b7zgzfu) ([raw file](https://github.com/cockroachdb/cockroach/blob/689018872a9aba9ae031cbb8290f6de627b27bd2/pkg/sql/opt/metadata.go#L203)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Is this ever called with a function other than `CopyScalarWithoutPlaceholders`? If not, I guess you probably did this to avoid dependency cycles? Another way to handle this that might be better is to define a callback function and assign it with `init()`, like we did here: https://github.com/cockroachdb/cockroach/blob/bc95d8f5e79576e38208b89af65a2050ab52b982/pkg/sql/opt/memo/expr_format.go#L1348 and here: https://github.com/cockroachdb/cockroach/blob/e0499335c7330e2453ffdee72bda07988eb1d486/pkg/sql/opt/ordering/scan.go#L157.
</blockquote></details>

I don't think that approach works here, because `CopyScalarWithoutPlaceHolders` uses a Factory instance, so we can't set a "static" copy function at `init`-time.
___
*[pkg/sql/opt/table_meta.go, line 180 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66571#-McPOVkr3QyW_V6ok5Lj:-McQ3quVEnqTvBkgR5lC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/689018872a9aba9ae031cbb8290f6de627b27bd2/pkg/sql/opt/table_meta.go#L180)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: scalarCopy -> copyScalar
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66571#-:-McQnkEYEkLRZtpXPYFO:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball)

___
*[pkg/sql/opt/metadata.go, line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66571#-McPPppN0a8PuCeAZYPD:-McQngJy-9UPrw-qs1Fc:bt2hk4r) ([raw file](https://github.com/cockroachdb/cockroach/blob/689018872a9aba9ae031cbb8290f6de627b27bd2/pkg/sql/opt/metadata.go#L203)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't think that approach works here, because `CopyScalarWithoutPlaceHolders` uses a Factory instance, so we can't set a "static" copy function at `init`-time.
</blockquote></details>

Ah ok makes sense.

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
