### PR TITLE
release-20.1: heapprofiler: properly preserve heap dumps, refactor some code

### LINKED ISSUE #50237: server:   heap profiler GC removes the wrong files
So there's logic to "garbage collect" heap profiler files so there's always no more than N files in the directory, configurable via cluster setting `"server.heap_profile.max_profiles"` (default 5)

The code is implemented in `(o *HeapProfiler) gcProfiles()`

This code has two **major** flaws:

- **it does not sort the files** and instead uses the directory order (FS-dependent / OS-dependent) to decide which files to remove

- **it removes files indiscriminately of type**

I can see in my cluster of interest that I have 5 files:

```
memprof.000000001448318504_2020-06-11T10_57_35.202.pprof
memprof.fraction_system_memory.000000019154821120_2020-06-05T13_22_13.241.pprof
memprof.fraction_system_memory.000000019331059712_2020-03-04T16_58_39.54.pprof
memprof.fraction_system_memory.000000019349680128_2020-06-05T13_26_32.349.pprof
memprof.fraction_system_memory.000000020150149120_2020-06-05T09_25_25.637.pprof
```

The 4 "fraction_system_memory" are from v19.1, this format is not used any more in v19.2. However, they count in the determination of which files to remove. The result is (for this cluster) that there is always at most one up to date pprof file remaining.

### PR DESCRIPTION
**Pull request by knz**
Requested by #53412

Backport 11/12 commits from #50446.
Backport 1/1 commits from #55364.
Backport 1/1 commits from #55630

/cc @cockroachdb/release

---

Fixes #50237 

See the individual commits for details.

### CODE REVIEW

**Review by andreimatei — APPROVED** [review]
:lgtm: unless you can think of anything... smaller... to backport to make the profiler suck less.

But I do wonder below about skipping what appears to be a random test.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55260#-:-MIzjXim-qtKB_qkQOFr:binbh7x)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

___
*[pkg/sql/distsql/columnar_operators_test.go, line 42 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/55260#-MIzifQk8vlrrMatWTsa:-MIzifQk8vlrrMatWTsb:bokezoz) ([raw file](https://github.com/cockroachdb/cockroach/blob/48c134fd9b3a4db64b94b55b4e8fee7166e050a6/pkg/sql/distsql/columnar_operators_test.go#L42)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 
> 	skip.WithIssue(t, 52742, "flaky")
> ```

this issue has been apparently fixed by https://github.com/cockroachdb/cockroach/commit/04be991de228af541c191f81f71a8b0ce5d19f19

What's up with this test in this PR?

**Comment by knz** [comment]
waiting on #55630 to merge this

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55260)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei)

___
*[pkg/sql/distsql/columnar_operators_test.go, line 42 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/55260#-MIzifQk8vlrrMatWTsa:-MJlZ0JwDw_bV0jt3apA:bz016y1) ([raw file](https://github.com/cockroachdb/cockroach/blob/48c134fd9b3a4db64b94b55b4e8fee7166e050a6/pkg/sql/distsql/columnar_operators_test.go#L42)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this issue has been apparently fixed by https://github.com/cockroachdb/cockroach/commit/04be991de228af541c191f81f71a8b0ce5d19f19

What's up with this test in this PR?
</blockquote></details>

This was a stray commit. Removed it from the PR.

**Comment by joshimhoff** [comment]
Anything blocking merging this? SRE so so excited to see those heap profiles.

**Comment by knz** [comment]
Ben suggested we waited to confirm that this works well with 20.2 in prod for a bit before we let it go to 20.1. what do you think?

**Comment by joshimhoff** [comment]
I don't have a good sense of the risks of this backport, but they are SO many OOMs for which we don't get a root cause today, and that makes me sad, so I'm excited to get this running on CC (which shall remain largely 20.1 for a while).

> Ben suggested we waited to confirm that this works well with 20.2 in prod for a bit before we let it go to 20.1. what do you think?

Are we waiting to make sure this PR doesn't cause stability problems somehow? Or are we waiting to make sure it works as expected, that is, there are profiles saved in more cases?

I'm guessing we mean the former. If former, I don't understand the stability risks posed by this backport concretely. Interested in understanding it though if you can say more!

**Comment by knz** [comment]
> Are we waiting to make sure this PR doesn't cause stability problems somehow? Or are we waiting to make sure it works as expected, that is, there are profiles saved in more cases?

Both, if my understanding is correct.

**Comment by knz** [comment]
I'm going to go ahead with this as we don't seem to see 20.2 falling over due to this code.

**Pull request merged**
