### PR TITLE
bazel: add dev roachprod-bench-wrapper command

### LINKED ISSUE #90837: dev: build portable test binaries for microbenchmarks
We currently use the `benchdiff` tool [1] for comparing microbenchmarks for releases. This tool builds the test binaries using `go` directly and is unaware of the `Bazel runfiles` concept [2] that can specify data required during tests. `Bazel` does the management of this data during execution, but it becomes more troublesome if only the binary is copied.

Hence it would be useful to add a command to `dev` to easily produce portable test binaries, with its data, given a package name wildcard, using `Bazel`. This is a precursor to being able to distribute the test binaries to a cluster for running parallel benchmarks.

[1] https://github.com/nvanbenschoten/benchdiff
[2] https://bazel.build/extending/rules#runfiles

Jira issue: CRDB-20966

Epic CRDB-20903

### PR DESCRIPTION
**Pull request by herkolategan**
Add command roachprod-bench-wrapper to dev. The command will build all the test
binaries for a given set of packages, using Bazel. Any runfiles required by the
binaries will also be staged. Binaries and runfiles are added to a tar in
artifacts and can be optionally compressed. The output is portable without being
dependent on the repository.

Each package is supplied with a run script that will set up environment variables
for Bazel runfiles to be used by the test binary.

Additionally, this builds the binary for a sub command roachprod-bench that will
orchestrate the execution of the binaries. The sub command is also executed by
the roachprod-bench command with specified arguments passed to it.

Resolves: #90837
See also: #90958

Epic: CRDB-20903

Release justification: test-only change.
Release note: None

### CODE REVIEW

**Review by srosenberg — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91144)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

___
*[`pkg/cmd/dev/roachprod_bench.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NGcH4t9CgV9pldnwiJc:-NGcH4t9CgV9pldnwiJd:bto46jh) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bdab024723d8dbb209ad24d4e453afcd394f85/pkg/cmd/dev/roachprod_bench.go#L32)):*
> ```Go
> 	benchArgsFlag = "bench-args"
> 	compressFlag  = "compress"
> 	batchSize     = 128
> ```

Should this be exposed as a CLI arg.?
___
*[`pkg/cmd/dev/roachprod_bench.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NGcA5p_6PmFQDr7HWQb:-NGcA5p_6PmFQDr7HWQc:b8fm0o8) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bdab024723d8dbb209ad24d4e453afcd394f85/pkg/cmd/dev/roachprod_bench.go#L38)):*
> ```Go
> 	roachprodBenchCmd := &cobra.Command{
> 		Use:     "roachprod-bench <pkg>",
> 		Short:   "run the given benchmarks on the given roachprod cluster",
> ```

Let's try to be more helpful to the end-user by referring to the actual command for further documentation; also, benchmarks is ambiguous since we have many types (e.g., roachperf tests are benchmarks too). How about something like this?

```
invokes pkg/cmd/roachprod-bench to parallelize execution of specified microbenchmarks
```
___
*[`pkg/cmd/dev/roachprod_bench.go` line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NGcAwn4Do98g-EkBnDZ:-NGcAwn4Do98g-EkBnD_:b5twei9) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bdab024723d8dbb209ad24d4e453afcd394f85/pkg/cmd/dev/roachprod_bench.go#L40)):*
> ```Go
> 		Short:   "run the given benchmarks on the given roachprod cluster",
> 		Long:    "run the given benchmarks on the given roachprod cluster.",
> 		Example: `dev roachprod-bench ./pkg/sql/importer --cluster my_cluster`,
> ```

I find it confusing that the `dev` wrapper has the same name as the actual command doing the heavy lifting. Could we perhaps rename this to `roachprod-bench-wrapper`?
___
*[`pkg/cmd/dev/roachprod_bench.go` line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NGcBL262Cbr29R40yti:-NGcBL262Cbr29R40ytj:b-10i5pq) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bdab024723d8dbb209ad24d4e453afcd394f85/pkg/cmd/dev/roachprod_bench.go#L69)):*
> ```Go
> 
> 	if cluster == "" {
> 		return fmt.Errorf("must provide --cluster (you can create one via: `roachprod create $USER-bench -n 8 --gce-machine-type=n2d-standard-8 --local-ssd=true`)")
> ```

Nit: `you can create one` --> `e.g.,` (fewer chars to parse :)
___
*[`pkg/cmd/dev/roachprod_bench.go` line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NGcBa-401theXz-7Sdk:-NGcBa-401theXz-7Sdl:b-2xpwgd) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bdab024723d8dbb209ad24d4e453afcd394f85/pkg/cmd/dev/roachprod_bench.go#L74)):*
> ```Go
> 	packages, testArgs := splitArgsAtDash(cmd, commandLine)
> 	if len(packages) != 1 {
> 		return fmt.Errorf("must provide a test (benchmark) target like ./pkg/cmd/dev or ./pkg/util/... for a wildcard match")
> ```

Nit: assume the end-user is familiar with idiomatic go glob `...`;  something like this,

```
expected a single benchmark target specification; e.g., ./pkg/cmd/dev or ./pkg/util/...
```
___
*[`pkg/cmd/dev/roachprod_bench.go` line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NGcDkiG-oQmnIR2YBx6:-NGcDkiG-oQmnIR2YBx7:b-50kidv) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bdab024723d8dbb209ad24d4e453afcd394f85/pkg/cmd/dev/roachprod_bench.go#L102)):*
> ```Go
> 	}
> 
> 	// Generate a unique build hash for the given targets and git revision.
> ```

Shouldn't we bail out when `testTargets` is empty?
___
*[`pkg/cmd/dev/roachprod_bench.go` line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NGcGCuz-URPU0Wj-y1g:-NGcGCuz-URPU0Wj-y1h:b-gpivza) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bdab024723d8dbb209ad24d4e453afcd394f85/pkg/cmd/dev/roachprod_bench.go#L108)):*
> ```Go
> 	}
> 	gitRevision := strings.TrimSpace(string(stdout))
> 	buildHash := md5.New()
> ```

Nit: I am surprised to see `md5` is still widespread almost two decades later after first collisions were published. Even `bazel` uses `md5` to derive output directory, but everything else is on `sha256` afaik.
___
*[`pkg/cmd/dev/roachprod_bench.go` line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NGcHGJP00SOHD_vRCfQ:-NGcHGJP00SOHD_vRCfR:b5fqkwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bdab024723d8dbb209ad24d4e453afcd394f85/pkg/cmd/dev/roachprod_bench.go#L143)):*
> ```Go
> 			crossArgs = append(crossArgs, "--config=race")
> 		}
> 		err = d.crossBuildTests(ctx, crossArgs, targets, "crosslinux", volume, outputPrefix)
> ```

Could we parameterize this if only to make it future-proof against `arm64`?
___
*[`pkg/cmd/dev/roachprod_bench.go` line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NGcHwUk7WCBRaO0f_YD:-NGcHwUl3KxewHyICwgW:b-3i24bh) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bdab024723d8dbb209ad24d4e453afcd394f85/pkg/cmd/dev/roachprod_bench.go#L155)):*
> ```Go
> 	}
> 
> 	if comress {
> ```

`compress`
___
*[`pkg/cmd/dev/roachprod_bench.go` line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NGcIQ6EAdDY12XGJy90:-NGcIQ6EAdDY12XGJy91:b-ppgmgx) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bdab024723d8dbb209ad24d4e453afcd394f85/pkg/cmd/dev/roachprod_bench.go#L158)):*
> ```Go
> 		log.Printf("Compressing output, this might take a while...")
> 		// Requires pigz (parallel gzip) to be installed on the system.
> 		compressionProgram := "pigz"
> ```

We now have a go-native analogue of it (i.e., `pgzip` [1]); might be worth replacing since not a lot of folks will have `pigz` locally installed.

[1] https://github.com/cockroachdb/cockroach/blob/45abe9112aa3972aabdc5c0fcca70e767fdb1cfc/pkg/ccl/changefeedccl/compression.go#L51
___
*[`pkg/cmd/dev/roachprod_bench.go` line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NGcJ1OTDvjefKxrvUjP:-NGcJ1OTDvjefKxrvUjQ:b-3t9w9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bdab024723d8dbb209ad24d4e453afcd394f85/pkg/cmd/dev/roachprod_bench.go#L227)):*
> ```Go
> 	// Construct a script that builds the binaries and copies them
> 	// to the appropriate location in /artifacts.
> 	var script strings.Builder
> ```

It might improve readability to use a template, e.g., https://github.com/cockroachdb/cockroach/blob/45abe9112aa3972aabdc5c0fcca70e767fdb1cfc/pkg/roachprod/install/cockroach.go#L414

**Review by herkolategan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91144)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs and @srosenberg)

___
*[`pkg/cmd/dev/roachprod_bench.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NGcH4t9CgV9pldnwiJc:-NH06e9lArkrqpxPHCcV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bdab024723d8dbb209ad24d4e453afcd394f85/pkg/cmd/dev/roachprod_bench.go#L32)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Should this be exposed as a CLI arg.?
</blockquote></details>

Done.
___
*[`pkg/cmd/dev/roachprod_bench.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NGcA5p_6PmFQDr7HWQb:-NH06oby9HzVxKpd4-xw:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bdab024723d8dbb209ad24d4e453afcd394f85/pkg/cmd/dev/roachprod_bench.go#L38)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Let's try to be more helpful to the end-user by referring to the actual command for further documentation; also, benchmarks is ambiguous since we have many types (e.g., roachperf tests are benchmarks too). How about something like this?

```
invokes pkg/cmd/roachprod-bench to parallelize execution of specified microbenchmarks
```
</blockquote></details>

Good idea, done.
___
*[`pkg/cmd/dev/roachprod_bench.go` line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NGcAwn4Do98g-EkBnDZ:-NH06rzZ0SlkedSzjolz:b-yz6shl) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bdab024723d8dbb209ad24d4e453afcd394f85/pkg/cmd/dev/roachprod_bench.go#L40)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

I find it confusing that the `dev` wrapper has the same name as the actual command doing the heavy lifting. Could we perhaps rename this to `roachprod-bench-wrapper`?
</blockquote></details>

Also had this ambiguous feeling the whole time, I have updated it.
___
*[`pkg/cmd/dev/roachprod_bench.go` line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NGcBL262Cbr29R40yti:-NH06t8A6qmtb027NSoE:b-6nlwfn) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bdab024723d8dbb209ad24d4e453afcd394f85/pkg/cmd/dev/roachprod_bench.go#L69)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Nit: `you can create one` --> `e.g.,` (fewer chars to parse :)
</blockquote></details>

That sounds better. I'll update.
___
*[`pkg/cmd/dev/roachprod_bench.go` line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NGcBa-401theXz-7Sdk:-NH07Xtb2wLt9t_UGknw:b-l67mr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bdab024723d8dbb209ad24d4e453afcd394f85/pkg/cmd/dev/roachprod_bench.go#L74)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Nit: assume the end-user is familiar with idiomatic go glob `...`;  something like this,

```
expected a single benchmark target specification; e.g., ./pkg/cmd/dev or ./pkg/util/...
```
</blockquote></details>

Fair enough, can also be looked up if not understood. Updated.
___
*[`pkg/cmd/dev/roachprod_bench.go` line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NGcDkiG-oQmnIR2YBx6:-NH07kf62q9E4VN6BlNP:b-7tye0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bdab024723d8dbb209ad24d4e453afcd394f85/pkg/cmd/dev/roachprod_bench.go#L102)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Shouldn't we bail out when `testTargets` is empty?
</blockquote></details>

Good catch, would definitely not make sense to continue empty-handed. 
___
*[`pkg/cmd/dev/roachprod_bench.go` line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NGcGCuz-URPU0Wj-y1g:-NH07vDX7vb8QyPosM_C:birqcma) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bdab024723d8dbb209ad24d4e453afcd394f85/pkg/cmd/dev/roachprod_bench.go#L108)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Nit: I am surprised to see `md5` is still widespread almost two decades later after first collisions were published. Even `bazel` uses `md5` to derive output directory, but everything else is on `sha256` afaik.
</blockquote></details>

Force of habit, but good point, and easy to switch. Updated.
___
*[`pkg/cmd/dev/roachprod_bench.go` line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NGcHGJP00SOHD_vRCfQ:-NH08DO-ET5iaSRujtql:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bdab024723d8dbb209ad24d4e453afcd394f85/pkg/cmd/dev/roachprod_bench.go#L143)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Could we parameterize this if only to make it future-proof against `arm64`?
</blockquote></details>

Done.
___
*[`pkg/cmd/dev/roachprod_bench.go` line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NGcHwUk7WCBRaO0f_YD:-NH08EeI2zmcELfAyaPa:bof548u) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bdab024723d8dbb209ad24d4e453afcd394f85/pkg/cmd/dev/roachprod_bench.go#L155)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

`compress`
</blockquote></details>

My keyboard seems to be missing a 'p'. Done.
___
*[`pkg/cmd/dev/roachprod_bench.go` line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NGcIQ6EAdDY12XGJy90:-NH08u9IEm_K-8Bauo2c:b-w3daf7) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bdab024723d8dbb209ad24d4e453afcd394f85/pkg/cmd/dev/roachprod_bench.go#L158)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

We now have a go-native analogue of it (i.e., `pgzip` [1]); might be worth replacing since not a lot of folks will have `pigz` locally installed.

[1] https://github.com/cockroachdb/cockroach/blob/45abe9112aa3972aabdc5c0fcca70e767fdb1cfc/pkg/ccl/changefeedccl/compression.go#L51
</blockquote></details>

Nice, thanks for pointing this out; I was unaware till now that we had that dependency added.
___
*[`pkg/cmd/dev/roachprod_bench.go` line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NGcJ1OTDvjefKxrvUjP:-NH08XPVBcofF__bvtOs:b-drq358) ([raw file](https://github.com/cockroachdb/cockroach/blob/53bdab024723d8dbb209ad24d4e453afcd394f85/pkg/cmd/dev/roachprod_bench.go#L227)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

It might improve readability to use a template, e.g., https://github.com/cockroachdb/cockroach/blob/45abe9112aa3972aabdc5c0fcca70e767fdb1cfc/pkg/roachprod/install/cockroach.go#L414
</blockquote></details>

Great idea. Done; I still kept the template text in the source, but if you think we should move it out to a scripts folder same as the example I can go that route as well.

**Review by srosenberg — APPROVED** [review]
Nice work! I've added a few minor comments after my second pass. Otherwise, it looks great.

:lgtm: 

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-:-NGcJXMm9eQOPh3DlJIl:brwqspy)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

___
*[`pkg/cmd/dev/roachprod_bench.go` line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NIVDvIR0GIJJ9xFfY7t:-NIVDvISEgrT2GyPJoe4:biskp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2c39c2544092a7d9de3f1a971d433fe66dc3d50/pkg/cmd/dev/roachprod_bench.go#L91)):*
> ```Go
> 	roachprodBenchCmd.Flags().String(buildHashFlag, "", "override the build hash for the build output")
> 	roachprodBenchCmd.Flags().Bool(raceFlag, false, "run tests using race builds")
> 	roachprodBenchCmd.Flags().Bool(compressFlag, false, "compress the output of the benchmarks binaries")
> ```

Curious why it's disabled by default? The ELF binaries have quite a bit of entropy especially when compiled with DWARF (symbols), so you get a fairly decent compression.
___
*[`pkg/cmd/dev/roachprod_bench.go` line 105 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NIVGRj4A9jVI7ut1A2U:-NIVGRj4A9jVI7ut1A2V:b-x7951l) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2c39c2544092a7d9de3f1a971d433fe66dc3d50/pkg/cmd/dev/roachprod_bench.go#L105)):*
> ```Go
> 		race        = mustGetFlagBool(cmd, raceFlag)
> 		compress    = mustGetFlagBool(cmd, compressFlag)
> 		batchSize   = mustGetFlagInt(cmd, batchSizeFlag)
> ```

We have to make sure `batchSize > 0`, otherwise you'll be stuck with an infinite loop. Could add another helper which takes an arbitrary predicate: `mustGetConstrainedIntFlag(*cobra.Command, func(int) bool)`
___
*[`pkg/cmd/dev/roachprod_bench.go` line 322 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NIVIlrz7fxH5SEnlm3M:-NIVIlrz7fxH5SEnlm3N:b9jddhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2c39c2544092a7d9de3f1a971d433fe66dc3d50/pkg/cmd/dev/roachprod_bench.go#L322)):*
> ```Go
> 	}
> 	if tarOutput {
> 		script.WriteString("echo Packaging staged build output...\n")
> ```

I think this can be decoupled from the build step; instead, this could be done after the loop. It's a separate concern, and it seems to increase the cognitive load,

* it's true only on the last iteration
* it complicates `compressFile` which should only do just that
___
*[`pkg/cmd/dev/roachprod_bench.go` line 353 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NIVJpjtBp0JoT6uSbOY:-NIVJpjtBp0JoT6uSbOZ:bhc2ekl) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2c39c2544092a7d9de3f1a971d433fe66dc3d50/pkg/cmd/dev/roachprod_bench.go#L353)):*
> ```Go
> 
> func compressFile(filePath string) (err error) {
> 	binTarFile, err := os.Open(filePath)
> ```

That's a separate concern from compressing a file. I think the append step should happen after `compressFile`; also see the above comment on moving `tar -c` after the loop.
___
*[`pkg/cmd/dev/roachprod_bench.go` line 358 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NIVKhfTBHOrHVp6axWA:-NIVKhfTBHOrHVp6axWB:b-8xxsic) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2c39c2544092a7d9de3f1a971d433fe66dc3d50/pkg/cmd/dev/roachprod_bench.go#L358)):*
> ```Go
> 	}
> 	defer func() {
> 		if closeErr := binTarFile.Close(); closeErr != nil && err == nil {
> ```

We have `errors.CombineErrors` for dealing with multiple errors. Is there a reason to swallow one of the two?

**Review by herkolategan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91144)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @renatolabs and @srosenberg)

___
*[`pkg/cmd/dev/roachprod_bench.go` line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NIVDvIR0GIJJ9xFfY7t:-NIbxenJ3E-G9O8R5UKy:b-t3t9tu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2c39c2544092a7d9de3f1a971d433fe66dc3d50/pkg/cmd/dev/roachprod_bench.go#L91)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Curious why it's disabled by default? The ELF binaries have quite a bit of entropy especially when compiled with DWARF (symbols), so you get a fairly decent compression.
</blockquote></details>

I was unsure of the additional time overhead initially, but with parallel gzip it makes sense to have this on by default.
___
*[`pkg/cmd/dev/roachprod_bench.go` line 105 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NIVGRj4A9jVI7ut1A2U:-NIcC-_i6QsHu_r8yc5V:b-7m99qi) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2c39c2544092a7d9de3f1a971d433fe66dc3d50/pkg/cmd/dev/roachprod_bench.go#L105)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

We have to make sure `batchSize > 0`, otherwise you'll be stuck with an infinite loop. Could add another helper which takes an arbitrary predicate: `mustGetConstrainedIntFlag(*cobra.Command, func(int) bool)`
</blockquote></details>

Done, but I opted to also add an error to clarify any issues.
___
*[`pkg/cmd/dev/roachprod_bench.go` line 322 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NIVIlrz7fxH5SEnlm3M:-NIcC8Zx7fJB0K3yVMls:b-bj6bfr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2c39c2544092a7d9de3f1a971d433fe66dc3d50/pkg/cmd/dev/roachprod_bench.go#L322)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

I think this can be decoupled from the build step; instead, this could be done after the loop. It's a separate concern, and it seems to increase the cognitive load,

* it's true only on the last iteration
* it complicates `compressFile` which should only do just that
</blockquote></details>

I initially assumed the docker container disappears after execution, but since it remains available I agree it can be moved to a separate run. The reason I prefer to run `tar` from within the docker container is to support environments where it might not be available - albeit highly unlikely.
___
*[`pkg/cmd/dev/roachprod_bench.go` line 353 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NIVJpjtBp0JoT6uSbOY:-NIcCdFp3yje0Kr3MJMd:bmz3tim) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2c39c2544092a7d9de3f1a971d433fe66dc3d50/pkg/cmd/dev/roachprod_bench.go#L353)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

That's a separate concern from compressing a file. I think the append step should happen after `compressFile`; also see the above comment on moving `tar -c` after the loop.
</blockquote></details>

This function only does compression. The variable naming was not great, I have updated it to reflect that.
___
*[`pkg/cmd/dev/roachprod_bench.go` line 358 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NIVKhfTBHOrHVp6axWA:-NIcCrm51I1RYv_JNl6a:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2c39c2544092a7d9de3f1a971d433fe66dc3d50/pkg/cmd/dev/roachprod_bench.go#L358)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

We have `errors.CombineErrors` for dealing with multiple errors. Is there a reason to swallow one of the two?
</blockquote></details>

Good point, done.

**Review by herkolategan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91144)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @renatolabs and @srosenberg)

___
*[`pkg/cmd/dev/roachprod_bench.go` line 322 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-NIVIlrz7fxH5SEnlm3M:-NIcE0AmBoXDy2jnC2rh:b64d37l) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2c39c2544092a7d9de3f1a971d433fe66dc3d50/pkg/cmd/dev/roachprod_bench.go#L322)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

I initially assumed the docker container disappears after execution, but since it remains available I agree it can be moved to a separate run. The reason I prefer to run `tar` from within the docker container is to support environments where it might not be available - albeit highly unlikely.
</blockquote></details>

I'll correct myself, since the statement about the container is flawed. I am copying from the container now, hence the tar step can be done outside the loop in contrast to the original appending to the tar that also dereferenced soft links.

**Review by srosenberg — APPROVED** [review]
Took another look, thanks for incorporating the changes. No further comments,.

> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91144#-:-NIeZrmJ-8pNOnreaHVL:bfixobs)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @renatolabs)

**Pull request merged**
