### PR TITLE
cmd/roachtest: refactor some ORM tests output handling

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit extracts out a helper struct that contains the common
state between all ORM and driver tests. It also introduces a few
new methods that will be reused by gopg ORM test.

Release note: None

### CODE REVIEW

**Comment by rohany** [comment]
this LGTM. I'll try and rebase my django changes onto here and reuse/extend this struct.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
Hm, seems like a flake.

bors r+

**Pull request merged**
