### PR TITLE
sqlbase: store list of column IDs used by CHECK constraint on proto

### PR DESCRIPTION
**Pull request by nvb**
Up to this point, we have relied on parsing a CHECK constraint's expression
every time we needed to determine the columns that it uses. This is
pretty bad because the columns will never change. Doing this also
limited our ability to introspect on the CHECK constraint.

This change addresses this by storing the IDs of all columns that a CHECK
constraint uses in a sorted slice on its descriptor. This allows us to
clean up chunks of code, address a few TODOs, and open up the path
to implementing the information_schema.constraint_column_usage table,
which requires this information.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
Don't you need a migration to populate this field for existing descriptors? I just skimmed this change, so perhaps I missed where that is happening. One thought is that we could populate the field when the `TableDescriptor` is loaded. See https://github.com/cockroachdb/cockroach/issues/22275. 

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22322#-:-L4Le0oiEb3Q-tW7Tgoa:bb5isqo)*

**Comment by justinj** [comment]
LGTM modulo Peter's question. I think the glorious future is #22275 which feels to me like it would be a cleaner way of addressing this problem, though obviously that change is a lot less incremental than this one.

---

Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/create_table.go, line 1335 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22322#-L4M7zxONAb4WQhUm9iy:-L4M7zxPqXchsIBk0p0E:b-wlnivi) ([raw file](https://github.com/cockroachdb/cockroach/blob/975d24224517a78a9ec79a618d1bafbbd612b231/pkg/sql/create_table.go#L1335)):*
> ```Go
> // replaceVars replaces the occurrences of column names in an expression with
> // dummies containing their type, so that they may be typechecked. It returns
> // this new expression tree alongsize a set containing the ColumnID of each
> ```

nit: `s/alongsize/alongside/`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22322#-:-L4M94jkppqn2W9HGWVO:b-ti4rd4)*

**Comment by nvanbenschoten** [comment]
I was figuring that we didn't lose anything by not performing a migration because we already didn't have this information, but that's pretty sloppy. I agree that we should add a migration similar to https://github.com/cockroachdb/cockroach/pull/20701. I'll ping the PR when that's done.

**Comment by nvanbenschoten** [comment]
Added a migration to populate these column IDs on existing table descriptors. PTAL!

---

Review status: 0 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/create_table.go, line 1335 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22322#-L4M7zxONAb4WQhUm9iy:-L4dfzGavsMlv7In7Owc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/975d24224517a78a9ec79a618d1bafbbd612b231/pkg/sql/create_table.go#L1335)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nit: `s/alongsize/alongside/`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22322#-:-L4dc0TAf7QS_dziHk5Y:b-k89xxs)*

**Comment by petermattis** [comment]
Review status: 0 of 18 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sqlmigrations/migrations.go, line 165 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/22322#-L4fXaytsU4-UWvWZON6:-L4fXaytsU4-UWvWZON7:b5rz7cq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3af21b2845db1a264937018906d18f3eabff7254/pkg/sqlmigrations/migrations.go#L165)):*
> ```Go
> 	{
> 		name:   "upgrade table descs to store check constraint columns",
> 		workFn: storeCheckConstraintColumnsOnTableDescs,
> ```

This migration will be run the first time a 2.0 server starts in a cluster, right? What happens if that is done via a rolling upgrade and a table is created on a pre-2.0 server? Seems like the migration won't be run again and we'll have a table without the column-ids populated in the check constraint.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22322)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 18 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sqlmigrations/migrations.go, line 165 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/22322#-L4fXaytsU4-UWvWZON6:-L4f_lOn0KCGaiCoiU21:b79iceq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3af21b2845db1a264937018906d18f3eabff7254/pkg/sqlmigrations/migrations.go#L165)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This migration will be run the first time a 2.0 server starts in a cluster, right? What happens if that is done via a rolling upgrade and a table is created on a pre-2.0 server? Seems like the migration won't be run again and we'll have a table without the column-ids populated in the check constraint.
</blockquote></details>

Yeah, you're right. We'll need to link a cluster version to this migration and refuse to run it/mark it as complete until that version `IsMinSupported`. 

I'm confused how migrations like https://github.com/cockroachdb/cockroach/pull/20701 got around this issue entirely though. They do seem to avoid the worst of it because they perform the migration locally if necessary on all accesses (see `MaybeUpgradeFormatVersion`), but they must run into the same issue of the migration missing some descriptors after marking it as complete, so I don't think we'll ever be able to remove these local migrations.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22322)*

**Comment by petermattis** [comment]
Review status: 0 of 18 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sqlmigrations/migrations.go, line 165 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/22322#-L4fXaytsU4-UWvWZON6:-L4g5fJLLsLnTxziSP5u:b-imw6je) ([raw file](https://github.com/cockroachdb/cockroach/blob/3af21b2845db1a264937018906d18f3eabff7254/pkg/sqlmigrations/migrations.go#L165)):*
> I'm confused how migrations like #20701 got around this issue entirely though. They do seem to avoid the worst of it because they perform the migration locally if necessary on all accesses (see MaybeUpgradeFormatVersion), but they must run into the same issue of the migration missing some descriptors after marking it as complete, so I don't think we'll ever be able to remove these local migrations.

Agreed. Probably worth socializing this more widely. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22322)*

**Comment by bdarnell** [comment]
#20701 was safe because it spans multiple releases. The "new" format was introduced in 1.0, but we only updated existing tables lazily. In 2.0, we're finally forcing the upgrade, but this won't be a problem for downgrades because 1.1 understands both the old and new formats (and only creates the new).

**Comment by nvanbenschoten** [comment]
Yeah, I just chatted with @benesch about that and everything checks out.

I have adjusted this change to take a similar approach. We add the `ColumnIDs` slice to new `TableDescriptors` from this point onward. When we need this slice, we check if it is present and populate it if it's not. We can then introduce a sql migration in 2.1 that does what I was trying to do here. Finally, in 2.2/3.0 we can remove this migration (as is done in https://github.com/cockroachdb/cockroach/pull/22358).

**Comment by petermattis** [comment]
> I have adjusted this change to take a similar approach. 

Ack. I'll leave it to someone (@justinj?) to give this PR a final review.

---

Review status: 0 of 17 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22322#-:-L4gQvH6xVsJWfklreRg:b-y6vrlw)*

**Comment by justinj** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 2 of 12 files at r3, 1 of 15 files at r6, 2 of 2 files at r7, 11 of 11 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22322#-:-L4m2wwMR0UMtTPWqwKt:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
TFTRs!

**Pull request merged**
