### PR TITLE
engine: fix different serialization of MVCCMetadata used for

### LINKED ISSUE #45811: roachtest: engine/switch/nodes=3 failed
[(roachtest).engine/switch/nodes=3 failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1790595&tab=buildLog) on [master@954fe69d554162aec0fbc001aad1fe5103d8df13](https://github.com/cockroachdb/cockroach/commits/954fe69d554162aec0fbc001aad1fe5103d8df13):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/20200306-1790595/engine/switch/nodes=3/run_1
	test_runner.go:756: test timed out (10h0m0s)

	cluster.go:1935,engine_switch.go:129,engine_switch.go:140,test_runner.go:741: error with attached stack trace:
		    main.(*cluster).RunE
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2010
		    main.(*cluster).Run
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:1933
		    main.registerEngineSwitch.func1
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/engine_switch.go:129
		    main.registerEngineSwitch.func2
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/engine_switch.go:140
		    main.(*testRunner).runTest.func2
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:741
		    runtime.goexit
		    	/usr/local/go/src/runtime/asm_amd64.s:1357
		  - error with embedded safe details: output in %s
		    -- arg 1: <string>
		  - output in run_082446.331_n4_workload_check_tpcc:
		  - error with attached stack trace:
		    main.execCmd
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:406
		    main.(*cluster).RunL
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2019
		    main.(*cluster).RunE
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2000
		    main.(*cluster).Run
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:1933
		    main.registerEngineSwitch.func1
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/engine_switch.go:129
		    main.registerEngineSwitch.func2
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/engine_switch.go:140
		    main.(*testRunner).runTest.func2
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:741
		    runtime.goexit
		    	/usr/local/go/src/runtime/asm_amd64.s:1357
		  - error with embedded safe details: %s returned:
		    stderr:
		    %s
		    stdout:
		    %s
		    -- arg 1: <string>
		    -- arg 2: <string>
		    -- arg 3: <string>
		  - /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1790595-1583481796-02-n4cpu4:4 -- ./workload check tpcc --warehouses=1 --expensive-checks=true {pgurl:1} returned:
		    stderr:
		    
		    stdout::
		  - context canceled

```

<details><summary>More</summary><p>

Artifacts: [/engine/switch/nodes=3](https://teamcity.cockroachdb.com/viewLog.html?buildId=1790595&tab=artifacts#/engine/switch/nodes=3)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Aengine%2Fswitch%2Fnodes%3D3.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by sumeerbhola**
non-MVCC data that is merged using C++ code in RocksDB and
Go code in Pebble

The serialization now matches the C++ code.

Fixes #45811

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
Looks good, though I've got one more test for you to enhance/add.

PS I appreciate the use of a very unattractive name for this proto.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45973#-:-M2648FU4dvCGbWY5Iya:bzal6k4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/enginepb/mvcc.proto, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45973#-M263SXC5NJrcs1p9_Gm:-M263SXC5NJrcs1p9_Gn:but5ko0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4f6f1a38c6417e5ba4a5557750328ec0827740b/pkg/storage/enginepb/mvcc.proto#L89)):*
> ```protobuf
>   option (gogoproto.goproto_stringer) = false;
>   option (gogoproto.equal) = true;
>   option (gogoproto.populate) = true;
> ```

I believe this is only used by `kv/kvserver/below_raft_protos_test.go`. It would be nice to verify that the serialization of this proto doesn't accidentally changed, because the serialization happens below Raft. But I'm not sure if you can hook directly into the `below_raft_protos_test.go` due to the way those golden files are checked that they are still being marshaled below Raft. If you can hook into that test, great. If you can't, I'd suggest forking the relevant portions (i.e. randomly populating a proto using a fixed seed and verifying the output when serialized).

**Review by sumeerbhola — COMMENTED** [review]
TFTR!
Modified below_raft_protos_test.go

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45973#-:-M29Hvhs0Y6nicHgrUZi:b2w5mvf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

___
*[pkg/storage/sst_writer_test.go, line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45973#-M29IFsm6xISTq-iRt4x:-M29IFsm6xISTq-iRt4y:b-ls94n) ([raw file](https://github.com/cockroachdb/cockroach/blob/a362994483e0f65939a1a1e9d181500bf34a1eac/pkg/storage/sst_writer_test.go#L148)):*
> ```Go
> 	require.Equal(t, string(sstRocks), string(sstPebble))
> 	itRocks.Close()
> 	itPebble.Close()
> ```

this is unrelated -- the test was failing with a `pebble: cache has non-zero reference count` error. Not sure why it has not been consistently failing.
___
*[pkg/storage/enginepb/mvcc.proto, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45973#-M263SXC5NJrcs1p9_Gm:-M299Msp2q7B5LQjz0R-:bu15qj0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4f6f1a38c6417e5ba4a5557750328ec0827740b/pkg/storage/enginepb/mvcc.proto#L89)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I believe this is only used by `kv/kvserver/below_raft_protos_test.go`. It would be nice to verify that the serialization of this proto doesn't accidentally changed, because the serialization happens below Raft. But I'm not sure if you can hook directly into the `below_raft_protos_test.go` due to the way those golden files are checked that they are still being marshaled below Raft. If you can hook into that test, great. If you can't, I'd suggest forking the relevant portions (i.e. randomly populating a proto using a fixed seed and verifying the output when serialized).
</blockquote></details>

You were right -- running the kvserver tests with `COCKROACH_STORAGE_ENGINE=pebble` fails with
`*enginepb.MVCCMetadataSubsetForMergeSerialization: missing fixture! Please adjust belowRaftGoldenProtos if necessary`

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45973#-:-M29Jjiy376JqZ0rsNoR:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

___
*[pkg/storage/sst_writer_test.go, line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45973#-M29IFsm6xISTq-iRt4x:-M29JGBq9mfaFfjR12ax:b-so9p2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/a362994483e0f65939a1a1e9d181500bf34a1eac/pkg/storage/sst_writer_test.go#L148)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this is unrelated -- the test was failing with a `pebble: cache has non-zero reference count` error. Not sure why it has not been consistently failing.
</blockquote></details>

GC needs to fire in order for the finalizer-based leak detection to trigger. I wouldn't be surprised if there are one or two more such places lurking. It has been straightforward to track down the missing `Close` calls in my experience.

**Pull request merged**
