### PR TITLE
sql: persist PRIMARY REGION metadata onto database descriptor

### PR DESCRIPTION
**Pull request by otan**
sql: persist PRIMARY REGION metadata onto database descriptor

Release note (sql change): CREATE DATABASE ... PRIMARY REGION ...
is now stored on the database descriptor.

delegate: show primary_region for SHOW DATABASES

Release note (sql change): SHOW DATABASES / crdb_internal.databases now
both display the PRIMARY REGION set on the database descriptor as the
`primary_region` column.

### CODE REVIEW

**Review by ajstorm — CHANGES_REQUESTED** [review]
Looks great!  Might want to pull some of this logic out of create database though, and have it live in region_util.go

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57038#-:-MMuunz2Be4VsKJazq7i:b4gh7y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/descriptor.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57038#-MMupAY6-dncZW38JK0w:-MMupAY7DMrhOy7z4t-S:bvjfudj) ([raw file](https://github.com/cockroachdb/cockroach/blob/302a4acad9a49ffc274f253e7937948ea7301840/pkg/sql/descriptor.go#L99)):*
> ```Go
> 			return nil, false, err
> 		}
> 		regionConfig.PrimaryRegion = string(database.PrimaryRegion)
> ```

Can we pull all of this logic out of here and have a single call to `validateDatabaseRegions` which takes  `liveRegions`, the primary region, and returns a bool if all of the checks below are satisfied?  Then we could either keep this logic below in-tact in that function, or split it into two sub-functions (one for the primary region testing and the other for the region testing).
___
*[pkg/sql/descriptor.go, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57038#-MMuraH3C4pCFDgLnl7v:-MMuraH3C4pCFDgLnl7w:bb9uwq) ([raw file](https://github.com/cockroachdb/cockroach/blob/302a4acad9a49ffc274f253e7937948ea7301840/pkg/sql/descriptor.go#L127)):*
> ```Go
> 					)
> 				}
> 				seenRegions[region] = struct{}{}
> ```

Is there a reason why we don't make `regionConfig.Regions` a map?  Then we could avoid the need for `seenRegions`.
___
*[pkg/sql/descriptor.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57038#-MMutRvs-Ey3EJQofU17:-MMutRvs-Ey3EJQofU18:b-nu7kx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/302a4acad9a49ffc274f253e7937948ea7301840/pkg/sql/descriptor.go#L132)):*
> ```Go
> 			// If PRIMARY REGION is not in REGIONS, add it implicitly.
> 			if _, ok := seenRegions[regionConfig.PrimaryRegion]; !ok {
> 				regionConfig.Regions = append(
> ```

noob golang question, but why the building of a new slice here to append where above we were appending the string directly?  Is there some reason why you want primary region to be at the front of the slice?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57038)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/sql/descriptor.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57038#-MMupAY6-dncZW38JK0w:-MMvDTNY0buV0EoEJyH2:b-quypyp) ([raw file](https://github.com/cockroachdb/cockroach/blob/302a4acad9a49ffc274f253e7937948ea7301840/pkg/sql/descriptor.go#L99)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Can we pull all of this logic out of here and have a single call to `validateDatabaseRegions` which takes  `liveRegions`, the primary region, and returns a bool if all of the checks below are satisfied?  Then we could either keep this logic below in-tact in that function, or split it into two sub-functions (one for the primary region testing and the other for the region testing).
</blockquote></details>

problem is that we need to add the primary region if database.Regions == 0, so it didn't really work as a "add this at the end" kind of check :\. splitting it into two seemed kind of gross, and this logic is very specific to create db.
___
*[pkg/sql/descriptor.go, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57038#-MMuraH3C4pCFDgLnl7v:-MMvDfr6AOTMSnz8ugmI:b-muefp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/302a4acad9a49ffc274f253e7937948ea7301840/pkg/sql/descriptor.go#L127)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Is there a reason why we don't make `regionConfig.Regions` a map?  Then we could avoid the need for `seenRegions`.
</blockquote></details>

i'm not sure protobufs (which is how this is backed) have a nice way of map[string]struct{}. Also you lose order :)
___
*[pkg/sql/descriptor.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57038#-MMutRvs-Ey3EJQofU17:-MMvDm921wX88RqAeubn:beo3jza) ([raw file](https://github.com/cockroachdb/cockroach/blob/302a4acad9a49ffc274f253e7937948ea7301840/pkg/sql/descriptor.go#L132)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

noob golang question, but why the building of a new slice here to append where above we were appending the string directly?  Is there some reason why you want primary region to be at the front of the slice?
</blockquote></details>

I wanted to put primary region at the front! if you feel strongly otherwise we can put it at the back ;)

**Review by nvb — APPROVED** [review]
> Reviewed 6 of 6 files at r1, 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57038)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/sql/descriptor.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57038#-MMutRvs-Ey3EJQofU17:-MMvDdLB7e7GwYkygxCD:b-icn1zg) ([raw file](https://github.com/cockroachdb/cockroach/blob/302a4acad9a49ffc274f253e7937948ea7301840/pkg/sql/descriptor.go#L132)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

I wanted to put primary region at the front! if you feel strongly otherwise we can put it at the back ;)
</blockquote></details>

Yeah, it looks like it's because he wants the primary region first. We could avoid the re-alloc with an append, shift, and assignment, but it's probably not worth it.

On this note though (and related to your map question up above), do we want to keep the regions in a specific order? Maybe ordered lexicographically to allow searching and to avoid the need to sort when formatting.

**Comment by otan** [comment]
___
*[pkg/sql/descriptor.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57038#-MMutRvs-Ey3EJQofU17:-MMvG0KpDCVOan5kkb68:bwcl2t0) ([raw file](https://github.com/cockroachdb/cockroach/blob/302a4acad9a49ffc274f253e7937948ea7301840/pkg/sql/descriptor.go#L132)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, it looks like it's because he wants the primary region first. We could avoid the re-alloc with an append, shift, and assignment, but it's probably not worth it.

On this note though (and related to your map question up above), do we want to keep the regions in a specific order? Maybe ordered lexicographically to allow searching and to avoid the need to sort when formatting.
</blockquote></details>

I have sorted them in lexicographical order!

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57038)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @nvanbenschoten, and @otan)

___
*[pkg/sql/descriptor.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57038#-MMupAY6-dncZW38JK0w:-MMvbizN1e3biVUk36YD:b4g6402) ([raw file](https://github.com/cockroachdb/cockroach/blob/302a4acad9a49ffc274f253e7937948ea7301840/pkg/sql/descriptor.go#L99)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

problem is that we need to add the primary region if database.Regions == 0, so it didn't really work as a "add this at the end" kind of check :\. splitting it into two seemed kind of gross, and this logic is very specific to create db.
</blockquote></details>

That all makes sense, just thinking that the region management logic is now about half of the length of createDatabase, and many databases may not even use multiple regions (or will have them altered in afterwards).  To that point, I'd also think that this logic will be needed in the alter case too.  Even pulling all of the region logic into a separate function that can be called from here would simplify the code significantly.  Give it some thought.  If you still disagree, I'm good.  As @otan would say, I'm not dying on this hill ;-)

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57038)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @nvanbenschoten)

___
*[pkg/sql/descriptor.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57038#-MMupAY6-dncZW38JK0w:-MMvoif67aRep8agwpru:b1icvth) ([raw file](https://github.com/cockroachdb/cockroach/blob/302a4acad9a49ffc274f253e7937948ea7301840/pkg/sql/descriptor.go#L99)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

That all makes sense, just thinking that the region management logic is now about half of the length of createDatabase, and many databases may not even use multiple regions (or will have them altered in afterwards).  To that point, I'd also think that this logic will be needed in the alter case too.  Even pulling all of the region logic into a separate function that can be called from here would simplify the code significantly.  Give it some thought.  If you still disagree, I'm good.  As @otan would say, I'm not dying on this hill ;-) 
</blockquote></details>

I think the logic for alter will be different since we're only ever dealing with one region at a time -- abstracting this to a new function for readability though. maybe it can be mangled, but later us problem.

**Review by ajstorm — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57038#-:-MMxHFeC7wPtlpcBRHQO:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @nvanbenschoten, and @otan)

___
*[pkg/sql/descriptor.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57038#-MMupAY6-dncZW38JK0w:-MMxHD1x9CjQjZMPq3_R:b-j3dbo1) ([raw file](https://github.com/cockroachdb/cockroach/blob/302a4acad9a49ffc274f253e7937948ea7301840/pkg/sql/descriptor.go#L99)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

I think the logic for alter will be different since we're only ever dealing with one region at a time -- abstracting this to a new function for readability though. maybe it can be mangled, but later us problem.
</blockquote></details>

Me likey.

**Comment by otan** [comment]
bors r=ajstorm

**Pull request merged**
