### PR TITLE
upgrades: drop payload and progress from system.jobs 

### PR DESCRIPTION
**Pull request by adityamaru**
Please see individual commits.

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
:lgtm: 

I'm assuming all writes have already stopped on 23.1, so we have no danger of any funny mixed version state

> Reviewed 1 of 1 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115056#-:-Nk0zm5aD_e1LGidWuAc:b-6td3wj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @stevendanna)

**Comment by adityamaru** [comment]
TFTR!

bors r=fqazi

**Comment by RaduBerinde** [comment]
What is the benefit of this change? The extra columns shouldn't hurt anything. On the flip side, if the jobs table is large, the schema change during upgrade might have a non-trivial cost (and perhaps cause issues during upgrade).

CC @petermattis - we were just discussing the other day that we sometimes error too much on the side of keeping the current state as clean as possible at the expense of upgrade reliability.

**Comment by RaduBerinde** [comment]
I wasn't clear - I was specifically asking about the upgrade migration. Creating the table without the extra columns on new clusters is good, I just don't see the benefit of the schema change if it exists already.

**Comment by RaduBerinde** [comment]
*[`pkg/upgrade/upgrades/v24_1_drop_payload_and_progress_jobs.go` line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/115056#-Nkaqy5k9TcTlfRNLRCk:-Nkaqy5k9TcTlfRNLRCl:btdlxm5) ([raw file](https://github.com/cockroachdb/cockroach/blob/24ef7d5803496ac47978b31ed1dcb3f3b76ee869/pkg/upgrade/upgrades/v24_1_drop_payload_and_progress_jobs.go#L24)):*
> ```Go
> 	ctx context.Context, cv clusterversion.ClusterVersion, deps upgrade.TenantDeps,
> ) error {
> 	_, err := deps.InternalExecutor.ExecEx(ctx, "drop-payload-payload", nil, /* txn */
> ```

Is it not possible to drop both columns in one statement? If it is, why do two schema changes?

**Comment by dt** [comment]
That said, I wish it were possible to have `drop column` be a metadata only operation if the column is already empty (which it generally should be here since we stopped writing it in 23.1). It'd be nice if we could mark it as dropped but not do the index rebuilds or backfill or whatever, then do a scan for not-null rows, and if we don't find any, just remove it from the desc.

**Pull request merged**
