### PR TITLE
optbuilder: add ST_Collect/ST_MakeLine to isOrderingSensitive

### PR DESCRIPTION
**Pull request by otan**
Release note (bug fix): Fix a bug where ST_MakeLine and ST_Collect
did not respect ordering when used over a window clause.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57724)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/geospatial, line 5018 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57724#-MO4T79A9iT2M4n2g16S:-MO4T79A9iT2M4n2g16T:b-vx1mnn) ([raw file](https://github.com/cockroachdb/cockroach/blob/8121c57ce35e183a97be5fc6aa12f078c09acb4f/pkg/sql/logictest/testdata/logic_test/geospatial#L5018)):*
> ```
> 
> query T
> EXPLAIN SELECT ST_MakeLine(geom ORDER BY geom) FROM geo_table
> ```

Plans should be only in opt/exec/execbuilder tests, not in logic tests. There are multiple reasons for this, including ease of making changes in the optimizer (you only have to rewrite and consult diffs in one set of tests), and allowing running logic tests with randomized plan changes. Geospatial changes already broke this rule a lot, but we should aim to do better. 

Also, we have an outstanding task to make this case not use window functions (and just push down the order requirement), which would change these plans and probably defeat the purpose of the tests. It would be better if we could build a testcase that returns the wrong result if the order is not right (the `fakedist` config should result in out-of order rows if the optimizer drops the ordering).

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57724#-:-MO6tO6O2eQv_nKcz8Iy:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by otan** [comment]
thankssss

bors r=rytaft

**Comment by RaduBerinde** [comment]
:lgtm: Thanks!

**Pull request merged**
