### PR TITLE
opt: support UPDATE on tables with virtual columns

### PR DESCRIPTION
**Pull request by RaduBerinde**
Release note: None

### CODE REVIEW

**Review by mgartner — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59207)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/virtual_columns, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59207#-MRfKYjE9nZ_w5CCIy1R:-MRfKYjE9nZ_w5CCIy1S:bfnd2lp) ([raw file](https://github.com/cockroachdb/cockroach/blob/833241989b41c76b5c62092f231865f12a093238/pkg/sql/logictest/testdata/logic_test/virtual_columns#L93)):*
> ```
> 
> statement ok
> UPDATE t SET a=a+1
> ```

Can you add a test that errs when trying to update a virtual column? There is already one for INSERTs above. Something like:

```
UPDATE t SET v=1
```
___
*[pkg/sql/logictest/testdata/logic_test/virtual_columns, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59207#-MRfIkRWA4Ya7LCQXjv8:-MRfIkRWA4Ya7LCQXjv9:b-xrovwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/833241989b41c76b5c62092f231865f12a093238/pkg/sql/logictest/testdata/logic_test/virtual_columns#L100)):*
> ```
> a   b   v
> 23  20  43
> 45  40  85
> ```

I think this should be:

```
a   b   v
3  20  23
4  40  44
```
___
*[pkg/sql/logictest/testdata/logic_test/virtual_columns, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59207#-MRfIzQZCQWZlLxm81YL:-MRfIzQZCQWZlLxm81YM:b-n8grga) ([raw file](https://github.com/cockroachdb/cockroach/blob/833241989b41c76b5c62092f231865f12a093238/pkg/sql/logictest/testdata/logic_test/virtual_columns#L107)):*
> ```
> a  b  v
> ```

[nit] remove extra new line 
___
*[pkg/sql/opt/exec/execbuilder/testdata/virtual_columns, line 427 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59207#-MRfNTOa0iYWJb-64JqR:-MRfNTOa0iYWJb-64JqS:b-k2p5za) ([raw file](https://github.com/cockroachdb/cockroach/blob/833241989b41c76b5c62092f231865f12a093238/pkg/sql/opt/exec/execbuilder/testdata/virtual_columns#L427)):*
> ```
> 
> query T
> EXPLAIN (VERBOSE) UPDATE t SET b=b+1 WHERE v=45 RETURNING a,b,v
> ```

[nit] Did you want to include a test like this but for `t_idx` to ensure that the index on `v` is scanned rather than a full table scan?
___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 3581 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59207#-MRfM6e_AEMzZD8YdoGw:-MRfM6ea2D26GTS33wdM:b91oucy) ([raw file](https://github.com/cockroachdb/cockroach/blob/833241989b41c76b5c62092f231865f12a093238/pkg/sql/opt/norm/testdata/rules/prune_cols#L3581)):*
> ```
> # We cannot prune column v because it is affected by the change.
> norm
> UPDATE virt_idx SET b = b + 1
> ```

This is the same test as above, no? I think you meant to update the `virt_idx2` table in one of these tests (or a new test?). When you fix that, can you make the comment clear that `v` should not be pruned when updating the primary key because the v index entry needs to be modified.
___
*[pkg/sql/opt/optbuilder/testdata/virtual-columns, line 359 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59207#-MRfKx8W7VyebfyJWHU6:-MRfKx8XESPfvaZvZD4B:b-k9dg4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/833241989b41c76b5c62092f231865f12a093238/pkg/sql/opt/optbuilder/testdata/virtual-columns#L359)):*
> ```
>                 └── v:7 = 1
> 
> # -- UPDATE tests --
> ```

You can also add a test here too that errs when trying to update a virtual column. There's one for inserts, so it seems appropriate to include this test case in both logic and optbuilder tests.

**Review by RaduBerinde — COMMENTED** [review]
Thanks for the thorough review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59207#-:-MRg940aC2JWeZs1oICo:bst74u7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/virtual_columns, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59207#-MRfKYjE9nZ_w5CCIy1R:-MRg6evR7eT_6pv1x2Co:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/833241989b41c76b5c62092f231865f12a093238/pkg/sql/logictest/testdata/logic_test/virtual_columns#L93)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you add a test that errs when trying to update a virtual column? There is already one for INSERTs above. Something like:

```
UPDATE t SET v=1
```
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/virtual_columns, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59207#-MRfIkRWA4Ya7LCQXjv8:-MRfeHsW5FGZxVkJ1MJ5:b-4ix524) ([raw file](https://github.com/cockroachdb/cockroach/blob/833241989b41c76b5c62092f231865f12a093238/pkg/sql/logictest/testdata/logic_test/virtual_columns#L100)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think this should be:

```
a   b   v
3  20  23
4  40  44
```

</blockquote></details>

Wow.. great catch.. this was a bug (execution silently does bad things when you have an update column without a fetch column, even if you don't need the old value). Fixed (in NeededMutationCols, plus some sanity checks in the execbuilder and exec code).
___
*[pkg/sql/opt/exec/execbuilder/testdata/virtual_columns, line 427 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59207#-MRfNTOa0iYWJb-64JqR:-MRg6uO296ao4W06GoxH:b-rtgu8p) ([raw file](https://github.com/cockroachdb/cockroach/blob/833241989b41c76b5c62092f231865f12a093238/pkg/sql/opt/exec/execbuilder/testdata/virtual_columns#L427)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] Did you want to include a test like this but for `t_idx` to ensure that the index on `v` is scanned rather than a full table scan?
</blockquote></details>

Done (added below).
___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 3581 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59207#-MRfM6e_AEMzZD8YdoGw:-MRg7E-tAoDXFPmvKkAQ:b-i734o1) ([raw file](https://github.com/cockroachdb/cockroach/blob/833241989b41c76b5c62092f231865f12a093238/pkg/sql/opt/norm/testdata/rules/prune_cols#L3581)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This is the same test as above, no? I think you meant to update the `virt_idx2` table in one of these tests (or a new test?). When you fix that, can you make the comment clear that `v` should not be pruned when updating the primary key because the v index entry needs to be modified.
</blockquote></details>

it's `a=a+1` vs `b=b+1`(they are pretty different since a is a PK).

Added the test you mentioned though, plus another one.

**Comment by RaduBerinde** [comment]
CI failure is unrelated flake (see https://github.com/cockroachdb/cockroach/pull/59324).

**Review by mgartner — APPROVED** [review]
Very nice! :lgtm: 

> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59207#-:-MRgh9B54j2_1oOolHOq:bup7q37)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/virtual_columns, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59207#-MRfIkRWA4Ya7LCQXjv8:-MRgfIdh8_0jD21d7qTO:bmi8ppe) ([raw file](https://github.com/cockroachdb/cockroach/blob/833241989b41c76b5c62092f231865f12a093238/pkg/sql/logictest/testdata/logic_test/virtual_columns#L100)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Wow.. great catch.. this was a bug (execution silently does bad things when you have an update column without a fetch column, even if you don't need the old value). Fixed (in NeededMutationCols, plus some sanity checks in the execbuilder and exec code).
</blockquote></details>

:100: 
___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 3581 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59207#-MRfM6e_AEMzZD8YdoGw:-MRgfzXY5UG84ku_J5Vn:btpw88r) ([raw file](https://github.com/cockroachdb/cockroach/blob/833241989b41c76b5c62092f231865f12a093238/pkg/sql/opt/norm/testdata/rules/prune_cols#L3581)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

it's `a=a+1` vs `b=b+1`(they are pretty different since a is a PK).

Added the test you mentioned though, plus another one.
</blockquote></details>

I guess they don't seem different to me given that `v` is defined as `(a+b)`, so even if `a` wasn't a PK, `v` would have to be fetched. Regardless, the new tests cover all these cases.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 7 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59207#-:-MRtdDo5AdUGGDXGpbK2:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/opt/norm/prune_cols_funcs.go, line 162 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59207#-MRtbu3qEG5FjHBvuwXa:-MRtbu3qEG5FjHBvuwXb:b-5hojwj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d80201c8c0a740ee52044628a2ee97910aca9d5/pkg/sql/opt/norm/prune_cols_funcs.go#L162)):*
> ```Go
> 		// corresponding fetch column (even if the old value is not necessary).
> 		// Note that when this limitation is fixed, the rest of the code below
> 		// needs to be revisited as well.
> ```

[nit] maybe make this a `TODO` so it's more explicit that this will need to change.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59207)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/norm/prune_cols_funcs.go, line 162 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59207#-MRtbu3qEG5FjHBvuwXa:-MRv1Zc86Gx4HA54XxFR:b-oq0z05) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d80201c8c0a740ee52044628a2ee97910aca9d5/pkg/sql/opt/norm/prune_cols_funcs.go#L162)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] maybe make this a `TODO` so it's more explicit that this will need to change.
</blockquote></details>

Done, TFTR

**Review by rytaft — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59207)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Pull request merged**
