### PR TITLE
roachtest: fix gorm roachtest

### LINKED ISSUE #64159: roachtest: gorm failed
roachtest.gorm [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2917180&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=2917180&tab=artifacts#/gorm) on master @ [9e821aa456bfbe8b5ec3a8ef79ae3954d52cb675](https://github.com/cockroachdb/cockroach/commits/9e821aa456bfbe8b5ec3a8ef79ae3954d52cb675):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/gorm/run_1
	test.go:298,assertions.go:262,assertions.go:1332,require.go:1035,gorm.go:103,test_runner.go:777: 
			Error Trace:	gorm.go:103
			            				test_runner.go:777
			            				asm_amd64.s:1374
			Error:      	Received unexpected error:
			            	output in run_213727.401_n1_cockroach_sql: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-2917180-1619205254-41-n1cpu4:1 -- cockroach sql -e "CREATE DATABASE gorm" --insecure returned: exit status 20
			            	(1) attached stack trace
			            	  -- stack trace:
			            	  | main.(*cluster).RunE
			            	  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2418
			            	  | main.registerGORM.func1
			            	  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/gorm.go:102
			            	  | main.(*testRunner).runTest.func2
			            	  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:777
			            	  | runtime.goexit
			            	  | 	/usr/local/go/src/runtime/asm_amd64.s:1374
			            	Wraps: (2) output in run_213727.401_n1_cockroach_sql
			            	Wraps: (3) /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-2917180-1619205254-41-n1cpu4:1 -- cockroach sql -e "CREATE DATABASE gorm" --insecure returned
			            	  | stderr:
			            	  | bash: cockroach: command not found
			            	  | Error: COMMAND_PROBLEM: exit status 127
			            	  | (1) COMMAND_PROBLEM
			            	  | Wraps: (2) Node 1. Command with error:
			            	  |   | ``````
			            	  |   | cockroach sql -e "CREATE DATABASE gorm" --insecure
			            	  |   | ``````
			            	  | Wraps: (3) exit status 127
			            	  | Error types: (1) errors.Cmd (2) *hintdetail.withDetail (3) *exec.ExitError
			            	  |
			            	  | stdout:
			            	Wraps: (4) exit status 20
			            	Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *main.withCommandDetails (4) *exec.ExitError
			Test:       	gorm
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
# From https://go.crdb.dev/p/roachstress, perhaps edited lightly.
caffeinate ./roachstress.sh gorm
```
</p>
</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*gorm.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by RichardJCai**
roachtest: fix gorm roachtest

Release note: None

resolves #64159

### CODE REVIEW

**Comment by RichardJCai** [comment]
I have no idea how this worked when I tested it locally before.

**Review by rafiss — APPROVED** [review]
lgtm thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64213#-:-MZDjFCW6-65AQj3Nc84:b3lcc29)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by RichardJCai** [comment]
Thanks!

bors r=rafiss

**Comment by RichardJCai** [comment]
bors r=rafiss

**Comment by RichardJCai** [comment]
bors r=rafiss

**Comment by RichardJCai** [comment]
bors r=rafiss

**Pull request merged**
