### PR TITLE
client: rename to internalclient

### PR DESCRIPTION
**Pull request by madelynnblue**
Rename internal/client to internalclient so that packages outside of
cockroach can import the client package. This is useful for packages
that need to interface with the cockroach KV layer directly, like
plugins or coprocessors.

Notable changes: lease.proto had its go_package field changed, but
not its package field.

See #13901 for discussion

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14237)

### CODE REVIEW

**Comment by dt** [comment]
Long lines in func sigs throughout thanks to the long pkgname prefix everywhere.
+1 on the change, -1 on the name, just because it looks clunky in every signature, but don't care enough really get on bikeshed committee.

**Comment by mjibson** [comment]
If I got to choose I'd move back into the kv directory still named `client`. The point of this PR is to enable people to use the client package to do weird stuff. Having the compiler enforce not using it forces folks to do silly things like build their code in the cockroach directory. That is, it's still pretty easy to get around, might as well make it friendly.

**Comment by mjibson** [comment]
Changed to use `kv/client` instead of `internalclient`. Bike shed time.

**Comment by petermattis** [comment]
If -1 on doing this now while we don't have a solid plan for coprocessors or plugins, nor is either feature on the roadmap. Additionally, exposing `internal/client` gives us more surface area to support right now. While I can envision wanting to expose it eventually, this doesn't seem like the time.

My 2 cents.

**Comment by bdarnell** [comment]
My comment https://github.com/cockroachdb/cockroach/issues/13901#issuecomment-284538151 still stands.

**Pull request closed without merging**
