### PR TITLE
release-21.1: cli: print LSM stats every minute during manual compaction

### PR DESCRIPTION
**Pull request by nicktrav**
When running a manual compaction of the entire LSM through
`cockroach debug compact` print the LSM stats table every minute. This
helps provide some indication of the pace of progress.

Release note: None

Release justification: operational tooling enhancement.

### CODE REVIEW

**Comment by nicktrav** [comment]
Keeping this up our sleeve for an open support case (cockroachlabs/support#1406), as a just-in-case.

I'm not 100% sure this meets the backport eligibility. It's an enhancement that already exists on `master` and `21.2`, and it's for operation-only code (i.e. offline manual compactions), but it's still new code, and there's no gating or opt-in.

**Comment by nicktrav** [comment]
Keeping this up our sleeve for an open support case, as a just-in-case.

I'm not 100% sure this meets the backport eligibility. It's an enhancement that already exists on `master` and `21.2`, and it's for operation-only code (i.e. offline manual compactions), but it's still new code, and there's no gating or opt-in.

**Review by tbg — COMMENTED** [review]
I think this is a low-risk change that doesn't touch core DB functionality and so we should allow ourselves to backport it.

**Comment by nicktrav** [comment]
Just realized that this will also need 0e0082d16bd9a19b5c11662c3d83cdfe54c5e506 to be backported, which isn't limited to just CLI code, so the change is slightly more risky.

I will re-work and re-open.

**Pull request closed without merging**
