### PR TITLE
roachprod: account for cost of boot partition

### LINKED ISSUE #120728: roachprod: account for cost of boot partition
When creating GCE clusters on roachprod, we're not properly accounting for the cost of the root partition.  This can be easily reproed by comparing these two cluster creations:

```
./bin/roachprod create ajstorm-test --clouds gce --nodes 1 --gce-machine-type n2-standard-16 --os-volume-size 10000 --local-ssd=true --gce-zones us-east1-b,us-east1-c,us-east1-d --username ajstorm --lifetime 1h
```

which shows this cost:

```
> roachprod list --pattern ajstorm                                                                                                                                                                             Cluster                     Clouds  Size              VM       Arch  $/hour  $ Spent  Uptime     TTL  $/TTL
                                                                                                       
  ajstorm-test  [gce:cockroach-ephemeral]     1  n2-standard-16   ice lake   $0.86    $0.04    3m0s  57m43s  $0.83
```

and this:

```
./bin/roachprod create ajstorm-test --clouds gce --nodes 1 --gce-machine-type n2-standard-16 --os-volume-size 100 --local-ssd=true --gce-zones us-east1-b,us-east1-c,us-east1-d --username ajstorm --lifetime 1h
```

which shows the same cost:

```
> roachprod list --pattern ajstorm                                                                                                                                                                 
            Cluster                     Clouds  Size              VM       Arch  $/hour  $ Spent  Uptime       TTL  $/TTL
                                                                                                         
  ajstorm-test  [gce:cockroach-ephemeral]     1  n2-standard-16   ice lake   $0.86    $0.01    1m0s  1h54m20s  $1.64
```

Kudos to @herkolategan for catching this problem before it cost us a significant amount of money.

Jira issue: CRDB-36842

### PR DESCRIPTION
**Pull request by vidit-bhat**
Previously, when creating a GCE cluster on roachprod we were ignoring the cost of the boot disk.
This change ensures that we also account for the cost of the boot disk.

Epic: none
Fixes: #120728
Release note: None

### CODE REVIEW

**Review by DarrylWong — COMMENTED** [review]
Nice! I left two nits to reduce the amount of code duplication but it looks like your change works! :partying_face: 



> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121938#-:-Nuz62bqB9etUxe-MW3K:b-2xerie)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @renatolabs, @srosenberg, and @vidit-bhat)

___
*[`pkg/roachprod/vm/gce/gcloud.go` line 234 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121938#-Nuz33847wZSB2OSEpc6:-Nuz33847wZSB2OSEpc7:bcimubb) ([raw file](https://github.com/cockroachdb/cockroach/blob/69506c72aca27d1c33d70c340149a1f6f216b4b6/pkg/roachprod/vm/gce/gcloud.go#L234)):*
> ```Go
> 						Size:               parseDiskSize(detailedDisk.SizeGB),
> 					}
> 					volumes = append(volumes, vol)
> ```

nit: We can move `!jsonVMDisk.Boot` from above down here and do: 

```
if !jsonVMDisk.Boot  {
    volumes = append(volumes, vol)
} else {
    bootVolume = vol
}
```

And then get rid of the else case entirely.
___
*[`pkg/roachprod/vm/gce/gcloud.go` line 2554 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121938#-Nuz3QtE-OK0eVsPpgKe:-Nuz3QtE-OK0eVsPpgKf:b-rjizkf) ([raw file](https://github.com/cockroachdb/cockroach/blob/69506c72aca27d1c33d70c340149a1f6f216b4b6/pkg/roachprod/vm/gce/gcloud.go#L2554)):*
> ```Go
> 				}
> 			}
> 			for _, v := range vm.NonBootAttachedVolumes {
> ```

nit: instead we can do

```
			volumes := append(vm.NonBootAttachedVolumes, vm.BootVolume)
			for _, v := range volumes {
```

And get rid of the duplicated logic.

**Comment by vidit-bhat** [comment]
Nice catches! Updated

**Review by DarrylWong — APPROVED** [review]
LGTM

**Review by srosenberg — APPROVED** [review]

**Review by renatolabs — APPROVED** [review]

**Review by herkolategan — APPROVED** [review]

**Comment by srosenberg** [comment]
We should probably backport this into 24.1, 23.2 and 23.1; shouldn't result in (many) conflicts.

**Comment by vidit-bhat** [comment]
blathers backport 24.1 23.2 23.1

**Pull request merged**
