### PR TITLE
sql: change zone name syntax to match SQL

### PR DESCRIPTION
**Pull request by solongordon**
Per Raphael's suggestion, I updated zone names to match the SQL
identifier you would use to alter the zone. Examples:

```
before                   | after
-------------------------+---------------------------------------------------
.meta                    | RANGE meta
movr                     | DATABASE movr
movr.users               | TABLE movr.public.users
movr.users@name_idx      | INDEX movr.public.users@name_idx
movr.users.asia          | PARTITION asia OF TABLE movr.public.users
movr.users@name_idx.asia | PARTITION asia OF INDEX movr.public.users@name_idx
```

This is nice for a few reasons. One is that it has a direct relationship
with the SQL syntax rather than being a bespoke syntax only for
referring to zones. Another is that it makes it easy to remove or alter
a batch of zones. For instance, some of our tests need to set
`num_replicas = 1` across all zones.

Release note: None

### CODE REVIEW

**Comment by solongordon** [comment]
I wonder if it would make more sense to call this something different from a "zone name". Maybe something like "target"?

**Review by knz — COMMENTED** [review]
Amazing work, thanks for getting this out so fast. "target" sounds good to me.

Just ensure this works properly with special identifiers, then this is good to go.

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39404#-:-LlgyD7z4HoS55LHZpso:biw6p0p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @rohany, and @solongordon)

___
*[pkg/ccl/logictestccl/testdata/logic_test/zone, line 504 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39404#-LlgxuPnALpCMnGrxCML:-LlgxuPo0MCNEKuPWft-:b-wben6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/47adc8b9a1f1f73a2407e7b7f7363b800d6446c6/pkg/ccl/logictestccl/testdata/logic_test/zone#L504)):*
> ```
> FROM crdb_internal.zones
> ----
> RANGE default                                     default   NULL    NULL    NULL       NULL
> ```

Please put a few examples ALTER, SHOW and DROP for a zone on identifiers containing special characters, to illustrate+test the UX of properly quoting identifiers.

`create database "hello world"`

`create table "hello world"`

`create index "hello world"`

`partition "hello world"`

then add the zones for each of them

**Comment by danhhz** [comment]
cool! i'll leave the review to knz, but I love the idea

**Review by rohany — COMMENTED** [review]
i like the idea -- its much clearer than the old zone names.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39404#-:-Llhbhp68AFIyq3gZKhw:bdw4bk1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @rohany, and @solongordon)

**Comment by awoods187** [comment]
this is awesome

**Review by solongordon — COMMENTED** [review]
Updates:
- Add logic tests for quoted identifiers.
- Rename zone_name to target everywhere.
- Ensure that table names are fully qualified in the event log.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39404#-:-Llhe8Ok0vARuFlhGFOu:b-1sajsm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz and @knz)

___
*[pkg/ccl/logictestccl/testdata/logic_test/zone, line 504 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39404#-LlgxuPnALpCMnGrxCML:-Llhe7OG8Tt1Wc1P0tn0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/47adc8b9a1f1f73a2407e7b7f7363b800d6446c6/pkg/ccl/logictestccl/testdata/logic_test/zone#L504)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please put a few examples ALTER, SHOW and DROP for a zone on identifiers containing special characters, to illustrate+test the UX of properly quoting identifiers.

`create database "hello world"`

`create table "hello world"`

`create index "hello world"`

`partition "hello world"`

then add the zones for each of them
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
:100: 

> Reviewed 16 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39404#-:-Lli2-Z26ff6Yu0uta66:bmi8ppe)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz)

**Comment by knz** [comment]
just a flake
```
		 IO error: While lock file: /home/roach/local/3/data/cockroach-temp226209764/TEMP_DIR.LOCK: Resource temporarily unavailable
```

bors r+

**Comment by knz** [comment]
external docker failure

```
	panic: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.0.53:53: read udp 127.0.0.1:56495->127.0.0.53:53: read: connection refused
```

we're in the hot hours of california...

bors r+_

**Comment by knz** [comment]
this again looks like a flake but if as I suspect there's a glut of west coast activity, there's only so much I can do now :sweat_smile:

**Comment by knz** [comment]
maybe morning hours are quieter?

bors r+

**Comment by knz** [comment]
they were indeed :tada:

**Pull request merged**
