### PR TITLE
jobs: check GCMutations when checking for orphaned jobs

### PR DESCRIPTION
**Pull request by pbardea**
We periodically GC jobs from the jobs table, this includes collecting
orphaned running jobs. However, jobs could still be referenced by a
GCMutation or the job that drops the table (and therefore not be
orphaned).

Release note (bug fix): Fix a bug where drop index jobs waiting for GC
TTL might be erroneously deleted early. Usually a DROP INDEX job would
appear as "waiting for GC TTL" to indicate that the data is still on
disk, however this bug would may cause this job to be deleted before the
data was actually removed from disk.

### CODE REVIEW

**Comment by pbardea** [comment]
This still needs a test.

**Review by thoszhang — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea and @spaskob)

___
*[pkg/jobs/registry.go, line 433 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44831#-M-RJWY11zvpleYAbPFY:-M-RJWY29SEf83K_qjb1:b-f18dbi) ([raw file](https://github.com/cockroachdb/cockroach/blob/08b87f8e92f93ff1204302317d9a322ece004a1e/pkg/jobs/registry.go#L433)):*
> ```Go
> 				return err
> 			}
> 			if len(td.GetMutations()) != 0 || len(td.GetGCMutations()) != 0 {
> ```

Should we also check `TableDescriptor.DropJobID` (which is just the ID for the job that's dropping the table)?

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @spaskob)

___
*[pkg/jobs/registry.go, line 433 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44831#-M-RJWY11zvpleYAbPFY:-M-RSB2-3a9Ok2Bvl9nm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/08b87f8e92f93ff1204302317d9a322ece004a1e/pkg/jobs/registry.go#L433)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Should we also check `TableDescriptor.DropJobID` (which is just the ID for the job that's dropping the table)? 
</blockquote></details>

Done.

**Review by pbardea — COMMENTED** [review]
Added tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44831#-:-M-RSKbP-cixjs6c6WPG:bufim0i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @spaskob)

**Review by spaskob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @spaskob)

___
*[pkg/jobs/registry.go, line 433 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44831#-M-RJWY11zvpleYAbPFY:-M-RVsXu7BmVVQ0_f8Yv:bmticz6) ([raw file](https://github.com/cockroachdb/cockroach/blob/08b87f8e92f93ff1204302317d9a322ece004a1e/pkg/jobs/registry.go#L433)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: you don't need an if, you can just assign the if condition to pendingMutations

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/jobs/registry.go, line 433 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44831#-M-RJWY11zvpleYAbPFY:-M-RWqZu7O5oMTvcYmMH:buzjopq) ([raw file](https://github.com/cockroachdb/cockroach/blob/08b87f8e92f93ff1204302317d9a322ece004a1e/pkg/jobs/registry.go#L433)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

nit: you don't need an if, you can just assign the if condition to pendingMutations
</blockquote></details>

Done. I was on the edge of how readable this was when the condition got longer, but decided to go back to the one liner.

**Review by spaskob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/jobs/registry.go, line 433 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44831#-M-RJWY11zvpleYAbPFY:-M-SFxJeA5n0dnl1pqCC:bam4db1) ([raw file](https://github.com/cockroachdb/cockroach/blob/08b87f8e92f93ff1204302317d9a322ece004a1e/pkg/jobs/registry.go#L433)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Done. I was on the edge of how readable this was when the condition got longer, but decided to go back to the one liner.
</blockquote></details>

sg, if you are worried about readability you can always split the operands:

mutantions := len(td.GetMutations()) != 0; ....; pendingMutations := mutations || gcMutations || dropJob

**Review by spaskob — APPROVED** [review]
Thanks for fixing this!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44831#-:-M-SGm7jBVZBm4H1_gvM:b-whxd1j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/jobs/registry.go, line 433 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44831#-M-RJWY11zvpleYAbPFY:-M-Spblu82uTV7Ojt-d0:b-1b5h75) ([raw file](https://github.com/cockroachdb/cockroach/blob/08b87f8e92f93ff1204302317d9a322ece004a1e/pkg/jobs/registry.go#L433)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

sg, if you are worried about readability you can always split the operands:

mutantions := len(td.GetMutations()) != 0; ....; pendingMutations := mutations || gcMutations || dropJob
</blockquote></details>

I ended up liking something in between and grouped the mutation checks and the job check separately.

**Review by spaskob — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/jobs/registry.go, line 433 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44831#-M-RJWY11zvpleYAbPFY:-M-UugX88wUN8j5QAgbU:bq9s42r) ([raw file](https://github.com/cockroachdb/cockroach/blob/08b87f8e92f93ff1204302317d9a322ece004a1e/pkg/jobs/registry.go#L433)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I ended up liking something in between and grouped the mutation checks and the job check separately.
</blockquote></details>

much better!

**Review by thoszhang — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44831)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by pbardea** [comment]
TFTRs
bors r=lucy-zhang,spaskob

**Comment by andreimatei** [comment]
nit: the release note is not comprehensible by users. Or by me, for that matter. Please try to explain what the effect of the bug / of the fix are.

**Comment by pbardea** [comment]
Updated release note.
bors r=lucy-zhang,spaskob

**Pull request merged**
