### PR TITLE
catalog: add namespace validation

### LINKED ISSUE #61010: sql/catalog: add namespace validation
**Is your feature request related to a problem? Please describe.**

Descriptor validation does not currently validate the structure of namespace. This leaves room for bugs in the implementation of various schema changes.

**Additional context**

There are short and long-term risks with adding this validation.

A risk are that we uncover old bugs which have left the namespace table in an invalid state which prohibit certain activities. Previous additions of validation have prevented common behaviors like `SHOW TABLES` and `BACKUP` from working until the corruption is resolved (see https://github.com/cockroachdb/cockroach/issues/56810 among others). The addition of `crdb_internal.unsafe_(upsert|delete)_namespace_entry` should help -- but those functions are not perfect. Regardless, they are hard to use and need some expert consultation.

A mitigation to this risk is to find ways to suppress this new validation (or perhaps all validation?) in specific scenarios. There are clear tradeoffs either way on that front. Probably `SHOW TABLES` should remain rather resilient. `BACKUP` is more nuanced. `DROP` is also an interesting case (see https://github.com/cockroachdb/cockroach/issues/50651). How exactly the code interfaces would look for this is also unclear. Two approaches are to utilize sentinal errors and filter them at the appropriate levels or to provide flags to suppress the error that will be terminated at a lower level. The problem with the latter approach is that we aren't principled about our flags or the layers at the present moment. If we wait a bit to refactor that code then that may be a more tenable approach. 

Another consideration is the extra namespace lookups incurring extra round-trips. This can be mitigated with batching the namespace lookups with descriptor lookups. 

One proposal to mitigate the short term risk would be to suppress this additional validation from bubbling up in general in this release and instead have it fire off sentry reports. That approach is not free from the namespace lookup issues.

There is a WIP PR to add this validation [here](https://github.com/cockroachdb/cockroach/pull/61009)

### PR DESCRIPTION
**Pull request by postamar**
Previously, the contents of the namespace table were only ever validated
by the doctor tool. This commit adds namespace validation checks into the
existing descriptor validation framework in the catalog package. These
checks are now run as part of the pre-txn-commit descriptor validation
suite.

Fixes #61010.

Release note (cli change): changed formatting of namespace validation
failures in doctor.

### CODE REVIEW

**Comment by postamar** [comment]
Note that this doesn't report namespace validation errors to sentry or anything but bubbles them up just like any other validation error.

**Review by ajwerner — COMMENTED** [review]
Just the pg_temp comment. Otherwise :lgtm: 

> Reviewed 20 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61961#-:-MW4We2O4KQjTsfBS2TY:b-rxowx3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy and @postamar)

___
*[pkg/sql/catalog/desc_getter.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61961#-MW4VttPDj7Gc5Z5jReW:-MW4VttPDj7Gc5Z5jReX:b-7ffa6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc25c6e65245a0adee3000fc7480844df3ce9aa9/pkg/sql/catalog/desc_getter.go#L24)):*
> ```Go
> // Lookups are performed on a best-effort basis. When a descriptor or namespace
> // entry cannot be found, the zero-value is returned, with no error.
> type DescGetter interface {
> ```

This name is feeling bad but I don't immediately have one I like more. `Store` could be okay. 
___
*[pkg/sql/catalog/catalogkv/desc_getter.go, line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61961#-MW4UiaLD3CQBDAI5xBa:-MW4UiaLD3CQBDAI5xBb:bws8jcx) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc25c6e65245a0adee3000fc7480844df3ce9aa9/pkg/sql/catalog/catalogkv/desc_getter.go#L125)):*
> ```Go
> 	isBatchEmpty := true
> 	for _, r := range requests {
> 		if r.Name == "" {
> ```

when does this happen?
___
*[pkg/sql/doctor/doctor.go, line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61961#-MW4VBxy0DOLSIz9DGLE:-MW4VBxy0DOLSIz9DGLF:b-vak45l) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc25c6e65245a0adee3000fc7480844df3ce9aa9/pkg/sql/doctor/doctor.go#L174)):*
> ```Go
> 		return nil
> 	}
> 	if strings.HasPrefix(row.Name, "pg_temp_") {
> ```

I think this policy should only apply to schemas (i.e. ParentSchemaID == descpb.InvalidSchemaID but has a ParentID). Also, users can create things with this prefix I'm pretty sure (not a good idea but alas). Maybe instead we should just allow the descriptor to not exist in this case rather than avoiding validation?

FWIW I am very sad about temp tables. I know why we did it, but I'm sad.

**Review by postamar — COMMENTED** [review]
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61961#-:-MW6-e5x2u6ar0GSqmw5:b-9qdoz3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @miretskiy)

___
*[pkg/sql/catalog/desc_getter.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61961#-MW4VttPDj7Gc5Z5jReW:-MW5z_KDDYKngsAJQsYH:b-harowc) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc25c6e65245a0adee3000fc7480844df3ce9aa9/pkg/sql/catalog/desc_getter.go#L24)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This name is feeling bad but I don't immediately have one I like more. `Store` could be okay. 
</blockquote></details>

I'm scratching my head too. It's basically a dependency injection mechanism for either pretending to- or actually looking up stored catalog objects from storage. 
___
*[pkg/sql/catalog/catalogkv/desc_getter.go, line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61961#-MW4UiaLD3CQBDAI5xBa:-MW5zqM-5t7f5EyUY0YZ:b-2blqx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc25c6e65245a0adee3000fc7480844df3ce9aa9/pkg/sql/catalog/catalogkv/desc_getter.go#L125)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

when does this happen?
</blockquote></details>

I suspect never but it's a super cheap and harmless request validation check so I'm inclined to leave it there.
___
*[pkg/sql/doctor/doctor.go, line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61961#-MW4VBxy0DOLSIz9DGLE:-MW6-IFz5zWvPH14G7Kb:b7ffdjk) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc25c6e65245a0adee3000fc7480844df3ce9aa9/pkg/sql/doctor/doctor.go#L174)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think this policy should only apply to schemas (i.e. ParentSchemaID == descpb.InvalidSchemaID but has a ParentID). Also, users can create things with this prefix I'm pretty sure (not a good idea but alas). Maybe instead we should just allow the descriptor to not exist in this case rather than avoiding validation?

FWIW I am very sad about temp tables. I know why we did it, but I'm sad. 
</blockquote></details>

Ugh, right, so that's what it is.
I think this is the only occasion where we browse the namespace table to validate the descriptors referred therein so I'll leave it as is but with the check for schemas you suggested.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61961#-:-MW62LSN5XjnFkznSOKK:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[pkg/sql/catalog/desc_getter.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61961#-MW4VttPDj7Gc5Z5jReW:-MW61Tj-6vM07WHIROkl:b-qpbi90) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc25c6e65245a0adee3000fc7480844df3ce9aa9/pkg/sql/catalog/desc_getter.go#L24)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I'm scratching my head too. It's basically a dependency injection mechanism for either pretending to- or actually looking up stored catalog objects from storage. 
</blockquote></details>

Right, but not quite the raw stored catalog object. One issue I have with it now is that it doesn't really help us understand whether a descriptor is "hydrated". That concept is sort of bespoke at the moment but I suspect it will become more real over time. I'm bullish on storing references to things like databases and schemas in objects but have doubts about when we'd get around to doing it. My sense is that so much complexity comes from not having that.

**Pull request merged**
