### PR TITLE
kvserver: update TestSystemZoneConfigs

### LINKED ISSUE #98200: kv/kvserver: TestSystemZoneConfigs failed
kv/kvserver.TestSystemZoneConfigs [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/8965166?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/8965166?buildTab=artifacts#/) on master @ [1b162d1b274eec7b307fbbfca7294460bfdef025](https://github.com/cockroachdb/cockroach/commits/1b162d1b274eec7b307fbbfca7294460bfdef025):

```
=== RUN   TestSystemZoneConfigs
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/9ded2e1b6e3cd0145900033ce06c11b0/logTestSystemZoneConfigs2842108216
    test_log_scope.go:79: use -show-logs to present logs inline
    client_replica_test.go:2768: condition failed to evaluate within 45s: got 288 voters, want 290; details: map[1:r1:/{Min-System/NodeLiveness} [(n1,s1):1, (n4,s4):2, (n6,s6):3, (n2,s2):4, (n7,s7):5, next=6, gen=8] 2:r2:/System/NodeLiveness{-Max} [(n1,s1):1, (n3,s3):2, (n4,s4):3, (n6,s6):4, (n7,s7):5, next=6, gen=8] 3:r3:/System/{NodeLivenessMax-tsd} [(n1,s1):1, (n6,s6):2, (n7,s7):3, (n3,s3):4, (n5,s5):5, next=6, gen=8] 4:r4:/System{/tsd-tse} [(n3,s3):4, (n6,s6):2, (n2,s2):3, next=5, gen=8] 5:r5:/{Systemtse-Table/0} [(n1,s1):1, (n2,s2):2, (n5,s5):3, (n3,s3):4, (n6,s6):5, next=6, gen=8] 6:r6:/Table/{0-3} [(n1,s1):1, (n7,s7):2, (n5,s5):3, (n6,s6):4, (n2,s2):5, next=6, gen=8] 7:r7:/Table/{3-4} [(n1,s1):1, (n5,s5):2, (n2,s2):3, (n7,s7):4, (n4,s4):5, next=6, gen=8] 8:r8:/Table/{4-5} [(n1,s1):1, (n5,s5):2, (n3,s3):3, (n4,s4):4, (n2,s2):5, next=6, gen=8] 9:r9:/Table/{5-6} [(n2,s2):6, (n3,s3):2, (n5,s5):3, (n4,s4):4, (n6,s6):5, next=7, gen=12] 10:r10:/Table/{6-7} [(n1,s1):1, (n5,s5):2, (n7,s7):3, (n4,s4):4, (n2,s2):5, next=6, gen=8] 11:r11:/Table/{7-8} [(n1,s1):1, (n6,s6):2, (n4,s4):3, (n3,s3):4, (n2,s2):5, next=6, gen=8] 12:r12:/Table/{8-11} [(n1,s1):1, (n5,s5):2, (n2,s2):3, (n3,s3):4, (n4,s4):5, next=6, gen=8] 13:r13:/Table/1{1-2} [(n1,s1):1, (n6,s6):2, (n3,s3):3, (n4,s4):4, (n7,s7):5, next=6, gen=8] 14:r14:/Table/1{2-3} [(n1,s1):1, (n7,s7):2, (n4,s4):3, (n2,s2):4, (n3,s3):5, next=6, gen=8] 15:r15:/Table/1{3-4} [(n1,s1):1, (n2,s2):2, (n4,s4):3, (n3,s3):4, (n7,s7):5, next=6, gen=8] 16:r16:/Table/1{4-5} [(n5,s5):6, (n3,s3):2, (n4,s4):3, (n7,s7):4, (n2,s2):5, next=7, gen=12] 17:r17:/Table/1{5-6} [(n1,s1):1, (n5,s5):2, (n3,s3):3, (n6,s6):4, (n7,s7):5, next=6, gen=8] 18:r18:/Table/1{6-7} [(n3,s3):6, (n4,s4):2, (n5,s5):3, (n6,s6):4, (n7,s7):5, next=7, gen=12] 19:r19:/Table/1{7-8} [(n1,s1):1, (n4,s4):2, (n6,s6):3, (n2,s2):4, (n5,s5):5, next=6, gen=8] 20:r20:/Table/1{8-9} [(n1,s1):1, (n7,s7):2, (n2,s2):3, (n5,s5):4, (n6,s6):5, next=6, gen=8] 21:r21:/Table/{19-20} [(n1,s1):1, (n7,s7):2, (n2,s2):3, (n6,s6):4, (n5,s5):5, next=6, gen=8] 22:r22:/Table/2{0-1} [(n1,s1):1, (n7,s7):2, (n6,s6):3, (n4,s4):4, (n5,s5):5, next=6, gen=8] 23:r23:/Table/2{1-2} [(n1,s1):1, (n7,s7):2, (n6,s6):3, (n3,s3):4, (n4,s4):5, next=6, gen=8] 24:r24:/Table/2{2-3} [(n1,s1):1, (n7,s7):2, (n6,s6):3, (n5,s5):4, (n3,s3):5, next=6, gen=8] 25:r25:/Table/2{3-4} [(n4,s4):6, (n2,s2):2, (n3,s3):3, (n7,s7):4, (n6,s6):5, next=7, gen=12] 26:r26:/Table/2{4-5} [(n5,s5):6, (n2,s2):2, (n4,s4):3, (n3,s3):4, (n7,s7):5, next=7, gen=12] 27:r27:/Table/2{5-6} [(n2,s2):6, (n4,s4):2, (n7,s7):3, (n5,s5):4, (n3,s3):5, next=7, gen=12] 28:r28:/Table/2{6-7} [(n1,s1):1, (n4,s4):2, (n2,s2):3, (n5,s5):4, (n3,s3):5, next=6, gen=8] 29:r29:/Table/2{7-8} [(n4,s4):6, (n3,s3):2, (n2,s2):3, (n7,s7):4, (n6,s6):5, next=7, gen=12] 30:r30:/Table/2{8-9} [(n1,s1):1, (n4,s4):2, (n5,s5):3, (n2,s2):4, (n7,s7):5, next=6, gen=8] 31:r31:/{Table/29-NamespaceTable/30} [(n1,s1):1, (n7,s7):2, (n4,s4):3, (n3,s3):4, (n6,s6):5, next=6, gen=8] 32:r32:/NamespaceTable/{30-Max} [(n1,s1):1, (n5,s5):2, (n4,s4):3, (n2,s2):4, (n6,s6):5, next=6, gen=8] 33:r33:/{NamespaceTable/Max-Table/32} [(n1,s1):1, (n5,s5):2, (n3,s3):3, (n7,s7):4, (n4,s4):5, next=6, gen=8] 34:r34:/Table/3{2-3} [(n1,s1):1, (n6,s6):2, (n7,s7):3, (n3,s3):4, (n2,s2):5, next=6, gen=8] 35:r35:/Table/3{3-4} [(n6,s6):6, (n4,s4):2, (n3,s3):3, (n5,s5):4, (n7,s7):5, next=7, gen=12] 36:r36:/Table/3{4-5} [(n1,s1):1, (n3,s3):2, (n5,s5):3, (n4,s4):4, (n2,s2):5, next=6, gen=8] 37:r37:/Table/3{5-6} [(n1,s1):1, (n3,s3):2, (n7,s7):3, (n2,s2):4, (n4,s4):5, next=6, gen=8] 38:r38:/Table/3{6-7} [(n1,s1):1, (n6,s6):2, (n5,s5):3, (n2,s2):4, (n3,s3):5, next=6, gen=8] 39:r39:/Table/3{7-8} [(n1,s1):1, (n3,s3):2, (n7,s7):3, (n5,s5):4, (n6,s6):5, next=6, gen=8] 40:r40:/Table/3{8-9} [(n6,s6):6, (n4,s4):2, (n2,s2):3, (n7,s7):4, (n5,s5):5, next=7, gen=12] 41:r41:/Table/{39-40} [(n1,s1):1, (n6,s6):2, (n7,s7):3, (n5,s5):4, (n4,s4):5, next=6, gen=8] 42:r42:/Table/4{0-1} [(n1,s1):1, (n6,s6):2, (n7,s7):3, (n5,s5):4, (n3,s3):5, next=6, gen=8] 43:r43:/Table/4{1-2} [(n3,s3):6, (n2,s2):2, (n7,s7):3, (n4,s4):4, (n6,s6):5, next=7, gen=12] 44:r44:/Table/4{2-3} [(n1,s1):1, (n6,s6):2, (n3,s3):3, (n2,s2):4, (n5,s5):5, next=6, gen=8] 45:r45:/Table/4{3-4} [(n1,s1):1, (n5,s5):2, (n3,s3):3, (n6,s6):4, (n4,s4):5, next=6, gen=8] 46:r46:/Table/4{4-5} [(n2,s2):6, (n3,s3):2, (n6,s6):3, (n4,s4):4, (n5,s5):5, next=7, gen=12] 47:r47:/Table/4{5-6} [(n1,s1):1, (n2,s2):2, (n6,s6):3, (n7,s7):4, (n5,s5):5, next=6, gen=8] 48:r48:/Table/4{6-7} [(n1,s1):1, (n5,s5):2, (n2,s2):3, (n6,s6):4, (n4,s4):5, next=6, gen=8] 49:r49:/Table/4{7-8} [(n1,s1):1, (n5,s5):2, (n2,s2):3, (n4,s4):4, (n3,s3):5, next=6, gen=8] 50:r50:/Table/{48-50} [(n1,s1):1, (n7,s7):2, (n6,s6):3, (n5,s5):4, (n2,s2):5, next=6, gen=8] 51:r51:/Table/5{0-1} [(n4,s4):6, (n2,s2):2, (n6,s6):3, (n3,s3):4, (n7,s7):5, next=7, gen=12] 52:r52:/Table/5{1-2} [(n1,s1):1, (n2,s2):2, (n4,s4):3, (n6,s6):4, (n7,s7):5, next=6, gen=8] 53:r53:/Table/5{2-3} [(n1,s1):1, (n6,s6):2, (n5,s5):3, (n7,s7):4, (n3,s3):5, next=6, gen=8] 54:r54:/Table/5{3-4} [(n6,s6):6, (n2,s2):2, (n7,s7):3, (n5,s5):4, (n4,s4):5, next=7, gen=12] 55:r55:/Table/5{4-5} [(n7,s7):6, (n4,s4):2, (n5,s5):3, (n2,s2):4, (n3,s3):5, next=7, gen=12] 56:r56:/Table/5{5-6} [(n1,s1):1, (n3,s3):2, (n4,s4):3, (n5,s5):4, (n7,s7):5, next=6, gen=8] 57:r57:/Table/5{6-7} [(n1,s1):1, (n3,s3):2, (n2,s2):3, (n4,s4):4, (n6,s6):5, next=6, gen=8] 58:r58:/{Table/57-Max} [(n1,s1):1, (n3,s3):2, (n6,s6):3, (n2,s2):4, (n5,s5):5, next=6, gen=8]]
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/9ded2e1b6e3cd0145900033ce06c11b0/logTestSystemZoneConfigs2842108216
--- FAIL: TestSystemZoneConfigs (56.08s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestSystemZoneConfigs.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-25127

### PR DESCRIPTION
**Pull request by irfansharif**
Fixes #98200. This test was written pre-spanconfig days, and when enabling spanconfigs by default, opted out of using it. This commit makes it use spanconfigs after giving up on reproducing/diagnosing the original flake (this test is notoriously slow -- taking 30+s given it waits for actual upreplication and replica movement, so not --stress friendly).

Using spanconfigs here surfaced a rare, latent bug, one this author incorrectly thought was fixed back in #75939. In very rare cases, right during cluster bootstrap before the span config reconciler has ever had a chance to run (i.e. system.span_configurations is empty), it's possible that the subscriber has subscribed to an empty span config state (we've only seen this happen in unit tests with 50ms scan intervals). So it's not been meaningfully "updated" in any sense of the word, but we still previously set a non-empty last-updated timestamp, something various components in KV rely on as proof that we have span configs as of some timestamp. As a result, we saw KV incorrectly merge away the liveness range into adjacent ranges, and then later split it off. We don't think we've ever seen this happen outside of tests as it instantly triggers the following fatal in the raftScheduler, which wants to prioritize the liveness range above all else:

    panic: priority range ID already set: old=2, new=61, first set at:

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm: besides unimportant nits. Thanks for deflaking this.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100210#-:-NRoccz7Ec3_vUYM3w6e:b-z8z2wk)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @irfansharif)

___
*[`pkg/kv/kvserver/client_replica_test.go` line 2723 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100210#-NRocX5T5YimkBeG9wfG:-NRocX5T5YimkBeG9wfH:b-r2j3p6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e64b899e325d37bd86731e5b6db52c2c97b0302a/pkg/kv/kvserver/client_replica_test.go#L2723)):*
> ```Go
> 	// Span configs however collapse the known-empty /Table/{0-3} keyspace into
> 	// the adjacent range, so we have:
> 	//
> ```

nit: remove empty line here or add it above for symmetry.
___
*[`pkg/kv/kvserver/client_replica_test.go` line 2758 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100210#-NRocC_F4NbxHYBJoSdk:-NRocC_F4NbxHYBJoSdl:b-vkcyvm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e64b899e325d37bd86731e5b6db52c2c97b0302a/pkg/kv/kvserver/client_replica_test.go#L2758)):*
> ```Go
> 			totalReplicas += len(desc.Replicas().VoterDescriptors())
> 		}
> 		sortedDesc := make([]roachpb.RangeDescriptor, 0, 0)
> ```

nit: not that it matters, but why pre-allocate the slice if you aren't giving it capacity? I'd expect either `var sortedDesc []roachpb.RangeDescriptor` or `sortedDesc := make([]roachpb.RangeDescriptor, 0, len(replicas))`

**Review by irfansharif — COMMENTED** [review]
Updating this test uncovered another real (but rare) span config integration bug -- PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100210#-:-NS6B5po43C6LYm-gGVT:b-wt4zwi)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani and @nvanbenschoten)

**Review by arulajmani — APPROVED** [review]
Nice find! :lgtm: modulo comment. 

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100210#-:-NS6V1D9EYrHCY9d3_sF:bbfqvwl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif)

___
*[`pkg/kv/kvserver/queue_helpers_testutil.go` line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100210#-NS6UYwR02-13toJ5zfw:-NS6UYwR02-13toJ5zfx:bpxx0a8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f63663b578ce19cb9b9a9b7f012a532f28a5000a/pkg/kv/kvserver/queue_helpers_testutil.go#L33)):*
> ```Go
> func forceScanAndProcess(ctx context.Context, s *Store, q *baseQueue) error {
> 	if q.queueConfig.needsSpanConfigs {
> 		// Check that the system config is available. It is needed by many
> ```

nit: "Check that the span config state is available" 
___
*[`pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber.go` line 416 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100210#-NS6Tn6A2bGyYseqLYIq:-NS6Tn6A2bGyYseqLYIr:b-x4cow6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f63663b578ce19cb9b9a9b7f012a532f28a5000a/pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber.go#L416)):*
> ```Go
> 		// some timestamp.
> 		s.setLastUpdatedLocked(ts)
> 	}
> ```

Let's pull all of this into `handleUpdate` instead? Then you don't have to duplicate things between this function and `handlePartialUpdate`.

Once we do that, could we just return early from `handleUpdate` as well? 



_Code quote:_
```Go
	if len(events) != 0 {
		// In very rare cases, right during cluster bootstrap before the span
		// config reconciler has ever had a chance to run (i.e.
		// system.span_configurations is empty), it's possible that the
		// subscriber has subscribed to an empty span config state. We've only
		// seen this happen in unit tests with 50ms scan intervals. So it's not
		// been meaningfully "updated" in any sense of the word -- we'll perhaps
		// get the initial state in the next partial update. We don't set the
		// last-updated timestamp until then -- various components in KV rely on
		// this timestamp to be non-empty as proof we have span configs as of
		// some timestamp.
		s.setLastUpdatedLocked(ts)
	}
```

**Comment by irfansharif** [comment]
#104198.

**Pull request closed without merging**
