### PR TITLE
storage: retry splits more

### PR DESCRIPTION
**Pull request by tbg**
In tpccbench/nodes=9/cpu=4/multi-region, I consistently see the RESTORE
fail a split because the retry loop in executeAdminCommandWithDescriptor
interleaves with replicate queue activity until the retries are
exhausted. This is likely since due to the geo-replicated nature of the
cluster, the many steps involved in replicating the range take much
longer than we're used to; in the logs I can see the split attempt
and an interleaving replication change taking turns until the split
gives up. The solution is to just retry the split forever as long
as we're only seeing errors we know should eventually resolve.

Touches #41028.

Release justification: fixes roachtest failure, is low risk

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]

**Comment by nvanbenschoten** [comment]
@ajwerner's idea to perform some best-effort locking on the leaseholder would also help here. Is there an open issue for that?

**Comment by tbg** [comment]
TFTR!

bors r=nvanbenschoten

**Comment by tbg** [comment]
CI failed because I failed to update (by way of removing) a test that verified the old behavior. Nathan and I agreed that the old behavior is FUD and that the original problem that originally prompted the retry limit does not apply any more.

bors r=nvanbenschoten

**Comment by tbg** [comment]
no space left on device during `make bench`

bors r=nvanbenschoten

**Pull request merged**
