### PR TITLE
storage: create new TestSnapshotAfterTruncationWithUncommittedTail test

### PR DESCRIPTION
**Pull request by nvb**
This PR adds a regression test for #37056. In doing so, it also confirms
the theory that #37055 is the proper fix for that bug.

Before #37055, the test would get stuck with the following logs repeatedly
firing:
```
I190424 00:15:52.338808 12 storage/client_test.go:1242  SucceedsSoon: expected [21 21 21], got [12 21 21]
I190424 00:15:52.378060 78 vendor/go.etcd.io/etcd/raft/raft.go:1317  [s1,r1/1:/M{in-ax}] 1 [logterm: 6, index: 31] rejected msgApp [logterm: 8, index: 31] from 2
I190424 00:15:52.378248 184 vendor/go.etcd.io/etcd/raft/raft.go:1065  [s2,r1/2:/M{in-ax}] 2 received msgApp rejection(lastindex: 31) from 1 for index 31
I190424 00:15:52.378275 184 vendor/go.etcd.io/etcd/raft/raft.go:1068  [s2,r1/2:/M{in-ax}] 2 decreased progress of 1 to [next = 31, match = 31, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
```

After #37055, the test passes.

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37058)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/storage/client_merge_test.go, line 2994 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37058#-LdBxa7T7y2A0WuHZhoT:-LdBxa7T7y2A0WuHZhoU:btwni9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/00f587664d0d2d1130b804cf84c95d38832cfd90/pkg/storage/client_merge_test.go#L2994)):*
> ```Go
> 	if len(req.Heartbeats)+len(req.HeartbeatResps) > 0 {
> 		reqCpy := *req
> 		*req = reqCpy
> ```

Why make a shallow copy in both directions? This doesn't look like it does anything. Should the second line be `req = &reqCpy`?
___
*[pkg/storage/client_raft_test.go, line 867 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37058#-LdBzS-b17TpuYIwyUGn:-LdBzS-b17TpuYIwyUGo:b-lmrycy) ([raw file](https://github.com/cockroachdb/cockroach/blob/00f587664d0d2d1130b804cf84c95d38832cfd90/pkg/storage/client_raft_test.go#L867)):*
> ```Go
> 	ctx := context.Background()
> 	mtc := &multiTestContext{
> 		// This test was written before the multiTestContext started creating many
> ```

Not quite true in this case, but OK. 
___
*[pkg/storage/client_raft_test.go, line 941 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37058#-LdC-hT35crh1nyRE0Pl:-LdC-hT35crh1nyRE0Pm:bq4pv87) ([raw file](https://github.com/cockroachdb/cockroach/blob/00f587664d0d2d1130b804cf84c95d38832cfd90/pkg/storage/client_raft_test.go#L941)):*
> ```Go
> 	for i := 0; i < 32; i++ {
> 		cCtx, cancel := context.WithTimeout(ctx, 25*time.Millisecond)
> 		defer cancel()
> ```

These deferred cancels will pile up until the end of the outer function. Should this be wrapped in a func literal to run them sooner? 
___
*[pkg/storage/client_raft_test.go, line 961 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37058#-LdC08F04pjPzhh6YM9_:-LdC08F04pjPzhh6YM9a:b-txr2zi) ([raw file](https://github.com/cockroachdb/cockroach/blob/00f587664d0d2d1130b804cf84c95d38832cfd90/pkg/storage/client_raft_test.go#L961)):*
> ```Go
> 	testutils.SucceedsSoon(t, func() error {
> 		mtc.advanceClock(ctx)
> 		err := newLeaderRepl.AdminTransferLease(ctx, newLeaderRepl.StoreID())
> ```

I don't think we need a transfer here. What's happening is that we're waiting for the old leader's lease to time out and then the first operation on newLeaderRepl will acquire the lease. Here that operation is an immediate transfer to itself, which is redundant - it could just be a Get. 
___
*[pkg/storage/client_raft_test.go, line 993 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37058#-LdC0e7JAiQgidBixiJH:-LdC0e7JAiQgidBixiJI:b-suac2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/00f587664d0d2d1130b804cf84c95d38832cfd90/pkg/storage/client_raft_test.go#L993)):*
> ```Go
> 	}
> 
> 	// The partitioned replica should catch up after a snapshot.
> ```

Can we assert that a snapshot was used? (maybe via a metric?)

**Review by ajwerner — APPROVED** [review]
:lgtm: I have nothing to add. Thanks for typing this up!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37058#-:-LdC7hB_CNcH4MwhZbrB:bgkosuq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/client_raft_test.go, line 936 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37058#-LdC7czl2ni6gm36vfGS:-LdC7czm-Fl14D-Ip3Ra:b-w6o057) ([raw file](https://github.com/cockroachdb/cockroach/blob/00f587664d0d2d1130b804cf84c95d38832cfd90/pkg/storage/client_raft_test.go#L936)):*
> ```
>  cancelled,
> ```
gets me every time

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37058)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @bdarnell)

___
*[pkg/storage/client_merge_test.go, line 2994 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37058#-LdBxa7T7y2A0WuHZhoT:-LdC7h1X6Tt5WlL8Mfhn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00f587664d0d2d1130b804cf84c95d38832cfd90/pkg/storage/client_merge_test.go#L2994)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Why make a shallow copy in both directions? This doesn't look like it does anything. Should the second line be `req = &reqCpy`?
</blockquote></details>

Done.
___
*[pkg/storage/client_raft_test.go, line 936 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37058#-LdC7czl2ni6gm36vfGS:-LdCAPRgA3LrkuEa6fh8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00f587664d0d2d1130b804cf84c95d38832cfd90/pkg/storage/client_raft_test.go#L936)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
>  cancelled,
> ```
gets me every time
</blockquote></details>

Done.
___
*[pkg/storage/client_raft_test.go, line 941 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37058#-LdC-hT35crh1nyRE0Pl:-LdC7zFyCt7MghDRTIJG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00f587664d0d2d1130b804cf84c95d38832cfd90/pkg/storage/client_raft_test.go#L941)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

These deferred cancels will pile up until the end of the outer function. Should this be wrapped in a func literal to run them sooner? 
</blockquote></details>

Done.
___
*[pkg/storage/client_raft_test.go, line 961 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37058#-LdC08F04pjPzhh6YM9_:-LdC91_h3-C-VgTJmOXJ:bgxjiwj) ([raw file](https://github.com/cockroachdb/cockroach/blob/00f587664d0d2d1130b804cf84c95d38832cfd90/pkg/storage/client_raft_test.go#L961)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I don't think we need a transfer here. What's happening is that we're waiting for the old leader's lease to time out and then the first operation on newLeaderRepl will acquire the lease. Here that operation is an immediate transfer to itself, which is redundant - it could just be a Get. 
</blockquote></details>

I did it like this to be explicit, but I'm fine removing the `AdminTransferLease`. In that case, I can just put the increment in the `SucceedsSoon` loop. Done.
___
*[pkg/storage/client_raft_test.go, line 993 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37058#-LdC0e7JAiQgidBixiJH:-LdC8uDJ7hLSvCKFy7no:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00f587664d0d2d1130b804cf84c95d38832cfd90/pkg/storage/client_raft_test.go#L993)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Can we assert that a snapshot was used? (maybe via a metric?)
</blockquote></details>

Done.

**Review by tbg — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37058)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @bdarnell)

**Pull request merged**
