### PR TITLE
sql,server: provide an approximate creation time for indexes

### LINKED ISSUE #72626: Add index create_date to crdb_internal.table_indexes
Knowing when an index was created will help developers determine whether they should drop the index if there has been no reads on that index. If the index was created 'far' in the past with no reads, it's a definite signal to drop. If it was recently created, the developer _may_ want to hold off until they run their workload to see if the index will be used. This would complement crdb_internal.index_usage_statistics.

Epic: CRDB-9075

### PR DESCRIPTION
**Pull request by ajwerner**
This change plumbs a timestamp through to the index descriptor when it is
created. The timestamp used is based on the transaction start time. The
timestamp is then plumbed into the `crdb_internal.table_indexes` table and
exposed as a new NULL-able TIMESTAMP column, `created_at`.

Then, lastly, the timestamp is plumbed through to the status server via the
`TableIndexStatsRequest`.

Fixes #72626.

Release note (sql change): The database now records the approximate time when
an index was created it. This information is exposed via a new NULL-able
TIMESTAMP column, `created_at`, on `crdb_internal.table_indexes`.

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
Changes looking good, thanks for working on this! Just one clarification and the tests that need to be addressed

> Reviewed 37 of 38 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75753#-:-MupwJj99fQj43duR_ze:bvy3gnu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @maryliag)

___
*[pkg/sql/schemachanger/scpb/elements.proto, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75753#-MupudPrBRnzVwgyKv00:-MupudPrBRnzVwgyKv01:bv1gcxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/80018e961cd596d6d7739cd4bfbc114d48b13128/pkg/sql/schemachanger/scpb/elements.proto#L95)):*
> ```protobuf
>   bool unique = 3;
>   repeated uint32 key_column_ids = 4 [(gogoproto.customname) = "KeyColumnIDs", (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/sql/sem/catid.ColumnID"];
>   repeated Direction key_column_directions = 5;
> ```

we don't rename proto because they could still being used somewhere (frontend), so we create a new one and deprecate the old. If this value is still new and not yet added to any release and being used anywhere, then it's safe to make the change.
So I just want to confirm where/if this is being used on the frontend.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[pkg/sql/schemachanger/scpb/elements.proto, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75753#-MupudPrBRnzVwgyKv00:-MupwhYTB0GW9ZpsE2X7:bg3za83) ([raw file](https://github.com/cockroachdb/cockroach/blob/80018e961cd596d6d7739cd4bfbc114d48b13128/pkg/sql/schemachanger/scpb/elements.proto#L95)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

we don't rename proto because they could still being used somewhere (frontend), so we create a new one and deprecate the old. If this value is still new and not yet added to any release and being used anywhere, then it's safe to make the change.
So I just want to confirm where/if this is being used on the frontend.
</blockquote></details>

I solemnly swear you don't use this protobuf in the UI anywhere. We have both never shipped this proto, it's new in 22.1, and we don't expose it via any of our status/admin routes.

**Review by maryliag — APPROVED** [review]
You will need to rebase to deal with some conflicts, otherwise :lgtm: 

> Reviewed 1 of 38 files at r1, 32 of 32 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75753#-:-MvTpBvk9Uh5tYj5a5nF:br42nrh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by ajwerner** [comment]
@postamar any interest in a look?

**Review by chengxiong-ruan — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75753#-:-MvV0d8UDkedGWBBxLhr:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Pull request merged**
