### PR TITLE
cmd/roachtest: tweak kv{0,95} tests

### PR DESCRIPTION
**Pull request by petermattis**
Use 8 cpu machines which matches the machine specs used in previous kv
perf testing. Remount the disks with "nobarrier" for a similar reason.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[pkg/cmd/roachtest/kv.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25822#-LD8_8gQ67_LIPG9MDnG:-LD8_8gQ67_LIPG9MDnH:br3lc5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/320cbf96b7aa3bd85999b61bfa4ee2358c4aa0e1/pkg/cmd/roachtest/kv.go#L98)):*
> ```Go
> }
> 
> func registerKVScalability(r *registry) {
> ```

@nvanbenschoten I'll make this into a benchmark once your PR merges.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25822)*

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/cmd/roachtest/kv.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25822#-LD8l_CS7XKoiK6ucCkU:-LD8l_CS7XKoiK6ucCkV:b-vspavs) ([raw file](https://github.com/cockroachdb/cockroach/blob/320cbf96b7aa3bd85999b61bfa4ee2358c4aa0e1/pkg/cmd/roachtest/kv.go#L26)):*
> ```Go
> 	runKV := func(ctx context.Context, t *test, c *cluster, percent int) {
> 		if !c.isLocal() {
> 			// TODO(peter): remountNoBarrier when Nathan's PR merges.
> ```

You can merge this now and I'll take care of this.

---

*[pkg/cmd/roachtest/kv.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25822#-LD8lse1EPNmebaVX6Ay:-LD8lse1EPNmebaVX6Az:b-n5np7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/320cbf96b7aa3bd85999b61bfa4ee2358c4aa0e1/pkg/cmd/roachtest/kv.go#L59)):*
> ```Go
> 			r.Add(testSpec{
> 				Name:   fmt.Sprintf("kv%d/nodes=%d", p, n),
> 				Nodes:  nodes(n+1, cpu(8)),
> ```

I was meaning to ask before, does this assert that existing clusters provided with `--cluster` fit this machine type?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25822#-:-LD8m25T3yOcvBNsRc07:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/cmd/roachtest/kv.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25822#-LD8lse1EPNmebaVX6Ay:-LD8m9RQD-EwsHGTHUWr:b-bgpu3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/320cbf96b7aa3bd85999b61bfa4ee2358c4aa0e1/pkg/cmd/roachtest/kv.go#L59)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I was meaning to ask before, does this assert that existing clusters provided with `--cluster` fit this machine type?
</blockquote></details>

I don't think it currently does, so better question - should it?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25822)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/cmd/roachtest/kv.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25822#-LD8lse1EPNmebaVX6Ay:-LD8mMqqCu-DT12tufms:bqsfhst) ([raw file](https://github.com/cockroachdb/cockroach/blob/320cbf96b7aa3bd85999b61bfa4ee2358c4aa0e1/pkg/cmd/roachtest/kv.go#L59)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I don't think it currently does, so better question - should it?
</blockquote></details>

No, it currently doesn't make any verification of an existing cluster with the desired cluster. It probably should. I'll file an issue.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25822)*

**Comment by petermattis** [comment]
bors r=nvanbenschoten

**Comment by petermattis** [comment]
Failure is #25334.

bors r=nvanbenschoten

**Pull request merged**
