### PR TITLE
ui: show warning when data is not old enough

### LINKED ISSUE #108989: improve consistency on SQL Activity
Scenario: a fingerprint gets executed 1k times per day.
On `statement_activity`, we are able to keep the data for that fingerprint for 2 days.
On `statement_statistics` we had data for several days, but the limit of the table was reached, so older data had to be deleted and now only data for the past day is available.

If a user selects see past day: it will return the results from `statement_activity`, since the selected period existed there, and we will show 2k.
If a user selects past week: the `statement_activity` doesn't have this entire period, so it will return the results from `statement_statistics`, and that only had the last day, so it will return 1k.

So for the user, it shows past day 2k and past week 1k, which is confusing.
We need to improve this experience.

Possible solution:
- Delete the data based on TTL and have the same value for all tables
- Some union when the main table is selected
- Show warning/info message.

Jira issue: CRDB-30734

### PR DESCRIPTION
**Pull request by maryliag**
If a user selects a time period that we don't have the data for it (because it was already cleaned),
we show a warning to indicate the data might not be complete.

Fix #108989

Screenshot 2023-08-23 at 5 30 18 PM

https://www.loom.com/share/a7e0b0738d834bb0b6f38a9da43fb6a4

Release note (ui change): Show warning when time period selected on SQL Activity is older than the oldest data available.

### CODE REVIEW

**Comment by dongniwang** [comment]
How about "Data is available since MMM DD, HH:MM (UTC)"? Have we been using "data" as a generic term or "SQL Stats" is the right term here? Or "Latest data available since MMM DD, HH:MM (UTC)"?

I'm also thinking that we should inform users in the Search Criteria section of this information as well so they have it before making a selection. And disabling the dropdown selections that we don't have data for.

**Review by gtr — CHANGES_REQUESTED** [review]
> I'm also thinking that we should inform users in the Search Criteria section of this information as well so they have it before making a selection. And disabling the dropdown selections that we don't have data for.

I think disabling the dropdown would defeat the purpose of this warning, no? But I do agree that informing users in the search criteria about the data we have is a good idea. That way, it comes as less of a surprise when the warning does appear. 

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109164#-:-NcYpFh42Sw3hp5thPuh:b-d854gy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @florence-crl, @koorosh, and @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/aggregatedLabel.tsx` line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109164#-NcYnAZ_0nlZHt7KkWIm:-NcYnAZ_0nlZHt7KkWIn:bc6muxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/481735e8589bca34749a502124f51cb9b2fcfd54/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/aggregatedLabel.tsx#L33)):*
> ```XML
> }
> 
> export const TimeScaleLabel: React.FC<TimeScaleLabelProps> = ({
> ```

small nit: the file is called `aggregatedLabel.tsx` but the exported component here is `TimeScaleLabel`. I think naming it something like `AggregatedTimeScaleLabel` is better since it'll match the filename and it'll be used in the aggregated stats pages. I could also see it just being called `TimeScaleLabel` since it's also used in the txn details and stmt details pages, though. Either way, up to you but I think the filename should match the component name.

**Review by maryliag — COMMENTED** [review]
Updates to "SQL Stats available are available since". Image updated on PR description.

There is another issue to focus on the Search Criteria, so I will leave those changes to it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109164#-:-NcZIqos7N50gJodb8sw:bteuprg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @florence-crl, @gtr, and @koorosh)

___
*[`pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/aggregatedLabel.tsx` line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109164#-NcYnAZ_0nlZHt7KkWIm:-NcZJ9lL70vYPt7LgsJF:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/481735e8589bca34749a502124f51cb9b2fcfd54/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/aggregatedLabel.tsx#L33)):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

small nit: the file is called `aggregatedLabel.tsx` but the exported component here is `TimeScaleLabel`. I think naming it something like `AggregatedTimeScaleLabel` is better since it'll match the filename and it'll be used in the aggregated stats pages. I could also see it just being called `TimeScaleLabel` since it's also used in the txn details and stmt details pages, though. Either way, up to you but I think the filename should match the component name.
</blockquote></details>

Done

**Review by gtr — APPROVED** [review]
:lgtm: ! Probably just wait for Florence's and Dongni's approval for the copy.

> Reviewed 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109164#-:-NcZTb0p8RgWQnnm6n_f:b-7ev6p)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @florence-crl and @koorosh)

**Comment by maryliag** [comment]
Talked offline with Dogni and the copy was approved.
TFTRs

bors r+

**Pull request merged**
