### PR TITLE
opt: add rules to reorder joins to aid in filter pushdown

### PR DESCRIPTION
**Pull request by DrewKimball**
Previously, the filters of a query like the following couldn't be
pushed down:
```
norm
SELECT * FROM xy, ab, uv WHERE x=u AND y=a
----
inner-join (hash)
 ├── scan xy
 ├── inner-join (cross)
 │    ├── scan ab
 │    ├── scan uv
 │    └── filters (true)
 └── filters
      ├── x = u
      └── y = a
```
This patch adds four rules that produce variants on the following
tranformation of the above plan:
```
----
inner-join (hash)
 ├── inner-join (hash)
 │    ├── scan xy
 │    ├── scan ab
 │    └── filters
 │         └── y = a
 ├── scan uv
 └── filters
      └── x = u
```
Transforming a query in this way can lead to smaller row counts,
since filters are pushed closer to the relations they reference. It
can also aid in limit pushdown.

Release note (sql change): Enhance the optimizer's ability to
reorder joins.

### CODE REVIEW

**Comment by DrewKimball** [comment]
I ran the tpch queries whose plans changed (Q2, Q8, Q9, Q10) against master to see if the runtimes changed. I ran each query four times and took the average of the last three (since the first run often seems to be an outlier) measured to the nearest millisecond.

Query | Before 1 | Before 2 | Before 3 | After 1 | After 2 | After 3 | Before Mean | After Mean | Before StDev | After StdDev | Delta | Percent Change
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Q2 | 959ms | 942ms | 952ms | 940ms | 914ms | 905ms | 951ms | 919.67ms | 8.54ms | 18.18ms | -31.33ms | -3.29%
Q8 | 9063ms | 9197ms | 9129ms | 3067ms | 3136ms | 3026ms | 9129.67ms | 3076.33ms | 67.00ms | 55.59ms | -6053.33ms | -66.30%
Q9 | 78067ms | 82292ms | 77875ms | 58182ms | 58450ms | 57771ms | 79411.33ms | 58134.33ms | 2496.58ms | 342.00ms | -21277ms | -26.79%
Q10 | 4027ms | 4072ms | 4122ms | 3945ms | 3788ms | 3990ms | 4073.67ms | 3907.67ms | 47.52ms | 106.05ms | -166ms | -4.07%

**Comment by RaduBerinde** [comment]
Wow, those improvements are impressive!!

**Review by rytaft — COMMENTED** [review]
> Wow, those improvements are impressive!!
 
+1 !

> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49948#-:-M9KrQNKAiqReAFjSii0:b7709a0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[pkg/sql/opt/norm/rules/join.opt, line 547 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49948#-M9Kn-O3BgLzvIhTsISa:-M9Kn-O3BgLzvIhTsISb:buok24a) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22ee4b7c3e58230058c083c9f4513703ef9d9a0/pkg/sql/opt/norm/rules/join.opt#L547)):*
> ```
> # pushing cross joins up the operator tree. LeftAssociateJoinsLeft matches when
> # the following conditions are true:
> # 1. The lower InnerJoin is the left input of the upper InnerJoin.
> ```

[nit] I think "outer" and "inner" might be clearer than "upper" and "lower"
___
*[pkg/sql/opt/norm/rules/join.opt, line 551 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49948#-M9Ko0ue0BCxtznwpRM-:-M9Ko0ue0BCxtznwpRM0:bj4vq7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22ee4b7c3e58230058c083c9f4513703ef9d9a0/pkg/sql/opt/norm/rules/join.opt#L551)):*
> ```
> #    of the upper InnerJoin and the left input of the lower InnerJoin.
> # 3. The lower InnerJoin's ON condition does not reference the left input of the
> #    lower InnerJoin.
> ```

The rule seems stricter -- seems like the ON conditions must be empty
___
*[pkg/sql/opt/norm/rules/join.opt, line 563 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49948#-M9KnT8tCv51oUKhtXoQ:-M9KnT8tCv51oUKhtXoR:b-5p7ogq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22ee4b7c3e58230058c083c9f4513703ef9d9a0/pkg/sql/opt/norm/rules/join.opt#L563)):*
> ```
> #   ON b=u
> #
> # In this example, the neither of the filters in the original query could be
> ```

[nit] the neither -> neither
___
*[pkg/sql/opt/norm/rules/join.opt, line 571 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49948#-M9KoNAiAwbBBpLx1tut:-M9KoNAj6hIP10zCtl17:bsz61kz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22ee4b7c3e58230058c083c9f4513703ef9d9a0/pkg/sql/opt/norm/rules/join.opt#L571)):*
> ```
> # In the worst case scenario, LeftAssociateJoinsLeft and its variants will
> # be fired (n^2)/4 times, where n is the number of joins in the join tree.
> [LeftAssociateJoinsLeft, Normalize, LowPriority]
> ```

Can you add a comment on why you made this LowPriority?
___
*[pkg/sql/opt/norm/rules/join.opt, line 598 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49948#-M9KorMX0ssExaGKWr57:-M9KorMX0ssExaGKWr58:b5072zu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22ee4b7c3e58230058c083c9f4513703ef9d9a0/pkg/sql/opt/norm/rules/join.opt#L598)):*
> ```
>         $outerRight
>         (ExtractBoundConditions
>             $newOn:(ConcatFilters $outerOn $innerOn)
> ```

Since `$innerOn` is empty, I don't think you need to include it here (or bother binding the variable in the first place)
___
*[pkg/sql/opt/norm/rules/join.opt, line 614 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49948#-M9KpOXQ4-84ib9xb1B0:-M9KpOXQ4-84ib9xb1B1:b-uggvfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22ee4b7c3e58230058c083c9f4513703ef9d9a0/pkg/sql/opt/norm/rules/join.opt#L614)):*
> ```
> #   ON a=x AND b=u
> # =>
> #   SELECT * FROM uv
> ```

shouldn't this one be `xy`?

**Comment by awoods187** [comment]
nice job on the speed ups!

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49948)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/opt/norm/rules/join.opt, line 547 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49948#-M9Kn-O3BgLzvIhTsISa:-M9MbrTy7cgXjy61Wzrn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22ee4b7c3e58230058c083c9f4513703ef9d9a0/pkg/sql/opt/norm/rules/join.opt#L547)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] I think "outer" and "inner" might be clearer than "upper" and "lower"
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rules/join.opt, line 551 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49948#-M9Ko0ue0BCxtznwpRM-:-M9MbsGqALlO4n9W4lpS:b37y4vq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22ee4b7c3e58230058c083c9f4513703ef9d9a0/pkg/sql/opt/norm/rules/join.opt#L551)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

The rule seems stricter -- seems like the ON conditions must be empty
</blockquote></details>

Right, forgot to change that. Done.
___
*[pkg/sql/opt/norm/rules/join.opt, line 563 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49948#-M9KnT8tCv51oUKhtXoQ:-M9Mc3CTB2SQnGdCo8di:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22ee4b7c3e58230058c083c9f4513703ef9d9a0/pkg/sql/opt/norm/rules/join.opt#L563)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] the neither -> neither
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rules/join.opt, line 571 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49948#-M9KoNAiAwbBBpLx1tut:-M9McNgCBFOHVHBJPBcZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22ee4b7c3e58230058c083c9f4513703ef9d9a0/pkg/sql/opt/norm/rules/join.opt#L571)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Can you add a comment on why you made this LowPriority?
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rules/join.opt, line 598 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49948#-M9KorMX0ssExaGKWr57:-M9Mcic49wMTUb-HT3C3:beu4u9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22ee4b7c3e58230058c083c9f4513703ef9d9a0/pkg/sql/opt/norm/rules/join.opt#L598)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Since `$innerOn` is empty, I don't think you need to include it here (or bother binding the variable in the first place)
</blockquote></details>

Good point, Done.
___
*[pkg/sql/opt/norm/rules/join.opt, line 614 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49948#-M9KpOXQ4-84ib9xb1B0:-M9MdM96AvjM5CIkkPln:bzfkl7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22ee4b7c3e58230058c083c9f4513703ef9d9a0/pkg/sql/opt/norm/rules/join.opt#L614)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

shouldn't this one be `xy`?
</blockquote></details>

Indeed it should - nice catch. Done.

**Review by rytaft — APPROVED** [review]
:lgtm: 

You're getting some failing tests. For the logic tests, you should be able to run `make test PKG=./pkg/sql/logictest... TESTFLAGS='-rewrite=true' TESTS='TestLogic//tpch_vec'` to fix the failures. 

For the stats quality tests, I am running them for you and I'll send you the updates. Dealing with plan changes in the stats quality tests is a pain in the butt, so there's not a great need for you to learn how to do that unless you think you'll be making a lot more changes to TPC-H plans. (We haven't fully automated all the steps needed to update the stats quality tests, so there is currently some manual work. Let me know if you'd like me to show you how it works.)

> Reviewed 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49948#-:-M9KsTSrAjdPILuGEESb:b-jfjc5q)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by rytaft** [comment]
Here's a gist with the TPC-H stats quality updates: https://gist.github.com/rytaft/2e1b915c17c06c766b3ec626c3c3ef4b

**Review by RaduBerinde — APPROVED** [review]
:lgtm: This is great!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49948#-:-M9ZbO_bEYGiLvNsjFkx:b48xzcn)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @rytaft)

___
*[pkg/sql/opt/norm/rules/join.opt, line 547 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49948#-M9ZaFdtDm-zkg4eEMN9:-M9ZaFdu04onBF8obz1A:b-4y5w6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/e07a9e13c1f7e777fb770af9a6a4d75d408423f2/pkg/sql/opt/norm/rules/join.opt#L547)):*
> ```
> # pushing cross joins up the operator tree. LeftAssociateJoinsLeft matches when
> # the following conditions are true:
> # 1. The inner InnerJoin is the left input of the outer InnerJoin.
> ```

[nit] I'd use "join" instead of "InnerJoin" here, this is a tongue twister. Also consider using "lower/higher" or "outside/inside" instead of "outer/inner"

**Review by rytaft — APPROVED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49948)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49948)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

___
*[pkg/sql/opt/norm/rules/join.opt, line 547 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49948#-M9ZaFdtDm-zkg4eEMN9:-M9_Neio633MxPOi9S_S:bps2ayj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e07a9e13c1f7e777fb770af9a6a4d75d408423f2/pkg/sql/opt/norm/rules/join.opt#L547)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I'd use "join" instead of "InnerJoin" here, this is a tongue twister. Also consider using "lower/higher" or "outside/inside" instead of "outer/inner"
</blockquote></details>

Heh, I've gotten as many different recommendations on that naming as I've had reviewers. I'll go with outside/inside for consistency with #49992.

**Comment by yuzefovich** [comment]
Nice speedups!

**Pull request merged**
