### PR TITLE
server: add mvcc stats to range debug page

### LINKED ISSUE #15722: storage: range debug page should provide access to MVCCStats
The subject says it all. While trying to debug something today, I wanted to see the value of `MVCCStats.Total()` to see if a range should be split.

### PR DESCRIPTION
**Pull request by BramGruneir**
Fixes #15722.

See the MVCC sections near the end of the range stats.
screen shot 2017-05-08 at 16 14 53

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/server/debug_range.go, line 65 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15785#-KjeoLDXbpU3_XHoSsZ5:-KjeoLDXbpU3_XHoSsZ6:b-thiwdc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c28e5c227a3ab1810c14da301819a2fbcbab86a/pkg/server/debug_range.go#L65)):*
> ```Go
> 	debugRangeHeaderMVCCVal           = "MVCC Value Bytes/Count"
> 	debugRangeHeaderMVCCIntent        = "MVCC Intent Bytes/Count"
> 	debugRangeHeaderMVCCSys           = "MVCC System Bytes/Count"
> ```

Some much repetition of `MVCC` here. I don't have a concrete suggestion. Perhaps we could drop `MVCC`, but that might be confusing. 

---

*[pkg/server/debug_range.go, line 595 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15785#-KjeogPOYnMwia79lXGe:-KjeogPOYnMwia79lXGf:b-z3pl9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c28e5c227a3ab1810c14da301819a2fbcbab86a/pkg/server/debug_range.go#L595)):*
> ```Go
> 				info.State.ReplicaState.Stats.SysBytes,
> 				info.State.ReplicaState.Stats.SysCount,
> 			),
> ```

Lot of repetition above. I wouldn't go crazy trying to get rid of it, but a closure or two could help:

```
fmtBytesCount := func(bytes, count int) string {
  return fmt.Sprintf("%d bytes / %d", bytes, count)
}
...
  stats := info.State.ReplicaState.Stats
...
  Title: fmtBytesCount(stats.SysBytes, stats.SysCount)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15785#-:-KjepGXzj7_vnaSlHBo8:bnfp4nl)*

**Comment by BramGruneir** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/server/debug_range.go, line 65 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15785#-KjeoLDXbpU3_XHoSsZ5:-KjfFBjq1UqToWsayxYU:b-24c036) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c28e5c227a3ab1810c14da301819a2fbcbab86a/pkg/server/debug_range.go#L65)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Some much repetition of `MVCC` here. I don't have a concrete suggestion. Perhaps we could drop `MVCC`, but that might be confusing. 
</blockquote></details>

I was thinking of adding some type of sub title, just not sure of how it would look.

---

*[pkg/server/debug_range.go, line 595 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15785#-KjeogPOYnMwia79lXGe:-KjfFMYYJtZpnWNz4DxI:b39jy4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c28e5c227a3ab1810c14da301819a2fbcbab86a/pkg/server/debug_range.go#L595)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Lot of repetition above. I wouldn't go crazy trying to get rid of it, but a closure or two could help:

```
fmtBytesCount := func(bytes, count int) string {
  return fmt.Sprintf("%d bytes / %d", bytes, count)
}
...
  stats := info.State.ReplicaState.Stats
...
  Title: fmtBytesCount(stats.SysBytes, stats.SysCount)
```
</blockquote></details>

Done, cleaned it up a bit.  But there's a ton of repetition throughout this file.  I'm going to try to clean some of it up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15785)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/server/debug_range.go, line 595 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15785#-KjeogPOYnMwia79lXGe:-KjhQ83ucDUaJ01yqtfJ:bu3is99) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c28e5c227a3ab1810c14da301819a2fbcbab86a/pkg/server/debug_range.go#L595)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Done, cleaned it up a bit.  But there's a ton of repetition throughout this file.  I'm going to try to clean some of it up.
</blockquote></details>

Some of the lines above are now longer than 100 columns. I thought `crlfmt` would complain about that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15785)*

**Comment by BramGruneir** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/server/debug_range.go, line 595 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15785#-KjeogPOYnMwia79lXGe:-Kjh_8saXVMqskx37xdE:b75ott6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c28e5c227a3ab1810c14da301819a2fbcbab86a/pkg/server/debug_range.go#L595)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Some of the lines above are now longer than 100 columns. I thought `crlfmt` would complain about that.
</blockquote></details>

AFAIK, we don't actually enforce the hard limit.  I think it looks a little better as single lines, but I've cut down all overtly offending lines.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15785)*

**Pull request merged**
