### PR TITLE
roachtest: add --debug flag that preserves cluster on failure

### PR DESCRIPTION
**Pull request by benesch**
Release note: None

### CODE REVIEW

**Comment by tschottdorf** [comment]
Should this flag default to `true`? I realize that there's a chance this will leak resources if we set things up incorrectly. However I assume we're going to set it to true in our nightlies anyway? And for local testing, you usually want to check what went wrong too.

**Comment by benesch** [comment]
I wasn’t planning to flip the bit until things got a bit more reliable. We’re still failing every night on TC. You mind if I merge as-is for now?

**Comment by tschottdorf** [comment]
Not at all! Was just drive-by'ing.

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24371#-:-L8tLk2_-ORaY435dFyY:bnfp4nl)*

**Pull request merged**
