### PR TITLE
indexrec: improve recommendations for queries with inequalities

### LINKED ISSUE #102206: opt: include != and IS DISTINCT FROM and IS NOT NULL columns in index recommendations
Index recommendations currently do not consider hypothetical indexes on columns used with the following operators:
- `!=`
- `IS DISTINCT FROM`
- `IS NOT NULL`

I think columns used with these operators could go into the R (range) set of columns during hypothetical index creation, as we still generate constrained index scans for them when an index exists.

Jira issue: CRDB-27339

### PR DESCRIPTION
**Pull request by qiyanghe1998**
Fixes #102206

As for the tests, since !=, IS DISTINT FROM and IS NOT are categorized as range
index, so I copied similar tests with "R": R, EQ + R, J + R, EQ + J + R.

Release note: None

Epic: None

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
Very nice! :lgtm: Just left some optional nits.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104208#-:-NWrW1eYDc_ZBVU2v50W:b-ujjz14)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @qiyanghe1998)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104208#-NWrUZNj8_SBWucL6fRL):*
nit: It's hard to make titles fit in ~72 characters — I don't always manage it — but you can try to make them less specific and put the details in the commit message body. For example, "indexrec: improve recommendations for queries with inequalities" is an option.
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104208#-NWrVX1r1jMLzf6kGz14):*
nit: "changed" makes it sound like you altered existing tests. maybe `so I copied similar tests with "R": ...`

**Comment by qiyanghe1998** [comment]
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104208#-NWrVX1r1jMLzf6kGz14):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: "changed" makes it sound like you altered existing tests. maybe `so I copied similar tests with "R": ...`
</blockquote></details>

fixed

**Comment by qiyanghe1998** [comment]
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104208#-NWrUZNj8_SBWucL6fRL):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: It's hard to make titles fit in ~72 characters — I don't always manage it — but you can try to make them less specific and put the details in the commit message body. For example, "indexrec: improve recommendations for queries with inequalities" is an option.
</blockquote></details>

Thanks. Great advice, fixed.

**Review by mgartner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104208)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach)

**Pull request merged**
