### PR TITLE
base: add envvars for Raft/lease settings

### PR DESCRIPTION
**Pull request by erikgrinaker**
These settings are needed to properly adjust the lease duration with various tradeoffs. The defaults are very conservative, to handle high-latency clusters, and users on low-latency cluster may want to reduce them to improve availability when losing leaseholders.

Epic: none

Release note (ops change): The following environment variables have been added, but should be changed with caution since misconfiguration will result in an inoperable cluster:
* `COCKROACH_RAFT_TICK_INTERVAL`: the Raft tick interval (default 200ms).
* `COCKROACH_RAFT_HEARTBEAT_INTERVAL_TICKS`: the interval between Raft heartbeats in ticks (default 5).
* `COCKROACH_RANGE_LEASE_RAFT_ELECTION_TIMEOUT_MULTIPLIER`: the range lease duration as a multiple of the Raft election timeout (default 3.0).
* `COCKROACH_RANGE_LEASE_RENEWAL_FRACTION`: the fraction before the end of the lease where expiration-based leases should be renewed (default 0.5).
* `COCKROACH_LIVENESS_RENEWAL_FRACTION`: the fraction before the end of the lease where epoch-based leases should be renewed via a node liveness heartbeat (default 0.5).

### CODE REVIEW

**Review by tbg — APPROVED** [review]
Could you add the reason for adding these to the commit message? You may also want to point out in the commit message that these should not freely be set by users since misconfiguration can cause severe issues.

**Comment by erikgrinaker** [comment]
Sure, done.

**Comment by erikgrinaker** [comment]
Internal context, FWIW: https://cockroachlabs.slack.com/archives/C013M2PD35H/p1672786701309859

**Comment by tbg** [comment]
Still good just in case you forgot about this.

**Comment by erikgrinaker** [comment]
There's been some discussion about simplifying the config here in #94704, so I'll keep this around until we figure out what to do.

**Comment by erikgrinaker** [comment]
Superseded by #98584 and #98559.

**Pull request closed without merging**
