### PR TITLE
importccl,backupccl,eventspb: eventlog entries for IMPORT and RESTORE

### PR DESCRIPTION
**Pull request by dt**
Screen Shot 2021-02-01 at 1 30 51 PM

Release note (sql change): IMPORT and RESTORE now log events to the event log.

### CODE REVIEW

**Review by miretskiy — APPROVED** [review]
> Reviewed 7 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59661)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @knz)

___
*[pkg/ccl/importccl/import_stmt.go, line 1510 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59661#-MSTz8ayE9psiJ6oW-kM:-MSTz8az1iGl4KlAmWRA:b7ozpdv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a34fc8d166d87d14e9fa292f493b92c241fd7c13/pkg/ccl/importccl/import_stmt.go#L1510)):*
> ```Go
> 	}); err != nil {
> 		log.Warningf(ctx, "failed to log event: %v", err)
> 	}
> ```

pretty verbose stuff... Do you think this could be moved to shared function?

**Review by dhartunian — APPROVED** [review]
:lgtm: from a DB Console perspective.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59661#-:-MSU-0Tz7u4tu_43fqs7:ben5uaf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @knz)

___
*[pkg/ui/src/util/events.ts, line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59661#-MSU-K1P9WFPA9thjB5b:-MSU-K1P9WFPA9thjB5c:b-ga5zds) ([raw file](https://github.com/cockroachdb/cockroach/blob/a34fc8d166d87d14e9fa292f493b92c241fd7c13/pkg/ui/src/util/events.ts#L140)):*
> ```XML
>       return `Role Altered: User ${info.User} altered role ${info.RoleName} with options ${info.Options}`;
>     case eventTypes.IMPORT:
>       return `Data/Schema Imported: User ${info.User} ran ${info.Statement}`;
> ```

Do we need the "data/schema " prefix here? Can we just say "Import: " and "Restore: "?

**Review by knz — COMMENTED** [review]
> Reviewed 7 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59661)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/ccl/backupccl/restore_job.go, line 1291 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59661#-MSU06Um17iIiZIm07rq:-MSU06Um17iIiZIm07rr:bvuqb8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/a34fc8d166d87d14e9fa292f493b92c241fd7c13/pkg/ccl/backupccl/restore_job.go#L1291)):*
> ```Go
> 
> 	if err := p.ExecCfg().DB.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
> 		ev := &eventpb.Restore{
> ```

That seems ... incomplete.

This really needs to call into `log.logEventInternalForSQLStatements()` (probably needs to be exported)

in any case the needs also to include:

- the application_name
- the statement placeholders 

In general, the code in `backupccl` should not be responsible for filling in the user & timestamp. Whatever code you need to do this needs to live in `sql/event_log`, so that the next engineer who needs to add a new field common to all events has just 1 place to look at.
___
*[pkg/ccl/importccl/import_stmt.go, line 1496 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59661#-MSU0b-z0_5kGGZlLoSC:-MSU0b0-7lAlcGwRn98R:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/a34fc8d166d87d14e9fa292f493b92c241fd7c13/pkg/ccl/importccl/import_stmt.go#L1496)):*
> ```Go
> 
> 	ev := &eventpb.Import{
> 		CommonEventDetails: eventpb.CommonEventDetails{
> ```

ditto
___
*[pkg/util/log/eventpb/ddl_events.proto, line 432 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59661#-MSU0fJS4Gei3dRY9ha3:-MSU0fJS4Gei3dRY9ha4:bn5kkuq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a34fc8d166d87d14e9fa292f493b92c241fd7c13/pkg/util/log/eventpb/ddl_events.proto#L432)):*
> ```protobuf
> 
> 
> message Import {
> ```

You need a docstring above `message` here and below.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59661)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian, @dt, and @knz)

___
*[pkg/ccl/backupccl/restore_job.go, line 1291 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59661#-MSU06Um17iIiZIm07rq:-MSU3rYS3YAGMEsL4n6w:b6eykhx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a34fc8d166d87d14e9fa292f493b92c241fd7c13/pkg/ccl/backupccl/restore_job.go#L1291)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

That seems ... incomplete.

This really needs to call into `log.logEventInternalForSQLStatements()` (probably needs to be exported)

in any case the needs also to include:

- the application_name
- the statement placeholders 

In general, the code in `backupccl` should not be responsible for filling in the user & timestamp. Whatever code you need to do this needs to live in `sql/event_log`, so that the next engineer who needs to add a new field common to all events has just 1 place to look at.
</blockquote></details>

Ah, I'd assumed by the un-exported and "Internal" that that wasn't intended for use outside `sql`. 

Application name and placeholders are a little interesting: we're in a job execution here, not in statement execution, so there are no placeholders -- if the job was planed by a statement and that statement had placeholders, they were long ago evaluated to determine the actual the actual job definition. 

Similarly, if the job was planned by a statement, that statement's session might have had an application name, but we're no longer in statement eval. 
___
*[pkg/ui/src/util/events.ts, line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59661#-MSU-K1P9WFPA9thjB5b:-MSU6faQCPgFsQ0OhE-r:bud636k) ([raw file](https://github.com/cockroachdb/cockroach/blob/a34fc8d166d87d14e9fa292f493b92c241fd7c13/pkg/ui/src/util/events.ts#L140)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Do we need the "data/schema " prefix here? Can we just say "Import: " and "Restore: "?
</blockquote></details>

It seemed like all the others were sentence-ified?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59661)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @dt)

___
*[pkg/ccl/backupccl/restore_job.go, line 1291 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59661#-MSU06Um17iIiZIm07rq:-MSU7l-e7sZGDPYep1m5:boqq2kw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a34fc8d166d87d14e9fa292f493b92c241fd7c13/pkg/ccl/backupccl/restore_job.go#L1291)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Ah, I'd assumed by the un-exported and "Internal" that that wasn't intended for use outside `sql`. 

Application name and placeholders are a little interesting: we're in a job execution here, not in statement execution, so there are no placeholders -- if the job was planed by a statement and that statement had placeholders, they were long ago evaluated to determine the actual the actual job definition. 

Similarly, if the job was planned by a statement, that statement's session might have had an application name, but we're no longer in statement eval. 


</blockquote></details>

1. the app name should be added to the job payload. That is generally a shrotcoming of the job definitions today and that would be good to fix regardless of this PR

2. regarding placeholders: I agree with your point, *however* the semantics of the event definition are clear: the `Statement` field in the event must report the statement that was used to issue the backup.  But what's in the `Description` field then? Is that not a copy of the statement? If it is, and the original statement contained placeholders, what remains in `Description`? 

I suspect that the statement *without* placeholders was copied to `Description` during planning. And now this teaches us that this design was incomplete: like the app name is still missing, probably the job payload should contain discrete/separate fields to memorize the statement *and the placeholder values* for the purpose of logging the event when the job eventually gets executed.


You could come back to me with the idea that  bulk i/o jobs really are not associated with SQL statements. Maybe that's a valid stance. But if that is what you want, then it's not legitimate to reuse the `CommonSQLEventDetails` in the two new payload types you've introduced.
___
*[pkg/util/log/eventpb/ddl_events.proto, line 432 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59661#-MSU0fJS4Gei3dRY9ha3:-MSU8kB2Ap_Q8MeYdmal:b-6ttvp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a34fc8d166d87d14e9fa292f493b92c241fd7c13/pkg/util/log/eventpb/ddl_events.proto#L432)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You need a docstring above `message` here and below.
</blockquote></details>

Also, arguably IMPORT / RESTORE are not DDL events. Are you sure they should be categorized under the SQL_SCHEMA logging channel?
It does not feel like it fits the definition of the SQL_SCHEMA channel, at least not the one our customers were asking for.

Based on the channel definitions, they may belong to the OPS channel instead.

(You can group new events under a different channel by adding a new category header (as a comment) in-between the groups. You can look at `sql_audit_events.proto` for an example that has multiple groups already.)

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59661)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian, @dt, and @knz)

___
*[pkg/ccl/backupccl/restore_job.go, line 1291 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59661#-MSU06Um17iIiZIm07rq:-MSU7XzZ0dlSWP60OQLq:b-km4idn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a34fc8d166d87d14e9fa292f493b92c241fd7c13/pkg/ccl/backupccl/restore_job.go#L1291)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

1. the app name should be added to the job payload. That is generally a shrotcoming of the job definitions today and that would be good to fix regardless of this PR

2. regarding placeholders: I agree with your point, *however* the semantics of the event definition are clear: the `Statement` field in the event must report the statement that was used to issue the backup.  But what's in the `Description` field then? Is that not a copy of the statement? If it is, and the original statement contained placeholders, what remains in `Description`? 

I suspect that the statement *without* placeholders was copied to `Description` during planning. And now this teaches us that this design was incomplete: like the app name is still missing, probably the job payload should contain discrete/separate fields to memorize the statement *and the placeholder values* for the purpose of logging the event when the job eventually gets executed.


You could come back to me with the idea that  bulk i/o jobs really are not associated with SQL statements. Maybe that's a valid stance. But if that is what you want, then it's not legitimate to reuse the `CommonSQLEventDetails` in the two new payload types you've introduced.
</blockquote></details>

`Description` is a string attribute of all jobs, provided by the code that created the job, to act as a human readable description of what that job is doing. 

For RESTORE and IMPORT, it is populated with _approximately_ a statement that, if run would produce an equivalent job, but it is not the original statement. We construct a new AST and fill in its fields, intentionally removing or altering some elements, such as redacting secret key fields in URIs or passphrases, using the actual values the job uses (i.e that were already derived from evaluating placeholders if needed).

I'm not sure I follow that jobs should have preserved original statement and placeholder values. Those were relevant to the code that determined what job to create, but are not really relevant to the execution of the job -- the job is `Restore{URI: 'http://abc'}`and doesn't care if it was planned using `RESTORE FROM $1` + "http://abc" vs `RESTORE FROM 'http://abc'` or potentially not by a statement at all (currently we have individual jobs that are created outside a statement execution but so far they can be traced back to a statement somewhere, but this is not assumed by jobs).

So perhaps you're right: jobs aren't statements and I shouldn't be using `CommonSQLEventDetails`.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59661)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @dt)

___
*[pkg/ccl/backupccl/restore_job.go, line 1291 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59661#-MSU06Um17iIiZIm07rq:-MSbU3xU60dLA0aVBdHR:b-ljmkiz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a34fc8d166d87d14e9fa292f493b92c241fd7c13/pkg/ccl/backupccl/restore_job.go#L1291)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

`Description` is a string attribute of all jobs, provided by the code that created the job, to act as a human readable description of what that job is doing. 

For RESTORE and IMPORT, it is populated with _approximately_ a statement that, if run would produce an equivalent job, but it is not the original statement. We construct a new AST and fill in its fields, intentionally removing or altering some elements, such as redacting secret key fields in URIs or passphrases, using the actual values the job uses (i.e that were already derived from evaluating placeholders if needed).

I'm not sure I follow that jobs should have preserved original statement and placeholder values. Those were relevant to the code that determined what job to create, but are not really relevant to the execution of the job -- the job is `Restore{URI: 'http://abc'}`and doesn't care if it was planned using `RESTORE FROM $1` + "http://abc" vs `RESTORE FROM 'http://abc'` or potentially not by a statement at all (currently we have individual jobs that are created outside a statement execution but so far they can be traced back to a statement somewhere, but this is not assumed by jobs).

So perhaps you're right: jobs aren't statements and I shouldn't be using `CommonSQLEventDetails`. 
</blockquote></details>

I think what we need here is a `CommonJobEventDetails` with the job payload details as fields; the docstrings on its fields would explain what is going on and what the user can expect wrt to SQL statements embedded in the 'description' field.

**Comment by knz** [comment]
yes that sounds reasonable, cool thanks

**Comment by knz** [comment]
ok so after discussion:

- `CommonJobEventDetails` is useful as a shared field between multiple event types. It's not good to include the finished timestamps in the common detail payload however, because ...
- ... we also want event payloads when jobs are initially created. At that time, there is no finish time yet.

Also the timestamps, if/when included should probably follow the model of other events which either use seconds or nanos.

**Comment by adityamaru** [comment]
Closing in favour of #62658.

**Pull request closed without merging**
