### PR TITLE
multitenant: track and report read/write request usage

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### multitenant: make the tenant consumption struct more usable

This commit renames the `TokenBucketRequest_Consumption` message to
`TenantConsumption` and adds some utility functions to add and
subtract the values.

The `SQLPodCPUSeconds` field is renamed to `SQLPodsCPUSeconds` which
is more accurate and consistent with the rest of the code.

Release note: None

#### tenantrate: move logic to map batches to cost to tenantcostmodel

This commit moves to `tenantcostmodel` the logic to extract the
components of `BatchRequest` and `BatchResponse` which factor into
RUs. From here the logic can be shared on both the tenant side and the
host cluster side.

Release note: None

#### multitenant: track and report read/write request usage

This change adds logic in the tenant-side cost controller to intercept
batch requests and responses and track their resource usage. The
interception happens inside the DistSender.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68343)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andy-kimball, and @stevendanna)

___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 721 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68343#-Mg7KCv52W-HNhv8xKSm:-Mg7KCv52W-HNhv8xKSn:b-gfcwwg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1366395c6936a11ba1b91dac76bf8bf3249e745b/pkg/kv/kvclient/kvcoord/dist_sender.go#L721)):*
> ```Go
> 
> 	if ds.batchInterceptor != nil {
> 		if err := ds.batchInterceptor.OnRequestWait(ctx, &ba); err != nil {
> ```

I wondered if the right interface would be to pass in `tenantcostmodel.RequestInfo` instead of `BatchRequest` - perhaps that would express better what the interceptor cares about (and we wouldn't need the MockBatchRequest stuff).

I think `ba` would not escape to the heap here if we did that.

**Review by andy-kimball — APPROVED** [review]
:lgtm:, with a couple comments + suggestion to change BatchInterceptor.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68343#-:-Mg7XBry2srajY7KWKrd:b-qhxib3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @RaduBerinde, and @stevendanna)

___
*[pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go, line 134 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68343#-Mg7Q4KICzzWeMr8rG9v:-Mg7Q4KICzzWeMr8rG9w:bi597yc) ([raw file](https://github.com/cockroachdb/cockroach/blob/34dd15207285362e90b475613a2c73a58e6d85b6/pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go#L134)):*
> ```Go
> 	}
> 	c.mu.consumption.RU += float64(c.mu.costCfg.RequestCost(info))
> 	c.mu.Unlock()
> ```

Why not `defer c.mu.Unlock()` just after the `Lock` call above?
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 721 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68343#-Mg7KCv52W-HNhv8xKSm:-Mg7TuR0-SmEXYV9kjl6:b-4fe0fh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1366395c6936a11ba1b91dac76bf8bf3249e745b/pkg/kv/kvclient/kvcoord/dist_sender.go#L721)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I wondered if the right interface would be to pass in `tenantcostmodel.RequestInfo` instead of `BatchRequest` - perhaps that would express better what the interceptor cares about (and we wouldn't need the MockBatchRequest stuff).

I think `ba` would not escape to the heap here if we did that.
</blockquote></details>

Given that the interceptor is all about tenants, I'd make it as specific as it can be. I'd call it `TenantSideTrafficInterceptor` (or maybe just `TenantSideInterceptor`) and have it directly take `RequestInfo` and `ResponseInfo`.
___
*[pkg/roachpb/api.go, line 1562 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68343#-Mg7OsNq382u7BS4mZ0V:-Mg7OsNr7ICnBYJ61P-H:b-1puojf) ([raw file](https://github.com/cockroachdb/cockroach/blob/34dd15207285362e90b475613a2c73a58e6d85b6/pkg/roachpb/api.go#L1562)):*
> ```Go
> 
> // Sub subtracts consumption, making sure no fields become negative.
> func (c *TenantConsumption) Sub(other *TenantConsumption) {
> ```

Worth having a unit test for this (in particular to test the underflow cases)?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68343)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andy-kimball, and @stevendanna)

___
*[pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go, line 134 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68343#-Mg7Q4KICzzWeMr8rG9v:-Mg84YN_3o_yWUJES0KW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/34dd15207285362e90b475613a2c73a58e6d85b6/pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go#L134)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Why not `defer c.mu.Unlock()` just after the `Lock` call above?
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 721 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68343#-Mg7KCv52W-HNhv8xKSm:-Mg8eZFf9dqptf9cvK-o:b2z6lcw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1366395c6936a11ba1b91dac76bf8bf3249e745b/pkg/kv/kvclient/kvcoord/dist_sender.go#L721)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Given that the interceptor is all about tenants, I'd make it as specific as it can be. I'd call it `TenantSideTrafficInterceptor` (or maybe just `TenantSideInterceptor`) and have it directly take `RequestInfo` and `ResponseInfo`.
</blockquote></details>

Done. Went with `TenantSideKVInterceptor`
___
*[pkg/roachpb/api.go, line 1562 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68343#-Mg7OsNq382u7BS4mZ0V:-Mg80_ZUCTY__MkpIMpi:bpdiyrf) ([raw file](https://github.com/cockroachdb/cockroach/blob/34dd15207285362e90b475613a2c73a58e6d85b6/pkg/roachpb/api.go#L1562)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Worth having a unit test for this (in particular to test the underflow cases)?
</blockquote></details>

Done, thanks, I should have added some. It was broken actually, I forgot some of the fields were unsigned ints.

**Comment by RaduBerinde** [comment]
Merging this to open the next PR. @ajwerner if you have any comments, I'm happy to address them in a follow-up PR.

bors r+

**Pull request merged**
