### PR TITLE
sql/sem/tree: add type-specific allocation sizes for DatumAlloc

### PR DESCRIPTION
**Pull request by mgartner**
#### sql/colexec: add more cases to BenchmarkMaterializer

Release note: None

#### sql/sem/tree: refactor DatumAlloc

This commit renames the `AllocSize` field of the `DatumAlloc` struct to
`DefaultAllocSize` in preparation of a future commit that will introduce
allocation sizes for individual datum types.

Release note: None

#### sql/sem/tree: add type-specific allocation sizes for DatumAlloc

`DatumAlloc` now allows for users to provide type-specific allocation
sizes. This is useful when the number of allocations of specific types
can be known before bulk allocating datums with `DatumAlloc`.

Type-specific allocation sizes are currently only used by
`VecToDatumConverter`. This can significantly reduce the number of
allocations made by `Materializer` when operating on a small batch of
wide rows that has many duplicate column types. For example, consider a
single-row batch with 100 string columns. Prior to this change, the
allocation size would be set to 1 (because the batch size is 1) and
`DatumAlloc` would allocate 100 individual string slices. After this
change, `DatumAlloc` allocates a single string slice with a length of
100.

Epic: None

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
Benchmark reults for `BenchmarkMaterializer`: https://gist.github.com/mgartner/d68193ecc33d4f5329a0ffa4e3f4825d

Let me know if there are other interesting benchmarks I should run.

**Comment by mgartner** [comment]
Some more context:

In a real-world workload with queries with many lookup-joins, I noticed quite a bit of overhead for the materializers and columnarizers to convert datums to vecs and vice versa. About 10% of allocations were due to `DatumAlloc` allocations due to the rows being very wide and the batch sizes being very small.

**Review by yuzefovich — APPROVED** [review]
Nice! I don't think more benchmarks are needed :lgtm:

> Reviewed 1 of 1 files at r1, 10 of 10 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126035#-:-O-xCgqj9SOwWaAH1j7T:bg5yvee)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/colconv/vec_to_datum_tmpl.go` line 188 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126035#-O-xBSyw1p3e5plLr2WW:-O-xBSyw1p3e5plLr2WX:b-k3wvdd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1314f78322fa4e46d70dbb652b8d657df8b0d100/pkg/sql/colconv/vec_to_datum_tmpl.go#L188)):*
> ```Go
> 	// Provide the datum allocator with hints about the number of allocations
> 	// for each type.
> 	c.da.ResetTypeAllocSizes()
> ```

nit: should we move this block to be right after modifying `c.da.DefaultAllocSize` here and below?
___
*[`pkg/sql/colexec/materializer_test.go` line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126035#-O-wrjgX2SSfRQz7kOMw:-O-wrjgX2SSfRQz7kOMx:bk0wts6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d22967bc8be8167b8263ac9880fc0cc82efffcc/pkg/sql/colexec/materializer_test.go#L116)):*
> ```Go
> 		{"int", []*types.T{types.Int}},
> 		{"float", []*types.T{types.Float}},
> 		{"bytea", []*types.T{types.Bytes}},
> ```

nit: probably `s/bytea/bytes/` (this would match some cases before this patch too for cross-release comparison).

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126035)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[`pkg/sql/colconv/vec_to_datum_tmpl.go` line 188 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126035#-O-xBSyw1p3e5plLr2WW:-O09nr9mApBsvg0JBKay:bi2e3pa) ([raw file](https://github.com/cockroachdb/cockroach/blob/1314f78322fa4e46d70dbb652b8d657df8b0d100/pkg/sql/colconv/vec_to_datum_tmpl.go#L188)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: should we move this block to be right after modifying `c.da.DefaultAllocSize` here and below?
</blockquote></details>

Looks to me like it is already right after, just the `sel` and `vecs` delarations between? `vecs` is referenced in the new block. Do you mean moving the `sel` declaration to after this block?
___
*[`pkg/sql/colexec/materializer_test.go` line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126035#-O-wrjgX2SSfRQz7kOMw:-O09pM303EY9M5fL_GNK:boj1qgt) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d22967bc8be8167b8263ac9880fc0cc82efffcc/pkg/sql/colexec/materializer_test.go#L116)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: probably `s/bytea/bytes/` (this would match some cases before this patch too for cross-release comparison).
</blockquote></details>

Good catch. Done.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 11 of 11 files at r4, 10 of 10 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126035)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[`pkg/sql/colconv/vec_to_datum_tmpl.go` line 188 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126035#-O-xBSyw1p3e5plLr2WW:-O09w4C_A6H5omS5pcQL:bw89bcn) ([raw file](https://github.com/cockroachdb/cockroach/blob/1314f78322fa4e46d70dbb652b8d657df8b0d100/pkg/sql/colconv/vec_to_datum_tmpl.go#L188)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Looks to me like it is already right after, just the `sel` and `vecs` delarations between? `vecs` is referenced in the new block. Do you mean moving the `sel` declaration to after this block?
</blockquote></details>

Yeah, I just meant to move it above `sel` definition, for better visual grouping.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126035)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[`pkg/sql/colconv/vec_to_datum_tmpl.go` line 188 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126035#-O-xBSyw1p3e5plLr2WW:-O0Ao0z29YvrgQ1J0sJq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1314f78322fa4e46d70dbb652b8d657df8b0d100/pkg/sql/colconv/vec_to_datum_tmpl.go#L188)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Yeah, I just meant to move it above `sel` definition, for better visual grouping.
</blockquote></details>

Done.

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
