### PR TITLE
sql: split tuple inequalities when splitting filters

### LINKED ISSUE #20472: sql: break up tuple comparisons in splitFilter
```
CREATE TABLE t1 (a INT, b INT, c INT);
CREATE TABLE t2 (a INT, b INT, d INT);
EXPLAIN (VERBOSE) SELECT * FROM t1 NATURAL JOIN t2 WHERE (a, b, c) > (1, 2, 3)
----
Level  Type    Field     Description            Columns                                                                             Ordering
0      render  ·         ·                      (a, b, c, d)                                                                        ·
0      ·       render 0  test.t1.a              ·                                                                                   ·
0      ·       render 1  test.t1.b              ·                                                                                   ·
0      ·       render 2  test.t1.c              ·                                                                                   ·
0      ·       render 3  test.t2.d              ·                                                                                   ·
1      join    ·         ·                      (a, b, c, rowid[hidden,omitted], a[omitted], b[omitted], d, rowid[hidden,omitted])  ·
1      ·       type      inner                  ·                                                                                   ·
1      ·       equality  (a, b) = (a, b)        ·                                                                                   ·
2      scan    ·         ·                      (a, b, c, rowid[hidden,omitted])                                                    a!=NULL; b!=NULL; c!=NULL; rowid!=NULL; key(rowid)
2      ·       table     t1@primary             ·                                                                                   ·
2      ·       spans     ALL                    ·                                                                                   ·
2      ·       filter    (a, b, c) > (1, 2, 3)  ·                                                                                   ·
2      scan    ·         ·                      (a, b, d, rowid[hidden,omitted])                                                    rowid!=NULL; key(rowid)
2      ·       table     t2@primary             ·                                                                                   ·
2      ·       spans     ALL                    ·                                                                                   ·
                                                         ·
```
We could be pushing down the filter `(a, b) >= (1, 2)` to the other side.

### PR DESCRIPTION
**Pull request by RaduBerinde**
We know that `(a, b, x) > (1, 2, 3)` implies `(a, b) >= (1, 2)`; we want to use
this if only variables `a` and `b` are available (e.g. one side of a join).

Note that we don't handle tuple equality; instead, my proposal is to normalize
those to conjunctions so we don't have to have special code in multiple places
(#20473).

Fixes #20472.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
Thanks for tackling this.

Commit message:
```
Release note (sql change): queries that use inequalities using tuples, e.g. (a,b,c) < (x,y,z), are now slightly better optimized.
```

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/expr_filter.go, line 155 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20484#-L-cSz0NUstYiLAvh19k:-L-cSz0Ouu6ngHrVGTEs:bmwnmee) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c2a9e8f74dbd15528c2ceb67a917ea5562d23c4/pkg/sql/expr_filter.go#L155)):*
> ```Go
> }
> 
> // If we have a tuple comparison, we want to try to see if we can use a
> ```

Explain that the function does at a high level and what are the arguments before you provide the examples.

---

*[pkg/sql/expr_filter.go, line 164 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20484#-L-cSR5oIXVGYOTxAHIq:-L-cSR5oIXVGYOTxAHIr:b5ewb2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c2a9e8f74dbd15528c2ceb67a917ea5562d23c4/pkg/sql/expr_filter.go#L164)):*
> ```Go
> //   (a, b, x) >= (1, 2, 3)
> // becomes
> //   (a, b) > (1, 2, 3)
> ```

the second part I disagree with. (a, b, x) >= (1,2,3) does not imply (a,b) > (1,2).
You say something about NOT below but it is not explained here. It is not clear what the "weaker" argument stands for and its relationship with NOT. Please use more words to make the explanation true.

---

*[pkg/sql/expr_filter.go, line 213 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20484#-L-cSp1aTijI-Hk9IuXF:-L-cSp1aTijI-Hk9IuXG:b-yxtv6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c2a9e8f74dbd15528c2ceb67a917ea5562d23c4/pkg/sql/expr_filter.go#L213)):*
> ```Go
> 		newOp.Left = left.Truncate(prefix)
> 		newOp.Right = &tree.DTuple{
> 			D:      append(tree.Datums(nil), right.D[:prefix]...),
> ```

Curious: why not `D: right.D[:prefix]` directly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20484#-:-L-cTTEssY3v2jc8xnlG:biw8cuw)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/expr_filter.go, line 164 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20484#-L-cSR5oIXVGYOTxAHIq:-L-cXG5e0ykaIxjhFprw:bp8lc7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c2a9e8f74dbd15528c2ceb67a917ea5562d23c4/pkg/sql/expr_filter.go#L164)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Add here:
```
// Because  (a,b) > (1,2) implies  (a,b,x) >= (1,2,3) for every x.
```

---

*[pkg/sql/expr_filter.go, line 213 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20484#-L-cSp1aTijI-Hk9IuXF:-L-cXvsRB4tZF7D7fCNw:b-rbvw8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c2a9e8f74dbd15528c2ceb67a917ea5562d23c4/pkg/sql/expr_filter.go#L213)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I wondered if that's safe and it seems like it should be, but I chose the safe route. I can change it if you prefer.
</blockquote></details>

The datums are immutable. The simpler code is safe (conversely, if it's not safe then we have much more serious problems elsewhere anyway).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20484#-:-L-cY27mhc8KDvd6TJRq:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/expr_filter.go, line 164 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20484#-L-cSR5oIXVGYOTxAHIq:-L-cYf7OmxC8_cFZ6rb7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c2a9e8f74dbd15528c2ceb67a917ea5562d23c4/pkg/sql/expr_filter.go#L164)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Add here:
```
// Because  (a,b) > (1,2) implies  (a,b,x) >= (1,2,3) for every x.
```


</blockquote></details>

Done.

---

*[pkg/sql/expr_filter.go, line 213 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20484#-L-cSp1aTijI-Hk9IuXF:-L-cYNbCzJTkP2tEEu6z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c2a9e8f74dbd15528c2ceb67a917ea5562d23c4/pkg/sql/expr_filter.go#L213)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

The datums are immutable. The simpler code is safe (conversely, if it's not safe then we have much more serious problems elsewhere anyway).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20484)*

**Comment by knz** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20484)*

**Pull request merged**
