### PR TITLE
technote/txn_coord_sender: clarify TransactionAbortedError

### PR DESCRIPTION
**Pull request by andreimatei**
Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]

**Comment by knz** [comment]
is this up to date with your latest error state change?

**Review by andreimatei — COMMENTED** [review]
Yeah, the note about `TransactionAbortedError` is fine. I've added some more words to it, PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42803#-:-LyVDOrhEHB2-9DQJVLb:bdswlrf)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by knz — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42803)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42803#-:-LyZvSdY3uKMrbzFR4tY:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
