### PR TITLE
ccl: make most CCL tests link in all the CCL code; don't skip tests

### PR DESCRIPTION
**Pull request by andreimatei**
Before this patch, a lot of ccl/... tests were being silently skipped
50% of the time, when `ShouldStartDefaultTestTenant()` decided to
attempt to create a tenant: the `TestServer` startup code was trying to
create a tenant which was failing in a lot of ccl test packages because
the tests in these packages were running in binaries that didn't have
various other ccl/... packages linked in. The tenant creation error was
then swallowed and the test skipped. Having tests be skipped half the
time is no good; this patch makes the tenant creation no longer fail for
any ccl tests that's starting a server, and deletes the silent skipping.

The transparent creation of the tenant is checking whether a license is
active - which, in the context of tests, reduces to checking whether
utilccl.TestingEnableEnterprise() was called (perhaps in main_test.go).
However, this was not enough to guarantee that the tenant creation will
succeed instead of failing with a bizarre "ccl binary required" error.
Even though we knew that some CCL code was linked in (i.e. utilccl),
this doesn't mean that *all* ccl code was linked in.

This patch makes it such that a license check (i.e.
utilccl.CheckEnterpriseEnabled()) doesn't succeed when "all the CCL
code" (i.e. the `ccl` pkg) is not linked in. When that's not the case,
the function panics, telling you that you need to add more deps to your
test binary. The `TestingEnableEnterprise()` function moves `utilccl` to
`ccl`, thus forcing the majority of ccl tests to import `ccl` (usually
in their `main_test.go`, which generally moves to the `foo_test` pkg to
avoid a dep cycle).
I'm also leaving behind a utilccl.TestingEnableEnterpriseTricky(), which
enables the license without forcing `ccl` to be imported. This is used
by the few packages that want more control over enabling/disabling the
license but cannot import `ccl` without a dep cycle; such tests in pkg
`foo` generally import `ccl` from a file in the `foo_test` pkg (so `ccl`
ends up being linked in the shared test binary).

utilccl.CheckEnterpriseEnabled() stays in the `utilccl` pkg, so everyone
can use it without dep cycles, but it relies from a bool injected from
the `ccl` pkg.

This patch builds on https://github.com/cockroachdb/cockroach/pull/92024, which made a bunch of ccl tests pass when
running against a tenant, instead of fail, once they're no longer
skipped.

---

Now that utilccl.CheckEnterpriseEnabled() reliably determines whether
the CCL features are around, it can be used from BSL code (through
base.CheckEnterpriseEnabled()) to determine whether CCL features can be
used. This is a corollary of the things that were going for the
TestServer tenant creation, but this is how I actually got here: I tried
to use follower reads, gated by base.CheckEnterpriseEnabled(), only to
get an error in ccl tests that my binary is not ccl enough.

Release note: None
Epic: None

### CODE REVIEW

**Comment by andreimatei** [comment]
Last two commits are to be reviewed here now.

**Review by knz — COMMENTED** [review]
Nice work. I think we need to investigate the relationship between `package X` and `package X_test` wrt TestMain.

> Reviewed 2 of 2 files at r1, 153 of 153 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-:-NHOwYpBEN0g5sXZMCjf:b6kzwrd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @andreimatei, and @dt)

___
*[`pkg/ccl/utilccl/license_check.go` line 233 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHOtPzB5UqErH7Cv8CW:-NHOtPzB5UqErH7Cv8CX:b-kgidib) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ccaec4aed53c871862ba49f7acb9a68d61a6aeb/pkg/ccl/utilccl/license_check.go#L233)):*
> ```Go
> 		// thus, cannot depend on `ccl`. AllCCLCodeImported is used to break the
> 		// dependency cycle.
> 		log.Fatalf(context.Background(), "not all ccl imported, but license checked")
> ```

Can you make this an actual panic? This will ensure that the test output will contain the end marker needed by TC to report the name of the test in CI.
___
*[`pkg/ccl/backupccl/backuprand/main_test.go` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHOuHL7EZt663z-b7Sh:-NHOuHL7EZt663z-b7Si:bs57cch) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ccaec4aed53c871862ba49f7acb9a68d61a6aeb/pkg/ccl/backupccl/backuprand/main_test.go#L9)):*
> ```Go
> //     https://github.com/cockroachdb/cockroach/blob/master/licenses/CCL.txt
> 
> package backuprand_test
> ```

I don't think this one does what you think it does. NB: the tests in `backuprand_test.go` use `package backuprand`, and for that package the TestMain function will not run.
If you want do change this, also change the package in `backuprand_test.go`

(I did manually check that the other two packages `backupinfo` and `backupdest` were ok already)
___
*[`pkg/ccl/backupccl/backupresolver/main_test.go` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHOub5E9R9FNO2xLPG0:-NHOub5E9R9FNO2xLPG1:bovanqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ccaec4aed53c871862ba49f7acb9a68d61a6aeb/pkg/ccl/backupccl/backupresolver/main_test.go#L9)):*
> ```Go
> //     https://github.com/cockroachdb/cockroach/blob/master/licenses/CCL.txt
> 
> package backupresolver_test
> ```

ditto `backupresolver_test.go`
___
*[`pkg/ccl/changefeedccl/main_test.go` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHOukGf7k0aEvaemo7e:-NHOukGf7k0aEvaemo7f:b-qbj7j8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ccaec4aed53c871862ba49f7acb9a68d61a6aeb/pkg/ccl/changefeedccl/main_test.go#L9)):*
> ```Go
> //     https://github.com/cockroachdb/cockroach/blob/master/licenses/CCL.txt
> 
> package changefeedccl_test
> ```

Please review the other `_test.go` files in the package and adjust the package names accordingly.
___
*[`pkg/ccl/changefeedccl/cdctest/main_test.go` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHOusLNE3lmuX01rGju:-NHOusLNE3lmuX01rGjv:boxesge) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ccaec4aed53c871862ba49f7acb9a68d61a6aeb/pkg/ccl/changefeedccl/cdctest/main_test.go#L9)):*
> ```Go
> //     https://github.com/cockroachdb/cockroach/blob/master/licenses/CCL.txt
> 
> package cdctest_test
> ```

ditto `validator_test.go`
___
*[`pkg/ccl/changefeedccl/schemafeed/main_test.go` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHOuzqRATRWfMErH0s0:-NHOuzqRATRWfMErH0s1:b-poyaac) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ccaec4aed53c871862ba49f7acb9a68d61a6aeb/pkg/ccl/changefeedccl/schemafeed/main_test.go#L9)):*
> ```Go
> //     https://github.com/cockroachdb/cockroach/blob/master/licenses/CCL.txt
> 
> package schemafeed_test
> ```

ditto the other `_test.go` files
___
*[`pkg/ccl/jwtauthccl/main_test.go` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHOv55d3djX5y1-EO8K:-NHOv55d3djX5y1-EO8L:b-poyaac) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ccaec4aed53c871862ba49f7acb9a68d61a6aeb/pkg/ccl/jwtauthccl/main_test.go#L9)):*
> ```Go
> //     https://github.com/cockroachdb/cockroach/blob/master/licenses/CCL.txt
> 
> package jwtauthccl_test
> ```

ditto the other `_test.go` files
___
*[`pkg/ccl/multitenantccl/tenantcostclient/main_test.go` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHOvMOzAUF-umvKIU-Q:-NHOvMOzAUF-umvKIU-R:b-poyaac) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ccaec4aed53c871862ba49f7acb9a68d61a6aeb/pkg/ccl/multitenantccl/tenantcostclient/main_test.go#L9)):*
> ```Go
> //     https://github.com/cockroachdb/cockroach/blob/master/licenses/CCL.txt
> 
> package tenantcostclient_test
> ```

ditto the other `_test.go` files
___
*[`pkg/ccl/partitionccl/main_test.go` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHOvQlJ7yyHYCj0tbsm:-NHOvQlJ7yyHYCj0tbsn:b-poyaac) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ccaec4aed53c871862ba49f7acb9a68d61a6aeb/pkg/ccl/partitionccl/main_test.go#L9)):*
> ```Go
> //     https://github.com/cockroachdb/cockroach/blob/master/licenses/CCL.txt
> 
> package partitionccl_test
> ```

ditto the other `_test.go` files
___
*[`pkg/ccl/partitionccl/main_test.go` line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHOvWGZDOMWub4TR7Ig:-NHOvWG_5__TqzV-AEYK:b-3a5d7r) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ccaec4aed53c871862ba49f7acb9a68d61a6aeb/pkg/ccl/partitionccl/main_test.go#L29)):*
> ```Go
> 	// ccl.TestingEnableEnterprise() instead of the utilccl version. That requires
> 	// this file to move to the partitionccl_test package. Doing that causes one
> 	// of the tests to panic. I haven't investigated why.
> ```

You could file a followup issue though (and drop a link here). Thanks.
___
*[`pkg/ccl/sqlproxyccl/main_test.go` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHOvj1P5BMGguieSncb:-NHOvj1P5BMGguieSncc:b-poyaac) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ccaec4aed53c871862ba49f7acb9a68d61a6aeb/pkg/ccl/sqlproxyccl/main_test.go#L9)):*
> ```Go
> //     https://github.com/cockroachdb/cockroach/blob/master/licenses/CCL.txt
> 
> package sqlproxyccl_test
> ```

ditto the other `_test.go` files
___
*[`pkg/ccl/streamingccl/streamclient/main_test.go` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHOvpYDDozfpmKvLJxA:-NHOvpYDDozfpmKvLJxB:b-poyaac) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ccaec4aed53c871862ba49f7acb9a68d61a6aeb/pkg/ccl/streamingccl/streamclient/main_test.go#L9)):*
> ```Go
> //     https://github.com/cockroachdb/cockroach/blob/master/licenses/CCL.txt
> 
> package streamclient_test
> ```

ditto the other `_test.go` files
___
*[`pkg/ccl/streamingccl/streamingest/main_test.go` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHOvuYq4oW-WPEg1rM-:-NHOvuYr9uJN9WdgCMDr:b-poyaac) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ccaec4aed53c871862ba49f7acb9a68d61a6aeb/pkg/ccl/streamingccl/streamingest/main_test.go#L9)):*
> ```Go
> //     https://github.com/cockroachdb/cockroach/blob/master/licenses/CCL.txt
> 
> package streamingest_test
> ```

ditto the other `_test.go` files
___
*[`pkg/ccl/streamingccl/streamproducer/main_test.go` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHOvvHy8QCQTSTsLEYq:-NHOvvHy8QCQTSTsLEYr:b-poyaac) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ccaec4aed53c871862ba49f7acb9a68d61a6aeb/pkg/ccl/streamingccl/streamproducer/main_test.go#L9)):*
> ```Go
> //     https://github.com/cockroachdb/cockroach/blob/master/licenses/CCL.txt
> 
> package streamproducer_test
> ```

ditto the other `_test.go` files
___
*[`pkg/ccl/utilccl/main_test.go` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHOw2ezAchF0-WlYKzT:-NHOw2ezAchF0-WlYKzU:b-poyaac) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ccaec4aed53c871862ba49f7acb9a68d61a6aeb/pkg/ccl/utilccl/main_test.go#L9)):*
> ```Go
> //     https://github.com/cockroachdb/cockroach/blob/master/licenses/CCL.txt
> 
> package utilccl_test
> ```

ditto the other `_test.go` files
___
*[`pkg/ccl/workloadccl/main_test.go` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHOw9_o1Tcu37wt4Dty:-NHOw9_o1Tcu37wt4Dtz:bw5vixl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ccaec4aed53c871862ba49f7acb9a68d61a6aeb/pkg/ccl/workloadccl/main_test.go#L9)):*
> ```Go
> //     https://github.com/cockroachdb/cockroach/blob/master/licenses/CCL.txt
> 
> package workloadccl_test
> ```

this one is OK because the other _test.go files already have it.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92157)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @dt, and @knz)

___
*[`pkg/ccl/utilccl/license_check.go` line 233 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHOtPzB5UqErH7Cv8CW:-NHPjQmy20CdBgOlU0dR:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ccaec4aed53c871862ba49f7acb9a68d61a6aeb/pkg/ccl/utilccl/license_check.go#L233)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Can you make this an actual panic? This will ensure that the test output will contain the end marker needed by TC to report the name of the test in CI.
</blockquote></details>

done.
___
*[`pkg/ccl/backupccl/backuprand/main_test.go` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHOuHL7EZt663z-b7Sh:-NHPhSHd1QOROPsLtRnj:bzan7ol) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ccaec4aed53c871862ba49f7acb9a68d61a6aeb/pkg/ccl/backupccl/backuprand/main_test.go#L9)):*
All `_test.go` files get linked together, and a `TestMain` from either package is run before the tests from both packages run. If it wasn't, this PR would fail all the tests...
This is how our `TestServer` factrory injection works. In most BSL packages, `serverutils.InitTestServerFactory` needs to be done in an `_test` package.

> If you want do change this, also change the package in backuprand_test.go

Luckily we don't have to do this, because we couldn't do this - there's a reason most tests are in the same pkg as the code test and not in `_test`.
___
*[`pkg/ccl/partitionccl/main_test.go` line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHOvWGZDOMWub4TR7Ig:-NHPiI9oDP1UQSydXp_s:b7sqzef) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ccaec4aed53c871862ba49f7acb9a68d61a6aeb/pkg/ccl/partitionccl/main_test.go#L29)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

You could file a followup issue though (and drop a link here). Thanks.
</blockquote></details>

this was leftover; I had fixed it. Removed.

**Review by knz — APPROVED** [review]
:lgtm: thanks!

> Reviewed 2 of 9 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-:-NHQEZvX5xPaucI8KC03:brfqlux)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @andreimatei, and @dt)

**Review by ajstorm — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92157)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @dt, and @knz)

___
*[`pkg/ccl/utilccl/license_check.go` line 80 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHQLi-D4LktK1WESpYz:-NHQLi-D4LktK1WESpZ-:b2f2hi5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b6ce4055f969735049595a22b824c968199c309/pkg/ccl/utilccl/license_check.go#L80)):*
> ```Go
> // TestingEnableEnterpriseTricky is only useful if `ccl` was imported elsewhere
> // (commonly in a file in the foo_test package, perhaps main_test.go).
> func TestingEnableEnterpriseTricky() func() {
> ```

The term "tricky" here is a bit too obfuscated for my liking (as evidenced by the fact that you have to define what you mean by tricky in this comment).  What about something like `TestingMaybeEnableEnterprise` and then state in the comment that this should only be used if the caller is certain that the `ccl` package was fully imported elsewhere?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92157)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm, @dt, and @knz)

___
*[`pkg/ccl/utilccl/license_check.go` line 80 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHQLi-D4LktK1WESpYz:-NHQdETh0cenwGIPDNms:b-qg0y9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b6ce4055f969735049595a22b824c968199c309/pkg/ccl/utilccl/license_check.go#L80)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

The term "tricky" here is a bit too obfuscated for my liking (as evidenced by the fact that you have to define what you mean by tricky in this comment).  What about something like `TestingMaybeEnableEnterprise` and then state in the comment that this should only be used if the caller is certain that the `ccl` package was fully imported elsewhere?
</blockquote></details>

I've removed "tricky" from the name, and instead made the function at panic at runtime if `ccl` wasn't linked in. No callers were affected. PTAL.

**Review by ajstorm — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92157)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @dt, and @knz)

___
*[`pkg/ccl/utilccl/license_check.go` line 75 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHQgTVt79cg84VCpz-G:-NHQgTVu32b3hHvuH9cJ:b-9vfi8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9c5c56103ea3946fb2076075ab5c35a9002380f/pkg/ccl/utilccl/license_check.go#L75)):*
> ```Go
> // TestingEnableEnterprise allows overriding the license check in tests.
> //
> // Prefer using ccl.TestingDisableEnterprise instead when that's possible
> ```

Should this be `ccl.TestingEnableEnterprise`?
___
*[`pkg/ccl/utilccl/license_check.go` line 77 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHQhFTPATtPHnzJp7Hd:-NHQhFTPATtPHnzJp7He:b-kvyp1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9c5c56103ea3946fb2076075ab5c35a9002380f/pkg/ccl/utilccl/license_check.go#L77)):*
> ```Go
> // Prefer using ccl.TestingDisableEnterprise instead when that's possible
> // without introducing a dependency cycle. This function is useful for packages
> // that can't import `ccl`. However, it panics if package `ccl` (which, in turn,
> ```

Nit: ...that can't import `ccl` _without introducing a dependancy cycle_.  However, _the function_ panics if...
___
*[`pkg/ccl/utilccl/license_check.go` line 81 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHQhdll-Su6-VkuaDTv:-NHQhdll-Su6-VkuaDTw:b-r69djo) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9c5c56103ea3946fb2076075ab5c35a9002380f/pkg/ccl/utilccl/license_check.go#L81)):*
> ```Go
> // tests, generally the right thing to do is to import `ccl` in a file in the
> // `foo_test` pkg (for example, main_test.go). Frequently, calling
> // ccl.TestingEnableEnterprise in TestMain is enough, so this
> ```

What do you mean by "enough" here?
___
*[`pkg/ccl/utilccl/license_check.go` line 83 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHQhpEu9xEGQje_9F1C:-NHQhpEvAwMBKVlm0qom:b-al4q2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9c5c56103ea3946fb2076075ab5c35a9002380f/pkg/ccl/utilccl/license_check.go#L83)):*
> ```Go
> // ccl.TestingEnableEnterprise in TestMain is enough, so this
> // utilccl.TestingEnableEnterprise is not frequently used. Even if this function
> // didn't panic, CheckEnterpriseEnabled() requires all the CCL code to be linked
> ```

Nit: Even if this function didn't panic, CheckEnterpriseEnabled() _will panic if not all the CCL code has been linked in, so callers of this function would likely just have the panic kicked down the road to the check call_.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92157)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm, @dt, and @knz)

___
*[`pkg/ccl/utilccl/license_check.go` line 75 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHQgTVt79cg84VCpz-G:-NHRoxgO4kkxtPhJRZDW:b-5g9o7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9c5c56103ea3946fb2076075ab5c35a9002380f/pkg/ccl/utilccl/license_check.go#L75)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Should this be `ccl.TestingEnableEnterprise`?
</blockquote></details>

yes, done
___
*[`pkg/ccl/utilccl/license_check.go` line 77 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHQhFTPATtPHnzJp7Hd:-NHRp7086ln0UYVldjDw:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9c5c56103ea3946fb2076075ab5c35a9002380f/pkg/ccl/utilccl/license_check.go#L77)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: ...that can't import `ccl` _without introducing a dependancy cycle_.  However, _the function_ panics if...
</blockquote></details>

done
___
*[`pkg/ccl/utilccl/license_check.go` line 81 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHQhdll-Su6-VkuaDTv:-NHRpIqs8TCh_obqSyJy:b-jui4rr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9c5c56103ea3946fb2076075ab5c35a9002380f/pkg/ccl/utilccl/license_check.go#L81)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

What do you mean by "enough" here?
</blockquote></details>

I expanded.
___
*[`pkg/ccl/utilccl/license_check.go` line 83 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHQhpEu9xEGQje_9F1C:-NHRqMikDZgBfaAWJhm6:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9c5c56103ea3946fb2076075ab5c35a9002380f/pkg/ccl/utilccl/license_check.go#L83)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Even if this function didn't panic, CheckEnterpriseEnabled() _will panic if not all the CCL code has been linked in, so callers of this function would likely just have the panic kicked down the road to the check call_.
</blockquote></details>

done

**Review by ajstorm — APPROVED** [review]
:lgtm: Thanks for making the changes.  One super-minor nit left.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-:-NHUaofZ8BuAcDLMSt8a:bcfszmh)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @dt, and @knz)

___
*[`pkg/ccl/utilccl/license_check.go` line 83 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHQhpEu9xEGQje_9F1C:-NHUaK67APgHpyctQp_h:b-j26z3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9c5c56103ea3946fb2076075ab5c35a9002380f/pkg/ccl/utilccl/license_check.go#L83)):*
Thanks.  One super minor nit: 

> if not all the CCL code to be linked in

should be "if not all the CCL code has been linked in"

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92157)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @dt and @knz)

___
*[`pkg/ccl/utilccl/license_check.go` line 83 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92157#-NHQhpEu9xEGQje_9F1C:-NHUsO7y8uoYb1JNxeEK:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9c5c56103ea3946fb2076075ab5c35a9002380f/pkg/ccl/utilccl/license_check.go#L83)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Thanks.  One super minor nit: 

> if not all the CCL code to be linked in

should be "if not all the CCL code has been linked in"
</blockquote></details>

done

**Pull request merged**
