### PR TITLE
distsql: add support for partition spans in tenant

### PR DESCRIPTION
**Pull request by rharding6373**
This PR adds `PartitionSpansTenant`, which assigns SQL instances to
    spans when distsql is in tenant mode. The current implementation is a
    naive round-robin approach. That is, we find all available instances in
    the tenant and assign each span requested by the caller to an instance
    in round-robin order. This is reasonable for the initial use case,
    backup operations, since spans must completely cover a table's span.
    
    Release note (sql change): Adds support for distributed backup in a
    multitenant environment that uses all available SQL pods in the tenant.

### CODE REVIEW

**Review by rharding6373 — COMMENTED** [review]
Note: First two commits are from #76566.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77023#-:-MwjCkoXBKJwjmgOTUOc:b-byc9ey)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @cucaroach, and @yuzefovich)

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77023#-:-MwjMA0nEmc4e0fSXpFy:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @cucaroach, and @rharding6373)

___
*[pkg/sql/distsql_physical_planner.go, line 1151 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77023#-MwjLLhq2x9I-W4nGZb3:-MwjLLhq2x9I-W4nGZb4:b-7e0fp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f413059bec29b78ed2baa09a2a9e209c5600a4b/pkg/sql/distsql_physical_planner.go#L1151)):*
> ```Go
> 		return nil, err
> 	}
> 	rand.Shuffle(len(instances), func(i, j int) {
> ```

nit: add a comment for why we do this shuffle.

**Review by rharding6373 — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77023#-:-MwmXwWsBEzd3Y1PbJ9w:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @ajwerner, @cucaroach, and @yuzefovich)

___
*[pkg/sql/distsql_physical_planner.go, line 1151 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77023#-MwjLLhq2x9I-W4nGZb3:-MwmXuJL8PqdcgHYBSKR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f413059bec29b78ed2baa09a2a9e209c5600a4b/pkg/sql/distsql_physical_planner.go#L1151)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: add a comment for why we do this shuffle.
</blockquote></details>

Done.

**Pull request merged**
