### PR TITLE
sql: create stats after a schema change

### LINKED ISSUE #34839: opt: trigger automatic statistics when adding an index
Automatic stats are only triggered when ~5-10% rows are changed or its been 2x the average refresh and a change hasn't been triggered.

We should experiment with adding automatic statistics when an index is added. Users add indexes to improve performance--we should give them the best result possible by using the best statistics possible.

### PR DESCRIPTION
**Pull request by rytaft**
This commit triggers statistics creation after a successful
schema change. This ensures that new indexes and columns are
included in the latest stats.

Fixes #34839

Release note (sql change): Schema changes now trigger automatic
statistics collection for the affected table.

### CODE REVIEW

**Review by vivekmenezes — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35252)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, @rytaft, and @vivekmenezes)

___
*[pkg/sql/schema_changer.go, line 1115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35252#-L_7b6Z7CjQKM8cXIMe4:-L_7b6Z7CjQKM8cXIMe5:bi2xm5t) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c46b61a64d8b7c39e9214b6ba770ed7371e9f92/pkg/sql/schema_changer.go#L1115)):*
> ```Go
> 		sc.tableID,
> 		math.MaxInt32, /* rowsAffected */
> 	)
> ```

Looks like this will run the stats collection asynchronously. That's what we want here.

**Comment by rytaft** [comment]
___
*[pkg/sql/schema_changer.go, line 1115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35252#-L_7b6Z7CjQKM8cXIMe4:-L_AyBJuBDSr8CgiNeF3:b-2aj8nm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c46b61a64d8b7c39e9214b6ba770ed7371e9f92/pkg/sql/schema_changer.go#L1115)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Looks like this will run the stats collection asynchronously. That's what we want here.
</blockquote></details>

Yep it's all asynchronous -- would it help for me to update the comment?

**Review by vivekmenezes — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35252)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, and @rytaft)

___
*[pkg/sql/schema_changer.go, line 1115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35252#-L_7b6Z7CjQKM8cXIMe4:-L_CGvypBuUH8eQ7noId:b43w1vj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c46b61a64d8b7c39e9214b6ba770ed7371e9f92/pkg/sql/schema_changer.go#L1115)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Yep it's all asynchronous -- would it help for me to update the comment?
</blockquote></details>

Yes please do. Feel free to merge!

**Comment by rytaft** [comment]
Thanks!

bors r+

**Pull request merged**
