### PR TITLE
vendor: bump Pebble to 821db50635d6

### PR DESCRIPTION
**Pull request by jbowens**
```
821db506 db: respect IterOptions bounds during range-key iteration
c3ead1bc internal/rangekey: add DefragmentingIter
51cf6fbd internal/metamorphic: disable disk-backed FS for random configs
6af77d55 internal/metamorphic: use at least FormatRangeKeys
b1af263a internal/metamorphic: write range keys
3dce07ae db: add format major version for range keys
caab54e5 internal/manifest: Add randomized test for incremental sublevels
b6bb9870 internal/cache: enable debug stack collection when tracing enabled
b2295acd db: add experimental DB.RegisterFlushCompletedCallback
4402015c db: add OnlyReadGuaranteedDurable to IterOptions
20377e7d sstable: estimate indexBlock.estimatedSize()
db46dab6 internal/rangekey: fix interleaving iteration bug
b7b78b1c internal/manifest: incrementally generate L0Sublevels for L0 additions
788ef98e sstable: estimate Writer.EstimatedSize for cases when parallelism is enabled
a29a18b5 sstable: close `Writer` on `RewriteKeySuffixes` error
```

Release note: none

### CODE REVIEW

**Review by mufeez-amjad — APPROVED** [review]

**Review by nicktrav — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76744#-:-Mw84G5BA08FwmBWGh8N:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Review by nicktrav — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76744)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens)

**Review by nicktrav — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76744)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens)

**Review by jbowens — COMMENTED** [review]
TFTRs!

r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76744#-:-Mw8rGNH8nAvrpIDNs0K:bc3z4os)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens)

**Comment by jbowens** [comment]
oops,

bors r+

**Pull request merged**
