### PR TITLE
storage: select 2 random candidates instead of 10

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10761)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/allocator_test.go, line 719 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10761#-KWmzwlOXFEyaqpwumXs:-KWmzwlOXFEyaqpwumXt:bvv46cx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8e82133d05454e5731b9a0a8cd4b99344514ff/pkg/storage/allocator_test.go#L719)):*
> ```Go
> 			// We might not get a rebalance target if the random nodes selected as
> 			// candidates are not suitable targets.
> 			if result != nil && result.StoreID != 1 && result.StoreID != 2 {
> ```

Perhaps this loop should run until 10 instances of stores 1 or 2 are seen, rather than 10 instances total.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10761#-:-KWmzlMp6rWhWPfKJPoE:bg7igkv)*

**Comment by petermattis** [comment]
Btw, this was exacerbating the problem we were seeing on blue. When a node goes down and we decide to recover a replica on the dead node, every other node in the cluster would select the "best" node to add the new replica to. This effectively limits the recovery bandwidth to the single "best" node in the cluster.

**Comment by petermattis** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/allocator_test.go, line 719 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10761#-KWmzwlOXFEyaqpwumXs:-KWn0389j26yOqaaMzVO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8e82133d05454e5731b9a0a8cd4b99344514ff/pkg/storage/allocator_test.go#L719)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Perhaps this loop should run until 10 instances of stores 1 or 2 are seen, rather than 10 instances total.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10761)*

**Comment by BramGruneir** [comment]
LGTM

But shouldn't the reservation system have each node choose the next best if the best one was denied?

**Comment by BramGruneir** [comment]
Ah, no it wouldn't because we have the reservation timeout set to 0.  Why no up that to 1 sec?

**Comment by petermattis** [comment]
> But shouldn't the reservation system have each node choose the next best if the best one was denied?

Not as far as I can tell.

**Comment by petermattis** [comment]
> Ah, no it wouldn't because we have the reservation timeout set to 0. Why no up that to 1 sec?

Because snapshots can often take less than a second.

**Comment by BramGruneir** [comment]
Sure, but that's only an advantage when you have a ton of snapshots trying to get to a single machine.  In this case, the 2nd best, and all the rest, are perfect fine.

**Comment by petermattis** [comment]
> Sure, but that's only an advantage when you have a ton of snapshots trying to get to a single machine. In this case, the 2nd best, and all the rest, are perfect fine.

Any "best" is problematic. That's the motivation behind this change. We can't determine "best" in a distributed fashion and 2 is a much better number of random candidates than any larger number (3, 4, 5, etc).

**Comment by BramGruneir** [comment]
I'm not disputing the change, I think it will work well.  

I'm suggesting that we up the timeout on declined reservation to 1s (or maybe 0.5s).

**Comment by petermattis** [comment]
> I'm suggesting that we up the timeout on declined reservation to 1s (or maybe 0.5s).

I have reservations to that change. It mentally confuses my model of candidates and random selection to be filtering off a portion of the nodes for a period of time. And we noticed problems in the past with a non-zero throttling for declined reservations.

**Comment by BramGruneir** [comment]
The only real disadvantage I can think of is when adding a new node to a small system.  Say a 3 -> 4 node cluster.

In that case, it would slow down replication. since all 3 would try to send a snapshot at once, and 2 would be slowed down, potentially allowing only one node to proceed while the others wait (we could mitigate this with some randomization in the wait times).  In a larger system, 10 nodes or so, this shouldn't be an issue.

I think it's worth testing again.  I'll take a look at doing so when I have some time.

**Pull request merged**
