### PR TITLE
exec: template hash join

### PR DESCRIPTION
**Pull request by changangela**
This commit pulls the hash join execgen templating string into the `hashjoiner_tmpl.go` file. We also added some more advanced templating techniques using the `{{define}}` semantics. This allows us to easily template out duplicate code and selection vector duplication.

This PR builds off of #32836.

### CODE REVIEW

**Review by asubiotto — COMMENTED** [review]
Nice work, this looks fine to me. @jordanlewis, do you want to take a quick look at this?

> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33237#-:-LU6VykxALwaj3X_RU0N:by3yuy1)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/execgen/cmd/execgen/hashjoiner_gen.go, line 60 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33237#-LU6VP3H0ONckaZP96M3:-LU6VP3H0ONckaZP96M4:b-yak94y) ([raw file](https://github.com/cockroachdb/cockroach/blob/772d53e57926ce8d13989b2f29df8d844df15856/pkg/sql/exec/execgen/cmd/execgen/hashjoiner_gen.go#L60)):*
> ```Go
> 
> 	tmpl, err := template.New("hashjoiner_op").Funcs(template.FuncMap{
> 		"buildDict": func(values ...interface{}) (map[string]interface{}, error) {
> ```

What does this `buildDict` do?
___
*[pkg/sql/exec/execgen/cmd/execgen/hashjoiner_gen.go, line 84 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33237#-LU6UTBTEZbzJU46dL5g:-LU6UTBU0L21Bzc4uyfh:bu34ubj) ([raw file](https://github.com/cockroachdb/cockroach/blob/772d53e57926ce8d13989b2f29df8d844df15856/pkg/sql/exec/execgen/cmd/execgen/hashjoiner_gen.go#L84)):*
> ```Go
> 		HashTemplate interface{}
> 	}{
> 		NETemplate:   comparisonOpToOverloads[tree.NE],
> ```

Is it not necessary to do an intersection of `comparisonOpToOverload[tree.NE]` with `hashOverloads`?

**Review by changangela — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33237)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/execgen/cmd/execgen/hashjoiner_gen.go, line 60 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33237#-LU6VP3H0ONckaZP96M3:-LU6YOy08nyv2TCbZtt_:b-ortoqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/772d53e57926ce8d13989b2f29df8d844df15856/pkg/sql/exec/execgen/cmd/execgen/hashjoiner_gen.go#L60)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What does this `buildDict` do?
</blockquote></details>

It's a function that builds a dictionary out of its arguments. The reason we are using this is because the templating language only allows 1 argument to be passed in to `{{template funcName arg}}` and we get around that by building multiple arguments into a single dictionary (`{{template funcName buildDict argName1 arg1 argName2 arg2 ... }}`. I'll work on documenting this better.
___
*[pkg/sql/exec/execgen/cmd/execgen/hashjoiner_gen.go, line 84 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33237#-LU6UTBTEZbzJU46dL5g:-LU6Z0-1DHFr6rgeypue:b8o7l9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/772d53e57926ce8d13989b2f29df8d844df15856/pkg/sql/exec/execgen/cmd/execgen/hashjoiner_gen.go#L84)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is it not necessary to do an intersection of `comparisonOpToOverload[tree.NE]` with `hashOverloads`?
</blockquote></details>

In this case we can just use them separately since we never need both NE and Hash in the same function.

**Review by asubiotto — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33237)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/execgen/cmd/execgen/hashjoiner_gen.go, line 60 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33237#-LU6VP3H0ONckaZP96M3:-LU6b6DG3k2h3D5Rj4I-:bfh215q) ([raw file](https://github.com/cockroachdb/cockroach/blob/772d53e57926ce8d13989b2f29df8d844df15856/pkg/sql/exec/execgen/cmd/execgen/hashjoiner_gen.go#L60)):*
<details><summary><i>Previously, changangela (Angela Chang) wrote…</i></summary><blockquote>

It's a function that builds a dictionary out of its arguments. The reason we are using this is because the templating language only allows 1 argument to be passed in to `{{template funcName arg}}` and we get around that by building multiple arguments into a single dictionary (`{{template funcName buildDict argName1 arg1 argName2 arg2 ... }}`. I'll work on documenting this better.
</blockquote></details>

I see, cool. Yes, a comment would be great.
___
*[pkg/sql/exec/execgen/cmd/execgen/hashjoiner_gen.go, line 84 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33237#-LU6UTBTEZbzJU46dL5g:-LU6bBZX3wcbzXsR48DI:b27dl2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/772d53e57926ce8d13989b2f29df8d844df15856/pkg/sql/exec/execgen/cmd/execgen/hashjoiner_gen.go#L84)):*
<details><summary><i>Previously, changangela (Angela Chang) wrote…</i></summary><blockquote>

In this case we can just use them separately since we never need both NE and Hash in the same function.
</blockquote></details>

I'm not sure I follow. What if you have one type that implements NE but not hash? Won't you get a panic when you try to `checkCol` but you'll be able to `rehash` just fine? Or maybe it doesn't matter because one is for probing and the other is for building so it's a valid state?

**Review by changangela — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33237)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/execgen/cmd/execgen/hashjoiner_gen.go, line 60 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33237#-LU6VP3H0ONckaZP96M3:-LU6qwOLElalely_5Xbx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/772d53e57926ce8d13989b2f29df8d844df15856/pkg/sql/exec/execgen/cmd/execgen/hashjoiner_gen.go#L60)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I see, cool. Yes, a comment would be great.
</blockquote></details>

Done.
___
*[pkg/sql/exec/execgen/cmd/execgen/hashjoiner_gen.go, line 84 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33237#-LU6UTBTEZbzJU46dL5g:-LU6YzNhEbvY332XlsRP:b-50saz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/772d53e57926ce8d13989b2f29df8d844df15856/pkg/sql/exec/execgen/cmd/execgen/hashjoiner_gen.go#L84)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm not sure I follow. What if you have one type that implements NE but not hash? Won't you get a panic when you try to `checkCol` but you'll be able to `rehash` just fine? Or maybe it doesn't matter because one is for probing and the other is for building so it's a valid state?
</blockquote></details>

Oh I see what you mean. I've added a intersectOverloads function.

**Review by asubiotto — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33237#-:-LU7-Brh0U5xPWTj4V4q:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/execgen/cmd/execgen/hashjoiner_gen.go, line 84 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33237#-LU6UTBTEZbzJU46dL5g:-LU7--Sx56zZB2WjDGg1:b-yr3oba) ([raw file](https://github.com/cockroachdb/cockroach/blob/772d53e57926ce8d13989b2f29df8d844df15856/pkg/sql/exec/execgen/cmd/execgen/hashjoiner_gen.go#L84)):*
<details><summary><i>Previously, changangela (Angela Chang) wrote…</i></summary><blockquote>

Oh I see what you mean. I've added a intersectOverloads function.
</blockquote></details>

Great! That'll be very useful

**Review by changangela — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33237)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/hashjoiner_tmpl.go, line 16 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33237#-LU7KQbz6WDjdPXkJmtl:-LU7KQbz6WDjdPXkJmtm:b-ar28tt) ([raw file](https://github.com/cockroachdb/cockroach/blob/3615897b21a799e5aac7fdba05fc8e78b49e1715/pkg/sql/exec/hashjoiner_tmpl.go#L16)):*
> ```Go
> 
> // {{/*
> // +build execgen_template
> ```

@jordanlewis do we want to keep this?

**Comment by jordanlewis** [comment]
Oops - certainly not. Amended. The rest LGTM so let's merge.

**Pull request merged**
