### PR TITLE
spanconfig,kvserver: teach the GC job to respect tenant PTS records

### LINKED ISSUE #77239: gcjob: consult protected timestamps when deciding to GC tenants
**Describe the problem**

The GC job waits out the GC TTL set on a tenant's `RANGE DEFAULT` zone configuration when GC-ing it. Now that we've introduced protected timestamps for secondary tenant ranges as well, we need to account for them when GC-ing tenants as well. This is very similar to how we take into account protected timestamp information when GC-ing tables/indexes on the system tenant today, where we wait till the protection is removed even if the TTL has expired. 

It's an open question if we should be reading protected timestamp information that a tenant has set on its spans when deciding to GC the tenant or not. The tenant may have set a protected timestamp on its entire keyspace or on specific table's ranges. I'm inclined to say no, because whatever operation set the protection to begin with may not be around to remove it if the tenant is deleted. Think of a backup that was running when the tenant was deleted. 

We should however take into account any protected timestamp the system tenant may have written over the tenant's keyspace when GC-ing a tenant. This includes a protected timestamp set explicitly over the tenant's keyspace or one that was set on the entire keyspace. 

Jira issue: CRDB-13496

### PR DESCRIPTION
**Pull request by adityamaru**
This change teaches the GC job responsible for ClearRange'ing a tenants
data to respect protected timestamp records that are protecting a tenants
data. Specifically, once the tenants row data has expired, the GC job now
checks for protected timestamp records that have been written by the system
tenant targetting that particular tenant, or targetting its entire keyspace
i.e. all secondary tenants. If the record is protecting a time less than the
drop time of the tenant then the GC will be delayed.

This change also consolidates all tenant GC related tests into one file. The only
new test is `TestGCTenantJobWaitsForProtectedTimestamps`.

Release note (enterprise change): Tenant GC job will now wait for protected
timestamp records targetting the tenant, and with a protect time less than
the tenant's drop time.

Release justification: high-priority changes in existing functionality

Fixes: #77239

### CODE REVIEW

**Comment by adityamaru** [comment]
First commit is from #77478 which im going to try to merge ASAP.

**Comment by adityamaru** [comment]
friendly ping @arulajmani @ajwerner

**Review by arulajmani — COMMENTED** [review]
Sorry for taking so long to review this. Breather week and what not. Mostly looks good! 

> Reviewed 1 of 1 files at r1, 5 of 16 files at r2, 16 of 16 files at r3, 15 of 16 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-:-MyhzsCTEGXpoRA97Gm5:b-ucx9hf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @arulajmani)

___
*[-- commits, line 12 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-MygfseC9h8JwrPrfNlX):*
nit: to respect protected timestamp records set by the system tenant that are protecting... 

Also, could you add some words around why this is sane?
___
*[pkg/kv/kvserver/protectedts/ptutil/testutils.go, line 11 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-Mygo-lA0FFpBaLLvgNX:-Mygo-lA0FFpBaLLvgNY:b-v6k841) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/kv/kvserver/protectedts/ptutil/testutils.go#L11)):*
> ```Go
> // licenses/APL.txt.
> 
> package ptutil
> ```

Can we put this file in package `protectedts`? 
___
*[pkg/kv/kvserver/protectedts/ptutil/testutils.go, line 29 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-Mygnv25Cwm2D2cvJmCv:-Mygnv25Cwm2D2cvJmCw:bw5ho8j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/kv/kvserver/protectedts/ptutil/testutils.go#L29)):*
> ```Go
> // ensures a protection at the given protectionTimestamp exists for all the
> // supplied spans.
> func VerifyProtectionTimestampExistsOnSpans(
> ```

s/VerifyProtecteionTimestampExistsOnSpans/TestingVerifyProtectionTimestampExistsOnSpans/g
___
*[pkg/sql/gcjob/refresh_statuses.go, line 320 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-Mygku944pY0TgOZdKwr:-Mygku957tIcA_XWDr5g:b-4967qp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/sql/gcjob/refresh_statuses.go#L320)):*
> ```Go
> 		return nil
> 	}); err != nil {
> 		return isProtected, err
> ```

nit: return false, nil?
___
*[pkg/sql/gcjob/refresh_statuses.go, line 342 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-MyglFSx5tPDSb6yPiJ_:-MyglFSx5tPDSb6yPiJa:bq0ivig) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/sql/gcjob/refresh_statuses.go#L342)):*
> ```Go
> 	cfg := execCfg.SystemConfig.GetSystemConfig()
> 	zoneCfg, err := cfg.GetZoneConfigForObject(keys.MakeSQLCodec(roachpb.MakeTenantID(tenID)), 0)
> 	if err != nil {
> ```

Do we need to make this change that removes the fallback logic in this patch?
___
*[pkg/sql/gcjob/refresh_statuses.go, line 359 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-Myhq2v21QiX4OAHUupa:-Myhq2v21QiX4OAHUupb:b8zzxjh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/sql/gcjob/refresh_statuses.go#L359)):*
> ```Go
> 
> 		if isProtected {
> 			log.Infof(ctx, "GC TTL for dropped tenant %d has expired, but protected timestamp"+
> ```

nit: missing space?
___
*[pkg/ccl/testccl/sqlccl/tenant_gc_test.go, line 132 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-Myhp7n47-PfvR9cR01P:-Myhp7n47-PfvR9cR01Q:b-h5n5oo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/ccl/testccl/sqlccl/tenant_gc_test.go#L132)):*
> ```Go
> }
> 
> func TestGCTenantJobWaitsForProtectedTimestamps(t *testing.T) {
> ```

nit: could you add a comment?
___
*[pkg/ccl/testccl/sqlccl/tenant_gc_test.go, line 135 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-MyhouIlBdfNMowo_3Q4:-MyhouIlBdfNMowo_3Q5:bxrnlxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/ccl/testccl/sqlccl/tenant_gc_test.go#L135)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 	defer log.Scope(t).Close(t)
> 	gcjob.SetSmallMaxGCIntervalForTest()
> ```

nit: defer gcjob.SetSmall...
___
*[pkg/ccl/testccl/sqlccl/tenant_gc_test.go, line 146 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-MyhqOfX1tH1n911-QPK:-MyhqOfX1tH1n911-QPL:b1xmcr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/ccl/testccl/sqlccl/tenant_gc_test.go#L146)):*
> ```Go
> 	sqlDB := sqlutils.MakeSQLRunner(sqlDBRaw)
> 
> 	sqlDB.Exec(t, "SET CLUSTER SETTING kv.closed_timestamp.target_duration = '100ms'")
> ```

Why do we need this for this test?
___
*[pkg/ccl/testccl/sqlccl/tenant_gc_test.go, line 163 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-MyhtwfjAmiQlkZ91xoz:-MyhtwfjAmiQlkZ91xp-:b-v5kjtj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/ccl/testccl/sqlccl/tenant_gc_test.go#L163)):*
> ```Go
> 	}
> 
> 	checkGCBlockedByPTS := func(sj *jobs.StartableJob, tenID uint64) {
> ```

Let's pass in a `testing.T` in here considering this is called from more than 1 subtests?
___
*[pkg/ccl/testccl/sqlccl/tenant_gc_test.go, line 170 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-MyhpjmMBJ0v5QX89Sps:-MyhpjmMBJ0v5QX89Spt:b-lebn4j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/ccl/testccl/sqlccl/tenant_gc_test.go#L170)):*
> ```Go
> 			log.WithFlattenedSensitiveData)
> 		if err != nil {
> 			t.Fatal(err)
> ```

nit: can we just require.NoError?
___
*[pkg/ccl/testccl/sqlccl/tenant_gc_test.go, line 172 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-MyhrN9R9ZIPkmki3Esg:-MyhrN9R9ZIPkmki3Esh:b2gur7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/ccl/testccl/sqlccl/tenant_gc_test.go#L172)):*
> ```Go
> 			t.Fatal(err)
> 		}
> 		if len(entries) > 0 {
> ```

I may be missing something,  but shouldn't this be `len(entries) == 0`? Did you instead mean to wrap this reading from the log file and checking for pattern inside of a `SucceedsSoon` with a `len(entries)==0` check?
___
*[pkg/ccl/testccl/sqlccl/tenant_gc_test.go, line 263 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-MyhzcdD6MSubMPUfUQn:-MyhzcdD6MSubMPUfUQo:b9ftxck) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/ccl/testccl/sqlccl/tenant_gc_test.go#L263)):*
> ```Go
> 		sqlDB.Exec(t, "ALTER RANGE tenants CONFIGURE ZONE USING gc.ttlseconds = 1;")
> 
> 		ten, conn11 := serverutils.StartTenant(t, srv,
> ```

nit: should we call this con10 (referencing the tenant ID) instead?
___
*[pkg/ccl/testccl/sqlccl/tenant_gc_test.go, line 323 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-MyhyppKCLg6_LjjldvH:-MyhyppKCLg6_LjjldvI:b-c2ilt0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/ccl/testccl/sqlccl/tenant_gc_test.go#L323)):*
> ```Go
> // TestGCTenant is lightweight test that tests the branching logic in Resume
> // depending on if the job is GC for tenant or tables/indexes.
> func TestGCResumer(t *testing.T) {
> ```

Did this test need to move to this file? IIUC, it doesn't need to be in the CCL package, does it? If so, can we please move it back. 
___
*[pkg/ccl/testccl/sqlccl/tenant_gc_test.go, line 412 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-MyhydYM6olNWIMfVXVy:-MyhydYM6olNWIMfVXVz:b2zv52c) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/ccl/testccl/sqlccl/tenant_gc_test.go#L412)):*
> ```Go
> // TestGCTenant tests the `gcTenant` method responsible for clearing the
> // tenant's data.
> func TestGCTenant(t *testing.T) {
> ```

Should we move this test to the non-CCL package file? Separately, is this test buying us much?

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77726)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @arulajmani)

___
*[pkg/kv/kvserver/protectedts/ptutil/testutils.go, line 11 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-Mygo-lA0FFpBaLLvgNX:-MyjuU_P2Xo7i2iFsVsM:bqyis1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/kv/kvserver/protectedts/ptutil/testutils.go#L11)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Can we put this file in package `protectedts`? 
</blockquote></details>

There was a dependency cycle that motivated me to put this in its own package.
___
*[pkg/kv/kvserver/protectedts/ptutil/testutils.go, line 29 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-Mygnv25Cwm2D2cvJmCv:-Myk6SHdAFL2KOG_80xa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/kv/kvserver/protectedts/ptutil/testutils.go#L29)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

s/VerifyProtecteionTimestampExistsOnSpans/TestingVerifyProtectionTimestampExistsOnSpans/g
</blockquote></details>

Done.
___
*[pkg/sql/gcjob/refresh_statuses.go, line 342 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-MyglFSx5tPDSb6yPiJ_:-Myk7ZRkAm8cTH5OaadE:bk4xgjw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/sql/gcjob/refresh_statuses.go#L342)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Do we need to make this change that removes the fallback logic in this patch?
</blockquote></details>

good catch, this wasn't intended. Reverted the change.



_Code quote:_
```Go
log.Errorf(ctx, "zone config for tenants range: err = %+v", err)
```
___
*[pkg/ccl/testccl/sqlccl/tenant_gc_test.go, line 150 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-MykahHkAZsdoIIAtped:-MykahHkAZsdoIIAtpee:b5urwlh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/ccl/testccl/sqlccl/tenant_gc_test.go#L150)):*
> ```Go
> 	execCfg := srv.ExecutorConfig().(sql.ExecutorConfig)
> 	jobRegistry := execCfg.JobRegistry
> 	defer srv.Stopper().Stop(ctx)
> ```

doesn't this speed up the test by speeding up reconciliation?
___
*[pkg/ccl/testccl/sqlccl/tenant_gc_test.go, line 163 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-MyhtwfjAmiQlkZ91xoz:-MykA-KS9be8Plnu1yGv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/ccl/testccl/sqlccl/tenant_gc_test.go#L163)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Let's pass in a `testing.T` in here considering this is called from more than 1 subtests?
</blockquote></details>

Done.
___
*[pkg/ccl/testccl/sqlccl/tenant_gc_test.go, line 170 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-MyhpjmMBJ0v5QX89Sps:-Mykb-MG8ZClP395P25-:b-6qtsjk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/ccl/testccl/sqlccl/tenant_gc_test.go#L170)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: can we just require.NoError?
</blockquote></details>

Changed to a succeeds soon so returning an error instead
___
*[pkg/ccl/testccl/sqlccl/tenant_gc_test.go, line 172 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-MyhrN9R9ZIPkmki3Esg:-MykA0YgEWZH7EgkS_XD:bu05dnr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/ccl/testccl/sqlccl/tenant_gc_test.go#L172)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I may be missing something,  but shouldn't this be `len(entries) == 0`? Did you instead mean to wrap this reading from the log file and checking for pattern inside of a `SucceedsSoon` with a `len(entries)==0` check?
</blockquote></details>

Hmmm how did this happen, that's exactly what I thought I was doing lol. Fixed!
___
*[pkg/ccl/testccl/sqlccl/tenant_gc_test.go, line 263 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-MyhzcdD6MSubMPUfUQn:-MykABG0EJXV7Vhr5ino:b-krr3e7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/ccl/testccl/sqlccl/tenant_gc_test.go#L263)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: should we call this con10 (referencing the tenant ID) instead?
</blockquote></details>

Yup, got lost in the shuffle of tenant IDs. 
___
*[pkg/ccl/testccl/sqlccl/tenant_gc_test.go, line 323 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-MyhyppKCLg6_LjjldvH:-MykAEnI1rzm7cUacePv:b-7pcql8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/ccl/testccl/sqlccl/tenant_gc_test.go#L323)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Did this test need to move to this file? IIUC, it doesn't need to be in the CCL package, does it? If so, can we please move it back. 
</blockquote></details>

I found it slightly annoying that tests for GC tenant and job were all over the place, but yeah I agree this doesn't mean that it should lie in CCL. I've moved them to the gc_job_test.go file.
___
*[pkg/ccl/testccl/sqlccl/tenant_gc_test.go, line 412 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-MyhydYM6olNWIMfVXVy:-MykBygB8TrmDJ4aOXQ2:b-6chkc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/ccl/testccl/sqlccl/tenant_gc_test.go#L412)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should we move this test to the non-CCL package file? Separately, is this test buying us much?
</blockquote></details>

Moved to gc_job_test.go, I think it's a nice unit test for `gcTenant`. The other tests seem to be more to do with the GC job evaluating a tenant GC-ability.

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> Reviewed 16 of 16 files at r5, 16 of 16 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-:-MymbdP9BMcIHzMpr-ch:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @arulajmani)

___
*[pkg/kv/kvserver/protectedts/ptutil/testutils.go, line 11 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-Mygo-lA0FFpBaLLvgNX:-Mym_y8J5bIRkCg6zlr4:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/kv/kvserver/protectedts/ptutil/testutils.go#L11)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

There was a dependency cycle that motivated me to put this in its own package.
</blockquote></details>

Ack.
___
*[pkg/ccl/testccl/sqlccl/tenant_gc_test.go, line 150 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-MykahHkAZsdoIIAtped:-MymaSQv8ZqXgsIWiVCK:b-pcwjm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/ccl/testccl/sqlccl/tenant_gc_test.go#L150)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

doesn't this speed up the test by speeding up reconciliation?
</blockquote></details>

I don't think we're relying on reconciliation in this test, are we? 
___
*[pkg/ccl/testccl/sqlccl/tenant_gc_test.go, line 412 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-MyhydYM6olNWIMfVXVy:-MymbOoh84incd6SE4KD:b8wsrly) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/ccl/testccl/sqlccl/tenant_gc_test.go#L412)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

Moved to gc_job_test.go, I think it's a nice unit test for `gcTenant`. The other tests seem to be more to do with the GC job evaluating a tenant GC-ability.
</blockquote></details>

We can keep it if you like it! 
___
*[pkg/ccl/testccl/sqlccl/tenant_gc_test.go, line 169 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-Mymb9J70U5h0tcLhIu8:-Mymb9J70U5h0tcLhIu9:b-tdcj5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/abb2c7ac81d8027f9486d8970010d56b71897cff/pkg/ccl/testccl/sqlccl/tenant_gc_test.go#L169)):*
> ```Go
> 	checkGCBlockedByPTS := func(t *testing.T, sj *jobs.StartableJob, tenID uint64) {
> 		testutils.SucceedsSoon(t, func() error {
> 			log.Flush()
> ```

Should this `log.Flush` be outside the succeeds soon block?

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77726)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @arulajmani)

___
*[pkg/ccl/testccl/sqlccl/tenant_gc_test.go, line 150 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-MykahHkAZsdoIIAtped:-MymgxFkAvsi1dRwGMGS:btir3pk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/ccl/testccl/sqlccl/tenant_gc_test.go#L150)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I don't think we're relying on reconciliation in this test, are we? 
</blockquote></details>

The writing of pts records and the changes to range default GC TTL would be through reconciliation no?
___
*[pkg/ccl/testccl/sqlccl/tenant_gc_test.go, line 169 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-Mymb9J70U5h0tcLhIu8:-MymgUeh0GG9aBGGEVuB:b-6ol83r) ([raw file](https://github.com/cockroachdb/cockroach/blob/abb2c7ac81d8027f9486d8970010d56b71897cff/pkg/ccl/testccl/sqlccl/tenant_gc_test.go#L169)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should this `log.Flush` be outside the succeeds soon block?
</blockquote></details>

hmm the reason I had this inside the closure was that if we haven't seen a log entry in this iteration of the succeeds soon, then we want to flush all the logs to file and check again in the next iteration. `TestRotateCerts` also seems to do this but I'm not sure if this is wrong.

**Comment by adityamaru** [comment]
bors r=arulajmani

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77726)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @arulajmani)

___
*[pkg/ccl/testccl/sqlccl/tenant_gc_test.go, line 150 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-MykahHkAZsdoIIAtped:-MymxcAj0T7f0sLjKVaN:bu6cygu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6d123a7a387cbb7d136b1e05585eed8382d130c/pkg/ccl/testccl/sqlccl/tenant_gc_test.go#L150)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

The writing of pts records and the changes to range default GC TTL would be through reconciliation no?
</blockquote></details>

Yup, but the test doesn't read them from KV. 
___
*[pkg/ccl/testccl/sqlccl/tenant_gc_test.go, line 169 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77726#-Mymb9J70U5h0tcLhIu8:-MymxVz1AtxSRT5Lpl2f:bpw5zs4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4f862cfd3f8b8cad6d04e1999c472ee8b048eb9/pkg/ccl/testccl/sqlccl/tenant_gc_test.go#L169)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

hmm the reason I had this inside the closure was that if we haven't seen a log entry in this iteration of the succeeds soon, then we want to flush all the logs to file and check again in the next iteration. `TestRotateCerts` also seems to do this but I'm not sure if this is wrong.
</blockquote></details>

Never mind me, I was reading it as a "truncate" and not a flush. I think what you have is correct.

**Comment by adityamaru** [comment]
blathers backport 22.1

**Comment by adityamaru** [comment]
bors r=arulajmani

**Pull request merged**
