### PR TITLE
colexec: implement aggregate window functions in the vectorized engine

### LINKED ISSUE #37036: exec: support all aggregates as window functions in vectorized engine

### PR DESCRIPTION
**Pull request by DrewKimball**
**coldata: add Truncate method to Bytes**

Due to a limitation of the flat buffer implementation, `Set` cannot
be called on a `Bytes` columns at an index less than `maxSetLength`.
In such a case, `Set` will panic, rather than invalidating data beyond
the `Set` index. This behavior is intentional, to avoid the subtle bugs
that could result from misusing a version of `Set` that invalidated
following data, and the performance hit that would result from exactly
mimicking slice indexing behavior.

However, in some cases we really don't care about the data stored beyond
the `Set` index. For example, `SpillingQueue` copies input batches into
its own batches, which sets `maxSetLength` to the length of the batch for
`Bytes` columns. This will lead to panics if `Set` is called at any index
less than the length of the batch, which is problematic if a batch needs
to be partially written to, then stored in the queue, and then finished.

This patch adds a method `Truncate` to `Bytes` columns that sets `maxSetLength`
to the desired value, invalidating any data beyond the new length. This
allows for `Set` to be used even in cases where `maxSetLength` is changed.

Release note: None

**colexecagg: add window variants of optimized aggregate functions**

This commit adds variants of the aggregate functions supported by the
vectorized engine that can be executed in a window context.

Release note: None

**colexecagg: change aggregate function interface**

This commit modifies the `Compute` function of the aggregate function
interface to take a `startIdx` argument, which indicates the row starting
from which the aggregation should be computed. This will make it easier
for window functions to reuse the existing aggregate function logic.

Release note: None

**colexec: pull window function constructor fields into struct**

This commit pulls common fields that are used to construct window
function operators into a struct that is passed as an argument.
This simplifies the logic in `NewColOperator` that constructs
window functions.

Release note: None

**colexec: implement window aggregate functions**

This patch allows aggregate functions to be executed in a window
context - specifically, the aggregate functions that already have an
optimized implementation in the vectorized engine. This is accomplished
by reusing the existing aggregate function templates to generate `Window`
variants that can be used by `windowAggregator` operators to aggregate
over window frames. The window frames are calculated by `windowFramer`
operators that return a set of intervals `[startIdx, endIdx)` over which
the aggregate function should be evaluated for each row.

Note that this implementation uses the potentially quadratic approach
(depending on window frame) of aggregating over the entire window frame
for every row. For this reason, this commit may constitute a regression in 
performance for some queries. A future PR will implement the sliding-window 
optimization, which should make the vectorized implementation strictly better 
than the row-engine implementation.

Release note (sql change): common aggregate functions can now be executed
in the vectorized engine. This allows for better memory accounting and
faster execution in some cases.

**colexecwindow: add tests for window aggregate functions**

This commit adds the window aggregate functions that are supported
by the vectorized engine to the window function tests and benchmark.

Release note: None

Fixes #37036

### CODE REVIEW

**Comment by DrewKimball** [comment]
I've split this PR into separate commits for ease of reviewing. When it comes time to merge, I'll merge the last five commits into one.

**Review by yuzefovich — COMMENTED** [review]
Great stuff! Thanks for breaking it down - it was very easy to review! I only have some nits and a question about closers.

> Reviewed 10 of 10 files at r1, 28 of 28 files at r2, 38 of 38 files at r3, 19 of 19 files at r4, 5 of 6 files at r5, 6 of 6 files at r7, 5 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68081#-:-Mf_06Fn-wA1ERmyqlvJ:bqr6udf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[pkg/sql/colexec/colbuilder/execplan.go, line 1284 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68081#-MfZvd9R6PZhBzux2V8C:-MfZvd9R6PZhBzux2V8D:b-wwwj90) ([raw file](https://github.com/cockroachdb/cockroach/blob/1305175538be5d16b4c1d17305771423bedf9c22/pkg/sql/colexec/colbuilder/execplan.go#L1284)):*
> ```Go
> 					// we check if the returned operator is a Closer.
> 					if c, ok := result.Root.(colexecop.Closer); ok {
> 						result.ToClose = append(result.ToClose, c)
> ```

I just realized that we're probably forgetting to add buffered window operators to `ToClose`, no? At least I don't immediately see where this is done. Usually we check that all expected closers are actually closed as part of the unit test.
___
*[pkg/sql/colexec/colexecagg/aggregate_funcs.go, line 160 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68081#-MfZtL0CB7KrVDr2zA3q:-MfZtL0CB7KrVDr2zA3r:b-dmzg58) ([raw file](https://github.com/cockroachdb/cockroach/blob/3556b7d5761a6f6f24cc88ce702f31d026e2b035/pkg/sql/colexec/colexecagg/aggregate_funcs.go#L160)):*
> ```Go
> 
> func (h *unorderedAggregateFuncBase) CurrentOutputIndex() int {
> 	colexecerror.InternalError(errors.AssertionFailedf("CurrentOutputIndex called with hash aggregation"))
> ```

nit: `s/hash aggregation/unordered aggregation/`.
___
*[pkg/sql/colexec/colexecwindow/buffered_window.go, line 304 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68081#-MfZrj0H48io4kzmMj90:-MfZrj0I9ZHO_XFzFfbj:b-fkqp0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7480ccccac33c75cac8a90a49c932f90d678606/pkg/sql/colexec/colexecwindow/buffered_window.go#L304)):*
> ```Go
> 				// The spilling queue sets 'maxSetLength' to the length of the batch for
> 				// bytes-like types, so we have to reset it so that `Set` can be used.
> 				switch typeconv.TypeFamilyToCanonicalTypeFamily(b.outputColTyp.Family()) {
> ```

nit: we could store the canonical type family for the output vector. We also have `CanonicalTypeFamily` method on `coldata.Vec`.
___
*[pkg/sql/colexec/colexecwindow/window_aggregator.go, line 39 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/68081#-MfZxfoyAWOEM9ZMKL7_:-MfZxfoz6RGzpjmwpWu4:bnkti00) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4d2d0c048bf81cc67f7696d9443874b557b5938/pkg/sql/colexec/colexecwindow/window_aggregator.go#L39)):*
> ```Go
> ) colexecop.Operator {
> 	// Because the buffer is used multiple times per-row, it is important to
> 	// prevent it from spilling to disk of possible. For this reason, we give the
> ```

nit: `s/of possible/if possible/`.
___
*[pkg/sql/colexec/colexecwindow/window_functions_test.go, line 1299 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68081#-MfZzql3C4fTVlcoLZvB:-MfZzql3C4fTVlcoLZvC:b-u2rfxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b449503ab17c230f05e446b539f02010bd300d4/pkg/sql/colexec/colexecwindow/window_functions_test.go#L1299)):*
> ```Go
> 	}
> 
> 	for aggFnIdx := 0; aggFnIdx < len(execinfrapb.AggregatorSpec_Func_name); aggFnIdx++ {
> ```

nit: I think we need to +1 here because of this https://github.com/cockroachdb/cockroach/blob/b32885b5aecae4ad77d9f609495019d17fe00288/pkg/sql/distsql/columnar_operators_test.go#L123-L124.
___
*[pkg/sql/colexec/execgen/cmd/execgen/agg_gen_util.go, line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68081#-MfZucj33P9Zl931smgy:-MfZucj33P9Zl931smgz:b581dcn) ([raw file](https://github.com/cockroachdb/cockroach/blob/3556b7d5761a6f6f24cc88ce702f31d026e2b035/pkg/sql/colexec/execgen/cmd/execgen/agg_gen_util.go#L45)):*
> ```Go
> 		)
> 	}
> 	if genWindowVariant {
> ```

super nit: to me it seems that a slightly cleaner approach would be to define `aggKinds` local variable over which the loop above iterates and append to `aggKinds` the `windowAggKind` if `getWindowVariant` is `true`.
___
*[pkg/sql/distsql/columnar_operators_test.go, line 1083 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68081#-Mf_-FFs0W1_vH7UVuqH:-Mf_-FFs0W1_vH7UVuqI:bz5wbo1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b449503ab17c230f05e446b539f02010bd300d4/pkg/sql/distsql/columnar_operators_test.go#L1083)):*
> ```Go
> 	const manyRowsProbability = 0.05
> 	const fewRows = 10
> 	var manyRows = 2 * coldata.BatchSize()
> ```

nit: maybe randomize this a bit by adding `+rng.Intn(coldata.BatchSize())`.
___
*[pkg/sql/distsql/columnar_operators_test.go, line 1139 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68081#-Mf_-WX_Ed4OcEuETOST:-Mf_-WX_Ed4OcEuETOSU:bqh09rx) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b449503ab17c230f05e446b539f02010bd300d4/pkg/sql/distsql/columnar_operators_test.go#L1139)):*
> ```Go
> 
> 					if orderNonPartitionCols {
> 						// The outputs of this window function is not deterministic if there
> ```

nit: `s/outputs/output/`.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68081)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/colbuilder/execplan.go, line 1284 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68081#-MfZvd9R6PZhBzux2V8C:-Mf_8dmbCNImtGruyWlg:b-jb8s8v) ([raw file](https://github.com/cockroachdb/cockroach/blob/1305175538be5d16b4c1d17305771423bedf9c22/pkg/sql/colexec/colbuilder/execplan.go#L1284)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I just realized that we're probably forgetting to add buffered window operators to `ToClose`, no? At least I don't immediately see where this is done. Usually we check that all expected closers are actually closed as part of the unit test.
</blockquote></details>

Huh, that's a good catch. I'll just move that block down so that we always execute it.
___
*[pkg/sql/colexec/colexecagg/aggregate_funcs.go, line 160 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68081#-MfZtL0CB7KrVDr2zA3q:-Mf_94CVExH2Vx_Z5K6f:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3556b7d5761a6f6f24cc88ce702f31d026e2b035/pkg/sql/colexec/colexecagg/aggregate_funcs.go#L160)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `s/hash aggregation/unordered aggregation/`.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/colexecwindow/buffered_window.go, line 304 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68081#-MfZrj0H48io4kzmMj90:-Mf_9KKtCmLF_xXvQKgn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7480ccccac33c75cac8a90a49c932f90d678606/pkg/sql/colexec/colexecwindow/buffered_window.go#L304)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: we could store the canonical type family for the output vector. We also have `CanonicalTypeFamily` method on `coldata.Vec`.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/colexecwindow/window_aggregator.go, line 39 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/68081#-MfZxfoyAWOEM9ZMKL7_:-Mf_9TTs1CKe7UgHujJ1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4d2d0c048bf81cc67f7696d9443874b557b5938/pkg/sql/colexec/colexecwindow/window_aggregator.go#L39)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `s/of possible/if possible/`.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/colexecwindow/window_functions_test.go, line 1299 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68081#-MfZzql3C4fTVlcoLZvB:-Mf_9oloCQWH3J_Qf0Wn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b449503ab17c230f05e446b539f02010bd300d4/pkg/sql/colexec/colexecwindow/window_functions_test.go#L1299)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I think we need to +1 here because of this https://github.com/cockroachdb/cockroach/blob/b32885b5aecae4ad77d9f609495019d17fe00288/pkg/sql/distsql/columnar_operators_test.go#L123-L124.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/execgen/cmd/execgen/agg_gen_util.go, line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68081#-MfZucj33P9Zl931smgy:-Mf_ABrt0W_Re2Nl5LoC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3556b7d5761a6f6f24cc88ce702f31d026e2b035/pkg/sql/colexec/execgen/cmd/execgen/agg_gen_util.go#L45)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

super nit: to me it seems that a slightly cleaner approach would be to define `aggKinds` local variable over which the loop above iterates and append to `aggKinds` the `windowAggKind` if `getWindowVariant` is `true`.
</blockquote></details>

Done.
___
*[pkg/sql/distsql/columnar_operators_test.go, line 1083 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68081#-Mf_-FFs0W1_vH7UVuqH:-Mf_AOMS2ESo8vupPocS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b449503ab17c230f05e446b539f02010bd300d4/pkg/sql/distsql/columnar_operators_test.go#L1083)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: maybe randomize this a bit by adding `+rng.Intn(coldata.BatchSize())`.
</blockquote></details>

Done.
___
*[pkg/sql/distsql/columnar_operators_test.go, line 1139 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68081#-Mf_-WX_Ed4OcEuETOST:-Mf_ANwN4zl4zGU2Ao5s:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b449503ab17c230f05e446b539f02010bd300d4/pkg/sql/distsql/columnar_operators_test.go#L1139)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `s/outputs/output/`.
</blockquote></details>

Done.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 10 of 28 files at r11, 38 of 38 files at r12, 16 of 19 files at r13, 6 of 7 files at r14, 5 of 5 files at r15.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68081#-:-Mf_nIFU5WihgOysSBiw:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

**Comment by DrewKimball** [comment]
TFTR!

**Comment by DrewKimball** [comment]
Bazel failure looks unrelated to this PR, so I'm borsing now.

**Pull request merged**
