### PR TITLE
opt: Lay groundwork for decorrelation rules

### PR DESCRIPTION
**Pull request by andy-kimball**
The decorrelation rules require a number of supporting rules and
properties. This sequence of commits adds many of those prerequisites.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: 0 of 36 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/opt/memo/testdata/logprops/join, line 65 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25409#-LCE_QVw2Darps170pus:-LCEb4Qr00aomCbs9bHi:belfi0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/46a5d649b900fc958e9437ac2b3e0e7dd9b74a8f/pkg/sql/opt/memo/testdata/logprops/join#L65)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Shouldn't there be an error here? The `values` op is returning 2 rows while the `max1-row` op only accepts a single row.
</blockquote></details>

It would definitely end up being an error when we execute.. I'm not sure we want to spend too much effort detecting it at planning time since it's an error case (I think we would need to plumb errors through the factory)

---

*[pkg/sql/opt/norm/factory.go, line 588 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25409#-LCEZnnz7sNQ36_5lvZ3:-LCEZnnz7sNQ36_5lvZ4:b5jsom2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bf03ff70d7a73fad20a8c7ad55b261f2c8524f7/pkg/sql/opt/norm/factory.go#L588)):*
> ```Go
> // ----------------------------------------------------------------------
> 
> func (f *Factory) constructNonLeftJoin(
> ```

[nit] could use a function comment (same below), explaining we do this when we can prove that all rows on the left produce an output without the join being right/full

---

*[pkg/sql/opt/norm/rules/join.opt, line 101 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25409#-LCE_ELm2BjMJkiV1_15:-LCE_ELm2BjMJkiV1_16:bfr6413) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bf03ff70d7a73fad20a8c7ad55b261f2c8524f7/pkg/sql/opt/norm/rules/join.opt#L101)):*
> ```
> )
> 
> # SimplifyLeftJoin reduces a LeftJoin operator to an InnerJoin operator (or a
> ```

should mention that it's only for "cross joins" (no condition)

---

*[pkg/sql/opt/norm/rules/join.opt, line 119 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25409#-LCE_erI75Cs2YlFiWqI:-LCE_erI75Cs2YlFiWqJ:b-o7rnv9) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bf03ff70d7a73fad20a8c7ad55b261f2c8524f7/pkg/sql/opt/norm/rules/join.opt#L119)):*
> ```
> )
> 
> # SimplifyRightJoin reduces a RightJoin opeator to an InnerJoin operator (or a
> ```

ditto; also "operator"

---

*[pkg/sql/opt/norm/rules/join.opt, line 148 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25409#-LCE_pszDomRP_GX7lP6:-LCE_pszDomRP_GX7lP7:b2pt5yr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bf03ff70d7a73fad20a8c7ad55b261f2c8524f7/pkg/sql/opt/norm/rules/join.opt#L148)):*
> ```
> $left
> 
> # EliminateAntiJoin discards an AntiJoin operator when it's known that the left
> ```

the right input.

Here it doesn't matter if there's a filter condition, so we could generalize this to accept any filter.
We can also have a separate rule that does the same when the condition is `(False)`, regardless of the right input (not sure how useful it would be).

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25409)*

**Comment by RaduBerinde** [comment]
LGTM

**Comment by rytaft** [comment]
:lgtm_strong: 

---

Reviewed 12 of 20 files at r1, 24 of 24 files at r6, 7 of 7 files at r7, 6 of 6 files at r8, 5 of 5 files at r9, 11 of 11 files at r10.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25409#-:-LCG6_g68B8B59qyUm84:b-uwkowd)*

**Pull request merged**
