### PR TITLE
kv,storage,sql: purge snapshot isolation

### PR DESCRIPTION
**Pull request by benesch**
This touches a lot so I cast a wide net for reviewers. Feel free to remove yourself!

---

Snapshot isolation was disabled in v2.1, so it is safe to remove all
code paths that handle snapshot isolation in v2.2.

This is a necessary precursor to #32487.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
Mostly :lgtm: as long as we're sure that a 2.1 node will never perform SNAPSHOT transactions. If we can't be sure about that then I'm not confident that everything here is safe (for instance, removing the check for `RetryOnPush` during EndTxn evaluation).

It was a pretty easy review because all you're doing is deleting code. Definitely get others to weigh in as well, as I'm sure we all have a few special-cases we remember adding to deal with SNAPSHOT isolation that may not have been picked up here.

Out of curiosity, did you look at every single use of `enginepb.SERIALIZABLE`

> Reviewed 33 of 33 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32860#-:-LT0vHdF-HBPCQLvsphv:b-z6q0ud)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/roachpb/data.go, line 732 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32860#-LT0wx7r9BbsyE62-hxb:-LT0wx7r9BbsyE62-hxc:b-aq9j0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94f47c10697a28df1702a1b5f5f5ed7d7364237/pkg/roachpb/data.go#L732)):*
> ```Go
> 	baseKey Key,
> 	userPriority UserPriority,
> 	isolation enginepb.IsolationType,
> ```

Should we remove this argument?
___
*[pkg/roachpb/data.proto, line 384 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32860#-LT0wfUfEHWNqHn3VEpD:-LT0wfUfEHWNqHn3VEpE:b-hys9yb) ([raw file](https://github.com/cockroachdb/cockroach/blob/91e1d7b3450519eb2d67b838c3639ab074789b20/pkg/roachpb/data.proto#L384)):*
> ```protobuf
>   // prevent the LostDeleteRange anomaly. This flag is relevant only
>   // for SNAPSHOT transactions.
>   bool retry_on_push = 13;
> ```

`reserved`
___
*[pkg/storage/batcheval/cmd_end_transaction.go, line 390 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32860#-LT0vzi3DnOFx6LQ_KEY:-LT0vzi4038JYWQoSUPI:bng1dhf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94f47c10697a28df1702a1b5f5f5ed7d7364237/pkg/storage/batcheval/cmd_end_transaction.go#L390)):*
> ```Go
> 		// timestamp.
> 		if isTxnPushed {
> 			if txn.Isolation == enginepb.SERIALIZABLE {
> ```

Do we want to assume that all transactions are `SERIALIZABLE` now? Is the plan to remove conditions like this?

**Review by bdarnell — APPROVED** [review]
:tada: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32860#-:-LT3EsG73ScwS5YaYsO9:bjwa7hh)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/kv/txn_correctness_test.go, line 1034 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32860#-LT3EMIv4moWx1PEAglw:-LT3EMIv4moWx1PEAglx:bvi6mjx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94f47c10697a28df1702a1b5f5f5ed7d7364237/pkg/kv/txn_correctness_test.go#L1034)):*
> ```Go
> }
> 
> // TestTxnDBWriteSkewAnomaly verifies that SI suffers from the write
> ```

This comment needs an update. 
___
*[pkg/storage/batcheval/cmd_end_transaction.go, line 390 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32860#-LT0vzi3DnOFx6LQ_KEY:-LT3EpjDCHi3cpXP7tGn:b-q0lk1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94f47c10697a28df1702a1b5f5f5ed7d7364237/pkg/storage/batcheval/cmd_end_transaction.go#L390)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we want to assume that all transactions are `SERIALIZABLE` now? Is the plan to remove conditions like this?
</blockquote></details>

Yes, I think so.

**Review by andreimatei — APPROVED** [review]
🎉 LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32860#-:-LT3I-73ElKUvGzGZfRg:b-47lbqw)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/roachpb/data.proto, line 384 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32860#-LT0wfUfEHWNqHn3VEpD:-LT3IMyRDEsspuJg5dFZ:b-1wwk5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/91e1d7b3450519eb2d67b838c3639ab074789b20/pkg/roachpb/data.proto#L384)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`reserved`
</blockquote></details>

so glad to see this one gone
___
*[pkg/roachpb/errors.proto, line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32860#-LT3IR1j5GkJv2fozdKJ:-LT3IR1j5GkJv2fozdKK:b-544ov5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94f47c10697a28df1702a1b5f5f5ed7d7364237/pkg/roachpb/errors.proto#L203)):*
> ```protobuf
>   // A concurrent writer finished first, causing restart.
>   RETRY_WRITE_TOO_OLD = 1;
>   reserved 2;
> ```

I think we usually put these at the top ?
___
*[pkg/sql/conn_executor.go, line 1681 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32860#-LT3IYY72FBCQZE7ULK8:-LT3IYY72FBCQZE7ULK9:bts7bh3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94f47c10697a28df1702a1b5f5f5ed7d7364237/pkg/sql/conn_executor.go#L1681)):*
> ```Go
> 		}
> 	}
> 	if modes.Isolation != tree.UnspecifiedIsolation && modes.Isolation != tree.SerializableIsolation {
> ```

can't `tree.SerializableIsolation` go away? (and maybe the whole enum)
___
*[pkg/storage/engine/enginepb/mvcc3.proto, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32860#-LT3Ij3ODV_BKjIN2-Zi:-LT3Ij3ODV_BKjIN2-Zj:blaknir) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94f47c10697a28df1702a1b5f5f5ed7d7364237/pkg/storage/engine/enginepb/mvcc3.proto#L23)):*
> ```protobuf
> // TODO(tschottdorf): Should not live in enginepb (but can't live in roachpb
> // either).
> enum IsolationType {
> ```

can't this go away?

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32860)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/kv/txn_correctness_test.go, line 1034 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32860#-LT3EMIv4moWx1PEAglw:-LT4E67C4OaA5Ub_YYER:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94f47c10697a28df1702a1b5f5f5ed7d7364237/pkg/kv/txn_correctness_test.go#L1034)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This comment needs an update. 
</blockquote></details>

Done.
___
*[pkg/roachpb/data.go, line 732 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32860#-LT0wx7r9BbsyE62-hxb:-LT4E4UXEUy8JTHbBYwr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94f47c10697a28df1702a1b5f5f5ed7d7364237/pkg/roachpb/data.go#L732)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we remove this argument?
</blockquote></details>

Done.
___
*[pkg/roachpb/data.proto, line 384 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32860#-LT0wfUfEHWNqHn3VEpD:-LT4E1Aw86mzcHIkIFFk:b-spz0wu) ([raw file](https://github.com/cockroachdb/cockroach/blob/91e1d7b3450519eb2d67b838c3639ab074789b20/pkg/roachpb/data.proto#L384)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

so glad to see this one gone
</blockquote></details>

Yikes, good catch, Nathan. Done.
___
*[pkg/roachpb/errors.proto, line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32860#-LT3IR1j5GkJv2fozdKJ:-LT4DtxR9WWSzv-cBBp5:bho90dm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94f47c10697a28df1702a1b5f5f5ed7d7364237/pkg/roachpb/errors.proto#L203)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think we usually put these at the top ?
</blockquote></details>

We do it both ways, it appears. It seems leaving them inline is slightly more common than putting them at the top, so I'm going to leave as is, though I'll note that I didn't do the most thorough check.
___
*[pkg/sql/conn_executor.go, line 1681 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32860#-LT3IYY72FBCQZE7ULK8:-LT4Egoc4VFXr56MBGqS:b6hncgv) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94f47c10697a28df1702a1b5f5f5ed7d7364237/pkg/sql/conn_executor.go#L1681)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can't `tree.SerializableIsolation` go away? (and maybe the whole enum)
</blockquote></details>

In theory, but it changes the roundtripping of `SET TRANSACTION ISOLATION LEVEL` statements, so I'd like to leave it to another PR where it can be properly bikeshedded.
___
*[pkg/storage/batcheval/cmd_end_transaction.go, line 390 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32860#-LT0vzi3DnOFx6LQ_KEY:-LT4Don312k3gIBbPXlI:b-x3vd36) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94f47c10697a28df1702a1b5f5f5ed7d7364237/pkg/storage/batcheval/cmd_end_transaction.go#L390)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Yes, I think so. 
</blockquote></details>

Done, here and elsewhere.
___
*[pkg/storage/engine/enginepb/mvcc3.proto, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32860#-LT3Ij3ODV_BKjIN2-Zi:-LT4DkMu1CDjHEKNAh1u:b-9f087b) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94f47c10697a28df1702a1b5f5f5ed7d7364237/pkg/storage/engine/enginepb/mvcc3.proto#L23)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can't this go away?
</blockquote></details>

Yep, done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 49 of 49 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32860#-:-LT4Ju8sBz7GJTXvs_4s:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/roachpb/data.go, line 732 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32860#-LT0wx7r9BbsyE62-hxb:-LT4JP1S6giZh5d37V16:bi9estx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94f47c10697a28df1702a1b5f5f5ed7d7364237/pkg/roachpb/data.go#L732)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:pray:

**Comment by benesch** [comment]
bors r=andreimatei,nvanbenschoten,bdarnell

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32860)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/conn_executor.go, line 1681 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32860#-LT3IYY72FBCQZE7ULK8:-LT8mHXv5nc_L5gMF0eF:b3zou61) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94f47c10697a28df1702a1b5f5f5ed7d7364237/pkg/sql/conn_executor.go#L1681)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

In theory, but it changes the roundtripping of `SET TRANSACTION ISOLATION LEVEL` statements, so I'd like to leave it to another PR where it can be properly bikeshedded.
</blockquote></details>

Do other isolation levels round trip? If not, I say burn it.

**Pull request merged**
