### PR TITLE
cli: avoid special line at the end of CSV/TSV output

### LINKED ISSUE #18584: cli: improve the csv/tsv output (and sql results in general)
Previously the csv/tsv output would output the total row count at the beginning, now it does at the end.

@bdarnell suggests: having the row count at the end makes parsing difficult. Do we really need it?

Initially I thought that the row count was useful at least for humans so that a csv/tsv output on the screen can be easily sized (humans are not good at counting manually). So Ben suggested we only display the row count when interactive, which is indeed a simple change.

However after thinking this some more I realized that we have another need: when a client issues multiple queries one after another, we also need a *delimiter* to separate result batches. This is especially true for csv/tsv where otherwise there would be no delimiter and no way to distinguish the column header of a new result batch from an extra row in the previous batch.

That said, the row count is not a very good delimiter either -- it is a variable string and thus difficult to match.

So instead I propose to do the following:
- make the row count only appear on interactive shells by default (perhaps with an option to hide/show it)
- add two new options "footer" and "header", with footer set to "--" by default, to be printed before and after result batches

@bdarnell would this be adequate?

### PR DESCRIPTION
**Pull request by knz**
Fixes #18584.

Prior to this patch, the csv/tsv formatters would end a table with a
row count. This is not great for interoperability with external tools
which may expect to be able to redirect the table output to a file and
open that directly in a csv/tsv reader, where the final row count
would be incorrectly interpreted as an extra row.

This patch changes the behavior by omitting the row count altogether
for csv/tsv output.

Release note (cli change): when printing tabular results as CSV or
TSV, no final row count is emitted. This is intended to increase
interoperability with external tools.

### CODE REVIEW

**Comment by jordanlewis** [comment]
Oo, can you include an example of the before/after for the end-user in the PR?

**Comment by bdarnell** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cli/flags.go, line 369 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/20835#-L0fPPU8Ghj0Fur9PMll:-L0fPPU9NXI_NBrKyWui:bmp5h5d) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b1342d5e2a5cb547912128aa9ed6051539dd3ee/pkg/cli/flags.go#L369)):*
> ```Go
> 		f := cmd.Flags()
> 		VarFlag(f, &cliCtx.tableDisplayFormat, cliflags.TableDisplayFormat)
> 		BoolFlag(f, &cliCtx.displayRowCounts, cliflags.DisplayRowCounts, cliCtx.displayRowCounts)
> ```

In my mind the row count is a part of the `pretty` format and not something that can be toggled on/off independently. This knob and the associated implementation of row counts for every format seem like unnecessary complexity to me. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20835)*

**Comment by knz** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cli/flags.go, line 369 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/20835#-L0fPPU8Ghj0Fur9PMll:-L0faiW8-wxgal2xkwRO:b-isnimv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b1342d5e2a5cb547912128aa9ed6051539dd3ee/pkg/cli/flags.go#L369)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

In my mind the row count is a part of the `pretty` format and not something that can be toggled on/off independently. This knob and the associated implementation of row counts for every format seem like unnecessary complexity to me. 
</blockquote></details>

I started making it configurable for csv/tsv (there are legitimate cases where we want a row count for them) and then I wasn't happy with having it configurable form csv/tsv. In particular it became clear that at least the html and records formatters should also have it. But then for orthogonality in docs I figured that it should be the same everywhere so the explanation remains simple. What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20835)*

**Comment by bdarnell** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cli/flags.go, line 369 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/20835#-L0fPPU8Ghj0Fur9PMll:-L0fgRycj4u8uMlBvDfR:b-ivwwc5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b1342d5e2a5cb547912128aa9ed6051539dd3ee/pkg/cli/flags.go#L369)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I started making it configurable for csv/tsv (there are legitimate cases where we want a row count for them) and then I wasn't happy with having it configurable form csv/tsv. In particular it became clear that at least the html and records formatters should also have it. But then for orthogonality in docs I figured that it should be the same everywhere so the explanation remains simple. What do you think?
</blockquote></details>

What is that use case? The reason I was thinking it was format-specific was because I couldn't think of any time you'd want anything but CSV/TSV data when using those formats.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20835)*

**Comment by knz** [comment]
I have removed all commits but the last and simplified the implementation. PTAL.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/cli/flags.go, line 369 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/20835#-L0fPPU8Ghj0Fur9PMll:-L4M3P9T9RskHU_3ts-1:bpkfx6g) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b1342d5e2a5cb547912128aa9ed6051539dd3ee/pkg/cli/flags.go#L369)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

What is that use case? The reason I was thinking it was format-specific was because I couldn't think of any time you'd want anything but CSV/TSV data when using those formats.
</blockquote></details>

Okay, removed, PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20835#-:-L4M3RCpW13MUwT7O03I:b-5zoffa)*

**Comment by bdarnell** [comment]
Reviewed 9 of 9 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/cli/format_table.go, line 289 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/20835#-L4Y_TPMXyEdkpsq2xqT:-L4Y_TPMXyEdkpsq2xqU:b4xsw0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b4da8c94c5549d48735037c3e0887117c656d50/pkg/cli/format_table.go#L289)):*
> ```Go
> func (p *csvReporter) doneRows(w io.Writer, seenRows int) error {
> 	p.csvWriter.Flush()
> 	// Ensure that there is a separator, in case multiple csv/tsv tables
> ```

Even a blank line can make things more complicated for readers. For example, python's `csv.reader` will return an empty list for the blank line, so reading code needs to explicitly handle it. We shouldn't add a blank line in the common case of a single query. If we want a separator, we should only use it when there are multiple queries. But even then I don't think it's worth the effort - executing multiple queries in a single CLI invocation and using CSV output seems like a very unusual workflow. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20835)*

**Comment by knz** [comment]
Removed the empty line as suggested. PTAL

**Review by bdarnell — APPROVED** [review]

**Comment by knz** [comment]
TFYR!

**Pull request merged**
