### PR TITLE
sqlbase: add a TypeDescriptor proto message

### PR DESCRIPTION
**Pull request by rohany**
This PR adds a protobuf descriptor that represents
a user defined type.

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm: though take care to add a cluster version and gate writing of these things behind it before you add any code that writes one of these. 

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48111#-:-M66NJGlEWLwSowkX6-G:bbbtm9y)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lucy-zhang)

**Comment by rohany** [comment]
Good catch -- I'll make sure to add one in https://github.com/cockroachdb/cockroach/pull/48086/

**Review by thoszhang — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48111)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rohany)

___
*[pkg/sql/sqlbase/structured.proto, line 1011 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48111#-M66Obob7VclogMCjs3M:-M66Obob7VclogMCjs3N:b-gkfp6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/74bfe030ff20554efdc15df8e261bc41c8db44f8/pkg/sql/sqlbase/structured.proto#L1011)):*
> ```protobuf
>   // TODO (rohany): Leaving this empty until we actually store enum values.
> 
>   // TODO (rohany): Do we need a draining names like the table descriptor?
> ```

Yeah, I think we can just repurpose `TableDescriptor_NameInfo` for types (and even probably for databases and schemas eventually, since I think the only point of that struct is to refer to a single namespace entry). There is still the question of whether we want to extract draining names to the separate lease metadata column. Either way, we can just merge as-is and do that as a follow-up.

**Comment by rohany** [comment]
TFTRs!

bors r+

**Pull request merged**
