### PR TITLE
cdc/jobs: use changefeed jobs internal table for SHOW CHANGEFEED JOBS

### LINKED ISSUE #92261: changefeedccl: remove dependency on system.jobs table for SHOW CHANGEFEED JOBS
Currently, `SHOW CHANGEFEED JOBS` reads from the `system.jobs` table. This causes the statement to fail if a non-admin user executes it. To fix this, we can use a virtual table like `crdb_internal.jobs` instead. Note that all the necessary columns do not exist in `crdb_internal.jobs`, so we may have to create a new virtual table or modify an existing one.

### PR DESCRIPTION
**Pull request by jayshrivastava**
#### cdc/jobs: use changefeed jobs internal table for SHOW CHANGEFEED JOBS
Previously, the `SHOW CHANGEFEED JOBS` statement directly used the
`system.jobs` table. This made it difficult to implement fine grained
permissions for changefeeds since querying the `system.jobs` table requires
users to be admins.

This change adds a new virtual table, `crdb_internal.kv_changefeed_jobs_details`,
which filters each row based on the user's privileges. This change updates
`SHOW CHANGEFEED JOBS` to use this table.

Closes: https://github.com/cockroachdb/cockroach/issues/92261

Release note: Non-admin users can now execute `SHOW CHANGEFEED JOBS` to view
changefeed jobs.
Epic: None

### CODE REVIEW

**Comment by miretskiy** [comment]
> This change adds a new virtual table, crdb_internal.kv_changefeed_jobs_details,
which filters each row based on the user's privileges. This change updates
SHOW CHANGEFEED JOBS to use this table.

I understand that querying system.jobs  is not ideal, and that's the reasons for this PR.
I don't understand however, why we need to introduce a new internal table at all?
Why can't we just query crdb_internal.jobs instead?

**Comment by jayshrivastava** [comment]
> > This change adds a new virtual table, crdb_internal.kv_changefeed_jobs_details,
> > which filters each row based on the user's privileges. This change updates
> > SHOW CHANGEFEED JOBS to use this table.
> 
> I understand that querying system.jobs is not ideal, and that's the reasons for this PR. I don't understand however, why we need to introduce a new internal table at all? Why can't we just query crdb_internal.jobs instead?

I figured it would be a bit more organized to not include changefeed specific columns in `crdb_internal.jobs`. Although, adding just one column, `changefeed_details`, isn't that bad: 
```
crdb_internal.pb_to_json(
'cockroach.sql.jobs.jobspb.Payload',
payload, false, true
)->'changefeed' AS changefeed_details
```
Notably, I the `SHOW CHANGEFEED JOBS` query leverages a hash join between the two virtual tables, so I don't think my approach is much less efficient or anything.
```
              │   └── • hash join
              │       │ equality: (job_id) = (job_id)
              │       │
              │       ├── • virtual table
              │       │     table: kv_changefeed_jobs_details@primary
              │       │
              │       └── • filter
              │           │ filter: (finished IS NULL) OR (finished > '2022-11-29 03:54:20.662581')
              │           │
              │           └── • virtual table
              │                 table: jobs@primary
```

**Comment by miretskiy** [comment]
> I figured it would be a bit more organized to not include changefeed specific columns in `crdb_internal.jobs`. Although, adding just one column, `changefeed_details`, isn't that bad:

Why do we need to add that? Doesn't the system contain all of the required data already?

**Comment by jayshrivastava** [comment]
> Why do we need to add that? Doesn't the system contain all of the required data already?  

`crdb_internal.jobs` does not have the data we need, so we need to make it available. `system.jobs` has the info we need, but we can't have `SHOW CHANGEFEED JOBS` query `system.jobs` as it does now.

**Comment by miretskiy** [comment]
I maybe wrong here -- so, please forgive if I am.  Maybe we should sink up offline.
At any rate, reading the issue this PR is trying to solve, it appears to me that the problem is a 
bit more generic than just being changefeed specific (we can imagine having show backup jobs, or whatnot in the future).

I kinda liked the delegate approach show changefeed jobs took; and I think it's a better approach vs showing everything
into crdb_internal.jobs
At the same time, I don't like adding a changefeed specific crdb_internal table.
What we want is a meld between crdb_internal.jobs -- namely, the functionality around restricting result set only to the
jobs that the user has permissions to view, and raw system.jobs so that callers can do what they please with the results.

So, I'm thinking of something like `crdb_internal.role_jobs` (or something similar to convey the fact that this is a table with records filtered based on the role); perform the checks doen by crdb_internal.jobs (wrt to admin/role permissions) and return filtered results.  We should also be able to add job type specific checks -- e.g. look at payload, and based on payload type (e.g. changefeed, backup, etc) require type specific permission (e..g controlchangefeed).

Yet another approach is to forego current delegate based implementation and just implement full node to show changefeed jobs (though, again, this probably would not scale well to the other types of "show" commands)

**Comment by jayshrivastava** [comment]
Closing in favor of https://github.com/cockroachdb/cockroach/pull/94796

**Pull request closed without merging**
