### PR TITLE
opt: follow-up to #27351

### PR DESCRIPTION
**Pull request by RaduBerinde**
Release note: None

### CODE REVIEW

**Review by andy-kimball — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27453#-:-LHJY81o-Lx5TTa7_Ujc:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by rytaft — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27453)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/props/ordering_choice.go, line 290 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27453#-LHJZtYA1JpuKzmGLu_I:-LHJZtYA1JpuKzmGLu_J:b-rfegdj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e36b5a9908ec6c38e9784ef5d923ef3474e40778/pkg/sql/opt/props/ordering_choice.go#L290)):*
> ```Go
> //   +1,-(2|3) opt(4,5)
> //
> // then CanProject will behave as follows for these input sets:
> ```

CanProject -> CanProjectCols

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27453)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/props/ordering_choice.go, line 290 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27453#-LHJZtYA1JpuKzmGLu_I:-LHJbiMK6gfbDHMnL0qE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e36b5a9908ec6c38e9784ef5d923ef3474e40778/pkg/sql/opt/props/ordering_choice.go#L290)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

CanProject -> CanProjectCols
</blockquote></details>

Done.

**Comment by knz** [comment]
I find the commit message a bit short :smirk_cat:

**Pull request merged**
