### PR TITLE
kv: more improvements to range cache using generation

### PR DESCRIPTION
**Pull request by jeffrey-xiao**
Adds the generation to the request lookup key when coalescing requests to decrease the number of lookups in the rare double split case.

Additionally, use the generation when evicting a stale descriptor. Doing a pointer comparison is not the best way of determining if the descriptor exists in the cache. We can use the generation instead if it
comparable.

Release note: None

I used the roachtests in #38792 to measure the number of range lookups before and after this change and there doesn't seem to be a statistically significant diff. I also added a temporary metric to see how often the double split case happens by checking how often this error was returned: https://github.com/cockroachdb/cockroach/blob/dae43101d05d6247dfb9c74f645213329246afa8/pkg/kv/range_cache.go#L412-L413

The case did not appear in `kv50/rangelookups/split/nodes=8/workers=2`.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38819)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jeffrey-xiao, and @nvanbenschoten)

___
*[pkg/kv/range_cache.go, line 491 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38819#-LjY5W3ICaONUePfD40B:-LjY5W3ICaONUePfD40C:b-rfed0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/d49712fb8ca1f4cb169c1e1780288daa73681478/pkg/kv/range_cache.go#L491)):*
> ```
> only if it equals the cached range descriptor as a pointer.
> ```

This comment is now stale.
___
*[pkg/kv/range_cache.go, line 504 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38819#-LjY5jJI42DLQjW2itqb:-LjY5jJI42DLQjW2itqc:b347q6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/d49712fb8ca1f4cb169c1e1780288daa73681478/pkg/kv/range_cache.go#L504)):*
> ```Go
> 			}
> 		} else {
> 			// One descriptor's generation is comparable, while the other is
> ```

We can fold this into the first case by making the condition `if seenDesc.GetGenerationComparable() || cachedDesc.GetGenerationComparable() { ... } else { ... }` , right?

**Comment by jeffrey-xiao** [comment]
___
*[pkg/kv/range_cache.go, line 504 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38819#-LjY5jJI42DLQjW2itqb:-Ljad0jn4gWrqUVeh5LT:bmfqxyz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d49712fb8ca1f4cb169c1e1780288daa73681478/pkg/kv/range_cache.go#L504)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We can fold this into the first case by making the condition `if seenDesc.GetGenerationComparable() || cachedDesc.GetGenerationComparable() { ... } else { ... }` , right?
</blockquote></details>

If by folding the else into the first case, you mean:
```
if seenDesc.GetGenerationComparable() || cachedDesc.GetGenerationComparable() {
	if seenDesc.GetGeneration() != cachedDesc.GetGeneration() {
		return nil
	}
} else if !seenDesc.GetGenerationComparable() && !cachedDesc.GetGenerationComparable() {
	if seenDesc != cachedDesc {
		return nil
	}
}
```

Isn't it possible for one range descriptor's generation to be incomparable and another is comparable, but their generations are equal? E.G.

1) 19.2 node splits a range and marks both sides as comparable
2) lease on RHS transfers to 19.1 node
3) 19.1 performs a change replicas on RHS and generation is the same, but the range descriptors are different

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38819)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @jeffrey-xiao)

___
*[pkg/kv/range_cache.go, line 504 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38819#-LjY5jJI42DLQjW2itqb:-Ljbu3ApD0rGMkGEKzec:bw8t1m9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d49712fb8ca1f4cb169c1e1780288daa73681478/pkg/kv/range_cache.go#L504)):*
<details><summary><i>Previously, jeffrey-xiao (Jeffrey Xiao) wrote…</i></summary><blockquote>

If by folding the else into the first case, you mean:
```
if seenDesc.GetGenerationComparable() || cachedDesc.GetGenerationComparable() {
	if seenDesc.GetGeneration() != cachedDesc.GetGeneration() {
		return nil
	}
} else if !seenDesc.GetGenerationComparable() && !cachedDesc.GetGenerationComparable() {
	if seenDesc != cachedDesc {
		return nil
	}
}
```

Isn't it possible for one range descriptor's generation to be incomparable and another is comparable, but their generations are equal? E.G.

1) 19.2 node splits a range and marks both sides as comparable
2) lease on RHS transfers to 19.1 node
3) 19.1 performs a change replicas on RHS and generation is the same, but the range descriptors are different 
</blockquote></details>

You're right, good point.

**Review by nvb — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38819)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38819#-:-Ljuq4yk7qJJkIT6GP4_:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by jeffrey-xiao** [comment]
TFTRs!

bors r+

**Pull request merged**
