### PR TITLE
*: Remove cryptopp from c-deps, stop building it

### PR DESCRIPTION
**Pull request by itsbilal**
libcryptopp was only used for RocksDB encryption-at-rest. Now
that RocksDB is deleted (#55509), we can remove libcryptopp too.

Release note: None.

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55858#-:-MKFlvOl60swc2inLhz9:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens, @otan, and @petermattis)

**Review by petermattis — APPROVED** [review]

**Comment by jordanlewis** [comment]
This is like CockroachDB Christmas!

**Comment by otan** [comment]
In time for Halloween, we can dress up as the ghost of RocksDB

**Comment by itsbilal** [comment]
TFTR! 🎃 

bors r=petermattis

**Pull request merged**
