### PR TITLE
 base: include Spec in TempStorageConfig's created in tests

### LINKED ISSUE #114210: sql/catalog/tabledesc: TestRemoveDefaultExprFromComputedColumn failed [timed out while starting tenant]
sql/catalog/tabledesc.TestRemoveDefaultExprFromComputedColumn [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/12603206?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/12603206?buildTab=artifacts#/) on master @ [d3f1f25c822bdb282d250834cae1f7b3475142d7](https://github.com/cockroachdb/cockroach/commits/d3f1f25c822bdb282d250834cae1f7b3475142d7):

Fatal error:

```
panic: test timed out after 57s
running tests:
	TestRemoveDefaultExprFromComputedColumn (6s)

```
Stack: 

```
goroutine 30130 [running]:
testing.(*M).startAlarm.func1()
	GOROOT/src/testing/testing.go:2259 +0x320
created by time.goFunc
	GOROOT/src/time/sleep.go:176 +0x38
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestRemoveDefaultExprFromComputedColumn
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/7b4578e3c0124849ee4088d817d512f1/logTestRemoveDefaultExprFromComputedColumn3327043814
    test_log_scope.go:81: use -show-logs to present logs inline
    test_server_shim.go:159: automatically injected a shared process virtual cluster under test; see comment at top of test_server_shim.go for details.
```
</p>
</details>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRemoveDefaultExprFromComputedColumn.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-33394

### LINKED ISSUE #114253: sql/row: TestRowFetcherReset failed (shared-process MT slow to start up)
sql/row.TestRowFetcherReset [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/12615335?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/12615335?buildTab=artifacts#/) on master @ [9a3b101687f99ceb94cc9ac9d0e2f18033473f52](https://github.com/cockroachdb/cockroach/commits/9a3b101687f99ceb94cc9ac9d0e2f18033473f52):

Fatal error:

```
panic: test timed out after 57s
running tests:
	TestRowFetcherReset (5s)

```
Stack: 

```
goroutine 37161 [running]:
testing.(*M).startAlarm.func1()
	GOROOT/src/testing/testing.go:2259 +0x320
created by time.goFunc
	GOROOT/src/time/sleep.go:176 +0x38
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestRowFetcherReset
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/9db56821b86748e0fc537f3d515778f0/logTestRowFetcherReset1362446101
    test_log_scope.go:81: use -show-logs to present logs inline
    test_server_shim.go:159: automatically injected a shared process virtual cluster under test; see comment at top of test_server_shim.go for details.
```
</p>
</details>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRowFetcherReset.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-33421

### PR DESCRIPTION
**Pull request by stevendanna**
For shared-process virtual clusters, the spec is later used to
 determine whether the temp engine should be in-memory or
 not. Previously, by not setting this field, shared-process SQL servers
 were always started with on-disk temporary storage during tests.
    
 I believe this is the cause of at least some of the slowness we've
 seen during server startup and shutdown in CI.
    
 This likely isn't a complete story (other sources of slowness include
 the time it takes to run permanent migrations and the KV-side rate
 limiter), but stack traces related to this temporary directory have
 been seen in the 4 most recent timeouts I've investigated.
    
 Fixes #114210
 Fixes #114253
    
 Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
I have some questions, perhaps I'm missing something though.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115246#-:-NkSDITGCK3qfqac55N4:b5w7de2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115246#-NkSCgLc4Cn8T2lsMfN_):*
Hm, I'm a bit confused here. What are the places you're referring to where we set `TempStorageConfig.InMemory`? It seems like most tests simply inherit `DefaultTestStoreSpec` which has `InMemory = true`.
___
*[`pkg/server/server_controller_new_server.go` line 322 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115246#-NkSCxu6E9FVcF6pJmwK:-NkSCxu6E9FVcF6pJmwL:b-4onm0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc56537b3ff050143baad96a961312ff9b46c0f9/pkg/server/server_controller_new_server.go#L322)):*
> ```Go
> 
> 	tempStorageCfg := base.TempStorageConfigFromKVConfig(ctx, st, kvServerCfg.SQLConfig.TempStorageConfig)
> 	if !tempStorageCfg.InMemory {
> ```

I wonder whether it's not that `InMemory` boolean wasn't properly set, rather the fact that with this patch we no longer create a temp directory? Namely, previously, even if `tempStorageCfg.InMemory` was correctly set to `true`, we still proceeded to `fs.CreateTempDir` call.

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115246)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115246#-NkSCgLc4Cn8T2lsMfN_):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, I'm a bit confused here. What are the places you're referring to where we set `TempStorageConfig.InMemory`? It seems like most tests simply inherit `DefaultTestStoreSpec` which has `InMemory = true`.
</blockquote></details>

The code is a mess, so it is possible I'm the confused one. But, over in makeTestServerConfig  we have

```golang
func makeTestSQLConfig(st *cluster.Settings, tenID roachpb.TenantID) SQLConfig {
	return MakeSQLConfig(tenID, base.DefaultTestTempStorageConfig(st))
}
```

Where `DefaultTestTempStorageConfig(st)`  creates a TempStorageConfig with an empty store spec (where InMemory is `false`):

```golang
// DefaultTestTempStorageConfigWithSize is the associated temp storage for
// DefaultTestStoreSpec that is in-memory with the customized maximum size.
func DefaultTestTempStorageConfigWithSize(
	st *cluster.Settings, maxSizeBytes int64,
) TempStorageConfig {
	monitor := mon.NewMonitor(
		"in-mem temp storage",
		mon.DiskResource,
		nil,             /* curCount */
		nil,             /* maxHist */
		1024*1024,       /* increment */
		maxSizeBytes/10, /* noteworthy */
		st,
	)
	monitor.Start(context.Background(), nil /* pool */, mon.NewStandaloneBudget(maxSizeBytes))
	return TempStorageConfig{
		InMemory: true,
		Mon:      monitor,
		Settings: st,
	}
}
```

For the system tenant, this empty store spec survives our config process and via some logging we can see it right before we call NewTempEngine:

```
I231129 23:11:36.407700 15 server/server\_sql.go:718  \[T1,Vsystem,n?\] 9  creating temp engine: base.TempStorageConfig{InMemory:true, Path:"", Mon:(\*mon.BytesMonitor)(0x14001864820), Spec:base.StoreSpec{Path:"", Size:base.SizeSpec{InBytes:0, Percent:0}, BallastSize:(\*base.SizeSpec)(nil), InMemory:false, Attributes:roachpb.Attributes{Attrs:\[\]string(nil)}, StickyVFSID:"", UseFileRegistry:false, RocksDBOptions:"", PebbleOptions:"", EncryptionOptions:\[\]uint8(nil), ProvisionedRateSpec:base.ProvisionedRateSpec{DiskName:"", ProvisionedBandwidth:0}}, Settings:(\*cluster.Settings)(0x140036d2000)}
```

Then during tenant startup, we end up using that zero-values store spec when calling TempStorageConfigFromEnv.

However, perhaps this points out that a better fix would be to change DefaultTestTempStorageConfig  to populate the Spec correctly from the outset.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115246)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115246#-NkSCgLc4Cn8T2lsMfN_):*
I see, indeed, it's quite confusing. Currently, we end up with `TempStorageConfig.InMemory = true` and `TempStorageConfig.Spec.InMemory = false`.

> However, perhaps this points out that a better fix would be to change DefaultTestTempStorageConfig to populate the Spec correctly from the outset.

This sounds like the right approach. Also probably update `InheritTestTempStorageConfig` as well to copy over `parentConfig.Store`?

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115246)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115246#-NkSCgLc4Cn8T2lsMfN_):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I see, indeed, it's quite confusing. Currently, we end up with `TempStorageConfig.InMemory = true` and `TempStorageConfig.Spec.InMemory = false`.

> However, perhaps this points out that a better fix would be to change DefaultTestTempStorageConfig to populate the Spec correctly from the outset.

This sounds like the right approach. Also probably update `InheritTestTempStorageConfig` as well to copy over `parentConfig.Store`?
</blockquote></details>

I split this up into a few steps. The first commit does what we've outlined here.  Then there are some further cleanups so we can choose what to backport.

**Review by yuzefovich — APPROVED** [review]
:lgtm: with a minor suggestion, thanks!

> Reviewed 4 of 4 files at r2, 1 of 1 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115246#-:-NkX8a9S6hjEPP-Nyndm:bt652y3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[`pkg/sql/colflow/draining_test.go` line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115246#-NkX6zgbBHymYDqEGWQ6:-NkX6zgbBHymYDqEGWQ7:b-m6al9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/26388529ad777df68f9d6b7de7c254d6981cba55/pkg/sql/colflow/draining_test.go#L56)):*
> ```Go
> 
> 	// Set up a two node cluster.
> 	tempStorageConfig := base.TempStorageConfig{InMemory: true, Mon: diskMonitor, Settings: st, Spec: base.DefaultTestStoreSpec}
> ```

There are a few places in `rowcontainer` tests that might need the same change. I think there we can actually remove the manual instantiation of `base.TempStorageConfig` struct in favor of using `base.DefaultTestTempStorageConfig()`. This one in `draining_test` needs a manual instantiation because it has a custom disk monitor which `rowcontainer` tests / benchmarks don't.

**Comment by stevendanna** [comment]
@yuzefovich Thanks. I'm going to merge as is, but I'll be following up with some more changes to how these tempfiles work and will include more cleanups in there.  I _think_ that the other uses in rowcontainer don't likely represent problems in the tests because we aren't starting a secondary tenant using those particular TempStorageConfig's but I agree we should clean them up regardless.

**Comment by stevendanna** [comment]
bors r=yuzefovich

**Comment by yuzefovich** [comment]
Sounds good - those tests don't start a test server anyway.

**Pull request merged**
