### PR TITLE
workload: jitter the teardown of connections to prevent thundering herd

### PR DESCRIPTION
**Pull request by sean-**
workload: jitter the teardown of connections to prevent thundering herd

This change upgrades workload's use of pgx from v4 to v5 in order to allow jittering the teardown of connections.  This change sets a max connection age of 5min and jitters the teardown by 30s.  Upgrading to pgx v5 also adds non-blocking pgxpool connection acquisition.

workload: add flags to manage the age and lifecycle of connection pool

Add flags to all workload types to specify:

* the max connection age: `--max-conn-lifetime duration`
* the max connection age jitter: `--max-conn-lifetime-jitter duration`
* the max connection idle time: `--max-conn-idle-time duration`
* the connection health check interval: `--conn-healthcheck-period duration`
* the min number of connections in the pool: `--min-conns int`

workload: add support for remaining pgx query modes

Add support for `pgx.QueryExecModeCacheDescribe` and `pgx.QueryExecModeDescribeExec`.  Previously, only three of the five query modes were available.

workload: fix race condition when recording histogram data

Release note (cli change): workload jitters teardown of connections to prevent thundering herd impacting P99 latency results.

Release note (cli change): workload utility now has flags to tune the connection pool used for testing.  See `--conn-healthcheck-period`, `--min-conns`, and the `--max-conn-*` flags for details.

Release note (cli change): workload now supports every [PostgreSQL query mode](https://github.com/jackc/pgx/blob/fa5fbed497bc75acee05c1667a8760ce0d634cba/conn.go#L167-L182) available via the underlying pgx driver.

### CODE REVIEW

**Review by sean- — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98689)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs, @sravotto, and @srosenberg)

___
*[`pkg/workload/pgx_helpers.go` line 191 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98689#-NQfnDEsDE4zkoKUdFem:-NQfnDEsDE4zkoKUdFen:b-pbpua7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f38a8a4d5cee7dbad5f2c3de48f65b3291d5a7f/pkg/workload/pgx_helpers.go#L191)):*
> ```Go
> // MultiConnPool.  The max number of connections are warmed up if numConns is
> // set to 0.
> func (m *MultiConnPool) WarmupConns(ctx context.Context, numConns int) error {
> ```

I refactored connection pool warming out of `NewMultiConnPool()` into `WarmupConns()` so that a future engineer can potentially disable connection warmups when the `--ramp` argument is used.  Right now `--ramp`'ed workloads will have all connections established, which is still useful, but at present connections don't ramp with the workload.

**Review by srosenberg — COMMENTED** [review]
The changes seem sound to me. We should run some roachperfs before merging to the reduce the risk of a regression.

> Reviewed 1 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98689#-:-NQgpYPC6yLoffbhknlG:b2isye9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs, @sean-, and @sravotto)

___
*[`pkg/workload/pgx_helpers.go` line 120 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98689#-NQgcFA-CHHP-LKoINGW:-NQgcFA-CHHP-LKoINGX:b18pcsh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e2efd51542dccddd31c5abcbd0696725132fa1e/pkg/workload/pgx_helpers.go#L120)):*
> ```Go
> 		logLevel = cfg.LogLevel
> 	}
> 	maxConnLifetime := 5 * time.Minute
> ```

Previously (in v4), this default was 1 hour. What's the rationale for reducing it down to 5 minutes?
___
*[`pkg/workload/pgx_helpers.go` line 160 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98689#-NQgfsUqC_8Yi1o0fbEQ:-NQgfsUqC_8Yi1o0fbER:btkstby) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e2efd51542dccddd31c5abcbd0696725132fa1e/pkg/workload/pgx_helpers.go#L160)):*
> ```Go
> 			}
> 
> 			// Disable the automatic prepared statement cache. We've seen a lot of
> ```

Actual examples would be preferred. Is prepared statement cache detrimental in a majority of the cases? Does the cache churn have a non-negligible performance penalty for workload throughput?
___
*[`pkg/workload/pgx_helpers.go` line 164 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98689#-NQgfOSvCsHKyb4pJ3LY:-NQgfOSvCsHKyb4pJ3LZ:b8wqgvd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e2efd51542dccddd31c5abcbd0696725132fa1e/pkg/workload/pgx_helpers.go#L164)):*
> ```Go
> 			connCfg := poolCfg.ConnConfig
> 			connCfg.DefaultQueryExecMode = pgx.QueryExecModeDescribeExec
> 			connCfg.StatementCacheCapacity = 0
> ```

These two cache capacity defaults corresponds to `QueryExecModeCacheStatement` and `QueryExecModeCacheDescribe`. Why are we overriding them when the default mode is `QueryExecModeDescribeExec`?
___
*[`pkg/workload/pgx_helpers.go` line 237 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98689#-NQghvDx1i3jj4-VddJL:-NQghvDx1i3jj4-VddJM:bm9dw01) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e2efd51542dccddd31c5abcbd0696725132fa1e/pkg/workload/pgx_helpers.go#L237)):*
> ```Go
> 
> 	var numWarmupConns int
> 	if numConns <= 0 {
> ```

`< 0` is handled above. In fact, it feels like a precondition.
___
*[`pkg/workload/sql_runner.go` line 283 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98689#-NQglYp61-AgQJtZFQEQ:-NQglYp7-1gPt7YqgavT:b69ql54) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e2efd51542dccddd31c5abcbd0696725132fa1e/pkg/workload/sql_runner.go#L283)):*
> ```Go
> 	args = append(args, simpleQuery)
> 	copy(args[1:], args)
> 	args[0] = simpleQuery
> ```

This looks like a typo. The first element should be of type `pgx.QueryExecMode`, not `[]pgx.QueryExecMode`.
___
*[`pkg/workload/kv/kv.go` line 602 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98689#-NQgoWoe6oeoiaUy-MKO:-NQgoWoe6oeoiaUy-MKP:b-nzwjsy) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e2efd51542dccddd31c5abcbd0696725132fa1e/pkg/workload/kv/kv.go#L602)):*
> ```Go
> 		var tx pgx.Tx
> 		pl := o.mcp.Get()
> 		conn, err := pl.Acquire(ctx)
> ```

`BeginTx` does invoke `Acquire`, why the more verbose version?

**Review by sean- — COMMENTED** [review]
Additional testing would be welcome, but we don't see any major regressions.  Thanks to @sravotto, the new binary is already being tested.  Specifically, the following is a graph of the before and after, starting at ~8:25.  To get this effect, both #98689 and #98701 are required.  I expect we will see an improvement in tail latency with this new change, however, both because of the jitter, and because of a change in pgx 5.1.0 where pgx updated their internal version of Puddle to do a non-blocking, background acquisition of a resource:

https://github.com/jackc/pgx/blob/master/CHANGELOG.md#510-november-12-2022
https://github.com/jackc/puddle/blob/master/CHANGELOG.md#130-august-27-2022
https://github.com/jackc/pgx/commit/c00fb5d2a182b5d2ddc2ffab3fd7c4379f363478



> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98689#-:-NQkNm2l5AAyZmZ42Q8W:bg27c8n)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs, @sravotto, and @srosenberg)

___
*[`pkg/workload/pgx_helpers.go` line 120 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98689#-NQgcFA-CHHP-LKoINGW:-NQkRrHnDNm7oWIwP3Jh:b-lxd8mq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e2efd51542dccddd31c5abcbd0696725132fa1e/pkg/workload/pgx_helpers.go#L120)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Previously (in v4), this default was 1 hour. What's the rationale for reducing it down to 5 minutes?
</blockquote></details>

To allow for reasonable management of crdb clusters.  Specifically, if a crdb decommission was kicked off, we don't want to wait for 1hr for connections to drain.  Instead, we can kick off a benchmark and wait for only 5min to have the workload driver to recycle all of its connections, which significantly shortens the amount of time required for an operator to wait when performing any kind of maintenance.  The cost of establishing a TLS connection isn't so great that it can't be safely amortized over a 5min period of time.
___
*[`pkg/workload/pgx_helpers.go` line 160 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98689#-NQgfsUqC_8Yi1o0fbEQ:-NQkSIr99APMvFuxCQM9:bj1hr8f) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e2efd51542dccddd31c5abcbd0696725132fa1e/pkg/workload/pgx_helpers.go#L160)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Actual examples would be preferred. Is prepared statement cache detrimental in a majority of the cases? Does the cache churn have a non-negligible performance penalty for workload throughput?
</blockquote></details>

These comments were present before the refactoring required to update to pgx v5; therefore, I didn't revalidate them.
___
*[`pkg/workload/pgx_helpers.go` line 164 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98689#-NQgfOSvCsHKyb4pJ3LY:-NQkSX6620_GeLw4GQSs:b9dqz4a) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e2efd51542dccddd31c5abcbd0696725132fa1e/pkg/workload/pgx_helpers.go#L164)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

These two cache capacity defaults corresponds to `QueryExecModeCacheStatement` and `QueryExecModeCacheDescribe`. Why are we overriding them when the default mode is `QueryExecModeDescribeExec`?
</blockquote></details>

Ditto.  I wondered the same thing myself but didn't want to open a new investigation into a problem I wasn't attempting to solve.
___
*[`pkg/workload/pgx_helpers.go` line 237 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98689#-NQghvDx1i3jj4-VddJL:-NQkT3Sk3NTqmfVHi8yT:b-ymqqzl) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e2efd51542dccddd31c5abcbd0696725132fa1e/pkg/workload/pgx_helpers.go#L237)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

`< 0` is handled above. In fact, it feels like a precondition.
</blockquote></details>

Updated this check to be `==` instead.  The `< 0` check short-circuits the warmup entirely, whereas `== 0` auto-sizes the warmup to max conns.  There is no change in behavior, but this is slightly more explicit (the previous `< 0` short-circuit didn't exist until late in this update).
___
*[`pkg/workload/sql_runner.go` line 283 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98689#-NQglYp61-AgQJtZFQEQ:-NQkTLouBHb9FTdjl5LX:b-c2dwg4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e2efd51542dccddd31c5abcbd0696725132fa1e/pkg/workload/sql_runner.go#L283)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

This looks like a typo. The first element should be of type `pgx.QueryExecMode`, not `[]pgx.QueryExecMode`.
</blockquote></details>

This is the same `copy()` logic that was there previously and just a slice trick to prepend a value: https://github.com/cockroachdb/cockroach/blob/85c6e3874ed6f5e5e47da278b06e26e09d78bfb6/pkg/workload/sql_runner.go#L280-L282
___
*[`pkg/workload/kv/kv.go` line 602 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98689#-NQgoWoe6oeoiaUy-MKO:-NQkUOTaB195AoWDrK_1:bgldx8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e2efd51542dccddd31c5abcbd0696725132fa1e/pkg/workload/kv/kv.go#L602)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

`BeginTx` does invoke `Acquire`, why the more verbose version?
</blockquote></details>

TIL.  I was doing a strict refactor of what was there.  I've updated this to use `BeginTx()`.  Thank you!

**Review by nvb — COMMENTED** [review]
> Reviewed 9 of 22 files at r1, 4 of 4 files at r8, 13 of 13 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98689)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs, @sean-, @sravotto, and @srosenberg)

___
*[`pkg/workload/pgx_helpers.go` line 273 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/98689#-NRW46tB-h9beR-MfYRb:-NRW46tB-h9beR-MfYRc:bot62ng) ([raw file](https://github.com/cockroachdb/cockroach/blob/82739f5b2b976621232d56bc5b5aed0cdd32a340/pkg/workload/pgx_helpers.go#L273)):*
> ```Go
> }
> 
> // AddPreparedStatement adds the given sql statement to the map of
> ```

The comment on this method is off.
___
*[`pkg/workload/pgx_helpers.go` line 323 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/98689#-NRW5JCS3V4kV8lpxIo4:-NRW5JCS3V4kV8lpxIo5:b7z9prb) ([raw file](https://github.com/cockroachdb/cockroach/blob/82739f5b2b976621232d56bc5b5aed0cdd32a340/pkg/workload/pgx_helpers.go#L323)):*
> ```Go
> 		g.Go(func() error {
> 			if err := sem.Acquire(warmupCtx, 1); err != nil {
> 				warmupConns <- struct{}{}
> ```

With an error group, once any goroutine returns an error, the context is cancelled, so you should be able to `select { <-warmupConns, <-warmupCtx }` down below instead of doing this dance with the warmup conn accounting and sem release on the error path.
___
*[`pkg/workload/sql_runner.go` line 276 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/98689#-NRW5yq85OlDU3RYjQR8:-NRW5yq85OlDU3RYjQR9:b-4rut8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d336a6264404fa0b60d015fe548b73fb1ffed170/pkg/workload/sql_runner.go#L276)):*
> ```Go
> }
> 
> // prependQuerySimpleProtocol inserts pgx.QuerySimpleProtocol(true) at the
> ```

What allows us to remove this for the `QueryExecModeSimpleProtocol` case? Are we telling pgx to use `QueryExecModeSimpleProtocol` somewhere else?
___
*[`pkg/workload/indexes/indexes.go` line 162 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/98689#-NRW6CtQ1jz_z8IEFY-M:-NRW6CtQ1jz_z8IEFY-N:b-lcyqp6) ([raw file](https://github.com/cockroachdb/cockroach/blob/82739f5b2b976621232d56bc5b5aed0cdd32a340/pkg/workload/indexes/indexes.go#L162)):*
> ```Go
> 	}
> 	cfg := workload.MultiConnPoolCfg{
> 		ConnHealthCheckPeriod: w.connFlags.ConnHealthCheckPeriod,
> ```

This looks tedious and error-prone. Should we pull out a constructor?

**Review by sean- — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98689)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten, @renatolabs, @sravotto, and @srosenberg)

___
*[`pkg/workload/sql_runner.go` line 276 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/98689#-NRW5yq85OlDU3RYjQR8:-NRZk9P8AEGZ0JR2uJQ0:b-gg3g6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/d336a6264404fa0b60d015fe548b73fb1ffed170/pkg/workload/sql_runner.go#L276)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What allows us to remove this for the `QueryExecModeSimpleProtocol` case? Are we telling pgx to use `QueryExecModeSimpleProtocol` somewhere else?
</blockquote></details>

`Exec()` via [`pgxpool`](https://github.com/jackc/pgx/blob/master/pgxpool/conn.go#L82-L84) calls `Exec()` in [`pgconn`](https://github.com/jackc/pgx/blob/master/pgconn/pgconn.go#L925-L929), which always uses the simple query protocol.
___
*[`pkg/workload/indexes/indexes.go` line 162 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/98689#-NRW6CtQ1jz_z8IEFY-M:-NRZkdJd4AhWoS20hs3L:bvik9cp) ([raw file](https://github.com/cockroachdb/cockroach/blob/82739f5b2b976621232d56bc5b5aed0cdd32a340/pkg/workload/indexes/indexes.go#L162)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This looks tedious and error-prone. Should we pull out a constructor?
</blockquote></details>

I was cargo-culting the existing style here, but agree this should be revisited.

**Review by sean- — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98689)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten, @renatolabs, @sravotto, and @srosenberg)

___
*[`pkg/workload/indexes/indexes.go` line 162 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/98689#-NRW6CtQ1jz_z8IEFY-M:-NRdnzS_-2lbLrHDYQKR:b-u5k1fq) ([raw file](https://github.com/cockroachdb/cockroach/blob/82739f5b2b976621232d56bc5b5aed0cdd32a340/pkg/workload/indexes/indexes.go#L162)):*
<details><summary><i>Previously, sean- (Sean Chittenden) wrote…</i></summary><blockquote>

I was cargo-culting the existing style here, but agree this should be revisited.
</blockquote></details>

Revisited and created a helper function that creates a `workload.MultiConnPoolCfg` from a `workload.ConnFlags`

**Review by nvb — APPROVED** [review]
:lgtm: the change here looks good. Thanks for making it and iterating on this.

> Reviewed 1 of 2 files at r13, 1 of 1 files at r14, 6 of 6 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98689#-:-NReLF1X8LHwVc0lGzAU:bxdpoty)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @renatolabs, @sean-, @sravotto, and @srosenberg)

___
*[`pkg/workload/histogram/histogram.go` line 76 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/98689#-NReL6dZD7KYJ0KGZpmQ:-NReL6dZD7KYJ0KGZpmR:bxjcq60) ([raw file](https://github.com/cockroachdb/cockroach/blob/065bd78da92b95e0b98fd2d01e86f7b1bfd75f9d/pkg/workload/histogram/histogram.go#L76)):*
> ```Go
> func (w *NamedHistogram) Record(elapsed time.Duration) {
> 	w.prometheusHistogram.Observe(float64(elapsed.Nanoseconds()) / float64(time.Second))
> 	w.mu.Lock()
> ```

Nice find. What brought you here?

**Review by sean- — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98689)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bobvawter, @renatolabs, @sravotto, and @srosenberg)

___
*[`pkg/workload/histogram/histogram.go` line 76 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/98689#-NReL6dZD7KYJ0KGZpmQ:-NRhoM9A1Ekvc31Eiubl:blxd1j6) ([raw file](https://github.com/cockroachdb/cockroach/blob/065bd78da92b95e0b98fd2d01e86f7b1bfd75f9d/pkg/workload/histogram/histogram.go#L76)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Nice find. What brought you here?
</blockquote></details>

I started getting desperate to stamp out a race condition and ran the race detector as a quick first pass, and stumbled across this (h/t to @bobvawter for the suggestion).  The bug is when running `workload` with <100% of the connections pre-warmed, one connection `Acquire()` succeeds but returns an invalid connection, leading to the operator being required to run the test with `--tolerate-errors`.  This shouldn't be necessary but only happens at higher levels of concurrency and with low numbers of pre-warmed connections.  The following is for posterity and not something I want to have this PR block on.

I haven't been able to hunt down the bug yet.   I thought I resolved this, but by adding debug code, I masked the race condition.  Infuriatingly, if I inject debug code in the error branch, the error never presents itself.  (Mission accomplished? :laughing:).  Specifically, if you warm up less than 100% of the connections (this is a new feature, so this isn't a regression), then the call to [`pgxpool.Acquire()`](https://github.com/cockroachdb/cockroach/pull/98689/files#diff-b5ca6df33eebefec31e473d892cc2e114f5ea3d812012ebfd328efb9a0ab640dR113) can (and frequently does while the workload is just starting), return a `nil` `conn`.  The `err` return value varies, and the most common error is `read: connection reset by peer`.  With low levels of concurrency, this doesn't happen, but when using a concurrency of 300 and only warming up one connection, it happens nearly every run.

What's wild is putting in `q.Q()` (a debugging library I use) _in the error path_[2] seems to be all that's required to prevent the race from happening.  Downgrading from `q.Q()` to `log.Warningf()` reintroduces the problem.  I've been looking into `pgxpool`'s `Acquire()` and `Release()` code paths, as well as `jackc/puddle` but haven't been able to figure out where the bug is.  My current suspicion is a `pgxpool.Conn` is being `Release()`'ed back into the pool in an invalid state.  I've added `AfterRelease()` and `BeforeAcquire()` handlers to try and catch things inside of `pgxpool`, but struck out there. 
 I'm starting to suspect there's something subtle in the memory model that isn't being handled correctly in [`jackc/puddle`'s `Acquire()` or `Release()`](https://github.com/jackc/puddle/blob/c5402ce53663d3c6481ea83c2912c339aeb94adc/pool.go#L340-L341).  I'm going to continue to pursue this in the background because my gaze is starting to move external to `workload`.

[1] Sample `workload` output w/ bug:
```
$ workload run kv --tolerate-errors --db movr '--concurrency=300' --min-conns 1 '--duration=3s' '--warmup-conns=1' 'postgresql://root@127.0.0.1:26257/movr?sslmode=disable&name=url1'
INFO: Build completed successfully, 32 total actions
I230329 15:37:52.285739 1 workload/cli/run.go:622  [T1] 1  random seed: -2816927724130576403
I230329 15:37:52.285813 1 workload/cli/run.go:429  [T1] 2  creating load generator...
I230329 15:37:52.292837 1 workload/cli/run.go:460  [T1] 3  creating load generator... done (took 7.022875ms)
E230329 15:37:52.321974 1 workload/cli/run.go:548  [T1] 4  read tcp 127.0.0.1:52708 -> 127.0.0.1:26257: read: connection reset by peer
_elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
    1.0s       96        19013.8        19155.6     14.2     23.1     75.5     96.5 write
    2.0s       96        19489.6        19322.9     16.3     26.2     37.7     52.4 write
    3.0s       96        19349.8        19331.8     16.8     28.3     37.7     58.7 write
Highest sequence written: 58300. Can be passed as --write-seq=R58300 to the next run.

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
    3.0s       96          58000        19330.0     15.4     15.7     26.2     39.8     96.5  write

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
    3.0s       96          58000        19330.0     15.4     15.7     26.2     39.8     96.5
```

[2] Sample patch that masks the problem:

```
➜ git diff pkg/workload/sql_runner.go
diff --git a/pkg/workload/sql_runner.go b/pkg/workload/sql_runner.go
index 8f579a69258..6c39e657e76 100644
--- a/pkg/workload/sql_runner.go
+++ b/pkg/workload/sql_runner.go
@@ -14,6 +14,7 @@ import (
        "context"
        "fmt"

+       // "github.com/cockroachdb/cockroach/pkg/util/log"
+       "github.com/ryboe/q"
        "github.com/cockroachdb/errors"
        "github.com/jackc/pgx/v5"
        "github.com/jackc/pgx/v5/pgconn"
@@ -110,8 +111,16 @@ type StmtHandle struct {
 // See pgx.Conn.Exec.
 func (h StmtHandle) Exec(ctx context.Context, args ...interface{}) (pgconn.CommandTag, error) {
        h.check()
        conn, err := h.s.sr.mcp.Get().Acquire(ctx)
        if err != nil {
+               // log.Warningf(ctx, "race conditions gunna race: %v", h.s.sr.mcp)
+               q.Q("mcp", h.s.sr.mcp)
                return pgconn.CommandTag{}, err
        }
        defer conn.Release()

```

**Comment by sean-** [comment]
bors try

**Comment by sean-** [comment]
bors retry

**Comment by sean-** [comment]
bors retry

**Pull request merged**
