### PR TITLE
sql: enhance the handling of internal errors, add sentry reporting

### PR DESCRIPTION
**Pull request by knz**
Subsumes #35826.
Subsumes #35823.

This PR achieves the following:

- (jordan) removes the stack trace from the telemetry counters
- (roadmap) encloses a stack trace in pgerror.Error objects
- (roadmap) reports the details of pgerrors with CodeInternalError to sentry
- (radu) shows these details when an internal error is encountered in logic tests
- (radu) shows these details when a pgerror is printed somewhere else with `printf("%+v", err)`
- (bug fix) fixes the crash reporting enable flag (detection was broken)

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

Very nice work, thank you! This gets us all the benefits we had with panics but without actually crashing!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35820#-:-La7b_aH6P0NAI9EghDz:bve9jjv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @knz, and @RaduBerinde)

___
*[pkg/sql/pgwire/pgerror/errors.go, line 295 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35820#-La7_BFe6GTDcNe6PQkw:-La7_BFe6GTDcNe6PQkx:b-3q1xji) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fac91da4ead0bda37fb63b2b0e744105344819f/pkg/sql/pgwire/pgerror/errors.go#L295)):*
> ```Go
> }
> 
> // Format implements the fmt.Formatter interface.
> ```

[nit] Add to this comment and explain the three variations `v`, `+v`, s`. It's important because it's not common for `%s` and `%v` to be different.
___
*[pkg/sql/pgwire/pgerror/errors.go, line 299 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35820#-La7_cG26EbHfD35ldVY:-La7_cG26EbHfD35ldVZ:b-clms6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fac91da4ead0bda37fb63b2b0e744105344819f/pkg/sql/pgwire/pgerror/errors.go#L299)):*
> ```Go
> 	switch verb {
> 	case 'v':
> 		switch {
> ```

[nit] switch with a single case should be `if`. Or just put them all in a big switch with
```go
case verb == 'v' && s.Flag('+'):
case verb == 'v':
case verb == 's':
```
___
*[pkg/sql/pgwire/pgerror/errors.go, line 318 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35820#-La7_vRC5F50ihX6fn6g:-La7_vRC5F50ihX6fn6h:b2rs838) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fac91da4ead0bda37fb63b2b0e744105344819f/pkg/sql/pgwire/pgerror/errors.go#L318)):*
> ```Go
> 	case 's':
> 		fmt.Fprintf(s, "%s", pg.Message)
> 	}
> ```

What is this supposed to return if the verb is bad? Unfortunately this interface is poorly documented in `fmt`.
___
*[pkg/sql/pgwire/pgerror/errors.proto, line 50 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35820#-La7aYfY9cKEyV25z822:-La7aYfY9cKEyV25z823:b-qz0ye9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fac91da4ead0bda37fb63b2b0e744105344819f/pkg/sql/pgwire/pgerror/errors.proto#L50)):*
> ```protobuf
>   }
> 
>   // complement to the detail field that can be reported
> ```

[nit] explicitly mention that all info is scrubbed

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35820)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/pgwire/pgerror/errors.go, line 295 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35820#-La7_BFe6GTDcNe6PQkw:-LaAOx3iA5m59HFLmEqG:b-23hndi) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fac91da4ead0bda37fb63b2b0e744105344819f/pkg/sql/pgwire/pgerror/errors.go#L295)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Add to this comment and explain the three variations `v`, `+v`, s`. It's important because it's not common for `%s` and `%v` to be different.
</blockquote></details>

I changed it back - it was breaking otherwise.
___
*[pkg/sql/pgwire/pgerror/errors.go, line 299 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35820#-La7_cG26EbHfD35ldVY:-LaAOzz3EX75sTqi0Ffx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fac91da4ead0bda37fb63b2b0e744105344819f/pkg/sql/pgwire/pgerror/errors.go#L299)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] switch with a single case should be `if`. Or just put them all in a big switch with
```go
case verb == 'v' && s.Flag('+'):
case verb == 'v':
case verb == 's':
```
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/pgerror/errors.go, line 318 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35820#-La7_vRC5F50ihX6fn6g:-LaAP04S9kl8PtJHjh1K:b-6va7ca) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fac91da4ead0bda37fb63b2b0e744105344819f/pkg/sql/pgwire/pgerror/errors.go#L318)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

What is this supposed to return if the verb is bad? Unfortunately this interface is poorly documented in `fmt`.
</blockquote></details>

Then nothing is printed. That's the way the `errors` package does it, so I'm not asking further questions.
___
*[pkg/sql/pgwire/pgerror/errors.proto, line 50 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35820#-La7aYfY9cKEyV25z822:-LaAPL2m4PAcIbJuQ0jd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fac91da4ead0bda37fb63b2b0e744105344819f/pkg/sql/pgwire/pgerror/errors.proto#L50)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] explicitly mention that all info is scrubbed
</blockquote></details>

Done.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/pgwire/pgerror/errors.go, line 295 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35820#-La7_BFe6GTDcNe6PQkw:-LaAQc0M0mShLsI-PqOU:bk29s5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fac91da4ead0bda37fb63b2b0e744105344819f/pkg/sql/pgwire/pgerror/errors.go#L295)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I changed it back - it was breaking otherwise.
</blockquote></details>

Ok, great. I actually hit this in a test where I had to change `%s` to `%v` which felt strange.

Still worth a comment mentioning that `%s / %v` show the error message and `%+v` shows details as well (`+v` is not particularly well documented in `fmt`, it just says "when printing structs, the plus flag (%+v) adds field names").

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35820)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/pgwire/pgerror/errors.go, line 295 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35820#-La7_BFe6GTDcNe6PQkw:-LaAWENL6ogYO8tC5yo_:b-gk1pbx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fac91da4ead0bda37fb63b2b0e744105344819f/pkg/sql/pgwire/pgerror/errors.go#L295)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Ok, great. I actually hit this in a test where I had to change `%s` to `%v` which felt strange.

Still worth a comment mentioning that `%s / %v` show the error message and `%+v` shows details as well (`+v` is not particularly well documented in `fmt`, it just says "when printing structs, the plus flag (%+v) adds field names").
</blockquote></details>

Added the comment.

**Comment by knz** [comment]
This PR is more or less complete, but I want to get a green build on #35821 to verify that the API changes here are good.

**Comment by knz** [comment]
It was a good idea to iterate on the other PR before merging this one. I discovered that the `pgerror.Wrap` functions were not well defined: 

1. they should return `nil` if given a `nil` err as input (that's how `errors.Wrap` is used in many places)
2. because they must return a `nil` *interface reference*, they can't return `*Error` -- a `nil` *Error is turned into a non-nil `error`, and that breaks things badly.

Adjusted the PR accordingly, with an explanatory comment.

**Comment by knz** [comment]
Another "oops" caught by the other PR: the result message for
`pgerror.Wrapf(errors.Wrap(pgerror.NewError("x", "a"), "b"), "c")`

should be `c: b: a`, not `c: a`.

Fixed (also added a test).

**Comment by knz** [comment]
Yet another "oops" caught in tests:

`pgerror.Wrapf(err, CodeDataExceptionError, ...)` is meant to add the pg code if `err` didn't have one already.

However if `err` is a retry error, we want the retry error code to prevail over the one provided to `Wrapf`.

I modified the logic accordingly to preserve retry errors + ambiguity errors.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/pgwire/pgerror/wrap.go, line 82 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/35820#-LaFmWvV9MYHVAmgbIas:-LaFmWvW-XhoIGCkCyFN:b-7dnixd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6ef12ca8377583dcdf464749bdeb04924905fa3/pkg/sql/pgwire/pgerror/wrap.go#L82)):*
> ```Go
> 
> 		// We'll want to report what we can from the provided context.
> 		st := log.NewStackTrace(depth + 1)
> ```

If the error already was CodeInternalError and had a stack trace, do we need to embed another stack trace every time we wrap it?

**Comment by knz** [comment]
> If the error already was CodeInternalError and had a stack trace, do we need to embed another stack trace every time we wrap it?

**Comment by knz** [comment]
> If the error already was CodeInternalError and had a stack trace, do we need to embed another stack trace every time we wrap it?

As I was debugging a couple of things I discovered that error objects do not simply flow on *return* paths, they also move horizontally in code (i.e. passed "down" to function calls) and also across the network (distsql).

capturing the wrap stack traces gives a better idea of the paths taken through the code by an error.

**Pull request merged**
