### PR TITLE
kvserver: disable allocator checks with `COCKROACH_DISABLE_LEADER_FOLLOWS_LEASEHOLDER`

### PR DESCRIPTION
**Pull request by erikgrinaker**
Otherwise, the replicate queue may be unable to relocate leaseholder replicas. This can cause e.g. `failover/partial/lease-leader` to flake.

Resolves #112241.
Epic: none
Release note: None

### CODE REVIEW

**Comment by erikgrinaker** [comment]
I'll need to verify this fix by stressing `failover/partial/lease-leader`, doing 100 runs.

**Comment by erikgrinaker** [comment]
Passed 100/100 stress runs.

**Review by andrewbaptist — APPROVED** [review]
:lgtm:

Thanks for getting this fixed. I wonder if this would have been easier if `COCKROACH_DISABLE_LEADER_FOLLOWS_LEASEHOLDER` was a testing knob, because I'm not fully sure I understand all the implications of it being set for other parts of the system. But for now, definitely good to deflake this.

**Comment by erikgrinaker** [comment]
> I wonder if this would have been easier if `COCKROACH_DISABLE_LEADER_FOLLOWS_LEASEHOLDER` was a testing knob, because I'm not fully sure I understand all the implications of it being set for other parts of the system.

It effectively is. We can't modify testing knobs directly in roachtests, because they use a pre-built binary, but `COCKROACH_DISABLE_LEADER_FOLLOWS_LEASEHOLDER` enables the 3 following testing knobs at runtime:

* `StoreTestingKnobs.DisableLeaderFollowsLeaseholder = true`
* `StoreTestingKnobs.AllowLeaseRequestProposalsWhenNotLeader = true`
* `allocator.TestingKnobs.AllowLeaseTransfersToReplicasNeedingSnapshots = true`

There is functionally no difference between setting that envvar or setting those three testing knobs.

See:

https://github.com/cockroachdb/cockroach/pull/112958/files#diff-54f1a64483857ccffab8db68de1c7b15c8ce88450e5769fb219cb1dc55fedb9dR1336-R1341

**Pull request merged**
