### PR TITLE
opt: implement execution for GROUP BY

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: support rowsort in execbuilder test

This is useful for queries where the ordering of results can vary
(e.g. GROUP BY).

Release note: None

#### sql: set ActiveMemAcc in newInternalPlanner

This is used for the optimizer test engine and I see a crash because
this is not initialized.

Release note: None

#### sql: simplify aggregateFuncHolder

We don't need a function reference in aggregateFuncHolder, just the
name of the function.

Release note: None

#### opt: implement execution for GROUP BY

The testfile includes most of the tests in `TestLogic/aggregate`; I
removed cases that were testing just the build process (e.g. semantic
errors).

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
:lgtm:
I don't have enough context on the funcName change, but rest LGTM.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23501#-:-L6xB2JfYgZOaq7WCJWC:b96lhvf)*

**Comment by rytaft** [comment]
:lgtm: 

---

Reviewed 8 of 9 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt_exec_engine.go, line 260 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23501#-L6xBKKpxPIwVQm_IwcX:-L6xBKKpxPIwVQm_IwcY:bqqwmrf) ([raw file](https://github.com/cockroachdb/cockroach/blob/41a61b1ff1e509298570ff85d11ff803455fa5e5/pkg/sql/opt_exec_engine.go#L260)):*
> ```Go
> 		// TODO(radu): only generate the grouping columns we actually need.
> 		f := n.newAggregateFuncHolder(
> 			"", /* function */
> ```

function -> funcName

---

*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 273 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23501#-L6xDaYfxSQALWU0vEMV:-L6xDaYfxSQALWU0vEMW:boxw6rt) ([raw file](https://github.com/cockroachdb/cockroach/blob/41a61b1ff1e509298570ff85d11ff803455fa5e5/pkg/sql/opt/exec/execbuilder/relational_builder.go#L273)):*
> ```Go
> 
> 		argIdx := make([]int, fn.ChildCount())
> 		for i := range argIdx {
> ```

[nit] `i` is hiding the outer `i`

---

*[pkg/sql/opt/exec/execbuilder/testdata/aggregate, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23501#-L6xEgY2-SQTGMxHijNK:-L6xEgY2-SQTGMxHijNL:brth7ar) ([raw file](https://github.com/cockroachdb/cockroach/blob/41a61b1ff1e509298570ff85d11ff803455fa5e5/pkg/sql/opt/exec/execbuilder/testdata/aggregate#L1)):*
> ```
> # tests adapted from logictest -- aggregate
> ```

Are there any tests which have different output from the original logictests file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23501#-:-L6xE_CblclIAI2i6Nvq:bg7igkv)*

**Comment by RaduBerinde** [comment]
Review status: 6 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/opt_exec_engine.go, line 260 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23501#-L6xBKKpxPIwVQm_IwcX:-L6xJI_EGhiGPCToLS3I:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/41a61b1ff1e509298570ff85d11ff803455fa5e5/pkg/sql/opt_exec_engine.go#L260)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

function -> funcName
</blockquote></details>

Done.

---

*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 273 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23501#-L6xDaYfxSQALWU0vEMV:-L6xJPueo91YlN_ypUoA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/41a61b1ff1e509298570ff85d11ff803455fa5e5/pkg/sql/opt/exec/execbuilder/relational_builder.go#L273)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] `i` is hiding the outer `i`
</blockquote></details>

Done.

---

*[pkg/sql/opt/exec/execbuilder/testdata/aggregate, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23501#-L6xEgY2-SQTGMxHijNK:-L6xJQMuLA5FFTqwdrhK:b-lprn6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/41a61b1ff1e509298570ff85d11ff803455fa5e5/pkg/sql/opt/exec/execbuilder/testdata/aggregate#L1)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Are there any tests which have different output from the original logictests file?
</blockquote></details>

No (unless I missed it). I checked diffs between the logictest file and this file as I was enabling groups of tests and I didn't see any differences (other than order for rowsort queries)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23501)*

**Comment by rytaft** [comment]
Reviewed 2 of 2 files at r2.
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/opt/exec/execbuilder/testdata/aggregate, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23501#-L6xEgY2-SQTGMxHijNK:-L6xKO6TKxKDrDgqkh9S:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/41a61b1ff1e509298570ff85d11ff803455fa5e5/pkg/sql/opt/exec/execbuilder/testdata/aggregate#L1)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

No (unless I missed it). I checked diffs between the logictest file and this file as I was enabling groups of tests and I didn't see any differences (other than order for rowsort queries)
</blockquote></details>

:thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23501)*

**Pull request merged**
