### PR TITLE
ui: Tweak the style of the caret in the timeScaleDropdown component

### PR DESCRIPTION
**Pull request by jocrl**
Contributes to #74512.

This commit modifies the style and size of the caret in the timeScaleDropdown
component to match that of the "Filters" dropdown in the Statements and
Transactions pages.

Release note (ui): A minor styling tweak to change style of the caret in the
time selection component.

Before:
image

After:
image

Superimposed with the caret in the Filters dropdown:
image

### CODE REVIEW

**Comment by Annebirzin** [comment]
@jocrl yep I think that works. Another nit: Can we also make all the arrows (Filter arrow, Timepicker arrow, left/right arrow) match the gray that is used in the Text (ie. 'Filter (0)' and '3:03PM - 4:03PM' text)?

**Comment by jocrl** [comment]
@Annebirzin actually, I'm realizing that the caret in the time selection component was made to match those of dropdowns in the metrics page. That Metrics-style caret component is used in quite a few places in db-console, whereas the Filters-style caret is used more often in cluster-ui (pages that are shared between db-console and managed-service).

Not sure what you want to do about the caret styles? Should there be different styles for the metrics, vs statements and transactions pages? I'll file a CRUX ticket to unify the two, but that seems like a larger issue.

Metrics page before this change:
image
Metrics page after this change:
image

Usages of the metrics-style caret component:
image

Usages of the filters-style caret component:
image

**Comment by Annebirzin** [comment]
@jocrl Oh I see. Ideally, the caret would be the same style across all these pages rather than having different styles

**Comment by jocrl** [comment]
Right. How about we go with no changes for now, and I'll file an issue with the CRUX team to unify the caret/dropdown components? It looks like you've previously filed a few for other components.

**Comment by Annebirzin** [comment]
Sounds good! Hm yea those might be very old tickets, but probably still worth updating at some point.

**Comment by jocrl** [comment]
Created https://cockroachlabs.atlassian.net/browse/CC-6186

**Pull request closed without merging**
