### PR TITLE
sql: payloads_for_trace should start iterator in Start

### PR DESCRIPTION
**Pull request by stevendanna**
According to the comments on the ValueGenerator interface, Close()
should not need to be called unless Start was called. This was not
true for payloads_for_trace since it started an iterator in a
constructor rather than in Start.

I don't believe this currently causes any problems, but I noted it
making an unrelated change.

Epic: None
Release justification: low risk bug fix
Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
lgtm, but i think this is better reviewed by obs-inf or maybe kv-obs

**Review by dhartunian — APPROVED** [review]
:lgtm: thanks @stevendanna. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86989#-:-NDYgCtH4TpuBg0D7E2A:b3pwvgj)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
consider whether we can remove this function, as well as `payloads_for_span`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86989#-:-NDYkqAiAFO-EUHuRIfS:b2i6i6b)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
