### PR TITLE
clusterversion: prefix version keys by release

### PR DESCRIPTION
**Pull request by dt**
When we need to mint a new version, prefixing it with the version it will be released in, makes it easier to read the code and know when it will or will not be active, and makes it easier to find all the version-specific code that is relevant to a specific version upgrade step, for example when deleting it after that step falls out of the compatibility window.

For example, when naming a version for a migration that will occur during the upgrade to 23.1, a name like `clusterversion.V23_1JobStatsTable` instead of just `clusterversion.JobStatsTable` clearly shows the reader when this version became active -- in the upgrade to 23.1 -- and makes it easy to find-and-delete checks of this version once support for 23.1 is dropped.

Release note: none.
Epic: none.

### CODE REVIEW

**Review by knz — APPROVED** [review]
This is cool but must have been a chore to implement :sweat_smile:

**Comment by dt** [comment]
> a chore to implement

Eh, not to bad; a regex did most of the work and then just let the complier slowly go and find the rest of missed ones between other tasks.

**Review by celiala — APPROVED** [review]
Thank you! 🙏🏼 💯 - LGTM!

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
