### PR TITLE
opt: better remaining filter simplification for OR

### PR DESCRIPTION
**Pull request by RaduBerinde**
Currently we have some simple cases where a disjunction results in exact (tight)
constraints, and yet we still have unnecessary remaining filters.

This change fixes this by plumbing more "tightness" information and moving the
Or filter simplification later, after we get to check if the condition is
implied by the final spans.

Release note (performance improvement): improvement in some plans involving
filters with OR expressions.

Release justification: low-risk, high-benefit change to existing functionality.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46371#-:-M36HJlkByVdOTU7xE92:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @RaduBerinde)

___
*[pkg/sql/opt/idxconstraint/index_constraints.go, line 712 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46371#-M36FUn70e4xJjJHPQfx:-M36FUn70e4xJjJHPQfy:b-jk267) ([raw file](https://github.com/cockroachdb/cockroach/blob/c661945a6c6b1228fd547362e43525b8a5826a4d/pkg/sql/opt/idxconstraint/index_constraints.go#L712)):*
> ```Go
> 		// that corresponds to where the key ends. We can skip offsets at which no
> 		// keys end.
> 		// To calculate this, we get the minimum length of any key that doesn't ends
> ```

[nit] ends -> end

(not this change, but while you're making changes...)
___
*[pkg/sql/opt/idxconstraint/index_constraints.go, line 1070 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46371#-M2uH4Ny0xlkRH5wXEpS:-M2uH4Nz9kZ3cabgZVos:b6q9kl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c661945a6c6b1228fd547362e43525b8a5826a4d/pkg/sql/opt/idxconstraint/index_constraints.go#L1070)):*
> ```Go
> //
> //    An example where this doesn't work well is with disjunctions:
> //    `@1 <= 1 OR @1 >= 4` has spans `[ - /1], [/1 - ]` but in separation neither
> ```

Should this be `[ - /1], [/4 - ]`? Also, is this comment still valid?

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46371#-:-M373jCIDweOV9DF1Ezi:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @rytaft)

___
*[pkg/sql/opt/idxconstraint/index_constraints.go, line 712 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46371#-M36FUn70e4xJjJHPQfx:-M373UrjAqdRTRrlg11q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c661945a6c6b1228fd547362e43525b8a5826a4d/pkg/sql/opt/idxconstraint/index_constraints.go#L712)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] ends -> end

(not this change, but while you're making changes...)
</blockquote></details>

Done.
___
*[pkg/sql/opt/idxconstraint/index_constraints.go, line 1070 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46371#-M2uH4Ny0xlkRH5wXEpS:-M373UJrBrxarMzRlqRr:b-7ota9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/c661945a6c6b1228fd547362e43525b8a5826a4d/pkg/sql/opt/idxconstraint/index_constraints.go#L1070)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Should this be `[ - /1], [/4 - ]`? Also, is this comment still valid?
</blockquote></details>

Removed. The comment was right in that this didn't work, but it was wrong in that it wasn't a consequence of the conditions described above.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46371)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball)

**Pull request merged**
