### PR TITLE
sql: set "output tuples" stat in row execution

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change makes all the rowexec processors emit the output tuple
count stat.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56817)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @RaduBerinde)

___
*[pkg/sql/logictest/testdata/logic_test/explain_analyze_plans, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56817#-MMMopfc9mC4Wp_kFa0K:-MMMopfdDQjFUk8OveMs:b-99chga) ([raw file](https://github.com/cockroachdb/cockroach/blob/aadad7f3b0f9b4061453b9e440f72827432d0ab9/pkg/sql/logictest/testdata/logic_test/explain_analyze_plans#L94)):*
> ```
> SELECT url FROM [EXPLAIN ANALYZE (DISTSQL) SELECT avg(k) OVER () FROM kv]
> ----
> https://cockroachdb.github.io/distsqlplan/decode.html#eJzclE1v2zAMhu_7FQJPCaAg_hwGnZpt2RAsa7qk6D4KH1SL6ITYlifJabsi_32w7GRJ1q7uLehRJF-_ekiZ92B-ZcBgMZ6O352TSmfkw3z2mVyOv51NR5NTMjodTb__GJPe-8nifPFl2idtKV9d95Z9MrsYz0mv36iWqwQoFErgKc_RALsEHygEQCEEChFQiCGhUGqVojFK1yX3TjARt8A8CrIoK1uHEwqp0gjsHqy0GQKDc36V4Ry5QD30gIJAy2XmbJark1LLnOs7oLAoeWEYGQxr41llGTmpr_HpgliZIyOeaU9VmaEhGrlgpK24urPb0BvyFihccZv-RENUZcv6W7Vzq9yEfEjWFJpTe3dj-TUC89f0Eb6_WFWhtECNYg8pWT_Qga-yEOoG9TDexx9dfOyd-P0tbg3unFpGRuJtxFieZbudyPktyTFX-o7wLFMptygY8Rx8nTOprltAhDTLfysOWlH74C2mlZWq2HXp0Mb40TYGe230uz8T_-lnMgwGw_DIHkrQnTDoQBgOhtGREYbdCcMOhNHA_RLHRBh1J4w6EMaDI-N7YlnP0ZSqMHiw1B7-slcvOxTX2GxGoyqd4plWqbNpjjOncwGBxjZZvzlMCpdyF9wV-_8Vv94Te4fi4DnODsVRQYH2RuklueHS7g5JoEEteSZ_88PluJFsh5iiXGE7yE1yM81N7nkT3WcLXzBb9ILZ4pfElqxf_QkAAP__bPpoEQ==
> ```

We now are duplicating `tuples output` stat for the processors that are wrapped into the vectorized flows (`windower` in this query). We should either fix it in this PR or leave a TODO.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56817)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/explain_analyze_plans, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56817#-MMMopfc9mC4Wp_kFa0K:-MMN-cL0Bsmy6FMRxjHS:b-387keq) ([raw file](https://github.com/cockroachdb/cockroach/blob/aadad7f3b0f9b4061453b9e440f72827432d0ab9/pkg/sql/logictest/testdata/logic_test/explain_analyze_plans#L94)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

We now are duplicating `tuples output` stat for the processors that are wrapped into the vectorized flows (`windower` in this query). We should either fix it in this PR or leave a TODO.
</blockquote></details>

Good catch. I can try to fix it, can you point me to the code that wraps row procs into vectorized flows?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56817)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/explain_analyze_plans, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56817#-MMMopfc9mC4Wp_kFa0K:-MMN7Xa1Bdz8nxiAmLtQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aadad7f3b0f9b4061453b9e440f72827432d0ab9/pkg/sql/logictest/testdata/logic_test/explain_analyze_plans#L94)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Good catch. I can try to fix it, can you point me to the code that wraps row procs into vectorized flows?
</blockquote></details>

Done.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56817#-:-MMNOYFS-6bwJ3WPsq7I:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Pull request merged**
