### PR TITLE
distsql: Support `valuesNode` in planning

### PR DESCRIPTION
**Pull request by rampage644**
This PR addresses #14140

TODO:
 1. [x] Write tests
 1. [x] Better distribution recommendation

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Thanks for the contribution!

This should get tested by `TestLogic`. It would be good to add (to one of the `distsql_` test files) some cases that verifiy the plans for some queries, similar to [this one](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/distsql_agg#L75).

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/distsql_physical_planner.go, line 331 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16849#-KoJNMamaV0UqkZmfrH4:-KoJNMamaV0UqkZmfrH5:b-p99cip) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcc03c391f8889a07297608ccf36c1cd2d553e10/pkg/sql/distsql_physical_planner.go#L331)):*
> ```Go
> 
> 	case *valuesNode:
> 		rec := shouldNotDistribute
> ```

If we don't support some case (`n.n = nil`), we should return an error. Otherwise the query will still run under distsql when `DISTSQL_MODE` is `on`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16849#-:-KoJOFIkZ7tiRAfM4RT6:b2xu2it)*

**Comment by rampage644** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/distsql_physical_planner.go, line 331 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16849#-KoJNMamaV0UqkZmfrH4:-KoMgPWMeL8cFG7E7KU5:boqbiti) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcc03c391f8889a07297608ccf36c1cd2d553e10/pkg/sql/distsql_physical_planner.go#L331)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

If we don't support some case (`n.n = nil`), we should return an error. Otherwise the query will still run under distsql when `DISTSQL_MODE` is `on`.
</blockquote></details>

My bad, haven't read surrounding code attentive enough. Not returning an error results in test failures as well. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16849)*

**Comment by RaduBerinde** [comment]
LGTM

Please squash the commits.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/distsql_physical_planner.go, line 334 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16849#-KoN9Q1up2DUdLX1-YUF:-KoN9Q1up2DUdLX1-YUG:b-psef08) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d0ac861fef7f6bc33be938a9f12c0748b9039b5/pkg/sql/distsql_physical_planner.go#L334)):*
> ```Go
> 		var err error
> 		if n.n == nil {
> 			err = newQueryNotSupportedErrorf("unsupported node %T without SQL VALUES clause", node)
> ```

can just return 0, newQueryNotSupported here, it makes the logic easier to follow

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16849#-:-KoN9tx4-1KqzOuBz7VU:b6bsnph)*

**Comment by rampage644** [comment]
Done! Hope the tests won't stuck.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/distsql_physical_planner.go, line 334 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16849#-KoN9Q1up2DUdLX1-YUF:-KoQxtYJ5kv4gWSODRnP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d0ac861fef7f6bc33be938a9f12c0748b9039b5/pkg/sql/distsql_physical_planner.go#L334)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

can just return 0, newQueryNotSupported here, it makes the logic easier to follow
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16849#-:-KoR-AyZAE7XuAFjJY01:b-2toxj9)*

**Review by RaduBerinde — APPROVED** [review]

**Comment by rampage644** [comment]
Let me know if I'm expected to do anything else to this PR.

**Comment by RaduBerinde** [comment]
Merged, thanks!

**Pull request merged**
