### PR TITLE
stats: fix missing auto stats on system tables on cluster startup

### LINKED ISSUE #86362: stats: automatic stats on system tables might never be collected
I created a fresh cluster, and after 30 minutes there are still no stats on some of the system tables. For four of them it is expected, but out of the remaining 35 system tables stats are only present for 12. I believe the problem is that `getAllTablesTemplateSQL` query that is used for `ensureAllTables` explicitly filters out the system database. This means that unless there are some modifications to the system tables, they won't get the auto stats collected.

Jira issue: CRDB-18715

### PR DESCRIPTION
**Pull request by msirek**
Fixes #86362

Previously, auto stats were not collected on system tables at cluster
startup time. Auto stats support for system tables was added by #80887.

The query which discovers which tables to check for needed stats refresh
on startup was skipping system tables. This patch makes the adjustment
to that query.

Release note (bug fix): This patch fixes missing auto stats collection
on system tables during cluster startup. This bug only affects the 22.2
alpha release.

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

nit: add a backport 22.2 label.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88685#-:-NCptXYzCT6RRxAJbvr8:bdjspbe)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88685#-NCpswx70QaLwu8W-rBN):*
nit: I think that only in 22.2 we started collecting stats on system tables, so I don't think there has been a stable release with this bug, thus, no need for the release note.
___
*[`pkg/sql/stats/automatic_stats_test.go` line 208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88685#-NCpskNjAknUOVNW80je:-NCpskNjAknUOVNW80jf:bsgayvz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab096f5e1fc021cd3b0b80400ca4d61bf8bb2581/pkg/sql/stats/automatic_stats_test.go#L208)):*
> ```Go
> 
> 	// This now includes 36 system tables as well as the 2 created above.
> 	if err := checkAllTablesCount(ctx, 38, r); err != nil {
> ```

nit: can we define this number as a variable dependent on some constant? I.e. in case another system table is introduced I'd be great to not have to update this test manually.

**Review by msirek — COMMENTED** [review]
Added the label

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88685#-:-NCq5T2mC2lvt8JHnz7x:b-dj5sv4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88685#-NCpswx70QaLwu8W-rBN):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I think that only in 22.2 we started collecting stats on system tables, so I don't think there has been a stable release with this bug, thus, no need for the release note.
</blockquote></details>

Removed it
___
*[`pkg/sql/stats/automatic_stats_test.go` line 208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88685#-NCpskNjAknUOVNW80je:-NCqD-p71R1AtqH4ORwA:b-tg6o77) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab096f5e1fc021cd3b0b80400ca4d61bf8bb2581/pkg/sql/stats/automatic_stats_test.go#L208)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: can we define this number as a variable dependent on some constant? I.e. in case another system table is introduced I'd be great to not have to update this test manually.
</blockquote></details>

Added `bootstrap.NumSystemTablesForSystemTenant`

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88685#-:-NCqRy7Q6nzhEIcvS6H1:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @msirek and @yuzefovich)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88685#-NCpswx70QaLwu8W-rBN):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Removed it
</blockquote></details>

But we've still had alpha releases... is there a reason not to include the note and let the docs team decide? (could mention in the note that it only exists on alpha releases).
___
*[`pkg/sql/catalog/bootstrap/metadata.go` line 347 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88685#-NCqOUepAJln-cZFrcbt:-NCqOUepAJln-cZFrcbu:bj68mbc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a45a25a470a9c99b156ac1df4748101a5f5adc/pkg/sql/catalog/bootstrap/metadata.go#L347)):*
> ```Go
> 	// Adding a new system table? It should be added here to the metadata schema,
> 	// and also created as a migration for older clusters.
> 	// If adding a call to AddDescriptor or AddDescriptorForSystemTenant , please
> ```

nit: extra space before comma
___
*[`pkg/sql/catalog/bootstrap/metadata.go` line 348 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88685#-NCqRlVz9TLZNmvPTh_g:-NCqRlW-7H5GAJgGEzCF:b1wh6ao) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a45a25a470a9c99b156ac1df4748101a5f5adc/pkg/sql/catalog/bootstrap/metadata.go#L348)):*
> ```Go
> 	// and also created as a migration for older clusters.
> 	// If adding a call to AddDescriptor or AddDescriptorForSystemTenant , please
> 	// bump the setting of NumSystemTablesForSystemTenant below.
> ```

nit: maybe also note that this constant is just used for testing purposes. Because otherwise this feels kind of janky

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88685)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rytaft and @yuzefovich)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88685#-NCpswx70QaLwu8W-rBN):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

But we've still had alpha releases... is there a reason not to include the note and let the docs team decide? (could mention in the note that it only exists on alpha releases).
</blockquote></details>

Re-added the note mentioning the bug is in the alpha release.
___
*[`pkg/sql/catalog/bootstrap/metadata.go` line 347 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88685#-NCqOUepAJln-cZFrcbt:-NCqYzJFEPonJE6P1b5l:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a45a25a470a9c99b156ac1df4748101a5f5adc/pkg/sql/catalog/bootstrap/metadata.go#L347)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: extra space before comma
</blockquote></details>

Fixed



_Code quote:_
```Go
If adding a call to AddDescriptor or AddDescriptorForSystemTenant
```
___
*[`pkg/sql/catalog/bootstrap/metadata.go` line 348 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88685#-NCqRlVz9TLZNmvPTh_g:-NCqZzY12CiqfVt1sC51:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a45a25a470a9c99b156ac1df4748101a5f5adc/pkg/sql/catalog/bootstrap/metadata.go#L348)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: maybe also note that this constant is just used for testing purposes. Because otherwise this feels kind of janky
</blockquote></details>

Done

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88685#-:-NCqedPxD3YB0IKLiXzD:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

**Review by msirek — COMMENTED** [review]
TFTRs!
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88685#-:-NCrDbq2CSw3ovVfGd2I:bg1822s)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88685)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88685#-NCpswx70QaLwu8W-rBN):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Re-added the note mentioning the bug is in the alpha release.
</blockquote></details>

Yes, we had alpha releases, but I vaguely remember that we shouldn't include release notes for fixes to bugs only present in alphas - because we don't consider them "stable". I guess explicitly mentioning the affected releases should be enough to let the docs team decide.

**Pull request merged**
