### PR TITLE
kv: rationalize load-based range merging

### LINKED ISSUE #62700: kv/sql: GC after TRUNCATE temporarily craters write throughput
This issue described the back half of https://github.com/cockroachdb/cockroach/issues/62672.

After waiting out the GC TLL of a `TRUNCATE` or `DROP TABLE`, a series of `ClearRange` requests are issued to clear out space. This can cause a dramatic drop in write throughput on other tables that takes 10s of minutes to recover from. In the words of the customer that helped us diagnose this: "it's a write availability time bomb."

#### Reproduction

The easiest way to reproduce this is to use the `clearrange/checks=false` roachtest, with a slight adaptation to run load during the cleanup:

```go
diff --git a/pkg/cmd/roachtest/clearrange.go b/pkg/cmd/roachtest/clearrange.go
index e557cdd17b..25d8b4d10c 100644
--- a/pkg/cmd/roachtest/clearrange.go
+++ b/pkg/cmd/roachtest/clearrange.go
@@ -73,7 +73,7 @@ func runClearRange(ctx context.Context, t *test, c *cluster, aggressiveChecks bo

        if t.buildVersion.AtLeast(version.MustParse("v19.2.0")) {
                conn := c.Conn(ctx, 1)
-               if _, err := conn.ExecContext(ctx, `SET CLUSTER SETTING kv.bulk_io_write.concurrent_addsstable_requests = $1`, c.spec.NodeCount); err != nil {
+               if _, err := conn.ExecContext(ctx, `SET CLUSTER SETTING kv.bulk_io_write.concurrent_addsstable_requests = $1`, 8); err != nil {
                        t.Fatal(err)
                }
                conn.Close()
@@ -114,6 +114,11 @@ func runClearRange(ctx context.Context, t *test, c *cluster, aggressiveChecks bo
        }()

        m := newMonitor(ctx, c)
+       m.Go(func(ctx context.Context) error {
+               c.Run(ctx, c.Node(1), `./cockroach workload init kv`)
+               c.Run(ctx, c.All(), `./cockroach workload run kv --concurrency=32 --duration=1h30m`)
+               return nil
+       })
        m.Go(func(ctx context.Context) error {
                conn := c.Conn(ctx, 1)
                defer conn.Close()
@@ -132,7 +137,7 @@ func runClearRange(ctx context.Context, t *test, c *cluster, aggressiveChecks bo

                // Set a low TTL so that the ClearRange-based cleanup mechanism can kick in earlier.
                // This could also be done after dropping the table.
-               if _, err := conn.ExecContext(ctx, `ALTER TABLE bigbank.bank CONFIGURE ZONE USING gc.ttlseconds = 30`); err != nil {
+               if _, err := conn.ExecContext(ctx, `ALTER TABLE bigbank.bank CONFIGURE ZONE USING gc.ttlseconds = 1800`); err != nil {
                        return err
                }
```

This configures the test to import a 2 TB table, ramp write load up on a different table over 30 minutes, clear the 2 TB table, and then observe the impact on the foreground traffic. The effect is not pretty:

Screen Shot 2021-03-28 at 2 46 43 PM

#### Other notes

In attempting to reproduce, I also ran this with a configuration that looked more similar to the relevant customer's cluster - 20 nodes, 32 vCPU per node, 2 SSDs per node, and a 4 TB table. This looked very similar:

_note: this is a 10 minute time scale, not 30 minute like above_

Screen Shot 2021-03-27 at 10 49 58 PM

Screen Shot 2021-03-27 at 10 52 18 PM

### PR DESCRIPTION
**Pull request by nvb**
Closes #62700.
Fully addresses #41317.

This commit reworks how queries-per-second measurements are used when determining whether to merge two ranges together. At a high-level, the change moves from a scheme where the QPS over the last second on the LHS and RHS ranges are combined and compared against a threshold (half the load-based split threshold) to a scheme where the maximum QPS measured over the past 5 minutes (configurable) on the LHS and RHS ranges are combined and compared against said threshold.

The commit makes this change to avoid thrashing and to avoid overreacting to temporary fluctuations in load. These overreactions lead to general instability in clusters, as we saw in #41317. Worse, the overreactions compound and can lead to cluster-wide meltdowns where a transient slowdown can trigger a wave of range merges, which can slow the cluster down further, which can lead to more merges, etc. This is what we saw in #62700. This behavior is bad on small clusters and it is even worse on large ones, where range merges don't just interrupt traffic, but also result in a centralization of load in a previously well-distributed dataset, undoing all of the hard work of load-based splitting and rebalancing and creating serious hotspots.

The commit improves this situation by introducing a form of memory into the load-based split `Decider`. This is the object which was previously only responsible for measuring queries-per-second on a range and triggering the process of finding a load-based split point. The object is now given an additional role of taking the second-long QPS samples that it measures and aggregating them together to track the maximum historical QPS over a configurable retention period. This maximum QPS measurement can be used to prevent load-based splits from being merged away until the resulting ranges have consistently remained below a certain QPS threshold for a sufficiently long period of time.

The `mergeQueue` is taught how to use this new source of information. It is also taught that it should be conservative about imprecision in this QPS tracking, opting to skip a merge rather than perform one when the maximum QPS measurement has not been tracked for long enough. This means that range merges will typically no longer fire within 5 minutes of a lease transfer. This seems fine, as there are almost never situations where a range merge is desperately needed and we should risk making a bad decision in order to perform one.

I've measured this change on the `clearrange` roachtest that we made heavy use of in #62700. As expected, it has the same effect as bumping up the `kv.range_split.by_load_merge_delay` high enough such that ranges never merge on the active table. Here's a screenshot of a recent run. We still see a period of increased tail latency and reduced throughput, which has a strong correlation with Pebble compactions. However, we no longer see the subsequent cluster outage that used to follow, where ranges on the active table would begin to merge and throughput would fall to 0 and struggle to recover, bottoming out repeatedly.

Screen Shot 2021-04-26 at 12 32 53 AM

Screen Shot 2021-04-26 at 12 33 04 AM

Instead of what we originally saw, which looked like:

Screen Shot 2021-03-27 at 10 52 18 PM

Release note (performance improvement): Range merges are no longer considered if a range has seen significant load over the previous 5 minutes, instead of being considered as long as a range has low load over the last second. This improves stability, as load-based splits will no longer rapidly disappear during transient throughput dips.

cc @cockroachdb/kv

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Even on a 24-node cluster, things look much better. We still only see a performance hit due to merges on the inactive table and corresponding compactions, and no longer any collapse due to bad rebalancing/merging decisions on the active table. And as a reminder, this test is merging the inactive table extra aggressively. `kv.range_merge.queue_interval` defaults to `1s`, but the test drops it to `0s`. Without this, I would expect the transient slowdown to be less severe.

Screen Shot 2021-04-26 at 10 55 14 AM

Screen Shot 2021-04-26 at 10 55 26 AM

**Review by irfansharif — APPROVED** [review]
> Range merges are no longer triggered if a range has seen significant load over the previous 5 minutes, instead of only considering the last second. 

We'll want to reword the release note a bit I think, I'm not sure it's saying what we want it to say. 

Given we now have this QPS memory, do we still need split expirations? https://github.com/cockroachdb/cockroach/blob/fa324020c6358a7a9e42aab3feb722dac17db6ce/pkg/kv/kvserver/split_queue.go#L231-L250

Aside, to further reduce the impact of the merge queue, what would we advice customers to do? Given we're not doing any pacing ourselves, we'd just suggest bumping up `kv.range_merge.queue_interval` to something more acceptable for their given cluster size?

> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64201#-:-MZDzcY--LjBJvJphhP8:b-mumd64)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/client_merge_test.go, line 4077 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64201#-MZE10pwErC0iNRFxutw:-MZE10pwErC0iNRFxutx:b-8a679p) ([raw file](https://github.com/cockroachdb/cockroach/blob/0abf30a514ccc33a9921875939b9110ea799ad03/pkg/kv/kvserver/client_merge_test.go#L4077)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 	// TODO(nvanbenschoten): re-skip this test before merging.
> 	// skip.WithIssue(t, 64056, "flaky test")
> ```

Bump.
___
*[pkg/kv/kvserver/client_merge_test.go, line 4236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64201#-MZE7-mL7tsLN_3Q18sj:-MZE7-mL7tsLN_3Q18sk:bds3i2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/0abf30a514ccc33a9921875939b9110ea799ad03/pkg/kv/kvserver/client_merge_test.go#L4236)):*
> ```Go
> 	})
> 
> 	t.Run("load-based-merging", func(t *testing.T) {
> ```

Nice test.
___
*[pkg/kv/kvserver/client_merge_test.go, line 4255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64201#-MZE1N_l-mxd2Ejuaq0R:-MZE1N_l-mxd2Ejuaq0S:bdo9tuf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0abf30a514ccc33a9921875939b9110ea799ad03/pkg/kv/kvserver/client_merge_test.go#L4255)):*
> ```Go
> 			// measurement from both sides to be sufficiently stable and reliable,
> 			// meaning that it was a maximum measurement over some extended period of
> 			// time.
> ```

Some form of this comment would be well placed near the merge queue code, if not already there.
___
*[pkg/kv/kvserver/helpers_test.go, line 398 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64201#-MZE2HMWBYsA1BQXiadF:-MZE2HMWBYsA1BQXiadG:b9ifyma) ([raw file](https://github.com/cockroachdb/cockroach/blob/0abf30a514ccc33a9921875939b9110ea799ad03/pkg/kv/kvserver/helpers_test.go#L398)):*
> ```Go
> // assist load-based split (and merge) decisions.
> func (r *Replica) LoadBasedSplitter() *split.Decider {
> 	return &r.loadBasedSplitter
> ```

Should `r.loadBasedSplitter` simply be a pointer instead?
___
*[pkg/kv/kvserver/batcheval/cmd_range_stats.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64201#-MZDzzSxEDm4aLqktSyU:-MZDzzSxEDm4aLqktSyV:b-8a679p) ([raw file](https://github.com/cockroachdb/cockroach/blob/0abf30a514ccc33a9921875939b9110ea799ad03/pkg/kv/kvserver/batcheval/cmd_range_stats.go#L50)):*
> ```Go
> 		// TODO(nvanbenschten): this needs to be migrated in. As is, we will confuse
> 		// old versions. We'll need to keep using GetLastSplitQPS in mixed-version
> 		// clusters. Do this before merging.
> ```

Bump.

**Review by nvb — COMMENTED** [review]
Thanks for the review!

> We'll want to reword the release note a bit I think, I'm not sure it's saying what we want it to say.

Done.

> Given we now have this QPS memory, do we still need split expirations?

Good point. I've reworded the comment for now, and left a TODO to remove entirely once we can rely entirely on this new mechanism.

> Aside, to further reduce the impact of the merge queue, what would we advice customers to do? Given we're not doing any pacing ourselves, we'd just suggest bumping up kv.range_merge.queue_interval to something more acceptable for their given cluster size?

If customers are seeing this remain an issue, then bumping `kv.range_merge.queue_interval` would be the first suggestion. We bumped the default for this value up to 5s in https://github.com/cockroachdb/cockroach/pull/64239. The cluster size itself shouldn't matter, because the rate limit scales by store count.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64201#-:-MZjIj6uD39otwsDu9e-:b-jygr3j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif)

___
*[pkg/kv/kvserver/client_merge_test.go, line 4077 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64201#-MZE10pwErC0iNRFxutw:-MZj9b1O7cY6H0xAZLdf:bbx5l2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/0abf30a514ccc33a9921875939b9110ea799ad03/pkg/kv/kvserver/client_merge_test.go#L4077)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Bump.
</blockquote></details>

Done. I added a precursor commit on here which un-skips most of `TestMergeQueue` and only skips the `non-collocated` subtest, which we found to be the likely problem in #64199.
___
*[pkg/kv/kvserver/client_merge_test.go, line 4255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64201#-MZE1N_l-mxd2Ejuaq0R:-MZjALr55jxuT3vTM0Zt:b-qu6n94) ([raw file](https://github.com/cockroachdb/cockroach/blob/0abf30a514ccc33a9921875939b9110ea799ad03/pkg/kv/kvserver/client_merge_test.go#L4255)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Some form of this comment would be well placed near the merge queue code, if not already there.
</blockquote></details>

Good point. Done.
___
*[pkg/kv/kvserver/helpers_test.go, line 398 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64201#-MZE2HMWBYsA1BQXiadF:-MZjAbZRCse4d5f87UZd:bs8ze6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/0abf30a514ccc33a9921875939b9110ea799ad03/pkg/kv/kvserver/helpers_test.go#L398)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Should `r.loadBasedSplitter` simply be a pointer instead?
</blockquote></details>

We're pretty deliberate about allowing the `split.Decider` to stored by value, so I think this is intentional:
https://github.com/cockroachdb/cockroach/blob/684e753c15f3fc58df79b6ea70e7b6715eae4835/pkg/kv/kvserver/split/decider.go#L54-L57
___
*[pkg/kv/kvserver/batcheval/cmd_range_stats.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64201#-MZDzzSxEDm4aLqktSyU:-MZjFLoSDNRh2Ml9QLut:b-im9w57) ([raw file](https://github.com/cockroachdb/cockroach/blob/0abf30a514ccc33a9921875939b9110ea799ad03/pkg/kv/kvserver/batcheval/cmd_range_stats.go#L50)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Bump.
</blockquote></details>

Done. I avoided the cluster version and I did this in a way that should allow us to backport this change. I'd appreciate a second pair of eyes to check that I have the migration lined up correctly.

**Review by irfansharif — APPROVED** [review]
:lgtm:

> Reviewed 1 of 18 files at r2, 9 of 18 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64201#-:-MZo9mda0JyOiSkRzbGZ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif and @nvanbenschoten)

___
*[pkg/kv/kvserver/batcheval/cmd_range_stats.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64201#-MZDzzSxEDm4aLqktSyU:-MZo93JSAsWM9ASdMZUj:b-324c3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/0abf30a514ccc33a9921875939b9110ea799ad03/pkg/kv/kvserver/batcheval/cmd_range_stats.go#L50)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Done. I avoided the cluster version and I did this in a way that should allow us to backport this change. I'd appreciate a second pair of eyes to check that I have the migration lined up correctly.
</blockquote></details>

We'd backport this to 21.1.0? Or are we aiming for a patch release? The former would let us remove the extra fields in 21.2. The migration itself LGTM.

**Review by nvb — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64201#-:-MZoHso92zQvY36DQWZ-:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif)

___
*[pkg/kv/kvserver/batcheval/cmd_range_stats.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64201#-MZDzzSxEDm4aLqktSyU:-MZoHtrVEjiOdmvvBRWe:b-rrumkq) ([raw file](https://github.com/cockroachdb/cockroach/blob/0abf30a514ccc33a9921875939b9110ea799ad03/pkg/kv/kvserver/batcheval/cmd_range_stats.go#L50)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

We'd backport this to 21.1.0? Or are we aiming for a patch release? The former would let us remove the extra fields in 21.2. The migration itself LGTM.
</blockquote></details>

Good question. Unfortunately, I don't think we'll be able to get this into 21.1.0, which means that everything will be pushed back a release. It's too bad, but not worth the risk of rushing this in.

**Pull request merged**
