### PR TITLE
cli,storage: use VFS.GetDiskUsage instead of gosigar

### PR DESCRIPTION
**Pull request by jbowens**
Consolidate all disk usage calculations to go through the Pebble VFS's
GetDiskUsage function.

Release note: None

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
Added another commit to move the capacity calculation from mvcc.go into pebble.go, since it really has nothing to do with MVCC.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66796#-:-Md2yHTW0YJ7hy9oyUMD:bv72oxu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[pkg/server/config.go, line 518 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66796#-MdNrjNI5HZLLS0vLjGl:-MdNrjNI5HZLLS0vLjGm:bb7eprq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b28a2661ec4c23a9b606e72433ad23c45264ddd9/pkg/server/config.go#L518)):*
> ```Go
> 		} else {
> 			if spec.Size.Percent > 0 {
> 				du, err := vfs.Default.GetDiskUsage(spec.Path)
> ```

I'm forgetting -- do we have an implementation of this other than the one in `disk_usage_unix.go`? I see that gosigar has an implementation for windows too.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

___
*[pkg/server/config.go, line 518 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66796#-MdNrjNI5HZLLS0vLjGl:-MdNstil9fyn_8ntJP28:bgltlu4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b28a2661ec4c23a9b606e72433ad23c45264ddd9/pkg/server/config.go#L518)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'm forgetting -- do we have an implementation of this other than the one in `disk_usage_unix.go`? I see that gosigar has an implementation for windows too.
</blockquote></details>

Yeah, we have implementations for linux, unix and windows.

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 5 of 7 files at r1, 2 of 2 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66796#-:-MdNuKSe7vMuitRJJXH5:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66796#-:-MdNzviT-XWarVEv__qt:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Review by jbowens — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66796#-:-MdOKGnc4ahoCOv6cuqy:b-tlx7ko)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Pull request merged**
