### PR TITLE
cli/exit: new package to replace direct uses of os.Exit

### LINKED ISSUE #56508: distinct exit codes for different failure conditions
When debugging #56440 (support issue [#663](https://github.com/cockroachlabs/support/issues/663)), one of the first symptoms we observed was that our nodes were exiting with exit code 2. This initially lead us to believe that our nodes were having issues writing to log files, based on [our code which returns exit code 2 when that happens](https://github.com/cockroachdb/cockroach/blob/4f632cf1be01fdfdf3f4933e7d57ae48a5044ca8/pkg/util/log/exit_override.go#L71).

Instead, the reason we were observing exit code 2 is because that is the exit code returned by the Go runtime when `panic()` is called. We were not having issues writing to log files, but using exit code 2 when logging problems occur mislead us into thinking that was the problem.

It would be nice to use different exit codes for different exit conditions in CockroachDB, and document each exit code. We would then quickly be able to see what the cause of an unexpected crash was based on the exit code returned. For example, an exit code of 2 would indicate a runtime panic, an exit code of 3 could indicate an issue writing to log files, etc. @knz informs me there are at least 3 other exit conditions in CockroachDB, which could also return unique exit codes.

### PR DESCRIPTION
**Pull request by knz**
Fixes #56508 

Intended to be back-ported to 20.2. 

This commit introduces a new package `cli/exit` to organize the
process exit status codes returned when the `cockroach` process
terminates. These codes were previously not organized and not
easy to map back to particular situations.

The introduction of this structure for exit codes does not imply
that every particular situation can be mapped to a unique exit code.
As the new package's documentation indicates:

```go
// Note that due to the limited range of unix exit codes, it is not
// possible to map all possible error situations inside a CockroachDB
// server to a unique exit code.
// This is why the main mechanism to explain the cause of a process
// termination must remain the logging subsystem.
//
// The introduction of discrete exit codes here is thus meant to
// merely complement logging, in those cases where logging is unable
// to detail the reason why the process is terminating; for example:
//
// - before logging is initialized (e.g. during command-line parsing)
// - when a logging operation fails.
//
// For client commands, the situation is different: there are much
// fewer different exit situations, so we could envision discrete
// error codes for them. Additionally, different client commands
// can reuse the same numeric codes for different error situations,
// when they do not overlap.
```

Release note (cli change): Some specific situations now have dedicated
exit status codes. The following codes are defined:

| Code | Description                                                                                                                                         |
|------|-----------------------------------------------------------------------------------------------------------------------------------------------------|
| 0    | Process terminated without error.                                                                                                                   |
| 1    | An unspecified error was encountered. Explanation should be present in the stderr or logging output.                                                |
| 2    | Go runtime error, or uncaught panic. Likely a bug in CockroachDB. Explanation may be present in logging output.                                     |
| 3    | Server process interrupted gracefully with Ctrl+C / SIGINT.                                                                                         |
| 4    | Command-line flag error.                                                                                                                            |
| 5    | A logging operation to the process' stderr stream failed (e.g. stderr has been closed). Some details may be present in the file output, if enabled. |
| 6    | A logging operation to file has failed (e.g. log disk full, no inodes, permission issue, etc). Some details may be present in the stderr stream.    |
| 7    | Server detected an internal error and triggered an emergency shutdown.                                                                              |
| 8    | Logging failed while processing an emergency shutdown.                                                                                              |

### CODE REVIEW

**Comment by joshimhoff** [comment]
This makes me so happy.

> Intended to be back-ported to 20.2.

I kinda figured we wouldn't be able to backport to 20.1 since could break customers that depend on exit codes but now I wonder if we can given that we ARE backporting to 20.2, which is launched. 

Actually tho, we could backport into 20.1 but only use new functionality if a flag is set. And then set that flag on CC. CC users don't have access to exit codes.

Thoughts?

**Comment by knz** [comment]
exit codes were not documented before now, so i'm mildly favorable to changing the behavior in existing releases. @bdarnell may have a different opinion.

**Review by DuskEagle — APPROVED** [review]
Thank you! This looks really good.

For what it's worth, I don't see any issues with backporting this change.

> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56574#-:-MLs3JXQCm9VSBUSVI5z:b9l3m39)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @DuskEagle, @joshimhoff, and @knz)

___
*[pkg/cli/exit/codes.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56574#-MLs2ADA8-H7ePnIW4cc:-MLs2ADA8-H7ePnIW4cd:b9mh0ho) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd7736b2b798b5723980e3a7dbb4b55a59b6bb0a/pkg/cli/exit/codes.go#L34)):*
> ```Go
> // Interrupted (3) indicates the server process was interrupted with
> // Ctrl+C / SIGINT.
> func Interrupted() Code { return Code{3} }
> ```

When I first saw this I wondered why we weren't using exit code 130 for this error (i.e. 128+(SIGINT's signal number)). But after reading a bit more I think using a different error code is justifiable. 130 would be the exit code if the signal directly terminated CockroachDB. But since the signal was handled, even returning exit code 130 would not be the same as exiting due to the INT signal: https://unix.stackexchange.com/a/386856. So using a different exit code makes sense.
___
*[pkg/testutils/lint/lint_test.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56574#-MLs1U5gC1AgYFrlnxW4:-MLs1U5gC1AgYFrlnxW5:b-kp7hkw) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd7736b2b798b5723980e3a7dbb4b55a59b6bb0a/pkg/testutils/lint/lint_test.go#L122)):*
> ```Go
> // expense of increased running time.
> func TestLint(t *testing.T) {
> 	crdb := build.Package{Dir: "/home/kena/src/go/src/github.com/cockroachdb/cockroach"}
> ```

Cleanup?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56574)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @DuskEagle, and @joshimhoff)

___
*[pkg/cli/exit/codes.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56574#-MLs2ADA8-H7ePnIW4cc:-MLs463MDSlqUu7jwAAI:b6x5326) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd7736b2b798b5723980e3a7dbb4b55a59b6bb0a/pkg/cli/exit/codes.go#L34)):*
<details><summary><i>Previously, DuskEagle (Joel Kenny) wrote…</i></summary><blockquote>

When I first saw this I wondered why we weren't using exit code 130 for this error (i.e. 128+(SIGINT's signal number)). But after reading a bit more I think using a different error code is justifiable. 130 would be the exit code if the signal directly terminated CockroachDB. But since the signal was handled, even returning exit code 130 would not be the same as exiting due to the INT signal: https://unix.stackexchange.com/a/386856. So using a different exit code makes sense.
</blockquote></details>

Thanks :+1:
___
*[pkg/testutils/lint/lint_test.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56574#-MLs1U5gC1AgYFrlnxW4:-MLs478sAkDbR63U2aBn:b-3eywoa) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd7736b2b798b5723980e3a7dbb4b55a59b6bb0a/pkg/testutils/lint/lint_test.go#L122)):*
<details><summary><i>Previously, DuskEagle (Joel Kenny) wrote…</i></summary><blockquote>

Cleanup?
</blockquote></details>

oops, fixed.

**Comment by knz** [comment]
TFYR but I'll also wait for an additional eye from @bdarnell .

**Review by DuskEagle — COMMENTED** [review]
> Reviewed 13 of 13 files at r2, 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56574)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @DuskEagle, and @joshimhoff)

**Comment by knz** [comment]
@joshimhoff can you figure out whether this actually needs to be back-ported and how far

**Comment by joshimhoff** [comment]
A 20.2 backport would be much appreciated. A 20.1 backport is a nice to have only. If ya don't want to do it e.g. cause it's hard to implement or you have compatibility concerns skip it. We support the latest two major versions in production, so we don't care about earlier versions like 19.2.

**Review by tbg — APPROVED** [review]
> Reviewed 16 of 16 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56574)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @DuskEagle, @joshimhoff, and @knz)

___
*[pkg/testutils/lint/lint_test.go, line 1155 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56574#-MMG2g63D_FwQMV9cuRE:-MMG2g63D_FwQMV9cuRF:b86juuh) ([raw file](https://github.com/cockroachdb/cockroach/blob/42af8472df491ec26b9f6182e6aff39eedaa1d57/pkg/testutils/lint/lint_test.go#L1155)):*
> ```Go
> 			filter,
> 		), func(s string) {
> 			t.Errorf("\n%s <- forbidden; use 'protoutil.Message' instead", s)
> ```

copy pasta

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56574)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @DuskEagle, @joshimhoff, and @tbg)

___
*[pkg/testutils/lint/lint_test.go, line 1155 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56574#-MMG2g63D_FwQMV9cuRE:-MMG4tug-Y-gPz8VwOe0:b9nuvjy) ([raw file](https://github.com/cockroachdb/cockroach/blob/42af8472df491ec26b9f6182e6aff39eedaa1d57/pkg/testutils/lint/lint_test.go#L1155)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

copy pasta
</blockquote></details>

woah nice! good catch.

**Comment by knz** [comment]
I'm taking Tobias' review as a sign from the server team, instead of ben.

bors r=tbg

**Pull request merged**
