### PR TITLE
rowexec: fix the table reader benchmark

### PR DESCRIPTION
**Pull request by yuzefovich**
Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
It was broken yesterday in d8710a0839e3bd72e286a2a046e97c20ee2f6458.

**Review by msirek — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78431#-:-Mywhijv9Fp6qz7OVxOC:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by jlinder** [comment]
I think bors is waiting on the `blathers/release-justification-check` check to be reported. That's why it's not continuing.

**Comment by jlinder** [comment]
I got blathers to run the check (by editing the PR body). Looks like Bors is not adding this PR to a batch. Re-borsing to get bors to pick it up (or tell us what else is wrong).

bors r+

**Comment by jlinder** [comment]
https://github.com/cockroachdb/cockroach/pull/78393 had a similar problem where blathers missed running the release-justification-check. We didn't immediately re-bors that PR to see if bors picks it up within an hour or so. 🤞

**Pull request merged**
