### PR TITLE
cli,backup,import,sql: add cli flag to allow non-admin node-based access

### PR DESCRIPTION
**Pull request by dt**
Typically when running statements like BACKUP, IMPORT, or EXPORT, we
only allow an admin user to direct that operation to interact with some
remote resource that might be reachable only by virtue of being accessed
by the node running the operation.

Specifically, access to s3 or google cloud storage using 'implicit'
auth, which uses the respective SDK methods to use the running machine's
role or machine account, is typically only available to admin users, as
is the ability to specify arbitrary network URIs using http:// or the
custom-endpoint parameters to the other storage providers. This is
because in these cases, the fact that the node is accessing that s3
bucket or network URI may allow a degree of access the user might not
otherwise have, and thus we restrict this to highly trusted admin users.

This change introduces a flag,
--external-io-enable-non-admin-implicit-access, that removes this
restriction, allowing any SQL user who can invoke IMPORT, BACKUP or
EXPORT commands to point those operations at URIs that would otherwise
be restricted to admin-only users as described above. This may be
desirable in an environment where network access is already controlled,
for example at the container level, or where all users, not just admin
users, are trusted enough to have the node make network requests on
their behalf.

Release note (security update): add a new flag --external-io-enable-non-admin-implicit-access
that can remove the admin-only restriction on interacting with arbitrary network endpoint and
using 'implicit' auth in operations such as BACKUP, IMPORT or EXPORT.

### CODE REVIEW

**Review by adityamaru — APPROVED** [review]
Should we add a simple test that creates a non-admin user and runs IMPORT,BACKUP,RESTORE,EXPORT,SHOW using implicit and this flag?

**Review by stevendanna — COMMENTED** [review]
Thanks for jumping on this.  

If we forget this check, we "fail-closed" so in terms of short-term solutions to the customer problem, I think this is a relatively safe one.  It also takes very purposeful action to enable (restarting all of your servers with this flag).

> Should we add a simple test that creates a non-admin user and runs IMPORT,BACKUP,RESTORE,EXPORT,SHOW using implicit and this flag?
 
Agree. A test that the disable-external-io flag takes precedence might be good as well. (Note, I haven't checked what tests are already there.) The long-term maintenance of this feature is likely relatively low if we get these tests in place.

A potential concern to think about as a follow up is that there is (existing and new ) inconsistency between CHANGEFEEDs and these bulk operations. Changefeeds allow arbitrary network access with or without this flag. 

Having these policy checks so spread out in the code makes it a little hard to audit; but I don't think we need to fix that to move forward with this if we get a few tests in place.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71594#-:-Mm2RI1Z7OBcZg3e673U:b6zyq96)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @adityamaru, @dt, and @knz)

___
*[pkg/ccl/backupccl/restore_planning.go, line 1683 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71594#-Mm2RtfT8tX-GE8KxGIC:-Mm2RtfT8tX-GE8KxGID:b6eq1nw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e43e0f1fec94eaebe5985993c565d2bcd4c5332d/pkg/ccl/backupccl/restore_planning.go#L1683)):*
> ```Go
> 	}
> 	knobs := p.ExecCfg().BackupRestoreTestingKnobs
> 	if knobs != nil && knobs.AllowImplicitAccess {
> ```

Interesting that we had already built this testing knob for ourselves.
___
*[pkg/sql/export.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71594#-Mm2W1x6-V2IZLHqvNuT:-Mm2W1x6-V2IZLHqvNuU:b-dsgypm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e43e0f1fec94eaebe5985993c565d2bcd4c5332d/pkg/sql/export.go#L146)):*
> ```Go
> 			panic(pgerror.Newf(
> 				pgcode.InsufficientPrivilege,
> 				"only users with the admin role are allowed to EXPORT to the specified URI"))
> ```

[nit, existing code] other error messages of this form include the provider in the error message.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71594)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @adityamaru, @knz, and @stevendanna)

___
*[pkg/ccl/backupccl/restore_planning.go, line 1683 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71594#-Mm2RtfT8tX-GE8KxGIC:-MmJnDf94at4WHsNdsQg:b-rnchzi) ([raw file](https://github.com/cockroachdb/cockroach/blob/e43e0f1fec94eaebe5985993c565d2bcd4c5332d/pkg/ccl/backupccl/restore_planning.go#L1683)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Interesting that we had already built this testing knob for ourselves.
</blockquote></details>

so this got me thinking, interesting indeed, and perhaps this was suggesting that what we should be doing here is replacing the knob with out flag, which also exercises it in tests. Reworked diff a tiny bit to do that.
___
*[pkg/sql/export.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71594#-Mm2W1x6-V2IZLHqvNuT:-MmKDBST91wd_Y6ykAV_:bcl7cm7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e43e0f1fec94eaebe5985993c565d2bcd4c5332d/pkg/sql/export.go#L146)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

[nit, existing code] other error messages of this form include the provider in the error message.
</blockquote></details>

I think we should leave it as-is if we're backporting in case someone is matching error messages.

**Review by stevendanna — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71594)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @adityamaru, and @knz)

___
*[pkg/ccl/backupccl/restore_planning.go, line 1683 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71594#-Mm2RtfT8tX-GE8KxGIC:-MmUMsKI6TGuYWV8K99Y:b-wdj8zi) ([raw file](https://github.com/cockroachdb/cockroach/blob/e43e0f1fec94eaebe5985993c565d2bcd4c5332d/pkg/ccl/backupccl/restore_planning.go#L1683)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

so this got me thinking, interesting indeed, and perhaps this was suggesting that what we should be doing here is replacing the knob with out flag, which also exercises it in tests. Reworked diff a tiny bit to do that.
</blockquote></details>

Nice, thanks!
___
*[pkg/sql/export.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71594#-Mm2W1x6-V2IZLHqvNuT:-MmUMx_3BTzfbsPwyRnX:b-oz8tym) ([raw file](https://github.com/cockroachdb/cockroach/blob/e43e0f1fec94eaebe5985993c565d2bcd4c5332d/pkg/sql/export.go#L146)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I think we should leave it as-is if we're backporting in case someone is matching error messages.
</blockquote></details>

Good call.

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
