### PR TITLE
roachtest: ignore duplicated events in fingerprint validator

### LINKED ISSUE #87251: roachtest: cdc/mixed-versions failed
roachtest.cdc/mixed-versions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6315043?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6315043?buildTab=artifacts#/cdc/mixed-versions) on master @ [b316a5ed5fe7253d113174d9d95ddebf1143b4e4](https://github.com/cockroachdb/cockroach/commits/b316a5ed5fe7253d113174d9d95ddebf1143b4e4):

```
		fingerprints did not match at 1662012953217966182.0000000000: -7193529376367807878 vs -575912197428535334
		fingerprints did not match at 1662012953318282082.2147483647: -7193529376367807878 vs -575912197428535334
		fingerprints did not match at 1662012953318282083.0000000000: -2377291327688549372 vs -2947884904978010073
		fingerprints did not match at 1662012953418195508.2147483647: -2377291327688549372 vs -2947884904978010073
		fingerprints did not match at 1662012953418195509.0000000000: -2720948113420083189 vs -927396977112245779
		fingerprints did not match at 1662012953517937414.2147483647: -2720948113420083189 vs -927396977112245779
		fingerprints did not match at 1662012953517937415.0000000000: 7475856697260981752 vs 2117337898367763459
		fingerprints did not match at 1662012953617589744.2147483647: 7475856697260981752 vs 2117337898367763459
		fingerprints did not match at 1662012953617589745.0000000000: 1820627787345656057 vs 8899379016680462365
		fingerprints did not match at 1662012953718306485.2147483647: 1820627787345656057 vs 8899379016680462365
		fingerprints did not match at 1662012953718306486.0000000000: -1856891811505264868 vs -4451799070968216272
		fingerprints did not match at 1662012953817943295.2147483647: -1856891811505264868 vs -4451799070968216272
		fingerprints did not match at 1662012953817943296.0000000000: -7890515708225038336 vs -4235160518299549158
		fingerprints did not match at 1662012953918212792.2147483647: -7890515708225038336 vs -4235160518299549158
		fingerprints did not match at 1662012953918212793.0000000000: -1925874997012688649 vs 5743771035771097675
		fingerprints did not match at 1662012954018001281.2147483647: -1925874997012688649 vs 5743771035771097675
		fingerprints did not match at 1662012954018001282.0000000000: -1020645138007226035 vs -3099730575125181541

	cluster.go:1940,cdc.go:1472,cdc.go:1906,mixed_version_cdc.go:114,panic.go:838,test_impl.go:265,mixed_version_cdc.go:252,versionupgrade.go:197,mixed_version_cdc.go:337,mixed_version_cdc.go:58,test_runner.go:897: cluster.RunE: context canceled
		(1) attached stack trace
		  -- stack trace:
		  | main.(*clusterImpl).RunE
		  | 	main/pkg/cmd/roachtest/cluster.go:1957
		  | main.(*clusterImpl).Run
		  | 	main/pkg/cmd/roachtest/cluster.go:1938
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.kafkaManager.stop
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cdc.go:1472
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.setupKafka.func1
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cdc.go:1906
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*cdcMixedVersionTester).Cleanup
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/mixed_version_cdc.go:114
		  | runtime.gopanic
		  | 	GOROOT/src/runtime/panic.go:838
		  | main.(*testImpl).Fatalf
		  | 	main/pkg/cmd/roachtest/test_impl.go:265
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*cdcMixedVersionTester).assertValid.func1
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/mixed_version_cdc.go:252
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*versionUpgradeTest).run
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/versionupgrade.go:197
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.runCDCMixedVersions
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/mixed_version_cdc.go:337
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerCDCMixedVersions.func1
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/mixed_version_cdc.go:58
		  | main.(*testRunner).runTest.func2
		  | 	main/pkg/cmd/roachtest/test_runner.go:897
		  | runtime.goexit
		  | 	GOROOT/src/runtime/asm_amd64.s:1571
		Wraps: (2) cluster.RunE
		Wraps: (3) context canceled
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *errors.errorString
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/mixed-versions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-19236

Epic CRDB-11732

### PR DESCRIPTION
**Pull request by renatolabs**
This commit updates the fingerprint validator (and its use in the
`cdc/mixed-versions` test) to ignore duplicated events received by the
validator.

A previously implicit assumption of the validator is that any events
that it receives are either not duplicated, or -- if they are
duplicated -- they are within the previous resolved timestamp and the
current resolved timestamp. However, that assumption is not justified
by the changefeed guarantees and depends on how frequently `resolved`
events are emitted and how often the changefeed checkpoints.

In the specific case of the `cdc/mixed-versions` roachtest, it was
possible for the changefeed to start from an old checkpoint (older
than the last received `resolved` timestamp), causing it to re-emit
old events that happened way before the previously observed resolved
event. As a consequence, when the validator applies the update
associated with that event, there is a mismatch with state of the
original table as of the update's timestamp, as the fingerprint
validator relies on the fact that updates are applied in order.

To fix the issue, we now skip events that happen before the timestamp
of the previous `resolved` event received. In addition, the caller can
also tell the validator to verify that such out-of-order messages
received by the validator have indeed been previously seen; if not,
that would represent a violation of the changefeed's guarantees.

Fixes: https://github.com/cockroachdb/cockroach/issues/87251.

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
First commit is a slight variation of what I had done in #88961 to remove retries from the validator.

**Review by srosenberg — COMMENTED** [review]
> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89332)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, @samiskin, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/mixed_version_cdc.go` line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89332#-NDfcINM93dTUAbCrM0T:-NDfcINNB8SFwk0Nbf-4:b-vkn4ye) ([raw file](https://github.com/cockroachdb/cockroach/blob/9192ed91dfd1038d4b2881c3e6e483c8e1bf919b/pkg/cmd/roachtest/tests/mixed_version_cdc.go#L228)):*
> ```Go
> 				if m == nil {
> 					t.L().Printf("end of changefeed")
> 					return nil
> ```

This control escape bypasses `close(cmvt.validatorDone)`. Methinks `waitForValidator` would block indefinitely in this case.

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89332)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @samiskin, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/mixed_version_cdc.go` line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89332#-NDfcINM93dTUAbCrM0T:-NDhx3gM0oNgzMBuGJhD:bf7nrsi) ([raw file](https://github.com/cockroachdb/cockroach/blob/9192ed91dfd1038d4b2881c3e6e483c8e1bf919b/pkg/cmd/roachtest/tests/mixed_version_cdc.go#L228)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

This control escape bypasses `close(cmvt.validatorDone)`. Methinks `waitForValidator` would block indefinitely in this case.
</blockquote></details>

`validatorDone` is removed on the second commit. If that error condition did happen, the validator would hang waiting for resolved timestamps and the test would eventually timeout.

Changed the handling of this situation to call `t.Fatal` to fail early and more clearly.

**Review by srosenberg — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89332#-:-NDi1_Um0rf59fEFWgC3:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, @samiskin, and @srosenberg)

___
*[`pkg/ccl/changefeedccl/cdctest/validator.go` line 636 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89332#-NDi-fbnBl7_7oaYiMzH:-NDi-fbo4vhbdFFEru4T:b96pdt3) ([raw file](https://github.com/cockroachdb/cockroach/blob/27b214fcbad64d19f5f075b804a7287748bf3a2f/pkg/ccl/changefeedccl/cdctest/validator.go#L636)):*
> ```Go
> 	}
> 
> 	v.previouslySeen[row.eventKey()] = struct{}{}
> ```

What about duplicates with the same row key? Are those allowed by CDC semantics?
___
*[`pkg/ccl/changefeedccl/cdctest/validator.go` line 649 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89332#-NDi07CREX1lpzDR8lcG:-NDi07CREX1lpzDR8lcH:b-zcx5ao) ([raw file](https://github.com/cockroachdb/cockroach/blob/27b214fcbad64d19f5f075b804a7287748bf3a2f/pkg/ccl/changefeedccl/cdctest/validator.go#L649)):*
> ```Go
> 	}
> 
> 	// row's timestamp is after the last resolved timestam; no problem
> ```

Nit: spelling `timestamp`.
___
*[`pkg/ccl/changefeedccl/cdctest/validator.go` line 657 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89332#-NDi0V2i0NWJg1HZ1jk5:-NDi0V2i0NWJg1HZ1jk6:bg9kuzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/27b214fcbad64d19f5f075b804a7287748bf3a2f/pkg/ccl/changefeedccl/cdctest/validator.go#L657)):*
> ```Go
> 	// hasn't been seen before; that shouldn't happen
> 	if _, seen := v.previouslySeen[row.eventKey()]; !seen {
> 		return fmt.Errorf("unexpected new event at timestamp %s after resolved timestamp %s",
> ```

"unexpected out-of-order event at timestamp..."?
___
*[`pkg/cmd/roachtest/tests/mixed_version_cdc.go` line 54 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89332#-NDi0pl5202Cta6nqf17:-NDi0pl5202Cta6nqf18:b-aie5w3) ([raw file](https://github.com/cockroachdb/cockroach/blob/27b214fcbad64d19f5f075b804a7287748bf3a2f/pkg/cmd/roachtest/tests/mixed_version_cdc.go#L54)):*
> ```Go
> 	// enforcing a maximum number of operations sets a boundary on the
> 	// validator's memory usage
> 	maxOps = 12000
> ```

Do you have a sense of the memory footprint per maxOps? I am mostly just curious why `12000` is a safe value.

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89332)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan, @samiskin, and @srosenberg)

___
*[`pkg/ccl/changefeedccl/cdctest/validator.go` line 636 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89332#-NDi-fbnBl7_7oaYiMzH:-NDiipUv-r7ufVGiEfGd:bhkdfui) ([raw file](https://github.com/cockroachdb/cockroach/blob/27b214fcbad64d19f5f075b804a7287748bf3a2f/pkg/ccl/changefeedccl/cdctest/validator.go#L636)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

What about duplicates with the same row key? Are those allowed by CDC semantics?
</blockquote></details>

In any run there will be multiple updates with the same row key, but with different timestamps. Which is why this event key is a combination of row key and timestamp.
___
*[`pkg/ccl/changefeedccl/cdctest/validator.go` line 649 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89332#-NDi07CREX1lpzDR8lcG:-NDij3Rp3JNRfIcnDE5O:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/27b214fcbad64d19f5f075b804a7287748bf3a2f/pkg/ccl/changefeedccl/cdctest/validator.go#L649)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Nit: spelling `timestamp`.
</blockquote></details>

Fixed.
___
*[`pkg/ccl/changefeedccl/cdctest/validator.go` line 657 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89332#-NDi0V2i0NWJg1HZ1jk5:-NDij4OH9X8v9byqSGxG:bxayja0) ([raw file](https://github.com/cockroachdb/cockroach/blob/27b214fcbad64d19f5f075b804a7287748bf3a2f/pkg/ccl/changefeedccl/cdctest/validator.go#L657)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

"unexpected out-of-order event at timestamp..."?
</blockquote></details>

Updated the error message.
___
*[`pkg/cmd/roachtest/tests/mixed_version_cdc.go` line 54 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89332#-NDi0pl5202Cta6nqf17:-NDij6BK9sWk7TdyDOsR:b-w9qmqt) ([raw file](https://github.com/cockroachdb/cockroach/blob/27b214fcbad64d19f5f075b804a7287748bf3a2f/pkg/cmd/roachtest/tests/mixed_version_cdc.go#L54)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Do you have a sense of the memory footprint per maxOps? I am mostly just curious why `12000` is a safe value.
</blockquote></details>

`12000` was picked for a combination of: 1) workload finishes within the existing 30-minute timeout for the test; and 2) provides enough activity for the validator to see resolved timestamps during the different parts of the upgrade process validated in this test. I updated the comment associated with this constant with this information.

In terms of memory usage: since the workload is performing 12k operations, and each operation should translate to two keys being updated (account being transferred from, and account being transferred to), we should have ~24k entries in the `previouslySeen` map (I validated this in a few runs of the test). I also wrote this benchmark [1] to approximate memory usage of a map of the same size and type of data. TLDR: the map should peak at around 4MB of memory used, which is pretty acceptable IMO.

[1] https://gist.github.com/renatolabs/d6fbe68dd4c367bac1cffa692482c4ff

**Review by srosenberg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89332)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan, @renatolabs, @samiskin, and @srosenberg)

___
*[`pkg/ccl/changefeedccl/cdctest/validator.go` line 636 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89332#-NDi-fbnBl7_7oaYiMzH:-NDinFYhDb4wdfRn6WFx:brzkhs7) ([raw file](https://github.com/cockroachdb/cockroach/blob/27b214fcbad64d19f5f075b804a7287748bf3a2f/pkg/ccl/changefeedccl/cdctest/validator.go#L636)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

In any run there will be multiple updates with the same row key, but with different timestamps. Which is why this event key is a combination of row key and timestamp.
</blockquote></details>

Right, I meant the same (row key, timestamp) tuple seen multiple times; is this valid?
___
*[`pkg/cmd/roachtest/tests/mixed_version_cdc.go` line 54 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89332#-NDi0pl5202Cta6nqf17:-NDingKo7ZhCig2oFbe8:b7rtjv8) ([raw file](https://github.com/cockroachdb/cockroach/blob/27b214fcbad64d19f5f075b804a7287748bf3a2f/pkg/cmd/roachtest/tests/mixed_version_cdc.go#L54)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

`12000` was picked for a combination of: 1) workload finishes within the existing 30-minute timeout for the test; and 2) provides enough activity for the validator to see resolved timestamps during the different parts of the upgrade process validated in this test. I updated the comment associated with this constant with this information.

In terms of memory usage: since the workload is performing 12k operations, and each operation should translate to two keys being updated (account being transferred from, and account being transferred to), we should have ~24k entries in the `previouslySeen` map (I validated this in a few runs of the test). I also wrote this benchmark [1] to approximate memory usage of a map of the same size and type of data. TLDR: the map should peak at around 4MB of memory used, which is pretty acceptable IMO.

[1] https://gist.github.com/renatolabs/d6fbe68dd4c367bac1cffa692482c4ff
</blockquote></details>

Thanks for the clarification and a microbenchmark to estimate the memory footprint!

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89332)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan, @renatolabs, @samiskin, and @srosenberg)

___
*[`pkg/ccl/changefeedccl/cdctest/validator.go` line 636 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89332#-NDi-fbnBl7_7oaYiMzH:-NDiq-Xg6S1JXtc_3bgw:b-r7ee4) ([raw file](https://github.com/cockroachdb/cockroach/blob/27b214fcbad64d19f5f075b804a7287748bf3a2f/pkg/ccl/changefeedccl/cdctest/validator.go#L636)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Right, I meant the same (row key, timestamp) tuple seen multiple times; is this valid?
</blockquote></details>

Yes, it's valid, changefeed's delivery is at-least-once. An "old" event can be received by the client even after multiple later resolved timestamps are received, which is exactly what the validator couldn't handle before this PR.

**Comment by renatolabs** [comment]
bors r=srosenberg

TFTR!

**Pull request merged**
