### PR TITLE
storage: Fix CheckSSTConflicts stats calculations

### LINKED ISSUE #94141: storage: `CheckSSTConflicts` computes incorrect stats for SST range keys
In #94140, I'm adding kvnemesis test coverage of `AddSSTable` ingestion of MVCC range keys. This found a number of problems:

* Conflicting intents are not handled correctly, errors with `checking for key collisions: not at MVCC value`. Fixed in #94395

* The SST and engine iterators get out of sync, errors with `checking for key collisions: expected engine iter to be ahead of sst iter`. Fixed in #94395

* Incorrect MVCC stats calculations. Not fixed yet

To reproduce, check out the branch in #94140 and run e.g.:

```
$ dev test pkg/kv/kvnemesis -f TestKVNemesisSingleNode -v --stress --ignore-cache
=== RUN   TestKVNemesisSingleNode
I221222 15:43:31.221541 1 (gostd) rand.go:199  [-] 1  random seed: -6583167934786910228
    test_log_scope.go:161: test logs captured to: /tmp/test/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/logTestKVNemesisSingleNode1895708328
    test_log_scope.go:79: use -show-logs to present logs inline
    kvnemesis_test.go:179: seed: 7378274295210697597
    kvnemesis_test.go:123: kvnemesis logging to /tmp/test/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/kvnemesis2616062505
    kvnemesis.go:165: error applying x.AddSSTable(ctx, tk(3909762554118877548), tk(18446744073709551615), ... /* @s7 */) // 1221 bytes (as writes)
        // ^-- [tk(7945596544032338278), tk(12435402613537045058)) -> sv(s7): /Table/100/"{6e446df58f9e7166"-ac936cca9ad6fa42"} -> /<empty>
        // ^-- [tk(17786095308637885568), tk(18446744073709551615)) -> sv(s7): /Table/100/"f{6d4e772cc9a5480"-fffffffffffffff"} -> /<empty>: checking for key collisions: expected engine iter to be ahead of sst iter
    kvnemesis.go:185: failures(verbose): /tmp/test/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/kvnemesis2616062505/failures
        repro steps: /tmp/test/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/kvnemesis2616062505/repro.go
        rangefeed KVs: /tmp/test/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/kvnemesis2616062505/kvs-rangefeed.txt
        scan KVs: /tmp/test/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/kvnemesis2616062505/kvs-scan.txt
    kvnemesis_test.go:206: 
        	Error Trace:	/home/erik/.cache/bazel/_bazel_erik/58b8816bb117734f0a0eaaef7fcef95b/sandbox/linux-sandbox/291/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/kv/kvnemesis/kvnemesis_test_/kvnemesis_test.runfiles/com_github_cockroachdb_cockroach/pkg/kv/kvnemesis/kvnemesis_test.go:206
        	            				/home/erik/.cache/bazel/_bazel_erik/58b8816bb117734f0a0eaaef7fcef95b/sandbox/linux-sandbox/291/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/kv/kvnemesis/kvnemesis_test_/kvnemesis_test.runfiles/com_github_cockroachdb_cockroach/pkg/kv/kvnemesis/kvnemesis_test.go:147
        	Error:      	Should be zero, but was 1
        	Test:       	TestKVNemesisSingleNode
        	Messages:   	kvnemesis detected failures
    panic.go:522: -- test log scope end --
test logs left over in: /tmp/test/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/logTestKVNemesisSingleNode1895708328
--- FAIL: TestKVNemesisSingleNode (1.58s)
FAIL
I221222 15:43:32.816153 1 (gostd) testmain.go:100  [-] 1  Test //pkg/kv/kvnemesis:kvnemesis_test exited with error code 1


ERROR: exit status 1

11 runs completed, 1 failures, over 2s
```

Jira issue: CRDB-22707

Epic CRDB-20465

### PR DESCRIPTION
**Pull request by itsbilal**
Previously we were missing some cases of range key overlaps with other range keys, or were too eagerly stepping over engine keys that did not conflict with sstable keys, resulting in incorrect stats. This change adds more targeted test cases to TestEvalAddSSTable to test for those previously-unaccounted cases, and fixes them in CheckSSTConflicts.

Informs #94140 and #98408.
Fixes #94141.

Epic: none

Release note: None

### CODE REVIEW

**Comment by itsbilal** [comment]
I got a couple hundred runs of the updated KVNemesis running successfully after this change. I'll do a longer stress run on Monday to see if something is still missing.

**Review by erikgrinaker — APPROVED** [review]
Nice, thanks. The logic here is too complex to eyeball, so I'll rely on kvnemesis to verify that it's correct.

**Comment by itsbilal** [comment]
Had to do two more fixes before kvnemesis would go into the thousands of runs, and now it seems to chug along well. 🤞

**Comment by itsbilal** [comment]
bors r=erikgrinaker

**Pull request merged**
