### PR TITLE
editing labels to include y-axis name and metric

### LINKED ISSUE #19944: ui: label axes with measure name
After #19870, the byte axes are labeled with the measure name, with units in parentheses.  We should make all the other unit types consistent with this.

### PR DESCRIPTION
**Pull request by dianasaur323**
fixes https://github.com/cockroachdb/cockroach/issues/19944

### CODE REVIEW

**Review by vilterp — APPROVED** [review]
Nice!

**Comment by couchand** [comment]
hey i already did this in  #20737

**Comment by dianasaur323** [comment]
poop how did I not see that? @couchand lmk how you want to proceed?

**Comment by vilterp** [comment]
Whoops, my bad for not catching it either. Missed it in the flurry of PRs you sent out last week! haha

**Comment by dianasaur323** [comment]
serious face palm... sorry about that...

**Pull request merged**
