### PR TITLE
release-2.0: fix gossip tight loopback connection issue and "impossible" assertion

### PR DESCRIPTION
**Pull request by petermattis**
Backport:
  * 2/2 commits from "gossip: infoStore.mostDistant should never return the local node-id" (#29398)
  * 1/1 commits from "gossip: allow receipt of \"loopback infos\"" (#30008)

Please see individual PRs for details.

/cc @cockroachdb/release

### CODE REVIEW

**Review by a-robinson — APPROVED** [review]
LGTM

**Review by bdarnell — APPROVED** [review]

**Comment by petermattis** [comment]
bors r=a-robinson,bdarnell

**Comment by petermattis** [comment]
bors r=a-robinson,bdarnell

**Comment by petermattis** [comment]
bors r=a-robinson,bdarnell

**Comment by petermattis** [comment]
Some sort of teamcity problem with applying the patch for the `acceptance` tests. Trying again.

bors r=a-robinson,bdarnell

**Comment by a-robinson** [comment]
That's been a issue with the 2.0 branch. @benesch told me to just manually merge cherrypicks to release-2.0

**Comment by petermattis** [comment]
> That's been a issue with the 2.0 branch. @benesch told me to just manually merge cherrypicks to release-2.0

The merge button is disabled. @benesch should we disable bors for the release-2.0 branch?

**Pull request merged**
