### PR TITLE
changefeedccl: low-hanging perf work

### PR DESCRIPTION
**Pull request by danhhz**
The first five commits are #26549. See the individual commits for details. Overall improvement:

    name          old time/op    new time/op     delta
    Changefeed-8    11.3ms ± 4%      7.9ms ± 2%  -30.31%  (p=0.008 n=5+5)

    name          old speed      new speed       delta
    Changefeed-8  8.93MB/s ± 4%  12.80MB/s ± 2%  +43.36%  (p=0.008 n=5+5)

    name          old alloc/op   new alloc/op    delta
    Changefeed-8    4.19MB ± 0%     2.45MB ± 0%  -41.46%  (p=0.008 n=5+5)

    name          old allocs/op  new allocs/op   delta
    Changefeed-8     56.2k ± 0%      37.0k ± 0%  -34.20%  (p=0.008 n=5+5)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Reviewed 1 of 4 files at r4, 1 of 2 files at r5, 2 of 2 files at r6, 2 of 2 files at r7.
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/ccl/changefeedccl/changefeed.go, line 108 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/26601#-LEoQvFK5bFZgPE2fnT1:-LEoQvFK5bFZgPE2fnT2:baoh6xe) ([raw file](https://github.com/cockroachdb/cockroach/blob/26de72bd1be493df6525adb89dc2c824d27b8705/pkg/ccl/changefeedccl/changefeed.go#L108)):*
> ```Go
> 		return err
> 	}
> 	defer func() { _ = closeFn() }()
> ```

You don't want to log this error?

---

*[pkg/ccl/changefeedccl/changefeed.go, line 212 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/26601#-LEoS3K96MwCHsCS6W_y:-LEoS3K96MwCHsCS6W_z:b-lpj29x) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcd4b98ba4eaaae43467cb20da1bb56d40caeb4b/pkg/ccl/changefeedccl/changefeed.go#L212)):*
> ```Go
> 	var output []emitRow
> 	var kvs sqlbase.SpanKVFetcher
> 	var scratch bufalloc.ByteAllocator
> ```

Can we ever reset this? Maybe at the beginning of each call to the returned closure?

---

*[pkg/ccl/changefeedccl/changefeed.go, line 243 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/26601#-LEoRiV825ftl8HxqNsb:-LEoRiV9CrHISvFI8iO9:b4hxe19) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcd4b98ba4eaaae43467cb20da1bb56d40caeb4b/pkg/ccl/changefeedccl/changefeed.go#L243)):*
> ```Go
> 				}
> 				var key, value []byte
> 				scratch, key = scratch.Copy(unsafeKey.Key, 0 /* extraCap */)
> ```

Does passing `len(it.UnsafeValue())` as the extra capactity help at all?

---

*[pkg/ccl/changefeedccl/changefeed_test.go, line 273 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/26601#-LEoSK4Z7sZCLEtmY3wM:-LEoSK4Z7sZCLEtmY3wN:bd2l4zx) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcd4b98ba4eaaae43467cb20da1bb56d40caeb4b/pkg/ccl/changefeedccl/changefeed_test.go#L273)):*
> ```Go
> 		closed bool
> 	}
> 	scratch bufalloc.ByteAllocator
> ```

Should this be reset in `testKafkaProducer.Reset`?

---

*[pkg/ccl/changefeedccl/rowfetcher_cache.go, line 85 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/26601#-LEoRPB_0ck1WXjKWaVz:-LEoRPB_0ck1WXjKWaW-:b-p032sj) ([raw file](https://github.com/cockroachdb/cockroach/blob/97cddc20ef09e6fe3766fa95fa613d84c144c49b/pkg/ccl/changefeedccl/rowfetcher_cache.go#L85)):*
> ```Go
> 		return nil, err
> 	}
> 	// TODO(dan): Bound the size of the cache. LRU?
> ```

You can also add that closed notifications will eventually allow us to bound this size more optimally.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26601)*

**Comment by danhhz** [comment]
Thanks for the review! RFAL

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/ccl/changefeedccl/changefeed.go, line 108 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/26601#-LEoQvFK5bFZgPE2fnT1:-LEo_ZR74v2wrTf4DGrH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26de72bd1be493df6525adb89dc2c824d27b8705/pkg/ccl/changefeedccl/changefeed.go#L108)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

You don't want to log this error?
</blockquote></details>

Done.

---

*[pkg/ccl/changefeedccl/changefeed.go, line 212 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/26601#-LEoS3K96MwCHsCS6W_y:-LEo_jkfBnbQzXDd4UO3:blug9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcd4b98ba4eaaae43467cb20da1bb56d40caeb4b/pkg/ccl/changefeedccl/changefeed.go#L212)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we ever reset this? Maybe at the beginning of each call to the returned closure?
</blockquote></details>

ByteAllocator doesn't yet have a Reset method. left this as a todo for now if that's okay (the resulting allocations from not resetting are small compared to json generation)

---

*[pkg/ccl/changefeedccl/changefeed.go, line 243 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/26601#-LEoRiV825ftl8HxqNsb:-LEoa5HU4Nc3SRjsZBcY:burzhs1) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcd4b98ba4eaaae43467cb20da1bb56d40caeb4b/pkg/ccl/changefeedccl/changefeed.go#L243)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does passing `len(it.UnsafeValue())` as the extra capactity help at all?
</blockquote></details>

extra capacity is extra `cap()` on the returned `[]byte` so you can append to it later without causing an allocation, but we don't append to this

---

*[pkg/ccl/changefeedccl/changefeed_test.go, line 273 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/26601#-LEoSK4Z7sZCLEtmY3wM:-LEobSbtBZvhPq_75S_S:b-uum804) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcd4b98ba4eaaae43467cb20da1bb56d40caeb4b/pkg/ccl/changefeedccl/changefeed_test.go#L273)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should this be reset in `testKafkaProducer.Reset`?
</blockquote></details>

also left this one as a TODO

---

*[pkg/ccl/changefeedccl/rowfetcher_cache.go, line 85 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/26601#-LEoRPB_0ck1WXjKWaVz:-LEobUpW5dGyPhpgRtVt:b-30dqv) ([raw file](https://github.com/cockroachdb/cockroach/blob/97cddc20ef09e6fe3766fa95fa613d84c144c49b/pkg/ccl/changefeedccl/rowfetcher_cache.go#L85)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

You can also add that closed notifications will eventually allow us to bound this size more optimally.
</blockquote></details>

Good call. Done (though I think it's resolved notifications, correct?)

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26601#-:-LEodiP63cyUmwpP2y7s:b-6sx6b6)*

**Comment by nvanbenschoten** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/ccl/changefeedccl/changefeed.go, line 212 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/26601#-LEoS3K96MwCHsCS6W_y:-LEoev4v1pJGoo2EM-9j:b8vf6sm) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcd4b98ba4eaaae43467cb20da1bb56d40caeb4b/pkg/ccl/changefeedccl/changefeed.go#L212)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

ByteAllocator doesn't yet have a Reset method. left this as a todo for now if that's okay (the resulting allocations from not resetting are small compared to json generation)
</blockquote></details>

I think reseting is equivalent to setting the ByteAllocator to nil: `scratch = nil`.

---

*[pkg/ccl/changefeedccl/changefeed.go, line 243 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/26601#-LEoRiV825ftl8HxqNsb:-LEofaR73atZvEi23UVd:b-813c4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcd4b98ba4eaaae43467cb20da1bb56d40caeb4b/pkg/ccl/changefeedccl/changefeed.go#L243)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

extra capacity is extra `cap()` on the returned `[]byte` so you can append to it later without causing an allocation, but we don't append to this
</blockquote></details>

Oh ok, I thought it was extra capacity in the returned `scratch` buffer allocator. Never mind!

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26601)*

**Comment by danhhz** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/ccl/changefeedccl/changefeed.go, line 212 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/26601#-LEoS3K96MwCHsCS6W_y:-LEozjT54ogsetne5tas:bvhxqvj) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcd4b98ba4eaaae43467cb20da1bb56d40caeb4b/pkg/ccl/changefeedccl/changefeed.go#L212)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think reseting is equivalent to setting the ByteAllocator to nil: `scratch = nil`.
</blockquote></details>

I don't think that's advantageous. ByteAllocator continually doubles its allocation size as it goes, so resetting it to nil would throw away whatever extra it had and start it from a small size again. The Reset I'm imagining would let it reuse whatever it had already used from the last thing it allocated

---

*[pkg/ccl/changefeedccl/changefeed.go, line 243 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/26601#-LEoRiV825ftl8HxqNsb:-LEp-CTn2kuNSPtIC5A8:brs4ega) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcd4b98ba4eaaae43467cb20da1bb56d40caeb4b/pkg/ccl/changefeedccl/changefeed.go#L243)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Oh ok, I thought it was extra capacity in the returned `scratch` buffer allocator. Never mind!
</blockquote></details>

Yeah, ByteAllocator is pretty specific to its initial use and it just happens to mostly work for what I need here

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26601)*

**Comment by nvanbenschoten** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/ccl/changefeedccl/changefeed.go, line 212 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/26601#-LEoS3K96MwCHsCS6W_y:-LEpLUUo9Sn05vfvFDdc:b-ovrzry) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcd4b98ba4eaaae43467cb20da1bb56d40caeb4b/pkg/ccl/changefeedccl/changefeed.go#L212)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I don't think that's advantageous. ByteAllocator continually doubles its allocation size as it goes, so resetting it to nil would throw away whatever extra it had and start it from a small size again. The Reset I'm imagining would let it reuse whatever it had already used from the last thing it allocated
</blockquote></details>

To accomplish that you could do `scratch  = scratch[:0]`.

I was pretty worried about the capactity of the buffer doubling forever, but I see now that there's a `chunkAllocMaxSize = 16384`, so we don't have to worry about that.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26601)*

**Comment by danhhz** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/ccl/changefeedccl/changefeed.go, line 212 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/26601#-LEoS3K96MwCHsCS6W_y:-LEpSz4q5gDxwnLb3lqn:baiis6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcd4b98ba4eaaae43467cb20da1bb56d40caeb4b/pkg/ccl/changefeedccl/changefeed.go#L212)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

To accomplish that you could do `scratch  = scratch[:0]`.

I was pretty worried about the capactity of the buffer doubling forever, but I see now that there's a `chunkAllocMaxSize = 16384`, so we don't have to worry about that.
</blockquote></details>

That's work! Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26601)*

**Comment by danhhz** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/ccl/changefeedccl/changefeed.go, line 212 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/26601#-LEoS3K96MwCHsCS6W_y:-LEpVLd-0SKFJ2G2x0cQ:b-rjguid) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcd4b98ba4eaaae43467cb20da1bb56d40caeb4b/pkg/ccl/changefeedccl/changefeed.go#L212)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

That's work! Done
</blockquote></details>

*That will work

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26601)*

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26601#-:-LEqIZHy1L5CdKPYH_bG:bnfp4nl)*

**Comment by danhhz** [comment]
TFTR!

bors r=nvanbenschoten

**Pull request merged**
