### PR TITLE
roachtest: use default server.time_after_store_suspect in perturbation

### PR DESCRIPTION
**Pull request by kvoli**
Previously, `server.time_after_store_suspect` was set to 10s, down from
the default of 30s in `perturbation` roachtests. It is uncommon for
users to alter this cluster setting, let alone decrease it.

Restore the default setting value, 30s.

Part of: https://github.com/cockroachdb/cockroach/issues/132615
Release note: None

### CODE REVIEW

**Review by andrewbaptist — APPROVED** [review]
:lgtm:

I'm glad you left the TODO as hopefully we can change the default to be something lower once we have pull mode.

**Review by arulajmani — APPROVED** [review]

**Comment by kvoli** [comment]
TYFTR!

bors r=andrewbaptist,arulajmani

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132759#-:-O9ew3YzDwOlgouZlgrY:bg7igkv)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @DarrylWong, @nvanbenschoten, and @vidit-bhat)

**Comment by kvoli** [comment]
TYFTR!

rebased.

**Comment by kvoli** [comment]
blathers backport 24.3

**Pull request merged**
