### PR TITLE
sql: A couple of small SQL cleanup commits

### PR DESCRIPTION
**Pull request by ajstorm**
A couple of small commits:

- Added more human-readable formatting to SHOW CREATE TABLE when run on a
view.
- Cleaned up the hint for PLACEMENT RESTRICTED to make it more actionable

See individual commits for more details.

### CODE REVIEW

**Review by otan — COMMENTED** [review]
i know you didn't ask for a review, but i looked anyway!

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71315)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[pkg/sql/alter_database.go, line 1121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71315#-MlV6vm010wwGQVNdLX9-r2-1121:-MlrCOCg2185jA2zU3Cf:b-q2rea1) ([raw file](https://github.com/cockroachdb/cockroach/blob/824e87b568569f49058bfcb87726f94901dea3d0/pkg/sql/alter_database.go#L1121)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nuh gotta leave the cluster setting in there >:D i'd just add the RESET SESSION setting, and append that to all other places needing this hint
</blockquote></details>

:-/ 

Are there compelling cases where we think customers will want to set the cluster setting?  I'd think in almost all cases, you'd want to set the session setting, alter the database, and be done with it forever.  Furthermore, if the variable is meant to provide protection against misuse, doesn't the cluster setting go against that ethos?
___
*[pkg/sql/show_create_clauses.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71315#-MlV6vm-6wzO1F0QOp14-r1-105:-MlrCkaADueo8qiPhRVw:btg6tnt) ([raw file](https://github.com/cockroachdb/cockroach/blob/823e357ba0fe576005e37f74345d6db33bed6483/pkg/sql/show_create_clauses.go#L105)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i think you want this:

```
if i > 0 {
   f.WriteString(",")
}
f.WriteString("\n\t") // otherwise you get CREATE VIEW v(blah blah,\n\t, but you probably want a new line before blah blah.
```
</blockquote></details>

Took your advice but also adding a bit more subtlety.  I don't think we want single column views to print on multiple lines (because they look kinda gross that way).  Have a look and let me know what you think.
___
*[pkg/sql/show_test.go, line 335 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71315#-MllzJXKACJ2pGVo_BPR-r3-335:-MlrD3WZDkHoNF5U19m7:b-taq6gs) ([raw file](https://github.com/cockroachdb/cockroach/blob/31d46983e0854f2bd6cdee872ef90b6fd10048a2/pkg/sql/show_test.go#L335)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

do we want a new line after this ending bracket? 
is this view ... too sparse?
</blockquote></details>

I'm fine with it AS-is, but is there some precedent we can use to break the tie?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71315)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @rafiss)

___
*[pkg/sql/alter_database.go, line 1121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71315#-MlV6vm010wwGQVNdLX9-r2-1121:-Mlrt8Kc9CmI00yyvOcz:b5wcrgd) ([raw file](https://github.com/cockroachdb/cockroach/blob/824e87b568569f49058bfcb87726f94901dea3d0/pkg/sql/alter_database.go#L1121)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

:-/ 

Are there compelling cases where we think customers will want to set the cluster setting?  I'd think in almost all cases, you'd want to set the session setting, alter the database, and be done with it forever.  Furthermore, if the variable is meant to provide protection against misuse, doesn't the cluster setting go against that ethos?
</blockquote></details>

eh, i can imagine people wanting it on always. up to you in the end.
___
*[pkg/sql/show_create_clauses.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71315#-MlV6vm-6wzO1F0QOp14-r1-105:-Mlrtu7F8gUau4gadzF1:b-6zdg15) ([raw file](https://github.com/cockroachdb/cockroach/blob/823e357ba0fe576005e37f74345d6db33bed6483/pkg/sql/show_create_clauses.go#L105)):*
>  "hello,hello"
___
*[pkg/sql/show_create_clauses.go, line 136 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71315#-MlrtdjA7y52jMDsuScl:-MlrtdjA7y52jMDsuScm:b-9gx2q8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a170d7cd16e962bcdfcee7156550236cc3db4fb5/pkg/sql/show_create_clauses.go#L136)):*
> ```Go
> 		// Pretty things up a bit more by adding new lines after each column.
> 		sequenceReplacedViewQuery = strings.Replace(
> 			sequenceReplacedViewQuery, ", ", ",\n\t\t", -1)
> ```

What happens if i name a column something like

```
root@127.0.0.1:5436/defaultdb> create table tt ("hello, adam" int);
CREATE TABLE
```

and create a view? I think this needs some escaping. Probably better to do it in the loop.
___
*[pkg/sql/show_test.go, line 335 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71315#-MllzJXKACJ2pGVo_BPR-r3-335:-MlrtTfUCDyFazMbIa8T:b-572wj8) ([raw file](https://github.com/cockroachdb/cockroach/blob/31d46983e0854f2bd6cdee872ef90b6fd10048a2/pkg/sql/show_test.go#L335)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

I'm fine with it AS-is, but is there some precedent we can use to break the tie?
</blockquote></details>

SHOW CREATE TABLE is always new lined at the end.

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71315)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @otan, and @rafiss)

___
*[pkg/sql/show_create_clauses.go, line 136 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71315#-MlrtdjA7y52jMDsuScl:-MmYPCVoC30yIE11LEJ4:b-yzg8jl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a170d7cd16e962bcdfcee7156550236cc3db4fb5/pkg/sql/show_create_clauses.go#L136)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

What happens if i name a column something like

```
root@127.0.0.1:5436/defaultdb> create table tt ("hello, adam" int);
CREATE TABLE
```

and create a view? I think this needs some escaping. Probably better to do it in the loop.
</blockquote></details>

I'm starting to think that maybe I should just close this PR.  Getting this to perfect isn't going to be simple because there's no loop above that handles this (it leverages the existing `viewQuery` string in the table descriptor), so it seems to imply writing a DDL parser here (or calling back into our own DDL parser somehow).  Either way, probably not worth the effort for an issue we've had to deal with forever and no users seem to be complaining about.  Please let me know if you disagree.

**Pull request closed without merging**
