### PR TITLE
DOC-3056: Updated SQL diagrams to match 22.1 HSI updates

### PR DESCRIPTION
**Pull request by nickvigilante**
Updated hash-sharded index related diagrams to use storage parameters

Release note: None

### CODE REVIEW

**Comment by nickvigilante** [comment]
Related to https://github.com/cockroachdb/docs/pull/13250.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79082)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nickvigilante)

___
*[docs/generated/sql/bnf/alter_primary_key.bnf, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79082#-Mzoqcud93CRLtak3bmr:-Mzoqcue5QAq-QFrMSQ1:bpg62fu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c30f74ab80204157c5a44923c209822a3bca5c33/docs/generated/sql/bnf/alter_primary_key.bnf#L4)):*
> ```
> 	'ALTER' 'TABLE' table_name 'ALTER' 'PRIMARY' 'KEY' 'USING' 'COLUMNS' '(' index_params ')' 'USING' 'HASH'  opt_with_storage_parameter_list
> 	| 'ALTER' 'TABLE' table_name 'ALTER' 'PRIMARY' 'KEY' 'USING' 'COLUMNS' '(' index_params ')'  opt_with_storage_parameter_list
> 	| 'ALTER' 'TABLE' 'IF' 'EXISTS' table_name 'ALTER' 'PRIMARY' 'KEY' 'USING' 'COLUMNS' '(' index_params ')' 'USING' 'HASH'  opt_with_storage_parameter_list
> ```

nit: does the extra space hurt here in any way?
___
*[docs/generated/sql/bnf/col_qualification.bnf, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79082#-MzoqfKs3Mds7QfrXoGy:-MzoqfKs3Mds7QfrXoGz:bpg62fu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c30f74ab80204157c5a44923c209822a3bca5c33/docs/generated/sql/bnf/col_qualification.bnf#L7)):*
> ```
> 	| 'CONSTRAINT' constraint_name 'UNIQUE'
> 	| 'CONSTRAINT' constraint_name 'PRIMARY' 'KEY' opt_with_storage_parameter_list
> 	| 'CONSTRAINT' constraint_name 'PRIMARY' 'KEY' 'USING' 'HASH'  opt_with_storage_parameter_list
> ```

nit: does the extra space hurt here in any way?
___
*[docs/generated/sql/bnf/col_qualification.bnf, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79082#-Mzoqfhx-0oNoxK8H-60:-Mzoqfhx-0oNoxK8H-61:bpg62fu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c30f74ab80204157c5a44923c209822a3bca5c33/docs/generated/sql/bnf/col_qualification.bnf#L23)):*
> ```
> 	| 'UNIQUE'
> 	| 'PRIMARY' 'KEY' opt_with_storage_parameter_list
> 	| 'PRIMARY' 'KEY' 'USING' 'HASH'  opt_with_storage_parameter_list
> ```

nit: does the extra space hurt here in any way?
___
*[docs/generated/sql/bnf/index_def.bnf, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79082#-Mzoqp6S17YZVMX3uWFl:-Mzoqp6S17YZVMX3uWFm:bpg62fu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c30f74ab80204157c5a44923c209822a3bca5c33/docs/generated/sql/bnf/index_def.bnf#L5)):*
> ```
> 	| 'INDEX' opt_index_name '(' index_elem ( ( ',' index_elem ) )* ')' 'USING' 'HASH'  'STORING' '(' name_list ')' opt_partition_by_index opt_with_storage_parameter_list opt_where_clause
> 	| 'INDEX' opt_index_name '(' index_elem ( ( ',' index_elem ) )* ')' 'USING' 'HASH'  'INCLUDE' '(' name_list ')' opt_partition_by_index opt_with_storage_parameter_list opt_where_clause
> 	| 'INDEX' opt_index_name '(' index_elem ( ( ',' index_elem ) )* ')' 'USING' 'HASH'   opt_partition_by_index opt_with_storage_parameter_list opt_where_clause
> ```

nit: does the extra space hurt here in any way?



_Code quote:_
```
	'INDEX' opt_index_name '(' index_elem ( ( ',' index_elem ) )* ')' 'USING' 'HASH'  'COVERING' '(' name_list ')' opt_partition_by_index opt_with_storage_parameter_list opt_where_clause
	| 'INDEX' opt_index_name '(' index_elem ( ( ',' index_elem ) )* ')' 'USING' 'HASH'  'STORING' '(' name_list ')' opt_partition_by_index opt_with_storage_parameter_list opt_where_clause
	| 'INDEX' opt_index_name '(' index_elem ( ( ',' index_elem ) )* ')' 'USING' 'HASH'  'INCLUDE' '(' name_list ')' opt_partition_by_index opt_with_storage_parameter_list opt_where_clause
	| 'INDEX' opt_index_name '(' index_elem ( ( ',' index_elem ) )* ')' 'USING' 'HASH'   opt_partition_by_index opt_with_storage_parameter_list opt_where_clause
```
___
*[docs/generated/sql/bnf/index_def.bnf, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79082#-Mzoqpyi7b9Qfap5r_rM:-Mzoqpyi7b9Qfap5r_rN:bpg62fu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c30f74ab80204157c5a44923c209822a3bca5c33/docs/generated/sql/bnf/index_def.bnf#L13)):*
> ```
> 	| 'UNIQUE' 'INDEX' opt_index_name '(' index_elem ( ( ',' index_elem ) )* ')' 'USING' 'HASH'  'STORING' '(' name_list ')' opt_partition_by_index opt_with_storage_parameter_list opt_where_clause
> 	| 'UNIQUE' 'INDEX' opt_index_name '(' index_elem ( ( ',' index_elem ) )* ')' 'USING' 'HASH'  'INCLUDE' '(' name_list ')' opt_partition_by_index opt_with_storage_parameter_list opt_where_clause
> 	| 'UNIQUE' 'INDEX' opt_index_name '(' index_elem ( ( ',' index_elem ) )* ')' 'USING' 'HASH'   opt_partition_by_index opt_with_storage_parameter_list opt_where_clause
> ```

nit: does the extra space hurt here in any way?



_Code quote:_
```
	| 'UNIQUE' 'INDEX' opt_index_name '(' index_elem ( ( ',' index_elem ) )* ')' 'USING' 'HASH'  'COVERING' '(' name_list ')' opt_partition_by_index opt_with_storage_parameter_list opt_where_clause
	| 'UNIQUE' 'INDEX' opt_index_name '(' index_elem ( ( ',' index_elem ) )* ')' 'USING' 'HASH'  'STORING' '(' name_list ')' opt_partition_by_index opt_with_storage_parameter_list opt_where_clause
	| 'UNIQUE' 'INDEX' opt_index_name '(' index_elem ( ( ',' index_elem ) )* ')' 'USING' 'HASH'  'INCLUDE' '(' name_list ')' opt_partition_by_index opt_with_storage_parameter_list opt_where_clause
	| 'UNIQUE' 'INDEX' opt_index_name '(' index_elem ( ( ',' index_elem ) )* ')' 'USING' 'HASH'   opt_partition_by_index opt_with_storage_parameter_list opt_where_clause
```
___
*[docs/generated/sql/bnf/table_constraint.bnf, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79082#-MzoqqsC8sE_OEJGq36O:-MzoqqsC8sE_OEJGq36P:bpg62fu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c30f74ab80204157c5a44923c209822a3bca5c33/docs/generated/sql/bnf/table_constraint.bnf#L7)):*
> ```
> 	| 'CONSTRAINT' constraint_name 'UNIQUE' '(' index_params ')' 'INCLUDE' '(' name_list ')' opt_partition_by_index opt_where_clause
> 	| 'CONSTRAINT' constraint_name 'UNIQUE' '(' index_params ')'  opt_partition_by_index opt_where_clause
> 	| 'CONSTRAINT' constraint_name 'PRIMARY' 'KEY' '(' index_params ')' 'USING' 'HASH'  opt_with_storage_parameter_list
> ```

nit: does the extra space hurt here in any way?
___
*[docs/generated/sql/bnf/table_constraint.bnf, line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79082#-MzoqrJpABNz6kRKA7GH:-MzoqrJpABNz6kRKA7GI:bpg62fu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c30f74ab80204157c5a44923c209822a3bca5c33/docs/generated/sql/bnf/table_constraint.bnf#L15)):*
> ```
> 	| 'UNIQUE' '(' index_params ')' 'INCLUDE' '(' name_list ')' opt_partition_by_index opt_where_clause
> 	| 'UNIQUE' '(' index_params ')'  opt_partition_by_index opt_where_clause
> 	| 'PRIMARY' 'KEY' '(' index_params ')' 'USING' 'HASH'  opt_with_storage_parameter_list
> ```

nit: does the extra space hurt here in any way?
___
*[pkg/cmd/docgen/diagrams.go, line 395 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79082#-MzoqtJnCNe71d0QpvRf:-MzoqtJnCNe71d0QpvRg:bd9ywr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c30f74ab80204157c5a44923c209822a3bca5c33/pkg/cmd/docgen/diagrams.go#L395)):*
> ```Go
> 		inline: []string{"alter_table_cmds", "alter_table_cmd", "opt_hash_sharded"},
> 		regreplace: map[string]string{
> 			"opt_hash_sharded_bucket_count": "",
> ```

maybe add an optional space here and below

**Review by nickvigilante — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79082)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[docs/generated/sql/bnf/alter_primary_key.bnf, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79082#-Mzoqcud93CRLtak3bmr:-Mzp0omn-mP9dHI-I6N0:b-w6t2sa) ([raw file](https://github.com/cockroachdb/cockroach/blob/c30f74ab80204157c5a44923c209822a3bca5c33/docs/generated/sql/bnf/alter_primary_key.bnf#L4)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: does the extra space hurt here in any way?
</blockquote></details>

I don't believe so, but I'll update diagrams.go to remove it.
___
*[docs/generated/sql/bnf/col_qualification.bnf, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79082#-MzoqfKs3Mds7QfrXoGy:-Mzp0dPb7m-8lW1DLqmf:b-w6t2sa) ([raw file](https://github.com/cockroachdb/cockroach/blob/c30f74ab80204157c5a44923c209822a3bca5c33/docs/generated/sql/bnf/col_qualification.bnf#L7)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: does the extra space hurt here in any way?
</blockquote></details>

I don't believe so, but I'll update diagrams.go to remove it.
___
*[docs/generated/sql/bnf/col_qualification.bnf, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79082#-Mzoqfhx-0oNoxK8H-60:-Mzp0ecU7aqQZ8yt5LVf:b-w6t2sa) ([raw file](https://github.com/cockroachdb/cockroach/blob/c30f74ab80204157c5a44923c209822a3bca5c33/docs/generated/sql/bnf/col_qualification.bnf#L23)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: does the extra space hurt here in any way?
</blockquote></details>

I don't believe so, but I'll update diagrams.go to remove it.
___
*[docs/generated/sql/bnf/index_def.bnf, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79082#-Mzoqp6S17YZVMX3uWFl:-Mzp0fRe2etNPpU7VRMz:b-w6t2sa) ([raw file](https://github.com/cockroachdb/cockroach/blob/c30f74ab80204157c5a44923c209822a3bca5c33/docs/generated/sql/bnf/index_def.bnf#L5)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: does the extra space hurt here in any way?
</blockquote></details>

I don't believe so, but I'll update diagrams.go to remove it.
___
*[docs/generated/sql/bnf/index_def.bnf, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79082#-Mzoqpyi7b9Qfap5r_rM:-Mzp0gJrA3gVjCmuG6Ck:b-w6t2sa) ([raw file](https://github.com/cockroachdb/cockroach/blob/c30f74ab80204157c5a44923c209822a3bca5c33/docs/generated/sql/bnf/index_def.bnf#L13)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: does the extra space hurt here in any way?
</blockquote></details>

I don't believe so, but I'll update diagrams.go to remove it.
___
*[docs/generated/sql/bnf/table_constraint.bnf, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79082#-MzoqqsC8sE_OEJGq36O:-Mzp0h02EgA3G3kGDX2s:b-w6t2sa) ([raw file](https://github.com/cockroachdb/cockroach/blob/c30f74ab80204157c5a44923c209822a3bca5c33/docs/generated/sql/bnf/table_constraint.bnf#L7)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: does the extra space hurt here in any way?
</blockquote></details>

I don't believe so, but I'll update diagrams.go to remove it.
___
*[docs/generated/sql/bnf/table_constraint.bnf, line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79082#-MzoqrJpABNz6kRKA7GH:-Mzp0hNX4y3hsPY_y3Oi:b-w6t2sa) ([raw file](https://github.com/cockroachdb/cockroach/blob/c30f74ab80204157c5a44923c209822a3bca5c33/docs/generated/sql/bnf/table_constraint.bnf#L15)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: does the extra space hurt here in any way?
</blockquote></details>

I don't believe so, but I'll update diagrams.go to remove it.
___
*[pkg/cmd/docgen/diagrams.go, line 395 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79082#-MzoqtJnCNe71d0QpvRf:-Mzp0nf23zur0sQKAgQv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c30f74ab80204157c5a44923c209822a3bca5c33/pkg/cmd/docgen/diagrams.go#L395)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

maybe add an optional space here and below
</blockquote></details>

Done.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79082#-:-N-PBelDErslxaDKLOrf:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nickvigilante)

**Pull request merged**
