### PR TITLE
opt: index accelerate `<tuple> = ANY(ARRAY[<tuple>, ...])`

### LINKED ISSUE #77364: Optimizer doesn't have a rule to recognize `IN` and `arrays in use` patterns
**Is your feature request related to a problem? Please describe.**
The optimizer doesn't have a rule to recognize `IN` and `arrays in use` patterns so users have to manually rewrite the pattern.

**Describe the solution you'd like**
Optimizer is able to recognize  `IN` and `arrays in use` 

**Describe alternatives you've considered**
Manually rewriting the pattern

**Additional context**
This shows the issue where the optimizer knows how to decode the statement but does optimize properly. This works in Postgres. The optimizer does know how to break it down and run it, but it needs to apply the optimization logic after it expands the array.

```root@:26257/defaultdb> EXPLAIN
select *
from arraypred
where (id1, id2) = any(array[(1, 10), (2, 20), (3, 30)]);

info
distribution: full
vectorized: true

• filter
│ estimated row count: 300,000
│ filter: (id1, id2) IN ((1, 10), (2, 20), (3, 30))
│
└── • scan
estimated row count: 900,000 (100% of the table; stats collected 4 minutes ago)
table: arraypred@primary
spans: FULL SCAN
(11 rows)

Time: 1ms total (execution 1ms / network 0ms)

root@:26257/defaultdb> EXPLAIN
select *
from arraypred
where (id1, id2) IN ((1, 10), (2, 20), (3, 30));

info
distribution: local
vectorized: true

• scan
estimated row count: 3 (<0.01% of the table; stats collected 9 minutes ago)
table: arraypred@primary
spans: [/1/10 - /1/10] [/2/20 - /2/20] [/3/30 - /3/30]
(7 rows)

Time: 1ms total (execution 1ms / network 0ms)
```

### PR DESCRIPTION
**Pull request by mgartner**
Previously, queries with filters of the form
`<tuple> = ANY(ARRAY[<tuple>, ...])` with constant tuples on the
right-hand side were not index accelerated. The normalization rules
`SimplifyAnyScalarArray` and `SimplifyEqualsAnyTuple` transform this
type of expression to an expression in the form
`<tuple> IN (<tuple>, ...)`, with the tuples on the right-hand side
represented as `ConstExpr`s. Because the constraint builder requires
tuples on the RHS of `IN` expressions to be `TupleExpr`s, not
`ConstExpr`s, no constraints could be generated for the normalized form
of the expression. Without constraints, exploration rules could not
generate constrained scans.

The normalization rules that perform the conversion to an `IN`
expression now convert `DTuple`s to `TupleExpr`s, allowing constraints
to be built for the `IN` expression, and enabling index acceleration.

I considered updating the constraint builder so that it can build
constraints when there are `DTuple`s on the RHS of `IN` expressions, but
it would be a more involved change. The changes here seem more likely to
be backported to a previous version. I've left a TODO as a reminder that
the best fix might be to improve the constraint builder.

Fixes #77364

Release note (performance improvement): Queries with filters containing
tuples in `= ANY` expressions, such as
`(a, b) = ANY(ARRAY[(1, 10), (2, 20)])`, are now index accelerated.

### CODE REVIEW

**Comment by mgartner** [comment]
I think this is safe to backport to 22.1 after some baking period, so I'm adding the backport label. Let me know if you disagree.

**Review by msirek — APPROVED** [review]
Great catch and fix!  I'm wondering how you found this, and if we should do more testing with ARRAY.
:lgtm: 

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82616#-:-N4BIYzU071H_-sawkgH:bk5577f)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`-- commits` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82616#-N4BEm2xACUX38j02Clf):*
nit: generated --> generate
___
*[`-- commits` line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82616#-N4BEuux666UfuyU23Mu):*
nit: build --> built

**Review by mgartner — COMMENTED** [review]
> I'm wondering how you found this, and if we should do more testing with ARRAY.

The issue was reported in #77364.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82616#-:-N4TfhGw7p3xAB2VlW0a:by2akbj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`-- commits` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82616#-N4BEm2xACUX38j02Clf):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

nit: generated --> generate
</blockquote></details>

Done.
___
*[`-- commits` line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82616#-N4BEuux666UfuyU23Mu):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

nit: build --> built
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm: I agree this should be backportable

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82616#-:-N5Ae-Tz79DWu5mupZVT:basog6y)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[`pkg/sql/opt/norm/scalar_funcs.go` line 232 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82616#-N5AdVKpERaJCiYfsEpx:-N5AdVKpERaJCiYfsEpy:bvcjp17) ([raw file](https://github.com/cockroachdb/cockroach/blob/e611be161f29cfd5e05524a2761127631a722414/pkg/sql/opt/norm/scalar_funcs.go#L232)):*
> ```Go
> 				exprs[i] = c.f.ConstructConstVal(t.D[i], typs[i])
> 			}
> 			elems[i] = c.f.ConstructTuple(exprs, t.ResolvedType())
> ```

nit: `t.ResolvedType()` can be `typ`

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82616)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @msirek and @rytaft)

___
*[`pkg/sql/opt/norm/scalar_funcs.go` line 232 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82616#-N5AdVKpERaJCiYfsEpx:-N5Ah-Vx9mcB-4I42ohx:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e611be161f29cfd5e05524a2761127631a722414/pkg/sql/opt/norm/scalar_funcs.go#L232)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: `t.ResolvedType()` can be `typ`
</blockquote></details>

Fixed.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82616)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
