### PR TITLE
backupccl,cloudimpl: implement vfs.File on for remote files, iterate them directly

### PR DESCRIPTION
**Pull request by dt**
This change adds an implementation of vfs.File backed by the `ReadFileAt` method 
of an ExternalStorage, the can be used for opening remote SSTs for iteration by
sstable.NewReader.

The second commit switches the restore processor to use the new wrapper
added in the first commit. This allows RESTORE to directly open and iterate remote files, without
first downloading them entirely to memory and iterating an in-memory “file”.

For now, verifying the SHA512 checksum still requires downloading the
entire file, so files are downloaded twice: once to stream (entirely and in-order)
through checksum computation and then once to stream (potentially partially
or our of order) to RESTORE ingest iteration. A future change could improve this,
either with caching small files in their entirety when memory allows and/or by
potentially skipping the file-level SHA512 checksums entirely, as SSTs maintain
their own block-level checksums.

Note: if a file is encrypted, it currently *must* be downloaded in its entirety
to be decrypted, as current encryption scheme seals the entire file as one message
with a single HMAC at its end, meaning the whole message must be read before any
of it can be authenticated and acted on. A chunked encoding such as #58181 could
avoid this.

Release note: none.

### CODE REVIEW

**Review by miretskiy — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58400)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/ccl/backupccl/restore_data_processor.go, line 196 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58400#-MQ9WLYT-wFMRPmTEllV:-MQ9WLYT-wFMRPmTEllW:bbs6kzy) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce6ae2dfa6f8640c430b9544f305dcdf53f34fee/pkg/ccl/backupccl/restore_data_processor.go#L196)):*
> ```Go
> 		}
> 	}()
> ```

I'm not a huge fan of this defer -- it's rather complex to keep track of what's going on, and I'm not sure it's needed at all.  I think a bit of refactoring can do wonders:

```
  func openVfsFile(...) (vfs.File, error) {
 		if err := retry.WithMaxAttempts(ctx, base.DefaultRetryOptions(), maxAttempts, func() error {
			var err error
			f, err = cloudimpl.NewFileWrapper(ctx, dir, file.Path)
           ....
  }

  func decryptIfNeeded(f vfs.File) (vfs.File, error) {
    if rd.spec.Encryption != nil {
      ...
    }
  }

```

Then, the loop below has a natural flow, with simple error handling:
```

for _, file := range entry.Files {
   f, err := openVfsFile()
   if err != nil {
      return err
   }
   f, err = decryptIfNeeded(f)
   if err != nil {
     ...
   }
   rest of the code.
```
___
*[pkg/storage/sst_iterator.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58400#-MQ9V0219XF_zjOtwN-1:-MQ9V0219XF_zjOtwN-2:b149c7t) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce6ae2dfa6f8640c430b9544f305dcdf53f34fee/pkg/storage/sst_iterator.go#L42)):*
> ```Go
> // Pebble's `sstable.Writer`, and assumes the keys use Cockroach's MVCC
> // format.
> func NewFileSSTIterator(path string) (SimpleMVCCIterator, error) {
> ```

I'm quite surprised this is used from so few places.  Maybe just keep the name as is anyway?
Call the new method with the NewFileSSTIterator?
___
*[pkg/storage/cloudimpl/external_storage.go, line 563 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58400#-MQ9TFHr-d6iMXNQ_qZu:-MQ9TFHr-d6iMXNQ_qZv:bliyxhv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b473677a0489e11e77f8f2f3e2d95e772cdfa596/pkg/storage/cloudimpl/external_storage.go#L563)):*
> ```Go
> // from it. Note: contrary to io.ReaderAt, ReadAt does *not* support parallel
> // calls and `Read` should not be called on a wrapper on which ReadAt is
> // also called, as ReadAt does reposition the underlying reader when called.
> ```

I understand why you have this comment here.  I'm not sure this would be safe though.
Even if there is a single reader (e.g. an iterator), how the data is read depends on the iterator implementation.  I mean, it's perfectly reasonable to say, read the header, then readAt to read the footer, then go back to readAt (after header), and then continue regular reads.

The unfortunate reality is that vfs file mixes 2 different concepts: a file type object (read) and a file descriptor based one (readAt).

Would it be safer to just forego any sort of optimization attempts at this stage, and simply read requested range?

We could address inefficiencies in that approach later, but at least we will satisfy interface correctly...
___
*[pkg/storage/cloudimpl/external_storage.go, line 596 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58400#-MQ9U4f4CrJgjIpBsotP:-MQ9U4f4CrJgjIpBsotQ:b-qxlqv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b473677a0489e11e77f8f2f3e2d95e772cdfa596/pkg/storage/cloudimpl/external_storage.go#L596)):*
> ```Go
> func (sizeStat) ModTime() time.Time { panic("unimplemented") }
> func (sizeStat) Mode() os.FileMode  { panic("unimplemented") }
> func (sizeStat) Name() string       { panic("unimplemented") }
> ```

I think we can extend sizeStat to propagate name.
We can also implement isDir (false), Mode (0644).  And I'd prefer to even return time{} as modtime.
___
*[pkg/storage/cloudimpl/external_storage.go, line 597 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58400#-MQ9U1KU1toycLDqmpvR:-MQ9U1KU1toycLDqmpvS:b-ex00q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b473677a0489e11e77f8f2f3e2d95e772cdfa596/pkg/storage/cloudimpl/external_storage.go#L597)):*
> ```Go
> func (sizeStat) Mode() os.FileMode  { panic("unimplemented") }
> func (sizeStat) Name() string       { panic("unimplemented") }
> func (sizeStat) Sys() interface{}   { panic("unimplemented") }
> ```

I think we should return nil here -- it's allowed by api.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58400)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[pkg/ccl/backupccl/restore_data_processor.go, line 196 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58400#-MQ9WLYT-wFMRPmTEllV:-MQ9aGHK4N1V7ADLwxPM:b-70nvr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce6ae2dfa6f8640c430b9544f305dcdf53f34fee/pkg/ccl/backupccl/restore_data_processor.go#L196)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I'm not a huge fan of this defer -- it's rather complex to keep track of what's going on, and I'm not sure it's needed at all.  I think a bit of refactoring can do wonders:

```
  func openVfsFile(...) (vfs.File, error) {
 		if err := retry.WithMaxAttempts(ctx, base.DefaultRetryOptions(), maxAttempts, func() error {
			var err error
			f, err = cloudimpl.NewFileWrapper(ctx, dir, file.Path)
           ....
  }

  func decryptIfNeeded(f vfs.File) (vfs.File, error) {
    if rd.spec.Encryption != nil {
      ...
    }
  }

```

Then, the loop below has a natural flow, with simple error handling:
```

for _, file := range entry.Files {
   f, err := openVfsFile()
   if err != nil {
      return err
   }
   f, err = decryptIfNeeded(f)
   if err != nil {
     ...
   }
   rest of the code.
```
</blockquote></details>

I'm not sure that helps? After `openVfsFile` we own `f` and are on the hook for ensuring it is closed -- e.g. if `decryptIfNeeded` returns an error or the checksum fails and returns an error or for any reason we leave this loop, we need to close it, so idiomatic is `defer` to ensure that happens. However, once we hand `f` over to the iterator, *it* now owns closing it, and we no longer should -- indeed, we must not, or it will panic.

Previously this wasn't an issue because we opened *our* file, read all of it, and then closed it, and then handed the content we read to the iterator in a new file that it owned and closed, but the whole point of this change is to have the iterator read our original file as it goes, and close it when it is done.  So what we need is a deferred close of `f` _only until we hand it to the iterator_. We get that with `defer func(){if f != nil { f.Close()}}()` and then just setting `f=nil` after we hand it to the iterator.
___
*[pkg/storage/sst_iterator.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58400#-MQ9V0219XF_zjOtwN-1:-MQ9YyB5BFkZmXynx2Ks:b-co4ilw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce6ae2dfa6f8640c430b9544f305dcdf53f34fee/pkg/storage/sst_iterator.go#L42)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I'm quite surprised this is used from so few places.  Maybe just keep the name as is anyway?
Call the new method with the NewFileSSTIterator?
</blockquote></details>

Heh, I started by doing that, but it bugged me that "file" iterator wasn't the one that took _the path to a file_ -- it felt like "NewSSTIterator" should be the base one and "NewXSSTIterator" the ones that get X -- a path, some bytes in memory, etc -- and then convert that to what the base thing wants?
___
*[pkg/storage/cloudimpl/external_storage.go, line 563 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58400#-MQ9TFHr-d6iMXNQ_qZu:-MQ9Z-snDjjWUK3aRcvh:b-e55l0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/b473677a0489e11e77f8f2f3e2d95e772cdfa596/pkg/storage/cloudimpl/external_storage.go#L563)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I understand why you have this comment here.  I'm not sure this would be safe though.
Even if there is a single reader (e.g. an iterator), how the data is read depends on the iterator implementation.  I mean, it's perfectly reasonable to say, read the header, then readAt to read the footer, then go back to readAt (after header), and then continue regular reads.

The unfortunate reality is that vfs file mixes 2 different concepts: a file type object (read) and a file descriptor based one (readAt).

Would it be safer to just forego any sort of optimization attempts at this stage, and simply read requested range?

We could address inefficiencies in that approach later, but at least we will satisfy interface correctly...
</blockquote></details>

I was worried about this too, but I checked and sstable.Reader _only_ calls `ReadAt`-- indeed,  I confirmed this by making a `vfs.ReadableFile` interface with only  `ReadAt`, `Stat`, and `Close` and (other than Prefetch,, which needs a type-sniff for `Fd` anyway) it works fine. I'll probably add that so we don't need to "implement" all the extra vfs.File methods, but that'll need to wait for an upstream PR and vendor bump, but the fact that it works makes me feel better about this for now. Since we iterate these SSTs once and in order, after the initial footer/index read, we'd expect almost entirely sequential access, where this optimization will save a lot of RPCs, renegotiating TLS, etc. I'm not eager to toss is just because of the io.ReaderAt comment which our one user -- sstable.Reader -- doesn't care about.
___
*[pkg/storage/cloudimpl/external_storage.go, line 596 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58400#-MQ9U4f4CrJgjIpBsotP:-MQ9dcd-B6e0r8JRqDi1:b-nv49vy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b473677a0489e11e77f8f2f3e2d95e772cdfa596/pkg/storage/cloudimpl/external_storage.go#L596)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I think we can extend sizeStat to propagate name.
We can also implement isDir (false), Mode (0644).  And I'd prefer to even return time{} as modtime.
</blockquote></details>

Eh, I dunno -- I like the clarity of `panic("unimplented")` for expressing "this is only here for calling `Size` and no other methods are ever called". 

Having all the other methods all panic makes it very explicit that we're assuming they are never called and makes it really loud and obvious if that assumption is violated. Having them return zero values or something makes me more uneasy that unintended usage may sneak in accidentally and go undetected. 

We use `panic("unimplemented")` this way throughout the codebase.
___
*[pkg/storage/cloudimpl/external_storage.go, line 597 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58400#-MQ9U1KU1toycLDqmpvR:-MQ9f6R_Aji5gcpFlUXY:bars335) ([raw file](https://github.com/cockroachdb/cockroach/blob/b473677a0489e11e77f8f2f3e2d95e772cdfa596/pkg/storage/cloudimpl/external_storage.go#L597)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I think we should return nil here -- it's allowed by api.
</blockquote></details>

Ditto above -- I'd rather be explicit that it is never called and only decide to return something as allowed by the api if/when someone wants to change that fact.

**Review by miretskiy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58400)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[pkg/storage/cloudimpl/external_storage.go, line 563 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58400#-MQ9TFHr-d6iMXNQ_qZu:-MQ9iTOS5aluWXGeKBfy:b-rcf334) ([raw file](https://github.com/cockroachdb/cockroach/blob/b473677a0489e11e77f8f2f3e2d95e772cdfa596/pkg/storage/cloudimpl/external_storage.go#L563)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I was worried about this too, but I checked and sstable.Reader _only_ calls `ReadAt`-- indeed,  I confirmed this by making a `vfs.ReadableFile` interface with only  `ReadAt`, `Stat`, and `Close` and (other than Prefetch,, which needs a type-sniff for `Fd` anyway) it works fine. I'll probably add that so we don't need to "implement" all the extra vfs.File methods, but that'll need to wait for an upstream PR and vendor bump, but the fact that it works makes me feel better about this for now. Since we iterate these SSTs once and in order, after the initial footer/index read, we'd expect almost entirely sequential access, where this optimization will save a lot of RPCs, renegotiating TLS, etc. I'm not eager to toss is just because of the io.ReaderAt comment which our one user -- sstable.Reader -- doesn't care about.
</blockquote></details>

Ack...
___
*[pkg/storage/cloudimpl/external_storage.go, line 596 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58400#-MQ9U4f4CrJgjIpBsotP:-MQ9hrotACHfNRuD16th:b-4hhwf2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b473677a0489e11e77f8f2f3e2d95e772cdfa596/pkg/storage/cloudimpl/external_storage.go#L596)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Eh, I dunno -- I like the clarity of `panic("unimplented")` for expressing "this is only here for calling `Size` and no other methods are ever called". 

Having all the other methods all panic makes it very explicit that we're assuming they are never called and makes it really loud and obvious if that assumption is violated. Having them return zero values or something makes me more uneasy that unintended usage may sneak in accidentally and go undetected. 

We use `panic("unimplemented")` this way throughout the codebase.
</blockquote></details>

Just weird to see that we implement vfs file w/out implement these methods.
And, it's not that we're lying (with exception of mod time) -- everything else we can implement correctly.

Also, I would easily see a log.Info("Stat file: ... %s", stat.Name())
Kinda silly to panic on that, particularly since we have the name anyway.
Also, if we have assumptions that are violated, returning an AssertionFailef is both more correct (i.e. assertion failed) and safer --- i..e does not crash the node.

**Review by miretskiy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58400)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[pkg/ccl/backupccl/restore_data_processor.go, line 196 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58400#-MQ9WLYT-wFMRPmTEllV:-MQ9ogDW7PO2lap4WRDg:bt0zi3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce6ae2dfa6f8640c430b9544f305dcdf53f34fee/pkg/ccl/backupccl/restore_data_processor.go#L196)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I'm not sure that helps? After `openVfsFile` we own `f` and are on the hook for ensuring it is closed -- e.g. if `decryptIfNeeded` returns an error or the checksum fails and returns an error or for any reason we leave this loop, we need to close it, so idiomatic is `defer` to ensure that happens. However, once we hand `f` over to the iterator, *it* now owns closing it, and we no longer should -- indeed, we must not, or it will panic.

Previously this wasn't an issue because we opened *our* file, read all of it, and then closed it, and then handed the content we read to the iterator in a new file that it owned and closed, but the whole point of this change is to have the iterator read our original file as it goes, and close it when it is done.  So what we need is a deferred close of `f` _only until we hand it to the iterator_. We get that with `defer func(){if f != nil { f.Close()}}()` and then just setting `f=nil` after we hand it to the iterator.
</blockquote></details>

I think I didn't make it clear enough...

after openVFS -- we either get the file or an error, and we do owe this file.
However, a call to decryptIfNeeded takes ownership of the file and returns possibly new file -- and only that that point would we need to worry about closing.
Maybe decryptIfNeeded could take a pointer to a file? to make it clear that it could mutate it?
___
*[pkg/storage/sst_iterator.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58400#-MQ9V0219XF_zjOtwN-1:-MQ9pB4A1nglK6iQOCkk:b8jk1g9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce6ae2dfa6f8640c430b9544f305dcdf53f34fee/pkg/storage/sst_iterator.go#L42)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Heh, I started by doing that, but it bugged me that "file" iterator wasn't the one that took _the path to a file_ -- it felt like "NewSSTIterator" should be the base one and "NewXSSTIterator" the ones that get X -- a path, some bytes in memory, etc -- and then convert that to what the base thing wants?
</blockquote></details>

Fine either way.

**Review by dt — COMMENTED** [review]
Okay, I've refactored this a bit. 

Rather than put a helper in `storage/cloud` that looks like it claims to implement `vfs.File`, but has methods which if called would panic, I've now moved this helper to `storageccl` and more importantly combined the creation of the read-at helper and the opening of the SST iterator into a single call, so our unsafe-not-actually-a-vfs.File thing is never floating around, where someone might try to call something like `file.Stat.ModTime()` or `Write()`.

Instead, this new helper gets the remote location (and encryption info) and we returns an sst iterator. The fact that we make an intermediate wrapper, which has some methods that may panic, is hidden, and is only between the helper and sstable.Reader (an upstream change picked up in rebase here also shrunk the interface needed by sstable.Reader so it no longer needs all of `vfs.File`).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58400#-:-MQSWpik-Pv0tL-EyOnq:b86imyg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[pkg/ccl/backupccl/restore_data_processor.go, line 196 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58400#-MQ9WLYT-wFMRPmTEllV:-MQSK6Rl79d3n8eCh5-N:b4a7r63) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce6ae2dfa6f8640c430b9544f305dcdf53f34fee/pkg/ccl/backupccl/restore_data_processor.go#L196)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I think I didn't make it clear enough...

after openVFS -- we either get the file or an error, and we do owe this file.
However, a call to decryptIfNeeded takes ownership of the file and returns possibly new file -- and only that that point would we need to worry about closing.
Maybe decryptIfNeeded could take a pointer to a file? to make it clear that it could mutate it?

</blockquote></details>

I see. I'm still a little uneasy about each err return branch being on the hook for its own error handling. Per PR-comment, I pulled this all into a helper func, so it's little cleaner now I think.
___
*[pkg/storage/sst_iterator.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58400#-MQ9V0219XF_zjOtwN-1:-MQSbIZj-OZ8EF3rVvcj:b-7jbuff) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce6ae2dfa6f8640c430b9544f305dcdf53f34fee/pkg/storage/sst_iterator.go#L42)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Fine either way.
</blockquote></details>

Since there were only two calls to it, I actually just changed it to take sstable.ReadableFile and switched those two calls (both tests) to open the file themselves.
___
*[pkg/storage/cloudimpl/external_storage.go, line 596 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58400#-MQ9U4f4CrJgjIpBsotP:-MQSLn7_8gfWIpp9raiL:b-69k50x) ([raw file](https://github.com/cockroachdb/cockroach/blob/b473677a0489e11e77f8f2f3e2d95e772cdfa596/pkg/storage/cloudimpl/external_storage.go#L596)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Just weird to see that we implement vfs file w/out implement these methods.
And, it's not that we're lying (with exception of mod time) -- everything else we can implement correctly.

Also, I would easily see a log.Info("Stat file: ... %s", stat.Name())
Kinda silly to panic on that, particularly since we have the name anyway.
Also, if we have assumptions that are violated, returning an AssertionFailef is both more correct (i.e. assertion failed) and safer --- i..e does not crash the node.
</blockquote></details>

Per PR-level comment, this is no longer possible since we no longer claim to implement vfs.File, and hide the wrapper entirely except from pebble.sstable.Reader.

**Review by dt — COMMENTED** [review]
added benefit of that refactor: I no longer implement `Read` so the caveat about `ReadAt` repositioning the reader is no longer a concern (though the one about parallel calls remains, but I feel better about that since assuming a struct is threadsafe if much less common)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58400#-:-MQScOAU7j0XqULxQOsj:bscifkx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

**Review by miretskiy — APPROVED** [review]
> Reviewed 4 of 5 files at r3, 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58400)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

**Comment by dt** [comment]
TFTRs!

bors r+

**Pull request merged**
