### PR TITLE
kvclient: small fixes and assertions

### PR DESCRIPTION
**Pull request by andreimatei**
See individual commits.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
LGTM with some comments.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47997#-:-M5gzM6JAKpNYmhGbFWa:b-vq17sv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 798 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47997#-M5gy10n0l20v5WZk71R:-M5gy10n0l20v5WZk71S:bcjuv3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebb06b5c13174dca83c0c8ee0c9c6e1cdca15860/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L798)):*
> ```Go
> 	// Update our transaction with any information the error has.
> 	if errTxn := pErr.GetTxn(); errTxn != nil {
> 		// Sanity checks. Finalized transactions are not supposed to get here.
> ```

Since you're here, can you explain why not? I'm not sure what I would say. We seem to have an invariant that non-retriable errors can only have PENDING transactions attached to them (which is probably an artifact of our attaching the "active" txn to all errors, right? Or are there errors that are legit without a txn), which is violated by some errors (such as the ones we're seeing in #47609).

For example, for the error created here from that issue (assuming it's that callsite) https://github.com/cockroachdb/cockroach/blob/a4f11bbbf0d88711f7e043f55aab77922005e5aa/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L231

A committed transaction is tacked onto the error here:

https://github.com/cockroachdb/cockroach/blob/c11b9afc543305bd6a8f47555c5d6d1fc3fe51d5/pkg/kv/kvserver/replica_evaluate.go#L500-L504
___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 800 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47997#-M5gx-mCDvG4E0GD0Prs:-M5gx-mD1nTz9kcT4Qge:b-luefpw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebb06b5c13174dca83c0c8ee0c9c6e1cdca15860/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L800)):*
> ```Go
> 		// Sanity checks. Finalized transactions are not supposed to get here.
> 		if errTxn.Status != roachpb.PENDING {
> 			if errTxn.Status == roachpb.COMMITTED {
> ```

Why an extra branch for this? We're hitting this first one, right? It looks like you're optimizing for the other one. Any reason to not merge these as

```go
log.Fatalf(ctx, "unexpected error with %s txn:\n%s [%T]\ntxn: %s",
  errTxn.Status,
  pErr, pErr.GoError(),
  txn,
)
```

**Review by nvb — APPROVED** [review]
Discussed in person. :lgtm: once Tobi's comments are resolved.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47997#-:-M60y9Xx69nh-72ui9td:b3nxrrd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47997)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 798 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47997#-M5gy10n0l20v5WZk71R:-M65dJxP6wCsu6cfACxh:b-6c634d) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebb06b5c13174dca83c0c8ee0c9c6e1cdca15860/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L798)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Since you're here, can you explain why not? I'm not sure what I would say. We seem to have an invariant that non-retriable errors can only have PENDING transactions attached to them (which is probably an artifact of our attaching the "active" txn to all errors, right? Or are there errors that are legit without a txn), which is violated by some errors (such as the ones we're seeing in #47609).

For example, for the error created here from that issue (assuming it's that callsite) https://github.com/cockroachdb/cockroach/blob/a4f11bbbf0d88711f7e043f55aab77922005e5aa/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L231

A committed transaction is tacked onto the error here:

https://github.com/cockroachdb/cockroach/blob/c11b9afc543305bd6a8f47555c5d6d1fc3fe51d5/pkg/kv/kvserver/replica_evaluate.go#L500-L504
</blockquote></details>

As the comment I've recently added at that `NewTransactionCommittedStatusError()` call site says <pats on the back≥ , that error doesn't make it to this level; it's swallowed by the committer interceptor.

I've added some comments. Please see if you find them convincing.

The case for the COMMITTED status is clear - that one should really not happen.

The case for ABORTED is murkier. Things get confusing on the client when the transaction is aborted. If we do know about the transaction is aborted, we should call `tc.cleanupTxnLocked()` - which we do for `TransactionAbortedError`, but then that has implications for savepoint rollbacks, etc. I like the `TransactionAbortedError` being the only one to signal aborted transactions invariant.
___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 800 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47997#-M5gx-mCDvG4E0GD0Prs:-M65gDqaA6ZlwEk2S2y0:bmxv0vd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebb06b5c13174dca83c0c8ee0c9c6e1cdca15860/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L800)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Why an extra branch for this? We're hitting this first one, right? It looks like you're optimizing for the other one. Any reason to not merge these as

```go
log.Fatalf(ctx, "unexpected error with %s txn:\n%s [%T]\ntxn: %s",
  errTxn.Status,
  pErr, pErr.GoError(),
  txn,
)
```
</blockquote></details>

the reason why they're separate is because they're morally very different cases. I want to hang different comments from the two. And also the aborted check we might have to relax if things go wrong. The other one probably not.

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47997#-:-M67ZMDGByo8D41ByftV:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

**Pull request merged**
