### PR TITLE
opt: fix BPCHAR type and CASE typing

### LINKED ISSUE #108360: sql: implicit casts from STRING to CHAR should use bpchar
**Describe the problem**

For consistency with Postgres, when a `string` is implicitly cast to a `char`, the cast should actually be `::bpchar` rather than `::char` to avoid truncating the string. (`bpchar` is a `char` type with an unspecified width. "bp" stands for "blank padded".)

**To Reproduce**

On master (v23.2 alpha), run the following in `cockroach demo`:
```
CREATE TABLE t1 (t TEXT);
INSERT INTO t1 VALUES ('tt');

CREATE TABLE t2 (c CHAR);
INSERT INTO t2 VALUES ('c');

SELECT (CASE WHEN t1.t > t2.c THEN t1.t ELSE t2.c END) 
FROM t1, t2 
WHERE t1.t = (CASE WHEN t1.t > t2.c THEN t1.t ELSE t2.c END);

EXPLAIN SELECT (CASE WHEN t1.t > t2.c THEN t1.t ELSE t2.c END) 
FROM t1, t2 
WHERE t1.t = (CASE WHEN t1.t > t2.c THEN t1.t ELSE t2.c END);
```

On CRDB this produces:
```
  c
-----
(0 rows)

                           info
-----------------------------------------------------------
  distribution: local
  vectorized: true

  • render
  │
  └── • cross join
      │ pred: t = CASE WHEN t > c THEN t::CHAR ELSE c END
      │
      ├── • scan
      │     missing stats
      │     table: t1@t1_pkey
      │     spans: FULL SCAN
      │
      └── • scan
            missing stats
            table: t2@t2_pkey
            spans: FULL SCAN
(17 rows)
```
On Postgres this produces:
```
 c  
----
 tt
(1 row)

                                            QUERY PLAN                                             
---------------------------------------------------------------------------------------------------
 Nested Loop  (cost=0.00..69215.60 rows=15368 width=32)
   Join Filter: ((CASE WHEN (t1.t > (t2.c)::text) THEN (t1.t)::bpchar ELSE t2.c END)::text = t1.t)
   ->  Seq Scan on t2  (cost=0.00..32.60 rows=2260 width=8)
   ->  Materialize  (cost=0.00..30.40 rows=1360 width=32)
         ->  Seq Scan on t1  (cost=0.00..23.60 rows=1360 width=32)
(5 rows)
```
Notice that the CRDB plan includes a `::char` cast, while the Postgres plan includes a `::bpchar` cast. This is the reason the two queries produce different results.

**Expected behavior**

CRDB should produce the same results as Postgres.

Jira issue: CRDB-30440

### LINKED ISSUE #127889: roachtest: unoptimized-query-oracle/disable-rules=half/rand-tables failed, something to do with coalesce of a cast and vectorized engine
roachtest.unoptimized-query-oracle/disable-rules=half/rand-tables [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16258222?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16258222?buildTab=artifacts#/unoptimized-query-oracle/disable-rules=half/rand-tables) on release-23.2 @ [826c4d1398506909264d6ad935851417cae59e2a](https://github.com/cockroachdb/cockroach/commits/826c4d1398506909264d6ad935851417cae59e2a):

```
  	... // 48 identical elements
  }
sql: SELECT
	COALESCE(
		('225.91.20.234/17':::INET::INET || tab_3651.col5_7::STRING)::STRING,
		CASE
		WHEN true THEN tab_3651."col5_5"
		ELSE tab_3651.col5_3
		END
	)
		AS col_10395,
	11:::INT8 AS col_10396,
	'00:01:41':::TIME AS col_10397,
	(-867527588):::INT8 AS col_10398,
	'20:44:44.584053+14:15':::TIMETZ AS col_10399,
	tab_3651.col5_3 AS col_10400,
	tab_3651.col5_2 AS col_10401,
	tab_3651."co%f5l5_4" AS col_10402,
	tab_3651.tableoid AS col_10403,
	'C4F1DDD5/5D1F2B62':::PG_LSN AS col_10404
FROM
	defaultdb.public." tab%efL
e5"@[0] AS tab_3651
WHERE
	'0/1000':::PG_LSN::PG_LSN NOT IN ('1928C26F/AA2FC12':::PG_LSN,)
ORDER BY
	col_10395 DESC NULLS FIRST,
	tab_3651.col5_7 NULLS LAST,
	col_10404 DESC NULLS FIRST,
	col_10400 ASC NULLS LAST,
	tab_3651.col5_8 ASC NULLS FIRST,
	tab_3651.col5_1 NULLS FIRST,
	col_10396 ASC NULLS LAST,
	tab_3651.crdb_internal_mvcc_timestamp ASC NULLS FIRST,
	tab_3651.col5😶_0,
	tab_3651.col5_3 DESC,
	tab_3651.col5_6 DESC NULLS FIRST,
	col_10403 NULLS LAST,
	col_10402 ASC,
	col_10398 DESC NULLS LAST,
	col_10399 ASC NULLS LAST,
	col_10401,
	tab_3651.col5_2 NULLS LAST,
	tab_3651."co%f5l5_4" DESC NULLS LAST,
	tab_3651."col5_5" DESC,
	col_10397,
	tab_3651.tableoid NULLS FIRST
LIMIT
	96:::INT8
test artifacts and logs in: /artifacts/unoptimized-query-oracle/disable-rules=half/rand-tables/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-16258222/unoptimized-query-oracle-disable-rules-half-rand-tables/1722340153929/1722340841232)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #126802 roachtest: unoptimized-query-oracle/disable-rules=half/rand-tables failed [C-test-failure O-roachtest O-robot T-sql-queries branch-release-23.1 release-blocker]
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*unoptimized-query-oracle/disable-rules=half/rand-tables.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-40653

### PR DESCRIPTION
**Pull request by mgartner**
This commit addresses inconsistencies from Postgres' behavior. First, it
makes the `BPCHAR` type distinct from `CHAR`. The former is a
blank-padded character type with no type width, meaning that it could
have any length. The latter is a blank-padded character type with a type
width of exactly 1 - it is essentially an alias of `CHAR(1)`.
Previously, a column of type `BPCHAR` behaved the same as a column of
type `CHAR(1)` - it enforced a length limit of 1.

Second, the typing of `CASE` and `CASE`-like expressions has been fixed.
The branches of these conditionals is no longer forced to have the same
type-width.

Fixes #127889
Fixes #108360

Release note (bug fix): A bug has been fixed that caused incorrect
evaluation of `CASE`, `COALESCE`, and `IF` expressions with branches
producing fixed-width string-like types, such as `CHAR`. In addition,
the `BPCHAR` type has been fixed so that it no longer incorrectly
imposes a length limit of 1.

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
Thanks for the fix! Assuming the test cases check out, :lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129007#-:-O4I3htVCEHDg_6PgFjH:bslsfmd)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/logictest/testdata/logic_test/case` line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129007#-O4I2HGLBDgtc4vdrqQq:-O4I2HGM3AI1JOS8iZVX:bxtsim) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a0a1605dc45f16dd7de6e606c9559c3c3df47a1/pkg/sql/logictest/testdata/logic_test/case#L71)):*
> ```
> ba
> 
> subtest end
> ```

I'd be curious to see a few additional tests:
```
SELECT CASE WHEN false THEN 'b'::CHAR ELSE 'foo'::TEXT END;
SELECT (CASE WHEN false THEN 'b'::CHAR ELSE 'foo'::TEXT END)::CHAR;
SELECT (CASE WHEN false THEN 'b'::CHAR ELSE 'foo'::TEXT END)::BPCHAR;
```
In Postgres:
```
postgres=# SELECT CASE WHEN false THEN 'b'::CHAR ELSE 'foo'::TEXT END;
SELECT (CASE WHEN false THEN 'b'::CHAR ELSE 'foo'::TEXT END)::CHAR;
SELECT (CASE WHEN false THEN 'b'::CHAR ELSE 'foo'::TEXT END)::BPCHAR;
 case
------
 foo
(1 row)

 bpchar
--------
 f
(1 row)

 bpchar
--------
 foo
(1 row)
```

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129007)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

___
*[`pkg/sql/logictest/testdata/logic_test/case` line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129007#-O4I2HGLBDgtc4vdrqQq:-O4LFYLK9XAr6Y5aYH78:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a0a1605dc45f16dd7de6e606c9559c3c3df47a1/pkg/sql/logictest/testdata/logic_test/case#L71)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I'd be curious to see a few additional tests:
```
SELECT CASE WHEN false THEN 'b'::CHAR ELSE 'foo'::TEXT END;
SELECT (CASE WHEN false THEN 'b'::CHAR ELSE 'foo'::TEXT END)::CHAR;
SELECT (CASE WHEN false THEN 'b'::CHAR ELSE 'foo'::TEXT END)::BPCHAR;
```
In Postgres:
```
postgres=# SELECT CASE WHEN false THEN 'b'::CHAR ELSE 'foo'::TEXT END;
SELECT (CASE WHEN false THEN 'b'::CHAR ELSE 'foo'::TEXT END)::CHAR;
SELECT (CASE WHEN false THEN 'b'::CHAR ELSE 'foo'::TEXT END)::BPCHAR;
 case
------
 foo
(1 row)

 bpchar
--------
 f
(1 row)

 bpchar
--------
 foo
(1 row)
```
</blockquote></details>

Done.

**Comment by mgartner** [comment]
I realized this is related to #108360. I'll have a follow-up PR to address a few more things I found (mentioned in that issue).

**Comment by mgartner** [comment]
I actually need to do the follow-up work in this same PR to get the tests to pass. We need to represent a `CHAR(N)` type with no type width in SQL when we serialize the cast for distributing it to other nodes. Because we simply serialize it as `CHAR` now, the remote node parses it as `CHAR(1)` semantically. This causes the `typing` logic tests to fail under `fakedist` and other configurations.

**Comment by mgartner** [comment]
I had to adjust some of the UDF resolution logic to find overloads with `CHAR`, `CHAR(N)`, or `BPCHAR` parameters with any three of those variations. The behavior now matches Postgres more closely.

**Comment by mgartner** [comment]
@DrewKimball mind taking one more quick look?

**Comment by mgartner** [comment]
Friendly ping @DrewKimball. :)

**Review by DrewKimball — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r2, 10 of 22 files at r3, 16 of 16 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129007#-:-O6b54qJ-NJcJbSFqA2W:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
