### PR TITLE
rpc: specify grpc.WithBackoffMaxDelay(time.Second)

### LINKED ISSUE #10643: cmd/zerosum: 0 QPS after node restart
```
~ zerosum -m 3 -n 4 -c simple
...
chaos: killing node 1 for 20s
...
chaos: starting node 1
...
used
     36s     35580       25533    134.5       32       41       43       48          25 41 37 41
     37s     35580       25533      0.0       32       42       45       -1              0 0 0 0
     38s     35580       25533      0.0       32       45       46       49          25 42 38 42
     39s     35580       25533      0.0       32       45       48       -1              0 0 0 0
     40s     35580       25533      0.0       32       48       50       52          25 45 41 45
_elapsed__accounts_________ops__ops/sec___errors___splits____xfers___ranges_____________replicas
     41s     35580       25533      0.0       32       49       51       55          26 47 44 48
     42s     35580       25533      0.0       32       51       52       -1              0 0 0 0
     43s     35580       25533      0.0       32       52       52       58          27 50 46 51
     44s     35580       25533      0.0       32       55       55       59          31 50 44 52
     45s     35580       25533      0.0       32       59       57       62          34 53 46 53
     46s     35580       25533      0.0       32       59       59       66          36 53 52 57
     47s     36146       26113    579.0       32       60       60       67          37 54 53 57
```

This didn't happen a few months ago. I've tried disabling both quiescence and coalesced heartbeats, but the problem still occurs. The restarted node isn't able to make progress because remote nodes are not talking to it. One problem causing this was #10642, but the above run was taken with that PR. Now it looks like remote nodes are periodically trying to send requests after the node restarts, but the requests are failing with `grpc: the connection is unavailable`. As far as I can tell, the connection is ok. I haven't tracked down yet why grpc is returning that error.

Cc @tamird

### PR DESCRIPTION
**Pull request by petermattis**
The default grpc backoff delay is 2m. This delay kicks in when a grpc
connection encounters a transient error such as being unable to connect
or the remote end terminating the connection. Using such a high backoff
causes problems when a node is down for a significant period of
time. When the node comes back up, it will be able to talk to other
nodes in the cluster, but the other nodes won't be able to talk to it.

Fixes #10643

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10652)

### CODE REVIEW

**Comment by petermattis** [comment]
1 second matches the max-backoff we use for our circuit breakers. Certainly seems bad to have these issues with asymmetric communication. I wonder if this is causing badness on blue where we keep a node down for 6m. 

Cc @cockroachdb/stability

**Comment by petermattis** [comment]
Note, we also have this comment next to the 1s time for our circuit breakers:

```
	// NB (nota Ben): MaxInterval should be less than the Raft election timeout
	// (1.5s) to avoid disruptions. A newly restarted node will be in follower
	// mode with no knowledge of the Raft leader. If it doesn't hear from a
	// leader before the election timeout expires, it will start to campaign,
	// which can be disruptive. Therefore the leader needs to get in touch (via
	// Raft heartbeats) with such nodes within one election timeout of their
	// restart, which won't happen if their backoff is too high.
```

**Comment by tamird** [comment]
LGTM. Can you extract a single constant to drive both the grpc backoff and the breaker MaxInterval?

**Review by bdarnell — APPROVED** [review]

**Comment by bdarnell** [comment]
+1 to a shared constant. Can we also specify the base backoff delay? This also defaults to 1s, so we're currently getting a fixed 1s delay with no backoff or jitter.

**Comment by petermattis** [comment]
Added a shared constant. It isn't currently possible to change the base delay for grpc backoff (without doing something really gross with unsafe casts). Here is the `BackoffConfig` structure (notice the `TODO`):

```
// BackoffConfig defines the parameters for the default gRPC backoff strategy.
type BackoffConfig struct {
	// MaxDelay is the upper bound of backoff delay.
	MaxDelay time.Duration

	// TODO(stevvooe): The following fields are not exported, as allowing
	// changes would violate the current gRPC specification for backoff. If
	// gRPC decides to allow more interesting backoff strategies, these fields
	// may be opened up in the future.

	// baseDelay is the amount of time to wait before retrying after the first
	// failure.
	baseDelay time.Duration

	// factor is applied to the backoff after each retry.
	factor float64

	// jitter provides a range to randomize backoff delays.
	jitter float64
}
```

**Comment by petermattis** [comment]
Added another commit which updates `ui/config.js` which is failing `make check`.

**Pull request merged**
