### PR TITLE
sqlproxyccl: use tokenbucket to throttle connection attempts

### PR DESCRIPTION
**Pull request by jeffswenson**
Previously, the sqlproxy used exponential backoff to reject connection
attempts if the source ip previously made an invalid connection attempt.
A map was used to track previously succesful (source ip, destination
cluster) pairs. The throttle was only applied to unsuccesful pairs.

Now a token bucket is used to throttle connections. If a connection is
succesful, the token is returned to the bucket. This should avoid
throttling well behaved users and provide tools to throttle
abuse.

The ConnectionCache was moved into the throttle service in order to
group the throttling logic into a single module.

The general intent of the change is to allow more connection attempts
before throttling kicks in. The main issue with the old approach is:
1. Testers would regularly lock themselves out by configuring an
   incorrect password. The max backoff was a too aggressive and
   testers would get stuck waiting minutes to hours for the throttle
   to end.
2. It's unclear how to handle racing connection attempts. Currently all
   connection attempts before the first success trigger the throttling
   code path. Using a token bucket naturally allows us to bound the
   total number of attempts the system lets through.

Release note: None

### CODE REVIEW

**Comment by JeffSwenson** [comment]
This resolves https://cockroachlabs.atlassian.net/browse/CC-4502.

I'm on the fence regarding the dual policy approach taken here. One alternative is to have a single restrictive policy, and keep the connection cache logic around. The connection cache skips throttling if an ip has ever successfully authenticated with a specific cluster. The main reason I slightly favor the dual token policy approach, is it provides some back pressure if a client is accidentally dosing their own cluster.

**Comment by JeffSwenson** [comment]
I talked about this offline with Darin. I've changed the implementation to the alternative I outlined here: https://github.com/cockroachdb/cockroach/pull/69041#issuecomment-900458124.

In addition to changing the throttling algorithm I made the following changes:
1. Started using the pkg/cache instead of the hand rolled cache.
2. Switched tokenBucket.tokens from an int to uint. This reduces the risk of weird behavior from an overlow.
3. Improved tokenBucket's handling of a time that rolls back and added a test for it.

**Review by darinpp — APPROVED** [review]
Looks good. Thanks.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69041)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/sqlproxyccl/throttler/token_bucket.go, line 25 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69041#-MiNBhX01bTUs4v_la1M:-MiNBhX01bTUs4v_la1N:bpzthkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b39da59f2d32eccf8f9d76ea1b5e39c0ec5c1863/pkg/ccl/sqlproxyccl/throttler/token_bucket.go#L25)):*
> ```Go
> }
> 
> // tokenBucket is not thread safe.
> ```

Did you consider using https://pkg.go.dev/golang.org/x/time/rate rather than building your own token bucket implementation? We use `golang.org/x/time/rate` elsewhere in CRDB and it has served us well. If there are good reasons to stick with a custom implementation it would be useful to add a comment here explaining why.

**Comment by aaron-crl** [comment]
This fundamentally changes the behavior of a security control in the product and should have required a security team review before being merged. I'll work with relevant leads to address that gap. We'll get a technical review of this PR started next week. cc @catj-cockroach who has been looking at the CC Auth story.

**Pull request merged**
