### PR TITLE
opt: remove VirtualScan operator

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change removes the `VirtualScan` operator and uses `Scan` for virtual
tables. This reduces code duplication and allows all the optimizations related
to `Scan` to function for virtual tables as well.

The main difficulty (which lead to the special operator) is that virtual tables
don't have a primary key. We fix this by adding a dummy, hidden PK column
(always column 0) and presenting a primary index on it. We don't actually
support scanning this column (if you try to select it by name explicitly, you
will get an error in the exec factory).

This change will make it easier to add "real" indexes to improve virtual table
performance.

Release note: None

### CODE REVIEW

**Review by andy-kimball — APPROVED** [review]
:lgtm:, nice way to improve this

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47356#-:-M4aARZp6FMyoVYd682a:bjj6gkc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @jordanlewis, @mgartner, and @rytaft)

**Review by jordanlewis — APPROVED** [review]
Nice, this is great!

**Comment by jordanlewis** [comment]
Pushing down filters into virtual scans will still need to have some special behavior - in most cases we don't want to remove any components of the filter even after push down - I assume that should be possible, but just wanted to call it out in case we'd need anything else here.

**Comment by jordanlewis** [comment]
Maybe I should say "some cases" instead of "most cases", but either way.

**Comment by RaduBerinde** [comment]
Not sure I understand - are you saying that the constraint won't be "guaranteed" and we'd still need to filter the constrained column? I would probably handle that by manufacturing filters from the constraint in the execbuilder (and save the rest of the optimizer from dealing with this complication).

**Pull request merged**
