### PR TITLE
cli: allow dump to be run as of a specified time

### PR DESCRIPTION
**Pull request by madelynnblue**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13853)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/cli/cli_test.go, line 182 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13853#-Ke5Ms7U91nmFjx6DiGN:-Ke5Ms7V8peyQwd8dLho:b-nhv5n5) ([raw file](https://github.com/cockroachdb/cockroach/blob/87019c67225d92b305160ed61778f46ff69e37de/pkg/cli/cli_test.go#L182)):*
> ```Go
> }
> 
> func (c cliTest) RunWithCaptureArgs(args []string) (out string, err error) {
> ```

why the named args?

---

*[pkg/cli/dump.go, line 110 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13853#-Ke5N3ZKK5LDfAfuFA3q:-Ke5N3ZKK5LDfAfuFA3r:b-v03jsk) ([raw file](https://github.com/cockroachdb/cockroach/blob/87019c67225d92b305160ed61778f46ff69e37de/pkg/cli/dump.go#L110)):*
> ```Go
> ) (mds []tableMetadata, clusterTS string, err error) {
> 	if asOf == "" {
> 		vals, err := conn.QueryRow("SELECT now()::string", nil)
> ```

can you comment why this uses ::string()?

---

*[pkg/cli/dump.go, line 116 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13853#-Ke5NYXSux4PjkyOzzs8:-Ke5NYXSux4PjkyOzzs9:b39uxff) ([raw file](https://github.com/cockroachdb/cockroach/blob/87019c67225d92b305160ed61778f46ff69e37de/pkg/cli/dump.go#L116)):*
> ```Go
> 		clusterTS = vals[0].(string)
> 	} else {
> 		// Validate the timestamp. This prevents SQL injection.
> ```

asked below but also relevant here: how come placeholders aren't supported?

---

*[pkg/cli/dump.go, line 117 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13853#-Ke5N7TrtYlbRGdabkwF:-Ke5N7TrtYlbRGdabkwG:b-vfgckf) ([raw file](https://github.com/cockroachdb/cockroach/blob/87019c67225d92b305160ed61778f46ff69e37de/pkg/cli/dump.go#L117)):*
> ```Go
> 	} else {
> 		// Validate the timestamp. This prevents SQL injection.
> 		_, err := parser.ParseDTimestamp(asOf, time.Nanosecond)
> ```

`if _, err := ...; err != nil {`

---

*[pkg/cli/dump.go, line 148 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13853#-Ke5NLxEcp8gNG96Ix3e:-Ke5NLxEcp8gNG96Ix3f:bw5hs1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/87019c67225d92b305160ed61778f46ff69e37de/pkg/cli/dump.go#L148)):*
> ```Go
> 		SELECT TABLE_NAME
> 		FROM information_schema.tables
> 		AS OF SYSTEM TIME '%s'
> ```

throughout: does AS OF SYSTEM TIME not handle placeholders?

---

*[pkg/cli/dump.go, line 150 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13853#-Ke5NPmLTMap9BszXAdI:-Ke5NPmLTMap9BszXAdJ:b-ba1r3t) ([raw file](https://github.com/cockroachdb/cockroach/blob/87019c67225d92b305160ed61778f46ff69e37de/pkg/cli/dump.go#L150)):*
> ```Go
> 		AS OF SYSTEM TIME '%s'
> 		WHERE TABLE_SCHEMA = $1
> 		`, ts), []driver.Value{dbName})
> ```

throughout: how come the explicit slice is needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13853)*

**Comment by mjibson** [comment]
Review status: 4 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/cli/cli_test.go, line 182 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13853#-Ke5Ms7U91nmFjx6DiGN:-Ke5OWa3j3k0rMdZXRE-:b-ips93e) ([raw file](https://github.com/cockroachdb/cockroach/blob/87019c67225d92b305160ed61778f46ff69e37de/pkg/cli/cli_test.go#L182)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why the named args?
</blockquote></details>

Removed. Just copied from the other function.

---

*[pkg/cli/dump.go, line 110 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13853#-Ke5N3ZKK5LDfAfuFA3q:-Ke5P1-xZpWQ3KXddOZZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/87019c67225d92b305160ed61778f46ff69e37de/pkg/cli/dump.go#L110)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can you comment why this uses ::string()?
</blockquote></details>

Done.

---

*[pkg/cli/dump.go, line 116 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13853#-Ke5NYXSux4PjkyOzzs8:-Ke5PTJQ0xixyLSnX_0-:b-as0hl1) ([raw file](https://github.com/cockroachdb/cockroach/blob/87019c67225d92b305160ed61778f46ff69e37de/pkg/cli/dump.go#L116)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

asked below but also relevant here: how come placeholders aren't supported?
</blockquote></details>

Answered below.

---

*[pkg/cli/dump.go, line 117 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13853#-Ke5N7TrtYlbRGdabkwF:-Ke5PcXv7cAeluN4Ggnh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/87019c67225d92b305160ed61778f46ff69e37de/pkg/cli/dump.go#L117)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

`if _, err := ...; err != nil {`
</blockquote></details>

Done.

---

*[pkg/cli/dump.go, line 148 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13853#-Ke5NLxEcp8gNG96Ix3e:-Ke5P38YNp5g9j6ims0w:b-xdqymh) ([raw file](https://github.com/cockroachdb/cockroach/blob/87019c67225d92b305160ed61778f46ff69e37de/pkg/cli/dump.go#L148)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

throughout: does AS OF SYSTEM TIME not handle placeholders?
</blockquote></details>

It does not. Since table descriptors can change (or just not exist) at certain times, it's not possible to return the pgwire types for any other placeholder since those types may vary over time.

---

*[pkg/cli/dump.go, line 150 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13853#-Ke5NPmLTMap9BszXAdI:-Ke5PMMWVPorEKEhAHea:b-r6kf3y) ([raw file](https://github.com/cockroachdb/cockroach/blob/87019c67225d92b305160ed61778f46ff69e37de/pkg/cli/dump.go#L150)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

throughout: how come the explicit slice is needed?
</blockquote></details>

This is the api for our own sqlConn: we're not using database/sql here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13853)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/cli/dump.go, line 148 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13853#-Ke5NLxEcp8gNG96Ix3e:-Ke5U5A8zgBg2K9YDtS9:b98lht) ([raw file](https://github.com/cockroachdb/cockroach/blob/87019c67225d92b305160ed61778f46ff69e37de/pkg/cli/dump.go#L148)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

It does not. Since table descriptors can change (or just not exist) at certain times, it's not possible to return the pgwire types for any other placeholder since those types may vary over time.
</blockquote></details>

I don't understand. What does the that have to do with using a placeholder for the AS OF TIMESTAMP value itself?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13853)*

**Comment by mjibson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/cli/dump.go, line 148 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13853#-Ke5NLxEcp8gNG96Ix3e:-Ke5WGLCFtn9P1Kt71Ye:b-jj4i4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/87019c67225d92b305160ed61778f46ff69e37de/pkg/cli/dump.go#L148)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I don't understand. What does the that have to do with using a placeholder for the AS OF TIMESTAMP value itself?
</blockquote></details>

Consider the query:

```
SELECT a FROM t AS OF SYSTEM TIME $1 WHERE b = $2
```

What is the type of $2? It is whatever type `t.b` is. The type of `t.b` could have changed, though, if a column were removed and added. Since we don't know the table descriptor until we know $1, we can't know the type of $2, so this statement can't send back the placeholders types over pgwire when the statement is prepared.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13853)*

**Comment by mjibson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/cli/dump.go, line 148 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13853#-Ke5NLxEcp8gNG96Ix3e:-Ke5WvXZo8br3bfOnpU3:b-6sfeqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/87019c67225d92b305160ed61778f46ff69e37de/pkg/cli/dump.go#L148)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Consider the query:

```
SELECT a FROM t AS OF SYSTEM TIME $1 WHERE b = $2
```

What is the type of $2? It is whatever type `t.b` is. The type of `t.b` could have changed, though, if a column were removed and added. Since we don't know the table descriptor until we know $1, we can't know the type of $2, so this statement can't send back the placeholders types over pgwire when the statement is prepared.
</blockquote></details>

It is notable, however, that we could support statements like:

```
SELECT a FROM t AS OF SYSTEM TIME $1
```

That is, where there are no unresolved placeholders. This is on my todo sometime list.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13853)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/cli/dump.go, line 148 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13853#-Ke5NLxEcp8gNG96Ix3e:-Ke5XDRfR4e53gbgO4h8:bg9fu9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/87019c67225d92b305160ed61778f46ff69e37de/pkg/cli/dump.go#L148)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

It is notable, however, that we could support statements like:

```
SELECT a FROM t AS OF SYSTEM TIME $1
```

That is, where there are no unresolved placeholders. This is on my todo sometime list.
</blockquote></details>

Your second comment is what I was referring to: there is a special case which would apply here and should work.

Could you file an issue?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13853)*

**Comment by mjibson** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/cli/dump.go, line 148 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13853#-Ke5NLxEcp8gNG96Ix3e:-Ke5Z9nwEz1PVFewOasW:b-ulowof) ([raw file](https://github.com/cockroachdb/cockroach/blob/87019c67225d92b305160ed61778f46ff69e37de/pkg/cli/dump.go#L148)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Your second comment is what I was referring to: there is a special case which would apply here and should work.

Could you file an issue?
</blockquote></details>

Filed #13856

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13853)*

**Pull request merged**
