### PR TITLE
sql: reduce allocations in `NewPlanningCtxWithOracle`

### PR DESCRIPTION
**Pull request by mgartner**
Epic: None

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
I'm thinking this might not actually be a safe change, due to these lines which copy the infra but not the `onFlowCleanup`:

https://github.com/cockroachdb/cockroach/pull/136859/files#diff-eaddfa7def2bd53371d91603695e5ee53febd67e98f7c622f00ba5530b5aa2adR941-R945

Benchmark results:

```
name                                     old time/op    new time/op    delta
EndToEnd/kv-read/vectorize=on/Simple        192µs ± 2%     193µs ± 2%    ~     (p=0.841 n=5+5)
EndToEnd/kv-read/vectorize=on/Prepared      131µs ± 2%     132µs ± 1%    ~     (p=0.841 n=5+5)
EndToEnd/kv-read/vectorize=off/Simple       190µs ± 1%     191µs ± 0%    ~     (p=0.286 n=5+4)
EndToEnd/kv-read/vectorize=off/Prepared     128µs ± 1%     129µs ± 2%    ~     (p=0.095 n=5+5)

name                                     old alloc/op   new alloc/op   delta
EndToEnd/kv-read/vectorize=on/Simple       32.2kB ± 7%    32.2kB ± 7%    ~     (p=0.841 n=5+5)
EndToEnd/kv-read/vectorize=on/Prepared     21.0kB ± 9%    20.9kB ± 9%    ~     (p=1.000 n=5+5)
EndToEnd/kv-read/vectorize=off/Simple      32.4kB ± 0%    32.4kB ± 0%    ~     (p=0.635 n=4+5)
EndToEnd/kv-read/vectorize=off/Prepared    22.4kB ± 7%    22.3kB ± 7%    ~     (p=0.548 n=5+5)

name                                     old allocs/op  new allocs/op  delta
EndToEnd/kv-read/vectorize=on/Simple          299 ± 4%       297 ± 4%    ~     (p=0.389 n=5+5)
EndToEnd/kv-read/vectorize=on/Prepared        211 ± 7%       209 ± 7%    ~     (p=0.238 n=5+5)
EndToEnd/kv-read/vectorize=off/Simple         286 ± 0%       284 ± 0%  -0.61%  (p=0.000 n=4+5)
EndToEnd/kv-read/vectorize=off/Prepared       199 ± 0%       197 ± 0%  -1.01%  (p=0.029 n=4+4)
```

**Comment by mgartner** [comment]
> I'm thinking this might not actually be a safe change, due to these lines which copy the infra but not the onFlowCleanup:

Oh, nvm, that's for a new physical plan, not a new planning ctx. Maybe it is fine?

**Review by yuzefovich — APPROVED** [review]
Nice find! :lgtm:

I think it should be a safe change - multiple physical plans can reference the same `PhysicalInfrastructure` object, and we clean up the infra only when all physical plans are done. This behavior doesn't change with this PR.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136859#-:-ODOB_VB-8jd0KK_QiSX:b-hod4e3)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/distsql_physical_planner.go` line 1078 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136859#-ODOB0i85-dhG4dCHT2E:-ODOB0i85-dhG4dCHT2F:b-op3v8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a334ccdeb2c927ed594aec59def446fa28e6376/pkg/sql/distsql_physical_planner.go#L1078)):*
> ```Go
> // planning has been completed.
> func (p *PlanningCtx) getCleanupFunc() func() {
> 	return func() {
> ```

nit: in most cases we have `len(p.onFlowCleanup) == 0`, so I wonder whether it's worth introducing a fast path here for the case, i.e. do something like
```
if len(p.onFlowCleanup) == 0 {
		return p.infra.Release
}
return func() {
		p.infra.Release()
		for _, r := range p.onFlowCleanup {
			r()
		}
}
```
Perhaps this will save some more allocations?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136859)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[`pkg/sql/distsql_physical_planner.go` line 1078 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136859#-ODOB0i85-dhG4dCHT2E:-ODOLKDE9xvdwB1CaVEu:b-kh0gww) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a334ccdeb2c927ed594aec59def446fa28e6376/pkg/sql/distsql_physical_planner.go#L1078)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: in most cases we have `len(p.onFlowCleanup) == 0`, so I wonder whether it's worth introducing a fast path here for the case, i.e. do something like
```
if len(p.onFlowCleanup) == 0 {
		return p.infra.Release
}
return func() {
		p.infra.Release()
		for _, r := range p.onFlowCleanup {
			r()
		}
}
```
Perhaps this will save some more allocations?
</blockquote></details>

I didn't observe any allocations here, and I didn't measure a difference from the change. But I made it anyway in case it has an effect in the future, and because I like how it makes the common case clear.

**Review by yuzefovich — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136859)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[`pkg/sql/distsql_physical_planner.go` line 1078 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136859#-ODOB0i85-dhG4dCHT2E:-ODOO8Kl8mU6pvm5Qwp-:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a334ccdeb2c927ed594aec59def446fa28e6376/pkg/sql/distsql_physical_planner.go#L1078)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I didn't observe any allocations here, and I didn't measure a difference from the change. But I made it anyway in case it has an effect in the future, and because I like how it makes the common case clear.
</blockquote></details>

:thumbsup:

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
