### PR TITLE
sql: improved aggregation for variance and stddev

### LINKED ISSUE #13689: sql,distsql: inconsistent aggregation results with DistSQL
I am seeing a few aggregation logic tests occasionally fail when DistSQL is enabled on a 3 node cluster (with fake span resolver). This happens both with and without the apd change #13551.

```
query RRR
SELECT VARIANCE(x), VARIANCE(y::decimal), VARIANCE(z) FROM xyz
----
9.00 4.5 6.333333333333333
We get:
9.00 4.5 6.333333333333334  
```
This comes just from STDDEV/VARIANCE processing arguments in a different order. Indeed, we can reproduce on regular sql using:
```
SELECT VARIANCE(x), VARIANCE(y::decimal), VARIANCE(z) FROM (SELECT x,y,z FROM xyz ORDER BY random())
```

This is an incorrect<sup>1</sup> result. I think that whatever output precision `p` we want for the result, `decimalVarianceAggregate` must use higher precision for its internal calculations (e.g. `p + 3`). Technically we may need something like `p + O(log count)` - we could increase the precision of the internal calculations as the count increases.

Another one is:
```
query RRR
SELECT STDDEV(x), STDDEV(y::decimal), STDDEV(z) FROM xyz
----
3  2.121320343559643  2.516611478423583
We get:
3  2.121320343559643  2.5166114784235836
```

Here we have an inconsistency in the number of decimals we output, and the result is also incorrect, the following decimal should be `2` not `6` (the correct result is: `2.51661147842358323241...`).

CC @mjibson @nvanbenschoten @knz

[1]: It can be argued that this is not incorrect, just "imprecise". My point of view is that we are choosing how many decimals to output; if we only compute to 14 accurate decimals, we should output just 14..  In this sense if the true value is `1.242`, it's imprecise but not incorrect to output `1.24`, but it's incorrect to output `1.23` or `1.25`.  Of course things that are on the "edge" like `1.25499xy..` or `1.25000xy..` could go either way - both `1.25` and `1.26` are correct.. I don't quite know what the formal guarantee should be.

### PR DESCRIPTION
**Pull request by madelynnblue**
Use extra internal precision during variance and stddev to protect
against order changes that can happen in dist SQL. Although this
isn't a perfect solution and there are theoretical worst cases that
could produce the behavior described in the fixed issue, this is a
fairly good fix. The problem can still occur if there are 1000 more
worst case inputs than non-worst case inputs. It is at least better
than what we have now.

Fixes #13689
Reverts 0fc3ae04961c33aaf1f569e9dfc8f9b0302b43c9

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14013)

### CODE REVIEW

**Comment by knz** [comment]
Ugh, the code change is functionally sound but I really want to see the benchmark diff on that. It seems we're going to pay a significant price here. Can you run the numbers?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14013#-:-KenuNdjmEVvhAJh4Frb:b-nqcl90)*

**Comment by RaduBerinde** [comment]
I don't understand why this is a problem for `float`. I thought that it's a given that `float` results are inexact..

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/parser/aggregate_builtins.go, line 755 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14013#-KeokXbowbxgO-06ob6s:-KeokXbowbxgO-06ob6t:b-fbzf8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/36974ca43dc8a574df4bd3ce9ad55953bcb4e87f/pkg/sql/parser/aggregate_builtins.go#L755)):*
> ```Go
> 
> func newDecimalVariance() *decimalVarianceAggregate {
> 	c := DecimalCtx.WithPrecision(DecimalCtx.Precision + 3)
> ```

add a comment here explaining the + 3, reference the issue #

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14013#-:-KeokWSf8NKui3Y87jsr:b-c78x38)*

**Comment by mjibson** [comment]
If we don't fix the float implementation then the tests as written won't pass in dist sql because sometimes a `6` is appended to the output of `stddev(z):

```
root@:26257/d> SELECT stddev(z) FROM (SELECT z FROM xyz ORDER BY random());
+-------------------+
|     stddev(z)     |
+-------------------+
| 2.516611478423583 |
+-------------------+
(1 row)
root@:26257/d> SELECT stddev(z) FROM (SELECT z FROM xyz ORDER BY random());
+--------------------+
|     stddev(z)      |
+--------------------+
| 2.5166114784235836 |
+--------------------+
(1 row)
```

I don't care which way we go. But if we decide to leave floats as is, we'll have to modify the input data of the test so it doesn't have these inconsistencies.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14013#-:-Keom7D0upHRnKuaLtuT:b-8c8rr0)*

**Comment by RaduBerinde** [comment]
I think that's ok.. We need to come up with something for logic tests to allow small errors in decimal-looking values.. A mode that detects decimal strings and allows an error up to some small `epsilon`. We will probably need this even for "real" decimals (due to cases where the last digit of precision has two correct possibilities).

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14013#-:-KeooVGdKoL6-9Cwau06:b-7997m0)*

**Comment by mjibson** [comment]
Ok. What about changing the tests to use `round` to truncate the changing digits?

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14013#-:-KeorIhqoz272bjiSLl7:b-9ucpcf)*

**Comment by RaduBerinde** [comment]
I don't see any problem with that.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14013#-:-Keougzyai4Tw9WNNFnI:b-6pkjr9)*

**Comment by mjibson** [comment]
Updated to only fix decimal.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/parser/aggregate_builtins.go, line 755 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14013#-KeokXbowbxgO-06ob6s:-Kep5sPbS_gpOitsQQ5A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/36974ca43dc8a574df4bd3ce9ad55953bcb4e87f/pkg/sql/parser/aggregate_builtins.go#L755)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

add a comment here explaining the + 3, reference the issue #
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14013#-:-KeqWjz0Q91BoqS4uXxO:bczoc2p)*

**Comment by RaduBerinde** [comment]
:lgtm: Thanks!

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14013#-:-Kesv_P0mEMNxNe4ElVR:b-g2a5fb)*

**Comment by knz** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/aggregate_builtins.go, line 675 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14013#-Ket-ROPitXF5zZfzjJ4:-Ket-ROQ7aSepJnJDGCf:bgiv5ch) ([raw file](https://github.com/cockroachdb/cockroach/blob/25e4c30698f2d524fb8a1ae3c9622daa3800031b/pkg/sql/parser/aggregate_builtins.go#L675)):*
> ```Go
> func newIntVarianceAggregate(_ []Type) AggregateFunc {
> 	return &intVarianceAggregate{
> 		agg: newDecimalVariance(),
> ```

I do not see any tests that mandate int variance use decimal precision.
Can you justify this a bit more in the commit message and/or add the corresponding tests that demonstrate how results go inaccurate otherwise?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14013)*

**Comment by mjibson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/aggregate_builtins.go, line 675 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14013#-Ket-ROPitXF5zZfzjJ4:-KetpQpRNxntENolswo4:b-wx81fl) ([raw file](https://github.com/cockroachdb/cockroach/blob/25e4c30698f2d524fb8a1ae3c9622daa3800031b/pkg/sql/parser/aggregate_builtins.go#L675)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I do not see any tests that mandate int variance use decimal precision.
Can you justify this a bit more in the commit message and/or add the corresponding tests that demonstrate how results go inaccurate otherwise?
</blockquote></details>

`intVarianceAggregate` was already using the decimal implementation. This change just initializes it correctly, so there's on functional change here. I don't think this PR should add analysis or justification of a feature it's not changing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14013)*

**Comment by knz** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/aggregate_builtins.go, line 675 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14013#-Ket-ROPitXF5zZfzjJ4:-KeuJbg0kGWJcZCyZFjC:b2nhb2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/25e4c30698f2d524fb8a1ae3c9622daa3800031b/pkg/sql/parser/aggregate_builtins.go#L675)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

`intVarianceAggregate` was already using the decimal implementation. This change just initializes it correctly, so there's on functional change here. I don't think this PR should add analysis or justification of a feature it's not changing.
</blockquote></details>

Ack

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14013#-:-KeuJdE6DyULETZd5P_W:bnfp4nl)*

**Pull request merged**
