### PR TITLE
sql: move uncommitted-tables check alongside the other consistency checks

### PR DESCRIPTION
**Pull request by RaduBerinde**
Moving the code to check for uncommitted tables before reusing a
prepared plan into `makeOptimizerPlan`, alongside the other
consistency checks. Also improving a testcase to verify this code
path.

Release note: None

### CODE REVIEW

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32734)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/plan.go, line 420 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32734#-LSWi5lm6VmVzfst8FjV:-LSWi5lm6VmVzfst8FjW:b7w2i69) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3ae73576b15c40afd94beac5a6252f51171d58f/pkg/sql/plan.go#L420)):*
> ```Go
> 		// bumped at most once per transaction, even if there are multiple DDL
> 		// operations.
> 		if p.Tables().hasUncommittedTables() ||
> ```

This will cause a subtle change in behavior. We'll now cache a prepared memo based on an uncommitted schema. Before, we'd compile a new memo, but we wouldn't save it to `stmt.Prepared`; we'd effectively just throw it away once we were done with it.

I'm not sure if it's valid to cache the schema in this uncommitted case. Say that version=0, and then we make a schema change so that version gets bumped to 1. We cache a memo based on version=1. Then that txn gets aborted, which would revert the version back to 0. Say a new txn runs and constructs a different schema, but also with version=1. If that's possible, then we'd now have an incorrect plan in the cache, based on the aborted version 1 schema, rather than the new version 1 schema.

Maybe these sorts of scenarios are not possible, but they made me nervous, and that's why I forced recompile of the plan if `hasUncommittedTables` is true, and then did not cache the resulting plan.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32734)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/plan.go, line 420 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32734#-LSWi5lm6VmVzfst8FjV:-LSWynVjDIRqWCxxlVKZ:b-5vlulv) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3ae73576b15c40afd94beac5a6252f51171d58f/pkg/sql/plan.go#L420)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This will cause a subtle change in behavior. We'll now cache a prepared memo based on an uncommitted schema. Before, we'd compile a new memo, but we wouldn't save it to `stmt.Prepared`; we'd effectively just throw it away once we were done with it.

I'm not sure if it's valid to cache the schema in this uncommitted case. Say that version=0, and then we make a schema change so that version gets bumped to 1. We cache a memo based on version=1. Then that txn gets aborted, which would revert the version back to 0. Say a new txn runs and constructs a different schema, but also with version=1. If that's possible, then we'd now have an incorrect plan in the cache, based on the aborted version 1 schema, rather than the new version 1 schema.

Maybe these sorts of scenarios are not possible, but they made me nervous, and that's why I forced recompile of the plan if `hasUncommittedTables` is true, and then did not cache the resulting plan.
</blockquote></details>

But the old code still cached the memo in the Prepare case. So I think your example was still possible if we only Prepare in the old txn.

Anyway, I changed the code to fall through to the third case, and also added a check for this in the prepare case to prevent saving the memo.

**Review by andy-kimball — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32734)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/plan.go, line 420 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32734#-LSWi5lm6VmVzfst8FjV:-LSX6paP3GKvDgmv2Rz-:buh1j32) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3ae73576b15c40afd94beac5a6252f51171d58f/pkg/sql/plan.go#L420)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

But the old code still cached the memo in the Prepare case. So I think your example was still possible if we only Prepare in the old txn.

Anyway, I changed the code to fall through to the third case, and also added a check for this in the prepare case to prevent saving the memo.
</blockquote></details>

Yes, I missed the Prepare case.
___
*[pkg/sql/plan.go, line 387 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32734#-LSX8urTDOy5MpGAX3D0:-LSX8urTDOy5MpGAX3D1:bxw229s) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4afc38dedbde97bc3195d80ff6b8a9f1ee08401/pkg/sql/plan.go#L387)):*
> ```Go
> 	// descriptor versions are bumped at most once per transaction, even if there
> 	// are multiple DDL operations. In this case, we avoid saving or reusing a
> 	// saved memo.
> ```

Can you add a comment explaining why we aren't reusing the memo in uncommitted case?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32734)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/plan.go, line 387 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32734#-LSX8urTDOy5MpGAX3D0:-LSXFa2n1weX6Sngk_2y:b-4ld515) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4afc38dedbde97bc3195d80ff6b8a9f1ee08401/pkg/sql/plan.go#L387)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Can you add a comment explaining why we aren't reusing the memo in uncommitted case?
</blockquote></details>

I thought this is what the comment explains.. I improved it a bit. If you want me to add something specific let me know.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32734)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/plan.go, line 387 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32734#-LSX8urTDOy5MpGAX3D0:-LSXbBYQBYT9ELJTqxJ9:bcuk5tp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4afc38dedbde97bc3195d80ff6b8a9f1ee08401/pkg/sql/plan.go#L387)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I thought this is what the comment explains.. I improved it a bit. If you want me to add something specific let me know.
</blockquote></details>

OK, not sure what I was thinking.

**Pull request merged**
