### PR TITLE
descs/collection: Added memory monitoring to Collection.kvDescriptors

### PR DESCRIPTION
**Pull request by Xiang-Gu**
Collection struct agressively caches descriptors to avoid reading from storage.
Previously, we do not have memory monitoring on those cached descriptors, and
we risk OOM crashes.

This PR adds memory monitoring on one of the cache descriptor set -- the
kvDescriptors -- since it stores all descriptors it reads from storage and it
is done per transaction and not shared between session. This means we would
have one copy of all descriptors for each session opened to the database,
consuming potentially a large amount of memory when we have a lot of
descriptors.

Release note: None

Related: #67049 #71282

### CODE REVIEW

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78516)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @samiskin and @Xiang-Gu)

___
*[pkg/sql/catalog/descs/kv_descriptors.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-MzGCk4n2YZrlO1eqYZW:-MzGCk4n2YZrlO1eqYZX:b-nj6nge) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c211e476dc1840317356b46268cd40c0a47a875/pkg/sql/catalog/descs/kv_descriptors.go#L103)):*
> ```Go
> 		systemNamespace: systemNamespace,
> 		monitor:         monitor,
> 		memAcc:          monitor.MakeBoundAccount(),
> ```

looks like `monitor` can be nil and this call may cause null pointer error. should check it's not nil first :)
___
*[pkg/sql/catalog/descs/kv_descriptors.go, line 277 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-MzGCwPQETUhC1fnS68N:-MzGCwPQETUhC1fnS68O:b-r10wwa) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c211e476dc1840317356b46268cd40c0a47a875/pkg/sql/catalog/descs/kv_descriptors.go#L277)):*
> ```Go
> 		}
> 
> 		if kd.monitor != nil {
> ```

with the previous comment addressed, you may just do `kd.memAcc.Monitor() != nil`. there is no need to keep `monitor` while it's not being used for other purpose.

**Comment by chengxiong-ruan** [comment]
good work btw :)

**Review by ajwerner — COMMENTED** [review]
I'm okay with leaving the monitor as optional: it's strictly better to sometimes monitor than to never monitor, but I agree that we need to be more defensive regarding nils. I think that my preference is to only store the bound account in the struct, we don't need the monitor itself after we've got the bound account, right? My understanding of the BoundAccount code is that an uninitialized bound account will just no-op on all of its operations. That way, we can avoid any defensive checks on use of the bound account throughout the code and just initialize it in the constructor if we have a non-nil monitor. Does that check out?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-:-MzGFRBTDE4SZEFCtyR_:b-e736qt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @samiskin and @Xiang-Gu)

**Review by ajwerner — COMMENTED** [review]
> we'd need to store a BoundAccount pointer in the struct instead.

I don't think this is true. Non-pointer values will have their address taken when methods on the pointer receiver are called on them. In these cases, the value is in a struct, so the right thing will happen. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-:-MzGK_Hw9gQDgJvHjaPq:bq5qw80)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @samiskin and @Xiang-Gu)

**Comment by chengxiong-ruan** [comment]
oh, I meant to make the `if b == nil {return nil}` part of the operator methods work we'd need a pointer in struct I think. Maybe I misunderstood the `no-op` you mentioned above lol.

**Review by ajwerner — COMMENTED** [review]
ah yeah you're totally right. Another approach is to make an `UnlimitedMonitor` that we attach the factory and use when we don't have one provided. That might be better from an observability perspective.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-:-MzGhrMn59h0BX4UTJLU:b-ra2rwg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @samiskin and @Xiang-Gu)

**Review by ajwerner — COMMENTED** [review]
See `NewUnlimitedMonitor` 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-:-MzGi8l_C_i1sfe5Vhon:bcwytsb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @samiskin and @Xiang-Gu)

**Review by Xiang-Gu — COMMENTED** [review]
Thanks. I've changed the code so that if a nil monitor is injected to MakeCollection, the Collection will self-create one with unlimited budget, so that any downstream resource allocation/release code will effectively become no-ops. We also don't need to worry about nil monitors (and the potential field/method access on nil monitors) because now it will never be nil.

RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-:-MzQXf1B3wNPiGfSfeSo:b3jpqqb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan and @samiskin)

___
*[pkg/sql/catalog/descs/kv_descriptors.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-MzGCk4n2YZrlO1eqYZW:-MzQYJR53O0VBd7-NTNJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c211e476dc1840317356b46268cd40c0a47a875/pkg/sql/catalog/descs/kv_descriptors.go#L103)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

looks like `monitor` can be nil and this call may cause null pointer error. should check it's not nil first :)
</blockquote></details>

Done.
___
*[pkg/sql/catalog/descs/kv_descriptors.go, line 277 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-MzGCwPQETUhC1fnS68N:-MzQYKRsDLmaJoxDgAuV:bwvbvr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c211e476dc1840317356b46268cd40c0a47a875/pkg/sql/catalog/descs/kv_descriptors.go#L277)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

with the previous comment addressed, you may just do `kd.memAcc.Monitor() != nil`. there is no need to keep `monitor` while it's not being used for other purpose.
</blockquote></details>

Done. Now only an BoundAccount is kept inside KvDescriptors.

**Review by ajwerner — CHANGES_REQUESTED** [review]
This is getting close. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-:-MzRYiQe-umCgybFhbUl:b-ix7odn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @samiskin, and @Xiang-Gu)

___
*[pkg/sql/catalog/descs/collection.go, line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-MzRY3Q6-8OqqNioTJuy:-MzRY3Q6-8OqqNioTJuz:b98oaxz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e28010abb59a7a6795a164536951259d0434d7f3/pkg/sql/catalog/descs/collection.go#L60)):*
> ```Go
> 		monitor = mon.NewUnlimitedMonitor(ctx, "CollectionMonUnlimited", mon.MemoryResource,
> 			nil /* curCount */, nil /* maxHist */, 0 /* noteworthy */, settings)
> 		isMonitorSelfCreated = true
> ```

let's not do this. The collection is a somewhat performance critical object, I'd rather not do this allocation every time we initialize one. Instead can we construct the unlimited monitor on the factor? If the problem with doing that is that we need somebody to close the unlimited monitor, have a close method on the factory and then attach the factory to the stopper



_Code quote:_
```Go
	isMonitorSelfCreated := false
	if monitor == nil {
		// If an upstream monitor is not provided, create one for itself with unlimited budget so that any
		// future resource allocation/release code on Collection can work properly as no-ops.
		monitor = mon.NewUnlimitedMonitor(ctx, "CollectionMonUnlimited", mon.MemoryResource,
			nil /* curCount */, nil /* maxHist */, 0 /* noteworthy */, settings)
		isMonitorSelfCreated = true
	}
```
___
*[pkg/sql/catalog/descs/kv_descriptors.go, line 275 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-MzRYUlXA0JJpDUrrhc1:-MzRYUlXA0JJpDUrrhc2:b-8diww6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e28010abb59a7a6795a164536951259d0434d7f3/pkg/sql/catalog/descs/kv_descriptors.go#L275)):*
> ```Go
> 		// Monitor memory usage of the catalog recently read from storage.
> 		if err := c.ForEachDescriptorEntry(func(desc catalog.Descriptor) error {
> 			if err := kd.memAcc.Grow(ctx, int64(unsafe.Sizeof(desc))); err != nil {
> ```

I don't think `unsafe.SizeOf` is what we want. I think what we want is something derived from the `Size()` method on the underlying protocol buffer. unsafe.SizeOf is just going to be 2 words here :(  



_Code quote:_
```Go
d
```

**Review by Xiang-Gu — COMMENTED** [review]
Per our discussion, I created a default, unlimited monitor in the Collection factory, and whenever an upstream monitor is not provided, that default one will be used.

Also, another major change is that I added a field `byteSize` in nstree.Catalog that keeps track of memory usage of its underlying map. It's much easier to track the right number of memory usage here. As a result, this PR is slightly bigger but those additional logic should be straightforward.

RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-:-MzVgCDD6Lcgt3yUEwgD:bi3hvkn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @samiskin)

___
*[pkg/sql/catalog/descs/collection.go, line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-MzRY3Q6-8OqqNioTJuy:-MzVdp5w2oE6MWcDVAqf:b-i6kpt) ([raw file](https://github.com/cockroachdb/cockroach/blob/e28010abb59a7a6795a164536951259d0434d7f3/pkg/sql/catalog/descs/collection.go#L60)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

let's not do this. The collection is a somewhat performance critical object, I'd rather not do this allocation every time we initialize one. Instead can we construct the unlimited monitor on the factor? If the problem with doing that is that we need somebody to close the unlimited monitor, have a close method on the factory and then attach the factory to the stopper
</blockquote></details>

done. I've put a default, unlimited monitor in the factory such that if an upstream monitor is not provided, that default one will be used.
___
*[pkg/sql/catalog/descs/kv_descriptors.go, line 275 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-MzRYUlXA0JJpDUrrhc1:-MzReAn_EBrXZfYPJ0_z:b9oza7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/e28010abb59a7a6795a164536951259d0434d7f3/pkg/sql/catalog/descs/kv_descriptors.go#L275)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't think `unsafe.SizeOf` is what we want. I think what we want is something derived from the `Size()` method on the underlying protocol buffer. unsafe.SizeOf is just going to be 2 words here :(  
</blockquote></details>

Per the discussion on slack, I modified the nstree.Catalog object to keep track of the memory usage of its underlying map in bytes. This newly added byteSize field is put into and can be accessed from the (immutable) Catalog object. The place to actually increase/decrease the field is added in the corresponding "setters" of the mutableCatalog object.

It is relatively straightforward but does make this PR slightly bigger.

**Review by ajwerner — COMMENTED** [review]
Just little stuff and this is ready to go 

> Reviewed 3 of 10 files at r1, 3 of 6 files at r2, 2 of 7 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-:-MzaacUcCV9t0HZoIRVm:b-9nyuuk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, @samiskin, and @Xiang-Gu)

___
*[pkg/sql/catalog/descs/collection.go, line 144 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-Mza_r6NEkqZhMQovEaw:-Mza_r6NEkqZhMQovEax:b20socf) ([raw file](https://github.com/cockroachdb/cockroach/blob/54d19942c506e4a6a313ab3490e3147f479197a9/pkg/sql/catalog/descs/collection.go#L144)):*
> ```Go
> 	// factory's default, unlimited monitor will be used, which essentially turns
> 	// any downstream memory allocation/release calls to no-ops.
> 	monitor *mon.BytesMonitor
> ```

I don't see you using this field, do we need to hold on to the monitor?



_Code quote:_
```Go
	// monitor is injected to track memory usage of this Collection.
	// It will be further passed down to each descriptor set where we create an
	// account to track memory allocation/releases.
	// If the maker of this Collection does not provide a monitor, the Collection
	// factory's default, unlimited monitor will be used, which essentially turns
	// any downstream memory allocation/release calls to no-ops.
	monitor *mon.BytesMonitor
```
___
*[pkg/sql/catalog/descs/factory.go, line 51 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-Mza_7KXB5omry5OB8C2:-Mza_7KYDshd4b6W7nZp:bq2emsa) ([raw file](https://github.com/cockroachdb/cockroach/blob/54d19942c506e4a6a313ab3490e3147f479197a9/pkg/sql/catalog/descs/factory.go#L51)):*
> ```Go
> 		hydratedTables: hydratedTables,
> 		systemDatabase: newSystemDatabaseNamespaceCache(leaseMgr.Codec()),
> 		defaultMonitor: mon.NewUnlimitedMonitor(ctx, "CollectionFactoryDefaultUnlimitedMonitor", mon.MemoryResource, nil /* curCount */, nil /* maxHist */, 0 /* noteworthy */, settings),
> ```

nit: wrap this
___
*[pkg/sql/catalog/descs/kv_descriptors.go, line 274 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-Mza_Dn5EDG8CQzc0wBT:-Mza_Dn5EDG8CQzc0wBU:b-smhb7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/54d19942c506e4a6a313ab3490e3147f479197a9/pkg/sql/catalog/descs/kv_descriptors.go#L274)):*
> ```Go
> 		// Monitor memory usage of the catalog recently read from storage.
> 		if err := kd.memAcc.Grow(ctx, c.ByteSize()); err != nil {
> 			log.Info(ctx, "Memory usage exceeds limit for kvDescriptors.allDescriptors.\n")
> ```

1) the logging library adds newlines for you
2) if you've got an error and you're going to log, you may as well log the error. 

I don't think it necessarily makes sense to log here. I think instead I'd wrap the error and pass it up the stack. 
___
*[pkg/sql/catalog/nstree/catalog.go, line 193 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-MzaaPv326EFPlH71rck:-MzaaPv326EFPlH71rcl:b-ya8mhx) ([raw file](https://github.com/cockroachdb/cockroach/blob/54d19942c506e4a6a313ab3490e3147f479197a9/pkg/sql/catalog/nstree/catalog.go#L193)):*
> ```Go
> 	mc.underlying.maybeInitialize()
> 	if removed := mc.underlying.byID.delete(id); removed != nil {
> 		mc.byteSize -= removed.(catalog.Descriptor).ByteSize()
> ```

May I request that you file an issue to audit the `ByteSize` methods of descriptors and make them more realistic? Not relevant for this PR, but I think we under-count by a pretty large factor. 
___
*[pkg/sql/catalog/descs/collection_test.go, line 617 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-Mza_iuN6pgro8uGaX61:-Mza_iuN6pgro8uGaX62:b6x5q3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/54d19942c506e4a6a313ab3490e3147f479197a9/pkg/sql/catalog/descs/collection_test.go#L617)):*
> ```Go
> // 3.	Change the monitor budget to something small. Repeat step 2 and expect an error
> // 		being thrown out when reading all those descriptors into memory to validate the
> //		memory monitor indeed kicked in and had an effect.
> ```

nit: indentation



_Code quote:_
```Go
// 3.	Change the monitor budget to something small. Repeat step 2 and expect an error
// 		being thrown out when reading all those descriptors into memory to validate the
//		memory monitor indeed kicked in and had an effect.
```

**Review by Xiang-Gu — COMMENTED** [review]
Thanks. RFAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-:-Mzpl-zI6dkIuxRqHd7b:b-hv3bge)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @samiskin)

___
*[pkg/sql/catalog/descs/collection.go, line 144 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-Mza_r6NEkqZhMQovEaw:-MzpYjai-WVHHn5FaOqq:b-mwxzmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/54d19942c506e4a6a313ab3490e3147f479197a9/pkg/sql/catalog/descs/collection.go#L144)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't see you using this field, do we need to hold on to the monitor?
</blockquote></details>

correct, it is not used. I have removed it now. 
___
*[pkg/sql/catalog/descs/factory.go, line 51 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-Mza_7KXB5omry5OB8C2:-MzpZhHN8SlJm8uNPGos:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/54d19942c506e4a6a313ab3490e3147f479197a9/pkg/sql/catalog/descs/factory.go#L51)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: wrap this
</blockquote></details>

done
___
*[pkg/sql/catalog/descs/kv_descriptors.go, line 274 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-Mza_Dn5EDG8CQzc0wBT:-MzpaOzP3650SPEdjUIH:b-rnrapz) ([raw file](https://github.com/cockroachdb/cockroach/blob/54d19942c506e4a6a313ab3490e3147f479197a9/pkg/sql/catalog/descs/kv_descriptors.go#L274)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

1) the logging library adds newlines for you
2) if you've got an error and you're going to log, you may as well log the error. 

I don't think it necessarily makes sense to log here. I think instead I'd wrap the error and pass it up the stack. 
</blockquote></details>

done. 
___
*[pkg/sql/catalog/nstree/catalog.go, line 193 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-MzaaPv326EFPlH71rck:-MzpiqixB3e9OWDAiL5Q:b-qfwyhb) ([raw file](https://github.com/cockroachdb/cockroach/blob/54d19942c506e4a6a313ab3490e3147f479197a9/pkg/sql/catalog/nstree/catalog.go#L193)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

May I request that you file an issue to audit the `ByteSize` methods of descriptors and make them more realistic? Not relevant for this PR, but I think we under-count by a pretty large factor. 
</blockquote></details>

Done, see issue #79355.
___
*[pkg/sql/catalog/descs/collection_test.go, line 617 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-Mza_iuN6pgro8uGaX61:-Mzpj4OZ2ebfnh0Abj6Q:bllgb13) ([raw file](https://github.com/cockroachdb/cockroach/blob/54d19942c506e4a6a313ab3490e3147f479197a9/pkg/sql/catalog/descs/collection_test.go#L617)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: indentation
</blockquote></details>

I think this might be a bug of reviewable because I didn't see this locally nor on Github (PR --> files changed).

**Review by ajwerner — APPROVED** [review]
:lgtm_strong: 

> Reviewed 4 of 5 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-:-N-6FFV10MInKWPAKeJh:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @samiskin, and @Xiang-Gu)

___
*[pkg/sql/catalog/descs/collection_test.go, line 617 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78516#-Mza_iuN6pgro8uGaX61:-N-6F7vfCCJZ-lawqd3w:bip4xwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/54d19942c506e4a6a313ab3490e3147f479197a9/pkg/sql/catalog/descs/collection_test.go#L617)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

I think this might be a bug of reviewable because I didn't see this locally nor on Github (PR --> files changed).
</blockquote></details>

I'm pointing at a mix between tabs and spacing in the comment.

**Pull request merged**
