### PR TITLE
distsql: account for aggregate func memory usage

### PR DESCRIPTION
**Pull request by solongordon**
The size of AggregateFunc implementations was previously not taken into
account by the Aggregator processor's memory monitoring.

Also, some aggregate builtins were not accounting for additional memory
usage during accumulation, particularly those which relied on Decimals, which
can grow arbitrarily large. I added more monitoring where appropriate.

The original issue warns against calling `Grow()` for every row. I'm calling
`ResizeTo()`, which is a no-op when the size hasn't actually changed. That
seems to be the case the vast majority of the time here, so I don't think it's
a bottleneck. There is still some overhead from the method dispatch, which
could be avoided by keeping track of the previous size on the AggregatorFunc
side and only calling `ResizeTo` when it changes. Not sure it's enough of a
performance hit to warrant that though. (We're talking about single digit
nanoseconds per row.) I can add that logic if reviewers feel it's worth it.

```
name                                   old time/op  new time/op  delta
AvgAggregateInt/count=1000-4           92.1µs ± 8%  96.8µs ± 5%     ~     (p=0.151 n=5+5)
AvgAggregateSmallInt/count=1000-4      27.1µs ± 3%  28.1µs ± 3%   +3.92%  (p=0.032 n=5+5)
AvgAggregateFloat/count=1000-4         7.35µs ± 1%  7.55µs ± 2%   +2.86%  (p=0.008 n=5+5)
AvgAggregateDecimal/count=1000-4        152µs ± 3%   162µs ± 2%   +6.15%  (p=0.008 n=5+5)
CountAggregate/count=1000-4            3.50µs ± 1%  3.49µs ± 1%     ~     (p=0.841 n=5+5)
SumIntAggregateInt/count=1000-4        14.8µs ± 2%  14.7µs ± 1%     ~     (p=0.310 n=5+5)
SumAggregateInt/count=1000-4           78.0µs ± 1%  83.4µs ± 1%   +6.92%  (p=0.008 n=5+5)
SumAggregateSmallInt/count=1000-4      21.1µs ± 2%  21.5µs ± 1%   +1.90%  (p=0.032 n=5+5)
SumAggregateFloat/count=1000-4         3.90µs ± 1%  3.99µs ± 1%   +2.32%  (p=0.008 n=5+5)
SumAggregateDecimal/count=1000-4        142µs ± 2%   150µs ± 2%   +5.26%  (p=0.008 n=5+5)
MaxAggregateInt/count=1000-4           8.72µs ± 2%  9.25µs ± 1%   +6.10%  (p=0.008 n=5+5)
MaxAggregateFloat/count=1000-4         8.75µs ± 2%  9.23µs ± 1%   +5.48%  (p=0.008 n=5+5)
MaxAggregateDecimal/count=1000-4       61.3µs ±10%  68.2µs ±27%     ~     (p=0.841 n=5+5)
MinAggregateInt/count=1000-4           8.66µs ± 2%  9.60µs ± 2%  +10.81%  (p=0.008 n=5+5)
MinAggregateFloat/count=1000-4         8.63µs ± 2%  9.38µs ± 2%   +8.67%  (p=0.008 n=5+5)
MinAggregateDecimal/count=1000-4       37.7µs ± 6%  42.8µs ±16%     ~     (p=0.056 n=5+5)
VarianceAggregateInt/count=1000-4      9.18ms ± 2%  9.71ms ± 5%   +5.70%  (p=0.032 n=5+5)
VarianceAggregateFloat/count=1000-4    9.31µs ± 1%  9.26µs ± 2%     ~     (p=0.548 n=5+5)
VarianceAggregateDecimal/count=1000-4  9.22ms ± 1%  9.27ms ± 2%     ~     (p=0.548 n=5+5)
StdDevAggregateInt/count=1000-4        9.20ms ± 1%  9.47ms ± 4%     ~     (p=0.056 n=5+5)
StdDevAggregateFloat/count=1000-4      13.1µs ± 1%  13.8µs ± 3%   +5.77%  (p=0.008 n=5+5)
StdDevAggregateDecimal/count=1000-4    9.33ms ± 2%  9.32ms ± 3%     ~     (p=1.000 n=5+5)
```

### CODE REVIEW

**Review by asubiotto — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28303)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 768 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28303#-LJK_Occ0yYVag0KsGpv:-LJK_Occ0yYVag0KsGpw:b-p0d2lj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a59d3c06fb1b62115667f9bde17a9e0b449b94f/pkg/sql/sem/builtins/aggregate_builtins.go#L768)):*
> ```Go
> 	if c < 0 {
> 		a.max = datum
> 		if err := a.acc.ResizeTo(ctx, int64(datum.Size())); err != nil {
> ```

Another idea for a performance improvement here is that you could get the type of `Datum` that an aggregate func operates on when created and call `DatumTypeSize(withTheType)` to see if the datum size is variable or not which would avoid a call to `Size` and `ResizeTo`.
___
*[pkg/sql/sem/builtins/aggregate_builtins_test.go, line 296 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28303#-LJKaW8a6FULat-sjKhy:-LJKaW8bD4NkLZlQgAfm:bm24gq0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a59d3c06fb1b62115667f9bde17a9e0b449b94f/pkg/sql/sem/builtins/aggregate_builtins_test.go#L296)):*
> ```Go
> 			b.Errorf("taking result of aggregate implementation %T failed", aggImpl)
> 		}
> 		aggImpl.Close(context.Background())
> ```

Heads up that I don't think this will get executed if we hit a `Fatal` or an `Error` (I think) so you'll get a confusing panic that the memory account still has bytes in it. Not sure whether we actually care or not since we'd have to solve that with executing a func with a defer inside on each loop of `b.N` (or we could also be careful to close on `Fatal` or `Error`).

**Review by solongordon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28303)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 768 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28303#-LJK_Occ0yYVag0KsGpv:-LJU-C0yEVUlnrN3wj-M:b-slq55f) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a59d3c06fb1b62115667f9bde17a9e0b449b94f/pkg/sql/sem/builtins/aggregate_builtins.go#L768)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Another idea for a performance improvement here is that you could get the type of `Datum` that an aggregate func operates on when created and call `DatumTypeSize(withTheType)` to see if the datum size is variable or not which would avoid a call to `Size` and `ResizeTo`.
</blockquote></details>

Nice, I was not aware of this method. Done.
___
*[pkg/sql/sem/builtins/aggregate_builtins_test.go, line 296 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28303#-LJKaW8a6FULat-sjKhy:-LJUM4jE50VdifJMiP1Z:b-28uxxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a59d3c06fb1b62115667f9bde17a9e0b449b94f/pkg/sql/sem/builtins/aggregate_builtins_test.go#L296)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Heads up that I don't think this will get executed if we hit a `Fatal` or an `Error` (I think) so you'll get a confusing panic that the memory account still has bytes in it. Not sure whether we actually care or not since we'd have to solve that with executing a func with a defer inside on each loop of `b.N` (or we could also be careful to close on `Fatal` or `Error`).
</blockquote></details>

Yeah, I was a bit worried about this too. I went ahead and wrapped it in a func.

**Review by asubiotto — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28303)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 748 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28303#-LJUZ5A_6IdYB8toxAx3:-LJUZ5A_6IdYB8toxAx4:b-3jqocb) ([raw file](https://github.com/cockroachdb/cockroach/blob/709d80a077df127a2bdf43406a2f0463b28be290/pkg/sql/sem/builtins/aggregate_builtins.go#L748)):*
> ```Go
> 
> 	acc       mon.BoundAccount
> 	datumSize uintptr
> ```

datumSize doesn't seem to be used, I think you can get rid of it
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 754 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28303#-LJUaH2R3f9bwY3h40AD:-LJUaH2R3f9bwY3h40AE:b-yufno9) ([raw file](https://github.com/cockroachdb/cockroach/blob/709d80a077df127a2bdf43406a2f0463b28be290/pkg/sql/sem/builtins/aggregate_builtins.go#L754)):*
> ```Go
> func newMaxAggregate(params []types.T, evalCtx *tree.EvalContext) tree.AggregateFunc {
> 	datumSize, variable := tree.DatumTypeSize(params[0])
> 	if variable {
> ```

I was thinking that you should `Grow` the account here to get a lower bound for variables or actual memory for fixed datums but that'll be messy because this constructor doesn't return an error. You could do that either in `Add` or just call out that you won't track it since it's constant (which is fine, but deserves a comment).

**Review by solongordon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28303)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 748 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28303#-LJUZ5A_6IdYB8toxAx3:-LJUcubGDwPOtwSUksl0:bdt0qc) ([raw file](https://github.com/cockroachdb/cockroach/blob/709d80a077df127a2bdf43406a2f0463b28be290/pkg/sql/sem/builtins/aggregate_builtins.go#L748)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

datumSize doesn't seem to be used, I think you can get rid of it
</blockquote></details>

It's used in `Size()`.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 754 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28303#-LJUaH2R3f9bwY3h40AD:-LJUcdLQ8tYF-ZJjqZb8:b-3kj1ih) ([raw file](https://github.com/cockroachdb/cockroach/blob/709d80a077df127a2bdf43406a2f0463b28be290/pkg/sql/sem/builtins/aggregate_builtins.go#L754)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I was thinking that you should `Grow` the account here to get a lower bound for variables or actual memory for fixed datums but that'll be messy because this constructor doesn't return an error. You could do that either in `Add` or just call out that you won't track it since it's constant (which is fine, but deserves a comment).
</blockquote></details>

Yeah, I'm avoiding the messiness by including `datumSize` in the implementation size reported by the `Size()` method. So it's accounted for in the aggregator's memory monitoring. Does that seem reasonable? This could use a better comment I guess.

**Review by asubiotto — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28303)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 748 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28303#-LJUZ5A_6IdYB8toxAx3:-LJUlqBiDprPR2JMIzzT:bjny5vc) ([raw file](https://github.com/cockroachdb/cockroach/blob/709d80a077df127a2bdf43406a2f0463b28be290/pkg/sql/sem/builtins/aggregate_builtins.go#L748)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

It's used in `Size()`.
</blockquote></details>

Ah, didn't see that
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 754 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28303#-LJUaH2R3f9bwY3h40AD:-LJUlnejA3k0Ng3yIIx2:b2313op) ([raw file](https://github.com/cockroachdb/cockroach/blob/709d80a077df127a2bdf43406a2f0463b28be290/pkg/sql/sem/builtins/aggregate_builtins.go#L754)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Yeah, I'm avoiding the messiness by including `datumSize` in the implementation size reported by the `Size()` method. So it's accounted for in the aggregator's memory monitoring. Does that seem reasonable? This could use a better comment I guess.
</blockquote></details>

Yup, that does seem reasonable. I would definitely add a comment.

**Pull request merged**
