### PR TITLE
sql: remove range loop copies > 128 bytes

### PR DESCRIPTION
**Pull request by jordanlewis**
This commit removes code that uses a value range loop over a slice,
where the value's type is over 128 bytes in size. It was mostly
automatically generated, using the following ruleguard ruleset:

```
// +build ignore

package gorules

import "github.com/quasilyte/go-ruleguard/dsl/fluent"

func largeloopslicecopy(m fluent.Matcher) {
	m.Match(
		`for _, $v := range $s { $b } `,
	).
		Where(m["s"].Type.Underlying().Is(`[]$T`) && m["v"].Type.Size > 128).
		Suggest(`for i := range $s {
$v := &$s[i]
$b
} `)
	m.Match(
		`for $i, $v := range $s { $b } `,
	).
		Where(m["s"].Type.Underlying().Is(`[]$T`) && m["v"].Type.Size > 128).
		Suggest(`for $i := range $s {
$v := &$s[$i]
$b
} `)
}
```

Some small manual fixups were required.

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

I'm assuming we'll want to add a linter too, right? We'd also need to fixup other packages too, I guess, for that.

> Reviewed 24 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57353#-:-MNW1Ytl5cWtRcLZL8FK:b-qnvsuy)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/sem/tree/create.go, line 1569 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57353#-MNW1UDW3dOYAaSM9eCh:-MNW1UDW3dOYAaSM9eCi:b-rpyhru) ([raw file](https://github.com/cockroachdb/cockroach/blob/6785859e676861aa1a921085d6968b2981e954bb/pkg/sql/sem/tree/create.go#L1569)):*
> ```Go
> 				}
> 
> 				if err != nil {
> ```

This probably should be a part of separate commit/PR.

**Review by yuzefovich — COMMENTED** [review]
Hm, it didn't catch the decimal copying in `arrowbatchconverter` - I guess the size of empty `apd.Decimal` isn't large enough.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57353#-:-MNW2D8A50lEW8K7WGkp:b-760m38)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by jordanlewis** [comment]
That's in `pkg/col`, is the reason.

**Review by RaduBerinde — APPROVED** [review]
Nice! LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57353#-:-MNW5sUc4CWl56x3NDxk:bcyhil1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by mgartner** [comment]
This all looks fine to me, but wanted to call that out that it's possible that value range loops are used in some places to avoid mutating the values in the slice.

**Comment by jordanlewis** [comment]
> This all looks fine to me, but wanted to call that out that it's possible that value range loops are used in some places to avoid mutating the values in the slice.

Indeed, had a test failure because of this. Scary!

**Pull request closed without merging**
