### PR TITLE
opt: Round decimal values before check constraints

### LINKED ISSUE #35364: sql: CBO fails to validate/enforce schema constraints prior to running CHECK constraints
This is a regression from the HP code. Found while investigating #35040.

```sql
CREATE TABLE d(x DECIMAL(1,0) CHECK (x = 0));
INSERT INTO d(x) VALUES (0); -- ok
UPDATE d SET x = 0.1; -- OK in HP and PostgreSQL, fails with CBO enabled
```

The problem is that column type constraints (width precision etc) must be applied (and the results truncated apropriately) prior to running the CHECK constraints.

This is non-trivial to fix in CBO yet as it requires a SQL built-in function able to apply column restrictions (this is not the same as performing a cast) and we don't have code to that effect yet.

My recommendation would be to temporarily disable CHECK planning in the CBO for 19.1, and improve the code towards a better fix post-release.

### PR DESCRIPTION
**Pull request by andy-kimball**
opt: Round decimal values before check constraints

The PG spec requires the following DECIMAL type behavior:

  If the scale of a value to be stored is greater than the declared scale
  of the column, the system will round the value to the specified number
  of fractional digits.

This is currently happening at the very end of the mutation operator, after
any check constraints. This commit moves the rounding to occur before check
constraints. Rounding must be performed on inserted and updated values before
computed columns are evaluated as well, since computed columns should run on
the final values to be inserted/updated.

Fixes #35364

Release note (sql change): Computed columns are now evaluated after rounding
any decimal values in input columns. Previously, computed columns used input
values before rounding.

### CODE REVIEW

**Review by knz — APPROVED** [review]
2nd commit LGTM, modulo fixing the upsert test.

Not reviewing the 1st commit due to lack of expertise; you'll need to rely on another reviewer.

> Reviewed 4 of 4 files at r1, 23 of 23 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-:-LabGweQ8VrpJ8bE3w2U:b83v335)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/upsert, line 924 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-LabG5HG6i8W6E0GH5Wp:-LabG5HG6i8W6E0GH5Wq:b-cjpa25) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ec51811db7da89293dd4646ed26ba2f427b9ca/pkg/sql/logictest/testdata/logic_test/upsert#L924)):*
> ```
> 
> query TT
> SELECT * FROM t35364
> ```

rowsort
___
*[pkg/sql/logictest/testdata/logic_test/upsert, line 934 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-LabG68U25VUHuC-44qm:-LabG68U25VUHuC-44qn:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ec51811db7da89293dd4646ed26ba2f427b9ca/pkg/sql/logictest/testdata/logic_test/upsert#L934)):*
> ```
> query TT
> SELECT * FROM t35364
> ----
> ```

ditto
___
*[pkg/sql/opt/cat/column.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-LabGCrHBfvO0AmacM3f:-LabGCrHBfvO0AmacM3g:b-kuppo) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ec51811db7da89293dd4646ed26ba2f427b9ca/pkg/sql/opt/cat/column.go#L50)):*
> ```Go
> 	//   Int      : # bits (16, 32, 64, etc)
> 	//   Bit Array: # bits
> 	//   String   : rune count
> ```

byte array is number of bytes IIRC

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

Are there any other types with this problem? Large INT8 stored in INT4 column? (though I'm not sure we actually restrict INT4s to the 32-bit range)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-:-LakhDdG2OT1QztByZPl:b-2y41ge)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, and @rytaft)

___
*[pkg/sql/opt/optbuilder/insert.go, line 930 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-LakfpOb-jKQ6GhnYduS:-LakfpOb-jKQ6GhnYduT:b-r9c1tj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efa9871e919715b41656ed94193279559122a01/pkg/sql/opt/optbuilder/insert.go#L930)):*
> ```Go
> 		// columns, as those columns can be used by RETURNING columns.
> 		if mb.updateScopeOrds[i] != -1 {
> 			mb.updateScopeOrds[i] = len(projectionsScope.cols) - 1
> ```

[nit] I would do `scopeColOrdinal := len() - 1` right after the `synthesizeColumn` call, so it's more clear why.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-LafZArD2IrOunk_voRg:-LafZArD2IrOunk_voRh:b-ayk1fu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efa9871e919715b41656ed94193279559122a01/pkg/sql/opt/optbuilder/mutation_builder.go#L77)):*
> ```Go
> 	// inserted are set to -1 (e.g. delete-only mutation columns). insertScopeOrds
> 	// is empty if this is not an Insert/Upsert operator.
> 	insertScopeOrds []int
> ```

[nit] consider making a type for this instead of `int` (we wouldn't need to include "ScopeOrd" in the name of every variable)
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-Lakg6WU7owR3urDLNvd:-Lakg6WU7owR3urDLNve:b13bk0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efa9871e919715b41656ed94193279559122a01/pkg/sql/opt/optbuilder/mutation_builder.go#L135)):*
> ```Go
> 
> 	// Allocate segmented array of scope column ordinals.
> 	scopeOrds := make([]int, tab.DeletableColumnCount()*4+tab.CheckCount())
> ```

[nit] `n := tab.DeletableColumnCount()` so we don't repeat it so many times below

**Review by rytaft — APPROVED** [review]
:lgtm:

mostly just a lot of nits about changing wording from "truncate" to "round", since truncation is a different thing

> Reviewed 4 of 4 files at r1, 23 of 23 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-:-Lapq53eAeo_kcAp2pWH:bpdinie)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andy-kimball and @justinj)

___
*[pkg/sql/opt/optbuilder/insert.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-LaplbKU5CrvGSch56D2:-LaplbKU5CrvGSch56D3:b-g6fapo) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efa9871e919715b41656ed94193279559122a01/pkg/sql/opt/optbuilder/insert.go#L289)):*
> ```Go
> 		// Add additional columns for computed expressions that may depend on any
> 		// updated columns.
> 		mb.addComputedColsForUpdate()
> ```

why did you remove this?
___
*[pkg/sql/opt/optbuilder/insert.go, line 231 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-LapkkmJ6Cg-b7N_9eW4:-LapkkmJ6Cg-b7N_9eW5:b-gimqoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ec51811db7da89293dd4646ed26ba2f427b9ca/pkg/sql/opt/optbuilder/insert.go#L231)):*
> ```Go
> 	mb.addDefaultColsForInsert()
> 
> 	// Possibly truncate DECIMAL-related columns containing insertion values. Do
> ```

truncate -> round
___
*[pkg/sql/opt/optbuilder/insert.go, line 595 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-LaplKxR6jULuTQ37G0e:-LaplKxS8KsUj8Wfntfc:b-gimqoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ec51811db7da89293dd4646ed26ba2f427b9ca/pkg/sql/opt/optbuilder/insert.go#L595)):*
> ```Go
> 	)
> 
> 	// Possibly truncate DECIMAL-related computed columns.
> ```

truncate -> round
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 494 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-Lapdn5NC69yvQUkwC0n:-Lapdn5NC69yvQUkwC0o:b-y6zlzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efa9871e919715b41656ed94193279559122a01/pkg/sql/opt/optbuilder/mutation_builder.go#L494)):*
> ```Go
> 			scopeOrd := mb.mapToReturnScopeOrd(i)
> 			if scopeOrd == -1 {
> 				panic(fmt.Sprintf("column %d is not available in the mutation input", i))
> ```

should this be an AssertionError?
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 503 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-LapdbqkA7L7Wj2l-Iau:-LapdbqkA7L7Wj2l-Iav:bbhnpyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efa9871e919715b41656ed94193279559122a01/pkg/sql/opt/optbuilder/mutation_builder.go#L503)):*
> ```Go
> }
> 
> // mapToReturnScopeOrd returns the scope column that provides the final value
> ```

[nit] ordinal of the scope column
___
*[pkg/sql/opt/optbuilder/update.go, line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-LapfjrqAV7I-BRaJGzY:-LapfjrqAV7I-BRaJGzZ:b-lzcjj5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efa9871e919715b41656ed94193279559122a01/pkg/sql/opt/optbuilder/update.go#L213)):*
> ```Go
> 		checkDatumTypeFitsColumnType(mb.tab.Column(ord), sourceCol.typ)
> 
> 		// Add ordinal of new column scope to the list of columns to update.
> ```

column scope -> scope column?
___
*[pkg/sql/opt/optbuilder/update.go, line 285 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-LapnyzH-6MCsh34cB6h:-LapnyzI5fxgAEh_An-W:b-gimqoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ec51811db7da89293dd4646ed26ba2f427b9ca/pkg/sql/opt/optbuilder/update.go#L285)):*
> ```Go
> 	mb.outScope = projectionsScope
> 
> 	// Possibly truncate DECIMAL-related columns that were updated. Do this
> ```

truncate -> round
___
*[pkg/sql/opt/optbuilder/update.go, line 316 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-Lapo1b8EEdVrDSE76Ib:-Lapo1b8EEdVrDSE76Ic:b-gimqoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ec51811db7da89293dd4646ed26ba2f427b9ca/pkg/sql/opt/optbuilder/update.go#L316)):*
> ```Go
> 	)
> 
> 	// Possibly truncate DECIMAL-related computed columns.
> ```

truncate -> round
___
*[pkg/sql/opt/optbuilder/testdata/insert, line 1355 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-LapoEb77M5Qe8owqhoR:-LapoEb84VHksUpBNCGq:b-yu8tbb) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ec51811db7da89293dd4646ed26ba2f427b9ca/pkg/sql/opt/optbuilder/testdata/insert#L1355)):*
> ```
> 
> # ------------------------------------------------------------------------------
> # Test decimal column truncation.
> ```

rounding

**Review by andy-kimball — COMMENTED** [review]
@raduberinde, the PG rules only specify rounding for `Decimal` types, not for any other types. There is a separate group of limit checks that raise errors if input values do not fit into the target type's precision. Those are run by the execution mutation operator. They can happen at the very end, just before the mutation occurs. The rounding has to happen earlier, hence the need for this fix.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-:-Laq1G1ZDV7C3ZSd35mw:b5i4aje)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @justinj, @knz, @RaduBerinde, and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/upsert, line 924 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-LabG5HG6i8W6E0GH5Wp:-Laq1mWl4x9LZry-YQAI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ec51811db7da89293dd4646ed26ba2f427b9ca/pkg/sql/logictest/testdata/logic_test/upsert#L924)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

rowsort
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/upsert, line 934 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-LabG68U25VUHuC-44qm:-Laq1mqmDYoTHla6EaFi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ec51811db7da89293dd4646ed26ba2f427b9ca/pkg/sql/logictest/testdata/logic_test/upsert#L934)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/opt/cat/column.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-LabGCrHBfvO0AmacM3f:-Laq2bVj1Efec-3qIucN:b-nlxv6g) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ec51811db7da89293dd4646ed26ba2f427b9ca/pkg/sql/opt/cat/column.go#L50)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

byte array is number of bytes IIRC
</blockquote></details>

I checked; it's definitely number of bits. For example: https://www.postgresql.org/docs/8.2/datatype-bit.html
___
*[pkg/sql/opt/optbuilder/insert.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-LaplbKU5CrvGSch56D2:-Laq2nUpAQI30_d8ca05:b-tc5sxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efa9871e919715b41656ed94193279559122a01/pkg/sql/opt/optbuilder/insert.go#L289)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

why did you remove this?
</blockquote></details>

It's now done inside of `addUpdateCols`.
___
*[pkg/sql/opt/optbuilder/insert.go, line 231 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-LapkkmJ6Cg-b7N_9eW4:-Laq2l9445mKk9sEFcCo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ec51811db7da89293dd4646ed26ba2f427b9ca/pkg/sql/opt/optbuilder/insert.go#L231)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

truncate -> round
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/insert.go, line 595 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-LaplKxR6jULuTQ37G0e:-Laq2sVP6MQiLyLneE1S:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ec51811db7da89293dd4646ed26ba2f427b9ca/pkg/sql/opt/optbuilder/insert.go#L595)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

truncate -> round
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-LafZArD2IrOunk_voRg:-Laq4v0ZDOZvBvJiC4u9:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efa9871e919715b41656ed94193279559122a01/pkg/sql/opt/optbuilder/mutation_builder.go#L77)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] consider making a type for this instead of `int` (we wouldn't need to include "ScopeOrd" in the name of every variable)
</blockquote></details>

Good idea. Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 494 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-Lapdn5NC69yvQUkwC0n:-Laq5TXI01qb2ddVX9SC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efa9871e919715b41656ed94193279559122a01/pkg/sql/opt/optbuilder/mutation_builder.go#L494)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

should this be an AssertionError?
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 503 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-LapdbqkA7L7Wj2l-Iau:-Laq5YvB13Fhy-Wbcz8z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efa9871e919715b41656ed94193279559122a01/pkg/sql/opt/optbuilder/mutation_builder.go#L503)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] ordinal of the scope column
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/update.go, line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-LapfjrqAV7I-BRaJGzY:-Laq5dZl9a_AZDJyqT-C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efa9871e919715b41656ed94193279559122a01/pkg/sql/opt/optbuilder/update.go#L213)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

column scope -> scope column?
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/update.go, line 285 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-LapnyzH-6MCsh34cB6h:-Laq5gg8BwxD5NVi49gD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ec51811db7da89293dd4646ed26ba2f427b9ca/pkg/sql/opt/optbuilder/update.go#L285)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

truncate -> round
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/update.go, line 316 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-Lapo1b8EEdVrDSE76Ib:-Laq5iER8fn9c1bZzuVV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ec51811db7da89293dd4646ed26ba2f427b9ca/pkg/sql/opt/optbuilder/update.go#L316)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

truncate -> round
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/testdata/insert, line 1355 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-LapoEb77M5Qe8owqhoR:-Laq5lPC6g-Ll2C5k-Yq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ec51811db7da89293dd4646ed26ba2f427b9ca/pkg/sql/opt/optbuilder/testdata/insert#L1355)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

rounding
</blockquote></details>

Done.

**Review by rytaft — CHANGES_REQUESTED** [review]
> Reviewed 1 of 24 files at r3, 23 of 23 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36066)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andy-kimball, @justinj, @knz, and @RaduBerinde)

___
*[pkg/sql/logictest/testdata/logic_test/upsert, line 924 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-LabG5HG6i8W6E0GH5Wp:-LaqEiN935O8s-oN2hON:bnu3n5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ec51811db7da89293dd4646ed26ba2f427b9ca/pkg/sql/logictest/testdata/logic_test/upsert#L924)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

looks like you didn't push this change
___
*[pkg/sql/logictest/testdata/logic_test/upsert, line 934 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-LabG68U25VUHuC-44qm:-LaqEkIW3ykC1hADIdJB:b-85ryxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ec51811db7da89293dd4646ed26ba2f427b9ca/pkg/sql/logictest/testdata/logic_test/upsert#L934)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

or this one
___
*[pkg/sql/opt/optbuilder/update.go, line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-LapfjrqAV7I-BRaJGzY:-LaqF9hgBJr9apeN2Nil:b-jbnamb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efa9871e919715b41656ed94193279559122a01/pkg/sql/opt/optbuilder/update.go#L213)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

looks like this didn't get pushed
___
*[pkg/sql/opt/optbuilder/testdata/insert, line 1355 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-LapoEb77M5Qe8owqhoR:-LaqFHspCf0fSS9YC3z9:bf426fu) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ec51811db7da89293dd4646ed26ba2f427b9ca/pkg/sql/opt/optbuilder/testdata/insert#L1355)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

didn't get pushed (I think there are a few more of these in other test files too)

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36066#-:-LaqSu4l4B5fvW_PHBn4:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj, @knz, and @RaduBerinde)

**Pull request merged**
