### PR TITLE
sql: support for column aliasing

### PR DESCRIPTION
**Pull request by RaduBerinde**
These changes implement column aliasing (issue #3708). It should be easier to review the three commits in this PR separately - each one is a self-contained change which passes tests.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4048)

### CODE REVIEW

**Comment by petermattis** [comment]
LGTM

---

Reviewed 6 of 6 files at r1, 5 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/select.go, line 285 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4048#-K9NWr2qnImbZ_NxpVFr:-K9NWr2rzViKOD7WxXDW:-2058799764) ([raw file](https://github.com/cockroachdb/cockroach/blob/b661c964e0102dab941f440a86a4bb1edc11cf1d/sql/select.go#L285)):*
I'm not sure if it matters here, but a nil slice is not equal to a slice of 0 length. You should `s/[]ResultColum{}/[]ResultColumn(nil)/g`. A nil slice implies no allocation while a non-nil 0 length slice sometimes does.

---

*[sql/testdata/select_table_alias, line 20 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4048#-K9NXBlpyIPecU2LLhUF:-K9NXBlpyIPecU2LLhUG:-1368309438) ([raw file](https://github.com/cockroachdb/cockroach/blob/b661c964e0102dab941f440a86a4bb1edc11cf1d/sql/testdata/select_table_alias#L20)):*
nit: `s/as/AS/g` to maintain consistency with the uppercase usage of SQL keywords.

---

*[sql/testdata/select_table_alias, line 117 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4048#-K9NXUSVsdTwSnzDhQ0L:-K9NXUSW_rS6S5eRiwz5:61039115) ([raw file](https://github.com/cockroachdb/cockroach/blob/b661c964e0102dab941f440a86a4bb1edc11cf1d/sql/testdata/select_table_alias#L117)):*
Nice tests.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4048#-:-K9NXZXLEZn1W3ECRqHr:676834233)*

**Comment by RaduBerinde** [comment]
*[sql/select.go, line 285 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4048#-K9NWr2qnImbZ_NxpVFr:-K9NZ3cbRvZX9Epoq8jZ:488830705) ([raw file](https://github.com/cockroachdb/cockroach/blob/b661c964e0102dab941f440a86a4bb1edc11cf1d/sql/select.go#L285)):*
Btw it feels like there should be some nicer way to make a copy of a slice?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4048)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/select.go, line 285 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4048#-K9NWr2qnImbZ_NxpVFr:-K9N_VtwY_Cb5f-i1u0Q:-684183261) ([raw file](https://github.com/cockroachdb/cockroach/blob/b661c964e0102dab941f440a86a4bb1edc11cf1d/sql/select.go#L285)):*
Yep. This is the Go Way.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4048)*

**Comment by RaduBerinde** [comment]
TFTR! Updated.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4048#-:-K9NaMq-9_6VdiGQ1bfW:-1512379193)*

**Comment by petermattis** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4048)*

**Pull request merged**
