### PR TITLE
server: configure nodelocal storage for shared-process tenant servers

### LINKED ISSUE #77986: allow tenants to use  nodelocal external storage
Currently, tenants cannot write or read to `nodelocal` external storage. Tenants should use `nodelocal` on self hosted and dedicated clusters only.

Jira issue: CRDB-13886
Epic CRDB-14582

### LINKED ISSUE #84588: server: ensure nodelocal works for secondary tenants (gated by capability) [CRDB-14537 followup]
Shared-memory tenant servers should have access to nodelocal storage.

Jira issue: CRDB-17751

Epic CRDB-23559

### PR DESCRIPTION
**Pull request by stevendanna**
This allows shared-process tenant servers to use node local storage.

In the future, we likely want to put this behind a tenant capability.

Fixes #77986
Fixes #84588.

Release note: None

### CODE REVIEW

**Comment by stevendanna** [comment]
While the tests are passing here, there may be an issue with tracers that requires investigation.

**Review by knz — APPROVED** [review]
If my understanding is correct, "Fixes #77986" is not exactly right - the issue was _already_ fixed before now, but that was done at the expense of having the same nodelocal storage shared across all tenants running on the same node, which could be seen as undesirable (because it would allow one tenant to read/write files from another tenant).

If that understanding is correct, i suggest we update the commit message and PR description accordingly.

**Comment by stevendanna** [comment]
@knz Not exactly.  Without the dir being set, node local storage does not work at all because an empty string results in the blob storage service returning an error claiming nodelocal storage isn't available.

**Comment by knz** [comment]
oh it's the DirConfig that was set already, not the Dir itself. I didn't read the code properly. Carry on.

**Comment by knz** [comment]
(this is good to go)

**Comment by stevendanna** [comment]
While this looks right, it is subtly wrong.  Currently we pass the node dialer instead of the pod dialer to the external storage builder, so we actually end up talking to the KV nodes in cases where we don't take the local node fast path. One fix is to pass the podDialer. But, I think I think our plan of record should actually be:

1) Make the blob storage a KV node service with no tenant scoping.  `nodelocal://` is exactly that, a node-specific service.
2) The blob client will use the node dialer as is currently does.
3) Add a capability that determines whether a tenant is allowed to use the blob service.
4) Disallow the `nodelocal://0` syntax unless you happen to be on a KV node.
5) Disallow the local client fast path unless you are a KV node and the system tenant (or just remove this fast-path completely).

I'll try to put a PR up for that this evening or tomorrow morning.

**Comment by knz** [comment]
Thanks for the investigation.

**Review by knz — COMMENTED** [review]
This is excellent work. Thank you! :100: 
Let me know when you've come around to making CI for the final review.

> Reviewed 1 of 1 files at r1, 16 of 16 files at r2, 66 of 66 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98184#-:-NQzXTBb8wa0PB3mGiC3:b-wjwofh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @srosenberg, and @stevendanna)

___
*[`pkg/blobs/client.go` line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98184#-NQzWdVZ9Qg351pDNPTd:-NQzWdVZ9Qg351pDNPTe:bkiqpt) ([raw file](https://github.com/cockroachdb/cockroach/blob/328058379a4284535ff8a4d3e56645809e08c9cb/pkg/blobs/client.go#L183)):*
> ```Go
> type BlobClientFactory func(ctx context.Context, dialing roachpb.NodeID) (BlobClient, error)
> 
> // NewBlobClientFactory returns a BlobClientFactory
> ```

Please extend this comment and explain what the arguments are about (especially `allowLocalFastpath`)
___
*[`pkg/blobs/client.go` line 190 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98184#-NQzWiZd6OSSptOQax8U:-NQzWiZd6OSSptOQax8V:bwha3pz) ([raw file](https://github.com/cockroachdb/cockroach/blob/328058379a4284535ff8a4d3e56645809e08c9cb/pkg/blobs/client.go#L190)):*
> ```Go
> 	allowLocalFastpath bool,
> ) BlobClientFactory {
> 	return func(ctx context.Context, dialing roachpb.NodeID) (BlobClient, error) {
> ```

maybe rename `dialing` to `dialTarget` or `targetNode`.

**Comment by stevendanna** [comment]
@dt @dnz Unless my most recent rebase produces new failures, this
should be good to review. I plan to rebase away the last commit
pre-merge.

Some things to take note of:

The most major change is here, we disallow nodelocal://0 unless
you are on a shared KV node and only allow the local fastpath for
some callers (notably the system tenant's sql server):

https://github.com/cockroachdb/cockroach/pull/98184/files#diff-6ba199cc5fe4b3b9fa3088e98094d556c3a6e38362b896a7d935a7a7bad404d9R181

We have to put in a limited exclusion of metadata clearing for
PutBlob:

https://github.com/cockroachdb/cockroach/pull/98184/files#diff-1f149f89da6dddb20e29922c8b1bdb984f3dfe06ab63f9be65a15945dfd2b44bR137

We have to grant testserver started tenants the can_use_blob_storage capability.

https://github.com/cockroachdb/cockroach/pull/98184/files#diff-d5dd8a04a615423d383141a5c4a48b18b554bf37c9bf66f402e3f782c4555456R1073

The majority of the rest of the diff is changing uses of
nodelocal://0 to nodelocal://1. This was required because our
test tenants are separate process tenants which aren't allowed to
use nodelocal://0.

**Review by dt — CHANGES_REQUESTED** [review]
Huh, I thought we concluded we were _not_ going with the first commit here?

That is, I believe #84588 is not actually something we want?

**Comment by dt** [comment]
Reading the second commit, I'm not actually sure I understand why the first commit is here?

If I am reading it correctly, only nodes now start a blob service, not all sql servers -- which seems correct to me -- right? So there is one service per-node, not one per server now, and that one service obviously thus isn't per-tenant, so is the cfg in the first commit doing anything?

**Comment by stevendanna** [comment]
@dt Good catch, the first commit really isn't needed.  I believe we still need to set externalIODir to _something_ because the client uses an empty iodir config to indicate that storage isn't configured.

**Review by knz — CHANGES_REQUESTED** [review]
This looks good, except the unfortunate choice of word "glob" in the capability name.

The capability names are user-facing, and their names should thus be coherent with our product docs. The feature is called "nodelocal storage" in our docs etc. It's unfortunate we've chosen to call it "BlobStorage" in the source code, but that incoherence is invisible to end-users.

> Reviewed 18 of 19 files at r5, 74 of 74 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98184#-:-NRmfTxQ4xk9BqYJAU1e:b-a05n4x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @srosenberg, and @stevendanna)

___
*[`pkg/blobs/client.go` line 190 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98184#-NRmeMBPE8pIwIQ0TDLV:-NRmeMBPE8pIwIQ0TDLW:b-1i9f7s) ([raw file](https://github.com/cockroachdb/cockroach/blob/e583f40016abcc82dcab1f5e36494b5fcc265daf/pkg/blobs/client.go#L190)):*
> ```Go
> // allowLocalFastpath indicates whether the client should create a
> // local client (which doesn't go through the network). The fast path
> // skips client capabaility checking so should be used with care.
> ```

nit: capability*
___
*[`pkg/server/server_controller_new_server.go` line 344 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98184#-NRmdzPdCFdm48S6VagT:-NRmdzPdCFdm48S6VagU:b-rl44df) ([raw file](https://github.com/cockroachdb/cockroach/blob/e583f40016abcc82dcab1f5e36494b5fcc265daf/pkg/server/server_controller_new_server.go#L344)):*
> ```Go
> 	if kvServerCfg.BaseConfig.Settings.ExternalIODir != "" {
> 		// Make this configurable on a per-tenant basis, see https://github.com/cockroachdb/cockroach/issues/84588.
> 		perTenantDir := fmt.Sprintf("tenant-%d", tenantID.ToUint64())
> ```

So if I understand right we can simplify to `baseCfg.Settings.ExternalIODir = kvServerCfg.BaseConfig.Settings.ExternalIODir`?

We "just" need to ensure it doesn't get deleted when the tenant server shuts down.
___
*[`pkg/server/testserver.go` line 1075 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98184#-NRmeBRdDwolTkT2QPBV:-NRmeBRdDwolTkT2QPBW:b-xdc0px) ([raw file](https://github.com/cockroachdb/cockroach/blob/e583f40016abcc82dcab1f5e36494b5fcc265daf/pkg/server/testserver.go#L1075)):*
> ```Go
> 	if st.Version.IsActive(ctx, clusterversion.V23_1TenantCapabilities) {
> 		_, err := ie.Exec(ctx, "testserver-alter-tenant-cap", nil,
> 			"ALTER TENANT [$1] GRANT CAPABILITY can_use_blob_storage", params.TenantID.ToUint64())
> ```

Why "blob" and not "nodelocal" in the capability name?
___
*[`pkg/util/grpcutil/fast_metadata.go` line 47 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98184#-NRmeGI74FUS6McseE-p:-NRmeGI74FUS6McseE-q:b9zzpj5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e583f40016abcc82dcab1f5e36494b5fcc265daf/pkg/util/grpcutil/fast_metadata.go#L47)):*
> ```Go
> 
> // ClearIncomingContextExcept removes the gRPC incoming metadata if
> // there is any, except for metadta items identified by the given
> ```

nit: metadata*

**Review by stevendanna — COMMENTED** [review]
@dt I rebased away the first commit. Now we just copy over the config directly. It's a little meh that is still necessary. But I'd like to clean that up in a follow-up if possible to avoid more test churn.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98184#-:-NRnyFnj5jDCs_cKa-0c:b9x32nw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @knz, @rytaft, and @srosenberg)

___
*[`pkg/server/server_controller_new_server.go` line 344 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98184#-NRmdzPdCFdm48S6VagT:-NRnxuf9C7UlF4tXYVYA:b-nz9ves) ([raw file](https://github.com/cockroachdb/cockroach/blob/e583f40016abcc82dcab1f5e36494b5fcc265daf/pkg/server/server_controller_new_server.go#L344)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

So if I understand right we can simplify to `baseCfg.Settings.ExternalIODir = kvServerCfg.BaseConfig.Settings.ExternalIODir`?

We "just" need to ensure it doesn't get deleted when the tenant server shuts down.
</blockquote></details>

Done.

Are you aware of code that would delete the ExternalIODir? On tenant server shut down?
___
*[`pkg/server/testserver.go` line 1075 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98184#-NRmeBRdDwolTkT2QPBV:-NRny5j29D-_E7IXO2o_:bebrd5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/e583f40016abcc82dcab1f5e36494b5fcc265daf/pkg/server/testserver.go#L1075)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Why "blob" and not "nodelocal" in the capability name?
</blockquote></details>

I've changed this. I think `blob` makes sense internally to the code, but since this is user-facing it should represent something the user knows about.

**Review by knz — APPROVED** [review]
Nice :100: 

> Reviewed 19 of 19 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98184#-:-NRrDv7b5N2xoQzPlxP_:b-ra3bk5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[`pkg/server/server_controller_new_server.go` line 344 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98184#-NRmdzPdCFdm48S6VagT:-NRrDoZN650xYP0DuMzZ:b-81sgk9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e583f40016abcc82dcab1f5e36494b5fcc265daf/pkg/server/server_controller_new_server.go#L344)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Done.

Are you aware of code that would delete the ExternalIODir? On tenant server shut down?
</blockquote></details>

I didn't find anything. So I think we're good.

**Comment by adityamaru** [comment]
bors r=dt,knz

borsing on behalf of Steven so that he doesn't have to fight another round of tests changing under this diff.

**Review by dt — APPROVED** [review]

**Comment by adityamaru** [comment]
bors r=dt,knz

**Comment by stevendanna** [comment]
bors r+ p=99

Setting a high priority so other PRs that need to rebase on top of this don't need to wait too long.

**Comment by rafiss** [comment]
bors p=99

i think that's how you can change the priority of something that's in the queue already

**Comment by stevendanna** [comment]
Waiting on https://github.com/cockroachdb/cockroach/pull/100272 to be able to backport it cleanly.

**Pull request merged**
