### PR TITLE
crdb_internal: cleanup active_range_feeds

### PR DESCRIPTION
**Pull request by dt**
This fixes the types of a few string columns that were holding timestamps, renames the misleading and awkward "startTS" and adds a column with the computed age of the resolved time as this table is often used for identifying lagging rangefeeds.

Not included here but perhaps should be: renaming the table to active_rangefeeds to be consistent with other references to the rangefeed system.

Release note: none.
Epic: none.

### CODE REVIEW

**Review by stevendanna — APPROVED** [review]
:lgtm: From https://www.cockroachlabs.com/docs/v23.2/crdb-internal#tables this is one of the tables we are allowed to change without notice.

**Comment by dt** [comment]
> this is one of the tables we are allowed to change without notice
It better be: it has "internal" right in the name.

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
