### PR TITLE
kvserver: don't cancel lease requests when callers cancel

### LINKED ISSUE #98453: kvserver: decouple lease requests from client context
Currently, lease requests (acquisitions and extensions) will be cancelled once all waiters go away:

https://github.com/cockroachdb/cockroach/blob/84a19f6e8f0c33b637deaa047c524ea6ab58f9a1/pkg/kv/kvserver/replica_range_lease.go#L105-L121

This is unfortunate in itself, because it might cause ranges to remain without leases indefinitely if lease acquisition takes a long time (e.g. because the previous leaseholder is unresponsive) and the client has a timeout that fires before the lease acquisition completes.

However, it is particularly problematic for expiration based leases, where we attempt to extend the lease asynchronously when a request comes in during the last half of the lease interval. This lease extension uses the client's context, but the client request is likely to complete before the lease extension does, which will cancel the lease extension. We already have a TODO saying as much:

https://github.com/cockroachdb/cockroach/blob/84a19f6e8f0c33b637deaa047c524ea6ab58f9a1/pkg/kv/kvserver/replica_range_lease.go#L1461-L1467

This problem is further exacerbated by the fact that concurrent requests won't join that pending lease request (which might otherwise have tided it over):

https://github.com/cockroachdb/cockroach/blob/84a19f6e8f0c33b637deaa047c524ea6ab58f9a1/pkg/kv/kvserver/replica_range_lease.go#L1434-L1436

Jira issue: CRDB-25277

Epic CRDB-25206

### PR DESCRIPTION
**Pull request by erikgrinaker**
Previously, asynchronous lease requests would be cancelled when all callers waiting for the request were cancelled. This could cause lease acquisitions to persistently fail in the face of IO delays if all callers timed out.

Furthermore, requests to ranges with expiration-based leases would trigger an asynchronous lease extension via
`maybeExtendLeaseAsyncLocked()` in the latter half of the lease interval, but because the originating request was likely to complete soon this could end up cancelling the lease request before it completed.

Resolves #98453.

Epic: none
Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
The change here looks good.

How does it interact with https://github.com/cockroachdb/cockroach/commit/ab74b974bd42bea1d50bf7c1ec8804180224f825 and https://github.com/cockroachdb/cockroach/commit/067e7402e0801f4b3d9250f124366508760a8f9a? In cases where the client is waiting synchronously for a lease request (`redirectOnOrAcquireLeaseForRequest`), will it now stop waiting after 4 seconds without canceling the underlying lease request, allowing the lease request to proceed indefinitely? We concluded in the discussion in https://github.com/cockroachdb/cockroach/pull/84865 that this wasn't an issue for lease requests that saw a steady influx of callers because there was no reason that retrying a lease request would lead to any more success than letting the existing one continue to run, so I think we're probably fine with this. I guess the added concern here is that it risks leaking stuck lease request goroutines on ranges that are no longer seeing active traffic.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98460#-:-NQROAAe8aKWwo-kZFHI:b-x3sg47)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist)

**Review by erikgrinaker — COMMENTED** [review]
Correct. I'm not so much worried about leaking the goroutine as I am about a lease request somehow getting permanently wedged and preventing further lease requests. But as you pointed out, there was already a risk of this happening as long as the range saw a steady flow of requests.

I'm mildly inclined to reinstate the inner lease acquisition timeout that was removed in 067e740, which would address both of these concerns (wedged requests and leaked goroutines).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98460#-:-NQRV49PATeIAHI4O-wg:bzb4hyz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist)

**Comment by erikgrinaker** [comment]
Going to go ahead and merge, we can reconsider the inner timeout independently. TFTR!

bors r+

**Pull request merged**
