### PR TITLE
storage: remove two sources of stats inconsistencies

### PR DESCRIPTION
**Pull request by tbg**
One in a test, one in unsafe-remove-dead-replicas. I noticed them while trying
out the unit tests with #41444.

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41492)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/storage/client_raft_test.go, line 1518 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41492#-LqptAqw0BCaopFK7Ae0:-LqptAqw0BCaopFK7Ae1:bqxp21b) ([raw file](https://github.com/cockroachdb/cockroach/blob/3de4d8ae363a7fa39d6ef74bb672a188b1d72ca9/pkg/storage/client_raft_test.go#L1518)):*
> ```Go
> // TestStoreRangeUpReplicate verifies that the replication queue will notice
> // under-replicated ranges and replicate them. Also tests that snapshots which
> // contain sideloaded proposals don't panic the receiving end.
> ```

I don't fully understand/remember this test, but I don't think the second sentence is true with this removal. I'm OK with removing it though instead of trying to fix it up and make the stats correct.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41492)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell)

___
*[pkg/storage/client_raft_test.go, line 1518 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41492#-LqptAqw0BCaopFK7Ae0:-LrIrzDXEvKp0wNhxLjJ:b-yx70ce) ([raw file](https://github.com/cockroachdb/cockroach/blob/3de4d8ae363a7fa39d6ef74bb672a188b1d72ca9/pkg/storage/client_raft_test.go#L1518)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I don't fully understand/remember this test, but I don't think the second sentence is true with this removal. I'm OK with removing it though instead of trying to fix it up and make the stats correct. 
</blockquote></details>

This was an issue around the raft log that was once part of the snapshots, and a bug that occurred when that raft log contained inlined sideloaded proposals. We don't send the raft log any more, so this is all moot. Removed the sentence.

**Review by tbg — COMMENTED** [review]
TFTR!

bors r=bdarnell

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41492#-:-LrIsBC3BtBFX5T9d70k:b82ppiz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell)

**Comment by tbg** [comment]
flaked on https://github.com/cockroachdb/cockroach/pull/41631

bors r=bdarnell

**Pull request merged**
