### PR TITLE
release-22.1: opt: backport optimizer settings for randomized testing

### PR DESCRIPTION
**Pull request by DrewKimball**
Backport:
  * 1/1 commits from "roachtest: add costfuzz test" (#79973)
  * 1/1 commits from "opt: fix performance regression due to getEnv in Optimizer.Init" (#81705)
  * 2/4 commits from "roachtest: add unoptimized-query-oracle test to validate query results" (#83095)

It is common for a bug found by the randomized tests to require setting one or more of `testing_optimizer_cost_perturbation`, `testing_optimizer_disable_rule_probability`, and `testing_optimizer_random_seed` for a reproduction. This patch backports these settings to 22.1 to make reproducing bugs and back-porting fixes easier. Only the portions of the backported commits relevant to these settings are included.

Please see individual PRs for details.

/cc @cockroachdb/release

Release justification: testing-only change to make bug reproductions and back-ports easier

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: Awesome! Thanks for doing this.

> Only the portions of the backported commits relevant to these settings are included.

I think you should also update the commit messages to make that clear, since they reference tests that don't exist.

> Reviewed 9 of 9 files at r1, 2 of 2 files at r2, 9 of 9 files at r3, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91715#-:-NGYpyH1Bbb8zJjU_F2d:b-ft3egu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

**Review by DrewKimball — COMMENTED** [review]
I added
```
[note]: This is a backport that includes only the portion of the original
commit that related to the optimizer settings for randomized testing.
```
to each commit message. Does that sound good to you?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91715#-:-NGYrKAfBYpG_I-Vab3f:bulkypg)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

**Review by rytaft — APPROVED** [review]
:lgtm: Thanks!

> Reviewed 1 of 2 files at r6, 10 of 10 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91715#-:-NGYriWN0J8_Mhpt37fy:b-g2a5fb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

**Comment by DrewKimball** [comment]
TFTR!

**Pull request merged**
