### PR TITLE
storage: move functionality from debug/print.go to storage for wider use

### PR DESCRIPTION
**Pull request by spencerkimball**
This allows replica_consistency_diff to print out readable MVCC keys and
values.

Release note: None

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
Basically LGTM, just want to take a look at the changed diff output to make sure nothing unexpected is going on. Also the linters are complaining about something.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37568#-:-Lf553wRAkYq-ngouxQJ:b-kxscj3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @spencerkimball)

___
*[pkg/storage/replica_consistency_diff.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37568#-Lf54bt10Frtg-XGBbPJ:-Lf54bt10Frtg-XGBbPK:bstzs3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b115b5218b558458c0b4f445e0129ec0e100ed3/pkg/storage/replica_consistency_diff.go#L70)):*
> ```Go
> 			prefix, ts.WallTime/1E9, ts.WallTime%1E9, ts.Logical, d.Key,
> 			prefix, prettyTime,
> 			prefix, SprintKeyValue(engine.MVCCKeyValue{Key: mvccKey, Value: d.Value}, false /* printKey */),
> ```

Doesn't this require a change to the tests?

**Review by spencerkimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37568)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/storage/replica_consistency_diff.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37568#-Lf54bt10Frtg-XGBbPJ:-Lf5ztXk7SUye8OMo6Or:bcr1gra) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b115b5218b558458c0b4f445e0129ec0e100ed3/pkg/storage/replica_consistency_diff.go#L70)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Doesn't this require a change to the tests?
</blockquote></details>

The existing test is checking a value which isn't further decoded by the addition of this change.

**Review by tbg — APPROVED** [review]
Thanks!

**Pull request merged**
