### PR TITLE
geo/geographiclib: start a GeographicLib library

### PR DESCRIPTION
**Pull request by otan**
This PR adds the GeographicLib code to our repo, handling spheroid
mathematics.

We copy the geodesic.c and geodesic.h files over with the license. The
linter has been edited to exclude checking for copyright headers here.
In future, when we add the c-deps for PROJ, we can remove them - but
that one is a bit more of an effort so punting on it for now.

Added a inverse functionality to show it off (to be used with
ST_Distance).

Release note: None

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
why is the approach here and the one in geos_unix.cc different -- in the latter we did not copy the header file and instead added manual typedefs for the functions we would use? Are we statically linking this since the license is less constrained?

And can we use C++ for our code, i.e., make it `geographiclib.cc`?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47288#-:-M4VEZdAA6pic6EI3vSS:b-rl68o2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @petermattis)

___
*[pkg/geo/geographiclib/geographiclib.c, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47288#-M4VGDPI24P3irwvmwfZ:-M4VGDPI24P3irwvmwf_:b-oyc35l) ([raw file](https://github.com/cockroachdb/cockroach/blob/f609803cb3ed016e49cec0c7aff83e62cb4a9cde/pkg/geo/geographiclib/geographiclib.c#L17)):*
> ```C
>   struct geod_geodesic spheroid;
>   geod_init(&spheroid, radius, flattening);
>   geod_inverse(&spheroid, aLat, aLng, bLat, bLng, s12, az1, az2);
> ```

is there no error propagation in the GeographicLib interfaces?

**Comment by otan** [comment]
C++: done

This one is licensed differently such that we can copy the code in as long as we have the license. Didn't do c-deps because it would require modifying their cmakelists in an annoying way. GEOS needs to be dlopen/dlsym'd so it behaves differently.

**Comment by otan** [comment]
___
*[pkg/geo/geographiclib/geographiclib.c, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47288#-M4VGDPI24P3irwvmwfZ:-M4VPefH8_MQmCcJZR4g:b-ws1ofr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f609803cb3ed016e49cec0c7aff83e62cb4a9cde/pkg/geo/geographiclib/geographiclib.c#L17)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is there no error propagation in the GeographicLib interfaces?
</blockquote></details>

Not that I can see.

**Comment by otan** [comment]
ooft, found a way of doing this differently!

**Comment by otan** [comment]
adding proj is quite difficult because it requires adding sqlite3. i'm going to back this out and revert to having inline `C`.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 7 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47288#-:-M4_xlUYDMQgOBOpTVJD:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @petermattis and @sumeerbhola)

**Comment by otan** [comment]
tftr!

bors r=sumeerbhola

**Pull request merged**
