### PR TITLE
sql: reimplement EXPLAIN (DISTSQL)

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: reimplement EXPLAIN (DISTSQL)

Reimplement EXPLAIN (DISTSQL) by leveraging the explainPlan code. We
emit everything that a regular EXPLAIN does, plus the diagram.

Release note (sql change): EXPLAIN (DISTSQL) has a new output schema
and format.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Ah, looks like there is a server API endpoint that tries to get the `json` using `EXPLAIN`. I will add a `(DISTSQL, JSON)` variant (and we won't document the `JSON` option).

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 14 of 14 files at r1, 28 of 28 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57954#-:-MOcZOtu9wHlOIQdRiRh:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @RaduBerinde, and @rytaft)

___
*[pkg/sql/explain_plan.go, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57954#-MOcUnVREvmevWth3TMF:-MOcUnVREvmevWth3TMG:bmu08yz) ([raw file](https://github.com/cockroachdb/cockroach/blob/118a6b389c1352adeab528a5055a03cb9c8cb7b6/pkg/sql/explain_plan.go#L53)):*
> ```Go
> 	plan := e.plan.WrappedPlan.(*planComponents)
> 
> 	// Determine the "distributed" and "vectorized" values, which we will emit as
> ```

nit: `s/distributed/distribution/`.
___
*[pkg/sql/explain_plan.go, line 124 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57954#-MOcZAHc2pSN8S8EIhLI:-MOcZAHc2pSN8S8EIhLJ:bgxdl6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/20195d72c714c89ca8ea9320e7074a3c931f910a/pkg/sql/explain_plan.go#L124)):*
> ```Go
> 	var rows []string
> 	if e.options.Flags[tree.ExplainFlagJSON] {
> 		// For the JSON flag, we only want to emit the diagram JSON
> ```

nit: missing period.
___
*[pkg/sql/opt/exec/execbuilder/testdata/distsql_misc, line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57954#-MOcYjepEm_AEQ4ib9o3:-MOcYjepEm_AEQ4ib9o4:b-wv20yg) ([raw file](https://github.com/cockroachdb/cockroach/blob/04e8935699b0645ad5c58160e8925e8a3148e24b/pkg/sql/opt/exec/execbuilder/testdata/distsql_misc#L24)):*
> ```
> #           (rightside.k IS NULL)
> # ]
> # ----
> ```

nit: this line will be needed
___
*[pkg/sql/rowexec/processors_test.go, line 789 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57954#-MOcW77j4Cgeldqj5fdg:-MOcW77j4Cgeldqj5fdh:b-88xlfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b697b01aa9cbd9cbb77fd6ec24dff900c6d031d9/pkg/sql/rowexec/processors_test.go#L789)):*
> ```Go
> 					func() {
> 						// Check distsql plan.
> 						rows, err := defaultConn.Query(fmt.Sprintf("SELECT info FROM [EXPLAIN (DISTSQL) %s] WHERE info LIKE 'Diagram:%%'", testCase.query))
> ```

nit: do we need double `%` symbol in LIKE clause?

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57954#-:-MOck9j4A5nJxBxD2Pa0:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @rytaft, and @yuzefovich)

___
*[pkg/sql/rowexec/processors_test.go, line 789 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57954#-MOcW77j4Cgeldqj5fdg:-MOcjz2X0844_tiVFnIM:b-3x75a2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b697b01aa9cbd9cbb77fd6ec24dff900c6d031d9/pkg/sql/rowexec/processors_test.go#L789)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: do we need double `%` symbol in LIKE clause?
</blockquote></details>

It's because it's inside a Printf format

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 14 of 14 files at r1, 28 of 28 files at r2, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57954#-:-MOf7LwJ9PWadD_3YRl8:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft and @yuzefovich)

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 13 of 14 files at r1, 25 of 28 files at r2, 6 of 7 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57954#-:-MOftMAt18eovD7_Wwph:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

**Pull request merged**
