### PR TITLE
roachtest: test CDC during rolling restarts

### PR DESCRIPTION
**Pull request by dt**
see commits

### CODE REVIEW

**Review by wenyihu6 — APPROVED** [review]

**Review by rharding6373 — APPROVED** [review]
This is great, thanks for making this test! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123404#-:-NwqCXZW2RsXKrjq6tQq:b7qsqgg)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @dt, and @herkolategan)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1015 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/123404#-NwqBMI4DBYWl9fzdcAn:-NwqBMI4DBYWl9fzdcAo:b-2s67ai) ([raw file](https://github.com/cockroachdb/cockroach/blob/69cf8678fb9e6ab4ca49edd19593796e4ac13bbd/pkg/cmd/roachtest/tests/cdc.go#L1015)):*
> ```Go
> 		defer func() {
> 			_, err := sink.Get(sinkURL + "/exit")
> 			t.L().Printf("%v", err)
> ```

nit: Could you add some context to the log message, e.g. "exit webhook sink status: %v"
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1066 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/123404#-NwqAKGE9wjbs_TzLEyB:-NwqAKGE9wjbs_TzLEyC:b-huf3gy) ([raw file](https://github.com/cockroachdb/cockroach/blob/69cf8678fb9e6ab4ca49edd19593796e4ac13bbd/pkg/cmd/roachtest/tests/cdc.go#L1066)):*
> ```Go
> 
> 	<-wait
> 	// TODO(dt) #116314.
> ```

nit: TODO(#116314)
___
*[`pkg/workload/debug/webhook_server.go` line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123404#-Nwq5OH76uUjo7zeeRLm:-Nwq5OH76uUjo7zeeRLn:b-5q3l7y) ([raw file](https://github.com/cockroachdb/cockroach/blob/308f118987389faaf2048f1a4915f43b0fd9934f/pkg/workload/debug/webhook_server.go#L74)):*
> ```Go
> 			after = before
> 			for _, i := range req.Payload {
> 				if _, ok := seen[i.After.ID]; !ok {
> ```

Not for this PR, but leaving as an idea for the future, this could also decode resolved timestamps and event timestamps. Then the server could also check ordering guarantees.

**Review by wenyihu6 — COMMENTED** [review]
I addressed the feedback since I'm on this branch anyways. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123404#-:-NwqF2aL8v1Zd_1rArLx:bn0bubj)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DarrylWong and @herkolategan)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1015 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/123404#-NwqBMI4DBYWl9fzdcAn:-NwqEuFI2La820c5lO8b:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/69cf8678fb9e6ab4ca49edd19593796e4ac13bbd/pkg/cmd/roachtest/tests/cdc.go#L1015)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

nit: Could you add some context to the log message, e.g. "exit webhook sink status: %v"
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1066 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/123404#-NwqAKGE9wjbs_TzLEyB:-NwqErei0OPCWkJC3mbb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/69cf8678fb9e6ab4ca49edd19593796e4ac13bbd/pkg/cmd/roachtest/tests/cdc.go#L1066)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

nit: TODO(#116314)
</blockquote></details>

Done.
___
*[`pkg/workload/debug/webhook_server.go` line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123404#-Nwq5OH76uUjo7zeeRLm:-NwqEYxh4hLrybnkmNuS:bwbowa) ([raw file](https://github.com/cockroachdb/cockroach/blob/308f118987389faaf2048f1a4915f43b0fd9934f/pkg/workload/debug/webhook_server.go#L74)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Not for this PR, but leaving as an idea for the future, this could also decode resolved timestamps and event timestamps. Then the server could also check ordering guarantees.
</blockquote></details>

I added a todo for cdc here.

**Comment by wenyihu6** [comment]
I swear I've removed your remote and won't mess around with your repo : )

**Review by rharding6373 — APPROVED** [review]
:lgtm: Thanks Wenyi! Might want to squash the first 2 commits before bors-ing, though 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123404#-:-NwqJGoa0L69URFB3FBR:b-ag7n3a)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong and @herkolategan)

**Review by wenyihu6 — COMMENTED** [review]
Done. I swear that I've removed your remote again after doing this. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123404#-:-NwqKu3n4AGpyyJqcZZR:b-k3nqse)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DarrylWong and @herkolategan)

**Comment by wenyihu6** [comment]
Thanks again for doing this, David! And thanks for the review, Rachael!

bors r=rharding6373

**Pull request merged**
