### PR TITLE
server: improve logging for reset quorum

### PR DESCRIPTION
**Pull request by TheSamHuang**
Adds additional logging throughout reset quorum command and RPC.

Release note: None.

### CODE REVIEW

**Review by irfansharif — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58056)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @TheSamHuang)

___
*[pkg/server/node.go, line 1028 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58056#-MOq3FRH7IPeVmz4i0a1:-MOq3FRH7IPeVmz4i0a2:b-fdeyfg) ([raw file](https://github.com/cockroachdb/cockroach/blob/977f19b8918c475ee2ca77fa49392ea362d6896d/pkg/server/node.go#L1028)):*
> ```Go
> 		txnTries += 1
> 		if txnTries > 1 {
> 			log.Infof(ctx, "txn to get range descriptor failed, retrying for attempt number %d", txnTries)
> ```

[nit] Let's skip the retry count and instead report only the fact that there are retries happening, `"failed to retrieve range descriptor for %s, retrying.."`
___
*[pkg/server/node.go, line 1052 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58056#-MOq0Hvi9hZGrOmtwFKy:-MOq0Hvi9hZGrOmtwFKz:b84nvtx) ([raw file](https://github.com/cockroachdb/cockroach/blob/977f19b8918c475ee2ca77fa49392ea362d6896d/pkg/server/node.go#L1052)):*
> ```Go
> 		return nil, err
> 	}
> 	log.Infof(ctx, "successfully read range descriptor for r%d from meta2", req.RangeID)
> ```

Skip "from meta2" (where else would it be?). Perhaps it's instructive to actually print the descriptor:
```
log.Infof(ctx, "retrieved original range descriptor %s", desc)
```
___
*[pkg/server/node.go, line 1095 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58056#-MOq2NSMBA2sHO94N4WS:-MOq2NSN6iJs94OYe7rQ:b-3oau7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/977f19b8918c475ee2ca77fa49392ea362d6896d/pkg/server/node.go#L1095)):*
> ```Go
> 	// eschewing updateRangeAddressing since the copy of the
> 	// descriptor that resides on the range itself has lost quorum.
> 	log.Infof(ctx, "meta2 entry for r%d is being edited", desc.RangeID)
> ```

We can skip this line, we've already printed everything right above ("initiating recovery ...").
___
*[pkg/server/node.go, line 1100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58056#-MOq2ThG7EzhyJ0b8wa9:-MOq2ThG7EzhyJ0b8waA:b4e5pvg) ([raw file](https://github.com/cockroachdb/cockroach/blob/977f19b8918c475ee2ca77fa49392ea362d6896d/pkg/server/node.go#L1100)):*
> ```Go
> 		return nil, err
> 	}
> 	log.Infof(ctx, "put meta2 entry for r%d succeeded", desc.RangeID)
> ```

`"updated meta2 entry for r%d", desc.RangeID`
___
*[pkg/server/node.go, line 1121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58056#-MOq3-6i5vj4bv3VDp-3:-MOq3-6i5vj4bv3VDp-4:b-iboziv) ([raw file](https://github.com/cockroachdb/cockroach/blob/977f19b8918c475ee2ca77fa49392ea362d6896d/pkg/server/node.go#L1121)):*
> ```Go
> 		return nil, err
> 	}
> ```

Let's maybe another one here to the effect of `"sent empty snapshot to %s", toReplicaDescriptor`.

**Review by TheSamHuang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58056)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif)

___
*[pkg/server/node.go, line 1028 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58056#-MOq3FRH7IPeVmz4i0a1:-MOt18sP6_RXBfe2YbbV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/977f19b8918c475ee2ca77fa49392ea362d6896d/pkg/server/node.go#L1028)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

[nit] Let's skip the retry count and instead report only the fact that there are retries happening, `"failed to retrieve range descriptor for %s, retrying.."`
</blockquote></details>

Done.
___
*[pkg/server/node.go, line 1052 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58056#-MOq0Hvi9hZGrOmtwFKy:-MOt1E-S-TIvB5Mg8Fmf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/977f19b8918c475ee2ca77fa49392ea362d6896d/pkg/server/node.go#L1052)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Skip "from meta2" (where else would it be?). Perhaps it's instructive to actually print the descriptor:
```
log.Infof(ctx, "retrieved original range descriptor %s", desc)
```
</blockquote></details>

Done.
___
*[pkg/server/node.go, line 1095 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58056#-MOq2NSMBA2sHO94N4WS:-MOt1Io4Cz2-BoiID-06:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/977f19b8918c475ee2ca77fa49392ea362d6896d/pkg/server/node.go#L1095)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

We can skip this line, we've already printed everything right above ("initiating recovery ...").
</blockquote></details>

Done.
___
*[pkg/server/node.go, line 1100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58056#-MOq2ThG7EzhyJ0b8wa9:-MOt1LtKEBBEpML_2Otu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/977f19b8918c475ee2ca77fa49392ea362d6896d/pkg/server/node.go#L1100)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

`"updated meta2 entry for r%d", desc.RangeID`
</blockquote></details>

Done.
___
*[pkg/server/node.go, line 1121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58056#-MOq3-6i5vj4bv3VDp-3:-MOt1UfP44IeeKQkWPuU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/977f19b8918c475ee2ca77fa49392ea362d6896d/pkg/server/node.go#L1121)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Let's maybe another one here to the effect of `"sent empty snapshot to %s", toReplicaDescriptor`.
</blockquote></details>

Done.

**Review by irfansharif — COMMENTED** [review]
:lgtm: thanks for the quick turnaround Sam!

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58056#-:-MOt4fiHBL8JpC5SAj2r:b1ywdrr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @TheSamHuang)

___
*[pkg/server/node.go, line 1028 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58056#-MOq3FRH7IPeVmz4i0a1:-MOt4WrA0uBPbGEGpImO:b-pwfb8u) ([raw file](https://github.com/cockroachdb/cockroach/blob/977f19b8918c475ee2ca77fa49392ea362d6896d/pkg/server/node.go#L1028)):*
<details><summary><i>Previously, TheSamHuang (Sam Huang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

[nit] We customarily add ellipses for this sort of thing, "..."

**Comment by TheSamHuang** [comment]
Thanks for the review! Added in the ellipses!

**Comment by TheSamHuang** [comment]
bors r=irfansharif

**Pull request merged**
