### PR TITLE
sqlproxy: add a timeout when dialing tenant pods

### PR DESCRIPTION
**Pull request by jeffswenson**
Dialing dead or non existent pods on GKS can black hole
the network connection. This leaves the connection process
stuck until the OS TCP timeout of 2 minutes.

The SQL proxy and the tenant pod are colocated. 5 seconds should
be more than enough to establish the TCP connection. Timeing out
will cause the retry loop in proxy_handler.go to refetch the tenant
IP address and retry the connection.

Release note: None

### CODE REVIEW

**Comment by JeffSwenson** [comment]
I verified this fix using the same test prober that uncovered it. I spent a fair amount of time trying to write a good regression test for this that could be checked in to the repository. The only solution I could find is to inject a fake DNS resolver that hangs indefinitely. Adding the test hooks to make that possible introduced more complexity to the production code than I think the change warrants. It was also an unsatisfying test in the sense that it covers a relatively small portion of possible regressions related to black holing. It effectively just verified that the Dial has a timeout set.

**Review by chrisseto — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68418#-:-MgGZBtD64_Im9L9VSmX:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @darinpp and @JeffSwenson)

___
*[pkg/ccl/sqlproxyccl/backend_dialer.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68418#-MgGZ6bH-7_73XRSxqnJ:-MgGZ6bH-7_73XRSxqnK:bjus8yo) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5339eff1859780f13be14f362fc6341357183e8/pkg/ccl/sqlproxyccl/backend_dialer.go#L23)):*
> ```Go
> // BackendDial is an example backend dialer that does a TCP/IP connection
> // to a backend, SSL and forwards the start message. It is defined as a variable
> // so it can be redirected for testing.
> ```

nit: Update the commit to include a note about using a < default connection timeout?
___
*[pkg/ccl/sqlproxyccl/backend_dialer.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68418#-MgGYuf-9DMMU8ALqTRb:-MgGYuf-9DMMU8ALqTRc:b-y5u7xj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5339eff1859780f13be14f362fc6341357183e8/pkg/ccl/sqlproxyccl/backend_dialer.go#L28)):*
> ```Go
> ) (net.Conn, error) {
> 	// Use a short dial timeout to mitigate network black holes.
> 	conn, err := net.DialTimeout("tcp", outgoingAddress, time.Second*5)
> ```

How difficult would it be to plumb this down from a CLI flag? Seems like something we might want to be configurable.

**Review by andy-kimball — APPROVED** [review]
:lgtm:  However, one consideration: when we add support for multiple regions, it will become possible for a proxy to connect to a SQL pod in a remote region. Ideally, we'd have an exponential backoff for the timeout that goes up higher than 5 seconds. We don't need that now, but maybe add a TODO.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68418#-:-MgGZFL-72a4I3iKsU4M:b-97atwc)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @darinpp and @JeffSwenson)

**Review by jeffswenson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68418)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @chrisseto and @darinpp)

___
*[pkg/ccl/sqlproxyccl/backend_dialer.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68418#-MgGYuf-9DMMU8ALqTRb:-MgGkAvi2el4mLVMZL9l:b-yl13aq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5339eff1859780f13be14f362fc6341357183e8/pkg/ccl/sqlproxyccl/backend_dialer.go#L28)):*
<details><summary><i>Previously, chrisseto (Chris Seto) wrote…</i></summary><blockquote>

How difficult would it be to plumb this down from a CLI flag? Seems like something we might want to be configurable.
</blockquote></details>

It's not trivial to add a new cockroach option and plumb it through to the proxy handler. If it turns out 5 seconds doesn't work reliably in production I think we should change the strategy. For example: instead of canceling the in progress request we could watch for new tenat pods and speculatively retry when a new pod is available.

**Pull request merged**
