### PR TITLE
cherrypick: c-deps: fix RocksDB on Windows without assertions

### PR DESCRIPTION
**Pull request by mberhault**

### CODE REVIEW

**Comment by mberhault** [comment]
I ran `./import.sh` (after fixing the tar invocation), the tarball was conflicting.

**Review by tamird — APPROVED** [review]

**Comment by mberhault** [comment]
btw, could you check whether the `tar -x` command on L52 is happy with the additional `-z` on osx? It needs it on linux.

**Comment by tamird** [comment]
Did you mean on L51? That doesn't look right to me, not all these tarballs are gzip (jemalloc is bzip2).

**Comment by mberhault** [comment]
yes, L51 on master, L52 on release-1.0. And blast! this means that import.sh doesn't work on linux right now.

**Pull request merged**
