### PR TITLE
kv/kvnemesis: add support for SkipLocked Gets, Scans, and RevScans

### PR DESCRIPTION
**Pull request by nvb**
This commit adds support to kvnemsis to run batches that contain a single Get, Scan, or ReverseScan operation using a SkipLocked wait policy. Such batches are allowed to omit keys in their response (those that are locked), but the key-values that are returned must be correct. For now, we don't assert that the missing keys were locked at the time of the read, as doing so would introduce a complex timing dependency into kvnemesis.

Even without such precise analysis, this change is sufficient to exercise a large number of interactions between SkipLocked and non-SkipLocked requests, giving us more confidence in the SkipLocked implementation. For instance, when stressing kvnemesis with this commit and with #90076 reverted, I am able to trigger the crash from #88980.

Release note: None
Epic: None

### CODE REVIEW

**Comment by tbg** [comment]
Would you be opposed to letting me merge this after https://github.com/cockroachdb/cockroach/pull/89477? That PR refactors pretty heavily so I would be slightly worried to mess something up when rebasing that-on-this.

If you think we need the nightly coverage for this now, we can go ahead with the merge and I'll sort it out later.

**Comment by nvanbenschoten** [comment]
> Would you be opposed to letting me merge this after https://github.com/cockroachdb/cockroach/pull/89477?

Sure, not a problem. I'll just give this some extra stressing time locally.

**Comment by tbg** [comment]
Heads up, kvnemesis update has merged, but despite what I promised earlier I'd prefer not to return to it for a bit 😅
Concepts haven't changed materially so rebase shouldn't be a big issue, let me know if anything's unclear.

**Comment by nvanbenschoten** [comment]
No problem. This is rebased on master now.

**Comment by arulajmani** [comment]
Thanks for the ping. Much needed, because I missed your earlier comment that this was rebased. I'll have a look this week, apologies for dropping the ball.

**Comment by nvanbenschoten** [comment]
@arulajmani since we're pushing on SKIP LOCKED again, it would be good to land this testing improvement. It's a large patch, but most of the updates are `--rewrites` to data-driven files. The actual code changes are contained and straightforward.

**Comment by arulajmani** [comment]
I'll give this a look tomorrow morning.

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> Reviewed 29 of 50 files at r1, 58 of 58 files at r2, 42 of 42 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91378#-:-Ncs48GBEfidCRqQOYtE:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by nvanbenschoten** [comment]
TFTR!

bors r+

**Pull request merged**
