### PR TITLE
storage: force new lease sequence number after restart

### PR DESCRIPTION
**Pull request by tbg**
This actually highlights some open questions that I am posting this PR
for.

Touches #10420.

Release note: None

### CODE REVIEW

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/storage/client_replica_test.go, line 998 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23204#-L6Sd1K5y6WGlE1Dap6J:-L6Sd1K5y6WGlE1Dap6K:buq2zyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/041d6845af4f9c8c67188ba2dde75b8779b237c4/pkg/storage/client_replica_test.go#L998)):*
> ```Go
> 		// likely because such a command would likely have popped out of Raft before the lease
> 		// anyway (and so all waiting commands would have observed it), but in the midst of
> 		// elections, it seems that these could theoretically reorder. Also, if the clock of
> ```

Yeah, this does seem like a potential problem. I didn't go deep enough when pulling on the minLeaseProposed thread; I think we need to do something to ensure a new lease sequence number is assigned instead of just extending the previous lease. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23204)*

**Comment by tschottdorf** [comment]
@nvanbenschoten, could you provide guidance on this?

**Comment by nvanbenschoten** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/storage/client_replica_test.go, line 994 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23204#-L6XMTOzIjUc8kz3d1W6:-L6XMTP-LMn-qMP9WGOx:bslndr3) ([raw file](https://github.com/cockroachdb/cockroach/blob/041d6845af4f9c8c67188ba2dde75b8779b237c4/pkg/storage/client_replica_test.go#L994)):*
> ```Go
> 	if preRestartLease.Sequence == postRestartLease.Sequence {
> 		// TODO(tschottdorf): figure out whether this is actually a problem. The concern here
> 		// is that while a new lease *is* requested, it is an extension lease. This means that
> ```

To clarify, this situation you're suggesting is only possible with expiration-based leases, right? For epoch-based leases, a node restart will cause the new lease to have an increased epoch, which will force the new lease to have a larger sequence number.

---

*[pkg/storage/client_replica_test.go, line 998 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23204#-L6Sd1K5y6WGlE1Dap6J:-L6XNWUJjzF3Eu09BC5n:b-i5ttpt) ([raw file](https://github.com/cockroachdb/cockroach/blob/041d6845af4f9c8c67188ba2dde75b8779b237c4/pkg/storage/client_replica_test.go#L998)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Yeah, this does seem like a potential problem. I didn't go deep enough when pulling on the minLeaseProposed thread; I think we need to do something to ensure a new lease sequence number is assigned instead of just extending the previous lease. 
</blockquote></details>

Yeah, similar to how we don't allow commands to be proposed below the `minLeaseProposedTS`, I don't think we want leases to be considered equivalent if the `minLeaseProposedTS` is past the Start timestamp of the existing lease.

One way we could ensure this is by forwarding the [`effectiveStart` timestamp](https://github.com/cockroachdb/cockroach/blob/d79f836047f4b761855168c488a9d04691b0627f/pkg/storage/batcheval/cmd_lease_request.go#L77) of a new lease by the `minLeaseProposedTS`. Leases are [not considered equivalent](https://github.com/cockroachdb/cockroach/blob/d79f836047f4b761855168c488a9d04691b0627f/pkg/roachpb/data.go#L1235) if they have different `Start` timestamps, so this would resolve the issue.

---

*[pkg/storage/client_replica_test.go, line 1000 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23204#-L6XN3cQn3IMuUJN41HB:-L6XN3cQn3IMuUJN41HC:b-v54x14) ([raw file](https://github.com/cockroachdb/cockroach/blob/041d6845af4f9c8c67188ba2dde75b8779b237c4/pkg/storage/client_replica_test.go#L1000)):*
> Also, if the clock of the node jumped backwards during a restart, we could end up accidentally shortening our lease.

This should be prevented by [expiration forwarding](https://github.com/cockroachdb/cockroach/blob/d79f836047f4b761855168c488a9d04691b0627f/pkg/storage/batcheval/cmd_lease_request.go#L84).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23204)*

**Comment by tschottdorf** [comment]
Thanks for your input, @nvanbenschoten! Incorporated that and updated the description and code, PTAL!

---

Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/storage/client_replica_test.go, line 982 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23204#-L6Y3laI1PexFjpEOeqJ:-L6Y3laI1PexFjpEOeqK:babj33c) ([raw file](https://github.com/cockroachdb/cockroach/blob/041d6845af4f9c8c67188ba2dde75b8779b237c4/pkg/storage/client_replica_test.go#L982)):*
> TestLeaseNotUsedAfterRestart

---

*[pkg/storage/client_replica_test.go, line 994 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23204#-L6XMTOzIjUc8kz3d1W6:-L6X_pSYjUOR2AppP6uS:b-bqbu2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/041d6845af4f9c8c67188ba2dde75b8779b237c4/pkg/storage/client_replica_test.go#L994)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

To clarify, this situation you're suggesting is only possible with expiration-based leases, right? For epoch-based leases, a node restart will cause the new lease to have an increased epoch, which will force the new lease to have a larger sequence number.
</blockquote></details>

Yep, we're only worried about this for expiration based leases.

---

*[pkg/storage/client_replica_test.go, line 998 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23204#-L6Sd1K5y6WGlE1Dap6J:-L6Y3mJ7XhKfhvNDOcMX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/041d6845af4f9c8c67188ba2dde75b8779b237c4/pkg/storage/client_replica_test.go#L998)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, similar to how we don't allow commands to be proposed below the `minLeaseProposedTS`, I don't think we want leases to be considered equivalent if the `minLeaseProposedTS` is past the Start timestamp of the existing lease.

One way we could ensure this is by forwarding the [`effectiveStart` timestamp](https://github.com/cockroachdb/cockroach/blob/d79f836047f4b761855168c488a9d04691b0627f/pkg/storage/batcheval/cmd_lease_request.go#L77) of a new lease by the `minLeaseProposedTS`. Leases are [not considered equivalent](https://github.com/cockroachdb/cockroach/blob/d79f836047f4b761855168c488a9d04691b0627f/pkg/roachpb/data.go#L1235) if they have different `Start` timestamps, so this would resolve the issue.
</blockquote></details>

Done.

---

*[pkg/storage/client_replica_test.go, line 1000 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23204#-L6XN3cQn3IMuUJN41HB:-L6Y3nDjPC4QgJNrOZDe:b8diu7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/041d6845af4f9c8c67188ba2dde75b8779b237c4/pkg/storage/client_replica_test.go#L1000)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> Also, if the clock of the node jumped backwards during a restart, we could end up accidentally shortening our lease.

This should be prevented by [expiration forwarding](https://github.com/cockroachdb/cockroach/blob/d79f836047f4b761855168c488a9d04691b0627f/pkg/storage/batcheval/cmd_lease_request.go#L84).

</blockquote></details>

Ack, good to know.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23204#-:-L6Y3oqt2vA_Vmz3b7fd:b-bwqlkb)*

**Comment by nvanbenschoten** [comment]
Reviewed 4 of 5 files at r2.
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/storage/batcheval/cmd_lease_request.go, line 83 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23204#-L6YIxY214c7jYJWtPCa:-L6YIxY214c7jYJWtPCb:b-kz4xl) ([raw file](https://github.com/cockroachdb/cockroach/blob/73ab04b74dda30abcf60f207e18641cec5353a1c/pkg/storage/batcheval/cmd_lease_request.go#L83)):*
> ```Go
> 	// timestamp. This makes sure that when a node restarts, its earlier in-flight
> 	// commands (which are not tracked by the command queue post restart) receive
> 	// an error under the new lease (since the sequence number will increase).
> ```

This is making a bit of a logical jump. The thing that it's missing is that the sequence number will increase if the `Start` timestamp of the new lease is not equal to the start timestamp of the old lease. If we succeed in forwarding the `effectiveStart` timestamp, we'll create this effect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23204)*

**Comment by tschottdorf** [comment]
RFAL. I hope this actually passes tests now. Since `RequestLeaseRequest` never goes to disk and because nodes that don't set the field just don't get the protection added here, I think this can go in without a migration, but I'll double check tomorrow.

---

Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/storage/batcheval/cmd_lease_request.go, line 83 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23204#-L6YIxY214c7jYJWtPCa:-L6_oN6swTEXouh0iHOy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/73ab04b74dda30abcf60f207e18641cec5353a1c/pkg/storage/batcheval/cmd_lease_request.go#L83)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is making a bit of a logical jump. The thing that it's missing is that the sequence number will increase if the `Start` timestamp of the new lease is not equal to the start timestamp of the old lease. If we succeed in forwarding the `effectiveStart` timestamp, we'll create this effect.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23204#-:-L6_oQ6gDWdd7EVGdL9i:b-fk7v9i)*

**Comment by tschottdorf** [comment]
TFTR! Had to make another small edit to de-flake tests (not setting `minLeaseProposeTS` for the first lease since that one is special with a zero start timestamp). @nvanbenschoten I'll wait for your sign-off; no rush.

**Comment by nvanbenschoten** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica.go, line 712 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/23204#-L6ds5ss00up6zGqbunI:-L6ds5ss00up6zGqbunJ:b-4bpumi) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ee477a2a57468a26fd8826e44d51519648ee48f/pkg/storage/replica.go#L712)):*
> ```Go
> 	// NB: we check the explicit lease to allow the initial lease to be extended.
> 	// The initial lease will start at the zero timestamp; if we set a minLeaseProposedTS
> 	// here,
> ```

The suspense is killing me.

---

*[pkg/storage/replica.go, line 722 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/23204#-L6dsQxHfFURQyEOHdmZ:-L6dsQxI3UanL7JhatYn:bromus5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ee477a2a57468a26fd8826e44d51519648ee48f/pkg/storage/replica.go#L722)):*
> ```Go
> 		// Instead, we make the first lease special (which is OK) and the problem
> 		// disappears.
> 		if r.mu.state.Lease.Replica.StoreID != 0 {
> ```

Does it work if we make this `if r.mu.state.Lease.Sequence > 0 {`? That reads a little better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23204)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica.go, line 712 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/23204#-L6ds5ss00up6zGqbunI:-L6e6sK9KIBAcLmcy06Z:bvu6wiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ee477a2a57468a26fd8826e44d51519648ee48f/pkg/storage/replica.go#L712)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The suspense is killing me.
</blockquote></details>

Oops. Removed.

---

*[pkg/storage/replica.go, line 722 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/23204#-L6dsQxHfFURQyEOHdmZ:-L6e6uTbY9cQzYXnQ3Yf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ee477a2a57468a26fd8826e44d51519648ee48f/pkg/storage/replica.go#L722)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does it work if we make this `if r.mu.state.Lease.Sequence > 0 {`? That reads a little better.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23204)*

**Comment by tschottdorf** [comment]
I seem to have introduced flakiness in the acceptance tests that restart nodes, going to hunt that down first.

**Comment by tschottdorf** [comment]
Just passed five consecutive builds and @jordanlewis observed a similar cluster of timeouts on his PRs earlier, so I'm confident chalking this up as fixed in #23402 and perhaps #23333.

**Pull request merged**
