### PR TITLE
sql: allow YMD, DMY for DateStyle as a session variable

### PR DESCRIPTION
**Pull request by otan**
Refs: #41773

See individual commits for details.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
glad it's coming together! nice find on the thing with constant resolution

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68093#-:-MfgBt__C2k_fTbpCr1Y:bcjb2i2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/ccl/cliccl/debug_backup.go, line 464 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68093#-Mfg8NOF4hqMC7DJSimM:-Mfg8NOF4hqMC7DJSimN:boqio5d) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca61335cba690c7bd19d021e53b331bbd41c7ac2/pkg/ccl/cliccl/debug_backup.go#L464)):*
> ```Go
> 	var err error
> 	// Attempt to parse as timestamp.
> 	if ts, _, err := pgdate.ParseTimestampWithoutTimezone(timeutil.Now(), pgdate.DateStyle{Order: pgdate.Order_MDY}, readTime); err == nil {
> ```

hm what does this change mean? `debug` for backups was parsing all dates wrong?
___
*[pkg/sql/vars.go, line 259 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68093#-Mfg6Wui30-TpjPJijGl:-Mfg6Wui30-TpjPJijGm:b-lhlr3d) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddb254b1a0a2ad024915dfff8d3f72822b08c5c6/pkg/sql/vars.go#L259)):*
> ```Go
> 	// See https://www.postgresql.org/docs/10/static/runtime-config-client.html#GUC-DATESTYLE
> 	`datestyle`: {
> 		Set: func(_ context.Context, m *sessionDataMutator, s string) error {
> ```

i just discovered that we're supposed to send a parameter status message when `datestyle` or `intervalstyle` are changed. see https://www.postgresql.org/docs/13/protocol-flow.html#PROTOCOL-ASYNC

we already implement this for the `timezone` session var by calling `BufferParamStatusUpdate` so should be doable

(when you add that, could you add a test in pgtest as well?)
___
*[pkg/sql/vars.go, line 265 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68093#-Mfg72U791WDpLbELjCB:-Mfg72U893EpIrNZ0CNw:b63eg7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddb254b1a0a2ad024915dfff8d3f72822b08c5c6/pkg/sql/vars.go#L265)):*
> ```Go
> 			}
> 			if ds.Style != pgdate.Style_ISO {
> 				return unimplemented.NewWithIssue(41773, "only ISO style is supported")
> ```

nit: we want the name of the session var to appear in the error message (here and in the previous `if` above this).

`intervalstyle` achieves this by using `newVarValueError`
___
*[pkg/sql/logictest/testdata/logic_test/datetime, line 1460 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68093#-Mfg9MucAa-XELe2iVu1:-Mfg9MucAa-XELe2iVu2:b-bc958t) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca61335cba690c7bd19d021e53b331bbd41c7ac2/pkg/sql/logictest/testdata/logic_test/datetime#L1460)):*
> ```
> 
> query T
> SELECT '6-12-26 BC'::DATE
> ```

a few comments on this test:
- do we need to be worried about compat? seems like previously, by default `SELECT '-56-12-26'::DATE` would work in CRDB but now it will not (unless datestyle is changed)?
- when i do `SELECT '6-12-26 BC'::DATE` in PG (in `ISO, MDY` mode), i get back `0026-12-06 BC`

maybe we need a release note saying the default parse mode is no longer YMD? (but perhaps this is too big of a change?)
___
*[pkg/sql/logictest/testdata/logic_test/datetime, line 1467 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68093#-Mfg9qUA0-T9FJbaAM7j:-Mfg9qUA0-T9FJbaAM7k:b-109ksk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca61335cba690c7bd19d021e53b331bbd41c7ac2/pkg/sql/logictest/testdata/logic_test/datetime#L1467)):*
> ```
> SELECT '5-12-26 BC'::DATE
> ----
> -0025-05-12 00:00:00 +0000 +0000
> ```

PG gives me `0026-05-12 BC` for this
___
*[pkg/sql/logictest/testdata/logic_test/datetime, line 1799 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68093#-MfgAHunBjYAdoSjZ8wH:-MfgAHunBjYAdoSjZ8wI:bldxye3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca61335cba690c7bd19d021e53b331bbd41c7ac2/pkg/sql/logictest/testdata/logic_test/datetime#L1799)):*
> ```
> set datestyle = 'ymd'
> 
> statement error field day value 2020 is out of range
> ```

looks like PG even gives a hint:
```
HINT:  Perhaps you need a different "datestyle" setting.
```

could we do that?
___
*[pkg/util/timetz/timetz.go, line 38 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68093#-MfgAytxBlNaTaxfmp_R:-MfgAytxBlNaTaxfmp_S:b-f0pfon) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca61335cba690c7bd19d021e53b331bbd41c7ac2/pkg/util/timetz/timetz.go#L38)):*
> ```Go
> 	// timeTZIncludesDateRegex is a regex to check whether there is a date
> 	// associated with the given string when attempting to parse it.
> 	timeTZIncludesDateRegex = regexp.MustCompile(`^\d{2,}[-/]`)
> ```

is that too open-ended? why not `^\d{2,4}[-/]`
___
*[pkg/util/timeutil/pgdate/parsing.go, line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68093#-Mfg7xkiAcD1AdqKgJmt:-Mfg7xkiAcD1AdqKgJmu:bct4eib) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cafddd68be40b6236ff04b5cc2e4021b2cae03b/pkg/util/timeutil/pgdate/parsing.go#L278)):*
> ```Go
> 
> // DefaultDateStyle returns the default datestyle for Postgres.
> func DefaultDateStyle() DateStyle {
> ```

nit: could this be a `const` instead of a function?
___
*[pkg/util/timeutil/pgdate/pgdate.go, line 265 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68093#-Mfg3Pq61vDri98cyhTj:-Mfg3Pq61vDri98cyhTk:b4rzucv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cafddd68be40b6236ff04b5cc2e4021b2cae03b/pkg/util/timeutil/pgdate/pgdate.go#L265)):*
> ```Go
> 		return s.String()
> 	}
> 	return s.String()
> ```

nit: looks like we could use a `default` case here instead? and possibly combine that case with `case Style_ISO, Style_SQL`
___
*[pkg/util/timeutil/pgdate/pgdate.proto, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68093#-Mfg3ZlrCWz-iEvC4r1v:-Mfg3Zls0I33EcZ89NEi:bbsh4j8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cafddd68be40b6236ff04b5cc2e4021b2cae03b/pkg/util/timeutil/pgdate/pgdate.proto#L18)):*
> ```protobuf
> message DateStyle {
>   Style style = 1;
>   Order order = 2;
> ```

nit: add a comment on `Order` so it's clear that it refers to day, month, year ordering. a comment on `Style` would be nice too

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68093)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/vars.go, line 259 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68093#-Mfg6Wui30-TpjPJijGl:-Mfi9h7q9sfDXh6j4L45:b-7ale3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddb254b1a0a2ad024915dfff8d3f72822b08c5c6/pkg/sql/vars.go#L259)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i just discovered that we're supposed to send a parameter status message when `datestyle` or `intervalstyle` are changed. see https://www.postgresql.org/docs/13/protocol-flow.html#PROTOCOL-ASYNC

we already implement this for the `timezone` session var by calling `BufferParamStatusUpdate` so should be doable

(when you add that, could you add a test in pgtest as well?)
</blockquote></details>

there's also `RegisterOnSessionDataChange` which might be useful for this?

https://github.com/cockroachdb/cockroach/blob/4c231cdd56b56999edf29253739ef98f027e0fc6/pkg/sql/conn_executor.go#L772

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68093)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/ccl/cliccl/debug_backup.go, line 464 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68093#-Mfg8NOF4hqMC7DJSimM:-MfjPqnp8o22-KE3hVEB:boec0ij) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca61335cba690c7bd19d021e53b331bbd41c7ac2/pkg/ccl/cliccl/debug_backup.go#L464)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm what does this change mean? `debug` for backups was parsing all dates wrong?
</blockquote></details>

see comment below. YMD is acceptable as long as the year is at least 3 digits 
___
*[pkg/sql/vars.go, line 259 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68093#-Mfg6Wui30-TpjPJijGl:-MfjNtg-5P48EiA3ZVCu:b-muf0pu) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddb254b1a0a2ad024915dfff8d3f72822b08c5c6/pkg/sql/vars.go#L259)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

there's also `RegisterOnSessionDataChange` which might be useful for this?

https://github.com/cockroachdb/cockroach/blob/4c231cdd56b56999edf29253739ef98f027e0fc6/pkg/sql/conn_executor.go#L772
</blockquote></details>

tacked on a commit.
___
*[pkg/sql/vars.go, line 265 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68093#-Mfg72U791WDpLbELjCB:-MfjTJeJ9Y4pSZx-5zhX:b-f1yzwi) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddb254b1a0a2ad024915dfff8d3f72822b08c5c6/pkg/sql/vars.go#L265)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: we want the name of the session var to appear in the error message (here and in the previous `if` above this).

`intervalstyle` achieves this by using `newVarValueError`
</blockquote></details>

i've kept this one because the unimplemented is important, but the other error i have done as suggested.
___
*[pkg/sql/logictest/testdata/logic_test/datetime, line 1460 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68093#-Mfg9MucAa-XELe2iVu1:-MfjPTk7AfXv7znGXLkc:b-1tuc6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca61335cba690c7bd19d021e53b331bbd41c7ac2/pkg/sql/logictest/testdata/logic_test/datetime#L1460)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

a few comments on this test:
- do we need to be worried about compat? seems like previously, by default `SELECT '-56-12-26'::DATE` would work in CRDB but now it will not (unless datestyle is changed)?
- when i do `SELECT '6-12-26 BC'::DATE` in PG (in `ISO, MDY` mode), i get back `0026-12-06 BC`

maybe we need a release note saying the default parse mode is no longer YMD? (but perhaps this is too big of a change?)
</blockquote></details>

i've added a release note. this can be backwards compatible if you format years < 100 with %04d.
YMD is accepted in all datestyles *if* you have a value in the first field has more than 3 digits. You can get around this with `056-12-26` 

-0025 == 26 BC. time.time just formats it differently.
___
*[pkg/sql/logictest/testdata/logic_test/datetime, line 1467 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68093#-Mfg9qUA0-T9FJbaAM7j:-MfjPGkF3seUrLJ8Tmx9:bnon8ae) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca61335cba690c7bd19d021e53b331bbd41c7ac2/pkg/sql/logictest/testdata/logic_test/datetime#L1467)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

PG gives me `0026-05-12 BC` for this
</blockquote></details>

a) this is libpq printing out the date, it's going to look different.
b) our CLI doesn't process BC correctly, that's a separate issue outside of this unfortunately. in fact, we just don't handle negative dates correctly in the string cast either.

separate, existing problem :'(
___
*[pkg/sql/logictest/testdata/logic_test/datetime, line 1799 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68093#-MfgAHunBjYAdoSjZ8wH:-MfjY7P0Bm1xGPVjW6OJ:b-tf18nq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca61335cba690c7bd19d021e53b331bbd41c7ac2/pkg/sql/logictest/testdata/logic_test/datetime#L1799)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

looks like PG even gives a hint:
```
HINT:  Perhaps you need a different "datestyle" setting.
```

could we do that?
</blockquote></details>

Done. Tacked on a commit.
___
*[pkg/util/timetz/timetz.go, line 38 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68093#-MfgAytxBlNaTaxfmp_R:-MfjOzzX9S4OXF1g6-nn:br9reel) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca61335cba690c7bd19d021e53b331bbd41c7ac2/pkg/util/timetz/timetz.go#L38)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is that too open-ended? why not `^\d{2,4}[-/]`
</blockquote></details>

nope, e.g. year 10000. actually, this should just be + for 1 year dates.
___
*[pkg/util/timeutil/pgdate/parsing.go, line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68093#-Mfg7xkiAcD1AdqKgJmt:-MfjNIOX5b1wXub5N4Bd:b-wfxer7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cafddd68be40b6236ff04b5cc2e4021b2cae03b/pkg/util/timeutil/pgdate/parsing.go#L278)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: could this be a `const` instead of a function?
</blockquote></details>

can't const a struct, don't want to make it a var so people can change it :')

**Review by rafiss — CHANGES_REQUESTED** [review]
to bikeshed the release note a bit:
```
Release note (backward-incompatible change): Previously, parsing a date
from a string would incorrectly assuming YMD format instead of the MDY
format if the date was formatted using the two digit format: "YY-MM-DD"
instead of "MM-DD-YY". This has been resolved. However, if you relied on
having two digits years as YY-MM-DD, prepend 0's at the front until it
is at least 3 digits, e.g. "15-10-15" for the year 15 should read
"015-10-15".
```

should we list this as a bugfix rather than a backward-incompatible change? or both?

my thought is that if we just say it's a backward-incompatible change, then we should be going through a whole deprecation+workaround gradual release process. but since we actually  view this as a bug, we are OK with immediately fixing it in one release. maybe @vy-ton has thoughts

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68093#-:-Mfx3ZqA20uRXboe2Bq8:b-oytagb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/logictest/testdata/logic_test/set, line 199 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68093#-Mfx2cMi2ehLqAojOQeD:-Mfx2cMi2ehLqAojOQeE:b-xu7fc) ([raw file](https://github.com/cockroachdb/cockroach/blob/013ea166bbeb00d253cd0b5c3ca72d47bb87a6ff/pkg/sql/logictest/testdata/logic_test/set#L199)):*
> ```
> SET datestyle = 'sql'
> 
> statement error nvalid value for parameter "DateStyle": "other"
> ```

nit: nvalid
___
*[pkg/sql/pgwire/testdata/pgtest/param_status, line 104 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68093#-Mfx2suC-Z6_I4F7ovXn:-Mfx2suC-Z6_I4F7ovXo:b-5i7je7) ([raw file](https://github.com/cockroachdb/cockroach/blob/013ea166bbeb00d253cd0b5c3ca72d47bb87a6ff/pkg/sql/pgwire/testdata/pgtest/param_status#L104)):*
> ```
> 
> send
> Query {"String": "SET DateStyle = 'YMD, ISO'"}
> ```

do we need a `datestyle_enabled` session var as well? or is that just coming in later?

**Review by otan — COMMENTED** [review]
i'll say both.

i wouldn't say we need an extra release, as there is an immediate action a client can do if they relied on YY-MM-DD shortform (use %04d as a format string - it parses as YYYY-MM-DD anyway).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68093#-:-Mg2mcvS45svnOAV0t6D:b-bb56as)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/pgwire/testdata/pgtest/param_status, line 104 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68093#-Mfx2suC-Z6_I4F7ovXn:-Mg2m_RnEHKqrD06-tGP:bg5wngq) ([raw file](https://github.com/cockroachdb/cockroach/blob/013ea166bbeb00d253cd0b5c3ca72d47bb87a6ff/pkg/sql/pgwire/testdata/pgtest/param_status#L104)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

do we need a `datestyle_enabled` session var as well? or is that just coming in later?
</blockquote></details>

coming later! need the builtins implemented first....

**Review by vy-ton — COMMENTED** [review]
> should we list this as a bugfix rather than a backward-incompatible change? or both?

More trickiness with date/time formats. I lean towards both mentioning this as a bug and backward-incompatible change. Clearly, we've seen recent examples that an issue can be both since users could inadvertently rely on the old, buggy behavior.

It's backward-incompatible because a client would have to make an app change to keep the old behavior. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68093#-:-Mg6NJ384nYeQ6x1KhGh:bmhqqrl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Review by rafiss — APPROVED** [review]
lgtm!

**Comment by otan** [comment]
thanks!

bors r=rafiss

**Pull request merged**
