### PR TITLE
tscache: switch to skiplist implementation by default, remove Request interface

### LINKED ISSUE #4768: storage: make cmdQ and tsCache concurrent
I saw nvanbenschoten make some improvement in `cmdQ` and `tsCache`.
It's a very good progress. But I have some other opinions.
When we use cmdQ or tsCache, we have a big locker like:

```
        r.mu.Lock()
        var wg sync.WaitGroup
        var spans []roachpb.Span
        readOnly := ba.IsReadOnly()
        for _, union := range ba.Requests {
            h := union.GetInner().Header()
            spans = append(spans, roachpb.Span{Key: h.Key, EndKey: h.EndKey})
        }
        r.mu.cmdQ.GetWait(readOnly, &wg, spans...)
        cmdKeys = append(cmdKeys, r.mu.cmdQ.Add(readOnly, spans...)...)
        r.mu.Unlock()
```

It will block the system performance heavily when there are concurrent request. 
Especially when each request(batch) has lots of cmds(will do more work in locker area, make other go routine wait more time)
I fact, when there are rare conflict, nvanbenschoten's solution will enlarge the locker area(because need more time to analysis) and decrease the system tps.
And my opinion is: "Because each item in tsCache will removed after 10 second, and each item in cmdQ will removed after several millisecond, So it's not worth to do much work for each item. the life of them are too short"
I saw currently we use red-black tree as base for them. red-black tree is hard for concurrence.
I'm doing some research on it, use skiplist to replace red-black tree and make them concurrent.
And here is preliminary benchmark result:
read32
I the test, I make a client to query value for rand key, and each batch has 32 queries(reads). 
The client can run with n threads. When I increase client threads number, you can see the system tps can't increase in current solution, But can increase obviously in my new solution.

Do you agree this improvement direction? I will try to complete it ASAP.

### LINKED ISSUE #6190: stability: nil pointer panic in timestamp cache
Seen on `cockroach-gamma-5` running e6880ae2b

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xe765a7]

goroutine 201640 [running]:
panic(0x16667e0, 0xc820012080)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/cockroachdb/cockroach/storage.(*Store).Send.func1(0xc82eadf268, 0xc82eadf2d8, 0x14472af1bbd1f04a, 0x0, 0xc82eadf2d0, 0xc82031c900)
        /go/src/github.com/cockroachdb/cockroach/storage/store.go:1558 +0x6e
panic(0x16667e0, 0xc820012080)
        /usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/cockroachdb/cockroach/util/cache.(*entryList).remove(0xc82037b128, 0xc83a500dd0, 0xc887212b80)
        /go/src/github.com/cockroachdb/cockroach/util/cache/cache.go:132 +0x107
github.com/cockroachdb/cockroach/util/cache.(*baseCache).removeElement(0xc82037b100, 0xc83a500dd0)
        /go/src/github.com/cockroachdb/cockroach/util/cache/cache.go:277 +0x3f
github.com/cockroachdb/cockroach/util/cache.(*baseCache).DelEntry(0xc82037b100, 0xc83a500dd0)
        /go/src/github.com/cockroachdb/cockroach/util/cache/cache.go:250 +0x32
github.com/cockroachdb/cockroach/storage.(*TimestampCache).Add(0xc82012db40, 0xc887212b18, 0x5, 0x8, 0xc887212b80, 0x7, 0x8, 0x14472ae78a58f663, 0x1, 0xc887212b70, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/timestamp_cache.go:186 +0x67d
github.com/cockroachdb/cockroach/storage.(*Replica).endCmds(0xc820322700, 0xc86d734040, 0x1, 0x1, 0xc828815180, 0xc82c46ff80, 0x0)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:936 +0x40e
github.com/cockroachdb/cockroach/storage.(*Replica).beginCmds.func1(0xc82c46ff80, 0x0)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:903 +0x5c
github.com/cockroachdb/cockroach/storage.(*Replica).addReadOnlyCmd.func1(0xc82d117b00, 0xc82eade9e8, 0xc82eade9f0)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:1091 +0x36
github.com/cockroachdb/cockroach/storage.(*Replica).addReadOnlyCmd(0xc820322700, 0x7fe348dd2e58, 0xc8209293e0, 0x14472ae78a58f663, 0x1, 0x500000005, 0x5, 0x9, 0x0, 0xc821f
54000, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:1108 +0x423
github.com/cockroachdb/cockroach/storage.(*Replica).Send(0xc820322700, 0x7fe348dd2e58, 0xc8209293e0, 0x14472ae78a58f663, 0x1, 0x500000005, 0x5, 0x9, 0x0, 0xc821f54000, ...
)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:793 +0x500
github.com/cockroachdb/cockroach/storage.(*Store).Send(0xc82031c900, 0x7fe348dd2e58, 0xc8209293e0, 0x14472ae78a58f663, 0x1, 0x500000005, 0x5, 0x9, 0x0, 0xc821f54000, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/store.go:1653 +0xe8e
github.com/cockroachdb/cockroach/storage.(*Stores).Send(0xc8203f8280, 0x7fe348dd2e58, 0xc820929380, 0x0, 0x0, 0x500000005, 0x5, 0x9, 0x0, 0xc821f54000, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/stores.go:178 +0x501
github.com/cockroachdb/cockroach/server.(*Node).Batch.func2()
        /go/src/github.com/cockroachdb/cockroach/server/node.go:730 +0x55b
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunTask(0xc8203b17a0, 0xc82eadf880, 0x0)
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:166 +0xd9
github.com/cockroachdb/cockroach/server.(*Node).Batch(0xc820346600, 0x7fe348dd2e58, 0xc820929110, 0xc828814e70, 0xb03ecef60a8a6a87, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/server/node.go:742 +0x2c0
github.com/cockroachdb/cockroach/roachpb._Internal_Batch_Handler(0x17a2ae0, 0xc820346600, 0x7fe348dd2e58, 0xc820929110, 0xc821fa9480, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/roachpb/api.pb.go:1336 +0x132
google.golang.org/grpc.(*Server).processUnaryRPC(0xc82000c580, 0x7fe348dd4418, 0xc82000abd0, 0xc82e7321c0, 0xc8204280a0, 0x22abba0, 0x0, 0x0, 0x0)
        /go/src/google.golang.org/grpc/server.go:497 +0xe13
google.golang.org/grpc.(*Server).handleStream(0xc82000c580, 0x7fe348dd4418, 0xc82000abd0, 0xc82e7321c0, 0x0)
        /go/src/google.golang.org/grpc/server.go:646 +0x109d
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc822a08980, 0xc82000c580, 0x7fe348dd4418, 0xc82000abd0, 0xc82e7321c0)
        /go/src/google.golang.org/grpc/server.go:323 +0xa0
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /go/src/google.golang.org/grpc/server.go:324 +0x9a
```

### LINKED ISSUE #14518: storage: revisit TimestampCache eviction policy
Internally, the `TimestampCache` has 3 caches: a read interval cache, a write interval cache and a request cache. The combined size of the caches is limited to `TimestampCache.maxBytes`, but the eviction from the caches is funky: we only evict from one of the sub-caches when inserting into it. For example, `TimestampCache.AddRequest` is the only place we evict from the request cache.

I'm not certain that this behavior is problematic, though it seems odd that inserting into the read interval cache might push `TimestampCache.bytes` over the `maxBytes` threshold, but not result in anything being evicted because all of the memory is consumed in the write interval cache.

### LINKED ISSUE #16796: perf: timestampCache causes GC-related slowdown
Running a read-only workload on a single node cluster shows performance degradation from ~19k ops/sec to a steady state of ~13.5k ops/sec. Investigation eventually pointed to the `timestampCache`. Specifically, if `timestampCache.AddRequest` is disabled, steady state performance is ~18k ops/sec. The workload under investigation is:

```
kv --read-percent 100 --concurrency 16 --splits 100 --write-seq 100000
```

Interestingly, the manipulation of the `timestampCache.requests` btree by `AddRequest` doesn't seem to be the problem. If `AddRequest` is tweaked to add and immediately delete the request, performance is good.

Part of the problem seems to be the btree. Replacing the btree with a fixed size ring buffer of approximately the same size results in steady state performance of ~15k ops/sec. The ring buffer experiment isn't a drop in replacement. More work would be required to flesh out its functionality and that additional functionality might end up negating the modest improvement it is providing.

Another experiment was to zero the `cacheRequest` before inserting it. This brought steady state performance back up to ~17k ops/sec. 

My current suspicion is that the non-zeroed `cacheRequests` are causing additional GC pressure. Enabling `GODEBUG=gctrace=1` shows:

|   | GC CPU  |
| ------------- | ------------- |
| master | 13% |
| disabled timestampCache | 7% |
| zeroed cacheRequest | 8% |

Note that there are two fields in `cacheRequest` that zeroing affects with this workload: `cacheRequest.span` and `cacheRequest.reads`. I'm not sure what to do here. We need the spans in order to later expand the requests into the interval tree. It is surprising to me that merely holding on to these keys is causing additional GC CPU usage. Suggestions are welcome.

### LINKED ISSUE #16901: storage: panic in timestamp cache
https://teamcity.cockroachdb.com/viewLog.html?buildId=288188&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests

Running this test for a few minutes on my laptop didn't reproduce it.

Partial stack trace:

```
E170706 06:58:05.671928 47242518 util/log/crash_reporting.go:82  [n1] a panic has occurred!
W170706 06:58:05.672208 182 storage/store.go:3569  [n1,s1,r5/1:/Table/{0-11}] handle raft ready: 1.0s [processed=1]
E170706 06:58:05.675474 47242518 util/log/crash_reporting.go:183  [n1] Reported as error 3dfc345caf92466cb0c7c5136b0a76a4
panic: bad reqSize: 14 < 152 [recovered]
    panic: bad reqSize: 14 < 152 [recovered]
    panic: bad reqSize: 14 < 152

goroutine 47242518 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4200b0630, 0x7f0b2111e8c0, 0xc42cea8c00)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:180 +0xb1
panic(0x186ebe0, 0xc4295ce150)
    /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send.func1(0xc4283eb540, 0xc4283eb5b0, 0x14ceab7e3f00479a, 0x0, 0xc4283eb5a8, 0xc420214800)
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2491 +0x224
panic(0x186ebe0, 0xc4295ce150)
    /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/storage.(*timestampCache).ExpandRequests(0xc4200ee000, 0x14cea8d5d767f9f7, 0xc400000000, 0xc4203dc6b8, 0x2, 0x8, 0xc42a390fd0, 0xf, 0x10)
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/timestamp_cache.go:659 +0x5c0
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).applyTimestampCache(0xc4201fee00, 0xc4319dbab0, 0xc42cea8c00, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2093 +0x176
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).tryExecuteWriteBatch(0xc4201fee00, 0x7f0b2111e8c0, 0xc42cea8cf0, 0x14cea8d5d767f9f7, 0x0, 0x100000001, 0x1, 0x5, 0x3ff0000000000000, 0xc426516820, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2465 +0x27f
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).executeWriteBatch(0xc4201fee00, 0x7f0b2111e8c0, 0xc42cea8cf0, 0x14cea8d5d767f9f7, 0x0, 0x100000001, 0x1, 0x5, 0x3ff0000000000000, 0xc426516820, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2342 +0x9d
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc4201fee00, 0x7f0b2111e8c0, 0xc42cea8cf0, 0x14cea8d5d767f9f7, 0x0, 0x100000001, 0x1, 0x5, 0x3ff0000000000000, 0xc426516820, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1677 +0x23d
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send(0xc420214800, 0x7f0b2111e8c0, 0xc42cea8c30, 0x14cea8d5d767f9f7, 0x0, 0x100000001, 0x1, 0x5, 0x3ff0000000000000, 0xc426516820, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2593 +0x5ad
github.com/cockroachdb/cockroach/pkg/storage.(*Stores).Send(0xc4205b0800, 0x7f0b2111e8c0, 0xc42cea8c00, 0x0, 0x0, 0x100000001, 0x1, 0x5, 0x3ff0000000000000, 0xc426516820, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/stores.go:187 +0x1ea
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal.func1(0x7f0b2111e8c0, 0xc42cea8c00, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:821 +0x19d
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc4200b0630, 0x7f0b2111e8c0, 0xc42cea8c00, 0x1aaa9f0, 0x10, 0xc4283eb820, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:245 +0xf7
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal(0xc420527b80, 0x7f0b2111e8c0, 0xc42cea8c00, 0xc42779cf48, 0xc42cea8c00, 0x1f, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:832 +0x119
github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch(0xc420527b80, 0x7f0b2111e8c0, 0xc42cea8c00, 0xc42779cf48, 0x1f, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:849 +0x99
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext.func1.1(0xc42b07fdb0, 0xc42779cf20, 0x7f0b2111e8c0, 0xc42cea8a50, 0xc420ba7788, 0xed8b70, 0x7f0b2111e8c0)
    /go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:257 +0x49e
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext.func1(0xc42b07fdb0, 0xc42779cf20, 0x7f0b2111e8c0, 0xc42cea8a50, 0x272fa40, 0xc4203bc1c0, 0xc42c8c41e0)
    /go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:270 +0x7e
created by github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext
    /go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:283 +0x141
```

### LINKED ISSUE #20123: teamcity: TestReplicaUpdateTSCache failed
https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=412962&_focus=64250

```
replica_test.go:1973: expected rTS=1s and wTS=0s, but got 0.000000123,0, 0.000000123,0; rTxnID=00000000-0000-0000-0000-000000000000, wTxnID=00000000-0000-0000-0000-000000000000
replica_test.go:1979: expected rTS=0s and wTS=2s, but got 0.000000123,0, 0.000000123,0; rTxnID=00000000-0000-0000-0000-000000000000, wTxnID=00000000-0000-0000-0000-000000000000
```

This is with the old tscache, but I recently touched this test so I must have made it flaky.

### PR DESCRIPTION
**Pull request by nvb**
Follow up to #19508.
Closes #4768.
Closes #6190.
Closes #14518.
Closes #16901.
Closes #16796.
Closes #20123.
Part of #17172.

This change switches the default `tscache.Cache` implementation to `sklImpl`. In doing so, it performs a series of cleanup steps that improve the external interface of `tscache.Cache` and improve `sklImpl's` performance moderately. This comes at the cost of removing some optimizations built into the `treeImpl`. Since we're no longer going to use that outside of testing, its performance matters less, so the tradeoff is worth it. The change is broken into a series of steps so that each one is self-contained:
1. Switch the `tscache` package to create `sklImpl` instances by default.
2. Make `treeImpl` thread-safe by adding internal locking.
3. Remove the `ThreadSafe` method from `tscache.Cache`. Remove the `tsCacheMu` lock from `Store`.
4. Remove the `requests` tree optimization from `treeImpl`.
5. Remove the `Request` type and `{Add,Expand}Request` methods from the `tscache` package. `tscache.Cache` now exports its `Add` method, which is used by `Replica` directly.

Before merging this, I want to see at least a few successful runs of Jepsen with the change enabled.

I'll also add some concrete benchmarks from before and after this change.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
This change just passed Jepsen: https://teamcity.cockroachdb.com/viewLog.html?buildId=421110. I'll run it a few times, but at this point, I don't expect anything to change. 

Also, to confirm that the change will produce benchmark numbers comparable to what we saw in the [initial investigation](https://github.com/cockroachdb/cockroach/pull/19508), I ran `./kv --read-percent=95 --splits=100 --concurrency=48 --write-seq 100000` across a 3 node cluster with and without the change. The numbers looked close to what we expected:

```
BEFORE:
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
  300.0s        0        3849972        12833.1      3.7      1.2     23.1     48.2    285.2

BenchmarkLoadgenKV/readPercent=95/splits=100/concurrency=48/duration=5m0s	 3849972	     77923 ns/op

AFTER:
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
  300.0s        0        4589871        15299.5      3.1      1.2     18.9     46.1    268.4

BenchmarkLoadgenKV/readPercent=95/splits=100/concurrency=48/duration=5m0s	 4589871	     65361 ns/op

Throughput increased by **19%**
50th percentile latency dropped by **16%**
95th percentile latency dropped by **19%**
99th percentile latency dropped by **4%**
```

The only surprising part is that my testing here didn't seem to affect 99th percentile latency. I think that's because the initial testing was using a single node cluster and the testing here is on a three node cluster, so there are other dominant factors that are now influencing the 99th percentile latency.

**Comment by tschottdorf** [comment]
:lgtm:! So good to see this coming to a close.

---

Reviewed 4 of 4 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 9 of 9 files at r4, 4 of 4 files at r5, 10 of 10 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica.go, line 1995 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/20232#-L-D-zzJhu3i9l2EXu1D:-L-D-ZSdbkjI2qnBK2OB:b-6oammf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b1f93c55304d27793ae2ba2ae5b647691701104/pkg/storage/replica.go#L1995)):*
> ```Go
> func (r *Replica) updateTimestampCache(ba *roachpb.BatchRequest, br *roachpb.BatchResponse) {
> 	// Create booleans to be passed as tsCache.Add's readCache argument.
> 	updateWriteCache := false
> ```

I got confused by these names. Do you need both of these variables or can you get away with a single variable? I don't see any mutations of `updateWriteCache`. Maybe reduce to one and call it `readOnlyUseReadCache`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20232#-:-L-D1QMaLc5LF0n468oX:befud96)*

**Comment by nvanbenschoten** [comment]
TFTR!

---

Review status: 3 of 17 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica.go, line 1995 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/20232#-L-D-zzJhu3i9l2EXu1D:-L-D5VPpHUU3bOzLJoYZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b1f93c55304d27793ae2ba2ae5b647691701104/pkg/storage/replica.go#L1995)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

I got confused by these names. Do you need both of these variables or can you get away with a single variable? I don't see any mutations of `updateWriteCache`. Maybe reduce to one and call it `readOnlyUseReadCache`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20232#-:-L-D4z691a7nlsEhtAa5:b-814g8k)*

**Comment by petermattis** [comment]
🎉 🎉 🎉

**Pull request merged**
