### PR TITLE
[WIP] libroach: automatically compact files with too many range deletions

### PR DESCRIPTION
**Pull request by petermattis**
Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
TBD is what to do with the compactor now that it is no longer necessary. What needs to replace it is something which calls `Flush` some reasonably short period of time after a `ClearRange` has been performed. Do I repurpose the compactor for this? Do I create a new background goroutine for performing this work? Do I worry about calling `Flush` unnecessarily (i.e. when an automatic flush has already taken place)?

I'm currently leaning towards stripping the compactor down to its essence and having a call to `Compactor.Flush` wake up the compactor queue which will call `Flush`. There will be no need for the compactor to persist anything to disk as `Flush` is automatically called by RocksDB after replaying the WAL. Lastly, I'm not going to worry about unnecessary `Flush` calls. Ideally, RocksDB would be performing these flushes internally, but an extra `Flush` after `ClearRange` is unlikely to kill performance.

Thoughts?

**Comment by benesch** [comment]
Sounds good to me. I'm assuming you won't ever flush more than once every _n_ seconds?

**Review by bdarnell — COMMENTED** [review]
Why do we need the explicit Flush? 

How does this work in transition? Existing sstables won't have the new properties attached; could those be left around for a long time?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31975#-:-LQ-zxJnCUTA288EmDbU:ba3bkdu)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by petermattis — COMMENTED** [review]
> Sounds good to me. I'm assuming you won't ever flush more than once every n seconds?

Yeah, there would be some limiter on how frequently the flushes occur.

> Why do we need the explicit Flush?

Without an explicit flush, the memtable can accumulate an excessive number of range deletions which slow performance and prevent disk space from being recovered. In the absence of other activity on the system, the range tombstones can sit in the memtable for a long period of time.

> How does this work in transition? Existing sstables won't have the new properties attached; could those be left around for a long time?

I suppose I could let the existing compactor clear its queue.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31975#-:-LQ01BZMA-B3hb4NoYrd:b-weja0e)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request closed without merging**
