### PR TITLE
storageccl: support RESTORE of interleaved tables

### LINKED ISSUE #14856: restore: interleaved tables don't rekey correctly
Repros by adding ```sqlDBRestore.Exec(`CREATE DATABASE ignored`)``` to the beginning of TestBackupRestoreInterleaved/"all tables in interleave hierarchy"

### PR DESCRIPTION
**Pull request by madelynnblue**
Fixes #14856

### CODE REVIEW

**Comment by danhhz** [comment]
Thanks for picking this up! I like the recursive solution

Can you also write up the whole context for this in the commit message, please?

---

Review status: 0 of 4 files reviewed at latest revision, 11 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/storageccl/import.go, line 77 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj4c54osDRwCL_fd8Q0:-Kj4c54osDRwCL_fd8Q1:b-g0rtrk) ([raw file](https://github.com/cockroachdb/cockroach/blob/78d05f0f19cff40b2bd14d45eb61be8c4c441745/pkg/ccl/storageccl/import.go#L77)):*
> ```Go
> 		var desc sqlbase.Descriptor
> 		if err := desc.Unmarshal(rekey.NewDesc); err != nil {
> 			return nil, err
> ```

wrap this error please (probably including the old id in the message somehow)

---

*[pkg/ccl/storageccl/import.go, line 205 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj4fCmYqmbMQeBdDxqU:-Kj4fCmYqmbMQeBdDxqV:bc65bol) ([raw file](https://github.com/cockroachdb/cockroach/blob/78d05f0f19cff40b2bd14d45eb61be8c4c441745/pkg/ccl/storageccl/import.go#L205)):*
> ```Go
> 		var ok bool
> 		var err error
> 		key.Key, ok, err = RewriteInterleavedKey(kr, descs, 0, key.Key)
> ```

I think we actually need this call in more places than this. We could end up with splits in the middle of a bunch of interleaved data (say one customer has more than 64MB of data, easy to make this case in a test using SPLIT AT), so the various start and end keys involved throughout restore should be rewritten as well

---

*[pkg/ccl/storageccl/key_rewriter.go, line 27 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj4j_TrZkHeTZhL7XEF:-Kj4j_Ts2vjvBXser1Bw:b-5xx5gj) ([raw file](https://github.com/cockroachdb/cockroach/blob/78d05f0f19cff40b2bd14d45eb61be8c4c441745/pkg/ccl/storageccl/key_rewriter.go#L27)):*
> ```Go
> // RewriteKey modifies key using the first matching rule and returns it. If no
> // rules matched, returns false and the original input key.
> func (kr KeyRewriter) RewriteKey(key []byte) ([]byte, bool) {
> ```

KeyRewriter should instead wrap the `map[sqlbase.ID]*sqlbase.TableDescriptor` and we should get rid of all the byte prefix rules

---

*[pkg/ccl/storageccl/key_rewriter.go, line 45 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj4lG90ptzmsv_IXkzl:-Kj4lG90ptzmsv_IXkzm:bdau7vp) ([raw file](https://github.com/cockroachdb/cockroach/blob/78d05f0f19cff40b2bd14d45eb61be8c4c441745/pkg/ccl/storageccl/key_rewriter.go#L45)):*
> ```Go
> 
> // RewriteInterleavedKey modifies key similar to RewriteKey, but is also
> // able to account for interleaved tables.
> ```

Describe the general process of what this is doing in the doc comment

---

*[pkg/ccl/storageccl/key_rewriter.go, line 46 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj4iy8dSvOZFLQtIIqR:-Kj4iy8dSvOZFLQtIIqS:b-1bxs1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/78d05f0f19cff40b2bd14d45eb61be8c4c441745/pkg/ccl/storageccl/key_rewriter.go#L46)):*
> ```Go
> // RewriteInterleavedKey modifies key similar to RewriteKey, but is also
> // able to account for interleaved tables.
> func RewriteInterleavedKey(kr KeyRewriter, descs map[sqlbase.ID]*sqlbase.TableDescriptor, skipKeys int, key []byte) ([]byte, bool, error) {
> ```

I was wrong, you don't need to pass along skipKeys. The same information is available as `index.Interleave.Ancestors[len(index.Interleave.Ancestors)-1].SharedPrefixLen`

---

*[pkg/ccl/storageccl/key_rewriter.go, line 58 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj4gnMeTHMnvNlaMfDS:-Kj4gnMeTHMnvNlaMfDT:bc2j1j9) ([raw file](https://github.com/cockroachdb/cockroach/blob/78d05f0f19cff40b2bd14d45eb61be8c4c441745/pkg/ccl/storageccl/key_rewriter.go#L58)):*
> ```Go
> 	desc := descs[sqlbase.ID(tableID)]
> 	if desc == nil {
> 		return nil, false, errors.New("missing table descriptor")
> ```

include the table id in the error, plz

---

*[pkg/ccl/storageccl/key_rewriter.go, line 61 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj4gv9EKYLH9AGiFElv:-Kj4gv9EKYLH9AGiFElw:bdgt90e) ([raw file](https://github.com/cockroachdb/cockroach/blob/78d05f0f19cff40b2bd14d45eb61be8c4c441745/pkg/ccl/storageccl/key_rewriter.go#L61)):*
> ```Go
> 	}
> 	// Check if this key may have interleaved children.
> 	k, _, indexID, err := sqlbase.DecodeTableIDIndexID(key)
> ```

This is decoding the table id a second time. You can call this instead of the first DecodeUvarintAscending

---

*[pkg/ccl/storageccl/key_rewriter.go, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj4hPJhDt81WMmrqzGO:-Kj4hPJhDt81WMmrqzGP:b-1d3ggp) ([raw file](https://github.com/cockroachdb/cockroach/blob/78d05f0f19cff40b2bd14d45eb61be8c4c441745/pkg/ccl/storageccl/key_rewriter.go#L75)):*
> ```Go
> 	// We do not support interleaved secondary indexes.
> 	if idx.ID != desc.PrimaryIndex.ID {
> 		return nil, false, errors.New("interleaved secondary indexes not supported")
> ```

true, but I think this error should be specifically about restoring interleaved secondary indexes not being supported. wdyt?

---

*[pkg/ccl/storageccl/key_rewriter.go, line 77 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj4hzYdEt9KbqLbPpOg:-Kj4hzYdEt9KbqLbPpOh:b-nl77y) ([raw file](https://github.com/cockroachdb/cockroach/blob/78d05f0f19cff40b2bd14d45eb61be8c4c441745/pkg/ccl/storageccl/key_rewriter.go#L77)):*
> ```Go
> 		return nil, false, errors.New("interleaved secondary indexes not supported")
> 	}
> 	colIDs, dirs := idx.FullColumnIDs()
> ```

we should add something to the tests for this (STORING, decimals, etc)

---

*[pkg/ccl/storageccl/key_rewriter.go, line 82 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj4ijXLgOmp-FOean0L:-Kj4ijXLgOmp-FOean0M:bdvffsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/78d05f0f19cff40b2bd14d45eb61be8c4c441745/pkg/ccl/storageccl/key_rewriter.go#L82)):*
> ```Go
> 		return nil, false, err
> 	}
> 	k, err = sqlbase.DecodeKeyVals(nil, vals[skipKeys:], dirs[skipKeys:], k)
> ```

This is going to allocate like crazy. Instead use encoding.PeekLength to skip over the columns

---

*[pkg/ccl/storageccl/key_rewriter.go, line 96 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj4iL_tTZWQSI76f-un:-Kj4iL_uj9rt9CePTnN4:bq50dlc) ([raw file](https://github.com/cockroachdb/cockroach/blob/78d05f0f19cff40b2bd14d45eb61be8c4c441745/pkg/ccl/storageccl/key_rewriter.go#L96)):*
> ```Go
> 		if !ok {
> 			// The interleaved child was not rewritten, skip this row.
> 			return key, false, nil
> ```

key will have already had the first tableID rewritten in this case. not much we can do about that though i guess

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-:-Kj4k_cmC1EFBhgMio7p:bv19lqj)*

**Comment by mjibson** [comment]
Review status: 0 of 5 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/storageccl/import.go, line 77 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj4c54osDRwCL_fd8Q0:-Kj4nKzYfS4nXB8m_6-v:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78d05f0f19cff40b2bd14d45eb61be8c4c441745/pkg/ccl/storageccl/import.go#L77)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

wrap this error please (probably including the old id in the message somehow)
</blockquote></details>

Done.

---

*[pkg/ccl/storageccl/key_rewriter.go, line 27 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj4j_TrZkHeTZhL7XEF:-Kj6VKCjFL9mnhCOibeb:b-rgebuj) ([raw file](https://github.com/cockroachdb/cockroach/blob/78d05f0f19cff40b2bd14d45eb61be8c4c441745/pkg/ccl/storageccl/key_rewriter.go#L27)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

KeyRewriter should instead wrap the `map[sqlbase.ID]*sqlbase.TableDescriptor` and we should get rid of all the byte prefix rules
</blockquote></details>

Why do we need to get rid of the byte prefix rules? We need to check the end prefixes, which are simply handled by those. I can see the argument for generating the byte prefixes downstream of an RPC, but not removing them altogether.

---

*[pkg/ccl/storageccl/key_rewriter.go, line 45 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj4lG90ptzmsv_IXkzl:-Kj6afmI-KLkBiZNqYyb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78d05f0f19cff40b2bd14d45eb61be8c4c441745/pkg/ccl/storageccl/key_rewriter.go#L45)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Describe the general process of what this is doing in the doc comment
</blockquote></details>

Done.

---

*[pkg/ccl/storageccl/key_rewriter.go, line 46 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj4iy8dSvOZFLQtIIqR:-Kj6VkfpLF9F0a-1EBy-:b91uewk) ([raw file](https://github.com/cockroachdb/cockroach/blob/78d05f0f19cff40b2bd14d45eb61be8c4c441745/pkg/ccl/storageccl/key_rewriter.go#L46)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I was wrong, you don't need to pass along skipKeys. The same information is available as `index.Interleave.Ancestors[len(index.Interleave.Ancestors)-1].SharedPrefixLen`
</blockquote></details>

I attempted this but none of the table descriptors had a non-zero value'd Ancestors field. Not sure why but I'm keeping the skip code for now.

---

*[pkg/ccl/storageccl/key_rewriter.go, line 58 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj4gnMeTHMnvNlaMfDS:-Kj6VzgCRvL-1fTWCncY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78d05f0f19cff40b2bd14d45eb61be8c4c441745/pkg/ccl/storageccl/key_rewriter.go#L58)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

include the table id in the error, plz
</blockquote></details>

Done.

---

*[pkg/ccl/storageccl/key_rewriter.go, line 61 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj4gv9EKYLH9AGiFElv:-Kj6W0F7b0KvcSBNGXc7:b-7tapau) ([raw file](https://github.com/cockroachdb/cockroach/blob/78d05f0f19cff40b2bd14d45eb61be8c4c441745/pkg/ccl/storageccl/key_rewriter.go#L61)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

This is decoding the table id a second time. You can call this instead of the first DecodeUvarintAscending
</blockquote></details>

This is decoding the new table ID because kr.RewriteKey happens before this, so I think it's not redundant.

---

*[pkg/ccl/storageccl/key_rewriter.go, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj4hPJhDt81WMmrqzGO:-Kj6WKmc5WTLKxl61iy4:bdzdyev) ([raw file](https://github.com/cockroachdb/cockroach/blob/78d05f0f19cff40b2bd14d45eb61be8c4c441745/pkg/ccl/storageccl/key_rewriter.go#L75)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

true, but I think this error should be specifically about restoring interleaved secondary indexes not being supported. wdyt?
</blockquote></details>

added the word "restoring" in front

---

*[pkg/ccl/storageccl/key_rewriter.go, line 77 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj4hzYdEt9KbqLbPpOg:-Kj6hgLwAcD9CfkBIl6N:bmamrto) ([raw file](https://github.com/cockroachdb/cockroach/blob/78d05f0f19cff40b2bd14d45eb61be8c4c441745/pkg/ccl/storageccl/key_rewriter.go#L77)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

we should add something to the tests for this (STORING, decimals, etc)
</blockquote></details>

Added some various indexes to a test. Composites (decimals) don't change much here because that just adds more value data, nothing to the keys.

---

*[pkg/ccl/storageccl/key_rewriter.go, line 82 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj4ijXLgOmp-FOean0L:-Kj6WTPJezIsQHtJsaGO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78d05f0f19cff40b2bd14d45eb61be8c4c441745/pkg/ccl/storageccl/key_rewriter.go#L82)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

This is going to allocate like crazy. Instead use encoding.PeekLength to skip over the columns
</blockquote></details>

Done.

---

*[pkg/ccl/storageccl/key_rewriter.go, line 96 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj4iL_tTZWQSI76f-un:-Kj6W_GMUybzXc2ORU8N:b-e4q4ym) ([raw file](https://github.com/cockroachdb/cockroach/blob/78d05f0f19cff40b2bd14d45eb61be8c4c441745/pkg/ccl/storageccl/key_rewriter.go#L96)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

key will have already had the first tableID rewritten in this case. not much we can do about that though i guess
</blockquote></details>

Yes, it's slightly a lie. But returning false does the correct thing later on, which is to ignore the row.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564)*

**Comment by mjibson** [comment]
Updated with a fix for the split test.

**Comment by mjibson** [comment]
Reformatted with correct crlfmt.

**Comment by danhhz** [comment]
LGTM. I think there's some followup work to do here, but more important that this makes 1.0

---

Review status: 0 of 9 files reviewed at latest revision, 20 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/key_rewriter.go, line 22 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-KjAsgjJc8pBAnnt259l:-KjAsgjKcoCEbkjOPfmN:b-7ks8d0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c04207cc142666fa93bfcc207be18b571c2e5e54/pkg/ccl/sqlccl/key_rewriter.go#L22)):*
> ```Go
> // implementation of the matching is in storageccl, but the interesting
> // constructor is here.
> func MakeKeyRewriterForNewTableID(
> ```

this is no longer used outside tests. i think you can just move the one test in sqlccl/key_rewriter_test.go to storageccl and remove key_rewriter from sqlccl entirely

---

*[pkg/ccl/storageccl/import.go, line 58 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj9vh6s03gLtg_4_q5X:-Kj9vh6tzhureT6WiQuA:byybuq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/beb2d35c19ad1206d6dfd43148277eedcde05874/pkg/ccl/storageccl/import.go#L58)):*
> ```Go
> 		importStart, ok, _ = kr.RewriteKey(append([]byte(nil), args.DataSpan.Key...))
> 		if !ok {
> 			return nil, errors.Errorf("could not rewrite start span key: %s", importStart)
> ```

nit "span start". same for "span end" below

---

*[pkg/ccl/storageccl/key_rewriter.go, line 27 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj4j_TrZkHeTZhL7XEF:-KjAtbmhQnsV9AiZnZoO:blbs9ue) ([raw file](https://github.com/cockroachdb/cockroach/blob/78d05f0f19cff40b2bd14d45eb61be8c4c441745/pkg/ccl/storageccl/key_rewriter.go#L27)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Why do we need to get rid of the byte prefix rules? We need to check the end prefixes, which are simply handled by those. I can see the argument for generating the byte prefixes downstream of an RPC, but not removing them altogether.
</blockquote></details>

I'm happy with them as an internal detail of KeyRewriter (as you have them in this revision). unexport this method though, please

---

*[pkg/ccl/storageccl/key_rewriter.go, line 46 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj4iy8dSvOZFLQtIIqR:-KjAu95m7k-GHX1GK7EO:byeobnr) ([raw file](https://github.com/cockroachdb/cockroach/blob/78d05f0f19cff40b2bd14d45eb61be8c4c441745/pkg/ccl/storageccl/key_rewriter.go#L46)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I attempted this but none of the table descriptors had a non-zero value'd Ancestors field. Not sure why but I'm keeping the skip code for now.
</blockquote></details>

leave a TODO then please. also can we call this var sharedPrefixLen (or at the very least skipCols)

---

*[pkg/ccl/storageccl/key_rewriter.go, line 61 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj4gv9EKYLH9AGiFElv:-KjAuZl4oehipaYFBfJa:bkr5npi) ([raw file](https://github.com/cockroachdb/cockroach/blob/78d05f0f19cff40b2bd14d45eb61be8c4c441745/pkg/ccl/storageccl/key_rewriter.go#L61)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

This is decoding the new table ID because kr.RewriteKey happens before this, so I think it's not redundant.
</blockquote></details>

Ah, I see. I think there's something smarter to be done here but this is fine for 1.0

---

*[pkg/ccl/storageccl/key_rewriter.go, line 20 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj9w2jtHrtf8b3fdAXd:-Kj9w2jtHrtf8b3fdAXe:bgzm447) ([raw file](https://github.com/cockroachdb/cockroach/blob/beb2d35c19ad1206d6dfd43148277eedcde05874/pkg/ccl/storageccl/key_rewriter.go#L20)):*
> ```Go
> )
> 
> // PrefixRewrite holds information for a single byte replacement of a prefix.
> ```

sounds like a replacement of a single byte

---

*[pkg/ccl/storageccl/key_rewriter.go, line 21 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-KjAr2Rag2zWKsS4zeVs:-KjAr2Rag2zWKsS4zeVt:b-lh0pyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/beb2d35c19ad1206d6dfd43148277eedcde05874/pkg/ccl/storageccl/key_rewriter.go#L21)):*
> ```Go
> 
> // PrefixRewrite holds information for a single byte replacement of a prefix.
> type PrefixRewrite struct {
> ```

unexport PrefixRewriter

---

*[pkg/ccl/storageccl/key_rewriter.go, line 28 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj9wL3S6UhWHY71gjqo:-Kj9wL3S6UhWHY71gjqp:b-t2dnyb) ([raw file](https://github.com/cockroachdb/cockroach/blob/beb2d35c19ad1206d6dfd43148277eedcde05874/pkg/ccl/storageccl/key_rewriter.go#L28)):*
> ```Go
> // PrefixRewriter is a matcher for an ordered list of pairs of byte prefix
> // rewrite rules. For dependency reasons, the implementation of the matching
> // is here, but the interesting constructor is in sqlccl.
> ```

"interesting constructor is in sqlccl" this is no longer true, right?

---

*[pkg/ccl/storageccl/key_rewriter.go, line 58 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj9wcPC3bqMnQhiKP5G:-Kj9wcPDuN_2RiPdzS6h:b-x924a8) ([raw file](https://github.com/cockroachdb/cockroach/blob/beb2d35c19ad1206d6dfd43148277eedcde05874/pkg/ccl/storageccl/key_rewriter.go#L58)):*
> ```Go
> }
> 
> // MakeKeyRewriter creates a KeyRewriter from the Rekeys field of an
> ```

instead of "Rekeys field of an ImportRequest" mention conceptually what data is included in that

---

*[pkg/ccl/storageccl/key_rewriter.go, line 68 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj9wyLKjnOv35pbxXY4:-Kj9wyLL1HGAvGRULv42:bbz683h) ([raw file](https://github.com/cockroachdb/cockroach/blob/beb2d35c19ad1206d6dfd43148277eedcde05874/pkg/ccl/storageccl/key_rewriter.go#L68)):*
> ```Go
> 			return nil, errors.Wrapf(err, "unmarshalling rekey descriptor for old table id %d", rekey.OldID)
> 		}
> 		descs[sqlbase.ID(rekey.OldID)] = desc.GetTable()
> ```

error if it's not a table? (GetTable would return nil)

---

*[pkg/ccl/storageccl/key_rewriter.go, line 122 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-KjAr8_JsJ6qit2tHrun:-KjAr8_JsJ6qit2tHruo:b-f8jfbc) ([raw file](https://github.com/cockroachdb/cockroach/blob/beb2d35c19ad1206d6dfd43148277eedcde05874/pkg/ccl/storageccl/key_rewriter.go#L122)):*
> ```Go
> // is, to find the next prefix of an interleaved child, then calls itself
> // recursively until all interleaved children have been rekeyed.
> func (kr *KeyRewriter) RewriteKey(key []byte) ([]byte, bool, error) {
> ```

"RewriteKey modifies key similar to RewriteKey"

---

*[pkg/ccl/storageccl/key_rewriter.go, line 171 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-KjAvcYv5OvN6OJSEokZ:-KjAvcYw-3rnWzsQ4XWW:bvjvap6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c04207cc142666fa93bfcc207be18b571c2e5e54/pkg/ccl/storageccl/key_rewriter.go#L171)):*
> ```Go
> 	// If we get a NotNULL, it's interleaved.
> 	k, ok = encoding.DecodeIfNotNull(k)
> 	if ok {
> ```

invert this if and early return `if !ok`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-:-KjAvkul90OKHdhtakc2:b2lzz5s)*

**Comment by mjibson** [comment]
I've made the suggested user-facing code changes. I've left the comment fixes, renames, and other refactorings for a followup commit post 1.0.

---

Review status: 0 of 9 files reviewed at latest revision, 20 unresolved discussions.

---

*[pkg/ccl/storageccl/import.go, line 205 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj4fCmYqmbMQeBdDxqU:-KjCSN4QIxswjQvxaOSB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78d05f0f19cff40b2bd14d45eb61be8c4c441745/pkg/ccl/storageccl/import.go#L205)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I think we actually need this call in more places than this. We could end up with splits in the middle of a bunch of interleaved data (say one customer has more than 64MB of data, easy to make this case in a test using SPLIT AT), so the various start and end keys involved throughout restore should be rewritten as well
</blockquote></details>

Done.

---

*[pkg/ccl/storageccl/import.go, line 58 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj9vh6s03gLtg_4_q5X:-KjCTCeduVUTSFN4wX6E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/beb2d35c19ad1206d6dfd43148277eedcde05874/pkg/ccl/storageccl/import.go#L58)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit "span start". same for "span end" below
</blockquote></details>

Done.

---

*[pkg/ccl/storageccl/key_rewriter.go, line 68 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-Kj9wyLKjnOv35pbxXY4:-KjCSyVEyOzzcdmtxnkT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/beb2d35c19ad1206d6dfd43148277eedcde05874/pkg/ccl/storageccl/key_rewriter.go#L68)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

error if it's not a table? (GetTable would return nil)
</blockquote></details>

Done.

---

*[pkg/ccl/storageccl/key_rewriter.go, line 171 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-KjAvcYv5OvN6OJSEokZ:-KjCSlLkmYxw9eg2HbYN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c04207cc142666fa93bfcc207be18b571c2e5e54/pkg/ccl/storageccl/key_rewriter.go#L171)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

invert this if and early return `if !ok`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15564#-:-KjCTP4lmZ-RpmIV3obP:bnbqn9v)*

**Comment by danhhz** [comment]
Merging to get this in rc2. @mjibson will followup with the rest of the comments after 1.0

**Pull request merged**
