### PR TITLE
server: Add Localities to Diagnostic Reporting

### PR DESCRIPTION
**Pull request by BramGruneir**
Localities are reported and hashed on a per node basis, but we should be able to determine the number of localities by looking at all the reporting nodes.

This also adds the option to set localities on the test server, which was required for testing.

### CODE REVIEW

**Comment by bdarnell** [comment]
Localities are likely to be chosen from a fairly small set; hashing them is likely to be reversible. We shouldn't upload localities unless we'd be willing to do it in unhashed form, and I don't think we want to do that (same for app names, actually - I didn't know we were doing this and I think we should take it out). 

Instead, I would suggest a per-cluster instead of per-node locality report that includes the number of locality levels and the number of distinct values at each level. 

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22716#-:-L5LV03gn-8pwUZDgpz7:b-u7jwxc)*

**Comment by BramGruneir** [comment]
We should fix the app name issue as well then.  I propose we should create a per node secret key that we use to hash everything for that cluster.  Then we can irreversibly hash both the app names and the localities (and anything else we're worried about).  

Note that this will require a migration.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22716#-:-L5P4uIj5mwF8RRKKfHI:bqrqrrh)*

**Comment by dt** [comment]
(nit: i assume you meant per-cluster, since we want all the nodes to hash the same locality or app the same)

:thumbsup:

Can probably just use a hidden cluster setting to handle persisting/gossiping/loading said secret, in which case I think you can copy the trace cluster setting migration.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22716#-:-L5P67dHyTFApz_sXnwh:b-ka0muk)*

**Comment by BramGruneir** [comment]
Yes, per cluster!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22716#-:-L5P7rPDZ38C3k15r5t3:b-uvz9sw)*

**Comment by BramGruneir** [comment]
I'm going to rebase this (and fix it) based on #22757.

**Comment by BramGruneir** [comment]
ok, this now uses the now correct version of HashForReporting.

**Comment by BramGruneir** [comment]
Rebased on master and ready to go.  PTAL

**Comment by dt** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22716#-:-L5W4K6irHgrIW-1ZB0c:bnfp4nl)*

**Comment by BramGruneir** [comment]
I'll cherry pick this into 2.0 along with #22822 once that's merged.

**Pull request merged**
