### PR TITLE
storageccl: allocate tmpdir under store's data dir if possible

### LINKED ISSUE #14021: storageccl: tmp files written outside data-dir
Currently our ExportStorage implementations for the various cloud storage providers require writing temp files to disk before uploading them. Right now, those files are allocated using go's `os.TempDir` with no prefix, meaning they use the system tempdir (i.e. /tmp).

Operators already configure nodes with one or more directories to store files in though, and may not expect their data to be written elsewhere -- potentially with different access control, permissions, storage allocation/quotas, io capacity, etc.

A simple heuristic might be to just use the first store's data dir, but eventually we might want to use all of them / whichever has most available space?

### PR DESCRIPTION
**Pull request by dt**
Fixes #14021.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14299)

### CODE REVIEW

**Comment by dt** [comment]
I'm not thrilled about `""` args in sql-land, but this might be better than nothing, so throwing this out there for comments.

**Comment by dt** [comment]
I have a followup which might help with the sql callsites: https://github.com/cockroachdb/cockroach/commit/7d695c6d603c0865d0c4f1b2a0132a7f3f8d6d57

**Comment by danhhz** [comment]
Overall, "" as a sentinel for the os tempdir feels a little magic to me. I'd prefer that the callers currently passing "" instead pass os.TempDir and it becomes an error to pass "". The sql usages could even make a subdir in os.TempDir and clean it up in a defer.

The followup seems nice, but it's a lot of additional code if the deferred cleanup I suggest above will work. But if you're really attached to UnbufferedExportStorage, than let's include it in the PR so I can more easily reason about the whole thing at once

Another possible solution is we replace ExportStorage entirely with UnbufferedExportStorage until we decide to try our hand at streaming

---

Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/engine/rocksdb.go, line 693 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14299#-Kfqafb9kwJ0_9_pqs7N:-Kfqafb9kwJ0_9_pqs7O:b70yl9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/3da156885571b24de272e54d4edebf82be777099/pkg/storage/engine/rocksdb.go#L693)):*
> ```Go
> // GetTempDir wraps ioutil.TempDir to have it alloc in store dir/tmp. In-memory
> // stores will return "".
> func (r *RocksDB) GetTempDir() string {
> ```

I think it's a little more obvious if this returns a *string

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14299#-:-Kfq_k1sZ-1yZPWq-he8:blsyzu8)*

**Comment by dt** [comment]
I like that `UnbufferedExportStorage` draws a line around where we use the `tmpHelper` -- specifically only in the storage code where rocksdb requires local file paths -- which also moves in the direction having `ExportStorage`  be just the network part (ie. what is called `Unbuffered` for now) and a wrapper util could provide the local files on top of it.

**Comment by dt** [comment]
I'm going to withdraw this in favor of a different approach (at least on the *ccl side) that refactors all the tempfile mgmt stuff out of the ExportStorage implementations entirely.

**Pull request closed without merging**
