### PR TITLE
ui: small fixes to the range debug page

### LINKED ISSUE #17909: ui: node claims to have voted for replica 0
image

Not clear where the root cause for this is or what it means.

### PR DESCRIPTION
**Pull request by BramGruneir**
- All debug calls now have a timeout of 10s instead of 30ms.
- Replace a replica's non-vote with a `-` instead of a `0`.
- All Logs used to display the range details table are now wrapped with FixLong for safety.
- The range log table timestamp column is not scaled so the date won't wrap.

Fixes #17909.

### CODE REVIEW

**Comment by BramGruneir** [comment]
cc @tschottdorf

**Comment by mrtracy** [comment]
What on earth are the changes in api.go and timestamp_cache.go?  The UI changes are fine, but I think two commits were somehow merged here improperly

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17931#-:-KsoL8vk5uJ4SYxvIObZ:bdfplig)*

**Comment by BramGruneir** [comment]
I have no bloody idea.  And why does it look like peter pushed to this branch?  I'll clean that up... :(

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17931#-:-KsoMCMdJcyLQtlyXvma:b-yl61k8)*

**Comment by BramGruneir** [comment]
So I'm guessing that I must have somehow mixed my commit with the previous one in a bad rebase.  Should be fixed finally.

**Comment by mrtracy** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17931#-:-KsoYDGgGpLbgJX13g5L:bnfp4nl)*

**Pull request merged**
