### PR TITLE
sql, *: simplify remove dependencies on pgerror, util/log

### PR DESCRIPTION
**Pull request by knz**
These changes are mostly mechanical (I used grep and perl, followed by crlfmt).

This compacts the source code: overall -300 locs, and shorter lines.

### CODE REVIEW

**Comment by andreimatei** [comment]
LGTM to everything but the last commit; I'm happy to see these changes.
What's the benefit of that one - extracting the error codes into their own package?

**Comment by knz** [comment]
>  What's the benefit of that one - extracting the error codes into their own package?

Avoid a cyclic dependency (as usual)

**Comment by knz** [comment]
Also it's more readable: "pgcode.Foo" is shorter than "pgwire.CodeFoo"

**Comment by andreimatei** [comment]
Do you remember what the dependency you were breaking was?

In any case, LGTM

**Pull request merged**
