### PR TITLE
workload: add zipfian distribution option to kv

### PR DESCRIPTION
**Pull request by ridwanmsharif**
Adds a workload distribution that spreads load according
to a Zipfian distribution. This is part of the experimentation
with load based splitting.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31902)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/kv/kv.go, line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31902#-LPlG4Z82MWpqNdP92IP:-LPlG4Z82MWpqNdP92IQ:b-1l6b7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/285922044f7eced66aee5650eb1ac7847ca86ff7/pkg/workload/kv/kv.go#L135)):*
> ```Go
> 			if w.sequential && w.splits > 0 {
> 				return errors.New("'sequential' and 'splits' cannot both be enabled")
> 			}
> ```

Validate against `--sequential` and `--zipfian`.
___
*[pkg/workload/kv/zipfian.go, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31902#-LPlFyDaCtooMkVA-pnZ:-LPlFyDaCtooMkVA-pn_:b-qq2cqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/285922044f7eced66aee5650eb1ac7847ca86ff7/pkg/workload/kv/zipfian.go#L17)):*
> ```Go
> )
> 
> // A Zipf generates Zipf distributed variates.
> ```

Add a comment explaining where this came from and why it was forked.
___
*[pkg/workload/kv/zipfian.go, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31902#-LPlGOvm2QEjIimNf7Qe:-LPlGOvm2QEjIimNf7Qf:b-eocyrb) ([raw file](https://github.com/cockroachdb/cockroach/blob/285922044f7eced66aee5650eb1ac7847ca86ff7/pkg/workload/kv/zipfian.go#L18)):*
> ```Go
> 
> // A Zipf generates Zipf distributed variates.
> type Zipf struct {
> ```

No need to export this type.
___
*[pkg/workload/kv/zipfian.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31902#-LPlGehF1rsz0rzkx4DL:-LPlGehF1rsz0rzkx4DM:bga9bby) ([raw file](https://github.com/cockroachdb/cockroach/blob/285922044f7eced66aee5650eb1ac7847ca86ff7/pkg/workload/kv/zipfian.go#L41)):*
> ```Go
> // such that P(k) is proportional to (v + k) ** (-s).
> // Requirements: s > 1 and v >= 1.
> func NewZipf(s float64, v float64, imax uint64) *Zipf {
> ```

No need to export this either.
___
*[pkg/workload/kv/zipfian.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31902#-LPlFqJLAIvG3Tklumtc:-LPlFqJLAIvG3Tklumtd:b-fhyujt) ([raw file](https://github.com/cockroachdb/cockroach/blob/285922044f7eced66aee5650eb1ac7847ca86ff7/pkg/workload/kv/zipfian.go#L66)):*
> ```Go
> 
> 	for {
> 		r := random.Float64() // r on [0,1]
> ```

`s/r on [0,1]/r in [0.0,1.0)/`
___
*[pkg/workload/kv/zipfian.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31902#-LPlH3qV3-85cLBNf4Kl:-LPlH3qV3-85cLBNf4Km:br3w8hy) ([raw file](https://github.com/cockroachdb/cockroach/blob/285922044f7eced66aee5650eb1ac7847ca86ff7/pkg/workload/kv/zipfian.go#L66)):*
> ```Go
> 
> 	for {
> 		r := random.Float64() // r on [0,1]
> ```

Like we talked about yesterday, this input doesn't need to be random, just deterministic based on the seed and uniformly distributed. We could just as easily hash the sequence number, map the value to a range of `[0.0,1.0)`, and make that the input to this function. 

The effect of this would be mapping the zipf function over the output of `hashGenerator`, so we could/should use that directly in `zipfGenerator`. In fact, `hashGenerator` could use `sequentialGenerator` directly as well.

That would save the cost of a new `rand.Source` and `rand.Rand` on every key. This might not sounds particularly expensive, but when we're pushing 200k qps, I suspect it will add up.

**Review by ridwanmsharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31902)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/kv/kv.go, line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31902#-LPlG4Z82MWpqNdP92IP:-LPsbtsQ1D-oTpd6adKf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/285922044f7eced66aee5650eb1ac7847ca86ff7/pkg/workload/kv/kv.go#L135)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Validate against `--sequential` and `--zipfian`.
</blockquote></details>

Done.
___
*[pkg/workload/kv/zipfian.go, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31902#-LPlFyDaCtooMkVA-pnZ:-LPsbw0A8IN5g_tiDre9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/285922044f7eced66aee5650eb1ac7847ca86ff7/pkg/workload/kv/zipfian.go#L17)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Add a comment explaining where this came from and why it was forked.
</blockquote></details>

Done.
___
*[pkg/workload/kv/zipfian.go, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31902#-LPlGOvm2QEjIimNf7Qe:-LPsbwnbBdRZAsMpTwDf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/285922044f7eced66aee5650eb1ac7847ca86ff7/pkg/workload/kv/zipfian.go#L18)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

No need to export this type.
</blockquote></details>

Done.
___
*[pkg/workload/kv/zipfian.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31902#-LPlGehF1rsz0rzkx4DL:-LPsbxOk3sgM4quO2jkb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/285922044f7eced66aee5650eb1ac7847ca86ff7/pkg/workload/kv/zipfian.go#L41)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

No need to export this either.
</blockquote></details>

Done.
___
*[pkg/workload/kv/zipfian.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31902#-LPlFqJLAIvG3Tklumtc:-LPsby61BlwIqqbda7cT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/285922044f7eced66aee5650eb1ac7847ca86ff7/pkg/workload/kv/zipfian.go#L66)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/r on [0,1]/r in [0.0,1.0)/`
</blockquote></details>

Done.
___
*[pkg/workload/kv/zipfian.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31902#-LPlH3qV3-85cLBNf4Kl:-LPsc0IWAo72UHUreLdX:b-450h48) ([raw file](https://github.com/cockroachdb/cockroach/blob/285922044f7eced66aee5650eb1ac7847ca86ff7/pkg/workload/kv/zipfian.go#L66)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Like we talked about yesterday, this input doesn't need to be random, just deterministic based on the seed and uniformly distributed. We could just as easily hash the sequence number, map the value to a range of `[0.0,1.0)`, and make that the input to this function. 

The effect of this would be mapping the zipf function over the output of `hashGenerator`, so we could/should use that directly in `zipfGenerator`. In fact, `hashGenerator` could use `sequentialGenerator` directly as well.

That would save the cost of a new `rand.Source` and `rand.Rand` on every key. This might not sounds particularly expensive, but when we're pushing 200k qps, I suspect it will add up.
</blockquote></details>

As discussed offline, we're going to keep using `rand` as is for some of the reasons below instead of prematurely optimizing as there's no issue with this as is. 

Looking a little closer into the zipfian calculation logic, I notice that the `rand` object calls `Float64()` in a huge loop. It relies on the ability to create random numbers indefinitely after initiating it with a seed. To keep this property (at least logically) I think we should keep the random number generator instead of a hash function. This is because its trivial to generate the first “random” number for r using the hash but every subsequent one would need to re-hash using the old value and continue that over and over again. Now that may very well be worth it, I’m just afraid of some skew that will cause w.r.t uniformity. But more than that; although a perf benefit may be seen in this specific workload, does it warrant replacing `rand` with our own seeding randomness generator that tries to do the same thing (but uses hash instead of explicitly using rand)? It makes more sense to me to leave this as is because the zipfian distribution works well with this calculation, instead of the extra hashing/rehashing logic that would need to be added here.

Also personal bias: this usage to me just screams like `rand` is the more semantically accurate and simpler answer.

**Comment by m-schneider** [comment]
___
*[pkg/workload/kv/kv.go, line 101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31902#-LQ-Jz4P2u93PVTNnZa_:-LQ-Jz4P2u93PVTNnZaa:b-973gcn) ([raw file](https://github.com/cockroachdb/cockroach/blob/77618f3217066cede766d01c6f84f1a1e06cab6c/pkg/workload/kv/kv.go#L101)):*
> ```Go
> 			`Percent (0-100) of operations that are reads of existing keys.`)
> 		g.flags.Int64Var(&g.seed, `seed`, 1, `Key hash seed.`)
> 		g.flags.BoolVar(&g.zipfian, `zipfian`, false,
> ```

Maybe add a general distribution flag in case we want to add different ones later?

**Pull request merged**
