### PR TITLE
geoindex: add indexing support for DWithin and DFullyWithin

### PR DESCRIPTION
**Pull request by sumeerbhola**
Additionally, fixed 2 bugs in geometry indexing: polygons
were not being reoriented to be CCW before passing to S2,
and using the edges of face 0 (which is the face used by
the bounded plane) was causing the covering to spill outside
the face (this was showing up in existing tests but was
overlooked). Adjusted the TODO for geography indexing:
polygons are not being correctly reoriented to be CCW so can
be interpreted as the whole world minus the shape.

DFullyWithin is not supported for Geography by PostGIS,
so it is omitted here too.

Release note: None

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50605)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/geoindex/index.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50605#-MB-ZbXm01IjEB6R58nO:-MB-ZbXn1v14bv0rSd5l:b-iy3dh4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23e142b21d417f838200428193ce08fadc2ceba/pkg/geo/geoindex/index.go#L88)):*
> ```Go
> 	// DWithin returns the index spans to read and union for the relationship
> 	// ST_DWithin(g, x, distanceMeters). That is, there exists a part of geometry g
> 	// that is within distance units of x, where x is an indexed geometry.
> ```

distance units -> distanceMeters?
___
*[pkg/geo/geoindex/s2_geography_index.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50605#-MB-vfZX8nhQtsnJzqvG:-MB-vfZX8nhQtsnJzqvH:b-nkh7ia) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23e142b21d417f838200428193ce08fadc2ceba/pkg/geo/geoindex/s2_geography_index.go#L106)):*
> ```Go
> 	}
> 	gCovering := covering(i.rc, r)
> 	angle := s1.Angle(distanceMeters / projInfo.Spheroid.SphereRadius)
> ```

It's difficult to understand what's happening here -- maybe some comments would help?
___
*[pkg/geo/geoindex/testdata/s2_geometry, line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50605#-MB-uvW27wurpodj8vVk:-MB-uvW3EBbEv_MVGQGv:b-ishavl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23e142b21d417f838200428193ce08fadc2ceba/pkg/geo/geoindex/testdata/s2_geometry#L281)):*
> ```
> F0/L0/, spilled
> 
> d-fully-within distance=2 name=point1
> ```

Might be worth adding another test where d-within and d-fully-within return different results.

**Comment by otan** [comment]
___
*[pkg/geo/geoindex/s2_geography_index.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50605#-MB-vfZX8nhQtsnJzqvG:-MB0-Rfk3oM3D6GnlpbI:bepok43) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23e142b21d417f838200428193ce08fadc2ceba/pkg/geo/geoindex/s2_geography_index.go#L106)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

It's difficult to understand what's happening here -- maybe some comments would help?
</blockquote></details>

you'll also want to add 10% here in case we're doing dwithin of a spheroid.

**Review by sumeerbhola — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50605#-:-MB1nq_-3WjpjM_-x2Mg:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/geo/geoindex/index.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50605#-MB-ZbXm01IjEB6R58nO:-MB1gYNU6ZIZSCgblP6Z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23e142b21d417f838200428193ce08fadc2ceba/pkg/geo/geoindex/index.go#L88)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

distance units -> distanceMeters?
</blockquote></details>

Done.
___
*[pkg/geo/geoindex/s2_geography_index.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50605#-MB-vfZX8nhQtsnJzqvG:-MB1nB_d2MPXVBScfly0:bkqpxmp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23e142b21d417f838200428193ce08fadc2ceba/pkg/geo/geoindex/s2_geography_index.go#L106)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

you'll also want to add 10% here in case we're doing dwithin of a spheroid.
</blockquote></details>

Added comments and expanded by 1.05 to mirror what is done in `newGeographyMinDistanceUpdater`
___
*[pkg/geo/geoindex/testdata/s2_geometry, line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50605#-MB-uvW27wurpodj8vVk:-MB1iMB_EQ0q2OCd4fb8:b-c3dyk9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23e142b21d417f838200428193ce08fadc2ceba/pkg/geo/geoindex/testdata/s2_geometry#L281)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Might be worth adding another test where d-within and d-fully-within return different results.
</blockquote></details>

They currently have the same implementation so this is unavoidable in the test. I've added a comment

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50605#-:-MB1vu4V0jt2b_0Dpiqw:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by otan** [comment]
___
*[pkg/geo/geoindex/s2_geography_index.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50605#-MB-vfZX8nhQtsnJzqvG:-MB2RNOg2EqSL1WtUWrh:brj46lt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23e142b21d417f838200428193ce08fadc2ceba/pkg/geo/geoindex/s2_geography_index.go#L106)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Added comments and expanded by 1.05 to mirror what is done in `newGeographyMinDistanceUpdater`
</blockquote></details>

We only need to do this if usesSpheroid := true.

**Comment by otan** [comment]
___
*[pkg/geo/geoindex/s2_geography_index.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50605#-MB-vfZX8nhQtsnJzqvG:-MB2RTx_6s3sv9dDU1j7:b-3nwvi7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23e142b21d417f838200428193ce08fadc2ceba/pkg/geo/geoindex/s2_geography_index.go#L106)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

We only need to do this if usesSpheroid := true.
</blockquote></details>

Maybe also drag 1.05 out into a constant shared by this and geogfn?

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50605)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan and @rytaft)

___
*[pkg/geo/geoindex/s2_geography_index.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50605#-MB-vfZX8nhQtsnJzqvG:-MB441tO8HtRh35e0zpi:b-iz2w0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23e142b21d417f838200428193ce08fadc2ceba/pkg/geo/geoindex/s2_geography_index.go#L106)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Maybe also drag 1.05 out into a constant shared by this and geogfn?
</blockquote></details>

Both done.

**Comment by otan** [comment]
___
*[pkg/geo/geoindex/s2_geography_index.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50605#-MB-vfZX8nhQtsnJzqvG:-MB4bSmh-qYD2M13ZgTF:b-b3q1qg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23e142b21d417f838200428193ce08fadc2ceba/pkg/geo/geoindex/s2_geography_index.go#L106)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Both done.
</blockquote></details>

This is a little different though -- the user can force a useSpheroid := true when using `DWithin` to make calculations faster (and filter more results). Is it hard to plumb that argument up to here?

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50605)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan and @rytaft)

___
*[pkg/geo/geoindex/s2_geography_index.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50605#-MB-vfZX8nhQtsnJzqvG:-MB4vxn82oH1C5qLgnb5:b-5734o7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23e142b21d417f838200428193ce08fadc2ceba/pkg/geo/geoindex/s2_geography_index.go#L106)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

This is a little different though -- the user can force a useSpheroid := true when using `DWithin` to make calculations faster (and filter more results). Is it hard to plumb that argument up to here?
</blockquote></details>

Added that parameter.

**Review by otan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50605)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan and @rytaft)

**Pull request merged**
