### PR TITLE
roachtest: exit 10 when tests failed

### PR DESCRIPTION
**Pull request by tbg**
Prior to this commit, `roachtest run` would always exit with code 1 if
it encountered ny problems. In practice, most of the time the reason it
would do that is because one of its tests failed; the exit status in
nightlies is always nonzero.

We want to distinguish that common case from that of roachtest itself
failing to run all of the tests. This commit adds a dedicated exit
status (10) which is used if some tests failed, but roachtest itself
did not encounter any problems.

In follow-up work, we will treat this exit status as a success, which
will allow us to configure notifications for the roachtest nightlies,
so that they can sound the alarm whenever seeing a truly unexpected
exit status (i.e. not zero or ten). For inspiration, see #63825 for
a recent roachtest breakage that this work should alert us to more
proactively in the future once the above plan is carried out.

Test failures continue to be emitted just the same (and issues are
still posted).

Independently roachtest also needs to be hardened against being taken
down by tests. This will require more invasive changes.

Release note: None

### CODE REVIEW

**Review by erikgrinaker — COMMENTED** [review]
> Test failures continue to be emitted just the same (and issues are
still posted).

How are test failures signalled to TeamCity in this case?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63835#-:-MYdQp8pDWw5KoXZKViE:b3v43kk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

**Comment by tbg** [comment]
> How are test failures signalled to TeamCity in this case?

TeamCity has the concept of a failed build and that of a failed test. Usually, we configure each build so that it is marked as failed whenever it observes a test failure, but you can change that. The suggestion is that we change it for the roachtest build. It would thus be "green" (but with test failures) in the common case, and "red" (regardless of test failures) when roachtest crashes.

**Comment by erikgrinaker** [comment]
>TeamCity has the concept of a failed build and that of a failed test. Usually, we configure each build so that it is marked as failed whenever it observes a test failure, but you can change that.

Right, that makes sense, I was just curious about which mechanism we use to signal test failures -- I see TeamCity supports a bunch of them:

https://www.jetbrains.com/help/teamcity/build-failure-conditions.html#Adding+custom+build+metric

**Comment by tbg** [comment]
We currently use the first three. If a build runs too long, exits nonzero, or reports any failures. The suggestion is to drop the last one, so it's only hanging and nonzero-exit builds that would trigger failures.

The actual config is [here](https://teamcity.cockroachdb.com/admin/editBuildFailureConditions.html?id=buildType:Cockroach_Nightlies_WorkloadNightly):

image

**Review by andreimatei — COMMENTED** [review]
It's definitely unusual for a test runner to exit 0 when tests fail. It's not unusual to use different exit codes to mean different things...
How specifically were you going to get some "alerting" from test runner crashes after this patch? By itself, I don't think a green or red mark on the nightly builds in TC will particularly help us; if anything, I prefer the build being red on test failures. I think what we want is, for example, a wrapper to roachtest invocations that pings slack on anything but a particular exit code.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63835#-:-MYfwimW4yDUDfAW5OnN:b2cuiyw)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by tbg — COMMENTED** [review]
> How specifically were you going to get some "alerting" from test runner crashes after this patch? 

See here:

> and we can set up email notifications that fire in such a case.

There are many ways to skin the cat but this seems like a reasonable one.

> I prefer the build being red

Not to invalidate your preference, but you would need to provide arguments for why it should be done one way or another. The tests will still be tracked as failing and it does make sense to decouple the test status from the build status in this case, which TeamCity natively allows us to do. I would like to avoid introducing additional moving parts such as slack notifications at this point in the interest of pragmatism. Using exit codes is possible too but it doesn't add anything; we would then have to teach TeamCity to *not* notify on certain exit codes, which seems like a pointless diversion.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63835#-:-MYi5DsZCW7NjTLJFg9f:b-xff1jd)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
> Not to invalidate your preference, but you would need to provide arguments for why it should be done one way or another.

Well but it's the other way around :). You want to change something; it's on you to argue for it.
A zero exit code with failed tests is too weird I think. It'd be surprising to everybody who wants to script roachtest. Even in TC, we already use roachtest in multiple builds with different needs - for example there's the roachtest invocation in Github CI. It's backwards to pass a flag to roachtest to modify the exit code contract. Seems much natural for roachtest to provide a clear contract through its exit codes that satisfies everybody. It wouldn't be hard for the email-sending script to ignore a particular "tests failed" exit code.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63835#-:-MYj_NX69ePqvQ4S9-f5:bytqqfb)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by tbg** [comment]
> Well but it's the other way around :). You want to change something; it's on you to argue for it.

That's right, but if I'm arguing for it and your reponse is "but I don't like it", that is not a convincing response. `roachtest` in itself is a weird setup. It is really a test orchestrator and runs a number of jobs that in a proper world would be individual TeamCity builds. For various reasons, we cannot do this (eng bandwidth and the fact that we want to share clusters between the build being the two large ones) and so we will necessarily have to do something that will look odd.

>  It wouldn't be hard for the email-sending script to ignore a particular "tests failed" exit code.

The goal is to not have a random "email sending" script that would then have to be maintained, and will probably fail silently at some point. The goal is to do everything with TeamCity built-ins. I see the merit in the exit-code idea and agree that it's cleaner than a flag at the `roachtest` level. But TeamCity doesn't actually consider this standard practice as far as its built-in tools are concerned - it does not have a way "notify folks if the exit code is anything but 0 and 12". We can still get there, but not in the way you prefer - I will teach the bash script wrapping roachtest to ignore the special exit code and to exit zero in that case, and we set up TeamCity to email someone whenever the build is red. I continue to consider that fine given the "orchestrator" role of `roachtest` itself, and in light of this enabling us to detect actual test failures. I also happen to know that @rachitgsrivastava, who is building an ETL pipeline for TC stats, is operating at the level of tests, so this isn't going to make things look more successful there than they are.

For reference, here's the documentation about these notifications (email and slack are supported): https://www.jetbrains.com/help/teamcity/subscribing-to-notifications.html#Which+Events+Will+Trigger+Notifications

**Comment by tbg** [comment]
Updated, PTAL.

**Review by erikgrinaker — APPROVED** [review]
LGTM, but maybe let @andreimatei respond to your comments above.

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> We can still get there, but not in the way you prefer - I will teach the bash script wrapping roachtest to ignore the special exit code and to exit zero in that case, and we set up TeamCity to email someone whenever the build is red

What you've done here is fine. I only care about `roachtest` not returning 0.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63835#-:-M_ufXKC90aK3TBgbX4h:b-m2i348)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[build/teamcity-nightly-roachtest-invoke.sh, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63835#-M_uf8J85FgkLDU3fSuW:-M_uf8J85FgkLDU3fSuX:b-srdy0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bb1619ae40133173a70dcb6d4060d3f1ef4253e/build/teamcity-nightly-roachtest-invoke.sh#L29)):*
> ```Shell
> # build. That way, build failures can be used to notify about serious
> # problems that prevent tests from being invoked in the first place.
> [[ ${code} -eq 0 || ${code} -eq 10 ]]
> ```

please make this more explicit - add an `exit 0` in an `if`. Took me a second otherwise.
___
*[pkg/cmd/roachtest/main.go, line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63835#-M_ueqLC24lLMr73AE_S:-M_ueqLC24lLMr73AE_T:b-aj4tv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8f119d3b88cf8b025113b3d1371ae93831a5ad6/pkg/cmd/roachtest/main.go#L252)):*
> ```Go
> }
> 
> type exitCoder interface {
> ```

please comment. But this interface seems unnecessary; I'd rename `exitCodeErr` to `testFailedErr` and recognize it here without any interfaces.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63835)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei)

___
*[build/teamcity-nightly-roachtest-invoke.sh, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63835#-M_uf8J85FgkLDU3fSuW:-M_uxUVc3pHkBZSjH9zv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bb1619ae40133173a70dcb6d4060d3f1ef4253e/build/teamcity-nightly-roachtest-invoke.sh#L29)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please make this more explicit - add an `exit 0` in an `if`. Took me a second otherwise.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/main.go, line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63835#-M_ueqLC24lLMr73AE_S:-M_uyBtm5HeUoBs-ysDp:b-xar2my) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8f119d3b88cf8b025113b3d1371ae93831a5ad6/pkg/cmd/roachtest/main.go#L252)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please comment. But this interface seems unnecessary; I'd rename `exitCodeErr` to `testFailedErr` and recognize it here without any interfaces.
</blockquote></details>

Done, much simpler.

**Comment by tbg** [comment]
bors r=andreimatei

**Pull request merged**
