### PR TITLE
cdcevent: simplify code for virtual column processing

### PR DESCRIPTION
**Pull request by andyyang890**
Epic: None

Release note: None

### CODE REVIEW

**Review by rharding6373 — COMMENTED** [review]
There are a couple things I don't understand in this refactor, so I have a couple questions to help me understand better. I'll take another look at it later.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118986#-:-NqDhskR7uOH6b9Nq98p:b-2suyed)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andyyang890 and @jayshrivastava)

___
*[`pkg/ccl/changefeedccl/cdcevent/event.go` line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118986#-NqDe2hq9q6VUY-1lF0Y:-NqDe2hq9q6VUY-1lF0Z:bzfaf08) ([raw file](https://github.com/cockroachdb/cockroach/blob/36249fccf5c443b26bfe3b31d7e1adf84afd3978/pkg/ccl/changefeedccl/cdcevent/event.go#L175)):*
> ```Go
> 			}
> 		case col.ord < len(r.datums):
> 			encDatum := r.datums[col.ord]
> ```

This doesn't seem like it has the same behavior as the old code. In the old code, it's expected that r.datums will only have the non-virtual data, so the data placement in r.datums is different than the column ordinal. In the new code, we assume that the data offset will be the same as the column ordinal. 
___
*[`pkg/ccl/changefeedccl/cdcevent/event.go` line 319 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118986#-NqDgfSLAu3dTeAyZW0R:-NqDgfSLAu3dTeAyZW0S:bam9lk1) ([raw file](https://github.com/cockroachdb/cockroach/blob/36249fccf5c443b26bfe3b31d7e1adf84afd3978/pkg/ccl/changefeedccl/cdcevent/event.go#L319)):*
> ```Go
> 			if isVirtual := col.IsVirtual(); isVirtual && includeVirtualColumns {
> 				colIdx := addColumn(col, virtualColOrd)
> 				sd.valueCols = append(sd.valueCols, colIdx)
> ```

Why don't we need an ord++ here anymore?

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118986)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava and @rharding6373)

___
*[`pkg/ccl/changefeedccl/cdcevent/event.go` line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118986#-NqDe2hq9q6VUY-1lF0Y:-NqE-_Gk5T7aL-RaHUz1:baucrw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/36249fccf5c443b26bfe3b31d7e1adf84afd3978/pkg/ccl/changefeedccl/cdcevent/event.go#L175)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

This doesn't seem like it has the same behavior as the old code. In the old code, it's expected that r.datums will only have the non-virtual data, so the data placement in r.datums is different than the column ordinal. In the new code, we assume that the data offset will be the same as the column ordinal.
</blockquote></details>

Yeah, I changed it so that the ordinal will match the datum position to begin with. I found the previous logic of offsetting with a `numVirtualCols` counter confusing and unnecessary.
___
*[`pkg/ccl/changefeedccl/cdcevent/event.go` line 319 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118986#-NqDgfSLAu3dTeAyZW0R:-NqE-QlxBCr1ZneSCVy5:bt7cfay) ([raw file](https://github.com/cockroachdb/cockroach/blob/36249fccf5c443b26bfe3b31d7e1adf84afd3978/pkg/ccl/changefeedccl/cdcevent/event.go#L319)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Why don't we need an ord++ here anymore?
</blockquote></details>

As mentioned above, I changed it so the position of non-virtual columns doesn't require any of the current finnicky offsetting logic in `forEachDatum`.

**Review by rharding6373 — APPROVED** [review]
:lgtm: Thanks for explaining! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118986#-:-NqYPD9J4042HvGVpFFu:b9aqvah)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jayshrivastava)

___
*[`pkg/ccl/changefeedccl/cdcevent/event.go` line 319 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118986#-NqDgfSLAu3dTeAyZW0R:-NqYP4x4BNmfHwyqVg1X:b-1cqqq) ([raw file](https://github.com/cockroachdb/cockroach/blob/36249fccf5c443b26bfe3b31d7e1adf84afd3978/pkg/ccl/changefeedccl/cdcevent/event.go#L319)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

As mentioned above, I changed it so the position of non-virtual columns doesn't require any of the current finnicky offsetting logic in `forEachDatum`.
</blockquote></details>

Ah, ok. Clever. Thanks for the explanations.

**Comment by andyyang890** [comment]
TFTR!

bors r=rharding6373

**Pull request merged**
