### PR TITLE
storage: decode synthetic suffix correctly for block property filtering

### PR DESCRIPTION
**Pull request by msbutler**
Previously, AdjustIntervalWithSyntheticSuffix would incorrectly decode the
syntheticSuffix with Uvarint decoding over the whole byte slice, even though
the suffix was encoded using EncodeMVCCTimestamp which encodes both the wall
time and logical time.

Our current tests likely didn't catch this bug because they don't run any
queries that exercise time bound iteration in pebble (like an AOST query). This
patch adds a fingerprint check to TestOnlineRestoreBasic which does run TBI on
pebble.

Epic: none

Release note: none

### CODE REVIEW

**Comment by msbutler** [comment]
only latest commit is relevant.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119964#-:-NsKjwth3F9J2sJVa9Sl:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt and @msbutler)

___
*[`pkg/storage/pebble.go` line 519 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119964#-NsKjllMEUi5tpcvg_Es:-NsKjllMEUi5tpcvg_Et:bkrwx77) ([raw file](https://github.com/cockroachdb/cockroach/blob/678e8ddaa74caf08d843be16678d2df0cff3b567/pkg/storage/pebble.go#L519)):*
> ```Go
> 		return 0, 0, errors.AssertionFailedf("the synthetic suffix %d is less than or equal to the original upper bound %d", synthDecoded, upper)
> 	}
> 	return synthDecodedWalltime, synthDecodedWalltime + 1, nil
> ```

[nit] maybe say that "[synthDecodedWalltime, synthDecodedWaltime+1)` includes the synthetic suffix, regardless of its logical component.
___
*[`pkg/storage/pebble.go` line 646 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119964#-NsKisAEEMaz0KaS46Mi:-NsKisAEEMaz0KaS46Mj:b6kqxmo) ([raw file](https://github.com/cockroachdb/cockroach/blob/678e8ddaa74caf08d843be16678d2df0cff3b567/pkg/storage/pebble.go#L646)):*
> ```Go
> 	// The actual value encoded into walltime is an int64, so +1 will not
> 	// overflow.
> 	upper = decodeWallTime(tc.max) + 1
> ```

[nit] maybe add to this comment, something like
"Note that the timestamp with wall time tc.max+1 and no logical component is a valid exclusive upper bound for timestamps with wall time tc.max and any logical component".

**Review by msbutler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119964)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt)

___
*[`pkg/storage/pebble.go` line 519 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119964#-NsKjllMEUi5tpcvg_Es:-NsKm-WM9ss_Rdy2_K2D:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/678e8ddaa74caf08d843be16678d2df0cff3b567/pkg/storage/pebble.go#L519)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] maybe say that "[synthDecodedWalltime, synthDecodedWaltime+1)` includes the synthetic suffix, regardless of its logical component.
</blockquote></details>

Done.
___
*[`pkg/storage/pebble.go` line 646 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119964#-NsKisAEEMaz0KaS46Mi:-NsKlzJo88TYe0e8f3x3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/678e8ddaa74caf08d843be16678d2df0cff3b567/pkg/storage/pebble.go#L646)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] maybe add to this comment, something like
"Note that the timestamp with wall time tc.max+1 and no logical component is a valid exclusive upper bound for timestamps with wall time tc.max and any logical component".
</blockquote></details>

Done.

**Comment by msbutler** [comment]
TFTR!

bors r=raduberinde

**Pull request merged**
