### PR TITLE
colexec: implement function concat_agg for vectorized engine

### PR DESCRIPTION
**Pull request by yongyanglai**
This PR contains implementation of vectorized aggregate function "concat_agg".
Related: #43561

Release note (sql change): vectorized engine now support aggregate function "concat_agg"

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Thanks for taking this on! It's in a very good shape already, but I left some suggestions on how to simplify the code a bit.

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-:-MBklH1Z73BoNQIQWaU0:b-btnz7z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yongyanglai)

___
*[pkg/sql/colexec/concat_agg_tmpl.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-MBjYfcWEZgc2fiY4OH1:-MBjYfcWEZgc2fiY4OH2:b-cxw5x3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d483b56144021acfc3a4bd6461db8bef6967ff59/pkg/sql/colexec/concat_agg_tmpl.go#L32)):*
> ```Go
> 
> // {{/*
> // Declarations to make the template compile properly
> ```

nit: missing periods here and in several places below.
___
*[pkg/sql/colexec/concat_agg_tmpl.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-MBjbo-c9Gq4g_68q40w:-MBjbo-c9Gq4g_68q40x:bdde51g) ([raw file](https://github.com/cockroachdb/cockroach/blob/d483b56144021acfc3a4bd6461db8bef6967ff59/pkg/sql/colexec/concat_agg_tmpl.go#L50)):*
> ```Go
> // {{range .}}
> 
> func (a *concat_TYPE_AGGKINDAgg) Init(groups []bool, vec coldata.Vec) {
> ```

I think we don't need to do templating on `_TYPE` - we know that `concat_agg` works only on `tree.DBytes` and `tree.DString`, and both types have the same physical representation, `coldata.Bytes`, so I think it is safe to hard-code that we're operating on `Bytes` vectors and `_TYPE` entirely.
___
*[pkg/sql/colexec/concat_agg_tmpl.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-MBjcE2cBULqIgDTkCSd:-MBjcE2cBULqIgDTkCSe:br7ngdt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d483b56144021acfc3a4bd6461db8bef6967ff59/pkg/sql/colexec/concat_agg_tmpl.go#L82)):*
> ```Go
> 		[]coldata.Vec{a.vec},
> 		func() {
> 			previousAggValMemoryUsage := _AGG_VAL_MEMORY_USAGE(a.curAgg)
> ```

I think we need to do less explicit memory accounting here. The reason is that when `execgen.SET` templated function call is within `PerformOperation`, then we're already measuring the updated memory usage automatically. What I mean is that `a.alloc.allocator.PerformOperation` itself will measure the memory footprint of `a.vec` before and after the operation is applied, so there is no need to do anything explicitly (in fact, what we have right now is double counting the memory usage).

As a result, I don't think we need this `_AGG_VAL_MEMORY_USAGE` function at all.
___
*[pkg/sql/colexec/concat_agg_tmpl.go, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-MBkfQjk7IZyuHc4maOp:-MBkfQjl9PG9KO9h06pY:b-z59jh1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d483b56144021acfc3a4bd6461db8bef6967ff59/pkg/sql/colexec/concat_agg_tmpl.go#L121)):*
> ```Go
> 			}
> 			a.alloc.allocator.AdjustMemoryUsage(-(_AGG_VAL_MEMORY_USAGE(a.curAgg)))
> 			a.curAgg = zero_RET_TYPEValue
> ```

nit: no need to zero out since `Flush` is called once the computation has been completed.
___
*[pkg/sql/colexec/concat_agg_tmpl.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-MBkhlmA2KCSrh3c7mpn:-MBkhlmA2KCSrh3c7mpo:bygt5qb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d483b56144021acfc3a4bd6461db8bef6967ff59/pkg/sql/colexec/concat_agg_tmpl.go#L183)):*
> ```Go
> // {{/*
> func _ACCUMULATE_CONCAT(
> 	a *sum_SUMKIND_TYPE_AGGKINDAgg, nulls *coldata.Nulls, i int, _HAS_NULLS bool,
> ```

nit: `s/sum_SUMKIND_TYPE_AGGKINDAgg/concat_TYPE_AGGKINDAgg/`.
___
*[pkg/sql/colexec/overloads_test_utils.eg.go, line 3303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-MBkl-au5SUCPhOK229q:-MBkl-au5SUCPhOK229r:bu5wihf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d483b56144021acfc3a4bd6461db8bef6967ff59/pkg/sql/colexec/overloads_test_utils.eg.go#L3303)):*
> ```Go
> 	// to go around "unused" error.
> 	_ = _overloadHelper
> ```

Our linter is complaining about this function that "r value is never used". Try this diff
```
diff --git a/pkg/sql/colexec/execgen/cmd/execgen/overloads_test_utils_gen.go b/pkg/sql/colexec/execgen/cmd/execgen/overloads_test_utils_gen.go
index 38c81e2dcc..2f0e030819 100644
--- a/pkg/sql/colexec/execgen/cmd/execgen/overloads_test_utils_gen.go
+++ b/pkg/sql/colexec/execgen/cmd/execgen/overloads_test_utils_gen.go
@@ -39,6 +39,7 @@ import (
 //     these utility test methods for datum-backed types.
 // */}}
 {{if and (not (eq .Left.VecMethod "Datum")) (not (eq .Right.VecMethod "Datum"))}}
+{{if and (not (eq .Left.VecMethod "Bytes")) (not (eq .Right.VecMethod "Bytes"))}}
 
 func {{template "opName" .}}(a {{.Left.GoType}}, b {{.Right.GoType}}) {{.Right.RetGoType}} {
        var r {{.Right.RetGoType}}
@@ -52,6 +53,7 @@ func {{template "opName" .}}(a {{.Left.GoType}}, b {{.Right.GoType}}) {{.Right.R
        return r
 }
 
+{{end}}
 {{end}}
 {{end}}
 `
```
so that we don't generate any "perform" methods on bytes types (since those are not used, and I'll be removing this file shortly anyway).
___
*[pkg/sql/colexec/execgen/cmd/execgen/concat_agg_gen.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-MBjXRaF2F8UoBA86IGV:-MBjXRaG3fpsOdgOjcDz:b-yelmx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d483b56144021acfc3a4bd6461db8bef6967ff59/pkg/sql/colexec/execgen/cmd/execgen/concat_agg_gen.go#L1)):*
> ```Go
> // Copyright 2018 The Cockroach Authors.
> ```

nit: `s/2018/2020/`.
___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go, line 265 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-MBkj8d49WHFFuX-HwLr:-MBkj8d49WHFFuX-HwLs:bn8sivd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d483b56144021acfc3a4bd6461db8bef6967ff59/pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go#L265)):*
> ```Go
> 			caller, idx, err := parseNonIndexableTargetElem(targetElem)
> 			var setStatement string
> 			if err != nil && idx == "-1" {
> ```

I think there is no need for "-1" index because we always set to it to -1 when `err` is non-nil, or am I missing something?
___
*[pkg/sql/logictest/testdata/logic_test/vectorize_agg, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-MBjZaofBJGaCAZIF2c4:-MBjZaofBJGaCAZIF2c5:bup1jdg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d483b56144021acfc3a4bd6461db8bef6967ff59/pkg/sql/logictest/testdata/logic_test/vectorize_agg#L36)):*
> ```
> 
> query TT
> SELECT concat_agg(_bytes), concat_agg(_string) FROM bytes_string
> ```

It would be nice to also run `EXPLAIN (VEC)` on these SELECT queries to make sure that the vectorized engine is used.

**Review by yongyanglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51148)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/concat_agg_tmpl.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-MBjYfcWEZgc2fiY4OH1:-MBn7MLj8hwBAQ259iQt:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d483b56144021acfc3a4bd6461db8bef6967ff59/pkg/sql/colexec/concat_agg_tmpl.go#L32)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: missing periods here and in several places below.
</blockquote></details>

Done
___
*[pkg/sql/colexec/concat_agg_tmpl.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-MBjbo-c9Gq4g_68q40w:-MBn7O3BDhCjTLtzV0z7:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d483b56144021acfc3a4bd6461db8bef6967ff59/pkg/sql/colexec/concat_agg_tmpl.go#L50)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think we don't need to do templating on `_TYPE` - we know that `concat_agg` works only on `tree.DBytes` and `tree.DString`, and both types have the same physical representation, `coldata.Bytes`, so I think it is safe to hard-code that we're operating on `Bytes` vectors and `_TYPE` entirely.
</blockquote></details>

Done
___
*[pkg/sql/colexec/concat_agg_tmpl.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-MBjcE2cBULqIgDTkCSd:-MBn7Q8nDjk4hZ_jCQRD:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d483b56144021acfc3a4bd6461db8bef6967ff59/pkg/sql/colexec/concat_agg_tmpl.go#L82)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think we need to do less explicit memory accounting here. The reason is that when `execgen.SET` templated function call is within `PerformOperation`, then we're already measuring the updated memory usage automatically. What I mean is that `a.alloc.allocator.PerformOperation` itself will measure the memory footprint of `a.vec` before and after the operation is applied, so there is no need to do anything explicitly (in fact, what we have right now is double counting the memory usage).

As a result, I don't think we need this `_AGG_VAL_MEMORY_USAGE` function at all.
</blockquote></details>

Done
___
*[pkg/sql/colexec/concat_agg_tmpl.go, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-MBkfQjk7IZyuHc4maOp:-MBn7Tce0d3kHxCxGPN1:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d483b56144021acfc3a4bd6461db8bef6967ff59/pkg/sql/colexec/concat_agg_tmpl.go#L121)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: no need to zero out since `Flush` is called once the computation has been completed.
</blockquote></details>

Done
___
*[pkg/sql/colexec/concat_agg_tmpl.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-MBkhlmA2KCSrh3c7mpn:-MBn7XcY8thPwmcm21BV:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d483b56144021acfc3a4bd6461db8bef6967ff59/pkg/sql/colexec/concat_agg_tmpl.go#L183)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: `s/sum_SUMKIND_TYPE_AGGKINDAgg/concat_TYPE_AGGKINDAgg/`.
</blockquote></details>

Done
___
*[pkg/sql/colexec/overloads_test_utils.eg.go, line 3303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-MBkl-au5SUCPhOK229q:-MBn7_6LBGT5_k5ybOeJ:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d483b56144021acfc3a4bd6461db8bef6967ff59/pkg/sql/colexec/overloads_test_utils.eg.go#L3303)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Our linter is complaining about this function that "r value is never used". Try this diff
```
diff --git a/pkg/sql/colexec/execgen/cmd/execgen/overloads_test_utils_gen.go b/pkg/sql/colexec/execgen/cmd/execgen/overloads_test_utils_gen.go
index 38c81e2dcc..2f0e030819 100644
--- a/pkg/sql/colexec/execgen/cmd/execgen/overloads_test_utils_gen.go
+++ b/pkg/sql/colexec/execgen/cmd/execgen/overloads_test_utils_gen.go
@@ -39,6 +39,7 @@ import (
 //     these utility test methods for datum-backed types.
 // */}}
 {{if and (not (eq .Left.VecMethod "Datum")) (not (eq .Right.VecMethod "Datum"))}}
+{{if and (not (eq .Left.VecMethod "Bytes")) (not (eq .Right.VecMethod "Bytes"))}}
 
 func {{template "opName" .}}(a {{.Left.GoType}}, b {{.Right.GoType}}) {{.Right.RetGoType}} {
        var r {{.Right.RetGoType}}
@@ -52,6 +53,7 @@ func {{template "opName" .}}(a {{.Left.GoType}}, b {{.Right.GoType}}) {{.Right.R
        return r
 }
 
+{{end}}
 {{end}}
 {{end}}
 `
```
so that we don't generate any "perform" methods on bytes types (since those are not used, and I'll be removing this file shortly anyway).
</blockquote></details>

Done
___
*[pkg/sql/colexec/execgen/cmd/execgen/concat_agg_gen.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-MBjXRaF2F8UoBA86IGV:-MBn7eCCB2ljoNKQUkYs:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d483b56144021acfc3a4bd6461db8bef6967ff59/pkg/sql/colexec/execgen/cmd/execgen/concat_agg_gen.go#L1)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: `s/2018/2020/`.
</blockquote></details>

Done
___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go, line 265 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-MBkj8d49WHFFuX-HwLr:-MBn7hGn8fjUHyqAL8qV:bks4p0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/d483b56144021acfc3a4bd6461db8bef6967ff59/pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go#L265)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think there is no need for "-1" index because we always set to it to -1 when `err` is non-nil, or am I missing something?
</blockquote></details>

Done
This change has been removed since hard coded template doesn't need it
___
*[pkg/sql/logictest/testdata/logic_test/vectorize_agg, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-MBjZaofBJGaCAZIF2c4:-MBn83XA7lkC-YthlhVG:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d483b56144021acfc3a4bd6461db8bef6967ff59/pkg/sql/logictest/testdata/logic_test/vectorize_agg#L36)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

It would be nice to also run `EXPLAIN (VEC)` on these SELECT queries to make sure that the vectorized engine is used.
</blockquote></details>

Done

**Comment by yongyanglai** [comment]
Thanks for reviews! The template is hard coded now.
PTAL

**Review by yuzefovich — APPROVED** [review]
Thanks! :lgtm:

> Reviewed 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-:-MBoNoiM62iuqy7eImvY:b-ftzx47)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yongyanglai)

___
*[pkg/sql/colexec/concat_agg_tmpl.go, line 135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-MBoMNlkCVDmHHOSpHH8:-MBoMNll8dwWfZD4kAz-:b-vgncui) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc3c60da6694be478cf4bd1a49bbe5f69847c7dc/pkg/sql/colexec/concat_agg_tmpl.go#L135)):*
> ```Go
> 	// memory usage of curAgg varies during aggregation, we
> 	// need the allocator to monitor this change.
> 	alloc *concat_AGGKINDAggAlloc
> ```

nit: rather than using `*concat_AGGKINDAggAlloc` to get access to the allocator we should use `*colmem.Allocator` object directly.

**Review by yongyanglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51148)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[pkg/sql/colexec/concat_agg_tmpl.go, line 135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-MBoMNlkCVDmHHOSpHH8:-MBt2Bzg4sZ-40vWEa1G:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc3c60da6694be478cf4bd1a49bbe5f69847c7dc/pkg/sql/colexec/concat_agg_tmpl.go#L135)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: rather than using `*concat_AGGKINDAggAlloc` to get access to the allocator we should use `*colmem.Allocator` object directly.
</blockquote></details>

Done



PTAL

**Comment by yongyanglai** [comment]
I have a question here. If there is possibility that aggregator run out of memory before allocator notice it. For example:
```sql
SELECT concat_agg(_string_col) FROM some_table
```
Seems that aggregate function won't flush aggregate value to output vector before it aggregate all values of `string_col` in table. If `some_table` is large enough, db server may exhaust memory but allocator doesn't see this memory usage.

**Review by yuzefovich — COMMENTED** [review]
Yes, there is such a possibility, and initially I thought it was ok for the value of `curAgg` be unaccounted for until the aggregation group is finished, but maybe it's unacceptable, let's see what my teammates think. cc @asubiotto @jordanlewis 

An alternative would be to do what you proposed initially - adjusting memory account of the allocator after every `a.curAgg = append(a.curAgg, col.Get(i)...)`, however, this will have a performance overhead.

How about this idea: the case that we want to be protected from is when thousands of values belong to the same aggregation group because in that case `a.curAgg` can grow arbitrarily large until it is "flushed". We could add a protection on per-batch granularity - we could get the length of `curAgg` before the loops of `_ACCUMULATE_CONCAT` in `Compute` and after the loops, and then we will adjust the memory account by the difference `after - before` (we will also need to reduce the account by `len(a.curAgg)` in `Flush` method). This way the performance hit will be negligible yet we're accounting for `a.curAgg` between different `coldata.Batch`es. Batch size is 1024, so at most we will have `1024 x avg string elem` bytes unaccounted for temporarily, and given that CockroachDB doesn't work well with large in size values (say 1MB), then we won't account - temporarily - for at most 1GB of RAM which seems acceptable to me.

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-:-MBtEZ9A2tR3zw9LRE5P:ba04z64)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51148)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yongyanglai)

___
*[pkg/sql/colexec/concat_agg_tmpl.go, line 132 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-MBtIdxD6S0eHsGO5PzQ:-MBtIdxD6S0eHsGO5PzR:by0o8a1) ([raw file](https://github.com/cockroachdb/cockroach/blob/22c4d9b0a25bfc3f820a62d63c6cb48aea46096e/pkg/sql/colexec/concat_agg_tmpl.go#L132)):*
> ```Go
> 
> type concat_AGGKINDAgg struct {
> 	// alloc is the alloc used to create this aggregateFunc
> ```

nit: the comment needs minor adjustment.

**Review by yongyanglai — COMMENTED** [review]
CI build failed. I didn't find meaningful logs in teamcity and diff shows only changes in code comments.
I ran `make test` on my linux computer, but there was seems no problem.
Should I trigger another run in teamcity?
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51148)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[pkg/sql/colexec/concat_agg_tmpl.go, line 132 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-MBtIdxD6S0eHsGO5PzQ:-MByZE5L3vcJ9DL3Timh:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/22c4d9b0a25bfc3f820a62d63c6cb48aea46096e/pkg/sql/colexec/concat_agg_tmpl.go#L132)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: the comment needs minor adjustment.
</blockquote></details>

Done

**Comment by yongyanglai** [comment]
> Yes, there is such a possibility, and initially I thought it was ok for the value of `curAgg` be unaccounted for until the aggregation group is finished, but maybe it's unacceptable, let's see what my teammates think. cc @asubiotto @jordanlewis
> 
> An alternative would be to do what you proposed initially - adjusting memory account of the allocator after every `a.curAgg = append(a.curAgg, col.Get(i)...)`, however, this will have a performance overhead.
> 
> How about this idea: the case that we want to be protected from is when thousands of values belong to the same aggregation group because in that case `a.curAgg` can grow arbitrarily large until it is "flushed". We could add a protection on per-batch granularity - we could get the length of `curAgg` before the loops of `_ACCUMULATE_CONCAT` in `Compute` and after the loops, and then we will adjust the memory account by the difference `after - before` (we will also need to reduce the account by `len(a.curAgg)` in `Flush` method). This way the performance hit will be negligible yet we're accounting for `a.curAgg` between different `coldata.Batch`es. Batch size is 1024, so at most we will have `1024 x avg string elem` bytes unaccounted for temporarily, and given that CockroachDB doesn't work well with large in size values (say 1MB), then we won't account - temporarily - for at most 1GB of RAM which seems acceptable to me.
> 
> > Reviewed 3 of 3 files at r3.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-:-MBtEZ9A2tR3zw9LRE5P:ba04z64)_ status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

I think it's a reasonable solution and I can't figure out a more efficient method to do so.
If you think it's necessary to monitor `a.curAgg` I will make changes to this PR then.

**Review by yuzefovich — COMMENTED** [review]
Oh, I just took look at your initial version with memory accounting, and that was basically what I outlined above. Yeah, I think we should bring it back, and you were right from the very start, my bad from steering you into wrong direction. The nice thing is that the code will now be simplified because we're hard-coding the usage on `Bytes` vector. I'll wait for you to update the PR accordingly.

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-:-MC-71Vb5EZZ9FEP_Uc1:b7xrjye)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by yongyanglai — COMMENTED** [review]
I have updated PR accordingly
PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-:-MC2CNbz7KeAZluOjDPr:bmn7z6v)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

**Review by yuzefovich — APPROVED** [review]
Awesome, thanks for your contribution!

bors r=yuzefovich

> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51148#-:-MC3KR1z9Lgy3UK1JR8v:b6kxlfp)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by yuzefovich** [comment]
Seems like bors crashed.

bors r=yuzefovich

**Pull request merged**
