### PR TITLE
kvserver: add debug pages for the side transport

### PR DESCRIPTION
**Pull request by andreimatei**
/debug/closedts-{sender,receiver} expose the state of the sender and
receiver - all the tracked ranges, the closed timestamps, the state of
connections to other nodes.

Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
Sender looks like:
Screenshot from 2021-03-12 18-39-45

And receiver:
Screenshot from 2021-03-12 18-40-32

**Review by nvb — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61963)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @andreimatei)

___
*[pkg/kv/kvserver/replica_closedts.go, line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-MWV7PXuAeA6nWSuIBal:-MWV7PXuAeA6nWSuIBam:b-lyu1s7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0951f28dbb5172d622162641fb7caff8a7513eb8/pkg/kv/kvserver/replica_closedts.go#L87)):*
> ```Go
> 	defer r.mu.Unlock()
> 	desc := r.descRLocked()
> 	res.Desc = desc
> ```

`res.Desc = r.descRLocked()`
___
*[pkg/kv/kvserver/closedts/ctpb/service.go, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-MWVH-WV86HqWaCKPC9Y:-MWVH-WW2fWViIGV1vlR:b-nhgqyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0da89a2bc84b27fed201951cf694c65703e4bb4/pkg/kv/kvserver/closedts/ctpb/service.go#L45)):*
> ```Go
> 		fmt.Fprintf(sb, "%s:%s (%s)", upd.Policy, upd.ClosedTimestamp, agoMsg)
> 	}
> 	sb.WriteRune('\n')
> ```

nit: new line after this.
___
*[pkg/kv/kvserver/closedts/sidetransport/receiver.go, line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-MWVHSiB-zdggGGMJHhY:-MWVHSiC5X59DC-ump0t:b-mu8dp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0da89a2bc84b27fed201951cf694c65703e4bb4/pkg/kv/kvserver/closedts/sidetransport/receiver.go#L138)):*
> ```Go
> // onRecvErr is called when one of the inbound streams errors out. The stream is
> // removed from the Receiver's collection.
> func (s *Receiver) onRecvErr(ctx context.Context, r *incomingStream, err error) {
> ```

Was this needed?
___
*[pkg/kv/kvserver/closedts/sidetransport/receiver.go, line 363 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-MWVI-Z0D8McWGnnQlRy:-MWVI-Z0D8McWGnnQlRz:b3erccp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0da89a2bc84b27fed201951cf694c65703e4bb4/pkg/kv/kvserver/closedts/sidetransport/receiver.go#L363)):*
> ```Go
> 			sb.WriteString(s + ":\n")
> 		} else {
> 			fmt.Fprintf(sb, "<h4>%s</h4>", s)
> ```

Is this the canonical way to generate HTML from Go? It all seems a little janky. Did you consider the use of `html/template` like we use in `writeToHTML`?
___
*[pkg/kv/kvserver/closedts/sidetransport/receiver.go, line 363 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-MWVIGoQ59qIF_btaaxh:-MWVIGoQ59qIF_btaaxi:bw2p71i) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0da89a2bc84b27fed201951cf694c65703e4bb4/pkg/kv/kvserver/closedts/sidetransport/receiver.go#L363)):*
> ```Go
> 			sb.WriteString(s + ":\n")
> 		} else {
> 			fmt.Fprintf(sb, "<h4>%s</h4>", s)
> ```

How do you feel about moving all the web stuff out into an `html.go` or a `debug.go` file? I'd hate for the business logic in both of these two files to get drowned out by the noise of these functions.
___
*[pkg/kv/kvserver/closedts/sidetransport/sender.go, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-MWVGfb647kF0JXbMU8k:-MWVGfb647kF0JXbMU8l:b9cqqdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/0951f28dbb5172d622162641fb7caff8a7513eb8/pkg/kv/kvserver/closedts/sidetransport/sender.go#L156)):*
> ```Go
> 	// ok is set if the desired timestamp can be closed. If not set, FailReason is
> 	// set.
> 	OK         bool
> ```

How do you feel about splitting this state over two variables instead of collapsing it into a single reason where `Ok` is a possible value? Does the latter approach strike you as less error prone?
___
*[pkg/kv/kvserver/closedts/sidetransport/sender.go, line 833 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-MWVInPNDn0bbVDdlk1q:-MWVInPOBsILuBnhPlVy:by7c4oz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0da89a2bc84b27fed201951cf694c65703e4bb4/pkg/kv/kvserver/closedts/sidetransport/sender.go#L833)):*
> ```Go
> 					// should have a blocking version of Dial() that we just leave hanging
> 					// and get a notification when it succeeds.
> 					r.cleanupStream()
> ```

Should we try to unify the hanlding of `recordDisconnected` and `cleanupStream` more closely? There's some redundancy here due to how we have debug state and real state parallel to one another.
___
*[pkg/server/server.go, line 700 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-MWVJQQr0xWbU0n9S_Vr:-MWVJQQr0xWbU0n9S_Vs:bp52ucy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0da89a2bc84b27fed201951cf694c65703e4bb4/pkg/server/server.go#L700)):*
> ```Go
> 	sStatus.setStmtDiagnosticsRequester(sqlServer.execCfg.StmtDiagnosticsRecorder)
> 	debugServer := debug.NewServer(st, sqlServer.pgServer.HBADebugFn())
> 	debugServer.RegisterClosedTimestampSideTransport(ctSender, ctReceiver)
> ```

Does this belong in `Server.PreStart`, somewhere near `s.debug.RegisterEngines`?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61963)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_closedts.go, line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-MWV7PXuAeA6nWSuIBal:-MWaPfIWCrJ3NHgQZTl_:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0951f28dbb5172d622162641fb7caff8a7513eb8/pkg/kv/kvserver/replica_closedts.go#L87)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`res.Desc = r.descRLocked()`
</blockquote></details>

done
___
*[pkg/kv/kvserver/closedts/ctpb/service.go, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-MWVH-WV86HqWaCKPC9Y:-MWaPo4vApDlO7IekXFp:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0da89a2bc84b27fed201951cf694c65703e4bb4/pkg/kv/kvserver/closedts/ctpb/service.go#L45)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: new line after this.
</blockquote></details>

done
___
*[pkg/kv/kvserver/closedts/sidetransport/receiver.go, line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-MWVHSiB-zdggGGMJHhY:-MWaQ2Xk3AkjXiGntZTM:b2txb03) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0da89a2bc84b27fed201951cf694c65703e4bb4/pkg/kv/kvserver/closedts/sidetransport/receiver.go#L138)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Was this needed?
</blockquote></details>

just the nodeid. changed to that
___
*[pkg/kv/kvserver/closedts/sidetransport/receiver.go, line 363 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-MWVI-Z0D8McWGnnQlRy:-MWaQq069PR14Ms92Aip:bdyzlw7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0da89a2bc84b27fed201951cf694c65703e4bb4/pkg/kv/kvserver/closedts/sidetransport/receiver.go#L363)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this the canonical way to generate HTML from Go? It all seems a little janky. Did you consider the use of `html/template` like we use in `writeToHTML`?
</blockquote></details>

I don't know what I considered... I did struggle a bit. Maybe I'll try it. I can assure it it'll be janky either way.
One thing, which is not even the main problem, is that I've tried to make these methods do either HTML or plain string. Although the plain string is not used at the moment. You think it's overkill?
___
*[pkg/kv/kvserver/closedts/sidetransport/receiver.go, line 363 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-MWVIGoQ59qIF_btaaxh:-MWaW5zQESdsFlLPwXEq:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0da89a2bc84b27fed201951cf694c65703e4bb4/pkg/kv/kvserver/closedts/sidetransport/receiver.go#L363)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

How do you feel about moving all the web stuff out into an `html.go` or a `debug.go` file? I'd hate for the business logic in both of these two files to get drowned out by the noise of these functions.
</blockquote></details>

done
___
*[pkg/kv/kvserver/closedts/sidetransport/sender.go, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-MWVGfb647kF0JXbMU8k:-MWaRlL-5Hjt0wE67hXR:b-qz1rsk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0951f28dbb5172d622162641fb7caff8a7513eb8/pkg/kv/kvserver/closedts/sidetransport/sender.go#L156)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

How do you feel about splitting this state over two variables instead of collapsing it into a single reason where `Ok` is a possible value? Does the latter approach strike you as less error prone?
</blockquote></details>

So how would you split it exactly? What do you do with `Desc`, which is needed on both success and failure?
___
*[pkg/kv/kvserver/closedts/sidetransport/sender.go, line 833 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-MWVInPNDn0bbVDdlk1q:-MWaSy2z4EmanNM_kxDk:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0da89a2bc84b27fed201951cf694c65703e4bb4/pkg/kv/kvserver/closedts/sidetransport/sender.go#L833)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we try to unify the hanlding of `recordDisconnected` and `cleanupStream` more closely? There's some redundancy here due to how we have debug state and real state parallel to one another.
</blockquote></details>

done
___
*[pkg/server/server.go, line 700 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-MWVJQQr0xWbU0n9S_Vr:-MWaU6gE1Cr7OTZw-nrH:b-gjloza) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0da89a2bc84b27fed201951cf694c65703e4bb4/pkg/server/server.go#L700)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does this belong in `Server.PreStart`, somewhere near `s.debug.RegisterEngines`?
</blockquote></details>

I'm not sure it's not better to bind things as early as possible, but done.

**Review by nvb — COMMENTED** [review]
> Reviewed 10 of 10 files at r3, 15 of 15 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61963)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @andreimatei)

___
*[pkg/kv/kvserver/closedts/sidetransport/receiver.go, line 363 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-MWVI-Z0D8McWGnnQlRy:-MWbEai3BEFNu1MdBeNM:b-9sfh2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0da89a2bc84b27fed201951cf694c65703e4bb4/pkg/kv/kvserver/closedts/sidetransport/receiver.go#L363)):*
> You think it's overkill?

I like the idea of having String methods, but I'm not sure that the attempt to avoid some duplication is actually making the code any clearer.
___
*[pkg/kv/kvserver/closedts/sidetransport/sender.go, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-MWVGfb647kF0JXbMU8k:-MWbE2sJDjjGvLvbhUk4:boxy51s) ([raw file](https://github.com/cockroachdb/cockroach/blob/0951f28dbb5172d622162641fb7caff8a7513eb8/pkg/kv/kvserver/closedts/sidetransport/sender.go#L156)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

So how would you split it exactly? What do you do with `Desc`, which is needed on both success and failure?
</blockquote></details>

Sorry, what I meant was that you're currently splitting it across `OK` and `FailReason`. You could just generalize `FailReason` to have an `Ok` option instead. I don't think that would impact `Desc`, would it?

**Comment by aayushshah15** [comment]
Andrei how do you feel about plopping these things into a set of tables instead of what we have right now? 

The current layout works fine if we're grepping for specific ranges and whatnot, but it seems like it'll get really unwieldy with thousands of ranges otherwise. What do you think?

**Review by andreimatei — COMMENTED** [review]
> Andrei how do you feel about plopping these things into a set of tables instead of what we have right now?

I think a table would be needlessly make the page very large. I say let's start with what we have here and keep the sky as the limit for the future.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-:-MYgAOk73qFhVno2HZFq:b3tlqim)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @nvanbenschoten)

___
*[pkg/kv/kvserver/closedts/sidetransport/receiver.go, line 363 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-MWVI-Z0D8McWGnnQlRy:-MYgAHKTAhCggT00sCUF:b-kpidr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0da89a2bc84b27fed201951cf694c65703e4bb4/pkg/kv/kvserver/closedts/sidetransport/receiver.go#L363)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> You think it's overkill?

I like the idea of having String methods, but I'm not sure that the attempt to avoid some duplication is actually making the code any clearer.
</blockquote></details>

I removed the `String` methods.
___
*[pkg/kv/kvserver/closedts/sidetransport/sender.go, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-MWVGfb647kF0JXbMU8k:-MYgBaoj9t4MTX4ZsSYC:byl426u) ([raw file](https://github.com/cockroachdb/cockroach/blob/0951f28dbb5172d622162641fb7caff8a7513eb8/pkg/kv/kvserver/closedts/sidetransport/sender.go#L156)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Sorry, what I meant was that you're currently splitting it across `OK` and `FailReason`. You could just generalize `FailReason` to have an `Ok` option instead. I don't think that would impact `Desc`, would it?
</blockquote></details>

I prefer it how it is, with a separate OK... It's easier to check for success I think. No?

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 16 files at r5, 15 of 15 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-:-MYhKwW3-c4cpIi97oJ2:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[pkg/kv/kvserver/closedts/sidetransport/sender.go, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-MWVGfb647kF0JXbMU8k:-MYhKcVA2WylK1byOL1D:b31d8nt) ([raw file](https://github.com/cockroachdb/cockroach/blob/0951f28dbb5172d622162641fb7caff8a7513eb8/pkg/kv/kvserver/closedts/sidetransport/sender.go#L156)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I prefer it how it is, with a separate OK... It's easier to check for success I think. No?
</blockquote></details>

I don't feel strongly, I just thought you'd like the elimination of the possibility of a `{Ok: true, FailReason: InvalidLease}` state. If not, feel free to ignore.

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-:-MYkEOwX1PjPYw-fbt3X:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)

**Comment by yuzefovich** [comment]
bors r-

There is a merge conflict here.

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-:-MYq87Iz1O9ZM_UlMqds:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15 and @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
some sort of TC compilation flake?

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-:-MYqGjYI5cduMJ7DF-5L:b-a5w29r)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15 and @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
bors r-

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-:-MYqSsDA4dDPyAA1CDSR:b-ydi9aw)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15 and @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61963#-:-MYqdNRi7D1bTK2zWOwg:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15 and @nvanbenschoten)

**Pull request merged**
