### PR TITLE
roachtest: make clearrange stricter

### PR DESCRIPTION
**Pull request by tbg**
In addition to running consistency checks frequently, fatal when the stats
are found to be incorrect.

Release note: None

### CODE REVIEW

**Review by benesch — APPROVED** [review]
:lgtm: modulo the envutil thing

And thanks! This is a great idea.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30818#-:-LNjnL9VATCACXb-zWNc:b-myi2oj)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/replica_consistency.go, line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30818#-LNjn3cb4_C-Kw62uNvb:-LNjn3cb4_C-Kw62uNvc:b4cbtv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/257f090b1a1542a511b633e8980c9362e7ab43f2/pkg/storage/replica_consistency.go#L113)):*
> ```Go
> 		}
> 
> 		if !delta.ContainsEstimates && envutil.EnvOrDefaultBool("COCKROACH_FATAL_ON_STATS_MISMATCH", false) {
> ```

I believe there is a requirement that all `envutil.EnvOrDefaultBool` calls occur during package initialization. (I.e., I think you need to extract this into a package global variable.)

**Review by petermattis — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30818#-:-LNjuduD4875wtvtMhKX:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/clearrange.go, line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30818#-LNjuKRDBWA41Kych7BJ:-LNjuKRDBWA41Kych7BK:bur77cy) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd63a641b73d87c77aea09eb52d1156458425cb8/pkg/cmd/roachtest/clearrange.go#L34)):*
> ```Go
> 			MinVersion: `v2.1.0`,
> 			Nodes:      nodes(10),
> 			// TODO(tschottdorf): seems like this should be stable.
> ```

I'd be fine with making that bump.

**Review by tbg — COMMENTED** [review]
TFTRs!

bors r=benesch,petermattis

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30818#-:-LNjwW0E9AelYtExDowZ:b-29g7su)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/cmd/roachtest/clearrange.go, line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30818#-LNjuKRDBWA41Kych7BJ:-LNjwNLp4WxUQqKgwcaE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd63a641b73d87c77aea09eb52d1156458425cb8/pkg/cmd/roachtest/clearrange.go#L34)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'd be fine with making that bump.
</blockquote></details>

Done.

**Review by benesch — APPROVED** [review]
> Reviewed 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30818)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Review by benesch — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30818)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Comment by tschottdorf** [comment]
Oops, linter complains.

bors r-

**Comment by tschottdorf** [comment]
bors r=petermattis,benesch

**Pull request merged**
