### PR TITLE
test: add a zone to test clusters

### PR DESCRIPTION
**Pull request by andrewbaptist**
Some code, notable dist_sender will log at higher log verbosity if a zone isn't specified for nodes. Adding a zone to a default configuration will surpress this logging.

Epic: none

Release note: None

### CODE REVIEW

**Comment by andrewbaptist** [comment]
@kvoli this started logging more after @wenyihu6 had added the check. This changes the tests to have a zone specified so there is no error.

**Comment by wenyihu6** [comment]
@kvoli Should I just remove these log lines or use `log.Every(time)` instead? I can send a patch for this. 
https://github.com/cockroachdb/cockroach/blob/c097a16427f65e9070991f062716d222ea5903fe/pkg/util/log/every_n.go#L20-L25

I think I added them initially to warn about the metric inaccuracies when localities were not set up properly. But it seems to be getting lots of complaints.

**Comment by andrewbaptist** [comment]
I think it is OK now that they are at a lower logging level. It is good that our test code covers this also, so I think it is reasonable to leave it it. I'll let @kvoli comment.

**Comment by kvoli** [comment]
> I think it is OK now that they are at a lower logging level. It is good that our test code covers this also, so I think it is reasonable to leave it it. I'll let @kvoli comment.

I believe it is fine now -- we log at a V level for all relevant log lines, this is mostly relevant to debugging.

**Pull request closed without merging**
