### PR TITLE
*: split sqlccl up into subpackages

### PR DESCRIPTION
**Pull request by dt**
Tried to keep this as mechanical as possible -- file renames, package name changes, a few exports and adding package qualifiers on callsites. A couple places, mostly in tests, required a bit of content editing -- moved the export storage helper to storageccl, a couple load_test.go tests were using backup/restore testing helpers. Added TODOs around a couple that should be moved/cleaned up post-refactor: some IMPORT calls are scattered in with some backup tests, until #21813 merges I just stubbed into_db for import.

### CODE REVIEW

**Comment by dt** [comment]
(as far as those TODOs, I'd prefer to merge the big, mechanical, harder to rebase change sooner rather than later, and follow up on with subsequent PRs, rather than try to get it all done at once).

**Comment by mjibson** [comment]
kv_test.go is the only file remaining in the sqlccl directory. It should likely be moved or removed. Is there any point in having a sqlccl directory at all anymore? Should its subdirs just be moved up to ccl?

**Comment by dt** [comment]
rebased and removed the into_db stub

**Review by danhhz — APPROVED** [review]
LGTM. agree with mjibson that the sqlccl dir seems unnecessary

**Comment by dt** [comment]
I figured it made sense to keep the `sqlccl` grouping as the the things under `sqlccl` are still implementing sql-exposed functionality, as opposed to storage/kv or pure libs like util, but I don't feel too strongly.

**Comment by dt** [comment]
@mjibson @danhhz how strongly do y'all feel about the dir depth?

**Comment by danhhz** [comment]
I don't think the grouping is buying us anything, but I don't feel strongly

**Comment by dt** [comment]
flattened

**Pull request merged**
