### PR TITLE
roachtest: jepsen to use pre-built uber jar

### LINKED ISSUE #74876: roachtest: jepsen nightlies - package self contained binary instead of buiding on the spot
Pulling dependency for testing framework that we don't normally change seems wasteful and error prone. We should instead pre-build and put a self contained archive as suitable for clojure apps.

Example of dependency download failure: #74673

At the first glance, this seem like a way to go: https://github.com/technomancy/leiningen/blob/master/doc/TUTORIAL.md and maybe push that to aws storage for us to download.

Jira issue: CRDB-12302

### PR DESCRIPTION
**Pull request by aliher1911**
Previously jepsen tests were built on the controller node prior to running. This is not ideal as fetching dependencies could fail and image should have build tools installed.
This PR changes test to use pre build jepsen binary from google cloud storage with a fallback to building from sources to be able to test changes.

Release note: None

Fixes #74876

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91298)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @herkolategan)

___
*[`pkg/cmd/roachtest/tests/jepsen.go` line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91298#-NGFBbTJ8HCLFhZOSAQ5:-NGFBbTJ8HCLFhZOSAQ6:bvz2dxh) ([raw file](https://github.com/cockroachdb/cockroach/blob/093ca5f670ae237a7a829465385f5ee109e4bed4/pkg/cmd/roachtest/tests/jepsen.go#L49)):*
> ```Go
> curl -o lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
> chmod +x lein
> cd jepsen/cockroachdb
> ```

Let's include : `git clone https://github.com/cockroachdb/jepsen`. It's not immediately obvious if you're just reading the preamble :)
___
*[`pkg/cmd/roachtest/tests/jepsen.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91298#-NGFAJdf9Nkgebplk-W6:-NGFAJdf9Nkgebplk-W7:b-e1yxnf) ([raw file](https://github.com/cockroachdb/cockroach/blob/093ca5f670ae237a7a829465385f5ee109e4bed4/pkg/cmd/roachtest/tests/jepsen.go#L68)):*
> ```Go
> 
> const gcpPath = "https://storage.googleapis.com/cockroach-jepsen"
> const binaryVersion = "0.1.0-SNAPSHOT-standalone"
> ```

Nit: I realize our jepsen fork hasn't been updated in > 2 years; still, it'd be nice to include the short sha into the jar name, since we're using a snapshot version; i.e., 

```
0.1.0-SNAPSHOT-4e97002-standalone
```

**Review by aliher1911 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91298)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/jepsen.go` line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91298#-NGFBbTJ8HCLFhZOSAQ5:-NGIJI-N3BvAtaqXMZ2z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/093ca5f670ae237a7a829465385f5ee109e4bed4/pkg/cmd/roachtest/tests/jepsen.go#L49)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Let's include : `git clone https://github.com/cockroachdb/jepsen`. It's not immediately obvious if you're just reading the preamble :)
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/tests/jepsen.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91298#-NGFAJdf9Nkgebplk-W6:-NGIIoZ16Q2eCTlTj72p:bckndxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/093ca5f670ae237a7a829465385f5ee109e4bed4/pkg/cmd/roachtest/tests/jepsen.go#L68)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Nit: I realize our jepsen fork hasn't been updated in > 2 years; still, it'd be nice to include the short sha into the jar name, since we're using a snapshot version; i.e., 

```
0.1.0-SNAPSHOT-4e97002-standalone
```
</blockquote></details>

It turned out we name it 0.1.0 and at the same time build agains snapshot of jepsen core - complete mess. 
But because it is all done by hand and we treat it a mono-repo, having sha is helpful as we could trace back to actual code. So I put that and also to the comment as it is our source of truth.

**Review by srosenberg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91298)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @herkolategan)

___
*[`pkg/cmd/roachtest/tests/jepsen.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91298#-NGFAJdf9Nkgebplk-W6:-NGINAv2CaMWMpVJo2th:b-uufgn3) ([raw file](https://github.com/cockroachdb/cockroach/blob/093ca5f670ae237a7a829465385f5ee109e4bed4/pkg/cmd/roachtest/tests/jepsen.go#L68)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

It turned out we name it 0.1.0 and at the same time build agains snapshot of jepsen core - complete mess. 
But because it is all done by hand and we treat it a mono-repo, having sha is helpful as we could trace back to actual code. So I put that and also to the comment as it is our source of truth.
</blockquote></details>

Oh, I see. This commit is also on `tc-nightly-main`. Do you know why we're not building off of master?

**Review by aliher1911 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91298)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/jepsen.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91298#-NGFAJdf9Nkgebplk-W6:-NGIOsip1LaJKdPm9WcL:bniwjy9) ([raw file](https://github.com/cockroachdb/cockroach/blob/093ca5f670ae237a7a829465385f5ee109e4bed4/pkg/cmd/roachtest/tests/jepsen.go#L68)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Oh, I see. This commit is also on `tc-nightly-main`. Do you know why we're not building off of master?
</blockquote></details>

Master is original jepsen master and they keep changing core and adding more databases again.
We also added some changes to core to address flakes that caused trouble to our tests, and updated cockroachdb to work with linux versions that we use on build images, but it probably made little sense upstream at the time or we just wanted to move fast and not bother with merging that all back. So I guess we just made our own fork and tc-nightly branch.

`tc-nightly-main` is what I added to allow us to make changes in future without breaking old cockroach releases that will rely on building from source forever. It is not too late to come up with any other schema for that if this doesn't sound good enough. I build standalone jar from hash that we currently use for tc-nightly so that we have a baseline functionally no different from current tests.

**Review by srosenberg — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91298#-:-NGIWVh-69LALfm3qPev:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aliher1911 and @herkolategan)

___
*[`pkg/cmd/roachtest/tests/jepsen.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91298#-NGFAJdf9Nkgebplk-W6:-NGIWP0t0QlGqFQQ5apE:b-k6rpao) ([raw file](https://github.com/cockroachdb/cockroach/blob/093ca5f670ae237a7a829465385f5ee109e4bed4/pkg/cmd/roachtest/tests/jepsen.go#L68)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Master is original jepsen master and they keep changing core and adding more databases again.
We also added some changes to core to address flakes that caused trouble to our tests, and updated cockroachdb to work with linux versions that we use on build images, but it probably made little sense upstream at the time or we just wanted to move fast and not bother with merging that all back. So I guess we just made our own fork and tc-nightly branch.

`tc-nightly-main` is what I added to allow us to make changes in future without breaking old cockroach releases that will rely on building from source forever. It is not too late to come up with any other schema for that if this doesn't sound good enough. I build standalone jar from hash that we currently use for tc-nightly so that we have a baseline functionally no different from current tests.
</blockquote></details>

Sounds good, thanks!

**Comment by aliher1911** [comment]
bors r=srosenberg

**Pull request merged**
