### PR TITLE
catalog: collecting virtual schemas can be expensive for some ORM queries 

### LINKED ISSUE #124750: catalog: collecting virtual schemas can be expensive for some ORM queries
Previously, when profiling certain ORM queries like the async PG type ones we would see excessive time in converting virtual schemas into Catalog objects that could be consumed by the descs.Collection. This was unnecessary and also showing up in benchmarking the ORM queries on larger schemas inside a new roach test for large schemas or BenchmarkORMQueries/asyncpg_type. This can be optimized by doing this entire conversion process once, since virtual schemas are immutable.

Jira issue: CRDB-39057

Epic CRDB-24134

### PR DESCRIPTION
**Pull request by fqazi**
Previously, when running ORM queries with larger schemas or our ORM query bench test we noticed that aggregating virtual schema objects could take a big chunk of time. This was because converting the internal the VirtualTable / VirtualSchemas into a nstree.Catalog was not cheap. To address this, this patch will:

1. Convert the VirtualTable / VirtualSchemas into a nstree.Catalog which can be used between collections (the entire state here is immutable).
2. Reduce some extra copies that happen when copying betwen nstree.Catalog objects, by allowing references to be ingested.

Fixes: #124750

```Orignal:
BenchmarkORMQueries/asyncpg_types         	       1	16914664491 ns/op	         0 roundtrips	6151796312 B/op	33275332 allocs/op
After having a shared nstree.Catalog object:
BenchmarkORMQueries/asyncpg_types         	       1	13252306945 ns/op	         0 roundtrips	5442736128 B/op	29586155 allocs/op
After optimizing MutableCatalog.AddAll:
BenchmarkORMQueries/asyncpg_types         	       1	12399752839 ns/op	         0 roundtrips	4602288096 B/op	27474078 allocs/op
````

### CODE REVIEW

**Review by annrpom — APPROVED** [review]
lgtm! just had a small question about the 2nd commit

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124751)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @fqazi)

___
*[`pkg/sql/virtual_schema.go` line 993 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124751#-NyzgOpt4ejLcMOg_8HO:-NyzgOpuEXcOX9DTV22_:b-j2kfvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b592a2f448577ae73792d9c7a8ac2fe24d184f34/pkg/sql/virtual_schema.go#L993)):*
> ```Go
> 		}
> 		ck := catalogkeys.CommentKey{ObjectID: uint32(vd.GetID())}
> 		switch vd.DescriptorType() {
> ```

why do we only care about these cases here, and not comments on columns, indexes, constraints, or functions? (i see this was a copy paste from the old code, but just curious)

**Review by rafiss — COMMENTED** [review]
this seems pretty safe to backport, what do you think?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124751#-:-NyziBwq2-EdMDAay36D:b-c49d1)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @fqazi)

**Review by fqazi — COMMENTED** [review]
Yeah, I'll tag it for 24.1

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124751#-:-NyzttSNCLUvVM_DPxfX:b2qygs5)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @rafiss)

___
*[`pkg/sql/virtual_schema.go` line 993 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124751#-NyzgOpt4ejLcMOg_8HO:-NyzpIl_5-bayStZN3OE:b63deta) ([raw file](https://github.com/cockroachdb/cockroach/blob/b592a2f448577ae73792d9c7a8ac2fe24d184f34/pkg/sql/virtual_schema.go#L993)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

why do we only care about these cases here, and not comments on columns, indexes, constraints, or functions? (i see this was a copy paste from the old code, but just curious)
</blockquote></details>

Currently we can only have relations or schemas in the virtual schema holder. But as a safety I added an assertion for other descriptor types.
___
*[`pkg/sql/catalog/nstree/catalog_mutable.go` line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124751#gh-1617379874:-NyzpRU6-zpC0ugmHbid:bxcdw0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/1af4e204979363109a04ed5a1b05f165ed722121/pkg/sql/catalog/nstree/catalog_mutable.go#L63)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

is there any benefit in the previous code (`ensureForID/ensureForName`) existing? or is that lift less safe?
</blockquote></details>

We can't use this code, but we should share it with the existing one. The existing code will add a new entry if it doesn't exist. If it does exist weirdly it will replace the entry and copy back the original data. But we can use the WithEntry variants to back them.

**Pull request merged**
