### PR TITLE
kvnemesis: support Scan operations

### LINKED ISSUE #50202: kv: CanForwardReadTimestamp not unset for multi-range batch
`CanForwardReadTimestamp` is described as:

https://github.com/cockroachdb/cockroach/blob/9a38931424b4b84116da606820d3cde699c90879/pkg/roachpb/api.proto#L1942-L1951

Like `EndTxn.CanCommitAtHigherTimestamp`, we unset the flag in `DistSender` if we notice a batch that is split into multiple sub-batches due to request type incompatibility:
https://github.com/cockroachdb/cockroach/blob/9a38931424b4b84116da606820d3cde699c90879/pkg/kv/kvclient/kvcoord/dist_sender.go#L575

However, we don't unset the flag in `DistSender` if a we notice a batch that is split into multiple sub-batches due to range boundaries in `divideAndSendBatchToRanges`. This was likely missed because doing so was not necessary for `EndTxn.CanCommitAtHigherTimestamp`. I think this is because non-parallel commit `EndTxn`s are prevented from splitting on range boundaries by [this check](https://github.com/cockroachdb/cockroach/blob/9a38931424b4b84116da606820d3cde699c90879/pkg/kv/kvclient/kvcoord/dist_sender.go#L1045-L1047) and parallel commit `EndTxn`s are [never issued](https://github.com/cockroachdb/cockroach/pull/44608) for batches with reads in them (i.e. for batches where any of the requests `NeedsRefresh`).

This doesn't affect the vast majority of workloads, but can lead to serializability violations for those that are affected. The conditions for being effected are:
1. the first operation that the transaction performs is a batch of locking read requests (due to implicit or explicit SFU)
2. this batch of locking reads spans multiple ranges
3. this batch of locking reads is issued in parallel by the `DistSender`
4. this locking read hits contention and is bumped on at least one of the ranges due to a WriteTooOld error

It turns out that the `kv/contention` roachtest meets these requirements perfectly when implicit SFU support is added to `UPSERT` statements: https://github.com/cockroachdb/cockroach/issues/50180. It creates a tremendous amount of contention and issues a batch of locking `ScanRequests` during a LookupJoin as its first operation. This materializes as ConditionFailedErrors (which should be impossible) in the `CPut`s that the `UPSERT` issues to maintain the table's secondary index.

### PR DESCRIPTION
**Pull request by nvb**
This commit adds support for scan operations to KVNemesis. This is all fairly straightforward. The most complex part of the change is the op time validation. The approach used here is to intersect the valid times of each of the keys returned by the scan. We then intersect this with the timeSpan preceding the timestamp of each key-value in the scan's bounds but not returned by the scan. This final timeSpan is the span of time that the scan is valid.

As a sanity check, I confirmed that `TestKVNemesisSingleNode` fails under stress almost immediately with a `committed txn non-atomic timestamps` error if I remove the `needsRefresh` from `ScanRequest`. Without that intentional bug, it has not yet failed after over an hour (~30k iterations) of stress.

I also confirmed that if I switch `Batch.Scan` for `Batch.ScanForUpdate`, stressing `TestKVNemesisSingleNode` fails after about 2 minutes because of #50202. When I apply the patch to fix #50202, the failure goes away. Adding a locking scan op to kvnemesis and fixing #50202 will come in a later change, but since that's what motivated this work, it's nice to confirm that this is improving testing coverage sufficiently to catch such bugs.

@tbg assigning you to review because I think you're the only other person who has looked at kvnemesis outside of Dan and me.
@aayushshah15 assigning you to review because I'm hoping that will change 😃. kvnemesis is a powerful tool for testing the kv layer, and closed timestamps in particular. It's already caught serious issues, and with medium-sized investment, I suspect that it will catch many more. Unfortunately, with Dan on leave, it's currently without an owner. I know you've already had a lot of success with this kind of randomized testing in the past. If you're interested in expanding on this, getting familiar with the kvnemesis would be a great place to start!

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
Looks good to me, but I'll defer to @aayushshah15!

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50314#-:-MA0sv4q0u1MxoqPSq2y:b-a5yr5p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvnemesis/generator.go, line 392 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50314#-MA0p8co61HZIPaST-Mi:-MA0p8co61HZIPaST-Mj:bm075oh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b631e7350749a33c23d1a3347a50527126d2d328/pkg/kv/kvnemesis/generator.go#L392)):*
> ```Go
> func randScan(g *generator, rng *rand.Rand) Operation {
> 	key, endKey := randKey(rng), randKey(rng)
> 	if endKey < key {
> ```

What about when they're equal? Won't that return an error from the KV API?
___
*[pkg/kv/kvnemesis/validator.go, line 441 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50314#-MA0q2u068lecr0Keu0y:-MA0q2u068lecr0Keu0z:bekdxwm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b631e7350749a33c23d1a3347a50527126d2d328/pkg/kv/kvnemesis/validator.go#L441)):*
> ```Go
> 	var failure string
> 	for idx, observation := range txnObservations {
> 		if failure != `` {
> ```

I like how you're consistently using Dan quotes in this file.
___
*[pkg/kv/kvnemesis/validator.go, line 704 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50314#-MA0qUDI7m2mb8jpJeK5:-MA0qUDI7m2mb8jpJeK6:b32wo2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b631e7350749a33c23d1a3347a50527126d2d328/pkg/kv/kvnemesis/validator.go#L704)):*
> ```Go
> 			continue
> 		}
> 		// Key not in scan response. Only valid is scan was before key's time.
> ```

if
___
*[pkg/kv/kvnemesis/validator.go, line 768 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50314#-MA0ruKg3sokkkLZbGzx:-MA0ruKg3sokkkLZbGzy:b-axacq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b631e7350749a33c23d1a3347a50527126d2d328/pkg/kv/kvnemesis/validator.go#L768)):*
I was just looking at the test cases further below and found it hard to decipher the output. For example here:

> `[s]{a-c}:[0.000000002,0,0,0)->["a":v1, "a2":v3, "b":v2]`,

what's `0.000000002,0,0,0`? It corresponds to `[start,end)` here and would hopefully explain to me the validity window of each read but how?
Should `observedScan` instead have the validity windows and print this a little more informatively?

**Review by aayushshah15 — COMMENTED** [review]
Looks good to me as well, though I'd prefer to give it another pass towards the end of the day since I haven't fully grokked it yet.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50314#-:-MA1oyUaEquoJWqWQAaJ:bqybhhp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvnemesis/validator.go, line 768 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50314#-MA0ruKg3sokkkLZbGzx:-MA1ouyh-D2zujmzK5kS:b2ngthx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b631e7350749a33c23d1a3347a50527126d2d328/pkg/kv/kvnemesis/validator.go#L768)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I was just looking at the test cases further below and found it hard to decipher the output. For example here:

> `[s]{a-c}:[0.000000002,0,0,0)->["a":v1, "a2":v3, "b":v2]`,

what's `0.000000002,0,0,0`? It corresponds to `[start,end)` here and would hopefully explain to me the validity window of each read but how?
Should `observedScan` instead have the validity windows and print this a little more informatively?
</blockquote></details>

+1

**Review by aayushshah15 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50314)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/kv/kvnemesis/validator.go, line 682 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50314#-MA3NTTrDOM32vF64a4a:-MA3NTTrDOM32vF64a4b:bj9jlgc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b631e7350749a33c23d1a3347a50527126d2d328/pkg/kv/kvnemesis/validator.go#L682)):*
> ```Go
> 	// Augment with the valid time span for any kv not observed but that
> 	// overlaps the scan span.
> 	// TODO(dan): this will get more complex once we add deletes.
> ```

I'm planning on spending some time adding node restarts to this soon (hopefully I'll get to it next week). I can give adding deletes a shot as well if it doesn't prove to be super complex, feel free to assign this todo to me.

**Review by nvb — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50314#-:-MA4d-BR1NVnatEcj-P6:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @tbg)

___
*[pkg/kv/kvnemesis/generator.go, line 392 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50314#-MA0p8co61HZIPaST-Mi:-MA4Sp4SBIhJO_ht-mEL:bnbr00k) ([raw file](https://github.com/cockroachdb/cockroach/blob/b631e7350749a33c23d1a3347a50527126d2d328/pkg/kv/kvnemesis/generator.go#L392)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

What about when they're equal? Won't that return an error from the KV API?
</blockquote></details>

I thought it would just be an empty range, but you're right. It hits an `end key %q must be greater than start %q` error. Fixed.
___
*[pkg/kv/kvnemesis/validator.go, line 441 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50314#-MA0q2u068lecr0Keu0y:-MA4Swh40QUmujRKVA89:boml89q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b631e7350749a33c23d1a3347a50527126d2d328/pkg/kv/kvnemesis/validator.go#L441)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I like how you're consistently using Dan quotes in this file.
</blockquote></details>

It wasn't easy to bring myself to do it.
___
*[pkg/kv/kvnemesis/validator.go, line 682 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50314#-MA3NTTrDOM32vF64a4a:-MA4T4P868EOQQTso1kk:b-6pn8n4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b631e7350749a33c23d1a3347a50527126d2d328/pkg/kv/kvnemesis/validator.go#L682)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

I'm planning on spending some time adding node restarts to this soon (hopefully I'll get to it next week). I can give adding deletes a shot as well if it doesn't prove to be super complex, feel free to assign this todo to me.
</blockquote></details>

Great! Deletes will be a little tricky because they will force you to represent distinctions of timeSpans, but it all seems doable. Reassigned.
___
*[pkg/kv/kvnemesis/validator.go, line 704 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50314#-MA0qUDI7m2mb8jpJeK5:-MA4UR5-0ShM2uV-bArJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b631e7350749a33c23d1a3347a50527126d2d328/pkg/kv/kvnemesis/validator.go#L704)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

if
</blockquote></details>

Done.
___
*[pkg/kv/kvnemesis/validator.go, line 768 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50314#-MA0ruKg3sokkkLZbGzx:-MA4V-0uBECsDmJm-LGO:b-qu6n94) ([raw file](https://github.com/cockroachdb/cockroach/blob/b631e7350749a33c23d1a3347a50527126d2d328/pkg/kv/kvnemesis/validator.go#L768)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

+1 
</blockquote></details>

Good point. Done.

**Pull request merged**
