### PR TITLE
multiregionccl: move multiregion database creation to CCL

### PR DESCRIPTION
**Pull request by otan**
Refs #59668 
(no enterprise checks in yet)

----

Multi-region database creation now requires a CCL license.

Release justification: low-risk changes to new functionality

Release note: None

### CODE REVIEW

**Review by ajstorm — APPROVED** [review]
:lgtm: 

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60950#-:-MUDySyv0y9JzIm-Fgdn:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/ccl/multiregionccl/multiregion.go, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60950#-MUDwuP4-7HJG-hxh281:-MUDwuP4-7HJG-hxh282:b-mroeyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/b241ea5258954b6036fe9aaf2beedfc4f4bb2b7e/pkg/ccl/multiregionccl/multiregion.go#L49)):*
> ```Go
> 
> 	regionConfig.PrimaryRegion = descpb.RegionName(primaryRegion)
> 	if regionConfig.PrimaryRegion != "" {
> ```

Can we use `tree.PrimaryRegionLocalityName` here?  Or do we not have access to that in CCL?
___
*[pkg/ccl/multiregionccl/multiregion.go, line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60950#-MUDx05p5DAaKjlOX5iV:-MUDx05p5DAaKjlOX5iW:b20gi4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/b241ea5258954b6036fe9aaf2beedfc4f4bb2b7e/pkg/ccl/multiregionccl/multiregion.go#L55)):*
> ```Go
> 	}
> 	if len(regions) > 0 {
> 		if regionConfig.PrimaryRegion == "" {
> ```

Nit: Same comment as above.
___
*[pkg/sql/descriptor.go, line 329 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60950#-MUDxeSU6t8P7VmwM4XG:-MUDxeSU6t8P7VmwM4XH:bejn78c) ([raw file](https://github.com/cockroachdb/cockroach/blob/b241ea5258954b6036fe9aaf2beedfc4f4bb2b7e/pkg/sql/descriptor.go#L329)):*
> ```Go
> ) (descpb.DatabaseDescriptor_RegionConfig, error) {
> 	return descpb.DatabaseDescriptor_RegionConfig{}, sqlerrors.NewCCLRequiredError(
> 		errors.New("creating multi-region databases requires a CCL binary"),
> ```

Nit: Is there a more standard message here?  In the past I thought that this was referred to in messages as an "Enterprise License".  I think I saw this in the message for using partitioning.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60950)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/sql/descriptor.go, line 329 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60950#-MUDxeSU6t8P7VmwM4XG:-MUFJqQZ8JeIFdfUkrgo:b-wapuzc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b241ea5258954b6036fe9aaf2beedfc4f4bb2b7e/pkg/sql/descriptor.go#L329)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Is there a more standard message here?  In the past I thought that this was referred to in messages as an "Enterprise License".  I think I saw this in the message for using partitioning.
</blockquote></details>

that's the enterprise license check, which is different to the CCL check.
the CCL license means that people can't use that code without our permission or something of the ilk.
the enterprise check means that people paid. some parts of backup are CCL but unpaid, for example. i'm putting the paid check in in a separate PR.

**Comment by otan** [comment]
bors r=ajstorm

**Comment by otan** [comment]
sad

bors r-

**Comment by otan** [comment]
merge conflict resolved!

bors r=ajstorm

**Pull request merged**
