### PR TITLE
storage: In multiTestContext, give each store its own Gossip

### LINKED ISSUE #4821: circleci: failed tests (13716): TestRestoreReplicas
The following test appears to have failed:

[#13716](https://circleci.com/gh/cockroachdb/cockroach/13716):

```
I160303 17:11:53.652597 raft/raft.go:459  [group 1] 1 became follower at term 6
I160303 17:11:53.652746 raft/raft.go:235  [group 1] newRaft 1 [peers: [1,2], term: 6, commit: 15, applied: 15, lastindex: 15, lastterm: 6]
I160303 17:11:53.653104 storage/replica.go:1706  [node=1,store=1,range=1] gossiping system config from store 1, range 1, hash 91100e0451ac1aab78723f763fac84cccdd4aea5
I160303 17:11:53.654292 storage/replica.go:1647  [node=1,store=1,range=1] gossiping cluster id "00000000-0000-0000-0000-000000000000" from store 1, range 1
I160303 17:11:53.654756 storage/replica.go:1656  [node=1,store=1,range=1] gossiping sentinel from store 1, range 1
panic: gossip infostore's NodeID is 0

goroutine 5165 [running]:
github.com/cockroachdb/cockroach/gossip.(*infoStore).newInfo(0xc820154000, 0xc82029d9f8, 0x10, 0x10, 0x1bf08eb000, 0x2a)
	/go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:135 +0xb4
github.com/cockroachdb/cockroach/gossip.(*Gossip).AddInfo(0xc8208a4000, 0x1cafe20, 0x8, 0xc82029d9f8, 0x10, 0x10, 0x1bf08eb000, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:522 +0x12b
github.com/cockroachdb/cockroach/storage.(*Replica).maybeGossipFirstRange(0xc820238820, 0x35c1100)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:1658 +0xeea
github.com/cockroachdb/cockroach/storage.(*Store).maybeGossipFirstRange(0xc8200c8800, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:797 +0x3c3
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:741 +0x6d
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8202461c0, 0xc8209c6c20)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x70
FAIL	github.com/cockroachdb/cockroach/storage	8.909s
=== RUN   TestBatchBasics
I160303 17:12:02.168741 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.01s)
=== RUN   TestBatchGet
I160303 17:12:02.178731 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I160303 17:12:02.183855 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.01s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by bdarnell**
Removes a problematic use of ResetNodeID which could result in panics.

Also move other pieces of `multiTestContext` from shared objects to per-store fields as needed to change Gossip.

Fixes #4821

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4926)

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 3 of 3 files at r3, 12 of 12 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4926#-:-KCEdZJVQ4dKkb_bLSpJ:1417088721)*

**Comment by spencerkimball** [comment]
Fixes #4815

**Comment by bdarnell** [comment]
OK, I think I've figured out what's going on with that failing test. New commit added.

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4926#-:-KCSxJHn6VMdLLvL68_i:1417088721)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 3 of 3 files at r3, 12 of 12 files at r4, 14 of 14 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/client_raft_test.go, line 1127 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4926#-KCSxPCjMH1h0eNRPO8M:-KCSxPCkyMF4G4z9wwaJ:509197254) ([raw file](https://github.com/cockroachdb/cockroach/blob/5718c04a8d3b8e1e941fb5f6b337693ce2adfd0e/storage/client_raft_test.go#L1127)):*
either "store" or "are"

---

*[storage/client_raft_test.go, line 1169 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4926#-KCSxKxau90vaNSpZQ1F:-KCSxKxau90vaNSpZQ1G:1596171114) ([raw file](https://github.com/cockroachdb/cockroach/blob/5718c04a8d3b8e1e941fb5f6b337693ce2adfd0e/storage/client_raft_test.go#L1169)):*
why this change?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4926)*

**Comment by bdarnell** [comment]
Review status: 14 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/client_raft_test.go, line 1127 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4926#-KCSxPCjMH1h0eNRPO8M:-KCSyWq2udhvd2meBAou:676635175) ([raw file](https://github.com/cockroachdb/cockroach/blob/5718c04a8d3b8e1e941fb5f6b337693ce2adfd0e/storage/client_raft_test.go#L1127)):*
Done

---

*[storage/client_raft_test.go, line 1169 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4926#-KCSxKxau90vaNSpZQ1F:-KCSyXjerYmvIbpXkLNE:1709727889) ([raw file](https://github.com/cockroachdb/cockroach/blob/5718c04a8d3b8e1e941fb5f6b337693ce2adfd0e/storage/client_raft_test.go#L1169)):*
Just needed to get stack traces while debugging. Changed back.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4926)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4926#-:-KCTVx5dgW2is6DjdSX8:1417088721)*

**Pull request merged**
