### PR TITLE
storage: refactor the iteration for scans

### PR DESCRIPTION
**Pull request by yuzefovich**
**storage: refactor the iteration for scans**

This commit refactors the iteration that we have for handling scans and
reverse scans in order to split the "get" part from the "advance key"
part. This is needed for the KV projection pushdown work in order to
avoid copying each key-value pair: unlike with the existing
`pebbleResults` struct where we append all KVs into `repr` buffer (and,
thus, copy each KV anyway), with the projection pushdown work we want to
perform the decoding directly on the unsafe KV that the iterator is
pointing at. With the previous "eager" advancement of the iterator, that
KV pair would get invalidated before we could decode it (to keep only the
needed parts of the KV). Now the decoder will be able to access the
unsafe KV (and copy out the necessary parts) before it is invalidated.

An additional boolean is introduced to indicate whether a new KV was
added into the result set or not (also needed for the pushdown work) but
is currently unused.

Previously, the logic was as:
- seek to the first key
- in the loop:
  - get one KV and advance to the next key (both actions as a single
operation).

Now, the logic becomes:
- seek to the first key
- in the loop:
  - get one KV
  - if the iteration can continue, advance to the next key.

This is implemented by introducing a simple state machine for the
"advance key" functions. The benchmark results show minor changes,
mostly positive, some negative:
https://gist.github.com/yuzefovich/4f976075e8dc9c5da9171c281787432d

Informs: #82323

Epic: CRDB-14837

Release note: None

**storage: eliminate a copy of the key in some cases with reverse scans**

This commit changes the contract of `prevKey` method to require that
a copy is passed in. Previously, the method would make a copy of the key
on its own before using the iterator, but in one of the two places where
`prevKey` is used it would be redundant since the caller (`seekVersion`)
already made a copy.

Epic: None

Release note: None

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93134)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @yuzefovich)

___
*[`-- commits` line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93134#-NInKvb5BQFgEHcrsjMh):*
Can you elaborate a bit on why this is needed for filter pushdown? It's not at all clear to me.
I am guessing there is some new/future need for stopping the iteration, without stepping the iterator, even when `get one KV` says that iteration can continue.
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93134#-NInP_k-DPBkMPv8Qf0o:-NInP_k-DPBkMPv8Qf0p:b-v0ycor) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc543b0a94314aa01f45b0d6318b8135bda549ac/pkg/storage/pebble_mvcc_scanner.go#L404)):*
> ```Go
> 	machine struct {
> 		// fn indicates the advance function that needs to be called next.
> 		fn advanceFn
> ```

This new code is a bit more error prone if something forgets to update `fn`. I don't have a better idea.
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93134#-NInTl7O4L5hX2To6jKt:-NInTl7O4L5hX2To6jKu:b-x4hkzc) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc543b0a94314aa01f45b0d6318b8135bda549ac/pkg/storage/pebble_mvcc_scanner.go#L406)):*
> ```Go
> 		fn advanceFn
> 		// origKey is a temporary buffer used to store the "original key" when
> 		// advancing the iterator at the new key.
> ```

Can you add to this code comment that this is backed by `keyBuf`.
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 690 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93134#-NInKRMj3nPVugMydLx0:-NInKRMj3nPVugMydLx1:b2uadxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc543b0a94314aa01f45b0d6318b8135bda549ac/pkg/storage/pebble_mvcc_scanner.go#L690)):*
> ```Go
> // - ok indicates whether the iteration should continue.
> // - added indicates whether a tuple was included into the result set.
> // (ok=true, added=false) indicates that the current key was skipped for some
> ```

will this (ok=true,added=false) case also be used in the future in which filter application will happen here and the item will not be added?
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 1073 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93134#-NInRqWO6IA6STPS2pft:-NInRqWO6IA6STPS2pfu:b-gvutgp) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc543b0a94314aa01f45b0d6318b8135bda549ac/pkg/storage/pebble_mvcc_scanner.go#L1073)):*
> ```Go
> // at new key" state.
> func (p *pebbleMVCCScanner) setAdvanceKeyAtNewKey(origKey []byte) {
> 	p.machine.origKey = origKey
> ```

The old code would immediately call into `prevKey` that would copy again.
Now we call `prevKey` later, which will also make a copy of origKey. Since we are in this code already, I think it's worth optimizing this path. If we lift the copying out of `prevKey` the other caller (`advanceKeyReverse`) will need to make a copy before calling `prevKey`.
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 1083 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93134#-NInQNAaC8vRePIbY7FG:-NInQNAaC8vRePIbY7FH:b-su0025) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc543b0a94314aa01f45b0d6318b8135bda549ac/pkg/storage/pebble_mvcc_scanner.go#L1083)):*
> ```Go
> // advanceKeyAtNewKeyReverse advances to the key after the key stored in
> // p.machine.origKey in the reverse direction, assuming we have just reached
> // that key.
> ```

I think this should be:
... assuming we have just reached the key after p.machine.origKey in the forward direction.

Though I don't think it uses that invariant in `prevKey(key)`.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93134)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

___
*[`-- commits` line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93134#-NInKvb5BQFgEHcrsjMh):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you elaborate a bit on why this is needed for filter pushdown? It's not at all clear to me.
I am guessing there is some new/future need for stopping the iteration, without stepping the iterator, even when `get one KV` says that iteration can continue.
</blockquote></details>

I expanded the commit message. I'm thinking about hiding the scan in the pushdown work behind the following interface:
```
// NextKVer can fetch a new KV from somewhere. If MVCCDecodingStrategy is set
// to required, the returned KV will include a timestamp.
type NextKVer interface {
	// NextKV returns the next kv from this NextKVer. Returns false if there are
	// no more kvs to fetch, the kv that was fetched, and any errors that may
	// have occurred.
        ...
	NextKV(context.Context, MVCCDecodingStrategy) (
		ok bool, kv roachpb.KeyValue, finalReferenceToBatch bool, err error,
	)
}
```
The split done in this PR will allow us to return the unsafe key-value pair that the iterator is pointing at on each `NextKV` call without having to perform a copy. It's not a big deal for existing `pebbleResults` because there we accumulate all KVs into `repr` buffer, but for the pushdown work it would be a nice optimization - the `cFetcher` (SQL decoder) will be able to pick out only the necessary parts of the KV (and copy only those parts).
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93134#-NInP_k-DPBkMPv8Qf0o:-NIoIVtt5EGVDTBz2vra:b-alhrda) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc543b0a94314aa01f45b0d6318b8135bda549ac/pkg/storage/pebble_mvcc_scanner.go#L404)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This new code is a bit more error prone if something forgets to update `fn`. I don't have a better idea.
</blockquote></details>

I moved some updates into `advance()` - trying to centralize the places where we update the states.
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93134#-NInTl7O4L5hX2To6jKt:-NIo7bCD8qdeLmaaX0hb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc543b0a94314aa01f45b0d6318b8135bda549ac/pkg/storage/pebble_mvcc_scanner.go#L406)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add to this code comment that this is backed by `keyBuf`.
</blockquote></details>

Done.
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 690 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93134#-NInKRMj3nPVugMydLx0:-NIo7g8m5wv7m9PNScgc:bbjucj) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc543b0a94314aa01f45b0d6318b8135bda549ac/pkg/storage/pebble_mvcc_scanner.go#L690)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

will this (ok=true,added=false) case also be used in the future in which filter application will happen here and the item will not be added?
</blockquote></details>

No, at least not with the current approach of injecting SQL decoding logic on top of the MVCC scan. I needed to explicitly return whether a key was skipped to know that there is nothing to return on that `NextKV` (from the new interface) call yet, so we need to advance the iterator further.

In my prototype, I have the following components for the scan with `COL_BATCH_RESPONSE` format:
```
cFetcherWrapper -> mvccScanFetchAdapter -> pebbleMVCCScanner -> MVCCIterator
```
`cFetcherWrapper` is a light wrapper around `cFetcher` that is injected into `storage` package and serializes `coldata.Batch`es (with only needed columns) into the arrow format. `mvccScanFetchAdapter` implements `NextKV` method and provides the access to the unsafe KV pair the iterator is currently pointing at. `pebbleMVCCScanner` and `MVCCIterator` are used exactly as before.

I imagine that in the future when we push the filtering logic into the KV, the chain of components will look like
```
<vectorized filter operators> -> cFetcherWrapper -> mvccScanFetchAdapter -> pebbleMVCCScanner -> MVCCIterator
```
so we just add some filtering on top of `coldata.Batch`es before serializing them into the response.
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 1073 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93134#-NInRqWO6IA6STPS2pft:-NIoHZH9DmQ414QbmQ04:b-uba3es) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc543b0a94314aa01f45b0d6318b8135bda549ac/pkg/storage/pebble_mvcc_scanner.go#L1073)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The old code would immediately call into `prevKey` that would copy again.
Now we call `prevKey` later, which will also make a copy of origKey. Since we are in this code already, I think it's worth optimizing this path. If we lift the copying out of `prevKey` the other caller (`advanceKeyReverse`) will need to make a copy before calling `prevKey`.
</blockquote></details>

Good point, done in a separate commit.
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 1083 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93134#-NInQNAaC8vRePIbY7FG:-NIoCdBl6ZUQzmfY73b1:b-te5d89) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc543b0a94314aa01f45b0d6318b8135bda549ac/pkg/storage/pebble_mvcc_scanner.go#L1083)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think this should be:
... assuming we have just reached the key after p.machine.origKey in the forward direction.

Though I don't think it uses that invariant in `prevKey(key)`.
</blockquote></details>

Looks like it was introduced in 9da5e29b35bb5ff92058c75a8467b60460aafa02, and it seems like the code hasn't been changed, so probably the invariant is still used albeit implicitly.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93134#-:-NIuTGI742b3uHXjjvUH:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @yuzefovich)

___
*[`-- commits` line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93134#-NInKvb5BQFgEHcrsjMh):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I expanded the commit message. I'm thinking about hiding the scan in the pushdown work behind the following interface:
```
// NextKVer can fetch a new KV from somewhere. If MVCCDecodingStrategy is set
// to required, the returned KV will include a timestamp.
type NextKVer interface {
	// NextKV returns the next kv from this NextKVer. Returns false if there are
	// no more kvs to fetch, the kv that was fetched, and any errors that may
	// have occurred.
        ...
	NextKV(context.Context, MVCCDecodingStrategy) (
		ok bool, kv roachpb.KeyValue, finalReferenceToBatch bool, err error,
	)
}
```
The split done in this PR will allow us to return the unsafe key-value pair that the iterator is pointing at on each `NextKV` call without having to perform a copy. It's not a big deal for existing `pebbleResults` because there we accumulate all KVs into `repr` buffer, but for the pushdown work it would be a nice optimization - the `cFetcher` (SQL decoder) will be able to pick out only the necessary parts of the KV (and copy only those parts).
</blockquote></details>

Thanks for the clarification -- makes sense.
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 690 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93134#-NInKRMj3nPVugMydLx0:-NIuRQ0U4HA4ANvmu1kz:b2nhb2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc543b0a94314aa01f45b0d6318b8135bda549ac/pkg/storage/pebble_mvcc_scanner.go#L690)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

No, at least not with the current approach of injecting SQL decoding logic on top of the MVCC scan. I needed to explicitly return whether a key was skipped to know that there is nothing to return on that `NextKV` (from the new interface) call yet, so we need to advance the iterator further.

In my prototype, I have the following components for the scan with `COL_BATCH_RESPONSE` format:
```
cFetcherWrapper -> mvccScanFetchAdapter -> pebbleMVCCScanner -> MVCCIterator
```
`cFetcherWrapper` is a light wrapper around `cFetcher` that is injected into `storage` package and serializes `coldata.Batch`es (with only needed columns) into the arrow format. `mvccScanFetchAdapter` implements `NextKV` method and provides the access to the unsafe KV pair the iterator is currently pointing at. `pebbleMVCCScanner` and `MVCCIterator` are used exactly as before.

I imagine that in the future when we push the filtering logic into the KV, the chain of components will look like
```
<vectorized filter operators> -> cFetcherWrapper -> mvccScanFetchAdapter -> pebbleMVCCScanner -> MVCCIterator
```
so we just add some filtering on top of `coldata.Batch`es before serializing them into the response.
</blockquote></details>

Ack
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 1083 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93134#-NInQNAaC8vRePIbY7FG:-NIuSlxg7u_55gLsFVje:bljbo8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc543b0a94314aa01f45b0d6318b8135bda549ac/pkg/storage/pebble_mvcc_scanner.go#L1083)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Looks like it was introduced in 9da5e29b35bb5ff92058c75a8467b60460aafa02, and it seems like the code hasn't been changed, so probably the invariant is still used albeit implicitly.
</blockquote></details>

You are right -- I reread `prevKey` and it is used. That code could use some code comments which I'll add in the near future.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93134#-:-NIxKGdGC7L2dRJAKg78:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

**Pull request merged**
