### PR TITLE
ui: Import redux functionality from `admin-ui-components`

### PR DESCRIPTION
**Pull request by koorosh**
Depends on https://github.com/cockroachdb/cockroach/pull/52421
Depends on https://github.com/cockroachdb/admin-ui-components/pull/17

Redux functionality is extracted out from project into
`admin-ui-components` package and not it has to be
re-imported back into AdminUI.

Following changes were made:
- `redux` dir is removed from project;
- all redux imports are changed to `@cockroachlabs/admin-ui-components`

Release note: none

### CODE REVIEW

**Comment by dhartunian** [comment]
@koorosh can you speak a bit more to the consequences of storing all the redux code in the external repo? I'm a bit worried that this will make development in Admin UI challenging for all the components that we have yet to pull out.

**Comment by koorosh** [comment]
> @koorosh can you speak a bit more to the consequences of storing all the redux code in the external repo? I'm a bit worried that this will make development in Admin UI challenging for all the components that we have yet to pull out.

 Agree, it affects development for all components. Currently, redux state is monolithic and different components depend on different parts of it and not sliced per feature/page in some independent manner, so I don't see how it can be partially extracted.
Major changes with redux state often accompanied by changes in protobuf API and certainly makes development quite challenging.
Would it be an option to extract all components and then extract redux functionality?

**Comment by dhartunian** [comment]
@koorosh thx for clarifying. Is it possible for Statements Page to use the new imports and for existing components to use the old imports? I understand then there's the danger of the implementations drifting apart which comes with its own set of challenges. Just want to know what the options are.

**Comment by koorosh** [comment]
Not actual anymore.

**Pull request closed without merging**
