### PR TITLE
demo: Add a Movr workload to run in cockroach demo

### LINKED ISSUE #39944: demo: add with-load switch for background workload for loaded dataset
Currently, the web ui for `cockroach demo` doesn't have anything interesting unless you add it. There's nothing in timeseries and nothing in the statements page unless you actually type commands into the shell.

It would be nice for actual demoing purposes if we could add some light background load so that the web ui gets populated with interesting data. This should probably be hidden behind a flag so that data doesn't just change out from under the user unless they're expecting it. The workload should be chosen based on the initial dataset that's loaded.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #39944.

When the `--with-load` flag is passed to demo, a sample movr
workload is run against the database.

I tried my best to replicate the Movr load in Nate's example script.

Based on talks with Dan, it was better to copy out a simpler
version of the logic to run the workload than try to hook
into workload.

Release note (cli change): Add a workload to run with cockroach demo.

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
good stuff

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40271#-:-LnLNFwtEyFSDJLzF6LE:bdc5dhy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @jordanlewis, and @rohany)

___
*[pkg/cli/demo.go, line 209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40271#-LnLLCBP6hcngsaZFWbH:-LnLLCBP6hcngsaZFWbI:b826phu) ([raw file](https://github.com/cockroachdb/cockroach/blob/00ae795c2402c4e4af0e3ece1952458b53a40f1b/pkg/cli/demo.go#L209)):*
> ```Go
> 	}
> 
> 	// TODO (rohany): cleanly cancel the workers -- how to do this?
> ```

I think you should be able to reuse the "stopper" abstraction here, instead of making raw goroutines. This way I think you'll be able to hook into the shutdown of the demo server.

You can get the stopper from the server with `server.Stopper()`. From there, you can spawn tasks with `RunWorker`, which will run a task in a goroutine with a context that will be cancelled when the stopper is stopped.
___
*[pkg/cli/demo.go, line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40271#-LnLMIn8Ek5FB4UYpot_:-LnLMIn9CWqYEq19Zhff:b-6wt810) ([raw file](https://github.com/cockroachdb/cockroach/blob/00ae795c2402c4e4af0e3ece1952458b53a40f1b/pkg/cli/demo.go#L243)):*
> ```Go
> 					}
> 					// TODO (rohany): What to do with this error?
> 					panic(err)
> ```

I'd say log it at warning level and move on. The logs will get added to a temp file soon.
___
*[pkg/cli/demo.go, line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40271#-LnLL-TZCe0NzweaJTV2:-LnLL-T_DI4dfz8GlNQ0:b9jppgm) ([raw file](https://github.com/cockroachdb/cockroach/blob/00ae795c2402c4e4af0e3ece1952458b53a40f1b/pkg/cli/demo.go#L246)):*
> ```Go
> 				}
> 			}
> 		}(workerFn)
> ```

hooray for avoiding the goroutine-captures-loop-variable gotcha.
___
*[pkg/workload/movr/movr.go, line 431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40271#-LnLJzzPEyyBxnH-oDnh:-LnLJzzPEyyBxnH-oDni:bj051kv) ([raw file](https://github.com/cockroachdb/cockroach/blob/00ae795c2402c4e4af0e3ece1952458b53a40f1b/pkg/workload/movr/movr.go#L431)):*
> ```Go
> 
> // Ops implements the Opser interface
> func (g *movr) Ops(urls []string, reg *histogram.Registry) (workload.QueryLoad, error) {
> ```

Awesome! It would be great to get a quick review on this from @nstewart or someone else who knows movr a bit better.
___
*[pkg/workload/movr/movr.go, line 489 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40271#-LnLKW515bzKX1RJWBTb:-LnLKW515bzKX1RJWBTc:b7txxwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/00ae795c2402c4e4af0e3ece1952458b53a40f1b/pkg/workload/movr/movr.go#L489)):*
> ```Go
> 
> 			// Get a random promo code.
> 			q = `SELECT code FROM promo_codes ORDER BY random() LIMIT 1`
> ```

We probably don't want to be doing a ton of order by random, which I believe causes a global sort. The other load generators have methods for keeping track of the max id of various entities, and using a client-generated random number to produce a point query - I think that'd reflect the reality of this app a little bit better.

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40271)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @jordanlewis, and @rohany)

___
*[pkg/cli/demo.go, line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40271#-LnLL-TZCe0NzweaJTV2:-LnLOU9fAwtTFg0OFVpE:btarzjw) ([raw file](https://github.com/cockroachdb/cockroach/blob/00ae795c2402c4e4af0e3ece1952458b53a40f1b/pkg/cli/demo.go#L246)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

hooray for avoiding the goroutine-captures-loop-variable gotcha.
</blockquote></details>

before I address these comments I'll have it be known that i spent an hour and a half trying to debug this

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40271)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @jordanlewis, @nstewart, and @rohany)

___
*[pkg/cli/demo.go, line 209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40271#-LnLLCBP6hcngsaZFWbH:-LnLYx4T88wBMxflr3so:b-5kbax0) ([raw file](https://github.com/cockroachdb/cockroach/blob/00ae795c2402c4e4af0e3ece1952458b53a40f1b/pkg/cli/demo.go#L209)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think you should be able to reuse the "stopper" abstraction here, instead of making raw goroutines. This way I think you'll be able to hook into the shutdown of the demo server.

You can get the stopper from the server with `server.Stopper()`. From there, you can spawn tasks with `RunWorker`, which will run a task in a goroutine with a context that will be cancelled when the stopper is stopped.
</blockquote></details>

Thanks for the pointer!
___
*[pkg/cli/demo.go, line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40271#-LnLMIn8Ek5FB4UYpot_:-LnLYwNp0YhxHpeaV5lX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00ae795c2402c4e4af0e3ece1952458b53a40f1b/pkg/cli/demo.go#L243)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I'd say log it at warning level and move on. The logs will get added to a temp file soon.
</blockquote></details>

Done.
___
*[pkg/workload/movr/movr.go, line 489 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40271#-LnLKW515bzKX1RJWBTb:-LnL_9Ms5BgNxAkWjKM0:b-aq6h2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/00ae795c2402c4e4af0e3ece1952458b53a40f1b/pkg/workload/movr/movr.go#L489)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

We probably don't want to be doing a ton of order by random, which I believe causes a global sort. The other load generators have methods for keeping track of the max id of various entities, and using a client-generated random number to produce a point query - I think that'd reflect the reality of this app a little bit better.
</blockquote></details>

Yeah, this does a global sort. Though I'm not sure of a good way of doing this (the movr demo basically keeps the database in memory as well to do a random selection). Its hard to just use a max id because we could be just running this benchmark for a long time -- we don't want to just stop doing inserts when we hit a max ID.

**Review by nstewart — CHANGES_REQUESTED** [review]
One minor comment, otherwise LGTM

**Review by danhhz — COMMENTED** [review]
I didn't look closely at the actual queryload impl since nate already did. everything else :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40271#-:-LnO0Eiv0b0Acz9BZD2F:be4kzq5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz, @jordanlewis, and @rohany)

___
*[pkg/cli/demo.go, line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40271#-LnLL-TZCe0NzweaJTV2:-LnO09jh5u5HYDkhn5AL:bbn2gq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/00ae795c2402c4e4af0e3ece1952458b53a40f1b/pkg/cli/demo.go#L246)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

before I address these comments I'll have it be known that i spent an hour and a half trying to debug this
</blockquote></details>

someone's really got to write a linter for this. i think it's possible with the new linter stuff
___
*[pkg/cli/demo.go, line 209 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40271#-LnNpoQu8jJQ2Rrc7cVQ:-LnNpoQu8jJQ2Rrc7cVR:b97minh) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c370bec9c44ee3918223777b9e65101aade50e/pkg/cli/demo.go#L209)):*
> ```Go
> 	opser, ok := gen.(workload.Opser)
> 	if !ok {
> 		return errors.New("default dataset does not have a workload defined")
> ```

it's not necessarily the default dataset, right? the user can specify the generator. i'd put gen.Meta().Name in this error message
___
*[pkg/cli/demo.go, line 224 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40271#-LnO-ZeSAGl3_0_-v21w:-LnO-ZeSAGl3_0_-v21x:baxy0ru) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c370bec9c44ee3918223777b9e65101aade50e/pkg/cli/demo.go#L224)):*
> ```Go
> 	// Start a goroutine to run each of the workload functions.
> 	for _, workerFn := range ops.WorkerFns {
> 		workloadFun := func(fun func(context.Context) error) func(context.Context) {
> ```

nit: we're inconsistent about what these are called, but i haven't seen "fun" before. let's not introduce a new one : - )
___
*[pkg/cli/demo.go, line 235 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40271#-LnO-SL-B7oUJWgVrGDt:-LnO-SL-B7oUJWgVrGDu:bxc6zhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c370bec9c44ee3918223777b9e65101aade50e/pkg/cli/demo.go#L235)):*
> ```Go
> 							return
> 						}
> 						panic(err)
> ```

whenever i don't have a real way to handle errors, i like to move everything into one function that returns an error and have the panic/log/whatever only once

```
if err := workFn(); err != nil {
  if errors.Cause(err) == ctx.Err() {
    return
  }
  panic/log
}
```
___
*[pkg/workload/movr/movr.go, line 489 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40271#-LnLKW515bzKX1RJWBTb:-LnNzbmV3C7tDfnhX7I_:bgtef42) ([raw file](https://github.com/cockroachdb/cockroach/blob/00ae795c2402c4e4af0e3ece1952458b53a40f1b/pkg/workload/movr/movr.go#L489)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Yeah, this does a global sort. Though I'm not sure of a good way of doing this (the movr demo basically keeps the database in memory as well to do a random selection). Its hard to just use a max id because we could be just running this benchmark for a long time -- we don't want to just stop doing inserts when we hit a max ID.
</blockquote></details>

generate a random code and SELECT the first one after it (you'll have to retry if it happens to generate a code after the very last code and nothing is after it. or better yet, wrap around and grab the first one)

**Review by rohany — COMMENTED** [review]
Cleanup up the code, and fixed some issues (simple errors, using random() sort).

RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40271#-:-LnObCP-02nt_N1EvrgP:b-un8i92)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @danhhz, @jordanlewis, @nstewart, and @rohany)

___
*[pkg/cli/demo.go, line 235 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40271#-LnO-SL-B7oUJWgVrGDt:-LnOKyfs2-NvK3nn3SA6:b-b3vfob) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c370bec9c44ee3918223777b9e65101aade50e/pkg/cli/demo.go#L235)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

whenever i don't have a real way to handle errors, i like to move everything into one function that returns an error and have the panic/log/whatever only once

```
if err := workFn(); err != nil {
  if errors.Cause(err) == ctx.Err() {
    return
  }
  panic/log
}
```
</blockquote></details>

We need to panic in the case of the limiter erroring, and only log in the case of the workload function erroring, so I don't think I can just do that.
___
*[pkg/workload/movr/movr.go, line 431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40271#-LnLJzzPEyyBxnH-oDnh:-LnOLIDs4Q0uYWI6WozR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00ae795c2402c4e4af0e3ece1952458b53a40f1b/pkg/workload/movr/movr.go#L431)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Awesome! It would be great to get a quick review on this from @nstewart or someone else who knows movr a bit better.
</blockquote></details>

Done.
___
*[pkg/workload/movr/movr.go, line 489 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40271#-LnLKW515bzKX1RJWBTb:-LnObAMn-Mrzyt6CinoF:b-vunp2) ([raw file](https://github.com/cockroachdb/cockroach/blob/00ae795c2402c4e4af0e3ece1952458b53a40f1b/pkg/workload/movr/movr.go#L489)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

generate a random code and SELECT the first one after it (you'll have to retry if it happens to generate a code after the very last code and nothing is after it. or better yet, wrap around and grab the first one)
</blockquote></details>

Thanks -- that works well!
___
*[pkg/workload/movr/movr.go, line 455 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40271#-LnKGOp_ih04fpNAWYS9-r2-455:-LnOLIQY3wQ_e1l3YDBr:bt29wdy) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c370bec9c44ee3918223777b9e65101aade50e/pkg/workload/movr/movr.go#L455)):*
<details><summary><i>Previously, nstewart (Nate) wrote…</i></summary><blockquote>

I think this should be an `else` or break after issuing the read (`SELECT city, id FROM vehicles WHERE city = $1`). As written it looks like if I say read percentage is 100%, I will still do a write every iteration
</blockquote></details>

If we enter the branch with the read query we always return, so if we do a read we don't do a write on that iteration.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40271)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @danhhz, @jordanlewis, @nstewart, and @rohany)

___
*[pkg/cli/demo.go, line 235 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40271#-LnO-SL-B7oUJWgVrGDt:-LnObdWRCYi3rtnZ1uLh:b-d1gg6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c370bec9c44ee3918223777b9e65101aade50e/pkg/cli/demo.go#L235)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

We need to panic in the case of the limiter erroring, and only log in the case of the workload function erroring, so I don't think I can just do that.
</blockquote></details>

gotcha. in that case, the two cases may want a comment
___
*[pkg/workload/movr/movr.go, line 489 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40271#-LnLKW515bzKX1RJWBTb:-LnOdko24JXfcg8Qomqd:b-tdqz3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/00ae795c2402c4e4af0e3ece1952458b53a40f1b/pkg/workload/movr/movr.go#L489)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Thanks -- that works well!
</blockquote></details>

there's certainly a more elegant way to write this, but you can do it in one query:

`select ifnull(a, b) from (select (select code from promo_codes where code > $1 order by code limit 1) as a, (select code from promo_codes order by code limit 1) as b);`

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40271)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @nstewart, and @rohany)

___
*[pkg/workload/movr/movr.go, line 489 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40271#-LnLKW515bzKX1RJWBTb:-LnOt98l-p9b6jdYLdNZ:b-k24nmr) ([raw file](https://github.com/cockroachdb/cockroach/blob/00ae795c2402c4e4af0e3ece1952458b53a40f1b/pkg/workload/movr/movr.go#L489)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

there's certainly a more elegant way to write this, but you can do it in one query:

`select ifnull(a, b) from (select (select code from promo_codes where code > $1 order by code limit 1) as a, (select code from promo_codes order by code limit 1) as b);`
</blockquote></details>

Thanks -- more complicated query makes the other code better

**Comment by nstewart** [comment]
___
*[pkg/workload/movr/movr.go, line 455 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40271#-LnKGOp_ih04fpNAWYS9-r2-455:-LnSqhRF8dT1j0HqCl4P:bpnue6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c370bec9c44ee3918223777b9e65101aade50e/pkg/workload/movr/movr.go#L455)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

If we enter the branch with the read query we always return, so if we do a read we don't do a write on that iteration.
</blockquote></details>

:man_facepalming:  --read too quickly. all set!

**Review by nstewart — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40271)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @nstewart, and @rohany)

**Comment by rohany** [comment]
@danhhz does this look good to you as well?

**Comment by danhhz** [comment]
LGTM

**Comment by rohany** [comment]
TFTR! 

bors r=danhhz,nstewart

**Pull request merged**
