### PR TITLE
sql: fix a bug in the planning of subqueries

### LINKED ISSUE #28335: sql: nested subquery with ARRAY gives "programming error"
```
root@:26257/defaultdb> SELECT (SELECT ARRAY(SELECT 1))[1];
pq: programming error: subquery 3 ("(SELECT 1)") not started prior to evaluation
```

### PR DESCRIPTION
**Pull request by knz**
Fixes #28335.

The heuristic planner would recurse twice into the operand of the
array flatten and ComparisonExpr operators, and cause an invalid plan
to be generated as a result. This patch fixes it.

Release note (sql change): CockroachDB now supports the `ARRAY()`
operator and comparisons with sub-queries on the right side of the
comparison, when they appear themselves in sub-queries.

### CODE REVIEW

**Review by rytaft — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28618#-:-LJxkAko1oGMHmFpbLp1:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/subquery.go, line 332 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28618#-LJxkNwfEUVCRfrSzSel:-LJxkNwg90Bbw7Tw0esv:bp0qi7b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffd3c2c9786cc7d12f035682735dca5e45b0fd31/pkg/sql/subquery.go#L332)):*
> ```Go
> 		switch t.Operator {
> 		case tree.In, tree.NotIn, tree.Any, tree.Some, tree.All:
> 			if sub, ok := t.Right.(*tree.Subquery); ok {
> ```

Do you need to add the same check here, too?

**Review by knz — COMMENTED** [review]
Very keen eye. PTAL.

(I also extended the commit message and release note accordingly)

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28618#-:-LJy6mDEEg6X4FZJNDpz:bplfess)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/subquery.go, line 332 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28618#-LJxkNwfEUVCRfrSzSel:-LJy6iIR4lC3OVqUgE2X:b-kb467i) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0b15b386c48605cd39359aecadcd18bfe538cd/pkg/sql/subquery.go#L332)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Do you need to add the same check here, too?
</blockquote></details>

Oh wow, very good catch!
Done. Also added a test.

**Review by rytaft — APPROVED** [review]
:lgtm: thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28618#-:-LJy7UD636ubzDBb7mpO:brfqlux)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by knz** [comment]
thank you!

bors r+

**Pull request merged**
