### PR TITLE
ui: debug page for localities & locations

### PR DESCRIPTION
**Pull request by couchand**
screen shot 2018-01-18 at 5 39 57 pm

part of the _No Fake Data 2018_ initiative:  loading the location config from the cluster and pairing it up with localities.

### CODE REVIEW

**Comment by vilterp** [comment]
Looks good! Plz just add a test for the `buildLocalityTree` selector.

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/ui/src/redux/cachedDataReducer.ts, line 18 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-L3ABSK0gGDnw_EdtDrc:-L3ABSK0gGDnw_EdtDrd:bqae8tu) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e9bfb135f2cf865f441c23bb32dd332d7aa800/pkg/ui/src/redux/cachedDataReducer.ts#L18)):*
> ```XML
> // CachedDataReducerState is used to track the state of the cached data.
> export class CachedDataReducerState<TResponseMessage> {
>   data?: TResponseMessage; // the latest data received
> ```

so these things were already null/undefined at times, but not just not marked as such here? :man_facepalming: 

---

*[pkg/ui/src/redux/localities.ts, line 7 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-L3AEapFCbhQDilliluk:-L3AEapFCbhQDillilul:b-l93vgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f57ef45ce383b8d476f7f6a0f2e2efc5f5afee30/pkg/ui/src/redux/localities.ts#L7)):*
> ```XML
> import { NodeStatus$Properties } from "src/util/proto";
> 
> function buildLocalityTree(nodes: NodeStatus$Properties[] = [], depth = 0): LocalityTree {
> ```

A test for this guy would be good.

---

*[pkg/ui/src/redux/locations.spec.ts, line 6 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-L3ACsSnRzOZ2SAmq9OO:-L3ACsSnRzOZ2SAmq9OP:bj3ifyk) ([raw file](https://github.com/cockroachdb/cockroach/blob/dddfbe89dcf6d90649c1d3b93c83be1422d0b446/pkg/ui/src/redux/locations.spec.ts#L6)):*
> ```XML
> import { Location, selectLocations, selectLocationTree } from "./locations";
> 
> function climbOutOfTheMorass(loc: Location) {
> ```

this returns a `Location$Properties`? Maybe add an explicit return type to make that more clear.

---

*[pkg/ui/src/views/reports/containers/localities/index.tsx, line 51 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-L3ADcpi3J27slpVEWpa:-L3ADcpi3J27slpVEWpb:bh5nt69) ([raw file](https://github.com/cockroachdb/cockroach/blob/f57ef45ce383b8d476f7f6a0f2e2efc5f5afee30/pkg/ui/src/views/reports/containers/localities/index.tsx#L51)):*
> ```XML
>       rows.push(
>         <tr>
>           <td className={`depth-${depth}`}>{ key }={ value }</td>
> ```

would prefer to do the inline style here, so it's not depth limited and we don't have repetitive classes in the style file. You don't even have to have a nested span: https://github.com/vilterp/dashboard-prototype/blob/2d53150d07869cf71400c637887f42a31c5dd370/src/TreeTable.js#L252

---

*[pkg/ui/src/views/reports/containers/localities/localities.styl, line 38 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-L3AE8k2yoEgQWgVZoiq:-L3AE8k2yoEgQWgVZoir:b-hl3zmg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f57ef45ce383b8d476f7f6a0f2e2efc5f5afee30/pkg/ui/src/views/reports/containers/localities/localities.styl#L38)):*
> ```Stylus
>     border-right 1px solid #ededed
> 
>     &.depth-1
> ```

As I said above, would prefer to use inline style instead of this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-:-L3AEiZEAAop3nieC8Ov:bid14gf)*

**Comment by couchand** [comment]
Review status: 8 of 12 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/ui/src/redux/cachedDataReducer.ts, line 18 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-L3ABSK0gGDnw_EdtDrc:-L3AQrmIqKB8-cJ6k-7D:bcf5heb) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e9bfb135f2cf865f441c23bb32dd332d7aa800/pkg/ui/src/redux/cachedDataReducer.ts#L18)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

so these things were already null/undefined at times, but not just not marked as such here? :man_facepalming: 
</blockquote></details>

I guess.  They initialize without anything but the defaults here... not sure why that's legit enough to TS to never complain.

---

*[pkg/ui/src/redux/localities.ts, line 7 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-L3AEapFCbhQDilliluk:-L3AR1bwpYFLhUbW1mPB:b-dngeeg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f57ef45ce383b8d476f7f6a0f2e2efc5f5afee30/pkg/ui/src/redux/localities.ts#L7)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

A test for this guy would be good.
</blockquote></details>

:+1: will do

---

*[pkg/ui/src/views/reports/containers/localities/index.tsx, line 51 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-L3ADcpi3J27slpVEWpa:-L3AR5dA65Rp7qir1XX8:bty50qr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f57ef45ce383b8d476f7f6a0f2e2efc5f5afee30/pkg/ui/src/views/reports/containers/localities/index.tsx#L51)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

would prefer to do the inline style here, so it's not depth limited and we don't have repetitive classes in the style file. You don't even have to have a nested span: https://github.com/vilterp/dashboard-prototype/blob/2d53150d07869cf71400c637887f42a31c5dd370/src/TreeTable.js#L252
</blockquote></details>

Agreed, just calculating the indent makes sense.  Unfortunately the table cell already has its own padding, so we need to either know it (but DRY!) or add a wrapper component (ugly).  No good answer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553)*

**Comment by vilterp** [comment]
:lgtm: with a couple more tests. Looks good!

---

Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/ui/src/util/locations.ts, line 18 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-L3AT0jSd7yE2idvyGSn:-L3AT0jTtcNuYDrxeinU:b-i721w8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d337a98503da829d4ec0344071ba5e038fa2148/pkg/ui/src/util/locations.ts#L18)):*
> ```XML
> }
> 
> export function findMostSpecificLocation(locations: LocationTree, tiers: LocalityTier[]) {
> ```

a test for this would be good too :+1: 

---

*[pkg/ui/src/views/reports/containers/localities/index.tsx, line 51 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-L3ADcpi3J27slpVEWpa:-L3ASirkO71zirYJDsS0:b-u1kg7k) ([raw file](https://github.com/cockroachdb/cockroach/blob/f57ef45ce383b8d476f7f6a0f2e2efc5f5afee30/pkg/ui/src/views/reports/containers/localities/index.tsx#L51)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

Agreed, just calculating the indent makes sense.  Unfortunately the table cell already has its own padding, so we need to either know it (but DRY!) or add a wrapper component (ugly).  No good answer.
</blockquote></details>

Putting it on a `span` in the `td` seems fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-:-L3ATiVhwZlb81L0YSz7:be3zd2y)*

**Comment by BramGruneir** [comment]
Overall looks good.  Just a few small comments.

Also, can you show some screenshots of examples of when localities are not set nicely?  Different top tier names, or even worse, different number of tiers, or a skipped tier on one node. 

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 5 of 5 files at r5, 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/ui/src/redux/locations.spec.ts, line 8 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-L3Br84gQ86LScdFQVaJ:-L3Br84gQ86LScdFQVaK:b-bs0gam) ([raw file](https://github.com/cockroachdb/cockroach/blob/dddfbe89dcf6d90649c1d3b93c83be1422d0b446/pkg/ui/src/redux/locations.spec.ts#L8)):*
> ```XML
> function climbOutOfTheMorass(loc: Location) {
>   // TODO(couchand): the generated protobuf types are simply horrible
>   return protos.cockroach.server.serverpb.LocationsResponse.Location.fromObject(loc).toObject();
> ```

fromObject().toObject()?  What does this do?

---

*[pkg/ui/src/util/locations.ts, line 6 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-L3BvYCVu27NFNjpKb63:-L3BvYCVu27NFNjpKb64:bdlk9it) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d337a98503da829d4ec0344071ba5e038fa2148/pkg/ui/src/util/locations.ts#L6)):*
> ```XML
> import { LocationTree } from "src/redux/locations";
> 
> export function getLocation(locations: LocationTree, tier: LocalityTier) {
> ```

Would be nice to have a few comments on these functions.

---

*[pkg/ui/src/views/reports/containers/localities/index.tsx, line 88 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-L3Bto28ImyUO1xvnEO6:-L3Bto28ImyUO1xvnEO7:by7m07j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f57ef45ce383b8d476f7f6a0f2e2efc5f5afee30/pkg/ui/src/views/reports/containers/localities/index.tsx#L88)):*
> ```XML
>   render() {
>     return (
>       <section className="section">
> ```

Want to put a loading component in here too? 

---

*[pkg/ui/src/views/reports/containers/localities/localities.styl, line 3 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-L3BuBHItv9MFQQEDEel:-L3BuBHItv9MFQQEDEem:bto79eo) ([raw file](https://github.com/cockroachdb/cockroach/blob/f57ef45ce383b8d476f7f6a0f2e2efc5f5afee30/pkg/ui/src/views/reports/containers/localities/localities.styl#L3)):*
> ```Stylus
> .locality-table
>   width 100%
>   border 1px solid #ededed
> ```

Are these colours available in a pallet anywhere?

---

*[pkg/ui/src/views/reports/containers/localities/localities.styl, line 22 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-L3BshxeKl-0VIp8Sm0K:-L3BshxfgljOR1aaZfMO:b-6hthrw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f57ef45ce383b8d476f7f6a0f2e2efc5f5afee30/pkg/ui/src/views/reports/containers/localities/localities.styl#L22)):*
> ```Stylus
>       text-align left
> 
>       td, th
> ```

Did we not try to keep our depth at 2, following BEM.  Are we not doing that anymore?  (It's been a while since I looked at our styl pages.)  

---

*[pkg/ui/src/views/reports/containers/localities/localities.styl, line 38 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-L3AE8k2yoEgQWgVZoiq:-L3BuJrSOeWo72Nm-Z-E:boo6j3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/f57ef45ce383b8d476f7f6a0f2e2efc5f5afee30/pkg/ui/src/views/reports/containers/localities/localities.styl#L38)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

As I said above, would prefer to use inline style instead of this.
</blockquote></details>

Or a function would work too.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-:-L3BvsFn-XIBa5dKRcl9:b-ey2vrh)*

**Comment by couchand** [comment]
Made changes for most of the comments.  The requested tests & screenshots are coming up shortly.

---

Review status: 2 of 13 files reviewed at latest revision, 9 unresolved discussions.

---

*[pkg/ui/src/redux/locations.spec.ts, line 6 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-L3ACsSnRzOZ2SAmq9OO:-L3U-wZZXnldjoW16xi4:bwdwf2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/dddfbe89dcf6d90649c1d3b93c83be1422d0b446/pkg/ui/src/redux/locations.spec.ts#L6)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

this returns a `Location$Properties`? Maybe add an explicit return type to make that more clear.
</blockquote></details>

according to the generated types, it returns a `{ [key: string]: any }` for some reason.  added that, plus an explanatory comment.

---

*[pkg/ui/src/redux/locations.spec.ts, line 8 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-L3Br84gQ86LScdFQVaJ:-L3U06tVkgrBnLhCcOYe:b-wau21o) ([raw file](https://github.com/cockroachdb/cockroach/blob/dddfbe89dcf6d90649c1d3b93c83be1422d0b446/pkg/ui/src/redux/locations.spec.ts#L8)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

fromObject().toObject()?  What does this do?
</blockquote></details>

added a perhaps-excessively-detailed explanatory comment to this function.

---

*[pkg/ui/src/util/locations.ts, line 6 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-L3BvYCVu27NFNjpKb63:-L3U0B4YGVbQ4SGD1QOg:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d337a98503da829d4ec0344071ba5e038fa2148/pkg/ui/src/util/locations.ts#L6)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Would be nice to have a few comments on these functions.
</blockquote></details>

done.

---

*[pkg/ui/src/views/reports/containers/localities/index.tsx, line 51 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-L3ADcpi3J27slpVEWpa:-L3U60X__mP72fTF3GHT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f57ef45ce383b8d476f7f6a0f2e2efc5f5afee30/pkg/ui/src/views/reports/containers/localities/index.tsx#L51)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

Putting it on a `span` in the `td` seems fine.
</blockquote></details>

Done.

---

*[pkg/ui/src/views/reports/containers/localities/index.tsx, line 88 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-L3Bto28ImyUO1xvnEO6:-L3U2rtgGBISUaKq9Ilt:b-qy3qbu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f57ef45ce383b8d476f7f6a0f2e2efc5f5afee30/pkg/ui/src/views/reports/containers/localities/index.tsx#L88)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Want to put a loading component in here too? 
</blockquote></details>

yes, done.

---

*[pkg/ui/src/views/reports/containers/localities/localities.styl, line 3 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-L3BuBHItv9MFQQEDEel:-L3U3KB0D1xwHpafx9I4:bh2qadx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f57ef45ce383b8d476f7f6a0f2e2efc5f5afee30/pkg/ui/src/views/reports/containers/localities/localities.styl#L3)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Are these colours available in a pallet anywhere?
</blockquote></details>

Yes, made the same comment to Pete offline.  Done.

---

*[pkg/ui/src/views/reports/containers/localities/localities.styl, line 22 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-L3BshxeKl-0VIp8Sm0K:-L3U3s9asMkQopoPVoys:b-d34m5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/f57ef45ce383b8d476f7f6a0f2e2efc5f5afee30/pkg/ui/src/views/reports/containers/localities/localities.styl#L22)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Did we not try to keep our depth at 2, following BEM.  Are we not doing that anymore?  (It's been a while since I looked at our styl pages.)  
</blockquote></details>

I'm not convinced BEM is worth the effort, I'd rather use thoughtful selectors than litter repetitive class names throughout our markup, or perhaps just inline styles, which seem to be where most react devs are headed generally.

That being said, at the moment BEM is still our nominal system of choice, so perhaps I should just use that instead.

---

*[pkg/ui/src/views/reports/containers/localities/localities.styl, line 38 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-L3AE8k2yoEgQWgVZoiq:-L3U61NJHhRKmhvaRO0s:b-v9xew6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f57ef45ce383b8d476f7f6a0f2e2efc5f5afee30/pkg/ui/src/views/reports/containers/localities/localities.styl#L38)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Or a function would work too.  
</blockquote></details>

Went with inline style, seems more obvious.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-:-L3U9Fpq1eeADqfmdpgj:boyp27d)*

**Comment by couchand** [comment]
Tests added, screenshots tomorrow, PTAL

---

Review status: 2 of 16 files reviewed at latest revision, 9 unresolved discussions.

---

*[pkg/ui/src/util/locations.ts, line 18 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-L3AT0jSd7yE2idvyGSn:-L3V39zZnmxykZRHSmqN:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d337a98503da829d4ec0344071ba5e038fa2148/pkg/ui/src/util/locations.ts#L18)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

a test for this would be good too :+1: 
</blockquote></details>

done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-:-L3V3D4VfpQdmzvyHh_-:b5q1bm3)*

**Comment by vilterp** [comment]
re :lgtm:

---

Reviewed 10 of 10 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 2 of 2 files at r10, 5 of 5 files at r11, 4 of 4 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, 3 of 3 files at r15, 3 of 3 files at r16, 2 of 2 files at r17, 1 of 1 files at r18, 1 of 1 files at r19, 2 of 2 files at r20, 1 of 1 files at r21, 1 of 1 files at r22, 1 of 1 files at r23.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-:-L3VCJLclzrRgwifnfOi:b-c8d8b0)*

**Comment by BramGruneir** [comment]
:lgtm:  Awaiting the screenshots.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/ui/src/redux/locations.spec.ts, line 8 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-L3Br84gQ86LScdFQVaJ:-L3WLkVc57WcQmEYOduG:bw8f35b) ([raw file](https://github.com/cockroachdb/cockroach/blob/dddfbe89dcf6d90649c1d3b93c83be1422d0b446/pkg/ui/src/redux/locations.spec.ts#L8)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

added a perhaps-excessively-detailed explanatory comment to this function.
</blockquote></details>

 Nice.  Thanks.

---

*[pkg/ui/src/views/reports/containers/localities/localities.styl, line 22 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-L3BshxeKl-0VIp8Sm0K:-L3WNQs_OcbkOfR9xGXx:b-yu1hf2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f57ef45ce383b8d476f7f6a0f2e2efc5f5afee30/pkg/ui/src/views/reports/containers/localities/localities.styl#L22)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

I'm not convinced BEM is worth the effort, I'd rather use thoughtful selectors than litter repetitive class names throughout our markup, or perhaps just inline styles, which seem to be where most react devs are headed generally.

That being said, at the moment BEM is still our nominal system of choice, so perhaps I should just use that instead.
</blockquote></details>

I was never convinced by BEM, but it should probably be kept for now until we shift to another system.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21553#-:-L3WOc9SO40QG2nVLGEp:b-ibkcx9)*

**Comment by couchand** [comment]
No locality set up:
screen shot 2018-01-23 at 10 01 40 am

Different tier names:
screen shot 2018-01-23 at 10 04 55 am

Different number of tiers:
screen shot 2018-01-23 at 10 08 33 am

(Note in that last one that, since the location is assigned to `city=nyc`, it's picked up for all of them)

**Comment by vilterp** [comment]
🎉

**Comment by knz** [comment]
nit: I am surprised there is no release not in any of these commits. This is a pretty major feature that would deserve mention in the release notes.

**Comment by couchand** [comment]
@knz given that we don't currently document these debug pages (though there is an ongoing discussion to do so), it would seem odd to mention them in the release notes.

**Pull request merged**
