### PR TITLE
sql: add query level execution stats to sampled query log

### PR DESCRIPTION
**Pull request by THardy98**
Partially addresses: #84729

This change adds:
- network bytes sent
- maximum memory usage
- maximum disk usage
- KV bytes read
- KV rows read
- network messages

fields to the `SampledQuery` telemetry log.

Release justification: low risk, high benefit changes to existing functionality

Release note (sql change): This change adds::
- network bytes sent
- maximum memory usage
- maximum disk usage
- KV bytes read
- KV rows read
- network messages fields to the `SampledQuery` telemetry log.

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87527)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @THardy98)

___
*[`pkg/util/log/eventpb/telemetry.proto` line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87527#-NBOUYfc8JWFsBY9Aa7P:-NBOUYfc8JWFsBY9Aa7Q:bx58ats) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad84bed49ea76d67504eead5a81fda38e1990839/pkg/util/log/eventpb/telemetry.proto#L147)):*
> ```protobuf
> 
>   // The number of network bytes sent by nodes for this query.
>   int64 network_bytes_sent = 39 [(gogoproto.jsontag) = ',omitempty'];
> ```

looks like there will be some merge conflicts with https://github.com/cockroachdb/cockroach/pull/87508/files
you and @xinhaoz should coordinate on merges (or one can already rebase on the other)

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87527#-:-NBOstPC0fm45CPle1dx:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @THardy98)

**Review by maryliag — COMMENTED** [review]
you're missing some generated code, you need to run `dev gen` to create the docs

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87527#-:-NBP2OcKALesyITGDXX0:b6yy9oj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @THardy98)

**Comment by THardy98** [comment]
CI failed essential Bazel CI on flakey eslint.sh test. Going to bors.

**Pull request merged**
