### PR TITLE
concurrency: consult finalizedTxnCache when adding discovered lock

### PR DESCRIPTION
**Pull request by sumeerbhola**
The finalizedTxnCache is consulted only when the number of
discovered locks being added is above a certain fraction of
the lock table capacity. When below that fraction, we prefer
to add the lock and consult the finalizedTxnCache in the
following call to ScanAndEnqueue, since that provides some
coordination that de-duplicates intent resolution.

Informs #62470

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
The first commit is from https://github.com/cockroachdb/cockroach/pull/64102

I haven't yet added a test for the change to `managerImpl` -- I want to get an opinion about the `lockTable` heuristic first. The pro is the coordination to reduce duplicate intent resolution. The con is that latches will be reacquired before the `ScanAndEnqueue`, which is wasteful. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64152#-:-MZ-FoVCDC7Fa4pM6SJb:bts29tx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @nvanbenschoten)

**Review by nvb — COMMENTED** [review]
> I want to get an opinion about the lockTable heuristic first. The pro is the coordination to reduce duplicate intent resolution. The con is that latches will be reacquired before the ScanAndEnqueue, which is wasteful.

The other pro is that it allows the lockTable to establish a lockWaitQueue on the contended key, which leads to more orderly and reactive queueing between contending transactions.

I think the heuristic is sane. My only thought would be that it may make sense to decouple it from the lockTable size entirely, and maybe even wrap it up in a private cluster setting. This would be easier to do if the heuristic was moved up to `(*managerImpl).HandleWriterIntentError`, which is the topic of one of my comments below.

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64152#-:-MZEnF6OCW0G8T1Gex4l:b-o0m81n)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @sumeerbhola)

___
*[pkg/kv/kvserver/concurrency/concurrency_manager.go, line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64152#-MZEeQdP94Hktc_KmRvL:-MZEeQdP94Hktc_KmRvM:b-jmqp0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/fafe68b0b0ac192abe1e4ad218662fc8f0990589/pkg/kv/kvserver/concurrency/concurrency_manager.go#L40)):*
> ```Go
> 	lt lockTable
> 	// Waits for locks that conflict with a request to be released.
> 	ltw *lockTableWaiterImpl
> ```

This is unfortunate. Should we add `ResolveDeferredIntents` to the external interface of the `lockTableWaiter` interface?
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 448 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64152#-MZEhGnD4cyraU7K2K0l:-MZEhGnD4cyraU7K2K0m:biudrus) ([raw file](https://github.com/cockroachdb/cockroach/blob/fafe68b0b0ac192abe1e4ad218662fc8f0990589/pkg/kv/kvserver/concurrency/lock_table.go#L448)):*
> ```Go
> }
> 
> func (g *lockTableGuardImpl) DiscoveredLocks(discoveredCount int) {
> ```

Would it make more sense to push this decision up to the caller of `AddDiscoveredLock` and add a new `checkFinalizedTxnCache bool` arg to `AddDiscoveredLock`? As is, this interaction is a little strange, as it's unclear what the purpose of this method is.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 450 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64152#-MZEfYxZ9RaBVkcDi-y9:-MZEfYxZ9RaBVkcDi-yA:b-p8mjjo) ([raw file](https://github.com/cockroachdb/cockroach/blob/fafe68b0b0ac192abe1e4ad218662fc8f0990589/pkg/kv/kvserver/concurrency/lock_table.go#L450)):*
> ```Go
> func (g *lockTableGuardImpl) DiscoveredLocks(discoveredCount int) {
> 	// Consult finalizedTxnCache if discovered more than 5% of capacity. This 5%
> 	// number is somewhat arbitrary. The capacity is 10,000, so 5%, which is 50,
> ```

5% is 500, isn't it? Does that still seem like a good number to you?
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 457 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64152#-MZEeEeK2bhVrVKy2uMC:-MZEeEeK2bhVrVKy2uMD:b-r2hx2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/fafe68b0b0ac192abe1e4ad218662fc8f0990589/pkg/kv/kvserver/concurrency/lock_table.go#L457)):*
> ```Go
> 	g.consultFinalizedTxnCacheForDiscoveredLocks = discoveredCount > int(g.lt.maxLocks)/20
> 	// Defensive: ScanAndEnqueue already empties toResolve, and since this
> 	// request proceeded to evaluation, there must have been any locks to
> ```

"must not have been"
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 2122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64152#-MZEeIun3y6otphD4Mom:-MZEeIun3y6otphD4Mon:bc8iijy) ([raw file](https://github.com/cockroachdb/cockroach/blob/fafe68b0b0ac192abe1e4ad218662fc8f0990589/pkg/kv/kvserver/concurrency/lock_table.go#L2122)):*
> ```Go
> // https://github.com/cockroachdb/cockroach/issues/62470#issuecomment-818374388
> // the possibility of consulting the finalizedTxnCache in AddDiscoveredLock,
> // and not adding the lock if the txn is already finalized, and instead tell
> ```

"telling"
___
*[pkg/kv/kvserver/concurrency/lock_table_test.go, line 146 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64152#-MZEgsbiB94RVs_Ty3NO:-MZEgsbjA8OJ7I1Mv11D:bs9ejok) ([raw file](https://github.com/cockroachdb/cockroach/blob/fafe68b0b0ac192abe1e4ad218662fc8f0990589/pkg/kv/kvserver/concurrency/lock_table_test.go#L146)):*
> ```Go
> 	defer log.Scope(t).Close(t)
> 
> 	intentsToResolveToStr := func(toResolve []roachpb.LockUpdate, startOnNewLine bool) string {
> ```

nit: Does this need to be a closure, or can it be a free function? The latter is preferable because it avoids cluttering the test and doesn't risk accidentally capturing external state.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64152)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 448 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64152#-MZEhGnD4cyraU7K2K0l:-MZIlD8T654afGLfRt9H:bbh6gf9) ([raw file](https://github.com/cockroachdb/cockroach/blob/fafe68b0b0ac192abe1e4ad218662fc8f0990589/pkg/kv/kvserver/concurrency/lock_table.go#L448)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Would it make more sense to push this decision up to the caller of `AddDiscoveredLock` and add a new `checkFinalizedTxnCache bool` arg to `AddDiscoveredLock`? As is, this interaction is a little strange, as it's unclear what the purpose of this method is.
</blockquote></details>

I did consider that interface before I ended up here. The pro here was to hide the heuristic in the implementation of the lock table and make it dependent on `maxLocks` since we are explicitly trying to avoid bloating the table and hitting the `maxLocks` limit. And it allows in the future for more lock table state, like the current number of locks, to be used in the decision making.

But the 5% number is arbitrary (and the calculation is wrong, as you noticed). I can change it to a cluster setting that specifies a lock count. I'm still in two minds about whether to keep this interface or to change it to have the `checkFinalizedTxnCache` argument to `AddDiscoveredLock`.

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64152#-:-MZp2A771-umFa56Z6KC:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @nvanbenschoten)

___
*[pkg/kv/kvserver/concurrency/concurrency_manager.go, line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64152#-MZEeQdP94Hktc_KmRvL:-MZp1TDo9VOz-L8ocW4L:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fafe68b0b0ac192abe1e4ad218662fc8f0990589/pkg/kv/kvserver/concurrency/concurrency_manager.go#L40)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is unfortunate. Should we add `ResolveDeferredIntents` to the external interface of the `lockTableWaiter` interface?
</blockquote></details>

Done
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 450 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64152#-MZEfYxZ9RaBVkcDi-y9:-MZou7wm1b1mPo9gwMpL:b-o2wnzj) ([raw file](https://github.com/cockroachdb/cockroach/blob/fafe68b0b0ac192abe1e4ad218662fc8f0990589/pkg/kv/kvserver/concurrency/lock_table.go#L450)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

5% is 500, isn't it? Does that still seem like a good number to you?
</blockquote></details>

I've set the default in the cluster setting to 200. Happy to change the default to something better.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 457 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64152#-MZEeEeK2bhVrVKy2uMC:-MZolzHl5pM_yZbLQbzz:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fafe68b0b0ac192abe1e4ad218662fc8f0990589/pkg/kv/kvserver/concurrency/lock_table.go#L457)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"must not have been"
</blockquote></details>

Done
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 2122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64152#-MZEeIun3y6otphD4Mom:-MZouEdt494b4iKr-JZp:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fafe68b0b0ac192abe1e4ad218662fc8f0990589/pkg/kv/kvserver/concurrency/lock_table.go#L2122)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"telling"
</blockquote></details>

Done
___
*[pkg/kv/kvserver/concurrency/lock_table_test.go, line 146 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64152#-MZEgsbiB94RVs_Ty3NO:-MZombBP5PVEhn425KRY:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fafe68b0b0ac192abe1e4ad218662fc8f0990589/pkg/kv/kvserver/concurrency/lock_table_test.go#L146)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: Does this need to be a closure, or can it be a free function? The latter is preferable because it avoids cluttering the test and doesn't risk accidentally capturing external state.
</blockquote></details>

Done

**Review by nvb — APPROVED** [review]
> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64152)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @sumeerbhola)

___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 448 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64152#-MZEhGnD4cyraU7K2K0l:-MZpPMMQB9gnAYoMldcN:b-olozzw) ([raw file](https://github.com/cockroachdb/cockroach/blob/fafe68b0b0ac192abe1e4ad218662fc8f0990589/pkg/kv/kvserver/concurrency/lock_table.go#L448)):*
> hide the heuristic in the implementation of the lock table and make it dependent on maxLocks

Does it depend on maxLocks? Right now, we compare against the `LockTableConsultFinalizedTxnCacheForDiscoveredCount` cluster setting, so I know it doesn't compare directly. But even morally, is this threshold a function of the lock table size, or is it orthogonal, having more to do with a tradeoff between avoiding extra work per lock and risking redundant txn pushes? The original comment here seemed to indicate that the two were directly related, but the new comment on the cluster setting paints a more nuanced relationship.

> And it allows in the future for more lock table state, like the current number of locks, to be used in the decision making.

Could you explain how this or other heuristics might be added to this method in the future? If the decision is entirely based on state passed in from the caller (num locks discovered), then I'm also not sure that it makes sense to complicate the `lockTableGuard` interface and obscure this fact in the process. But if it does incorporate lockTable state, I can understand this more.
___
*[pkg/kv/kvserver/concurrency/testdata/concurrency_manager/clear_abandoned_intents_without_adding_to_lock_table, line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64152#-MZpSlkT5xFXKU-C9t8C:-MZpSlkT5xFXKU-C9t8D:b-92hlen) ([raw file](https://github.com/cockroachdb/cockroach/blob/be0d95fc9c249308c3bb84dc814351ff4ad57389/pkg/kv/kvserver/concurrency/testdata/concurrency_manager/clear_abandoned_intents_without_adding_to_lock_table#L91)):*
> ```
> 
> # The intents get resolved instead of being added to the lock table.
> handle-write-intent-error req=req2 lease-seq=1
> ```

These tests are always very satisfying to read!

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64152)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 448 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64152#-MZEhGnD4cyraU7K2K0l:-MZrUf2U7kMCJR8PSCUc:b6hwz69) ([raw file](https://github.com/cockroachdb/cockroach/blob/fafe68b0b0ac192abe1e4ad218662fc8f0990589/pkg/kv/kvserver/concurrency/lock_table.go#L448)):*
> Does it depend on maxLocks? ... But even morally, is this threshold a function of the lock table size, or is it orthogonal, having more to do with a tradeoff between avoiding extra work per lock and risking redundant txn pushes?

It doesn't now with the cluster setting. But morally, yes the lock table size factors in, which is why it is mentioned in the code comment for `LockTableConsultFinalizedTxnCacheForDiscoveredCount`. I've also added it to the description since that is what someone adjusting this will see.

An alternative would be to make this a percentage of the lock table capacity, but then it could potentially become too small for reasonable size transactions.

> Could you explain how this or other heuristics might be added to this method in the future?

I was speculating there, and we can change the interface again if needed when adding more heuristics. My main thought had been that the `finalizedTxnCache` is in the lock table, and the capacity knowledge is in the same place, and we may want the max to be a fraction of the capacity (explicitly or implied via comments), so better to hide the decision there too.

But I don't have a strong opinion, and honestly I am having a hard time judging in this case where I am crossing the line of over-thinking, so if you have a strong opinion I am fine with changing the code to match.

**Comment by sumeerbhola** [comment]
Once this PR is finalized, I'm going to squash this commit into the one in https://github.com/cockroachdb/cockroach/pull/64102 before merging.

The other PR has failures in TestStatsWithLowTTL that I cannot reproduce locally, but happen frequently enough on CI (though now have stopped there too), which I've traced to a large numbers of intents being seen by the stats code, and suggest that clearing of these locks is slowing down progress in the stats code which makes it run afoul of GC. I've never seen that failure on this PR, that contains both commits, which suggests that the intents being seen are mostly from finalized transactions.
```
I210503 20:53:31.858831 219135 jobs/registry.go:1132 â‹® [n1] 91  CREATE STATS job â€¹655375767439376385â€º: stepping through state running with error: <nil>
I210503 20:53:32.497437 219136 kv/kvserver/concurrency/lock_table.go:2282 â‹® [-] 92  lockTable trying to clear 5192 locks
I210503 20:53:32.498292 219136 kv/kvserver/concurrency/lock_table.go:2302 â‹® [-] 93  lockTable clearing 5192 locks
I210503 20:53:32.512675 219136 kv/kvserver/concurrency/lock_table.go:2282 â‹® [-] 94  lockTable trying to clear 5250 locks
I210503 20:53:32.513301 219136 kv/kvserver/concurrency/lock_table.go:2302 â‹® [-] 95  lockTable clearing 5250 locks
I210503 20:53:32.528776 219136 kv/kvserver/concurrency/lock_table.go:2282 â‹® [-] 96  lockTable trying to clear 5250 locks
I210503 20:53:32.529702 219136 kv/kvserver/concurrency/lock_table.go:2302 â‹® [-] 97  lockTable clearing 5250 locks
I210503 20:53:32.545219 219136 kv/kvserver/concurrency/lock_table.go:2282 â‹® [-] 98  lockTable trying to clear 5250 locks
I210503 20:53:32.545796 219136 kv/kvserver/concurrency/lock_table.go:2302 â‹® [-] 99  lockTable clearing 5250 locks
I210503 20:53:33.224190 219136 kv/kvserver/concurrency/lock_table.go:2282 â‹® [-] 100  lockTable trying to clear 5046 locks
I210503 20:53:33.224843 219136 kv/kvserver/concurrency/lock_table.go:2302 â‹® [-] 101  lockTable clearing 5046 locks
I210503 20:53:33.345391 219136 kv/kvserver/concurrency/lock_table.go:2282 â‹® [-] 102  lockTable trying to clear 5250 locks
I210503 20:53:33.346003 219136 kv/kvserver/concurrency/lock_table.go:2302 â‹® [-] 103  lockTable clearing 5250 locks
I210503 20:53:33.621478 219135 jobs/registry.go:1132 â‹® [n1] 104  CREATE STATS job â€¹655375767439376385â€º: stepping through state reverting with error: â€¹batch timestamp 1620075211.740242507,0 must be after replica GC threshold 1620075212.452918536,0â€º
I210503 20:53:33.621478 219135 jobs/registry.go:1132 â‹® [n1] 104 +(1) â€¹batch timestamp 1620075211.740242507,0 must be after replica GC threshold 1620075212.452918536,0â€º
I210503 20:53:33.621478 219135 jobs/registry.go:1132 â‹® [n1] 104 +Error types: (1) *roachpb.BatchTimestampBeforeGCError
```

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64152)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 448 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64152#-MZEhGnD4cyraU7K2K0l:-MZxgUTYALliMzRWoBek:bt389ub) ([raw file](https://github.com/cockroachdb/cockroach/blob/fafe68b0b0ac192abe1e4ad218662fc8f0990589/pkg/kv/kvserver/concurrency/lock_table.go#L448)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> Does it depend on maxLocks? ... But even morally, is this threshold a function of the lock table size, or is it orthogonal, having more to do with a tradeoff between avoiding extra work per lock and risking redundant txn pushes?

It doesn't now with the cluster setting. But morally, yes the lock table size factors in, which is why it is mentioned in the code comment for `LockTableConsultFinalizedTxnCacheForDiscoveredCount`. I've also added it to the description since that is what someone adjusting this will see.

An alternative would be to make this a percentage of the lock table capacity, but then it could potentially become too small for reasonable size transactions.

> Could you explain how this or other heuristics might be added to this method in the future?

I was speculating there, and we can change the interface again if needed when adding more heuristics. My main thought had been that the `finalizedTxnCache` is in the lock table, and the capacity knowledge is in the same place, and we may want the max to be a fraction of the capacity (explicitly or implied via comments), so better to hide the decision there too.

But I don't have a strong opinion, and honestly I am having a hard time judging in this case where I am crossing the line of over-thinking, so if you have a strong opinion I am fine with changing the code to match.

</blockquote></details>

I think my preference is to switch to a `checkFinalizedTxnCache` flag. I'm also mostly torn, but the main thing that concerns me is the new hidden state on the `lockTableGuardImpl` (`consultFinalizedTxnCacheForDiscoveredLocks`). It seems unfortunate to promote what should be a local variable in `managerImpl.HandleWriterIntentError` to something more. If we did want to have the `lockTable` make this decision, I'd almost prefer an immutable `ShouldCheckFinalizedTxnCache` method on the `lockTable` which returns a `bool` that can then be passed to `AddDiscoveredLock`.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64152)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 448 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64152#-MZEhGnD4cyraU7K2K0l:-MZyMQHqCZI9OBNREhLI:b-l3x1gi) ([raw file](https://github.com/cockroachdb/cockroach/blob/fafe68b0b0ac192abe1e4ad218662fc8f0990589/pkg/kv/kvserver/concurrency/lock_table.go#L448)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think my preference is to switch to a `checkFinalizedTxnCache` flag. I'm also mostly torn, but the main thing that concerns me is the new hidden state on the `lockTableGuardImpl` (`consultFinalizedTxnCacheForDiscoveredLocks`). It seems unfortunate to promote what should be a local variable in `managerImpl.HandleWriterIntentError` to something more. If we did want to have the `lockTable` make this decision, I'd almost prefer an immutable `ShouldCheckFinalizedTxnCache` method on the `lockTable` which returns a `bool` that can then be passed to `AddDiscoveredLock`.
</blockquote></details>

I've moved this to `managerImpl` in https://github.com/cockroachdb/cockroach/pull/64102
PTAL

**Pull request closed without merging**
