### PR TITLE
ccl/sqlproxyccl: add support for moving connections away from DRAINING pods

### PR DESCRIPTION
**Pull request by jaylim-crl**
In #79346, we added a rebalancer queue for connection rebalancing. This commit
adds support for transferring connections away from DRAINING pods. The
rebalance loop runs once every 30 seconds for now, and connections will only be
moved away from DRAINING pods if the pod has been draining for at least 1
minute.

At the same time, we also fix an enqueue bug on the rebalancer queue where
we're releasing the semaphore in the case of an update, which is incorrect.

Release note: None

### CODE REVIEW

**Review by jeffswenson — APPROVED** [review]
LGTM :100:

**Comment by jaylim-crl** [comment]
TFTR! (and rebased)

**Comment by jaylim-crl** [comment]
bors r=JeffSwenson

**Review by andy-kimball — APPROVED** [review]
:lgtm:, very nice work. I've just got some nits and suggestions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79725#-:-N-R9O4DE1-3x4qTuEk8:bmn0cd4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @jaylim-crl)

___
*[pkg/ccl/sqlproxyccl/balancer/balancer.go, line 281 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79725#-N-R26Bn0_sDCu1fAE1m:-N-R26Bn0_sDCu1fAE1n:bd7p8xp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2efd2602da92ac6bcd8d54e117b5cb57df556800/pkg/ccl/sqlproxyccl/balancer/balancer.go#L281)):*
> ```Go
> // coming from the pod watcher.
> func (b *Balancer) rebalance(ctx context.Context) {
> 	// getAllConns ensures that tenants will have at least one connection.
> ```

NIT: getAllConns => GetAllCons
___
*[pkg/ccl/sqlproxyccl/balancer/balancer.go, line 282 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79725#-N-R4pzX-ou29q4UDNMf:-N-R4pzX-ou29q4UDNMg:bxmij6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/2efd2602da92ac6bcd8d54e117b5cb57df556800/pkg/ccl/sqlproxyccl/balancer/balancer.go#L282)):*
> ```Go
> func (b *Balancer) rebalance(ctx context.Context) {
> 	// getAllConns ensures that tenants will have at least one connection.
> 	tenantConns := b.connTracker.GetAllConns()
> ```

There are a lot of objects being created here, both in GetAllConns and in the below loop. Are you sure there is no clean way to reduce the number of transformations from one kind of map to another simply in order to iterate?

It probably doesn't matter, since we only run this every 30 seconds, but if there's something relatively easy/cheap, it might be worth looking for. For example, maybe there'd be a `ConnTracker.GetTenants` that returns a slice of tenants with connections. Then you'd iterate over that and call a `GetConnsByPod` method to get that tenant's pods, indexed by address. This would avoid allocating large objects, would minimize the scope of locks, and would avoid extra allocations to copy objects from map to map.

One other nit I noticed when looking at ConnTracker: the `GetConns` method is forcing creation of a tenant entry, which doesn't seem right, if the `tenantID` is not already present in the tracker.
___
*[pkg/ccl/sqlproxyccl/balancer/balancer.go, line 335 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79725#-N-R3KD89UUX2gMzU5OM:-N-R3KD89UUX2gMzU5ON:b5dw5rm) ([raw file](https://github.com/cockroachdb/cockroach/blob/2efd2602da92ac6bcd8d54e117b5cb57df556800/pkg/ccl/sqlproxyccl/balancer/balancer.go#L335)):*
> ```Go
> 			}
> 
> 			// Transfer all connections in DRAINING pods.
> ```

NIT: Should the DRAINING case be extracted as a separate function that will eventually live alongside a function that looks for connections to overloaded pods?

**Review by jaylim-crl — COMMENTED** [review]
TFTR! Addressed all the nits in https://github.com/cockroachdb/cockroach/pull/79857.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79725#-:-N-UFXoSAQdD8jy1r89d:b-n179mk)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/ccl/sqlproxyccl/balancer/balancer.go, line 281 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79725#-N-R26Bn0_sDCu1fAE1m:-N-UFaal9rIWznKcrQCO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2efd2602da92ac6bcd8d54e117b5cb57df556800/pkg/ccl/sqlproxyccl/balancer/balancer.go#L281)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: getAllConns => GetAllCons
</blockquote></details>

Done.
___
*[pkg/ccl/sqlproxyccl/balancer/balancer.go, line 282 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79725#-N-R4pzX-ou29q4UDNMf:-N-UFkFUDnAwhOuCgEkH:baehb5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/2efd2602da92ac6bcd8d54e117b5cb57df556800/pkg/ccl/sqlproxyccl/balancer/balancer.go#L282)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

There are a lot of objects being created here, both in GetAllConns and in the below loop. Are you sure there is no clean way to reduce the number of transformations from one kind of map to another simply in order to iterate?

It probably doesn't matter, since we only run this every 30 seconds, but if there's something relatively easy/cheap, it might be worth looking for. For example, maybe there'd be a `ConnTracker.GetTenants` that returns a slice of tenants with connections. Then you'd iterate over that and call a `GetConnsByPod` method to get that tenant's pods, indexed by address. This would avoid allocating large objects, would minimize the scope of locks, and would avoid extra allocations to copy objects from map to map.

One other nit I noticed when looking at ConnTracker: the `GetConns` method is forcing creation of a tenant entry, which doesn't seem right, if the `tenantID` is not already present in the tracker.
</blockquote></details>

Done. Good point about the extra allocations and transformations. re: scope of locks, that may not be relevant here since the previous design obtained a snapshot of tenants before copying the individual tenant conns, so we're not holding onto the lock for a long time.
___
*[pkg/ccl/sqlproxyccl/balancer/balancer.go, line 335 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79725#-N-R3KD89UUX2gMzU5OM:-N-UFb5b0bh94RtHocEX:bdz52iz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2efd2602da92ac6bcd8d54e117b5cb57df556800/pkg/ccl/sqlproxyccl/balancer/balancer.go#L335)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: Should the DRAINING case be extracted as a separate function that will eventually live alongside a function that looks for connections to overloaded pods?
</blockquote></details>

Hm, it's currently unclear how the other function will look like yet, so I left this as a TODO in the other PR, but consider this done. We will extract this out once we have a clearer idea.

**Comment by jaylim-crl** [comment]
blathers backport 22.1

**Pull request merged**
