### PR TITLE
roachtest: test our expected max tpcc warehouses

### PR DESCRIPTION
**Pull request by danhhz**
This 3 node, 16 cpu roachtest verifies our expected max warehouses. Also
remove the old warehouse=1 tests.

Release note: None

### CODE REVIEW

**Review by nvb — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30574)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/tpcc.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30574#-LNBS6iLAjlzffiVOi7J:-LNBS6iM7KE4Vit9zAaZ:b-yw8bz8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d304bc85e800b9c0e49b2cc659bcb82801e30bd/pkg/cmd/roachtest/tpcc.go#L67)):*
> ```Go
> 		Stable: true, // DO NOT COPY to new tests
> 		Run: func(ctx context.Context, t *test, c *cluster) {
> 			runTPCC(ctx, t, c, 1, " --wait=false")
> ```

We shouldn't get rid of the `--wait=false` test. That's still useful.
___
*[pkg/cmd/roachtest/tpcc.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30574#-LNBSKpx1oewVCHypAI_:-LNBSKpx1oewVCHypAIa:b-w2lfhc) ([raw file](https://github.com/cockroachdb/cockroach/blob/226f855cb58c9764d57794abc3f22ac24e0fd064/pkg/cmd/roachtest/tpcc.go#L88)):*
> ```Go
> 		Stable:     false,
> 		Run: func(ctx context.Context, t *test, c *cluster) {
> 			warehouses := 1500
> ```

Drop this down to 1400. We haven't demonstrated that we're able to consistently and reliably run 1500 warehouses for 2h in this configuration.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30574)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/tpcc.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30574#-LNBS6iLAjlzffiVOi7J:-LNBVXDb16SxmcSpnQsz:bv5mtld) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d304bc85e800b9c0e49b2cc659bcb82801e30bd/pkg/cmd/roachtest/tpcc.go#L67)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We shouldn't get rid of the `--wait=false` test. That's still useful.
</blockquote></details>

Why? I thought we moved away from --wait=false pretty much immediately
___
*[pkg/cmd/roachtest/tpcc.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30574#-LNBSKpx1oewVCHypAI_:-LNBVeGVAJZnUm3KuhUL:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/226f855cb58c9764d57794abc3f22ac24e0fd064/pkg/cmd/roachtest/tpcc.go#L88)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Drop this down to 1400. We haven't demonstrated that we're able to consistently and reliably run 1500 warehouses for 2h in this configuration.
</blockquote></details>

Done

**Review by nvb — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30574)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/tpcc.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30574#-LNBS6iLAjlzffiVOi7J:-LNBcuy_6nT_D1xyzqUo:bjkiits) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d304bc85e800b9c0e49b2cc659bcb82801e30bd/pkg/cmd/roachtest/tpcc.go#L67)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Why? I thought we moved away from --wait=false pretty much immediately
</blockquote></details>

It's still an interesting benchmark configuration. We'll want it when we hook this up to roachtest so we can actually see the effect of performance changes.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30574)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/tpcc.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30574#-LNBS6iLAjlzffiVOi7J:-LNBrEqb3FfXSbCxpCnA:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d304bc85e800b9c0e49b2cc659bcb82801e30bd/pkg/cmd/roachtest/tpcc.go#L67)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's still an interesting benchmark configuration. We'll want it when we hook this up to roachtest so we can actually see the effect of performance changes.
</blockquote></details>

Done

**Review by nvb — APPROVED** [review]

**Comment by danhhz** [comment]
TFTR!

bors r=nvanbenschoten

**Pull request merged**
