### PR TITLE
sql/parser: Add Date, TS, and Interval to StrVal's res type set

### LINKED ISSUE #6772: cannot insert/query java.sql.Timestamp without TIMESTAMP in query
I160518 12:17:55.038179 util/log/clog.go:998  [config] file created at: 2016/05/18 12:17:55
I160518 12:17:55.038179 util/log/clog.go:998  [config] running on machine: ip-10-2-1-85
I160518 12:17:55.038179 util/log/clog.go:998  [config] binary: CockroachDB beta-20160512 (linux amd64, built 2016/05/12 15:50:23, go1.6)
I160518 12:17:55.038179 util/log/clog.go:998  [config] arguments: [cockroach start --insecure --background --cache=2GiB --attrs=us-east-1c --background=false]

Hi, im playing around with java and latest psql driver

```
<dependency>
    <groupId>org.postgresql</groupId>
    <artifactId>postgresql</artifactId>
    <version>9.4.1208</version>
</dependency>
<dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-jdbc</artifactId>
    <version>4.2.6.RELEASE</version>
</dependency>
```

I am trying insert simple data with timestamp. and here is the thing that spring is not able to prepare valid statement. cockroach db is always responding with error messages, no matter if query reads or writes.

for a insert produced by spring from prepared statement
```
INSERT INTO clients_balance (id, client_id, balance, settled) 
VALUES ('K1', 'C1', '7.9938673', '2016-5-17 18:22:4.303000 +2:0:0')
```
db returns
> PSQLException: ERROR: param $4: could not parse string "2016-5-17 18:22:4.303000 +2:0:0" as timestamp

the query above is not working even in db's sql console.

Now the workaround is simple (after reading closer documentation :)
```
INSERT INTO clients_balance (id, client_id, balance, settled) 
VALUES ('K1', 'C1', '7.9938673', TIMESTAMP '2016-05-17 18:22:4.303000+02:0:0')
```
the difference is additional 0 near month and time zone and space near zone's + sign.

So I am a bit confused, on one hand queries work and I was able to add/read/update from my application, on the other it is really first time I had to go to low level sql. I was using postgresql for some time and I had never problems with spring wrapper. It is like cockroachdb is very strict comparing to postgresql when it comes to parsing queries. I thought db engine should be smart enough to parse string as timezone just looking at schema.

still I don't know if this is a bug or not. rather something I didn't expect. Or maybe I missed something. 
just thought might help.

### PR DESCRIPTION
**Pull request by nvb**
Fixes #6772.

This change adds the types `DATE`, `TIMESTAMP`, `TIMESTAMPTZ`, and
`INTERVAL` to the resolvable type set of `StrVal`. This means that if
one of those types is desired from a `StrVal`, it will be able to
resolve itself to that type, obviating the need for a cast.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6925)

### CODE REVIEW

**Comment by dt** [comment]
:lgtm:

<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> #### sql/parser: Add Date, TS, and Interval to StrVal&#39;s res type set
> 
> Fixes #6772.
> 
> 
> 
> This change adds the types `DATE`, `TIMESTAMP`, `TIMESTAMPTZ`, and
> 
> `INTERVAL` to the resolvable type set of `StrVal`. This means that if
> 
> one of those types is desired from a `StrVal`, it will be able to
> 
> resolve itself to that type, obviating the need for a cast.
> 
> 
> 
</details>


---

Reviewed 5 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/parser/constant_test.go, line 188 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6925#-KIiY13iDuRnHhqUIhlu:-KIiY13iDuRnHhqUIhlv:1130037072) ([raw file](https://github.com/cockroachdb/cockroach/blob/347c1d60d20a013609e677676056122843690606/sql/parser/constant_test.go#L188)):*
> ```Go
> 	d, err := ParseDDate(s, time.UTC)
> 	if err != nil {
> 		panic(err)
> ```

optional nit: plumb a `testing.T` in here and call `t.Fatal()` instead of panic

---

*[sql/testdata/datetime, line 13 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6925#-KIiQZECjby64c-36pro:-KIiQZECjby64c-36prp:215643957) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad4dff4bbfd6dad5ed41919a1fa1d2b852b2191a/sql/testdata/datetime#L13)):*
> ```
> statement ok
> INSERT INTO t VALUES
>   ('2015-08-30 03:34:45.34567'::timestamp, '2015-08-30'::date, '34h2s'::interval),
> ```

its_so_beautiful_crying_meme.jpg

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6925#-:-KIiYb2aTenkhdmV3qwa:1417088721)*

**Comment by paperstreet** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/testdata/datetime, line 10 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6925#-KIiZ0tGzrgmj22vVKQ9:-KIiZ0tH007mbTzaiZmC:900139631) ([raw file](https://github.com/cockroachdb/cockroach/blob/347c1d60d20a013609e677676056122843690606/sql/testdata/datetime#L10)):*
> ```
> )
> 
> # TODO(vivek) replace timestamp/date/interval type casting in this file.
> ```

is this what the these TODOs mean? can you delete them?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6925)*

**Comment by nvanbenschoten** [comment]
TFTRs!

<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> :lgtm:
</details>


---

Review status: 4 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/parser/constant_test.go, line 188 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6925#-KIiY13iDuRnHhqUIhlu:-KIi_hrHvlsE4WTZFdpk:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/347c1d60d20a013609e677676056122843690606/sql/parser/constant_test.go#L188)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> optional nit: plumb a `testing.T` in here and call `t.Fatal()` instead of panic
</details>
Done.

---

*[sql/testdata/datetime, line 10 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6925#-KIiZ0tGzrgmj22vVKQ9:-KIi_nyhh6KWLmJJDg4a:-1630632253) ([raw file](https://github.com/cockroachdb/cockroach/blob/347c1d60d20a013609e677676056122843690606/sql/testdata/datetime#L10)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> is this what the these TODOs mean? can you delete them?
</details>
Looks like it. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6925#-:-KIi_fzFHgjiI7B1v8M6:2125754307)*

**Comment by dt** [comment]
Reviewed 1 of 3 files at r3.
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6925)*

**Comment by dt** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6925)*

**Comment by jseldess** [comment]
Updated `date`, `timestamp`, and `interval` docs with https://github.com/cockroachdb/docs/pull/351

**Pull request merged**
