### PR TITLE
logictest: refactor monolithic `TestLogic` targets into many subtests

### LINKED ISSUE #77204: bazel: `dev testlogic base` fetches the large sqllogictest archives unnecessarily
**Describe the problem**

I ran `dev testlogic base --filter=role` and this failed because I didn't have an internet connection (??)
Then after I restored connectivity, I had to wait for a 100MB download of `sqllogictest-96138842571462ed9a697bff590828d8f6356a2f.tar.gz`, which is totally unneeded for this command.

`make testbaselogic FILES=role` does not incur this extra work.

Epic CRDB-8036

Jira issue: CRDB-13472

### LINKED ISSUE #77456: bazel,logictest: top-level test per something, maybe config
**Is your feature request related to a problem? Please describe.**

Logic tests having a single config hurts because we can't shard in bazel. To fix it, we need more top-level tests.

**Describe the solution you'd like**

A solution is to create a top-level test per config. This is sort of painful because we invoke the same set of configs in multiple packages which each involve different sets of testdata files. I'm not totally sure how to solve that problem. Maybe we codegen that? 

**Describe alternatives you've considered**
If we're going to codegen at all, I'd rather codegen based on the files than the configs because the configs are in go and to parse them out is much more complex. 

If we don't want to code-gen, I'm not sure what else we can really do. Maybe there's a way to write a new test runner.

Jira issue: CRDB-13601

### PR DESCRIPTION
**Pull request by rickystewart**
The monolithic `TestLogic` test (and its corollaries, found in
`pkg/ccl/logictestccl` and `pkg/sql/opt/exec/execbuilder`) is very prone
to timing out under Bazel as the subtests cannot be parallelized by the
Bazel test runner. Furthermore, it can be difficult to debug failures in
individual subtests as the logs for each parallel subtest are all
intermingled. To solve this problem we generate finer-grained tests
for each of the subtests that would otherwise be run in the monolithic
`TestLogic` test. To that end we do all of the following:

1. Split out some common helper logic into the subpackage
   `pkg/sql/logictest/logictestbase`.
2. Refactor the logic test machinery. Up until this point, the
   `RunLogicTest` function (and related functions) have dynamically
   enumerated the subtests from `testdata` and spawned a subtest with
   `t.Run()` for each. Instead, `RunLogicTest` now takes a specific
   configuration index and a path to one test file.
3. Restructure the logictests as follows: split out the long-running
   sqlite logic tests into their own packages, `pkg/sql/sqlitelogictest`
   and `pkg/ccl/sqlitelogictestccl`; for each logictest configuration X,
   create a subpackage `tests/X` to house all tests for that
   configuration; for each logictest file Y, create a test
   `LogicTest_X_Y` that tests that one specific file. We do this not
   only for `pkg/sql/logictest` but also for `pkg/ccl/logictestccl` and
   `pkg/sql/opt/exec/execbuilder`.
4. Create a helper binary that generates all of these test files and
   integrate into `bazel-generate.sh`.
5. Update `Makefile` and `dev` to change how they execute logic tests.
6. Update some TeamCity scripts to change how they execute logic tests.
   Update `bazci` accordingly.
7. Delete now-irrelevant TeamCity scripts from `build`.

This has some breaking changes for developers:
1. Developers using `make testlogic` or `dev testlogic` should generally
   not be affected as these frontends are ported to the new test API's.
2. Developers used to running
     `dev test pkg/sql/logictest -f TestLogic/config-name/file-name/subtest`
   or the equivalent
     `make test ./pkg/sql/logictest TESTS=TestLogic/config-name/file-name/subtest`
   will now instead have to run:
     `dev test pkg/sql/logictest/tests/config-name -f TestLogic_file_name/subtest`
   or
     `make test ./pkg/sql/logictest/tests/config-name TESTS=TestLogic_file_name/subtest`
   In particular we point to the following important differences:
   * In the `file-name`, replace - and . with an underscore (_). If the
     filename has a slash, omit it entirely.
   * Use underscores instead of / in between the function name prefix,
     and the file name. All of these are baked into the actual Go test
     (function) name so we need to use _.
   * Don't include the config-name in the test filter; it's redundant.
   Note that if you just want to test all the tests in a directory with
   a particular config, the test filter is no longer necessary, so you
   can just do e.g. `dev test pkg/sql/logictest/tests/local`. The filter
   is necessary only if you want to test a particular file or subtest.
3. The same as above applies for logic tests in `pkg/ccl/logictestccl` and
   `pkg/sql/opt/exec/execbuilder`, as in
   `dev test pkg/sql/opt/exec/execbuilder/tests/local -f TestExecBuild_autocommit`.
4. Sqlite logic tests are split out into their own directory
   (`pkg/sql/sqlitelogictest` and `pkg/ccl/sqlitelogictestccl`) with the
   same test layout as above, like
   `dev test pkg/sql/sqlitelogictest/tests/local ...`
5. `dev testlogic` will now unconditionally regenerate these test files
   before running the logic test, and `dev test` will do the same if the
   test is a logic test target. This behavior can be skipped with
   `--no-gen`.

Closes https://github.com/cockroachdb/cockroach/issues/77204.
Closes https://github.com/cockroachdb/cockroach/issues/77456.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
It's hard for me to explain just how much better this is going to make the lives of a great many people. Thanks for doing this! My initial commentary is extremely surface-level and really just nudges to take another pass on the generation code for future maintainability. I want to check this out and play with it!

> Reviewed 16 of 130 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84221#-:-N7Hpvpy3oJtn5hkfAiX:b6yvrqo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rail, @rickystewart, and @rytaft)

___
*[`pkg/cmd/generate-logictest/main.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84221#-N7HoLNG-k62zXGpvvun:-N7HoLNG-k62zXGpvvuo:b-qbw2o2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6b1edc5d14873e2776e554cd2b48d278df529e0/pkg/cmd/generate-logictest/main.go#L27)):*
> ```Go
> )
> 
> const testFileTemplate = `{{ if .Ccl }}// Copyright 2012 The Cockroach Authors.
> ```

do you know about the whitespace suppression markers in text template? They can make the templates easier to read.

https://pkg.go.dev/text/template#hdr-Text_and_spaces 

Also, sub-templates. If I'm being nit-picky, I think this would all be much easier to read if you split out a separate file and defined a bunch of smaller templates. 
___
*[`pkg/cmd/generate-logictest/main.go` line 293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84221#-N7HpdCPBjDdB3mPnPjb:-N7HpdCPBjDdB3mPnPjc:b2uvn7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6b1edc5d14873e2776e554cd2b48d278df529e0/pkg/cmd/generate-logictest/main.go#L293)):*
> ```Go
> 	buildFileTpl := template.Must(template.New("source").Parse(buildFileTemplate))
> 
> 	// Populate tests in pkg/sql/logictest.
> ```

May I gently nudge you towards factoring out some common logic repeated throughout this file?

**Review by mgartner — COMMENTED** [review]
In the commit msg/PR description can you clarify how these changes affect developers' workflows. For example, to rewrite the logic test file `default`, I'd run `make test PKG='pkg/sql/logictest' TESTS='TestLogic/local/default' TESTFLAGS='--rewrite'`, or the `dev` equivalent. The equivalent would now be `make test PKG='./pkg/sql/logictest/tests/local' TESTS='TestLogic_local_default' TESTFLAGS='--rewrite'`, correct?

Another common development pattern is to run logic tests on files that are excluded from git tracking. For example, I'd run `make test PKG='pkg/sql/logictest' TESTS='TestLogic/local/__test` TESTFLAGS='--rewrite'` to rewrite the untracked file `__test`. Is there a way to accommodate run these types of files and avoid continually generating and reverting changes to the generated logic test files?

Also, is it possible to add a command like `dev generate logictest` which only regenerates the generated logic tests? If someone adds a new logic test file and forgets to regenerate the tests, CI will fail, correct?

> Reviewed 94 of 130 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84221#-:-N7HyZ1u3v1_5eQA2ZRg:bl7h3v7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rail, @rickystewart, and @rytaft)

**Comment by rickystewart** [comment]
>  If I'm being nit-picky, I think this would all be much easier to read if you split out a separate file and defined a bunch of smaller templates.

Done.

> May I gently nudge you towards factoring out some common logic repeated throughout this file?

Done.

> In the commit msg/PR description can you clarify how these changes affect developers' workflows

Done. Happy to provide other examples if the examples in the commit message/PR description are not sufficient for any reason.

> Another common development pattern is to run logic tests on files that are excluded from git tracking. For example, I'd run make test PKG='pkg/sql/logictest' TESTS='TestLogic/local/__test TESTFLAGS='--rewrite'to rewrite the untracked file__test`. Is there a way to accommodate run these types of files and avoid continually generating and reverting changes to the generated logic test files?

Files don't have to be tracked by Git to be picked up by `generate-logictest`, they just have to exist on-disk. But you do have to `dev generate logictest`/`dev generate bazel` so the generated test for that file can exist before you run the `--rewrite`. Not sure if there's a way we can improve this. I am considering having `dev testlogic` run `dev generate logictest` right before running the actual logic test so you can't possibly forget to do it.

> Also, is it possible to add a command like dev generate logictest which only regenerates the generated logic tests?

Done.

> If someone adds a new logic test file and forgets to regenerate the tests, CI will fail, correct?

Yes.

**Comment by rickystewart** [comment]
> I am considering having dev testlogic run dev generate logictest right before running the actual logic test so you can't possibly forget to do it.

I decided to go ahead and implement this. You can skip the generation with `dev testlogic --no-gen`.

**Comment by yuzefovich** [comment]
Kudos for this work, awesome stuff!

> Happy to provide other examples if the examples in the commit message/PR description are not sufficient for any reason.

I'm curious how invocations using some shortcuts change, e.g. would `dev` be smart enough to run something like `dev testlogic base --files=lookup_join --config=local`?

**Comment by mgartner** [comment]
Is it possible to leave the underscores in file names?

> I decided to go ahead and implement this. You can skip the generation with dev testlogic --no-gen, but I figure the logic tests are generally long-running enough that the couple seconds to make sure all the files are up-to-date is not a huge impact for anyone.

It would be nice if `dev test` did this too. Is that possible?

> Remove special characters -_@./ from the config name or filename. These characters can't be in Go function names.

If we put each config/filename combo in its own package, we could leave the names as-is. For example, to test the `int_size` file in the `local-vec-off` config you could run `./dev test pkg/sql/logictest/tests/local-vec-off/int_size` or `./dev test pkg/sql/logictest/tests/local-vec-off/int_size -f TestLogic`. This has the added benefit of removing the redundant configname in the test command. WDYT?

---

I'm getting failures when trying to run logic tests as mentioned in the commit message:

```
> ./dev test './pkg/sql/logictest/tests/local' -f 'TestLogic_local_intsize' --rewrite
$ bazel test pkg/sql/logictest/tests/local:all --nocache_test_results --test_env=GOTRACEBACK=all --test_env=COCKROACH_WORKSPACE=/Users/marcus/go/src/github.com/cockroachdb/cockroach --test_arg -rewrite --sandbox_writable_path=/Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/logictest/tests/local --test_filter=TestLogic_local_intsize --test_sharding_strategy=disabled --test_output errors
INFO: Invocation ID: 1a737b93-81e7-43b3-b40c-b5d15488a8ba
INFO: Analyzed 2 targets (0 packages loaded, 0 targets configured).
INFO: Found 1 target and 1 test target...
FAIL: //pkg/sql/logictest/tests/local:local_test (see /private/var/tmp/_bazel_marcus/61eb653382e9435773303080c4f9ae5d/execroot/com_github_cockroachdb_cockroach/bazel-out/darwin-fastbuild/testlogs/pkg/sql/logictest/tests/local/local_test/test.log)
INFO: From Testing //pkg/sql/logictest/tests/local:local_test:
==================== Test output for //pkg/sql/logictest/tests/local:local_test:
initialized metamorphic constant "kv.rangefeed.use_dedicated_connection_class.enabled" with value true
initialized metamorphic constant "mvcc-incremental-iter-tbi" with value false
initialized metamorphic constant "coldata-batch-size" with value 730
initialized metamorphic constant "default-batch-bytes-limit" with value 64854
initialized metamorphic constant "kv-batch-size" with value 1
initialized metamorphic constant "datum-row-converter-batch-size" with value 1
initialized metamorphic constant "row-container-rows-per-chunk-shift" with value 1
initialized metamorphic constant "zig-zag-joiner-batch-size" with value 1
initialized metamorphic constant "max-batch-size" with value 4706
initialized metamorphic constant "max-batch-byte-size" with value 8310279
initialized metamorphic constant "parallel-scan-result-threshold" with value 645
initialized metamorphic constant "merge-joiner-groups-buffer" with value 15
initialized metamorphic constant "ColIndexJoin-batch-size" with value 3348408
initialized metamorphic constant "ColIndexJoin-using-streamer-batch-size" with value 429477
initialized metamorphic constant "addsst-rewrite-concurrency" with value 12
initialized metamorphic constant "split-scans-right-for-stats-first" with value true
initialized metamorphic constant "raft-log-truncation-clearrange-threshold" with value 753527
initialized metamorphic constant "span-reuse-rate" with value 100
initialized metamorphic constant "mvcc-incremental-iter-tbi" with value false
initialized metamorphic constant "mvcc-value-disable-simple-encoding" with value true
initialized metamorphic constant "mvcc-max-iters-before-seek" with value 1
initialized metamorphic constant "coldata-batch-size" with value 1711
initialized metamorphic constant "default-batch-bytes-limit" with value 3564
initialized metamorphic constant "kv-batch-size" with value 1
initialized metamorphic constant "datum-row-converter-batch-size" with value 1
initialized metamorphic constant "inverted-joiner-batch-size" with value 1
initialized metamorphic constant "zig-zag-joiner-batch-size" with value 1
initialized metamorphic constant "max-batch-size" with value 2240
initialized metamorphic constant "max-batch-byte-size" with value 21451008
initialized metamorphic constant "parallel-scan-result-threshold" with value 5666
initialized metamorphic constant "spilling-queue-initial-len" with value 9
initialized metamorphic constant "ColIndexJoin-batch-size" with value 3382291
initialized metamorphic constant "resolve-membership-single-scan-enabled" with value false
initialized metamorphic constant "addsst-rewrite-concurrency" with value 0
initialized metamorphic constant "raft-log-truncation-clearrange-threshold" with value 112413
I220720 17:54:57.756241 1 (gostd) rand.go:176  [-] 1  random seed: -2668404844013794835
test logs left over in: /Users/marcus/go/src/github.com/cockroachdb/cockroach/tmp/_tmp/4f4538e87aad5009695571c72e3c0e28/logTestLogic_local_intsize1569136338
--- FAIL: TestLogic_local_intsize (0.50s)
    test_log_scope.go:79: test logs captured to: /Users/marcus/go/src/github.com/cockroachdb/cockroach/tmp/_tmp/4f4538e87aad5009695571c72e3c0e28/logTestLogic_local_intsize1569136338
    test_log_scope.go:80: use -show-logs to present logs inline
    logic.go:3577:
        /private/var/tmp/_bazel_marcus/61eb653382e9435773303080c4f9ae5d/sandbox/darwin-sandbox/54/execroot/com_github_cockroachdb_cockroach/bazel-out/darwin-fastbuild/bin/pkg/sql/logictest/tests/local/local_test_/local_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/int_size:178: error while processing
    logic.go:3577: open /private/var/tmp/_bazel_marcus/61eb653382e9435773303080c4f9ae5d/sandbox/darwin-sandbox/54/execroot/com_github_cockroachdb_cockroach/bazel-out/darwin-fastbuild/bin/pkg/sql/logictest/tests/local/local_test_/local_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/int_size: operation not permitted
    panic.go:642: -- test log scope end --
FAIL
I220720 17:54:58.265394 1 (gostd) testmain.go:688  [-] 1  Test //pkg/sql/logictest/tests/local:local_test exited with error code 1
================================================================================
INFO: Elapsed time: 1.555s, Critical Path: 1.16s
INFO: 2 processes: 1 internal, 1 darwin-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
//pkg/sql/logictest/tests/local:local_test                               FAILED in 0.8s
  /private/var/tmp/_bazel_marcus/61eb653382e9435773303080c4f9ae5d/execroot/com_github_cockroachdb_cockroach/bazel-out/darwin-fastbuild/testlogs/pkg/sql/logictest/tests/local/local_test/test.log

INFO: Build completed, 1 test FAILED, 2 total actions
ERROR: exit status 3
```

**Comment by rickystewart** [comment]
> I'm curious how invocations using some shortcuts change, e.g. would dev be smart enough to run something like dev testlogic base --files=lookup_join --config=local?

Yes, this works. It's a goal that the `dev testlogic` and `make testlogic` interfaces are not impacted by the change.

> Is it possible to leave the underscores in file names?

Probably, let me check on this.

> If we put each config/filename combo in its own package, we could leave the names as-is. 

There is a config with a `@` in the name, `local-v1.1@v1.0-noupgrade`, which keeps us from keeping the config name as-is in the package path. Is it possible to change this config name?

I could go either way on putting each config/filename combo in its own package. If that seems useful to people I can make the change.

 > This has the added benefit of removing the redundant configname in the test command.

The redundant configname in the test filter is already unnecessary, I just kept it there to make the test names kind of match up to what they were prior to the change. I can delete it already without affecting anything if that doesn't seem important to people.

> I'm getting failures when trying to run logic tests as mentioned in the commit message:

Ah, the problem is `dev testlogic` has some logic to make the testdata paths writable that is not mirrored in `dev test`. I'll take a pass to sync the two of them up.

**Comment by yuzefovich** [comment]
> There is a config with a @ in the name, `local-v1.1@v1.0-noupgrade`, which keeps us from keeping the config name as-is in the package path. Is it possible to change this config name?

Sure, #84747.

**Comment by rickystewart** [comment]
> If we put each config/filename combo in its own package, we could leave the names as-is.

The config names are now as-is in the package path, and the config name is now omitted from the test name to avoid the redundancy.  RE: the filename, we have to substitute any `-` and `.` in the filename for underscores, and remove any `/` that might be in the filename, but otherwise it stays as-is in the function name.

> It would be nice if dev test did this too. Is that possible?

Done.

> I'm getting failures when trying to run logic tests as mentioned in the commit message:

This should work with the latest version of the code. (If you try it locally do a `dev build dev` first.)

**Comment by rickystewart** [comment]
Whoops, this needs a tweak to the `dev generate bazel` logic, hold on.

**Review by rytaft — APPROVED** [review]
Thank you for doing this!

> Reviewed 89 of 208 files at r7, 43 of 44 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84221#-:-N7mKCT5BijGThyMB1Du:bff479j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @mgartner, @rail, and @rickystewart)

**Review by rail — APPROVED** [review]
This is HUGE! :)
I tried my best to review this, let's assume our CI catches if there is something wrong with this.
:shipit:

**Comment by yuzefovich** [comment]
@rickystewart we just merged the change (#85042) to remote all `-spec-planning` configs. Apologies for asking you to rebase yet again.

**Review by mgartner — APPROVED** [review]
Looks great!

**Comment by rickystewart** [comment]
TFTR everyone, I know this was a huge PR :) 

bors r=rytaft,rail,mgartner

**Comment by rickystewart** [comment]
bors r=rytaft,rail,mgartner

**Comment by rickystewart** [comment]
This'll make it through bors one day.

bors r=rytaft,rail,mgartner

**Comment by yuzefovich** [comment]
Let's make sure that this gets merged tonight :)

bors r=rytaft,rail,mgartner p=999

**Comment by yuzefovich** [comment]
bors r=rytaft,rail,mgartner p=999

**Pull request merged**
