### PR TITLE
coldata: generate vec.eg.go within the bazel sandbox

### LINKED ISSUE #57801: build: generate langgen+coldata generated files within the bazel sandbox
Inside `pkg/sql/opt/optgen/lang/BUILD.bazel` there are some pin files that we need to generate them within bazel sandbox:
```
       "expr.og.go",  # keep
        "operator.og.go",  # keep
```

Also inside `pkg/col/coldata/BUILD.bazel` we need start generating:

```
"vec.eg.go",  # keep
```

Basically want to do the exact same thing we did with the parser generated files. Generate them through bazel, ignore the checked-in file in the source tree.

### PR DESCRIPTION
**Pull request by alan-mas**
Fixes #57801. We apply the same treatment as 52c5f51.

Release note: None

Co-authored-by: irfan sharif <irfanmahmoudsharif@gmail.com>

### CODE REVIEW

**Comment by alan-mas** [comment]
I am not sure why now it is working without adding `-target` in command. Means that it is not asking for `vec_tmpl.go` so I took away that part from the `genrule`

**Comment by irfansharif** [comment]
We've seen this before in https://github.com/cockroachdb/cockroach/commit/52c5f51b81214f55606c43b049df142224cdd0e6, patched it up as needed.

**Comment by alan-mas** [comment]
Code looks good to me, but Teamcity is failing in step `[Step 4/6] Ensure generated code is up-to-date` due to:
```
[05:16:17][Ensure generated code is up-to-date] Some automatically generated code is not up to date.
[05:16:17][Ensure generated code is up-to-date] Run `make generate` to automatically regenerate these.
[05:16:17][Ensure generated code is up-to-date] Process exited with code 1
```
and also:
```
[05:16:40][Step 6/6] Process exited with code 1 (Step: Assert Workspace Clean (Command Line))
```
Apart from that code seems good to me ant thank you for that workaround patch

**Review by rickystewart — APPROVED** [review]

**Pull request merged**
