### PR TITLE
sql: add cpu nanos to insights tables

### PR DESCRIPTION
**Pull request by maryliag**
Part Of #87213

Add `cpu_sql_nanos` to
`crdb_internal.{cluster,nodes}_execution_insights` and `crdb_internal.{cluster,nodes}_txn_execution_insights`.

Release note: None

### CODE REVIEW

**Review by j82w — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96204)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/sql/crdb_internal.go` line 6957 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96204#-NN310NI4H8EAq1oHyGG:-NN310NJCZxt788_iVx_:b8ahv2y) ([raw file](https://github.com/cockroachdb/cockroach/blob/16c95487007fe98551bf93b389663547206794fb/pkg/sql/crdb_internal.go#L6957)):*
> ```Go
>   causes                     STRING[] NOT NULL,
>   stmt_execution_ids         STRING[] NOT NULL,
>   cpu_nanos                  INT8
> ```

Should this be `sql_cpu_nanos` or something more specific since it doesn't cover cpu time of the entire query like kv layer?
___
*[`pkg/sql/sqlstats/insights/integration/insights_test.go` line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96204#-NN31rJu22UDsHdfrZbR:-NN31rJu22UDsHdfrZbS:b2nu4fx) ([raw file](https://github.com/cockroachdb/cockroach/blob/16c95487007fe98551bf93b389663547206794fb/pkg/sql/sqlstats/insights/integration/insights_test.go#L146)):*
> ```Go
> 		var startInsights, endInsights time.Time
> 		var implicitTxn bool
> 		var cpuNanos int64
> ```

Add a check to verify cpu is greater than 0 and less than some large number that should be incorrect.

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96204)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`pkg/sql/crdb_internal.go` line 6957 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96204#-NN310NI4H8EAq1oHyGG:-NN32uAC8vR-cfU5V4Jy:b-2fiwie) ([raw file](https://github.com/cockroachdb/cockroach/blob/16c95487007fe98551bf93b389663547206794fb/pkg/sql/crdb_internal.go#L6957)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Should this be `sql_cpu_nanos` or something more specific since it doesn't cover cpu time of the entire query like kv layer?
</blockquote></details>

I'm keeping consistent with the name on the system/stats tables. We will be adding the remaining info to it, so better to keep like this to avoid a renaming in the future
___
*[`pkg/sql/sqlstats/insights/integration/insights_test.go` line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96204#-NN31rJu22UDsHdfrZbR:-NN33Q-N0AAZ6CbrCbL6:b-y6ftna) ([raw file](https://github.com/cockroachdb/cockroach/blob/16c95487007fe98551bf93b389663547206794fb/pkg/sql/sqlstats/insights/integration/insights_test.go#L146)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Add a check to verify cpu is greater than 0 and less than some large number that should be incorrect. 
</blockquote></details>

Do you have any suggestion about what the large number should be?

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96204)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`pkg/sql/sqlstats/insights/integration/insights_test.go` line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96204#-NN31rJu22UDsHdfrZbR:-NN36eADEEcvnLeQAu7H:bb4dygw) ([raw file](https://github.com/cockroachdb/cockroach/blob/16c95487007fe98551bf93b389663547206794fb/pkg/sql/sqlstats/insights/integration/insights_test.go#L146)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Do you have any suggestion about what the large number should be?
</blockquote></details>

Just realize this is for a pg_sleep, so I can use that as a base for the time here

**Comment by j82w** [comment]
*[`pkg/sql/sqlstats/insights/integration/insights_test.go` line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96204#-NN31rJu22UDsHdfrZbR:-NN36wIS4JO4cDo9h5CR:b-8xc096) ([raw file](https://github.com/cockroachdb/cockroach/blob/16c95487007fe98551bf93b389663547206794fb/pkg/sql/sqlstats/insights/integration/insights_test.go#L146)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Just realize this is for a pg_sleep, so I can use that as a base for the time here
</blockquote></details>

It shouldn't exceed the elapsed time which can be calculated from the `end_time-start_time`. I would add 10ms buffer to be on the safe.

**Comment by j82w** [comment]
*[`pkg/sql/sqlstats/insights/integration/insights_test.go` line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96204#-NN31rJu22UDsHdfrZbR:-NN37Wkw1_5CbSRk_fAB:byjwiwb) ([raw file](https://github.com/cockroachdb/cockroach/blob/16c95487007fe98551bf93b389663547206794fb/pkg/sql/sqlstats/insights/integration/insights_test.go#L146)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

It shouldn't exceed the elapsed time which can be calculated from the `end_time-start_time`. I would add 10ms buffer to be on the safe. 
</blockquote></details>

Is the actual sleep time included in the cpu time? That seems like possibly a bug if it is because I'm hoping it doesn't hold a cpu that entire time.

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96204)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`pkg/sql/sqlstats/insights/integration/insights_test.go` line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96204#-NN31rJu22UDsHdfrZbR:-NN38Pt-0AJS8bSN_Qnj:b-s9cvxv) ([raw file](https://github.com/cockroachdb/cockroach/blob/16c95487007fe98551bf93b389663547206794fb/pkg/sql/sqlstats/insights/integration/insights_test.go#L146)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Is the actual sleep time included in the cpu time? That seems like possibly a bug if it is because I'm hoping it doesn't hold a cpu that entire time. 
</blockquote></details>

is not included, which made me think that the cpu had to be smaller, but your idea is better. Will add the changes

**Comment by j82w** [comment]
*[`pkg/sql/crdb_internal.go` line 6957 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96204#-NN310NI4H8EAq1oHyGG:-NN38BGJ-BAJdTomibp_:b-i2trui) ([raw file](https://github.com/cockroachdb/cockroach/blob/16c95487007fe98551bf93b389663547206794fb/pkg/sql/crdb_internal.go#L6957)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I'm keeping consistent with the name on the system/stats tables. We will be adding the remaining info to it, so better to keep like this to avoid a renaming in the future
</blockquote></details>

Wouldn't it be better to keep the cpu stats separate to avoid ambiguity? For example if it just says 10.1seconds it would be very different issue if 10s in sql layer and .1s is kv layer vs .1s in sql and 10 sin kv.

**Comment by j82w** [comment]
*[`pkg/ccl/backupccl/testdata/backup-restore/alter-schedule/backup-options` line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96204#-NN3EbZp8NUodVa8YKjz:-NN3EbZp8NUodVa8YKk-:bqmyccj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada02b90c8e806cef32283b06edbe2a167f3b5dc/pkg/ccl/backupccl/testdata/backup-restore/alter-schedule/backup-options#L41)):*
> ```
> with schedules as (show schedules) select id, command->'backup_statement' from schedules where label='datatest' order by command->>'backup_type' asc;
> ----
> 835701674603675649 "BACKUP INTO 'nodelocal://1/example-schedule' WITH revision_history = false, detached"
> ```

Is this right? I don't see anything in the PR touching backup options.

**Review by j82w — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96204#-:-NN3_Jj-4cxTtSbzvOO7:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)

**Review by j82w — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96204)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag)

**Comment by maryliag** [comment]
TFTR!
bors r+

**Pull request merged**
