### PR TITLE
sql: adds unique constraint checks to SCRUB

### LINKED ISSUE #73632: sql: add unique constraint checks to SCRUB
The `SCRUB` tool checks that foreign key and check constraints on a table are valid and that there are no rows violating these constraints. It does not check for unique constraint violations, since in the past these constraints have been enforced by `UNIQUE` indexes. However, as of 21.1, this is no longer the case. For `REGIONAL BY ROW` tables, tables with implicitly partitioned `UNIQUE` indexes, and tables with `UNIQUE WITHOUT INDEX` constraints, the constraints are enforced by checks added by the optimizer when planning mutation queries. If there is a bug in the optimizer, as was the case in https://github.com/cockroachdb/cockroach/issues/73024, these constraints may be violated. `SCRUB` should be updated to check that these `UNIQUE` constraints are not violated.

Jira issue: CRDB-11674

### PR DESCRIPTION
**Pull request by rharding6373**
The SCRUB tool validates table constraints. Before this change, it could
only validate `CHECK` and foreign key constraints. This PR enhances
SCRUB to also validate tables that contain `PRIMARY KEY`, `UNIQUE`, or
the experimental `UNIQUE WITHOUT INDEX` keywords.

Fixes: #73632

Release note (sql change): This PR expands the capabilities of the experimental
SCRUB tool to include checking unique constraints for primary keys,
unique indexes, and unique columns without indexes. The usage and output
of SCRUB is unchanged, but if there is a unique constraint violation,
users will see the error message `unique_constraint_violation` for all
rows that violate the constraint, along with information about the row.

### CODE REVIEW

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78297)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @rytaft)

___
*[pkg/sql/scrub_test.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-Myo3s5EEsSFO5FlDeL8:-Myo3s5EEsSFO5FlDeL9:bv7fbuy) ([raw file](https://github.com/cockroachdb/cockroach/blob/060077d6b0113556cc717a6923cbe48840b3fca4/pkg/sql/scrub_test.go#L23)):*
> ```Go
> 
> 	"github.com/cockroachdb/cockroach/pkg/base"
> 	_ "github.com/cockroachdb/cockroach/pkg/ccl/partitionccl"
> ```

There is a restriction that 'OSS binaries do not include enterprise features', so I need to find a different workaround for testing with partitions. I may consider moving some SCRUB tests into ccl. Thoughts?

**Review by cucaroach — CHANGES_REQUESTED** [review]
My first run in with scrub but :LGTM:!   How did you think about how to test this, like could some of the testing be done more easily in logictest files I wonder?      I'm surprised the scrub stuff doesn't have its own package, its pkg/sql kinda too big, consider that a nit to *think* about a separate package.   Did you think about extending/subclassing sqlCheckConstraintCheckOperation instead of making a completely separate new operation type?   Seems like a lot of code duplication...

> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-:-MyxiIBuBLDU2B82brV4:b-pzvyeg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rharding6373 and @rytaft)

___
*[pkg/sql/scrub.go, line 446 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-Myxjp6U3Cfrm3yLhABX:-Myxjp6U3Cfrm3yLhABY:bwiyiu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/060077d6b0113556cc717a6923cbe48840b3fca4/pkg/sql/scrub.go#L446)):*
> ```Go
> 			))
> 		case descpb.ConstraintTypePK:
> 			fallthrough
> ```

I didn't know go had this!   Or at least if I did I forgot...
___
*[pkg/sql/scrub_unique_constraint.go, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-MyxmvosAeMQuMyTKGFG:-MyxmvosAeMQuMyTKGFH:bve3vnj) ([raw file](https://github.com/cockroachdb/cockroach/blob/060077d6b0113556cc717a6923cbe48840b3fca4/pkg/sql/scrub_unique_constraint.go#L124)):*
> ```Go
> (SELECT %[4]s FROM %[2]s.%[3]s GROUP BY %[4]s HAVING COUNT(*) > 1) AS tbl2 
> ON %[5]s
> %[6]s `,
> ```

I don't know what it is but I feel like there must be a better way, like the string is declared outside the function and some kind of named parameter replaced (ala python) is done?   Consider this a nit.
___
*[pkg/sql/scrub_test.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-Myo3s5EEsSFO5FlDeL8:-MyxgM_E8fkoyP7FNQ3z:bujoao3) ([raw file](https://github.com/cockroachdb/cockroach/blob/060077d6b0113556cc717a6923cbe48840b3fca4/pkg/sql/scrub_test.go#L23)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

There is a restriction that 'OSS binaries do not include enterprise features', so I need to find a different workaround for testing with partitions. I may consider moving some SCRUB tests into ccl. Thoughts?
</blockquote></details>

Seems like overkill to apply this to testing code but I do think the goal was to be able to rm -rf pkg/ccl and build oss but I remember hearing that that doesn't currently work (and I see there's already a kv ccl dependency in existing code above so...).    I don't think I've ever heard of a "testing" exception.  I think if eventually partitions will move from CCL to OSS (they will right) that this should be fine but that's above my pay grade.

**Review by rharding6373 — COMMENTED** [review]
I think that one of the main reasons why most scrub files are in pkg/sql is because scrub implements the planNode interface, and all other plan node implementations are in pkg/sql. There is a pkg/sql/scrub which contains error handling for scrub, and some other pieces may be able to move there in the future.

I did consider extending sqlCheckConstraintCheckOperation, but decided that these checks were different enough to merit their own operation. Maybe in the future as scrub is revived it might make sense to refactor, since the biggest difference between all the operators is the query that they run to perform their checks.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-:-MyyElI01ZZUd_SAl4P9:b-h0ryky)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @rytaft)

___
*[pkg/sql/scrub.go, line 446 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-Myxjp6U3Cfrm3yLhABX:-Myxsz7w4dtbL51FG7sc:b8mhogz) ([raw file](https://github.com/cockroachdb/cockroach/blob/060077d6b0113556cc717a6923cbe48840b3fca4/pkg/sql/scrub.go#L446)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

I didn't know go had this!   Or at least if I did I forgot...
</blockquote></details>

Can be useful!
___
*[pkg/sql/scrub_unique_constraint.go, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-MyxmvosAeMQuMyTKGFG:-MyxucMO5KxJ3Z6IIfVm:b-fhwkkl) ([raw file](https://github.com/cockroachdb/cockroach/blob/060077d6b0113556cc717a6923cbe48840b3fca4/pkg/sql/scrub_unique_constraint.go#L124)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

I don't know what it is but I feel like there must be a better way, like the string is declared outside the function and some kind of named parameter replaced (ala python) is done?   Consider this a nit.
</blockquote></details>

I refactored a bit so that we don't reuse args, which is probably more confusing than it's worth. Hope that helps.
___
*[pkg/sql/scrub_test.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-Myo3s5EEsSFO5FlDeL8:-MyyU4RI6nqVFNITQwRM:b107f9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/060077d6b0113556cc717a6923cbe48840b3fca4/pkg/sql/scrub_test.go#L23)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Seems like overkill to apply this to testing code but I do think the goal was to be able to rm -rf pkg/ccl and build oss but I remember hearing that that doesn't currently work (and I see there's already a kv ccl dependency in existing code above so...).    I don't think I've ever heard of a "testing" exception.  I think if eventually partitions will move from CCL to OSS (they will right) that this should be fine but that's above my pay grade.  
</blockquote></details>

I moved the affected tests into pkg/ccl/partitionccl, and the relevant test helpers into pkg/sql/scrub/scrubtestutils to maintain the separation.

**Review by rytaft — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78297)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @rharding6373)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-Mz7bT7zAn7OxKewGAVB):*
did you mean `CHECK` instead of `CONSTRAINT`?
___
*[-- commits, line 11 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-Mz7b_VL1fMvIRCp65yk):*
I don't think sql is a valid category. Maybe "sql change"?
___
*[pkg/sql/scrub.go, line 446 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-Myxjp6U3Cfrm3yLhABX:-Mz7cIfj-K4Wk57uUwf3:bpchdwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/060077d6b0113556cc717a6923cbe48840b3fca4/pkg/sql/scrub.go#L446)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Can be useful!
</blockquote></details>

In this case since there's no logic unique to pk, you could just put them on the same line:
`case descpb.ConstraintTypePK, descpb.ConstraintTypeUnique:`
___
*[pkg/sql/scrub_unique_constraint.go, line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-Mz7d00UEy2lCyViX3uc:-Mz7d00UEy2lCyViX3ud:b-uhcmpl) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c59971f7b5495d853e0e029cd8ce4ada263b3c/pkg/sql/scrub_unique_constraint.go#L74)):*
> ```Go
> 		// Partitioning columns are prepended to the index but are not part of the
> 		// unique constraint, so we ignore them.
> 		if constraint.Index.Partitioning.NumColumns > 0 {
> ```

This isn't quite right -- it's the implicit partitioning columns that we ignore, not all partitioning columns. I think this should be `NumImplicitColumns`, not `NumColumns` (here and below). 

Related: Maybe you should add a test that SCRUB *doesn't* return an error if we don't have implicit partitioning columns.
___
*[pkg/sql/scrub_unique_constraint.go, line 88 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-MzAY0Vo9hDaD6qUyph_:-MzAY0Vo9hDaD6qUypha:b-7a6gku) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c59971f7b5495d853e0e029cd8ce4ada263b3c/pkg/sql/scrub_unique_constraint.go#L88)):*
> ```Go
> 	ctx := params.ctx
> 	// Create a query of the form:
> 	// SELECT a,b,c FROM db.t AS tbl1 JOIN
> ```

why do you need a join? Why can't you just do the same as `duplicateRowQuery` (or even better, just call that function here)? https://github.com/cockroachdb/cockroach/blob/6b50953299b32480bd536279cd79243fcc85020e/pkg/sql/check.go#L326
___
*[pkg/sql/scrub/scrubtestutils/scrub_test_helper.go, line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-MzApmAE07Fct2pVhPWt:-MzApmAF8NNny32QKu2e:b-g2ptj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c59971f7b5495d853e0e029cd8ce4ada263b3c/pkg/sql/scrub/scrubtestutils/scrub_test_helper.go#L68)):*
> ```Go
> 	t.Helper()
> 
> 	// Run SCRUB and find the FOREIGN KEY violation created.
> ```

does it have to be foreign key?
___
*[pkg/ccl/partitionccl/scrub_test.go, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-MzAs6207pc4CC3RhX5N:-MzArief0y7qFzJBJSkt:bemysla) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c59971f7b5495d853e0e029cd8ce4ada263b3c/pkg/ccl/partitionccl/scrub_test.go#L29)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/util/log"
> )
> ```

Nice tests! Can you add another one for a partial unique index?

**Review by rytaft — COMMENTED** [review]
Sorry for the delay!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-:-MzAtoFE1xUpOVNpHP-w:b2c5wy4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @rharding6373)

**Review by rharding6373 — COMMENTED** [review]
TFTRs! I added a couple more tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-:-MzHg7tMBk2dXjNkugRo:bv39acr)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @rytaft)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-Mz7bT7zAn7OxKewGAVB):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

did you mean `CHECK` instead of `CONSTRAINT`?
</blockquote></details>

Done.
___
*[-- commits, line 11 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-Mz7b_VL1fMvIRCp65yk):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I don't think sql is a valid category. Maybe "sql change"?
</blockquote></details>

Done.
___
*[pkg/sql/scrub.go, line 446 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-Myxjp6U3Cfrm3yLhABX:-MzGmVF5-qqMSFJ50MiQ:b1g6yb0) ([raw file](https://github.com/cockroachdb/cockroach/blob/060077d6b0113556cc717a6923cbe48840b3fca4/pkg/sql/scrub.go#L446)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

In this case since there's no logic unique to pk, you could just put them on the same line:
`case descpb.ConstraintTypePK, descpb.ConstraintTypeUnique:`
</blockquote></details>

There's always a better way. Thanks!
___
*[pkg/sql/scrub_unique_constraint.go, line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-Mz7d00UEy2lCyViX3uc:-MzHZbMD6l7a7PHzJ9fU:b-pms4ot) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c59971f7b5495d853e0e029cd8ce4ada263b3c/pkg/sql/scrub_unique_constraint.go#L74)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This isn't quite right -- it's the implicit partitioning columns that we ignore, not all partitioning columns. I think this should be `NumImplicitColumns`, not `NumColumns` (here and below). 

Related: Maybe you should add a test that SCRUB *doesn't* return an error if we don't have implicit partitioning columns.
</blockquote></details>

Fixed and added a test.
___
*[pkg/sql/scrub_unique_constraint.go, line 88 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-MzAY0Vo9hDaD6qUyph_:-MzH_JJN164Snn9sY2xQ:b9mgllo) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c59971f7b5495d853e0e029cd8ce4ada263b3c/pkg/sql/scrub_unique_constraint.go#L88)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

why do you need a join? Why can't you just do the same as `duplicateRowQuery` (or even better, just call that function here)? https://github.com/cockroachdb/cockroach/blob/6b50953299b32480bd536279cd79243fcc85020e/pkg/sql/check.go#L326
</blockquote></details>

The join is to make sure we get the primary key so that we could fill the results according to the schema specified in https://www.cockroachlabs.com/docs/v21.2/experimental-features.html#check-for-constraint-violations-with-scrub, but I put all public columns in the query to align with the check constraint scrub output.

Now that we've added a predicate to the subquery for cases I could modify `duplicateRowQuery` to allow for a predicate and reuse it, if you have strong feelings about it.
___
*[pkg/sql/scrub/scrubtestutils/scrub_test_helper.go, line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-MzApmAE07Fct2pVhPWt:-MzGmsB0CTdv7Nlgmlji:ba1fu3t) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c59971f7b5495d853e0e029cd8ce4ada263b3c/pkg/sql/scrub/scrubtestutils/scrub_test_helper.go#L68)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

does it have to be foreign key?
</blockquote></details>

Copy paste after reuse. Fixed.
___
*[pkg/ccl/partitionccl/scrub_test.go, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-MzAs6207pc4CC3RhX5N:-MzH2Ud0BhbIRpfnZ4JT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c59971f7b5495d853e0e029cd8ce4ada263b3c/pkg/ccl/partitionccl/scrub_test.go#L29)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Nice tests! Can you add another one for a partial unique index?
</blockquote></details>

Done.

**Review by cucaroach — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78297)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @rytaft)

**Review by rytaft — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78297)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @rharding6373)

___
*[pkg/sql/scrub_unique_constraint.go, line 88 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-MzAY0Vo9hDaD6qUyph_:-MzV3pGB3QnXRGeNiafV:b-tnhcxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c59971f7b5495d853e0e029cd8ce4ada263b3c/pkg/sql/scrub_unique_constraint.go#L88)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

The join is to make sure we get the primary key so that we could fill the results according to the schema specified in https://www.cockroachlabs.com/docs/v21.2/experimental-features.html#check-for-constraint-violations-with-scrub, but I put all public columns in the query to align with the check constraint scrub output.

Now that we've added a predicate to the subquery for cases I could modify `duplicateRowQuery` to allow for a predicate and reuse it, if you have strong feelings about it.
</blockquote></details>

I think `duplicateRowQuery` does allow for a predicate. I think it would be good to reuse it if possible to limit duplication of logic and avoid bugs. For example, I think you're not accounting for NULL values here (would be good to add some tests with NULLs, too).
___
*[pkg/ccl/partitionccl/scrub_test.go, line 117 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-MzV7AulC5Aw_7SbCjVP:-MzV7AulC5Aw_7SbCjVQ:b-vcvv8d) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7333dc0b0eed525941f7ea4455f32bc2366d6e1/pkg/ccl/partitionccl/scrub_test.go#L117)):*
> ```Go
> 	id INT PRIMARY KEY,
> 	id2 INT UNIQUE
> ) PARTITION BY LIST (id) (
> ```

Note that this only partitions the primary index, not the secondary index. If you want to partition the secondary index as well, you'll need to do something like:
```
CREATE TABLE db.t (
	id INT PRIMARY KEY,
	id2 INT,
	UNIQUE (id2) PARTITION BY LIST (id) (
		 PARTITION one VALUES IN (1),
		 PARTITION two VALUES IN (2)
	)
) PARTITION BY LIST (id) (
	 PARTITION one VALUES IN (1),
	 PARTITION two VALUES IN (2)
);
```
___
*[pkg/ccl/partitionccl/scrub_test.go, line 148 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-MzV5rVh7FmIhuUlJqIu:-MzV5rVh7FmIhuUlJqIv:b-t8swrq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7333dc0b0eed525941f7ea4455f32bc2366d6e1/pkg/ccl/partitionccl/scrub_test.go#L148)):*
> ```Go
> 	}
> 
> 	// Run SCRUB
> ```

nit: end comment with a period
___
*[pkg/ccl/partitionccl/scrub_test.go, line 248 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-MzV6r9C2rXaVoxaGk8b:-MzV6r9C2rXaVoxaGk8c:b-t8swrq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7333dc0b0eed525941f7ea4455f32bc2366d6e1/pkg/ccl/partitionccl/scrub_test.go#L248)):*
> ```Go
> 	}
> 
> 	// Run SCRUB
> ```

nit: end comment with a period
___
*[pkg/ccl/partitionccl/scrub_test.go, line 254 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-MzV6i-g1aaMM86b-wnG:-MzV6i-g1aaMM86b-wnH:bbj4vwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7333dc0b0eed525941f7ea4455f32bc2366d6e1/pkg/ccl/partitionccl/scrub_test.go#L254)):*
> ```Go
> 			Database:     "db",
> 			Table:        "t",
> 			PrimaryKey:   "(1, 3)",
> ```

Why is this a tuple (was noticing this in the other tests too)?

**Review by rharding6373 — COMMENTED** [review]
Reviving this PR adding unique constrain checks for SCRUB. PTAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-:-N2YLlM39A2nHfadRiHt:b7xk38f)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @rytaft)

___
*[`pkg/sql/scrub_unique_constraint.go` line 88 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-MzAY0Vo9hDaD6qUyph_:-MzqQfZm-HCraokvMOJD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c59971f7b5495d853e0e029cd8ce4ada263b3c/pkg/sql/scrub_unique_constraint.go#L88)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think `duplicateRowQuery` does allow for a predicate. I think it would be good to reuse it if possible to limit duplication of logic and avoid bugs. For example, I think you're not accounting for NULL values here (would be good to add some tests with NULLs, too).
</blockquote></details>

Done.
___
*[`pkg/ccl/partitionccl/scrub_test.go` line 117 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-MzV7AulC5Aw_7SbCjVP:-N2XvVYp3c7VB7PDczA1:bjjkgm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7333dc0b0eed525941f7ea4455f32bc2366d6e1/pkg/ccl/partitionccl/scrub_test.go#L117)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Note that this only partitions the primary index, not the secondary index. If you want to partition the secondary index as well, you'll need to do something like:
```
CREATE TABLE db.t (
	id INT PRIMARY KEY,
	id2 INT,
	UNIQUE (id2) PARTITION BY LIST (id) (
		 PARTITION one VALUES IN (1),
		 PARTITION two VALUES IN (2)
	)
) PARTITION BY LIST (id) (
	 PARTITION one VALUES IN (1),
	 PARTITION two VALUES IN (2)
);
```
</blockquote></details>

Added a secondary index here, too.
___
*[`pkg/ccl/partitionccl/scrub_test.go` line 254 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-MzV6i-g1aaMM86b-wnG:-MzpebBTEZUUvm-GueCZ:blis3px) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7333dc0b0eed525941f7ea4455f32bc2366d6e1/pkg/ccl/partitionccl/scrub_test.go#L254)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Why is this a tuple (was noticing this in the other tests too)?
</blockquote></details>

The first element in the tuple is the partition by value, which is included as part of the primary key in the catalog.

**Review by rytaft — COMMENTED** [review]
Very close! Just one test case that needs a fix.

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-:-N2chH6ZC1Rv8T9LLyov:b-5h843u)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @rharding6373)

___
*[`pkg/ccl/partitionccl/scrub_test.go` line 117 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-MzV7AulC5Aw_7SbCjVP:-N2ceuPV2zHK1IQ0moUN:b-kfzf00) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7333dc0b0eed525941f7ea4455f32bc2366d6e1/pkg/ccl/partitionccl/scrub_test.go#L117)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Added a secondary index here, too.
</blockquote></details>

Sorry, I realize `UNIQUE (id2) PARTITION BY LIST (id) (` in my example above probably doesn't work. If I understand the purpose of this test, I think you want `UNIQUE (id, id2) PARTITION BY LIST (id) (`.

I'm still not sure of the purpose of `id3` here. I think what's happening is that you are actually constructing a corrupt index below (there are two rows with `id3=4`), but SCRUB doesn't error because you haven't set it up to check non-partitioned indexes. I don't think we care too much about using SCRUB for non-partitioned indexes, so I don't think we need to change its behavior, but we should probably change this test to focus on partitioned indexes.
___
*[`pkg/ccl/partitionccl/scrub_test.go` line 254 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-MzV6i-g1aaMM86b-wnG:-N2cgfI35f1oI3AUrwoT:b-dqvzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7333dc0b0eed525941f7ea4455f32bc2366d6e1/pkg/ccl/partitionccl/scrub_test.go#L254)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

The first element in the tuple is the partition by value, which is included as part of the primary key in the catalog.
</blockquote></details>

Ah right, thanks.
___
*[`pkg/ccl/partitionccl/scrub_test.go` line 202 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-N2cdSQ0CN7iEp6lqHwW:-N2cdSQ0CN7iEp6lqHwX:bogj2cu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9731e5cc055673248e54ac8f09662b259ca5479c/pkg/ccl/partitionccl/scrub_test.go#L202)):*
> ```Go
>     PARTITION id2_one VALUES IN (1),
>     PARTITION id2_two VALUES IN (2)
> 	    )
> ```

nit: formatting looks a bit weird

**Review by rharding6373 — COMMENTED** [review]
TFTR! PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-:-N2qxV_n6KdtLubvmt1P:b-qozhfh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @rytaft)

___
*[`pkg/ccl/partitionccl/scrub_test.go` line 117 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-MzV7AulC5Aw_7SbCjVP:-N2qwqnm8fnO3e5M4z1_:b-nxaxx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7333dc0b0eed525941f7ea4455f32bc2366d6e1/pkg/ccl/partitionccl/scrub_test.go#L117)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Sorry, I realize `UNIQUE (id2) PARTITION BY LIST (id) (` in my example above probably doesn't work. If I understand the purpose of this test, I think you want `UNIQUE (id, id2) PARTITION BY LIST (id) (`.

I'm still not sure of the purpose of `id3` here. I think what's happening is that you are actually constructing a corrupt index below (there are two rows with `id3=4`), but SCRUB doesn't error because you haven't set it up to check non-partitioned indexes. I don't think we care too much about using SCRUB for non-partitioned indexes, so I don't think we need to change its behavior, but we should probably change this test to focus on partitioned indexes.
</blockquote></details>

So, the purpose of this test is to test an explicitly partitioned secondary index, but we don't expect unique constraint violations even if one of its fields is also unique. PTAL and see if this test now makes sense. It's possible that it's still just corrupting indexes in a way that doesn't align with the goals of the test. Note that if I don't also update the primary index, it does find a unique constrain violation...

**Review by rytaft — APPROVED** [review]
:lgtm: Nice job getting this over the finish line.

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78297#-:-N2s_x_hCPGMVAkJOfa2:b-uefxgn)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach)

**Comment by rharding6373** [comment]
Thanks for all the reviews and help on this issue! The remaining test failures look like flakes unrelated to this PR.

bors r+

**Pull request merged**
