### PR TITLE
server: add a separate sampling loop for Go mem stats

### LINKED ISSUE #27775: storage: very high cgo/sec numbers
Running the `kv/splits/nodes=3` roachtest, I've found a number of instances of impossible cgo/sec numbers such as:

`I180720 01:02:18.254304 226 server/status/runtime.go:255  [n1] runtime stats: 10 GiB RSS, 460 goroutines, 8.6 GiB/432 MiB/9.7 GiB GO alloc/idle/total, 237 MiB/301 MiB CGO alloc/total, 315829496.07cgo/sec, 14.06/0.00 %(u/s)time, 0.00 %gc (0x)`

The first occurrence happened ~30m after the test started. For reference, 10s of thousands of cgo calls per second is more typical, sometimes rising to 1m/sec during bursts. Either something is busted with the stat, or we're doing something super expensive periodically that deserves to be tracked down.

### PR DESCRIPTION
**Pull request by petermattis**
`runtime.ReadMemStats` will block waiting for any running GC cycle to
finish. On a large heap this can take upwards of 10s which is in excess of
the default frequency that we sample runtime statistics (10s).

Fixes #27775

Release note: none

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29061)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/server/status/runtime.go, line 495 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/29061#-LKlcrJ48c8TQcao6PVM:-LKlcrJ5APeJ8gc37kpU:b-yelc6s) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a758a1f83c6870e4acdfb2c17ad4b354d3d6101/pkg/server/status/runtime.go#L495)):*
> ```Go
> 		diskStats.iopsInProgress,
> 		humanize.IBytes(deltaNet.BytesRecv), humanize.IBytes(deltaNet.BytesSent),
> 	)
> ```

I'm not sure if this is the correct calculation for read/write disk utilization. On a linux machine, I've seen values in excess of 100%. I'm also frequently seeing a value for write time that is near 100% which seems impossibly high.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29061)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/server/status/runtime.go, line 495 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/29061#-LKlcrJ48c8TQcao6PVM:-LKlemgi7TQL7hFwHzwW:bghn4vg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a758a1f83c6870e4acdfb2c17ad4b354d3d6101/pkg/server/status/runtime.go#L495)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm not sure if this is the correct calculation for read/write disk utilization. On a linux machine, I've seen values in excess of 100%. I'm also frequently seeing a value for write time that is near 100% which seems impossibly high. 
</blockquote></details>

Hmm, the % write time numbers seem to match up with iostat, so perhaps this is correct. I think the values greater than 100% were caused by grabbing the time before the stats. Should be fixed now.

**Review by nvb — APPROVED** [review]
:lgtm: thanks for tracking this down.

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29061#-:-LKrHfljA41-EBrVudCA:b-cy04rw)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/server/status/runtime.go, line 252 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29061#-LKrEl84DW3Gg_GOe8Tq:-LKrEl84DW3Gg_GOe8Tr:bupzzlw) ([raw file](https://github.com/cockroachdb/cockroach/blob/850b6506b1a13946961f1a09f012481df6b11060/pkg/server/status/runtime.go#L252)):*
> ```Go
> 	}
> 
> 	// Memory stats that are updated atomically by SampleMemStats
> ```

nit: missing period at the end.
___
*[pkg/server/status/runtime.go, line 382 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29061#-LKrF5fn5Nq0D1jaazoo:-LKrF5fn5Nq0D1jaazop:b-246o2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/850b6506b1a13946961f1a09f012481df6b11060/pkg/server/status/runtime.go#L382)):*
> ```Go
> 	// runtime.ReadMemStats(). The only way you can know that is by reading the
> 	// source.
> 	gc := &debug.GCStats{}
> ```

Escape analysis allows us to keep this on the stack, right?
___
*[pkg/server/status/runtime.go, line 497 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29061#-LKrFnhO1W4R0vXuaKil:-LKrFnhO1W4R0vXuaKim:bwr606n) ([raw file](https://github.com/cockroachdb/cockroach/blob/850b6506b1a13946961f1a09f012481df6b11060/pkg/server/status/runtime.go#L497)):*
> ```Go
> 	// to get accurate numbers, be sure to subtract. eg: ms.Sys - ms.HeapReleased
> 	// for current memory reserved.
> 	ms := &runtime.MemStats{}
> ```

Same question about keeping this on the stack.
___
*[pkg/server/status/runtime.go, line 502 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29061#-LKrFt3d4foytsTyVQAx:-LKrFt3d4foytsTyVQAy:b9dle1g) ([raw file](https://github.com/cockroachdb/cockroach/blob/850b6506b1a13946961f1a09f012481df6b11060/pkg/server/status/runtime.go#L502)):*
> ```Go
> 	goAllocated := ms.Alloc
> 	goTotal := ms.Sys - ms.HeapReleased
> 	atomic.StorePointer(&rsr.memStats, unsafe.Pointer(&memStats{
> ```

Why the unsafe pointer? Just for atomic access? In that case isn't an `atomic.Value` more idiomatic?

**Review by petermattis — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29061#-:-LKrWVxD8fd2Lqfgt7oK:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/server/status/runtime.go, line 382 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29061#-LKrF5fn5Nq0D1jaazoo:-LKrVpPGApwNcxi1Kzx8:bwjftq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/850b6506b1a13946961f1a09f012481df6b11060/pkg/server/status/runtime.go#L382)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Escape analysis allows us to keep this on the stack, right?
</blockquote></details>

No, this goes on the heap. And it did before too. This method is only called once every 10s. Avoiding an allocation doesn't seem worthwhile.
___
*[pkg/server/status/runtime.go, line 497 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29061#-LKrFnhO1W4R0vXuaKil:-LKrVyi5C8n9aLhPyNls:bam267n) ([raw file](https://github.com/cockroachdb/cockroach/blob/850b6506b1a13946961f1a09f012481df6b11060/pkg/server/status/runtime.go#L497)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Same question about keeping this on the stack.
</blockquote></details>

Same reply. This  method is only called once every 10s.
___
*[pkg/server/status/runtime.go, line 502 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29061#-LKrFt3d4foytsTyVQAx:-LKrW0ID4JMR7ZftFJ1N:bk73m0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/850b6506b1a13946961f1a09f012481df6b11060/pkg/server/status/runtime.go#L502)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why the unsafe pointer? Just for atomic access? In that case isn't an `atomic.Value` more idiomatic?
</blockquote></details>

`atomic.Value` allows storing an `interface{}`. If you're always storing the same pointer value, using `atomic.StorePointer` is "easier". Well, maybe not easier, but just as straightforward. I don't think it particularly matters much in this code. What seemed worth doing is to have the memory stats updated atomically as a unit, which either `atomic.StorePointer` or `atomic.Value` achieve.

**Review by tbg — APPROVED** [review]
Wasn't able to properly review this because Reviewable's doing something weird to the diffs- perhaps got confused by some rebase- but what I saw LGTM! Glad to get to see these numbers in the future.

> Reviewed 2 of 2 files at r7, 2 of 2 files at r8, 2 of 2 files at r9, 1 of 1 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29061#-:-LKuxv7V6_57wYlOBHj0:b-ird1o3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by petermattis** [comment]
bors r=nvanbenschoten,tschottdorf

**Comment by petermattis** [comment]
`TestGossipRestart` flake. Already on my plate to move that acceptance test to a roachtest.

bors r=nvanbenschoten,tschottdorf

**Comment by petermattis** [comment]
Failure claimed to be fixed by @benesh. Trying again.

bors r=nvanbenschoten,tschottdorf

**Comment by petermattis** [comment]
Other people are getting PRs merged. Why not this one?

bors r=nvanbenschoten,tschottdorf

**Comment by petermattis** [comment]
bors r=nvanbenschoten,tschottdorf

**Comment by petermattis** [comment]
Needs a backport (when I'm on better wifi).

**Pull request merged**
