### PR TITLE
ui next: Visualization Wrapper

### PR DESCRIPTION
**Pull request by mrtracy**
Extract the "visualization" wrapper from the LineGraph component. This wrapper
is responsible for diplaying a title, tooltip, and other standard information
around arbitrary visuals.

Commit also implements tooltips on the visualization wrapper.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6720)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[ui/next/app/components/visualization.tsx, line 7 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6720#-KHvJRfbXvx360lVllBG:-KHvJRfcnvC7Giuyva_I:2036519543) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa2a6665f59aa0bdca87eec7f16f2772eba35f1a/ui/next/app/components/visualization.tsx#L7)):*
> ```XML
>   text: string;
>   title: string;
>   position?: "right" | "left";
> ```

how come nullable?

---

*[ui/next/app/components/visualization.tsx, line 26 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6720#-KHvJUBOYowqZ0eVx-wt:-KHvJUBOYowqZ0eVx-wu:-469765787) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa2a6665f59aa0bdca87eec7f16f2772eba35f1a/ui/next/app/components/visualization.tsx#L26)):*
> ```XML
> interface VisualizationProps {
>   title: string;
>   tooltip?: string;
> ```

ditto

---

*[ui/next/app/components/visualization.tsx, line 27 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6720#-KHvJV31mvH8ry4zH7bE:-KHvJV31mvH8ry4zH7bF:-469765787) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa2a6665f59aa0bdca87eec7f16f2772eba35f1a/ui/next/app/components/visualization.tsx#L27)):*
> ```XML
>   title: string;
>   tooltip?: string;
>   stale?: boolean;
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6720)*

**Comment by maxlang** [comment]
:lgtm:

<details><summary><i>Previously, mrtracy wrote…</i></summary>
> #### ui next: Visualization Wrapper
> 
> Extract the "visualization" wrapper from the LineGraph component. This wrapper
> 
> is responsible for diplaying a title, tooltip, and other standard information
> 
> around arbitrary visuals.
> 
> 
> 
> Commit also implements tooltips on the visualization wrapper.
> 
> 
> </details>


---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[ui/next/app/components/visualization.tsx, line 7 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6720#-KHvJRfbXvx360lVllBG:-KHvVBTqCPCqg3g-TwZp:2147428625) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa2a6665f59aa0bdca87eec7f16f2772eba35f1a/ui/next/app/components/visualization.tsx#L7)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> how come nullable?</details>
If position isn't specified, it uses the default below ("right")

---

*[ui/next/app/components/visualization.tsx, line 27 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6720#-KHvJV31mvH8ry4zH7bE:-KHvV3OrD3wPTeXC0pEg:-837674083) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa2a6665f59aa0bdca87eec7f16f2772eba35f1a/ui/next/app/components/visualization.tsx#L27)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> ditto</details>
A visualization might not have a tooltip or might not be stale.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6720#-:-KHvVOYU-wpFPkIRWl0q:1417088721)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[ui/next/app/components/visualization.tsx, line 7 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6720#-KHvJRfbXvx360lVllBG:-KHvVxwXH4PNxOJ-KGRe:-1484922149) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa2a6665f59aa0bdca87eec7f16f2772eba35f1a/ui/next/app/components/visualization.tsx#L7)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> If position isn't specified, it uses the default below ("right")</details>
is that react magic?

---

*[ui/next/app/components/visualization.tsx, line 27 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6720#-KHvJV31mvH8ry4zH7bE:-KHvVraIYW1ctsT6zPEi:1292455120) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa2a6665f59aa0bdca87eec7f16f2772eba35f1a/ui/next/app/components/visualization.tsx#L27)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> A visualization might not have a tooltip or might not be stale.</details>
isn't "not stale" "false", rather than null?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6720)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[ui/next/app/components/visualization.tsx, line 7 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6720#-KHvJRfbXvx360lVllBG:-KHvW0srarkW5ZTgbjwZ:-191731715) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa2a6665f59aa0bdca87eec7f16f2772eba35f1a/ui/next/app/components/visualization.tsx#L7)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> is that react magic?</details>
and if it uses the default, why would it ever be null?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6720)*

**Comment by maxlang** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[ui/next/app/components/visualization.tsx, line 52 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6720#-KHvVfbjaLj5Cd1rCORn:-KHvVfbjaLj5Cd1rCORo:1087178705) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa2a6665f59aa0bdca87eec7f16f2772eba35f1a/ui/next/app/components/visualization.tsx#L52)):*
> ```XML
>             (tooltip || stale) ? <div className={`icon-${icon}`} /> : ""
>           }
>         </div>
> ```

This could probably also be written:

```
if (tooltip || stale) {
  <div className="viz-info-icon">
    ...
  </div>
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6720)*

**Comment by mrtracy** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[ui/next/app/components/visualization.tsx, line 7 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6720#-KHvJRfbXvx360lVllBG:-KHviXvjHE8iVzAGIcVr:576530781) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa2a6665f59aa0bdca87eec7f16f2772eba35f1a/ui/next/app/components/visualization.tsx#L7)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> and if it uses the default, why would it ever be null?</details>
It has to be nullable if the property optional when instantiating a component. If it's not nullable, Typescript will raise an error if you attempt to instantiate the component without specifying the property.  

Inside of a react component you can specify a "defaultProps" collection which provides default values for unset properties once the component is actually instantiated.

This is the standard way of providing default properties in React.

---

*[ui/next/app/components/visualization.tsx, line 26 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6720#-KHvJUBOYowqZ0eVx-wt:-KHvj58PM3cGOylsRadf:1162835178) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa2a6665f59aa0bdca87eec7f16f2772eba35f1a/ui/next/app/components/visualization.tsx#L26)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> ditto</details>
same as above.

---

*[ui/next/app/components/visualization.tsx, line 27 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6720#-KHvJV31mvH8ry4zH7bE:-KHvjXxHkHAlnX5Oigtm:-265209901) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa2a6665f59aa0bdca87eec7f16f2772eba35f1a/ui/next/app/components/visualization.tsx#L27)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> isn't "not stale" "false", rather than null?</details>
null (or rather, `undefined`) and false are both "false-like" values, and this is only ever used in the context of `if (stale)`.  If we needed to distinguish different false-like values, we could add a defaultProp, but that is not necessary in this case.

The tooltip is simply optional.

---

*[ui/next/app/components/visualization.tsx, line 52 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6720#-KHvVfbjaLj5Cd1rCORn:-KHvk1xPRkmPGmDT3_Ud:-292339568) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa2a6665f59aa0bdca87eec7f16f2772eba35f1a/ui/next/app/components/visualization.tsx#L52)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> This could probably also be written:
> 
> ```
> if (tooltip || stale) {
>   <div className="viz-info-icon">
>     ...
>   </div>
> }
> ```</details>
It can't be written that way in internal JSX - anything inside of the brackets needs to evaluate to a single object (thus the usage of the ternary operator).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6720)*

**Comment by mrtracy** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[ui/next/app/components/visualization.tsx, line 7 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6720#-KHvJRfbXvx360lVllBG:-KHvkpWIw9pWPWVU3PVf:1058161888) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa2a6665f59aa0bdca87eec7f16f2772eba35f1a/ui/next/app/components/visualization.tsx#L7)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> It has to be nullable if the property optional when instantiating a component. If it's not nullable, Typescript will raise an error if you attempt to instantiate the component without specifying the property.  
> 
> Inside of a react component you can specify a "defaultProps" collection which provides default values for unset properties once the component is actually instantiated.
> 
> This is the standard way of providing default properties in React.</details>
I used the term "instantiate" incorrectly once above.  Typescript raises an error if you attempt to *create* a component in typescript JSX without explicitly specifying the property. That is: 

```
<Visualization text="My Text" /> 
``` 

Would raise an error because "title" was not explicitly specified.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6720)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[ui/next/app/components/visualization.tsx, line 7 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6720#-KHvJRfbXvx360lVllBG:-KHw90JfuIN465yWxWod:-1650195092) ([raw file](https://github.com/cockroachdb/cockroach/blob/345fdf5857d31a41476bf4afe66a924be995cc48/ui/next/app/components/visualization.tsx#L7)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> I used the term "instantiate" incorrectly once above.  Typescript raises an error if you attempt to *create* a component in typescript JSX without explicitly specifying the property. That is: 
> 
> ```
> <Visualization text="My Text" /> 
> ``` 
> 
> Would raise an error because "title" was not explicitly specified.</details>
I see - so you have to make it optional even if there's a `defaultProps` and the property should never be null in practice. Bummer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6720)*

**Comment by mrtracy** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[ui/next/app/components/visualization.tsx, line 7 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6720#-KHvJRfbXvx360lVllBG:-KHwKuqx_iaFi103h_zC:2094153779) ([raw file](https://github.com/cockroachdb/cockroach/blob/345fdf5857d31a41476bf4afe66a924be995cc48/ui/next/app/components/visualization.tsx#L7)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I see - so you have to make it optional even if there's a `defaultProps` and the property should never be null in practice. Bummer.</details>
The issue is that they're using one type when really, there are two: the first type is the "Explicit Props", which are directly passed to createElement. The second type is the type of `this.props` of the created component, which has default values filled in and also has the "children" element.  

In the typescript interface, `ReactElement` is generic over the type of the "Explicit Props" (T), and `this.props` has type `T & { children?: any }`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6720)*

**Pull request merged**
